<dec f='halide/build-apps/abseil-cpp/absl/strings/internal/str_format/extension.h' l='154' type='9'/>
<use f='halide/build-apps/abseil-cpp/absl/strings/internal/str_format/extension.h' l='145' u='r' c='_ZN4absl14lts_2020_02_2519str_format_internal28FormatConversionCharFromCharEc'/>
<use f='halide/build-apps/abseil-cpp/absl/strings/internal/str_format/extension.h' l='176' c='_ZN4absl14lts_2020_02_2519str_format_internal25FormatConversionCharRadixENS1_20FormatConversionCharE'/>
<use f='halide/build-apps/abseil-cpp/absl/strings/internal/str_format/extension.h' l='190' c='_ZN4absl14lts_2020_02_2519str_format_internal27FormatConversionCharIsUpperENS1_20FormatConversionCharE'/>
<use f='halide/build-apps/abseil-cpp/absl/strings/internal/str_format/extension.h' l='218' c='_ZN4absl14lts_2020_02_2519str_format_internal30FormatConversionCharIsIntegralENS1_20FormatConversionCharE'/>
<use f='halide/build-apps/abseil-cpp/absl/strings/internal/str_format/extension.h' l='145' c='_ZN4absl14lts_2020_02_2519str_format_internal26FormatConversionCharToCharENS1_20FormatConversionCharE'/>
<use f='halide/build-apps/abseil-cpp/absl/strings/internal/str_format/extension.h' l='145' u='r' c='_ZN4absl14lts_2020_02_2519str_format_internal31FormatConversionCharToConvValueEc'/>
<use f='halide/build-apps/abseil-cpp/absl/strings/internal/str_format/parser.cc' l='35'/>
