<dec f='halide/halide-install/include/Halide.h' l='3791' type='14'/>
<use f='halide/halide-install/include/Halide.h' l='12000'/>
<use f='halide/halide-install/include/Halide.h' l='12975' c='_ZN6Halide8Internal15VariadicVisitor13dispatch_exprEPKNS0_12BaseExprNodeEDpOTL0__'/>
<use f='halide/halide-install/include/Halide.h' l='13051' c='_ZN6Halide8Internal15VariadicVisitor13dispatch_stmtEPKNS0_12BaseStmtNodeEDpOTL0__'/>
<use f='halide/halide-install/include/Halide.h' l='27771' u='r' c='_ZN6Halide8Internal9IRMatcher11commutativeENS0_10IRNodeTypeE'/>
<dec f='halide/build/include/Halide.h' l='3791' type='14'/>
<use f='halide/build/include/Halide.h' l='12000'/>
<use f='halide/build/include/Halide.h' l='12975' c='_ZN6Halide8Internal15VariadicVisitor13dispatch_exprEPKNS0_12BaseExprNodeEDpOTL0__'/>
<use f='halide/build/include/Halide.h' l='13051' c='_ZN6Halide8Internal15VariadicVisitor13dispatch_stmtEPKNS0_12BaseStmtNodeEDpOTL0__'/>
<use f='halide/build/include/Halide.h' l='27771' u='r' c='_ZN6Halide8Internal9IRMatcher11commutativeENS0_10IRNodeTypeE'/>
<dec f='halide/src/Expr.h' l='44' type='14'/>
<use f='halide/src/IR.h' l='108'/>
<use f='halide/src/IRVisitor.h' l='193' c='_ZN6Halide8Internal15VariadicVisitor13dispatch_exprEPKNS0_12BaseExprNodeEDpOTL0__'/>
<use f='halide/src/IRVisitor.h' l='269' c='_ZN6Halide8Internal15VariadicVisitor13dispatch_stmtEPKNS0_12BaseStmtNodeEDpOTL0__'/>
<use f='halide/src/IRMatch.h' l='657' u='r' c='_ZN6Halide8Internal9IRMatcher11commutativeENS0_10IRNodeTypeE'/>
<use f='halide/src/IRMatch.cpp' l='451' c='_ZN6Halide8Internal9IRMatcher12equal_helperERKNS0_12BaseExprNodeES4_'/>
