<dec f='halide/src/Pipeline.cpp' l='68' type='Halide::Module'/>
<use f='halide/src/Pipeline.cpp' l='82' u='w' c='_ZN6Halide16PipelineContents16invalidate_cacheEv'/>
<use f='halide/src/Pipeline.cpp' l='119' u='w' c='_ZN6Halide16PipelineContentsC1Ev'/>
<use f='halide/src/Pipeline.cpp' l='488' u='r' c='_ZN6Halide8Pipeline17compile_to_moduleERKSt6vectorINS_8ArgumentESaIS2_EERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKNS_6TargetENS_11LinkageTypeE'/>
<use f='halide/src/Pipeline.cpp' l='518' u='w' c='_ZN6Halide8Pipeline17compile_to_moduleERKSt6vectorINS_8ArgumentESaIS2_EERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKNS_6TargetENS_11LinkageTypeE'/>
<use f='halide/src/Pipeline.cpp' l='523' u='r' c='_ZN6Halide8Pipeline17compile_to_moduleERKSt6vectorINS_8ArgumentESaIS2_EERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKNS_6TargetENS_11LinkageTypeE'/>
<use f='halide/src/Pipeline.cpp' l='598' u='m' c='_ZN6Halide8Pipeline11compile_jitERKNS_6TargetE'/>
<use f='halide/src/Pipeline.cpp' l='617' u='m' c='_ZN6Halide8Pipeline11compile_jitERKNS_6TargetE'/>
<offset>64</offset>
<doc f='halide/src/Pipeline.cpp' l='67'>// Cached lowered stmt</doc>
