<dec f='halide/tools/halide_trace_config.h' l='83' type='int'/>
<use f='halide/tools/halide_trace_config.h' l='87' u='w' c='_ZN6Halide5Trace5PointC1Eii'/>
<use f='halide/tools/halide_trace_config.h' l='91' u='r' c='_ZN6Halide5TracelsERSoRKNS0_5PointE'/>
<use f='halide/tools/halide_trace_config.h' l='96' u='a' c='_ZN6Halide5TracersERSiRNS0_5PointE'/>
<use f='halide/tools/halide_trace_config.h' l='220' u='r' c='_ZN6Halide5Trace10FuncConfig10merge_fromERKS1_'/>
<use f='halide/tools/halide_trace_config.h' l='221' u='w' c='_ZN6Halide5Trace10FuncConfig10merge_fromERKS1_'/>
<use f='halide/tools/halide_trace_config.h' l='221' u='r' c='_ZN6Halide5Trace10FuncConfig10merge_fromERKS1_'/>
<use f='halide/util/HalideTraceViz.cpp' l='448' u='r' c='_ZN12_GLOBAL__N_112calc_2d_sizeERKSt6vectorIN6Halide5Trace5RangeESaIS3_EERKS0_INS2_5PointESaIS8_EEPS3_SD_iii'/>
<use f='halide/util/HalideTraceViz.cpp' l='452' u='r' c='_ZN12_GLOBAL__N_112calc_2d_sizeERKSt6vectorIN6Halide5Trace5RangeESaIS3_EERKS0_INS2_5PointESaIS8_EEPS3_SD_iii'/>
<use f='halide/util/HalideTraceViz.cpp' l='519' u='r' c='_ZN12_GLOBAL__N_114do_auto_layoutERKN6Halide5Trace12GlobalConfigERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERNS_8FuncInfoE'/>
<use f='halide/util/HalideTraceViz.cpp' l='519' u='r' c='_ZN12_GLOBAL__N_114do_auto_layoutERKN6Halide5Trace12GlobalConfigERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERNS_8FuncInfoE'/>
<use f='halide/util/HalideTraceViz.cpp' l='524' u='r' c='_ZN12_GLOBAL__N_114do_auto_layoutERKN6Halide5Trace12GlobalConfigERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERNS_8FuncInfoE'/>
<use f='halide/util/HalideTraceViz.cpp' l='525' u='r' c='_ZN12_GLOBAL__N_114do_auto_layoutERKN6Halide5Trace12GlobalConfigERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERNS_8FuncInfoE'/>
<use f='halide/util/HalideTraceViz.cpp' l='564' u='r' c='_ZN12_GLOBAL__N_114do_auto_layoutERKN6Halide5Trace12GlobalConfigERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERNS_8FuncInfoE'/>
<use f='halide/util/HalideTraceViz.cpp' l='564' u='r' c='_ZN12_GLOBAL__N_114do_auto_layoutERKN6Halide5Trace12GlobalConfigERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERNS_8FuncInfoE'/>
<use f='halide/util/HalideTraceViz.cpp' l='586' u='r' c='_ZN12_GLOBAL__N_114do_auto_layoutERKN6Halide5Trace12GlobalConfigERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERNS_8FuncInfoE'/>
<use f='halide/util/HalideTraceViz.cpp' l='587' u='w' c='_ZN12_GLOBAL__N_114do_auto_layoutERKN6Halide5Trace12GlobalConfigERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERNS_8FuncInfoE'/>
<use f='halide/util/HalideTraceViz.cpp' l='587' u='r' c='_ZN12_GLOBAL__N_114do_auto_layoutERKN6Halide5Trace12GlobalConfigERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERNS_8FuncInfoE'/>
<use f='halide/util/HalideTraceViz.cpp' l='587' u='r' c='_ZN12_GLOBAL__N_114do_auto_layoutERKN6Halide5Trace12GlobalConfigERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERNS_8FuncInfoE'/>
<use f='halide/util/HalideTraceViz.cpp' l='590' u='r' c='_ZN12_GLOBAL__N_114do_auto_layoutERKN6Halide5Trace12GlobalConfigERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERNS_8FuncInfoE'/>
<use f='halide/util/HalideTraceViz.cpp' l='595' u='r' c='_ZN12_GLOBAL__N_114do_auto_layoutERKN6Halide5Trace12GlobalConfigERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERNS_8FuncInfoE'/>
<use f='halide/util/HalideTraceViz.cpp' l='595' u='r' c='_ZN12_GLOBAL__N_114do_auto_layoutERKN6Halide5Trace12GlobalConfigERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERNS_8FuncInfoE'/>
<use f='halide/util/HalideTraceViz.cpp' l='723' u='w' c='_ZN12_GLOBAL__N_112process_argsEiPPcPNS_8VizStateE'/>
<use f='halide/util/HalideTraceViz.cpp' l='739' u='w' c='_ZN12_GLOBAL__N_112process_argsEiPPcPNS_8VizStateE'/>
<use f='halide/util/HalideTraceViz.cpp' l='743' u='w' c='_ZN12_GLOBAL__N_112process_argsEiPPcPNS_8VizStateE'/>
<use f='halide/util/HalideTraceViz.cpp' l='746' u='w' c='_ZN12_GLOBAL__N_112process_argsEiPPcPNS_8VizStateE'/>
<use f='halide/util/HalideTraceViz.cpp' l='799' u='r' c='_ZN12_GLOBAL__N_112process_argsEiPPcPNS_8VizStateE'/>
<use f='halide/util/HalideTraceViz.cpp' l='799' u='r' c='_ZN12_GLOBAL__N_112process_argsEiPPcPNS_8VizStateE'/>
<use f='halide/util/HalideTraceViz.cpp' l='847' u='w' c='_ZN12_GLOBAL__N_112process_argsEiPPcPNS_8VizStateE'/>
<use f='halide/util/HalideTraceViz.cpp' l='911' u='r' c='_ZN12_GLOBAL__N_17Surface13do_draw_pixelEfiijPj'/>
<use f='halide/util/HalideTraceViz.cpp' l='912' u='r' c='_ZN12_GLOBAL__N_17Surface13do_draw_pixelEfiijPj'/>
<use f='halide/util/HalideTraceViz.cpp' l='926' u='r' c='_ZN12_GLOBAL__N_17Surface9fill_rectEiiiijPj'/>
<use f='halide/util/HalideTraceViz.cpp' l='929' u='r' c='_ZN12_GLOBAL__N_17Surface9fill_rectEiiiijPj'/>
<use f='halide/util/HalideTraceViz.cpp' l='930' u='r' c='_ZN12_GLOBAL__N_17Surface9fill_rectEiiiijPj'/>
<use f='halide/util/HalideTraceViz.cpp' l='956' u='r' c='_ZN12_GLOBAL__N_17Surface19do_fill_realizationEPjjRKNS_8FuncInfoERK21halide_trace_packet_tiii'/>
<use f='halide/util/HalideTraceViz.cpp' l='966' u='r' c='_ZN12_GLOBAL__N_17Surface19do_fill_realizationEPjjRKNS_8FuncInfoERK21halide_trace_packet_tiii'/>
<use f='halide/util/HalideTraceViz.cpp' l='970' u='r' c='_ZN12_GLOBAL__N_17Surface19do_fill_realizationEPjjRKNS_8FuncInfoERK21halide_trace_packet_tiii'/>
<use f='halide/util/HalideTraceViz.cpp' l='990' u='r' c='_ZNK12_GLOBAL__N_17Surface11frame_elemsEv'/>
<use f='halide/util/HalideTraceViz.cpp' l='998' u='r' c='_ZNK12_GLOBAL__N_17Surface15get_image_pixelEii'/>
<use f='halide/util/HalideTraceViz.cpp' l='1021' u='r' c='_ZN12_GLOBAL__N_17Surface9draw_textERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKN6Halide5Trace5PointEjf'/>
<use f='halide/util/HalideTraceViz.cpp' l='1023' u='r' c='_ZN12_GLOBAL__N_17Surface9draw_textERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKN6Halide5Trace5PointEjf'/>
<use f='halide/util/HalideTraceViz.cpp' l='1027' u='r' c='_ZN12_GLOBAL__N_17Surface9draw_textERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKN6Halide5Trace5PointEjf'/>
<use f='halide/util/HalideTraceViz.cpp' l='1120' u='r' c='_ZN12_GLOBAL__N_13runEbSt8functionIFvPNS_8VizStateEEE'/>
<use f='halide/util/HalideTraceViz.cpp' l='1127' u='r' c='_ZN12_GLOBAL__N_13runEbSt8functionIFvPNS_8VizStateEEE'/>
<use f='halide/util/HalideTraceViz.cpp' l='1128' u='w' c='_ZN12_GLOBAL__N_13runEbSt8functionIFvPNS_8VizStateEEE'/>
<use f='halide/util/HalideTraceViz.cpp' l='1128' u='r' c='_ZN12_GLOBAL__N_13runEbSt8functionIFvPNS_8VizStateEEE'/>
<use f='halide/util/HalideTraceViz.cpp' l='1128' u='r' c='_ZN12_GLOBAL__N_13runEbSt8functionIFvPNS_8VizStateEEE'/>
<use f='halide/util/HalideTraceViz.cpp' l='1132' u='r' c='_ZN12_GLOBAL__N_13runEbSt8functionIFvPNS_8VizStateEEE'/>
<use f='halide/util/HalideTraceViz.cpp' l='1133' u='r' c='_ZN12_GLOBAL__N_13runEbSt8functionIFvPNS_8VizStateEEE'/>
<use f='halide/util/HalideTraceViz.cpp' l='1309' u='w' c='_ZN12_GLOBAL__N_13runEbSt8functionIFvPNS_8VizStateEEE'/>
<use f='halide/util/HalideTraceViz.cpp' l='1309' u='r' c='_ZN12_GLOBAL__N_13runEbSt8functionIFvPNS_8VizStateEEE'/>
<use f='halide/util/HalideTraceViz.cpp' l='1342' u='r' c='_ZN12_GLOBAL__N_13runEbSt8functionIFvPNS_8VizStateEEE'/>
<use f='halide/util/HalideTraceViz.cpp' l='1350' u='r' c='_ZN12_GLOBAL__N_13runEbSt8functionIFvPNS_8VizStateEEE'/>
<use f='halide/util/HalideTraceViz.cpp' l='1356' u='r' c='_ZN12_GLOBAL__N_13runEbSt8functionIFvPNS_8VizStateEEE'/>
<use f='halide/util/HalideTraceViz.cpp' l='1358' u='r' c='_ZN12_GLOBAL__N_13runEbSt8functionIFvPNS_8VizStateEEE'/>
<offset>0</offset>
