<dec f='halide/halide-install/share/tools/halide_trace_config.h' l='83' type='int'/>
<use f='halide/halide-install/share/tools/halide_trace_config.h' l='87' u='w' c='_ZN6Halide5Trace5PointC1Eii'/>
<use f='halide/halide-install/share/tools/halide_trace_config.h' l='91' u='r' c='_ZN6Halide5TracelsERSoRKNS0_5PointE'/>
<use f='halide/halide-install/share/tools/halide_trace_config.h' l='96' u='a' c='_ZN6Halide5TracersERSiRNS0_5PointE'/>
<use f='halide/halide-install/share/tools/halide_trace_config.h' l='223' u='r' c='_ZN6Halide5Trace10FuncConfig10merge_fromERKS1_'/>
<use f='halide/halide-install/share/tools/halide_trace_config.h' l='224' u='w' c='_ZN6Halide5Trace10FuncConfig10merge_fromERKS1_'/>
<use f='halide/halide-install/share/tools/halide_trace_config.h' l='224' u='r' c='_ZN6Halide5Trace10FuncConfig10merge_fromERKS1_'/>
<use f='halide/apps/bilateral_grid/bilateral_grid_generator.cpp' l='160' u='w' c='_ZN12_GLOBAL__N_113BilateralGrid8generateEv'/>
<use f='halide/apps/bilateral_grid/bilateral_grid_generator.cpp' l='173' u='w' c='_ZN12_GLOBAL__N_113BilateralGrid8generateEv'/>
<use f='halide/apps/bilateral_grid/bilateral_grid_generator.cpp' l='177' u='w' c='_ZN12_GLOBAL__N_113BilateralGrid8generateEv'/>
<use f='halide/apps/bilateral_grid/bilateral_grid_generator.cpp' l='181' u='w' c='_ZN12_GLOBAL__N_113BilateralGrid8generateEv'/>
<use f='halide/apps/bilateral_grid/bilateral_grid_generator.cpp' l='185' u='w' c='_ZN12_GLOBAL__N_113BilateralGrid8generateEv'/>
<offset>32</offset>
<use f='halide/apps/camera_pipe/camera_pipe_generator.cpp' l='199' u='w' c='_ZN12_GLOBAL__N_18Demosaic8scheduleEv'/>
<use f='halide/apps/local_laplacian/local_laplacian_generator.cpp' l='168' u='w' c='_ZN12_GLOBAL__N_114LocalLaplacian8generateEv'/>
<use f='halide/apps/local_laplacian/local_laplacian_generator.cpp' l='179' u='w' c='_ZN12_GLOBAL__N_114LocalLaplacian8generateEv'/>
<dec f='halide/tools/halide_trace_config.h' l='83' type='int'/>
<use f='halide/tools/halide_trace_config.h' l='87' u='w' c='_ZN6Halide5Trace5PointC1Eii'/>
<use f='halide/tools/halide_trace_config.h' l='91' u='r' c='_ZN6Halide5TracelsERSoRKNS0_5PointE'/>
<use f='halide/tools/halide_trace_config.h' l='96' u='a' c='_ZN6Halide5TracersERSiRNS0_5PointE'/>
<use f='halide/tools/halide_trace_config.h' l='223' u='r' c='_ZN6Halide5Trace10FuncConfig10merge_fromERKS1_'/>
<use f='halide/tools/halide_trace_config.h' l='224' u='w' c='_ZN6Halide5Trace10FuncConfig10merge_fromERKS1_'/>
<use f='halide/tools/halide_trace_config.h' l='224' u='r' c='_ZN6Halide5Trace10FuncConfig10merge_fromERKS1_'/>
<use f='halide/util/HalideTraceViz.cpp' l='449' u='r' c='_ZN12_GLOBAL__N_112calc_2d_sizeERKSt6vectorIN6Halide5Trace5RangeESaIS3_EERKS0_INS2_5PointESaIS8_EEPS3_SD_iii'/>
<use f='halide/util/HalideTraceViz.cpp' l='453' u='r' c='_ZN12_GLOBAL__N_112calc_2d_sizeERKSt6vectorIN6Halide5Trace5RangeESaIS3_EERKS0_INS2_5PointESaIS8_EEPS3_SD_iii'/>
<use f='halide/util/HalideTraceViz.cpp' l='520' u='r' c='_ZN12_GLOBAL__N_114do_auto_layoutERKN6Halide5Trace12GlobalConfigERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERNS_8FuncInfoE'/>
<use f='halide/util/HalideTraceViz.cpp' l='520' u='r' c='_ZN12_GLOBAL__N_114do_auto_layoutERKN6Halide5Trace12GlobalConfigERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERNS_8FuncInfoE'/>
<use f='halide/util/HalideTraceViz.cpp' l='565' u='r' c='_ZN12_GLOBAL__N_114do_auto_layoutERKN6Halide5Trace12GlobalConfigERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERNS_8FuncInfoE'/>
<use f='halide/util/HalideTraceViz.cpp' l='565' u='r' c='_ZN12_GLOBAL__N_114do_auto_layoutERKN6Halide5Trace12GlobalConfigERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERNS_8FuncInfoE'/>
<use f='halide/util/HalideTraceViz.cpp' l='586' u='r' c='_ZN12_GLOBAL__N_114do_auto_layoutERKN6Halide5Trace12GlobalConfigERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERNS_8FuncInfoE'/>
<use f='halide/util/HalideTraceViz.cpp' l='588' u='w' c='_ZN12_GLOBAL__N_114do_auto_layoutERKN6Halide5Trace12GlobalConfigERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERNS_8FuncInfoE'/>
<use f='halide/util/HalideTraceViz.cpp' l='588' u='r' c='_ZN12_GLOBAL__N_114do_auto_layoutERKN6Halide5Trace12GlobalConfigERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERNS_8FuncInfoE'/>
<use f='halide/util/HalideTraceViz.cpp' l='588' u='r' c='_ZN12_GLOBAL__N_114do_auto_layoutERKN6Halide5Trace12GlobalConfigERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERNS_8FuncInfoE'/>
<use f='halide/util/HalideTraceViz.cpp' l='590' u='r' c='_ZN12_GLOBAL__N_114do_auto_layoutERKN6Halide5Trace12GlobalConfigERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERNS_8FuncInfoE'/>
<use f='halide/util/HalideTraceViz.cpp' l='724' u='w' c='_ZN12_GLOBAL__N_112process_argsEiPPcPNS_8VizStateE'/>
<use f='halide/util/HalideTraceViz.cpp' l='740' u='w' c='_ZN12_GLOBAL__N_112process_argsEiPPcPNS_8VizStateE'/>
<use f='halide/util/HalideTraceViz.cpp' l='749' u='w' c='_ZN12_GLOBAL__N_112process_argsEiPPcPNS_8VizStateE'/>
<use f='halide/util/HalideTraceViz.cpp' l='752' u='w' c='_ZN12_GLOBAL__N_112process_argsEiPPcPNS_8VizStateE'/>
<use f='halide/util/HalideTraceViz.cpp' l='799' u='r' c='_ZN12_GLOBAL__N_112process_argsEiPPcPNS_8VizStateE'/>
<use f='halide/util/HalideTraceViz.cpp' l='799' u='r' c='_ZN12_GLOBAL__N_112process_argsEiPPcPNS_8VizStateE'/>
<use f='halide/util/HalideTraceViz.cpp' l='848' u='w' c='_ZN12_GLOBAL__N_112process_argsEiPPcPNS_8VizStateE'/>
<use f='halide/util/HalideTraceViz.cpp' l='928' u='r' c='_ZN12_GLOBAL__N_17Surface9fill_rectEiiiijPj'/>
<use f='halide/util/HalideTraceViz.cpp' l='957' u='r' c='_ZN12_GLOBAL__N_17Surface19do_fill_realizationEPjjRKNS_8FuncInfoERK21halide_trace_packet_tiii'/>
<use f='halide/util/HalideTraceViz.cpp' l='967' u='r' c='_ZN12_GLOBAL__N_17Surface19do_fill_realizationEPjjRKNS_8FuncInfoERK21halide_trace_packet_tiii'/>
<use f='halide/util/HalideTraceViz.cpp' l='971' u='r' c='_ZN12_GLOBAL__N_17Surface19do_fill_realizationEPjjRKNS_8FuncInfoERK21halide_trace_packet_tiii'/>
<use f='halide/util/HalideTraceViz.cpp' l='990' u='r' c='_ZNK12_GLOBAL__N_17Surface11frame_elemsEv'/>
<use f='halide/util/HalideTraceViz.cpp' l='1022' u='r' c='_ZN12_GLOBAL__N_17Surface9draw_textERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKN6Halide5Trace5PointEjf'/>
<use f='halide/util/HalideTraceViz.cpp' l='1024' u='r' c='_ZN12_GLOBAL__N_17Surface9draw_textERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKN6Halide5Trace5PointEjf'/>
<use f='halide/util/HalideTraceViz.cpp' l='1120' u='r' c='_ZN12_GLOBAL__N_13runEbSt8functionIFvPNS_8VizStateEEE'/>
<use f='halide/util/HalideTraceViz.cpp' l='1127' u='r' c='_ZN12_GLOBAL__N_13runEbSt8functionIFvPNS_8VizStateEEE'/>
<use f='halide/util/HalideTraceViz.cpp' l='1129' u='w' c='_ZN12_GLOBAL__N_13runEbSt8functionIFvPNS_8VizStateEEE'/>
<use f='halide/util/HalideTraceViz.cpp' l='1129' u='r' c='_ZN12_GLOBAL__N_13runEbSt8functionIFvPNS_8VizStateEEE'/>
<use f='halide/util/HalideTraceViz.cpp' l='1129' u='r' c='_ZN12_GLOBAL__N_13runEbSt8functionIFvPNS_8VizStateEEE'/>
<use f='halide/util/HalideTraceViz.cpp' l='1132' u='r' c='_ZN12_GLOBAL__N_13runEbSt8functionIFvPNS_8VizStateEEE'/>
<use f='halide/util/HalideTraceViz.cpp' l='1133' u='r' c='_ZN12_GLOBAL__N_13runEbSt8functionIFvPNS_8VizStateEEE'/>
<use f='halide/util/HalideTraceViz.cpp' l='1310' u='w' c='_ZN12_GLOBAL__N_13runEbSt8functionIFvPNS_8VizStateEEE'/>
<use f='halide/util/HalideTraceViz.cpp' l='1310' u='r' c='_ZN12_GLOBAL__N_13runEbSt8functionIFvPNS_8VizStateEEE'/>
<use f='halide/util/HalideTraceViz.cpp' l='1343' u='r' c='_ZN12_GLOBAL__N_13runEbSt8functionIFvPNS_8VizStateEEE'/>
<use f='halide/util/HalideTraceViz.cpp' l='1351' u='r' c='_ZN12_GLOBAL__N_13runEbSt8functionIFvPNS_8VizStateEEE'/>
<use f='halide/util/HalideTraceViz.cpp' l='1355' u='r' c='_ZN12_GLOBAL__N_13runEbSt8functionIFvPNS_8VizStateEEE'/>
<use f='halide/util/HalideTraceViz.cpp' l='1357' u='r' c='_ZN12_GLOBAL__N_13runEbSt8functionIFvPNS_8VizStateEEE'/>
<offset>32</offset>
