<def f='halide/halide-install/include/Halide.h' l='5017' ll='5028'/>
<use f='halide/halide-install/include/Halide.h' l='5017'/>
<use f='halide/halide-install/include/Halide.h' l='5129' c='_ZN6Halide6TargetC1ENS0_2OSENS0_4ArchEiRKSt6vectorINS0_7FeatureESaIS4_EE'/>
<def f='halide/build/include/Halide.h' l='5017' ll='5028'/>
<use f='halide/build/include/Halide.h' l='5017'/>
<use f='halide/build/include/Halide.h' l='5129' c='_ZN6Halide6TargetC1ENS0_2OSENS0_4ArchEiRKSt6vectorINS0_7FeatureESaIS4_EE'/>
<use f='halide/python_bindings/src/PyEnums.cpp' l='63' c='_ZN6Halide14PythonBindings12define_enumsERN8pybind117module_E'/>
<use f='halide/python_bindings/src/PyTarget.cpp' l='26' c='_ZN6Halide14PythonBindings13define_targetERN8pybind117module_E'/>
<use f='halide/python_bindings/src/PyTarget.cpp' l='27' c='_ZN6Halide14PythonBindings13define_targetERN8pybind117module_E'/>
<def f='halide/src/Target.h' l='23' ll='34'/>
<use f='halide/src/Target.h' l='23'/>
<use f='halide/src/Target.h' l='135' c='_ZN6Halide6TargetC1ENS0_2OSENS0_4ArchEiRKSt6vectorINS0_7FeatureESaIS4_EE'/>
<use f='halide/src/Target.cpp' l='66' c='_ZN6Halide12_GLOBAL__N_121calculate_host_targetEv'/>
<use f='halide/src/Target.cpp' l='270'/>
<use f='halide/src/Target.cpp' l='282' c='_ZN6Halide12_GLOBAL__N_19lookup_osERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERNS_6Target2OSE'/>
