<def f='halide/build/include/Halide.h' l='31622' ll='31627'/>
<use f='halide/build/include/Halide.h' l='31633'/>
<use f='halide/build/include/Halide.h' l='31652' c='_ZN6Halide8Internal10ThreadPool13worker_threadEv'/>
<use f='halide/build/include/Halide.h' l='31701' c='_ZN6Halide8Internal10ThreadPool5asyncETL0__DpTL0_0_'/>
<mbr r='Halide::Internal::ThreadPool::Job::func' t='std::function&lt;T ()&gt;'/>
<mbr r='Halide::Internal::ThreadPool::Job::result' t='std::promise&lt;T&gt;'/>
<fun r='_ZN6Halide8Internal10ThreadPool3Job12run_unlockedERSt11unique_lockISt5mutexE'/>
<fun r='_ZN6Halide8Internal10ThreadPool3Job12run_unlockedERSt11unique_lockISt5mutexE'/>
<fun r='_ZN6Halide8Internal10ThreadPool3Job12run_unlockedERSt11unique_lockISt5mutexE'/>
