<dec f='halide/build/include/Halide.h' l='5075' type='23'/>
<use f='halide/python_bindings/src/PyEnums.cpp' l='105' u='r' c='_ZN6Halide14PythonBindings12define_enumsERN8pybind117module_E'/>
<dec f='halide/src/Target.h' l='81' type='23'/>
<use f='halide/src/CodeGen_C.cpp' l='421' u='r' c='_ZN6Halide8Internal9CodeGen_CD1Ev'/>
<use f='halide/src/DeviceInterface.cpp' l='147' u='r' c='_ZN6Halide33get_default_device_api_for_targetERKNS_6TargetE'/>
<use f='halide/src/JITModule.cpp' l='665' u='r' c='_ZN6Halide8Internal12_GLOBAL__N_111make_moduleEPN4llvm6ModuleENS_6TargetENS1_11RuntimeKindERKSt6vectorINS0_9JITModuleESaIS8_EEb'/>
<use f='halide/src/JITModule.cpp' l='675' u='r' c='_ZN6Halide8Internal12_GLOBAL__N_111make_moduleEPN4llvm6ModuleENS_6TargetENS1_11RuntimeKindERKSt6vectorINS0_9JITModuleESaIS8_EEb'/>
<use f='halide/src/JITModule.cpp' l='679' u='r' c='_ZN6Halide8Internal12_GLOBAL__N_111make_moduleEPN4llvm6ModuleENS_6TargetENS1_11RuntimeKindERKSt6vectorINS0_9JITModuleESaIS8_EEb'/>
<use f='halide/src/JITModule.cpp' l='842' u='r' c='_ZN6Halide8Internal16JITSharedRuntime3getEPN4llvm6ModuleERKNS_6TargetEb'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='1121' u='r' c='_ZN6Halide8Internal29get_initial_module_for_targetENS_6TargetEPN4llvm11LLVMContextEbb'/>
<use f='halide/src/OffloadGPULoops.cpp' l='261' u='r' c='_ZN6Halide8Internal12_GLOBAL__N_116InjectGpuOffloadC1ERKNS_6TargetE'/>
<use f='halide/src/Target.cpp' l='335' u='r'/>
<use f='halide/src/Target.cpp' l='738' u='r' c='_ZNK6Halide6Target15has_gpu_featureEv'/>
<use f='halide/src/Target.cpp' l='781' u='r' c='_ZNK6Halide6Target13supports_typeERKNS_4TypeE'/>
<use f='halide/src/Target.cpp' l='854' u='r' c='_ZNK6Halide6Target23get_required_device_apiEv'/>
<use f='halide/src/Target.cpp' l='868' u='r' c='_ZN6Halide29target_feature_for_device_apiENS_9DeviceAPIE'/>
<use f='halide/src/Target.cpp' l='950' u='r' c='_ZN6Halide6Target29get_runtime_compatible_targetERKS0_RS0_'/>
<use f='halide/test/generator/define_extern_opencl_generator.cpp' l='27' u='r' c='_ZN12_GLOBAL__N_124DefineExternOpenCLOutput8scheduleEv'/>
<use f='halide/test/generator/gpu_texture_generator.cpp' l='17' u='r' c='_ZN12_GLOBAL__N_110GpuTexture8generateEv'/>
<use f='halide/tutorial/lesson_12_using_the_gpu.cpp' l='297' u='a' c='_Z15find_gpu_targetv'/>
<use f='halide/tutorial/lesson_12_using_the_gpu.cpp' l='303' u='a' c='_Z15find_gpu_targetv'/>
<use f='halide/tutorial/lesson_19_wrapper_funcs.cpp' l='297' u='r' c='main'/>
