<dec f='halide/build/include/Halide.h' l='5028' type='enum OS'/>
<use f='halide/build/include/Halide.h' l='5130' u='w' c='_ZN6Halide6TargetC1ENS0_2OSENS0_4ArchEiRKSt6vectorINS0_7FeatureESaIS4_EE'/>
<use f='halide/build/include/Halide.h' l='5216' u='r' c='_ZNK6Halide6TargeteqERKS0_'/>
<use f='halide/build/include/Halide.h' l='5216' u='r' c='_ZNK6Halide6TargeteqERKS0_'/>
<use f='halide/build/include/Halide.h' l='13578' u='r' c='_ZNK6Halide12ExternalCode17is_for_cpu_targetERKNS_6TargetE'/>
<use f='halide/build/include/Halide.h' l='13578' u='r' c='_ZNK6Halide12ExternalCode17is_for_cpu_targetERKNS_6TargetE'/>
<use f='halide/build/include/Halide.h' l='13578' u='r' c='_ZNK6Halide12ExternalCode17is_for_cpu_targetERKNS_6TargetE'/>
<offset>0</offset>
<use f='halide/python_bindings/src/PyTarget.cpp' l='32' u='a' c='_ZN6Halide14PythonBindings13define_targetERN8pybind117module_E'/>
<dec f='halide/src/Target.h' l='34' type='enum OS'/>
<use f='halide/src/Target.h' l='136' u='w' c='_ZN6Halide6TargetC1ENS0_2OSENS0_4ArchEiRKSt6vectorINS0_7FeatureESaIS4_EE'/>
<use f='halide/src/Target.h' l='222' u='r' c='_ZNK6Halide6TargeteqERKS0_'/>
<use f='halide/src/Target.h' l='222' u='r' c='_ZNK6Halide6TargeteqERKS0_'/>
<use f='halide/src/ExternalCode.h' l='105' u='r' c='_ZNK6Halide12ExternalCode17is_for_cpu_targetERKNS_6TargetE'/>
<use f='halide/src/ExternalCode.h' l='105' u='r' c='_ZNK6Halide12ExternalCode17is_for_cpu_targetERKNS_6TargetE'/>
<use f='halide/src/ExternalCode.h' l='105' u='r' c='_ZNK6Halide12ExternalCode17is_for_cpu_targetERKNS_6TargetE'/>
<offset>0</offset>
<use f='halide/src/CPlusPlusMangle.cpp' l='349' u='r' c='_ZN6Halide8Internal18ItaniumABIMangling26simple_type_to_mangle_charERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKNS_6TargetE'/>
<use f='halide/src/CPlusPlusMangle.cpp' l='350' u='r' c='_ZN6Halide8Internal18ItaniumABIMangling26simple_type_to_mangle_charERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKNS_6TargetE'/>
<use f='halide/src/CPlusPlusMangle.cpp' l='357' u='r' c='_ZN6Halide8Internal18ItaniumABIMangling26simple_type_to_mangle_charERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKNS_6TargetE'/>
<use f='halide/src/CPlusPlusMangle.cpp' l='358' u='r' c='_ZN6Halide8Internal18ItaniumABIMangling26simple_type_to_mangle_charERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKNS_6TargetE'/>
<use f='halide/src/CPlusPlusMangle.cpp' l='538' u='r' c='_ZN6Halide8Internal18ItaniumABIMangling11mangle_typeB5cxx11ERKNS_4TypeERKNS_6TargetERNS1_12PrevPrefixesE'/>
<use f='halide/src/CPlusPlusMangle.cpp' l='539' u='r' c='_ZN6Halide8Internal18ItaniumABIMangling11mangle_typeB5cxx11ERKNS_4TypeERKNS_6TargetERNS1_12PrevPrefixesE'/>
<use f='halide/src/CPlusPlusMangle.cpp' l='559' u='r' c='_ZN6Halide8Internal18ItaniumABIMangling11mangle_typeB5cxx11ERKNS_4TypeERKNS_6TargetERNS1_12PrevPrefixesE'/>
<use f='halide/src/CPlusPlusMangle.cpp' l='560' u='r' c='_ZN6Halide8Internal18ItaniumABIMangling11mangle_typeB5cxx11ERKNS_4TypeERKNS_6TargetERNS1_12PrevPrefixesE'/>
<use f='halide/src/CPlusPlusMangle.cpp' l='609' u='r' c='_ZN6Halide8Internal31cplusplus_function_mangled_nameERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKSt6vectorIS6_SaIS6_EENS_4TypeERKS9_INS_1813871357'/>
<use f='halide/src/CPlusPlusMangle.cpp' l='1071' u='r' c='_ZN6Halide8Internal21cplusplus_mangle_testEv'/>
<use f='halide/src/CPlusPlusMangle.cpp' l='1087' u='r' c='_ZN6Halide8Internal21cplusplus_mangle_testEv'/>
<use f='halide/src/CodeGen_ARM.cpp' l='1277' u='r' c='_ZNK6Halide8Internal12_GLOBAL__N_111CodeGen_ARM4mcpuB5cxx11Ev'/>
<use f='halide/src/CodeGen_ARM.cpp' l='1279' u='r' c='_ZNK6Halide8Internal12_GLOBAL__N_111CodeGen_ARM4mcpuB5cxx11Ev'/>
<use f='halide/src/CodeGen_ARM.cpp' l='1319' u='r' c='_ZNK6Halide8Internal12_GLOBAL__N_111CodeGen_ARM6mattrsB5cxx11Ev'/>
<use f='halide/src/CodeGen_ARM.cpp' l='1319' u='r' c='_ZNK6Halide8Internal12_GLOBAL__N_111CodeGen_ARM6mattrsB5cxx11Ev'/>
<use f='halide/src/CodeGen_ARM.cpp' l='1332' u='r' c='_ZNK6Halide8Internal12_GLOBAL__N_111CodeGen_ARM18use_soft_float_abiEv'/>
<use f='halide/src/CodeGen_ARM.cpp' l='1333' u='r' c='_ZNK6Halide8Internal12_GLOBAL__N_111CodeGen_ARM18use_soft_float_abiEv'/>
<use f='halide/src/CodeGen_C.cpp' l='389' u='r' c='_ZN6Halide8Internal9CodeGen_CD1Ev'/>
<use f='halide/src/CodeGen_OpenGLCompute_Dev.cpp' l='695' u='r' c='_ZN6Halide8Internal12_GLOBAL__N_123CodeGen_OpenGLCompute_C10add_kernelERKNS0_4StmtERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKSt6vectorIN9276024'/>
<use f='halide/src/CodeGen_WebAssembly.cpp' l='293' u='r' c='_ZNK6Halide8Internal12_GLOBAL__N_119CodeGen_WebAssembly6mattrsB5cxx11Ev'/>
<use f='halide/src/HexagonOffload.cpp' l='964' u='w' c='_ZN6Halide8Internal18inject_hexagon_rpcENS0_4StmtERKNS_6TargetERNS_6ModuleE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='291' u='r' c='_ZN6Halide12_GLOBAL__N_126get_data_layout_for_targetENS_6TargetE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='293' u='r' c='_ZN6Halide12_GLOBAL__N_126get_data_layout_for_targetENS_6TargetE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='295' u='r' c='_ZN6Halide12_GLOBAL__N_126get_data_layout_for_targetENS_6TargetE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='297' u='r' c='_ZN6Halide12_GLOBAL__N_126get_data_layout_for_targetENS_6TargetE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='304' u='r' c='_ZN6Halide12_GLOBAL__N_126get_data_layout_for_targetENS_6TargetE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='306' u='r' c='_ZN6Halide12_GLOBAL__N_126get_data_layout_for_targetENS_6TargetE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='308' u='r' c='_ZN6Halide12_GLOBAL__N_126get_data_layout_for_targetENS_6TargetE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='310' u='r' c='_ZN6Halide12_GLOBAL__N_126get_data_layout_for_targetENS_6TargetE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='318' u='r' c='_ZN6Halide12_GLOBAL__N_126get_data_layout_for_targetENS_6TargetE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='324' u='r' c='_ZN6Halide12_GLOBAL__N_126get_data_layout_for_targetENS_6TargetE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='326' u='r' c='_ZN6Halide12_GLOBAL__N_126get_data_layout_for_targetENS_6TargetE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='328' u='r' c='_ZN6Halide12_GLOBAL__N_126get_data_layout_for_targetENS_6TargetE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='384' u='r' c='_ZN6Halide8Internal21get_triple_for_targetERKNS_6TargetE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='387' u='r' c='_ZN6Halide8Internal21get_triple_for_targetERKNS_6TargetE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='390' u='r' c='_ZN6Halide8Internal21get_triple_for_targetERKNS_6TargetE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='398' u='r' c='_ZN6Halide8Internal21get_triple_for_targetERKNS_6TargetE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='401' u='r' c='_ZN6Halide8Internal21get_triple_for_targetERKNS_6TargetE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='405' u='r' c='_ZN6Halide8Internal21get_triple_for_targetERKNS_6TargetE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='424' u='r' c='_ZN6Halide8Internal21get_triple_for_targetERKNS_6TargetE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='427' u='r' c='_ZN6Halide8Internal21get_triple_for_targetERKNS_6TargetE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='430' u='r' c='_ZN6Halide8Internal21get_triple_for_targetERKNS_6TargetE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='433' u='r' c='_ZN6Halide8Internal21get_triple_for_targetERKNS_6TargetE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='443' u='r' c='_ZN6Halide8Internal21get_triple_for_targetERKNS_6TargetE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='445' u='r' c='_ZN6Halide8Internal21get_triple_for_targetERKNS_6TargetE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='449' u='r' c='_ZN6Halide8Internal21get_triple_for_targetERKNS_6TargetE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='464' u='r' c='_ZN6Halide8Internal21get_triple_for_targetERKNS_6TargetE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='473' u='r' c='_ZN6Halide8Internal21get_triple_for_targetERKNS_6TargetE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='507' u='r' c='_ZN6Halide8Internal21get_triple_for_targetERKNS_6TargetE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='511' u='r' c='_ZN6Halide8Internal21get_triple_for_targetERKNS_6TargetE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='549' u='r' c='_ZN6Halide12_GLOBAL__N_112link_modulesERSt6vectorISt10unique_ptrIN4llvm6ModuleESt14default_deleteIS4_EESaIS7_EENS_6TargetEb'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='599' u='r' c='_ZN6Halide12_GLOBAL__N_112link_modulesERSt6vectorISt10unique_ptrIN4llvm6ModuleESt14default_deleteIS4_EESaIS7_EENS_6TargetEb'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='599' u='r' c='_ZN6Halide12_GLOBAL__N_112link_modulesERSt6vectorISt10unique_ptrIN4llvm6ModuleESt14default_deleteIS4_EESaIS7_EENS_6TargetEb'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='634' u='r' c='_ZN6Halide12_GLOBAL__N_112link_modulesERSt6vectorISt10unique_ptrIN4llvm6ModuleESt14default_deleteIS4_EESaIS7_EENS_6TargetEb'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='820' u='r' c='_ZN6Halide8Internal29get_initial_module_for_targetENS_6TargetEPN4llvm11LLVMContextEbb'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='838' u='r' c='_ZN6Halide8Internal29get_initial_module_for_targetENS_6TargetEPN4llvm11LLVMContextEbb'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='853' u='r' c='_ZN6Halide8Internal29get_initial_module_for_targetENS_6TargetEPN4llvm11LLVMContextEbb'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='868' u='r' c='_ZN6Halide8Internal29get_initial_module_for_targetENS_6TargetEPN4llvm11LLVMContextEbb'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='886' u='r' c='_ZN6Halide8Internal29get_initial_module_for_targetENS_6TargetEPN4llvm11LLVMContextEbb'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='899' u='r' c='_ZN6Halide8Internal29get_initial_module_for_targetENS_6TargetEPN4llvm11LLVMContextEbb'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='912' u='r' c='_ZN6Halide8Internal29get_initial_module_for_targetENS_6TargetEPN4llvm11LLVMContextEbb'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='921' u='r' c='_ZN6Halide8Internal29get_initial_module_for_targetENS_6TargetEPN4llvm11LLVMContextEbb'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='931' u='r' c='_ZN6Halide8Internal29get_initial_module_for_targetENS_6TargetEPN4llvm11LLVMContextEbb'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='955' u='r' c='_ZN6Halide8Internal29get_initial_module_for_targetENS_6TargetEPN4llvm11LLVMContextEbb'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='1007' u='r' c='_ZN6Halide8Internal29get_initial_module_for_targetENS_6TargetEPN4llvm11LLVMContextEbb'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='1007' u='r' c='_ZN6Halide8Internal29get_initial_module_for_targetENS_6TargetEPN4llvm11LLVMContextEbb'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='1008' u='r' c='_ZN6Halide8Internal29get_initial_module_for_targetENS_6TargetEPN4llvm11LLVMContextEbb'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='1068' u='r' c='_ZN6Halide8Internal29get_initial_module_for_targetENS_6TargetEPN4llvm11LLVMContextEbb'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='1115' u='r' c='_ZN6Halide8Internal29get_initial_module_for_targetENS_6TargetEPN4llvm11LLVMContextEbb'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='1122' u='r' c='_ZN6Halide8Internal29get_initial_module_for_targetENS_6TargetEPN4llvm11LLVMContextEbb'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='1130' u='r' c='_ZN6Halide8Internal29get_initial_module_for_targetENS_6TargetEPN4llvm11LLVMContextEbb'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='1133' u='r' c='_ZN6Halide8Internal29get_initial_module_for_targetENS_6TargetEPN4llvm11LLVMContextEbb'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='1139' u='r' c='_ZN6Halide8Internal29get_initial_module_for_targetENS_6TargetEPN4llvm11LLVMContextEbb'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='1157' u='r' c='_ZN6Halide8Internal29get_initial_module_for_targetENS_6TargetEPN4llvm11LLVMContextEbb'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='1183' u='r' c='_ZN6Halide8Internal29get_initial_module_for_targetENS_6TargetEPN4llvm11LLVMContextEbb'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='1189' u='r' c='_ZN6Halide8Internal29get_initial_module_for_targetENS_6TargetEPN4llvm11LLVMContextEbb'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='1195' u='r' c='_ZN6Halide8Internal29get_initial_module_for_targetENS_6TargetEPN4llvm11LLVMContextEbb'/>
<use f='halide/src/Module.cpp' l='42' u='r' c='_ZN6Halide8Internal15get_output_infoERKNS_6TargetE'/>
<use f='halide/src/Module.cpp' l='110' u='r' c='_ZN6Halide8Internal12_GLOBAL__N_122TemporaryObjectFileDir20add_temp_object_fileERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESA_RKNS_6TargetEb'/>
<use f='halide/src/Module.cpp' l='620' u='r' c='_ZNK6Halide6Module7compileERKSt3mapINS_6OutputENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESt4lessIS2_ESaISt4pairIKS2_S8_EEE'/>
<use f='halide/src/Module.cpp' l='836' u='r' c='_ZN6Halide19compile_multitargetERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKSt3mapINS_6OutputES5_St4lessIS9_ESaISt4pairIKS9_S5_EEERKSt6vec11731248'/>
<use f='halide/src/Module.cpp' l='836' u='r' c='_ZN6Halide19compile_multitargetERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKSt3mapINS_6OutputES5_St4lessIS9_ESaISt4pairIKS9_S5_EEERKSt6vec11731248'/>
<use f='halide/src/Module.cpp' l='927' u='r' c='_ZN6Halide19compile_multitargetERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKSt3mapINS_6OutputES5_St4lessIS9_ESaISt4pairIKS9_S5_EEERKSt6vec11731248'/>
<use f='halide/src/Module.cpp' l='1021' u='r' c='_ZN6Halide19compile_multitargetERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKSt3mapINS_6OutputES5_St4lessIS9_ESaISt4pairIKS9_S5_EEERKSt6vec11731248'/>
<use f='halide/src/Target.cpp' l='429' u='r' c='_ZN6Halide31get_jit_target_from_environmentEv'/>
<use f='halide/src/Target.cpp' l='429' u='r' c='_ZN6Halide31get_jit_target_from_environmentEv'/>
<use f='halide/src/Target.cpp' l='474' u='a' c='_ZN6Halide12_GLOBAL__N_112merge_stringERNS_6TargetERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE'/>
<use f='halide/src/Target.cpp' l='512' u='r' c='_ZN6Halide12_GLOBAL__N_112merge_stringERNS_6TargetERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE'/>
<use f='halide/src/Target.cpp' l='617' u='r' c='_ZNK6Halide6Target9to_stringB5cxx11Ev'/>
<use f='halide/src/Target.cpp' l='681' u='r' c='_ZNK6Halide6Target12has_unknownsEv'/>
<use f='halide/src/Target.cpp' l='1019' u='r' c='_ZN6Halide6Target29get_runtime_compatible_targetERKS0_RS0_'/>
<use f='halide/src/Target.cpp' l='1019' u='r' c='_ZN6Halide6Target29get_runtime_compatible_targetERKS0_RS0_'/>
<use f='halide/src/Target.cpp' l='1036' u='r' c='_ZN6Halide6Target29get_runtime_compatible_targetERKS0_RS0_'/>
<use f='halide/src/autoschedulers/li2018/GradientAutoscheduler.cpp' l='80' u='r' c='_ZN6Halide8Internal13Autoscheduler12_GLOBAL__N_119natural_vector_sizeERKNS_6TargetERKNS_4TypeE'/>
<use f='halide/tutorial/lesson_11_cross_compilation.cpp' l='56' u='w' c='main'/>
<use f='halide/tutorial/lesson_11_cross_compilation.cpp' l='65' u='w' c='main'/>
<use f='halide/tutorial/lesson_11_cross_compilation.cpp' l='80' u='w' c='main'/>
<use f='halide/tutorial/lesson_12_using_the_gpu.cpp' l='291' u='r' c='_Z15find_gpu_targetv'/>
<use f='halide/tutorial/lesson_12_using_the_gpu.cpp' l='298' u='r' c='_Z15find_gpu_targetv'/>
<use f='halide/tutorial/lesson_19_wrapper_funcs.cpp' l='294' u='r' c='main'/>
