<dec f='halide/build/include/Halide.h' l='4987' type='6'/>
<use f='halide/build/include/Halide.h' l='5001'/>
<use f='halide/python_bindings/src/PyEnums.cpp' l='19' u='r' c='_ZN6Halide14PythonBindings12define_enumsERN8pybind117module_E'/>
<dec f='halide/src/DeviceAPI.h' l='22' type='6'/>
<use f='halide/src/DeviceAPI.h' l='36'/>
<use f='halide/src/DeviceInterface.cpp' l='91' u='r' c='_ZN6Halide35get_device_interface_for_device_apiENS_9DeviceAPIERKNS_6TargetEPKc'/>
<use f='halide/src/DeviceInterface.cpp' l='146' u='r' c='_ZN6Halide33get_default_device_api_for_targetERKNS_6TargetE'/>
<use f='halide/src/DeviceInterface.cpp' l='180' c='_ZN6Halide8Internal26make_device_interface_callENS_9DeviceAPIENS_10MemoryTypeE'/>
<use f='halide/src/FuseGPUThreadLoops.cpp' l='1490' u='r' c='_ZN6Halide8Internal12_GLOBAL__N_115ZeroGPULoopMins5visitEPKNS0_3ForE'/>
<use f='halide/src/IRPrinter.cpp' l='96' c='_ZN6HalidelsERSoRKNS_9DeviceAPIE'/>
<use f='halide/src/OffloadGPULoops.cpp' l='265' u='a' c='_ZN6Halide8Internal12_GLOBAL__N_116InjectGpuOffloadC1ERKNS_6TargetE'/>
<use f='halide/src/Target.cpp' l='801' u='r' c='_ZNK6Halide6Target13supports_typeERKNS_4TypeENS_9DeviceAPIE'/>
<use f='halide/src/Target.cpp' l='852' u='r' c='_ZNK6Halide6Target23get_required_device_apiEv'/>
<use f='halide/src/Target.cpp' l='871' c='_ZN6Halide29target_feature_for_device_apiENS_9DeviceAPIE'/>
