<dec f='halide/build/include/Halide.h' l='3786' type='9'/>
<use f='halide/build/include/Halide.h' l='11973'/>
<use f='halide/build/include/Halide.h' l='12965' c='_ZN6Halide8Internal15VariadicVisitor13dispatch_exprEPKNS0_12BaseExprNodeEDpOTL0__'/>
<use f='halide/build/include/Halide.h' l='13046' c='_ZN6Halide8Internal15VariadicVisitor13dispatch_stmtEPKNS0_12BaseStmtNodeEDpOTL0__'/>
<dec f='halide/src/Expr.h' l='39' type='9'/>
<use f='halide/src/IR.h' l='81'/>
<use f='halide/src/IRVisitor.h' l='183' c='_ZN6Halide8Internal15VariadicVisitor13dispatch_exprEPKNS0_12BaseExprNodeEDpOTL0__'/>
<use f='halide/src/IRVisitor.h' l='264' c='_ZN6Halide8Internal15VariadicVisitor13dispatch_stmtEPKNS0_12BaseStmtNodeEDpOTL0__'/>
<use f='halide/src/IRMatch.cpp' l='445' c='_ZN6Halide8Internal9IRMatcher12equal_helperERKNS0_12BaseExprNodeES4_'/>
