<dec f='halide/build/include/Halide.h' l='11949' type='Halide::Expr'/>
<offset>320</offset>
<dec f='halide/src/IR.h' l='57' type='Halide::Expr'/>
<offset>320</offset>
<use f='halide/src/Bounds.cpp' l='476' u='m' c='_ZN6Halide8Internal12_GLOBAL__N_16Bounds5visitEPKNS0_3MulE'/>
<use f='halide/src/Bounds.cpp' l='484' u='r' c='_ZN6Halide8Internal12_GLOBAL__N_16Bounds5visitEPKNS0_3MulE'/>
<use f='halide/src/CSE.cpp' l='57' u='r' c='_ZN6Halide8Internal12_GLOBAL__N_114should_extractERKNS_4ExprEb'/>
<use f='halide/src/CodeGen_C.cpp' l='1827' u='r' c='_ZN6Halide8Internal9CodeGen_C5visitEPKNS0_3MulE'/>
<use f='halide/src/CodeGen_Hexagon.cpp' l='1854' u='r' c='_ZN6Halide8Internal12_GLOBAL__N_115CodeGen_Hexagon5visitEPKNS0_3MulE'/>
<use f='halide/src/CodeGen_Hexagon.cpp' l='1855' u='r' c='_ZN6Halide8Internal12_GLOBAL__N_115CodeGen_Hexagon5visitEPKNS0_3MulE'/>
<use f='halide/src/CodeGen_Hexagon.cpp' l='1866' u='r' c='_ZN6Halide8Internal12_GLOBAL__N_115CodeGen_Hexagon5visitEPKNS0_3MulE'/>
<use f='halide/src/CodeGen_Hexagon.cpp' l='1867' u='r' c='_ZN6Halide8Internal12_GLOBAL__N_115CodeGen_Hexagon5visitEPKNS0_3MulE'/>
<use f='halide/src/CodeGen_Hexagon.cpp' l='1880' u='m' c='_ZN6Halide8Internal12_GLOBAL__N_115CodeGen_Hexagon5visitEPKNS0_3MulE'/>
<use f='halide/src/CodeGen_LLVM.cpp' l='1509' u='r' c='_ZN6Halide8Internal12CodeGen_LLVM5visitEPKNS0_3MulE'/>
<use f='halide/src/CodeGen_LLVM.cpp' l='1513' u='r' c='_ZN6Halide8Internal12CodeGen_LLVM5visitEPKNS0_3MulE'/>
<use f='halide/src/CodeGen_LLVM.cpp' l='1518' u='r' c='_ZN6Halide8Internal12CodeGen_LLVM5visitEPKNS0_3MulE'/>
<use f='halide/src/CodeGen_LLVM.cpp' l='1750' u='r' c='_ZN6Halide8Internal12_GLOBAL__N_110promote_64ERKNS_4ExprE'/>
<use f='halide/src/Derivative.cpp' l='784' u='r' c='_ZN6Halide8Internal12_GLOBAL__N_126ReverseAccumulationVisitor10accumulateERKNS_4ExprES3_'/>
<use f='halide/src/Derivative.cpp' l='785' u='m' c='_ZN6Halide8Internal12_GLOBAL__N_126ReverseAccumulationVisitor10accumulateERKNS_4ExprES3_'/>
<use f='halide/src/Derivative.cpp' l='786' u='r' c='_ZN6Halide8Internal12_GLOBAL__N_126ReverseAccumulationVisitor10accumulateERKNS_4ExprES3_'/>
<use f='halide/src/Derivative.cpp' l='885' u='r' c='_ZN6Halide8Internal12_GLOBAL__N_126ReverseAccumulationVisitor5visitEPKNS0_3MulE'/>
<use f='halide/src/Derivative.cpp' l='887' u='r' c='_ZN6Halide8Internal12_GLOBAL__N_126ReverseAccumulationVisitor5visitEPKNS0_3MulE'/>
<use f='halide/src/Derivative.cpp' l='1593' u='r' c='_ZN6Halide8Internal12_GLOBAL__N_126ReverseAccumulationVisitor30propagate_halide_function_callENS_4ExprERKNSt7__cxx1112basic_stringIcSt11char_traitsIcE10448212'/>
<use f='halide/src/FindIntrinsics.cpp' l='253' u='r' c='_ZN6Halide8Internal12_GLOBAL__N_114FindIntrinsics5visitEPKNS0_3MulE'/>
<use f='halide/src/FindIntrinsics.cpp' l='253' u='r' c='_ZN6Halide8Internal12_GLOBAL__N_114FindIntrinsics5visitEPKNS0_3MulE'/>
<use f='halide/src/FindIntrinsics.cpp' l='260' u='r' c='_ZN6Halide8Internal12_GLOBAL__N_114FindIntrinsics5visitEPKNS0_3MulE'/>
<use f='halide/src/FindIntrinsics.cpp' l='260' u='r' c='_ZN6Halide8Internal12_GLOBAL__N_114FindIntrinsics5visitEPKNS0_3MulE'/>
<use f='halide/src/FindIntrinsics.cpp' l='262' u='r' c='_ZN6Halide8Internal12_GLOBAL__N_114FindIntrinsics5visitEPKNS0_3MulE'/>
<use f='halide/src/FindIntrinsics.cpp' l='262' u='r' c='_ZN6Halide8Internal12_GLOBAL__N_114FindIntrinsics5visitEPKNS0_3MulE'/>
<use f='halide/src/FindIntrinsics.cpp' l='267' u='r' c='_ZN6Halide8Internal12_GLOBAL__N_114FindIntrinsics5visitEPKNS0_3MulE'/>
<use f='halide/src/FindIntrinsics.cpp' l='293' u='r' c='_ZN6Halide8Internal12_GLOBAL__N_114FindIntrinsics5visitEPKNS0_3MulE'/>
<use f='halide/src/HexagonOptimize.cpp' l='406' u='r' c='_ZN6Halide8Internal12_GLOBAL__N_112find_mpy_opsERKNS_4ExprENS_4TypeES5_iRSt6vectorISt4pairIS2_S2_ESaIS8_EERS2_'/>
<use f='halide/src/HexagonOptimize.cpp' l='412' u='r' c='_ZN6Halide8Internal12_GLOBAL__N_112find_mpy_opsERKNS_4ExprENS_4TypeES5_iRSt6vectorISt4pairIS2_S2_ESaIS8_EERS2_'/>
<use f='halide/src/IR.cpp' l='54' u='w' c='_ZN6Halide8Internal3Mul4makeENS_4ExprES2_'/>
<use f='halide/src/IROperator.cpp' l='487' u='r' c='_ZN6Halide8Internal13lossless_castENS_4TypeENS_4ExprE'/>
<use f='halide/src/IROperator.cpp' l='545' u='r' c='_ZN6Halide8Internal15lossless_negateERKNS_4ExprE'/>
<use f='halide/src/IROperator.cpp' l='551' u='r' c='_ZN6Halide8Internal15lossless_negateERKNS_4ExprE'/>
<use f='halide/src/IRPrinter.cpp' l='523' u='r' c='_ZN6Halide8Internal9IRPrinter5visitEPKNS0_3MulE'/>
<use f='halide/src/IRVisitor.cpp' l='40' u='m' c='_ZN6Halide8Internal9IRVisitor5visitEPKNS0_3MulE'/>
<use f='halide/src/IRVisitor.cpp' l='311' u='r' c='_ZN6Halide8Internal14IRGraphVisitor5visitEPKNS0_3MulE'/>
<use f='halide/src/LICM.cpp' l='225' u='r' c='_ZN6Halide8Internal12_GLOBAL__N_14LICM4costERKNS_4ExprERKSt3setINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESt4lessISC_ESaISC_EE'/>
<use f='halide/src/LoopCarry.cpp' l='61' u='r' c='_ZN6Halide8Internal12_GLOBAL__N_19is_linearERKNS_4ExprERKNS0_5ScopeIS2_EE'/>
<use f='halide/src/LoopCarry.cpp' l='67' u='r' c='_ZN6Halide8Internal12_GLOBAL__N_19is_linearERKNS_4ExprERKNS0_5ScopeIS2_EE'/>
<use f='halide/src/LowerWarpShuffles.cpp' l='64' u='r' c='_ZN6Halide8Internal12_GLOBAL__N_118reduce_expr_helperENS_4ExprERKS2_'/>
<use f='halide/src/LowerWarpShuffles.cpp' l='64' u='r' c='_ZN6Halide8Internal12_GLOBAL__N_118reduce_expr_helperENS_4ExprERKS2_'/>
<use f='halide/src/LowerWarpShuffles.cpp' l='65' u='r' c='_ZN6Halide8Internal12_GLOBAL__N_118reduce_expr_helperENS_4ExprERKS2_'/>
<use f='halide/src/LowerWarpShuffles.cpp' l='65' u='r' c='_ZN6Halide8Internal12_GLOBAL__N_118reduce_expr_helperENS_4ExprERKS2_'/>
<use f='halide/src/LowerWarpShuffles.cpp' l='67' u='r' c='_ZN6Halide8Internal12_GLOBAL__N_118reduce_expr_helperENS_4ExprERKS2_'/>
<use f='halide/src/LowerWarpShuffles.cpp' l='168' u='r' c='_ZN6Halide8Internal12_GLOBAL__N_120DetermineAllocStride11warp_strideERKNS_4ExprE'/>
<use f='halide/src/LowerWarpShuffles.cpp' l='170' u='r' c='_ZN6Halide8Internal12_GLOBAL__N_120DetermineAllocStride11warp_strideERKNS_4ExprE'/>
<use f='halide/src/ModulusRemainder.cpp' l='123' u='r' c='_ZN6Halide8Internal12_GLOBAL__N_123ComputeModulusRemainder5visitEPKNS0_3MulE'/>
<use f='halide/src/Monotonic.cpp' l='292' u='m' c='_ZN6Halide8Internal12_GLOBAL__N_116DerivativeBounds5visitEPKNS0_3MulE'/>
<use f='halide/src/Monotonic.cpp' l='297' u='r' c='_ZN6Halide8Internal12_GLOBAL__N_116DerivativeBounds5visitEPKNS0_3MulE'/>
<use f='halide/src/Simplify_Let.cpp' l='107' u='m' c='_ZN6Halide8Internal8Simplify12simplify_letEPKT_PNS1_8ExprInfoE'/>
<use f='halide/src/Simplify_Let.cpp' l='127' u='r' c='_ZN6Halide8Internal8Simplify12simplify_letEPKT_PNS1_8ExprInfoE'/>
<use f='halide/src/Simplify_Let.cpp' l='128' u='r' c='_ZN6Halide8Internal8Simplify12simplify_letEPKT_PNS1_8ExprInfoE'/>
<use f='halide/src/Simplify_Mul.cpp' l='9' u='r' c='_ZN6Halide8Internal8Simplify5visitEPKNS0_3MulEPNS1_8ExprInfoE'/>
<use f='halide/src/Simplify_Mul.cpp' l='96' u='r' c='_ZN6Halide8Internal8Simplify5visitEPKNS0_3MulEPNS1_8ExprInfoE'/>
<use f='halide/src/Simplify_Mul.cpp' l='103' u='r' c='_ZN6Halide8Internal8Simplify5visitEPKNS0_3MulEPNS1_8ExprInfoE'/>
<use f='halide/src/Solve.cpp' l='93' u='r' c='_ZN6Halide8Internal12_GLOBAL__N_115SolveExpression6negateERKNS_4ExprE'/>
<use f='halide/src/Solve.cpp' l='94' u='r' c='_ZN6Halide8Internal12_GLOBAL__N_115SolveExpression6negateERKNS_4ExprE'/>
<use f='halide/src/Solve.cpp' l='174' u='r' c='_ZN6Halide8Internal12_GLOBAL__N_115SolveExpression5visitEPKNS0_3AddE'/>
<use f='halide/src/Solve.cpp' l='174' u='r' c='_ZN6Halide8Internal12_GLOBAL__N_115SolveExpression5visitEPKNS0_3AddE'/>
<use f='halide/src/Solve.cpp' l='175' u='r' c='_ZN6Halide8Internal12_GLOBAL__N_115SolveExpression5visitEPKNS0_3AddE'/>
<use f='halide/src/Solve.cpp' l='175' u='r' c='_ZN6Halide8Internal12_GLOBAL__N_115SolveExpression5visitEPKNS0_3AddE'/>
<use f='halide/src/Solve.cpp' l='177' u='r' c='_ZN6Halide8Internal12_GLOBAL__N_115SolveExpression5visitEPKNS0_3AddE'/>
<use f='halide/src/Solve.cpp' l='180' u='r' c='_ZN6Halide8Internal12_GLOBAL__N_115SolveExpression5visitEPKNS0_3AddE'/>
<use f='halide/src/Solve.cpp' l='183' u='r' c='_ZN6Halide8Internal12_GLOBAL__N_115SolveExpression5visitEPKNS0_3AddE'/>
<use f='halide/src/Solve.cpp' l='279' u='r' c='_ZN6Halide8Internal12_GLOBAL__N_115SolveExpression5visitEPKNS0_3SubE'/>
<use f='halide/src/Solve.cpp' l='279' u='r' c='_ZN6Halide8Internal12_GLOBAL__N_115SolveExpression5visitEPKNS0_3SubE'/>
<use f='halide/src/Solve.cpp' l='280' u='r' c='_ZN6Halide8Internal12_GLOBAL__N_115SolveExpression5visitEPKNS0_3SubE'/>
<use f='halide/src/Solve.cpp' l='280' u='r' c='_ZN6Halide8Internal12_GLOBAL__N_115SolveExpression5visitEPKNS0_3SubE'/>
<use f='halide/src/Solve.cpp' l='282' u='r' c='_ZN6Halide8Internal12_GLOBAL__N_115SolveExpression5visitEPKNS0_3SubE'/>
<use f='halide/src/Solve.cpp' l='319' u='r' c='_ZN6Halide8Internal12_GLOBAL__N_115SolveExpression5visitEPKNS0_3MulE'/>
<use f='halide/src/Solve.cpp' l='345' u='r' c='_ZN6Halide8Internal12_GLOBAL__N_115SolveExpression5visitEPKNS0_3MulE'/>
<use f='halide/src/Solve.cpp' l='359' u='r' c='_ZN6Halide8Internal12_GLOBAL__N_115SolveExpression5visitEPKNS0_3MulE'/>
<use f='halide/src/Solve.cpp' l='400' u='r' c='_ZN6Halide8Internal12_GLOBAL__N_115SolveExpression5visitEPKNS0_3DivE'/>
<use f='halide/src/Solve.cpp' l='400' u='r' c='_ZN6Halide8Internal12_GLOBAL__N_115SolveExpression5visitEPKNS0_3DivE'/>
<use f='halide/src/Solve.cpp' l='402' u='r' c='_ZN6Halide8Internal12_GLOBAL__N_115SolveExpression5visitEPKNS0_3DivE'/>
<use f='halide/src/Solve.cpp' l='508' u='r' c='_ZN6Halide8Internal12_GLOBAL__N_115SolveExpression16visit_min_max_opEPKT_'/>
<use f='halide/src/Solve.cpp' l='508' u='r' c='_ZN6Halide8Internal12_GLOBAL__N_115SolveExpression16visit_min_max_opEPKT_'/>
<use f='halide/src/Solve.cpp' l='508' u='r' c='_ZN6Halide8Internal12_GLOBAL__N_115SolveExpression16visit_min_max_opEPKT_'/>
<use f='halide/src/Solve.cpp' l='511' c='_ZN6Halide8Internal12_GLOBAL__N_115SolveExpression16visit_min_max_opEPKT_'/>
<use f='halide/src/Solve.cpp' l='512' u='r' c='_ZN6Halide8Internal12_GLOBAL__N_115SolveExpression16visit_min_max_opEPKT_'/>
<use f='halide/src/Solve.cpp' l='512' u='r' c='_ZN6Halide8Internal12_GLOBAL__N_115SolveExpression16visit_min_max_opEPKT_'/>
<use f='halide/src/Solve.cpp' l='512' u='r' c='_ZN6Halide8Internal12_GLOBAL__N_115SolveExpression16visit_min_max_opEPKT_'/>
<use f='halide/src/Solve.cpp' l='514' c='_ZN6Halide8Internal12_GLOBAL__N_115SolveExpression16visit_min_max_opEPKT_'/>
<use f='halide/src/Solve.cpp' l='662' u='r' c='_ZN6Halide8Internal12_GLOBAL__N_115SolveExpression9visit_cmpEPKT_'/>
<use f='halide/src/Solve.cpp' l='663' u='r' c='_ZN6Halide8Internal12_GLOBAL__N_115SolveExpression9visit_cmpEPKT_'/>
<use f='halide/src/Solve.cpp' l='664' u='r' c='_ZN6Halide8Internal12_GLOBAL__N_115SolveExpression9visit_cmpEPKT_'/>
<use f='halide/src/Solve.cpp' l='665' u='r' c='_ZN6Halide8Internal12_GLOBAL__N_115SolveExpression9visit_cmpEPKT_'/>
<use f='halide/src/Solve.cpp' l='667' u='r' c='_ZN6Halide8Internal12_GLOBAL__N_115SolveExpression9visit_cmpEPKT_'/>
<use f='halide/src/Solve.cpp' l='669' u='r' c='_ZN6Halide8Internal12_GLOBAL__N_115SolveExpression9visit_cmpEPKT_'/>
<use f='halide/src/Solve.cpp' l='673' u='r' c='_ZN6Halide8Internal12_GLOBAL__N_115SolveExpression9visit_cmpEPKT_'/>
<use f='halide/src/Solve.cpp' l='679' u='r' c='_ZN6Halide8Internal12_GLOBAL__N_115SolveExpression9visit_cmpEPKT_'/>
<use f='halide/src/Solve.cpp' l='680' u='r' c='_ZN6Halide8Internal12_GLOBAL__N_115SolveExpression9visit_cmpEPKT_'/>
<use f='halide/src/Solve.cpp' l='687' u='r' c='_ZN6Halide8Internal12_GLOBAL__N_115SolveExpression9visit_cmpEPKT_'/>
<use f='halide/src/Solve.cpp' l='691' u='r' c='_ZN6Halide8Internal12_GLOBAL__N_115SolveExpression9visit_cmpEPKT_'/>
<use f='halide/src/Solve.cpp' l='695' u='r' c='_ZN6Halide8Internal12_GLOBAL__N_115SolveExpression9visit_cmpEPKT_'/>
<use f='halide/src/StmtToHtml.cpp' l='244' u='r' c='_ZN6Halide8Internal12_GLOBAL__N_110StmtToHtml5visitEPKNS0_3MulE'/>
<use f='halide/src/VectorizeLoops.cpp' l='53' u='m' c='_ZN6Halide8Internal12_GLOBAL__N_122bounds_of_nested_lanesERKNS_4ExprE'/>
<use f='halide/src/VectorizeLoops.cpp' l='63' u='r' c='_ZN6Halide8Internal12_GLOBAL__N_122bounds_of_nested_lanesERKNS_4ExprE'/>
<use f='halide/src/VectorizeLoops.cpp' l='66' u='r' c='_ZN6Halide8Internal12_GLOBAL__N_122bounds_of_nested_lanesERKNS_4ExprE'/>
<use f='halide/src/VectorizeLoops.cpp' l='253' u='r' c='_ZN6Halide8Internal12_GLOBAL__N_119is_interleaved_rampERKNS_4ExprERKNS0_5ScopeIS2_EEPNS1_15InterleavedRampE'/>
<use f='halide/src/VectorizeLoops.cpp' l='1094' u='r' c='_ZN6Halide8Internal12_GLOBAL__N_110VectorSubs5visitEPKNS0_6AtomicE'/>
<use f='halide/src/autoschedulers/adams2019/FunctionDAG.cpp' l='211' u='r' c='_ZN6Halide8Internal13Autoscheduler12_GLOBAL__N_110Featurizer13differentiateERKNS_4ExprERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE'/>
<use f='halide/src/autoschedulers/adams2019/FunctionDAG.cpp' l='459' u='m' c='_ZN6Halide8Internal13Autoscheduler11FunctionDAG4Edge9BoundInfoC1ERKNS_4ExprERKNS2_4Node5StageE'/>
