<dec f='halide/build/include/Halide.h' l='5085' type='31'/>
<use f='halide/python_bindings/src/PyEnums.cpp' l='115' u='r' c='_ZN6Halide14PythonBindings12define_enumsERN8pybind117module_E'/>
<dec f='halide/src/Target.h' l='91' type='31'/>
<use f='halide/src/CodeGen_C.cpp' l='418' u='r' c='_ZN6Halide8Internal9CodeGen_CD1Ev'/>
<use f='halide/src/DeviceInterface.cpp' l='145' u='r' c='_ZN6Halide33get_default_device_api_for_targetERKNS_6TargetE'/>
<use f='halide/src/JITModule.cpp' l='666' u='r' c='_ZN6Halide8Internal12_GLOBAL__N_111make_moduleEPN4llvm6ModuleENS_6TargetENS1_11RuntimeKindERKSt6vectorINS0_9JITModuleESaIS8_EEb'/>
<use f='halide/src/JITModule.cpp' l='684' u='r' c='_ZN6Halide8Internal12_GLOBAL__N_111make_moduleEPN4llvm6ModuleENS_6TargetENS1_11RuntimeKindERKSt6vectorINS0_9JITModuleESaIS8_EEb'/>
<use f='halide/src/JITModule.cpp' l='689' u='r' c='_ZN6Halide8Internal12_GLOBAL__N_111make_moduleEPN4llvm6ModuleENS_6TargetENS1_11RuntimeKindERKSt6vectorINS0_9JITModuleESaIS8_EEb'/>
<use f='halide/src/JITModule.cpp' l='849' u='r' c='_ZN6Halide8Internal16JITSharedRuntime3getEPN4llvm6ModuleERKNS_6TargetEb'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='1145' u='r' c='_ZN6Halide8Internal29get_initial_module_for_targetENS_6TargetEPN4llvm11LLVMContextEbb'/>
<use f='halide/src/OffloadGPULoops.cpp' l='264' u='r' c='_ZN6Halide8Internal12_GLOBAL__N_116InjectGpuOffloadC1ERKNS_6TargetE'/>
<use f='halide/src/Target.cpp' l='345' u='r'/>
<use f='halide/src/Target.cpp' l='739' u='r' c='_ZNK6Halide6Target15has_gpu_featureEv'/>
<use f='halide/src/Target.cpp' l='778' u='r' c='_ZNK6Halide6Target13supports_typeERKNS_4TypeE'/>
<use f='halide/src/Target.cpp' l='783' u='r' c='_ZNK6Halide6Target13supports_typeERKNS_4TypeE'/>
<use f='halide/src/Target.cpp' l='851' u='r' c='_ZNK6Halide6Target23get_required_device_apiEv'/>
<use f='halide/src/Target.cpp' l='872' u='r' c='_ZN6Halide29target_feature_for_device_apiENS_9DeviceAPIE'/>
<use f='halide/src/Target.cpp' l='948' u='r' c='_ZN6Halide6Target29get_runtime_compatible_targetERKS0_RS0_'/>
<use f='halide/tutorial/lesson_12_using_the_gpu.cpp' l='301' u='a' c='_Z15find_gpu_targetv'/>
<use f='halide/tutorial/lesson_19_wrapper_funcs.cpp' l='295' u='r' c='main'/>
