<dec f='halide/build/include/Halide.h' l='4985' type='4'/>
<use f='halide/build/include/Halide.h' l='4999'/>
<use f='halide/python_bindings/src/PyEnums.cpp' l='17' u='r' c='_ZN6Halide14PythonBindings12define_enumsERN8pybind117module_E'/>
<dec f='halide/src/DeviceAPI.h' l='20' type='4'/>
<use f='halide/src/DeviceAPI.h' l='34'/>
<use f='halide/src/DeviceInterface.cpp' l='93' u='r' c='_ZN6Halide35get_device_interface_for_device_apiENS_9DeviceAPIERKNS_6TargetEPKc'/>
<use f='halide/src/DeviceInterface.cpp' l='148' u='r' c='_ZN6Halide33get_default_device_api_for_targetERKNS_6TargetE'/>
<use f='halide/src/DeviceInterface.cpp' l='173' c='_ZN6Halide8Internal26make_device_interface_callENS_9DeviceAPIENS_10MemoryTypeE'/>
<use f='halide/src/FuseGPUThreadLoops.cpp' l='1489' u='r' c='_ZN6Halide8Internal12_GLOBAL__N_115ZeroGPULoopMins5visitEPKNS0_3ForE'/>
<use f='halide/src/IRPrinter.cpp' l='90' c='_ZN6HalidelsERSoRKNS_9DeviceAPIE'/>
<use f='halide/src/OffloadGPULoops.cpp' l='262' u='a' c='_ZN6Halide8Internal12_GLOBAL__N_116InjectGpuOffloadC1ERKNS_6TargetE'/>
<use f='halide/src/Target.cpp' l='806' u='r' c='_ZNK6Halide6Target13supports_typeERKNS_4TypeENS_9DeviceAPIE'/>
<use f='halide/src/Target.cpp' l='855' u='r' c='_ZNK6Halide6Target23get_required_device_apiEv'/>
<use f='halide/src/Target.cpp' l='867' c='_ZN6Halide29target_feature_for_device_apiENS_9DeviceAPIE'/>
<use f='halide/test/generator/define_extern_opencl_generator.cpp' l='19' u='r' c='_ZN12_GLOBAL__N_124DefineExternOpenCLOutput8generateEv'/>
<use f='halide/test/generator/define_extern_opencl_generator.cpp' l='30' u='a' c='_ZN12_GLOBAL__N_124DefineExternOpenCLOutput8scheduleEv'/>
