<dec f='halide/build/include/Halide.h' l='3811' type='33'/>
<use f='halide/build/include/Halide.h' l='12638'/>
<use f='halide/build/include/Halide.h' l='13013' c='_ZN6Halide8Internal15VariadicVisitor13dispatch_exprEPKNS0_12BaseExprNodeEDpOTL0__'/>
<use f='halide/build/include/Halide.h' l='13075' c='_ZN6Halide8Internal15VariadicVisitor13dispatch_stmtEPKNS0_12BaseStmtNodeEDpOTL0__'/>
<dec f='halide/src/Expr.h' l='64' type='33'/>
<use f='halide/src/IR.h' l='746'/>
<use f='halide/src/IRVisitor.h' l='231' c='_ZN6Halide8Internal15VariadicVisitor13dispatch_exprEPKNS0_12BaseExprNodeEDpOTL0__'/>
<use f='halide/src/IRVisitor.h' l='293' c='_ZN6Halide8Internal15VariadicVisitor13dispatch_stmtEPKNS0_12BaseStmtNodeEDpOTL0__'/>
<use f='halide/src/IRMatch.cpp' l='508' c='_ZN6Halide8Internal9IRMatcher12equal_helperERKNS0_12BaseExprNodeES4_'/>
