<inh f='halide/build/include/Halide.h' l='3903' c='Halide::Internal::ExprNode'/>
<def f='halide/build/include/Halide.h' l='11995' ll='12001'/>
<use f='halide/build/include/Halide.h' l='11995'/>
<use f='halide/build/include/Halide.h' l='12827' c='_ZN6Halide8Internal9IRVisitor5visitEPKNS0_2EQE'/>
<use f='halide/build/include/Halide.h' l='12897' c='_ZN6Halide8Internal14IRGraphVisitor5visitEPKNS0_2EQE'/>
<use f='halide/build/include/Halide.h' l='12976' c='_ZN6Halide8Internal15VariadicVisitor13dispatch_exprEPKNS0_12BaseExprNodeEDpOTL0__'/>
<use f='halide/build/include/Halide.h' l='19093' c='_ZN6Halide8Internal9IRPrinter5visitEPKNS0_2EQE'/>
<use f='halide/build/include/Halide.h' l='19326' c='_ZN6Halide8Internal9CodeGen_C5visitEPKNS0_2EQE'/>
<use f='halide/build/include/Halide.h' l='20079' c='_ZN6Halide8Internal12CodeGen_LLVM5visitEPKNS0_2EQE'/>
<use f='halide/build/include/Halide.h' l='28052' c='_ZN6Halide8Internal9IRMatcherlsERSoRKNS1_5CmpOpINS0_2EQET_T0_EE'/>
<use f='halide/build/include/Halide.h' l='28369' c='_ZN6Halide8Internal9IRMatchereqEOT_OT0_'/>
<use f='halide/build/include/Halide.h' l='28379' c='_ZN6Halide8Internal9IRMatcher20constant_fold_cmp_opEll'/>
<use f='halide/build/include/Halide.h' l='28384' c='_ZN6Halide8Internal9IRMatcher20constant_fold_cmp_opEmm'/>
<use f='halide/build/include/Halide.h' l='28389' c='_ZN6Halide8Internal9IRMatcher20constant_fold_cmp_opEdd'/>
<use f='halide/build/include/Halide.h' l='30030' c='_ZN6Halide8Internal9IRMutator5visitEPKNS0_2EQE'/>
<size>48</size>
<doc f='halide/build/include/Halide.h' l='11994'>/** Is the first expression equal to the second */</doc>
<mbr r='Halide::Internal::EQ::a' o='256' t='Halide::Expr'/>
<mbr r='Halide::Internal::EQ::b' o='320' t='Halide::Expr'/>
<fun r='_ZN6Halide8Internal2EQ4makeENS_4ExprES2_'/>
<smbr r='Halide::Internal::EQ::_node_type' t='const Halide::Internal::IRNodeType'/>
<inh f='halide/src/Expr.h' l='156' c='Halide::Internal::ExprNode'/>
<def f='halide/src/IR.h' l='103' ll='109'/>
<use f='halide/src/IR.h' l='103'/>
<use f='halide/src/IRVisitor.h' l='45' c='_ZN6Halide8Internal9IRVisitor5visitEPKNS0_2EQE'/>
<use f='halide/src/IRVisitor.h' l='115' c='_ZN6Halide8Internal14IRGraphVisitor5visitEPKNS0_2EQE'/>
<use f='halide/src/IRVisitor.h' l='194' c='_ZN6Halide8Internal15VariadicVisitor13dispatch_exprEPKNS0_12BaseExprNodeEDpOTL0__'/>
<use f='halide/src/IRMutator.h' l='58' c='_ZN6Halide8Internal9IRMutator5visitEPKNS0_2EQE'/>
<size>48</size>
<doc f='halide/src/IR.h' l='102'>/** Is the first expression equal to the second */</doc>
<mbr r='Halide::Internal::EQ::a' o='256' t='Halide::Expr'/>
<mbr r='Halide::Internal::EQ::b' o='320' t='Halide::Expr'/>
<fun r='_ZN6Halide8Internal2EQ4makeENS_4ExprES2_'/>
<smbr r='Halide::Internal::EQ::_node_type' t='const Halide::Internal::IRNodeType'/>
<use f='halide/src/IRPrinter.h' l='162' c='_ZN6Halide8Internal9IRPrinter5visitEPKNS0_2EQE'/>
<size>48</size>
<use f='halide/src/IRMatch.h' l='938' c='_ZN6Halide8Internal9IRMatcherlsERSoRKNS1_5CmpOpINS0_2EQET_T0_EE'/>
<use f='halide/src/IRMatch.h' l='1255' c='_ZN6Halide8Internal9IRMatchereqEOT_OT0_'/>
<use f='halide/src/IRMatch.h' l='1265' c='_ZN6Halide8Internal9IRMatcher20constant_fold_cmp_opEll'/>
<use f='halide/src/IRMatch.h' l='1270' c='_ZN6Halide8Internal9IRMatcher20constant_fold_cmp_opEmm'/>
<use f='halide/src/IRMatch.h' l='1275' c='_ZN6Halide8Internal9IRMatcher20constant_fold_cmp_opEdd'/>
<size>48</size>
<use f='halide/src/Bounds.cpp' l='807' c='_ZN6Halide8Internal12_GLOBAL__N_16Bounds5visitEPKNS0_2EQE'/>
<use f='halide/src/Bounds.cpp' l='2507' c='_ZN6Halide8Internal12_GLOBAL__N_112BoxesTouched5visitEPKNS0_10IfThenElseE'/>
<use f='halide/src/Bounds.cpp' l='2507' c='_ZN6Halide8Internal12_GLOBAL__N_112BoxesTouched5visitEPKNS0_10IfThenElseE'/>
<size>48</size>
<use f='halide/src/CodeGen_LLVM.h' l='340' c='_ZN6Halide8Internal12CodeGen_LLVM5visitEPKNS0_2EQE'/>
<size>48</size>
<use f='halide/src/CodeGen_C.h' l='206' c='_ZN6Halide8Internal9CodeGen_C5visitEPKNS0_2EQE'/>
<use f='halide/src/CodeGen_C.cpp' l='1893' c='_ZN6Halide8Internal9CodeGen_C5visitEPKNS0_2EQE'/>
<size>48</size>
<use f='halide/src/Simplify_Internal.h' l='313' c='_ZN6Halide8Internal8Simplify5visitEPKNS0_2EQEPNS1_8ExprInfoE'/>
<size>48</size>
<use f='halide/src/CodeGen_LLVM.cpp' l='1606' c='_ZN6Halide8Internal12CodeGen_LLVM5visitEPKNS0_2EQE'/>
<use f='halide/src/CodeGen_LLVM.cpp' l='4207' c='_ZN6Halide8Internal12CodeGen_LLVM5visitEPKNS0_10IfThenElseE'/>
<use f='halide/src/CodeGen_LLVM.cpp' l='4207' c='_ZN6Halide8Internal12CodeGen_LLVM5visitEPKNS0_10IfThenElseE'/>
<size>48</size>
<use f='halide/src/CodeGen_OpenCL_Dev.cpp' l='90' c='_ZN6Halide8Internal12_GLOBAL__N_118CodeGen_OpenCL_Dev16CodeGen_OpenCL_C5visitEPKNS0_2EQE'/>
<use f='halide/src/CodeGen_OpenCL_Dev.cpp' l='702' c='_ZN6Halide8Internal12_GLOBAL__N_118CodeGen_OpenCL_Dev16CodeGen_OpenCL_C5visitEPKNS0_2EQE'/>
<size>48</size>
<use f='halide/src/CodeGen_OpenGLCompute_Dev.cpp' l='57' c='_ZN6Halide8Internal12_GLOBAL__N_123CodeGen_OpenGLCompute_C5visitEPKNS0_2EQE'/>
<use f='halide/src/CodeGen_OpenGLCompute_Dev.cpp' l='280' c='_ZN6Halide8Internal12_GLOBAL__N_123CodeGen_OpenGLCompute_C5visitEPKNS0_2EQE'/>
<size>48</size>
<use f='halide/src/CodeGen_X86.cpp' l='79' c='_ZN6Halide8Internal12_GLOBAL__N_111CodeGen_X865visitEPKNS0_2EQE'/>
<use f='halide/src/CodeGen_X86.cpp' l='341' c='_ZN6Halide8Internal12_GLOBAL__N_111CodeGen_X865visitEPKNS0_2EQE'/>
<size>48</size>
<use f='halide/src/Derivative.cpp' l='66' c='_ZN6Halide8Internal12_GLOBAL__N_126ReverseAccumulationVisitor5visitEPKNS0_2EQE'/>
<use f='halide/src/Derivative.cpp' l='959' c='_ZN6Halide8Internal12_GLOBAL__N_126ReverseAccumulationVisitor5visitEPKNS0_2EQE'/>
<size>48</size>
<use f='halide/src/DerivativeUtils.cpp' l='392' c='_ZN6Halide8Internal13solve_inverseENS_4ExprERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES9_'/>
<size>48</size>
<use f='halide/src/EliminateBoolVectors.cpp' l='61' c='_ZN6Halide8Internal12_GLOBAL__N_120EliminateBoolVectors5visitEPKNS0_2EQE'/>
<size>48</size>
<use f='halide/src/IR.cpp' l='111' c='_ZN6Halide8Internal2EQ4makeENS_4ExprES2_'/>
<use f='halide/src/IR.cpp' l='111' c='_ZN6Halide8Internal2EQ4makeENS_4ExprES2_'/>
<use f='halide/src/IR.cpp' l='1001' c='_ZNK6Halide8Internal8ExprNode6acceptEPNS0_9IRVisitorE'/>
<use f='halide/src/IR.cpp' l='1186' c='_ZNK6Halide8Internal8ExprNode11mutate_exprEPNS0_9IRMutatorE'/>
<size>48</size>
<fun r='_ZN6Halide8Internal2EQ4makeENS_4ExprES2_'/>
<use f='halide/src/IREquality.cpp' l='68' c='_ZN6Halide8Internal12_GLOBAL__N_110IRComparer5visitEPKNS0_2EQE'/>
<use f='halide/src/IREquality.cpp' l='375' c='_ZN6Halide8Internal12_GLOBAL__N_110IRComparer5visitEPKNS0_2EQE'/>
<size>48</size>
<use f='halide/src/IRMatch.cpp' l='177' c='_ZN6Halide8Internal12_GLOBAL__N_17IRMatch5visitEPKNS0_2EQE'/>
<use f='halide/src/IRMatch.cpp' l='452' c='_ZN6Halide8Internal9IRMatcher12equal_helperERKNS0_12BaseExprNodeES4_'/>
<size>48</size>
<use f='halide/src/IRMutator.cpp' l='74' c='_ZN6Halide8Internal9IRMutator5visitEPKNS0_2EQE'/>
<size>48</size>
<use f='halide/src/IRPrinter.cpp' l='559' c='_ZN6Halide8Internal9IRPrinter5visitEPKNS0_2EQE'/>
<size>48</size>
<use f='halide/src/IRVisitor.cpp' l='63' c='_ZN6Halide8Internal9IRVisitor5visitEPKNS0_2EQE'/>
<use f='halide/src/IRVisitor.cpp' l='334' c='_ZN6Halide8Internal14IRGraphVisitor5visitEPKNS0_2EQE'/>
<size>48</size>
<use f='halide/src/ModulusRemainder.cpp' l='46' c='_ZN6Halide8Internal12_GLOBAL__N_123ComputeModulusRemainder5visitEPKNS0_2EQE'/>
<use f='halide/src/ModulusRemainder.cpp' l='138' c='_ZN6Halide8Internal12_GLOBAL__N_123ComputeModulusRemainder5visitEPKNS0_2EQE'/>
<size>48</size>
<use f='halide/src/Monotonic.cpp' l='359' c='_ZN6Halide8Internal12_GLOBAL__N_116DerivativeBounds5visitEPKNS0_2EQE'/>
<size>48</size>
<use f='halide/src/RegionCosts.cpp' l='116' c='_ZN6Halide8Internal12_GLOBAL__N_18ExprCost5visitEPKNS0_2EQE'/>
<size>48</size>
<use f='halide/src/RemoveUndef.cpp' l='83' c='_ZN6Halide8Internal12_GLOBAL__N_111RemoveUndef5visitEPKNS0_2EQE'/>
<size>48</size>
<use f='halide/src/Simplify.cpp' l='198' c='_ZN6Halide8Internal8Simplify10ScopedFact10learn_trueERKNS_4ExprE'/>
<use f='halide/src/Simplify.cpp' l='198' c='_ZN6Halide8Internal8Simplify10ScopedFact10learn_trueERKNS_4ExprE'/>
<size>48</size>
<use f='halide/src/SimplifyCorrelatedDifferences.cpp' l='264' c='_ZN6Halide8Internal12_GLOBAL__N_129SimplifyCorrelatedDifferences5visitEPKNS0_2EQE'/>
<size>48</size>
<use f='halide/src/SimplifySpecializations.cpp' l='125' c='_ZN6Halide8Internal12_GLOBAL__N_138propagate_specialization_in_definitionERNS0_10DefinitionERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE'/>
<use f='halide/src/SimplifySpecializations.cpp' l='125' c='_ZN6Halide8Internal12_GLOBAL__N_138propagate_specialization_in_definitionERNS0_10DefinitionERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE'/>
<size>48</size>
<use f='halide/src/Simplify_EQ.cpp' l='6' c='_ZN6Halide8Internal8Simplify5visitEPKNS0_2EQEPNS1_8ExprInfoE'/>
<use f='halide/src/Simplify_EQ.cpp' l='121' c='_ZN6Halide8Internal8Simplify5visitEPKNS0_2EQEPNS1_8ExprInfoE'/>
<use f='halide/src/Simplify_EQ.cpp' l='121' c='_ZN6Halide8Internal8Simplify5visitEPKNS0_2EQEPNS1_8ExprInfoE'/>
<size>48</size>
<use f='halide/src/Solve.cpp' l='642' c='_ZN6Halide8Internal12_GLOBAL__N_115SolveExpression9visit_cmpEPKT_'/>
<use f='halide/src/Solve.cpp' l='764' c='_ZN6Halide8Internal12_GLOBAL__N_115SolveExpression5visitEPKNS0_2EQE'/>
<use f='halide/src/Solve.cpp' l='765' c='_ZN6Halide8Internal12_GLOBAL__N_115SolveExpression5visitEPKNS0_2EQE'/>
<use f='halide/src/Solve.cpp' l='765' c='_ZN6Halide8Internal12_GLOBAL__N_115SolveExpression5visitEPKNS0_2EQE'/>
<use f='halide/src/Solve.cpp' l='1096' c='_ZN6Halide8Internal12_GLOBAL__N_116SolveForInterval5visitEPKNS0_2EQE'/>
<size>48</size>
<use f='halide/src/StmtToHtml.cpp' l='273' c='_ZN6Halide8Internal12_GLOBAL__N_110StmtToHtml5visitEPKNS0_2EQE'/>
<size>48</size>
<use f='halide/src/TrimNoOps.cpp' l='305' c='_ZN6Halide8Internal12_GLOBAL__N_119SimplifyUsingBounds5visitEPKNS0_2EQE'/>
<size>48</size>
<use f='halide/src/VectorizeLoops.cpp' l='599' c='_ZN6Halide8Internal12_GLOBAL__N_110VectorSubs5visitEPKNS0_2EQE'/>
<size>48</size>
<use f='halide/src/autoschedulers/adams2019/FunctionDAG.cpp' l='96' c='_ZN6Halide8Internal13Autoscheduler12_GLOBAL__N_110Featurizer5visitEPKNS0_2EQE'/>
<size>48</size>
