<dec f='halide/build/include/Halide.h' l='2408' type='std::ostringstream'/>
<use f='halide/build/include/Halide.h' l='2420' c='_ZN6Halide8Internal11ErrorReportlsERKT_'/>
<offset>0</offset>
<dec f='halide/src/Error.h' l='72' type='std::ostringstream'/>
<use f='halide/src/Error.h' l='84' c='_ZN6Halide8Internal11ErrorReportlsERKT_'/>
<offset>0</offset>
<use f='halide/src/Error.cpp' l='82' u='a' c='_ZN6Halide8Internal11ErrorReportC1EPKciS3_i'/>
<use f='halide/src/Error.cpp' l='84' u='a' c='_ZN6Halide8Internal11ErrorReportC1EPKciS3_i'/>
<use f='halide/src/Error.cpp' l='86' u='a' c='_ZN6Halide8Internal11ErrorReportC1EPKciS3_i'/>
<use f='halide/src/Error.cpp' l='88' u='a' c='_ZN6Halide8Internal11ErrorReportC1EPKciS3_i'/>
<use f='halide/src/Error.cpp' l='90' u='a' c='_ZN6Halide8Internal11ErrorReportC1EPKciS3_i'/>
<use f='halide/src/Error.cpp' l='92' u='a' c='_ZN6Halide8Internal11ErrorReportC1EPKciS3_i'/>
<use f='halide/src/Error.cpp' l='94' u='a' c='_ZN6Halide8Internal11ErrorReportC1EPKciS3_i'/>
<use f='halide/src/Error.cpp' l='104' u='m' c='_ZN6Halide8Internal11ErrorReportD1Ev'/>
<use f='halide/src/Error.cpp' l='104' u='m' c='_ZN6Halide8Internal11ErrorReportD1Ev'/>
<use f='halide/src/Error.cpp' l='105' u='a' c='_ZN6Halide8Internal11ErrorReportD1Ev'/>
<use f='halide/src/Error.cpp' l='110' u='m' c='_ZN6Halide8Internal11ErrorReportD1Ev'/>
<use f='halide/src/Error.cpp' l='113' u='m' c='_ZN6Halide8Internal11ErrorReportD1Ev'/>
<use f='halide/src/Error.cpp' l='122' u='m' c='_ZN6Halide8Internal11ErrorReportD1Ev'/>
<use f='halide/src/Error.cpp' l='134' u='m' c='_ZN6Halide8Internal11ErrorReportD1Ev'/>
<use f='halide/src/Error.cpp' l='136' u='m' c='_ZN6Halide8Internal11ErrorReportD1Ev'/>
<use f='halide/src/Error.cpp' l='138' u='m' c='_ZN6Halide8Internal11ErrorReportD1Ev'/>
