<use f='halide/build/include/Halide.h' l='2294' c='_ZN6HalidelsERSoRKNS_6ModuleE'/>
<use f='halide/build/include/Halide.h' l='13311' c='_ZN6Halide8Internal9JITModuleC1ERKNS_6ModuleERKNS0_11LoweredFuncERKSt6vectorIS1_SaIS1_EE'/>
<def f='halide/build/include/Halide.h' l='14025' ll='14092'/>
<use f='halide/build/include/Halide.h' l='14050' c='_ZNK6Halide6Module10submodulesEv'/>
<use f='halide/build/include/Halide.h' l='14062' c='_ZN6Halide6Module6appendERKS0_'/>
<use f='halide/build/include/Halide.h' l='14077' c='_ZNK6Halide6Module18resolve_submodulesEv'/>
<use f='halide/build/include/Halide.h' l='14095' c='_ZN6Halide12link_modulesERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKSt6vectorINS_6ModuleESaIS9_EE'/>
<use f='halide/build/include/Halide.h' l='14095' c='_ZN6Halide12link_modulesERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKSt6vectorINS_6ModuleESaIS9_EE'/>
<use f='halide/build/include/Halide.h' l='14110'/>
<use f='halide/build/include/Halide.h' l='14992' c='_ZN6Halide8Pipeline17compile_to_moduleERKSt6vectorINS_8ArgumentESaIS2_EERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKNS_6TargetENS_11LinkageTypeE'/>
<use f='halide/build/include/Halide.h' l='16881' c='_ZN6Halide4Func17compile_to_moduleERKSt6vectorINS_8ArgumentESaIS2_EERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKNS_6TargetE'/>
<use f='halide/build/include/Halide.h' l='18966' c='_ZN6HalidelsERSoRKNS_6ModuleE'/>
<use f='halide/build/include/Halide.h' l='19167' c='_ZN6Halide8Internal9CodeGen_C7compileERKNS_6ModuleE'/>
<use f='halide/build/include/Halide.h' l='19804' c='_ZN6Halide8Internal12CodeGen_LLVM7compileERKNS_6ModuleE'/>
<use f='halide/build/include/Halide.h' l='19902' c='_ZN6Halide8Internal12CodeGen_LLVM17add_external_codeERKNS_6ModuleE'/>
<use f='halide/build/include/Halide.h' l='20315' c='_ZN6Halide12codegen_llvmERKNS_6ModuleERN4llvm11LLVMContextE'/>
<use f='halide/build/include/Halide.h' l='20561' c='_ZN6Halide8Internal15CodeGen_PyTorch7compileERKNS_6ModuleE'/>
<use f='halide/build/include/Halide.h' l='26031' c='_ZN6Halide8Internal13GeneratorBase12build_moduleERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEENS_11LinkageTypeE'/>
<use f='halide/build/include/Halide.h' l='26048' c='_ZN6Halide8Internal13GeneratorBase21build_gradient_moduleERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE'/>
<use f='halide/build/include/Halide.h' l='26829' c='_ZN6Halide8Internal18inject_hexagon_rpcENS0_4StmtERKNS_6TargetERNS_6ModuleE'/>
<use f='halide/build/include/Halide.h' l='26831' c='_ZN6Halide8Internal39compile_module_to_hexagon_shared_objectERKNS_6ModuleE'/>
<use f='halide/build/include/Halide.h' l='30180' c='_ZN6Halide29compile_module_to_llvm_moduleERKNS_6ModuleERN4llvm11LLVMContextE'/>
<use f='halide/build/include/Halide.h' l='30301' c='_ZN6Halide8Internal5lowerERKSt6vectorINS0_8FunctionESaIS2_EERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKNS_6TargetERKS1_INS_8ArgumentESaIS464497'/>
<use f='halide/build/include/Halide.h' l='30743' c='_ZN6Halide8Internal18PythonExtensionGen7compileERKNS_6ModuleE'/>
<use f='halide/build/include/Halide.h' l='31415' c='_ZN6Halide8Internal13print_to_htmlERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKNS_6ModuleE'/>
<use f='halide/build/include/Halide.h' l='31960' c='_ZN6Halide8Internal10WasmModule7compileERKNS_6ModuleERKSt6vectorINS_8ArgumentESaIS6_EERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKSt3mapIS11257875'/>
<size>8</size>
<doc f='halide/build/include/Halide.h' l='14023'>/** A halide module. This represents IR containing lowered function
 * definitions and buffers. */</doc>
<mbr r='Halide::Module::contents' o='0' t='Internal::IntrusivePtr&lt;Internal::ModuleContents&gt;'/>
<fun r='_ZN6Halide6ModuleC1ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKNS_6TargetE'/>
<fun r='_ZNK6Halide6Module6targetEv'/>
<fun r='_ZNK6Halide6Module4nameB5cxx11Ev'/>
<fun r='_ZNK6Halide6Module26get_auto_scheduler_resultsEv'/>
<fun r='_ZNK6Halide6Module16any_strict_floatEv'/>
<fun r='_ZNK6Halide6Module7buffersEv'/>
<fun r='_ZNK6Halide6Module9functionsEv'/>
<fun r='_ZN6Halide6Module9functionsEv'/>
<fun r='_ZNK6Halide6Module10submodulesEv'/>
<fun r='_ZNK6Halide6Module13external_codeEv'/>
<fun r='_ZNK6Halide6Module20get_function_by_nameERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE'/>
<fun r='_ZN6Halide6Module6appendERKNS_6BufferIvEE'/>
<fun r='_ZN6Halide6Module6appendERKNS_8Internal11LoweredFuncE'/>
<fun r='_ZN6Halide6Module6appendERKS0_'/>
<fun r='_ZN6Halide6Module6appendERKNS_12ExternalCodeE'/>
<fun r='_ZNK6Halide6Module7compileERKSt3mapINS_6OutputENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESt4lessIS2_ESaISt4pairIKS2_S8_EEE'/>
<fun r='_ZNK6Halide6Module17compile_to_bufferEv'/>
<fun r='_ZNK6Halide6Module18resolve_submodulesEv'/>
<fun r='_ZNK6Halide6Module19remap_metadata_nameERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES8_'/>
<fun r='_ZNK6Halide6Module21get_metadata_name_mapB5cxx11Ev'/>
<fun r='_ZN6Halide6Module26set_auto_scheduler_resultsERKNS_20AutoSchedulerResultsE'/>
<fun r='_ZN6Halide6Module20set_any_strict_floatEb'/>
<use f='halide/python_bindings/src/PyModule.cpp' l='25' c='_ZN6Halide14PythonBindings13define_moduleERN8pybind117module_E'/>
<use f='halide/python_bindings/src/PyModule.cpp' l='34' c='_ZN6Halide14PythonBindings13define_moduleERN8pybind117module_E'/>
<use f='halide/python_bindings/src/PyModule.cpp' l='35' c='_ZN6Halide14PythonBindings13define_moduleERN8pybind117module_E'/>
<use f='halide/python_bindings/src/PyModule.cpp' l='35' c='_ZN6Halide14PythonBindings13define_moduleERN8pybind117module_E'/>
<use f='halide/python_bindings/src/PyModule.cpp' l='57' c='_ZN6Halide14PythonBindings13define_moduleERN8pybind117module_E'/>
<size>8</size>
<use f='halide/src/Debug.h' l='21' c='_ZN6HalidelsERSoRKNS_6ModuleE'/>
<use f='halide/src/JITModule.h' l='44' c='_ZN6Halide8Internal9JITModuleC1ERKNS_6ModuleERKNS0_11LoweredFuncERKSt6vectorIS1_SaIS1_EE'/>
<def f='halide/src/Module.h' l='135' ll='202'/>
<use f='halide/src/Module.h' l='160' c='_ZNK6Halide6Module10submodulesEv'/>
<use f='halide/src/Module.h' l='172' c='_ZN6Halide6Module6appendERKS0_'/>
<use f='halide/src/Module.h' l='187' c='_ZNK6Halide6Module18resolve_submodulesEv'/>
<use f='halide/src/Module.h' l='205' c='_ZN6Halide12link_modulesERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKSt6vectorINS_6ModuleESaIS9_EE'/>
<use f='halide/src/Module.h' l='205' c='_ZN6Halide12link_modulesERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKSt6vectorINS_6ModuleESaIS9_EE'/>
<use f='halide/src/Module.h' l='220'/>
<use f='halide/src/Pipeline.h' l='336' c='_ZN6Halide8Pipeline17compile_to_moduleERKSt6vectorINS_8ArgumentESaIS2_EERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKNS_6TargetENS_11LinkageTypeE'/>
<use f='halide/src/Func.h' l='1001' c='_ZN6Halide4Func17compile_to_moduleERKSt6vectorINS_8ArgumentESaIS2_EERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKNS_6TargetE'/>
<size>8</size>
<doc f='halide/src/Module.h' l='133'>/** A halide module. This represents IR containing lowered function
 * definitions and buffers. */</doc>
<mbr r='Halide::Module::contents' o='0' t='Internal::IntrusivePtr&lt;Internal::ModuleContents&gt;'/>
<fun r='_ZN6Halide6ModuleC1ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKNS_6TargetE'/>
<fun r='_ZNK6Halide6Module6targetEv'/>
<fun r='_ZNK6Halide6Module4nameB5cxx11Ev'/>
<fun r='_ZNK6Halide6Module26get_auto_scheduler_resultsEv'/>
<fun r='_ZNK6Halide6Module16any_strict_floatEv'/>
<fun r='_ZNK6Halide6Module7buffersEv'/>
<fun r='_ZNK6Halide6Module9functionsEv'/>
<fun r='_ZN6Halide6Module9functionsEv'/>
<fun r='_ZNK6Halide6Module10submodulesEv'/>
<fun r='_ZNK6Halide6Module13external_codeEv'/>
<fun r='_ZNK6Halide6Module20get_function_by_nameERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE'/>
<fun r='_ZN6Halide6Module6appendERKNS_6BufferIvEE'/>
<fun r='_ZN6Halide6Module6appendERKNS_8Internal11LoweredFuncE'/>
<fun r='_ZN6Halide6Module6appendERKS0_'/>
<fun r='_ZN6Halide6Module6appendERKNS_12ExternalCodeE'/>
<fun r='_ZNK6Halide6Module7compileERKSt3mapINS_6OutputENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESt4lessIS2_ESaISt4pairIKS2_S8_EEE'/>
<fun r='_ZNK6Halide6Module17compile_to_bufferEv'/>
<fun r='_ZNK6Halide6Module18resolve_submodulesEv'/>
<fun r='_ZNK6Halide6Module19remap_metadata_nameERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES8_'/>
<fun r='_ZNK6Halide6Module21get_metadata_name_mapB5cxx11Ev'/>
<fun r='_ZN6Halide6Module26set_auto_scheduler_resultsERKNS_20AutoSchedulerResultsE'/>
<fun r='_ZN6Halide6Module20set_any_strict_floatEb'/>
<use f='halide/src/IRPrinter.h' l='35' c='_ZN6HalidelsERSoRKNS_6ModuleE'/>
<size>8</size>
<use f='halide/src/CodeGen_LLVM.h' l='65' c='_ZN6Halide8Internal12CodeGen_LLVM7compileERKNS_6ModuleE'/>
<use f='halide/src/CodeGen_LLVM.h' l='163' c='_ZN6Halide8Internal12CodeGen_LLVM17add_external_codeERKNS_6ModuleE'/>
<use f='halide/src/CodeGen_LLVM.h' l='576' c='_ZN6Halide12codegen_llvmERKNS_6ModuleERN4llvm11LLVMContextE'/>
<size>8</size>
<use f='halide/src/CodeGen_C.h' l='47' c='_ZN6Halide8Internal9CodeGen_C7compileERKNS_6ModuleE'/>
<use f='halide/src/CodeGen_C.cpp' l='1492' c='_ZN6Halide8Internal9CodeGen_C7compileERKNS_6ModuleE'/>
<use f='halide/src/CodeGen_C.cpp' l='2929' c='_ZN6Halide8Internal9CodeGen_C4testEv'/>
<size>8</size>
<use f='halide/src/CodeGen_LLVM.cpp' l='40' c='_ZN6Halide12codegen_llvmERKNS_6ModuleERN4llvm11LLVMContextE'/>
<use f='halide/src/CodeGen_LLVM.cpp' l='324' c='_ZN6Halide8Internal12CodeGen_LLVM17add_external_codeERKNS_6ModuleE'/>
<use f='halide/src/CodeGen_LLVM.cpp' l='477' c='_ZN6Halide8Internal12CodeGen_LLVM7compileERKNS_6ModuleE'/>
<size>8</size>
<use f='halide/src/CodeGen_PyTorch.h' l='35' c='_ZN6Halide8Internal15CodeGen_PyTorch7compileERKNS_6ModuleE'/>
<use f='halide/src/CodeGen_PyTorch.cpp' l='18' c='_ZN6Halide8Internal15CodeGen_PyTorch7compileERKNS_6ModuleE'/>
<use f='halide/src/CodeGen_PyTorch.cpp' l='253' c='_ZN6Halide8Internal15CodeGen_PyTorch4testEv'/>
<use f='halide/src/CodeGen_PyTorch.cpp' l='319' c='_ZN6Halide8Internal15CodeGen_PyTorch4testEv'/>
<size>8</size>
<use f='halide/src/LLVM_Output.h' l='31' c='_ZN6Halide29compile_module_to_llvm_moduleERKNS_6ModuleERN4llvm11LLVMContextE'/>
<use f='halide/src/Lower.h' l='32' c='_ZN6Halide8Internal5lowerERKSt6vectorINS0_8FunctionESaIS2_EERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKNS_6TargetERKS1_INS_8ArgumentESaIS464497'/>
<use f='halide/src/Func.cpp' l='3163' c='_ZN6Halide4Func17compile_to_moduleERKSt6vectorINS_8ArgumentESaIS2_EERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKNS_6TargetE'/>
<size>8</size>
<use f='halide/src/Generator.h' l='3097' c='_ZN6Halide8Internal13GeneratorBase12build_moduleERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEENS_11LinkageTypeE'/>
<use f='halide/src/Generator.h' l='3114' c='_ZN6Halide8Internal13GeneratorBase21build_gradient_moduleERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE'/>
<use f='halide/src/Generator.cpp' l='1025' c='_ZN6Halide8Internal26generate_filter_main_innerEiPPcRSo'/>
<use f='halide/src/Generator.cpp' l='1460' c='_ZN6Halide8Internal13GeneratorBase12build_moduleERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEENS_11LinkageTypeE'/>
<use f='halide/src/Generator.cpp' l='1477' c='_ZN6Halide8Internal13GeneratorBase12build_moduleERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEENS_11LinkageTypeE'/>
<use f='halide/src/Generator.cpp' l='1500' c='_ZN6Halide8Internal13GeneratorBase21build_gradient_moduleERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE'/>
<use f='halide/src/Generator.cpp' l='1652' c='_ZN6Halide8Internal13GeneratorBase21build_gradient_moduleERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE'/>
<size>8</size>
<use f='halide/src/HexagonOffload.h' l='22' c='_ZN6Halide8Internal18inject_hexagon_rpcENS0_4StmtERKNS_6TargetERNS_6ModuleE'/>
<use f='halide/src/HexagonOffload.h' l='24' c='_ZN6Halide8Internal39compile_module_to_hexagon_shared_objectERKNS_6ModuleE'/>
<use f='halide/src/HexagonOffload.cpp' l='695'/>
<use f='halide/src/HexagonOffload.cpp' l='925' c='_ZN6Halide8Internal12_GLOBAL__N_116InjectHexagonRpcC1ERNS_6ModuleE'/>
<use f='halide/src/HexagonOffload.cpp' l='956' c='_ZN6Halide8Internal18inject_hexagon_rpcENS0_4StmtERKNS_6TargetERNS_6ModuleE'/>
<use f='halide/src/HexagonOffload.cpp' l='988' c='_ZN6Halide8Internal18inject_hexagon_rpcENS0_4StmtERKNS_6TargetERNS_6ModuleE'/>
<use f='halide/src/HexagonOffload.cpp' l='989' c='_ZN6Halide8Internal18inject_hexagon_rpcENS0_4StmtERKNS_6TargetERNS_6ModuleE'/>
<use f='halide/src/HexagonOffload.cpp' l='1001' c='_ZN6Halide8Internal39compile_module_to_hexagon_shared_objectERKNS_6ModuleE'/>
<size>8</size>
<use f='halide/src/IRPrinter.cpp' l='64' c='_ZN6HalidelsERSoRKNS_6ModuleE'/>
<size>8</size>
<use f='halide/src/JITModule.cpp' l='233' c='_ZN6Halide8Internal9JITModuleC1ERKNS_6ModuleERKNS0_11LoweredFuncERKSt6vectorIS1_SaIS1_EE'/>
<size>8</size>
<use f='halide/src/LLVM_Output.cpp' l='398' c='_ZN6Halide29compile_module_to_llvm_moduleERKNS_6ModuleERN4llvm11LLVMContextE'/>
<size>8</size>
<use f='halide/src/Lower.cpp' l='109' c='_ZN6Halide8Internal12_GLOBAL__N_110lower_implERKSt6vectorINS0_8FunctionESaIS3_EERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKNS_6TargetERKS7388887'/>
<use f='halide/src/Lower.cpp' l='526' c='_ZN6Halide8Internal5lowerERKSt6vectorINS0_8FunctionESaIS2_EERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKNS_6TargetERKS1_INS_8ArgumentESaIS464497'/>
<use f='halide/src/Lower.cpp' l='534' c='_ZN6Halide8Internal5lowerERKSt6vectorINS0_8FunctionESaIS2_EERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKNS_6TargetERKS1_INS_8ArgumentESaIS464497'/>
<use f='halide/src/Lower.cpp' l='557' c='_ZN6Halide8Internal15lower_main_stmtERKSt6vectorINS0_8FunctionESaIS2_EERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKNS_6TargetERKS1_INS0_4S10231373'/>
<size>8</size>
<use f='halide/src/PythonExtensionGen.h' l='21' c='_ZN6Halide8Internal18PythonExtensionGen7compileERKNS_6ModuleE'/>
<use f='halide/src/StmtToHtml.h' l='24' c='_ZN6Halide8Internal13print_to_htmlERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKNS_6ModuleE'/>
<use f='halide/src/Module.cpp' l='155' c='_ZN6Halide8Internal12_GLOBAL__N_117emit_registrationERKNS_6ModuleERSo'/>
<use f='halide/src/Module.cpp' l='331'/>
<use f='halide/src/Module.cpp' l='414' c='_ZNK6Halide6Module10submodulesEv'/>
<use f='halide/src/Module.cpp' l='440' c='_ZN6Halide6Module6appendERKS0_'/>
<use f='halide/src/Module.cpp' l='448' c='_ZN6Halide12link_modulesERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKSt6vectorINS_6ModuleESaIS9_EE'/>
<use f='halide/src/Module.cpp' l='448' c='_ZN6Halide12link_modulesERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKSt6vectorINS_6ModuleESaIS9_EE'/>
<use f='halide/src/Module.cpp' l='449' c='_ZN6Halide12link_modulesERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKSt6vectorINS_6ModuleESaIS9_EE'/>
<use f='halide/src/Module.cpp' l='452' c='_ZN6Halide12link_modulesERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKSt6vectorINS_6ModuleESaIS9_EE'/>
<use f='halide/src/Module.cpp' l='503' c='_ZNK6Halide6Module18resolve_submodulesEv'/>
<use f='halide/src/Module.cpp' l='508' c='_ZNK6Halide6Module18resolve_submodulesEv'/>
<use f='halide/src/Module.cpp' l='520' c='_ZNK6Halide6Module18resolve_submodulesEv'/>
<use f='halide/src/Module.cpp' l='714' c='_ZN6Halide26compile_standalone_runtimeERKSt3mapINS_6OutputENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESt4lessIS1_ESaISt4pairIKS1_S7_EEERKNS_6TargetE'/>
<use f='halide/src/Module.cpp' l='873' c='_ZN6Halide19compile_multitargetERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKSt3mapINS_6OutputES5_St4lessIS9_ESaISt4pairIKS9_S5_EEERKSt6vec11731248'/>
<use f='halide/src/Module.cpp' l='973' c='_ZN6Halide19compile_multitargetERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKSt3mapINS_6OutputES5_St4lessIS9_ESaISt4pairIKS9_S5_EEERKSt6vec11731248'/>
<use f='halide/src/Module.cpp' l='986' c='_ZN6Halide19compile_multitargetERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKSt3mapINS_6OutputES5_St4lessIS9_ESaISt4pairIKS9_S5_EEERKSt6vec11731248'/>
<use f='halide/src/Module.cpp' l='995' c='_ZN6Halide19compile_multitargetERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKSt3mapINS_6OutputES5_St4lessIS9_ESaISt4pairIKS9_S5_EEERKSt6vec11731248'/>
<size>8</size>
<fun r='_ZN6Halide6ModuleC1ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKNS_6TargetE'/>
<fun r='_ZN6Halide6Module26set_auto_scheduler_resultsERKNS_20AutoSchedulerResultsE'/>
<fun r='_ZN6Halide6Module20set_any_strict_floatEb'/>
<fun r='_ZNK6Halide6Module6targetEv'/>
<fun r='_ZNK6Halide6Module4nameB5cxx11Ev'/>
<fun r='_ZNK6Halide6Module26get_auto_scheduler_resultsEv'/>
<fun r='_ZNK6Halide6Module16any_strict_floatEv'/>
<fun r='_ZNK6Halide6Module7buffersEv'/>
<fun r='_ZNK6Halide6Module9functionsEv'/>
<fun r='_ZN6Halide6Module9functionsEv'/>
<fun r='_ZNK6Halide6Module10submodulesEv'/>
<fun r='_ZNK6Halide6Module13external_codeEv'/>
<fun r='_ZNK6Halide6Module20get_function_by_nameERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE'/>
<fun r='_ZN6Halide6Module6appendERKNS_6BufferIvEE'/>
<fun r='_ZN6Halide6Module6appendERKNS_8Internal11LoweredFuncE'/>
<fun r='_ZN6Halide6Module6appendERKS0_'/>
<fun r='_ZN6Halide6Module6appendERKNS_12ExternalCodeE'/>
<fun r='_ZNK6Halide6Module17compile_to_bufferEv'/>
<fun r='_ZNK6Halide6Module18resolve_submodulesEv'/>
<fun r='_ZNK6Halide6Module19remap_metadata_nameERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES8_'/>
<fun r='_ZNK6Halide6Module21get_metadata_name_mapB5cxx11Ev'/>
<fun r='_ZNK6Halide6Module7compileERKSt3mapINS_6OutputENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESt4lessIS2_ESaISt4pairIKS2_S8_EEE'/>
<use f='halide/src/WasmExecutor.h' l='35' c='_ZN6Halide8Internal10WasmModule7compileERKNS_6ModuleERKSt6vectorINS_8ArgumentESaIS6_EERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKSt3mapIS11257875'/>
<use f='halide/src/Pipeline.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_111output_nameERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKNS_6ModuleES8_'/>
<use f='halide/src/Pipeline.cpp' l='37' c='_ZN6Halide12_GLOBAL__N_113single_outputERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKNS_6ModuleENS_6OutputE'/>
<use f='halide/src/Pipeline.cpp' l='68'/>
<use f='halide/src/Pipeline.cpp' l='82' c='_ZN6Halide16PipelineContents16invalidate_cacheEv'/>
<use f='halide/src/Pipeline.cpp' l='269' c='_ZN6Halide8Pipeline18compile_to_bitcodeERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKSt6vectorINS_8ArgumentESaISA_EES8_RKNS_6TargetE'/>
<use f='halide/src/Pipeline.cpp' l='277' c='_ZN6Halide8Pipeline24compile_to_llvm_assemblyERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKSt6vectorINS_8ArgumentESaISA_EES8_RKNS_6TargetE'/>
<use f='halide/src/Pipeline.cpp' l='285' c='_ZN6Halide8Pipeline17compile_to_objectERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKSt6vectorINS_8ArgumentESaISA_EES8_RKNS_6TargetE'/>
<use f='halide/src/Pipeline.cpp' l='294' c='_ZN6Halide8Pipeline17compile_to_headerERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKSt6vectorINS_8ArgumentESaISA_EES8_RKNS_6TargetE'/>
<use f='halide/src/Pipeline.cpp' l='302' c='_ZN6Halide8Pipeline19compile_to_assemblyERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKSt6vectorINS_8ArgumentESaISA_EES8_RKNS_6TargetE'/>
<use f='halide/src/Pipeline.cpp' l='310' c='_ZN6Halide8Pipeline12compile_to_cERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKSt6vectorINS_8ArgumentESaISA_EES8_RKNS_6TargetE'/>
<use f='halide/src/Pipeline.cpp' l='323' c='_ZN6Halide8Pipeline23compile_to_lowered_stmtERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKSt6vectorINS_8ArgumentESaISA_EENS_16StmtOutputFormatERKNS_6TargetE'/>
<use f='halide/src/Pipeline.cpp' l='331' c='_ZN6Halide8Pipeline25compile_to_static_libraryERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKSt6vectorINS_8ArgumentESaISA_EES8_RKNS_6TargetE'/>
<use f='halide/src/Pipeline.cpp' l='338' c='_ZN6Halide8Pipeline37compile_to_multitarget_static_libraryERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKSt6vectorINS_8ArgumentESaISA_EERKS96452959'/>
<use f='halide/src/Pipeline.cpp' l='349' c='_ZN6Halide8Pipeline35compile_to_multitarget_object_filesERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKSt6vectorINS_8ArgumentESaISA_EERKS9_I11711475'/>
<use f='halide/src/Pipeline.cpp' l='360' c='_ZN6Halide8Pipeline15compile_to_fileERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKSt6vectorINS_8ArgumentESaISA_EES8_RKNS_6TargetE'/>
<use f='halide/src/Pipeline.cpp' l='454' c='_ZN6Halide8Pipeline17compile_to_moduleERKSt6vectorINS_8ArgumentESaIS2_EERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKNS_6TargetENS_11LinkageTypeE'/>
<use f='halide/src/Pipeline.cpp' l='488' c='_ZN6Halide8Pipeline17compile_to_moduleERKSt6vectorINS_8ArgumentESaIS2_EERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKNS_6TargetENS_11LinkageTypeE'/>
<use f='halide/src/Pipeline.cpp' l='592' c='_ZN6Halide8Pipeline11compile_jitERKNS_6TargetE'/>
<size>8</size>
<use f='halide/src/PythonExtensionGen.cpp' l='132' c='_ZN6Halide8Internal18PythonExtensionGen7compileERKNS_6ModuleE'/>
<size>8</size>
<use f='halide/src/StmtToHtml.cpp' l='771' c='_ZN6Halide8Internal12_GLOBAL__N_110StmtToHtml5printERKNS_6ModuleE'/>
<use f='halide/src/StmtToHtml.cpp' l='868' c='_ZN6Halide8Internal13print_to_htmlERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKNS_6ModuleE'/>
<size>8</size>
<use f='halide/src/WasmExecutor.cpp' l='1331' c='_ZN6Halide8Internal18WasmModuleContentsC1ERKNS_6ModuleERKSt6vectorINS_8ArgumentESaIS6_EERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKSt3map9139084'/>
<use f='halide/src/WasmExecutor.cpp' l='1343' c='_ZN6Halide8Internal18WasmModuleContentsC1ERKNS_6ModuleERKSt6vectorINS_8ArgumentESaIS6_EERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKSt3map9139084'/>
<use f='halide/src/WasmExecutor.cpp' l='1572' c='_ZN6Halide8Internal10WasmModule7compileERKNS_6ModuleERKSt6vectorINS_8ArgumentESaIS6_EERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKSt3mapIS11257875'/>
<size>8</size>
