<dec f='halide/build/include/Halide.h' l='3785' type='8'/>
<use f='halide/build/include/Halide.h' l='11944'/>
<use f='halide/build/include/Halide.h' l='12963' c='_ZN6Halide8Internal15VariadicVisitor13dispatch_exprEPKNS0_12BaseExprNodeEDpOTL0__'/>
<use f='halide/build/include/Halide.h' l='13045' c='_ZN6Halide8Internal15VariadicVisitor13dispatch_stmtEPKNS0_12BaseStmtNodeEDpOTL0__'/>
<use f='halide/build/include/Halide.h' l='29030'/>
<use f='halide/build/include/Halide.h' l='29031'/>
<dec f='halide/src/Expr.h' l='38' type='8'/>
<use f='halide/src/IR.h' l='52'/>
<use f='halide/src/IRVisitor.h' l='181' c='_ZN6Halide8Internal15VariadicVisitor13dispatch_exprEPKNS0_12BaseExprNodeEDpOTL0__'/>
<use f='halide/src/IRVisitor.h' l='263' c='_ZN6Halide8Internal15VariadicVisitor13dispatch_stmtEPKNS0_12BaseStmtNodeEDpOTL0__'/>
<use f='halide/src/IRMatch.h' l='1916'/>
<use f='halide/src/IRMatch.h' l='1917'/>
<use f='halide/src/IRMatch.cpp' l='439' c='_ZN6Halide8Internal9IRMatcher12equal_helperERKNS0_12BaseExprNodeES4_'/>
