<dec f='halide/apps/hannk/util/error_util.h' l='37' type='std::ostringstream'/>
<use f='halide/apps/hannk/util/error_util.h' l='49' c='_ZN5hannk8internal6LoggerlsERKT_'/>
<offset>0</offset>
<use f='halide/apps/hannk/util/error_util.cpp' l='36' u='a' c='_ZN5hannk8internal6LoggerC1ENS_11LogSeverityEPKci'/>
<use f='halide/apps/hannk/util/error_util.cpp' l='43' u='a' c='_ZN5hannk8internal6LoggerC1ENS_11LogSeverityE'/>
<use f='halide/apps/hannk/util/error_util.cpp' l='47' u='m' c='_ZN5hannk8internal6Logger6finishEv'/>
<use f='halide/apps/hannk/util/error_util.cpp' l='47' u='m' c='_ZN5hannk8internal6Logger6finishEv'/>
<use f='halide/apps/hannk/util/error_util.cpp' l='48' u='a' c='_ZN5hannk8internal6Logger6finishEv'/>
<use f='halide/apps/hannk/util/error_util.cpp' l='51' u='m' c='_ZN5hannk8internal6Logger6finishEv'/>
<use f='halide/apps/hannk/util/error_util.cpp' l='65' u='a' c='_ZN5hannk8internal7CheckerC1EPKc'/>
<use f='halide/apps/hannk/util/error_util.cpp' l='70' u='a' c='_ZN5hannk8internal7CheckerC1EPKciS3_'/>
