<dec f='halide/apps/hannk/interpreter/elementwise_program.h' l='22' type='2'/>
<doc f='halide/apps/hannk/interpreter/elementwise_program.h' l='21'>// saturating_sub(load(op1), load(op2) + op3)</doc>
<use f='halide/apps/hannk/interpreter/elementwise_program.cpp' l='16' c='_ZN5hannk20ElementwiseAssembler9to_stringENS0_6OpCodeE'/>
<use f='halide/apps/hannk/interpreter/elementwise_program.cpp' l='48' c='_ZN5hannk12_GLOBAL__N_123get_opcode_operand_maskENS_20ElementwiseAssembler6OpCodeE'/>
<use f='halide/apps/hannk/interpreter/elementwise_program.cpp' l='156' u='r' c='_ZN5hannk20ElementwiseAssembler3subENS0_4SlotES1_s'/>
