<use f='halide/llvm-install/include/llvm/ADT/APInt.h' l='1883' c='_ZNK4llvm5APInt5magicEv'/>
<def f='halide/llvm-install/include/llvm/ADT/APInt.h' l='2023' ll='2026'/>
<size>24</size>
<doc f='halide/llvm-install/include/llvm/ADT/APInt.h' l='2022'>/// Magic data for optimising signed division by a constant.</doc>
<mbr r='llvm::APInt::ms::m' o='0' t='llvm::APInt'/>
<mbr r='llvm::APInt::ms::s' o='128' t='unsigned int'/>
