<dec f='halide/llvm-install/include/llvm/Support/WithColor.h' l='54' type='llvm::raw_ostream &amp;'/>
<use f='halide/llvm-install/include/llvm/Support/WithColor.h' l='75' u='w' c='_ZN4llvm9WithColorC1ERNS_11raw_ostreamENS1_6ColorsEbbNS_9ColorModeE'/>
<use f='halide/llvm-install/include/llvm/Support/WithColor.h' l='80' u='a' c='_ZN4llvm9WithColor3getEv'/>
<use f='halide/llvm-install/include/llvm/Support/WithColor.h' l='81' u='a' c='_ZN4llvm9WithColorcvRNS_11raw_ostreamEEv'/>
<use f='halide/llvm-install/include/llvm/Support/WithColor.h' l='83' c='_ZN4llvm9WithColorlsERT_'/>
<use f='halide/llvm-install/include/llvm/Support/WithColor.h' l='87' c='_ZN4llvm9WithColorlsERKT_'/>
<offset>0</offset>
