<dec f='halide/llvm-install/include/llvm/ADT/Triple.h' l='253' type='llvm::Triple::OSType'/>
<use f='halide/llvm-install/include/llvm/ADT/Triple.h' l='268' u='w' c='_ZN4llvm6TripleC1Ev'/>
<use f='halide/llvm-install/include/llvm/ADT/Triple.h' l='278' u='r' c='_ZNK4llvm6TripleeqERKS0_'/>
<use f='halide/llvm-install/include/llvm/ADT/Triple.h' l='278' u='r' c='_ZNK4llvm6TripleeqERKS0_'/>
<use f='halide/llvm-install/include/llvm/ADT/Triple.h' l='314' u='r' c='_ZNK4llvm6Triple5getOSEv'/>
<offset>352</offset>
<doc f='halide/llvm-install/include/llvm/ADT/Triple.h' l='252'>/// The parsed OS type.</doc>
