<use f='halide/llvm-install/include/llvm/ADT/fallible_iterator.h' l='99' c='_ZN4llvm17fallible_iteratordeEv'/>
<use f='halide/llvm-install/include/llvm/ADT/fallible_iterator.h' l='102' c='_ZNK4llvm17fallible_iteratordeEv'/>
<use f='halide/llvm-install/include/llvm/ADT/fallible_iterator.h' l='108' u='c' c='_ZN4llvm17fallible_iteratorptEv'/>
<use f='halide/llvm-install/include/llvm/ADT/fallible_iterator.h' l='115' u='c' c='_ZNK4llvm17fallible_iteratorptEv'/>
<use f='halide/llvm-install/include/llvm/ADT/fallible_iterator.h' l='127' u='c' c='_ZN4llvm17fallible_iteratorppEv'/>
<use f='halide/llvm-install/include/llvm/ADT/fallible_iterator.h' l='143' u='c' c='_ZN4llvm17fallible_iteratormmEv'/>
<use f='halide/llvm-install/include/llvm/ADT/fallible_iterator.h' l='196' u='w' c='_ZN4llvm17fallible_iteratorC1ET_PNS_5ErrorE'/>
<dec f='halide/llvm-install/include/llvm/ADT/fallible_iterator.h' l='214' type='Underlying'/>
