<dec f='halide/llvm-install/include/llvm/IR/DiagnosticInfo.h' l='265' type='const llvm::Module &amp;'/>
<use f='halide/llvm-install/include/llvm/IR/DiagnosticInfo.h' l='271' u='w' c='_ZN4llvm42DiagnosticInfoIgnoringInvalidDebugMetadataC1ERKNS_6ModuleENS_18DiagnosticSeverityE'/>
<use f='halide/llvm-install/include/llvm/IR/DiagnosticInfo.h' l='273' u='a' c='_ZNK4llvm42DiagnosticInfoIgnoringInvalidDebugMetadata9getModuleEv'/>
<offset>128</offset>
<doc f='halide/llvm-install/include/llvm/IR/DiagnosticInfo.h' l='264'>/// The module that is concerned by this debug metadata version diagnostic.</doc>
