<dec f='halide/llvm-install/include/llvm/Support/raw_ostream.h' l='637' type='SmallVectorImpl&lt;char&gt; &amp;'/>
<use f='halide/llvm-install/include/llvm/Support/raw_ostream.h' l='652' u='w' c='_ZN4llvm19raw_svector_ostreamC1ERNS_15SmallVectorImplIcEE'/>
<use f='halide/llvm-install/include/llvm/Support/raw_ostream.h' l='661' u='m' c='_ZNK4llvm19raw_svector_ostream3strEv'/>
<use f='halide/llvm-install/include/llvm/Support/raw_ostream.h' l='661' u='m' c='_ZNK4llvm19raw_svector_ostream3strEv'/>
<offset>512</offset>
