<use f='halide/llvm-install/include/llvm/Analysis/IVDescriptors.h' l='272' u='r' c='_ZNK4llvm19InductionDescriptor7getKindEv'/>
<use f='halide/llvm-install/include/llvm/Analysis/IVDescriptors.h' l='309' u='r' c='_ZN4llvm19InductionDescriptor16hasUnsafeAlgebraEv'/>
<use f='halide/llvm-install/include/llvm/Analysis/IVDescriptors.h' l='316' u='r' c='_ZN4llvm19InductionDescriptor20getUnsafeAlgebraInstEv'/>
<dec f='halide/llvm-install/include/llvm/Analysis/IVDescriptors.h' l='346' type='llvm::InductionDescriptor::InductionKind'/>
<offset>192</offset>
<doc f='halide/llvm-install/include/llvm/Analysis/IVDescriptors.h' l='345'>/// Induction kind.</doc>
