<dec f='halide/llvm-install/include/llvm/IR/DiagnosticInfo.h' l='238' type='const llvm::Module &amp;'/>
<use f='halide/llvm-install/include/llvm/IR/DiagnosticInfo.h' l='247' u='w' c='_ZN4llvm34DiagnosticInfoDebugMetadataVersionC1ERKNS_6ModuleEjNS_18DiagnosticSeverityE'/>
<use f='halide/llvm-install/include/llvm/IR/DiagnosticInfo.h' l='250' u='a' c='_ZNK4llvm34DiagnosticInfoDebugMetadataVersion9getModuleEv'/>
<offset>128</offset>
<doc f='halide/llvm-install/include/llvm/IR/DiagnosticInfo.h' l='237'>/// The module that is concerned by this debug metadata version diagnostic.</doc>
