<use f='halide/llvm-install/include/llvm/BinaryFormat/Magic.h' l='55' u='r' c='_ZNK4llvm10file_magic9is_objectEv'/>
<use f='halide/llvm-install/include/llvm/BinaryFormat/Magic.h' l='58' u='w' c='_ZN4llvm10file_magicC1ENS0_4ImplE'/>
<use f='halide/llvm-install/include/llvm/BinaryFormat/Magic.h' l='59' u='r' c='_ZNK4llvm10file_magiccvNS0_4ImplEEv'/>
<dec f='halide/llvm-install/include/llvm/BinaryFormat/Magic.h' l='62' type='llvm::file_magic::Impl'/>
<offset>0</offset>
