<dec f='halide/llvm-install/include/llvm/Support/BranchProbability.h' l='35' type='const uint32_t'/>
<use f='halide/llvm-install/include/llvm/Support/BranchProbability.h' l='50' u='r' c='_ZN4llvm17BranchProbability6getOneEv'/>
<use f='halide/llvm-install/include/llvm/Support/BranchProbability.h' l='66' u='r' c='_ZN4llvm17BranchProbability14getDenominatorEv'/>
<use f='halide/llvm-install/include/llvm/Support/BranchProbability.h' l='69' u='r' c='_ZNK4llvm17BranchProbability8getComplEv'/>
<use f='halide/llvm-install/include/llvm/Support/BranchProbability.h' l='95' u='r' c='_ZN4llvm17BranchProbabilitypLES0_'/>
<use f='halide/llvm-install/include/llvm/Support/BranchProbability.h' l='95' u='r' c='_ZN4llvm17BranchProbabilitypLES0_'/>
<use f='halide/llvm-install/include/llvm/Support/BranchProbability.h' l='110' u='r' c='_ZN4llvm17BranchProbabilitymLES0_'/>
<use f='halide/llvm-install/include/llvm/Support/BranchProbability.h' l='110' u='r' c='_ZN4llvm17BranchProbabilitymLES0_'/>
<use f='halide/llvm-install/include/llvm/Support/BranchProbability.h' l='117' u='r' c='_ZN4llvm17BranchProbabilitymLEj'/>
<use f='halide/llvm-install/include/llvm/Support/BranchProbability.h' l='117' u='r' c='_ZN4llvm17BranchProbabilitymLEj'/>
<use f='halide/llvm-install/include/llvm/Support/BranchProbability.h' l='124' u='r' c='_ZN4llvm17BranchProbabilitydVES0_'/>
<use f='halide/llvm-install/include/llvm/Support/BranchProbability.h' l='243' u='r' c='_ZN4llvm17BranchProbability22normalizeProbabilitiesET_S1_'/>
<doc f='halide/llvm-install/include/llvm/Support/BranchProbability.h' l='34'>// Denominator, which is a constant value.</doc>
