<dec f='halide/llvm-install/include/llvm/ADT/Triple.h' l='206' type='1'/>
<use f='halide/llvm-install/include/llvm/ADT/Triple.h' l='530' u='r' c='_ZNK4llvm6Triple16isGNUEnvironmentEv'/>
<use f='halide/llvm-install/include/llvm/ADT/Triple.h' l='573' u='r' c='_ZNK4llvm6Triple23isWindowsGNUEnvironmentEv'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='386' u='r' c='_ZN6Halide8Internal21get_triple_for_targetERKNS_6TargetE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='476' u='r' c='_ZN6Halide8Internal21get_triple_for_targetERKNS_6TargetE'/>
