<dec f='halide/llvm-install/include/llvm/IR/IRBuilder.h' l='368' type='llvm::IRBuilderBase &amp;'/>
<use f='halide/llvm-install/include/llvm/IR/IRBuilder.h' l='375' u='w' c='_ZN4llvm13IRBuilderBase16InsertPointGuardC1ERS0_'/>
<use f='halide/llvm-install/include/llvm/IR/IRBuilder.h' l='382' u='m' c='_ZN4llvm13IRBuilderBase16InsertPointGuardD1Ev'/>
<use f='halide/llvm-install/include/llvm/IR/IRBuilder.h' l='383' u='m' c='_ZN4llvm13IRBuilderBase16InsertPointGuardD1Ev'/>
<offset>0</offset>
