<dec f='halide/llvm-install/include/llvm/Support/raw_ostream.h' l='437' type='std::error_code'/>
<use f='halide/llvm-install/include/llvm/Support/raw_ostream.h' l='457' u='w' c='_ZN4llvm14raw_fd_ostream14error_detectedESt10error_code'/>
<use f='halide/llvm-install/include/llvm/Support/raw_ostream.h' l='507' u='r' c='_ZNK4llvm14raw_fd_ostream5errorEv'/>
<use f='halide/llvm-install/include/llvm/Support/raw_ostream.h' l='513' u='m' c='_ZNK4llvm14raw_fd_ostream9has_errorEv'/>
<use f='halide/llvm-install/include/llvm/Support/raw_ostream.h' l='524' u='w' c='_ZN4llvm14raw_fd_ostream11clear_errorEv'/>
<offset>576</offset>
