<dec f='halide/llvm-install/include/llvm/IR/Metadata.h' l='1245' type='MDNode::op_iterator'/>
<use f='halide/llvm-install/include/llvm/IR/Metadata.h' l='1249' u='w' c='_ZN4llvm22TypedMDOperandIteratorC1EPKNS_9MDOperandE'/>
<use f='halide/llvm-install/include/llvm/IR/Metadata.h' l='1251' u='r' c='_ZNK4llvm22TypedMDOperandIteratordeEv'/>
<use f='halide/llvm-install/include/llvm/IR/Metadata.h' l='1254' u='w' c='_ZN4llvm22TypedMDOperandIteratorppEv'/>
<use f='halide/llvm-install/include/llvm/IR/Metadata.h' l='1260' u='w' c='_ZN4llvm22TypedMDOperandIteratorppEi'/>
<use f='halide/llvm-install/include/llvm/IR/Metadata.h' l='1264' c='_ZNK4llvm22TypedMDOperandIteratoreqERKNS_22TypedMDOperandIteratorIT_EE'/>
<use f='halide/llvm-install/include/llvm/IR/Metadata.h' l='1265' c='_ZNK4llvm22TypedMDOperandIteratorneERKNS_22TypedMDOperandIteratorIT_EE'/>
