<use f='halide/llvm-install/include/llvm/IR/InstrTypes.h' l='1998' u='r' c='_ZNK4llvm8CallBase27hasClobberingOperandBundlesEv'/>
<use f='halide/llvm-install/include/llvm/IR/InstrTypes.h' l='1999' u='r' c='_ZNK4llvm8CallBase27hasClobberingOperandBundlesEv'/>
<dec f='halide/llvm-install/include/llvm/IR/InstrTypes.h' l='2079' type='StringMapEntry&lt;uint32_t&gt; *'/>
<use f='halide/llvm-install/include/llvm/IR/InstrTypes.h' l='2090' u='r' c='_ZNK4llvm8CallBase12BundleOpInfoeqERKS1_'/>
<use f='halide/llvm-install/include/llvm/IR/InstrTypes.h' l='2090' u='r' c='_ZNK4llvm8CallBase12BundleOpInfoeqERKS1_'/>
<use f='halide/llvm-install/include/llvm/IR/InstrTypes.h' l='2100' u='r' c='_ZNK4llvm8CallBase29operandBundleFromBundleOpInfoERKNS0_12BundleOpInfoE'/>
<offset>0</offset>
<doc f='halide/llvm-install/include/llvm/IR/InstrTypes.h' l='2077'>/// The operand bundle tag, interned by
    /// LLVMContextImpl::getOrInsertBundleTag.</doc>
