<dec f='halide/llvm-install/include/llvm/ExecutionEngine/ExecutionEngine.h' l='114' type='const llvm::DataLayout'/>
<use f='halide/llvm-install/include/llvm/ExecutionEngine/ExecutionEngine.h' l='197' u='a' c='_ZNK4llvm15ExecutionEngine13getDataLayoutEv'/>
<use f='halide/llvm-install/include/llvm/ExecutionEngine/ExecutionEngine.h' l='505' u='w' c='_ZN4llvm15ExecutionEngineC1ENS_10DataLayoutE'/>
<offset>704</offset>
<doc f='halide/llvm-install/include/llvm/ExecutionEngine/ExecutionEngine.h' l='108'>/// The target data for the platform for which execution is being performed.
  ///
  /// Note: the DataLayout is LLVMContext specific because it has an
  /// internal cache based on type pointers. It makes unsafe to reuse the
  /// ExecutionEngine across context, we don&apos;t enforce this rule but undefined
  /// behavior can occurs if the user tries to do it.</doc>
