<use f='halide/llvm-install/include/llvm/Support/Memory.h' l='142' u='w' c='_ZN4llvm3sys17OwningMemoryBlockC1ENS0_11MemoryBlockE'/>
<use f='halide/llvm-install/include/llvm/Support/Memory.h' l='144' u='w' c='_ZN4llvm3sys17OwningMemoryBlockC1EOS1_'/>
<use f='halide/llvm-install/include/llvm/Support/Memory.h' l='144' u='r' c='_ZN4llvm3sys17OwningMemoryBlockC1EOS1_'/>
<use f='halide/llvm-install/include/llvm/Support/Memory.h' l='145' u='w' c='_ZN4llvm3sys17OwningMemoryBlockC1EOS1_'/>
<use f='halide/llvm-install/include/llvm/Support/Memory.h' l='148' u='w' c='_ZN4llvm3sys17OwningMemoryBlockaSEOS1_'/>
<use f='halide/llvm-install/include/llvm/Support/Memory.h' l='148' u='r' c='_ZN4llvm3sys17OwningMemoryBlockaSEOS1_'/>
<use f='halide/llvm-install/include/llvm/Support/Memory.h' l='149' u='w' c='_ZN4llvm3sys17OwningMemoryBlockaSEOS1_'/>
<use f='halide/llvm-install/include/llvm/Support/Memory.h' l='153' u='a' c='_ZN4llvm3sys17OwningMemoryBlockD1Ev'/>
<use f='halide/llvm-install/include/llvm/Support/Memory.h' l='155' u='m' c='_ZNK4llvm3sys17OwningMemoryBlock4baseEv'/>
<use f='halide/llvm-install/include/llvm/Support/Memory.h' l='158' u='m' c='_ZNK4llvm3sys17OwningMemoryBlock13allocatedSizeEv'/>
<use f='halide/llvm-install/include/llvm/Support/Memory.h' l='159' u='r' c='_ZNK4llvm3sys17OwningMemoryBlock14getMemoryBlockEv'/>
<dec f='halide/llvm-install/include/llvm/Support/Memory.h' l='161' type='llvm::sys::MemoryBlock'/>
<offset>0</offset>
