<use f='halide/llvm-install/include/llvm/PassAnalysisSupport.h' l='160' u='w' c='_ZN4llvm16AnalysisResolverC1ERNS_13PMDataManagerE'/>
<use f='halide/llvm-install/include/llvm/PassAnalysisSupport.h' l='162' u='a' c='_ZN4llvm16AnalysisResolver16getPMDataManagerEv'/>
<dec f='halide/llvm-install/include/llvm/PassAnalysisSupport.h' l='200' type='llvm::PMDataManager &amp;'/>
<offset>192</offset>
<doc f='halide/llvm-install/include/llvm/PassAnalysisSupport.h' l='199'>/// PassManager that is used to resolve analysis info</doc>
