<use f='halide/llvm-install/include/llvm/IR/InstrTypes.h' l='1064' u='w' c='_ZN4llvm16OperandBundleUseC1EPNS_14StringMapEntryIjEENS_8ArrayRefINS_3UseEEE'/>
<use f='halide/llvm-install/include/llvm/IR/InstrTypes.h' l='1079' u='r' c='_ZNK4llvm16OperandBundleUse10getTagNameEv'/>
<use f='halide/llvm-install/include/llvm/IR/InstrTypes.h' l='1088' u='r' c='_ZNK4llvm16OperandBundleUse8getTagIDEv'/>
<dec f='halide/llvm-install/include/llvm/IR/InstrTypes.h' l='1108' type='StringMapEntry&lt;uint32_t&gt; *'/>
<offset>128</offset>
<doc f='halide/llvm-install/include/llvm/IR/InstrTypes.h' l='1107'>/// Pointer to an entry in LLVMContextImpl::getOrInsertBundleTag.</doc>
