<dec f='halide/llvm-install/include/llvm/IR/IRBuilder.h' l='120' type='llvm::BasicBlock *'/>
<use f='halide/llvm-install/include/llvm/IR/IRBuilder.h' l='150' u='r' c='_ZNK4llvm13IRBuilderBase6InsertEPT_RKNS_5TwineE'/>
<use f='halide/llvm-install/include/llvm/IR/IRBuilder.h' l='174' u='w' c='_ZN4llvm13IRBuilderBase19ClearInsertionPointEv'/>
<use f='halide/llvm-install/include/llvm/IR/IRBuilder.h' l='178' u='r' c='_ZNK4llvm13IRBuilderBase14GetInsertBlockEv'/>
<use f='halide/llvm-install/include/llvm/IR/IRBuilder.h' l='185' u='w' c='_ZN4llvm13IRBuilderBase14SetInsertPointEPNS_10BasicBlockE'/>
<use f='halide/llvm-install/include/llvm/IR/IRBuilder.h' l='186' u='r' c='_ZN4llvm13IRBuilderBase14SetInsertPointEPNS_10BasicBlockE'/>
<use f='halide/llvm-install/include/llvm/IR/IRBuilder.h' l='192' u='w' c='_ZN4llvm13IRBuilderBase14SetInsertPointEPNS_11InstructionE'/>
<use f='halide/llvm-install/include/llvm/IR/IRBuilder.h' l='201' u='w' c='_ZN4llvm13IRBuilderBase14SetInsertPointEPNS_10BasicBlockENS_14ilist_iteratorINS_12ilist_detail12node_optionsINS_11InstructionELb0ELb0EvEELb0ELb0EEE'/>
<use f='halide/llvm-install/include/llvm/IR/IRBuilder.h' l='347' u='r' c='_ZN4llvm13IRBuilderBase28setConstrainedFPFunctionAttrEv'/>
<use f='halide/llvm-install/include/llvm/IR/IRBuilder.h' l='1693' u='r' c='_ZN4llvm13IRBuilderBase12CreateAllocaEPNS_4TypeEjPNS_5ValueERKNS_5TwineE'/>
<use f='halide/llvm-install/include/llvm/IR/IRBuilder.h' l='1700' u='r' c='_ZN4llvm13IRBuilderBase12CreateAllocaEPNS_4TypeEPNS_5ValueERKNS_5TwineE'/>
<use f='halide/llvm-install/include/llvm/IR/IRBuilder.h' l='1773' u='r' c='_ZN4llvm13IRBuilderBase17CreateAlignedLoadEPNS_4TypeEPNS_5ValueENS_10MaybeAlignEbRKNS_5TwineE'/>
<use f='halide/llvm-install/include/llvm/IR/IRBuilder.h' l='1831' u='r' c='_ZN4llvm13IRBuilderBase18CreateAlignedStoreEPNS_5ValueES2_NS_10MaybeAlignEb'/>
<use f='halide/llvm-install/include/llvm/IR/IRBuilder.h' l='1845' u='r' c='_ZN4llvm13IRBuilderBase19CreateAtomicCmpXchgEPNS_5ValueES2_S2_NS_14AtomicOrderingES3_h'/>
<use f='halide/llvm-install/include/llvm/IR/IRBuilder.h' l='1854' u='r' c='_ZN4llvm13IRBuilderBase15CreateAtomicRMWENS_13AtomicRMWInst5BinOpEPNS_5ValueES4_NS_14AtomicOrderingEh'/>
<offset>384</offset>
