<dec f='halide/llvm-install/include/llvm/Passes/PassBuilder.h' l='252' type='const llvm::PassBuilder::OptimizationLevel'/>
<doc f='halide/llvm-install/include/llvm/Passes/PassBuilder.h' l='245'>/// A very specialized mode that will optimize for code size at any and all
    /// costs.
    ///
    /// This is useful primarily when there are absolute size limitations and
    /// any effort taken to reduce the size is worth it regardless of the
    /// execution time impact. You should expect this level to produce rather
    /// slow, but very small, code.</doc>
