<dec f='halide/llvm-install/include/llvm/Analysis/MemoryDependenceAnalysis.h' l='211' type='llvm::BasicBlock *'/>
<use f='halide/llvm-install/include/llvm/Analysis/MemoryDependenceAnalysis.h' l='216' u='w' c='_ZN4llvm16NonLocalDepEntryC1EPNS_10BasicBlockENS_12MemDepResultE'/>
<use f='halide/llvm-install/include/llvm/Analysis/MemoryDependenceAnalysis.h' l='219' u='w' c='_ZN4llvm16NonLocalDepEntryC1EPNS_10BasicBlockE'/>
<use f='halide/llvm-install/include/llvm/Analysis/MemoryDependenceAnalysis.h' l='222' u='r' c='_ZNK4llvm16NonLocalDepEntry5getBBEv'/>
<use f='halide/llvm-install/include/llvm/Analysis/MemoryDependenceAnalysis.h' l='228' u='r' c='_ZNK4llvm16NonLocalDepEntryltERKS0_'/>
<use f='halide/llvm-install/include/llvm/Analysis/MemoryDependenceAnalysis.h' l='228' u='r' c='_ZNK4llvm16NonLocalDepEntryltERKS0_'/>
<offset>0</offset>
