<use f='halide/build/_deps/pybind11-src/include/pybind11/detail/init.h' l='44'/>
<use f='halide/build/_deps/pybind11-src/include/pybind11/detail/init.h' l='48' c='_ZN8pybind116detail8initimpl8is_aliasEPNT_4typeE'/>
<use f='halide/build/_deps/pybind11-src/include/pybind11/detail/init.h' l='72' c='_ZN8pybind116detail8initimpl24construct_alias_from_cppESt17integral_constantIbLb1EERNS0_16value_and_holderEONT_4typeE'/>
<use f='halide/build/_deps/pybind11-src/include/pybind11/detail/init.h' l='77' c='_ZN8pybind116detail8initimpl24construct_alias_from_cppESt17integral_constantIbLb0EERNS0_16value_and_holderEONT_4typeE'/>
<use f='halide/build/_deps/pybind11-src/include/pybind11/detail/init.h' l='96' c='_ZN8pybind116detail8initimpl9constructERNS0_16value_and_holderEPNT_4typeEb'/>
<use f='halide/build/_deps/pybind11-src/include/pybind11/detail/init.h' l='126' c='_ZN8pybind116detail8initimpl9constructERNS0_16value_and_holderEPNT_10type_aliasEb'/>
<use f='halide/build/_deps/pybind11-src/include/pybind11/detail/init.h' l='150' c='_ZN8pybind116detail8initimpl9constructERNS0_16value_and_holderEONT_4typeEb'/>
<use f='halide/build/_deps/pybind11-src/include/pybind11/detail/init.h' l='151' c='_ZN8pybind116detail8initimpl9constructERNS0_16value_and_holderEONT_4typeEb'/>
<use f='halide/build/_deps/pybind11-src/include/pybind11/detail/init.h' l='156' c='_ZN8pybind116detail8initimpl9constructERNS0_16value_and_holderEONT_4typeEb'/>
<use f='halide/build/_deps/pybind11-src/include/pybind11/detail/init.h' l='175' c='_ZN8pybind116detail8initimpl11constructor7executeERTL0__DpRKTL0_0_'/>
<use f='halide/build/_deps/pybind11-src/include/pybind11/detail/init.h' l='181'/>
<use f='halide/build/_deps/pybind11-src/include/pybind11/detail/init.h' l='185' c='_ZN8pybind116detail8initimpl11constructor7executeERTL0__DpRKTL0_0_'/>
<use f='halide/build/_deps/pybind11-src/include/pybind11/detail/init.h' l='193'/>
