<def f='halide/build-apps/ruy/ruy/prepacked_cache.h' l='43'/>
<use f='halide/build-apps/ruy/ruy/prepacked_cache.h' l='127' c='_ZN3ruy14PrepackedCache3GetEPKvPNS_5PEMatE'/>
<use f='halide/build-apps/ruy/ruy/prepacked_cache.cc' l='79' c='_ZN3ruy14PrepackedCache3GetEPKvPNS_5PEMatE'/>
