<dec f='halide/build-apps/_deps/tflite-src/tensorflow/lite/c/common.h' l='798' type='void *(*)(TfLiteContext *, const char *, size_t)'/>
<use f='halide/apps/hannk/delegate/hannk_delegate.cpp' l='455' u='w' c='_ZN5hannk12_GLOBAL__N_119HannkDelegateKernel15GetRegistrationEv'/>
<offset>0</offset>
<doc f='halide/build-apps/_deps/tflite-src/tensorflow/lite/c/common.h' l='783'>// Initializes the op from serialized data.
  // If a built-in op:
  //   `buffer` is the op&apos;s params data (TfLiteLSTMParams*).
  //   `length` is zero.
  // If custom op:
  //   `buffer` is the op&apos;s `custom_options`.
  //   `length` is the size of the buffer.
  //
  // Returns a type-punned (i.e. void*) opaque data (e.g. a primitive pointer
  // or an instance of a struct).
  //
  // The returned pointer will be stored with the node in the `user_data` field,
  // accessible within prepare and invoke functions below.
  // NOTE: if the data is already in the desired format, simply implement this
  // function to return `nullptr` and implement the free function to be a no-op.</doc>
<use f='halide/build-apps/_deps/tflite-src/tensorflow/lite/core/subgraph.h' l='412' u='r' c='_ZN6tflite8Subgraph6OpInitERK18TfLiteRegistrationPKcm'/>
<use f='halide/build-apps/_deps/tflite-src/tensorflow/lite/core/subgraph.h' l='413' u='r' c='_ZN6tflite8Subgraph6OpInitERK18TfLiteRegistrationPKcm'/>
