<dec f='x264/filters/video/video.h' l='44' type='int (*)(hnd_t *, cli_vid_filter_t *, video_info_t *, x264_param_t *, char *)'/>
<offset>128</offset>
<doc f='x264/filters/video/video.h' l='41'>/* init: initializes the filter given the input clip properties and parameter to adjust them as necessary
     * with the given options provided by the user.
     * returns 0 on success, nonzero on error. */</doc>
<use f='x264/filters/video/video.c' l='72' u='r' c='x264_init_vid_filter'/>
