<dec f='llvm/build/lib/Target/Hexagon/HexagonGenDFAPacketizer.inc' l='11911' type='uint64_t'/>
<offset>64</offset>
<doc f='llvm/build/lib/Target/Hexagon/HexagonGenDFAPacketizer.inc' l='11911'>// The input symbol that causes this transition.</doc>
