<dec f='llvm/libcxxabi/src/demangle/ItaniumDemangle.h' l='1643' type='const (anonymous namespace)::itanium_demangle::Node *'/>
<use f='llvm/libcxxabi/src/demangle/ItaniumDemangle.h' l='1649' u='w' c='_ZN12_GLOBAL__N_116itanium_demangle10MemberExprC1EPKNS0_4NodeENS0_10StringViewES4_'/>
<use f='llvm/libcxxabi/src/demangle/ItaniumDemangle.h' l='1651' c='_ZNK12_GLOBAL__N_116itanium_demangle10MemberExpr5matchET_'/>
<use f='llvm/libcxxabi/src/demangle/ItaniumDemangle.h' l='1654' u='r' c='_ZNK12_GLOBAL__N_116itanium_demangle10MemberExpr9printLeftERNS0_12OutputStreamE'/>
<offset>128</offset>
