<dec f='llvm/clang/include/clang-c/Index.h' l='6226' type='CXModule'/>
<offset>64</offset>
<doc f='llvm/clang/include/clang-c/Index.h' l='6223'>/**
   * The imported module or NULL if the AST file is a PCH.
   */</doc>
<use f='llvm/clang/tools/c-index-test/c-index-test.c' l='3694' u='r' c='index_importedASTFile'/>
<use f='llvm/clang/tools/c-index-test/c-index-test.c' l='3695' u='r' c='index_importedASTFile'/>
