<dec f='llvm/build/lib/Target/AMDGPU/R600GenDFAPacketizer.inc' l='76' type='uint64_t'/>
<offset>64</offset>
<doc f='llvm/build/lib/Target/AMDGPU/R600GenDFAPacketizer.inc' l='76'>// The input symbol that causes this transition.</doc>
