<dec f='llvm/libcxxabi/src/demangle/ItaniumDemangle.h' l='701' type='const (anonymous namespace)::itanium_demangle::Node *'/>
<use f='llvm/libcxxabi/src/demangle/ItaniumDemangle.h' l='703' u='w' c='_ZN12_GLOBAL__N_116itanium_demangle12NoexceptSpecC1EPKNS0_4NodeE'/>
<use f='llvm/libcxxabi/src/demangle/ItaniumDemangle.h' l='705' c='_ZNK12_GLOBAL__N_116itanium_demangle12NoexceptSpec5matchET_'/>
<use f='llvm/libcxxabi/src/demangle/ItaniumDemangle.h' l='709' u='r' c='_ZNK12_GLOBAL__N_116itanium_demangle12NoexceptSpec9printLeftERNS0_12OutputStreamE'/>
<offset>128</offset>
