<dec f='llvm/libcxxabi/src/demangle/ItaniumDemangle.h' l='1923' type='const (anonymous namespace)::itanium_demangle::Node *'/>
<use f='llvm/libcxxabi/src/demangle/ItaniumDemangle.h' l='1927' u='w' c='_ZN12_GLOBAL__N_116itanium_demangle10BracedExprC1EPKNS0_4NodeES4_b'/>
<use f='llvm/libcxxabi/src/demangle/ItaniumDemangle.h' l='1929' c='_ZNK12_GLOBAL__N_116itanium_demangle10BracedExpr5matchET_'/>
<use f='llvm/libcxxabi/src/demangle/ItaniumDemangle.h' l='1940' u='r' c='_ZNK12_GLOBAL__N_116itanium_demangle10BracedExpr9printLeftERNS0_12OutputStreamE'/>
<use f='llvm/libcxxabi/src/demangle/ItaniumDemangle.h' l='1940' u='r' c='_ZNK12_GLOBAL__N_116itanium_demangle10BracedExpr9printLeftERNS0_12OutputStreamE'/>
<use f='llvm/libcxxabi/src/demangle/ItaniumDemangle.h' l='1942' u='r' c='_ZNK12_GLOBAL__N_116itanium_demangle10BracedExpr9printLeftERNS0_12OutputStreamE'/>
<offset>192</offset>
