<use f='llvm/clang/unittests/Tooling/Syntax/TokensTest.cpp' l='81' u='w' c='_ZN12_GLOBAL__N_112KindMatcherP10gmock_ImplC1ET_'/>
<dec f='llvm/clang/unittests/Tooling/Syntax/TokensTest.cpp' l='81' type='K_type'/>
<use f='llvm/clang/unittests/Tooling/Syntax/TokensTest.cpp' l='81' c='_ZNK12_GLOBAL__N_112KindMatcherP10gmock_Impl17FormatDescriptionB5cxx11Eb'/>
<use f='llvm/clang/unittests/Tooling/Syntax/TokensTest.cpp' l='81' c='_ZNK12_GLOBAL__N_112KindMatcherP10gmock_Impl15MatchAndExplainETL0__PN7testing19MatchResultListenerE'/>
