<use f='llvm/llvm/unittests/FuzzMutate/OperationsTest.cpp' l='75' u='w' c='_ZN12_GLOBAL__N_115HasTypeMatcherP10gmock_ImplC1ET_'/>
<dec f='llvm/llvm/unittests/FuzzMutate/OperationsTest.cpp' l='75' type='T_type'/>
<use f='llvm/llvm/unittests/FuzzMutate/OperationsTest.cpp' l='75' c='_ZNK12_GLOBAL__N_115HasTypeMatcherP10gmock_Impl17FormatDescriptionB5cxx11Eb'/>
<use f='llvm/llvm/unittests/FuzzMutate/OperationsTest.cpp' l='75' c='_ZNK12_GLOBAL__N_115HasTypeMatcherP10gmock_Impl15MatchAndExplainETL0__PN7testing19MatchResultListenerE'/>
