<dec f='llvm/libcxxabi/src/demangle/ItaniumDemangle.h' l='127' type='(anonymous namespace)::itanium_demangle::Node::Kind'/>
<use f='llvm/libcxxabi/src/demangle/ItaniumDemangle.h' l='146' u='w' c='_ZN12_GLOBAL__N_116itanium_demangle4NodeC1ENS1_4KindENS1_5CacheES3_S3_'/>
<use f='llvm/libcxxabi/src/demangle/ItaniumDemangle.h' l='176' u='r' c='_ZNK12_GLOBAL__N_116itanium_demangle4Node7getKindEv'/>
<use f='llvm/libcxxabi/src/demangle/ItaniumDemangle.h' l='2197' u='r' c='_ZNK12_GLOBAL__N_116itanium_demangle4Node5visitET_'/>
<offset>64</offset>
