<use f='llvm/llvm/unittests/FuzzMutate/OperationsTest.cpp' l='71' u='w' c='_ZN12_GLOBAL__N_118TypesMatchMatcherP10gmock_ImplC1ET_'/>
<dec f='llvm/llvm/unittests/FuzzMutate/OperationsTest.cpp' l='71' type='V_type'/>
<use f='llvm/llvm/unittests/FuzzMutate/OperationsTest.cpp' l='71' u='c' c='_ZNK12_GLOBAL__N_118TypesMatchMatcherP10gmock_Impl17FormatDescriptionB5cxx11Eb'/>
<use f='llvm/llvm/unittests/FuzzMutate/OperationsTest.cpp' l='71' c='_ZNK12_GLOBAL__N_118TypesMatchMatcherP10gmock_Impl17FormatDescriptionB5cxx11Eb'/>
<use f='llvm/llvm/unittests/FuzzMutate/OperationsTest.cpp' l='72' u='c' c='_ZNK12_GLOBAL__N_118TypesMatchMatcherP10gmock_Impl15MatchAndExplainETL0__PN7testing19MatchResultListenerE'/>
