<dec f='llvm/compiler-rt/lib/asan/asan_descriptions.h' l='38' type='void __asan::AsanThreadIdAndName::Init(__sanitizer::u32 tid, const char * tname)'/>
<use f='llvm/compiler-rt/lib/asan/asan_descriptions.cpp' l='23' u='c' c='__asan::AsanThreadIdAndName::AsanThreadIdAndName'/>
<use f='llvm/compiler-rt/lib/asan/asan_descriptions.cpp' l='28' u='c' c='__asan::AsanThreadIdAndName::AsanThreadIdAndName'/>
<use f='llvm/compiler-rt/lib/asan/asan_descriptions.cpp' l='32' u='c' c='__asan::AsanThreadIdAndName::AsanThreadIdAndName'/>
<def f='llvm/compiler-rt/lib/asan/asan_descriptions.cpp' l='36' ll='41' type='void __asan::AsanThreadIdAndName::Init(__sanitizer::u32 tid, const char * tname)'/>
