<dec f='llvm/compiler-rt/lib/asan/asan_thread.h' l='70' type='void __asan::AsanThread::Init(const __asan::AsanThread::InitOptions * options = nullptr)'/>
<def f='llvm/compiler-rt/lib/asan/asan_thread.cpp' l='221' ll='249' type='void __asan::AsanThread::Init(const __asan::AsanThread::InitOptions * options = nullptr)'/>
<use f='llvm/compiler-rt/lib/asan/asan_thread.cpp' l='257' u='c' c='__asan::AsanThread::ThreadStart'/>
