<dec f='llvm/compiler-rt/lib/hwasan/hwasan_thread.h' l='26' type='void __hwasan::Thread::Init(__sanitizer::uptr stack_buffer_start, __sanitizer::uptr stack_buffer_size)'/>
<use f='llvm/compiler-rt/lib/hwasan/hwasan_thread_list.h' l='102' u='c' c='__hwasan::HwasanThreadList::CreateCurrentThread'/>
<doc f='llvm/compiler-rt/lib/hwasan/hwasan_thread.h' l='26'>// Must be called from the thread itself.</doc>
<def f='llvm/compiler-rt/lib/hwasan/hwasan_thread.cpp' l='37' ll='76' type='void __hwasan::Thread::Init(__sanitizer::uptr stack_buffer_start, __sanitizer::uptr stack_buffer_size)'/>
