<dec f='llvm/compiler-rt/lib/memprof/memprof_thread.h' l='69' type='void __memprof::MemprofThread::Init(const __memprof::MemprofThread::InitOptions * options = nullptr)'/>
<def f='llvm/compiler-rt/lib/memprof/memprof_thread.cpp' l='123' ll='135' type='void __memprof::MemprofThread::Init(const __memprof::MemprofThread::InitOptions * options = nullptr)'/>
<use f='llvm/compiler-rt/lib/memprof/memprof_thread.cpp' l='140' u='c' c='__memprof::MemprofThread::ThreadStart'/>
