<dec f='llvm/compiler-rt/lib/memprof/memprof_descriptions.h' l='38' type='void __memprof::MemprofThreadIdAndName::Init(__sanitizer::u32 tid, const char * tname)'/>
<use f='llvm/compiler-rt/lib/memprof/memprof_descriptions.cpp' l='23' u='c' c='__memprof::MemprofThreadIdAndName::MemprofThreadIdAndName'/>
<use f='llvm/compiler-rt/lib/memprof/memprof_descriptions.cpp' l='28' u='c' c='__memprof::MemprofThreadIdAndName::MemprofThreadIdAndName'/>
<use f='llvm/compiler-rt/lib/memprof/memprof_descriptions.cpp' l='32' u='c' c='__memprof::MemprofThreadIdAndName::MemprofThreadIdAndName'/>
<def f='llvm/compiler-rt/lib/memprof/memprof_descriptions.cpp' l='36' ll='41' type='void __memprof::MemprofThreadIdAndName::Init(__sanitizer::u32 tid, const char * tname)'/>
