<dec f='llvm/compiler-rt/lib/msan/msan_thread.h' l='27' type='void __msan::MsanThread::Init()'/>
<doc f='llvm/compiler-rt/lib/msan/msan_thread.h' l='27'>// Should be called from the thread itself.</doc>
<def f='llvm/compiler-rt/lib/msan/msan_thread.cpp' l='45' ll='50' type='void __msan::MsanThread::Init()'/>
<use f='llvm/compiler-rt/lib/msan/msan_thread.cpp' l='69' u='c' c='__msan::MsanThread::ThreadStart'/>
