<dec f='llvm/compiler-rt/lib/sanitizer_common/sanitizer_symbolizer.h' l='32' type='char *'/>
<offset>64</offset>
<use f='llvm/compiler-rt/lib/sanitizer_common/sanitizer_stacktrace_printer.cpp' l='138' u='r' c='__sanitizer::RenderFrame'/>
<use f='llvm/compiler-rt/lib/sanitizer_common/sanitizer_stacktrace_printer.cpp' l='181' u='r' c='__sanitizer::RenderFrame'/>
<use f='llvm/compiler-rt/lib/sanitizer_common/sanitizer_stacktrace_printer.cpp' l='182' u='r' c='__sanitizer::RenderFrame'/>
<use f='llvm/compiler-rt/lib/sanitizer_common/sanitizer_stacktrace_printer.cpp' l='192' u='r' c='__sanitizer::RenderFrame'/>
<use f='llvm/compiler-rt/lib/sanitizer_common/sanitizer_stacktrace_printer.cpp' l='194' u='r' c='__sanitizer::RenderFrame'/>
<use f='llvm/compiler-rt/lib/sanitizer_common/sanitizer_symbolizer.cpp' l='28' u='r' c='__sanitizer::AddressInfo::Clear'/>
<use f='llvm/compiler-rt/lib/sanitizer_common/sanitizer_symbolizer.cpp' l='37' u='w' c='__sanitizer::AddressInfo::FillModuleInfo'/>
<use f='llvm/compiler-rt/lib/sanitizer_common/sanitizer_symbolizer_libcdep.cpp' l='343' u='r' c='__sanitizer::ParseSymbolizePCOutput'/>
<use f='llvm/compiler-rt/lib/sanitizer_common/sanitizer_symbolizer_libcdep.cpp' l='407' u='r' c='__sanitizer::LLVMSymbolizer::SymbolizePC'/>
<use f='llvm/compiler-rt/lib/sanitizer_common/sanitizer_symbolizer_posix_libcdep.cpp' l='274' u='r' c='__sanitizer::Addr2LinePool::SymbolizePC'/>
<use f='llvm/compiler-rt/lib/tsan/rtl/tsan_report.cpp' l='300' u='r' c='__tsan::FrameIsInternal'/>
<use f='llvm/compiler-rt/lib/tsan/rtl/tsan_suppressions.cpp' l='98' u='r' c='__tsan::IsSuppressed'/>
<use f='llvm/compiler-rt/lib/ubsan/ubsan_diag.cpp' l='168' u='r' c='_ZL14RenderLocationPN11__sanitizer20InternalScopedStringEN7__ubsan8LocationE'/>
<use f='llvm/compiler-rt/lib/ubsan/ubsan_diag.cpp' l='169' u='r' c='_ZL14RenderLocationPN11__sanitizer20InternalScopedStringEN7__ubsan8LocationE'/>
<use f='llvm/compiler-rt/lib/ubsan/ubsan_handlers.cpp' l='854' u='r' c='_ZL17handleCFIBadIcallPN7__ubsan16CFICheckFailDataEmNS_13ReportOptionsE'/>
