<dec f='llvm/compiler-rt/lib/sanitizer_common/sanitizer_allocator_size_class_map.h' l='126' type='const __sanitizer::uptr'/>
<use f='llvm/compiler-rt/lib/sanitizer_common/sanitizer_allocator_size_class_map.h' l='155' u='r' c='__sanitizer::SizeClassMap::Size'/>
<use f='llvm/compiler-rt/lib/sanitizer_common/sanitizer_allocator_size_class_map.h' l='164' u='r' c='__sanitizer::SizeClassMap::ClassID'/>
