<def f='llvm/compiler-rt/lib/sanitizer_common/sanitizer_allocator_stats.h' l='28' ll='30' type='void __sanitizer::AllocatorStats::Init()'/>
<use f='llvm/compiler-rt/lib/sanitizer_common/sanitizer_allocator_local_cache.h' l='22' u='c' c='__sanitizer::SizeClassAllocator64LocalCache::Init'/>
<use f='llvm/compiler-rt/lib/sanitizer_common/sanitizer_allocator_local_cache.h' l='126' u='c' c='__sanitizer::SizeClassAllocator32LocalCache::Init'/>
