<use f='llvm/compiler-rt/lib/sanitizer_common/sanitizer_report_decorator.h' l='29' u='c' c='__sanitizer::SanitizerCommonDecorator::Warning'/>
<use f='llvm/compiler-rt/lib/sanitizer_common/sanitizer_report_decorator.h' l='30' u='c' c='__sanitizer::SanitizerCommonDecorator::Error'/>
<def f='llvm/compiler-rt/lib/sanitizer_common/sanitizer_report_decorator.h' l='35' type='const char * __sanitizer::SanitizerCommonDecorator::Red() const'/>
<use f='llvm/compiler-rt/lib/asan/asan_descriptions.h' l='54' u='c' c='__asan::Decorator::ShadowByte'/>
<use f='llvm/compiler-rt/lib/asan/asan_descriptions.h' l='60' u='c' c='__asan::Decorator::ShadowByte'/>
<use f='llvm/compiler-rt/lib/asan/asan_descriptions.h' l='73' u='c' c='__asan::Decorator::ShadowByte'/>
<use f='llvm/compiler-rt/lib/lsan/lsan_common.cpp' l='156' u='c' c='__lsan::Decorator::Error'/>
