<dec f='llvm/compiler-rt/lib/sanitizer_common/sanitizer_common.h' l='170' type='__sanitizer::uptr __sanitizer::ReservedAddressRange::Init(__sanitizer::uptr size, const char * name = nullptr, __sanitizer::uptr fixed_addr = 0)'/>
<use f='llvm/compiler-rt/lib/sanitizer_common/sanitizer_allocator_primary64.h' l='76' u='c' c='__sanitizer::SizeClassAllocator64::Init'/>
<use f='llvm/compiler-rt/lib/sanitizer_common/sanitizer_allocator_secondary.h' l='35' u='c' c='__sanitizer::LargeMmapAllocatorPtrArrayDynamic::Init'/>
<use f='llvm/compiler-rt/lib/sanitizer_common/sanitizer_common_libcdep.cpp' l='136' u='c' c='__sanitizer::ReservedAddressRange::InitAligned'/>
<use f='llvm/compiler-rt/lib/sanitizer_common/sanitizer_common_libcdep.cpp' l='137' u='c' c='__sanitizer::ReservedAddressRange::InitAligned'/>
<def f='llvm/compiler-rt/lib/sanitizer_common/sanitizer_posix_libcdep.cpp' l='339' ll='346' type='__sanitizer::uptr __sanitizer::ReservedAddressRange::Init(__sanitizer::uptr size, const char * name = nullptr, __sanitizer::uptr fixed_addr = 0)'/>
<use f='llvm/compiler-rt/lib/scudo/scudo_allocator_secondary.h' l='87' u='c' c='__scudo::LargeMmapAllocator::Allocate'/>
