<def f='llvm/compiler-rt/lib/sanitizer_common/sanitizer_mutex.h' l='24' ll='26' type='void __sanitizer::StaticSpinMutex::Init()'/>
<use f='llvm/compiler-rt/lib/sanitizer_common/sanitizer_mutex.h' l='65' u='c' c='__sanitizer::SpinMutex::SpinMutex'/>
<use f='llvm/compiler-rt/lib/sanitizer_common/sanitizer_allocator_bytemap.h' l='52' u='c' c='__sanitizer::TwoLevelByteMap::Init'/>
<use f='llvm/compiler-rt/lib/sanitizer_common/sanitizer_quarantine.h' l='93' u='c' c='__sanitizer::Quarantine::Init'/>
<use f='llvm/compiler-rt/lib/sanitizer_common/sanitizer_quarantine.h' l='94' u='c' c='__sanitizer::Quarantine::Init'/>
