<dec f='llvm/compiler-rt/lib/sanitizer_common/sanitizer_allocator_size_class_map.h' l='125' type='const __sanitizer::uptr'/>
<use f='llvm/compiler-rt/lib/sanitizer_common/sanitizer_allocator_size_class_map.h' l='126' u='r'/>
<use f='llvm/compiler-rt/lib/sanitizer_common/sanitizer_allocator_size_class_map.h' l='136' u='r'/>
<use f='llvm/compiler-rt/lib/sanitizer_common/sanitizer_allocator_size_class_map.h' l='154' u='r' c='__sanitizer::SizeClassMap::Size'/>
<use f='llvm/compiler-rt/lib/sanitizer_common/sanitizer_allocator_size_class_map.h' l='155' u='r' c='__sanitizer::SizeClassMap::Size'/>
<use f='llvm/compiler-rt/lib/sanitizer_common/sanitizer_allocator_size_class_map.h' l='164' u='r' c='__sanitizer::SizeClassMap::ClassID'/>
<use f='llvm/compiler-rt/lib/sanitizer_common/sanitizer_allocator_size_class_map.h' l='165' u='r' c='__sanitizer::SizeClassMap::ClassID'/>
<use f='llvm/compiler-rt/lib/sanitizer_common/sanitizer_allocator_size_class_map.h' l='167' u='r' c='__sanitizer::SizeClassMap::ClassID'/>
