<def f='llvm/compiler-rt/lib/sanitizer_common/sanitizer_allocator_combined.h' l='38' ll='42' type='void __sanitizer::CombinedAllocator::Init(__sanitizer::s32 release_to_os_interval_ms)'/>
<use f='llvm/compiler-rt/lib/hwasan/hwasan_allocator.cpp' l='87' u='c' c='__hwasan::HwasanAllocatorInit'/>
<use f='llvm/compiler-rt/lib/msan/msan_allocator.cpp' l='136' u='c' c='__msan::MsanAllocatorInit'/>
<use f='llvm/compiler-rt/lib/sanitizer_common/sanitizer_allocator.cpp' l='101' u='c' c='__sanitizer::internal_allocator'/>
<use f='llvm/compiler-rt/lib/tsan/rtl/tsan_mman.cpp' l='121' u='c' c='__tsan::InitializeAllocator'/>
