<dec f='llvm/compiler-rt/lib/sanitizer_common/sanitizer_symbolizer.h' l='67' type='char *'/>
<offset>0</offset>
<doc f='llvm/compiler-rt/lib/sanitizer_common/sanitizer_symbolizer.h' l='65'>// Owns all the string members. Storage for them is
  // (de)allocated using sanitizer internal allocator.</doc>
<use f='llvm/compiler-rt/lib/sanitizer_common/sanitizer_symbolizer.cpp' l='63' u='r' c='__sanitizer::DataInfo::Clear'/>
<use f='llvm/compiler-rt/lib/sanitizer_common/sanitizer_symbolizer_libcdep.cpp' l='114' u='w' c='__sanitizer::Symbolizer::SymbolizeData'/>
<use f='llvm/compiler-rt/lib/sanitizer_common/sanitizer_symbolizer_libcdep.cpp' l='416' u='r' c='__sanitizer::LLVMSymbolizer::SymbolizeData'/>
<use f='llvm/compiler-rt/lib/tsan/rtl/tsan_report.cpp' l='194' u='r' c='__tsan::PrintLocation'/>
<use f='llvm/compiler-rt/lib/tsan/rtl/tsan_report.cpp' l='197' u='r' c='__tsan::PrintLocation'/>
<use f='llvm/compiler-rt/lib/tsan/rtl/tsan_suppressions.cpp' l='136' u='r' c='__tsan::IsSuppressed'/>
