<def f='llvm/compiler-rt/lib/sanitizer_common/sanitizer_allocator_stats.h' l='38' ll='41' type='void __sanitizer::AllocatorStats::Sub(__sanitizer::AllocatorStat i, __sanitizer::uptr v)'/>
<use f='llvm/compiler-rt/lib/sanitizer_common/sanitizer_allocator_local_cache.h' l='61' u='c' c='__sanitizer::SizeClassAllocator64LocalCache::Deallocate'/>
<use f='llvm/compiler-rt/lib/sanitizer_common/sanitizer_allocator_local_cache.h' l='177' u='c' c='__sanitizer::SizeClassAllocator32LocalCache::Deallocate'/>
<use f='llvm/compiler-rt/lib/sanitizer_common/sanitizer_allocator_secondary.h' l='146' u='c' c='__sanitizer::LargeMmapAllocator::Deallocate'/>
<use f='llvm/compiler-rt/lib/sanitizer_common/sanitizer_allocator_secondary.h' l='147' u='c' c='__sanitizer::LargeMmapAllocator::Deallocate'/>
<use f='llvm/compiler-rt/lib/scudo/scudo_allocator_secondary.h' l='159' u='c' c='__scudo::LargeMmapAllocator::Deallocate'/>
<use f='llvm/compiler-rt/lib/scudo/scudo_allocator_secondary.h' l='160' u='c' c='__scudo::LargeMmapAllocator::Deallocate'/>
