<def f='llvm/compiler-rt/lib/sanitizer_common/sanitizer_ring_buffer.h' l='93' ll='102' type='void __sanitizer::CompactRingBuffer::Init(void * storage, __sanitizer::uptr size)'/>
<use f='llvm/compiler-rt/lib/sanitizer_common/sanitizer_ring_buffer.h' l='110' u='c' c='__sanitizer::CompactRingBuffer::CompactRingBuffer{T}'/>
<use f='llvm/compiler-rt/lib/sanitizer_common/sanitizer_ring_buffer.h' l='117' u='c' c='__sanitizer::CompactRingBuffer::CompactRingBuffer{T}'/>
