<dec f='llvm/compiler-rt/lib/sanitizer_common/sanitizer_common.h' l='822' type='void __sanitizer::ListOfModules::init()'/>
<use f='llvm/compiler-rt/lib/lsan/lsan_common_linux.cpp' l='55' u='c' c='__lsan::InitializePlatformSpecificModules'/>
<def f='llvm/compiler-rt/lib/sanitizer_common/sanitizer_common_nolibc.cpp' l='32' type='void __sanitizer::ListOfModules::init()'/>
<use f='llvm/compiler-rt/lib/sanitizer_common/sanitizer_libignore.cpp' l='54' u='c' c='__sanitizer::LibIgnore::OnLibraryLoaded'/>
<def f='llvm/compiler-rt/lib/sanitizer_common/sanitizer_linux_libcdep.cpp' l='627' ll='635' type='void __sanitizer::ListOfModules::init()'/>
<use f='llvm/compiler-rt/lib/sanitizer_common/sanitizer_symbolizer_libcdep.cpp' l='188' u='c' c='__sanitizer::Symbolizer::RefreshModules'/>
