<dec f='llvm/compiler-rt/lib/sanitizer_common/sanitizer_symbolizer.h' l='99' type='char *'/>
<offset>0</offset>
<use f='llvm/compiler-rt/lib/sanitizer_common/sanitizer_symbolizer.cpp' l='70' u='r' c='__sanitizer::FrameInfo::Clear'/>
<use f='llvm/compiler-rt/lib/sanitizer_common/sanitizer_symbolizer_libcdep.cpp' l='132' u='w' c='__sanitizer::Symbolizer::SymbolizeFrame'/>
<use f='llvm/compiler-rt/lib/sanitizer_common/sanitizer_symbolizer_libcdep.cpp' l='426' u='r' c='__sanitizer::LLVMSymbolizer::SymbolizeFrame'/>
