<dec f='llvm/compiler-rt/lib/scudo/scudo_tsd.h' l='29' type='void __scudo::ScudoTSD::init()'/>
<def f='llvm/compiler-rt/lib/scudo/scudo_allocator.cpp' l='689' ll='692' type='void __scudo::ScudoTSD::init()'/>
<use f='llvm/compiler-rt/lib/scudo/scudo_tsd_exclusive.cpp' l='52' u='c' c='__scudo::initOnce'/>
<use f='llvm/compiler-rt/lib/scudo/scudo_tsd_exclusive.cpp' l='61' u='c' c='__scudo::initThread'/>
