<dec f='llvm/compiler-rt/lib/tsan/rtl/tsan_stack_trace.h' l='27' type='void __tsan::VarSizeStackTrace::Init(const __sanitizer::uptr * pcs, __sanitizer::uptr cnt, __sanitizer::uptr extra_top_pc = 0)'/>
<use f='llvm/compiler-rt/lib/tsan/rtl/tsan_rtl_report.cpp' l='438' u='c' c='__tsan::RestoreStack'/>
<def f='llvm/compiler-rt/lib/tsan/rtl/tsan_stack_trace.cpp' l='38' ll='43' type='void __tsan::VarSizeStackTrace::Init(const __sanitizer::uptr * pcs, __sanitizer::uptr cnt, __sanitizer::uptr extra_top_pc = 0)'/>
