<dec f='llvm/compiler-rt/lib/tsan/rtl/tsan_sync.h' l='70' type='void __tsan::SyncVar::Init(__tsan::ThreadState * thr, __sanitizer::uptr pc, __sanitizer::uptr addr, __sanitizer::u64 uid)'/>
<def f='llvm/compiler-rt/lib/tsan/rtl/tsan_sync.cpp' l='26' ll='36' type='void __tsan::SyncVar::Init(__tsan::ThreadState * thr, __sanitizer::uptr pc, __sanitizer::uptr addr, __sanitizer::u64 uid)'/>
<use f='llvm/compiler-rt/lib/tsan/rtl/tsan_sync.cpp' l='244' u='c' c='__tsan::MetaMap::GetAndLock'/>
