<dec f='llvm/compiler-rt/lib/xray/xray_segmented_array.h' l='82' type='__xray::Array::Segment *'/>
<use f='llvm/compiler-rt/lib/xray/xray_segmented_array.h' l='88' u='w' c='__xray::Array::Iterator::Iterator{U}'/>
<use f='llvm/compiler-rt/lib/xray/xray_segmented_array.h' l='108' u='w' c='__xray::Array::Iterator::operator++'/>
<use f='llvm/compiler-rt/lib/xray/xray_segmented_array.h' l='108' u='r' c='__xray::Array::Iterator::operator++'/>
<use f='llvm/compiler-rt/lib/xray/xray_segmented_array.h' l='120' u='w' c='__xray::Array::Iterator::operator--'/>
<use f='llvm/compiler-rt/lib/xray/xray_segmented_array.h' l='120' u='r' c='__xray::Array::Iterator::operator--'/>
<use f='llvm/compiler-rt/lib/xray/xray_segmented_array.h' l='156' u='a' c='__xray::Array::Iterator::operator*'/>
