<dec f='llvm/llvm/examples/BrainF/BrainF.h' l='80' type='llvm::Module *'/>
<use f='llvm/llvm/examples/BrainF/BrainF.cpp' l='61' u='r' c='_ZN6BrainF5parseEPSiiNS_12CompileFlagsERN4llvm11LLVMContextE'/>
<use f='llvm/llvm/examples/BrainF/BrainF.cpp' l='65' u='w' c='_ZN6BrainF6headerERN4llvm11LLVMContextE'/>
<use f='llvm/llvm/examples/BrainF/BrainF.cpp' l='71' u='r' c='_ZN6BrainF6headerERN4llvm11LLVMContextE'/>
<use f='llvm/llvm/examples/BrainF/BrainF.cpp' l='76' u='r' c='_ZN6BrainF6headerERN4llvm11LLVMContextE'/>
<use f='llvm/llvm/examples/BrainF/BrainF.cpp' l='79' u='r' c='_ZN6BrainF6headerERN4llvm11LLVMContextE'/>
<use f='llvm/llvm/examples/BrainF/BrainF.cpp' l='86' u='r' c='_ZN6BrainF6headerERN4llvm11LLVMContextE'/>
<use f='llvm/llvm/examples/BrainF/BrainF.cpp' l='146' u='r' c='_ZN6BrainF6headerERN4llvm11LLVMContextE'/>
<use f='llvm/llvm/examples/BrainF/BrainF.cpp' l='154' u='r' c='_ZN6BrainF6headerERN4llvm11LLVMContextE'/>
<offset>128</offset>
