<dec f='llvm/clang/lib/AST/FormatStringParsing.h' l='73' type='T'/>
<use f='llvm/clang/lib/AST/FormatStringParsing.h' l='81' u='w' c='_ZN5clang21analyze_format_string15SpecifierResultC1EPKcRKT_'/>
<use f='llvm/clang/lib/AST/FormatStringParsing.h' l='88' u='a' c='_ZNK5clang21analyze_format_string15SpecifierResult8getValueEv'/>
<use f='llvm/clang/lib/AST/FormatStringParsing.h' l='90' u='a' c='_ZN5clang21analyze_format_string15SpecifierResult8getValueEv'/>
