<dec f='llvm/clang/include/clang/Analysis/PathDiagnostic.h' l='201' type='const clang::Decl *'/>
<use f='llvm/clang/include/clang/Analysis/PathDiagnostic.h' l='233' u='w' c='_ZN5clang4ento22PathDiagnosticLocationC1EPKNS_4DeclERKNS_13SourceManagerE'/>
<use f='llvm/clang/include/clang/Analysis/PathDiagnostic.h' l='355' u='r' c='_ZNK5clang4ento22PathDiagnosticLocation6asDeclEv'/>
<offset>128</offset>
<use f='llvm/clang/lib/Analysis/PathDiagnostic.cpp' l='760' u='r' c='_ZNK5clang4ento22PathDiagnosticLocation11genLocationENS_14SourceLocationEN4llvm12PointerUnionIJPKNS_15LocationContextEPNS_19AnalysisDeclContextEEEE'/>
<use f='llvm/clang/lib/Analysis/PathDiagnostic.cpp' l='762' u='r' c='_ZNK5clang4ento22PathDiagnosticLocation11genLocationENS_14SourceLocationEN4llvm12PointerUnionIJPKNS_15LocationContextEPNS_19AnalysisDeclContextEEEE'/>
<use f='llvm/clang/lib/Analysis/PathDiagnostic.cpp' l='814' u='r' c='_ZNK5clang4ento22PathDiagnosticLocation8genRangeEN4llvm12PointerUnionIJPKNS_15LocationContextEPNS_19AnalysisDeclContextEEEE'/>
<use f='llvm/clang/lib/Analysis/PathDiagnostic.cpp' l='816' u='r' c='_ZNK5clang4ento22PathDiagnosticLocation8genRangeEN4llvm12PointerUnionIJPKNS_15LocationContextEPNS_19AnalysisDeclContextEEEE'/>
<use f='llvm/clang/lib/Analysis/PathDiagnostic.cpp' l='821' u='r' c='_ZNK5clang4ento22PathDiagnosticLocation8genRangeEN4llvm12PointerUnionIJPKNS_15LocationContextEPNS_19AnalysisDeclContextEEEE'/>
<use f='llvm/clang/lib/Analysis/PathDiagnostic.cpp' l='833' u='w' c='_ZN5clang4ento22PathDiagnosticLocation7flattenEv'/>
<use f='llvm/clang/lib/Analysis/PathDiagnostic.cpp' l='838' u='w' c='_ZN5clang4ento22PathDiagnosticLocation7flattenEv'/>
<use f='llvm/clang/lib/Analysis/PathDiagnostic.cpp' l='1225' u='r' c='_ZNK5clang4ento22PathDiagnosticLocation4dumpEv'/>
<use f='llvm/clang/lib/Analysis/PathDiagnostic.cpp' l='1227' u='r' c='_ZNK5clang4ento22PathDiagnosticLocation4dumpEv'/>
<use f='llvm/clang/lib/Analysis/PathDiagnostic.cpp' l='1230' u='r' c='_ZNK5clang4ento22PathDiagnosticLocation4dumpEv'/>
