<dec f='llvm/clang/include/clang/StaticAnalyzer/Core/PathSensitive/SymbolManager.h' l='211' type='const clang::Stmt *'/>
<use f='llvm/clang/include/clang/StaticAnalyzer/Core/PathSensitive/SymbolManager.h' l='220' u='w' c='_ZN5clang4ento14SymbolMetadataC1EjPKNS0_9MemRegionEPKNS_4StmtENS_8QualTypeEPKNS_15LocationContextEjPKv'/>
<use f='llvm/clang/include/clang/StaticAnalyzer/Core/PathSensitive/SymbolManager.h' l='230' u='r' c='_ZNK5clang4ento14SymbolMetadata7getStmtEv'/>
<use f='llvm/clang/include/clang/StaticAnalyzer/Core/PathSensitive/SymbolManager.h' l='254' u='r' c='_ZN5clang4ento14SymbolMetadata7ProfileERN4llvm16FoldingSetNodeIDE'/>
<offset>320</offset>
