<dec f='llvm/clang/include/clang/StaticAnalyzer/Core/PathSensitive/SymbolManager.h' l='212' type='clang::QualType'/>
<use f='llvm/clang/include/clang/StaticAnalyzer/Core/PathSensitive/SymbolManager.h' l='220' u='w' c='_ZN5clang4ento14SymbolMetadataC1EjPKNS0_9MemRegionEPKNS_4StmtENS_8QualTypeEPKNS_15LocationContextEjPKv'/>
<use f='llvm/clang/include/clang/StaticAnalyzer/Core/PathSensitive/SymbolManager.h' l='254' u='r' c='_ZN5clang4ento14SymbolMetadata7ProfileERN4llvm16FoldingSetNodeIDE'/>
<offset>384</offset>
<use f='llvm/clang/lib/StaticAnalyzer/Core/SymbolManager.cpp' l='94' u='m' c='_ZNK5clang4ento14SymbolMetadata12dumpToStreamERN4llvm11raw_ostreamE'/>
<use f='llvm/clang/lib/StaticAnalyzer/Core/SymbolManager.cpp' l='326' u='r' c='_ZNK5clang4ento14SymbolMetadata7getTypeEv'/>
