<dec f='llvm/clang/include/clang/Serialization/ASTReader.h' l='554' type='ArrayRef&lt;serialization::LocalDeclID&gt;'/>
<use f='llvm/clang/include/clang/Serialization/ASTReader.h' l='558' u='w' c='_ZN5clang9ASTReader13FileDeclsInfoC1EPNS_13serialization10ModuleFileEN4llvm8ArrayRefIjEE'/>
<offset>64</offset>
<use f='llvm/clang/lib/Serialization/ASTReader.cpp' l='7584' u='m' c='_ZN5clang9ASTReader19FindFileRegionDeclsENS_6FileIDEjjRN4llvm15SmallVectorImplIPNS_4DeclEEE'/>
<use f='llvm/clang/lib/Serialization/ASTReader.cpp' l='7593' u='a' c='_ZN5clang9ASTReader19FindFileRegionDeclsENS_6FileIDEjjRN4llvm15SmallVectorImplIPNS_4DeclEEE'/>
<use f='llvm/clang/lib/Serialization/ASTReader.cpp' l='7594' u='m' c='_ZN5clang9ASTReader19FindFileRegionDeclsENS_6FileIDEjjRN4llvm15SmallVectorImplIPNS_4DeclEEE'/>
<use f='llvm/clang/lib/Serialization/ASTReader.cpp' l='7600' u='m' c='_ZN5clang9ASTReader19FindFileRegionDeclsENS_6FileIDEjjRN4llvm15SmallVectorImplIPNS_4DeclEEE'/>
<use f='llvm/clang/lib/Serialization/ASTReader.cpp' l='7606' u='a' c='_ZN5clang9ASTReader19FindFileRegionDeclsENS_6FileIDEjjRN4llvm15SmallVectorImplIPNS_4DeclEEE'/>
<use f='llvm/clang/lib/Serialization/ASTReader.cpp' l='7607' u='m' c='_ZN5clang9ASTReader19FindFileRegionDeclsENS_6FileIDEjjRN4llvm15SmallVectorImplIPNS_4DeclEEE'/>
