<dec f='llvm/clang/include/clang/StaticAnalyzer/Core/PathSensitive/BasicValueFactory.h' l='82' type='const clang::NamedDecl *'/>
<use f='llvm/clang/include/clang/StaticAnalyzer/Core/PathSensitive/BasicValueFactory.h' l='88' u='w' c='_ZN5clang4ento19PointerToMemberDataC1EPKNS_9NamedDeclEN4llvm13ImmutableListIPKNS_16CXXBaseSpecifierEEE'/>
<use f='llvm/clang/include/clang/StaticAnalyzer/Core/PathSensitive/BasicValueFactory.h' l='98' u='r' c='_ZN5clang4ento19PointerToMemberData7ProfileERN4llvm16FoldingSetNodeIDE'/>
<use f='llvm/clang/include/clang/StaticAnalyzer/Core/PathSensitive/BasicValueFactory.h' l='99' u='r' c='_ZNK5clang4ento19PointerToMemberData17getDeclaratorDeclEv'/>
<offset>64</offset>
