<dec f='llvm/clang/include/clang/AST/APValue.h' l='45' type='const clang::Type *'/>
<use f='llvm/clang/include/clang/AST/APValue.h' l='48' u='w' c='_ZN5clang14TypeInfoLValueC1Ev'/>
<use f='llvm/clang/include/clang/AST/APValue.h' l='51' u='r' c='_ZNK5clang14TypeInfoLValue7getTypeEv'/>
<use f='llvm/clang/include/clang/AST/APValue.h' l='52' u='r' c='_ZNK5clang14TypeInfoLValuecvbEv'/>
<use f='llvm/clang/include/clang/AST/APValue.h' l='54' u='r' c='_ZN5clang14TypeInfoLValue14getOpaqueValueEv'/>
<use f='llvm/clang/include/clang/AST/APValue.h' l='57' u='w' c='_ZN5clang14TypeInfoLValue18getFromOpaqueValueEPv'/>
<offset>0</offset>
<use f='llvm/clang/lib/AST/APValue.cpp' l='28' u='w' c='_ZN5clang14TypeInfoLValueC1EPKNS_4TypeE'/>
