<dec f='llvm/clang/lib/Index/FileIndexRecord.h' l='30' type='std::vector&lt;DeclOccurrence&gt;'/>
<use f='llvm/clang/lib/Index/FileIndexRecord.h' l='36' u='r' c='_ZNK5clang5index15FileIndexRecord32getDeclOccurrencesSortedByOffsetEv'/>
<use f='llvm/clang/lib/Index/FileIndexRecord.cpp' l='27' u='m' c='_ZN5clang5index15FileIndexRecord16addDeclOccurenceEjjPKNS_4DeclEN4llvm8ArrayRefINS0_14SymbolRelationEEE'/>
<use f='llvm/clang/lib/Index/FileIndexRecord.cpp' l='29' u='m' c='_ZN5clang5index15FileIndexRecord16addDeclOccurenceEjjPKNS_4DeclEN4llvm8ArrayRefINS0_14SymbolRelationEEE'/>
<use f='llvm/clang/lib/Index/FileIndexRecord.cpp' l='34' u='m' c='_ZN5clang5index15FileIndexRecord16addDeclOccurenceEjjPKNS_4DeclEN4llvm8ArrayRefINS0_14SymbolRelationEEE'/>
<use f='llvm/clang/lib/Index/FileIndexRecord.cpp' l='40' u='a' c='_ZN5clang5index15FileIndexRecord16addDeclOccurenceEjjPKNS_4DeclEN4llvm8ArrayRefINS0_14SymbolRelationEEE'/>
<use f='llvm/clang/lib/Index/FileIndexRecord.cpp' l='41' u='m' c='_ZN5clang5index15FileIndexRecord16addDeclOccurenceEjjPKNS_4DeclEN4llvm8ArrayRefINS0_14SymbolRelationEEE'/>
<use f='llvm/clang/lib/Index/FileIndexRecord.cpp' l='46' c='_ZNK5clang5index15FileIndexRecord5printERN4llvm11raw_ostreamE'/>
<offset>64</offset>
