<dec f='llvm/clang/include/clang/Analysis/PathDiagnostic.h' l='198' type='enum Kind'/>
<use f='llvm/clang/include/clang/Analysis/PathDiagnostic.h' l='207' u='w' c='_ZN5clang4ento22PathDiagnosticLocationC1ENS_14SourceLocationERKNS_13SourceManagerENS1_4KindE'/>
<use f='llvm/clang/include/clang/Analysis/PathDiagnostic.h' l='223' u='w' c='_ZN5clang4ento22PathDiagnosticLocationC1EPKNS_4StmtERKNS_13SourceManagerEN4llvm12PointerUnionIJPKNS_15LocationContextEPNS_19AnalysisDeclContextEEEE'/>
<use f='llvm/clang/include/clang/Analysis/PathDiagnostic.h' l='224' u='r' c='_ZN5clang4ento22PathDiagnosticLocationC1EPKNS_4StmtERKNS_13SourceManagerEN4llvm12PointerUnionIJPKNS_15LocationContextEPNS_19AnalysisDeclContextEEEE'/>
<use f='llvm/clang/include/clang/Analysis/PathDiagnostic.h' l='233' u='w' c='_ZN5clang4ento22PathDiagnosticLocationC1EPKNS_4DeclERKNS_13SourceManagerE'/>
<use f='llvm/clang/include/clang/Analysis/PathDiagnostic.h' l='329' u='r' c='_ZNK5clang4ento22PathDiagnosticLocationeqERKS1_'/>
<use f='llvm/clang/include/clang/Analysis/PathDiagnostic.h' l='329' u='r' c='_ZNK5clang4ento22PathDiagnosticLocationeqERKS1_'/>
<use f='llvm/clang/include/clang/Analysis/PathDiagnostic.h' l='357' u='r' c='_ZNK5clang4ento22PathDiagnosticLocation8hasRangeEv'/>
<use f='llvm/clang/include/clang/Analysis/PathDiagnostic.h' l='357' u='r' c='_ZNK5clang4ento22PathDiagnosticLocation8hasRangeEv'/>
<use f='llvm/clang/include/clang/Analysis/PathDiagnostic.h' l='357' u='r' c='_ZNK5clang4ento22PathDiagnosticLocation8hasRangeEv'/>
<offset>0</offset>
<use f='llvm/clang/lib/Analysis/PathDiagnostic.cpp' l='748' u='r' c='_ZNK5clang4ento22PathDiagnosticLocation11genLocationENS_14SourceLocationEN4llvm12PointerUnionIJPKNS_15LocationContextEPNS_19AnalysisDeclContextEEEE'/>
<use f='llvm/clang/lib/Analysis/PathDiagnostic.cpp' l='773' u='r' c='_ZNK5clang4ento22PathDiagnosticLocation8genRangeEN4llvm12PointerUnionIJPKNS_15LocationContextEPNS_19AnalysisDeclContextEEEE'/>
<use f='llvm/clang/lib/Analysis/PathDiagnostic.cpp' l='830' u='r' c='_ZN5clang4ento22PathDiagnosticLocation7flattenEv'/>
<use f='llvm/clang/lib/Analysis/PathDiagnostic.cpp' l='831' u='w' c='_ZN5clang4ento22PathDiagnosticLocation7flattenEv'/>
<use f='llvm/clang/lib/Analysis/PathDiagnostic.cpp' l='835' u='r' c='_ZN5clang4ento22PathDiagnosticLocation7flattenEv'/>
<use f='llvm/clang/lib/Analysis/PathDiagnostic.cpp' l='836' u='w' c='_ZN5clang4ento22PathDiagnosticLocation7flattenEv'/>
<use f='llvm/clang/lib/Analysis/PathDiagnostic.cpp' l='1209' u='r' c='_ZNK5clang4ento22PathDiagnosticLocation4dumpEv'/>
