<dec f='llvm/clang/include/clang/CodeGen/CodeGenAction.h' l='31' type='std::unique_ptr&lt;llvm::Module&gt;'/>
<offset>0</offset>
<doc f='llvm/clang/include/clang/CodeGen/CodeGenAction.h' l='30'>/// The module to link in.</doc>
<use f='llvm/clang/lib/CodeGen/CodeGenAction.cpp' l='252' u='m' c='_ZN5clang15BackendConsumer13LinkInModulesEv'/>
<use f='llvm/clang/lib/CodeGen/CodeGenAction.cpp' l='260' u='m' c='_ZN5clang15BackendConsumer13LinkInModulesEv'/>
<use f='llvm/clang/lib/CodeGen/CodeGenAction.cpp' l='265' u='a' c='_ZN5clang15BackendConsumer13LinkInModulesEv'/>
<use f='llvm/clang/lib/CodeGen/CodeGenAction.cpp' l='272' u='a' c='_ZN5clang15BackendConsumer13LinkInModulesEv'/>
