<dec f='llvm/clang/include/clang/Basic/LangStandard.h' l='31' type='4'/>
<use f='llvm/clang/lib/Frontend/ASTUnit.cpp' l='2676' u='r' c='_ZNK5clang7ASTUnit12getInputKindEv'/>
<use f='llvm/clang/lib/Frontend/CompilerInstance.cpp' l='1016' u='r' c='_ZL22getLanguageFromOptionsRKN5clang11LangOptionsE'/>
<use f='llvm/clang/lib/Frontend/CompilerInvocation.cpp' l='1749' u='r' c='_ZL17ParseFrontendArgsRN5clang15FrontendOptionsERN4llvm3opt7ArgListERNS_17DiagnosticsEngineERb'/>
<use f='llvm/clang/lib/Frontend/CompilerInvocation.cpp' l='1988' c='_ZN5clang18CompilerInvocation15setLangDefaultsERNS_11LangOptionsENS_9InputKindERKN4llvm6TripleERSt6vectorINSt7__cxx1112basic_stringIcSt11char_traitsIc12293528'/>
<use f='llvm/clang/lib/Frontend/CompilerInvocation.cpp' l='2110' c='_ZL29IsInputCompatibleWithStandardN5clang9InputKindERKNS_12LangStandardE'/>
<use f='llvm/clang/lib/Frontend/CompilerInvocation.cpp' l='2112' u='r' c='_ZL29IsInputCompatibleWithStandardN5clang9InputKindERKNS_12LangStandardE'/>
<use f='llvm/clang/lib/Frontend/CompilerInvocation.cpp' l='2117' u='r' c='_ZL29IsInputCompatibleWithStandardN5clang9InputKindERKNS_12LangStandardE'/>
<use f='llvm/clang/lib/Frontend/CompilerInvocation.cpp' l='2120' u='r' c='_ZL29IsInputCompatibleWithStandardN5clang9InputKindERKNS_12LangStandardE'/>
<use f='llvm/clang/lib/Frontend/CompilerInvocation.cpp' l='2139' c='_ZL16GetInputKindNameN5clang9InputKindE'/>
<use f='llvm/clang/lib/Frontend/FrontendActions.cpp' l='861' c='_ZN5clang19PrintPreambleAction13ExecuteActionEv'/>
<use f='llvm/clang/lib/Frontend/FrontendOptions.cpp' l='21' u='r' c='_ZN5clang15FrontendOptions24getInputKindForExtensionEN4llvm9StringRefE'/>
<use f='llvm/clang/lib/Frontend/FrontendOptions.cpp' l='27' u='r' c='_ZN5clang15FrontendOptions24getInputKindForExtensionEN4llvm9StringRefE'/>
<use f='llvm/clang/lib/Frontend/FrontendOptions.cpp' l='28' u='r' c='_ZN5clang15FrontendOptions24getInputKindForExtensionEN4llvm9StringRefE'/>
<use f='llvm/clang/lib/Frontend/FrontendOptions.cpp' l='29' u='r' c='_ZN5clang15FrontendOptions24getInputKindForExtensionEN4llvm9StringRefE'/>
<use f='llvm/clang/lib/Frontend/FrontendOptions.cpp' l='30' u='r' c='_ZN5clang15FrontendOptions24getInputKindForExtensionEN4llvm9StringRefE'/>
<use f='llvm/clang/lib/StaticAnalyzer/Frontend/ModelInjector.cpp' l='70' u='r' c='_ZN5clang4ento13ModelInjector15onBodySynthesisEPKNS_9NamedDeclE'/>
<use f='llvm/clang/lib/Tooling/InterpolatingCompilationDatabase.cpp' l='260' c='_ZN5clang7tooling12_GLOBAL__N_119TransferableCommand6toTypeENS_8LanguageE'/>
<use f='llvm/clang/unittests/Frontend/CodeGenActionTest.cpp' l='49' u='r' c='_ZN12_GLOBAL__N_132CodeGenTest_TestNullCodeGen_Test8TestBodyEv'/>
<use f='llvm/clang/unittests/Frontend/FrontendActionTest.cpp' l='88' u='r' c='_ZN12_GLOBAL__N_129ASTFrontendAction_Sanity_Test8TestBodyEv'/>
<use f='llvm/clang/unittests/Frontend/FrontendActionTest.cpp' l='108' u='r' c='_ZN12_GLOBAL__N_141ASTFrontendAction_IncrementalParsing_Test8TestBodyEv'/>
<use f='llvm/clang/unittests/Frontend/FrontendActionTest.cpp' l='135' u='r' c='_ZN12_GLOBAL__N_153ASTFrontendAction_LateTemplateIncrementalParsing_Test8TestBodyEv'/>
<use f='llvm/clang/unittests/Frontend/FrontendActionTest.cpp' l='181' u='r' c='_ZN12_GLOBAL__N_145PreprocessorFrontendAction_EndSourceFile_Test8TestBodyEv'/>
<use f='llvm/clang/unittests/Frontend/FrontendActionTest.cpp' l='242' u='r' c='_ZN12_GLOBAL__N_141ASTFrontendAction_ExternalSemaSource_Test8TestBodyEv'/>
<use f='llvm/clang/unittests/Frontend/OutputStreamTest.cpp' l='29' u='r' c='_ZN12_GLOBAL__N_141FrontendOutputTests_TestOutputStream_Test8TestBodyEv'/>
<use f='llvm/clang/unittests/Frontend/OutputStreamTest.cpp' l='53' u='r' c='_ZN12_GLOBAL__N_154FrontendOutputTests_TestVerboseOutputStreamShared_Test8TestBodyEv'/>
<use f='llvm/clang/unittests/Frontend/OutputStreamTest.cpp' l='82' u='r' c='_ZN12_GLOBAL__N_153FrontendOutputTests_TestVerboseOutputStreamOwned_Test8TestBodyEv'/>
<use f='llvm/lldb/source/Plugins/TypeSystem/Clang/TypeSystemClang.cpp' l='490' c='_ZL13ParseLangArgsRN5clang11LangOptionsENS_9InputKindEPKc'/>
