<dec f='llvm/clang/include/clang/Lex/Preprocessor.h' l='722' type='clang::Module *'/>
<use f='llvm/clang/include/clang/Lex/Preprocessor.h' l='739' u='w' c='_ZN5clang12Preprocessor21BuildingSubmoduleInfoC1EPNS_6ModuleENS_14SourceLocationEbPNS0_14SubmoduleStateEj'/>
<offset>0</offset>
<doc f='llvm/clang/include/clang/Lex/Preprocessor.h' l='721'>/// The module that we are building.</doc>
<use f='llvm/clang/lib/Lex/PPLexerChange.cpp' l='732' u='r' c='_ZN5clang12Preprocessor14LeaveSubmoduleEb'/>
<use f='llvm/clang/lib/Lex/Preprocessor.cpp' l='1317' u='r' c='_ZN5clang12Preprocessor17makeModuleVisibleEPNS_6ModuleENS_14SourceLocationE'/>
<use f='llvm/clang/lib/Lex/Preprocessor.cpp' l='1318' u='r' c='_ZN5clang12Preprocessor17makeModuleVisibleEPNS_6ModuleENS_14SourceLocationE'/>
