<dec f='llvm/clang/include/clang/AST/Expr.h' l='2575' type='0'/>
<use f='llvm/clang/include/clang/AST/Expr.h' l='2584' u='w' c='_ZN5clang18ArraySubscriptExprC1EPNS_4ExprES2_NS_8QualTypeENS_13ExprValueKindENS_14ExprObjectKindENS_14SourceLocationE'/>
<use f='llvm/clang/include/clang/AST/Expr.h' l='2603' u='r' c='_ZN5clang18ArraySubscriptExpr6getLHSEv'/>
<use f='llvm/clang/include/clang/AST/Expr.h' l='2604' u='r' c='_ZNK5clang18ArraySubscriptExpr6getLHSEv'/>
<use f='llvm/clang/include/clang/AST/Expr.h' l='2605' u='w' c='_ZN5clang18ArraySubscriptExpr6setLHSEPNS_4ExprE'/>
