<dec f='llvm/clang/include/clang/Sema/Sema.h' l='10067' type='2'/>
<use f='llvm/clang/lib/Sema/SemaDeclAttr.cpp' l='5302' c='_ZN5clang4Sema16AddXConsumedAttrEPNS_4DeclERKNS_19AttributeCommonInfoENS0_19RetainOwnershipKindEb'/>
<use f='llvm/clang/lib/Sema/SemaDeclAttr.cpp' l='5343' u='r' c='_ZL31parsedAttrToRetainOwnershipKindRKN5clang10ParsedAttrE'/>
<use f='llvm/clang/lib/Sema/SemaTemplateInstantiateDecl.cpp' l='605' u='r' c='_ZL25attrToRetainOwnershipKindPKN5clang4AttrE'/>
