<dec f='llvm/clang/lib/ARCMigrate/Transforms.h' l='90' type='clang::Decl *'/>
<offset>128</offset>
<use f='llvm/clang/lib/ARCMigrate/TransGCAttrs.cpp' l='115' u='w' c='_ZN12_GLOBAL__N_116GCAttrsCollector10handleAttrEN5clang17AttributedTypeLocEPNS1_4DeclE'/>
<use f='llvm/clang/lib/ARCMigrate/TransGCAttrs.cpp' l='184' u='r' c='_ZL24errorForGCAttrsOnNonObjCRN5clang5arcmt5trans16MigrationContextE'/>
<use f='llvm/clang/lib/ARCMigrate/TransGCAttrs.cpp' l='340' u='r' c='_ZN5clang5arcmt5trans16MigrationContext11dumpGCAttrsEv'/>
<use f='llvm/clang/lib/ARCMigrate/TransGCAttrs.cpp' l='342' u='r' c='_ZN5clang5arcmt5trans16MigrationContext11dumpGCAttrsEv'/>
