<dec f='llvm/clang/include/clang/Analysis/ConstructionContext.h' l='441' type='const clang::CXXNewExpr *'/>
<use f='llvm/clang/include/clang/Analysis/ConstructionContext.h' l='447' u='w' c='_ZN5clang37NewAllocatedObjectConstructionContextC1EPKNS_10CXXNewExprE'/>
<use f='llvm/clang/include/clang/Analysis/ConstructionContext.h' l='452' u='r' c='_ZNK5clang37NewAllocatedObjectConstructionContext13getCXXNewExprEv'/>
<offset>64</offset>
