<dec f='llvm/clang/include/clang/AST/Type.h' l='2874' type='2'/>
<use f='llvm/clang/lib/AST/ASTContext.cpp' l='3559' u='r' c='_ZNK5clang10ASTContext27getVariableArrayDecayedTypeENS_8QualTypeE'/>
<use f='llvm/clang/lib/AST/JSONNodeDumper.cpp' l='571' c='_ZN5clang14JSONNodeDumper14VisitArrayTypeEPKNS_9ArrayTypeE'/>
<use f='llvm/clang/lib/AST/TextNodeDumper.cpp' l='1373' c='_ZN5clang14TextNodeDumper14VisitArrayTypeEPKNS_9ArrayTypeE'/>
<use f='llvm/clang/lib/AST/TypePrinter.cpp' l='551' u='r' c='_ZN12_GLOBAL__N_111TypePrinter23printVariableArrayAfterEPKN5clang17VariableArrayTypeERN4llvm11raw_ostreamE'/>
<use f='llvm/clang/lib/Index/USRGeneration.cpp' l='881' c='_ZN12_GLOBAL__N_112USRGenerator9VisitTypeEN5clang8QualTypeE'/>
<use f='llvm/clang/lib/Sema/SemaChecking.cpp' l='13845' u='r' c='_ZL28diagnoseArrayStarInParamTypeRN5clang4SemaENS_8QualTypeENS_14SourceLocationE'/>
<use f='llvm/clang/lib/Sema/SemaType.cpp' l='2430' u='r' c='_ZN5clang4Sema14BuildArrayTypeENS_8QualTypeENS_9ArrayType17ArraySizeModifierEPNS_4ExprEjNS_11SourceRangeENS_15DeclarationNameE'/>
<use f='llvm/clang/lib/Sema/SemaType.cpp' l='4836' u='r' c='_ZL24GetFullTypeForDeclaratorRN12_GLOBAL__N_119TypeProcessingStateEN5clang8QualTypeEPNS2_14TypeSourceInfoE'/>
<use f='llvm/clang/lib/Sema/SemaType.cpp' l='4841' u='r' c='_ZL24GetFullTypeForDeclaratorRN12_GLOBAL__N_119TypeProcessingStateEN5clang8QualTypeEPNS2_14TypeSourceInfoE'/>
