<dec f='llvm/clang/include/clang/Analysis/PathDiagnostic.h' l='422' type='llvm::StringRef'/>
<use f='llvm/clang/include/clang/Analysis/PathDiagnostic.h' l='440' u='w' c='_ZN5clang4ento19PathDiagnosticPiece6setTagEPKc'/>
<use f='llvm/clang/include/clang/Analysis/PathDiagnostic.h' l='443' u='m' c='_ZNK5clang4ento19PathDiagnosticPiece6getTagEv'/>
<use f='llvm/clang/include/clang/Analysis/PathDiagnostic.h' l='447' u='r' c='_ZNK5clang4ento19PathDiagnosticPiece9getTagStrEv'/>
<offset>512</offset>
<doc f='llvm/clang/include/clang/Analysis/PathDiagnostic.h' l='418'>/// A constant string that can be used to tag the PathDiagnosticPiece,
  /// typically with the identification of the creator.  The actual pointer
  /// value is meant to be an identifier; the string itself is useful for
  /// debugging.</doc>
