<dec f='llvm/clang/lib/AST/Interp/Integral.h' l='62' type='clang::interp::Integral::T'/>
<use f='llvm/clang/lib/AST/Interp/Integral.h' l='69' u='w' c='_ZN5clang6interp8IntegralC1ETL0__'/>
<use f='llvm/clang/lib/AST/Interp/Integral.h' l='73' u='w' c='_ZN5clang6interp8IntegralC1Ev'/>
<use f='llvm/clang/lib/AST/Interp/Integral.h' l='77' u='w' c='_ZN5clang6interp8IntegralC1ENS0_8IntegralIXTL0__EXTL0_0_EEE'/>
<use f='llvm/clang/lib/AST/Interp/Integral.h' l='81' u='w' c='_ZN5clang6interp8IntegralC1ERKN4llvm6APSIntE'/>
<use f='llvm/clang/lib/AST/Interp/Integral.h' l='83' c='_ZNK5clang6interp8IntegralltENS0_8IntegralIXT_EXT0_EEE'/>
<use f='llvm/clang/lib/AST/Interp/Integral.h' l='84' c='_ZNK5clang6interp8IntegralgtENS0_8IntegralIXT_EXT0_EEE'/>
<use f='llvm/clang/lib/AST/Interp/Integral.h' l='85' c='_ZNK5clang6interp8IntegralleENS0_8IntegralIXT_EXT0_EEE'/>
<use f='llvm/clang/lib/AST/Interp/Integral.h' l='86' c='_ZNK5clang6interp8IntegralgeENS0_8IntegralIXT_EXT0_EEE'/>
<use f='llvm/clang/lib/AST/Interp/Integral.h' l='87' c='_ZNK5clang6interp8IntegraleqENS0_8IntegralIXT_EXT0_EEE'/>
<use f='llvm/clang/lib/AST/Interp/Integral.h' l='88' c='_ZNK5clang6interp8IntegralneENS0_8IntegralIXT_EXT0_EEE'/>
<use f='llvm/clang/lib/AST/Interp/Integral.h' l='91' c='_ZNK5clang6interp8IntegralgtEj'/>
<use f='llvm/clang/lib/AST/Interp/Integral.h' l='91' u='r' c='_ZNK5clang6interp8IntegralgtEj'/>
<use f='llvm/clang/lib/AST/Interp/Integral.h' l='94' u='r' c='_ZNK5clang6interp8IntegralngEv'/>
<use f='llvm/clang/lib/AST/Interp/Integral.h' l='95' c='_ZNK5clang6interp8IntegralcoEv'/>
<use f='llvm/clang/lib/AST/Interp/Integral.h' l='99' u='r' c='_ZNK5clang6interp8IntegralcvNS0_8IntegralIXTL0__EXTL0_0_EEEEv'/>
<use f='llvm/clang/lib/AST/Interp/Integral.h' l='102' u='r' c='_ZNK5clang6interp8IntegralcvjEv'/>
<use f='llvm/clang/lib/AST/Interp/Integral.h' l='103' u='r' c='_ZNK5clang6interp8IntegralcvlEv'/>
<use f='llvm/clang/lib/AST/Interp/Integral.h' l='104' u='r' c='_ZNK5clang6interp8IntegralcvmEv'/>
<use f='llvm/clang/lib/AST/Interp/Integral.h' l='107' u='r' c='_ZNK5clang6interp8Integral8toAPSIntEv'/>
<use f='llvm/clang/lib/AST/Interp/Integral.h' l='123' u='r' c='_ZNK5clang6interp8Integral6isZeroEv'/>
<use f='llvm/clang/lib/AST/Interp/Integral.h' l='127' c='_ZNK5clang6interp8Integral10isMinusOneEv'/>
<use f='llvm/clang/lib/AST/Interp/Integral.h' l='131' c='_ZNK5clang6interp8Integral10isNegativeEv'/>
<use f='llvm/clang/lib/AST/Interp/Integral.h' l='135' c='_ZNK5clang6interp8Integral7compareERKNS0_8IntegralIXT_EXT0_EEE'/>
<use f='llvm/clang/lib/AST/Interp/Integral.h' l='138' c='_ZNK5clang6interp8Integral17countLeadingZerosEv'/>
<use f='llvm/clang/lib/AST/Interp/Integral.h' l='146' c='_ZNK5clang6interp8Integral8truncateEj'/>
<use f='llvm/clang/lib/AST/Interp/Integral.h' l='146' c='_ZNK5clang6interp8Integral8truncateEj'/>
<use f='llvm/clang/lib/AST/Interp/Integral.h' l='149' c='_ZNK5clang6interp8Integral5printERN4llvm11raw_ostreamE'/>
