<dec f='llvm/clang/include/clang/Parse/Parser.h' l='1116' type='clang::Parser &amp;'/>
<use f='llvm/clang/include/clang/Parse/Parser.h' l='1122' u='w' c='_ZN5clang6Parser15MultiParseScopeC1ERS0_'/>
<use f='llvm/clang/include/clang/Parse/Parser.h' l='1124' u='m' c='_ZN5clang6Parser15MultiParseScope5EnterEj'/>
<use f='llvm/clang/include/clang/Parse/Parser.h' l='1129' u='m' c='_ZN5clang6Parser15MultiParseScope4ExitEv'/>
<offset>0</offset>
