<use f='llvm/clang/include/clang/Analysis/Analyses/ThreadSafetyTIL.h' l='841' u='w' c='_ZN5clang12threadSafety3til5ApplyC1EPNS1_5SExprES4_'/>
<use f='llvm/clang/include/clang/Analysis/Analyses/ThreadSafetyTIL.h' l='843' u='w' c='_ZN5clang12threadSafety3til5ApplyC1ERKS2_PNS1_5SExprES6_'/>
<use f='llvm/clang/include/clang/Analysis/Analyses/ThreadSafetyTIL.h' l='847' u='r' c='_ZN5clang12threadSafety3til5Apply3funEv'/>
<use f='llvm/clang/include/clang/Analysis/Analyses/ThreadSafetyTIL.h' l='848' u='r' c='_ZNK5clang12threadSafety3til5Apply3funEv'/>
<use f='llvm/clang/include/clang/Analysis/Analyses/ThreadSafetyTIL.h' l='855' c='_ZN5clang12threadSafety3til5Apply8traverseERT_NS3_5R_CtxE'/>
<dec f='llvm/clang/include/clang/Analysis/Analyses/ThreadSafetyTIL.h' l='869' type='clang::threadSafety::til::SExpr *'/>
<offset>128</offset>
