<dec f='llvm/clang/include/clang/StaticAnalyzer/Core/PathSensitive/CoreEngine.h' l='492' type='CFGBlock::const_succ_iterator'/>
<use f='llvm/clang/include/clang/StaticAnalyzer/Core/PathSensitive/CoreEngine.h' l='494' u='w' c='_ZN5clang4ento23IndirectGotoNodeBuilder8iteratorC1EPKNS_8CFGBlock13AdjacentBlockE'/>
<use f='llvm/clang/include/clang/StaticAnalyzer/Core/PathSensitive/CoreEngine.h' l='497' u='w' c='_ZN5clang4ento23IndirectGotoNodeBuilder8iteratorppEv'/>
<use f='llvm/clang/include/clang/StaticAnalyzer/Core/PathSensitive/CoreEngine.h' l='498' u='r' c='_ZNK5clang4ento23IndirectGotoNodeBuilder8iteratorneERKS2_'/>
<use f='llvm/clang/include/clang/StaticAnalyzer/Core/PathSensitive/CoreEngine.h' l='498' u='r' c='_ZNK5clang4ento23IndirectGotoNodeBuilder8iteratorneERKS2_'/>
<use f='llvm/clang/include/clang/StaticAnalyzer/Core/PathSensitive/CoreEngine.h' l='501' u='r' c='_ZNK5clang4ento23IndirectGotoNodeBuilder8iterator8getLabelEv'/>
<use f='llvm/clang/include/clang/StaticAnalyzer/Core/PathSensitive/CoreEngine.h' l='505' u='r' c='_ZNK5clang4ento23IndirectGotoNodeBuilder8iterator8getBlockEv'/>
<offset>0</offset>
