<dec f='llvm/clang/include/clang/Sema/DeclSpec.h' l='66' type='clang::NestedNameSpecifierLocBuilder'/>
<use f='llvm/clang/include/clang/Sema/DeclSpec.h' l='78' u='m' c='_ZNK5clang12CXXScopeSpec11getScopeRepEv'/>
<use f='llvm/clang/include/clang/Sema/DeclSpec.h' l='205' u='m' c='_ZN5clang12CXXScopeSpec10SetInvalidENS_11SourceRangeE'/>
<use f='llvm/clang/include/clang/Sema/DeclSpec.h' l='214' u='m' c='_ZN5clang12CXXScopeSpec5clearEv'/>
<use f='llvm/clang/include/clang/Sema/DeclSpec.h' l='218' u='m' c='_ZNK5clang12CXXScopeSpec13location_dataEv'/>
<use f='llvm/clang/include/clang/Sema/DeclSpec.h' l='222' u='m' c='_ZNK5clang12CXXScopeSpec13location_sizeEv'/>
<offset>64</offset>
<use f='llvm/clang/lib/Sema/DeclSpec.cpp' l='55' u='m' c='_ZN5clang12CXXScopeSpec6ExtendERNS_10ASTContextENS_14SourceLocationENS_7TypeLocES3_'/>
<use f='llvm/clang/lib/Sema/DeclSpec.cpp' l='67' u='m' c='_ZN5clang12CXXScopeSpec6ExtendERNS_10ASTContextEPNS_14IdentifierInfoENS_14SourceLocationES5_'/>
<use f='llvm/clang/lib/Sema/DeclSpec.cpp' l='80' u='m' c='_ZN5clang12CXXScopeSpec6ExtendERNS_10ASTContextEPNS_13NamespaceDeclENS_14SourceLocationES5_'/>
<use f='llvm/clang/lib/Sema/DeclSpec.cpp' l='93' u='m' c='_ZN5clang12CXXScopeSpec6ExtendERNS_10ASTContextEPNS_18NamespaceAliasDeclENS_14SourceLocationES5_'/>
<use f='llvm/clang/lib/Sema/DeclSpec.cpp' l='105' u='m' c='_ZN5clang12CXXScopeSpec10MakeGlobalERNS_10ASTContextENS_14SourceLocationE'/>
<use f='llvm/clang/lib/Sema/DeclSpec.cpp' l='116' u='m' c='_ZN5clang12CXXScopeSpec9MakeSuperERNS_10ASTContextEPNS_13CXXRecordDeclENS_14SourceLocationES5_'/>
<use f='llvm/clang/lib/Sema/DeclSpec.cpp' l='127' u='m' c='_ZN5clang12CXXScopeSpec11MakeTrivialERNS_10ASTContextEPNS_19NestedNameSpecifierENS_11SourceRangeE'/>
<use f='llvm/clang/lib/Sema/DeclSpec.cpp' l='134' u='m' c='_ZN5clang12CXXScopeSpec5AdoptENS_22NestedNameSpecifierLocE'/>
<use f='llvm/clang/lib/Sema/DeclSpec.cpp' l='139' u='m' c='_ZN5clang12CXXScopeSpec5AdoptENS_22NestedNameSpecifierLocE'/>
<use f='llvm/clang/lib/Sema/DeclSpec.cpp' l='145' u='m' c='_ZNK5clang12CXXScopeSpec23getLastQualifierNameLocEv'/>
<use f='llvm/clang/lib/Sema/DeclSpec.cpp' l='147' u='m' c='_ZNK5clang12CXXScopeSpec23getLastQualifierNameLocEv'/>
<use f='llvm/clang/lib/Sema/DeclSpec.cpp' l='152' u='m' c='_ZNK5clang12CXXScopeSpec19getWithLocInContextERNS_10ASTContextE'/>
<use f='llvm/clang/lib/Sema/DeclSpec.cpp' l='155' u='m' c='_ZNK5clang12CXXScopeSpec19getWithLocInContextERNS_10ASTContextE'/>
