<dec f='llvm/clang/include/clang/Tooling/DependencyScanning/DependencyScanningService.h' l='38' type='0'/>
<doc f='llvm/clang/include/clang/Tooling/DependencyScanning/DependencyScanningService.h' l='35'>/// This is the Makefile compatible dep format. This will include all of the
  /// deps necessary for an implicit modules build, but won&apos;t include any
  /// intermodule dependency information.</doc>
<use f='llvm/clang/lib/Tooling/DependencyScanning/DependencyScanningWorker.cpp' l='117' c='_ZN12_GLOBAL__N_124DependencyScanningAction13runInvocationESt10shared_ptrIN5clang18CompilerInvocationEEPNS2_11FileManagerES1_INS2_22PCHContainerOperat11311088'/>
<use f='llvm/clang/tools/clang-scan-deps/ClangScanDeps.cpp' l='125' u='a'/>
<use f='llvm/clang/tools/clang-scan-deps/ClangScanDeps.cpp' l='131' u='r'/>
<use f='llvm/clang/tools/clang-scan-deps/ClangScanDeps.cpp' l='529' u='r' c='main'/>
