<dec f='llvm/clang/include/clang/Sema/Sema.h' l='12706' type='clang::Expr *'/>
<use f='llvm/clang/include/clang/Sema/Sema.h' l='12711' u='w' c='_ZN5clang4Sema16MisalignedMemberC1Ev'/>
<use f='llvm/clang/include/clang/Sema/Sema.h' l='12714' u='w' c='_ZN5clang4Sema16MisalignedMemberC1EPNS_4ExprEPNS_10RecordDeclEPNS_9ValueDeclENS_9CharUnitsE'/>
<use f='llvm/clang/include/clang/Sema/Sema.h' l='12718' u='r' c='_ZN5clang4Sema16MisalignedMembereqERKS1_'/>
<use f='llvm/clang/include/clang/Sema/Sema.h' l='12718' u='r' c='_ZN5clang4Sema16MisalignedMembereqERKS1_'/>
<offset>0</offset>
<use f='llvm/clang/lib/Sema/SemaChecking.cpp' l='15662' u='r' c='_ZN5clang4Sema25DiagnoseMisalignedMembersEv'/>
<use f='llvm/clang/lib/Sema/SemaChecking.cpp' l='15663' u='r' c='_ZN5clang4Sema25DiagnoseMisalignedMembersEv'/>
