<dec f='llvm/clang/include/clang/StaticAnalyzer/Core/PathSensitive/SymExpr.h' l='40' type='clang::ento::SymExpr::Kind'/>
<use f='llvm/clang/include/clang/StaticAnalyzer/Core/PathSensitive/SymExpr.h' l='43' u='w' c='_ZN5clang4ento7SymExprC1ENS1_4KindE'/>
<use f='llvm/clang/include/clang/StaticAnalyzer/Core/PathSensitive/SymExpr.h' l='56' u='r' c='_ZNK5clang4ento7SymExpr7getKindEv'/>
<offset>128</offset>
