<dec f='llvm/clang/include/clang/StaticAnalyzer/Core/PathSensitive/MemRegion.h' l='473' type='const clang::Expr *'/>
<use f='llvm/clang/include/clang/StaticAnalyzer/Core/PathSensitive/MemRegion.h' l='476' u='w' c='_ZN5clang4ento12AllocaRegionC1EPKNS_4ExprEjPKNS0_14MemSpaceRegionE'/>
<use f='llvm/clang/include/clang/StaticAnalyzer/Core/PathSensitive/MemRegion.h' l='484' u='r' c='_ZNK5clang4ento12AllocaRegion7getExprEv'/>
<offset>512</offset>
<use f='llvm/clang/lib/StaticAnalyzer/Core/MemRegion.cpp' l='250' u='r' c='_ZNK5clang4ento12AllocaRegion7ProfileERN4llvm16FoldingSetNodeIDE'/>
<use f='llvm/clang/lib/StaticAnalyzer/Core/MemRegion.cpp' l='453' u='r' c='_ZNK5clang4ento12AllocaRegion12dumpToStreamERN4llvm11raw_ostreamE'/>
