<dec f='llvm/clang/include/clang/Basic/SourceLocation.h' l='214' type='clang::SourceLocation'/>
<use f='llvm/clang/include/clang/Basic/SourceLocation.h' l='218' u='w' c='_ZN5clang11SourceRangeC1ENS_14SourceLocationE'/>
<use f='llvm/clang/include/clang/Basic/SourceLocation.h' l='219' u='w' c='_ZN5clang11SourceRangeC1ENS_14SourceLocationES1_'/>
<use f='llvm/clang/include/clang/Basic/SourceLocation.h' l='222' u='r' c='_ZNK5clang11SourceRange6getEndEv'/>
<use f='llvm/clang/include/clang/Basic/SourceLocation.h' l='225' u='w' c='_ZN5clang11SourceRange6setEndENS_14SourceLocationE'/>
<use f='llvm/clang/include/clang/Basic/SourceLocation.h' l='227' u='m' c='_ZNK5clang11SourceRange7isValidEv'/>
<use f='llvm/clang/include/clang/Basic/SourceLocation.h' l='231' u='r' c='_ZNK5clang11SourceRangeeqERKS0_'/>
<use f='llvm/clang/include/clang/Basic/SourceLocation.h' l='231' u='r' c='_ZNK5clang11SourceRangeeqERKS0_'/>
<use f='llvm/clang/include/clang/Basic/SourceLocation.h' l='235' u='r' c='_ZNK5clang11SourceRangeneERKS0_'/>
<use f='llvm/clang/include/clang/Basic/SourceLocation.h' l='235' u='r' c='_ZNK5clang11SourceRangeneERKS0_'/>
<use f='llvm/clang/include/clang/Basic/SourceLocation.h' l='240' u='r' c='_ZNK5clang11SourceRange13fullyContainsERKS0_'/>
<use f='llvm/clang/include/clang/Basic/SourceLocation.h' l='240' u='r' c='_ZNK5clang11SourceRange13fullyContainsERKS0_'/>
<offset>32</offset>
<use f='llvm/clang/lib/Basic/SourceLocation.cpp' l='140' u='r' c='_ZNK5clang11SourceRange5printERN4llvm11raw_ostreamERKNS_13SourceManagerE'/>
<use f='llvm/clang/lib/Basic/SourceLocation.cpp' l='142' u='r' c='_ZNK5clang11SourceRange5printERN4llvm11raw_ostreamERKNS_13SourceManagerE'/>
