<dec f='llvm/clang/include/clang/Tooling/Syntax/Tokens.h' l='448' type='clang::Preprocessor &amp;'/>
<offset>384</offset>
<use f='llvm/clang/lib/Tooling/Syntax/Tokens.cpp' l='550' u='m' c='_ZN5clang6syntax14TokenCollector19CollectPPExpansions12MacroExpandsERKNS_5TokenERKNS_15MacroDefinitionENS_11SourceRangeEPKNS_9MacroArgsE'/>
<use f='llvm/clang/lib/Tooling/Syntax/Tokens.cpp' l='605' u='w' c='_ZN5clang6syntax14TokenCollectorC1ERNS_12PreprocessorE'/>
<use f='llvm/clang/lib/Tooling/Syntax/Tokens.cpp' l='818' u='m' c='_ZNO5clang6syntax14TokenCollector7consumeEv'/>
<use f='llvm/clang/lib/Tooling/Syntax/Tokens.cpp' l='821' u='m' c='_ZNO5clang6syntax14TokenCollector7consumeEv'/>
<use f='llvm/clang/lib/Tooling/Syntax/Tokens.cpp' l='821' u='m' c='_ZNO5clang6syntax14TokenCollector7consumeEv'/>
