<dec f='llvm/clang/include/clang/Serialization/ASTReader.h' l='730' type='clang::ASTReader::ModuleFile *'/>
<use f='llvm/clang/include/clang/Serialization/ASTReader.h' l='735' u='w' c='_ZN5clang9ASTReader16PendingMacroInfoC1EPNS_13serialization10ModuleFileEj'/>
<offset>0</offset>
<use f='llvm/clang/lib/Serialization/ASTReader.cpp' l='2091' u='r' c='_ZN5clang9ASTReader19resolvePendingMacroEPNS_14IdentifierInfoERKNS0_16PendingMacroInfoE'/>
<use f='llvm/clang/lib/Serialization/ASTReader.cpp' l='9239' u='r' c='_ZN5clang9ASTReader20finishPendingActionsEv'/>
<use f='llvm/clang/lib/Serialization/ASTReader.cpp' l='9246' u='r' c='_ZN5clang9ASTReader20finishPendingActionsEv'/>
