<dec f='llvm/clang/include/clang/StaticAnalyzer/Core/PathSensitive/MemRegion.h' l='259' type='const clang::ento::CodeTextRegion *'/>
<use f='llvm/clang/include/clang/StaticAnalyzer/Core/PathSensitive/MemRegion.h' l='262' u='w' c='_ZN5clang4ento23StaticGlobalSpaceRegionC1ERNS0_16MemRegionManagerEPKNS0_14CodeTextRegionE'/>
<use f='llvm/clang/include/clang/StaticAnalyzer/Core/PathSensitive/MemRegion.h' l='271' u='r' c='_ZNK5clang4ento23StaticGlobalSpaceRegion13getCodeRegionEv'/>
<offset>448</offset>
<use f='llvm/clang/lib/StaticAnalyzer/Core/MemRegion.cpp' l='546' u='r' c='_ZNK5clang4ento23StaticGlobalSpaceRegion12dumpToStreamERN4llvm11raw_ostreamE'/>
