<dec f='llvm/clang/include/clang/Analysis/CFG.h' l='995' type='IMPL'/>
<use f='llvm/clang/include/clang/Analysis/CFG.h' l='1003' u='w' c='_ZN5clang8CFGBlock24FilteredCFGBlockIteratorC1ERKT_S4_PKS0_RKNS0_13FilterOptionsE'/>
<use f='llvm/clang/include/clang/Analysis/CFG.h' l='1004' c='_ZN5clang8CFGBlock24FilteredCFGBlockIteratorC1ERKT_S4_PKS0_RKNS0_13FilterOptionsE'/>
<use f='llvm/clang/include/clang/Analysis/CFG.h' l='1005' u='w' c='_ZN5clang8CFGBlock24FilteredCFGBlockIteratorC1ERKT_S4_PKS0_RKNS0_13FilterOptionsE'/>
<use f='llvm/clang/include/clang/Analysis/CFG.h' l='1008' c='_ZNK5clang8CFGBlock24FilteredCFGBlockIterator7hasMoreEv'/>
<use f='llvm/clang/include/clang/Analysis/CFG.h' l='1011' u='w' c='_ZN5clang8CFGBlock24FilteredCFGBlockIteratorppEv'/>
<use f='llvm/clang/include/clang/Analysis/CFG.h' l='1011' c='_ZN5clang8CFGBlock24FilteredCFGBlockIteratorppEv'/>
<use f='llvm/clang/include/clang/Analysis/CFG.h' l='1015' c='_ZNK5clang8CFGBlock24FilteredCFGBlockIteratordeEv'/>
