<dec f='llvm/clang/include/clang/Sema/DeclSpec.h' l='2673' type='clang::ExprResult'/>
<use f='llvm/clang/include/clang/Sema/DeclSpec.h' l='2683' u='w' c='_ZN5clang16LambdaIntroducer13LambdaCaptureC1ENS_17LambdaCaptureKindENS_14SourceLocationEPNS_14IdentifierInfoES3_NS_21LambdaCaptureInitKindENS_12Action10970978'/>
<offset>192</offset>
<use f='llvm/clang/lib/Sema/SemaLambda.cpp' l='1088' u='m' c='_ZN5clang4Sema28ActOnStartOfLambdaDefinitionERNS_16LambdaIntroducerERNS_10DeclaratorEPNS_5ScopeE'/>
<use f='llvm/clang/lib/Sema/SemaLambda.cpp' l='1092' u='m' c='_ZN5clang4Sema28ActOnStartOfLambdaDefinitionERNS_16LambdaIntroducerERNS_10DeclaratorEPNS_5ScopeE'/>
<use f='llvm/clang/lib/Sema/SemaLambda.cpp' l='1105' u='m' c='_ZN5clang4Sema28ActOnStartOfLambdaDefinitionERNS_16LambdaIntroducerERNS_10DeclaratorEPNS_5ScopeE'/>
<use f='llvm/clang/lib/Sema/SemaLambda.cpp' l='1107' u='m' c='_ZN5clang4Sema28ActOnStartOfLambdaDefinitionERNS_16LambdaIntroducerERNS_10DeclaratorEPNS_5ScopeE'/>
<use f='llvm/clang/lib/Sema/SemaLambda.cpp' l='1125' u='m' c='_ZN5clang4Sema28ActOnStartOfLambdaDefinitionERNS_16LambdaIntroducerERNS_10DeclaratorEPNS_5ScopeE'/>
<use f='llvm/clang/lib/Sema/SemaLambda.cpp' l='1217' u='m' c='_ZN5clang4Sema28ActOnStartOfLambdaDefinitionERNS_16LambdaIntroducerERNS_10DeclaratorEPNS_5ScopeE'/>
<use f='llvm/clang/lib/Sema/SemaLambda.cpp' l='1217' u='m' c='_ZN5clang4Sema28ActOnStartOfLambdaDefinitionERNS_16LambdaIntroducerERNS_10DeclaratorEPNS_5ScopeE'/>
<use f='llvm/clang/lib/Sema/SemaLambda.cpp' l='1226' u='m' c='_ZN5clang4Sema28ActOnStartOfLambdaDefinitionERNS_16LambdaIntroducerERNS_10DeclaratorEPNS_5ScopeE'/>
