<dec f='llvm/clang/include/clang/Parse/Parser.h' l='1078' type='clang::Parser *'/>
<use f='llvm/clang/include/clang/Parse/Parser.h' l='1088' u='w' c='_ZN5clang6Parser10ParseScopeC1EPS0_jbb'/>
<use f='llvm/clang/include/clang/Parse/Parser.h' l='1095' u='w' c='_ZN5clang6Parser10ParseScopeC1EPS0_jbb'/>
<use f='llvm/clang/include/clang/Parse/Parser.h' l='1102' u='r' c='_ZN5clang6Parser10ParseScope4ExitEv'/>
<use f='llvm/clang/include/clang/Parse/Parser.h' l='1103' u='r' c='_ZN5clang6Parser10ParseScope4ExitEv'/>
<use f='llvm/clang/include/clang/Parse/Parser.h' l='1104' u='w' c='_ZN5clang6Parser10ParseScope4ExitEv'/>
<offset>0</offset>
