<dec f='llvm/clang/include/clang/AST/Stmt.h' l='2502' type='3'/>
<use f='llvm/clang/include/clang/AST/Stmt.h' l='2534' u='r' c='_ZN5clang7ForStmt6getIncEv'/>
<use f='llvm/clang/include/clang/AST/Stmt.h' l='2539' u='r' c='_ZNK5clang7ForStmt6getIncEv'/>
<use f='llvm/clang/include/clang/AST/Stmt.h' l='2544' u='w' c='_ZN5clang7ForStmt6setIncEPNS_4ExprE'/>
<use f='llvm/clang/lib/AST/Stmt.cpp' l='1006' u='w' c='_ZN5clang7ForStmtC1ERKNS_10ASTContextEPNS_4StmtEPNS_4ExprEPNS_7VarDeclES7_S5_NS_14SourceLocationESA_SA_'/>
