<dec f='llvm/clang/include/clang/Basic/ProfileList.h' l='33' type='std::unique_ptr&lt;ProfileSpecialCaseList&gt;'/>
<offset>0</offset>
<use f='llvm/clang/lib/Basic/ProfileList.cpp' l='67' u='w' c='_ZN5clang11ProfileListC1EN4llvm8ArrayRefINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEERNS_13SourceManagerE'/>
<use f='llvm/clang/lib/Basic/ProfileList.cpp' l='69' u='m' c='_ZN5clang11ProfileListC1EN4llvm8ArrayRefINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEERNS_13SourceManagerE'/>
<use f='llvm/clang/lib/Basic/ProfileList.cpp' l='70' u='m' c='_ZN5clang11ProfileListC1EN4llvm8ArrayRefINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEERNS_13SourceManagerE'/>
<use f='llvm/clang/lib/Basic/ProfileList.cpp' l='70' u='m' c='_ZN5clang11ProfileListC1EN4llvm8ArrayRefINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEERNS_13SourceManagerE'/>
<use f='llvm/clang/lib/Basic/ProfileList.cpp' l='92' u='m' c='_ZNK5clang11ProfileList18isFunctionExcludedEN4llvm9StringRefENS_14CodeGenOptions16ProfileInstrKindE'/>
<use f='llvm/clang/lib/Basic/ProfileList.cpp' l='94' u='m' c='_ZNK5clang11ProfileList18isFunctionExcludedEN4llvm9StringRefENS_14CodeGenOptions16ProfileInstrKindE'/>
<use f='llvm/clang/lib/Basic/ProfileList.cpp' l='109' u='m' c='_ZNK5clang11ProfileList14isFileExcludedEN4llvm9StringRefENS_14CodeGenOptions16ProfileInstrKindE'/>
<use f='llvm/clang/lib/Basic/ProfileList.cpp' l='111' u='m' c='_ZNK5clang11ProfileList14isFileExcludedEN4llvm9StringRefENS_14CodeGenOptions16ProfileInstrKindE'/>
