<dec f='llvm/clang/include/clang/StaticAnalyzer/Core/PathSensitive/CoreEngine.h' l='539' type='CFGBlock::const_succ_reverse_iterator'/>
<use f='llvm/clang/include/clang/StaticAnalyzer/Core/PathSensitive/CoreEngine.h' l='541' u='w' c='_ZN5clang4ento17SwitchNodeBuilder8iteratorC1ESt16reverse_iteratorIPKNS_8CFGBlock13AdjacentBlockEE'/>
<use f='llvm/clang/include/clang/StaticAnalyzer/Core/PathSensitive/CoreEngine.h' l='544' u='w' c='_ZN5clang4ento17SwitchNodeBuilder8iteratorppEv'/>
<use f='llvm/clang/include/clang/StaticAnalyzer/Core/PathSensitive/CoreEngine.h' l='545' u='r' c='_ZNK5clang4ento17SwitchNodeBuilder8iteratorneERKS2_'/>
<use f='llvm/clang/include/clang/StaticAnalyzer/Core/PathSensitive/CoreEngine.h' l='545' u='r' c='_ZNK5clang4ento17SwitchNodeBuilder8iteratorneERKS2_'/>
<use f='llvm/clang/include/clang/StaticAnalyzer/Core/PathSensitive/CoreEngine.h' l='546' u='r' c='_ZNK5clang4ento17SwitchNodeBuilder8iteratoreqERKS2_'/>
<use f='llvm/clang/include/clang/StaticAnalyzer/Core/PathSensitive/CoreEngine.h' l='546' u='r' c='_ZNK5clang4ento17SwitchNodeBuilder8iteratoreqERKS2_'/>
<use f='llvm/clang/include/clang/StaticAnalyzer/Core/PathSensitive/CoreEngine.h' l='549' u='m' c='_ZNK5clang4ento17SwitchNodeBuilder8iterator7getCaseEv'/>
<use f='llvm/clang/include/clang/StaticAnalyzer/Core/PathSensitive/CoreEngine.h' l='553' u='m' c='_ZNK5clang4ento17SwitchNodeBuilder8iterator8getBlockEv'/>
<offset>0</offset>
