<dec f='llvm/clang/lib/CodeGen/CGOpenMPRuntime.h' l='1148' type='clang::CodeGen::Address'/>
<use f='llvm/clang/lib/CodeGen/CGOpenMPRuntime.h' l='1156' u='w' c='_ZN5clang7CodeGen15CGOpenMPRuntime13StaticRTInputC1EjbbNS0_7AddressES3_S3_S3_PN4llvm5ValueE'/>
<offset>448</offset>
<doc f='llvm/clang/lib/CodeGen/CGOpenMPRuntime.h' l='1146'>/// Address of the output variable in which the stride value is returned
    /// necessary to generated the static_chunked scheduled loop.</doc>
<use f='llvm/clang/lib/CodeGen/CGOpenMPRuntime.cpp' l='2757' u='m' c='_ZL21emitForStaticInitCallRN5clang7CodeGen15CodeGenFunctionEPN4llvm5ValueES5_NS3_14FunctionCalleeEN12_GLOBAL__N_115OpenMPSchedTypeENS_28OpenMPSchedule5494257'/>
