<dec f='llvm/clang/include/clang/Sema/CodeCompleteConsumer.h' l='1173' type='llvm::raw_ostream &amp;'/>
<use f='llvm/clang/include/clang/Sema/CodeCompleteConsumer.h' l='1182' u='w' c='_ZN5clang28PrintingCodeCompleteConsumerC1ERKNS_19CodeCompleteOptionsERN4llvm11raw_ostreamE'/>
<offset>128</offset>
<doc f='llvm/clang/include/clang/Sema/CodeCompleteConsumer.h' l='1172'>/// The raw output stream.</doc>
<use f='llvm/clang/lib/Sema/CodeCompleteConsumer.cpp' l='541' u='m' c='_ZN5clang28PrintingCodeCompleteConsumer26ProcessCodeCompleteResultsERNS_4SemaENS_21CodeCompletionContextEPNS_20CodeCompletionResultEj'/>
<use f='llvm/clang/lib/Sema/CodeCompleteConsumer.cpp' l='549' u='m' c='_ZN5clang28PrintingCodeCompleteConsumer26ProcessCodeCompleteResultsERNS_4SemaENS_21CodeCompletionContextEPNS_20CodeCompletionResultEj'/>
<use f='llvm/clang/lib/Sema/CodeCompleteConsumer.cpp' l='552' u='a' c='_ZN5clang28PrintingCodeCompleteConsumer26ProcessCodeCompleteResultsERNS_4SemaENS_21CodeCompletionContextEPNS_20CodeCompletionResultEj'/>
<use f='llvm/clang/lib/Sema/CodeCompleteConsumer.cpp' l='563' u='m' c='_ZN5clang28PrintingCodeCompleteConsumer26ProcessCodeCompleteResultsERNS_4SemaENS_21CodeCompletionContextEPNS_20CodeCompletionResultEj'/>
<use f='llvm/clang/lib/Sema/CodeCompleteConsumer.cpp' l='568' u='m' c='_ZN5clang28PrintingCodeCompleteConsumer26ProcessCodeCompleteResultsERNS_4SemaENS_21CodeCompletionContextEPNS_20CodeCompletionResultEj'/>
<use f='llvm/clang/lib/Sema/CodeCompleteConsumer.cpp' l='570' u='m' c='_ZN5clang28PrintingCodeCompleteConsumer26ProcessCodeCompleteResultsERNS_4SemaENS_21CodeCompletionContextEPNS_20CodeCompletionResultEj'/>
<use f='llvm/clang/lib/Sema/CodeCompleteConsumer.cpp' l='575' u='m' c='_ZN5clang28PrintingCodeCompleteConsumer26ProcessCodeCompleteResultsERNS_4SemaENS_21CodeCompletionContextEPNS_20CodeCompletionResultEj'/>
<use f='llvm/clang/lib/Sema/CodeCompleteConsumer.cpp' l='579' u='m' c='_ZN5clang28PrintingCodeCompleteConsumer26ProcessCodeCompleteResultsERNS_4SemaENS_21CodeCompletionContextEPNS_20CodeCompletionResultEj'/>
<use f='llvm/clang/lib/Sema/CodeCompleteConsumer.cpp' l='583' u='m' c='_ZN5clang28PrintingCodeCompleteConsumer26ProcessCodeCompleteResultsERNS_4SemaENS_21CodeCompletionContextEPNS_20CodeCompletionResultEj'/>
<use f='llvm/clang/lib/Sema/CodeCompleteConsumer.cpp' l='588' u='m' c='_ZN5clang28PrintingCodeCompleteConsumer26ProcessCodeCompleteResultsERNS_4SemaENS_21CodeCompletionContextEPNS_20CodeCompletionResultEj'/>
<use f='llvm/clang/lib/Sema/CodeCompleteConsumer.cpp' l='602' u='m' c='_ZN5clang28PrintingCodeCompleteConsumer26ProcessCodeCompleteResultsERNS_4SemaENS_21CodeCompletionContextEPNS_20CodeCompletionResultEj'/>
<use f='llvm/clang/lib/Sema/CodeCompleteConsumer.cpp' l='609' u='m' c='_ZN5clang28PrintingCodeCompleteConsumer26ProcessCodeCompleteResultsERNS_4SemaENS_21CodeCompletionContextEPNS_20CodeCompletionResultEj'/>
<use f='llvm/clang/lib/Sema/CodeCompleteConsumer.cpp' l='647' u='m' c='_ZN5clang28PrintingCodeCompleteConsumer25ProcessOverloadCandidatesERNS_4SemaEjPNS_20CodeCompleteConsumer17OverloadCandidateEjNS_14SourceLocationE'/>
<use f='llvm/clang/lib/Sema/CodeCompleteConsumer.cpp' l='648' u='a' c='_ZN5clang28PrintingCodeCompleteConsumer25ProcessOverloadCandidatesERNS_4SemaEjPNS_20CodeCompleteConsumer17OverloadCandidateEjNS_14SourceLocationE'/>
<use f='llvm/clang/lib/Sema/CodeCompleteConsumer.cpp' l='649' u='m' c='_ZN5clang28PrintingCodeCompleteConsumer25ProcessOverloadCandidatesERNS_4SemaEjPNS_20CodeCompleteConsumer17OverloadCandidateEjNS_14SourceLocationE'/>
<use f='llvm/clang/lib/Sema/CodeCompleteConsumer.cpp' l='655' u='m' c='_ZN5clang28PrintingCodeCompleteConsumer25ProcessOverloadCandidatesERNS_4SemaEjPNS_20CodeCompleteConsumer17OverloadCandidateEjNS_14SourceLocationE'/>
