<dec f='llvm/clang/include/clang/StaticAnalyzer/Core/PathSensitive/CoreEngine.h' l='481' type='const clang::Expr *'/>
<use f='llvm/clang/include/clang/StaticAnalyzer/Core/PathSensitive/CoreEngine.h' l='487' u='w' c='_ZN5clang4ento23IndirectGotoNodeBuilderC1EPNS0_12ExplodedNodeEPKNS_8CFGBlockEPKNS_4ExprES6_PNS0_10CoreEngineE'/>
<use f='llvm/clang/include/clang/StaticAnalyzer/Core/PathSensitive/CoreEngine.h' l='516' u='r' c='_ZNK5clang4ento23IndirectGotoNodeBuilder9getTargetEv'/>
<offset>192</offset>
