<dec f='llvm/clang/include/clang/Serialization/ASTReader.h' l='277' type='clang::Preprocessor &amp;'/>
<use f='llvm/clang/include/clang/Serialization/ASTReader.h' l='282' u='w' c='_ZN5clang12PCHValidatorC1ERNS_12PreprocessorERNS_9ASTReaderE'/>
<offset>64</offset>
<use f='llvm/clang/lib/Serialization/ASTReader.cpp' l='440' u='m' c='_ZN5clang12PCHValidator19ReadLanguageOptionsERKNS_11LangOptionsEbb'/>
<use f='llvm/clang/lib/Serialization/ASTReader.cpp' l='449' u='m' c='_ZN5clang12PCHValidator17ReadTargetOptionsERKNS_13TargetOptionsEbb'/>
<use f='llvm/clang/lib/Serialization/ASTReader.cpp' l='564' u='m' c='_ZN5clang12PCHValidator21ReadDiagnosticOptionsEN4llvm18IntrusiveRefCntPtrINS_17DiagnosticOptionsEEEb'/>
<use f='llvm/clang/lib/Serialization/ASTReader.cpp' l='575' u='a' c='_ZN5clang12PCHValidator21ReadDiagnosticOptionsEN4llvm18IntrusiveRefCntPtrINS_17DiagnosticOptionsEEEb'/>
<use f='llvm/clang/lib/Serialization/ASTReader.cpp' l='755' u='m' c='_ZN5clang12PCHValidator23ReadPreprocessorOptionsERKNS_19PreprocessorOptionsEbRNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE'/>
<use f='llvm/clang/lib/Serialization/ASTReader.cpp' l='759' u='m' c='_ZN5clang12PCHValidator23ReadPreprocessorOptionsERKNS_19PreprocessorOptionsEbRNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE'/>
<use f='llvm/clang/lib/Serialization/ASTReader.cpp' l='761' u='m' c='_ZN5clang12PCHValidator23ReadPreprocessorOptionsERKNS_19PreprocessorOptionsEbRNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE'/>
<use f='llvm/clang/lib/Serialization/ASTReader.cpp' l='802' u='m' c='_ZN5clang12PCHValidator23ReadHeaderSearchOptionsERKNS_19HeaderSearchOptionsEN4llvm9StringRefEb'/>
<use f='llvm/clang/lib/Serialization/ASTReader.cpp' l='804' u='m' c='_ZN5clang12PCHValidator23ReadHeaderSearchOptionsERKNS_19HeaderSearchOptionsEN4llvm9StringRefEb'/>
<use f='llvm/clang/lib/Serialization/ASTReader.cpp' l='808' u='m' c='_ZN5clang12PCHValidator11ReadCounterERKNS_13serialization10ModuleFileEj'/>
