<dec f='llvm/clang/include/clang/StaticAnalyzer/Core/PathSensitive/MemRegion.h' l='1183' type='const clang::Expr *'/>
<use f='llvm/clang/include/clang/StaticAnalyzer/Core/PathSensitive/MemRegion.h' l='1186' u='w' c='_ZN5clang4ento19CXXTempObjectRegionC1EPKNS_4ExprEPKNS0_14MemSpaceRegionE'/>
<use f='llvm/clang/include/clang/StaticAnalyzer/Core/PathSensitive/MemRegion.h' l='1196' u='r' c='_ZNK5clang4ento19CXXTempObjectRegion7getExprEv'/>
<use f='llvm/clang/include/clang/StaticAnalyzer/Core/PathSensitive/MemRegion.h' l='1198' u='r' c='_ZNK5clang4ento19CXXTempObjectRegion12getValueTypeEv'/>
<offset>448</offset>
<use f='llvm/clang/lib/StaticAnalyzer/Core/MemRegion.cpp' l='388' u='r' c='_ZNK5clang4ento19CXXTempObjectRegion7ProfileERN4llvm16FoldingSetNodeIDE'/>
<use f='llvm/clang/lib/StaticAnalyzer/Core/MemRegion.cpp' l='482' u='r' c='_ZNK5clang4ento19CXXTempObjectRegion12dumpToStreamERN4llvm11raw_ostreamE'/>
