<dec f='llvm/clang/tools/libclang/CXIndexDataConsumer.h' l='49' type='const clang::NamedDecl *'/>
<use f='llvm/clang/tools/libclang/CXIndexDataConsumer.cpp' l='991' u='r' c='_ZN5clang7cxindex19CXIndexDataConsumer19handleCXXRecordDeclEPKNS_13CXXRecordDeclEPKNS_9NamedDeclE'/>
<use f='llvm/clang/tools/libclang/CXIndexDataConsumer.cpp' l='1144' u='w' c='_ZN5clang7cxindex19CXIndexDataConsumer13getEntityInfoEPKNS_9NamedDeclERNS0_10EntityInfoERNS0_12ScratchAllocE'/>
<offset>640</offset>
<use f='llvm/clang/tools/libclang/Indexing.cpp' l='841' u='r' c='clang_index_getClientEntity'/>
<use f='llvm/clang/tools/libclang/Indexing.cpp' l='849' u='r' c='clang_index_setClientEntity'/>
