<dec f='llvm/clang/include/clang/AST/Type.h' l='1041' type='const clang::QualType &amp;'/>
<use f='llvm/clang/include/clang/AST/Type.h' l='1049' u='w' c='_ZN5clang8QualType22StreamedQualTypeHelperC1ERKS0_RKNS_14PrintingPolicyERKN4llvm5TwineEj'/>
<use f='llvm/clang/include/clang/AST/Type.h' l='1054' u='m' c='_ZN5clanglsERN4llvm11raw_ostreamERKNS_8QualType22StreamedQualTypeHelperE'/>
<offset>0</offset>
