<use f='llvm/clang/lib/AST/Interp/Program.h' l='156' u='w' c='_ZN5clang6interp7Program6GlobalC1EDpT_'/>
<use f='llvm/clang/lib/AST/Interp/Program.h' l='164' u='m' c='_ZN5clang6interp7Program6Global4dataEv'/>
<use f='llvm/clang/lib/AST/Interp/Program.h' l='166' u='a' c='_ZN5clang6interp7Program6Global5blockEv'/>
<dec f='llvm/clang/lib/AST/Interp/Program.h' l='170' type='clang::interp::Block'/>
<offset>0</offset>
<doc f='llvm/clang/lib/AST/Interp/Program.h' l='169'>/// Required metadata - does not actually track pointers.</doc>
