<def f='llvm/clang/include/clang/AST/APValue.h' l='275' ll='280'/>
<use f='llvm/clang/include/clang/AST/APValue.h' l='302'/>
<use f='llvm/clang/include/clang/AST/APValue.h' l='505' c='_ZN5clang7APValue22getArrayInitializedEltEj'/>
<use f='llvm/clang/include/clang/AST/APValue.h' l='516' c='_ZN5clang7APValue14getArrayFillerEv'/>
<use f='llvm/clang/include/clang/AST/APValue.h' l='523' c='_ZNK5clang7APValue23getArrayInitializedEltsEv'/>
<use f='llvm/clang/include/clang/AST/APValue.h' l='527' c='_ZNK5clang7APValue12getArraySizeEv'/>
<size>16</size>
<mbr r='clang::APValue::Arr::Elts' o='0' t='clang::APValue *'/>
<mbr r='clang::APValue::Arr::NumElts' o='64' t='unsigned int'/>
<mbr r='clang::APValue::Arr::ArrSize' o='96' t='unsigned int'/>
<fun r='_ZN5clang7APValue3ArrC1Ejj'/>
<fun r='_ZN5clang7APValue3ArrD1Ev'/>
<use f='llvm/clang/lib/AST/APValue.cpp' l='417' c='_ZN5clang7APValue24DestroyDataAndMakeUninitEv'/>
<use f='llvm/clang/lib/AST/APValue.cpp' l='1006' c='_ZN5clang7APValue9MakeArrayEjj'/>
<size>16</size>
<fun r='_ZN5clang7APValue3ArrC1Ejj'/>
<fun r='_ZN5clang7APValue3ArrD1Ev'/>
<use f='llvm/clang/lib/AST/ASTImporter.cpp' l='9101' c='_ZN5clang15ASTNodeImporter13ImportAPValueERKNS_7APValueE'/>
<use f='llvm/clang/lib/AST/ASTImporter.cpp' l='9102' c='_ZN5clang15ASTNodeImporter13ImportAPValueERKNS_7APValueE'/>
<size>16</size>
