<dec f='llvm/clang/include/clang/Driver/ToolChain.h' l='121' type='const clang::driver::Driver &amp;'/>
<use f='llvm/clang/include/clang/Driver/ToolChain.h' l='205' u='a' c='_ZNK5clang6driver9ToolChain9getDriverEv'/>
<offset>64</offset>
<use f='llvm/clang/lib/Driver/ToolChain.cpp' l='76' u='w' c='_ZN5clang6driver9ToolChainC1ERKNS0_6DriverERKN4llvm6TripleERKNS5_3opt7ArgListE'/>
<use f='llvm/clang/lib/Driver/ToolChain.cpp' l='480' u='m' c='_ZNK5clang6driver9ToolChain14getRuntimePathB5cxx11Ev'/>
<use f='llvm/clang/lib/Driver/ToolChain.cpp' l='481' u='m' c='_ZNK5clang6driver9ToolChain14getRuntimePathB5cxx11Ev'/>
<use f='llvm/clang/lib/Driver/ToolChain.cpp' l='486' u='m' c='_ZNK5clang6driver9ToolChain14getRuntimePathB5cxx11Ev'/>
<use f='llvm/clang/lib/Driver/ToolChain.cpp' l='498' u='m' c='_ZNK5clang6driver9ToolChain16getCXXStdlibPathB5cxx11Ev'/>
<use f='llvm/clang/lib/Driver/ToolChain.cpp' l='499' u='m' c='_ZNK5clang6driver9ToolChain16getCXXStdlibPathB5cxx11Ev'/>
<use f='llvm/clang/lib/Driver/ToolChain.cpp' l='504' u='m' c='_ZNK5clang6driver9ToolChain16getCXXStdlibPathB5cxx11Ev'/>
<use f='llvm/clang/lib/Driver/ToolChain.cpp' l='540' u='m' c='_ZNK5clang6driver9ToolChain10SelectToolERKNS0_9JobActionE'/>
<use f='llvm/clang/lib/Driver/ToolChain.cpp' l='549' u='m' c='_ZNK5clang6driver9ToolChain11GetFilePathB5cxx11EPKc'/>
<use f='llvm/clang/lib/Driver/ToolChain.cpp' l='553' u='m' c='_ZNK5clang6driver9ToolChain14GetProgramPathB5cxx11EPKc'/>
<use f='llvm/clang/lib/Driver/ToolChain.cpp' l='640' u='m' c='_ZNK5clang6driver9ToolChain22LookupTypeForExtensionEN4llvm9StringRefE'/>
<use f='llvm/clang/lib/Driver/ToolChain.cpp' l='834' u='m' c='_ZNK5clang6driver9ToolChain17ComputeLLVMTripleB5cxx11ERKN4llvm3opt7ArgListENS0_5types2IDE'/>
<use f='llvm/clang/lib/Driver/ToolChain.cpp' l='852' u='m' c='_ZNK5clang6driver9ToolChain14computeSysRootB5cxx11Ev'/>
