<dec f='llvm/clang/include/clang/StaticAnalyzer/Core/PathSensitive/CallEvent.h' l='109' type='const clang::Decl *'/>
<use f='llvm/clang/include/clang/StaticAnalyzer/Core/PathSensitive/CallEvent.h' l='119' u='w' c='_ZN5clang4ento17RuntimeDefinitionC1EPKNS_4DeclE'/>
<use f='llvm/clang/include/clang/StaticAnalyzer/Core/PathSensitive/CallEvent.h' l='120' u='w' c='_ZN5clang4ento17RuntimeDefinitionC1EPKNS_4DeclEPKNS0_9MemRegionE'/>
<use f='llvm/clang/include/clang/StaticAnalyzer/Core/PathSensitive/CallEvent.h' l='122' u='r' c='_ZN5clang4ento17RuntimeDefinition7getDeclEv'/>
<offset>0</offset>
<doc f='llvm/clang/include/clang/StaticAnalyzer/Core/PathSensitive/CallEvent.h' l='107'>/// The Declaration of the function which could be called at runtime.
  /// NULL if not available.</doc>
