<dec f='llvm/build/tools/clang/include/clang/Basic/AttrList.inc' l='78' type='37'/>
<use f='llvm/build/tools/clang/include/clang/AST/Attrs.inc' l='8237' u='r' c='_ZN5clang10PascalAttr7classofEPKNS_4AttrE'/>
<use f='llvm/build/tools/clang/include/clang/AST/AttrVisitor.inc' l='5008' c='_ZN5clang19RecursiveASTVisitor12TraverseAttrEPNS_4AttrE'/>
<use f='llvm/build/tools/clang/include/clang/AST/AttrImpl.inc' l='19504' u='r' c='_ZN5clang10PascalAttrC1ERNS_10ASTContextERKNS_19AttributeCommonInfoE'/>
<use f='llvm/build/tools/clang/include/clang/AST/AttrImpl.inc' l='27798' c='_ZNK5clang4Attr11getSpellingEv'/>
<use f='llvm/build/tools/clang/include/clang/AST/AttrImpl.inc' l='28466' c='_ZNK5clang4Attr5cloneERNS_10ASTContextE'/>
<use f='llvm/build/tools/clang/include/clang/AST/AttrImpl.inc' l='29134' c='_ZNK5clang4Attr11printPrettyERN4llvm11raw_ostreamERKNS_14PrintingPolicyE'/>
<use f='llvm/clang/lib/AST/Type.cpp' l='3555' c='_ZNK5clang14AttributedType13isCallingConvEv'/>
<use f='llvm/clang/lib/AST/TypePrinter.cpp' l='1706' c='_ZN12_GLOBAL__N_111TypePrinter20printAttributedAfterEPKN5clang14AttributedTypeERN4llvm11raw_ostreamE'/>
<use f='llvm/build/tools/clang/include/clang/Sema/AttrTemplateInstantiate.inc' l='1103' c='_ZN5clang4sema28instantiateTemplateAttributeEPKNS_4AttrERNS_10ASTContextERNS_4SemaERKNS_30MultiLevelTemplateArgumentListE'/>
<use f='llvm/build/tools/clang/include/clang/Sema/AttrTemplateInstantiate.inc' l='2283' c='_ZN5clang4sema35instantiateTemplateAttributeForDeclEPKNS_4AttrERNS_10ASTContextERNS_4SemaERKNS_30MultiLevelTemplateArgumentListE'/>
<use f='llvm/build/tools/clang/include/clang/Serialization/AttrPCHRead.inc' l='2534' c='_ZN5clang15ASTRecordReader8readAttrEv'/>
<use f='llvm/build/tools/clang/include/clang/Serialization/AttrPCHWrite.inc' l='1779' c='_ZN5clang15ASTRecordWriter7AddAttrEPKNS_4AttrE'/>
