<dec f='llvm/clang/lib/CodeGen/CodeGenFunction.h' l='3568' type='clang::CodeGen::Address'/>
<use f='llvm/clang/lib/CodeGen/CodeGenFunction.h' l='3591' u='w' c='_ZN5clang7CodeGen15CodeGenFunction16OMPLoopArgumentsC1ENS0_7AddressES3_S3_S3_PN4llvm5ValueEPNS_4ExprES8_S8_S8_S8_S8_'/>
<offset>256</offset>
<doc f='llvm/clang/lib/CodeGen/CodeGenFunction.h' l='3567'>/// loop stride</doc>
<use f='llvm/clang/lib/CodeGen/CGStmtOpenMP.cpp' l='2443' u='r' c='_ZN5clang7CodeGen15CodeGenFunction16EmitOMPOuterLoopEbbRKNS_16OMPLoopDirectiveERNS1_15OMPPrivateScopeERKNS1_16OMPLoopArgumentsERKN4llvm12function_refI6190539'/>
<use f='llvm/clang/lib/CodeGen/CGStmtOpenMP.cpp' l='2605' u='r' c='_ZN5clang7CodeGen15CodeGenFunction19EmitOMPForOuterLoopERKNS_16OpenMPScheduleTyEbRKNS_16OMPLoopDirectiveERNS1_15OMPPrivateScopeEbRKNS1_16OMPLoopArgume11330629'/>
<use f='llvm/clang/lib/CodeGen/CGStmtOpenMP.cpp' l='2619' u='r' c='_ZN5clang7CodeGen15CodeGenFunction19EmitOMPForOuterLoopERKNS_16OpenMPScheduleTyEbRKNS_16OMPLoopDirectiveERNS1_15OMPPrivateScopeEbRKNS1_16OMPLoopArgume11330629'/>
<use f='llvm/clang/lib/CodeGen/CGStmtOpenMP.cpp' l='2651' u='r' c='_ZN5clang7CodeGen15CodeGenFunction26EmitOMPDistributeOuterLoopENS_28OpenMPDistScheduleClauseKindERKNS_16OMPLoopDirectiveERNS1_15OMPPrivateScopeERKNS1_8046876'/>
<use f='llvm/clang/lib/CodeGen/CGStmtOpenMP.cpp' l='2668' u='w' c='_ZN5clang7CodeGen15CodeGenFunction26EmitOMPDistributeOuterLoopENS_28OpenMPDistScheduleClauseKindERKNS_16OMPLoopDirectiveERNS1_15OMPPrivateScopeERKNS1_8046876'/>
<use f='llvm/clang/lib/CodeGen/CGStmtOpenMP.cpp' l='2668' u='r' c='_ZN5clang7CodeGen15CodeGenFunction26EmitOMPDistributeOuterLoopENS_28OpenMPDistScheduleClauseKindERKNS_16OMPLoopDirectiveERNS1_15OMPPrivateScopeERKNS1_8046876'/>
