<dec f='llvm/clang/include/clang/Serialization/ASTReader.h' l='306' type='clang::Preprocessor &amp;'/>
<use f='llvm/clang/include/clang/Serialization/ASTReader.h' l='309' u='w' c='_ZN5clang23SimpleASTReaderListenerC1ERNS_12PreprocessorE'/>
<offset>64</offset>
<use f='llvm/clang/lib/Serialization/ASTReader.cpp' l='769' u='m' c='_ZN5clang23SimpleASTReaderListener23ReadPreprocessorOptionsERKNS_19PreprocessorOptionsEbRNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE'/>
<use f='llvm/clang/lib/Serialization/ASTReader.cpp' l='771' u='m' c='_ZN5clang23SimpleASTReaderListener23ReadPreprocessorOptionsERKNS_19PreprocessorOptionsEbRNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE'/>
<use f='llvm/clang/lib/Serialization/ASTReader.cpp' l='773' u='m' c='_ZN5clang23SimpleASTReaderListener23ReadPreprocessorOptionsERKNS_19PreprocessorOptionsEbRNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE'/>
