<dec f='llvm/clang/include/clang/StaticAnalyzer/Core/PathSensitive/AnalysisManager.h' l='36' type='clang::Preprocessor &amp;'/>
<use f='llvm/clang/include/clang/StaticAnalyzer/Core/PathSensitive/AnalysisManager.h' l='66' u='a' c='_ZN5clang4ento15AnalysisManager15getPreprocessorEv'/>
<offset>1472</offset>
<use f='llvm/clang/lib/StaticAnalyzer/Core/AnalysisManager.cpp' l='41' u='w' c='_ZN5clang4ento15AnalysisManagerC1ERNS_10ASTContextERNS_12PreprocessorERKSt6vectorIPNS0_22PathDiagnosticConsumerESaIS8_EEPFSt10unique_ptrINS0_12StoreMa12873945'/>
