<dec f='llvm/clang/include/clang/Sema/Sema.h' l='5747' type='clang::Sema *'/>
<use f='llvm/clang/include/clang/Sema/Sema.h' l='5765' u='w' c='_ZN5clang4Sema30ImplicitExceptionSpecificationC1ERS0_'/>
<use f='llvm/clang/include/clang/Sema/Sema.h' l='5804' u='r' c='_ZNK5clang4Sema30ImplicitExceptionSpecification16getExceptionSpecEv'/>
<offset>0</offset>
<doc f='llvm/clang/include/clang/Sema/Sema.h' l='5746'>// Pointer to allow copying</doc>
<use f='llvm/clang/lib/Sema/SemaDeclCXX.cpp' l='168' u='r' c='_ZN5clang4Sema30ImplicitExceptionSpecification10CalledDeclENS_14SourceLocationEPKNS_13CXXMethodDeclE'/>
<use f='llvm/clang/lib/Sema/SemaDeclCXX.cpp' l='224' u='r' c='_ZN5clang4Sema30ImplicitExceptionSpecification10CalledDeclENS_14SourceLocationEPKNS_13CXXMethodDeclE'/>
<use f='llvm/clang/lib/Sema/SemaDeclCXX.cpp' l='253' u='r' c='_ZN5clang4Sema30ImplicitExceptionSpecification10CalledStmtEPNS_4StmtE'/>
