<dec f='llvm/clang/include/clang/Sema/Sema.h' l='5450' type='clang::Expr *'/>
<offset>0</offset>
<use f='llvm/clang/lib/Parse/ParseExpr.cpp' l='2557' u='w' c='_ZN5clang6Parser29ParseBuiltinPrimaryExpressionEv'/>
<use f='llvm/clang/lib/Sema/TreeTransform.h' l='10167' u='w' c='_ZN5clang13TreeTransform21TransformOffsetOfExprEPNS_12OffsetOfExprE'/>
<use f='llvm/clang/lib/Sema/SemaExpr.cpp' l='14976' u='r' c='_ZN5clang4Sema20BuildBuiltinOffsetOfENS_14SourceLocationEPNS_14TypeSourceInfoEN4llvm8ArrayRefINS0_17OffsetOfComponentEEES1_'/>
