<dec f='llvm/clang/include/clang/AST/TemplateBase.h' l='140' type='uintptr_t'/>
<use f='llvm/clang/include/clang/AST/TemplateBase.h' l='157' u='w' c='_ZN5clang16TemplateArgumentC1ENS_8QualTypeEb'/>
<use f='llvm/clang/include/clang/AST/TemplateBase.h' l='222' u='w' c='_ZN5clang16TemplateArgumentC1EPNS_4ExprE'/>
<use f='llvm/clang/include/clang/AST/TemplateBase.h' l='271' u='r' c='_ZNK5clang16TemplateArgument9getAsTypeEv'/>
<use f='llvm/clang/include/clang/AST/TemplateBase.h' l='289' u='r' c='_ZNK5clang16TemplateArgument14getNullPtrTypeEv'/>
<use f='llvm/clang/include/clang/AST/TemplateBase.h' l='344' u='r' c='_ZNK5clang16TemplateArgument9getAsExprEv'/>
<offset>64</offset>
<use f='llvm/clang/lib/AST/TemplateBase.cpp' l='293' u='r' c='_ZNK5clang16TemplateArgument18structurallyEqualsERKS0_'/>
<use f='llvm/clang/lib/AST/TemplateBase.cpp' l='293' u='r' c='_ZNK5clang16TemplateArgument18structurallyEqualsERKS0_'/>
