<dec f='llvm/clang/include/clang/Basic/FileManager.h' l='54' type='IntrusiveRefCntPtr&lt;llvm::vfs::FileSystem&gt;'/>
<use f='llvm/clang/include/clang/Basic/FileManager.h' l='243' u='m' c='_ZNK5clang11FileManager20getVirtualFileSystemEv'/>
<use f='llvm/clang/include/clang/Basic/FileManager.h' l='246' u='w' c='_ZN5clang11FileManager20setVirtualFileSystemEN4llvm18IntrusiveRefCntPtrINS1_3vfs10FileSystemEEE'/>
<offset>64</offset>
<use f='llvm/clang/lib/Basic/FileManager.cpp' l='53' u='w' c='_ZN5clang11FileManagerC1ERKNS_17FileSystemOptionsEN4llvm18IntrusiveRefCntPtrINS4_3vfs10FileSystemEEE'/>
<use f='llvm/clang/lib/Basic/FileManager.cpp' l='57' u='m' c='_ZN5clang11FileManagerC1ERKNS_17FileSystemOptionsEN4llvm18IntrusiveRefCntPtrINS4_3vfs10FileSystemEEE'/>
<use f='llvm/clang/lib/Basic/FileManager.cpp' l='58' u='w' c='_ZN5clang11FileManagerC1ERKNS_17FileSystemOptionsEN4llvm18IntrusiveRefCntPtrINS4_3vfs10FileSystemEEE'/>
<use f='llvm/clang/lib/Basic/FileManager.cpp' l='487' u='m' c='_ZNK5clang11FileManager16makeAbsolutePathERN4llvm15SmallVectorImplIcEE'/>
<use f='llvm/clang/lib/Basic/FileManager.cpp' l='537' u='m' c='_ZN5clang11FileManager20getBufferForFileImplEN4llvm9StringRefElbb'/>
<use f='llvm/clang/lib/Basic/FileManager.cpp' l='542' u='m' c='_ZN5clang11FileManager20getBufferForFileImplEN4llvm9StringRefElbb'/>
<use f='llvm/clang/lib/Basic/FileManager.cpp' l='558' u='m' c='_ZN5clang11FileManager12getStatValueEN4llvm9StringRefERNS1_3vfs6StatusEbPSt10unique_ptrINS3_4FileESt14default_deleteIS7_EE'/>
<use f='llvm/clang/lib/Basic/FileManager.cpp' l='564' u='m' c='_ZN5clang11FileManager12getStatValueEN4llvm9StringRefERNS1_3vfs6StatusEbPSt10unique_ptrINS3_4FileESt14default_deleteIS7_EE'/>
<use f='llvm/clang/lib/Basic/FileManager.cpp' l='573' u='m' c='_ZN5clang11FileManager21getNoncachedStatValueEN4llvm9StringRefERNS1_3vfs6StatusE'/>
<use f='llvm/clang/lib/Basic/FileManager.cpp' l='610' u='m' c='_ZN5clang11FileManager16getCanonicalNameEPKNS_14DirectoryEntryE'/>
<use f='llvm/clang/lib/Basic/FileManager.cpp' l='626' u='m' c='_ZN5clang11FileManager16getCanonicalNameEPKNS_9FileEntryE'/>
