<use f='llvm/clang/include/clang/Sema/Sema.h' l='9140' u='w' c='_ZN5clang4Sema28LocalEagerInstantiationScopeC1ERS0_'/>
<use f='llvm/clang/include/clang/Sema/Sema.h' l='9145' u='m' c='_ZN5clang4Sema28LocalEagerInstantiationScope7performEv'/>
<use f='llvm/clang/include/clang/Sema/Sema.h' l='9151' u='m' c='_ZN5clang4Sema28LocalEagerInstantiationScopeD1Ev'/>
<dec f='llvm/clang/include/clang/Sema/Sema.h' l='9155' type='clang::Sema &amp;'/>
<offset>0</offset>
