<dec f='llvm/clang/include/clang/StaticAnalyzer/Core/BugReporter/BugReporterVisitors.h' l='344' type='clang::ento::DefinedSVal'/>
<offset>128</offset>
<doc f='llvm/clang/include/clang/StaticAnalyzer/Core/BugReporter/BugReporterVisitors.h' l='342'>/// The symbolic value for which we are tracking constraints.
  /// This value is constrained to null in the end of path.</doc>
<use f='llvm/clang/lib/StaticAnalyzer/Core/BugReporterVisitors.cpp' l='1603' u='w' c='_ZN5clang4ento36SuppressInlineDefensiveChecksVisitorC1ENS0_11DefinedSValEPKNS0_12ExplodedNodeE'/>
<use f='llvm/clang/lib/StaticAnalyzer/Core/BugReporterVisitors.cpp' l='1614' u='r' c='_ZNK5clang4ento36SuppressInlineDefensiveChecksVisitor7ProfileERN4llvm16FoldingSetNodeIDE'/>
<use f='llvm/clang/lib/StaticAnalyzer/Core/BugReporterVisitors.cpp' l='1631' u='r' c='_ZN5clang4ento36SuppressInlineDefensiveChecksVisitor9VisitNodeEPKNS0_12ExplodedNodeERNS0_18BugReporterContextERNS0_22PathSensitiveBugReportE'/>
<use f='llvm/clang/lib/StaticAnalyzer/Core/BugReporterVisitors.cpp' l='1638' u='r' c='_ZN5clang4ento36SuppressInlineDefensiveChecksVisitor9VisitNodeEPKNS0_12ExplodedNodeERNS0_18BugReporterContextERNS0_22PathSensitiveBugReportE'/>
<use f='llvm/clang/lib/StaticAnalyzer/Core/BugReporterVisitors.cpp' l='1639' u='r' c='_ZN5clang4ento36SuppressInlineDefensiveChecksVisitor9VisitNodeEPKNS0_12ExplodedNodeERNS0_18BugReporterContextERNS0_22PathSensitiveBugReportE'/>
