<use f='llvm/clang/include/clang/Sema/SemaInternal.h' l='100' u='w' c='_ZN5clang22TypoCorrectionConsumerC1ERNS_4SemaERKNS_19DeclarationNameInfoENS1_14LookupNameKindEPNS_5ScopeEPNS_12CXXScopeSpecESt10unique_ptrINS_27Correc6387778'/>
<use f='llvm/clang/include/clang/Sema/SemaInternal.h' l='205' u='m' c='_ZNK5clang22TypoCorrectionConsumer5getSSEv'/>
<dec f='llvm/clang/include/clang/Sema/SemaInternal.h' l='311' type='std::unique_ptr&lt;CXXScopeSpec&gt;'/>
<offset>3712</offset>
<use f='llvm/clang/lib/Sema/SemaLookup.cpp' l='4287' u='m' c='_ZN5clang22TypoCorrectionConsumer13addNamespacesERKN4llvm9MapVectorIPNS_13NamespaceDeclEbNS1_8DenseMapIS4_jNS1_12DenseMapInfoIS4_EENS1_6detail12DenseM14173056'/>
<use f='llvm/clang/lib/Sema/SemaLookup.cpp' l='4287' u='m' c='_ZN5clang22TypoCorrectionConsumer13addNamespacesERKN4llvm9MapVectorIPNS_13NamespaceDeclEbNS1_8DenseMapIS4_jNS1_12DenseMapInfoIS4_EENS1_6detail12DenseM14173056'/>
<use f='llvm/clang/lib/Sema/SemaLookup.cpp' l='4287' u='m' c='_ZN5clang22TypoCorrectionConsumer13addNamespacesERKN4llvm9MapVectorIPNS_13NamespaceDeclEbNS1_8DenseMapIS4_jNS1_12DenseMapInfoIS4_EENS1_6detail12DenseM14173056'/>
<use f='llvm/clang/lib/Sema/SemaLookup.cpp' l='4339' u='m' c='_ZN5clang22TypoCorrectionConsumer17resolveCorrectionERNS_14TypoCorrectionE'/>
<use f='llvm/clang/lib/Sema/SemaLookup.cpp' l='4356' u='m' c='_ZN5clang22TypoCorrectionConsumer17resolveCorrectionERNS_14TypoCorrectionE'/>
<use f='llvm/clang/lib/Sema/SemaLookup.cpp' l='4357' u='m' c='_ZN5clang22TypoCorrectionConsumer17resolveCorrectionERNS_14TypoCorrectionE'/>
<use f='llvm/clang/lib/Sema/SemaLookup.cpp' l='4380' u='m' c='_ZN5clang22TypoCorrectionConsumer17resolveCorrectionERNS_14TypoCorrectionE'/>
<use f='llvm/clang/lib/Sema/SemaLookup.cpp' l='4427' u='m' c='_ZN5clang22TypoCorrectionConsumer23performQualifiedLookupsEv'/>
<use f='llvm/clang/lib/Sema/SemaLookup.cpp' l='4427' u='m' c='_ZN5clang22TypoCorrectionConsumer23performQualifiedLookupsEv'/>
<use f='llvm/clang/lib/Sema/SemaLookup.cpp' l='4431' u='m' c='_ZN5clang22TypoCorrectionConsumer23performQualifiedLookupsEv'/>
<use f='llvm/clang/lib/Sema/SemaLookup.cpp' l='4448' u='m' c='_ZN5clang22TypoCorrectionConsumer23performQualifiedLookupsEv'/>
