<dec f='llvm/clang/include/clang/Sema/Sema.h' l='12852' type='clang::Decl *'/>
<offset>896</offset>
<doc f='llvm/clang/include/clang/Sema/Sema.h' l='12851'>/// The template function declaration to be late parsed.</doc>
<use f='llvm/clang/lib/Parse/ParseTemplate.cpp' l='1628' u='r' c='_ZN5clang6Parser25ParseLateTemplatedFuncDefERNS_18LateParsedTemplateE'/>
<use f='llvm/clang/lib/Parse/ParseTemplate.cpp' l='1635' u='r' c='_ZN5clang6Parser25ParseLateTemplatedFuncDefERNS_18LateParsedTemplateE'/>
<use f='llvm/clang/lib/Parse/ParseTemplate.cpp' l='1684' u='r' c='_ZN5clang6Parser25ParseLateTemplatedFuncDefERNS_18LateParsedTemplateE'/>
<use f='llvm/clang/lib/Parse/ParseTemplate.cpp' l='1687' u='r' c='_ZN5clang6Parser25ParseLateTemplatedFuncDefERNS_18LateParsedTemplateE'/>
<use f='llvm/clang/lib/Parse/ParseTemplate.cpp' l='1689' u='r' c='_ZN5clang6Parser25ParseLateTemplatedFuncDefERNS_18LateParsedTemplateE'/>
<use f='llvm/clang/lib/Parse/ParseTemplate.cpp' l='1698' u='r' c='_ZN5clang6Parser25ParseLateTemplatedFuncDefERNS_18LateParsedTemplateE'/>
<use f='llvm/clang/lib/Parse/ParseTemplate.cpp' l='1701' u='r' c='_ZN5clang6Parser25ParseLateTemplatedFuncDefERNS_18LateParsedTemplateE'/>
<use f='llvm/clang/lib/Sema/SemaTemplate.cpp' l='10918' u='w' c='_ZN5clang4Sema24MarkAsLateParsedTemplateEPNS_12FunctionDeclEPNS_4DeclERN4llvm11SmallVectorINS_5TokenELj4EEE'/>
<use f='llvm/clang/lib/Serialization/ASTReader.cpp' l='8423' u='w' c='_ZN5clang9ASTReader23ReadLateParsedTemplatesERN4llvm9MapVectorIPKNS_12FunctionDeclESt10unique_ptrINS_18LateParsedTemplateESt14default_deleteIS7_EENS1_1319681'/>
<use f='llvm/clang/lib/Serialization/ASTReader.cpp' l='8425' u='r' c='_ZN5clang9ASTReader23ReadLateParsedTemplatesERN4llvm9MapVectorIPKNS_12FunctionDeclESt10unique_ptrINS_18LateParsedTemplateESt14default_deleteIS7_EENS1_1319681'/>
<use f='llvm/clang/lib/Serialization/ASTWriter.cpp' l='4121' u='r' c='_ZN5clang9ASTWriter24WriteLateParsedTemplatesERNS_4SemaE'/>
