<dec f='llvm/clang/include/clang/ASTMatchers/Dynamic/Parser.h' l='248' type='clang::ast_matchers::dynamic::Parser::Sema *const'/>
<use f='llvm/clang/lib/ASTMatchers/Dynamic/Parser.cpp' l='398' u='r' c='_ZN5clang12ast_matchers7dynamic6Parser25parseIdentifierPrefixImplEPNS1_12VariantValueE'/>
<use f='llvm/clang/lib/ASTMatchers/Dynamic/Parser.cpp' l='463' u='r' c='_ZN5clang12ast_matchers7dynamic6Parser26parseMatcherExpressionImplERKNS2_9TokenInfoEPNS1_12VariantValueE'/>
<use f='llvm/clang/lib/ASTMatchers/Dynamic/Parser.cpp' l='531' u='r' c='_ZN5clang12ast_matchers7dynamic6Parser26parseMatcherExpressionImplERKNS2_9TokenInfoEPNS1_12VariantValueE'/>
<use f='llvm/clang/lib/ASTMatchers/Dynamic/Parser.cpp' l='578' u='r' c='_ZN5clang12ast_matchers7dynamic6Parser24addExpressionCompletionsEv'/>
<use f='llvm/clang/lib/ASTMatchers/Dynamic/Parser.cpp' l='579' u='r' c='_ZN5clang12ast_matchers7dynamic6Parser24addExpressionCompletionsEv'/>
<use f='llvm/clang/lib/ASTMatchers/Dynamic/Parser.cpp' l='629' u='w' c='_ZN5clang12ast_matchers7dynamic6ParserC1EPNS2_13CodeTokenizerEPNS2_4SemaEPKN4llvm9StringMapINS1_12VariantValueENS7_15MallocAllocatorEEEPNS1_11DiagnosticsE'/>
<offset>64</offset>
