<use f='llvm/clang/include/clang/Sema/Sema.h' l='1672' u='m' c='_ZN5clanglsERKNS_4Sema21SemaDiagnosticBuilderERKT_'/>
<use f='llvm/clang/include/clang/Sema/Sema.h' l='1686' u='m' c='_ZNK5clang4Sema21SemaDiagnosticBuilderlsEOT_'/>
<use f='llvm/clang/include/clang/Sema/Sema.h' l='1695' u='m' c='_ZN5clanglsERKNS_4Sema21SemaDiagnosticBuilderERKNS_17PartialDiagnosticE'/>
<use f='llvm/clang/include/clang/Sema/Sema.h' l='1703' u='m' c='_ZNK5clang4Sema21SemaDiagnosticBuilder12AddFixItHintERKNS_9FixItHintE'/>
<dec f='llvm/clang/include/clang/Sema/Sema.h' l='1719' type='clang::Sema &amp;'/>
<offset>0</offset>
<use f='llvm/clang/lib/Sema/Sema.cpp' l='1700' u='w' c='_ZN5clang4Sema21SemaDiagnosticBuilderC1ENS1_4KindENS_14SourceLocationEjPNS_12FunctionDeclERS0_'/>
<use f='llvm/clang/lib/Sema/Sema.cpp' l='1720' u='w' c='_ZN5clang4Sema21SemaDiagnosticBuilderC1EOS1_'/>
<use f='llvm/clang/lib/Sema/Sema.cpp' l='1720' u='r' c='_ZN5clang4Sema21SemaDiagnosticBuilderC1EOS1_'/>
<use f='llvm/clang/lib/Sema/Sema.cpp' l='1733' u='m' c='_ZN5clang4Sema21SemaDiagnosticBuilderD1Ev'/>
<use f='llvm/clang/lib/Sema/Sema.cpp' l='1737' u='a' c='_ZN5clang4Sema21SemaDiagnosticBuilderD1Ev'/>
