<dec f='llvm/clang/lib/CodeGen/CodeGenAction.cpp' l='109' type='clang::BackendAction'/>
<use f='llvm/clang/lib/CodeGen/CodeGenAction.cpp' l='145' u='w' c='_ZN5clang15BackendConsumerC1ENS_13BackendActionERNS_17DiagnosticsEngineERKNS_19HeaderSearchOptionsERKNS_19PreprocessorOptionsERKNS_14CodeGenOptionsERK14121951'/>
<use f='llvm/clang/lib/CodeGen/CodeGenAction.cpp' l='169' u='w' c='_ZN5clang15BackendConsumerC1ENS_13BackendActionERNS_17DiagnosticsEngineERKNS_19HeaderSearchOptionsERKNS_19PreprocessorOptionsERKNS_14CodeGenOptionsERK8168210'/>
<use f='llvm/clang/lib/CodeGen/CodeGenAction.cpp' l='346' u='r' c='_ZN5clang15BackendConsumer21HandleTranslationUnitERNS_10ASTContextE'/>
<offset>192</offset>
