<dec f='llvm/clang/include/clang/AST/FormatString.h' l='279' type='clang::analyze_format_string::ArgType::TypeKind'/>
<use f='llvm/clang/include/clang/AST/FormatString.h' l='289' u='r' c='_ZNK5clang21analyze_format_string7ArgType7isSizeTEv'/>
<use f='llvm/clang/include/clang/AST/FormatString.h' l='291' u='r' c='_ZNK5clang21analyze_format_string7ArgType10isPtrdiffTEv'/>
<use f='llvm/clang/include/clang/AST/FormatString.h' l='304' u='w' c='_ZN5clang21analyze_format_string7ArgType9makeSizeTERKS1_'/>
<use f='llvm/clang/include/clang/AST/FormatString.h' l='312' u='w' c='_ZN5clang21analyze_format_string7ArgType12makePtrdiffTERKS1_'/>
<offset>224</offset>
