<dec f='llvm/clang/include/clang/Serialization/ASTWriter.h' l='135' type='clang::Preprocessor *'/>
<offset>384</offset>
<doc f='llvm/clang/include/clang/Serialization/ASTWriter.h' l='134'>/// The preprocessor we&apos;re writing.</doc>
<use f='llvm/clang/lib/Serialization/ASTWriter.cpp' l='1469' u='r' c='_ZN5clang9ASTWriter15WriteInputFilesERNS_13SourceManagerERNS_19HeaderSearchOptionsEb'/>
<use f='llvm/clang/lib/Serialization/ASTWriter.cpp' l='1477' u='r' c='_ZN5clang9ASTWriter15WriteInputFilesERNS_13SourceManagerERNS_19HeaderSearchOptionsEb'/>
<use f='llvm/clang/lib/Serialization/ASTWriter.cpp' l='1780' u='r' c='_ZN5clang9ASTWriter17WriteHeaderSearchERKNS_12HeaderSearchE'/>
<use f='llvm/clang/lib/Serialization/ASTWriter.cpp' l='2680' u='r' c='_ZN5clang9ASTWriter15WriteSubmodulesEPNS_6ModuleE'/>
<use f='llvm/clang/lib/Serialization/ASTWriter.cpp' l='2963' u='r' c='_ZN5clang9ASTWriter13WriteCommentsEv'/>
<use f='llvm/clang/lib/Serialization/ASTWriter.cpp' l='4384' u='w' c='_ZN5clang9ASTWriter8WriteASTERNS_4SemaERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEPNS_6ModuleEN4llvm9StringRefEbb'/>
<use f='llvm/clang/lib/Serialization/ASTWriter.cpp' l='4389' u='w' c='_ZN5clang9ASTWriter8WriteASTERNS_4SemaERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEPNS_6ModuleEN4llvm9StringRefEbb'/>
