<dec f='llvm/clang/include/clang/AST/ExternalASTSource.h' l='521' type='LazyVector&lt;T, Source, Loader, LoadedStorage, LocalStorage&gt; *'/>
<use f='llvm/clang/include/clang/AST/ExternalASTSource.h' l='524' u='w' c='_ZN5clang10LazyVector8iteratorC1EPNS_10LazyVectorIT_T0_XT1_EXT2_EXT3_EEEi'/>
<use f='llvm/clang/include/clang/AST/ExternalASTSource.h' l='533' u='c' c='_ZNK5clang10LazyVector8iteratordeEv'/>
<use f='llvm/clang/include/clang/AST/ExternalASTSource.h' l='534' u='c' c='_ZNK5clang10LazyVector8iteratordeEv'/>
