<dec f='llvm/clang/lib/Lex/ModuleMap.cpp' l='1362' type='20'/>
<use f='llvm/clang/lib/Lex/ModuleMap.cpp' l='1569' u='r' c='_ZN5clang15ModuleMapParser12consumeTokenEv'/>
<use f='llvm/clang/lib/Lex/ModuleMap.cpp' l='1864' u='r' c='_ZN5clang15ModuleMapParser15parseModuleDeclEv'/>
<use f='llvm/clang/lib/Lex/ModuleMap.cpp' l='2504' u='r' c='_ZN5clang15ModuleMapParser15parseExportDeclEv'/>
<use f='llvm/clang/lib/Lex/ModuleMap.cpp' l='2834' u='r' c='_ZN5clang15ModuleMapParser23parseInferredModuleDeclEbb'/>
<use f='llvm/clang/lib/Lex/ModuleMap.cpp' l='2973' c='_ZN5clang15ModuleMapParser18parseModuleMapFileEv'/>
