<dec f='llvm/clang/include/clang/AST/Expr.h' l='2482' type='clang::Stmt *'/>
<use f='llvm/clang/include/clang/AST/Expr.h' l='2530' u='r' c='_ZN5clang24UnaryExprOrTypeTraitExpr15getArgumentExprEv'/>
<use f='llvm/clang/include/clang/AST/Expr.h' l='2537' u='w' c='_ZN5clang24UnaryExprOrTypeTraitExpr11setArgumentEPNS_4ExprE'/>
<offset>0</offset>
<use f='llvm/clang/lib/AST/Expr.cpp' l='1487' u='w' c='_ZN5clang24UnaryExprOrTypeTraitExprC1ENS_20UnaryExprOrTypeTraitEPNS_4ExprENS_8QualTypeENS_14SourceLocationES5_'/>
<use f='llvm/clang/lib/AST/Expr.cpp' l='4525' u='a' c='_ZNK5clang24UnaryExprOrTypeTraitExpr8childrenEv'/>
<use f='llvm/clang/lib/AST/Expr.cpp' l='4525' u='a' c='_ZNK5clang24UnaryExprOrTypeTraitExpr8childrenEv'/>
