<dec f='llvm/clang/lib/Sema/UsedDeclVisitor.h' l='23' type='clang::Sema &amp;'/>
<use f='llvm/clang/lib/Sema/UsedDeclVisitor.h' l='28' u='w' c='_ZN5clang15UsedDeclVisitorC1ERNS_4SemaE'/>
<use f='llvm/clang/lib/Sema/UsedDeclVisitor.h' l='72' u='m' c='_ZN5clang15UsedDeclVisitor18VisitCXXDeleteExprEPNS_13CXXDeleteExprE'/>
<use f='llvm/clang/lib/Sema/UsedDeclVisitor.h' l='75' u='m' c='_ZN5clang15UsedDeclVisitor18VisitCXXDeleteExprEPNS_13CXXDeleteExprE'/>
