<dec f='llvm/clang/include/clang/StaticAnalyzer/Core/PathSensitive/ExprEngine.h' l='150' type='clang::ento::ExplodedGraph &amp;'/>
<use f='llvm/clang/include/clang/StaticAnalyzer/Core/PathSensitive/ExprEngine.h' l='261' u='a' c='_ZN5clang4ento10ExprEngine8getGraphEv'/>
<use f='llvm/clang/include/clang/StaticAnalyzer/Core/PathSensitive/ExprEngine.h' l='262' u='a' c='_ZNK5clang4ento10ExprEngine8getGraphEv'/>
<offset>2176</offset>
<doc f='llvm/clang/include/clang/StaticAnalyzer/Core/PathSensitive/ExprEngine.h' l='149'>/// G - the simulation graph.</doc>
<use f='llvm/clang/lib/StaticAnalyzer/Core/ExprEngine.cpp' l='209' u='w' c='_ZN5clang4ento10ExprEngineC1ERNS_8cross_tu27CrossTranslationUnitContextERNS0_15AnalysisManagerEPN4llvm8DenseSetIPKNS_4DeclENS7_12DenseMapInfoISB_EEEEP14498536'/>
<use f='llvm/clang/lib/StaticAnalyzer/Core/ExprEngine.cpp' l='211' u='m' c='_ZN5clang4ento10ExprEngineC1ERNS_8cross_tu27CrossTranslationUnitContextERNS0_15AnalysisManagerEPN4llvm8DenseSetIPKNS_4DeclENS7_12DenseMapInfoISB_EEEEP14498536'/>
<use f='llvm/clang/lib/StaticAnalyzer/Core/ExprEngine.cpp' l='224' u='m' c='_ZN5clang4ento10ExprEngineC1ERNS_8cross_tu27CrossTranslationUnitContextERNS0_15AnalysisManagerEPN4llvm8DenseSetIPKNS_4DeclENS7_12DenseMapInfoISB_EEEEP14498536'/>
<use f='llvm/clang/lib/StaticAnalyzer/Core/ExprEngine.cpp' l='624' u='a' c='_ZN5clang4ento10ExprEngine18processEndWorklistEv'/>
<use f='llvm/clang/lib/StaticAnalyzer/Core/ExprEngine.cpp' l='771' u='m' c='_ZN5clang4ento10ExprEngine11ProcessStmtEPKNS_4StmtEPNS0_12ExplodedNodeE'/>
<use f='llvm/clang/lib/StaticAnalyzer/Core/ExprEngine.cpp' l='1938' u='m' c='_ZN5clang4ento10ExprEngine21replayWithoutInliningEPNS0_12ExplodedNodeEPKNS_15LocationContextE'/>
<use f='llvm/clang/lib/StaticAnalyzer/Core/ExprEngine.cpp' l='1944' u='a' c='_ZN5clang4ento10ExprEngine21replayWithoutInliningEPNS0_12ExplodedNodeEPKNS_15LocationContextE'/>
<use f='llvm/clang/lib/StaticAnalyzer/Core/ExprEngine.cpp' l='2006' u='m' c='_ZN5clang4ento10ExprEngine23processCFGBlockEntranceERKNS_9BlockEdgeERNS0_20NodeBuilderWithSinksEPNS0_12ExplodedNodeE'/>
<use f='llvm/clang/lib/StaticAnalyzer/Core/ExprEngineCallAndReturn.cpp' l='64' u='m' c='_ZN5clang4ento10ExprEngine16processCallEnterERNS0_18NodeBuilderContextENS_9CallEnterEPNS0_12ExplodedNodeE'/>
<use f='llvm/clang/lib/StaticAnalyzer/Core/ExprEngineCallAndReturn.cpp' l='65' u='a' c='_ZN5clang4ento10ExprEngine16processCallEnterERNS0_18NodeBuilderContextENS_9CallEnterEPNS0_12ExplodedNodeE'/>
<use f='llvm/clang/lib/StaticAnalyzer/Core/ExprEngineCallAndReturn.cpp' l='285' u='m' c='_ZN5clang4ento10ExprEngine15processCallExitEPNS0_12ExplodedNodeE'/>
<use f='llvm/clang/lib/StaticAnalyzer/Core/ExprEngineCallAndReturn.cpp' l='286' u='a' c='_ZN5clang4ento10ExprEngine15processCallExitEPNS0_12ExplodedNodeE'/>
<use f='llvm/clang/lib/StaticAnalyzer/Core/ExprEngineCallAndReturn.cpp' l='313' u='m' c='_ZN5clang4ento10ExprEngine15processCallExitEPNS0_12ExplodedNodeE'/>
<use f='llvm/clang/lib/StaticAnalyzer/Core/ExprEngineCallAndReturn.cpp' l='314' u='a' c='_ZN5clang4ento10ExprEngine15processCallExitEPNS0_12ExplodedNodeE'/>
<use f='llvm/clang/lib/StaticAnalyzer/Core/ExprEngineCallAndReturn.cpp' l='464' u='m' c='_ZN5clang4ento10ExprEngine10inlineCallERKNS0_9CallEventEPKNS_4DeclERNS0_11NodeBuilderEPNS0_12ExplodedNodeEN4llvm18IntrusiveRefCntPtrIKNS0_12ProgramStateEEE'/>
<use f='llvm/clang/lib/StaticAnalyzer/Core/ExprEngineCallAndReturn.cpp' l='465' u='a' c='_ZN5clang4ento10ExprEngine10inlineCallERKNS0_9CallEventEPKNS_4DeclERNS0_11NodeBuilderEPNS0_12ExplodedNodeEN4llvm18IntrusiveRefCntPtrIKNS0_12ProgramStateEEE'/>
