<dec f='llvm/build/tools/clang/include/clang/AST/Attrs.inc' l='8065' type='clang::IdentifierInfo *'/>
<use f='llvm/build/tools/clang/include/clang/AST/Attrs.inc' l='8115' u='r' c='_ZNK5clang13OwnershipAttr9getModuleEv'/>
<offset>320</offset>
<use f='llvm/build/tools/clang/include/clang/AST/AttrImpl.inc' l='19129' u='w' c='_ZN5clang13OwnershipAttrC1ERNS_10ASTContextERKNS_19AttributeCommonInfoEPNS_14IdentifierInfoEPNS_8ParamIdxEj'/>
<use f='llvm/build/tools/clang/include/clang/AST/AttrImpl.inc' l='19139' u='w' c='_ZN5clang13OwnershipAttrC1ERNS_10ASTContextERKNS_19AttributeCommonInfoEPNS_14IdentifierInfoE'/>
<use f='llvm/build/tools/clang/include/clang/AST/AttrImpl.inc' l='19163' u='r' c='_ZNK5clang13OwnershipAttr5cloneERNS_10ASTContextE'/>
