<dec f='llvm/clang/lib/Driver/ToolChains/ROCm.h' l='88' type='SmallString&lt;0&gt;'/>
<use f='llvm/clang/lib/Driver/ToolChains/ROCm.h' l='99' u='m' c='_ZNK5clang6driver24RocmInstallationDetector19allGenericLibsValidEv'/>
<use f='llvm/clang/lib/Driver/ToolChains/ROCm.h' l='161' u='m' c='_ZNK5clang6driver24RocmInstallationDetector13getOpenCLPathEv'/>
<offset>3008</offset>
<doc f='llvm/clang/lib/Driver/ToolChains/ROCm.h' l='87'>// Libraries that are always linked depending on the language</doc>
<use f='llvm/clang/lib/Driver/ToolChains/AMDGPU.cpp' l='50' u='w' c='_ZN5clang6driver24RocmInstallationDetector17scanLibDevicePathEN4llvm9StringRefE'/>
