<dec f='llvm/clang/include/clang/Parse/Parser.h' l='1265' type='clang::Parser *'/>
<offset>64</offset>
<use f='llvm/clang/lib/Parse/ParseCXXInlineMethods.cpp' l='229' u='w' c='_ZN5clang6Parser15LateParsedClassC1EPS0_PNS0_12ParsingClassE'/>
<use f='llvm/clang/lib/Parse/ParseCXXInlineMethods.cpp' l='232' u='r' c='_ZN5clang6Parser15LateParsedClassD1Ev'/>
<use f='llvm/clang/lib/Parse/ParseCXXInlineMethods.cpp' l='236' u='r' c='_ZN5clang6Parser15LateParsedClass28ParseLexedMethodDeclarationsEv'/>
<use f='llvm/clang/lib/Parse/ParseCXXInlineMethods.cpp' l='240' u='r' c='_ZN5clang6Parser15LateParsedClass28ParseLexedMemberInitializersEv'/>
<use f='llvm/clang/lib/Parse/ParseCXXInlineMethods.cpp' l='244' u='r' c='_ZN5clang6Parser15LateParsedClass20ParseLexedMethodDefsEv'/>
<use f='llvm/clang/lib/Parse/ParseCXXInlineMethods.cpp' l='248' u='r' c='_ZN5clang6Parser15LateParsedClass20ParseLexedAttributesEv'/>
<use f='llvm/clang/lib/Parse/ParseCXXInlineMethods.cpp' l='252' u='r' c='_ZN5clang6Parser15LateParsedClass17ParseLexedPragmasEv'/>
