<def f='llvm/clang/include/clang/Lex/PPConditionalDirectiveRecord.h' l='41' ll='55'/>
<size>8</size>
<mbr r='clang::PPConditionalDirectiveRecord::CondDirectiveLoc::Comp::SM' o='0' t='clang::SourceManager &amp;'/>
<fun r='_ZN5clang28PPConditionalDirectiveRecord16CondDirectiveLoc4CompC1ERNS_13SourceManagerE'/>
<fun r='_ZN5clang28PPConditionalDirectiveRecord16CondDirectiveLoc4CompclERKS1_S4_'/>
<fun r='_ZN5clang28PPConditionalDirectiveRecord16CondDirectiveLoc4CompclERKS1_NS_14SourceLocationE'/>
<fun r='_ZN5clang28PPConditionalDirectiveRecord16CondDirectiveLoc4CompclENS_14SourceLocationERKS1_'/>
<use f='llvm/clang/lib/Lex/PPConditionalDirectiveRecord.cpp' l='29' c='_ZNK5clang28PPConditionalDirectiveRecord35rangeIntersectsConditionalDirectiveENS_11SourceRangeE'/>
<use f='llvm/clang/lib/Lex/PPConditionalDirectiveRecord.cpp' l='38' c='_ZNK5clang28PPConditionalDirectiveRecord35rangeIntersectsConditionalDirectiveENS_11SourceRangeE'/>
<use f='llvm/clang/lib/Lex/PPConditionalDirectiveRecord.cpp' l='58' c='_ZNK5clang28PPConditionalDirectiveRecord33findConditionalDirectiveRegionLocENS_14SourceLocationE'/>
<size>8</size>
