<dec f='llvm/clang/include/clang/Parse/Parser.h' l='1691' type='clang::Decl *'/>
<use f='llvm/clang/include/clang/Parse/Parser.h' l='1697' u='w' c='_ZN5clang6Parser23ObjCImplParsingDataRAIIC1ERS0_PNS_4DeclE'/>
<offset>64</offset>
<use f='llvm/clang/lib/Parse/ParseExpr.cpp' l='2191' u='r' c='_ZN5clang6Parser28ParsePostfixExpressionSuffixENS_12ActionResultIPNS_4ExprELb1EEE'/>
<use f='llvm/clang/lib/Parse/ParseObjc.cpp' l='2246' u='r' c='_ZN5clang6Parser23ObjCImplParsingDataRAIID1Ev'/>
<use f='llvm/clang/lib/Parse/ParseObjc.cpp' l='2256' u='r' c='_ZN5clang6Parser23ObjCImplParsingDataRAII6finishENS_11SourceRangeE'/>
