<def f='llvm/clang/include/clang/Serialization/ContinuousRangeMap.h' l='111' ll='137'/>
<use f='llvm/clang/include/clang/Serialization/ContinuousRangeMap.h' l='116' c='_ZN5clang18ContinuousRangeMap7BuilderC1ERKS1_'/>
<use f='llvm/clang/include/clang/Serialization/ContinuousRangeMap.h' l='117' c='_ZN5clang18ContinuousRangeMap7BuilderaSERKS1_'/>
<use f='llvm/clang/include/clang/Serialization/ContinuousRangeMap.h' l='117' c='_ZN5clang18ContinuousRangeMap7BuilderaSERKS1_'/>
<use f='llvm/clang/include/clang/Serialization/ContinuousRangeMap.h' l='139'/>
<doc f='llvm/clang/include/clang/Serialization/ContinuousRangeMap.h' l='109'>/// An object that helps properly build a continuous range map
  /// from a set of values.</doc>
<mbr r='clang::ContinuousRangeMap::Builder::Self' t='ContinuousRangeMap&lt;Int, V, InitialCapacity&gt; &amp;'/>
<fun r='_ZN5clang18ContinuousRangeMap7BuilderC1ERNS_18ContinuousRangeMapIT_T0_XT1_EEE'/>
<fun r='_ZN5clang18ContinuousRangeMap7BuilderC1ERKS1_'/>
<fun r='_ZN5clang18ContinuousRangeMap7BuilderaSERKS1_'/>
<fun r='_ZN5clang18ContinuousRangeMap7BuilderD1Ev'/>
<fun r='_ZN5clang18ContinuousRangeMap7Builder6insertERKSt4pairIT_T0_E'/>
<use f='llvm/clang/lib/Serialization/ASTReader.cpp' l='3840' c='_ZNK5clang9ASTReader19ReadModuleOffsetMapERNS_13serialization10ModuleFileE'/>
<size>8</size>
