<dec f='llvm/clang/include/clang/Sema/DeclSpec.h' l='1553' type='clang::DeclaratorChunk::BlockPointerTypeInfo'/>
<use f='llvm/clang/include/clang/Sema/DeclSpec.h' l='1562' u='m' c='_ZN5clang15DeclaratorChunk7destroyEv'/>
<use f='llvm/clang/include/clang/Sema/DeclSpec.h' l='1656' u='m' c='_ZN5clang15DeclaratorChunk15getBlockPointerEjNS_14SourceLocationE'/>
<use f='llvm/clang/include/clang/Sema/DeclSpec.h' l='1666' u='m' c='_ZN5clang15DeclaratorChunk7getPipeEjNS_14SourceLocationE'/>
<offset>0</offset>
<use f='llvm/clang/lib/Sema/SemaType.cpp' l='4766' u='m' c='_ZL24GetFullTypeForDeclaratorRN12_GLOBAL__N_119TypeProcessingStateEN5clang8QualTypeEPNS2_14TypeSourceInfoE'/>
<use f='llvm/clang/lib/Sema/SemaType.cpp' l='4770' u='m' c='_ZL24GetFullTypeForDeclaratorRN12_GLOBAL__N_119TypeProcessingStateEN5clang8QualTypeEPNS2_14TypeSourceInfoE'/>
<use f='llvm/clang/lib/Sema/SemaType.cpp' l='4771' u='m' c='_ZL24GetFullTypeForDeclaratorRN12_GLOBAL__N_119TypeProcessingStateEN5clang8QualTypeEPNS2_14TypeSourceInfoE'/>
