<dec f='llvm/clang/include/clang/StaticAnalyzer/Core/PathSensitive/MemRegion.h' l='861' type='const clang::CompoundLiteralExpr *'/>
<use f='llvm/clang/include/clang/StaticAnalyzer/Core/PathSensitive/MemRegion.h' l='865' u='w' c='_ZN5clang4ento21CompoundLiteralRegionC1EPKNS_19CompoundLiteralExprEPKNS0_14MemSpaceRegionE'/>
<use f='llvm/clang/include/clang/StaticAnalyzer/Core/PathSensitive/MemRegion.h' l='876' u='r' c='_ZNK5clang4ento21CompoundLiteralRegion12getValueTypeEv'/>
<use f='llvm/clang/include/clang/StaticAnalyzer/Core/PathSensitive/MemRegion.h' l='878' u='r' c='_ZNK5clang4ento21CompoundLiteralRegion11isBoundableEv'/>
<use f='llvm/clang/include/clang/StaticAnalyzer/Core/PathSensitive/MemRegion.h' l='884' u='r' c='_ZNK5clang4ento21CompoundLiteralRegion14getLiteralExprEv'/>
<offset>448</offset>
<use f='llvm/clang/lib/StaticAnalyzer/Core/MemRegion.cpp' l='254' u='r' c='_ZNK5clang4ento21CompoundLiteralRegion7ProfileERN4llvm16FoldingSetNodeIDE'/>
<use f='llvm/clang/lib/StaticAnalyzer/Core/MemRegion.cpp' l='477' u='r' c='_ZNK5clang4ento21CompoundLiteralRegion12dumpToStreamERN4llvm11raw_ostreamE'/>
