<dec f='llvm/clang/lib/Sema/Sema.cpp' l='99' type='clang::Sema *'/>
<use f='llvm/clang/lib/Sema/Sema.cpp' l='103' u='w' c='_ZN5clang4sema15SemaPPCallbacks3setERNS_4SemaE'/>
<use f='llvm/clang/lib/Sema/Sema.cpp' l='105' u='w' c='_ZN5clang4sema15SemaPPCallbacks5resetEv'/>
<use f='llvm/clang/lib/Sema/Sema.cpp' l='110' u='r' c='_ZN5clang4sema15SemaPPCallbacks11FileChangedENS_14SourceLocationENS_11PPCallbacks16FileChangeReasonENS_6SrcMgr18CharacteristicKindENS_6FileIDE'/>
<use f='llvm/clang/lib/Sema/Sema.cpp' l='114' u='r' c='_ZN5clang4sema15SemaPPCallbacks11FileChangedENS_14SourceLocationENS_11PPCallbacks16FileChangeReasonENS_6SrcMgr18CharacteristicKindENS_6FileIDE'/>
<use f='llvm/clang/lib/Sema/Sema.cpp' l='124' u='r' c='_ZN5clang4sema15SemaPPCallbacks11FileChangedENS_14SourceLocationENS_11PPCallbacks16FileChangeReasonENS_6SrcMgr18CharacteristicKindENS_6FileIDE'/>
<use f='llvm/clang/lib/Sema/Sema.cpp' l='135' u='r' c='_ZN5clang4sema15SemaPPCallbacks11FileChangedENS_14SourceLocationENS_11PPCallbacks16FileChangeReasonENS_6SrcMgr18CharacteristicKindENS_6FileIDE'/>
<offset>64</offset>
