<dec f='llvm/clang/include/clang/StaticAnalyzer/Core/PathSensitive/SymbolManager.h' l='79' type='clang::QualType'/>
<use f='llvm/clang/include/clang/StaticAnalyzer/Core/PathSensitive/SymbolManager.h' l='87' u='w' c='_ZN5clang4ento14SymbolConjuredC1EjPKNS_4StmtEPKNS_15LocationContextENS_8QualTypeEjPKv'/>
<use f='llvm/clang/include/clang/StaticAnalyzer/Core/PathSensitive/SymbolManager.h' l='120' u='r' c='_ZN5clang4ento14SymbolConjured7ProfileERN4llvm16FoldingSetNodeIDE'/>
<offset>320</offset>
<use f='llvm/clang/lib/StaticAnalyzer/Core/SymbolManager.cpp' l='74' u='m' c='_ZNK5clang4ento14SymbolConjured12dumpToStreamERN4llvm11raw_ostreamE'/>
<use f='llvm/clang/lib/StaticAnalyzer/Core/SymbolManager.cpp' l='313' u='r' c='_ZNK5clang4ento14SymbolConjured7getTypeEv'/>
