<dec f='llvm/clang/include/clang/AST/Expr.h' l='4445' type='1'/>
<use f='llvm/clang/include/clang/AST/Expr.h' l='4456' u='w' c='_ZN5clang10ChooseExprC1ENS_14SourceLocationEPNS_4ExprES3_S3_NS_8QualTypeENS_13ExprValueKindENS_14ExprObjectKindES1_b'/>
<use f='llvm/clang/include/clang/AST/Expr.h' l='4486' u='r' c='_ZNK5clang10ChooseExpr6getLHSEv'/>
<use f='llvm/clang/include/clang/AST/Expr.h' l='4487' u='w' c='_ZN5clang10ChooseExpr6setLHSEPNS_4ExprE'/>
