<dec f='llvm/clang/include/clang/Sema/Sema.h' l='1026' type='clang::Sema &amp;'/>
<use f='llvm/clang/include/clang/Sema/Sema.h' l='1032' u='w' c='_ZN5clang4Sema24SynthesizedFunctionScopeC1ERS0_PNS_11DeclContextE'/>
<use f='llvm/clang/include/clang/Sema/Sema.h' l='1048' u='m' c='_ZN5clang4Sema24SynthesizedFunctionScope14addContextNoteENS_14SourceLocationE'/>
<use f='llvm/clang/include/clang/Sema/Sema.h' l='1049' u='m' c='_ZN5clang4Sema24SynthesizedFunctionScope14addContextNoteENS_14SourceLocationE'/>
<use f='llvm/clang/include/clang/Sema/Sema.h' l='1056' u='m' c='_ZN5clang4Sema24SynthesizedFunctionScopeD1Ev'/>
<use f='llvm/clang/include/clang/Sema/Sema.h' l='1057' u='m' c='_ZN5clang4Sema24SynthesizedFunctionScopeD1Ev'/>
<use f='llvm/clang/include/clang/Sema/Sema.h' l='1059' u='m' c='_ZN5clang4Sema24SynthesizedFunctionScopeD1Ev'/>
<use f='llvm/clang/include/clang/Sema/Sema.h' l='1060' u='m' c='_ZN5clang4Sema24SynthesizedFunctionScopeD1Ev'/>
<offset>0</offset>
