<dec f='llvm/clang/include/clang/Parse/Parser.h' l='1281' type='SmallVector&lt;clang::Decl *, 2&gt;'/>
<use f='llvm/clang/include/clang/Parse/Parser.h' l='1289' u='m' c='_ZN5clang6Parser19LateParsedAttribute7addDeclEPNS_4DeclE'/>
<offset>1216</offset>
<use f='llvm/clang/lib/Parse/ParseCXXInlineMethods.cpp' l='710' u='m' c='_ZN5clang6Parser19ParseLexedAttributeERNS0_19LateParsedAttributeEbb'/>
<use f='llvm/clang/lib/Parse/ParseCXXInlineMethods.cpp' l='711' u='m' c='_ZN5clang6Parser19ParseLexedAttributeERNS0_19LateParsedAttributeEbb'/>
<use f='llvm/clang/lib/Parse/ParseCXXInlineMethods.cpp' l='719' u='m' c='_ZN5clang6Parser19ParseLexedAttributeERNS0_19LateParsedAttributeEbb'/>
<use f='llvm/clang/lib/Parse/ParseCXXInlineMethods.cpp' l='753' u='m' c='_ZN5clang6Parser19ParseLexedAttributeERNS0_19LateParsedAttributeEbb'/>
<use f='llvm/clang/lib/Parse/ParseCXXInlineMethods.cpp' l='754' u='m' c='_ZN5clang6Parser19ParseLexedAttributeERNS0_19LateParsedAttributeEbb'/>
