<use f='llvm/clang/include/clang/Sema/Sema.h' l='4535' u='w' c='_ZN5clang4Sema11FullExprArgC1Ev'/>
<use f='llvm/clang/include/clang/Sema/Sema.h' l='4536' u='w' c='_ZN5clang4Sema11FullExprArgC1ERS0_'/>
<use f='llvm/clang/include/clang/Sema/Sema.h' l='4539' u='r' c='_ZN5clang4Sema11FullExprArg7releaseEv'/>
<use f='llvm/clang/include/clang/Sema/Sema.h' l='4542' u='r' c='_ZNK5clang4Sema11FullExprArg3getEv'/>
<use f='llvm/clang/include/clang/Sema/Sema.h' l='4545' u='r' c='_ZN5clang4Sema11FullExprArgptEv'/>
<use f='llvm/clang/include/clang/Sema/Sema.h' l='4553' u='w' c='_ZN5clang4Sema11FullExprArgC1EPNS_4ExprE'/>
<dec f='llvm/clang/include/clang/Sema/Sema.h' l='4555' type='clang::Expr *'/>
<offset>0</offset>
