<dec f='llvm/clang/lib/CodeGen/CGOpenMPRuntime.h' l='283' type='clang::CodeGen::CGOpenMPRuntime::LastprivateConditionalRAII::ActionToDo'/>
<offset>64</offset>
<use f='llvm/clang/lib/CodeGen/CGOpenMPRuntime.cpp' l='12052' u='w' c='_ZN5clang7CodeGen15CGOpenMPRuntime26LastprivateConditionalRAIIC1ERNS0_15CodeGenFunctionERKNS_22OMPExecutableDirectiveENS0_6LValueE'/>
<use f='llvm/clang/lib/CodeGen/CGOpenMPRuntime.cpp' l='12061' u='r' c='_ZN5clang7CodeGen15CGOpenMPRuntime26LastprivateConditionalRAIIC1ERNS0_15CodeGenFunctionERKNS_22OMPExecutableDirectiveENS0_6LValueE'/>
<use f='llvm/clang/lib/CodeGen/CGOpenMPRuntime.cpp' l='12083' u='w' c='_ZN5clang7CodeGen15CGOpenMPRuntime26LastprivateConditionalRAIIC1ERNS0_15CodeGenFunctionERKNS_22OMPExecutableDirectiveE'/>
<use f='llvm/clang/lib/CodeGen/CGOpenMPRuntime.cpp' l='12090' u='w' c='_ZN5clang7CodeGen15CGOpenMPRuntime26LastprivateConditionalRAIIC1ERNS0_15CodeGenFunctionERKNS_22OMPExecutableDirectiveE'/>
<use f='llvm/clang/lib/CodeGen/CGOpenMPRuntime.cpp' l='12109' u='r' c='_ZN5clang7CodeGen15CGOpenMPRuntime26LastprivateConditionalRAIID1Ev'/>
<use f='llvm/clang/lib/CodeGen/CGOpenMPRuntime.cpp' l='12114' u='r' c='_ZN5clang7CodeGen15CGOpenMPRuntime26LastprivateConditionalRAIID1Ev'/>
