<use f='llvm/clang/include/clang/ASTMatchers/ASTMatchersInternal.h' l='1480' u='w' c='_ZN5clang12ast_matchers8internal16TraversalWrapperC1ENS_13TraversalKindERKT_'/>
<use f='llvm/clang/include/clang/ASTMatchers/ASTMatchersInternal.h' l='1484' u='r' c='_ZNK5clang12ast_matchers8internal16TraversalWrappercvNS1_7MatcherITL0__EEEv'/>
<dec f='llvm/clang/include/clang/ASTMatchers/ASTMatchersInternal.h' l='1490' type='clang::TraversalKind'/>
