<dec f='llvm/clang/include/clang/Sema/DeclSpec.h' l='1807' type='clang::CXXScopeSpec'/>
<use f='llvm/clang/include/clang/Sema/DeclSpec.h' l='1925' u='a' c='_ZNK5clang10Declarator15getCXXScopeSpecEv'/>
<use f='llvm/clang/include/clang/Sema/DeclSpec.h' l='1926' u='a' c='_ZN5clang10Declarator15getCXXScopeSpecEv'/>
<use f='llvm/clang/include/clang/Sema/DeclSpec.h' l='1974' u='m' c='_ZN5clang10Declarator5clearEv'/>
<offset>64</offset>
