<dec f='llvm/clang/lib/StaticAnalyzer/Checkers/Taint.h' l='91' type='const clang::ento::SVal'/>
<use f='llvm/clang/lib/StaticAnalyzer/Checkers/Taint.h' l='94' u='w' c='_ZN5clang4ento5taint15TaintBugVisitorC1ENS0_4SValE'/>
<use f='llvm/clang/lib/StaticAnalyzer/Checkers/Taint.h' l='95' u='r' c='_ZNK5clang4ento5taint15TaintBugVisitor7ProfileERN4llvm16FoldingSetNodeIDE'/>
<offset>128</offset>
<use f='llvm/clang/lib/StaticAnalyzer/Checkers/Taint.cpp' l='237' u='r' c='_ZN5clang4ento5taint15TaintBugVisitor9VisitNodeEPKNS0_12ExplodedNodeERNS0_18BugReporterContextERNS0_22PathSensitiveBugReportE'/>
<use f='llvm/clang/lib/StaticAnalyzer/Checkers/Taint.cpp' l='238' u='r' c='_ZN5clang4ento5taint15TaintBugVisitor9VisitNodeEPKNS0_12ExplodedNodeERNS0_18BugReporterContextERNS0_22PathSensitiveBugReportE'/>
