<dec f='llvm/clang/lib/StaticAnalyzer/Checkers/RetainCountChecker/RetainCountChecker.h' l='87' type='clang::QualType'/>
<use f='llvm/clang/lib/StaticAnalyzer/Checkers/RetainCountChecker/RetainCountChecker.h' l='112' u='w' c='_ZN5clang4ento18retaincountchecker6RefValC1ENS2_4KindENS0_7ObjKindEjjNS_8QualTypeENS2_17IvarAccessHistoryE'/>
<use f='llvm/clang/lib/StaticAnalyzer/Checkers/RetainCountChecker/RetainCountChecker.h' l='141' u='r' c='_ZNK5clang4ento18retaincountchecker6RefVal7getTypeEv'/>
<use f='llvm/clang/lib/StaticAnalyzer/Checkers/RetainCountChecker/RetainCountChecker.h' l='223' u='r' c='_ZNK5clang4ento18retaincountchecker6RefValeqERKS2_'/>
<use f='llvm/clang/lib/StaticAnalyzer/Checkers/RetainCountChecker/RetainCountChecker.h' l='223' u='r' c='_ZNK5clang4ento18retaincountchecker6RefValeqERKS2_'/>
<use f='llvm/clang/lib/StaticAnalyzer/Checkers/RetainCountChecker/RetainCountChecker.h' l='227' u='r' c='_ZNK5clang4ento18retaincountchecker6RefVal7ProfileERN4llvm16FoldingSetNodeIDE'/>
<use f='llvm/clang/lib/StaticAnalyzer/Checkers/RetainCountChecker/RetainCountChecker.cpp' l='47' u='m' c='_ZNK5clang4ento18retaincountchecker6RefVal5printERN4llvm11raw_ostreamE'/>
<use f='llvm/clang/lib/StaticAnalyzer/Checkers/RetainCountChecker/RetainCountChecker.cpp' l='48' u='m' c='_ZNK5clang4ento18retaincountchecker6RefVal5printERN4llvm11raw_ostreamE'/>
<offset>64</offset>
<doc f='llvm/clang/lib/StaticAnalyzer/Checkers/RetainCountChecker/RetainCountChecker.h' l='86'>/// The (static) type of the object at the time we started tracking it.</doc>
