<dec f='llvm/clang/include/clang/Analysis/CloneDetection.h' l='37' type='const clang::Stmt *'/>
<use f='llvm/clang/include/clang/Analysis/CloneDetection.h' l='101' u='r' c='_ZNK5clang12StmtSequence4sizeEv'/>
<use f='llvm/clang/include/clang/Analysis/CloneDetection.h' l='136' u='r' c='_ZNK5clang12StmtSequenceeqERKS0_'/>
<use f='llvm/clang/include/clang/Analysis/CloneDetection.h' l='137' u='r' c='_ZNK5clang12StmtSequenceeqERKS0_'/>
<use f='llvm/clang/include/clang/Analysis/CloneDetection.h' l='141' u='r' c='_ZNK5clang12StmtSequenceneERKS0_'/>
<use f='llvm/clang/include/clang/Analysis/CloneDetection.h' l='142' u='r' c='_ZNK5clang12StmtSequenceneERKS0_'/>
<use f='llvm/clang/lib/Analysis/CloneDetection.cpp' l='25' u='w' c='_ZN5clang12StmtSequenceC1EPKNS_12CompoundStmtEPKNS_4DeclEjj'/>
<use f='llvm/clang/lib/Analysis/CloneDetection.cpp' l='32' u='w' c='_ZN5clang12StmtSequenceC1EPKNS_4StmtEPKNS_4DeclE'/>
<use f='llvm/clang/lib/Analysis/CloneDetection.cpp' l='35' u='w' c='_ZN5clang12StmtSequenceC1Ev'/>
<use f='llvm/clang/lib/Analysis/CloneDetection.cpp' l='61' u='a' c='_ZNK5clang12StmtSequence5beginEv'/>
<use f='llvm/clang/lib/Analysis/CloneDetection.cpp' l='63' u='r' c='_ZNK5clang12StmtSequence5beginEv'/>
<use f='llvm/clang/lib/Analysis/CloneDetection.cpp' l='69' u='a' c='_ZNK5clang12StmtSequence3endEv'/>
<use f='llvm/clang/lib/Analysis/CloneDetection.cpp' l='71' u='r' c='_ZNK5clang12StmtSequence3endEv'/>
<offset>0</offset>
<doc f='llvm/clang/include/clang/Analysis/CloneDetection.h' l='34'>/// If this object identifies a sequence of statements inside a CompoundStmt,
  /// S points to this CompoundStmt. If this object only identifies a single
  /// Stmt, then S is a pointer to this Stmt.</doc>
