<dec f='llvm/clang/include/clang/Parse/Parser.h' l='2848' type='clang::CXXScopeSpec &amp;'/>
<use f='llvm/clang/include/clang/Parse/Parser.h' l='2853' u='w' c='_ZN5clang6Parser18DeclaratorScopeObjC1ERS0_RNS_12CXXScopeSpecE'/>
<use f='llvm/clang/include/clang/Parse/Parser.h' l='2862' u='a' c='_ZN5clang6Parser18DeclaratorScopeObj20EnterDeclaratorScopeEv'/>
<use f='llvm/clang/include/clang/Parse/Parser.h' l='2869' u='r' c='_ZN5clang6Parser18DeclaratorScopeObjD1Ev'/>
<offset>64</offset>
