<dec f='llvm/clang/lib/AST/Mangle.cpp' l='376' type='llvm::DataLayout'/>
<use f='llvm/clang/lib/AST/Mangle.cpp' l='380' u='w' c='_ZN5clang16ASTNameGenerator14ImplementationC1ERNS_10ASTContextE'/>
<use f='llvm/clang/lib/AST/Mangle.cpp' l='406' u='r' c='_ZN5clang16ASTNameGenerator14Implementation9writeNameEPKNS_4DeclERN4llvm11raw_ostreamE'/>
<use f='llvm/clang/lib/AST/Mangle.cpp' l='444' u='r' c='_ZN5clang16ASTNameGenerator14Implementation15getAllManglingsB5cxx11EPKNS_17ObjCContainerDeclE'/>
<use f='llvm/clang/lib/AST/Mangle.cpp' l='546' u='r' c='_ZN5clang16ASTNameGenerator14Implementation18getMangledStructorB5cxx11EPKNS_9NamedDeclEj'/>
<use f='llvm/clang/lib/AST/Mangle.cpp' l='560' u='r' c='_ZN5clang16ASTNameGenerator14Implementation15getMangledThunkB5cxx11EPKNS_13CXXMethodDeclERKNS_9ThunkInfoE'/>
<offset>64</offset>
