<dec f='llvm/clang/include/clang/AST/CXXInheritance.h' l='81' type='DeclContext::lookup_result'/>
<offset>960</offset>
<doc f='llvm/clang/include/clang/AST/CXXInheritance.h' l='79'>/// The set of declarations found inside this base class
  /// subobject.</doc>
<use f='llvm/clang/lib/AST/CXXInheritance.cpp' l='389' u='w' c='_ZL18findOrdinaryMemberPKN5clang13CXXRecordDeclERNS_11CXXBasePathENS_15DeclarationNameE'/>
<use f='llvm/clang/lib/AST/CXXInheritance.cpp' l='390' c='_ZL18findOrdinaryMemberPKN5clang13CXXRecordDeclERNS_11CXXBasePathENS_15DeclarationNameE'/>
<use f='llvm/clang/lib/AST/CXXInheritance.cpp' l='456' c='_ZN5clang13CXXRecordDecl19lookupDependentNameENS_15DeclarationNameEN4llvm12function_refIFbPKNS_9NamedDeclEEEE'/>
<use f='llvm/clang/lib/Sema/SemaDeclCXX.cpp' l='9663' u='w' c='_ZN12_GLOBAL__N_123FindHiddenVirtualMethodclEPKN5clang16CXXBaseSpecifierERNS1_11CXXBasePathE'/>
<use f='llvm/clang/lib/Sema/SemaDeclCXX.cpp' l='9663' u='m' c='_ZN12_GLOBAL__N_123FindHiddenVirtualMethodclEPKN5clang16CXXBaseSpecifierERNS1_11CXXBasePathE'/>
<use f='llvm/clang/lib/Sema/SemaDeclCXX.cpp' l='9664' u='w' c='_ZN12_GLOBAL__N_123FindHiddenVirtualMethodclEPKN5clang16CXXBaseSpecifierERNS1_11CXXBasePathE'/>
<use f='llvm/clang/lib/Sema/SemaDeclCXX.cpp' l='9664' u='m' c='_ZN12_GLOBAL__N_123FindHiddenVirtualMethodclEPKN5clang16CXXBaseSpecifierERNS1_11CXXBasePathE'/>
<use f='llvm/clang/lib/Sema/SemaDeclCXX.cpp' l='9665' u='m' c='_ZN12_GLOBAL__N_123FindHiddenVirtualMethodclEPKN5clang16CXXBaseSpecifierERNS1_11CXXBasePathE'/>
<use f='llvm/clang/lib/Sema/SemaLookup.cpp' l='641' u='m' c='_ZN5clang12LookupResult21addDeclsFromBasePathsERKNS_12CXXBasePathsE'/>
<use f='llvm/clang/lib/Sema/SemaLookup.cpp' l='642' u='m' c='_ZN5clang12LookupResult21addDeclsFromBasePathsERKNS_12CXXBasePathsE'/>
<use f='llvm/clang/lib/Sema/SemaLookup.cpp' l='2194' u='w' c='_ZN5clang4Sema19LookupQualifiedNameERNS_12LookupResultEPNS_11DeclContextEb'/>
<use f='llvm/clang/lib/Sema/SemaLookup.cpp' l='2194' u='m' c='_ZN5clang4Sema19LookupQualifiedNameERNS_12LookupResultEPNS_11DeclContextEb'/>
<use f='llvm/clang/lib/Sema/SemaLookup.cpp' l='2195' u='w' c='_ZN5clang4Sema19LookupQualifiedNameERNS_12LookupResultEPNS_11DeclContextEb'/>
<use f='llvm/clang/lib/Sema/SemaLookup.cpp' l='2195' u='m' c='_ZN5clang4Sema19LookupQualifiedNameERNS_12LookupResultEPNS_11DeclContextEb'/>
<use f='llvm/clang/lib/Sema/SemaLookup.cpp' l='2196' u='m' c='_ZN5clang4Sema19LookupQualifiedNameERNS_12LookupResultEPNS_11DeclContextEb'/>
<use f='llvm/clang/lib/Sema/SemaLookup.cpp' l='2322' u='r' c='_ZN5clang4Sema19LookupQualifiedNameERNS_12LookupResultEPNS_11DeclContextEb'/>
<use f='llvm/clang/lib/Sema/SemaLookup.cpp' l='2323' u='r' c='_ZN5clang4Sema19LookupQualifiedNameERNS_12LookupResultEPNS_11DeclContextEb'/>
<use f='llvm/clang/lib/Sema/SemaLookup.cpp' l='2323' u='r' c='_ZN5clang4Sema19LookupQualifiedNameERNS_12LookupResultEPNS_11DeclContextEb'/>
<use f='llvm/clang/lib/Sema/SemaLookup.cpp' l='2340' u='r' c='_ZN5clang4Sema19LookupQualifiedNameERNS_12LookupResultEPNS_11DeclContextEb'/>
<use f='llvm/clang/lib/Sema/SemaLookup.cpp' l='2352' c='_ZN5clang4Sema19LookupQualifiedNameERNS_12LookupResultEPNS_11DeclContextEb'/>
<use f='llvm/clang/lib/Sema/SemaLookup.cpp' l='2498' u='m' c='_ZN5clang4Sema23DiagnoseAmbiguousLookupERNS_12LookupResultE'/>
<use f='llvm/clang/lib/Sema/SemaLookup.cpp' l='2516' u='m' c='_ZN5clang4Sema23DiagnoseAmbiguousLookupERNS_12LookupResultE'/>
<use f='llvm/lldb/source/Plugins/TypeSystem/Clang/TypeSystemClang.cpp' l='166' u='w' c='_ZN12_GLOBAL__N_121addOverridesForMethodEPN5clang13CXXMethodDeclE'/>
<use f='llvm/lldb/source/Plugins/TypeSystem/Clang/TypeSystemClang.cpp' l='174' u='w' c='_ZN12_GLOBAL__N_121addOverridesForMethodEPN5clang13CXXMethodDeclE'/>
<use f='llvm/lldb/source/Plugins/TypeSystem/Clang/TypeSystemClang.cpp' l='174' u='m' c='_ZN12_GLOBAL__N_121addOverridesForMethodEPN5clang13CXXMethodDeclE'/>
<use f='llvm/lldb/source/Plugins/TypeSystem/Clang/TypeSystemClang.cpp' l='175' u='w' c='_ZN12_GLOBAL__N_121addOverridesForMethodEPN5clang13CXXMethodDeclE'/>
<use f='llvm/lldb/source/Plugins/TypeSystem/Clang/TypeSystemClang.cpp' l='175' u='m' c='_ZN12_GLOBAL__N_121addOverridesForMethodEPN5clang13CXXMethodDeclE'/>
<use f='llvm/lldb/source/Plugins/TypeSystem/Clang/TypeSystemClang.cpp' l='177' u='m' c='_ZN12_GLOBAL__N_121addOverridesForMethodEPN5clang13CXXMethodDeclE'/>
<use f='llvm/lldb/source/Plugins/TypeSystem/Clang/TypeSystemClang.cpp' l='179' u='w' c='_ZN12_GLOBAL__N_121addOverridesForMethodEPN5clang13CXXMethodDeclE'/>
<use f='llvm/lldb/source/Plugins/TypeSystem/Clang/TypeSystemClang.cpp' l='6539' u='w' c='_ZN12lldb_private15TypeSystemClang29GetIndexOfChildMemberWithNameEPvPKcbRSt6vectorIjSaIjEE'/>
<use f='llvm/lldb/source/Plugins/TypeSystem/Clang/TypeSystemClang.cpp' l='6542' u='m' c='_ZN12lldb_private15TypeSystemClang29GetIndexOfChildMemberWithNameEPvPKcbRSt6vectorIjSaIjEE'/>
<use f='llvm/lldb/source/Plugins/TypeSystem/Clang/TypeSystemClang.cpp' l='6565' c='_ZN12lldb_private15TypeSystemClang29GetIndexOfChildMemberWithNameEPvPKcbRSt6vectorIjSaIjEE'/>
