<use f='llvm/clang/include/clang/Lex/Preprocessor.h' l='310' u='w' c='_ZN5clang12Preprocessor9ImportSeqC1ENS1_5StateE'/>
<use f='llvm/clang/include/clang/Lex/Preprocessor.h' l='314' u='w' c='_ZN5clang12Preprocessor9ImportSeq17handleOpenBracketEv'/>
<use f='llvm/clang/include/clang/Lex/Preprocessor.h' l='314' u='r' c='_ZN5clang12Preprocessor9ImportSeq17handleOpenBracketEv'/>
<use f='llvm/clang/include/clang/Lex/Preprocessor.h' l='318' u='w' c='_ZN5clang12Preprocessor9ImportSeq18handleCloseBracketEv'/>
<use f='llvm/clang/include/clang/Lex/Preprocessor.h' l='318' u='r' c='_ZN5clang12Preprocessor9ImportSeq18handleCloseBracketEv'/>
<use f='llvm/clang/include/clang/Lex/Preprocessor.h' l='323' u='r' c='_ZN5clang12Preprocessor9ImportSeq16handleCloseBraceEv'/>
<use f='llvm/clang/include/clang/Lex/Preprocessor.h' l='324' u='w' c='_ZN5clang12Preprocessor9ImportSeq16handleCloseBraceEv'/>
<use f='llvm/clang/include/clang/Lex/Preprocessor.h' l='329' u='w' c='_ZN5clang12Preprocessor9ImportSeq10handleSemiEv'/>
<use f='llvm/clang/include/clang/Lex/Preprocessor.h' l='336' u='r' c='_ZN5clang12Preprocessor9ImportSeq12handleExportEv'/>
<use f='llvm/clang/include/clang/Lex/Preprocessor.h' l='337' u='w' c='_ZN5clang12Preprocessor9ImportSeq12handleExportEv'/>
<use f='llvm/clang/include/clang/Lex/Preprocessor.h' l='338' u='r' c='_ZN5clang12Preprocessor9ImportSeq12handleExportEv'/>
<use f='llvm/clang/include/clang/Lex/Preprocessor.h' l='339' u='w' c='_ZN5clang12Preprocessor9ImportSeq12handleExportEv'/>
<use f='llvm/clang/include/clang/Lex/Preprocessor.h' l='343' u='r' c='_ZN5clang12Preprocessor9ImportSeq12handleImportEv'/>
<use f='llvm/clang/include/clang/Lex/Preprocessor.h' l='343' u='r' c='_ZN5clang12Preprocessor9ImportSeq12handleImportEv'/>
<use f='llvm/clang/include/clang/Lex/Preprocessor.h' l='344' u='w' c='_ZN5clang12Preprocessor9ImportSeq12handleImportEv'/>
<use f='llvm/clang/include/clang/Lex/Preprocessor.h' l='345' u='r' c='_ZN5clang12Preprocessor9ImportSeq12handleImportEv'/>
<use f='llvm/clang/include/clang/Lex/Preprocessor.h' l='346' u='w' c='_ZN5clang12Preprocessor9ImportSeq12handleImportEv'/>
<use f='llvm/clang/include/clang/Lex/Preprocessor.h' l='352' u='r' c='_ZN5clang12Preprocessor9ImportSeq16handleHeaderNameEv'/>
<use f='llvm/clang/include/clang/Lex/Preprocessor.h' l='359' u='r' c='_ZN5clang12Preprocessor9ImportSeq10handleMiscEv'/>
<use f='llvm/clang/include/clang/Lex/Preprocessor.h' l='360' u='w' c='_ZN5clang12Preprocessor9ImportSeq10handleMiscEv'/>
<use f='llvm/clang/include/clang/Lex/Preprocessor.h' l='363' u='r' c='_ZN5clang12Preprocessor9ImportSeq10atTopLevelEv'/>
<use f='llvm/clang/include/clang/Lex/Preprocessor.h' l='364' u='r' c='_ZN5clang12Preprocessor9ImportSeq14afterImportSeqEv'/>
<dec f='llvm/clang/include/clang/Lex/Preprocessor.h' l='367' type='clang::Preprocessor::ImportSeq::State'/>
<offset>0</offset>
