<dec f='llvm/clang/include/clang/Parse/Parser.h' l='1328' type='clang::Decl *'/>
<use f='llvm/clang/include/clang/Parse/Parser.h' l='1331' u='w' c='_ZN5clang6Parser11LexedMethodC1EPS0_PNS_4DeclE'/>
<offset>128</offset>
<use f='llvm/clang/lib/Parse/ParseCXXInlineMethods.cpp' l='518' u='r' c='_ZN5clang6Parser19ParseLexedMethodDefERNS0_11LexedMethodE'/>
<use f='llvm/clang/lib/Parse/ParseCXXInlineMethods.cpp' l='528' u='r' c='_ZN5clang6Parser19ParseLexedMethodDefERNS0_11LexedMethodE'/>
<use f='llvm/clang/lib/Parse/ParseCXXInlineMethods.cpp' l='544' u='r' c='_ZN5clang6Parser19ParseLexedMethodDefERNS0_11LexedMethodE'/>
<use f='llvm/clang/lib/Parse/ParseCXXInlineMethods.cpp' l='547' u='r' c='_ZN5clang6Parser19ParseLexedMethodDefERNS0_11LexedMethodE'/>
<use f='llvm/clang/lib/Parse/ParseCXXInlineMethods.cpp' l='552' u='r' c='_ZN5clang6Parser19ParseLexedMethodDefERNS0_11LexedMethodE'/>
<use f='llvm/clang/lib/Parse/ParseCXXInlineMethods.cpp' l='557' u='r' c='_ZN5clang6Parser19ParseLexedMethodDefERNS0_11LexedMethodE'/>
<use f='llvm/clang/lib/Parse/ParseCXXInlineMethods.cpp' l='562' u='r' c='_ZN5clang6Parser19ParseLexedMethodDefERNS0_11LexedMethodE'/>
<use f='llvm/clang/lib/Parse/ParseCXXInlineMethods.cpp' l='567' u='r' c='_ZN5clang6Parser19ParseLexedMethodDefERNS0_11LexedMethodE'/>
<use f='llvm/clang/lib/Parse/ParseCXXInlineMethods.cpp' l='572' u='r' c='_ZN5clang6Parser19ParseLexedMethodDefERNS0_11LexedMethodE'/>
<use f='llvm/clang/lib/Parse/ParseCXXInlineMethods.cpp' l='581' u='r' c='_ZN5clang6Parser19ParseLexedMethodDefERNS0_11LexedMethodE'/>
<use f='llvm/clang/lib/Parse/ParseCXXInlineMethods.cpp' l='586' u='r' c='_ZN5clang6Parser19ParseLexedMethodDefERNS0_11LexedMethodE'/>
<use f='llvm/clang/lib/Parse/ParseCXXInlineMethods.cpp' l='589' u='r' c='_ZN5clang6Parser19ParseLexedMethodDefERNS0_11LexedMethodE'/>
<use f='llvm/clang/lib/Parse/ParseObjc.cpp' l='3635' u='r' c='_ZN5clang6Parser24ParseLexedObjCMethodDefsERNS0_11LexedMethodEb'/>
