<use f='llvm/clang/include/clang/Lex/LiteralSupport.h' l='233' u='w' c='_ZN5clang19StringLiteralParserC1EN4llvm8ArrayRefINS_5TokenEEERKNS_13SourceManagerERKNS_11LangOptionsERKNS_10TargetInfoEPNS_17DiagnosticsEngineE'/>
<dec f='llvm/clang/include/clang/Lex/LiteralSupport.h' l='239' type='bool'/>
<use f='llvm/clang/include/clang/Lex/LiteralSupport.h' l='262' u='r' c='_ZNK5clang19StringLiteralParser8isPascalEv'/>
<offset>5256</offset>
<use f='llvm/clang/lib/Lex/LiteralSupport.cpp' l='1480' u='w' c='_ZN5clang19StringLiteralParserC1EN4llvm8ArrayRefINS_5TokenEEERNS_12PreprocessorEb'/>
<use f='llvm/clang/lib/Lex/LiteralSupport.cpp' l='1556' u='w' c='_ZN5clang19StringLiteralParser4initEN4llvm8ArrayRefINS_5TokenEEE'/>
<use f='llvm/clang/lib/Lex/LiteralSupport.cpp' l='1675' u='w' c='_ZN5clang19StringLiteralParser4initEN4llvm8ArrayRefINS_5TokenEEE'/>
<use f='llvm/clang/lib/Lex/LiteralSupport.cpp' l='1676' u='r' c='_ZN5clang19StringLiteralParser4initEN4llvm8ArrayRefINS_5TokenEEE'/>
<use f='llvm/clang/lib/Lex/LiteralSupport.cpp' l='1728' u='r' c='_ZN5clang19StringLiteralParser4initEN4llvm8ArrayRefINS_5TokenEEE'/>
<use f='llvm/clang/lib/Lex/PPDirectives.cpp' l='1200' u='r' c='_ZN5clang12Preprocessor19HandleLineDirectiveEv'/>
<use f='llvm/clang/lib/Lex/PPDirectives.cpp' l='1350' u='r' c='_ZN5clang12Preprocessor20HandleDigitDirectiveERNS_5TokenE'/>
<use f='llvm/clang/lib/Lex/Preprocessor.cpp' l='1352' u='r' c='_ZN5clang12Preprocessor22FinishLexStringLiteralERNS_5TokenERNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEPKcb'/>
<use f='llvm/clang/lib/Parse/ParseExprCXX.cpp' l='2672' u='r' c='_ZN5clang6Parser26ParseUnqualifiedIdOperatorERNS_12CXXScopeSpecEbNS_9OpaquePtrINS_8QualTypeEEERNS_13UnqualifiedIdE'/>
<use f='llvm/clang/lib/Sema/SemaExpr.cpp' l='1853' u='r' c='_ZN5clang4Sema18ActOnStringLiteralEN4llvm8ArrayRefINS_5TokenEEEPNS_5ScopeE'/>
