<dec f='llvm/clang/include/clang/StaticAnalyzer/Core/PathSensitive/BasicValueFactory.h' l='43' type='llvm::ImmutableList&lt;SVal&gt;'/>
<use f='llvm/clang/include/clang/StaticAnalyzer/Core/PathSensitive/BasicValueFactory.h' l='46' u='w' c='_ZN5clang4ento15CompoundValDataC1ENS_8QualTypeEN4llvm13ImmutableListINS0_4SValEEE'/>
<use f='llvm/clang/include/clang/StaticAnalyzer/Core/PathSensitive/BasicValueFactory.h' l='52' u='m' c='_ZNK5clang4ento15CompoundValData5beginEv'/>
<use f='llvm/clang/include/clang/StaticAnalyzer/Core/PathSensitive/BasicValueFactory.h' l='53' u='m' c='_ZNK5clang4ento15CompoundValData3endEv'/>
<use f='llvm/clang/include/clang/StaticAnalyzer/Core/PathSensitive/BasicValueFactory.h' l='58' u='r' c='_ZN5clang4ento15CompoundValData7ProfileERN4llvm16FoldingSetNodeIDE'/>
<offset>128</offset>
