<dec f='llvm/clang/include/clang/StaticAnalyzer/Core/PathSensitive/SymbolManager.h' l='315' type='clang::QualType'/>
<use f='llvm/clang/include/clang/StaticAnalyzer/Core/PathSensitive/SymbolManager.h' l='319' u='w' c='_ZN5clang4ento13BinarySymExprC1ENS0_7SymExpr4KindENS_18BinaryOperatorKindENS_8QualTypeE'/>
<use f='llvm/clang/include/clang/StaticAnalyzer/Core/PathSensitive/SymbolManager.h' l='330' u='r' c='_ZNK5clang4ento13BinarySymExpr7getTypeEv'/>
<offset>256</offset>
