<use f='llvm/clang/lib/AST/Interp/InterpState.h' l='85' u='r' c='_ZNK5clang6interp11InterpState9getSourceEPNS0_8FunctionENS0_7CodePtrE'/>
<use f='llvm/clang/lib/AST/Interp/InterpState.h' l='85' u='r' c='_ZNK5clang6interp11InterpState9getSourceEPNS0_8FunctionENS0_7CodePtrE'/>
<dec f='llvm/clang/lib/AST/Interp/InterpState.h' l='94' type='clang::interp::SourceMapper *'/>
<offset>256</offset>
<doc f='llvm/clang/lib/AST/Interp/InterpState.h' l='93'>/// Reference to the offset-source mapping.</doc>
<use f='llvm/clang/lib/AST/Interp/InterpState.cpp' l='26' u='w' c='_ZN5clang6interp11InterpStateC1ERNS0_5StateERNS0_7ProgramERNS0_11InterpStackERNS0_7ContextEPNS0_12SourceMapperE'/>
