<dec f='llvm/clang/include/clang/Analysis/RetainSummaryManager.h' l='50' type='4'/>
<doc f='llvm/clang/include/clang/Analysis/RetainSummaryManager.h' l='48'>/// Indicates that the tracking object is a descendant of a
  /// referenced-counted OSObject, used in the Darwin kernel.</doc>
<use f='llvm/clang/lib/Analysis/RetainSummaryManager.cpp' l='95' u='r' c='_ZN5clang4ento20RetainSummaryManager19hasAnyEnabledAttrOfEPKNS_4DeclENS_8QualTypeE'/>
<use f='llvm/clang/lib/Analysis/RetainSummaryManager.cpp' l='646' u='r' c='_ZN5clang4ento20RetainSummaryManager29updateSummaryForArgumentTypesERKNS_7AnyCallERPKNS0_13RetainSummaryE'/>
<use f='llvm/clang/lib/Analysis/RetainSummaryManager.cpp' l='809' u='r' c='_ZN5clang4ento20RetainSummaryManager22getOSSummaryRetainRuleEPKNS_12FunctionDeclE'/>
<use f='llvm/clang/lib/Analysis/RetainSummaryManager.cpp' l='818' u='r' c='_ZN5clang4ento20RetainSummaryManager23getOSSummaryReleaseRuleEPKNS_12FunctionDeclE'/>
<use f='llvm/clang/lib/Analysis/RetainSummaryManager.cpp' l='827' u='r' c='_ZN5clang4ento20RetainSummaryManager20getOSSummaryFreeRuleEPKNS_12FunctionDeclE'/>
<use f='llvm/clang/lib/Analysis/RetainSummaryManager.cpp' l='832' u='r' c='_ZN5clang4ento20RetainSummaryManager22getOSSummaryCreateRuleEPKNS_12FunctionDeclE'/>
<use f='llvm/clang/lib/Analysis/RetainSummaryManager.cpp' l='838' u='r' c='_ZN5clang4ento20RetainSummaryManager19getOSSummaryGetRuleEPKNS_12FunctionDeclE'/>
<use f='llvm/clang/lib/Analysis/RetainSummaryManager.cpp' l='925' u='r' c='_ZN5clang4ento20RetainSummaryManager26applyParamAnnotationEffectEPKNS_11ParmVarDeclEjPKNS_9NamedDeclERNS0_21RetainSummaryTemplateE'/>
<use f='llvm/clang/lib/Analysis/RetainSummaryManager.cpp' l='945' u='r' c='_ZN5clang4ento20RetainSummaryManager26applyParamAnnotationEffectEPKNS_11ParmVarDeclEjPKNS_9NamedDeclERNS0_21RetainSummaryTemplateE'/>
<use f='llvm/clang/lib/Analysis/RetainSummaryManager.cpp' l='992' u='r' c='_ZN5clang4ento20RetainSummaryManager28updateSummaryFromAnnotationsERPKNS0_13RetainSummaryEPKNS_12FunctionDeclE'/>
<use f='llvm/clang/lib/StaticAnalyzer/Checkers/RetainCountChecker/RetainCountChecker.cpp' l='438' u='r' c='_ZL28shouldEscapeOSArgumentOnCallRKN5clang4ento9CallEventEjPKNS0_18retaincountchecker6RefValE'/>
<use f='llvm/clang/lib/StaticAnalyzer/Checkers/RetainCountChecker/RetainCountChecker.cpp' l='574' u='r' c='_ZL19updateOutParametersN4llvm18IntrusiveRefCntPtrIKN5clang4ento12ProgramStateEEERKNS2_13RetainSummaryERKNS2_9CallEventE'/>
<use f='llvm/clang/lib/StaticAnalyzer/Checkers/RetainCountChecker/RetainCountChecker.cpp' l='627' u='r' c='_ZNK5clang4ento18retaincountchecker18RetainCountChecker12checkSummaryERKNS0_13RetainSummaryERKNS0_9CallEventERNS0_14CheckerContextE'/>
<use f='llvm/clang/lib/StaticAnalyzer/Checkers/RetainCountChecker/RetainCountChecker.cpp' l='1355' u='r' c='_ZNK5clang4ento18retaincountchecker18RetainCountChecker18checkBeginFunctionERNS0_14CheckerContextE'/>
<use f='llvm/clang/lib/StaticAnalyzer/Checkers/RetainCountChecker/RetainCountDiagnostics.cpp' l='267' u='r' c='_ZL30generateDiagnosticsForCallLikeN4llvm18IntrusiveRefCntPtrIKN5clang4ento12ProgramStateEEEPKNS1_15LocationContextERKNS2_18retaincountchecker6RefValE11512542'/>
<use f='llvm/clang/lib/StaticAnalyzer/Checkers/RetainCountChecker/RetainCountDiagnostics.cpp' l='795' u='r' c='_ZN5clang4ento18retaincountchecker20RefLeakReportVisitor10getEndPathERNS0_18BugReporterContextEPKNS0_12ExplodedNodeERNS0_22PathSensitiveBugReportE'/>
