<use f='llvm/clang/lib/AST/Interp/InterpBlock.h' l='118' u='m' c='_ZN5clang6interp9DeadBlock4dataEv'/>
<dec f='llvm/clang/lib/AST/Interp/InterpBlock.h' l='134' type='clang::interp::Block'/>
<offset>192</offset>
<doc f='llvm/clang/lib/AST/Interp/InterpBlock.h' l='133'>/// Actual block storing data and tracking pointers.</doc>
<use f='llvm/clang/lib/AST/Interp/InterpBlock.cpp' l='64' u='w' c='_ZN5clang6interp9DeadBlockC1ERPS1_PNS0_5BlockE'/>
<use f='llvm/clang/lib/AST/Interp/InterpBlock.cpp' l='74' u='m' c='_ZN5clang6interp9DeadBlockC1ERPS1_PNS0_5BlockE'/>
<use f='llvm/clang/lib/AST/Interp/InterpBlock.cpp' l='76' u='a' c='_ZN5clang6interp9DeadBlockC1ERPS1_PNS0_5BlockE'/>
