<dec f='llvm/clang/include/clang/AST/Expr.h' l='1223' type='clang::ValueDecl *'/>
<use f='llvm/clang/include/clang/AST/Expr.h' l='1285' u='r' c='_ZN5clang11DeclRefExpr7getDeclEv'/>
<use f='llvm/clang/include/clang/AST/Expr.h' l='1286' u='r' c='_ZNK5clang11DeclRefExpr7getDeclEv'/>
<use f='llvm/clang/include/clang/AST/Expr.h' l='1323' u='r' c='_ZN5clang11DeclRefExpr12getFoundDeclEv'/>
<use f='llvm/clang/include/clang/AST/Expr.h' l='1329' u='r' c='_ZNK5clang11DeclRefExpr12getFoundDeclEv'/>
<offset>128</offset>
<doc f='llvm/clang/include/clang/AST/Expr.h' l='1222'>/// The declaration that we are referencing.</doc>
<use f='llvm/clang/lib/AST/Expr.cpp' l='385' u='w' c='_ZN5clang11DeclRefExprC1ERKNS_10ASTContextEPNS_9ValueDeclEbNS_8QualTypeENS_13ExprValueKindENS_14SourceLocationERKNS_18DeclarationNameLocENS_15NonOdrUseReasonE'/>
<use f='llvm/clang/lib/AST/Expr.cpp' l='404' u='w' c='_ZN5clang11DeclRefExprC1ERKNS_10ASTContextENS_22NestedNameSpecifierLocENS_14SourceLocationEPNS_9ValueDeclEbRKNS_19DeclarationNameInfoEPNS_9NamedDeclEP6599683'/>
<use f='llvm/clang/lib/AST/Expr.cpp' l='491' u='w' c='_ZN5clang11DeclRefExpr7setDeclEPNS_9ValueDeclE'/>
<use f='llvm/clang/lib/Serialization/ASTReaderStmt.cpp' l='617' u='w' c='_ZN5clang13ASTStmtReader16VisitDeclRefExprEPNS_11DeclRefExprE'/>
