<dec f='llvm/clang/include/clang/Analysis/ConstructionContext.h' l='370' type='const clang::CXXCtorInitializer *'/>
<use f='llvm/clang/include/clang/Analysis/ConstructionContext.h' l='375' u='w' c='_ZN5clang41ConstructorInitializerConstructionContextC1ENS_19ConstructionContext4KindEPKNS_18CXXCtorInitializerE'/>
<use f='llvm/clang/include/clang/Analysis/ConstructionContext.h' l='381' u='r' c='_ZNK5clang41ConstructorInitializerConstructionContext21getCXXCtorInitializerEv'/>
<offset>64</offset>
