<use f='llvm/clang/lib/Parse/ParseCXXInlineMethods.cpp' l='1113' u='w' c='_ZN5clang6Parser33UnannotatedTentativeParsingActionC1ERS0_NS_3tok9TokenKindE'/>
<use f='llvm/clang/lib/Parse/ParseCXXInlineMethods.cpp' l='1125' u='m' c='_ZN5clang6Parser33UnannotatedTentativeParsingAction17RevertAnnotationsEv'/>
<use f='llvm/clang/lib/Parse/ParseCXXInlineMethods.cpp' l='1129' u='m' c='_ZN5clang6Parser33UnannotatedTentativeParsingAction17RevertAnnotationsEv'/>
<use f='llvm/clang/lib/Parse/ParseCXXInlineMethods.cpp' l='1130' u='m' c='_ZN5clang6Parser33UnannotatedTentativeParsingAction17RevertAnnotationsEv'/>
<use f='llvm/clang/lib/Parse/ParseCXXInlineMethods.cpp' l='1133' u='m' c='_ZN5clang6Parser33UnannotatedTentativeParsingAction17RevertAnnotationsEv'/>
<dec f='llvm/clang/lib/Parse/ParseCXXInlineMethods.cpp' l='1138' type='clang::Parser &amp;'/>
<offset>640</offset>
