<use f='llvm/clang/include/clang/Sema/Sema.h' l='9086' u='w' c='_ZN5clang4Sema29GlobalEagerInstantiationScopeC1ERS0_b'/>
<use f='llvm/clang/include/clang/Sema/Sema.h' l='9095' u='m' c='_ZN5clang4Sema29GlobalEagerInstantiationScope7performEv'/>
<use f='llvm/clang/include/clang/Sema/Sema.h' l='9096' u='m' c='_ZN5clang4Sema29GlobalEagerInstantiationScope7performEv'/>
<use f='llvm/clang/include/clang/Sema/Sema.h' l='9106' u='m' c='_ZN5clang4Sema29GlobalEagerInstantiationScopeD1Ev'/>
<use f='llvm/clang/include/clang/Sema/Sema.h' l='9109' u='m' c='_ZN5clang4Sema29GlobalEagerInstantiationScopeD1Ev'/>
<use f='llvm/clang/include/clang/Sema/Sema.h' l='9109' u='m' c='_ZN5clang4Sema29GlobalEagerInstantiationScopeD1Ev'/>
<use f='llvm/clang/include/clang/Sema/Sema.h' l='9112' u='m' c='_ZN5clang4Sema29GlobalEagerInstantiationScopeD1Ev'/>
<use f='llvm/clang/include/clang/Sema/Sema.h' l='9115' u='m' c='_ZN5clang4Sema29GlobalEagerInstantiationScopeD1Ev'/>
<use f='llvm/clang/include/clang/Sema/Sema.h' l='9116' u='m' c='_ZN5clang4Sema29GlobalEagerInstantiationScopeD1Ev'/>
<use f='llvm/clang/include/clang/Sema/Sema.h' l='9116' u='m' c='_ZN5clang4Sema29GlobalEagerInstantiationScopeD1Ev'/>
<dec f='llvm/clang/include/clang/Sema/Sema.h' l='9123' type='clang::Sema &amp;'/>
<offset>0</offset>
