<dec f='llvm/clang/include/clang/Analysis/AnyCall.h' l='61' type='const clang::Expr *'/>
<use f='llvm/clang/include/clang/Analysis/AnyCall.h' l='69' u='w' c='_ZN5clang7AnyCallC1EPKNS_8CallExprE'/>
<use f='llvm/clang/include/clang/Analysis/AnyCall.h' l='79' u='w' c='_ZN5clang7AnyCallC1EPKNS_15ObjCMessageExprE'/>
<use f='llvm/clang/include/clang/Analysis/AnyCall.h' l='82' u='w' c='_ZN5clang7AnyCallC1EPKNS_10CXXNewExprE'/>
<use f='llvm/clang/include/clang/Analysis/AnyCall.h' l='85' u='w' c='_ZN5clang7AnyCallC1EPKNS_13CXXDeleteExprE'/>
<use f='llvm/clang/include/clang/Analysis/AnyCall.h' l='88' u='w' c='_ZN5clang7AnyCallC1EPKNS_16CXXConstructExprE'/>
<use f='llvm/clang/include/clang/Analysis/AnyCall.h' l='91' u='w' c='_ZN5clang7AnyCallC1EPKNS_24CXXInheritedCtorInitExprE'/>
<use f='llvm/clang/include/clang/Analysis/AnyCall.h' l='93' u='w' c='_ZN5clang7AnyCallC1EPKNS_17CXXDestructorDeclE'/>
<use f='llvm/clang/include/clang/Analysis/AnyCall.h' l='95' u='w' c='_ZN5clang7AnyCallC1EPKNS_18CXXConstructorDeclE'/>
<use f='llvm/clang/include/clang/Analysis/AnyCall.h' l='97' u='w' c='_ZN5clang7AnyCallC1EPKNS_14ObjCMethodDeclE'/>
<use f='llvm/clang/include/clang/Analysis/AnyCall.h' l='99' u='w' c='_ZN5clang7AnyCallC1EPKNS_12FunctionDeclE'/>
<use f='llvm/clang/include/clang/Analysis/AnyCall.h' l='167' u='r' c='_ZNK5clang7AnyCall13getReturnTypeERNS_10ASTContextE'/>
<use f='llvm/clang/include/clang/Analysis/AnyCall.h' l='168' u='r' c='_ZNK5clang7AnyCall13getReturnTypeERNS_10ASTContextE'/>
<use f='llvm/clang/include/clang/Analysis/AnyCall.h' l='171' u='r' c='_ZNK5clang7AnyCall13getReturnTypeERNS_10ASTContextE'/>
<use f='llvm/clang/include/clang/Analysis/AnyCall.h' l='172' u='r' c='_ZNK5clang7AnyCall13getReturnTypeERNS_10ASTContextE'/>
<use f='llvm/clang/include/clang/Analysis/AnyCall.h' l='177' u='r' c='_ZNK5clang7AnyCall13getReturnTypeERNS_10ASTContextE'/>
<use f='llvm/clang/include/clang/Analysis/AnyCall.h' l='201' u='r' c='_ZNK5clang7AnyCall7getExprEv'/>
<use f='llvm/clang/include/clang/Analysis/AnyCall.h' l='209' u='r' c='_ZNK5clang7AnyCall4dumpEv'/>
<use f='llvm/clang/include/clang/Analysis/AnyCall.h' l='210' u='r' c='_ZNK5clang7AnyCall4dumpEv'/>
<offset>0</offset>
<doc f='llvm/clang/include/clang/Analysis/AnyCall.h' l='56'>/// Either expression or declaration (but not both at the same time)
  /// can be null.

  /// Call expression, is null when is not known (then declaration is non-null),
  /// or for implicit destructor calls (when no expression exists.)</doc>
