<dec f='llvm/clang/include/clang/Sema/DeclSpec.h' l='2608' type='clang::Declarator'/>
<use f='llvm/clang/include/clang/Sema/DeclSpec.h' l='2611' u='w' c='_ZN5clang15FieldDeclaratorC1ERKNS_8DeclSpecE'/>
<offset>0</offset>
<use f='llvm/clang/include/clang/Parse/RAIIObjectsForParser.h' l='236' u='m' c='_ZNK5clang22ParsingFieldDeclarator11getDeclSpecEv'/>
<use f='llvm/clang/lib/Parse/ParseDecl.cpp' l='4141' u='m' c='_ZN5clang6Parser22ParseStructDeclarationERNS_15ParsingDeclSpecEN4llvm12function_refIFvRNS_22ParsingFieldDeclaratorEEEE'/>
<use f='llvm/clang/lib/Parse/ParseDecl.cpp' l='4148' u='a' c='_ZN5clang6Parser22ParseStructDeclarationERNS_15ParsingDeclSpecEN4llvm12function_refIFvRNS_22ParsingFieldDeclaratorEEEE'/>
<use f='llvm/clang/lib/Parse/ParseDecl.cpp' l='4157' u='a' c='_ZN5clang6Parser22ParseStructDeclarationERNS_15ParsingDeclSpecEN4llvm12function_refIFvRNS_22ParsingFieldDeclaratorEEEE'/>
<use f='llvm/clang/lib/Parse/ParseDecl.cpp' l='4159' u='m' c='_ZN5clang6Parser22ParseStructDeclarationERNS_15ParsingDeclSpecEN4llvm12function_refIFvRNS_22ParsingFieldDeclaratorEEEE'/>
<use f='llvm/clang/lib/Parse/ParseDecl.cpp' l='4170' u='a' c='_ZN5clang6Parser22ParseStructDeclarationERNS_15ParsingDeclSpecEN4llvm12function_refIFvRNS_22ParsingFieldDeclaratorEEEE'/>
<use f='llvm/clang/lib/Parse/ParseDecl.cpp' l='4256' u='m' c='_ZN5clang6Parser20ParseStructUnionBodyENS_14SourceLocationENS_17TypeSpecifierTypeEPNS_10RecordDeclE'/>
<use f='llvm/clang/lib/Parse/ParseDecl.cpp' l='4257' u='a' c='_ZN5clang6Parser20ParseStructUnionBodyENS_14SourceLocationENS_17TypeSpecifierTypeEPNS_10RecordDeclE'/>
<use f='llvm/clang/lib/Parse/ParseObjc.cpp' l='730' u='m' c='_ZN5clang6Parser26ParseObjCInterfaceDeclListENS_3tok15ObjCKeywordKindEPNS_4DeclE'/>
<use f='llvm/clang/lib/Parse/ParseObjc.cpp' l='732' u='m' c='_ZN5clang6Parser26ParseObjCInterfaceDeclListENS_3tok15ObjCKeywordKindEPNS_4DeclE'/>
<use f='llvm/clang/lib/Parse/ParseObjc.cpp' l='737' u='m' c='_ZN5clang6Parser26ParseObjCInterfaceDeclListENS_3tok15ObjCKeywordKindEPNS_4DeclE'/>
<use f='llvm/clang/lib/Parse/ParseObjc.cpp' l='745' u='a' c='_ZN5clang6Parser26ParseObjCInterfaceDeclListENS_3tok15ObjCKeywordKindEPNS_4DeclE'/>
<use f='llvm/clang/lib/Parse/ParseObjc.cpp' l='751' u='m' c='_ZN5clang6Parser26ParseObjCInterfaceDeclListENS_3tok15ObjCKeywordKindEPNS_4DeclE'/>
<use f='llvm/clang/lib/Parse/ParseObjc.cpp' l='761' u='m' c='_ZN5clang6Parser26ParseObjCInterfaceDeclListENS_3tok15ObjCKeywordKindEPNS_4DeclE'/>
<use f='llvm/clang/lib/Parse/ParseObjc.cpp' l='1974' u='m' c='_ZN5clang6Parser31ParseObjCClassInstanceVariablesEPNS_4DeclENS_3tok15ObjCKeywordKindENS_14SourceLocationE'/>
<use f='llvm/clang/lib/Parse/ParseObjc.cpp' l='1976' u='m' c='_ZN5clang6Parser31ParseObjCClassInstanceVariablesEPNS_4DeclENS_3tok15ObjCKeywordKindENS_14SourceLocationE'/>
<use f='llvm/clang/lib/Parse/ParseObjc.cpp' l='1976' u='a' c='_ZN5clang6Parser31ParseObjCClassInstanceVariablesEPNS_4DeclENS_3tok15ObjCKeywordKindENS_14SourceLocationE'/>
<use f='llvm/clang/lib/Sema/SemaObjCProperty.cpp' l='183' u='m' c='_ZN5clang4Sema13ActOnPropertyEPNS_5ScopeENS_14SourceLocationES3_RNS_15FieldDeclaratorERNS_12ObjCDeclSpecENS_8SelectorES8_NS_3tok15ObjCKeywordKindEPNS_11DeclContextE'/>
<use f='llvm/clang/lib/Sema/SemaObjCProperty.cpp' l='185' u='a' c='_ZN5clang4Sema13ActOnPropertyEPNS_5ScopeENS_14SourceLocationES3_RNS_15FieldDeclaratorERNS_12ObjCDeclSpecENS_8SelectorES8_NS_3tok15ObjCKeywordKindEPNS_11DeclContextE'/>
<use f='llvm/clang/lib/Sema/SemaObjCProperty.cpp' l='429' u='m' c='_ZN5clang4Sema30HandlePropertyInClassExtensionEPNS_5ScopeENS_14SourceLocationES3_RNS_15FieldDeclaratorENS_8SelectorES3_S6_S3_bRjjNS_8QualTypeEPNS_14Ty4345573'/>
<use f='llvm/clang/lib/Sema/SemaObjCProperty.cpp' l='581' u='m' c='_ZN5clang4Sema18CreatePropertyDeclEPNS_5ScopeEPNS_17ObjCContainerDeclENS_14SourceLocationES5_RNS_15FieldDeclaratorENS_8SelectorES5_S8_S5_bjjNS_8QualTy13753222'/>
<use f='llvm/clang/lib/Sema/SemaObjCProperty.cpp' l='614' u='m' c='_ZN5clang4Sema18CreatePropertyDeclEPNS_5ScopeEPNS_17ObjCContainerDeclENS_14SourceLocationES5_RNS_15FieldDeclaratorENS_8SelectorES5_S8_S5_bjjNS_8QualTy13753222'/>
<use f='llvm/clang/lib/Sema/SemaObjCProperty.cpp' l='623' u='m' c='_ZN5clang4Sema18CreatePropertyDeclEPNS_5ScopeEPNS_17ObjCContainerDeclENS_14SourceLocationES5_RNS_15FieldDeclaratorENS_8SelectorES5_S8_S5_bjjNS_8QualTy13753222'/>
<use f='llvm/clang/lib/Sema/SemaObjCProperty.cpp' l='648' u='r' c='_ZN5clang4Sema18CreatePropertyDeclEPNS_5ScopeEPNS_17ObjCContainerDeclENS_14SourceLocationES5_RNS_15FieldDeclaratorENS_8SelectorES5_S8_S5_bjjNS_8QualTy13753222'/>
