<dec f='llvm/clang/include/clang/AST/Stmt.h' l='2502' type='0'/>
<use f='llvm/clang/include/clang/AST/Stmt.h' l='2514' u='r' c='_ZN5clang7ForStmt7getInitEv'/>
<use f='llvm/clang/include/clang/AST/Stmt.h' l='2537' u='r' c='_ZNK5clang7ForStmt7getInitEv'/>
<use f='llvm/clang/include/clang/AST/Stmt.h' l='2542' u='w' c='_ZN5clang7ForStmt7setInitEPNS_4StmtE'/>
<use f='llvm/clang/lib/AST/Stmt.cpp' l='1003' u='w' c='_ZN5clang7ForStmtC1ERKNS_10ASTContextEPNS_4StmtEPNS_4ExprEPNS_7VarDeclES7_S5_NS_14SourceLocationESA_SA_'/>
