<dec f='llvm/clang/include/clang/StaticAnalyzer/Core/CheckerManager.h' l='131' type='const clang::Preprocessor *'/>
<use f='llvm/clang/include/clang/StaticAnalyzer/Core/CheckerManager.h' l='174' u='r' c='_ZNK5clang4ento14CheckerManager15getPreprocessorEv'/>
<offset>4928</offset>
<use f='llvm/clang/lib/StaticAnalyzer/Frontend/CreateCheckerManager.cpp' l='25' u='w' c='_ZN5clang4ento14CheckerManagerC1ERNS_10ASTContextERNS_15AnalyzerOptionsERKNS_12PreprocessorEN4llvm8ArrayRefINSt7__cxx1112basic_stringIcSt11char_traits2122276'/>
