<dec f='llvm/clang/include/clang/Serialization/ASTReader.h' l='584' type='clang::ASTReader::ModuleFile *'/>
<offset>0</offset>
<use f='llvm/clang/lib/Serialization/ASTReaderDecl.cpp' l='4223' u='r' c='_ZN5clang9ASTReader21loadDeclUpdateRecordsERNS0_19PendingUpdateRecordE'/>
<use f='llvm/clang/lib/Serialization/ASTReaderDecl.cpp' l='4224' u='r' c='_ZN5clang9ASTReader21loadDeclUpdateRecordsERNS0_19PendingUpdateRecordE'/>
