<dec f='llvm/clang/include/clang/AST/TextNodeDumper.h' l='33' type='llvm::raw_ostream &amp;'/>
<use f='llvm/clang/include/clang/AST/TextNodeDumper.h' l='67' u='m' c='_ZN5clang17TextTreeStructure8AddChildEN4llvm9StringRefET_'/>
<use f='llvm/clang/include/clang/AST/TextNodeDumper.h' l='89' u='m' c='_ZN5clang17TextTreeStructure8AddChildEN4llvm9StringRefET_'/>
<use f='llvm/clang/include/clang/AST/TextNodeDumper.h' l='90' u='a' c='_ZN5clang17TextTreeStructure8AddChildEN4llvm9StringRefET_'/>
<use f='llvm/clang/include/clang/AST/TextNodeDumper.h' l='91' u='m' c='_ZN5clang17TextTreeStructure8AddChildEN4llvm9StringRefET_'/>
<use f='llvm/clang/include/clang/AST/TextNodeDumper.h' l='93' u='m' c='_ZN5clang17TextTreeStructure8AddChildEN4llvm9StringRefET_'/>
<use f='llvm/clang/include/clang/AST/TextNodeDumper.h' l='125' u='w' c='_ZN5clang17TextTreeStructureC1ERN4llvm11raw_ostreamEb'/>
<offset>0</offset>
