<dec f='llvm/clang/include/clang/Analysis/PathDiagnostic.h' l='200' type='const clang::Stmt *'/>
<use f='llvm/clang/include/clang/Analysis/PathDiagnostic.h' l='224' u='w' c='_ZN5clang4ento22PathDiagnosticLocationC1EPKNS_4StmtERKNS_13SourceManagerEN4llvm12PointerUnionIJPKNS_15LocationContextEPNS_19AnalysisDeclContextEEEE'/>
<use f='llvm/clang/include/clang/Analysis/PathDiagnostic.h' l='348' u='r' c='_ZNK5clang4ento22PathDiagnosticLocation6asStmtEv'/>
<offset>64</offset>
<use f='llvm/clang/lib/Analysis/PathDiagnostic.cpp' l='754' u='r' c='_ZNK5clang4ento22PathDiagnosticLocation11genLocationENS_14SourceLocationEN4llvm12PointerUnionIJPKNS_15LocationContextEPNS_19AnalysisDeclContextEEEE'/>
<use f='llvm/clang/lib/Analysis/PathDiagnostic.cpp' l='756' u='r' c='_ZNK5clang4ento22PathDiagnosticLocation11genLocationENS_14SourceLocationEN4llvm12PointerUnionIJPKNS_15LocationContextEPNS_19AnalysisDeclContextEEEE'/>
<use f='llvm/clang/lib/Analysis/PathDiagnostic.cpp' l='832' u='w' c='_ZN5clang4ento22PathDiagnosticLocation7flattenEv'/>
<use f='llvm/clang/lib/Analysis/PathDiagnostic.cpp' l='837' u='w' c='_ZN5clang4ento22PathDiagnosticLocation7flattenEv'/>
<use f='llvm/clang/lib/Analysis/PathDiagnostic.cpp' l='1219' u='r' c='_ZNK5clang4ento22PathDiagnosticLocation4dumpEv'/>
<use f='llvm/clang/lib/Analysis/PathDiagnostic.cpp' l='1220' u='r' c='_ZNK5clang4ento22PathDiagnosticLocation4dumpEv'/>
