<dec f='llvm/clang/include/clang/Basic/Attributes.h' l='21' type='0'/>
<use f='llvm/build/tools/clang/include/clang/Basic/AttrHasAttributeImpl.inc' l='11' c='_ZN5clang12hasAttributeENS_10AttrSyntaxEPKNS_14IdentifierInfoES3_RKNS_10TargetInfoERKNS_11LangOptionsE'/>
<doc f='llvm/clang/include/clang/Basic/Attributes.h' l='20'>/// Is the identifier known as a GNU-style attribute?</doc>
<use f='llvm/clang/lib/Lex/PPMacroExpansion.cpp' l='1688' u='r' c='_ZN5clang12Preprocessor18ExpandBuiltinMacroERNS_5TokenE'/>
