<dec f='llvm/clang/lib/CodeGen/CGValue.h' l='177' type='llvm::Value *'/>
<use f='llvm/clang/lib/CodeGen/CGValue.h' l='327' u='r' c='_ZNK5clang7CodeGen6LValue10getPointerERNS0_15CodeGenFunctionE'/>
<use f='llvm/clang/lib/CodeGen/CGValue.h' l='334' u='w' c='_ZN5clang7CodeGen6LValue10setAddressENS0_7AddressE'/>
<use f='llvm/clang/lib/CodeGen/CGValue.h' l='344' u='r' c='_ZNK5clang7CodeGen6LValue16getVectorPointerEv'/>
<use f='llvm/clang/lib/CodeGen/CGValue.h' l='356' u='r' c='_ZNK5clang7CodeGen6LValue16getMatrixPointerEv'/>
<use f='llvm/clang/lib/CodeGen/CGValue.h' l='369' u='r' c='_ZNK5clang7CodeGen6LValue19getExtVectorPointerEv'/>
<use f='llvm/clang/lib/CodeGen/CGValue.h' l='380' u='r' c='_ZNK5clang7CodeGen6LValue18getBitFieldPointerEv'/>
<use f='llvm/clang/lib/CodeGen/CGValue.h' l='387' u='r' c='_ZNK5clang7CodeGen6LValue12getGlobalRegEv'/>
<use f='llvm/clang/lib/CodeGen/CGValue.h' l='397' u='w' c='_ZN5clang7CodeGen6LValue8MakeAddrENS0_7AddressENS_8QualTypeERNS_10ASTContextENS0_14LValueBaseInfoENS0_14TBAAAccessInfoE'/>
<use f='llvm/clang/lib/CodeGen/CGValue.h' l='407' u='w' c='_ZN5clang7CodeGen6LValue13MakeVectorEltENS0_7AddressEPN4llvm5ValueENS_8QualTypeENS0_14LValueBaseInfoENS0_14TBAAAccessInfoE'/>
<use f='llvm/clang/lib/CodeGen/CGValue.h' l='419' u='w' c='_ZN5clang7CodeGen6LValue16MakeExtVectorEltENS0_7AddressEPN4llvm8ConstantENS_8QualTypeENS0_14LValueBaseInfoENS0_14TBAAAccessInfoE'/>
<use f='llvm/clang/lib/CodeGen/CGValue.h' l='437' u='w' c='_ZN5clang7CodeGen6LValue12MakeBitfieldENS0_7AddressERKNS0_14CGBitFieldInfoENS_8QualTypeENS0_14LValueBaseInfoENS0_14TBAAAccessInfoE'/>
<use f='llvm/clang/lib/CodeGen/CGValue.h' l='447' u='w' c='_ZN5clang7CodeGen6LValue13MakeGlobalRegENS0_7AddressENS_8QualTypeE'/>
<use f='llvm/clang/lib/CodeGen/CGValue.h' l='458' u='w' c='_ZN5clang7CodeGen6LValue13MakeMatrixEltENS0_7AddressEPN4llvm5ValueENS_8QualTypeENS0_14LValueBaseInfoENS0_14TBAAAccessInfoE'/>
<offset>64</offset>
