<def f='llvm/clang/unittests/AST/ASTImporterFixtures.h' l='109' ll='135'/>
<use f='llvm/clang/unittests/AST/ASTImporterFixtures.h' l='144'/>
<use f='llvm/clang/unittests/AST/ASTImporterFixtures.h' l='160' c='_ZN5clang12ast_matchers19ASTImporterTestBase10findFromTUEPNS_4DeclE'/>
<use f='llvm/clang/unittests/AST/ASTImporterFixtures.cpp' l='130' c='_ZN5clang12ast_matchers19ASTImporterTestBase10findFromTUEPNS_4DeclE'/>
<use f='llvm/clang/unittests/AST/ASTImporterFixtures.cpp' l='134' c='_ZN5clang12ast_matchers19ASTImporterTestBase10findFromTUEPNS_4DeclE'/>
<use f='llvm/clang/unittests/AST/ASTImporterFixtures.cpp' l='149' c='_ZN5clang12ast_matchers19ASTImporterTestBase15getImportedDeclEN4llvm9StringRefENS_12TestLanguageES3_S4_S3_'/>
<use f='llvm/clang/unittests/AST/ASTImporterFixtures.cpp' l='182' c='_ZN5clang12ast_matchers19ASTImporterTestBase9getTuDeclEN4llvm9StringRefENS_12TestLanguageES3_'/>
<use f='llvm/clang/unittests/AST/ASTImporterFixtures.cpp' l='197' c='_ZN5clang12ast_matchers19ASTImporterTestBase6ImportEPNS_4DeclENS_12TestLanguageE'/>
<use f='llvm/clang/unittests/AST/ASTImporterFixtures.cpp' l='206' c='_ZN5clang12ast_matchers19ASTImporterTestBase13importOrErrorEPNS_4DeclENS_12TestLanguageE'/>
<use f='llvm/clang/unittests/AST/ASTImporterFixtures.cpp' l='216' c='_ZN5clang12ast_matchers19ASTImporterTestBase10ImportTypeENS_8QualTypeEPNS_4DeclENS_12TestLanguageE'/>
<size>128</size>
<doc f='llvm/clang/unittests/AST/ASTImporterFixtures.h' l='107'>// Represents a &quot;From&quot; translation unit and holds an importer object which we
  // use to import from this translation unit.</doc>
<mbr r='clang::ast_matchers::ASTImporterTestBase::TU::Code' o='0' t='std::string'/>
<mbr r='clang::ast_matchers::ASTImporterTestBase::TU::FileName' o='256' t='std::string'/>
<mbr r='clang::ast_matchers::ASTImporterTestBase::TU::Unit' o='512' t='std::unique_ptr&lt;ASTUnit&gt;'/>
<mbr r='clang::ast_matchers::ASTImporterTestBase::TU::TUDecl' o='576' t='clang::TranslationUnitDecl *'/>
<mbr r='clang::ast_matchers::ASTImporterTestBase::TU::Importer' o='640' t='std::unique_ptr&lt;ASTImporter&gt;'/>
<mbr r='clang::ast_matchers::ASTImporterTestBase::TU::Creator' o='704' t='clang::ast_matchers::ASTImporterTestBase::ImporterConstructor'/>
<mbr r='clang::ast_matchers::ASTImporterTestBase::TU::ODRHandling' o='960' t='ASTImporter::ODRHandlingType'/>
<fun r='_ZN5clang12ast_matchers19ASTImporterTestBase2TUC1EN4llvm9StringRefES4_St6vectorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaISB_EESt8functio8745593'/>
<fun r='_ZN5clang12ast_matchers19ASTImporterTestBase2TUD1Ev'/>
<fun r='_ZN5clang12ast_matchers19ASTImporterTestBase2TU16lazyInitImporterERKSt10shared_ptrINS_22ASTImporterSharedStateEEPNS_7ASTUnitE'/>
<fun r='_ZN5clang12ast_matchers19ASTImporterTestBase2TU6importERKSt10shared_ptrINS_22ASTImporterSharedStateEEPNS_7ASTUnitEPNS_4DeclE'/>
<fun r='_ZN5clang12ast_matchers19ASTImporterTestBase2TU13importOrErrorERKSt10shared_ptrINS_22ASTImporterSharedStateEEPNS_7ASTUnitEPNS_4DeclE'/>
<fun r='_ZN5clang12ast_matchers19ASTImporterTestBase2TU6importERKSt10shared_ptrINS_22ASTImporterSharedStateEEPNS_7ASTUnitENS_8QualTypeE'/>
<fun r='_ZN5clang12ast_matchers19ASTImporterTestBase2TUC1EN4llvm9StringRefES4_St6vectorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaISB_EESt8functio8745593'/>
<fun r='_ZN5clang12ast_matchers19ASTImporterTestBase2TUD1Ev'/>
<fun r='_ZN5clang12ast_matchers19ASTImporterTestBase2TU16lazyInitImporterERKSt10shared_ptrINS_22ASTImporterSharedStateEEPNS_7ASTUnitE'/>
<fun r='_ZN5clang12ast_matchers19ASTImporterTestBase2TU6importERKSt10shared_ptrINS_22ASTImporterSharedStateEEPNS_7ASTUnitEPNS_4DeclE'/>
<fun r='_ZN5clang12ast_matchers19ASTImporterTestBase2TU13importOrErrorERKSt10shared_ptrINS_22ASTImporterSharedStateEEPNS_7ASTUnitEPNS_4DeclE'/>
<fun r='_ZN5clang12ast_matchers19ASTImporterTestBase2TU6importERKSt10shared_ptrINS_22ASTImporterSharedStateEEPNS_7ASTUnitENS_8QualTypeE'/>
