<dec f='llvm/clang/include/clang/Analysis/CloneDetection.h' l='40' type='const clang::Decl *'/>
<use f='llvm/clang/include/clang/Analysis/CloneDetection.h' l='115' u='r' c='_ZNK5clang12StmtSequence17getContainingDeclEv'/>
<use f='llvm/clang/lib/Analysis/CloneDetection.cpp' l='25' u='w' c='_ZN5clang12StmtSequenceC1EPKNS_12CompoundStmtEPKNS_4DeclEjj'/>
<use f='llvm/clang/lib/Analysis/CloneDetection.cpp' l='32' u='w' c='_ZN5clang12StmtSequenceC1EPKNS_4StmtEPKNS_4DeclE'/>
<use f='llvm/clang/lib/Analysis/CloneDetection.cpp' l='35' u='w' c='_ZN5clang12StmtSequenceC1Ev'/>
<use f='llvm/clang/lib/Analysis/CloneDetection.cpp' l='40' u='r' c='_ZNK5clang12StmtSequence8containsERKS0_'/>
<use f='llvm/clang/lib/Analysis/CloneDetection.cpp' l='40' u='r' c='_ZNK5clang12StmtSequence8containsERKS0_'/>
<use f='llvm/clang/lib/Analysis/CloneDetection.cpp' l='77' u='r' c='_ZNK5clang12StmtSequence13getASTContextEv'/>
<offset>64</offset>
<doc f='llvm/clang/include/clang/Analysis/CloneDetection.h' l='39'>/// The declaration that contains the statements.</doc>
