<dec f='llvm/clang/include/clang/Tooling/JSONCompilationDatabase.h' l='60' type='1'/>
<use f='llvm/clang/lib/Tooling/JSONCompilationDatabase.cpp' l='138' u='r' c='_ZN12_GLOBAL__N_119unescapeCommandLineB5cxx11EN5clang7tooling21JSONCommandLineSyntaxEN4llvm9StringRefE'/>
<use f='llvm/clang/unittests/Tooling/CompilationDatabaseTest.cpp' l='31' u='r' c='_ZN5clang7toolingL13expectFailureEN4llvm9StringRefES2_'/>
<use f='llvm/clang/unittests/Tooling/CompilationDatabaseTest.cpp' l='84' u='r' c='_ZN5clang7tooling40JSONCompilationDatabase_GetAllFiles_Test8TestBodyEv'/>
<use f='llvm/clang/unittests/Tooling/CompilationDatabaseTest.cpp' l='105' u='r' c='_ZN5clang7tooling40JSONCompilationDatabase_GetAllFiles_Test8TestBodyEv'/>
<use f='llvm/clang/unittests/Tooling/CompilationDatabaseTest.cpp' l='112' u='r' c='_ZN5clang7tooling50JSONCompilationDatabase_GetAllCompileCommands_Test8TestBodyEv'/>
<use f='llvm/clang/unittests/Tooling/CompilationDatabaseTest.cpp' l='126' u='r' c='_ZN5clang7tooling50JSONCompilationDatabase_GetAllCompileCommands_Test8TestBodyEv'/>
<use f='llvm/clang/unittests/Tooling/CompilationDatabaseTest.cpp' l='152' u='r' c='_ZN5clang7tooling50JSONCompilationDatabase_GetAllCompileCommands_Test8TestBodyEv'/>
<use f='llvm/clang/unittests/Tooling/CompilationDatabaseTest.cpp' l='179' u='r' c='_ZN5clang7toolingL29findCompileArgsInJsonDatabaseEN4llvm9StringRefENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERS8_'/>
