<dec f='llvm/clang/unittests/StaticAnalyzer/Reusables.h' l='52' type='clang::ento::FunctionSummariesTy'/>
<use f='llvm/clang/unittests/StaticAnalyzer/Reusables.h' l='65' u='w' c='_ZN5clang4ento18ExprEngineConsumerC1ERNS_16CompilerInstanceE'/>
<use f='llvm/clang/unittests/StaticAnalyzer/Reusables.h' l='66' u='a' c='_ZN5clang4ento18ExprEngineConsumerC1ERNS_16CompilerInstanceE'/>
<offset>15168</offset>
