<dec f='llvm/clang/include/clang/StaticAnalyzer/Core/BugReporter/BugReporter.h' l='96' type='std::string'/>
<use f='llvm/clang/include/clang/StaticAnalyzer/Core/BugReporter/BugReporter.h' l='99' u='w' c='_ZN5clang4ento27StackHintGeneratorForSymbolC1EPKNS0_7SymExprEN4llvm9StringRefE'/>
<use f='llvm/clang/include/clang/StaticAnalyzer/Core/BugReporter/BugReporter.h' l='111' u='r' c='_ZN5clang4ento27StackHintGeneratorForSymbol19getMessageForReturnB5cxx11EPKNS_8CallExprE'/>
<use f='llvm/clang/include/clang/StaticAnalyzer/Core/BugReporter/BugReporter.h' l='115' u='r' c='_ZN5clang4ento27StackHintGeneratorForSymbol27getMessageForSymbolNotFoundB5cxx11Ev'/>
<offset>128</offset>
<use f='llvm/clang/lib/StaticAnalyzer/Core/BugReporter.cpp' l='336' u='r' c='_ZN5clang4ento27StackHintGeneratorForSymbol16getMessageForArgB5cxx11EPKNS_4ExprEj'/>
