<use f='llvm/clang/unittests/Analysis/CFGBuildResult.h' l='29' u='w' c='_ZN5clang8analysis11BuildResultC1ENS1_6StatusEPKNS_12FunctionDeclESt10unique_ptrINS_3CFGESt14default_deleteIS7_EES6_INS_7ASTUnitES8_ISB_EE'/>
<use f='llvm/clang/unittests/Analysis/CFGBuildResult.h' l='31' u='r' c='_ZNK5clang8analysis11BuildResult9getStatusEv'/>
<dec f='llvm/clang/unittests/Analysis/CFGBuildResult.h' l='37' type='clang::analysis::BuildResult::Status'/>
<offset>0</offset>
