<dec f='llvm/clang/include/clang/AST/Expr.h' l='3337' type='clang::Stmt *'/>
<use f='llvm/clang/include/clang/AST/Expr.h' l='3342' u='w' c='_ZN5clang19CompoundLiteralExprC1ENS_14SourceLocationEPNS_14TypeSourceInfoENS_8QualTypeENS_13ExprValueKindEPNS_4ExprEb'/>
<use f='llvm/clang/include/clang/AST/Expr.h' l='3350' u='r' c='_ZNK5clang19CompoundLiteralExpr14getInitializerEv'/>
<use f='llvm/clang/include/clang/AST/Expr.h' l='3351' u='r' c='_ZN5clang19CompoundLiteralExpr14getInitializerEv'/>
<use f='llvm/clang/include/clang/AST/Expr.h' l='3352' u='w' c='_ZN5clang19CompoundLiteralExpr14setInitializerEPNS_4ExprE'/>
<use f='llvm/clang/include/clang/AST/Expr.h' l='3369' u='r' c='_ZNK5clang19CompoundLiteralExpr11getBeginLocEv'/>
<use f='llvm/clang/include/clang/AST/Expr.h' l='3372' u='r' c='_ZNK5clang19CompoundLiteralExpr11getBeginLocEv'/>
<use f='llvm/clang/include/clang/AST/Expr.h' l='3377' u='r' c='_ZNK5clang19CompoundLiteralExpr9getEndLocEv'/>
<use f='llvm/clang/include/clang/AST/Expr.h' l='3379' u='r' c='_ZNK5clang19CompoundLiteralExpr9getEndLocEv'/>
<use f='llvm/clang/include/clang/AST/Expr.h' l='3387' u='a' c='_ZN5clang19CompoundLiteralExpr8childrenEv'/>
<use f='llvm/clang/include/clang/AST/Expr.h' l='3387' u='a' c='_ZN5clang19CompoundLiteralExpr8childrenEv'/>
<use f='llvm/clang/include/clang/AST/Expr.h' l='3389' u='a' c='_ZNK5clang19CompoundLiteralExpr8childrenEv'/>
<use f='llvm/clang/include/clang/AST/Expr.h' l='3389' u='a' c='_ZNK5clang19CompoundLiteralExpr8childrenEv'/>
<offset>256</offset>
