<dec f='llvm/clang/include/clang/Serialization/ASTReader.h' l='1412' type='clang::ASTReader::ModuleFile *'/>
<use f='llvm/clang/include/clang/Serialization/ASTReader.h' l='1419' u='w' c='_ZN5clang9ASTReader18ModuleDeclIteratorC1EPS0_PNS_13serialization10ModuleFileEPKj'/>
<use f='llvm/clang/include/clang/Serialization/ASTReader.h' l='1422' u='r' c='_ZNK5clang9ASTReader18ModuleDeclIteratordeEv'/>
<offset>128</offset>
