<dec f='llvm/build/tools/clang/include/clang/AST/AbstractTypeReader.inc' l='12' type='PropertyReader &amp;'/>
<use f='llvm/build/tools/clang/include/clang/AST/AbstractTypeReader.inc' l='14' u='w' c='_ZN5clang13serialization18AbstractTypeReaderC1ERT_'/>
<use f='llvm/build/tools/clang/include/clang/AST/AbstractTypeReader.inc' l='127' u='c' c='_ZN5clang13serialization18AbstractTypeReader16readAdjustedTypeEv'/>
<use f='llvm/build/tools/clang/include/clang/AST/AbstractTypeReader.inc' l='128' u='c' c='_ZN5clang13serialization18AbstractTypeReader16readAdjustedTypeEv'/>
<use f='llvm/build/tools/clang/include/clang/AST/AbstractTypeReader.inc' l='129' u='c' c='_ZN5clang13serialization18AbstractTypeReader16readAdjustedTypeEv'/>
<use f='llvm/build/tools/clang/include/clang/AST/AbstractTypeReader.inc' l='134' u='c' c='_ZN5clang13serialization18AbstractTypeReader15readDecayedTypeEv'/>
<use f='llvm/build/tools/clang/include/clang/AST/AbstractTypeReader.inc' l='135' u='c' c='_ZN5clang13serialization18AbstractTypeReader15readDecayedTypeEv'/>
<use f='llvm/build/tools/clang/include/clang/AST/AbstractTypeReader.inc' l='140' u='c' c='_ZN5clang13serialization18AbstractTypeReader21readConstantArrayTypeEv'/>
<use f='llvm/build/tools/clang/include/clang/AST/AbstractTypeReader.inc' l='141' u='c' c='_ZN5clang13serialization18AbstractTypeReader21readConstantArrayTypeEv'/>
<use f='llvm/build/tools/clang/include/clang/AST/AbstractTypeReader.inc' l='142' u='c' c='_ZN5clang13serialization18AbstractTypeReader21readConstantArrayTypeEv'/>
<use f='llvm/build/tools/clang/include/clang/AST/AbstractTypeReader.inc' l='143' u='c' c='_ZN5clang13serialization18AbstractTypeReader21readConstantArrayTypeEv'/>
<use f='llvm/build/tools/clang/include/clang/AST/AbstractTypeReader.inc' l='144' u='c' c='_ZN5clang13serialization18AbstractTypeReader21readConstantArrayTypeEv'/>
<use f='llvm/build/tools/clang/include/clang/AST/AbstractTypeReader.inc' l='145' u='c' c='_ZN5clang13serialization18AbstractTypeReader21readConstantArrayTypeEv'/>
<use f='llvm/build/tools/clang/include/clang/AST/AbstractTypeReader.inc' l='154' u='c' c='_ZN5clang13serialization18AbstractTypeReader27readDependentSizedArrayTypeEv'/>
<use f='llvm/build/tools/clang/include/clang/AST/AbstractTypeReader.inc' l='155' u='c' c='_ZN5clang13serialization18AbstractTypeReader27readDependentSizedArrayTypeEv'/>
<use f='llvm/build/tools/clang/include/clang/AST/AbstractTypeReader.inc' l='156' u='c' c='_ZN5clang13serialization18AbstractTypeReader27readDependentSizedArrayTypeEv'/>
<use f='llvm/build/tools/clang/include/clang/AST/AbstractTypeReader.inc' l='157' u='c' c='_ZN5clang13serialization18AbstractTypeReader27readDependentSizedArrayTypeEv'/>
<use f='llvm/build/tools/clang/include/clang/AST/AbstractTypeReader.inc' l='158' u='c' c='_ZN5clang13serialization18AbstractTypeReader27readDependentSizedArrayTypeEv'/>
<use f='llvm/build/tools/clang/include/clang/AST/AbstractTypeReader.inc' l='159' u='c' c='_ZN5clang13serialization18AbstractTypeReader27readDependentSizedArrayTypeEv'/>
<use f='llvm/build/tools/clang/include/clang/AST/AbstractTypeReader.inc' l='160' u='c' c='_ZN5clang13serialization18AbstractTypeReader27readDependentSizedArrayTypeEv'/>
<use f='llvm/build/tools/clang/include/clang/AST/AbstractTypeReader.inc' l='170' u='c' c='_ZN5clang13serialization18AbstractTypeReader23readIncompleteArrayTypeEv'/>
<use f='llvm/build/tools/clang/include/clang/AST/AbstractTypeReader.inc' l='171' u='c' c='_ZN5clang13serialization18AbstractTypeReader23readIncompleteArrayTypeEv'/>
<use f='llvm/build/tools/clang/include/clang/AST/AbstractTypeReader.inc' l='172' u='c' c='_ZN5clang13serialization18AbstractTypeReader23readIncompleteArrayTypeEv'/>
<use f='llvm/build/tools/clang/include/clang/AST/AbstractTypeReader.inc' l='173' u='c' c='_ZN5clang13serialization18AbstractTypeReader23readIncompleteArrayTypeEv'/>
<use f='llvm/build/tools/clang/include/clang/AST/AbstractTypeReader.inc' l='181' u='c' c='_ZN5clang13serialization18AbstractTypeReader21readVariableArrayTypeEv'/>
<use f='llvm/build/tools/clang/include/clang/AST/AbstractTypeReader.inc' l='182' u='c' c='_ZN5clang13serialization18AbstractTypeReader21readVariableArrayTypeEv'/>
<use f='llvm/build/tools/clang/include/clang/AST/AbstractTypeReader.inc' l='183' u='c' c='_ZN5clang13serialization18AbstractTypeReader21readVariableArrayTypeEv'/>
<use f='llvm/build/tools/clang/include/clang/AST/AbstractTypeReader.inc' l='184' u='c' c='_ZN5clang13serialization18AbstractTypeReader21readVariableArrayTypeEv'/>
<use f='llvm/build/tools/clang/include/clang/AST/AbstractTypeReader.inc' l='185' u='c' c='_ZN5clang13serialization18AbstractTypeReader21readVariableArrayTypeEv'/>
<use f='llvm/build/tools/clang/include/clang/AST/AbstractTypeReader.inc' l='186' u='c' c='_ZN5clang13serialization18AbstractTypeReader21readVariableArrayTypeEv'/>
<use f='llvm/build/tools/clang/include/clang/AST/AbstractTypeReader.inc' l='187' u='c' c='_ZN5clang13serialization18AbstractTypeReader21readVariableArrayTypeEv'/>
<use f='llvm/build/tools/clang/include/clang/AST/AbstractTypeReader.inc' l='197' u='c' c='_ZN5clang13serialization18AbstractTypeReader14readAtomicTypeEv'/>
<use f='llvm/build/tools/clang/include/clang/AST/AbstractTypeReader.inc' l='198' u='c' c='_ZN5clang13serialization18AbstractTypeReader14readAtomicTypeEv'/>
<use f='llvm/build/tools/clang/include/clang/AST/AbstractTypeReader.inc' l='205' u='c' c='_ZN5clang13serialization18AbstractTypeReader18readAttributedTypeEv'/>
<use f='llvm/build/tools/clang/include/clang/AST/AbstractTypeReader.inc' l='206' u='c' c='_ZN5clang13serialization18AbstractTypeReader18readAttributedTypeEv'/>
<use f='llvm/build/tools/clang/include/clang/AST/AbstractTypeReader.inc' l='207' u='c' c='_ZN5clang13serialization18AbstractTypeReader18readAttributedTypeEv'/>
<use f='llvm/build/tools/clang/include/clang/AST/AbstractTypeReader.inc' l='208' u='c' c='_ZN5clang13serialization18AbstractTypeReader18readAttributedTypeEv'/>
<use f='llvm/build/tools/clang/include/clang/AST/AbstractTypeReader.inc' l='215' u='c' c='_ZN5clang13serialization18AbstractTypeReader20readBlockPointerTypeEv'/>
<use f='llvm/build/tools/clang/include/clang/AST/AbstractTypeReader.inc' l='216' u='c' c='_ZN5clang13serialization18AbstractTypeReader20readBlockPointerTypeEv'/>
<use f='llvm/build/tools/clang/include/clang/AST/AbstractTypeReader.inc' l='221' u='c' c='_ZN5clang13serialization18AbstractTypeReader15readBuiltinTypeEv'/>
<use f='llvm/build/tools/clang/include/clang/AST/AbstractTypeReader.inc' l='222' u='c' c='_ZN5clang13serialization18AbstractTypeReader15readBuiltinTypeEv'/>
<use f='llvm/build/tools/clang/include/clang/AST/AbstractTypeReader.inc' l='250' u='c' c='_ZN5clang13serialization18AbstractTypeReader15readComplexTypeEv'/>
<use f='llvm/build/tools/clang/include/clang/AST/AbstractTypeReader.inc' l='251' u='c' c='_ZN5clang13serialization18AbstractTypeReader15readComplexTypeEv'/>
<use f='llvm/build/tools/clang/include/clang/AST/AbstractTypeReader.inc' l='256' u='c' c='_ZN5clang13serialization18AbstractTypeReader16readDecltypeTypeEv'/>
<use f='llvm/build/tools/clang/include/clang/AST/AbstractTypeReader.inc' l='257' u='c' c='_ZN5clang13serialization18AbstractTypeReader16readDecltypeTypeEv'/>
<use f='llvm/build/tools/clang/include/clang/AST/AbstractTypeReader.inc' l='258' u='c' c='_ZN5clang13serialization18AbstractTypeReader16readDecltypeTypeEv'/>
<use f='llvm/build/tools/clang/include/clang/AST/AbstractTypeReader.inc' l='265' u='c' c='_ZN5clang13serialization18AbstractTypeReader12readAutoTypeEv'/>
<use f='llvm/build/tools/clang/include/clang/AST/AbstractTypeReader.inc' l='266' u='c' c='_ZN5clang13serialization18AbstractTypeReader12readAutoTypeEv'/>
<use f='llvm/build/tools/clang/include/clang/AST/AbstractTypeReader.inc' l='267' u='c' c='_ZN5clang13serialization18AbstractTypeReader12readAutoTypeEv'/>
<use f='llvm/build/tools/clang/include/clang/AST/AbstractTypeReader.inc' l='268' u='c' c='_ZN5clang13serialization18AbstractTypeReader12readAutoTypeEv'/>
<use f='llvm/build/tools/clang/include/clang/AST/AbstractTypeReader.inc' l='270' u='c' c='_ZN5clang13serialization18AbstractTypeReader12readAutoTypeEv'/>
<use f='llvm/build/tools/clang/include/clang/AST/AbstractTypeReader.inc' l='271' u='c' c='_ZN5clang13serialization18AbstractTypeReader12readAutoTypeEv'/>
<use f='llvm/build/tools/clang/include/clang/AST/AbstractTypeReader.inc' l='282' u='c' c='_ZN5clang13serialization18AbstractTypeReader37readDeducedTemplateSpecializationTypeEv'/>
<use f='llvm/build/tools/clang/include/clang/AST/AbstractTypeReader.inc' l='283' u='c' c='_ZN5clang13serialization18AbstractTypeReader37readDeducedTemplateSpecializationTypeEv'/>
<use f='llvm/build/tools/clang/include/clang/AST/AbstractTypeReader.inc' l='284' u='c' c='_ZN5clang13serialization18AbstractTypeReader37readDeducedTemplateSpecializationTypeEv'/>
<use f='llvm/build/tools/clang/include/clang/AST/AbstractTypeReader.inc' l='285' u='c' c='_ZN5clang13serialization18AbstractTypeReader37readDeducedTemplateSpecializationTypeEv'/>
<use f='llvm/build/tools/clang/include/clang/AST/AbstractTypeReader.inc' l='294' u='c' c='_ZN5clang13serialization18AbstractTypeReader29readDependentAddressSpaceTypeEv'/>
<use f='llvm/build/tools/clang/include/clang/AST/AbstractTypeReader.inc' l='295' u='c' c='_ZN5clang13serialization18AbstractTypeReader29readDependentAddressSpaceTypeEv'/>
<use f='llvm/build/tools/clang/include/clang/AST/AbstractTypeReader.inc' l='296' u='c' c='_ZN5clang13serialization18AbstractTypeReader29readDependentAddressSpaceTypeEv'/>
<use f='llvm/build/tools/clang/include/clang/AST/AbstractTypeReader.inc' l='297' u='c' c='_ZN5clang13serialization18AbstractTypeReader29readDependentAddressSpaceTypeEv'/>
<use f='llvm/build/tools/clang/include/clang/AST/AbstractTypeReader.inc' l='305' u='c' c='_ZN5clang13serialization18AbstractTypeReader23readDependentExtIntTypeEv'/>
<use f='llvm/build/tools/clang/include/clang/AST/AbstractTypeReader.inc' l='306' u='c' c='_ZN5clang13serialization18AbstractTypeReader23readDependentExtIntTypeEv'/>
<use f='llvm/build/tools/clang/include/clang/AST/AbstractTypeReader.inc' l='307' u='c' c='_ZN5clang13serialization18AbstractTypeReader23readDependentExtIntTypeEv'/>
<use f='llvm/build/tools/clang/include/clang/AST/AbstractTypeReader.inc' l='314' u='c' c='_ZN5clang13serialization18AbstractTypeReader21readDependentNameTypeEv'/>
<use f='llvm/build/tools/clang/include/clang/AST/AbstractTypeReader.inc' l='315' u='c' c='_ZN5clang13serialization18AbstractTypeReader21readDependentNameTypeEv'/>
<use f='llvm/build/tools/clang/include/clang/AST/AbstractTypeReader.inc' l='316' u='c' c='_ZN5clang13serialization18AbstractTypeReader21readDependentNameTypeEv'/>
<use f='llvm/build/tools/clang/include/clang/AST/AbstractTypeReader.inc' l='317' u='c' c='_ZN5clang13serialization18AbstractTypeReader21readDependentNameTypeEv'/>
<use f='llvm/build/tools/clang/include/clang/AST/AbstractTypeReader.inc' l='318' u='c' c='_ZN5clang13serialization18AbstractTypeReader21readDependentNameTypeEv'/>
<use f='llvm/build/tools/clang/include/clang/AST/AbstractTypeReader.inc' l='328' u='c' c='_ZN5clang13serialization18AbstractTypeReader31readDependentSizedExtVectorTypeEv'/>
<use f='llvm/build/tools/clang/include/clang/AST/AbstractTypeReader.inc' l='329' u='c' c='_ZN5clang13serialization18AbstractTypeReader31readDependentSizedExtVectorTypeEv'/>
<use f='llvm/build/tools/clang/include/clang/AST/AbstractTypeReader.inc' l='330' u='c' c='_ZN5clang13serialization18AbstractTypeReader31readDependentSizedExtVectorTypeEv'/>
<use f='llvm/build/tools/clang/include/clang/AST/AbstractTypeReader.inc' l='331' u='c' c='_ZN5clang13serialization18AbstractTypeReader31readDependentSizedExtVectorTypeEv'/>
<use f='llvm/build/tools/clang/include/clang/AST/AbstractTypeReader.inc' l='338' u='c' c='_ZN5clang13serialization18AbstractTypeReader39readDependentTemplateSpecializationTypeEv'/>
<use f='llvm/build/tools/clang/include/clang/AST/AbstractTypeReader.inc' l='339' u='c' c='_ZN5clang13serialization18AbstractTypeReader39readDependentTemplateSpecializationTypeEv'/>
<use f='llvm/build/tools/clang/include/clang/AST/AbstractTypeReader.inc' l='340' u='c' c='_ZN5clang13serialization18AbstractTypeReader39readDependentTemplateSpecializationTypeEv'/>
<use f='llvm/build/tools/clang/include/clang/AST/AbstractTypeReader.inc' l='341' u='c' c='_ZN5clang13serialization18AbstractTypeReader39readDependentTemplateSpecializationTypeEv'/>
<use f='llvm/build/tools/clang/include/clang/AST/AbstractTypeReader.inc' l='343' u='c' c='_ZN5clang13serialization18AbstractTypeReader39readDependentTemplateSpecializationTypeEv'/>
<use f='llvm/build/tools/clang/include/clang/AST/AbstractTypeReader.inc' l='351' u='c' c='_ZN5clang13serialization18AbstractTypeReader23readDependentVectorTypeEv'/>
<use f='llvm/build/tools/clang/include/clang/AST/AbstractTypeReader.inc' l='352' u='c' c='_ZN5clang13serialization18AbstractTypeReader23readDependentVectorTypeEv'/>
<use f='llvm/build/tools/clang/include/clang/AST/AbstractTypeReader.inc' l='353' u='c' c='_ZN5clang13serialization18AbstractTypeReader23readDependentVectorTypeEv'/>
<use f='llvm/build/tools/clang/include/clang/AST/AbstractTypeReader.inc' l='354' u='c' c='_ZN5clang13serialization18AbstractTypeReader23readDependentVectorTypeEv'/>
<use f='llvm/build/tools/clang/include/clang/AST/AbstractTypeReader.inc' l='355' u='c' c='_ZN5clang13serialization18AbstractTypeReader23readDependentVectorTypeEv'/>
<use f='llvm/build/tools/clang/include/clang/AST/AbstractTypeReader.inc' l='363' u='c' c='_ZN5clang13serialization18AbstractTypeReader18readElaboratedTypeEv'/>
<use f='llvm/build/tools/clang/include/clang/AST/AbstractTypeReader.inc' l='364' u='c' c='_ZN5clang13serialization18AbstractTypeReader18readElaboratedTypeEv'/>
<use f='llvm/build/tools/clang/include/clang/AST/AbstractTypeReader.inc' l='365' u='c' c='_ZN5clang13serialization18AbstractTypeReader18readElaboratedTypeEv'/>
<use f='llvm/build/tools/clang/include/clang/AST/AbstractTypeReader.inc' l='366' u='c' c='_ZN5clang13serialization18AbstractTypeReader18readElaboratedTypeEv'/>
<use f='llvm/build/tools/clang/include/clang/AST/AbstractTypeReader.inc' l='367' u='c' c='_ZN5clang13serialization18AbstractTypeReader18readElaboratedTypeEv'/>
<use f='llvm/build/tools/clang/include/clang/AST/AbstractTypeReader.inc' l='375' u='c' c='_ZN5clang13serialization18AbstractTypeReader14readExtIntTypeEv'/>
<use f='llvm/build/tools/clang/include/clang/AST/AbstractTypeReader.inc' l='376' u='c' c='_ZN5clang13serialization18AbstractTypeReader14readExtIntTypeEv'/>
<use f='llvm/build/tools/clang/include/clang/AST/AbstractTypeReader.inc' l='377' u='c' c='_ZN5clang13serialization18AbstractTypeReader14readExtIntTypeEv'/>
<use f='llvm/build/tools/clang/include/clang/AST/AbstractTypeReader.inc' l='384' u='c' c='_ZN5clang13serialization18AbstractTypeReader23readFunctionNoProtoTypeEv'/>
<use f='llvm/build/tools/clang/include/clang/AST/AbstractTypeReader.inc' l='385' u='c' c='_ZN5clang13serialization18AbstractTypeReader23readFunctionNoProtoTypeEv'/>
<use f='llvm/build/tools/clang/include/clang/AST/AbstractTypeReader.inc' l='386' u='c' c='_ZN5clang13serialization18AbstractTypeReader23readFunctionNoProtoTypeEv'/>
<use f='llvm/build/tools/clang/include/clang/AST/AbstractTypeReader.inc' l='387' u='c' c='_ZN5clang13serialization18AbstractTypeReader23readFunctionNoProtoTypeEv'/>
<use f='llvm/build/tools/clang/include/clang/AST/AbstractTypeReader.inc' l='388' u='c' c='_ZN5clang13serialization18AbstractTypeReader23readFunctionNoProtoTypeEv'/>
<use f='llvm/build/tools/clang/include/clang/AST/AbstractTypeReader.inc' l='389' u='c' c='_ZN5clang13serialization18AbstractTypeReader23readFunctionNoProtoTypeEv'/>
<use f='llvm/build/tools/clang/include/clang/AST/AbstractTypeReader.inc' l='390' u='c' c='_ZN5clang13serialization18AbstractTypeReader23readFunctionNoProtoTypeEv'/>
<use f='llvm/build/tools/clang/include/clang/AST/AbstractTypeReader.inc' l='391' u='c' c='_ZN5clang13serialization18AbstractTypeReader23readFunctionNoProtoTypeEv'/>
<use f='llvm/build/tools/clang/include/clang/AST/AbstractTypeReader.inc' l='392' u='c' c='_ZN5clang13serialization18AbstractTypeReader23readFunctionNoProtoTypeEv'/>
<use f='llvm/build/tools/clang/include/clang/AST/AbstractTypeReader.inc' l='393' u='c' c='_ZN5clang13serialization18AbstractTypeReader23readFunctionNoProtoTypeEv'/>
<use f='llvm/build/tools/clang/include/clang/AST/AbstractTypeReader.inc' l='404' u='c' c='_ZN5clang13serialization18AbstractTypeReader21readFunctionProtoTypeEv'/>
<use f='llvm/build/tools/clang/include/clang/AST/AbstractTypeReader.inc' l='405' u='c' c='_ZN5clang13serialization18AbstractTypeReader21readFunctionProtoTypeEv'/>
<use f='llvm/build/tools/clang/include/clang/AST/AbstractTypeReader.inc' l='406' u='c' c='_ZN5clang13serialization18AbstractTypeReader21readFunctionProtoTypeEv'/>
<use f='llvm/build/tools/clang/include/clang/AST/AbstractTypeReader.inc' l='407' u='c' c='_ZN5clang13serialization18AbstractTypeReader21readFunctionProtoTypeEv'/>
<use f='llvm/build/tools/clang/include/clang/AST/AbstractTypeReader.inc' l='408' u='c' c='_ZN5clang13serialization18AbstractTypeReader21readFunctionProtoTypeEv'/>
<use f='llvm/build/tools/clang/include/clang/AST/AbstractTypeReader.inc' l='410' u='c' c='_ZN5clang13serialization18AbstractTypeReader21readFunctionProtoTypeEv'/>
<use f='llvm/build/tools/clang/include/clang/AST/AbstractTypeReader.inc' l='412' u='c' c='_ZN5clang13serialization18AbstractTypeReader21readFunctionProtoTypeEv'/>
<use f='llvm/build/tools/clang/include/clang/AST/AbstractTypeReader.inc' l='414' u='c' c='_ZN5clang13serialization18AbstractTypeReader21readFunctionProtoTypeEv'/>
<use f='llvm/build/tools/clang/include/clang/AST/AbstractTypeReader.inc' l='415' u='c' c='_ZN5clang13serialization18AbstractTypeReader21readFunctionProtoTypeEv'/>
<use f='llvm/build/tools/clang/include/clang/AST/AbstractTypeReader.inc' l='416' u='c' c='_ZN5clang13serialization18AbstractTypeReader21readFunctionProtoTypeEv'/>
<use f='llvm/build/tools/clang/include/clang/AST/AbstractTypeReader.inc' l='417' u='c' c='_ZN5clang13serialization18AbstractTypeReader21readFunctionProtoTypeEv'/>
<use f='llvm/build/tools/clang/include/clang/AST/AbstractTypeReader.inc' l='418' u='c' c='_ZN5clang13serialization18AbstractTypeReader21readFunctionProtoTypeEv'/>
<use f='llvm/build/tools/clang/include/clang/AST/AbstractTypeReader.inc' l='419' u='c' c='_ZN5clang13serialization18AbstractTypeReader21readFunctionProtoTypeEv'/>
<use f='llvm/build/tools/clang/include/clang/AST/AbstractTypeReader.inc' l='420' u='c' c='_ZN5clang13serialization18AbstractTypeReader21readFunctionProtoTypeEv'/>
<use f='llvm/build/tools/clang/include/clang/AST/AbstractTypeReader.inc' l='421' u='c' c='_ZN5clang13serialization18AbstractTypeReader21readFunctionProtoTypeEv'/>
<use f='llvm/build/tools/clang/include/clang/AST/AbstractTypeReader.inc' l='422' u='c' c='_ZN5clang13serialization18AbstractTypeReader21readFunctionProtoTypeEv'/>
<use f='llvm/build/tools/clang/include/clang/AST/AbstractTypeReader.inc' l='423' u='c' c='_ZN5clang13serialization18AbstractTypeReader21readFunctionProtoTypeEv'/>
<use f='llvm/build/tools/clang/include/clang/AST/AbstractTypeReader.inc' l='443' u='c' c='_ZN5clang13serialization18AbstractTypeReader25readInjectedClassNameTypeEv'/>
<use f='llvm/build/tools/clang/include/clang/AST/AbstractTypeReader.inc' l='444' u='c' c='_ZN5clang13serialization18AbstractTypeReader25readInjectedClassNameTypeEv'/>
<use f='llvm/build/tools/clang/include/clang/AST/AbstractTypeReader.inc' l='445' u='c' c='_ZN5clang13serialization18AbstractTypeReader25readInjectedClassNameTypeEv'/>
<use f='llvm/build/tools/clang/include/clang/AST/AbstractTypeReader.inc' l='468' u='c' c='_ZN5clang13serialization18AbstractTypeReader22readMacroQualifiedTypeEv'/>
<use f='llvm/build/tools/clang/include/clang/AST/AbstractTypeReader.inc' l='469' u='c' c='_ZN5clang13serialization18AbstractTypeReader22readMacroQualifiedTypeEv'/>
<use f='llvm/build/tools/clang/include/clang/AST/AbstractTypeReader.inc' l='470' u='c' c='_ZN5clang13serialization18AbstractTypeReader22readMacroQualifiedTypeEv'/>
<use f='llvm/build/tools/clang/include/clang/AST/AbstractTypeReader.inc' l='477' u='c' c='_ZN5clang13serialization18AbstractTypeReader22readConstantMatrixTypeEv'/>
<use f='llvm/build/tools/clang/include/clang/AST/AbstractTypeReader.inc' l='478' u='c' c='_ZN5clang13serialization18AbstractTypeReader22readConstantMatrixTypeEv'/>
<use f='llvm/build/tools/clang/include/clang/AST/AbstractTypeReader.inc' l='479' u='c' c='_ZN5clang13serialization18AbstractTypeReader22readConstantMatrixTypeEv'/>
<use f='llvm/build/tools/clang/include/clang/AST/AbstractTypeReader.inc' l='480' u='c' c='_ZN5clang13serialization18AbstractTypeReader22readConstantMatrixTypeEv'/>
<use f='llvm/build/tools/clang/include/clang/AST/AbstractTypeReader.inc' l='487' u='c' c='_ZN5clang13serialization18AbstractTypeReader28readDependentSizedMatrixTypeEv'/>
<use f='llvm/build/tools/clang/include/clang/AST/AbstractTypeReader.inc' l='488' u='c' c='_ZN5clang13serialization18AbstractTypeReader28readDependentSizedMatrixTypeEv'/>
<use f='llvm/build/tools/clang/include/clang/AST/AbstractTypeReader.inc' l='489' u='c' c='_ZN5clang13serialization18AbstractTypeReader28readDependentSizedMatrixTypeEv'/>
<use f='llvm/build/tools/clang/include/clang/AST/AbstractTypeReader.inc' l='490' u='c' c='_ZN5clang13serialization18AbstractTypeReader28readDependentSizedMatrixTypeEv'/>
<use f='llvm/build/tools/clang/include/clang/AST/AbstractTypeReader.inc' l='491' u='c' c='_ZN5clang13serialization18AbstractTypeReader28readDependentSizedMatrixTypeEv'/>
<use f='llvm/build/tools/clang/include/clang/AST/AbstractTypeReader.inc' l='498' u='c' c='_ZN5clang13serialization18AbstractTypeReader21readMemberPointerTypeEv'/>
<use f='llvm/build/tools/clang/include/clang/AST/AbstractTypeReader.inc' l='499' u='c' c='_ZN5clang13serialization18AbstractTypeReader21readMemberPointerTypeEv'/>
<use f='llvm/build/tools/clang/include/clang/AST/AbstractTypeReader.inc' l='500' u='c' c='_ZN5clang13serialization18AbstractTypeReader21readMemberPointerTypeEv'/>
<use f='llvm/build/tools/clang/include/clang/AST/AbstractTypeReader.inc' l='507' u='c' c='_ZN5clang13serialization18AbstractTypeReader25readObjCObjectPointerTypeEv'/>
<use f='llvm/build/tools/clang/include/clang/AST/AbstractTypeReader.inc' l='508' u='c' c='_ZN5clang13serialization18AbstractTypeReader25readObjCObjectPointerTypeEv'/>
<use f='llvm/build/tools/clang/include/clang/AST/AbstractTypeReader.inc' l='515' u='c' c='_ZN5clang13serialization18AbstractTypeReader18readObjCObjectTypeEv'/>
<use f='llvm/build/tools/clang/include/clang/AST/AbstractTypeReader.inc' l='516' u='c' c='_ZN5clang13serialization18AbstractTypeReader18readObjCObjectTypeEv'/>
<use f='llvm/build/tools/clang/include/clang/AST/AbstractTypeReader.inc' l='518' u='c' c='_ZN5clang13serialization18AbstractTypeReader18readObjCObjectTypeEv'/>
<use f='llvm/build/tools/clang/include/clang/AST/AbstractTypeReader.inc' l='520' u='c' c='_ZN5clang13serialization18AbstractTypeReader18readObjCObjectTypeEv'/>
<use f='llvm/build/tools/clang/include/clang/AST/AbstractTypeReader.inc' l='521' u='c' c='_ZN5clang13serialization18AbstractTypeReader18readObjCObjectTypeEv'/>
<use f='llvm/build/tools/clang/include/clang/AST/AbstractTypeReader.inc' l='529' u='c' c='_ZN5clang13serialization18AbstractTypeReader21readObjCInterfaceTypeEv'/>
<use f='llvm/build/tools/clang/include/clang/AST/AbstractTypeReader.inc' l='530' u='c' c='_ZN5clang13serialization18AbstractTypeReader21readObjCInterfaceTypeEv'/>
<use f='llvm/build/tools/clang/include/clang/AST/AbstractTypeReader.inc' l='538' u='c' c='_ZN5clang13serialization18AbstractTypeReader21readObjCTypeParamTypeEv'/>
<use f='llvm/build/tools/clang/include/clang/AST/AbstractTypeReader.inc' l='539' u='c' c='_ZN5clang13serialization18AbstractTypeReader21readObjCTypeParamTypeEv'/>
<use f='llvm/build/tools/clang/include/clang/AST/AbstractTypeReader.inc' l='541' u='c' c='_ZN5clang13serialization18AbstractTypeReader21readObjCTypeParamTypeEv'/>
<use f='llvm/build/tools/clang/include/clang/AST/AbstractTypeReader.inc' l='548' u='c' c='_ZN5clang13serialization18AbstractTypeReader21readPackExpansionTypeEv'/>
<use f='llvm/build/tools/clang/include/clang/AST/AbstractTypeReader.inc' l='549' u='c' c='_ZN5clang13serialization18AbstractTypeReader21readPackExpansionTypeEv'/>
<use f='llvm/build/tools/clang/include/clang/AST/AbstractTypeReader.inc' l='550' u='c' c='_ZN5clang13serialization18AbstractTypeReader21readPackExpansionTypeEv'/>
<use f='llvm/build/tools/clang/include/clang/AST/AbstractTypeReader.inc' l='558' u='c' c='_ZN5clang13serialization18AbstractTypeReader13readParenTypeEv'/>
<use f='llvm/build/tools/clang/include/clang/AST/AbstractTypeReader.inc' l='559' u='c' c='_ZN5clang13serialization18AbstractTypeReader13readParenTypeEv'/>
<use f='llvm/build/tools/clang/include/clang/AST/AbstractTypeReader.inc' l='566' u='c' c='_ZN5clang13serialization18AbstractTypeReader12readPipeTypeEv'/>
<use f='llvm/build/tools/clang/include/clang/AST/AbstractTypeReader.inc' l='567' u='c' c='_ZN5clang13serialization18AbstractTypeReader12readPipeTypeEv'/>
<use f='llvm/build/tools/clang/include/clang/AST/AbstractTypeReader.inc' l='568' u='c' c='_ZN5clang13serialization18AbstractTypeReader12readPipeTypeEv'/>
<use f='llvm/build/tools/clang/include/clang/AST/AbstractTypeReader.inc' l='575' u='c' c='_ZN5clang13serialization18AbstractTypeReader15readPointerTypeEv'/>
<use f='llvm/build/tools/clang/include/clang/AST/AbstractTypeReader.inc' l='576' u='c' c='_ZN5clang13serialization18AbstractTypeReader15readPointerTypeEv'/>
<use f='llvm/build/tools/clang/include/clang/AST/AbstractTypeReader.inc' l='581' u='c' c='_ZN5clang13serialization18AbstractTypeReader23readLValueReferenceTypeEv'/>
<use f='llvm/build/tools/clang/include/clang/AST/AbstractTypeReader.inc' l='582' u='c' c='_ZN5clang13serialization18AbstractTypeReader23readLValueReferenceTypeEv'/>
<use f='llvm/build/tools/clang/include/clang/AST/AbstractTypeReader.inc' l='583' u='c' c='_ZN5clang13serialization18AbstractTypeReader23readLValueReferenceTypeEv'/>
<use f='llvm/build/tools/clang/include/clang/AST/AbstractTypeReader.inc' l='591' u='c' c='_ZN5clang13serialization18AbstractTypeReader23readRValueReferenceTypeEv'/>
<use f='llvm/build/tools/clang/include/clang/AST/AbstractTypeReader.inc' l='592' u='c' c='_ZN5clang13serialization18AbstractTypeReader23readRValueReferenceTypeEv'/>
<use f='llvm/build/tools/clang/include/clang/AST/AbstractTypeReader.inc' l='599' u='c' c='_ZN5clang13serialization18AbstractTypeReader33readSubstTemplateTypeParmPackTypeEv'/>
<use f='llvm/build/tools/clang/include/clang/AST/AbstractTypeReader.inc' l='600' u='c' c='_ZN5clang13serialization18AbstractTypeReader33readSubstTemplateTypeParmPackTypeEv'/>
<use f='llvm/build/tools/clang/include/clang/AST/AbstractTypeReader.inc' l='601' u='c' c='_ZN5clang13serialization18AbstractTypeReader33readSubstTemplateTypeParmPackTypeEv'/>
<use f='llvm/build/tools/clang/include/clang/AST/AbstractTypeReader.inc' l='610' u='c' c='_ZN5clang13serialization18AbstractTypeReader29readSubstTemplateTypeParmTypeEv'/>
<use f='llvm/build/tools/clang/include/clang/AST/AbstractTypeReader.inc' l='611' u='c' c='_ZN5clang13serialization18AbstractTypeReader29readSubstTemplateTypeParmTypeEv'/>
<use f='llvm/build/tools/clang/include/clang/AST/AbstractTypeReader.inc' l='612' u='c' c='_ZN5clang13serialization18AbstractTypeReader29readSubstTemplateTypeParmTypeEv'/>
<use f='llvm/build/tools/clang/include/clang/AST/AbstractTypeReader.inc' l='622' u='c' c='_ZN5clang13serialization18AbstractTypeReader12readEnumTypeEv'/>
<use f='llvm/build/tools/clang/include/clang/AST/AbstractTypeReader.inc' l='623' u='c' c='_ZN5clang13serialization18AbstractTypeReader12readEnumTypeEv'/>
<use f='llvm/build/tools/clang/include/clang/AST/AbstractTypeReader.inc' l='624' u='c' c='_ZN5clang13serialization18AbstractTypeReader12readEnumTypeEv'/>
<use f='llvm/build/tools/clang/include/clang/AST/AbstractTypeReader.inc' l='635' u='c' c='_ZN5clang13serialization18AbstractTypeReader14readRecordTypeEv'/>
<use f='llvm/build/tools/clang/include/clang/AST/AbstractTypeReader.inc' l='636' u='c' c='_ZN5clang13serialization18AbstractTypeReader14readRecordTypeEv'/>
<use f='llvm/build/tools/clang/include/clang/AST/AbstractTypeReader.inc' l='637' u='c' c='_ZN5clang13serialization18AbstractTypeReader14readRecordTypeEv'/>
<use f='llvm/build/tools/clang/include/clang/AST/AbstractTypeReader.inc' l='649' u='c' c='_ZN5clang13serialization18AbstractTypeReader30readTemplateSpecializationTypeEv'/>
<use f='llvm/build/tools/clang/include/clang/AST/AbstractTypeReader.inc' l='650' u='c' c='_ZN5clang13serialization18AbstractTypeReader30readTemplateSpecializationTypeEv'/>
<use f='llvm/build/tools/clang/include/clang/AST/AbstractTypeReader.inc' l='651' u='c' c='_ZN5clang13serialization18AbstractTypeReader30readTemplateSpecializationTypeEv'/>
<use f='llvm/build/tools/clang/include/clang/AST/AbstractTypeReader.inc' l='653' u='c' c='_ZN5clang13serialization18AbstractTypeReader30readTemplateSpecializationTypeEv'/>
<use f='llvm/build/tools/clang/include/clang/AST/AbstractTypeReader.inc' l='654' u='c' c='_ZN5clang13serialization18AbstractTypeReader30readTemplateSpecializationTypeEv'/>
<use f='llvm/build/tools/clang/include/clang/AST/AbstractTypeReader.inc' l='673' u='c' c='_ZN5clang13serialization18AbstractTypeReader24readTemplateTypeParmTypeEv'/>
<use f='llvm/build/tools/clang/include/clang/AST/AbstractTypeReader.inc' l='674' u='c' c='_ZN5clang13serialization18AbstractTypeReader24readTemplateTypeParmTypeEv'/>
<use f='llvm/build/tools/clang/include/clang/AST/AbstractTypeReader.inc' l='675' u='c' c='_ZN5clang13serialization18AbstractTypeReader24readTemplateTypeParmTypeEv'/>
<use f='llvm/build/tools/clang/include/clang/AST/AbstractTypeReader.inc' l='676' u='c' c='_ZN5clang13serialization18AbstractTypeReader24readTemplateTypeParmTypeEv'/>
<use f='llvm/build/tools/clang/include/clang/AST/AbstractTypeReader.inc' l='677' u='c' c='_ZN5clang13serialization18AbstractTypeReader24readTemplateTypeParmTypeEv'/>
<use f='llvm/build/tools/clang/include/clang/AST/AbstractTypeReader.inc' l='685' u='c' c='_ZN5clang13serialization18AbstractTypeReader18readTypeOfExprTypeEv'/>
<use f='llvm/build/tools/clang/include/clang/AST/AbstractTypeReader.inc' l='686' u='c' c='_ZN5clang13serialization18AbstractTypeReader18readTypeOfExprTypeEv'/>
<use f='llvm/build/tools/clang/include/clang/AST/AbstractTypeReader.inc' l='693' u='c' c='_ZN5clang13serialization18AbstractTypeReader14readTypeOfTypeEv'/>
<use f='llvm/build/tools/clang/include/clang/AST/AbstractTypeReader.inc' l='694' u='c' c='_ZN5clang13serialization18AbstractTypeReader14readTypeOfTypeEv'/>
<use f='llvm/build/tools/clang/include/clang/AST/AbstractTypeReader.inc' l='701' u='c' c='_ZN5clang13serialization18AbstractTypeReader15readTypedefTypeEv'/>
<use f='llvm/build/tools/clang/include/clang/AST/AbstractTypeReader.inc' l='702' u='c' c='_ZN5clang13serialization18AbstractTypeReader15readTypedefTypeEv'/>
<use f='llvm/build/tools/clang/include/clang/AST/AbstractTypeReader.inc' l='703' u='c' c='_ZN5clang13serialization18AbstractTypeReader15readTypedefTypeEv'/>
<use f='llvm/build/tools/clang/include/clang/AST/AbstractTypeReader.inc' l='714' u='c' c='_ZN5clang13serialization18AbstractTypeReader22readUnaryTransformTypeEv'/>
<use f='llvm/build/tools/clang/include/clang/AST/AbstractTypeReader.inc' l='715' u='c' c='_ZN5clang13serialization18AbstractTypeReader22readUnaryTransformTypeEv'/>
<use f='llvm/build/tools/clang/include/clang/AST/AbstractTypeReader.inc' l='716' u='c' c='_ZN5clang13serialization18AbstractTypeReader22readUnaryTransformTypeEv'/>
<use f='llvm/build/tools/clang/include/clang/AST/AbstractTypeReader.inc' l='717' u='c' c='_ZN5clang13serialization18AbstractTypeReader22readUnaryTransformTypeEv'/>
<use f='llvm/build/tools/clang/include/clang/AST/AbstractTypeReader.inc' l='724' u='c' c='_ZN5clang13serialization18AbstractTypeReader23readUnresolvedUsingTypeEv'/>
<use f='llvm/build/tools/clang/include/clang/AST/AbstractTypeReader.inc' l='725' u='c' c='_ZN5clang13serialization18AbstractTypeReader23readUnresolvedUsingTypeEv'/>
<use f='llvm/build/tools/clang/include/clang/AST/AbstractTypeReader.inc' l='732' u='c' c='_ZN5clang13serialization18AbstractTypeReader14readVectorTypeEv'/>
<use f='llvm/build/tools/clang/include/clang/AST/AbstractTypeReader.inc' l='733' u='c' c='_ZN5clang13serialization18AbstractTypeReader14readVectorTypeEv'/>
<use f='llvm/build/tools/clang/include/clang/AST/AbstractTypeReader.inc' l='734' u='c' c='_ZN5clang13serialization18AbstractTypeReader14readVectorTypeEv'/>
<use f='llvm/build/tools/clang/include/clang/AST/AbstractTypeReader.inc' l='735' u='c' c='_ZN5clang13serialization18AbstractTypeReader14readVectorTypeEv'/>
<use f='llvm/build/tools/clang/include/clang/AST/AbstractTypeReader.inc' l='742' u='c' c='_ZN5clang13serialization18AbstractTypeReader17readExtVectorTypeEv'/>
<use f='llvm/build/tools/clang/include/clang/AST/AbstractTypeReader.inc' l='743' u='c' c='_ZN5clang13serialization18AbstractTypeReader17readExtVectorTypeEv'/>
<use f='llvm/build/tools/clang/include/clang/AST/AbstractTypeReader.inc' l='744' u='c' c='_ZN5clang13serialization18AbstractTypeReader17readExtVectorTypeEv'/>
