<dec f='llvm/clang/lib/AST/Interp/EvalEmitter.h' l='89' type='clang::interp::InterpState'/>
<offset>2816</offset>
<doc f='llvm/clang/lib/AST/Interp/EvalEmitter.h' l='88'>/// Callee evaluation state.</doc>
<use f='llvm/clang/lib/AST/Interp/EvalEmitter.cpp' l='24' u='w' c='_ZN5clang6interp11EvalEmitterC1ERNS0_7ContextERNS0_7ProgramERNS0_5StateERNS0_11InterpStackERNS_7APValueE'/>
<use f='llvm/clang/lib/AST/Interp/EvalEmitter.cpp' l='26' u='m' c='_ZN5clang6interp11EvalEmitterC1ERNS0_7ContextERNS0_7ProgramERNS0_5StateERNS0_11InterpStackERNS_7APValueE'/>
<use f='llvm/clang/lib/AST/Interp/EvalEmitter.cpp' l='26' u='a' c='_ZN5clang6interp11EvalEmitterC1ERNS0_7ContextERNS0_7ProgramERNS0_5StateERNS0_11InterpStackERNS_7APValueE'/>
<use f='llvm/clang/lib/AST/Interp/EvalEmitter.cpp' l='71' u='m' c='_ZN5clang6interp11EvalEmitter8jumpTrueERKj'/>
<use f='llvm/clang/lib/AST/Interp/EvalEmitter.cpp' l='79' u='m' c='_ZN5clang6interp11EvalEmitter9jumpFalseERKj'/>
<use f='llvm/clang/lib/AST/Interp/EvalEmitter.cpp' l='102' u='m' c='_ZN5clang6interp11EvalEmitter7emitRetERKNS0_10SourceInfoE'/>
<use f='llvm/clang/lib/AST/Interp/EvalEmitter.cpp' l='192' u='m' c='_ZN5clang6interp11EvalEmitter12emitRetValueERKNS0_10SourceInfoE'/>
<use f='llvm/clang/lib/AST/Interp/EvalEmitter.cpp' l='202' u='m' c='_ZN5clang6interp11EvalEmitter15emitGetPtrLocalEjRKNS0_10SourceInfoE'/>
<use f='llvm/clang/lib/AST/Interp/EvalEmitter.cpp' l='216' u='m' c='_ZN5clang6interp11EvalEmitter12emitGetLocalEjRKNS0_10SourceInfoE'/>
<use f='llvm/clang/lib/AST/Interp/EvalEmitter.cpp' l='230' u='m' c='_ZN5clang6interp11EvalEmitter12emitSetLocalEjRKNS0_10SourceInfoE'/>
<use f='llvm/clang/lib/AST/Interp/EvalEmitter.cpp' l='241' u='m' c='_ZN5clang6interp11EvalEmitter11emitDestroyEjRKNS0_10SourceInfoE'/>
