<dec f='llvm/clang/include/clang/Sema/Sema.h' l='970' type='clang::Sema &amp;'/>
<use f='llvm/clang/include/clang/Sema/Sema.h' l='979' u='w' c='_ZN5clang4Sema11ContextRAIIC1ERS0_PNS_11DeclContextEb'/>
<use f='llvm/clang/include/clang/Sema/Sema.h' l='996' u='m' c='_ZN5clang4Sema11ContextRAII3popEv'/>
<use f='llvm/clang/include/clang/Sema/Sema.h' l='997' u='m' c='_ZN5clang4Sema11ContextRAII3popEv'/>
<use f='llvm/clang/include/clang/Sema/Sema.h' l='998' u='m' c='_ZN5clang4Sema11ContextRAII3popEv'/>
<use f='llvm/clang/include/clang/Sema/Sema.h' l='999' u='m' c='_ZN5clang4Sema11ContextRAII3popEv'/>
<use f='llvm/clang/include/clang/Sema/Sema.h' l='1000' u='m' c='_ZN5clang4Sema11ContextRAII3popEv'/>
<offset>0</offset>
