<dec f='llvm/clang/include/clang/Serialization/ASTReader.h' l='553' type='clang::ASTReader::ModuleFile *'/>
<use f='llvm/clang/include/clang/Serialization/ASTReader.h' l='558' u='w' c='_ZN5clang9ASTReader13FileDeclsInfoC1EPNS_13serialization10ModuleFileEN4llvm8ArrayRefIjEE'/>
<offset>0</offset>
<use f='llvm/clang/lib/Serialization/ASTReader.cpp' l='7591' u='r' c='_ZN5clang9ASTReader19FindFileRegionDeclsENS_6FileIDEjjRN4llvm15SmallVectorImplIPNS_4DeclEEE'/>
<use f='llvm/clang/lib/Serialization/ASTReader.cpp' l='7601' u='r' c='_ZN5clang9ASTReader19FindFileRegionDeclsENS_6FileIDEjjRN4llvm15SmallVectorImplIPNS_4DeclEEE'/>
<use f='llvm/clang/lib/Serialization/ASTReader.cpp' l='7612' u='r' c='_ZN5clang9ASTReader19FindFileRegionDeclsENS_6FileIDEjjRN4llvm15SmallVectorImplIPNS_4DeclEEE'/>
