<dec f='llvm/clang/include/clang/Parse/Parser.h' l='2972' type='clang::CXXScopeSpec'/>
<use f='llvm/clang/include/clang/Parse/Parser.h' l='2978' u='m' c='_ZN5clang6Parser15UsingDeclarator5clearEv'/>
<offset>64</offset>
<use f='llvm/clang/lib/Parse/ParseDeclCXX.cpp' l='604' u='a' c='_ZN5clang6Parser20ParseUsingDeclaratorENS_17DeclaratorContextERNS0_15UsingDeclaratorE'/>
<use f='llvm/clang/lib/Parse/ParseDeclCXX.cpp' l='614' u='m' c='_ZN5clang6Parser20ParseUsingDeclaratorENS_17DeclaratorContextERNS0_15UsingDeclaratorE'/>
<use f='llvm/clang/lib/Parse/ParseDeclCXX.cpp' l='631' u='m' c='_ZN5clang6Parser20ParseUsingDeclaratorENS_17DeclaratorContextERNS0_15UsingDeclaratorE'/>
<use f='llvm/clang/lib/Parse/ParseDeclCXX.cpp' l='632' u='m' c='_ZN5clang6Parser20ParseUsingDeclaratorENS_17DeclaratorContextERNS0_15UsingDeclaratorE'/>
<use f='llvm/clang/lib/Parse/ParseDeclCXX.cpp' l='633' u='m' c='_ZN5clang6Parser20ParseUsingDeclaratorENS_17DeclaratorContextERNS0_15UsingDeclaratorE'/>
<use f='llvm/clang/lib/Parse/ParseDeclCXX.cpp' l='636' u='a' c='_ZN5clang6Parser20ParseUsingDeclaratorENS_17DeclaratorContextERNS0_15UsingDeclaratorE'/>
<use f='llvm/clang/lib/Parse/ParseDeclCXX.cpp' l='640' u='a' c='_ZN5clang6Parser20ParseUsingDeclaratorENS_17DeclaratorContextERNS0_15UsingDeclaratorE'/>
<use f='llvm/clang/lib/Parse/ParseDeclCXX.cpp' l='753' u='a' c='_ZN5clang6Parser21ParseUsingDeclarationENS_17DeclaratorContextERKNS0_18ParsedTemplateInfoENS_14SourceLocationERS5_NS_15AccessSpecifierE'/>
<use f='llvm/clang/lib/Parse/ParseDeclCXX.cpp' l='827' u='m' c='_ZN5clang6Parser36ParseAliasDeclarationAfterDeclaratorERKNS0_18ParsedTemplateInfoENS_14SourceLocationERNS0_15UsingDeclaratorERS4_NS_15AccessSpecifierE13354100'/>
<use f='llvm/clang/lib/Parse/ParseDeclCXX.cpp' l='827' u='m' c='_ZN5clang6Parser36ParseAliasDeclarationAfterDeclaratorERKNS0_18ParsedTemplateInfoENS_14SourceLocationERNS0_15UsingDeclaratorERS4_NS_15AccessSpecifierE13354100'/>
<use f='llvm/clang/lib/Parse/ParseDeclCXX.cpp' l='828' u='m' c='_ZN5clang6Parser36ParseAliasDeclarationAfterDeclaratorERKNS0_18ParsedTemplateInfoENS_14SourceLocationERNS0_15UsingDeclaratorERS4_NS_15AccessSpecifierE13354100'/>
<use f='llvm/clang/lib/Parse/ParseDeclCXX.cpp' l='829' u='m' c='_ZN5clang6Parser36ParseAliasDeclarationAfterDeclaratorERKNS0_18ParsedTemplateInfoENS_14SourceLocationERNS0_15UsingDeclaratorERS4_NS_15AccessSpecifierE13354100'/>
<use f='llvm/clang/lib/Parse/ParseDeclCXX.cpp' l='830' u='m' c='_ZN5clang6Parser36ParseAliasDeclarationAfterDeclaratorERKNS0_18ParsedTemplateInfoENS_14SourceLocationERNS0_15UsingDeclaratorERS4_NS_15AccessSpecifierE13354100'/>
