<dec f='llvm/clang/include/clang/Index/IndexSymbol.h' l='66' type='3'/>
<use f='llvm/clang/lib/Index/IndexSymbol.cpp' l='392' u='r' c='_ZN5clang5index13getSymbolInfoEPKNS_4DeclE'/>
<use f='llvm/clang/lib/Index/IndexSymbol.cpp' l='554' c='_ZN5clang5index23getSymbolLanguageStringENS0_14SymbolLanguageE'/>
<use f='llvm/clang/tools/libclang/CXIndexDataConsumer.cpp' l='1309' c='_ZL27getEntityLangFromSymbolLangN5clang5index14SymbolLanguageE'/>
