<dec f='llvm/clang/include/clang/StaticAnalyzer/Core/BugReporter/BugReporter.h' l='580' type='clang::ento::BugReporterData &amp;'/>
<use f='llvm/clang/include/clang/StaticAnalyzer/Core/BugReporter/BugReporter.h' l='599' u='m' c='_ZN5clang4ento11BugReporter26getPathDiagnosticConsumersEv'/>
<use f='llvm/clang/include/clang/StaticAnalyzer/Core/BugReporter/BugReporter.h' l='607' u='m' c='_ZN5clang4ento11BugReporter10getContextEv'/>
<use f='llvm/clang/include/clang/StaticAnalyzer/Core/BugReporter/BugReporter.h' l='609' u='m' c='_ZN5clang4ento11BugReporter16getSourceManagerEv'/>
<use f='llvm/clang/include/clang/StaticAnalyzer/Core/BugReporter/BugReporter.h' l='611' u='m' c='_ZN5clang4ento11BugReporter18getAnalyzerOptionsEv'/>
<use f='llvm/clang/include/clang/StaticAnalyzer/Core/BugReporter/BugReporter.h' l='613' u='m' c='_ZN5clang4ento11BugReporter15getPreprocessorEv'/>
<offset>64</offset>
<use f='llvm/clang/lib/StaticAnalyzer/Core/BugReporter.cpp' l='2441' u='w' c='_ZN5clang4ento11BugReporterC1ERNS0_15BugReporterDataE'/>
