<dec f='llvm/clang/lib/Driver/ToolChains/ROCm.h' l='89' type='SmallString&lt;0&gt;'/>
<use f='llvm/clang/lib/Driver/ToolChains/ROCm.h' l='99' u='m' c='_ZNK5clang6driver24RocmInstallationDetector19allGenericLibsValidEv'/>
<use f='llvm/clang/lib/Driver/ToolChains/ROCm.h' l='166' u='m' c='_ZNK5clang6driver24RocmInstallationDetector10getHIPPathEv'/>
<offset>3200</offset>
<use f='llvm/clang/lib/Driver/ToolChains/AMDGPU.cpp' l='52' u='w' c='_ZN5clang6driver24RocmInstallationDetector17scanLibDevicePathEN4llvm9StringRefE'/>
