<dec f='llvm/clang/unittests/Tooling/Syntax/TreeTestBase.h' l='45' type='IntrusiveRefCntPtr&lt;llvm::vfs::InMemoryFileSystem&gt;'/>
<use f='llvm/clang/unittests/Tooling/Syntax/TreeTestBase.h' l='48' u='r'/>
<offset>320</offset>
<use f='llvm/clang/unittests/Tooling/Syntax/TreeTestBase.cpp' l='117' u='m' c='_ZN5clang6syntax14SyntaxTreeTest9buildTreeEN4llvm9StringRefERKNS_15TestClangConfigE'/>
<use f='llvm/clang/unittests/Tooling/Syntax/TreeTestBase.cpp' l='137' u='r' c='_ZN5clang6syntax14SyntaxTreeTest9buildTreeEN4llvm9StringRefERKNS_15TestClangConfigE'/>
