<dec f='llvm/clang/include/clang/AST/ASTDumper.h' l='22' type='llvm::raw_ostream &amp;'/>
<use f='llvm/clang/include/clang/AST/ASTDumper.h' l='28' u='w' c='_ZN5clang9ASTDumperC1ERN4llvm11raw_ostreamERKNS_10ASTContextEb'/>
<use f='llvm/clang/include/clang/AST/ASTDumper.h' l='31' u='w' c='_ZN5clang9ASTDumperC1ERN4llvm11raw_ostreamEb'/>
<use f='llvm/clang/lib/AST/ASTDumper.cpp' l='27' u='m' c='_ZN5clang9ASTDumper11dumpLookupsEPKNS_11DeclContextEb'/>
<use f='llvm/clang/lib/AST/ASTDumper.cpp' l='32' u='m' c='_ZN5clang9ASTDumper11dumpLookupsEPKNS_11DeclContextEb'/>
<use f='llvm/clang/lib/AST/ASTDumper.cpp' l='46' u='m' c='_ZN5clang9ASTDumper11dumpLookupsEPKNS_11DeclContextEb'/>
<use f='llvm/clang/lib/AST/ASTDumper.cpp' l='48' u='a' c='_ZN5clang9ASTDumper11dumpLookupsEPKNS_11DeclContextEb'/>
<use f='llvm/clang/lib/AST/ASTDumper.cpp' l='49' u='m' c='_ZN5clang9ASTDumper11dumpLookupsEPKNS_11DeclContextEb'/>
<use f='llvm/clang/lib/AST/ASTDumper.cpp' l='58' u='m' c='_ZN5clang9ASTDumper11dumpLookupsEPKNS_11DeclContextEb'/>
<use f='llvm/clang/lib/AST/ASTDumper.cpp' l='77' u='a' c='_ZN5clang9ASTDumper11dumpLookupsEPKNS_11DeclContextEb'/>
<use f='llvm/clang/lib/AST/ASTDumper.cpp' l='78' u='m' c='_ZN5clang9ASTDumper11dumpLookupsEPKNS_11DeclContextEb'/>
<offset>9408</offset>
