<dec f='llvm/clang/include/clang/AST/Decl.h' l='877' type='clang::VarDecl::InitType'/>
<offset>704</offset>
<doc f='llvm/clang/include/clang/AST/Decl.h' l='875'>/// The initializer for this variable or, for a ParmVarDecl, the
  /// C++ default argument.</doc>
<use f='llvm/clang/lib/AST/Decl.cpp' l='2242' u='m' c='_ZNK5clang7VarDecl7hasInitEv'/>
<use f='llvm/clang/lib/AST/Decl.cpp' l='2249' u='m' c='_ZN5clang7VarDecl7getInitEv'/>
<use f='llvm/clang/lib/AST/Decl.cpp' l='2252' u='m' c='_ZN5clang7VarDecl7getInitEv'/>
<use f='llvm/clang/lib/AST/Decl.cpp' l='2256' u='m' c='_ZN5clang7VarDecl14getInitAddressEv'/>
<use f='llvm/clang/lib/AST/Decl.cpp' l='2259' u='m' c='_ZN5clang7VarDecl14getInitAddressEv'/>
<use f='llvm/clang/lib/AST/Decl.cpp' l='2294' u='m' c='_ZN5clang7VarDecl7setInitEPNS_4ExprE'/>
<use f='llvm/clang/lib/AST/Decl.cpp' l='2299' u='w' c='_ZN5clang7VarDecl7setInitEPNS_4ExprE'/>
<use f='llvm/clang/lib/AST/Decl.cpp' l='2368' u='m' c='_ZNK5clang7VarDecl19ensureEvaluatedStmtEv'/>
<use f='llvm/clang/lib/AST/Decl.cpp' l='2375' u='m' c='_ZNK5clang7VarDecl19ensureEvaluatedStmtEv'/>
<use f='llvm/clang/lib/AST/Decl.cpp' l='2376' u='w' c='_ZNK5clang7VarDecl19ensureEvaluatedStmtEv'/>
<use f='llvm/clang/lib/AST/Decl.cpp' l='2382' u='m' c='_ZNK5clang7VarDecl16getEvaluatedStmtEv'/>
<use f='llvm/clang/lib/AST/Decl.cpp' l='2763' u='w' c='_ZN5clang11ParmVarDecl13setDefaultArgEPNS_4ExprE'/>
<use f='llvm/clang/lib/AST/Decl.cpp' l='2788' u='w' c='_ZN5clang11ParmVarDecl27setUninstantiatedDefaultArgEPNS_4ExprE'/>
<use f='llvm/clang/lib/AST/Decl.cpp' l='2794' u='m' c='_ZN5clang11ParmVarDecl27getUninstantiatedDefaultArgEv'/>
<use f='llvm/clang/lib/AST/Decl.cpp' l='2802' u='m' c='_ZNK5clang11ParmVarDecl13hasDefaultArgEv'/>
