<dec f='llvm/clang/lib/Driver/ToolChains/Cuda.h' l='30' type='const clang::driver::Driver &amp;'/>
<offset>0</offset>
<use f='llvm/clang/lib/Driver/ToolChains/Cuda.cpp' l='113' u='m' c='_ZN5clang6driver24CudaInstallationDetector24WarnIfUnsupportedVersionEv'/>
<use f='llvm/clang/lib/Driver/ToolChains/Cuda.cpp' l='121' u='w' c='_ZN5clang6driver24CudaInstallationDetectorC1ERKNS0_6DriverERKN4llvm6TripleERKNS5_3opt7ArgListE'/>
<use f='llvm/clang/lib/Driver/ToolChains/Cuda.cpp' l='305' u='m' c='_ZNK5clang6driver24CudaInstallationDetector18AddCudaIncludeArgsERKN4llvm3opt7ArgListERNS2_11SmallVectorIPKcLj16EEE'/>
<use f='llvm/clang/lib/Driver/ToolChains/Cuda.cpp' l='316' u='m' c='_ZNK5clang6driver24CudaInstallationDetector18AddCudaIncludeArgsERKN4llvm3opt7ArgListERNS2_11SmallVectorIPKcLj16EEE'/>
<use f='llvm/clang/lib/Driver/ToolChains/Cuda.cpp' l='336' u='m' c='_ZNK5clang6driver24CudaInstallationDetector28CheckCudaVersionSupportsArchENS_8CudaArchE'/>
