<dec f='llvm/clang/include/clang/Sema/DeclSpec.h' l='1551' type='clang::DeclaratorChunk::ArrayTypeInfo'/>
<use f='llvm/clang/include/clang/Sema/DeclSpec.h' l='1564' u='m' c='_ZN5clang15DeclaratorChunk7destroyEv'/>
<use f='llvm/clang/include/clang/Sema/DeclSpec.h' l='1615' u='m' c='_ZN5clang15DeclaratorChunk8getArrayEjbbPNS_4ExprENS_14SourceLocationES3_'/>
<use f='llvm/clang/include/clang/Sema/DeclSpec.h' l='1616' u='m' c='_ZN5clang15DeclaratorChunk8getArrayEjbbPNS_4ExprENS_14SourceLocationES3_'/>
<use f='llvm/clang/include/clang/Sema/DeclSpec.h' l='1617' u='m' c='_ZN5clang15DeclaratorChunk8getArrayEjbbPNS_4ExprENS_14SourceLocationES3_'/>
<use f='llvm/clang/include/clang/Sema/DeclSpec.h' l='1618' u='m' c='_ZN5clang15DeclaratorChunk8getArrayEjbbPNS_4ExprENS_14SourceLocationES3_'/>
<use f='llvm/clang/include/clang/Sema/DeclSpec.h' l='2291' u='m' c='_ZNK5clang10Declarator21isArrayOfUnknownBoundEv'/>
<offset>0</offset>
<use f='llvm/clang/lib/Sema/SemaExprCXX.cpp' l='1769' u='m' c='_ZN5clang4Sema11ActOnCXXNewENS_14SourceLocationEbS1_N4llvm15MutableArrayRefIPNS_4ExprEEES1_NS_11SourceRangeERNS_10DeclaratorES5_'/>
<use f='llvm/clang/lib/Sema/SemaExprCXX.cpp' l='1772' u='m' c='_ZN5clang4Sema11ActOnCXXNewENS_14SourceLocationEbS1_N4llvm15MutableArrayRefIPNS_4ExprEEES1_NS_11SourceRangeERNS_10DeclaratorES5_'/>
<use f='llvm/clang/lib/Sema/SemaExprCXX.cpp' l='1776' u='m' c='_ZN5clang4Sema11ActOnCXXNewENS_14SourceLocationEbS1_N4llvm15MutableArrayRefIPNS_4ExprEEES1_NS_11SourceRangeERNS_10DeclaratorES5_'/>
<use f='llvm/clang/lib/Sema/SemaExprCXX.cpp' l='1786' u='a' c='_ZN5clang4Sema11ActOnCXXNewENS_14SourceLocationEbS1_N4llvm15MutableArrayRefIPNS_4ExprEEES1_NS_11SourceRangeERNS_10DeclaratorES5_'/>
<use f='llvm/clang/lib/Sema/SemaTemplateVariadic.cpp' l='928' u='m' c='_ZN5clang4Sema32containsUnexpandedParameterPacksERNS_10DeclaratorE'/>
<use f='llvm/clang/lib/Sema/SemaTemplateVariadic.cpp' l='929' u='m' c='_ZN5clang4Sema32containsUnexpandedParameterPacksERNS_10DeclaratorE'/>
<use f='llvm/clang/lib/Sema/SemaType.cpp' l='3707' u='m' c='_ZL24warnAboutRedundantParensRN5clang4SemaERNS_10DeclaratorENS_8QualTypeE'/>
<use f='llvm/clang/lib/Sema/SemaType.cpp' l='4832' u='a' c='_ZL24GetFullTypeForDeclaratorRN12_GLOBAL__N_119TypeProcessingStateEN5clang8QualTypeEPNS2_14TypeSourceInfoE'/>
<use f='llvm/clang/lib/Sema/SemaType.cpp' l='6107' u='m' c='_ZN12_GLOBAL__N_119DeclaratorLocFiller17VisitArrayTypeLocEN5clang12ArrayTypeLocE'/>
