<dec f='llvm/clang/include/clang/Index/IndexSymbol.h' l='65' type='2'/>
<use f='llvm/clang/lib/Index/IndexSymbol.cpp' l='102' u='r' c='_ZN5clang5index13getSymbolInfoEPKNS_4DeclE'/>
<use f='llvm/clang/lib/Index/IndexSymbol.cpp' l='115' u='r' c='_ZN5clang5index13getSymbolInfoEPKNS_4DeclE'/>
<use f='llvm/clang/lib/Index/IndexSymbol.cpp' l='119' u='r' c='_ZN5clang5index13getSymbolInfoEPKNS_4DeclE'/>
<use f='llvm/clang/lib/Index/IndexSymbol.cpp' l='127' u='r' c='_ZN5clang5index13getSymbolInfoEPKNS_4DeclE'/>
<use f='llvm/clang/lib/Index/IndexSymbol.cpp' l='150' u='r' c='_ZN5clang5index13getSymbolInfoEPKNS_4DeclE'/>
<use f='llvm/clang/lib/Index/IndexSymbol.cpp' l='154' u='r' c='_ZN5clang5index13getSymbolInfoEPKNS_4DeclE'/>
<use f='llvm/clang/lib/Index/IndexSymbol.cpp' l='159' u='r' c='_ZN5clang5index13getSymbolInfoEPKNS_4DeclE'/>
<use f='llvm/clang/lib/Index/IndexSymbol.cpp' l='164' u='r' c='_ZN5clang5index13getSymbolInfoEPKNS_4DeclE'/>
<use f='llvm/clang/lib/Index/IndexSymbol.cpp' l='184' u='r' c='_ZN5clang5index13getSymbolInfoEPKNS_4DeclE'/>
<use f='llvm/clang/lib/Index/IndexSymbol.cpp' l='249' u='r' c='_ZN5clang5index13getSymbolInfoEPKNS_4DeclE'/>
<use f='llvm/clang/lib/Index/IndexSymbol.cpp' l='253' u='r' c='_ZN5clang5index13getSymbolInfoEPKNS_4DeclE'/>
<use f='llvm/clang/lib/Index/IndexSymbol.cpp' l='257' u='r' c='_ZN5clang5index13getSymbolInfoEPKNS_4DeclE'/>
<use f='llvm/clang/lib/Index/IndexSymbol.cpp' l='267' u='r' c='_ZN5clang5index13getSymbolInfoEPKNS_4DeclE'/>
<use f='llvm/clang/lib/Index/IndexSymbol.cpp' l='271' u='r' c='_ZN5clang5index13getSymbolInfoEPKNS_4DeclE'/>
<use f='llvm/clang/lib/Index/IndexSymbol.cpp' l='279' u='r' c='_ZN5clang5index13getSymbolInfoEPKNS_4DeclE'/>
<use f='llvm/clang/lib/Index/IndexSymbol.cpp' l='285' u='r' c='_ZN5clang5index13getSymbolInfoEPKNS_4DeclE'/>
<use f='llvm/clang/lib/Index/IndexSymbol.cpp' l='290' u='r' c='_ZN5clang5index13getSymbolInfoEPKNS_4DeclE'/>
<use f='llvm/clang/lib/Index/IndexSymbol.cpp' l='309' u='r' c='_ZN5clang5index13getSymbolInfoEPKNS_4DeclE'/>
<use f='llvm/clang/lib/Index/IndexSymbol.cpp' l='314' u='r' c='_ZN5clang5index13getSymbolInfoEPKNS_4DeclE'/>
<use f='llvm/clang/lib/Index/IndexSymbol.cpp' l='319' u='r' c='_ZN5clang5index13getSymbolInfoEPKNS_4DeclE'/>
<use f='llvm/clang/lib/Index/IndexSymbol.cpp' l='325' u='r' c='_ZN5clang5index13getSymbolInfoEPKNS_4DeclE'/>
<use f='llvm/clang/lib/Index/IndexSymbol.cpp' l='330' u='r' c='_ZN5clang5index13getSymbolInfoEPKNS_4DeclE'/>
<use f='llvm/clang/lib/Index/IndexSymbol.cpp' l='334' u='r' c='_ZN5clang5index13getSymbolInfoEPKNS_4DeclE'/>
<use f='llvm/clang/lib/Index/IndexSymbol.cpp' l='341' u='r' c='_ZN5clang5index13getSymbolInfoEPKNS_4DeclE'/>
<use f='llvm/clang/lib/Index/IndexSymbol.cpp' l='388' u='r' c='_ZN5clang5index13getSymbolInfoEPKNS_4DeclE'/>
<use f='llvm/clang/lib/Index/IndexSymbol.cpp' l='553' c='_ZN5clang5index23getSymbolLanguageStringENS0_14SymbolLanguageE'/>
<use f='llvm/clang/tools/libclang/CXIndexDataConsumer.cpp' l='1256' u='r' c='_ZL27getEntityKindFromSymbolKindN5clang5index10SymbolKindENS0_14SymbolLanguageE'/>
<use f='llvm/clang/tools/libclang/CXIndexDataConsumer.cpp' l='1308' c='_ZL27getEntityLangFromSymbolLangN5clang5index14SymbolLanguageE'/>
