<use f='llvm/clang/include/clang/Sema/SemaInternal.h' l='99' u='w' c='_ZN5clang22TypoCorrectionConsumerC1ERNS_4SemaERKNS_19DeclarationNameInfoENS1_14LookupNameKindEPNS_5ScopeEPNS_12CXXScopeSpecESt10unique_ptrINS_27Correc6387778'/>
<use f='llvm/clang/include/clang/Sema/SemaInternal.h' l='206' u='r' c='_ZNK5clang22TypoCorrectionConsumer8getScopeEv'/>
<dec f='llvm/clang/include/clang/Sema/SemaInternal.h' l='310' type='clang::Scope *'/>
<offset>3648</offset>
<use f='llvm/clang/lib/Sema/SemaLookup.cpp' l='4341' u='r' c='_ZN5clang22TypoCorrectionConsumer17resolveCorrectionERNS_14TypoCorrectionE'/>
