<dec f='llvm/clang/include/clang/AST/Decl.h' l='2998' type='clang::Stmt *'/>
<use f='llvm/clang/include/clang/AST/Decl.h' l='3005' u='w' c='_ZN5clang16EnumConstantDeclC1EPNS_11DeclContextENS_14SourceLocationEPNS_14IdentifierInfoENS_8QualTypeEPNS_4ExprERKN4llvm6APSIntE'/>
<use f='llvm/clang/include/clang/AST/Decl.h' l='3016' u='r' c='_ZNK5clang16EnumConstantDecl11getInitExprEv'/>
<use f='llvm/clang/include/clang/AST/Decl.h' l='3017' u='r' c='_ZN5clang16EnumConstantDecl11getInitExprEv'/>
<use f='llvm/clang/include/clang/AST/Decl.h' l='3020' u='w' c='_ZN5clang16EnumConstantDecl11setInitExprEPNS_4ExprE'/>
<offset>448</offset>
<doc f='llvm/clang/include/clang/AST/Decl.h' l='2998'>// an integer constant expression</doc>
<use f='llvm/clang/lib/AST/Decl.cpp' l='4913' u='r' c='_ZNK5clang16EnumConstantDecl14getSourceRangeEv'/>
<use f='llvm/clang/lib/AST/Decl.cpp' l='4914' u='r' c='_ZNK5clang16EnumConstantDecl14getSourceRangeEv'/>
