<dec f='llvm/clang/lib/Lex/ModuleMap.cpp' l='1406' type='clang::Lexer &amp;'/>
<use f='llvm/clang/lib/Lex/ModuleMap.cpp' l='1491' u='w' c='_ZN5clang15ModuleMapParserC1ERNS_5LexerERNS_13SourceManagerEPKNS_10TargetInfoERNS_17DiagnosticsEngineERNS_9ModuleMapEPKNS_9FileEntryEPKNS_14DirectoryEntryEb'/>
<use f='llvm/clang/lib/Lex/ModuleMap.cpp' l='1512' u='m' c='_ZN5clang15ModuleMapParser12consumeTokenEv'/>
<use f='llvm/clang/lib/Lex/ModuleMap.cpp' l='1608' u='m' c='_ZN5clang15ModuleMapParser12consumeTokenEv'/>
<use f='llvm/clang/lib/Lex/ModuleMap.cpp' l='1631' u='m' c='_ZN5clang15ModuleMapParser12consumeTokenEv'/>
<offset>0</offset>
