<dec f='llvm/clang/include/clang/AST/ExprCXX.h' l='309' type='const clang::Expr *'/>
<use f='llvm/clang/include/clang/AST/ExprCXX.h' l='333' u='r' c='_ZNK5clang26CXXRewrittenBinaryOperator6getLHSEv'/>
<use f='llvm/clang/include/clang/AST/ExprCXX.h' l='346' u='r' c='_ZNK5clang26CXXRewrittenBinaryOperator11getBeginLocEv'/>
<use f='llvm/clang/include/clang/AST/ExprCXX.h' l='353' u='r' c='_ZNK5clang26CXXRewrittenBinaryOperator14getSourceRangeEv'/>
<offset>64</offset>
<doc f='llvm/clang/include/clang/AST/ExprCXX.h' l='308'>/// The original left-hand side.</doc>
<use f='llvm/clang/include/clang/AST/RecursiveASTVisitor.h' l='2672' u='r' c='_ZN5clang19RecursiveASTVisitor34TraverseCXXRewrittenBinaryOperatorEPNS_26CXXRewrittenBinaryOperatorEPN4llvm15SmallVectorImplINS3_14PointerIntPairIPNS_1804206'/>
<use f='llvm/clang/lib/AST/ExprCXX.cpp' l='81' u='w' c='_ZNK5clang26CXXRewrittenBinaryOperator17getDecomposedFormEv'/>
<use f='llvm/clang/lib/AST/ExprCXX.cpp' l='96' u='w' c='_ZNK5clang26CXXRewrittenBinaryOperator17getDecomposedFormEv'/>
<use f='llvm/clang/lib/AST/ExprCXX.cpp' l='106' u='a' c='_ZNK5clang26CXXRewrittenBinaryOperator17getDecomposedFormEv'/>
<use f='llvm/clang/lib/AST/ExprCXX.cpp' l='113' u='r' c='_ZNK5clang26CXXRewrittenBinaryOperator17getDecomposedFormEv'/>
<use f='llvm/clang/lib/AST/ExprCXX.cpp' l='116' u='w' c='_ZNK5clang26CXXRewrittenBinaryOperator17getDecomposedFormEv'/>
<use f='llvm/clang/lib/AST/ExprCXX.cpp' l='121' u='w' c='_ZNK5clang26CXXRewrittenBinaryOperator17getDecomposedFormEv'/>
<use f='llvm/clang/lib/AST/ExprCXX.cpp' l='130' u='a' c='_ZNK5clang26CXXRewrittenBinaryOperator17getDecomposedFormEv'/>
<use f='llvm/clang/lib/AST/ItaniumMangle.cpp' l='4538' u='r' c='_ZN12_GLOBAL__N_114CXXNameMangler16mangleExpressionEPKN5clang4ExprEjb'/>
<use f='llvm/clang/lib/AST/StmtPrinter.cpp' l='1764' u='r' c='_ZN12_GLOBAL__N_111StmtPrinter31VisitCXXRewrittenBinaryOperatorEPN5clang26CXXRewrittenBinaryOperatorE'/>
<use f='llvm/clang/lib/Sema/TreeTransform.h' l='10629' u='r' c='_ZN5clang13TreeTransform35TransformCXXRewrittenBinaryOperatorEPNS_26CXXRewrittenBinaryOperatorE'/>
<use f='llvm/clang/lib/Sema/TreeTransform.h' l='10638' u='r' c='_ZN5clang13TreeTransform35TransformCXXRewrittenBinaryOperatorEPNS_26CXXRewrittenBinaryOperatorE'/>
