<use f='llvm/clang/include/clang/Sema/Sema.h' l='12678' u='w' c='_ZN5clang4Sema31SavePendingParsedClassStateRAIIC1ERS0_'/>
<dec f='llvm/clang/include/clang/Sema/Sema.h' l='12689' type='clang::Sema &amp;'/>
<use f='llvm/clang/include/clang/Sema/Sema.h' l='12697' u='m' c='_ZN5clang4Sema31SavePendingParsedClassStateRAII14swapSavedStateEv'/>
<use f='llvm/clang/include/clang/Sema/Sema.h' l='12699' u='m' c='_ZN5clang4Sema31SavePendingParsedClassStateRAII14swapSavedStateEv'/>
<offset>0</offset>
