<dec f='llvm/clang/include/clang/ASTMatchers/GtestMatchers.h' l='25' type='0'/>
<use f='llvm/clang/lib/ASTMatchers/GtestMatchers.cpp' l='26' c='_ZN5clang12ast_matchersL17getComparisonDeclENS0_8GtestCmpE'/>
<use f='llvm/clang/lib/ASTMatchers/GtestMatchers.cpp' l='46' c='_ZN5clang12ast_matchersL14getAssertMacroENS0_8GtestCmpE'/>
<use f='llvm/clang/lib/ASTMatchers/GtestMatchers.cpp' l='64' c='_ZN5clang12ast_matchersL14getExpectMacroENS0_8GtestCmpE'/>
<use f='llvm/clang/unittests/ASTMatchers/GtestMatchersTest.cpp' l='112' u='r' c='_ZN5clang12ast_matchers38GtestAssertTest_ShouldMatchAssert_Test8TestBodyEv'/>
<use f='llvm/clang/unittests/ASTMatchers/GtestMatchersTest.cpp' l='121' u='r' c='_ZN5clang12ast_matchers41GtestAssertTest_ShouldNotMatchExpect_Test8TestBodyEv'/>
<use f='llvm/clang/unittests/ASTMatchers/GtestMatchersTest.cpp' l='130' u='r' c='_ZN5clang12ast_matchers44GtestAssertTest_ShouldMatchNestedAssert_Test8TestBodyEv'/>
<use f='llvm/clang/unittests/ASTMatchers/GtestMatchersTest.cpp' l='138' u='r' c='_ZN5clang12ast_matchers38GtestExpectTest_ShouldMatchExpect_Test8TestBodyEv'/>
<use f='llvm/clang/unittests/ASTMatchers/GtestMatchersTest.cpp' l='147' u='r' c='_ZN5clang12ast_matchers41GtestExpectTest_ShouldNotMatchAssert_Test8TestBodyEv'/>
