<dec f='llvm/clang/include/clang/Analysis/AnyCall.h' l='66' type='clang::AnyCall::Kind'/>
<use f='llvm/clang/include/clang/Analysis/AnyCall.h' l='71' u='w' c='_ZN5clang7AnyCallC1EPKNS_8CallExprE'/>
<use f='llvm/clang/include/clang/Analysis/AnyCall.h' l='73' u='r' c='_ZN5clang7AnyCallC1EPKNS_8CallExprE'/>
<use f='llvm/clang/include/clang/Analysis/AnyCall.h' l='74' u='r' c='_ZN5clang7AnyCallC1EPKNS_8CallExprE'/>
<use f='llvm/clang/include/clang/Analysis/AnyCall.h' l='79' u='w' c='_ZN5clang7AnyCallC1EPKNS_15ObjCMessageExprE'/>
<use f='llvm/clang/include/clang/Analysis/AnyCall.h' l='82' u='w' c='_ZN5clang7AnyCallC1EPKNS_10CXXNewExprE'/>
<use f='llvm/clang/include/clang/Analysis/AnyCall.h' l='85' u='w' c='_ZN5clang7AnyCallC1EPKNS_13CXXDeleteExprE'/>
<use f='llvm/clang/include/clang/Analysis/AnyCall.h' l='88' u='w' c='_ZN5clang7AnyCallC1EPKNS_16CXXConstructExprE'/>
<use f='llvm/clang/include/clang/Analysis/AnyCall.h' l='91' u='w' c='_ZN5clang7AnyCallC1EPKNS_24CXXInheritedCtorInitExprE'/>
<use f='llvm/clang/include/clang/Analysis/AnyCall.h' l='93' u='w' c='_ZN5clang7AnyCallC1EPKNS_17CXXDestructorDeclE'/>
<use f='llvm/clang/include/clang/Analysis/AnyCall.h' l='95' u='w' c='_ZN5clang7AnyCallC1EPKNS_18CXXConstructorDeclE'/>
<use f='llvm/clang/include/clang/Analysis/AnyCall.h' l='97' u='w' c='_ZN5clang7AnyCallC1EPKNS_14ObjCMethodDeclE'/>
<use f='llvm/clang/include/clang/Analysis/AnyCall.h' l='101' u='w' c='_ZN5clang7AnyCallC1EPKNS_12FunctionDeclE'/>
<use f='llvm/clang/include/clang/Analysis/AnyCall.h' l='103' u='w' c='_ZN5clang7AnyCallC1EPKNS_12FunctionDeclE'/>
<use f='llvm/clang/include/clang/Analysis/AnyCall.h' l='105' u='w' c='_ZN5clang7AnyCallC1EPKNS_12FunctionDeclE'/>
<use f='llvm/clang/include/clang/Analysis/AnyCall.h' l='165' u='r' c='_ZNK5clang7AnyCall13getReturnTypeERNS_10ASTContextE'/>
<use f='llvm/clang/include/clang/Analysis/AnyCall.h' l='205' u='r' c='_ZNK5clang7AnyCall7getKindEv'/>
<offset>128</offset>
