<dec f='llvm/clang/lib/Serialization/ASTReaderInternals.h' l='246' type='clang::serialization::ModuleFile &amp;'/>
<use f='llvm/clang/lib/Serialization/ASTReaderInternals.h' l='268' u='w' c='_ZN5clang13serialization6reader19HeaderFileInfoTraitC1ERNS_9ASTReaderERNS0_10ModuleFileEPNS_12HeaderSearchEPKc'/>
<use f='llvm/clang/lib/Serialization/ASTReader.cpp' l='1815' u='m' c='_ZN5clang13serialization6reader19HeaderFileInfoTrait14GetInternalKeyEPKNS_9FileEntryE'/>
<use f='llvm/clang/lib/Serialization/ASTReader.cpp' l='1837' u='a' c='_ZN5clang13serialization6reader19HeaderFileInfoTrait8EqualKeyERKNS2_17internal_key_typeES5_'/>
<use f='llvm/clang/lib/Serialization/ASTReader.cpp' l='1887' u='a' c='_ZN5clang13serialization6reader19HeaderFileInfoTrait8ReadDataERKNS2_17internal_key_typeEPKhj'/>
<use f='llvm/clang/lib/Serialization/ASTReader.cpp' l='1905' u='a' c='_ZN5clang13serialization6reader19HeaderFileInfoTrait8ReadDataERKNS2_17internal_key_typeEPKhj'/>
<use f='llvm/clang/lib/Serialization/ASTReader.cpp' l='1913' u='a' c='_ZN5clang13serialization6reader19HeaderFileInfoTrait8ReadDataERKNS2_17internal_key_typeEPKhj'/>
<offset>64</offset>
