<dec f='llvm/clang/lib/Driver/ToolChains/ROCm.h' l='50' type='const clang::driver::Driver &amp;'/>
<offset>0</offset>
<use f='llvm/clang/lib/Driver/ToolChains/AMDGPU.cpp' l='32' u='m' c='_ZN5clang6driver24RocmInstallationDetector17scanLibDevicePathEN4llvm9StringRefE'/>
<use f='llvm/clang/lib/Driver/ToolChains/AMDGPU.cpp' l='127' u='m' c='_ZN5clang6driver24RocmInstallationDetector29getInstallationPathCandidatesEv'/>
<use f='llvm/clang/lib/Driver/ToolChains/AMDGPU.cpp' l='150' u='m' c='_ZN5clang6driver24RocmInstallationDetector29getInstallationPathCandidatesEv'/>
<use f='llvm/clang/lib/Driver/ToolChains/AMDGPU.cpp' l='152' u='m' c='_ZN5clang6driver24RocmInstallationDetector29getInstallationPathCandidatesEv'/>
<use f='llvm/clang/lib/Driver/ToolChains/AMDGPU.cpp' l='159' u='w' c='_ZN5clang6driver24RocmInstallationDetectorC1ERKNS0_6DriverERKN4llvm6TripleERKNS5_3opt7ArgListEbb'/>
<use f='llvm/clang/lib/Driver/ToolChains/AMDGPU.cpp' l='207' u='m' c='_ZN5clang6driver24RocmInstallationDetector19detectDeviceLibraryEv'/>
<use f='llvm/clang/lib/Driver/ToolChains/AMDGPU.cpp' l='280' u='m' c='_ZN5clang6driver24RocmInstallationDetector16detectHIPRuntimeEv'/>
<use f='llvm/clang/lib/Driver/ToolChains/AMDGPU.cpp' l='333' u='m' c='_ZNK5clang6driver24RocmInstallationDetector17AddHIPIncludeArgsERKN4llvm3opt7ArgListERNS2_11SmallVectorIPKcLj16EEE'/>
<use f='llvm/clang/lib/Driver/ToolChains/AMDGPU.cpp' l='344' u='m' c='_ZNK5clang6driver24RocmInstallationDetector17AddHIPIncludeArgsERKN4llvm3opt7ArgListERNS2_11SmallVectorIPKcLj16EEE'/>
