<dec f='llvm/clang/include/clang/Serialization/ASTWriter.h' l='348' type='const clang::Decl *'/>
<use f='llvm/clang/include/clang/Serialization/ASTWriter.h' l='357' c='_ZN5clang9ASTWriter10DeclUpdateC1Ej'/>
<use f='llvm/clang/include/clang/Serialization/ASTWriter.h' l='358' c='_ZN5clang9ASTWriter10DeclUpdateC1EjPKNS_4DeclE'/>
<use f='llvm/clang/include/clang/Serialization/ASTWriter.h' l='369' u='r' c='_ZNK5clang9ASTWriter10DeclUpdate7getDeclEv'/>
<offset>0</offset>
