<dec f='llvm/clang/include/clang/Analysis/AnyCall.h' l='65' type='const clang::Decl *'/>
<use f='llvm/clang/include/clang/Analysis/AnyCall.h' l='70' u='w' c='_ZN5clang7AnyCallC1EPKNS_8CallExprE'/>
<use f='llvm/clang/include/clang/Analysis/AnyCall.h' l='73' u='r' c='_ZN5clang7AnyCallC1EPKNS_8CallExprE'/>
<use f='llvm/clang/include/clang/Analysis/AnyCall.h' l='73' u='r' c='_ZN5clang7AnyCallC1EPKNS_8CallExprE'/>
<use f='llvm/clang/include/clang/Analysis/AnyCall.h' l='74' u='r' c='_ZN5clang7AnyCallC1EPKNS_8CallExprE'/>
<use f='llvm/clang/include/clang/Analysis/AnyCall.h' l='75' u='w' c='_ZN5clang7AnyCallC1EPKNS_8CallExprE'/>
<use f='llvm/clang/include/clang/Analysis/AnyCall.h' l='79' u='w' c='_ZN5clang7AnyCallC1EPKNS_15ObjCMessageExprE'/>
<use f='llvm/clang/include/clang/Analysis/AnyCall.h' l='82' u='w' c='_ZN5clang7AnyCallC1EPKNS_10CXXNewExprE'/>
<use f='llvm/clang/include/clang/Analysis/AnyCall.h' l='85' u='w' c='_ZN5clang7AnyCallC1EPKNS_13CXXDeleteExprE'/>
<use f='llvm/clang/include/clang/Analysis/AnyCall.h' l='88' u='w' c='_ZN5clang7AnyCallC1EPKNS_16CXXConstructExprE'/>
<use f='llvm/clang/include/clang/Analysis/AnyCall.h' l='91' u='w' c='_ZN5clang7AnyCallC1EPKNS_24CXXInheritedCtorInitExprE'/>
<use f='llvm/clang/include/clang/Analysis/AnyCall.h' l='93' u='w' c='_ZN5clang7AnyCallC1EPKNS_17CXXDestructorDeclE'/>
<use f='llvm/clang/include/clang/Analysis/AnyCall.h' l='95' u='w' c='_ZN5clang7AnyCallC1EPKNS_18CXXConstructorDeclE'/>
<use f='llvm/clang/include/clang/Analysis/AnyCall.h' l='97' u='w' c='_ZN5clang7AnyCallC1EPKNS_14ObjCMethodDeclE'/>
<use f='llvm/clang/include/clang/Analysis/AnyCall.h' l='99' u='w' c='_ZN5clang7AnyCallC1EPKNS_12FunctionDeclE'/>
<use f='llvm/clang/include/clang/Analysis/AnyCall.h' l='144' u='r' c='_ZNK5clang7AnyCall10parametersEv'/>
<use f='llvm/clang/include/clang/Analysis/AnyCall.h' l='147' u='r' c='_ZNK5clang7AnyCall10parametersEv'/>
<use f='llvm/clang/include/clang/Analysis/AnyCall.h' l='149' u='r' c='_ZNK5clang7AnyCall10parametersEv'/>
<use f='llvm/clang/include/clang/Analysis/AnyCall.h' l='151' u='r' c='_ZNK5clang7AnyCall10parametersEv'/>
<use f='llvm/clang/include/clang/Analysis/AnyCall.h' l='169' u='r' c='_ZNK5clang7AnyCall13getReturnTypeERNS_10ASTContextE'/>
<use f='llvm/clang/include/clang/Analysis/AnyCall.h' l='173' u='r' c='_ZNK5clang7AnyCall13getReturnTypeERNS_10ASTContextE'/>
<use f='llvm/clang/include/clang/Analysis/AnyCall.h' l='183' u='r' c='_ZNK5clang7AnyCall13getReturnTypeERNS_10ASTContextE'/>
<use f='llvm/clang/include/clang/Analysis/AnyCall.h' l='191' u='r' c='_ZNK5clang7AnyCall13getIdentifierEv'/>
<use f='llvm/clang/include/clang/Analysis/AnyCall.h' l='197' u='r' c='_ZNK5clang7AnyCall7getDeclEv'/>
<use f='llvm/clang/include/clang/Analysis/AnyCall.h' l='211' u='r' c='_ZNK5clang7AnyCall4dumpEv'/>
<use f='llvm/clang/include/clang/Analysis/AnyCall.h' l='212' u='r' c='_ZNK5clang7AnyCall4dumpEv'/>
<offset>64</offset>
<doc f='llvm/clang/include/clang/Analysis/AnyCall.h' l='63'>/// Corresponds to a statically known declaration of the called function,
  /// or null if it is not known (e.g. for a function pointer).</doc>
