<dec f='llvm/clang/include/clang/ASTMatchers/GtestMatchers.h' l='26' type='1'/>
<use f='llvm/clang/lib/ASTMatchers/GtestMatchers.cpp' l='30' c='_ZN5clang12ast_matchersL17getComparisonDeclENS0_8GtestCmpE'/>
<use f='llvm/clang/lib/ASTMatchers/GtestMatchers.cpp' l='48' c='_ZN5clang12ast_matchersL14getAssertMacroENS0_8GtestCmpE'/>
<use f='llvm/clang/lib/ASTMatchers/GtestMatchers.cpp' l='66' c='_ZN5clang12ast_matchersL14getExpectMacroENS0_8GtestCmpE'/>
<use f='llvm/clang/unittests/ASTMatchers/GtestMatchersTest.cpp' l='155' u='r' c='_ZN5clang12ast_matchers42GtestExpectTest_NeShouldMatchExpectNe_Test8TestBodyEv'/>
