<use f='llvm/clang/include/clang/Sema/Sema.h' l='1489' u='w' c='_ZN5clang4Sema19FPFeaturesStateRAIIC1ERS0_'/>
<use f='llvm/clang/include/clang/Sema/Sema.h' l='1493' u='m' c='_ZN5clang4Sema19FPFeaturesStateRAIID1Ev'/>
<use f='llvm/clang/include/clang/Sema/Sema.h' l='1494' u='m' c='_ZN5clang4Sema19FPFeaturesStateRAIID1Ev'/>
<dec f='llvm/clang/include/clang/Sema/Sema.h' l='1499' type='clang::Sema &amp;'/>
<offset>0</offset>
