<dec f='llvm/clang/include/clang/Frontend/ASTUnit.h' l='116' type='std::shared_ptr&lt;Preprocessor&gt;'/>
<use f='llvm/clang/include/clang/Frontend/ASTUnit.h' l='435' u='m' c='_ZNK5clang7ASTUnit15getPreprocessorEv'/>
<use f='llvm/clang/include/clang/Frontend/ASTUnit.h' l='436' u='m' c='_ZN5clang7ASTUnit15getPreprocessorEv'/>
<use f='llvm/clang/include/clang/Frontend/ASTUnit.h' l='437' u='r' c='_ZNK5clang7ASTUnit18getPreprocessorPtrEv'/>
<offset>512</offset>
<use f='llvm/clang/lib/Frontend/ASTUnit.cpp' l='276' u='w' c='_ZN5clang7ASTUnit15setPreprocessorESt10shared_ptrINS_12PreprocessorEE'/>
<use f='llvm/clang/lib/Frontend/ASTUnit.cpp' l='282' u='m' c='_ZN5clang7ASTUnit27enableSourceFileDiagnosticsEv'/>
<use f='llvm/clang/lib/Frontend/ASTUnit.cpp' l='800' u='w' c='_ZN5clang7ASTUnit15LoadFromASTFileERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKNS_18PCHContainerReaderENS0_10WhatToLoadEN4llvm18IntrusiveR4279402'/>
<use f='llvm/clang/lib/Frontend/ASTUnit.cpp' l='805' u='m' c='_ZN5clang7ASTUnit15LoadFromASTFileERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKNS_18PCHContainerReaderENS0_10WhatToLoadEN4llvm18IntrusiveR4279402'/>
<use f='llvm/clang/lib/Frontend/ASTUnit.cpp' l='822' u='m' c='_ZN5clang7ASTUnit15LoadFromASTFileERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKNS_18PCHContainerReaderENS0_10WhatToLoadEN4llvm18IntrusiveR4279402'/>
<use f='llvm/clang/lib/Frontend/ASTUnit.cpp' l='1453' u='w' c='_ZN5clang7ASTUnit35transferASTDataFromCompilerInstanceERNS_16CompilerInstanceE'/>
<use f='llvm/clang/lib/Frontend/ASTUnit.cpp' l='1594' u='w' c='_ZN5clang7ASTUnit32LoadFromCompilerInvocationActionESt10shared_ptrINS_18CompilerInvocationEES1_INS_22PCHContainerOperationsEEN4llvm18IntrusiveRefCntPt5770410'/>
<use f='llvm/clang/lib/Frontend/ASTUnit.cpp' l='1887' u='m' c='_ZN5clang7ASTUnit13ResetForParseEv'/>
<use f='llvm/clang/lib/Frontend/ASTUnit.cpp' l='2604' u='m' c='_ZNK5clang7ASTUnit29getLocalPreprocessingEntitiesEv'/>
