<use f='llvm/clang/include/clang/AST/DeclBase.h' l='735' c='_ZNK5clang4Decl19getOwningModuleSlowEv'/>
<use f='llvm/clang/include/clang/AST/DeclBase.h' l='743' c='_ZNK5clang4Decl23getImportedOwningModuleEv'/>
<use f='llvm/clang/include/clang/AST/DeclBase.h' l='752' c='_ZNK5clang4Decl20getLocalOwningModuleEv'/>
<use f='llvm/clang/include/clang/AST/DeclBase.h' l='758' c='_ZNK5clang4Decl20getLocalOwningModuleEv'/>
<use f='llvm/clang/include/clang/AST/DeclBase.h' l='760' c='_ZN5clang4Decl20setLocalOwningModuleEPNS_6ModuleE'/>
<use f='llvm/clang/include/clang/AST/DeclBase.h' l='764' c='_ZN5clang4Decl20setLocalOwningModuleEPNS_6ModuleE'/>
<use f='llvm/clang/include/clang/AST/DeclBase.h' l='773' c='_ZNK5clang4Decl15getOwningModuleEv'/>
<use f='llvm/clang/include/clang/AST/DeclBase.h' l='782' c='_ZNK5clang4Decl25getOwningModuleForLinkageEb'/>
<use f='llvm/clang/include/clang/AST/ExternalASTSource.h' l='162' c='_ZN5clang17ExternalASTSource9getModuleEj'/>
<use f='llvm/clang/include/clang/AST/Decl.h' l='4402'/>
<use f='llvm/clang/include/clang/AST/Decl.h' l='4414' c='_ZN5clang10ImportDeclC1EPNS_11DeclContextENS_14SourceLocationEPNS_6ModuleEN4llvm8ArrayRefIS3_EE'/>
<use f='llvm/clang/include/clang/AST/Decl.h' l='4417' c='_ZN5clang10ImportDeclC1EPNS_11DeclContextENS_14SourceLocationEPNS_6ModuleES3_'/>
<use f='llvm/clang/include/clang/AST/Decl.h' l='4439' c='_ZN5clang10ImportDecl6CreateERNS_10ASTContextEPNS_11DeclContextENS_14SourceLocationEPNS_6ModuleEN4llvm8ArrayRefIS5_EE'/>
<use f='llvm/clang/include/clang/AST/Decl.h' l='4445' c='_ZN5clang10ImportDecl14CreateImplicitERNS_10ASTContextEPNS_11DeclContextENS_14SourceLocationEPNS_6ModuleES5_'/>
<use f='llvm/clang/include/clang/AST/Decl.h' l='4453' c='_ZNK5clang10ImportDecl17getImportedModuleEv'/>
<use f='llvm/clang/include/clang/AST/ASTContext.h' l='429'/>
<use f='llvm/clang/include/clang/AST/ASTContext.h' l='441'/>
<use f='llvm/clang/include/clang/AST/ASTContext.h' l='943' c='_ZN5clang10ASTContext25mergeDefinitionIntoModuleEPNS_9NamedDeclEPNS_6ModuleEb'/>
<use f='llvm/clang/include/clang/AST/ASTContext.h' l='952' c='_ZN5clang10ASTContext30getModulesWithMergedDefinitionEPKNS_9NamedDeclE'/>
<use f='llvm/clang/include/clang/AST/ASTContext.h' l='958' c='_ZN5clang10ASTContext20addModuleInitializerEPNS_6ModuleEPNS_4DeclE'/>
<use f='llvm/clang/include/clang/AST/ASTContext.h' l='960' c='_ZN5clang10ASTContext25addLazyModuleInitializersEPNS_6ModuleEN4llvm8ArrayRefIjEE'/>
<use f='llvm/clang/include/clang/AST/ASTContext.h' l='963' c='_ZN5clang10ASTContext21getModuleInitializersEPNS_6ModuleE'/>
<def f='llvm/clang/include/clang/Basic/Module.h' l='96' ll='649'/>
<use f='llvm/clang/include/clang/Basic/Module.h' l='124'/>
<use f='llvm/clang/include/clang/Basic/Module.h' l='157'/>
<use f='llvm/clang/include/clang/Basic/Module.h' l='174'/>
<use f='llvm/clang/include/clang/Basic/Module.h' l='241'/>
<use f='llvm/clang/include/clang/Basic/Module.h' l='324'/>
<use f='llvm/clang/include/clang/Basic/Module.h' l='330'/>
<use f='llvm/clang/include/clang/Basic/Module.h' l='354'/>
<use f='llvm/clang/include/clang/Basic/Module.h' l='404'/>
<use f='llvm/clang/include/clang/Basic/Module.h' l='414' c='_ZN5clang6ModuleC1EN4llvm9StringRefENS_14SourceLocationEPS0_bbj'/>
<use f='llvm/clang/include/clang/Basic/Module.h' l='436' c='_ZNK5clang6Module14isUnimportableERKNS_11LangOptionsERKNS_10TargetInfoERSt4pairINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEbERPS0_'/>
<use f='llvm/clang/include/clang/Basic/Module.h' l='463' c='_ZNK5clang6Module11isAvailableERKNS_11LangOptionsERKNS_10TargetInfoERSt4pairINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEbERNS0_25UnresolvedHeaderDirectiveERPS0_'/>
<use f='llvm/clang/include/clang/Basic/Module.h' l='474' c='_ZNK5clang6Module13isSubModuleOfEPKS0_'/>
<use f='llvm/clang/include/clang/Basic/Module.h' l='480' c='_ZNK5clang6Module17isPartOfFrameworkEv'/>
<use f='llvm/clang/include/clang/Basic/Module.h' l='495' c='_ZN5clang6Module9setParentEPS0_'/>
<use f='llvm/clang/include/clang/Basic/Module.h' l='516' c='_ZN5clang6Module17getTopLevelModuleEv'/>
<use f='llvm/clang/include/clang/Basic/Module.h' l='517' c='_ZN5clang6Module17getTopLevelModuleEv'/>
<use f='llvm/clang/include/clang/Basic/Module.h' l='518' c='_ZN5clang6Module17getTopLevelModuleEv'/>
<use f='llvm/clang/include/clang/Basic/Module.h' l='523' c='_ZNK5clang6Module17getTopLevelModuleEv'/>
<use f='llvm/clang/include/clang/Basic/Module.h' l='573' c='_ZNK5clang6Module12directlyUsesEPKS0_'/>
<use f='llvm/clang/include/clang/Basic/Module.h' l='599' c='_ZNK5clang6Module13findSubmoduleEN4llvm9StringRefE'/>
<use f='llvm/clang/include/clang/Basic/Module.h' l='600' c='_ZN5clang6Module20findOrInferSubmoduleEN4llvm9StringRefE'/>
<use f='llvm/clang/include/clang/Basic/Module.h' l='608' c='_ZNK5clang6Module15isModuleVisibleEPKS0_'/>
<use f='llvm/clang/include/clang/Basic/Module.h' l='635' c='_ZNK5clang6Module18getExportedModulesERN4llvm15SmallVectorImplIPS0_EE'/>
<use f='llvm/clang/include/clang/Basic/Module.h' l='676' c='_ZNK5clang16VisibleModuleSet9isVisibleEPKNS_6ModuleE'/>
<use f='llvm/clang/include/clang/Basic/Module.h' l='681' c='_ZNK5clang16VisibleModuleSet12getImportLocEPKNS_6ModuleE'/>
<use f='llvm/clang/include/clang/Basic/Module.h' l='689'/>
<use f='llvm/clang/include/clang/Basic/Module.h' l='695'/>
<use f='llvm/clang/include/clang/Basic/Module.h' l='695'/>
<use f='llvm/clang/include/clang/Basic/Module.h' l='699' c='_ZN5clang16VisibleModuleSet10setVisibleEPNS_6ModuleENS_14SourceLocationEN4llvm12function_refIFvS2_EEENS5_IFvNS4_8ArrayRefIS2_EES2_NS4_9StringRefEEEE'/>
<use f='llvm/clang/include/clang/Basic/Module.h' l='700' c='_ZN5clang16VisibleModuleSet10setVisibleEPNS_6ModuleENS_14SourceLocationEN4llvm12function_refIFvS2_EEENS5_IFvNS4_8ArrayRefIS2_EES2_NS4_9StringRefEEEE'/>
<use f='llvm/clang/include/clang/Basic/Module.h' l='701' c='_ZN5clang16VisibleModuleSet10setVisibleEPNS_6ModuleENS_14SourceLocationEN4llvm12function_refIFvS2_EEENS5_IFvNS4_8ArrayRefIS2_EES2_NS4_9StringRefEEEE'/>
<use f='llvm/clang/include/clang/Basic/Module.h' l='701' c='_ZN5clang16VisibleModuleSet10setVisibleEPNS_6ModuleENS_14SourceLocationEN4llvm12function_refIFvS2_EEENS5_IFvNS4_8ArrayRefIS2_EES2_NS4_9StringRefEEEE'/>
<use f='llvm/clang/include/clang/Basic/Module.h' l='721'/>
<use f='llvm/clang/include/clang/Basic/Module.h' l='729' c='_ZN5clang19ASTSourceDescriptorC1ERNS_6ModuleE'/>
<use f='llvm/clang/include/clang/Basic/Module.h' l='735' c='_ZNK5clang19ASTSourceDescriptor15getModuleOrNullEv'/>
<use f='llvm/clang/include/clang/Lex/ModuleLoader.h' l='52'/>
<use f='llvm/clang/include/clang/Lex/ModuleLoader.h' l='55' c='_ZN5clang16ModuleLoadResultC1EPNS_6ModuleE'/>
<use f='llvm/clang/include/clang/Lex/ModuleLoader.h' l='58' c='_ZNK5clang16ModuleLoadResultcvPNS_6ModuleEEv'/>
<use f='llvm/clang/include/clang/Lex/ModuleLoader.h' l='136' c='_ZN5clang12ModuleLoader17makeModuleVisibleEPNS_6ModuleENS1_18NameVisibilityKindENS_14SourceLocationE'/>
<use f='llvm/clang/include/clang/Lex/ModuleLoader.h' l='175' c='_ZN5clang19TrivialModuleLoader17makeModuleVisibleEPNS_6ModuleENS1_18NameVisibilityKindENS_14SourceLocationE'/>
<use f='llvm/clang/include/clang/Lex/PPCallbacks.h' l='130' c='_ZN5clang11PPCallbacks18InclusionDirectiveENS_14SourceLocationERKNS_5TokenEN4llvm9StringRefEbNS_15CharSourceRangeEPKNS_9FileEntryES6_S6_PKNS_6ModuleEN8303703'/>
<use f='llvm/clang/include/clang/Lex/PPCallbacks.h' l='142' c='_ZN5clang11PPCallbacks16EnteredSubmoduleEPNS_6ModuleENS_14SourceLocationEb'/>
<use f='llvm/clang/include/clang/Lex/PPCallbacks.h' l='153' c='_ZN5clang11PPCallbacks13LeftSubmoduleEPNS_6ModuleENS_14SourceLocationEb'/>
<use f='llvm/clang/include/clang/Lex/PPCallbacks.h' l='168' c='_ZN5clang11PPCallbacks12moduleImportENS_14SourceLocationEN4llvm8ArrayRefISt4pairIPNS_14IdentifierInfoES1_EEEPKNS_6ModuleE'/>
<use f='llvm/clang/include/clang/Lex/PPCallbacks.h' l='409' c='_ZN5clang18PPChainedCallbacks18InclusionDirectiveENS_14SourceLocationERKNS_5TokenEN4llvm9StringRefEbNS_15CharSourceRangeEPKNS_9FileEntryES6_S6_PKNS_6M12657200'/>
<use f='llvm/clang/include/clang/Lex/PPCallbacks.h' l='419' c='_ZN5clang18PPChainedCallbacks16EnteredSubmoduleEPNS_6ModuleENS_14SourceLocationEb'/>
<use f='llvm/clang/include/clang/Lex/PPCallbacks.h' l='425' c='_ZN5clang18PPChainedCallbacks13LeftSubmoduleEPNS_6ModuleENS_14SourceLocationEb'/>
<use f='llvm/clang/include/clang/Lex/PPCallbacks.h' l='432' c='_ZN5clang18PPChainedCallbacks12moduleImportENS_14SourceLocationEN4llvm8ArrayRefISt4pairIPNS_14IdentifierInfoES1_EEEPKNS_6ModuleE'/>
<use f='llvm/clang/include/clang/Lex/PreprocessingRecord.h' l='535' c='_ZN5clang19PreprocessingRecord18InclusionDirectiveENS_14SourceLocationERKNS_5TokenEN4llvm9StringRefEbNS_15CharSourceRangeEPKNS_9FileEntryES6_S6_PKNS_610901186'/>
<use f='llvm/clang/include/clang/Lex/MacroInfo.h' l='498'/>
<use f='llvm/clang/include/clang/Lex/MacroInfo.h' l='506' c='_ZN5clang11ModuleMacroC1EPNS_6ModuleEPNS_14IdentifierInfoEPNS_9MacroInfoEN4llvm8ArrayRefIPS0_EE'/>
<use f='llvm/clang/include/clang/Lex/MacroInfo.h' l='515' c='_ZN5clang11ModuleMacro6createERNS_12PreprocessorEPNS_6ModuleEPNS_14IdentifierInfoEPNS_9MacroInfoEN4llvm8ArrayRefIPS0_EE'/>
<use f='llvm/clang/include/clang/Lex/MacroInfo.h' l='523' c='_ZN5clang11ModuleMacro7ProfileERN4llvm16FoldingSetNodeIDEPNS_6ModuleEPNS_14IdentifierInfoE'/>
<use f='llvm/clang/include/clang/Lex/MacroInfo.h' l='533' c='_ZNK5clang11ModuleMacro15getOwningModuleEv'/>
<use f='llvm/clang/include/clang/Lex/ModuleMap.h' l='95'/>
<use f='llvm/clang/include/clang/Lex/ModuleMap.h' l='99'/>
<use f='llvm/clang/include/clang/Lex/ModuleMap.h' l='102'/>
<use f='llvm/clang/include/clang/Lex/ModuleMap.h' l='106'/>
<use f='llvm/clang/include/clang/Lex/ModuleMap.h' l='109'/>
<use f='llvm/clang/include/clang/Lex/ModuleMap.h' l='121' c='_ZN5clang9ModuleMap25resolveLinkAsDependenciesEPNS_6ModuleE'/>
<use f='llvm/clang/include/clang/Lex/ModuleMap.h' l='125' c='_ZN5clang9ModuleMap19addLinkAsDependencyEPNS_6ModuleE'/>
<use f='llvm/clang/include/clang/Lex/ModuleMap.h' l='156'/>
<use f='llvm/clang/include/clang/Lex/ModuleMap.h' l='160' c='_ZN5clang9ModuleMap11KnownHeaderC1EPNS_6ModuleENS0_16ModuleHeaderRoleE'/>
<use f='llvm/clang/include/clang/Lex/ModuleMap.h' l='170' c='_ZNK5clang9ModuleMap11KnownHeader9getModuleEv'/>
<use f='llvm/clang/include/clang/Lex/ModuleMap.h' l='181' c='_ZNK5clang9ModuleMap11KnownHeader16isAccessibleFromEPNS_6ModuleE'/>
<use f='llvm/clang/include/clang/Lex/ModuleMap.h' l='206'/>
<use f='llvm/clang/include/clang/Lex/ModuleMap.h' l='209'/>
<use f='llvm/clang/include/clang/Lex/ModuleMap.h' l='218'/>
<use f='llvm/clang/include/clang/Lex/ModuleMap.h' l='227'/>
<use f='llvm/clang/include/clang/Lex/ModuleMap.h' l='274'/>
<use f='llvm/clang/include/clang/Lex/ModuleMap.h' l='276'/>
<use f='llvm/clang/include/clang/Lex/ModuleMap.h' l='295' c='_ZNK5clang9ModuleMap13resolveExportEPNS_6ModuleERKNS1_20UnresolvedExportDeclEb'/>
<use f='llvm/clang/include/clang/Lex/ModuleMap.h' l='309' c='_ZNK5clang9ModuleMap15resolveModuleIdERKN4llvm11SmallVectorISt4pairINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEENS_14SourceLocationEELj2EEEPNS_6ModuleEb'/>
<use f='llvm/clang/include/clang/Lex/ModuleMap.h' l='309' c='_ZNK5clang9ModuleMap15resolveModuleIdERKN4llvm11SmallVectorISt4pairINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEENS_14SourceLocationEELj2EEEPNS_6ModuleEb'/>
<use f='llvm/clang/include/clang/Lex/ModuleMap.h' l='318' c='_ZN5clang9ModuleMap19addUnresolvedHeaderEPNS_6ModuleENS1_25UnresolvedHeaderDirectiveERb'/>
<use f='llvm/clang/include/clang/Lex/ModuleMap.h' l='332' c='_ZN5clang9ModuleMap10findHeaderEPNS_6ModuleERKNS1_25UnresolvedHeaderDirectiveERN4llvm15SmallVectorImplIcEERb'/>
<use f='llvm/clang/include/clang/Lex/ModuleMap.h' l='341' c='_ZN5clang9ModuleMap13resolveHeaderEPNS_6ModuleERKNS1_25UnresolvedHeaderDirectiveERb'/>
<use f='llvm/clang/include/clang/Lex/ModuleMap.h' l='347' c='_ZN5clang9ModuleMap22resolveAsBuiltinHeaderEPNS_6ModuleERKNS1_25UnresolvedHeaderDirectiveE'/>
<use f='llvm/clang/include/clang/Lex/ModuleMap.h' l='377' c='_ZN5clang9ModuleMap20inferFrameworkModuleEPKNS_14DirectoryEntryENS0_10AttributesEPNS_6ModuleE'/>
<use f='llvm/clang/include/clang/Lex/ModuleMap.h' l='378' c='_ZN5clang9ModuleMap20inferFrameworkModuleEPKNS_14DirectoryEntryENS0_10AttributesEPNS_6ModuleE'/>
<use f='llvm/clang/include/clang/Lex/ModuleMap.h' l='460' c='_ZNK5clang9ModuleMap23resolveHeaderDirectivesEPNS_6ModuleE'/>
<use f='llvm/clang/include/clang/Lex/ModuleMap.h' l='476' c='_ZN5clang9ModuleMap23diagnoseHeaderInclusionEPNS_6ModuleEbNS_14SourceLocationEN4llvm9StringRefEPKNS_9FileEntryE'/>
<use f='llvm/clang/include/clang/Lex/ModuleMap.h' l='488' c='_ZNK5clang9ModuleMap27isHeaderUnavailableInModuleEPKNS_9FileEntryEPKNS_6ModuleE'/>
<use f='llvm/clang/include/clang/Lex/ModuleMap.h' l='495' c='_ZNK5clang9ModuleMap10findModuleEN4llvm9StringRefE'/>
<use f='llvm/clang/include/clang/Lex/ModuleMap.h' l='506' c='_ZNK5clang9ModuleMap23lookupModuleUnqualifiedEN4llvm9StringRefEPNS_6ModuleE'/>
<use f='llvm/clang/include/clang/Lex/ModuleMap.h' l='506' c='_ZNK5clang9ModuleMap23lookupModuleUnqualifiedEN4llvm9StringRefEPNS_6ModuleE'/>
<use f='llvm/clang/include/clang/Lex/ModuleMap.h' l='517' c='_ZNK5clang9ModuleMap21lookupModuleQualifiedEN4llvm9StringRefEPNS_6ModuleE'/>
<use f='llvm/clang/include/clang/Lex/ModuleMap.h' l='517' c='_ZNK5clang9ModuleMap21lookupModuleQualifiedEN4llvm9StringRefEPNS_6ModuleE'/>
<use f='llvm/clang/include/clang/Lex/ModuleMap.h' l='533' c='_ZN5clang9ModuleMap18findOrCreateModuleEN4llvm9StringRefEPNS_6ModuleEbb'/>
<use f='llvm/clang/include/clang/Lex/ModuleMap.h' l='533' c='_ZN5clang9ModuleMap18findOrCreateModuleEN4llvm9StringRefEPNS_6ModuleEbb'/>
<use f='llvm/clang/include/clang/Lex/ModuleMap.h' l='542' c='_ZN5clang9ModuleMap39createGlobalModuleFragmentForModuleUnitENS_14SourceLocationE'/>
<use f='llvm/clang/include/clang/Lex/ModuleMap.h' l='545' c='_ZN5clang9ModuleMap43createPrivateModuleFragmentForInterfaceUnitEPNS_6ModuleENS_14SourceLocationE'/>
<use f='llvm/clang/include/clang/Lex/ModuleMap.h' l='545' c='_ZN5clang9ModuleMap43createPrivateModuleFragmentForInterfaceUnitEPNS_6ModuleENS_14SourceLocationE'/>
<use f='llvm/clang/include/clang/Lex/ModuleMap.h' l='555' c='_ZN5clang9ModuleMap28createModuleForInterfaceUnitENS_14SourceLocationEN4llvm9StringRefEPNS_6ModuleE'/>
<use f='llvm/clang/include/clang/Lex/ModuleMap.h' l='556' c='_ZN5clang9ModuleMap28createModuleForInterfaceUnitENS_14SourceLocationEN4llvm9StringRefEPNS_6ModuleE'/>
<use f='llvm/clang/include/clang/Lex/ModuleMap.h' l='559' c='_ZN5clang9ModuleMap18createHeaderModuleEN4llvm9StringRefENS1_8ArrayRefINS_6Module6HeaderEEE'/>
<use f='llvm/clang/include/clang/Lex/ModuleMap.h' l='563' c='_ZN5clang9ModuleMap20inferFrameworkModuleEPKNS_14DirectoryEntryEbPNS_6ModuleE'/>
<use f='llvm/clang/include/clang/Lex/ModuleMap.h' l='564' c='_ZN5clang9ModuleMap20inferFrameworkModuleEPKNS_14DirectoryEntryEbPNS_6ModuleE'/>
<use f='llvm/clang/include/clang/Lex/ModuleMap.h' l='568' c='_ZN5clang9ModuleMap20createShadowedModuleEN4llvm9StringRefEbPNS_6ModuleE'/>
<use f='llvm/clang/include/clang/Lex/ModuleMap.h' l='569' c='_ZN5clang9ModuleMap20createShadowedModuleEN4llvm9StringRefEbPNS_6ModuleE'/>
<use f='llvm/clang/include/clang/Lex/ModuleMap.h' l='578' c='_ZN5clang9ModuleMap18mayShadowNewModuleEPNS_6ModuleE'/>
<use f='llvm/clang/include/clang/Lex/ModuleMap.h' l='591' c='_ZNK5clang9ModuleMap26getContainingModuleMapFileEPKNS_6ModuleE'/>
<use f='llvm/clang/include/clang/Lex/ModuleMap.h' l='602' c='_ZNK5clang9ModuleMap27getModuleMapFileForUniquingEPKNS_6ModuleE'/>
<use f='llvm/clang/include/clang/Lex/ModuleMap.h' l='604' c='_ZN5clang9ModuleMap26setInferredModuleAllowedByEPNS_6ModuleEPKNS_9FileEntryE'/>
<use f='llvm/clang/include/clang/Lex/ModuleMap.h' l='610' c='_ZN5clang9ModuleMap27getAdditionalModuleMapFilesEPKNS_6ModuleE'/>
<use f='llvm/clang/include/clang/Lex/ModuleMap.h' l='617' c='_ZN5clang9ModuleMap26addAdditionalModuleMapFileEPKNS_6ModuleEPKNS_9FileEntryE'/>
<use f='llvm/clang/include/clang/Lex/ModuleMap.h' l='627' c='_ZN5clang9ModuleMap14resolveExportsEPNS_6ModuleEb'/>
<use f='llvm/clang/include/clang/Lex/ModuleMap.h' l='637' c='_ZN5clang9ModuleMap11resolveUsesEPNS_6ModuleEb'/>
<use f='llvm/clang/include/clang/Lex/ModuleMap.h' l='647' c='_ZN5clang9ModuleMap16resolveConflictsEPNS_6ModuleEb'/>
<use f='llvm/clang/include/clang/Lex/ModuleMap.h' l='651' c='_ZN5clang9ModuleMap17setUmbrellaHeaderEPNS_6ModuleENS_12FileEntryRefEN4llvm5TwineE'/>
<use f='llvm/clang/include/clang/Lex/ModuleMap.h' l='656' c='_ZN5clang9ModuleMap14setUmbrellaDirEPNS_6ModuleENS_17DirectoryEntryRefEN4llvm5TwineE'/>
<use f='llvm/clang/include/clang/Lex/ModuleMap.h' l='661' c='_ZN5clang9ModuleMap9addHeaderEPNS_6ModuleENS1_6HeaderENS0_16ModuleHeaderRoleEb'/>
<use f='llvm/clang/include/clang/Lex/ModuleMap.h' l='665' c='_ZN5clang9ModuleMap13excludeHeaderEPNS_6ModuleENS1_6HeaderE'/>
<use f='llvm/clang/include/clang/Lex/ModuleMap.h' l='701' c='_ZN5clang9ModuleMap15cacheModuleLoadERKNS_14IdentifierInfoEPNS_6ModuleE'/>
<use f='llvm/clang/include/clang/Lex/ModuleMap.h' l='706' c='_ZN5clang9ModuleMap19getCachedModuleLoadERKNS_14IdentifierInfoE'/>
<use f='llvm/clang/include/clang/Lex/Preprocessor.h' l='532'/>
<use f='llvm/clang/include/clang/Lex/Preprocessor.h' l='539'/>
<use f='llvm/clang/include/clang/Lex/Preprocessor.h' l='547' c='_ZN5clang12Preprocessor16IncludeStackInfoC1ENS0_12CurLexerKindEPNS_6ModuleEOSt10unique_ptrINS_5LexerESt14default_deleteIS6_EEPNS_17PreprocessorLexerEO11927613'/>
<use f='llvm/clang/include/clang/Lex/Preprocessor.h' l='722'/>
<use f='llvm/clang/include/clang/Lex/Preprocessor.h' l='736' c='_ZN5clang12Preprocessor21BuildingSubmoduleInfoC1EPNS_6ModuleENS_14SourceLocationEbPNS0_14SubmoduleStateEj'/>
<use f='llvm/clang/include/clang/Lex/Preprocessor.h' l='756'/>
<use f='llvm/clang/include/clang/Lex/Preprocessor.h' l='1009' c='_ZNK5clang12Preprocessor24getCurrentLexerSubmoduleEv'/>
<use f='llvm/clang/include/clang/Lex/Preprocessor.h' l='1061' c='_ZN5clang12Preprocessor27isMacroDefinedInLocalModuleEPKNS_14IdentifierInfoEPNS_6ModuleE'/>
<use f='llvm/clang/include/clang/Lex/Preprocessor.h' l='1152' c='_ZN5clang12Preprocessor14addModuleMacroEPNS_6ModuleEPNS_14IdentifierInfoEPNS_9MacroInfoEN4llvm8ArrayRefIPNS_11ModuleMacroEEERb'/>
<use f='llvm/clang/include/clang/Lex/Preprocessor.h' l='1154' c='_ZN5clang12Preprocessor14getModuleMacroEPNS_6ModuleEPNS_14IdentifierInfoE'/>
<use f='llvm/clang/include/clang/Lex/Preprocessor.h' l='1412' c='_ZN5clang12Preprocessor17makeModuleVisibleEPNS_6ModuleENS_14SourceLocationE'/>
<use f='llvm/clang/include/clang/Lex/Preprocessor.h' l='1414' c='_ZNK5clang12Preprocessor18getModuleImportLocEPNS_6ModuleE'/>
<use f='llvm/clang/include/clang/Lex/Preprocessor.h' l='1930' c='_ZN5clang12Preprocessor34diagnoseMissingHeaderInUmbrellaDirERKNS_6ModuleE'/>
<use f='llvm/clang/include/clang/Lex/Preprocessor.h' l='1987' c='_ZN5clang12Preprocessor16getCurrentModuleEv'/>
<use f='llvm/clang/include/clang/Lex/Preprocessor.h' l='2032' c='_ZN5clang12Preprocessor14EnterSubmoduleEPNS_6ModuleENS_14SourceLocationEb'/>
<use f='llvm/clang/include/clang/Lex/Preprocessor.h' l='2033' c='_ZN5clang12Preprocessor14LeaveSubmoduleEb'/>
<use f='llvm/clang/include/clang/Lex/Preprocessor.h' l='2249'/>
<use f='llvm/clang/include/clang/Lex/Preprocessor.h' l='2251' c='_ZN5clang12Preprocessor12ImportActionC1ENS1_10ActionKindEPNS_6ModuleE'/>
<use f='llvm/clang/include/clang/Lex/Preprocessor.h' l='2287' c='_ZN5clang12Preprocessor22checkModuleIsAvailableERKNS_11LangOptionsERKNS_10TargetInfoERNS_17DiagnosticsEngineEPNS_6ModuleE'/>
<use f='llvm/clang/include/clang/Lex/Preprocessor.h' l='2293' c='_ZN5clang12Preprocessor20getModuleForLocationENS_14SourceLocationE'/>
<use f='llvm/clang/include/clang/Frontend/FrontendAction.h' l='161' c='_ZNK5clang14FrontendAction16getCurrentModuleEv'/>
<size>1896</size>
<doc f='llvm/clang/include/clang/Basic/Module.h' l='95'>/// Describes a module or submodule.</doc>
<mbr r='clang::Module::Name' o='0' t='std::string'/>
<mbr r='clang::Module::DefinitionLoc' o='256' t='clang::SourceLocation'/>
<mbr r='clang::Module::Kind' o='288' t='clang::Module::ModuleKind'/>
<mbr r='clang::Module::Parent' o='320' t='clang::Module *'/>
<mbr r='clang::Module::Directory' o='384' t='const clang::DirectoryEntry *'/>
<mbr r='clang::Module::PresumedModuleMapFile' o='448' t='std::string'/>
<mbr r='clang::Module::Umbrella' o='704' t='llvm::PointerUnion&lt;const FileEntryRef::MapEntry *, const DirectoryEntryRef::MapEntry *&gt;'/>
<mbr r='clang::Module::Signature' o='768' t='clang::ASTFileSignature'/>
<mbr r='clang::Module::UmbrellaAsWritten' o='960' t='std::string'/>
<mbr r='clang::Module::ExportAsModule' o='1216' t='std::string'/>
<fun r='_ZNK5clang6Module15isModulePurviewEv'/>
<mbr r='clang::Module::SubModules' o='1472' t='std::vector&lt;Module *&gt;'/>
<mbr r='clang::Module::SubModuleIndex' o='1664' t='llvm::StringMap&lt;unsigned int&gt;'/>
<mbr r='clang::Module::ASTFile' o='1920' t='Optional&lt;clang::FileEntryRef&gt;'/>
<mbr r='clang::Module::TopHeaders' o='1984' t='llvm::SmallSetVector&lt;const FileEntry *, 2&gt;'/>
<mbr r='clang::Module::TopHeaderNames' o='2432' t='std::vector&lt;std::string&gt;'/>
<mbr r='clang::Module::VisibleModulesCache' o='2624' t='llvm::DenseSet&lt;const Module *&gt;'/>
<mbr r='clang::Module::VisibilityID' o='2816' t='unsigned int'/>
<smbr r='clang::Module::NumHeaderKinds' t='const int'/>
<mbr r='clang::Module::Headers' o='2880' t='SmallVector&lt;clang::Module::Header, 2&gt; [5]'/>
<mbr r='clang::Module::UnresolvedHeaders' o='6720' t='SmallVector&lt;clang::Module::UnresolvedHeaderDirective, 1&gt;'/>
<mbr r='clang::Module::MissingHeaders' o='7488' t='SmallVector&lt;clang::Module::UnresolvedHeaderDirective, 1&gt;'/>
<mbr r='clang::Module::Requirements' o='8256' t='SmallVector&lt;clang::Module::Requirement, 2&gt;'/>
<mbr r='clang::Module::ShadowingModule' o='9024' t='clang::Module *'/>
<mbr r='clang::Module::IsUnimportable' o='9088' t='unsigned int'/>
<mbr r='clang::Module::HasIncompatibleModuleFile' o='9089' t='unsigned int'/>
<mbr r='clang::Module::IsAvailable' o='9090' t='unsigned int'/>
<mbr r='clang::Module::IsFromModuleFile' o='9091' t='unsigned int'/>
<mbr r='clang::Module::IsFramework' o='9092' t='unsigned int'/>
<mbr r='clang::Module::IsExplicit' o='9093' t='unsigned int'/>
<mbr r='clang::Module::IsSystem' o='9094' t='unsigned int'/>
<mbr r='clang::Module::IsExternC' o='9095' t='unsigned int'/>
<mbr r='clang::Module::IsInferred' o='9096' t='unsigned int'/>
<mbr r='clang::Module::InferSubmodules' o='9097' t='unsigned int'/>
<mbr r='clang::Module::InferExplicitSubmodules' o='9098' t='unsigned int'/>
<mbr r='clang::Module::InferExportWildcard' o='9099' t='unsigned int'/>
<mbr r='clang::Module::ConfigMacrosExhaustive' o='9100' t='unsigned int'/>
<mbr r='clang::Module::NoUndeclaredIncludes' o='9101' t='unsigned int'/>
<mbr r='clang::Module::ModuleMapIsPrivate' o='9102' t='unsigned int'/>
<mbr r='clang::Module::NameVisibility' o='9120' t='clang::Module::NameVisibilityKind'/>
<mbr r='clang::Module::InferredSubmoduleLoc' o='9152' t='clang::SourceLocation'/>
<mbr r='clang::Module::Imports' o='9216' t='llvm::SmallSetVector&lt;Module *, 2&gt;'/>
<mbr r='clang::Module::Exports' o='9664' t='SmallVector&lt;clang::Module::ExportDecl, 2&gt;'/>
<mbr r='clang::Module::UnresolvedExports' o='9920' t='SmallVector&lt;clang::Module::UnresolvedExportDecl, 2&gt;'/>
<mbr r='clang::Module::DirectUses' o='11840' t='SmallVector&lt;clang::Module *, 2&gt;'/>
<mbr r='clang::Module::UnresolvedDirectUses' o='12096' t='SmallVector&lt;clang::ModuleId, 2&gt;'/>
<mbr r='clang::Module::LinkLibraries' o='13760' t='llvm::SmallVector&lt;LinkLibrary, 2&gt;'/>
<mbr r='clang::Module::UseExportAsModuleLinkName' o='14528' t='bool'/>
<mbr r='clang::Module::ConfigMacros' o='14592' t='std::vector&lt;std::string&gt;'/>
<mbr r='clang::Module::UnresolvedConflicts' o='14784' t='std::vector&lt;UnresolvedConflict&gt;'/>
<mbr r='clang::Module::Conflicts' o='14976' t='std::vector&lt;Conflict&gt;'/>
<fun r='_ZN5clang6ModuleC1EN4llvm9StringRefENS_14SourceLocationEPS0_bbj'/>
<fun r='_ZN5clang6ModuleD1Ev'/>
<fun r='_ZNK5clang6Module14isUnimportableEv'/>
<fun r='_ZNK5clang6Module14isUnimportableERKNS_11LangOptionsERKNS_10TargetInfoERSt4pairINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEbERPS0_'/>
<fun r='_ZNK5clang6Module11isAvailableEv'/>
<fun r='_ZNK5clang6Module11isAvailableERKNS_11LangOptionsERKNS_10TargetInfoERSt4pairINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEbERNS0_25UnresolvedHeaderDirectiveERPS0_'/>
<fun r='_ZNK5clang6Module11isSubModuleEv'/>
<fun r='_ZNK5clang6Module13isSubModuleOfEPKS0_'/>
<fun r='_ZNK5clang6Module17isPartOfFrameworkEv'/>
<fun r='_ZNK5clang6Module14isSubFrameworkEv'/>
<fun r='_ZN5clang6Module9setParentEPS0_'/>
<fun r='_ZNK5clang6Module17getFullModuleNameB5cxx11Eb'/>
<fun r='_ZNK5clang6Module16fullModuleNameIsEN4llvm8ArrayRefINS1_9StringRefEEE'/>
<fun r='_ZN5clang6Module17getTopLevelModuleEv'/>
<fun r='_ZNK5clang6Module17getTopLevelModuleEv'/>
<fun r='_ZNK5clang6Module21getTopLevelModuleNameEv'/>
<fun r='_ZNK5clang6Module10getASTFileEv'/>
<fun r='_ZN5clang6Module10setASTFileEN4llvm8OptionalINS_12FileEntryRefEEE'/>
<fun r='_ZNK5clang6Module14getUmbrellaDirEv'/>
<fun r='_ZNK5clang6Module17getUmbrellaHeaderEv'/>
<fun r='_ZNK5clang6Module14hasUmbrellaDirEv'/>
<fun r='_ZN5clang6Module12addTopHeaderEPKNS_9FileEntryE'/>
<fun r='_ZN5clang6Module20addTopHeaderFilenameEN4llvm9StringRefE'/>
<fun r='_ZN5clang6Module13getTopHeadersERNS_11FileManagerE'/>
<fun r='_ZNK5clang6Module12directlyUsesEPKS0_'/>
<fun r='_ZN5clang6Module14addRequirementEN4llvm9StringRefEbRKNS_11LangOptionsERKNS_10TargetInfoE'/>
<fun r='_ZN5clang6Module15markUnavailableEb'/>
<fun r='_ZNK5clang6Module13findSubmoduleEN4llvm9StringRefE'/>
<fun r='_ZN5clang6Module20findOrInferSubmoduleEN4llvm9StringRefE'/>
<fun r='_ZNK5clang6Module15isModuleVisibleEPKS0_'/>
<fun r='_ZNK5clang6Module15getVisibilityIDEv'/>
<fun r='_ZN5clang6Module15submodule_beginEv'/>
<fun r='_ZNK5clang6Module15submodule_beginEv'/>
<fun r='_ZN5clang6Module13submodule_endEv'/>
<fun r='_ZNK5clang6Module13submodule_endEv'/>
<fun r='_ZN5clang6Module10submodulesEv'/>
<fun r='_ZNK5clang6Module10submodulesEv'/>
<fun r='_ZNK5clang6Module18getExportedModulesERN4llvm15SmallVectorImplIPS0_EE'/>
<fun r='_ZN5clang6Module24getModuleInputBufferNameEv'/>
<fun r='_ZNK5clang6Module5printERN4llvm11raw_ostreamEj'/>
<fun r='_ZNK5clang6Module4dumpEv'/>
<fun r='_ZNK5clang6Module24buildVisibleModulesCacheEv'/>
<use f='llvm/clang/include/clang/Sema/Sema.h' l='2117'/>
<use f='llvm/clang/include/clang/Sema/Sema.h' l='2129' c='_ZNK5clang4Sema16getCurrentModuleEv'/>
<use f='llvm/clang/include/clang/Sema/Sema.h' l='2137' c='_ZN5clang4Sema15getOwningModuleEPKNS_4DeclE'/>
<use f='llvm/clang/include/clang/Sema/Sema.h' l='2145' c='_ZN5clang4Sema15isModuleVisibleEPKNS_6ModuleEb'/>
<use f='llvm/clang/include/clang/Sema/Sema.h' l='2149' c='_ZN5clang4Sema17makeModuleVisibleEPNS_6ModuleENS_14SourceLocationE'/>
<use f='llvm/clang/include/clang/Sema/Sema.h' l='2161' c='_ZN5clang4Sema21hasVisibleDeclarationEPKNS_9NamedDeclEPN4llvm15SmallVectorImplIPNS_6ModuleEEE'/>
<use f='llvm/clang/include/clang/Sema/Sema.h' l='2165' c='_ZN5clang4Sema25hasVisibleDeclarationSlowEPKNS_9NamedDeclEPN4llvm15SmallVectorImplIPNS_6ModuleEEE'/>
<use f='llvm/clang/include/clang/Sema/Sema.h' l='2186' c='_ZN5clang4Sema25hasVisibleDefaultArgumentEPKNS_9NamedDeclEPN4llvm15SmallVectorImplIPNS_6ModuleEEE'/>
<use f='llvm/clang/include/clang/Sema/Sema.h' l='2192' c='_ZN5clang4Sema32hasVisibleExplicitSpecializationEPKNS_9NamedDeclEPN4llvm15SmallVectorImplIPNS_6ModuleEEE'/>
<use f='llvm/clang/include/clang/Sema/Sema.h' l='2197' c='_ZN5clang4Sema30hasVisibleMemberSpecializationEPKNS_9NamedDeclEPN4llvm15SmallVectorImplIPNS_6ModuleEEE'/>
<use f='llvm/clang/include/clang/Sema/Sema.h' l='2864' c='_ZN5clang4Sema17ActOnModuleImportENS_14SourceLocationES1_S1_PNS_6ModuleEN4llvm8ArrayRefISt4pairIPNS_14IdentifierInfoES1_EEE'/>
<use f='llvm/clang/include/clang/Sema/Sema.h' l='2869' c='_ZN5clang4Sema18ActOnModuleIncludeENS_14SourceLocationEPNS_6ModuleE'/>
<use f='llvm/clang/include/clang/Sema/Sema.h' l='2870' c='_ZN5clang4Sema18BuildModuleIncludeENS_14SourceLocationEPNS_6ModuleE'/>
<use f='llvm/clang/include/clang/Sema/Sema.h' l='2873' c='_ZN5clang4Sema16ActOnModuleBeginENS_14SourceLocationEPNS_6ModuleE'/>
<use f='llvm/clang/include/clang/Sema/Sema.h' l='2875' c='_ZN5clang4Sema14ActOnModuleEndENS_14SourceLocationEPNS_6ModuleE'/>
<use f='llvm/clang/include/clang/Sema/Sema.h' l='2884' c='_ZN5clang4Sema42createImplicitModuleImportForErrorRecoveryENS_14SourceLocationEPNS_6ModuleE'/>
<use f='llvm/clang/include/clang/Sema/Sema.h' l='2901' c='_ZN5clang4Sema21diagnoseMissingImportENS_14SourceLocationEPNS_9NamedDeclES1_N4llvm8ArrayRefIPNS_6ModuleEEENS0_17MissingImportKindEb'/>
<use f='llvm/clang/include/clang/Sema/Sema.h' l='8682'/>
<use f='llvm/clang/include/clang/Sema/Sema.h' l='8687'/>
<use f='llvm/clang/include/clang/Sema/Sema.h' l='8692' c='_ZN5clang4Sema16getLookupModulesEv'/>
<size>1896</size>
<use f='llvm/clang/include/clang/Frontend/CompilerInstance.h' l='798' c='_ZN5clang16CompilerInstance17makeModuleVisibleEPNS_6ModuleENS1_18NameVisibilityKindENS_14SourceLocationE'/>
<size>1896</size>
<use f='llvm/clang/include/clang/Lex/ExternalPreprocessorSource.h' l='42' c='_ZN5clang26ExternalPreprocessorSource9getModuleEj'/>
<use f='llvm/clang/include/clang/Lex/DirectoryLookup.h' l='182' c='_ZNK5clang15DirectoryLookup10LookupFileERN4llvm9StringRefERNS_12HeaderSearchENS_14SourceLocationEPNS1_15SmallVectorImplIcEES9_PNS_6ModuleEPNS_9ModuleM3995184'/>
<use f='llvm/clang/include/clang/Lex/DirectoryLookup.h' l='190' c='_ZNK5clang15DirectoryLookup17DoFrameworkLookupEN4llvm9StringRefERNS_12HeaderSearchEPNS1_15SmallVectorImplIcEES7_PNS_6ModuleEPNS_9ModuleMap11KnownHeaderERbSD_'/>
<use f='llvm/clang/include/clang/Lex/HeaderSearch.h' l='406' c='_ZN5clang12HeaderSearch10LookupFileEN4llvm9StringRefENS_14SourceLocationEbPKNS_15DirectoryLookupERS6_NS1_8ArrayRefISt4pairIPKNS_9FileEntryEPKNS_14Dire14579246'/>
<use f='llvm/clang/include/clang/Lex/HeaderSearch.h' l='419' c='_ZN5clang12HeaderSearch24LookupSubframeworkHeaderEN4llvm9StringRefEPKNS_9FileEntryEPNS1_15SmallVectorImplIcEES8_PNS_6ModuleEPNS_9ModuleMap11KnownHeaderE'/>
<use f='llvm/clang/include/clang/Lex/HeaderSearch.h' l='434' c='_ZN5clang12HeaderSearch22ShouldEnterIncludeFileERNS_12PreprocessorEPKNS_9FileEntryEbbPNS_6ModuleE'/>
<use f='llvm/clang/include/clang/Lex/HeaderSearch.h' l='509' c='_ZN5clang12HeaderSearch23getCachedModuleFileNameB5cxx11EPNS_6ModuleE'/>
<use f='llvm/clang/include/clang/Lex/HeaderSearch.h' l='531' c='_ZN5clang12HeaderSearch33getPrebuiltImplicitModuleFileNameB5cxx11EPNS_6ModuleE'/>
<use f='llvm/clang/include/clang/Lex/HeaderSearch.h' l='558' c='_ZN5clang12HeaderSearch12lookupModuleEN4llvm9StringRefEbb'/>
<use f='llvm/clang/include/clang/Lex/HeaderSearch.h' l='613' c='_ZN5clang12HeaderSearch17collectAllModulesERN4llvm15SmallVectorImplIPNS_6ModuleEEE'/>
<use f='llvm/clang/include/clang/Lex/HeaderSearch.h' l='632' c='_ZN5clang12HeaderSearch12lookupModuleEN4llvm9StringRefES2_b'/>
<use f='llvm/clang/include/clang/Lex/HeaderSearch.h' l='662' c='_ZN5clang12HeaderSearch19loadFrameworkModuleEN4llvm9StringRefEPKNS_14DirectoryEntryEb'/>
<use f='llvm/clang/include/clang/Lex/HeaderSearch.h' l='676' c='_ZN5clang12HeaderSearch25findUsableModuleForHeaderEPKNS_9FileEntryEPKNS_14DirectoryEntryEPNS_6ModuleEPNS_9ModuleMap11KnownHeaderEb'/>
<use f='llvm/clang/include/clang/Lex/HeaderSearch.h' l='686' c='_ZN5clang12HeaderSearch34findUsableModuleForFrameworkHeaderEPKNS_9FileEntryEN4llvm9StringRefEPNS_6ModuleEPNS_9ModuleMap11KnownHeaderEb'/>
<use f='llvm/clang/include/clang/Lex/HeaderSearch.h' l='694' c='_ZN5clang12HeaderSearch23getFileAndSuggestModuleEN4llvm9StringRefENS_14SourceLocationEPKNS_14DirectoryEntryEbPNS_6ModuleEPNS_9ModuleMap11KnownHeaderE'/>
<use f='llvm/clang/include/clang/Serialization/ASTReader.h' l='664'/>
<use f='llvm/clang/include/clang/Serialization/ASTReader.h' l='676'/>
<use f='llvm/clang/include/clang/Serialization/ASTReader.h' l='688'/>
<use f='llvm/clang/include/clang/Serialization/ASTReader.h' l='1579' c='_ZN5clang9ASTReader17makeModuleVisibleEPNS_6ModuleENS1_18NameVisibilityKindENS_14SourceLocationE'/>
<use f='llvm/clang/include/clang/Serialization/ASTReader.h' l='1584' c='_ZN5clang9ASTReader16makeNamesVisibleERKN4llvm11SmallVectorIPNS_4DeclELj2EEEPNS_6ModuleE'/>
<use f='llvm/clang/include/clang/Serialization/ASTReader.h' l='2089' c='_ZN5clang9ASTReader12getSubmoduleEj'/>
<use f='llvm/clang/include/clang/Serialization/ASTReader.h' l='2094' c='_ZN5clang9ASTReader9getModuleEj'/>
<size>1896</size>
<use f='llvm/clang/include/clang/Serialization/ASTDeserializationListener.h' l='54' c='_ZN5clang26ASTDeserializationListener10ModuleReadEjPNS_6ModuleE'/>
<use f='llvm/clang/include/clang/Frontend/MultiplexConsumer.h' l='42' c='_ZN5clang35MultiplexASTDeserializationListener10ModuleReadEjPNS_6ModuleE'/>
<size>1896</size>
<use f='llvm/clang/include/clang/AST/ASTMutationListener.h' l='140' c='_ZN5clang19ASTMutationListener25RedefinedHiddenDefinitionEPKNS_9NamedDeclEPNS_6ModuleE'/>
<use f='llvm/clang/lib/AST/ASTContext.cpp' l='1086' c='_ZN5clang10ASTContext25mergeDefinitionIntoModuleEPNS_9NamedDeclEPNS_6ModuleEb'/>
<use f='llvm/clang/lib/AST/ASTContext.cpp' l='1101' c='_ZN5clang10ASTContext30deduplicateMergedDefinitonsForEPNS_9NamedDeclE'/>
<use f='llvm/clang/lib/AST/ASTContext.cpp' l='1102' c='_ZN5clang10ASTContext30deduplicateMergedDefinitonsForEPNS_9NamedDeclE'/>
<use f='llvm/clang/lib/AST/ASTContext.cpp' l='1108' c='_ZN5clang10ASTContext30getModulesWithMergedDefinitionEPKNS_9NamedDeclE'/>
<use f='llvm/clang/lib/AST/ASTContext.cpp' l='1134' c='_ZN5clang10ASTContext20addModuleInitializerEPNS_6ModuleEPNS_4DeclE'/>
<use f='llvm/clang/lib/AST/ASTContext.cpp' l='1160' c='_ZN5clang10ASTContext25addLazyModuleInitializersEPNS_6ModuleEN4llvm8ArrayRefIjEE'/>
<use f='llvm/clang/lib/AST/ASTContext.cpp' l='1168' c='_ZN5clang10ASTContext21getModuleInitializersEPNS_6ModuleE'/>
<size>1896</size>
<use f='llvm/clang/lib/AST/Decl.cpp' l='1496' c='_ZNK5clang4Decl25getOwningModuleForLinkageEb'/>
<use f='llvm/clang/lib/AST/Decl.cpp' l='1497' c='_ZNK5clang4Decl25getOwningModuleForLinkageEb'/>
<use f='llvm/clang/lib/AST/Decl.cpp' l='5029' c='_ZL23getNumModuleIdentifiersPN5clang6ModuleE'/>
<use f='llvm/clang/lib/AST/Decl.cpp' l='5039' c='_ZN5clang10ImportDeclC1EPNS_11DeclContextENS_14SourceLocationEPNS_6ModuleEN4llvm8ArrayRefIS3_EE'/>
<use f='llvm/clang/lib/AST/Decl.cpp' l='5050' c='_ZN5clang10ImportDeclC1EPNS_11DeclContextENS_14SourceLocationEPNS_6ModuleES3_'/>
<use f='llvm/clang/lib/AST/Decl.cpp' l='5057' c='_ZN5clang10ImportDecl6CreateERNS_10ASTContextEPNS_11DeclContextENS_14SourceLocationEPNS_6ModuleEN4llvm8ArrayRefIS5_EE'/>
<use f='llvm/clang/lib/AST/Decl.cpp' l='5066' c='_ZN5clang10ImportDecl14CreateImplicitERNS_10ASTContextEPNS_11DeclContextENS_14SourceLocationEPNS_6ModuleES5_'/>
<size>1896</size>
<use f='llvm/clang/lib/AST/DeclBase.cpp' l='103' c='_ZN5clang4DeclnwEmRKNS_10ASTContextEPNS_11DeclContextEm'/>
<use f='llvm/clang/lib/AST/DeclBase.cpp' l='105' c='_ZN5clang4DeclnwEmRKNS_10ASTContextEPNS_11DeclContextEm'/>
<use f='llvm/clang/lib/AST/DeclBase.cpp' l='109' c='_ZN5clang4DeclnwEmRKNS_10ASTContextEPNS_11DeclContextEm'/>
<use f='llvm/clang/lib/AST/DeclBase.cpp' l='114' c='_ZNK5clang4Decl19getOwningModuleSlowEv'/>
<use f='llvm/clang/lib/AST/ItaniumMangle.cpp' l='471' c='_ZN12_GLOBAL__N_114CXXNameMangler16mangleModuleNameEPKN5clang6ModuleE'/>
<use f='llvm/clang/lib/AST/ItaniumMangle.cpp' l='916' c='_ZN12_GLOBAL__N_114CXXNameMangler21mangleNameWithAbiTagsEN5clang10GlobalDeclEPKN4llvm11SmallVectorINS3_9StringRefELj4EEE'/>
<use f='llvm/clang/lib/AST/ItaniumMangle.cpp' l='935' c='_ZN12_GLOBAL__N_114CXXNameMangler16mangleModuleNameEPKN5clang6ModuleE'/>
<size>1896</size>
<use f='llvm/clang/lib/AST/TextNodeDumper.cpp' l='261' c='_ZN5clang14TextNodeDumper5VisitEPKNS_4DeclE'/>
<use f='llvm/clang/lib/AST/TextNodeDumper.cpp' l='264' c='_ZN5clang14TextNodeDumper5VisitEPKNS_4DeclE'/>
<size>1896</size>
<use f='llvm/clang/lib/Basic/Module.cpp' l='37' c='_ZN5clang6ModuleC1EN4llvm9StringRefENS_14SourceLocationEPS0_bbj'/>
<use f='llvm/clang/lib/Basic/Module.cpp' l='132' c='_ZNK5clang6Module14isUnimportableERKNS_11LangOptionsERKNS_10TargetInfoERSt4pairINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEbERPS0_'/>
<use f='llvm/clang/lib/Basic/Module.cpp' l='136' c='_ZNK5clang6Module14isUnimportableERKNS_11LangOptionsERKNS_10TargetInfoERSt4pairINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEbERPS0_'/>
<use f='llvm/clang/lib/Basic/Module.cpp' l='156' c='_ZNK5clang6Module11isAvailableERKNS_11LangOptionsERKNS_10TargetInfoERSt4pairINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEbERNS0_25UnresolvedHeaderDirectiveERPS0_'/>
<use f='llvm/clang/lib/Basic/Module.cpp' l='165' c='_ZNK5clang6Module11isAvailableERKNS_11LangOptionsERKNS_10TargetInfoERSt4pairINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEbERNS0_25UnresolvedHeaderDirectiveERPS0_'/>
<use f='llvm/clang/lib/Basic/Module.cpp' l='175' c='_ZNK5clang6Module13isSubModuleOfEPKS0_'/>
<use f='llvm/clang/lib/Basic/Module.cpp' l='183' c='_ZNK5clang6Module17getTopLevelModuleEv'/>
<use f='llvm/clang/lib/Basic/Module.cpp' l='184' c='_ZNK5clang6Module17getTopLevelModuleEv'/>
<use f='llvm/clang/lib/Basic/Module.cpp' l='225' c='_ZNK5clang6Module17getFullModuleNameB5cxx11Eb'/>
<use f='llvm/clang/lib/Basic/Module.cpp' l='238' c='_ZNK5clang6Module16fullModuleNameIsEN4llvm8ArrayRefINS1_9StringRefEEE'/>
<use f='llvm/clang/lib/Basic/Module.cpp' l='274' c='_ZNK5clang6Module12directlyUsesEPKS0_'/>
<use f='llvm/clang/lib/Basic/Module.cpp' l='305' c='_ZN5clang6Module15markUnavailableEb'/>
<use f='llvm/clang/lib/Basic/Module.cpp' l='312' c='_ZN5clang6Module15markUnavailableEb'/>
<use f='llvm/clang/lib/Basic/Module.cpp' l='315' c='_ZN5clang6Module15markUnavailableEb'/>
<use f='llvm/clang/lib/Basic/Module.cpp' l='332' c='_ZNK5clang6Module13findSubmoduleEN4llvm9StringRefE'/>
<use f='llvm/clang/lib/Basic/Module.cpp' l='340' c='_ZN5clang6Module20findOrInferSubmoduleEN4llvm9StringRefE'/>
<use f='llvm/clang/lib/Basic/Module.cpp' l='346' c='_ZN5clang6Module20findOrInferSubmoduleEN4llvm9StringRefE'/>
<use f='llvm/clang/lib/Basic/Module.cpp' l='346' c='_ZN5clang6Module20findOrInferSubmoduleEN4llvm9StringRefE'/>
<use f='llvm/clang/lib/Basic/Module.cpp' l='355' c='_ZNK5clang6Module18getExportedModulesERN4llvm15SmallVectorImplIPS0_EE'/>
<use f='llvm/clang/lib/Basic/Module.cpp' l='360' c='_ZNK5clang6Module18getExportedModulesERN4llvm15SmallVectorImplIPS0_EE'/>
<use f='llvm/clang/lib/Basic/Module.cpp' l='368' c='_ZNK5clang6Module18getExportedModulesERN4llvm15SmallVectorImplIPS0_EE'/>
<use f='llvm/clang/lib/Basic/Module.cpp' l='370' c='_ZNK5clang6Module18getExportedModulesERN4llvm15SmallVectorImplIPS0_EE'/>
<use f='llvm/clang/lib/Basic/Module.cpp' l='384' c='_ZNK5clang6Module18getExportedModulesERN4llvm15SmallVectorImplIPS0_EE'/>
<use f='llvm/clang/lib/Basic/Module.cpp' l='398' c='_ZNK5clang6Module18getExportedModulesERN4llvm15SmallVectorImplIPS0_EE'/>
<use f='llvm/clang/lib/Basic/Module.cpp' l='403' c='_ZNK5clang6Module18getExportedModulesERN4llvm15SmallVectorImplIPS0_EE'/>
<use f='llvm/clang/lib/Basic/Module.cpp' l='425' c='_ZNK5clang6Module24buildVisibleModulesCacheEv'/>
<use f='llvm/clang/lib/Basic/Module.cpp' l='427' c='_ZNK5clang6Module24buildVisibleModulesCacheEv'/>
<use f='llvm/clang/lib/Basic/Module.cpp' l='546' c='_ZNK5clang6Module5printERN4llvm11raw_ostreamEj'/>
<use f='llvm/clang/lib/Basic/Module.cpp' l='628' c='_ZN5clang16VisibleModuleSet10setVisibleEPNS_6ModuleENS_14SourceLocationEN4llvm12function_refIFvS2_EEENS5_IFvNS4_8ArrayRefIS2_EES2_NS4_9StringRefEEEE'/>
<use f='llvm/clang/lib/Basic/Module.cpp' l='637' c='_ZN5clang16VisibleModuleSet10setVisibleEPNS_6ModuleENS_14SourceLocationEN4llvm12function_refIFvS2_EEENS5_IFvNS4_8ArrayRefIS2_EES2_NS4_9StringRefEEEE'/>
<use f='llvm/clang/lib/Basic/Module.cpp' l='653' c='_ZN5clang16VisibleModuleSet10setVisibleEPNS_6ModuleENS_14SourceLocationEN4llvm12function_refIFvS2_EEENS5_IFvNS4_8ArrayRefIS2_EES2_NS4_9StringRefEEEE'/>
<use f='llvm/clang/lib/Basic/Module.cpp' l='655' c='_ZN5clang16VisibleModuleSet10setVisibleEPNS_6ModuleENS_14SourceLocationEN4llvm12function_refIFvS2_EEENS5_IFvNS4_8ArrayRefIS2_EES2_NS4_9StringRefEEEE'/>
<use f='llvm/clang/lib/Basic/Module.cpp' l='663' c='_ZN5clang16VisibleModuleSet10setVisibleEPNS_6ModuleENS_14SourceLocationEN4llvm12function_refIFvS2_EEENS5_IFvNS4_8ArrayRefIS2_EES2_NS4_9StringRefEEEE'/>
<use f='llvm/clang/lib/Basic/Module.cpp' l='673' c='_ZN5clang19ASTSourceDescriptorC1ERNS_6ModuleE'/>
<size>1896</size>
<fun r='_ZN5clang6ModuleC1EN4llvm9StringRefENS_14SourceLocationEPS0_bbj'/>
<fun r='_ZN5clang6ModuleD1Ev'/>
<fun r='_ZNK5clang6Module14isUnimportableERKNS_11LangOptionsERKNS_10TargetInfoERSt4pairINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEbERPS0_'/>
<fun r='_ZNK5clang6Module11isAvailableERKNS_11LangOptionsERKNS_10TargetInfoERSt4pairINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEbERNS0_25UnresolvedHeaderDirectiveERPS0_'/>
<fun r='_ZNK5clang6Module13isSubModuleOfEPKS0_'/>
<fun r='_ZNK5clang6Module17getTopLevelModuleEv'/>
<fun r='_ZNK5clang6Module17getFullModuleNameB5cxx11Eb'/>
<fun r='_ZNK5clang6Module16fullModuleNameIsEN4llvm8ArrayRefINS1_9StringRefEEE'/>
<fun r='_ZNK5clang6Module14getUmbrellaDirEv'/>
<fun r='_ZN5clang6Module12addTopHeaderEPKNS_9FileEntryE'/>
<fun r='_ZN5clang6Module13getTopHeadersERNS_11FileManagerE'/>
<fun r='_ZNK5clang6Module12directlyUsesEPKS0_'/>
<fun r='_ZN5clang6Module14addRequirementEN4llvm9StringRefEbRKNS_11LangOptionsERKNS_10TargetInfoE'/>
<fun r='_ZN5clang6Module15markUnavailableEb'/>
<fun r='_ZNK5clang6Module13findSubmoduleEN4llvm9StringRefE'/>
<fun r='_ZN5clang6Module20findOrInferSubmoduleEN4llvm9StringRefE'/>
<fun r='_ZNK5clang6Module18getExportedModulesERN4llvm15SmallVectorImplIPS0_EE'/>
<fun r='_ZNK5clang6Module24buildVisibleModulesCacheEv'/>
<fun r='_ZNK5clang6Module5printERN4llvm11raw_ostreamEj'/>
<fun r='_ZNK5clang6Module4dumpEv'/>
<use f='llvm/clang/lib/CodeGen/CGDebugInfo.h' l='127'/>
<use f='llvm/clang/lib/CodeGen/CodeGenModule.h' l='477'/>
<use f='llvm/clang/lib/CodeGen/CodeGenModule.h' l='481'/>
<size>1896</size>
<use f='llvm/clang/lib/CodeGen/CGDebugInfo.cpp' l='2532' c='_ZN5clang7CodeGen11CGDebugInfo20getOrCreateModuleRefENS_19ASTSourceDescriptorEb'/>
<use f='llvm/clang/lib/CodeGen/CGDebugInfo.cpp' l='3205' c='_ZN5clang7CodeGen11CGDebugInfo21getParentModuleOrNullEPKNS_4DeclE'/>
<use f='llvm/clang/lib/CodeGen/CGDebugInfo.cpp' l='4879' c='_ZN5clang7CodeGen11CGDebugInfo14EmitImportDeclERKNS_10ImportDeclE'/>
<size>1896</size>
<use f='llvm/clang/lib/CodeGen/MacroPPCallbacks.h' l='106' c='_ZN5clang16MacroPPCallbacks18InclusionDirectiveENS_14SourceLocationERKNS_5TokenEN4llvm9StringRefEbNS_15CharSourceRangeEPKNS_9FileEntryES6_S6_PKNS_6Mod2747158'/>
<size>1896</size>
<use f='llvm/clang/lib/CodeGen/CodeGenModule.cpp' l='2167' c='_ZL23addLinkOptionsPostorderRN5clang7CodeGen13CodeGenModuleEPNS_6ModuleERN4llvm15SmallVectorImplIPNS5_6MDNodeEEERNS5_11SmallPtrSetIS4_Lj16EEE'/>
<use f='llvm/clang/lib/CodeGen/CodeGenModule.cpp' l='2169' c='_ZL23addLinkOptionsPostorderRN5clang7CodeGen13CodeGenModuleEPNS_6ModuleERN4llvm15SmallVectorImplIPNS5_6MDNodeEEERNS5_11SmallPtrSetIS4_Lj16EEE'/>
<use f='llvm/clang/lib/CodeGen/CodeGenModule.cpp' l='2224' c='_ZN5clang7CodeGen13CodeGenModule21EmitModuleLinkOptionsEv'/>
<use f='llvm/clang/lib/CodeGen/CodeGenModule.cpp' l='2225' c='_ZN5clang7CodeGen13CodeGenModule21EmitModuleLinkOptionsEv'/>
<use f='llvm/clang/lib/CodeGen/CodeGenModule.cpp' l='2226' c='_ZN5clang7CodeGen13CodeGenModule21EmitModuleLinkOptionsEv'/>
<use f='llvm/clang/lib/CodeGen/CodeGenModule.cpp' l='2229' c='_ZN5clang7CodeGen13CodeGenModule21EmitModuleLinkOptionsEv'/>
<use f='llvm/clang/lib/CodeGen/CodeGenModule.cpp' l='2242' c='_ZN5clang7CodeGen13CodeGenModule21EmitModuleLinkOptionsEv'/>
<use f='llvm/clang/lib/CodeGen/CodeGenModule.cpp' l='2271' c='_ZN5clang7CodeGen13CodeGenModule21EmitModuleLinkOptionsEv'/>
<use f='llvm/clang/lib/CodeGen/CodeGenModule.cpp' l='5769' c='_ZN5clang7CodeGen13CodeGenModule16EmitTopLevelDeclEPNS_4DeclE'/>
<use f='llvm/clang/lib/CodeGen/CodeGenModule.cpp' l='5770' c='_ZN5clang7CodeGen13CodeGenModule16EmitTopLevelDeclEPNS_4DeclE'/>
<use f='llvm/clang/lib/CodeGen/CodeGenModule.cpp' l='5775' c='_ZN5clang7CodeGen13CodeGenModule16EmitTopLevelDeclEPNS_4DeclE'/>
<size>1896</size>
<use f='llvm/clang/lib/CodeGen/MacroPPCallbacks.cpp' l='171' c='_ZN5clang16MacroPPCallbacks18InclusionDirectiveENS_14SourceLocationERKNS_5TokenEN4llvm9StringRefEbNS_15CharSourceRangeEPKNS_9FileEntryES6_S6_PKNS_6Mod2747158'/>
<size>1896</size>
<use f='llvm/clang/include/clang/Index/USRGeneration.h' l='82' c='_ZN5clang5index24generateFullUSRForModuleEPKNS_6ModuleERN4llvm11raw_ostreamE'/>
<use f='llvm/clang/include/clang/Index/USRGeneration.h' l='90' c='_ZN5clang5index28generateUSRFragmentForModuleEPKNS_6ModuleERN4llvm11raw_ostreamE'/>
<size>1896</size>
<use f='llvm/clang/include/clang/Serialization/ASTWriter.h' l='141'/>
<use f='llvm/clang/include/clang/Serialization/ASTWriter.h' l='352'/>
<use f='llvm/clang/include/clang/Serialization/ASTWriter.h' l='364' c='_ZN5clang9ASTWriter10DeclUpdateC1EjPNS_6ModuleE'/>
<use f='llvm/clang/include/clang/Serialization/ASTWriter.h' l='377' c='_ZNK5clang9ASTWriter10DeclUpdate9getModuleEv'/>
<use f='llvm/clang/include/clang/Serialization/ASTWriter.h' l='453'/>
<use f='llvm/clang/include/clang/Serialization/ASTWriter.h' l='460' c='_ZN5clang9ASTWriter14getSubmoduleIDEPNS_6ModuleE'/>
<use f='llvm/clang/include/clang/Serialization/ASTWriter.h' l='485' c='_ZN5clang9ASTWriter15WriteSubmodulesEPNS_6ModuleE'/>
<use f='llvm/clang/include/clang/Serialization/ASTWriter.h' l='548' c='_ZN5clang9ASTWriter12WriteASTCoreERNS_4SemaEN4llvm9StringRefERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEPNS_6ModuleE'/>
<use f='llvm/clang/include/clang/Serialization/ASTWriter.h' l='586' c='_ZN5clang9ASTWriter8WriteASTERNS_4SemaERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEPNS_6ModuleEN4llvm9StringRefEbb'/>
<use f='llvm/clang/include/clang/Serialization/ASTWriter.h' l='676' c='_ZN5clang9ASTWriter29getLocalOrImportedSubmoduleIDEPNS_6ModuleE'/>
<use f='llvm/clang/include/clang/Serialization/ASTWriter.h' l='728' c='_ZN5clang9ASTWriter10ModuleReadEjPNS_6ModuleE'/>
<use f='llvm/clang/include/clang/Serialization/ASTWriter.h' l='760' c='_ZN5clang9ASTWriter25RedefinedHiddenDefinitionEPKNS_9NamedDeclEPNS_6ModuleE'/>
<use f='llvm/clang/lib/Frontend/ASTUnit.cpp' l='926' c='_ZL28AddTopLevelDeclarationToHashPN5clang4DeclERj'/>
<size>1896</size>
<use f='llvm/clang/include/clang/Sema/MultiplexExternalSemaSource.h' l='154' c='_ZN5clang27MultiplexExternalSemaSource9getModuleEj'/>
<size>1896</size>
<use f='llvm/clang/lib/Frontend/CompilerInstance.cpp' l='1169' c='_ZL13compileModuleRN5clang16CompilerInstanceENS_14SourceLocationEPNS_6ModuleEN4llvm9StringRefE'/>
<use f='llvm/clang/lib/Frontend/CompilerInstance.cpp' l='1240' c='_ZL23compileModuleAndReadASTRN5clang16CompilerInstanceENS_14SourceLocationES2_PNS_6ModuleEN4llvm9StringRefE'/>
<use f='llvm/clang/lib/Frontend/CompilerInstance.cpp' l='1323' c='_ZL16checkConfigMacroRN5clang12PreprocessorEN4llvm9StringRefEPNS_6ModuleENS_14SourceLocationE'/>
<use f='llvm/clang/lib/Frontend/CompilerInstance.cpp' l='1544' c='_ZZN5clang16CompilerInstance14loadModuleFileEN4llvm9StringRefEEN15ReadModuleNames18markAllUnavailableEv'/>
<use f='llvm/clang/lib/Frontend/CompilerInstance.cpp' l='1552' c='_ZZN5clang16CompilerInstance14loadModuleFileEN4llvm9StringRefEEN15ReadModuleNames18markAllUnavailableEv'/>
<use f='llvm/clang/lib/Frontend/CompilerInstance.cpp' l='1555' c='_ZZN5clang16CompilerInstance14loadModuleFileEN4llvm9StringRefEEN15ReadModuleNames18markAllUnavailableEv'/>
<use f='llvm/clang/lib/Frontend/CompilerInstance.cpp' l='1619' c='_ZL18selectModuleSourcePN5clang6ModuleEN4llvm9StringRefERNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKSt3mapIS9_S9_St4lessIvESaISt4pairIKS9_S13465666'/>
<use f='llvm/clang/lib/Frontend/CompilerInstance.cpp' l='1657' c='_ZN5clang16CompilerInstance29findOrCompileModuleAndReadASTEN4llvm9StringRefENS_14SourceLocationES3_b'/>
<use f='llvm/clang/lib/Frontend/CompilerInstance.cpp' l='1844' c='_ZN5clang16CompilerInstance10loadModuleENS_14SourceLocationEN4llvm8ArrayRefISt4pairIPNS_14IdentifierInfoES1_EEENS_6Module18NameVisibilityKindEb'/>
<use f='llvm/clang/lib/Frontend/CompilerInstance.cpp' l='1888' c='_ZN5clang16CompilerInstance10loadModuleENS_14SourceLocationEN4llvm8ArrayRefISt4pairIPNS_14IdentifierInfoES1_EEENS_6Module18NameVisibilityKindEb'/>
<use f='llvm/clang/lib/Frontend/CompilerInstance.cpp' l='2002' c='_ZN5clang16CompilerInstance10loadModuleENS_14SourceLocationEN4llvm8ArrayRefISt4pairIPNS_14IdentifierInfoES1_EEENS_6Module18NameVisibilityKindEb'/>
<use f='llvm/clang/lib/Frontend/CompilerInstance.cpp' l='2072' c='_ZN5clang16CompilerInstance17makeModuleVisibleEPNS_6ModuleENS1_18NameVisibilityKindENS_14SourceLocationE'/>
<use f='llvm/clang/lib/Frontend/CompilerInstance.cpp' l='2122' c='_ZN5clang16CompilerInstance21loadGlobalModuleIndexENS_14SourceLocationE'/>
<size>1896</size>
<use f='llvm/clang/lib/Frontend/DependencyFile.cpp' l='71' c='_ZN12_GLOBAL__N_123DepCollectorPPCallbacks18InclusionDirectiveEN5clang14SourceLocationERKNS1_5TokenEN4llvm9StringRefEbNS1_15CharSourceRangeEPKNS1_9Fil15924456'/>
<size>1896</size>
<use f='llvm/clang/lib/Frontend/DependencyGraph.cpp' l='52' c='_ZN12_GLOBAL__N_123DependencyGraphCallback18InclusionDirectiveEN5clang14SourceLocationERKNS1_5TokenEN4llvm9StringRefEbNS1_15CharSourceRangeEPKNS1_9Fil1053258'/>
<use f='llvm/clang/lib/Frontend/DependencyGraph.cpp' l='77' c='_ZN12_GLOBAL__N_123DependencyGraphCallback18InclusionDirectiveEN5clang14SourceLocationERKNS1_5TokenEN4llvm9StringRefEbNS1_15CharSourceRangeEPKNS1_9Fil1053258'/>
<size>1896</size>
<use f='llvm/clang/lib/Frontend/FrontendAction.cpp' l='143' c='_ZNK5clang14FrontendAction16getCurrentModuleEv'/>
<use f='llvm/clang/lib/Frontend/FrontendAction.cpp' l='317' c='_ZL27collectModuleHeaderIncludesRKN5clang11LangOptionsERNS_11FileManagerERNS_17DiagnosticsEngineERNS_9ModuleMapEPNS_6ModuleERN4llvm15SmallVectorImplIcEE'/>
<use f='llvm/clang/lib/Frontend/FrontendAction.cpp' l='458' c='_ZL20prepareToBuildModuleRN5clang16CompilerInstanceEN4llvm9StringRefE'/>
<use f='llvm/clang/lib/Frontend/FrontendAction.cpp' l='472' c='_ZL20prepareToBuildModuleRN5clang16CompilerInstanceEN4llvm9StringRefE'/>
<use f='llvm/clang/lib/Frontend/FrontendAction.cpp' l='524' c='_ZL23getInputBufferForModuleRN5clang16CompilerInstanceEPNS_6ModuleE'/>
<use f='llvm/clang/lib/Frontend/FrontendAction.cpp' l='616' c='_ZN5clang14FrontendAction15BeginSourceFileERNS_16CompilerInstanceERKNS_17FrontendInputFileE'/>
<size>1896</size>
<use f='llvm/clang/lib/Frontend/ModuleDependencyCollector.cpp' l='52' c='_ZN12_GLOBAL__N_127ModuleDependencyPPCallbacks18InclusionDirectiveEN5clang14SourceLocationERKNS1_5TokenEN4llvm9StringRefEbNS1_15CharSourceRangeEPKNS1_5767932'/>
<size>1896</size>
<use f='llvm/clang/lib/Frontend/MultiplexConsumer.cpp' l='71' c='_ZN5clang35MultiplexASTDeserializationListener10ModuleReadEjPNS_6ModuleE'/>
<use f='llvm/clang/lib/Frontend/MultiplexConsumer.cpp' l='109' c='_ZN5clang28MultiplexASTMutationListener25RedefinedHiddenDefinitionEPKNS_9NamedDeclEPNS_6ModuleE'/>
<use f='llvm/clang/lib/Frontend/MultiplexConsumer.cpp' l='223' c='_ZN5clang28MultiplexASTMutationListener25RedefinedHiddenDefinitionEPKNS_9NamedDeclEPNS_6ModuleE'/>
<use f='llvm/clang/lib/Frontend/PrecompiledPreamble.cpp' l='104' c='_ZN12_GLOBAL__N_120MissingFileCollector18InclusionDirectiveEN5clang14SourceLocationERKNS1_5TokenEN4llvm9StringRefEbNS1_15CharSourceRangeEPKNS1_9FileEn3230152'/>
<size>1896</size>
<use f='llvm/clang/lib/Frontend/PrintPreprocessedOutput.cpp' l='132' c='_ZN12_GLOBAL__N_124PrintPPOutputPPCallbacks18InclusionDirectiveEN5clang14SourceLocationERKNS1_5TokenEN4llvm9StringRefEbNS1_15CharSourceRangeEPKNS1_9Fi4968174'/>
<use f='llvm/clang/lib/Frontend/PrintPreprocessedOutput.cpp' l='182' c='_ZN12_GLOBAL__N_124PrintPPOutputPPCallbacks11BeginModuleEPKN5clang6ModuleE'/>
<use f='llvm/clang/lib/Frontend/PrintPreprocessedOutput.cpp' l='183' c='_ZN12_GLOBAL__N_124PrintPPOutputPPCallbacks9EndModuleEPKN5clang6ModuleE'/>
<use f='llvm/clang/lib/Frontend/PrintPreprocessedOutput.cpp' l='334' c='_ZN12_GLOBAL__N_124PrintPPOutputPPCallbacks18InclusionDirectiveEN5clang14SourceLocationERKNS1_5TokenEN4llvm9StringRefEbNS1_15CharSourceRangeEPKNS1_9Fi4968174'/>
<use f='llvm/clang/lib/Frontend/PrintPreprocessedOutput.cpp' l='385' c='_ZN12_GLOBAL__N_124PrintPPOutputPPCallbacks11BeginModuleEPKN5clang6ModuleE'/>
<use f='llvm/clang/lib/Frontend/PrintPreprocessedOutput.cpp' l='392' c='_ZN12_GLOBAL__N_124PrintPPOutputPPCallbacks9EndModuleEPKN5clang6ModuleE'/>
<use f='llvm/clang/lib/Frontend/PrintPreprocessedOutput.cpp' l='765' c='_ZL23PrintPreprocessedTokensRN5clang12PreprocessorERNS_5TokenEPN12_GLOBAL__N_124PrintPPOutputPPCallbacksERN4llvm11raw_ostreamE'/>
<use f='llvm/clang/lib/Frontend/PrintPreprocessedOutput.cpp' l='770' c='_ZL23PrintPreprocessedTokensRN5clang12PreprocessorERNS_5TokenEPN12_GLOBAL__N_124PrintPPOutputPPCallbacksERN4llvm11raw_ostreamE'/>
<use f='llvm/clang/lib/Frontend/PrintPreprocessedOutput.cpp' l='778' c='_ZL23PrintPreprocessedTokensRN5clang12PreprocessorERNS_5TokenEPN12_GLOBAL__N_124PrintPPOutputPPCallbacksERN4llvm11raw_ostreamE'/>
<use f='llvm/clang/lib/Frontend/PrintPreprocessedOutput.cpp' l='778' c='_ZL23PrintPreprocessedTokensRN5clang12PreprocessorERNS_5TokenEPN12_GLOBAL__N_124PrintPPOutputPPCallbacksERN4llvm11raw_ostreamE'/>
<size>1896</size>
<use f='llvm/clang/lib/Frontend/Rewrite/InclusionRewriter.cpp' l='49'/>
<use f='llvm/clang/lib/Frontend/Rewrite/InclusionRewriter.cpp' l='51'/>
<use f='llvm/clang/lib/Frontend/Rewrite/InclusionRewriter.cpp' l='69' c='_ZN12_GLOBAL__N_117InclusionRewriter17handleModuleBeginERN5clang5TokenE'/>
<use f='llvm/clang/lib/Frontend/Rewrite/InclusionRewriter.cpp' l='81' c='_ZN12_GLOBAL__N_117InclusionRewriter18InclusionDirectiveEN5clang14SourceLocationERKNS1_5TokenEN4llvm9StringRefEbNS1_15CharSourceRangeEPKNS1_9FileEntry14791813'/>
<use f='llvm/clang/lib/Frontend/Rewrite/InclusionRewriter.cpp' l='90' c='_ZN12_GLOBAL__N_117InclusionRewriter25WriteImplicitModuleImportEPKN5clang6ModuleE'/>
<use f='llvm/clang/lib/Frontend/Rewrite/InclusionRewriter.cpp' l='98' c='_ZNK12_GLOBAL__N_117InclusionRewriter20FindModuleAtLocationEN5clang14SourceLocationE'/>
<use f='llvm/clang/lib/Frontend/Rewrite/InclusionRewriter.cpp' l='99' c='_ZNK12_GLOBAL__N_117InclusionRewriter17FindEnteredModuleEN5clang14SourceLocationE'/>
<use f='llvm/clang/lib/Frontend/Rewrite/InclusionRewriter.cpp' l='147' c='_ZN12_GLOBAL__N_117InclusionRewriter25WriteImplicitModuleImportEPKN5clang6ModuleE'/>
<use f='llvm/clang/lib/Frontend/Rewrite/InclusionRewriter.cpp' l='197' c='_ZN12_GLOBAL__N_117InclusionRewriter18InclusionDirectiveEN5clang14SourceLocationERKNS1_5TokenEN4llvm9StringRefEbNS1_15CharSourceRangeEPKNS1_9FileEntry14791813'/>
<use f='llvm/clang/lib/Frontend/Rewrite/InclusionRewriter.cpp' l='234' c='_ZNK12_GLOBAL__N_117InclusionRewriter20FindModuleAtLocationEN5clang14SourceLocationE'/>
<use f='llvm/clang/lib/Frontend/Rewrite/InclusionRewriter.cpp' l='244' c='_ZNK12_GLOBAL__N_117InclusionRewriter17FindEnteredModuleEN5clang14SourceLocationE'/>
<use f='llvm/clang/lib/Frontend/Rewrite/InclusionRewriter.cpp' l='427' c='_ZN12_GLOBAL__N_117InclusionRewriter7ProcessEN5clang6FileIDENS1_6SrcMgr18CharacteristicKindEPKNS1_15DirectoryLookupE'/>
<use f='llvm/clang/lib/Frontend/Rewrite/InclusionRewriter.cpp' l='430' c='_ZN12_GLOBAL__N_117InclusionRewriter7ProcessEN5clang6FileIDENS1_6SrcMgr18CharacteristicKindEPKNS1_15DirectoryLookupE'/>
<size>1896</size>
<use f='llvm/clang/include/clang/Index/IndexDataConsumer.h' l='61' c='_ZN5clang5index17IndexDataConsumer22handleModuleOccurrenceEPKNS_10ImportDeclEPKNS_6ModuleEjNS_14SourceLocationE'/>
<size>1896</size>
<use f='llvm/clang/lib/Index/IndexingContext.cpp' l='94' c='_ZL22reportModuleReferencesPKN5clang6ModuleEN4llvm8ArrayRefINS_14SourceLocationEEEPKNS_10ImportDeclERNS_5index17IndexDataConsumerE'/>
<use f='llvm/clang/lib/Index/IndexingContext.cpp' l='137' c='_ZN5clang5index15IndexingContext14importedModuleEPKNS_10ImportDeclE'/>
<size>1896</size>
<use f='llvm/clang/lib/Index/USRGeneration.cpp' l='1133' c='_ZN5clang5index24generateFullUSRForModuleEPKNS_6ModuleERN4llvm11raw_ostreamE'/>
<use f='llvm/clang/lib/Index/USRGeneration.cpp' l='1148' c='_ZN5clang5index28generateUSRFragmentForModuleEPKNS_6ModuleERN4llvm11raw_ostreamE'/>
<size>1896</size>
<use f='llvm/clang/lib/Lex/HeaderSearch.cpp' l='139' c='_ZN5clang12HeaderSearch23getCachedModuleFileNameB5cxx11EPNS_6ModuleE'/>
<use f='llvm/clang/lib/Lex/HeaderSearch.cpp' l='167' c='_ZN5clang12HeaderSearch33getPrebuiltImplicitModuleFileNameB5cxx11EPNS_6ModuleE'/>
<use f='llvm/clang/lib/Lex/HeaderSearch.cpp' l='232' c='_ZN5clang12HeaderSearch12lookupModuleEN4llvm9StringRefEbb'/>
<use f='llvm/clang/lib/Lex/HeaderSearch.cpp' l='235' c='_ZN5clang12HeaderSearch12lookupModuleEN4llvm9StringRefEbb'/>
<use f='llvm/clang/lib/Lex/HeaderSearch.cpp' l='257' c='_ZN5clang12HeaderSearch12lookupModuleEN4llvm9StringRefES2_b'/>
<use f='llvm/clang/lib/Lex/HeaderSearch.cpp' l='259' c='_ZN5clang12HeaderSearch12lookupModuleEN4llvm9StringRefES2_b'/>
<use f='llvm/clang/lib/Lex/HeaderSearch.cpp' l='347' c='_ZN5clang12HeaderSearch23getFileAndSuggestModuleEN4llvm9StringRefENS_14SourceLocationEPKNS_14DirectoryEntryEbPNS_6ModuleEPNS_9ModuleMap11KnownHeaderE'/>
<use f='llvm/clang/lib/Lex/HeaderSearch.cpp' l='379' c='_ZNK5clang15DirectoryLookup10LookupFileERN4llvm9StringRefERNS_12HeaderSearchENS_14SourceLocationEPNS1_15SmallVectorImplIcEES9_PNS_6ModuleEPNS_9ModuleM3995184'/>
<use f='llvm/clang/lib/Lex/HeaderSearch.cpp' l='505' c='_ZL16needModuleLookupPN5clang6ModuleEb'/>
<use f='llvm/clang/lib/Lex/HeaderSearch.cpp' l='515' c='_ZNK5clang15DirectoryLookup17DoFrameworkLookupEN4llvm9StringRefERNS_12HeaderSearchEPNS1_15SmallVectorImplIcEES7_PNS_6ModuleEPNS_9ModuleMap11KnownHeaderERbSD_'/>
<use f='llvm/clang/lib/Lex/HeaderSearch.cpp' l='759' c='_ZN5clang12HeaderSearch10LookupFileEN4llvm9StringRefENS_14SourceLocationEbPKNS_15DirectoryLookupERS6_NS1_8ArrayRefISt4pairIPKNS_9FileEntryEPKNS_14Dire14579246'/>
<use f='llvm/clang/lib/Lex/HeaderSearch.cpp' l='1047' c='_ZN5clang12HeaderSearch24LookupSubframeworkHeaderEN4llvm9StringRefEPKNS_9FileEntryEPNS1_15SmallVectorImplIcEES8_PNS_6ModuleEPNS_9ModuleMap11KnownHeaderE'/>
<use f='llvm/clang/lib/Lex/HeaderSearch.cpp' l='1272' c='_ZN5clang12HeaderSearch22ShouldEnterIncludeFileERNS_12PreprocessorEPKNS_9FileEntryEbbPNS_6ModuleE'/>
<use f='llvm/clang/lib/Lex/HeaderSearch.cpp' l='1433' c='_ZL13suggestModuleRN5clang12HeaderSearchEPKNS_9FileEntryEPNS_6ModuleEPNS_9ModuleMap11KnownHeaderE'/>
<use f='llvm/clang/lib/Lex/HeaderSearch.cpp' l='1466' c='_ZN5clang12HeaderSearch25findUsableModuleForHeaderEPKNS_9FileEntryEPKNS_14DirectoryEntryEPNS_6ModuleEPNS_9ModuleMap11KnownHeaderEb'/>
<use f='llvm/clang/lib/Lex/HeaderSearch.cpp' l='1477' c='_ZN5clang12HeaderSearch34findUsableModuleForFrameworkHeaderEPKNS_9FileEntryEN4llvm9StringRefEPNS_6ModuleEPNS_9ModuleMap11KnownHeaderEb'/>
<use f='llvm/clang/lib/Lex/HeaderSearch.cpp' l='1625' c='_ZN5clang12HeaderSearch19loadFrameworkModuleEN4llvm9StringRefEPKNS_14DirectoryEntryEb'/>
<use f='llvm/clang/lib/Lex/HeaderSearch.cpp' l='1628' c='_ZN5clang12HeaderSearch19loadFrameworkModuleEN4llvm9StringRefEPKNS_14DirectoryEntryEb'/>
<use f='llvm/clang/lib/Lex/HeaderSearch.cpp' l='1681' c='_ZN5clang12HeaderSearch17collectAllModulesERN4llvm15SmallVectorImplIPNS_6ModuleEEE'/>
<size>1896</size>
<use f='llvm/clang/lib/Lex/MacroInfo.cpp' l='241' c='_ZN5clang11ModuleMacro6createERNS_12PreprocessorEPNS_6ModuleEPNS_14IdentifierInfoEPNS_9MacroInfoEN4llvm8ArrayRefIPS0_EE'/>
<size>1896</size>
<use f='llvm/clang/lib/Lex/ModuleMap.cpp' l='58' c='_ZN5clang9ModuleMap25resolveLinkAsDependenciesEPNS_6ModuleE'/>
<use f='llvm/clang/lib/Lex/ModuleMap.cpp' l='69' c='_ZN5clang9ModuleMap19addLinkAsDependencyEPNS_6ModuleE'/>
<use f='llvm/clang/lib/Lex/ModuleMap.cpp' l='108' c='_ZNK5clang9ModuleMap13resolveExportEPNS_6ModuleERKNS1_20UnresolvedExportDeclEb'/>
<use f='llvm/clang/lib/Lex/ModuleMap.cpp' l='118' c='_ZNK5clang9ModuleMap13resolveExportEPNS_6ModuleERKNS1_20UnresolvedExportDeclEb'/>
<use f='llvm/clang/lib/Lex/ModuleMap.cpp' l='125' c='_ZNK5clang9ModuleMap15resolveModuleIdERKN4llvm11SmallVectorISt4pairINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEENS_14SourceLocationEELj2EEEPNS_6ModuleEb'/>
<use f='llvm/clang/lib/Lex/ModuleMap.cpp' l='125' c='_ZNK5clang9ModuleMap15resolveModuleIdERKN4llvm11SmallVectorISt4pairINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEENS_14SourceLocationEELj2EEEPNS_6ModuleEb'/>
<use f='llvm/clang/lib/Lex/ModuleMap.cpp' l='128' c='_ZNK5clang9ModuleMap15resolveModuleIdERKN4llvm11SmallVectorISt4pairINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEENS_14SourceLocationEELj2EEEPNS_6ModuleEb'/>
<use f='llvm/clang/lib/Lex/ModuleMap.cpp' l='139' c='_ZNK5clang9ModuleMap15resolveModuleIdERKN4llvm11SmallVectorISt4pairINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEENS_14SourceLocationEELj2EEEPNS_6ModuleEb'/>
<use f='llvm/clang/lib/Lex/ModuleMap.cpp' l='157' c='_ZL23appendSubframeworkPathsPN5clang6ModuleERN4llvm15SmallVectorImplIcEE'/>
<use f='llvm/clang/lib/Lex/ModuleMap.cpp' l='175' c='_ZN5clang9ModuleMap10findHeaderEPNS_6ModuleERKNS1_25UnresolvedHeaderDirectiveERN4llvm15SmallVectorImplIcEERb'/>
<use f='llvm/clang/lib/Lex/ModuleMap.cpp' l='250' c='_ZN5clang9ModuleMap13resolveHeaderEPNS_6ModuleERKNS1_25UnresolvedHeaderDirectiveERb'/>
<use f='llvm/clang/lib/Lex/ModuleMap.cpp' l='258' c='_ZN5clang9ModuleMap13resolveHeaderEPNS_6ModuleERKNS1_25UnresolvedHeaderDirectiveERb'/>
<use f='llvm/clang/lib/Lex/ModuleMap.cpp' l='290' c='_ZN5clang9ModuleMap22resolveAsBuiltinHeaderEPNS_6ModuleERKNS1_25UnresolvedHeaderDirectiveE'/>
<use f='llvm/clang/lib/Lex/ModuleMap.cpp' l='445' c='_ZL22violatesPrivateIncludePN5clang6ModuleEPKNS_9FileEntryENS_9ModuleMap11KnownHeaderE'/>
<use f='llvm/clang/lib/Lex/ModuleMap.cpp' l='468' c='_ZL17getTopLevelOrNullPN5clang6ModuleE'/>
<use f='llvm/clang/lib/Lex/ModuleMap.cpp' l='468' c='_ZL17getTopLevelOrNullPN5clang6ModuleE'/>
<use f='llvm/clang/lib/Lex/ModuleMap.cpp' l='472' c='_ZN5clang9ModuleMap23diagnoseHeaderInclusionEPNS_6ModuleEbNS_14SourceLocationEN4llvm9StringRefEPKNS_9FileEntryE'/>
<use f='llvm/clang/lib/Lex/ModuleMap.cpp' l='488' c='_ZN5clang9ModuleMap23diagnoseHeaderInclusionEPNS_6ModuleEbNS_14SourceLocationEN4llvm9StringRefEPKNS_9FileEntryE'/>
<use f='llvm/clang/lib/Lex/ModuleMap.cpp' l='489' c='_ZN5clang9ModuleMap23diagnoseHeaderInclusionEPNS_6ModuleEbNS_14SourceLocationEN4llvm9StringRefEPKNS_9FileEntryE'/>
<use f='llvm/clang/lib/Lex/ModuleMap.cpp' l='603' c='_ZN5clang9ModuleMap40findOrCreateModuleForHeaderInUmbrellaDirEPKNS_9FileEntryE'/>
<use f='llvm/clang/lib/Lex/ModuleMap.cpp' l='607' c='_ZN5clang9ModuleMap40findOrCreateModuleForHeaderInUmbrellaDirEPKNS_9FileEntryE'/>
<use f='llvm/clang/lib/Lex/ModuleMap.cpp' l='696' c='_ZNK5clang9ModuleMap27isHeaderUnavailableInModuleEPKNS_9FileEntryEPKNS_6ModuleE'/>
<use f='llvm/clang/lib/Lex/ModuleMap.cpp' l='725' c='_ZNK5clang9ModuleMap27isHeaderUnavailableInModuleEPKNS_9FileEntryEPKNS_6ModuleE'/>
<use f='llvm/clang/lib/Lex/ModuleMap.cpp' l='736' c='_ZNK5clang9ModuleMap27isHeaderUnavailableInModuleEPKNS_9FileEntryEPKNS_6ModuleE'/>
<use f='llvm/clang/lib/Lex/ModuleMap.cpp' l='742' c='_ZNK5clang9ModuleMap27isHeaderUnavailableInModuleEPKNS_9FileEntryEPKNS_6ModuleE'/>
<use f='llvm/clang/lib/Lex/ModuleMap.cpp' l='790' c='_ZNK5clang9ModuleMap10findModuleEN4llvm9StringRefE'/>
<use f='llvm/clang/lib/Lex/ModuleMap.cpp' l='798' c='_ZNK5clang9ModuleMap23lookupModuleUnqualifiedEN4llvm9StringRefEPNS_6ModuleE'/>
<use f='llvm/clang/lib/Lex/ModuleMap.cpp' l='799' c='_ZNK5clang9ModuleMap23lookupModuleUnqualifiedEN4llvm9StringRefEPNS_6ModuleE'/>
<use f='llvm/clang/lib/Lex/ModuleMap.cpp' l='801' c='_ZNK5clang9ModuleMap23lookupModuleUnqualifiedEN4llvm9StringRefEPNS_6ModuleE'/>
<use f='llvm/clang/lib/Lex/ModuleMap.cpp' l='808' c='_ZNK5clang9ModuleMap21lookupModuleQualifiedEN4llvm9StringRefEPNS_6ModuleE'/>
<use f='llvm/clang/lib/Lex/ModuleMap.cpp' l='808' c='_ZNK5clang9ModuleMap21lookupModuleQualifiedEN4llvm9StringRefEPNS_6ModuleE'/>
<use f='llvm/clang/lib/Lex/ModuleMap.cpp' l='815' c='_ZN5clang9ModuleMap18findOrCreateModuleEN4llvm9StringRefEPNS_6ModuleEbb'/>
<use f='llvm/clang/lib/Lex/ModuleMap.cpp' l='816' c='_ZN5clang9ModuleMap18findOrCreateModuleEN4llvm9StringRefEPNS_6ModuleEbb'/>
<use f='llvm/clang/lib/Lex/ModuleMap.cpp' l='820' c='_ZN5clang9ModuleMap18findOrCreateModuleEN4llvm9StringRefEPNS_6ModuleEbb'/>
<use f='llvm/clang/lib/Lex/ModuleMap.cpp' l='824' c='_ZN5clang9ModuleMap18findOrCreateModuleEN4llvm9StringRefEPNS_6ModuleEbb'/>
<use f='llvm/clang/lib/Lex/ModuleMap.cpp' l='824' c='_ZN5clang9ModuleMap18findOrCreateModuleEN4llvm9StringRefEPNS_6ModuleEbb'/>
<use f='llvm/clang/lib/Lex/ModuleMap.cpp' l='835' c='_ZN5clang9ModuleMap39createGlobalModuleFragmentForModuleUnitENS_14SourceLocationE'/>
<use f='llvm/clang/lib/Lex/ModuleMap.cpp' l='837' c='_ZN5clang9ModuleMap39createGlobalModuleFragmentForModuleUnitENS_14SourceLocationE'/>
<use f='llvm/clang/lib/Lex/ModuleMap.cpp' l='843' c='_ZN5clang9ModuleMap43createPrivateModuleFragmentForInterfaceUnitEPNS_6ModuleENS_14SourceLocationE'/>
<use f='llvm/clang/lib/Lex/ModuleMap.cpp' l='844' c='_ZN5clang9ModuleMap43createPrivateModuleFragmentForInterfaceUnitEPNS_6ModuleENS_14SourceLocationE'/>
<use f='llvm/clang/lib/Lex/ModuleMap.cpp' l='847' c='_ZN5clang9ModuleMap43createPrivateModuleFragmentForInterfaceUnitEPNS_6ModuleENS_14SourceLocationE'/>
<use f='llvm/clang/lib/Lex/ModuleMap.cpp' l='853' c='_ZN5clang9ModuleMap28createModuleForInterfaceUnitENS_14SourceLocationEN4llvm9StringRefEPNS_6ModuleE'/>
<use f='llvm/clang/lib/Lex/ModuleMap.cpp' l='855' c='_ZN5clang9ModuleMap28createModuleForInterfaceUnitENS_14SourceLocationEN4llvm9StringRefEPNS_6ModuleE'/>
<use f='llvm/clang/lib/Lex/ModuleMap.cpp' l='860' c='_ZN5clang9ModuleMap28createModuleForInterfaceUnitENS_14SourceLocationEN4llvm9StringRefEPNS_6ModuleE'/>
<use f='llvm/clang/lib/Lex/ModuleMap.cpp' l='881' c='_ZN5clang9ModuleMap18createHeaderModuleEN4llvm9StringRefENS1_8ArrayRefINS_6Module6HeaderEEE'/>
<use f='llvm/clang/lib/Lex/ModuleMap.cpp' l='887' c='_ZN5clang9ModuleMap18createHeaderModuleEN4llvm9StringRefENS1_8ArrayRefINS_6Module6HeaderEEE'/>
<use f='llvm/clang/lib/Lex/ModuleMap.cpp' l='893' c='_ZN5clang9ModuleMap18createHeaderModuleEN4llvm9StringRefENS1_8ArrayRefINS_6Module6HeaderEEE'/>
<use f='llvm/clang/lib/Lex/ModuleMap.cpp' l='906' c='_ZL18inferFrameworkLinkPN5clang6ModuleEPKNS_14DirectoryEntryERNS_11FileManagerE'/>
<use f='llvm/clang/lib/Lex/ModuleMap.cpp' l='929' c='_ZN5clang9ModuleMap20inferFrameworkModuleEPKNS_14DirectoryEntryEbPNS_6ModuleE'/>
<use f='llvm/clang/lib/Lex/ModuleMap.cpp' l='930' c='_ZN5clang9ModuleMap20inferFrameworkModuleEPKNS_14DirectoryEntryEbPNS_6ModuleE'/>
<use f='llvm/clang/lib/Lex/ModuleMap.cpp' l='936' c='_ZN5clang9ModuleMap20inferFrameworkModuleEPKNS_14DirectoryEntryENS0_10AttributesEPNS_6ModuleE'/>
<use f='llvm/clang/lib/Lex/ModuleMap.cpp' l='937' c='_ZN5clang9ModuleMap20inferFrameworkModuleEPKNS_14DirectoryEntryENS0_10AttributesEPNS_6ModuleE'/>
<use f='llvm/clang/lib/Lex/ModuleMap.cpp' l='953' c='_ZN5clang9ModuleMap20inferFrameworkModuleEPKNS_14DirectoryEntryENS0_10AttributesEPNS_6ModuleE'/>
<use f='llvm/clang/lib/Lex/ModuleMap.cpp' l='1023' c='_ZN5clang9ModuleMap20inferFrameworkModuleEPKNS_14DirectoryEntryENS0_10AttributesEPNS_6ModuleE'/>
<use f='llvm/clang/lib/Lex/ModuleMap.cpp' l='1023' c='_ZN5clang9ModuleMap20inferFrameworkModuleEPKNS_14DirectoryEntryENS0_10AttributesEPNS_6ModuleE'/>
<use f='llvm/clang/lib/Lex/ModuleMap.cpp' l='1109' c='_ZN5clang9ModuleMap20createShadowedModuleEN4llvm9StringRefEbPNS_6ModuleE'/>
<use f='llvm/clang/lib/Lex/ModuleMap.cpp' l='1110' c='_ZN5clang9ModuleMap20createShadowedModuleEN4llvm9StringRefEbPNS_6ModuleE'/>
<use f='llvm/clang/lib/Lex/ModuleMap.cpp' l='1113' c='_ZN5clang9ModuleMap20createShadowedModuleEN4llvm9StringRefEbPNS_6ModuleE'/>
<use f='llvm/clang/lib/Lex/ModuleMap.cpp' l='1114' c='_ZN5clang9ModuleMap20createShadowedModuleEN4llvm9StringRefEbPNS_6ModuleE'/>
<use f='llvm/clang/lib/Lex/ModuleMap.cpp' l='1124' c='_ZN5clang9ModuleMap17setUmbrellaHeaderEPNS_6ModuleENS_12FileEntryRefEN4llvm5TwineE'/>
<use f='llvm/clang/lib/Lex/ModuleMap.cpp' l='1136' c='_ZN5clang9ModuleMap14setUmbrellaDirEPNS_6ModuleENS_17DirectoryEntryRefEN4llvm5TwineE'/>
<use f='llvm/clang/lib/Lex/ModuleMap.cpp' l='1143' c='_ZN5clang9ModuleMap19addUnresolvedHeaderEPNS_6ModuleENS1_25UnresolvedHeaderDirectiveERb'/>
<use f='llvm/clang/lib/Lex/ModuleMap.cpp' l='1195' c='_ZNK5clang9ModuleMap23resolveHeaderDirectivesEPNS_6ModuleE'/>
<use f='llvm/clang/lib/Lex/ModuleMap.cpp' l='1204' c='_ZN5clang9ModuleMap9addHeaderEPNS_6ModuleENS1_6HeaderENS0_16ModuleHeaderRoleEb'/>
<use f='llvm/clang/lib/Lex/ModuleMap.cpp' l='1233' c='_ZN5clang9ModuleMap13excludeHeaderEPNS_6ModuleENS1_6HeaderE'/>
<use f='llvm/clang/lib/Lex/ModuleMap.cpp' l='1244' c='_ZNK5clang9ModuleMap26getContainingModuleMapFileEPKNS_6ModuleE'/>
<use f='llvm/clang/lib/Lex/ModuleMap.cpp' l='1252' c='_ZNK5clang9ModuleMap27getModuleMapFileForUniquingEPKNS_6ModuleE'/>
<use f='llvm/clang/lib/Lex/ModuleMap.cpp' l='1260' c='_ZN5clang9ModuleMap26setInferredModuleAllowedByEPNS_6ModuleEPKNS_9FileEntryE'/>
<use f='llvm/clang/lib/Lex/ModuleMap.cpp' l='1265' c='_ZN5clang9ModuleMap26addAdditionalModuleMapFileEPKNS_6ModuleEPKNS_9FileEntryE'/>
<use f='llvm/clang/lib/Lex/ModuleMap.cpp' l='1292' c='_ZN5clang9ModuleMap14resolveExportsEPNS_6ModuleEb'/>
<use f='llvm/clang/lib/Lex/ModuleMap.cpp' l='1305' c='_ZN5clang9ModuleMap11resolveUsesEPNS_6ModuleEb'/>
<use f='llvm/clang/lib/Lex/ModuleMap.cpp' l='1309' c='_ZN5clang9ModuleMap11resolveUsesEPNS_6ModuleEb'/>
<use f='llvm/clang/lib/Lex/ModuleMap.cpp' l='1318' c='_ZN5clang9ModuleMap16resolveConflictsEPNS_6ModuleEb'/>
<use f='llvm/clang/lib/Lex/ModuleMap.cpp' l='1322' c='_ZN5clang9ModuleMap16resolveConflictsEPNS_6ModuleEb'/>
<use f='llvm/clang/lib/Lex/ModuleMap.cpp' l='1440'/>
<use f='llvm/clang/lib/Lex/ModuleMap.cpp' l='1450'/>
<use f='llvm/clang/lib/Lex/ModuleMap.cpp' l='1755' c='_ZN5clang15ModuleMapParser22diagnosePrivateModulesENS_14SourceLocationES1_'/>
<use f='llvm/clang/lib/Lex/ModuleMap.cpp' l='1890' c='_ZN5clang15ModuleMapParser15parseModuleDeclEv'/>
<use f='llvm/clang/lib/Lex/ModuleMap.cpp' l='1895' c='_ZN5clang15ModuleMapParser15parseModuleDeclEv'/>
<use f='llvm/clang/lib/Lex/ModuleMap.cpp' l='1897' c='_ZN5clang15ModuleMapParser15parseModuleDeclEv'/>
<use f='llvm/clang/lib/Lex/ModuleMap.cpp' l='1939' c='_ZN5clang15ModuleMapParser15parseModuleDeclEv'/>
<use f='llvm/clang/lib/Lex/ModuleMap.cpp' l='1940' c='_ZN5clang15ModuleMapParser15parseModuleDeclEv'/>
<use f='llvm/clang/lib/Lex/ModuleMap.cpp' l='2190' c='_ZL20shouldAddRequirementPN5clang6ModuleEN4llvm9StringRefERb'/>
<use f='llvm/clang/lib/Lex/ModuleMap.cpp' l='2462' c='_ZN5clang15ModuleMapParser20parseUmbrellaDirDeclENS_14SourceLocationE'/>
<size>1896</size>
<use f='llvm/clang/lib/Lex/PPDirectives.cpp' l='129' c='_ZL19isForModuleBuildingPN5clang6ModuleEN4llvm9StringRefES3_'/>
<use f='llvm/clang/lib/Lex/PPDirectives.cpp' l='635' c='_ZN5clang12Preprocessor20getModuleForLocationENS_14SourceLocationE'/>
<use f='llvm/clang/lib/Lex/PPDirectives.cpp' l='658' c='_ZN5clang12Preprocessor32getHeaderToIncludeForDiagnosticsENS_14SourceLocationES1_'/>
<use f='llvm/clang/lib/Lex/PPDirectives.cpp' l='729' c='_ZN5clang12Preprocessor10LookupFileENS_14SourceLocationEN4llvm9StringRefEbPKNS_15DirectoryLookupEPKNS_9FileEntryERS6_PNS2_15SmallVectorImplIcEESD_PNS_3223316'/>
<use f='llvm/clang/lib/Lex/PPDirectives.cpp' l='1650' c='_ZN5clang12Preprocessor22checkModuleIsAvailableERKNS_11LangOptionsERKNS_10TargetInfoERNS_17DiagnosticsEngineEPNS_6ModuleE'/>
<use f='llvm/clang/lib/Lex/PPDirectives.cpp' l='1653' c='_ZN5clang12Preprocessor22checkModuleIsAvailableERKNS_11LangOptionsERKNS_10TargetInfoERNS_17DiagnosticsEngineEPNS_6ModuleE'/>
<use f='llvm/clang/lib/Lex/PPDirectives.cpp' l='1980' c='_ZN5clang12Preprocessor27HandleHeaderIncludeOrImportENS_14SourceLocationERNS_5TokenES3_S1_PKNS_15DirectoryLookupEPKNS_9FileEntryE'/>
<use f='llvm/clang/lib/Lex/PPDirectives.cpp' l='2192' c='_ZN5clang12Preprocessor27HandleHeaderIncludeOrImportENS_14SourceLocationERNS_5TokenES3_S1_PKNS_15DirectoryLookupEPKNS_9FileEntryE'/>
<use f='llvm/clang/lib/Lex/PPDirectives.cpp' l='2203' c='_ZN5clang12Preprocessor27HandleHeaderIncludeOrImportENS_14SourceLocationERNS_5TokenES3_S1_PKNS_15DirectoryLookupEPKNS_9FileEntryE'/>
<size>1896</size>
<use f='llvm/clang/lib/Lex/PPLexerChange.cpp' l='257' c='_ZL38collectAllSubModulesWithUmbrellaHeaderRKN5clang6ModuleERN4llvm15SmallVectorImplIPS1_EE'/>
<use f='llvm/clang/lib/Lex/PPLexerChange.cpp' l='257' c='_ZL38collectAllSubModulesWithUmbrellaHeaderRKN5clang6ModuleERN4llvm15SmallVectorImplIPS1_EE'/>
<use f='llvm/clang/lib/Lex/PPLexerChange.cpp' l='264' c='_ZN5clang12Preprocessor34diagnoseMissingHeaderInUmbrellaDirERKNS_6ModuleE'/>
<use f='llvm/clang/lib/Lex/PPLexerChange.cpp' l='317' c='_ZN5clang12Preprocessor15HandleEndOfFileERNS_5TokenEb'/>
<use f='llvm/clang/lib/Lex/PPLexerChange.cpp' l='443' c='_ZN5clang12Preprocessor15HandleEndOfFileERNS_5TokenEb'/>
<use f='llvm/clang/lib/Lex/PPLexerChange.cpp' l='536' c='_ZN5clang12Preprocessor15HandleEndOfFileERNS_5TokenEb'/>
<use f='llvm/clang/lib/Lex/PPLexerChange.cpp' l='537' c='_ZN5clang12Preprocessor15HandleEndOfFileERNS_5TokenEb'/>
<use f='llvm/clang/lib/Lex/PPLexerChange.cpp' l='646' c='_ZN5clang12Preprocessor14EnterSubmoduleEPNS_6ModuleENS_14SourceLocationEb'/>
<use f='llvm/clang/lib/Lex/PPLexerChange.cpp' l='723' c='_ZN5clang12Preprocessor14LeaveSubmoduleEb'/>
<use f='llvm/clang/lib/Lex/PPLexerChange.cpp' l='732' c='_ZN5clang12Preprocessor14LeaveSubmoduleEb'/>
<size>1896</size>
<use f='llvm/clang/lib/Lex/PPMacroExpansion.cpp' l='131' c='_ZN5clang12Preprocessor14addModuleMacroEPNS_6ModuleEPNS_14IdentifierInfoEPNS_9MacroInfoEN4llvm8ArrayRefIPNS_11ModuleMacroEEERb'/>
<use f='llvm/clang/lib/Lex/PPMacroExpansion.cpp' l='173' c='_ZN5clang12Preprocessor14getModuleMacroEPNS_6ModuleEPNS_14IdentifierInfoE'/>
<size>1896</size>
<use f='llvm/clang/lib/Lex/Pragma.cpp' l='1110' c='_ZN12_GLOBAL__N_118PragmaDebugHandler12HandlePragmaERN5clang12PreprocessorENS1_16PragmaIntroducerERNS1_5TokenE'/>
<use f='llvm/clang/lib/Lex/Pragma.cpp' l='1567' c='_ZN12_GLOBAL__N_125PragmaModuleImportHandler12HandlePragmaERN5clang12PreprocessorENS1_16PragmaIntroducerERNS1_5TokenE'/>
<use f='llvm/clang/lib/Lex/Pragma.cpp' l='1615' c='_ZN12_GLOBAL__N_124PragmaModuleBeginHandler12HandlePragmaERN5clang12PreprocessorENS1_16PragmaIntroducerERNS1_5TokenE'/>
<use f='llvm/clang/lib/Lex/Pragma.cpp' l='1658' c='_ZN12_GLOBAL__N_122PragmaModuleEndHandler12HandlePragmaERN5clang12PreprocessorENS1_16PragmaIntroducerERNS1_5TokenE'/>
<size>1896</size>
<use f='llvm/clang/lib/Lex/PreprocessingRecord.cpp' l='469' c='_ZN5clang19PreprocessingRecord18InclusionDirectiveENS_14SourceLocationERKNS_5TokenEN4llvm9StringRefEbNS_15CharSourceRangeEPKNS_9FileEntryES6_S6_PKNS_610901186'/>
<size>1896</size>
<use f='llvm/clang/lib/Lex/Preprocessor.cpp' l='517' c='_ZN5clang12Preprocessor16getCurrentModuleEv'/>
<use f='llvm/clang/lib/Lex/Preprocessor.cpp' l='1285' c='_ZN5clang12Preprocessor20LexAfterModuleImportERNS_5TokenE'/>
<use f='llvm/clang/lib/Lex/Preprocessor.cpp' l='1304' c='_ZN5clang12Preprocessor17makeModuleVisibleEPNS_6ModuleENS_14SourceLocationE'/>
<use f='llvm/clang/lib/Lex/Preprocessor.cpp' l='1306' c='_ZN5clang12Preprocessor17makeModuleVisibleEPNS_6ModuleENS_14SourceLocationE'/>
<use f='llvm/clang/lib/Lex/Preprocessor.cpp' l='1307' c='_ZN5clang12Preprocessor17makeModuleVisibleEPNS_6ModuleENS_14SourceLocationE'/>
<use f='llvm/clang/lib/Lex/Preprocessor.cpp' l='1307' c='_ZN5clang12Preprocessor17makeModuleVisibleEPNS_6ModuleENS_14SourceLocationE'/>
<size>1896</size>
<use f='llvm/clang/lib/Parse/Parser.cpp' l='659' c='_ZN5clang6Parser17ParseTopLevelDeclERNS_9OpaquePtrINS_12DeclGroupRefEEEb'/>
<use f='llvm/clang/lib/Parse/Parser.cpp' l='665' c='_ZN5clang6Parser17ParseTopLevelDeclERNS_9OpaquePtrINS_12DeclGroupRefEEEb'/>
<use f='llvm/clang/lib/Parse/Parser.cpp' l='671' c='_ZN5clang6Parser17ParseTopLevelDeclERNS_9OpaquePtrINS_12DeclGroupRefEEEb'/>
<use f='llvm/clang/lib/Parse/Parser.cpp' l='2381' c='_ZN5clang6Parser17ParseModuleImportENS_14SourceLocationE'/>
<use f='llvm/clang/lib/Parse/Parser.cpp' l='2390' c='_ZN5clang6Parser17ParseModuleImportENS_14SourceLocationE'/>
<use f='llvm/clang/lib/Parse/Parser.cpp' l='2490' c='_ZN5clang6Parser26parseMisplacedModuleImportEv'/>
<use f='llvm/clang/lib/Parse/Parser.cpp' l='2502' c='_ZN5clang6Parser26parseMisplacedModuleImportEv'/>
<use f='llvm/clang/lib/Parse/Parser.cpp' l='2511' c='_ZN5clang6Parser26parseMisplacedModuleImportEv'/>
<size>1896</size>
<use f='llvm/clang/lib/Sema/MultiplexExternalSemaSource.cpp' l='168' c='_ZN5clang27MultiplexExternalSemaSource9getModuleEj'/>
<size>1896</size>
<use f='llvm/clang/lib/Sema/Sema.cpp' l='1132' c='_ZN5clang4Sema25ActOnEndOfTranslationUnitEv'/>
<use f='llvm/clang/lib/Sema/Sema.cpp' l='1135' c='_ZN5clang4Sema25ActOnEndOfTranslationUnitEv'/>
<use f='llvm/clang/lib/Sema/Sema.cpp' l='1138' c='_ZN5clang4Sema25ActOnEndOfTranslationUnitEv'/>
<size>1896</size>
<use f='llvm/clang/lib/Sema/SemaCodeComplete.cpp' l='4109' c='_ZN5clang4Sema24CodeCompleteModuleImportENS_14SourceLocationEN4llvm8ArrayRefISt4pairIPNS_14IdentifierInfoES1_EEE'/>
<use f='llvm/clang/lib/Sema/SemaCodeComplete.cpp' l='4121' c='_ZN5clang4Sema24CodeCompleteModuleImportENS_14SourceLocationEN4llvm8ArrayRefISt4pairIPNS_14IdentifierInfoES1_EEE'/>
<size>1896</size>
<use f='llvm/clang/lib/Sema/SemaDecl.cpp' l='1576' c='_ZN5clang4Sema33CheckRedeclarationModuleOwnershipEPNS_9NamedDeclES2_'/>
<use f='llvm/clang/lib/Sema/SemaDecl.cpp' l='1577' c='_ZN5clang4Sema33CheckRedeclarationModuleOwnershipEPNS_9NamedDeclES2_'/>
<use f='llvm/clang/lib/Sema/SemaDecl.cpp' l='4267' c='_ZN5clang4Sema22notePreviousDefinitionEPKNS_9NamedDeclENS_14SourceLocationE'/>
<size>1896</size>
<use f='llvm/clang/lib/Sema/SemaLookup.cpp' l='1478' c='_ZL17getDefiningModuleRN5clang4SemaEPNS_4DeclE'/>
<use f='llvm/clang/lib/Sema/SemaLookup.cpp' l='1503' c='_ZN5clang4Sema16getLookupModulesEv'/>
<use f='llvm/clang/lib/Sema/SemaLookup.cpp' l='1507' c='_ZN5clang4Sema16getLookupModulesEv'/>
<use f='llvm/clang/lib/Sema/SemaLookup.cpp' l='1519' c='_ZL17isInCurrentModulePKN5clang6ModuleERKNS_11LangOptionsE'/>
<use f='llvm/clang/lib/Sema/SemaLookup.cpp' l='1527' c='_ZN5clang4Sema26hasVisibleMergedDefinitionEPNS_9NamedDeclE'/>
<use f='llvm/clang/lib/Sema/SemaLookup.cpp' l='1534' c='_ZN5clang4Sema34hasMergedDefinitionInCurrentModuleEPNS_9NamedDeclE'/>
<use f='llvm/clang/lib/Sema/SemaLookup.cpp' l='1543' c='_ZL25hasVisibleDefaultArgumentRN5clang4SemaEPKT_PN4llvm15SmallVectorImplIPNS_6ModuleEEE'/>
<use f='llvm/clang/lib/Sema/SemaLookup.cpp' l='1564' c='_ZN5clang4Sema25hasVisibleDefaultArgumentEPKNS_9NamedDeclEPN4llvm15SmallVectorImplIPNS_6ModuleEEE'/>
<use f='llvm/clang/lib/Sema/SemaLookup.cpp' l='1575' c='_ZL25hasVisibleDeclarationImplRN5clang4SemaEPKNS_9NamedDeclEPN4llvm15SmallVectorImplIPNS_6ModuleEEET_'/>
<use f='llvm/clang/lib/Sema/SemaLookup.cpp' l='1601' c='_ZN5clang4Sema32hasVisibleExplicitSpecializationEPKNS_9NamedDeclEPN4llvm15SmallVectorImplIPNS_6ModuleEEE'/>
<use f='llvm/clang/lib/Sema/SemaLookup.cpp' l='1614' c='_ZN5clang4Sema30hasVisibleMemberSpecializationEPKNS_9NamedDeclEPN4llvm15SmallVectorImplIPNS_6ModuleEEE'/>
<use f='llvm/clang/lib/Sema/SemaLookup.cpp' l='1641' c='_ZN5clang12LookupResult13isVisibleSlowERNS_4SemaEPNS_9NamedDeclE'/>
<use f='llvm/clang/lib/Sema/SemaLookup.cpp' l='1712' c='_ZN5clang4Sema15isModuleVisibleEPKNS_6ModuleEb'/>
<use f='llvm/clang/lib/Sema/SemaLookup.cpp' l='1741' c='_ZN5clang4Sema15isModuleVisibleEPKNS_6ModuleEb'/>
<use f='llvm/clang/lib/Sema/SemaLookup.cpp' l='1816' c='_ZN5clang4Sema25hasVisibleDeclarationSlowEPKNS_9NamedDeclEPN4llvm15SmallVectorImplIPNS_6ModuleEEE'/>
<use f='llvm/clang/lib/Sema/SemaLookup.cpp' l='5297' c='_ZN5clang4Sema21diagnoseMissingImportENS_14SourceLocationEPNS_9NamedDeclENS0_17MissingImportKindEb'/>
<use f='llvm/clang/lib/Sema/SemaLookup.cpp' l='5300' c='_ZN5clang4Sema21diagnoseMissingImportENS_14SourceLocationEPNS_9NamedDeclENS0_17MissingImportKindEb'/>
<use f='llvm/clang/lib/Sema/SemaLookup.cpp' l='5321' c='_ZN5clang4Sema21diagnoseMissingImportENS_14SourceLocationEPNS_9NamedDeclES1_N4llvm8ArrayRefIPNS_6ModuleEEENS0_17MissingImportKindEb'/>
<use f='llvm/clang/lib/Sema/SemaLookup.cpp' l='5333' c='_ZN5clang4Sema21diagnoseMissingImportENS_14SourceLocationEPNS_9NamedDeclES1_N4llvm8ArrayRefIPNS_6ModuleEEENS0_17MissingImportKindEb'/>
<use f='llvm/clang/lib/Sema/SemaLookup.cpp' l='5334' c='_ZN5clang4Sema21diagnoseMissingImportENS_14SourceLocationEPNS_9NamedDeclES1_N4llvm8ArrayRefIPNS_6ModuleEEENS0_17MissingImportKindEb'/>
<use f='llvm/clang/lib/Sema/SemaLookup.cpp' l='5370' c='_ZN5clang4Sema21diagnoseMissingImportENS_14SourceLocationEPNS_9NamedDeclES1_N4llvm8ArrayRefIPNS_6ModuleEEENS0_17MissingImportKindEb'/>
<size>1896</size>
<use f='llvm/clang/lib/Sema/SemaModule.cpp' l='22' c='_ZL24checkModuleImportContextRN5clang4SemaEPNS_6ModuleENS_14SourceLocationEPNS_11DeclContextEb'/>
<use f='llvm/clang/lib/Sema/SemaModule.cpp' l='139' c='_ZN5clang4Sema15ActOnModuleDeclENS_14SourceLocationES1_NS0_14ModuleDeclKindEN4llvm8ArrayRefISt4pairIPNS_14IdentifierInfoES1_EEEb'/>
<use f='llvm/clang/lib/Sema/SemaModule.cpp' l='180' c='_ZN5clang4Sema15ActOnModuleDeclENS_14SourceLocationES1_NS0_14ModuleDeclKindEN4llvm8ArrayRefISt4pairIPNS_14IdentifierInfoES1_EEEb'/>
<use f='llvm/clang/lib/Sema/SemaModule.cpp' l='284' c='_ZN5clang4Sema30ActOnPrivateModuleFragmentDeclENS_14SourceLocationES1_'/>
<use f='llvm/clang/lib/Sema/SemaModule.cpp' l='324' c='_ZN5clang4Sema17ActOnModuleImportENS_14SourceLocationES1_S1_N4llvm8ArrayRefISt4pairIPNS_14IdentifierInfoES1_EEE'/>
<use f='llvm/clang/lib/Sema/SemaModule.cpp' l='344' c='_ZN5clang4Sema17ActOnModuleImportENS_14SourceLocationES1_S1_PNS_6ModuleEN4llvm8ArrayRefISt4pairIPNS_14IdentifierInfoES1_EEE'/>
<use f='llvm/clang/lib/Sema/SemaModule.cpp' l='365' c='_ZN5clang4Sema17ActOnModuleImportENS_14SourceLocationES1_S1_PNS_6ModuleEN4llvm8ArrayRefISt4pairIPNS_14IdentifierInfoES1_EEE'/>
<use f='llvm/clang/lib/Sema/SemaModule.cpp' l='404' c='_ZN5clang4Sema18ActOnModuleIncludeENS_14SourceLocationEPNS_6ModuleE'/>
<use f='llvm/clang/lib/Sema/SemaModule.cpp' l='409' c='_ZN5clang4Sema18BuildModuleIncludeENS_14SourceLocationEPNS_6ModuleE'/>
<use f='llvm/clang/lib/Sema/SemaModule.cpp' l='438' c='_ZN5clang4Sema16ActOnModuleBeginENS_14SourceLocationEPNS_6ModuleE'/>
<use f='llvm/clang/lib/Sema/SemaModule.cpp' l='462' c='_ZN5clang4Sema14ActOnModuleEndENS_14SourceLocationEPNS_6ModuleE'/>
<use f='llvm/clang/lib/Sema/SemaModule.cpp' l='503' c='_ZN5clang4Sema42createImplicitModuleImportForErrorRecoveryENS_14SourceLocationEPNS_6ModuleE'/>
<size>1896</size>
<use f='llvm/clang/lib/Sema/SemaOverload.cpp' l='9932' c='_ZN5clang4Sema45diagnoseEquivalentInternalLinkageDeclarationsENS_14SourceLocationEPKNS_9NamedDeclEN4llvm8ArrayRefIS4_EE'/>
<use f='llvm/clang/lib/Sema/SemaOverload.cpp' l='9937' c='_ZN5clang4Sema45diagnoseEquivalentInternalLinkageDeclarationsENS_14SourceLocationEPKNS_9NamedDeclEN4llvm8ArrayRefIS4_EE'/>
<size>1896</size>
<use f='llvm/clang/lib/Sema/SemaTemplate.cpp' l='5595' c='_ZL23diagnoseMissingArgumentRN5clang4SemaENS_14SourceLocationEPNS_12TemplateDeclEPKT_RNS_24TemplateArgumentListInfoE'/>
<use f='llvm/clang/lib/Sema/SemaTemplate.cpp' l='10966'/>
<size>1896</size>
<use f='llvm/clang/lib/Sema/SemaTemplateInstantiate.cpp' l='463' c='_ZN5clang4Sema23popCodeSynthesisContextEv'/>
<size>1896</size>
<use f='llvm/clang/include/clang/Serialization/ASTRecordReader.h' l='93' c='_ZN5clang15ASTRecordReader12getSubmoduleEj'/>
<use f='llvm/clang/lib/Serialization/ASTReader.cpp' l='539' c='_ZL26getTopImportImplicitModuleRN5clang13serialization13ModuleManagerERNS_12PreprocessorE'/>
<use f='llvm/clang/lib/Serialization/ASTReader.cpp' l='557' c='_ZL26getTopImportImplicitModuleRN5clang13serialization13ModuleManagerERNS_12PreprocessorE'/>
<use f='llvm/clang/lib/Serialization/ASTReader.cpp' l='575' c='_ZN5clang12PCHValidator21ReadDiagnosticOptionsEN4llvm18IntrusiveRefCntPtrINS_17DiagnosticOptionsEEEb'/>
<use f='llvm/clang/lib/Serialization/ASTReader.cpp' l='1906' c='_ZN5clang13serialization6reader19HeaderFileInfoTrait8ReadDataERKNS2_17internal_key_typeEPKhj'/>
<use f='llvm/clang/lib/Serialization/ASTReader.cpp' l='2163' c='_ZN5clang9ASTReader19resolvePendingMacroEPNS_14IdentifierInfoERKNS0_16PendingMacroInfoE'/>
<use f='llvm/clang/lib/Serialization/ASTReader.cpp' l='2170' c='_ZN5clang9ASTReader19resolvePendingMacroEPNS_14IdentifierInfoERKNS0_16PendingMacroInfoE'/>
<use f='llvm/clang/lib/Serialization/ASTReader.cpp' l='2891' c='_ZN5clang9ASTReader16ReadControlBlockERNS_13serialization10ModuleFileERN4llvm15SmallVectorImplINS0_14ImportedModuleEEEPKS2_j'/>
<use f='llvm/clang/lib/Serialization/ASTReader.cpp' l='3928' c='_ZN5clang9ASTReader22ReadModuleMapFileBlockERN4llvm11SmallVectorImLj64EEERNS_13serialization10ModuleFileEPKS6_j'/>
<use f='llvm/clang/lib/Serialization/ASTReader.cpp' l='4045' c='_ZN5clang9ASTReader16makeNamesVisibleERKN4llvm11SmallVectorIPNS_4DeclELj2EEEPNS_6ModuleE'/>
<use f='llvm/clang/lib/Serialization/ASTReader.cpp' l='4059' c='_ZN5clang9ASTReader17makeModuleVisibleEPNS_6ModuleENS1_18NameVisibilityKindENS_14SourceLocationE'/>
<use f='llvm/clang/lib/Serialization/ASTReader.cpp' l='4062' c='_ZN5clang9ASTReader17makeModuleVisibleEPNS_6ModuleENS1_18NameVisibilityKindENS_14SourceLocationE'/>
<use f='llvm/clang/lib/Serialization/ASTReader.cpp' l='4063' c='_ZN5clang9ASTReader17makeModuleVisibleEPNS_6ModuleENS1_18NameVisibilityKindENS_14SourceLocationE'/>
<use f='llvm/clang/lib/Serialization/ASTReader.cpp' l='4094' c='_ZN5clang9ASTReader17makeModuleVisibleEPNS_6ModuleENS1_18NameVisibilityKindENS_14SourceLocationE'/>
<use f='llvm/clang/lib/Serialization/ASTReader.cpp' l='4098' c='_ZN5clang9ASTReader17makeModuleVisibleEPNS_6ModuleENS1_18NameVisibilityKindENS_14SourceLocationE'/>
<use f='llvm/clang/lib/Serialization/ASTReader.cpp' l='4375' c='_ZN5clang9ASTReader7ReadASTEN4llvm9StringRefENS_13serialization10ModuleKindENS_14SourceLocationEjPNS1_15SmallVectorImplINS0_17ImportedSubmoduleEEE'/>
<use f='llvm/clang/lib/Serialization/ASTReader.cpp' l='4996' c='_ZN5clang9ASTReader17InitializeContextEv'/>
<use f='llvm/clang/lib/Serialization/ASTReader.cpp' l='5455' c='_ZN5clang9ASTReader18ReadSubmoduleBlockERNS_13serialization10ModuleFileEj'/>
<use f='llvm/clang/lib/Serialization/ASTReader.cpp' l='5525' c='_ZN5clang9ASTReader18ReadSubmoduleBlockERNS_13serialization10ModuleFileEj'/>
<use f='llvm/clang/lib/Serialization/ASTReader.cpp' l='7976' c='_ZN5clang9ASTReader10UpdateSemaEv'/>
<use f='llvm/clang/lib/Serialization/ASTReader.cpp' l='8611' c='_ZN5clang9ASTReader12getSubmoduleEj'/>
<use f='llvm/clang/lib/Serialization/ASTReader.cpp' l='8625' c='_ZN5clang9ASTReader9getModuleEj'/>
<use f='llvm/clang/lib/Serialization/ASTReader.cpp' l='8661' c='_ZN5clang9ASTReader19getSourceDescriptorEj'/>
<use f='llvm/clang/lib/Serialization/ASTReader.cpp' l='9162' c='_ZN5clang9ASTReader32getOwningModuleNameForDiagnosticB5cxx11EPKNS_4DeclE'/>
<size>1896</size>
<use f='llvm/clang/lib/Serialization/ASTReaderDecl.cpp' l='155' c='_ZN5clang13ASTDeclReader10readModuleEv'/>
<use f='llvm/clang/lib/Serialization/ASTReaderDecl.cpp' l='621' c='_ZN5clang13ASTDeclReader9VisitDeclEPNS_4DeclE'/>
<use f='llvm/clang/lib/Serialization/ASTReaderDecl.cpp' l='4685' c='_ZN5clang13ASTDeclReader10UpdateDeclEPNS_4DeclERN4llvm15SmallVectorImplIjEE'/>
<size>1896</size>
<use f='llvm/clang/lib/Serialization/ASTWriter.cpp' l='1639'/>
<use f='llvm/clang/lib/Serialization/ASTWriter.cpp' l='1721' c='_ZN12_GLOBAL__N_119HeaderFileInfoTrait8EmitDataERN4llvm11raw_ostreamERKNS0_8key_typeERKNS0_9data_typeEj'/>
<use f='llvm/clang/lib/Serialization/ASTWriter.cpp' l='1760' c='_ZN5clang9ASTWriter17WriteHeaderSearchERKNS_12HeaderSearchE'/>
<use f='llvm/clang/lib/Serialization/ASTWriter.cpp' l='1762' c='_ZN5clang9ASTWriter17WriteHeaderSearchERKNS_12HeaderSearchE'/>
<use f='llvm/clang/lib/Serialization/ASTWriter.cpp' l='2474' c='_ZN5clang9ASTWriter29getLocalOrImportedSubmoduleIDEPNS_6ModuleE'/>
<use f='llvm/clang/lib/Serialization/ASTWriter.cpp' l='2491' c='_ZN5clang9ASTWriter14getSubmoduleIDEPNS_6ModuleE'/>
<use f='llvm/clang/lib/Serialization/ASTWriter.cpp' l='2503' c='_ZL18getNumberOfModulesPN5clang6ModuleE'/>
<use f='llvm/clang/lib/Serialization/ASTWriter.cpp' l='2512' c='_ZN5clang9ASTWriter15WriteSubmodulesEPNS_6ModuleE'/>
<use f='llvm/clang/lib/Serialization/ASTWriter.cpp' l='2611' c='_ZN5clang9ASTWriter15WriteSubmodulesEPNS_6ModuleE'/>
<use f='llvm/clang/lib/Serialization/ASTWriter.cpp' l='2614' c='_ZN5clang9ASTWriter15WriteSubmodulesEPNS_6ModuleE'/>
<use f='llvm/clang/lib/Serialization/ASTWriter.cpp' l='4368' c='_ZN5clang9ASTWriter8WriteASTERNS_4SemaERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEPNS_6ModuleEN4llvm9StringRefEbb'/>
<use f='llvm/clang/lib/Serialization/ASTWriter.cpp' l='4414' c='_ZN5clang9ASTWriter12WriteASTCoreERNS_4SemaEN4llvm9StringRefERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEPNS_6ModuleE'/>
<use f='llvm/clang/lib/Serialization/ASTWriter.cpp' l='4881' c='_ZN5clang9ASTWriter12WriteASTCoreERNS_4SemaEN4llvm9StringRefERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEPNS_6ModuleE'/>
<use f='llvm/clang/lib/Serialization/ASTWriter.cpp' l='4882' c='_ZZN5clang9ASTWriter12WriteASTCoreERNS_4SemaEN4llvm9StringRefERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEPNS_6ModuleEEN10ModuleInfoC1EmSE_'/>
<use f='llvm/clang/lib/Serialization/ASTWriter.cpp' l='5780' c='_ZN5clang9ASTWriter10ModuleReadEjPNS_6ModuleE'/>
<use f='llvm/clang/lib/Serialization/ASTWriter.cpp' l='6020' c='_ZN5clang9ASTWriter25RedefinedHiddenDefinitionEPKNS_9NamedDeclEPNS_6ModuleE'/>
<size>1896</size>
<use f='llvm/clang/lib/Serialization/GeneratePCH.cpp' l='50' c='_ZN5clang12PCHGenerator21HandleTranslationUnitERNS_10ASTContextE'/>
<size>1896</size>
<use f='llvm/clang/lib/Serialization/ModuleManager.cpp' l='54' c='_ZNK5clang13serialization13ModuleManager18lookupByModuleNameEN4llvm9StringRefE'/>
<use f='llvm/clang/lib/Serialization/ModuleManager.cpp' l='290' c='_ZN5clang13serialization13ModuleManager13removeModulesEN4llvm16pointee_iteratorIPSt10unique_ptrINS0_10ModuleFileESt14default_deleteIS5_EES5_EEPNS_9ModuleMapE'/>
<size>1896</size>
<use f='llvm/clang/include/clang/Tooling/DependencyScanning/ModuleDepCollector.h' l='121' c='_ZN5clang7tooling12dependencies20ModuleDepCollectorPP18InclusionDirectiveENS_14SourceLocationERKNS_5TokenEN4llvm9StringRefEbNS_15CharSourceRangeEPKNS_928640'/>
<use f='llvm/clang/include/clang/Tooling/DependencyScanning/ModuleDepCollector.h' l='124' c='_ZN5clang7tooling12dependencies20ModuleDepCollectorPP12moduleImportENS_14SourceLocationEN4llvm8ArrayRefISt4pairIPNS_14IdentifierInfoES3_EEEPKNS_6ModuleE'/>
<use f='llvm/clang/include/clang/Tooling/DependencyScanning/ModuleDepCollector.h' l='131'/>
<use f='llvm/clang/include/clang/Tooling/DependencyScanning/ModuleDepCollector.h' l='133' c='_ZN5clang7tooling12dependencies20ModuleDepCollectorPP12handleImportEPKNS_6ModuleE'/>
<use f='llvm/clang/include/clang/Tooling/DependencyScanning/ModuleDepCollector.h' l='134' c='_ZN5clang7tooling12dependencies20ModuleDepCollectorPP20handleTopLevelModuleEPKNS_6ModuleE'/>
<use f='llvm/clang/include/clang/Tooling/DependencyScanning/ModuleDepCollector.h' l='135' c='_ZN5clang7tooling12dependencies20ModuleDepCollectorPP19addAllSubmoduleDepsEPKNS_6ModuleERNS1_10ModuleDepsERN4llvm8DenseSetIS5_NS8_12DenseMapInfoIS5_EEEE'/>
<use f='llvm/clang/include/clang/Tooling/DependencyScanning/ModuleDepCollector.h' l='136' c='_ZN5clang7tooling12dependencies20ModuleDepCollectorPP19addAllSubmoduleDepsEPKNS_6ModuleERNS1_10ModuleDepsERN4llvm8DenseSetIS5_NS8_12DenseMapInfoIS5_EEEE'/>
<use f='llvm/clang/include/clang/Tooling/DependencyScanning/ModuleDepCollector.h' l='137' c='_ZN5clang7tooling12dependencies20ModuleDepCollectorPP12addModuleDepEPKNS_6ModuleERNS1_10ModuleDepsERN4llvm8DenseSetIS5_NS8_12DenseMapInfoIS5_EEEE'/>
<use f='llvm/clang/include/clang/Tooling/DependencyScanning/ModuleDepCollector.h' l='138' c='_ZN5clang7tooling12dependencies20ModuleDepCollectorPP12addModuleDepEPKNS_6ModuleERNS1_10ModuleDepsERN4llvm8DenseSetIS5_NS8_12DenseMapInfoIS5_EEEE'/>
<size>1896</size>
<use f='llvm/clang/lib/Tooling/DependencyScanning/ModuleDepCollector.cpp' l='89' c='_ZN5clang7tooling12dependencies20ModuleDepCollectorPP18InclusionDirectiveENS_14SourceLocationERKNS_5TokenEN4llvm9StringRefEbNS_15CharSourceRangeEPKNS_928640'/>
<use f='llvm/clang/lib/Tooling/DependencyScanning/ModuleDepCollector.cpp' l='101' c='_ZN5clang7tooling12dependencies20ModuleDepCollectorPP12moduleImportENS_14SourceLocationEN4llvm8ArrayRefISt4pairIPNS_14IdentifierInfoES3_EEEPKNS_6ModuleE'/>
<use f='llvm/clang/lib/Tooling/DependencyScanning/ModuleDepCollector.cpp' l='105' c='_ZN5clang7tooling12dependencies20ModuleDepCollectorPP12handleImportEPKNS_6ModuleE'/>
<use f='llvm/clang/lib/Tooling/DependencyScanning/ModuleDepCollector.cpp' l='119' c='_ZN5clang7tooling12dependencies20ModuleDepCollectorPP13EndOfMainFileEv'/>
<use f='llvm/clang/lib/Tooling/DependencyScanning/ModuleDepCollector.cpp' l='130' c='_ZN5clang7tooling12dependencies20ModuleDepCollectorPP20handleTopLevelModuleEPKNS_6ModuleE'/>
<use f='llvm/clang/lib/Tooling/DependencyScanning/ModuleDepCollector.cpp' l='157' c='_ZN5clang7tooling12dependencies20ModuleDepCollectorPP20handleTopLevelModuleEPKNS_6ModuleE'/>
<use f='llvm/clang/lib/Tooling/DependencyScanning/ModuleDepCollector.cpp' l='162' c='_ZN5clang7tooling12dependencies20ModuleDepCollectorPP19addAllSubmoduleDepsEPKNS_6ModuleERNS1_10ModuleDepsERN4llvm8DenseSetIS5_NS8_12DenseMapInfoIS5_EEEE'/>
<use f='llvm/clang/lib/Tooling/DependencyScanning/ModuleDepCollector.cpp' l='163' c='_ZN5clang7tooling12dependencies20ModuleDepCollectorPP19addAllSubmoduleDepsEPKNS_6ModuleERNS1_10ModuleDepsERN4llvm8DenseSetIS5_NS8_12DenseMapInfoIS5_EEEE'/>
<use f='llvm/clang/lib/Tooling/DependencyScanning/ModuleDepCollector.cpp' l='166' c='_ZN5clang7tooling12dependencies20ModuleDepCollectorPP19addAllSubmoduleDepsEPKNS_6ModuleERNS1_10ModuleDepsERN4llvm8DenseSetIS5_NS8_12DenseMapInfoIS5_EEEE'/>
<use f='llvm/clang/lib/Tooling/DependencyScanning/ModuleDepCollector.cpp' l='171' c='_ZN5clang7tooling12dependencies20ModuleDepCollectorPP12addModuleDepEPKNS_6ModuleERNS1_10ModuleDepsERN4llvm8DenseSetIS5_NS8_12DenseMapInfoIS5_EEEE'/>
<use f='llvm/clang/lib/Tooling/DependencyScanning/ModuleDepCollector.cpp' l='172' c='_ZN5clang7tooling12dependencies20ModuleDepCollectorPP12addModuleDepEPKNS_6ModuleERNS1_10ModuleDepsERN4llvm8DenseSetIS5_NS8_12DenseMapInfoIS5_EEEE'/>
<use f='llvm/clang/lib/Tooling/DependencyScanning/ModuleDepCollector.cpp' l='173' c='_ZN5clang7tooling12dependencies20ModuleDepCollectorPP12addModuleDepEPKNS_6ModuleERNS1_10ModuleDepsERN4llvm8DenseSetIS5_NS8_12DenseMapInfoIS5_EEEE'/>
<size>1896</size>
<use f='llvm/clang/tools/c-index-test/core_main.cpp' l='79' c='_ZL21printSymbolNameAndUSRPKN5clang6ModuleERN4llvm11raw_ostreamE'/>
<use f='llvm/clang/tools/c-index-test/core_main.cpp' l='139' c='_ZN12_GLOBAL__N_122PrintIndexDataConsumer22handleModuleOccurrenceEPKN5clang10ImportDeclEPKNS1_6ModuleEjNS1_14SourceLocationE'/>
<use f='llvm/clang/tools/c-index-test/core_main.cpp' l='314' c='_ZL21printSymbolNameAndUSRPKN5clang6ModuleERN4llvm11raw_ostreamE'/>
<size>1896</size>
<use f='llvm/clang/tools/libclang/CIndex.cpp' l='4558' c='_ZL15getDeclSpellingPKN5clang4DeclE'/>
<use f='llvm/clang/tools/libclang/CIndex.cpp' l='8403' c='clang_Module_getASTFile'/>
<use f='llvm/clang/tools/libclang/CIndex.cpp' l='8403' c='clang_Module_getASTFile'/>
<use f='llvm/clang/tools/libclang/CIndex.cpp' l='8412' c='clang_Module_getParent'/>
<use f='llvm/clang/tools/libclang/CIndex.cpp' l='8412' c='clang_Module_getParent'/>
<use f='llvm/clang/tools/libclang/CIndex.cpp' l='8419' c='clang_Module_getName'/>
<use f='llvm/clang/tools/libclang/CIndex.cpp' l='8419' c='clang_Module_getName'/>
<use f='llvm/clang/tools/libclang/CIndex.cpp' l='8426' c='clang_Module_getFullName'/>
<use f='llvm/clang/tools/libclang/CIndex.cpp' l='8426' c='clang_Module_getFullName'/>
<use f='llvm/clang/tools/libclang/CIndex.cpp' l='8433' c='clang_Module_isSystem'/>
<use f='llvm/clang/tools/libclang/CIndex.cpp' l='8433' c='clang_Module_isSystem'/>
<use f='llvm/clang/tools/libclang/CIndex.cpp' l='8445' c='clang_Module_getNumTopLevelHeaders'/>
<use f='llvm/clang/tools/libclang/CIndex.cpp' l='8445' c='clang_Module_getNumTopLevelHeaders'/>
<use f='llvm/clang/tools/libclang/CIndex.cpp' l='8459' c='clang_Module_getTopLevelHeader'/>
<use f='llvm/clang/tools/libclang/CIndex.cpp' l='8459' c='clang_Module_getTopLevelHeader'/>
<size>1896</size>
<use f='llvm/clang/tools/libclang/CXIndexDataConsumer.h' l='438' c='_ZN5clang7cxindex19CXIndexDataConsumer22handleModuleOccurrenceEPKNS_10ImportDeclEPKNS_6ModuleEjNS_14SourceLocationE'/>
<use f='llvm/clang/tools/libclang/CXIndexDataConsumer.cpp' l='224' c='_ZN5clang7cxindex19CXIndexDataConsumer22handleModuleOccurrenceEPKNS_10ImportDeclEPKNS_6ModuleEjNS_14SourceLocationE'/>
<use f='llvm/clang/tools/libclang/CXIndexDataConsumer.cpp' l='482' c='_ZN5clang7cxindex19CXIndexDataConsumer14importedModuleEPKNS_10ImportDeclE'/>
<use f='llvm/clang/tools/libclang/CXIndexDataConsumer.cpp' l='490' c='_ZN5clang7cxindex19CXIndexDataConsumer14importedModuleEPKNS_10ImportDeclE'/>
<size>1896</size>
<use f='llvm/clang/tools/libclang/Indexing.cpp' l='266' c='_ZN12_GLOBAL__N_116IndexPPCallbacks18InclusionDirectiveEN5clang14SourceLocationERKNS1_5TokenEN4llvm9StringRefEbNS1_15CharSourceRangeEPKNS1_9FileEntryE7674604'/>
<size>1896</size>
<use f='llvm/clang/unittests/Lex/PPCallbacksTest.cpp' l='40' c='_ZN12_GLOBAL__N_127InclusionDirectiveCallbacks18InclusionDirectiveEN5clang14SourceLocationERKNS1_5TokenEN4llvm9StringRefEbNS1_15CharSourceRangeEPKNS1_11755304'/>
<use f='llvm/clang/unittests/Lex/PPCallbacksTest.cpp' l='62'/>
<size>1896</size>
<use f='llvm/lldb/source/Plugins/ExpressionParser/Clang/ASTUtils.h' l='71' c='_ZN12lldb_private24ExternalASTSourceWrapper9getModuleEj'/>
<use f='llvm/lldb/source/Plugins/ExpressionParser/Clang/ASTUtils.h' l='397' c='_ZN12lldb_private24SemaSourceWithPriorities9getModuleEj'/>
<size>1896</size>
<use f='llvm/lldb/source/Plugins/ExpressionParser/Clang/ClangExternalASTSourceCallbacks.h' l='54' c='_ZN12lldb_private31ClangExternalASTSourceCallbacks9getModuleEj'/>
<use f='llvm/lldb/source/Plugins/ExpressionParser/Clang/ClangExternalASTSourceCallbacks.h' l='55' c='_ZN12lldb_private31ClangExternalASTSourceCallbacks14RegisterModuleEPN5clang6ModuleE'/>
<use f='llvm/lldb/source/Plugins/ExpressionParser/Clang/ClangExternalASTSourceCallbacks.h' l='56' c='_ZN12lldb_private31ClangExternalASTSourceCallbacks14GetIDForModuleEPN5clang6ModuleE'/>
<use f='llvm/lldb/source/Plugins/ExpressionParser/Clang/ClangExternalASTSourceCallbacks.h' l='60'/>
<use f='llvm/lldb/source/Plugins/ExpressionParser/Clang/ClangExternalASTSourceCallbacks.h' l='61'/>
<use f='llvm/lldb/source/Plugins/ExpressionParser/Clang/ClangASTImporter.cpp' l='1027' c='_ZL11RemapModuleN12lldb_private21OptionalClangModuleIDERNS_31ClangExternalASTSourceCallbacksES2_'/>
<size>1896</size>
<use f='llvm/lldb/source/Plugins/ExpressionParser/Clang/ClangExpressionParser.cpp' l='122' c='_ZN12lldb_private21ClangExpressionParser25LLDBPreprocessorCallbacks12moduleImportEN5clang14SourceLocationEN4llvm8ArrayRefISt4pairIPNS2_14IdentifierInf6716238'/>
<size>1896</size>
<use f='llvm/lldb/source/Plugins/ExpressionParser/Clang/ClangExternalASTSourceCallbacks.cpp' l='65' c='_ZN12lldb_private31ClangExternalASTSourceCallbacks14RegisterModuleEPN5clang6ModuleE'/>
<use f='llvm/lldb/source/Plugins/ExpressionParser/Clang/ClangExternalASTSourceCallbacks.cpp' l='74' c='_ZN12lldb_private31ClangExternalASTSourceCallbacks19getSourceDescriptorEj'/>
<use f='llvm/lldb/source/Plugins/ExpressionParser/Clang/ClangExternalASTSourceCallbacks.cpp' l='79' c='_ZN12lldb_private31ClangExternalASTSourceCallbacks9getModuleEj'/>
<use f='llvm/lldb/source/Plugins/ExpressionParser/Clang/ClangExternalASTSourceCallbacks.cpp' l='86' c='_ZN12lldb_private31ClangExternalASTSourceCallbacks14GetIDForModuleEPN5clang6ModuleE'/>
<size>1896</size>
<use f='llvm/lldb/source/Plugins/ExpressionParser/Clang/ClangModulesDeclVendor.cpp' l='105' c='_ZN12_GLOBAL__N_126ClangModulesDeclVendorImpl25ReportModuleExportsHelperERSt3setImSt4lessImESaImEEPN5clang6ModuleE'/>
<use f='llvm/lldb/source/Plugins/ExpressionParser/Clang/ClangModulesDeclVendor.cpp' l='107' c='_ZN12_GLOBAL__N_126ClangModulesDeclVendorImpl19ReportModuleExportsERSt6vectorImSaImEEPN5clang6ModuleE'/>
<use f='llvm/lldb/source/Plugins/ExpressionParser/Clang/ClangModulesDeclVendor.cpp' l='122'/>
<use f='llvm/lldb/source/Plugins/ExpressionParser/Clang/ClangModulesDeclVendor.cpp' l='199' c='_ZN12_GLOBAL__N_126ClangModulesDeclVendorImpl25ReportModuleExportsHelperERSt3setImSt4lessImESaImEEPN5clang6ModuleE'/>
<use f='llvm/lldb/source/Plugins/ExpressionParser/Clang/ClangModulesDeclVendor.cpp' l='205' c='_ZN12_GLOBAL__N_126ClangModulesDeclVendorImpl25ReportModuleExportsHelperERSt3setImSt4lessImESaImEEPN5clang6ModuleE'/>
<use f='llvm/lldb/source/Plugins/ExpressionParser/Clang/ClangModulesDeclVendor.cpp' l='209' c='_ZN12_GLOBAL__N_126ClangModulesDeclVendorImpl25ReportModuleExportsHelperERSt3setImSt4lessImESaImEEPN5clang6ModuleE'/>
<use f='llvm/lldb/source/Plugins/ExpressionParser/Clang/ClangModulesDeclVendor.cpp' l='215' c='_ZN12_GLOBAL__N_126ClangModulesDeclVendorImpl19ReportModuleExportsERSt6vectorImSaImEEPN5clang6ModuleE'/>
<use f='llvm/lldb/source/Plugins/ExpressionParser/Clang/ClangModulesDeclVendor.cpp' l='317' c='_ZN12_GLOBAL__N_126ClangModulesDeclVendorImpl9AddModuleERKN12lldb_private12SourceModuleEPSt6vectorImSaImEERNS1_6StreamE'/>
<use f='llvm/lldb/source/Plugins/ExpressionParser/Clang/ClangModulesDeclVendor.cpp' l='326' c='_ZN12_GLOBAL__N_126ClangModulesDeclVendorImpl9AddModuleERKN12lldb_private12SourceModuleEPSt6vectorImSaImEERNS1_6StreamE'/>
<use f='llvm/lldb/source/Plugins/ExpressionParser/Clang/ClangModulesDeclVendor.cpp' l='338' c='_ZN12_GLOBAL__N_126ClangModulesDeclVendorImpl9AddModuleERKN12lldb_private12SourceModuleEPSt6vectorImSaImEERNS1_6StreamE'/>
<use f='llvm/lldb/source/Plugins/ExpressionParser/Clang/ClangModulesDeclVendor.cpp' l='468' c='_ZN12_GLOBAL__N_126ClangModulesDeclVendorImpl12ForEachMacroERKSt6vectorImSaImEESt8functionIFbN4llvm9StringRefES8_EE'/>
<use f='llvm/lldb/source/Plugins/ExpressionParser/Clang/ClangModulesDeclVendor.cpp' l='480' c='_ZN12_GLOBAL__N_126ClangModulesDeclVendorImpl12ForEachMacroERKSt6vectorImSaImEESt8functionIFbN4llvm9StringRefES8_EE'/>
<size>1896</size>
<use f='llvm/lldb/source/Plugins/TypeSystem/Clang/TypeSystemClang.cpp' l='1272' c='_ZN12lldb_private15TypeSystemClang22GetOrCreateClangModuleEN4llvm9StringRefENS_21OptionalClangModuleIDEbb'/>
<size>1896</size>
