<dec f='llvm/clang/include/clang/Lex/PreprocessorOptions.h' l='54' type='2'/>
<use f='llvm/clang/include/clang/Lex/PreprocessorOptions.h' l='57' u='r'/>
<use f='llvm/clang/include/clang/Lex/PreprocessorOptions.h' l='59'/>
<doc f='llvm/clang/include/clang/Lex/PreprocessorOptions.h' l='53'>/// Disable validation for module files.</doc>
<use f='llvm/clang/lib/Serialization/ASTReader.cpp' l='2230' u='r' c='_ZNK5clang9ASTReader30shouldDisableValidationForFileERKNS_13serialization10ModuleFileE'/>
<use f='llvm/clang/lib/Serialization/ASTReader.cpp' l='2899' u='r' c='_ZN5clang9ASTReader16ReadControlBlockERNS_13serialization10ModuleFileERN4llvm15SmallVectorImplINS0_14ImportedModuleEEEPKS2_j'/>
<use f='llvm/clang/lib/Serialization/ASTReader.cpp' l='3933' u='r' c='_ZN5clang9ASTReader22ReadModuleMapFileBlockERN4llvm11SmallVectorImLj64EEERNS_13serialization10ModuleFileEPKS6_j'/>
<use f='llvm/clang/lib/Serialization/ASTReader.cpp' l='5549' u='r' c='_ZN5clang9ASTReader18ReadSubmoduleBlockERNS_13serialization10ModuleFileEj'/>
