<dec f='llvm/clang/include/clang/Sema/Sema.h' l='1815' type='clang::Sema *'/>
<use f='llvm/clang/include/clang/Sema/Sema.h' l='1818' u='w' c='_ZN5clang4Sema26PoppedFunctionScopeDeleterC1EPS0_'/>
<offset>0</offset>
<use f='llvm/clang/lib/Sema/Sema.cpp' l='2027' u='r' c='_ZNK5clang4Sema26PoppedFunctionScopeDeleterclEPNS_4sema17FunctionScopeInfoE'/>
<use f='llvm/clang/lib/Sema/Sema.cpp' l='2028' u='r' c='_ZNK5clang4Sema26PoppedFunctionScopeDeleterclEPNS_4sema17FunctionScopeInfoE'/>
