<dec f='llvm/clang/include/clang/AST/CommentSema.h' l='46' type='const clang::Preprocessor *'/>
<offset>256</offset>
<use f='llvm/clang/lib/AST/CommentSema.cpp' l='32' u='w' c='_ZN5clang8comments4SemaC1ERN4llvm20BumpPtrAllocatorImplINS2_15MallocAllocatorELm4096ELm4096ELm128EEERKNS_13SourceManagerERNS_17DiagnosticsEngineERNS0_151310'/>
<use f='llvm/clang/lib/AST/CommentSema.cpp' l='698' u='r' c='_ZN5clang8comments4Sema22checkDeprecatedCommandEPKNS0_19BlockCommandCommentE'/>
<use f='llvm/clang/lib/AST/CommentSema.cpp' l='705' u='r' c='_ZN5clang8comments4Sema22checkDeprecatedCommandEPKNS0_19BlockCommandCommentE'/>
<use f='llvm/clang/lib/AST/CommentSema.cpp' l='707' u='r' c='_ZN5clang8comments4Sema22checkDeprecatedCommandEPKNS0_19BlockCommandCommentE'/>
<use f='llvm/clang/lib/AST/CommentSema.cpp' l='715' u='r' c='_ZN5clang8comments4Sema22checkDeprecatedCommandEPKNS0_19BlockCommandCommentE'/>
<use f='llvm/clang/lib/AST/CommentSema.cpp' l='718' u='r' c='_ZN5clang8comments4Sema22checkDeprecatedCommandEPKNS0_19BlockCommandCommentE'/>
