<dec f='llvm/clang/include/clang/Basic/LangStandard.h' l='34' type='7'/>
<use f='llvm/clang/lib/Frontend/ASTUnit.cpp' l='2670' u='r' c='_ZNK5clang7ASTUnit12getInputKindEv'/>
<use f='llvm/clang/lib/Frontend/CompilerInstance.cpp' l='1011' u='r' c='_ZL22getLanguageFromOptionsRKN5clang11LangOptionsE'/>
<use f='llvm/clang/lib/Frontend/CompilerInvocation.cpp' l='490' u='r' c='_ZL20getOptimizationLevelRN4llvm3opt7ArgListEN5clang9InputKindERNS3_17DiagnosticsEngineE'/>
<use f='llvm/clang/lib/Frontend/CompilerInvocation.cpp' l='1746' u='r' c='_ZL17ParseFrontendArgsRN5clang15FrontendOptionsERN4llvm3opt7ArgListERNS_17DiagnosticsEngineERb'/>
<use f='llvm/clang/lib/Frontend/CompilerInvocation.cpp' l='1963' c='_ZN5clang18CompilerInvocation15setLangDefaultsERNS_11LangOptionsENS_9InputKindERKN4llvm6TripleERSt6vectorINSt7__cxx1112basic_stringIcSt11char_traitsIc12293528'/>
<use f='llvm/clang/lib/Frontend/CompilerInvocation.cpp' l='2107' c='_ZL29IsInputCompatibleWithStandardN5clang9InputKindERKNS_12LangStandardE'/>
<use f='llvm/clang/lib/Frontend/CompilerInvocation.cpp' l='2108' u='r' c='_ZL29IsInputCompatibleWithStandardN5clang9InputKindERKNS_12LangStandardE'/>
<use f='llvm/clang/lib/Frontend/CompilerInvocation.cpp' l='2143' c='_ZL16GetInputKindNameN5clang9InputKindE'/>
<use f='llvm/clang/lib/Frontend/FrontendActions.cpp' l='864' c='_ZN5clang19PrintPreambleAction13ExecuteActionEv'/>
<use f='llvm/clang/lib/Frontend/FrontendOptions.cpp' l='31' u='r' c='_ZN5clang15FrontendOptions24getInputKindForExtensionEN4llvm9StringRefE'/>
<use f='llvm/lldb/source/Plugins/TypeSystem/Clang/TypeSystemClang.cpp' l='479' c='_ZL13ParseLangArgsRN5clang11LangOptionsENS_9InputKindEPKc'/>
