<dec f='llvm/clang/include/clang/StaticAnalyzer/Core/PathSensitive/CoreEngine.h' l='75' type='clang::ento::ExplodedGraph'/>
<use f='llvm/clang/include/clang/StaticAnalyzer/Core/PathSensitive/CoreEngine.h' l='140' u='a' c='_ZN5clang4ento10CoreEngine8getGraphEv'/>
<offset>64</offset>
<doc f='llvm/clang/include/clang/StaticAnalyzer/Core/PathSensitive/CoreEngine.h' l='74'>/// G - The simulation graph.  Each node is a (location,state) pair.</doc>
<use f='llvm/clang/lib/StaticAnalyzer/Core/CoreEngine.cpp' l='76' u='m' c='_ZN5clang4ento10CoreEngineC1ERNS0_10ExprEngineEPNS0_19FunctionSummariesTyERNS_15AnalyzerOptionsE'/>
<use f='llvm/clang/lib/StaticAnalyzer/Core/CoreEngine.cpp' l='81' u='m' c='_ZN5clang4ento10CoreEngine15ExecuteWorkListEPKNS_15LocationContextEjN4llvm18IntrusiveRefCntPtrIKNS0_12ProgramStateEEE'/>
<use f='llvm/clang/lib/StaticAnalyzer/Core/CoreEngine.cpp' l='109' u='m' c='_ZN5clang4ento10CoreEngine15ExecuteWorkListEPKNS_15LocationContextEjN4llvm18IntrusiveRefCntPtrIKNS0_12ProgramStateEEE'/>
<use f='llvm/clang/lib/StaticAnalyzer/Core/CoreEngine.cpp' l='111' u='m' c='_ZN5clang4ento10CoreEngine15ExecuteWorkListEPKNS_15LocationContextEjN4llvm18IntrusiveRefCntPtrIKNS0_12ProgramStateEEE'/>
<use f='llvm/clang/lib/StaticAnalyzer/Core/CoreEngine.cpp' l='126' u='m' c='_ZN5clang4ento10CoreEngine15ExecuteWorkListEPKNS_15LocationContextEjN4llvm18IntrusiveRefCntPtrIKNS0_12ProgramStateEEE'/>
<use f='llvm/clang/lib/StaticAnalyzer/Core/CoreEngine.cpp' l='201' u='m' c='_ZN5clang4ento10CoreEngine31ExecuteWorkListWithInitialStateEPKNS_15LocationContextEjN4llvm18IntrusiveRefCntPtrIKNS0_12ProgramStateEEERNS0_15ExplodedNodeSetE'/>
<use f='llvm/clang/lib/StaticAnalyzer/Core/CoreEngine.cpp' l='201' u='m' c='_ZN5clang4ento10CoreEngine31ExecuteWorkListWithInitialStateEPKNS_15LocationContextEjN4llvm18IntrusiveRefCntPtrIKNS0_12ProgramStateEEERNS0_15ExplodedNodeSetE'/>
<use f='llvm/clang/lib/StaticAnalyzer/Core/CoreEngine.cpp' l='499' u='m' c='_ZN5clang4ento10CoreEngine12generateNodeERKNS_12ProgramPointEN4llvm18IntrusiveRefCntPtrIKNS0_12ProgramStateEEEPNS0_12ExplodedNodeE'/>
<use f='llvm/clang/lib/StaticAnalyzer/Core/CoreEngine.cpp' l='502' u='a' c='_ZN5clang4ento10CoreEngine12generateNodeERKNS_12ProgramPointEN4llvm18IntrusiveRefCntPtrIKNS0_12ProgramStateEEEPNS0_12ExplodedNodeE'/>
<use f='llvm/clang/lib/StaticAnalyzer/Core/CoreEngine.cpp' l='505' u='m' c='_ZN5clang4ento10CoreEngine12generateNodeERKNS_12ProgramPointEN4llvm18IntrusiveRefCntPtrIKNS0_12ProgramStateEEEPNS0_12ExplodedNodeE'/>
<use f='llvm/clang/lib/StaticAnalyzer/Core/CoreEngine.cpp' l='555' u='m' c='_ZN5clang4ento10CoreEngine15enqueueStmtNodeEPNS0_12ExplodedNodeEPKNS_8CFGBlockEj'/>
<use f='llvm/clang/lib/StaticAnalyzer/Core/CoreEngine.cpp' l='556' u='a' c='_ZN5clang4ento10CoreEngine15enqueueStmtNodeEPNS0_12ExplodedNodeEPKNS_8CFGBlockEj'/>
<use f='llvm/clang/lib/StaticAnalyzer/Core/CoreEngine.cpp' l='571' u='m' c='_ZN5clang4ento10CoreEngine25generateCallExitBeginNodeEPNS0_12ExplodedNodeEPKNS_10ReturnStmtE'/>
<use f='llvm/clang/lib/StaticAnalyzer/Core/CoreEngine.cpp' l='572' u='a' c='_ZN5clang4ento10CoreEngine25generateCallExitBeginNodeEPNS0_12ExplodedNodeEPKNS_10ReturnStmtE'/>
<use f='llvm/clang/lib/StaticAnalyzer/Core/CoreEngine.cpp' l='596' u='m' c='_ZN5clang4ento10CoreEngine20enqueueEndOfFunctionERNS0_15ExplodedNodeSetEPKNS_10ReturnStmtE'/>
<use f='llvm/clang/lib/StaticAnalyzer/Core/CoreEngine.cpp' l='610' u='m' c='_ZN5clang4ento11NodeBuilder16generateNodeImplERKNS_12ProgramPointEN4llvm18IntrusiveRefCntPtrIKNS0_12ProgramStateEEEPNS0_12ExplodedNodeEb'/>
<use f='llvm/clang/lib/StaticAnalyzer/Core/CoreEngine.cpp' l='611' u='a' c='_ZN5clang4ento11NodeBuilder16generateNodeImplERKNS_12ProgramPointEN4llvm18IntrusiveRefCntPtrIKNS0_12ProgramStateEEEPNS0_12ExplodedNodeEb'/>
<use f='llvm/clang/lib/StaticAnalyzer/Core/CoreEngine.cpp' l='652' u='m' c='_ZN5clang4ento23IndirectGotoNodeBuilder12generateNodeERKNS1_8iteratorEN4llvm18IntrusiveRefCntPtrIKNS0_12ProgramStateEEEb'/>
<use f='llvm/clang/lib/StaticAnalyzer/Core/CoreEngine.cpp' l='654' u='a' c='_ZN5clang4ento23IndirectGotoNodeBuilder12generateNodeERKNS1_8iteratorEN4llvm18IntrusiveRefCntPtrIKNS0_12ProgramStateEEEb'/>
<use f='llvm/clang/lib/StaticAnalyzer/Core/CoreEngine.cpp' l='670' u='m' c='_ZN5clang4ento17SwitchNodeBuilder20generateCaseStmtNodeERKNS1_8iteratorEN4llvm18IntrusiveRefCntPtrIKNS0_12ProgramStateEEE'/>
<use f='llvm/clang/lib/StaticAnalyzer/Core/CoreEngine.cpp' l='672' u='a' c='_ZN5clang4ento17SwitchNodeBuilder20generateCaseStmtNodeERKNS1_8iteratorEN4llvm18IntrusiveRefCntPtrIKNS0_12ProgramStateEEE'/>
<use f='llvm/clang/lib/StaticAnalyzer/Core/CoreEngine.cpp' l='694' u='m' c='_ZN5clang4ento17SwitchNodeBuilder23generateDefaultCaseNodeEN4llvm18IntrusiveRefCntPtrIKNS0_12ProgramStateEEEb'/>
<use f='llvm/clang/lib/StaticAnalyzer/Core/CoreEngine.cpp' l='696' u='a' c='_ZN5clang4ento17SwitchNodeBuilder23generateDefaultCaseNodeEN4llvm18IntrusiveRefCntPtrIKNS0_12ProgramStateEEEb'/>
