<dec f='llvm/clang/include/clang/Basic/LangStandard.h' l='37' type='10'/>
<use f='llvm/clang/lib/Frontend/CompilerInvocation.cpp' l='1748' u='r' c='_ZL17ParseFrontendArgsRN5clang15FrontendOptionsERN4llvm3opt7ArgListERNS_17DiagnosticsEngineERb'/>
<use f='llvm/clang/lib/Frontend/CompilerInvocation.cpp' l='1999' c='_ZN5clang18CompilerInvocation15setLangDefaultsERNS_11LangOptionsENS_9InputKindERKN4llvm6TripleERSt6vectorINSt7__cxx1112basic_stringIcSt11char_traitsIc12293528'/>
<use f='llvm/clang/lib/Frontend/CompilerInvocation.cpp' l='2056' u='r' c='_ZN5clang18CompilerInvocation15setLangDefaultsERNS_11LangOptionsENS_9InputKindERKN4llvm6TripleERSt6vectorINSt7__cxx1112basic_stringIcSt11char_traitsIc12293528'/>
<use f='llvm/clang/lib/Frontend/CompilerInvocation.cpp' l='2119' c='_ZL29IsInputCompatibleWithStandardN5clang9InputKindERKNS_12LangStandardE'/>
<use f='llvm/clang/lib/Frontend/CompilerInvocation.cpp' l='2120' u='r' c='_ZL29IsInputCompatibleWithStandardN5clang9InputKindERKNS_12LangStandardE'/>
<use f='llvm/clang/lib/Frontend/CompilerInvocation.cpp' l='2149' c='_ZL16GetInputKindNameN5clang9InputKindE'/>
<use f='llvm/clang/lib/Frontend/FrontendActions.cpp' l='866' c='_ZN5clang19PrintPreambleAction13ExecuteActionEv'/>
<use f='llvm/clang/lib/Frontend/FrontendOptions.cpp' l='33' u='r' c='_ZN5clang15FrontendOptions24getInputKindForExtensionEN4llvm9StringRefE'/>
<use f='llvm/lldb/source/Plugins/TypeSystem/Clang/TypeSystemClang.cpp' l='494' c='_ZL13ParseLangArgsRN5clang11LangOptionsENS_9InputKindEPKc'/>
