<dec f='llvm/clang/include/clang/Basic/LangOptions.h' l='186' type='3'/>
<doc f='llvm/clang/include/clang/Basic/LangOptions.h' l='185'>/// Interoperability with the latest known version of the Swift runtime</doc>
<use f='llvm/clang/lib/AST/ASTContext.cpp' l='6496' u='r' c='_ZNK5clang10ASTContext23getCFConstantStringDeclEv'/>
<use f='llvm/clang/lib/CodeGen/CodeGenModule.cpp' l='4987' u='r' c='_ZN5clang7CodeGen13CodeGenModule25GetAddrOfConstantCFStringEPKNS_13StringLiteralE'/>
<use f='llvm/clang/lib/CodeGen/CodeGenModule.cpp' l='4998' c='_ZN5clang7CodeGen13CodeGenModule25GetAddrOfConstantCFStringEPKNS_13StringLiteralE'/>
