<dec f='llvm/clang/include/clang/AST/Type.h' l='4481' type='clang::Expr *'/>
<use f='llvm/clang/include/clang/AST/Type.h' l='4490' u='r' c='_ZNK5clang12DecltypeType17getUnderlyingExprEv'/>
<offset>192</offset>
<use f='llvm/clang/lib/AST/Type.cpp' l='3430' u='w' c='_ZN5clang12DecltypeTypeC1EPNS_4ExprENS_8QualTypeES3_'/>
<use f='llvm/clang/lib/AST/Type.cpp' l='3432' u='r' c='_ZNK5clang12DecltypeType9isSugaredEv'/>
