<dec f='llvm/clang/include/clang/Parse/Parser.h' l='2131' type='clang::CXXScopeSpec'/>
<offset>64</offset>
<doc f='llvm/clang/include/clang/Parse/Parser.h' l='2130'>/// Nested-name-specifier preceding the name.</doc>
<use f='llvm/clang/lib/Parse/ParseStmt.cpp' l='2515' u='a' c='_ZN5clang6Parser31ParseMicrosoftIfExistsStatementERN4llvm11SmallVectorIPNS_4StmtELj32EEE'/>
<use f='llvm/clang/lib/Parse/Parser.cpp' l='2183' u='a' c='_ZN5clang6Parser31ParseMicrosoftIfExistsConditionERNS0_17IfExistsConditionE'/>
<use f='llvm/clang/lib/Parse/Parser.cpp' l='2188' u='m' c='_ZN5clang6Parser31ParseMicrosoftIfExistsConditionERNS0_17IfExistsConditionE'/>
<use f='llvm/clang/lib/Parse/Parser.cpp' l='2195' u='a' c='_ZN5clang6Parser31ParseMicrosoftIfExistsConditionERNS0_17IfExistsConditionE'/>
<use f='llvm/clang/lib/Parse/Parser.cpp' l='2210' u='a' c='_ZN5clang6Parser31ParseMicrosoftIfExistsConditionERNS0_17IfExistsConditionE'/>
