<dec f='llvm/clang/include/clang/AST/Expr.h' l='3728' type='0'/>
<use f='llvm/clang/include/clang/AST/Expr.h' l='3776' u='r' c='_ZNK5clang14BinaryOperator6getLHSEv'/>
<use f='llvm/clang/include/clang/AST/Expr.h' l='3777' u='w' c='_ZN5clang14BinaryOperator6setLHSEPNS_4ExprE'/>
<use f='llvm/clang/lib/AST/Expr.cpp' l='4333' u='w' c='_ZN5clang14BinaryOperatorC1ERKNS_10ASTContextEPNS_4ExprES5_NS_18BinaryOperatorKindENS_8QualTypeENS_13ExprValueKindENS_14ExprObjectKindENS_14SourceLoca6958891'/>
<use f='llvm/clang/lib/AST/Expr.cpp' l='4350' u='w' c='_ZN5clang14BinaryOperatorC1ERKNS_10ASTContextEPNS_4ExprES5_NS_18BinaryOperatorKindENS_8QualTypeENS_13ExprValueKindENS_14ExprObjectKindENS_14SourceLoca14702311'/>
