<dec f='llvm/clang/include/clang/StaticAnalyzer/Core/PathSensitive/BasicValueFactory.h' l='83' type='llvm::ImmutableList&lt;const CXXBaseSpecifier *&gt;'/>
<use f='llvm/clang/include/clang/StaticAnalyzer/Core/PathSensitive/BasicValueFactory.h' l='88' u='w' c='_ZN5clang4ento19PointerToMemberDataC1EPKNS_9NamedDeclEN4llvm13ImmutableListIPKNS_16CXXBaseSpecifierEEE'/>
<use f='llvm/clang/include/clang/StaticAnalyzer/Core/PathSensitive/BasicValueFactory.h' l='92' u='m' c='_ZNK5clang4ento19PointerToMemberData5beginEv'/>
<use f='llvm/clang/include/clang/StaticAnalyzer/Core/PathSensitive/BasicValueFactory.h' l='93' u='m' c='_ZNK5clang4ento19PointerToMemberData3endEv'/>
<use f='llvm/clang/include/clang/StaticAnalyzer/Core/PathSensitive/BasicValueFactory.h' l='98' u='r' c='_ZN5clang4ento19PointerToMemberData7ProfileERN4llvm16FoldingSetNodeIDE'/>
<use f='llvm/clang/include/clang/StaticAnalyzer/Core/PathSensitive/BasicValueFactory.h' l='102' u='r' c='_ZNK5clang4ento19PointerToMemberData14getCXXBaseListEv'/>
<offset>128</offset>
