<dec f='llvm/clang/include/clang/AST/DeclCXX.h' l='2179' type='clang::Stmt *'/>
<use f='llvm/clang/include/clang/AST/DeclCXX.h' l='2254' u='r' c='_ZNK5clang18CXXCtorInitializer26isInClassMemberInitializerEv'/>
<use f='llvm/clang/include/clang/AST/DeclCXX.h' l='2360' u='r' c='_ZNK5clang18CXXCtorInitializer7getInitEv'/>
<offset>128</offset>
<doc f='llvm/clang/include/clang/AST/DeclCXX.h' l='2177'>/// The argument used to initialize the base or member, which may
  /// end up constructing an object (when multiple arguments are involved).</doc>
<use f='llvm/clang/lib/AST/DeclCXX.cpp' l='2509' u='w' c='_ZN5clang18CXXCtorInitializerC1ERNS_10ASTContextEPNS_14TypeSourceInfoEbNS_14SourceLocationEPNS_4ExprES5_S5_'/>
<use f='llvm/clang/lib/AST/DeclCXX.cpp' l='2518' u='w' c='_ZN5clang18CXXCtorInitializerC1ERNS_10ASTContextEPNS_9FieldDeclENS_14SourceLocationES5_PNS_4ExprES5_'/>
<use f='llvm/clang/lib/AST/DeclCXX.cpp' l='2527' u='w' c='_ZN5clang18CXXCtorInitializerC1ERNS_10ASTContextEPNS_17IndirectFieldDeclENS_14SourceLocationES5_PNS_4ExprES5_'/>
<use f='llvm/clang/lib/AST/DeclCXX.cpp' l='2535' u='w' c='_ZN5clang18CXXCtorInitializerC1ERNS_10ASTContextEPNS_14TypeSourceInfoENS_14SourceLocationEPNS_4ExprES5_'/>
