<dec f='llvm/clang/include/clang/StaticAnalyzer/Core/PathSensitive/BasicValueFactory.h' l='42' type='clang::QualType'/>
<use f='llvm/clang/include/clang/StaticAnalyzer/Core/PathSensitive/BasicValueFactory.h' l='46' u='w' c='_ZN5clang4ento15CompoundValDataC1ENS_8QualTypeEN4llvm13ImmutableListINS0_4SValEEE'/>
<use f='llvm/clang/include/clang/StaticAnalyzer/Core/PathSensitive/BasicValueFactory.h' l='58' u='r' c='_ZN5clang4ento15CompoundValData7ProfileERN4llvm16FoldingSetNodeIDE'/>
<offset>64</offset>
