<dec f='llvm/lldb/source/Plugins/Instruction/ARM64/EmulateInstructionARM64.h' l='135' type='uint32_t'/>
<use f='llvm/lldb/source/Plugins/Instruction/ARM64/EmulateInstructionARM64.cpp' l='548' u='r' c='_ZN23EmulateInstructionARM6414ConditionHoldsEj'/>
<use f='llvm/lldb/source/Plugins/Instruction/ARM64/EmulateInstructionARM64.cpp' l='554' u='r' c='_ZN23EmulateInstructionARM6414ConditionHoldsEj'/>
<use f='llvm/lldb/source/Plugins/Instruction/ARM64/EmulateInstructionARM64.cpp' l='557' u='r' c='_ZN23EmulateInstructionARM6414ConditionHoldsEj'/>
<use f='llvm/lldb/source/Plugins/Instruction/ARM64/EmulateInstructionARM64.cpp' l='584' u='w' c='_ZN23EmulateInstructionARM6412AddWithCarryEjmmbRNS_9ProcStateE'/>
<use f='llvm/lldb/source/Plugins/Instruction/ARM64/EmulateInstructionARM64.cpp' l='673' u='w' c='_ZN23EmulateInstructionARM6416EmulateADDSUBImmEj'/>
<use f='llvm/lldb/source/Plugins/Instruction/ARM64/EmulateInstructionARM64.cpp' l='673' u='r' c='_ZN23EmulateInstructionARM6416EmulateADDSUBImmEj'/>
<offset>1</offset>
<use f='llvm/lldb/unittests/Instruction/TestAArch64Emulator.cpp' l='54' u='r' c='_ZN37TestAArch64Emulator_TestOverflow_Test8TestBodyEv'/>
<use f='llvm/lldb/unittests/Instruction/TestAArch64Emulator.cpp' l='54' u='r' c='_ZN37TestAArch64Emulator_TestOverflow_Test8TestBodyEv'/>
<use f='llvm/lldb/unittests/Instruction/TestAArch64Emulator.cpp' l='57' u='r' c='_ZN37TestAArch64Emulator_TestOverflow_Test8TestBodyEv'/>
<use f='llvm/lldb/unittests/Instruction/TestAArch64Emulator.cpp' l='57' u='r' c='_ZN37TestAArch64Emulator_TestOverflow_Test8TestBodyEv'/>
<use f='llvm/lldb/unittests/Instruction/TestAArch64Emulator.cpp' l='60' u='r' c='_ZN37TestAArch64Emulator_TestOverflow_Test8TestBodyEv'/>
<use f='llvm/lldb/unittests/Instruction/TestAArch64Emulator.cpp' l='60' u='r' c='_ZN37TestAArch64Emulator_TestOverflow_Test8TestBodyEv'/>
