<use f='llvm/compiler-rt/lib/fuzzer/FuzzerDictionary.h' l='52' u='w' c='_ZN6fuzzer15DictionaryEntryC1ENS_9FixedWordILm64EEE'/>
<use f='llvm/compiler-rt/lib/fuzzer/FuzzerDictionary.h' l='53' u='w' c='_ZN6fuzzer15DictionaryEntryC1ENS_9FixedWordILm64EEEm'/>
<use f='llvm/compiler-rt/lib/fuzzer/FuzzerDictionary.h' l='54' u='a' c='_ZNK6fuzzer15DictionaryEntry4GetWEv'/>
<use f='llvm/compiler-rt/lib/fuzzer/FuzzerDictionary.h' l='67' u='m' c='_ZN6fuzzer15DictionaryEntry5PrintEPKc'/>
<use f='llvm/compiler-rt/lib/fuzzer/FuzzerDictionary.h' l='67' u='m' c='_ZN6fuzzer15DictionaryEntry5PrintEPKc'/>
<dec f='llvm/compiler-rt/lib/fuzzer/FuzzerDictionary.h' l='74' type='fuzzer::Word'/>
<offset>0</offset>
