<def f='llvm/compiler-rt/lib/fuzzer/FuzzerTracePC.h' l='140' ll='155'/>
<use f='llvm/compiler-rt/lib/fuzzer/FuzzerTracePC.h' l='157'/>
<size>16</size>
<doc f='llvm/compiler-rt/lib/fuzzer/FuzzerTracePC.h' l='137'>// Module represents the array of 8-bit counters split into regions
  // such that every region, except maybe the first and the last one, is one
  // full page.</doc>
<mbr r='fuzzer::TracePC::Module::Regions' o='0' t='fuzzer::TracePC::Module::Region *'/>
<mbr r='fuzzer::TracePC::Module::NumRegions' o='64' t='size_t'/>
<fun r='_ZN6fuzzer7TracePC6Module5StartEv'/>
<fun r='_ZN6fuzzer7TracePC6Module4StopEv'/>
<fun r='_ZN6fuzzer7TracePC6Module4SizeEv'/>
<fun r='_ZN6fuzzer7TracePC6Module3IdxEPh'/>
