<def f='llvm/compiler-rt/lib/fuzzer/FuzzerCommand.h' l='25' ll='174'/>
<use f='llvm/compiler-rt/lib/fuzzer/FuzzerCommand.h' l='39' c='_ZN6fuzzer7CommandC1ERKS0_'/>
<use f='llvm/compiler-rt/lib/fuzzer/FuzzerCommand.h' l='43' c='_ZN6fuzzer7CommandaSERKS0_'/>
<use f='llvm/compiler-rt/lib/fuzzer/FuzzerCommand.h' l='43' c='_ZN6fuzzer7CommandaSERKS0_'/>
<use f='llvm/compiler-rt/lib/fuzzer/FuzzerCommand.h' l='155' c='_ZN6fuzzer7CommandC1EOS0_'/>
<use f='llvm/compiler-rt/lib/fuzzer/FuzzerCommand.h' l='156' c='_ZN6fuzzer7CommandaSEOS0_'/>
<use f='llvm/compiler-rt/lib/fuzzer/FuzzerCommand.h' l='156' c='_ZN6fuzzer7CommandaSEOS0_'/>
<use f='llvm/compiler-rt/lib/fuzzer/FuzzerUtil.h' l='59' c='_ZN6fuzzer14ExecuteCommandERKNS_7CommandE'/>
<use f='llvm/compiler-rt/lib/fuzzer/FuzzerUtil.h' l='60' c='_ZN6fuzzer14ExecuteCommandERKNS_7CommandEPNSt8__Fuzzer12basic_stringIcNS3_11char_traitsIcEENS3_9allocatorIcEEEE'/>
<size>56</size>
<fun r='_ZN6fuzzer7Command19ignoreRemainingArgsEv'/>
<fun r='_ZN6fuzzer7CommandC1Ev'/>
<fun r='_ZN6fuzzer7CommandC1ERKNSt8__Fuzzer6vectorINS1_12basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEENS_16fuzzer_allocatorIS8_EEEE'/>
<fun r='_ZN6fuzzer7CommandC1ERKS0_'/>
<fun r='_ZN6fuzzer7CommandaSERKS0_'/>
<fun r='_ZN6fuzzer7CommandD1Ev'/>
<fun r='_ZNK6fuzzer7Command11hasArgumentERKNSt8__Fuzzer12basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEE'/>
<fun r='_ZNK6fuzzer7Command12getArgumentsEv'/>
<fun r='_ZN6fuzzer7Command11addArgumentERKNSt8__Fuzzer12basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEE'/>
<fun r='_ZN6fuzzer7Command12addArgumentsERKNSt8__Fuzzer6vectorINS1_12basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEENS_16fuzzer_allocatorIS8_EEEE'/>
<fun r='_ZN6fuzzer7Command14removeArgumentERKNSt8__Fuzzer12basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEE'/>
<fun r='_ZNK6fuzzer7Command7hasFlagERKNSt8__Fuzzer12basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEE'/>
<fun r='_ZNK6fuzzer7Command12getFlagValueERKNSt8__Fuzzer12basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEE'/>
<fun r='_ZN6fuzzer7Command7addFlagERKNSt8__Fuzzer12basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEES9_'/>
<fun r='_ZN6fuzzer7Command10removeFlagERKNSt8__Fuzzer12basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEE'/>
<fun r='_ZNK6fuzzer7Command13hasOutputFileEv'/>
<fun r='_ZNK6fuzzer7Command13getOutputFileEv'/>
<fun r='_ZN6fuzzer7Command13setOutputFileERKNSt8__Fuzzer12basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEE'/>
<fun r='_ZNK6fuzzer7Command19isOutAndErrCombinedEv'/>
<fun r='_ZN6fuzzer7Command16combineOutAndErrEb'/>
<fun r='_ZNK6fuzzer7Command8toStringEv'/>
<fun r='_ZN6fuzzer7CommandC1EOS0_'/>
<fun r='_ZN6fuzzer7CommandaSEOS0_'/>
<fun r='_ZN6fuzzer7Command14endMutableArgsEv'/>
<fun r='_ZNK6fuzzer7Command14endMutableArgsEv'/>
<mbr r='fuzzer::Command::Args' o='0' t='Vector&lt;std::string&gt;'/>
<mbr r='fuzzer::Command::CombinedOutAndErr' o='192' t='bool'/>
<mbr r='fuzzer::Command::OutputFile' o='256' t='std::string'/>
<use f='llvm/compiler-rt/lib/fuzzer/FuzzerDataFlowTrace.cpp' l='268' c='_ZN6fuzzer15CollectDataFlowERKNSt8__Fuzzer12basic_stringIcNS0_11char_traitsIcEENS0_9allocatorIcEEEES8_RKNS0_6vectorINS_9SizedFileENS_16fuzzer_allocatorISA_EEEE'/>
<use f='llvm/compiler-rt/lib/fuzzer/FuzzerDataFlowTrace.cpp' l='278' c='_ZN6fuzzer15CollectDataFlowERKNSt8__Fuzzer12basic_stringIcNS0_11char_traitsIcEENS0_9allocatorIcEEEES8_RKNS0_6vectorINS_9SizedFileENS_16fuzzer_allocatorISA_EEEE'/>
<size>56</size>
<use f='llvm/compiler-rt/lib/fuzzer/FuzzerDriver.cpp' l='230' c='_ZN6fuzzerL12WorkerThreadERKNS_7CommandEPNSt8__Fuzzer6atomicIjEEjPNS4_IbEE'/>
<use f='llvm/compiler-rt/lib/fuzzer/FuzzerDriver.cpp' l='236' c='_ZN6fuzzerL12WorkerThreadERKNS_7CommandEPNSt8__Fuzzer6atomicIjEEjPNS4_IbEE'/>
<use f='llvm/compiler-rt/lib/fuzzer/FuzzerDriver.cpp' l='290' c='_ZN6fuzzerL22RunInMultipleProcessesERKNSt8__Fuzzer6vectorINS0_12basic_stringIcNS0_11char_traitsIcEENS0_9allocatorIcEEEENS_16fuzzer_allocatorIS7_EEEEjj'/>
<use f='llvm/compiler-rt/lib/fuzzer/FuzzerDriver.cpp' l='360' c='_ZN6fuzzer17CleanseCrashInputERKNSt8__Fuzzer6vectorINS0_12basic_stringIcNS0_11char_traitsIcEENS0_9allocatorIcEEEENS_16fuzzer_allocatorIS7_EEEERKNS_14FuzzingOptionsE'/>
<use f='llvm/compiler-rt/lib/fuzzer/FuzzerDriver.cpp' l='413' c='_ZN6fuzzer18MinimizeCrashInputERKNSt8__Fuzzer6vectorINS0_12basic_stringIcNS0_11char_traitsIcEENS0_9allocatorIcEEEENS_16fuzzer_allocatorIS7_EEEERKNS_14FuzzingOptionsE'/>
<use f='llvm/compiler-rt/lib/fuzzer/FuzzerDriver.cpp' l='433' c='_ZN6fuzzer18MinimizeCrashInputERKNSt8__Fuzzer6vectorINS0_12basic_stringIcNS0_11char_traitsIcEENS0_9allocatorIcEEEENS_16fuzzer_allocatorIS7_EEEERKNS_14FuzzingOptionsE'/>
<size>56</size>
<use f='llvm/compiler-rt/lib/fuzzer/FuzzerFork.cpp' l='66'/>
<use f='llvm/compiler-rt/lib/fuzzer/FuzzerFork.cpp' l='118' c='_ZN6fuzzer9GlobalEnv12CreateNewJobEm'/>
<use f='llvm/compiler-rt/lib/fuzzer/FuzzerFork.cpp' l='236' c='_ZN6fuzzer9GlobalEnv10CollectDFTERKNSt8__Fuzzer12basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEE'/>
<size>56</size>
<use f='llvm/compiler-rt/lib/fuzzer/FuzzerMerge.cpp' l='362' c='_ZN6fuzzer19CrashResistantMergeERKNSt8__Fuzzer6vectorINS0_12basic_stringIcNS0_11char_traitsIcEENS0_9allocatorIcEEEENS_16fuzzer_allocatorIS7_EEEERKNS1_13171865'/>
<use f='llvm/compiler-rt/lib/fuzzer/FuzzerMerge.cpp' l='369' c='_ZN6fuzzer19CrashResistantMergeERKNSt8__Fuzzer6vectorINS0_12basic_stringIcNS0_11char_traitsIcEENS0_9allocatorIcEEEENS_16fuzzer_allocatorIS7_EEEERKNS1_13171865'/>
<size>56</size>
<use f='llvm/compiler-rt/lib/fuzzer/FuzzerUtilLinux.cpp' l='23' c='_ZN6fuzzer14ExecuteCommandERKNS_7CommandE'/>
<size>56</size>
<use f='llvm/compiler-rt/lib/fuzzer/FuzzerUtilPosix.cpp' l='90' c='_ZN6fuzzer14ExecuteCommandERKNS_7CommandEPNSt8__Fuzzer12basic_stringIcNS3_11char_traitsIcEENS3_9allocatorIcEEEE'/>
<size>56</size>
