<dec f='llvm/polly/lib/External/ppcg/gpu_group.h' l='20' type='int'/>
<offset>128</offset>
<doc f='llvm/polly/lib/External/ppcg/gpu_group.h' l='19'>/* Position of this group in the list of reference groups of array. */</doc>
<use f='llvm/polly/lib/External/ppcg/gpu_group.c' l='40' u='r' c='gpu_array_ref_group_print_name'/>
<use f='llvm/polly/lib/External/ppcg/gpu_group.c' l='1404' u='w' c='set_array_groups'/>
