<dec f='llvm/compiler-rt/lib/gwp_asan/platform_specific/mutex_posix.h' l='18' type='pthread_mutex_t'/>
<offset>0</offset>
<use f='llvm/compiler-rt/lib/gwp_asan/platform_specific/mutex_posix.cpp' l='16' u='a' c='_ZN8gwp_asan5Mutex4lockEv'/>
<use f='llvm/compiler-rt/lib/gwp_asan/platform_specific/mutex_posix.cpp' l='22' u='a' c='_ZN8gwp_asan5Mutex7tryLockEv'/>
<use f='llvm/compiler-rt/lib/gwp_asan/platform_specific/mutex_posix.cpp' l='25' u='a' c='_ZN8gwp_asan5Mutex6unlockEv'/>
