<use f='llvm/compiler-rt/lib/gwp_asan/mutex.h' l='32' u='w' c='_ZN8gwp_asan10ScopedLockC1ERNS_5MutexE'/>
<use f='llvm/compiler-rt/lib/gwp_asan/mutex.h' l='32' u='m' c='_ZN8gwp_asan10ScopedLockC1ERNS_5MutexE'/>
<use f='llvm/compiler-rt/lib/gwp_asan/mutex.h' l='33' u='m' c='_ZN8gwp_asan10ScopedLockD1Ev'/>
<dec f='llvm/compiler-rt/lib/gwp_asan/mutex.h' l='38' type='gwp_asan::Mutex &amp;'/>
<offset>0</offset>
