<dec f='llvm/polly/lib/External/isl/isl_polynomial_private.h' l='30' type='isl_poly *[]'/>
<offset>320</offset>
<use f='llvm/polly/lib/External/isl/isl_fold.c' l='582' u='r' c='isl_qpolynomial_sign'/>
<use f='llvm/polly/lib/External/isl/isl_fold.c' l='588' u='r' c='isl_qpolynomial_sign'/>
<use f='llvm/polly/lib/External/isl/isl_output.c' l='1747' u='r' c='poly_rec_n_non_zero'/>
<use f='llvm/polly/lib/External/isl/isl_output.c' l='1851' u='r' c='poly_print'/>
<use f='llvm/polly/lib/External/isl/isl_output.c' l='1852' u='r' c='poly_print'/>
<use f='llvm/polly/lib/External/isl/isl_output.c' l='1853' u='r' c='poly_print'/>
<use f='llvm/polly/lib/External/isl/isl_output.c' l='1854' u='r' c='poly_print'/>
<use f='llvm/polly/lib/External/isl/isl_output.c' l='1868' u='r' c='poly_print'/>
<use f='llvm/polly/lib/External/isl/isl_output.c' l='1873' u='r' c='poly_print'/>
<use f='llvm/polly/lib/External/isl/isl_polynomial.c' l='124' u='r' c='isl_poly_plain_cmp'/>
<use f='llvm/polly/lib/External/isl/isl_polynomial.c' l='124' u='r' c='isl_poly_plain_cmp'/>
<use f='llvm/polly/lib/External/isl/isl_polynomial.c' l='167' u='r' c='isl_poly_is_equal'/>
<use f='llvm/polly/lib/External/isl/isl_polynomial.c' l='167' u='r' c='isl_poly_is_equal'/>
<use f='llvm/polly/lib/External/isl/isl_polynomial.c' l='636' u='r' c='poly_free_rec'/>
<use f='llvm/polly/lib/External/isl/isl_polynomial.c' l='681' u='w' c='isl_poly_dup_rec'/>
<use f='llvm/polly/lib/External/isl/isl_polynomial.c' l='681' u='r' c='isl_poly_dup_rec'/>
<use f='llvm/polly/lib/External/isl/isl_polynomial.c' l='682' u='r' c='isl_poly_dup_rec'/>
<use f='llvm/polly/lib/External/isl/isl_polynomial.c' l='801' u='r' c='replace_by_constant_term'/>
<use f='llvm/polly/lib/External/isl/isl_polynomial.c' l='871' u='w' c='isl_poly_sum'/>
<use f='llvm/polly/lib/External/isl/isl_polynomial.c' l='871' u='r' c='isl_poly_sum'/>
<use f='llvm/polly/lib/External/isl/isl_polynomial.c' l='899' u='w' c='isl_poly_sum'/>
<use f='llvm/polly/lib/External/isl/isl_polynomial.c' l='899' u='r' c='isl_poly_sum'/>
<use f='llvm/polly/lib/External/isl/isl_polynomial.c' l='900' u='r' c='isl_poly_sum'/>
<use f='llvm/polly/lib/External/isl/isl_polynomial.c' l='901' u='r' c='isl_poly_sum'/>
<use f='llvm/polly/lib/External/isl/isl_polynomial.c' l='905' u='r' c='isl_poly_sum'/>
<use f='llvm/polly/lib/External/isl/isl_polynomial.c' l='909' u='r' c='isl_poly_sum'/>
<use f='llvm/polly/lib/External/isl/isl_polynomial.c' l='960' u='w' c='isl_poly_add_isl_int'/>
<use f='llvm/polly/lib/External/isl/isl_polynomial.c' l='960' u='r' c='isl_poly_add_isl_int'/>
<use f='llvm/polly/lib/External/isl/isl_polynomial.c' l='961' u='r' c='isl_poly_add_isl_int'/>
<use f='llvm/polly/lib/External/isl/isl_polynomial.c' l='1011' u='w' c='isl_poly_mul_isl_int'/>
<use f='llvm/polly/lib/External/isl/isl_polynomial.c' l='1011' u='r' c='isl_poly_mul_isl_int'/>
<use f='llvm/polly/lib/External/isl/isl_polynomial.c' l='1012' u='r' c='isl_poly_mul_isl_int'/>
<use f='llvm/polly/lib/External/isl/isl_polynomial.c' l='1070' u='w' c='isl_poly_scale_val'/>
<use f='llvm/polly/lib/External/isl/isl_polynomial.c' l='1070' u='r' c='isl_poly_scale_val'/>
<use f='llvm/polly/lib/External/isl/isl_polynomial.c' l='1071' u='r' c='isl_poly_scale_val'/>
<use f='llvm/polly/lib/External/isl/isl_polynomial.c' l='1126' u='w' c='isl_poly_mul_rec'/>
<use f='llvm/polly/lib/External/isl/isl_polynomial.c' l='1126' u='r' c='isl_poly_mul_rec'/>
<use f='llvm/polly/lib/External/isl/isl_polynomial.c' l='1127' u='r' c='isl_poly_mul_rec'/>
<use f='llvm/polly/lib/External/isl/isl_polynomial.c' l='1128' u='r' c='isl_poly_mul_rec'/>
<use f='llvm/polly/lib/External/isl/isl_polynomial.c' l='1133' u='w' c='isl_poly_mul_rec'/>
<use f='llvm/polly/lib/External/isl/isl_polynomial.c' l='1134' u='r' c='isl_poly_mul_rec'/>
<use f='llvm/polly/lib/External/isl/isl_polynomial.c' l='1141' u='r' c='isl_poly_mul_rec'/>
<use f='llvm/polly/lib/External/isl/isl_polynomial.c' l='1142' u='r' c='isl_poly_mul_rec'/>
<use f='llvm/polly/lib/External/isl/isl_polynomial.c' l='1143' u='w' c='isl_poly_mul_rec'/>
<use f='llvm/polly/lib/External/isl/isl_polynomial.c' l='1143' u='r' c='isl_poly_mul_rec'/>
<use f='llvm/polly/lib/External/isl/isl_polynomial.c' l='1144' u='r' c='isl_poly_mul_rec'/>
<use f='llvm/polly/lib/External/isl/isl_polynomial.c' l='1241' u='w' c='isl_poly_mul'/>
<use f='llvm/polly/lib/External/isl/isl_polynomial.c' l='1241' u='r' c='isl_poly_mul'/>
<use f='llvm/polly/lib/External/isl/isl_polynomial.c' l='1243' u='r' c='isl_poly_mul'/>
<use f='llvm/polly/lib/External/isl/isl_polynomial.c' l='1390' u='w' c='isl_poly_var_pow'/>
<use f='llvm/polly/lib/External/isl/isl_polynomial.c' l='1391' u='r' c='isl_poly_var_pow'/>
<use f='llvm/polly/lib/External/isl/isl_polynomial.c' l='1395' u='r' c='isl_poly_var_pow'/>
<use f='llvm/polly/lib/External/isl/isl_polynomial.c' l='1427' u='r' c='reorder'/>
<use f='llvm/polly/lib/External/isl/isl_polynomial.c' l='1431' u='r' c='reorder'/>
<use f='llvm/polly/lib/External/isl/isl_polynomial.c' l='1614' u='w' c='expand'/>
<use f='llvm/polly/lib/External/isl/isl_polynomial.c' l='1614' u='r' c='expand'/>
<use f='llvm/polly/lib/External/isl/isl_polynomial.c' l='1615' u='r' c='expand'/>
<use f='llvm/polly/lib/External/isl/isl_polynomial.c' l='2023' u='r' c='isl_poly_get_constant_val'/>
<use f='llvm/polly/lib/External/isl/isl_polynomial.c' l='2065' u='r' c='isl_poly_is_affine'/>
<use f='llvm/polly/lib/External/isl/isl_polynomial.c' l='2069' u='r' c='isl_poly_is_affine'/>
<use f='llvm/polly/lib/External/isl/isl_polynomial.c' l='2126' u='r' c='isl_poly_update_affine'/>
<use f='llvm/polly/lib/External/isl/isl_polynomial.c' l='2131' u='r' c='isl_poly_update_affine'/>
<use f='llvm/polly/lib/External/isl/isl_polynomial.c' l='2237' u='r' c='poly_update_den'/>
<use f='llvm/polly/lib/External/isl/isl_polynomial.c' l='2314' u='r' c='isl_poly_subs'/>
<use f='llvm/polly/lib/External/isl/isl_polynomial.c' l='2317' u='r' c='isl_poly_subs'/>
<use f='llvm/polly/lib/External/isl/isl_polynomial.c' l='2678' u='r' c='poly_set_active'/>
<use f='llvm/polly/lib/External/isl/isl_polynomial.c' l='2866' u='w' c='isl_poly_drop'/>
<use f='llvm/polly/lib/External/isl/isl_polynomial.c' l='2866' u='r' c='isl_poly_drop'/>
<use f='llvm/polly/lib/External/isl/isl_polynomial.c' l='2867' u='r' c='isl_poly_drop'/>
<use f='llvm/polly/lib/External/isl/isl_polynomial.c' l='3241' u='r' c='isl_poly_eval'/>
<use f='llvm/polly/lib/External/isl/isl_polynomial.c' l='3246' u='r' c='isl_poly_eval'/>
<use f='llvm/polly/lib/External/isl/isl_polynomial.c' l='3679' u='r' c='isl_poly_degree'/>
<use f='llvm/polly/lib/External/isl/isl_polynomial.c' l='3684' u='r' c='isl_poly_degree'/>
<use f='llvm/polly/lib/External/isl/isl_polynomial.c' l='3734' u='r' c='isl_poly_coeff'/>
<use f='llvm/polly/lib/External/isl/isl_polynomial.c' l='3747' u='r' c='isl_poly_coeff'/>
<use f='llvm/polly/lib/External/isl/isl_polynomial.c' l='3750' u='r' c='isl_poly_coeff'/>
<use f='llvm/polly/lib/External/isl/isl_polynomial.c' l='3751' u='w' c='isl_poly_coeff'/>
<use f='llvm/polly/lib/External/isl/isl_polynomial.c' l='3826' u='w' c='isl_poly_homogenize'/>
<use f='llvm/polly/lib/External/isl/isl_polynomial.c' l='3826' u='r' c='isl_poly_homogenize'/>
<use f='llvm/polly/lib/External/isl/isl_polynomial.c' l='3837' u='r' c='isl_poly_homogenize'/>
<use f='llvm/polly/lib/External/isl/isl_polynomial.c' l='3842' u='w' c='isl_poly_homogenize'/>
<use f='llvm/polly/lib/External/isl/isl_polynomial.c' l='3842' u='r' c='isl_poly_homogenize'/>
<use f='llvm/polly/lib/External/isl/isl_polynomial.c' l='3845' u='r' c='isl_poly_homogenize'/>
<use f='llvm/polly/lib/External/isl/isl_polynomial.c' l='4142' u='r' c='isl_poly_foreach_term'/>
