<dec f='llvm/polly/lib/External/isl/isl_aff_private.h' l='19' type='isl_local_space *'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='74' u='w' c='isl_aff_alloc_vec'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='126' u='r' c='isl_aff_dup'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='289' u='r' c='isl_aff_var_on_domain'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='343' u='r' c='isl_aff_free'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='353' u='r' c='isl_aff_get_ctx'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='366' u='r' c='isl_aff_get_hash'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='379' u='r' c='isl_aff_peek_domain_local_space'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='430' u='r' c='isl_aff_find_dim_by_name'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='437' u='r' c='isl_aff_peek_domain_space'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='450' u='r' c='isl_aff_get_space'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='469' u='r' c='isl_aff_get_local_space'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='493' u='r' c='isl_aff_take_domain_local_space'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='494' u='w' c='isl_aff_take_domain_local_space'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='510' u='r' c='isl_aff_restore_domain_local_space'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='518' u='r' c='isl_aff_restore_domain_local_space'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='519' u='w' c='isl_aff_restore_domain_local_space'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='540' u='r' c='isl_aff_get_dim_name'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='550' u='w' c='isl_aff_reset_domain_space'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='550' u='r' c='isl_aff_reset_domain_space'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='551' u='r' c='isl_aff_reset_domain_space'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='619' u='r' c='isl_aff_realign_domain'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='621' u='r' c='isl_aff_realign_domain'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='622' u='w' c='isl_aff_realign_domain'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='622' u='r' c='isl_aff_realign_domain'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='624' u='r' c='isl_aff_realign_domain'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='642' u='r' c='isl_aff_align_params'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='648' u='r' c='isl_aff_align_params'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='708' u='r' c='isl_aff_plain_is_equal'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='708' u='r' c='isl_aff_plain_is_equal'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='782' u='r' c='isl_aff_get_coefficient_val'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='787' u='r' c='isl_aff_get_coefficient_val'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='811' u='r' c='isl_aff_coefficient_sgn'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='814' u='r' c='isl_aff_coefficient_sgn'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='1110' u='r' c='isl_aff_set_coefficient'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='1123' u='r' c='isl_aff_set_coefficient'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='1147' u='r' c='isl_aff_set_coefficient_si'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='1152' u='r' c='isl_aff_set_coefficient_si'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='1187' u='r' c='isl_aff_set_coefficient_val'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='1198' u='r' c='isl_aff_set_coefficient_val'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='1252' u='r' c='isl_aff_add_coefficient'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='1265' u='r' c='isl_aff_add_coefficient'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='1294' u='r' c='isl_aff_add_coefficient_val'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='1313' u='r' c='isl_aff_add_coefficient_val'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='1357' u='r' c='isl_aff_get_div'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='1408' u='w' c='isl_aff_remove_unused_divs'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='1408' u='r' c='isl_aff_remove_unused_divs'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='1410' u='r' c='isl_aff_remove_unused_divs'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='1436' u='r' c='plug_in_integral_divs'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='1438' u='r' c='plug_in_integral_divs'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='1440' u='r' c='plug_in_integral_divs'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='1448' u='r' c='plug_in_integral_divs'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='1455' u='r' c='plug_in_integral_divs'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='1456' u='w' c='plug_in_integral_divs'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='1497' u='r' c='plug_in_unit_divs'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='1499' u='w' c='plug_in_unit_divs'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='1499' u='r' c='plug_in_unit_divs'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='1500' u='r' c='plug_in_unit_divs'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='1502' u='r' c='plug_in_unit_divs'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='1524' u='r' c='swap_div'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='1534' u='r' c='swap_div'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='1535' u='w' c='swap_div'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='1589' u='r' c='sort_divs'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='1680' u='w' c='isl_aff_floor'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='1680' u='r' c='isl_aff_floor'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='1681' u='r' c='isl_aff_floor'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='1823' u='w' c='isl_aff_expand_divs'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='1823' u='r' c='isl_aff_expand_divs'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='1824' u='r' c='isl_aff_expand_divs'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='1895' u='r' c='isl_aff_add'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='1895' u='r' c='isl_aff_add'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='1920' u='r' c='isl_aff_add'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='1920' u='r' c='isl_aff_add'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='2104' u='w' c='isl_aff_set_dim_name'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='2104' u='r' c='isl_aff_set_dim_name'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='2105' u='r' c='isl_aff_set_dim_name'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='2123' u='w' c='isl_aff_set_dim_id'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='2123' u='r' c='isl_aff_set_dim_id'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='2124' u='r' c='isl_aff_set_dim_id'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='2146' u='w' c='isl_aff_set_tuple_id'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='2146' u='r' c='isl_aff_set_tuple_id'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='2147' u='r' c='isl_aff_set_tuple_id'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='2180' u='w' c='isl_aff_substitute_equalities_lifted'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='2180' u='r' c='isl_aff_substitute_equalities_lifted'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='2183' u='r' c='isl_aff_substitute_equalities_lifted'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='2536' u='r' c='isl_aff_involves_dims'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='2540' u='r' c='isl_aff_involves_dims'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='2580' u='r' c='isl_aff_drop_dims'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='2584' u='r' c='isl_aff_drop_dims'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='2591' u='w' c='isl_aff_drop_dims'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='2591' u='r' c='isl_aff_drop_dims'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='2592' u='r' c='isl_aff_drop_dims'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='2595' u='r' c='isl_aff_drop_dims'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='2659' u='r' c='isl_aff_insert_dims'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='2663' u='r' c='isl_aff_insert_dims'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='2670' u='w' c='isl_aff_insert_dims'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='2670' u='r' c='isl_aff_insert_dims'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='2671' u='r' c='isl_aff_insert_dims'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='2674' u='r' c='isl_aff_insert_dims'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='2710' u='r' c='isl_aff_move_dims'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='2711' u='r' c='isl_aff_move_dims'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='2726' u='r' c='isl_aff_move_dims'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='2745' u='w' c='isl_aff_move_dims'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='2745' u='r' c='isl_aff_move_dims'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='2747' u='r' c='isl_aff_move_dims'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='5573' u='r' c='isl_aff_substitute'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='5573' u='r' c='isl_aff_substitute'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='5583' u='w' c='isl_aff_substitute'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='5583' u='r' c='isl_aff_substitute'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='5584' u='r' c='isl_aff_substitute'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='5591' u='r' c='isl_aff_substitute'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='5934' u='r' c='isl_aff_align_divs'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='5934' u='r' c='isl_aff_align_divs'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='5945' u='r' c='isl_aff_align_divs'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='5945' u='r' c='isl_aff_align_divs'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='5956' u='r' c='isl_aff_align_divs'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='5956' u='r' c='isl_aff_align_divs'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='6001' u='w' c='isl_aff_lift'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='6001' u='r' c='isl_aff_lift'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='6002' u='r' c='isl_aff_lift'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='7196' u='r' c='isl_multi_pw_aff_apply_aff'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='7563' u='r' c='isl_aff_plain_cmp'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='7563' u='r' c='isl_aff_plain_cmp'/>
<offset>64</offset>
<use f='llvm/polly/lib/External/isl/isl_ilp.c' l='375' u='r' c='isl_basic_set_opt'/>
<use f='llvm/polly/lib/External/isl/isl_ilp.c' l='399' u='r' c='isl_basic_set_opt'/>
<use f='llvm/polly/lib/External/isl/isl_ilp.c' l='480' u='r' c='isl_set_opt'/>
<use f='llvm/polly/lib/External/isl/isl_local_space.c' l='1182' u='r' c='isl_local_space_substitute'/>
<use f='llvm/polly/lib/External/isl/isl_local_space.c' l='1185' u='r' c='isl_local_space_substitute'/>
<use f='llvm/polly/lib/External/isl/isl_local_space.c' l='1508' u='r' c='isl_local_space_preimage_multi_aff'/>
<use f='llvm/polly/lib/External/isl/isl_lp.c' l='271' u='r' c='isl_basic_set_opt_lp_val_aligned'/>
<use f='llvm/polly/lib/External/isl/isl_lp.c' l='291' u='r' c='isl_basic_set_opt_lp_val_aligned'/>
<use f='llvm/polly/lib/External/isl/isl_lp.c' l='332' u='r' c='isl_basic_set_opt_lp_val'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='13445' u='r' c='isl_basic_set_substitute'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='13448' u='r' c='isl_basic_set_substitute'/>
<use f='llvm/polly/lib/External/isl/isl_output.c' l='2647' u='r' c='last_modulo'/>
<use f='llvm/polly/lib/External/isl/isl_output.c' l='2665' u='r' c='print_aff_num_base'/>
<use f='llvm/polly/lib/External/isl/isl_output.c' l='2814' u='r' c='print_aff'/>
<use f='llvm/polly/lib/External/isl/isl_output.c' l='2817' u='r' c='print_aff'/>
<use f='llvm/polly/lib/External/isl/isl_output.c' l='2821' u='r' c='print_aff'/>
<use f='llvm/polly/lib/External/isl/isl_output.c' l='2835' u='r' c='print_aff_isl'/>
<use f='llvm/polly/lib/External/isl/isl_output.c' l='2982' u='r' c='print_aff_c'/>
<use f='llvm/polly/lib/External/isl/isl_polynomial.c' l='3509' u='r' c='isl_qpolynomial_from_aff'/>
<use f='llvm/polly/lib/External/isl/isl_polynomial.c' l='3514' u='r' c='isl_qpolynomial_from_aff'/>
