<dec f='llvm/polly/lib/External/isl/include/isl/arg.h' l='77' type='struct (anonymous struct at /fast/tmp/llvm-proj-12/polly/lib/External/isl/include/isl/arg.h:74:2)'/>
<offset>0</offset>
<use f='llvm/polly/lib/External/isl/isl_arg.c' l='19' macro='1' u='w'/>
<use f='llvm/polly/lib/External/isl/isl_arg.c' l='39' u='m' c='set_default_bool'/>
<use f='llvm/polly/lib/External/isl/isl_arg.c' l='910' u='m' c='parse_bool_option'/>
<use f='llvm/polly/lib/External/isl/isl_arg.c' l='911' u='m' c='parse_bool_option'/>
<use f='llvm/polly/lib/External/isl/isl_arg.c' l='917' u='m' c='parse_bool_option'/>
<use f='llvm/polly/lib/External/isl/isl_arg.c' l='918' u='m' c='parse_bool_option'/>
<use f='llvm/polly/lib/External/isl/isl_arg.c' l='942' u='m' c='parse_bool_option'/>
<use f='llvm/polly/lib/External/isl/isl_arg.c' l='943' u='m' c='parse_bool_option'/>
<use f='llvm/polly/lib/External/isl/isl_options.c' l='120' macro='1' u='w'/>
<use f='llvm/polly/lib/External/isl/isl_options.c' l='128' macro='1' u='w'/>
<use f='llvm/polly/lib/External/isl/isl_options.c' l='131' macro='1' u='w'/>
<use f='llvm/polly/lib/External/isl/isl_options.c' l='135' macro='1' u='w'/>
<use f='llvm/polly/lib/External/isl/isl_options.c' l='137' macro='1' u='w'/>
<use f='llvm/polly/lib/External/isl/isl_options.c' l='148' macro='1' u='w'/>
<use f='llvm/polly/lib/External/isl/isl_options.c' l='150' macro='1' u='w'/>
<use f='llvm/polly/lib/External/isl/isl_options.c' l='154' macro='1' u='w'/>
<use f='llvm/polly/lib/External/isl/isl_options.c' l='157' macro='1' u='w'/>
<use f='llvm/polly/lib/External/isl/isl_options.c' l='160' macro='1' u='w'/>
<use f='llvm/polly/lib/External/isl/isl_options.c' l='163' macro='1' u='w'/>
<use f='llvm/polly/lib/External/isl/isl_options.c' l='166' macro='1' u='w'/>
<use f='llvm/polly/lib/External/isl/isl_options.c' l='169' macro='1' u='w'/>
<use f='llvm/polly/lib/External/isl/isl_options.c' l='175' macro='1' u='w'/>
<use f='llvm/polly/lib/External/isl/isl_options.c' l='177' macro='1' u='w'/>
<use f='llvm/polly/lib/External/isl/isl_options.c' l='183' macro='1' u='w'/>
<use f='llvm/polly/lib/External/isl/isl_options.c' l='185' macro='1' u='w'/>
<use f='llvm/polly/lib/External/isl/isl_options.c' l='190' macro='1' u='w'/>
<use f='llvm/polly/lib/External/isl/isl_options.c' l='193' macro='1' u='w'/>
<use f='llvm/polly/lib/External/isl/isl_options.c' l='195' macro='1' u='w'/>
<use f='llvm/polly/lib/External/isl/isl_options.c' l='197' macro='1' u='w'/>
<use f='llvm/polly/lib/External/isl/isl_options.c' l='199' macro='1' u='w'/>
<use f='llvm/polly/lib/External/isl/isl_options.c' l='201' macro='1' u='w'/>
<use f='llvm/polly/lib/External/isl/isl_options.c' l='203' macro='1' u='w'/>
<use f='llvm/polly/lib/External/isl/isl_options.c' l='206' macro='1' u='w'/>
<use f='llvm/polly/lib/External/isl/isl_options.c' l='213' macro='1' u='w'/>
<use f='llvm/polly/lib/External/isl/isl_options.c' l='216' macro='1' u='w'/>
<use f='llvm/polly/lib/External/isl/isl_options.c' l='218' macro='1' u='w'/>
<use f='llvm/polly/lib/External/isl/isl_options.c' l='220' macro='1' u='w'/>
<use f='llvm/polly/lib/External/ppcg/ppcg_options.c' l='51' macro='1' u='w'/>
<use f='llvm/polly/lib/External/ppcg/ppcg_options.c' l='53' macro='1' u='w'/>
<use f='llvm/polly/lib/External/ppcg/ppcg_options.c' l='55' macro='1' u='w'/>
<use f='llvm/polly/lib/External/ppcg/ppcg_options.c' l='57' macro='1' u='w'/>
<use f='llvm/polly/lib/External/ppcg/ppcg_options.c' l='60' macro='1' u='w'/>
<use f='llvm/polly/lib/External/ppcg/ppcg_options.c' l='66' macro='1' u='w'/>
<use f='llvm/polly/lib/External/ppcg/ppcg_options.c' l='71' macro='1' u='w'/>
<use f='llvm/polly/lib/External/ppcg/ppcg_options.c' l='74' macro='1' u='w'/>
<use f='llvm/polly/lib/External/ppcg/ppcg_options.c' l='82' macro='1' u='w'/>
<use f='llvm/polly/lib/External/ppcg/ppcg_options.c' l='85' macro='1' u='w'/>
<use f='llvm/polly/lib/External/ppcg/ppcg_options.c' l='87' macro='1' u='w'/>
<use f='llvm/polly/lib/External/ppcg/ppcg_options.c' l='89' macro='1' u='w'/>
<use f='llvm/polly/lib/External/ppcg/ppcg_options.c' l='90' macro='1' u='w'/>
<use f='llvm/polly/lib/External/ppcg/ppcg_options.c' l='92' macro='1' u='w'/>
<use f='llvm/polly/lib/External/ppcg/ppcg_options.c' l='96' macro='1' u='w'/>
<use f='llvm/polly/lib/External/ppcg/ppcg_options.c' l='99' macro='1' u='w'/>
<use f='llvm/polly/lib/External/ppcg/ppcg_options.c' l='102' macro='1' u='w'/>
<use f='llvm/polly/lib/External/ppcg/ppcg_options.c' l='108' macro='1' u='w'/>
<use f='llvm/polly/lib/External/ppcg/ppcg_options.c' l='113' macro='1' u='w'/>
<use f='llvm/polly/lib/External/ppcg/ppcg_options.c' l='116' macro='1' u='w'/>
<use f='llvm/polly/lib/External/ppcg/ppcg_options.c' l='119' macro='1' u='w'/>
<use f='llvm/polly/lib/External/ppcg/ppcg_options.c' l='123' macro='1' u='w'/>
<use f='llvm/polly/lib/External/ppcg/ppcg_options.c' l='126' macro='1' u='w'/>
<use f='llvm/polly/lib/External/ppcg/ppcg_options.c' l='128' macro='1' u='w'/>
