<dec f='llvm/polly/lib/External/isl/isl_ast_private.h' l='72' type='isl_ast_expr *'/>
<use f='llvm/polly/lib/External/isl/isl_ast.c' l='1043' u='w' c='isl_ast_node_dup'/>
<use f='llvm/polly/lib/External/isl/isl_ast.c' l='1043' u='r' c='isl_ast_node_dup'/>
<use f='llvm/polly/lib/External/isl/isl_ast.c' l='1047' u='r' c='isl_ast_node_dup'/>
<use f='llvm/polly/lib/External/isl/isl_ast.c' l='1101' u='r' c='isl_ast_node_free'/>
<use f='llvm/polly/lib/External/isl/isl_ast.c' l='1201' u='r' c='isl_ast_node_for_get_init'/>
<use f='llvm/polly/lib/External/isl/isl_ast.c' l='1224' u='r' c='isl_ast_node_for_get_cond'/>
<use f='llvm/polly/lib/External/isl/isl_ast.c' l='2158' u='r' c='print_ast_node_isl'/>
<use f='llvm/polly/lib/External/isl/isl_ast.c' l='2163' u='r' c='print_ast_node_isl'/>
<use f='llvm/polly/lib/External/isl/isl_ast.c' l='2386' u='r' c='print_for_c'/>
<use f='llvm/polly/lib/External/isl/isl_ast.c' l='2406' u='r' c='print_for_c'/>
<use f='llvm/polly/lib/External/isl/isl_ast.c' l='2652' u='r' c='ast_node_required_macros'/>
<offset>128</offset>
<use f='llvm/polly/lib/External/isl/isl_ast_codegen.c' l='800' u='w' c='refine_degenerate'/>
<use f='llvm/polly/lib/External/isl/isl_ast_codegen.c' l='802' u='r' c='refine_degenerate'/>
<use f='llvm/polly/lib/External/isl/isl_ast_codegen.c' l='1128' u='w' c='set_for_node_expressions'/>
<use f='llvm/polly/lib/External/isl/isl_ast_codegen.c' l='1131' u='r' c='set_for_node_expressions'/>
