<dec f='llvm/polly/lib/External/isl/isl_ast_private.h' l='76' type='struct (anonymous struct at /fast/tmp/llvm-proj-12/polly/lib/External/isl/isl_ast_private.h:69:3)'/>
<use f='llvm/polly/lib/External/isl/isl_ast.c' l='904' u='m' c='isl_ast_node_alloc_for'/>
<use f='llvm/polly/lib/External/isl/isl_ast.c' l='905' u='m' c='isl_ast_node_alloc_for'/>
<use f='llvm/polly/lib/External/isl/isl_ast.c' l='1042' u='m' c='isl_ast_node_dup'/>
<use f='llvm/polly/lib/External/isl/isl_ast.c' l='1042' u='m' c='isl_ast_node_dup'/>
<use f='llvm/polly/lib/External/isl/isl_ast.c' l='1043' u='m' c='isl_ast_node_dup'/>
<use f='llvm/polly/lib/External/isl/isl_ast.c' l='1043' u='m' c='isl_ast_node_dup'/>
<use f='llvm/polly/lib/External/isl/isl_ast.c' l='1044' u='m' c='isl_ast_node_dup'/>
<use f='llvm/polly/lib/External/isl/isl_ast.c' l='1044' u='m' c='isl_ast_node_dup'/>
<use f='llvm/polly/lib/External/isl/isl_ast.c' l='1045' u='m' c='isl_ast_node_dup'/>
<use f='llvm/polly/lib/External/isl/isl_ast.c' l='1045' u='m' c='isl_ast_node_dup'/>
<use f='llvm/polly/lib/External/isl/isl_ast.c' l='1046' u='m' c='isl_ast_node_dup'/>
<use f='llvm/polly/lib/External/isl/isl_ast.c' l='1046' u='m' c='isl_ast_node_dup'/>
<use f='llvm/polly/lib/External/isl/isl_ast.c' l='1047' u='m' c='isl_ast_node_dup'/>
<use f='llvm/polly/lib/External/isl/isl_ast.c' l='1047' u='m' c='isl_ast_node_dup'/>
<use f='llvm/polly/lib/External/isl/isl_ast.c' l='1047' u='m' c='isl_ast_node_dup'/>
<use f='llvm/polly/lib/External/isl/isl_ast.c' l='1048' u='m' c='isl_ast_node_dup'/>
<use f='llvm/polly/lib/External/isl/isl_ast.c' l='1048' u='m' c='isl_ast_node_dup'/>
<use f='llvm/polly/lib/External/isl/isl_ast.c' l='1100' u='m' c='isl_ast_node_free'/>
<use f='llvm/polly/lib/External/isl/isl_ast.c' l='1101' u='m' c='isl_ast_node_free'/>
<use f='llvm/polly/lib/External/isl/isl_ast.c' l='1102' u='m' c='isl_ast_node_free'/>
<use f='llvm/polly/lib/External/isl/isl_ast.c' l='1103' u='m' c='isl_ast_node_free'/>
<use f='llvm/polly/lib/External/isl/isl_ast.c' l='1104' u='m' c='isl_ast_node_free'/>
<use f='llvm/polly/lib/External/isl/isl_ast.c' l='1139' u='m' c='isl_ast_node_for_set_body'/>
<use f='llvm/polly/lib/External/isl/isl_ast.c' l='1140' u='m' c='isl_ast_node_for_set_body'/>
<use f='llvm/polly/lib/External/isl/isl_ast.c' l='1157' u='m' c='isl_ast_node_for_get_body'/>
<use f='llvm/polly/lib/External/isl/isl_ast.c' l='1168' u='m' c='isl_ast_node_for_mark_degenerate'/>
<use f='llvm/polly/lib/External/isl/isl_ast.c' l='1179' u='m' c='isl_ast_node_for_is_degenerate'/>
<use f='llvm/polly/lib/External/isl/isl_ast.c' l='1190' u='m' c='isl_ast_node_for_get_iterator'/>
<use f='llvm/polly/lib/External/isl/isl_ast.c' l='1201' u='m' c='isl_ast_node_for_get_init'/>
<use f='llvm/polly/lib/External/isl/isl_ast.c' l='1219' u='m' c='isl_ast_node_for_get_cond'/>
<use f='llvm/polly/lib/External/isl/isl_ast.c' l='1220' u='m' c='isl_ast_node_for_get_cond'/>
<use f='llvm/polly/lib/External/isl/isl_ast.c' l='1223' u='m' c='isl_ast_node_for_get_cond'/>
<use f='llvm/polly/lib/External/isl/isl_ast.c' l='1224' u='m' c='isl_ast_node_for_get_cond'/>
<use f='llvm/polly/lib/External/isl/isl_ast.c' l='1240' u='m' c='isl_ast_node_for_get_inc'/>
<use f='llvm/polly/lib/External/isl/isl_ast.c' l='1241' u='m' c='isl_ast_node_for_get_inc'/>
<use f='llvm/polly/lib/External/isl/isl_ast.c' l='1466' u='m' c='isl_ast_node_foreach_descendant_top_down'/>
<use f='llvm/polly/lib/External/isl/isl_ast.c' l='2153' u='m' c='print_ast_node_isl'/>
<use f='llvm/polly/lib/External/isl/isl_ast.c' l='2155' u='m' c='print_ast_node_isl'/>
<use f='llvm/polly/lib/External/isl/isl_ast.c' l='2158' u='m' c='print_ast_node_isl'/>
<use f='llvm/polly/lib/External/isl/isl_ast.c' l='2163' u='m' c='print_ast_node_isl'/>
<use f='llvm/polly/lib/External/isl/isl_ast.c' l='2167' u='m' c='print_ast_node_isl'/>
<use f='llvm/polly/lib/External/isl/isl_ast.c' l='2171' u='m' c='print_ast_node_isl'/>
<use f='llvm/polly/lib/External/isl/isl_ast.c' l='2174' u='m' c='print_ast_node_isl'/>
<use f='llvm/polly/lib/External/isl/isl_ast.c' l='2177' u='m' c='print_ast_node_isl'/>
<use f='llvm/polly/lib/External/isl/isl_ast.c' l='2248' u='m' c='need_block'/>
<use f='llvm/polly/lib/External/isl/isl_ast.c' l='2376' u='m' c='print_for_c'/>
<use f='llvm/polly/lib/External/isl/isl_ast.c' l='2377' u='m' c='print_for_c'/>
<use f='llvm/polly/lib/External/isl/isl_ast.c' l='2386' u='m' c='print_for_c'/>
<use f='llvm/polly/lib/External/isl/isl_ast.c' l='2388' u='m' c='print_for_c'/>
<use f='llvm/polly/lib/External/isl/isl_ast.c' l='2392' u='m' c='print_for_c'/>
<use f='llvm/polly/lib/External/isl/isl_ast.c' l='2394' u='m' c='print_for_c'/>
<use f='llvm/polly/lib/External/isl/isl_ast.c' l='2396' u='m' c='print_for_c'/>
<use f='llvm/polly/lib/External/isl/isl_ast.c' l='2406' u='m' c='print_for_c'/>
<use f='llvm/polly/lib/External/isl/isl_ast.c' l='2409' u='m' c='print_for_c'/>
<use f='llvm/polly/lib/External/isl/isl_ast.c' l='2652' u='m' c='ast_node_required_macros'/>
<use f='llvm/polly/lib/External/isl/isl_ast.c' l='2653' u='m' c='ast_node_required_macros'/>
<use f='llvm/polly/lib/External/isl/isl_ast.c' l='2654' u='m' c='ast_node_required_macros'/>
<use f='llvm/polly/lib/External/isl/isl_ast.c' l='2656' u='m' c='ast_node_required_macros'/>
<use f='llvm/polly/lib/External/isl/isl_ast.c' l='2659' u='m' c='ast_node_required_macros'/>
<offset>0</offset>
<use f='llvm/polly/lib/External/isl/isl_ast_codegen.c' l='800' u='m' c='refine_degenerate'/>
<use f='llvm/polly/lib/External/isl/isl_ast_codegen.c' l='802' u='m' c='refine_degenerate'/>
<use f='llvm/polly/lib/External/isl/isl_ast_codegen.c' l='1029' u='m' c='set_for_cond_from_list'/>
<use f='llvm/polly/lib/External/isl/isl_ast_codegen.c' l='1031' u='m' c='set_for_cond_from_list'/>
<use f='llvm/polly/lib/External/isl/isl_ast_codegen.c' l='1034' u='m' c='set_for_cond_from_list'/>
<use f='llvm/polly/lib/External/isl/isl_ast_codegen.c' l='1052' u='m' c='set_for_cond_from_set'/>
<use f='llvm/polly/lib/External/isl/isl_ast_codegen.c' l='1053' u='m' c='set_for_cond_from_set'/>
<use f='llvm/polly/lib/External/isl/isl_ast_codegen.c' l='1128' u='m' c='set_for_node_expressions'/>
<use f='llvm/polly/lib/External/isl/isl_ast_codegen.c' l='1129' u='m' c='set_for_node_expressions'/>
<use f='llvm/polly/lib/External/isl/isl_ast_codegen.c' l='1131' u='m' c='set_for_node_expressions'/>
<use f='llvm/polly/lib/External/isl/isl_ast_codegen.c' l='1131' u='m' c='set_for_node_expressions'/>
