<use f='llvm/polly/lib/External/isl/isl_list_templ.c' l='72' u='r' c='isl_union_pw_multi_aff_list_dup'/>
<use f='llvm/polly/lib/External/isl/isl_list_templ.c' l='123' u='r' c='isl_union_pw_multi_aff_list_grow'/>
<use f='llvm/polly/lib/External/isl/isl_list_templ.c' l='147' u='w' c='isl_union_pw_multi_aff_list_add'/>
<use f='llvm/polly/lib/External/isl/isl_list_templ.c' l='174' u='r' c='isl_union_pw_multi_aff_list_drop'/>
<use f='llvm/polly/lib/External/isl/isl_list_templ.c' l='176' u='w' c='isl_union_pw_multi_aff_list_drop'/>
<use f='llvm/polly/lib/External/isl/isl_list_templ.c' l='176' u='r' c='isl_union_pw_multi_aff_list_drop'/>
<use f='llvm/polly/lib/External/isl/isl_list_templ.c' l='213' u='w' c='isl_union_pw_multi_aff_list_insert'/>
<use f='llvm/polly/lib/External/isl/isl_list_templ.c' l='213' u='r' c='isl_union_pw_multi_aff_list_insert'/>
<use f='llvm/polly/lib/External/isl/isl_list_templ.c' l='215' u='w' c='isl_union_pw_multi_aff_list_insert'/>
<use f='llvm/polly/lib/External/isl/isl_list_templ.c' l='221' u='r' c='isl_union_pw_multi_aff_list_insert'/>
<use f='llvm/polly/lib/External/isl/isl_list_templ.c' l='224' u='r' c='isl_union_pw_multi_aff_list_insert'/>
<use f='llvm/polly/lib/External/isl/isl_list_templ.c' l='246' u='r' c='isl_union_pw_multi_aff_list_free'/>
<use f='llvm/polly/lib/External/isl/isl_list_templ.c' l='272' u='r' c='isl_union_pw_multi_aff_list_peek'/>
<use f='llvm/polly/lib/External/isl/isl_list_templ.c' l='299' u='r' c='isl_union_pw_multi_aff_list_set_union_pw_multi_aff'/>
<use f='llvm/polly/lib/External/isl/isl_list_templ.c' l='306' u='r' c='isl_union_pw_multi_aff_list_set_union_pw_multi_aff'/>
<use f='llvm/polly/lib/External/isl/isl_list_templ.c' l='307' u='w' c='isl_union_pw_multi_aff_list_set_union_pw_multi_aff'/>
<use f='llvm/polly/lib/External/isl/isl_list_templ.c' l='334' u='r' c='isl_union_pw_multi_aff_list_take_union_pw_multi_aff'/>
<use f='llvm/polly/lib/External/isl/isl_list_templ.c' l='335' u='w' c='isl_union_pw_multi_aff_list_take_union_pw_multi_aff'/>
<use f='llvm/polly/lib/External/isl/isl_list_templ.c' l='386' u='r' c='isl_union_pw_multi_aff_list_foreach'/>
<use f='llvm/polly/lib/External/isl/isl_list_templ.c' l='409' u='r' c='isl_union_pw_multi_aff_list_every'/>
<use f='llvm/polly/lib/External/isl/isl_list_templ.c' l='478' u='r' c='isl_union_pw_multi_aff_list_sort'/>
<use f='llvm/polly/lib/External/isl/isl_list_templ.c' l='478' u='r' c='isl_union_pw_multi_aff_list_sort'/>
<use f='llvm/polly/lib/External/isl/isl_list_templ.c' l='504' u='r' c='isl_union_pw_multi_aff_list_follows'/>
<use f='llvm/polly/lib/External/isl/isl_list_templ.c' l='504' u='r' c='isl_union_pw_multi_aff_list_follows'/>
<use f='llvm/polly/lib/External/isl/isl_list_templ.c' l='523' u='r' c='isl_union_pw_multi_aff_list_call_on_scc'/>
<use f='llvm/polly/lib/External/isl/isl_list_templ.c' l='619' u='r' c='isl_union_pw_multi_aff_list_concat_inplace'/>
<use f='llvm/polly/lib/External/isl/isl_list_templ.c' l='645' u='r' c='isl_union_pw_multi_aff_list_concat'/>
<use f='llvm/polly/lib/External/isl/isl_list_templ.c' l='647' u='r' c='isl_union_pw_multi_aff_list_concat'/>
<use f='llvm/polly/lib/External/isl/isl_list_templ.c' l='669' u='r' c='isl_printer_print_union_pw_multi_aff_list'/>
