<dec f='llvm/polly/lib/External/isl/include/isl/obj.h' l='50' type='void *'/>
<offset>64</offset>
<use f='llvm/polly/lib/External/isl/isl_input.c' l='2595' u='w' c='obj_read_poly'/>
<use f='llvm/polly/lib/External/isl/isl_input.c' l='2635' u='w' c='obj_read_poly_or_fold'/>
<use f='llvm/polly/lib/External/isl/isl_input.c' l='2676' u='w' c='obj_read_body'/>
<use f='llvm/polly/lib/External/isl/isl_input.c' l='2708' u='w' c='obj_read_body'/>
<use f='llvm/polly/lib/External/isl/isl_input.c' l='2719' u='w' c='to_union'/>
<use f='llvm/polly/lib/External/isl/isl_input.c' l='2719' u='r' c='to_union'/>
<use f='llvm/polly/lib/External/isl/isl_input.c' l='2722' u='w' c='to_union'/>
<use f='llvm/polly/lib/External/isl/isl_input.c' l='2722' u='r' c='to_union'/>
<use f='llvm/polly/lib/External/isl/isl_input.c' l='2725' u='w' c='to_union'/>
<use f='llvm/polly/lib/External/isl/isl_input.c' l='2725' u='r' c='to_union'/>
<use f='llvm/polly/lib/External/isl/isl_input.c' l='2728' u='w' c='to_union'/>
<use f='llvm/polly/lib/External/isl/isl_input.c' l='2728' u='r' c='to_union'/>
<use f='llvm/polly/lib/External/isl/isl_input.c' l='2734' u='r' c='to_union'/>
<use f='llvm/polly/lib/External/isl/isl_input.c' l='2742' u='r' c='obj_add'/>
<use f='llvm/polly/lib/External/isl/isl_input.c' l='2772' u='r' c='obj_add'/>
<use f='llvm/polly/lib/External/isl/isl_input.c' l='2772' u='r' c='obj_add'/>
<use f='llvm/polly/lib/External/isl/isl_input.c' l='2776' u='r' c='obj_add'/>
<use f='llvm/polly/lib/External/isl/isl_input.c' l='2776' u='r' c='obj_add'/>
<use f='llvm/polly/lib/External/isl/isl_input.c' l='2781' u='r' c='obj_add'/>
<use f='llvm/polly/lib/External/isl/isl_input.c' l='2781' u='r' c='obj_add'/>
<use f='llvm/polly/lib/External/isl/isl_input.c' l='2786' u='r' c='obj_add'/>
<use f='llvm/polly/lib/External/isl/isl_input.c' l='2786' u='r' c='obj_add'/>
<use f='llvm/polly/lib/External/isl/isl_input.c' l='2790' u='w' c='obj_add'/>
<use f='llvm/polly/lib/External/isl/isl_input.c' l='2790' u='r' c='obj_add'/>
<use f='llvm/polly/lib/External/isl/isl_input.c' l='2790' u='r' c='obj_add'/>
<use f='llvm/polly/lib/External/isl/isl_input.c' l='2793' u='r' c='obj_add'/>
<use f='llvm/polly/lib/External/isl/isl_input.c' l='2794' u='r' c='obj_add'/>
<use f='llvm/polly/lib/External/isl/isl_input.c' l='2796' u='w' c='obj_add'/>
<use f='llvm/polly/lib/External/isl/isl_input.c' l='2859' u='w' c='schedule_read'/>
<use f='llvm/polly/lib/External/isl/isl_input.c' l='2876' u='w' c='obj_read_disjuncts'/>
<use f='llvm/polly/lib/External/isl/isl_input.c' l='2883' u='r' c='obj_read_disjuncts'/>
<use f='llvm/polly/lib/External/isl/isl_input.c' l='2887' u='r' c='obj_read_disjuncts'/>
<use f='llvm/polly/lib/External/isl/isl_input.c' l='2923' u='w' c='obj_read'/>
<use f='llvm/polly/lib/External/isl/isl_input.c' l='2933' u='w' c='obj_read'/>
<use f='llvm/polly/lib/External/isl/isl_input.c' l='2936' u='w' c='obj_read'/>
<use f='llvm/polly/lib/External/isl/isl_input.c' l='2983' u='r' c='obj_read'/>
<use f='llvm/polly/lib/External/isl/isl_input.c' l='3002' u='r' c='obj_read'/>
<use f='llvm/polly/lib/External/isl/isl_input.c' l='3005' u='w' c='obj_read'/>
<use f='llvm/polly/lib/External/isl/isl_input.c' l='3019' u='r' c='isl_stream_read_map'/>
<use f='llvm/polly/lib/External/isl/isl_input.c' l='3024' u='w' c='isl_stream_read_map'/>
<use f='llvm/polly/lib/External/isl/isl_input.c' l='3024' u='r' c='isl_stream_read_map'/>
<use f='llvm/polly/lib/External/isl/isl_input.c' l='3026' u='r' c='isl_stream_read_map'/>
<use f='llvm/polly/lib/External/isl/isl_input.c' l='3028' u='r' c='isl_stream_read_map'/>
<use f='llvm/polly/lib/External/isl/isl_input.c' l='3037' u='r' c='isl_stream_read_set'/>
<use f='llvm/polly/lib/External/isl/isl_input.c' l='3038' u='r' c='isl_stream_read_set'/>
<use f='llvm/polly/lib/External/isl/isl_input.c' l='3039' u='w' c='isl_stream_read_set'/>
<use f='llvm/polly/lib/External/isl/isl_input.c' l='3039' u='r' c='isl_stream_read_set'/>
<use f='llvm/polly/lib/External/isl/isl_input.c' l='3045' u='r' c='isl_stream_read_set'/>
<use f='llvm/polly/lib/External/isl/isl_input.c' l='3047' u='r' c='isl_stream_read_set'/>
<use f='llvm/polly/lib/External/isl/isl_input.c' l='3058' u='w' c='isl_stream_read_union_map'/>
<use f='llvm/polly/lib/External/isl/isl_input.c' l='3058' u='r' c='isl_stream_read_union_map'/>
<use f='llvm/polly/lib/External/isl/isl_input.c' l='3062' u='w' c='isl_stream_read_union_map'/>
<use f='llvm/polly/lib/External/isl/isl_input.c' l='3062' u='r' c='isl_stream_read_union_map'/>
<use f='llvm/polly/lib/External/isl/isl_input.c' l='3064' u='r' c='isl_stream_read_union_map'/>
<use f='llvm/polly/lib/External/isl/isl_input.c' l='3065' u='r' c='isl_stream_read_union_map'/>
<use f='llvm/polly/lib/External/isl/isl_input.c' l='3067' u='r' c='isl_stream_read_union_map'/>
<use f='llvm/polly/lib/External/isl/isl_input.c' l='3070' u='r' c='isl_stream_read_union_map'/>
<use f='llvm/polly/lib/External/isl/isl_input.c' l='3072' u='r' c='isl_stream_read_union_map'/>
<use f='llvm/polly/lib/External/isl/isl_input.c' l='3085' u='w' c='extract_union_set'/>
<use f='llvm/polly/lib/External/isl/isl_input.c' l='3085' u='r' c='extract_union_set'/>
<use f='llvm/polly/lib/External/isl/isl_input.c' l='3087' u='r' c='extract_union_set'/>
<use f='llvm/polly/lib/External/isl/isl_input.c' l='3090' u='r' c='extract_union_set'/>
<use f='llvm/polly/lib/External/isl/isl_input.c' l='3092' u='r' c='extract_union_set'/>
<use f='llvm/polly/lib/External/isl/isl_input.c' l='3115' u='r' c='basic_map_read'/>
<use f='llvm/polly/lib/External/isl/isl_input.c' l='3118' u='r' c='basic_map_read'/>
<use f='llvm/polly/lib/External/isl/isl_input.c' l='3136' u='r' c='basic_map_read'/>
<use f='llvm/polly/lib/External/isl/isl_input.c' l='3355' u='r' c='isl_stream_read_pw_qpolynomial'/>
<use f='llvm/polly/lib/External/isl/isl_input.c' l='3359' u='r' c='isl_stream_read_pw_qpolynomial'/>
<use f='llvm/polly/lib/External/isl/isl_input.c' l='3361' u='r' c='isl_stream_read_pw_qpolynomial'/>
<use f='llvm/polly/lib/External/isl/isl_input.c' l='3399' u='r' c='isl_stream_read_pw_qpolynomial_fold'/>
<use f='llvm/polly/lib/External/isl/isl_input.c' l='3402' u='r' c='isl_stream_read_pw_qpolynomial_fold'/>
<use f='llvm/polly/lib/External/isl/isl_input.c' l='3404' u='r' c='isl_stream_read_pw_qpolynomial_fold'/>
<use f='llvm/polly/lib/External/isl/isl_input.c' l='4283' u='r' c='read_union_set_body'/>
<use f='llvm/polly/lib/External/isl/isl_input.c' l='4453' u='w' c='isl_stream_read_union_pw_qpolynomial'/>
<use f='llvm/polly/lib/External/isl/isl_input.c' l='4453' u='r' c='isl_stream_read_union_pw_qpolynomial'/>
<use f='llvm/polly/lib/External/isl/isl_input.c' l='4455' u='r' c='isl_stream_read_union_pw_qpolynomial'/>
<use f='llvm/polly/lib/External/isl/isl_input.c' l='4459' u='r' c='isl_stream_read_union_pw_qpolynomial'/>
<use f='llvm/polly/lib/External/isl/isl_input.c' l='4461' u='r' c='isl_stream_read_union_pw_qpolynomial'/>
<use f='llvm/polly/unittests/Isl/IslTest.cpp' l='25' u='r' c='_ZL10parseSpaceP7isl_ctxPKc'/>
<use f='llvm/polly/unittests/Isl/IslTest.cpp' l='27' u='r' c='_ZL10parseSpaceP7isl_ctxPKc'/>
<use f='llvm/polly/unittests/Isl/IslTest.cpp' l='31' u='r' c='_ZL10parseSpaceP7isl_ctxPKc'/>
