<dec f='llvm/polly/lib/External/isl/isl_constraint_private.h' l='12' type='isl_local_space *'/>
<offset>64</offset>
<use f='llvm/polly/lib/External/isl/isl_constraint.c' l='32' u='r' c='isl_constraint_get_ctx'/>
<use f='llvm/polly/lib/External/isl/isl_constraint.c' l='37' u='r' c='n'/>
<use f='llvm/polly/lib/External/isl/isl_constraint.c' l='42' u='r' c='offset'/>
<use f='llvm/polly/lib/External/isl/isl_constraint.c' l='59' u='w' c='isl_constraint_alloc_vec'/>
<use f='llvm/polly/lib/External/isl/isl_constraint.c' l='145' u='r' c='isl_constraint_dup'/>
<use f='llvm/polly/lib/External/isl/isl_constraint.c' l='178' u='r' c='isl_constraint_free'/>
<use f='llvm/polly/lib/External/isl/isl_constraint.c' l='314' u='r' c='isl_constraint_is_equal'/>
<use f='llvm/polly/lib/External/isl/isl_constraint.c' l='314' u='r' c='isl_constraint_is_equal'/>
<use f='llvm/polly/lib/External/isl/isl_constraint.c' l='374' u='r' c='isl_constraint_peek_space'/>
<use f='llvm/polly/lib/External/isl/isl_constraint.c' l='380' u='r' c='isl_constraint_get_space'/>
<use f='llvm/polly/lib/External/isl/isl_constraint.c' l='386' u='r' c='isl_constraint_get_local_space'/>
<use f='llvm/polly/lib/External/isl/isl_constraint.c' l='417' u='r' c='isl_constraint_involves_dims'/>
<use f='llvm/polly/lib/External/isl/isl_constraint.c' l='422' u='r' c='isl_constraint_involves_dims'/>
<use f='llvm/polly/lib/External/isl/isl_constraint.c' l='446' u='r' c='isl_constraint_is_lower_bound'/>
<use f='llvm/polly/lib/External/isl/isl_constraint.c' l='459' u='r' c='isl_constraint_is_upper_bound'/>
<use f='llvm/polly/lib/External/isl/isl_constraint.c' l='467' u='r' c='isl_constraint_get_dim_name'/>
<use f='llvm/polly/lib/External/isl/isl_constraint.c' l='498' u='r' c='isl_constraint_get_coefficient'/>
<use f='llvm/polly/lib/External/isl/isl_constraint.c' l='514' u='r' c='isl_constraint_get_coefficient_val'/>
<use f='llvm/polly/lib/External/isl/isl_constraint.c' l='524' u='r' c='isl_constraint_get_div'/>
<use f='llvm/polly/lib/External/isl/isl_constraint.c' l='589' u='r' c='isl_constraint_set_coefficient'/>
<use f='llvm/polly/lib/External/isl/isl_constraint.c' l='611' u='r' c='isl_constraint_set_coefficient_val'/>
<use f='llvm/polly/lib/External/isl/isl_constraint.c' l='633' u='r' c='isl_constraint_set_coefficient_si'/>
<use f='llvm/polly/lib/External/isl/isl_constraint.c' l='681' u='r' c='isl_constraint_is_div_constraint'/>
<use f='llvm/polly/lib/External/isl/isl_constraint.c' l='712' u='r' c='isl_constraint_is_div_equality'/>
<use f='llvm/polly/lib/External/isl/isl_constraint.c' l='733' u='r' c='isl_basic_map_from_constraint'/>
<use f='llvm/polly/lib/External/isl/isl_constraint.c' l='1244' u='r' c='isl_constraint_get_bound'/>
<use f='llvm/polly/lib/External/isl/isl_constraint.c' l='1277' u='r' c='isl_constraint_get_aff'/>
<use f='llvm/polly/lib/External/isl/isl_constraint.c' l='1343' u='r' c='isl_constraint_plain_cmp'/>
<use f='llvm/polly/lib/External/isl/isl_constraint.c' l='1343' u='r' c='isl_constraint_plain_cmp'/>
<use f='llvm/polly/lib/External/isl/isl_constraint.c' l='1378' u='r' c='isl_constraint_cmp_last_non_zero'/>
<use f='llvm/polly/lib/External/isl/isl_constraint.c' l='1378' u='r' c='isl_constraint_cmp_last_non_zero'/>
