<dec f='llvm/polly/lib/External/isl/isl_vec_private.h' l='13' type='isl_int *'/>
<use f='llvm/polly/lib/External/isl/basis_reduction_templ.c' l='193' u='r' c='isl_tab_compute_reduced_basis'/>
<use f='llvm/polly/lib/External/isl/basis_reduction_templ.c' l='196' u='r' c='isl_tab_compute_reduced_basis'/>
<use f='llvm/polly/lib/External/isl/basis_reduction_tab.c' l='186' u='r' c='solve_lp'/>
<use f='llvm/polly/lib/External/isl/basis_reduction_tab.c' l='187' u='r' c='solve_lp'/>
<use f='llvm/polly/lib/External/isl/basis_reduction_tab.c' l='188' u='r' c='solve_lp'/>
<use f='llvm/polly/lib/External/isl/basis_reduction_tab.c' l='191' u='r' c='solve_lp'/>
<use f='llvm/polly/lib/External/isl/basis_reduction_tab.c' l='198' u='r' c='solve_lp'/>
<use f='llvm/polly/lib/External/isl/basis_reduction_tab.c' l='199' u='r' c='solve_lp'/>
<use f='llvm/polly/lib/External/isl/basis_reduction_tab.c' l='200' u='r' c='solve_lp'/>
<use f='llvm/polly/lib/External/isl/basis_reduction_tab.c' l='201' u='r' c='solve_lp'/>
<use f='llvm/polly/lib/External/isl/basis_reduction_tab.c' l='224' u='r' c='cut_lp_to_hyperplane'/>
<use f='llvm/polly/lib/External/isl/basis_reduction_tab.c' l='225' u='r' c='cut_lp_to_hyperplane'/>
<use f='llvm/polly/lib/External/isl/basis_reduction_tab.c' l='226' u='r' c='cut_lp_to_hyperplane'/>
<use f='llvm/polly/lib/External/isl/basis_reduction_tab.c' l='227' u='r' c='cut_lp_to_hyperplane'/>
<use f='llvm/polly/lib/External/isl/basis_reduction_tab.c' l='232' u='r' c='cut_lp_to_hyperplane'/>
<use f='llvm/polly/lib/External/isl/basis_reduction_tab.c' l='233' u='r' c='cut_lp_to_hyperplane'/>
<use f='llvm/polly/lib/External/isl/basis_reduction_tab.c' l='236' u='r' c='cut_lp_to_hyperplane'/>
<use f='llvm/polly/lib/External/isl/basis_reduction_tab.c' l='237' u='r' c='cut_lp_to_hyperplane'/>
<use f='llvm/polly/lib/External/isl/basis_reduction_tab.c' l='238' u='r' c='cut_lp_to_hyperplane'/>
<use f='llvm/polly/lib/External/isl/basis_reduction_tab.c' l='272' u='r' c='add_lp_row'/>
<use f='llvm/polly/lib/External/isl/basis_reduction_tab.c' l='273' u='r' c='add_lp_row'/>
<use f='llvm/polly/lib/External/isl/basis_reduction_tab.c' l='274' u='r' c='add_lp_row'/>
<use f='llvm/polly/lib/External/isl/basis_reduction_tab.c' l='276' u='r' c='add_lp_row'/>
<use f='llvm/polly/lib/External/isl/basis_reduction_tab.c' l='285' u='r' c='get_alpha'/>
<use f='llvm/polly/lib/External/isl/basis_reduction_tab.c' l='286' u='r' c='get_alpha'/>
<offset>192</offset>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='149' u='r' c='isl_aff_zero_on_domain'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='150' u='r' c='isl_aff_zero_on_domain'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='242' u='r' c='isl_aff_val_on_domain'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='243' u='r' c='isl_aff_val_on_domain'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='244' u='r' c='isl_aff_val_on_domain'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='291' u='r' c='isl_aff_var_on_domain'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='292' u='r' c='isl_aff_var_on_domain'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='293' u='r' c='isl_aff_var_on_domain'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='595' u='r' c='vec_reorder'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='595' u='r' c='vec_reorder'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='596' u='r' c='vec_reorder'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='598' u='r' c='vec_reorder'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='598' u='r' c='vec_reorder'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='677' u='r' c='isl_aff_plain_is_zero'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='679' u='r' c='isl_aff_plain_is_zero'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='690' u='r' c='isl_aff_is_nan'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='726' u='r' c='isl_aff_get_denominator'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='742' u='r' c='isl_aff_get_denominator_val'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='758' u='r' c='isl_aff_get_constant_val'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='758' u='r' c='isl_aff_get_constant_val'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='788' u='r' c='isl_aff_get_coefficient_val'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='788' u='r' c='isl_aff_get_coefficient_val'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='815' u='r' c='isl_aff_coefficient_sgn'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='836' u='r' c='isl_aff_set_constant'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='860' u='r' c='isl_aff_set_constant_val'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='861' u='r' c='isl_aff_set_constant_val'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='873' u='r' c='isl_aff_set_constant_val'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='874' u='r' c='isl_aff_set_constant_val'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='876' u='r' c='isl_aff_set_constant_val'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='876' u='r' c='isl_aff_set_constant_val'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='878' u='r' c='isl_aff_set_constant_val'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='879' u='r' c='isl_aff_set_constant_val'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='880' u='r' c='isl_aff_set_constant_val'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='880' u='r' c='isl_aff_set_constant_val'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='881' u='r' c='isl_aff_set_constant_val'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='881' u='r' c='isl_aff_set_constant_val'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='916' u='r' c='isl_aff_add_constant'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='916' u='r' c='isl_aff_add_constant'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='936' u='r' c='isl_aff_add_rat_constant_val'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='936' u='r' c='isl_aff_add_rat_constant_val'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='937' u='r' c='isl_aff_add_rat_constant_val'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='938' u='r' c='isl_aff_add_rat_constant_val'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='938' u='r' c='isl_aff_add_rat_constant_val'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='943' u='r' c='isl_aff_add_rat_constant_val'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='944' u='r' c='isl_aff_add_rat_constant_val'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='945' u='r' c='isl_aff_add_rat_constant_val'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='945' u='r' c='isl_aff_add_rat_constant_val'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='946' u='r' c='isl_aff_add_rat_constant_val'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='946' u='r' c='isl_aff_add_rat_constant_val'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='1045' u='r' c='isl_aff_add_constant_num'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='1045' u='r' c='isl_aff_add_constant_num'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='1087' u='r' c='isl_aff_set_constant_si'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='1124' u='r' c='isl_aff_set_coefficient'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='1153' u='r' c='isl_aff_set_coefficient_si'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='1164' u='r' c='isl_aff_set_coefficient_si'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='1199' u='r' c='isl_aff_set_coefficient_val'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='1200' u='r' c='isl_aff_set_coefficient_val'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='1212' u='r' c='isl_aff_set_coefficient_val'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='1213' u='r' c='isl_aff_set_coefficient_val'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='1215' u='r' c='isl_aff_set_coefficient_val'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='1215' u='r' c='isl_aff_set_coefficient_val'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='1217' u='r' c='isl_aff_set_coefficient_val'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='1218' u='r' c='isl_aff_set_coefficient_val'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='1219' u='r' c='isl_aff_set_coefficient_val'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='1219' u='r' c='isl_aff_set_coefficient_val'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='1220' u='r' c='isl_aff_set_coefficient_val'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='1220' u='r' c='isl_aff_set_coefficient_val'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='1266' u='r' c='isl_aff_add_coefficient'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='1266' u='r' c='isl_aff_add_coefficient'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='1315' u='r' c='isl_aff_add_coefficient_val'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='1315' u='r' c='isl_aff_add_coefficient_val'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='1316' u='r' c='isl_aff_add_coefficient_val'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='1317' u='r' c='isl_aff_add_coefficient_val'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='1317' u='r' c='isl_aff_add_coefficient_val'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='1322' u='r' c='isl_aff_add_coefficient_val'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='1323' u='r' c='isl_aff_add_coefficient_val'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='1324' u='r' c='isl_aff_add_coefficient_val'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='1324' u='r' c='isl_aff_add_coefficient_val'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='1325' u='r' c='isl_aff_add_coefficient_val'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='1325' u='r' c='isl_aff_add_coefficient_val'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='1377' u='r' c='isl_aff_neg'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='1377' u='r' c='isl_aff_neg'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='1400' u='r' c='isl_aff_remove_unused_divs'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='1448' u='r' c='plug_in_integral_divs'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='1531' u='r' c='swap_div'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='1531' u='r' c='swap_div'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='1556' u='r' c='merge_divs'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='1563' u='r' c='merge_divs'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='1564' u='r' c='merge_divs'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='1564' u='r' c='merge_divs'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='1565' u='r' c='merge_divs'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='1647' u='r' c='isl_aff_floor'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='1659' u='r' c='isl_aff_floor'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='1659' u='r' c='isl_aff_floor'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='1659' u='r' c='isl_aff_floor'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='1660' u='r' c='isl_aff_floor'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='1670' u='r' c='isl_aff_floor'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='1670' u='r' c='isl_aff_floor'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='1672' u='r' c='isl_aff_floor'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='1672' u='r' c='isl_aff_floor'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='1672' u='r' c='isl_aff_floor'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='1673' u='r' c='isl_aff_floor'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='1673' u='r' c='isl_aff_floor'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='1673' u='r' c='isl_aff_floor'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='1674' u='r' c='isl_aff_floor'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='1674' u='r' c='isl_aff_floor'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='1675' u='r' c='isl_aff_floor'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='1675' u='r' c='isl_aff_floor'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='1675' u='r' c='isl_aff_floor'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='1676' u='r' c='isl_aff_floor'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='1676' u='r' c='isl_aff_floor'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='1688' u='r' c='isl_aff_floor'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='1689' u='r' c='isl_aff_floor'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='1786' u='r' c='isl_aff_ceil'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='1796' u='r' c='isl_aff_ceil'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='1796' u='r' c='isl_aff_ceil'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='1796' u='r' c='isl_aff_ceil'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='1797' u='r' c='isl_aff_ceil'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='1797' u='r' c='isl_aff_ceil'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='1850' u='r' c='add_expanded'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='1850' u='r' c='add_expanded'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='1851' u='r' c='add_expanded'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='1852' u='r' c='add_expanded'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='1852' u='r' c='add_expanded'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='1853' u='r' c='add_expanded'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='1854' u='r' c='add_expanded'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='1854' u='r' c='add_expanded'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='1855' u='r' c='add_expanded'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='1856' u='r' c='add_expanded'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='1856' u='r' c='add_expanded'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='1964' u='r' c='isl_aff_scale'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='1965' u='r' c='isl_aff_scale'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='1965' u='r' c='isl_aff_scale'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='1970' u='r' c='isl_aff_scale'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='1971' u='r' c='isl_aff_scale'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='1971' u='r' c='isl_aff_scale'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='1973' u='r' c='isl_aff_scale'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='1973' u='r' c='isl_aff_scale'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='2036' u='r' c='isl_aff_scale_down'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='2038' u='r' c='isl_aff_scale_down'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='2038' u='r' c='isl_aff_scale_down'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='2040' u='r' c='isl_aff_scale_down'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='2040' u='r' c='isl_aff_scale_down'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='2193' u='r' c='isl_aff_substitute_equalities_lifted'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='2194' u='r' c='isl_aff_substitute_equalities_lifted'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='2536' u='r' c='isl_aff_involves_dims'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='3381' u='r' c='isl_aff_is_cst'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='3436' u='r' c='isl_aff_mul'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='3437' u='r' c='isl_aff_mul'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='3482' u='r' c='isl_aff_div'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='3484' u='r' c='isl_aff_div'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='3484' u='r' c='isl_aff_div'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='3485' u='r' c='isl_aff_div'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='3485' u='r' c='isl_aff_div'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='3488' u='r' c='isl_aff_div'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='3489' u='r' c='isl_aff_div'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='3492' u='r' c='isl_aff_div'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='3492' u='r' c='isl_aff_div'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='3493' u='r' c='isl_aff_div'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='3493' u='r' c='isl_aff_div'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='3952' u='r' c='isl_multi_aff_from_aff_mat'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='3953' u='r' c='isl_multi_aff_from_aff_mat'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='4782' u='r' c='extract_aff_from_equality'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='4783' u='r' c='extract_aff_from_equality'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='4786' u='r' c='extract_aff_from_equality'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='4787' u='r' c='extract_aff_from_equality'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='4791' u='r' c='extract_aff_from_equality'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='4792' u='r' c='extract_aff_from_equality'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='4799' u='r' c='extract_aff_from_equality'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='4800' u='r' c='extract_aff_from_equality'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='4802' u='r' c='extract_aff_from_equality'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='5021' u='r' c='pw_multi_aff_from_map_div'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='5022' u='r' c='pw_multi_aff_from_map_div'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='5308' u='r' c='pw_multi_aff_from_map_stride'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='5310' u='r' c='pw_multi_aff_from_map_stride'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='5313' u='r' c='pw_multi_aff_from_map_stride'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='5315' u='r' c='pw_multi_aff_from_map_stride'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='5594' u='r' c='isl_aff_substitute'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='5594' u='r' c='isl_aff_substitute'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='5763' u='r' c='isl_seq_preimage'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='5773' u='r' c='isl_seq_preimage'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='5779' u='r' c='isl_seq_preimage'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='5785' u='r' c='isl_seq_preimage'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='5843' u='r' c='isl_aff_pullback_multi_aff'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='5843' u='r' c='isl_aff_pullback_multi_aff'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='7567' u='r' c='isl_aff_plain_cmp'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='7568' u='r' c='isl_aff_plain_cmp'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='7572' u='r' c='isl_aff_plain_cmp'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='7572' u='r' c='isl_aff_plain_cmp'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='9817' u='r' c='eval'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='9817' u='r' c='eval'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='9818' u='r' c='eval'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='9818' u='r' c='eval'/>
<use f='llvm/polly/lib/External/isl/isl_aff_map.c' l='90' u='r' c='isl_basic_map_from_aff2'/>
<use f='llvm/polly/lib/External/isl/isl_aff_map.c' l='91' u='r' c='isl_basic_map_from_aff2'/>
<use f='llvm/polly/lib/External/isl/isl_aff_map.c' l='92' u='r' c='isl_basic_map_from_aff2'/>
<use f='llvm/polly/lib/External/isl/isl_affine_hull.c' l='282' u='r' c='outside_point'/>
<use f='llvm/polly/lib/External/isl/isl_affine_hull.c' l='283' u='r' c='outside_point'/>
<use f='llvm/polly/lib/External/isl/isl_affine_hull.c' l='284' u='r' c='outside_point'/>
<use f='llvm/polly/lib/External/isl/isl_affine_hull.c' l='349' u='r' c='adjacent_point'/>
<use f='llvm/polly/lib/External/isl/isl_affine_hull.c' l='349' u='r' c='adjacent_point'/>
<use f='llvm/polly/lib/External/isl/isl_affine_hull.c' l='351' u='r' c='adjacent_point'/>
<use f='llvm/polly/lib/External/isl/isl_affine_hull.c' l='351' u='r' c='adjacent_point'/>
<use f='llvm/polly/lib/External/isl/isl_affine_hull.c' l='600' u='r' c='initial_hull'/>
<use f='llvm/polly/lib/External/isl/isl_affine_hull.c' l='652' u='r' c='isl_tab_detect_equalities'/>
<use f='llvm/polly/lib/External/isl/isl_affine_hull.c' l='663' u='r' c='isl_tab_detect_equalities'/>
<use f='llvm/polly/lib/External/isl/isl_bernstein.c' l='186' u='r' c='extract_coefficients'/>
<use f='llvm/polly/lib/External/isl/isl_bernstein.c' l='193' u='r' c='extract_coefficients'/>
<use f='llvm/polly/lib/External/isl/isl_bernstein.c' l='193' u='r' c='extract_coefficients'/>
<use f='llvm/polly/lib/External/isl/isl_bernstein.c' l='201' u='r' c='extract_coefficients'/>
<use f='llvm/polly/lib/External/isl/isl_bernstein.c' l='202' u='r' c='extract_coefficients'/>
<use f='llvm/polly/lib/External/isl/isl_bernstein.c' l='208' u='r' c='extract_coefficients'/>
<use f='llvm/polly/lib/External/isl/isl_bernstein.c' l='222' u='r' c='extract_coefficients'/>
<use f='llvm/polly/lib/External/isl/isl_bernstein.c' l='223' u='r' c='extract_coefficients'/>
<use f='llvm/polly/lib/External/isl/isl_bernstein.c' l='229' u='r' c='extract_coefficients'/>
<use f='llvm/polly/lib/External/isl/isl_bernstein.c' l='229' u='r' c='extract_coefficients'/>
<use f='llvm/polly/lib/External/isl/isl_bernstein.c' l='232' u='r' c='extract_coefficients'/>
<use f='llvm/polly/lib/External/isl/isl_bernstein.c' l='232' u='r' c='extract_coefficients'/>
<use f='llvm/polly/lib/External/isl/isl_coalesce.c' l='903' u='r' c='try_tightening'/>
<use f='llvm/polly/lib/External/isl/isl_coalesce.c' l='913' u='r' c='try_tightening'/>
<use f='llvm/polly/lib/External/isl/isl_coalesce.c' l='913' u='r' c='try_tightening'/>
<use f='llvm/polly/lib/External/isl/isl_coalesce.c' l='914' u='r' c='try_tightening'/>
<use f='llvm/polly/lib/External/isl/isl_coalesce.c' l='921' u='r' c='try_tightening'/>
<use f='llvm/polly/lib/External/isl/isl_coalesce.c' l='924' u='r' c='try_tightening'/>
<use f='llvm/polly/lib/External/isl/isl_coalesce.c' l='1017' u='r' c='tighten_on_relaxed_facet'/>
<use f='llvm/polly/lib/External/isl/isl_coalesce.c' l='1651' u='r' c='is_adj_ineq_extension'/>
<use f='llvm/polly/lib/External/isl/isl_coalesce.c' l='1774' u='r' c='can_wrap_in_facet'/>
<use f='llvm/polly/lib/External/isl/isl_coalesce.c' l='1775' u='r' c='can_wrap_in_facet'/>
<use f='llvm/polly/lib/External/isl/isl_coalesce.c' l='1775' u='r' c='can_wrap_in_facet'/>
<use f='llvm/polly/lib/External/isl/isl_coalesce.c' l='1776' u='r' c='can_wrap_in_facet'/>
<use f='llvm/polly/lib/External/isl/isl_coalesce.c' l='1778' u='r' c='can_wrap_in_facet'/>
<use f='llvm/polly/lib/External/isl/isl_coalesce.c' l='1781' u='r' c='can_wrap_in_facet'/>
<use f='llvm/polly/lib/External/isl/isl_coalesce.c' l='1788' u='r' c='can_wrap_in_facet'/>
<use f='llvm/polly/lib/External/isl/isl_coalesce.c' l='2320' u='r' c='check_eq_adj_eq'/>
<use f='llvm/polly/lib/External/isl/isl_coalesce.c' l='2322' u='r' c='check_eq_adj_eq'/>
<use f='llvm/polly/lib/External/isl/isl_coalesce.c' l='2323' u='r' c='check_eq_adj_eq'/>
<use f='llvm/polly/lib/External/isl/isl_coalesce.c' l='2323' u='r' c='check_eq_adj_eq'/>
<use f='llvm/polly/lib/External/isl/isl_coalesce.c' l='2325' u='r' c='check_eq_adj_eq'/>
<use f='llvm/polly/lib/External/isl/isl_coalesce.c' l='2328' u='r' c='check_eq_adj_eq'/>
<use f='llvm/polly/lib/External/isl/isl_coalesce.c' l='2333' u='r' c='check_eq_adj_eq'/>
<use f='llvm/polly/lib/External/isl/isl_coalesce.c' l='2333' u='r' c='check_eq_adj_eq'/>
<use f='llvm/polly/lib/External/isl/isl_coalesce.c' l='2334' u='r' c='check_eq_adj_eq'/>
<use f='llvm/polly/lib/External/isl/isl_coalesce.c' l='2334' u='r' c='check_eq_adj_eq'/>
<use f='llvm/polly/lib/External/isl/isl_coalesce.c' l='2336' u='r' c='check_eq_adj_eq'/>
<use f='llvm/polly/lib/External/isl/isl_coalesce.c' l='2339' u='r' c='check_eq_adj_eq'/>
<use f='llvm/polly/lib/External/isl/isl_coalesce.c' l='3060' u='r' c='fix_constant_divs'/>
<use f='llvm/polly/lib/External/isl/isl_coalesce.c' l='3069' u='r' c='fix_constant_divs'/>
<use f='llvm/polly/lib/External/isl/isl_coalesce.c' l='3070' u='r' c='fix_constant_divs'/>
<use f='llvm/polly/lib/External/isl/isl_coalesce.c' l='3072' u='r' c='fix_constant_divs'/>
<use f='llvm/polly/lib/External/isl/isl_coalesce.c' l='3073' u='r' c='fix_constant_divs'/>
<use f='llvm/polly/lib/External/isl/isl_coalesce.c' l='3074' u='r' c='fix_constant_divs'/>
<use f='llvm/polly/lib/External/isl/isl_coalesce.c' l='3076' u='r' c='fix_constant_divs'/>
<use f='llvm/polly/lib/External/isl/isl_coalesce.c' l='3077' u='r' c='fix_constant_divs'/>
<use f='llvm/polly/lib/External/isl/isl_coalesce.c' l='3761' u='r' c='add_sub_equalities'/>
<use f='llvm/polly/lib/External/isl/isl_coalesce.c' l='3771' u='r' c='add_sub_equalities'/>
<use f='llvm/polly/lib/External/isl/isl_coalesce.c' l='3771' u='r' c='add_sub_equalities'/>
<use f='llvm/polly/lib/External/isl/isl_coalesce.c' l='3772' u='r' c='add_sub_equalities'/>
<use f='llvm/polly/lib/External/isl/isl_coalesce.c' l='3772' u='r' c='add_sub_equalities'/>
<use f='llvm/polly/lib/External/isl/isl_coalesce.c' l='3773' u='r' c='add_sub_equalities'/>
<use f='llvm/polly/lib/External/isl/isl_coalesce.c' l='3775' u='r' c='add_sub_equalities'/>
<use f='llvm/polly/lib/External/isl/isl_constraint.c' l='111' u='r' c='isl_basic_map_constraint'/>
<use f='llvm/polly/lib/External/isl/isl_constraint.c' l='418' u='r' c='isl_constraint_involves_dims'/>
<use f='llvm/polly/lib/External/isl/isl_constraint.c' l='447' u='r' c='isl_constraint_is_lower_bound'/>
<use f='llvm/polly/lib/External/isl/isl_constraint.c' l='460' u='r' c='isl_constraint_is_upper_bound'/>
<use f='llvm/polly/lib/External/isl/isl_constraint.c' l='475' u='r' c='isl_constraint_get_constant'/>
<use f='llvm/polly/lib/External/isl/isl_constraint.c' l='489' u='r' c='isl_constraint_get_constant_val'/>
<use f='llvm/polly/lib/External/isl/isl_constraint.c' l='499' u='r' c='isl_constraint_get_coefficient'/>
<use f='llvm/polly/lib/External/isl/isl_constraint.c' l='515' u='r' c='isl_constraint_get_coefficient_val'/>
<use f='llvm/polly/lib/External/isl/isl_constraint.c' l='538' u='r' c='isl_constraint_set_constant'/>
<use f='llvm/polly/lib/External/isl/isl_constraint.c' l='573' u='r' c='isl_constraint_set_constant_si'/>
<use f='llvm/polly/lib/External/isl/isl_constraint.c' l='590' u='r' c='isl_constraint_set_coefficient'/>
<use f='llvm/polly/lib/External/isl/isl_constraint.c' l='634' u='r' c='isl_constraint_set_coefficient_si'/>
<use f='llvm/polly/lib/External/isl/isl_constraint.c' l='656' u='r' c='isl_constraint_negate'/>
<use f='llvm/polly/lib/External/isl/isl_constraint.c' l='656' u='r' c='isl_constraint_negate'/>
<use f='llvm/polly/lib/External/isl/isl_constraint.c' l='682' u='r' c='isl_constraint_is_div_constraint'/>
<use f='llvm/polly/lib/External/isl/isl_constraint.c' l='713' u='r' c='isl_constraint_is_div_equality'/>
<use f='llvm/polly/lib/External/isl/isl_constraint.c' l='751' u='r' c='isl_basic_map_from_constraint'/>
<use f='llvm/polly/lib/External/isl/isl_constraint.c' l='1239' u='r' c='isl_constraint_get_bound'/>
<use f='llvm/polly/lib/External/isl/isl_constraint.c' l='1248' u='r' c='isl_constraint_get_bound'/>
<use f='llvm/polly/lib/External/isl/isl_constraint.c' l='1249' u='r' c='isl_constraint_get_bound'/>
<use f='llvm/polly/lib/External/isl/isl_constraint.c' l='1249' u='r' c='isl_constraint_get_bound'/>
<use f='llvm/polly/lib/External/isl/isl_constraint.c' l='1251' u='r' c='isl_constraint_get_bound'/>
<use f='llvm/polly/lib/External/isl/isl_constraint.c' l='1251' u='r' c='isl_constraint_get_bound'/>
<use f='llvm/polly/lib/External/isl/isl_constraint.c' l='1252' u='r' c='isl_constraint_get_bound'/>
<use f='llvm/polly/lib/External/isl/isl_constraint.c' l='1253' u='r' c='isl_constraint_get_bound'/>
<use f='llvm/polly/lib/External/isl/isl_constraint.c' l='1253' u='r' c='isl_constraint_get_bound'/>
<use f='llvm/polly/lib/External/isl/isl_constraint.c' l='1281' u='r' c='isl_constraint_get_aff'/>
<use f='llvm/polly/lib/External/isl/isl_constraint.c' l='1281' u='r' c='isl_constraint_get_aff'/>
<use f='llvm/polly/lib/External/isl/isl_constraint.c' l='1282' u='r' c='isl_constraint_get_aff'/>
<use f='llvm/polly/lib/External/isl/isl_constraint.c' l='1347' u='r' c='isl_constraint_plain_cmp'/>
<use f='llvm/polly/lib/External/isl/isl_constraint.c' l='1348' u='r' c='isl_constraint_plain_cmp'/>
<use f='llvm/polly/lib/External/isl/isl_constraint.c' l='1352' u='r' c='isl_constraint_plain_cmp'/>
<use f='llvm/polly/lib/External/isl/isl_constraint.c' l='1352' u='r' c='isl_constraint_plain_cmp'/>
<use f='llvm/polly/lib/External/isl/isl_constraint.c' l='1382' u='r' c='isl_constraint_cmp_last_non_zero'/>
<use f='llvm/polly/lib/External/isl/isl_constraint.c' l='1383' u='r' c='isl_constraint_cmp_last_non_zero'/>
<use f='llvm/polly/lib/External/isl/isl_constraint.c' l='1388' u='r' c='isl_constraint_cmp_last_non_zero'/>
<use f='llvm/polly/lib/External/isl/isl_constraint.c' l='1388' u='r' c='isl_constraint_cmp_last_non_zero'/>
<use f='llvm/polly/lib/External/isl/isl_convex_hull.c' l='1121' u='r' c='valid_direction'/>
<use f='llvm/polly/lib/External/isl/isl_fold.c' l='485' u='r' c='isl_qpolynomial_aff_sign'/>
<use f='llvm/polly/lib/External/isl/isl_fold.c' l='485' u='r' c='isl_qpolynomial_aff_sign'/>
<use f='llvm/polly/lib/External/isl/isl_fold.c' l='495' u='r' c='isl_qpolynomial_aff_sign'/>
<use f='llvm/polly/lib/External/isl/isl_fold.c' l='495' u='r' c='isl_qpolynomial_aff_sign'/>
<use f='llvm/polly/lib/External/isl/isl_fold.c' l='564' u='r' c='isl_qpolynomial_sign'/>
<use f='llvm/polly/lib/External/isl/isl_fold.c' l='565' u='r' c='isl_qpolynomial_sign'/>
<use f='llvm/polly/lib/External/isl/isl_fold.c' l='566' u='r' c='isl_qpolynomial_sign'/>
<use f='llvm/polly/lib/External/isl/isl_fold.c' l='570' u='r' c='isl_qpolynomial_sign'/>
<use f='llvm/polly/lib/External/isl/isl_fold.c' l='570' u='r' c='isl_qpolynomial_sign'/>
<use f='llvm/polly/lib/External/isl/isl_ilp.c' l='182' u='r' c='solve_ilp_search'/>
<use f='llvm/polly/lib/External/isl/isl_ilp.c' l='221' u='r' c='solve_ilp'/>
<use f='llvm/polly/lib/External/isl/isl_ilp.c' l='249' u='r' c='solve_ilp'/>
<use f='llvm/polly/lib/External/isl/isl_ilp.c' l='282' u='r' c='solve_ilp_with_eq'/>
<use f='llvm/polly/lib/External/isl/isl_ilp.c' l='287' u='r' c='solve_ilp_with_eq'/>
<use f='llvm/polly/lib/External/isl/isl_ilp.c' l='355' u='r' c='basic_set_opt'/>
<use f='llvm/polly/lib/External/isl/isl_ilp.c' l='378' u='r' c='isl_basic_set_opt'/>
<use f='llvm/polly/lib/External/isl/isl_input.c' l='512' u='r' c='accept_affine_factor'/>
<use f='llvm/polly/lib/External/isl/isl_input.c' l='1043' u='r' c='pw_aff_is_expr'/>
<use f='llvm/polly/lib/External/isl/isl_input.c' l='3322' u='r' c='isl_vec_read_polylib'/>
<use f='llvm/polly/lib/External/isl/isl_local.c' l='300' u='r' c='isl_local_extend_point_vec'/>
<use f='llvm/polly/lib/External/isl/isl_local.c' l='310' u='r' c='isl_local_extend_point_vec'/>
<use f='llvm/polly/lib/External/isl/isl_local.c' l='311' u='r' c='isl_local_extend_point_vec'/>
<use f='llvm/polly/lib/External/isl/isl_local.c' l='312' u='r' c='isl_local_extend_point_vec'/>
<use f='llvm/polly/lib/External/isl/isl_local.c' l='312' u='r' c='isl_local_extend_point_vec'/>
<use f='llvm/polly/lib/External/isl/isl_local_space.c' l='319' u='r' c='extract_div'/>
<use f='llvm/polly/lib/External/isl/isl_local_space.c' l='588' u='r' c='isl_local_space_add_div'/>
<use f='llvm/polly/lib/External/isl/isl_local_space.c' l='1193' u='r' c='isl_local_space_substitute'/>
<use f='llvm/polly/lib/External/isl/isl_lp.c' l='117' u='r' c='isl_map_solve_lp'/>
<use f='llvm/polly/lib/External/isl/isl_lp.c' l='118' u='r' c='isl_map_solve_lp'/>
<use f='llvm/polly/lib/External/isl/isl_lp.c' l='119' u='r' c='isl_map_solve_lp'/>
<use f='llvm/polly/lib/External/isl/isl_lp.c' l='231' u='r' c='basic_set_opt_lp'/>
<use f='llvm/polly/lib/External/isl/isl_lp.c' l='232' u='r' c='basic_set_opt_lp'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='1871' u='r' c='isl_basic_map_insert_div'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='3609' u='r' c='isl_basic_map_contains'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='3617' u='r' c='isl_basic_map_contains'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='11466' u='r' c='isl_basic_set_vars_get_sign'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='11467' u='r' c='isl_basic_set_vars_get_sign'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='11473' u='r' c='isl_basic_set_vars_get_sign'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='11474' u='r' c='isl_basic_set_vars_get_sign'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='11477' u='r' c='isl_basic_set_vars_get_sign'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='11486' u='r' c='isl_basic_set_vars_get_sign'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='11487' u='r' c='isl_basic_set_vars_get_sign'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='11490' u='r' c='isl_basic_set_vars_get_sign'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='13454' u='r' c='isl_basic_set_substitute'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='13467' u='r' c='isl_basic_set_substitute'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='13468' u='r' c='isl_basic_set_substitute'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='13476' u='r' c='isl_basic_set_substitute'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='13477' u='r' c='isl_basic_set_substitute'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='13486' u='r' c='isl_basic_set_substitute'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='13487' u='r' c='isl_basic_set_substitute'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='13488' u='r' c='isl_basic_set_substitute'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='13622' u='r' c='multi_aff_strides'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='13664' u='r' c='add_ma_strides'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='13672' u='r' c='add_ma_strides'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='13678' u='r' c='add_ma_strides'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='13684' u='r' c='add_ma_strides'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='13688' u='r' c='add_ma_strides'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='14328' u='r' c='is_internal'/>
<use f='llvm/polly/lib/External/isl/isl_map_simplify.c' l='4279' u='r' c='test_ineq_is_satisfied'/>
<use f='llvm/polly/lib/External/isl/isl_map_simplify.c' l='4353' u='r' c='int_between_bounds'/>
<use f='llvm/polly/lib/External/isl/isl_map_simplify.c' l='4360' u='r' c='int_between_bounds'/>
<use f='llvm/polly/lib/External/isl/isl_map_simplify.c' l='4362' u='r' c='int_between_bounds'/>
<use f='llvm/polly/lib/External/isl/isl_map_simplify.c' l='4366' u='r' c='int_between_bounds'/>
<use f='llvm/polly/lib/External/isl/isl_map_simplify.c' l='4370' u='r' c='int_between_bounds'/>
<use f='llvm/polly/lib/External/isl/isl_map_simplify.c' l='4370' u='r' c='int_between_bounds'/>
<use f='llvm/polly/lib/External/isl/isl_map_simplify.c' l='4371' u='r' c='int_between_bounds'/>
<use f='llvm/polly/lib/External/isl/isl_map_simplify.c' l='4373' u='r' c='int_between_bounds'/>
<use f='llvm/polly/lib/External/isl/isl_map_simplify.c' l='4374' u='r' c='int_between_bounds'/>
<use f='llvm/polly/lib/External/isl/isl_map_simplify.c' l='4374' u='r' c='int_between_bounds'/>
<use f='llvm/polly/lib/External/isl/isl_map_simplify.c' l='5155' u='r' c='preimage'/>
<use f='llvm/polly/lib/External/isl/isl_map_simplify.c' l='5159' u='r' c='preimage'/>
<use f='llvm/polly/lib/External/isl/isl_map_simplify.c' l='5363' u='r' c='normalize_constraint'/>
<use f='llvm/polly/lib/External/isl/isl_map_simplify.c' l='5371' u='r' c='normalize_constraint'/>
<use f='llvm/polly/lib/External/isl/isl_map_simplify.c' l='5373' u='r' c='normalize_constraint'/>
<use f='llvm/polly/lib/External/isl/isl_map_simplify.c' l='5373' u='r' c='normalize_constraint'/>
<use f='llvm/polly/lib/External/isl/isl_map_simplify.c' l='5374' u='r' c='normalize_constraint'/>
<use f='llvm/polly/lib/External/isl/isl_map_simplify.c' l='5374' u='r' c='normalize_constraint'/>
<use f='llvm/polly/lib/External/isl/isl_map_simplify.c' l='5459' u='r' c='isl_basic_map_reduce_coefficients'/>
<use f='llvm/polly/lib/External/isl/isl_map_simplify.c' l='5465' u='r' c='isl_basic_map_reduce_coefficients'/>
<use f='llvm/polly/lib/External/isl/isl_map_subtract.c' l='37' u='r' c='expand_constraint'/>
<use f='llvm/polly/lib/External/isl/isl_map_subtract.c' l='38' u='r' c='expand_constraint'/>
<use f='llvm/polly/lib/External/isl/isl_map_subtract.c' l='42' u='r' c='expand_constraint'/>
<use f='llvm/polly/lib/External/isl/isl_map_subtract.c' l='42' u='r' c='expand_constraint'/>
<use f='llvm/polly/lib/External/isl/isl_map_subtract.c' l='78' u='r' c='tab_add_constraints'/>
<use f='llvm/polly/lib/External/isl/isl_map_subtract.c' l='82' u='r' c='tab_add_constraints'/>
<use f='llvm/polly/lib/External/isl/isl_map_subtract.c' l='91' u='r' c='tab_add_constraints'/>
<use f='llvm/polly/lib/External/isl/isl_map_subtract.c' l='144' u='r' c='tab_add_constraint'/>
<use f='llvm/polly/lib/External/isl/isl_map_subtract.c' l='158' u='r' c='tab_add_constraint'/>
<use f='llvm/polly/lib/External/isl/isl_map_subtract.c' l='197' u='r' c='tab_add_divs'/>
<use f='llvm/polly/lib/External/isl/isl_map_subtract.c' l='198' u='r' c='tab_add_divs'/>
<use f='llvm/polly/lib/External/isl/isl_map_subtract.c' l='200' u='r' c='tab_add_divs'/>
<use f='llvm/polly/lib/External/isl/isl_map_subtract.c' l='201' u='r' c='tab_add_divs'/>
<use f='llvm/polly/lib/External/isl/isl_map_subtract.c' l='205' u='r' c='tab_add_divs'/>
<use f='llvm/polly/lib/External/isl/isl_map_subtract.c' l='764' u='r' c='singleton_extract_point'/>
<use f='llvm/polly/lib/External/isl/isl_map_subtract.c' l='778' u='r' c='singleton_extract_point'/>
<use f='llvm/polly/lib/External/isl/isl_map_subtract.c' l='781' u='r' c='singleton_extract_point'/>
<use f='llvm/polly/lib/External/isl/isl_map_subtract.c' l='781' u='r' c='singleton_extract_point'/>
<use f='llvm/polly/lib/External/isl/isl_map_subtract.c' l='782' u='r' c='singleton_extract_point'/>
<use f='llvm/polly/lib/External/isl/isl_map_subtract.c' l='784' u='r' c='singleton_extract_point'/>
<use f='llvm/polly/lib/External/isl/isl_mat.c' l='466' u='r' c='isl_mat_vec_product'/>
<use f='llvm/polly/lib/External/isl/isl_mat.c' l='489' u='r' c='isl_mat_vec_inverse_product'/>
<use f='llvm/polly/lib/External/isl/isl_mat.c' l='497' u='r' c='isl_mat_vec_inverse_product'/>
<use f='llvm/polly/lib/External/isl/isl_mat.c' l='522' u='r' c='isl_vec_mat_product'/>
<use f='llvm/polly/lib/External/isl/isl_mat.c' l='524' u='r' c='isl_vec_mat_product'/>
<use f='llvm/polly/lib/External/isl/isl_mat.c' l='524' u='r' c='isl_vec_mat_product'/>
<use f='llvm/polly/lib/External/isl/isl_mat.c' l='1829' u='r' c='isl_mat_from_row_vec'/>
<use f='llvm/polly/lib/External/isl/isl_mat.c' l='1853' u='r' c='isl_mat_get_row'/>
<use f='llvm/polly/lib/External/isl/isl_output.c' l='813' u='r' c='print_constraints'/>
<use f='llvm/polly/lib/External/isl/isl_output.c' l='815' u='r' c='print_constraints'/>
<use f='llvm/polly/lib/External/isl/isl_output.c' l='816' u='r' c='print_constraints'/>
<use f='llvm/polly/lib/External/isl/isl_output.c' l='842' u='r' c='print_constraints'/>
<use f='llvm/polly/lib/External/isl/isl_output.c' l='844' u='r' c='print_constraints'/>
<use f='llvm/polly/lib/External/isl/isl_output.c' l='846' u='r' c='print_constraints'/>
<use f='llvm/polly/lib/External/isl/isl_output.c' l='852' u='r' c='print_constraints'/>
<use f='llvm/polly/lib/External/isl/isl_output.c' l='857' u='r' c='print_constraints'/>
<use f='llvm/polly/lib/External/isl/isl_output.c' l='2530' u='r' c='isl_printer_print_constraint'/>
<use f='llvm/polly/lib/External/isl/isl_output.c' l='2644' u='r' c='last_modulo'/>
<use f='llvm/polly/lib/External/isl/isl_output.c' l='2646' u='r' c='last_modulo'/>
<use f='llvm/polly/lib/External/isl/isl_output.c' l='2666' u='r' c='print_aff_num_base'/>
<use f='llvm/polly/lib/External/isl/isl_output.c' l='2799' u='r' c='print_aff_body'/>
<use f='llvm/polly/lib/External/isl/isl_output.c' l='2803' u='r' c='print_aff_body'/>
<use f='llvm/polly/lib/External/isl/isl_output.c' l='2980' u='r' c='print_aff_c'/>
<use f='llvm/polly/lib/External/isl/isl_output.c' l='2982' u='r' c='print_aff_c'/>
<use f='llvm/polly/lib/External/isl/isl_output.c' l='2983' u='r' c='print_aff_c'/>
<use f='llvm/polly/lib/External/isl/isl_output.c' l='2985' u='r' c='print_aff_c'/>
<use f='llvm/polly/lib/External/isl/isl_point.c' l='103' u='r' c='isl_point_zero'/>
<use f='llvm/polly/lib/External/isl/isl_point.c' l='104' u='r' c='isl_point_zero'/>
<use f='llvm/polly/lib/External/isl/isl_point.c' l='336' u='r' c='isl_point_get_coordinate_val'/>
<use f='llvm/polly/lib/External/isl/isl_point.c' l='337' u='r' c='isl_point_get_coordinate_val'/>
<use f='llvm/polly/lib/External/isl/isl_point.c' l='407' u='r' c='isl_point_set_coordinate_val'/>
<use f='llvm/polly/lib/External/isl/isl_point.c' l='408' u='r' c='isl_point_set_coordinate_val'/>
<use f='llvm/polly/lib/External/isl/isl_point.c' l='420' u='r' c='isl_point_set_coordinate_val'/>
<use f='llvm/polly/lib/External/isl/isl_point.c' l='421' u='r' c='isl_point_set_coordinate_val'/>
<use f='llvm/polly/lib/External/isl/isl_point.c' l='423' u='r' c='isl_point_set_coordinate_val'/>
<use f='llvm/polly/lib/External/isl/isl_point.c' l='423' u='r' c='isl_point_set_coordinate_val'/>
<use f='llvm/polly/lib/External/isl/isl_point.c' l='425' u='r' c='isl_point_set_coordinate_val'/>
<use f='llvm/polly/lib/External/isl/isl_point.c' l='426' u='r' c='isl_point_set_coordinate_val'/>
<use f='llvm/polly/lib/External/isl/isl_point.c' l='427' u='r' c='isl_point_set_coordinate_val'/>
<use f='llvm/polly/lib/External/isl/isl_point.c' l='427' u='r' c='isl_point_set_coordinate_val'/>
<use f='llvm/polly/lib/External/isl/isl_point.c' l='428' u='r' c='isl_point_set_coordinate_val'/>
<use f='llvm/polly/lib/External/isl/isl_point.c' l='428' u='r' c='isl_point_set_coordinate_val'/>
<use f='llvm/polly/lib/External/isl/isl_point.c' l='462' u='r' c='isl_point_add_ui'/>
<use f='llvm/polly/lib/External/isl/isl_point.c' l='462' u='r' c='isl_point_add_ui'/>
<use f='llvm/polly/lib/External/isl/isl_point.c' l='490' u='r' c='isl_point_sub_ui'/>
<use f='llvm/polly/lib/External/isl/isl_point.c' l='490' u='r' c='isl_point_sub_ui'/>
<use f='llvm/polly/lib/External/isl/isl_point.c' l='696' u='r' c='isl_basic_set_box_from_points'/>
<use f='llvm/polly/lib/External/isl/isl_point.c' l='696' u='r' c='isl_basic_set_box_from_points'/>
<use f='llvm/polly/lib/External/isl/isl_point.c' l='697' u='r' c='isl_basic_set_box_from_points'/>
<use f='llvm/polly/lib/External/isl/isl_point.c' l='697' u='r' c='isl_basic_set_box_from_points'/>
<use f='llvm/polly/lib/External/isl/isl_point.c' l='705' u='r' c='isl_basic_set_box_from_points'/>
<use f='llvm/polly/lib/External/isl/isl_point.c' l='708' u='r' c='isl_basic_set_box_from_points'/>
<use f='llvm/polly/lib/External/isl/isl_point.c' l='710' u='r' c='isl_basic_set_box_from_points'/>
<use f='llvm/polly/lib/External/isl/isl_point.c' l='718' u='r' c='isl_basic_set_box_from_points'/>
<use f='llvm/polly/lib/External/isl/isl_point.c' l='721' u='r' c='isl_basic_set_box_from_points'/>
<use f='llvm/polly/lib/External/isl/isl_point.c' l='723' u='r' c='isl_basic_set_box_from_points'/>
<use f='llvm/polly/lib/External/isl/isl_point.c' l='758' u='r' c='print_coordinate'/>
<use f='llvm/polly/lib/External/isl/isl_point.c' l='759' u='r' c='print_coordinate'/>
<use f='llvm/polly/lib/External/isl/isl_point.c' l='761' u='r' c='print_coordinate'/>
<use f='llvm/polly/lib/External/isl/isl_point.c' l='795' u='r' c='isl_printer_print_point'/>
<use f='llvm/polly/lib/External/isl/isl_point.c' l='796' u='r' c='isl_printer_print_point'/>
<use f='llvm/polly/lib/External/isl/isl_point.c' l='798' u='r' c='isl_printer_print_point'/>
<use f='llvm/polly/lib/External/isl/isl_polynomial.c' l='2094' u='r' c='update_coeff'/>
<use f='llvm/polly/lib/External/isl/isl_polynomial.c' l='2096' u='r' c='update_coeff'/>
<use f='llvm/polly/lib/External/isl/isl_polynomial.c' l='2097' u='r' c='update_coeff'/>
<use f='llvm/polly/lib/External/isl/isl_polynomial.c' l='2097' u='r' c='update_coeff'/>
<use f='llvm/polly/lib/External/isl/isl_polynomial.c' l='2098' u='r' c='update_coeff'/>
<use f='llvm/polly/lib/External/isl/isl_polynomial.c' l='2148' u='r' c='isl_qpolynomial_extract_affine'/>
<use f='llvm/polly/lib/External/isl/isl_polynomial.c' l='2149' u='r' c='isl_qpolynomial_extract_affine'/>
<use f='llvm/polly/lib/External/isl/isl_polynomial.c' l='3239' u='r' c='isl_poly_eval'/>
<use f='llvm/polly/lib/External/isl/isl_polynomial.c' l='3239' u='r' c='isl_poly_eval'/>
<use f='llvm/polly/lib/External/isl/isl_polynomial.c' l='3505' u='r' c='isl_qpolynomial_from_aff'/>
<use f='llvm/polly/lib/External/isl/isl_polynomial.c' l='3505' u='r' c='isl_qpolynomial_from_aff'/>
<use f='llvm/polly/lib/External/isl/isl_polynomial.c' l='4083' u='r' c='isl_term_get_div'/>
<use f='llvm/polly/lib/External/isl/isl_polynomial.c' l='4998' u='r' c='make_divs_pos'/>
<use f='llvm/polly/lib/External/isl/isl_polynomial.c' l='4999' u='r' c='make_divs_pos'/>
<use f='llvm/polly/lib/External/isl/isl_polynomial.c' l='4999' u='r' c='make_divs_pos'/>
<use f='llvm/polly/lib/External/isl/isl_polynomial.c' l='5000' u='r' c='make_divs_pos'/>
<use f='llvm/polly/lib/External/isl/isl_polynomial.c' l='5006' u='r' c='make_divs_pos'/>
<use f='llvm/polly/lib/External/isl/isl_polynomial.c' l='5008' u='r' c='make_divs_pos'/>
<use f='llvm/polly/lib/External/isl/isl_polynomial.c' l='5009' u='r' c='make_divs_pos'/>
<use f='llvm/polly/lib/External/isl/isl_polynomial.c' l='5014' u='r' c='make_divs_pos'/>
<use f='llvm/polly/lib/External/isl/isl_polynomial.c' l='5017' u='r' c='make_divs_pos'/>
<use f='llvm/polly/lib/External/isl/isl_polynomial.c' l='5024' u='r' c='make_divs_pos'/>
<use f='llvm/polly/lib/External/isl/isl_polynomial.c' l='5027' u='r' c='make_divs_pos'/>
<use f='llvm/polly/lib/External/isl/isl_polynomial.c' l='5028' u='r' c='make_divs_pos'/>
<use f='llvm/polly/lib/External/isl/isl_polynomial.c' l='5186' u='r' c='isl_basic_map_from_qpolynomial'/>
<use f='llvm/polly/lib/External/isl/isl_polynomial.c' l='5187' u='r' c='isl_basic_map_from_qpolynomial'/>
<use f='llvm/polly/lib/External/isl/isl_polynomial.c' l='5188' u='r' c='isl_basic_map_from_qpolynomial'/>
<use f='llvm/polly/lib/External/isl/isl_sample.c' l='50' u='r' c='zero_sample'/>
<use f='llvm/polly/lib/External/isl/isl_sample.c' l='51' u='r' c='zero_sample'/>
<use f='llvm/polly/lib/External/isl/isl_sample.c' l='85' u='r' c='interval_sample'/>
<use f='llvm/polly/lib/External/isl/isl_sample.c' l='89' u='r' c='interval_sample'/>
<use f='llvm/polly/lib/External/isl/isl_sample.c' l='228' u='r' c='compute_min'/>
<use f='llvm/polly/lib/External/isl/isl_sample.c' l='246' u='r' c='compute_max'/>
<use f='llvm/polly/lib/External/isl/isl_sample.c' l='249' u='r' c='compute_max'/>
<use f='llvm/polly/lib/External/isl/isl_sample.c' l='249' u='r' c='compute_max'/>
<use f='llvm/polly/lib/External/isl/isl_sample.c' l='287' u='r' c='greedy_search'/>
<use f='llvm/polly/lib/External/isl/isl_sample.c' l='287' u='r' c='greedy_search'/>
<use f='llvm/polly/lib/External/isl/isl_sample.c' l='315' u='r' c='greedy_search'/>
<use f='llvm/polly/lib/External/isl/isl_sample.c' l='315' u='r' c='greedy_search'/>
<use f='llvm/polly/lib/External/isl/isl_sample.c' l='455' u='r' c='isl_tab_sample'/>
<use f='llvm/polly/lib/External/isl/isl_sample.c' l='455' u='r' c='isl_tab_sample'/>
<use f='llvm/polly/lib/External/isl/isl_sample.c' l='483' u='r' c='isl_tab_sample'/>
<use f='llvm/polly/lib/External/isl/isl_sample.c' l='483' u='r' c='isl_tab_sample'/>
<use f='llvm/polly/lib/External/isl/isl_sample.c' l='485' u='r' c='isl_tab_sample'/>
<use f='llvm/polly/lib/External/isl/isl_sample.c' l='485' u='r' c='isl_tab_sample'/>
<use f='llvm/polly/lib/External/isl/isl_sample.c' l='493' u='r' c='isl_tab_sample'/>
<use f='llvm/polly/lib/External/isl/isl_sample.c' l='509' u='r' c='isl_tab_sample'/>
<use f='llvm/polly/lib/External/isl/isl_sample.c' l='568' u='r' c='factor_sample'/>
<use f='llvm/polly/lib/External/isl/isl_sample.c' l='568' u='r' c='factor_sample'/>
<use f='llvm/polly/lib/External/isl/isl_sample.c' l='594' u='r' c='factored_sample'/>
<use f='llvm/polly/lib/External/isl/isl_sample.c' l='713' u='r' c='plug_in'/>
<use f='llvm/polly/lib/External/isl/isl_sample.c' l='805' u='r' c='shift_cone'/>
<use f='llvm/polly/lib/External/isl/isl_sample.c' l='808' u='r' c='shift_cone'/>
<use f='llvm/polly/lib/External/isl/isl_sample.c' l='849' u='r' c='round_up_in_cone'/>
<use f='llvm/polly/lib/External/isl/isl_sample.c' l='886' u='r' c='vec_concat'/>
<use f='llvm/polly/lib/External/isl/isl_sample.c' l='887' u='r' c='vec_concat'/>
<use f='llvm/polly/lib/External/isl/isl_sample.c' l='893' u='r' c='vec_concat'/>
<use f='llvm/polly/lib/External/isl/isl_sample.c' l='893' u='r' c='vec_concat'/>
<use f='llvm/polly/lib/External/isl/isl_sample.c' l='894' u='r' c='vec_concat'/>
<use f='llvm/polly/lib/External/isl/isl_sample.c' l='894' u='r' c='vec_concat'/>
<use f='llvm/polly/lib/External/isl/isl_sample.c' l='1000' u='r' c='vec_sum_of_neg'/>
<use f='llvm/polly/lib/External/isl/isl_sample.c' l='1001' u='r' c='vec_sum_of_neg'/>
<use f='llvm/polly/lib/External/isl/isl_sample.c' l='1045' u='r' c='tab_shift_cone'/>
<use f='llvm/polly/lib/External/isl/isl_sample.c' l='1230' u='r' c='isl_basic_set_from_vec'/>
<use f='llvm/polly/lib/External/isl/isl_sample.c' l='1231' u='r' c='isl_basic_set_from_vec'/>
<use f='llvm/polly/lib/External/isl/isl_scan.c' l='79' u='r' c='scan_0D'/>
<use f='llvm/polly/lib/External/isl/isl_scan.c' l='153' u='r' c='isl_basic_set_scan'/>
<use f='llvm/polly/lib/External/isl/isl_scan.c' l='161' u='r' c='isl_basic_set_scan'/>
<use f='llvm/polly/lib/External/isl/isl_scan.c' l='164' u='r' c='isl_basic_set_scan'/>
<use f='llvm/polly/lib/External/isl/isl_scan.c' l='164' u='r' c='isl_basic_set_scan'/>
<use f='llvm/polly/lib/External/isl/isl_scan.c' l='171' u='r' c='isl_basic_set_scan'/>
<use f='llvm/polly/lib/External/isl/isl_scan.c' l='171' u='r' c='isl_basic_set_scan'/>
<use f='llvm/polly/lib/External/isl/isl_scan.c' l='173' u='r' c='isl_basic_set_scan'/>
<use f='llvm/polly/lib/External/isl/isl_scan.c' l='173' u='r' c='isl_basic_set_scan'/>
<use f='llvm/polly/lib/External/isl/isl_scan.c' l='183' u='r' c='isl_basic_set_scan'/>
<use f='llvm/polly/lib/External/isl/isl_scan.c' l='183' u='r' c='isl_basic_set_scan'/>
<use f='llvm/polly/lib/External/isl/isl_scan.c' l='192' u='r' c='isl_basic_set_scan'/>
<use f='llvm/polly/lib/External/isl/isl_scheduler.c' l='877' u='r' c='compute_max_coefficient'/>
<use f='llvm/polly/lib/External/isl/isl_scheduler.c' l='878' u='r' c='compute_max_coefficient'/>
<use f='llvm/polly/lib/External/isl/isl_scheduler.c' l='878' u='r' c='compute_max_coefficient'/>
<use f='llvm/polly/lib/External/isl/isl_scheduler.c' l='894' u='r' c='compute_max_coefficient'/>
<use f='llvm/polly/lib/External/isl/isl_scheduler.c' l='895' u='r' c='compute_max_coefficient'/>
<use f='llvm/polly/lib/External/isl/isl_scheduler.c' l='896' u='r' c='compute_max_coefficient'/>
<use f='llvm/polly/lib/External/isl/isl_scheduler.c' l='902' u='r' c='compute_max_coefficient'/>
<use f='llvm/polly/lib/External/isl/isl_scheduler.c' l='902' u='r' c='compute_max_coefficient'/>
<use f='llvm/polly/lib/External/isl/isl_scheduler.c' l='2795' u='r' c='node_add_coefficient_constraints'/>
<use f='llvm/polly/lib/External/isl/isl_scheduler.c' l='2798' u='r' c='node_add_coefficient_constraints'/>
<use f='llvm/polly/lib/External/isl/isl_scheduler.c' l='2799' u='r' c='node_add_coefficient_constraints'/>
<use f='llvm/polly/lib/External/isl/isl_scheduler.c' l='2800' u='r' c='node_add_coefficient_constraints'/>
<use f='llvm/polly/lib/External/isl/isl_scheduler.c' l='2800' u='r' c='node_add_coefficient_constraints'/>
<use f='llvm/polly/lib/External/isl/isl_scheduler.c' l='2805' u='r' c='node_add_coefficient_constraints'/>
<use f='llvm/polly/lib/External/isl/isl_scheduler.c' l='2807' u='r' c='node_add_coefficient_constraints'/>
<use f='llvm/polly/lib/External/isl/isl_scheduler.c' l='2807' u='r' c='node_add_coefficient_constraints'/>
<use f='llvm/polly/lib/External/isl/isl_scheduler.c' l='2811' u='r' c='node_add_coefficient_constraints'/>
<use f='llvm/polly/lib/External/isl/isl_scheduler.c' l='2813' u='r' c='node_add_coefficient_constraints'/>
<use f='llvm/polly/lib/External/isl/isl_scheduler.c' l='3160' u='r' c='extract_var_coef'/>
<use f='llvm/polly/lib/External/isl/isl_scheduler.c' l='3161' u='r' c='extract_var_coef'/>
<use f='llvm/polly/lib/External/isl/isl_scheduler.c' l='3161' u='r' c='extract_var_coef'/>
<use f='llvm/polly/lib/External/isl/isl_scheduler.c' l='3208' u='r' c='update_schedule'/>
<use f='llvm/polly/lib/External/isl/isl_scheduler.c' l='3212' u='r' c='update_schedule'/>
<use f='llvm/polly/lib/External/isl/isl_scheduler.c' l='3215' u='r' c='update_schedule'/>
<use f='llvm/polly/lib/External/isl/isl_scheduler.c' l='4579' u='r' c='is_trivial'/>
<use f='llvm/polly/lib/External/isl/isl_scheduler.c' l='4636' u='r' c='find_node_coalescing'/>
<use f='llvm/polly/lib/External/isl/isl_scheduler.c' l='4649' u='r' c='find_node_coalescing'/>
<use f='llvm/polly/lib/External/isl/isl_scheduler.c' l='4655' u='r' c='find_node_coalescing'/>
<use f='llvm/polly/lib/External/isl/isl_scheduler.c' l='4693' u='r' c='zero_out_node_coef'/>
<use f='llvm/polly/lib/External/isl/isl_scheduler.c' l='4694' u='r' c='zero_out_node_coef'/>
<use f='llvm/polly/lib/External/isl/isl_scheduler.c' l='4695' u='r' c='zero_out_node_coef'/>
<use f='llvm/polly/lib/External/isl/isl_scheduler.c' l='4742' u='r' c='carries_dependences'/>
<use f='llvm/polly/lib/External/isl/isl_scheduler.c' l='4742' u='r' c='carries_dependences'/>
<use f='llvm/polly/lib/External/isl/isl_scheduler.c' l='4742' u='r' c='carries_dependences'/>
<use f='llvm/polly/lib/External/isl/isl_scheduler.c' l='4743' u='r' c='carries_dependences'/>
<use f='llvm/polly/lib/External/isl/isl_scheduler.c' l='4744' u='r' c='carries_dependences'/>
<use f='llvm/polly/lib/External/isl/isl_scheduler.c' l='4807' u='r' c='non_neg_lexmin'/>
<use f='llvm/polly/lib/External/isl/isl_tab.c' l='902' u='r' c='isl_tab_add_sample'/>
<use f='llvm/polly/lib/External/isl/isl_tab.c' l='2217' u='r' c='ineq_for_div'/>
<use f='llvm/polly/lib/External/isl/isl_tab.c' l='2218' u='r' c='ineq_for_div'/>
<use f='llvm/polly/lib/External/isl/isl_tab.c' l='2254' u='r' c='add_div_constraints'/>
<use f='llvm/polly/lib/External/isl/isl_tab.c' l='2257' u='r' c='add_div_constraints'/>
<use f='llvm/polly/lib/External/isl/isl_tab.c' l='2261' u='r' c='add_div_constraints'/>
<use f='llvm/polly/lib/External/isl/isl_tab.c' l='2262' u='r' c='add_div_constraints'/>
<use f='llvm/polly/lib/External/isl/isl_tab.c' l='2263' u='r' c='add_div_constraints'/>
<use f='llvm/polly/lib/External/isl/isl_tab.c' l='2263' u='r' c='add_div_constraints'/>
<use f='llvm/polly/lib/External/isl/isl_tab.c' l='2263' u='r' c='add_div_constraints'/>
<use f='llvm/polly/lib/External/isl/isl_tab.c' l='2264' u='r' c='add_div_constraints'/>
<use f='llvm/polly/lib/External/isl/isl_tab.c' l='2264' u='r' c='add_div_constraints'/>
<use f='llvm/polly/lib/External/isl/isl_tab.c' l='2267' u='r' c='add_div_constraints'/>
<use f='llvm/polly/lib/External/isl/isl_tab.c' l='2270' u='r' c='add_div_constraints'/>
<use f='llvm/polly/lib/External/isl/isl_tab.c' l='2295' u='r' c='div_is_nonneg'/>
<use f='llvm/polly/lib/External/isl/isl_tab.c' l='2299' u='r' c='div_is_nonneg'/>
<use f='llvm/polly/lib/External/isl/isl_tab.c' l='2301' u='r' c='div_is_nonneg'/>
<use f='llvm/polly/lib/External/isl/isl_tab.c' l='3389' u='r' c='isl_tab_min'/>
<use f='llvm/polly/lib/External/isl/isl_tab.c' l='3393' u='r' c='isl_tab_min'/>
<use f='llvm/polly/lib/External/isl/isl_tab.c' l='3398' u='r' c='isl_tab_min'/>
<use f='llvm/polly/lib/External/isl/isl_tab.c' l='3401' u='r' c='isl_tab_min'/>
<use f='llvm/polly/lib/External/isl/isl_tab.c' l='3580' u='r' c='detect_constant_with_tmp'/>
<use f='llvm/polly/lib/External/isl/isl_tab.c' l='3581' u='r' c='detect_constant_with_tmp'/>
<use f='llvm/polly/lib/External/isl/isl_tab.c' l='3582' u='r' c='detect_constant_with_tmp'/>
<use f='llvm/polly/lib/External/isl/isl_tab.c' l='3583' u='r' c='detect_constant_with_tmp'/>
<use f='llvm/polly/lib/External/isl/isl_tab_pip.c' l='291' u='r' c='set_from_affine_matrix'/>
<use f='llvm/polly/lib/External/isl/isl_tab_pip.c' l='292' u='r' c='set_from_affine_matrix'/>
<use f='llvm/polly/lib/External/isl/isl_tab_pip.c' l='913' u='r' c='get_row_parameter_ineq'/>
<use f='llvm/polly/lib/External/isl/isl_tab_pip.c' l='933' u='r' c='normalize_div'/>
<use f='llvm/polly/lib/External/isl/isl_tab_pip.c' l='934' u='r' c='normalize_div'/>
<use f='llvm/polly/lib/External/isl/isl_tab_pip.c' l='939' u='r' c='normalize_div'/>
<use f='llvm/polly/lib/External/isl/isl_tab_pip.c' l='939' u='r' c='normalize_div'/>
<use f='llvm/polly/lib/External/isl/isl_tab_pip.c' l='940' u='r' c='normalize_div'/>
<use f='llvm/polly/lib/External/isl/isl_tab_pip.c' l='940' u='r' c='normalize_div'/>
<use f='llvm/polly/lib/External/isl/isl_tab_pip.c' l='941' u='r' c='normalize_div'/>
<use f='llvm/polly/lib/External/isl/isl_tab_pip.c' l='941' u='r' c='normalize_div'/>
<use f='llvm/polly/lib/External/isl/isl_tab_pip.c' l='963' u='r' c='get_row_parameter_div'/>
<use f='llvm/polly/lib/External/isl/isl_tab_pip.c' l='964' u='r' c='get_row_parameter_div'/>
<use f='llvm/polly/lib/External/isl/isl_tab_pip.c' l='965' u='r' c='get_row_parameter_div'/>
<use f='llvm/polly/lib/External/isl/isl_tab_pip.c' l='965' u='r' c='get_row_parameter_div'/>
<use f='llvm/polly/lib/External/isl/isl_tab_pip.c' l='967' u='r' c='get_row_parameter_div'/>
<use f='llvm/polly/lib/External/isl/isl_tab_pip.c' l='967' u='r' c='get_row_parameter_div'/>
<use f='llvm/polly/lib/External/isl/isl_tab_pip.c' l='967' u='r' c='get_row_parameter_div'/>
<use f='llvm/polly/lib/External/isl/isl_tab_pip.c' l='991' u='r' c='get_row_split_div'/>
<use f='llvm/polly/lib/External/isl/isl_tab_pip.c' l='992' u='r' c='get_row_split_div'/>
<use f='llvm/polly/lib/External/isl/isl_tab_pip.c' l='994' u='r' c='get_row_split_div'/>
<use f='llvm/polly/lib/External/isl/isl_tab_pip.c' l='994' u='r' c='get_row_split_div'/>
<use f='llvm/polly/lib/External/isl/isl_tab_pip.c' l='994' u='r' c='get_row_split_div'/>
<use f='llvm/polly/lib/External/isl/isl_tab_pip.c' l='1026' u='r' c='ineq_for_div'/>
<use f='llvm/polly/lib/External/isl/isl_tab_pip.c' l='1027' u='r' c='ineq_for_div'/>
<use f='llvm/polly/lib/External/isl/isl_tab_pip.c' l='2066' u='r' c='context_tab_insert_div'/>
<use f='llvm/polly/lib/External/isl/isl_tab_pip.c' l='2069' u='r' c='context_tab_insert_div'/>
<use f='llvm/polly/lib/External/isl/isl_tab_pip.c' l='2161' u='r' c='get_div'/>
<use f='llvm/polly/lib/External/isl/isl_tab_pip.c' l='2161' u='r' c='get_div'/>
<use f='llvm/polly/lib/External/isl/isl_tab_pip.c' l='2431' u='r' c='best_split'/>
<use f='llvm/polly/lib/External/isl/isl_tab_pip.c' l='2451' u='r' c='best_split'/>
<use f='llvm/polly/lib/External/isl/isl_tab_pip.c' l='2736' u='r' c='tab_detect_nonnegative_parameters'/>
<use f='llvm/polly/lib/External/isl/isl_tab_pip.c' l='2738' u='r' c='tab_detect_nonnegative_parameters'/>
<use f='llvm/polly/lib/External/isl/isl_tab_pip.c' l='2739' u='r' c='tab_detect_nonnegative_parameters'/>
<use f='llvm/polly/lib/External/isl/isl_tab_pip.c' l='2750' u='r' c='tab_detect_nonnegative_parameters'/>
<use f='llvm/polly/lib/External/isl/isl_tab_pip.c' l='2931' u='r' c='gbr_init_shifted'/>
<use f='llvm/polly/lib/External/isl/isl_tab_pip.c' l='2943' u='r' c='gbr_init_shifted'/>
<use f='llvm/polly/lib/External/isl/isl_tab_pip.c' l='3347' u='r' c='propagate_equalities'/>
<use f='llvm/polly/lib/External/isl/isl_tab_pip.c' l='3355' u='r' c='propagate_equalities'/>
<use f='llvm/polly/lib/External/isl/isl_tab_pip.c' l='3356' u='r' c='propagate_equalities'/>
<use f='llvm/polly/lib/External/isl/isl_tab_pip.c' l='3360' u='r' c='propagate_equalities'/>
<use f='llvm/polly/lib/External/isl/isl_tab_pip.c' l='3772' u='r' c='is_strict'/>
<use f='llvm/polly/lib/External/isl/isl_tab_pip.c' l='3774' u='r' c='is_strict'/>
<use f='llvm/polly/lib/External/isl/isl_tab_pip.c' l='3775' u='r' c='is_strict'/>
<use f='llvm/polly/lib/External/isl/isl_tab_pip.c' l='3775' u='r' c='is_strict'/>
<use f='llvm/polly/lib/External/isl/isl_tab_pip.c' l='3776' u='r' c='is_strict'/>
<use f='llvm/polly/lib/External/isl/isl_tab_pip.c' l='3776' u='r' c='is_strict'/>
<use f='llvm/polly/lib/External/isl/isl_tab_pip.c' l='3867' u='r' c='row_sign'/>
<use f='llvm/polly/lib/External/isl/isl_tab_pip.c' l='3873' u='r' c='row_sign'/>
<use f='llvm/polly/lib/External/isl/isl_tab_pip.c' l='3873' u='r' c='row_sign'/>
<use f='llvm/polly/lib/External/isl/isl_tab_pip.c' l='3874' u='r' c='row_sign'/>
<use f='llvm/polly/lib/External/isl/isl_tab_pip.c' l='3874' u='r' c='row_sign'/>
<use f='llvm/polly/lib/External/isl/isl_tab_pip.c' l='3876' u='r' c='row_sign'/>
<use f='llvm/polly/lib/External/isl/isl_tab_pip.c' l='3885' u='r' c='row_sign'/>
<use f='llvm/polly/lib/External/isl/isl_tab_pip.c' l='3885' u='r' c='row_sign'/>
<use f='llvm/polly/lib/External/isl/isl_tab_pip.c' l='3886' u='r' c='row_sign'/>
<use f='llvm/polly/lib/External/isl/isl_tab_pip.c' l='3886' u='r' c='row_sign'/>
<use f='llvm/polly/lib/External/isl/isl_tab_pip.c' l='3894' u='r' c='row_sign'/>
<use f='llvm/polly/lib/External/isl/isl_tab_pip.c' l='3894' u='r' c='row_sign'/>
<use f='llvm/polly/lib/External/isl/isl_tab_pip.c' l='3896' u='r' c='row_sign'/>
<use f='llvm/polly/lib/External/isl/isl_tab_pip.c' l='3964' u='r' c='no_sol_in_strict'/>
<use f='llvm/polly/lib/External/isl/isl_tab_pip.c' l='3964' u='r' c='no_sol_in_strict'/>
<use f='llvm/polly/lib/External/isl/isl_tab_pip.c' l='3966' u='r' c='no_sol_in_strict'/>
<use f='llvm/polly/lib/External/isl/isl_tab_pip.c' l='3975' u='r' c='no_sol_in_strict'/>
<use f='llvm/polly/lib/External/isl/isl_tab_pip.c' l='3975' u='r' c='no_sol_in_strict'/>
<use f='llvm/polly/lib/External/isl/isl_tab_pip.c' l='4143' u='r' c='find_solutions'/>
<use f='llvm/polly/lib/External/isl/isl_tab_pip.c' l='4145' u='r' c='find_solutions'/>
<use f='llvm/polly/lib/External/isl/isl_tab_pip.c' l='4145' u='r' c='find_solutions'/>
<use f='llvm/polly/lib/External/isl/isl_tab_pip.c' l='4146' u='r' c='find_solutions'/>
<use f='llvm/polly/lib/External/isl/isl_tab_pip.c' l='4146' u='r' c='find_solutions'/>
<use f='llvm/polly/lib/External/isl/isl_tab_pip.c' l='4148' u='r' c='find_solutions'/>
<use f='llvm/polly/lib/External/isl/isl_tab_pip.c' l='4182' u='r' c='find_solutions'/>
<use f='llvm/polly/lib/External/isl/isl_tab_pip.c' l='4182' u='r' c='find_solutions'/>
<use f='llvm/polly/lib/External/isl/isl_tab_pip.c' l='4183' u='r' c='find_solutions'/>
<use f='llvm/polly/lib/External/isl/isl_tab_pip.c' l='4269' u='r' c='find_solutions_main'/>
<use f='llvm/polly/lib/External/isl/isl_tab_pip.c' l='4270' u='r' c='find_solutions_main'/>
<use f='llvm/polly/lib/External/isl/isl_tab_pip.c' l='4276' u='r' c='find_solutions_main'/>
<use f='llvm/polly/lib/External/isl/isl_tab_pip.c' l='4276' u='r' c='find_solutions_main'/>
<use f='llvm/polly/lib/External/isl/isl_tab_pip.c' l='4279' u='r' c='find_solutions_main'/>
<use f='llvm/polly/lib/External/isl/isl_tab_pip.c' l='4279' u='r' c='find_solutions_main'/>
<use f='llvm/polly/lib/External/isl/isl_tab_pip.c' l='4281' u='r' c='find_solutions_main'/>
<use f='llvm/polly/lib/External/isl/isl_tab_lexopt_templ.c' l='81' u='r' c='basic_map_partial_lexopt_symm'/>
<use f='llvm/polly/lib/External/isl/isl_tab_lexopt_templ.c' l='83' u='r' c='basic_map_partial_lexopt_symm'/>
<use f='llvm/polly/lib/External/isl/isl_tab_lexopt_templ.c' l='109' u='r' c='basic_map_partial_lexopt_symm'/>
<use f='llvm/polly/lib/External/isl/isl_tab_pip.c' l='4994' u='r' c='extract_sample_sequence'/>
<use f='llvm/polly/lib/External/isl/isl_tab_pip.c' l='4999' u='r' c='extract_sample_sequence'/>
<use f='llvm/polly/lib/External/isl/isl_tab_pip.c' l='5094' u='r' c='is_optimal'/>
<use f='llvm/polly/lib/External/isl/isl_tab_pip.c' l='5124' u='r' c='force_better_solution'/>
<use f='llvm/polly/lib/External/isl/isl_tab_pip.c' l='5141' u='r' c='force_better_solution'/>
<use f='llvm/polly/lib/External/isl/isl_tab_pip.c' l='5142' u='r' c='force_better_solution'/>
<use f='llvm/polly/lib/External/isl/isl_tab_pip.c' l='5169' u='r' c='fix_zero'/>
<use f='llvm/polly/lib/External/isl/isl_tab_pip.c' l='5171' u='r' c='fix_zero'/>
<use f='llvm/polly/lib/External/isl/isl_tab_pip.c' l='5194' u='r' c='pos_neg'/>
<use f='llvm/polly/lib/External/isl/isl_tab_pip.c' l='5199' u='r' c='pos_neg'/>
<use f='llvm/polly/lib/External/isl/isl_tab_pip.c' l='5202' u='r' c='pos_neg'/>
<use f='llvm/polly/lib/External/isl/isl_tab_pip.c' l='5204' u='r' c='pos_neg'/>
<use f='llvm/polly/lib/External/isl/isl_tab_pip.c' l='5873' u='r' c='set_minimum_pa'/>
<use f='llvm/polly/lib/External/isl/isl_tab_pip.c' l='5874' u='r' c='set_minimum_pa'/>
<use f='llvm/polly/lib/External/isl/isl_tab_pip.c' l='5875' u='r' c='set_minimum_pa'/>
<use f='llvm/polly/lib/External/isl/isl_tab_lexopt_templ.c' l='81' u='r' c='basic_map_partial_lexopt_symm_pw_multi_aff'/>
<use f='llvm/polly/lib/External/isl/isl_tab_lexopt_templ.c' l='83' u='r' c='basic_map_partial_lexopt_symm_pw_multi_aff'/>
<use f='llvm/polly/lib/External/isl/isl_tab_lexopt_templ.c' l='109' u='r' c='basic_map_partial_lexopt_symm_pw_multi_aff'/>
<use f='llvm/polly/lib/External/isl/isl_transitive_closure.c' l='2217' u='r' c='box_closure_on_domain'/>
<use f='llvm/polly/lib/External/isl/isl_transitive_closure.c' l='2221' u='r' c='box_closure_on_domain'/>
<use f='llvm/polly/lib/External/isl/isl_transitive_closure.c' l='2223' u='r' c='box_closure_on_domain'/>
<use f='llvm/polly/lib/External/isl/isl_transitive_closure.c' l='2238' u='r' c='box_closure_on_domain'/>
<use f='llvm/polly/lib/External/isl/isl_transitive_closure.c' l='2253' u='r' c='box_closure_on_domain'/>
<use f='llvm/polly/lib/External/isl/isl_vec.c' l='29' u='r' c='isl_vec_get_hash'/>
<use f='llvm/polly/lib/External/isl/isl_vec.c' l='48' u='w' c='isl_vec_alloc'/>
<use f='llvm/polly/lib/External/isl/isl_vec.c' l='73' u='w' c='isl_vec_extend'/>
<use f='llvm/polly/lib/External/isl/isl_vec.c' l='111' u='r' c='isl_vec_expand'/>
<use f='llvm/polly/lib/External/isl/isl_vec.c' l='111' u='r' c='isl_vec_expand'/>
<use f='llvm/polly/lib/External/isl/isl_vec.c' l='117' u='r' c='isl_vec_expand'/>
<use f='llvm/polly/lib/External/isl/isl_vec.c' l='118' u='r' c='isl_vec_expand'/>
<use f='llvm/polly/lib/External/isl/isl_vec.c' l='121' u='r' c='isl_vec_expand'/>
<use f='llvm/polly/lib/External/isl/isl_vec.c' l='137' u='r' c='isl_vec_zero'/>
<use f='llvm/polly/lib/External/isl/isl_vec.c' l='159' u='r' c='isl_vec_zero_extend'/>
<use f='llvm/polly/lib/External/isl/isl_vec.c' l='187' u='r' c='isl_vec_concat'/>
<use f='llvm/polly/lib/External/isl/isl_vec.c' l='187' u='r' c='isl_vec_concat'/>
<use f='llvm/polly/lib/External/isl/isl_vec.c' l='215' u='r' c='isl_vec_dup'/>
<use f='llvm/polly/lib/External/isl/isl_vec.c' l='215' u='r' c='isl_vec_dup'/>
<use f='llvm/polly/lib/External/isl/isl_vec.c' l='265' u='r' c='isl_vec_get_element_val'/>
<use f='llvm/polly/lib/External/isl/isl_vec.c' l='277' u='r' c='isl_vec_set_element'/>
<use f='llvm/polly/lib/External/isl/isl_vec.c' l='293' u='r' c='isl_vec_set_element_si'/>
<use f='llvm/polly/lib/External/isl/isl_vec.c' l='328' u='r' c='isl_vec_cmp_element'/>
<use f='llvm/polly/lib/External/isl/isl_vec.c' l='328' u='r' c='isl_vec_cmp_element'/>
<use f='llvm/polly/lib/External/isl/isl_vec.c' l='337' u='r' c='isl_vec_is_zero'/>
<use f='llvm/polly/lib/External/isl/isl_vec.c' l='348' u='r' c='isl_vec_is_equal'/>
<use f='llvm/polly/lib/External/isl/isl_vec.c' l='348' u='r' c='isl_vec_is_equal'/>
<use f='llvm/polly/lib/External/isl/isl_vec.c' l='363' u='r' c='isl_printer_print_vec'/>
<use f='llvm/polly/lib/External/isl/isl_vec.c' l='392' u='r' c='isl_vec_set'/>
<use f='llvm/polly/lib/External/isl/isl_vec.c' l='401' u='r' c='isl_vec_set_si'/>
<use f='llvm/polly/lib/External/isl/isl_vec.c' l='416' u='r' c='isl_vec_set_val'/>
<use f='llvm/polly/lib/External/isl/isl_vec.c' l='430' u='r' c='isl_vec_clr'/>
<use f='llvm/polly/lib/External/isl/isl_vec.c' l='448' u='r' c='isl_vec_ceil'/>
<use f='llvm/polly/lib/External/isl/isl_vec.c' l='448' u='r' c='isl_vec_ceil'/>
<use f='llvm/polly/lib/External/isl/isl_vec.c' l='448' u='r' c='isl_vec_ceil'/>
<use f='llvm/polly/lib/External/isl/isl_vec.c' l='450' u='r' c='isl_vec_ceil'/>
<use f='llvm/polly/lib/External/isl/isl_vec.c' l='459' u='r' c='isl_vec_normalize'/>
<use f='llvm/polly/lib/External/isl/isl_vec.c' l='468' u='r' c='isl_vec_neg'/>
<use f='llvm/polly/lib/External/isl/isl_vec.c' l='468' u='r' c='isl_vec_neg'/>
<use f='llvm/polly/lib/External/isl/isl_vec.c' l='479' u='r' c='isl_vec_scale'/>
<use f='llvm/polly/lib/External/isl/isl_vec.c' l='479' u='r' c='isl_vec_scale'/>
<use f='llvm/polly/lib/External/isl/isl_vec.c' l='491' u='r' c='isl_vec_fdiv_r'/>
<use f='llvm/polly/lib/External/isl/isl_vec.c' l='491' u='r' c='isl_vec_fdiv_r'/>
<use f='llvm/polly/lib/External/isl/isl_vec.c' l='505' u='r' c='isl_vec_add'/>
<use f='llvm/polly/lib/External/isl/isl_vec.c' l='505' u='r' c='isl_vec_add'/>
<use f='llvm/polly/lib/External/isl/isl_vec.c' l='506' u='r' c='isl_vec_add'/>
<use f='llvm/polly/lib/External/isl/isl_vec.c' l='529' u='r' c='isl_vec_sort'/>
<use f='llvm/polly/lib/External/isl/isl_vec.c' l='529' u='r' c='isl_vec_sort'/>
<use f='llvm/polly/lib/External/isl/isl_vec.c' l='548' u='r' c='isl_vec_drop_els'/>
<use f='llvm/polly/lib/External/isl/isl_vec.c' l='548' u='r' c='isl_vec_drop_els'/>
<use f='llvm/polly/lib/External/isl/isl_vec.c' l='577' u='r' c='isl_vec_insert_els'/>
<use f='llvm/polly/lib/External/isl/isl_vec.c' l='577' u='r' c='isl_vec_insert_els'/>
<use f='llvm/polly/lib/External/isl/isl_vec.c' l='578' u='r' c='isl_vec_insert_els'/>
<use f='llvm/polly/lib/External/isl/isl_vec.c' l='578' u='r' c='isl_vec_insert_els'/>
<use f='llvm/polly/lib/External/isl/isl_vec.c' l='604' u='r' c='isl_vec_insert_zero_els'/>
<use f='llvm/polly/lib/External/isl/isl_vec.c' l='638' u='r' c='isl_vec_move_els'/>
<use f='llvm/polly/lib/External/isl/isl_vec.c' l='638' u='r' c='isl_vec_move_els'/>
<use f='llvm/polly/lib/External/isl/isl_vec.c' l='639' u='r' c='isl_vec_move_els'/>
<use f='llvm/polly/lib/External/isl/isl_vec.c' l='639' u='r' c='isl_vec_move_els'/>
<use f='llvm/polly/lib/External/isl/isl_vec.c' l='640' u='r' c='isl_vec_move_els'/>
<use f='llvm/polly/lib/External/isl/isl_vec.c' l='641' u='r' c='isl_vec_move_els'/>
<use f='llvm/polly/lib/External/isl/isl_vec.c' l='642' u='r' c='isl_vec_move_els'/>
<use f='llvm/polly/lib/External/isl/isl_vec.c' l='643' u='r' c='isl_vec_move_els'/>
<use f='llvm/polly/lib/External/isl/isl_vec.c' l='645' u='r' c='isl_vec_move_els'/>
<use f='llvm/polly/lib/External/isl/isl_vec.c' l='645' u='r' c='isl_vec_move_els'/>
<use f='llvm/polly/lib/External/isl/isl_vec.c' l='646' u='r' c='isl_vec_move_els'/>
<use f='llvm/polly/lib/External/isl/isl_vec.c' l='647' u='r' c='isl_vec_move_els'/>
<use f='llvm/polly/lib/External/isl/isl_vec.c' l='648' u='r' c='isl_vec_move_els'/>
<use f='llvm/polly/lib/External/isl/isl_vec.c' l='648' u='r' c='isl_vec_move_els'/>
<use f='llvm/polly/lib/External/isl/isl_vec.c' l='649' u='r' c='isl_vec_move_els'/>
<use f='llvm/polly/lib/External/isl/isl_vec.c' l='650' u='r' c='isl_vec_move_els'/>
<use f='llvm/polly/lib/External/isl/isl_vertices.c' l='710' u='r' c='create_todo'/>
<use f='llvm/polly/lib/External/isl/isl_vertices.c' l='922' u='r' c='compute_chambers'/>
<use f='llvm/polly/lib/External/isl/isl_vertices.c' l='1141' u='r' c='tab_for_shifted_cone'/>
<use f='llvm/polly/lib/External/isl/isl_vertices.c' l='1143' u='r' c='tab_for_shifted_cone'/>
<use f='llvm/polly/lib/External/isl/isl_vertices.c' l='1144' u='r' c='tab_for_shifted_cone'/>
<use f='llvm/polly/lib/External/isl/isl_vertices.c' l='1148' u='r' c='tab_for_shifted_cone'/>
<use f='llvm/polly/lib/External/isl/isl_vertices.c' l='1150' u='r' c='tab_for_shifted_cone'/>
<use f='llvm/polly/lib/External/isl/isl_vertices.c' l='1151' u='r' c='tab_for_shifted_cone'/>
<use f='llvm/polly/lib/External/isl/isl_vertices.c' l='1159' u='r' c='tab_for_shifted_cone'/>
<use f='llvm/polly/lib/External/isl/isl_vertices.c' l='1160' u='r' c='tab_for_shifted_cone'/>
<use f='llvm/polly/lib/External/isl/isl_vertices.c' l='1161' u='r' c='tab_for_shifted_cone'/>
<use f='llvm/polly/lib/External/isl/isl_vertices.c' l='1187' u='r' c='isl_basic_set_interior_point'/>
<use f='llvm/polly/lib/External/isl/isl_vertices.c' l='1187' u='r' c='isl_basic_set_interior_point'/>
<use f='llvm/polly/lib/External/isl/isl_vertices.c' l='1440' u='r' c='vertex_on_facet'/>
<use f='llvm/polly/lib/External/isl/isl_vertices.c' l='1445' u='r' c='vertex_on_facet'/>
<use f='llvm/polly/lib/External/isl/isl_vertices.c' l='1449' u='r' c='vertex_on_facet'/>
