<dec f='llvm/polly/lib/External/isl/isl_multi_templ.h' l='24' type='isl_union_pw_aff *[1]'/>
<use f='llvm/polly/lib/External/isl/isl_multi_templ.c' l='93' u='r' c='isl_multi_union_pw_aff_dup'/>
<use f='llvm/polly/lib/External/isl/isl_multi_templ.c' l='133' u='r' c='isl_multi_union_pw_aff_free'/>
<use f='llvm/polly/lib/External/isl/isl_multi_templ.c' l='168' u='r' c='isl_multi_union_pw_aff_get_at'/>
<use f='llvm/polly/lib/External/isl/isl_multi_templ.c' l='192' u='r' c='isl_multi_union_pw_aff_restore'/>
<use f='llvm/polly/lib/External/isl/isl_multi_templ.c' l='193' u='w' c='isl_multi_union_pw_aff_restore'/>
<use f='llvm/polly/lib/External/isl/isl_multi_templ.c' l='303' u='w' c='isl_multi_union_pw_aff_reset_space_and_domain'/>
<use f='llvm/polly/lib/External/isl/isl_multi_templ.c' l='303' u='r' c='isl_multi_union_pw_aff_reset_space_and_domain'/>
<use f='llvm/polly/lib/External/isl/isl_multi_templ.c' l='305' u='r' c='isl_multi_union_pw_aff_reset_space_and_domain'/>
<use f='llvm/polly/lib/External/isl/isl_multi_templ.c' l='370' u='w' c='isl_multi_union_pw_aff_realign_domain'/>
<use f='llvm/polly/lib/External/isl/isl_multi_templ.c' l='370' u='r' c='isl_multi_union_pw_aff_realign_domain'/>
<use f='llvm/polly/lib/External/isl/isl_multi_templ.c' l='372' u='r' c='isl_multi_union_pw_aff_realign_domain'/>
<use f='llvm/polly/lib/External/isl/isl_multi_templ.c' l='498' u='r' c='isl_multi_union_pw_aff_drop_dims'/>
<use f='llvm/polly/lib/External/isl/isl_multi_templ.c' l='500' u='w' c='isl_multi_union_pw_aff_drop_dims'/>
<use f='llvm/polly/lib/External/isl/isl_multi_templ.c' l='500' u='r' c='isl_multi_union_pw_aff_drop_dims'/>
<use f='llvm/polly/lib/External/isl/isl_multi_templ.c' l='515' u='w' c='isl_multi_union_pw_aff_drop_dims'/>
<use f='llvm/polly/lib/External/isl/isl_multi_templ.c' l='515' u='r' c='isl_multi_union_pw_aff_drop_dims'/>
<use f='llvm/polly/lib/External/isl/isl_multi_templ.c' l='516' u='r' c='isl_multi_union_pw_aff_drop_dims'/>
<use f='llvm/polly/lib/External/isl/isl_multi_templ.c' l='775' u='w' c='isl_multi_union_pw_aff_bin_op'/>
<use f='llvm/polly/lib/External/isl/isl_multi_templ.c' l='775' u='r' c='isl_multi_union_pw_aff_bin_op'/>
<use f='llvm/polly/lib/External/isl/isl_multi_templ.c' l='776' u='r' c='isl_multi_union_pw_aff_bin_op'/>
<use f='llvm/polly/lib/External/isl/isl_multi_templ.c' l='777' u='r' c='isl_multi_union_pw_aff_bin_op'/>
<use f='llvm/polly/lib/External/isl/isl_multi_templ.c' l='811' u='r' c='isl_multi_union_pw_aff_any'/>
<use f='llvm/polly/lib/External/isl/isl_multi_templ.c' l='837' u='r' c='isl_multi_union_pw_aff_every'/>
<use f='llvm/polly/lib/External/isl/isl_multi_templ.c' l='884' u='r' c='isl_multi_union_pw_aff_plain_is_equal'/>
<use f='llvm/polly/lib/External/isl/isl_multi_templ.c' l='884' u='r' c='isl_multi_union_pw_aff_plain_is_equal'/>
<use f='llvm/polly/lib/External/isl/isl_multi_apply_templ.c' l='37' u='w' c='isl_multi_union_pw_aff_apply_aligned_set'/>
<use f='llvm/polly/lib/External/isl/isl_multi_apply_templ.c' l='37' u='r' c='isl_multi_union_pw_aff_apply_aligned_set'/>
<use f='llvm/polly/lib/External/isl/isl_multi_apply_templ.c' l='38' u='r' c='isl_multi_union_pw_aff_apply_aligned_set'/>
<use f='llvm/polly/lib/External/isl/isl_multi_apply_templ.c' l='37' u='w' c='isl_multi_union_pw_aff_apply_aligned_union_set'/>
<use f='llvm/polly/lib/External/isl/isl_multi_apply_templ.c' l='37' u='r' c='isl_multi_union_pw_aff_apply_aligned_union_set'/>
<use f='llvm/polly/lib/External/isl/isl_multi_apply_templ.c' l='38' u='r' c='isl_multi_union_pw_aff_apply_aligned_union_set'/>
<use f='llvm/polly/lib/External/isl/isl_multi_arith_templ.c' l='56' u='w' c='isl_multi_union_pw_aff_scale_val'/>
<use f='llvm/polly/lib/External/isl/isl_multi_arith_templ.c' l='56' u='r' c='isl_multi_union_pw_aff_scale_val'/>
<use f='llvm/polly/lib/External/isl/isl_multi_arith_templ.c' l='58' u='r' c='isl_multi_union_pw_aff_scale_val'/>
<use f='llvm/polly/lib/External/isl/isl_multi_arith_templ.c' l='96' u='w' c='isl_multi_union_pw_aff_scale_down_val'/>
<use f='llvm/polly/lib/External/isl/isl_multi_arith_templ.c' l='96' u='r' c='isl_multi_union_pw_aff_scale_down_val'/>
<use f='llvm/polly/lib/External/isl/isl_multi_arith_templ.c' l='98' u='r' c='isl_multi_union_pw_aff_scale_down_val'/>
<use f='llvm/polly/lib/External/isl/isl_multi_arith_templ.c' l='133' u='w' c='isl_multi_union_pw_aff_scale_multi_val'/>
<use f='llvm/polly/lib/External/isl/isl_multi_arith_templ.c' l='133' u='r' c='isl_multi_union_pw_aff_scale_multi_val'/>
<use f='llvm/polly/lib/External/isl/isl_multi_arith_templ.c' l='134' u='r' c='isl_multi_union_pw_aff_scale_multi_val'/>
<use f='llvm/polly/lib/External/isl/isl_multi_arith_templ.c' l='169' u='w' c='isl_multi_union_pw_aff_scale_down_multi_val'/>
<use f='llvm/polly/lib/External/isl/isl_multi_arith_templ.c' l='169' u='r' c='isl_multi_union_pw_aff_scale_down_multi_val'/>
<use f='llvm/polly/lib/External/isl/isl_multi_arith_templ.c' l='170' u='r' c='isl_multi_union_pw_aff_scale_down_multi_val'/>
<use f='llvm/polly/lib/External/isl/isl_multi_arith_templ.c' l='205' u='w' c='isl_multi_union_pw_aff_mod_multi_val'/>
<use f='llvm/polly/lib/External/isl/isl_multi_arith_templ.c' l='205' u='r' c='isl_multi_union_pw_aff_mod_multi_val'/>
<use f='llvm/polly/lib/External/isl/isl_multi_arith_templ.c' l='206' u='r' c='isl_multi_union_pw_aff_mod_multi_val'/>
<use f='llvm/polly/lib/External/isl/isl_multi_arith_templ.c' l='228' u='w' c='isl_multi_union_pw_aff_neg'/>
<use f='llvm/polly/lib/External/isl/isl_multi_arith_templ.c' l='228' u='r' c='isl_multi_union_pw_aff_neg'/>
<use f='llvm/polly/lib/External/isl/isl_multi_arith_templ.c' l='229' u='r' c='isl_multi_union_pw_aff_neg'/>
<use f='llvm/polly/lib/External/isl/isl_multi_coalesce.c' l='26' u='r' c='isl_multi_union_pw_aff_coalesce'/>
<use f='llvm/polly/lib/External/isl/isl_multi_coalesce.c' l='30' u='r' c='isl_multi_union_pw_aff_coalesce'/>
<use f='llvm/polly/lib/External/isl/isl_multi_coalesce.c' l='31' u='w' c='isl_multi_union_pw_aff_coalesce'/>
<use f='llvm/polly/lib/External/isl/isl_multi_dim_id_templ.c' l='63' u='w' c='isl_multi_union_pw_aff_set_dim_name'/>
<use f='llvm/polly/lib/External/isl/isl_multi_dim_id_templ.c' l='63' u='r' c='isl_multi_union_pw_aff_set_dim_name'/>
<use f='llvm/polly/lib/External/isl/isl_multi_dim_id_templ.c' l='65' u='r' c='isl_multi_union_pw_aff_set_dim_name'/>
<use f='llvm/polly/lib/External/isl/isl_multi_floor.c' l='23' u='w' c='isl_multi_union_pw_aff_floor'/>
<use f='llvm/polly/lib/External/isl/isl_multi_floor.c' l='23' u='r' c='isl_multi_union_pw_aff_floor'/>
<use f='llvm/polly/lib/External/isl/isl_multi_floor.c' l='24' u='r' c='isl_multi_union_pw_aff_floor'/>
<offset>64</offset>
