<dec f='llvm/polly/lib/External/isl/include/isl/arg.h' l='85' type='struct (anonymous struct at /fast/tmp/llvm-proj-12/polly/lib/External/isl/include/isl/arg.h:81:2)'/>
<offset>0</offset>
<use f='llvm/polly/lib/External/isl/isl_arg.c' l='69' u='m' c='set_default_long'/>
<use f='llvm/polly/lib/External/isl/isl_arg.c' l='555' u='m' c='print_long_help'/>
<use f='llvm/polly/lib/External/isl/isl_arg.c' l='561' u='m' c='print_long_help'/>
<use f='llvm/polly/lib/External/isl/isl_arg.c' l='1058' u='m' c='parse_long_option'/>
<use f='llvm/polly/lib/External/isl/isl_arg.c' l='1059' u='m' c='parse_long_option'/>
<use f='llvm/polly/lib/External/isl/isl_arg.c' l='1067' u='m' c='parse_long_option'/>
<use f='llvm/polly/lib/External/isl/isl_arg.c' l='1068' u='m' c='parse_long_option'/>
<use f='llvm/polly/lib/External/isl/isl_arg.c' l='1073' u='m' c='parse_long_option'/>
<use f='llvm/polly/lib/External/isl/isl_arg.c' l='1073' u='m' c='parse_long_option'/>
<use f='llvm/polly/lib/External/isl/isl_arg.c' l='1074' u='m' c='parse_long_option'/>
<use f='llvm/polly/lib/External/isl/isl_arg.c' l='1075' u='m' c='parse_long_option'/>
<use f='llvm/polly/lib/External/isl/isl_arg.c' l='1076' u='m' c='parse_long_option'/>
<use f='llvm/polly/lib/External/isl/isl_arg.c' l='1076' u='m' c='parse_long_option'/>
