<dec f='llvm/polly/lib/External/isl/isl_ast_private.h' l='74' type='isl_ast_expr *'/>
<use f='llvm/polly/lib/External/isl/isl_ast.c' l='1045' u='w' c='isl_ast_node_dup'/>
<use f='llvm/polly/lib/External/isl/isl_ast.c' l='1045' u='r' c='isl_ast_node_dup'/>
<use f='llvm/polly/lib/External/isl/isl_ast.c' l='1048' u='r' c='isl_ast_node_dup'/>
<use f='llvm/polly/lib/External/isl/isl_ast.c' l='1103' u='r' c='isl_ast_node_free'/>
<use f='llvm/polly/lib/External/isl/isl_ast.c' l='1241' u='r' c='isl_ast_node_for_get_inc'/>
<use f='llvm/polly/lib/External/isl/isl_ast.c' l='2171' u='r' c='print_ast_node_isl'/>
<use f='llvm/polly/lib/External/isl/isl_ast.c' l='2392' u='r' c='print_for_c'/>
<use f='llvm/polly/lib/External/isl/isl_ast.c' l='2656' u='r' c='ast_node_required_macros'/>
<offset>256</offset>
<use f='llvm/polly/lib/External/isl/isl_ast_codegen.c' l='1129' u='w' c='set_for_node_expressions'/>
<use f='llvm/polly/lib/External/isl/isl_ast_codegen.c' l='1131' u='r' c='set_for_node_expressions'/>
