<dec f='llvm/polly/lib/External/isl/isl_stream_private.h' l='14' type='isl_int'/>
<use f='llvm/polly/lib/External/isl/isl_input.c' l='167' u='r' c='next_token'/>
<use f='llvm/polly/lib/External/isl/isl_input.c' l='167' u='r' c='next_token'/>
<use f='llvm/polly/lib/External/isl/isl_input.c' l='167' u='r' c='next_token'/>
<use f='llvm/polly/lib/External/isl/isl_input.c' l='228' u='r' c='isl_stream_read_val'/>
<use f='llvm/polly/lib/External/isl/isl_input.c' l='228' u='r' c='isl_stream_read_val'/>
<use f='llvm/polly/lib/External/isl/isl_input.c' l='231' u='r' c='isl_stream_read_val'/>
<use f='llvm/polly/lib/External/isl/isl_input.c' l='269' u='r' c='int_div_by_cst'/>
<use f='llvm/polly/lib/External/isl/isl_input.c' l='289' u='r' c='accept_cst_factor'/>
<use f='llvm/polly/lib/External/isl/isl_input.c' l='322' u='r' c='affine_mod'/>
<use f='llvm/polly/lib/External/isl/isl_input.c' l='324' u='r' c='affine_mod'/>
<use f='llvm/polly/lib/External/isl/isl_input.c' l='440' u='r' c='accept_div'/>
<use f='llvm/polly/lib/External/isl/isl_input.c' l='518' u='r' c='accept_affine_factor'/>
<use f='llvm/polly/lib/External/isl/isl_input.c' l='524' u='r' c='accept_affine_factor'/>
<use f='llvm/polly/lib/External/isl/isl_input.c' l='641' u='r' c='accept_affine'/>
<use f='llvm/polly/lib/External/isl/isl_input.c' l='641' u='r' c='accept_affine'/>
<use f='llvm/polly/lib/External/isl/isl_input.c' l='647' u='r' c='accept_affine'/>
<use f='llvm/polly/lib/External/isl/isl_input.c' l='654' u='a' c='accept_affine'/>
<use f='llvm/polly/lib/External/isl/isl_input.c' l='656' u='r' c='accept_affine'/>
<use f='llvm/polly/lib/External/isl/isl_input.c' l='678' u='r' c='accept_affine'/>
<use f='llvm/polly/lib/External/isl/isl_input.c' l='2179' u='r' c='basic_map_read_polylib_constraint'/>
<use f='llvm/polly/lib/External/isl/isl_input.c' l='2213' u='r' c='basic_map_read_polylib_constraint'/>
<use f='llvm/polly/lib/External/isl/isl_input.c' l='2255' u='r' c='basic_map_read_polylib'/>
<use f='llvm/polly/lib/External/isl/isl_input.c' l='2256' u='r' c='basic_map_read_polylib'/>
<use f='llvm/polly/lib/External/isl/isl_input.c' l='2271' u='r' c='basic_map_read_polylib'/>
<use f='llvm/polly/lib/External/isl/isl_input.c' l='2282' u='r' c='basic_map_read_polylib'/>
<use f='llvm/polly/lib/External/isl/isl_input.c' l='2293' u='r' c='basic_map_read_polylib'/>
<use f='llvm/polly/lib/External/isl/isl_input.c' l='2304' u='r' c='basic_map_read_polylib'/>
<use f='llvm/polly/lib/External/isl/isl_input.c' l='2366' u='r' c='map_read_polylib'/>
<use f='llvm/polly/lib/External/isl/isl_input.c' l='2400' u='r' c='optional_power'/>
<use f='llvm/polly/lib/External/isl/isl_input.c' l='2445' u='r' c='read_factor'/>
<use f='llvm/polly/lib/External/isl/isl_input.c' l='2445' u='r' c='read_factor'/>
<use f='llvm/polly/lib/External/isl/isl_input.c' l='2450' u='r' c='read_factor'/>
<use f='llvm/polly/lib/External/isl/isl_input.c' l='2542' u='r' c='read_term'/>
<use f='llvm/polly/lib/External/isl/isl_input.c' l='2919' u='r' c='obj_read'/>
<use f='llvm/polly/lib/External/isl/isl_input.c' l='2923' u='r' c='obj_read'/>
<use f='llvm/polly/lib/External/isl/isl_input.c' l='3311' u='r' c='isl_vec_read_polylib'/>
<use f='llvm/polly/lib/External/isl/isl_input.c' l='3322' u='r' c='isl_vec_read_polylib'/>
<offset>0</offset>
<use f='llvm/polly/lib/External/isl/isl_stream.c' l='100' u='r' c='isl_token_get_val'/>
<use f='llvm/polly/lib/External/isl/isl_stream.c' l='122' u='r' c='isl_token_free'/>
<use f='llvm/polly/lib/External/isl/isl_stream.c' l='147' u='r' c='isl_stream_error'/>
<use f='llvm/polly/lib/External/isl/isl_stream.c' l='454' u='r' c='next_token'/>
<use f='llvm/polly/lib/External/isl/isl_stream.c' l='463' u='r' c='next_token'/>
<use f='llvm/polly/lib/External/isl/isl_stream.c' l='464' u='r' c='next_token'/>
