<dec f='llvm/polly/lib/External/isl/isl_ast_private.h' l='68' type='struct (anonymous struct at /fast/tmp/llvm-proj-12/polly/lib/External/isl/isl_ast_private.h:64:3)'/>
<use f='llvm/polly/lib/External/isl/isl_ast.c' l='879' u='m' c='isl_ast_node_alloc_if'/>
<use f='llvm/polly/lib/External/isl/isl_ast.c' l='1034' u='m' c='isl_ast_node_dup'/>
<use f='llvm/polly/lib/External/isl/isl_ast.c' l='1034' u='m' c='isl_ast_node_dup'/>
<use f='llvm/polly/lib/External/isl/isl_ast.c' l='1035' u='m' c='isl_ast_node_dup'/>
<use f='llvm/polly/lib/External/isl/isl_ast.c' l='1035' u='m' c='isl_ast_node_dup'/>
<use f='llvm/polly/lib/External/isl/isl_ast.c' l='1036' u='m' c='isl_ast_node_dup'/>
<use f='llvm/polly/lib/External/isl/isl_ast.c' l='1036' u='m' c='isl_ast_node_dup'/>
<use f='llvm/polly/lib/External/isl/isl_ast.c' l='1037' u='m' c='isl_ast_node_dup'/>
<use f='llvm/polly/lib/External/isl/isl_ast.c' l='1037' u='m' c='isl_ast_node_dup'/>
<use f='llvm/polly/lib/External/isl/isl_ast.c' l='1038' u='m' c='isl_ast_node_dup'/>
<use f='llvm/polly/lib/External/isl/isl_ast.c' l='1038' u='m' c='isl_ast_node_dup'/>
<use f='llvm/polly/lib/External/isl/isl_ast.c' l='1095' u='m' c='isl_ast_node_free'/>
<use f='llvm/polly/lib/External/isl/isl_ast.c' l='1096' u='m' c='isl_ast_node_free'/>
<use f='llvm/polly/lib/External/isl/isl_ast.c' l='1097' u='m' c='isl_ast_node_free'/>
<use f='llvm/polly/lib/External/isl/isl_ast.c' l='1257' u='m' c='isl_ast_node_if_set_then'/>
<use f='llvm/polly/lib/External/isl/isl_ast.c' l='1258' u='m' c='isl_ast_node_if_set_then'/>
<use f='llvm/polly/lib/External/isl/isl_ast.c' l='1277' u='m' c='isl_ast_node_if_get_then_node'/>
<use f='llvm/polly/lib/External/isl/isl_ast.c' l='1297' u='m' c='isl_ast_node_if_has_else_node'/>
<use f='llvm/polly/lib/External/isl/isl_ast.c' l='1318' u='m' c='isl_ast_node_if_get_else_node'/>
<use f='llvm/polly/lib/External/isl/isl_ast.c' l='1337' u='m' c='isl_ast_node_if_get_cond'/>
<use f='llvm/polly/lib/External/isl/isl_ast.c' l='1469' u='m' c='isl_ast_node_foreach_descendant_top_down'/>
<use f='llvm/polly/lib/External/isl/isl_ast.c' l='1473' u='m' c='isl_ast_node_foreach_descendant_top_down'/>
<use f='llvm/polly/lib/External/isl/isl_ast.c' l='1475' u='m' c='isl_ast_node_foreach_descendant_top_down'/>
<use f='llvm/polly/lib/External/isl/isl_ast.c' l='2204' u='m' c='print_ast_node_isl'/>
<use f='llvm/polly/lib/External/isl/isl_ast.c' l='2206' u='m' c='print_ast_node_isl'/>
<use f='llvm/polly/lib/External/isl/isl_ast.c' l='2209' u='m' c='print_ast_node_isl'/>
<use f='llvm/polly/lib/External/isl/isl_ast.c' l='2212' u='m' c='print_ast_node_isl'/>
<use f='llvm/polly/lib/External/isl/isl_ast.c' l='2215' u='m' c='print_ast_node_isl'/>
<use f='llvm/polly/lib/External/isl/isl_ast.c' l='2250' u='m' c='need_block'/>
<use f='llvm/polly/lib/External/isl/isl_ast.c' l='2429' u='m' c='print_if_c'/>
<use f='llvm/polly/lib/External/isl/isl_ast.c' l='2431' u='m' c='print_if_c'/>
<use f='llvm/polly/lib/External/isl/isl_ast.c' l='2431' u='m' c='print_if_c'/>
<use f='llvm/polly/lib/External/isl/isl_ast.c' l='2662' u='m' c='ast_node_required_macros'/>
<use f='llvm/polly/lib/External/isl/isl_ast.c' l='2663' u='m' c='ast_node_required_macros'/>
<use f='llvm/polly/lib/External/isl/isl_ast.c' l='2664' u='m' c='ast_node_required_macros'/>
<use f='llvm/polly/lib/External/isl/isl_ast.c' l='2665' u='m' c='ast_node_required_macros'/>
<offset>0</offset>
<use f='llvm/polly/lib/External/isl/isl_ast_graft.c' l='513' u='m' c='extend_then'/>
<use f='llvm/polly/lib/External/isl/isl_ast_graft.c' l='524' u='m' c='extend_else'/>
