<dec f='llvm/polly/lib/External/isl/isl_map_private.h' l='112' type='struct isl_basic_map *[1]'/>
<offset>448</offset>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='4952' u='r' c='pw_multi_aff_from_map_base'/>
<use f='llvm/polly/lib/External/isl/isl_affine_hull.c' l='1163' u='w' c='isl_map_local_affine_hull'/>
<use f='llvm/polly/lib/External/isl/isl_affine_hull.c' l='1163' u='r' c='isl_map_local_affine_hull'/>
<use f='llvm/polly/lib/External/isl/isl_affine_hull.c' l='1164' u='w' c='isl_map_local_affine_hull'/>
<use f='llvm/polly/lib/External/isl/isl_affine_hull.c' l='1164' u='r' c='isl_map_local_affine_hull'/>
<use f='llvm/polly/lib/External/isl/isl_affine_hull.c' l='1165' u='w' c='isl_map_local_affine_hull'/>
<use f='llvm/polly/lib/External/isl/isl_affine_hull.c' l='1165' u='r' c='isl_map_local_affine_hull'/>
<use f='llvm/polly/lib/External/isl/isl_affine_hull.c' l='1166' u='r' c='isl_map_local_affine_hull'/>
<use f='llvm/polly/lib/External/isl/isl_affine_hull.c' l='1228' u='r' c='isl_map_affine_hull'/>
<use f='llvm/polly/lib/External/isl/isl_affine_hull.c' l='1236' u='w' c='isl_map_affine_hull'/>
<use f='llvm/polly/lib/External/isl/isl_affine_hull.c' l='1236' u='r' c='isl_map_affine_hull'/>
<use f='llvm/polly/lib/External/isl/isl_affine_hull.c' l='1236' u='r' c='isl_map_affine_hull'/>
<use f='llvm/polly/lib/External/isl/isl_affine_hull.c' l='1238' u='r' c='isl_map_affine_hull'/>
<use f='llvm/polly/lib/External/isl/isl_coalesce.c' l='4127' u='r' c='update_basic_maps'/>
<use f='llvm/polly/lib/External/isl/isl_coalesce.c' l='4129' u='w' c='update_basic_maps'/>
<use f='llvm/polly/lib/External/isl/isl_coalesce.c' l='4129' u='r' c='update_basic_maps'/>
<use f='llvm/polly/lib/External/isl/isl_coalesce.c' l='4146' u='r' c='update_basic_maps'/>
<use f='llvm/polly/lib/External/isl/isl_coalesce.c' l='4147' u='w' c='update_basic_maps'/>
<use f='llvm/polly/lib/External/isl/isl_coalesce.c' l='4207' u='w' c='isl_map_coalesce'/>
<use f='llvm/polly/lib/External/isl/isl_coalesce.c' l='4207' u='r' c='isl_map_coalesce'/>
<use f='llvm/polly/lib/External/isl/isl_coalesce.c' l='4208' u='r' c='isl_map_coalesce'/>
<use f='llvm/polly/lib/External/isl/isl_coalesce.c' l='4210' u='r' c='isl_map_coalesce'/>
<use f='llvm/polly/lib/External/isl/isl_convex_hull.c' l='129' u='r' c='uset_is_bound'/>
<use f='llvm/polly/lib/External/isl/isl_convex_hull.c' l='132' u='r' c='uset_is_bound'/>
<use f='llvm/polly/lib/External/isl/isl_convex_hull.c' l='139' u='w' c='uset_is_bound'/>
<use f='llvm/polly/lib/External/isl/isl_convex_hull.c' l='139' u='r' c='uset_is_bound'/>
<use f='llvm/polly/lib/External/isl/isl_convex_hull.c' l='140' u='r' c='uset_is_bound'/>
<use f='llvm/polly/lib/External/isl/isl_convex_hull.c' l='169' u='w' c='isl_set_add_basic_set_equality'/>
<use f='llvm/polly/lib/External/isl/isl_convex_hull.c' l='169' u='r' c='isl_set_add_basic_set_equality'/>
<use f='llvm/polly/lib/External/isl/isl_convex_hull.c' l='170' u='r' c='isl_set_add_basic_set_equality'/>
<use f='llvm/polly/lib/External/isl/isl_convex_hull.c' l='212' u='r' c='wrap_constraints'/>
<use f='llvm/polly/lib/External/isl/isl_convex_hull.c' l='213' u='r' c='wrap_constraints'/>
<use f='llvm/polly/lib/External/isl/isl_convex_hull.c' l='234' u='r' c='wrap_constraints'/>
<use f='llvm/polly/lib/External/isl/isl_convex_hull.c' l='237' u='r' c='wrap_constraints'/>
<use f='llvm/polly/lib/External/isl/isl_convex_hull.c' l='241' u='r' c='wrap_constraints'/>
<use f='llvm/polly/lib/External/isl/isl_convex_hull.c' l='244' u='r' c='wrap_constraints'/>
<use f='llvm/polly/lib/External/isl/isl_convex_hull.c' l='610' u='w' c='convex_hull_1d'/>
<use f='llvm/polly/lib/External/isl/isl_convex_hull.c' l='610' u='r' c='convex_hull_1d'/>
<use f='llvm/polly/lib/External/isl/isl_convex_hull.c' l='611' u='r' c='convex_hull_1d'/>
<use f='llvm/polly/lib/External/isl/isl_convex_hull.c' l='622' u='r' c='convex_hull_1d'/>
<use f='llvm/polly/lib/External/isl/isl_convex_hull.c' l='623' u='r' c='convex_hull_1d'/>
<use f='llvm/polly/lib/External/isl/isl_convex_hull.c' l='626' u='r' c='convex_hull_1d'/>
<use f='llvm/polly/lib/External/isl/isl_convex_hull.c' l='627' u='r' c='convex_hull_1d'/>
<use f='llvm/polly/lib/External/isl/isl_convex_hull.c' l='628' u='r' c='convex_hull_1d'/>
<use f='llvm/polly/lib/External/isl/isl_convex_hull.c' l='630' u='r' c='convex_hull_1d'/>
<use f='llvm/polly/lib/External/isl/isl_convex_hull.c' l='631' u='r' c='convex_hull_1d'/>
<use f='llvm/polly/lib/External/isl/isl_convex_hull.c' l='634' u='r' c='convex_hull_1d'/>
<use f='llvm/polly/lib/External/isl/isl_convex_hull.c' l='635' u='r' c='convex_hull_1d'/>
<use f='llvm/polly/lib/External/isl/isl_convex_hull.c' l='637' u='r' c='convex_hull_1d'/>
<use f='llvm/polly/lib/External/isl/isl_convex_hull.c' l='640' u='r' c='convex_hull_1d'/>
<use f='llvm/polly/lib/External/isl/isl_convex_hull.c' l='648' u='r' c='convex_hull_1d'/>
<use f='llvm/polly/lib/External/isl/isl_convex_hull.c' l='858' u='r' c='isl_set_is_bounded'/>
<use f='llvm/polly/lib/External/isl/isl_convex_hull.c' l='1414' u='r' c='isl_set_combined_lineality_space'/>
<use f='llvm/polly/lib/External/isl/isl_convex_hull.c' l='1628' u='r' c='common_constraints'/>
<use f='llvm/polly/lib/External/isl/isl_convex_hull.c' l='1636' u='r' c='common_constraints'/>
<use f='llvm/polly/lib/External/isl/isl_convex_hull.c' l='1639' u='r' c='common_constraints'/>
<use f='llvm/polly/lib/External/isl/isl_convex_hull.c' l='1644' u='r' c='common_constraints'/>
<use f='llvm/polly/lib/External/isl/isl_convex_hull.c' l='1646' u='r' c='common_constraints'/>
<use f='llvm/polly/lib/External/isl/isl_convex_hull.c' l='1660' u='r' c='common_constraints'/>
<use f='llvm/polly/lib/External/isl/isl_convex_hull.c' l='1662' u='r' c='common_constraints'/>
<use f='llvm/polly/lib/External/isl/isl_convex_hull.c' l='1684' u='r' c='common_constraints'/>
<use f='llvm/polly/lib/External/isl/isl_convex_hull.c' l='1685' u='r' c='common_constraints'/>
<use f='llvm/polly/lib/External/isl/isl_convex_hull.c' l='1693' u='r' c='common_constraints'/>
<use f='llvm/polly/lib/External/isl/isl_convex_hull.c' l='1694' u='r' c='common_constraints'/>
<use f='llvm/polly/lib/External/isl/isl_convex_hull.c' l='1696' u='r' c='common_constraints'/>
<use f='llvm/polly/lib/External/isl/isl_convex_hull.c' l='1714' u='r' c='common_constraints'/>
<use f='llvm/polly/lib/External/isl/isl_convex_hull.c' l='1716' u='r' c='common_constraints'/>
<use f='llvm/polly/lib/External/isl/isl_convex_hull.c' l='1718' u='r' c='common_constraints'/>
<use f='llvm/polly/lib/External/isl/isl_convex_hull.c' l='1720' u='r' c='common_constraints'/>
<use f='llvm/polly/lib/External/isl/isl_convex_hull.c' l='1727' u='r' c='common_constraints'/>
<use f='llvm/polly/lib/External/isl/isl_convex_hull.c' l='1760' u='r' c='proto_hull'/>
<use f='llvm/polly/lib/External/isl/isl_convex_hull.c' l='1761' u='r' c='proto_hull'/>
<use f='llvm/polly/lib/External/isl/isl_convex_hull.c' l='1811' u='r' c='uset_convex_hull'/>
<use f='llvm/polly/lib/External/isl/isl_convex_hull.c' l='1868' u='r' c='uset_convex_hull_wrap_bounded'/>
<use f='llvm/polly/lib/External/isl/isl_convex_hull.c' l='1946' u='r' c='isl_map_convex_hull'/>
<use f='llvm/polly/lib/External/isl/isl_convex_hull.c' l='2102' u='r' c='sh_data_alloc'/>
<use f='llvm/polly/lib/External/isl/isl_convex_hull.c' l='2102' u='r' c='sh_data_alloc'/>
<use f='llvm/polly/lib/External/isl/isl_convex_hull.c' l='2105' u='r' c='sh_data_alloc'/>
<use f='llvm/polly/lib/External/isl/isl_convex_hull.c' l='2131' u='r' c='is_bound'/>
<use f='llvm/polly/lib/External/isl/isl_convex_hull.c' l='2316' u='r' c='add_bounds'/>
<use f='llvm/polly/lib/External/isl/isl_convex_hull.c' l='2318' u='r' c='add_bounds'/>
<use f='llvm/polly/lib/External/isl/isl_convex_hull.c' l='2318' u='r' c='add_bounds'/>
<use f='llvm/polly/lib/External/isl/isl_convex_hull.c' l='2319' u='r' c='add_bounds'/>
<use f='llvm/polly/lib/External/isl/isl_convex_hull.c' l='2323' u='r' c='add_bounds'/>
<use f='llvm/polly/lib/External/isl/isl_convex_hull.c' l='2324' u='r' c='add_bounds'/>
<use f='llvm/polly/lib/External/isl/isl_convex_hull.c' l='2345' u='r' c='uset_simple_hull'/>
<use f='llvm/polly/lib/External/isl/isl_convex_hull.c' l='2347' u='r' c='uset_simple_hull'/>
<use f='llvm/polly/lib/External/isl/isl_convex_hull.c' l='2347' u='r' c='uset_simple_hull'/>
<use f='llvm/polly/lib/External/isl/isl_convex_hull.c' l='2386' u='r' c='map_simple_hull_trivial'/>
<use f='llvm/polly/lib/External/isl/isl_convex_hull.c' l='2447' u='r' c='map_simple_hull'/>
<use f='llvm/polly/lib/External/isl/isl_convex_hull.c' l='2662' u='r' c='isl_map_plain_unshifted_simple_hull'/>
<use f='llvm/polly/lib/External/isl/isl_convex_hull.c' l='2666' u='r' c='isl_map_plain_unshifted_simple_hull'/>
<use f='llvm/polly/lib/External/isl/isl_convex_hull.c' l='2978' u='r' c='map_unshifted_simple_hull_from_basic_map_list'/>
<use f='llvm/polly/lib/External/isl/isl_equalities.c' l='833' u='r' c='isl_set_dim_residue_class'/>
<use f='llvm/polly/lib/External/isl/isl_equalities.c' l='846' u='r' c='isl_set_dim_residue_class'/>
<use f='llvm/polly/lib/External/isl/isl_farkas.c' l='906' u='r' c='isl_set_coefficients'/>
<use f='llvm/polly/lib/External/isl/isl_farkas.c' l='910' u='r' c='isl_set_coefficients'/>
<use f='llvm/polly/lib/External/isl/isl_farkas.c' l='955' u='r' c='isl_set_solutions'/>
<use f='llvm/polly/lib/External/isl/isl_farkas.c' l='959' u='r' c='isl_set_solutions'/>
<use f='llvm/polly/lib/External/isl/isl_pw_lift_templ.c' l='27' u='r' c='foreach_lifted_subset'/>
<use f='llvm/polly/lib/External/isl/isl_ilp.c' l='442' u='r' c='isl_set_opt_aligned'/>
<use f='llvm/polly/lib/External/isl/isl_ilp.c' l='452' u='r' c='isl_set_opt_aligned'/>
<use f='llvm/polly/lib/External/isl/isl_input.c' l='3130' u='r' c='basic_map_read'/>
<use f='llvm/polly/lib/External/isl/isl_lp.c' l='108' u='r' c='isl_map_solve_lp'/>
<use f='llvm/polly/lib/External/isl/isl_lp.c' l='109' u='r' c='isl_map_solve_lp'/>
<use f='llvm/polly/lib/External/isl/isl_lp.c' l='133' u='r' c='isl_map_solve_lp'/>
<use f='llvm/polly/lib/External/isl/isl_lp.c' l='146' u='r' c='isl_map_solve_lp'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='675' u='w' c='isl_map_set_tuple_name'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='675' u='r' c='isl_map_set_tuple_name'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='676' u='r' c='isl_map_set_tuple_name'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='876' u='w' c='isl_map_set_dim_name'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='876' u='r' c='isl_map_set_dim_name'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='877' u='r' c='isl_map_set_dim_name'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='1092' u='r' c='isl_map_is_rational'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='1098' u='r' c='isl_map_is_rational'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='1180' u='r' c='isl_map_has_rational'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='2204' u='w' c='isl_map_set_rational'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='2204' u='r' c='isl_map_set_rational'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='2205' u='r' c='isl_map_set_rational'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='2427' u='w' c='isl_map_drop'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='2427' u='r' c='isl_map_drop'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='2428' u='r' c='isl_map_drop'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='2481' u='w' c='isl_map_eliminate'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='2481' u='r' c='isl_map_eliminate'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='2482' u='r' c='isl_map_eliminate'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='2546' u='w' c='isl_map_remove_divs'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='2546' u='r' c='isl_map_remove_divs'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='2547' u='r' c='isl_map_remove_divs'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='2852' u='w' c='isl_map_remove_divs_involving_dims'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='2852' u='r' c='isl_map_remove_divs_involving_dims'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='2854' u='r' c='isl_map_remove_divs_involving_dims'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='2910' u='r' c='isl_map_involves_dims'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='3110' u='w' c='drop_constraints'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='3110' u='r' c='drop_constraints'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='3111' u='r' c='drop_constraints'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='3243' u='w' c='isl_map_remove_unknown_divs'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='3243' u='r' c='isl_map_remove_unknown_divs'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='3244' u='r' c='isl_map_remove_unknown_divs'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='3280' u='w' c='isl_map_remove_dims'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='3280' u='r' c='isl_map_remove_dims'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='3281' u='r' c='isl_map_remove_dims'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='3282' u='r' c='isl_map_remove_dims'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='3401' u='w' c='isl_map_grow'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='3401' u='r' c='isl_map_grow'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='3402' u='r' c='isl_map_grow'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='3465' u='r' c='isl_set_print_internal'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='3486' u='r' c='isl_map_print_internal'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='3724' u='r' c='map_intersect_add_constraint'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='3725' u='r' c='map_intersect_add_constraint'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='3727' u='r' c='map_intersect_add_constraint'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='3727' u='r' c='map_intersect_add_constraint'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='3737' u='r' c='map_intersect_add_constraint'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='3738' u='w' c='map_intersect_add_constraint'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='3738' u='r' c='map_intersect_add_constraint'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='3738' u='r' c='map_intersect_add_constraint'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='3740' u='w' c='map_intersect_add_constraint'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='3740' u='r' c='map_intersect_add_constraint'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='3741' u='r' c='map_intersect_add_constraint'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='3743' u='w' c='map_intersect_add_constraint'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='3743' u='r' c='map_intersect_add_constraint'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='3744' u='w' c='map_intersect_add_constraint'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='3744' u='r' c='map_intersect_add_constraint'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='3745' u='r' c='map_intersect_add_constraint'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='3748' u='r' c='map_intersect_add_constraint'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='3749' u='r' c='map_intersect_add_constraint'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='3792' u='r' c='map_intersect_internal'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='3792' u='r' c='map_intersect_internal'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='3794' u='r' c='map_intersect_internal'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='3794' u='r' c='map_intersect_internal'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='3795' u='r' c='map_intersect_internal'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='3795' u='r' c='map_intersect_internal'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='3826' u='r' c='map_intersect_internal'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='3827' u='r' c='map_intersect_internal'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='4069' u='w' c='isl_map_insert_dims'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='4069' u='r' c='isl_map_insert_dims'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='4070' u='r' c='isl_map_insert_dims'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='4258' u='w' c='isl_map_move_dims'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='4258' u='r' c='isl_map_move_dims'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='4261' u='r' c='isl_map_move_dims'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='4493' u='w' c='isl_map_project_out'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='4493' u='r' c='isl_map_project_out'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='4494' u='r' c='isl_map_project_out'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='4839' u='r' c='isl_map_sum'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='4840' u='r' c='isl_map_sum'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='4906' u='w' c='isl_map_neg'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='4906' u='r' c='isl_map_neg'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='4907' u='r' c='isl_map_neg'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='4989' u='w' c='isl_map_floordiv'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='4989' u='r' c='isl_map_floordiv'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='4990' u='r' c='isl_map_floordiv'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='5691' u='r' c='isl_map_underlying_set'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='5691' u='r' c='isl_map_underlying_set'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='5694' u='w' c='isl_map_underlying_set'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='5695' u='r' c='isl_map_underlying_set'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='5696' u='r' c='isl_map_underlying_set'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='5703' u='r' c='isl_map_underlying_set'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='5780' u='w' c='isl_map_reset_space'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='5780' u='r' c='isl_map_reset_space'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='5782' u='r' c='isl_map_reset_space'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='6061' u='w' c='isl_map_transform'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='6061' u='r' c='isl_map_transform'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='6062' u='r' c='isl_map_transform'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='6299' u='r' c='isl_map_dup'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='6315' u='w' c='isl_map_add_basic_map'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='6340' u='r' c='isl_map_free'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='6471' u='r' c='remove_if_empty'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='6477' u='r' c='remove_if_empty'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='6480' u='w' c='remove_if_empty'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='6480' u='r' c='remove_if_empty'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='6505' u='r' c='isl_map_inline_foreach_basic_map'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='6509' u='r' c='isl_map_inline_foreach_basic_map'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='6510' u='w' c='isl_map_inline_foreach_basic_map'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='6531' u='w' c='isl_map_fix_si'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='6531' u='r' c='isl_map_fix_si'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='6555' u='w' c='isl_map_fix'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='6555' u='r' c='isl_map_fix'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='6556' u='r' c='isl_map_fix'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='6590' u='w' c='isl_map_fix_val'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='6590' u='r' c='isl_map_fix_val'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='6685' u='w' c='map_bound_si'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='6685' u='r' c='map_bound_si'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='6687' u='r' c='map_bound_si'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='6770' u='w' c='map_bound'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='6770' u='r' c='map_bound'/>
<use f='llvm/polly/lib/External/isl/isl_map_lexopt_templ.c' l='113' u='r' c='basic_map_partial_lexopt_pw_multi_aff'/>
<use f='llvm/polly/lib/External/isl/isl_map_lexopt_templ.c' l='122' u='r' c='basic_map_partial_lexopt_pw_multi_aff'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='7151' u='r' c='isl_map_partial_lexopt_aligned_pw_multi_aff'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='7160' u='r' c='isl_map_partial_lexopt_aligned_pw_multi_aff'/>
<use f='llvm/polly/lib/External/isl/isl_map_lexopt_templ.c' l='113' u='r' c='basic_map_partial_lexopt'/>
<use f='llvm/polly/lib/External/isl/isl_map_lexopt_templ.c' l='122' u='r' c='basic_map_partial_lexopt'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='7241' u='r' c='isl_map_partial_lexopt_aligned'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='7373' u='r' c='map_dim_opt'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='7377' u='r' c='map_dim_opt'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='7546' u='w' c='set_append_equalities'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='7546' u='r' c='set_append_equalities'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='7548' u='r' c='set_append_equalities'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='7779' u='w' c='replace_space_by_local_space'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='7779' u='r' c='replace_space_by_local_space'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='7781' u='r' c='replace_space_by_local_space'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='7953' u='r' c='isl_map_divs_known'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='8011' u='r' c='isl_map_compute_divs'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='8014' u='r' c='isl_map_compute_divs'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='8106' u='r' c='map_union_disjoint'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='8112' u='r' c='map_union_disjoint'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='8220' u='r' c='map_intersect_set'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='8221' u='r' c='map_intersect_set'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='8498' u='r' c='isl_map_apply_range'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='8499' u='r' c='isl_map_apply_range'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='8658' u='r' c='isl_map_deltas'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='9010' u='r' c='isl_map_is_empty'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='9232' u='r' c='isl_map_plain_is_universe'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='9395' u='w' c='isl_map_order_divs'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='9395' u='r' c='isl_map_order_divs'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='9396' u='r' c='isl_map_order_divs'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='9607' u='w' c='isl_map_align_divs_internal'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='9607' u='r' c='isl_map_align_divs_internal'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='9607' u='r' c='isl_map_align_divs_internal'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='9609' u='w' c='isl_map_align_divs_internal'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='9609' u='r' c='isl_map_align_divs_internal'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='9609' u='r' c='isl_map_align_divs_internal'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='9610' u='r' c='isl_map_align_divs_internal'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='9651' u='w' c='isl_map_align_divs_to_basic_map_list'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='9651' u='r' c='isl_map_align_divs_to_basic_map_list'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='9654' u='r' c='isl_map_align_divs_to_basic_map_list'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='9891' u='r' c='isl_set_follows_at'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='9891' u='r' c='isl_set_follows_at'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='9943' u='r' c='isl_map_plain_has_fixed_var'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='9946' u='r' c='isl_map_plain_has_fixed_var'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='9948' u='r' c='isl_map_plain_has_fixed_var'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='10261' u='r' c='isl_set_plain_cmp'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='10261' u='r' c='isl_set_plain_cmp'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='10305' u='r' c='sort_and_remove_duplicates'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='10307' u='r' c='sort_and_remove_duplicates'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='10307' u='r' c='sort_and_remove_duplicates'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='10309' u='r' c='sort_and_remove_duplicates'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='10311' u='w' c='sort_and_remove_duplicates'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='10311' u='r' c='sort_and_remove_duplicates'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='10340' u='r' c='isl_map_remove_obvious_duplicates'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='10344' u='r' c='isl_map_remove_obvious_duplicates'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='10345' u='w' c='isl_map_remove_obvious_duplicates'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='10366' u='r' c='isl_map_normalize'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='10369' u='r' c='isl_map_normalize'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='10370' u='w' c='isl_map_normalize'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='10410' u='r' c='isl_map_plain_is_equal'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='10410' u='r' c='isl_map_plain_is_equal'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='10446' u='r' c='isl_map_get_basic_map_list'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='10774' u='r' c='map_product'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='10775' u='r' c='map_product'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='11090' u='r' c='isl_map_get_hash'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='11125' u='r' c='isl_map_foreach_basic_map'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='11140' u='r' c='isl_set_foreach_basic_set'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='11160' u='r' c='isl_set_every_basic_set'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='11183' u='r' c='isl_set_get_basic_set_list'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='11233' u='r' c='isl_set_lift'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='11242' u='w' c='isl_set_lift'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='11242' u='r' c='isl_set_lift'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='11243' u='r' c='isl_set_lift'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='11277' u='r' c='isl_set_size'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='11345' u='r' c='isl_map_dim_is_bounded'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='11376' u='r' c='has_any_bound'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='11416' u='r' c='has_bound'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='11805' u='r' c='isl_map_plain_is_single_valued'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='11977' u='r' c='isl_set_is_box'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='12130' u='w' c='isl_map_reset'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='12130' u='r' c='isl_map_reset'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='12131' u='r' c='isl_map_reset'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='12299' u='r' c='isl_map_realign'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='12302' u='w' c='isl_map_realign'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='12302' u='r' c='isl_map_realign'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='12304' u='r' c='isl_map_realign'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='13515' u='w' c='isl_set_substitute'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='13515' u='r' c='isl_set_substitute'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='13944' u='w' c='map_preimage_multi_aff'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='13944' u='r' c='map_preimage_multi_aff'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='13946' u='r' c='map_preimage_multi_aff'/>
<use f='llvm/polly/lib/External/isl/isl_map_simplify.c' l='1942' u='w' c='isl_map_drop_constraints_involving_unknown_divs'/>
<use f='llvm/polly/lib/External/isl/isl_map_simplify.c' l='1944' u='r' c='isl_map_drop_constraints_involving_unknown_divs'/>
<use f='llvm/polly/lib/External/isl/isl_map_simplify.c' l='1945' u='r' c='isl_map_drop_constraints_involving_unknown_divs'/>
<use f='llvm/polly/lib/External/isl/isl_map_simplify.c' l='3357' u='w' c='isl_map_gist_basic_map'/>
<use f='llvm/polly/lib/External/isl/isl_map_simplify.c' l='3357' u='r' c='isl_map_gist_basic_map'/>
<use f='llvm/polly/lib/External/isl/isl_map_simplify.c' l='3359' u='r' c='isl_map_gist_basic_map'/>
<use f='llvm/polly/lib/External/isl/isl_map_simplify.c' l='3361' u='r' c='isl_map_gist_basic_map'/>
<use f='llvm/polly/lib/External/isl/isl_map_simplify.c' l='3362' u='r' c='isl_map_gist_basic_map'/>
<use f='llvm/polly/lib/External/isl/isl_map_simplify.c' l='3364' u='w' c='isl_map_gist_basic_map'/>
<use f='llvm/polly/lib/External/isl/isl_map_simplify.c' l='3364' u='r' c='isl_map_gist_basic_map'/>
<use f='llvm/polly/lib/External/isl/isl_map_simplify.c' l='3550' u='r' c='replace_by_disjunct'/>
<use f='llvm/polly/lib/External/isl/isl_map_simplify.c' l='3586' u='w' c='isl_map_plain_gist_basic_map'/>
<use f='llvm/polly/lib/External/isl/isl_map_simplify.c' l='3586' u='r' c='isl_map_plain_gist_basic_map'/>
<use f='llvm/polly/lib/External/isl/isl_map_simplify.c' l='3588' u='r' c='isl_map_plain_gist_basic_map'/>
<use f='llvm/polly/lib/External/isl/isl_map_simplify.c' l='3895' u='r' c='all_pairs'/>
<use f='llvm/polly/lib/External/isl/isl_map_simplify.c' l='3895' u='r' c='all_pairs'/>
<use f='llvm/polly/lib/External/isl/isl_map_subtract.c' l='386' u='r' c='basic_map_collect_diff'/>
<use f='llvm/polly/lib/External/isl/isl_map_subtract.c' l='393' u='r' c='basic_map_collect_diff'/>
<use f='llvm/polly/lib/External/isl/isl_map_subtract.c' l='416' u='r' c='basic_map_collect_diff'/>
<use f='llvm/polly/lib/External/isl/isl_map_subtract.c' l='428' u='r' c='basic_map_collect_diff'/>
<use f='llvm/polly/lib/External/isl/isl_map_subtract.c' l='434' u='r' c='basic_map_collect_diff'/>
<use f='llvm/polly/lib/External/isl/isl_map_subtract.c' l='570' u='r' c='isl_map_subtract'/>
<use f='llvm/polly/lib/External/isl/isl_map_subtract.c' l='704' u='r' c='map_diff_is_empty'/>
<use f='llvm/polly/lib/External/isl/isl_map_subtract.c' l='739' u='r' c='isl_map_plain_is_singleton'/>
<use f='llvm/polly/lib/External/isl/isl_map_subtract.c' l='813' u='r' c='map_is_singleton_subset'/>
<use f='llvm/polly/lib/External/isl/isl_map_subtract.c' l='818' u='r' c='map_is_singleton_subset'/>
<use f='llvm/polly/lib/External/isl/isl_map_subtract.c' l='907' u='r' c='isl_map_make_disjoint'/>
<use f='llvm/polly/lib/External/isl/isl_map_subtract.c' l='910' u='r' c='isl_map_make_disjoint'/>
<use f='llvm/polly/lib/External/isl/isl_mat.c' l='1426' u='w' c='isl_set_preimage'/>
<use f='llvm/polly/lib/External/isl/isl_mat.c' l='1426' u='r' c='isl_set_preimage'/>
<use f='llvm/polly/lib/External/isl/isl_mat.c' l='1428' u='r' c='isl_set_preimage'/>
<use f='llvm/polly/lib/External/isl/isl_output.c' l='171' u='r' c='isl_map_print_polylib'/>
<use f='llvm/polly/lib/External/isl/isl_output.c' l='1068' u='r' c='isl_map_print_omega'/>
<use f='llvm/polly/lib/External/isl/isl_output.c' l='1081' u='r' c='isl_set_print_omega'/>
<use f='llvm/polly/lib/External/isl/isl_output.c' l='1136' u='r' c='print_disjuncts_core'/>
<use f='llvm/polly/lib/External/isl/isl_output.c' l='1136' u='r' c='print_disjuncts_core'/>
<use f='llvm/polly/lib/External/isl/isl_output.c' l='1138' u='r' c='print_disjuncts_core'/>
<use f='llvm/polly/lib/External/isl/isl_output.c' l='1139' u='r' c='print_disjuncts_core'/>
<use f='llvm/polly/lib/External/isl/isl_output.c' l='1139' u='r' c='print_disjuncts_core'/>
<use f='llvm/polly/lib/External/isl/isl_output.c' l='1349' u='r' c='split_aff'/>
<use f='llvm/polly/lib/External/isl/isl_output.c' l='1350' u='r' c='split_aff'/>
<use f='llvm/polly/lib/External/isl/isl_output.c' l='1448' u='r' c='print_split_map'/>
<use f='llvm/polly/lib/External/isl/isl_output.c' l='1474' u='r' c='isl_map_print_isl_body'/>
<use f='llvm/polly/lib/External/isl/isl_output.c' l='2239' u='r' c='print_set_c'/>
<use f='llvm/polly/lib/External/isl/isl_point.c' l='537' u='r' c='isl_set_foreach_point'/>
<use f='llvm/polly/lib/External/isl/isl_point.c' l='594' u='r' c='isl_map_contains_point'/>
<use f='llvm/polly/lib/External/isl/isl_sample.c' l='1278' u='r' c='isl_map_sample'/>
<use f='llvm/polly/lib/External/isl/isl_sample.c' l='1320' u='r' c='isl_set_sample_point'/>
<use f='llvm/polly/lib/External/isl/isl_scan.c' l='240' u='r' c='isl_set_scan'/>
<use f='llvm/polly/lib/External/isl/isl_tab_pip.c' l='4811' u='r' c='need_split_set'/>
<use f='llvm/polly/lib/External/isl/isl_tab_pip.c' l='4852' u='r' c='split_domain'/>
<use f='llvm/polly/lib/External/isl/isl_tab_pip.c' l='4853' u='r' c='split_domain'/>
<use f='llvm/polly/lib/External/isl/isl_test.c' l='1972' u='r' c='test_gist'/>
<use f='llvm/polly/lib/External/isl/isl_transitive_closure.c' l='795' u='r' c='construct_extended_path'/>
<use f='llvm/polly/lib/External/isl/isl_transitive_closure.c' l='1058' u='r' c='composability'/>
<use f='llvm/polly/lib/External/isl/isl_transitive_closure.c' l='1081' u='r' c='composability'/>
<use f='llvm/polly/lib/External/isl/isl_transitive_closure.c' l='1128' u='r' c='compose'/>
<use f='llvm/polly/lib/External/isl/isl_transitive_closure.c' l='1172' u='r' c='compute_incremental'/>
<use f='llvm/polly/lib/External/isl/isl_transitive_closure.c' l='1251' u='r' c='incremental_on_entire_domain'/>
<use f='llvm/polly/lib/External/isl/isl_transitive_closure.c' l='1253' u='r' c='incremental_on_entire_domain'/>
<use f='llvm/polly/lib/External/isl/isl_transitive_closure.c' l='1255' u='r' c='incremental_on_entire_domain'/>
<use f='llvm/polly/lib/External/isl/isl_transitive_closure.c' l='1351' u='r' c='incremental_closure'/>
<use f='llvm/polly/lib/External/isl/isl_transitive_closure.c' l='1357' u='r' c='incremental_closure'/>
<use f='llvm/polly/lib/External/isl/isl_transitive_closure.c' l='1376' u='r' c='incremental_closure'/>
<use f='llvm/polly/lib/External/isl/isl_transitive_closure.c' l='1630' u='r' c='floyd_warshall_with_groups'/>
<use f='llvm/polly/lib/External/isl/isl_transitive_closure.c' l='1751' u='r' c='floyd_warshall'/>
<use f='llvm/polly/lib/External/isl/isl_transitive_closure.c' l='1895' u='r' c='construct_power_components'/>
<use f='llvm/polly/lib/External/isl/isl_transitive_closure.c' l='1919' u='r' c='construct_power_components'/>
<use f='llvm/polly/lib/External/isl/isl_transitive_closure.c' l='2412' u='r' c='can_be_split_off'/>
<use f='llvm/polly/lib/External/isl/isl_transitive_closure.c' l='2429' u='r' c='can_be_split_off'/>
<use f='llvm/polly/lib/External/isl/isl_transitive_closure.c' l='2526' u='r' c='transitive_closure_omega'/>
<use f='llvm/polly/lib/External/isl/isl_transitive_closure.c' l='2607' u='r' c='collect_basic_map'/>
