<dec f='llvm/polly/lib/External/isl/isl_map_private.h' l='67' type='isl_int **'/>
<use f='llvm/polly/lib/External/isl/basis_reduction_templ.c' l='337' u='r' c='isl_basic_set_reduced_basis'/>
<offset>384</offset>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='2189' u='r' c='isl_aff_substitute_equalities_lifted'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='2193' u='r' c='isl_aff_substitute_equalities_lifted'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='4781' u='r' c='extract_aff_from_equality'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='4782' u='r' c='extract_aff_from_equality'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='4784' u='r' c='extract_aff_from_equality'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='4786' u='r' c='extract_aff_from_equality'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='4788' u='r' c='extract_aff_from_equality'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='4792' u='r' c='extract_aff_from_equality'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='4793' u='r' c='extract_aff_from_equality'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='4794' u='r' c='extract_aff_from_equality'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='4807' u='r' c='extract_aff_from_equality'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='5309' u='r' c='pw_multi_aff_from_map_stride'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='5310' u='r' c='pw_multi_aff_from_map_stride'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='5313' u='r' c='pw_multi_aff_from_map_stride'/>
<use f='llvm/polly/lib/External/isl/isl_aff.c' l='5387' u='r' c='pw_multi_aff_from_map_check_strides'/>
<use f='llvm/polly/lib/External/isl/isl_aff_map.c' l='90' u='r' c='isl_basic_map_from_aff2'/>
<use f='llvm/polly/lib/External/isl/isl_aff_map.c' l='91' u='r' c='isl_basic_map_from_aff2'/>
<use f='llvm/polly/lib/External/isl/isl_aff_map.c' l='92' u='r' c='isl_basic_map_from_aff2'/>
<use f='llvm/polly/lib/External/isl/isl_affine_hull.c' l='80' u='r' c='set_common_multiple'/>
<use f='llvm/polly/lib/External/isl/isl_affine_hull.c' l='80' u='r' c='set_common_multiple'/>
<use f='llvm/polly/lib/External/isl/isl_affine_hull.c' l='85' u='r' c='set_common_multiple'/>
<use f='llvm/polly/lib/External/isl/isl_affine_hull.c' l='85' u='r' c='set_common_multiple'/>
<use f='llvm/polly/lib/External/isl/isl_affine_hull.c' l='86' u='r' c='set_common_multiple'/>
<use f='llvm/polly/lib/External/isl/isl_affine_hull.c' l='87' u='r' c='set_common_multiple'/>
<use f='llvm/polly/lib/External/isl/isl_affine_hull.c' l='87' u='r' c='set_common_multiple'/>
<use f='llvm/polly/lib/External/isl/isl_affine_hull.c' l='88' u='r' c='set_common_multiple'/>
<use f='llvm/polly/lib/External/isl/isl_affine_hull.c' l='89' u='r' c='set_common_multiple'/>
<use f='llvm/polly/lib/External/isl/isl_affine_hull.c' l='89' u='r' c='set_common_multiple'/>
<use f='llvm/polly/lib/External/isl/isl_affine_hull.c' l='101' u='r' c='delete_row'/>
<use f='llvm/polly/lib/External/isl/isl_affine_hull.c' l='104' u='r' c='delete_row'/>
<use f='llvm/polly/lib/External/isl/isl_affine_hull.c' l='104' u='r' c='delete_row'/>
<use f='llvm/polly/lib/External/isl/isl_affine_hull.c' l='105' u='r' c='delete_row'/>
<use f='llvm/polly/lib/External/isl/isl_affine_hull.c' l='133' u='r' c='construct_column'/>
<use f='llvm/polly/lib/External/isl/isl_affine_hull.c' l='135' u='r' c='construct_column'/>
<use f='llvm/polly/lib/External/isl/isl_affine_hull.c' l='135' u='r' c='construct_column'/>
<use f='llvm/polly/lib/External/isl/isl_affine_hull.c' l='136' u='r' c='construct_column'/>
<use f='llvm/polly/lib/External/isl/isl_affine_hull.c' l='137' u='r' c='construct_column'/>
<use f='llvm/polly/lib/External/isl/isl_affine_hull.c' l='138' u='r' c='construct_column'/>
<use f='llvm/polly/lib/External/isl/isl_affine_hull.c' l='138' u='r' c='construct_column'/>
<use f='llvm/polly/lib/External/isl/isl_affine_hull.c' l='139' u='r' c='construct_column'/>
<use f='llvm/polly/lib/External/isl/isl_affine_hull.c' l='140' u='r' c='construct_column'/>
<use f='llvm/polly/lib/External/isl/isl_affine_hull.c' l='140' u='r' c='construct_column'/>
<use f='llvm/polly/lib/External/isl/isl_affine_hull.c' l='167' u='r' c='transform_column'/>
<use f='llvm/polly/lib/External/isl/isl_affine_hull.c' l='167' u='r' c='transform_column'/>
<use f='llvm/polly/lib/External/isl/isl_affine_hull.c' l='178' u='r' c='transform_column'/>
<use f='llvm/polly/lib/External/isl/isl_affine_hull.c' l='178' u='r' c='transform_column'/>
<use f='llvm/polly/lib/External/isl/isl_affine_hull.c' l='180' u='r' c='transform_column'/>
<use f='llvm/polly/lib/External/isl/isl_affine_hull.c' l='180' u='r' c='transform_column'/>
<use f='llvm/polly/lib/External/isl/isl_affine_hull.c' l='184' u='r' c='transform_column'/>
<use f='llvm/polly/lib/External/isl/isl_affine_hull.c' l='184' u='r' c='transform_column'/>
<use f='llvm/polly/lib/External/isl/isl_affine_hull.c' l='184' u='r' c='transform_column'/>
<use f='llvm/polly/lib/External/isl/isl_affine_hull.c' l='186' u='r' c='transform_column'/>
<use f='llvm/polly/lib/External/isl/isl_affine_hull.c' l='186' u='r' c='transform_column'/>
<use f='llvm/polly/lib/External/isl/isl_affine_hull.c' l='186' u='r' c='transform_column'/>
<use f='llvm/polly/lib/External/isl/isl_affine_hull.c' l='219' u='r' c='affine_hull'/>
<use f='llvm/polly/lib/External/isl/isl_affine_hull.c' l='221' u='r' c='affine_hull'/>
<use f='llvm/polly/lib/External/isl/isl_affine_hull.c' l='334' u='r' c='isl_basic_set_recession_cone'/>
<use f='llvm/polly/lib/External/isl/isl_affine_hull.c' l='439' u='r' c='extend_affine_hull'/>
<use f='llvm/polly/lib/External/isl/isl_affine_hull.c' l='445' u='r' c='extend_affine_hull'/>
<use f='llvm/polly/lib/External/isl/isl_affine_hull.c' l='452' u='r' c='extend_affine_hull'/>
<use f='llvm/polly/lib/External/isl/isl_affine_hull.c' l='598' u='r' c='initial_hull'/>
<use f='llvm/polly/lib/External/isl/isl_affine_hull.c' l='600' u='r' c='initial_hull'/>
<use f='llvm/polly/lib/External/isl/isl_affine_hull.c' l='601' u='r' c='initial_hull'/>
<use f='llvm/polly/lib/External/isl/isl_affine_hull.c' l='602' u='r' c='initial_hull'/>
<use f='llvm/polly/lib/External/isl/isl_affine_hull.c' l='602' u='r' c='initial_hull'/>
<use f='llvm/polly/lib/External/isl/isl_affine_hull.c' l='684' u='r' c='isl_tab_detect_equalities'/>
<use f='llvm/polly/lib/External/isl/isl_affine_hull.c' l='685' u='r' c='isl_tab_detect_equalities'/>
<use f='llvm/polly/lib/External/isl/isl_affine_hull.c' l='744' u='r' c='affine_hull_with_cone'/>
<use f='llvm/polly/lib/External/isl/isl_affine_hull.c' l='936' u='r' c='isl_basic_map_detect_equalities'/>
<use f='llvm/polly/lib/External/isl/isl_affine_hull.c' l='936' u='r' c='isl_basic_map_detect_equalities'/>
<use f='llvm/polly/lib/External/isl/isl_affine_hull.c' l='1049' u='r' c='add_strides'/>
<use f='llvm/polly/lib/External/isl/isl_affine_hull.c' l='1050' u='r' c='add_strides'/>
<use f='llvm/polly/lib/External/isl/isl_affine_hull.c' l='1051' u='r' c='add_strides'/>
<use f='llvm/polly/lib/External/isl/isl_affine_hull.c' l='1117' u='r' c='isl_basic_map_make_strides_explicit'/>
<use f='llvm/polly/lib/External/isl/isl_affine_hull.c' l='1123' u='r' c='isl_basic_map_make_strides_explicit'/>
<use f='llvm/polly/lib/External/isl/isl_affine_hull.c' l='1125' u='r' c='isl_basic_map_make_strides_explicit'/>
<use f='llvm/polly/lib/External/isl/isl_bernstein.c' l='53' u='r' c='vertex_is_integral'/>
<use f='llvm/polly/lib/External/isl/isl_bernstein.c' l='54' u='r' c='vertex_is_integral'/>
<use f='llvm/polly/lib/External/isl/isl_bernstein.c' l='80' u='r' c='vertex_coordinate'/>
<use f='llvm/polly/lib/External/isl/isl_bernstein.c' l='84' u='r' c='vertex_coordinate'/>
<use f='llvm/polly/lib/External/isl/isl_bernstein.c' l='84' u='r' c='vertex_coordinate'/>
<use f='llvm/polly/lib/External/isl/isl_bernstein.c' l='88' u='r' c='vertex_coordinate'/>
<use f='llvm/polly/lib/External/isl/isl_coalesce.c' l='84' u='r' c='eq_status_in'/>
<use f='llvm/polly/lib/External/isl/isl_coalesce.c' l='84' u='r' c='eq_status_in'/>
<use f='llvm/polly/lib/External/isl/isl_coalesce.c' l='85' u='r' c='eq_status_in'/>
<use f='llvm/polly/lib/External/isl/isl_coalesce.c' l='443' u='r' c='add_valid_constraints'/>
<use f='llvm/polly/lib/External/isl/isl_coalesce.c' l='443' u='r' c='add_valid_constraints'/>
<use f='llvm/polly/lib/External/isl/isl_coalesce.c' l='448' u='r' c='add_valid_constraints'/>
<use f='llvm/polly/lib/External/isl/isl_coalesce.c' l='453' u='r' c='add_valid_constraints'/>
<use f='llvm/polly/lib/External/isl/isl_coalesce.c' l='682' u='r' c='contains'/>
<use f='llvm/polly/lib/External/isl/isl_coalesce.c' l='682' u='r' c='contains'/>
<use f='llvm/polly/lib/External/isl/isl_coalesce.c' l='683' u='r' c='contains'/>
<use f='llvm/polly/lib/External/isl/isl_coalesce.c' l='684' u='r' c='contains'/>
<use f='llvm/polly/lib/External/isl/isl_coalesce.c' l='684' u='r' c='contains'/>
<use f='llvm/polly/lib/External/isl/isl_coalesce.c' l='689' u='r' c='contains'/>
<use f='llvm/polly/lib/External/isl/isl_coalesce.c' l='1197' u='r' c='wraps_update_max'/>
<use f='llvm/polly/lib/External/isl/isl_coalesce.c' l='1378' u='r' c='add_selected_wraps'/>
<use f='llvm/polly/lib/External/isl/isl_coalesce.c' l='1380' u='r' c='add_selected_wraps'/>
<use f='llvm/polly/lib/External/isl/isl_coalesce.c' l='1386' u='r' c='add_selected_wraps'/>
<use f='llvm/polly/lib/External/isl/isl_coalesce.c' l='1893' u='r' c='try_wrap_in_facets'/>
<use f='llvm/polly/lib/External/isl/isl_coalesce.c' l='1896' u='r' c='try_wrap_in_facets'/>
<use f='llvm/polly/lib/External/isl/isl_coalesce.c' l='2070' u='r' c='can_wrap_in_set'/>
<use f='llvm/polly/lib/External/isl/isl_coalesce.c' l='2071' u='r' c='can_wrap_in_set'/>
<use f='llvm/polly/lib/External/isl/isl_coalesce.c' l='2073' u='r' c='can_wrap_in_set'/>
<use f='llvm/polly/lib/External/isl/isl_coalesce.c' l='2075' u='r' c='can_wrap_in_set'/>
<use f='llvm/polly/lib/External/isl/isl_coalesce.c' l='2076' u='r' c='can_wrap_in_set'/>
<use f='llvm/polly/lib/External/isl/isl_coalesce.c' l='2320' u='r' c='check_eq_adj_eq'/>
<use f='llvm/polly/lib/External/isl/isl_coalesce.c' l='2322' u='r' c='check_eq_adj_eq'/>
<use f='llvm/polly/lib/External/isl/isl_constraint.c' l='101' u='r' c='isl_basic_map_constraint'/>
<use f='llvm/polly/lib/External/isl/isl_constraint.c' l='220' u='r' c='isl_basic_map_foreach_constraint'/>
<use f='llvm/polly/lib/External/isl/isl_constraint.c' l='740' u='r' c='isl_basic_map_from_constraint'/>
<use f='llvm/polly/lib/External/isl/isl_constraint.c' l='796' u='r' c='isl_basic_map_has_defining_equality'/>
<use f='llvm/polly/lib/External/isl/isl_constraint.c' l='797' u='r' c='isl_basic_map_has_defining_equality'/>
<use f='llvm/polly/lib/External/isl/isl_constraint.c' l='802' u='r' c='isl_basic_map_has_defining_equality'/>
<use f='llvm/polly/lib/External/isl/isl_constraint.c' l='1176' u='r' c='isl_basic_set_foreach_bound_pair'/>
<use f='llvm/polly/lib/External/isl/isl_constraint.c' l='1180' u='r' c='isl_basic_set_foreach_bound_pair'/>
<use f='llvm/polly/lib/External/isl/isl_convex_hull.c' l='223' u='r' c='wrap_constraints'/>
<use f='llvm/polly/lib/External/isl/isl_convex_hull.c' l='225' u='r' c='wrap_constraints'/>
<use f='llvm/polly/lib/External/isl/isl_convex_hull.c' l='226' u='r' c='wrap_constraints'/>
<use f='llvm/polly/lib/External/isl/isl_convex_hull.c' l='227' u='r' c='wrap_constraints'/>
<use f='llvm/polly/lib/External/isl/isl_convex_hull.c' l='236' u='r' c='wrap_constraints'/>
<use f='llvm/polly/lib/External/isl/isl_convex_hull.c' l='237' u='r' c='wrap_constraints'/>
<use f='llvm/polly/lib/External/isl/isl_convex_hull.c' l='237' u='r' c='wrap_constraints'/>
<use f='llvm/polly/lib/External/isl/isl_convex_hull.c' l='238' u='r' c='wrap_constraints'/>
<use f='llvm/polly/lib/External/isl/isl_convex_hull.c' l='425' u='r' c='initial_facet_constraint'/>
<use f='llvm/polly/lib/External/isl/isl_convex_hull.c' l='427' u='r' c='initial_facet_constraint'/>
<use f='llvm/polly/lib/External/isl/isl_convex_hull.c' l='430' u='r' c='initial_facet_constraint'/>
<use f='llvm/polly/lib/External/isl/isl_convex_hull.c' l='626' u='r' c='convex_hull_1d'/>
<use f='llvm/polly/lib/External/isl/isl_convex_hull.c' l='627' u='r' c='convex_hull_1d'/>
<use f='llvm/polly/lib/External/isl/isl_convex_hull.c' l='628' u='r' c='convex_hull_1d'/>
<use f='llvm/polly/lib/External/isl/isl_convex_hull.c' l='630' u='r' c='convex_hull_1d'/>
<use f='llvm/polly/lib/External/isl/isl_convex_hull.c' l='631' u='r' c='convex_hull_1d'/>
<use f='llvm/polly/lib/External/isl/isl_convex_hull.c' l='656' u='r' c='convex_hull_1d'/>
<use f='llvm/polly/lib/External/isl/isl_convex_hull.c' l='657' u='r' c='convex_hull_1d'/>
<use f='llvm/polly/lib/External/isl/isl_convex_hull.c' l='658' u='r' c='convex_hull_1d'/>
<use f='llvm/polly/lib/External/isl/isl_convex_hull.c' l='659' u='r' c='convex_hull_1d'/>
<use f='llvm/polly/lib/External/isl/isl_convex_hull.c' l='660' u='r' c='convex_hull_1d'/>
<use f='llvm/polly/lib/External/isl/isl_convex_hull.c' l='661' u='r' c='convex_hull_1d'/>
<use f='llvm/polly/lib/External/isl/isl_convex_hull.c' l='664' u='r' c='convex_hull_1d'/>
<use f='llvm/polly/lib/External/isl/isl_convex_hull.c' l='665' u='r' c='convex_hull_1d'/>
<use f='llvm/polly/lib/External/isl/isl_convex_hull.c' l='666' u='r' c='convex_hull_1d'/>
<use f='llvm/polly/lib/External/isl/isl_convex_hull.c' l='667' u='r' c='convex_hull_1d'/>
<use f='llvm/polly/lib/External/isl/isl_convex_hull.c' l='668' u='r' c='convex_hull_1d'/>
<use f='llvm/polly/lib/External/isl/isl_convex_hull.c' l='669' u='r' c='convex_hull_1d'/>
<use f='llvm/polly/lib/External/isl/isl_convex_hull.c' l='766' u='r' c='convex_hull_pair_elim'/>
<use f='llvm/polly/lib/External/isl/isl_convex_hull.c' l='767' u='r' c='convex_hull_pair_elim'/>
<use f='llvm/polly/lib/External/isl/isl_convex_hull.c' l='768' u='r' c='convex_hull_pair_elim'/>
<use f='llvm/polly/lib/External/isl/isl_convex_hull.c' l='768' u='r' c='convex_hull_pair_elim'/>
<use f='llvm/polly/lib/External/isl/isl_convex_hull.c' l='790' u='r' c='convex_hull_pair_elim'/>
<use f='llvm/polly/lib/External/isl/isl_convex_hull.c' l='791' u='r' c='convex_hull_pair_elim'/>
<use f='llvm/polly/lib/External/isl/isl_convex_hull.c' l='792' u='r' c='convex_hull_pair_elim'/>
<use f='llvm/polly/lib/External/isl/isl_convex_hull.c' l='793' u='r' c='convex_hull_pair_elim'/>
<use f='llvm/polly/lib/External/isl/isl_convex_hull.c' l='892' u='r' c='induced_lineality_space'/>
<use f='llvm/polly/lib/External/isl/isl_convex_hull.c' l='893' u='r' c='induced_lineality_space'/>
<use f='llvm/polly/lib/External/isl/isl_convex_hull.c' l='893' u='r' c='induced_lineality_space'/>
<use f='llvm/polly/lib/External/isl/isl_convex_hull.c' l='906' u='r' c='induced_lineality_space'/>
<use f='llvm/polly/lib/External/isl/isl_convex_hull.c' l='907' u='r' c='induced_lineality_space'/>
<use f='llvm/polly/lib/External/isl/isl_convex_hull.c' l='907' u='r' c='induced_lineality_space'/>
<use f='llvm/polly/lib/External/isl/isl_convex_hull.c' l='960' u='r' c='modulo_lineality'/>
<use f='llvm/polly/lib/External/isl/isl_convex_hull.c' l='1026' u='r' c='valid_direction_lp'/>
<use f='llvm/polly/lib/External/isl/isl_convex_hull.c' l='1028' u='r' c='valid_direction_lp'/>
<use f='llvm/polly/lib/External/isl/isl_convex_hull.c' l='1030' u='r' c='valid_direction_lp'/>
<use f='llvm/polly/lib/External/isl/isl_convex_hull.c' l='1030' u='r' c='valid_direction_lp'/>
<use f='llvm/polly/lib/External/isl/isl_convex_hull.c' l='1031' u='r' c='valid_direction_lp'/>
<use f='llvm/polly/lib/External/isl/isl_convex_hull.c' l='1031' u='r' c='valid_direction_lp'/>
<use f='llvm/polly/lib/External/isl/isl_convex_hull.c' l='1034' u='r' c='valid_direction_lp'/>
<use f='llvm/polly/lib/External/isl/isl_convex_hull.c' l='1037' u='r' c='valid_direction_lp'/>
<use f='llvm/polly/lib/External/isl/isl_convex_hull.c' l='1039' u='r' c='valid_direction_lp'/>
<use f='llvm/polly/lib/External/isl/isl_convex_hull.c' l='1039' u='r' c='valid_direction_lp'/>
<use f='llvm/polly/lib/External/isl/isl_convex_hull.c' l='1040' u='r' c='valid_direction_lp'/>
<use f='llvm/polly/lib/External/isl/isl_convex_hull.c' l='1040' u='r' c='valid_direction_lp'/>
<use f='llvm/polly/lib/External/isl/isl_convex_hull.c' l='1043' u='r' c='valid_direction_lp'/>
<use f='llvm/polly/lib/External/isl/isl_convex_hull.c' l='1112' u='r' c='valid_direction'/>
<use f='llvm/polly/lib/External/isl/isl_convex_hull.c' l='1370' u='r' c='isl_basic_set_lineality_space'/>
<use f='llvm/polly/lib/External/isl/isl_convex_hull.c' l='1371' u='r' c='isl_basic_set_lineality_space'/>
<use f='llvm/polly/lib/External/isl/isl_convex_hull.c' l='1371' u='r' c='isl_basic_set_lineality_space'/>
<use f='llvm/polly/lib/External/isl/isl_convex_hull.c' l='1380' u='r' c='isl_basic_set_lineality_space'/>
<use f='llvm/polly/lib/External/isl/isl_convex_hull.c' l='1381' u='r' c='isl_basic_set_lineality_space'/>
<use f='llvm/polly/lib/External/isl/isl_convex_hull.c' l='1685' u='r' c='common_constraints'/>
<use f='llvm/polly/lib/External/isl/isl_convex_hull.c' l='2073' u='r' c='hash_basic_set'/>
<use f='llvm/polly/lib/External/isl/isl_convex_hull.c' l='2073' u='r' c='hash_basic_set'/>
<use f='llvm/polly/lib/External/isl/isl_convex_hull.c' l='2074' u='r' c='hash_basic_set'/>
<use f='llvm/polly/lib/External/isl/isl_convex_hull.c' l='2318' u='r' c='add_bounds'/>
<use f='llvm/polly/lib/External/isl/isl_convex_hull.c' l='2318' u='r' c='add_bounds'/>
<use f='llvm/polly/lib/External/isl/isl_convex_hull.c' l='2319' u='r' c='add_bounds'/>
<use f='llvm/polly/lib/External/isl/isl_convex_hull.c' l='2577' u='r' c='select_shared_equalities'/>
<use f='llvm/polly/lib/External/isl/isl_convex_hull.c' l='2578' u='r' c='select_shared_equalities'/>
<use f='llvm/polly/lib/External/isl/isl_convex_hull.c' l='2589' u='r' c='select_shared_equalities'/>
<use f='llvm/polly/lib/External/isl/isl_convex_hull.c' l='2589' u='r' c='select_shared_equalities'/>
<use f='llvm/polly/lib/External/isl/isl_convex_hull.c' l='2842' u='r' c='collect_inequalities'/>
<use f='llvm/polly/lib/External/isl/isl_convex_hull.c' l='2843' u='r' c='collect_inequalities'/>
<use f='llvm/polly/lib/External/isl/isl_convex_hull.c' l='3102' u='r' c='isl_set_bounded_simple_hull'/>
<use f='llvm/polly/lib/External/isl/isl_convex_hull.c' l='3104' u='r' c='isl_set_bounded_simple_hull'/>
<use f='llvm/polly/lib/External/isl/isl_dim_map.c' l='158' u='r' c='isl_basic_map_add_constraints_dim_map'/>
<use f='llvm/polly/lib/External/isl/isl_dim_map.c' l='158' u='r' c='isl_basic_map_add_constraints_dim_map'/>
<use f='llvm/polly/lib/External/isl/isl_equalities.c' l='685' u='r' c='compress_variables'/>
<use f='llvm/polly/lib/External/isl/isl_equalities.c' l='759' u='r' c='isl_basic_set_dim_residue_class'/>
<use f='llvm/polly/lib/External/isl/isl_equalities.c' l='779' u='r' c='isl_basic_set_dim_residue_class'/>
<use f='llvm/polly/lib/External/isl/isl_factorization.c' l='288' u='r' c='isl_basic_set_factorizer'/>
<use f='llvm/polly/lib/External/isl/isl_farkas.c' l='272' u='r' c='farkas'/>
<use f='llvm/polly/lib/External/isl/isl_farkas.c' l='273' u='r' c='farkas'/>
<use f='llvm/polly/lib/External/isl/isl_farkas.c' l='275' u='r' c='farkas'/>
<use f='llvm/polly/lib/External/isl/isl_farkas.c' l='276' u='r' c='farkas'/>
<use f='llvm/polly/lib/External/isl/isl_farkas.c' l='278' u='r' c='farkas'/>
<use f='llvm/polly/lib/External/isl/isl_farkas.c' l='299' u='r' c='farkas'/>
<use f='llvm/polly/lib/External/isl/isl_farkas.c' l='502' u='r' c='add_lines'/>
<use f='llvm/polly/lib/External/isl/isl_farkas.c' l='503' u='r' c='add_lines'/>
<use f='llvm/polly/lib/External/isl/isl_farkas.c' l='503' u='r' c='add_lines'/>
<use f='llvm/polly/lib/External/isl/isl_input.c' l='2185' u='r' c='basic_map_read_polylib_constraint'/>
<use f='llvm/polly/lib/External/isl/isl_local_space.c' l='1074' u='r' c='isl_local_space_substitute_equalities'/>
<use f='llvm/polly/lib/External/isl/isl_local_space.c' l='1087' u='r' c='isl_local_space_substitute_equalities'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='1023' u='r' c='isl_basic_set_eq_is_stride'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='1026' u='r' c='isl_basic_set_eq_is_stride'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='1028' u='r' c='isl_basic_set_eq_is_stride'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='1031' u='r' c='isl_basic_set_eq_is_stride'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='1035' u='r' c='isl_basic_set_eq_is_stride'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='1038' u='r' c='isl_basic_set_eq_is_stride'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='1041' u='r' c='isl_basic_set_eq_is_stride'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='1042' u='r' c='isl_basic_set_eq_is_stride'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='1151' u='r' c='isl_basic_map_has_rational'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='1154' u='r' c='isl_basic_map_has_rational'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='1155' u='r' c='isl_basic_map_has_rational'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='1157' u='r' c='isl_basic_map_has_rational'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='1268' u='w' c='basic_map_init'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='1356' u='r' c='dup_constraints'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='1356' u='r' c='dup_constraints'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='1583' u='r' c='isl_basic_map_alloc_equality'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='1589' u='r' c='isl_basic_map_alloc_equality'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='1596' u='r' c='isl_basic_map_alloc_equality'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='1597' u='r' c='isl_basic_map_alloc_equality'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='1600' u='w' c='isl_basic_map_alloc_equality'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='1603' u='r' c='isl_basic_map_alloc_equality'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='1645' u='r' c='isl_basic_map_drop_equality'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='1648' u='r' c='isl_basic_map_drop_equality'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='1648' u='r' c='isl_basic_map_drop_equality'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='1649' u='r' c='isl_basic_map_drop_equality'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='1668' u='r' c='isl_basic_map_inequality_to_equality'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='1669' u='r' c='isl_basic_map_inequality_to_equality'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='1672' u='w' c='isl_basic_map_inequality_to_equality'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='1681' u='r' c='room_for_ineq'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='1771' u='r' c='isl_basic_map_add_eq'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='2080' u='r' c='isl_basic_map_swap_vars'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='2137' u='r' c='isl_basic_map_set_to_empty'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='2138' u='r' c='isl_basic_map_set_to_empty'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='2245' u='r' c='isl_basic_map_swap_div'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='2245' u='r' c='isl_basic_map_swap_div'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='2345' u='r' c='isl_basic_map_drop_core'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='2886' u='r' c='isl_basic_map_involves_dims'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='2982' u='r' c='isl_basic_map_drop_constraints_involving'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='3032' u='r' c='isl_basic_map_drop_constraints_not_involving_dims'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='3609' u='r' c='isl_basic_map_contains'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='3738' u='r' c='map_intersect_add_constraint'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='4801' u='r' c='isl_basic_map_sum'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='4802' u='r' c='isl_basic_map_sum'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='4803' u='r' c='isl_basic_map_sum'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='4804' u='r' c='isl_basic_map_sum'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='4879' u='r' c='isl_basic_map_neg'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='4879' u='r' c='isl_basic_map_neg'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='5037' u='r' c='var_equal'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='5038' u='r' c='var_equal'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='5039' u='r' c='var_equal'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='6362' u='r' c='isl_basic_map_fix_pos_si'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='6363' u='r' c='isl_basic_map_fix_pos_si'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='6364' u='r' c='isl_basic_map_fix_pos_si'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='6387' u='r' c='isl_basic_map_fix_pos'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='6388' u='r' c='isl_basic_map_fix_pos'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='6389' u='r' c='isl_basic_map_fix_pos'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='7519' u='r' c='basic_set_append_equalities'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='7520' u='r' c='basic_set_append_equalities'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='7577' u='r' c='first_parameter_equality'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='7673' u='r' c='parameter_compute_divs'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='8573' u='r' c='isl_basic_map_deltas'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='8574' u='r' c='isl_basic_map_deltas'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='8575' u='r' c='isl_basic_map_deltas'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='8576' u='r' c='isl_basic_map_deltas'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='8702' u='r' c='isl_basic_map_deltas_map'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='8703' u='r' c='isl_basic_map_deltas_map'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='8704' u='r' c='isl_basic_map_deltas_map'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='8705' u='r' c='isl_basic_map_deltas_map'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='9913' u='r' c='isl_basic_map_plain_has_fixed_var'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='9917' u='r' c='isl_basic_map_plain_has_fixed_var'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='9919' u='r' c='isl_basic_map_plain_has_fixed_var'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='9921' u='r' c='isl_basic_map_plain_has_fixed_var'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='9924' u='r' c='isl_basic_map_plain_has_fixed_var'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='10228' u='r' c='isl_basic_map_plain_cmp'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='10228' u='r' c='isl_basic_map_plain_cmp'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='11048' u='r' c='isl_basic_map_get_hash'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='11303' u='r' c='basic_map_dim_is_bounded'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='11702' u='r' c='isl_basic_map_output_defining_equality'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='11704' u='r' c='isl_basic_map_output_defining_equality'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='11707' u='r' c='isl_basic_map_output_defining_equality'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='11711' u='r' c='isl_basic_map_output_defining_equality'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='11712' u='r' c='isl_basic_map_output_defining_equality'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='11714' u='r' c='isl_basic_map_output_defining_equality'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='11718' u='r' c='isl_basic_map_output_defining_equality'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='11945' u='r' c='isl_basic_set_is_box'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='11947' u='r' c='isl_basic_set_is_box'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='12764' u='r' c='isl_basic_map_equalities_matrix'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='12856' u='r' c='isl_basic_map_from_constraint_matrices'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='13150' u='r' c='equator'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='13153' u='r' c='equator'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='13154' u='r' c='equator'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='13213' u='r' c='isl_map_oppose'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='13216' u='r' c='isl_map_oppose'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='13217' u='r' c='isl_map_oppose'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='13463' u='r' c='isl_basic_set_substitute'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='13465' u='r' c='isl_basic_set_substitute'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='13466' u='r' c='isl_basic_set_substitute'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='13467' u='r' c='isl_basic_set_substitute'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='13467' u='r' c='isl_basic_set_substitute'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='13671' u='r' c='add_ma_strides'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='13675' u='r' c='add_ma_strides'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='13677' u='r' c='add_ma_strides'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='13681' u='r' c='add_ma_strides'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='13683' u='r' c='add_ma_strides'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='13687' u='r' c='add_ma_strides'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='13688' u='r' c='add_ma_strides'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='13816' u='r' c='isl_basic_map_preimage_multi_aff'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='13816' u='r' c='isl_basic_map_preimage_multi_aff'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='14244' u='r' c='isl_basic_set_extract_equalities'/>
<use f='llvm/polly/lib/External/isl/isl_map.c' l='14403' u='r' c='isl_basic_map_transform_dims'/>
<use f='llvm/polly/lib/External/isl/isl_map_simplify.c' l='33' u='r' c='swap_equality'/>
<use f='llvm/polly/lib/External/isl/isl_map_simplify.c' l='34' u='r' c='swap_equality'/>
<use f='llvm/polly/lib/External/isl/isl_map_simplify.c' l='34' u='r' c='swap_equality'/>
<use f='llvm/polly/lib/External/isl/isl_map_simplify.c' l='35' u='r' c='swap_equality'/>
<use f='llvm/polly/lib/External/isl/isl_map_simplify.c' l='59' u='r' c='isl_basic_map_normalize_constraints'/>
<use f='llvm/polly/lib/External/isl/isl_map_simplify.c' l='61' u='r' c='isl_basic_map_normalize_constraints'/>
<use f='llvm/polly/lib/External/isl/isl_map_simplify.c' l='70' u='r' c='isl_basic_map_normalize_constraints'/>
<use f='llvm/polly/lib/External/isl/isl_map_simplify.c' l='73' u='r' c='isl_basic_map_normalize_constraints'/>
<use f='llvm/polly/lib/External/isl/isl_map_simplify.c' l='77' u='r' c='isl_basic_map_normalize_constraints'/>
<use f='llvm/polly/lib/External/isl/isl_map_simplify.c' l='77' u='r' c='isl_basic_map_normalize_constraints'/>
<use f='llvm/polly/lib/External/isl/isl_map_simplify.c' l='316' u='r' c='eliminate_var_using_equality'/>
<use f='llvm/polly/lib/External/isl/isl_map_simplify.c' l='318' u='r' c='eliminate_var_using_equality'/>
<use f='llvm/polly/lib/External/isl/isl_map_simplify.c' l='322' u='r' c='eliminate_var_using_equality'/>
<use f='llvm/polly/lib/External/isl/isl_map_simplify.c' l='323' u='r' c='eliminate_var_using_equality'/>
<use f='llvm/polly/lib/External/isl/isl_map_simplify.c' l='434' u='r' c='eliminate_divs_eq'/>
<use f='llvm/polly/lib/External/isl/isl_map_simplify.c' l='435' u='r' c='eliminate_divs_eq'/>
<use f='llvm/polly/lib/External/isl/isl_map_simplify.c' l='437' u='r' c='eliminate_divs_eq'/>
<use f='llvm/polly/lib/External/isl/isl_map_simplify.c' l='444' u='r' c='eliminate_divs_eq'/>
<use f='llvm/polly/lib/External/isl/isl_map_simplify.c' l='473' u='r' c='eliminate_divs_ineq'/>
<use f='llvm/polly/lib/External/isl/isl_map_simplify.c' l='510' u='r' c='bmap_eq_involves_unknown_divs'/>
<use f='llvm/polly/lib/External/isl/isl_map_simplify.c' l='568' u='r' c='set_div_from_eq'/>
<use f='llvm/polly/lib/External/isl/isl_map_simplify.c' l='570' u='r' c='set_div_from_eq'/>
<use f='llvm/polly/lib/External/isl/isl_map_simplify.c' l='621' u='r' c='isl_basic_map_gauss5'/>
<use f='llvm/polly/lib/External/isl/isl_map_simplify.c' l='633' u='r' c='isl_basic_map_gauss5'/>
<use f='llvm/polly/lib/External/isl/isl_map_simplify.c' l='634' u='r' c='isl_basic_map_gauss5'/>
<use f='llvm/polly/lib/External/isl/isl_map_simplify.c' l='634' u='r' c='isl_basic_map_gauss5'/>
<use f='llvm/polly/lib/External/isl/isl_map_simplify.c' l='637' u='r' c='isl_basic_map_gauss5'/>
<use f='llvm/polly/lib/External/isl/isl_map_simplify.c' l='648' u='r' c='isl_basic_map_gauss5'/>
<use f='llvm/polly/lib/External/isl/isl_map_simplify.c' l='906' u='r' c='n_pure_div_eq'/>
<use f='llvm/polly/lib/External/isl/isl_map_simplify.c' l='910' u='r' c='n_pure_div_eq'/>
<use f='llvm/polly/lib/External/isl/isl_map_simplify.c' l='999' u='r' c='normalize_divs'/>
<use f='llvm/polly/lib/External/isl/isl_map_simplify.c' l='1016' u='r' c='normalize_divs'/>
<use f='llvm/polly/lib/External/isl/isl_map_simplify.c' l='1018' u='r' c='normalize_divs'/>
<use f='llvm/polly/lib/External/isl/isl_map_simplify.c' l='1020' u='r' c='normalize_divs'/>
<use f='llvm/polly/lib/External/isl/isl_map_simplify.c' l='1051' u='r' c='normalize_divs'/>
<use f='llvm/polly/lib/External/isl/isl_map_simplify.c' l='1095' u='r' c='normalize_divs'/>
<use f='llvm/polly/lib/External/isl/isl_map_simplify.c' l='1096' u='r' c='normalize_divs'/>
<use f='llvm/polly/lib/External/isl/isl_map_simplify.c' l='1609' u='r' c='div_is_redundant'/>
<use f='llvm/polly/lib/External/isl/isl_map_simplify.c' l='1746' u='r' c='isl_basic_map_eliminate_vars'/>
<use f='llvm/polly/lib/External/isl/isl_map_simplify.c' l='1749' u='r' c='isl_basic_map_eliminate_vars'/>
<use f='llvm/polly/lib/External/isl/isl_map_simplify.c' l='1967' u='r' c='compute_elimination_index'/>
<use f='llvm/polly/lib/External/isl/isl_map_simplify.c' l='1996' u='r' c='reduced_using_equalities'/>
<use f='llvm/polly/lib/External/isl/isl_map_simplify.c' l='2033' u='r' c='isl_basic_set_reduce_using_equalities'/>
<use f='llvm/polly/lib/External/isl/isl_map_simplify.c' l='2033' u='r' c='isl_basic_set_reduce_using_equalities'/>
<use f='llvm/polly/lib/External/isl/isl_map_simplify.c' l='2206' u='r' c='drop_unrelated_constraints'/>
<use f='llvm/polly/lib/External/isl/isl_map_simplify.c' l='2311' u='r' c='isl_basic_map_drop_unrelated_constraints'/>
<use f='llvm/polly/lib/External/isl/isl_map_simplify.c' l='2356' u='r' c='drop_irrelevant_constraints'/>
<use f='llvm/polly/lib/External/isl/isl_map_simplify.c' l='2841' u='r' c='uset_gist'/>
<use f='llvm/polly/lib/External/isl/isl_map_simplify.c' l='2891' u='r' c='n_div_eq'/>
<use f='llvm/polly/lib/External/isl/isl_map_simplify.c' l='2922' u='r' c='basic_map_from_equalities'/>
<use f='llvm/polly/lib/External/isl/isl_map_simplify.c' l='2965' u='r' c='combined_variable_compression'/>
<use f='llvm/polly/lib/External/isl/isl_map_simplify.c' l='2970' u='r' c='combined_variable_compression'/>
<use f='llvm/polly/lib/External/isl/isl_map_simplify.c' l='2974' u='r' c='combined_variable_compression'/>
<use f='llvm/polly/lib/External/isl/isl_map_simplify.c' l='2976' u='r' c='combined_variable_compression'/>
<use f='llvm/polly/lib/External/isl/isl_map_simplify.c' l='2983' u='r' c='combined_variable_compression'/>
<use f='llvm/polly/lib/External/isl/isl_map_simplify.c' l='3041' u='r' c='extract_compressed_stride_constraints'/>
<use f='llvm/polly/lib/External/isl/isl_map_simplify.c' l='3042' u='r' c='extract_compressed_stride_constraints'/>
<use f='llvm/polly/lib/External/isl/isl_map_simplify.c' l='3054' u='r' c='extract_compressed_stride_constraints'/>
<use f='llvm/polly/lib/External/isl/isl_map_simplify.c' l='3171' u='r' c='reduce_stride_constraints'/>
<use f='llvm/polly/lib/External/isl/isl_map_simplify.c' l='3176' u='r' c='reduce_stride_constraints'/>
<use f='llvm/polly/lib/External/isl/isl_map_simplify.c' l='3183' u='r' c='reduce_stride_constraints'/>
<use f='llvm/polly/lib/External/isl/isl_map_simplify.c' l='3186' u='r' c='reduce_stride_constraints'/>
<use f='llvm/polly/lib/External/isl/isl_map_simplify.c' l='3187' u='r' c='reduce_stride_constraints'/>
<use f='llvm/polly/lib/External/isl/isl_map_simplify.c' l='3467' u='r' c='drop_equalities'/>
<use f='llvm/polly/lib/External/isl/isl_map_simplify.c' l='3470' u='r' c='drop_equalities'/>
<use f='llvm/polly/lib/External/isl/isl_map_simplify.c' l='3471' u='r' c='drop_equalities'/>
<use f='llvm/polly/lib/External/isl/isl_map_simplify.c' l='3480' u='r' c='drop_equalities'/>
<use f='llvm/polly/lib/External/isl/isl_map_simplify.c' l='3480' u='r' c='drop_equalities'/>
<use f='llvm/polly/lib/External/isl/isl_map_simplify.c' l='3839' u='r' c='isl_basic_map_plain_is_disjoint'/>
<use f='llvm/polly/lib/External/isl/isl_map_simplify.c' l='5043' u='r' c='isl_basic_map_drop_redundant_divs_ineq'/>
<use f='llvm/polly/lib/External/isl/isl_map_simplify.c' l='5188' u='r' c='isl_basic_map_preimage_vars'/>
<use f='llvm/polly/lib/External/isl/isl_map_simplify.c' l='5280' u='r' c='isl_basic_map_drop_redundant_divs'/>
<use f='llvm/polly/lib/External/isl/isl_map_simplify.c' l='5285' u='r' c='isl_basic_map_drop_redundant_divs'/>
<use f='llvm/polly/lib/External/isl/isl_map_simplify.c' l='5297' u='r' c='isl_basic_map_drop_redundant_divs'/>
<use f='llvm/polly/lib/External/isl/isl_map_simplify.c' l='5325' u='r' c='has_multiple_var_equality'/>
<use f='llvm/polly/lib/External/isl/isl_map_simplify.c' l='5328' u='r' c='has_multiple_var_equality'/>
<use f='llvm/polly/lib/External/isl/isl_map_simplify.c' l='5329' u='r' c='has_multiple_var_equality'/>
<use f='llvm/polly/lib/External/isl/isl_map_simplify.c' l='5333' u='r' c='has_multiple_var_equality'/>
<use f='llvm/polly/lib/External/isl/isl_map_simplify.c' l='5337' u='r' c='has_multiple_var_equality'/>
<use f='llvm/polly/lib/External/isl/isl_map_simplify.c' l='5338' u='r' c='has_multiple_var_equality'/>
<use f='llvm/polly/lib/External/isl/isl_map_simplify.c' l='5342' u='r' c='has_multiple_var_equality'/>
<use f='llvm/polly/lib/External/isl/isl_map_simplify.c' l='5442' u='r' c='isl_basic_map_reduce_coefficients'/>
<use f='llvm/polly/lib/External/isl/isl_map_simplify.c' l='5523' u='r' c='isl_basic_map_shift_div'/>
<use f='llvm/polly/lib/External/isl/isl_map_simplify.c' l='5525' u='r' c='isl_basic_map_shift_div'/>
<use f='llvm/polly/lib/External/isl/isl_map_simplify.c' l='5526' u='r' c='isl_basic_map_shift_div'/>
<use f='llvm/polly/lib/External/isl/isl_map_subtract.c' l='77' u='r' c='tab_add_constraints'/>
<use f='llvm/polly/lib/External/isl/isl_map_subtract.c' l='80' u='r' c='tab_add_constraints'/>
<use f='llvm/polly/lib/External/isl/isl_map_subtract.c' l='80' u='r' c='tab_add_constraints'/>
<use f='llvm/polly/lib/External/isl/isl_map_subtract.c' l='81' u='r' c='tab_add_constraints'/>
<use f='llvm/polly/lib/External/isl/isl_map_subtract.c' l='84' u='r' c='tab_add_constraints'/>
<use f='llvm/polly/lib/External/isl/isl_map_subtract.c' l='84' u='r' c='tab_add_constraints'/>
<use f='llvm/polly/lib/External/isl/isl_map_subtract.c' l='139' u='r' c='tab_add_constraint'/>
<use f='llvm/polly/lib/External/isl/isl_map_subtract.c' l='139' u='r' c='tab_add_constraint'/>
<use f='llvm/polly/lib/External/isl/isl_map_subtract.c' l='142' u='r' c='tab_add_constraint'/>
<use f='llvm/polly/lib/External/isl/isl_map_subtract.c' l='142' u='r' c='tab_add_constraint'/>
<use f='llvm/polly/lib/External/isl/isl_map_subtract.c' l='143' u='r' c='tab_add_constraint'/>
<use f='llvm/polly/lib/External/isl/isl_map_subtract.c' l='146' u='r' c='tab_add_constraint'/>
<use f='llvm/polly/lib/External/isl/isl_map_subtract.c' l='146' u='r' c='tab_add_constraint'/>
<use f='llvm/polly/lib/External/isl/isl_map_subtract.c' l='148' u='r' c='tab_add_constraint'/>
<use f='llvm/polly/lib/External/isl/isl_map_subtract.c' l='148' u='r' c='tab_add_constraint'/>
<use f='llvm/polly/lib/External/isl/isl_map_subtract.c' l='768' u='r' c='singleton_extract_point'/>
<use f='llvm/polly/lib/External/isl/isl_map_subtract.c' l='771' u='r' c='singleton_extract_point'/>
<use f='llvm/polly/lib/External/isl/isl_map_subtract.c' l='772' u='r' c='singleton_extract_point'/>
<use f='llvm/polly/lib/External/isl/isl_map_subtract.c' l='775' u='r' c='singleton_extract_point'/>
<use f='llvm/polly/lib/External/isl/isl_map_subtract.c' l='778' u='r' c='singleton_extract_point'/>
<use f='llvm/polly/lib/External/isl/isl_map_subtract.c' l='779' u='r' c='singleton_extract_point'/>
<use f='llvm/polly/lib/External/isl/isl_map_subtract.c' l='782' u='r' c='singleton_extract_point'/>
<use f='llvm/polly/lib/External/isl/isl_map_subtract.c' l='784' u='r' c='singleton_extract_point'/>
<use f='llvm/polly/lib/External/isl/isl_mat.c' l='1388' u='r' c='isl_basic_set_preimage'/>
<use f='llvm/polly/lib/External/isl/isl_morph.c' l='438' u='r' c='copy_equalities'/>
<use f='llvm/polly/lib/External/isl/isl_morph.c' l='438' u='r' c='copy_equalities'/>
<use f='llvm/polly/lib/External/isl/isl_morph.c' l='503' u='r' c='isl_basic_set_variable_compression'/>
<use f='llvm/polly/lib/External/isl/isl_morph.c' l='506' u='r' c='isl_basic_set_variable_compression'/>
<use f='llvm/polly/lib/External/isl/isl_morph.c' l='511' u='r' c='isl_basic_set_variable_compression'/>
<use f='llvm/polly/lib/External/isl/isl_morph.c' l='590' u='r' c='isl_basic_set_parameter_compression'/>
<use f='llvm/polly/lib/External/isl/isl_morph.c' l='599' u='r' c='isl_basic_set_parameter_compression'/>
<use f='llvm/polly/lib/External/isl/isl_morph.c' l='600' u='r' c='isl_basic_set_parameter_compression'/>
<use f='llvm/polly/lib/External/isl/isl_output.c' l='70' u='r' c='print_constraint_polylib'/>
<use f='llvm/polly/lib/External/isl/isl_output.c' l='803' u='r' c='print_constraints'/>
<use f='llvm/polly/lib/External/isl/isl_output.c' l='812' u='r' c='print_constraints'/>
<use f='llvm/polly/lib/External/isl/isl_output.c' l='813' u='r' c='print_constraints'/>
<use f='llvm/polly/lib/External/isl/isl_output.c' l='815' u='r' c='print_constraints'/>
<use f='llvm/polly/lib/External/isl/isl_output.c' l='1280' u='r' c='get_aff'/>
<use f='llvm/polly/lib/External/isl/isl_output.c' l='1282' u='r' c='get_aff'/>
<use f='llvm/polly/lib/External/isl/isl_output.c' l='1283' u='r' c='get_aff'/>
<use f='llvm/polly/lib/External/isl/isl_output.c' l='1317' u='r' c='drop_aff'/>
<use f='llvm/polly/lib/External/isl/isl_output.c' l='1321' u='r' c='drop_aff'/>
<use f='llvm/polly/lib/External/isl/isl_output.c' l='1321' u='r' c='drop_aff'/>
<use f='llvm/polly/lib/External/isl/isl_output.c' l='1322' u='r' c='drop_aff'/>
<use f='llvm/polly/lib/External/isl/isl_output.c' l='1322' u='r' c='drop_aff'/>
<use f='llvm/polly/lib/External/isl/isl_output.c' l='1396' u='r' c='defining_equality'/>
<use f='llvm/polly/lib/External/isl/isl_output.c' l='1398' u='r' c='defining_equality'/>
<use f='llvm/polly/lib/External/isl/isl_output.c' l='1399' u='r' c='defining_equality'/>
<use f='llvm/polly/lib/External/isl/isl_output.c' l='1399' u='r' c='defining_equality'/>
<use f='llvm/polly/lib/External/isl/isl_output.c' l='1428' u='r' c='print_dim_eq'/>
<use f='llvm/polly/lib/External/isl/isl_output.c' l='2200' u='r' c='print_basic_set_c'/>
<use f='llvm/polly/lib/External/isl/isl_output.c' l='2203' u='r' c='print_basic_set_c'/>
<use f='llvm/polly/lib/External/isl/isl_output.c' l='2208' u='r' c='print_basic_set_c'/>
<use f='llvm/polly/lib/External/isl/isl_output.c' l='2212' u='r' c='print_basic_set_c'/>
<use f='llvm/polly/lib/External/isl/isl_polynomial.c' l='3000' u='r' c='isl_qpolynomial_substitute_equalities_lifted'/>
<use f='llvm/polly/lib/External/isl/isl_polynomial.c' l='3007' u='r' c='isl_qpolynomial_substitute_equalities_lifted'/>
<use f='llvm/polly/lib/External/isl/isl_polynomial.c' l='3012' u='r' c='isl_qpolynomial_substitute_equalities_lifted'/>
<use f='llvm/polly/lib/External/isl/isl_polynomial.c' l='3013' u='r' c='isl_qpolynomial_substitute_equalities_lifted'/>
<use f='llvm/polly/lib/External/isl/isl_polynomial.c' l='3013' u='r' c='isl_qpolynomial_substitute_equalities_lifted'/>
<use f='llvm/polly/lib/External/isl/isl_polynomial.c' l='3014' u='r' c='isl_qpolynomial_substitute_equalities_lifted'/>
<use f='llvm/polly/lib/External/isl/isl_polynomial.c' l='3015' u='r' c='isl_qpolynomial_substitute_equalities_lifted'/>
<use f='llvm/polly/lib/External/isl/isl_polynomial.c' l='3018' u='r' c='isl_qpolynomial_substitute_equalities_lifted'/>
<use f='llvm/polly/lib/External/isl/isl_polynomial.c' l='5186' u='r' c='isl_basic_map_from_qpolynomial'/>
<use f='llvm/polly/lib/External/isl/isl_polynomial.c' l='5187' u='r' c='isl_basic_map_from_qpolynomial'/>
<use f='llvm/polly/lib/External/isl/isl_polynomial.c' l='5188' u='r' c='isl_basic_map_from_qpolynomial'/>
<use f='llvm/polly/lib/External/isl/isl_sample.c' l='84' u='r' c='interval_sample'/>
<use f='llvm/polly/lib/External/isl/isl_sample.c' l='85' u='r' c='interval_sample'/>
<use f='llvm/polly/lib/External/isl/isl_sample.c' l='87' u='r' c='interval_sample'/>
<use f='llvm/polly/lib/External/isl/isl_sample.c' l='89' u='r' c='interval_sample'/>
<use f='llvm/polly/lib/External/isl/isl_sample.c' l='177' u='r' c='tab_equalities'/>
<use f='llvm/polly/lib/External/isl/isl_sample.c' l='961' u='r' c='isl_basic_set_sample_with_cone'/>
<use f='llvm/polly/lib/External/isl/isl_sample.c' l='1229' u='r' c='isl_basic_set_from_vec'/>
<use f='llvm/polly/lib/External/isl/isl_sample.c' l='1230' u='r' c='isl_basic_set_from_vec'/>
<use f='llvm/polly/lib/External/isl/isl_sample.c' l='1231' u='r' c='isl_basic_set_from_vec'/>
<use f='llvm/polly/lib/External/isl/isl_scheduler.c' l='2868' u='r' c='add_sum_constraint'/>
<use f='llvm/polly/lib/External/isl/isl_scheduler.c' l='2869' u='r' c='add_sum_constraint'/>
<use f='llvm/polly/lib/External/isl/isl_scheduler.c' l='2871' u='r' c='add_sum_constraint'/>
<use f='llvm/polly/lib/External/isl/isl_scheduler.c' l='2892' u='r' c='add_param_sum_constraint'/>
<use f='llvm/polly/lib/External/isl/isl_scheduler.c' l='2893' u='r' c='add_param_sum_constraint'/>
<use f='llvm/polly/lib/External/isl/isl_scheduler.c' l='2898' u='r' c='add_param_sum_constraint'/>
<use f='llvm/polly/lib/External/isl/isl_scheduler.c' l='2920' u='r' c='add_var_sum_constraint'/>
<use f='llvm/polly/lib/External/isl/isl_scheduler.c' l='2921' u='r' c='add_var_sum_constraint'/>
<use f='llvm/polly/lib/External/isl/isl_scheduler.c' l='2927' u='r' c='add_var_sum_constraint'/>
<use f='llvm/polly/lib/External/isl/isl_scheduler.c' l='4438' u='r' c='setup_carry_lp'/>
<use f='llvm/polly/lib/External/isl/isl_scheduler.c' l='4439' u='r' c='setup_carry_lp'/>
<use f='llvm/polly/lib/External/isl/isl_scheduler.c' l='4440' u='r' c='setup_carry_lp'/>
<use f='llvm/polly/lib/External/isl/isl_scheduler.c' l='4442' u='r' c='setup_carry_lp'/>
<use f='llvm/polly/lib/External/isl/isl_tab.c' l='2405' u='r' c='isl_tab_from_basic_map'/>
<use f='llvm/polly/lib/External/isl/isl_tab.c' l='2456' u='r' c='isl_tab_from_recession_cone'/>
<use f='llvm/polly/lib/External/isl/isl_tab.c' l='2458' u='r' c='isl_tab_from_recession_cone'/>
<use f='llvm/polly/lib/External/isl/isl_tab.c' l='2461' u='r' c='isl_tab_from_recession_cone'/>
<use f='llvm/polly/lib/External/isl/isl_tab.c' l='2462' u='r' c='isl_tab_from_recession_cone'/>
<use f='llvm/polly/lib/External/isl/isl_tab_pip.c' l='2344' u='r' c='tab_for_lexmin'/>
<use f='llvm/polly/lib/External/isl/isl_tab_pip.c' l='2345' u='r' c='tab_for_lexmin'/>
<use f='llvm/polly/lib/External/isl/isl_tab_pip.c' l='2346' u='r' c='tab_for_lexmin'/>
<use f='llvm/polly/lib/External/isl/isl_tab_pip.c' l='2348' u='r' c='tab_for_lexmin'/>
<use f='llvm/polly/lib/External/isl/isl_tab_pip.c' l='2349' u='r' c='tab_for_lexmin'/>
<use f='llvm/polly/lib/External/isl/isl_tab_pip.c' l='2978' u='r' c='drop_constant_terms'/>
<use f='llvm/polly/lib/External/isl/isl_tab_pip.c' l='4721' u='r' c='set_minimum'/>
<use f='llvm/polly/lib/External/isl/isl_tab_pip.c' l='4722' u='r' c='set_minimum'/>
<use f='llvm/polly/lib/External/isl/isl_tab_pip.c' l='4764' u='r' c='need_split_basic_map'/>
<use f='llvm/polly/lib/External/isl/isl_transitive_closure.c' l='79' u='r' c='set_path_length'/>
<use f='llvm/polly/lib/External/isl/isl_transitive_closure.c' l='258' u='r' c='path_along_steps'/>
<use f='llvm/polly/lib/External/isl/isl_transitive_closure.c' l='259' u='r' c='path_along_steps'/>
<use f='llvm/polly/lib/External/isl/isl_transitive_closure.c' l='260' u='r' c='path_along_steps'/>
<use f='llvm/polly/lib/External/isl/isl_transitive_closure.c' l='263' u='r' c='path_along_steps'/>
<use f='llvm/polly/lib/External/isl/isl_transitive_closure.c' l='266' u='r' c='path_along_steps'/>
<use f='llvm/polly/lib/External/isl/isl_transitive_closure.c' l='468' u='r' c='add_delta_constraints'/>
<use f='llvm/polly/lib/External/isl/isl_transitive_closure.c' l='491' u='r' c='add_delta_constraints'/>
<use f='llvm/polly/lib/External/isl/isl_transitive_closure.c' l='612' u='r' c='path_along_delta'/>
<use f='llvm/polly/lib/External/isl/isl_transitive_closure.c' l='613' u='r' c='path_along_delta'/>
<use f='llvm/polly/lib/External/isl/isl_transitive_closure.c' l='614' u='r' c='path_along_delta'/>
<use f='llvm/polly/lib/External/isl/isl_transitive_closure.c' l='615' u='r' c='path_along_delta'/>
<use f='llvm/polly/lib/External/isl/isl_transitive_closure.c' l='696' u='r' c='equate_parameter_to_length'/>
<use f='llvm/polly/lib/External/isl/isl_transitive_closure.c' l='697' u='r' c='equate_parameter_to_length'/>
<use f='llvm/polly/lib/External/isl/isl_transitive_closure.c' l='698' u='r' c='equate_parameter_to_length'/>
<use f='llvm/polly/lib/External/isl/isl_transitive_closure.c' l='699' u='r' c='equate_parameter_to_length'/>
<use f='llvm/polly/lib/External/isl/isl_transitive_closure.c' l='1501' u='r' c='increment'/>
<use f='llvm/polly/lib/External/isl/isl_transitive_closure.c' l='1502' u='r' c='increment'/>
<use f='llvm/polly/lib/External/isl/isl_transitive_closure.c' l='1503' u='r' c='increment'/>
<use f='llvm/polly/lib/External/isl/isl_transitive_closure.c' l='1504' u='r' c='increment'/>
<use f='llvm/polly/lib/External/isl/isl_transitive_closure.c' l='2205' u='r' c='box_closure_on_domain'/>
<use f='llvm/polly/lib/External/isl/isl_transitive_closure.c' l='2206' u='r' c='box_closure_on_domain'/>
<use f='llvm/polly/lib/External/isl/isl_transitive_closure.c' l='2207' u='r' c='box_closure_on_domain'/>
<use f='llvm/polly/lib/External/isl/isl_transitive_closure.c' l='2208' u='r' c='box_closure_on_domain'/>
<use f='llvm/polly/lib/External/isl/isl_transitive_closure.c' l='2209' u='r' c='box_closure_on_domain'/>
<use f='llvm/polly/lib/External/isl/isl_transitive_closure.c' l='2210' u='r' c='box_closure_on_domain'/>
<use f='llvm/polly/lib/External/isl/isl_transitive_closure.c' l='2211' u='r' c='box_closure_on_domain'/>
<use f='llvm/polly/lib/External/isl/isl_transitive_closure.c' l='2212' u='r' c='box_closure_on_domain'/>
<use f='llvm/polly/lib/External/isl/isl_vertices.c' l='1143' u='r' c='tab_for_shifted_cone'/>
<use f='llvm/polly/lib/External/isl/isl_vertices.c' l='1444' u='r' c='vertex_on_facet'/>
<use f='llvm/polly/lib/External/isl/isl_vertices.c' l='1445' u='r' c='vertex_on_facet'/>
