<use f='llvm/polly/include/polly/CodeGen/IslNodeBuilder.h' l='76' u='w' c='_ZN14IslNodeBuilderC1ERN4llvm9IRBuilderINS0_14ConstantFolderEN5polly10IRInserterEEERNS3_13ScopAnnotatorERKNS0_10DataLayoutERNS0_8LoopInfoERNS0_15Scala10521409'/>
<dec f='llvm/polly/include/polly/CodeGen/IslNodeBuilder.h' l='153' type='const llvm::DataLayout &amp;'/>
<offset>3712</offset>
<use f='llvm/polly/lib/CodeGen/IslNodeBuilder.cpp' l='686' u='r' c='_ZN14IslNodeBuilder17createForParallelEP12isl_ast_node'/>
<use f='llvm/polly/lib/CodeGen/IslNodeBuilder.cpp' l='689' u='r' c='_ZN14IslNodeBuilder17createForParallelEP12isl_ast_node'/>
<use f='llvm/polly/lib/CodeGen/IslNodeBuilder.cpp' l='1397' u='m' c='_ZN14IslNodeBuilder26preloadInvariantEquivClassERN5polly21InvariantEquivClassTyE'/>
<use f='llvm/polly/lib/CodeGen/IslNodeBuilder.cpp' l='1473' u='m' c='_ZN14IslNodeBuilder17allocateNewArraysESt4pairIPN4llvm10BasicBlockES3_E'/>
<use f='llvm/polly/lib/CodeGen/IslNodeBuilder.cpp' l='1497' u='m' c='_ZN14IslNodeBuilder17allocateNewArraysESt4pairIPN4llvm10BasicBlockES3_E'/>
<use f='llvm/polly/lib/CodeGen/IslNodeBuilder.cpp' l='1567' u='r' c='_ZN14IslNodeBuilder12generateSCEVEPKN4llvm4SCEVE'/>
