<dec f='llvm/lld/ELF/Config.h' l='105' type='llvm::StringRef'/>
<offset>2112</offset>
<use f='llvm/lld/ELF/Driver.cpp' l='992' u='w' c='_ZL11readConfigsRN4llvm3opt12InputArgListE'/>
<use f='llvm/lld/ELF/Driver.cpp' l='2122' u='r' c='_ZN3lld3elf12LinkerDriver4linkERN4llvm3opt12InputArgListE'/>
<use f='llvm/lld/ELF/MarkLive.cpp' l='239' u='r' c='_ZN12_GLOBAL__N_18MarkLive3runEv'/>
<use f='llvm/lld/ELF/SyntheticSections.cpp' l='1485' u='r' c='_ZN3lld3elf14DynamicSection16finalizeContentsEv'/>
