<def f='llvm/lld/include/lld/ReaderWriter/MachOLinkingContext.h' l='49' ll='54'/>
<use f='llvm/lld/include/lld/ReaderWriter/MachOLinkingContext.h' l='87' c='_ZN3lld19MachOLinkingContext9configureEN4llvm5MachO14HeaderFileTypeENS0_4ArchENS0_2OSEjb'/>
<use f='llvm/lld/include/lld/ReaderWriter/MachOLinkingContext.h' l='125' c='_ZNK3lld19MachOLinkingContext2osEv'/>
<use f='llvm/lld/include/lld/ReaderWriter/MachOLinkingContext.h' l='459'/>
<use f='llvm/lld/lib/Driver/DarwinLdDriver.cpp' l='397' c='_ZN3lld6mach_o5parseEN4llvm8ArrayRefIPKcEERNS_19MachOLinkingContextE'/>
<use f='llvm/lld/lib/ReaderWriter/MachO/MachONormalizedFile.h' l='248'/>
<use f='llvm/lld/lib/ReaderWriter/MachO/File.h' l='202' c='_ZNK3lld6mach_o9MachOFile2OSEv'/>
<use f='llvm/lld/lib/ReaderWriter/MachO/File.h' l='203' c='_ZN3lld6mach_o9MachOFile5setOSENS_19MachOLinkingContext2OSE'/>
<use f='llvm/lld/lib/ReaderWriter/MachO/File.h' l='275'/>
<use f='llvm/lld/lib/ReaderWriter/MachO/MachOLinkingContext.cpp' l='184' c='_ZN3lld19MachOLinkingContext9configureEN4llvm5MachO14HeaderFileTypeENS0_4ArchENS0_2OSEjb'/>
<use f='llvm/lld/lib/ReaderWriter/MachO/MachONormalizedFileYAML.cpp' l='135'/>
<use f='llvm/lld/lib/ReaderWriter/MachO/MachONormalizedFileYAML.cpp' l='136' c='_ZN4llvm4yaml23ScalarEnumerationTraitsIN3lld19MachOLinkingContext2OSEvE11enumerationERNS0_2IOERS4_'/>
