<use f='llvm/lld/COFF/Symbols.h' l='242' u='w' c='_ZN3lld4coff15DefinedAbsoluteC1EN4llvm9StringRefENS2_6object13COFFSymbolRefE'/>
<use f='llvm/lld/COFF/Symbols.h' l='247' u='w' c='_ZN3lld4coff15DefinedAbsoluteC1EN4llvm9StringRefEm'/>
<use f='llvm/lld/COFF/Symbols.h' l='253' u='r' c='_ZN3lld4coff15DefinedAbsolute6getRVAEv'/>
<use f='llvm/lld/COFF/Symbols.h' l='254' u='w' c='_ZN3lld4coff15DefinedAbsolute5setVAEm'/>
<use f='llvm/lld/COFF/Symbols.h' l='255' u='r' c='_ZNK3lld4coff15DefinedAbsolute5getVAEv'/>
<dec f='llvm/lld/COFF/Symbols.h' l='263' type='uint64_t'/>
<offset>128</offset>
