<dec f='llvm/lldb/source/Plugins/ScriptInterpreter/Python/PythonDataObjects.h' l='742' type='const char *'/>
<use f='llvm/lldb/source/Plugins/ScriptInterpreter/Python/PythonDataObjects.h' l='748' u='w' c='_ZN12lldb_private6python12PythonScriptC1EPKc'/>
<offset>0</offset>
<use f='llvm/lldb/source/Plugins/ScriptInterpreter/Python/PythonDataObjects.cpp' l='1565' u='r' c='_ZN12lldb_private6python12PythonScript4InitEv'/>
