<dec f='llvm/lldb/source/Plugins/ObjectFile/Breakpad/BreakpadRecords.h' l='23' type='0'/>
<use f='llvm/lldb/source/Plugins/ObjectFile/Breakpad/BreakpadRecords.h' l='52' u='r' c='_ZN12lldb_private8breakpad12ModuleRecordC1EN4llvm6Triple6OSTypeENS3_8ArchTypeENS_4UUIDE'/>
<use f='llvm/lldb/source/Plugins/ObjectFile/Breakpad/BreakpadRecords.h' l='97' u='r' c='_ZN12lldb_private8breakpad10FuncRecordC1EbmmmN4llvm9StringRefE'/>
<use f='llvm/lldb/source/Plugins/ObjectFile/Breakpad/BreakpadRecords.h' l='132' u='r' c='_ZN12lldb_private8breakpad12PublicRecordC1EbmmN4llvm9StringRefE'/>
<use f='llvm/lldb/source/Plugins/ObjectFile/Breakpad/BreakpadRecords.cpp' l='129' u='a' c='_ZN12lldb_private8breakpad6Record8classifyEN4llvm9StringRefE'/>
<use f='llvm/lldb/source/Plugins/ObjectFile/Breakpad/BreakpadRecords.cpp' l='485' c='_ZN12lldb_private8breakpad8toStringENS0_6Record4KindE'/>
<use f='llvm/lldb/unittests/ObjectFile/Breakpad/BreakpadRecordsTest.cpp' l='17' c='_ZN20Record_classify_Test8TestBodyEv'/>
<use f='llvm/lldb/unittests/ObjectFile/Breakpad/BreakpadRecordsTest.cpp' l='17' u='r' c='_ZN20Record_classify_Test8TestBodyEv'/>
