<use f='llvm/lldb/include/lldb/lldb-forward.h' l='344'/>
<use f='llvm/lldb/include/lldb/lldb-forward.h' l='345'/>
<use f='llvm/lldb/include/lldb/lldb-private-interfaces.h' l='107'/>
<use f='llvm/lldb/include/lldb/Core/ModuleList.h' l='200' c='_ZNK12lldb_private10ModuleList17GetIndexForModuleEPKNS_6ModuleE'/>
<use f='llvm/lldb/include/lldb/Core/ModuleList.h' l='238' c='_ZNK12lldb_private10ModuleList23GetModulePointerAtIndexEm'/>
<use f='llvm/lldb/include/lldb/Core/ModuleList.h' l='312' c='_ZNK12lldb_private10ModuleList10FindModuleEPKNS_6ModuleE'/>
<use f='llvm/lldb/include/lldb/Core/ModuleList.h' l='347' c='_ZNK12lldb_private10ModuleList9FindTypesEPNS_6ModuleENS_11ConstStringEbmRN4llvm8DenseSetIPNS_10SymbolFileENS4_12DenseMapInfoIS7_EEEERNS_8TypeListE'/>
<use f='llvm/lldb/include/lldb/Core/ModuleList.h' l='399' c='_ZN12lldb_private10ModuleList16RemoveIfOrphanedEPKNS_6ModuleE'/>
<use f='llvm/lldb/include/lldb/Core/ModuleList.h' l='436' c='_ZN12lldb_private10ModuleList15ModuleIsInCacheEPKNS_6ModuleE'/>
<use f='llvm/lldb/include/lldb/Core/ModuleList.h' l='451' c='_ZN12lldb_private10ModuleList28RemoveSharedModuleIfOrphanedEPKNS_6ModuleE'/>
<use f='llvm/lldb/include/lldb/Symbol/UnwindTable.h' l='26' c='_ZN12lldb_private11UnwindTableC1ERNS_6ModuleE'/>
<use f='llvm/lldb/include/lldb/Symbol/UnwindTable.h' l='70'/>
<use f='llvm/lldb/include/lldb/Symbol/ObjectFile.h' l='61'/>
<use f='llvm/lldb/include/lldb/Symbol/TypeSystem.h' l='80' c='_ZN12lldb_private10TypeSystem14CreateInstanceEN4lldb12LanguageTypeEPNS_6ModuleE'/>
<use f='llvm/lldb/include/lldb/Symbol/TypeSystem.h' l='515' c='_ZN12lldb_private13TypeSystemMap24GetTypeSystemForLanguageEN4lldb12LanguageTypeEPNS_6ModuleEb'/>
<inh f='llvm/lldb/include/lldb/Symbol/SymbolContextScope.h' l='64' c='lldb_private::SymbolContextScope'/>
<def f='llvm/lldb/include/lldb/Core/Module.h' l='75' ll='1056'/>
<use f='llvm/lldb/include/lldb/Core/Module.h' l='75'/>
<use f='llvm/lldb/include/lldb/Core/Module.h' l='86' c='_ZN12lldb_private6Module25GetAllocatedModuleAtIndexEm'/>
<use f='llvm/lldb/include/lldb/Core/Module.h' l='125' c='_ZN12lldb_private6Module26CreateModuleFromObjectFileEDpOT0_'/>
<use f='llvm/lldb/include/lldb/Core/Module.h' l='1054' c='_ZN12lldb_private6ModuleC1ERKS0_'/>
<use f='llvm/lldb/include/lldb/Core/Module.h' l='1055' c='_ZN12lldb_private6ModuleaSERKS0_'/>
<use f='llvm/lldb/include/lldb/Core/Module.h' l='1055' c='_ZN12lldb_private6ModuleaSERKS0_'/>
<use f='llvm/lldb/include/lldb/Breakpoint/BreakpointLocationList.h' l='84' c='_ZN12lldb_private22BreakpointLocationList12FindInModuleEPNS_6ModuleERNS_28BreakpointLocationCollectionE'/>
<use f='llvm/lldb/include/lldb/Target/Target.h' l='862' c='_ZN12lldb_private6Target26GetExecutableModulePointerEv'/>
<size>696</size>
<doc f='llvm/lldb/include/lldb/Core/Module.h' l='60'>/// \class Module Module.h &quot;lldb/Core/Module.h&quot;
/// A class that describes an executable image and its associated
///        object and symbol files.
///
/// The module is designed to be able to select a single slice of an
/// executable image as it would appear on disk and during program execution.
///
/// Modules control when and if information is parsed according to which
/// accessors are called. For example the object file (ObjectFile)
/// representation will only be parsed if the object file is requested using
/// the Module::GetObjectFile() is called. The debug symbols will only be
/// parsed if the symbol file (SymbolFile) is requested using the
/// Module::GetSymbolFile() method.
///
/// The module will parse more detailed information as more queries are made.</doc>
<fun r='_ZN12lldb_private6Module25GetNumberAllocatedModulesEv'/>
<fun r='_ZN12lldb_private6Module25GetAllocatedModuleAtIndexEm'/>
<fun r='_ZN12lldb_private6Module34GetAllocationModuleCollectionMutexEv'/>
<fun r='_ZN12lldb_private6ModuleC1ERKNS_8FileSpecERKNS_8ArchSpecEPKNS_11ConstStringEmRKNSt6chrono10time_pointINSA_3_V212system_clockENSA_8durationIlSt5ratioIL2833961'/>
<fun r='_ZN12lldb_private6ModuleC1ERKNS_10ModuleSpecE'/>
<fun r='_ZN12lldb_private6Module26CreateModuleFromObjectFileEDpOT0_'/>
<fun r='_ZN12lldb_private6ModuleD1Ev'/>
<fun r='_ZN12lldb_private6Module17MatchesModuleSpecERKNS_10ModuleSpecE'/>
<fun r='_ZN12lldb_private6Module14SetLoadAddressERNS_6TargetEmbRb'/>
<fun r='_ZN12lldb_private6Module22CalculateSymbolContextEPNS_13SymbolContextE'/>
<fun r='_ZN12lldb_private6Module28CalculateSymbolContextModuleEv'/>
<fun r='_ZN12lldb_private6Module14GetDescriptionERN4llvm11raw_ostreamEN4lldb16DescriptionLevelE'/>
<fun r='_ZNK12lldb_private6Module27GetSpecificationDescriptionB5cxx11Ev'/>
<fun r='_ZN12lldb_private6Module4DumpEPNS_6StreamE'/>
<fun r='_ZN12lldb_private6Module17DumpSymbolContextEPNS_6StreamE'/>
<fun r='_ZN12lldb_private6Module30FindFirstSymbolWithNameAndTypeENS_11ConstStringEN4lldb10SymbolTypeE'/>
<fun r='_ZN12lldb_private6Module26FindSymbolsWithNameAndTypeENS_11ConstStringEN4lldb10SymbolTypeERNS_17SymbolContextListE'/>
<fun r='_ZN12lldb_private6Module31FindSymbolsMatchingRegExAndTypeERKNS_17RegularExpressionEN4lldb10SymbolTypeERNS_17SymbolContextListE'/>
<fun r='_ZN12lldb_private6Module19FindFunctionSymbolsENS_11ConstStringEjRNS_17SymbolContextListE'/>
<fun r='_ZN12lldb_private6Module16FindCompileUnitsERKNS_8FileSpecERNS_17SymbolContextListE'/>
<fun r='_ZN12lldb_private6Module13FindFunctionsENS_11ConstStringERKNS_19CompilerDeclContextEN4lldb16FunctionNameTypeEbbRNS_17SymbolContextListE'/>
<fun r='_ZN12lldb_private6Module13FindFunctionsERKNS_17RegularExpressionEbbRNS_17SymbolContextListE'/>
<fun r='_ZN12lldb_private6Module20FindAddressesForLineESt10shared_ptrINS_6TargetEERKNS_8FileSpecEjPNS_8FunctionERSt6vectorINS_7AddressESaISA_EESD_'/>
<fun r='_ZN12lldb_private6Module19FindGlobalVariablesENS_11ConstStringERKNS_19CompilerDeclContextEmRNS_12VariableListE'/>
<fun r='_ZN12lldb_private6Module19FindGlobalVariablesERKNS_17RegularExpressionEmRNS_12VariableListE'/>
<fun r='_ZN12lldb_private6Module9FindTypesENS_11ConstStringEbmRN4llvm8DenseSetIPNS_10SymbolFileENS2_12DenseMapInfoIS5_EEEERNS_8TypeListE'/>
<fun r='_ZN12lldb_private6Module9FindTypesEN4llvm8ArrayRefINS_15CompilerContextEEENS_11LanguageSetERNS1_8DenseSetIPNS_10SymbolFileENS1_12DenseMapInfoIS8_EEEERNS_7TypeMapE'/>
<fun r='_ZN12lldb_private6Module13FindFirstTypeERKNS_13SymbolContextENS_11ConstStringEb'/>
<fun r='_ZN12lldb_private6Module20FindTypesInNamespaceENS_11ConstStringERKNS_19CompilerDeclContextEmRNS_8TypeListE'/>
<fun r='_ZNK12lldb_private6Module15GetArchitectureEv'/>
<fun r='_ZNK12lldb_private6Module11GetFileSpecEv'/>
<fun r='_ZNK12lldb_private6Module19GetPlatformFileSpecEv'/>
<fun r='_ZN12lldb_private6Module19SetPlatformFileSpecERKNS_8FileSpecE'/>
<fun r='_ZNK12lldb_private6Module24GetRemoteInstallFileSpecEv'/>
<fun r='_ZN12lldb_private6Module24SetRemoteInstallFileSpecERKNS_8FileSpecE'/>
<fun r='_ZNK12lldb_private6Module21GetSymbolFileFileSpecEv'/>
<fun r='_ZN12lldb_private6Module14PreloadSymbolsEv'/>
<fun r='_ZN12lldb_private6Module21SetSymbolFileFileSpecERKNS_8FileSpecE'/>
<fun r='_ZNK12lldb_private6Module19GetModificationTimeEv'/>
<fun r='_ZNK12lldb_private6Module25GetObjectModificationTimeEv'/>
<fun r='_ZN12lldb_private6Module16RegisterXcodeSDKEN4llvm9StringRefES2_'/>
<fun r='_ZN12lldb_private6Module12IsExecutableEv'/>
<fun r='_ZN12lldb_private6Module16IsLoadedInTargetEPNS_6TargetE'/>
<fun r='_ZN12lldb_private6Module29LoadScriptingResourceInTargetEPNS_6TargetERNS_6StatusEPNS_6StreamE'/>
<fun r='_ZN12lldb_private6Module18GetNumCompileUnitsEv'/>
<fun r='_ZN12lldb_private6Module21GetCompileUnitAtIndexEm'/>
<fun r='_ZNK12lldb_private6Module13GetObjectNameEv'/>
<fun r='_ZNK12lldb_private6Module15GetObjectOffsetEv'/>
<fun r='_ZN12lldb_private6Module13GetObjectFileEv'/>
<fun r='_ZN12lldb_private6Module14GetSectionListEv'/>
<fun r='_ZN12lldb_private6Module27SectionFileAddressesChangedEv'/>
<fun r='_ZN12lldb_private6Module14GetUnwindTableEv'/>
<fun r='_ZN12lldb_private6Module10GetVersionEv'/>
<fun r='_ZN12lldb_private6Module19GetMemoryObjectFileERKSt10shared_ptrINS_7ProcessEEmRNS_6StatusEm'/>
<fun r='_ZN12lldb_private6Module13GetSymbolFileEbPNS_6StreamE'/>
<fun r='_ZN12lldb_private6Module9GetSymtabEv'/>
<fun r='_ZN12lldb_private6Module7GetUUIDEv'/>
<fun r='_ZN12lldb_private6Module20ParseAllDebugSymbolsEv'/>
<fun r='_ZN12lldb_private6Module18ResolveFileAddressEmRNS_7AddressE'/>
<fun r='_ZN12lldb_private6Module30ResolveSymbolContextForAddressERKNS_7AddressEN4lldb17SymbolContextItemERNS_13SymbolContextEb'/>
<fun r='_ZN12lldb_private6Module31ResolveSymbolContextForFilePathEPKcjbN4lldb17SymbolContextItemERNS_17SymbolContextListE'/>
<fun r='_ZN12lldb_private6Module32ResolveSymbolContextsForFileSpecERKNS_8FileSpecEjbN4lldb17SymbolContextItemERNS_17SymbolContextListE'/>
<fun r='_ZN12lldb_private6Module24SetFileSpecAndObjectNameERKNS_8FileSpecENS_11ConstStringE'/>
<fun r='_ZN12lldb_private6Module22GetIsDynamicLinkEditorEv'/>
<fun r='_ZN12lldb_private6Module24GetTypeSystemForLanguageEN4lldb12LanguageTypeE'/>
<fun r='_ZN12lldb_private6Module10LogMessageEPNS_3LogEPKcz'/>
<fun r='_ZN12lldb_private6Module26LogMessageVerboseBacktraceEPNS_3LogEPKcz'/>
<fun r='_ZN12lldb_private6Module13ReportWarningEPKcz'/>
<fun r='_ZN12lldb_private6Module11ReportErrorEPKcz'/>
<fun r='_ZN12lldb_private6Module27ReportErrorIfModifyDetectedEPKcz'/>
<fun r='_ZNK12lldb_private6Module14FileHasChangedEv'/>
<fun r='_ZNK12lldb_private6Module8GetMutexEv'/>
<fun r='_ZN12lldb_private6Module20GetSourceMappingListEv'/>
<fun r='_ZNK12lldb_private6Module20GetSourceMappingListEv'/>
<fun r='_ZNK12lldb_private6Module14FindSourceFileERKNS_8FileSpecERS1_'/>
<fun r='_ZNK12lldb_private6Module15RemapSourceFileEN4llvm9StringRefERNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE'/>
<fun r='_ZNK12lldb_private6Module15RemapSourceFileEPKcRNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE'/>
<fun r='_ZN12lldb_private6Module17MergeArchitectureERKNS_8ArchSpecE'/>
<mbr r='lldb_private::Module::m_mutex' o='192' t='std::recursive_mutex'/>
<mbr r='lldb_private::Module::m_mod_time' o='512' t='llvm::sys::TimePoint&lt;&gt;'/>
<mbr r='lldb_private::Module::m_arch' o='576' t='lldb_private::ArchSpec'/>
<mbr r='lldb_private::Module::m_uuid' o='1216' t='lldb_private::UUID'/>
<mbr r='lldb_private::Module::m_file' o='1600' t='lldb_private::FileSpec'/>
<mbr r='lldb_private::Module::m_platform_file' o='1792' t='lldb_private::FileSpec'/>
<mbr r='lldb_private::Module::m_remote_install_file' o='1984' t='lldb_private::FileSpec'/>
<mbr r='lldb_private::Module::m_symfile_spec' o='2176' t='lldb_private::FileSpec'/>
<mbr r='lldb_private::Module::m_object_name' o='2368' t='lldb_private::ConstString'/>
<mbr r='lldb_private::Module::m_object_offset' o='2432' t='uint64_t'/>
<mbr r='lldb_private::Module::m_object_mod_time' o='2496' t='llvm::sys::TimePoint&lt;&gt;'/>
<mbr r='lldb_private::Module::m_data_sp' o='2560' t='lldb::DataBufferSP'/>
<mbr r='lldb_private::Module::m_objfile_sp' o='2688' t='lldb::ObjectFileSP'/>
<mbr r='lldb_private::Module::m_unwind_table' o='2816' t='llvm::Optional&lt;UnwindTable&gt;'/>
<mbr r='lldb_private::Module::m_symfile_up' o='4032' t='lldb::SymbolVendorUP'/>
<mbr r='lldb_private::Module::m_old_symfiles' o='4096' t='std::vector&lt;lldb::SymbolVendorUP&gt;'/>
<mbr r='lldb_private::Module::m_type_system_map' o='4288' t='lldb_private::TypeSystemMap'/>
<mbr r='lldb_private::Module::m_source_mappings' o='5056' t='lldb_private::PathMappingList'/>
<mbr r='lldb_private::Module::m_sections_up' o='5440' t='lldb::SectionListUP'/>
<mbr r='lldb_private::Module::m_did_load_objfile' o='5504' t='std::atomic&lt;bool&gt;'/>
<mbr r='lldb_private::Module::m_did_load_symfile' o='5512' t='std::atomic&lt;bool&gt;'/>
<mbr r='lldb_private::Module::m_did_set_uuid' o='5520' t='std::atomic&lt;bool&gt;'/>
<mbr r='lldb_private::Module::m_file_has_changed' o='5528' t='bool'/>
<mbr r='lldb_private::Module::m_first_file_changed_log' o='5529' t='bool'/>
<fun r='_ZN12lldb_private6Module30ResolveSymbolContextForAddressEmbN4lldb17SymbolContextItemERNS_7AddressERNS_13SymbolContextE'/>
<fun r='_ZN12lldb_private6Module32SymbolIndicesToSymbolContextListEPNS_6SymtabERSt6vectorIjSaIjEERNS_17SymbolContextListE'/>
<fun r='_ZN12lldb_private6Module15SetArchitectureERKNS_8ArchSpecE'/>
<fun r='_ZN12lldb_private6Module7SetUUIDERKNS_4UUIDE'/>
<fun r='_ZN12lldb_private6Module21GetUnifiedSectionListEv'/>
<fun r='_ZN12lldb_private6ModuleC1Ev'/>
<fun r='_ZN12lldb_private6Module14FindTypes_ImplENS_11ConstStringERKNS_19CompilerDeclContextEmRN4llvm8DenseSetIPNS_10SymbolFileENS5_12DenseMapInfoIS8_EEEERNS_7TypeMapE'/>
<fun r='_ZN12lldb_private6ModuleC1ERKS0_'/>
<fun r='_ZN12lldb_private6ModuleaSERKS0_'/>
<use f='llvm/lldb/include/lldb/Target/Process.h' l='987' c='_ZN12lldb_private7Process10WillLaunchEPNS_6ModuleE'/>
<use f='llvm/lldb/include/lldb/Target/Process.h' l='1006' c='_ZN12lldb_private7Process8DoLaunchEPNS_6ModuleERNS_17ProcessLaunchInfoE'/>
<use f='llvm/lldb/include/lldb/Core/Value.h' l='130' c='_ZN12lldb_private5Value14GetValueAsDataEPNS_16ExecutionContextERNS_13DataExtractorEPNS_6ModuleE'/>
<use f='llvm/lldb/include/lldb/Core/Value.h' l='137' c='_ZN12lldb_private5Value20ConvertToLoadAddressEPNS_6ModuleEPNS_6TargetE'/>
<use f='llvm/lldb/include/lldb/Target/Platform.h' l='301' c='_ZN12lldb_private8Platform34LocateExecutableScriptingResourcesEPNS_6TargetERNS_6ModuleEPNS_6StreamE'/>
<use f='llvm/lldb/include/lldb/Symbol/CompileUnit.h' l='258' c='_ZN12lldb_private11CompileUnit21ForEachExternalModuleERN4llvm8DenseSetIPNS_10SymbolFileENS1_12DenseMapInfoIS4_EEEENS1_12function_refIFbRNS_6ModuleEEEE'/>
<use f='llvm/lldb/include/lldb/Symbol/SymbolFile.h' l='167' c='_ZN12lldb_private10SymbolFile21ForEachExternalModuleERNS_11CompileUnitERN4llvm8DenseSetIPS0_NS3_12DenseMapInfoIS5_EEEENS3_12function_refIFbRNS_6ModuleEEEE'/>
<size>696</size>
<use f='llvm/lldb/source/API/SBProcess.cpp' l='151' c='_ZN4lldb9SBProcess12RemoteLaunchEPPKcS3_S2_S2_S2_S2_jbRNS_7SBErrorE'/>
<use f='llvm/lldb/source/API/SBProcess.cpp' l='999' c='_ZN4lldb9SBProcess14GetDescriptionERNS_8SBStreamE'/>
<size>696</size>
<use f='llvm/lldb/include/lldb/Core/ValueObjectConstResult.h' l='59' c='_ZN12lldb_private22ValueObjectConstResult6CreateEPNS_21ExecutionContextScopeERNS_5ValueENS_11ConstStringEPNS_6ModuleE'/>
<use f='llvm/lldb/include/lldb/Core/ValueObjectConstResult.h' l='148' c='_ZN12lldb_private22ValueObjectConstResultC1EPNS_21ExecutionContextScopeERNS_14ClusterManagerINS_11ValueObjectEEERKNS_5ValueENS_11ConstStringEPNS_6ModuleE'/>
<use f='llvm/lldb/source/API/SBTarget.cpp' l='296' c='_ZN4lldb8SBTarget12LaunchSimpleEPPKcS3_S2_'/>
<use f='llvm/lldb/source/API/SBTarget.cpp' l='380' c='_ZN4lldb8SBTarget6LaunchERNS_10SBListenerEPPKcS5_S4_S4_S4_S4_jbRNS_7SBErrorE'/>
<use f='llvm/lldb/source/API/SBTarget.cpp' l='440' c='_ZN4lldb8SBTarget6LaunchERNS_12SBLaunchInfoERNS_7SBErrorE'/>
<use f='llvm/lldb/source/API/SBTarget.cpp' l='595' c='_ZN4lldb8SBTarget13GetExecutableEv'/>
<size>696</size>
<use f='llvm/lldb/source/Breakpoint/BreakpointLocationList.cpp' l='81' c='_ZN12lldb_private22BreakpointLocationList12FindInModuleEPNS_6ModuleERNS_28BreakpointLocationCollectionE'/>
<size>696</size>
<use f='llvm/lldb/source/Commands/CommandObjectPlatform.cpp' l='1033' c='_ZN34CommandObjectPlatformProcessLaunch9DoExecuteERN12lldb_private4ArgsERNS0_19CommandReturnObjectE'/>
<size>696</size>
<use f='llvm/lldb/source/Commands/CommandObjectSource.cpp' l='153' c='_ZN23CommandObjectSourceInfo25DumpLinesInSymbolContextsERN12lldb_private6StreamERKNS0_17SymbolContextListERKNS0_10ModuleListERKNS0_8FileSpecE'/>
<use f='llvm/lldb/source/Commands/CommandObjectSource.cpp' l='196' c='_ZN23CommandObjectSourceInfo23DumpFileLinesInCompUnitERN12lldb_private6StreamEPNS0_6ModuleEPNS0_11CompileUnitERKNS0_8FileSpecE'/>
<use f='llvm/lldb/source/Commands/CommandObjectSource.cpp' l='277' c='_ZN23CommandObjectSourceInfo21DumpFileLinesInModuleERN12lldb_private6StreamEPNS0_6ModuleERKNS0_8FileSpecE'/>
<use f='llvm/lldb/source/Commands/CommandObjectSource.cpp' l='498' c='_ZN23CommandObjectSourceInfo16DumpLinesForFileERN12lldb_private19CommandReturnObjectE'/>
<size>696</size>
<use f='llvm/lldb/source/Commands/CommandObjectTarget.cpp' l='66' c='_ZL14DumpTargetInfojPN12lldb_private6TargetEPKcbRNS_6StreamE'/>
<use f='llvm/lldb/source/Commands/CommandObjectTarget.cpp' l='1300' c='_ZL22DumpModuleArchitectureRN12lldb_private6StreamEPNS_6ModuleEbj'/>
<use f='llvm/lldb/source/Commands/CommandObjectTarget.cpp' l='1318' c='_ZL14DumpModuleUUIDRN12lldb_private6StreamEPNS_6ModuleE'/>
<use f='llvm/lldb/source/Commands/CommandObjectTarget.cpp' l='1326' c='_ZL24DumpCompileUnitLineTableRN12lldb_private18CommandInterpreterERNS_6StreamEPNS_6ModuleERKNS_8FileSpecEN4lldb16DescriptionLevelE'/>
<use f='llvm/lldb/source/Commands/CommandObjectTarget.cpp' l='1430' c='_ZL16DumpModuleSymtabRN12lldb_private18CommandInterpreterERNS_6StreamEPNS_6ModuleENS_9SortOrderENS_7Mangled14NamePreferenceE'/>
<use f='llvm/lldb/source/Commands/CommandObjectTarget.cpp' l='1440' c='_ZL18DumpModuleSectionsRN12lldb_private18CommandInterpreterERNS_6StreamEPNS_6ModuleE'/>
<use f='llvm/lldb/source/Commands/CommandObjectTarget.cpp' l='1454' c='_ZL20DumpModuleSymbolFileRN12lldb_private6StreamEPNS_6ModuleE'/>
<use f='llvm/lldb/source/Commands/CommandObjectTarget.cpp' l='1486' c='_ZL21LookupAddressInModuleRN12lldb_private18CommandInterpreterERNS_6StreamEPNS_6ModuleEjmmb'/>
<use f='llvm/lldb/source/Commands/CommandObjectTarget.cpp' l='1536' c='_ZL20LookupSymbolInModuleRN12lldb_private18CommandInterpreterERNS_6StreamEPNS_6ModuleEPKcbb'/>
<use f='llvm/lldb/source/Commands/CommandObjectTarget.cpp' l='1600' c='_ZL22LookupFunctionInModuleRN12lldb_private18CommandInterpreterERNS_6StreamEPNS_6ModuleEPKcbbbb'/>
<use f='llvm/lldb/source/Commands/CommandObjectTarget.cpp' l='1635' c='_ZL18LookupTypeInModulePN12lldb_private6TargetERNS_18CommandInterpreterERNS_6StreamEPNS_6ModuleEPKcb'/>
<use f='llvm/lldb/source/Commands/CommandObjectTarget.cpp' l='1683' c='_ZL14LookupTypeHerePN12lldb_private6TargetERNS_18CommandInterpreterERNS_6StreamERNS_6ModuleEPKcb'/>
<use f='llvm/lldb/source/Commands/CommandObjectTarget.cpp' l='1727' c='_ZL25LookupFileAndLineInModuleRN12lldb_private18CommandInterpreterERNS_6StreamEPNS_6ModuleERKNS_8FileSpecEjbb'/>
<use f='llvm/lldb/source/Commands/CommandObjectTarget.cpp' l='1769' c='_ZL17FindModulesByNamePN12lldb_private6TargetEPKcRNS_10ModuleListEb'/>
<use f='llvm/lldb/source/Commands/CommandObjectTarget.cpp' l='2149' c='_ZN38CommandObjectTargetModulesDumpSections9DoExecuteERN12lldb_private4ArgsERNS0_19CommandReturnObjectE'/>
<use f='llvm/lldb/source/Commands/CommandObjectTarget.cpp' l='2237' c='_ZN38CommandObjectTargetModulesDumpClangAST9DoExecuteERN12lldb_private4ArgsERNS0_19CommandReturnObjectE'/>
<use f='llvm/lldb/source/Commands/CommandObjectTarget.cpp' l='2303' c='_ZN37CommandObjectTargetModulesDumpSymfile9DoExecuteERN12lldb_private4ArgsERNS0_19CommandReturnObjectE'/>
<use f='llvm/lldb/source/Commands/CommandObjectTarget.cpp' l='2710' c='_ZN30CommandObjectTargetModulesLoad9DoExecuteERN12lldb_private4ArgsERNS0_19CommandReturnObjectE'/>
<use f='llvm/lldb/source/Commands/CommandObjectTarget.cpp' l='3056' c='_ZN30CommandObjectTargetModulesList9DoExecuteERN12lldb_private4ArgsERNS0_19CommandReturnObjectE'/>
<use f='llvm/lldb/source/Commands/CommandObjectTarget.cpp' l='3090' c='_ZN30CommandObjectTargetModulesList11PrintModuleEPN12lldb_private6TargetEPNS0_6ModuleEiRNS0_6StreamE'/>
<use f='llvm/lldb/source/Commands/CommandObjectTarget.cpp' l='3785' c='_ZN32CommandObjectTargetModulesLookup14LookupInModuleERN12lldb_private18CommandInterpreterEPNS0_6ModuleERNS0_19CommandReturnObjectERb'/>
<use f='llvm/lldb/source/Commands/CommandObjectTarget.cpp' l='3920' c='_ZN32CommandObjectTargetModulesLookup9DoExecuteERN12lldb_private4ArgsERNS0_19CommandReturnObjectE'/>
<size>696</size>
<use f='llvm/lldb/source/Core/Address.cpp' l='920' c='_ZN12lldb_private7Address29CompareModulePointerAndOffsetERKS0_S2_'/>
<use f='llvm/lldb/source/Core/Address.cpp' l='921' c='_ZN12lldb_private7Address29CompareModulePointerAndOffsetERKS0_S2_'/>
<use f='llvm/lldb/source/Core/Address.cpp' l='958' c='_ZN12lldb_privateltERKNS_7AddressES2_'/>
<use f='llvm/lldb/source/Core/Address.cpp' l='959' c='_ZN12lldb_privateltERKNS_7AddressES2_'/>
<use f='llvm/lldb/source/Core/Address.cpp' l='973' c='_ZN12lldb_privategtERKNS_7AddressES2_'/>
<use f='llvm/lldb/source/Core/Address.cpp' l='974' c='_ZN12lldb_privategtERKNS_7AddressES2_'/>
<size>696</size>
<use f='llvm/lldb/source/Core/DynamicLoader.cpp' l='82' c='_ZN12lldb_private13DynamicLoader19GetTargetExecutableEv'/>
<size>696</size>
<use f='llvm/lldb/source/Core/FormatEntity.cpp' l='1174' c='_ZN12lldb_private12FormatEntity6FormatERKNS0_5EntryERNS_6StreamEPKNS_13SymbolContextEPKNS_16ExecutionContextEPKNS_7AddressEPNS_11ValueObjectEbb'/>
<use f='llvm/lldb/source/Core/FormatEntity.cpp' l='1380' c='_ZN12lldb_private12FormatEntity6FormatERKNS0_5EntryERNS_6StreamEPKNS_13SymbolContextEPKNS_16ExecutionContextEPKNS_7AddressEPNS_11ValueObjectEbb'/>
<use f='llvm/lldb/source/Core/FormatEntity.cpp' l='1831' c='_ZN12lldb_private12FormatEntity6FormatERKNS0_5EntryERNS_6StreamEPKNS_13SymbolContextEPKNS_16ExecutionContextEPKNS_7AddressEPNS_11ValueObjectEbb'/>
<size>696</size>
<use f='llvm/lldb/source/Core/Module.cpp' l='84'/>
<use f='llvm/lldb/source/Core/Module.cpp' l='118' c='_ZN12lldb_private6Module25GetAllocatedModuleAtIndexEm'/>
<size>696</size>
<fun r='_ZN12lldb_private6Module34GetAllocationModuleCollectionMutexEv'/>
<fun r='_ZN12lldb_private6Module25GetNumberAllocatedModulesEv'/>
<fun r='_ZN12lldb_private6Module25GetAllocatedModuleAtIndexEm'/>
<fun r='_ZN12lldb_private6ModuleC1ERKNS_10ModuleSpecE'/>
<fun r='_ZN12lldb_private6ModuleC1ERKNS_8FileSpecERKNS_8ArchSpecEPKNS_11ConstStringEmRKNSt6chrono10time_pointINSA_3_V212system_clockENSA_8durationIlSt5ratioIL2833961'/>
<fun r='_ZN12lldb_private6ModuleC1Ev'/>
<fun r='_ZN12lldb_private6ModuleD1Ev'/>
<fun r='_ZN12lldb_private6Module19GetMemoryObjectFileERKSt10shared_ptrINS_7ProcessEEmRNS_6StatusEm'/>
<fun r='_ZN12lldb_private6Module7GetUUIDEv'/>
<fun r='_ZN12lldb_private6Module7SetUUIDERKNS_4UUIDE'/>
<fun r='_ZN12lldb_private6Module24GetTypeSystemForLanguageEN4lldb12LanguageTypeE'/>
<fun r='_ZN12lldb_private6Module20ParseAllDebugSymbolsEv'/>
<fun r='_ZN12lldb_private6Module22CalculateSymbolContextEPNS_13SymbolContextE'/>
<fun r='_ZN12lldb_private6Module28CalculateSymbolContextModuleEv'/>
<fun r='_ZN12lldb_private6Module17DumpSymbolContextEPNS_6StreamE'/>
<fun r='_ZN12lldb_private6Module18GetNumCompileUnitsEv'/>
<fun r='_ZN12lldb_private6Module21GetCompileUnitAtIndexEm'/>
<fun r='_ZN12lldb_private6Module18ResolveFileAddressEmRNS_7AddressE'/>
<fun r='_ZN12lldb_private6Module30ResolveSymbolContextForAddressERKNS_7AddressEN4lldb17SymbolContextItemERNS_13SymbolContextEb'/>
<fun r='_ZN12lldb_private6Module31ResolveSymbolContextForFilePathEPKcjbN4lldb17SymbolContextItemERNS_17SymbolContextListE'/>
<fun r='_ZN12lldb_private6Module32ResolveSymbolContextsForFileSpecERKNS_8FileSpecEjbN4lldb17SymbolContextItemERNS_17SymbolContextListE'/>
<fun r='_ZN12lldb_private6Module19FindGlobalVariablesENS_11ConstStringERKNS_19CompilerDeclContextEmRNS_12VariableListE'/>
<fun r='_ZN12lldb_private6Module19FindGlobalVariablesERKNS_17RegularExpressionEmRNS_12VariableListE'/>
<fun r='_ZN12lldb_private6Module16FindCompileUnitsERKNS_8FileSpecERNS_17SymbolContextListE'/>
<fun r='_ZN12lldb_private6Module13FindFunctionsENS_11ConstStringERKNS_19CompilerDeclContextEN4lldb16FunctionNameTypeEbbRNS_17SymbolContextListE'/>
<fun r='_ZN12lldb_private6Module13FindFunctionsERKNS_17RegularExpressionEbbRNS_17SymbolContextListE'/>
<fun r='_ZN12lldb_private6Module20FindAddressesForLineESt10shared_ptrINS_6TargetEERKNS_8FileSpecEjPNS_8FunctionERSt6vectorINS_7AddressESaISA_EESD_'/>
<fun r='_ZN12lldb_private6Module14FindTypes_ImplENS_11ConstStringERKNS_19CompilerDeclContextEmRN4llvm8DenseSetIPNS_10SymbolFileENS5_12DenseMapInfoIS8_EEEERNS_7TypeMapE'/>
<fun r='_ZN12lldb_private6Module20FindTypesInNamespaceENS_11ConstStringERKNS_19CompilerDeclContextEmRNS_8TypeListE'/>
<fun r='_ZN12lldb_private6Module13FindFirstTypeERKNS_13SymbolContextENS_11ConstStringEb'/>
<fun r='_ZN12lldb_private6Module9FindTypesENS_11ConstStringEbmRN4llvm8DenseSetIPNS_10SymbolFileENS2_12DenseMapInfoIS5_EEEERNS_8TypeListE'/>
<fun r='_ZN12lldb_private6Module9FindTypesEN4llvm8ArrayRefINS_15CompilerContextEEENS_11LanguageSetERNS1_8DenseSetIPNS_10SymbolFileENS1_12DenseMapInfoIS8_EEEERNS_7TypeMapE'/>
<fun r='_ZN12lldb_private6Module13GetSymbolFileEbPNS_6StreamE'/>
<fun r='_ZN12lldb_private6Module9GetSymtabEv'/>
<fun r='_ZN12lldb_private6Module24SetFileSpecAndObjectNameERKNS_8FileSpecENS_11ConstStringE'/>
<fun r='_ZNK12lldb_private6Module15GetArchitectureEv'/>
<fun r='_ZNK12lldb_private6Module27GetSpecificationDescriptionB5cxx11Ev'/>
<fun r='_ZN12lldb_private6Module14GetDescriptionERN4llvm11raw_ostreamEN4lldb16DescriptionLevelE'/>
<fun r='_ZN12lldb_private6Module11ReportErrorEPKcz'/>
<fun r='_ZNK12lldb_private6Module14FileHasChangedEv'/>
<fun r='_ZN12lldb_private6Module27ReportErrorIfModifyDetectedEPKcz'/>
<fun r='_ZN12lldb_private6Module13ReportWarningEPKcz'/>
<fun r='_ZN12lldb_private6Module10LogMessageEPNS_3LogEPKcz'/>
<fun r='_ZN12lldb_private6Module26LogMessageVerboseBacktraceEPNS_3LogEPKcz'/>
<fun r='_ZN12lldb_private6Module4DumpEPNS_6StreamE'/>
<fun r='_ZNK12lldb_private6Module13GetObjectNameEv'/>
<fun r='_ZN12lldb_private6Module13GetObjectFileEv'/>
<fun r='_ZN12lldb_private6Module14GetSectionListEv'/>
<fun r='_ZN12lldb_private6Module27SectionFileAddressesChangedEv'/>
<fun r='_ZN12lldb_private6Module14GetUnwindTableEv'/>
<fun r='_ZN12lldb_private6Module21GetUnifiedSectionListEv'/>
<fun r='_ZN12lldb_private6Module30FindFirstSymbolWithNameAndTypeENS_11ConstStringEN4lldb10SymbolTypeE'/>
<fun r='_ZN12lldb_private6Module32SymbolIndicesToSymbolContextListEPNS_6SymtabERSt6vectorIjSaIjEERNS_17SymbolContextListE'/>
<fun r='_ZN12lldb_private6Module19FindFunctionSymbolsENS_11ConstStringEjRNS_17SymbolContextListE'/>
<fun r='_ZN12lldb_private6Module26FindSymbolsWithNameAndTypeENS_11ConstStringEN4lldb10SymbolTypeERNS_17SymbolContextListE'/>
<fun r='_ZN12lldb_private6Module31FindSymbolsMatchingRegExAndTypeERKNS_17RegularExpressionEN4lldb10SymbolTypeERNS_17SymbolContextListE'/>
<fun r='_ZN12lldb_private6Module14PreloadSymbolsEv'/>
<fun r='_ZN12lldb_private6Module21SetSymbolFileFileSpecERKNS_8FileSpecE'/>
<fun r='_ZN12lldb_private6Module12IsExecutableEv'/>
<fun r='_ZN12lldb_private6Module16IsLoadedInTargetEPNS_6TargetE'/>
<fun r='_ZN12lldb_private6Module29LoadScriptingResourceInTargetEPNS_6TargetERNS_6StatusEPNS_6StreamE'/>
<fun r='_ZN12lldb_private6Module15SetArchitectureERKNS_8ArchSpecE'/>
<fun r='_ZN12lldb_private6Module14SetLoadAddressERNS_6TargetEmbRb'/>
<fun r='_ZN12lldb_private6Module17MatchesModuleSpecERKNS_10ModuleSpecE'/>
<fun r='_ZNK12lldb_private6Module14FindSourceFileERKNS_8FileSpecERS1_'/>
<fun r='_ZNK12lldb_private6Module15RemapSourceFileEN4llvm9StringRefERNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE'/>
<fun r='_ZN12lldb_private6Module16RegisterXcodeSDKEN4llvm9StringRefES2_'/>
<fun r='_ZN12lldb_private6Module17MergeArchitectureERKNS_8ArchSpecE'/>
<fun r='_ZN12lldb_private6Module10GetVersionEv'/>
<fun r='_ZN12lldb_private6Module22GetIsDynamicLinkEditorEv'/>
<use f='llvm/lldb/source/Core/ModuleList.cpp' l='273' c='_ZN12lldb_private10ModuleList16RemoveIfOrphanedEPKNS_6ModuleE'/>
<use f='llvm/lldb/source/Core/ModuleList.cpp' l='347' c='_ZNK12lldb_private10ModuleList23GetModulePointerAtIndexEm'/>
<use f='llvm/lldb/source/Core/ModuleList.cpp' l='493' c='_ZNK12lldb_private10ModuleList10FindModuleEPKNS_6ModuleE'/>
<use f='llvm/lldb/source/Core/ModuleList.cpp' l='528' c='_ZNK12lldb_private10ModuleList9FindTypesEPNS_6ModuleENS_11ConstStringEbmRN4llvm8DenseSetIPNS_10SymbolFileENS4_12DenseMapInfoIS7_EEEERNS_8TypeListE'/>
<use f='llvm/lldb/source/Core/ModuleList.cpp' l='619' c='_ZN12lldb_private10ModuleList15LogUUIDAndPathsEPNS_3LogEPKc'/>
<use f='llvm/lldb/source/Core/ModuleList.cpp' l='687' c='_ZNK12lldb_private10ModuleList17GetIndexForModuleEPKNS_6ModuleE'/>
<use f='llvm/lldb/source/Core/ModuleList.cpp' l='729' c='_ZN12lldb_private10ModuleList15ModuleIsInCacheEPKNS_6ModuleE'/>
<use f='llvm/lldb/source/Core/ModuleList.cpp' l='806' c='_ZN12lldb_private10ModuleList15GetSharedModuleERKNS_10ModuleSpecERSt10shared_ptrINS_6ModuleEEPKNS_12FileSpecListEPN4llvm15SmallVectorImplIS6_EEPbb'/>
<use f='llvm/lldb/source/Core/ModuleList.cpp' l='848' c='_ZN12lldb_private10ModuleList15GetSharedModuleERKNS_10ModuleSpecERSt10shared_ptrINS_6ModuleEEPKNS_12FileSpecListEPN4llvm15SmallVectorImplIS6_EEPbb'/>
<use f='llvm/lldb/source/Core/ModuleList.cpp' l='947' c='_ZN12lldb_private10ModuleList15GetSharedModuleERKNS_10ModuleSpecERSt10shared_ptrINS_6ModuleEEPKNS_12FileSpecListEPN4llvm15SmallVectorImplIS6_EEPbb'/>
<use f='llvm/lldb/source/Core/ModuleList.cpp' l='994' c='_ZN12lldb_private10ModuleList28RemoveSharedModuleIfOrphanedEPKNS_6ModuleE'/>
<size>696</size>
<use f='llvm/lldb/source/Core/SourceManager.cpp' l='338' c='_ZN12lldb_private13SourceManager21GetDefaultFileAndLineERNS_8FileSpecERj'/>
<size>696</size>
<use f='llvm/lldb/source/Core/Value.cpp' l='300' c='_ZN12lldb_private5Value14GetValueAsDataEPNS_16ExecutionContextERNS_13DataExtractorEPNS_6ModuleE'/>
<use f='llvm/lldb/source/Core/Value.cpp' l='646' c='_ZN12lldb_private5Value20ConvertToLoadAddressEPNS_6ModuleEPNS_6TargetE'/>
<size>696</size>
<use f='llvm/lldb/source/Core/ValueObjectConstResult.cpp' l='101' c='_ZN12lldb_private22ValueObjectConstResult6CreateEPNS_21ExecutionContextScopeERNS_5ValueENS_11ConstStringEPNS_6ModuleE'/>
<use f='llvm/lldb/source/Core/ValueObjectConstResult.cpp' l='187' c='_ZN12lldb_private22ValueObjectConstResultC1EPNS_21ExecutionContextScopeERNS_14ClusterManagerINS_11ValueObjectEEERKNS_5ValueENS_11ConstStringEPNS_6ModuleE'/>
<use f='llvm/lldb/source/Plugins/SymbolFile/DWARF/DWARFIndex.h' l='22' c='_ZN12lldb_private10DWARFIndexC1ERNS_6ModuleE'/>
<use f='llvm/lldb/source/Plugins/SymbolFile/DWARF/DWARFIndex.h' l='65'/>
<use f='llvm/lldb/source/Plugins/SymbolFile/DWARF/SymbolFileDWARF.h' l='120' c='_ZN15SymbolFileDWARF21ForEachExternalModuleERN12lldb_private11CompileUnitERN4llvm8DenseSetIPNS0_10SymbolFileENS3_12DenseMapInfoIS6_EEEENS3_12function_5131787'/>
<size>696</size>
<use f='llvm/lldb/source/Plugins/TypeSystem/Clang/TypeSystemClang.h' l='148' c='_ZN12lldb_private15TypeSystemClang14CreateInstanceEN4lldb12LanguageTypeEPNS_6ModuleEPNS_6TargetE'/>
<size>696</size>
<use f='llvm/lldb/source/Plugins/DynamicLoader/Darwin-Kernel/DynamicLoaderDarwinKernel.cpp' l='145' c='_ZN25DynamicLoaderDarwinKernel14CreateInstanceEPN12lldb_private7ProcessEb'/>
<use f='llvm/lldb/source/Plugins/DynamicLoader/Darwin-Kernel/DynamicLoaderDarwinKernel.cpp' l='215' c='_ZN25DynamicLoaderDarwinKernel29SearchForKernelAtSameLoadAddrEPN12lldb_private7ProcessE'/>
<use f='llvm/lldb/source/Plugins/DynamicLoader/Darwin-Kernel/DynamicLoaderDarwinKernel.cpp' l='798' c='_ZN25DynamicLoaderDarwinKernel13KextImageInfo26LoadImageUsingMemoryModuleEPN12lldb_private7ProcessE'/>
<size>696</size>
<use f='llvm/lldb/source/Plugins/DynamicLoader/Hexagon-DYLD/DynamicLoaderHexagonDYLD.cpp' l='188' c='_ZN24DynamicLoaderHexagonDYLD19GetTargetExecutableEv'/>
<use f='llvm/lldb/source/Plugins/DynamicLoader/Hexagon-DYLD/DynamicLoaderHexagonDYLD.cpp' l='529' c='_ZN24DynamicLoaderHexagonDYLD13GetEntryPointEv'/>
<use f='llvm/lldb/source/Plugins/DynamicLoader/Hexagon-DYLD/DynamicLoaderHexagonDYLD.cpp' l='602' c='_ZN24DynamicLoaderHexagonDYLD18GetThreadLocalDataESt10shared_ptrIN12lldb_private6ModuleEES0_INS1_6ThreadEEm'/>
<size>696</size>
<use f='llvm/lldb/source/Plugins/DynamicLoader/Hexagon-DYLD/HexagonDYLDRendezvous.cpp' l='55' c='_ZN21HexagonDYLDRendezvousC1EPN12lldb_private7ProcessE'/>
<size>696</size>
<use f='llvm/lldb/source/Plugins/DynamicLoader/MacOSX-DYLD/DynamicLoaderDarwin.h' l='175' c='_ZN12lldb_private19DynamicLoaderDarwin22UpdateImageLoadAddressEPNS_6ModuleERNS0_9ImageInfoE'/>
<use f='llvm/lldb/source/Plugins/DynamicLoader/MacOSX-DYLD/DynamicLoaderDarwin.h' l='177' c='_ZN12lldb_private19DynamicLoaderDarwin20UnloadModuleSectionsEPNS_6ModuleERNS0_9ImageInfoE'/>
<use f='llvm/lldb/source/Plugins/DynamicLoader/MacOSX-DYLD/DynamicLoaderDarwin.cpp' l='243' c='_ZN12lldb_private19DynamicLoaderDarwin22UpdateImageLoadAddressEPNS_6ModuleERNS0_9ImageInfoE'/>
<use f='llvm/lldb/source/Plugins/DynamicLoader/MacOSX-DYLD/DynamicLoaderDarwin.cpp' l='320' c='_ZN12lldb_private19DynamicLoaderDarwin20UnloadModuleSectionsEPNS_6ModuleERNS0_9ImageInfoE'/>
<size>696</size>
<use f='llvm/lldb/source/Plugins/DynamicLoader/MacOSX-DYLD/DynamicLoaderMacOS.h' l='94' c='_ZN18DynamicLoaderMacOS36GetDyldLockVariableAddressFromModuleEPN12lldb_private6ModuleE'/>
<use f='llvm/lldb/source/Plugins/DynamicLoader/MacOSX-DYLD/DynamicLoaderMacOS.cpp' l='39' c='_ZN18DynamicLoaderMacOS14CreateInstanceEPN12lldb_private7ProcessEb'/>
<use f='llvm/lldb/source/Plugins/DynamicLoader/MacOSX-DYLD/DynamicLoaderMacOS.cpp' l='375' c='_ZN18DynamicLoaderMacOS36GetDyldLockVariableAddressFromModuleEPN12lldb_private6ModuleE'/>
<size>696</size>
<use f='llvm/lldb/source/Plugins/DynamicLoader/MacOSX-DYLD/DynamicLoaderMacOSXDYLD.cpp' l='60' c='_ZN23DynamicLoaderMacOSXDYLD14CreateInstanceEPN12lldb_private7ProcessEb'/>
<use f='llvm/lldb/source/Plugins/DynamicLoader/MacOSX-DYLD/DynamicLoaderMacOSXDYLD.cpp' l='230' c='_ZN23DynamicLoaderMacOSXDYLD19DoInitialImageFetchEv'/>
<size>696</size>
<use f='llvm/lldb/source/Plugins/DynamicLoader/POSIX-DYLD/DYLDRendezvous.cpp' l='104' c='_ZN14DYLDRendezvous20UpdateExecutablePathEv'/>
<size>696</size>
<use f='llvm/lldb/source/Plugins/DynamicLoader/POSIX-DYLD/DynamicLoaderPOSIXDYLD.h' l='85'/>
<size>696</size>
<use f='llvm/lldb/source/Plugins/DynamicLoader/Static/DynamicLoaderStatic.cpp' l='48' c='_ZN19DynamicLoaderStatic14CreateInstanceEPN12lldb_private7ProcessEb'/>
<size>696</size>
<use f='llvm/lldb/source/Plugins/ExpressionParser/Clang/ClangExpressionDeclMap.h' l='245' c='_ZN12lldb_private22ClangExpressionDeclMap16GetSymbolAddressERNS_6TargetEPNS_7ProcessENS_11ConstStringEN4lldb10SymbolTypeEPNS_6ModuleE'/>
<use f='llvm/lldb/source/Plugins/ExpressionParser/Clang/ClangExpressionDeclMap.cpp' l='502' c='_ZN12lldb_private22ClangExpressionDeclMap16GetSymbolAddressERNS_6TargetEPNS_7ProcessENS_11ConstStringEN4lldb10SymbolTypeEPNS_6ModuleE'/>
<size>696</size>
<use f='llvm/lldb/source/Plugins/ExpressionParser/Clang/ClangUserExpression.cpp' l='500' c='_Z15GetModuleConfigN4lldb12LanguageTypeERN12lldb_private16ExecutionContextE'/>
<size>696</size>
<use f='llvm/lldb/source/Plugins/Platform/MacOSX/PlatformDarwin.h' l='43' c='_ZN14PlatformDarwin34LocateExecutableScriptingResourcesEPN12lldb_private6TargetERNS0_6ModuleEPNS0_6StreamE'/>
<use f='llvm/lldb/source/Plugins/Platform/MacOSX/PlatformDarwin.cpp' l='71' c='_ZN14PlatformDarwin34LocateExecutableScriptingResourcesEPN12lldb_private6TargetERNS0_6ModuleEPNS0_6StreamE'/>
<use f='llvm/lldb/source/Plugins/Platform/MacOSX/PlatformDarwin.cpp' l='293' c='_ZN14PlatformDarwin29GetSharedModuleWithLocalCacheERKN12lldb_private10ModuleSpecERSt10shared_ptrINS0_6ModuleEEPKNS0_12FileSpecListEPN4llvm15SmallVectorImplIS6_EEPb'/>
<use f='llvm/lldb/source/Plugins/Platform/MacOSX/PlatformDarwin.cpp' l='330' c='_ZN14PlatformDarwin29GetSharedModuleWithLocalCacheERKN12lldb_private10ModuleSpecERSt10shared_ptrINS0_6ModuleEEPKNS0_12FileSpecListEPN4llvm15SmallVectorImplIS6_EEPb'/>
<use f='llvm/lldb/source/Plugins/Platform/MacOSX/PlatformDarwin.cpp' l='355' c='_ZN14PlatformDarwin29GetSharedModuleWithLocalCacheERKN12lldb_private10ModuleSpecERSt10shared_ptrINS0_6ModuleEEPKNS0_12FileSpecListEPN4llvm15SmallVectorImplIS6_EEPb'/>
<size>696</size>
<use f='llvm/lldb/source/Plugins/Process/gdb-remote/ProcessGDBRemote.h' l='78' c='_ZN12lldb_private18process_gdb_remote16ProcessGDBRemote10WillLaunchEPNS_6ModuleE'/>
<use f='llvm/lldb/source/Plugins/Process/gdb-remote/ProcessGDBRemote.h' l='80' c='_ZN12lldb_private18process_gdb_remote16ProcessGDBRemote8DoLaunchEPNS_6ModuleERNS_17ProcessLaunchInfoE'/>
<use f='llvm/lldb/source/Plugins/Process/gdb-remote/ProcessGDBRemote.cpp' l='222' c='_ZN12lldb_private18process_gdb_remote16ProcessGDBRemote8CanDebugESt10shared_ptrINS_6TargetEEb'/>
<use f='llvm/lldb/source/Plugins/Process/gdb-remote/ProcessGDBRemote.cpp' l='620' c='_ZN12lldb_private18process_gdb_remote16ProcessGDBRemote10WillLaunchEPNS_6ModuleE'/>
<use f='llvm/lldb/source/Plugins/Process/gdb-remote/ProcessGDBRemote.cpp' l='736' c='_ZN12lldb_private18process_gdb_remote16ProcessGDBRemote8DoLaunchEPNS_6ModuleERNS_17ProcessLaunchInfoE'/>
<size>696</size>
<use f='llvm/lldb/source/Plugins/Process/mach-core/ProcessMachCore.cpp' l='391' c='_ZN15ProcessMachCore10DoLoadCoreEv'/>
<size>696</size>
<use f='llvm/lldb/source/Plugins/SymbolFile/Breakpad/SymbolFileBreakpad.cpp' l='320' c='_ZN12lldb_private8breakpad18SymbolFileBreakpad10AddSymbolsERNS_6SymtabE'/>
<size>696</size>
<use f='llvm/lldb/source/Plugins/SymbolFile/DWARF/AppleDWARFIndex.h' l='19' c='_ZN12lldb_private15AppleDWARFIndex6CreateERNS_6ModuleENS_18DWARFDataExtractorES3_S3_S3_S3_'/>
<use f='llvm/lldb/source/Plugins/SymbolFile/DWARF/AppleDWARFIndex.h' l='24' c='_ZN12lldb_private15AppleDWARFIndexC1ERNS_6ModuleESt10unique_ptrIN15DWARFMappedHash11MemoryTableESt14default_deleteIS5_EES8_S8_S8_'/>
<use f='llvm/lldb/source/Plugins/SymbolFile/DWARF/AppleDWARFIndex.cpp' l='21' c='_ZN12lldb_private15AppleDWARFIndex6CreateERNS_6ModuleENS_18DWARFDataExtractorES3_S3_S3_S3_'/>
<size>696</size>
<use f='llvm/lldb/source/Plugins/SymbolFile/DWARF/SymbolFileDWARFDebugMap.h' l='68' c='_ZN23SymbolFileDWARFDebugMap21ForEachExternalModuleERN12lldb_private11CompileUnitERN4llvm8DenseSetIPNS0_10SymbolFileENS3_12DenseMapInfoIS6_EEEENS3_12f11796812'/>
<use f='llvm/lldb/source/Plugins/SymbolFile/DWARF/SymbolFileDWARFDebugMap.h' l='207' c='_ZN23SymbolFileDWARFDebugMap25GetCompUnitInfosForModuleEPKN12lldb_private6ModuleERSt6vectorIPNS_15CompileUnitInfoESaIS6_EE'/>
<use f='llvm/lldb/source/Plugins/SymbolFile/DWARF/SymbolFileDWARFDebugMap.h' l='210' c='_ZN23SymbolFileDWARFDebugMap23GetModuleByCompUnitInfoEPNS_15CompileUnitInfoE'/>
<use f='llvm/lldb/source/Plugins/SymbolFile/DWARF/SymbolFileDWARFDebugMap.h' l='213' c='_ZN23SymbolFileDWARFDebugMap19GetModuleByOSOIndexEj'/>
<use f='llvm/lldb/source/Plugins/SymbolFile/DWARF/DWARFASTParserClang.cpp' l='175' c='_ZN19DWARFASTParserClang24ParseTypeFromClangModuleERKN12lldb_private13SymbolContextERK8DWARFDIEPNS0_3LogE'/>
<size>696</size>
<use f='llvm/lldb/source/Plugins/SymbolFile/DWARF/ManualDWARFIndex.h' l='22' c='_ZN12lldb_private16ManualDWARFIndexC1ERNS_6ModuleER15SymbolFileDWARFN4llvm8DenseSetIjNS5_12DenseMapInfoIjEEEE'/>
<use f='llvm/lldb/source/Plugins/SymbolFile/DWARF/DebugNamesDWARFIndex.h' l='23' c='_ZN12lldb_private20DebugNamesDWARFIndex6CreateERNS_6ModuleENS_18DWARFDataExtractorES3_R15SymbolFileDWARF'/>
<use f='llvm/lldb/source/Plugins/SymbolFile/DWARF/DebugNamesDWARFIndex.h' l='59' c='_ZN12lldb_private20DebugNamesDWARFIndexC1ERNS_6ModuleESt10unique_ptrIN4llvm15DWARFDebugNamesESt14default_deleteIS5_EENS_18DWARFDataExtractorES9_R15SymbolFileDWARF'/>
<use f='llvm/lldb/source/Plugins/SymbolFile/DWARF/DebugNamesDWARFIndex.cpp' l='21' c='_ZN12lldb_private20DebugNamesDWARFIndex6CreateERNS_6ModuleENS_18DWARFDataExtractorES3_R15SymbolFileDWARF'/>
<size>696</size>
<use f='llvm/lldb/source/Plugins/SymbolFile/DWARF/SymbolFileDWARF.cpp' l='856' c='_ZN15SymbolFileDWARF21ForEachExternalModuleERN12lldb_private11CompileUnitERN4llvm8DenseSetIPNS0_10SymbolFileENS3_12DenseMapInfoIS6_EEEENS3_12function_5131787'/>
<size>696</size>
<use f='llvm/lldb/source/Plugins/SymbolFile/DWARF/SymbolFileDWARFDebugMap.cpp' l='56' c='_ZN23SymbolFileDWARFDebugMap15CompileUnitInfo15GetFileRangeMapEPS_'/>
<ovr f='llvm/lldb/source/Plugins/SymbolFile/DWARF/SymbolFileDWARFDebugMap.cpp' l='165' c='DebugMapModule'/>
<use f='llvm/lldb/source/Plugins/SymbolFile/DWARF/SymbolFileDWARFDebugMap.cpp' l='165'/>
<use f='llvm/lldb/source/Plugins/SymbolFile/DWARF/SymbolFileDWARFDebugMap.cpp' l='171' c='_ZN14DebugMapModuleC1ERKSt10shared_ptrIN12lldb_private6ModuleEEjRKNS1_8FileSpecERKNS1_8ArchSpecEPKNS1_11ConstStringElNSt6chrono10time_pointINSF_3_V2123325806'/>
<use f='llvm/lldb/source/Plugins/SymbolFile/DWARF/SymbolFileDWARFDebugMap.cpp' l='394' c='_ZN23SymbolFileDWARFDebugMap19GetModuleByOSOIndexEj'/>
<use f='llvm/lldb/source/Plugins/SymbolFile/DWARF/SymbolFileDWARFDebugMap.cpp' l='401' c='_ZN23SymbolFileDWARFDebugMap23GetModuleByCompUnitInfoEPNS_15CompileUnitInfoE'/>
<use f='llvm/lldb/source/Plugins/SymbolFile/DWARF/SymbolFileDWARFDebugMap.cpp' l='482' c='_ZN23SymbolFileDWARFDebugMap23GetObjectFileByOSOIndexEj'/>
<use f='llvm/lldb/source/Plugins/SymbolFile/DWARF/SymbolFileDWARFDebugMap.cpp' l='503' c='_ZN23SymbolFileDWARFDebugMap27GetObjectFileByCompUnitInfoEPNS_15CompileUnitInfoE'/>
<use f='llvm/lldb/source/Plugins/SymbolFile/DWARF/SymbolFileDWARFDebugMap.cpp' l='539' c='_ZN23SymbolFileDWARFDebugMap27GetSymbolFileByCompUnitInfoEPNS_15CompileUnitInfoE'/>
<use f='llvm/lldb/source/Plugins/SymbolFile/DWARF/SymbolFileDWARFDebugMap.cpp' l='573' c='_ZN23SymbolFileDWARFDebugMap23ParseCompileUnitAtIndexEj'/>
<use f='llvm/lldb/source/Plugins/SymbolFile/DWARF/SymbolFileDWARFDebugMap.cpp' l='613' c='_ZN23SymbolFileDWARFDebugMap25GetCompUnitInfosForModuleEPKN12lldb_private6ModuleERSt6vectorIPNS_15CompileUnitInfoESaIS6_EE'/>
<use f='llvm/lldb/source/Plugins/SymbolFile/DWARF/SymbolFileDWARFDebugMap.cpp' l='667' c='_ZN23SymbolFileDWARFDebugMap21ForEachExternalModuleERN12lldb_private11CompileUnitERN4llvm8DenseSetIPNS0_10SymbolFileENS3_12DenseMapInfoIS6_EEEENS3_12f11796812'/>
<use f='llvm/lldb/source/Plugins/SymbolFile/DWARF/SymbolFileDWARFDebugMap.cpp' l='789' c='_ZN23SymbolFileDWARFDebugMap20ResolveSymbolContextERKN12lldb_private7AddressEN4lldb17SymbolContextItemERNS0_13SymbolContextE'/>
<use f='llvm/lldb/source/Plugins/SymbolFile/DWARF/SymbolFileDWARFDebugMap.cpp' l='1388' c='_ZN23SymbolFileDWARFDebugMap14LinkOSOAddressERN12lldb_private7AddressE'/>
<use f='llvm/lldb/source/Plugins/SymbolFile/DWARF/SymbolFileDWARFDebugMap.cpp' l='1389' c='_ZN23SymbolFileDWARFDebugMap14LinkOSOAddressERN12lldb_private7AddressE'/>
<size>696</size>
<use f='llvm/lldb/source/Plugins/SystemRuntime/MacOSX/SystemRuntimeMacOSX.cpp' l='46' c='_ZN19SystemRuntimeMacOSX14CreateInstanceEPN12lldb_private7ProcessE'/>
<size>696</size>
<use f='llvm/lldb/source/Plugins/TypeSystem/Clang/TypeSystemClang.cpp' l='583' c='_ZN12lldb_private15TypeSystemClang14CreateInstanceEN4lldb12LanguageTypeEPNS_6ModuleEPNS_6TargetE'/>
<size>696</size>
<use f='llvm/lldb/source/Symbol/CompileUnit.cpp' l='353' c='_ZN12lldb_private11CompileUnit21ForEachExternalModuleERN4llvm8DenseSetIPNS_10SymbolFileENS1_12DenseMapInfoIS4_EEEENS1_12function_refIFbRNS_6ModuleEEEE'/>
<size>696</size>
<use f='llvm/lldb/source/Symbol/SymbolContext.cpp' l='774' c='_ZN12lldb_private13SymbolContext24FindBestGlobalDataSymbolENS_11ConstStringERNS_6StatusE'/>
<size>696</size>
<use f='llvm/lldb/source/Symbol/TypeSystem.cpp' l='41' c='_ZL20CreateInstanceHelperN4lldb12LanguageTypeEPN12lldb_private6ModuleEPNS1_6TargetE'/>
<use f='llvm/lldb/source/Symbol/TypeSystem.cpp' l='56' c='_ZN12lldb_private10TypeSystem14CreateInstanceEN4lldb12LanguageTypeEPNS_6ModuleE'/>
<use f='llvm/lldb/source/Symbol/TypeSystem.cpp' l='295' c='_ZN12lldb_private13TypeSystemMap24GetTypeSystemForLanguageEN4lldb12LanguageTypeEPNS_6ModuleEb'/>
<use f='llvm/lldb/source/Symbol/UnwindTable.cpp' l='31' c='_ZN12lldb_private11UnwindTableC1ERNS_6ModuleE'/>
<size>696</size>
<use f='llvm/lldb/source/Target/ModuleCache.cpp' l='87' c='_ZN12_GLOBAL__N_120DeleteExistingModuleERKN12lldb_private8FileSpecES3_'/>
<size>696</size>
<use f='llvm/lldb/source/Target/Platform.cpp' l='182' c='_ZN12lldb_private8Platform34LocateExecutableScriptingResourcesEPNS_6TargetERNS_6ModuleEPNS_6StreamE'/>
<size>696</size>
<use f='llvm/lldb/source/Target/Process.cpp' l='2344' c='_ZN12lldb_private7Process20ReadModuleFromMemoryERKNS_8FileSpecEmm'/>
<use f='llvm/lldb/source/Target/Process.cpp' l='2431' c='_ZN12lldb_private7Process6LaunchERNS_17ProcessLaunchInfoE'/>
<size>696</size>
<use f='llvm/lldb/source/Target/Target.cpp' l='164' c='_ZN12lldb_private6Target4DumpEPNS_6StreamEN4lldb16DescriptionLevelE'/>
<use f='llvm/lldb/source/Target/Target.cpp' l='1362' c='_ZN12lldb_private6Target26GetExecutableModulePointerEv'/>
<use f='llvm/lldb/source/Target/Target.cpp' l='2111' c='_ZN12lldb_private6Target17GetOrCreateModuleERKNS_10ModuleSpecEbPNS_6StatusE'/>
<use f='llvm/lldb/source/Target/Target.cpp' l='2142' c='_ZN12lldb_private6Target17GetOrCreateModuleERKNS_10ModuleSpecEbPNS_6StatusE'/>
<use f='llvm/lldb/source/Target/Target.cpp' l='2463' c='_ZN12lldb_private6Target20GetEntryPointAddressEv'/>
<size>696</size>
<use f='llvm/lldb/source/Target/TargetList.cpp' l='420' c='_ZNK12lldb_private10TargetList39FindTargetWithExecutableAndArchitectureERKNS_8FileSpecEPKNS_8ArchSpecE'/>
<size>696</size>
<use f='llvm/lldb/tools/lldb-test/lldb-test.cpp' l='191' c='_ZN4opts7symbolsL13findFunctionsERN12lldb_private6ModuleE'/>
<use f='llvm/lldb/tools/lldb-test/lldb-test.cpp' l='192' c='_ZN4opts7symbolsL10findBlocksERN12lldb_private6ModuleE'/>
<use f='llvm/lldb/tools/lldb-test/lldb-test.cpp' l='193' c='_ZN4opts7symbolsL14findNamespacesERN12lldb_private6ModuleE'/>
<use f='llvm/lldb/tools/lldb-test/lldb-test.cpp' l='194' c='_ZN4opts7symbolsL9findTypesERN12lldb_private6ModuleE'/>
<use f='llvm/lldb/tools/lldb-test/lldb-test.cpp' l='195' c='_ZN4opts7symbolsL13findVariablesERN12lldb_private6ModuleE'/>
<use f='llvm/lldb/tools/lldb-test/lldb-test.cpp' l='196' c='_ZN4opts7symbolsL10dumpModuleERN12lldb_private6ModuleE'/>
<use f='llvm/lldb/tools/lldb-test/lldb-test.cpp' l='197' c='_ZN4opts7symbolsL7dumpASTERN12lldb_private6ModuleE'/>
<use f='llvm/lldb/tools/lldb-test/lldb-test.cpp' l='198' c='_ZN4opts7symbolsL18dumpEntireClangASTERN12lldb_private6ModuleE'/>
<use f='llvm/lldb/tools/lldb-test/lldb-test.cpp' l='199' c='_ZN4opts7symbolsL6verifyERN12lldb_private6ModuleE'/>
<use f='llvm/lldb/tools/lldb-test/lldb-test.cpp' l='201' c='_ZN4opts7symbolsL9getActionEv'/>
<use f='llvm/lldb/tools/lldb-test/lldb-test.cpp' l='414' c='_ZN4opts7symbolsL13findFunctionsERN12lldb_private6ModuleE'/>
<use f='llvm/lldb/tools/lldb-test/lldb-test.cpp' l='467' c='_ZN4opts7symbolsL10findBlocksERN12lldb_private6ModuleE'/>
<use f='llvm/lldb/tools/lldb-test/lldb-test.cpp' l='504' c='_ZN4opts7symbolsL14findNamespacesERN12lldb_private6ModuleE'/>
<use f='llvm/lldb/tools/lldb-test/lldb-test.cpp' l='522' c='_ZN4opts7symbolsL9findTypesERN12lldb_private6ModuleE'/>
<use f='llvm/lldb/tools/lldb-test/lldb-test.cpp' l='554' c='_ZN4opts7symbolsL13findVariablesERN12lldb_private6ModuleE'/>
<use f='llvm/lldb/tools/lldb-test/lldb-test.cpp' l='594' c='_ZN4opts7symbolsL10dumpModuleERN12lldb_private6ModuleE'/>
<use f='llvm/lldb/tools/lldb-test/lldb-test.cpp' l='602' c='_ZN4opts7symbolsL7dumpASTERN12lldb_private6ModuleE'/>
<use f='llvm/lldb/tools/lldb-test/lldb-test.cpp' l='630' c='_ZN4opts7symbolsL18dumpEntireClangASTERN12lldb_private6ModuleE'/>
<use f='llvm/lldb/tools/lldb-test/lldb-test.cpp' l='654' c='_ZN4opts7symbolsL6verifyERN12lldb_private6ModuleE'/>
<use f='llvm/lldb/tools/lldb-test/lldb-test.cpp' l='705' c='_ZN4opts7symbolsL9getActionEv'/>
<use f='llvm/lldb/tools/lldb-test/lldb-test.cpp' l='825' c='_ZN4opts7symbolsL11dumpSymbolsERN12lldb_private8DebuggerE'/>
<use f='llvm/lldb/tools/lldb-test/lldb-test.cpp' l='882' c='_ZL15dumpObjectFilesRN12lldb_private8DebuggerE'/>
<size>696</size>
<use f='llvm/lldb/unittests/Core/MangledTest.cpp' l='168' c='_ZN48MangledTest_NameIndexes_FindFunctionSymbols_Test8TestBodyEv'/>
<size>696</size>
<use f='llvm/lldb/unittests/Core/ModuleSpecTest.cpp' l='39' c='_ZN41ModuleSpecTest_InvalidInMemoryBuffer_Test8TestBodyEv'/>
<use f='llvm/lldb/unittests/Core/ModuleSpecTest.cpp' l='49' c='_ZN50ModuleSpecTest_InvalidInMemoryBufferValidFile_Test8TestBodyEv'/>
<use f='llvm/lldb/unittests/Core/ModuleSpecTest.cpp' l='72' c='_ZN31ModuleSpecTest_TestELFFile_Test8TestBodyEv'/>
<use f='llvm/lldb/unittests/Core/ModuleSpecTest.cpp' l='113' c='_ZN32ModuleSpecTest_TestCOFFFile_Test8TestBodyEv'/>
<use f='llvm/lldb/unittests/Core/ModuleSpecTest.cpp' l='162' c='_ZN33ModuleSpecTest_TestMachOFile_Test8TestBodyEv'/>
<size>696</size>
<use f='llvm/lldb/unittests/ObjectFile/ELF/TestObjectFileELF.cpp' l='94' c='_ZN50ObjectFileELFTest_SectionsResolveConsistently_Test8TestBodyEv'/>
<use f='llvm/lldb/unittests/ObjectFile/ELF/TestObjectFileELF.cpp' l='212' c='_ZN68ObjectFileELFTest_GetSymtab_NoSymEntryPointArmThumbAddressClass_Test8TestBodyEv'/>
<use f='llvm/lldb/unittests/ObjectFile/ELF/TestObjectFileELF.cpp' l='274' c='_ZN63ObjectFileELFTest_GetSymtab_NoSymEntryPointArmAddressClass_Test8TestBodyEv'/>
<size>696</size>
<use f='llvm/lldb/unittests/ObjectFile/PECOFF/TestPECallFrameInfo.cpp' l='195' c='_ZNK19PECallFrameInfoTest13GetUnwindPlanEmRN12lldb_private10UnwindPlanE'/>
<size>696</size>
<use f='llvm/lldb/unittests/Symbol/TestDWARFCallFrameInfo.cpp' l='223' c='_ZN22DWARFCallFrameInfoTest9TestBasicEN12lldb_private18DWARFCallFrameInfo4TypeEN4llvm9StringRefE'/>
<size>696</size>
<use f='llvm/lldb/unittests/Symbol/TestLineEntry.cpp' l='52' c='_ZN13LineEntryTest5SetUpEv'/>
<size>696</size>
<use f='llvm/lldb/unittests/SymbolFile/DWARF/SymbolFileDWARFTests.cpp' l='61' c='_ZN47SymbolFileDWARFTests_TestAbilitiesForDWARF_Test8TestBodyEv'/>
<size>696</size>
<use f='llvm/lldb/unittests/Target/RemoteAwarePlatformTest.cpp' l='76' c='_ZN68RemoteAwarePlatformTest_TestResolveExecutabelOnClientByPlatform_Test8TestBodyEv'/>
<size>696</size>
<use f='llvm/lldb/unittests/TestingSupport/Symbol/YAMLModuleTester.cpp' l='22' c='_ZN12lldb_private16YAMLModuleTesterC1EN4llvm9StringRefE'/>
<size>696</size>
