<dec f='llvm/lldb/source/Plugins/LanguageRuntime/RenderScript/RenderScriptRuntime/RenderScriptRuntime.cpp' l='506' type='empirical_type&lt;lldb::addr_t&gt;'/>
<use f='llvm/lldb/source/Plugins/LanguageRuntime/RenderScript/RenderScriptRuntime/RenderScriptRuntime.cpp' l='1654' u='m' c='_ZN12lldb_private19RenderScriptRuntime18FixupScriptDetailsESt10shared_ptrINS_17lldb_renderscript18RSModuleDescriptorEE'/>
<use f='llvm/lldb/source/Plugins/LanguageRuntime/RenderScript/RenderScriptRuntime/RenderScriptRuntime.cpp' l='3830' u='m' c='_ZN12lldb_private19RenderScriptRuntime12LookUpScriptEmb'/>
<use f='llvm/lldb/source/Plugins/LanguageRuntime/RenderScript/RenderScriptRuntime/RenderScriptRuntime.cpp' l='3831' u='m' c='_ZN12lldb_private19RenderScriptRuntime12LookUpScriptEmb'/>
<use f='llvm/lldb/source/Plugins/LanguageRuntime/RenderScript/RenderScriptRuntime/RenderScriptRuntime.cpp' l='3836' u='w' c='_ZN12lldb_private19RenderScriptRuntime12LookUpScriptEmb'/>
<offset>1152</offset>
<doc f='llvm/lldb/source/Plugins/LanguageRuntime/RenderScript/RenderScriptRuntime/RenderScriptRuntime.cpp' l='505'>// Pointer to the script object itself.</doc>
