<dec f='llvm/lldb/include/lldb/Symbol/DWARFCallFrameInfo.h' l='35' type='0'/>
<use f='llvm/lldb/include/lldb/Symbol/DWARFCallFrameInfo.h' l='163' u='r' c='_ZNK12lldb_private18DWARFCallFrameInfo15GetRegisterKindEv'/>
<use f='llvm/lldb/source/Plugins/ObjectFile/Mach-O/ObjectFileMachO.cpp' l='2482' u='r' c='_ZN15ObjectFileMachO11ParseSymtabEv'/>
<use f='llvm/lldb/source/Symbol/DWARFCallFrameInfo.cpp' l='261' u='r' c='_ZN12lldb_private18DWARFCallFrameInfo8ParseCIEEj'/>
<use f='llvm/lldb/source/Symbol/DWARFCallFrameInfo.cpp' l='467' u='r' c='_ZN12lldb_private18DWARFCallFrameInfo11GetFDEIndexEv'/>
<use f='llvm/lldb/source/Symbol/DWARFCallFrameInfo.cpp' l='553' u='r' c='_ZN12lldb_private18DWARFCallFrameInfo15FDEToUnwindPlanEjNS_7AddressERNS_10UnwindPlanE'/>
<use f='llvm/lldb/source/Symbol/UnwindTable.cpp' l='61' u='a' c='_ZN12lldb_private11UnwindTable10InitializeEv'/>
<use f='llvm/lldb/unittests/Symbol/TestDWARFCallFrameInfo.cpp' l='227' u='r' c='_ZN22DWARFCallFrameInfoTest9TestBasicEN12lldb_private18DWARFCallFrameInfo4TypeEN4llvm9StringRefE'/>
<use f='llvm/lldb/unittests/Symbol/TestDWARFCallFrameInfo.cpp' l='256' u='r' c='_ZN36DWARFCallFrameInfoTest_Basic_eh_Test8TestBodyEv'/>
