<def f='llvm/lldb/include/lldb/Host/FileAction.h' l='19' ll='24'/>
<use f='llvm/lldb/include/lldb/Host/FileAction.h' l='38' c='_ZNK12lldb_private10FileAction9GetActionEv'/>
<use f='llvm/lldb/include/lldb/Host/FileAction.h' l='49'/>
