<dec f='llvm/lldb/tools/lldb-test/FormatUtil.h' l='23' type='llvm::raw_ostream &amp;'/>
<use f='llvm/lldb/tools/lldb-test/FormatUtil.h' l='32' u='m' c='_ZN12lldb_private11LinePrinter4LineC1ERS0_'/>
<use f='llvm/lldb/tools/lldb-test/FormatUtil.h' l='38' u='a' c='_ZN12lldb_private11LinePrinter4LinecvRN4llvm11raw_ostreamEEv'/>
<use f='llvm/lldb/tools/lldb-test/FormatUtil.cpp' l='22' u='w' c='_ZN12lldb_private11LinePrinterC1EiRN4llvm11raw_ostreamE'/>
<use f='llvm/lldb/tools/lldb-test/FormatUtil.cpp' l='37' u='m' c='_ZN12lldb_private11LinePrinter7NewLineEv'/>
<use f='llvm/lldb/tools/lldb-test/FormatUtil.cpp' l='47' u='m' c='_ZN12lldb_private11LinePrinter12formatBinaryEN4llvm9StringRefENS1_8ArrayRefIhEEj'/>
<use f='llvm/lldb/tools/lldb-test/FormatUtil.cpp' l='61' u='m' c='_ZN12lldb_private11LinePrinter12formatBinaryEN4llvm9StringRefENS1_8ArrayRefIhEEmj'/>
<offset>0</offset>
