<dec f='llvm/lldb/source/Plugins/Process/elf-core/RegisterUtilities.h' l='78' type='llvm::Triple::OSType'/>
<offset>0</offset>
<doc f='llvm/lldb/source/Plugins/Process/elf-core/RegisterUtilities.h' l='77'>// OS to which this entry applies to. Must not be UnknownOS.</doc>
<use f='llvm/lldb/source/Plugins/Process/elf-core/RegisterUtilities.cpp' l='18' u='r' c='_ZL11getNoteTypeRKN4llvm6TripleENS_8ArrayRefIN12lldb_private10RegsetDescEEE'/>
