<dec f='llvm/lldb/include/lldb/DataFormatters/TypeSummary.h' l='47' type='1'/>
<use f='llvm/lldb/include/lldb/DataFormatters/TypeSummary.h' l='388' u='r' c='_ZN12lldb_private19ScriptSummaryFormat7classofEPKNS_15TypeSummaryImplE'/>
<use f='llvm/lldb/source/API/SBTypeSummary.cpp' l='383' c='_ZN4lldb13SBTypeSummary9IsEqualToERS0_'/>
<use f='llvm/lldb/source/API/SBTypeSummary.cpp' l='455' u='r' c='_ZN4lldb13SBTypeSummary17ChangeSummaryTypeEb'/>
<use f='llvm/lldb/source/DataFormatters/TypeSummary.cpp' l='149' u='r' c='_ZN12lldb_private19ScriptSummaryFormatC1ERKNS_15TypeSummaryImpl5FlagsEPKcS6_'/>
