<dec f='llvm/lldb/include/lldb/DataFormatters/StringPrinter.h' l='27' type='1'/>
<use f='llvm/lldb/source/DataFormatters/StringPrinter.cpp' l='99' u='r' c='_Z18attemptASCIIEscapejN12lldb_private10formatters13StringPrinter11EscapeStyleE'/>
<use f='llvm/lldb/source/DataFormatters/StringPrinter.cpp' l='159' c='_ZL16GetPrintableImplPhS_RS_N12lldb_private10formatters13StringPrinter11EscapeStyleE'/>
<use f='llvm/lldb/source/DataFormatters/StringPrinter.cpp' l='206' c='_ZL16GetPrintableImplPhS_RS_N12lldb_private10formatters13StringPrinter11EscapeStyleE'/>
<use f='llvm/lldb/unittests/DataFormatter/StringPrinterTests.cpp' l='122' u='r' c='_ZN33StringPrinterTests_SwiftUTF8_Test8TestBodyEv'/>
