<use f='llvm/lldb/tools/lldb-test/FormatUtil.h' l='63' u='w' c='_ZN12lldb_private10AutoIndentC1ERNS_11LinePrinterEj'/>
<use f='llvm/lldb/tools/lldb-test/FormatUtil.h' l='67' u='r' c='_ZN12lldb_private10AutoIndentD1Ev'/>
<use f='llvm/lldb/tools/lldb-test/FormatUtil.h' l='68' u='r' c='_ZN12lldb_private10AutoIndentD1Ev'/>
<dec f='llvm/lldb/tools/lldb-test/FormatUtil.h' l='71' type='lldb_private::LinePrinter *'/>
<offset>0</offset>
