<dec f='llvm/lldb/include/lldb/Target/StackFrameRecognizer.h' l='130' type='lldb_private::ConstString'/>
<offset>256</offset>
<use f='llvm/lldb/source/Target/StackFrameRecognizer.cpp' l='84' u='m' c='_ZN12lldb_private27StackFrameRecognizerManager7ForEachERKSt8functionIFvjNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES7_N4llvm8ArrayRefINS_11ConstStringEEEbEE'/>
<use f='llvm/lldb/source/Target/StackFrameRecognizer.cpp' l='123' u='m' c='_ZN12lldb_private27StackFrameRecognizerManager21GetRecognizerForFrameESt10shared_ptrINS_10StackFrameEE'/>
<use f='llvm/lldb/source/Target/StackFrameRecognizer.cpp' l='124' u='m' c='_ZN12lldb_private27StackFrameRecognizerManager21GetRecognizerForFrameESt10shared_ptrINS_10StackFrameEE'/>
