<dec f='llvm/lldb/include/lldb/lldb-private-enumerations.h' l='192' type='2'/>
<use f='llvm/lldb/include/lldb/lldb-private-enumerations.h' l='204' u='r'/>
<use f='llvm/lldb/source/Plugins/SymbolFile/DWARF/DWARFDIE.cpp' l='385' u='r' c='_ZNK8DWARFDIE14GetDeclContextERN4llvm15SmallVectorImplIN12lldb_private15CompilerContextEEE'/>
<use f='llvm/lldb/source/Symbol/Type.cpp' l='49' u='r' c='_ZN12lldb_private14contextMatchesEN4llvm8ArrayRefINS_15CompilerContextEEES3_'/>
<use f='llvm/lldb/source/Symbol/Type.cpp' l='73' c='_ZNK12lldb_private15CompilerContext4DumpEv'/>
<use f='llvm/lldb/tools/lldb-test/lldb-test.cpp' l='255' u='r' c='_Z20parseCompilerContextv'/>
<use f='llvm/lldb/unittests/Symbol/TestType.cpp' l='54' u='r' c='_ZN32Type_CompilerContextPattern_Test8TestBodyEv'/>
<use f='llvm/lldb/unittests/Symbol/TestType.cpp' l='55' u='r' c='_ZN32Type_CompilerContextPattern_Test8TestBodyEv'/>
<use f='llvm/lldb/unittests/Symbol/TestType.cpp' l='59' u='r' c='_ZN32Type_CompilerContextPattern_Test8TestBodyEv'/>
<use f='llvm/lldb/unittests/Symbol/TestType.cpp' l='60' u='r' c='_ZN32Type_CompilerContextPattern_Test8TestBodyEv'/>
<use f='llvm/lldb/unittests/Symbol/TestType.cpp' l='64' u='r' c='_ZN32Type_CompilerContextPattern_Test8TestBodyEv'/>
<use f='llvm/lldb/unittests/Symbol/TestType.cpp' l='67' u='r' c='_ZN32Type_CompilerContextPattern_Test8TestBodyEv'/>
<use f='llvm/lldb/unittests/Symbol/TestType.cpp' l='74' u='r' c='_ZN32Type_CompilerContextPattern_Test8TestBodyEv'/>
<use f='llvm/lldb/unittests/Symbol/TestType.cpp' l='75' u='r' c='_ZN32Type_CompilerContextPattern_Test8TestBodyEv'/>
<use f='llvm/lldb/unittests/Symbol/TestType.cpp' l='76' u='r' c='_ZN32Type_CompilerContextPattern_Test8TestBodyEv'/>
<use f='llvm/lldb/unittests/Symbol/TestType.cpp' l='80' u='r' c='_ZN32Type_CompilerContextPattern_Test8TestBodyEv'/>
<use f='llvm/lldb/unittests/Symbol/TestType.cpp' l='81' u='r' c='_ZN32Type_CompilerContextPattern_Test8TestBodyEv'/>
<use f='llvm/lldb/unittests/Symbol/TestType.cpp' l='84' u='r' c='_ZN32Type_CompilerContextPattern_Test8TestBodyEv'/>
<use f='llvm/lldb/unittests/Symbol/TestType.cpp' l='85' u='r' c='_ZN32Type_CompilerContextPattern_Test8TestBodyEv'/>
<use f='llvm/lldb/unittests/Symbol/TestType.cpp' l='90' u='r' c='_ZN32Type_CompilerContextPattern_Test8TestBodyEv'/>
<use f='llvm/lldb/unittests/Symbol/TestType.cpp' l='91' u='r' c='_ZN32Type_CompilerContextPattern_Test8TestBodyEv'/>
