<dec f='llvm/lldb/include/lldb/DataFormatters/StringPrinter.h' l='27' type='0'/>
<use f='llvm/lldb/include/lldb/DataFormatters/StringPrinter.h' l='99'/>
<use f='llvm/lldb/source/DataFormatters/StringPrinter.cpp' l='155' c='_ZL16GetPrintableImplPhS_RS_N12lldb_private10formatters13StringPrinter11EscapeStyleE'/>
<use f='llvm/lldb/source/DataFormatters/StringPrinter.cpp' l='202' c='_ZL16GetPrintableImplPhS_RS_N12lldb_private10formatters13StringPrinter11EscapeStyleE'/>
<use f='llvm/lldb/unittests/DataFormatter/StringPrinterTests.cpp' l='54' u='r' c='_ZN32StringPrinterTests_CxxASCII_Test8TestBodyEv'/>
<use f='llvm/lldb/unittests/DataFormatter/StringPrinterTests.cpp' l='88' u='r' c='_ZN31StringPrinterTests_CxxUTF8_Test8TestBodyEv'/>
