<dec f='llvm/lldb/source/Plugins/Process/Utility/RegisterContext_x86.h' l='252' type='lldb_private::MMSRegComp'/>
<offset>0</offset>
<use f='llvm/lldb/source/Plugins/Process/Utility/RegisterContext_x86.cpp' l='28' u='m' c='_ZN12lldb_private21AbridgedToFullTagWordEhtN4llvm8ArrayRefINS_6MMSRegEEE'/>
<use f='llvm/lldb/source/Plugins/Process/Utility/RegisterContext_x86.cpp' l='30' u='m' c='_ZN12lldb_private21AbridgedToFullTagWordEhtN4llvm8ArrayRefINS_6MMSRegEEE'/>
<use f='llvm/lldb/unittests/Process/Utility/RegisterContextTest.cpp' l='29' u='m' c='_Z12st_from_compmt'/>
<use f='llvm/lldb/unittests/Process/Utility/RegisterContextTest.cpp' l='30' u='m' c='_Z12st_from_compmt'/>
