<dec f='llvm/llvm/include/llvm/CodeGen/ModuloSchedule.h' l='377' type='llvm::ModuloSchedule &amp;'/>
<use f='llvm/llvm/include/llvm/CodeGen/ModuloSchedule.h' l='381' u='w' c='_ZN4llvm27ModuloScheduleTestAnnotaterC1ERNS_15MachineFunctionERNS_14ModuloScheduleE'/>
<offset>64</offset>
<use f='llvm/llvm/lib/CodeGen/ModuloSchedule.cpp' l='2188' u='m' c='_ZN4llvm27ModuloScheduleTestAnnotater8annotateEv'/>
<use f='llvm/llvm/lib/CodeGen/ModuloSchedule.cpp' l='2191' u='m' c='_ZN4llvm27ModuloScheduleTestAnnotater8annotateEv'/>
<use f='llvm/llvm/lib/CodeGen/ModuloSchedule.cpp' l='2191' u='m' c='_ZN4llvm27ModuloScheduleTestAnnotater8annotateEv'/>
