<dec f='llvm/llvm/include/llvm/Analysis/RegionPass.h' l='87' type='std::deque&lt;Region *&gt;'/>
<offset>3328</offset>
<use f='llvm/llvm/lib/Analysis/RegionPass.cpp' l='60' u='a' c='_ZN4llvm13RGPassManager13runOnFunctionERNS_8FunctionE'/>
<use f='llvm/llvm/lib/Analysis/RegionPass.cpp' l='62' u='m' c='_ZN4llvm13RGPassManager13runOnFunctionERNS_8FunctionE'/>
<use f='llvm/llvm/lib/Analysis/RegionPass.cpp' l='66' c='_ZN4llvm13RGPassManager13runOnFunctionERNS_8FunctionE'/>
<use f='llvm/llvm/lib/Analysis/RegionPass.cpp' l='74' u='m' c='_ZN4llvm13RGPassManager13runOnFunctionERNS_8FunctionE'/>
<use f='llvm/llvm/lib/Analysis/RegionPass.cpp' l='76' u='m' c='_ZN4llvm13RGPassManager13runOnFunctionERNS_8FunctionE'/>
<use f='llvm/llvm/lib/Analysis/RegionPass.cpp' l='142' u='m' c='_ZN4llvm13RGPassManager13runOnFunctionERNS_8FunctionE'/>
