<dec f='llvm/build/lib/Target/SystemZ/SystemZGenInstrInfo.inc' l='1809' type='1794'/>
<use f='llvm/build/lib/Target/SystemZ/SystemZGenAsmMatcher.inc' l='4630'/>
<use f='llvm/build/lib/Target/SystemZ/SystemZGenMCCodeEmitter.inc' l='5436' c='_ZNK12_GLOBAL__N_120SystemZMCCodeEmitter21getBinaryCodeForInstrERKN4llvm6MCInstERNS1_15SmallVectorImplINS1_7MCFixupEEERKNS1_15MCSubtargetInfoE'/>
<use f='llvm/build/lib/Target/SystemZ/SystemZGenDAGISel.inc' l='18422' u='r' c='_ZN12_GLOBAL__N_119SystemZDAGToDAGISel10SelectCodeEPN4llvm6SDNodeE'/>
<use f='llvm/build/lib/Target/SystemZ/SystemZGenDAGISel.inc' l='18422' u='r' c='_ZN12_GLOBAL__N_119SystemZDAGToDAGISel10SelectCodeEPN4llvm6SDNodeE'/>
<use f='llvm/llvm/lib/Target/SystemZ/SystemZInstrInfo.cpp' l='1647' c='_ZNK4llvm16SystemZInstrInfo14getLoadAndTestEj'/>
<use f='llvm/llvm/lib/Target/SystemZ/SystemZInstrInfo.cpp' l='1908' c='_ZNK4llvm16SystemZInstrInfo14getLoadAndTrapEj'/>
