<use f='llvm/llvm/include/llvm/Analysis/IteratedDominanceFrontier.h' l='27' u='w' c='_ZN4llvm19IDFCalculatorDetail16ChildrenGetterTyINS_10BasicBlockEXT_EEC1EPKNS_9GraphDiffIPS2_XT_EEE'/>
<dec f='llvm/llvm/include/llvm/Analysis/IteratedDominanceFrontier.h' l='33' type='const GraphDiff&lt;llvm::BasicBlock *, IsPostDom&gt; *'/>
<use f='llvm/llvm/include/llvm/Analysis/IteratedDominanceFrontier.h' l='71' u='r' c='_ZN4llvm19IDFCalculatorDetail16ChildrenGetterTyINS_10BasicBlockEXT_EE3getERKPS2_'/>
<use f='llvm/llvm/include/llvm/Analysis/IteratedDominanceFrontier.h' l='76' u='c' c='_ZN4llvm19IDFCalculatorDetail16ChildrenGetterTyINS_10BasicBlockEXT_EE3getERKPS2_'/>
