<dec f='llvm/llvm/include/llvm/BinaryFormat/MachO.h' l='1730' type='union (anonymous union at /fast/tmp/llvm-proj-12/llvm/include/llvm/BinaryFormat/MachO.h:1727:3)'/>
<use f='llvm/llvm/include/llvm/BinaryFormat/MachO.h' l='1770' u='m' c='_ZN4llvm5MachO10swapStructERNS0_18x86_thread_state_tE'/>
<offset>64</offset>
<use f='llvm/llvm/tools/llvm-objdump/MachODump.cpp' l='9710' u='m' c='_ZL18PrintThreadCommandN4llvm5MachO14thread_commandEPKcbj'/>
<use f='llvm/llvm/tools/llvm-objdump/MachODump.cpp' l='9788' u='m' c='_ZL18PrintThreadCommandN4llvm5MachO14thread_commandEPKcbj'/>
