<dec f='llvm/llvm/lib/Target/Hexagon/HexagonTargetTransformInfo.h' l='39' type='const llvm::HexagonSubtarget &amp;'/>
<use f='llvm/llvm/lib/Target/Hexagon/HexagonTargetTransformInfo.h' l='42' u='a' c='_ZNK4llvm14HexagonTTIImpl5getSTEv'/>
<use f='llvm/llvm/lib/Target/Hexagon/HexagonTargetTransformInfo.h' l='55' u='w' c='_ZN4llvm14HexagonTTIImplC1EPKNS_20HexagonTargetMachineERKNS_8FunctionE'/>
<use f='llvm/llvm/lib/Target/Hexagon/HexagonTargetTransformInfo.h' l='55' u='m' c='_ZN4llvm14HexagonTTIImplC1EPKNS_20HexagonTargetMachineERKNS_8FunctionE'/>
<offset>128</offset>
<use f='llvm/llvm/lib/Target/Hexagon/HexagonTargetTransformInfo.cpp' l='47' u='m' c='_ZNK4llvm14HexagonTTIImpl6useHVXEv'/>
<use f='llvm/llvm/lib/Target/Hexagon/HexagonTargetTransformInfo.cpp' l='104' u='m' c='_ZNK4llvm14HexagonTTIImpl28getMinVectorRegisterBitWidthEv'/>
<use f='llvm/llvm/lib/Target/Hexagon/HexagonTargetTransformInfo.cpp' l='108' u='m' c='_ZNK4llvm14HexagonTTIImpl12getMinimumVFEj'/>
<use f='llvm/llvm/lib/Target/Hexagon/HexagonTargetTransformInfo.cpp' l='159' u='m' c='_ZN4llvm14HexagonTTIImpl15getMemoryOpCostEjPNS_4TypeENS_10MaybeAlignEjNS_19TargetTransformInfo14TargetCostKindEPKNS_11InstructionE'/>
<use f='llvm/llvm/lib/Target/Hexagon/HexagonTargetTransformInfo.cpp' l='302' u='m' c='_ZN4llvm14HexagonTTIImpl18isLegalMaskedStoreEPNS_4TypeENS_5AlignE'/>
<use f='llvm/llvm/lib/Target/Hexagon/HexagonTargetTransformInfo.cpp' l='306' u='m' c='_ZN4llvm14HexagonTTIImpl17isLegalMaskedLoadEPNS_4TypeENS_5AlignE'/>
<use f='llvm/llvm/lib/Target/Hexagon/HexagonTargetTransformInfo.cpp' l='312' u='m' c='_ZNK4llvm14HexagonTTIImpl19getPrefetchDistanceEv'/>
<use f='llvm/llvm/lib/Target/Hexagon/HexagonTargetTransformInfo.cpp' l='316' u='m' c='_ZNK4llvm14HexagonTTIImpl16getCacheLineSizeEv'/>
