<use f='llvm/llvm/include/llvm/Analysis/TargetTransformInfo.h' l='875' u='w' c='_ZN4llvm19TargetTransformInfo13ReductionDataC1ENS0_13ReductionKindEjPNS_5ValueES4_'/>
<dec f='llvm/llvm/include/llvm/Analysis/TargetTransformInfo.h' l='879' type='llvm::Value *'/>
<offset>64</offset>
<use f='llvm/llvm/lib/Analysis/TargetTransformInfo.cpp' l='1145' u='r' c='_ZL29matchPairwiseReductionAtLevelPN4llvm11InstructionEjj'/>
<use f='llvm/llvm/lib/Analysis/TargetTransformInfo.cpp' l='1175' u='r' c='_ZL29matchPairwiseReductionAtLevelPN4llvm11InstructionEjj'/>
<use f='llvm/llvm/lib/Analysis/TargetTransformInfo.cpp' l='1178' u='r' c='_ZL29matchPairwiseReductionAtLevelPN4llvm11InstructionEjj'/>
<use f='llvm/llvm/lib/Analysis/TargetTransformInfo.cpp' l='1328' u='r' c='_ZN4llvm19TargetTransformInfo29matchVectorSplittingReductionEPKNS_18ExtractElementInstERjRPNS_10VectorTypeE'/>
