<dec f='llvm/llvm/lib/Target/ARM/ARMISelLowering.h' l='133' type='386'/>
<doc f='llvm/llvm/lib/Target/ARM/ARMISelLowering.h' l='133'>// Low-overhead loops, While Loop Start</doc>
<use f='llvm/llvm/lib/Target/ARM/ARMISelDAGToDAG.cpp' l='3683' c='_ZN12_GLOBAL__N_115ARMDAGToDAGISel6SelectEPN4llvm6SDNodeE'/>
<use f='llvm/llvm/lib/Target/ARM/ARMISelDAGToDAG.cpp' l='3688' u='r' c='_ZN12_GLOBAL__N_115ARMDAGToDAGISel6SelectEPN4llvm6SDNodeE'/>
<use f='llvm/llvm/lib/Target/ARM/ARMISelLowering.cpp' l='1804' c='_ZNK4llvm17ARMTargetLowering17getTargetNodeNameEj'/>
<use f='llvm/llvm/lib/Target/ARM/ARMISelLowering.cpp' l='16032' u='r' c='_ZL20PerformHWLoopCombinePN4llvm6SDNodeERNS_14TargetLowering15DAGCombinerInfoEPKNS_12ARMSubtargetE'/>
<use f='llvm/llvm/lib/Target/ARM/ARMISelLowering.cpp' l='16039' u='r' c='_ZL20PerformHWLoopCombinePN4llvm6SDNodeERNS_14TargetLowering15DAGCombinerInfoEPKNS_12ARMSubtargetE'/>
