<use f='llvm/llvm/include/llvm/Analysis/BranchProbabilityInfo.h' l='302' u='r' c='_ZNK4llvm21BranchProbabilityInfo9LoopBlock11getLoopDataEv'/>
<use f='llvm/llvm/include/llvm/Analysis/BranchProbabilityInfo.h' l='303' u='m' c='_ZNK4llvm21BranchProbabilityInfo9LoopBlock7getLoopEv'/>
<use f='llvm/llvm/include/llvm/Analysis/BranchProbabilityInfo.h' l='304' u='m' c='_ZNK4llvm21BranchProbabilityInfo9LoopBlock9getSccNumEv'/>
<dec f='llvm/llvm/include/llvm/Analysis/BranchProbabilityInfo.h' l='314' type='llvm::BranchProbabilityInfo::LoopData'/>
<offset>64</offset>
<use f='llvm/llvm/lib/Analysis/BranchProbabilityInfo.cpp' l='246' u='m' c='_ZN4llvm21BranchProbabilityInfo9LoopBlockC1EPKNS_10BasicBlockERKNS_8LoopInfoERKNS0_7SccInfoE'/>
<use f='llvm/llvm/lib/Analysis/BranchProbabilityInfo.cpp' l='247' u='m' c='_ZN4llvm21BranchProbabilityInfo9LoopBlockC1EPKNS_10BasicBlockERKNS_8LoopInfoERKNS0_7SccInfoE'/>
<use f='llvm/llvm/lib/Analysis/BranchProbabilityInfo.cpp' l='248' u='m' c='_ZN4llvm21BranchProbabilityInfo9LoopBlockC1EPKNS_10BasicBlockERKNS_8LoopInfoERKNS0_7SccInfoE'/>
