<dec f='llvm/build/lib/Target/X86/X86GenRegisterInfo.inc' l='85' type='65'/>
<use f='llvm/llvm/lib/Target/X86/MCTargetDesc/X86BaseInfo.h' l='392' c='_ZN4llvm3X8630getSegmentOverridePrefixForRegEj'/>
<use f='llvm/build/lib/Target/X86/X86GenAsmMatcher.inc' l='7427' c='_ZL20validateOperandClassRN4llvm18MCParsedAsmOperandEN12_GLOBAL__N_114MatchClassKindE'/>
<use f='llvm/llvm/lib/Target/X86/Disassembler/X86Disassembler.cpp' l='1773' macro='1' u='r' c='_ZL17translateRegisterRN4llvm6MCInstENS_15X86Disassembler3RegE'/>
<use f='llvm/llvm/lib/Target/X86/Disassembler/X86Disassembler.cpp' l='1823'/>
<use f='llvm/llvm/lib/Target/X86/Disassembler/X86Disassembler.cpp' l='2010' macro='1' u='r' c='_ZL19translateRMRegisterRN4llvm6MCInstERNS_15X86Disassembler19InternalInstructionE'/>
<use f='llvm/llvm/lib/Target/X86/MCTargetDesc/X86AsmBackend.cpp' l='482' u='r' c='_ZL21hasInterruptDelaySlotRKN4llvm6MCInstE'/>
<use f='llvm/llvm/lib/Target/X86/X86ISelDAGToDAG.cpp' l='2502' u='r' c='_ZN12_GLOBAL__N_115X86DAGToDAGISel16selectVectorAddrEPN4llvm9MemSDNodeENS1_7SDValueES4_S4_RS4_S5_S5_S5_S5_'/>
<use f='llvm/llvm/lib/Target/X86/X86ISelDAGToDAG.cpp' l='2544' u='r' c='_ZN12_GLOBAL__N_115X86DAGToDAGISel10selectAddrEPN4llvm6SDNodeENS1_7SDValueERS4_S5_S5_S5_S5_'/>
<use f='llvm/llvm/lib/Target/X86/X86RegisterInfo.cpp' l='561' u='r' c='_ZNK4llvm15X86RegisterInfo15getReservedRegsERKNS_15MachineFunctionE'/>
