<use f='llvm/llvm/include/llvm/CodeGen/RegAllocPBQP.h' l='481' u='w' c='_ZN4llvm4PBQP8RegAlloc18RegAllocSolverImpl19SpillCostComparatorC1ERKNS0_5GraphIS2_EE'/>
<use f='llvm/llvm/include/llvm/CodeGen/RegAllocPBQP.h' l='484' u='m' c='_ZN4llvm4PBQP8RegAlloc18RegAllocSolverImpl19SpillCostComparatorclEjj'/>
<use f='llvm/llvm/include/llvm/CodeGen/RegAllocPBQP.h' l='485' u='m' c='_ZN4llvm4PBQP8RegAlloc18RegAllocSolverImpl19SpillCostComparatorclEjj'/>
<use f='llvm/llvm/include/llvm/CodeGen/RegAllocPBQP.h' l='487' u='m' c='_ZN4llvm4PBQP8RegAlloc18RegAllocSolverImpl19SpillCostComparatorclEjj'/>
<use f='llvm/llvm/include/llvm/CodeGen/RegAllocPBQP.h' l='487' u='m' c='_ZN4llvm4PBQP8RegAlloc18RegAllocSolverImpl19SpillCostComparatorclEjj'/>
<dec f='llvm/llvm/include/llvm/CodeGen/RegAllocPBQP.h' l='492' type='const llvm::PBQP::RegAlloc::RegAllocSolverImpl::Graph &amp;'/>
<offset>0</offset>
