<dec f='llvm/llvm/include/llvm/Target/TargetOptions.h' l='109' type='1'/>
<doc f='llvm/llvm/include/llvm/Target/TargetOptions.h' l='109'>// Tune debug info for gdb.</doc>
<use f='llvm/clang/include/clang/Driver/ToolChain.h' l='506' u='r' c='_ZNK5clang6driver9ToolChain24getDefaultDebuggerTuningEv'/>
<use f='llvm/clang/lib/CodeGen/CGDebugInfo.cpp' l='5047' u='r' c='_ZNK5clang7CodeGen11CGDebugInfo23getCallSiteRelatedAttrsEv'/>
<use f='llvm/clang/lib/Driver/ToolChains/Fuchsia.h' l='60' u='r' c='_ZNK5clang6driver10toolchains7Fuchsia24getDefaultDebuggerTuningEv'/>
<use f='llvm/clang/lib/Driver/ToolChains/Clang.cpp' l='1016' c='_ZL23RenderDebugEnablingArgsRKN4llvm3opt7ArgListERNS_11SmallVectorIPKcLj16EEEN5clang14codegenoptions13DebugInfoKindEjNS_12DebuggerKindE'/>
<use f='llvm/clang/lib/Driver/ToolChains/Clang.cpp' l='3810' u='r' c='_ZL18renderDebugOptionsRKN5clang6driver9ToolChainERKNS0_6DriverERKN4llvm6TripleERKNS7_3opt7ArgListEbbRNS7_11SmallVectorIPKcLj16EEERNS_14codegenoptions4144156'/>
<use f='llvm/llvm/lib/CodeGen/AsmPrinter/DwarfDebug.h' l='820' u='r' c='_ZNK4llvm10DwarfDebug10tuneForGDBEv'/>
<use f='llvm/llvm/lib/CodeGen/AsmPrinter/DwarfDebug.cpp' l='361' u='r' c='_ZN4llvm10DwarfDebugC1EPNS_10AsmPrinterE'/>
<use f='llvm/llvm/lib/CodeGen/CommandFlags.cpp' l='415' u='a' c='_ZN4llvm7codegen20RegisterCodeGenFlagsC1Ev'/>
