<dec f='llvm/build/lib/Target/SystemZ/SystemZGenInstrInfo.inc' l='1455' type='1440'/>
<use f='llvm/build/lib/Target/SystemZ/SystemZGenAsmMatcher.inc' l='4290'/>
<use f='llvm/build/lib/Target/SystemZ/SystemZGenMCCodeEmitter.inc' l='3976' c='_ZNK12_GLOBAL__N_120SystemZMCCodeEmitter21getBinaryCodeForInstrERKN4llvm6MCInstERNS1_15SmallVectorImplINS1_7MCFixupEEERKNS1_15MCSubtargetInfoE'/>
<use f='llvm/build/lib/Target/SystemZ/SystemZGenDAGISel.inc' l='18682' u='r' c='_ZN12_GLOBAL__N_119SystemZDAGToDAGISel10SelectCodeEPN4llvm6SDNodeE'/>
<use f='llvm/build/lib/Target/SystemZ/SystemZGenDAGISel.inc' l='18682' u='r' c='_ZN12_GLOBAL__N_119SystemZDAGToDAGISel10SelectCodeEPN4llvm6SDNodeE'/>
<use f='llvm/llvm/lib/Target/SystemZ/SystemZInstrInfo.cpp' l='1130' u='r' c='_ZNK4llvm16SystemZInstrInfo21foldMemoryOperandImplERNS_15MachineFunctionERNS_12MachineInstrENS_8ArrayRefIjEENS_26MachineInstrBundleIteratorIS3_Lb0EEEi15416259'/>
<use f='llvm/llvm/lib/Target/SystemZ/SystemZInstrInfo.cpp' l='1344' u='r' c='_ZNK4llvm16SystemZInstrInfo18expandPostRAPseudoERNS_12MachineInstrE'/>
<use f='llvm/llvm/lib/Target/SystemZ/SystemZInstrInfo.cpp' l='1598' u='r' c='_ZNK4llvm16SystemZInstrInfo19getLoadStoreOpcodesEPKNS_19TargetRegisterClassERjS4_'/>
<use f='llvm/llvm/lib/Target/SystemZ/SystemZShortenInst.cpp' l='347' u='r' c='_ZN12_GLOBAL__N_118SystemZShortenInst12processBlockERN4llvm17MachineBasicBlockE'/>
