<dec f='llvm/llvm/lib/Target/ARM/ARMSubtarget.h' l='523' type='const llvm::ARMBaseTargetMachine &amp;'/>
<offset>5504</offset>
<use f='llvm/llvm/lib/Target/ARM/ARMSubtarget.cpp' l='102' u='w' c='_ZN4llvm12ARMSubtargetC1ERKNS_6TripleERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESB_RKNS_20ARMBaseTargetMachineEbb'/>
<use f='llvm/llvm/lib/Target/ARM/ARMSubtarget.cpp' l='331' u='m' c='_ZNK4llvm12ARMSubtarget17isTargetHardFloatEv'/>
<use f='llvm/llvm/lib/Target/ARM/ARMSubtarget.cpp' l='335' u='m' c='_ZNK4llvm12ARMSubtarget10isAPCS_ABIEv'/>
<use f='llvm/llvm/lib/Target/ARM/ARMSubtarget.cpp' l='339' u='m' c='_ZNK4llvm12ARMSubtarget11isAAPCS_ABIEv'/>
<use f='llvm/llvm/lib/Target/ARM/ARMSubtarget.cpp' l='340' u='m' c='_ZNK4llvm12ARMSubtarget11isAAPCS_ABIEv'/>
<use f='llvm/llvm/lib/Target/ARM/ARMSubtarget.cpp' l='344' u='m' c='_ZNK4llvm12ARMSubtarget13isAAPCS16_ABIEv'/>
<use f='llvm/llvm/lib/Target/ARM/ARMSubtarget.cpp' l='348' u='m' c='_ZNK4llvm12ARMSubtarget6isROPIEv'/>
<use f='llvm/llvm/lib/Target/ARM/ARMSubtarget.cpp' l='349' u='m' c='_ZNK4llvm12ARMSubtarget6isROPIEv'/>
<use f='llvm/llvm/lib/Target/ARM/ARMSubtarget.cpp' l='352' u='m' c='_ZNK4llvm12ARMSubtarget6isRWPIEv'/>
<use f='llvm/llvm/lib/Target/ARM/ARMSubtarget.cpp' l='353' u='m' c='_ZNK4llvm12ARMSubtarget6isRWPIEv'/>
<use f='llvm/llvm/lib/Target/ARM/ARMSubtarget.cpp' l='357' u='m' c='_ZNK4llvm12ARMSubtarget18isGVIndirectSymbolEPKNS_11GlobalValueE'/>
<use f='llvm/llvm/lib/Target/ARM/ARMSubtarget.cpp' l='363' u='m' c='_ZNK4llvm12ARMSubtarget18isGVIndirectSymbolEPKNS_11GlobalValueE'/>
<use f='llvm/llvm/lib/Target/ARM/ARMSubtarget.cpp' l='371' u='m' c='_ZNK4llvm12ARMSubtarget9isGVInGOTEPKNS_11GlobalValueE'/>
<use f='llvm/llvm/lib/Target/ARM/ARMSubtarget.cpp' l='372' u='m' c='_ZNK4llvm12ARMSubtarget9isGVInGOTEPKNS_11GlobalValueE'/>
<use f='llvm/llvm/lib/Target/ARM/ARMSubtarget.cpp' l='440' u='m' c='_ZNK4llvm12ARMSubtarget11useFastISelEv'/>
