<dec f='llvm/llvm/include/llvm/CodeGen/MachineModuleInfo.h' l='295' type='const llvm::LLVMTargetMachine *'/>
<use f='llvm/llvm/include/llvm/CodeGen/MachineModuleInfo.h' l='301' u='w' c='_ZN4llvm21MachineModuleAnalysisC1EPKNS_17LLVMTargetMachineE'/>
<offset>0</offset>
<use f='llvm/llvm/lib/CodeGen/MachineModuleInfo.cpp' l='336' u='r' c='_ZN4llvm21MachineModuleAnalysis3runERNS_6ModuleERNS_15AnalysisManagerIS1_JEEE'/>
