<dec f='llvm/llvm/unittests/CodeGen/TestAsmPrinter.h' l='50' type='std::unique_ptr&lt;MCContext&gt;'/>
<use f='llvm/llvm/unittests/CodeGen/TestAsmPrinter.h' l='77' u='m' c='_ZNK4llvm14TestAsmPrinter6getCtxEv'/>
<offset>0</offset>
<use f='llvm/llvm/unittests/CodeGen/TestAsmPrinter.cpp' l='58' u='m' c='_ZN4llvm14TestAsmPrinter4initEPKNS_6TargetENS_9StringRefEtNS_5dwarf11DwarfFormatE'/>
<use f='llvm/llvm/unittests/CodeGen/TestAsmPrinter.cpp' l='60' u='m' c='_ZN4llvm14TestAsmPrinter4initEPKNS_6TargetENS_9StringRefEtNS_5dwarf11DwarfFormatE'/>
<use f='llvm/llvm/unittests/CodeGen/TestAsmPrinter.cpp' l='62' u='m' c='_ZN4llvm14TestAsmPrinter4initEPKNS_6TargetENS_9StringRefEtNS_5dwarf11DwarfFormatE'/>
<use f='llvm/llvm/unittests/CodeGen/TestAsmPrinter.cpp' l='71' u='m' c='_ZN4llvm14TestAsmPrinter4initEPKNS_6TargetENS_9StringRefEtNS_5dwarf11DwarfFormatE'/>
<use f='llvm/llvm/unittests/CodeGen/TestAsmPrinter.cpp' l='75' u='m' c='_ZN4llvm14TestAsmPrinter4initEPKNS_6TargetENS_9StringRefEtNS_5dwarf11DwarfFormatE'/>
