<dec f='llvm/llvm/include/llvm/Analysis/StackSafetyAnalysis.h' l='133' type='llvm::raw_ostream &amp;'/>
<use f='llvm/llvm/include/llvm/Analysis/StackSafetyAnalysis.h' l='136' u='w' c='_ZN4llvm28StackSafetyGlobalPrinterPassC1ERNS_11raw_ostreamE'/>
<offset>0</offset>
<use f='llvm/llvm/lib/Analysis/StackSafetyAnalysis.cpp' l='955' u='m' c='_ZN4llvm28StackSafetyGlobalPrinterPass3runERNS_6ModuleERNS_15AnalysisManagerIS1_JEEE'/>
<use f='llvm/llvm/lib/Analysis/StackSafetyAnalysis.cpp' l='956' u='a' c='_ZN4llvm28StackSafetyGlobalPrinterPass3runERNS_6ModuleERNS_15AnalysisManagerIS1_JEEE'/>
