<dec f='llvm/build/lib/Target/Mips/MipsGenInstrInfo.inc' l='344' type='329'/>
<use f='llvm/build/lib/Target/Mips/MipsGenDAGISel.inc' l='24418' u='r' c='_ZN4llvm16MipsDAGToDAGISel10SelectCodeEPNS_6SDNodeE'/>
<use f='llvm/build/lib/Target/Mips/MipsGenDAGISel.inc' l='24418' u='r' c='_ZN4llvm16MipsDAGToDAGISel10SelectCodeEPNS_6SDNodeE'/>
<use f='llvm/build/lib/Target/Mips/MipsGenMCPseudoLowering.inc' l='62' c='_ZN4llvm14MipsAsmPrinter27emitPseudoExpansionLoweringERNS_10MCStreamerEPKNS_12MachineInstrE'/>
<use f='llvm/llvm/lib/Target/Mips/MipsInstrInfo.cpp' l='282' c='_ZNK4llvm13MipsInstrInfo21isBranchOffsetInRangeEjl'/>
<use f='llvm/llvm/lib/Target/Mips/MipsInstrInfo.cpp' l='477' c='_ZNK4llvm13MipsInstrInfo24getEquivalentCompactFormENS_26MachineInstrBundleIteratorINS_12MachineInstrELb0EEE'/>
<use f='llvm/build/lib/Target/Mips/MipsGenGlobalISel.inc' l='23810' u='r' c='_ZNK12_GLOBAL__N_123MipsInstructionSelector13getMatchTableEv'/>
<use f='llvm/llvm/lib/Target/Mips/MipsSEISelLowering.cpp' l='3070' u='r' c='_ZNK4llvm20MipsSETargetLowering12emitBPOSGE32ERNS_12MachineInstrEPNS_17MachineBasicBlockE'/>
<use f='llvm/llvm/lib/Target/Mips/MipsSEISelLowering.cpp' l='3139' u='r' c='_ZNK4llvm20MipsSETargetLowering20emitMSACBranchPseudoERNS_12MachineInstrEPNS_17MachineBasicBlockEj'/>
<use f='llvm/llvm/lib/Target/Mips/MipsSEInstrInfo.cpp' l='30' u='r' c='_ZL22getUnconditionalBranchRKN4llvm13MipsSubtargetE'/>
<use f='llvm/llvm/lib/Target/Mips/MipsSEInstrInfo.cpp' l='665' u='r' c='_ZNK4llvm15MipsSEInstrInfo18getAnalyzableBrOpcEj'/>
