<use f='llvm/llvm/include/llvm/ExecutionEngine/Orc/Shared/RPCUtils.h' l='1571' u='a' c='_ZN4llvm3orc6shared17ParallelCallGroup4callERKT_T0_DpRKT1_'/>
<use f='llvm/llvm/include/llvm/ExecutionEngine/Orc/Shared/RPCUtils.h' l='1581' u='a' c='_ZN4llvm3orc6shared17ParallelCallGroup4callERKT_T0_DpRKT1_'/>
<use f='llvm/llvm/include/llvm/ExecutionEngine/Orc/Shared/RPCUtils.h' l='1593' u='a' c='_ZN4llvm3orc6shared17ParallelCallGroup4waitEv'/>
<dec f='llvm/llvm/include/llvm/ExecutionEngine/Orc/Shared/RPCUtils.h' l='1599' type='std::mutex'/>
<offset>0</offset>
