<dec f='llvm/llvm/include/llvm/DebugInfo/PDB/Native/GSIStreamBuilder.h' l='89' type='std::unique_ptr&lt;GSIHashStreamBuilder&gt;'/>
<offset>256</offset>
<use f='llvm/llvm/lib/DebugInfo/PDB/Native/GSIStreamBuilder.cpp' l='193' u='m' c='_ZN4llvm3pdb16GSIStreamBuilder21finalizeGlobalBucketsEj'/>
<use f='llvm/llvm/lib/DebugInfo/PDB/Native/GSIStreamBuilder.cpp' l='287' u='w' c='_ZN4llvm3pdb16GSIStreamBuilderC1ERNS_3msf10MSFBuilderE'/>
<use f='llvm/llvm/lib/DebugInfo/PDB/Native/GSIStreamBuilder.cpp' l='302' u='m' c='_ZNK4llvm3pdb16GSIStreamBuilder30calculateGlobalsHashStreamSizeEv'/>
<use f='llvm/llvm/lib/DebugInfo/PDB/Native/GSIStreamBuilder.cpp' l='320' u='m' c='_ZN4llvm3pdb16GSIStreamBuilder17finalizeMsfLayoutEv'/>
<use f='llvm/llvm/lib/DebugInfo/PDB/Native/GSIStreamBuilder.cpp' l='376' u='m' c='_ZN4llvm3pdb16GSIStreamBuilder15addGlobalSymbolERKNS_8codeview8CVRecordINS2_10SymbolKindEEE'/>
<use f='llvm/llvm/lib/DebugInfo/PDB/Native/GSIStreamBuilder.cpp' l='475' u='m' c='_ZN4llvm3pdb16GSIStreamBuilder23commitGlobalsHashStreamENS_23WritableBinaryStreamRefE'/>
