<dec f='llvm/llvm/include/llvm/IR/PatternMatch.h' l='329' type='const llvm::APInt *&amp;'/>
<use f='llvm/llvm/include/llvm/IR/PatternMatch.h' l='331' u='w' c='_ZN4llvm12PatternMatch11api_pred_tyC1ERPKNS_5APIntE'/>
<use f='llvm/llvm/include/llvm/IR/PatternMatch.h' l='336' u='w' c='_ZN4llvm12PatternMatch11api_pred_ty5matchEPTL0__'/>
<use f='llvm/llvm/include/llvm/IR/PatternMatch.h' l='343' u='w' c='_ZN4llvm12PatternMatch11api_pred_ty5matchEPTL0__'/>
