<dec f='llvm/llvm/include/llvm/ObjectYAML/WasmYAML.h' l='85' type='llvm::StringRef'/>
<offset>0</offset>
<use f='llvm/llvm/lib/ObjectYAML/WasmEmitter.cpp' l='375' u='r' c='_ZN12_GLOBAL__N_110WasmWriter19writeSectionContentERN4llvm11raw_ostreamERNS1_8WasmYAML13ImportSectionE'/>
<use f='llvm/llvm/lib/ObjectYAML/WasmYAML.cpp' l='383' u='a' c='_ZN4llvm4yaml13MappingTraitsINS_8WasmYAML6ImportEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/tools/obj2yaml/wasm2yaml.cpp' l='230' u='w' c='_ZN12_GLOBAL__N_110WasmDumper4dumpEv'/>
