<dec f='llvm/llvm/include/llvm/XRay/FDRTraceWriter.h' l='49' type='support::endian::Writer'/>
<use f='llvm/llvm/lib/XRay/FDRTraceWriter.cpp' l='60' u='w' c='_ZN4llvm4xray14FDRTraceWriterC1ERNS_11raw_ostreamERKNS0_14XRayFileHeaderE'/>
<use f='llvm/llvm/lib/XRay/FDRTraceWriter.cpp' l='68' u='m' c='_ZN4llvm4xray14FDRTraceWriterC1ERNS_11raw_ostreamERKNS0_14XRayFileHeaderE'/>
<use f='llvm/llvm/lib/XRay/FDRTraceWriter.cpp' l='69' u='m' c='_ZN4llvm4xray14FDRTraceWriterC1ERNS_11raw_ostreamERKNS0_14XRayFileHeaderE'/>
<use f='llvm/llvm/lib/XRay/FDRTraceWriter.cpp' l='70' u='m' c='_ZN4llvm4xray14FDRTraceWriterC1ERNS_11raw_ostreamERKNS0_14XRayFileHeaderE'/>
<use f='llvm/llvm/lib/XRay/FDRTraceWriter.cpp' l='71' u='m' c='_ZN4llvm4xray14FDRTraceWriterC1ERNS_11raw_ostreamERKNS0_14XRayFileHeaderE'/>
<use f='llvm/llvm/lib/XRay/FDRTraceWriter.cpp' l='74' u='m' c='_ZN4llvm4xray14FDRTraceWriterC1ERNS_11raw_ostreamERKNS0_14XRayFileHeaderE'/>
<use f='llvm/llvm/lib/XRay/FDRTraceWriter.cpp' l='80' u='a' c='_ZN4llvm4xray14FDRTraceWriter5visitERNS0_13BufferExtentsE'/>
<use f='llvm/llvm/lib/XRay/FDRTraceWriter.cpp' l='84' u='a' c='_ZN4llvm4xray14FDRTraceWriter5visitERNS0_15WallclockRecordE'/>
<use f='llvm/llvm/lib/XRay/FDRTraceWriter.cpp' l='88' u='a' c='_ZN4llvm4xray14FDRTraceWriter5visitERNS0_14NewCPUIDRecordE'/>
<use f='llvm/llvm/lib/XRay/FDRTraceWriter.cpp' l='92' u='a' c='_ZN4llvm4xray14FDRTraceWriter5visitERNS0_13TSCWrapRecordE'/>
<use f='llvm/llvm/lib/XRay/FDRTraceWriter.cpp' l='96' u='a' c='_ZN4llvm4xray14FDRTraceWriter5visitERNS0_17CustomEventRecordE'/>
<use f='llvm/llvm/lib/XRay/FDRTraceWriter.cpp' l='100' u='m' c='_ZN4llvm4xray14FDRTraceWriter5visitERNS0_17CustomEventRecordE'/>
<use f='llvm/llvm/lib/XRay/FDRTraceWriter.cpp' l='105' u='a' c='_ZN4llvm4xray14FDRTraceWriter5visitERNS0_19CustomEventRecordV5E'/>
<use f='llvm/llvm/lib/XRay/FDRTraceWriter.cpp' l='109' u='m' c='_ZN4llvm4xray14FDRTraceWriter5visitERNS0_19CustomEventRecordV5E'/>
<use f='llvm/llvm/lib/XRay/FDRTraceWriter.cpp' l='114' u='a' c='_ZN4llvm4xray14FDRTraceWriter5visitERNS0_16TypedEventRecordE'/>
<use f='llvm/llvm/lib/XRay/FDRTraceWriter.cpp' l='118' u='m' c='_ZN4llvm4xray14FDRTraceWriter5visitERNS0_16TypedEventRecordE'/>
<use f='llvm/llvm/lib/XRay/FDRTraceWriter.cpp' l='123' u='a' c='_ZN4llvm4xray14FDRTraceWriter5visitERNS0_13CallArgRecordE'/>
<use f='llvm/llvm/lib/XRay/FDRTraceWriter.cpp' l='127' u='a' c='_ZN4llvm4xray14FDRTraceWriter5visitERNS0_9PIDRecordE'/>
<use f='llvm/llvm/lib/XRay/FDRTraceWriter.cpp' l='131' u='a' c='_ZN4llvm4xray14FDRTraceWriter5visitERNS0_15NewBufferRecordE'/>
<use f='llvm/llvm/lib/XRay/FDRTraceWriter.cpp' l='135' u='a' c='_ZN4llvm4xray14FDRTraceWriter5visitERNS0_15EndBufferRecordE'/>
<use f='llvm/llvm/lib/XRay/FDRTraceWriter.cpp' l='145' u='m' c='_ZN4llvm4xray14FDRTraceWriter5visitERNS0_14FunctionRecordE'/>
<use f='llvm/llvm/lib/XRay/FDRTraceWriter.cpp' l='146' u='m' c='_ZN4llvm4xray14FDRTraceWriter5visitERNS0_14FunctionRecordE'/>
<offset>64</offset>
