<use f='llvm/llvm/lib/ExecutionEngine/JITLink/MachOLinkGraphBuilder.h' l='86' u='m' c='_ZNK4llvm7jitlink21MachOLinkGraphBuilder8getGraphEv'/>
<dec f='llvm/llvm/lib/ExecutionEngine/JITLink/MachOLinkGraphBuilder.h' l='210' type='std::unique_ptr&lt;LinkGraph&gt;'/>
<use f='llvm/llvm/lib/ExecutionEngine/JITLink/MachOLinkGraphBuilder.cpp' l='45' u='a' c='_ZN4llvm7jitlink21MachOLinkGraphBuilder10buildGraphEv'/>
<use f='llvm/llvm/lib/ExecutionEngine/JITLink/MachOLinkGraphBuilder.cpp' l='51' u='w' c='_ZN4llvm7jitlink21MachOLinkGraphBuilderC1ERKNS_6object15MachOObjectFileENS_6TripleE'/>
<use f='llvm/llvm/lib/ExecutionEngine/JITLink/MachOLinkGraphBuilder.cpp' l='101' u='m' c='_ZN4llvm7jitlink21MachOLinkGraphBuilder16getCommonSectionEv'/>
<use f='llvm/llvm/lib/ExecutionEngine/JITLink/MachOLinkGraphBuilder.cpp' l='184' u='m' c='_ZN4llvm7jitlink21MachOLinkGraphBuilder24createNormalizedSectionsEv'/>
<use f='llvm/llvm/lib/ExecutionEngine/JITLink/MachOLinkGraphBuilder.cpp' l='319' u='m' c='_ZN4llvm7jitlink21MachOLinkGraphBuilder26addSectionStartSymAndBlockERNS0_7SectionEmPKcmjb'/>
<use f='llvm/llvm/lib/ExecutionEngine/JITLink/MachOLinkGraphBuilder.cpp' l='321' u='m' c='_ZN4llvm7jitlink21MachOLinkGraphBuilder26addSectionStartSymAndBlockERNS0_7SectionEmPKcmjb'/>
<use f='llvm/llvm/lib/ExecutionEngine/JITLink/MachOLinkGraphBuilder.cpp' l='322' u='m' c='_ZN4llvm7jitlink21MachOLinkGraphBuilder26addSectionStartSymAndBlockERNS0_7SectionEmPKcmjb'/>
<use f='llvm/llvm/lib/ExecutionEngine/JITLink/MachOLinkGraphBuilder.cpp' l='347' u='m' c='_ZN4llvm7jitlink21MachOLinkGraphBuilder22graphifyRegularSymbolsEv'/>
<use f='llvm/llvm/lib/ExecutionEngine/JITLink/MachOLinkGraphBuilder.cpp' l='356' u='m' c='_ZN4llvm7jitlink21MachOLinkGraphBuilder22graphifyRegularSymbolsEv'/>
<use f='llvm/llvm/lib/ExecutionEngine/JITLink/MachOLinkGraphBuilder.cpp' l='365' u='m' c='_ZN4llvm7jitlink21MachOLinkGraphBuilder22graphifyRegularSymbolsEv'/>
<use f='llvm/llvm/lib/ExecutionEngine/JITLink/MachOLinkGraphBuilder.cpp' l='509' u='m' c='_ZN4llvm7jitlink21MachOLinkGraphBuilder22graphifyRegularSymbolsEv'/>
<use f='llvm/llvm/lib/ExecutionEngine/JITLink/MachOLinkGraphBuilder.cpp' l='513' u='m' c='_ZN4llvm7jitlink21MachOLinkGraphBuilder22graphifyRegularSymbolsEv'/>
<use f='llvm/llvm/lib/ExecutionEngine/JITLink/MachOLinkGraphBuilder.cpp' l='542' u='m' c='_ZN4llvm7jitlink21MachOLinkGraphBuilder22graphifyRegularSymbolsEv'/>
<use f='llvm/llvm/lib/ExecutionEngine/JITLink/MachOLinkGraphBuilder.cpp' l='545' u='m' c='_ZN4llvm7jitlink21MachOLinkGraphBuilder22graphifyRegularSymbolsEv'/>
<offset>896</offset>
