<dec f='llvm/llvm/include/llvm/Support/TarWriter.h' l='27' type='llvm::raw_fd_ostream'/>
<offset>0</offset>
<use f='llvm/llvm/lib/Support/TarWriter.cpp' l='180' u='w' c='_ZN4llvm9TarWriterC1EiNS_9StringRefE'/>
<use f='llvm/llvm/lib/Support/TarWriter.cpp' l='195' u='a' c='_ZN4llvm9TarWriter6appendENS_9StringRefES1_'/>
<use f='llvm/llvm/lib/Support/TarWriter.cpp' l='197' u='a' c='_ZN4llvm9TarWriter6appendENS_9StringRefES1_'/>
<use f='llvm/llvm/lib/Support/TarWriter.cpp' l='198' u='a' c='_ZN4llvm9TarWriter6appendENS_9StringRefES1_'/>
<use f='llvm/llvm/lib/Support/TarWriter.cpp' l='201' u='m' c='_ZN4llvm9TarWriter6appendENS_9StringRefES1_'/>
<use f='llvm/llvm/lib/Support/TarWriter.cpp' l='202' u='a' c='_ZN4llvm9TarWriter6appendENS_9StringRefES1_'/>
<use f='llvm/llvm/lib/Support/TarWriter.cpp' l='207' u='m' c='_ZN4llvm9TarWriter6appendENS_9StringRefES1_'/>
<use f='llvm/llvm/lib/Support/TarWriter.cpp' l='208' u='m' c='_ZN4llvm9TarWriter6appendENS_9StringRefES1_'/>
<use f='llvm/llvm/lib/Support/TarWriter.cpp' l='209' u='m' c='_ZN4llvm9TarWriter6appendENS_9StringRefES1_'/>
<use f='llvm/llvm/lib/Support/TarWriter.cpp' l='210' u='m' c='_ZN4llvm9TarWriter6appendENS_9StringRefES1_'/>
