<dec f='llvm/llvm/lib/Target/Mips/MipsTargetObjectFile.h' l='19' type='const llvm::MipsTargetMachine *'/>
<offset>7232</offset>
<use f='llvm/llvm/lib/Target/Mips/MipsTargetObjectFile.cpp' l='55' u='w' c='_ZN4llvm20MipsTargetObjectFile10InitializeERNS_9MCContextERKNS_13TargetMachineE'/>
<use f='llvm/llvm/lib/Target/Mips/MipsTargetObjectFile.cpp' l='180' u='r' c='_ZNK4llvm20MipsTargetObjectFile21getSectionForConstantERKNS_10DataLayoutENS_11SectionKindEPKNS_8ConstantERNS_5AlignE'/>
