<dec f='llvm/llvm/lib/Target/PowerPC/PPCISelLowering.h' l='401' type='421'/>
<doc f='llvm/llvm/lib/Target/PowerPC/PPCISelLowering.h' l='399'>/// CHAIN = SC CHAIN, Imm128 - System call.  The 7-bit unsigned
    /// operand identifies the operating system entry point.</doc>
<use f='llvm/build/lib/Target/PowerPC/PPCGenDAGISel.inc' l='43356' u='r' c='_ZN12_GLOBAL__N_115PPCDAGToDAGISel10SelectCodeEPN4llvm6SDNodeE'/>
<use f='llvm/build/lib/Target/PowerPC/PPCGenDAGISel.inc' l='43356' u='r' c='_ZN12_GLOBAL__N_115PPCDAGToDAGISel10SelectCodeEPN4llvm6SDNodeE'/>
<use f='llvm/llvm/lib/Target/PowerPC/PPCISelLowering.cpp' l='1579' c='_ZNK4llvm17PPCTargetLowering17getTargetNodeNameEj'/>
