<dec f='llvm/llvm/include/llvm/Demangle/ItaniumDemangle.h' l='1969' type='const llvm::itanium_demangle::Node *'/>
<use f='llvm/llvm/include/llvm/Demangle/ItaniumDemangle.h' l='1976' u='w' c='_ZN4llvm16itanium_demangle8FoldExprC1EbNS0_10StringViewEPKNS0_4NodeES5_'/>
<use f='llvm/llvm/include/llvm/Demangle/ItaniumDemangle.h' l='1980' c='_ZNK4llvm16itanium_demangle8FoldExpr5matchET_'/>
<use f='llvm/llvm/include/llvm/Demangle/ItaniumDemangle.h' l='1994' u='r' c='_ZNK4llvm16itanium_demangle8FoldExpr9printLeftERNS0_12OutputStreamE'/>
<use f='llvm/llvm/include/llvm/Demangle/ItaniumDemangle.h' l='1995' u='r' c='_ZNK4llvm16itanium_demangle8FoldExpr9printLeftERNS0_12OutputStreamE'/>
<use f='llvm/llvm/include/llvm/Demangle/ItaniumDemangle.h' l='2012' u='r' c='_ZNK4llvm16itanium_demangle8FoldExpr9printLeftERNS0_12OutputStreamE'/>
<use f='llvm/llvm/include/llvm/Demangle/ItaniumDemangle.h' l='2016' u='r' c='_ZNK4llvm16itanium_demangle8FoldExpr9printLeftERNS0_12OutputStreamE'/>
<offset>192</offset>
