<use f='llvm/llvm/include/llvm/Analysis/IVDescriptors.h' l='272' u='r' c='_ZNK4llvm19InductionDescriptor7getKindEv'/>
<use f='llvm/llvm/include/llvm/Analysis/IVDescriptors.h' l='309' u='r' c='_ZN4llvm19InductionDescriptor16hasUnsafeAlgebraEv'/>
<use f='llvm/llvm/include/llvm/Analysis/IVDescriptors.h' l='316' u='r' c='_ZN4llvm19InductionDescriptor20getUnsafeAlgebraInstEv'/>
<dec f='llvm/llvm/include/llvm/Analysis/IVDescriptors.h' l='346' type='llvm::InductionDescriptor::InductionKind'/>
<offset>192</offset>
<doc f='llvm/llvm/include/llvm/Analysis/IVDescriptors.h' l='345'>/// Induction kind.</doc>
<use f='llvm/llvm/lib/Analysis/IVDescriptors.cpp' l='907' u='w' c='_ZN4llvm19InductionDescriptorC1EPNS_5ValueENS0_13InductionKindEPKNS_4SCEVEPNS_14BinaryOperatorEPNS_15SmallVectorImplIPNS_11InstructionEEE'/>
