<dec f='llvm/llvm/utils/TableGen/AsmWriterInst.h' l='83' type='const llvm::CodeGenInstruction *'/>
<use f='llvm/llvm/utils/TableGen/AsmWriterEmitter.cpp' l='131' u='r' c='_ZL16EmitInstructionsRSt6vectorIN4llvm13AsmWriterInstESaIS1_EERNS0_11raw_ostreamEb'/>
<use f='llvm/llvm/utils/TableGen/AsmWriterEmitter.cpp' l='132' u='r' c='_ZL16EmitInstructionsRSt6vectorIN4llvm13AsmWriterInstESaIS1_EERNS0_11raw_ostreamEb'/>
<use f='llvm/llvm/utils/TableGen/AsmWriterEmitter.cpp' l='134' u='r' c='_ZL16EmitInstructionsRSt6vectorIN4llvm13AsmWriterInstESaIS1_EERNS0_11raw_ostreamEb'/>
<use f='llvm/llvm/utils/TableGen/AsmWriterEmitter.cpp' l='135' u='r' c='_ZL16EmitInstructionsRSt6vectorIN4llvm13AsmWriterInstESaIS1_EERNS0_11raw_ostreamEb'/>
<use f='llvm/llvm/utils/TableGen/AsmWriterEmitter.cpp' l='146' u='r' c='_ZL16EmitInstructionsRSt6vectorIN4llvm13AsmWriterInstESaIS1_EERNS0_11raw_ostreamEb'/>
<use f='llvm/llvm/utils/TableGen/AsmWriterEmitter.cpp' l='147' u='r' c='_ZL16EmitInstructionsRSt6vectorIN4llvm13AsmWriterInstESaIS1_EERNS0_11raw_ostreamEb'/>
<use f='llvm/llvm/utils/TableGen/AsmWriterEmitter.cpp' l='151' u='r' c='_ZL16EmitInstructionsRSt6vectorIN4llvm13AsmWriterInstESaIS1_EERNS0_11raw_ostreamEb'/>
<use f='llvm/llvm/utils/TableGen/AsmWriterEmitter.cpp' l='152' u='r' c='_ZL16EmitInstructionsRSt6vectorIN4llvm13AsmWriterInstESaIS1_EERNS0_11raw_ostreamEb'/>
<use f='llvm/llvm/utils/TableGen/AsmWriterEmitter.cpp' l='190' u='r' c='_ZNK12_GLOBAL__N_116AsmWriterEmitter25FindUniqueOperandCommandsERSt6vectorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaIS7_EERS1_IS1_IjSaIjEESaISC_EERSC_b'/>
<use f='llvm/llvm/utils/TableGen/AsmWriterEmitter.cpp' l='194' u='r' c='_ZNK12_GLOBAL__N_116AsmWriterEmitter25FindUniqueOperandCommandsERSt6vectorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaIS7_EERS1_IS1_IjSaIjEESaISC_EERSC_b'/>
<offset>192</offset>
<use f='llvm/llvm/utils/TableGen/AsmWriterInst.cpp' l='51' u='w' c='_ZN4llvm13AsmWriterInstC1ERKNS_18CodeGenInstructionEjj'/>
