<dec f='llvm/llvm/lib/Target/X86/X86ISelLowering.h' l='394' type='478'/>
<use f='llvm/build/lib/Target/X86/X86GenDAGISel.inc' l='42799' u='r' c='_ZN12_GLOBAL__N_115X86DAGToDAGISel10SelectCodeEPN4llvm6SDNodeE'/>
<use f='llvm/build/lib/Target/X86/X86GenDAGISel.inc' l='42799' u='r' c='_ZN12_GLOBAL__N_115X86DAGToDAGISel10SelectCodeEPN4llvm6SDNodeE'/>
<use f='llvm/llvm/lib/Target/X86/X86ISelDAGToDAG.cpp' l='378' u='r' c='_ZNK12_GLOBAL__N_115X86DAGToDAGISel36shouldAvoidImmediateInstFormsForSizeEPN4llvm6SDNodeE'/>
<use f='llvm/llvm/lib/Target/X86/X86ISelDAGToDAG.cpp' l='587' c='_ZNK12_GLOBAL__N_115X86DAGToDAGISel18IsProfitableToFoldEN4llvm7SDValueEPNS1_6SDNodeES4_'/>
<use f='llvm/llvm/lib/Target/X86/X86ISelDAGToDAG.cpp' l='638' u='r' c='_ZNK12_GLOBAL__N_115X86DAGToDAGISel18IsProfitableToFoldEN4llvm7SDValueEPNS1_6SDNodeES4_'/>
<use f='llvm/llvm/lib/Target/X86/X86ISelDAGToDAG.cpp' l='2674' c='_ZN12_GLOBAL__N_115X86DAGToDAGISel13selectLEAAddrEN4llvm7SDValueERS2_S3_S3_S3_S3_'/>
<use f='llvm/llvm/lib/Target/X86/X86ISelDAGToDAG.cpp' l='3143' c='_ZN12_GLOBAL__N_115X86DAGToDAGISel27foldLoadStoreIntoMemOperandEPN4llvm6SDNodeE'/>
<use f='llvm/llvm/lib/Target/X86/X86ISelDAGToDAG.cpp' l='3195' c='_ZN12_GLOBAL__N_115X86DAGToDAGISel27foldLoadStoreIntoMemOperandEPN4llvm6SDNodeE'/>
<use f='llvm/llvm/lib/Target/X86/X86ISelDAGToDAG.cpp' l='3237' c='_ZN12_GLOBAL__N_115X86DAGToDAGISel27foldLoadStoreIntoMemOperandEPN4llvm6SDNodeE'/>
<use f='llvm/llvm/lib/Target/X86/X86ISelDAGToDAG.cpp' l='3261' c='_ZN12_GLOBAL__N_115X86DAGToDAGISel27foldLoadStoreIntoMemOperandEPN4llvm6SDNodeE'/>
<use f='llvm/llvm/lib/Target/X86/X86ISelDAGToDAG.cpp' l='3283' c='_ZN12_GLOBAL__N_115X86DAGToDAGISel27foldLoadStoreIntoMemOperandEPN4llvm6SDNodeE'/>
<use f='llvm/llvm/lib/Target/X86/X86ISelDAGToDAG.cpp' l='3314' u='r' c='_ZN12_GLOBAL__N_115X86DAGToDAGISel27foldLoadStoreIntoMemOperandEPN4llvm6SDNodeE'/>
<use f='llvm/llvm/lib/Target/X86/X86ISelDAGToDAG.cpp' l='3320' u='r' c='_ZN12_GLOBAL__N_115X86DAGToDAGISel27foldLoadStoreIntoMemOperandEPN4llvm6SDNodeE'/>
<use f='llvm/llvm/lib/Target/X86/X86IntrinsicsInfo.h' l='1109'/>
<use f='llvm/llvm/lib/Target/X86/X86IntrinsicsInfo.h' l='1110'/>
<use f='llvm/llvm/lib/Target/X86/X86ISelLowering.cpp' l='22272' u='r' c='_ZL8EmitTestN4llvm7SDValueEjRKNS_5SDLocERNS_12SelectionDAGERKNS_12X86SubtargetE'/>
<use f='llvm/llvm/lib/Target/X86/X86ISelLowering.cpp' l='22281' c='_ZL8EmitTestN4llvm7SDValueEjRKNS_5SDLocERNS_12SelectionDAGERKNS_12X86SubtargetE'/>
<use f='llvm/llvm/lib/Target/X86/X86ISelLowering.cpp' l='22290' u='r' c='_ZL8EmitTestN4llvm7SDValueEjRKNS_5SDLocERNS_12SelectionDAGERKNS_12X86SubtargetE'/>
<use f='llvm/llvm/lib/Target/X86/X86ISelLowering.cpp' l='22389' u='r' c='_ZL7EmitCmpN4llvm7SDValueES0_jRKNS_5SDLocERNS_12SelectionDAGERKNS_12X86SubtargetE'/>
<use f='llvm/llvm/lib/Target/X86/X86ISelLowering.cpp' l='23477' u='r' c='_ZL13getX86XALUOOpRN4llvm3X868CondCodeENS_7SDValueERNS_12SelectionDAGE'/>
<use f='llvm/llvm/lib/Target/X86/X86ISelLowering.cpp' l='23481' u='r' c='_ZL13getX86XALUOOpRN4llvm3X868CondCodeENS_7SDValueERNS_12SelectionDAGE'/>
<use f='llvm/llvm/lib/Target/X86/X86ISelLowering.cpp' l='23526' u='r' c='_ZL15isX86LogicalCmpN4llvm7SDValueE'/>
<use f='llvm/llvm/lib/Target/X86/X86ISelLowering.cpp' l='23667' u='r' c='_ZNK4llvm17X86TargetLowering11LowerSELECTENS_7SDValueERNS_12SelectionDAGE'/>
<use f='llvm/llvm/lib/Target/X86/X86ISelLowering.cpp' l='23672' u='r' c='_ZNK4llvm17X86TargetLowering11LowerSELECTENS_7SDValueERNS_12SelectionDAGE'/>
<use f='llvm/llvm/lib/Target/X86/X86ISelLowering.cpp' l='23783' u='r' c='_ZNK4llvm17X86TargetLowering11LowerSELECTENS_7SDValueERNS_12SelectionDAGE'/>
<use f='llvm/llvm/lib/Target/X86/X86ISelLowering.cpp' l='27188' u='r' c='_ZL8LowerABSN4llvm7SDValueERKNS_12X86SubtargetERNS_12SelectionDAGE'/>
<use f='llvm/llvm/lib/Target/X86/X86ISelLowering.cpp' l='31103' c='_ZNK4llvm17X86TargetLowering17getTargetNodeNameEj'/>
<use f='llvm/llvm/lib/Target/X86/X86ISelLowering.cpp' l='41576' u='r' c='_ZL23combineSetCCAtomicArithN4llvm7SDValueERNS_3X868CondCodeERNS_12SelectionDAGERKNS_12X86SubtargetE'/>
<use f='llvm/llvm/lib/Target/X86/X86ISelLowering.cpp' l='41681' u='r' c='_ZL25checkBoolTestSetCCCombineN4llvm7SDValueERNS_3X868CondCodeE'/>
<use f='llvm/llvm/lib/Target/X86/X86ISelLowering.cpp' l='41862' u='r' c='_ZL22combineCarryThroughADDN4llvm7SDValueERNS_12SelectionDAGE'/>
<use f='llvm/llvm/lib/Target/X86/X86ISelLowering.cpp' l='41867' u='r' c='_ZL22combineCarryThroughADDN4llvm7SDValueERNS_12SelectionDAGE'/>
<use f='llvm/llvm/lib/Target/X86/X86ISelLowering.cpp' l='42023' u='r' c='_ZL18combineSetCCMOVMSKN4llvm7SDValueERNS_3X868CondCodeERNS_12SelectionDAGERKNS_12X86SubtargetE'/>
<use f='llvm/llvm/lib/Target/X86/X86ISelLowering.cpp' l='42050' u='r' c='_ZL18combineSetCCMOVMSKN4llvm7SDValueERNS_3X868CondCodeERNS_12SelectionDAGERKNS_12X86SubtargetE'/>
<use f='llvm/llvm/lib/Target/X86/X86ISelLowering.cpp' l='42314' u='r' c='_ZL11combineCMovPN4llvm6SDNodeERNS_12SelectionDAGERNS_14TargetLowering15DAGCombinerInfoERKNS_12X86SubtargetE'/>
<use f='llvm/llvm/lib/Target/X86/X86ISelLowering.cpp' l='48461' u='r' c='_ZL10combineCMPPN4llvm6SDNodeERNS_12SelectionDAGE'/>
<use f='llvm/llvm/lib/Target/X86/X86ISelLowering.cpp' l='48511' u='r' c='_ZL16combineX86AddSubPN4llvm6SDNodeERNS_12SelectionDAGERNS_14TargetLowering15DAGCombinerInfoE'/>
<use f='llvm/llvm/lib/Target/X86/X86ISelLowering.cpp' l='48623' u='r' c='_ZL25combineAddOrSubToADCOrSBBPN4llvm6SDNodeERNS_12SelectionDAGE'/>
<use f='llvm/llvm/lib/Target/X86/X86ISelLowering.cpp' l='48630' u='r' c='_ZL25combineAddOrSubToADCOrSBBPN4llvm6SDNodeERNS_12SelectionDAGE'/>
<use f='llvm/llvm/lib/Target/X86/X86ISelLowering.cpp' l='48656' u='r' c='_ZL25combineAddOrSubToADCOrSBBPN4llvm6SDNodeERNS_12SelectionDAGE'/>
<use f='llvm/llvm/lib/Target/X86/X86ISelLowering.cpp' l='48659' u='r' c='_ZL25combineAddOrSubToADCOrSBBPN4llvm6SDNodeERNS_12SelectionDAGE'/>
<use f='llvm/llvm/lib/Target/X86/X86ISelLowering.cpp' l='48687' u='r' c='_ZL25combineAddOrSubToADCOrSBBPN4llvm6SDNodeERNS_12SelectionDAGE'/>
<use f='llvm/llvm/lib/Target/X86/X86ISelLowering.cpp' l='48691' u='r' c='_ZL25combineAddOrSubToADCOrSBBPN4llvm6SDNodeERNS_12SelectionDAGE'/>
<use f='llvm/llvm/lib/Target/X86/X86ISelLowering.cpp' l='48723' u='r' c='_ZL25combineAddOrSubToADCOrSBBPN4llvm6SDNodeERNS_12SelectionDAGE'/>
<use f='llvm/llvm/lib/Target/X86/X86ISelLowering.cpp' l='48737' u='r' c='_ZL25combineAddOrSubToADCOrSBBPN4llvm6SDNodeERNS_12SelectionDAGE'/>
<use f='llvm/llvm/lib/Target/X86/X86ISelLowering.cpp' l='48747' u='r' c='_ZL25combineAddOrSubToADCOrSBBPN4llvm6SDNodeERNS_12SelectionDAGE'/>
<use f='llvm/llvm/lib/Target/X86/X86ISelLowering.cpp' l='50309' c='_ZNK4llvm17X86TargetLowering17PerformDAGCombineEPNS_6SDNodeERNS_14TargetLowering15DAGCombinerInfoE'/>
