<dec f='llvm/llvm/include/llvm/Analysis/BlockFrequencyInfo.h' l='129' type='llvm::raw_ostream &amp;'/>
<use f='llvm/llvm/include/llvm/Analysis/BlockFrequencyInfo.h' l='132' u='w' c='_ZN4llvm25BlockFrequencyPrinterPassC1ERNS_11raw_ostreamE'/>
<offset>0</offset>
<use f='llvm/llvm/lib/Analysis/BlockFrequencyInfo.cpp' l='343' u='m' c='_ZN4llvm25BlockFrequencyPrinterPass3runERNS_8FunctionERNS_15AnalysisManagerIS1_JEEE'/>
<use f='llvm/llvm/lib/Analysis/BlockFrequencyInfo.cpp' l='346' u='a' c='_ZN4llvm25BlockFrequencyPrinterPass3runERNS_8FunctionERNS_15AnalysisManagerIS1_JEEE'/>
