<dec f='llvm/llvm/lib/Target/RISCV/RISCVTargetTransformInfo.h' l='33' type='const llvm::RISCVSubtarget *'/>
<use f='llvm/llvm/lib/Target/RISCV/RISCVTargetTransformInfo.h' l='36' u='r' c='_ZNK4llvm12RISCVTTIImpl5getSTEv'/>
<use f='llvm/llvm/lib/Target/RISCV/RISCVTargetTransformInfo.h' l='41' u='w' c='_ZN4llvm12RISCVTTIImplC1EPKNS_18RISCVTargetMachineERKNS_8FunctionE'/>
<use f='llvm/llvm/lib/Target/RISCV/RISCVTargetTransformInfo.h' l='42' u='r' c='_ZN4llvm12RISCVTTIImplC1EPKNS_18RISCVTargetMachineERKNS_8FunctionE'/>
<offset>128</offset>
