<dec f='llvm/llvm/lib/Target/ARM/ARMConstantPoolValue.h' l='211' type='const std::string'/>
<use f='llvm/llvm/lib/Target/ARM/ARMConstantPoolValue.h' l='221' u='r' c='_ZNK4llvm21ARMConstantPoolSymbol9getSymbolEv'/>
<use f='llvm/llvm/lib/Target/ARM/ARMConstantPoolValue.h' l='239' u='r' c='_ZNK4llvm21ARMConstantPoolSymbol6equalsEPKS0_'/>
<use f='llvm/llvm/lib/Target/ARM/ARMConstantPoolValue.h' l='239' u='r' c='_ZNK4llvm21ARMConstantPoolSymbol6equalsEPKS0_'/>
<offset>320</offset>
<doc f='llvm/llvm/lib/Target/ARM/ARMConstantPoolValue.h' l='211'>// ExtSymbol being loaded.</doc>
<use f='llvm/llvm/lib/Target/ARM/ARMConstantPoolValue.cpp' l='231' u='w' c='_ZN4llvm21ARMConstantPoolSymbolC1ERNS_11LLVMContextENS_9StringRefEjhNS_5ARMCP13ARMCPModifierEb'/>
<use f='llvm/llvm/lib/Target/ARM/ARMConstantPoolValue.cpp' l='246' u='r' c='_ZN4llvm21ARMConstantPoolSymbol12hasSameValueEPNS_20ARMConstantPoolValueE'/>
<use f='llvm/llvm/lib/Target/ARM/ARMConstantPoolValue.cpp' l='246' u='r' c='_ZN4llvm21ARMConstantPoolSymbol12hasSameValueEPNS_20ARMConstantPoolValueE'/>
<use f='llvm/llvm/lib/Target/ARM/ARMConstantPoolValue.cpp' l='250' u='r' c='_ZN4llvm21ARMConstantPoolSymbol20addSelectionDAGCSEIdERNS_16FoldingSetNodeIDE'/>
<use f='llvm/llvm/lib/Target/ARM/ARMConstantPoolValue.cpp' l='255' u='r' c='_ZNK4llvm21ARMConstantPoolSymbol5printERNS_11raw_ostreamE'/>
