<use f='llvm/llvm/include/llvm/ExecutionEngine/Orc/MachOPlatform.h' l='115' u='w' c='_ZN4llvm3orc13MachOPlatform17InitScraperPluginC1ERS1_'/>
<dec f='llvm/llvm/include/llvm/ExecutionEngine/Orc/MachOPlatform.h' l='148' type='llvm::orc::MachOPlatform &amp;'/>
<offset>384</offset>
<use f='llvm/llvm/lib/ExecutionEngine/Orc/MachOPlatform.cpp' l='378' u='m' c='_ZN4llvm3orc13MachOPlatform17InitScraperPlugin16modifyPassConfigERNS0_29MaterializationResponsibilityERKNS_6TripleERNS_7jitlink17PassConfigurationE'/>
