<dec f='llvm/llvm/lib/Target/X86/X86Subtarget.h' l='75' type='const llvm::TargetMachine &amp;'/>
<offset>2048</offset>
<use f='llvm/llvm/lib/Target/X86/X86Subtarget.cpp' l='77' u='m' c='_ZNK4llvm12X86Subtarget22classifyLocalReferenceEPKNS_11GlobalValueE'/>
<use f='llvm/llvm/lib/Target/X86/X86Subtarget.cpp' l='126' u='m' c='_ZNK4llvm12X86Subtarget23classifyGlobalReferenceEPKNS_11GlobalValueERKNS_6ModuleE'/>
<use f='llvm/llvm/lib/Target/X86/X86Subtarget.cpp' l='142' u='m' c='_ZNK4llvm12X86Subtarget23classifyGlobalReferenceEPKNS_11GlobalValueERKNS_6ModuleE'/>
<use f='llvm/llvm/lib/Target/X86/X86Subtarget.cpp' l='158' u='m' c='_ZNK4llvm12X86Subtarget23classifyGlobalReferenceEPKNS_11GlobalValueERKNS_6ModuleE'/>
<use f='llvm/llvm/lib/Target/X86/X86Subtarget.cpp' l='171' u='m' c='_ZNK4llvm12X86Subtarget23classifyGlobalReferenceEPKNS_11GlobalValueERKNS_6ModuleE'/>
<use f='llvm/llvm/lib/Target/X86/X86Subtarget.cpp' l='184' u='m' c='_ZNK4llvm12X86Subtarget31classifyGlobalFunctionReferenceEPKNS_11GlobalValueERKNS_6ModuleE'/>
<use f='llvm/llvm/lib/Target/X86/X86Subtarget.cpp' l='210' u='m' c='_ZNK4llvm12X86Subtarget31classifyGlobalFunctionReferenceEPKNS_11GlobalValueERKNS_6ModuleE'/>
<use f='llvm/llvm/lib/Target/X86/X86Subtarget.cpp' l='234' u='m' c='_ZNK4llvm12X86Subtarget26isLegalToCallImmediateAddrEv'/>
<use f='llvm/llvm/lib/Target/X86/X86Subtarget.cpp' l='299' u='w' c='_ZN4llvm12X86SubtargetC1ERKNS_6TripleENS_9StringRefES4_S4_RKNS_16X86TargetMachineENS_10MaybeAlignEjj'/>
<use f='llvm/llvm/lib/Target/X86/X86Subtarget.cpp' l='351' u='m' c='_ZNK4llvm12X86Subtarget21isPositionIndependentEv'/>
