<use f='llvm/llvm/include/llvm/CodeGen/TargetLowering.h' l='335' u='a' c='_ZNK4llvm18TargetLoweringBase16getTargetMachineEv'/>
<dec f='llvm/llvm/include/llvm/CodeGen/TargetLowering.h' l='2842' type='const llvm::TargetMachine &amp;'/>
<offset>64</offset>
<use f='llvm/llvm/lib/CodeGen/TargetLoweringBase.cpp' l='684' u='w' c='_ZN4llvm18TargetLoweringBaseC1ERKNS_13TargetMachineE'/>
<use f='llvm/llvm/lib/CodeGen/TargetLoweringBase.cpp' l='714' u='m' c='_ZN4llvm18TargetLoweringBaseC1ERKNS_13TargetMachineE'/>
<use f='llvm/llvm/lib/CodeGen/TargetLoweringBase.cpp' l='929' u='m' c='_ZNK4llvm18TargetLoweringBase19isFreeAddrSpaceCastEjj'/>
<use f='llvm/llvm/lib/CodeGen/TargetLoweringBase.cpp' l='1885' u='m' c='_ZNK4llvm18TargetLoweringBase27getSafeStackPointerLocationERNS_9IRBuilderINS_14ConstantFolderENS_24IRBuilderDefaultInserterEEE'/>
<use f='llvm/llvm/lib/CodeGen/TargetLoweringBase.cpp' l='1963' u='m' c='_ZNK4llvm18TargetLoweringBase21insertSSPDeclarationsERNS_6ModuleE'/>
<use f='llvm/llvm/lib/CodeGen/TargetLoweringBase.cpp' l='1964' u='m' c='_ZNK4llvm18TargetLoweringBase21insertSSPDeclarationsERNS_6ModuleE'/>
