<use f='llvm/llvm/include/llvm/Analysis/DependenceAnalysis.h' l='970' u='w' c='_ZN4llvm29DependenceAnalysisPrinterPassC1ERNS_11raw_ostreamE'/>
<dec f='llvm/llvm/include/llvm/Analysis/DependenceAnalysis.h' l='975' type='llvm::raw_ostream &amp;'/>
<offset>0</offset>
<use f='llvm/llvm/lib/Analysis/DependenceAnalysis.cpp' l='212' u='m' c='_ZN4llvm29DependenceAnalysisPrinterPass3runERNS_8FunctionERNS_15AnalysisManagerIS1_JEEE'/>
<use f='llvm/llvm/lib/Analysis/DependenceAnalysis.cpp' l='213' u='a' c='_ZN4llvm29DependenceAnalysisPrinterPass3runERNS_8FunctionERNS_15AnalysisManagerIS1_JEEE'/>
