<use f='llvm/llvm/include/llvm/Transforms/IPO/Inliner.h' l='132' u='a' c='_ZN4llvm24ModuleInlinerWrapperPass5getPMEv'/>
<dec f='llvm/llvm/include/llvm/Transforms/IPO/Inliner.h' l='143' type='llvm::CGSCCPassManager'/>
<offset>576</offset>
<use f='llvm/llvm/lib/Transforms/IPO/Inliner.cpp' l='1001' u='w' c='_ZN4llvm24ModuleInlinerWrapperPassC1ENS_12InlineParamsEbbNS_19InliningAdvisorModeEj'/>
<use f='llvm/llvm/lib/Transforms/IPO/Inliner.cpp' l='1008' u='m' c='_ZN4llvm24ModuleInlinerWrapperPassC1ENS_12InlineParamsEbbNS_19InliningAdvisorModeEj'/>
<use f='llvm/llvm/lib/Transforms/IPO/Inliner.cpp' l='1009' u='m' c='_ZN4llvm24ModuleInlinerWrapperPassC1ENS_12InlineParamsEbbNS_19InliningAdvisorModeEj'/>
<use f='llvm/llvm/lib/Transforms/IPO/Inliner.cpp' l='1030' u='a' c='_ZN4llvm24ModuleInlinerWrapperPass3runERNS_6ModuleERNS_15AnalysisManagerIS1_JEEE'/>
<use f='llvm/llvm/lib/Transforms/IPO/Inliner.cpp' l='1033' u='a' c='_ZN4llvm24ModuleInlinerWrapperPass3runERNS_6ModuleERNS_15AnalysisManagerIS1_JEEE'/>
