<dec f='llvm/llvm/include/llvm/Analysis/AliasAnalysis.h' l='123' type='6'/>
<use f='llvm/llvm/include/llvm/Analysis/AliasAnalysis.h' l='125' u='r'/>
<use f='llvm/llvm/include/llvm/Analysis/AliasAnalysis.h' l='183' u='r' c='_ZN4llvm8clearRefENS_10ModRefInfoE'/>
<use f='llvm/llvm/include/llvm/Analysis/AliasAnalysis.h' l='244' u='r'/>
<use f='llvm/llvm/include/llvm/Analysis/AliasAnalysis.h' l='266' u='r'/>
<use f='llvm/llvm/include/llvm/Analysis/AliasAnalysis.h' l='295' u='r'/>
<use f='llvm/llvm/include/llvm/Analysis/AliasAnalysis.h' l='321' u='r'/>
<doc f='llvm/llvm/include/llvm/Analysis/AliasAnalysis.h' l='122'>/// The access may modify the value stored in memory.</doc>
<use f='llvm/llvm/lib/Analysis/AliasAnalysis.cpp' l='330' u='r' c='_ZN4llvm9AAResults13getModRefInfoEPKNS_8CallBaseES3_RNS_11AAQueryInfoE'/>
<use f='llvm/llvm/lib/Analysis/AliasAnalysis.cpp' l='506' u='r' c='_ZN4llvm9AAResults13getModRefInfoEPKNS_9StoreInstERKNS_14MemoryLocationERNS_11AAQueryInfoE'/>
<use f='llvm/llvm/lib/Analysis/AliasAnalysis.cpp' l='754' u='r' c='_ZN4llvm9AAResults19canBasicBlockModifyERKNS_10BasicBlockERKNS_14MemoryLocationE'/>
<use f='llvm/llvm/lib/Analysis/AliasAnalysisEvaluator.cpp' l='245' c='_ZN4llvm11AAEvaluator11runInternalERNS_8FunctionERNS_9AAResultsE'/>
<use f='llvm/llvm/lib/Analysis/AliasAnalysisEvaluator.cpp' l='292' c='_ZN4llvm11AAEvaluator11runInternalERNS_8FunctionERNS_9AAResultsE'/>
<use f='llvm/llvm/lib/Analysis/BasicAliasAnalysis.cpp' l='756' u='r' c='_ZN4llvm13BasicAAResult16getArgModRefInfoEPKNS_8CallBaseEj'/>
<use f='llvm/llvm/lib/Analysis/BasicAliasAnalysis.cpp' l='833' u='r' c='_ZN4llvm13BasicAAResult13getModRefInfoEPKNS_8CallBaseERKNS_14MemoryLocationERNS_11AAQueryInfoE'/>
<use f='llvm/llvm/lib/Analysis/BasicAliasAnalysis.cpp' l='1012' u='r' c='_ZN4llvm13BasicAAResult13getModRefInfoEPKNS_8CallBaseES3_RNS_11AAQueryInfoE'/>
<use f='llvm/llvm/lib/Analysis/GlobalsModRef.cpp' l='328' u='r' c='_ZN4llvm15GlobalsAAResult14AnalyzeGlobalsERNS_6ModuleE'/>
<use f='llvm/llvm/lib/Analysis/GlobalsModRef.cpp' l='613' u='r' c='_ZN4llvm15GlobalsAAResult16AnalyzeCallGraphERNS_9CallGraphERNS_6ModuleE'/>
<use f='llvm/llvm/lib/Analysis/MemoryDependenceAnalysis.cpp' l='134' u='r' c='_ZL11GetLocationPKN4llvm11InstructionERNS_14MemoryLocationERKNS_17TargetLibraryInfoE'/>
<use f='llvm/llvm/lib/Analysis/MemoryDependenceAnalysis.cpp' l='152' u='r' c='_ZL11GetLocationPKN4llvm11InstructionERNS_14MemoryLocationERKNS_17TargetLibraryInfoE'/>
<use f='llvm/llvm/lib/Analysis/MemoryDependenceAnalysis.cpp' l='163' u='r' c='_ZL11GetLocationPKN4llvm11InstructionERNS_14MemoryLocationERKNS_17TargetLibraryInfoE'/>
<use f='llvm/llvm/lib/Analysis/MemoryDependenceAnalysis.cpp' l='168' u='r' c='_ZL11GetLocationPKN4llvm11InstructionERNS_14MemoryLocationERKNS_17TargetLibraryInfoE'/>
<use f='llvm/llvm/lib/Analysis/MemoryDependenceAnalysis.cpp' l='174' u='r' c='_ZL11GetLocationPKN4llvm11InstructionERNS_14MemoryLocationERKNS_17TargetLibraryInfoE'/>
<use f='llvm/llvm/lib/Analysis/MemoryDependenceAnalysis.cpp' l='629' c='_ZN4llvm23MemoryDependenceResults30getSimplePointerDependencyFromERKNS_14MemoryLocationEbNS_14ilist_iteratorINS_12ilist_detail12node_optionsINS_11Inst8138037'/>
<use f='llvm/llvm/lib/Target/Hexagon/HexagonLoopIdiomRecognition.cpp' l='2138' u='r' c='_ZN12_GLOBAL__N_125HexagonLoopIdiomRecognize19processCopyingStoreEPN4llvm4LoopEPNS1_9StoreInstEPKNS1_4SCEVE'/>
<use f='llvm/llvm/lib/Transforms/IPO/ArgumentPromotion.cpp' l='755' u='r' c='_ZL23isSafeToPromoteArgumentPN4llvm8ArgumentEPNS_4TypeERNS_9AAResultsEj'/>
<use f='llvm/llvm/lib/Transforms/Scalar/LoopIdiomRecognize.cpp' l='1138' u='r' c='_ZN12_GLOBAL__N_118LoopIdiomRecognize26processLoopStoreOfLoopLoadEPN4llvm9StoreInstEPKNS1_4SCEVE'/>
<use f='llvm/llvm/unittests/Analysis/AliasAnalysisTest.cpp' l='196' u='r' c='_ZN12_GLOBAL__N_136AliasAnalysisTest_getModRefInfo_Test8TestBodyEv'/>
<use f='llvm/llvm/unittests/Analysis/AliasAnalysisTest.cpp' l='197' u='r' c='_ZN12_GLOBAL__N_136AliasAnalysisTest_getModRefInfo_Test8TestBodyEv'/>
