<dec f='llvm/llvm/include/llvm/DebugInfo/Symbolize/DIPrinter.h' l='30' type='1'/>
<use f='llvm/llvm/lib/DebugInfo/Symbolize/DIPrinter.cpp' l='80' u='r' c='_ZN4llvm9symbolize9DIPrinter5printERKNS_10DILineInfoEb'/>
<use f='llvm/llvm/tools/llvm-symbolizer/llvm-symbolizer.cpp' l='175' u='r' c='_ZL14symbolizeInputRKN4llvm3opt12InputArgListEmbNS_9symbolize9DIPrinter11OutputStyleENS_9StringRefERNS4_14LLVMSymbolizerERS5_'/>
<use f='llvm/llvm/tools/llvm-symbolizer/llvm-symbolizer.cpp' l='317' u='r' c='main'/>
<use f='llvm/llvm/tools/llvm-symbolizer/llvm-symbolizer.cpp' l='320' u='r' c='main'/>
