<dec f='llvm/llvm/lib/Target/X86/X86LegalizerInfo.h' l='30' type='const llvm::X86TargetMachine &amp;'/>
<use f='llvm/llvm/lib/Target/X86/X86LegalizerInfo.cpp' l='60' u='w' c='_ZN4llvm16X86LegalizerInfoC1ERKNS_12X86SubtargetERKNS_16X86TargetMachineE'/>
<use f='llvm/llvm/lib/Target/X86/X86LegalizerInfo.cpp' l='102' u='m' c='_ZN4llvm16X86LegalizerInfo21setLegalizerInfo32bitEv'/>
<use f='llvm/llvm/lib/Target/X86/X86LegalizerInfo.cpp' l='197' u='m' c='_ZN4llvm16X86LegalizerInfo21setLegalizerInfo64bitEv'/>
<offset>746176</offset>
