<dec f='llvm/build/lib/Target/Lanai/LanaiGenRegisterInfo.inc' l='29' type='9'/>
<use f='llvm/build/lib/Target/Lanai/LanaiGenAsmMatcher.inc' l='766' c='_ZL20validateOperandClassRN4llvm18MCParsedAsmOperandEN12_GLOBAL__N_114MatchClassKindE'/>
<use f='llvm/llvm/lib/Target/Lanai/MCTargetDesc/LanaiBaseInfo.h' l='46' c='_ZN4llvmL25getLanaiRegisterNumberingEj'/>
<use f='llvm/llvm/lib/Target/Lanai/LanaiRegisterInfo.cpp' l='48' u='r' c='_ZNK4llvm17LanaiRegisterInfo15getReservedRegsERKNS_15MachineFunctionE'/>
