<def f='llvm/llvm/include/llvm/BinaryFormat/Minidump.h' l='203' ll='214'/>
<use f='llvm/llvm/include/llvm/BinaryFormat/Minidump.h' l='215'/>
<use f='llvm/llvm/include/llvm/Object/Minidump.h' l='71' c='_ZNK4llvm6object12MinidumpFile13getModuleListEv'/>
<use f='llvm/llvm/include/llvm/Object/Minidump.h' l='72' c='_ZNK4llvm6object12MinidumpFile13getModuleListEv'/>
<use f='llvm/lldb/source/Plugins/Process/minidump/MinidumpParser.h' l='59' c='_ZN12lldb_private8minidump14MinidumpParser13GetModuleUUIDEPKN4llvm8minidump6ModuleE'/>
<use f='llvm/lldb/source/Plugins/Process/minidump/MinidumpParser.h' l='77' c='_ZN12lldb_private8minidump14MinidumpParser13GetModuleListEv'/>
<use f='llvm/lldb/source/Plugins/Process/minidump/MinidumpParser.h' l='83' c='_ZN12lldb_private8minidump14MinidumpParser21GetFilteredModuleListEv'/>
<use f='llvm/lldb/source/Plugins/Process/minidump/MinidumpParser.cpp' l='51' c='_ZN12lldb_private8minidump14MinidumpParser13GetModuleUUIDEPKN4llvm8minidump6ModuleE'/>
<use f='llvm/lldb/source/Plugins/Process/minidump/MinidumpParser.cpp' l='249' c='_ZN12lldb_private8minidump14MinidumpParser13GetModuleListEv'/>
<use f='llvm/lldb/source/Plugins/Process/minidump/MinidumpParser.cpp' l='347' c='_ZN12lldb_private8minidump14MinidumpParser21GetFilteredModuleListEv'/>
<use f='llvm/lldb/source/Plugins/Process/minidump/MinidumpParser.cpp' l='369' c='_ZN12lldb_private8minidump14MinidumpParser21GetFilteredModuleListEv'/>
<size>108</size>
<mbr r='llvm::minidump::Module::BaseOfImage' o='0' t='support::ulittle64_t'/>
<mbr r='llvm::minidump::Module::SizeOfImage' o='64' t='support::ulittle32_t'/>
<mbr r='llvm::minidump::Module::Checksum' o='96' t='support::ulittle32_t'/>
<mbr r='llvm::minidump::Module::TimeDateStamp' o='128' t='support::ulittle32_t'/>
<mbr r='llvm::minidump::Module::ModuleNameRVA' o='160' t='support::ulittle32_t'/>
<mbr r='llvm::minidump::Module::VersionInfo' o='192' t='llvm::minidump::VSFixedFileInfo'/>
<mbr r='llvm::minidump::Module::CvRecord' o='608' t='llvm::minidump::LocationDescriptor'/>
<mbr r='llvm::minidump::Module::MiscRecord' o='672' t='llvm::minidump::LocationDescriptor'/>
<mbr r='llvm::minidump::Module::Reserved0' o='736' t='support::ulittle64_t'/>
<mbr r='llvm::minidump::Module::Reserved1' o='800' t='support::ulittle64_t'/>
<use f='llvm/lldb/source/Plugins/Process/minidump/ProcessMinidump.cpp' l='536' c='_ZN12lldb_private8minidump15ProcessMinidump14ReadModuleListEv'/>
<size>108</size>
<use f='llvm/lldb/unittests/Process/minidump/MinidumpParserTest.cpp' l='242' c='_ZN45MinidumpParserTest_GetFilteredModuleList_Test8TestBodyEv'/>
<use f='llvm/lldb/unittests/Process/minidump/MinidumpParserTest.cpp' l='243' c='_ZN45MinidumpParserTest_GetFilteredModuleList_Test8TestBodyEv'/>
<use f='llvm/lldb/unittests/Process/minidump/MinidumpParserTest.cpp' l='247' c='_ZN45MinidumpParserTest_GetFilteredModuleList_Test8TestBodyEv'/>
<use f='llvm/lldb/unittests/Process/minidump/MinidumpParserTest.cpp' l='708' c='_ZN57MinidumpParserTest_MinidumpDuplicateModuleMinAddress_Test8TestBodyEv'/>
<use f='llvm/lldb/unittests/Process/minidump/MinidumpParserTest.cpp' l='748' c='_ZN58MinidumpParserTest_MinidumpDuplicateModuleMappedFirst_Test8TestBodyEv'/>
<use f='llvm/lldb/unittests/Process/minidump/MinidumpParserTest.cpp' l='789' c='_ZN59MinidumpParserTest_MinidumpDuplicateModuleMappedSecond_Test8TestBodyEv'/>
<use f='llvm/lldb/unittests/Process/minidump/MinidumpParserTest.cpp' l='830' c='_ZN63MinidumpParserTest_MinidumpDuplicateModuleMappedSecondHigh_Test8TestBodyEv'/>
<use f='llvm/lldb/unittests/Process/minidump/MinidumpParserTest.cpp' l='873' c='_ZN59MinidumpParserTest_MinidumpDuplicateModuleSeparateCode_Test8TestBodyEv'/>
<use f='llvm/lldb/unittests/Process/minidump/MinidumpParserTest.cpp' l='899' c='_ZN43MinidumpParserTest_MinidumpModuleOrder_Test8TestBodyEv'/>
<size>108</size>
<use f='llvm/llvm/include/llvm/ObjectYAML/MinidumpYAML.h' l='77'/>
<size>108</size>
<use f='llvm/llvm/lib/ObjectYAML/MinidumpYAML.cpp' l='502' c='_ZN4llvm12MinidumpYAML6Stream6createERKNS_8minidump9DirectoryERKNS_6object12MinidumpFileE'/>
<size>108</size>
<use f='llvm/llvm/unittests/Object/MinidumpTest.cpp' l='350' c='_ZN31MinidumpFile_getModuleList_Test8TestBodyEv'/>
<use f='llvm/llvm/unittests/Object/MinidumpTest.cpp' l='353' c='_ZN31MinidumpFile_getModuleList_Test8TestBodyEv'/>
<size>108</size>
