<dec f='llvm/build/lib/Target/XCore/XCoreGenRegisterInfo.inc' l='21' type='1'/>
<use f='llvm/llvm/lib/Target/XCore/XCoreISelDAGToDAG.cpp' l='120' u='r' c='_ZN12_GLOBAL__N_117XCoreDAGToDAGISel28SelectInlineAsmMemoryOperandERKN4llvm7SDValueEjRSt6vectorIS2_SaIS2_EE'/>
<use f='llvm/llvm/lib/Target/XCore/XCoreRegisterInfo.cpp' l='233' u='r' c='_ZNK4llvm17XCoreRegisterInfo15getReservedRegsERKNS_15MachineFunctionE'/>
