<dec f='llvm/llvm/lib/Target/ARM/Utils/ARMBaseInfo.h' l='31' type='0'/>
<use f='llvm/llvm/lib/Target/ARM/Utils/ARMBaseInfo.h' l='51' c='_ZN4llvm5ARMCCL20getOppositeConditionENS0_9CondCodesE'/>
<use f='llvm/llvm/lib/Target/ARM/Utils/ARMBaseInfo.h' l='52' u='r' c='_ZN4llvm5ARMCCL20getOppositeConditionENS0_9CondCodesE'/>
<use f='llvm/llvm/lib/Target/ARM/Utils/ARMBaseInfo.h' l='74' c='_ZN4llvm5ARMCCL19getSwappedConditionENS0_9CondCodesE'/>
<use f='llvm/llvm/lib/Target/ARM/Utils/ARMBaseInfo.h' l='74' u='r' c='_ZN4llvm5ARMCCL19getSwappedConditionENS0_9CondCodesE'/>
<use f='llvm/llvm/lib/Target/ARM/Utils/ARMBaseInfo.h' l='148' c='_ZN4llvmL19ARMCondCodeToStringENS_5ARMCC9CondCodesE'/>
<use f='llvm/llvm/lib/Target/ARM/Utils/ARMBaseInfo.h' l='169' u='r' c='_ZN4llvmL21ARMCondCodeFromStringENS_9StringRefE'/>
<doc f='llvm/llvm/lib/Target/ARM/Utils/ARMBaseInfo.h' l='31'>// Equal                      Equal</doc>
<use f='llvm/llvm/lib/Target/ARM/MVETailPredUtils.h' l='94' u='r' c='_ZN4llvm20RevertWhileLoopStartEPNS_12MachineInstrEPKNS_15TargetInstrInfoEj'/>
<use f='llvm/llvm/lib/Target/ARM/ARMBaseInstrInfo.cpp' l='624' u='r' c='_ZNK4llvm16ARMBaseInstrInfo17SubsumesPredicateENS_8ArrayRefINS_14MachineOperandEEES3_'/>
<use f='llvm/llvm/lib/Target/ARM/ARMBaseInstrInfo.cpp' l='3156' u='r' c='_ZNK4llvm16ARMBaseInstrInfo20optimizeCompareInstrERNS_12MachineInstrENS_8RegisterES3_iiPKNS_19MachineRegisterInfoE'/>
<use f='llvm/llvm/lib/Target/ARM/ARMBaseInstrInfo.cpp' l='3205' c='_ZNK4llvm16ARMBaseInstrInfo20optimizeCompareInstrERNS_12MachineInstrENS_8RegisterES3_iiPKNS_19MachineRegisterInfoE'/>
<use f='llvm/llvm/lib/Target/ARM/ARMConstantIslandPass.cpp' l='1887' u='r' c='_ZN12_GLOBAL__N_118ARMConstantIslands22optimizeThumb2BranchesEv'/>
<use f='llvm/llvm/lib/Target/ARM/ARMExpandPseudoInsts.cpp' l='1127' u='r' c='_ZN12_GLOBAL__N_115ARMExpandPseudo17CMSEClearFPRegsV8ERN4llvm17MachineBasicBlockENS1_26MachineInstrBundleIteratorINS1_12MachineInstrELb0EEERKNS1_9BitVectorE'/>
<use f='llvm/llvm/lib/Target/ARM/ARMExpandPseudoInsts.cpp' l='1723' u='r' c='_ZN12_GLOBAL__N_115ARMExpandPseudo17ExpandCMP_SWAP_64ERN4llvm17MachineBasicBlockENS1_26MachineInstrBundleIteratorINS1_12MachineInstrELb0EEERS6_'/>
<use f='llvm/llvm/lib/Target/ARM/ARMFastISel.cpp' l='1189' u='r' c='_ZL14getComparePredN4llvm7CmpInst9PredicateE'/>
<use f='llvm/llvm/lib/Target/ARM/ARMFastISel.cpp' l='1274' u='r' c='_ZN12_GLOBAL__N_111ARMFastISel12SelectBranchEPKN4llvm11InstructionE'/>
<use f='llvm/llvm/lib/Target/ARM/ARMFastISel.cpp' l='1312' u='r' c='_ZN12_GLOBAL__N_111ARMFastISel12SelectBranchEPKN4llvm11InstructionE'/>
<use f='llvm/llvm/lib/Target/ARM/ARMFastISel.cpp' l='1673' u='r' c='_ZN12_GLOBAL__N_111ARMFastISel12SelectSelectEPKN4llvm11InstructionE'/>
<use f='llvm/llvm/lib/Target/ARM/ARMISelDAGToDAG.cpp' l='3826' c='_ZN12_GLOBAL__N_115ARMDAGToDAGISel6SelectEPN4llvm6SDNodeE'/>
<use f='llvm/llvm/lib/Target/ARM/ARMISelDAGToDAG.cpp' l='3903' c='_ZN12_GLOBAL__N_115ARMDAGToDAGISel6SelectEPN4llvm6SDNodeE'/>
<use f='llvm/llvm/lib/Target/ARM/ARMISelLowering.cpp' l='1938' u='r' c='_ZL12IntCCToARMCCN4llvm3ISD8CondCodeE'/>
<use f='llvm/llvm/lib/Target/ARM/ARMISelLowering.cpp' l='1957' u='r' c='_ZL11FPCCToARMCCN4llvm3ISD8CondCodeERNS_5ARMCC9CondCodesES4_'/>
<use f='llvm/llvm/lib/Target/ARM/ARMISelLowering.cpp' l='1967' u='r' c='_ZL11FPCCToARMCCN4llvm3ISD8CondCodeERNS_5ARMCC9CondCodesES4_'/>
<use f='llvm/llvm/lib/Target/ARM/ARMISelLowering.cpp' l='4625' c='_ZNK4llvm17ARMTargetLowering9getARMCmpENS_7SDValueES1_NS_3ISD8CondCodeERS1_RNS_12SelectionDAGERKNS_5SDLocE'/>
<use f='llvm/llvm/lib/Target/ARM/ARMISelLowering.cpp' l='4719' u='r' c='_ZNK4llvm17ARMTargetLowering13getARMXALUOOpENS_7SDValueERNS_12SelectionDAGERS1_'/>
<use f='llvm/llvm/lib/Target/ARM/ARMISelLowering.cpp' l='4730' u='r' c='_ZNK4llvm17ARMTargetLowering13getARMXALUOOpENS_7SDValueERNS_12SelectionDAGERS1_'/>
<use f='llvm/llvm/lib/Target/ARM/ARMISelLowering.cpp' l='4972' u='r' c='_ZL20checkVSELConstraintsN4llvm3ISD8CondCodeERNS_5ARMCC9CondCodesERbS5_'/>
<use f='llvm/llvm/lib/Target/ARM/ARMISelLowering.cpp' l='5300' u='r' c='_ZNK4llvm17ARMTargetLowering14LowerSELECT_CCENS_7SDValueERNS_12SelectionDAGE'/>
<use f='llvm/llvm/lib/Target/ARM/ARMISelLowering.cpp' l='6452' u='r' c='_ZL11LowerVSETCCN4llvm7SDValueERNS_12SelectionDAGEPKNS_12ARMSubtargetE'/>
<use f='llvm/llvm/lib/Target/ARM/ARMISelLowering.cpp' l='6500' u='r' c='_ZL11LowerVSETCCN4llvm7SDValueERNS_12SelectionDAGEPKNS_12ARMSubtargetE'/>
<use f='llvm/llvm/lib/Target/ARM/ARMISelLowering.cpp' l='6512' u='r' c='_ZL11LowerVSETCCN4llvm7SDValueERNS_12SelectionDAGEPKNS_12ARMSubtargetE'/>
<use f='llvm/llvm/lib/Target/ARM/ARMISelLowering.cpp' l='10939' u='r' c='_ZNK4llvm17ARMTargetLowering19EmitLowered__dbzchkERNS_12MachineInstrEPNS_17MachineBasicBlockE'/>
<use f='llvm/llvm/lib/Target/ARM/ARMISelLowering.cpp' l='11143' u='r' c='_ZNK4llvm17ARMTargetLowering27EmitInstrWithCustomInserterERNS_12MachineInstrEPNS_17MachineBasicBlockE'/>
<use f='llvm/llvm/lib/Target/ARM/ARMISelLowering.cpp' l='11153' u='r' c='_ZNK4llvm17ARMTargetLowering27EmitInstrWithCustomInserterERNS_12MachineInstrEPNS_17MachineBasicBlockE'/>
<use f='llvm/llvm/lib/Target/ARM/ARMISelLowering.cpp' l='11162' u='r' c='_ZNK4llvm17ARMTargetLowering27EmitInstrWithCustomInserterERNS_12MachineInstrEPNS_17MachineBasicBlockE'/>
<use f='llvm/llvm/lib/Target/ARM/ARMISelLowering.cpp' l='13228' c='_ZL14isValidMVECondjb'/>
<use f='llvm/llvm/lib/Target/ARM/ARMISelLowering.cpp' l='15846' u='r' c='_ZNK4llvm17ARMTargetLowering23PerformCMOVToBFICombineEPNS_6SDNodeERNS_12SelectionDAGE'/>
<use f='llvm/llvm/lib/Target/ARM/ARMISelLowering.cpp' l='16154' u='r' c='_ZNK4llvm17ARMTargetLowering18PerformCMOVCombineEPNS_6SDNodeERNS_12SelectionDAGE'/>
<use f='llvm/llvm/lib/Target/ARM/ARMISelLowering.cpp' l='16181' u='r' c='_ZNK4llvm17ARMTargetLowering18PerformCMOVCombineEPNS_6SDNodeERNS_12SelectionDAGE'/>
<use f='llvm/llvm/lib/Target/ARM/ARMISelLowering.cpp' l='16222' u='r' c='_ZNK4llvm17ARMTargetLowering18PerformCMOVCombineEPNS_6SDNodeERNS_12SelectionDAGE'/>
<use f='llvm/llvm/lib/Target/ARM/ARMInstructionSelector.cpp' l='399' u='a' c='_ZL15getComparePredsN4llvm7CmpInst9PredicateE'/>
<use f='llvm/llvm/lib/Target/ARM/ARMInstructionSelector.cpp' l='403' u='r' c='_ZL15getComparePredsN4llvm7CmpInst9PredicateE'/>
<use f='llvm/llvm/lib/Target/ARM/ARMInstructionSelector.cpp' l='796' u='r' c='_ZNK12_GLOBAL__N_122ARMInstructionSelector12selectSelectERN4llvm19MachineInstrBuilderERNS1_19MachineRegisterInfoE'/>
<use f='llvm/llvm/lib/Target/ARM/AsmParser/ARMAsmParser.cpp' l='2362' u='r' c='_ZNK12_GLOBAL__N_110ARMOperand23isITCondCodeRestrictedIEv'/>
<use f='llvm/llvm/lib/Target/ARM/AsmParser/ARMAsmParser.cpp' l='2384' u='r' c='_ZNK12_GLOBAL__N_110ARMOperand24isITCondCodeRestrictedFPEv'/>
<use f='llvm/llvm/lib/Target/ARM/Disassembler/ARMDisassembler.cpp' l='6227' u='r' c='_ZL33DecodeRestrictedIPredicateOperandRN4llvm6MCInstEjmPKv'/>
<use f='llvm/llvm/lib/Target/ARM/Disassembler/ARMDisassembler.cpp' l='6270' u='r' c='_ZL34DecodeRestrictedFPPredicateOperandRN4llvm6MCInstEjmPKv'/>
<use f='llvm/llvm/lib/Target/ARM/MCTargetDesc/ARMMCCodeEmitter.cpp' l='1962' c='_ZNK12_GLOBAL__N_116ARMMCCodeEmitter28getRestrictedCondCodeOpValueERKN4llvm6MCInstEjRNS1_15SmallVectorImplINS1_7MCFixupEEERKNS1_15MCSubtargetInfoE'/>
