<use f='llvm/llvm/include/llvm/CodeGen/RDFGraph.h' l='664' u='a' c='_ZNK4llvm3rdf13DataFlowGraph6getPRIEv'/>
<dec f='llvm/llvm/include/llvm/CodeGen/RDFGraph.h' l='868' type='const llvm::rdf::PhysicalRegisterInfo'/>
<use f='llvm/llvm/lib/CodeGen/RDFGraph.cpp' l='654' u='w' c='_ZN4llvm3rdf13DataFlowGraphC1ERNS_15MachineFunctionERKNS_15TargetInstrInfoERKNS_18TargetRegisterInfoERKNS_20MachineDominatorTreeERKNS_24MachineDominan10792868'/>
<use f='llvm/llvm/lib/CodeGen/RDFGraph.cpp' l='655' u='r' c='_ZN4llvm3rdf13DataFlowGraphC1ERNS_15MachineFunctionERKNS_15TargetInstrInfoERKNS_18TargetRegisterInfoERKNS_20MachineDominatorTreeERKNS_24MachineDominan10792868'/>
<use f='llvm/llvm/lib/CodeGen/RDFGraph.cpp' l='979' u='m' c='_ZNK4llvm3rdf13DataFlowGraph10makeRegRefERKNS_14MachineOperandE'/>
<use f='llvm/llvm/lib/CodeGen/RDFGraph.cpp' l='989' u='m' c='_ZNK4llvm3rdf13DataFlowGraph11restrictRefENS0_11RegisterRefES2_'/>
<use f='llvm/llvm/lib/CodeGen/RDFGraph.cpp' l='1057' u='m' c='_ZN4llvm3rdf13DataFlowGraph12pushClobbersENS0_8NodeAddrIPNS0_9InstrNodeEEERSt13unordered_mapIjNS1_8DefStackESt4hashIjESt8equal_toIjESaISt4pairIKjS7_EEE'/>
<use f='llvm/llvm/lib/CodeGen/RDFGraph.cpp' l='1112' u='m' c='_ZN4llvm3rdf13DataFlowGraph8pushDefsENS0_8NodeAddrIPNS0_9InstrNodeEEERSt13unordered_mapIjNS1_8DefStackESt4hashIjESt8equal_toIjESaISt4pairIKjS7_EEE'/>
<use f='llvm/llvm/lib/CodeGen/RDFGraph.cpp' l='1272' u='m' c='_ZN4llvm3rdf13DataFlowGraph9buildStmtENS0_8NodeAddrIPNS0_9BlockNodeEEERNS_12MachineInstrE'/>
<use f='llvm/llvm/lib/CodeGen/RDFGraph.cpp' l='1434' u='r' c='_ZN4llvm3rdf13DataFlowGraph9buildPhisERSt3mapIjSt3setINS0_11RegisterRefESt4lessIS4_ESaIS4_EES5_IjESaISt4pairIKjS8_EEERS8_NS0_8NodeAddrIPNS0_9BlockNodeEEE'/>
<use f='llvm/llvm/lib/CodeGen/RDFGraph.cpp' l='1460' u='m' c='_ZN4llvm3rdf13DataFlowGraph9buildPhisERSt3mapIjSt3setINS0_11RegisterRefESt4lessIS4_ESaIS4_EES5_IjESaISt4pairIKjS8_EEERS8_NS0_8NodeAddrIPNS0_9BlockNodeEEE'/>
<use f='llvm/llvm/lib/CodeGen/RDFGraph.cpp' l='1571' u='r' c='_ZN4llvm3rdf13DataFlowGraph9linkRefUpENS0_8NodeAddrIPNS0_9InstrNodeEEENS2_IT_EERNS1_8DefStackE'/>
<offset>192</offset>
