<use f='llvm/llvm/lib/ExecutionEngine/Orc/Core.cpp' l='469' u='w' c='_ZN4llvm3orc21InProgressLookupStateC1ENS0_10LookupKindESt6vectorISt4pairIPNS0_8JITDylibENS0_19JITDylibLookupFlagsEESaIS8_EENS0_15SymbolLookupSetENS0_11SymbolStateE'/>
<dec f='llvm/llvm/lib/ExecutionEngine/Orc/Core.cpp' l='477' type='llvm::orc::LookupKind'/>
<use f='llvm/llvm/lib/ExecutionEngine/Orc/Core.cpp' l='2218' u='r' c='_ZN4llvm3orc16ExecutionSession19OL_applyQueryPhase1ESt10unique_ptrINS0_21InProgressLookupStateESt14default_deleteIS3_EENS_5ErrorE'/>
<offset>64</offset>
