<dec f='llvm/llvm/include/llvm/Analysis/FunctionPropertiesAnalysis.h' l='77' type='llvm::raw_ostream &amp;'/>
<use f='llvm/llvm/include/llvm/Analysis/FunctionPropertiesAnalysis.h' l='80' u='w' c='_ZN4llvm29FunctionPropertiesPrinterPassC1ERNS_11raw_ostreamE'/>
<use f='llvm/llvm/lib/Analysis/FunctionPropertiesAnalysis.cpp' l='83' u='m' c='_ZN4llvm29FunctionPropertiesPrinterPass3runERNS_8FunctionERNS_15AnalysisManagerIS1_JEEE'/>
<use f='llvm/llvm/lib/Analysis/FunctionPropertiesAnalysis.cpp' l='86' u='a' c='_ZN4llvm29FunctionPropertiesPrinterPass3runERNS_8FunctionERNS_15AnalysisManagerIS1_JEEE'/>
<offset>0</offset>
