<dec f='llvm/llvm/include/llvm/DebugInfo/CodeView/SymbolRecord.h' l='402' type='uint16_t'/>
<use f='llvm/llvm/include/llvm/DebugInfo/CodeView/SymbolRecord.h' l='405' u='r' c='_ZNK4llvm8codeview10ProcRefSym4modiEv'/>
<offset>96</offset>
<use f='llvm/lld/COFF/PDB.cpp' l='517' u='w' c='_ZL15addGlobalSymbolRN4llvm3pdb16GSIStreamBuilderEtjRSt6vectorIhSaIhEE'/>
<use f='llvm/lld/COFF/PDB.cpp' l='519' u='w' c='_ZL15addGlobalSymbolRN4llvm3pdb16GSIStreamBuilderEtjRSt6vectorIhSaIhEE'/>
<use f='llvm/lldb/source/Plugins/SymbolFile/NativePDB/PdbUtil.h' l='126' u='r' c='_ZN12lldb_private4npdb13IsValidRecordERKN4llvm8codeview10ProcRefSymE'/>
<use f='llvm/llvm/lib/DebugInfo/CodeView/SymbolDumper.cpp' l='526' u='r' c='_ZN12_GLOBAL__N_118CVSymbolDumperImpl16visitKnownRecordERN4llvm8codeview8CVRecordINS2_10SymbolKindEEERNS2_10ProcRefSymE'/>
<use f='llvm/llvm/lib/DebugInfo/CodeView/SymbolRecordMapping.cpp' l='376' u='a' c='_ZN4llvm8codeview19SymbolRecordMapping16visitKnownRecordERNS0_8CVRecordINS0_10SymbolKindEEERNS0_10ProcRefSymE'/>
<use f='llvm/llvm/lib/ObjectYAML/CodeViewYAMLSymbols.cpp' l='374' u='a' c='_ZN4llvm12CodeViewYAML6detail16SymbolRecordImpl3mapERNS_4yaml2IOE'/>
<use f='llvm/llvm/tools/llvm-pdbutil/MinimalSymbolDumper.cpp' l='793' u='a' c='_ZN4llvm3pdb19MinimalSymbolDumper16visitKnownRecordERNS_8codeview8CVRecordINS2_10SymbolKindEEERNS2_10ProcRefSymE'/>
