<dec f='llvm/llvm/tools/llvm-xray/xray-graph.h' l='61' type='llvm::xray::GraphRenderer::TimeStat'/>
<use f='llvm/llvm/tools/llvm-xray/xray-graph-diff.cpp' l='262' u='r' c='_ZL8getColorB5cxx11RKN4llvm6detail12DenseMapPairISt4pairINS_9StringRefES3_ENS_4xray17GraphDiffRenderer13EdgeAttributeEEERKNS5_5GraphINS6_15VertexAttri13655128'/>
<use f='llvm/llvm/tools/llvm-xray/xray-graph-diff.cpp' l='263' u='r' c='_ZL8getColorB5cxx11RKN4llvm6detail12DenseMapPairISt4pairINS_9StringRefES3_ENS_4xray17GraphDiffRenderer13EdgeAttributeEEERKNS5_5GraphINS6_15VertexAttri13655128'/>
<use f='llvm/llvm/tools/llvm-xray/xray-graph-diff.cpp' l='313' u='r' c='_ZL8getLabelB5cxx11RKN4llvm6detail12DenseMapPairISt4pairINS_9StringRefES3_ENS_4xray17GraphDiffRenderer13EdgeAttributeEEENS5_13GraphRenderer8StatTypeE'/>
<use f='llvm/llvm/tools/llvm-xray/xray-graph-diff.cpp' l='314' u='r' c='_ZL8getLabelB5cxx11RKN4llvm6detail12DenseMapPairISt4pairINS_9StringRefES3_ENS_4xray17GraphDiffRenderer13EdgeAttributeEEENS5_13GraphRenderer8StatTypeE'/>
<use f='llvm/llvm/tools/llvm-xray/xray-graph-diff.cpp' l='353' u='r' c='_ZL12getLineWidthRKN4llvm6detail12DenseMapPairISt4pairINS_9StringRefES3_ENS_4xray17GraphDiffRenderer13EdgeAttributeEEENS5_13GraphRenderer8StatTypeE'/>
<use f='llvm/llvm/tools/llvm-xray/xray-graph-diff.cpp' l='354' u='r' c='_ZL12getLineWidthRKN4llvm6detail12DenseMapPairISt4pairINS_9StringRefES3_ENS_4xray17GraphDiffRenderer13EdgeAttributeEEENS5_13GraphRenderer8StatTypeE'/>
<offset>0</offset>
<use f='llvm/llvm/tools/llvm-xray/xray-graph.cpp' l='251' u='a' c='_ZN4llvm4xray13GraphRenderer13accountRecordERKNS0_10XRayRecordE'/>
<use f='llvm/llvm/tools/llvm-xray/xray-graph.cpp' l='261' u='a' c='_ZN4llvm4xray13GraphRenderer13accountRecordERKNS0_10XRayRecordE'/>
<use f='llvm/llvm/tools/llvm-xray/xray-graph.cpp' l='304' u='a' c='_ZN4llvm4xray13GraphRenderer23calculateEdgeStatisticsEv'/>
<use f='llvm/llvm/tools/llvm-xray/xray-graph.cpp' l='305' u='r' c='_ZN4llvm4xray13GraphRenderer23calculateEdgeStatisticsEv'/>
<use f='llvm/llvm/tools/llvm-xray/xray-graph.cpp' l='336' u='a' c='_ZN4llvm4xray13GraphRenderer19normalizeStatisticsEd'/>
<use f='llvm/llvm/tools/llvm-xray/xray-graph.cpp' l='408' u='r' c='_ZN4llvm4xray13GraphRenderer16exportGraphAsDOTERNS_11raw_ostreamENS1_8StatTypeES4_S4_S4_'/>
