<dec f='llvm/llvm/include/llvm/ExecutionEngine/Orc/Layer.h' l='128' type='llvm::orc::IRLayer &amp;'/>
<offset>896</offset>
<use f='llvm/llvm/lib/ExecutionEngine/Orc/Layer.cpp' l='131' u='w' c='_ZN4llvm3orc31BasicIRLayerMaterializationUnitC1ERNS0_7IRLayerERKNS0_14IRSymbolMapper15ManglingOptionsENS0_16ThreadSafeModuleE'/>
<use f='llvm/llvm/lib/ExecutionEngine/Orc/Layer.cpp' l='142' u='m' c='_ZN4llvm3orc31BasicIRLayerMaterializationUnit11materializeESt10unique_ptrINS0_29MaterializationResponsibilityESt14default_deleteIS3_EE'/>
<use f='llvm/llvm/lib/ExecutionEngine/Orc/Layer.cpp' l='152' u='m' c='_ZN4llvm3orc31BasicIRLayerMaterializationUnit11materializeESt10unique_ptrINS0_29MaterializationResponsibilityESt14default_deleteIS3_EE'/>
