<use f='llvm/llvm/include/llvm/LTO/LTO.h' l='194' u='w' c='_ZN4llvm3lto18NativeObjectStreamC1ESt10unique_ptrINS_17raw_pwrite_streamESt14default_deleteIS3_EE'/>
<dec f='llvm/llvm/include/llvm/LTO/LTO.h' l='195' type='std::unique_ptr&lt;raw_pwrite_stream&gt;'/>
<offset>64</offset>
<use f='llvm/llvm/lib/LTO/Caching.cpp' l='88' u='m' c='_ZZZN4llvm3lto10localCacheENS_9StringRefESt8functionIFvjSt10unique_ptrINS_12MemoryBufferESt14default_deleteIS4_EEEEENK3$_0clEjS1_EN11CacheStreamD1Ev'/>
<use f='llvm/llvm/lib/LTO/LTOBackend.cpp' l='447' u='m' c='_ZL7codegenRKN4llvm3lto6ConfigEPNS_13TargetMachineESt8functionIFSt10unique_ptrINS0_18NativeObjectStreamESt14default_deleteIS8_EEjEEjRNS_6ModuleERKNS_18ModuleSummaryIndexE'/>
<use f='llvm/llvm/tools/llvm-lto2/llvm-lto2.cpp' l='376' u='m' c='_ZL3runiPPc'/>
