<dec f='llvm/llvm/lib/Target/X86/ImmutableGraph.h' l='200' type='const ImmutableGraph&lt;NodeValueT, EdgeValueT&gt; &amp;'/>
<use f='llvm/llvm/lib/Target/X86/ImmutableGraph.h' l='205' u='w' c='_ZN4llvm14ImmutableGraph7EdgeSetC1ERKNS_14ImmutableGraphIT_T0_EEb'/>
<use f='llvm/llvm/lib/Target/X86/ImmutableGraph.h' l='207' u='c' c='_ZN4llvm14ImmutableGraph7EdgeSet6insertERKNS0_4EdgeE'/>
<use f='llvm/llvm/lib/Target/X86/ImmutableGraph.h' l='213' u='c' c='_ZN4llvm14ImmutableGraph7EdgeSet5eraseERKNS0_4EdgeE'/>
<use f='llvm/llvm/lib/Target/X86/ImmutableGraph.h' l='217' u='c' c='_ZNK4llvm14ImmutableGraph7EdgeSet8containsERKNS0_4EdgeE'/>
