<use f='llvm/llvm/include/llvm/Analysis/VectorUtils.h' l='590' u='w' c='_ZN4llvm15InterleaveGroupC1EjbNS_5AlignE'/>
<use f='llvm/llvm/include/llvm/Analysis/VectorUtils.h' l='595' u='w' c='_ZN4llvm15InterleaveGroupC1EPT_iNS_5AlignE'/>
<use f='llvm/llvm/include/llvm/Analysis/VectorUtils.h' l='603' u='r' c='_ZNK4llvm15InterleaveGroup9getFactorEv'/>
<use f='llvm/llvm/include/llvm/Analysis/VectorUtils.h' l='634' u='r' c='_ZN4llvm15InterleaveGroup12insertMemberEPT_iNS_5AlignE'/>
<use f='llvm/llvm/include/llvm/Analysis/VectorUtils.h' l='646' u='r' c='_ZN4llvm15InterleaveGroup12insertMemberEPT_iNS_5AlignE'/>
<dec f='llvm/llvm/include/llvm/Analysis/VectorUtils.h' l='706' type='uint32_t'/>
<doc f='llvm/llvm/include/llvm/Analysis/VectorUtils.h' l='706'>// Interleave Factor.</doc>
