<dec f='llvm/llvm/include/llvm/TableGen/Record.h' l='1984' type='llvm::Init *'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='1987' u='w' c='_ZN4llvm11MapResolver11MappedValueC1Ev'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='1988' u='w' c='_ZN4llvm11MapResolver11MappedValueC1EPNS_4InitEb'/>
<offset>0</offset>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='2675' u='r' c='_ZN4llvm11MapResolver7resolveEPNS_4InitE'/>
