<dec f='llvm/llvm/include/llvm/IR/Instructions.h' l='720' type='2'/>
<doc f='llvm/llvm/include/llvm/IR/Instructions.h' l='719'>/// *p = old - v</doc>
<use f='llvm/clang/lib/CodeGen/CGAtomic.cpp' l='619' u='r' c='_ZL12EmitAtomicOpRN5clang7CodeGen15CodeGenFunctionEPNS_10AtomicExprENS0_7AddressES5_S5_S5_PN4llvm5ValueES8_mNS6_14AtomicOrderingEh'/>
<use f='llvm/clang/lib/CodeGen/CGBuiltin.cpp' l='399' u='r' c='_ZL24EmitAtomicDecrementValueRN5clang7CodeGen15CodeGenFunctionEPKNS_8CallExprEN4llvm14AtomicOrderingE'/>
<use f='llvm/clang/lib/CodeGen/CGBuiltin.cpp' l='1481' u='r' c='_ZN5clang7CodeGen15CodeGenFunction19EmitMSVCBuiltinExprENS1_10MSVCIntrinEPKNS_8CallExprE'/>
<use f='llvm/clang/lib/CodeGen/CGBuiltin.cpp' l='3566' u='r' c='_ZN5clang7CodeGen15CodeGenFunction15EmitBuiltinExprENS_10GlobalDeclEjPKNS_8CallExprENS0_15ReturnValueSlotE'/>
<use f='llvm/clang/lib/CodeGen/CGBuiltin.cpp' l='3614' u='r' c='_ZN5clang7CodeGen15CodeGenFunction15EmitBuiltinExprENS_10GlobalDeclEjPKNS_8CallExprENS0_15ReturnValueSlotE'/>
<use f='llvm/clang/lib/CodeGen/CGBuiltin.cpp' l='16151' u='r' c='_ZN5clang7CodeGen15CodeGenFunction20EmitNVPTXBuiltinExprEjPKNS_8CallExprE'/>
<use f='llvm/clang/lib/CodeGen/CGExprScalar.cpp' l='2445' u='r' c='_ZN12_GLOBAL__N_117ScalarExprEmitter23EmitScalarPrePostIncDecEPKN5clang13UnaryOperatorENS1_7CodeGen6LValueEbb'/>
<use f='llvm/clang/lib/CodeGen/CGExprScalar.cpp' l='2999' u='r' c='_ZN12_GLOBAL__N_117ScalarExprEmitter24EmitCompoundAssignLValueEPKN5clang22CompoundAssignOperatorEMS0_FPN4llvm5ValueERKNS_9BinOpInfoEERS7_'/>
<use f='llvm/clang/lib/CodeGen/CGStmtOpenMP.cpp' l='5053' u='r' c='_ZL16emitOMPAtomicRMWRN5clang7CodeGen15CodeGenFunctionENS0_6LValueENS0_6RValueENS_18BinaryOperatorKindEN4llvm14AtomicOrderingEb'/>
<use f='llvm/llvm/lib/AsmParser/LLParser.cpp' l='7511' u='r' c='_ZN4llvm8LLParser14parseAtomicRMWERPNS_11InstructionERNS0_16PerFunctionStateE'/>
<use f='llvm/llvm/lib/Bitcode/Reader/BitcodeReader.cpp' l='1121' u='r' c='_ZL22getDecodedRMWOperationj'/>
<use f='llvm/llvm/lib/Bitcode/Writer/BitcodeWriter.cpp' l='567' c='_ZL22getEncodedRMWOperationN4llvm13AtomicRMWInst5BinOpE'/>
<use f='llvm/llvm/lib/CodeGen/AtomicExpandPass.cpp' l='502' c='_ZL15performAtomicOpN4llvm13AtomicRMWInst5BinOpERNS_9IRBuilderINS_14ConstantFolderENS_24IRBuilderDefaultInserterEEEPNS_5ValueES8_'/>
<use f='llvm/llvm/lib/CodeGen/AtomicExpandPass.cpp' l='727' c='_ZL21performMaskedAtomicOpN4llvm13AtomicRMWInst5BinOpERNS_9IRBuilderINS_14ConstantFolderENS_24IRBuilderDefaultInserterEEEPNS_5ValueES8_S8_RKN12_GLOBAL2516351'/>
<use f='llvm/llvm/lib/CodeGen/AtomicExpandPass.cpp' l='1361' c='_ZN12_GLOBAL__N_112AtomicExpand15isIdempotentRMWEPN4llvm13AtomicRMWInstE'/>
<use f='llvm/llvm/lib/CodeGen/AtomicExpandPass.cpp' l='1579' c='_ZL13GetRMWLibcallN4llvm13AtomicRMWInst5BinOpE'/>
<use f='llvm/llvm/lib/CodeGen/GlobalISel/IRTranslator.cpp' l='2742' c='_ZN4llvm12IRTranslator18translateAtomicRMWERKNS_4UserERNS_16MachineIRBuilderE'/>
<use f='llvm/llvm/lib/CodeGen/SelectionDAG/SelectionDAGBuilder.cpp' l='4500' c='_ZN4llvm19SelectionDAGBuilder14visitAtomicRMWERKNS_13AtomicRMWInstE'/>
<use f='llvm/llvm/lib/IR/Core.cpp' l='3579' u='r' c='_ZL19mapFromLLVMRMWBinOp18LLVMAtomicRMWBinOp'/>
<use f='llvm/llvm/lib/IR/Core.cpp' l='3599' c='_ZL17mapToLLVMRMWBinOpN4llvm13AtomicRMWInst5BinOpE'/>
<use f='llvm/llvm/lib/IR/Instructions.cpp' l='1614' c='_ZN4llvm13AtomicRMWInst16getOperationNameENS0_5BinOpE'/>
<use f='llvm/llvm/lib/Target/AMDGPU/AMDGPUAtomicOptimizer.cpp' l='124' c='_ZN12_GLOBAL__N_121AMDGPUAtomicOptimizer18visitAtomicRMWInstERN4llvm13AtomicRMWInstE'/>
<use f='llvm/llvm/lib/Target/AMDGPU/AMDGPUAtomicOptimizer.cpp' l='177' u='r' c='_ZN12_GLOBAL__N_121AMDGPUAtomicOptimizer18visitIntrinsicInstERN4llvm13IntrinsicInstE'/>
<use f='llvm/llvm/lib/Target/AMDGPU/AMDGPUAtomicOptimizer.cpp' l='256' c='_ZL19buildNonAtomicBinOpRN4llvm9IRBuilderINS_14ConstantFolderENS_24IRBuilderDefaultInserterEEENS_13AtomicRMWInst5BinOpEPNS_5ValueES8_'/>
<use f='llvm/llvm/lib/Target/AMDGPU/AMDGPUAtomicOptimizer.cpp' l='393' c='_ZL27getIdentityValueForAtomicOpN4llvm13AtomicRMWInst5BinOpEj'/>
<use f='llvm/llvm/lib/Target/AMDGPU/AMDGPUAtomicOptimizer.cpp' l='491' u='r' c='_ZNK12_GLOBAL__N_121AMDGPUAtomicOptimizer14optimizeAtomicERN4llvm11InstructionENS1_13AtomicRMWInst5BinOpEjb'/>
<use f='llvm/llvm/lib/Target/AMDGPU/AMDGPUAtomicOptimizer.cpp' l='527' c='_ZNK12_GLOBAL__N_121AMDGPUAtomicOptimizer14optimizeAtomicERN4llvm11InstructionENS1_13AtomicRMWInst5BinOpEjb'/>
<use f='llvm/llvm/lib/Target/AMDGPU/AMDGPUAtomicOptimizer.cpp' l='630' c='_ZNK12_GLOBAL__N_121AMDGPUAtomicOptimizer14optimizeAtomicERN4llvm11InstructionENS1_13AtomicRMWInst5BinOpEjb'/>
<use f='llvm/llvm/lib/Target/RISCV/RISCVExpandAtomicPseudoInsts.cpp' l='105' u='r' c='_ZN12_GLOBAL__N_123RISCVExpandAtomicPseudo8expandMIERN4llvm17MachineBasicBlockENS1_26MachineInstrBundleIteratorINS1_12MachineInstrELb0EEERS6_'/>
<use f='llvm/llvm/lib/Target/RISCV/RISCVExpandAtomicPseudoInsts.cpp' l='314' c='_ZN12_GLOBAL__N_128doMaskedAtomicBinOpExpansionEPKN4llvm14RISCVInstrInfoERNS0_12MachineInstrENS0_8DebugLocEPNS0_17MachineBasicBlockES8_S8_NS0_13AtomicRMWInst5BinOpEi'/>
<use f='llvm/llvm/lib/Target/RISCV/RISCVISelLowering.cpp' l='4353' c='_ZL35getIntrinsicForMaskedAtomicRMWBinOpjN4llvm13AtomicRMWInst5BinOpE'/>
<use f='llvm/llvm/lib/Target/RISCV/RISCVISelLowering.cpp' l='4376' c='_ZL35getIntrinsicForMaskedAtomicRMWBinOpjN4llvm13AtomicRMWInst5BinOpE'/>
<use f='llvm/llvm/lib/Target/WebAssembly/WebAssemblyISelLowering.cpp' l='296' c='_ZNK4llvm25WebAssemblyTargetLowering25shouldExpandAtomicRMWInIREPNS_13AtomicRMWInstE'/>
<use f='llvm/llvm/lib/Target/X86/X86ISelLowering.cpp' l='28693' c='_ZNK4llvm17X86TargetLowering25shouldExpandAtomicRMWInIREPNS_13AtomicRMWInstE'/>
<use f='llvm/llvm/lib/Transforms/InstCombine/InstCombineAtomicRMW.cpp' l='42' c='_ZN12_GLOBAL__N_115isIdempotentRMWERN4llvm13AtomicRMWInstE'/>
<use f='llvm/llvm/lib/Transforms/Instrumentation/ThreadSanitizer.cpp' l='329' u='r' c='_ZN12_GLOBAL__N_115ThreadSanitizer10initializeERN4llvm6ModuleE'/>
<use f='llvm/llvm/lib/Transforms/Scalar/LowerAtomic.cpp' l='59' c='_ZL18LowerAtomicRMWInstPN4llvm13AtomicRMWInstE'/>
