<use f='llvm/llvm/include/llvm/Transforms/IPO/WholeProgramDevirt.h' l='124' u='w' c='_ZN4llvm18wholeprogramdevirt17VirtualCallTargetC1EPKNS0_14TypeMemberInfoEb'/>
<dec f='llvm/llvm/include/llvm/Transforms/IPO/WholeProgramDevirt.h' l='131' type='const llvm::wholeprogramdevirt::TypeMemberInfo *'/>
<use f='llvm/llvm/include/llvm/Transforms/IPO/WholeProgramDevirt.h' l='147' u='r' c='_ZNK4llvm18wholeprogramdevirt17VirtualCallTarget14minBeforeBytesEv'/>
<use f='llvm/llvm/include/llvm/Transforms/IPO/WholeProgramDevirt.h' l='154' u='r' c='_ZNK4llvm18wholeprogramdevirt17VirtualCallTarget13minAfterBytesEv'/>
<use f='llvm/llvm/include/llvm/Transforms/IPO/WholeProgramDevirt.h' l='154' u='r' c='_ZNK4llvm18wholeprogramdevirt17VirtualCallTarget13minAfterBytesEv'/>
<use f='llvm/llvm/include/llvm/Transforms/IPO/WholeProgramDevirt.h' l='159' u='r' c='_ZNK4llvm18wholeprogramdevirt17VirtualCallTarget20allocatedBeforeBytesEv'/>
<use f='llvm/llvm/include/llvm/Transforms/IPO/WholeProgramDevirt.h' l='165' u='r' c='_ZNK4llvm18wholeprogramdevirt17VirtualCallTarget19allocatedAfterBytesEv'/>
<use f='llvm/llvm/include/llvm/Transforms/IPO/WholeProgramDevirt.h' l='171' u='r' c='_ZN4llvm18wholeprogramdevirt17VirtualCallTarget12setBeforeBitEm'/>
<use f='llvm/llvm/include/llvm/Transforms/IPO/WholeProgramDevirt.h' l='177' u='r' c='_ZN4llvm18wholeprogramdevirt17VirtualCallTarget11setAfterBitEm'/>
<use f='llvm/llvm/include/llvm/Transforms/IPO/WholeProgramDevirt.h' l='186' u='r' c='_ZN4llvm18wholeprogramdevirt17VirtualCallTarget14setBeforeBytesEmh'/>
<use f='llvm/llvm/include/llvm/Transforms/IPO/WholeProgramDevirt.h' l='188' u='r' c='_ZN4llvm18wholeprogramdevirt17VirtualCallTarget14setBeforeBytesEmh'/>
<use f='llvm/llvm/include/llvm/Transforms/IPO/WholeProgramDevirt.h' l='195' u='r' c='_ZN4llvm18wholeprogramdevirt17VirtualCallTarget13setAfterBytesEmh'/>
<use f='llvm/llvm/include/llvm/Transforms/IPO/WholeProgramDevirt.h' l='197' u='r' c='_ZN4llvm18wholeprogramdevirt17VirtualCallTarget13setAfterBytesEmh'/>
<offset>64</offset>
<doc f='llvm/llvm/include/llvm/Transforms/IPO/WholeProgramDevirt.h' l='129'>// A pointer to the type identifier member through which the pointer to Fn is
  // accessed.</doc>
<use f='llvm/llvm/lib/Transforms/IPO/WholeProgramDevirt.cpp' l='219' u='r' c='_ZN4llvm18wholeprogramdevirt16findLowestOffsetENS_8ArrayRefINS0_17VirtualCallTargetEEEbm'/>
<use f='llvm/llvm/lib/Transforms/IPO/WholeProgramDevirt.cpp' l='220' u='r' c='_ZN4llvm18wholeprogramdevirt16findLowestOffsetENS_8ArrayRefINS0_17VirtualCallTargetEEEbm'/>
<use f='llvm/llvm/lib/Transforms/IPO/WholeProgramDevirt.cpp' l='294' u='w' c='_ZN4llvm18wholeprogramdevirt17VirtualCallTargetC1EPNS_8FunctionEPKNS0_14TypeMemberInfoE'/>
<use f='llvm/llvm/lib/Transforms/IPO/WholeProgramDevirt.cpp' l='1240' u='r' c='_ZN12_GLOBAL__N_112DevirtModule20tryICallBranchFunnelEN4llvm15MutableArrayRefINS1_18wholeprogramdevirt17VirtualCallTargetEEERNS_14VTableSlotInfoEPNS1_6390897'/>
<use f='llvm/llvm/lib/Transforms/IPO/WholeProgramDevirt.cpp' l='1499' u='r' c='_ZN12_GLOBAL__N_112DevirtModule18tryUniqueRetValOptEjN4llvm15MutableArrayRefINS1_18wholeprogramdevirt17VirtualCallTargetEEERNS_12CallSiteInfoEPNS1_28W5872698'/>
