<dec f='llvm/llvm/include/llvm/XRay/Graph.h' l='142' type='llvm::xray::Graph::NeighborEdgeIteratorT::InternalEdgeMapT *'/>
<use f='llvm/llvm/include/llvm/XRay/Graph.h' l='151' u='r' c='_ZNK4llvm4xray5Graph21NeighborEdgeIteratorTcvNS1_21NeighborEdgeIteratorTIXTL1__EXTL0_0_ETL0_1_KNS_6detail12DenseMapPairISt4pairIT1_S8_ET0_EEEEEv'/>
<use f='llvm/llvm/include/llvm/XRay/Graph.h' l='160' u='w' c='_ZN4llvm4xray5Graph21NeighborEdgeIteratorTC1ETL0_1_PNSt11conditionalIXTL0__EKNS_8DenseMapISt4pairIT1_S7_ET0_NS_12DenseMapInfoIS8_EENS_6detail12DenseMa15283413'/>
<use f='llvm/llvm/include/llvm/XRay/Graph.h' l='164' u='c' c='_ZNK4llvm4xray5Graph21NeighborEdgeIteratorTdeEv'/>
<use f='llvm/llvm/include/llvm/XRay/Graph.h' l='166' u='c' c='_ZNK4llvm4xray5Graph21NeighborEdgeIteratorTdeEv'/>
