<dec f='llvm/llvm/include/llvm/CodeGen/TargetRegisterInfo.h' l='53' type='const llvm::MCRegisterClass *'/>
<use f='llvm/llvm/include/llvm/CodeGen/TargetRegisterInfo.h' l='69' u='r' c='_ZNK4llvm19TargetRegisterClass5getIDEv'/>
<use f='llvm/llvm/include/llvm/CodeGen/TargetRegisterInfo.h' l='73' u='r' c='_ZNK4llvm19TargetRegisterClass5beginEv'/>
<use f='llvm/llvm/include/llvm/CodeGen/TargetRegisterInfo.h' l='74' u='r' c='_ZNK4llvm19TargetRegisterClass3endEv'/>
<use f='llvm/llvm/include/llvm/CodeGen/TargetRegisterInfo.h' l='77' u='r' c='_ZNK4llvm19TargetRegisterClass10getNumRegsEv'/>
<use f='llvm/llvm/include/llvm/CodeGen/TargetRegisterInfo.h' l='81' u='r' c='_ZNK4llvm19TargetRegisterClass12getRegistersEv'/>
<use f='llvm/llvm/include/llvm/CodeGen/TargetRegisterInfo.h' l='81' u='r' c='_ZNK4llvm19TargetRegisterClass12getRegistersEv'/>
<use f='llvm/llvm/include/llvm/CodeGen/TargetRegisterInfo.h' l='86' u='r' c='_ZNK4llvm19TargetRegisterClass11getRegisterEj'/>
<use f='llvm/llvm/include/llvm/CodeGen/TargetRegisterInfo.h' l='96' u='r' c='_ZNK4llvm19TargetRegisterClass8containsENS_8RegisterE'/>
<use f='llvm/llvm/include/llvm/CodeGen/TargetRegisterInfo.h' l='105' u='r' c='_ZNK4llvm19TargetRegisterClass8containsENS_8RegisterES1_'/>
<use f='llvm/llvm/include/llvm/CodeGen/TargetRegisterInfo.h' l='111' u='r' c='_ZNK4llvm19TargetRegisterClass11getCopyCostEv'/>
<use f='llvm/llvm/include/llvm/CodeGen/TargetRegisterInfo.h' l='115' u='r' c='_ZNK4llvm19TargetRegisterClass13isAllocatableEv'/>
<use f='llvm/llvm/include/llvm/CodeGen/TargetRegisterInfo.h' l='548' u='r' c='_ZNK4llvm18TargetRegisterInfo19getMatchingSuperRegENS_10MCRegisterEjPKNS_19TargetRegisterClassE'/>
<use f='llvm/llvm/include/llvm/CodeGen/TargetRegisterInfo.h' l='708' u='r' c='_ZNK4llvm18TargetRegisterInfo15getRegClassNameEPKNS_19TargetRegisterClassE'/>
<offset>0</offset>
<doc f='llvm/llvm/include/llvm/CodeGen/TargetRegisterInfo.h' l='52'>// Instance variables filled by tablegen, do not use!</doc>
<use f='llvm/llvm/lib/Target/AArch64/AArch64RegisterInfo.cpp' l='337' u='r' c='_ZNK4llvm19AArch64RegisterInfo19isAnyArgRegReservedERKNS_15MachineFunctionE'/>
<use f='llvm/llvm/lib/Target/AMDGPU/SIRegisterInfo.cpp' l='2013' u='r' c='_ZNK4llvm14SIRegisterInfo16getRegSplitPartsEPKNS_19TargetRegisterClassEj'/>
