<dec f='llvm/llvm/include/llvm/DebugInfo/CodeView/CodeView.h' l='157' type='13'/>
<use f='llvm/llvm/lib/CodeGen/AsmPrinter/CodeViewDebug.cpp' l='738' u='r' c='_ZL17MapDWLangToCVLangj'/>
<use f='llvm/llvm/lib/DebugInfo/CodeView/EnumTables.cpp' l='104'/>
<use f='llvm/llvm/lib/DebugInfo/PDB/PDBExtras.cpp' l='228' c='_ZN4llvm3pdblsERNS_11raw_ostreamERKNS_8codeview14SourceLanguageE'/>
<use f='llvm/llvm/tools/llvm-pdbutil/MinimalSymbolDumper.cpp' l='204' c='_ZL20formatSourceLanguageB5cxx11N4llvm8codeview14SourceLanguageE'/>
