<dec f='llvm/llvm/include/llvm/Support/raw_ostream.h' l='108' type='const llvm::raw_ostream::Colors'/>
<use f='llvm/clang/include/clang/AST/ASTDumperUtils.h' l='66'/>
<use f='llvm/clang/include/clang/AST/ASTDumperUtils.h' l='76'/>
<use f='llvm/clang/lib/Frontend/TextDiagnostic.cpp' l='38' u='r'/>
<use f='llvm/clang/lib/Frontend/TextDiagnostic.cpp' l='39' u='r'/>
<use f='llvm/llvm/lib/Support/WithColor.cpp' l='42' u='r' c='_ZN4llvm9WithColorC1ERNS_11raw_ostreamENS_14HighlightColorENS_9ColorModeE'/>
<use f='llvm/llvm/lib/Support/WithColor.cpp' l='45' u='r' c='_ZN4llvm9WithColorC1ERNS_11raw_ostreamENS_14HighlightColorENS_9ColorModeE'/>
<def f='llvm/llvm/lib/Support/raw_ostream.cpp' l='67' type='const raw_ostream::Colors'/>
<use f='llvm/llvm/tools/llvm-cov/CodeCoverage.cpp' l='187' u='r' c='_ZN12_GLOBAL__N_116CodeCoverageTool5errorERKN4llvm5TwineENS1_9StringRefE'/>
<use f='llvm/llvm/tools/llvm-cov/CodeCoverage.cpp' l='193' u='r' c='_ZN12_GLOBAL__N_116CodeCoverageTool7warningERKN4llvm5TwineENS1_9StringRefE'/>
<use f='llvm/llvm/tools/llvm-cov/CoverageReport.cpp' l='118' u='r' c='_ZN12_GLOBAL__N_132determineCoveragePercentageColorERKT_'/>
<use f='llvm/llvm/tools/llvm-cov/SourceCoverageViewText.cpp' l='111' u='r' c='_ZN4llvm22SourceCoverageViewText10renderLineERNS_11raw_ostreamENS_18SourceCoverageView7LineRefERKNS_8coverage17LineCoverageStatsEjj'/>
<use f='llvm/llvm/tools/llvm-cov/SourceCoverageViewText.cpp' l='124' u='r' c='_ZN4llvm22SourceCoverageViewText10renderLineERNS_11raw_ostreamENS_18SourceCoverageView7LineRefERKNS_8coverage17LineCoverageStatsEjj'/>
<use f='llvm/llvm/tools/llvm-cov/SourceCoverageViewText.cpp' l='126' u='r' c='_ZN4llvm22SourceCoverageViewText10renderLineERNS_11raw_ostreamENS_18SourceCoverageView7LineRefERKNS_8coverage17LineCoverageStatsEjj'/>
<use f='llvm/llvm/tools/llvm-cov/SourceCoverageViewText.cpp' l='250' u='r' c='_ZN4llvm22SourceCoverageViewText16renderBranchViewERNS_11raw_ostreamERNS_10BranchViewEj'/>
<use f='llvm/llvm/tools/llvm-cov/SourceCoverageViewText.cpp' l='260' u='r' c='_ZN4llvm22SourceCoverageViewText16renderBranchViewERNS_11raw_ostreamERNS_10BranchViewEj'/>
<use f='llvm/llvm/tools/llvm-cov/SourceCoverageViewText.cpp' l='279' u='r' c='_ZN4llvm22SourceCoverageViewText23renderInstantiationViewERNS_11raw_ostreamERNS_17InstantiationViewEj'/>
<use f='llvm/llvm/tools/llvm-cov/llvm-cov.cpp' l='88' u='r' c='main'/>
<use f='llvm/llvm/tools/llvm-mca/Views/SchedulerStatistics.cpp' l='161' u='r' c='_ZNK4llvm3mca19SchedulerStatistics19printSchedulerUsageERNS_11raw_ostreamE'/>
<use f='llvm/llvm/tools/llvm-mca/Views/TimelineView.cpp' l='113' u='r' c='_ZN4llvm3mcaL11chooseColorEjji'/>
<use f='llvm/llvm/tools/llvm-pdbutil/LinePrinter.cpp' l='327' u='r' c='_ZN4llvm3pdb9WithColor10applyColorENS0_13PDB_ColorItemE'/>
<use f='llvm/llvm/utils/FileCheck/FileCheck.cpp' l='207' u='r' c='_ZL9GetMarkerN4llvm13FileCheckDiag9MatchTypeE'/>
<use f='llvm/llvm/utils/FileCheck/FileCheck.cpp' l='210' u='r' c='_ZL9GetMarkerN4llvm13FileCheckDiag9MatchTypeE'/>
<use f='llvm/llvm/utils/FileCheck/FileCheck.cpp' l='218' u='r' c='_ZL9GetMarkerN4llvm13FileCheckDiag9MatchTypeE'/>
<use f='llvm/llvm/utils/FileCheck/FileCheck.cpp' l='297' u='r' c='_ZL23DumpInputAnnotationHelpRN4llvm11raw_ostreamE'/>
