<dec f='llvm/llvm/include/llvm/IR/ValueMap.h' l='334' type='llvm::ValueMapIterator::BaseT'/>
<use f='llvm/llvm/include/llvm/IR/ValueMap.h' l='337' u='w' c='_ZN4llvm16ValueMapIteratorC1Ev'/>
<use f='llvm/llvm/include/llvm/IR/ValueMap.h' l='338' u='w' c='_ZN4llvm16ValueMapIteratorC1ENT_8iteratorE'/>
<use f='llvm/llvm/include/llvm/IR/ValueMap.h' l='340' u='r' c='_ZNK4llvm16ValueMapIterator4baseEv'/>
<use f='llvm/llvm/include/llvm/IR/ValueMap.h' l='354' u='c' c='_ZNK4llvm16ValueMapIteratordeEv'/>
<use f='llvm/llvm/include/llvm/IR/ValueMap.h' l='354' u='r' c='_ZNK4llvm16ValueMapIteratordeEv'/>
<use f='llvm/llvm/include/llvm/IR/ValueMap.h' l='363' c='_ZNK4llvm16ValueMapIteratoreqERKNS_16ValueMapIteratorIT_T0_EE'/>
<use f='llvm/llvm/include/llvm/IR/ValueMap.h' l='366' c='_ZNK4llvm16ValueMapIteratorneERKNS_16ValueMapIteratorIT_T0_EE'/>
<use f='llvm/llvm/include/llvm/IR/ValueMap.h' l='370' u='w' c='_ZN4llvm16ValueMapIteratorppEv'/>
