<dec f='llvm/build/lib/Target/Mips/MipsGenInstrInfo.inc' l='2573' type='2558'/>
<use f='llvm/llvm/lib/Target/Mips/AsmParser/MipsAsmParser.cpp' l='5194' u='r' c='_ZN12_GLOBAL__N_113MipsAsmParser10expandMulOERN4llvm6MCInstENS1_5SMLocERNS1_10MCStreamerEPKNS1_15MCSubtargetInfoE'/>
<use f='llvm/build/lib/Target/Mips/MipsGenAsmMatcher.inc' l='7797'/>
<use f='llvm/build/lib/Target/Mips/MipsGenAsmMatcher.inc' l='7803'/>
<use f='llvm/build/lib/Target/Mips/MipsGenMCCodeEmitter.inc' l='5421' c='_ZNK4llvm17MipsMCCodeEmitter21getBinaryCodeForInstrERKNS_6MCInstERNS_15SmallVectorImplINS_7MCFixupEEERKNS_15MCSubtargetInfoE'/>
<use f='llvm/build/lib/Target/Mips/MipsGenDAGISel.inc' l='16289' u='r' c='_ZN4llvm16MipsDAGToDAGISel10SelectCodeEPNS_6SDNodeE'/>
<use f='llvm/build/lib/Target/Mips/MipsGenDAGISel.inc' l='16289' u='r' c='_ZN4llvm16MipsDAGToDAGISel10SelectCodeEPNS_6SDNodeE'/>
<use f='llvm/build/lib/Target/Mips/MipsGenDAGISel.inc' l='20761' u='r' c='_ZN4llvm16MipsDAGToDAGISel10SelectCodeEPNS_6SDNodeE'/>
<use f='llvm/build/lib/Target/Mips/MipsGenDAGISel.inc' l='20761' u='r' c='_ZN4llvm16MipsDAGToDAGISel10SelectCodeEPNS_6SDNodeE'/>
<use f='llvm/build/lib/Target/Mips/MipsGenDAGISel.inc' l='21740' u='r' c='_ZN4llvm16MipsDAGToDAGISel10SelectCodeEPNS_6SDNodeE'/>
<use f='llvm/build/lib/Target/Mips/MipsGenDAGISel.inc' l='21740' u='r' c='_ZN4llvm16MipsDAGToDAGISel10SelectCodeEPNS_6SDNodeE'/>
<use f='llvm/build/lib/Target/Mips/MipsGenDAGISel.inc' l='21766' u='r' c='_ZN4llvm16MipsDAGToDAGISel10SelectCodeEPNS_6SDNodeE'/>
<use f='llvm/build/lib/Target/Mips/MipsGenDAGISel.inc' l='21766' u='r' c='_ZN4llvm16MipsDAGToDAGISel10SelectCodeEPNS_6SDNodeE'/>
<use f='llvm/build/lib/Target/Mips/MipsGenDAGISel.inc' l='21805' u='r' c='_ZN4llvm16MipsDAGToDAGISel10SelectCodeEPNS_6SDNodeE'/>
<use f='llvm/build/lib/Target/Mips/MipsGenDAGISel.inc' l='21805' u='r' c='_ZN4llvm16MipsDAGToDAGISel10SelectCodeEPNS_6SDNodeE'/>
<use f='llvm/build/lib/Target/Mips/MipsGenDAGISel.inc' l='21831' u='r' c='_ZN4llvm16MipsDAGToDAGISel10SelectCodeEPNS_6SDNodeE'/>
<use f='llvm/build/lib/Target/Mips/MipsGenDAGISel.inc' l='21831' u='r' c='_ZN4llvm16MipsDAGToDAGISel10SelectCodeEPNS_6SDNodeE'/>
<use f='llvm/llvm/lib/Target/Mips/MipsExpandPseudo.cpp' l='186' u='r' c='_ZN12_GLOBAL__N_116MipsExpandPseudo26expandAtomicCmpSwapSubwordERN4llvm17MachineBasicBlockENS1_26MachineInstrBundleIteratorINS1_12MachineInstrELb0EEERS6_'/>
<use f='llvm/llvm/lib/Target/Mips/MipsExpandPseudo.cpp' l='561' u='r' c='_ZN12_GLOBAL__N_116MipsExpandPseudo24expandAtomicBinOpSubwordERN4llvm17MachineBasicBlockENS1_26MachineInstrBundleIteratorINS1_12MachineInstrELb0EEERS6_'/>
<use f='llvm/build/lib/Target/Mips/MipsGenFastISel.inc' l='3663' u='r' c='_ZN12_GLOBAL__N_112MipsFastISel46fastEmit_ISD_SRA_MVT_i32_ri_Predicate_immZExt5EN4llvm3MVTEjbm'/>
<use f='llvm/llvm/lib/Target/Mips/MipsFastISel.cpp' l='1845' u='r' c='_ZN12_GLOBAL__N_112MipsFastISel15emitIntSExt32r1EN4llvm3MVTEjS2_j'/>
<use f='llvm/llvm/lib/Target/Mips/MipsFastISel.cpp' l='2000' u='r' c='_ZN12_GLOBAL__N_112MipsFastISel11selectShiftEPKN4llvm11InstructionE'/>
<use f='llvm/llvm/lib/Target/Mips/MipsISelLowering.cpp' l='1639' u='r' c='_ZNK4llvm18MipsTargetLowering24emitSignExtendToI32InRegERNS_12MachineInstrEPNS_17MachineBasicBlockEjjj'/>
<use f='llvm/build/lib/Target/Mips/MipsGenGlobalISel.inc' l='12649' u='r' c='_ZNK12_GLOBAL__N_123MipsInstructionSelector13getMatchTableEv'/>
<use f='llvm/build/lib/Target/Mips/MipsGenGlobalISel.inc' l='14727' u='r' c='_ZNK12_GLOBAL__N_123MipsInstructionSelector13getMatchTableEv'/>
