<dec f='llvm/build/lib/Target/MSP430/MSP430GenRegisterInfo.inc' l='21' type='1'/>
<use f='llvm/build/lib/Target/MSP430/MSP430GenAsmMatcher.inc' l='383' u='r' c='_ZN12_GLOBAL__N_115MSP430AsmParser15convertToMCInstEjRN4llvm6MCInstEjRKNS1_15SmallVectorImplISt10unique_ptrINS1_18MCParsedAsmOperandESt14default_deleteIS6_EEEE'/>
<use f='llvm/build/lib/Target/MSP430/MSP430GenAsmMatcher.inc' l='579' c='_ZL20validateOperandClassRN4llvm18MCParsedAsmOperandEN12_GLOBAL__N_114MatchClassKindE'/>
<use f='llvm/llvm/lib/Target/MSP430/AsmParser/MSP430AsmParser.cpp' l='563' c='_ZL16convertGR16ToGR8j'/>
<use f='llvm/llvm/lib/Target/MSP430/Disassembler/MSP430Disassembler.cpp' l='85'/>
<use f='llvm/build/lib/Target/MSP430/MSP430GenAsmWriter.inc' l='1087' u='r' c='_ZN4llvm17MSP430InstPrinter15printAliasInstrEPKNS_6MCInstEmRNS_11raw_ostreamE'/>
<use f='llvm/llvm/lib/Target/MSP430/MSP430RegisterInfo.cpp' l='85' u='r' c='_ZNK4llvm18MSP430RegisterInfo15getReservedRegsERKNS_15MachineFunctionE'/>
