<dec f='llvm/llvm/tools/llvm-jitlink/llvm-jitlink.h' l='48' type='llvm::Session &amp;'/>
<offset>1344</offset>
<use f='llvm/llvm/tools/llvm-jitlink/llvm-jitlink.cpp' l='497' u='w' c='_ZN4llvm29LLVMJITLinkObjectLinkingLayerC1ERNS_7SessionERNS_7jitlink20JITLinkMemoryManagerE'/>
<use f='llvm/llvm/tools/llvm-jitlink/llvm-jitlink.cpp' l='502' u='m' c='_ZN4llvm29LLVMJITLinkObjectLinkingLayer3addENS_18IntrusiveRefCntPtrINS_3orc15ResourceTrackerEEESt10unique_ptrINS_12MemoryBufferESt14default_deleteIS6_EE'/>
<use f='llvm/llvm/tools/llvm-jitlink/llvm-jitlink.cpp' l='502' u='m' c='_ZN4llvm29LLVMJITLinkObjectLinkingLayer3addENS_18IntrusiveRefCntPtrINS_3orc15ResourceTrackerEEESt10unique_ptrINS_12MemoryBufferESt14default_deleteIS6_EE'/>
<use f='llvm/llvm/tools/llvm-jitlink/llvm-jitlink.cpp' l='555' u='m' c='_ZN4llvm29LLVMJITLinkObjectLinkingLayer3addENS_18IntrusiveRefCntPtrINS_3orc15ResourceTrackerEEESt10unique_ptrINS_12MemoryBufferESt14default_deleteIS6_EE'/>
<use f='llvm/llvm/tools/llvm-jitlink/llvm-jitlink.cpp' l='555' u='m' c='_ZN4llvm29LLVMJITLinkObjectLinkingLayer3addENS_18IntrusiveRefCntPtrINS_3orc15ResourceTrackerEEESt10unique_ptrINS_12MemoryBufferESt14default_deleteIS6_EE'/>
<use f='llvm/llvm/tools/llvm-jitlink/llvm-jitlink.cpp' l='557' u='m' c='_ZN4llvm29LLVMJITLinkObjectLinkingLayer3addENS_18IntrusiveRefCntPtrINS_3orc15ResourceTrackerEEESt10unique_ptrINS_12MemoryBufferESt14default_deleteIS6_EE'/>
<use f='llvm/llvm/tools/llvm-jitlink/llvm-jitlink.cpp' l='559' u='m' c='_ZN4llvm29LLVMJITLinkObjectLinkingLayer3addENS_18IntrusiveRefCntPtrINS_3orc15ResourceTrackerEEESt10unique_ptrINS_12MemoryBufferESt14default_deleteIS6_EE'/>
<use f='llvm/llvm/tools/llvm-jitlink/llvm-jitlink.cpp' l='561' u='m' c='_ZN4llvm29LLVMJITLinkObjectLinkingLayer3addENS_18IntrusiveRefCntPtrINS_3orc15ResourceTrackerEEESt10unique_ptrINS_12MemoryBufferESt14default_deleteIS6_EE'/>
<use f='llvm/llvm/tools/llvm-jitlink/llvm-jitlink.cpp' l='563' u='m' c='_ZN4llvm29LLVMJITLinkObjectLinkingLayer3addENS_18IntrusiveRefCntPtrINS_3orc15ResourceTrackerEEESt10unique_ptrINS_12MemoryBufferESt14default_deleteIS6_EE'/>
<use f='llvm/llvm/tools/llvm-jitlink/llvm-jitlink.cpp' l='567' u='m' c='_ZN4llvm29LLVMJITLinkObjectLinkingLayer3addENS_18IntrusiveRefCntPtrINS_3orc15ResourceTrackerEEESt10unique_ptrINS_12MemoryBufferESt14default_deleteIS6_EE'/>
