<dec f='llvm/llvm/include/llvm/Analysis/ScalarEvolution.h' l='971' type='const llvm::SCEV *'/>
<use f='llvm/llvm/include/llvm/Analysis/ScalarEvolution.h' l='976' u='w' c='_ZN4llvm15ScalarEvolution22LoopInvariantPredicateC1ENS_7CmpInst9PredicateEPKNS_4SCEVES6_'/>
<offset>64</offset>
<use f='llvm/llvm/lib/Transforms/Scalar/IndVarSimplify.cpp' l='1387' u='r' c='_ZL36optimizeLoopExitWithUnknownExitCountPKN4llvm4LoopEPNS_10BranchInstEPNS_10BasicBlockEPKNS_4SCEVEbbPNS_15ScalarEvolutionERNS_12SCEVExpanderERNS_15S1253477'/>
<use f='llvm/llvm/lib/Transforms/Scalar/IndVarSimplify.cpp' l='1390' u='r' c='_ZL36optimizeLoopExitWithUnknownExitCountPKN4llvm4LoopEPNS_10BranchInstEPNS_10BasicBlockEPKNS_4SCEVEbbPNS_15ScalarEvolutionERNS_12SCEVExpanderERNS_15S1253477'/>
<use f='llvm/llvm/lib/Transforms/Utils/SimplifyIndVar.cpp' l='201' u='r' c='_ZN12_GLOBAL__N_114SimplifyIndvar25makeIVComparisonInvariantEPN4llvm8ICmpInstEPNS1_5ValueE'/>
