<use f='llvm/llvm/lib/Transforms/Vectorize/VPlan.h' l='254' u='w' c='_ZN4llvm16VPTransformStateC1ENS_12ElementCountEjPNS_4LoopEPNS_8LoopInfoEPNS_13DominatorTreeERNS_9IRBuilderINS_14ConstantFolderENS_24IRBuilderDefaultIn16745765'/>
<dec f='llvm/llvm/lib/Transforms/Vectorize/VPlan.h' l='364' type='IRBuilder&lt;&gt; &amp;'/>
<use f='llvm/llvm/lib/Transforms/Vectorize/LoopVectorize.cpp' l='8989' u='a' c='_ZN4llvm13VPBlendRecipe7executeERNS_16VPTransformStateE'/>
<use f='llvm/llvm/lib/Transforms/Vectorize/LoopVectorize.cpp' l='9019' u='m' c='_ZN4llvm13VPBlendRecipe7executeERNS_16VPTransformStateE'/>
<use f='llvm/llvm/lib/Transforms/Vectorize/LoopVectorize.cpp' l='9045' u='m' c='_ZN4llvm17VPReductionRecipe7executeERNS_16VPTransformStateE'/>
<use f='llvm/llvm/lib/Transforms/Vectorize/LoopVectorize.cpp' l='9049' u='a' c='_ZN4llvm17VPReductionRecipe7executeERNS_16VPTransformStateE'/>
<use f='llvm/llvm/lib/Transforms/Vectorize/LoopVectorize.cpp' l='9054' u='a' c='_ZN4llvm17VPReductionRecipe7executeERNS_16VPTransformStateE'/>
<use f='llvm/llvm/lib/Transforms/Vectorize/LoopVectorize.cpp' l='9057' u='m' c='_ZN4llvm17VPReductionRecipe7executeERNS_16VPTransformStateE'/>
<use f='llvm/llvm/lib/Transforms/Vectorize/LoopVectorize.cpp' l='9109' u='m' c='_ZN4llvm20VPBranchOnMaskRecipe7executeERNS_16VPTransformStateE'/>
<use f='llvm/llvm/lib/Transforms/Vectorize/LoopVectorize.cpp' l='9110' u='m' c='_ZN4llvm20VPBranchOnMaskRecipe7executeERNS_16VPTransformStateE'/>
<use f='llvm/llvm/lib/Transforms/Vectorize/LoopVectorize.cpp' l='9112' u='m' c='_ZN4llvm20VPBranchOnMaskRecipe7executeERNS_16VPTransformStateE'/>
<use f='llvm/llvm/lib/Transforms/Vectorize/LoopVectorize.cpp' l='9144' u='m' c='_ZN4llvm19VPPredInstPHIRecipe7executeERNS_16VPTransformStateE'/>
<use f='llvm/llvm/lib/Transforms/Vectorize/LoopVectorize.cpp' l='9150' u='m' c='_ZN4llvm19VPPredInstPHIRecipe7executeERNS_16VPTransformStateE'/>
<offset>2176</offset>
<doc f='llvm/llvm/lib/Transforms/Vectorize/VPlan.h' l='363'>/// Hold a reference to the IRBuilder used to generate output IR code.</doc>
<use f='llvm/llvm/lib/Transforms/Vectorize/VPlan.cpp' l='234' u='m' c='_ZN4llvm16VPTransformState3getEPNS_7VPValueERKNS_11VPIterationE'/>
<use f='llvm/llvm/lib/Transforms/Vectorize/VPlan.cpp' l='235' u='m' c='_ZN4llvm16VPTransformState3getEPNS_7VPValueERKNS_11VPIterationE'/>
<use f='llvm/llvm/lib/Transforms/Vectorize/VPlan.cpp' l='309' u='m' c='_ZN4llvm12VPBasicBlock7executeEPNS_16VPTransformStateE'/>
<use f='llvm/llvm/lib/Transforms/Vectorize/VPlan.cpp' l='311' u='m' c='_ZN4llvm12VPBasicBlock7executeEPNS_16VPTransformStateE'/>
<use f='llvm/llvm/lib/Transforms/Vectorize/VPlan.cpp' l='312' u='m' c='_ZN4llvm12VPBasicBlock7executeEPNS_16VPTransformStateE'/>
<use f='llvm/llvm/lib/Transforms/Vectorize/VPlan.cpp' l='340' u='m' c='_ZN4llvm12VPBasicBlock7executeEPNS_16VPTransformStateE'/>
<use f='llvm/llvm/lib/Transforms/Vectorize/VPlan.cpp' l='341' u='m' c='_ZN4llvm12VPBasicBlock7executeEPNS_16VPTransformStateE'/>
<use f='llvm/llvm/lib/Transforms/Vectorize/VPlan.cpp' l='466' u='a' c='_ZN4llvm13VPInstruction19generateInstructionERNS_16VPTransformStateEj'/>
<use f='llvm/llvm/lib/Transforms/Vectorize/VPlan.cpp' l='599' u='m' c='_ZN4llvm5VPlan7executeEPNS_16VPTransformStateE'/>
<use f='llvm/llvm/lib/Transforms/Vectorize/VPlan.cpp' l='600' u='m' c='_ZN4llvm5VPlan7executeEPNS_16VPTransformStateE'/>
<use f='llvm/llvm/lib/Transforms/Vectorize/VPlan.cpp' l='601' u='m' c='_ZN4llvm5VPlan7executeEPNS_16VPTransformStateE'/>
