<dec f='llvm/llvm/include/llvm/DebugInfo/CodeView/CodeView.h' l='150' type='6'/>
<use f='llvm/llvm/lib/CodeGen/AsmPrinter/CodeViewDebug.cpp' l='736' u='r' c='_ZL17MapDWLangToCVLangj'/>
<use f='llvm/llvm/lib/DebugInfo/CodeView/EnumTables.cpp' l='101'/>
<use f='llvm/llvm/lib/DebugInfo/PDB/Native/NativeRawSymbol.cpp' l='170' u='r' c='_ZNK4llvm3pdb15NativeRawSymbol11getLanguageEv'/>
<use f='llvm/llvm/lib/DebugInfo/PDB/PDBExtras.cpp' l='221' c='_ZN4llvm3pdblsERNS_11raw_ostreamERKNS_8codeview14SourceLanguageE'/>
<use f='llvm/llvm/tools/llvm-pdbutil/MinimalSymbolDumper.cpp' l='197' c='_ZL20formatSourceLanguageB5cxx11N4llvm8codeview14SourceLanguageE'/>
