<use f='llvm/llvm/include/llvm/Transforms/Utils/Evaluator.h' l='41' u='w' c='_ZN4llvm9EvaluatorC1ERKNS_10DataLayoutEPKNS_17TargetLibraryInfoE'/>
<dec f='llvm/llvm/include/llvm/Transforms/Utils/Evaluator.h' l='126' type='const llvm::DataLayout &amp;'/>
<offset>4928</offset>
<use f='llvm/llvm/lib/Transforms/Utils/Evaluator.cpp' l='239' u='r' c='_ZN4llvm9Evaluator17ComputeLoadResultEPNS_8ConstantE'/>
<use f='llvm/llvm/lib/Transforms/Utils/Evaluator.cpp' l='244' u='r' c='_ZN4llvm9Evaluator17ComputeLoadResultEPNS_8ConstantE'/>
<use f='llvm/llvm/lib/Transforms/Utils/Evaluator.cpp' l='275' u='r' c='_ZN4llvm9Evaluator23getCalleeWithFormalArgsERNS_8CallBaseERNS_15SmallVectorImplIPNS_8ConstantEEE'/>
<use f='llvm/llvm/lib/Transforms/Utils/Evaluator.cpp' l='292' u='r' c='_ZN4llvm9Evaluator15getFormalParamsERNS_8CallBaseEPNS_8FunctionERNS_15SmallVectorImplIPNS_8ConstantEEE'/>
<use f='llvm/llvm/lib/Transforms/Utils/Evaluator.cpp' l='312' u='r' c='_ZN4llvm9Evaluator22castCallResultIfNeededEPNS_5ValueEPNS_8ConstantE'/>
<use f='llvm/llvm/lib/Transforms/Utils/Evaluator.cpp' l='336' u='r' c='_ZN4llvm9Evaluator13EvaluateBlockENS_14ilist_iteratorINS_12ilist_detail12node_optionsINS_11InstructionELb0ELb0EvEELb0ELb0EEERPNS_10BasicBlockE'/>
<use f='llvm/llvm/lib/Transforms/Utils/Evaluator.cpp' l='353' u='r' c='_ZN4llvm9Evaluator13EvaluateBlockENS_14ilist_iteratorINS_12ilist_detail12node_optionsINS_11InstructionELb0ELb0EvEELb0ELb0EEERPNS_10BasicBlockE'/>
<use f='llvm/llvm/lib/Transforms/Utils/Evaluator.cpp' l='372' u='r' c='_ZN4llvm9Evaluator13EvaluateBlockENS_14ilist_iteratorINS_12ilist_detail12node_optionsINS_11InstructionELb0ELb0EvEELb0ELb0EEERPNS_10BasicBlockE'/>
<use f='llvm/llvm/lib/Transforms/Utils/Evaluator.cpp' l='380' u='r' c='_ZN4llvm9Evaluator13EvaluateBlockENS_14ilist_iteratorINS_12ilist_detail12node_optionsINS_11InstructionELb0ELb0EvEELb0ELb0EEERPNS_10BasicBlockE'/>
<use f='llvm/llvm/lib/Transforms/Utils/Evaluator.cpp' l='446' u='r' c='_ZN4llvm9Evaluator13EvaluateBlockENS_14ilist_iteratorINS_12ilist_detail12node_optionsINS_11InstructionELb0ELb0EvEELb0ELb0EEERPNS_10BasicBlockE'/>
<use f='llvm/llvm/lib/Transforms/Utils/Evaluator.cpp' l='529' u='m' c='_ZN4llvm9Evaluator13EvaluateBlockENS_14ilist_iteratorINS_12ilist_detail12node_optionsINS_11InstructionELb0ELb0EvEELb0ELb0EEERPNS_10BasicBlockE'/>
<use f='llvm/llvm/lib/Transforms/Utils/Evaluator.cpp' l='650' u='r' c='_ZN4llvm9Evaluator13EvaluateBlockENS_14ilist_iteratorINS_12ilist_detail12node_optionsINS_11InstructionELb0ELb0EvEELb0ELb0EEERPNS_10BasicBlockE'/>
