<dec f='llvm/llvm/lib/Target/AMDGPU/GCNIterativeScheduler.cpp' l='128' type='llvm::GCNIterativeScheduler &amp;'/>
<use f='llvm/llvm/lib/Target/AMDGPU/GCNIterativeScheduler.cpp' l='134' u='w' c='_ZN4llvm21GCNIterativeScheduler8BuildDAGC1ERKNS0_6RegionERS0_'/>
<use f='llvm/llvm/lib/Target/AMDGPU/GCNIterativeScheduler.cpp' l='136' u='m' c='_ZN4llvm21GCNIterativeScheduler8BuildDAGC1ERKNS0_6RegionERS0_'/>
<use f='llvm/llvm/lib/Target/AMDGPU/GCNIterativeScheduler.cpp' l='137' u='m' c='_ZN4llvm21GCNIterativeScheduler8BuildDAGC1ERKNS0_6RegionERS0_'/>
<use f='llvm/llvm/lib/Target/AMDGPU/GCNIterativeScheduler.cpp' l='139' u='m' c='_ZN4llvm21GCNIterativeScheduler8BuildDAGC1ERKNS0_6RegionERS0_'/>
<use f='llvm/llvm/lib/Target/AMDGPU/GCNIterativeScheduler.cpp' l='139' u='m' c='_ZN4llvm21GCNIterativeScheduler8BuildDAGC1ERKNS0_6RegionERS0_'/>
<use f='llvm/llvm/lib/Target/AMDGPU/GCNIterativeScheduler.cpp' l='141' u='m' c='_ZN4llvm21GCNIterativeScheduler8BuildDAGC1ERKNS0_6RegionERS0_'/>
<use f='llvm/llvm/lib/Target/AMDGPU/GCNIterativeScheduler.cpp' l='142' u='m' c='_ZN4llvm21GCNIterativeScheduler8BuildDAGC1ERKNS0_6RegionERS0_'/>
<use f='llvm/llvm/lib/Target/AMDGPU/GCNIterativeScheduler.cpp' l='146' u='m' c='_ZN4llvm21GCNIterativeScheduler8BuildDAGD1Ev'/>
<use f='llvm/llvm/lib/Target/AMDGPU/GCNIterativeScheduler.cpp' l='147' u='m' c='_ZN4llvm21GCNIterativeScheduler8BuildDAGD1Ev'/>
<offset>0</offset>
