<dec f='llvm/build/include/llvm/IR/IntrinsicEnums.inc' l='245' type='236'/>
<doc f='llvm/build/include/llvm/IR/IntrinsicEnums.inc' l='245'>// llvm.rint</doc>
<use f='llvm/clang/lib/CodeGen/CGBuiltin.cpp' l='2420' u='r' c='_ZN5clang7CodeGen15CodeGenFunction15EmitBuiltinExprENS_10GlobalDeclEjPKNS_8CallExprENS0_15ReturnValueSlotE'/>
<use f='llvm/build/tools/clang/include/clang/Basic/arm_mve_builtin_cg.inc' l='8663' u='r' c='_ZN5clang7CodeGen15CodeGenFunction21EmitARMMVEBuiltinExprEjPKNS_8CallExprENS0_15ReturnValueSlotEN4llvm6Triple8ArchTypeE'/>
<use f='llvm/build/tools/clang/include/clang/Basic/arm_mve_builtin_cg.inc' l='8667' u='r' c='_ZN5clang7CodeGen15CodeGenFunction21EmitARMMVEBuiltinExprEjPKNS_8CallExprENS0_15ReturnValueSlotEN4llvm6Triple8ArchTypeE'/>
<use f='llvm/clang/lib/CodeGen/CGBuiltin.cpp' l='10426' u='r' c='_ZN5clang7CodeGen15CodeGenFunction22EmitAArch64BuiltinExprEjPKNS_8CallExprEN4llvm6Triple8ArchTypeE'/>
<use f='llvm/clang/lib/CodeGen/CGBuiltin.cpp' l='10433' u='r' c='_ZN5clang7CodeGen15CodeGenFunction22EmitAArch64BuiltinExprEjPKNS_8CallExprEN4llvm6Triple8ArchTypeE'/>
<use f='llvm/clang/lib/CodeGen/CGBuiltin.cpp' l='14782' u='r' c='_ZN5clang7CodeGen15CodeGenFunction18EmitPPCBuiltinExprEjPKNS_8CallExprE'/>
<use f='llvm/clang/lib/CodeGen/CGBuiltin.cpp' l='15673' u='r' c='_ZN5clang7CodeGen15CodeGenFunction22EmitSystemZBuiltinExprEjPKNS_8CallExprE'/>
<use f='llvm/llvm/lib/Analysis/ConstantFolding.cpp' l='1571' c='_ZN4llvm21canConstantFoldCallToEPKNS_8CallBaseEPKNS_8FunctionE'/>
<use f='llvm/llvm/lib/Analysis/ConstantFolding.cpp' l='1946' u='r' c='_ZN12_GLOBAL__N_123ConstantFoldScalarCall1EN4llvm9StringRefEjPNS0_4TypeENS0_8ArrayRefIPNS0_8ConstantEEEPKNS0_17TargetLibraryInfoEPKNS0_8CallBaseE'/>
<use f='llvm/llvm/lib/Analysis/InstructionSimplify.cpp' l='5235' c='_ZL12IsIdempotentj'/>
<use f='llvm/llvm/lib/Analysis/InstructionSimplify.cpp' l='5365' c='_ZL22simplifyUnaryIntrinsicPN4llvm8FunctionEPNS_5ValueERKNS_13SimplifyQueryE'/>
<use f='llvm/llvm/lib/Analysis/ValueTracking.cpp' l='3183' u='r' c='_ZN4llvm23getIntrinsicForCallSiteERKNS_8CallBaseEPKNS_17TargetLibraryInfoE'/>
<use f='llvm/llvm/lib/Analysis/ValueTracking.cpp' l='3558' c='_ZN4llvm15isKnownNeverNaNEPKNS_5ValueEPKNS_17TargetLibraryInfoEj'/>
<use f='llvm/llvm/lib/Analysis/VectorUtils.cpp' l='83' c='_ZN4llvm23isTriviallyVectorizableEj'/>
<use f='llvm/llvm/include/llvm/CodeGen/BasicTTIImpl.h' l='1500' c='_ZN4llvm16BasicTTIImplBase30getTypeBasedIntrinsicInstrCostERKNS_23IntrinsicCostAttributesENS_19TargetTransformInfo14TargetCostKindE'/>
<use f='llvm/llvm/lib/CodeGen/GlobalISel/IRTranslator.cpp' l='1717' c='_ZN4llvm12IRTranslator24getSimpleIntrinsicOpcodeEj'/>
<use f='llvm/llvm/lib/CodeGen/SelectionDAG/SelectionDAGBuilder.cpp' l='6093' c='_ZN4llvm19SelectionDAGBuilder18visitIntrinsicCallERKNS_8CallInstEj'/>
<use f='llvm/llvm/lib/CodeGen/SelectionDAG/SelectionDAGBuilder.cpp' l='6108' c='_ZN4llvm19SelectionDAGBuilder18visitIntrinsicCallERKNS_8CallInstEj'/>
<use f='llvm/llvm/lib/Target/ARM/ARMTargetTransformInfo.cpp' l='1603' c='_ZN4llvm10ARMTTIImpl15isLoweredToCallEPKNS_8FunctionE'/>
<use f='llvm/llvm/lib/Target/PowerPC/PPCTargetTransformInfo.cpp' l='498' c='_ZN4llvm10PPCTTIImpl11mightUseCTREPNS_10BasicBlockEPNS_17TargetLibraryInfoERNS_15SmallPtrSetImplIPKNS_5ValueEEE'/>
<use f='llvm/llvm/lib/Transforms/InstCombine/InstCombineCalls.cpp' l='1317' c='_ZN4llvm16InstCombinerImpl13visitCallInstERNS_8CallInstE'/>
<use f='llvm/llvm/lib/Transforms/InstCombine/InstCombineCasts.cpp' l='1798' c='_ZN4llvm16InstCombinerImpl12visitFPTruncERNS_11FPTruncInstE'/>
<use f='llvm/llvm/lib/Transforms/Utils/SimplifyLibCalls.cpp' l='2998' u='r' c='_ZN4llvm17LibCallSimplifier28optimizeFloatingPointLibCallEPNS_8CallInstENS_7LibFuncERNS_13IRBuilderBaseE'/>
