<dec f='llvm/llvm/include/llvm/Analysis/LazyCallGraph.h' l='1305' type='llvm::raw_ostream &amp;'/>
<offset>0</offset>
<use f='llvm/llvm/lib/Analysis/LazyCallGraph.cpp' l='1990' u='w' c='_ZN4llvm24LazyCallGraphPrinterPassC1ERNS_11raw_ostreamE'/>
<use f='llvm/llvm/lib/Analysis/LazyCallGraph.cpp' l='2021' u='m' c='_ZN4llvm24LazyCallGraphPrinterPass3runERNS_6ModuleERNS_15AnalysisManagerIS1_JEEE'/>
<use f='llvm/llvm/lib/Analysis/LazyCallGraph.cpp' l='2025' u='a' c='_ZN4llvm24LazyCallGraphPrinterPass3runERNS_6ModuleERNS_15AnalysisManagerIS1_JEEE'/>
<use f='llvm/llvm/lib/Analysis/LazyCallGraph.cpp' l='2029' u='a' c='_ZN4llvm24LazyCallGraphPrinterPass3runERNS_6ModuleERNS_15AnalysisManagerIS1_JEEE'/>
