<use f='llvm/llvm/include/llvm/Support/YAMLParser.h' l='159' u='r' c='_ZNK4llvm4yaml4Node9getRawTagEv'/>
<dec f='llvm/llvm/include/llvm/Support/YAMLParser.h' l='190' type='llvm::StringRef'/>
<offset>448</offset>
<doc f='llvm/llvm/include/llvm/Support/YAMLParser.h' l='189'>/// The tag as typed in the document.</doc>
<use f='llvm/llvm/lib/Support/YAMLParser.cpp' l='1885' u='w' c='_ZN4llvm4yaml4NodeC1EjRSt10unique_ptrINS0_8DocumentESt14default_deleteIS3_EENS_9StringRefES8_'/>
