<dec f='llvm/llvm/include/llvm/IR/ModuleSlotTracker.h' l='35' type='const llvm::Module *'/>
<use f='llvm/llvm/include/llvm/IR/ModuleSlotTracker.h' l='60' u='r' c='_ZNK4llvm17ModuleSlotTracker9getModuleEv'/>
<offset>128</offset>
<use f='llvm/llvm/lib/IR/AsmWriter.cpp' l='872' u='w' c='_ZN4llvm17ModuleSlotTrackerC1ERNS_11SlotTrackerEPKNS_6ModuleEPKNS_8FunctionE'/>
<use f='llvm/llvm/lib/IR/AsmWriter.cpp' l='877' u='w' c='_ZN4llvm17ModuleSlotTrackerC1EPKNS_6ModuleEb'/>
<use f='llvm/llvm/lib/IR/AsmWriter.cpp' l='887' u='a' c='_ZN4llvm17ModuleSlotTracker10getMachineEv'/>
