<use f='llvm/llvm/lib/Support/FileCollector.cpp' l='259' u='w' c='_ZN4llvm23FileCollectorFileSystemC1ENS_18IntrusiveRefCntPtrINS_3vfs10FileSystemEEESt10shared_ptrINS_13FileCollectorEE'/>
<use f='llvm/llvm/lib/Support/FileCollector.cpp' l='262' u='m' c='_ZN4llvm23FileCollectorFileSystem6statusERKNS_5TwineE'/>
<use f='llvm/llvm/lib/Support/FileCollector.cpp' l='270' u='m' c='_ZN4llvm23FileCollectorFileSystem15openFileForReadERKNS_5TwineE'/>
<use f='llvm/llvm/lib/Support/FileCollector.cpp' l='278' u='r' c='_ZN4llvm23FileCollectorFileSystem9dir_beginERKNS_5TwineERSt10error_code'/>
<use f='llvm/llvm/lib/Support/FileCollector.cpp' l='283' u='m' c='_ZNK4llvm23FileCollectorFileSystem11getRealPathERKNS_5TwineERNS_15SmallVectorImplIcEE'/>
<use f='llvm/llvm/lib/Support/FileCollector.cpp' l='293' u='m' c='_ZN4llvm23FileCollectorFileSystem7isLocalERKNS_5TwineERb'/>
<use f='llvm/llvm/lib/Support/FileCollector.cpp' l='297' u='m' c='_ZNK4llvm23FileCollectorFileSystem26getCurrentWorkingDirectoryB5cxx11Ev'/>
<use f='llvm/llvm/lib/Support/FileCollector.cpp' l='301' u='m' c='_ZN4llvm23FileCollectorFileSystem26setCurrentWorkingDirectoryERKNS_5TwineE'/>
<dec f='llvm/llvm/lib/Support/FileCollector.cpp' l='305' type='IntrusiveRefCntPtr&lt;vfs::FileSystem&gt;'/>
<offset>128</offset>
