<dec f='llvm/llvm/lib/Target/AArch64/Utils/AArch64BaseInfo.h' l='250' type='14'/>
<use f='llvm/llvm/lib/Target/AArch64/Utils/AArch64BaseInfo.h' l='279' c='_ZN4llvm9AArch64CCL15getCondCodeNameENS0_8CondCodeE'/>
<doc f='llvm/llvm/lib/Target/AArch64/Utils/AArch64BaseInfo.h' l='250'>// Always (unconditional)     Always (unconditional)</doc>
<use f='llvm/llvm/lib/Target/AArch64/AArch64FastISel.cpp' l='2250' u='r' c='_ZL12getCompareCCN4llvm7CmpInst9PredicateE'/>
<use f='llvm/llvm/lib/Target/AArch64/AArch64FastISel.cpp' l='2461' u='r' c='_ZN12_GLOBAL__N_115AArch64FastISel12selectBranchEPKN4llvm11InstructionE'/>
<use f='llvm/llvm/lib/Target/AArch64/AArch64FastISel.cpp' l='2477' u='r' c='_ZN12_GLOBAL__N_115AArch64FastISel12selectBranchEPKN4llvm11InstructionE'/>
<use f='llvm/llvm/lib/Target/AArch64/AArch64FastISel.cpp' l='2742' u='r' c='_ZN12_GLOBAL__N_115AArch64FastISel12selectSelectEPKN4llvm11InstructionE'/>
<use f='llvm/llvm/lib/Target/AArch64/AArch64FastISel.cpp' l='2826' u='r' c='_ZN12_GLOBAL__N_115AArch64FastISel12selectSelectEPKN4llvm11InstructionE'/>
<use f='llvm/llvm/lib/Target/AArch64/AArch64ISelLowering.cpp' l='2131' u='r' c='_ZL21changeFPCCToAArch64CCN4llvm3ISD8CondCodeERNS_9AArch64CC8CondCodeES4_'/>
<use f='llvm/llvm/lib/Target/AArch64/AArch64ISelLowering.cpp' l='2194' u='r' c='_ZL24changeFPCCToANDAArch64CCN4llvm3ISD8CondCodeERNS_9AArch64CC8CondCodeES4_'/>
<use f='llvm/llvm/lib/Target/AArch64/AArch64ISelLowering.cpp' l='2524' u='r' c='_ZL18emitConjunctionRecRN4llvm12SelectionDAGENS_7SDValueERNS_9AArch64CC8CondCodeEbS2_S4_'/>
<use f='llvm/llvm/lib/Target/AArch64/AArch64ISelLowering.cpp' l='2621' u='r' c='_ZL15emitConjunctionRN4llvm12SelectionDAGENS_7SDValueERNS_9AArch64CC8CondCodeE'/>
<use f='llvm/llvm/lib/Target/AArch64/AArch64ISelLowering.cpp' l='6425' u='r' c='_ZNK4llvm21AArch64TargetLowering10LowerBR_CCENS_7SDValueERNS_12SelectionDAGE'/>
<use f='llvm/llvm/lib/Target/AArch64/AArch64ISelLowering.cpp' l='6650' u='r' c='_ZNK4llvm21AArch64TargetLowering10LowerSETCCENS_7SDValueERNS_12SelectionDAGE'/>
<use f='llvm/llvm/lib/Target/AArch64/AArch64ISelLowering.cpp' l='6856' u='r' c='_ZNK4llvm21AArch64TargetLowering14LowerSELECT_CCENS_3ISD8CondCodeENS_7SDValueES3_S3_S3_RKNS_5SDLocERNS_12SelectionDAGE'/>
<use f='llvm/llvm/lib/Target/AArch64/AArch64ISelLowering.cpp' l='10325' u='r' c='_ZNK4llvm21AArch64TargetLowering11LowerVSETCCENS_7SDValueERNS_12SelectionDAGE'/>
<use f='llvm/llvm/lib/Target/AArch64/AArch64ISelLowering.cpp' l='14759' c='_ZL20isEquivalentMasklessjjN4llvm3ISD11LoadExtTypeEii'/>
<use f='llvm/llvm/lib/Target/AArch64/AsmParser/AArch64AsmParser.cpp' l='2769' u='r' c='_ZN12_GLOBAL__N_116AArch64AsmParser19parseCondCodeStringEN4llvm9StringRefE'/>
<use f='llvm/llvm/lib/Target/AArch64/AsmParser/AArch64AsmParser.cpp' l='2806' u='r' c='_ZN12_GLOBAL__N_116AArch64AsmParser13parseCondCodeERN4llvm15SmallVectorImplISt10unique_ptrINS1_18MCParsedAsmOperandESt14default_deleteIS4_EEEEb'/>
<use f='llvm/llvm/lib/Target/AArch64/GISel/AArch64InstructionSelector.cpp' l='1214' u='r' c='_ZL25changeFCMPPredToAArch64CCN4llvm7CmpInst9PredicateERNS_9AArch64CC8CondCodeES4_'/>
<use f='llvm/llvm/lib/Target/AArch64/GISel/AArch64InstructionSelector.cpp' l='1497' u='r' c='_ZNK12_GLOBAL__N_126AArch64InstructionSelector28selectCompareBranchFedByFCmpERN4llvm12MachineInstrES3_RNS1_16MachineIRBuilderE'/>
<use f='llvm/llvm/lib/Target/AArch64/GISel/AArch64InstructionSelector.cpp' l='4204' u='r' c='_ZNK12_GLOBAL__N_126AArch64InstructionSelector15emitCSetForFCmpEN4llvm8RegisterENS1_7CmpInst9PredicateERNS1_16MachineIRBuilderE'/>
<use f='llvm/llvm/lib/Target/AArch64/GISel/AArch64InstructionSelector.cpp' l='4460' u='r' c='_ZNK12_GLOBAL__N_126AArch64InstructionSelector12tryOptSelectERN4llvm12MachineInstrE'/>
<use f='llvm/build/lib/Target/AArch64/AArch64GenAsmWriter.inc' l='24269' u='r' c='_ZL35AArch64InstPrinterValidateMCOperandRKN4llvm9MCOperandERKNS_15MCSubtargetInfoEj'/>
<use f='llvm/build/lib/Target/AArch64/AArch64GenAsmWriter1.inc' l='24992' u='r' c='_ZL40AArch64AppleInstPrinterValidateMCOperandRKN4llvm9MCOperandERKNS_15MCSubtargetInfoEj'/>
