<dec f='llvm/build/lib/Target/PowerPC/PPCGenRegisterInfo.inc' l='24' type='4'/>
<use f='llvm/build/lib/Target/PowerPC/PPCGenAsmMatcher.inc' l='4422' c='_ZL20validateOperandClassRN4llvm18MCParsedAsmOperandEN12_GLOBAL__N_114MatchClassKindE'/>
<use f='llvm/llvm/lib/Target/PowerPC/PPCFrameLowering.cpp' l='404' c='_ZNK4llvm16PPCFrameLowering19replaceFPWithRealFPERNS_15MachineFunctionE'/>
<use f='llvm/llvm/lib/Target/PowerPC/PPCISelLowering.cpp' l='15304' u='r' c='_ZNK4llvm17PPCTargetLowering14LowerFRAMEADDRENS_7SDValueERNS_12SelectionDAGE'/>
<use f='llvm/llvm/lib/Target/PowerPC/PPCRegisterInfo.cpp' l='278' u='r' c='_ZNK4llvm15PPCRegisterInfo15getReservedRegsERKNS_15MachineFunctionE'/>
