<dec f='llvm/llvm/include/llvm/MC/MCAsmMacro.h' l='49' type='23'/>
<use f='llvm/llvm/lib/MC/MCParser/AsmLexer.cpp' l='776' u='r' c='_ZN4llvm8AsmLexer8LexTokenEv'/>
<use f='llvm/llvm/lib/MC/MCParser/AsmParser.cpp' l='1559' c='_ZL24getDarwinBinOpPrecedenceN4llvm8AsmToken9TokenKindERNS_12MCBinaryExpr6OpcodeEb'/>
<use f='llvm/llvm/lib/MC/MCParser/AsmParser.cpp' l='1636' c='_ZL21getGNUBinOpPrecedenceRKN4llvm9MCAsmInfoENS_8AsmToken9TokenKindERNS_12MCBinaryExpr6OpcodeEb'/>
<use f='llvm/llvm/lib/MC/MCParser/AsmParser.cpp' l='1754' u='r' c='_ZN12_GLOBAL__N_19AsmParser14parseStatementERNS_18ParseStatementInfoEPN4llvm23MCAsmParserSemaCallbackE'/>
<use f='llvm/llvm/lib/MC/MCParser/AsmParser.cpp' l='2551' c='_ZL10isOperatorN4llvm8AsmToken9TokenKindE'/>
<use f='llvm/llvm/lib/MC/MCParser/MCAsmLexer.cpp' l='97' c='_ZNK4llvm8AsmToken4dumpERNS_11raw_ostreamE'/>
<use f='llvm/llvm/lib/MC/MCParser/MasmParser.cpp' l='1882' c='_ZL21getGNUBinOpPrecedenceN4llvm8AsmToken9TokenKindERNS_12MCBinaryExpr6OpcodeEbb'/>
<use f='llvm/llvm/lib/MC/MCParser/MasmParser.cpp' l='2024' u='r' c='_ZN12_GLOBAL__N_110MasmParser14parseStatementERNS_18ParseStatementInfoEPN4llvm23MCAsmParserSemaCallbackE'/>
<use f='llvm/llvm/lib/MC/MCParser/MasmParser.cpp' l='2849' c='_ZL10isOperatorN4llvm8AsmToken9TokenKindE'/>
<use f='llvm/llvm/lib/Target/BPF/AsmParser/BPFAsmParser.cpp' l='377' c='_ZN12_GLOBAL__N_112BPFAsmParser22parseOperandAsOperatorERN4llvm15SmallVectorImplISt10unique_ptrINS1_18MCParsedAsmOperandESt14default_deleteIS4_EEEE'/>
<use f='llvm/llvm/lib/Target/Lanai/AsmParser/LanaiAsmParser.cpp' l='858' u='r' c='_ZN12_GLOBAL__N_114LanaiAsmParser12parsePrePostEN4llvm9StringRefEPi'/>
<use f='llvm/llvm/lib/Target/Mips/AsmParser/MipsAsmParser.cpp' l='6491' c='_ZN12_GLOBAL__N_113MipsAsmParser15parseMemOperandERN4llvm15SmallVectorImplISt10unique_ptrINS1_18MCParsedAsmOperandESt14default_deleteIS4_EEEE'/>
<use f='llvm/llvm/lib/Target/X86/AsmParser/X86AsmParser.cpp' l='2112' c='_ZN12_GLOBAL__N_112X86AsmParser20ParseIntelExpressionERNS0_21IntelExprStateMachineERN4llvm5SMLocE'/>
<use f='llvm/llvm/lib/Target/X86/AsmParser/X86AsmParser.cpp' l='2675' u='r' c='_ZN12_GLOBAL__N_112X86AsmParser15ParseATTOperandERN4llvm15SmallVectorImplISt10unique_ptrINS1_18MCParsedAsmOperandESt14default_deleteIS4_EEEE'/>
<use f='llvm/llvm/lib/Target/X86/AsmParser/X86AsmParser.cpp' l='3360' u='r' c='_ZN12_GLOBAL__N_112X86AsmParser16ParseInstructionERN4llvm20ParseInstructionInfoENS1_9StringRefENS1_5SMLocERNS1_15SmallVectorImplISt10unique_ptrINS1_1814823810'/>
