<use f='llvm/llvm/include/llvm/Analysis/TargetTransformInfo.h' l='93' u='w' c='_ZN4llvm16HardwareLoopInfoC1EPNS_4LoopE'/>
<dec f='llvm/llvm/include/llvm/Analysis/TargetTransformInfo.h' l='94' type='llvm::Loop *'/>
<offset>0</offset>
<use f='llvm/llvm/lib/Analysis/TargetTransformInfo.cpp' l='50' u='r' c='_ZN4llvm16HardwareLoopInfo10canAnalyzeERNS_8LoopInfoE'/>
<use f='llvm/llvm/lib/Analysis/TargetTransformInfo.cpp' l='155' u='r' c='_ZN4llvm16HardwareLoopInfo23isHardwareLoopCandidateERNS_15ScalarEvolutionERNS_8LoopInfoERNS_13DominatorTreeEbb'/>
<use f='llvm/llvm/lib/Analysis/TargetTransformInfo.cpp' l='160' u='r' c='_ZN4llvm16HardwareLoopInfo23isHardwareLoopCandidateERNS_15ScalarEvolutionERNS_8LoopInfoERNS_13DominatorTreeEbb'/>
<use f='llvm/llvm/lib/Analysis/TargetTransformInfo.cpp' l='165' u='r' c='_ZN4llvm16HardwareLoopInfo23isHardwareLoopCandidateERNS_15ScalarEvolutionERNS_8LoopInfoERNS_13DominatorTreeEbb'/>
<use f='llvm/llvm/lib/Analysis/TargetTransformInfo.cpp' l='171' u='r' c='_ZN4llvm16HardwareLoopInfo23isHardwareLoopCandidateERNS_15ScalarEvolutionERNS_8LoopInfoERNS_13DominatorTreeEbb'/>
<use f='llvm/llvm/lib/Analysis/TargetTransformInfo.cpp' l='180' u='r' c='_ZN4llvm16HardwareLoopInfo23isHardwareLoopCandidateERNS_15ScalarEvolutionERNS_8LoopInfoERNS_13DominatorTreeEbb'/>
<use f='llvm/llvm/lib/Analysis/TargetTransformInfo.cpp' l='191' u='r' c='_ZN4llvm16HardwareLoopInfo23isHardwareLoopCandidateERNS_15ScalarEvolutionERNS_8LoopInfoERNS_13DominatorTreeEbb'/>
<use f='llvm/llvm/lib/Analysis/TargetTransformInfo.cpp' l='192' u='r' c='_ZN4llvm16HardwareLoopInfo23isHardwareLoopCandidateERNS_15ScalarEvolutionERNS_8LoopInfoERNS_13DominatorTreeEbb'/>
<use f='llvm/llvm/lib/CodeGen/HardwareLoops.cpp' l='189' u='r' c='_ZN12_GLOBAL__N_112HardwareLoopC1ERN4llvm16HardwareLoopInfoERNS1_15ScalarEvolutionERKNS1_10DataLayoutEPNS1_25OptimizationRemarkEmitterE'/>
<use f='llvm/llvm/lib/CodeGen/HardwareLoops.cpp' l='288' u='r' c='_ZN12_GLOBAL__N_113HardwareLoops14TryConvertLoopERN4llvm16HardwareLoopInfoE'/>
