<use f='llvm/llvm/include/llvm/Analysis/LazyCallGraph.h' l='324' u='r' c='_ZNK4llvm13LazyCallGraph4Node8getGraphEv'/>
<use f='llvm/llvm/include/llvm/Analysis/LazyCallGraph.h' l='345' u='r' c='_ZNK4llvm13LazyCallGraph4Node6isDeadEv'/>
<dec f='llvm/llvm/include/llvm/Analysis/LazyCallGraph.h' l='376' type='llvm::LazyCallGraph *'/>
<use f='llvm/llvm/include/llvm/Analysis/LazyCallGraph.h' l='389' u='w' c='_ZN4llvm13LazyCallGraph4NodeC1ERS0_RNS_8FunctionE'/>
<offset>0</offset>
<use f='llvm/llvm/lib/Analysis/LazyCallGraph.cpp' l='108' u='r' c='_ZN4llvm13LazyCallGraph4Node12populateSlowEv'/>
<use f='llvm/llvm/lib/Analysis/LazyCallGraph.cpp' l='122' u='r' c='_ZN4llvm13LazyCallGraph4Node12populateSlowEv'/>
<use f='llvm/llvm/lib/Analysis/LazyCallGraph.cpp' l='128' u='r' c='_ZN4llvm13LazyCallGraph4Node12populateSlowEv'/>
<use f='llvm/llvm/lib/Analysis/LazyCallGraph.cpp' l='130' u='r' c='_ZN4llvm13LazyCallGraph4Node12populateSlowEv'/>
<use f='llvm/llvm/lib/Analysis/LazyCallGraph.cpp' l='1579' u='w' c='_ZN4llvm13LazyCallGraph18removeDeadFunctionERNS_8FunctionE'/>
<use f='llvm/llvm/lib/Analysis/LazyCallGraph.cpp' l='1806' u='w' c='_ZN4llvm13LazyCallGraph15updateGraphPtrsEv'/>
