<dec f='llvm/llvm/tools/llvm-rc/ResourceScriptStmt.h' l='612' type='uint32_t'/>
<use f='llvm/llvm/tools/llvm-rc/ResourceScriptStmt.h' l='640' u='w' c='_ZN4llvm2rc7ControlC1ENS_9StringRefENS0_11IntOrStringEjjjjjNS_8OptionalINS0_14IntWithNotMaskEEENS4_IjEES7_S3_'/>
<use f='llvm/llvm/tools/llvm-rc/ResourceFileWriter.cpp' l='1015' u='r' c='_ZN4llvm2rc18ResourceFileWriter24writeSingleDialogControlERKNS0_7ControlEb'/>
<use f='llvm/llvm/tools/llvm-rc/ResourceFileWriter.cpp' l='1025' u='r' c='_ZN4llvm2rc18ResourceFileWriter24writeSingleDialogControlERKNS0_7ControlEb'/>
<offset>384</offset>
<use f='llvm/llvm/tools/llvm-rc/ResourceScriptStmt.cpp' l='154' u='r' c='_ZNK4llvm2rc7Control3logERNS_11raw_ostreamE'/>
