<use f='llvm/llvm/include/llvm/ExecutionEngine/Orc/OrcRemoteTargetClient.h' l='790' u='a' c='_ZN4llvm3orc6remote21OrcRemoteTargetClient22enableCompileCallbacksEm'/>
<use f='llvm/llvm/include/llvm/ExecutionEngine/Orc/OrcRemoteTargetClient.h' l='812' u='w' c='_ZN4llvm3orc6remote21OrcRemoteTargetClientC1ERNS0_6shared14RawByteChannelERNS0_16ExecutionSessionERNS_5ErrorE'/>
<use f='llvm/llvm/include/llvm/ExecutionEngine/Orc/OrcRemoteTargetClient.h' l='832' u='m' c='_ZN4llvm3orc6remote21OrcRemoteTargetClient18deregisterEHFramesEmj'/>
<use f='llvm/llvm/include/llvm/ExecutionEngine/Orc/OrcRemoteTargetClient.h' l='847' u='m' c='_ZN4llvm3orc6remote21OrcRemoteTargetClient27destroyIndirectStubsManagerEm'/>
<use f='llvm/llvm/include/llvm/ExecutionEngine/Orc/OrcRemoteTargetClient.h' l='880' u='m' c='_ZN4llvm3orc6remote21OrcRemoteTargetClient10reserveMemEmmj'/>
<use f='llvm/llvm/include/llvm/ExecutionEngine/Orc/OrcRemoteTargetClient.h' l='888' u='m' c='_ZN4llvm3orc6remote21OrcRemoteTargetClient14setProtectionsEmmj'/>
<use f='llvm/llvm/include/llvm/ExecutionEngine/Orc/OrcRemoteTargetClient.h' l='896' u='m' c='_ZN4llvm3orc6remote21OrcRemoteTargetClient8writeMemEmPKcm'/>
<dec f='llvm/llvm/include/llvm/ExecutionEngine/Orc/OrcRemoteTargetClient.h' l='908' type='llvm::orc::ExecutionSession &amp;'/>
<offset>2624</offset>
