<use f='llvm/llvm/lib/Target/AMDGPU/AMDGPU.h' l='142' u='w' c='_ZN4llvm33AMDGPUPropagateAttributesLatePassC1ERNS_13TargetMachineE'/>
<dec f='llvm/llvm/lib/Target/AMDGPU/AMDGPU.h' l='146' type='llvm::TargetMachine &amp;'/>
<offset>0</offset>
<use f='llvm/llvm/lib/Target/AMDGPU/AMDGPUPropagateAttributes.cpp' l='423' u='a' c='_ZN4llvm33AMDGPUPropagateAttributesLatePass3runERNS_6ModuleERNS_15AnalysisManagerIS1_JEEE'/>
