<use f='llvm/llvm/lib/ExecutionEngine/Orc/Core.cpp' l='523' u='w' c='_ZN4llvm3orc25InProgressFullLookupStateC1ENS0_10LookupKindESt6vectorISt4pairIPNS0_8JITDylibENS0_19JITDylibLookupFlagsEESaIS8_EENS0_15SymbolLookupSetEN2288052'/>
<use f='llvm/llvm/lib/ExecutionEngine/Orc/Core.cpp' l='529' u='a' c='_ZN4llvm3orc25InProgressFullLookupState8completeESt10unique_ptrINS0_21InProgressLookupStateESt14default_deleteIS3_EE'/>
<use f='llvm/llvm/lib/ExecutionEngine/Orc/Core.cpp' l='535' u='m' c='_ZN4llvm3orc25InProgressFullLookupState4failENS_5ErrorE'/>
<use f='llvm/llvm/lib/ExecutionEngine/Orc/Core.cpp' l='536' u='m' c='_ZN4llvm3orc25InProgressFullLookupState4failENS_5ErrorE'/>
<dec f='llvm/llvm/lib/ExecutionEngine/Orc/Core.cpp' l='540' type='std::shared_ptr&lt;AsynchronousSymbolQuery&gt;'/>
<offset>1408</offset>
