<dec f='llvm/llvm/include/llvm/Support/Error.h' l='1196' type='std::error_code'/>
<offset>320</offset>
<use f='llvm/llvm/lib/Support/Error.cpp' l='117' u='w' c='_ZN4llvm11StringErrorC1ESt10error_codeRKNS_5TwineE'/>
<use f='llvm/llvm/lib/Support/Error.cpp' l='120' u='w' c='_ZN4llvm11StringErrorC1ERKNS_5TwineESt10error_code'/>
<use f='llvm/llvm/lib/Support/Error.cpp' l='126' u='m' c='_ZNK4llvm11StringError3logERNS_11raw_ostreamE'/>
<use f='llvm/llvm/lib/Support/Error.cpp' l='133' u='r' c='_ZNK4llvm11StringError18convertToErrorCodeEv'/>
