<dec f='llvm/llvm/include/llvm/CodeGen/MachineBasicBlock.h' l='1031' type='MachineBasicBlock::iterator'/>
<use f='llvm/llvm/include/llvm/CodeGen/MachineBasicBlock.h' l='1036' u='w' c='_ZN4llvm16MachineInstrSpanC1ENS_26MachineInstrBundleIteratorINS_12MachineInstrELb0EEEPNS_17MachineBasicBlockE'/>
<use f='llvm/llvm/include/llvm/CodeGen/MachineBasicBlock.h' l='1043' u='r' c='_ZN4llvm16MachineInstrSpan3endEv'/>
<offset>192</offset>
