<dec f='llvm/llvm/include/llvm/TableGen/Record.h' l='778' type='15'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='1000' c='_ZNK4llvm9BinOpInit4FoldEPNS_6RecordE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='1015' c='_ZNK4llvm9BinOpInit4FoldEPNS_6RecordE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='1033' c='_ZNK4llvm9BinOpInit4FoldEPNS_6RecordE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='1044' u='r' c='_ZNK4llvm9BinOpInit4FoldEPNS_6RecordE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='1128' c='_ZNK4llvm9BinOpInit11getAsStringB5cxx11Ev'/>
<use f='llvm/llvm/lib/TableGen/TGParser.cpp' l='1118' u='r' c='_ZN4llvm8TGParser14ParseOperationEPNS_6RecordEPNS_5RecTyE'/>
<use f='llvm/llvm/lib/TableGen/TGParser.cpp' l='1246' c='_ZN4llvm8TGParser14ParseOperationEPNS_6RecordEPNS_5RecTyE'/>
