<dec f='llvm/build/lib/Target/AVR/AVRGenRegisterInfo.inc' l='21' type='1'/>
<use f='llvm/llvm/lib/Target/AVR/AVRFrameLowering.cpp' l='105' u='r' c='_ZNK4llvm16AVRFrameLowering12emitPrologueERNS_15MachineFunctionERNS_17MachineBasicBlockE'/>
<use f='llvm/llvm/lib/Target/AVR/AVRFrameLowering.cpp' l='129' u='r' c='_ZNK4llvm16AVRFrameLowering12emitPrologueERNS_15MachineFunctionERNS_17MachineBasicBlockE'/>
<use f='llvm/llvm/lib/Target/AVR/AVRFrameLowering.cpp' l='210' u='r' c='_ZNK4llvm16AVRFrameLowering12emitEpilogueERNS_15MachineFunctionERNS_17MachineBasicBlockE'/>
<use f='llvm/llvm/lib/Target/AVR/AVRFrameLowering.cpp' l='357' u='r' c='_ZNK4llvm16AVRFrameLowering29eliminateCallFramePseudoInstrERNS_15MachineFunctionERNS_17MachineBasicBlockENS_26MachineInstrBundleIteratorINS_12MachineInstrELb0EEE'/>
<use f='llvm/llvm/lib/Target/AVR/AVRFrameLowering.cpp' l='364' u='r' c='_ZNK4llvm16AVRFrameLowering29eliminateCallFramePseudoInstrERNS_15MachineFunctionERNS_17MachineBasicBlockENS_26MachineInstrBundleIteratorINS_12MachineInstrELb0EEE'/>
<use f='llvm/llvm/lib/Target/AVR/AVRFrameLowering.cpp' l='387' u='r' c='_ZNK4llvm16AVRFrameLowering29eliminateCallFramePseudoInstrERNS_15MachineFunctionERNS_17MachineBasicBlockENS_26MachineInstrBundleIteratorINS_12MachineInstrELb0EEE'/>
<use f='llvm/llvm/lib/Target/AVR/AVRFrameLowering.cpp' l='394' u='r' c='_ZNK4llvm16AVRFrameLowering29eliminateCallFramePseudoInstrERNS_15MachineFunctionERNS_17MachineBasicBlockENS_26MachineInstrBundleIteratorINS_12MachineInstrELb0EEE'/>
<use f='llvm/llvm/lib/Target/AVR/AVRFrameLowering.cpp' l='506' u='r' c='_ZN4llvm14AVRDynAllocaSR20runOnMachineFunctionERNS_15MachineFunctionE'/>
<use f='llvm/llvm/lib/Target/AVR/AVRFrameLowering.cpp' l='514' u='r' c='_ZN4llvm14AVRDynAllocaSR20runOnMachineFunctionERNS_15MachineFunctionE'/>
<use f='llvm/llvm/lib/Target/AVR/AVRISelDAGToDAG.cpp' l='334' u='r' c='_ZN4llvm15AVRDAGToDAGISel6selectEPNS_6SDNodeE'/>
<use f='llvm/llvm/lib/Target/AVR/AVRISelLowering.cpp' l='48' u='r' c='_ZN4llvm17AVRTargetLoweringC1ERKNS_16AVRTargetMachineERKNS_12AVRSubtargetE'/>
<use f='llvm/llvm/lib/Target/AVR/AVRISelLowering.cpp' l='1287' u='r' c='_ZNK4llvm17AVRTargetLowering9LowerCallERNS_14TargetLowering16CallLoweringInfoERNS_15SmallVectorImplINS_7SDValueEEE'/>
<use f='llvm/llvm/lib/Target/AVR/AVRInstrInfo.cpp' l='69' u='r' c='_ZNK4llvm12AVRInstrInfo11copyPhysRegERNS_17MachineBasicBlockENS_26MachineInstrBundleIteratorINS_12MachineInstrELb0EEERKNS_8DebugLocENS_10MCRegisterES9_b'/>
<use f='llvm/llvm/lib/Target/AVR/AVRInstrInfo.cpp' l='71' u='r' c='_ZNK4llvm12AVRInstrInfo11copyPhysRegERNS_17MachineBasicBlockENS_26MachineInstrBundleIteratorINS_12MachineInstrELb0EEERKNS_8DebugLocENS_10MCRegisterES9_b'/>
<use f='llvm/llvm/lib/Target/AVR/AVRRegisterInfo.cpp' l='67' u='r' c='_ZNK4llvm15AVRRegisterInfo15getReservedRegsERKNS_15MachineFunctionE'/>
<use f='llvm/llvm/lib/Target/AVR/AVRRegisterInfo.cpp' l='259' u='r' c='_ZNK4llvm15AVRRegisterInfo16getFrameRegisterERKNS_15MachineFunctionE'/>
<use f='llvm/build/lib/Target/AVR/AVRGenAsmMatcher.inc' l='1041' c='_ZL20validateOperandClassRN4llvm18MCParsedAsmOperandEN12_GLOBAL__N_114MatchClassKindE'/>
