<dec f='llvm/build/lib/Target/X86/X86GenRegisterInfo.inc' l='22' type='2'/>
<use f='llvm/build/lib/Target/X86/X86GenAsmMatcher.inc' l='7187' c='_ZL20validateOperandClassRN4llvm18MCParsedAsmOperandEN12_GLOBAL__N_114MatchClassKindE'/>
<use f='llvm/llvm/lib/Target/X86/Disassembler/X86Disassembler.cpp' l='1773' macro='1' u='r' c='_ZL17translateRegisterRN4llvm6MCInstENS_15X86Disassembler3RegE'/>
<use f='llvm/llvm/lib/Target/X86/Disassembler/X86Disassembler.cpp' l='2010' macro='1' u='r' c='_ZL19translateRMRegisterRN4llvm6MCInstERNS_15X86Disassembler19InternalInstructionE'/>
<use f='llvm/llvm/lib/Target/X86/MCTargetDesc/X86MCTargetDesc.cpp' l='87' u='r' c='_ZN4llvm6X86_MC28initLLVMToSEHAndCVRegMappingEPNS_14MCRegisterInfoE'/>
<use f='llvm/llvm/lib/Target/X86/MCTargetDesc/X86MCTargetDesc.cpp' l='627' c='_ZN4llvm28getX86SubSuperRegisterOrZeroENS_10MCRegisterEjb'/>
<use f='llvm/llvm/lib/Target/X86/MCTargetDesc/X86MCTargetDesc.cpp' l='639' c='_ZN4llvm28getX86SubSuperRegisterOrZeroENS_10MCRegisterEjb'/>
<use f='llvm/llvm/lib/Target/X86/MCTargetDesc/X86MCTargetDesc.cpp' l='640' u='r' c='_ZN4llvm28getX86SubSuperRegisterOrZeroENS_10MCRegisterEjb'/>
<use f='llvm/llvm/lib/Target/X86/MCTargetDesc/X86MCTargetDesc.cpp' l='676' c='_ZN4llvm28getX86SubSuperRegisterOrZeroENS_10MCRegisterEjb'/>
<use f='llvm/llvm/lib/Target/X86/MCTargetDesc/X86MCTargetDesc.cpp' l='712' c='_ZN4llvm28getX86SubSuperRegisterOrZeroENS_10MCRegisterEjb'/>
<use f='llvm/llvm/lib/Target/X86/MCTargetDesc/X86MCTargetDesc.cpp' l='748' c='_ZN4llvm28getX86SubSuperRegisterOrZeroENS_10MCRegisterEjb'/>
<use f='llvm/llvm/lib/Target/X86/X86CallLowering.cpp' l='437' u='r' c='_ZNK4llvm15X86CallLowering9lowerCallERNS_16MachineIRBuilderERNS_12CallLowering16CallLoweringInfoE'/>
<use f='llvm/llvm/lib/Target/X86/X86CallLowering.cpp' l='439' u='r' c='_ZNK4llvm15X86CallLowering9lowerCallERNS_16MachineIRBuilderERNS_12CallLowering16CallLoweringInfoE'/>
<use f='llvm/build/lib/Target/X86/X86GenCallingConv.inc' l='2698' u='r' c='_ZL15RetCC_X86CommonjN4llvm3MVTES0_NS_11CCValAssign7LocInfoENS_3ISD10ArgFlagsTyERNS_7CCStateE'/>
<use f='llvm/build/lib/Target/X86/X86GenCallingConv.inc' l='2967' u='r' c='_ZL17RetCC_X86_32_FastjN4llvm3MVTES0_NS_11CCValAssign7LocInfoENS_3ISD10ArgFlagsTyERNS_7CCStateE'/>
<use f='llvm/build/lib/Target/X86/X86GenCallingConv.inc' l='3069' u='r' c='_ZL20RetCC_X86_32_RegCalljN4llvm3MVTES0_NS_11CCValAssign7LocInfoENS_3ISD10ArgFlagsTyERNS_7CCStateE'/>
<use f='llvm/build/lib/Target/X86/X86GenCallingConv.inc' l='3471' u='r' c='_ZL18RetCC_X86_64_SwiftjN4llvm3MVTES0_NS_11CCValAssign7LocInfoENS_3ISD10ArgFlagsTyERNS_7CCStateE'/>
<use f='llvm/build/lib/Target/X86/X86GenCallingConv.inc' l='3644' u='r' c='_ZL24RetCC_X86_SysV64_RegCalljN4llvm3MVTES0_NS_11CCValAssign7LocInfoENS_3ISD10ArgFlagsTyERNS_7CCStateE'/>
<use f='llvm/build/lib/Target/X86/X86GenCallingConv.inc' l='3858' u='r' c='_ZL23RetCC_X86_Win64_RegCalljN4llvm3MVTES0_NS_11CCValAssign7LocInfoENS_3ISD10ArgFlagsTyERNS_7CCStateE'/>
<use f='llvm/build/lib/Target/X86/X86GenFastISel.inc' l='7983' u='r' c='_ZN12_GLOBAL__N_111X86FastISel26fastEmit_ISD_MUL_MVT_i8_rrEN4llvm3MVTEjbjb'/>
<use f='llvm/llvm/lib/Target/X86/X86FastISel.cpp' l='1905' u='r' c='_ZN12_GLOBAL__N_111X86FastISel15X86SelectDivRemEPKN4llvm11InstructionE'/>
<use f='llvm/llvm/lib/Target/X86/X86FastISel.cpp' l='1907' u='r' c='_ZN12_GLOBAL__N_111X86FastISel15X86SelectDivRemEPKN4llvm11InstructionE'/>
<use f='llvm/llvm/lib/Target/X86/X86FastISel.cpp' l='2975' u='r' c='_ZN12_GLOBAL__N_111X86FastISel22fastLowerIntrinsicCallEPKN4llvm13IntrinsicInstE'/>
<use f='llvm/llvm/lib/Target/X86/X86FastISel.cpp' l='2990' u='r' c='_ZN12_GLOBAL__N_111X86FastISel22fastLowerIntrinsicCallEPKN4llvm13IntrinsicInstE'/>
<use f='llvm/llvm/lib/Target/X86/X86FastISel.cpp' l='3494' u='r' c='_ZN12_GLOBAL__N_111X86FastISel13fastLowerCallERN4llvm8FastISel16CallLoweringInfoE'/>
<use f='llvm/llvm/lib/Target/X86/X86FastISel.cpp' l='3554' u='r' c='_ZN12_GLOBAL__N_111X86FastISel13fastLowerCallERN4llvm8FastISel16CallLoweringInfoE'/>
<use f='llvm/llvm/lib/Target/X86/X86FixupBWInsts.cpp' l='356' u='r' c='_ZNK12_GLOBAL__N_115FixupBWInstPass16tryReplaceExtendEjPN4llvm12MachineInstrE'/>
<use f='llvm/llvm/lib/Target/X86/X86FrameLowering.cpp' l='157' u='r' c='_ZL11isEAXLiveInRN4llvm17MachineBasicBlockE'/>
<use f='llvm/build/lib/Target/X86/X86GenDAGISel.inc' l='34546' u='r' c='_ZN12_GLOBAL__N_115X86DAGToDAGISel10SelectCodeEPN4llvm6SDNodeE'/>
<use f='llvm/build/lib/Target/X86/X86GenDAGISel.inc' l='34710' u='r' c='_ZN12_GLOBAL__N_115X86DAGToDAGISel10SelectCodeEPN4llvm6SDNodeE'/>
<use f='llvm/llvm/lib/Target/X86/X86ISelDAGToDAG.cpp' l='4985' u='r' c='_ZN12_GLOBAL__N_115X86DAGToDAGISel6SelectEPN4llvm6SDNodeE'/>
<use f='llvm/llvm/lib/Target/X86/X86ISelDAGToDAG.cpp' l='5204' u='r' c='_ZN12_GLOBAL__N_115X86DAGToDAGISel6SelectEPN4llvm6SDNodeE'/>
<use f='llvm/llvm/lib/Target/X86/X86ISelLowering.cpp' l='3501' u='r' c='_ZN12_GLOBAL__N_121VarArgsLoweringHelper33createVarArgAreaAndStoreRegistersERN4llvm7SDValueEj'/>
<use f='llvm/llvm/lib/Target/X86/X86ISelLowering.cpp' l='3574' u='r' c='_ZN12_GLOBAL__N_121VarArgsLoweringHelper25forwardMustTailParametersERN4llvm7SDValueE'/>
<use f='llvm/llvm/lib/Target/X86/X86ISelLowering.cpp' l='3575' u='r' c='_ZN12_GLOBAL__N_121VarArgsLoweringHelper25forwardMustTailParametersERN4llvm7SDValueE'/>
<use f='llvm/llvm/lib/Target/X86/X86ISelLowering.cpp' l='3576' u='r' c='_ZN12_GLOBAL__N_121VarArgsLoweringHelper25forwardMustTailParametersERN4llvm7SDValueE'/>
<use f='llvm/llvm/lib/Target/X86/X86ISelLowering.cpp' l='4204' u='r' c='_ZNK4llvm17X86TargetLowering9LowerCallERNS_14TargetLowering16CallLoweringInfoERNS_15SmallVectorImplINS_7SDValueEEE'/>
<use f='llvm/llvm/lib/Target/X86/X86ISelLowering.cpp' l='28891' u='r' c='_ZL13LowerCMP_SWAPN4llvm7SDValueERKNS_12X86SubtargetERNS_12SelectionDAGE'/>
<use f='llvm/llvm/lib/Target/X86/X86InstructionSelector.cpp' l='1528' u='r' c='_ZNK12_GLOBAL__N_122X86InstructionSelector12selectDivRemERN4llvm12MachineInstrERNS1_19MachineRegisterInfoERNS1_15MachineFunctionE'/>
<use f='llvm/llvm/lib/Target/X86/X86InstructionSelector.cpp' l='1530' u='r' c='_ZNK12_GLOBAL__N_122X86InstructionSelector12selectDivRemERN4llvm12MachineInstrERNS1_19MachineRegisterInfoERNS1_15MachineFunctionE'/>
<use f='llvm/llvm/lib/Target/X86/X86MCInstLower.cpp' l='330' u='r' c='_ZL20SimplifyShortImmFormRN4llvm6MCInstEj'/>
<use f='llvm/llvm/lib/Target/X86/X86MCInstLower.cpp' l='349' u='r' c='_ZL13SimplifyMOVSXRN4llvm6MCInstE'/>
<use f='llvm/llvm/lib/Target/X86/X86MCInstLower.cpp' l='391' u='r' c='_ZL21SimplifyShortMoveFormRN4llvm13X86AsmPrinterERNS_6MCInstEj'/>
<use f='llvm/llvm/lib/Target/X86/X86SelectionDAGInfo.cpp' l='138' u='r' c='_ZNK4llvm19X86SelectionDAGInfo23EmitTargetCodeForMemsetERNS_12SelectionDAGERKNS_5SDLocENS_7SDValueES6_S6_S6_NS_5AlignEbNS_18MachinePointerInfoE'/>
<use f='llvm/llvm/lib/Target/X86/X86SelectionDAGInfo.cpp' l='154' u='r' c='_ZNK4llvm19X86SelectionDAGInfo23EmitTargetCodeForMemsetERNS_12SelectionDAGERKNS_5SDLocENS_7SDValueES6_S6_S6_NS_5AlignEbNS_18MachinePointerInfoE'/>
<use f='llvm/llvm/unittests/tools/llvm-exegesis/X86/BenchmarkResultTest.cpp' l='67' u='r' c='_ZN4llvm8exegesis12_GLOBAL__N_147BenchmarkResultTest_WriteToAndReadFromDisk_Test8TestBodyEv'/>
<use f='llvm/llvm/unittests/tools/llvm-exegesis/X86/BenchmarkResultTest.cpp' l='73' u='r' c='_ZN4llvm8exegesis12_GLOBAL__N_147BenchmarkResultTest_WriteToAndReadFromDisk_Test8TestBodyEv'/>
<use f='llvm/llvm/unittests/tools/llvm-exegesis/X86/RegisterAliasingTest.cpp' l='35' u='r' c='_ZN4llvm8exegesis12_GLOBAL__N_145RegisterAliasingTest_TrackSimpleRegister_Test8TestBodyEv'/>
<use f='llvm/llvm/unittests/tools/llvm-exegesis/X86/RegisterAliasingTest.cpp' l='52' u='r' c='_ZN4llvm8exegesis12_GLOBAL__N_144RegisterAliasingTest_TrackRegisterClass_Test8TestBodyEv'/>
<use f='llvm/llvm/unittests/tools/llvm-exegesis/X86/TargetTest.cpp' l='159' u='r' c='_ZN4llvm8exegesis12_GLOBAL__N_137Core2TargetTest_SetRegToGR8Value_Test8TestBodyEv'/>
