<use f='llvm/llvm/include/llvm/Support/Error.h' l='1110' u='w' c='_ZN4llvm7ECError12setErrorCodeESt10error_code'/>
<use f='llvm/llvm/include/llvm/Support/Error.h' l='1111' u='r' c='_ZNK4llvm7ECError18convertToErrorCodeEv'/>
<use f='llvm/llvm/include/llvm/Support/Error.h' l='1112' u='m' c='_ZNK4llvm7ECError3logERNS_11raw_ostreamE'/>
<use f='llvm/llvm/include/llvm/Support/Error.h' l='1119' u='w' c='_ZN4llvm7ECErrorC1ESt10error_code'/>
<dec f='llvm/llvm/include/llvm/Support/Error.h' l='1121' type='std::error_code'/>
<offset>64</offset>
