<dec f='llvm/llvm/lib/Target/AArch64/Utils/AArch64BaseInfo.h' l='236' type='0'/>
<use f='llvm/llvm/lib/Target/AArch64/Utils/AArch64BaseInfo.h' l='259'/>
<use f='llvm/llvm/lib/Target/AArch64/Utils/AArch64BaseInfo.h' l='265' c='_ZN4llvm9AArch64CCL15getCondCodeNameENS0_8CondCodeE'/>
<use f='llvm/llvm/lib/Target/AArch64/Utils/AArch64BaseInfo.h' l='299' c='_ZN4llvm9AArch64CCL24getNZCVToSatisfyCondCodeENS0_8CondCodeE'/>
<doc f='llvm/llvm/lib/Target/AArch64/Utils/AArch64BaseInfo.h' l='236'>// Equal                      Equal</doc>
<use f='llvm/llvm/lib/Target/AArch64/AArch64AsmPrinter.cpp' l='411' u='r' c='_ZN12_GLOBAL__N_117AArch64AsmPrinter26EmitHwasanMemaccessSymbolsERN4llvm6ModuleE'/>
<use f='llvm/llvm/lib/Target/AArch64/AArch64AsmPrinter.cpp' l='475' u='r' c='_ZN12_GLOBAL__N_117AArch64AsmPrinter26EmitHwasanMemaccessSymbolsERN4llvm6ModuleE'/>
<use f='llvm/llvm/lib/Target/AArch64/AArch64CondBrTuning.cpp' l='122' u='r' c='_ZN12_GLOBAL__N_119AArch64CondBrTuning15convertToCondBrERN4llvm12MachineInstrE'/>
<use f='llvm/llvm/lib/Target/AArch64/AArch64ConditionalCompares.cpp' l='289' u='r' c='_ZL9parseCondN4llvm8ArrayRefINS_14MachineOperandEEERNS_9AArch64CC8CondCodeE'/>
<use f='llvm/llvm/lib/Target/AArch64/AArch64ConditionalCompares.cpp' l='709' u='r' c='_ZN12_GLOBAL__N_111SSACCmpConv7convertERN4llvm15SmallVectorImplIPNS1_17MachineBasicBlockEEE'/>
<use f='llvm/llvm/lib/Target/AArch64/AArch64ExpandPseudoInsts.cpp' l='304' u='r' c='_ZN12_GLOBAL__N_119AArch64ExpandPseudo18expandCMP_SWAP_128ERN4llvm17MachineBasicBlockENS1_26MachineInstrBundleIteratorINS1_12MachineInstrELb0EEERS6_'/>
<use f='llvm/llvm/lib/Target/AArch64/AArch64ExpandPseudoInsts.cpp' l='312' u='r' c='_ZN12_GLOBAL__N_119AArch64ExpandPseudo18expandCMP_SWAP_128ERN4llvm17MachineBasicBlockENS1_26MachineInstrBundleIteratorINS1_12MachineInstrELb0EEERS6_'/>
<use f='llvm/llvm/lib/Target/AArch64/AArch64FastISel.cpp' l='2253' u='r' c='_ZL12getCompareCCN4llvm7CmpInst9PredicateE'/>
<use f='llvm/llvm/lib/Target/AArch64/AArch64FastISel.cpp' l='2466' u='r' c='_ZN12_GLOBAL__N_115AArch64FastISel12selectBranchEPKN4llvm11InstructionE'/>
<use f='llvm/llvm/lib/Target/AArch64/AArch64FastISel.cpp' l='2792' u='r' c='_ZN12_GLOBAL__N_115AArch64FastISel12selectSelectEPKN4llvm11InstructionE'/>
<use f='llvm/llvm/lib/Target/AArch64/AArch64ISelLowering.cpp' l='2107' u='r' c='_ZL22changeIntCCToAArch64CCN4llvm3ISD8CondCodeE'/>
<use f='llvm/llvm/lib/Target/AArch64/AArch64ISelLowering.cpp' l='2137' u='r' c='_ZL21changeFPCCToAArch64CCN4llvm3ISD8CondCodeERNS_9AArch64CC8CondCodeES4_'/>
<use f='llvm/llvm/lib/Target/AArch64/AArch64ISelLowering.cpp' l='2164' u='r' c='_ZL21changeFPCCToAArch64CCN4llvm3ISD8CondCodeERNS_9AArch64CC8CondCodeES4_'/>
<use f='llvm/llvm/lib/Target/AArch64/AArch64ISelLowering.cpp' l='6798' u='r' c='_ZNK4llvm21AArch64TargetLowering14LowerSELECT_CCENS_3ISD8CondCodeENS_7SDValueES3_S3_S3_RKNS_5SDLocERNS_12SelectionDAGE'/>
<use f='llvm/llvm/lib/Target/AArch64/AArch64ISelLowering.cpp' l='6807' u='r' c='_ZNK4llvm21AArch64TargetLowering14LowerSELECT_CCENS_3ISD8CondCodeENS_7SDValueES3_S3_S3_RKNS_5SDLocERNS_12SelectionDAGE'/>
<use f='llvm/llvm/lib/Target/AArch64/AArch64ISelLowering.cpp' l='7320' u='r' c='_ZNK4llvm21AArch64TargetLowering20LowerShiftRightPartsENS_7SDValueERNS_12SelectionDAGE'/>
<use f='llvm/llvm/lib/Target/AArch64/AArch64ISelLowering.cpp' l='7375' u='r' c='_ZNK4llvm21AArch64TargetLowering19LowerShiftLeftPartsENS_7SDValueERNS_12SelectionDAGE'/>
<use f='llvm/llvm/lib/Target/AArch64/AArch64ISelLowering.cpp' l='10199' c='_ZL20EmitVectorComparisonN4llvm7SDValueES0_NS_9AArch64CC8CondCodeEbNS_3EVTERKNS_5SDLocERNS_12SelectionDAGE'/>
<use f='llvm/llvm/lib/Target/AArch64/AArch64ISelLowering.cpp' l='10238' c='_ZL20EmitVectorComparisonN4llvm7SDValueES0_NS_9AArch64CC8CondCodeEbNS_3EVTERKNS_5SDLocERNS_12SelectionDAGE'/>
<use f='llvm/llvm/lib/Target/AArch64/AArch64ISelLowering.cpp' l='14747' c='_ZL20isEquivalentMasklessjjN4llvm3ISD11LoadExtTypeEii'/>
<use f='llvm/llvm/lib/Target/AArch64/AArch64ISelLowering.cpp' l='14863' u='r' c='_ZL20performBRCONDCombinePN4llvm6SDNodeERNS_14TargetLowering15DAGCombinerInfoERNS_12SelectionDAGE'/>
<use f='llvm/llvm/lib/Target/AArch64/AArch64ISelLowering.cpp' l='14895' u='r' c='_ZL20performBRCONDCombinePN4llvm6SDNodeERNS_14TargetLowering15DAGCombinerInfoERNS_12SelectionDAGE'/>
<use f='llvm/llvm/lib/Target/AArch64/AArch64InstrInfo.cpp' l='679' u='r' c='_ZNK4llvm16AArch64InstrInfo12insertSelectERNS_17MachineBasicBlockENS_26MachineInstrBundleIteratorINS_12MachineInstrELb0EEERKNS_8DebugLocENS_8RegisterE7312218'/>
<use f='llvm/llvm/lib/Target/AArch64/AArch64InstrInfo.cpp' l='683' u='r' c='_ZNK4llvm16AArch64InstrInfo12insertSelectERNS_17MachineBasicBlockENS_26MachineInstrBundleIteratorINS_12MachineInstrELb0EEERKNS_8DebugLocENS_8RegisterE7312218'/>
<use f='llvm/llvm/lib/Target/AArch64/AArch64InstrInfo.cpp' l='718' u='r' c='_ZNK4llvm16AArch64InstrInfo12insertSelectERNS_17MachineBasicBlockENS_26MachineInstrBundleIteratorINS_12MachineInstrELb0EEERKNS_8DebugLocENS_8RegisterE7312218'/>
<use f='llvm/llvm/lib/Target/AArch64/AArch64InstrInfo.cpp' l='1592' c='_ZL11getUsedNZCVN4llvm9AArch64CC8CondCodeE'/>
<use f='llvm/llvm/lib/Target/AArch64/AArch64RedundantCopyElimination.cpp' l='146' u='r' c='_ZN12_GLOBAL__N_131AArch64RedundantCopyElimination18knownRegValInBlockERN4llvm12MachineInstrEPNS1_17MachineBasicBlockERNS1_15SmallVectorImplINS0_6RegI8280297'/>
<use f='llvm/llvm/lib/Target/AArch64/AArch64RedundantCopyElimination.cpp' l='150' u='r' c='_ZN12_GLOBAL__N_131AArch64RedundantCopyElimination18knownRegValInBlockERN4llvm12MachineInstrEPNS1_17MachineBasicBlockERNS1_15SmallVectorImplINS0_6RegI8280297'/>
<use f='llvm/llvm/lib/Target/AArch64/AArch64SpeculationHardening.cpp' l='379' u='r' c='_ZNK12_GLOBAL__N_127AArch64SpeculationHardening29insertSPToRegTaintPropagationERN4llvm17MachineBasicBlockENS1_26MachineInstrBundleIteratorINS1_12MachineInstrELb0EEE'/>
<use f='llvm/llvm/lib/Target/AArch64/AsmParser/AArch64AsmParser.cpp' l='2753' u='r' c='_ZN12_GLOBAL__N_116AArch64AsmParser19parseCondCodeStringEN4llvm9StringRefE'/>
<use f='llvm/llvm/lib/Target/AArch64/AsmParser/AArch64AsmParser.cpp' l='2776' u='r' c='_ZN12_GLOBAL__N_116AArch64AsmParser19parseCondCodeStringEN4llvm9StringRefE'/>
<use f='llvm/llvm/lib/Target/AArch64/GISel/AArch64InstructionSelector.cpp' l='1191' u='r' c='_ZL25changeICMPPredToAArch64CCN4llvm7CmpInst9PredicateE'/>
<use f='llvm/llvm/lib/Target/AArch64/GISel/AArch64InstructionSelector.cpp' l='1219' u='r' c='_ZL25changeFCMPPredToAArch64CCN4llvm7CmpInst9PredicateERNS_9AArch64CC8CondCodeES4_'/>
<use f='llvm/llvm/lib/Target/AArch64/GISel/AArch64InstructionSelector.cpp' l='1244' u='r' c='_ZL25changeFCMPPredToAArch64CCN4llvm7CmpInst9PredicateERNS_9AArch64CC8CondCodeES4_'/>
<use f='llvm/llvm/lib/Target/AArch64/GISel/AArch64InstructionSelector.cpp' l='1640' u='r' c='_ZNK12_GLOBAL__N_126AArch64InstructionSelector19selectCompareBranchERN4llvm12MachineInstrERNS1_15MachineFunctionERNS1_19MachineRegisterInfoE'/>
<use f='llvm/llvm/lib/Target/AArch64/GISel/AArch64InstructionSelector.cpp' l='4499' u='r' c='_ZNK12_GLOBAL__N_126AArch64InstructionSelector21tryFoldIntegerCompareERN4llvm14MachineOperandES3_S3_RNS1_16MachineIRBuilderE'/>
