<dec f='llvm/llvm/include/llvm/Analysis/IVUsers.h' l='95' type='llvm::Loop *'/>
<use f='llvm/llvm/include/llvm/Analysis/IVUsers.h' l='114' u='w' c='_ZN4llvm7IVUsersC1EOS0_'/>
<use f='llvm/llvm/include/llvm/Analysis/IVUsers.h' l='114' u='a' c='_ZN4llvm7IVUsersC1EOS0_'/>
<use f='llvm/llvm/include/llvm/Analysis/IVUsers.h' l='124' u='r' c='_ZNK4llvm7IVUsers7getLoopEv'/>
<use f='llvm/llvm/lib/Analysis/IVUsers.cpp' l='203' u='r' c='_ZN4llvm7IVUsers12AddUsersImplEPNS_11InstructionERNS_15SmallPtrSetImplIPNS_4LoopEEE'/>
<use f='llvm/llvm/lib/Analysis/IVUsers.cpp' l='235' u='r' c='_ZN4llvm7IVUsers12AddUsersImplEPNS_11InstructionERNS_15SmallPtrSetImplIPNS_4LoopEEE'/>
<use f='llvm/llvm/lib/Analysis/IVUsers.cpp' l='307' u='w' c='_ZN4llvm7IVUsersC1EPNS_4LoopEPNS_15AssumptionCacheEPNS_8LoopInfoEPNS_13DominatorTreeEPNS_15ScalarEvolutionE'/>
<use f='llvm/llvm/lib/Analysis/IVUsers.cpp' l='321' u='r' c='_ZNK4llvm7IVUsers5printERNS_11raw_ostreamEPKNS_6ModuleE'/>
<use f='llvm/llvm/lib/Analysis/IVUsers.cpp' l='322' u='r' c='_ZNK4llvm7IVUsers5printERNS_11raw_ostreamEPKNS_6ModuleE'/>
<use f='llvm/llvm/lib/Analysis/IVUsers.cpp' l='323' u='r' c='_ZNK4llvm7IVUsers5printERNS_11raw_ostreamEPKNS_6ModuleE'/>
<offset>0</offset>
