<dec f='llvm/clang/unittests/CodeGen/TestCompiler.h' l='30' type='std::unique_ptr&lt;clang::CodeGenerator&gt;'/>
<use f='llvm/clang/unittests/CodeGen/TestCompiler.h' l='59' u='m' c='_ZN4llvm12TestCompilerC1EN5clang11LangOptionsENS1_14CodeGenOptionsE'/>
<use f='llvm/clang/unittests/CodeGen/TestCompiler.h' l='70' u='a' c='_ZN4llvm12TestCompiler4initEPKcSt10unique_ptrIN5clang11ASTConsumerESt14default_deleteIS5_EE'/>
<offset>2752</offset>
<use f='llvm/clang/unittests/CodeGen/CodeGenExternalTest.cpp' l='267' u='a' c='_ZN12_GLOBAL__N_144CodeGenExternalTest_CodeGenExternalTest_Test8TestBodyEv'/>
<use f='llvm/clang/unittests/CodeGen/IncrementalProcessingTest.cpp' l='119' u='a' c='_ZN12_GLOBAL__N_148IncrementalProcessing_EmitCXXGlobalInitFunc_Test8TestBodyEv'/>
