<use f='llvm/llvm/include/llvm/CodeGen/ModuloSchedule.h' l='283' u='w' c='_ZN4llvm29PeelingModuloScheduleExpanderC1ERNS_15MachineFunctionERNS_14ModuloScheduleEPNS_13LiveIntervalsE'/>
<use f='llvm/llvm/include/llvm/CodeGen/ModuloSchedule.h' l='284' u='m' c='_ZN4llvm29PeelingModuloScheduleExpanderC1ERNS_15MachineFunctionERNS_14ModuloScheduleEPNS_13LiveIntervalsE'/>
<dec f='llvm/llvm/include/llvm/CodeGen/ModuloSchedule.h' l='295' type='const llvm::TargetSubtargetInfo &amp;'/>
<offset>128</offset>
