<dec f='llvm/llvm/include/llvm/DebugInfo/GSYM/FileWriter.h' l='30' type='llvm::raw_pwrite_stream &amp;'/>
<use f='llvm/llvm/include/llvm/DebugInfo/GSYM/FileWriter.h' l='34' u='w' c='_ZN4llvm4gsym10FileWriterC1ERNS_17raw_pwrite_streamENS_7support10endiannessE'/>
<use f='llvm/llvm/include/llvm/DebugInfo/GSYM/FileWriter.h' l='113' u='a' c='_ZN4llvm4gsym10FileWriter10get_streamEv'/>
<use f='llvm/llvm/lib/DebugInfo/GSYM/FileWriter.cpp' l='18' u='m' c='_ZN4llvm4gsym10FileWriterD1Ev'/>
<use f='llvm/llvm/lib/DebugInfo/GSYM/FileWriter.cpp' l='24' u='m' c='_ZN4llvm4gsym10FileWriter9writeSLEBEl'/>
<use f='llvm/llvm/lib/DebugInfo/GSYM/FileWriter.cpp' l='31' u='m' c='_ZN4llvm4gsym10FileWriter9writeULEBEm'/>
<use f='llvm/llvm/lib/DebugInfo/GSYM/FileWriter.cpp' l='35' u='m' c='_ZN4llvm4gsym10FileWriter7writeU8Eh'/>
<use f='llvm/llvm/lib/DebugInfo/GSYM/FileWriter.cpp' l='40' u='m' c='_ZN4llvm4gsym10FileWriter8writeU16Et'/>
<use f='llvm/llvm/lib/DebugInfo/GSYM/FileWriter.cpp' l='45' u='m' c='_ZN4llvm4gsym10FileWriter8writeU32Ej'/>
<use f='llvm/llvm/lib/DebugInfo/GSYM/FileWriter.cpp' l='50' u='m' c='_ZN4llvm4gsym10FileWriter8writeU64Em'/>
<use f='llvm/llvm/lib/DebugInfo/GSYM/FileWriter.cpp' l='55' u='m' c='_ZN4llvm4gsym10FileWriter7fixup32Ejm'/>
<use f='llvm/llvm/lib/DebugInfo/GSYM/FileWriter.cpp' l='60' u='m' c='_ZN4llvm4gsym10FileWriter9writeDataENS_8ArrayRefIhEE'/>
<use f='llvm/llvm/lib/DebugInfo/GSYM/FileWriter.cpp' l='64' u='m' c='_ZN4llvm4gsym10FileWriter19writeNullTerminatedENS_9StringRefE'/>
<use f='llvm/llvm/lib/DebugInfo/GSYM/FileWriter.cpp' l='68' u='m' c='_ZN4llvm4gsym10FileWriter4tellEv'/>
<use f='llvm/llvm/lib/DebugInfo/GSYM/FileWriter.cpp' l='72' u='m' c='_ZN4llvm4gsym10FileWriter7alignToEm'/>
<use f='llvm/llvm/lib/DebugInfo/GSYM/FileWriter.cpp' l='77' u='m' c='_ZN4llvm4gsym10FileWriter7alignToEm'/>
<offset>0</offset>
