<dec f='llvm/llvm/include/llvm/DebugInfo/CodeView/CodeView.h' l='445' type='256'/>
<use f='llvm/llvm/lib/DebugInfo/CodeView/EnumTables.cpp' l='111'/>
<use f='llvm/llvm/tools/llvm-pdbutil/MinimalSymbolDumper.cpp' l='70' u='r' c='_ZL22formatCompileSym2FlagsB5cxx11jN4llvm8codeview16CompileSym2FlagsE'/>
<use f='llvm/llvm/tools/llvm-pdbutil/MinimalSymbolDumper.cpp' l='70' u='r' c='_ZL22formatCompileSym2FlagsB5cxx11jN4llvm8codeview16CompileSym2FlagsE'/>
