<dec f='llvm/llvm/lib/Target/X86/ImmutableGraph.h' l='113' type='llvm::BitVector'/>
<use f='llvm/llvm/lib/Target/X86/ImmutableGraph.h' l='117' u='w' c='_ZN4llvm14ImmutableGraph7NodeSetC1ERKNS_14ImmutableGraphIT_T0_EEb'/>
<use f='llvm/llvm/lib/Target/X86/ImmutableGraph.h' l='120' u='m' c='_ZN4llvm14ImmutableGraph7NodeSet6insertERKNS0_4NodeE'/>
<use f='llvm/llvm/lib/Target/X86/ImmutableGraph.h' l='121' u='m' c='_ZN4llvm14ImmutableGraph7NodeSet6insertERKNS0_4NodeE'/>
<use f='llvm/llvm/lib/Target/X86/ImmutableGraph.h' l='126' u='m' c='_ZN4llvm14ImmutableGraph7NodeSet5eraseERKNS0_4NodeE'/>
<use f='llvm/llvm/lib/Target/X86/ImmutableGraph.h' l='130' u='m' c='_ZNK4llvm14ImmutableGraph7NodeSet8containsERKNS0_4NodeE'/>
<use f='llvm/llvm/lib/Target/X86/ImmutableGraph.h' l='132' u='m' c='_ZN4llvm14ImmutableGraph7NodeSet5clearEv'/>
<use f='llvm/llvm/lib/Target/X86/ImmutableGraph.h' l='133' u='m' c='_ZNK4llvm14ImmutableGraph7NodeSet5emptyEv'/>
<use f='llvm/llvm/lib/Target/X86/ImmutableGraph.h' l='135' u='m' c='_ZNK4llvm14ImmutableGraph7NodeSet5countEv'/>
<use f='llvm/llvm/lib/Target/X86/ImmutableGraph.h' l='137' u='m' c='_ZNK4llvm14ImmutableGraph7NodeSet4sizeEv'/>
<use f='llvm/llvm/lib/Target/X86/ImmutableGraph.h' l='141' u='w' c='_ZN4llvm14ImmutableGraph7NodeSetoRERKS1_'/>
<use f='llvm/llvm/lib/Target/X86/ImmutableGraph.h' l='147' u='w' c='_ZN4llvm14ImmutableGraph7NodeSetaNERKS1_'/>
<use f='llvm/llvm/lib/Target/X86/ImmutableGraph.h' l='153' u='w' c='_ZN4llvm14ImmutableGraph7NodeSeteOERKS1_'/>
<use f='llvm/llvm/lib/Target/X86/ImmutableGraph.h' l='158' u='m' c='_ZNK4llvm14ImmutableGraph7NodeSet11index_beginEv'/>
<use f='llvm/llvm/lib/Target/X86/ImmutableGraph.h' l='159' u='m' c='_ZNK4llvm14ImmutableGraph7NodeSet9index_endEv'/>
<use f='llvm/llvm/lib/Target/X86/ImmutableGraph.h' l='160' u='m' c='_ZN4llvm14ImmutableGraph7NodeSet3setEi'/>
<use f='llvm/llvm/lib/Target/X86/ImmutableGraph.h' l='161' u='m' c='_ZN4llvm14ImmutableGraph7NodeSet5resetEi'/>
<use f='llvm/llvm/lib/Target/X86/ImmutableGraph.h' l='195' u='m' c='_ZNK4llvm14ImmutableGraph7NodeSet5beginEv'/>
