<dec f='llvm/llvm/include/llvm/CodeGen/ScheduleDAGInstrs.h' l='145' type='llvm::MachineBasicBlock *'/>
<offset>7360</offset>
<doc f='llvm/llvm/include/llvm/CodeGen/ScheduleDAGInstrs.h' l='141'>// State specific to the current scheduling region.
    // ------------------------------------------------

    /// The block in which to insert instructions</doc>
<use f='llvm/llvm/lib/CodeGen/MachinePipeliner.cpp' l='1676' u='r' c='_ZN4llvm17SwingSchedulerDAG22registerPressureFilterERNS_11SmallVectorINS_7NodeSetELj8EEE'/>
<use f='llvm/llvm/lib/CodeGen/MachinePipeliner.cpp' l='1676' u='r' c='_ZN4llvm17SwingSchedulerDAG22registerPressureFilterERNS_11SmallVectorINS_7NodeSetELj8EEE'/>
<use f='llvm/llvm/lib/CodeGen/MachinePipeliner.cpp' l='2289' u='r' c='_ZN4llvm17SwingSchedulerDAG13findDefInLoopENS_8RegisterE'/>
<use f='llvm/llvm/lib/CodeGen/MachinePipeliner.cpp' l='2355' u='r' c='_ZN4llvm17SwingSchedulerDAG16isLoopCarriedDepEPNS_5SUnitERKNS_4SDepEb'/>
<use f='llvm/llvm/lib/CodeGen/MachineScheduler.cpp' l='740' u='r' c='_ZN4llvm13ScheduleDAGMI15moveInstructionEPNS_12MachineInstrENS_26MachineInstrBundleIteratorIS1_Lb0EEE'/>
<use f='llvm/llvm/lib/CodeGen/MachineScheduler.cpp' l='740' u='r' c='_ZN4llvm13ScheduleDAGMI15moveInstructionEPNS_12MachineInstrENS_26MachineInstrBundleIteratorIS1_Lb0EEE'/>
<use f='llvm/llvm/lib/CodeGen/MachineScheduler.cpp' l='909' u='r' c='_ZN4llvm13ScheduleDAGMI16placeDebugValuesEv'/>
<use f='llvm/llvm/lib/CodeGen/MachineScheduler.cpp' l='909' u='r' c='_ZN4llvm13ScheduleDAGMI16placeDebugValuesEv'/>
<use f='llvm/llvm/lib/CodeGen/MachineScheduler.cpp' l='920' u='r' c='_ZN4llvm13ScheduleDAGMI16placeDebugValuesEv'/>
<use f='llvm/llvm/lib/CodeGen/MachineScheduler.cpp' l='920' u='r' c='_ZN4llvm13ScheduleDAGMI16placeDebugValuesEv'/>
<use f='llvm/llvm/lib/CodeGen/MachineScheduler.cpp' l='1018' u='r' c='_ZN4llvm17ScheduleDAGMILive15initRegPressureEv'/>
<use f='llvm/llvm/lib/CodeGen/MachineScheduler.cpp' l='1020' u='r' c='_ZN4llvm17ScheduleDAGMILive15initRegPressureEv'/>
<use f='llvm/llvm/lib/CodeGen/MachineScheduler.cpp' l='1153' u='r' c='_ZN4llvm17ScheduleDAGMILive19updatePressureDiffsENS_8ArrayRefINS_16RegisterMaskPairEEE'/>
<use f='llvm/llvm/lib/CodeGen/MachineScheduler.cpp' l='1154' u='r' c='_ZN4llvm17ScheduleDAGMILive19updatePressureDiffsENS_8ArrayRefINS_16RegisterMaskPairEEE'/>
<use f='llvm/llvm/lib/CodeGen/MachineScheduler.cpp' l='1155' u='r' c='_ZN4llvm17ScheduleDAGMILive19updatePressureDiffsENS_8ArrayRefINS_16RegisterMaskPairEEE'/>
<use f='llvm/llvm/lib/CodeGen/MachineScheduler.cpp' l='1285' u='r' c='_ZN4llvm17ScheduleDAGMILive23buildDAGWithRegPressureEv'/>
<use f='llvm/llvm/lib/CodeGen/MachineScheduler.cpp' l='1337' u='r' c='_ZN4llvm17ScheduleDAGMILive25computeCyclicCriticalPathEv'/>
<use f='llvm/llvm/lib/CodeGen/MachineScheduler.cpp' l='1337' u='r' c='_ZN4llvm17ScheduleDAGMILive25computeCyclicCriticalPathEv'/>
<use f='llvm/llvm/lib/CodeGen/MachineScheduler.cpp' l='1347' u='r' c='_ZN4llvm17ScheduleDAGMILive25computeCyclicCriticalPathEv'/>
<use f='llvm/llvm/lib/CodeGen/PostRASchedulerList.cpp' l='675' u='r' c='_ZN12_GLOBAL__N_120SchedulePostRATDList12EmitScheduleEv'/>
<use f='llvm/llvm/lib/CodeGen/PostRASchedulerList.cpp' l='675' u='r' c='_ZN12_GLOBAL__N_120SchedulePostRATDList12EmitScheduleEv'/>
<use f='llvm/llvm/lib/CodeGen/PostRASchedulerList.cpp' l='680' u='r' c='_ZN12_GLOBAL__N_120SchedulePostRATDList12EmitScheduleEv'/>
<use f='llvm/llvm/lib/CodeGen/PostRASchedulerList.cpp' l='680' u='r' c='_ZN12_GLOBAL__N_120SchedulePostRATDList12EmitScheduleEv'/>
<use f='llvm/llvm/lib/CodeGen/PostRASchedulerList.cpp' l='683' u='r' c='_ZN12_GLOBAL__N_120SchedulePostRATDList12EmitScheduleEv'/>
<use f='llvm/llvm/lib/CodeGen/PostRASchedulerList.cpp' l='697' u='r' c='_ZN12_GLOBAL__N_120SchedulePostRATDList12EmitScheduleEv'/>
<use f='llvm/llvm/lib/CodeGen/PostRASchedulerList.cpp' l='697' u='r' c='_ZN12_GLOBAL__N_120SchedulePostRATDList12EmitScheduleEv'/>
<use f='llvm/llvm/lib/CodeGen/ScheduleDAGInstrs.cpp' l='179' u='w' c='_ZN4llvm17ScheduleDAGInstrs10startBlockEPNS_17MachineBasicBlockE'/>
<use f='llvm/llvm/lib/CodeGen/ScheduleDAGInstrs.cpp' l='184' u='w' c='_ZN4llvm17ScheduleDAGInstrs11finishBlockEv'/>
<use f='llvm/llvm/lib/CodeGen/ScheduleDAGInstrs.cpp' l='203' u='r' c='_ZN4llvm17ScheduleDAGInstrs19addSchedBarrierDepsEv'/>
<use f='llvm/llvm/lib/CodeGen/ScheduleDAGInstrs.cpp' l='222' u='r' c='_ZN4llvm17ScheduleDAGInstrs19addSchedBarrierDepsEv'/>
<use f='llvm/llvm/lib/CodeGen/ScheduleDAGInstrs.cpp' l='1197' u='r' c='_ZNK4llvm17ScheduleDAGInstrs10getDAGNameB5cxx11Ev'/>
<use f='llvm/llvm/lib/Target/AMDGPU/SIMachineScheduler.h' l='446' u='r' c='_ZN4llvm15SIScheduleDAGMI13initRPTrackerERNS_18RegPressureTrackerE'/>
<use f='llvm/llvm/lib/Target/AMDGPU/SIMachineScheduler.h' l='449' u='r' c='_ZN4llvm15SIScheduleDAGMI5getBBEv'/>
<use f='llvm/llvm/lib/Target/AMDGPU/GCNSchedStrategy.cpp' l='395' u='r' c='_ZN4llvm20GCNScheduleDAGMILive8scheduleEv'/>
<use f='llvm/llvm/lib/Target/AMDGPU/GCNSchedStrategy.cpp' l='396' u='r' c='_ZN4llvm20GCNScheduleDAGMILive8scheduleEv'/>
<use f='llvm/llvm/lib/Target/Hexagon/HexagonMachineScheduler.h' l='100' u='r' c='_ZN4llvm20VLIWMachineScheduler9getBBSizeEv'/>
