<dec f='llvm/llvm/include/llvm/CodeGen/IntrinsicLowering.h' l='25' type='const llvm::DataLayout &amp;'/>
<use f='llvm/llvm/include/llvm/CodeGen/IntrinsicLowering.h' l='30' u='w' c='_ZN4llvm17IntrinsicLoweringC1ERKNS_10DataLayoutE'/>
<use f='llvm/llvm/lib/CodeGen/IntrinsicLowering.cpp' l='337' u='m' c='_ZN4llvm17IntrinsicLowering18LowerIntrinsicCallEPNS_8CallInstE'/>
<use f='llvm/llvm/lib/CodeGen/IntrinsicLowering.cpp' l='348' u='m' c='_ZN4llvm17IntrinsicLowering18LowerIntrinsicCallEPNS_8CallInstE'/>
<use f='llvm/llvm/lib/CodeGen/IntrinsicLowering.cpp' l='360' u='m' c='_ZN4llvm17IntrinsicLowering18LowerIntrinsicCallEPNS_8CallInstE'/>
<offset>0</offset>
