<dec f='llvm/llvm/include/llvm/CodeGen/GlobalISel/LegalizerInfo.h' l='340' type='llvm::LegalizeActions::LegalizeAction'/>
<use f='llvm/llvm/include/llvm/CodeGen/GlobalISel/LegalizerInfo.h' l='346' u='w' c='_ZN4llvm12LegalizeRuleC1ESt8functionIFbRKNS_13LegalityQueryEEENS_15LegalizeActions14LegalizeActionES1_IFSt4pairIjNS_3LLTEES4_EE'/>
<use f='llvm/llvm/include/llvm/CodeGen/GlobalISel/LegalizerInfo.h' l='353' u='r' c='_ZNK4llvm12LegalizeRule9getActionEv'/>
<offset>256</offset>
