<dec f='llvm/llvm/include/llvm/Remarks/RemarkSerializer.h' l='66' type='llvm::raw_ostream &amp;'/>
<use f='llvm/llvm/include/llvm/Remarks/RemarkSerializer.h' l='68' u='w' c='_ZN4llvm7remarks14MetaSerializerC1ERNS_11raw_ostreamE'/>
<offset>64</offset>
<doc f='llvm/llvm/include/llvm/Remarks/RemarkSerializer.h' l='65'>/// The open raw_ostream that the metadata is emitted to.</doc>
<use f='llvm/llvm/lib/Remarks/BitstreamRemarkSerializer.cpp' l='385' u='a' c='_ZN4llvm7remarks23BitstreamMetaSerializer4emitEv'/>
<use f='llvm/llvm/lib/Remarks/YAMLRemarkSerializer.cpp' l='244' u='a' c='_ZN4llvm7remarks18YAMLMetaSerializer4emitEv'/>
<use f='llvm/llvm/lib/Remarks/YAMLRemarkSerializer.cpp' l='245' u='a' c='_ZN4llvm7remarks18YAMLMetaSerializer4emitEv'/>
<use f='llvm/llvm/lib/Remarks/YAMLRemarkSerializer.cpp' l='246' u='a' c='_ZN4llvm7remarks18YAMLMetaSerializer4emitEv'/>
<use f='llvm/llvm/lib/Remarks/YAMLRemarkSerializer.cpp' l='248' u='a' c='_ZN4llvm7remarks18YAMLMetaSerializer4emitEv'/>
<use f='llvm/llvm/lib/Remarks/YAMLRemarkSerializer.cpp' l='252' u='a' c='_ZN4llvm7remarks24YAMLStrTabMetaSerializer4emitEv'/>
<use f='llvm/llvm/lib/Remarks/YAMLRemarkSerializer.cpp' l='253' u='a' c='_ZN4llvm7remarks24YAMLStrTabMetaSerializer4emitEv'/>
<use f='llvm/llvm/lib/Remarks/YAMLRemarkSerializer.cpp' l='254' u='a' c='_ZN4llvm7remarks24YAMLStrTabMetaSerializer4emitEv'/>
<use f='llvm/llvm/lib/Remarks/YAMLRemarkSerializer.cpp' l='256' u='a' c='_ZN4llvm7remarks24YAMLStrTabMetaSerializer4emitEv'/>
