<dec f='llvm/llvm/include/llvm/Analysis/MemoryBuiltins.h' l='300' type='llvm::ObjectSizeOffsetEvaluator::BuilderTy'/>
<offset>192</offset>
<use f='llvm/llvm/lib/Analysis/MemoryBuiltins.cpp' l='863' u='w' c='_ZN4llvm25ObjectSizeOffsetEvaluatorC1ERKNS_10DataLayoutEPKNS_17TargetLibraryInfoERNS_11LLVMContextENS_14ObjectSizeOptsE'/>
<use f='llvm/llvm/lib/Analysis/MemoryBuiltins.cpp' l='917' u='a' c='_ZN4llvm25ObjectSizeOffsetEvaluator8compute_EPNS_5ValueE'/>
<use f='llvm/llvm/lib/Analysis/MemoryBuiltins.cpp' l='919' u='m' c='_ZN4llvm25ObjectSizeOffsetEvaluator8compute_EPNS_5ValueE'/>
<use f='llvm/llvm/lib/Analysis/MemoryBuiltins.cpp' l='961' u='m' c='_ZN4llvm25ObjectSizeOffsetEvaluator15visitAllocaInstERNS_10AllocaInstE'/>
<use f='llvm/llvm/lib/Analysis/MemoryBuiltins.cpp' l='977' u='m' c='_ZN4llvm25ObjectSizeOffsetEvaluator13visitCallBaseERNS_8CallBaseE'/>
<use f='llvm/llvm/lib/Analysis/MemoryBuiltins.cpp' l='982' u='m' c='_ZN4llvm25ObjectSizeOffsetEvaluator13visitCallBaseERNS_8CallBaseE'/>
<use f='llvm/llvm/lib/Analysis/MemoryBuiltins.cpp' l='983' u='m' c='_ZN4llvm25ObjectSizeOffsetEvaluator13visitCallBaseERNS_8CallBaseE'/>
<use f='llvm/llvm/lib/Analysis/MemoryBuiltins.cpp' l='1011' u='a' c='_ZN4llvm25ObjectSizeOffsetEvaluator16visitGEPOperatorERNS_11GEPOperatorE'/>
<use f='llvm/llvm/lib/Analysis/MemoryBuiltins.cpp' l='1012' u='m' c='_ZN4llvm25ObjectSizeOffsetEvaluator16visitGEPOperatorERNS_11GEPOperatorE'/>
<use f='llvm/llvm/lib/Analysis/MemoryBuiltins.cpp' l='1027' u='m' c='_ZN4llvm25ObjectSizeOffsetEvaluator12visitPHINodeERNS_7PHINodeE'/>
<use f='llvm/llvm/lib/Analysis/MemoryBuiltins.cpp' l='1028' u='m' c='_ZN4llvm25ObjectSizeOffsetEvaluator12visitPHINodeERNS_7PHINodeE'/>
<use f='llvm/llvm/lib/Analysis/MemoryBuiltins.cpp' l='1035' u='m' c='_ZN4llvm25ObjectSizeOffsetEvaluator12visitPHINodeERNS_7PHINodeE'/>
<use f='llvm/llvm/lib/Analysis/MemoryBuiltins.cpp' l='1076' u='m' c='_ZN4llvm25ObjectSizeOffsetEvaluator15visitSelectInstERNS_10SelectInstE'/>
<use f='llvm/llvm/lib/Analysis/MemoryBuiltins.cpp' l='1078' u='m' c='_ZN4llvm25ObjectSizeOffsetEvaluator15visitSelectInstERNS_10SelectInstE'/>
