<dec f='llvm/llvm/lib/CodeGen/AsmPrinter/DwarfExpression.h' l='131' type='llvm::DwarfCompileUnit &amp;'/>
<use f='llvm/llvm/lib/CodeGen/AsmPrinter/DwarfExpression.h' l='286' u='w' c='_ZN4llvm15DwarfExpressionC1EjRNS_16DwarfCompileUnitE'/>
<offset>128</offset>
<use f='llvm/llvm/lib/CodeGen/AsmPrinter/DwarfExpression.cpp' l='397' u='m' c='_ZN4llvm15DwarfExpression18finalizeEntryValueEv'/>
<use f='llvm/llvm/lib/CodeGen/AsmPrinter/DwarfExpression.cpp' l='425' u='m' c='_ZN4llvm15DwarfExpression19getOrCreateBaseTypeEjNS_5dwarf8TypeKindE'/>
<use f='llvm/llvm/lib/CodeGen/AsmPrinter/DwarfExpression.cpp' l='427' u='m' c='_ZN4llvm15DwarfExpression19getOrCreateBaseTypeEjNS_5dwarf8TypeKindE'/>
<use f='llvm/llvm/lib/CodeGen/AsmPrinter/DwarfExpression.cpp' l='428' u='m' c='_ZN4llvm15DwarfExpression19getOrCreateBaseTypeEjNS_5dwarf8TypeKindE'/>
<use f='llvm/llvm/lib/CodeGen/AsmPrinter/DwarfExpression.cpp' l='432' u='m' c='_ZN4llvm15DwarfExpression19getOrCreateBaseTypeEjNS_5dwarf8TypeKindE'/>
<use f='llvm/llvm/lib/CodeGen/AsmPrinter/DwarfExpression.cpp' l='553' u='m' c='_ZN4llvm15DwarfExpression13addExpressionEONS_18DIExpressionCursorEj'/>
<use f='llvm/llvm/lib/CodeGen/AsmPrinter/DwarfUnit.cpp' l='53' u='m' c='_ZN4llvm18DIEDwarfExpression6emitOpEhPKc'/>
<use f='llvm/llvm/lib/CodeGen/AsmPrinter/DwarfUnit.cpp' l='57' u='m' c='_ZN4llvm18DIEDwarfExpression10emitSignedEl'/>
<use f='llvm/llvm/lib/CodeGen/AsmPrinter/DwarfUnit.cpp' l='61' u='m' c='_ZN4llvm18DIEDwarfExpression12emitUnsignedEm'/>
<use f='llvm/llvm/lib/CodeGen/AsmPrinter/DwarfUnit.cpp' l='65' u='m' c='_ZN4llvm18DIEDwarfExpression9emitData1Eh'/>
<use f='llvm/llvm/lib/CodeGen/AsmPrinter/DwarfUnit.cpp' l='69' u='m' c='_ZN4llvm18DIEDwarfExpression15emitBaseTypeRefEm'/>
