<dec f='llvm/llvm/include/llvm/CodeGen/GlobalISel/MachineIRBuilder.h' l='45' type='llvm::DebugLoc'/>
<use f='llvm/llvm/include/llvm/CodeGen/GlobalISel/MachineIRBuilder.h' l='285' u='a' c='_ZN4llvm16MachineIRBuilder5getDLEv'/>
<use f='llvm/llvm/include/llvm/CodeGen/GlobalISel/MachineIRBuilder.h' l='363' u='w' c='_ZN4llvm16MachineIRBuilder11setDebugLocERKNS_8DebugLocE'/>
<use f='llvm/llvm/include/llvm/CodeGen/GlobalISel/MachineIRBuilder.h' l='366' u='r' c='_ZN4llvm16MachineIRBuilder11getDebugLocEv'/>
<offset>192</offset>
<doc f='llvm/llvm/include/llvm/CodeGen/GlobalISel/MachineIRBuilder.h' l='44'>/// Debug location to be set to any instruction we create.</doc>
<use f='llvm/llvm/lib/CodeGen/GlobalISel/MachineIRBuilder.cpp' l='31' u='w' c='_ZN4llvm16MachineIRBuilder5setMFERNS_15MachineFunctionE'/>
