<dec f='llvm/llvm/include/llvm/ExecutionEngine/Orc/ExecutionUtils.h' l='86' type='unsigned int'/>
<offset>64</offset>
<use f='llvm/llvm/lib/ExecutionEngine/Orc/ExecutionUtils.cpp' l='27' u='w' c='_ZN4llvm3orc16CtorDtorIteratorC1EPKNS_14GlobalVariableEb'/>
<use f='llvm/llvm/lib/ExecutionEngine/Orc/ExecutionUtils.cpp' l='32' u='r' c='_ZNK4llvm3orc16CtorDtorIteratoreqERKS1_'/>
<use f='llvm/llvm/lib/ExecutionEngine/Orc/ExecutionUtils.cpp' l='32' u='r' c='_ZNK4llvm3orc16CtorDtorIteratoreqERKS1_'/>
<use f='llvm/llvm/lib/ExecutionEngine/Orc/ExecutionUtils.cpp' l='40' u='w' c='_ZN4llvm3orc16CtorDtorIteratorppEv'/>
<use f='llvm/llvm/lib/ExecutionEngine/Orc/ExecutionUtils.cpp' l='46' u='w' c='_ZN4llvm3orc16CtorDtorIteratorppEi'/>
<use f='llvm/llvm/lib/ExecutionEngine/Orc/ExecutionUtils.cpp' l='51' u='r' c='_ZNK4llvm3orc16CtorDtorIteratordeEv'/>
