<dec f='llvm/llvm/include/llvm/Analysis/ScalarEvolution.h' l='2188' type='const llvm::Loop &amp;'/>
<offset>768</offset>
<doc f='llvm/llvm/include/llvm/Analysis/ScalarEvolution.h' l='2187'>/// The analyzed Loop.</doc>
<use f='llvm/llvm/lib/Analysis/ScalarEvolution.cpp' l='13011' u='w' c='_ZN4llvm25PredicatedScalarEvolutionC1ERNS_15ScalarEvolutionERNS_4LoopE'/>
<use f='llvm/llvm/lib/Analysis/ScalarEvolution.cpp' l='13026' u='a' c='_ZN4llvm25PredicatedScalarEvolution7getSCEVEPNS_5ValueE'/>
<use f='llvm/llvm/lib/Analysis/ScalarEvolution.cpp' l='13035' u='a' c='_ZN4llvm25PredicatedScalarEvolution21getBackedgeTakenCountEv'/>
<use f='llvm/llvm/lib/Analysis/ScalarEvolution.cpp' l='13057' u='a' c='_ZN4llvm25PredicatedScalarEvolution16updateGenerationEv'/>
<use f='llvm/llvm/lib/Analysis/ScalarEvolution.cpp' l='13097' u='a' c='_ZN4llvm25PredicatedScalarEvolution11getAsAddRecEPNS_5ValueE'/>
<use f='llvm/llvm/lib/Analysis/ScalarEvolution.cpp' l='13112' u='w' c='_ZN4llvm25PredicatedScalarEvolutionC1ERKS0_'/>
<use f='llvm/llvm/lib/Analysis/ScalarEvolution.cpp' l='13112' u='r' c='_ZN4llvm25PredicatedScalarEvolutionC1ERKS0_'/>
<use f='llvm/llvm/lib/Analysis/ScalarEvolution.cpp' l='13120' u='m' c='_ZNK4llvm25PredicatedScalarEvolution5printERNS_11raw_ostreamEj'/>
