<dec f='llvm/llvm/include/llvm/CodeGen/MachinePipeliner.h' l='158' type='SmallVector&lt;SmallPtrSet&lt;llvm::SUnit *, 4&gt;, 10&gt;'/>
<use f='llvm/llvm/include/llvm/CodeGen/MachinePipeliner.h' l='167' u='w' c='_ZN4llvm17SwingSchedulerDAG8CircuitsC1ERSt6vectorINS_5SUnitESaIS3_EERNS_26ScheduleDAGTopologicalSortE'/>
<use f='llvm/llvm/include/llvm/CodeGen/MachinePipeliner.h' l='180' u='m' c='_ZN4llvm17SwingSchedulerDAG8Circuits5resetEv'/>
<use f='llvm/llvm/lib/CodeGen/MachinePipeliner.cpp' l='1310' u='m' c='_ZN4llvm17SwingSchedulerDAG8Circuits7circuitEiiRNS_11SmallVectorINS_7NodeSetELj8EEEb'/>
<use f='llvm/llvm/lib/CodeGen/MachinePipeliner.cpp' l='1311' u='m' c='_ZN4llvm17SwingSchedulerDAG8Circuits7circuitEiiRNS_11SmallVectorINS_7NodeSetELj8EEEb'/>
<use f='llvm/llvm/lib/CodeGen/MachinePipeliner.cpp' l='1321' u='m' c='_ZN4llvm17SwingSchedulerDAG8Circuits7unblockEi'/>
<offset>640</offset>
