<dec f='llvm/build/lib/Target/PowerPC/PPCGenInstrInfo.inc' l='1510' type='1495'/>
<use f='llvm/build/lib/Target/PowerPC/PPCGenAsmMatcher.inc' l='6845'/>
<use f='llvm/build/lib/Target/PowerPC/PPCGenAsmMatcher.inc' l='6846'/>
<use f='llvm/build/lib/Target/PowerPC/PPCGenAsmWriter.inc' l='10298' u='r' c='_ZN4llvm14PPCInstPrinter15printAliasInstrEPKNS_6MCInstEmRKNS_15MCSubtargetInfoERNS_11raw_ostreamE'/>
<use f='llvm/build/lib/Target/PowerPC/PPCGenMCCodeEmitter.inc' l='4265' c='_ZNK4llvm16PPCMCCodeEmitter21getBinaryCodeForInstrERKNS_6MCInstERNS_15SmallVectorImplINS_7MCFixupEEERKNS_15MCSubtargetInfoE'/>
<use f='llvm/build/lib/Target/PowerPC/PPCGenDAGISel.inc' l='43365' u='r' c='_ZN12_GLOBAL__N_115PPCDAGToDAGISel10SelectCodeEPN4llvm6SDNodeE'/>
<use f='llvm/build/lib/Target/PowerPC/PPCGenDAGISel.inc' l='43365' u='r' c='_ZN12_GLOBAL__N_115PPCDAGToDAGISel10SelectCodeEPN4llvm6SDNodeE'/>
