<dec f='llvm/llvm/include/llvm/CodeGen/StackProtector.h' l='51' type='llvm::Module *'/>
<offset>896</offset>
<use f='llvm/llvm/lib/CodeGen/StackProtector.cpp' l='85' u='w' c='_ZN4llvm14StackProtector13runOnFunctionERNS_8FunctionE'/>
<use f='llvm/llvm/lib/CodeGen/StackProtector.cpp' l='135' u='r' c='_ZNK4llvm14StackProtector24ContainsProtectableArrayEPNS_4TypeERbbb'/>
<use f='llvm/llvm/lib/CodeGen/StackProtector.cpp' l='167' u='r' c='_ZN4llvm14StackProtector15HasAddressTakenEPKNS_11InstructionEm'/>
<use f='llvm/llvm/lib/CodeGen/StackProtector.cpp' l='353' u='r' c='_ZN4llvm14StackProtector22RequiresStackProtectorEv'/>
<use f='llvm/llvm/lib/CodeGen/StackProtector.cpp' l='452' u='r' c='_ZN4llvm14StackProtector21InsertStackProtectorsEv'/>
<use f='llvm/llvm/lib/CodeGen/StackProtector.cpp' l='476' u='r' c='_ZN4llvm14StackProtector21InsertStackProtectorsEv'/>
<use f='llvm/llvm/lib/CodeGen/StackProtector.cpp' l='534' u='r' c='_ZN4llvm14StackProtector21InsertStackProtectorsEv'/>
<use f='llvm/llvm/lib/CodeGen/StackProtector.cpp' l='563' u='r' c='_ZN4llvm14StackProtector12CreateFailBBEv'/>
<use f='llvm/llvm/lib/CodeGen/StackProtector.cpp' l='570' u='r' c='_ZN4llvm14StackProtector12CreateFailBBEv'/>
