<dec f='llvm/llvm/include/llvm/Analysis/InlineSizeEstimatorAnalysis.h' l='37' type='llvm::raw_ostream &amp;'/>
<use f='llvm/llvm/include/llvm/Analysis/InlineSizeEstimatorAnalysis.h' l='40' u='w' c='_ZN4llvm38InlineSizeEstimatorAnalysisPrinterPassC1ERNS_11raw_ostreamE'/>
<use f='llvm/llvm/lib/Analysis/InlineSizeEstimatorAnalysis.cpp' l='280' u='m' c='_ZN4llvm38InlineSizeEstimatorAnalysisPrinterPass3runERNS_8FunctionERNS_15AnalysisManagerIS1_JEEE'/>
<offset>0</offset>
