<dec f='llvm/llvm/include/llvm/Analysis/ScalarEvolution.h' l='2080' type='llvm::raw_ostream &amp;'/>
<use f='llvm/llvm/include/llvm/Analysis/ScalarEvolution.h' l='2083' u='w' c='_ZN4llvm26ScalarEvolutionPrinterPassC1ERNS_11raw_ostreamE'/>
<offset>0</offset>
<use f='llvm/llvm/lib/Analysis/ScalarEvolution.cpp' l='12645' u='m' c='_ZN4llvm26ScalarEvolutionPrinterPass3runERNS_8FunctionERNS_15AnalysisManagerIS1_JEEE'/>
<use f='llvm/llvm/lib/Analysis/ScalarEvolution.cpp' l='12647' u='a' c='_ZN4llvm26ScalarEvolutionPrinterPass3runERNS_8FunctionERNS_15AnalysisManagerIS1_JEEE'/>
