<dec f='llvm/llvm/lib/Target/X86/MCTargetDesc/X86BaseInfo.h' l='784' type='4096'/>
<use f='llvm/llvm/lib/Target/X86/MCTargetDesc/X86ATTInstPrinter.cpp' l='103' u='r' c='_ZN4llvm17X86ATTInstPrinter20printVecCompareInstrEPKNS_6MCInstERNS_11raw_ostreamE'/>
<use f='llvm/llvm/lib/Target/X86/MCTargetDesc/X86ATTInstPrinter.cpp' l='181' u='r' c='_ZN4llvm17X86ATTInstPrinter20printVecCompareInstrEPKNS_6MCInstERNS_11raw_ostreamE'/>
<use f='llvm/llvm/lib/Target/X86/MCTargetDesc/X86IntelInstPrinter.cpp' l='86' u='r' c='_ZN4llvm19X86IntelInstPrinter20printVecCompareInstrEPKNS_6MCInstERNS_11raw_ostreamE'/>
<use f='llvm/llvm/lib/Target/X86/MCTargetDesc/X86IntelInstPrinter.cpp' l='171' u='r' c='_ZN4llvm19X86IntelInstPrinter20printVecCompareInstrEPKNS_6MCInstERNS_11raw_ostreamE'/>
<use f='llvm/llvm/lib/Target/X86/MCTargetDesc/X86MCCodeEmitter.cpp' l='858' c='_ZNK12_GLOBAL__N_116X86MCCodeEmitter19emitVEXOpcodePrefixEiRKN4llvm6MCInstERNS1_11raw_ostreamE'/>
<use f='llvm/llvm/lib/Target/X86/MCTargetDesc/X86MCCodeEmitter.cpp' l='1357' c='_ZNK12_GLOBAL__N_116X86MCCodeEmitter16emitOpcodePrefixEiRKN4llvm6MCInstERKNS1_15MCSubtargetInfoERNS1_11raw_ostreamE'/>
