<dec f='llvm/llvm/include/llvm/ADT/IntEqClasses.h' l='33' type='SmallVector&lt;unsigned int, 8&gt;'/>
<use f='llvm/llvm/include/llvm/ADT/IntEqClasses.h' l='51' u='m' c='_ZN4llvm12IntEqClasses5clearEv'/>
<use f='llvm/llvm/include/llvm/ADT/IntEqClasses.h' l='77' u='m' c='_ZNK4llvm12IntEqClassesixEj'/>
<offset>0</offset>
<doc f='llvm/llvm/include/llvm/ADT/IntEqClasses.h' l='28'>/// EC - When uncompressed, map each integer to a smaller member of its
  /// equivalence class. The class leader is the smallest member and maps to
  /// itself.
  ///
  /// When compressed, EC[i] is the equivalence class of i.</doc>
<use f='llvm/llvm/lib/Support/IntEqClasses.cpp' l='27' u='m' c='_ZN4llvm12IntEqClasses4growEj'/>
<use f='llvm/llvm/lib/Support/IntEqClasses.cpp' l='28' u='m' c='_ZN4llvm12IntEqClasses4growEj'/>
<use f='llvm/llvm/lib/Support/IntEqClasses.cpp' l='29' u='m' c='_ZN4llvm12IntEqClasses4growEj'/>
<use f='llvm/llvm/lib/Support/IntEqClasses.cpp' l='29' u='m' c='_ZN4llvm12IntEqClasses4growEj'/>
<use f='llvm/llvm/lib/Support/IntEqClasses.cpp' l='34' u='m' c='_ZN4llvm12IntEqClasses4joinEjj'/>
<use f='llvm/llvm/lib/Support/IntEqClasses.cpp' l='35' u='m' c='_ZN4llvm12IntEqClasses4joinEjj'/>
<use f='llvm/llvm/lib/Support/IntEqClasses.cpp' l='41' u='m' c='_ZN4llvm12IntEqClasses4joinEjj'/>
<use f='llvm/llvm/lib/Support/IntEqClasses.cpp' l='43' u='m' c='_ZN4llvm12IntEqClasses4joinEjj'/>
<use f='llvm/llvm/lib/Support/IntEqClasses.cpp' l='45' u='m' c='_ZN4llvm12IntEqClasses4joinEjj'/>
<use f='llvm/llvm/lib/Support/IntEqClasses.cpp' l='47' u='m' c='_ZN4llvm12IntEqClasses4joinEjj'/>
<use f='llvm/llvm/lib/Support/IntEqClasses.cpp' l='55' u='m' c='_ZNK4llvm12IntEqClasses10findLeaderEj'/>
<use f='llvm/llvm/lib/Support/IntEqClasses.cpp' l='56' u='m' c='_ZNK4llvm12IntEqClasses10findLeaderEj'/>
<use f='llvm/llvm/lib/Support/IntEqClasses.cpp' l='63' u='m' c='_ZN4llvm12IntEqClasses8compressEv'/>
<use f='llvm/llvm/lib/Support/IntEqClasses.cpp' l='64' u='m' c='_ZN4llvm12IntEqClasses8compressEv'/>
<use f='llvm/llvm/lib/Support/IntEqClasses.cpp' l='64' u='m' c='_ZN4llvm12IntEqClasses8compressEv'/>
<use f='llvm/llvm/lib/Support/IntEqClasses.cpp' l='64' u='m' c='_ZN4llvm12IntEqClasses8compressEv'/>
<use f='llvm/llvm/lib/Support/IntEqClasses.cpp' l='64' u='m' c='_ZN4llvm12IntEqClasses8compressEv'/>
<use f='llvm/llvm/lib/Support/IntEqClasses.cpp' l='71' u='m' c='_ZN4llvm12IntEqClasses10uncompressEv'/>
<use f='llvm/llvm/lib/Support/IntEqClasses.cpp' l='72' u='m' c='_ZN4llvm12IntEqClasses10uncompressEv'/>
<use f='llvm/llvm/lib/Support/IntEqClasses.cpp' l='73' u='m' c='_ZN4llvm12IntEqClasses10uncompressEv'/>
<use f='llvm/llvm/lib/Support/IntEqClasses.cpp' l='73' u='m' c='_ZN4llvm12IntEqClasses10uncompressEv'/>
<use f='llvm/llvm/lib/Support/IntEqClasses.cpp' l='75' u='m' c='_ZN4llvm12IntEqClasses10uncompressEv'/>
