<dec f='llvm/llvm/lib/Target/AMDGPU/GCNIterativeScheduler.cpp' l='159' type='llvm::GCNIterativeScheduler &amp;'/>
<use f='llvm/llvm/lib/Target/AMDGPU/GCNIterativeScheduler.cpp' l='168' u='w' c='_ZN4llvm21GCNIterativeScheduler22OverrideLegacyStrategyC1ERNS0_6RegionERNS_20MachineSchedStrategyERS0_'/>
<use f='llvm/llvm/lib/Target/AMDGPU/GCNIterativeScheduler.cpp' l='172' u='m' c='_ZN4llvm21GCNIterativeScheduler22OverrideLegacyStrategyC1ERNS0_6RegionERNS_20MachineSchedStrategyERS0_'/>
<use f='llvm/llvm/lib/Target/AMDGPU/GCNIterativeScheduler.cpp' l='174' u='m' c='_ZN4llvm21GCNIterativeScheduler22OverrideLegacyStrategyC1ERNS0_6RegionERNS_20MachineSchedStrategyERS0_'/>
<use f='llvm/llvm/lib/Target/AMDGPU/GCNIterativeScheduler.cpp' l='175' u='m' c='_ZN4llvm21GCNIterativeScheduler22OverrideLegacyStrategyC1ERNS0_6RegionERNS_20MachineSchedStrategyERS0_'/>
<use f='llvm/llvm/lib/Target/AMDGPU/GCNIterativeScheduler.cpp' l='179' u='m' c='_ZN4llvm21GCNIterativeScheduler22OverrideLegacyStrategyD1Ev'/>
<use f='llvm/llvm/lib/Target/AMDGPU/GCNIterativeScheduler.cpp' l='180' u='m' c='_ZN4llvm21GCNIterativeScheduler22OverrideLegacyStrategyD1Ev'/>
<use f='llvm/llvm/lib/Target/AMDGPU/GCNIterativeScheduler.cpp' l='181' u='m' c='_ZN4llvm21GCNIterativeScheduler22OverrideLegacyStrategyD1Ev'/>
<use f='llvm/llvm/lib/Target/AMDGPU/GCNIterativeScheduler.cpp' l='182' u='m' c='_ZN4llvm21GCNIterativeScheduler22OverrideLegacyStrategyD1Ev'/>
<use f='llvm/llvm/lib/Target/AMDGPU/GCNIterativeScheduler.cpp' l='189' u='m' c='_ZN4llvm21GCNIterativeScheduler22OverrideLegacyStrategy8scheduleEv'/>
<use f='llvm/llvm/lib/Target/AMDGPU/GCNIterativeScheduler.cpp' l='192' u='m' c='_ZN4llvm21GCNIterativeScheduler22OverrideLegacyStrategy8scheduleEv'/>
<use f='llvm/llvm/lib/Target/AMDGPU/GCNIterativeScheduler.cpp' l='194' u='m' c='_ZN4llvm21GCNIterativeScheduler22OverrideLegacyStrategy8scheduleEv'/>
<use f='llvm/llvm/lib/Target/AMDGPU/GCNIterativeScheduler.cpp' l='202' u='m' c='_ZN4llvm21GCNIterativeScheduler22OverrideLegacyStrategy12restoreOrderEv'/>
<use f='llvm/llvm/lib/Target/AMDGPU/GCNIterativeScheduler.cpp' l='202' u='m' c='_ZN4llvm21GCNIterativeScheduler22OverrideLegacyStrategy12restoreOrderEv'/>
<offset>0</offset>
