<def f='llvm/llvm/include/llvm/Support/CodeGen.h' l='71'/>
<use f='llvm/llvm/include/llvm/CodeGen/CommandFlags.h' l='53' c='_ZN4llvm7codegen20getFramePointerUsageEv'/>
<use f='llvm/llvm/lib/CodeGen/CommandFlags.cpp' l='55'/>
<use f='llvm/llvm/lib/CodeGen/CommandFlags.cpp' l='55' c='_ZN4llvm7codegen20getFramePointerUsageEv'/>
<use f='llvm/llvm/lib/CodeGen/CommandFlags.cpp' l='185' c='_ZN4llvm7codegen20RegisterCodeGenFlagsC1Ev'/>
