<dec f='llvm/llvm/include/llvm/MC/MCExpr.h' l='501' type='18'/>
<use f='llvm/llvm/include/llvm/MC/MCExpr.h' l='607' u='r' c='_ZN4llvm12MCBinaryExpr9createSubEPKNS_6MCExprES3_RNS_9MCContextE'/>
<doc f='llvm/llvm/include/llvm/MC/MCExpr.h' l='501'>///&lt; Subtraction.</doc>
<use f='llvm/llvm/lib/MC/MCCodeView.cpp' l='451' u='r' c='_ZL16computeLabelDiffRN4llvm11MCAsmLayoutEPKNS_8MCSymbolES4_'/>
<use f='llvm/llvm/lib/MC/MCDwarf.cpp' l='143' u='r' c='_ZL21makeEndMinusStartExprRN4llvm9MCContextERKNS_8MCSymbolES4_i'/>
<use f='llvm/llvm/lib/MC/MCDwarf.cpp' l='145' u='r' c='_ZL21makeEndMinusStartExprRN4llvm9MCContextERKNS_8MCSymbolES4_i'/>
<use f='llvm/llvm/lib/MC/MCExpr.cpp' l='155' c='_ZNK4llvm6MCExpr5printERNS_11raw_ostreamEPKNS_9MCAsmInfoEb'/>
<use f='llvm/llvm/lib/MC/MCExpr.cpp' l='921' c='_ZNK4llvm6MCExpr25evaluateAsRelocatableImplERNS_7MCValueEPKNS_11MCAssemblerEPKNS_11MCAsmLayoutEPKNS_7MCFixupEPKNS_8DenseMapIPKNS_9MCSectionEmNS_12Dens14347918'/>
<use f='llvm/llvm/lib/MC/MCExpr.cpp' l='973' c='_ZNK4llvm6MCExpr25evaluateAsRelocatableImplERNS_7MCValueEPKNS_11MCAssemblerEPKNS_11MCAsmLayoutEPKNS_7MCFixupEPKNS_8DenseMapIPKNS_9MCSectionEmNS_12Dens14347918'/>
<use f='llvm/llvm/lib/MC/MCExpr.cpp' l='1029' u='r' c='_ZNK4llvm6MCExpr22findAssociatedFragmentEv'/>
<use f='llvm/llvm/lib/MC/MCObjectStreamer.cpp' l='471' u='r' c='_ZL15buildSymbolDiffRN4llvm16MCObjectStreamerEPKNS_8MCSymbolES4_'/>
<use f='llvm/llvm/lib/MC/MCParser/AsmParser.cpp' l='1555' u='r' c='_ZL24getDarwinBinOpPrecedenceN4llvm8AsmToken9TokenKindERNS_12MCBinaryExpr6OpcodeEb'/>
<use f='llvm/llvm/lib/MC/MCParser/AsmParser.cpp' l='1613' u='r' c='_ZL21getGNUBinOpPrecedenceRKN4llvm9MCAsmInfoENS_8AsmToken9TokenKindERNS_12MCBinaryExpr6OpcodeEb'/>
<use f='llvm/llvm/lib/MC/MCParser/MasmParser.cpp' l='1867' u='r' c='_ZL21getGNUBinOpPrecedenceN4llvm8AsmToken9TokenKindERNS_12MCBinaryExpr6OpcodeEbb'/>
<use f='llvm/llvm/lib/MC/MCPseudoProbe.cpp' l='31' u='r' c='_ZL15buildSymbolDiffPN4llvm16MCObjectStreamerEPKNS_8MCSymbolES4_'/>
<use f='llvm/llvm/lib/Target/AMDGPU/MCTargetDesc/SIMCCodeEmitter.cpp' l='451' u='r' c='_ZL10needsPCRelPKN4llvm6MCExprE'/>
<use f='llvm/llvm/lib/Target/Mips/AsmParser/MipsAsmParser.cpp' l='6488' u='r' c='_ZN12_GLOBAL__N_113MipsAsmParser15parseMemOperandERN4llvm15SmallVectorImplISt10unique_ptrINS1_18MCParsedAsmOperandESt14default_deleteIS4_EEEE'/>
<use f='llvm/llvm/lib/Target/PowerPC/AsmParser/PPCAsmParser.cpp' l='726' u='r' c='_ZL13addNegOperandRN4llvm6MCInstERNS_9MCOperandERNS_9MCContextE'/>
<use f='llvm/llvm/lib/Target/RISCV/AsmParser/RISCVAsmParser.cpp' l='1420' u='r' c='_ZN12_GLOBAL__N_114RISCVAsmParser15parseBareSymbolERN4llvm15SmallVectorImplISt10unique_ptrINS1_18MCParsedAsmOperandESt14default_deleteIS4_EEEE'/>
<use f='llvm/llvm/lib/Target/WebAssembly/AsmParser/WebAssemblyAsmParser.cpp' l='1035' u='r' c='_ZN12_GLOBAL__N_120WebAssemblyAsmParser15onEndOfFunctionEv'/>
