<use f='llvm/llvm/examples/Kaleidoscope/BuildingAJIT/Chapter4/KaleidoscopeJIT.h' l='91' u='w' c='_ZN4llvm3orc20KaleidoscopeASTLayerC1ERNS0_7IRLayerERKNS_10DataLayoutE'/>
<use f='llvm/llvm/examples/Kaleidoscope/BuildingAJIT/Chapter4/KaleidoscopeJIT.h' l='106' u='r' c='_ZN4llvm3orc20KaleidoscopeASTLayer12getInterfaceER11FunctionAST'/>
<dec f='llvm/llvm/examples/Kaleidoscope/BuildingAJIT/Chapter4/KaleidoscopeJIT.h' l='115' type='const llvm::DataLayout &amp;'/>
<offset>64</offset>
