<use f='llvm/llvm/include/llvm/CodeGen/RDFRegisters.h' l='170' u='w' c='_ZN4llvm3rdf12RegisterAggrC1ERKNS0_20PhysicalRegisterInfoE'/>
<dec f='llvm/llvm/include/llvm/CodeGen/RDFRegisters.h' l='246' type='const llvm::rdf::PhysicalRegisterInfo &amp;'/>
<offset>192</offset>
<use f='llvm/llvm/lib/CodeGen/RDFRegisters.cpp' l='247' u='m' c='_ZNK4llvm3rdf12RegisterAggr10hasAliasOfENS0_11RegisterRefE'/>
<use f='llvm/llvm/lib/CodeGen/RDFRegisters.cpp' l='249' u='m' c='_ZNK4llvm3rdf12RegisterAggr10hasAliasOfENS0_11RegisterRefE'/>
<use f='llvm/llvm/lib/CodeGen/RDFRegisters.cpp' l='260' u='m' c='_ZNK4llvm3rdf12RegisterAggr10hasCoverOfENS0_11RegisterRefE'/>
<use f='llvm/llvm/lib/CodeGen/RDFRegisters.cpp' l='264' u='m' c='_ZNK4llvm3rdf12RegisterAggr10hasCoverOfENS0_11RegisterRefE'/>
<use f='llvm/llvm/lib/CodeGen/RDFRegisters.cpp' l='275' u='m' c='_ZN4llvm3rdf12RegisterAggr6insertENS0_11RegisterRefE'/>
<use f='llvm/llvm/lib/CodeGen/RDFRegisters.cpp' l='279' u='m' c='_ZN4llvm3rdf12RegisterAggr6insertENS0_11RegisterRefE'/>
<use f='llvm/llvm/lib/CodeGen/RDFRegisters.cpp' l='293' u='r' c='_ZN4llvm3rdf12RegisterAggr9intersectENS0_11RegisterRefE'/>
<use f='llvm/llvm/lib/CodeGen/RDFRegisters.cpp' l='302' u='r' c='_ZN4llvm3rdf12RegisterAggr5clearENS0_11RegisterRefE'/>
<use f='llvm/llvm/lib/CodeGen/RDFRegisters.cpp' l='311' u='r' c='_ZNK4llvm3rdf12RegisterAggr13intersectWithENS0_11RegisterRefE'/>
<use f='llvm/llvm/lib/CodeGen/RDFRegisters.cpp' l='321' u='r' c='_ZNK4llvm3rdf12RegisterAggr7clearInENS0_11RegisterRefE'/>
<use f='llvm/llvm/lib/CodeGen/RDFRegisters.cpp' l='333' u='m' c='_ZNK4llvm3rdf12RegisterAggr10makeRegRefEv'/>
<use f='llvm/llvm/lib/CodeGen/RDFRegisters.cpp' l='339' u='m' c='_ZNK4llvm3rdf12RegisterAggr10makeRegRefEv'/>
<use f='llvm/llvm/lib/CodeGen/RDFRegisters.cpp' l='352' u='m' c='_ZNK4llvm3rdf12RegisterAggr10makeRegRefEv'/>
<use f='llvm/llvm/lib/CodeGen/RDFRegisters.cpp' l='363' u='m' c='_ZNK4llvm3rdf12RegisterAggr5printERNS_11raw_ostreamE'/>
<use f='llvm/llvm/lib/CodeGen/RDFRegisters.cpp' l='371' u='m' c='_ZN4llvm3rdf12RegisterAggr11rr_iteratorC1ERKS1_b'/>
