<dec f='llvm/build/lib/Target/RISCV/RISCVGenInstrInfo.inc' l='14478' type='14463'/>
<use f='llvm/build/lib/Target/RISCV/RISCVGenAsmMatcher.inc' l='3777'/>
<use f='llvm/build/lib/Target/RISCV/RISCVGenAsmMatcher.inc' l='3778'/>
<use f='llvm/llvm/lib/Target/RISCV/AsmParser/RISCVAsmParser.cpp' l='2542' u='r' c='_ZN12_GLOBAL__N_114RISCVAsmParser18processInstructionERN4llvm6MCInstENS1_5SMLocERNS1_15SmallVectorImplISt10unique_ptrINS1_18MCParsedAsmOperandESt14def15576407'/>
<use f='llvm/build/lib/Target/RISCV/RISCVGenMCCodeEmitter.inc' l='15535' c='_ZNK12_GLOBAL__N_118RISCVMCCodeEmitter21getBinaryCodeForInstrERKN4llvm6MCInstERNS1_15SmallVectorImplINS1_7MCFixupEEERKNS1_15MCSubtargetInfoE'/>
<use f='llvm/build/lib/Target/RISCV/RISCVGenDAGISel.inc' l='17615' u='r' c='_ZN4llvm17RISCVDAGToDAGISel10SelectCodeEPNS_6SDNodeE'/>
<use f='llvm/build/lib/Target/RISCV/RISCVGenDAGISel.inc' l='17615' u='r' c='_ZN4llvm17RISCVDAGToDAGISel10SelectCodeEPNS_6SDNodeE'/>
<use f='llvm/build/lib/Target/RISCV/RISCVGenDAGISel.inc' l='17627' u='r' c='_ZN4llvm17RISCVDAGToDAGISel10SelectCodeEPNS_6SDNodeE'/>
<use f='llvm/build/lib/Target/RISCV/RISCVGenDAGISel.inc' l='17627' u='r' c='_ZN4llvm17RISCVDAGToDAGISel10SelectCodeEPNS_6SDNodeE'/>
<use f='llvm/build/lib/Target/RISCV/RISCVGenDAGISel.inc' l='17648' u='r' c='_ZN4llvm17RISCVDAGToDAGISel10SelectCodeEPNS_6SDNodeE'/>
<use f='llvm/build/lib/Target/RISCV/RISCVGenDAGISel.inc' l='17648' u='r' c='_ZN4llvm17RISCVDAGToDAGISel10SelectCodeEPNS_6SDNodeE'/>
<use f='llvm/build/lib/Target/RISCV/RISCVGenDAGISel.inc' l='17655' u='r' c='_ZN4llvm17RISCVDAGToDAGISel10SelectCodeEPNS_6SDNodeE'/>
<use f='llvm/build/lib/Target/RISCV/RISCVGenDAGISel.inc' l='17655' u='r' c='_ZN4llvm17RISCVDAGToDAGISel10SelectCodeEPNS_6SDNodeE'/>
<use f='llvm/build/lib/Target/RISCV/RISCVGenDAGISel.inc' l='17669' u='r' c='_ZN4llvm17RISCVDAGToDAGISel10SelectCodeEPNS_6SDNodeE'/>
<use f='llvm/build/lib/Target/RISCV/RISCVGenDAGISel.inc' l='17669' u='r' c='_ZN4llvm17RISCVDAGToDAGISel10SelectCodeEPNS_6SDNodeE'/>
<use f='llvm/build/lib/Target/RISCV/RISCVGenDAGISel.inc' l='17676' u='r' c='_ZN4llvm17RISCVDAGToDAGISel10SelectCodeEPNS_6SDNodeE'/>
<use f='llvm/build/lib/Target/RISCV/RISCVGenDAGISel.inc' l='17676' u='r' c='_ZN4llvm17RISCVDAGToDAGISel10SelectCodeEPNS_6SDNodeE'/>
<use f='llvm/build/lib/Target/RISCV/RISCVGenDAGISel.inc' l='17692' u='r' c='_ZN4llvm17RISCVDAGToDAGISel10SelectCodeEPNS_6SDNodeE'/>
<use f='llvm/build/lib/Target/RISCV/RISCVGenDAGISel.inc' l='17692' u='r' c='_ZN4llvm17RISCVDAGToDAGISel10SelectCodeEPNS_6SDNodeE'/>
<use f='llvm/build/lib/Target/RISCV/RISCVGenDAGISel.inc' l='17701' u='r' c='_ZN4llvm17RISCVDAGToDAGISel10SelectCodeEPNS_6SDNodeE'/>
<use f='llvm/build/lib/Target/RISCV/RISCVGenDAGISel.inc' l='17701' u='r' c='_ZN4llvm17RISCVDAGToDAGISel10SelectCodeEPNS_6SDNodeE'/>
<use f='llvm/build/lib/Target/RISCV/RISCVGenDAGISel.inc' l='17710' u='r' c='_ZN4llvm17RISCVDAGToDAGISel10SelectCodeEPNS_6SDNodeE'/>
<use f='llvm/build/lib/Target/RISCV/RISCVGenDAGISel.inc' l='17710' u='r' c='_ZN4llvm17RISCVDAGToDAGISel10SelectCodeEPNS_6SDNodeE'/>
<use f='llvm/build/lib/Target/RISCV/RISCVGenDAGISel.inc' l='17719' u='r' c='_ZN4llvm17RISCVDAGToDAGISel10SelectCodeEPNS_6SDNodeE'/>
<use f='llvm/build/lib/Target/RISCV/RISCVGenDAGISel.inc' l='17719' u='r' c='_ZN4llvm17RISCVDAGToDAGISel10SelectCodeEPNS_6SDNodeE'/>
<use f='llvm/llvm/lib/Target/RISCV/RISCVISelDAGToDAG.cpp' l='974' c='_ZN4llvm17RISCVDAGToDAGISel23doPeepholeLoadStoreADDIEv'/>
<use f='llvm/llvm/lib/Target/RISCV/RISCVInstrInfo.cpp' l='74' c='_ZNK4llvm14RISCVInstrInfo18isStoreToStackSlotERKNS_12MachineInstrERi'/>
<use f='llvm/llvm/lib/Target/RISCV/RISCVInstrInfo.cpp' l='154' u='r' c='_ZNK4llvm14RISCVInstrInfo19storeRegToStackSlotERNS_17MachineBasicBlockENS_26MachineInstrBundleIteratorINS_12MachineInstrELb0EEENS_8RegisterEbiPKNS_19T7708132'/>
<use f='llvm/build/lib/Target/RISCV/RISCVGenGlobalISel.inc' l='11129' u='r' c='_ZNK12_GLOBAL__N_124RISCVInstructionSelector13getMatchTableEv'/>
<use f='llvm/build/lib/Target/RISCV/RISCVGenGlobalISel.inc' l='11156' u='r' c='_ZNK12_GLOBAL__N_124RISCVInstructionSelector13getMatchTableEv'/>
<use f='llvm/build/lib/Target/RISCV/RISCVGenGlobalISel.inc' l='11172' u='r' c='_ZNK12_GLOBAL__N_124RISCVInstructionSelector13getMatchTableEv'/>
<use f='llvm/build/lib/Target/RISCV/RISCVGenGlobalISel.inc' l='11188' u='r' c='_ZNK12_GLOBAL__N_124RISCVInstructionSelector13getMatchTableEv'/>
<use f='llvm/llvm/lib/Target/RISCV/RISCVMergeBaseOffset.cpp' l='226' c='_ZN12_GLOBAL__N_123RISCVMergeBaseOffsetOpt19detectAndFoldOffsetERN4llvm12MachineInstrES3_'/>
