<dec f='llvm/build/lib/Target/Mips/MipsGenInstrInfo.inc' l='2413' type='2398'/>
<use f='llvm/build/lib/Target/Mips/MipsGenAsmMatcher.inc' l='7550'/>
<use f='llvm/llvm/lib/Target/Mips/Disassembler/MipsDisassembler.cpp' l='1565' u='r' c='_ZL12DecodeMemEVARN4llvm6MCInstEjmPKv'/>
<use f='llvm/build/lib/Target/Mips/MipsGenMCCodeEmitter.inc' l='3037' c='_ZNK4llvm17MipsMCCodeEmitter21getBinaryCodeForInstrERKNS_6MCInstERNS_15SmallVectorImplINS_7MCFixupEEERKNS_15MCSubtargetInfoE'/>
<use f='llvm/llvm/lib/Target/Mips/MipsSERegisterInfo.cpp' l='87' c='_ZL28getLoadStoreOffsetSizeInBitsjN4llvm14MachineOperandE'/>
