<dec f='llvm/llvm/include/llvm/CodeGen/GlobalISel/GISelKnownBits.h' l='32' type='const llvm::DataLayout &amp;'/>
<use f='llvm/llvm/include/llvm/CodeGen/GlobalISel/GISelKnownBits.h' l='53' u='a' c='_ZNK4llvm14GISelKnownBits13getDataLayoutEv'/>
<offset>768</offset>
<use f='llvm/llvm/lib/CodeGen/GlobalISel/GISelKnownBits.cpp' l='32' u='w' c='_ZN4llvm14GISelKnownBitsC1ERNS_15MachineFunctionEj'/>
<use f='llvm/llvm/lib/CodeGen/GlobalISel/GISelKnownBits.cpp' l='249' u='m' c='_ZN4llvm14GISelKnownBits20computeKnownBitsImplENS_8RegisterERNS_9KnownBitsERKNS_5APIntEj'/>
<use f='llvm/llvm/lib/CodeGen/GlobalISel/GISelKnownBits.cpp' l='411' u='m' c='_ZN4llvm14GISelKnownBits20computeKnownBitsImplENS_8RegisterERNS_9KnownBitsERKNS_5APIntEj'/>
