<dec f='llvm/llvm/examples/Kaleidoscope/BuildingAJIT/Chapter1/KaleidoscopeJIT.h' l='36' type='std::unique_ptr&lt;ExecutionSession&gt;'/>
<use f='llvm/llvm/examples/Kaleidoscope/BuildingAJIT/Chapter1/KaleidoscopeJIT.h' l='50' u='w' c='_ZN4llvm3orc15KaleidoscopeJITC1ESt10unique_ptrINS0_20TargetProcessControlESt14default_deleteIS3_EES2_INS0_16ExecutionSessionES4_IS7_EENS0_23JITTargetM9673592'/>
<use f='llvm/llvm/examples/Kaleidoscope/BuildingAJIT/Chapter1/KaleidoscopeJIT.h' l='51' u='m' c='_ZN4llvm3orc15KaleidoscopeJITC1ESt10unique_ptrINS0_20TargetProcessControlESt14default_deleteIS3_EES2_INS0_16ExecutionSessionES4_IS7_EENS0_23JITTargetM9673592'/>
<use f='llvm/llvm/examples/Kaleidoscope/BuildingAJIT/Chapter1/KaleidoscopeJIT.h' l='52' u='m' c='_ZN4llvm3orc15KaleidoscopeJITC1ESt10unique_ptrINS0_20TargetProcessControlESt14default_deleteIS3_EES2_INS0_16ExecutionSessionES4_IS7_EENS0_23JITTargetM9673592'/>
<use f='llvm/llvm/examples/Kaleidoscope/BuildingAJIT/Chapter1/KaleidoscopeJIT.h' l='54' u='m' c='_ZN4llvm3orc15KaleidoscopeJITC1ESt10unique_ptrINS0_20TargetProcessControlESt14default_deleteIS3_EES2_INS0_16ExecutionSessionES4_IS7_EENS0_23JITTargetM9673592'/>
<use f='llvm/llvm/examples/Kaleidoscope/BuildingAJIT/Chapter1/KaleidoscopeJIT.h' l='56' u='m' c='_ZN4llvm3orc15KaleidoscopeJITC1ESt10unique_ptrINS0_20TargetProcessControlESt14default_deleteIS3_EES2_INS0_16ExecutionSessionES4_IS7_EENS0_23JITTargetM9673592'/>
<use f='llvm/llvm/examples/Kaleidoscope/BuildingAJIT/Chapter1/KaleidoscopeJIT.h' l='63' u='m' c='_ZN4llvm3orc15KaleidoscopeJITD1Ev'/>
<use f='llvm/llvm/examples/Kaleidoscope/BuildingAJIT/Chapter1/KaleidoscopeJIT.h' l='64' u='m' c='_ZN4llvm3orc15KaleidoscopeJITD1Ev'/>
<use f='llvm/llvm/examples/Kaleidoscope/BuildingAJIT/Chapter1/KaleidoscopeJIT.h' l='96' u='m' c='_ZN4llvm3orc15KaleidoscopeJIT6lookupENS_9StringRefE'/>
<offset>64</offset>
<dec f='llvm/llvm/examples/Kaleidoscope/BuildingAJIT/Chapter2/KaleidoscopeJIT.h' l='41' type='std::unique_ptr&lt;ExecutionSession&gt;'/>
<use f='llvm/llvm/examples/Kaleidoscope/BuildingAJIT/Chapter2/KaleidoscopeJIT.h' l='56' u='w' c='_ZN4llvm3orc15KaleidoscopeJITC1ESt10unique_ptrINS0_20TargetProcessControlESt14default_deleteIS3_EES2_INS0_16ExecutionSessionES4_IS7_EENS0_23JITTargetM9673592'/>
<use f='llvm/llvm/examples/Kaleidoscope/BuildingAJIT/Chapter2/KaleidoscopeJIT.h' l='57' u='m' c='_ZN4llvm3orc15KaleidoscopeJITC1ESt10unique_ptrINS0_20TargetProcessControlESt14default_deleteIS3_EES2_INS0_16ExecutionSessionES4_IS7_EENS0_23JITTargetM9673592'/>
<use f='llvm/llvm/examples/Kaleidoscope/BuildingAJIT/Chapter2/KaleidoscopeJIT.h' l='58' u='m' c='_ZN4llvm3orc15KaleidoscopeJITC1ESt10unique_ptrINS0_20TargetProcessControlESt14default_deleteIS3_EES2_INS0_16ExecutionSessionES4_IS7_EENS0_23JITTargetM9673592'/>
<use f='llvm/llvm/examples/Kaleidoscope/BuildingAJIT/Chapter2/KaleidoscopeJIT.h' l='60' u='m' c='_ZN4llvm3orc15KaleidoscopeJITC1ESt10unique_ptrINS0_20TargetProcessControlESt14default_deleteIS3_EES2_INS0_16ExecutionSessionES4_IS7_EENS0_23JITTargetM9673592'/>
<use f='llvm/llvm/examples/Kaleidoscope/BuildingAJIT/Chapter2/KaleidoscopeJIT.h' l='62' u='m' c='_ZN4llvm3orc15KaleidoscopeJITC1ESt10unique_ptrINS0_20TargetProcessControlESt14default_deleteIS3_EES2_INS0_16ExecutionSessionES4_IS7_EENS0_23JITTargetM9673592'/>
<use f='llvm/llvm/examples/Kaleidoscope/BuildingAJIT/Chapter2/KaleidoscopeJIT.h' l='63' u='m' c='_ZN4llvm3orc15KaleidoscopeJITC1ESt10unique_ptrINS0_20TargetProcessControlESt14default_deleteIS3_EES2_INS0_16ExecutionSessionES4_IS7_EENS0_23JITTargetM9673592'/>
<use f='llvm/llvm/examples/Kaleidoscope/BuildingAJIT/Chapter2/KaleidoscopeJIT.h' l='70' u='m' c='_ZN4llvm3orc15KaleidoscopeJITD1Ev'/>
<use f='llvm/llvm/examples/Kaleidoscope/BuildingAJIT/Chapter2/KaleidoscopeJIT.h' l='71' u='m' c='_ZN4llvm3orc15KaleidoscopeJITD1Ev'/>
<use f='llvm/llvm/examples/Kaleidoscope/BuildingAJIT/Chapter2/KaleidoscopeJIT.h' l='104' u='m' c='_ZN4llvm3orc15KaleidoscopeJIT6lookupENS_9StringRefE'/>
<offset>64</offset>
<dec f='llvm/llvm/examples/Kaleidoscope/BuildingAJIT/Chapter3/KaleidoscopeJIT.h' l='43' type='std::unique_ptr&lt;ExecutionSession&gt;'/>
<use f='llvm/llvm/examples/Kaleidoscope/BuildingAJIT/Chapter3/KaleidoscopeJIT.h' l='66' u='w' c='_ZN4llvm3orc15KaleidoscopeJITC1ESt10unique_ptrINS0_20TargetProcessControlESt14default_deleteIS3_EES2_INS0_16ExecutionSessionES4_IS7_EES2_INS0_19TPCInd15416843'/>
<use f='llvm/llvm/examples/Kaleidoscope/BuildingAJIT/Chapter3/KaleidoscopeJIT.h' l='67' u='m' c='_ZN4llvm3orc15KaleidoscopeJITC1ESt10unique_ptrINS0_20TargetProcessControlESt14default_deleteIS3_EES2_INS0_16ExecutionSessionES4_IS7_EES2_INS0_19TPCInd15416843'/>
<use f='llvm/llvm/examples/Kaleidoscope/BuildingAJIT/Chapter3/KaleidoscopeJIT.h' l='68' u='m' c='_ZN4llvm3orc15KaleidoscopeJITC1ESt10unique_ptrINS0_20TargetProcessControlESt14default_deleteIS3_EES2_INS0_16ExecutionSessionES4_IS7_EES2_INS0_19TPCInd15416843'/>
<use f='llvm/llvm/examples/Kaleidoscope/BuildingAJIT/Chapter3/KaleidoscopeJIT.h' l='70' u='m' c='_ZN4llvm3orc15KaleidoscopeJITC1ESt10unique_ptrINS0_20TargetProcessControlESt14default_deleteIS3_EES2_INS0_16ExecutionSessionES4_IS7_EES2_INS0_19TPCInd15416843'/>
<use f='llvm/llvm/examples/Kaleidoscope/BuildingAJIT/Chapter3/KaleidoscopeJIT.h' l='72' u='m' c='_ZN4llvm3orc15KaleidoscopeJITC1ESt10unique_ptrINS0_20TargetProcessControlESt14default_deleteIS3_EES2_INS0_16ExecutionSessionES4_IS7_EES2_INS0_19TPCInd15416843'/>
<use f='llvm/llvm/examples/Kaleidoscope/BuildingAJIT/Chapter3/KaleidoscopeJIT.h' l='73' u='m' c='_ZN4llvm3orc15KaleidoscopeJITC1ESt10unique_ptrINS0_20TargetProcessControlESt14default_deleteIS3_EES2_INS0_16ExecutionSessionES4_IS7_EES2_INS0_19TPCInd15416843'/>
<use f='llvm/llvm/examples/Kaleidoscope/BuildingAJIT/Chapter3/KaleidoscopeJIT.h' l='76' u='m' c='_ZN4llvm3orc15KaleidoscopeJITC1ESt10unique_ptrINS0_20TargetProcessControlESt14default_deleteIS3_EES2_INS0_16ExecutionSessionES4_IS7_EES2_INS0_19TPCInd15416843'/>
<use f='llvm/llvm/examples/Kaleidoscope/BuildingAJIT/Chapter3/KaleidoscopeJIT.h' l='83' u='m' c='_ZN4llvm3orc15KaleidoscopeJITD1Ev'/>
<use f='llvm/llvm/examples/Kaleidoscope/BuildingAJIT/Chapter3/KaleidoscopeJIT.h' l='84' u='m' c='_ZN4llvm3orc15KaleidoscopeJITD1Ev'/>
<use f='llvm/llvm/examples/Kaleidoscope/BuildingAJIT/Chapter3/KaleidoscopeJIT.h' l='86' u='m' c='_ZN4llvm3orc15KaleidoscopeJITD1Ev'/>
<use f='llvm/llvm/examples/Kaleidoscope/BuildingAJIT/Chapter3/KaleidoscopeJIT.h' l='130' u='m' c='_ZN4llvm3orc15KaleidoscopeJIT6lookupENS_9StringRefE'/>
<offset>64</offset>
<dec f='llvm/llvm/examples/Kaleidoscope/BuildingAJIT/Chapter4/KaleidoscopeJIT.h' l='130' type='std::unique_ptr&lt;ExecutionSession&gt;'/>
<use f='llvm/llvm/examples/Kaleidoscope/BuildingAJIT/Chapter4/KaleidoscopeJIT.h' l='153' u='w' c='_ZN4llvm3orc15KaleidoscopeJITC1ESt10unique_ptrINS0_20TargetProcessControlESt14default_deleteIS3_EES2_INS0_16ExecutionSessionES4_IS7_EES2_INS0_19TPCInd15416843'/>
<use f='llvm/llvm/examples/Kaleidoscope/BuildingAJIT/Chapter4/KaleidoscopeJIT.h' l='154' u='m' c='_ZN4llvm3orc15KaleidoscopeJITC1ESt10unique_ptrINS0_20TargetProcessControlESt14default_deleteIS3_EES2_INS0_16ExecutionSessionES4_IS7_EES2_INS0_19TPCInd15416843'/>
<use f='llvm/llvm/examples/Kaleidoscope/BuildingAJIT/Chapter4/KaleidoscopeJIT.h' l='155' u='m' c='_ZN4llvm3orc15KaleidoscopeJITC1ESt10unique_ptrINS0_20TargetProcessControlESt14default_deleteIS3_EES2_INS0_16ExecutionSessionES4_IS7_EES2_INS0_19TPCInd15416843'/>
<use f='llvm/llvm/examples/Kaleidoscope/BuildingAJIT/Chapter4/KaleidoscopeJIT.h' l='157' u='m' c='_ZN4llvm3orc15KaleidoscopeJITC1ESt10unique_ptrINS0_20TargetProcessControlESt14default_deleteIS3_EES2_INS0_16ExecutionSessionES4_IS7_EES2_INS0_19TPCInd15416843'/>
<use f='llvm/llvm/examples/Kaleidoscope/BuildingAJIT/Chapter4/KaleidoscopeJIT.h' l='159' u='m' c='_ZN4llvm3orc15KaleidoscopeJITC1ESt10unique_ptrINS0_20TargetProcessControlESt14default_deleteIS3_EES2_INS0_16ExecutionSessionES4_IS7_EES2_INS0_19TPCInd15416843'/>
<use f='llvm/llvm/examples/Kaleidoscope/BuildingAJIT/Chapter4/KaleidoscopeJIT.h' l='161' u='m' c='_ZN4llvm3orc15KaleidoscopeJITC1ESt10unique_ptrINS0_20TargetProcessControlESt14default_deleteIS3_EES2_INS0_16ExecutionSessionES4_IS7_EES2_INS0_19TPCInd15416843'/>
<use f='llvm/llvm/examples/Kaleidoscope/BuildingAJIT/Chapter4/KaleidoscopeJIT.h' l='168' u='m' c='_ZN4llvm3orc15KaleidoscopeJITD1Ev'/>
<use f='llvm/llvm/examples/Kaleidoscope/BuildingAJIT/Chapter4/KaleidoscopeJIT.h' l='169' u='m' c='_ZN4llvm3orc15KaleidoscopeJITD1Ev'/>
<use f='llvm/llvm/examples/Kaleidoscope/BuildingAJIT/Chapter4/KaleidoscopeJIT.h' l='171' u='m' c='_ZN4llvm3orc15KaleidoscopeJITD1Ev'/>
<use f='llvm/llvm/examples/Kaleidoscope/BuildingAJIT/Chapter4/KaleidoscopeJIT.h' l='221' u='m' c='_ZN4llvm3orc15KaleidoscopeJIT6lookupENS_9StringRefE'/>
<offset>64</offset>
<dec f='llvm/llvm/examples/Kaleidoscope/include/KaleidoscopeJIT.h' l='36' type='std::unique_ptr&lt;ExecutionSession&gt;'/>
<use f='llvm/llvm/examples/Kaleidoscope/include/KaleidoscopeJIT.h' l='50' u='w' c='_ZN4llvm3orc15KaleidoscopeJITC1ESt10unique_ptrINS0_20TargetProcessControlESt14default_deleteIS3_EES2_INS0_16ExecutionSessionES4_IS7_EENS0_23JITTargetM9673592'/>
<use f='llvm/llvm/examples/Kaleidoscope/include/KaleidoscopeJIT.h' l='51' u='m' c='_ZN4llvm3orc15KaleidoscopeJITC1ESt10unique_ptrINS0_20TargetProcessControlESt14default_deleteIS3_EES2_INS0_16ExecutionSessionES4_IS7_EENS0_23JITTargetM9673592'/>
<use f='llvm/llvm/examples/Kaleidoscope/include/KaleidoscopeJIT.h' l='52' u='m' c='_ZN4llvm3orc15KaleidoscopeJITC1ESt10unique_ptrINS0_20TargetProcessControlESt14default_deleteIS3_EES2_INS0_16ExecutionSessionES4_IS7_EENS0_23JITTargetM9673592'/>
<use f='llvm/llvm/examples/Kaleidoscope/include/KaleidoscopeJIT.h' l='54' u='m' c='_ZN4llvm3orc15KaleidoscopeJITC1ESt10unique_ptrINS0_20TargetProcessControlESt14default_deleteIS3_EES2_INS0_16ExecutionSessionES4_IS7_EENS0_23JITTargetM9673592'/>
<use f='llvm/llvm/examples/Kaleidoscope/include/KaleidoscopeJIT.h' l='56' u='m' c='_ZN4llvm3orc15KaleidoscopeJITC1ESt10unique_ptrINS0_20TargetProcessControlESt14default_deleteIS3_EES2_INS0_16ExecutionSessionES4_IS7_EENS0_23JITTargetM9673592'/>
<use f='llvm/llvm/examples/Kaleidoscope/include/KaleidoscopeJIT.h' l='63' u='m' c='_ZN4llvm3orc15KaleidoscopeJITD1Ev'/>
<use f='llvm/llvm/examples/Kaleidoscope/include/KaleidoscopeJIT.h' l='64' u='m' c='_ZN4llvm3orc15KaleidoscopeJITD1Ev'/>
<use f='llvm/llvm/examples/Kaleidoscope/include/KaleidoscopeJIT.h' l='96' u='m' c='_ZN4llvm3orc15KaleidoscopeJIT6lookupENS_9StringRefE'/>
<offset>64</offset>
