<dec f='llvm/llvm/lib/Target/WebAssembly/WebAssemblySortRegion.h' l='65' type='const llvm::MachineLoopInfo &amp;'/>
<use f='llvm/llvm/lib/Target/WebAssembly/WebAssemblySortRegion.h' l='74' u='w' c='_ZN4llvm11WebAssembly14SortRegionInfoC1ERKNS_15MachineLoopInfoERKNS_24WebAssemblyExceptionInfoE'/>
<offset>0</offset>
<use f='llvm/llvm/lib/Target/WebAssembly/WebAssemblySortRegion.cpp' l='18' u='m' c='_ZN4llvm11WebAssembly14SortRegionInfo12getRegionForEPKNS_17MachineBasicBlockE'/>
<use f='llvm/llvm/lib/Target/WebAssembly/WebAssemblySortRegion.cpp' l='47' u='m' c='_ZN4llvm11WebAssembly14SortRegionInfo9getBottomEPKNS0_10SortRegionE'/>
