<use f='llvm/llvm/include/llvm/ExecutionEngine/Orc/LLJIT.h' l='62' u='m' c='_ZN4llvm3orc5LLJIT19getExecutionSessionEv'/>
<use f='llvm/llvm/include/llvm/ExecutionEngine/Orc/LLJIT.h' l='76' u='m' c='_ZN4llvm3orc5LLJIT17getJITDylibByNameENS_9StringRefE'/>
<use f='llvm/llvm/include/llvm/ExecutionEngine/Orc/LLJIT.h' l='86' u='m' c='_ZN4llvm3orc5LLJIT14createJITDylibENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE'/>
<use f='llvm/llvm/include/llvm/ExecutionEngine/Orc/LLJIT.h' l='120' u='m' c='_ZN4llvm3orc5LLJIT19lookupLinkerMangledERNS0_8JITDylibENS_9StringRefE'/>
<use f='llvm/llvm/include/llvm/ExecutionEngine/Orc/LLJIT.h' l='185' u='m' c='_ZNK4llvm3orc5LLJIT15mangleAndInternENS_9StringRefE'/>
<dec f='llvm/llvm/include/llvm/ExecutionEngine/Orc/LLJIT.h' l='202' type='std::unique_ptr&lt;ExecutionSession&gt;'/>
<offset>0</offset>
<use f='llvm/llvm/lib/ExecutionEngine/Orc/LLJIT.cpp' l='980' u='m' c='_ZN4llvm3orc5LLJITD1Ev'/>
<use f='llvm/llvm/lib/ExecutionEngine/Orc/LLJIT.cpp' l='981' u='m' c='_ZN4llvm3orc5LLJITD1Ev'/>
<use f='llvm/llvm/lib/ExecutionEngine/Orc/LLJIT.cpp' l='1011' u='m' c='_ZN4llvm3orc5LLJIT19lookupLinkerMangledERNS0_8JITDylibENS0_15SymbolStringPtrE'/>
<use f='llvm/llvm/lib/ExecutionEngine/Orc/LLJIT.cpp' l='1060' u='w' c='_ZN4llvm3orc5LLJITC1ERNS0_17LLJITBuilderStateERNS_5ErrorE'/>
<use f='llvm/llvm/lib/ExecutionEngine/Orc/LLJIT.cpp' l='1065' u='m' c='_ZN4llvm3orc5LLJITC1ERNS0_17LLJITBuilderStateERNS_5ErrorE'/>
<use f='llvm/llvm/lib/ExecutionEngine/Orc/LLJIT.cpp' l='1081' u='m' c='_ZN4llvm3orc5LLJITC1ERNS0_17LLJITBuilderStateERNS_5ErrorE'/>
<use f='llvm/llvm/lib/ExecutionEngine/Orc/LLJIT.cpp' l='1088' u='m' c='_ZN4llvm3orc5LLJITC1ERNS0_17LLJITBuilderStateERNS_5ErrorE'/>
<use f='llvm/llvm/lib/ExecutionEngine/Orc/LLJIT.cpp' l='1097' u='m' c='_ZN4llvm3orc5LLJITC1ERNS0_17LLJITBuilderStateERNS_5ErrorE'/>
<use f='llvm/llvm/lib/ExecutionEngine/Orc/LLJIT.cpp' l='1098' u='m' c='_ZN4llvm3orc5LLJITC1ERNS0_17LLJITBuilderStateERNS_5ErrorE'/>
<use f='llvm/llvm/lib/ExecutionEngine/Orc/LLJIT.cpp' l='1100' u='m' c='_ZN4llvm3orc5LLJITC1ERNS0_17LLJITBuilderStateERNS_5ErrorE'/>
<use f='llvm/llvm/lib/ExecutionEngine/Orc/LLJIT.cpp' l='1107' u='m' c='_ZN4llvm3orc5LLJITC1ERNS0_17LLJITBuilderStateERNS_5ErrorE'/>
<use f='llvm/llvm/lib/ExecutionEngine/Orc/LLJIT.cpp' l='1197' u='m' c='_ZN4llvm3orc9LLLazyJITC1ERNS0_21LLLazyJITBuilderStateERNS_5ErrorE'/>
<use f='llvm/llvm/lib/ExecutionEngine/Orc/LLJIT.cpp' l='1223' u='m' c='_ZN4llvm3orc9LLLazyJITC1ERNS0_21LLLazyJITBuilderStateERNS_5ErrorE'/>
