<dec f='llvm/llvm/lib/Target/AMDGPU/R600InstrInfo.h' l='42' type='const llvm::R600Subtarget &amp;'/>
<offset>2880</offset>
<use f='llvm/llvm/lib/Target/AMDGPU/R600InstrInfo.cpp' l='32' u='w' c='_ZN4llvm13R600InstrInfoC1ERKNS_13R600SubtargetE'/>
<use f='llvm/llvm/lib/Target/AMDGPU/R600InstrInfo.cpp' l='155' u='m' c='_ZNK4llvm13R600InstrInfo11isTransOnlyEj'/>
<use f='llvm/llvm/lib/Target/AMDGPU/R600InstrInfo.cpp' l='177' u='m' c='_ZNK4llvm13R600InstrInfo15usesVertexCacheEj'/>
<use f='llvm/llvm/lib/Target/AMDGPU/R600InstrInfo.cpp' l='187' u='m' c='_ZNK4llvm13R600InstrInfo16usesTextureCacheEj'/>
<use f='llvm/llvm/lib/Target/AMDGPU/R600InstrInfo.cpp' l='1299' u='m' c='_ZNK4llvm13R600InstrInfo28buildSlotOfVectorInstructionERNS_17MachineBasicBlockEPNS_12MachineInstrEjj'/>
