<dec f='llvm/llvm/include/llvm/DebugInfo/DWARF/DWARFAcceleratorTable.h' l='265' type='dwarf::Tag'/>
<use f='llvm/llvm/include/llvm/DebugInfo/DWARF/DWARFAcceleratorTable.h' l='270' u='w' c='_ZN4llvm15DWARFDebugNames6AbbrevC1EjNS_5dwarf3TagESt6vectorINS0_17AttributeEncodingESaIS5_EE'/>
<use f='llvm/llvm/include/llvm/DebugInfo/DWARF/DWARFAcceleratorTable.h' l='298' u='r' c='_ZNK4llvm15DWARFDebugNames5Entry3tagEv'/>
<offset>32</offset>
<doc f='llvm/llvm/include/llvm/DebugInfo/DWARF/DWARFAcceleratorTable.h' l='265'>///&lt; Dwarf Tag of the described entity.</doc>
<use f='llvm/llvm/lib/DebugInfo/DWARF/DWARFAcceleratorTable.cpp' l='415' u='r' c='_ZNK4llvm15DWARFDebugNames6Abbrev4dumpERNS_13ScopedPrinterE'/>
<use f='llvm/llvm/lib/DebugInfo/DWARF/DWARFAcceleratorTable.cpp' l='573' u='r' c='_ZNK4llvm15DWARFDebugNames5Entry4dumpERNS_13ScopedPrinterE'/>
<use f='llvm/llvm/lib/DebugInfo/DWARF/DWARFVerifier.cpp' l='1202' u='r' c='_ZN4llvm13DWARFVerifier22verifyNameIndexAbbrevsERKNS_15DWARFDebugNames9NameIndexE'/>
<use f='llvm/llvm/lib/DebugInfo/DWARF/DWARFVerifier.cpp' l='1206' u='r' c='_ZN4llvm13DWARFVerifier22verifyNameIndexAbbrevsERKNS_15DWARFDebugNames9NameIndexE'/>
