<dec f='llvm/llvm/include/llvm/CodeGen/MIRParser/MIParser.h' l='43' type='union (anonymous union at /fast/tmp/llvm-proj-12/llvm/include/llvm/CodeGen/MIRParser/MIParser.h:40:3)'/>
<use f='llvm/llvm/lib/CodeGen/MIRParser/MIParser.cpp' l='1339' u='m' c='_ZN12_GLOBAL__N_18MIParser24parseRegisterClassOrBankERN4llvm8VRegInfoE'/>
<use f='llvm/llvm/lib/CodeGen/MIRParser/MIParser.cpp' l='1342' u='m' c='_ZN12_GLOBAL__N_18MIParser24parseRegisterClassOrBankERN4llvm8VRegInfoE'/>
<use f='llvm/llvm/lib/CodeGen/MIRParser/MIParser.cpp' l='1344' u='m' c='_ZN12_GLOBAL__N_18MIParser24parseRegisterClassOrBankERN4llvm8VRegInfoE'/>
<use f='llvm/llvm/lib/CodeGen/MIRParser/MIParser.cpp' l='1370' u='m' c='_ZN12_GLOBAL__N_18MIParser24parseRegisterClassOrBankERN4llvm8VRegInfoE'/>
<use f='llvm/llvm/lib/CodeGen/MIRParser/MIParser.cpp' l='1372' u='m' c='_ZN12_GLOBAL__N_18MIParser24parseRegisterClassOrBankERN4llvm8VRegInfoE'/>
<offset>64</offset>
<use f='llvm/llvm/lib/CodeGen/MIRParser/MIRParser.cpp' l='561' u='m' c='_ZN4llvm13MIRParserImpl17parseRegisterInfoERNS_25PerFunctionMIParsingStateERKNS_4yaml15MachineFunctionE'/>
<use f='llvm/llvm/lib/CodeGen/MIRParser/MIRParser.cpp' l='566' u='m' c='_ZN4llvm13MIRParserImpl17parseRegisterInfoERNS_25PerFunctionMIParsingStateERKNS_4yaml15MachineFunctionE'/>
<use f='llvm/llvm/lib/CodeGen/MIRParser/MIRParser.cpp' l='575' u='m' c='_ZN4llvm13MIRParserImpl17parseRegisterInfoERNS_25PerFunctionMIParsingStateERKNS_4yaml15MachineFunctionE'/>
<use f='llvm/llvm/lib/CodeGen/MIRParser/MIRParser.cpp' l='637' u='m' c='_ZN4llvm13MIRParserImpl17setupRegisterInfoERKNS_25PerFunctionMIParsingStateERKNS_4yaml15MachineFunctionE'/>
<use f='llvm/llvm/lib/CodeGen/MIRParser/MIRParser.cpp' l='644' u='m' c='_ZN4llvm13MIRParserImpl17setupRegisterInfoERKNS_25PerFunctionMIParsingStateERKNS_4yaml15MachineFunctionE'/>
