<dec f='llvm/llvm/lib/CodeGen/InterferenceCache.h' l='51' type='unsigned int'/>
<use f='llvm/llvm/lib/CodeGen/InterferenceCache.h' l='128' u='r' c='_ZN4llvm17InterferenceCache5Entry3getEj'/>
<use f='llvm/llvm/lib/CodeGen/InterferenceCache.cpp' l='92' u='w' c='_ZN4llvm17InterferenceCache5Entry10revalidateEPNS_17LiveIntervalUnionEPKNS_18TargetRegisterInfoE'/>
<use f='llvm/llvm/lib/CodeGen/InterferenceCache.cpp' l='106' u='w' c='_ZN4llvm17InterferenceCache5Entry5resetENS_10MCRegisterEPNS_17LiveIntervalUnionEPKNS_18TargetRegisterInfoEPKNS_15MachineFunctionE'/>
<use f='llvm/llvm/lib/CodeGen/InterferenceCache.cpp' l='160' u='r' c='_ZN4llvm17InterferenceCache5Entry6updateEj'/>
<use f='llvm/llvm/lib/CodeGen/InterferenceCache.cpp' l='209' u='r' c='_ZN4llvm17InterferenceCache5Entry6updateEj'/>
<offset>32</offset>
<doc f='llvm/llvm/lib/CodeGen/InterferenceCache.h' l='49'>/// Tag - Cache tag is changed when any of the underlying LiveIntervalUnions
    /// change.</doc>
