<dec f='llvm/llvm/include/llvm/Bitstream/BitstreamWriter.h' l='35' type='llvm::raw_fd_stream *'/>
<use f='llvm/llvm/include/llvm/Bitstream/BitstreamWriter.h' l='88' u='r' c='_ZNK4llvm15BitstreamWriter20GetNumOfFlushedBytesEv'/>
<use f='llvm/llvm/include/llvm/Bitstream/BitstreamWriter.h' l='88' u='r' c='_ZNK4llvm15BitstreamWriter20GetNumOfFlushedBytesEv'/>
<use f='llvm/llvm/include/llvm/Bitstream/BitstreamWriter.h' l='101' u='r' c='_ZN4llvm15BitstreamWriter11FlushToFileEv'/>
<use f='llvm/llvm/include/llvm/Bitstream/BitstreamWriter.h' l='105' u='r' c='_ZN4llvm15BitstreamWriter11FlushToFileEv'/>
<use f='llvm/llvm/include/llvm/Bitstream/BitstreamWriter.h' l='119' u='w' c='_ZN4llvm15BitstreamWriterC1ERNS_15SmallVectorImplIcEEPNS_13raw_fd_streamEj'/>
<use f='llvm/llvm/include/llvm/Bitstream/BitstreamWriter.h' l='156' u='r' c='_ZN4llvm15BitstreamWriter13BackpatchWordEmj'/>
<use f='llvm/llvm/include/llvm/Bitstream/BitstreamWriter.h' l='172' u='r' c='_ZN4llvm15BitstreamWriter13BackpatchWordEmj'/>
<use f='llvm/llvm/include/llvm/Bitstream/BitstreamWriter.h' l='173' u='r' c='_ZN4llvm15BitstreamWriter13BackpatchWordEmj'/>
<use f='llvm/llvm/include/llvm/Bitstream/BitstreamWriter.h' l='188' u='r' c='_ZN4llvm15BitstreamWriter13BackpatchWordEmj'/>
<use f='llvm/llvm/include/llvm/Bitstream/BitstreamWriter.h' l='189' u='r' c='_ZN4llvm15BitstreamWriter13BackpatchWordEmj'/>
<use f='llvm/llvm/include/llvm/Bitstream/BitstreamWriter.h' l='194' u='r' c='_ZN4llvm15BitstreamWriter13BackpatchWordEmj'/>
<offset>64</offset>
<doc f='llvm/llvm/include/llvm/Bitstream/BitstreamWriter.h' l='33'>/// FS - The file stream that Out flushes to. If FS is nullptr, it does not
  /// support read or seek, Out cannot be flushed until all data are written.</doc>
