<dec f='llvm/build/lib/Target/Sparc/SparcGenRegisterInfo.inc' l='180' type='160'/>
<use f='llvm/llvm/lib/Target/Sparc/AsmParser/SparcAsmParser.cpp' l='137'/>
<use f='llvm/build/lib/Target/Sparc/SparcGenAsmMatcher.inc' l='2141' c='_ZL20validateOperandClassRN4llvm18MCParsedAsmOperandEN12_GLOBAL__N_114MatchClassKindE'/>
<use f='llvm/llvm/lib/Target/Sparc/Disassembler/SparcDisassembler.cpp' l='62'/>
<use f='llvm/llvm/lib/Target/Sparc/SparcISelLowering.cpp' l='1028' u='r' c='_ZNK4llvm19SparcTargetLowering17getRegisterByNameEPKcNS_3LLTERKNS_15MachineFunctionE'/>
<use f='llvm/llvm/lib/Target/Sparc/SparcRegisterInfo.cpp' l='64' u='r' c='_ZNK4llvm17SparcRegisterInfo15getReservedRegsERKNS_15MachineFunctionE'/>
