<dec f='llvm/llvm/include/llvm/Analysis/ScalarEvolution.h' l='269' type='const llvm::SCEV *'/>
<use f='llvm/llvm/include/llvm/Analysis/ScalarEvolution.h' l='283' u='r' c='_ZNK4llvm18SCEVEqualPredicate6getLHSEv'/>
<offset>320</offset>
<doc f='llvm/llvm/include/llvm/Analysis/ScalarEvolution.h' l='268'>/// We assume that LHS == RHS.</doc>
<use f='llvm/llvm/lib/Analysis/ScalarEvolution.cpp' l='12878' u='w' c='_ZN4llvm18SCEVEqualPredicateC1ENS_19FoldingSetNodeIDRefEPKNS_4SCEVES4_'/>
<use f='llvm/llvm/lib/Analysis/ScalarEvolution.cpp' l='12889' u='r' c='_ZNK4llvm18SCEVEqualPredicate7impliesEPKNS_13SCEVPredicateE'/>
<use f='llvm/llvm/lib/Analysis/ScalarEvolution.cpp' l='12889' u='r' c='_ZNK4llvm18SCEVEqualPredicate7impliesEPKNS_13SCEVPredicateE'/>
<use f='llvm/llvm/lib/Analysis/ScalarEvolution.cpp' l='12894' u='r' c='_ZNK4llvm18SCEVEqualPredicate7getExprEv'/>
<use f='llvm/llvm/lib/Analysis/ScalarEvolution.cpp' l='12897' u='r' c='_ZNK4llvm18SCEVEqualPredicate5printERNS_11raw_ostreamEj'/>
