<dec f='llvm/llvm/lib/LineEditor/LineEditor.cpp' l='102' type='EditLine *'/>
<use f='llvm/llvm/lib/LineEditor/LineEditor.cpp' l='211' u='w' c='_ZN4llvm10LineEditorC1ENS_9StringRefES1_P8_IO_FILES3_S3_'/>
<use f='llvm/llvm/lib/LineEditor/LineEditor.cpp' l='214' u='r' c='_ZN4llvm10LineEditorC1ENS_9StringRefES1_P8_IO_FILES3_S3_'/>
<use f='llvm/llvm/lib/LineEditor/LineEditor.cpp' l='215' u='r' c='_ZN4llvm10LineEditorC1ENS_9StringRefES1_P8_IO_FILES3_S3_'/>
<use f='llvm/llvm/lib/LineEditor/LineEditor.cpp' l='216' u='r' c='_ZN4llvm10LineEditorC1ENS_9StringRefES1_P8_IO_FILES3_S3_'/>
<use f='llvm/llvm/lib/LineEditor/LineEditor.cpp' l='217' u='r' c='_ZN4llvm10LineEditorC1ENS_9StringRefES1_P8_IO_FILES3_S3_'/>
<use f='llvm/llvm/lib/LineEditor/LineEditor.cpp' l='219' u='r' c='_ZN4llvm10LineEditorC1ENS_9StringRefES1_P8_IO_FILES3_S3_'/>
<use f='llvm/llvm/lib/LineEditor/LineEditor.cpp' l='220' u='r' c='_ZN4llvm10LineEditorC1ENS_9StringRefES1_P8_IO_FILES3_S3_'/>
<use f='llvm/llvm/lib/LineEditor/LineEditor.cpp' l='222' u='r' c='_ZN4llvm10LineEditorC1ENS_9StringRefES1_P8_IO_FILES3_S3_'/>
<use f='llvm/llvm/lib/LineEditor/LineEditor.cpp' l='224' u='r' c='_ZN4llvm10LineEditorC1ENS_9StringRefES1_P8_IO_FILES3_S3_'/>
<use f='llvm/llvm/lib/LineEditor/LineEditor.cpp' l='226' u='r' c='_ZN4llvm10LineEditorC1ENS_9StringRefES1_P8_IO_FILES3_S3_'/>
<use f='llvm/llvm/lib/LineEditor/LineEditor.cpp' l='238' u='r' c='_ZN4llvm10LineEditorD1Ev'/>
<use f='llvm/llvm/lib/LineEditor/LineEditor.cpp' l='259' u='r' c='_ZNK4llvm10LineEditor8readLineB5cxx11Ev'/>
<offset>128</offset>
