<dec f='llvm/llvm/include/llvm/CodeGen/MachineConstantPool.h' l='122' type='const llvm::DataLayout &amp;'/>
<use f='llvm/llvm/include/llvm/CodeGen/MachineConstantPool.h' l='124' u='a' c='_ZNK4llvm19MachineConstantPool13getDataLayoutEv'/>
<use f='llvm/llvm/include/llvm/CodeGen/MachineConstantPool.h' l='129' u='w' c='_ZN4llvm19MachineConstantPoolC1ERKNS_10DataLayoutE'/>
<offset>448</offset>
<use f='llvm/llvm/lib/CodeGen/MachineFunction.cpp' l='1215' u='r' c='_ZN4llvm19MachineConstantPool20getConstantPoolIndexEPKNS_8ConstantENS_5AlignE'/>
