<use f='llvm/llvm/include/llvm/ExecutionEngine/Orc/Layer.h' l='69' u='w' c='_ZN4llvm3orc7IRLayerC1ERNS0_16ExecutionSessionERPKNS0_14IRSymbolMapper15ManglingOptionsE'/>
<use f='llvm/llvm/include/llvm/ExecutionEngine/Orc/Layer.h' l='74' u='a' c='_ZN4llvm3orc7IRLayer19getExecutionSessionEv'/>
<dec f='llvm/llvm/include/llvm/ExecutionEngine/Orc/Layer.h' l='113' type='llvm::orc::ExecutionSession &amp;'/>
<offset>128</offset>
