<dec f='llvm/llvm/lib/Target/PowerPC/PPCSubtarget.h' l='161' type='const llvm::PPCTargetMachine &amp;'/>
<use f='llvm/llvm/lib/Target/PowerPC/PPCSubtarget.h' l='212' u='a' c='_ZNK4llvm12PPCSubtarget16getTargetMachineEv'/>
<offset>3968</offset>
<use f='llvm/llvm/lib/Target/PowerPC/PPCSubtarget.cpp' l='59' u='w' c='_ZN4llvm12PPCSubtargetC1ERKNS_6TripleERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESB_RKNS_16PPCTargetMachineE'/>
<use f='llvm/llvm/lib/Target/PowerPC/PPCSubtarget.cpp' l='233' u='m' c='_ZNK4llvm12PPCSubtarget18isGVIndirectSymbolEPKNS_11GlobalValueE'/>
<use f='llvm/llvm/lib/Target/PowerPC/PPCSubtarget.cpp' l='235' u='m' c='_ZNK4llvm12PPCSubtarget18isGVIndirectSymbolEPKNS_11GlobalValueE'/>
<use f='llvm/llvm/lib/Target/PowerPC/PPCSubtarget.cpp' l='240' u='m' c='_ZNK4llvm12PPCSubtarget10isELFv2ABIEv'/>
<use f='llvm/llvm/lib/Target/PowerPC/PPCSubtarget.cpp' l='241' u='m' c='_ZNK4llvm12PPCSubtarget7isPPC64Ev'/>
