<use f='llvm/llvm/include/llvm/Support/BinaryStreamArray.h' l='97' u='w' c='_ZN4llvm14VarStreamArrayC1ERKT0_'/>
<use f='llvm/llvm/include/llvm/Support/BinaryStreamArray.h' l='103' u='w' c='_ZN4llvm14VarStreamArrayC1ENS_15BinaryStreamRefERKT0_j'/>
<use f='llvm/llvm/include/llvm/Support/BinaryStreamArray.h' l='106' u='r' c='_ZNK4llvm14VarStreamArray5beginEPb'/>
<use f='llvm/llvm/include/llvm/Support/BinaryStreamArray.h' l='112' u='r' c='_ZNK4llvm14VarStreamArray3endEv'/>
<use f='llvm/llvm/include/llvm/Support/BinaryStreamArray.h' l='122' u='r' c='_ZNK4llvm14VarStreamArray9substreamEjj'/>
<use f='llvm/llvm/include/llvm/Support/BinaryStreamArray.h' l='130' u='r' c='_ZNK4llvm14VarStreamArray2atEj'/>
<use f='llvm/llvm/include/llvm/Support/BinaryStreamArray.h' l='133' u='a' c='_ZNK4llvm14VarStreamArray12getExtractorEv'/>
<use f='llvm/llvm/include/llvm/Support/BinaryStreamArray.h' l='134' u='a' c='_ZN4llvm14VarStreamArray12getExtractorEv'/>
<dec f='llvm/llvm/include/llvm/Support/BinaryStreamArray.h' l='146' type='Extractor'/>
