<use f='llvm/llvm/lib/CodeGen/AsmPrinter/DIEHash.h' l='35' u='w' c='_ZN4llvm7DIEHashC1EPNS_10AsmPrinterEPNS_16DwarfCompileUnitE'/>
<dec f='llvm/llvm/lib/CodeGen/AsmPrinter/DIEHash.h' l='105' type='llvm::DwarfCompileUnit *'/>
<offset>1280</offset>
<use f='llvm/llvm/lib/CodeGen/AsmPrinter/DIEHash.cpp' l='220' u='r' c='_ZN4llvm7DIEHash13hashBlockDataERKNS_14iterator_rangeINS_12DIEValueList20const_value_iteratorEEE'/>
