<dec f='llvm/llvm/include/llvm/XRay/FDRRecordProducer.h' l='29' type='llvm::DataExtractor &amp;'/>
<use f='llvm/llvm/include/llvm/XRay/FDRRecordProducer.h' l='40' u='w' c='_ZN4llvm4xray23FileBasedRecordProducerC1ERKNS0_14XRayFileHeaderERNS_13DataExtractorERm'/>
<use f='llvm/llvm/lib/XRay/FDRRecordProducer.cpp' l='88' u='m' c='_ZN4llvm4xray23FileBasedRecordProducer20findNextBufferExtentEv'/>
<use f='llvm/llvm/lib/XRay/FDRRecordProducer.cpp' l='102' u='a' c='_ZN4llvm4xray23FileBasedRecordProducer20findNextBufferExtentEv'/>
<use f='llvm/llvm/lib/XRay/FDRRecordProducer.cpp' l='150' u='m' c='_ZN4llvm4xray23FileBasedRecordProducer7produceEv'/>
<use f='llvm/llvm/lib/XRay/FDRRecordProducer.cpp' l='172' u='a' c='_ZN4llvm4xray23FileBasedRecordProducer7produceEv'/>
<offset>128</offset>
