<dec f='llvm/build/lib/Target/AArch64/AArch64GenInstrInfo.inc' l='878' type='863'/>
<use f='llvm/llvm/lib/Target/AArch64/AArch64InstrInfo.h' l='395' u='r' c='_ZN4llvmL20isUncondBranchOpcodeEi'/>
<use f='llvm/llvm/lib/Target/AArch64/AArch64AsmPrinter.cpp' l='282' u='r' c='_ZN12_GLOBAL__N_117AArch64AsmPrinter8EmitSledERKN4llvm12MachineInstrENS1_10AsmPrinter8SledKindE'/>
<use f='llvm/llvm/lib/Target/AArch64/AArch64AsmPrinter.cpp' l='515' u='r' c='_ZN12_GLOBAL__N_117AArch64AsmPrinter26EmitHwasanMemaccessSymbolsERN4llvm6ModuleE'/>
<use f='llvm/llvm/lib/Target/AArch64/AArch64AsmPrinter.cpp' l='1227' u='r' c='_ZN12_GLOBAL__N_117AArch64AsmPrinter15emitInstructionEPKN4llvm12MachineInstrE'/>
<use f='llvm/llvm/lib/Target/AArch64/AArch64FastISel.cpp' l='2494' u='r' c='_ZN12_GLOBAL__N_115AArch64FastISel12selectBranchEPKN4llvm11InstructionE'/>
<use f='llvm/build/lib/Target/AArch64/AArch64GenDAGISel.inc' l='126562' u='r' c='_ZN12_GLOBAL__N_119AArch64DAGToDAGISel10SelectCodeEPN4llvm6SDNodeE'/>
<use f='llvm/build/lib/Target/AArch64/AArch64GenDAGISel.inc' l='126562' u='r' c='_ZN12_GLOBAL__N_119AArch64DAGToDAGISel10SelectCodeEPN4llvm6SDNodeE'/>
<use f='llvm/llvm/lib/Target/AArch64/AArch64ISelLowering.cpp' l='2038' u='r' c='_ZNK4llvm21AArch64TargetLowering12EmitF128CSELERNS_12MachineInstrEPNS_17MachineBasicBlockE'/>
<use f='llvm/llvm/lib/Target/AArch64/AArch64InstrInfo.cpp' l='191' c='_ZL25getBranchDisplacementBitsj'/>
<use f='llvm/llvm/lib/Target/AArch64/AArch64InstrInfo.cpp' l='221' c='_ZNK4llvm16AArch64InstrInfo18getBranchDestBlockERKNS_12MachineInstrE'/>
<use f='llvm/llvm/lib/Target/AArch64/AArch64InstrInfo.cpp' l='507' u='r' c='_ZNK4llvm16AArch64InstrInfo12insertBranchERNS_17MachineBasicBlockEPS1_S3_NS_8ArrayRefINS_14MachineOperandEEERKNS_8DebugLocEPi'/>
<use f='llvm/llvm/lib/Target/AArch64/AArch64InstrInfo.cpp' l='519' u='r' c='_ZNK4llvm16AArch64InstrInfo12insertBranchERNS_17MachineBasicBlockEPS1_S3_NS_8ArrayRefINS_14MachineOperandEEERKNS_8DebugLocEPi'/>
<use f='llvm/build/lib/Target/AArch64/AArch64GenGlobalISel.inc' l='62047' u='r' c='_ZNK12_GLOBAL__N_126AArch64InstructionSelector13getMatchTableEv'/>
<use f='llvm/build/lib/Target/AArch64/AArch64GenMCCodeEmitter.inc' l='15930' c='_ZNK12_GLOBAL__N_120AArch64MCCodeEmitter21getBinaryCodeForInstrERKN4llvm6MCInstERNS1_15SmallVectorImplINS1_7MCFixupEEERKNS1_15MCSubtargetInfoE'/>
