<use f='llvm/llvm/tools/llvm-pdbutil/LinePrinter.h' l='158' u='a' c='_ZN4llvm3pdb9WithColor3getEv'/>
<dec f='llvm/llvm/tools/llvm-pdbutil/LinePrinter.h' l='162' type='llvm::raw_ostream &amp;'/>
<offset>0</offset>
<use f='llvm/llvm/tools/llvm-pdbutil/LinePrinter.cpp' l='288' u='w' c='_ZN4llvm3pdb9WithColorC1ERNS0_11LinePrinterENS0_13PDB_ColorItemE'/>
<use f='llvm/llvm/tools/llvm-pdbutil/LinePrinter.cpp' l='295' u='m' c='_ZN4llvm3pdb9WithColorD1Ev'/>
<use f='llvm/llvm/tools/llvm-pdbutil/LinePrinter.cpp' l='301' u='m' c='_ZN4llvm3pdb9WithColor10applyColorENS0_13PDB_ColorItemE'/>
<use f='llvm/llvm/tools/llvm-pdbutil/LinePrinter.cpp' l='304' u='m' c='_ZN4llvm3pdb9WithColor10applyColorENS0_13PDB_ColorItemE'/>
<use f='llvm/llvm/tools/llvm-pdbutil/LinePrinter.cpp' l='307' u='m' c='_ZN4llvm3pdb9WithColor10applyColorENS0_13PDB_ColorItemE'/>
<use f='llvm/llvm/tools/llvm-pdbutil/LinePrinter.cpp' l='310' u='m' c='_ZN4llvm3pdb9WithColor10applyColorENS0_13PDB_ColorItemE'/>
<use f='llvm/llvm/tools/llvm-pdbutil/LinePrinter.cpp' l='314' u='m' c='_ZN4llvm3pdb9WithColor10applyColorENS0_13PDB_ColorItemE'/>
<use f='llvm/llvm/tools/llvm-pdbutil/LinePrinter.cpp' l='317' u='m' c='_ZN4llvm3pdb9WithColor10applyColorENS0_13PDB_ColorItemE'/>
<use f='llvm/llvm/tools/llvm-pdbutil/LinePrinter.cpp' l='320' u='m' c='_ZN4llvm3pdb9WithColor10applyColorENS0_13PDB_ColorItemE'/>
<use f='llvm/llvm/tools/llvm-pdbutil/LinePrinter.cpp' l='323' u='m' c='_ZN4llvm3pdb9WithColor10applyColorENS0_13PDB_ColorItemE'/>
<use f='llvm/llvm/tools/llvm-pdbutil/LinePrinter.cpp' l='327' u='m' c='_ZN4llvm3pdb9WithColor10applyColorENS0_13PDB_ColorItemE'/>
<use f='llvm/llvm/tools/llvm-pdbutil/LinePrinter.cpp' l='330' u='m' c='_ZN4llvm3pdb9WithColor10applyColorENS0_13PDB_ColorItemE'/>
