<dec f='llvm/llvm/include/llvm/Analysis/MemoryBuiltins.h' l='233' type='const llvm::DataLayout &amp;'/>
<offset>0</offset>
<use f='llvm/llvm/lib/Analysis/MemoryBuiltins.cpp' l='605' u='w' c='_ZN4llvm23ObjectSizeOffsetVisitorC1ERKNS_10DataLayoutEPKNS_17TargetLibraryInfoERNS_11LLVMContextENS_14ObjectSizeOptsE'/>
<use f='llvm/llvm/lib/Analysis/MemoryBuiltins.cpp' l='611' u='m' c='_ZN4llvm23ObjectSizeOffsetVisitor7computeEPNS_5ValueE'/>
<use f='llvm/llvm/lib/Analysis/MemoryBuiltins.cpp' l='670' u='m' c='_ZN4llvm23ObjectSizeOffsetVisitor15visitAllocaInstERNS_10AllocaInstE'/>
<use f='llvm/llvm/lib/Analysis/MemoryBuiltins.cpp' l='696' u='m' c='_ZN4llvm23ObjectSizeOffsetVisitor13visitArgumentERNS_8ArgumentE'/>
<use f='llvm/llvm/lib/Analysis/MemoryBuiltins.cpp' l='785' u='m' c='_ZN4llvm23ObjectSizeOffsetVisitor16visitGEPOperatorERNS_11GEPOperatorE'/>
<use f='llvm/llvm/lib/Analysis/MemoryBuiltins.cpp' l='786' u='r' c='_ZN4llvm23ObjectSizeOffsetVisitor16visitGEPOperatorERNS_11GEPOperatorE'/>
<use f='llvm/llvm/lib/Analysis/MemoryBuiltins.cpp' l='802' u='m' c='_ZN4llvm23ObjectSizeOffsetVisitor19visitGlobalVariableERNS_14GlobalVariableE'/>
