<dec f='llvm/llvm/include/llvm/Remarks/RemarkSerializer.h' l='42' type='llvm::raw_ostream &amp;'/>
<use f='llvm/llvm/include/llvm/Remarks/RemarkSerializer.h' l='51' u='w' c='_ZN4llvm7remarks16RemarkSerializerC1ENS0_6FormatERNS_11raw_ostreamENS0_14SerializerModeE'/>
<use f='llvm/llvm/include/llvm/Remarks/RemarkStreamer.h' l='59' u='a' c='_ZN4llvm7remarks14RemarkStreamer9getStreamEv'/>
<offset>128</offset>
<doc f='llvm/llvm/include/llvm/Remarks/RemarkSerializer.h' l='41'>/// The open raw_ostream that the remark diagnostics are emitted to.</doc>
<use f='llvm/llvm/lib/Remarks/BitstreamRemarkSerializer.cpp' l='355' u='a' c='_ZN4llvm7remarks25BitstreamRemarkSerializer4emitERKNS0_6RemarkE'/>
<use f='llvm/llvm/lib/Remarks/BitstreamRemarkSerializer.cpp' l='365' u='a' c='_ZN4llvm7remarks25BitstreamRemarkSerializer4emitERKNS0_6RemarkE'/>
<use f='llvm/llvm/lib/Remarks/YAMLRemarkSerializer.cpp' l='191' u='a' c='_ZN4llvm7remarks26YAMLStrTabRemarkSerializer4emitERKNS0_6RemarkE'/>
