<dec f='llvm/llvm/include/llvm/CodeGen/AsmPrinter.h' l='212' type='llvm::PseudoProbeHandler *'/>
<offset>3456</offset>
<doc f='llvm/llvm/include/llvm/CodeGen/AsmPrinter.h' l='210'>/// A handler that supports pseudo probe emission with embedded inline
  /// context.</doc>
<use f='llvm/llvm/lib/CodeGen/AsmPrinter/AsmPrinter.cpp' l='344' u='w' c='_ZN4llvm10AsmPrinter16doInitializationERNS_6ModuleE'/>
<use f='llvm/llvm/lib/CodeGen/AsmPrinter/AsmPrinter.cpp' l='345' u='r' c='_ZN4llvm10AsmPrinter16doInitializationERNS_6ModuleE'/>
<use f='llvm/llvm/lib/CodeGen/AsmPrinter/AsmPrinter.cpp' l='1116' u='r' c='_ZN4llvm10AsmPrinter15emitPseudoProbeERKNS_12MachineInstrE'/>
