<dec f='llvm/llvm/lib/Target/X86/ImmutableGraph.h' l='201' type='llvm::BitVector'/>
<use f='llvm/llvm/lib/Target/X86/ImmutableGraph.h' l='205' u='w' c='_ZN4llvm14ImmutableGraph7EdgeSetC1ERKNS_14ImmutableGraphIT_T0_EEb'/>
<use f='llvm/llvm/lib/Target/X86/ImmutableGraph.h' l='208' u='m' c='_ZN4llvm14ImmutableGraph7EdgeSet6insertERKNS0_4EdgeE'/>
<use f='llvm/llvm/lib/Target/X86/ImmutableGraph.h' l='209' u='m' c='_ZN4llvm14ImmutableGraph7EdgeSet6insertERKNS0_4EdgeE'/>
<use f='llvm/llvm/lib/Target/X86/ImmutableGraph.h' l='214' u='m' c='_ZN4llvm14ImmutableGraph7EdgeSet5eraseERKNS0_4EdgeE'/>
<use f='llvm/llvm/lib/Target/X86/ImmutableGraph.h' l='218' u='m' c='_ZNK4llvm14ImmutableGraph7EdgeSet8containsERKNS0_4EdgeE'/>
<use f='llvm/llvm/lib/Target/X86/ImmutableGraph.h' l='220' u='m' c='_ZN4llvm14ImmutableGraph7EdgeSet5clearEv'/>
<use f='llvm/llvm/lib/Target/X86/ImmutableGraph.h' l='221' u='m' c='_ZNK4llvm14ImmutableGraph7EdgeSet5emptyEv'/>
<use f='llvm/llvm/lib/Target/X86/ImmutableGraph.h' l='223' u='m' c='_ZNK4llvm14ImmutableGraph7EdgeSet5countEv'/>
<use f='llvm/llvm/lib/Target/X86/ImmutableGraph.h' l='225' u='m' c='_ZNK4llvm14ImmutableGraph7EdgeSet4sizeEv'/>
<use f='llvm/llvm/lib/Target/X86/ImmutableGraph.h' l='229' u='w' c='_ZN4llvm14ImmutableGraph7EdgeSetoRERKS1_'/>
<use f='llvm/llvm/lib/Target/X86/ImmutableGraph.h' l='235' u='w' c='_ZN4llvm14ImmutableGraph7EdgeSetaNERKS1_'/>
<use f='llvm/llvm/lib/Target/X86/ImmutableGraph.h' l='241' u='w' c='_ZN4llvm14ImmutableGraph7EdgeSeteOERKS1_'/>
<use f='llvm/llvm/lib/Target/X86/ImmutableGraph.h' l='246' u='m' c='_ZNK4llvm14ImmutableGraph7EdgeSet11index_beginEv'/>
<use f='llvm/llvm/lib/Target/X86/ImmutableGraph.h' l='247' u='m' c='_ZNK4llvm14ImmutableGraph7EdgeSet9index_endEv'/>
<use f='llvm/llvm/lib/Target/X86/ImmutableGraph.h' l='248' u='m' c='_ZN4llvm14ImmutableGraph7EdgeSet3setEi'/>
<use f='llvm/llvm/lib/Target/X86/ImmutableGraph.h' l='249' u='m' c='_ZN4llvm14ImmutableGraph7EdgeSet5resetEi'/>
<use f='llvm/llvm/lib/Target/X86/ImmutableGraph.h' l='283' u='m' c='_ZNK4llvm14ImmutableGraph7EdgeSet5beginEv'/>
