<use f='llvm/llvm/unittests/ExecutionEngine/Orc/OrcTestCommon.h' l='184' u='m' c='_ZN4llvm13ModuleBuilder18createFunctionDeclEPNS_12FunctionTypeENS_9StringRefE'/>
<use f='llvm/llvm/unittests/ExecutionEngine/Orc/OrcTestCommon.h' l='187' u='m' c='_ZN4llvm13ModuleBuilder9getModuleEv'/>
<use f='llvm/llvm/unittests/ExecutionEngine/Orc/OrcTestCommon.h' l='188' u='m' c='_ZNK4llvm13ModuleBuilder9getModuleEv'/>
<use f='llvm/llvm/unittests/ExecutionEngine/Orc/OrcTestCommon.h' l='189' u='a' c='_ZN4llvm13ModuleBuilder10takeModuleEv'/>
<dec f='llvm/llvm/unittests/ExecutionEngine/Orc/OrcTestCommon.h' l='192' type='std::unique_ptr&lt;Module&gt;'/>
<offset>0</offset>
<use f='llvm/llvm/unittests/ExecutionEngine/Orc/OrcTestCommon.cpp' l='26' u='w' c='_ZN4llvm13ModuleBuilderC1ERNS_11LLVMContextENS_9StringRefES3_'/>
<use f='llvm/llvm/unittests/ExecutionEngine/Orc/OrcTestCommon.cpp' l='28' u='m' c='_ZN4llvm13ModuleBuilderC1ERNS_11LLVMContextENS_9StringRefES3_'/>
