<dec f='llvm/llvm/lib/Target/AMDGPU/AMDGPUTargetTransformInfo.h' l='229' type='const llvm::R600Subtarget *'/>
<use f='llvm/llvm/lib/Target/AMDGPU/AMDGPUTargetTransformInfo.h' l='236' u='r' c='_ZNK4llvm11R600TTIImpl5getSTEv'/>
<offset>128</offset>
<use f='llvm/llvm/lib/Target/AMDGPU/AMDGPUTargetTransformInfo.cpp' l='1201' u='w' c='_ZN4llvm11R600TTIImplC1EPKNS_19AMDGPUTargetMachineERKNS_8FunctionE'/>
<use f='llvm/llvm/lib/Target/AMDGPU/AMDGPUTargetTransformInfo.cpp' l='1202' u='r' c='_ZN4llvm11R600TTIImplC1EPKNS_19AMDGPUTargetMachineERKNS_8FunctionE'/>
