<dec f='llvm/llvm/include/llvm/Transforms/IPO/SampleProfileProbe.h' l='131' type='llvm::TargetMachine *'/>
<use f='llvm/llvm/include/llvm/Transforms/IPO/SampleProfileProbe.h' l='134' u='w' c='_ZN4llvm22SampleProfileProbePassC1EPNS_13TargetMachineE'/>
<offset>0</offset>
<use f='llvm/llvm/lib/Transforms/IPO/SampleProfileProbe.cpp' l='386' u='r' c='_ZN4llvm22SampleProfileProbePass3runERNS_6ModuleERNS_15AnalysisManagerIS1_JEEE'/>
