<dec f='llvm/llvm/include/llvm/IR/LegacyPassManagers.h' l='113' type='llvm::Module *'/>
<use f='llvm/llvm/include/llvm/IR/LegacyPassManagers.h' l='117' u='w' c='_ZN4llvm27PassManagerPrettyStackEntryC1EPNS_4PassE'/>
<use f='llvm/llvm/include/llvm/IR/LegacyPassManagers.h' l='119' u='w' c='_ZN4llvm27PassManagerPrettyStackEntryC1EPNS_4PassERNS_5ValueE'/>
<use f='llvm/llvm/include/llvm/IR/LegacyPassManagers.h' l='121' u='w' c='_ZN4llvm27PassManagerPrettyStackEntryC1EPNS_4PassERNS_6ModuleE'/>
<offset>256</offset>
<use f='llvm/llvm/lib/IR/LegacyPassManager.cpp' l='215' u='r' c='_ZNK4llvm27PassManagerPrettyStackEntry5printERNS_11raw_ostreamE'/>
<use f='llvm/llvm/lib/IR/LegacyPassManager.cpp' l='222' u='r' c='_ZNK4llvm27PassManagerPrettyStackEntry5printERNS_11raw_ostreamE'/>
<use f='llvm/llvm/lib/IR/LegacyPassManager.cpp' l='223' u='r' c='_ZNK4llvm27PassManagerPrettyStackEntry5printERNS_11raw_ostreamE'/>
<use f='llvm/llvm/lib/IR/LegacyPassManager.cpp' l='240' u='r' c='_ZNK4llvm27PassManagerPrettyStackEntry5printERNS_11raw_ostreamE'/>
