<dec f='llvm/llvm/include/llvm/ADT/iterator.h' l='363' type='NodeRef'/>
<use f='llvm/llvm/include/llvm/ADT/iterator.h' l='368' u='w' c='_ZN4llvm27WrappedPairNodeDataIteratorC1ET_T1_'/>
<use f='llvm/llvm/include/llvm/ADT/iterator.h' l='372' u='w' c='_ZNK4llvm27WrappedPairNodeDataIteratordeEv'/>
<use f='llvm/llvm/include/llvm/ADT/iterator.h' l='373' u='a' c='_ZNK4llvm27WrappedPairNodeDataIteratordeEv'/>
