<dec f='llvm/llvm/include/llvm/CodeGen/SwitchLoweringUtils.h' l='94' type='llvm::MachineBasicBlock *'/>
<use f='llvm/llvm/include/llvm/CodeGen/SwitchLoweringUtils.h' l='101' u='w' c='_ZN4llvm8SwitchCG8CaseBitsC1EmPNS_17MachineBasicBlockEjNS_17BranchProbabilityE'/>
<offset>64</offset>
<use f='llvm/llvm/lib/CodeGen/SwitchLoweringUtils.cpp' l='422' u='r' c='_ZN4llvm8SwitchCG14SwitchLowering13buildBitTestsERSt6vectorINS0_11CaseClusterESaIS3_EEjjPKNS_10SwitchInstERS3_'/>
<use f='llvm/llvm/lib/CodeGen/SwitchLoweringUtils.cpp' l='452' u='r' c='_ZN4llvm8SwitchCG14SwitchLowering13buildBitTestsERSt6vectorINS0_11CaseClusterESaIS3_EEjjPKNS_10SwitchInstERS3_'/>
