<dec f='llvm/build/lib/Target/XCore/XCoreGenRegisterInfo.inc' l='24' type='4'/>
<use f='llvm/llvm/lib/Target/XCore/MCTargetDesc/XCoreMCTargetDesc.cpp' l='63' u='r' c='_ZL20createXCoreMCAsmInfoRKN4llvm14MCRegisterInfoERKNS_6TripleERKNS_15MCTargetOptionsE'/>
<use f='llvm/llvm/lib/Target/XCore/XCoreFrameLowering.cpp' l='129' u='r' c='_ZL14IfNeededLDAWSPRN4llvm17MachineBasicBlockENS_26MachineInstrBundleIteratorINS_12MachineInstrELb0EEERKNS_8DebugLocERKNS_15TargetInstrInfoEiRi'/>
<use f='llvm/llvm/lib/Target/XCore/XCoreFrameLowering.cpp' l='409' u='r' c='_ZNK4llvm18XCoreFrameLowering12emitEpilogueERNS_15MachineFunctionERNS_17MachineBasicBlockE'/>
<use f='llvm/llvm/lib/Target/XCore/XCoreFrameLowering.cpp' l='515' u='r' c='_ZNK4llvm18XCoreFrameLowering29eliminateCallFramePseudoInstrERNS_15MachineFunctionERNS_17MachineBasicBlockENS_26MachineInstrBundleIteratorINS_12MachineInstrELb0EEE'/>
<use f='llvm/llvm/lib/Target/XCore/XCoreISelLowering.cpp' l='82' u='r' c='_ZN4llvm19XCoreTargetLoweringC1ERKNS_13TargetMachineERKNS_14XCoreSubtargetE'/>
<use f='llvm/llvm/lib/Target/XCore/XCoreInstrInfo.cpp' l='345' u='r' c='_ZNK4llvm14XCoreInstrInfo11copyPhysRegERNS_17MachineBasicBlockENS_26MachineInstrBundleIteratorINS_12MachineInstrELb0EEERKNS_8DebugLocENS_10MCRegisterES9_b'/>
<use f='llvm/llvm/lib/Target/XCore/XCoreInstrInfo.cpp' l='350' u='r' c='_ZNK4llvm14XCoreInstrInfo11copyPhysRegERNS_17MachineBasicBlockENS_26MachineInstrBundleIteratorINS_12MachineInstrELb0EEERKNS_8DebugLocENS_10MCRegisterES9_b'/>
<use f='llvm/llvm/lib/Target/XCore/XCoreRegisterInfo.cpp' l='235' u='r' c='_ZNK4llvm17XCoreRegisterInfo15getReservedRegsERKNS_15MachineFunctionE'/>
<use f='llvm/llvm/lib/Target/XCore/XCoreRegisterInfo.cpp' l='322' u='r' c='_ZNK4llvm17XCoreRegisterInfo16getFrameRegisterERKNS_15MachineFunctionE'/>
