<dec f='llvm/llvm/tools/llvm-xray/xray-graph.h' l='71' type='llvm::xray::GraphRenderer::TimeStat'/>
<use f='llvm/llvm/tools/llvm-xray/xray-graph-diff.cpp' l='283' u='r' c='_ZL8getColorB5cxx11RKN4llvm6detail12DenseMapPairINS_9StringRefENS_4xray17GraphDiffRenderer15VertexAttributeEEERKNS3_5GraphIS5_NS4_13EdgeAttributeES2_E14713852'/>
<use f='llvm/llvm/tools/llvm-xray/xray-graph-diff.cpp' l='284' u='r' c='_ZL8getColorB5cxx11RKN4llvm6detail12DenseMapPairINS_9StringRefENS_4xray17GraphDiffRenderer15VertexAttributeEEERKNS3_5GraphIS5_NS4_13EdgeAttributeES2_E14713852'/>
<use f='llvm/llvm/tools/llvm-xray/xray-graph-diff.cpp' l='334' u='r' c='_ZL8getLabelB5cxx11RKN4llvm6detail12DenseMapPairINS_9StringRefENS_4xray17GraphDiffRenderer15VertexAttributeEEENS3_13GraphRenderer8StatTypeEi'/>
<use f='llvm/llvm/tools/llvm-xray/xray-graph-diff.cpp' l='335' u='r' c='_ZL8getLabelB5cxx11RKN4llvm6detail12DenseMapPairINS_9StringRefENS_4xray17GraphDiffRenderer15VertexAttributeEEENS3_13GraphRenderer8StatTypeEi'/>
<offset>256</offset>
<use f='llvm/llvm/tools/llvm-xray/xray-graph.cpp' l='252' u='a' c='_ZN4llvm4xray13GraphRenderer13accountRecordERKNS0_10XRayRecordE'/>
<use f='llvm/llvm/tools/llvm-xray/xray-graph.cpp' l='262' u='a' c='_ZN4llvm4xray13GraphRenderer13accountRecordERKNS0_10XRayRecordE'/>
<use f='llvm/llvm/tools/llvm-xray/xray-graph.cpp' l='317' u='a' c='_ZN4llvm4xray13GraphRenderer25calculateVertexStatisticsEv'/>
<use f='llvm/llvm/tools/llvm-xray/xray-graph.cpp' l='318' u='r' c='_ZN4llvm4xray13GraphRenderer25calculateVertexStatisticsEv'/>
<use f='llvm/llvm/tools/llvm-xray/xray-graph.cpp' l='340' u='a' c='_ZN4llvm4xray13GraphRenderer19normalizeStatisticsEd'/>
<use f='llvm/llvm/tools/llvm-xray/xray-graph.cpp' l='428' u='m' c='_ZN4llvm4xray13GraphRenderer16exportGraphAsDOTERNS_11raw_ostreamENS1_8StatTypeES4_S4_S4_'/>
<use f='llvm/llvm/tools/llvm-xray/xray-graph.cpp' l='434' u='m' c='_ZN4llvm4xray13GraphRenderer16exportGraphAsDOTERNS_11raw_ostreamENS1_8StatTypeES4_S4_S4_'/>
