<dec f='llvm/llvm/include/llvm/Analysis/ScalarEvolutionExpressions.h' l='355' type='const llvm::Loop *'/>
<use f='llvm/llvm/include/llvm/Analysis/ScalarEvolutionExpressions.h' l='359' u='w' c='_ZN4llvm14SCEVAddRecExprC1ENS_19FoldingSetNodeIDRefEPKPKNS_4SCEVEmPKNS_4LoopE'/>
<use f='llvm/llvm/include/llvm/Analysis/ScalarEvolutionExpressions.h' l='363' u='r' c='_ZNK4llvm14SCEVAddRecExpr7getLoopEv'/>
<offset>384</offset>
