<dec f='llvm/llvm/include/llvm/Transforms/Utils/ScalarEvolutionExpander.h' l='127' type='llvm::IRBuilderBase &amp;'/>
<use f='llvm/llvm/include/llvm/Transforms/Utils/ScalarEvolutionExpander.h' l='138' u='w' c='_ZN4llvm12SCEVExpander20SCEVInsertPointGuardC1ERNS_13IRBuilderBaseEPS0_'/>
<use f='llvm/llvm/include/llvm/Transforms/Utils/ScalarEvolutionExpander.h' l='149' u='m' c='_ZN4llvm12SCEVExpander20SCEVInsertPointGuardD1Ev'/>
<use f='llvm/llvm/include/llvm/Transforms/Utils/ScalarEvolutionExpander.h' l='150' u='m' c='_ZN4llvm12SCEVExpander20SCEVInsertPointGuardD1Ev'/>
<offset>0</offset>
