<dec f='llvm/llvm/include/llvm/DWARFLinker/DWARFLinkerCompileUnit.h' l='30' type='DIE::value_iterator'/>
<use f='llvm/llvm/include/llvm/DWARFLinker/DWARFLinkerCompileUnit.h' l='33' u='w' c='_ZN4llvm13PatchLocationC1ENS_12DIEValueList14value_iteratorE'/>
<use f='llvm/llvm/include/llvm/DWARFLinker/DWARFLinkerCompileUnit.h' l='37' u='m' c='_ZNK4llvm13PatchLocation3setEm'/>
<use f='llvm/llvm/include/llvm/DWARFLinker/DWARFLinkerCompileUnit.h' l='39' u='m' c='_ZNK4llvm13PatchLocation3setEm'/>
<use f='llvm/llvm/include/llvm/DWARFLinker/DWARFLinkerCompileUnit.h' l='44' u='m' c='_ZNK4llvm13PatchLocation3getEv'/>
<offset>0</offset>
