<dec f='llvm/llvm/include/llvm/IR/LegacyPassManager.h' l='63' type='llvm::legacy::PassManagerImpl *'/>
<offset>64</offset>
<doc f='llvm/llvm/include/llvm/IR/LegacyPassManager.h' l='61'>/// PassManagerImpl_New is the actual class. PassManager is just the
  /// wraper to publish simple pass manager interface</doc>
<use f='llvm/llvm/lib/IR/LegacyPassManager.cpp' l='1661' u='w' c='_ZN4llvm6legacy11PassManagerC1Ev'/>
<use f='llvm/llvm/lib/IR/LegacyPassManager.cpp' l='1663' u='r' c='_ZN4llvm6legacy11PassManagerC1Ev'/>
<use f='llvm/llvm/lib/IR/LegacyPassManager.cpp' l='1663' u='r' c='_ZN4llvm6legacy11PassManagerC1Ev'/>
<use f='llvm/llvm/lib/IR/LegacyPassManager.cpp' l='1667' u='r' c='_ZN4llvm6legacy11PassManagerD1Ev'/>
<use f='llvm/llvm/lib/IR/LegacyPassManager.cpp' l='1671' u='r' c='_ZN4llvm6legacy11PassManager3addEPNS_4PassE'/>
<use f='llvm/llvm/lib/IR/LegacyPassManager.cpp' l='1677' u='r' c='_ZN4llvm6legacy11PassManager3runERNS_6ModuleE'/>
