<dec f='llvm/llvm/include/llvm/MC/MCExpr.h' l='493' type='10'/>
<use f='llvm/llvm/include/llvm/MC/MCExpr.h' l='572' u='r' c='_ZN4llvm12MCBinaryExpr9createModEPKNS_6MCExprES3_RNS_9MCContextE'/>
<doc f='llvm/llvm/include/llvm/MC/MCExpr.h' l='492'>///&lt; some target-specific non-zero value).</doc>
<doc f='llvm/llvm/include/llvm/MC/MCExpr.h' l='493'>///&lt; Signed remainder.</doc>
<use f='llvm/llvm/lib/MC/MCExpr.cpp' l='149' c='_ZNK4llvm6MCExpr5printERNS_11raw_ostreamEPKNS_9MCAsmInfoEb'/>
<use f='llvm/llvm/lib/MC/MCExpr.cpp' l='946' c='_ZNK4llvm6MCExpr25evaluateAsRelocatableImplERNS_7MCValueEPKNS_11MCAssemblerEPKNS_11MCAsmLayoutEPKNS_7MCFixupEPKNS_8DenseMapIPKNS_9MCSectionEmNS_12Dens14347918'/>
<use f='llvm/llvm/lib/MC/MCParser/AsmParser.cpp' l='1566' u='r' c='_ZL24getDarwinBinOpPrecedenceN4llvm8AsmToken9TokenKindERNS_12MCBinaryExpr6OpcodeEb'/>
<use f='llvm/llvm/lib/MC/MCParser/AsmParser.cpp' l='1643' u='r' c='_ZL21getGNUBinOpPrecedenceRKN4llvm9MCAsmInfoENS_8AsmToken9TokenKindERNS_12MCBinaryExpr6OpcodeEb'/>
<use f='llvm/llvm/lib/MC/MCParser/MasmParser.cpp' l='1889' u='r' c='_ZL21getGNUBinOpPrecedenceN4llvm8AsmToken9TokenKindERNS_12MCBinaryExpr6OpcodeEbb'/>
<use f='llvm/llvm/lib/Target/Mips/AsmParser/MipsAsmParser.cpp' l='6520' u='r' c='_ZN12_GLOBAL__N_113MipsAsmParser15parseMemOperandERN4llvm15SmallVectorImplISt10unique_ptrINS1_18MCParsedAsmOperandESt14default_deleteIS4_EEEE'/>
