<dec f='llvm/llvm/tools/llvm-exegesis/lib/Analysis.h' l='102' type='llvm::exegesis::ResolvedSchedClass'/>
<use f='llvm/llvm/tools/llvm-exegesis/lib/Analysis.cpp' l='210' u='w' c='_ZN4llvm8exegesis8Analysis27ResolvedSchedClassAndPointsC1EONS0_18ResolvedSchedClassE'/>
<use f='llvm/llvm/tools/llvm-exegesis/lib/Analysis.cpp' l='548' u='m' c='_ZNK4llvm8exegesis8Analysis3runERNS_11raw_ostreamE'/>
<use f='llvm/llvm/tools/llvm-exegesis/lib/Analysis.cpp' l='573' u='r' c='_ZNK4llvm8exegesis8Analysis3runERNS_11raw_ostreamE'/>
<use f='llvm/llvm/tools/llvm-exegesis/lib/Analysis.cpp' l='584' u='m' c='_ZNK4llvm8exegesis8Analysis3runERNS_11raw_ostreamE'/>
<use f='llvm/llvm/tools/llvm-exegesis/lib/Analysis.cpp' l='588' u='r' c='_ZNK4llvm8exegesis8Analysis3runERNS_11raw_ostreamE'/>
<use f='llvm/llvm/tools/llvm-exegesis/lib/Analysis.cpp' l='590' u='r' c='_ZNK4llvm8exegesis8Analysis3runERNS_11raw_ostreamE'/>
<offset>0</offset>
