<dec f='llvm/llvm/include/llvm/TableGen/Record.h' l='975' type='llvm::Init *'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='979' u='w' c='_ZN4llvm10FoldOpInitC1EPNS_4InitES2_S2_S2_S2_PNS_5RecTyE'/>
<offset>448</offset>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='1442' u='r' c='_ZNK4llvm10FoldOpInit7ProfileERNS_16FoldingSetNodeIDE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='1451' u='r' c='_ZNK4llvm10FoldOpInit4FoldEPNS_6RecordE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='1464' u='r' c='_ZNK4llvm10FoldOpInit17resolveReferencesERNS_8ResolverE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='1470' u='r' c='_ZNK4llvm10FoldOpInit17resolveReferencesERNS_8ResolverE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='1480' u='r' c='_ZNK4llvm10FoldOpInit11getAsStringB5cxx11Ev'/>
