<dec f='llvm/build/lib/Target/X86/X86GenRegisterInfo.inc' l='39' type='19'/>
<use f='llvm/build/lib/Target/X86/X86GenAsmMatcher.inc' l='7188' c='_ZL20validateOperandClassRN4llvm18MCParsedAsmOperandEN12_GLOBAL__N_114MatchClassKindE'/>
<use f='llvm/llvm/lib/Target/X86/Disassembler/X86Disassembler.cpp' l='1773' macro='1' u='r' c='_ZL17translateRegisterRN4llvm6MCInstENS_15X86Disassembler3RegE'/>
<use f='llvm/llvm/lib/Target/X86/Disassembler/X86Disassembler.cpp' l='2010' macro='1' u='r' c='_ZL19translateRMRegisterRN4llvm6MCInstERNS_15X86Disassembler19InternalInstructionE'/>
<use f='llvm/llvm/lib/Target/X86/MCTargetDesc/X86MCTargetDesc.cpp' l='89' u='r' c='_ZN4llvm6X86_MC28initLLVMToSEHAndCVRegMappingEPNS_14MCRegisterInfoE'/>
<use f='llvm/llvm/lib/Target/X86/MCTargetDesc/X86MCTargetDesc.cpp' l='629' c='_ZN4llvm28getX86SubSuperRegisterOrZeroENS_10MCRegisterEjb'/>
<use f='llvm/llvm/lib/Target/X86/MCTargetDesc/X86MCTargetDesc.cpp' l='641' c='_ZN4llvm28getX86SubSuperRegisterOrZeroENS_10MCRegisterEjb'/>
<use f='llvm/llvm/lib/Target/X86/MCTargetDesc/X86MCTargetDesc.cpp' l='642' u='r' c='_ZN4llvm28getX86SubSuperRegisterOrZeroENS_10MCRegisterEjb'/>
<use f='llvm/llvm/lib/Target/X86/MCTargetDesc/X86MCTargetDesc.cpp' l='678' c='_ZN4llvm28getX86SubSuperRegisterOrZeroENS_10MCRegisterEjb'/>
<use f='llvm/llvm/lib/Target/X86/MCTargetDesc/X86MCTargetDesc.cpp' l='714' c='_ZN4llvm28getX86SubSuperRegisterOrZeroENS_10MCRegisterEjb'/>
<use f='llvm/llvm/lib/Target/X86/MCTargetDesc/X86MCTargetDesc.cpp' l='750' c='_ZN4llvm28getX86SubSuperRegisterOrZeroENS_10MCRegisterEjb'/>
<use f='llvm/build/lib/Target/X86/X86GenCallingConv.inc' l='655' u='r' c='_ZL18CC_X86_32_FastCalljN4llvm3MVTES0_NS_11CCValAssign7LocInfoENS_3ISD10ArgFlagsTyERNS_7CCStateE'/>
<use f='llvm/build/lib/Target/X86/X86GenCallingConv.inc' l='2256' u='r' c='_ZL14CC_X86_Win64_CjN4llvm3MVTES0_NS_11CCValAssign7LocInfoENS_3ISD10ArgFlagsTyERNS_7CCStateE'/>
<use f='llvm/build/lib/Target/X86/X86GenCallingConv.inc' l='2698' u='r' c='_ZL15RetCC_X86CommonjN4llvm3MVTES0_NS_11CCValAssign7LocInfoENS_3ISD10ArgFlagsTyERNS_7CCStateE'/>
<use f='llvm/build/lib/Target/X86/X86GenCallingConv.inc' l='2967' u='r' c='_ZL17RetCC_X86_32_FastjN4llvm3MVTES0_NS_11CCValAssign7LocInfoENS_3ISD10ArgFlagsTyERNS_7CCStateE'/>
<use f='llvm/build/lib/Target/X86/X86GenCallingConv.inc' l='3069' u='r' c='_ZL20RetCC_X86_32_RegCalljN4llvm3MVTES0_NS_11CCValAssign7LocInfoENS_3ISD10ArgFlagsTyERNS_7CCStateE'/>
<use f='llvm/build/lib/Target/X86/X86GenCallingConv.inc' l='3471' u='r' c='_ZL18RetCC_X86_64_SwiftjN4llvm3MVTES0_NS_11CCValAssign7LocInfoENS_3ISD10ArgFlagsTyERNS_7CCStateE'/>
<use f='llvm/build/lib/Target/X86/X86GenCallingConv.inc' l='3644' u='r' c='_ZL24RetCC_X86_SysV64_RegCalljN4llvm3MVTES0_NS_11CCValAssign7LocInfoENS_3ISD10ArgFlagsTyERNS_7CCStateE'/>
<use f='llvm/build/lib/Target/X86/X86GenCallingConv.inc' l='3858' u='r' c='_ZL23RetCC_X86_Win64_RegCalljN4llvm3MVTES0_NS_11CCValAssign7LocInfoENS_3ISD10ArgFlagsTyERNS_7CCStateE'/>
<use f='llvm/llvm/unittests/tools/llvm-exegesis/X86/RegisterAliasingTest.cpp' l='55' u='r' c='_ZN4llvm8exegesis12_GLOBAL__N_144RegisterAliasingTest_TrackRegisterClass_Test8TestBodyEv'/>
<use f='llvm/llvm/unittests/tools/llvm-exegesis/X86/SnippetFileTest.cpp' l='87' u='r' c='_ZN4llvm8exegesis12_GLOBAL__N_129X86SnippetFileTest_Works_Test8TestBodyEv'/>
