<dec f='llvm/llvm/lib/Target/RISCV/MCTargetDesc/RISCVELFStreamer.h' l='23' type='unsigned int'/>
<use f='llvm/llvm/lib/Target/RISCV/MCTargetDesc/RISCVELFStreamer.h' l='35' u='r' c='_ZN4llvm22RISCVTargetELFStreamer16getAttributeItemEj'/>
<use f='llvm/llvm/lib/Target/RISCV/MCTargetDesc/RISCVELFStreamer.cpp' l='125' u='r' c='_ZN4llvm22RISCVTargetELFStreamer22finishAttributeSectionEv'/>
<use f='llvm/llvm/lib/Target/RISCV/MCTargetDesc/RISCVELFStreamer.cpp' l='154' u='r' c='_ZNK4llvm22RISCVTargetELFStreamer20calculateContentSizeEv'/>
<use f='llvm/llvm/lib/Target/RISCV/MCTargetDesc/RISCVELFStreamer.cpp' l='158' u='r' c='_ZNK4llvm22RISCVTargetELFStreamer20calculateContentSizeEv'/>
<use f='llvm/llvm/lib/Target/RISCV/MCTargetDesc/RISCVELFStreamer.cpp' l='162' u='r' c='_ZNK4llvm22RISCVTargetELFStreamer20calculateContentSizeEv'/>
<offset>32</offset>
