<dec f='llvm/llvm/lib/Target/ARM/Utils/ARMBaseInfo.h' l='40' type='9'/>
<use f='llvm/llvm/lib/Target/ARM/Utils/ARMBaseInfo.h' l='59' u='r' c='_ZN4llvm5ARMCCL20getOppositeConditionENS0_9CondCodesE'/>
<use f='llvm/llvm/lib/Target/ARM/Utils/ARMBaseInfo.h' l='60' c='_ZN4llvm5ARMCCL20getOppositeConditionENS0_9CondCodesE'/>
<use f='llvm/llvm/lib/Target/ARM/Utils/ARMBaseInfo.h' l='76' u='r' c='_ZN4llvm5ARMCCL19getSwappedConditionENS0_9CondCodesE'/>
<use f='llvm/llvm/lib/Target/ARM/Utils/ARMBaseInfo.h' l='79' c='_ZN4llvm5ARMCCL19getSwappedConditionENS0_9CondCodesE'/>
<use f='llvm/llvm/lib/Target/ARM/Utils/ARMBaseInfo.h' l='157' c='_ZN4llvmL19ARMCondCodeToStringENS_5ARMCC9CondCodesE'/>
<use f='llvm/llvm/lib/Target/ARM/Utils/ARMBaseInfo.h' l='180' u='r' c='_ZN4llvmL21ARMCondCodeFromStringENS_9StringRefE'/>
<doc f='llvm/llvm/lib/Target/ARM/Utils/ARMBaseInfo.h' l='40'>// Unsigned lower or same     Less than or equal</doc>
<use f='llvm/llvm/lib/Target/ARM/ARMBaseInstrInfo.cpp' l='623' c='_ZNK4llvm16ARMBaseInstrInfo17SubsumesPredicateENS_8ArrayRefINS_14MachineOperandEEES3_'/>
<use f='llvm/llvm/lib/Target/ARM/ARMBaseInstrInfo.cpp' l='3217' c='_ZNK4llvm16ARMBaseInstrInfo20optimizeCompareInstrERNS_12MachineInstrENS_8RegisterES3_iiPKNS_19MachineRegisterInfoE'/>
<use f='llvm/llvm/lib/Target/ARM/ARMFastISel.cpp' l='1203' u='r' c='_ZL14getComparePredN4llvm7CmpInst9PredicateE'/>
<use f='llvm/llvm/lib/Target/ARM/ARMISelLowering.cpp' l='1946' u='r' c='_ZL12IntCCToARMCCN4llvm3ISD8CondCodeE'/>
<use f='llvm/llvm/lib/Target/ARM/ARMISelLowering.cpp' l='1963' u='r' c='_ZL11FPCCToARMCCN4llvm3ISD8CondCodeERNS_5ARMCC9CondCodesES4_'/>
<use f='llvm/llvm/lib/Target/ARM/ARMInstructionSelector.cpp' l='422' u='r' c='_ZL15getComparePredsN4llvm7CmpInst9PredicateE'/>
