<dec f='llvm/llvm/include/llvm/ADT/DenseSet.h' l='142' type='typename MapTy::const_iterator'/>
<use f='llvm/llvm/include/llvm/ADT/DenseSet.h' l='154' u='w' c='_ZN4llvm6detail12DenseSetImpl13ConstIteratorC1ERKNS1_8IteratorE'/>
<use f='llvm/llvm/include/llvm/ADT/DenseSet.h' l='155' u='w' c='_ZN4llvm6detail12DenseSetImpl13ConstIteratorC1ERKNT0_14const_iteratorE'/>
<use f='llvm/llvm/include/llvm/ADT/DenseSet.h' l='157' u='c' c='_ZNK4llvm6detail12DenseSetImpl13ConstIteratordeEv'/>
<use f='llvm/llvm/include/llvm/ADT/DenseSet.h' l='158' u='c' c='_ZNK4llvm6detail12DenseSetImpl13ConstIteratorptEv'/>
<use f='llvm/llvm/include/llvm/ADT/DenseSet.h' l='160' u='w' c='_ZN4llvm6detail12DenseSetImpl13ConstIteratorppEv'/>
<use f='llvm/llvm/include/llvm/ADT/DenseSet.h' l='161' u='w' c='_ZN4llvm6detail12DenseSetImpl13ConstIteratorppEi'/>
