<dec f='llvm/build/lib/Target/Hexagon/HexagonGenRegisterInfo.inc' l='106' type='86'/>
<use f='llvm/build/lib/Target/Hexagon/HexagonGenAsmMatcher.inc' l='6998' c='_ZL20validateOperandClassRN4llvm18MCParsedAsmOperandEN12_GLOBAL__N_114MatchClassKindE'/>
<use f='llvm/llvm/lib/Target/Hexagon/Disassembler/HexagonDisassembler.cpp' l='548' u='r' c='_ZL26DecodeIntRegsRegisterClassRN4llvm6MCInstEjmPKv'/>
<use f='llvm/llvm/lib/Target/Hexagon/Disassembler/HexagonDisassembler.cpp' l='564' u='r' c='_ZL33DecodeGeneralSubRegsRegisterClassRN4llvm6MCInstEjmPKv'/>
<use f='llvm/llvm/lib/Target/Hexagon/HexagonBitTracker.cpp' l='1251' u='r' c='_ZNK4llvm16HexagonEvaluator14getNextPhysRegEjj'/>
<use f='llvm/llvm/lib/Target/Hexagon/HexagonFrameLowering.cpp' l='1075' u='r' c='_ZNK4llvm20HexagonFrameLowering23insertCFIInstructionsAtERNS_17MachineBasicBlockENS_26MachineInstrBundleIteratorINS_12MachineInstrELb0EEE'/>
<use f='llvm/llvm/lib/Target/Hexagon/HexagonISelLowering.cpp' l='142' u='r' c='_ZL10CC_SkipOddRjRN4llvm3MVTES2_RNS0_11CCValAssign7LocInfoERNS0_3ISD10ArgFlagsTyERNS0_7CCStateE'/>
<use f='llvm/build/lib/Target/Hexagon/HexagonGenCallingConv.inc' l='76' u='r' c='_ZL10CC_HexagonjN4llvm3MVTES0_NS_11CCValAssign7LocInfoENS_3ISD10ArgFlagsTyERNS_7CCStateE'/>
<use f='llvm/build/lib/Target/Hexagon/HexagonGenCallingConv.inc' l='291' u='r' c='_ZL17CC_Hexagon_LegacyjN4llvm3MVTES0_NS_11CCValAssign7LocInfoENS_3ISD10ArgFlagsTyERNS_7CCStateE'/>
<use f='llvm/llvm/lib/Target/Hexagon/HexagonISelLowering.cpp' l='251' u='r' c='_ZNK4llvm21HexagonTargetLowering17getRegisterByNameEPKcNS_3LLTERKNS_15MachineFunctionE'/>
<use f='llvm/llvm/lib/Target/Hexagon/HexagonRegisterInfo.cpp' l='51' u='r' c='_ZNK4llvm19HexagonRegisterInfo23isEHReturnCalleeSaveRegEj'/>
<use f='llvm/llvm/lib/Target/Hexagon/HexagonRegisterInfo.cpp' l='60' u='r' c='_ZNK4llvm19HexagonRegisterInfo18getCallerSavedRegsEPKNS_15MachineFunctionEPKNS_19TargetRegisterClassE'/>
<use f='llvm/llvm/lib/Target/Hexagon/HexagonRegisterInfo.cpp' l='117' u='r' c='_ZNK4llvm19HexagonRegisterInfo18getCalleeSavedRegsEPKNS_15MachineFunctionE'/>
<use f='llvm/llvm/lib/Target/Hexagon/MCTargetDesc/HexagonMCDuplexInfo.cpp' l='671' c='_ZL6addOpsRN4llvm6MCInstERKS0_j'/>
<use f='llvm/llvm/lib/Target/Hexagon/MCTargetDesc/HexagonMCInstrInfo.cpp' l='269' c='_ZN4llvm18HexagonMCInstrInfo26getDuplexRegisterNumberingEj'/>
