<dec f='llvm/llvm/include/llvm/IR/PatternMatch.h' l='931' type='LHS_t'/>
<use f='llvm/llvm/include/llvm/IR/PatternMatch.h' l='936' u='w' c='_ZN4llvm12PatternMatch14BinaryOp_matchC1ERKT_RKT0_'/>
<use f='llvm/llvm/include/llvm/IR/PatternMatch.h' l='941' u='c' c='_ZN4llvm12PatternMatch14BinaryOp_match5matchEPTL0__'/>
<use f='llvm/llvm/include/llvm/IR/PatternMatch.h' l='942' u='c' c='_ZN4llvm12PatternMatch14BinaryOp_match5matchEPTL0__'/>
<use f='llvm/llvm/include/llvm/IR/PatternMatch.h' l='947' u='c' c='_ZN4llvm12PatternMatch14BinaryOp_match5matchEPTL0__'/>
<use f='llvm/llvm/include/llvm/IR/PatternMatch.h' l='948' u='c' c='_ZN4llvm12PatternMatch14BinaryOp_match5matchEPTL0__'/>
