<dec f='llvm/build/lib/Target/X86/X86GenRegisterInfo.inc' l='30' type='10'/>
<use f='llvm/llvm/lib/Target/X86/AsmParser/X86AsmParser.cpp' l='3875' u='r' c='_ZN12_GLOBAL__N_112X86AsmParser19validateInstructionERN4llvm6MCInstERKNS1_15SmallVectorImplISt10unique_ptrINS1_18MCParsedAsmOperandESt14default_deleteIS6_EEEE'/>
<use f='llvm/build/lib/Target/X86/X86GenAsmMatcher.inc' l='7193' c='_ZL20validateOperandClassRN4llvm18MCParsedAsmOperandEN12_GLOBAL__N_114MatchClassKindE'/>
<use f='llvm/llvm/lib/Target/X86/Disassembler/X86Disassembler.cpp' l='1773' macro='1' u='r' c='_ZL17translateRegisterRN4llvm6MCInstENS_15X86Disassembler3RegE'/>
<use f='llvm/llvm/lib/Target/X86/Disassembler/X86Disassembler.cpp' l='2010' macro='1' u='r' c='_ZL19translateRMRegisterRN4llvm6MCInstERNS_15X86Disassembler19InternalInstructionE'/>
<use f='llvm/llvm/lib/Target/X86/MCTargetDesc/X86MCCodeEmitter.cpp' l='1227' u='r' c='_ZNK12_GLOBAL__N_116X86MCCodeEmitter13emitREXPrefixEiRKN4llvm6MCInstERKNS1_15MCSubtargetInfoERNS1_11raw_ostreamE'/>
<use f='llvm/llvm/lib/Target/X86/MCTargetDesc/X86MCTargetDesc.cpp' l='92' u='r' c='_ZN4llvm6X86_MC28initLLVMToSEHAndCVRegMappingEPNS_14MCRegisterInfoE'/>
<use f='llvm/llvm/lib/Target/X86/MCTargetDesc/X86MCTargetDesc.cpp' l='631' c='_ZN4llvm28getX86SubSuperRegisterOrZeroENS_10MCRegisterEjb'/>
<use f='llvm/llvm/lib/Target/X86/MCTargetDesc/X86MCTargetDesc.cpp' l='632' u='r' c='_ZN4llvm28getX86SubSuperRegisterOrZeroENS_10MCRegisterEjb'/>
<use f='llvm/llvm/lib/Target/X86/MCTargetDesc/X86MCTargetDesc.cpp' l='643' c='_ZN4llvm28getX86SubSuperRegisterOrZeroENS_10MCRegisterEjb'/>
<use f='llvm/llvm/lib/Target/X86/MCTargetDesc/X86MCTargetDesc.cpp' l='680' c='_ZN4llvm28getX86SubSuperRegisterOrZeroENS_10MCRegisterEjb'/>
<use f='llvm/llvm/lib/Target/X86/MCTargetDesc/X86MCTargetDesc.cpp' l='716' c='_ZN4llvm28getX86SubSuperRegisterOrZeroENS_10MCRegisterEjb'/>
<use f='llvm/llvm/lib/Target/X86/MCTargetDesc/X86MCTargetDesc.cpp' l='752' c='_ZN4llvm28getX86SubSuperRegisterOrZeroENS_10MCRegisterEjb'/>
<use f='llvm/llvm/tools/llvm-exegesis/lib/X86/Target.cpp' l='749'/>
