<dec f='llvm/llvm/include/llvm/IR/PatternMatch.h' l='2392' type='LHS'/>
<use f='llvm/llvm/include/llvm/IR/PatternMatch.h' l='2395' u='w' c='_ZN4llvm12PatternMatch15LogicalOp_matchC1ERKT_RKT0_'/>
<use f='llvm/llvm/include/llvm/IR/PatternMatch.h' l='2402' u='c' c='_ZN4llvm12PatternMatch15LogicalOp_match5matchEPTL0__'/>
<use f='llvm/llvm/include/llvm/IR/PatternMatch.h' l='2409' u='c' c='_ZN4llvm12PatternMatch15LogicalOp_match5matchEPTL0__'/>
<use f='llvm/llvm/include/llvm/IR/PatternMatch.h' l='2415' u='c' c='_ZN4llvm12PatternMatch15LogicalOp_match5matchEPTL0__'/>
