<dec f='llvm/llvm/utils/TableGen/X86RecognizableInstr.h' l='227' type='InstructionSpecifier *'/>
<offset>704</offset>
<doc f='llvm/llvm/utils/TableGen/X86RecognizableInstr.h' l='225'>/// The description of the instruction that is emitted into the instruction
  /// info table</doc>
<use f='llvm/llvm/utils/TableGen/X86RecognizableInstr.cpp' l='69' u='w' c='_ZN4llvm15X86Disassembler17RecognizableInstrC1ERNS0_18DisassemblerTablesERKNS_18CodeGenInstructionEt'/>
<use f='llvm/llvm/utils/TableGen/X86RecognizableInstr.cpp' l='381' u='r' c='_ZN4llvm15X86Disassembler17RecognizableInstr13handleOperandEbRjS2_jPKjPFNS0_15OperandEncodingERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEhE'/>
<use f='llvm/llvm/utils/TableGen/X86RecognizableInstr.cpp' l='382' u='r' c='_ZN4llvm15X86Disassembler17RecognizableInstr13handleOperandEbRjS2_jPKjPFNS0_15OperandEncodingERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEhE'/>
<use f='llvm/llvm/utils/TableGen/X86RecognizableInstr.cpp' l='392' u='r' c='_ZN4llvm15X86Disassembler17RecognizableInstr13handleOperandEbRjS2_jPKjPFNS0_15OperandEncodingERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEhE'/>
<use f='llvm/llvm/utils/TableGen/X86RecognizableInstr.cpp' l='393' u='r' c='_ZN4llvm15X86Disassembler17RecognizableInstr13handleOperandEbRjS2_jPKjPFNS0_15OperandEncodingERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEhE'/>
<use f='llvm/llvm/utils/TableGen/X86RecognizableInstr.cpp' l='401' u='r' c='_ZN4llvm15X86Disassembler17RecognizableInstr24emitInstructionSpecifierEv'/>
<use f='llvm/llvm/utils/TableGen/X86RecognizableInstr.cpp' l='403' u='r' c='_ZN4llvm15X86Disassembler17RecognizableInstr24emitInstructionSpecifierEv'/>
