<dec f='llvm/llvm/tools/llvm-rc/ResourceScriptStmt.h' l='654' type='uint32_t'/>
<use f='llvm/llvm/tools/llvm-rc/ResourceScriptStmt.h' l='661' u='w' c='_ZN4llvm2rc14DialogResourceC1EjjjjjONS0_16OptionalStmtListEbt'/>
<use f='llvm/llvm/tools/llvm-rc/ResourceFileWriter.cpp' l='1113' u='r' c='_ZN4llvm2rc18ResourceFileWriter15writeDialogBodyEPKNS0_10RCResourceE'/>
<use f='llvm/llvm/tools/llvm-rc/ResourceFileWriter.cpp' l='1126' u='r' c='_ZN4llvm2rc18ResourceFileWriter15writeDialogBodyEPKNS0_10RCResourceE'/>
<offset>384</offset>
<use f='llvm/llvm/tools/llvm-rc/ResourceScriptStmt.cpp' l='167' u='r' c='_ZNK4llvm2rc14DialogResource3logERNS_11raw_ostreamE'/>
