<dec f='llvm/llvm/include/llvm/Demangle/MicrosoftDemangleNodes.h' l='614' type='llvm::ms_demangle::StorageClass'/>
<offset>192</offset>
<use f='llvm/llvm/lib/Demangle/MicrosoftDemangle.cpp' l='847' u='w' c='_ZN4llvm11ms_demangle9Demangler24demangleVariableEncodingERNS_16itanium_demangle10StringViewENS0_12StorageClassE'/>
<use f='llvm/llvm/lib/Demangle/MicrosoftDemangleNodes.cpp' l='589' u='r' c='_ZNK4llvm11ms_demangle18VariableSymbolNode6outputERNS_16itanium_demangle12OutputStreamENS0_11OutputFlagsE'/>
