<use f='llvm/llvm/include/llvm/Support/FormatVariadic.h' l='50' u='w' c='_ZN4llvm15ReplacementItemC1ENS_9StringRefE'/>
<use f='llvm/llvm/include/llvm/Support/FormatVariadic.h' l='53' u='w' c='_ZN4llvm15ReplacementItemC1ENS_9StringRefEmmNS_10AlignStyleEcS1_'/>
<dec f='llvm/llvm/include/llvm/Support/FormatVariadic.h' l='57' type='llvm::StringRef'/>
<use f='llvm/llvm/include/llvm/Support/FormatVariadic.h' l='89' u='r' c='_ZNK4llvm19formatv_object_base6formatERNS_11raw_ostreamE'/>
<use f='llvm/llvm/include/llvm/Support/FormatVariadic.h' l='93' u='r' c='_ZNK4llvm19formatv_object_base6formatERNS_11raw_ostreamE'/>
<offset>64</offset>
<use f='llvm/llvm/unittests/Support/FormatVariadicTest.cpp' l='47' u='r' c='_ZN38FormatVariadicTest_NoReplacements_Test8TestBodyEv'/>
<use f='llvm/llvm/unittests/Support/FormatVariadicTest.cpp' l='55' u='r' c='_ZN36FormatVariadicTest_EscapedBrace_Test8TestBodyEv'/>
<use f='llvm/llvm/unittests/Support/FormatVariadicTest.cpp' l='61' u='r' c='_ZN36FormatVariadicTest_EscapedBrace_Test8TestBodyEv'/>
<use f='llvm/llvm/unittests/Support/FormatVariadicTest.cpp' l='67' u='r' c='_ZN36FormatVariadicTest_EscapedBrace_Test8TestBodyEv'/>
<use f='llvm/llvm/unittests/Support/FormatVariadicTest.cpp' l='73' u='r' c='_ZN36FormatVariadicTest_EscapedBrace_Test8TestBodyEv'/>
<use f='llvm/llvm/unittests/Support/FormatVariadicTest.cpp' l='152' u='r' c='_ZN48FormatVariadicTest_ValidReplacementSequence_Test8TestBodyEv'/>
<use f='llvm/llvm/unittests/Support/FormatVariadicTest.cpp' l='162' u='r' c='_ZN48FormatVariadicTest_ValidReplacementSequence_Test8TestBodyEv'/>
<use f='llvm/llvm/unittests/Support/FormatVariadicTest.cpp' l='173' u='r' c='_ZN48FormatVariadicTest_ValidReplacementSequence_Test8TestBodyEv'/>
<use f='llvm/llvm/unittests/Support/FormatVariadicTest.cpp' l='183' u='r' c='_ZN48FormatVariadicTest_ValidReplacementSequence_Test8TestBodyEv'/>
<use f='llvm/llvm/unittests/Support/FormatVariadicTest.cpp' l='193' u='r' c='_ZN48FormatVariadicTest_ValidReplacementSequence_Test8TestBodyEv'/>
<use f='llvm/llvm/unittests/Support/FormatVariadicTest.cpp' l='203' u='r' c='_ZN48FormatVariadicTest_ValidReplacementSequence_Test8TestBodyEv'/>
<use f='llvm/llvm/unittests/Support/FormatVariadicTest.cpp' l='253' u='r' c='_ZN44FormatVariadicTest_MultipleReplacements_Test8TestBodyEv'/>
<use f='llvm/llvm/unittests/Support/FormatVariadicTest.cpp' l='264' u='r' c='_ZN44FormatVariadicTest_MultipleReplacements_Test8TestBodyEv'/>
