<dec f='llvm/build/lib/Target/ARM/ARMGenInstrInfo.inc' l='869' type='854'/>
<use f='llvm/llvm/lib/Target/ARM/ARMFrameLowering.cpp' l='2472' u='r' c='_ZNK4llvm16ARMFrameLowering24adjustForSegmentedStacksERNS_15MachineFunctionERNS_17MachineBasicBlockE'/>
<use f='llvm/build/lib/Target/ARM/ARMGenDAGISel.inc' l='46686' u='r' c='_ZN12_GLOBAL__N_115ARMDAGToDAGISel10SelectCodeEPN4llvm6SDNodeE'/>
<use f='llvm/build/lib/Target/ARM/ARMGenDAGISel.inc' l='46686' u='r' c='_ZN12_GLOBAL__N_115ARMDAGToDAGISel10SelectCodeEPN4llvm6SDNodeE'/>
<use f='llvm/build/lib/Target/ARM/ARMGenDAGISel.inc' l='60744' u='r' c='_ZN12_GLOBAL__N_115ARMDAGToDAGISel10SelectCodeEPN4llvm6SDNodeE'/>
<use f='llvm/build/lib/Target/ARM/ARMGenDAGISel.inc' l='60744' u='r' c='_ZN12_GLOBAL__N_115ARMDAGToDAGISel10SelectCodeEPN4llvm6SDNodeE'/>
<use f='llvm/llvm/lib/Target/ARM/ARMISelDAGToDAG.cpp' l='5066' u='r' c='_ZN12_GLOBAL__N_115ARMDAGToDAGISel15tryReadRegisterEPN4llvm6SDNodeE'/>
<use f='llvm/build/lib/Target/ARM/ARMGenAsmMatcher.inc' l='11191'/>
<use f='llvm/build/lib/Target/ARM/ARMGenAsmMatcher.inc' l='11193'/>
<use f='llvm/build/lib/Target/ARM/ARMGenMCCodeEmitter.inc' l='16369' c='_ZNK12_GLOBAL__N_116ARMMCCodeEmitter21getBinaryCodeForInstrERKN4llvm6MCInstERNS1_15SmallVectorImplINS1_7MCFixupEEERKNS1_15MCSubtargetInfoE'/>
