<dec f='llvm/llvm/lib/Target/PowerPC/PPCISelLowering.h' l='166' type='367'/>
<use f='llvm/build/lib/Target/PowerPC/PPCGenFastISel.inc' l='4806' c='_ZN12_GLOBAL__N_111PPCFastISel11fastEmit_rrEN4llvm3MVTES2_jjbjb'/>
<use f='llvm/build/lib/Target/PowerPC/PPCGenDAGISel.inc' l='44623' u='r' c='_ZN12_GLOBAL__N_115PPCDAGToDAGISel10SelectCodeEPN4llvm6SDNodeE'/>
<use f='llvm/build/lib/Target/PowerPC/PPCGenDAGISel.inc' l='44623' u='r' c='_ZN12_GLOBAL__N_115PPCDAGToDAGISel10SelectCodeEPN4llvm6SDNodeE'/>
<use f='llvm/llvm/lib/Target/PowerPC/PPCISelLowering.cpp' l='1513' c='_ZNK4llvm17PPCTargetLowering17getTargetNodeNameEj'/>
<use f='llvm/llvm/lib/Target/PowerPC/PPCISelLowering.cpp' l='8371' u='r' c='_ZNK4llvm17PPCTargetLowering14LowerSRA_PARTSENS_7SDValueERNS_12SelectionDAGE'/>
<use f='llvm/llvm/lib/Target/PowerPC/PPCISelLowering.cpp' l='8372' u='r' c='_ZNK4llvm17PPCTargetLowering14LowerSRA_PARTSENS_7SDValueERNS_12SelectionDAGE'/>
<use f='llvm/llvm/lib/Target/PowerPC/PPCISelLowering.cpp' l='14137' c='_ZNK4llvm17PPCTargetLowering17PerformDAGCombineEPNS_6SDNodeERNS_14TargetLowering15DAGCombinerInfoE'/>
<use f='llvm/llvm/lib/Target/PowerPC/PPCISelLowering.cpp' l='15865' u='r' c='_ZL18stripModuloOnShiftRKN4llvm14TargetLoweringEPNS_6SDNodeERNS_12SelectionDAGE'/>
