<dec f='llvm/llvm/include/llvm/MC/MCExpr.h' l='482' type='3'/>
<use f='llvm/llvm/include/llvm/MC/MCExpr.h' l='537' u='r' c='_ZN4llvm12MCBinaryExpr8createEQEPKNS_6MCExprES3_RNS_9MCContextE'/>
<doc f='llvm/llvm/include/llvm/MC/MCExpr.h' l='482'>///&lt; Equality comparison.</doc>
<use f='llvm/llvm/lib/MC/MCExpr.cpp' l='141' c='_ZNK4llvm6MCExpr5printERNS_11raw_ostreamEPKNS_9MCAsmInfoEb'/>
<use f='llvm/llvm/lib/MC/MCExpr.cpp' l='903' c='_ZNK4llvm6MCExpr25evaluateAsRelocatableImplERNS_7MCValueEPKNS_11MCAssemblerEPKNS_11MCAsmLayoutEPKNS_7MCFixupEPKNS_8DenseMapIPKNS_9MCSectionEmNS_12Dens14347918'/>
<use f='llvm/llvm/lib/MC/MCExpr.cpp' l='960' c='_ZNK4llvm6MCExpr25evaluateAsRelocatableImplERNS_7MCValueEPKNS_11MCAssemblerEPKNS_11MCAsmLayoutEPKNS_7MCFixupEPKNS_8DenseMapIPKNS_9MCSectionEmNS_12Dens14347918'/>
<use f='llvm/llvm/lib/MC/MCExpr.cpp' l='981' c='_ZNK4llvm6MCExpr25evaluateAsRelocatableImplERNS_7MCValueEPKNS_11MCAssemblerEPKNS_11MCAsmLayoutEPKNS_7MCFixupEPKNS_8DenseMapIPKNS_9MCSectionEmNS_12Dens14347918'/>
<use f='llvm/llvm/lib/MC/MCParser/AsmParser.cpp' l='1523' u='r' c='_ZL24getDarwinBinOpPrecedenceN4llvm8AsmToken9TokenKindERNS_12MCBinaryExpr6OpcodeEb'/>
<use f='llvm/llvm/lib/MC/MCParser/AsmParser.cpp' l='1589' u='r' c='_ZL21getGNUBinOpPrecedenceRKN4llvm9MCAsmInfoENS_8AsmToken9TokenKindERNS_12MCBinaryExpr6OpcodeEb'/>
<use f='llvm/llvm/lib/MC/MCParser/MasmParser.cpp' l='1841' u='r' c='_ZL21getGNUBinOpPrecedenceN4llvm8AsmToken9TokenKindERNS_12MCBinaryExpr6OpcodeEbb'/>
