<dec f='llvm/build/lib/Target/AArch64/AArch64GenRegisterInfo.inc' l='269' type='249'/>
<use f='llvm/llvm/lib/Target/AArch64/AArch64CallingConvention.cpp' l='39'/>
<use f='llvm/build/lib/Target/AArch64/AArch64GenCallingConv.inc' l='164' u='r' c='_ZN4llvm16CC_AArch64_AAPCSEjNS_3MVTES0_NS_11CCValAssign7LocInfoENS_3ISD10ArgFlagsTyERNS_7CCStateE'/>
<use f='llvm/build/lib/Target/AArch64/AArch64GenCallingConv.inc' l='1235' u='r' c='_ZN4llvm19RetCC_AArch64_AAPCSEjNS_3MVTES0_NS_11CCValAssign7LocInfoENS_3ISD10ArgFlagsTyERNS_7CCStateE'/>
<use f='llvm/llvm/lib/Target/AArch64/AsmParser/AArch64AsmParser.cpp' l='2264' u='r' c='_ZL25matchSVEDataVectorRegNameN4llvm9StringRefE'/>
<use f='llvm/llvm/lib/Target/AArch64/Disassembler/AArch64Disassembler.cpp' l='539'/>
<use f='llvm/llvm/lib/Target/AArch64/MCTargetDesc/AArch64InstPrinter.cpp' l='1216' u='r' c='_ZL21getNextVectorRegisterjj'/>
<use f='llvm/llvm/lib/Target/AArch64/MCTargetDesc/AArch64InstPrinter.cpp' l='1217' c='_ZL21getNextVectorRegisterjj'/>
