<use f='llvm/llvm/include/llvm/ExecutionEngine/Orc/ThreadSafeModule.h' l='42' u='w' c='_ZN4llvm3orc17ThreadSafeContext4LockC1ESt10shared_ptrINS1_5StateEE'/>
<use f='llvm/llvm/include/llvm/ExecutionEngine/Orc/ThreadSafeModule.h' l='42' u='m' c='_ZN4llvm3orc17ThreadSafeContext4LockC1ESt10shared_ptrINS1_5StateEE'/>
<dec f='llvm/llvm/include/llvm/ExecutionEngine/Orc/ThreadSafeModule.h' l='45' type='std::shared_ptr&lt;State&gt;'/>
<offset>0</offset>
