<dec f='llvm/llvm/include/llvm/Analysis/TargetLibraryInfo.h' l='452' type='llvm::TargetLibraryAnalysis'/>
<use f='llvm/llvm/include/llvm/Analysis/TargetLibraryInfo.h' l='465' u='m' c='_ZN4llvm28TargetLibraryInfoWrapperPass6getTLIERKNS_8FunctionE'/>
<offset>256</offset>
<use f='llvm/llvm/lib/Analysis/TargetLibraryInfo.cpp' l='1660' u='w' c='_ZN4llvm28TargetLibraryInfoWrapperPassC1Ev'/>
<use f='llvm/llvm/lib/Analysis/TargetLibraryInfo.cpp' l='1665' u='w' c='_ZN4llvm28TargetLibraryInfoWrapperPassC1ERKNS_6TripleE'/>
<use f='llvm/llvm/lib/Analysis/TargetLibraryInfo.cpp' l='1671' u='w' c='_ZN4llvm28TargetLibraryInfoWrapperPassC1ERKNS_21TargetLibraryInfoImplE'/>
