<dec f='llvm/llvm/lib/Target/AVR/AVRISelLowering.h' l='61' type='354'/>
<doc f='llvm/llvm/lib/Target/AVR/AVRISelLowering.h' l='60'>/// Test for zero or minus instruction.</doc>
<use f='llvm/build/lib/Target/AVR/AVRGenDAGISel.inc' l='1421' u='r' c='_ZN4llvm15AVRDAGToDAGISel10SelectCodeEPNS_6SDNodeE'/>
<use f='llvm/build/lib/Target/AVR/AVRGenDAGISel.inc' l='1421' u='r' c='_ZN4llvm15AVRDAGToDAGISel10SelectCodeEPNS_6SDNodeE'/>
<use f='llvm/llvm/lib/Target/AVR/AVRISelLowering.cpp' l='259' c='_ZNK4llvm17AVRTargetLowering17getTargetNodeNameEj'/>
<use f='llvm/llvm/lib/Target/AVR/AVRISelLowering.cpp' l='610' u='r' c='_ZNK4llvm17AVRTargetLowering9getAVRCmpENS_7SDValueES1_NS_3ISD8CondCodeERS1_RNS_12SelectionDAGENS_5SDLocE'/>
<use f='llvm/llvm/lib/Target/AVR/AVRISelLowering.cpp' l='648' u='r' c='_ZNK4llvm17AVRTargetLowering9getAVRCmpENS_7SDValueES1_NS_3ISD8CondCodeERS1_RNS_12SelectionDAGENS_5SDLocE'/>
<use f='llvm/llvm/lib/Target/AVR/AVRISelLowering.cpp' l='658' u='r' c='_ZNK4llvm17AVRTargetLowering9getAVRCmpENS_7SDValueES1_NS_3ISD8CondCodeERS1_RNS_12SelectionDAGENS_5SDLocE'/>
