<dec f='llvm/build/lib/Target/Mips/MipsGenRegisterInfo.inc' l='29' type='9'/>
<use f='llvm/llvm/lib/Target/Mips/AsmParser/MipsAsmParser.cpp' l='1385' u='r' c='_ZNK12_GLOBAL__N_111MipsOperand32isMemWithSimmWordAlignedOffsetGPEv'/>
<use f='llvm/llvm/lib/Target/Mips/AsmParser/MipsAsmParser.cpp' l='2187' u='r' c='_ZN12_GLOBAL__N_113MipsAsmParser18processInstructionERN4llvm6MCInstENS1_5SMLocERNS1_10MCStreamerEPKNS1_15MCSubtargetInfoE'/>
<use f='llvm/llvm/lib/Target/Mips/AsmParser/MipsAsmParser.cpp' l='2190' u='r' c='_ZN12_GLOBAL__N_113MipsAsmParser18processInstructionERN4llvm6MCInstENS1_5SMLocERNS1_10MCStreamerEPKNS1_15MCSubtargetInfoE'/>
<use f='llvm/llvm/lib/Target/Mips/AsmParser/MipsAsmParser.cpp' l='3254' u='r' c='_ZL7nextRegj'/>
<use f='llvm/llvm/lib/Target/Mips/AsmParser/MipsAsmParser.cpp' l='3255' c='_ZL7nextRegj'/>
<use f='llvm/llvm/lib/Target/Mips/AsmParser/MipsAsmParser.cpp' l='5607' u='r' c='_ZL20getRegisterForMxtrFPRN4llvm6MCInstEb'/>
<use f='llvm/llvm/lib/Target/Mips/AsmParser/MipsAsmParser.cpp' l='5646' u='r' c='_ZL20getRegisterForMxtrC0RN4llvm6MCInstEb'/>
<use f='llvm/build/lib/Target/Mips/MipsGenAsmMatcher.inc' l='4229' c='_ZL20validateOperandClassRN4llvm18MCParsedAsmOperandEN12_GLOBAL__N_114MatchClassKindE'/>
<use f='llvm/llvm/lib/Target/Mips/Disassembler/MipsDisassembler.cpp' l='1834' u='r' c='_ZL21DecodeMemMMGPImm7Lsl2RN4llvm6MCInstEjmPKv'/>
<use f='llvm/llvm/lib/Target/Mips/MCTargetDesc/MipsABIInfo.cpp' l='86' u='r' c='_ZNK4llvm11MipsABIInfo12GetGlobalPtrEv'/>
<use f='llvm/llvm/lib/Target/Mips/MCTargetDesc/MipsTargetStreamer.cpp' l='42' u='r' c='_ZN4llvm18MipsTargetStreamerC1ERNS_10MCStreamerE'/>
<use f='llvm/llvm/lib/Target/Mips/MipsISelLowering.h' l='478' u='r' c='_ZNK4llvm18MipsTargetLowering12getAddrGPRelEPT_RKNS_5SDLocENS_3EVTERNS_12SelectionDAGEb'/>
<use f='llvm/llvm/lib/Target/Mips/MicroMipsSizeReduction.cpp' l='383' u='r' c='_ZL20ConsecutiveRegistersjj'/>
<use f='llvm/llvm/lib/Target/Mips/MipsCallLowering.cpp' l='597' u='r' c='_ZNK4llvm16MipsCallLowering9lowerCallERNS_16MachineIRBuilderERNS_12CallLowering16CallLoweringInfoE'/>
<use f='llvm/llvm/lib/Target/Mips/MipsCallLowering.cpp' l='599' u='r' c='_ZNK4llvm16MipsCallLowering9lowerCallERNS_16MachineIRBuilderERNS_12CallLowering16CallLoweringInfoE'/>
<use f='llvm/llvm/lib/Target/Mips/MipsISelLowering.cpp' l='3038' u='r' c='_ZNK4llvm18MipsTargetLowering11getOpndListERNS_15SmallVectorImplINS_7SDValueEEERSt5dequeISt4pairIjS2_ESaIS7_EEbbbbRNS_14TargetLowering16CallLoweringInfoES2_S2_'/>
<use f='llvm/llvm/lib/Target/Mips/MipsISelLowering.cpp' l='4727' u='r' c='_ZNK4llvm18MipsTargetLowering17getRegisterByNameEPKcNS_3LLTERKNS_15MachineFunctionE'/>
<use f='llvm/llvm/lib/Target/Mips/MipsOptimizePICCall.cpp' l='168' u='r' c='_ZL11eraseGPOpndRN4llvm12MachineInstrE'/>
<use f='llvm/llvm/lib/Target/Mips/MipsRegisterInfo.cpp' l='177' u='r' c='_ZNK4llvm16MipsRegisterInfo15getReservedRegsERKNS_15MachineFunctionE'/>
<use f='llvm/llvm/lib/Target/Mips/MipsRegisterInfo.cpp' l='236' u='r' c='_ZNK4llvm16MipsRegisterInfo15getReservedRegsERKNS_15MachineFunctionE'/>
