<dec f='llvm/build/lib/Target/AArch64/AArch64GenRegisterInfo.inc' l='22' type='2'/>
<use f='llvm/llvm/lib/Target/AArch64/Utils/AArch64BaseInfo.h' l='60' c='_ZN4llvmL15getWRegFromXRegEj'/>
<use f='llvm/llvm/lib/Target/AArch64/Utils/AArch64BaseInfo.h' l='100' u='r' c='_ZN4llvmL15getXRegFromWRegEj'/>
<use f='llvm/llvm/lib/Target/AArch64/AArch64AsmPrinter.cpp' l='490' u='r' c='_ZN12_GLOBAL__N_117AArch64AsmPrinter26EmitHwasanMemaccessSymbolsERN4llvm6ModuleE'/>
<use f='llvm/llvm/lib/Target/AArch64/AArch64CollectLOH.cpp' l='269' u='r' c='_ZL16mapRegToGPRIndext'/>
<use f='llvm/llvm/lib/Target/AArch64/AArch64ExpandPseudoInsts.cpp' l='659' u='r' c='_ZN12_GLOBAL__N_119AArch64ExpandPseudo19expandCALL_RVMARKERERN4llvm17MachineBasicBlockENS1_26MachineInstrBundleIteratorINS1_12MachineInstrELb0EEE'/>
<use f='llvm/llvm/lib/Target/AArch64/AArch64ExpandPseudoInsts.cpp' l='661' u='r' c='_ZN12_GLOBAL__N_119AArch64ExpandPseudo19expandCALL_RVMARKERERN4llvm17MachineBasicBlockENS1_26MachineInstrBundleIteratorINS1_12MachineInstrELb0EEE'/>
<use f='llvm/llvm/lib/Target/AArch64/AArch64FrameLowering.cpp' l='710' u='r' c='_ZL9InsertSEHN4llvm26MachineInstrBundleIteratorINS_12MachineInstrELb0EEERKNS_15TargetInstrInfoENS1_6MIFlagE'/>
<use f='llvm/llvm/lib/Target/AArch64/AArch64FrameLowering.cpp' l='759' u='r' c='_ZL9InsertSEHN4llvm26MachineInstrBundleIteratorINS_12MachineInstrELb0EEERKNS_15TargetInstrInfoENS1_6MIFlagE'/>
<use f='llvm/llvm/lib/Target/AArch64/AArch64FrameLowering.cpp' l='1179' u='r' c='_ZNK4llvm20AArch64FrameLowering12emitPrologueERNS_15MachineFunctionERNS_17MachineBasicBlockE'/>
<use f='llvm/llvm/lib/Target/AArch64/AArch64FrameLowering.cpp' l='1386' u='r' c='_ZNK4llvm20AArch64FrameLowering12emitPrologueERNS_15MachineFunctionERNS_17MachineBasicBlockE'/>
<use f='llvm/llvm/lib/Target/AArch64/AArch64FrameLowering.cpp' l='1705' u='r' c='_ZNK4llvm20AArch64FrameLowering12emitEpilogueERNS_15MachineFunctionERNS_17MachineBasicBlockE'/>
<use f='llvm/llvm/lib/Target/AArch64/AArch64FrameLowering.cpp' l='1767' u='r' c='_ZNK4llvm20AArch64FrameLowering12emitEpilogueERNS_15MachineFunctionERNS_17MachineBasicBlockE'/>
<use f='llvm/llvm/lib/Target/AArch64/AArch64FrameLowering.cpp' l='1848' u='r' c='_ZNK4llvm20AArch64FrameLowering22getSEHFrameIndexOffsetERKNS_15MachineFunctionEi'/>
<use f='llvm/llvm/lib/Target/AArch64/AArch64FrameLowering.cpp' l='2024' u='r' c='_ZL32invalidateWindowsRegisterPairingjjbb'/>
<use f='llvm/llvm/lib/Target/AArch64/AArch64FrameLowering.cpp' l='2256' u='r' c='_ZL30computeCalleeSaveRegisterPairsRN4llvm15MachineFunctionENS_8ArrayRefINS_15CalleeSavedInfoEEEPKNS_18TargetRegisterInfoERNS_15SmallVectorImplIN12_GL6601255'/>
<use f='llvm/llvm/lib/Target/AArch64/AArch64FrameLowering.cpp' l='2257' u='r' c='_ZL30computeCalleeSaveRegisterPairsRN4llvm15MachineFunctionENS_8ArrayRefINS_15CalleeSavedInfoEEEPKNS_18TargetRegisterInfoERNS_15SmallVectorImplIN12_GL6601255'/>
<use f='llvm/llvm/lib/Target/AArch64/AArch64FrameLowering.cpp' l='2631' u='r' c='_ZNK4llvm20AArch64FrameLowering20determineCalleeSavesERNS_15MachineFunctionERNS_9BitVectorEPNS_12RegScavengerE'/>
<use f='llvm/llvm/lib/Target/AArch64/AArch64ISelLowering.cpp' l='7202' u='r' c='_ZNK4llvm21AArch64TargetLowering14LowerFRAMEADDRENS_7SDValueERNS_12SelectionDAGE'/>
<use f='llvm/llvm/lib/Target/AArch64/AArch64ISelLowering.cpp' l='7252' u='r' c='_ZNK4llvm21AArch64TargetLowering21LowerADDROFRETURNADDRENS_7SDValueERNS_12SelectionDAGE'/>
<use f='llvm/llvm/lib/Target/AArch64/AArch64InstrInfo.cpp' l='3677' u='r' c='_ZL18emitFrameOffsetAdjRN4llvm17MachineBasicBlockENS_26MachineInstrBundleIteratorINS_12MachineInstrELb0EEERKNS_8DebugLocEjjljPKNS_15TargetInstrInfoENS3_6MIFlagEbPb'/>
<use f='llvm/llvm/lib/Target/AArch64/AArch64InstrInfo.cpp' l='3678' u='r' c='_ZL18emitFrameOffsetAdjRN4llvm17MachineBasicBlockENS_26MachineInstrBundleIteratorINS_12MachineInstrELb0EEERKNS_8DebugLocEjjljPKNS_15TargetInstrInfoENS3_6MIFlagEbPb'/>
<use f='llvm/llvm/lib/Target/AArch64/AArch64RegisterInfo.cpp' l='412' u='r' c='_ZNK4llvm19AArch64RegisterInfo16getFrameRegisterERKNS_15MachineFunctionE'/>
<use f='llvm/llvm/lib/Target/AArch64/AArch64RegisterInfo.cpp' l='505' u='r' c='_ZNK4llvm19AArch64RegisterInfo17needsFrameBaseRegEPNS_12MachineInstrEl'/>
<use f='llvm/llvm/lib/Target/AArch64/AArch64SLSHardening.cpp' l='179'/>
<use f='llvm/llvm/lib/Target/AArch64/AsmParser/AArch64AsmParser.cpp' l='2351' u='r' c='_ZN12_GLOBAL__N_116AArch64AsmParser22matchRegisterNameAliasEN4llvm9StringRefENS_7RegKindE'/>
<use f='llvm/llvm/lib/Target/AArch64/AsmParser/AArch64AsmParser.cpp' l='3930' u='r' c='_ZN12_GLOBAL__N_116AArch64AsmParser20parseRegisterInRangeERjjjj'/>
<use f='llvm/llvm/lib/Target/AArch64/AsmParser/AArch64AsmParser.cpp' l='3932' u='r' c='_ZN12_GLOBAL__N_116AArch64AsmParser20parseRegisterInRangeERjjjj'/>
<use f='llvm/llvm/lib/Target/AArch64/AsmParser/AArch64AsmParser.cpp' l='3939' u='r' c='_ZN12_GLOBAL__N_116AArch64AsmParser20parseRegisterInRangeERjjjj'/>
<use f='llvm/llvm/lib/Target/AArch64/AsmParser/AArch64AsmParser.cpp' l='5883' u='r' c='_ZN12_GLOBAL__N_116AArch64AsmParser25parseDirectiveSEHSaveRegPEN4llvm5SMLocE'/>
<use f='llvm/llvm/lib/Target/AArch64/AsmParser/AArch64AsmParser.cpp' l='5895' u='r' c='_ZN12_GLOBAL__N_116AArch64AsmParser26parseDirectiveSEHSaveRegPXEN4llvm5SMLocE'/>
<use f='llvm/llvm/lib/Target/AArch64/Disassembler/AArch64Disassembler.cpp' l='438'/>
<use f='llvm/llvm/lib/Target/AArch64/GISel/AArch64InstructionSelector.cpp' l='5020' u='r' c='_ZN12_GLOBAL__N_126AArch64InstructionSelector15selectIntrinsicERN4llvm12MachineInstrERNS1_19MachineRegisterInfoE'/>
<use f='llvm/llvm/lib/Target/AArch64/MCTargetDesc/AArch64AsmBackend.cpp' l='598' u='r' c='_ZNK12_GLOBAL__N_123DarwinAArch64AsmBackend29generateCompactUnwindEncodingEN4llvm8ArrayRefINS1_16MCCFIInstructionEEE'/>
<use f='llvm/llvm/lib/Target/AArch64/MCTargetDesc/AArch64MCTargetDesc.cpp' l='130' u='r' c='_ZN4llvm10AArch64_MC22initLLVMToCVRegMappingEPNS_14MCRegisterInfoE'/>
