<dec f='llvm/llvm/include/llvm/CodeGen/GlobalISel/MIPatternMatch.h' l='212' type='LHS_P'/>
<use f='llvm/llvm/include/llvm/CodeGen/GlobalISel/MIPatternMatch.h' l='215' u='w' c='_ZN4llvm14MIPatternMatch14BinaryOp_matchC1ERKT_RKT0_'/>
<use f='llvm/llvm/include/llvm/CodeGen/GlobalISel/MIPatternMatch.h' l='221' u='c' c='_ZN4llvm14MIPatternMatch14BinaryOp_match5matchERKNS_19MachineRegisterInfoEOTL0__'/>
<use f='llvm/llvm/include/llvm/CodeGen/GlobalISel/MIPatternMatch.h' l='224' u='c' c='_ZN4llvm14MIPatternMatch14BinaryOp_match5matchERKNS_19MachineRegisterInfoEOTL0__'/>
