<dec f='llvm/llvm/lib/DebugInfo/Symbolize/SymbolizableObjectFile.h' l='71' type='const object::ObjectFile *'/>
<use f='llvm/llvm/lib/DebugInfo/Symbolize/SymbolizableObjectFile.cpp' l='97' u='w' c='_ZN4llvm9symbolize22SymbolizableObjectFileC1EPKNS_6object10ObjectFileESt10unique_ptrINS_9DIContextESt14default_deleteIS7_EEb'/>
<use f='llvm/llvm/lib/DebugInfo/Symbolize/SymbolizableObjectFile.cpp' l='187' u='r' c='_ZN4llvm9symbolize22SymbolizableObjectFile9addSymbolERKNS_6object9SymbolRefEmPNS_13DataExtractorEm'/>
<use f='llvm/llvm/lib/DebugInfo/Symbolize/SymbolizableObjectFile.cpp' l='199' u='r' c='_ZNK4llvm9symbolize22SymbolizableObjectFile13isWin32ModuleEv'/>
<use f='llvm/llvm/lib/DebugInfo/Symbolize/SymbolizableObjectFile.cpp' l='204' u='r' c='_ZNK4llvm9symbolize22SymbolizableObjectFile22getModulePreferredBaseEv'/>
<use f='llvm/llvm/lib/DebugInfo/Symbolize/SymbolizableObjectFile.cpp' l='308' u='r' c='_ZNK4llvm9symbolize22SymbolizableObjectFile31getModuleSectionIndexForAddressEm'/>
<offset>64</offset>
