<dec f='llvm/llvm/lib/CodeGen/AsmPrinter/DebugLocStream.h' l='34' type='llvm::DwarfCompileUnit *'/>
<use f='llvm/llvm/lib/CodeGen/AsmPrinter/DebugLocStream.h' l='38' u='w' c='_ZN4llvm14DebugLocStream4ListC1EPNS_16DwarfCompileUnitEm'/>
<offset>0</offset>
<use f='llvm/llvm/lib/CodeGen/AsmPrinter/DIEHash.cpp' l='236' u='r' c='_ZN4llvm7DIEHash11hashLocListERKNS_10DIELocListE'/>
<use f='llvm/llvm/lib/CodeGen/AsmPrinter/DwarfDebug.cpp' l='2705' u='r' c='_ZL11emitLocListRN4llvm10DwarfDebugEPNS_10AsmPrinterERKNS_14DebugLocStream4ListE'/>
<use f='llvm/llvm/lib/CodeGen/AsmPrinter/DwarfDebug.cpp' l='2710' u='r' c='_ZL11emitLocListRN4llvm10DwarfDebugEPNS_10AsmPrinterERKNS_14DebugLocStream4ListE'/>
<use f='llvm/llvm/lib/CodeGen/AsmPrinter/DwarfDebug.cpp' l='2768' u='r' c='_ZN4llvm10DwarfDebug15emitDebugLocDWOEv'/>
