<use f='llvm/llvm/include/llvm/CodeGen/SwitchLoweringUtils.h' l='256' u='w' c='_ZN4llvm8SwitchCG14SwitchLowering4initERKNS_14TargetLoweringERKNS_13TargetMachineERKNS_10DataLayoutE'/>
<dec f='llvm/llvm/include/llvm/CodeGen/SwitchLoweringUtils.h' l='296' type='const llvm::TargetMachine *'/>
<offset>704</offset>
<use f='llvm/llvm/lib/CodeGen/SwitchLoweringUtils.cpp' l='98' u='r' c='_ZN4llvm8SwitchCG14SwitchLowering14findJumpTablesERSt6vectorINS0_11CaseClusterESaIS3_EEPKNS_10SwitchInstEPNS_17MachineBasicBlockEPNS_18ProfileSummaryI1582550'/>
<use f='llvm/llvm/lib/CodeGen/SwitchLoweringUtils.cpp' l='281' u='r' c='_ZN4llvm8SwitchCG14SwitchLowering19findBitTestClustersERSt6vectorINS0_11CaseClusterESaIS3_EEPKNS_10SwitchInstE'/>
