<dec f='llvm/llvm/include/llvm/CodeGen/SwitchLoweringUtils.h' l='137' type='llvm::SDLoc'/>
<use f='llvm/llvm/include/llvm/CodeGen/SwitchLoweringUtils.h' l='150' u='w' c='_ZN4llvm8SwitchCG9CaseBlockC1ENS_3ISD8CondCodeEPKNS_5ValueES6_S6_PNS_17MachineBasicBlockES8_S8_NS_5SDLocENS_17BranchProbabilityESA_'/>
<offset>448</offset>
<doc f='llvm/llvm/include/llvm/CodeGen/SwitchLoweringUtils.h' l='135'>/// The debug location of the instruction this CaseBlock was
  /// produced from.</doc>
<use f='llvm/llvm/lib/CodeGen/SelectionDAG/SelectionDAGBuilder.cpp' l='2349' u='r' c='_ZN4llvm19SelectionDAGBuilder15visitSwitchCaseERNS_8SwitchCG9CaseBlockEPNS_17MachineBasicBlockE'/>
