<use f='llvm/llvm/include/llvm/ExecutionEngine/Orc/Layer.h' l='69' u='w' c='_ZN4llvm3orc7IRLayerC1ERNS0_16ExecutionSessionERPKNS0_14IRSymbolMapper15ManglingOptionsE'/>
<use f='llvm/llvm/include/llvm/ExecutionEngine/Orc/Layer.h' l='78' u='a' c='_ZNK4llvm3orc7IRLayer18getManglingOptionsEv'/>
<dec f='llvm/llvm/include/llvm/ExecutionEngine/Orc/Layer.h' l='114' type='const IRSymbolMapper::ManglingOptions *&amp;'/>
<offset>192</offset>
