<dec f='llvm/build/lib/Target/X86/X86GenRegisterInfo.inc' l='82' type='62'/>
<use f='llvm/llvm/lib/Target/X86/AsmParser/X86AsmParser.cpp' l='3927' u='r' c='_ZN12_GLOBAL__N_112X86AsmParser21applyLVICFIMitigationERN4llvm6MCInstERNS1_10MCStreamerE'/>
<use f='llvm/build/lib/Target/X86/X86GenAsmMatcher.inc' l='7243' c='_ZL20validateOperandClassRN4llvm18MCParsedAsmOperandEN12_GLOBAL__N_114MatchClassKindE'/>
<use f='llvm/llvm/lib/Target/X86/Disassembler/X86Disassembler.cpp' l='1773' macro='1' u='r' c='_ZL17translateRegisterRN4llvm6MCInstENS_15X86Disassembler3RegE'/>
<use f='llvm/llvm/lib/Target/X86/Disassembler/X86Disassembler.cpp' l='2010' macro='1' u='r' c='_ZL19translateRMRegisterRN4llvm6MCInstERNS_15X86Disassembler19InternalInstructionE'/>
<use f='llvm/llvm/lib/Target/X86/MCTargetDesc/X86MCTargetDesc.cpp' l='99' u='r' c='_ZN4llvm6X86_MC28initLLVMToSEHAndCVRegMappingEPNS_14MCRegisterInfoE'/>
<use f='llvm/llvm/lib/Target/X86/MCTargetDesc/X86MCTargetDesc.cpp' l='625' c='_ZN4llvm28getX86SubSuperRegisterOrZeroENS_10MCRegisterEjb'/>
<use f='llvm/llvm/lib/Target/X86/MCTargetDesc/X86MCTargetDesc.cpp' l='626' u='r' c='_ZN4llvm28getX86SubSuperRegisterOrZeroENS_10MCRegisterEjb'/>
<use f='llvm/llvm/lib/Target/X86/MCTargetDesc/X86MCTargetDesc.cpp' l='653' c='_ZN4llvm28getX86SubSuperRegisterOrZeroENS_10MCRegisterEjb'/>
<use f='llvm/llvm/lib/Target/X86/MCTargetDesc/X86MCTargetDesc.cpp' l='690' c='_ZN4llvm28getX86SubSuperRegisterOrZeroENS_10MCRegisterEjb'/>
<use f='llvm/llvm/lib/Target/X86/MCTargetDesc/X86MCTargetDesc.cpp' l='691' u='r' c='_ZN4llvm28getX86SubSuperRegisterOrZeroENS_10MCRegisterEjb'/>
<use f='llvm/llvm/lib/Target/X86/MCTargetDesc/X86MCTargetDesc.cpp' l='726' c='_ZN4llvm28getX86SubSuperRegisterOrZeroENS_10MCRegisterEjb'/>
<use f='llvm/llvm/lib/Target/X86/MCTargetDesc/X86MCTargetDesc.cpp' l='762' c='_ZN4llvm28getX86SubSuperRegisterOrZeroENS_10MCRegisterEjb'/>
