<dec f='llvm/build/lib/Target/Mips/MipsGenInstrInfo.inc' l='2408' type='2393'/>
<use f='llvm/build/lib/Target/Mips/MipsGenAsmMatcher.inc' l='7545'/>
<use f='llvm/llvm/lib/Target/Mips/Disassembler/MipsDisassembler.cpp' l='1543' u='r' c='_ZL9DecodeMemRN4llvm6MCInstEjmPKv'/>
<use f='llvm/build/lib/Target/Mips/MipsGenMCCodeEmitter.inc' l='7727' c='_ZNK4llvm17MipsMCCodeEmitter21getBinaryCodeForInstrERKNS_6MCInstERNS_15SmallVectorImplINS_7MCFixupEEERKNS_15MCSubtargetInfoE'/>
<use f='llvm/llvm/lib/Target/Mips/MCTargetDesc/MipsNaClELFStreamer.cpp' l='248' c='_ZN4llvm28isBasePlusOffsetMemoryAccessEjPjPb'/>
<use f='llvm/llvm/lib/Target/Mips/MipsExpandPseudo.cpp' l='99' u='r' c='_ZN12_GLOBAL__N_116MipsExpandPseudo26expandAtomicCmpSwapSubwordERN4llvm17MachineBasicBlockENS1_26MachineInstrBundleIteratorINS1_12MachineInstrELb0EEERS6_'/>
<use f='llvm/llvm/lib/Target/Mips/MipsExpandPseudo.cpp' l='227' u='r' c='_ZN12_GLOBAL__N_116MipsExpandPseudo19expandAtomicCmpSwapERN4llvm17MachineBasicBlockENS1_26MachineInstrBundleIteratorINS1_12MachineInstrELb0EEERS6_'/>
<use f='llvm/llvm/lib/Target/Mips/MipsExpandPseudo.cpp' l='330' u='r' c='_ZN12_GLOBAL__N_116MipsExpandPseudo24expandAtomicBinOpSubwordERN4llvm17MachineBasicBlockENS1_26MachineInstrBundleIteratorINS1_12MachineInstrELb0EEERS6_'/>
<use f='llvm/llvm/lib/Target/Mips/MipsExpandPseudo.cpp' l='606' u='r' c='_ZN12_GLOBAL__N_116MipsExpandPseudo17expandAtomicBinOpERN4llvm17MachineBasicBlockENS1_26MachineInstrBundleIteratorINS1_12MachineInstrELb0EEERS6_j'/>
<use f='llvm/llvm/lib/Target/Mips/MipsSERegisterInfo.cpp' l='84' c='_ZL28getLoadStoreOffsetSizeInBitsjN4llvm14MachineOperandE'/>
