<dec f='llvm/build/lib/Target/Lanai/LanaiGenRegisterInfo.inc' l='25' type='5'/>
<use f='llvm/build/lib/Target/Lanai/LanaiGenAsmMatcher.inc' l='797' c='_ZL20validateOperandClassRN4llvm18MCParsedAsmOperandEN12_GLOBAL__N_114MatchClassKindE'/>
<use f='llvm/llvm/lib/Target/Lanai/Disassembler/LanaiDisassembler.cpp' l='156'/>
<use f='llvm/llvm/lib/Target/Lanai/LanaiAsmPrinter.cpp' l='168' u='r' c='_ZN12_GLOBAL__N_115LanaiAsmPrinter19emitCallInstructionEPKN4llvm12MachineInstrE'/>
<use f='llvm/llvm/lib/Target/Lanai/LanaiDelaySlotFiller.cpp' l='251' u='r' c='_ZN12_GLOBAL__N_16Filler14insertDefsUsesEN4llvm14ilist_iteratorINS1_12ilist_detail12node_optionsINS1_12MachineInstrELb1ELb1EvEELb0ELb0EEERNS1_8SmallSe16262472'/>
<use f='llvm/llvm/lib/Target/Lanai/LanaiFrameLowering.cpp' l='115' u='r' c='_ZNK4llvm18LanaiFrameLowering12emitPrologueERNS_15MachineFunctionERNS_17MachineBasicBlockE'/>
<use f='llvm/llvm/lib/Target/Lanai/LanaiFrameLowering.cpp' l='123' u='r' c='_ZNK4llvm18LanaiFrameLowering12emitPrologueERNS_15MachineFunctionERNS_17MachineBasicBlockE'/>
<use f='llvm/llvm/lib/Target/Lanai/LanaiFrameLowering.cpp' l='130' u='r' c='_ZNK4llvm18LanaiFrameLowering12emitPrologueERNS_15MachineFunctionERNS_17MachineBasicBlockE'/>
<use f='llvm/llvm/lib/Target/Lanai/LanaiFrameLowering.cpp' l='131' u='r' c='_ZNK4llvm18LanaiFrameLowering12emitPrologueERNS_15MachineFunctionERNS_17MachineBasicBlockE'/>
<use f='llvm/llvm/lib/Target/Lanai/LanaiFrameLowering.cpp' l='186' u='r' c='_ZNK4llvm18LanaiFrameLowering12emitEpilogueERNS_15MachineFunctionERNS_17MachineBasicBlockE'/>
<use f='llvm/llvm/lib/Target/Lanai/MCTargetDesc/LanaiBaseInfo.h' l='52' c='_ZN4llvmL25getLanaiRegisterNumberingEj'/>
<use f='llvm/llvm/lib/Target/Lanai/LanaiISelLowering.cpp' l='83' u='r' c='_ZN4llvm19LanaiTargetLoweringC1ERKNS_13TargetMachineERKNS_14LanaiSubtargetE'/>
<use f='llvm/llvm/lib/Target/Lanai/LanaiISelLowering.cpp' l='221' u='r' c='_ZNK4llvm19LanaiTargetLowering17getRegisterByNameEPKcNS_3LLTERKNS_15MachineFunctionE'/>
<use f='llvm/llvm/lib/Target/Lanai/LanaiISelLowering.cpp' l='691' u='r' c='_ZNK4llvm19LanaiTargetLowering14LowerCCCCallToENS_7SDValueES1_jbbRKNS_15SmallVectorImplINS_3ISD9OutputArgEEERKNS2_IS1_EERKNS2_INS3_8InputArgEEERKNS_5S11208842'/>
<use f='llvm/llvm/lib/Target/Lanai/LanaiRegisterInfo.cpp' l='49' u='r' c='_ZNK4llvm17LanaiRegisterInfo15getReservedRegsERKNS_15MachineFunctionE'/>
<use f='llvm/llvm/lib/Target/Lanai/LanaiRegisterInfo.cpp' l='158' u='r' c='_ZNK4llvm17LanaiRegisterInfo19eliminateFrameIndexENS_26MachineInstrBundleIteratorINS_12MachineInstrELb0EEEijPNS_12RegScavengerE'/>
