<dec f='llvm/llvm/include/llvm/DWARFLinker/DWARFLinker.h' l='365' type='llvm::CompileUnit &amp;'/>
<use f='llvm/llvm/include/llvm/DWARFLinker/DWARFLinker.h' l='374' u='w' c='_ZN4llvm11DWARFLinker12WorklistItemC1ENS_8DWARFDieERNS_11CompileUnitEjNS0_16WorklistItemTypeE'/>
<use f='llvm/llvm/include/llvm/DWARFLinker/DWARFLinker.h' l='378' u='w' c='_ZN4llvm11DWARFLinker12WorklistItemC1ENS_8DWARFDieERNS_11CompileUnitENS0_16WorklistItemTypeEPNS3_7DIEInfoE'/>
<use f='llvm/llvm/include/llvm/DWARFLinker/DWARFLinker.h' l='381' u='w' c='_ZN4llvm11DWARFLinker12WorklistItemC1EjRNS_11CompileUnitEj'/>
<use f='llvm/llvm/lib/DWARFLinker/DWARFLinker.cpp' l='740' u='a' c='_ZN4llvm11DWARFLinker17lookForDIEsToKeepERNS_12AddressesMapERSt3mapImNS_19ObjFileAddressRangeESt4lessImESaISt4pairIKmS4_EEERKSt6vectorISt10unique_ptrI3222953'/>
<use f='llvm/llvm/lib/DWARFLinker/DWARFLinker.cpp' l='743' u='a' c='_ZN4llvm11DWARFLinker17lookForDIEsToKeepERNS_12AddressesMapERSt3mapImNS_19ObjFileAddressRangeESt4lessImESaISt4pairIKmS4_EEERKSt6vectorISt10unique_ptrI3222953'/>
<use f='llvm/llvm/lib/DWARFLinker/DWARFLinker.cpp' l='746' u='a' c='_ZN4llvm11DWARFLinker17lookForDIEsToKeepERNS_12AddressesMapERSt3mapImNS_19ObjFileAddressRangeESt4lessImESaISt4pairIKmS4_EEERKSt6vectorISt10unique_ptrI3222953'/>
<use f='llvm/llvm/lib/DWARFLinker/DWARFLinker.cpp' l='749' u='a' c='_ZN4llvm11DWARFLinker17lookForDIEsToKeepERNS_12AddressesMapERSt3mapImNS_19ObjFileAddressRangeESt4lessImESaISt4pairIKmS4_EEERKSt6vectorISt10unique_ptrI3222953'/>
<use f='llvm/llvm/lib/DWARFLinker/DWARFLinker.cpp' l='753' u='a' c='_ZN4llvm11DWARFLinker17lookForDIEsToKeepERNS_12AddressesMapERSt3mapImNS_19ObjFileAddressRangeESt4lessImESaISt4pairIKmS4_EEERKSt6vectorISt10unique_ptrI3222953'/>
<use f='llvm/llvm/lib/DWARFLinker/DWARFLinker.cpp' l='760' u='m' c='_ZN4llvm11DWARFLinker17lookForDIEsToKeepERNS_12AddressesMapERSt3mapImNS_19ObjFileAddressRangeESt4lessImESaISt4pairIKmS4_EEERKSt6vectorISt10unique_ptrI3222953'/>
<use f='llvm/llvm/lib/DWARFLinker/DWARFLinker.cpp' l='761' u='m' c='_ZN4llvm11DWARFLinker17lookForDIEsToKeepERNS_12AddressesMapERSt3mapImNS_19ObjFileAddressRangeESt4lessImESaISt4pairIKmS4_EEERKSt6vectorISt10unique_ptrI3222953'/>
<use f='llvm/llvm/lib/DWARFLinker/DWARFLinker.cpp' l='776' u='a' c='_ZN4llvm11DWARFLinker17lookForDIEsToKeepERNS_12AddressesMapERSt3mapImNS_19ObjFileAddressRangeESt4lessImESaISt4pairIKmS4_EEERKSt6vectorISt10unique_ptrI3222953'/>
<use f='llvm/llvm/lib/DWARFLinker/DWARFLinker.cpp' l='781' u='a' c='_ZN4llvm11DWARFLinker17lookForDIEsToKeepERNS_12AddressesMapERSt3mapImNS_19ObjFileAddressRangeESt4lessImESaISt4pairIKmS4_EEERKSt6vectorISt10unique_ptrI3222953'/>
<use f='llvm/llvm/lib/DWARFLinker/DWARFLinker.cpp' l='800' u='a' c='_ZN4llvm11DWARFLinker17lookForDIEsToKeepERNS_12AddressesMapERSt3mapImNS_19ObjFileAddressRangeESt4lessImESaISt4pairIKmS4_EEERKSt6vectorISt10unique_ptrI3222953'/>
<use f='llvm/llvm/lib/DWARFLinker/DWARFLinker.cpp' l='804' u='m' c='_ZN4llvm11DWARFLinker17lookForDIEsToKeepERNS_12AddressesMapERSt3mapImNS_19ObjFileAddressRangeESt4lessImESaISt4pairIKmS4_EEERKSt6vectorISt10unique_ptrI3222953'/>
<use f='llvm/llvm/lib/DWARFLinker/DWARFLinker.cpp' l='809' u='a' c='_ZN4llvm11DWARFLinker17lookForDIEsToKeepERNS_12AddressesMapERSt3mapImNS_19ObjFileAddressRangeESt4lessImESaISt4pairIKmS4_EEERKSt6vectorISt10unique_ptrI3222953'/>
<offset>192</offset>
