<dec f='llvm/llvm/include/llvm/BinaryFormat/MachO.h' l='530' type='uint32_t'/>
<use f='llvm/llvm/include/llvm/BinaryFormat/MachO.h' l='1048' u='a' c='_ZN4llvm5MachO10swapStructERNS0_12load_commandE'/>
<offset>0</offset>
<use f='llvm/lld/MachO/InputFiles.cpp' l='151' u='r' c='_ZN3lld5macho11findCommandEPKN4llvm5MachO14mach_header_64Ej'/>
<use f='llvm/lld/MachO/InputFiles.cpp' l='605' u='r' c='_ZN3lld5macho9DylibFileC1EN4llvm15MemoryBufferRefEPS1_'/>
<use f='llvm/lld/lib/ReaderWriter/MachO/MachONormalizedFileBinaryReader.cpp' l='73' u='r' c='_ZN3lld6mach_o10normalizedL18forEachLoadCommandEN4llvm9StringRefEjbbSt8functionIFbjjPKcEE'/>
<use f='llvm/lldb/source/Plugins/DynamicLoader/MacOSX-DYLD/DynamicLoaderMacOSXDYLD.cpp' l='839' u='w' c='_ZN23DynamicLoaderMacOSXDYLD17ParseLoadCommandsERKN12lldb_private13DataExtractorERNS0_19DynamicLoaderDarwin9ImageInfoEPNS0_8FileSpecE'/>
<use f='llvm/lldb/source/Plugins/DynamicLoader/MacOSX-DYLD/DynamicLoaderMacOSXDYLD.cpp' l='841' u='r' c='_ZN23DynamicLoaderMacOSXDYLD17ParseLoadCommandsERKN12lldb_private13DataExtractorERNS0_19DynamicLoaderDarwin9ImageInfoEPNS0_8FileSpecE'/>
<use f='llvm/lldb/source/Plugins/ObjectFile/Mach-O/ObjectFileMachO.cpp' l='1275' u='a' c='_ZN15ObjectFileMachO10IsStrippedEv'/>
<use f='llvm/lldb/source/Plugins/ObjectFile/Mach-O/ObjectFileMachO.cpp' l='1277' u='r' c='_ZN15ObjectFileMachO10IsStrippedEv'/>
<use f='llvm/lldb/source/Plugins/ObjectFile/Mach-O/ObjectFileMachO.cpp' l='1278' u='r' c='_ZN15ObjectFileMachO10IsStrippedEv'/>
<use f='llvm/lldb/source/Plugins/ObjectFile/Mach-O/ObjectFileMachO.cpp' l='1830' u='r' c='_ZN15ObjectFileMachO22ProcessDysymtabCommandERKN4llvm5MachO12load_commandEm'/>
<use f='llvm/lldb/source/Plugins/ObjectFile/Mach-O/ObjectFileMachO.cpp' l='1855' u='r' c='_ZN15ObjectFileMachO14CreateSectionsERN12lldb_private11SectionListE'/>
<use f='llvm/lldb/source/Plugins/ObjectFile/Mach-O/ObjectFileMachO.cpp' l='1855' u='r' c='_ZN15ObjectFileMachO14CreateSectionsERN12lldb_private11SectionListE'/>
<use f='llvm/lldb/source/Plugins/ObjectFile/Mach-O/ObjectFileMachO.cpp' l='1857' u='r' c='_ZN15ObjectFileMachO14CreateSectionsERN12lldb_private11SectionListE'/>
<use f='llvm/lldb/source/Plugins/ObjectFile/Mach-O/ObjectFileMachO.cpp' l='2198' u='r' c='_ZN15ObjectFileMachO11ParseSymtabEv'/>
<use f='llvm/lldb/source/Plugins/ObjectFile/Mach-O/ObjectFileMachO.cpp' l='2200' u='r' c='_ZN15ObjectFileMachO11ParseSymtabEv'/>
<use f='llvm/lldb/source/Plugins/ObjectFile/Mach-O/ObjectFileMachO.cpp' l='2211' u='r' c='_ZN15ObjectFileMachO11ParseSymtabEv'/>
<use f='llvm/lldb/source/Plugins/ObjectFile/Mach-O/ObjectFileMachO.cpp' l='2232' u='r' c='_ZN15ObjectFileMachO11ParseSymtabEv'/>
<use f='llvm/lldb/source/Plugins/ObjectFile/Mach-O/ObjectFileMachO.cpp' l='2241' u='r' c='_ZN15ObjectFileMachO11ParseSymtabEv'/>
<use f='llvm/lldb/source/Plugins/ObjectFile/Mach-O/ObjectFileMachO.cpp' l='5000' u='r' c='_ZN15ObjectFileMachO15GetAllArchSpecsERKN4llvm5MachO11mach_headerERKN12lldb_private13DataExtractorEmRNS5_10ModuleSpecERNS5_14ModuleSpecListE'/>
<use f='llvm/lldb/source/Plugins/ObjectFile/Mach-O/ObjectFileMachO.cpp' l='5013' u='r' c='_ZN15ObjectFileMachO15GetAllArchSpecsERKN4llvm5MachO11mach_headerERKN12lldb_private13DataExtractorEmRNS5_10ModuleSpecERNS5_14ModuleSpecListE'/>
<use f='llvm/lldb/source/Plugins/ObjectFile/Mach-O/ObjectFileMachO.cpp' l='5020' u='r' c='_ZN15ObjectFileMachO15GetAllArchSpecsERKN4llvm5MachO11mach_headerERKN12lldb_private13DataExtractorEmRNS5_10ModuleSpecERNS5_14ModuleSpecListE'/>
<use f='llvm/lldb/source/Plugins/ObjectFile/Mach-O/ObjectFileMachO.cpp' l='5050' u='r' c='_ZN15ObjectFileMachO15GetAllArchSpecsERKN4llvm5MachO11mach_headerERKN12lldb_private13DataExtractorEmRNS5_10ModuleSpecERNS5_14ModuleSpecListE'/>
<use f='llvm/lldb/source/Plugins/ObjectFile/Mach-O/ObjectFileMachO.cpp' l='5143' u='r' c='_ZN15ObjectFileMachO19GetDependentModulesERN12lldb_private12FileSpecListE'/>
<use f='llvm/lldb/source/Plugins/ObjectFile/Mach-O/ObjectFileMachO.cpp' l='5154' u='r' c='_ZN15ObjectFileMachO19GetDependentModulesERN12lldb_private12FileSpecListE'/>
<use f='llvm/lldb/source/Plugins/ObjectFile/Mach-O/ObjectFileMachO.cpp' l='5279' u='r' c='_ZN15ObjectFileMachO20GetEntryPointAddressEv'/>
<use f='llvm/lldb/source/Plugins/ObjectFile/Mach-O/ObjectFileMachO.cpp' l='5455' u='a' c='_ZN15ObjectFileMachO19GetIdentifierStringB5cxx11Ev'/>
<use f='llvm/lldb/source/Plugins/ObjectFile/Mach-O/ObjectFileMachO.cpp' l='5457' u='r' c='_ZN15ObjectFileMachO19GetIdentifierStringB5cxx11Ev'/>
<use f='llvm/lldb/source/Plugins/ObjectFile/Mach-O/ObjectFileMachO.cpp' l='5524' u='a' c='_ZN15ObjectFileMachO25GetCorefileMainBinaryInfoERmRN12lldb_private4UUIDERNS1_10ObjectFile10BinaryTypeE'/>
<use f='llvm/lldb/source/Plugins/ObjectFile/Mach-O/ObjectFileMachO.cpp' l='5526' u='r' c='_ZN15ObjectFileMachO25GetCorefileMainBinaryInfoERmRN12lldb_private4UUIDERNS1_10ObjectFile10BinaryTypeE'/>
<use f='llvm/llvm/lib/DebugInfo/DWARF/DWARFContext.cpp' l='84' u='r' c='_ZL8dumpUUIDRN4llvm11raw_ostreamERKNS_6object10ObjectFileE'/>
<use f='llvm/llvm/lib/Object/MachOObjectFile.cpp' l='1321' u='r' c='_ZN4llvm6object15MachOObjectFileC1ENS_15MemoryBufferRefEbbRNS_5ErrorEjj'/>
<use f='llvm/llvm/lib/Object/MachOObjectFile.cpp' l='1335' u='r' c='_ZN4llvm6object15MachOObjectFileC1ENS_15MemoryBufferRefEbbRNS_5ErrorEjj'/>
<use f='llvm/llvm/lib/Object/MachOObjectFile.cpp' l='1338' u='r' c='_ZN4llvm6object15MachOObjectFileC1ENS_15MemoryBufferRefEbbRNS_5ErrorEjj'/>
<use f='llvm/llvm/lib/Object/MachOObjectFile.cpp' l='1342' u='r' c='_ZN4llvm6object15MachOObjectFileC1ENS_15MemoryBufferRefEbbRNS_5ErrorEjj'/>
<use f='llvm/llvm/lib/Object/MachOObjectFile.cpp' l='1347' u='r' c='_ZN4llvm6object15MachOObjectFileC1ENS_15MemoryBufferRefEbbRNS_5ErrorEjj'/>
<use f='llvm/llvm/lib/Object/MachOObjectFile.cpp' l='1353' u='r' c='_ZN4llvm6object15MachOObjectFileC1ENS_15MemoryBufferRefEbbRNS_5ErrorEjj'/>
<use f='llvm/llvm/lib/Object/MachOObjectFile.cpp' l='1358' u='r' c='_ZN4llvm6object15MachOObjectFileC1ENS_15MemoryBufferRefEbbRNS_5ErrorEjj'/>
<use f='llvm/llvm/lib/Object/MachOObjectFile.cpp' l='1363' u='r' c='_ZN4llvm6object15MachOObjectFileC1ENS_15MemoryBufferRefEbbRNS_5ErrorEjj'/>
<use f='llvm/llvm/lib/Object/MachOObjectFile.cpp' l='1368' u='r' c='_ZN4llvm6object15MachOObjectFileC1ENS_15MemoryBufferRefEbbRNS_5ErrorEjj'/>
<use f='llvm/llvm/lib/Object/MachOObjectFile.cpp' l='1373' u='r' c='_ZN4llvm6object15MachOObjectFileC1ENS_15MemoryBufferRefEbbRNS_5ErrorEjj'/>
<use f='llvm/llvm/lib/Object/MachOObjectFile.cpp' l='1377' u='r' c='_ZN4llvm6object15MachOObjectFileC1ENS_15MemoryBufferRefEbbRNS_5ErrorEjj'/>
<use f='llvm/llvm/lib/Object/MachOObjectFile.cpp' l='1381' u='r' c='_ZN4llvm6object15MachOObjectFileC1ENS_15MemoryBufferRefEbbRNS_5ErrorEjj'/>
<use f='llvm/llvm/lib/Object/MachOObjectFile.cpp' l='1392' u='r' c='_ZN4llvm6object15MachOObjectFileC1ENS_15MemoryBufferRefEbbRNS_5ErrorEjj'/>
<use f='llvm/llvm/lib/Object/MachOObjectFile.cpp' l='1398' u='r' c='_ZN4llvm6object15MachOObjectFileC1ENS_15MemoryBufferRefEbbRNS_5ErrorEjj'/>
<use f='llvm/llvm/lib/Object/MachOObjectFile.cpp' l='1404' u='r' c='_ZN4llvm6object15MachOObjectFileC1ENS_15MemoryBufferRefEbbRNS_5ErrorEjj'/>
<use f='llvm/llvm/lib/Object/MachOObjectFile.cpp' l='1407' u='r' c='_ZN4llvm6object15MachOObjectFileC1ENS_15MemoryBufferRefEbbRNS_5ErrorEjj'/>
<use f='llvm/llvm/lib/Object/MachOObjectFile.cpp' l='1411' u='r' c='_ZN4llvm6object15MachOObjectFileC1ENS_15MemoryBufferRefEbbRNS_5ErrorEjj'/>
<use f='llvm/llvm/lib/Object/MachOObjectFile.cpp' l='1415' u='r' c='_ZN4llvm6object15MachOObjectFileC1ENS_15MemoryBufferRefEbbRNS_5ErrorEjj'/>
<use f='llvm/llvm/lib/Object/MachOObjectFile.cpp' l='1419' u='r' c='_ZN4llvm6object15MachOObjectFileC1ENS_15MemoryBufferRefEbbRNS_5ErrorEjj'/>
<use f='llvm/llvm/lib/Object/MachOObjectFile.cpp' l='1423' u='r' c='_ZN4llvm6object15MachOObjectFileC1ENS_15MemoryBufferRefEbbRNS_5ErrorEjj'/>
<use f='llvm/llvm/lib/Object/MachOObjectFile.cpp' l='1427' u='r' c='_ZN4llvm6object15MachOObjectFileC1ENS_15MemoryBufferRefEbbRNS_5ErrorEjj'/>
<use f='llvm/llvm/lib/Object/MachOObjectFile.cpp' l='1430' u='r' c='_ZN4llvm6object15MachOObjectFileC1ENS_15MemoryBufferRefEbbRNS_5ErrorEjj'/>
<use f='llvm/llvm/lib/Object/MachOObjectFile.cpp' l='1433' u='r' c='_ZN4llvm6object15MachOObjectFileC1ENS_15MemoryBufferRefEbbRNS_5ErrorEjj'/>
<use f='llvm/llvm/lib/Object/MachOObjectFile.cpp' l='1436' u='r' c='_ZN4llvm6object15MachOObjectFileC1ENS_15MemoryBufferRefEbbRNS_5ErrorEjj'/>
<use f='llvm/llvm/lib/Object/MachOObjectFile.cpp' l='1440' u='r' c='_ZN4llvm6object15MachOObjectFileC1ENS_15MemoryBufferRefEbbRNS_5ErrorEjj'/>
<use f='llvm/llvm/lib/Object/MachOObjectFile.cpp' l='1444' u='r' c='_ZN4llvm6object15MachOObjectFileC1ENS_15MemoryBufferRefEbbRNS_5ErrorEjj'/>
<use f='llvm/llvm/lib/Object/MachOObjectFile.cpp' l='1448' u='r' c='_ZN4llvm6object15MachOObjectFileC1ENS_15MemoryBufferRefEbbRNS_5ErrorEjj'/>
<use f='llvm/llvm/lib/Object/MachOObjectFile.cpp' l='1452' u='r' c='_ZN4llvm6object15MachOObjectFileC1ENS_15MemoryBufferRefEbbRNS_5ErrorEjj'/>
<use f='llvm/llvm/lib/Object/MachOObjectFile.cpp' l='1455' u='r' c='_ZN4llvm6object15MachOObjectFileC1ENS_15MemoryBufferRefEbbRNS_5ErrorEjj'/>
<use f='llvm/llvm/lib/Object/MachOObjectFile.cpp' l='1458' u='r' c='_ZN4llvm6object15MachOObjectFileC1ENS_15MemoryBufferRefEbbRNS_5ErrorEjj'/>
<use f='llvm/llvm/lib/Object/MachOObjectFile.cpp' l='1461' u='r' c='_ZN4llvm6object15MachOObjectFileC1ENS_15MemoryBufferRefEbbRNS_5ErrorEjj'/>
<use f='llvm/llvm/lib/Object/MachOObjectFile.cpp' l='1472' u='r' c='_ZN4llvm6object15MachOObjectFileC1ENS_15MemoryBufferRefEbbRNS_5ErrorEjj'/>
<use f='llvm/llvm/lib/Object/MachOObjectFile.cpp' l='1483' u='r' c='_ZN4llvm6object15MachOObjectFileC1ENS_15MemoryBufferRefEbbRNS_5ErrorEjj'/>
<use f='llvm/llvm/lib/Object/MachOObjectFile.cpp' l='1494' u='r' c='_ZN4llvm6object15MachOObjectFileC1ENS_15MemoryBufferRefEbbRNS_5ErrorEjj'/>
<use f='llvm/llvm/lib/Object/MachOObjectFile.cpp' l='1505' u='r' c='_ZN4llvm6object15MachOObjectFileC1ENS_15MemoryBufferRefEbbRNS_5ErrorEjj'/>
<use f='llvm/llvm/lib/Object/MachOObjectFile.cpp' l='1508' u='r' c='_ZN4llvm6object15MachOObjectFileC1ENS_15MemoryBufferRefEbbRNS_5ErrorEjj'/>
<use f='llvm/llvm/lib/Object/MachOObjectFile.cpp' l='1521' u='r' c='_ZN4llvm6object15MachOObjectFileC1ENS_15MemoryBufferRefEbbRNS_5ErrorEjj'/>
<use f='llvm/llvm/lib/Object/MachOObjectFile.cpp' l='1534' u='r' c='_ZN4llvm6object15MachOObjectFileC1ENS_15MemoryBufferRefEbbRNS_5ErrorEjj'/>
<use f='llvm/llvm/lib/Object/MachOObjectFile.cpp' l='1547' u='r' c='_ZN4llvm6object15MachOObjectFileC1ENS_15MemoryBufferRefEbbRNS_5ErrorEjj'/>
<use f='llvm/llvm/lib/Object/MachOObjectFile.cpp' l='1559' u='r' c='_ZN4llvm6object15MachOObjectFileC1ENS_15MemoryBufferRefEbbRNS_5ErrorEjj'/>
<use f='llvm/llvm/lib/Object/MachOObjectFile.cpp' l='1571' u='r' c='_ZN4llvm6object15MachOObjectFileC1ENS_15MemoryBufferRefEbbRNS_5ErrorEjj'/>
<use f='llvm/llvm/lib/Object/MachOObjectFile.cpp' l='1583' u='r' c='_ZN4llvm6object15MachOObjectFileC1ENS_15MemoryBufferRefEbbRNS_5ErrorEjj'/>
<use f='llvm/llvm/lib/Object/MachOObjectFile.cpp' l='1591' u='r' c='_ZN4llvm6object15MachOObjectFileC1ENS_15MemoryBufferRefEbbRNS_5ErrorEjj'/>
<use f='llvm/llvm/lib/Object/MachOObjectFile.cpp' l='1595' u='r' c='_ZN4llvm6object15MachOObjectFileC1ENS_15MemoryBufferRefEbbRNS_5ErrorEjj'/>
<use f='llvm/llvm/lib/Object/MachOObjectFile.cpp' l='1599' u='r' c='_ZN4llvm6object15MachOObjectFileC1ENS_15MemoryBufferRefEbbRNS_5ErrorEjj'/>
<use f='llvm/llvm/lib/Object/MachOObjectFile.cpp' l='1602' u='r' c='_ZN4llvm6object15MachOObjectFileC1ENS_15MemoryBufferRefEbbRNS_5ErrorEjj'/>
<use f='llvm/llvm/lib/Object/MachOObjectFile.cpp' l='1604' u='r' c='_ZN4llvm6object15MachOObjectFileC1ENS_15MemoryBufferRefEbbRNS_5ErrorEjj'/>
<use f='llvm/llvm/lib/Object/MachOUniversalWriter.cpp' l='36' u='r' c='_ZL22calculateFileAlignmentRKN4llvm6object15MachOObjectFileE'/>
<use f='llvm/llvm/lib/ObjectYAML/MachOEmitter.cpp' l='233' u='r' c='_ZN12_GLOBAL__N_111MachOWriter17writeLoadCommandsERN4llvm11raw_ostreamE'/>
<use f='llvm/llvm/lib/ObjectYAML/MachOEmitter.cpp' l='268' u='r' c='_ZN12_GLOBAL__N_111MachOWriter16writeSectionDataERN4llvm11raw_ostreamE'/>
<use f='llvm/llvm/lib/ObjectYAML/MachOEmitter.cpp' l='359' u='r' c='_ZN12_GLOBAL__N_111MachOWriter16writeRelocationsERN4llvm11raw_ostreamE'/>
<use f='llvm/llvm/lib/ObjectYAML/MachOEmitter.cpp' l='451' u='r' c='_ZN12_GLOBAL__N_111MachOWriter17writeLinkEditDataERN4llvm11raw_ostreamE'/>
<use f='llvm/llvm/lib/ObjectYAML/MachOYAML.cpp' l='245' u='r' c='_ZN4llvm4yaml13MappingTraitsINS_9MachOYAML11LoadCommandEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/MachOYAML.cpp' l='247' u='w' c='_ZN4llvm4yaml13MappingTraitsINS_9MachOYAML11LoadCommandEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/MachOYAML.cpp' l='257' u='r' c='_ZN4llvm4yaml13MappingTraitsINS_9MachOYAML11LoadCommandEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/tools/dsymutil/MachOUtils.cpp' l='143' u='r' c='_ZN4llvm8dsymutil10MachOUtilsL17iterateOnSegmentsERKNS_6object15MachOObjectFileET_'/>
<use f='llvm/llvm/tools/dsymutil/MachOUtils.cpp' l='145' u='r' c='_ZN4llvm8dsymutil10MachOUtilsL17iterateOnSegmentsERKNS_6object15MachOObjectFileET_'/>
<use f='llvm/llvm/tools/dsymutil/MachOUtils.cpp' l='402' u='r' c='_ZN4llvm8dsymutil10MachOUtils21generateDsymCompanionENS_18IntrusiveRefCntPtrINS_3vfs10FileSystemEEERKNS0_8DebugMapERNS0_19SymbolMapTranslatorERNS_10MC9861341'/>
<use f='llvm/llvm/tools/dsymutil/MachOUtils.cpp' l='545' u='r' c='_ZN4llvm8dsymutil10MachOUtils21generateDsymCompanionENS_18IntrusiveRefCntPtrINS_3vfs10FileSystemEEERKNS0_8DebugMapERNS0_19SymbolMapTranslatorERNS_10MC9861341'/>
<use f='llvm/llvm/tools/dsymutil/MachOUtils.cpp' l='550' u='r' c='_ZN4llvm8dsymutil10MachOUtils21generateDsymCompanionENS_18IntrusiveRefCntPtrINS_3vfs10FileSystemEEERKNS0_8DebugMapERNS0_19SymbolMapTranslatorERNS_10MC9861341'/>
<use f='llvm/llvm/tools/llvm-gsymutil/llvm-gsymutil.cpp' l='233' u='r' c='_ZL19getImageBaseAddressPKN4llvm6object15MachOObjectFileE'/>
<use f='llvm/llvm/tools/llvm-gsymutil/llvm-gsymutil.cpp' l='238' u='r' c='_ZL19getImageBaseAddressPKN4llvm6object15MachOObjectFileE'/>
<use f='llvm/llvm/tools/llvm-nm/llvm-nm.cpp' l='1247' u='r' c='_ZL26dumpSymbolsFromDLInfoMachORN4llvm6object15MachOObjectFileE'/>
<use f='llvm/llvm/tools/llvm-nm/llvm-nm.cpp' l='1253' u='r' c='_ZL26dumpSymbolsFromDLInfoMachORN4llvm6object15MachOObjectFileE'/>
<use f='llvm/llvm/tools/llvm-nm/llvm-nm.cpp' l='1604' u='r' c='_ZL26dumpSymbolsFromDLInfoMachORN4llvm6object15MachOObjectFileE'/>
<use f='llvm/llvm/tools/llvm-nm/llvm-nm.cpp' l='1611' u='r' c='_ZL26dumpSymbolsFromDLInfoMachORN4llvm6object15MachOObjectFileE'/>
<use f='llvm/llvm/tools/llvm-objcopy/MachO/MachOLayoutBuilder.cpp' l='30' u='r' c='_ZNK4llvm7objcopy5macho18MachOLayoutBuilder17computeSizeOfCmdsEv'/>
<use f='llvm/llvm/tools/llvm-objcopy/MachO/MachOLayoutBuilder.cpp' l='124' u='r' c='_ZN4llvm7objcopy5macho18MachOLayoutBuilder14layoutSegmentsEv'/>
<use f='llvm/llvm/tools/llvm-objcopy/MachO/MachOLayoutBuilder.cpp' l='190' u='r' c='_ZN4llvm7objcopy5macho18MachOLayoutBuilder14layoutSegmentsEv'/>
<use f='llvm/llvm/tools/llvm-objcopy/MachO/MachOLayoutBuilder.cpp' l='272' u='r' c='_ZN4llvm7objcopy5macho18MachOLayoutBuilder10layoutTailEm'/>
<use f='llvm/llvm/tools/llvm-objcopy/MachO/MachOLayoutBuilder.cpp' l='290' u='r' c='_ZN4llvm7objcopy5macho18MachOLayoutBuilder10layoutTailEm'/>
<use f='llvm/llvm/tools/llvm-objcopy/MachO/MachOObjcopy.cpp' l='142' u='r' c='_ZN4llvm7objcopy5machoL19processLoadCommandsERKNS0_10CopyConfigERNS1_6ObjectE'/>
<use f='llvm/llvm/tools/llvm-objcopy/MachO/MachOObjcopy.cpp' l='173' u='r' c='_ZN4llvm7objcopy5machoL19processLoadCommandsERKNS0_10CopyConfigERNS1_6ObjectE'/>
<use f='llvm/llvm/tools/llvm-objcopy/MachO/MachOObjcopy.cpp' l='192' u='r' c='_ZN4llvm7objcopy5machoL19processLoadCommandsERKNS0_10CopyConfigERNS1_6ObjectE'/>
<use f='llvm/llvm/tools/llvm-objcopy/MachO/MachOReader.cpp' l='121' u='r' c='_ZNK4llvm7objcopy5macho11MachOReader16readLoadCommandsERNS1_6ObjectE'/>
<use f='llvm/llvm/tools/llvm-objcopy/MachO/MachOReader.cpp' l='171' u='r' c='_ZNK4llvm7objcopy5macho11MachOReader16readLoadCommandsERNS1_6ObjectE'/>
<use f='llvm/llvm/tools/llvm-objcopy/MachO/MachOWriter.cpp' l='170' u='r' c='_ZN4llvm7objcopy5macho11MachOWriter17writeLoadCommandsEv'/>
<use f='llvm/llvm/tools/llvm-objcopy/MachO/MachOWriter.cpp' l='206' u='r' c='_ZN4llvm7objcopy5macho11MachOWriter17writeLoadCommandsEv'/>
<use f='llvm/llvm/tools/llvm-objcopy/MachO/Object.cpp' l='36' u='r' c='_ZN4llvm7objcopy5macho6Object24updateLoadCommandIndexesEv'/>
<use f='llvm/llvm/tools/llvm-objcopy/MachO/Object.cpp' l='117' u='r' c='_ZNK4llvm7objcopy5macho6Object27nextAvailableSegmentAddressEv'/>
<use f='llvm/llvm/tools/llvm-objcopy/MachO/Object.cpp' l='172' u='r' c='_ZNK4llvm7objcopy5macho11LoadCommand14getSegmentNameEv'/>
<use f='llvm/llvm/tools/llvm-objcopy/MachO/Object.cpp' l='184' u='r' c='_ZNK4llvm7objcopy5macho11LoadCommand16getSegmentVMAddrEv'/>
<use f='llvm/llvm/tools/llvm-objdump/MachODump.cpp' l='370' u='r' c='_ZL21getSectionsAndSymbolsPN4llvm6object15MachOObjectFileERSt6vectorINS0_10SectionRefESaIS4_EERS3_INS0_9SymbolRefESaIS8_EERNS_15SmallVectorImplImEERm'/>
<use f='llvm/llvm/tools/llvm-objdump/MachODump.cpp' l='377' u='r' c='_ZL21getSectionsAndSymbolsPN4llvm6object15MachOObjectFileERSt6vectorINS0_10SectionRefESaIS4_EERS3_INS0_9SymbolRefESaIS8_EERNS_15SmallVectorImplImEERm'/>
<use f='llvm/llvm/tools/llvm-objdump/MachODump.cpp' l='384' u='r' c='_ZL21getSectionsAndSymbolsPN4llvm6object15MachOObjectFileERSt6vectorINS0_10SectionRefESaIS4_EERS3_INS0_9SymbolRefESaIS8_EERNS_15SmallVectorImplImEERm'/>
<use f='llvm/llvm/tools/llvm-objdump/MachODump.cpp' l='727' u='r' c='_ZL20PrintIndirectSymbolsPN4llvm6object15MachOObjectFileEb'/>
<use f='llvm/llvm/tools/llvm-objdump/MachODump.cpp' l='755' u='r' c='_ZL20PrintIndirectSymbolsPN4llvm6object15MachOObjectFileEb'/>
<use f='llvm/llvm/tools/llvm-objdump/MachODump.cpp' l='1063' u='r' c='_ZL16PrintRelocationsPKN4llvm6object15MachOObjectFileEb'/>
<use f='llvm/llvm/tools/llvm-objdump/MachODump.cpp' l='1083' u='r' c='_ZL16PrintRelocationsPKN4llvm6object15MachOObjectFileEb'/>
<use f='llvm/llvm/tools/llvm-objdump/MachODump.cpp' l='1209' u='r' c='_ZL11PrintDylibsPN4llvm6object15MachOObjectFileEb'/>
<use f='llvm/llvm/tools/llvm-objdump/MachODump.cpp' l='1210' u='r' c='_ZL11PrintDylibsPN4llvm6object15MachOObjectFileEb'/>
<use f='llvm/llvm/tools/llvm-objdump/MachODump.cpp' l='1211' u='r' c='_ZL11PrintDylibsPN4llvm6object15MachOObjectFileEb'/>
<use f='llvm/llvm/tools/llvm-objdump/MachODump.cpp' l='1212' u='r' c='_ZL11PrintDylibsPN4llvm6object15MachOObjectFileEb'/>
<use f='llvm/llvm/tools/llvm-objdump/MachODump.cpp' l='1213' u='r' c='_ZL11PrintDylibsPN4llvm6object15MachOObjectFileEb'/>
<use f='llvm/llvm/tools/llvm-objdump/MachODump.cpp' l='1214' u='r' c='_ZL11PrintDylibsPN4llvm6object15MachOObjectFileEb'/>
<use f='llvm/llvm/tools/llvm-objdump/MachODump.cpp' l='1215' u='r' c='_ZL11PrintDylibsPN4llvm6object15MachOObjectFileEb'/>
<use f='llvm/llvm/tools/llvm-objdump/MachODump.cpp' l='1231' u='r' c='_ZL11PrintDylibsPN4llvm6object15MachOObjectFileEb'/>
<use f='llvm/llvm/tools/llvm-objdump/MachODump.cpp' l='1233' u='r' c='_ZL11PrintDylibsPN4llvm6object15MachOObjectFileEb'/>
<use f='llvm/llvm/tools/llvm-objdump/MachODump.cpp' l='1235' u='r' c='_ZL11PrintDylibsPN4llvm6object15MachOObjectFileEb'/>
<use f='llvm/llvm/tools/llvm-objdump/MachODump.cpp' l='1237' u='r' c='_ZL11PrintDylibsPN4llvm6object15MachOObjectFileEb'/>
<use f='llvm/llvm/tools/llvm-objdump/MachODump.cpp' l='1243' u='r' c='_ZL11PrintDylibsPN4llvm6object15MachOObjectFileEb'/>
<use f='llvm/llvm/tools/llvm-objdump/MachODump.cpp' l='1245' u='r' c='_ZL11PrintDylibsPN4llvm6object15MachOObjectFileEb'/>
<use f='llvm/llvm/tools/llvm-objdump/MachODump.cpp' l='1247' u='r' c='_ZL11PrintDylibsPN4llvm6object15MachOObjectFileEb'/>
<use f='llvm/llvm/tools/llvm-objdump/MachODump.cpp' l='1249' u='r' c='_ZL11PrintDylibsPN4llvm6object15MachOObjectFileEb'/>
<use f='llvm/llvm/tools/llvm-objdump/MachODump.cpp' l='1251' u='r' c='_ZL11PrintDylibsPN4llvm6object15MachOObjectFileEb'/>
<use f='llvm/llvm/tools/llvm-objdump/MachODump.cpp' l='1253' u='r' c='_ZL11PrintDylibsPN4llvm6object15MachOObjectFileEb'/>
<use f='llvm/llvm/tools/llvm-objdump/MachODump.cpp' l='3016' u='r' c='_ZL19GuessCstringPointermPN12_GLOBAL__N_115DisassembleInfoE'/>
<use f='llvm/llvm/tools/llvm-objdump/MachODump.cpp' l='3037' u='r' c='_ZL19GuessCstringPointermPN12_GLOBAL__N_115DisassembleInfoE'/>
<use f='llvm/llvm/tools/llvm-objdump/MachODump.cpp' l='3072' u='r' c='_ZL19GuessIndirectSymbolmPN12_GLOBAL__N_115DisassembleInfoE'/>
<use f='llvm/llvm/tools/llvm-objdump/MachODump.cpp' l='3103' u='r' c='_ZL19GuessIndirectSymbolmPN12_GLOBAL__N_115DisassembleInfoE'/>
<use f='llvm/llvm/tools/llvm-objdump/MachODump.cpp' l='3223' u='r' c='_ZL19GuessPointerPointermPN12_GLOBAL__N_115DisassembleInfoERbS2_S2_S2_'/>
<use f='llvm/llvm/tools/llvm-objdump/MachODump.cpp' l='10090' u='r' c='_ZL17PrintLoadCommandsPKN4llvm6object15MachOObjectFileEjjb'/>
<use f='llvm/llvm/tools/llvm-objdump/MachODump.cpp' l='10103' u='r' c='_ZL17PrintLoadCommandsPKN4llvm6object15MachOObjectFileEjjb'/>
<use f='llvm/llvm/tools/llvm-objdump/MachODump.cpp' l='10117' u='r' c='_ZL17PrintLoadCommandsPKN4llvm6object15MachOObjectFileEjjb'/>
<use f='llvm/llvm/tools/llvm-objdump/MachODump.cpp' l='10120' u='r' c='_ZL17PrintLoadCommandsPKN4llvm6object15MachOObjectFileEjjb'/>
<use f='llvm/llvm/tools/llvm-objdump/MachODump.cpp' l='10125' u='r' c='_ZL17PrintLoadCommandsPKN4llvm6object15MachOObjectFileEjjb'/>
<use f='llvm/llvm/tools/llvm-objdump/MachODump.cpp' l='10126' u='r' c='_ZL17PrintLoadCommandsPKN4llvm6object15MachOObjectFileEjjb'/>
<use f='llvm/llvm/tools/llvm-objdump/MachODump.cpp' l='10129' u='r' c='_ZL17PrintLoadCommandsPKN4llvm6object15MachOObjectFileEjjb'/>
<use f='llvm/llvm/tools/llvm-objdump/MachODump.cpp' l='10130' u='r' c='_ZL17PrintLoadCommandsPKN4llvm6object15MachOObjectFileEjjb'/>
<use f='llvm/llvm/tools/llvm-objdump/MachODump.cpp' l='10131' u='r' c='_ZL17PrintLoadCommandsPKN4llvm6object15MachOObjectFileEjjb'/>
<use f='llvm/llvm/tools/llvm-objdump/MachODump.cpp' l='10134' u='r' c='_ZL17PrintLoadCommandsPKN4llvm6object15MachOObjectFileEjjb'/>
<use f='llvm/llvm/tools/llvm-objdump/MachODump.cpp' l='10137' u='r' c='_ZL17PrintLoadCommandsPKN4llvm6object15MachOObjectFileEjjb'/>
<use f='llvm/llvm/tools/llvm-objdump/MachODump.cpp' l='10140' u='r' c='_ZL17PrintLoadCommandsPKN4llvm6object15MachOObjectFileEjjb'/>
<use f='llvm/llvm/tools/llvm-objdump/MachODump.cpp' l='10141' u='r' c='_ZL17PrintLoadCommandsPKN4llvm6object15MachOObjectFileEjjb'/>
<use f='llvm/llvm/tools/llvm-objdump/MachODump.cpp' l='10142' u='r' c='_ZL17PrintLoadCommandsPKN4llvm6object15MachOObjectFileEjjb'/>
<use f='llvm/llvm/tools/llvm-objdump/MachODump.cpp' l='10143' u='r' c='_ZL17PrintLoadCommandsPKN4llvm6object15MachOObjectFileEjjb'/>
<use f='llvm/llvm/tools/llvm-objdump/MachODump.cpp' l='10146' u='r' c='_ZL17PrintLoadCommandsPKN4llvm6object15MachOObjectFileEjjb'/>
<use f='llvm/llvm/tools/llvm-objdump/MachODump.cpp' l='10149' u='r' c='_ZL17PrintLoadCommandsPKN4llvm6object15MachOObjectFileEjjb'/>
<use f='llvm/llvm/tools/llvm-objdump/MachODump.cpp' l='10153' u='r' c='_ZL17PrintLoadCommandsPKN4llvm6object15MachOObjectFileEjjb'/>
<use f='llvm/llvm/tools/llvm-objdump/MachODump.cpp' l='10156' u='r' c='_ZL17PrintLoadCommandsPKN4llvm6object15MachOObjectFileEjjb'/>
<use f='llvm/llvm/tools/llvm-objdump/MachODump.cpp' l='10159' u='r' c='_ZL17PrintLoadCommandsPKN4llvm6object15MachOObjectFileEjjb'/>
<use f='llvm/llvm/tools/llvm-objdump/MachODump.cpp' l='10163' u='r' c='_ZL17PrintLoadCommandsPKN4llvm6object15MachOObjectFileEjjb'/>
<use f='llvm/llvm/tools/llvm-objdump/MachODump.cpp' l='10167' u='r' c='_ZL17PrintLoadCommandsPKN4llvm6object15MachOObjectFileEjjb'/>
<use f='llvm/llvm/tools/llvm-objdump/MachODump.cpp' l='10171' u='r' c='_ZL17PrintLoadCommandsPKN4llvm6object15MachOObjectFileEjjb'/>
<use f='llvm/llvm/tools/llvm-objdump/MachODump.cpp' l='10174' u='r' c='_ZL17PrintLoadCommandsPKN4llvm6object15MachOObjectFileEjjb'/>
<use f='llvm/llvm/tools/llvm-objdump/MachODump.cpp' l='10177' u='r' c='_ZL17PrintLoadCommandsPKN4llvm6object15MachOObjectFileEjjb'/>
<use f='llvm/llvm/tools/llvm-objdump/MachODump.cpp' l='10180' u='r' c='_ZL17PrintLoadCommandsPKN4llvm6object15MachOObjectFileEjjb'/>
<use f='llvm/llvm/tools/llvm-objdump/MachODump.cpp' l='10183' u='r' c='_ZL17PrintLoadCommandsPKN4llvm6object15MachOObjectFileEjjb'/>
<use f='llvm/llvm/tools/llvm-objdump/MachODump.cpp' l='10186' u='r' c='_ZL17PrintLoadCommandsPKN4llvm6object15MachOObjectFileEjjb'/>
<use f='llvm/llvm/tools/llvm-objdump/MachODump.cpp' l='10189' u='r' c='_ZL17PrintLoadCommandsPKN4llvm6object15MachOObjectFileEjjb'/>
<use f='llvm/llvm/tools/llvm-objdump/MachODump.cpp' l='10190' u='r' c='_ZL17PrintLoadCommandsPKN4llvm6object15MachOObjectFileEjjb'/>
<use f='llvm/llvm/tools/llvm-objdump/MachODump.cpp' l='10193' u='r' c='_ZL17PrintLoadCommandsPKN4llvm6object15MachOObjectFileEjjb'/>
<use f='llvm/llvm/tools/llvm-objdump/MachODump.cpp' l='10194' u='r' c='_ZL17PrintLoadCommandsPKN4llvm6object15MachOObjectFileEjjb'/>
<use f='llvm/llvm/tools/llvm-objdump/MachODump.cpp' l='10195' u='r' c='_ZL17PrintLoadCommandsPKN4llvm6object15MachOObjectFileEjjb'/>
<use f='llvm/llvm/tools/llvm-objdump/MachODump.cpp' l='10196' u='r' c='_ZL17PrintLoadCommandsPKN4llvm6object15MachOObjectFileEjjb'/>
<use f='llvm/llvm/tools/llvm-objdump/MachODump.cpp' l='10197' u='r' c='_ZL17PrintLoadCommandsPKN4llvm6object15MachOObjectFileEjjb'/>
<use f='llvm/llvm/tools/llvm-objdump/MachODump.cpp' l='10198' u='r' c='_ZL17PrintLoadCommandsPKN4llvm6object15MachOObjectFileEjjb'/>
<use f='llvm/llvm/tools/llvm-objdump/MachODump.cpp' l='10201' u='r' c='_ZL17PrintLoadCommandsPKN4llvm6object15MachOObjectFileEjjb'/>
<use f='llvm/llvm/tools/llvm-objdump/MachODump.cpp' l='10202' u='r' c='_ZL17PrintLoadCommandsPKN4llvm6object15MachOObjectFileEjjb'/>
<use f='llvm/llvm/tools/llvm-objdump/MachODump.cpp' l='10203' u='r' c='_ZL17PrintLoadCommandsPKN4llvm6object15MachOObjectFileEjjb'/>
<use f='llvm/llvm/tools/llvm-objdump/MachODump.cpp' l='10204' u='r' c='_ZL17PrintLoadCommandsPKN4llvm6object15MachOObjectFileEjjb'/>
<use f='llvm/llvm/tools/llvm-objdump/MachODump.cpp' l='10205' u='r' c='_ZL17PrintLoadCommandsPKN4llvm6object15MachOObjectFileEjjb'/>
<use f='llvm/llvm/tools/llvm-objdump/MachODump.cpp' l='10206' u='r' c='_ZL17PrintLoadCommandsPKN4llvm6object15MachOObjectFileEjjb'/>
<use f='llvm/llvm/tools/llvm-objdump/MachODump.cpp' l='10211' u='r' c='_ZL17PrintLoadCommandsPKN4llvm6object15MachOObjectFileEjjb'/>
<use f='llvm/llvm/tools/llvm-objdump/MachODump.cpp' l='10264' u='r' c='_ZL21printMachOExportsTriePKN4llvm6object15MachOObjectFileE'/>
<use f='llvm/llvm/tools/llvm-objdump/MachODump.cpp' l='10270' u='r' c='_ZL21printMachOExportsTriePKN4llvm6object15MachOObjectFileE'/>
<use f='llvm/llvm/tools/llvm-readobj/MachODumper.cpp' l='703' u='r' c='_ZN12_GLOBAL__N_111MachODumper20printNeededLibrariesEv'/>
<use f='llvm/llvm/tools/llvm-readobj/MachODumper.cpp' l='704' u='r' c='_ZN12_GLOBAL__N_111MachODumper20printNeededLibrariesEv'/>
<use f='llvm/llvm/tools/llvm-readobj/MachODumper.cpp' l='705' u='r' c='_ZN12_GLOBAL__N_111MachODumper20printNeededLibrariesEv'/>
<use f='llvm/llvm/tools/llvm-readobj/MachODumper.cpp' l='706' u='r' c='_ZN12_GLOBAL__N_111MachODumper20printNeededLibrariesEv'/>
<use f='llvm/llvm/tools/llvm-readobj/MachODumper.cpp' l='707' u='r' c='_ZN12_GLOBAL__N_111MachODumper20printNeededLibrariesEv'/>
<use f='llvm/llvm/tools/llvm-readobj/MachODumper.cpp' l='708' u='r' c='_ZN12_GLOBAL__N_111MachODumper20printNeededLibrariesEv'/>
<use f='llvm/llvm/tools/llvm-readobj/MachODumper.cpp' l='726' u='r' c='_ZN12_GLOBAL__N_111MachODumper20printMachODataInCodeEv'/>
<use f='llvm/llvm/tools/llvm-readobj/MachODumper.cpp' l='749' u='r' c='_ZN12_GLOBAL__N_111MachODumper20printMachOVersionMinEv'/>
<use f='llvm/llvm/tools/llvm-readobj/MachODumper.cpp' l='771' u='r' c='_ZN12_GLOBAL__N_111MachODumper20printMachOVersionMinEv'/>
<use f='llvm/llvm/tools/llvm-readobj/MachODumper.cpp' l='811' u='r' c='_ZN12_GLOBAL__N_111MachODumper18printMachODysymtabEv'/>
<use f='llvm/llvm/tools/llvm-readobj/MachODumper.cpp' l='838' u='r' c='_ZN12_GLOBAL__N_111MachODumper17printMachOSegmentEv'/>
<use f='llvm/llvm/tools/llvm-readobj/MachODumper.cpp' l='838' u='r' c='_ZN12_GLOBAL__N_111MachODumper17printMachOSegmentEv'/>
<use f='llvm/llvm/tools/llvm-readobj/MachODumper.cpp' l='859' u='r' c='_ZN12_GLOBAL__N_111MachODumper25printMachOIndirectSymbolsEv'/>
<use f='llvm/llvm/tools/llvm-readobj/MachODumper.cpp' l='875' u='r' c='_ZN12_GLOBAL__N_111MachODumper23printMachOLinkerOptionsEv'/>
<use f='llvm/llvm/tools/llvm-size/llvm-size.cpp' l='229' u='r' c='_ZL23printDarwinSectionSizesPN4llvm6object15MachOObjectFileE'/>
<use f='llvm/llvm/tools/llvm-size/llvm-size.cpp' l='255' u='r' c='_ZL23printDarwinSectionSizesPN4llvm6object15MachOObjectFileE'/>
<use f='llvm/llvm/tools/llvm-size/llvm-size.cpp' l='298' u='r' c='_ZL23printDarwinSegmentSizesPN4llvm6object15MachOObjectFileE'/>
<use f='llvm/llvm/tools/llvm-size/llvm-size.cpp' l='324' u='r' c='_ZL23printDarwinSegmentSizesPN4llvm6object15MachOObjectFileE'/>
<use f='llvm/llvm/tools/obj2yaml/macho2yaml.cpp' l='305' u='r' c='_ZN11MachODumper16dumpLoadCommandsERSt10unique_ptrIN4llvm9MachOYAML6ObjectESt14default_deleteIS3_EE'/>
<use f='llvm/llvm/tools/sancov/sancov.cpp' l='611' u='r' c='_ZN12_GLOBAL__N_129findMachOIndirectCovFunctionsERKN4llvm6object15MachOObjectFileEPSt3setImSt4lessImESaImEE'/>
<use f='llvm/llvm/tools/sancov/sancov.cpp' l='637' u='r' c='_ZN12_GLOBAL__N_129findMachOIndirectCovFunctionsERKN4llvm6object15MachOObjectFileEPSt3setImSt4lessImESaImEE'/>
<use f='llvm/llvm/unittests/BinaryFormat/MachOTest.cpp' l='44' u='r' c='_ZN26MachOTest_UnalignedLC_Test8TestBodyEv'/>
<use f='llvm/llvm/unittests/BinaryFormat/MachOTest.cpp' l='44' u='r' c='_ZN26MachOTest_UnalignedLC_Test8TestBodyEv'/>
