<dec f='llvm/llvm/include/llvm/CodeGen/DIE.h' l='732' type='dwarf::Tag'/>
<use f='llvm/llvm/include/llvm/CodeGen/DIE.h' l='743' u='w' c='_ZN4llvm3DIEC1ENS_5dwarf3TagE'/>
<use f='llvm/llvm/include/llvm/CodeGen/DIE.h' l='758' u='r' c='_ZNK4llvm3DIE6getTagEv'/>
<offset>224</offset>
<doc f='llvm/llvm/include/llvm/CodeGen/DIE.h' l='731'>/// Dwarf tag code.</doc>
<use f='llvm/llvm/lib/CodeGen/AsmPrinter/DIE.cpp' l='187' u='r' c='_ZNK4llvm3DIE14generateAbbrevEv'/>
