<dec f='llvm/llvm/include/llvm/ObjectYAML/DWARFYAML.h' l='38' type='llvm::dwarf::Tag'/>
<offset>128</offset>
<use f='llvm/llvm/lib/ObjectYAML/DWARFEmitter.cpp' l='110' u='r' c='_ZNK4llvm9DWARFYAML4Data28getAbbrevTableContentByIndexEm'/>
<use f='llvm/llvm/lib/ObjectYAML/DWARFYAML.cpp' l='122' u='a' c='_ZN4llvm4yaml13MappingTraitsINS_9DWARFYAML6AbbrevEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/tools/obj2yaml/dwarf2yaml.cpp' l='33' u='w' c='_Z15dumpDebugAbbrevRN4llvm12DWARFContextERNS_9DWARFYAML4DataE'/>
