<dec f='llvm/llvm/lib/Target/AArch64/MCTargetDesc/AArch64AddressingModes.h' l='34' type='0'/>
<use f='llvm/llvm/lib/Target/AArch64/MCTargetDesc/AArch64AddressingModes.h' l='55' c='_ZN4llvm10AArch64_AML18getShiftExtendNameENS0_15ShiftExtendTypeE'/>
<use f='llvm/llvm/lib/Target/AArch64/MCTargetDesc/AArch64AddressingModes.h' l='76' u='r' c='_ZN4llvm10AArch64_AML12getShiftTypeEj'/>
<use f='llvm/llvm/lib/Target/AArch64/MCTargetDesc/AArch64AddressingModes.h' l='104' c='_ZN4llvm10AArch64_AML13getShifterImmENS0_15ShiftExtendTypeEj'/>
<use f='llvm/llvm/lib/Target/AArch64/AArch64ExpandImm.cpp' l='83' u='r' c='_ZN4llvm11AArch64_IMML20tryToreplicateChunksEmRNS_15SmallVectorImplINS0_12ImmInsnModelEEE'/>
<use f='llvm/llvm/lib/Target/AArch64/AArch64ExpandImm.cpp' l='98' u='r' c='_ZN4llvm11AArch64_IMML20tryToreplicateChunksEmRNS_15SmallVectorImplINS0_12ImmInsnModelEEE'/>
<use f='llvm/llvm/lib/Target/AArch64/AArch64ExpandImm.cpp' l='229' u='r' c='_ZN4llvm11AArch64_IMML17trySequenceOfOnesEmRNS_15SmallVectorImplINS0_12ImmInsnModelEEE'/>
<use f='llvm/llvm/lib/Target/AArch64/AArch64ExpandImm.cpp' l='238' u='r' c='_ZN4llvm11AArch64_IMML17trySequenceOfOnesEmRNS_15SmallVectorImplINS0_12ImmInsnModelEEE'/>
<use f='llvm/llvm/lib/Target/AArch64/AArch64ExpandImm.cpp' l='281' u='r' c='_ZN4llvm11AArch64_IMML18expandMOVImmSimpleEmjjjRNS_15SmallVectorImplINS0_12ImmInsnModelEEE'/>
<use f='llvm/llvm/lib/Target/AArch64/AArch64ExpandImm.cpp' l='299' u='r' c='_ZN4llvm11AArch64_IMML18expandMOVImmSimpleEmjjjRNS_15SmallVectorImplINS0_12ImmInsnModelEEE'/>
<use f='llvm/llvm/lib/Target/AArch64/AArch64ExpandImm.cpp' l='372' u='r' c='_ZN4llvm11AArch64_IMM12expandMOVImmEmjRNS_15SmallVectorImplINS0_12ImmInsnModelEEE'/>
<use f='llvm/llvm/lib/Target/AArch64/AArch64ExpandPseudoInsts.cpp' l='807' u='r' c='_ZN12_GLOBAL__N_119AArch64ExpandPseudo8expandMIERN4llvm17MachineBasicBlockENS1_26MachineInstrBundleIteratorINS1_12MachineInstrELb0EEERS6_'/>
<use f='llvm/llvm/lib/Target/AArch64/AArch64ExpandPseudoInsts.cpp' l='977' u='r' c='_ZN12_GLOBAL__N_119AArch64ExpandPseudo8expandMIERN4llvm17MachineBasicBlockENS1_26MachineInstrBundleIteratorINS1_12MachineInstrELb0EEERS6_'/>
<use f='llvm/llvm/lib/Target/AArch64/AArch64ExpandPseudoInsts.cpp' l='982' u='r' c='_ZN12_GLOBAL__N_119AArch64ExpandPseudo8expandMIERN4llvm17MachineBasicBlockENS1_26MachineInstrBundleIteratorINS1_12MachineInstrELb0EEERS6_'/>
<use f='llvm/llvm/lib/Target/AArch64/AArch64FastISel.cpp' l='733' u='r' c='_ZN12_GLOBAL__N_115AArch64FastISel14computeAddressEPKN4llvm5ValueERNS0_7AddressEPNS1_4TypeE'/>
<use f='llvm/llvm/lib/Target/AArch64/AArch64FastISel.cpp' l='817' u='r' c='_ZN12_GLOBAL__N_115AArch64FastISel14computeAddressEPKN4llvm5ValueERNS0_7AddressEPNS1_4TypeE'/>
<use f='llvm/llvm/lib/Target/AArch64/AArch64FastISel.cpp' l='862' u='r' c='_ZN12_GLOBAL__N_115AArch64FastISel14computeAddressEPKN4llvm5ValueERNS0_7AddressEPNS1_4TypeE'/>
<use f='llvm/llvm/lib/Target/AArch64/AArch64FastISel.cpp' l='1076' u='r' c='_ZN12_GLOBAL__N_115AArch64FastISel15simplifyAddressERNS0_7AddressEN4llvm3MVTE'/>
<use f='llvm/llvm/lib/Target/AArch64/AArch64FastISel.cpp' l='1266' u='r' c='_ZN12_GLOBAL__N_115AArch64FastISel10emitAddSubEbN4llvm3MVTEPKNS1_5ValueES5_bbb'/>
<use f='llvm/llvm/lib/Target/AArch64/AArch64FastISel.cpp' l='1280' u='r' c='_ZN12_GLOBAL__N_115AArch64FastISel10emitAddSubEbN4llvm3MVTEPKNS1_5ValueES5_bbb'/>
<use f='llvm/llvm/lib/Target/AArch64/AArch64FastISel.cpp' l='1391' u='r' c='_ZN12_GLOBAL__N_115AArch64FastISel13emitAddSub_riEbN4llvm3MVTEjbmbb'/>
<use f='llvm/llvm/lib/Target/AArch64/AArch64FastISel.cpp' l='1770' u='r' c='_ZN12_GLOBAL__N_115AArch64FastISel16emitLogicalOp_rsEjN4llvm3MVTEjbjbm'/>
<use f='llvm/llvm/lib/Target/AArch64/AArch64FrameLowering.cpp' l='1200' u='r' c='_ZNK4llvm20AArch64FrameLowering12emitPrologueERNS_15MachineFunctionERNS_17MachineBasicBlockE'/>
<use f='llvm/llvm/lib/Target/AArch64/AArch64FrameLowering.cpp' l='1208' u='r' c='_ZNK4llvm20AArch64FrameLowering12emitPrologueERNS_15MachineFunctionERNS_17MachineBasicBlockE'/>
<use f='llvm/llvm/lib/Target/AArch64/AArch64ISelDAGToDAG.cpp' l='413' u='r' c='_ZN12_GLOBAL__N_119AArch64DAGToDAGISel16SelectArithImmedEN4llvm7SDValueERS2_S3_'/>
<use f='llvm/llvm/lib/Target/AArch64/AArch64ISelDAGToDAG.cpp' l='460' u='r' c='_ZL19getShiftTypeForNodeN4llvm7SDValueE'/>
<use f='llvm/llvm/lib/Target/AArch64/AArch64ISelDAGToDAG.cpp' l='2202' u='r' c='_ZL33getUsefulBitsFromOrWithShiftedRegN4llvm7SDValueERNS_5APIntEj'/>
<use f='llvm/llvm/lib/Target/AArch64/AArch64ISelDAGToDAG.cpp' l='3484' u='r' c='_ZN12_GLOBAL__N_119AArch64DAGToDAGISel6SelectEPN4llvm6SDNodeE'/>
<use f='llvm/llvm/lib/Target/AArch64/AArch64InstrInfo.cpp' l='894' u='r' c='_ZN4llvm16AArch64InstrInfo20isFalkorShiftExtFastERKNS_12MachineInstrE'/>
<use f='llvm/llvm/lib/Target/AArch64/AArch64InstrInfo.cpp' l='2919' u='r' c='_ZNK4llvm16AArch64InstrInfo11copyPhysRegERNS_17MachineBasicBlockENS_26MachineInstrBundleIteratorINS_12MachineInstrELb0EEERKNS_8DebugLocENS_10MCRegisterES9_b'/>
<use f='llvm/llvm/lib/Target/AArch64/AArch64InstrInfo.cpp' l='2925' u='r' c='_ZNK4llvm16AArch64InstrInfo11copyPhysRegERNS_17MachineBasicBlockENS_26MachineInstrBundleIteratorINS_12MachineInstrELb0EEERKNS_8DebugLocENS_10MCRegisterES9_b'/>
<use f='llvm/llvm/lib/Target/AArch64/AArch64InstrInfo.cpp' l='2930' u='r' c='_ZNK4llvm16AArch64InstrInfo11copyPhysRegERNS_17MachineBasicBlockENS_26MachineInstrBundleIteratorINS_12MachineInstrELb0EEERKNS_8DebugLocENS_10MCRegisterES9_b'/>
<use f='llvm/llvm/lib/Target/AArch64/AArch64InstrInfo.cpp' l='3013' u='r' c='_ZNK4llvm16AArch64InstrInfo11copyPhysRegERNS_17MachineBasicBlockENS_26MachineInstrBundleIteratorINS_12MachineInstrELb0EEERKNS_8DebugLocENS_10MCRegisterES9_b'/>
<use f='llvm/llvm/lib/Target/AArch64/AArch64InstrInfo.cpp' l='3017' u='r' c='_ZNK4llvm16AArch64InstrInfo11copyPhysRegERNS_17MachineBasicBlockENS_26MachineInstrBundleIteratorINS_12MachineInstrELb0EEERKNS_8DebugLocENS_10MCRegisterES9_b'/>
<use f='llvm/llvm/lib/Target/AArch64/AArch64InstrInfo.cpp' l='3671' u='r' c='_ZL18emitFrameOffsetAdjRN4llvm17MachineBasicBlockENS_26MachineInstrBundleIteratorINS_12MachineInstrELb0EEERKNS_8DebugLocEjjljPKNS_15TargetInstrInfoENS3_6MIFlagEbPb'/>
<use f='llvm/llvm/lib/Target/AArch64/AArch64LoadStoreOptimizer.cpp' l='1049' u='r' c='_ZN12_GLOBAL__N_119AArch64LoadStoreOpt20promoteLoadFromStoreEN4llvm26MachineInstrBundleIteratorINS1_12MachineInstrELb0EEES4_'/>
<use f='llvm/llvm/lib/Target/AArch64/AArch64RegisterInfo.cpp' l='549' u='r' c='_ZNK4llvm19AArch64RegisterInfo28materializeFrameBaseRegisterEPNS_17MachineBasicBlockEil'/>
<use f='llvm/llvm/lib/Target/AArch64/AsmParser/AArch64AsmParser.cpp' l='1217' u='r' c='_ZNK12_GLOBAL__N_114AArch64Operand22isGPR64WithShiftExtendEv'/>
<use f='llvm/llvm/lib/Target/AArch64/AsmParser/AArch64AsmParser.cpp' l='1270' u='r' c='_ZNK12_GLOBAL__N_114AArch64Operand9isShifterEv'/>
<use f='llvm/llvm/lib/Target/AArch64/AsmParser/AArch64AsmParser.cpp' l='1317' u='r' c='_ZNK12_GLOBAL__N_114AArch64Operand8isExtendEv'/>
<use f='llvm/llvm/lib/Target/AArch64/AsmParser/AArch64AsmParser.cpp' l='1336' u='r' c='_ZNK12_GLOBAL__N_114AArch64Operand13isExtendLSL64Ev'/>
<use f='llvm/llvm/lib/Target/AArch64/AsmParser/AArch64AsmParser.cpp' l='1344' u='r' c='_ZNK12_GLOBAL__N_114AArch64Operand12isMemXExtendEv'/>
<use f='llvm/llvm/lib/Target/AArch64/AsmParser/AArch64AsmParser.cpp' l='1365' u='r' c='_ZNK12_GLOBAL__N_114AArch64Operand19isArithmeticShifterEv'/>
<use f='llvm/llvm/lib/Target/AArch64/AsmParser/AArch64AsmParser.cpp' l='1376' u='r' c='_ZNK12_GLOBAL__N_114AArch64Operand16isLogicalShifterEv'/>
<use f='llvm/llvm/lib/Target/AArch64/AsmParser/AArch64AsmParser.cpp' l='1387' u='r' c='_ZNK12_GLOBAL__N_114AArch64Operand17isMovImm32ShifterEv'/>
<use f='llvm/llvm/lib/Target/AArch64/AsmParser/AArch64AsmParser.cpp' l='1399' u='r' c='_ZNK12_GLOBAL__N_114AArch64Operand17isMovImm64ShifterEv'/>
<use f='llvm/llvm/lib/Target/AArch64/AsmParser/AArch64AsmParser.cpp' l='1411' u='r' c='_ZNK12_GLOBAL__N_114AArch64Operand19isLogicalVecShifterEv'/>
<use f='llvm/llvm/lib/Target/AArch64/AsmParser/AArch64AsmParser.cpp' l='1421' u='r' c='_ZNK12_GLOBAL__N_114AArch64Operand27isLogicalVecHalfWordShifterEv'/>
<use f='llvm/llvm/lib/Target/AArch64/AsmParser/AArch64AsmParser.cpp' l='1804' u='r' c='_ZNK12_GLOBAL__N_114AArch64Operand17addExtendOperandsERN4llvm6MCInstEj'/>
<use f='llvm/llvm/lib/Target/AArch64/AsmParser/AArch64AsmParser.cpp' l='1812' u='r' c='_ZNK12_GLOBAL__N_114AArch64Operand19addExtend64OperandsERN4llvm6MCInstEj'/>
<use f='llvm/llvm/lib/Target/AArch64/AsmParser/AArch64AsmParser.cpp' l='1887' c='_ZN12_GLOBAL__N_114AArch64Operand9CreateRegEjNS_7RegKindEN4llvm5SMLocES3_RNS2_9MCContextENS_23RegConstraintEqualityTyENS2_10AArch64_AM15ShiftExtendTypeEjj'/>
<use f='llvm/llvm/lib/Target/AArch64/AsmParser/AArch64AsmParser.cpp' l='1906' c='_ZN12_GLOBAL__N_114AArch64Operand15CreateVectorRegEjNS_7RegKindEjN4llvm5SMLocES3_RNS2_9MCContextENS2_10AArch64_AM15ShiftExtendTypeEjj'/>
<use f='llvm/llvm/lib/Target/AArch64/AsmParser/AArch64AsmParser.cpp' l='2825' u='r' c='_ZN12_GLOBAL__N_116AArch64AsmParser27tryParseOptionalShiftExtendERN4llvm15SmallVectorImplISt10unique_ptrINS1_18MCParsedAsmOperandESt14default_deleteIS4_EEEE'/>
<use f='llvm/llvm/lib/Target/AArch64/AsmParser/AArch64AsmParser.cpp' l='2849' u='r' c='_ZN12_GLOBAL__N_116AArch64AsmParser27tryParseOptionalShiftExtendERN4llvm15SmallVectorImplISt10unique_ptrINS1_18MCParsedAsmOperandESt14default_deleteIS4_EEEE'/>
<use f='llvm/llvm/lib/Target/AArch64/AsmParser/AArch64AsmParser.cpp' l='3880' u='r' c='_ZN12_GLOBAL__N_116AArch64AsmParser12parseOperandERN4llvm15SmallVectorImplISt10unique_ptrINS1_18MCParsedAsmOperandESt14default_deleteIS4_EEEEbb'/>
<use f='llvm/llvm/lib/Target/AArch64/GISel/AArch64InstructionSelector.cpp' l='5106' u='r' c='_ZNK12_GLOBAL__N_126AArch64InstructionSelector29select12BitValueWithLeftShiftEm'/>
<use f='llvm/llvm/lib/Target/AArch64/GISel/AArch64InstructionSelector.cpp' l='5674' u='r' c='_ZL19getShiftTypeForInstRN4llvm12MachineInstrE'/>
<use f='llvm/llvm/lib/Target/AArch64/MCTargetDesc/AArch64InstPrinter.cpp' l='983' u='r' c='_ZN4llvm18AArch64InstPrinter12printShifterEPKNS_6MCInstEjRKNS_15MCSubtargetInfoERNS_11raw_ostreamE'/>
