<dec f='llvm/build/lib/Target/Lanai/LanaiGenRegisterInfo.inc' l='21' type='1'/>
<use f='llvm/build/lib/Target/Lanai/LanaiGenAsmMatcher.inc' l='798' c='_ZL20validateOperandClassRN4llvm18MCParsedAsmOperandEN12_GLOBAL__N_114MatchClassKindE'/>
<use f='llvm/llvm/lib/Target/Lanai/Disassembler/LanaiDisassembler.cpp' l='156'/>
<use f='llvm/llvm/lib/Target/Lanai/LanaiFrameLowering.cpp' l='114' u='r' c='_ZNK4llvm18LanaiFrameLowering12emitPrologueERNS_15MachineFunctionERNS_17MachineBasicBlockE'/>
<use f='llvm/llvm/lib/Target/Lanai/LanaiFrameLowering.cpp' l='122' u='r' c='_ZNK4llvm18LanaiFrameLowering12emitPrologueERNS_15MachineFunctionERNS_17MachineBasicBlockE'/>
<use f='llvm/llvm/lib/Target/Lanai/LanaiFrameLowering.cpp' l='187' u='r' c='_ZNK4llvm18LanaiFrameLowering12emitEpilogueERNS_15MachineFunctionERNS_17MachineBasicBlockE'/>
<use f='llvm/llvm/lib/Target/Lanai/LanaiFrameLowering.cpp' l='191' u='r' c='_ZNK4llvm18LanaiFrameLowering12emitEpilogueERNS_15MachineFunctionERNS_17MachineBasicBlockE'/>
<use f='llvm/llvm/lib/Target/Lanai/LanaiFrameLowering.cpp' l='192' u='r' c='_ZNK4llvm18LanaiFrameLowering12emitEpilogueERNS_15MachineFunctionERNS_17MachineBasicBlockE'/>
<use f='llvm/llvm/lib/Target/Lanai/MCTargetDesc/LanaiBaseInfo.h' l='55' c='_ZN4llvmL25getLanaiRegisterNumberingEj'/>
<use f='llvm/llvm/lib/Target/Lanai/LanaiISelLowering.cpp' l='222' u='r' c='_ZNK4llvm19LanaiTargetLowering17getRegisterByNameEPKcNS_3LLTERKNS_15MachineFunctionE'/>
<use f='llvm/llvm/lib/Target/Lanai/LanaiISelLowering.cpp' l='1082' u='r' c='_ZNK4llvm19LanaiTargetLowering14LowerFRAMEADDRENS_7SDValueERNS_12SelectionDAGE'/>
<use f='llvm/llvm/lib/Target/Lanai/LanaiRegisterInfo.cpp' l='51' u='r' c='_ZNK4llvm17LanaiRegisterInfo15getReservedRegsERKNS_15MachineFunctionE'/>
<use f='llvm/llvm/lib/Target/Lanai/LanaiRegisterInfo.cpp' l='258' u='r' c='_ZNK4llvm17LanaiRegisterInfo16getFrameRegisterERKNS_15MachineFunctionE'/>
