<dec f='llvm/llvm/include/llvm/Analysis/GlobalsModRef.h' l='64' type='std::list&lt;DeletionCallbackHandle&gt;::iterator'/>
<offset>320</offset>
<use f='llvm/llvm/lib/Analysis/GlobalsModRef.cpp' l='242' u='r' c='_ZN4llvm15GlobalsAAResult22DeletionCallbackHandle7deletedEv'/>
<use f='llvm/llvm/lib/Analysis/GlobalsModRef.cpp' l='298' u='w' c='_ZN4llvm15GlobalsAAResult14AnalyzeGlobalsERNS_6ModuleE'/>
<use f='llvm/llvm/lib/Analysis/GlobalsModRef.cpp' l='312' u='w' c='_ZN4llvm15GlobalsAAResult14AnalyzeGlobalsERNS_6ModuleE'/>
<use f='llvm/llvm/lib/Analysis/GlobalsModRef.cpp' l='317' u='w' c='_ZN4llvm15GlobalsAAResult14AnalyzeGlobalsERNS_6ModuleE'/>
<use f='llvm/llvm/lib/Analysis/GlobalsModRef.cpp' l='326' u='w' c='_ZN4llvm15GlobalsAAResult14AnalyzeGlobalsERNS_6ModuleE'/>
<use f='llvm/llvm/lib/Analysis/GlobalsModRef.cpp' l='463' u='w' c='_ZN4llvm15GlobalsAAResult27AnalyzeIndirectGlobalMemoryEPNS_14GlobalVariableE'/>
<use f='llvm/llvm/lib/Analysis/GlobalsModRef.cpp' l='468' u='w' c='_ZN4llvm15GlobalsAAResult27AnalyzeIndirectGlobalMemoryEPNS_14GlobalVariableE'/>
<use f='llvm/llvm/lib/Analysis/GlobalsModRef.cpp' l='511' u='w' c='_ZN4llvm15GlobalsAAResult16AnalyzeCallGraphERNS_9CallGraphERNS_6ModuleE'/>
