<use f='llvm/llvm/lib/Target/AMDGPU/AMDGPU.h' l='130' u='w' c='_ZN4llvm34AMDGPUPropagateAttributesEarlyPassC1ERNS_13TargetMachineE'/>
<dec f='llvm/llvm/lib/Target/AMDGPU/AMDGPU.h' l='134' type='llvm::TargetMachine &amp;'/>
<offset>0</offset>
<use f='llvm/llvm/lib/Target/AMDGPU/AMDGPUPropagateAttributes.cpp' l='416' u='a' c='_ZN4llvm34AMDGPUPropagateAttributesEarlyPass3runERNS_8FunctionERNS_15AnalysisManagerIS1_JEEE'/>
