<dec f='llvm/llvm/include/llvm/ExecutionEngine/ExecutionEngine.h' l='537' type='std::unique_ptr&lt;Module&gt;'/>
<offset>0</offset>
<use f='llvm/llvm/lib/ExecutionEngine/ExecutionEngine.cpp' l='473' u='w' c='_ZN4llvm13EngineBuilderC1ESt10unique_ptrINS_6ModuleESt14default_deleteIS2_EE'/>
<use f='llvm/llvm/lib/ExecutionEngine/ExecutionEngine.cpp' l='538' u='a' c='_ZN4llvm13EngineBuilder6createEPNS_13TargetMachineE'/>
<use f='llvm/llvm/lib/ExecutionEngine/ExecutionEngine.cpp' l='551' u='a' c='_ZN4llvm13EngineBuilder6createEPNS_13TargetMachineE'/>
<use f='llvm/llvm/lib/ExecutionEngine/TargetSelect.cpp' l='31' u='m' c='_ZN4llvm13EngineBuilder12selectTargetEv'/>
<use f='llvm/llvm/lib/ExecutionEngine/TargetSelect.cpp' l='32' u='m' c='_ZN4llvm13EngineBuilder12selectTargetEv'/>
