<dec f='llvm/llvm/include/llvm/Support/SuffixTree.h' l='244' type='llvm::SuffixTree::RepeatedSubstring'/>
<use f='llvm/llvm/include/llvm/Support/SuffixTree.h' l='259' u='w' c='_ZN4llvm10SuffixTree25RepeatedSubstringIterator7advanceEv'/>
<use f='llvm/llvm/include/llvm/Support/SuffixTree.h' l='298' u='m' c='_ZN4llvm10SuffixTree25RepeatedSubstringIterator7advanceEv'/>
<use f='llvm/llvm/include/llvm/Support/SuffixTree.h' l='300' u='m' c='_ZN4llvm10SuffixTree25RepeatedSubstringIterator7advanceEv'/>
<use f='llvm/llvm/include/llvm/Support/SuffixTree.h' l='312' u='a' c='_ZN4llvm10SuffixTree25RepeatedSubstringIteratordeEv'/>
<offset>64</offset>
<doc f='llvm/llvm/include/llvm/Support/SuffixTree.h' l='243'>/// The repeated substring associated with this node.</doc>
