<dec f='llvm/llvm/include/llvm/Analysis/ProfileSummaryInfo.h' l='219' type='llvm::raw_ostream &amp;'/>
<use f='llvm/llvm/include/llvm/Analysis/ProfileSummaryInfo.h' l='222' u='w' c='_ZN4llvm25ProfileSummaryPrinterPassC1ERNS_11raw_ostreamE'/>
<offset>0</offset>
<use f='llvm/llvm/lib/Analysis/ProfileSummaryInfo.cpp' l='449' u='m' c='_ZN4llvm25ProfileSummaryPrinterPass3runERNS_6ModuleERNS_15AnalysisManagerIS1_JEEE'/>
<use f='llvm/llvm/lib/Analysis/ProfileSummaryInfo.cpp' l='451' u='m' c='_ZN4llvm25ProfileSummaryPrinterPass3runERNS_6ModuleERNS_15AnalysisManagerIS1_JEEE'/>
<use f='llvm/llvm/lib/Analysis/ProfileSummaryInfo.cpp' l='453' u='m' c='_ZN4llvm25ProfileSummaryPrinterPass3runERNS_6ModuleERNS_15AnalysisManagerIS1_JEEE'/>
<use f='llvm/llvm/lib/Analysis/ProfileSummaryInfo.cpp' l='455' u='m' c='_ZN4llvm25ProfileSummaryPrinterPass3runERNS_6ModuleERNS_15AnalysisManagerIS1_JEEE'/>
<use f='llvm/llvm/lib/Analysis/ProfileSummaryInfo.cpp' l='456' u='m' c='_ZN4llvm25ProfileSummaryPrinterPass3runERNS_6ModuleERNS_15AnalysisManagerIS1_JEEE'/>
