<dec f='llvm/llvm/include/llvm/DebugInfo/CodeView/CodeView.h' l='472' type='524288'/>
<use f='llvm/llvm/lib/DebugInfo/CodeView/EnumTables.cpp' l='134'/>
<use f='llvm/llvm/tools/llvm-pdbutil/MinimalSymbolDumper.cpp' l='101' u='r' c='_ZL22formatCompileSym3FlagsB5cxx11jN4llvm8codeview16CompileSym3FlagsE'/>
<use f='llvm/llvm/tools/llvm-pdbutil/MinimalSymbolDumper.cpp' l='101' u='r' c='_ZL22formatCompileSym3FlagsB5cxx11jN4llvm8codeview16CompileSym3FlagsE'/>
