<dec f='llvm/llvm/include/llvm/CodeGen/SelectionDAGNodes.h' l='1080' type='llvm::DebugLoc'/>
<use f='llvm/llvm/include/llvm/CodeGen/SelectionDAGNodes.h' l='1085' u='w' c='_ZN4llvm5SDLocC1EPKNS_6SDNodeE'/>
<use f='llvm/llvm/include/llvm/CodeGen/SelectionDAGNodes.h' l='1090' u='w' c='_ZN4llvm5SDLocC1EPKNS_11InstructionEi'/>
<use f='llvm/llvm/include/llvm/CodeGen/SelectionDAGNodes.h' l='1094' u='a' c='_ZNK4llvm5SDLoc11getDebugLocEv'/>
<offset>0</offset>
