<dec f='llvm/llvm/include/llvm/Object/MachOUniversalWriter.h' l='28' type='const llvm::object::Binary *'/>
<use f='llvm/llvm/include/llvm/Object/MachOUniversalWriter.h' l='59' u='r' c='_ZNK4llvm6object5Slice9getBinaryEv'/>
<use f='llvm/llvm/lib/Object/MachOUniversalWriter.cpp' l='80' u='w' c='_ZN4llvm6object5SliceC1ERKNS0_7ArchiveEjjNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEj'/>
<use f='llvm/llvm/lib/Object/MachOUniversalWriter.cpp' l='84' u='w' c='_ZN4llvm6object5SliceC1ERKNS0_15MachOObjectFileEj'/>
<use f='llvm/llvm/lib/Object/MachOUniversalWriter.cpp' l='91' u='w' c='_ZN4llvm6object5SliceC1ERKNS0_12IRObjectFileEjjNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEj'/>
<use f='llvm/llvm/lib/Object/MachOUniversalWriter.cpp' l='210' u='w' c='_ZN4llvm6object5Slice6createERKNS0_7ArchiveEPNS_11LLVMContextE'/>
<use f='llvm/llvm/lib/Object/MachOUniversalWriter.cpp' l='219' u='w' c='_ZN4llvm6object5Slice6createERKNS0_7ArchiveEPNS_11LLVMContextE'/>
<offset>0</offset>
