<dec f='llvm/llvm/include/llvm/CodeGen/TargetInstrInfo.h' l='633' type='llvm::MachineOperand'/>
<offset>64</offset>
<use f='llvm/llvm/lib/CodeGen/ImplicitNullChecks.cpp' l='572' u='m' c='_ZN12_GLOBAL__N_118ImplicitNullChecks25analyzeBlockForNullChecksERN4llvm17MachineBasicBlockERNS1_15SmallVectorImplINS0_9NullCheckEEE'/>
<use f='llvm/llvm/lib/CodeGen/ImplicitNullChecks.cpp' l='597' u='m' c='_ZN12_GLOBAL__N_118ImplicitNullChecks25analyzeBlockForNullChecksERN4llvm17MachineBasicBlockERNS1_15SmallVectorImplINS0_9NullCheckEEE'/>
<use f='llvm/llvm/lib/CodeGen/MachineSink.cpp' l='919' u='m' c='_ZL32SinkingPreventsImplicitNullCheckRN4llvm12MachineInstrEPKNS_15TargetInstrInfoEPKNS_18TargetRegisterInfoE'/>
<use f='llvm/llvm/lib/CodeGen/MachineSink.cpp' l='922' u='m' c='_ZL32SinkingPreventsImplicitNullCheckRN4llvm12MachineInstrEPKNS_15TargetInstrInfoEPKNS_18TargetRegisterInfoE'/>
<use f='llvm/llvm/lib/Target/AArch64/AArch64InstrInfo.cpp' l='399' u='w' c='_ZNK4llvm16AArch64InstrInfo22analyzeBranchPredicateERNS_17MachineBasicBlockERNS_15TargetInstrInfo22MachineBranchPredicateEb'/>
<use f='llvm/llvm/lib/Target/X86/X86InstrInfo.cpp' l='3212' u='w' c='_ZNK4llvm12X86InstrInfo22analyzeBranchPredicateERNS_17MachineBasicBlockERNS_15TargetInstrInfo22MachineBranchPredicateEb'/>
