<dec f='llvm/llvm/lib/Target/ARM/Utils/ARMBaseInfo.h' l='106' type='8'/>
<use f='llvm/llvm/lib/Target/ARM/MVEVPTBlockPass.cpp' l='138' u='r' c='_ZL19GetInitialBlockMaskj'/>
<use f='llvm/llvm/lib/Target/ARM/Thumb2InstrInfo.cpp' l='805' u='r' c='_ZN4llvm21recomputeVPTBlockMaskERNS_12MachineInstrE'/>
<use f='llvm/llvm/lib/Target/ARM/Utils/ARMBaseInfo.cpp' l='30' c='_ZN4llvm19expandPredBlockMaskENS_3ARM13PredBlockMaskENS_6ARMVCC8VPTCodesE'/>
