<dec f='llvm/llvm/include/llvm/Support/Parallel.h' l='63' type='llvm::parallel::detail::Latch'/>
<use f='llvm/llvm/include/llvm/Support/Parallel.h' l='72' u='m' c='_ZNK4llvm8parallel6detail9TaskGroup4syncEv'/>
<offset>0</offset>
<use f='llvm/llvm/lib/Support/Parallel.cpp' l='158' u='m' c='_ZN4llvm8parallel6detail9TaskGroup5spawnESt8functionIFvvEE'/>
<use f='llvm/llvm/lib/Support/Parallel.cpp' l='161' u='m' c='_ZN4llvm8parallel6detail9TaskGroup5spawnESt8functionIFvvEE'/>
