<dec f='llvm/llvm/include/llvm/IR/Dominators.h' l='264' type='llvm::raw_ostream &amp;'/>
<offset>0</offset>
<use f='llvm/llvm/lib/IR/Dominators.cpp' l='361' u='w' c='_ZN4llvm24DominatorTreePrinterPassC1ERNS_11raw_ostreamE'/>
<use f='llvm/llvm/lib/IR/Dominators.cpp' l='365' u='m' c='_ZN4llvm24DominatorTreePrinterPass3runERNS_8FunctionERNS_15AnalysisManagerIS1_JEEE'/>
<use f='llvm/llvm/lib/IR/Dominators.cpp' l='366' u='a' c='_ZN4llvm24DominatorTreePrinterPass3runERNS_8FunctionERNS_15AnalysisManagerIS1_JEEE'/>
