<dec f='llvm/llvm/include/llvm/ExecutionEngine/Orc/ExecutionUtils.h' l='293' type='llvm::orc::ObjectLayer &amp;'/>
<offset>64</offset>
<use f='llvm/llvm/lib/ExecutionEngine/Orc/ExecutionUtils.cpp' l='374' u='m' c='_ZN4llvm3orc32StaticLibraryDefinitionGenerator13tryToGenerateERNS0_11LookupStateENS0_10LookupKindERNS0_8JITDylibENS0_19JITDylibLookupFlagsERKNS0_15SymbolLookupSetE'/>
<use f='llvm/llvm/lib/ExecutionEngine/Orc/ExecutionUtils.cpp' l='383' u='w' c='_ZN4llvm3orc32StaticLibraryDefinitionGeneratorC1ERNS0_11ObjectLayerESt10unique_ptrINS_12MemoryBufferESt14default_deleteIS5_EERNS_5ErrorE'/>
