<dec f='llvm/llvm/include/llvm/IR/PseudoProbe.h' l='78' type='float'/>
<offset>96</offset>
<use f='llvm/llvm/lib/IR/PseudoProbe.cpp' l='38' u='w' c='_ZN4llvm29extractProbeFromDiscriminatorERKNS_11InstructionE'/>
<use f='llvm/llvm/lib/IR/PseudoProbe.cpp' l='53' u='w' c='_ZN4llvm12extractProbeERKNS_11InstructionE'/>
<use f='llvm/llvm/lib/Transforms/IPO/SampleProfile.cpp' l='910' u='r' c='_ZN12_GLOBAL__N_119SampleProfileLoader14getProbeWeightERKN4llvm11InstructionE'/>
<use f='llvm/llvm/lib/Transforms/IPO/SampleProfile.cpp' l='919' u='r' c='_ZN12_GLOBAL__N_119SampleProfileLoader14getProbeWeightERKN4llvm11InstructionE'/>
<use f='llvm/llvm/lib/Transforms/IPO/SampleProfile.cpp' l='1402' u='r' c='_ZN12_GLOBAL__N_119SampleProfileLoader18tryInlineCandidateERNS_15InlineCandidateEPN4llvm11SmallVectorIPNS3_8CallBaseELj8EEE'/>
<use f='llvm/llvm/lib/Transforms/IPO/SampleProfile.cpp' l='1427' u='r' c='_ZN12_GLOBAL__N_119SampleProfileLoader18getInlineCandidateEPNS_15InlineCandidateEPN4llvm8CallBaseE'/>
<use f='llvm/llvm/lib/Transforms/IPO/SampleProfile.cpp' l='2042' u='r' c='_ZN12_GLOBAL__N_119SampleProfileLoader16propagateWeightsERN4llvm8FunctionE'/>
<use f='llvm/llvm/lib/Transforms/IPO/SampleProfile.cpp' l='2043' u='r' c='_ZN12_GLOBAL__N_119SampleProfileLoader16propagateWeightsERN4llvm8FunctionE'/>
<use f='llvm/llvm/lib/Transforms/IPO/SampleProfileProbe.cpp' l='121' u='r' c='_ZN4llvm19PseudoProbeVerifier19collectProbeFactorsEPKNS_10BasicBlockERSt13unordered_mapImfSt4hashImESt8equal_toImESaISt4pairIKmfEEE'/>
