<use f='llvm/llvm/include/llvm/Frontend/OpenMP/OMPIRBuilder.h' l='142' u='w' c='_ZN4llvm15OpenMPIRBuilder19LocationDescriptionC1ERKNS_9IRBuilderIT_T0_EE'/>
<use f='llvm/llvm/include/llvm/Frontend/OpenMP/OMPIRBuilder.h' l='145' u='w' c='_ZN4llvm15OpenMPIRBuilder19LocationDescriptionC1ERKNS_13IRBuilderBase11InsertPointERKNS_8DebugLocE'/>
<dec f='llvm/llvm/include/llvm/Frontend/OpenMP/OMPIRBuilder.h' l='147' type='llvm::DebugLoc'/>
<use f='llvm/llvm/include/llvm/Frontend/OpenMP/OMPIRBuilder.h' l='373' u='r' c='_ZN4llvm15OpenMPIRBuilder16updateToLocationERKNS0_19LocationDescriptionE'/>
<offset>128</offset>
<use f='llvm/llvm/lib/Frontend/OpenMP/OMPIRBuilder.cpp' l='290' u='m' c='_ZN4llvm15OpenMPIRBuilder20getOrCreateSrcLocStrERKNS0_19LocationDescriptionE'/>
<use f='llvm/llvm/lib/Frontend/OpenMP/OMPIRBuilder.cpp' l='957' u='r' c='_ZN4llvm15OpenMPIRBuilder19createCanonicalLoopERKNS0_19LocationDescriptionENS_12function_refIFvNS_13IRBuilderBase11InsertPointEPNS_5ValueEEEES8_RKNS_5TwineE'/>
<use f='llvm/llvm/lib/Frontend/OpenMP/OMPIRBuilder.cpp' l='999' u='r' c='_ZN4llvm15OpenMPIRBuilder19createCanonicalLoopERKNS0_19LocationDescriptionENS_12function_refIFvNS_13IRBuilderBase11InsertPointEPNS_5ValueEEEES8_S8_S8_bbS6_RKNS_5TwineE'/>
<use f='llvm/llvm/lib/Frontend/OpenMP/OMPIRBuilder.cpp' l='1159' u='r' c='_ZN4llvm15OpenMPIRBuilder25createStaticWorkshareLoopERKNS0_19LocationDescriptionEPNS_17CanonicalLoopInfoENS_13IRBuilderBase11InsertPointEbPNS_5ValueE'/>
<use f='llvm/llvm/unittests/Frontend/OpenMPIRBuilderTest.cpp' l='1466' u='r' c='_ZN12_GLOBAL__N_145OpenMPIRBuilderTest_TileSingleLoopCounts_Test8TestBodyEv'/>
