<dec f='llvm/llvm/unittests/Analysis/ScalarEvolutionTest.cpp' l='35' type='llvm::Module'/>
<use f='llvm/llvm/unittests/Analysis/ScalarEvolutionTest.cpp' l='43' u='w' c='_ZN4llvm20ScalarEvolutionsTestC1Ev'/>
<use f='llvm/llvm/unittests/Analysis/ScalarEvolutionTest.cpp' l='76' u='a' c='_ZN4llvm41ScalarEvolutionsTest_SCEVUnknownRAUW_Test8TestBodyEv'/>
<use f='llvm/llvm/unittests/Analysis/ScalarEvolutionTest.cpp' l='82' u='a' c='_ZN4llvm41ScalarEvolutionsTest_SCEVUnknownRAUW_Test8TestBodyEv'/>
<use f='llvm/llvm/unittests/Analysis/ScalarEvolutionTest.cpp' l='83' u='a' c='_ZN4llvm41ScalarEvolutionsTest_SCEVUnknownRAUW_Test8TestBodyEv'/>
<use f='llvm/llvm/unittests/Analysis/ScalarEvolutionTest.cpp' l='84' u='a' c='_ZN4llvm41ScalarEvolutionsTest_SCEVUnknownRAUW_Test8TestBodyEv'/>
<use f='llvm/llvm/unittests/Analysis/ScalarEvolutionTest.cpp' l='125' u='a' c='_ZN4llvm39ScalarEvolutionsTest_SimplifiedPHI_Test8TestBodyEv'/>
<use f='llvm/llvm/unittests/Analysis/ScalarEvolutionTest.cpp' l='283' u='a' c='_ZN4llvm47ScalarEvolutionsTest_CompareSCEVComplexity_Test8TestBodyEv'/>
<use f='llvm/llvm/unittests/Analysis/ScalarEvolutionTest.cpp' l='348' u='m' c='_ZN4llvm48ScalarEvolutionsTest_CompareValueComplexity_Test8TestBodyEv'/>
<use f='llvm/llvm/unittests/Analysis/ScalarEvolutionTest.cpp' l='353' u='a' c='_ZN4llvm48ScalarEvolutionsTest_CompareValueComplexity_Test8TestBodyEv'/>
<use f='llvm/llvm/unittests/Analysis/ScalarEvolutionTest.cpp' l='391' u='a' c='_ZN4llvm37ScalarEvolutionsTest_SCEVAddExpr_Test8TestBodyEv'/>
<use f='llvm/llvm/unittests/Analysis/ScalarEvolutionTest.cpp' l='625' u='a' c='_ZN4llvm44ScalarEvolutionsTest_SCEVZeroExtendExpr_Test8TestBodyEv'/>
<use f='llvm/llvm/unittests/Analysis/ScalarEvolutionTest.cpp' l='690' u='m' c='_ZN4llvm49ScalarEvolutionsTest_SCEVExitLimitForgetLoop_Test8TestBodyEv'/>
<use f='llvm/llvm/unittests/Analysis/ScalarEvolutionTest.cpp' l='788' u='m' c='_ZN4llvm50ScalarEvolutionsTest_SCEVExitLimitForgetValue_Test8TestBodyEv'/>
<use f='llvm/llvm/unittests/Analysis/ScalarEvolutionTest.cpp' l='860' u='a' c='_ZN4llvm61ScalarEvolutionsTest_SCEVAddRecFromPHIwithLargeConstants_Test8TestBodyEv'/>
<use f='llvm/llvm/unittests/Analysis/ScalarEvolutionTest.cpp' l='917' u='a' c='_ZN4llvm65ScalarEvolutionsTest_SCEVAddRecFromPHIwithLargeConstantAccum_Test8TestBodyEv'/>
<use f='llvm/llvm/unittests/Analysis/ScalarEvolutionTest.cpp' l='971' u='a' c='_ZN4llvm45ScalarEvolutionsTest_SCEVFoldSumOfTruncs_Test8TestBodyEv'/>
<offset>192</offset>
