<use f='llvm/llvm/lib/Target/AMDGPU/AMDGPU.h' l='246' u='w' c='_ZN4llvm31AMDGPUPromoteAllocaToVectorPassC1ERNS_13TargetMachineE'/>
<dec f='llvm/llvm/lib/Target/AMDGPU/AMDGPU.h' l='250' type='llvm::TargetMachine &amp;'/>
<offset>0</offset>
<use f='llvm/llvm/lib/Target/AMDGPU/AMDGPUPromoteAlloca.cpp' l='1112' u='a' c='_ZN4llvm31AMDGPUPromoteAllocaToVectorPass3runERNS_8FunctionERNS_15AnalysisManagerIS1_JEEE'/>
