<dec f='llvm/llvm/lib/Target/NVPTX/NVPTX.h' l='150' type='0'/>
<use f='llvm/llvm/lib/Target/NVPTX/MCTargetDesc/NVPTXInstPrinter.cpp' l='161' c='_ZN4llvm16NVPTXInstPrinter12printCmpModeEPKNS_6MCInstEiRNS_11raw_ostreamEPKc'/>
<use f='llvm/llvm/lib/Target/NVPTX/NVPTXISelDAGToDAG.cpp' l='544' u='r' c='_ZL13getPTXCmpModeRKN4llvm14CondCodeSDNodeEb'/>
<use f='llvm/llvm/lib/Target/NVPTX/NVPTXISelDAGToDAG.cpp' l='572' u='r' c='_ZL13getPTXCmpModeRKN4llvm14CondCodeSDNodeEb'/>
