<dec f='llvm/build/lib/Target/ARM/ARMGenInstrInfo.inc' l='1758' type='1743'/>
<use f='llvm/build/lib/Target/ARM/ARMGenFastISel.inc' l='5234' u='r' c='_ZN12_GLOBAL__N_111ARMFastISel31fastEmit_ISD_SSUBSAT_MVT_i32_rrEN4llvm3MVTEjbjb'/>
<use f='llvm/build/lib/Target/ARM/ARMGenDAGISel.inc' l='16324' u='r' c='_ZN12_GLOBAL__N_115ARMDAGToDAGISel10SelectCodeEPN4llvm6SDNodeE'/>
<use f='llvm/build/lib/Target/ARM/ARMGenDAGISel.inc' l='16324' u='r' c='_ZN12_GLOBAL__N_115ARMDAGToDAGISel10SelectCodeEPN4llvm6SDNodeE'/>
<use f='llvm/build/lib/Target/ARM/ARMGenDAGISel.inc' l='57805' u='r' c='_ZN12_GLOBAL__N_115ARMDAGToDAGISel10SelectCodeEPN4llvm6SDNodeE'/>
<use f='llvm/build/lib/Target/ARM/ARMGenDAGISel.inc' l='57805' u='r' c='_ZN12_GLOBAL__N_115ARMDAGToDAGISel10SelectCodeEPN4llvm6SDNodeE'/>
<use f='llvm/build/lib/Target/ARM/ARMGenGlobalISel.inc' l='17224' u='r' c='_ZNK12_GLOBAL__N_122ARMInstructionSelector13getMatchTableEv'/>
<use f='llvm/build/lib/Target/ARM/ARMGenGlobalISel.inc' l='38853' u='r' c='_ZNK12_GLOBAL__N_122ARMInstructionSelector13getMatchTableEv'/>
<use f='llvm/build/lib/Target/ARM/ARMGenAsmMatcher.inc' l='11342'/>
<use f='llvm/build/lib/Target/ARM/ARMGenMCCodeEmitter.inc' l='14648' c='_ZNK12_GLOBAL__N_116ARMMCCodeEmitter21getBinaryCodeForInstrERKN4llvm6MCInstERNS1_15SmallVectorImplINS1_7MCFixupEEERKNS1_15MCSubtargetInfoE'/>
