<use f='llvm/llvm/lib/ExecutionEngine/JITLink/JITLinkGeneric.h' l='37' u='w' c='_ZN4llvm7jitlink13JITLinkerBaseC1ESt10unique_ptrINS0_14JITLinkContextESt14default_deleteIS3_EES2_INS0_9LinkGraphES4_IS7_EENS0_17PassConfigurationE'/>
<dec f='llvm/llvm/lib/ExecutionEngine/JITLink/JITLinkGeneric.h' l='112' type='std::unique_ptr&lt;LinkGraph&gt;'/>
<offset>128</offset>
<use f='llvm/llvm/lib/ExecutionEngine/JITLink/JITLinkGeneric.cpp' l='40' u='m' c='_ZN4llvm7jitlink13JITLinkerBase10linkPhase1ESt10unique_ptrIS1_St14default_deleteIS1_EE'/>
<use f='llvm/llvm/lib/ExecutionEngine/JITLink/JITLinkGeneric.cpp' l='72' u='m' c='_ZN4llvm7jitlink13JITLinkerBase10linkPhase1ESt10unique_ptrIS1_St14default_deleteIS1_EE'/>
<use f='llvm/llvm/lib/ExecutionEngine/JITLink/JITLinkGeneric.cpp' l='136' u='m' c='_ZN4llvm7jitlink13JITLinkerBase10linkPhase2ESt10unique_ptrIS1_St14default_deleteIS1_EENS_8ExpectedINS_8DenseMapINS_9StringRefENS_18JITEvaluatedSymbolE4378600'/>
<use f='llvm/llvm/lib/ExecutionEngine/JITLink/JITLinkGeneric.cpp' l='172' u='m' c='_ZN4llvm7jitlink13JITLinkerBase9runPassesERSt6vectorISt8functionIFNS_5ErrorERNS0_9LinkGraphEEESaIS8_EE'/>
<use f='llvm/llvm/lib/ExecutionEngine/JITLink/JITLinkGeneric.cpp' l='182' u='m' c='_ZN4llvm7jitlink13JITLinkerBase12layOutBlocksEv'/>
<use f='llvm/llvm/lib/ExecutionEngine/JITLink/JITLinkGeneric.cpp' l='305' u='m' c='_ZNK4llvm7jitlink13JITLinkerBase22getExternalSymbolNamesEv'/>
<use f='llvm/llvm/lib/ExecutionEngine/JITLink/JITLinkGeneric.cpp' l='320' u='m' c='_ZN4llvm7jitlink13JITLinkerBase17applyLookupResultENS_8DenseMapINS_9StringRefENS_18JITEvaluatedSymbolENS_12DenseMapInfoIS3_EENS_6detail12DenseMapPairIS3_S4_EEEE'/>
<use f='llvm/llvm/lib/ExecutionEngine/JITLink/JITLinkGeneric.cpp' l='420' u='m' c='_ZN4llvm7jitlink13JITLinkerBase9dumpGraphERNS_11raw_ostreamE'/>
