<dec f='llvm/llvm/include/llvm/IR/PatternMatch.h' l='202' type='const llvm::APFloat *&amp;'/>
<use f='llvm/llvm/include/llvm/IR/PatternMatch.h' l='206' u='w' c='_ZN4llvm12PatternMatch13apfloat_matchC1ERPKNS_7APFloatEb'/>
<use f='llvm/llvm/include/llvm/IR/PatternMatch.h' l='210' u='w' c='_ZN4llvm12PatternMatch13apfloat_match5matchEPT_'/>
<use f='llvm/llvm/include/llvm/IR/PatternMatch.h' l='217' u='w' c='_ZN4llvm12PatternMatch13apfloat_match5matchEPT_'/>
<offset>0</offset>
