<dec f='llvm/llvm/include/llvm/LTO/legacy/LTOModule.h' l='51' type='std::unique_ptr&lt;Module&gt;'/>
<use f='llvm/llvm/include/llvm/LTO/legacy/LTOModule.h' l='115' u='m' c='_ZNK4llvm9LTOModule9getModuleEv'/>
<use f='llvm/llvm/include/llvm/LTO/legacy/LTOModule.h' l='116' u='m' c='_ZN4llvm9LTOModule9getModuleEv'/>
<use f='llvm/llvm/include/llvm/LTO/legacy/LTOModule.h' l='118' u='a' c='_ZN4llvm9LTOModule10takeModuleEv'/>
<offset>320</offset>
<use f='llvm/llvm/lib/LTO/LTOModule.cpp' l='48' u='w' c='_ZN4llvm9LTOModuleC1ESt10unique_ptrINS_6ModuleESt14default_deleteIS2_EENS_15MemoryBufferRefEPNS_13TargetMachineE'/>
<use f='llvm/llvm/lib/LTO/LTOModule.cpp' l='50' u='m' c='_ZN4llvm9LTOModuleC1ESt10unique_ptrINS_6ModuleESt14default_deleteIS2_EENS_15MemoryBufferRefEPNS_13TargetMachineE'/>
<use f='llvm/llvm/lib/LTO/LTOModule.cpp' l='684' u='m' c='_ZNK4llvm9LTOModule15getMachOCPUTypeEv'/>
<use f='llvm/llvm/lib/LTO/LTOModule.cpp' l='688' u='m' c='_ZNK4llvm9LTOModule18getMachOCPUSubTypeEv'/>
