<dec f='llvm/llvm/tools/llvm-readobj/Win64EHDumper.h' l='25' type='llvm::raw_ostream &amp;'/>
<use f='llvm/llvm/tools/llvm-readobj/Win64EHDumper.h' l='55' u='w' c='_ZN4llvm7Win64EH6DumperC1ERNS_13ScopedPrinterE'/>
<offset>64</offset>
<use f='llvm/llvm/tools/llvm-readobj/Win64EHDumper.cpp' l='226' u='m' c='_ZN4llvm7Win64EH6Dumper15printUnwindCodeERKNS0_10UnwindInfoENS_8ArrayRefINS0_10UnwindCodeEEE'/>
<use f='llvm/llvm/tools/llvm-readobj/Win64EHDumper.cpp' l='230' u='m' c='_ZN4llvm7Win64EH6Dumper15printUnwindCodeERKNS0_10UnwindInfoENS_8ArrayRefINS0_10UnwindCodeEEE'/>
<use f='llvm/llvm/tools/llvm-readobj/Win64EHDumper.cpp' l='236' u='m' c='_ZN4llvm7Win64EH6Dumper15printUnwindCodeERKNS0_10UnwindInfoENS_8ArrayRefINS0_10UnwindCodeEEE'/>
<use f='llvm/llvm/tools/llvm-readobj/Win64EHDumper.cpp' l='241' u='m' c='_ZN4llvm7Win64EH6Dumper15printUnwindCodeERKNS0_10UnwindInfoENS_8ArrayRefINS0_10UnwindCodeEEE'/>
<use f='llvm/llvm/tools/llvm-readobj/Win64EHDumper.cpp' l='243' u='m' c='_ZN4llvm7Win64EH6Dumper15printUnwindCodeERKNS0_10UnwindInfoENS_8ArrayRefINS0_10UnwindCodeEEE'/>
<use f='llvm/llvm/tools/llvm-readobj/Win64EHDumper.cpp' l='248' u='m' c='_ZN4llvm7Win64EH6Dumper15printUnwindCodeERKNS0_10UnwindInfoENS_8ArrayRefINS0_10UnwindCodeEEE'/>
<use f='llvm/llvm/tools/llvm-readobj/Win64EHDumper.cpp' l='253' u='m' c='_ZN4llvm7Win64EH6Dumper15printUnwindCodeERKNS0_10UnwindInfoENS_8ArrayRefINS0_10UnwindCodeEEE'/>
<use f='llvm/llvm/tools/llvm-readobj/Win64EHDumper.cpp' l='258' u='m' c='_ZN4llvm7Win64EH6Dumper15printUnwindCodeERKNS0_10UnwindInfoENS_8ArrayRefINS0_10UnwindCodeEEE'/>
<use f='llvm/llvm/tools/llvm-readobj/Win64EHDumper.cpp' l='263' u='m' c='_ZN4llvm7Win64EH6Dumper15printUnwindCodeERKNS0_10UnwindInfoENS_8ArrayRefINS0_10UnwindCodeEEE'/>
<use f='llvm/llvm/tools/llvm-readobj/Win64EHDumper.cpp' l='268' u='m' c='_ZN4llvm7Win64EH6Dumper15printUnwindCodeERKNS0_10UnwindInfoENS_8ArrayRefINS0_10UnwindCodeEEE'/>
<use f='llvm/llvm/tools/llvm-readobj/Win64EHDumper.cpp' l='272' u='m' c='_ZN4llvm7Win64EH6Dumper15printUnwindCodeERKNS0_10UnwindInfoENS_8ArrayRefINS0_10UnwindCodeEEE'/>
