<use f='llvm/llvm/include/llvm/Transforms/Utils/ScalarEvolutionExpander.h' l='46' u='w' c='_ZN4llvm11SCEVOperandC1EjiPKNS_4SCEVE'/>
<dec f='llvm/llvm/include/llvm/Transforms/Utils/ScalarEvolutionExpander.h' l='52' type='const llvm::SCEV *'/>
<offset>64</offset>
<doc f='llvm/llvm/include/llvm/Transforms/Utils/ScalarEvolutionExpander.h' l='51'>/// The SCEV operand to be costed.</doc>
<use f='llvm/llvm/lib/Transforms/Utils/ScalarEvolutionExpander.cpp' l='2187' c='_ZL22costAndCollectOperandsRKN4llvm11SCEVOperandERKNS_19TargetTransformInfoENS3_14TargetCostKindERNS_15SmallVectorImplIS0_EE'/>
<use f='llvm/llvm/lib/Transforms/Utils/ScalarEvolutionExpander.cpp' l='2329' u='r' c='_ZN4llvm12SCEVExpander25isHighCostExpansionHelperERKNS_11SCEVOperandEPNS_4LoopERKNS_11InstructionERiRKNS_19TargetTransformInfoERNS_15SmallPtrSetImplIP205181'/>
