<dec f='llvm/llvm/include/llvm/Analysis/CallGraph.h' l='74' type='llvm::Module &amp;'/>
<use f='llvm/llvm/include/llvm/Analysis/CallGraph.h' l='102' u='a' c='_ZNK4llvm9CallGraph9getModuleEv'/>
<offset>0</offset>
<use f='llvm/llvm/lib/Analysis/CallGraph.cpp' l='34' u='w' c='_ZN4llvm9CallGraphC1ERNS_6ModuleE'/>
<use f='llvm/llvm/lib/Analysis/CallGraph.cpp' l='43' u='w' c='_ZN4llvm9CallGraphC1EOS0_'/>
<use f='llvm/llvm/lib/Analysis/CallGraph.cpp' l='43' u='r' c='_ZN4llvm9CallGraphC1EOS0_'/>
<use f='llvm/llvm/lib/Analysis/CallGraph.cpp' l='166' u='m' c='_ZN4llvm9CallGraph24removeFunctionFromModuleEPNS_13CallGraphNodeE'/>
