<dec f='llvm/llvm/include/llvm/Support/VirtualFileSystem.h' l='596' type='llvm::vfs::Status'/>
<use f='llvm/llvm/include/llvm/Support/VirtualFileSystem.h' l='603' u='w' c='_ZN4llvm3vfs21RedirectingFileSystem25RedirectingDirectoryEntryC1ENS_9StringRefESt6vectorISt10unique_ptrINS1_5EntryESt14default_deleteIS6_EESaIS9_EENS0_6StatusE'/>
<use f='llvm/llvm/include/llvm/Support/VirtualFileSystem.h' l='605' u='w' c='_ZN4llvm3vfs21RedirectingFileSystem25RedirectingDirectoryEntryC1ENS_9StringRefENS0_6StatusE'/>
<use f='llvm/llvm/include/llvm/Support/VirtualFileSystem.h' l='607' u='r' c='_ZN4llvm3vfs21RedirectingFileSystem25RedirectingDirectoryEntry9getStatusEv'/>
<offset>576</offset>
