<dec f='llvm/build/lib/Target/PowerPC/PPCGenInstrInfo.inc' l='1554' type='1539'/>
<use f='llvm/build/lib/Target/PowerPC/PPCGenAsmMatcher.inc' l='6860'/>
<use f='llvm/build/lib/Target/PowerPC/PPCGenMCCodeEmitter.inc' l='2838' c='_ZNK4llvm16PPCMCCodeEmitter21getBinaryCodeForInstrERKNS_6MCInstERNS_15SmallVectorImplINS_7MCFixupEEERKNS_15MCSubtargetInfoE'/>
<use f='llvm/build/lib/Target/PowerPC/PPCGenDAGISel.inc' l='43624' u='r' c='_ZN12_GLOBAL__N_115PPCDAGToDAGISel10SelectCodeEPN4llvm6SDNodeE'/>
<use f='llvm/build/lib/Target/PowerPC/PPCGenDAGISel.inc' l='43624' u='r' c='_ZN12_GLOBAL__N_115PPCDAGToDAGISel10SelectCodeEPN4llvm6SDNodeE'/>
<use f='llvm/build/lib/Target/PowerPC/PPCGenDAGISel.inc' l='44476' u='r' c='_ZN12_GLOBAL__N_115PPCDAGToDAGISel10SelectCodeEPN4llvm6SDNodeE'/>
<use f='llvm/build/lib/Target/PowerPC/PPCGenDAGISel.inc' l='44476' u='r' c='_ZN12_GLOBAL__N_115PPCDAGToDAGISel10SelectCodeEPN4llvm6SDNodeE'/>
<use f='llvm/llvm/lib/Target/PowerPC/PPCInstrInfo.cpp' l='3979' c='_ZNK4llvm12PPCInstrInfo15instrHasImmFormEjbRNS_12ImmInstrInfoEb'/>
<use f='llvm/llvm/lib/Target/PowerPC/PPCInstrInfo.cpp' l='4009' c='_ZNK4llvm12PPCInstrInfo15instrHasImmFormEjbRNS_12ImmInstrInfoEb'/>
<use f='llvm/llvm/lib/Target/PowerPC/PPCInstrInfo.cpp' l='4950' u='r' c='_ZNK4llvm12PPCInstrInfo25transformToImmFormFedByLIERNS_12MachineInstrERKNS_12ImmInstrInfoEjS2_'/>
