<dec f='llvm/build/lib/Target/RISCV/RISCVGenRegisterInfo.inc' l='67' type='47'/>
<use f='llvm/build/lib/Target/RISCV/RISCVGenAsmMatcher.inc' l='2379' c='_ZL20validateOperandClassRN4llvm18MCParsedAsmOperandEN12_GLOBAL__N_114MatchClassKindE'/>
<use f='llvm/llvm/lib/Target/RISCV/RISCVFrameLowering.cpp' l='651' u='r' c='_ZNK4llvm18RISCVFrameLowering20determineCalleeSavesERNS_15MachineFunctionERNS_9BitVectorEPNS_12RegScavengerE'/>
<use f='llvm/llvm/lib/Target/RISCV/RISCVISelLowering.cpp' l='2836'/>
<use f='llvm/llvm/lib/Target/RISCV/RISCVISelLowering.cpp' l='3315' u='r' c='_ZL15CC_RISCV_FastCCjN4llvm3MVTES0_NS_11CCValAssign7LocInfoENS_3ISD10ArgFlagsTyERNS_7CCStateE'/>
<use f='llvm/llvm/lib/Target/RISCV/RISCVISelLowering.cpp' l='4176' u='r' c='_ZNK4llvm19RISCVTargetLowering28getRegForInlineAsmConstraintEPKNS_18TargetRegisterInfoENS_9StringRefENS_3MVTE'/>
<use f='llvm/llvm/lib/Target/RISCV/RISCVISelLowering.cpp' l='4491' u='r' c='_ZNK4llvm19RISCVTargetLowering27getExceptionPointerRegisterEPKNS_8ConstantE'/>
