<dec f='llvm/llvm/lib/Target/RISCV/MCTargetDesc/RISCVBaseInfo.h' l='128' type='8'/>
<use f='llvm/llvm/lib/Target/RISCV/AsmParser/RISCVAsmParser.cpp' l='844' u='r' c='_ZNK12_GLOBAL__N_112RISCVOperand19addFenceArgOperandsERN4llvm6MCInstEj'/>
<use f='llvm/llvm/lib/Target/RISCV/MCTargetDesc/RISCVInstPrinter.cpp' l='140' u='r' c='_ZN4llvm16RISCVInstPrinter13printFenceArgEPKNS_6MCInstEjRKNS_15MCSubtargetInfoERNS_11raw_ostreamE'/>
