<dec f='llvm/llvm/include/llvm/Analysis/PtrUseVisitor.h' l='117' type='const llvm::DataLayout &amp;'/>
<use f='llvm/llvm/include/llvm/Analysis/PtrUseVisitor.h' l='162' u='w' c='_ZN4llvm6detail17PtrUseVisitorBaseC1ERKNS_10DataLayoutE'/>
<use f='llvm/llvm/include/llvm/Analysis/PtrUseVisitor.h' l='224' u='m' c='_ZN4llvm13PtrUseVisitor8visitPtrERNS_11InstructionE'/>
<use f='llvm/llvm/lib/Analysis/PtrUseVisitor.cpp' l='37' u='m' c='_ZN4llvm6detail17PtrUseVisitorBase18adjustOffsetForGEPERNS_17GetElementPtrInstE'/>
<use f='llvm/llvm/lib/Analysis/PtrUseVisitor.cpp' l='38' u='r' c='_ZN4llvm6detail17PtrUseVisitorBase18adjustOffsetForGEPERNS_17GetElementPtrInstE'/>
<offset>0</offset>
<use f='llvm/llvm/lib/Transforms/Scalar/SROA.cpp' l='784' u='m' c='_ZN4llvm4sroa12AllocaSlices12SliceBuilder13visitLoadInstERNS_8LoadInstE'/>
<use f='llvm/llvm/lib/Transforms/Scalar/SROA.cpp' l='790' u='m' c='_ZN4llvm4sroa12AllocaSlices12SliceBuilder13visitLoadInstERNS_8LoadInstE'/>
<use f='llvm/llvm/lib/Transforms/Scalar/SROA.cpp' l='802' u='m' c='_ZN4llvm4sroa12AllocaSlices12SliceBuilder14visitStoreInstERNS_9StoreInstE'/>
<use f='llvm/llvm/lib/Transforms/Scalar/SROA.cpp' l='808' u='m' c='_ZN4llvm4sroa12AllocaSlices12SliceBuilder14visitStoreInstERNS_9StoreInstE'/>
<use f='llvm/llvm/lib/Transforms/Scalar/SROA.cpp' l='844' u='m' c='_ZN4llvm4sroa12AllocaSlices12SliceBuilder15visitMemSetInstERNS_10MemSetInstE'/>
<use f='llvm/llvm/lib/Transforms/Scalar/SROA.cpp' l='869' u='m' c='_ZN4llvm4sroa12AllocaSlices12SliceBuilder20visitMemTransferInstERNS_15MemTransferInstE'/>
<use f='llvm/llvm/lib/Transforms/Scalar/SROA.cpp' l='870' u='m' c='_ZN4llvm4sroa12AllocaSlices12SliceBuilder20visitMemTransferInstERNS_15MemTransferInstE'/>
