<dec f='llvm/llvm/include/llvm/IR/PatternMatch.h' l='1912' type='Sum_t'/>
<use f='llvm/llvm/include/llvm/IR/PatternMatch.h' l='1915' u='w' c='_ZN4llvm12PatternMatch22UAddWithOverflow_matchC1ERKT_RKT0_RKT1_'/>
<use f='llvm/llvm/include/llvm/IR/PatternMatch.h' l='1929' u='c' c='_ZN4llvm12PatternMatch22UAddWithOverflow_match5matchEPTL0__'/>
<use f='llvm/llvm/include/llvm/IR/PatternMatch.h' l='1934' u='c' c='_ZN4llvm12PatternMatch22UAddWithOverflow_match5matchEPTL0__'/>
<use f='llvm/llvm/include/llvm/IR/PatternMatch.h' l='1941' u='c' c='_ZN4llvm12PatternMatch22UAddWithOverflow_match5matchEPTL0__'/>
<use f='llvm/llvm/include/llvm/IR/PatternMatch.h' l='1946' u='c' c='_ZN4llvm12PatternMatch22UAddWithOverflow_match5matchEPTL0__'/>
<use f='llvm/llvm/include/llvm/IR/PatternMatch.h' l='1955' u='c' c='_ZN4llvm12PatternMatch22UAddWithOverflow_match5matchEPTL0__'/>
<use f='llvm/llvm/include/llvm/IR/PatternMatch.h' l='1960' u='c' c='_ZN4llvm12PatternMatch22UAddWithOverflow_match5matchEPTL0__'/>
