<dec f='llvm/llvm/lib/Target/NVPTX/NVPTX.h' l='151' type='1'/>
<use f='llvm/llvm/lib/Target/NVPTX/MCTargetDesc/NVPTXInstPrinter.cpp' l='164' c='_ZN4llvm16NVPTXInstPrinter12printCmpModeEPKNS_6MCInstEiRNS_11raw_ostreamEPKc'/>
<use f='llvm/llvm/lib/Target/NVPTX/NVPTXISelDAGToDAG.cpp' l='554' u='r' c='_ZL13getPTXCmpModeRKN4llvm14CondCodeSDNodeEb'/>
<use f='llvm/llvm/lib/Target/NVPTX/NVPTXISelDAGToDAG.cpp' l='582' u='r' c='_ZL13getPTXCmpModeRKN4llvm14CondCodeSDNodeEb'/>
