<dec f='llvm/llvm/include/llvm/Analysis/StackSafetyAnalysis.h' l='63' type='llvm::Module *'/>
<offset>0</offset>
<use f='llvm/llvm/lib/Analysis/StackSafetyAnalysis.cpp' l='800' u='r' c='_ZNK4llvm21StackSafetyGlobalInfo7getInfoEv'/>
<use f='llvm/llvm/lib/Analysis/StackSafetyAnalysis.cpp' l='869' u='w' c='_ZN4llvm21StackSafetyGlobalInfoC1EPNS_6ModuleESt8functionIFRKNS_15StackSafetyInfoERNS_8FunctionEEEPKNS_18ModuleSummaryIndexE'/>
