<dec f='llvm/llvm/lib/Target/ARM/ARMHazardRecognizer.h' l='50' type='const llvm::DataLayout &amp;'/>
<offset>832</offset>
<use f='llvm/llvm/lib/Target/ARM/ARMHazardRecognizer.cpp' l='167' u='w' c='_ZN4llvm31ARMBankConflictHazardRecognizerC1EPKNS_11ScheduleDAGElb'/>
<use f='llvm/llvm/lib/Target/ARM/ARMHazardRecognizer.cpp' l='208' u='r' c='_ZN4llvm31ARMBankConflictHazardRecognizer13getHazardTypeEPNS_5SUnitEi'/>
<use f='llvm/llvm/lib/Target/ARM/ARMHazardRecognizer.cpp' l='209' u='r' c='_ZN4llvm31ARMBankConflictHazardRecognizer13getHazardTypeEPNS_5SUnitEi'/>
