<dec f='llvm/llvm/include/llvm/Transforms/IPO/Attributor.h' l='3790' type='1'/>
<use f='llvm/llvm/include/llvm/Transforms/IPO/Attributor.h' l='3792' u='r'/>
<use f='llvm/llvm/lib/Passes/PassBuilder.cpp' l='1081' u='r' c='_ZN4llvm11PassBuilder33buildModuleSimplificationPipelineENS0_17OptimizationLevelENS_18ThinOrFullLTOPhaseE'/>
<use f='llvm/llvm/lib/Transforms/IPO/PassManagerBuilder.cpp' l='173' u='a'/>
<use f='llvm/llvm/lib/Transforms/IPO/PassManagerBuilder.cpp' l='611' u='r' c='_ZN4llvm18PassManagerBuilder25populateModulePassManagerERNS_6legacy15PassManagerBaseE'/>
<use f='llvm/llvm/lib/Transforms/IPO/PassManagerBuilder.cpp' l='965' u='r' c='_ZN4llvm18PassManagerBuilder24addLTOOptimizationPassesERNS_6legacy15PassManagerBaseE'/>
