<dec f='llvm/llvm/lib/Target/SystemZ/SystemZTargetTransformInfo.h' l='23' type='const llvm::SystemZSubtarget *'/>
<use f='llvm/llvm/lib/Target/SystemZ/SystemZTargetTransformInfo.h' l='26' u='r' c='_ZNK4llvm14SystemZTTIImpl5getSTEv'/>
<use f='llvm/llvm/lib/Target/SystemZ/SystemZTargetTransformInfo.h' l='33' u='w' c='_ZN4llvm14SystemZTTIImplC1EPKNS_20SystemZTargetMachineERKNS_8FunctionE'/>
<use f='llvm/llvm/lib/Target/SystemZ/SystemZTargetTransformInfo.h' l='34' u='r' c='_ZN4llvm14SystemZTTIImplC1EPKNS_20SystemZTargetMachineERKNS_8FunctionE'/>
<offset>128</offset>
<use f='llvm/llvm/lib/Target/SystemZ/SystemZTargetTransformInfo.cpp' l='152' u='r' c='_ZN4llvm14SystemZTTIImpl17getIntImmCostInstEjjRKNS_5APIntEPNS_4TypeENS_19TargetTransformInfo14TargetCostKindEPNS_11InstructionE'/>
<use f='llvm/llvm/lib/Target/SystemZ/SystemZTargetTransformInfo.cpp' l='239' u='r' c='_ZN4llvm14SystemZTTIImpl16getPopcntSupportEj'/>
<use f='llvm/llvm/lib/Target/SystemZ/SystemZTargetTransformInfo.cpp' l='321' u='r' c='_ZNK4llvm14SystemZTTIImpl20getNumberOfRegistersEj'/>
<use f='llvm/llvm/lib/Target/SystemZ/SystemZTargetTransformInfo.cpp' l='329' u='r' c='_ZNK4llvm14SystemZTTIImpl19getRegisterBitWidthEb'/>
<use f='llvm/llvm/lib/Target/SystemZ/SystemZTargetTransformInfo.cpp' l='348' u='r' c='_ZNK4llvm14SystemZTTIImpl20getMinPrefetchStrideEjjjb'/>
<use f='llvm/llvm/lib/Target/SystemZ/SystemZTargetTransformInfo.cpp' l='439' u='r' c='_ZN4llvm14SystemZTTIImpl22getArithmeticInstrCostEjPNS_4TypeENS_19TargetTransformInfo14TargetCostKindENS3_16OperandValueKindES5_NS3_22OperandValuePrope11515742'/>
<use f='llvm/llvm/lib/Target/SystemZ/SystemZTargetTransformInfo.cpp' l='464' u='r' c='_ZN4llvm14SystemZTTIImpl22getArithmeticInstrCostEjPNS_4TypeENS_19TargetTransformInfo14TargetCostKindENS3_16OperandValueKindES5_NS3_22OperandValuePrope11515742'/>
<use f='llvm/llvm/lib/Target/SystemZ/SystemZTargetTransformInfo.cpp' l='476' u='r' c='_ZN4llvm14SystemZTTIImpl22getArithmeticInstrCostEjPNS_4TypeENS_19TargetTransformInfo14TargetCostKindENS3_16OperandValueKindES5_NS3_22OperandValuePrope11515742'/>
<use f='llvm/llvm/lib/Target/SystemZ/SystemZTargetTransformInfo.cpp' l='508' u='r' c='_ZN4llvm14SystemZTTIImpl22getArithmeticInstrCostEjPNS_4TypeENS_19TargetTransformInfo14TargetCostKindENS3_16OperandValueKindES5_NS3_22OperandValuePrope11515742'/>
<use f='llvm/llvm/lib/Target/SystemZ/SystemZTargetTransformInfo.cpp' l='546' u='r' c='_ZN4llvm14SystemZTTIImpl14getShuffleCostENS_19TargetTransformInfo11ShuffleKindEPNS_10VectorTypeEiS4_'/>
<use f='llvm/llvm/lib/Target/SystemZ/SystemZTargetTransformInfo.cpp' l='728' u='r' c='_ZN4llvm14SystemZTTIImpl16getCastInstrCostEjPNS_4TypeES2_NS_19TargetTransformInfo15CastContextHintENS3_14TargetCostKindEPKNS_11InstructionE'/>
<use f='llvm/llvm/lib/Target/SystemZ/SystemZTargetTransformInfo.cpp' l='745' u='r' c='_ZN4llvm14SystemZTTIImpl16getCastInstrCostEjPNS_4TypeES2_NS_19TargetTransformInfo15CastContextHintENS3_14TargetCostKindEPKNS_11InstructionE'/>
<use f='llvm/llvm/lib/Target/SystemZ/SystemZTargetTransformInfo.cpp' l='781' u='r' c='_ZN4llvm14SystemZTTIImpl16getCastInstrCostEjPNS_4TypeES2_NS_19TargetTransformInfo15CastContextHintENS3_14TargetCostKindEPKNS_11InstructionE'/>
<use f='llvm/llvm/lib/Target/SystemZ/SystemZTargetTransformInfo.cpp' l='880' u='r' c='_ZN4llvm14SystemZTTIImpl18getCmpSelInstrCostEjPNS_4TypeES2_NS_7CmpInst9PredicateENS_19TargetTransformInfo14TargetCostKindEPKNS_11InstructionE'/>
<use f='llvm/llvm/lib/Target/SystemZ/SystemZTargetTransformInfo.cpp' l='998' u='r' c='_ZN4llvm14SystemZTTIImpl14isFoldableLoadEPKNS_8LoadInstERPKNS_11InstructionE'/>
<use f='llvm/llvm/lib/Target/SystemZ/SystemZTargetTransformInfo.cpp' l='1084' u='r' c='_ZN4llvm14SystemZTTIImpl15getMemoryOpCostEjPNS_4TypeENS_10MaybeAlignEjNS_19TargetTransformInfo14TargetCostKindEPKNS_11InstructionE'/>
