<dec f='llvm/llvm/include/llvm/Analysis/LazyCallGraph.h' l='883' type='llvm::LazyCallGraph *'/>
<use f='llvm/llvm/include/llvm/Analysis/LazyCallGraph.h' l='887' u='w' c='_ZN4llvm13LazyCallGraph26postorder_ref_scc_iteratorC1ERS0_'/>
<use f='llvm/llvm/include/llvm/Analysis/LazyCallGraph.h' l='890' u='w' c='_ZN4llvm13LazyCallGraph26postorder_ref_scc_iteratorC1ERS0_NS1_8IsAtEndTE'/>
<use f='llvm/llvm/include/llvm/Analysis/LazyCallGraph.h' l='904' u='r' c='_ZNK4llvm13LazyCallGraph26postorder_ref_scc_iteratoreqERKS1_'/>
<use f='llvm/llvm/include/llvm/Analysis/LazyCallGraph.h' l='904' u='r' c='_ZNK4llvm13LazyCallGraph26postorder_ref_scc_iteratoreqERKS1_'/>
<use f='llvm/llvm/include/llvm/Analysis/LazyCallGraph.h' l='912' u='r' c='_ZN4llvm13LazyCallGraph26postorder_ref_scc_iteratorppEv'/>
<use f='llvm/llvm/include/llvm/Analysis/LazyCallGraph.h' l='912' u='r' c='_ZN4llvm13LazyCallGraph26postorder_ref_scc_iteratorppEv'/>
<offset>0</offset>
