<dec f='llvm/llvm/lib/Transforms/Scalar/SROA.cpp' l='365' type='llvm::sroa::Partition::iterator'/>
<use f='llvm/llvm/lib/Transforms/Scalar/SROA.cpp' l='372' u='w' c='_ZN4llvm4sroa9PartitionC1EPN12_GLOBAL__N_15SliceE'/>
<use f='llvm/llvm/lib/Transforms/Scalar/SROA.cpp' l='395' u='r' c='_ZNK4llvm4sroa9Partition5emptyEv'/>
<use f='llvm/llvm/lib/Transforms/Scalar/SROA.cpp' l='407' u='r' c='_ZNK4llvm4sroa9Partition3endEv'/>
<use f='llvm/llvm/lib/Transforms/Scalar/SROA.cpp' l='494' u='r' c='_ZN4llvm4sroa12AllocaSlices18partition_iterator7advanceEv'/>
<use f='llvm/llvm/lib/Transforms/Scalar/SROA.cpp' l='505' u='r' c='_ZN4llvm4sroa12AllocaSlices18partition_iterator7advanceEv'/>
<use f='llvm/llvm/lib/Transforms/Scalar/SROA.cpp' l='532' u='w' c='_ZN4llvm4sroa12AllocaSlices18partition_iterator7advanceEv'/>
<use f='llvm/llvm/lib/Transforms/Scalar/SROA.cpp' l='543' u='r' c='_ZN4llvm4sroa12AllocaSlices18partition_iterator7advanceEv'/>
<use f='llvm/llvm/lib/Transforms/Scalar/SROA.cpp' l='543' u='r' c='_ZN4llvm4sroa12AllocaSlices18partition_iterator7advanceEv'/>
<use f='llvm/llvm/lib/Transforms/Scalar/SROA.cpp' l='544' u='r' c='_ZN4llvm4sroa12AllocaSlices18partition_iterator7advanceEv'/>
<use f='llvm/llvm/lib/Transforms/Scalar/SROA.cpp' l='545' u='r' c='_ZN4llvm4sroa12AllocaSlices18partition_iterator7advanceEv'/>
<use f='llvm/llvm/lib/Transforms/Scalar/SROA.cpp' l='546' u='w' c='_ZN4llvm4sroa12AllocaSlices18partition_iterator7advanceEv'/>
<use f='llvm/llvm/lib/Transforms/Scalar/SROA.cpp' l='560' u='r' c='_ZN4llvm4sroa12AllocaSlices18partition_iterator7advanceEv'/>
<use f='llvm/llvm/lib/Transforms/Scalar/SROA.cpp' l='560' u='r' c='_ZN4llvm4sroa12AllocaSlices18partition_iterator7advanceEv'/>
<use f='llvm/llvm/lib/Transforms/Scalar/SROA.cpp' l='561' u='r' c='_ZN4llvm4sroa12AllocaSlices18partition_iterator7advanceEv'/>
<use f='llvm/llvm/lib/Transforms/Scalar/SROA.cpp' l='562' u='r' c='_ZN4llvm4sroa12AllocaSlices18partition_iterator7advanceEv'/>
<use f='llvm/llvm/lib/Transforms/Scalar/SROA.cpp' l='563' u='w' c='_ZN4llvm4sroa12AllocaSlices18partition_iterator7advanceEv'/>
<use f='llvm/llvm/lib/Transforms/Scalar/SROA.cpp' l='569' u='r' c='_ZN4llvm4sroa12AllocaSlices18partition_iterator7advanceEv'/>
<use f='llvm/llvm/lib/Transforms/Scalar/SROA.cpp' l='569' u='r' c='_ZN4llvm4sroa12AllocaSlices18partition_iterator7advanceEv'/>
<use f='llvm/llvm/lib/Transforms/Scalar/SROA.cpp' l='571' u='r' c='_ZN4llvm4sroa12AllocaSlices18partition_iterator7advanceEv'/>
<offset>192</offset>
