<dec f='llvm/llvm/lib/Target/X86/ImmutableGraph.h' l='112' type='const ImmutableGraph&lt;NodeValueT, EdgeValueT&gt; &amp;'/>
<use f='llvm/llvm/lib/Target/X86/ImmutableGraph.h' l='117' u='w' c='_ZN4llvm14ImmutableGraph7NodeSetC1ERKNS_14ImmutableGraphIT_T0_EEb'/>
<use f='llvm/llvm/lib/Target/X86/ImmutableGraph.h' l='119' u='c' c='_ZN4llvm14ImmutableGraph7NodeSet6insertERKNS0_4NodeE'/>
<use f='llvm/llvm/lib/Target/X86/ImmutableGraph.h' l='125' u='c' c='_ZN4llvm14ImmutableGraph7NodeSet5eraseERKNS0_4NodeE'/>
<use f='llvm/llvm/lib/Target/X86/ImmutableGraph.h' l='129' u='c' c='_ZNK4llvm14ImmutableGraph7NodeSet8containsERKNS0_4NodeE'/>
