<dec f='llvm/llvm/include/llvm/Demangle/ItaniumDemangle.h' l='701' type='const llvm::itanium_demangle::Node *'/>
<use f='llvm/llvm/include/llvm/Demangle/ItaniumDemangle.h' l='703' u='w' c='_ZN4llvm16itanium_demangle12NoexceptSpecC1EPKNS0_4NodeE'/>
<use f='llvm/llvm/include/llvm/Demangle/ItaniumDemangle.h' l='705' c='_ZNK4llvm16itanium_demangle12NoexceptSpec5matchET_'/>
<use f='llvm/llvm/include/llvm/Demangle/ItaniumDemangle.h' l='709' u='r' c='_ZNK4llvm16itanium_demangle12NoexceptSpec9printLeftERNS0_12OutputStreamE'/>
<offset>128</offset>
