<dec f='llvm/llvm/include/llvm/IR/LegacyPassManagers.h' l='112' type='llvm::Value *'/>
<use f='llvm/llvm/include/llvm/IR/LegacyPassManagers.h' l='117' u='w' c='_ZN4llvm27PassManagerPrettyStackEntryC1EPNS_4PassE'/>
<use f='llvm/llvm/include/llvm/IR/LegacyPassManagers.h' l='119' u='w' c='_ZN4llvm27PassManagerPrettyStackEntryC1EPNS_4PassERNS_5ValueE'/>
<use f='llvm/llvm/include/llvm/IR/LegacyPassManagers.h' l='121' u='w' c='_ZN4llvm27PassManagerPrettyStackEntryC1EPNS_4PassERNS_6ModuleE'/>
<offset>192</offset>
<use f='llvm/llvm/lib/IR/LegacyPassManager.cpp' l='215' u='r' c='_ZNK4llvm27PassManagerPrettyStackEntry5printERNS_11raw_ostreamE'/>
<use f='llvm/llvm/lib/IR/LegacyPassManager.cpp' l='226' u='r' c='_ZNK4llvm27PassManagerPrettyStackEntry5printERNS_11raw_ostreamE'/>
<use f='llvm/llvm/lib/IR/LegacyPassManager.cpp' l='232' u='r' c='_ZNK4llvm27PassManagerPrettyStackEntry5printERNS_11raw_ostreamE'/>
<use f='llvm/llvm/lib/IR/LegacyPassManager.cpp' l='234' u='r' c='_ZNK4llvm27PassManagerPrettyStackEntry5printERNS_11raw_ostreamE'/>
<use f='llvm/llvm/lib/IR/LegacyPassManager.cpp' l='240' u='r' c='_ZNK4llvm27PassManagerPrettyStackEntry5printERNS_11raw_ostreamE'/>
