<dec f='llvm/llvm/include/llvm/DebugInfo/CodeView/CodeView.h' l='160' type='16'/>
<use f='llvm/llvm/lib/DebugInfo/CodeView/EnumTables.cpp' l='106'/>
<use f='llvm/llvm/lib/DebugInfo/PDB/PDBExtras.cpp' l='231' c='_ZN4llvm3pdblsERNS_11raw_ostreamERKNS_8codeview14SourceLanguageE'/>
<use f='llvm/llvm/tools/llvm-pdbutil/MinimalSymbolDumper.cpp' l='207' c='_ZL20formatSourceLanguageB5cxx11N4llvm8codeview14SourceLanguageE'/>
