<dec f='llvm/llvm/include/llvm/Transforms/Scalar/NaryReassociate.h' l='168' type='const llvm::DataLayout *'/>
<offset>64</offset>
<use f='llvm/llvm/lib/Transforms/Scalar/NaryReassociate.cpp' l='206' u='w' c='_ZN4llvm19NaryReassociatePass7runImplERNS_8FunctionEPNS_15AssumptionCacheEPNS_13DominatorTreeEPNS_15ScalarEvolutionEPNS_17TargetLibraryInfoEPNS_19TargetTransformInfoE'/>
<use f='llvm/llvm/lib/Transforms/Scalar/NaryReassociate.cpp' l='321' u='r' c='_ZN4llvm19NaryReassociatePass21requiresSignExtensionEPNS_5ValueEPNS_17GetElementPtrInstE'/>
<use f='llvm/llvm/lib/Transforms/Scalar/NaryReassociate.cpp' l='333' u='r' c='_ZN4llvm19NaryReassociatePass24tryReassociateGEPAtIndexEPNS_17GetElementPtrInstEjPNS_4TypeE'/>
<use f='llvm/llvm/lib/Transforms/Scalar/NaryReassociate.cpp' l='342' u='r' c='_ZN4llvm19NaryReassociatePass24tryReassociateGEPAtIndexEPNS_17GetElementPtrInstEjPNS_4TypeE'/>
<use f='llvm/llvm/lib/Transforms/Scalar/NaryReassociate.cpp' l='371' u='r' c='_ZN4llvm19NaryReassociatePass24tryReassociateGEPAtIndexEPNS_17GetElementPtrInstEjPNS_5ValueES4_PNS_4TypeE'/>
<use f='llvm/llvm/lib/Transforms/Scalar/NaryReassociate.cpp' l='372' u='r' c='_ZN4llvm19NaryReassociatePass24tryReassociateGEPAtIndexEPNS_17GetElementPtrInstEjPNS_5ValueES4_PNS_4TypeE'/>
<use f='llvm/llvm/lib/Transforms/Scalar/NaryReassociate.cpp' l='373' u='r' c='_ZN4llvm19NaryReassociatePass24tryReassociateGEPAtIndexEPNS_17GetElementPtrInstEjPNS_5ValueES4_PNS_4TypeE'/>
<use f='llvm/llvm/lib/Transforms/Scalar/NaryReassociate.cpp' l='396' u='r' c='_ZN4llvm19NaryReassociatePass24tryReassociateGEPAtIndexEPNS_17GetElementPtrInstEjPNS_5ValueES4_PNS_4TypeE'/>
<use f='llvm/llvm/lib/Transforms/Scalar/NaryReassociate.cpp' l='398' u='r' c='_ZN4llvm19NaryReassociatePass24tryReassociateGEPAtIndexEPNS_17GetElementPtrInstEjPNS_5ValueES4_PNS_4TypeE'/>
<use f='llvm/llvm/lib/Transforms/Scalar/NaryReassociate.cpp' l='417' u='r' c='_ZN4llvm19NaryReassociatePass24tryReassociateGEPAtIndexEPNS_17GetElementPtrInstEjPNS_5ValueES4_PNS_4TypeE'/>
