<dec f='llvm/build/lib/Target/RISCV/RISCVGenInstrInfo.inc' l='14581' type='14566'/>
<use f='llvm/build/lib/Target/RISCV/RISCVGenAsmMatcher.inc' l='4008'/>
<use f='llvm/build/lib/Target/RISCV/RISCVGenMCCodeEmitter.inc' l='16452' c='_ZNK12_GLOBAL__N_118RISCVMCCodeEmitter21getBinaryCodeForInstrERKN4llvm6MCInstERNS1_15SmallVectorImplINS1_7MCFixupEEERKNS1_15MCSubtargetInfoE'/>
<use f='llvm/llvm/lib/Target/RISCV/RISCVExpandAtomicPseudoInsts.cpp' l='385' u='r' c='_ZN12_GLOBAL__N_110insertSextEPKN4llvm14RISCVInstrInfoENS0_8DebugLocEPNS0_17MachineBasicBlockENS0_8RegisterES7_'/>
<use f='llvm/build/lib/Target/RISCV/RISCVGenDAGISel.inc' l='26355' u='r' c='_ZN4llvm17RISCVDAGToDAGISel10SelectCodeEPNS_6SDNodeE'/>
<use f='llvm/build/lib/Target/RISCV/RISCVGenDAGISel.inc' l='26355' u='r' c='_ZN4llvm17RISCVDAGToDAGISel10SelectCodeEPNS_6SDNodeE'/>
<use f='llvm/build/lib/Target/RISCV/RISCVGenDAGISel.inc' l='26362' u='r' c='_ZN4llvm17RISCVDAGToDAGISel10SelectCodeEPNS_6SDNodeE'/>
<use f='llvm/build/lib/Target/RISCV/RISCVGenDAGISel.inc' l='26362' u='r' c='_ZN4llvm17RISCVDAGToDAGISel10SelectCodeEPNS_6SDNodeE'/>
<use f='llvm/build/lib/Target/RISCV/RISCVGenDAGISel.inc' l='26416' u='r' c='_ZN4llvm17RISCVDAGToDAGISel10SelectCodeEPNS_6SDNodeE'/>
<use f='llvm/build/lib/Target/RISCV/RISCVGenDAGISel.inc' l='26416' u='r' c='_ZN4llvm17RISCVDAGToDAGISel10SelectCodeEPNS_6SDNodeE'/>
<use f='llvm/build/lib/Target/RISCV/RISCVGenDAGISel.inc' l='26423' u='r' c='_ZN4llvm17RISCVDAGToDAGISel10SelectCodeEPNS_6SDNodeE'/>
<use f='llvm/build/lib/Target/RISCV/RISCVGenDAGISel.inc' l='26423' u='r' c='_ZN4llvm17RISCVDAGToDAGISel10SelectCodeEPNS_6SDNodeE'/>
<use f='llvm/build/lib/Target/RISCV/RISCVGenGlobalISel.inc' l='17501' u='r' c='_ZNK12_GLOBAL__N_124RISCVInstructionSelector13getMatchTableEv'/>
<use f='llvm/build/lib/Target/RISCV/RISCVGenGlobalISel.inc' l='17530' u='r' c='_ZNK12_GLOBAL__N_124RISCVInstructionSelector13getMatchTableEv'/>
<use f='llvm/build/lib/Target/RISCV/RISCVGenGlobalISel.inc' l='17558' u='r' c='_ZNK12_GLOBAL__N_124RISCVInstructionSelector13getMatchTableEv'/>
<use f='llvm/build/lib/Target/RISCV/RISCVGenGlobalISel.inc' l='17587' u='r' c='_ZNK12_GLOBAL__N_124RISCVInstructionSelector13getMatchTableEv'/>
