<use f='llvm/llvm/include/llvm/ExecutionEngine/Orc/MachOPlatform.h' l='98' u='a' c='_ZNK4llvm3orc13MachOPlatform19getExecutionSessionEv'/>
<dec f='llvm/llvm/include/llvm/ExecutionEngine/Orc/MachOPlatform.h' l='158' type='llvm::orc::ExecutionSession &amp;'/>
<offset>64</offset>
<use f='llvm/llvm/lib/ExecutionEngine/Orc/MachOPlatform.cpp' l='151' u='w' c='_ZN4llvm3orc13MachOPlatformC1ERNS0_16ExecutionSessionERNS0_18ObjectLinkingLayerESt10unique_ptrINS_12MemoryBufferESt14default_deleteIS7_EE'/>
<use f='llvm/llvm/lib/ExecutionEngine/Orc/MachOPlatform.cpp' l='196' u='m' c='_ZN4llvm3orc13MachOPlatform22getInitializerSequenceERNS0_8JITDylibE'/>
