<dec f='llvm/build/include/llvm/IR/IntrinsicEnums.inc' l='81' type='72'/>
<doc f='llvm/build/include/llvm/IR/IntrinsicEnums.inc' l='81'>// llvm.exp</doc>
<use f='llvm/clang/lib/CodeGen/CGBuiltin.cpp' l='2263' u='r' c='_ZN5clang7CodeGen15CodeGenFunction15EmitBuiltinExprENS_10GlobalDeclEjPKNS_8CallExprENS0_15ReturnValueSlotE'/>
<use f='llvm/llvm/lib/Analysis/ConstantFolding.cpp' l='1509' c='_ZN4llvm21canConstantFoldCallToEPKNS_8CallBaseEPKNS_8FunctionE'/>
<use f='llvm/llvm/lib/Analysis/ConstantFolding.cpp' l='2063' c='_ZN12_GLOBAL__N_123ConstantFoldScalarCall1EN4llvm9StringRefEjPNS0_4TypeENS0_8ArrayRefIPNS0_8ConstantEEEPKNS0_17TargetLibraryInfoEPKNS0_8CallBaseE'/>
<use f='llvm/llvm/lib/Analysis/InstructionSimplify.cpp' l='5331' c='_ZL22simplifyUnaryIntrinsicPN4llvm8FunctionEPNS_5ValueERKNS_13SimplifyQueryE'/>
<use f='llvm/llvm/lib/Analysis/InstructionSimplify.cpp' l='5344' u='c' c='_ZL22simplifyUnaryIntrinsicPN4llvm8FunctionEPNS_5ValueERKNS_13SimplifyQueryE'/>
<use f='llvm/llvm/lib/Analysis/ValueTracking.cpp' l='3135' u='r' c='_ZN4llvm23getIntrinsicForCallSiteERKNS_8CallBaseEPKNS_17TargetLibraryInfoE'/>
<use f='llvm/llvm/lib/Analysis/ValueTracking.cpp' l='3374' c='_ZL31cannotBeOrderedLessThanZeroImplPKN4llvm5ValueEPKNS_17TargetLibraryInfoEbj'/>
<use f='llvm/llvm/lib/Analysis/ValueTracking.cpp' l='3553' c='_ZN4llvm15isKnownNeverNaNEPKNS_5ValueEPKNS_17TargetLibraryInfoEj'/>
<use f='llvm/llvm/lib/Analysis/VectorUtils.cpp' l='69' c='_ZN4llvm23isTriviallyVectorizableEj'/>
<use f='llvm/llvm/include/llvm/CodeGen/BasicTTIImpl.h' l='1452' c='_ZN4llvm16BasicTTIImplBase30getTypeBasedIntrinsicInstrCostERKNS_23IntrinsicCostAttributesENS_19TargetTransformInfo14TargetCostKindE'/>
<use f='llvm/llvm/lib/CodeGen/GlobalISel/IRTranslator.cpp' l='1683' c='_ZN4llvm12IRTranslator24getSimpleIntrinsicOpcodeEj'/>
<use f='llvm/llvm/lib/CodeGen/IntrinsicLowering.cpp' l='389' c='_ZN4llvm17IntrinsicLowering18LowerIntrinsicCallEPNS_8CallInstE'/>
<use f='llvm/llvm/lib/CodeGen/SelectionDAG/SelectionDAGBuilder.cpp' l='6075' c='_ZN4llvm19SelectionDAGBuilder18visitIntrinsicCallERKNS_8CallInstEj'/>
<use f='llvm/llvm/lib/Target/ARM/ARMTargetTransformInfo.cpp' l='1594' c='_ZN4llvm10ARMTTIImpl15isLoweredToCallEPKNS_8FunctionE'/>
<use f='llvm/llvm/lib/Target/PowerPC/PPCTargetTransformInfo.cpp' l='472' c='_ZN4llvm10PPCTTIImpl11mightUseCTREPNS_10BasicBlockEPNS_17TargetLibraryInfoERNS_15SmallPtrSetImplIPKNS_5ValueEEE'/>
<use f='llvm/llvm/lib/Transforms/InstCombine/InstCombineMulDivRem.cpp' l='560' u='c' c='_ZN4llvm16InstCombinerImpl9visitFMulERNS_14BinaryOperatorE'/>
<use f='llvm/llvm/lib/Transforms/InstCombine/InstCombineMulDivRem.cpp' l='561' u='c' c='_ZN4llvm16InstCombinerImpl9visitFMulERNS_14BinaryOperatorE'/>
<use f='llvm/llvm/lib/Transforms/InstCombine/InstCombineMulDivRem.cpp' l='564' u='r' c='_ZN4llvm16InstCombinerImpl9visitFMulERNS_14BinaryOperatorE'/>
<use f='llvm/llvm/lib/Transforms/Utils/SimplifyLibCalls.cpp' l='1512' u='r' c='_ZN4llvm17LibCallSimplifier17replacePowWithExpEPNS_8CallInstERNS_13IRBuilderBaseE'/>
<use f='llvm/llvm/lib/Transforms/Utils/SimplifyLibCalls.cpp' l='2002' u='r' c='_ZN4llvm17LibCallSimplifier11optimizeLogEPNS_8CallInstERNS_13IRBuilderBaseE'/>
<use f='llvm/llvm/lib/Transforms/Utils/SimplifyLibCalls.cpp' l='2004' u='r' c='_ZN4llvm17LibCallSimplifier11optimizeLogEPNS_8CallInstERNS_13IRBuilderBaseE'/>
