<dec f='llvm/llvm/include/llvm/IR/Metadata.h' l='343' type='llvm::Value *'/>
<use f='llvm/llvm/include/llvm/IR/Metadata.h' l='352' u='w' c='_ZN4llvm15ValueAsMetadataC1EjPNS_5ValueE'/>
<use f='llvm/llvm/include/llvm/IR/Metadata.h' l='379' u='r' c='_ZNK4llvm15ValueAsMetadata8getValueEv'/>
<use f='llvm/llvm/include/llvm/IR/Metadata.h' l='380' u='r' c='_ZNK4llvm15ValueAsMetadata7getTypeEv'/>
<use f='llvm/llvm/include/llvm/IR/Metadata.h' l='381' u='r' c='_ZNK4llvm15ValueAsMetadata10getContextEv'/>
<offset>1024</offset>
<use f='llvm/llvm/lib/IR/Metadata.cpp' l='446' u='w' c='_ZN4llvm15ValueAsMetadata10handleRAUWEPNS_5ValueES2_'/>
