<dec f='llvm/build/lib/Target/SystemZ/SystemZGenInstrInfo.inc' l='1131' type='1116'/>
<use f='llvm/build/lib/Target/SystemZ/SystemZGenAsmMatcher.inc' l='4001'/>
<use f='llvm/build/lib/Target/SystemZ/SystemZGenMCCodeEmitter.inc' l='5626' c='_ZNK12_GLOBAL__N_120SystemZMCCodeEmitter21getBinaryCodeForInstrERKN4llvm6MCInstERNS1_15SmallVectorImplINS1_7MCFixupEEERKNS1_15MCSubtargetInfoE'/>
<use f='llvm/build/lib/Target/SystemZ/SystemZGenDAGISel.inc' l='11778' u='r' c='_ZN12_GLOBAL__N_119SystemZDAGToDAGISel10SelectCodeEPN4llvm6SDNodeE'/>
<use f='llvm/build/lib/Target/SystemZ/SystemZGenDAGISel.inc' l='11778' u='r' c='_ZN12_GLOBAL__N_119SystemZDAGToDAGISel10SelectCodeEPN4llvm6SDNodeE'/>
<use f='llvm/llvm/lib/Target/SystemZ/SystemZISelLowering.cpp' l='7646' u='r' c='_ZNK4llvm21SystemZTargetLowering18emitAtomicCmpSwapWERNS_12MachineInstrEPNS_17MachineBasicBlockE'/>
<use f='llvm/llvm/lib/Target/SystemZ/SystemZISelLowering.cpp' l='8346' u='r' c='_ZNK4llvm21SystemZTargetLowering27EmitInstrWithCustomInserterERNS_12MachineInstrEPNS_17MachineBasicBlockE'/>
<use f='llvm/llvm/lib/Target/SystemZ/SystemZISelLowering.cpp' l='8349' u='r' c='_ZNK4llvm21SystemZTargetLowering27EmitInstrWithCustomInserterERNS_12MachineInstrEPNS_17MachineBasicBlockE'/>
<use f='llvm/llvm/lib/Target/SystemZ/SystemZISelLowering.cpp' l='8356' u='r' c='_ZNK4llvm21SystemZTargetLowering27EmitInstrWithCustomInserterERNS_12MachineInstrEPNS_17MachineBasicBlockE'/>
<use f='llvm/llvm/lib/Target/SystemZ/SystemZISelLowering.cpp' l='8359' u='r' c='_ZNK4llvm21SystemZTargetLowering27EmitInstrWithCustomInserterERNS_12MachineInstrEPNS_17MachineBasicBlockE'/>
<use f='llvm/llvm/lib/Target/SystemZ/SystemZInstrInfo.cpp' l='1223' u='r' c='_ZNK4llvm16SystemZInstrInfo21foldMemoryOperandImplERNS_15MachineFunctionERNS_12MachineInstrENS_8ArrayRefIjEENS_26MachineInstrBundleIteratorIS3_Lb0EEEi15416259'/>
<use f='llvm/llvm/lib/Target/SystemZ/SystemZInstrInfo.cpp' l='1739' c='_ZNK4llvm16SystemZInstrInfo15getFusedCompareEjNS_9SystemZII16FusedCompareTypeEPKNS_12MachineInstrE'/>
<use f='llvm/llvm/lib/Target/SystemZ/SystemZInstrInfo.cpp' l='1760' c='_ZNK4llvm16SystemZInstrInfo15getFusedCompareEjNS_9SystemZII16FusedCompareTypeEPKNS_12MachineInstrE'/>
<use f='llvm/llvm/lib/Target/SystemZ/SystemZInstrInfo.cpp' l='1781' c='_ZNK4llvm16SystemZInstrInfo15getFusedCompareEjNS_9SystemZII16FusedCompareTypeEPKNS_12MachineInstrE'/>
<use f='llvm/llvm/lib/Target/SystemZ/SystemZInstrInfo.cpp' l='1802' c='_ZNK4llvm16SystemZInstrInfo15getFusedCompareEjNS_9SystemZII16FusedCompareTypeEPKNS_12MachineInstrE'/>
<use f='llvm/llvm/lib/Target/SystemZ/SystemZLongBranch.cpp' l='406' u='r' c='_ZN12_GLOBAL__N_117SystemZLongBranch11relaxBranchERNS_14TerminatorInfoE'/>
