<dec f='llvm/build/lib/Target/RISCV/RISCVGenInstrInfo.inc' l='14592' type='14577'/>
<use f='llvm/build/lib/Target/RISCV/RISCVGenCompressInstEmitter.inc' l='916' c='_ZL12compressInstRN4llvm6MCInstERKS0_RKNS_15MCSubtargetInfoERNS_9MCContextE'/>
<use f='llvm/build/lib/Target/RISCV/RISCVGenAsmMatcher.inc' l='4024'/>
<use f='llvm/build/lib/Target/RISCV/RISCVGenAsmMatcher.inc' l='4025'/>
<use f='llvm/llvm/lib/Target/RISCV/AsmParser/RISCVAsmParser.cpp' l='2536' u='r' c='_ZN12_GLOBAL__N_114RISCVAsmParser18processInstructionERN4llvm6MCInstENS1_5SMLocERNS1_15SmallVectorImplISt10unique_ptrINS1_18MCParsedAsmOperandESt14def15576407'/>
<use f='llvm/build/lib/Target/RISCV/RISCVGenMCCodeEmitter.inc' l='15540' c='_ZNK12_GLOBAL__N_118RISCVMCCodeEmitter21getBinaryCodeForInstrERKN4llvm6MCInstERNS1_15SmallVectorImplINS1_7MCFixupEEERKNS1_15MCSubtargetInfoE'/>
<use f='llvm/llvm/lib/Target/RISCV/RISCVFrameLowering.cpp' l='67' u='r' c='_ZL15emitSCSPrologueRN4llvm15MachineFunctionERNS_17MachineBasicBlockENS_26MachineInstrBundleIteratorINS_12MachineInstrELb0EEERKNS_8DebugLocE'/>
<use f='llvm/build/lib/Target/RISCV/RISCVGenDAGISel.inc' l='16797' u='r' c='_ZN4llvm17RISCVDAGToDAGISel10SelectCodeEPNS_6SDNodeE'/>
<use f='llvm/build/lib/Target/RISCV/RISCVGenDAGISel.inc' l='16797' u='r' c='_ZN4llvm17RISCVDAGToDAGISel10SelectCodeEPNS_6SDNodeE'/>
<use f='llvm/build/lib/Target/RISCV/RISCVGenDAGISel.inc' l='16808' u='r' c='_ZN4llvm17RISCVDAGToDAGISel10SelectCodeEPNS_6SDNodeE'/>
<use f='llvm/build/lib/Target/RISCV/RISCVGenDAGISel.inc' l='16808' u='r' c='_ZN4llvm17RISCVDAGToDAGISel10SelectCodeEPNS_6SDNodeE'/>
<use f='llvm/build/lib/Target/RISCV/RISCVGenDAGISel.inc' l='16862' u='r' c='_ZN4llvm17RISCVDAGToDAGISel10SelectCodeEPNS_6SDNodeE'/>
<use f='llvm/build/lib/Target/RISCV/RISCVGenDAGISel.inc' l='16862' u='r' c='_ZN4llvm17RISCVDAGToDAGISel10SelectCodeEPNS_6SDNodeE'/>
<use f='llvm/build/lib/Target/RISCV/RISCVGenDAGISel.inc' l='16873' u='r' c='_ZN4llvm17RISCVDAGToDAGISel10SelectCodeEPNS_6SDNodeE'/>
<use f='llvm/build/lib/Target/RISCV/RISCVGenDAGISel.inc' l='16873' u='r' c='_ZN4llvm17RISCVDAGToDAGISel10SelectCodeEPNS_6SDNodeE'/>
<use f='llvm/build/lib/Target/RISCV/RISCVGenDAGISel.inc' l='16913' u='r' c='_ZN4llvm17RISCVDAGToDAGISel10SelectCodeEPNS_6SDNodeE'/>
<use f='llvm/build/lib/Target/RISCV/RISCVGenDAGISel.inc' l='16913' u='r' c='_ZN4llvm17RISCVDAGToDAGISel10SelectCodeEPNS_6SDNodeE'/>
<use f='llvm/build/lib/Target/RISCV/RISCVGenDAGISel.inc' l='16923' u='r' c='_ZN4llvm17RISCVDAGToDAGISel10SelectCodeEPNS_6SDNodeE'/>
<use f='llvm/build/lib/Target/RISCV/RISCVGenDAGISel.inc' l='16923' u='r' c='_ZN4llvm17RISCVDAGToDAGISel10SelectCodeEPNS_6SDNodeE'/>
<use f='llvm/build/lib/Target/RISCV/RISCVGenDAGISel.inc' l='16970' u='r' c='_ZN4llvm17RISCVDAGToDAGISel10SelectCodeEPNS_6SDNodeE'/>
<use f='llvm/build/lib/Target/RISCV/RISCVGenDAGISel.inc' l='16970' u='r' c='_ZN4llvm17RISCVDAGToDAGISel10SelectCodeEPNS_6SDNodeE'/>
<use f='llvm/build/lib/Target/RISCV/RISCVGenDAGISel.inc' l='16981' u='r' c='_ZN4llvm17RISCVDAGToDAGISel10SelectCodeEPNS_6SDNodeE'/>
<use f='llvm/build/lib/Target/RISCV/RISCVGenDAGISel.inc' l='16981' u='r' c='_ZN4llvm17RISCVDAGToDAGISel10SelectCodeEPNS_6SDNodeE'/>
<use f='llvm/build/lib/Target/RISCV/RISCVGenDAGISel.inc' l='17023' u='r' c='_ZN4llvm17RISCVDAGToDAGISel10SelectCodeEPNS_6SDNodeE'/>
<use f='llvm/build/lib/Target/RISCV/RISCVGenDAGISel.inc' l='17023' u='r' c='_ZN4llvm17RISCVDAGToDAGISel10SelectCodeEPNS_6SDNodeE'/>
<use f='llvm/build/lib/Target/RISCV/RISCVGenDAGISel.inc' l='17033' u='r' c='_ZN4llvm17RISCVDAGToDAGISel10SelectCodeEPNS_6SDNodeE'/>
<use f='llvm/build/lib/Target/RISCV/RISCVGenDAGISel.inc' l='17033' u='r' c='_ZN4llvm17RISCVDAGToDAGISel10SelectCodeEPNS_6SDNodeE'/>
<use f='llvm/build/lib/Target/RISCV/RISCVGenDAGISel.inc' l='17091' u='r' c='_ZN4llvm17RISCVDAGToDAGISel10SelectCodeEPNS_6SDNodeE'/>
<use f='llvm/build/lib/Target/RISCV/RISCVGenDAGISel.inc' l='17091' u='r' c='_ZN4llvm17RISCVDAGToDAGISel10SelectCodeEPNS_6SDNodeE'/>
<use f='llvm/build/lib/Target/RISCV/RISCVGenDAGISel.inc' l='17102' u='r' c='_ZN4llvm17RISCVDAGToDAGISel10SelectCodeEPNS_6SDNodeE'/>
<use f='llvm/build/lib/Target/RISCV/RISCVGenDAGISel.inc' l='17102' u='r' c='_ZN4llvm17RISCVDAGToDAGISel10SelectCodeEPNS_6SDNodeE'/>
<use f='llvm/build/lib/Target/RISCV/RISCVGenDAGISel.inc' l='17154' u='r' c='_ZN4llvm17RISCVDAGToDAGISel10SelectCodeEPNS_6SDNodeE'/>
<use f='llvm/build/lib/Target/RISCV/RISCVGenDAGISel.inc' l='17154' u='r' c='_ZN4llvm17RISCVDAGToDAGISel10SelectCodeEPNS_6SDNodeE'/>
<use f='llvm/build/lib/Target/RISCV/RISCVGenDAGISel.inc' l='17165' u='r' c='_ZN4llvm17RISCVDAGToDAGISel10SelectCodeEPNS_6SDNodeE'/>
<use f='llvm/build/lib/Target/RISCV/RISCVGenDAGISel.inc' l='17165' u='r' c='_ZN4llvm17RISCVDAGToDAGISel10SelectCodeEPNS_6SDNodeE'/>
<use f='llvm/build/lib/Target/RISCV/RISCVGenDAGISel.inc' l='17203' u='r' c='_ZN4llvm17RISCVDAGToDAGISel10SelectCodeEPNS_6SDNodeE'/>
<use f='llvm/build/lib/Target/RISCV/RISCVGenDAGISel.inc' l='17203' u='r' c='_ZN4llvm17RISCVDAGToDAGISel10SelectCodeEPNS_6SDNodeE'/>
<use f='llvm/build/lib/Target/RISCV/RISCVGenDAGISel.inc' l='17213' u='r' c='_ZN4llvm17RISCVDAGToDAGISel10SelectCodeEPNS_6SDNodeE'/>
<use f='llvm/build/lib/Target/RISCV/RISCVGenDAGISel.inc' l='17213' u='r' c='_ZN4llvm17RISCVDAGToDAGISel10SelectCodeEPNS_6SDNodeE'/>
<use f='llvm/build/lib/Target/RISCV/RISCVGenDAGISel.inc' l='17258' u='r' c='_ZN4llvm17RISCVDAGToDAGISel10SelectCodeEPNS_6SDNodeE'/>
<use f='llvm/build/lib/Target/RISCV/RISCVGenDAGISel.inc' l='17258' u='r' c='_ZN4llvm17RISCVDAGToDAGISel10SelectCodeEPNS_6SDNodeE'/>
<use f='llvm/build/lib/Target/RISCV/RISCVGenDAGISel.inc' l='17269' u='r' c='_ZN4llvm17RISCVDAGToDAGISel10SelectCodeEPNS_6SDNodeE'/>
<use f='llvm/build/lib/Target/RISCV/RISCVGenDAGISel.inc' l='17269' u='r' c='_ZN4llvm17RISCVDAGToDAGISel10SelectCodeEPNS_6SDNodeE'/>
<use f='llvm/build/lib/Target/RISCV/RISCVGenDAGISel.inc' l='17309' u='r' c='_ZN4llvm17RISCVDAGToDAGISel10SelectCodeEPNS_6SDNodeE'/>
<use f='llvm/build/lib/Target/RISCV/RISCVGenDAGISel.inc' l='17309' u='r' c='_ZN4llvm17RISCVDAGToDAGISel10SelectCodeEPNS_6SDNodeE'/>
<use f='llvm/build/lib/Target/RISCV/RISCVGenDAGISel.inc' l='17319' u='r' c='_ZN4llvm17RISCVDAGToDAGISel10SelectCodeEPNS_6SDNodeE'/>
<use f='llvm/build/lib/Target/RISCV/RISCVGenDAGISel.inc' l='17319' u='r' c='_ZN4llvm17RISCVDAGToDAGISel10SelectCodeEPNS_6SDNodeE'/>
<use f='llvm/build/lib/Target/RISCV/RISCVGenDAGISel.inc' l='19471' u='r' c='_ZN4llvm17RISCVDAGToDAGISel10SelectCodeEPNS_6SDNodeE'/>
<use f='llvm/build/lib/Target/RISCV/RISCVGenDAGISel.inc' l='19471' u='r' c='_ZN4llvm17RISCVDAGToDAGISel10SelectCodeEPNS_6SDNodeE'/>
<use f='llvm/build/lib/Target/RISCV/RISCVGenDAGISel.inc' l='19516' u='r' c='_ZN4llvm17RISCVDAGToDAGISel10SelectCodeEPNS_6SDNodeE'/>
<use f='llvm/build/lib/Target/RISCV/RISCVGenDAGISel.inc' l='19516' u='r' c='_ZN4llvm17RISCVDAGToDAGISel10SelectCodeEPNS_6SDNodeE'/>
<use f='llvm/build/lib/Target/RISCV/RISCVGenDAGISel.inc' l='19569' u='r' c='_ZN4llvm17RISCVDAGToDAGISel10SelectCodeEPNS_6SDNodeE'/>
<use f='llvm/build/lib/Target/RISCV/RISCVGenDAGISel.inc' l='19569' u='r' c='_ZN4llvm17RISCVDAGToDAGISel10SelectCodeEPNS_6SDNodeE'/>
<use f='llvm/build/lib/Target/RISCV/RISCVGenDAGISel.inc' l='19606' u='r' c='_ZN4llvm17RISCVDAGToDAGISel10SelectCodeEPNS_6SDNodeE'/>
<use f='llvm/build/lib/Target/RISCV/RISCVGenDAGISel.inc' l='19606' u='r' c='_ZN4llvm17RISCVDAGToDAGISel10SelectCodeEPNS_6SDNodeE'/>
<use f='llvm/build/lib/Target/RISCV/RISCVGenDAGISel.inc' l='19650' u='r' c='_ZN4llvm17RISCVDAGToDAGISel10SelectCodeEPNS_6SDNodeE'/>
<use f='llvm/build/lib/Target/RISCV/RISCVGenDAGISel.inc' l='19650' u='r' c='_ZN4llvm17RISCVDAGToDAGISel10SelectCodeEPNS_6SDNodeE'/>
<use f='llvm/build/lib/Target/RISCV/RISCVGenDAGISel.inc' l='19687' u='r' c='_ZN4llvm17RISCVDAGToDAGISel10SelectCodeEPNS_6SDNodeE'/>
<use f='llvm/build/lib/Target/RISCV/RISCVGenDAGISel.inc' l='19687' u='r' c='_ZN4llvm17RISCVDAGToDAGISel10SelectCodeEPNS_6SDNodeE'/>
<use f='llvm/build/lib/Target/RISCV/RISCVGenDAGISel.inc' l='19735' u='r' c='_ZN4llvm17RISCVDAGToDAGISel10SelectCodeEPNS_6SDNodeE'/>
<use f='llvm/build/lib/Target/RISCV/RISCVGenDAGISel.inc' l='19735' u='r' c='_ZN4llvm17RISCVDAGToDAGISel10SelectCodeEPNS_6SDNodeE'/>
<use f='llvm/build/lib/Target/RISCV/RISCVGenDAGISel.inc' l='19778' u='r' c='_ZN4llvm17RISCVDAGToDAGISel10SelectCodeEPNS_6SDNodeE'/>
<use f='llvm/build/lib/Target/RISCV/RISCVGenDAGISel.inc' l='19778' u='r' c='_ZN4llvm17RISCVDAGToDAGISel10SelectCodeEPNS_6SDNodeE'/>
<use f='llvm/build/lib/Target/RISCV/RISCVGenDAGISel.inc' l='19821' u='r' c='_ZN4llvm17RISCVDAGToDAGISel10SelectCodeEPNS_6SDNodeE'/>
<use f='llvm/build/lib/Target/RISCV/RISCVGenDAGISel.inc' l='19821' u='r' c='_ZN4llvm17RISCVDAGToDAGISel10SelectCodeEPNS_6SDNodeE'/>
<use f='llvm/build/lib/Target/RISCV/RISCVGenDAGISel.inc' l='19862' u='r' c='_ZN4llvm17RISCVDAGToDAGISel10SelectCodeEPNS_6SDNodeE'/>
<use f='llvm/build/lib/Target/RISCV/RISCVGenDAGISel.inc' l='19862' u='r' c='_ZN4llvm17RISCVDAGToDAGISel10SelectCodeEPNS_6SDNodeE'/>
<use f='llvm/llvm/lib/Target/RISCV/RISCVISelDAGToDAG.cpp' l='972' c='_ZN4llvm17RISCVDAGToDAGISel23doPeepholeLoadStoreADDIEv'/>
<use f='llvm/llvm/lib/Target/RISCV/RISCVISelLowering.cpp' l='2567' u='r' c='_ZL22emitBuildPairF64PseudoRN4llvm12MachineInstrEPNS_17MachineBasicBlockE'/>
<use f='llvm/llvm/lib/Target/RISCV/RISCVISelLowering.cpp' l='2572' u='r' c='_ZL22emitBuildPairF64PseudoRN4llvm12MachineInstrEPNS_17MachineBasicBlockE'/>
<use f='llvm/llvm/lib/Target/RISCV/RISCVInstrInfo.cpp' l='73' c='_ZNK4llvm14RISCVInstrInfo18isStoreToStackSlotERKNS_12MachineInstrERi'/>
<use f='llvm/llvm/lib/Target/RISCV/RISCVInstrInfo.cpp' l='152' u='r' c='_ZNK4llvm14RISCVInstrInfo19storeRegToStackSlotERNS_17MachineBasicBlockENS_26MachineInstrBundleIteratorINS_12MachineInstrELb0EEENS_8RegisterEbiPKNS_19T7708132'/>
<use f='llvm/build/lib/Target/RISCV/RISCVGenGlobalISel.inc' l='11282' u='r' c='_ZNK12_GLOBAL__N_124RISCVInstructionSelector13getMatchTableEv'/>
<use f='llvm/build/lib/Target/RISCV/RISCVGenGlobalISel.inc' l='11342' u='r' c='_ZNK12_GLOBAL__N_124RISCVInstructionSelector13getMatchTableEv'/>
<use f='llvm/build/lib/Target/RISCV/RISCVGenGlobalISel.inc' l='11489' u='r' c='_ZNK12_GLOBAL__N_124RISCVInstructionSelector13getMatchTableEv'/>
<use f='llvm/build/lib/Target/RISCV/RISCVGenGlobalISel.inc' l='11527' u='r' c='_ZNK12_GLOBAL__N_124RISCVInstructionSelector13getMatchTableEv'/>
<use f='llvm/build/lib/Target/RISCV/RISCVGenGlobalISel.inc' l='11676' u='r' c='_ZNK12_GLOBAL__N_124RISCVInstructionSelector13getMatchTableEv'/>
<use f='llvm/build/lib/Target/RISCV/RISCVGenGlobalISel.inc' l='11736' u='r' c='_ZNK12_GLOBAL__N_124RISCVInstructionSelector13getMatchTableEv'/>
<use f='llvm/build/lib/Target/RISCV/RISCVGenGlobalISel.inc' l='11883' u='r' c='_ZNK12_GLOBAL__N_124RISCVInstructionSelector13getMatchTableEv'/>
<use f='llvm/build/lib/Target/RISCV/RISCVGenGlobalISel.inc' l='11921' u='r' c='_ZNK12_GLOBAL__N_124RISCVInstructionSelector13getMatchTableEv'/>
<use f='llvm/llvm/lib/Target/RISCV/RISCVMergeBaseOffset.cpp' l='224' c='_ZN12_GLOBAL__N_123RISCVMergeBaseOffsetOpt19detectAndFoldOffsetERN4llvm12MachineInstrES3_'/>
