<use f='llvm/llvm/include/llvm/ExecutionEngine/Orc/ThreadSafeModule.h' l='92' u='m' c='_ZN4llvm3orc16ThreadSafeModuleaSEOS1_'/>
<use f='llvm/llvm/include/llvm/ExecutionEngine/Orc/ThreadSafeModule.h' l='94' u='w' c='_ZN4llvm3orc16ThreadSafeModuleaSEOS1_'/>
<use f='llvm/llvm/include/llvm/ExecutionEngine/Orc/ThreadSafeModule.h' l='96' u='w' c='_ZN4llvm3orc16ThreadSafeModuleaSEOS1_'/>
<use f='llvm/llvm/include/llvm/ExecutionEngine/Orc/ThreadSafeModule.h' l='96' u='a' c='_ZN4llvm3orc16ThreadSafeModuleaSEOS1_'/>
<use f='llvm/llvm/include/llvm/ExecutionEngine/Orc/ThreadSafeModule.h' l='105' u='w' c='_ZN4llvm3orc16ThreadSafeModuleC1ESt10unique_ptrINS_6ModuleESt14default_deleteIS3_EES2_INS_11LLVMContextES4_IS7_EE'/>
<use f='llvm/llvm/include/llvm/ExecutionEngine/Orc/ThreadSafeModule.h' l='110' u='w' c='_ZN4llvm3orc16ThreadSafeModuleC1ESt10unique_ptrINS_6ModuleESt14default_deleteIS3_EENS0_17ThreadSafeContextE'/>
<use f='llvm/llvm/include/llvm/ExecutionEngine/Orc/ThreadSafeModule.h' l='114' u='m' c='_ZN4llvm3orc16ThreadSafeModuleD1Ev'/>
<use f='llvm/llvm/include/llvm/ExecutionEngine/Orc/ThreadSafeModule.h' l='116' u='w' c='_ZN4llvm3orc16ThreadSafeModuleD1Ev'/>
<use f='llvm/llvm/include/llvm/ExecutionEngine/Orc/ThreadSafeModule.h' l='123' u='m' c='_ZNK4llvm3orc16ThreadSafeModulecvbEv'/>
<use f='llvm/llvm/include/llvm/ExecutionEngine/Orc/ThreadSafeModule.h' l='136' u='m' c='_ZN4llvm3orc16ThreadSafeModule12withModuleDoEOT_'/>
<use f='llvm/llvm/include/llvm/ExecutionEngine/Orc/ThreadSafeModule.h' l='143' u='m' c='_ZNK4llvm3orc16ThreadSafeModule12withModuleDoEOT_'/>
<use f='llvm/llvm/include/llvm/ExecutionEngine/Orc/ThreadSafeModule.h' l='147' u='m' c='_ZN4llvm3orc16ThreadSafeModule17getModuleUnlockedEv'/>
<use f='llvm/llvm/include/llvm/ExecutionEngine/Orc/ThreadSafeModule.h' l='150' u='m' c='_ZNK4llvm3orc16ThreadSafeModule17getModuleUnlockedEv'/>
<dec f='llvm/llvm/include/llvm/ExecutionEngine/Orc/ThreadSafeModule.h' l='156' type='std::unique_ptr&lt;Module&gt;'/>
<offset>0</offset>
