<dec f='llvm/llvm/include/llvm/CodeGen/AsmPrinter.h' l='109' type='llvm::MachineLoopInfo *'/>
<offset>1280</offset>
<doc f='llvm/llvm/include/llvm/CodeGen/AsmPrinter.h' l='108'>/// This is a pointer to the current MachineLoopInfo.</doc>
<use f='llvm/llvm/lib/CodeGen/AsmPrinter/AsmPrinter.cpp' l='1175' u='w' c='_ZN4llvm10AsmPrinter16emitFunctionBodyEv'/>
<use f='llvm/llvm/lib/CodeGen/AsmPrinter/AsmPrinter.cpp' l='1176' u='r' c='_ZN4llvm10AsmPrinter16emitFunctionBodyEv'/>
<use f='llvm/llvm/lib/CodeGen/AsmPrinter/AsmPrinter.cpp' l='1179' u='w' c='_ZN4llvm10AsmPrinter16emitFunctionBodyEv'/>
<use f='llvm/llvm/lib/CodeGen/AsmPrinter/AsmPrinter.cpp' l='3188' u='r' c='_ZN4llvm10AsmPrinter19emitBasicBlockStartERKNS_17MachineBasicBlockE'/>
