<dec f='llvm/llvm/lib/Target/X86/X86.h' l='175' type='256'/>
<use f='llvm/llvm/lib/Target/X86/X86ISelDAGToDAG.cpp' l='1638' c='_ZN12_GLOBAL__N_115X86DAGToDAGISel18matchLoadInAddressEPN4llvm10LoadSDNodeERNS_18X86ISelAddressModeEb'/>
<use f='llvm/llvm/lib/Target/X86/X86ISelDAGToDAG.cpp' l='2497' u='r' c='_ZN12_GLOBAL__N_115X86DAGToDAGISel16selectVectorAddrEPN4llvm9MemSDNodeENS1_7SDValueES4_S4_RS4_S5_S5_S5_S5_'/>
<use f='llvm/llvm/lib/Target/X86/X86ISelDAGToDAG.cpp' l='2539' u='r' c='_ZN12_GLOBAL__N_115X86DAGToDAGISel10selectAddrEPN4llvm6SDNodeENS1_7SDValueERS4_S5_S5_S5_S5_'/>
<use f='llvm/llvm/lib/Target/X86/X86ISelLowering.cpp' l='2523' u='r' c='_ZNK4llvm17X86TargetLowering15getIRStackGuardERNS_9IRBuilderINS_14ConstantFolderENS_24IRBuilderDefaultInserterEEE'/>
