<dec f='llvm/llvm/include/llvm/IR/DebugInfoMetadata.h' l='1324' type='1'/>
<use f='llvm/clang/lib/Frontend/CompilerInvocation.cpp' l='1045' u='r' c='_ZN5clang18CompilerInvocation16ParseCodeGenArgsERNS_14CodeGenOptionsERN4llvm3opt7ArgListENS_9InputKindERNS_17DiagnosticsEngineERKNS3_6TripleERKNSt7__c13589808'/>
<use f='llvm/llvm/lib/CodeGen/AsmPrinter/DwarfCompileUnit.cpp' l='1264' c='_ZNK4llvm16DwarfCompileUnit19hasDwarfPubSectionsEv'/>
<use f='llvm/llvm/lib/CodeGen/AsmPrinter/DwarfDebug.cpp' l='2337' u='r' c='_ZN4llvm10DwarfDebug20emitDebugPubSectionsEv'/>
<use f='llvm/llvm/lib/IR/DebugInfoMetadata.cpp' l='770' u='a' c='_ZN4llvm13DICompileUnit16getNameTableKindENS_9StringRefE'/>
<use f='llvm/llvm/lib/IR/DebugInfoMetadata.cpp' l='789' c='_ZN4llvm13DICompileUnit19nameTableKindStringENS0_18DebugNameTableKindE'/>
