<dec f='llvm/build/lib/Target/PowerPC/PPCGenInstrInfo.inc' l='1100' type='1085'/>
<use f='llvm/build/lib/Target/PowerPC/PPCGenAsmMatcher.inc' l='6293'/>
<use f='llvm/llvm/lib/Target/PowerPC/PPCInstrInfo.h' l='137'/>
<use f='llvm/llvm/lib/Target/PowerPC/PPCInstrInfo.h' l='144'/>
<use f='llvm/llvm/lib/Target/PowerPC/PPCInstrInfo.h' l='151'/>
<use f='llvm/build/lib/Target/PowerPC/PPCGenMCCodeEmitter.inc' l='5000' c='_ZNK4llvm16PPCMCCodeEmitter21getBinaryCodeForInstrERKNS_6MCInstERNS_15SmallVectorImplINS_7MCFixupEEERKNS_15MCSubtargetInfoE'/>
<use f='llvm/llvm/lib/Target/PowerPC/PPCAsmPrinter.cpp' l='441' u='r' c='_ZN12_GLOBAL__N_113PPCAsmPrinter15LowerPATCHPOINTERN4llvm9StackMapsERKNS1_12MachineInstrE'/>
<use f='llvm/llvm/lib/Target/PowerPC/PPCAsmPrinter.cpp' l='446' u='r' c='_ZN12_GLOBAL__N_113PPCAsmPrinter15LowerPATCHPOINTERN4llvm9StackMapsERKNS1_12MachineInstrE'/>
<use f='llvm/llvm/lib/Target/PowerPC/PPCAsmPrinter.cpp' l='460' u='r' c='_ZN12_GLOBAL__N_113PPCAsmPrinter15LowerPATCHPOINTERN4llvm9StackMapsERKNS1_12MachineInstrE'/>
<use f='llvm/llvm/lib/Target/PowerPC/PPCAsmPrinter.cpp' l='789' u='r' c='_ZN12_GLOBAL__N_113PPCAsmPrinter15emitInstructionEPKN4llvm12MachineInstrE'/>
<use f='llvm/llvm/lib/Target/PowerPC/PPCAsmPrinter.cpp' l='918' u='r' c='_ZN12_GLOBAL__N_113PPCAsmPrinter15emitInstructionEPKN4llvm12MachineInstrE'/>
<use f='llvm/llvm/lib/Target/PowerPC/PPCAsmPrinter.cpp' l='988' u='r' c='_ZN12_GLOBAL__N_113PPCAsmPrinter15emitInstructionEPKN4llvm12MachineInstrE'/>
<use f='llvm/llvm/lib/Target/PowerPC/PPCAsmPrinter.cpp' l='1222' c='_ZN12_GLOBAL__N_113PPCAsmPrinter15emitInstructionEPKN4llvm12MachineInstrE'/>
<use f='llvm/llvm/lib/Target/PowerPC/PPCAsmPrinter.cpp' l='1598' u='r' c='_ZN12_GLOBAL__N_118PPCLinuxAsmPrinter21emitFunctionBodyStartEv'/>
<use f='llvm/llvm/lib/Target/PowerPC/PPCFastISel.cpp' l='494' u='r' c='_ZN12_GLOBAL__N_111PPCFastISel11PPCEmitLoadEN4llvm3MVTERNS1_8RegisterERNS_7AddressEPKNS1_19TargetRegisterClassEbj'/>
<use f='llvm/llvm/lib/Target/PowerPC/PPCFastISel.cpp' l='568' c='_ZN12_GLOBAL__N_111PPCFastISel11PPCEmitLoadEN4llvm3MVTERNS1_8RegisterERNS_7AddressEPKNS1_19TargetRegisterClassEbj'/>
<use f='llvm/llvm/lib/Target/PowerPC/PPCFrameLowering.cpp' l='1523' u='r' c='_ZNK4llvm16PPCFrameLowering12emitEpilogueERNS_15MachineFunctionERNS_17MachineBasicBlockE'/>
<use f='llvm/build/lib/Target/PowerPC/PPCGenDAGISel.inc' l='855' u='r' c='_ZN12_GLOBAL__N_115PPCDAGToDAGISel10SelectCodeEPN4llvm6SDNodeE'/>
<use f='llvm/build/lib/Target/PowerPC/PPCGenDAGISel.inc' l='855' u='r' c='_ZN12_GLOBAL__N_115PPCDAGToDAGISel10SelectCodeEPN4llvm6SDNodeE'/>
<use f='llvm/build/lib/Target/PowerPC/PPCGenDAGISel.inc' l='3918' u='r' c='_ZN12_GLOBAL__N_115PPCDAGToDAGISel10SelectCodeEPN4llvm6SDNodeE'/>
<use f='llvm/build/lib/Target/PowerPC/PPCGenDAGISel.inc' l='3918' u='r' c='_ZN12_GLOBAL__N_115PPCDAGToDAGISel10SelectCodeEPN4llvm6SDNodeE'/>
<use f='llvm/llvm/lib/Target/PowerPC/PPCISelDAGToDAG.cpp' l='6702' c='_ZN12_GLOBAL__N_115PPCDAGToDAGISel13PeepholePPC64Ev'/>
<use f='llvm/llvm/lib/Target/PowerPC/PPCISelLowering.cpp' l='11067' u='r' c='_ZNK4llvm17PPCTargetLowering17emitEHSjLjLongJmpERNS_12MachineInstrEPNS_17MachineBasicBlockE'/>
<use f='llvm/llvm/lib/Target/PowerPC/PPCISelLowering.cpp' l='11079' u='r' c='_ZNK4llvm17PPCTargetLowering17emitEHSjLjLongJmpERNS_12MachineInstrEPNS_17MachineBasicBlockE'/>
<use f='llvm/llvm/lib/Target/PowerPC/PPCISelLowering.cpp' l='11091' u='r' c='_ZNK4llvm17PPCTargetLowering17emitEHSjLjLongJmpERNS_12MachineInstrEPNS_17MachineBasicBlockE'/>
<use f='llvm/llvm/lib/Target/PowerPC/PPCISelLowering.cpp' l='11103' u='r' c='_ZNK4llvm17PPCTargetLowering17emitEHSjLjLongJmpERNS_12MachineInstrEPNS_17MachineBasicBlockE'/>
<use f='llvm/llvm/lib/Target/PowerPC/PPCISelLowering.cpp' l='11116' u='r' c='_ZNK4llvm17PPCTargetLowering17emitEHSjLjLongJmpERNS_12MachineInstrEPNS_17MachineBasicBlockE'/>
<use f='llvm/llvm/lib/Target/PowerPC/PPCISelLowering.cpp' l='12007' u='r' c='_ZNK4llvm17PPCTargetLowering27EmitInstrWithCustomInserterERNS_12MachineInstrEPNS_17MachineBasicBlockE'/>
<use f='llvm/llvm/lib/Target/PowerPC/PPCInstrInfo.cpp' l='3004' u='r' c='_ZNK4llvm12PPCInstrInfo18expandPostRAPseudoERNS_12MachineInstrE'/>
<use f='llvm/llvm/lib/Target/PowerPC/PPCInstrInfo.cpp' l='3047' u='r' c='_ZNK4llvm12PPCInstrInfo18expandPostRAPseudoERNS_12MachineInstrE'/>
<use f='llvm/llvm/lib/Target/PowerPC/PPCInstrInfo.cpp' l='4072' u='r' c='_ZNK4llvm12PPCInstrInfo15instrHasImmFormEjbRNS_12ImmInstrInfoEb'/>
<use f='llvm/llvm/lib/Target/PowerPC/PPCMacroFusion.cpp' l='128' u='r' c='_ZN12_GLOBAL__N_118checkOpConstraintsENS_13FusionFeature10FusionKindERKN4llvm12MachineInstrES5_'/>
<use f='llvm/llvm/lib/Target/PowerPC/PPCMacroFusion.def' l='42' u='r' c='_ZN12_GLOBAL__N_122shouldScheduleAdjacentERKN4llvm15TargetInstrInfoERKNS0_19TargetSubtargetInfoEPKNS0_12MachineInstrERS8_'/>
<use f='llvm/llvm/lib/Target/PowerPC/PPCPreEmitPeephole.cpp' l='69' c='_ZN12_GLOBAL__N_117hasPCRelativeFormERN4llvm12MachineInstrE'/>
<use f='llvm/llvm/lib/Target/PowerPC/PPCRegisterInfo.cpp' l='100' u='a' c='_ZN4llvm15PPCRegisterInfoC1ERKNS_16PPCTargetMachineE'/>
<use f='llvm/llvm/lib/Target/PowerPC/PPCRegisterInfo.cpp' l='588' u='r' c='_ZNK4llvm15PPCRegisterInfo20prepareDynamicAllocaENS_26MachineInstrBundleIteratorINS_12MachineInstrELb0EEERNS_8RegisterERbS5_'/>
<use f='llvm/llvm/lib/Target/PowerPC/PPCRegisterInfo.cpp' l='1090' c='_ZL23offsetMinAlignForOpcodej'/>
