<dec f='llvm/llvm/include/llvm/Passes/PassBuilder.h' l='143' type='llvm::TargetMachine *'/>
<offset>64</offset>
<use f='llvm/llvm/lib/Passes/PassBuilder.cpp' l='442' u='w' c='_ZN4llvm11PassBuilderC1EbPNS_13TargetMachineENS_21PipelineTuningOptionsENS_8OptionalINS_10PGOOptionsEEEPNS_28PassInstrumentationCallbacksE'/>
<use f='llvm/llvm/lib/Passes/PassRegistry.def' l='172' u='r' c='_ZN4llvm11PassBuilder24registerFunctionAnalysesERNS_15AnalysisManagerINS_8FunctionEJEEE'/>
<use f='llvm/llvm/lib/Passes/PassRegistry.def' l='172' u='r' c='_ZN4llvm11PassBuilder24registerFunctionAnalysesERNS_15AnalysisManagerINS_8FunctionEJEEE'/>
<use f='llvm/llvm/lib/Passes/PassBuilder.cpp' l='1008' u='r' c='_ZN4llvm11PassBuilder33buildModuleSimplificationPipelineENS0_17OptimizationLevelENS_18ThinOrFullLTOPhaseE'/>
<use f='llvm/llvm/lib/Passes/PassBuilder.cpp' l='1922' u='r' c='_ZN4llvm11PassBuilder22buildDefaultAAPipelineEv'/>
<use f='llvm/llvm/lib/Passes/PassBuilder.cpp' l='1923' u='r' c='_ZN4llvm11PassBuilder22buildDefaultAAPipelineEv'/>
<use f='llvm/llvm/lib/Passes/PassRegistry.def' l='105' u='r' c='_ZN4llvm11PassBuilder15parseModulePassERNS_11PassManagerINS_6ModuleENS_15AnalysisManagerIS2_JEEEJEEERKNS0_15PipelineElementE'/>
<use f='llvm/llvm/lib/Passes/PassRegistry.def' l='172' u='r' c='_ZN4llvm11PassBuilder17parseFunctionPassERNS_11PassManagerINS_8FunctionENS_15AnalysisManagerIS2_JEEEJEEERKNS0_15PipelineElementE'/>
<use f='llvm/llvm/lib/Passes/PassRegistry.def' l='172' u='r' c='_ZN4llvm11PassBuilder17parseFunctionPassERNS_11PassManagerINS_8FunctionENS_15AnalysisManagerIS2_JEEEJEEERKNS0_15PipelineElementE'/>
<use f='llvm/llvm/lib/Passes/PassRegistry.def' l='172' u='r' c='_ZN4llvm11PassBuilder17parseFunctionPassERNS_11PassManagerINS_8FunctionENS_15AnalysisManagerIS2_JEEEJEEERKNS0_15PipelineElementE'/>
<use f='llvm/llvm/lib/Passes/PassRegistry.def' l='172' u='r' c='_ZN4llvm11PassBuilder17parseFunctionPassERNS_11PassManagerINS_8FunctionENS_15AnalysisManagerIS2_JEEEJEEERKNS0_15PipelineElementE'/>
