<use f='llvm/llvm/include/llvm/CodeGen/SwitchLoweringUtils.h' l='257' u='w' c='_ZN4llvm8SwitchCG14SwitchLowering4initERKNS_14TargetLoweringERKNS_13TargetMachineERKNS_10DataLayoutE'/>
<dec f='llvm/llvm/include/llvm/CodeGen/SwitchLoweringUtils.h' l='297' type='const llvm::DataLayout *'/>
<offset>768</offset>
<use f='llvm/llvm/lib/CodeGen/SwitchLoweringUtils.cpp' l='229' u='r' c='_ZN4llvm8SwitchCG14SwitchLowering14buildJumpTableERKSt6vectorINS0_11CaseClusterESaIS3_EEjjPKNS_10SwitchInstEPNS_17MachineBasicBlockERS3_'/>
<use f='llvm/llvm/lib/CodeGen/SwitchLoweringUtils.cpp' l='285' u='r' c='_ZN4llvm8SwitchCG14SwitchLowering19findBitTestClustersERSt6vectorINS0_11CaseClusterESaIS3_EEPKNS_10SwitchInstE'/>
<use f='llvm/llvm/lib/CodeGen/SwitchLoweringUtils.cpp' l='317' u='r' c='_ZN4llvm8SwitchCG14SwitchLowering19findBitTestClustersERSt6vectorINS0_11CaseClusterESaIS3_EEPKNS_10SwitchInstE'/>
<use f='llvm/llvm/lib/CodeGen/SwitchLoweringUtils.cpp' l='385' u='r' c='_ZN4llvm8SwitchCG14SwitchLowering13buildBitTestsERSt6vectorINS0_11CaseClusterESaIS3_EEjjPKNS_10SwitchInstERS3_'/>
<use f='llvm/llvm/lib/CodeGen/SwitchLoweringUtils.cpp' l='391' u='r' c='_ZN4llvm8SwitchCG14SwitchLowering13buildBitTestsERSt6vectorINS0_11CaseClusterESaIS3_EEjjPKNS_10SwitchInstERS3_'/>
