<dec f='llvm/llvm/include/llvm/XRay/Graph.h' l='207' type='llvm::xray::Graph::InOutEdgeView::InternalEdgeMapT &amp;'/>
<use f='llvm/llvm/include/llvm/XRay/Graph.h' l='216' c='_ZN4llvm4xray5Graph13InOutEdgeView5beginEv'/>
<use f='llvm/llvm/include/llvm/XRay/Graph.h' l='223' c='_ZNK4llvm4xray5Graph13InOutEdgeView6cbeginEv'/>
<use f='llvm/llvm/include/llvm/XRay/Graph.h' l='232' c='_ZN4llvm4xray5Graph13InOutEdgeView3endEv'/>
<use f='llvm/llvm/include/llvm/XRay/Graph.h' l='238' c='_ZNK4llvm4xray5Graph13InOutEdgeView4cendEv'/>
<use f='llvm/llvm/include/llvm/XRay/Graph.h' l='254' u='w' c='_ZN4llvm4xray5Graph13InOutEdgeViewC1ERNSt11conditionalIXTL0__EKNS0_5GraphIT_T0_T1_EES9_E4typeES7_'/>
