<dec f='llvm/build/lib/Target/BPF/BPFGenRegisterInfo.inc' l='24' type='4'/>
<use f='llvm/build/lib/Target/BPF/BPFGenAsmMatcher.inc' l='676' c='_ZL20validateOperandClassRN4llvm18MCParsedAsmOperandEN12_GLOBAL__N_114MatchClassKindE'/>
<use f='llvm/build/lib/Target/BPF/BPFGenCallingConv.inc' l='32' u='r' c='_ZL8CC_BPF32jN4llvm3MVTES0_NS_11CCValAssign7LocInfoENS_3ISD10ArgFlagsTyERNS_7CCStateE'/>
<use f='llvm/build/lib/Target/BPF/BPFGenCallingConv.inc' l='42' u='r' c='_ZL8CC_BPF32jN4llvm3MVTES0_NS_11CCValAssign7LocInfoENS_3ISD10ArgFlagsTyERNS_7CCStateE'/>
<use f='llvm/build/lib/Target/BPF/BPFGenCallingConv.inc' l='79' u='r' c='_ZL8CC_BPF64jN4llvm3MVTES0_NS_11CCValAssign7LocInfoENS_3ISD10ArgFlagsTyERNS_7CCStateE'/>
<use f='llvm/llvm/lib/Target/BPF/Disassembler/BPFDisassembler.cpp' l='97'/>
