<use f='llvm/llvm/include/llvm/Support/YAMLTraits.h' l='315'/>
<use f='llvm/llvm/include/llvm/Support/YAMLTraits.h' l='331'/>
<use f='llvm/llvm/include/llvm/Support/YAMLTraits.h' l='400'/>
<use f='llvm/llvm/include/llvm/Support/YAMLTraits.h' l='414'/>
<use f='llvm/llvm/include/llvm/Support/YAMLTraits.h' l='426'/>
<use f='llvm/llvm/include/llvm/Support/YAMLTraits.h' l='440'/>
<use f='llvm/llvm/include/llvm/Support/YAMLTraits.h' l='454'/>
<use f='llvm/llvm/include/llvm/Support/YAMLTraits.h' l='469'/>
<use f='llvm/llvm/include/llvm/Support/YAMLTraits.h' l='518'/>
<def f='llvm/llvm/include/llvm/Support/YAMLTraits.h' l='751' ll='940'/>
<use f='llvm/llvm/include/llvm/Support/YAMLTraits.h' l='945' c='_ZN4llvm4yaml6detail9doMappingERNS0_2IOERT_RT0_'/>
<use f='llvm/llvm/include/llvm/Support/YAMLTraits.h' l='949' c='_ZN4llvm4yaml6detail9doMappingERNS0_2IOERT_RNS0_12EmptyContextE'/>
<use f='llvm/llvm/include/llvm/Support/YAMLTraits.h' l='957' c='_ZN4llvm4yaml7yamlizeERNS0_2IOERT_bRNS0_12EmptyContextE'/>
<use f='llvm/llvm/include/llvm/Support/YAMLTraits.h' l='965' c='_ZN4llvm4yaml7yamlizeERNS0_2IOERT_bRNS0_12EmptyContextE'/>
<use f='llvm/llvm/include/llvm/Support/YAMLTraits.h' l='976' c='_ZN4llvm4yaml7yamlizeERNS0_2IOERT_bRNS0_12EmptyContextE'/>
<use f='llvm/llvm/include/llvm/Support/YAMLTraits.h' l='997' c='_ZN4llvm4yaml7yamlizeERNS0_2IOERT_bRNS0_12EmptyContextE'/>
<use f='llvm/llvm/include/llvm/Support/YAMLTraits.h' l='1016' c='_ZN4llvm4yaml7yamlizeERNS0_2IOERT_bRNS0_12EmptyContextE'/>
<use f='llvm/llvm/include/llvm/Support/YAMLTraits.h' l='1041' c='_ZN4llvm4yaml7yamlizeERNS0_2IOERT_bRT0_'/>
<use f='llvm/llvm/include/llvm/Support/YAMLTraits.h' l='1067' c='_ZN4llvm4yaml7yamlizeERNS0_2IOERT_bRT0_'/>
<use f='llvm/llvm/include/llvm/Support/YAMLTraits.h' l='1081' c='_ZN4llvm4yaml7yamlizeERNS0_2IOERT_bRNS0_12EmptyContextE'/>
<use f='llvm/llvm/include/llvm/Support/YAMLTraits.h' l='1096' c='_ZN4llvm4yaml7yamlizeERNS0_2IOERT_bRNS0_12EmptyContextE'/>
<use f='llvm/llvm/include/llvm/Support/YAMLTraits.h' l='1110' c='_ZN4llvm4yaml7yamlizeERNS0_2IOERT_bRNS0_12EmptyContextE'/>
<use f='llvm/llvm/include/llvm/Support/YAMLTraits.h' l='1116' c='_ZN4llvm4yaml7yamlizeERNS0_2IOERT_bRT0_'/>
<use f='llvm/llvm/include/llvm/Support/YAMLTraits.h' l='1270' c='_ZN4llvm4yaml23ScalarEnumerationTraitsINS_7support6detail31packed_endian_specific_integralIT_XT0_EXT1_EXsr13PickAlignmentIS5_XT1_EEE5valueEEENSt9enabl4134484'/>
<use f='llvm/llvm/include/llvm/Support/YAMLTraits.h' l='1285' c='_ZN4llvm4yaml18ScalarBitSetTraitsINS_7support6detail31packed_endian_specific_integralIT_XT0_EXT1_EXsr13PickAlignmentIS5_XT1_EEE5valueEEENSt9enable_ifI9848273'/>
<use f='llvm/llvm/include/llvm/Support/YAMLTraits.h' l='1296' c='_ZN4llvm4yaml20MappingNormalizationC1ERNS0_2IOERT0_'/>
<use f='llvm/llvm/include/llvm/Support/YAMLTraits.h' l='1319'/>
<use f='llvm/llvm/include/llvm/Support/YAMLTraits.h' l='1328' c='_ZN4llvm4yaml24MappingNormalizationHeapC1ERNS0_2IOERT0_PNS_20BumpPtrAllocatorImplINS_15MallocAllocatorELm4096ELm4096ELm128EEE'/>
<use f='llvm/llvm/include/llvm/Support/YAMLTraits.h' l='1356'/>
<ovr f='llvm/llvm/include/llvm/Support/YAMLTraits.h' l='1373' c='llvm::yaml::Input'/>
<use f='llvm/llvm/include/llvm/Support/YAMLTraits.h' l='1373'/>
<ovr f='llvm/llvm/include/llvm/Support/YAMLTraits.h' l='1536' c='llvm::yaml::Output'/>
<use f='llvm/llvm/include/llvm/Support/YAMLTraits.h' l='1536'/>
<use f='llvm/llvm/include/llvm/Support/YAMLTraits.h' l='1910' c='_ZN4llvm4yaml18SequenceTraitsImpl4sizeERNS0_2IOERT_'/>
<use f='llvm/llvm/include/llvm/Support/YAMLTraits.h' l='1912' c='_ZN4llvm4yaml18SequenceTraitsImpl7elementERNS0_2IOERT_m'/>
<use f='llvm/llvm/include/llvm/Support/YAMLTraits.h' l='1963' c='_ZN4llvm4yaml35StdMapStringCustomMappingTraitsImpl8inputOneERNS0_2IOENS_9StringRefERSt3mapINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEET_St4le13306843'/>
<use f='llvm/llvm/include/llvm/Support/YAMLTraits.h' l='1967' c='_ZN4llvm4yaml35StdMapStringCustomMappingTraitsImpl6outputERNS0_2IOERSt3mapINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEET_St4lessISA_ESaISt4pairIKSA_SB_EEE'/>
<use f='llvm/lldb/include/lldb/Utility/FileSpec.h' l='447' c='_ZN4llvm4yaml23ScalarEnumerationTraitsIN12lldb_private13FileSpecStyleEvE11enumerationERNS0_2IOERS3_'/>
<use f='llvm/lldb/include/lldb/Utility/FileSpec.h' l='451' c='_ZN4llvm4yaml13MappingTraitsIN12lldb_private8FileSpecEE7mappingERNS0_2IOERS3_'/>
<size>16</size>
<doc f='llvm/llvm/include/llvm/Support/YAMLTraits.h' l='750'>// Base class for Input and Output.</doc>
<fun r='_ZN4llvm4yaml2IOC1EPv'/>
<fun r='_ZN4llvm4yaml2IOD1Ev'/>
<fun r='_ZNK4llvm4yaml2IO10outputtingEv'/>
<fun r='_ZN4llvm4yaml2IO13beginSequenceEv'/>
<fun r='_ZN4llvm4yaml2IO16preflightElementEjRPv'/>
<fun r='_ZN4llvm4yaml2IO17postflightElementEPv'/>
<fun r='_ZN4llvm4yaml2IO11endSequenceEv'/>
<fun r='_ZN4llvm4yaml2IO21canElideEmptySequenceEv'/>
<fun r='_ZN4llvm4yaml2IO17beginFlowSequenceEv'/>
<fun r='_ZN4llvm4yaml2IO20preflightFlowElementEjRPv'/>
<fun r='_ZN4llvm4yaml2IO21postflightFlowElementEPv'/>
<fun r='_ZN4llvm4yaml2IO15endFlowSequenceEv'/>
<fun r='_ZN4llvm4yaml2IO6mapTagENS_9StringRefEb'/>
<fun r='_ZN4llvm4yaml2IO12beginMappingEv'/>
<fun r='_ZN4llvm4yaml2IO10endMappingEv'/>
<fun r='_ZN4llvm4yaml2IO12preflightKeyEPKcbbRbRPv'/>
<fun r='_ZN4llvm4yaml2IO13postflightKeyEPv'/>
<fun r='_ZN4llvm4yaml2IO4keysEv'/>
<fun r='_ZN4llvm4yaml2IO16beginFlowMappingEv'/>
<fun r='_ZN4llvm4yaml2IO14endFlowMappingEv'/>
<fun r='_ZN4llvm4yaml2IO15beginEnumScalarEv'/>
<fun r='_ZN4llvm4yaml2IO15matchEnumScalarEPKcb'/>
<fun r='_ZN4llvm4yaml2IO17matchEnumFallbackEv'/>
<fun r='_ZN4llvm4yaml2IO13endEnumScalarEv'/>
<fun r='_ZN4llvm4yaml2IO17beginBitSetScalarERb'/>
<fun r='_ZN4llvm4yaml2IO11bitSetMatchEPKcb'/>
<fun r='_ZN4llvm4yaml2IO15endBitSetScalarEv'/>
<fun r='_ZN4llvm4yaml2IO12scalarStringERNS_9StringRefENS0_11QuotingTypeE'/>
<fun r='_ZN4llvm4yaml2IO17blockScalarStringERNS_9StringRefE'/>
<fun r='_ZN4llvm4yaml2IO9scalarTagERNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE'/>
<fun r='_ZN4llvm4yaml2IO11getNodeKindEv'/>
<fun r='_ZN4llvm4yaml2IO8setErrorERKNS_5TwineE'/>
<fun r='_ZN4llvm4yaml2IO19setAllowUnknownKeysEb'/>
<fun r='_ZN4llvm4yaml2IO8enumCaseERT_PKcS2_'/>
<fun r='_ZN4llvm4yaml2IO8enumCaseERT_PKcj'/>
<fun r='_ZN4llvm4yaml2IO12enumFallbackERT0_'/>
<fun r='_ZN4llvm4yaml2IO10bitSetCaseERT_PKcS2_'/>
<fun r='_ZN4llvm4yaml2IO10bitSetCaseERT_PKcj'/>
<fun r='_ZN4llvm4yaml2IO16maskedBitSetCaseERT_PKcS2_S2_'/>
<fun r='_ZN4llvm4yaml2IO16maskedBitSetCaseERT_PKcjj'/>
<fun r='_ZNK4llvm4yaml2IO10getContextEv'/>
<fun r='_ZN4llvm4yaml2IO10setContextEPv'/>
<fun r='_ZN4llvm4yaml2IO11mapRequiredEPKcRT_'/>
<fun r='_ZN4llvm4yaml2IO11mapRequiredEPKcRT_RT0_'/>
<fun r='_ZN4llvm4yaml2IO11mapOptionalEPKcRT_'/>
<fun r='_ZN4llvm4yaml2IO11mapOptionalEPKcRT_RKT0_'/>
<fun r='_ZN4llvm4yaml2IO22mapOptionalWithContextEPKcRT_RT0_'/>
<fun r='_ZN4llvm4yaml2IO22mapOptionalWithContextEPKcRNS_8OptionalIT_EERT0_'/>
<fun r='_ZN4llvm4yaml2IO22mapOptionalWithContextEPKcRT_RT0_'/>
<fun r='_ZN4llvm4yaml2IO22mapOptionalWithContextEPKcRT_RKT1_RT0_'/>
<fun r='_ZN4llvm4yaml2IO21processKeyWithDefaultEPKcRNS_8OptionalIT_EERKS6_bRT0_'/>
<fun r='_ZN4llvm4yaml2IO21processKeyWithDefaultEPKcRT_RKS4_bRT0_'/>
<fun r='_ZN4llvm4yaml2IO10processKeyEPKcRT_bRT0_'/>
<mbr r='llvm::yaml::IO::Ctxt' o='64' t='void *'/>
<fun r='_ZN4llvm4yaml2IO21processKeyWithDefaultEPKcRNS_8OptionalIT_EERKS6_bRT0_'/>
<use f='llvm/clang/lib/APINotes/APINotesYAMLCompiler.cpp' l='41' c='_ZN4llvm4yaml23ScalarEnumerationTraitsIN12_GLOBAL__N_115APIAvailabilityEvE11enumerationERNS0_2IOERS3_'/>
<use f='llvm/clang/lib/APINotes/APINotesYAMLCompiler.cpp' l='62' c='_ZN4llvm4yaml23ScalarEnumerationTraitsIN12_GLOBAL__N_110MethodKindEvE11enumerationERNS0_2IOERS3_'/>
<use f='llvm/clang/lib/APINotes/APINotesYAMLCompiler.cpp' l='88' c='_ZN4llvm4yaml23ScalarEnumerationTraitsIN5clang15NullabilityKindEvE11enumerationERNS0_2IOERS3_'/>
<use f='llvm/clang/lib/APINotes/APINotesYAMLCompiler.cpp' l='106' c='_ZN4llvm4yaml23ScalarEnumerationTraitsIN5clang9api_notes25RetainCountConventionKindEvE11enumerationERNS0_2IOERS4_'/>
<use f='llvm/clang/lib/APINotes/APINotesYAMLCompiler.cpp' l='120' c='_ZN4llvm4yaml13MappingTraitsIN12_GLOBAL__N_15ParamEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/clang/lib/APINotes/APINotesYAMLCompiler.cpp' l='173' c='_ZN4llvm4yaml23ScalarEnumerationTraitsIN12_GLOBAL__N_117FactoryAsInitKindEvE11enumerationERNS0_2IOERS3_'/>
<use f='llvm/clang/lib/APINotes/APINotesYAMLCompiler.cpp' l='181' c='_ZN4llvm4yaml13MappingTraitsIN12_GLOBAL__N_16MethodEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/clang/lib/APINotes/APINotesYAMLCompiler.cpp' l='222' c='_ZN4llvm4yaml13MappingTraitsIN12_GLOBAL__N_18PropertyEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/clang/lib/APINotes/APINotesYAMLCompiler.cpp' l='261' c='_ZN4llvm4yaml13MappingTraitsIN12_GLOBAL__N_15ClassEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/clang/lib/APINotes/APINotesYAMLCompiler.cpp' l='302' c='_ZN4llvm4yaml13MappingTraitsIN12_GLOBAL__N_18FunctionEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/clang/lib/APINotes/APINotesYAMLCompiler.cpp' l='337' c='_ZN4llvm4yaml13MappingTraitsIN12_GLOBAL__N_114GlobalVariableEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/clang/lib/APINotes/APINotesYAMLCompiler.cpp' l='367' c='_ZN4llvm4yaml13MappingTraitsIN12_GLOBAL__N_112EnumConstantEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/clang/lib/APINotes/APINotesYAMLCompiler.cpp' l='396' c='_ZN4llvm4yaml23ScalarEnumerationTraitsIN12_GLOBAL__N_124EnumConvenienceAliasKindEvE11enumerationERNS0_2IOERS3_'/>
<use f='llvm/clang/lib/APINotes/APINotesYAMLCompiler.cpp' l='430' c='_ZN4llvm4yaml23ScalarEnumerationTraitsIN5clang9api_notes21EnumExtensibilityKindEvE11enumerationERNS0_2IOERS4_'/>
<use f='llvm/clang/lib/APINotes/APINotesYAMLCompiler.cpp' l='438' c='_ZN4llvm4yaml13MappingTraitsIN12_GLOBAL__N_13TagEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/clang/lib/APINotes/APINotesYAMLCompiler.cpp' l='474' c='_ZN4llvm4yaml23ScalarEnumerationTraitsIN5clang9api_notes16SwiftNewTypeKindEvE11enumerationERNS0_2IOERS4_'/>
<use f='llvm/clang/lib/APINotes/APINotesYAMLCompiler.cpp' l='482' c='_ZN4llvm4yaml13MappingTraitsIN12_GLOBAL__N_17TypedefEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/clang/lib/APINotes/APINotesYAMLCompiler.cpp' l='511' c='_ZN4llvm4yamlL16mapTopLevelItemsERNS0_2IOERN12_GLOBAL__N_113TopLevelItemsE'/>
<use f='llvm/clang/lib/APINotes/APINotesYAMLCompiler.cpp' l='537' c='_ZN4llvm4yaml13MappingTraitsIN12_GLOBAL__N_19VersionedEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/clang/lib/APINotes/APINotesYAMLCompiler.cpp' l='561' c='_ZN4llvm4yaml13MappingTraitsIN12_GLOBAL__N_16ModuleEE7mappingERNS0_2IOERS3_'/>
<size>16</size>
<use f='llvm/clang/include/clang/Tooling/Inclusions/IncludeStyle.h' l='162' c='_ZN4llvm4yaml13MappingTraitsIN5clang7tooling12IncludeStyle15IncludeCategoryEE7mappingERNS0_2IOERS5_'/>
<use f='llvm/clang/include/clang/Tooling/Inclusions/IncludeStyle.h' l='170' c='_ZN4llvm4yaml23ScalarEnumerationTraitsIN5clang7tooling12IncludeStyle18IncludeBlocksStyleEvE11enumerationERNS0_2IOERS5_'/>
<size>16</size>
<use f='llvm/clang/lib/Format/Format.cpp' l='57' c='_ZN4llvm4yaml23ScalarEnumerationTraitsIN5clang6format11FormatStyle12LanguageKindEvE11enumerationERNS0_2IOERS5_'/>
<use f='llvm/clang/lib/Format/Format.cpp' l='70' c='_ZN4llvm4yaml23ScalarEnumerationTraitsIN5clang6format11FormatStyle16LanguageStandardEvE11enumerationERNS0_2IOERS5_'/>
<use f='llvm/clang/lib/Format/Format.cpp' l='89' c='_ZN4llvm4yaml23ScalarEnumerationTraitsIN5clang6format11FormatStyle11UseTabStyleEvE11enumerationERNS0_2IOERS5_'/>
<use f='llvm/clang/lib/Format/Format.cpp' l='102' c='_ZN4llvm4yaml23ScalarEnumerationTraitsIN5clang6format11FormatStyle20JavaScriptQuoteStyleEvE11enumerationERNS0_2IOERS5_'/>
<use f='llvm/clang/lib/Format/Format.cpp' l='110' c='_ZN4llvm4yaml23ScalarEnumerationTraitsIN5clang6format11FormatStyle15ShortBlockStyleEvE11enumerationERNS0_2IOERS5_'/>
<use f='llvm/clang/lib/Format/Format.cpp' l='120' c='_ZN4llvm4yaml23ScalarEnumerationTraitsIN5clang6format11FormatStyle18ShortFunctionStyleEvE11enumerationERNS0_2IOERS5_'/>
<use f='llvm/clang/lib/Format/Format.cpp' l='132' c='_ZN4llvm4yaml23ScalarEnumerationTraitsIN5clang6format11FormatStyle21AlignConsecutiveStyleEvE11enumerationERNS0_2IOERS5_'/>
<use f='llvm/clang/lib/Format/Format.cpp' l='147' c='_ZN4llvm4yaml23ScalarEnumerationTraitsIN5clang6format11FormatStyle12ShortIfStyleEvE11enumerationERNS0_2IOERS5_'/>
<use f='llvm/clang/lib/Format/Format.cpp' l='159' c='_ZN4llvm4yaml23ScalarEnumerationTraitsIN5clang6format11FormatStyle16ShortLambdaStyleEvE11enumerationERNS0_2IOERS5_'/>
<use f='llvm/clang/lib/Format/Format.cpp' l='170' c='_ZN4llvm4yaml23ScalarEnumerationTraitsIN5clang6format11FormatStyle12BinPackStyleEvE11enumerationERNS0_2IOERS5_'/>
<use f='llvm/clang/lib/Format/Format.cpp' l='178' c='_ZN4llvm4yaml23ScalarEnumerationTraitsIN5clang6format11FormatStyle18TrailingCommaStyleEvE11enumerationERNS0_2IOERS5_'/>
<use f='llvm/clang/lib/Format/Format.cpp' l='185' c='_ZN4llvm4yaml23ScalarEnumerationTraitsIN5clang6format11FormatStyle19BinaryOperatorStyleEvE11enumerationERNS0_2IOERS5_'/>
<use f='llvm/clang/lib/Format/Format.cpp' l='195' c='_ZN4llvm4yaml23ScalarEnumerationTraitsIN5clang6format11FormatStyle18BraceBreakingStyleEvE11enumerationERNS0_2IOERS5_'/>
<use f='llvm/clang/lib/Format/Format.cpp' l='212' c='_ZN4llvm4yaml23ScalarEnumerationTraitsIN5clang6format11FormatStyle39BraceWrappingAfterControlStatementStyleEvE11enumerationERNS0_2IOERS5_'/>
<use f='llvm/clang/lib/Format/Format.cpp' l='227' c='_ZN4llvm4yaml23ScalarEnumerationTraitsIN5clang6format11FormatStyle33BreakConstructorInitializersStyleEvE11enumerationERNS0_2IOERS5_'/>
<use f='llvm/clang/lib/Format/Format.cpp' l='236' c='_ZN4llvm4yaml23ScalarEnumerationTraitsIN5clang6format11FormatStyle25BreakInheritanceListStyleEvE11enumerationERNS0_2IOERS5_'/>
<use f='llvm/clang/lib/Format/Format.cpp' l='248' c='_ZN4llvm4yaml23ScalarEnumerationTraitsIN5clang6format11FormatStyle34EmptyLineBeforeAccessModifierStyleEvE11enumerationERNS0_2IOERS5_'/>
<use f='llvm/clang/lib/Format/Format.cpp' l='258' c='_ZN4llvm4yaml23ScalarEnumerationTraitsIN5clang6format11FormatStyle22PPDirectiveIndentStyleEvE11enumerationERNS0_2IOERS5_'/>
<use f='llvm/clang/lib/Format/Format.cpp' l='267' c='_ZN4llvm4yaml23ScalarEnumerationTraitsIN5clang6format11FormatStyle22IndentExternBlockStyleEvE11enumerationERNS0_2IOERS5_'/>
<use f='llvm/clang/lib/Format/Format.cpp' l='278' c='_ZN4llvm4yaml23ScalarEnumerationTraitsIN5clang6format11FormatStyle23ReturnTypeBreakingStyleEvE11enumerationERNS0_2IOERS5_'/>
<use f='llvm/clang/lib/Format/Format.cpp' l='290' c='_ZN4llvm4yaml23ScalarEnumerationTraitsIN5clang6format11FormatStyle30BreakTemplateDeclarationsStyleEvE11enumerationERNS0_2IOERS5_'/>
<use f='llvm/clang/lib/Format/Format.cpp' l='305' c='_ZN4llvm4yaml23ScalarEnumerationTraitsIN5clang6format11FormatStyle33DefinitionReturnTypeBreakingStyleEvE11enumerationERNS0_2IOERS5_'/>
<use f='llvm/clang/lib/Format/Format.cpp' l='318' c='_ZN4llvm4yaml23ScalarEnumerationTraitsIN5clang6format11FormatStyle24NamespaceIndentationKindEvE11enumerationERNS0_2IOERS5_'/>
<use f='llvm/clang/lib/Format/Format.cpp' l='327' c='_ZN4llvm4yaml23ScalarEnumerationTraitsIN5clang6format11FormatStyle21BracketAlignmentStyleEvE11enumerationERNS0_2IOERS5_'/>
<use f='llvm/clang/lib/Format/Format.cpp' l='340' c='_ZN4llvm4yaml23ScalarEnumerationTraitsIN5clang6format11FormatStyle28EscapedNewlineAlignmentStyleEvE11enumerationERNS0_2IOERS5_'/>
<use f='llvm/clang/lib/Format/Format.cpp' l='353' c='_ZN4llvm4yaml23ScalarEnumerationTraitsIN5clang6format11FormatStyle21OperandAlignmentStyleEvE11enumerationERNS0_2IOERS5_'/>
<use f='llvm/clang/lib/Format/Format.cpp' l='366' c='_ZN4llvm4yaml23ScalarEnumerationTraitsIN5clang6format11FormatStyle21PointerAlignmentStyleEvE11enumerationERNS0_2IOERS5_'/>
<use f='llvm/clang/lib/Format/Format.cpp' l='380' c='_ZN4llvm4yaml23ScalarEnumerationTraitsIN5clang6format11FormatStyle33SpaceAroundPointerQualifiersStyleEvE11enumerationERNS0_2IOERS5_'/>
<use f='llvm/clang/lib/Format/Format.cpp' l='390' c='_ZN4llvm4yaml23ScalarEnumerationTraitsIN5clang6format11FormatStyle24SpaceBeforeParensOptionsEvE11enumerationERNS0_2IOERS5_'/>
<use f='llvm/clang/lib/Format/Format.cpp' l='409' c='_ZN4llvm4yaml23ScalarEnumerationTraitsIN5clang6format11FormatStyle25BitFieldColonSpacingStyleEvE11enumerationERNS0_2IOERS5_'/>
<use f='llvm/clang/lib/Format/Format.cpp' l='420' c='_ZN4llvm4yaml23ScalarEnumerationTraitsIN5clang6format11FormatStyle27SortJavaStaticImportOptionsEvE11enumerationERNS0_2IOERS5_'/>
<use f='llvm/clang/lib/Format/Format.cpp' l='428' c='_ZN4llvm4yaml13MappingTraitsIN5clang6format11FormatStyleEE7mappingERNS0_2IOERS4_'/>
<use f='llvm/clang/lib/Format/Format.cpp' l='681' c='_ZN4llvm4yaml13MappingTraitsIN5clang6format11FormatStyle18BraceWrappingFlagsEE7mappingERNS0_2IOERS5_'/>
<use f='llvm/clang/lib/Format/Format.cpp' l='704' c='_ZN4llvm4yaml13MappingTraitsIN5clang6format11FormatStyle15RawStringFormatEE7mappingERNS0_2IOERS5_'/>
<use f='llvm/clang/lib/Format/Format.cpp' l='719' c='_ZN4llvm4yaml18DocumentListTraitsISt6vectorIN5clang6format11FormatStyleESaIS5_EEE4sizeERNS0_2IOERS7_'/>
<use f='llvm/clang/lib/Format/Format.cpp' l='722' c='_ZN4llvm4yaml18DocumentListTraitsISt6vectorIN5clang6format11FormatStyleESaIS5_EEE7elementERNS0_2IOERS7_m'/>
<size>16</size>
<use f='llvm/clang/lib/Frontend/FrontendActions.cpp' l='365' c='_ZN4llvm4yaml13MappingTraitsIN12_GLOBAL__N_114TemplightEntryEE7mappingERNS0_2IOERS3_'/>
<size>16</size>
<use f='llvm/clang/lib/StaticAnalyzer/Checkers/GenericTaintChecker.cpp' l='318' c='_ZN4llvm4yaml13MappingTraitsIN12_GLOBAL__N_119GenericTaintChecker18TaintConfigurationEE7mappingERNS0_2IOERS4_'/>
<use f='llvm/clang/lib/StaticAnalyzer/Checkers/GenericTaintChecker.cpp' l='326' c='_ZN4llvm4yaml13MappingTraitsIN12_GLOBAL__N_119GenericTaintChecker18TaintConfiguration11PropagationEE7mappingERNS0_2IOERS5_'/>
<use f='llvm/clang/lib/StaticAnalyzer/Checkers/GenericTaintChecker.cpp' l='339' c='_ZN4llvm4yaml23ScalarEnumerationTraitsIN12_GLOBAL__N_119GenericTaintChecker12VariadicTypeEvE11enumerationERNS0_2IOERS4_'/>
<use f='llvm/clang/lib/StaticAnalyzer/Checkers/GenericTaintChecker.cpp' l='347' c='_ZN4llvm4yaml13MappingTraitsISt5tupleIJNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES8_NS_11SmallVectorIjLj2EEEEEE7mappingERNS0_2IOERSB_'/>
<size>16</size>
<use f='llvm/clang/lib/Tooling/Inclusions/IncludeStyle.cpp' l='17' c='_ZN4llvm4yaml13MappingTraitsIN5clang7tooling12IncludeStyle15IncludeCategoryEE7mappingERNS0_2IOERS5_'/>
<use f='llvm/clang/lib/Tooling/Inclusions/IncludeStyle.cpp' l='25' c='_ZN4llvm4yaml23ScalarEnumerationTraitsIN5clang7tooling12IncludeStyle18IncludeBlocksStyleEvE11enumerationERNS0_2IOERS5_'/>
<size>16</size>
<use f='llvm/clang/include/clang/Tooling/ReplacementsYaml.h' l='33' c='_ZN4llvm4yaml13MappingTraitsIN5clang7tooling11ReplacementEE21NormalizedReplacementC1ERKNS0_2IOE'/>
<use f='llvm/clang/include/clang/Tooling/ReplacementsYaml.h' l='36' c='_ZN4llvm4yaml13MappingTraitsIN5clang7tooling11ReplacementEE21NormalizedReplacementC1ERKNS0_2IOERKS4_'/>
<use f='llvm/clang/include/clang/Tooling/ReplacementsYaml.h' l='40' c='_ZN4llvm4yaml13MappingTraitsIN5clang7tooling11ReplacementEE21NormalizedReplacement11denormalizeERKNS0_2IOE'/>
<use f='llvm/clang/include/clang/Tooling/ReplacementsYaml.h' l='51' c='_ZN4llvm4yaml13MappingTraitsIN5clang7tooling11ReplacementEE7mappingERNS0_2IOERS4_'/>
<use f='llvm/clang/include/clang/Tooling/ReplacementsYaml.h' l='64' c='_ZN4llvm4yaml13MappingTraitsIN5clang7tooling27TranslationUnitReplacementsEE7mappingERNS0_2IOERS4_'/>
<use f='llvm/clang/lib/Tooling/Refactoring/AtomicChange.cpp' l='24' c='_ZN12_GLOBAL__N_122NormalizedAtomicChangeC1ERKN4llvm4yaml2IOE'/>
<use f='llvm/clang/lib/Tooling/Refactoring/AtomicChange.cpp' l='28' c='_ZN12_GLOBAL__N_122NormalizedAtomicChangeC1ERKN4llvm4yaml2IOERKN5clang7tooling12AtomicChangeE'/>
<use f='llvm/clang/lib/Tooling/Refactoring/AtomicChange.cpp' l='36' c='_ZN12_GLOBAL__N_122NormalizedAtomicChange11denormalizeERKN4llvm4yaml2IOE'/>
<use f='llvm/clang/lib/Tooling/Refactoring/AtomicChange.cpp' l='55' c='_ZN4llvm4yaml13MappingTraitsIN12_GLOBAL__N_122NormalizedAtomicChangeEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/clang/lib/Tooling/Refactoring/AtomicChange.cpp' l='68' c='_ZN4llvm4yaml13MappingTraitsIN5clang7tooling12AtomicChangeEE7mappingERNS0_2IOERS4_'/>
<size>16</size>
<use f='llvm/clang/tools/clang-rename/ClangRename.cpp' l='56' c='_ZN4llvm4yaml13MappingTraitsI13RenameAllInfoE7mappingERNS0_2IOERS2_'/>
<size>16</size>
<use f='llvm/clang/tools/driver/cc1gen_reproducer_main.cpp' l='54' c='_ZN4llvm4yaml13MappingTraitsIN12_GLOBAL__N_115UnsavedFileHashEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/clang/tools/driver/cc1gen_reproducer_main.cpp' l='61' c='_ZN4llvm4yaml13MappingTraitsIN12_GLOBAL__N_119ClangInvocationInfoEE7mappingERNS0_2IOERS3_'/>
<size>16</size>
<use f='llvm/clang/include/clang/Tooling/DiagnosticsYaml.h' l='31' c='_ZN4llvm4yaml13MappingTraitsIN5clang7tooling13FileByteRangeEE7mappingERNS0_2IOERS4_'/>
<use f='llvm/clang/include/clang/Tooling/DiagnosticsYaml.h' l='39' c='_ZN4llvm4yaml13MappingTraitsIN5clang7tooling17DiagnosticMessageEE7mappingERNS0_2IOERS4_'/>
<use f='llvm/clang/include/clang/Tooling/DiagnosticsYaml.h' l='65' c='_ZN4llvm4yaml13MappingTraitsIN5clang7tooling10DiagnosticEE20NormalizedDiagnosticC1ERKNS0_2IOE'/>
<use f='llvm/clang/include/clang/Tooling/DiagnosticsYaml.h' l='68' c='_ZN4llvm4yaml13MappingTraitsIN5clang7tooling10DiagnosticEE20NormalizedDiagnosticC1ERKNS0_2IOERKS4_'/>
<use f='llvm/clang/include/clang/Tooling/DiagnosticsYaml.h' l='73' c='_ZN4llvm4yaml13MappingTraitsIN5clang7tooling10DiagnosticEE20NormalizedDiagnostic11denormalizeERKNS0_2IOE'/>
<use f='llvm/clang/include/clang/Tooling/DiagnosticsYaml.h' l='86' c='_ZN4llvm4yaml13MappingTraitsIN5clang7tooling10DiagnosticEE7mappingERNS0_2IOERS4_'/>
<use f='llvm/clang/include/clang/Tooling/DiagnosticsYaml.h' l='101' c='_ZN4llvm4yaml13MappingTraitsIN5clang7tooling26TranslationUnitDiagnosticsEE7mappingERNS0_2IOERS4_'/>
<use f='llvm/clang/include/clang/Tooling/DiagnosticsYaml.h' l='108' c='_ZN4llvm4yaml23ScalarEnumerationTraitsIN5clang7tooling10Diagnostic5LevelEvE11enumerationERNS0_2IOERS5_'/>
<size>16</size>
<use f='llvm/lld/include/lld/Core/Reader.h' l='73' c='_ZNK3lld27YamlIOTaggedDocumentHandler13handledDocTagERN4llvm4yaml2IOERPKNS_4FileE'/>
<use f='llvm/lld/include/lld/Core/Reader.h' l='103' c='_ZNK3lld8Registry15handleTaggedDocERN4llvm4yaml2IOERPKNS_4FileE'/>
<use f='llvm/lld/lib/Core/Reader.cpp' l='62' c='_ZNK3lld8Registry15handleTaggedDocERN4llvm4yaml2IOERPKNS_4FileE'/>
<use f='llvm/lld/lib/ReaderWriter/MachO/MachONormalizedFile.h' l='328' c='_ZNK3lld6mach_o32MachOYamlIOTaggedDocumentHandler13handledDocTagERN4llvm4yaml2IOERPKNS_4FileE'/>
<size>16</size>
<use f='llvm/lld/lib/ReaderWriter/MachO/MachONormalizedFileYAML.cpp' l='56' c='_ZN4llvm4yaml14SequenceTraitsISt6vectorIN3lld6mach_o10normalized7SectionESaIS6_EEvE4sizeERNS0_2IOERS8_'/>
<use f='llvm/lld/lib/ReaderWriter/MachO/MachONormalizedFileYAML.cpp' l='59' c='_ZN4llvm4yaml14SequenceTraitsISt6vectorIN3lld6mach_o10normalized7SectionESaIS6_EEvE7elementERNS0_2IOERS8_m'/>
<use f='llvm/lld/lib/ReaderWriter/MachO/MachONormalizedFileYAML.cpp' l='68' c='_ZN4llvm4yaml14SequenceTraitsISt6vectorIN3lld6mach_o10normalized6SymbolESaIS6_EEvE4sizeERNS0_2IOERS8_'/>
<use f='llvm/lld/lib/ReaderWriter/MachO/MachONormalizedFileYAML.cpp' l='71' c='_ZN4llvm4yaml14SequenceTraitsISt6vectorIN3lld6mach_o10normalized6SymbolESaIS6_EEvE7elementERNS0_2IOERS8_m'/>
<use f='llvm/lld/lib/ReaderWriter/MachO/MachONormalizedFileYAML.cpp' l='81' c='_ZN4llvm4yaml14SequenceTraitsISt6vectorIN3lld6mach_o10normalized10RelocationESaIS6_EEvE4sizeERNS0_2IOERS8_'/>
<use f='llvm/lld/lib/ReaderWriter/MachO/MachONormalizedFileYAML.cpp' l='84' c='_ZN4llvm4yaml14SequenceTraitsISt6vectorIN3lld6mach_o10normalized10RelocationESaIS6_EEvE7elementERNS0_2IOERS8_m'/>
<use f='llvm/lld/lib/ReaderWriter/MachO/MachONormalizedFileYAML.cpp' l='94' c='_ZN4llvm4yaml14SequenceTraitsISt6vectorINS0_4Hex8ESaIS3_EEvE4sizeERNS0_2IOERS5_'/>
<use f='llvm/lld/lib/ReaderWriter/MachO/MachONormalizedFileYAML.cpp' l='97' c='_ZN4llvm4yaml14SequenceTraitsISt6vectorINS0_4Hex8ESaIS3_EEvE7elementERNS0_2IOERS5_m'/>
<use f='llvm/lld/lib/ReaderWriter/MachO/MachONormalizedFileYAML.cpp' l='109' c='_ZN4llvm4yaml14SequenceTraitsISt6vectorIjSaIjEEvE4sizeERNS0_2IOERS4_'/>
<use f='llvm/lld/lib/ReaderWriter/MachO/MachONormalizedFileYAML.cpp' l='112' c='_ZN4llvm4yaml14SequenceTraitsISt6vectorIjSaIjEEvE7elementERNS0_2IOERS4_m'/>
<use f='llvm/lld/lib/ReaderWriter/MachO/MachONormalizedFileYAML.cpp' l='122' c='_ZN4llvm4yaml23ScalarEnumerationTraitsIN3lld19MachOLinkingContext4ArchEvE11enumerationERNS0_2IOERS4_'/>
<use f='llvm/lld/lib/ReaderWriter/MachO/MachONormalizedFileYAML.cpp' l='136' c='_ZN4llvm4yaml23ScalarEnumerationTraitsIN3lld19MachOLinkingContext2OSEvE11enumerationERNS0_2IOERS4_'/>
<use f='llvm/lld/lib/ReaderWriter/MachO/MachONormalizedFileYAML.cpp' l='151' c='_ZN4llvm4yaml23ScalarEnumerationTraitsINS_5MachO14HeaderFileTypeEvE11enumerationERNS0_2IOERS3_'/>
<use f='llvm/lld/lib/ReaderWriter/MachO/MachONormalizedFileYAML.cpp' l='162' c='_ZN4llvm4yaml18ScalarBitSetTraitsIN3lld6mach_o10normalized9FileFlagsEvE6bitsetERNS0_2IOERS5_'/>
<use f='llvm/lld/lib/ReaderWriter/MachO/MachONormalizedFileYAML.cpp' l='173' c='_ZN4llvm4yaml23ScalarEnumerationTraitsINS_5MachO11SectionTypeEvE11enumerationERNS0_2IOERS3_'/>
<use f='llvm/lld/lib/ReaderWriter/MachO/MachONormalizedFileYAML.cpp' l='223' c='_ZN4llvm4yaml18ScalarBitSetTraitsIN3lld6mach_o10normalized11SectionAttrEvE6bitsetERNS0_2IOERS5_'/>
<use f='llvm/lld/lib/ReaderWriter/MachO/MachONormalizedFileYAML.cpp' l='264' c='_ZN4llvm4yaml23ScalarEnumerationTraitsINS_5MachO9NListTypeEvE11enumerationERNS0_2IOERS3_'/>
<use f='llvm/lld/lib/ReaderWriter/MachO/MachONormalizedFileYAML.cpp' l='275' c='_ZN4llvm4yaml18ScalarBitSetTraitsIN3lld6mach_o10normalized11SymbolScopeEvE6bitsetERNS0_2IOERS5_'/>
<use f='llvm/lld/lib/ReaderWriter/MachO/MachONormalizedFileYAML.cpp' l='283' c='_ZN4llvm4yaml18ScalarBitSetTraitsIN3lld6mach_o10normalized10SymbolDescEvE6bitsetERNS0_2IOERS5_'/>
<use f='llvm/lld/lib/ReaderWriter/MachO/MachONormalizedFileYAML.cpp' l='296' c='_ZN4llvm4yaml13MappingTraitsIN3lld6mach_o10normalized7SectionEE7mappingERNS0_2IOERS5_'/>
<use f='llvm/lld/lib/ReaderWriter/MachO/MachONormalizedFileYAML.cpp' l='321' c='_ZN4llvm4yaml13MappingTraitsIN3lld6mach_o10normalized7SectionEE17NormalizedContentC1ERNS0_2IOE'/>
<use f='llvm/lld/lib/ReaderWriter/MachO/MachONormalizedFileYAML.cpp' l='322' c='_ZN4llvm4yaml13MappingTraitsIN3lld6mach_o10normalized7SectionEE17NormalizedContentC1ERNS0_2IOENS_8ArrayRefIhEE'/>
<use f='llvm/lld/lib/ReaderWriter/MachO/MachONormalizedFileYAML.cpp' l='328' c='_ZN4llvm4yaml13MappingTraitsIN3lld6mach_o10normalized7SectionEE17NormalizedContent11denormalizeERNS0_2IOE'/>
<use f='llvm/lld/lib/ReaderWriter/MachO/MachONormalizedFileYAML.cpp' l='343'/>
<use f='llvm/lld/lib/ReaderWriter/MachO/MachONormalizedFileYAML.cpp' l='351' c='_ZN4llvm4yaml13MappingTraitsIN3lld6mach_o10normalized10RelocationEE7mappingERNS0_2IOERS5_'/>
<use f='llvm/lld/lib/ReaderWriter/MachO/MachONormalizedFileYAML.cpp' l='369' c='_ZN4llvm4yaml23ScalarEnumerationTraitsINS_5MachO18RelocationInfoTypeEvE11enumerationERNS0_2IOERS3_'/>
<use f='llvm/lld/lib/ReaderWriter/MachO/MachONormalizedFileYAML.cpp' l='462' c='_ZN4llvm4yaml13MappingTraitsIN3lld6mach_o10normalized6SymbolEE7mappingERNS0_2IOERS5_'/>
<use f='llvm/lld/lib/ReaderWriter/MachO/MachONormalizedFileYAML.cpp' l='530' c='_ZN4llvm4yaml13MappingTraitsIN3lld6mach_o10normalized7SegmentEE7mappingERNS0_2IOERS5_'/>
<use f='llvm/lld/lib/ReaderWriter/MachO/MachONormalizedFileYAML.cpp' l='541' c='_ZN4llvm4yaml23ScalarEnumerationTraitsINS_5MachO15LoadCommandTypeEvE11enumerationERNS0_2IOERS3_'/>
<use f='llvm/lld/lib/ReaderWriter/MachO/MachONormalizedFileYAML.cpp' l='565' c='_ZN4llvm4yaml13MappingTraitsIN3lld6mach_o10normalized14DependentDylibEE7mappingERNS0_2IOERS5_'/>
<use f='llvm/lld/lib/ReaderWriter/MachO/MachONormalizedFileYAML.cpp' l='578' c='_ZN4llvm4yaml23ScalarEnumerationTraitsINS_5MachO10RebaseTypeEvE11enumerationERNS0_2IOERS3_'/>
<use f='llvm/lld/lib/ReaderWriter/MachO/MachONormalizedFileYAML.cpp' l='591' c='_ZN4llvm4yaml13MappingTraitsIN3lld6mach_o10normalized14RebaseLocationEE7mappingERNS0_2IOERS5_'/>
<use f='llvm/lld/lib/ReaderWriter/MachO/MachONormalizedFileYAML.cpp' l='603' c='_ZN4llvm4yaml23ScalarEnumerationTraitsINS_5MachO8BindTypeEvE11enumerationERNS0_2IOERS3_'/>
<use f='llvm/lld/lib/ReaderWriter/MachO/MachONormalizedFileYAML.cpp' l='615' c='_ZN4llvm4yaml13MappingTraitsIN3lld6mach_o10normalized12BindLocationEE7mappingERNS0_2IOERS5_'/>
<use f='llvm/lld/lib/ReaderWriter/MachO/MachONormalizedFileYAML.cpp' l='630' c='_ZN4llvm4yaml23ScalarEnumerationTraitsINS_5MachO16ExportSymbolKindEvE11enumerationERNS0_2IOERS3_'/>
<use f='llvm/lld/lib/ReaderWriter/MachO/MachONormalizedFileYAML.cpp' l='642' c='_ZN4llvm4yaml18ScalarBitSetTraitsIN3lld6mach_o10normalized11ExportFlagsEvE6bitsetERNS0_2IOERS5_'/>
<use f='llvm/lld/lib/ReaderWriter/MachO/MachONormalizedFileYAML.cpp' l='655' c='_ZN4llvm4yaml13MappingTraitsIN3lld6mach_o10normalized6ExportEE7mappingERNS0_2IOERS5_'/>
<use f='llvm/lld/lib/ReaderWriter/MachO/MachONormalizedFileYAML.cpp' l='669' c='_ZN4llvm4yaml23ScalarEnumerationTraitsINS_5MachO14DataRegionTypeEvE11enumerationERNS0_2IOERS3_'/>
<use f='llvm/lld/lib/ReaderWriter/MachO/MachONormalizedFileYAML.cpp' l='685' c='_ZN4llvm4yaml13MappingTraitsIN3lld6mach_o10normalized10DataInCodeEE7mappingERNS0_2IOERS5_'/>
<use f='llvm/lld/lib/ReaderWriter/MachO/MachONormalizedFileYAML.cpp' l='713' c='_ZN4llvm4yaml13MappingTraitsIN3lld6mach_o10normalized14NormalizedFileEE7mappingERNS0_2IOERS5_'/>
<use f='llvm/lld/lib/ReaderWriter/MachO/MachONormalizedFileYAML.cpp' l='743' c='_ZN4llvm4yaml13MappingTraitsIN3lld6mach_o10normalized14NormalizedFileEE8validateB5cxx11ERNS0_2IOERS5_'/>
<use f='llvm/lld/lib/ReaderWriter/MachO/MachONormalizedFileYAML.cpp' l='754' c='_ZNK3lld6mach_o32MachOYamlIOTaggedDocumentHandler13handledDocTagERN4llvm4yaml2IOERPKNS_4FileE'/>
<size>16</size>
<use f='llvm/lld/lib/ReaderWriter/YAML/ReaderWriterYAML.cpp' l='183' c='_ZN12_GLOBAL__N_115RefNameResolverC1EPKN3lld4FileERN4llvm4yaml2IOE'/>
<use f='llvm/lld/lib/ReaderWriter/YAML/ReaderWriterYAML.cpp' l='204'/>
<use f='llvm/lld/lib/ReaderWriter/YAML/ReaderWriterYAML.cpp' l='286' c='_ZN4llvm4yaml23ScalarEnumerationTraitsIN3lld4File4KindEvE11enumerationERNS0_2IOERS4_'/>
<use f='llvm/lld/lib/ReaderWriter/YAML/ReaderWriterYAML.cpp' l='295' c='_ZN4llvm4yaml23ScalarEnumerationTraitsIN3lld4Atom5ScopeEvE11enumerationERNS0_2IOERS4_'/>
<use f='llvm/lld/lib/ReaderWriter/YAML/ReaderWriterYAML.cpp' l='303' c='_ZN4llvm4yaml23ScalarEnumerationTraitsIN3lld11DefinedAtom13SectionChoiceEvE11enumerationERNS0_2IOERS4_'/>
<use f='llvm/lld/lib/ReaderWriter/YAML/ReaderWriterYAML.cpp' l='312' c='_ZN4llvm4yaml23ScalarEnumerationTraitsIN3lld11DefinedAtom12InterposableEvE11enumerationERNS0_2IOERS4_'/>
<use f='llvm/lld/lib/ReaderWriter/YAML/ReaderWriterYAML.cpp' l='320' c='_ZN4llvm4yaml23ScalarEnumerationTraitsIN3lld11DefinedAtom5MergeEvE11enumerationERNS0_2IOERS4_'/>
<use f='llvm/lld/lib/ReaderWriter/YAML/ReaderWriterYAML.cpp' l='334' c='_ZN4llvm4yaml23ScalarEnumerationTraitsIN3lld11DefinedAtom13DeadStripKindEvE11enumerationERNS0_2IOERS4_'/>
<use f='llvm/lld/lib/ReaderWriter/YAML/ReaderWriterYAML.cpp' l='342' c='_ZN4llvm4yaml23ScalarEnumerationTraitsIN3lld11DefinedAtom13DynamicExportEvE11enumerationERNS0_2IOERS4_'/>
<use f='llvm/lld/lib/ReaderWriter/YAML/ReaderWriterYAML.cpp' l='349' c='_ZN4llvm4yaml23ScalarEnumerationTraitsIN3lld11DefinedAtom9CodeModelEvE11enumerationERNS0_2IOERS4_'/>
<use f='llvm/lld/lib/ReaderWriter/YAML/ReaderWriterYAML.cpp' l='364' c='_ZN4llvm4yaml23ScalarEnumerationTraitsIN3lld11DefinedAtom18ContentPermissionsEvE11enumerationERNS0_2IOERS4_'/>
<use f='llvm/lld/lib/ReaderWriter/YAML/ReaderWriterYAML.cpp' l='376' c='_ZN4llvm4yaml23ScalarEnumerationTraitsIN3lld11DefinedAtom11ContentTypeEvE11enumerationERNS0_2IOERS4_'/>
<use f='llvm/lld/lib/ReaderWriter/YAML/ReaderWriterYAML.cpp' l='434' c='_ZN4llvm4yaml23ScalarEnumerationTraitsIN3lld13UndefinedAtom9CanBeNullEvE11enumerationERNS0_2IOERS4_'/>
<use f='llvm/lld/lib/ReaderWriter/YAML/ReaderWriterYAML.cpp' l='442' c='_ZN4llvm4yaml23ScalarEnumerationTraitsIN12_GLOBAL__N_114ShlibCanBeNullEvE11enumerationERNS0_2IOERS3_'/>
<use f='llvm/lld/lib/ReaderWriter/YAML/ReaderWriterYAML.cpp' l='450' c='_ZN4llvm4yaml23ScalarEnumerationTraitsIN3lld17SharedLibraryAtom4TypeEvE11enumerationERNS0_2IOERS4_'/>
<use f='llvm/lld/lib/ReaderWriter/YAML/ReaderWriterYAML.cpp' l='501' c='_ZN4llvm4yaml23ScalarEnumerationTraitsIN12_GLOBAL__N_19FileKindsEvE11enumerationERNS0_2IOERS3_'/>
<use f='llvm/lld/lib/ReaderWriter/YAML/ReaderWriterYAML.cpp' l='509' c='_ZN4llvm4yaml13MappingTraitsIN12_GLOBAL__N_110ArchMemberEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/lld/lib/ReaderWriter/YAML/ReaderWriterYAML.cpp' l='518' c='_ZN4llvm4yaml14SequenceTraitsIN12_GLOBAL__N_18AtomListIT_EEvE4sizeERNS0_2IOERS5_'/>
<use f='llvm/lld/lib/ReaderWriter/YAML/ReaderWriterYAML.cpp' l='519' c='_ZN4llvm4yaml14SequenceTraitsIN12_GLOBAL__N_18AtomListIT_EEvE7elementERNS0_2IOERS5_m'/>
<use f='llvm/lld/lib/ReaderWriter/YAML/ReaderWriterYAML.cpp' l='528' c='_ZN4llvm4yaml14SequenceTraitsIN3lld4File9AtomRangeIT_EEvE4sizeERNS0_2IOERS6_'/>
<use f='llvm/lld/lib/ReaderWriter/YAML/ReaderWriterYAML.cpp' l='529' c='_ZN4llvm4yaml14SequenceTraitsIN3lld4File9AtomRangeIT_EEvE7elementERNS0_2IOERS6_m'/>
<use f='llvm/lld/lib/ReaderWriter/YAML/ReaderWriterYAML.cpp' l='559' c='_ZN4llvm4yaml18DocumentListTraitsISt6vectorIPKN3lld4FileESaIS6_EEE4sizeERNS0_2IOERS8_'/>
<use f='llvm/lld/lib/ReaderWriter/YAML/ReaderWriterYAML.cpp' l='562' c='_ZN4llvm4yaml18DocumentListTraitsISt6vectorIPKN3lld4FileESaIS6_EEE7elementERNS0_2IOERS8_m'/>
<use f='llvm/lld/lib/ReaderWriter/YAML/ReaderWriterYAML.cpp' l='574' c='_ZN4llvm4yaml13MappingTraitsIPKN3lld4FileEE15NormArchiveFileC1ERNS0_2IOE'/>
<use f='llvm/lld/lib/ReaderWriter/YAML/ReaderWriterYAML.cpp' l='576' c='_ZN4llvm4yaml13MappingTraitsIPKN3lld4FileEE15NormArchiveFileC1ERNS0_2IOES5_'/>
<use f='llvm/lld/lib/ReaderWriter/YAML/ReaderWriterYAML.cpp' l='582' c='_ZN4llvm4yaml13MappingTraitsIPKN3lld4FileEE15NormArchiveFile11denormalizeERNS0_2IOE'/>
<use f='llvm/lld/lib/ReaderWriter/YAML/ReaderWriterYAML.cpp' l='626' c='_ZN4llvm4yaml13MappingTraitsIPKN3lld4FileEE14NormalizedFileC1ERNS0_2IOE'/>
<use f='llvm/lld/lib/ReaderWriter/YAML/ReaderWriterYAML.cpp' l='633' c='_ZN4llvm4yaml13MappingTraitsIPKN3lld4FileEE14NormalizedFileC1ERNS0_2IOES5_'/>
<use f='llvm/lld/lib/ReaderWriter/YAML/ReaderWriterYAML.cpp' l='645' c='_ZN4llvm4yaml13MappingTraitsIPKN3lld4FileEE14NormalizedFile11denormalizeERNS0_2IOE'/>
<use f='llvm/lld/lib/ReaderWriter/YAML/ReaderWriterYAML.cpp' l='678'/>
<use f='llvm/lld/lib/ReaderWriter/YAML/ReaderWriterYAML.cpp' l='692' c='_ZN4llvm4yaml13MappingTraitsIPKN3lld4FileEE7mappingERNS0_2IOERS5_'/>
<use f='llvm/lld/lib/ReaderWriter/YAML/ReaderWriterYAML.cpp' l='704' c='_ZN4llvm4yaml13MappingTraitsIPKN3lld4FileEE12mappingAtomsERNS0_2IOERS5_'/>
<use f='llvm/lld/lib/ReaderWriter/YAML/ReaderWriterYAML.cpp' l='726' c='_ZN4llvm4yaml13MappingTraitsIPKN3lld4FileEE14mappingArchiveERNS0_2IOERS5_'/>
<use f='llvm/lld/lib/ReaderWriter/YAML/ReaderWriterYAML.cpp' l='740' c='_ZN4llvm4yaml13MappingTraitsIPKN3lld9ReferenceEE19NormalizedReferenceC1ERNS0_2IOE'/>
<use f='llvm/lld/lib/ReaderWriter/YAML/ReaderWriterYAML.cpp' l='745' c='_ZN4llvm4yaml13MappingTraitsIPKN3lld9ReferenceEE19NormalizedReferenceC1ERNS0_2IOES5_'/>
<use f='llvm/lld/lib/ReaderWriter/YAML/ReaderWriterYAML.cpp' l='756' c='_ZN4llvm4yaml13MappingTraitsIPKN3lld9ReferenceEE19NormalizedReference11denormalizeERNS0_2IOE'/>
<use f='llvm/lld/lib/ReaderWriter/YAML/ReaderWriterYAML.cpp' l='775' c='_ZN4llvm4yaml13MappingTraitsIPKN3lld9ReferenceEE19NormalizedReference10targetNameERNS0_2IOES5_'/>
<use f='llvm/lld/lib/ReaderWriter/YAML/ReaderWriterYAML.cpp' l='791' c='_ZN4llvm4yaml13MappingTraitsIPKN3lld9ReferenceEE7mappingERNS0_2IOERS5_'/>
<use f='llvm/lld/lib/ReaderWriter/YAML/ReaderWriterYAML.cpp' l='809' c='_ZN4llvm4yaml13MappingTraitsIPKN3lld11DefinedAtomEE14NormalizedAtomC1ERNS0_2IOE'/>
<use f='llvm/lld/lib/ReaderWriter/YAML/ReaderWriterYAML.cpp' l='815' c='_ZN4llvm4yaml13MappingTraitsIPKN3lld11DefinedAtomEE14NormalizedAtomC1ERNS0_2IOES5_'/>
<use f='llvm/lld/lib/ReaderWriter/YAML/ReaderWriterYAML.cpp' l='837' c='_ZN4llvm4yaml13MappingTraitsIPKN3lld11DefinedAtomEE14NormalizedAtom11denormalizeERNS0_2IOE'/>
<use f='llvm/lld/lib/ReaderWriter/YAML/ReaderWriterYAML.cpp' l='858' c='_ZN4llvm4yaml13MappingTraitsIPKN3lld11DefinedAtomEE14NormalizedAtom15fileFromContextERNS0_2IOE'/>
<use f='llvm/lld/lib/ReaderWriter/YAML/ReaderWriterYAML.cpp' l='941' c='_ZN4llvm4yaml13MappingTraitsIPKN3lld11DefinedAtomEE7mappingERNS0_2IOERS5_'/>
<use f='llvm/lld/lib/ReaderWriter/YAML/ReaderWriterYAML.cpp' l='988' c='_ZN4llvm4yaml13MappingTraitsIPN3lld11DefinedAtomEE7mappingERNS0_2IOERS4_'/>
<use f='llvm/lld/lib/ReaderWriter/YAML/ReaderWriterYAML.cpp' l='999' c='_ZN4llvm4yaml13MappingTraitsIPKN3lld13UndefinedAtomEE14NormalizedAtomC1ERNS0_2IOE'/>
<use f='llvm/lld/lib/ReaderWriter/YAML/ReaderWriterYAML.cpp' l='1002' c='_ZN4llvm4yaml13MappingTraitsIPKN3lld13UndefinedAtomEE14NormalizedAtomC1ERNS0_2IOES5_'/>
<use f='llvm/lld/lib/ReaderWriter/YAML/ReaderWriterYAML.cpp' l='1008' c='_ZN4llvm4yaml13MappingTraitsIPKN3lld13UndefinedAtomEE14NormalizedAtom11denormalizeERNS0_2IOE'/>
<use f='llvm/lld/lib/ReaderWriter/YAML/ReaderWriterYAML.cpp' l='1024' c='_ZN4llvm4yaml13MappingTraitsIPKN3lld13UndefinedAtomEE14NormalizedAtom15fileFromContextERNS0_2IOE'/>
<use f='llvm/lld/lib/ReaderWriter/YAML/ReaderWriterYAML.cpp' l='1040' c='_ZN4llvm4yaml13MappingTraitsIPKN3lld13UndefinedAtomEE7mappingERNS0_2IOERS5_'/>
<use f='llvm/lld/lib/ReaderWriter/YAML/ReaderWriterYAML.cpp' l='1052' c='_ZN4llvm4yaml13MappingTraitsIPN3lld13UndefinedAtomEE7mappingERNS0_2IOERS4_'/>
<use f='llvm/lld/lib/ReaderWriter/YAML/ReaderWriterYAML.cpp' l='1063' c='_ZN4llvm4yaml13MappingTraitsIPKN3lld17SharedLibraryAtomEE14NormalizedAtomC1ERNS0_2IOE'/>
<use f='llvm/lld/lib/ReaderWriter/YAML/ReaderWriterYAML.cpp' l='1067' c='_ZN4llvm4yaml13MappingTraitsIPKN3lld17SharedLibraryAtomEE14NormalizedAtomC1ERNS0_2IOES5_'/>
<use f='llvm/lld/lib/ReaderWriter/YAML/ReaderWriterYAML.cpp' l='1074' c='_ZN4llvm4yaml13MappingTraitsIPKN3lld17SharedLibraryAtomEE14NormalizedAtom11denormalizeERNS0_2IOE'/>
<use f='llvm/lld/lib/ReaderWriter/YAML/ReaderWriterYAML.cpp' l='1093' c='_ZN4llvm4yaml13MappingTraitsIPKN3lld17SharedLibraryAtomEE14NormalizedAtom15fileFromContextERNS0_2IOE'/>
<use f='llvm/lld/lib/ReaderWriter/YAML/ReaderWriterYAML.cpp' l='1115' c='_ZN4llvm4yaml13MappingTraitsIPKN3lld17SharedLibraryAtomEE7mappingERNS0_2IOERS5_'/>
<use f='llvm/lld/lib/ReaderWriter/YAML/ReaderWriterYAML.cpp' l='1130' c='_ZN4llvm4yaml13MappingTraitsIPN3lld17SharedLibraryAtomEE7mappingERNS0_2IOERS4_'/>
<use f='llvm/lld/lib/ReaderWriter/YAML/ReaderWriterYAML.cpp' l='1141' c='_ZN4llvm4yaml13MappingTraitsIPKN3lld12AbsoluteAtomEE14NormalizedAtomC1ERNS0_2IOE'/>
<use f='llvm/lld/lib/ReaderWriter/YAML/ReaderWriterYAML.cpp' l='1144' c='_ZN4llvm4yaml13MappingTraitsIPKN3lld12AbsoluteAtomEE14NormalizedAtomC1ERNS0_2IOES5_'/>
<use f='llvm/lld/lib/ReaderWriter/YAML/ReaderWriterYAML.cpp' l='1150' c='_ZN4llvm4yaml13MappingTraitsIPKN3lld12AbsoluteAtomEE14NormalizedAtom11denormalizeERNS0_2IOE'/>
<use f='llvm/lld/lib/ReaderWriter/YAML/ReaderWriterYAML.cpp' l='1166' c='_ZN4llvm4yaml13MappingTraitsIPKN3lld12AbsoluteAtomEE14NormalizedAtom15fileFromContextERNS0_2IOE'/>
<use f='llvm/lld/lib/ReaderWriter/YAML/ReaderWriterYAML.cpp' l='1185' c='_ZN4llvm4yaml13MappingTraitsIPKN3lld12AbsoluteAtomEE7mappingERNS0_2IOERS5_'/>
<use f='llvm/lld/lib/ReaderWriter/YAML/ReaderWriterYAML.cpp' l='1210' c='_ZN4llvm4yaml13MappingTraitsIPN3lld12AbsoluteAtomEE7mappingERNS0_2IOERS4_'/>
<use f='llvm/lld/lib/ReaderWriter/YAML/ReaderWriterYAML.cpp' l='1220' c='_ZN12_GLOBAL__N_115RefNameResolverC1EPKN3lld4FileERN4llvm4yaml2IOE'/>
<use f='llvm/lld/lib/ReaderWriter/YAML/ReaderWriterYAML.cpp' l='1248' c='_ZN4llvm4yaml13MappingTraitsIPKN3lld4FileEE14NormalizedFile11denormalizeERNS0_2IOE'/>
<use f='llvm/lld/lib/ReaderWriter/YAML/ReaderWriterYAML.cpp' l='1279' c='_ZN4llvm4yaml13MappingTraitsIPKN3lld9ReferenceEE19NormalizedReference10targetNameERNS0_2IOES5_'/>
<use f='llvm/lld/lib/ReaderWriter/YAML/ReaderWriterYAML.cpp' l='1329' c='_ZNK3lld12_GLOBAL__N_133NativeYamlIOTaggedDocumentHandler13handledDocTagERN4llvm4yaml2IOERPKNS_4FileE'/>
<use f='llvm/lld/lib/ReaderWriter/YAML/ReaderWriterYAML.cpp' l='1340' c='_ZNK3lld12_GLOBAL__N_134ArchiveYamlIOTaggedDocumentHandler13handledDocTagERN4llvm4yaml2IOERPKNS_4FileE'/>
<size>16</size>
<use f='llvm/lldb/include/lldb/Utility/Args.h' l='387' c='_ZN4llvm4yaml13MappingTraitsIN12lldb_private4Args8ArgEntryEE18NormalizedArgEntryC1ERNS0_2IOE'/>
<use f='llvm/lldb/include/lldb/Utility/Args.h' l='388' c='_ZN4llvm4yaml13MappingTraitsIN12lldb_private4Args8ArgEntryEE18NormalizedArgEntryC1ERNS0_2IOERS4_'/>
<use f='llvm/lldb/include/lldb/Utility/Args.h' l='390' c='_ZN4llvm4yaml13MappingTraitsIN12lldb_private4Args8ArgEntryEE18NormalizedArgEntry11denormalizeERNS0_2IOE'/>
<use f='llvm/lldb/include/lldb/Utility/Args.h' l='396' c='_ZN4llvm4yaml13MappingTraitsIN12lldb_private4Args8ArgEntryEE7mappingERNS0_2IOERS4_'/>
<use f='llvm/lldb/include/lldb/Utility/Args.h' l='399' c='_ZN4llvm4yaml13MappingTraitsIN12lldb_private4ArgsEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/lldb/include/lldb/Utility/ProcessInfo.h' l='228' c='_ZN4llvm4yaml13MappingTraitsIN12lldb_private19ProcessInstanceInfoEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/lldb/include/lldb/Utility/ReproducerProvider.h' l='424' c='_ZN4llvm4yaml13MappingTraitsIN12lldb_private5repro18SymbolFileProvider5EntryEE7mappingERNS0_2IOERS5_'/>
<size>16</size>
<use f='llvm/lldb/include/lldb/Utility/GDBRemote.h' l='136' c='_ZN4llvm4yaml23ScalarEnumerationTraitsIN12lldb_private15GDBRemotePacket4TypeEvE11enumerationERNS0_2IOERS4_'/>
<use f='llvm/lldb/include/lldb/Utility/GDBRemote.h' l='150' c='_ZN4llvm4yaml13MappingTraitsIN12lldb_private15GDBRemotePacketEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/lldb/include/lldb/Utility/GDBRemote.h' l='152' c='_ZN4llvm4yaml13MappingTraitsIN12lldb_private15GDBRemotePacketEE8validateERNS0_2IOERS3_'/>
<size>16</size>
<use f='llvm/lldb/source/Utility/Args.cpp' l='686' c='_ZN4llvm4yaml13MappingTraitsIN12lldb_private4Args8ArgEntryEE7mappingERNS0_2IOERS4_'/>
<use f='llvm/lldb/source/Utility/Args.cpp' l='693' c='_ZN4llvm4yaml13MappingTraitsIN12lldb_private4ArgsEE7mappingERNS0_2IOERS3_'/>
<size>16</size>
<use f='llvm/lldb/source/Utility/FileSpec.cpp' l='542' c='_ZN4llvm4yaml23ScalarEnumerationTraitsIN12lldb_private13FileSpecStyleEvE11enumerationERNS0_2IOERS3_'/>
<use f='llvm/lldb/source/Utility/FileSpec.cpp' l='548' c='_ZN4llvm4yaml13MappingTraitsIN12lldb_private8FileSpecEE7mappingERNS0_2IOERS3_'/>
<size>16</size>
<use f='llvm/lldb/source/Utility/GDBRemote.cpp' l='67' c='_ZN4llvm4yaml23ScalarEnumerationTraitsIN12lldb_private15GDBRemotePacket4TypeEvE11enumerationERNS0_2IOERS4_'/>
<use f='llvm/lldb/source/Utility/GDBRemote.cpp' l='84' c='_ZN4llvm4yaml13MappingTraitsIN12lldb_private15GDBRemotePacketEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/lldb/source/Utility/GDBRemote.cpp' l='94' c='_ZN4llvm4yaml13MappingTraitsIN12lldb_private15GDBRemotePacketEE8validateERNS0_2IOERS3_'/>
<size>16</size>
<use f='llvm/lldb/source/Utility/ProcessInfo.cpp' l='338' c='_ZN4llvm4yaml13MappingTraitsIN12lldb_private19ProcessInstanceInfoEE7mappingERNS0_2IOERS3_'/>
<size>16</size>
<use f='llvm/lldb/unittests/Utility/ReproducerTest.cpp' l='78' c='_ZN4llvm4yaml13MappingTraitsI8YamlDataE7mappingERNS0_2IOERS2_'/>
<size>16</size>
<use f='llvm/llvm/lib/BinaryFormat/MsgPackDocumentYAML.cpp' l='210' c='_ZN4llvm4yaml19CustomMappingTraitsINS_7msgpack10MapDocNodeEE8inputOneERNS0_2IOENS_9StringRefERS3_'/>
<use f='llvm/llvm/lib/BinaryFormat/MsgPackDocumentYAML.cpp' l='216' c='_ZN4llvm4yaml19CustomMappingTraitsINS_7msgpack10MapDocNodeEE6outputERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/BinaryFormat/MsgPackDocumentYAML.cpp' l='226' c='_ZN4llvm4yaml14SequenceTraitsINS_7msgpack12ArrayDocNodeEvE4sizeERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/BinaryFormat/MsgPackDocumentYAML.cpp' l='228' c='_ZN4llvm4yaml14SequenceTraitsINS_7msgpack12ArrayDocNodeEvE7elementERNS0_2IOERS3_m'/>
<size>16</size>
<use f='llvm/llvm/include/llvm/CodeGen/MIRYamlMapping.h' l='130' c='_ZN4llvm4yaml23ScalarEnumerationTraitsINS_20MachineJumpTableInfo11JTEntryKindEvE11enumerationERNS0_2IOERS3_'/>
<use f='llvm/llvm/include/llvm/CodeGen/MIRYamlMapping.h' l='202' c='_ZN4llvm4yaml13MappingTraitsINS0_25VirtualRegisterDefinitionEE7mappingERNS0_2IOERS2_'/>
<use f='llvm/llvm/include/llvm/CodeGen/MIRYamlMapping.h' l='223' c='_ZN4llvm4yaml13MappingTraitsINS0_21MachineFunctionLiveInEE7mappingERNS0_2IOERS2_'/>
<use f='llvm/llvm/include/llvm/CodeGen/MIRYamlMapping.h' l='270' c='_ZN4llvm4yaml23ScalarEnumerationTraitsINS0_18MachineStackObject10ObjectTypeEvE11enumerationERNS0_2IOERS3_'/>
<use f='llvm/llvm/include/llvm/CodeGen/MIRYamlMapping.h' l='278' c='_ZN4llvm4yaml13MappingTraitsINS0_18MachineStackObjectEE7mappingERNS0_2IOERS2_'/>
<use f='llvm/llvm/include/llvm/CodeGen/MIRYamlMapping.h' l='338' c='_ZN4llvm4yaml23ScalarEnumerationTraitsINS0_23FixedMachineStackObject10ObjectTypeEvE11enumerationERNS0_2IOERS3_'/>
<use f='llvm/llvm/include/llvm/CodeGen/MIRYamlMapping.h' l='347' c='_ZN4llvm4yaml23ScalarEnumerationTraitsINS_13TargetStackID5ValueEvE11enumerationERNS0_2IOERS3_'/>
<use f='llvm/llvm/include/llvm/CodeGen/MIRYamlMapping.h' l='356' c='_ZN4llvm4yaml13MappingTraitsINS0_23FixedMachineStackObjectEE7mappingERNS0_2IOERS2_'/>
<use f='llvm/llvm/include/llvm/CodeGen/MIRYamlMapping.h' l='418' c='_ZN4llvm4yaml13MappingTraitsINS0_12CallSiteInfo10ArgRegPairEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/include/llvm/CodeGen/MIRYamlMapping.h' l='434' c='_ZN4llvm4yaml13MappingTraitsINS0_12CallSiteInfoEE7mappingERNS0_2IOERS2_'/>
<use f='llvm/llvm/include/llvm/CodeGen/MIRYamlMapping.h' l='458' c='_ZN4llvm4yaml13MappingTraitsINS0_22DebugValueSubstitutionEE7mappingERNS0_2IOERS2_'/>
<use f='llvm/llvm/include/llvm/CodeGen/MIRYamlMapping.h' l='488' c='_ZN4llvm4yaml13MappingTraitsINS0_24MachineConstantPoolValueEE7mappingERNS0_2IOERS2_'/>
<use f='llvm/llvm/include/llvm/CodeGen/MIRYamlMapping.h' l='515' c='_ZN4llvm4yaml13MappingTraitsINS0_16MachineJumpTable5EntryEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/include/llvm/CodeGen/MIRYamlMapping.h' l='536' c='_ZN4llvm4yaml13MappingTraitsINS0_16MachineJumpTableEE7mappingERNS0_2IOERS2_'/>
<use f='llvm/llvm/include/llvm/CodeGen/MIRYamlMapping.h' l='593' c='_ZN4llvm4yaml13MappingTraitsINS0_16MachineFrameInfoEE7mappingERNS0_2IOERS2_'/>
<use f='llvm/llvm/include/llvm/CodeGen/MIRYamlMapping.h' l='625' c='_ZN4llvm4yaml19MachineFunctionInfo11mappingImplERNS0_2IOE'/>
<use f='llvm/llvm/include/llvm/CodeGen/MIRYamlMapping.h' l='629' c='_ZN4llvm4yaml13MappingTraitsISt10unique_ptrINS0_19MachineFunctionInfoESt14default_deleteIS3_EEE7mappingERNS0_2IOERS6_'/>
<use f='llvm/llvm/include/llvm/CodeGen/MIRYamlMapping.h' l='664' c='_ZN4llvm4yaml13MappingTraitsINS0_15MachineFunctionEE7mappingERNS0_2IOERS2_'/>
<size>16</size>
<use f='llvm/llvm/lib/InterfaceStub/TBEHandler.cpp' l='26' c='_ZN4llvm4yaml23ScalarEnumerationTraitsINS_6elfabi13ELFSymbolTypeEvE11enumerationERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/InterfaceStub/TBEHandler.cpp' l='74' c='_ZN4llvm4yaml13MappingTraitsINS_6elfabi9ELFSymbolEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/InterfaceStub/TBEHandler.cpp' l='95' c='_ZN4llvm4yaml19CustomMappingTraitsISt3setINS_6elfabi9ELFSymbolESt4lessIS4_ESaIS4_EEE8inputOneERNS0_2IOENS_9StringRefERS8_'/>
<use f='llvm/llvm/lib/InterfaceStub/TBEHandler.cpp' l='101' c='_ZN4llvm4yaml19CustomMappingTraitsISt3setINS_6elfabi9ELFSymbolESt4lessIS4_ESaIS4_EEE6outputERNS0_2IOERS8_'/>
<use f='llvm/llvm/lib/InterfaceStub/TBEHandler.cpp' l='109' c='_ZN4llvm4yaml13MappingTraitsINS_6elfabi7ELFStubEE7mappingERNS0_2IOERS3_'/>
<size>16</size>
<use f='llvm/llvm/include/llvm/ObjectYAML/ArchiveYAML.h' l='65' c='_ZN4llvm4yaml13MappingTraitsINS_8ArchYAML7ArchiveEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/include/llvm/ObjectYAML/ArchiveYAML.h' l='66' c='_ZN4llvm4yaml13MappingTraitsINS_8ArchYAML7ArchiveEE8validateB5cxx11ERNS0_2IOERS3_'/>
<use f='llvm/llvm/include/llvm/ObjectYAML/ArchiveYAML.h' l='70' c='_ZN4llvm4yaml13MappingTraitsINS_8ArchYAML7Archive5ChildEE7mappingERNS0_2IOERS4_'/>
<use f='llvm/llvm/include/llvm/ObjectYAML/ArchiveYAML.h' l='71' c='_ZN4llvm4yaml13MappingTraitsINS_8ArchYAML7Archive5ChildEE8validateB5cxx11ERNS0_2IOERS4_'/>
<size>16</size>
<use f='llvm/llvm/lib/ObjectYAML/ArchiveYAML.cpp' l='19' c='_ZN4llvm4yaml13MappingTraitsINS_8ArchYAML7ArchiveEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/ArchiveYAML.cpp' l='29' c='_ZN4llvm4yaml13MappingTraitsINS_8ArchYAML7ArchiveEE8validateB5cxx11ERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/ArchiveYAML.cpp' l='37' c='_ZN4llvm4yaml13MappingTraitsINS_8ArchYAML7Archive5ChildEE7mappingERNS0_2IOERS4_'/>
<use f='llvm/llvm/lib/ObjectYAML/ArchiveYAML.cpp' l='46' c='_ZN4llvm4yaml13MappingTraitsINS_8ArchYAML7Archive5ChildEE8validateB5cxx11ERNS0_2IOERS4_'/>
<size>16</size>
<use f='llvm/llvm/include/llvm/ObjectYAML/CodeViewYAMLDebugSections.h' l='135' macro='1' c='_ZN4llvm4yaml13MappingTraitsINS_12CodeViewYAML19YAMLDebugSubsectionEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/include/llvm/ObjectYAML/CodeViewYAMLTypeHashing.h' l='57' macro='1' c='_ZN4llvm4yaml13MappingTraitsINS_12CodeViewYAML13DebugHSectionEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/include/llvm/ObjectYAML/CodeViewYAMLTypes.h' l='64' macro='1' c='_ZN4llvm4yaml13MappingTraitsINS_12CodeViewYAML10LeafRecordEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/include/llvm/ObjectYAML/CodeViewYAMLTypes.h' l='65' macro='1' c='_ZN4llvm4yaml13MappingTraitsINS_12CodeViewYAML12MemberRecordEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/include/llvm/ObjectYAML/COFFYAML.h' l='125' c='_ZN4llvm4yaml23ScalarEnumerationTraitsINS_8COFFYAML27WeakExternalCharacteristicsEvE11enumerationERNS0_2IOERS3_'/>
<use f='llvm/llvm/include/llvm/ObjectYAML/COFFYAML.h' l='130' c='_ZN4llvm4yaml23ScalarEnumerationTraitsINS_8COFFYAML13AuxSymbolTypeEvE11enumerationERNS0_2IOERS3_'/>
<use f='llvm/llvm/include/llvm/ObjectYAML/COFFYAML.h' l='135' c='_ZN4llvm4yaml23ScalarEnumerationTraitsINS_8COFFYAML10COMDATTypeEvE11enumerationERNS0_2IOERS3_'/>
<use f='llvm/llvm/include/llvm/ObjectYAML/COFFYAML.h' l='140' c='_ZN4llvm4yaml23ScalarEnumerationTraitsINS_4COFF12MachineTypesEvE11enumerationERNS0_2IOERS3_'/>
<use f='llvm/llvm/include/llvm/ObjectYAML/COFFYAML.h' l='145' c='_ZN4llvm4yaml23ScalarEnumerationTraitsINS_4COFF14SymbolBaseTypeEvE11enumerationERNS0_2IOERS3_'/>
<use f='llvm/llvm/include/llvm/ObjectYAML/COFFYAML.h' l='150' c='_ZN4llvm4yaml23ScalarEnumerationTraitsINS_4COFF18SymbolStorageClassEvE11enumerationERNS0_2IOERS3_'/>
<use f='llvm/llvm/include/llvm/ObjectYAML/COFFYAML.h' l='155' c='_ZN4llvm4yaml23ScalarEnumerationTraitsINS_4COFF17SymbolComplexTypeEvE11enumerationERNS0_2IOERS3_'/>
<use f='llvm/llvm/include/llvm/ObjectYAML/COFFYAML.h' l='160' c='_ZN4llvm4yaml23ScalarEnumerationTraitsINS_4COFF18RelocationTypeI386EvE11enumerationERNS0_2IOERS3_'/>
<use f='llvm/llvm/include/llvm/ObjectYAML/COFFYAML.h' l='165' c='_ZN4llvm4yaml23ScalarEnumerationTraitsINS_4COFF19RelocationTypeAMD64EvE11enumerationERNS0_2IOERS3_'/>
<use f='llvm/llvm/include/llvm/ObjectYAML/COFFYAML.h' l='170' c='_ZN4llvm4yaml23ScalarEnumerationTraitsINS_4COFF18RelocationTypesARMEvE11enumerationERNS0_2IOERS3_'/>
<use f='llvm/llvm/include/llvm/ObjectYAML/COFFYAML.h' l='175' c='_ZN4llvm4yaml23ScalarEnumerationTraitsINS_4COFF20RelocationTypesARM64EvE11enumerationERNS0_2IOERS3_'/>
<use f='llvm/llvm/include/llvm/ObjectYAML/COFFYAML.h' l='180' c='_ZN4llvm4yaml23ScalarEnumerationTraitsINS_4COFF16WindowsSubsystemEvE11enumerationERNS0_2IOERS3_'/>
<use f='llvm/llvm/include/llvm/ObjectYAML/COFFYAML.h' l='185' c='_ZN4llvm4yaml18ScalarBitSetTraitsINS_4COFF15CharacteristicsEvE6bitsetERNS0_2IOERS3_'/>
<use f='llvm/llvm/include/llvm/ObjectYAML/COFFYAML.h' l='190' c='_ZN4llvm4yaml18ScalarBitSetTraitsINS_4COFF22SectionCharacteristicsEvE6bitsetERNS0_2IOERS3_'/>
<use f='llvm/llvm/include/llvm/ObjectYAML/COFFYAML.h' l='195' c='_ZN4llvm4yaml18ScalarBitSetTraitsINS_4COFF18DLLCharacteristicsEvE6bitsetERNS0_2IOERS3_'/>
<use f='llvm/llvm/include/llvm/ObjectYAML/COFFYAML.h' l='200' c='_ZN4llvm4yaml13MappingTraitsINS_8COFFYAML10RelocationEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/include/llvm/ObjectYAML/COFFYAML.h' l='205' c='_ZN4llvm4yaml13MappingTraitsINS_8COFFYAML8PEHeaderEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/include/llvm/ObjectYAML/COFFYAML.h' l='210' c='_ZN4llvm4yaml13MappingTraitsINS_4COFF13DataDirectoryEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/include/llvm/ObjectYAML/COFFYAML.h' l='215' c='_ZN4llvm4yaml13MappingTraitsINS_4COFF6headerEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/include/llvm/ObjectYAML/COFFYAML.h' l='219' c='_ZN4llvm4yaml13MappingTraitsINS_4COFF27AuxiliaryFunctionDefinitionEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/include/llvm/ObjectYAML/COFFYAML.h' l='223' c='_ZN4llvm4yaml13MappingTraitsINS_4COFF22AuxiliarybfAndefSymbolEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/include/llvm/ObjectYAML/COFFYAML.h' l='227' c='_ZN4llvm4yaml13MappingTraitsINS_4COFF21AuxiliaryWeakExternalEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/include/llvm/ObjectYAML/COFFYAML.h' l='231' c='_ZN4llvm4yaml13MappingTraitsINS_4COFF26AuxiliarySectionDefinitionEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/include/llvm/ObjectYAML/COFFYAML.h' l='235' c='_ZN4llvm4yaml13MappingTraitsINS_4COFF17AuxiliaryCLRTokenEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/include/llvm/ObjectYAML/COFFYAML.h' l='240' c='_ZN4llvm4yaml13MappingTraitsINS_8COFFYAML6SymbolEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/include/llvm/ObjectYAML/COFFYAML.h' l='245' c='_ZN4llvm4yaml13MappingTraitsINS_8COFFYAML7SectionEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/include/llvm/ObjectYAML/COFFYAML.h' l='250' c='_ZN4llvm4yaml13MappingTraitsINS_8COFFYAML6ObjectEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/include/llvm/ObjectYAML/DWARFYAML.h' l='283' c='_ZN4llvm4yaml13MappingTraitsINS_9DWARFYAML4DataEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/include/llvm/ObjectYAML/DWARFYAML.h' l='287' c='_ZN4llvm4yaml13MappingTraitsINS_9DWARFYAML11AbbrevTableEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/include/llvm/ObjectYAML/DWARFYAML.h' l='291' c='_ZN4llvm4yaml13MappingTraitsINS_9DWARFYAML6AbbrevEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/include/llvm/ObjectYAML/DWARFYAML.h' l='295' c='_ZN4llvm4yaml13MappingTraitsINS_9DWARFYAML15AttributeAbbrevEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/include/llvm/ObjectYAML/DWARFYAML.h' l='299' c='_ZN4llvm4yaml13MappingTraitsINS_9DWARFYAML16ARangeDescriptorEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/include/llvm/ObjectYAML/DWARFYAML.h' l='303' c='_ZN4llvm4yaml13MappingTraitsINS_9DWARFYAML6ARangeEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/include/llvm/ObjectYAML/DWARFYAML.h' l='307' c='_ZN4llvm4yaml13MappingTraitsINS_9DWARFYAML10RangeEntryEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/include/llvm/ObjectYAML/DWARFYAML.h' l='311' c='_ZN4llvm4yaml13MappingTraitsINS_9DWARFYAML6RangesEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/include/llvm/ObjectYAML/DWARFYAML.h' l='315' c='_ZN4llvm4yaml13MappingTraitsINS_9DWARFYAML8PubEntryEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/include/llvm/ObjectYAML/DWARFYAML.h' l='319' c='_ZN4llvm4yaml13MappingTraitsINS_9DWARFYAML10PubSectionEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/include/llvm/ObjectYAML/DWARFYAML.h' l='323' c='_ZN4llvm4yaml13MappingTraitsINS_9DWARFYAML4UnitEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/include/llvm/ObjectYAML/DWARFYAML.h' l='327' c='_ZN4llvm4yaml13MappingTraitsINS_9DWARFYAML5EntryEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/include/llvm/ObjectYAML/DWARFYAML.h' l='331' c='_ZN4llvm4yaml13MappingTraitsINS_9DWARFYAML9FormValueEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/include/llvm/ObjectYAML/DWARFYAML.h' l='335' c='_ZN4llvm4yaml13MappingTraitsINS_9DWARFYAML4FileEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/include/llvm/ObjectYAML/DWARFYAML.h' l='339' c='_ZN4llvm4yaml13MappingTraitsINS_9DWARFYAML15LineTableOpcodeEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/include/llvm/ObjectYAML/DWARFYAML.h' l='343' c='_ZN4llvm4yaml13MappingTraitsINS_9DWARFYAML9LineTableEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/include/llvm/ObjectYAML/DWARFYAML.h' l='347' c='_ZN4llvm4yaml13MappingTraitsINS_9DWARFYAML11SegAddrPairEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/include/llvm/ObjectYAML/DWARFYAML.h' l='351' c='_ZN4llvm4yaml13MappingTraitsINS_9DWARFYAML14DWARFOperationEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/include/llvm/ObjectYAML/DWARFYAML.h' l='356' c='_ZN4llvm4yaml13MappingTraitsINS_9DWARFYAML9ListTableIT_EEE7mappingERNS0_2IOERS5_'/>
<use f='llvm/llvm/include/llvm/ObjectYAML/DWARFYAML.h' l='361' c='_ZN4llvm4yaml13MappingTraitsINS_9DWARFYAML11ListEntriesIT_EEE7mappingERNS0_2IOERS5_'/>
<use f='llvm/llvm/include/llvm/ObjectYAML/DWARFYAML.h' l='362' c='_ZN4llvm4yaml13MappingTraitsINS_9DWARFYAML11ListEntriesIT_EEE8validateB5cxx11ERNS0_2IOERS5_'/>
<use f='llvm/llvm/include/llvm/ObjectYAML/DWARFYAML.h' l='367' c='_ZN4llvm4yaml13MappingTraitsINS_9DWARFYAML12RnglistEntryEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/include/llvm/ObjectYAML/DWARFYAML.h' l='371' c='_ZN4llvm4yaml13MappingTraitsINS_9DWARFYAML12LoclistEntryEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/include/llvm/ObjectYAML/DWARFYAML.h' l='375' c='_ZN4llvm4yaml13MappingTraitsINS_9DWARFYAML14AddrTableEntryEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/include/llvm/ObjectYAML/DWARFYAML.h' l='379' c='_ZN4llvm4yaml13MappingTraitsINS_9DWARFYAML18StringOffsetsTableEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/include/llvm/ObjectYAML/DWARFYAML.h' l='383' c='_ZN4llvm4yaml23ScalarEnumerationTraitsINS_5dwarf11DwarfFormatEvE11enumerationERNS0_2IOERS3_'/>
<use f='llvm/llvm/include/llvm/ObjectYAML/DWARFYAML.h' l='393' c='_ZN4llvm4yaml23ScalarEnumerationTraitsINS_5dwarf3TagEvE11enumerationERNS0_2IOERS3_'/>
<use f='llvm/llvm/include/llvm/ObjectYAML/DWARFYAML.h' l='403' c='_ZN4llvm4yaml23ScalarEnumerationTraitsINS_5dwarf13LineNumberOpsEvE11enumerationERNS0_2IOERS3_'/>
<use f='llvm/llvm/include/llvm/ObjectYAML/DWARFYAML.h' l='413' c='_ZN4llvm4yaml23ScalarEnumerationTraitsINS_5dwarf21LineNumberExtendedOpsEvE11enumerationERNS0_2IOERS3_'/>
<use f='llvm/llvm/include/llvm/ObjectYAML/DWARFYAML.h' l='423' c='_ZN4llvm4yaml23ScalarEnumerationTraitsINS_5dwarf9AttributeEvE11enumerationERNS0_2IOERS3_'/>
<use f='llvm/llvm/include/llvm/ObjectYAML/DWARFYAML.h' l='433' c='_ZN4llvm4yaml23ScalarEnumerationTraitsINS_5dwarf4FormEvE11enumerationERNS0_2IOERS3_'/>
<use f='llvm/llvm/include/llvm/ObjectYAML/DWARFYAML.h' l='443' c='_ZN4llvm4yaml23ScalarEnumerationTraitsINS_5dwarf8UnitTypeEvE11enumerationERNS0_2IOERS3_'/>
<use f='llvm/llvm/include/llvm/ObjectYAML/DWARFYAML.h' l='450' c='_ZN4llvm4yaml23ScalarEnumerationTraitsINS_5dwarf9ConstantsEvE11enumerationERNS0_2IOERS3_'/>
<use f='llvm/llvm/include/llvm/ObjectYAML/DWARFYAML.h' l='461' c='_ZN4llvm4yaml23ScalarEnumerationTraitsINS_5dwarf14RnglistEntriesEvE11enumerationERNS0_2IOERS3_'/>
<use f='llvm/llvm/include/llvm/ObjectYAML/DWARFYAML.h' l='470' c='_ZN4llvm4yaml23ScalarEnumerationTraitsINS_5dwarf14LoclistEntriesEvE11enumerationERNS0_2IOERS3_'/>
<use f='llvm/llvm/include/llvm/ObjectYAML/DWARFYAML.h' l='479' c='_ZN4llvm4yaml23ScalarEnumerationTraitsINS_5dwarf12LocationAtomEvE11enumerationERNS0_2IOERS3_'/>
<use f='llvm/llvm/include/llvm/ObjectYAML/ELFYAML.h' l='762' c='_ZN4llvm4yaml23ScalarEnumerationTraitsINS_7ELFYAML6ELF_ETEvE11enumerationERNS0_2IOERS3_'/>
<use f='llvm/llvm/include/llvm/ObjectYAML/ELFYAML.h' l='766' c='_ZN4llvm4yaml23ScalarEnumerationTraitsINS_7ELFYAML6ELF_PTEvE11enumerationERNS0_2IOERS3_'/>
<use f='llvm/llvm/include/llvm/ObjectYAML/ELFYAML.h' l='771' c='_ZN4llvm4yaml23ScalarEnumerationTraitsINS_7ELFYAML6ELF_EMEvE11enumerationERNS0_2IOERS3_'/>
<use f='llvm/llvm/include/llvm/ObjectYAML/ELFYAML.h' l='776' c='_ZN4llvm4yaml23ScalarEnumerationTraitsINS_7ELFYAML12ELF_ELFCLASSEvE11enumerationERNS0_2IOERS3_'/>
<use f='llvm/llvm/include/llvm/ObjectYAML/ELFYAML.h' l='781' c='_ZN4llvm4yaml23ScalarEnumerationTraitsINS_7ELFYAML11ELF_ELFDATAEvE11enumerationERNS0_2IOERS3_'/>
<use f='llvm/llvm/include/llvm/ObjectYAML/ELFYAML.h' l='786' c='_ZN4llvm4yaml23ScalarEnumerationTraitsINS_7ELFYAML12ELF_ELFOSABIEvE11enumerationERNS0_2IOERS3_'/>
<use f='llvm/llvm/include/llvm/ObjectYAML/ELFYAML.h' l='791' c='_ZN4llvm4yaml18ScalarBitSetTraitsINS_7ELFYAML6ELF_EFEvE6bitsetERNS0_2IOERS3_'/>
<use f='llvm/llvm/include/llvm/ObjectYAML/ELFYAML.h' l='795' c='_ZN4llvm4yaml18ScalarBitSetTraitsINS_7ELFYAML6ELF_PFEvE6bitsetERNS0_2IOERS3_'/>
<use f='llvm/llvm/include/llvm/ObjectYAML/ELFYAML.h' l='800' c='_ZN4llvm4yaml23ScalarEnumerationTraitsINS_7ELFYAML7ELF_SHTEvE11enumerationERNS0_2IOERS3_'/>
<use f='llvm/llvm/include/llvm/ObjectYAML/ELFYAML.h' l='805' c='_ZN4llvm4yaml18ScalarBitSetTraitsINS_7ELFYAML7ELF_SHFEvE6bitsetERNS0_2IOERS3_'/>
<use f='llvm/llvm/include/llvm/ObjectYAML/ELFYAML.h' l='809' c='_ZN4llvm4yaml23ScalarEnumerationTraitsINS_7ELFYAML7ELF_SHNEvE11enumerationERNS0_2IOERS3_'/>
<use f='llvm/llvm/include/llvm/ObjectYAML/ELFYAML.h' l='813' c='_ZN4llvm4yaml23ScalarEnumerationTraitsINS_7ELFYAML7ELF_STBEvE11enumerationERNS0_2IOERS3_'/>
<use f='llvm/llvm/include/llvm/ObjectYAML/ELFYAML.h' l='818' c='_ZN4llvm4yaml23ScalarEnumerationTraitsINS_7ELFYAML7ELF_STTEvE11enumerationERNS0_2IOERS3_'/>
<use f='llvm/llvm/include/llvm/ObjectYAML/ELFYAML.h' l='823' c='_ZN4llvm4yaml23ScalarEnumerationTraitsINS_7ELFYAML7ELF_RELEvE11enumerationERNS0_2IOERS3_'/>
<use f='llvm/llvm/include/llvm/ObjectYAML/ELFYAML.h' l='828' c='_ZN4llvm4yaml23ScalarEnumerationTraitsINS_7ELFYAML10ELF_DYNTAGEvE11enumerationERNS0_2IOERS3_'/>
<use f='llvm/llvm/include/llvm/ObjectYAML/ELFYAML.h' l='833' c='_ZN4llvm4yaml23ScalarEnumerationTraitsINS_7ELFYAML7ELF_RSSEvE11enumerationERNS0_2IOERS3_'/>
<use f='llvm/llvm/include/llvm/ObjectYAML/ELFYAML.h' l='838' c='_ZN4llvm4yaml23ScalarEnumerationTraitsINS_7ELFYAML12MIPS_AFL_REGEvE11enumerationERNS0_2IOERS3_'/>
<use f='llvm/llvm/include/llvm/ObjectYAML/ELFYAML.h' l='843' c='_ZN4llvm4yaml23ScalarEnumerationTraitsINS_7ELFYAML11MIPS_ABI_FPEvE11enumerationERNS0_2IOERS3_'/>
<use f='llvm/llvm/include/llvm/ObjectYAML/ELFYAML.h' l='848' c='_ZN4llvm4yaml23ScalarEnumerationTraitsINS_7ELFYAML12MIPS_AFL_EXTEvE11enumerationERNS0_2IOERS3_'/>
<use f='llvm/llvm/include/llvm/ObjectYAML/ELFYAML.h' l='853' c='_ZN4llvm4yaml23ScalarEnumerationTraitsINS_7ELFYAML8MIPS_ISAEvE11enumerationERNS0_2IOERS3_'/>
<use f='llvm/llvm/include/llvm/ObjectYAML/ELFYAML.h' l='858' c='_ZN4llvm4yaml18ScalarBitSetTraitsINS_7ELFYAML12MIPS_AFL_ASEEvE6bitsetERNS0_2IOERS3_'/>
<use f='llvm/llvm/include/llvm/ObjectYAML/ELFYAML.h' l='863' c='_ZN4llvm4yaml18ScalarBitSetTraitsINS_7ELFYAML15MIPS_AFL_FLAGS1EvE6bitsetERNS0_2IOERS3_'/>
<use f='llvm/llvm/include/llvm/ObjectYAML/ELFYAML.h' l='868' c='_ZN4llvm4yaml13MappingTraitsINS_7ELFYAML10FileHeaderEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/include/llvm/ObjectYAML/ELFYAML.h' l='872' c='_ZN4llvm4yaml13MappingTraitsINS_7ELFYAML13SectionHeaderEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/include/llvm/ObjectYAML/ELFYAML.h' l='876' c='_ZN4llvm4yaml13MappingTraitsINS_7ELFYAML13ProgramHeaderEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/include/llvm/ObjectYAML/ELFYAML.h' l='877' c='_ZN4llvm4yaml13MappingTraitsINS_7ELFYAML13ProgramHeaderEE8validateB5cxx11ERNS0_2IOERS3_'/>
<use f='llvm/llvm/include/llvm/ObjectYAML/ELFYAML.h' l='882' c='_ZN4llvm4yaml13MappingTraitsINS_7ELFYAML6SymbolEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/include/llvm/ObjectYAML/ELFYAML.h' l='883' c='_ZN4llvm4yaml13MappingTraitsINS_7ELFYAML6SymbolEE8validateB5cxx11ERNS0_2IOERS3_'/>
<use f='llvm/llvm/include/llvm/ObjectYAML/ELFYAML.h' l='887' c='_ZN4llvm4yaml13MappingTraitsINS_7ELFYAML14StackSizeEntryEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/include/llvm/ObjectYAML/ELFYAML.h' l='891' c='_ZN4llvm4yaml13MappingTraitsINS_7ELFYAML14BBAddrMapEntryEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/include/llvm/ObjectYAML/ELFYAML.h' l='895' c='_ZN4llvm4yaml13MappingTraitsINS_7ELFYAML14BBAddrMapEntry7BBEntryEE7mappingERNS0_2IOERS4_'/>
<use f='llvm/llvm/include/llvm/ObjectYAML/ELFYAML.h' l='899' c='_ZN4llvm4yaml13MappingTraitsINS_7ELFYAML13GnuHashHeaderEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/include/llvm/ObjectYAML/ELFYAML.h' l='903' c='_ZN4llvm4yaml13MappingTraitsINS_7ELFYAML12DynamicEntryEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/include/llvm/ObjectYAML/ELFYAML.h' l='907' c='_ZN4llvm4yaml13MappingTraitsINS_7ELFYAML9NoteEntryEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/include/llvm/ObjectYAML/ELFYAML.h' l='911' c='_ZN4llvm4yaml13MappingTraitsINS_7ELFYAML11VerdefEntryEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/include/llvm/ObjectYAML/ELFYAML.h' l='915' c='_ZN4llvm4yaml13MappingTraitsINS_7ELFYAML12VerneedEntryEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/include/llvm/ObjectYAML/ELFYAML.h' l='919' c='_ZN4llvm4yaml13MappingTraitsINS_7ELFYAML12VernauxEntryEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/include/llvm/ObjectYAML/ELFYAML.h' l='923' c='_ZN4llvm4yaml13MappingTraitsINS_7ELFYAML12LinkerOptionEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/include/llvm/ObjectYAML/ELFYAML.h' l='927' c='_ZN4llvm4yaml13MappingTraitsINS_7ELFYAML14CallGraphEntryEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/include/llvm/ObjectYAML/ELFYAML.h' l='931' c='_ZN4llvm4yaml13MappingTraitsINS_7ELFYAML10RelocationEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/include/llvm/ObjectYAML/ELFYAML.h' l='935' c='_ZN4llvm4yaml13MappingTraitsINS_7ELFYAML18ARMIndexTableEntryEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/include/llvm/ObjectYAML/ELFYAML.h' l='939' c='_ZN4llvm4yaml13MappingTraitsISt10unique_ptrINS_7ELFYAML5ChunkESt14default_deleteIS4_EEE7mappingERNS0_2IOERS7_'/>
<use f='llvm/llvm/include/llvm/ObjectYAML/ELFYAML.h' l='940' c='_ZN4llvm4yaml13MappingTraitsISt10unique_ptrINS_7ELFYAML5ChunkESt14default_deleteIS4_EEE8validateB5cxx11ERNS0_2IOERS7_'/>
<use f='llvm/llvm/include/llvm/ObjectYAML/ELFYAML.h' l='945' c='_ZN4llvm4yaml13MappingTraitsINS_7ELFYAML6ObjectEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/include/llvm/ObjectYAML/ELFYAML.h' l='949' c='_ZN4llvm4yaml13MappingTraitsINS_7ELFYAML13SectionOrTypeEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/include/llvm/ObjectYAML/MachOYAML.h' l='178' c='_ZN4llvm4yaml13MappingTraitsINS_9MachOYAML10FileHeaderEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/include/llvm/ObjectYAML/MachOYAML.h' l='182' c='_ZN4llvm4yaml13MappingTraitsINS_9MachOYAML6ObjectEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/include/llvm/ObjectYAML/MachOYAML.h' l='186' c='_ZN4llvm4yaml13MappingTraitsINS_9MachOYAML9FatHeaderEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/include/llvm/ObjectYAML/MachOYAML.h' l='190' c='_ZN4llvm4yaml13MappingTraitsINS_9MachOYAML7FatArchEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/include/llvm/ObjectYAML/MachOYAML.h' l='194' c='_ZN4llvm4yaml13MappingTraitsINS_9MachOYAML15UniversalBinaryEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/include/llvm/ObjectYAML/MachOYAML.h' l='198' c='_ZN4llvm4yaml13MappingTraitsINS_9MachOYAML11LoadCommandEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/include/llvm/ObjectYAML/MachOYAML.h' l='202' c='_ZN4llvm4yaml13MappingTraitsINS_9MachOYAML12LinkEditDataEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/include/llvm/ObjectYAML/MachOYAML.h' l='206' c='_ZN4llvm4yaml13MappingTraitsINS_9MachOYAML12RebaseOpcodeEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/include/llvm/ObjectYAML/MachOYAML.h' l='210' c='_ZN4llvm4yaml13MappingTraitsINS_9MachOYAML10BindOpcodeEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/include/llvm/ObjectYAML/MachOYAML.h' l='214' c='_ZN4llvm4yaml13MappingTraitsINS_9MachOYAML11ExportEntryEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/include/llvm/ObjectYAML/MachOYAML.h' l='218' c='_ZN4llvm4yaml13MappingTraitsINS_9MachOYAML10RelocationEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/include/llvm/ObjectYAML/MachOYAML.h' l='222' c='_ZN4llvm4yaml13MappingTraitsINS_9MachOYAML7SectionEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/include/llvm/ObjectYAML/MachOYAML.h' l='223' c='_ZN4llvm4yaml13MappingTraitsINS_9MachOYAML7SectionEE8validateB5cxx11ERNS0_2IOERS3_'/>
<use f='llvm/llvm/include/llvm/ObjectYAML/MachOYAML.h' l='227' c='_ZN4llvm4yaml13MappingTraitsINS_9MachOYAML10NListEntryEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/include/llvm/ObjectYAML/MachOYAML.h' l='231' c='_ZN4llvm4yaml13MappingTraitsINS_5MachO18build_tool_versionEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/include/llvm/ObjectYAML/MachOYAML.h' l='238' c='_ZN4llvm4yaml23ScalarEnumerationTraitsINS_5MachO15LoadCommandTypeEvE11enumerationERNS0_2IOERS3_'/>
<use f='llvm/llvm/include/llvm/ObjectYAML/MachOYAML.h' l='247' c='_ZN4llvm4yaml23ScalarEnumerationTraitsINS_5MachO12RebaseOpcodeEvE11enumerationERNS0_2IOERS3_'/>
<use f='llvm/llvm/include/llvm/ObjectYAML/MachOYAML.h' l='262' c='_ZN4llvm4yaml23ScalarEnumerationTraitsINS_5MachO10BindOpcodeEvE11enumerationERNS0_2IOERS3_'/>
<use f='llvm/llvm/include/llvm/ObjectYAML/MachOYAML.h' l='310' c='_ZN4llvm4yaml13MappingTraitsINS_5MachO5dylibEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/include/llvm/ObjectYAML/MachOYAML.h' l='314' c='_ZN4llvm4yaml13MappingTraitsINS_5MachO6fvmlibEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/include/llvm/ObjectYAML/MachOYAML.h' l='318' c='_ZN4llvm4yaml13MappingTraitsINS_5MachO7sectionEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/include/llvm/ObjectYAML/MachOYAML.h' l='322' c='_ZN4llvm4yaml13MappingTraitsINS_5MachO10section_64EE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/include/llvm/ObjectYAML/MinidumpYAML.h' l='238' c='_ZN4llvm4yaml13MappingTraitsISt10unique_ptrINS_12MinidumpYAML6StreamESt14default_deleteIS4_EEE7mappingERNS0_2IOERS7_'/>
<use f='llvm/llvm/include/llvm/ObjectYAML/MinidumpYAML.h' l='239' c='_ZN4llvm4yaml13MappingTraitsISt10unique_ptrINS_12MinidumpYAML6StreamESt14default_deleteIS4_EEE8validateB5cxx11ERNS0_2IOERS7_'/>
<use f='llvm/llvm/include/llvm/ObjectYAML/MinidumpYAML.h' l='243' c='_ZN4llvm4yaml20MappingContextTraitsINS_8minidump16MemoryDescriptorENS0_9BinaryRefEE7mappingERNS0_2IOERS3_RS4_'/>
<use f='llvm/llvm/include/llvm/ObjectYAML/MinidumpYAML.h' l='251' macro='1' c='_ZN4llvm4yaml18ScalarBitSetTraitsINS_8minidump16MemoryProtectionEvE6bitsetERNS0_2IOERS3_'/>
<use f='llvm/llvm/include/llvm/ObjectYAML/MinidumpYAML.h' l='252' macro='1' c='_ZN4llvm4yaml18ScalarBitSetTraitsINS_8minidump11MemoryStateEvE6bitsetERNS0_2IOERS3_'/>
<use f='llvm/llvm/include/llvm/ObjectYAML/MinidumpYAML.h' l='253' macro='1' c='_ZN4llvm4yaml18ScalarBitSetTraitsINS_8minidump10MemoryTypeEvE6bitsetERNS0_2IOERS3_'/>
<use f='llvm/llvm/include/llvm/ObjectYAML/MinidumpYAML.h' l='255' macro='1' c='_ZN4llvm4yaml23ScalarEnumerationTraitsINS_8minidump21ProcessorArchitectureEvE11enumerationERNS0_2IOERS3_'/>
<use f='llvm/llvm/include/llvm/ObjectYAML/MinidumpYAML.h' l='256' macro='1' c='_ZN4llvm4yaml23ScalarEnumerationTraitsINS_8minidump10OSPlatformEvE11enumerationERNS0_2IOERS3_'/>
<use f='llvm/llvm/include/llvm/ObjectYAML/MinidumpYAML.h' l='257' macro='1' c='_ZN4llvm4yaml23ScalarEnumerationTraitsINS_8minidump10StreamTypeEvE11enumerationERNS0_2IOERS3_'/>
<use f='llvm/llvm/include/llvm/ObjectYAML/MinidumpYAML.h' l='259' macro='1' c='_ZN4llvm4yaml13MappingTraitsINS_8minidump7CPUInfo7ArmInfoEE7mappingERNS0_2IOERS4_'/>
<use f='llvm/llvm/include/llvm/ObjectYAML/MinidumpYAML.h' l='260' macro='1' c='_ZN4llvm4yaml13MappingTraitsINS_8minidump7CPUInfo9OtherInfoEE7mappingERNS0_2IOERS4_'/>
<use f='llvm/llvm/include/llvm/ObjectYAML/MinidumpYAML.h' l='261' macro='1' c='_ZN4llvm4yaml13MappingTraitsINS_8minidump7CPUInfo7X86InfoEE7mappingERNS0_2IOERS4_'/>
<use f='llvm/llvm/include/llvm/ObjectYAML/MinidumpYAML.h' l='262' macro='1' c='_ZN4llvm4yaml13MappingTraitsINS_8minidump9ExceptionEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/include/llvm/ObjectYAML/MinidumpYAML.h' l='263' macro='1' c='_ZN4llvm4yaml13MappingTraitsINS_8minidump10MemoryInfoEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/include/llvm/ObjectYAML/MinidumpYAML.h' l='264' macro='1' c='_ZN4llvm4yaml13MappingTraitsINS_8minidump15VSFixedFileInfoEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/include/llvm/ObjectYAML/MinidumpYAML.h' l='266' macro='1' c='_ZN4llvm4yaml13MappingTraitsINS_12MinidumpYAML6detail22ParsedMemoryDescriptorEE7mappingERNS0_2IOERS4_'/>
<use f='llvm/llvm/include/llvm/ObjectYAML/MinidumpYAML.h' l='268' macro='1' c='_ZN4llvm4yaml13MappingTraitsINS_12MinidumpYAML6detail12ParsedModuleEE7mappingERNS0_2IOERS4_'/>
<use f='llvm/llvm/include/llvm/ObjectYAML/MinidumpYAML.h' l='270' macro='1' c='_ZN4llvm4yaml13MappingTraitsINS_12MinidumpYAML6detail12ParsedThreadEE7mappingERNS0_2IOERS4_'/>
<use f='llvm/llvm/include/llvm/ObjectYAML/MinidumpYAML.h' l='279' macro='1' c='_ZN4llvm4yaml13MappingTraitsINS_12MinidumpYAML6ObjectEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/include/llvm/ObjectYAML/WasmYAML.h' l='432' c='_ZN4llvm4yaml13MappingTraitsINS_8WasmYAML10FileHeaderEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/include/llvm/ObjectYAML/WasmYAML.h' l='436' c='_ZN4llvm4yaml13MappingTraitsISt10unique_ptrINS_8WasmYAML7SectionESt14default_deleteIS4_EEE7mappingERNS0_2IOERS7_'/>
<use f='llvm/llvm/include/llvm/ObjectYAML/WasmYAML.h' l='440' c='_ZN4llvm4yaml13MappingTraitsINS_8WasmYAML6ObjectEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/include/llvm/ObjectYAML/WasmYAML.h' l='444' c='_ZN4llvm4yaml13MappingTraitsINS_8WasmYAML6ImportEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/include/llvm/ObjectYAML/WasmYAML.h' l='448' c='_ZN4llvm4yaml13MappingTraitsINS_8WasmYAML6ExportEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/include/llvm/ObjectYAML/WasmYAML.h' l='452' c='_ZN4llvm4yaml13MappingTraitsINS_8WasmYAML6GlobalEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/include/llvm/ObjectYAML/WasmYAML.h' l='456' c='_ZN4llvm4yaml18ScalarBitSetTraitsINS_8WasmYAML10LimitFlagsEvE6bitsetERNS0_2IOERS3_'/>
<use f='llvm/llvm/include/llvm/ObjectYAML/WasmYAML.h' l='460' c='_ZN4llvm4yaml18ScalarBitSetTraitsINS_8WasmYAML11SymbolFlagsEvE6bitsetERNS0_2IOERS3_'/>
<use f='llvm/llvm/include/llvm/ObjectYAML/WasmYAML.h' l='464' c='_ZN4llvm4yaml23ScalarEnumerationTraitsINS_8WasmYAML10SymbolKindEvE11enumerationERNS0_2IOERS3_'/>
<use f='llvm/llvm/include/llvm/ObjectYAML/WasmYAML.h' l='468' c='_ZN4llvm4yaml18ScalarBitSetTraitsINS_8WasmYAML12SegmentFlagsEvE6bitsetERNS0_2IOERS3_'/>
<use f='llvm/llvm/include/llvm/ObjectYAML/WasmYAML.h' l='472' c='_ZN4llvm4yaml23ScalarEnumerationTraitsINS_8WasmYAML11SectionTypeEvE11enumerationERNS0_2IOERS3_'/>
<use f='llvm/llvm/include/llvm/ObjectYAML/WasmYAML.h' l='476' c='_ZN4llvm4yaml13MappingTraitsINS_8WasmYAML9SignatureEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/include/llvm/ObjectYAML/WasmYAML.h' l='480' c='_ZN4llvm4yaml13MappingTraitsINS_8WasmYAML5TableEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/include/llvm/ObjectYAML/WasmYAML.h' l='484' c='_ZN4llvm4yaml13MappingTraitsINS_8WasmYAML6LimitsEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/include/llvm/ObjectYAML/WasmYAML.h' l='488' c='_ZN4llvm4yaml13MappingTraitsINS_8WasmYAML8FunctionEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/include/llvm/ObjectYAML/WasmYAML.h' l='492' c='_ZN4llvm4yaml13MappingTraitsINS_8WasmYAML10RelocationEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/include/llvm/ObjectYAML/WasmYAML.h' l='496' c='_ZN4llvm4yaml13MappingTraitsINS_8WasmYAML9NameEntryEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/include/llvm/ObjectYAML/WasmYAML.h' l='500' c='_ZN4llvm4yaml13MappingTraitsINS_8WasmYAML13ProducerEntryEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/include/llvm/ObjectYAML/WasmYAML.h' l='504' c='_ZN4llvm4yaml23ScalarEnumerationTraitsINS_8WasmYAML19FeaturePolicyPrefixEvE11enumerationERNS0_2IOERS3_'/>
<use f='llvm/llvm/include/llvm/ObjectYAML/WasmYAML.h' l='508' c='_ZN4llvm4yaml13MappingTraitsINS_8WasmYAML12FeatureEntryEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/include/llvm/ObjectYAML/WasmYAML.h' l='512' c='_ZN4llvm4yaml13MappingTraitsINS_8WasmYAML11SegmentInfoEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/include/llvm/ObjectYAML/WasmYAML.h' l='516' c='_ZN4llvm4yaml13MappingTraitsINS_8WasmYAML9LocalDeclEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/include/llvm/ObjectYAML/WasmYAML.h' l='520' c='_ZN4llvm4yaml13MappingTraitsINS_4wasm12WasmInitExprEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/include/llvm/ObjectYAML/WasmYAML.h' l='524' c='_ZN4llvm4yaml13MappingTraitsINS_8WasmYAML11DataSegmentEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/include/llvm/ObjectYAML/WasmYAML.h' l='528' c='_ZN4llvm4yaml13MappingTraitsINS_8WasmYAML11ElemSegmentEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/include/llvm/ObjectYAML/WasmYAML.h' l='532' c='_ZN4llvm4yaml13MappingTraitsINS_8WasmYAML10SymbolInfoEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/include/llvm/ObjectYAML/WasmYAML.h' l='536' c='_ZN4llvm4yaml13MappingTraitsINS_8WasmYAML12InitFunctionEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/include/llvm/ObjectYAML/WasmYAML.h' l='540' c='_ZN4llvm4yaml23ScalarEnumerationTraitsINS_8WasmYAML10ComdatKindEvE11enumerationERNS0_2IOERS3_'/>
<use f='llvm/llvm/include/llvm/ObjectYAML/WasmYAML.h' l='544' c='_ZN4llvm4yaml13MappingTraitsINS_8WasmYAML11ComdatEntryEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/include/llvm/ObjectYAML/WasmYAML.h' l='548' c='_ZN4llvm4yaml13MappingTraitsINS_8WasmYAML6ComdatEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/include/llvm/ObjectYAML/WasmYAML.h' l='552' c='_ZN4llvm4yaml23ScalarEnumerationTraitsINS_8WasmYAML9ValueTypeEvE11enumerationERNS0_2IOERS3_'/>
<use f='llvm/llvm/include/llvm/ObjectYAML/WasmYAML.h' l='556' c='_ZN4llvm4yaml23ScalarEnumerationTraitsINS_8WasmYAML10ExportKindEvE11enumerationERNS0_2IOERS3_'/>
<use f='llvm/llvm/include/llvm/ObjectYAML/WasmYAML.h' l='560' c='_ZN4llvm4yaml23ScalarEnumerationTraitsINS_8WasmYAML9TableTypeEvE11enumerationERNS0_2IOERS3_'/>
<use f='llvm/llvm/include/llvm/ObjectYAML/WasmYAML.h' l='564' c='_ZN4llvm4yaml23ScalarEnumerationTraitsINS_8WasmYAML6OpcodeEvE11enumerationERNS0_2IOERS3_'/>
<use f='llvm/llvm/include/llvm/ObjectYAML/WasmYAML.h' l='568' c='_ZN4llvm4yaml23ScalarEnumerationTraitsINS_8WasmYAML9RelocTypeEvE11enumerationERNS0_2IOERS3_'/>
<use f='llvm/llvm/include/llvm/ObjectYAML/WasmYAML.h' l='572' c='_ZN4llvm4yaml13MappingTraitsINS_8WasmYAML5EventEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/include/llvm/ObjectYAML/ObjectYAML.h' l='37' c='_ZN4llvm4yaml13MappingTraitsINS0_14YamlObjectFileEE7mappingERNS0_2IOERS2_'/>
<size>16</size>
<use f='llvm/llvm/lib/ObjectYAML/COFFYAML.cpp' l='34' c='_ZN4llvm4yaml23ScalarEnumerationTraitsINS_8COFFYAML10COMDATTypeEvE11enumerationERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/COFFYAML.cpp' l='47' c='_ZN4llvm4yaml23ScalarEnumerationTraitsINS_8COFFYAML27WeakExternalCharacteristicsEvE11enumerationERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/COFFYAML.cpp' l='55' c='_ZN4llvm4yaml23ScalarEnumerationTraitsINS_8COFFYAML13AuxSymbolTypeEvE11enumerationERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/COFFYAML.cpp' l='60' c='_ZN4llvm4yaml23ScalarEnumerationTraitsINS_4COFF12MachineTypesEvE11enumerationERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/COFFYAML.cpp' l='86' c='_ZN4llvm4yaml23ScalarEnumerationTraitsINS_4COFF14SymbolBaseTypeEvE11enumerationERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/COFFYAML.cpp' l='106' c='_ZN4llvm4yaml23ScalarEnumerationTraitsINS_4COFF18SymbolStorageClassEvE11enumerationERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/COFFYAML.cpp' l='137' c='_ZN4llvm4yaml23ScalarEnumerationTraitsINS_4COFF17SymbolComplexTypeEvE11enumerationERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/COFFYAML.cpp' l='145' c='_ZN4llvm4yaml23ScalarEnumerationTraitsINS_4COFF18RelocationTypeI386EvE11enumerationERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/COFFYAML.cpp' l='160' c='_ZN4llvm4yaml23ScalarEnumerationTraitsINS_4COFF19RelocationTypeAMD64EvE11enumerationERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/COFFYAML.cpp' l='181' c='_ZN4llvm4yaml23ScalarEnumerationTraitsINS_4COFF18RelocationTypesARMEvE11enumerationERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/COFFYAML.cpp' l='202' c='_ZN4llvm4yaml23ScalarEnumerationTraitsINS_4COFF20RelocationTypesARM64EvE11enumerationERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/COFFYAML.cpp' l='224' c='_ZN4llvm4yaml23ScalarEnumerationTraitsINS_4COFF16WindowsSubsystemEvE11enumerationERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/COFFYAML.cpp' l='244' c='_ZN4llvm4yaml18ScalarBitSetTraitsINS_4COFF15CharacteristicsEvE6bitsetERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/COFFYAML.cpp' l='263' c='_ZN4llvm4yaml18ScalarBitSetTraitsINS_4COFF22SectionCharacteristicsEvE6bitsetERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/COFFYAML.cpp' l='289' c='_ZN4llvm4yaml18ScalarBitSetTraitsINS_4COFF18DLLCharacteristicsEvE6bitsetERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/COFFYAML.cpp' l='307' c='_ZN4llvm4yaml12_GLOBAL__N_121NSectionSelectionTypeC1ERNS0_2IOE'/>
<use f='llvm/llvm/lib/ObjectYAML/COFFYAML.cpp' l='309' c='_ZN4llvm4yaml12_GLOBAL__N_121NSectionSelectionTypeC1ERNS0_2IOEh'/>
<use f='llvm/llvm/lib/ObjectYAML/COFFYAML.cpp' l='312' c='_ZN4llvm4yaml12_GLOBAL__N_121NSectionSelectionType11denormalizeERNS0_2IOE'/>
<use f='llvm/llvm/lib/ObjectYAML/COFFYAML.cpp' l='318' c='_ZN4llvm4yaml12_GLOBAL__N_128NWeakExternalCharacteristicsC1ERNS0_2IOE'/>
<use f='llvm/llvm/lib/ObjectYAML/COFFYAML.cpp' l='320' c='_ZN4llvm4yaml12_GLOBAL__N_128NWeakExternalCharacteristicsC1ERNS0_2IOEj'/>
<use f='llvm/llvm/lib/ObjectYAML/COFFYAML.cpp' l='323' c='_ZN4llvm4yaml12_GLOBAL__N_128NWeakExternalCharacteristics11denormalizeERNS0_2IOE'/>
<use f='llvm/llvm/lib/ObjectYAML/COFFYAML.cpp' l='329' c='_ZN4llvm4yaml12_GLOBAL__N_123NSectionCharacteristicsC1ERNS0_2IOE'/>
<use f='llvm/llvm/lib/ObjectYAML/COFFYAML.cpp' l='331' c='_ZN4llvm4yaml12_GLOBAL__N_123NSectionCharacteristicsC1ERNS0_2IOEj'/>
<use f='llvm/llvm/lib/ObjectYAML/COFFYAML.cpp' l='334' c='_ZN4llvm4yaml12_GLOBAL__N_123NSectionCharacteristics11denormalizeERNS0_2IOE'/>
<use f='llvm/llvm/lib/ObjectYAML/COFFYAML.cpp' l='340' c='_ZN4llvm4yaml12_GLOBAL__N_113NAuxTokenTypeC1ERNS0_2IOE'/>
<use f='llvm/llvm/lib/ObjectYAML/COFFYAML.cpp' l='342' c='_ZN4llvm4yaml12_GLOBAL__N_113NAuxTokenTypeC1ERNS0_2IOEh'/>
<use f='llvm/llvm/lib/ObjectYAML/COFFYAML.cpp' l='345' c='_ZN4llvm4yaml12_GLOBAL__N_113NAuxTokenType11denormalizeERNS0_2IOE'/>
<use f='llvm/llvm/lib/ObjectYAML/COFFYAML.cpp' l='351' c='_ZN4llvm4yaml12_GLOBAL__N_113NStorageClassC1ERNS0_2IOE'/>
<use f='llvm/llvm/lib/ObjectYAML/COFFYAML.cpp' l='352' c='_ZN4llvm4yaml12_GLOBAL__N_113NStorageClassC1ERNS0_2IOEh'/>
<use f='llvm/llvm/lib/ObjectYAML/COFFYAML.cpp' l='354' c='_ZN4llvm4yaml12_GLOBAL__N_113NStorageClass11denormalizeERNS0_2IOE'/>
<use f='llvm/llvm/lib/ObjectYAML/COFFYAML.cpp' l='360' c='_ZN4llvm4yaml12_GLOBAL__N_18NMachineC1ERNS0_2IOE'/>
<use f='llvm/llvm/lib/ObjectYAML/COFFYAML.cpp' l='361' c='_ZN4llvm4yaml12_GLOBAL__N_18NMachineC1ERNS0_2IOEt'/>
<use f='llvm/llvm/lib/ObjectYAML/COFFYAML.cpp' l='363' c='_ZN4llvm4yaml12_GLOBAL__N_18NMachine11denormalizeERNS0_2IOE'/>
<use f='llvm/llvm/lib/ObjectYAML/COFFYAML.cpp' l='369' c='_ZN4llvm4yaml12_GLOBAL__N_122NHeaderCharacteristicsC1ERNS0_2IOE'/>
<use f='llvm/llvm/lib/ObjectYAML/COFFYAML.cpp' l='370' c='_ZN4llvm4yaml12_GLOBAL__N_122NHeaderCharacteristicsC1ERNS0_2IOEt'/>
<use f='llvm/llvm/lib/ObjectYAML/COFFYAML.cpp' l='373' c='_ZN4llvm4yaml12_GLOBAL__N_122NHeaderCharacteristics11denormalizeERNS0_2IOE'/>
<use f='llvm/llvm/lib/ObjectYAML/COFFYAML.cpp' l='380' c='_ZN4llvm4yaml12_GLOBAL__N_15NTypeC1ERNS0_2IOE'/>
<use f='llvm/llvm/lib/ObjectYAML/COFFYAML.cpp' l='381' c='_ZN4llvm4yaml12_GLOBAL__N_15NTypeC1ERNS0_2IOEt'/>
<use f='llvm/llvm/lib/ObjectYAML/COFFYAML.cpp' l='383' c='_ZN4llvm4yaml12_GLOBAL__N_15NType11denormalizeERNS0_2IOE'/>
<use f='llvm/llvm/lib/ObjectYAML/COFFYAML.cpp' l='389' c='_ZN4llvm4yaml12_GLOBAL__N_117NWindowsSubsystemC1ERNS0_2IOE'/>
<use f='llvm/llvm/lib/ObjectYAML/COFFYAML.cpp' l='390' c='_ZN4llvm4yaml12_GLOBAL__N_117NWindowsSubsystemC1ERNS0_2IOEt'/>
<use f='llvm/llvm/lib/ObjectYAML/COFFYAML.cpp' l='392' c='_ZN4llvm4yaml12_GLOBAL__N_117NWindowsSubsystem11denormalizeERNS0_2IOE'/>
<use f='llvm/llvm/lib/ObjectYAML/COFFYAML.cpp' l='398' c='_ZN4llvm4yaml12_GLOBAL__N_119NDLLCharacteristicsC1ERNS0_2IOE'/>
<use f='llvm/llvm/lib/ObjectYAML/COFFYAML.cpp' l='399' c='_ZN4llvm4yaml12_GLOBAL__N_119NDLLCharacteristicsC1ERNS0_2IOEt'/>
<use f='llvm/llvm/lib/ObjectYAML/COFFYAML.cpp' l='402' c='_ZN4llvm4yaml12_GLOBAL__N_119NDLLCharacteristics11denormalizeERNS0_2IOE'/>
<use f='llvm/llvm/lib/ObjectYAML/COFFYAML.cpp' l='409' c='_ZN4llvm4yaml13MappingTraitsINS_8COFFYAML10RelocationEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/COFFYAML.cpp' l='437' c='_ZN4llvm4yaml13MappingTraitsINS_4COFF13DataDirectoryEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/COFFYAML.cpp' l='443' c='_ZN4llvm4yaml13MappingTraitsINS_8COFFYAML8PEHeaderEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/COFFYAML.cpp' l='490' c='_ZN4llvm4yaml13MappingTraitsINS_4COFF6headerEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/COFFYAML.cpp' l='501' c='_ZN4llvm4yaml13MappingTraitsINS_4COFF27AuxiliaryFunctionDefinitionEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/COFFYAML.cpp' l='509' c='_ZN4llvm4yaml13MappingTraitsINS_4COFF22AuxiliarybfAndefSymbolEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/COFFYAML.cpp' l='515' c='_ZN4llvm4yaml13MappingTraitsINS_4COFF21AuxiliaryWeakExternalEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/COFFYAML.cpp' l='523' c='_ZN4llvm4yaml13MappingTraitsINS_4COFF26AuxiliarySectionDefinitionEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/COFFYAML.cpp' l='536' c='_ZN4llvm4yaml13MappingTraitsINS_4COFF17AuxiliaryCLRTokenEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/COFFYAML.cpp' l='542' c='_ZN4llvm4yaml13MappingTraitsINS_8COFFYAML6SymbolEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/COFFYAML.cpp' l='559' c='_ZN4llvm4yaml13MappingTraitsINS_8COFFYAML7SectionEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/COFFYAML.cpp' l='590' c='_ZN4llvm4yaml13MappingTraitsINS_8COFFYAML6ObjectEE7mappingERNS0_2IOERS3_'/>
<size>16</size>
<use f='llvm/llvm/include/llvm/ObjectYAML/CodeViewYAMLSymbols.h' l='45' macro='1' c='_ZN4llvm4yaml13MappingTraitsINS_12CodeViewYAML12SymbolRecordEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/CodeViewYAMLDebugSections.cpp' l='69' macro='1' c='_ZN4llvm4yaml23ScalarEnumerationTraitsINS_8codeview19DebugSubsectionKindEvE11enumerationERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/CodeViewYAMLDebugSections.cpp' l='70' macro='1' c='_ZN4llvm4yaml23ScalarEnumerationTraitsINS_8codeview16FileChecksumKindEvE11enumerationERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/CodeViewYAMLDebugSections.cpp' l='71' macro='1' c='_ZN4llvm4yaml18ScalarBitSetTraitsINS_8codeview9LineFlagsEvE6bitsetERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/CodeViewYAMLDebugSections.cpp' l='73' macro='1' c='_ZN4llvm4yaml13MappingTraitsINS_8codeview17CrossModuleExportEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/CodeViewYAMLDebugSections.cpp' l='74' macro='1' c='_ZN4llvm4yaml13MappingTraitsINS_12CodeViewYAML13YAMLFrameDataEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/CodeViewYAMLDebugSections.cpp' l='75' macro='1' c='_ZN4llvm4yaml13MappingTraitsINS_12CodeViewYAML21YAMLCrossModuleImportEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/CodeViewYAMLDebugSections.cpp' l='76' macro='1' c='_ZN4llvm4yaml13MappingTraitsINS_8codeview21CrossModuleImportItemEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/CodeViewYAMLDebugSections.cpp' l='77' macro='1' c='_ZN4llvm4yaml13MappingTraitsINS_12CodeViewYAML15SourceLineEntryEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/CodeViewYAMLDebugSections.cpp' l='78' macro='1' c='_ZN4llvm4yaml13MappingTraitsINS_12CodeViewYAML17SourceColumnEntryEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/CodeViewYAMLDebugSections.cpp' l='79' macro='1' c='_ZN4llvm4yaml13MappingTraitsINS_12CodeViewYAML23SourceFileChecksumEntryEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/CodeViewYAMLDebugSections.cpp' l='80' macro='1' c='_ZN4llvm4yaml13MappingTraitsINS_12CodeViewYAML15SourceLineBlockEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/CodeViewYAMLDebugSections.cpp' l='81' macro='1' c='_ZN4llvm4yaml13MappingTraitsINS_12CodeViewYAML11InlineeSiteEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/CodeViewYAMLDebugSections.cpp' l='91' c='_ZN4llvm12CodeViewYAML6detail18YAMLSubsectionBase3mapERNS_4yaml2IOE'/>
<use f='llvm/llvm/lib/ObjectYAML/CodeViewYAMLDebugSections.cpp' l='109' c='_ZN12_GLOBAL__N_123YAMLChecksumsSubsection3mapERN4llvm4yaml2IOE'/>
<use f='llvm/llvm/lib/ObjectYAML/CodeViewYAMLDebugSections.cpp' l='123' c='_ZN12_GLOBAL__N_119YAMLLinesSubsection3mapERN4llvm4yaml2IOE'/>
<use f='llvm/llvm/lib/ObjectYAML/CodeViewYAMLDebugSections.cpp' l='139' c='_ZN12_GLOBAL__N_126YAMLInlineeLinesSubsection3mapERN4llvm4yaml2IOE'/>
<use f='llvm/llvm/lib/ObjectYAML/CodeViewYAMLDebugSections.cpp' l='155' c='_ZN12_GLOBAL__N_132YAMLCrossModuleExportsSubsection3mapERN4llvm4yaml2IOE'/>
<use f='llvm/llvm/lib/ObjectYAML/CodeViewYAMLDebugSections.cpp' l='169' c='_ZN12_GLOBAL__N_132YAMLCrossModuleImportsSubsection3mapERN4llvm4yaml2IOE'/>
<use f='llvm/llvm/lib/ObjectYAML/CodeViewYAMLDebugSections.cpp' l='183' c='_ZN12_GLOBAL__N_121YAMLSymbolsSubsection3mapERN4llvm4yaml2IOE'/>
<use f='llvm/llvm/lib/ObjectYAML/CodeViewYAMLDebugSections.cpp' l='197' c='_ZN12_GLOBAL__N_125YAMLStringTableSubsection3mapERN4llvm4yaml2IOE'/>
<use f='llvm/llvm/lib/ObjectYAML/CodeViewYAMLDebugSections.cpp' l='211' c='_ZN12_GLOBAL__N_123YAMLFrameDataSubsection3mapERN4llvm4yaml2IOE'/>
<use f='llvm/llvm/lib/ObjectYAML/CodeViewYAMLDebugSections.cpp' l='226' c='_ZN12_GLOBAL__N_127YAMLCoffSymbolRVASubsection3mapERN4llvm4yaml2IOE'/>
<use f='llvm/llvm/lib/ObjectYAML/CodeViewYAMLDebugSections.cpp' l='238' c='_ZN4llvm4yaml18ScalarBitSetTraitsINS_8codeview9LineFlagsEvE6bitsetERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/CodeViewYAMLDebugSections.cpp' l='244' c='_ZN4llvm4yaml23ScalarEnumerationTraitsINS_8codeview16FileChecksumKindEvE11enumerationERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/CodeViewYAMLDebugSections.cpp' l='265' c='_ZN4llvm4yaml13MappingTraitsINS_12CodeViewYAML15SourceLineEntryEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/CodeViewYAMLDebugSections.cpp' l='272' c='_ZN4llvm4yaml13MappingTraitsINS_12CodeViewYAML17SourceColumnEntryEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/CodeViewYAMLDebugSections.cpp' l='277' c='_ZN4llvm4yaml13MappingTraitsINS_12CodeViewYAML15SourceLineBlockEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/CodeViewYAMLDebugSections.cpp' l='283' c='_ZN4llvm4yaml13MappingTraitsINS_8codeview17CrossModuleExportEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/CodeViewYAMLDebugSections.cpp' l='288' c='_ZN4llvm4yaml13MappingTraitsINS_12CodeViewYAML21YAMLCrossModuleImportEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/CodeViewYAMLDebugSections.cpp' l='295' c='_ZN4llvm4yaml13MappingTraitsINS_12CodeViewYAML23SourceFileChecksumEntryEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/CodeViewYAMLDebugSections.cpp' l='301' c='_ZN4llvm4yaml13MappingTraitsINS_12CodeViewYAML11InlineeSiteEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/CodeViewYAMLDebugSections.cpp' l='308' c='_ZN4llvm4yaml13MappingTraitsINS_12CodeViewYAML13YAMLFrameDataEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/CodeViewYAMLDebugSections.cpp' l='319' c='_ZN12_GLOBAL__N_123YAMLChecksumsSubsection3mapERN4llvm4yaml2IOE'/>
<use f='llvm/llvm/lib/ObjectYAML/CodeViewYAMLDebugSections.cpp' l='324' c='_ZN12_GLOBAL__N_119YAMLLinesSubsection3mapERN4llvm4yaml2IOE'/>
<use f='llvm/llvm/lib/ObjectYAML/CodeViewYAMLDebugSections.cpp' l='334' c='_ZN12_GLOBAL__N_126YAMLInlineeLinesSubsection3mapERN4llvm4yaml2IOE'/>
<use f='llvm/llvm/lib/ObjectYAML/CodeViewYAMLDebugSections.cpp' l='340' c='_ZN12_GLOBAL__N_132YAMLCrossModuleExportsSubsection3mapERN4llvm4yaml2IOE'/>
<use f='llvm/llvm/lib/ObjectYAML/CodeViewYAMLDebugSections.cpp' l='345' c='_ZN12_GLOBAL__N_132YAMLCrossModuleImportsSubsection3mapERN4llvm4yaml2IOE'/>
<use f='llvm/llvm/lib/ObjectYAML/CodeViewYAMLDebugSections.cpp' l='350' c='_ZN12_GLOBAL__N_121YAMLSymbolsSubsection3mapERN4llvm4yaml2IOE'/>
<use f='llvm/llvm/lib/ObjectYAML/CodeViewYAMLDebugSections.cpp' l='355' c='_ZN12_GLOBAL__N_125YAMLStringTableSubsection3mapERN4llvm4yaml2IOE'/>
<use f='llvm/llvm/lib/ObjectYAML/CodeViewYAMLDebugSections.cpp' l='360' c='_ZN12_GLOBAL__N_123YAMLFrameDataSubsection3mapERN4llvm4yaml2IOE'/>
<use f='llvm/llvm/lib/ObjectYAML/CodeViewYAMLDebugSections.cpp' l='365' c='_ZN12_GLOBAL__N_127YAMLCoffSymbolRVASubsection3mapERN4llvm4yaml2IOE'/>
<use f='llvm/llvm/lib/ObjectYAML/CodeViewYAMLDebugSections.cpp' l='371' c='_ZN4llvm4yaml13MappingTraitsINS_12CodeViewYAML19YAMLDebugSubsectionEE7mappingERNS0_2IOERS3_'/>
<size>16</size>
<use f='llvm/llvm/lib/ObjectYAML/CodeViewYAMLSymbols.cpp' l='48' macro='1' c='_ZN4llvm4yaml23ScalarEnumerationTraitsINS_8codeview10SymbolKindEvE11enumerationERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/CodeViewYAMLSymbols.cpp' l='49' macro='1' c='_ZN4llvm4yaml23ScalarEnumerationTraitsINS_8codeview15FrameCookieKindEvE11enumerationERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/CodeViewYAMLSymbols.cpp' l='51' macro='1' c='_ZN4llvm4yaml18ScalarBitSetTraitsINS_8codeview16CompileSym2FlagsEvE6bitsetERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/CodeViewYAMLSymbols.cpp' l='52' macro='1' c='_ZN4llvm4yaml18ScalarBitSetTraitsINS_8codeview16CompileSym3FlagsEvE6bitsetERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/CodeViewYAMLSymbols.cpp' l='53' macro='1' c='_ZN4llvm4yaml18ScalarBitSetTraitsINS_8codeview11ExportFlagsEvE6bitsetERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/CodeViewYAMLSymbols.cpp' l='54' macro='1' c='_ZN4llvm4yaml18ScalarBitSetTraitsINS_8codeview14PublicSymFlagsEvE6bitsetERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/CodeViewYAMLSymbols.cpp' l='55' macro='1' c='_ZN4llvm4yaml18ScalarBitSetTraitsINS_8codeview13LocalSymFlagsEvE6bitsetERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/CodeViewYAMLSymbols.cpp' l='56' macro='1' c='_ZN4llvm4yaml18ScalarBitSetTraitsINS_8codeview12ProcSymFlagsEvE6bitsetERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/CodeViewYAMLSymbols.cpp' l='57' macro='1' c='_ZN4llvm4yaml18ScalarBitSetTraitsINS_8codeview21FrameProcedureOptionsEvE6bitsetERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/CodeViewYAMLSymbols.cpp' l='58' macro='1' c='_ZN4llvm4yaml23ScalarEnumerationTraitsINS_8codeview7CPUTypeEvE11enumerationERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/CodeViewYAMLSymbols.cpp' l='59' macro='1' c='_ZN4llvm4yaml23ScalarEnumerationTraitsINS_8codeview10RegisterIdEvE11enumerationERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/CodeViewYAMLSymbols.cpp' l='60' macro='1' c='_ZN4llvm4yaml23ScalarEnumerationTraitsINS_8codeview14TrampolineTypeEvE11enumerationERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/CodeViewYAMLSymbols.cpp' l='61' macro='1' c='_ZN4llvm4yaml23ScalarEnumerationTraitsINS_8codeview12ThunkOrdinalEvE11enumerationERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/CodeViewYAMLSymbols.cpp' l='76' c='_ZN4llvm4yaml23ScalarEnumerationTraitsINS_8codeview10SymbolKindEvE11enumerationERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/CodeViewYAMLSymbols.cpp' l='83' c='_ZN4llvm4yaml18ScalarBitSetTraitsINS_8codeview16CompileSym2FlagsEvE6bitsetERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/CodeViewYAMLSymbols.cpp' l='92' c='_ZN4llvm4yaml18ScalarBitSetTraitsINS_8codeview16CompileSym3FlagsEvE6bitsetERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/CodeViewYAMLSymbols.cpp' l='101' c='_ZN4llvm4yaml18ScalarBitSetTraitsINS_8codeview11ExportFlagsEvE6bitsetERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/CodeViewYAMLSymbols.cpp' l='109' c='_ZN4llvm4yaml18ScalarBitSetTraitsINS_8codeview14PublicSymFlagsEvE6bitsetERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/CodeViewYAMLSymbols.cpp' l='117' c='_ZN4llvm4yaml18ScalarBitSetTraitsINS_8codeview13LocalSymFlagsEvE6bitsetERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/CodeViewYAMLSymbols.cpp' l='125' c='_ZN4llvm4yaml18ScalarBitSetTraitsINS_8codeview12ProcSymFlagsEvE6bitsetERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/CodeViewYAMLSymbols.cpp' l='134' c='_ZN4llvm4yaml18ScalarBitSetTraitsINS_8codeview21FrameProcedureOptionsEvE6bitsetERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/CodeViewYAMLSymbols.cpp' l='142' c='_ZN4llvm4yaml23ScalarEnumerationTraitsINS_8codeview7CPUTypeEvE11enumerationERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/CodeViewYAMLSymbols.cpp' l='149' c='_ZN4llvm4yaml23ScalarEnumerationTraitsINS_8codeview10RegisterIdEvE11enumerationERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/CodeViewYAMLSymbols.cpp' l='181' c='_ZN4llvm4yaml23ScalarEnumerationTraitsINS_8codeview14TrampolineTypeEvE11enumerationERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/CodeViewYAMLSymbols.cpp' l='189' c='_ZN4llvm4yaml23ScalarEnumerationTraitsINS_8codeview12ThunkOrdinalEvE11enumerationERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/CodeViewYAMLSymbols.cpp' l='198' c='_ZN4llvm4yaml23ScalarEnumerationTraitsINS_8codeview15FrameCookieKindEvE11enumerationERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/CodeViewYAMLSymbols.cpp' l='209' c='_ZN4llvm4yaml13MappingTraitsINS_8codeview22LocalVariableAddrRangeEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/CodeViewYAMLSymbols.cpp' l='216' c='_ZN4llvm4yaml13MappingTraitsINS_8codeview20LocalVariableAddrGapEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/CodeViewYAMLSymbols.cpp' l='234' c='_ZN4llvm12CodeViewYAML6detail16SymbolRecordBase3mapERNS_4yaml2IOE'/>
<use f='llvm/llvm/lib/ObjectYAML/CodeViewYAMLSymbols.cpp' l='245' c='_ZN4llvm12CodeViewYAML6detail16SymbolRecordImpl3mapERNS_4yaml2IOE'/>
<use f='llvm/llvm/lib/ObjectYAML/CodeViewYAMLSymbols.cpp' l='263' c='_ZN4llvm12CodeViewYAML6detail19UnknownSymbolRecord3mapERNS_4yaml2IOE'/>
<use f='llvm/llvm/lib/ObjectYAML/CodeViewYAMLSymbols.cpp' l='286' c='_ZN4llvm12CodeViewYAML6detail16SymbolRecordImpl3mapERNS_4yaml2IOE'/>
<use f='llvm/llvm/lib/ObjectYAML/CodeViewYAMLSymbols.cpp' l='288' c='_ZN4llvm12CodeViewYAML6detail19UnknownSymbolRecord3mapERNS_4yaml2IOE'/>
<use f='llvm/llvm/lib/ObjectYAML/CodeViewYAMLSymbols.cpp' l='302' c='_ZN4llvm12CodeViewYAML6detail16SymbolRecordImpl3mapERNS_4yaml2IOE'/>
<use f='llvm/llvm/lib/ObjectYAML/CodeViewYAMLSymbols.cpp' l='312' c='_ZN4llvm12CodeViewYAML6detail16SymbolRecordImpl3mapERNS_4yaml2IOE'/>
<use f='llvm/llvm/lib/ObjectYAML/CodeViewYAMLSymbols.cpp' l='321' c='_ZN4llvm12CodeViewYAML6detail16SymbolRecordImpl3mapERNS_4yaml2IOE'/>
<use f='llvm/llvm/lib/ObjectYAML/CodeViewYAMLSymbols.cpp' l='330' c='_ZN4llvm12CodeViewYAML6detail16SymbolRecordImpl3mapERNS_4yaml2IOE'/>
<use f='llvm/llvm/lib/ObjectYAML/CodeViewYAMLSymbols.cpp' l='338' c='_ZN4llvm12CodeViewYAML6detail16SymbolRecordImpl3mapERNS_4yaml2IOE'/>
<use f='llvm/llvm/lib/ObjectYAML/CodeViewYAMLSymbols.cpp' l='344' c='_ZN4llvm12CodeViewYAML6detail16SymbolRecordImpl3mapERNS_4yaml2IOE'/>
<use f='llvm/llvm/lib/ObjectYAML/CodeViewYAMLSymbols.cpp' l='358' c='_ZN4llvm12CodeViewYAML6detail16SymbolRecordImpl3mapERNS_4yaml2IOE'/>
<use f='llvm/llvm/lib/ObjectYAML/CodeViewYAMLSymbols.cpp' l='364' c='_ZN4llvm12CodeViewYAML6detail16SymbolRecordImpl3mapERNS_4yaml2IOE'/>
<use f='llvm/llvm/lib/ObjectYAML/CodeViewYAMLSymbols.cpp' l='371' c='_ZN4llvm12CodeViewYAML6detail16SymbolRecordImpl3mapERNS_4yaml2IOE'/>
<use f='llvm/llvm/lib/ObjectYAML/CodeViewYAMLSymbols.cpp' l='378' c='_ZN4llvm12CodeViewYAML6detail16SymbolRecordImpl3mapERNS_4yaml2IOE'/>
<use f='llvm/llvm/lib/ObjectYAML/CodeViewYAMLSymbols.cpp' l='382' c='_ZN4llvm12CodeViewYAML6detail16SymbolRecordImpl3mapERNS_4yaml2IOE'/>
<use f='llvm/llvm/lib/ObjectYAML/CodeViewYAMLSymbols.cpp' l='389' c='_ZN4llvm12CodeViewYAML6detail16SymbolRecordImpl3mapERNS_4yaml2IOE'/>
<use f='llvm/llvm/lib/ObjectYAML/CodeViewYAMLSymbols.cpp' l='396' c='_ZN4llvm12CodeViewYAML6detail16SymbolRecordImpl3mapERNS_4yaml2IOE'/>
<use f='llvm/llvm/lib/ObjectYAML/CodeViewYAMLSymbols.cpp' l='402' c='_ZN4llvm12CodeViewYAML6detail16SymbolRecordImpl3mapERNS_4yaml2IOE'/>
<use f='llvm/llvm/lib/ObjectYAML/CodeViewYAMLSymbols.cpp' l='409' c='_ZN4llvm12CodeViewYAML6detail16SymbolRecordImpl3mapERNS_4yaml2IOE'/>
<use f='llvm/llvm/lib/ObjectYAML/CodeViewYAMLSymbols.cpp' l='416' c='_ZN4llvm12CodeViewYAML6detail16SymbolRecordImpl3mapERNS_4yaml2IOE'/>
<use f='llvm/llvm/lib/ObjectYAML/CodeViewYAMLSymbols.cpp' l='422' c='_ZN4llvm12CodeViewYAML6detail16SymbolRecordImpl3mapERNS_4yaml2IOE'/>
<use f='llvm/llvm/lib/ObjectYAML/CodeViewYAMLSymbols.cpp' l='431' c='_ZN4llvm12CodeViewYAML6detail16SymbolRecordImpl3mapERNS_4yaml2IOE'/>
<use f='llvm/llvm/lib/ObjectYAML/CodeViewYAMLSymbols.cpp' l='435' c='_ZN4llvm12CodeViewYAML6detail16SymbolRecordImpl3mapERNS_4yaml2IOE'/>
<use f='llvm/llvm/lib/ObjectYAML/CodeViewYAMLSymbols.cpp' l='443' c='_ZN4llvm12CodeViewYAML6detail16SymbolRecordImpl3mapERNS_4yaml2IOE'/>
<use f='llvm/llvm/lib/ObjectYAML/CodeViewYAMLSymbols.cpp' l='452' c='_ZN4llvm12CodeViewYAML6detail16SymbolRecordImpl3mapERNS_4yaml2IOE'/>
<use f='llvm/llvm/lib/ObjectYAML/CodeViewYAMLSymbols.cpp' l='460' c='_ZN4llvm12CodeViewYAML6detail16SymbolRecordImpl3mapERNS_4yaml2IOE'/>
<use f='llvm/llvm/lib/ObjectYAML/CodeViewYAMLSymbols.cpp' l='465' c='_ZN4llvm12CodeViewYAML6detail16SymbolRecordImpl3mapERNS_4yaml2IOE'/>
<use f='llvm/llvm/lib/ObjectYAML/CodeViewYAMLSymbols.cpp' l='477' c='_ZN4llvm12CodeViewYAML6detail16SymbolRecordImpl3mapERNS_4yaml2IOE'/>
<use f='llvm/llvm/lib/ObjectYAML/CodeViewYAMLSymbols.cpp' l='491' c='_ZN4llvm12CodeViewYAML6detail16SymbolRecordImpl3mapERNS_4yaml2IOE'/>
<use f='llvm/llvm/lib/ObjectYAML/CodeViewYAMLSymbols.cpp' l='503' c='_ZN4llvm12CodeViewYAML6detail16SymbolRecordImpl3mapERNS_4yaml2IOE'/>
<use f='llvm/llvm/lib/ObjectYAML/CodeViewYAMLSymbols.cpp' l='509' c='_ZN4llvm12CodeViewYAML6detail16SymbolRecordImpl3mapERNS_4yaml2IOE'/>
<use f='llvm/llvm/lib/ObjectYAML/CodeViewYAMLSymbols.cpp' l='516' c='_ZN4llvm12CodeViewYAML6detail16SymbolRecordImpl3mapERNS_4yaml2IOE'/>
<use f='llvm/llvm/lib/ObjectYAML/CodeViewYAMLSymbols.cpp' l='523' c='_ZN4llvm12CodeViewYAML6detail16SymbolRecordImpl3mapERNS_4yaml2IOE'/>
<use f='llvm/llvm/lib/ObjectYAML/CodeViewYAMLSymbols.cpp' l='529' c='_ZN4llvm12CodeViewYAML6detail16SymbolRecordImpl3mapERNS_4yaml2IOE'/>
<use f='llvm/llvm/lib/ObjectYAML/CodeViewYAMLSymbols.cpp' l='533' c='_ZN4llvm12CodeViewYAML6detail16SymbolRecordImpl3mapERNS_4yaml2IOE'/>
<use f='llvm/llvm/lib/ObjectYAML/CodeViewYAMLSymbols.cpp' l='538' c='_ZN4llvm12CodeViewYAML6detail16SymbolRecordImpl3mapERNS_4yaml2IOE'/>
<use f='llvm/llvm/lib/ObjectYAML/CodeViewYAMLSymbols.cpp' l='542' c='_ZN4llvm12CodeViewYAML6detail16SymbolRecordImpl3mapERNS_4yaml2IOE'/>
<use f='llvm/llvm/lib/ObjectYAML/CodeViewYAMLSymbols.cpp' l='548' c='_ZN4llvm12CodeViewYAML6detail16SymbolRecordImpl3mapERNS_4yaml2IOE'/>
<use f='llvm/llvm/lib/ObjectYAML/CodeViewYAMLSymbols.cpp' l='555' c='_ZN4llvm12CodeViewYAML6detail16SymbolRecordImpl3mapERNS_4yaml2IOE'/>
<use f='llvm/llvm/lib/ObjectYAML/CodeViewYAMLSymbols.cpp' l='561' c='_ZN4llvm12CodeViewYAML6detail16SymbolRecordImpl3mapERNS_4yaml2IOE'/>
<use f='llvm/llvm/lib/ObjectYAML/CodeViewYAMLSymbols.cpp' l='568' c='_ZN4llvm12CodeViewYAML6detail16SymbolRecordImpl3mapERNS_4yaml2IOE'/>
<use f='llvm/llvm/lib/ObjectYAML/CodeViewYAMLSymbols.cpp' l='575' c='_ZN4llvm12CodeViewYAML6detail16SymbolRecordImpl3mapERNS_4yaml2IOE'/>
<use f='llvm/llvm/lib/ObjectYAML/CodeViewYAMLSymbols.cpp' l='579' c='_ZN4llvm12CodeViewYAML6detail16SymbolRecordImpl3mapERNS_4yaml2IOE'/>
<use f='llvm/llvm/lib/ObjectYAML/CodeViewYAMLSymbols.cpp' l='598' c='_ZN4llvm4yaml13MappingTraitsINS_12CodeViewYAML6detail16SymbolRecordBaseEE7mappingERNS0_2IOERS4_'/>
<use f='llvm/llvm/lib/ObjectYAML/CodeViewYAMLSymbols.cpp' l='632' c='_ZL19mapSymbolRecordImplRN4llvm4yaml2IOEPKcNS_8codeview10SymbolKindERNS_12CodeViewYAML12SymbolRecordE'/>
<use f='llvm/llvm/lib/ObjectYAML/CodeViewYAMLSymbols.cpp' l='641' c='_ZN4llvm4yaml13MappingTraitsINS_12CodeViewYAML12SymbolRecordEE7mappingERNS0_2IOERS3_'/>
<size>16</size>
<use f='llvm/llvm/lib/ObjectYAML/CodeViewYAMLTypeHashing.cpp' l='29' c='_ZN4llvm4yaml13MappingTraitsINS_12CodeViewYAML13DebugHSectionEE7mappingERNS0_2IOERS3_'/>
<size>16</size>
<use f='llvm/llvm/lib/ObjectYAML/CodeViewYAMLTypes.cpp' l='53' macro='1' c='_ZN4llvm4yaml23ScalarEnumerationTraitsINS_8codeview12TypeLeafKindEvE11enumerationERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/CodeViewYAMLTypes.cpp' l='54' macro='1' c='_ZN4llvm4yaml23ScalarEnumerationTraitsINS_8codeview29PointerToMemberRepresentationEvE11enumerationERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/CodeViewYAMLTypes.cpp' l='55' macro='1' c='_ZN4llvm4yaml23ScalarEnumerationTraitsINS_8codeview15VFTableSlotKindEvE11enumerationERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/CodeViewYAMLTypes.cpp' l='56' macro='1' c='_ZN4llvm4yaml23ScalarEnumerationTraitsINS_8codeview17CallingConventionEvE11enumerationERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/CodeViewYAMLTypes.cpp' l='57' macro='1' c='_ZN4llvm4yaml23ScalarEnumerationTraitsINS_8codeview11PointerKindEvE11enumerationERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/CodeViewYAMLTypes.cpp' l='58' macro='1' c='_ZN4llvm4yaml23ScalarEnumerationTraitsINS_8codeview11PointerModeEvE11enumerationERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/CodeViewYAMLTypes.cpp' l='59' macro='1' c='_ZN4llvm4yaml23ScalarEnumerationTraitsINS_8codeview7HfaKindEvE11enumerationERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/CodeViewYAMLTypes.cpp' l='60' macro='1' c='_ZN4llvm4yaml23ScalarEnumerationTraitsINS_8codeview12MemberAccessEvE11enumerationERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/CodeViewYAMLTypes.cpp' l='61' macro='1' c='_ZN4llvm4yaml23ScalarEnumerationTraitsINS_8codeview10MethodKindEvE11enumerationERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/CodeViewYAMLTypes.cpp' l='62' macro='1' c='_ZN4llvm4yaml23ScalarEnumerationTraitsINS_8codeview18WindowsRTClassKindEvE11enumerationERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/CodeViewYAMLTypes.cpp' l='63' macro='1' c='_ZN4llvm4yaml23ScalarEnumerationTraitsINS_8codeview9LabelTypeEvE11enumerationERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/CodeViewYAMLTypes.cpp' l='65' macro='1' c='_ZN4llvm4yaml18ScalarBitSetTraitsINS_8codeview14PointerOptionsEvE6bitsetERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/CodeViewYAMLTypes.cpp' l='66' macro='1' c='_ZN4llvm4yaml18ScalarBitSetTraitsINS_8codeview15ModifierOptionsEvE6bitsetERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/CodeViewYAMLTypes.cpp' l='67' macro='1' c='_ZN4llvm4yaml18ScalarBitSetTraitsINS_8codeview15FunctionOptionsEvE6bitsetERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/CodeViewYAMLTypes.cpp' l='68' macro='1' c='_ZN4llvm4yaml18ScalarBitSetTraitsINS_8codeview12ClassOptionsEvE6bitsetERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/CodeViewYAMLTypes.cpp' l='69' macro='1' c='_ZN4llvm4yaml18ScalarBitSetTraitsINS_8codeview13MethodOptionsEvE6bitsetERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/CodeViewYAMLTypes.cpp' l='71' macro='1' c='_ZN4llvm4yaml13MappingTraitsINS_8codeview15OneMethodRecordEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/CodeViewYAMLTypes.cpp' l='72' macro='1' c='_ZN4llvm4yaml13MappingTraitsINS_8codeview17MemberPointerInfoEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/CodeViewYAMLTypes.cpp' l='84' c='_ZN4llvm12CodeViewYAML6detail14LeafRecordBase3mapERNS_4yaml2IOE'/>
<use f='llvm/llvm/lib/ObjectYAML/CodeViewYAMLTypes.cpp' l='93' c='_ZN4llvm12CodeViewYAML6detail14LeafRecordImpl3mapERNS_4yaml2IOE'/>
<use f='llvm/llvm/lib/ObjectYAML/CodeViewYAMLTypes.cpp' l='110' c='_ZN4llvm12CodeViewYAML6detail14LeafRecordImplINS_8codeview15FieldListRecordEE3mapERNS_4yaml2IOE'/>
<use f='llvm/llvm/lib/ObjectYAML/CodeViewYAMLTypes.cpp' l='123' c='_ZN4llvm12CodeViewYAML6detail16MemberRecordBase3mapERNS_4yaml2IOE'/>
<use f='llvm/llvm/lib/ObjectYAML/CodeViewYAMLTypes.cpp' l='131' c='_ZN4llvm12CodeViewYAML6detail16MemberRecordImpl3mapERNS_4yaml2IOE'/>
<use f='llvm/llvm/lib/ObjectYAML/CodeViewYAMLTypes.cpp' l='193' c='_ZN4llvm4yaml23ScalarEnumerationTraitsINS_8codeview12TypeLeafKindEvE11enumerationERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/CodeViewYAMLTypes.cpp' l='201' c='_ZN4llvm4yaml23ScalarEnumerationTraitsINS_8codeview29PointerToMemberRepresentationEvE11enumerationERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/CodeViewYAMLTypes.cpp' l='221' c='_ZN4llvm4yaml23ScalarEnumerationTraitsINS_8codeview15VFTableSlotKindEvE11enumerationERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/CodeViewYAMLTypes.cpp' l='232' c='_ZN4llvm4yaml23ScalarEnumerationTraitsINS_8codeview17CallingConventionEvE11enumerationERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/CodeViewYAMLTypes.cpp' l='259' c='_ZN4llvm4yaml23ScalarEnumerationTraitsINS_8codeview11PointerKindEvE11enumerationERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/CodeViewYAMLTypes.cpp' l='277' c='_ZN4llvm4yaml23ScalarEnumerationTraitsINS_8codeview11PointerModeEvE11enumerationERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/CodeViewYAMLTypes.cpp' l='287' c='_ZN4llvm4yaml23ScalarEnumerationTraitsINS_8codeview7HfaKindEvE11enumerationERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/CodeViewYAMLTypes.cpp' l='294' c='_ZN4llvm4yaml23ScalarEnumerationTraitsINS_8codeview12MemberAccessEvE11enumerationERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/CodeViewYAMLTypes.cpp' l='302' c='_ZN4llvm4yaml23ScalarEnumerationTraitsINS_8codeview10MethodKindEvE11enumerationERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/CodeViewYAMLTypes.cpp' l='315' c='_ZN4llvm4yaml23ScalarEnumerationTraitsINS_8codeview18WindowsRTClassKindEvE11enumerationERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/CodeViewYAMLTypes.cpp' l='322' c='_ZN4llvm4yaml23ScalarEnumerationTraitsINS_8codeview9LabelTypeEvE11enumerationERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/CodeViewYAMLTypes.cpp' l='327' c='_ZN4llvm4yaml18ScalarBitSetTraitsINS_8codeview14PointerOptionsEvE6bitsetERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/CodeViewYAMLTypes.cpp' l='339' c='_ZN4llvm4yaml18ScalarBitSetTraitsINS_8codeview15ModifierOptionsEvE6bitsetERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/CodeViewYAMLTypes.cpp' l='347' c='_ZN4llvm4yaml18ScalarBitSetTraitsINS_8codeview15FunctionOptionsEvE6bitsetERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/CodeViewYAMLTypes.cpp' l='356' c='_ZN4llvm4yaml18ScalarBitSetTraitsINS_8codeview12ClassOptionsEvE6bitsetERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/CodeViewYAMLTypes.cpp' l='376' c='_ZN4llvm4yaml18ScalarBitSetTraitsINS_8codeview13MethodOptionsEvE6bitsetERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/CodeViewYAMLTypes.cpp' l='385' c='_ZN4llvm4yaml13MappingTraitsINS_8codeview17MemberPointerInfoEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/CodeViewYAMLTypes.cpp' l='394' c='_ZN4llvm12CodeViewYAML6detail14LeafRecordImpl3mapERNS_4yaml2IOE'/>
<use f='llvm/llvm/lib/ObjectYAML/CodeViewYAMLTypes.cpp' l='399' c='_ZN4llvm12CodeViewYAML6detail14LeafRecordImpl3mapERNS_4yaml2IOE'/>
<use f='llvm/llvm/lib/ObjectYAML/CodeViewYAMLTypes.cpp' l='407' c='_ZN4llvm12CodeViewYAML6detail14LeafRecordImpl3mapERNS_4yaml2IOE'/>
<use f='llvm/llvm/lib/ObjectYAML/CodeViewYAMLTypes.cpp' l='418' c='_ZN4llvm12CodeViewYAML6detail14LeafRecordImpl3mapERNS_4yaml2IOE'/>
<use f='llvm/llvm/lib/ObjectYAML/CodeViewYAMLTypes.cpp' l='422' c='_ZN4llvm12CodeViewYAML6detail14LeafRecordImpl3mapERNS_4yaml2IOE'/>
<use f='llvm/llvm/lib/ObjectYAML/CodeViewYAMLTypes.cpp' l='428' c='_ZN4llvm12CodeViewYAML6detail14LeafRecordImpl3mapERNS_4yaml2IOE'/>
<use f='llvm/llvm/lib/ObjectYAML/CodeViewYAMLTypes.cpp' l='432' c='_ZN4llvm12CodeViewYAML6detail14LeafRecordImpl3mapERNS_4yaml2IOE'/>
<use f='llvm/llvm/lib/ObjectYAML/CodeViewYAMLTypes.cpp' l='436' c='_ZN4llvm12CodeViewYAML6detail14LeafRecordImpl3mapERNS_4yaml2IOE'/>
<use f='llvm/llvm/lib/ObjectYAML/CodeViewYAMLTypes.cpp' l='442' c='_ZN4llvm12CodeViewYAML6detail14LeafRecordImpl3mapERNS_4yaml2IOE'/>
<use f='llvm/llvm/lib/ObjectYAML/CodeViewYAMLTypes.cpp' l='449' c='_ZN4llvm12CodeViewYAML6detail14LeafRecordImplINS_8codeview15FieldListRecordEE3mapERNS_4yaml2IOE'/>
<use f='llvm/llvm/lib/ObjectYAML/CodeViewYAMLTypes.cpp' l='502' c='_ZN4llvm4yaml13MappingTraitsINS_8codeview15OneMethodRecordEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/CodeViewYAMLTypes.cpp' l='513' c='_ZN4llvm12CodeViewYAML6detail14LeafRecordImpl3mapERNS_4yaml2IOE'/>
<use f='llvm/llvm/lib/ObjectYAML/CodeViewYAMLTypes.cpp' l='524' c='_ZN4llvm12CodeViewYAML6detail14LeafRecordImpl3mapERNS_4yaml2IOE'/>
<use f='llvm/llvm/lib/ObjectYAML/CodeViewYAMLTypes.cpp' l='533' c='_ZN4llvm12CodeViewYAML6detail14LeafRecordImpl3mapERNS_4yaml2IOE'/>
<use f='llvm/llvm/lib/ObjectYAML/CodeViewYAMLTypes.cpp' l='542' c='_ZN4llvm12CodeViewYAML6detail14LeafRecordImpl3mapERNS_4yaml2IOE'/>
<use f='llvm/llvm/lib/ObjectYAML/CodeViewYAMLTypes.cpp' l='548' c='_ZN4llvm12CodeViewYAML6detail14LeafRecordImpl3mapERNS_4yaml2IOE'/>
<use f='llvm/llvm/lib/ObjectYAML/CodeViewYAMLTypes.cpp' l='552' c='_ZN4llvm12CodeViewYAML6detail14LeafRecordImpl3mapERNS_4yaml2IOE'/>
<use f='llvm/llvm/lib/ObjectYAML/CodeViewYAMLTypes.cpp' l='558' c='_ZN4llvm12CodeViewYAML6detail14LeafRecordImpl3mapERNS_4yaml2IOE'/>
<use f='llvm/llvm/lib/ObjectYAML/CodeViewYAMLTypes.cpp' l='563' c='_ZN4llvm12CodeViewYAML6detail14LeafRecordImpl3mapERNS_4yaml2IOE'/>
<use f='llvm/llvm/lib/ObjectYAML/CodeViewYAMLTypes.cpp' l='569' c='_ZN4llvm12CodeViewYAML6detail14LeafRecordImpl3mapERNS_4yaml2IOE'/>
<use f='llvm/llvm/lib/ObjectYAML/CodeViewYAMLTypes.cpp' l='575' c='_ZN4llvm12CodeViewYAML6detail14LeafRecordImpl3mapERNS_4yaml2IOE'/>
<use f='llvm/llvm/lib/ObjectYAML/CodeViewYAMLTypes.cpp' l='582' c='_ZN4llvm12CodeViewYAML6detail14LeafRecordImpl3mapERNS_4yaml2IOE'/>
<use f='llvm/llvm/lib/ObjectYAML/CodeViewYAMLTypes.cpp' l='586' c='_ZN4llvm12CodeViewYAML6detail14LeafRecordImpl3mapERNS_4yaml2IOE'/>
<use f='llvm/llvm/lib/ObjectYAML/CodeViewYAMLTypes.cpp' l='593' c='_ZN4llvm12CodeViewYAML6detail14LeafRecordImpl3mapERNS_4yaml2IOE'/>
<use f='llvm/llvm/lib/ObjectYAML/CodeViewYAMLTypes.cpp' l='597' c='_ZN4llvm12CodeViewYAML6detail14LeafRecordImpl3mapERNS_4yaml2IOE'/>
<use f='llvm/llvm/lib/ObjectYAML/CodeViewYAMLTypes.cpp' l='604' c='_ZN4llvm12CodeViewYAML6detail14LeafRecordImpl3mapERNS_4yaml2IOE'/>
<use f='llvm/llvm/lib/ObjectYAML/CodeViewYAMLTypes.cpp' l='608' c='_ZN4llvm12CodeViewYAML6detail16MemberRecordImpl3mapERNS_4yaml2IOE'/>
<use f='llvm/llvm/lib/ObjectYAML/CodeViewYAMLTypes.cpp' l='612' c='_ZN4llvm12CodeViewYAML6detail16MemberRecordImpl3mapERNS_4yaml2IOE'/>
<use f='llvm/llvm/lib/ObjectYAML/CodeViewYAMLTypes.cpp' l='618' c='_ZN4llvm12CodeViewYAML6detail16MemberRecordImpl3mapERNS_4yaml2IOE'/>
<use f='llvm/llvm/lib/ObjectYAML/CodeViewYAMLTypes.cpp' l='623' c='_ZN4llvm12CodeViewYAML6detail16MemberRecordImpl3mapERNS_4yaml2IOE'/>
<use f='llvm/llvm/lib/ObjectYAML/CodeViewYAMLTypes.cpp' l='630' c='_ZN4llvm12CodeViewYAML6detail16MemberRecordImpl3mapERNS_4yaml2IOE'/>
<use f='llvm/llvm/lib/ObjectYAML/CodeViewYAMLTypes.cpp' l='636' c='_ZN4llvm12CodeViewYAML6detail16MemberRecordImpl3mapERNS_4yaml2IOE'/>
<use f='llvm/llvm/lib/ObjectYAML/CodeViewYAMLTypes.cpp' l='642' c='_ZN4llvm12CodeViewYAML6detail16MemberRecordImpl3mapERNS_4yaml2IOE'/>
<use f='llvm/llvm/lib/ObjectYAML/CodeViewYAMLTypes.cpp' l='646' c='_ZN4llvm12CodeViewYAML6detail16MemberRecordImpl3mapERNS_4yaml2IOE'/>
<use f='llvm/llvm/lib/ObjectYAML/CodeViewYAMLTypes.cpp' l='652' c='_ZN4llvm12CodeViewYAML6detail16MemberRecordImpl3mapERNS_4yaml2IOE'/>
<use f='llvm/llvm/lib/ObjectYAML/CodeViewYAMLTypes.cpp' l='660' c='_ZN4llvm12CodeViewYAML6detail16MemberRecordImpl3mapERNS_4yaml2IOE'/>
<use f='llvm/llvm/lib/ObjectYAML/CodeViewYAMLTypes.cpp' l='704' c='_ZN4llvm4yaml13MappingTraitsINS_12CodeViewYAML6detail14LeafRecordBaseEE7mappingERNS0_2IOERS4_'/>
<use f='llvm/llvm/lib/ObjectYAML/CodeViewYAMLTypes.cpp' l='708' c='_ZN4llvm4yaml13MappingTraitsINS_12CodeViewYAML6detail16MemberRecordBaseEE7mappingERNS0_2IOERS4_'/>
<use f='llvm/llvm/lib/ObjectYAML/CodeViewYAMLTypes.cpp' l='715' c='_ZL17mapLeafRecordImplRN4llvm4yaml2IOEPKcNS_8codeview12TypeLeafKindERNS_12CodeViewYAML10LeafRecordE'/>
<use f='llvm/llvm/lib/ObjectYAML/CodeViewYAMLTypes.cpp' l='726' c='_ZN4llvm4yaml13MappingTraitsINS_12CodeViewYAML10LeafRecordEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/CodeViewYAMLTypes.cpp' l='747' c='_ZL19mapMemberRecordImplRN4llvm4yaml2IOEPKcNS_8codeview12TypeLeafKindERNS_12CodeViewYAML12MemberRecordE'/>
<use f='llvm/llvm/lib/ObjectYAML/CodeViewYAMLTypes.cpp' l='755' c='_ZN4llvm4yaml13MappingTraitsINS_12CodeViewYAML12MemberRecordEE7mappingERNS0_2IOERS3_'/>
<size>16</size>
<use f='llvm/llvm/lib/ObjectYAML/DWARFYAML.cpp' l='91' c='_ZN4llvm4yaml13MappingTraitsINS_9DWARFYAML4DataEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/DWARFYAML.cpp' l='114' c='_ZN4llvm4yaml13MappingTraitsINS_9DWARFYAML11AbbrevTableEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/DWARFYAML.cpp' l='119' c='_ZN4llvm4yaml13MappingTraitsINS_9DWARFYAML6AbbrevEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/DWARFYAML.cpp' l='128' c='_ZN4llvm4yaml13MappingTraitsINS_9DWARFYAML15AttributeAbbrevEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/DWARFYAML.cpp' l='136' c='_ZN4llvm4yaml13MappingTraitsINS_9DWARFYAML16ARangeDescriptorEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/DWARFYAML.cpp' l='141' c='_ZN4llvm4yaml13MappingTraitsINS_9DWARFYAML6ARangeEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/DWARFYAML.cpp' l='153' c='_ZN4llvm4yaml13MappingTraitsINS_9DWARFYAML10RangeEntryEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/DWARFYAML.cpp' l='158' c='_ZN4llvm4yaml13MappingTraitsINS_9DWARFYAML6RangesEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/DWARFYAML.cpp' l='165' c='_ZN4llvm4yaml13MappingTraitsINS_9DWARFYAML8PubEntryEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/DWARFYAML.cpp' l='174' c='_ZN4llvm4yaml13MappingTraitsINS_9DWARFYAML10PubSectionEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/DWARFYAML.cpp' l='183' c='_ZN4llvm4yaml13MappingTraitsINS_9DWARFYAML4UnitEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/DWARFYAML.cpp' l='195' c='_ZN4llvm4yaml13MappingTraitsINS_9DWARFYAML5EntryEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/DWARFYAML.cpp' l='201' c='_ZN4llvm4yaml13MappingTraitsINS_9DWARFYAML9FormValueEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/DWARFYAML.cpp' l='209' c='_ZN4llvm4yaml13MappingTraitsINS_9DWARFYAML4FileEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/DWARFYAML.cpp' l='217' c='_ZN4llvm4yaml13MappingTraitsINS_9DWARFYAML15LineTableOpcodeEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/DWARFYAML.cpp' l='236' c='_ZN4llvm4yaml13MappingTraitsINS_9DWARFYAML9LineTableEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/DWARFYAML.cpp' l='255' c='_ZN4llvm4yaml13MappingTraitsINS_9DWARFYAML11SegAddrPairEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/DWARFYAML.cpp' l='261' c='_ZN4llvm4yaml13MappingTraitsINS_9DWARFYAML14AddrTableEntryEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/DWARFYAML.cpp' l='271' c='_ZN4llvm4yaml13MappingTraitsINS_9DWARFYAML18StringOffsetsTableEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/DWARFYAML.cpp' l='280' c='_ZN4llvm4yaml13MappingTraitsINS_9DWARFYAML14DWARFOperationEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/DWARFYAML.cpp' l='286' c='_ZN4llvm4yaml13MappingTraitsINS_9DWARFYAML12RnglistEntryEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/DWARFYAML.cpp' l='292' c='_ZN4llvm4yaml13MappingTraitsINS_9DWARFYAML12LoclistEntryEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/DWARFYAML.cpp' l='301' c='_ZN4llvm4yaml13MappingTraitsINS_9DWARFYAML11ListEntriesIT_EEE7mappingERNS0_2IOERS5_'/>
<use f='llvm/llvm/lib/ObjectYAML/DWARFYAML.cpp' l='308' c='_ZN4llvm4yaml13MappingTraitsINS_9DWARFYAML11ListEntriesIT_EEE8validateB5cxx11ERNS0_2IOERS5_'/>
<use f='llvm/llvm/lib/ObjectYAML/DWARFYAML.cpp' l='316' c='_ZN4llvm4yaml13MappingTraitsINS_9DWARFYAML9ListTableIT_EEE7mappingERNS0_2IOERS5_'/>
<size>16</size>
<use f='llvm/llvm/lib/ObjectYAML/ELFYAML.cpp' l='43' c='_ZN4llvm4yaml23ScalarEnumerationTraitsINS_7ELFYAML6ELF_ETEvE11enumerationERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/ELFYAML.cpp' l='55' c='_ZN4llvm4yaml23ScalarEnumerationTraitsINS_7ELFYAML6ELF_PTEvE11enumerationERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/ELFYAML.cpp' l='74' c='_ZN4llvm4yaml23ScalarEnumerationTraitsINS_7ELFYAML6ELF_EMEvE11enumerationERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/ELFYAML.cpp' l='242' c='_ZN4llvm4yaml23ScalarEnumerationTraitsINS_7ELFYAML12ELF_ELFCLASSEvE11enumerationERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/ELFYAML.cpp' l='252' c='_ZN4llvm4yaml23ScalarEnumerationTraitsINS_7ELFYAML11ELF_ELFDATAEvE11enumerationERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/ELFYAML.cpp' l='263' c='_ZN4llvm4yaml23ScalarEnumerationTraitsINS_7ELFYAML12ELF_ELFOSABIEvE11enumerationERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/ELFYAML.cpp' l='294' c='_ZN4llvm4yaml18ScalarBitSetTraitsINS_7ELFYAML6ELF_EFEvE6bitsetERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/ELFYAML.cpp' l='463' c='_ZN4llvm4yaml23ScalarEnumerationTraitsINS_7ELFYAML7ELF_SHTEvE11enumerationERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/ELFYAML.cpp' l='534' c='_ZN4llvm4yaml18ScalarBitSetTraitsINS_7ELFYAML6ELF_PFEvE6bitsetERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/ELFYAML.cpp' l='542' c='_ZN4llvm4yaml18ScalarBitSetTraitsINS_7ELFYAML7ELF_SHFEvE6bitsetERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/ELFYAML.cpp' l='586' c='_ZN4llvm4yaml23ScalarEnumerationTraitsINS_7ELFYAML7ELF_SHNEvE11enumerationERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/ELFYAML.cpp' l='609' c='_ZN4llvm4yaml23ScalarEnumerationTraitsINS_7ELFYAML7ELF_STBEvE11enumerationERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/ELFYAML.cpp' l='620' c='_ZN4llvm4yaml23ScalarEnumerationTraitsINS_7ELFYAML7ELF_STTEvE11enumerationERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/ELFYAML.cpp' l='636' c='_ZN4llvm4yaml23ScalarEnumerationTraitsINS_7ELFYAML7ELF_RSSEvE11enumerationERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/ELFYAML.cpp' l='646' c='_ZN4llvm4yaml23ScalarEnumerationTraitsINS_7ELFYAML7ELF_RELEvE11enumerationERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/ELFYAML.cpp' l='703' c='_ZN4llvm4yaml23ScalarEnumerationTraitsINS_7ELFYAML10ELF_DYNTAGEvE11enumerationERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/ELFYAML.cpp' l='771' c='_ZN4llvm4yaml23ScalarEnumerationTraitsINS_7ELFYAML12MIPS_AFL_REGEvE11enumerationERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/ELFYAML.cpp' l='781' c='_ZN4llvm4yaml23ScalarEnumerationTraitsINS_7ELFYAML11MIPS_ABI_FPEvE11enumerationERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/ELFYAML.cpp' l='795' c='_ZN4llvm4yaml23ScalarEnumerationTraitsINS_7ELFYAML12MIPS_AFL_EXTEvE11enumerationERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/ELFYAML.cpp' l='821' c='_ZN4llvm4yaml23ScalarEnumerationTraitsINS_7ELFYAML8MIPS_ISAEvE11enumerationERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/ELFYAML.cpp' l='833' c='_ZN4llvm4yaml18ScalarBitSetTraitsINS_7ELFYAML12MIPS_AFL_ASEEvE6bitsetERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/ELFYAML.cpp' l='854' c='_ZN4llvm4yaml18ScalarBitSetTraitsINS_7ELFYAML15MIPS_AFL_FLAGS1EvE6bitsetERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/ELFYAML.cpp' l='861' c='_ZN4llvm4yaml13MappingTraitsINS_7ELFYAML13SectionHeaderEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/ELFYAML.cpp' l='865' c='_ZN4llvm4yaml13MappingTraitsINS_7ELFYAML10FileHeaderEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/ELFYAML.cpp' l='889' c='_ZN4llvm4yaml13MappingTraitsINS_7ELFYAML13ProgramHeaderEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/ELFYAML.cpp' l='903' c='_ZN4llvm4yaml13MappingTraitsINS_7ELFYAML13ProgramHeaderEE8validateB5cxx11ERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/ELFYAML.cpp' l='948' c='_ZN4llvm4yaml12_GLOBAL__N_115NormalizedOtherC1ERNS0_2IOE'/>
<use f='llvm/llvm/lib/ObjectYAML/ELFYAML.cpp' l='949' c='_ZN4llvm4yaml12_GLOBAL__N_115NormalizedOtherC1ERNS0_2IOENS_8OptionalIhEE'/>
<use f='llvm/llvm/lib/ObjectYAML/ELFYAML.cpp' l='989' c='_ZN4llvm4yaml12_GLOBAL__N_115NormalizedOther11denormalizeERNS0_2IOE'/>
<use f='llvm/llvm/lib/ObjectYAML/ELFYAML.cpp' l='1034'/>
<use f='llvm/llvm/lib/ObjectYAML/ELFYAML.cpp' l='1073' c='_ZN4llvm4yaml13MappingTraitsINS_7ELFYAML6SymbolEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/ELFYAML.cpp' l='1093' c='_ZN4llvm4yaml13MappingTraitsINS_7ELFYAML6SymbolEE8validateB5cxx11ERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/ELFYAML.cpp' l='1100' c='_ZN4llvm4yamlL20commonSectionMappingERNS0_2IOERNS_7ELFYAML7SectionE'/>
<use f='llvm/llvm/lib/ObjectYAML/ELFYAML.cpp' l='1127' c='_ZN4llvm4yamlL14sectionMappingERNS0_2IOERNS_7ELFYAML14DynamicSectionE'/>
<use f='llvm/llvm/lib/ObjectYAML/ELFYAML.cpp' l='1132' c='_ZN4llvm4yamlL14sectionMappingERNS0_2IOERNS_7ELFYAML17RawContentSectionE'/>
<use f='llvm/llvm/lib/ObjectYAML/ELFYAML.cpp' l='1148' c='_ZN4llvm4yamlL14sectionMappingERNS0_2IOERNS_7ELFYAML16BBAddrMapSectionE'/>
<use f='llvm/llvm/lib/ObjectYAML/ELFYAML.cpp' l='1154' c='_ZN4llvm4yamlL14sectionMappingERNS0_2IOERNS_7ELFYAML17StackSizesSectionE'/>
<use f='llvm/llvm/lib/ObjectYAML/ELFYAML.cpp' l='1159' c='_ZN4llvm4yamlL14sectionMappingERNS0_2IOERNS_7ELFYAML11HashSectionE'/>
<use f='llvm/llvm/lib/ObjectYAML/ELFYAML.cpp' l='1172' c='_ZN4llvm4yamlL14sectionMappingERNS0_2IOERNS_7ELFYAML11NoteSectionE'/>
<use f='llvm/llvm/lib/ObjectYAML/ELFYAML.cpp' l='1178' c='_ZN4llvm4yamlL14sectionMappingERNS0_2IOERNS_7ELFYAML14GnuHashSectionE'/>
<use f='llvm/llvm/lib/ObjectYAML/ELFYAML.cpp' l='1185' c='_ZN4llvm4yamlL14sectionMappingERNS0_2IOERNS_7ELFYAML13NoBitsSectionE'/>
<use f='llvm/llvm/lib/ObjectYAML/ELFYAML.cpp' l='1189' c='_ZN4llvm4yamlL14sectionMappingERNS0_2IOERNS_7ELFYAML13VerdefSectionE'/>
<use f='llvm/llvm/lib/ObjectYAML/ELFYAML.cpp' l='1195' c='_ZN4llvm4yamlL14sectionMappingERNS0_2IOERNS_7ELFYAML13SymverSectionE'/>
<use f='llvm/llvm/lib/ObjectYAML/ELFYAML.cpp' l='1200' c='_ZN4llvm4yamlL14sectionMappingERNS0_2IOERNS_7ELFYAML14VerneedSectionE'/>
<use f='llvm/llvm/lib/ObjectYAML/ELFYAML.cpp' l='1206' c='_ZN4llvm4yamlL14sectionMappingERNS0_2IOERNS_7ELFYAML17RelocationSectionE'/>
<use f='llvm/llvm/lib/ObjectYAML/ELFYAML.cpp' l='1212' c='_ZN4llvm4yamlL14sectionMappingERNS0_2IOERNS_7ELFYAML11RelrSectionE'/>
<use f='llvm/llvm/lib/ObjectYAML/ELFYAML.cpp' l='1217' c='_ZN4llvm4yamlL19groupSectionMappingERNS0_2IOERNS_7ELFYAML12GroupSectionE'/>
<use f='llvm/llvm/lib/ObjectYAML/ELFYAML.cpp' l='1223' c='_ZN4llvm4yamlL14sectionMappingERNS0_2IOERNS_7ELFYAML18SymtabShndxSectionE'/>
<use f='llvm/llvm/lib/ObjectYAML/ELFYAML.cpp' l='1228' c='_ZN4llvm4yamlL14sectionMappingERNS0_2IOERNS_7ELFYAML14AddrsigSectionE'/>
<use f='llvm/llvm/lib/ObjectYAML/ELFYAML.cpp' l='1233' c='_ZN4llvm4yamlL11fillMappingERNS0_2IOERNS_7ELFYAML4FillE'/>
<use f='llvm/llvm/lib/ObjectYAML/ELFYAML.cpp' l='1240' c='_ZN4llvm4yamlL25sectionHeaderTableMappingERNS0_2IOERNS_7ELFYAML18SectionHeaderTableE'/>
<use f='llvm/llvm/lib/ObjectYAML/ELFYAML.cpp' l='1248' c='_ZN4llvm4yamlL14sectionMappingERNS0_2IOERNS_7ELFYAML20LinkerOptionsSectionE'/>
<use f='llvm/llvm/lib/ObjectYAML/ELFYAML.cpp' l='1253' c='_ZN4llvm4yamlL14sectionMappingERNS0_2IOERNS_7ELFYAML25DependentLibrariesSectionE'/>
<use f='llvm/llvm/lib/ObjectYAML/ELFYAML.cpp' l='1259' c='_ZN4llvm4yamlL14sectionMappingERNS0_2IOERNS_7ELFYAML23CallGraphProfileSectionE'/>
<use f='llvm/llvm/lib/ObjectYAML/ELFYAML.cpp' l='1265' c='_ZN4llvm4yaml13MappingTraitsINS_7ELFYAML13SectionOrTypeEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/ELFYAML.cpp' l='1269' c='_ZN4llvm4yamlL14sectionMappingERNS0_2IOERNS_7ELFYAML20ARMIndexTableSectionE'/>
<use f='llvm/llvm/lib/ObjectYAML/ELFYAML.cpp' l='1274' c='_ZN4llvm4yamlL14sectionMappingERNS0_2IOERNS_7ELFYAML12MipsABIFlagsE'/>
<use f='llvm/llvm/lib/ObjectYAML/ELFYAML.cpp' l='1294' c='_ZN4llvm4yamlL14getStringValueERNS0_2IOEPKc'/>
<use f='llvm/llvm/lib/ObjectYAML/ELFYAML.cpp' l='1300' c='_ZN4llvm4yamlL14setStringValueERNS0_2IOEPKcNS_9StringRefE'/>
<use f='llvm/llvm/lib/ObjectYAML/ELFYAML.cpp' l='1310' c='_ZN4llvm4yaml13MappingTraitsISt10unique_ptrINS_7ELFYAML5ChunkESt14default_deleteIS4_EEE7mappingERNS0_2IOERS7_'/>
<use f='llvm/llvm/lib/ObjectYAML/ELFYAML.cpp' l='1467' c='_ZN4llvm4yaml13MappingTraitsISt10unique_ptrINS_7ELFYAML5ChunkESt14default_deleteIS4_EEE8validateB5cxx11ERNS0_2IOERS7_'/>
<use f='llvm/llvm/lib/ObjectYAML/ELFYAML.cpp' l='1542' c='_ZN4llvm4yaml12_GLOBAL__N_123NormalizedMips64RelTypeC1ERNS0_2IOE'/>
<use f='llvm/llvm/lib/ObjectYAML/ELFYAML.cpp' l='1547' c='_ZN4llvm4yaml12_GLOBAL__N_123NormalizedMips64RelTypeC1ERNS0_2IOENS_7ELFYAML7ELF_RELE'/>
<use f='llvm/llvm/lib/ObjectYAML/ELFYAML.cpp' l='1551' c='_ZN4llvm4yaml12_GLOBAL__N_123NormalizedMips64RelType11denormalizeERNS0_2IOE'/>
<use f='llvm/llvm/lib/ObjectYAML/ELFYAML.cpp' l='1565' c='_ZN4llvm4yaml13MappingTraitsINS_7ELFYAML14StackSizeEntryEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/ELFYAML.cpp' l='1572' c='_ZN4llvm4yaml13MappingTraitsINS_7ELFYAML14BBAddrMapEntryEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/ELFYAML.cpp' l='1579' c='_ZN4llvm4yaml13MappingTraitsINS_7ELFYAML14BBAddrMapEntry7BBEntryEE7mappingERNS0_2IOERS4_'/>
<use f='llvm/llvm/lib/ObjectYAML/ELFYAML.cpp' l='1586' c='_ZN4llvm4yaml13MappingTraitsINS_7ELFYAML13GnuHashHeaderEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/ELFYAML.cpp' l='1595' c='_ZN4llvm4yaml13MappingTraitsINS_7ELFYAML12DynamicEntryEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/ELFYAML.cpp' l='1603' c='_ZN4llvm4yaml13MappingTraitsINS_7ELFYAML9NoteEntryEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/ELFYAML.cpp' l='1611' c='_ZN4llvm4yaml13MappingTraitsINS_7ELFYAML11VerdefEntryEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/ELFYAML.cpp' l='1622' c='_ZN4llvm4yaml13MappingTraitsINS_7ELFYAML12VerneedEntryEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/ELFYAML.cpp' l='1631' c='_ZN4llvm4yaml13MappingTraitsINS_7ELFYAML12VernauxEntryEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/ELFYAML.cpp' l='1641' c='_ZN4llvm4yaml13MappingTraitsINS_7ELFYAML10RelocationEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/ELFYAML.cpp' l='1664' c='_ZN4llvm4yaml13MappingTraitsINS_7ELFYAML18ARMIndexTableEntryEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/ELFYAML.cpp' l='1677' c='_ZN4llvm4yaml13MappingTraitsINS_7ELFYAML6ObjectEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/ELFYAML.cpp' l='1696' c='_ZN4llvm4yaml13MappingTraitsINS_7ELFYAML12LinkerOptionEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/ELFYAML.cpp' l='1704' c='_ZN4llvm4yaml13MappingTraitsINS_7ELFYAML14CallGraphEntryEE7mappingERNS0_2IOERS3_'/>
<size>16</size>
<use f='llvm/llvm/lib/ObjectYAML/MachOYAML.cpp' l='84' c='_ZN4llvm4yaml13MappingTraitsINS_9MachOYAML10FileHeaderEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/MachOYAML.cpp' l='97' c='_ZN4llvm4yaml13MappingTraitsINS_9MachOYAML6ObjectEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/MachOYAML.cpp' l='124' c='_ZN4llvm4yaml13MappingTraitsINS_9MachOYAML9FatHeaderEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/MachOYAML.cpp' l='129' c='_ZN4llvm4yaml13MappingTraitsINS_9MachOYAML7FatArchEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/MachOYAML.cpp' l='141' c='_ZN4llvm4yaml13MappingTraitsINS_9MachOYAML15UniversalBinaryEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/MachOYAML.cpp' l='155' c='_ZN4llvm4yaml13MappingTraitsINS_9MachOYAML12LinkEditDataEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/MachOYAML.cpp' l='167' c='_ZN4llvm4yaml13MappingTraitsINS_9MachOYAML12RebaseOpcodeEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/MachOYAML.cpp' l='174' c='_ZN4llvm4yaml13MappingTraitsINS_9MachOYAML10BindOpcodeEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/MachOYAML.cpp' l='183' c='_ZN4llvm4yaml13MappingTraitsINS_9MachOYAML11ExportEntryEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/MachOYAML.cpp' l='195' c='_ZN4llvm4yaml13MappingTraitsINS_9MachOYAML10NListEntryEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/MachOYAML.cpp' l='204' c='_ZN4llvm4yaml18mapLoadCommandDataERNS0_2IOERNS_9MachOYAML11LoadCommandE'/>
<use f='llvm/llvm/lib/ObjectYAML/MachOYAML.cpp' l='208' c='_ZN4llvm4yaml18mapLoadCommandDataERNS0_2IOERNS_9MachOYAML11LoadCommandE'/>
<use f='llvm/llvm/lib/ObjectYAML/MachOYAML.cpp' l='214' c='_ZN4llvm4yaml18mapLoadCommandDataERNS0_2IOERNS_9MachOYAML11LoadCommandE'/>
<use f='llvm/llvm/lib/ObjectYAML/MachOYAML.cpp' l='220' c='_ZN4llvm4yaml18mapLoadCommandDataERNS0_2IOERNS_9MachOYAML11LoadCommandE'/>
<use f='llvm/llvm/lib/ObjectYAML/MachOYAML.cpp' l='226' c='_ZN4llvm4yaml18mapLoadCommandDataERNS0_2IOERNS_9MachOYAML11LoadCommandE'/>
<use f='llvm/llvm/lib/ObjectYAML/MachOYAML.cpp' l='232' c='_ZN4llvm4yaml18mapLoadCommandDataERNS0_2IOERNS_9MachOYAML11LoadCommandE'/>
<use f='llvm/llvm/lib/ObjectYAML/MachOYAML.cpp' l='238' c='_ZN4llvm4yaml18mapLoadCommandDataERNS0_2IOERNS_9MachOYAML11LoadCommandE'/>
<use f='llvm/llvm/lib/ObjectYAML/MachOYAML.cpp' l='243' c='_ZN4llvm4yaml13MappingTraitsINS_9MachOYAML11LoadCommandEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/MachOYAML.cpp' l='265' c='_ZN4llvm4yaml13MappingTraitsINS_5MachO17dyld_info_commandEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/MachOYAML.cpp' l='279' c='_ZN4llvm4yaml13MappingTraitsINS_9MachOYAML10RelocationEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/MachOYAML.cpp' l='290' c='_ZN4llvm4yaml13MappingTraitsINS_9MachOYAML7SectionEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/MachOYAML.cpp' l='309' c='_ZN4llvm4yaml13MappingTraitsINS_9MachOYAML7SectionEE8validateB5cxx11ERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/MachOYAML.cpp' l='317' c='_ZN4llvm4yaml13MappingTraitsINS_5MachO18build_tool_versionEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/MachOYAML.cpp' l='322' c='_ZN4llvm4yaml13MappingTraitsINS_5MachO5dylibEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/MachOYAML.cpp' l='330' c='_ZN4llvm4yaml13MappingTraitsINS_5MachO13dylib_commandEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/MachOYAML.cpp' l='335' c='_ZN4llvm4yaml13MappingTraitsINS_5MachO16dylinker_commandEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/MachOYAML.cpp' l='340' c='_ZN4llvm4yaml13MappingTraitsINS_5MachO16dysymtab_commandEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/MachOYAML.cpp' l='362' c='_ZN4llvm4yaml13MappingTraitsINS_5MachO23encryption_info_commandEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/MachOYAML.cpp' l='369' c='_ZN4llvm4yaml13MappingTraitsINS_5MachO26encryption_info_command_64EE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/MachOYAML.cpp' l='377' c='_ZN4llvm4yaml13MappingTraitsINS_5MachO19entry_point_commandEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/MachOYAML.cpp' l='383' c='_ZN4llvm4yaml13MappingTraitsINS_5MachO15fvmfile_commandEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/MachOYAML.cpp' l='388' c='_ZN4llvm4yaml13MappingTraitsINS_5MachO6fvmlibEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/MachOYAML.cpp' l='395' c='_ZN4llvm4yaml13MappingTraitsINS_5MachO14fvmlib_commandEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/MachOYAML.cpp' l='400' c='_ZN4llvm4yaml13MappingTraitsINS_5MachO13ident_commandEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/MachOYAML.cpp' l='403' c='_ZN4llvm4yaml13MappingTraitsINS_5MachO21linkedit_data_commandEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/MachOYAML.cpp' l='409' c='_ZN4llvm4yaml13MappingTraitsINS_5MachO21linker_option_commandEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/MachOYAML.cpp' l='414' c='_ZN4llvm4yaml13MappingTraitsINS_5MachO21prebind_cksum_commandEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/MachOYAML.cpp' l='419' c='_ZN4llvm4yaml13MappingTraitsINS_5MachO12load_commandEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/MachOYAML.cpp' l='422' c='_ZN4llvm4yaml13MappingTraitsINS_5MachO22prebound_dylib_commandEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/MachOYAML.cpp' l='429' c='_ZN4llvm4yaml13MappingTraitsINS_5MachO16routines_commandEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/MachOYAML.cpp' l='441' c='_ZN4llvm4yaml13MappingTraitsINS_5MachO19routines_command_64EE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/MachOYAML.cpp' l='453' c='_ZN4llvm4yaml13MappingTraitsINS_5MachO13rpath_commandEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/MachOYAML.cpp' l='457' c='_ZN4llvm4yaml13MappingTraitsINS_5MachO7sectionEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/MachOYAML.cpp' l='471' c='_ZN4llvm4yaml13MappingTraitsINS_5MachO10section_64EE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/MachOYAML.cpp' l='488' c='_ZN4llvm4yaml13MappingTraitsINS_5MachO15segment_commandEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/MachOYAML.cpp' l='501' c='_ZN4llvm4yaml13MappingTraitsINS_5MachO18segment_command_64EE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/MachOYAML.cpp' l='514' c='_ZN4llvm4yaml13MappingTraitsINS_5MachO22source_version_commandEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/MachOYAML.cpp' l='519' c='_ZN4llvm4yaml13MappingTraitsINS_5MachO18sub_client_commandEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/MachOYAML.cpp' l='524' c='_ZN4llvm4yaml13MappingTraitsINS_5MachO21sub_framework_commandEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/MachOYAML.cpp' l='529' c='_ZN4llvm4yaml13MappingTraitsINS_5MachO19sub_library_commandEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/MachOYAML.cpp' l='534' c='_ZN4llvm4yaml13MappingTraitsINS_5MachO20sub_umbrella_commandEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/MachOYAML.cpp' l='539' c='_ZN4llvm4yaml13MappingTraitsINS_5MachO14symseg_commandEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/MachOYAML.cpp' l='545' c='_ZN4llvm4yaml13MappingTraitsINS_5MachO14symtab_commandEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/MachOYAML.cpp' l='553' c='_ZN4llvm4yaml13MappingTraitsINS_5MachO14thread_commandEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/MachOYAML.cpp' l='556' c='_ZN4llvm4yaml13MappingTraitsINS_5MachO22twolevel_hints_commandEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/MachOYAML.cpp' l='562' c='_ZN4llvm4yaml13MappingTraitsINS_5MachO12uuid_commandEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/MachOYAML.cpp' l='567' c='_ZN4llvm4yaml13MappingTraitsINS_5MachO19version_min_commandEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/MachOYAML.cpp' l='573' c='_ZN4llvm4yaml13MappingTraitsINS_5MachO12note_commandEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/MachOYAML.cpp' l='580' c='_ZN4llvm4yaml13MappingTraitsINS_5MachO21build_version_commandEE7mappingERNS0_2IOERS3_'/>
<size>16</size>
<use f='llvm/llvm/lib/ObjectYAML/MinidumpYAML.cpp' l='20' c='_ZL11mapOptionalRN4llvm4yaml2IOEPKcRT_NS5_10value_typeE'/>
<use f='llvm/llvm/lib/ObjectYAML/MinidumpYAML.cpp' l='27' c='_ZL13mapRequiredAsRN4llvm4yaml2IOEPKcRT0_'/>
<use f='llvm/llvm/lib/ObjectYAML/MinidumpYAML.cpp' l='37' c='_ZL13mapOptionalAsRN4llvm4yaml2IOEPKcRT0_T_'/>
<use f='llvm/llvm/lib/ObjectYAML/MinidumpYAML.cpp' l='54' c='_ZL14mapRequiredHexRN4llvm4yaml2IOEPKcRT_'/>
<use f='llvm/llvm/lib/ObjectYAML/MinidumpYAML.cpp' l='62' c='_ZL14mapOptionalHexRN4llvm4yaml2IOEPKcRT_NS5_10value_typeE'/>
<use f='llvm/llvm/lib/ObjectYAML/MinidumpYAML.cpp' l='121' c='_ZN4llvm4yaml18ScalarBitSetTraitsINS_8minidump16MemoryProtectionEvE6bitsetERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/MinidumpYAML.cpp' l='127' c='_ZN4llvm4yaml18ScalarBitSetTraitsINS_8minidump11MemoryStateEvE6bitsetERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/MinidumpYAML.cpp' l='133' c='_ZN4llvm4yaml18ScalarBitSetTraitsINS_8minidump10MemoryTypeEvE6bitsetERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/MinidumpYAML.cpp' l='140' c='_ZN4llvm4yaml23ScalarEnumerationTraitsINS_8minidump21ProcessorArchitectureEvE11enumerationERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/MinidumpYAML.cpp' l='147' c='_ZN4llvm4yaml23ScalarEnumerationTraitsINS_8minidump10OSPlatformEvE11enumerationERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/MinidumpYAML.cpp' l='155' c='_ZN4llvm4yaml23ScalarEnumerationTraitsINS_8minidump10StreamTypeEvE11enumerationERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/MinidumpYAML.cpp' l='163' c='_ZN4llvm4yaml13MappingTraitsINS_8minidump7CPUInfo7ArmInfoEE7mappingERNS0_2IOERS4_'/>
<use f='llvm/llvm/lib/ObjectYAML/MinidumpYAML.cpp' l='200' c='_ZN4llvm4yaml13MappingTraitsINS_8minidump7CPUInfo9OtherInfoEE7mappingERNS0_2IOERS4_'/>
<use f='llvm/llvm/lib/ObjectYAML/MinidumpYAML.cpp' l='235' c='_ZN4llvm4yaml13MappingTraitsINS_8minidump7CPUInfo7X86InfoEE7mappingERNS0_2IOERS4_'/>
<use f='llvm/llvm/lib/ObjectYAML/MinidumpYAML.cpp' l='245' c='_ZN4llvm4yaml13MappingTraitsINS_8minidump10MemoryInfoEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/MinidumpYAML.cpp' l='259' c='_ZN4llvm4yaml13MappingTraitsINS_8minidump15VSFixedFileInfoEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/MinidumpYAML.cpp' l='277' c='_ZN4llvm4yaml13MappingTraitsINS_12MinidumpYAML6detail12ParsedModuleEE7mappingERNS0_2IOERS4_'/>
<use f='llvm/llvm/lib/ObjectYAML/MinidumpYAML.cpp' l='290' c='_ZL13streamMappingRN4llvm4yaml2IOERNS_12MinidumpYAML16RawContentStreamE'/>
<use f='llvm/llvm/lib/ObjectYAML/MinidumpYAML.cpp' l='302' c='_ZN4llvm4yaml13MappingTraitsINS_12MinidumpYAML6detail22ParsedMemoryDescriptorEE7mappingERNS0_2IOERS4_'/>
<use f='llvm/llvm/lib/ObjectYAML/MinidumpYAML.cpp' l='307' c='_ZL13streamMappingRN4llvm4yaml2IOERNS_12MinidumpYAML20MemoryInfoListStreamE'/>
<use f='llvm/llvm/lib/ObjectYAML/MinidumpYAML.cpp' l='311' c='_ZL13streamMappingRN4llvm4yaml2IOERNS_12MinidumpYAML6detail10ListStreamINS4_22ParsedMemoryDescriptorEEE'/>
<use f='llvm/llvm/lib/ObjectYAML/MinidumpYAML.cpp' l='315' c='_ZL13streamMappingRN4llvm4yaml2IOERNS_12MinidumpYAML6detail10ListStreamINS4_12ParsedModuleEEE'/>
<use f='llvm/llvm/lib/ObjectYAML/MinidumpYAML.cpp' l='319' c='_ZL13streamMappingRN4llvm4yaml2IOERNS_12MinidumpYAML16SystemInfoStreamE'/>
<use f='llvm/llvm/lib/ObjectYAML/MinidumpYAML.cpp' l='349' c='_ZL13streamMappingRN4llvm4yaml2IOERNS_12MinidumpYAML17TextContentStreamE'/>
<use f='llvm/llvm/lib/ObjectYAML/MinidumpYAML.cpp' l='354' c='_ZN4llvm4yaml20MappingContextTraitsINS_8minidump16MemoryDescriptorENS0_9BinaryRefEE7mappingERNS0_2IOERS3_RS4_'/>
<use f='llvm/llvm/lib/ObjectYAML/MinidumpYAML.cpp' l='360' c='_ZN4llvm4yaml13MappingTraitsINS_12MinidumpYAML6detail12ParsedThreadEE7mappingERNS0_2IOERS4_'/>
<use f='llvm/llvm/lib/ObjectYAML/MinidumpYAML.cpp' l='370' c='_ZL13streamMappingRN4llvm4yaml2IOERNS_12MinidumpYAML6detail10ListStreamINS4_12ParsedThreadEEE'/>
<use f='llvm/llvm/lib/ObjectYAML/MinidumpYAML.cpp' l='374' c='_ZL13streamMappingRN4llvm4yaml2IOERNS_12MinidumpYAML15ExceptionStreamE'/>
<use f='llvm/llvm/lib/ObjectYAML/MinidumpYAML.cpp' l='381' c='_ZN4llvm4yaml13MappingTraitsINS_8minidump9ExceptionEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/MinidumpYAML.cpp' l='401' c='_ZN4llvm4yaml13MappingTraitsISt10unique_ptrINS_12MinidumpYAML6StreamESt14default_deleteIS4_EEE7mappingERNS0_2IOERS7_'/>
<use f='llvm/llvm/lib/ObjectYAML/MinidumpYAML.cpp' l='438' c='_ZN4llvm4yaml13MappingTraitsISt10unique_ptrINS_12MinidumpYAML6StreamESt14default_deleteIS4_EEE8validateB5cxx11ERNS0_2IOERS7_'/>
<use f='llvm/llvm/lib/ObjectYAML/MinidumpYAML.cpp' l='454' c='_ZN4llvm4yaml13MappingTraitsINS_12MinidumpYAML6ObjectEE7mappingERNS0_2IOERS3_'/>
<size>16</size>
<use f='llvm/llvm/lib/ObjectYAML/ObjectYAML.cpp' l='22' c='_ZN4llvm4yaml13MappingTraitsINS0_14YamlObjectFileEE7mappingERNS0_2IOERS2_'/>
<size>16</size>
<use f='llvm/llvm/lib/ObjectYAML/WasmYAML.cpp' l='32' c='_ZN4llvm4yaml13MappingTraitsINS_8WasmYAML10FileHeaderEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/WasmYAML.cpp' l='36' c='_ZN4llvm4yaml13MappingTraitsINS_8WasmYAML6ObjectEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/WasmYAML.cpp' l='45' c='_ZN4llvm4yamlL20commonSectionMappingERNS0_2IOERNS_8WasmYAML7SectionE'/>
<use f='llvm/llvm/lib/ObjectYAML/WasmYAML.cpp' l='50' c='_ZN4llvm4yamlL14sectionMappingERNS0_2IOERNS_8WasmYAML13DylinkSectionE'/>
<use f='llvm/llvm/lib/ObjectYAML/WasmYAML.cpp' l='60' c='_ZN4llvm4yamlL14sectionMappingERNS0_2IOERNS_8WasmYAML11NameSectionE'/>
<use f='llvm/llvm/lib/ObjectYAML/WasmYAML.cpp' l='68' c='_ZN4llvm4yamlL14sectionMappingERNS0_2IOERNS_8WasmYAML14LinkingSectionE'/>
<use f='llvm/llvm/lib/ObjectYAML/WasmYAML.cpp' l='78' c='_ZN4llvm4yamlL14sectionMappingERNS0_2IOERNS_8WasmYAML16ProducersSectionE'/>
<use f='llvm/llvm/lib/ObjectYAML/WasmYAML.cpp' l='86' c='_ZN4llvm4yamlL14sectionMappingERNS0_2IOERNS_8WasmYAML21TargetFeaturesSectionE'/>
<use f='llvm/llvm/lib/ObjectYAML/WasmYAML.cpp' l='92' c='_ZN4llvm4yamlL14sectionMappingERNS0_2IOERNS_8WasmYAML13CustomSectionE'/>
<use f='llvm/llvm/lib/ObjectYAML/WasmYAML.cpp' l='98' c='_ZN4llvm4yamlL14sectionMappingERNS0_2IOERNS_8WasmYAML11TypeSectionE'/>
<use f='llvm/llvm/lib/ObjectYAML/WasmYAML.cpp' l='103' c='_ZN4llvm4yamlL14sectionMappingERNS0_2IOERNS_8WasmYAML13ImportSectionE'/>
<use f='llvm/llvm/lib/ObjectYAML/WasmYAML.cpp' l='108' c='_ZN4llvm4yamlL14sectionMappingERNS0_2IOERNS_8WasmYAML15FunctionSectionE'/>
<use f='llvm/llvm/lib/ObjectYAML/WasmYAML.cpp' l='113' c='_ZN4llvm4yamlL14sectionMappingERNS0_2IOERNS_8WasmYAML12TableSectionE'/>
<use f='llvm/llvm/lib/ObjectYAML/WasmYAML.cpp' l='118' c='_ZN4llvm4yamlL14sectionMappingERNS0_2IOERNS_8WasmYAML13MemorySectionE'/>
<use f='llvm/llvm/lib/ObjectYAML/WasmYAML.cpp' l='123' c='_ZN4llvm4yamlL14sectionMappingERNS0_2IOERNS_8WasmYAML12EventSectionE'/>
<use f='llvm/llvm/lib/ObjectYAML/WasmYAML.cpp' l='128' c='_ZN4llvm4yamlL14sectionMappingERNS0_2IOERNS_8WasmYAML13GlobalSectionE'/>
<use f='llvm/llvm/lib/ObjectYAML/WasmYAML.cpp' l='133' c='_ZN4llvm4yamlL14sectionMappingERNS0_2IOERNS_8WasmYAML13ExportSectionE'/>
<use f='llvm/llvm/lib/ObjectYAML/WasmYAML.cpp' l='138' c='_ZN4llvm4yamlL14sectionMappingERNS0_2IOERNS_8WasmYAML12StartSectionE'/>
<use f='llvm/llvm/lib/ObjectYAML/WasmYAML.cpp' l='143' c='_ZN4llvm4yamlL14sectionMappingERNS0_2IOERNS_8WasmYAML11ElemSectionE'/>
<use f='llvm/llvm/lib/ObjectYAML/WasmYAML.cpp' l='148' c='_ZN4llvm4yamlL14sectionMappingERNS0_2IOERNS_8WasmYAML11CodeSectionE'/>
<use f='llvm/llvm/lib/ObjectYAML/WasmYAML.cpp' l='153' c='_ZN4llvm4yamlL14sectionMappingERNS0_2IOERNS_8WasmYAML11DataSectionE'/>
<use f='llvm/llvm/lib/ObjectYAML/WasmYAML.cpp' l='158' c='_ZN4llvm4yamlL14sectionMappingERNS0_2IOERNS_8WasmYAML16DataCountSectionE'/>
<use f='llvm/llvm/lib/ObjectYAML/WasmYAML.cpp' l='164' c='_ZN4llvm4yaml13MappingTraitsISt10unique_ptrINS_8WasmYAML7SectionESt14default_deleteIS4_EEE7mappingERNS0_2IOERS7_'/>
<use f='llvm/llvm/lib/ObjectYAML/WasmYAML.cpp' l='278' c='_ZN4llvm4yaml23ScalarEnumerationTraitsINS_8WasmYAML11SectionTypeEvE11enumerationERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/WasmYAML.cpp' l='298' c='_ZN4llvm4yaml13MappingTraitsINS_8WasmYAML9SignatureEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/WasmYAML.cpp' l='304' c='_ZN4llvm4yaml13MappingTraitsINS_8WasmYAML5TableEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/WasmYAML.cpp' l='310' c='_ZN4llvm4yaml13MappingTraitsINS_8WasmYAML8FunctionEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/WasmYAML.cpp' l='318' c='_ZN4llvm4yaml13MappingTraitsINS_8WasmYAML10RelocationEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/WasmYAML.cpp' l='326' c='_ZN4llvm4yaml13MappingTraitsINS_8WasmYAML9NameEntryEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/WasmYAML.cpp' l='332' c='_ZN4llvm4yaml13MappingTraitsINS_8WasmYAML13ProducerEntryEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/WasmYAML.cpp' l='338' c='_ZN4llvm4yaml23ScalarEnumerationTraitsINS_8WasmYAML19FeaturePolicyPrefixEvE11enumerationERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/WasmYAML.cpp' l='347' c='_ZN4llvm4yaml13MappingTraitsINS_8WasmYAML12FeatureEntryEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/WasmYAML.cpp' l='353' c='_ZN4llvm4yaml13MappingTraitsINS_8WasmYAML11SegmentInfoEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/WasmYAML.cpp' l='361' c='_ZN4llvm4yaml13MappingTraitsINS_8WasmYAML9LocalDeclEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/WasmYAML.cpp' l='366' c='_ZN4llvm4yaml13MappingTraitsINS_8WasmYAML6LimitsEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/WasmYAML.cpp' l='376' c='_ZN4llvm4yaml13MappingTraitsINS_8WasmYAML11ElemSegmentEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/WasmYAML.cpp' l='381' c='_ZN4llvm4yaml13MappingTraitsINS_8WasmYAML6ImportEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/WasmYAML.cpp' l='403' c='_ZN4llvm4yaml13MappingTraitsINS_8WasmYAML6ExportEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/WasmYAML.cpp' l='410' c='_ZN4llvm4yaml13MappingTraitsINS_8WasmYAML6GlobalEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/WasmYAML.cpp' l='418' c='_ZN4llvm4yaml13MappingTraitsINS_4wasm12WasmInitExprEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/WasmYAML.cpp' l='448' c='_ZN4llvm4yaml13MappingTraitsINS_8WasmYAML11DataSegmentEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/WasmYAML.cpp' l='466' c='_ZN4llvm4yaml13MappingTraitsINS_8WasmYAML12InitFunctionEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/WasmYAML.cpp' l='472' c='_ZN4llvm4yaml23ScalarEnumerationTraitsINS_8WasmYAML10ComdatKindEvE11enumerationERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/WasmYAML.cpp' l='481' c='_ZN4llvm4yaml13MappingTraitsINS_8WasmYAML11ComdatEntryEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/WasmYAML.cpp' l='486' c='_ZN4llvm4yaml13MappingTraitsINS_8WasmYAML6ComdatEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/WasmYAML.cpp' l='492' c='_ZN4llvm4yaml13MappingTraitsINS_8WasmYAML10SymbolInfoEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/WasmYAML.cpp' l='520' c='_ZN4llvm4yaml13MappingTraitsINS_8WasmYAML5EventEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/WasmYAML.cpp' l='527' c='_ZN4llvm4yaml18ScalarBitSetTraitsINS_8WasmYAML10LimitFlagsEvE6bitsetERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/WasmYAML.cpp' l='536' c='_ZN4llvm4yaml18ScalarBitSetTraitsINS_8WasmYAML12SegmentFlagsEvE6bitsetERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/WasmYAML.cpp' l='539' c='_ZN4llvm4yaml18ScalarBitSetTraitsINS_8WasmYAML11SymbolFlagsEvE6bitsetERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/WasmYAML.cpp' l='555' c='_ZN4llvm4yaml23ScalarEnumerationTraitsINS_8WasmYAML10SymbolKindEvE11enumerationERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/WasmYAML.cpp' l='567' c='_ZN4llvm4yaml23ScalarEnumerationTraitsINS_8WasmYAML9ValueTypeEvE11enumerationERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/WasmYAML.cpp' l='581' c='_ZN4llvm4yaml23ScalarEnumerationTraitsINS_8WasmYAML10ExportKindEvE11enumerationERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/WasmYAML.cpp' l='592' c='_ZN4llvm4yaml23ScalarEnumerationTraitsINS_8WasmYAML6OpcodeEvE11enumerationERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/WasmYAML.cpp' l='605' c='_ZN4llvm4yaml23ScalarEnumerationTraitsINS_8WasmYAML9TableTypeEvE11enumerationERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/WasmYAML.cpp' l='613' c='_ZN4llvm4yaml23ScalarEnumerationTraitsINS_8WasmYAML9RelocTypeEvE11enumerationERNS0_2IOERS3_'/>
<size>16</size>
<use f='llvm/llvm/include/llvm/ObjectYAML/XCOFFYAML.h' l='53' c='_ZN4llvm4yaml23ScalarEnumerationTraitsINS_5XCOFF12StorageClassEvE11enumerationERNS0_2IOERS3_'/>
<use f='llvm/llvm/include/llvm/ObjectYAML/XCOFFYAML.h' l='57' c='_ZN4llvm4yaml13MappingTraitsINS_9XCOFFYAML10FileHeaderEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/include/llvm/ObjectYAML/XCOFFYAML.h' l='61' c='_ZN4llvm4yaml13MappingTraitsINS_9XCOFFYAML6ObjectEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/include/llvm/ObjectYAML/XCOFFYAML.h' l='65' c='_ZN4llvm4yaml13MappingTraitsINS_9XCOFFYAML6SymbolEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/XCOFFYAML.cpp' l='27' c='_ZN4llvm4yaml23ScalarEnumerationTraitsINS_5XCOFF12StorageClassEvE11enumerationERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/XCOFFYAML.cpp' l='83' c='_ZN4llvm4yaml13MappingTraitsINS_9XCOFFYAML10FileHeaderEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/XCOFFYAML.cpp' l='93' c='_ZN4llvm4yaml13MappingTraitsINS_9XCOFFYAML6SymbolEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/ObjectYAML/XCOFFYAML.cpp' l='102' c='_ZN4llvm4yaml13MappingTraitsINS_9XCOFFYAML6ObjectEE7mappingERNS0_2IOERS3_'/>
<size>16</size>
<use f='llvm/llvm/lib/Remarks/YAMLRemarkSerializer.cpp' l='23' c='_ZL15mapRemarkHeaderRN4llvm4yaml2IOET_S3_NS_8OptionalINS_7remarks14RemarkLocationEEES3_NS4_ImEENS_8ArrayRefINS5_8ArgumentEEE'/>
<use f='llvm/llvm/lib/Remarks/YAMLRemarkSerializer.cpp' l='39' c='_ZN4llvm4yaml13MappingTraitsIPNS_7remarks6RemarkEE7mappingERNS0_2IOERS4_'/>
<use f='llvm/llvm/lib/Remarks/YAMLRemarkSerializer.cpp' l='77' c='_ZN4llvm4yaml13MappingTraitsINS_7remarks14RemarkLocationEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/Remarks/YAMLRemarkSerializer.cpp' l='126' c='_ZN4llvm4yaml14SequenceTraitsINS_8ArrayRefIT_EEvE4sizeERNS0_2IOERS4_'/>
<use f='llvm/llvm/lib/Remarks/YAMLRemarkSerializer.cpp' l='127' c='_ZN4llvm4yaml14SequenceTraitsINS_8ArrayRefIT_EEvE7elementERNS0_2IOERS4_m'/>
<use f='llvm/llvm/lib/Remarks/YAMLRemarkSerializer.cpp' l='136' c='_ZN4llvm4yaml13MappingTraitsINS_7remarks8ArgumentEE7mappingERNS0_2IOERS3_'/>
<size>16</size>
<use f='llvm/llvm/lib/Support/AMDGPUMetadata.cpp' l='29' c='_ZN4llvm4yaml23ScalarEnumerationTraitsINS_6AMDGPU5HSAMD15AccessQualifierEvE11enumerationERNS0_2IOERS4_'/>
<use f='llvm/llvm/lib/Support/AMDGPUMetadata.cpp' l='39' c='_ZN4llvm4yaml23ScalarEnumerationTraitsINS_6AMDGPU5HSAMD21AddressSpaceQualifierEvE11enumerationERNS0_2IOERS4_'/>
<use f='llvm/llvm/lib/Support/AMDGPUMetadata.cpp' l='51' c='_ZN4llvm4yaml23ScalarEnumerationTraitsINS_6AMDGPU5HSAMD9ValueKindEvE11enumerationERNS0_2IOERS4_'/>
<use f='llvm/llvm/lib/Support/AMDGPUMetadata.cpp' l='75' c='_ZN4llvm4yaml23ScalarEnumerationTraitsINS_6AMDGPU5HSAMD9ValueTypeEvE11enumerationERNS0_2IOERS4_'/>
<use f='llvm/llvm/lib/Support/AMDGPUMetadata.cpp' l='93' c='_ZN4llvm4yaml13MappingTraitsINS_6AMDGPU5HSAMD6Kernel5Attrs8MetadataEE7mappingERNS0_2IOERS6_'/>
<use f='llvm/llvm/lib/Support/AMDGPUMetadata.cpp' l='107' c='_ZN4llvm4yaml13MappingTraitsINS_6AMDGPU5HSAMD6Kernel3Arg8MetadataEE7mappingERNS0_2IOERS6_'/>
<use f='llvm/llvm/lib/Support/AMDGPUMetadata.cpp' l='135' c='_ZN4llvm4yaml13MappingTraitsINS_6AMDGPU5HSAMD6Kernel9CodeProps8MetadataEE7mappingERNS0_2IOERS6_'/>
<use f='llvm/llvm/lib/Support/AMDGPUMetadata.cpp' l='165' c='_ZN4llvm4yaml13MappingTraitsINS_6AMDGPU5HSAMD6Kernel10DebugProps8MetadataEE7mappingERNS0_2IOERS6_'/>
<use f='llvm/llvm/lib/Support/AMDGPUMetadata.cpp' l='181' c='_ZN4llvm4yaml13MappingTraitsINS_6AMDGPU5HSAMD6Kernel8MetadataEE7mappingERNS0_2IOERS5_'/>
<use f='llvm/llvm/lib/Support/AMDGPUMetadata.cpp' l='200' c='_ZN4llvm4yaml13MappingTraitsINS_6AMDGPU5HSAMD8MetadataEE7mappingERNS0_2IOERS4_'/>
<size>16</size>
<use f='llvm/llvm/lib/Support/YAMLTraits.cpp' l='61' c='_ZN4llvm4yaml5InputC1ENS_9StringRefEPvPFvRKNS_12SMDiagnosticES3_ES3_'/>
<use f='llvm/llvm/lib/Support/YAMLTraits.cpp' l='69' c='_ZN4llvm4yaml5InputC1ENS_15MemoryBufferRefEPvPFvRKNS_12SMDiagnosticES3_ES3_'/>
<use f='llvm/llvm/lib/Support/YAMLTraits.cpp' l='469' c='_ZN4llvm4yaml6OutputC1ERNS_11raw_ostreamEPvi'/>
<size>16</size>
<fun r='_ZN4llvm4yaml2IOC1EPv'/>
<fun r='_ZN4llvm4yaml2IOD1Ev'/>
<fun r='_ZNK4llvm4yaml2IO10getContextEv'/>
<fun r='_ZN4llvm4yaml2IO10setContextEPv'/>
<fun r='_ZN4llvm4yaml2IO19setAllowUnknownKeysEb'/>
<use f='llvm/llvm/lib/Target/AArch64/AArch64MachineFunctionInfo.h' l='390' c='_ZN4llvm4yaml19AArch64FunctionInfo11mappingImplERNS0_2IOE'/>
<use f='llvm/llvm/lib/Target/AArch64/AArch64MachineFunctionInfo.h' l='395' c='_ZN4llvm4yaml13MappingTraitsINS0_19AArch64FunctionInfoEE7mappingERNS0_2IOERS2_'/>
<size>16</size>
<use f='llvm/llvm/lib/Target/AArch64/AArch64MachineFunctionInfo.cpp' l='27' c='_ZN4llvm4yaml19AArch64FunctionInfo11mappingImplERNS0_2IOE'/>
<size>16</size>
<use f='llvm/llvm/lib/Target/AMDGPU/SIMachineFunctionInfo.h' l='158' c='_ZN4llvm4yaml13MappingTraitsINS0_10SIArgumentEE7mappingERNS0_2IOERS2_'/>
<use f='llvm/llvm/lib/Target/AMDGPU/SIMachineFunctionInfo.h' l='203' c='_ZN4llvm4yaml13MappingTraitsINS0_14SIArgumentInfoEE7mappingERNS0_2IOERS2_'/>
<use f='llvm/llvm/lib/Target/AMDGPU/SIMachineFunctionInfo.h' l='259' c='_ZN4llvm4yaml13MappingTraitsINS0_6SIModeEE7mappingERNS0_2IOERS2_'/>
<use f='llvm/llvm/lib/Target/AMDGPU/SIMachineFunctionInfo.h' l='296' c='_ZN4llvm4yaml21SIMachineFunctionInfo11mappingImplERNS0_2IOE'/>
<use f='llvm/llvm/lib/Target/AMDGPU/SIMachineFunctionInfo.h' l='301' c='_ZN4llvm4yaml13MappingTraitsINS0_21SIMachineFunctionInfoEE7mappingERNS0_2IOERS2_'/>
<size>16</size>
<use f='llvm/llvm/lib/Target/AMDGPU/SIMachineFunctionInfo.cpp' l='548' c='_ZN4llvm4yaml21SIMachineFunctionInfo11mappingImplERNS0_2IOE'/>
<size>16</size>
<use f='llvm/llvm/lib/Target/WebAssembly/WebAssemblyMachineFunctionInfo.h' l='181' c='_ZN4llvm4yaml23WebAssemblyFunctionInfo11mappingImplERNS0_2IOE'/>
<use f='llvm/llvm/lib/Target/WebAssembly/WebAssemblyMachineFunctionInfo.h' l='186' c='_ZN4llvm4yaml13MappingTraitsINS0_23WebAssemblyFunctionInfoEE7mappingERNS0_2IOERS2_'/>
<size>16</size>
<use f='llvm/llvm/lib/Target/WebAssembly/WebAssemblyMachineFunctionInfo.cpp' l='109' c='_ZN4llvm4yaml23WebAssemblyFunctionInfo11mappingImplERNS0_2IOE'/>
<size>16</size>
<use f='llvm/llvm/lib/TextAPI/MachO/TextStubCommon.h' l='40' c='_ZN4llvm4yaml23ScalarEnumerationTraitsINS_5MachO18ObjCConstraintTypeEvE11enumerationERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/TextAPI/MachO/TextStubCommon.h' l='50' c='_ZN4llvm4yaml18ScalarBitSetTraitsINS_5MachO15ArchitectureSetEvE6bitsetERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/TextAPI/MachO/TextStub.cpp' l='287' c='_ZN4llvm4yaml13MappingTraitsIN12_GLOBAL__N_113ExportSectionEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/TextAPI/MachO/TextStub.cpp' l='309' c='_ZN4llvm4yaml13MappingTraitsIN12_GLOBAL__N_116UndefinedSectionEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/TextAPI/MachO/TextStub.cpp' l='325' c='_ZN4llvm4yaml13MappingTraitsIN12_GLOBAL__N_113SymbolSectionEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/TextAPI/MachO/TextStub.cpp' l='337' c='_ZN4llvm4yaml13MappingTraitsIN12_GLOBAL__N_115UmbrellaSectionEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/TextAPI/MachO/TextStub.cpp' l='344' c='_ZN4llvm4yaml13MappingTraitsIN12_GLOBAL__N_16UUIDv4EE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/TextAPI/MachO/TextStub.cpp' l='352' c='_ZN4llvm4yaml20MappingContextTraitsIN12_GLOBAL__N_115MetadataSectionENS3_6OptionEE7mappingERNS0_2IOERS3_RS4_'/>
<use f='llvm/llvm/lib/TextAPI/MachO/TextStub.cpp' l='368' c='_ZN4llvm4yaml18ScalarBitSetTraitsIN12_GLOBAL__N_18TBDFlagsEvE6bitsetERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/TextAPI/MachO/TextStub.cpp' l='437' c='_ZN4llvm4yaml13MappingTraitsIPKNS_5MachO13InterfaceFileEE13NormalizedTBDC1ERNS0_2IOE'/>
<use f='llvm/llvm/lib/TextAPI/MachO/TextStub.cpp' l='438' c='_ZN4llvm4yaml13MappingTraitsIPKNS_5MachO13InterfaceFileEE13NormalizedTBDC1ERNS0_2IOERS5_'/>
<use f='llvm/llvm/lib/TextAPI/MachO/TextStub.cpp' l='613' c='_ZN4llvm4yaml13MappingTraitsIPKNS_5MachO13InterfaceFileEE13NormalizedTBD11denormalizeERNS0_2IOE'/>
<use f='llvm/llvm/lib/TextAPI/MachO/TextStub.cpp' l='746' c='_ZN4llvm4yaml13MappingTraitsIPKNS_5MachO13InterfaceFileEE19setFileTypeForInputEPNS2_14TextAPIContextERNS0_2IOE'/>
<use f='llvm/llvm/lib/TextAPI/MachO/TextStub.cpp' l='762' c='_ZN4llvm4yaml13MappingTraitsIPKNS_5MachO13InterfaceFileEE7mappingERNS0_2IOERS5_'/>
<use f='llvm/llvm/lib/TextAPI/MachO/TextStub.cpp' l='804' c='_ZN4llvm4yaml13MappingTraitsIPKNS_5MachO13InterfaceFileEE16NormalizedTBD_V4C1ERNS0_2IOE'/>
<use f='llvm/llvm/lib/TextAPI/MachO/TextStub.cpp' l='805' c='_ZN4llvm4yaml13MappingTraitsIPKNS_5MachO13InterfaceFileEE16NormalizedTBD_V4C1ERNS0_2IOERS5_'/>
<use f='llvm/llvm/lib/TextAPI/MachO/TextStub.cpp' l='908' c='_ZN4llvm4yaml13MappingTraitsIPKNS_5MachO13InterfaceFileEE16NormalizedTBD_V411denormalizeERNS0_2IOE'/>
<use f='llvm/llvm/lib/TextAPI/MachO/TextStub.cpp' l='1022' c='_ZN4llvm4yaml13MappingTraitsIPKNS_5MachO13InterfaceFileEE15mapKeysToValuesENS2_8FileTypeERNS0_2IOERS5_'/>
<use f='llvm/llvm/lib/TextAPI/MachO/TextStub.cpp' l='1052' c='_ZN4llvm4yaml13MappingTraitsIPKNS_5MachO13InterfaceFileEE17mapKeysToValuesV4ERNS0_2IOERS5_'/>
<use f='llvm/llvm/lib/TextAPI/MachO/TextStub.cpp' l='1081' c='_ZN4llvm4yaml18DocumentListTraitsISt6vectorIPKNS_5MachO13InterfaceFileESaIS6_EEE4sizeERNS0_2IOERS8_'/>
<use f='llvm/llvm/lib/TextAPI/MachO/TextStub.cpp' l='1085' c='_ZN4llvm4yaml18DocumentListTraitsISt6vectorIPKNS_5MachO13InterfaceFileESaIS6_EEE7elementERNS0_2IOERS8_m'/>
<size>16</size>
<use f='llvm/llvm/lib/TextAPI/MachO/TextStubCommon.cpp' l='35' c='_ZN4llvm4yaml23ScalarEnumerationTraitsINS_5MachO18ObjCConstraintTypeEvE11enumerationERNS0_2IOERS3_'/>
<use f='llvm/llvm/lib/TextAPI/MachO/TextStubCommon.cpp' l='133' c='_ZN4llvm4yaml18ScalarBitSetTraitsINS_5MachO15ArchitectureSetEvE6bitsetERNS0_2IOERS3_'/>
<size>16</size>
<use f='llvm/llvm/include/llvm/IR/ModuleSummaryIndexYAML.h' l='19' c='_ZN4llvm4yaml23ScalarEnumerationTraitsINS_18TypeTestResolution4KindEvE11enumerationERNS0_2IOERS3_'/>
<use f='llvm/llvm/include/llvm/IR/ModuleSummaryIndexYAML.h' l='30' c='_ZN4llvm4yaml13MappingTraitsINS_18TypeTestResolutionEE7mappingERNS0_2IOERS2_'/>
<use f='llvm/llvm/include/llvm/IR/ModuleSummaryIndexYAML.h' l='42' c='_ZN4llvm4yaml23ScalarEnumerationTraitsINS_28WholeProgramDevirtResolution5ByArg4KindEvE11enumerationERNS0_2IOERS4_'/>
<use f='llvm/llvm/include/llvm/IR/ModuleSummaryIndexYAML.h' l='55' c='_ZN4llvm4yaml13MappingTraitsINS_28WholeProgramDevirtResolution5ByArgEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/include/llvm/IR/ModuleSummaryIndexYAML.h' l='67' c='_ZN4llvm4yaml19CustomMappingTraitsISt3mapISt6vectorImSaImEENS_28WholeProgramDevirtResolution5ByArgESt4lessIS5_ESaISt4pairIKS5_S7_EEEE8inputOneERNS0_2IOENS_9StringRefERSE_'/>
<use f='llvm/llvm/include/llvm/IR/ModuleSummaryIndexYAML.h' l='83' c='_ZN4llvm4yaml19CustomMappingTraitsISt3mapISt6vectorImSaImEENS_28WholeProgramDevirtResolution5ByArgESt4lessIS5_ESaISt4pairIKS5_S7_EEEE6outputERNS0_2IOERSE_'/>
<use f='llvm/llvm/include/llvm/IR/ModuleSummaryIndexYAML.h' l='98' c='_ZN4llvm4yaml23ScalarEnumerationTraitsINS_28WholeProgramDevirtResolution4KindEvE11enumerationERNS0_2IOERS3_'/>
<use f='llvm/llvm/include/llvm/IR/ModuleSummaryIndexYAML.h' l='107' c='_ZN4llvm4yaml13MappingTraitsINS_28WholeProgramDevirtResolutionEE7mappingERNS0_2IOERS2_'/>
<use f='llvm/llvm/include/llvm/IR/ModuleSummaryIndexYAML.h' l='116' c='_ZN4llvm4yaml19CustomMappingTraitsISt3mapImNS_28WholeProgramDevirtResolutionESt4lessImESaISt4pairIKmS3_EEEE8inputOneERNS0_2IOENS_9StringRefERSA_'/>
<use f='llvm/llvm/include/llvm/IR/ModuleSummaryIndexYAML.h' l='125' c='_ZN4llvm4yaml19CustomMappingTraitsISt3mapImNS_28WholeProgramDevirtResolutionESt4lessImESaISt4pairIKmS3_EEEE6outputERNS0_2IOERSA_'/>
<use f='llvm/llvm/include/llvm/IR/ModuleSummaryIndexYAML.h' l='132' c='_ZN4llvm4yaml13MappingTraitsINS_13TypeIdSummaryEE7mappingERNS0_2IOERS2_'/>
<use f='llvm/llvm/include/llvm/IR/ModuleSummaryIndexYAML.h' l='156' c='_ZN4llvm4yaml13MappingTraitsINS_15FunctionSummary7VFuncIdEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/include/llvm/IR/ModuleSummaryIndexYAML.h' l='163' c='_ZN4llvm4yaml13MappingTraitsINS_15FunctionSummary10ConstVCallEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/include/llvm/IR/ModuleSummaryIndexYAML.h' l='179' c='_ZN4llvm4yaml13MappingTraitsINS0_19FunctionSummaryYamlEE7mappingERNS0_2IOERS2_'/>
<use f='llvm/llvm/include/llvm/IR/ModuleSummaryIndexYAML.h' l='206' c='_ZN4llvm4yaml19CustomMappingTraitsISt3mapImNS_22GlobalValueSummaryInfoESt4lessImESaISt4pairIKmS3_EEEE8inputOneERNS0_2IOENS_9StringRefERSA_'/>
<use f='llvm/llvm/include/llvm/IR/ModuleSummaryIndexYAML.h' l='238' c='_ZN4llvm4yaml19CustomMappingTraitsISt3mapImNS_22GlobalValueSummaryInfoESt4lessImESaISt4pairIKmS3_EEEE6outputERNS0_2IOERSA_'/>
<use f='llvm/llvm/include/llvm/IR/ModuleSummaryIndexYAML.h' l='265' c='_ZN4llvm4yaml19CustomMappingTraitsISt8multimapImSt4pairINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEENS_13TypeIdSummaryEESt4lessImESaIS3_IKmSB_2564530'/>
<use f='llvm/llvm/include/llvm/IR/ModuleSummaryIndexYAML.h' l='270' c='_ZN4llvm4yaml19CustomMappingTraitsISt8multimapImSt4pairINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEENS_13TypeIdSummaryEESt4lessImESaIS3_IKmSB_578560'/>
<use f='llvm/llvm/include/llvm/IR/ModuleSummaryIndexYAML.h' l='277' c='_ZN4llvm4yaml13MappingTraitsINS_18ModuleSummaryIndexEE7mappingERNS0_2IOERS2_'/>
<size>16</size>
<use f='llvm/llvm/include/llvm/XRay/InstrumentationMap.h' l='107' c='_ZN4llvm4yaml23ScalarEnumerationTraitsINS_4xray9SledEntry13FunctionKindsEvE11enumerationERNS0_2IOERS4_'/>
<use f='llvm/llvm/include/llvm/XRay/InstrumentationMap.h' l='119' c='_ZN4llvm4yaml13MappingTraitsINS_4xray17YAMLXRaySledEntryEE7mappingERNS0_2IOERS3_'/>
<size>16</size>
<use f='llvm/llvm/include/llvm/XRay/YAMLXRayRecord.h' l='56' c='_ZN4llvm4yaml23ScalarEnumerationTraitsINS_4xray11RecordTypesEvE11enumerationERNS0_2IOERS3_'/>
<use f='llvm/llvm/include/llvm/XRay/YAMLXRayRecord.h' l='67' c='_ZN4llvm4yaml13MappingTraitsINS_4xray18YAMLXRayFileHeaderEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/include/llvm/XRay/YAMLXRayRecord.h' l='77' c='_ZN4llvm4yaml13MappingTraitsINS_4xray14YAMLXRayRecordEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/include/llvm/XRay/YAMLXRayRecord.h' l='94' c='_ZN4llvm4yaml13MappingTraitsINS_4xray13YAMLXRayTraceEE7mappingERNS0_2IOERS3_'/>
<size>16</size>
<use f='llvm/llvm/tools/dsymutil/DebugMap.h' l='236' c='_ZN4llvm4yaml13MappingTraitsISt4pairINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEENS_8dsymutil14DebugMapObject13SymbolMappingEEE7mappingERNS0_2IOERSC_'/>
<use f='llvm/llvm/tools/dsymutil/DebugMap.h' l='243' c='_ZN4llvm4yaml13MappingTraitsINS_8dsymutil14DebugMapObjectEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/tools/dsymutil/DebugMap.h' l='255' c='_ZN4llvm4yaml14SequenceTraitsISt6vectorISt10unique_ptrINS_8dsymutil14DebugMapObjectESt14default_deleteIS5_EESaIS8_EEvE4sizeERNS0_2IOERSA_'/>
<use f='llvm/llvm/tools/dsymutil/DebugMap.h' l='257' c='_ZN4llvm4yaml14SequenceTraitsISt6vectorISt10unique_ptrINS_8dsymutil14DebugMapObjectESt14default_deleteIS5_EESaIS8_EEvE7elementERNS0_2IOERSA_m'/>
<use f='llvm/llvm/tools/dsymutil/DebugMap.h' l='262' c='_ZN4llvm4yaml13MappingTraitsINS_8dsymutil8DebugMapEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/tools/dsymutil/DebugMap.h' l='266' c='_ZN4llvm4yaml13MappingTraitsISt10unique_ptrINS_8dsymutil8DebugMapESt14default_deleteIS4_EEE7mappingERNS0_2IOERS7_'/>
<use f='llvm/llvm/tools/dsymutil/DebugMap.cpp' l='154' c='_ZN4llvm4yaml13MappingTraitsINS_8dsymutil14DebugMapObjectEE7YamlDMOC1ERNS0_2IOE'/>
<use f='llvm/llvm/tools/dsymutil/DebugMap.cpp' l='155' c='_ZN4llvm4yaml13MappingTraitsINS_8dsymutil14DebugMapObjectEE7YamlDMOC1ERNS0_2IOERS3_'/>
<use f='llvm/llvm/tools/dsymutil/DebugMap.cpp' l='156' c='_ZN4llvm4yaml13MappingTraitsINS_8dsymutil14DebugMapObjectEE7YamlDMO11denormalizeERNS0_2IOE'/>
<use f='llvm/llvm/tools/dsymutil/DebugMap.cpp' l='164' c='_ZN4llvm4yaml13MappingTraitsISt4pairINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEENS_8dsymutil14DebugMapObject13SymbolMappingEEE7mappingERNS0_2IOERSC_'/>
<use f='llvm/llvm/tools/dsymutil/DebugMap.cpp' l='172' c='_ZN4llvm4yaml13MappingTraitsINS_8dsymutil14DebugMapObjectEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/tools/dsymutil/DebugMap.cpp' l='190' c='_ZN4llvm4yaml14SequenceTraitsISt6vectorISt10unique_ptrINS_8dsymutil14DebugMapObjectESt14default_deleteIS5_EESaIS8_EEvE4sizeERNS0_2IOERSA_'/>
<use f='llvm/llvm/tools/dsymutil/DebugMap.cpp' l='196' c='_ZN4llvm4yaml14SequenceTraitsISt6vectorISt10unique_ptrINS_8dsymutil14DebugMapObjectESt14default_deleteIS5_EESaIS8_EEvE7elementERNS0_2IOERSA_m'/>
<use f='llvm/llvm/tools/dsymutil/DebugMap.cpp' l='205' c='_ZN4llvm4yaml13MappingTraitsINS_8dsymutil8DebugMapEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/tools/dsymutil/DebugMap.cpp' l='215' c='_ZN4llvm4yaml13MappingTraitsISt10unique_ptrINS_8dsymutil8DebugMapESt14default_deleteIS4_EEE7mappingERNS0_2IOERS7_'/>
<use f='llvm/llvm/tools/dsymutil/DebugMap.cpp' l='226' c='_ZN4llvm4yaml13MappingTraitsINS_8dsymutil14DebugMapObjectEE7YamlDMOC1ERNS0_2IOERS3_'/>
<use f='llvm/llvm/tools/dsymutil/DebugMap.cpp' l='236' c='_ZN4llvm4yaml13MappingTraitsINS_8dsymutil14DebugMapObjectEE7YamlDMO11denormalizeERNS0_2IOE'/>
<size>16</size>
<use f='llvm/llvm/tools/llvm-exegesis/lib/BenchmarkResult.cpp' l='221' c='_ZN4llvm4yaml13MappingTraitsINS_8exegesis16BenchmarkMeasureEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/tools/llvm-exegesis/lib/BenchmarkResult.cpp' l='235' c='_ZN4llvm4yaml23ScalarEnumerationTraitsINS_8exegesis20InstructionBenchmark5ModeEEvE11enumerationERNS0_2IOERS4_'/>
<use f='llvm/llvm/tools/llvm-exegesis/lib/BenchmarkResult.cpp' l='286' c='_ZN4llvm4yaml20MappingContextTraitsINS_8exegesis23InstructionBenchmarkKeyENS_12_GLOBAL__N_111YamlContextEE7mappingERNS0_2IOERS3_RS5_'/>
<use f='llvm/llvm/tools/llvm-exegesis/lib/BenchmarkResult.cpp' l='298' c='_ZN4llvm4yaml20MappingContextTraitsINS_8exegesis20InstructionBenchmarkENS_12_GLOBAL__N_111YamlContextEE16NormalizedBinaryC1ERNS0_2IOE'/>
<use f='llvm/llvm/tools/llvm-exegesis/lib/BenchmarkResult.cpp' l='299' c='_ZN4llvm4yaml20MappingContextTraitsINS_8exegesis20InstructionBenchmarkENS_12_GLOBAL__N_111YamlContextEE16NormalizedBinaryC1ERNS0_2IOERSt6vectorIhSaIhEE'/>
<use f='llvm/llvm/tools/llvm-exegesis/lib/BenchmarkResult.cpp' l='300' c='_ZN4llvm4yaml20MappingContextTraitsINS_8exegesis20InstructionBenchmarkENS_12_GLOBAL__N_111YamlContextEE16NormalizedBinary11denormalizeERNS0_2IOE'/>
<use f='llvm/llvm/tools/llvm-exegesis/lib/BenchmarkResult.cpp' l='313' c='_ZN4llvm4yaml20MappingContextTraitsINS_8exegesis20InstructionBenchmarkENS_12_GLOBAL__N_111YamlContextEE7mappingERNS0_2IOERS3_RS5_'/>
<size>16</size>
<use f='llvm/llvm/tools/llvm-ifs/llvm-ifs.cpp' l='96' c='_ZN4llvm4yaml23ScalarEnumerationTraitsI13IFSSymbolTypevE11enumerationERNS0_2IOERS2_'/>
<use f='llvm/llvm/tools/llvm-ifs/llvm-ifs.cpp' l='109' c='_ZN4llvm4yaml13MappingTraitsI9IFSSymbolE7mappingERNS0_2IOERS2_'/>
<use f='llvm/llvm/tools/llvm-ifs/llvm-ifs.cpp' l='158' c='_ZN4llvm4yaml13MappingTraitsI7IFSStubE7mappingERNS0_2IOERS2_'/>
<size>16</size>
<use f='llvm/llvm/tools/llvm-pdbutil/PdbYaml.h' l='118' macro='1' c='_ZN4llvm4yaml13MappingTraitsINS_3pdb4yaml9PdbObjectEE7mappingERNS0_2IOERS4_'/>
<use f='llvm/llvm/tools/llvm-pdbutil/PdbYaml.h' l='119' macro='1' c='_ZN4llvm4yaml13MappingTraitsINS_3pdb4yaml10MSFHeadersEE7mappingERNS0_2IOERS4_'/>
<use f='llvm/llvm/tools/llvm-pdbutil/PdbYaml.h' l='120' macro='1' c='_ZN4llvm4yaml13MappingTraitsINS_3msf10SuperBlockEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/tools/llvm-pdbutil/PdbYaml.h' l='121' macro='1' c='_ZN4llvm4yaml13MappingTraitsINS_3pdb4yaml15StreamBlockListEE7mappingERNS0_2IOERS4_'/>
<use f='llvm/llvm/tools/llvm-pdbutil/PdbYaml.h' l='122' macro='1' c='_ZN4llvm4yaml13MappingTraitsINS_3pdb4yaml13PdbInfoStreamEE7mappingERNS0_2IOERS4_'/>
<use f='llvm/llvm/tools/llvm-pdbutil/PdbYaml.h' l='123' macro='1' c='_ZN4llvm4yaml13MappingTraitsINS_3pdb4yaml12PdbDbiStreamEE7mappingERNS0_2IOERS4_'/>
<use f='llvm/llvm/tools/llvm-pdbutil/PdbYaml.h' l='124' macro='1' c='_ZN4llvm4yaml13MappingTraitsINS_3pdb4yaml12PdbTpiStreamEE7mappingERNS0_2IOERS4_'/>
<use f='llvm/llvm/tools/llvm-pdbutil/PdbYaml.h' l='125' macro='1' c='_ZN4llvm4yaml13MappingTraitsINS_3pdb4yaml16PdbPublicsStreamEE7mappingERNS0_2IOERS4_'/>
<use f='llvm/llvm/tools/llvm-pdbutil/PdbYaml.h' l='126' macro='1' c='_ZN4llvm4yaml13MappingTraitsINS_3pdb4yaml18NamedStreamMappingEE7mappingERNS0_2IOERS4_'/>
<use f='llvm/llvm/tools/llvm-pdbutil/PdbYaml.h' l='127' macro='1' c='_ZN4llvm4yaml13MappingTraitsINS_3pdb4yaml13PdbModiStreamEE7mappingERNS0_2IOERS4_'/>
<use f='llvm/llvm/tools/llvm-pdbutil/PdbYaml.h' l='128' macro='1' c='_ZN4llvm4yaml13MappingTraitsINS_3pdb4yaml16PdbDbiModuleInfoEE7mappingERNS0_2IOERS4_'/>
<use f='llvm/llvm/tools/llvm-pdbutil/PdbYaml.cpp' l='34' c='_ZN4llvm4yaml23ScalarEnumerationTraitsINS_3pdb11PDB_MachineEvE11enumerationERNS0_2IOERS3_'/>
<use f='llvm/llvm/tools/llvm-pdbutil/PdbYaml.cpp' l='58' c='_ZN4llvm4yaml23ScalarEnumerationTraitsINS_3pdb13PdbRaw_DbiVerEvE11enumerationERNS0_2IOERS3_'/>
<use f='llvm/llvm/tools/llvm-pdbutil/PdbYaml.cpp' l='68' c='_ZN4llvm4yaml23ScalarEnumerationTraitsINS_3pdb14PdbRaw_ImplVerEvE11enumerationERNS0_2IOERS3_'/>
<use f='llvm/llvm/tools/llvm-pdbutil/PdbYaml.cpp' l='83' c='_ZN4llvm4yaml23ScalarEnumerationTraitsINS_3pdb13PdbRaw_TpiVerEvE11enumerationERNS0_2IOERS3_'/>
<use f='llvm/llvm/tools/llvm-pdbutil/PdbYaml.cpp' l='93' c='_ZN4llvm4yaml23ScalarEnumerationTraitsINS_3pdb17PdbRaw_FeatureSigEvE11enumerationERNS0_2IOERS3_'/>
<use f='llvm/llvm/tools/llvm-pdbutil/PdbYaml.cpp' l='104' c='_ZN4llvm4yaml13MappingTraitsINS_3pdb4yaml9PdbObjectEE7mappingERNS0_2IOERS4_'/>
<use f='llvm/llvm/tools/llvm-pdbutil/PdbYaml.cpp' l='116' c='_ZN4llvm4yaml13MappingTraitsINS_3pdb4yaml10MSFHeadersEE7mappingERNS0_2IOERS4_'/>
<use f='llvm/llvm/tools/llvm-pdbutil/PdbYaml.cpp' l='124' c='_ZN4llvm4yaml13MappingTraitsINS_3msf10SuperBlockEE7mappingERNS0_2IOERS3_'/>
<use f='llvm/llvm/tools/llvm-pdbutil/PdbYaml.cpp' l='138' c='_ZN4llvm4yaml13MappingTraitsINS_3pdb4yaml15StreamBlockListEE7mappingERNS0_2IOERS4_'/>
<use f='llvm/llvm/tools/llvm-pdbutil/PdbYaml.cpp' l='142' c='_ZN4llvm4yaml13MappingTraitsINS_3pdb4yaml13PdbInfoStreamEE7mappingERNS0_2IOERS4_'/>
<use f='llvm/llvm/tools/llvm-pdbutil/PdbYaml.cpp' l='150' c='_ZN4llvm4yaml13MappingTraitsINS_3pdb4yaml12PdbDbiStreamEE7mappingERNS0_2IOERS4_'/>
<use f='llvm/llvm/tools/llvm-pdbutil/PdbYaml.cpp' l='161' c='_ZN4llvm4yaml13MappingTraitsINS_3pdb4yaml12PdbTpiStreamEE7mappingERNS0_2IOERS4_'/>
<use f='llvm/llvm/tools/llvm-pdbutil/PdbYaml.cpp' l='168' c='_ZN4llvm4yaml13MappingTraitsINS_3pdb4yaml16PdbPublicsStreamEE7mappingERNS0_2IOERS4_'/>
<use f='llvm/llvm/tools/llvm-pdbutil/PdbYaml.cpp' l='172' c='_ZN4llvm4yaml13MappingTraitsINS_3pdb4yaml18NamedStreamMappingEE7mappingERNS0_2IOERS4_'/>
<use f='llvm/llvm/tools/llvm-pdbutil/PdbYaml.cpp' l='178' c='_ZN4llvm4yaml13MappingTraitsINS_3pdb4yaml13PdbModiStreamEE7mappingERNS0_2IOERS4_'/>
<use f='llvm/llvm/tools/llvm-pdbutil/PdbYaml.cpp' l='183' c='_ZN4llvm4yaml13MappingTraitsINS_3pdb4yaml16PdbDbiModuleInfoEE7mappingERNS0_2IOERS4_'/>
<size>16</size>
<use f='llvm/llvm/unittests/ObjectYAML/YAMLTest.cpp' l='23' c='_ZN4llvm4yaml13MappingTraitsI12BinaryHolderE7mappingERNS0_2IOERS2_'/>
<size>16</size>
<use f='llvm/llvm/unittests/Support/YAMLIOTest.cpp' l='62' c='_ZN4llvm4yaml13MappingTraitsI6FooBarE7mappingERNS0_2IOERS2_'/>
<use f='llvm/llvm/unittests/Support/YAMLIOTest.cpp' l='69' c='_ZN4llvm4yaml13MappingTraitsI15FooBarContainerE7mappingERNS0_2IOERS2_'/>
<use f='llvm/llvm/unittests/Support/YAMLIOTest.cpp' l='266' c='_ZN4llvm4yaml13MappingTraitsI15WithStringFieldE7mappingERNS0_2IOERS2_'/>
<use f='llvm/llvm/unittests/Support/YAMLIOTest.cpp' l='350' c='_ZN4llvm4yaml13MappingTraitsI12BuiltInTypesE7mappingERNS0_2IOERS2_'/>
<use f='llvm/llvm/unittests/Support/YAMLIOTest.cpp' l='502' c='_ZN4llvm4yaml13MappingTraitsI11EndianTypesE7mappingERNS0_2IOERS2_'/>
<use f='llvm/llvm/unittests/Support/YAMLIOTest.cpp' l='598' c='_ZN4llvm4yaml23ScalarEnumerationTraitsI4EnumvE11enumerationERNS0_2IOERS2_'/>
<use f='llvm/llvm/unittests/Support/YAMLIOTest.cpp' l='605' c='_ZN4llvm4yaml18ScalarBitSetTraitsI10BitsetEnumvE6bitsetERNS0_2IOERS2_'/>
<use f='llvm/llvm/unittests/Support/YAMLIOTest.cpp' l='612' c='_ZN4llvm4yaml13MappingTraitsI11EndianEnumsE7mappingERNS0_2IOERS2_'/>
<use f='llvm/llvm/unittests/Support/YAMLIOTest.cpp' l='697' c='_ZN4llvm4yaml13MappingTraitsI11StringTypesE7mappingERNS0_2IOERS2_'/>
<use f='llvm/llvm/unittests/Support/YAMLIOTest.cpp' l='828' c='_ZN4llvm4yaml23ScalarEnumerationTraitsI6ColorsvE11enumerationERNS0_2IOERS2_'/>
<use f='llvm/llvm/unittests/Support/YAMLIOTest.cpp' l='837' c='_ZN4llvm4yaml13MappingTraitsI8ColorMapE7mappingERNS0_2IOERS2_'/>
<use f='llvm/llvm/unittests/Support/YAMLIOTest.cpp' l='902' c='_ZN4llvm4yaml18ScalarBitSetTraitsI7MyFlagsvE6bitsetERNS0_2IOERS2_'/>
<use f='llvm/llvm/unittests/Support/YAMLIOTest.cpp' l='911' c='_ZN4llvm4yaml13MappingTraitsI8FlagsMapE7mappingERNS0_2IOERS2_'/>
<use f='llvm/llvm/unittests/Support/YAMLIOTest.cpp' l='994' c='_ZN4llvm4yaml13MappingTraitsI15MyCustomTypeMapE7mappingERNS0_2IOERS2_'/>
<use f='llvm/llvm/unittests/Support/YAMLIOTest.cpp' l='1087' c='_ZN4llvm4yaml13MappingTraitsI22MultilineStringTypeMapE7mappingERNS0_2IOERS2_'/>
<use f='llvm/llvm/unittests/Support/YAMLIOTest.cpp' l='1259' c='_ZN4llvm4yaml13MappingTraitsI14NameAndNumbersE7mappingERNS0_2IOERS2_'/>
<use f='llvm/llvm/unittests/Support/YAMLIOTest.cpp' l='1282' c='_ZN4llvm4yaml13MappingTraitsI18NameAndNumbersFlowE7mappingERNS0_2IOERS2_'/>
<use f='llvm/llvm/unittests/Support/YAMLIOTest.cpp' l='1399' c='_ZN4llvm4yaml13MappingTraitsI12TotalSecondsE17NormalizedSecondsC1ERNS0_2IOE'/>
<use f='llvm/llvm/unittests/Support/YAMLIOTest.cpp' l='1402' c='_ZN4llvm4yaml13MappingTraitsI12TotalSecondsE17NormalizedSecondsC1ERNS0_2IOERS2_'/>
<use f='llvm/llvm/unittests/Support/YAMLIOTest.cpp' l='1407' c='_ZN4llvm4yaml13MappingTraitsI12TotalSecondsE17NormalizedSeconds11denormalizeERNS0_2IOE'/>
<use f='llvm/llvm/unittests/Support/YAMLIOTest.cpp' l='1416' c='_ZN4llvm4yaml13MappingTraitsI12TotalSecondsE7mappingERNS0_2IOERS2_'/>
<use f='llvm/llvm/unittests/Support/YAMLIOTest.cpp' l='1508' c='_ZN4llvm4yaml23ScalarEnumerationTraitsI6AFlagsvE11enumerationERNS0_2IOERS2_'/>
<use f='llvm/llvm/unittests/Support/YAMLIOTest.cpp' l='1516' c='_ZN4llvm4yaml23ScalarEnumerationTraitsI6BFlagsvE11enumerationERNS0_2IOERS2_'/>
<use f='llvm/llvm/unittests/Support/YAMLIOTest.cpp' l='1524' c='_ZN4llvm4yaml23ScalarEnumerationTraitsI4KindvE11enumerationERNS0_2IOERS2_'/>
<use f='llvm/llvm/unittests/Support/YAMLIOTest.cpp' l='1531' c='_ZN4llvm4yaml13MappingTraitsI12KindAndFlagsE7mappingERNS0_2IOERS2_'/>
<use f='llvm/llvm/unittests/Support/YAMLIOTest.cpp' l='1621' c='_ZN4llvm4yaml13MappingTraitsI9FooBarMapE7mappingERNS0_2IOERS2_'/>
<use f='llvm/llvm/unittests/Support/YAMLIOTest.cpp' l='1700' c='_ZN4llvm4yaml13MappingTraitsI8MyDoubleE7mappingERNS0_2IOERS2_'/>
<use f='llvm/llvm/unittests/Support/YAMLIOTest.cpp' l='1707' c='_ZN4llvm4yaml13MappingTraitsI8MyDoubleE14mappingDecimalERNS0_2IOERS2_'/>
<use f='llvm/llvm/unittests/Support/YAMLIOTest.cpp' l='1710' c='_ZN4llvm4yaml13MappingTraitsI8MyDoubleE15mappingFractionERNS0_2IOERS2_'/>
<use f='llvm/llvm/unittests/Support/YAMLIOTest.cpp' l='1782' c='_ZN4llvm4yaml13MappingTraitsI12MyValidationE7mappingERNS0_2IOERS2_'/>
<use f='llvm/llvm/unittests/Support/YAMLIOTest.cpp' l='1785' c='_ZN4llvm4yaml13MappingTraitsI12MyValidationE8validateB5cxx11ERNS0_2IOERS2_'/>
<use f='llvm/llvm/unittests/Support/YAMLIOTest.cpp' l='1832' c='_ZN4llvm4yaml13MappingTraitsI10FlowFooBarE7mappingERNS0_2IOERS2_'/>
<use f='llvm/llvm/unittests/Support/YAMLIOTest.cpp' l='1842' c='_ZN4llvm4yaml13MappingTraitsI13FlowFooBarDocE7mappingERNS0_2IOERS2_'/>
<use f='llvm/llvm/unittests/Support/YAMLIOTest.cpp' l='2336' c='_ZN4llvm4yaml13MappingTraitsI12OptionalTestE7mappingERNS0_2IOERS2_'/>
<use f='llvm/llvm/unittests/Support/YAMLIOTest.cpp' l='2343' c='_ZN4llvm4yaml13MappingTraitsI15OptionalTestSeqE7mappingERNS0_2IOERS2_'/>
<use f='llvm/llvm/unittests/Support/YAMLIOTest.cpp' l='2426' c='_ZN4llvm4yaml13MappingTraitsI7FlowMapE7mappingERNS0_2IOERS2_'/>
<use f='llvm/llvm/unittests/Support/YAMLIOTest.cpp' l='2547' c='_ZN4llvm4yaml20MappingContextTraitsI9SimpleMap14MappingContextE7mappingERNS0_2IOERS2_RS3_'/>
<use f='llvm/llvm/unittests/Support/YAMLIOTest.cpp' l='2556' c='_ZN4llvm4yaml13MappingTraitsI9NestedMapE7mappingERNS0_2IOERS2_'/>
<use f='llvm/llvm/unittests/Support/YAMLIOTest.cpp' l='2677' c='_ZN4llvm4yaml13MappingTraitsI12FooBarMapMapE7mappingERNS0_2IOERS2_'/>
<use f='llvm/llvm/unittests/Support/YAMLIOTest.cpp' l='2965' c='_ZN4llvm4yaml19CustomMappingTraitsI3MapE8inputOneERNS0_2IOENS_9StringRefERS2_'/>
<use f='llvm/llvm/unittests/Support/YAMLIOTest.cpp' l='2969' c='_ZN4llvm4yaml19CustomMappingTraitsI3MapE6outputERNS0_2IOERS2_'/>
<use f='llvm/llvm/unittests/Support/YAMLIOTest.cpp' l='2976' c='_ZN4llvm4yaml14SequenceTraitsI3SeqvE4sizeERNS0_2IOERS2_'/>
<use f='llvm/llvm/unittests/Support/YAMLIOTest.cpp' l='2978' c='_ZN4llvm4yaml14SequenceTraitsI3SeqvE7elementERNS0_2IOERS2_m'/>
<size>16</size>
