<dec f='llvm/llvm/include/llvm/IR/DIBuilder.h' l='42' type='llvm::Module &amp;'/>
<offset>0</offset>
<use f='llvm/llvm/lib/IR/DIBuilder.cpp' l='35' u='w' c='_ZN4llvm9DIBuilderC1ERNS_6ModuleEbPNS_13DICompileUnitE'/>
<use f='llvm/llvm/lib/IR/DIBuilder.cpp' l='35' u='m' c='_ZN4llvm9DIBuilderC1ERNS_6ModuleEbPNS_13DICompileUnitE'/>
<use f='llvm/llvm/lib/IR/DIBuilder.cpp' l='158' u='m' c='_ZN4llvm9DIBuilder17createCompileUnitEjPNS_6DIFileENS_9StringRefEbS3_jS3_NS_13DICompileUnit17DebugEmissionKindEmbbNS4_18DebugNameTableKindEbS3_S3_'/>
<use f='llvm/llvm/lib/IR/DIBuilder.cpp' l='973' u='a' c='_ZN4llvm9DIBuilder13insertDeclareEPNS_5ValueEPNS_15DILocalVariableEPNS_12DIExpressionEPKNS_10DILocationEPNS_10BasicBlockEPNS_11InstructionE'/>
<use f='llvm/llvm/lib/IR/DIBuilder.cpp' l='996' u='a' c='_ZN4llvm9DIBuilder23insertDbgValueIntrinsicEPNS_5ValueEPNS_15DILocalVariableEPNS_12DIExpressionEPKNS_10DILocationEPNS_10BasicBlockEPNS_11InstructionE'/>
<use f='llvm/llvm/lib/IR/DIBuilder.cpp' l='1018' u='a' c='_ZN4llvm9DIBuilder11insertLabelEPNS_7DILabelEPKNS_10DILocationEPNS_10BasicBlockEPNS_11InstructionE'/>
