<dec f='llvm/llvm/include/llvm/Analysis/ModuleDebugInfoPrinter.h' l='21' type='llvm::raw_ostream &amp;'/>
<use f='llvm/llvm/lib/Analysis/ModuleDebugInfoPrinter.cpp' l='141' u='w' c='_ZN4llvm26ModuleDebugInfoPrinterPassC1ERNS_11raw_ostreamE'/>
<use f='llvm/llvm/lib/Analysis/ModuleDebugInfoPrinter.cpp' l='146' u='a' c='_ZN4llvm26ModuleDebugInfoPrinterPass3runERNS_6ModuleERNS_15AnalysisManagerIS1_JEEE'/>
<offset>5504</offset>
