<dec f='llvm/llvm/lib/IR/Verifier.cpp' l='130' type='const llvm::DataLayout &amp;'/>
<use f='llvm/llvm/lib/IR/Verifier.cpp' l='141' u='w' c='_ZN4llvm15VerifierSupportC1EPNS_11raw_ostreamERKNS_6ModuleE'/>
<use f='llvm/llvm/lib/IR/Verifier.cpp' l='665' u='m' c='_ZN12_GLOBAL__N_18Verifier19visitGlobalVariableERKN4llvm14GlobalVariableE'/>
<use f='llvm/llvm/lib/IR/Verifier.cpp' l='2091' u='m' c='_ZN12_GLOBAL__N_18Verifier17visitConstantExprEPKN4llvm12ConstantExprE'/>
<use f='llvm/llvm/lib/IR/Verifier.cpp' l='2359' u='m' c='_ZN12_GLOBAL__N_18Verifier13visitFunctionERKN4llvm8FunctionE'/>
<use f='llvm/llvm/lib/IR/Verifier.cpp' l='2915' u='m' c='_ZN12_GLOBAL__N_18Verifier17visitPtrToIntInstERN4llvm12PtrToIntInstE'/>
<use f='llvm/llvm/lib/IR/Verifier.cpp' l='2942' u='m' c='_ZN12_GLOBAL__N_18Verifier17visitIntToPtrInstERN4llvm12IntToPtrInstE'/>
<use f='llvm/llvm/lib/IR/Verifier.cpp' l='3601' u='m' c='_ZN12_GLOBAL__N_18Verifier24checkAtomicMemAccessSizeEPN4llvm4TypeEPKNS1_11InstructionE'/>
<use f='llvm/llvm/lib/IR/Verifier.cpp' l='3697' u='m' c='_ZN12_GLOBAL__N_18Verifier15visitAllocaInstERN4llvm10AllocaInstE'/>
<use f='llvm/llvm/lib/IR/Verifier.cpp' l='4393' u='m' c='_ZN12_GLOBAL__N_18Verifier16visitInstructionERN4llvm11InstructionE'/>
<offset>896</offset>
