<dec f='llvm/llvm/examples/Kaleidoscope/BuildingAJIT/Chapter4/KaleidoscopeJIT.h' l='84' type='llvm::orc::KaleidoscopeASTLayer &amp;'/>
<use f='llvm/llvm/examples/Kaleidoscope/BuildingAJIT/Chapter4/KaleidoscopeJIT.h' l='120' u='w' c='_ZN4llvm3orc34KaleidoscopeASTMaterializationUnitC1ERNS0_20KaleidoscopeASTLayerESt10unique_ptrI11FunctionASTSt14default_deleteIS5_EE'/>
<use f='llvm/llvm/examples/Kaleidoscope/BuildingAJIT/Chapter4/KaleidoscopeJIT.h' l='124' u='m' c='_ZN4llvm3orc34KaleidoscopeASTMaterializationUnit11materializeESt10unique_ptrINS0_29MaterializationResponsibilityESt14default_deleteIS3_EE'/>
<offset>320</offset>
