<dec f='llvm/llvm/include/llvm/Support/YAMLTraits.h' l='1523' type='std::error_code'/>
<offset>768</offset>
<use f='llvm/llvm/lib/Support/YAMLTraits.cpp' l='61' u='a' c='_ZN4llvm4yaml5InputC1ENS_9StringRefEPvPFvRKNS_12SMDiagnosticES3_ES3_'/>
<use f='llvm/llvm/lib/Support/YAMLTraits.cpp' l='69' u='a' c='_ZN4llvm4yaml5InputC1ENS_15MemoryBufferRefEPvPFvRKNS_12SMDiagnosticES3_ES3_'/>
<use f='llvm/llvm/lib/Support/YAMLTraits.cpp' l='77' u='r' c='_ZN4llvm4yaml5Input5errorEv'/>
<use f='llvm/llvm/lib/Support/YAMLTraits.cpp' l='94' u='w' c='_ZN4llvm4yaml5Input18setCurrentDocumentEv'/>
<use f='llvm/llvm/lib/Support/YAMLTraits.cpp' l='134' u='m' c='_ZN4llvm4yaml5Input12beginMappingEv'/>
<use f='llvm/llvm/lib/Support/YAMLTraits.cpp' l='158' u='m' c='_ZN4llvm4yaml5Input12preflightKeyEPKcbbRbRPv'/>
<use f='llvm/llvm/lib/Support/YAMLTraits.cpp' l='165' u='w' c='_ZN4llvm4yaml5Input12preflightKeyEPKcbbRbRPv'/>
<use f='llvm/llvm/lib/Support/YAMLTraits.cpp' l='196' u='m' c='_ZN4llvm4yaml5Input10endMappingEv'/>
<use f='llvm/llvm/lib/Support/YAMLTraits.cpp' l='237' u='m' c='_ZN4llvm4yaml5Input16preflightElementEjRPv'/>
<use f='llvm/llvm/lib/Support/YAMLTraits.cpp' l='254' u='m' c='_ZN4llvm4yaml5Input20preflightFlowElementEjRPv'/>
<use f='llvm/llvm/lib/Support/YAMLTraits.cpp' l='312' u='m' c='_ZN4llvm4yaml5Input11bitSetMatchEPKcb'/>
<use f='llvm/llvm/lib/Support/YAMLTraits.cpp' l='334' u='m' c='_ZN4llvm4yaml5Input15endBitSetScalarEv'/>
<use f='llvm/llvm/lib/Support/YAMLTraits.cpp' l='378' u='w' c='_ZN4llvm4yaml5Input8setErrorEPNS0_4NodeERKNS_5TwineE'/>
<use f='llvm/llvm/lib/Support/YAMLTraits.cpp' l='383' u='w' c='_ZN4llvm4yaml5Input8setErrorERKNS_7SMRangeERKNS_5TwineE'/>
<use f='llvm/llvm/lib/Support/YAMLTraits.cpp' l='415' u='m' c='_ZN4llvm4yaml5Input12createHNodesEPNS0_4NodeE'/>
<use f='llvm/llvm/lib/Support/YAMLTraits.cpp' l='440' u='m' c='_ZN4llvm4yaml5Input12createHNodesEPNS0_4NodeE'/>
