<dec f='llvm/llvm/include/llvm/CodeGen/MachineScheduler.h' l='121' type='const llvm::MachineLoopInfo *'/>
<use f='llvm/llvm/include/llvm/CodeGen/MachineScheduler.h' l='293' u='r' c='_ZN4llvm13ScheduleDAGMIC1EPNS_19MachineSchedContextESt10unique_ptrINS_20MachineSchedStrategyESt14default_deleteIS4_EEb'/>
<use f='llvm/llvm/lib/CodeGen/MachineScheduler.cpp' l='393' u='w' c='_ZN12_GLOBAL__N_116MachineScheduler20runOnMachineFunctionERN4llvm15MachineFunctionE'/>
<use f='llvm/llvm/lib/CodeGen/MachineScheduler.cpp' l='432' u='w' c='_ZN12_GLOBAL__N_120PostMachineScheduler20runOnMachineFunctionERN4llvm15MachineFunctionE'/>
<offset>128</offset>
<use f='llvm/llvm/lib/Target/SystemZ/SystemZMachineScheduler.cpp' l='131' u='r' c='_ZN4llvm26SystemZPostRASchedStrategyC1EPKNS_19MachineSchedContextE'/>
