<dec f='llvm/llvm/lib/Target/X86/X86ISelLowering.h' l='47' type='339'/>
<doc f='llvm/llvm/lib/Target/X86/X86ISelLowering.h' l='45'>/// Bitwise logical OR of floating point values. This corresponds
    /// to X86::ORPS or X86::ORPD.</doc>
<use f='llvm/build/lib/Target/X86/X86GenFastISel.inc' l='15300' c='_ZN12_GLOBAL__N_111X86FastISel11fastEmit_rrEN4llvm3MVTES2_jjbjb'/>
<use f='llvm/build/lib/Target/X86/X86GenDAGISel.inc' l='91033' u='r' c='_ZN12_GLOBAL__N_115X86DAGToDAGISel10SelectCodeEPN4llvm6SDNodeE'/>
<use f='llvm/build/lib/Target/X86/X86GenDAGISel.inc' l='91033' u='r' c='_ZN12_GLOBAL__N_115X86DAGToDAGISel10SelectCodeEPN4llvm6SDNodeE'/>
<use f='llvm/llvm/lib/Target/X86/X86ISelDAGToDAG.cpp' l='1115' c='_ZN12_GLOBAL__N_115X86DAGToDAGISel17PreprocessISelDAGEv'/>
<use f='llvm/llvm/lib/Target/X86/X86ISelDAGToDAG.cpp' l='1140' c='_ZN12_GLOBAL__N_115X86DAGToDAGISel17PreprocessISelDAGEv'/>
<use f='llvm/llvm/lib/Target/X86/X86ISelLowering.cpp' l='21847' u='r' c='_ZL15LowerFABSorFNEGN4llvm7SDValueERNS_12SelectionDAGE'/>
<use f='llvm/llvm/lib/Target/X86/X86ISelLowering.cpp' l='21924' u='r' c='_ZL14LowerFCOPYSIGNN4llvm7SDValueERNS_12SelectionDAGE'/>
<use f='llvm/llvm/lib/Target/X86/X86ISelLowering.cpp' l='22894' u='r' c='_ZL11LowerVSETCCN4llvm7SDValueERKNS_12X86SubtargetERNS_12SelectionDAGE'/>
<use f='llvm/llvm/lib/Target/X86/X86ISelLowering.cpp' l='23607' u='r' c='_ZNK4llvm17X86TargetLowering11LowerSELECTENS_7SDValueERNS_12SelectionDAGE'/>
<use f='llvm/llvm/lib/Target/X86/X86ISelLowering.cpp' l='30976' c='_ZNK4llvm17X86TargetLowering17getTargetNodeNameEj'/>
<use f='llvm/llvm/lib/Target/X86/X86ISelLowering.cpp' l='31449' c='_ZNK4llvm17X86TargetLowering18isCommutativeBinOpEj'/>
<use f='llvm/llvm/lib/Target/X86/X86ISelLowering.cpp' l='34390' c='_ZNK4llvm17X86TargetLowering29computeKnownBitsForTargetNodeENS_7SDValueERNS_9KnownBitsERKNS_5APIntERKNS_12SelectionDAGEj'/>
<use f='llvm/llvm/lib/Target/X86/X86ISelLowering.cpp' l='39147' u='r' c='_ZL15getAltBitOpcodej'/>
<use f='llvm/llvm/lib/Target/X86/X86ISelLowering.cpp' l='39808' u='r' c='_ZL14combineBitcastPN4llvm6SDNodeERNS_12SelectionDAGERNS_14TargetLowering15DAGCombinerInfoERKNS_12X86SubtargetE'/>
<use f='llvm/llvm/lib/Target/X86/X86ISelLowering.cpp' l='43756' u='r' c='_ZL30convertIntLogicToFPLogicOpcodej'/>
<use f='llvm/llvm/lib/Target/X86/X86ISelLowering.cpp' l='44433' u='r' c='_ZL9combineOrPN4llvm6SDNodeERNS_12SelectionDAGERNS_14TargetLowering15DAGCombinerInfoERKNS_12X86SubtargetE'/>
<use f='llvm/llvm/lib/Target/X86/X86ISelLowering.cpp' l='46635' c='_ZL17lowerX86FPLogicOpPN4llvm6SDNodeERNS_12SelectionDAGERKNS_12X86SubtargetE'/>
<use f='llvm/llvm/lib/Target/X86/X86ISelLowering.cpp' l='50342' c='_ZNK4llvm17X86TargetLowering17PerformDAGCombineEPNS_6SDNodeERNS_14TargetLowering15DAGCombinerInfoE'/>
