<dec f='llvm/build/lib/Target/PowerPC/PPCGenInstrInfo.inc' l='1743' type='1728'/>
<use f='llvm/build/lib/Target/PowerPC/PPCGenAsmMatcher.inc' l='7004'/>
<use f='llvm/build/lib/Target/PowerPC/PPCGenAsmMatcher.inc' l='7005'/>
<use f='llvm/build/lib/Target/PowerPC/PPCGenAsmMatcher.inc' l='7007'/>
<use f='llvm/build/lib/Target/PowerPC/PPCGenAsmMatcher.inc' l='7009'/>
<use f='llvm/build/lib/Target/PowerPC/PPCGenAsmMatcher.inc' l='7012'/>
<use f='llvm/build/lib/Target/PowerPC/PPCGenAsmMatcher.inc' l='7014'/>
<use f='llvm/build/lib/Target/PowerPC/PPCGenAsmMatcher.inc' l='7016'/>
<use f='llvm/build/lib/Target/PowerPC/PPCGenAsmMatcher.inc' l='7018'/>
<use f='llvm/build/lib/Target/PowerPC/PPCGenAsmMatcher.inc' l='7020'/>
<use f='llvm/build/lib/Target/PowerPC/PPCGenAsmMatcher.inc' l='7022'/>
<use f='llvm/build/lib/Target/PowerPC/PPCGenAsmMatcher.inc' l='7024'/>
<use f='llvm/build/lib/Target/PowerPC/PPCGenAsmMatcher.inc' l='7026'/>
<use f='llvm/build/lib/Target/PowerPC/PPCGenAsmMatcher.inc' l='7028'/>
<use f='llvm/build/lib/Target/PowerPC/PPCGenAsmMatcher.inc' l='7030'/>
<use f='llvm/build/lib/Target/PowerPC/PPCGenAsmMatcher.inc' l='7032'/>
<use f='llvm/build/lib/Target/PowerPC/PPCGenAsmMatcher.inc' l='7034'/>
<use f='llvm/build/lib/Target/PowerPC/PPCGenAsmWriter.inc' l='10308' u='r' c='_ZN4llvm14PPCInstPrinter15printAliasInstrEPKNS_6MCInstEmRKNS_15MCSubtargetInfoERNS_11raw_ostreamE'/>
<use f='llvm/build/lib/Target/PowerPC/PPCGenMCCodeEmitter.inc' l='4757' c='_ZNK4llvm16PPCMCCodeEmitter21getBinaryCodeForInstrERKNS_6MCInstERNS_15SmallVectorImplINS_7MCFixupEEERKNS_15MCSubtargetInfoE'/>
