<dec f='llvm/llvm/include/llvm/CodeGen/MachinePipeliner.h' l='64' type='const llvm::MachineLoopInfo *'/>
<use f='llvm/llvm/include/llvm/CodeGen/MachinePipeliner.h' l='196' u='r' c='_ZN4llvm17SwingSchedulerDAGC1ERNS_16MachinePipelinerERNS_11MachineLoopERNS_13LiveIntervalsERKNS_17RegisterClassInfoEj'/>
<use f='llvm/llvm/lib/CodeGen/MachinePipeliner.cpp' l='218' u='w' c='_ZN4llvm16MachinePipeliner20runOnMachineFunctionERNS_15MachineFunctionE'/>
<use f='llvm/llvm/lib/CodeGen/MachinePipeliner.cpp' l='224' u='r' c='_ZN4llvm16MachinePipeliner20runOnMachineFunctionERNS_15MachineFunctionE'/>
<offset>960</offset>
