<dec f='llvm/llvm/include/llvm/TableGen/Record.h' l='776' type='1'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='1069' c='_ZNK4llvm9BinOpInit4FoldEPNS_6RecordE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='1087' c='_ZNK4llvm9BinOpInit4FoldEPNS_6RecordE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='1119' c='_ZNK4llvm9BinOpInit11getAsStringB5cxx11Ev'/>
<use f='llvm/llvm/lib/TableGen/TGParser.cpp' l='1109' u='r' c='_ZN4llvm8TGParser14ParseOperationEPNS_6RecordEPNS_5RecTyE'/>
<use f='llvm/llvm/lib/TableGen/TGParser.cpp' l='1303' u='r' c='_ZN4llvm8TGParser14ParseOperationEPNS_6RecordEPNS_5RecTyE'/>
