<dec f='llvm/llvm/include/llvm/Demangle/ItaniumDemangle.h' l='417' type='llvm::itanium_demangle::StringView'/>
<use f='llvm/llvm/include/llvm/Demangle/ItaniumDemangle.h' l='422' u='w' c='_ZN4llvm16itanium_demangle10AbiTagAttrC1EPNS0_4NodeENS0_10StringViewE'/>
<use f='llvm/llvm/include/llvm/Demangle/ItaniumDemangle.h' l='424' c='_ZNK4llvm16itanium_demangle10AbiTagAttr5matchET_'/>
<use f='llvm/llvm/include/llvm/Demangle/ItaniumDemangle.h' l='429' u='r' c='_ZNK4llvm16itanium_demangle10AbiTagAttr9printLeftERNS0_12OutputStreamE'/>
<offset>192</offset>
