<dec f='llvm/llvm/include/llvm/DebugInfo/CodeView/CodeView.h' l='165' type='83'/>
<use f='llvm/lldb/source/Plugins/SymbolFile/NativePDB/SymbolFileNativePDB.cpp' l='80' c='_ZL17TranslateLanguageN4llvm8codeview14SourceLanguageE'/>
<use f='llvm/lldb/source/Plugins/SymbolFile/PDB/SymbolFilePDB.cpp' l='70' c='_ZN12_GLOBAL__N_117TranslateLanguageEN4llvm8codeview14SourceLanguageE'/>
<use f='llvm/llvm/lib/CodeGen/AsmPrinter/CodeViewDebug.cpp' l='742' u='r' c='_ZL17MapDWLangToCVLangj'/>
<use f='llvm/llvm/lib/DebugInfo/CodeView/EnumTables.cpp' l='107'/>
<use f='llvm/llvm/lib/DebugInfo/PDB/PDBExtras.cpp' l='233' c='_ZN4llvm3pdblsERNS_11raw_ostreamERKNS_8codeview14SourceLanguageE'/>
<use f='llvm/llvm/lib/DebugInfo/PDB/PDBSymbolCompiland.cpp' l='102' u='r' c='_ZNK4llvm3pdb18PDBSymbolCompiland21getSourceFileFullPathB5cxx11Ev'/>
<use f='llvm/llvm/tools/llvm-pdbutil/MinimalSymbolDumper.cpp' l='209' c='_ZL20formatSourceLanguageB5cxx11N4llvm8codeview14SourceLanguageE'/>
