<dec f='llvm/llvm/include/llvm/IR/CallingConv.h' l='73' type='16'/>
<doc f='llvm/llvm/include/llvm/IR/CallingConv.h' l='72'>// Swift - Calling convention for Swift.</doc>
<use f='llvm/clang/lib/CodeGen/CGCall.cpp' l='68' u='r' c='_ZN5clang7CodeGen12CodeGenTypes27ClangCallConvToLLVMCallConvENS_11CallingConvE'/>
<use f='llvm/llvm/lib/AsmParser/LLParser.cpp' l='2133' u='r' c='_ZN4llvm8LLParser24parseOptionalCallingConvERj'/>
<use f='llvm/llvm/lib/IR/AsmWriter.cpp' l='390' c='_ZL16PrintCallingConvjRN4llvm11raw_ostreamE'/>
<use f='llvm/llvm/lib/Target/AArch64/AArch64Subtarget.h' l='568' c='_ZNK4llvm16AArch64Subtarget18isCallingConvWin64Ej'/>
<use f='llvm/llvm/lib/Target/AArch64/AArch64FastISel.cpp' l='2958' u='r' c='_ZN12_GLOBAL__N_115AArch64FastISel18fastLowerArgumentsEv'/>
<use f='llvm/llvm/lib/Target/AArch64/AArch64ISelLowering.cpp' l='4518' c='_ZNK4llvm21AArch64TargetLowering17CCAssignFnForCallEjb'/>
<use f='llvm/llvm/lib/Target/AArch64/AArch64ISelLowering.cpp' l='4999' c='_ZL17mayTailCallThisCCj'/>
<use f='llvm/llvm/lib/Target/AArch64/GISel/AArch64CallLowering.cpp' l='533' c='_ZL17mayTailCallThisCCj'/>
<use f='llvm/llvm/lib/Target/ARM/ARMFastISel.cpp' l='1856' c='_ZN12_GLOBAL__N_111ARMFastISel17CCAssignFnForCallEjbb'/>
<use f='llvm/llvm/lib/Target/ARM/ARMFastISel.cpp' l='3022' c='_ZN12_GLOBAL__N_111ARMFastISel18fastLowerArgumentsEv'/>
<use f='llvm/llvm/lib/Target/ARM/ARMISelLowering.cpp' l='2000' c='_ZNK4llvm17ARMTargetLowering23getEffectiveCallingConvEjb'/>
<use f='llvm/llvm/lib/Target/WebAssembly/WebAssemblyFastISel.cpp' l='645' u='r' c='_ZN12_GLOBAL__N_119WebAssemblyFastISel18fastLowerArgumentsEv'/>
<use f='llvm/llvm/lib/Target/WebAssembly/WebAssemblyFastISel.cpp' l='766' u='r' c='_ZN12_GLOBAL__N_119WebAssemblyFastISel10selectCallEPKN4llvm11InstructionE'/>
<use f='llvm/llvm/lib/Target/WebAssembly/WebAssemblyFixFunctionBitcasts.cpp' l='248' u='r' c='_ZN12_GLOBAL__N_119FixFunctionBitcasts11runOnModuleERN4llvm6ModuleE'/>
<use f='llvm/llvm/lib/Target/WebAssembly/WebAssemblyISelLowering.cpp' l='801' u='r' c='_ZL20callingConvSupportedj'/>
<use f='llvm/llvm/lib/Target/WebAssembly/WebAssemblyISelLowering.cpp' l='927' u='r' c='_ZNK4llvm25WebAssemblyTargetLowering9LowerCallERNS_14TargetLowering16CallLoweringInfoERNS_15SmallVectorImplINS_7SDValueEEE'/>
<use f='llvm/llvm/lib/Target/WebAssembly/WebAssemblyISelLowering.cpp' l='1136' u='r' c='_ZNK4llvm25WebAssemblyTargetLowering20LowerFormalArgumentsENS_7SDValueEjbRKNS_15SmallVectorImplINS_3ISD8InputArgEEERKNS_5SDLocERNS_12SelectionDAGERNS2_IS1_EE'/>
<use f='llvm/llvm/lib/Target/WebAssembly/WebAssemblyMachineFunctionInfo.cpp' l='75' u='r' c='_ZN4llvm19computeSignatureVTsEPKNS_12FunctionTypeEPKNS_8FunctionERS4_RKNS_13TargetMachineERNS_15SmallVectorImplINS_3MVTEEESD_'/>
<use f='llvm/llvm/lib/Target/X86/X86Subtarget.h' l='887' c='_ZNK4llvm12X86Subtarget18isCallingConvWin64Ej'/>
<use f='llvm/build/lib/Target/X86/X86GenCallingConv.inc' l='1439' u='r' c='_ZL11CC_X86_64_CjN4llvm3MVTES0_NS_11CCValAssign7LocInfoENS_3ISD10ArgFlagsTyERNS_7CCStateE'/>
<use f='llvm/build/lib/Target/X86/X86GenCallingConv.inc' l='3251' u='r' c='_ZL12RetCC_X86_64jN4llvm3MVTES0_NS_11CCValAssign7LocInfoENS_3ISD10ArgFlagsTyERNS_7CCStateE'/>
<use f='llvm/llvm/lib/Target/X86/X86FastISel.cpp' l='1295' u='r' c='_ZN12_GLOBAL__N_111X86FastISel12X86SelectRetEPKN4llvm11InstructionE'/>
<use f='llvm/llvm/lib/Target/X86/X86FastISel.cpp' l='3241' c='_ZN12_GLOBAL__N_111X86FastISel13fastLowerCallERN4llvm8FastISel16CallLoweringInfoE'/>
<use f='llvm/llvm/lib/Target/X86/X86ISelLowering.cpp' l='3202' c='_ZL17mayTailCallThisCCj'/>
<use f='llvm/llvm/lib/Target/X86/X86ISelLowering.cpp' l='3746' u='r' c='_ZNK4llvm17X86TargetLowering20LowerFormalArgumentsENS_7SDValueEjbRKNS_15SmallVectorImplINS_3ISD8InputArgEEERKNS_5SDLocERNS_12SelectionDAGERNS2_IS1_EE'/>
<use f='llvm/llvm/lib/Transforms/Coroutines/CoroInternal.h' l='248' u='r' c='_ZNK4llvm4coro5Shape19getResumeFunctionCCEv'/>
