<dec f='llvm/llvm/include/llvm/Analysis/MemorySSA.h' l='946' type='llvm::raw_ostream &amp;'/>
<use f='llvm/llvm/include/llvm/Analysis/MemorySSA.h' l='949' u='w' c='_ZN4llvm20MemorySSAPrinterPassC1ERNS_11raw_ostreamE'/>
<offset>0</offset>
<use f='llvm/llvm/lib/Analysis/MemorySSA.cpp' l='2353' u='m' c='_ZN4llvm20MemorySSAPrinterPass3runERNS_8FunctionERNS_15AnalysisManagerIS1_JEEE'/>
<use f='llvm/llvm/lib/Analysis/MemorySSA.cpp' l='2354' u='a' c='_ZN4llvm20MemorySSAPrinterPass3runERNS_8FunctionERNS_15AnalysisManagerIS1_JEEE'/>
