<dec f='llvm/llvm/include/llvm/IR/LegacyPassManager.h' l='92' type='llvm::Module *'/>
<offset>128</offset>
<use f='llvm/llvm/lib/IR/LegacyPassManager.cpp' l='1327' u='w' c='_ZN4llvm6legacy19FunctionPassManagerC1EPNS_6ModuleE'/>
<use f='llvm/llvm/lib/IR/LegacyPassManager.cpp' l='1359' u='r' c='_ZN4llvm6legacy19FunctionPassManager16doInitializationEv'/>
<use f='llvm/llvm/lib/IR/LegacyPassManager.cpp' l='1365' u='r' c='_ZN4llvm6legacy19FunctionPassManager14doFinalizationEv'/>
