<dec f='llvm/llvm/include/llvm/Analysis/IRSimilarityIdentifier.h' l='780' type='llvm::raw_ostream &amp;'/>
<use f='llvm/llvm/include/llvm/Analysis/IRSimilarityIdentifier.h' l='783' u='w' c='_ZN4llvm31IRSimilarityAnalysisPrinterPassC1ERNS_11raw_ostreamE'/>
<use f='llvm/llvm/lib/Analysis/IRSimilarityIdentifier.cpp' l='922' u='m' c='_ZN4llvm31IRSimilarityAnalysisPrinterPass3runERNS_6ModuleERNS_15AnalysisManagerIS1_JEEE'/>
<use f='llvm/llvm/lib/Analysis/IRSimilarityIdentifier.cpp' l='925' u='m' c='_ZN4llvm31IRSimilarityAnalysisPrinterPass3runERNS_6ModuleERNS_15AnalysisManagerIS1_JEEE'/>
<use f='llvm/llvm/lib/Analysis/IRSimilarityIdentifier.cpp' l='928' u='m' c='_ZN4llvm31IRSimilarityAnalysisPrinterPass3runERNS_6ModuleERNS_15AnalysisManagerIS1_JEEE'/>
<use f='llvm/llvm/lib/Analysis/IRSimilarityIdentifier.cpp' l='930' u='m' c='_ZN4llvm31IRSimilarityAnalysisPrinterPass3runERNS_6ModuleERNS_15AnalysisManagerIS1_JEEE'/>
<offset>0</offset>
