<use f='llvm/llvm/include/llvm/ExecutionEngine/Orc/Speculation.h' l='110' u='m' c='_ZN4llvm3orc10Speculator13launchCompileEm'/>
<use f='llvm/llvm/include/llvm/ExecutionEngine/Orc/Speculation.h' l='117' u='m' c='_ZN4llvm3orc10Speculator13launchCompileEm'/>
<use f='llvm/llvm/include/llvm/ExecutionEngine/Orc/Speculation.h' l='124' u='w' c='_ZN4llvm3orc10SpeculatorC1ERNS0_13ImplSymbolMapERNS0_16ExecutionSessionE'/>
<use f='llvm/llvm/include/llvm/ExecutionEngine/Orc/Speculation.h' l='154' u='m' c='_ZN4llvm3orc10Speculator15registerSymbolsENS_8DenseMapINS0_15SymbolStringPtrENS_8DenseSetIS3_NS_12DenseMapInfoIS3_EEEES6_NS_6detail12DenseMapPairIS3_S8249400'/>
<use f='llvm/llvm/include/llvm/ExecutionEngine/Orc/Speculation.h' l='162' u='a' c='_ZN4llvm3orc10Speculator5getESEv'/>
<dec f='llvm/llvm/include/llvm/ExecutionEngine/Orc/Speculation.h' l='168' type='llvm::orc::ExecutionSession &amp;'/>
<offset>384</offset>
