<dec f='llvm/llvm/lib/Target/X86/X86ISelLowering.h' l='816' type='851'/>
<doc f='llvm/llvm/lib/Target/X86/X86ISelLowering.h' l='812'>/// This instruction implements a truncating store from FP stack
    /// slots. This corresponds to the X86::FST32m / X86::FST64m. It takes a
    /// chain operand, value to store, address, and glue. The memory VT
    /// specifies the type to store as.</doc>
<use f='llvm/build/lib/Target/X86/X86GenDAGISel.inc' l='54995' u='r' c='_ZN12_GLOBAL__N_115X86DAGToDAGISel10SelectCodeEPN4llvm6SDNodeE'/>
<use f='llvm/build/lib/Target/X86/X86GenDAGISel.inc' l='54995' u='r' c='_ZN12_GLOBAL__N_115X86DAGToDAGISel10SelectCodeEPN4llvm6SDNodeE'/>
<use f='llvm/llvm/lib/Target/X86/X86ISelDAGToDAG.cpp' l='1307' u='r' c='_ZN12_GLOBAL__N_115X86DAGToDAGISel17PreprocessISelDAGEv'/>
<use f='llvm/llvm/lib/Target/X86/X86ISelLowering.cpp' l='20005' u='r' c='_ZNK4llvm17X86TargetLowering9BuildFILDENS_3EVTES1_RKNS_5SDLocENS_7SDValueES5_NS_18MachinePointerInfoENS_5AlignERNS_12SelectionDAGE'/>
<use f='llvm/llvm/lib/Target/X86/X86ISelLowering.cpp' l='30982' c='_ZNK4llvm17X86TargetLowering17getTargetNodeNameEj'/>
