<dec f='llvm/llvm/lib/Target/ARM/Utils/ARMBaseInfo.h' l='33' type='2'/>
<use f='llvm/llvm/lib/Target/ARM/Utils/ARMBaseInfo.h' l='53' c='_ZN4llvm5ARMCCL20getOppositeConditionENS0_9CondCodesE'/>
<use f='llvm/llvm/lib/Target/ARM/Utils/ARMBaseInfo.h' l='54' u='r' c='_ZN4llvm5ARMCCL20getOppositeConditionENS0_9CondCodesE'/>
<use f='llvm/llvm/lib/Target/ARM/Utils/ARMBaseInfo.h' l='76' c='_ZN4llvm5ARMCCL19getSwappedConditionENS0_9CondCodesE'/>
<use f='llvm/llvm/lib/Target/ARM/Utils/ARMBaseInfo.h' l='79' u='r' c='_ZN4llvm5ARMCCL19getSwappedConditionENS0_9CondCodesE'/>
<use f='llvm/llvm/lib/Target/ARM/Utils/ARMBaseInfo.h' l='150' c='_ZN4llvmL19ARMCondCodeToStringENS_5ARMCC9CondCodesE'/>
<use f='llvm/llvm/lib/Target/ARM/Utils/ARMBaseInfo.h' l='171' u='r' c='_ZN4llvmL21ARMCondCodeFromStringENS_9StringRefE'/>
<use f='llvm/llvm/lib/Target/ARM/Utils/ARMBaseInfo.h' l='172' u='r' c='_ZN4llvmL21ARMCondCodeFromStringENS_9StringRefE'/>
<doc f='llvm/llvm/lib/Target/ARM/Utils/ARMBaseInfo.h' l='33'>// Carry set                  &gt;, ==, or unordered</doc>
<use f='llvm/llvm/lib/Target/ARM/ARMBaseInstrInfo.cpp' l='621' c='_ZNK4llvm16ARMBaseInstrInfo17SubsumesPredicateENS_8ArrayRefINS_14MachineOperandEEES3_'/>
<use f='llvm/llvm/lib/Target/ARM/ARMBaseInstrInfo.cpp' l='2830' c='_ZL20getCmpToAddConditionN4llvm5ARMCC9CondCodesE'/>
<use f='llvm/llvm/lib/Target/ARM/ARMBaseInstrInfo.cpp' l='2831' u='r' c='_ZL20getCmpToAddConditionN4llvm5ARMCC9CondCodesE'/>
<use f='llvm/llvm/lib/Target/ARM/ARMBaseInstrInfo.cpp' l='3212' c='_ZNK4llvm16ARMBaseInstrInfo20optimizeCompareInstrERNS_12MachineInstrENS_8RegisterES3_iiPKNS_19MachineRegisterInfoE'/>
<use f='llvm/llvm/lib/Target/ARM/ARMFastISel.cpp' l='1220' u='r' c='_ZL14getComparePredN4llvm7CmpInst9PredicateE'/>
<use f='llvm/llvm/lib/Target/ARM/ARMISelLowering.cpp' l='1944' u='r' c='_ZL12IntCCToARMCCN4llvm3ISD8CondCodeE'/>
<use f='llvm/llvm/lib/Target/ARM/ARMISelLowering.cpp' l='4699' u='r' c='_ZNK4llvm17ARMTargetLowering13getARMXALUOOpENS_7SDValueERNS_12SelectionDAGERS1_'/>
<use f='llvm/llvm/lib/Target/ARM/ARMISelLowering.cpp' l='4713' u='r' c='_ZNK4llvm17ARMTargetLowering13getARMXALUOOpENS_7SDValueERNS_12SelectionDAGERS1_'/>
<use f='llvm/llvm/lib/Target/ARM/ARMISelLowering.cpp' l='6508' u='r' c='_ZL11LowerVSETCCN4llvm7SDValueERNS_12SelectionDAGEPKNS_12ARMSubtargetE'/>
<use f='llvm/llvm/lib/Target/ARM/ARMISelLowering.cpp' l='13235' c='_ZL14isValidMVECondjb'/>
<use f='llvm/llvm/lib/Target/ARM/ARMInstructionSelector.cpp' l='446' u='r' c='_ZL15getComparePredsN4llvm7CmpInst9PredicateE'/>
<use f='llvm/llvm/lib/Target/ARM/AsmParser/ARMAsmParser.cpp' l='2377' u='r' c='_ZNK12_GLOBAL__N_110ARMOperand23isITCondCodeRestrictedUEv'/>
<use f='llvm/llvm/lib/Target/ARM/Disassembler/ARMDisassembler.cpp' l='6258' u='r' c='_ZL33DecodeRestrictedUPredicateOperandRN4llvm6MCInstEjmPKv'/>
<use f='llvm/llvm/lib/Target/ARM/MCTargetDesc/ARMInstPrinter.cpp' l='973' u='r' c='_ZN4llvm14ARMInstPrinter40printMandatoryRestrictedPredicateOperandEPKNS_6MCInstEjRKNS_15MCSubtargetInfoERNS_11raw_ostreamE'/>
<use f='llvm/llvm/lib/Target/ARM/MCTargetDesc/ARMMCCodeEmitter.cpp' l='1961' c='_ZNK12_GLOBAL__N_116ARMMCCodeEmitter28getRestrictedCondCodeOpValueERKN4llvm6MCInstEjRNS1_15SmallVectorImplINS1_7MCFixupEEERKNS1_15MCSubtargetInfoE'/>
