<dec f='llvm/llvm/include/llvm/DebugInfo/CodeView/CodeView.h' l='461' type='256'/>
<use f='llvm/llvm/lib/DebugInfo/CodeView/EnumTables.cpp' l='123'/>
<use f='llvm/llvm/tools/llvm-pdbutil/MinimalSymbolDumper.cpp' l='90' u='r' c='_ZL22formatCompileSym3FlagsB5cxx11jN4llvm8codeview16CompileSym3FlagsE'/>
<use f='llvm/llvm/tools/llvm-pdbutil/MinimalSymbolDumper.cpp' l='90' u='r' c='_ZL22formatCompileSym3FlagsB5cxx11jN4llvm8codeview16CompileSym3FlagsE'/>
