<dec f='llvm/llvm/include/llvm/Target/TargetLoweringObjectFile.h' l='66' type='const llvm::TargetMachine *'/>
<offset>6912</offset>
<use f='llvm/llvm/lib/CodeGen/TargetLoweringObjectFileImpl.cpp' l='342' u='r' c='_ZNK4llvm27TargetLoweringObjectFileELF18emitModuleMetadataERNS_10MCStreamerERNS_6ModuleE'/>
<use f='llvm/llvm/lib/Target/TargetLoweringObjectFile.cpp' l='54' u='w' c='_ZN4llvm24TargetLoweringObjectFile10InitializeERNS_9MCContextERKNS_13TargetMachineE'/>
<use f='llvm/llvm/lib/Target/TargetLoweringObjectFile.cpp' l='177' u='r' c='_ZNK4llvm24TargetLoweringObjectFile21emitCGProfileMetadataERNS_10MCStreamerERNS_6ModuleE'/>
