<dec f='llvm/llvm/lib/Target/AArch64/Utils/AArch64BaseInfo.h' l='238' type='2'/>
<use f='llvm/llvm/lib/Target/AArch64/Utils/AArch64BaseInfo.h' l='267' c='_ZN4llvm9AArch64CCL15getCondCodeNameENS0_8CondCodeE'/>
<use f='llvm/llvm/lib/Target/AArch64/Utils/AArch64BaseInfo.h' l='301' c='_ZN4llvm9AArch64CCL24getNZCVToSatisfyCondCodeENS0_8CondCodeE'/>
<doc f='llvm/llvm/lib/Target/AArch64/Utils/AArch64BaseInfo.h' l='238'>// Unsigned higher or same    &gt;, ==, or unordered</doc>
<use f='llvm/llvm/lib/Target/AArch64/AArch64FastISel.cpp' l='2284' u='r' c='_ZL12getCompareCCN4llvm7CmpInst9PredicateE'/>
<use f='llvm/llvm/lib/Target/AArch64/AArch64FastISel.cpp' l='3441' u='r' c='_ZN12_GLOBAL__N_115AArch64FastISel17foldXALUIntrinsicERN4llvm9AArch64CC8CondCodeEPKNS1_11InstructionEPKNS1_5ValueE'/>
<use f='llvm/llvm/lib/Target/AArch64/AArch64FastISel.cpp' l='3733' u='r' c='_ZN12_GLOBAL__N_115AArch64FastISel22fastLowerIntrinsicCallEPKN4llvm13IntrinsicInstE'/>
<use f='llvm/llvm/lib/Target/AArch64/AArch64ISelLowering.cpp' l='2119' u='r' c='_ZL22changeIntCCToAArch64CCN4llvm3ISD8CondCodeE'/>
<use f='llvm/llvm/lib/Target/AArch64/AArch64ISelLowering.cpp' l='2811' u='r' c='_ZL17getAArch64XALUOOpRN4llvm9AArch64CC8CondCodeENS_7SDValueERNS_12SelectionDAGE'/>
<use f='llvm/llvm/lib/Target/AArch64/AArch64ISelLowering.cpp' l='10264' c='_ZL20EmitVectorComparisonN4llvm7SDValueES0_NS_9AArch64CC8CondCodeEbNS_3EVTERKNS_5SDLocERNS_12SelectionDAGE'/>
<use f='llvm/llvm/lib/Target/AArch64/AArch64ISelLowering.cpp' l='14741' c='_ZL20isEquivalentMasklessjjN4llvm3ISD11LoadExtTypeEii'/>
<use f='llvm/llvm/lib/Target/AArch64/AArch64InstrInfo.cpp' l='1601' c='_ZL11getUsedNZCVN4llvm9AArch64CC8CondCodeE'/>
<use f='llvm/llvm/lib/Target/AArch64/AsmParser/AArch64AsmParser.cpp' l='2755' u='r' c='_ZN12_GLOBAL__N_116AArch64AsmParser19parseCondCodeStringEN4llvm9StringRefE'/>
<use f='llvm/llvm/lib/Target/AArch64/AsmParser/AArch64AsmParser.cpp' l='2756' u='r' c='_ZN12_GLOBAL__N_116AArch64AsmParser19parseCondCodeStringEN4llvm9StringRefE'/>
<use f='llvm/llvm/lib/Target/AArch64/AsmParser/AArch64AsmParser.cpp' l='2778' u='r' c='_ZN12_GLOBAL__N_116AArch64AsmParser19parseCondCodeStringEN4llvm9StringRefE'/>
<use f='llvm/llvm/lib/Target/AArch64/GISel/AArch64InstructionSelector.cpp' l='1203' u='r' c='_ZL25changeICMPPredToAArch64CCN4llvm7CmpInst9PredicateE'/>
<use f='llvm/llvm/lib/Target/AArch64/GISel/AArch64InstructionSelector.cpp' l='4377' u='a' c='_ZNK12_GLOBAL__N_126AArch64InstructionSelector14emitOverflowOpEjN4llvm8RegisterERNS1_14MachineOperandES4_RNS1_16MachineIRBuilderE'/>
