<dec f='llvm/build/lib/Target/Mips/MipsGenInstrInfo.inc' l='2411' type='2396'/>
<use f='llvm/build/lib/Target/Mips/MipsGenAsmMatcher.inc' l='7549'/>
<use f='llvm/llvm/lib/Target/Mips/Disassembler/MipsDisassembler.cpp' l='1544' u='r' c='_ZL9DecodeMemRN4llvm6MCInstEjmPKv'/>
<use f='llvm/build/lib/Target/Mips/MipsGenMCCodeEmitter.inc' l='7729' c='_ZNK4llvm17MipsMCCodeEmitter21getBinaryCodeForInstrERKNS_6MCInstERNS_15SmallVectorImplINS_7MCFixupEEERKNS_15MCSubtargetInfoE'/>
<use f='llvm/llvm/lib/Target/Mips/MipsExpandPseudo.cpp' l='236' u='r' c='_ZN12_GLOBAL__N_116MipsExpandPseudo19expandAtomicCmpSwapERN4llvm17MachineBasicBlockENS1_26MachineInstrBundleIteratorINS1_12MachineInstrELb0EEERS6_'/>
<use f='llvm/llvm/lib/Target/Mips/MipsExpandPseudo.cpp' l='620' u='r' c='_ZN12_GLOBAL__N_116MipsExpandPseudo17expandAtomicBinOpERN4llvm17MachineBasicBlockENS1_26MachineInstrBundleIteratorINS1_12MachineInstrELb0EEERS6_j'/>
<use f='llvm/llvm/lib/Target/Mips/MipsSERegisterInfo.cpp' l='86' c='_ZL28getLoadStoreOffsetSizeInBitsjN4llvm14MachineOperandE'/>
