<use f='llvm/llvm/include/llvm/Analysis/BranchProbabilityInfo.h' l='300' u='r' c='_ZNK4llvm21BranchProbabilityInfo9LoopBlock8getBlockEv'/>
<use f='llvm/llvm/include/llvm/Analysis/BranchProbabilityInfo.h' l='301' u='r' c='_ZN4llvm21BranchProbabilityInfo9LoopBlock8getBlockEv'/>
<dec f='llvm/llvm/include/llvm/Analysis/BranchProbabilityInfo.h' l='313' type='const llvm::BasicBlock *const'/>
<offset>0</offset>
<use f='llvm/llvm/lib/Analysis/BranchProbabilityInfo.cpp' l='245' u='w' c='_ZN4llvm21BranchProbabilityInfo9LoopBlockC1EPKNS_10BasicBlockERKNS_8LoopInfoERKNS0_7SccInfoE'/>
