<use f='llvm/llvm/lib/CodeGen/AsmPrinter/DwarfDebug.h' l='280' u='w' c='_ZN4llvm8SymbolCUC1EPNS_16DwarfCompileUnitEPKNS_8MCSymbolE'/>
<dec f='llvm/llvm/lib/CodeGen/AsmPrinter/DwarfDebug.h' l='283' type='llvm::DwarfCompileUnit *'/>
<offset>64</offset>
<use f='llvm/llvm/lib/CodeGen/AsmPrinter/DwarfDebug.cpp' l='2815' u='r' c='_ZN4llvm10DwarfDebug16emitDebugARangesEv'/>
<use f='llvm/llvm/lib/CodeGen/AsmPrinter/DwarfDebug.cpp' l='2844' u='r' c='_ZN4llvm10DwarfDebug16emitDebugARangesEv'/>
<use f='llvm/llvm/lib/CodeGen/AsmPrinter/DwarfDebug.cpp' l='2844' u='r' c='_ZN4llvm10DwarfDebug16emitDebugARangesEv'/>
<use f='llvm/llvm/lib/CodeGen/AsmPrinter/DwarfDebug.cpp' l='2849' u='r' c='_ZN4llvm10DwarfDebug16emitDebugARangesEv'/>
