<dec f='llvm/llvm/lib/Target/SystemZ/SystemZMachineScheduler.h' l='32' type='const llvm::MachineLoopInfo *'/>
<use f='llvm/llvm/lib/Target/SystemZ/SystemZMachineScheduler.cpp' l='96' u='r' c='_ZN4llvm26SystemZPostRASchedStrategy8enterMBBEPNS_17MachineBasicBlockE'/>
<use f='llvm/llvm/lib/Target/SystemZ/SystemZMachineScheduler.cpp' l='131' u='w' c='_ZN4llvm26SystemZPostRASchedStrategyC1EPKNS_19MachineSchedContextE'/>
<offset>64</offset>
