<dec f='llvm/llvm/lib/Target/AMDGPU/AMDGPUInstructionSelector.h' l='324' type='const llvm::AMDGPUTargetMachine &amp;'/>
<use f='llvm/build/lib/Target/AMDGPU/AMDGPUGenGlobalISel.inc' l='225' u='m' c='_ZNK4llvm25AMDGPUInstructionSelector32computeAvailableFunctionFeaturesEPKNS_12GCNSubtargetEPKNS_15MachineFunctionE'/>
<use f='llvm/llvm/lib/Target/AMDGPU/AMDGPUInstructionSelector.cpp' l='48' u='w' c='_ZN4llvm25AMDGPUInstructionSelectorC1ERKNS_12GCNSubtargetERKNS_22AMDGPURegisterBankInfoERKNS_19AMDGPUTargetMachineE'/>
<use f='llvm/llvm/lib/Target/AMDGPU/AMDGPUInstructionSelector.cpp' l='1423' u='m' c='_ZNK4llvm25AMDGPUInstructionSelector14selectSBarrierERNS_12MachineInstrE'/>
<use f='llvm/llvm/lib/Target/AMDGPU/AMDGPUInstructionSelector.cpp' l='3656' u='m' c='_ZNK4llvm25AMDGPUInstructionSelector23selectMUBUFScratchOffenERNS_14MachineOperandE'/>
<offset>576</offset>
