<use f='llvm/llvm/include/llvm/ExecutionEngine/Orc/Core.h' l='1051' u='w' c='_ZN4llvm3orc8JITDylib18UnmaterializedInfoC1ESt10unique_ptrINS0_19MaterializationUnitESt14default_deleteIS4_EEPNS0_15ResourceTrackerE'/>
<dec f='llvm/llvm/include/llvm/ExecutionEngine/Orc/Core.h' l='1053' type='std::unique_ptr&lt;MaterializationUnit&gt;'/>
<offset>0</offset>
<use f='llvm/llvm/lib/ExecutionEngine/Orc/Core.cpp' l='728' u='m' c='_ZN4llvm3orc8JITDylib7replaceERNS0_29MaterializationResponsibilityESt10unique_ptrINS0_19MaterializationUnitESt14default_deleteIS5_EE'/>
<use f='llvm/llvm/lib/ExecutionEngine/Orc/Core.cpp' l='1323' u='m' c='_ZN4llvm3orc8JITDylib6removeERKNS_8DenseSetINS0_15SymbolStringPtrENS_12DenseMapInfoIS3_EEEE'/>
<use f='llvm/llvm/lib/ExecutionEngine/Orc/Core.cpp' l='1357' u='m' c='_ZN4llvm3orc8JITDylib4dumpERNS_11raw_ostreamE'/>
<use f='llvm/llvm/lib/ExecutionEngine/Orc/Core.cpp' l='1357' u='m' c='_ZN4llvm3orc8JITDylib4dumpERNS_11raw_ostreamE'/>
<use f='llvm/llvm/lib/ExecutionEngine/Orc/Core.cpp' l='1606' u='m' c='_ZN4llvm3orc8JITDylib10defineImplERNS0_19MaterializationUnitE'/>
<use f='llvm/llvm/lib/ExecutionEngine/Orc/Core.cpp' l='1632' u='m' c='_ZN4llvm3orc8JITDylib26installMaterializationUnitESt10unique_ptrINS0_19MaterializationUnitESt14default_deleteIS3_EERNS0_15ResourceTrackerE'/>
<use f='llvm/llvm/lib/ExecutionEngine/Orc/Core.cpp' l='2398' u='m' c='_ZN4llvm3orc16ExecutionSession17OL_completeLookupESt10unique_ptrINS0_21InProgressLookupStateESt14default_deleteIS3_EESt10shared_ptrINS0_23Asynchronous13989853'/>
<use f='llvm/llvm/lib/ExecutionEngine/Orc/Core.cpp' l='2438' u='m' c='_ZN4llvm3orc16ExecutionSession17OL_completeLookupESt10unique_ptrINS0_21InProgressLookupStateESt14default_deleteIS3_EESt10shared_ptrINS0_23Asynchronous13989853'/>
<use f='llvm/llvm/lib/ExecutionEngine/Orc/Core.cpp' l='2493' u='m' c='_ZN4llvm3orc16ExecutionSession17OL_completeLookupESt10unique_ptrINS0_21InProgressLookupStateESt14default_deleteIS3_EESt10shared_ptrINS0_23Asynchronous13989853'/>
<use f='llvm/llvm/lib/ExecutionEngine/Orc/Core.cpp' l='2494' u='m' c='_ZN4llvm3orc16ExecutionSession17OL_completeLookupESt10unique_ptrINS0_21InProgressLookupStateESt14default_deleteIS3_EESt10shared_ptrINS0_23Asynchronous13989853'/>
<use f='llvm/llvm/lib/ExecutionEngine/Orc/Core.cpp' l='2497' u='a' c='_ZN4llvm3orc16ExecutionSession17OL_completeLookupESt10unique_ptrINS0_21InProgressLookupStateESt14default_deleteIS3_EESt10shared_ptrINS0_23Asynchronous13989853'/>
