<dec f='llvm/llvm/include/llvm/Support/raw_ostream.h' l='637' type='SmallVectorImpl&lt;char&gt; &amp;'/>
<use f='llvm/llvm/include/llvm/Support/raw_ostream.h' l='652' u='w' c='_ZN4llvm19raw_svector_ostreamC1ERNS_15SmallVectorImplIcEE'/>
<use f='llvm/llvm/include/llvm/Support/raw_ostream.h' l='661' u='m' c='_ZNK4llvm19raw_svector_ostream3strEv'/>
<use f='llvm/llvm/include/llvm/Support/raw_ostream.h' l='661' u='m' c='_ZNK4llvm19raw_svector_ostream3strEv'/>
<offset>512</offset>
<use f='llvm/llvm/lib/Support/raw_ostream.cpp' l='953' u='m' c='_ZNK4llvm19raw_svector_ostream11current_posEv'/>
<use f='llvm/llvm/lib/Support/raw_ostream.cpp' l='956' u='m' c='_ZN4llvm19raw_svector_ostream10write_implEPKcm'/>
<use f='llvm/llvm/lib/Support/raw_ostream.cpp' l='961' u='m' c='_ZN4llvm19raw_svector_ostream11pwrite_implEPKcmm'/>
