<dec f='llvm/llvm/unittests/CodeGen/TestAsmPrinter.h' l='51' type='llvm::MockMCStreamer *'/>
<use f='llvm/llvm/unittests/CodeGen/TestAsmPrinter.h' l='78' u='r' c='_ZNK4llvm14TestAsmPrinter5getMSEv'/>
<offset>64</offset>
<doc f='llvm/llvm/unittests/CodeGen/TestAsmPrinter.h' l='51'>// Owned by AsmPrinter</doc>
<use f='llvm/llvm/unittests/CodeGen/TestAsmPrinter.cpp' l='62' u='w' c='_ZN4llvm14TestAsmPrinter4initEPKNS_6TargetENS_9StringRefEtNS_5dwarf11DwarfFormatE'/>
<use f='llvm/llvm/unittests/CodeGen/TestAsmPrinter.cpp' l='65' u='r' c='_ZN4llvm14TestAsmPrinter4initEPKNS_6TargetENS_9StringRefEtNS_5dwarf11DwarfFormatE'/>
