<dec f='llvm/llvm/include/llvm/IR/ValueMap.h' l='386' type='llvm::ValueMapConstIterator::BaseT'/>
<use f='llvm/llvm/include/llvm/IR/ValueMap.h' l='389' u='w' c='_ZN4llvm21ValueMapConstIteratorC1Ev'/>
<use f='llvm/llvm/include/llvm/IR/ValueMap.h' l='390' u='w' c='_ZN4llvm21ValueMapConstIteratorC1ENT_14const_iteratorE'/>
<use f='llvm/llvm/include/llvm/IR/ValueMap.h' l='392' u='w' c='_ZN4llvm21ValueMapConstIteratorC1ENS_16ValueMapIteratorIT_T0_EE'/>
<use f='llvm/llvm/include/llvm/IR/ValueMap.h' l='394' u='r' c='_ZNK4llvm21ValueMapConstIterator4baseEv'/>
<use f='llvm/llvm/include/llvm/IR/ValueMap.h' l='406' u='c' c='_ZNK4llvm21ValueMapConstIteratordeEv'/>
<use f='llvm/llvm/include/llvm/IR/ValueMap.h' l='406' u='r' c='_ZNK4llvm21ValueMapConstIteratordeEv'/>
<use f='llvm/llvm/include/llvm/IR/ValueMap.h' l='415' c='_ZNK4llvm21ValueMapConstIteratoreqERKNS_21ValueMapConstIteratorIT_T0_EE'/>
<use f='llvm/llvm/include/llvm/IR/ValueMap.h' l='418' c='_ZNK4llvm21ValueMapConstIteratorneERKNS_21ValueMapConstIteratorIT_T0_EE'/>
<use f='llvm/llvm/include/llvm/IR/ValueMap.h' l='422' u='w' c='_ZN4llvm21ValueMapConstIteratorppEv'/>
