<dec f='llvm/llvm/lib/Transforms/Vectorize/VPlan.h' l='2089' type='const llvm::VPBasicBlock &amp;'/>
<use f='llvm/llvm/lib/Transforms/Vectorize/VPlan.h' l='2133' u='w' c='_ZN4llvm8VPlanSlpC1ERNS_23VPInterleavedAccessInfoERNS_12VPBasicBlockE'/>
<offset>256</offset>
<doc f='llvm/llvm/lib/Transforms/Vectorize/VPlan.h' l='2087'>/// Basic block to operate on. For now, only instructions in a single BB are
  /// considered.</doc>
<use f='llvm/llvm/lib/Transforms/Vectorize/VPlanSLP.cpp' l='105' u='a' c='_ZNK4llvm8VPlanSlp15areVectorizableENS_8ArrayRefIPNS_7VPValueEEE'/>
