<dec f='llvm/llvm/include/llvm/TableGen/Record.h' l='776' type='7'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='1075' c='_ZNK4llvm9BinOpInit4FoldEPNS_6RecordE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='1093' c='_ZNK4llvm9BinOpInit4FoldEPNS_6RecordE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='1125' c='_ZNK4llvm9BinOpInit11getAsStringB5cxx11Ev'/>
<use f='llvm/llvm/lib/TableGen/TGParser.cpp' l='1114' u='r' c='_ZN4llvm8TGParser14ParseOperationEPNS_6RecordEPNS_5RecTyE'/>
<use f='llvm/llvm/lib/TableGen/TGParser.cpp' l='1305' u='r' c='_ZN4llvm8TGParser14ParseOperationEPNS_6RecordEPNS_5RecTyE'/>
