<dec f='llvm/llvm/include/llvm/Analysis/LazyValueInfo.h' l='34' type='const llvm::DataLayout *'/>
<use f='llvm/llvm/include/llvm/Analysis/LazyValueInfo.h' l='44' u='w' c='_ZN4llvm13LazyValueInfoC1EPNS_15AssumptionCacheEPKNS_10DataLayoutEPNS_17TargetLibraryInfoE'/>
<use f='llvm/llvm/include/llvm/Analysis/LazyValueInfo.h' l='46' u='w' c='_ZN4llvm13LazyValueInfoC1EOS0_'/>
<use f='llvm/llvm/include/llvm/Analysis/LazyValueInfo.h' l='46' u='r' c='_ZN4llvm13LazyValueInfoC1EOS0_'/>
<use f='llvm/llvm/include/llvm/Analysis/LazyValueInfo.h' l='52' u='w' c='_ZN4llvm13LazyValueInfoaSEOS0_'/>
<use f='llvm/llvm/include/llvm/Analysis/LazyValueInfo.h' l='52' u='r' c='_ZN4llvm13LazyValueInfoaSEOS0_'/>
<offset>64</offset>
