<use f='llvm/llvm/lib/ExecutionEngine/JITLink/BasicGOTAndStubsBuilder.h' l='25' u='w' c='_ZN4llvm7jitlink23BasicGOTAndStubsBuilderC1ERNS0_9LinkGraphE'/>
<use f='llvm/llvm/lib/ExecutionEngine/JITLink/BasicGOTAndStubsBuilder.h' l='30' u='m' c='_ZN4llvm7jitlink23BasicGOTAndStubsBuilder3runEv'/>
<use f='llvm/llvm/lib/ExecutionEngine/JITLink/BasicGOTAndStubsBuilder.h' l='30' u='m' c='_ZN4llvm7jitlink23BasicGOTAndStubsBuilder3runEv'/>
<dec f='llvm/llvm/lib/ExecutionEngine/JITLink/BasicGOTAndStubsBuilder.h' l='95' type='llvm::jitlink::LinkGraph &amp;'/>
