<dec f='llvm/llvm/include/llvm/Transforms/Utils/CallGraphUpdater.h' l='42' type='llvm::CallGraph *'/>
<use f='llvm/llvm/include/llvm/Transforms/Utils/CallGraphUpdater.h' l='63' u='w' c='_ZN4llvm16CallGraphUpdater10initializeERNS_9CallGraphERNS_12CallGraphSCCE'/>
<offset>3584</offset>
<doc f='llvm/llvm/include/llvm/Transforms/Utils/CallGraphUpdater.h' l='38'>///}

  /// Old PM variables
  ///{</doc>
<use f='llvm/llvm/lib/Transforms/Utils/CallGraphUpdater.cpp' l='29' u='r' c='_ZN4llvm16CallGraphUpdater8finalizeEv'/>
<use f='llvm/llvm/lib/Transforms/Utils/CallGraphUpdater.cpp' l='34' u='r' c='_ZN4llvm16CallGraphUpdater8finalizeEv'/>
<use f='llvm/llvm/lib/Transforms/Utils/CallGraphUpdater.cpp' l='36' u='r' c='_ZN4llvm16CallGraphUpdater8finalizeEv'/>
<use f='llvm/llvm/lib/Transforms/Utils/CallGraphUpdater.cpp' l='42' u='r' c='_ZN4llvm16CallGraphUpdater8finalizeEv'/>
<use f='llvm/llvm/lib/Transforms/Utils/CallGraphUpdater.cpp' l='45' u='r' c='_ZN4llvm16CallGraphUpdater8finalizeEv'/>
<use f='llvm/llvm/lib/Transforms/Utils/CallGraphUpdater.cpp' l='88' u='r' c='_ZN4llvm16CallGraphUpdater17reanalyzeFunctionERNS_8FunctionE'/>
<use f='llvm/llvm/lib/Transforms/Utils/CallGraphUpdater.cpp' l='89' u='r' c='_ZN4llvm16CallGraphUpdater17reanalyzeFunctionERNS_8FunctionE'/>
<use f='llvm/llvm/lib/Transforms/Utils/CallGraphUpdater.cpp' l='91' u='r' c='_ZN4llvm16CallGraphUpdater17reanalyzeFunctionERNS_8FunctionE'/>
<use f='llvm/llvm/lib/Transforms/Utils/CallGraphUpdater.cpp' l='101' u='r' c='_ZN4llvm16CallGraphUpdater24registerOutlinedFunctionERNS_8FunctionES2_'/>
<use f='llvm/llvm/lib/Transforms/Utils/CallGraphUpdater.cpp' l='102' u='r' c='_ZN4llvm16CallGraphUpdater24registerOutlinedFunctionERNS_8FunctionES2_'/>
<use f='llvm/llvm/lib/Transforms/Utils/CallGraphUpdater.cpp' l='116' u='r' c='_ZN4llvm16CallGraphUpdater14removeFunctionERNS_8FunctionE'/>
<use f='llvm/llvm/lib/Transforms/Utils/CallGraphUpdater.cpp' l='117' u='r' c='_ZN4llvm16CallGraphUpdater14removeFunctionERNS_8FunctionE'/>
<use f='llvm/llvm/lib/Transforms/Utils/CallGraphUpdater.cpp' l='126' u='r' c='_ZN4llvm16CallGraphUpdater19replaceFunctionWithERNS_8FunctionES2_'/>
<use f='llvm/llvm/lib/Transforms/Utils/CallGraphUpdater.cpp' l='128' u='r' c='_ZN4llvm16CallGraphUpdater19replaceFunctionWithERNS_8FunctionES2_'/>
<use f='llvm/llvm/lib/Transforms/Utils/CallGraphUpdater.cpp' l='129' u='r' c='_ZN4llvm16CallGraphUpdater19replaceFunctionWithERNS_8FunctionES2_'/>
<use f='llvm/llvm/lib/Transforms/Utils/CallGraphUpdater.cpp' l='131' u='r' c='_ZN4llvm16CallGraphUpdater19replaceFunctionWithERNS_8FunctionES2_'/>
<use f='llvm/llvm/lib/Transforms/Utils/CallGraphUpdater.cpp' l='145' u='r' c='_ZN4llvm16CallGraphUpdater15replaceCallSiteERNS_8CallBaseES2_'/>
<use f='llvm/llvm/lib/Transforms/Utils/CallGraphUpdater.cpp' l='150' u='r' c='_ZN4llvm16CallGraphUpdater15replaceCallSiteERNS_8CallBaseES2_'/>
<use f='llvm/llvm/lib/Transforms/Utils/CallGraphUpdater.cpp' l='151' u='r' c='_ZN4llvm16CallGraphUpdater15replaceCallSiteERNS_8CallBaseES2_'/>
<use f='llvm/llvm/lib/Transforms/Utils/CallGraphUpdater.cpp' l='162' u='r' c='_ZN4llvm16CallGraphUpdater14removeCallSiteERNS_8CallBaseE'/>
<use f='llvm/llvm/lib/Transforms/Utils/CallGraphUpdater.cpp' l='166' u='r' c='_ZN4llvm16CallGraphUpdater14removeCallSiteERNS_8CallBaseE'/>
