<dec f='llvm/build/lib/Target/Lanai/LanaiGenRegisterInfo.inc' l='30' type='10'/>
<use f='llvm/build/lib/Target/Lanai/LanaiGenAsmMatcher.inc' l='767' c='_ZL20validateOperandClassRN4llvm18MCParsedAsmOperandEN12_GLOBAL__N_114MatchClassKindE'/>
<use f='llvm/llvm/lib/Target/Lanai/Disassembler/LanaiDisassembler.cpp' l='156'/>
<use f='llvm/llvm/lib/Target/Lanai/MCTargetDesc/LanaiBaseInfo.h' l='49' c='_ZN4llvmL25getLanaiRegisterNumberingEj'/>
