<dec f='llvm/build/lib/Target/SystemZ/SystemZGenInstrInfo.inc' l='1417' type='1402'/>
<use f='llvm/build/lib/Target/SystemZ/SystemZGenAsmMatcher.inc' l='4253'/>
<use f='llvm/build/lib/Target/SystemZ/SystemZGenMCCodeEmitter.inc' l='3973' c='_ZNK12_GLOBAL__N_120SystemZMCCodeEmitter21getBinaryCodeForInstrERKN4llvm6MCInstERNS1_15SmallVectorImplINS1_7MCFixupEEERKNS1_15MCSubtargetInfoE'/>
<use f='llvm/build/lib/Target/SystemZ/SystemZGenDAGISel.inc' l='18415' u='r' c='_ZN12_GLOBAL__N_119SystemZDAGToDAGISel10SelectCodeEPN4llvm6SDNodeE'/>
<use f='llvm/build/lib/Target/SystemZ/SystemZGenDAGISel.inc' l='18415' u='r' c='_ZN12_GLOBAL__N_119SystemZDAGToDAGISel10SelectCodeEPN4llvm6SDNodeE'/>
<use f='llvm/llvm/lib/Target/SystemZ/SystemZISelLowering.cpp' l='7356' u='r' c='_ZNK4llvm21SystemZTargetLowering20emitAtomicLoadBinaryERNS_12MachineInstrEPNS_17MachineBasicBlockEjjb'/>
<use f='llvm/llvm/lib/Target/SystemZ/SystemZISelLowering.cpp' l='7474' u='r' c='_ZNK4llvm21SystemZTargetLowering20emitAtomicLoadMinMaxERNS_12MachineInstrEPNS_17MachineBasicBlockEjjj'/>
<use f='llvm/llvm/lib/Target/SystemZ/SystemZISelLowering.cpp' l='7587' u='r' c='_ZNK4llvm21SystemZTargetLowering18emitAtomicCmpSwapWERNS_12MachineInstrEPNS_17MachineBasicBlockE'/>
<use f='llvm/llvm/lib/Target/SystemZ/SystemZInstrInfo.cpp' l='1376' u='r' c='_ZNK4llvm16SystemZInstrInfo18expandPostRAPseudoERNS_12MachineInstrE'/>
<use f='llvm/llvm/lib/Target/SystemZ/SystemZInstrInfo.cpp' l='1578' u='r' c='_ZNK4llvm16SystemZInstrInfo19getLoadStoreOpcodesEPKNS_19TargetRegisterClassERjS4_'/>
<use f='llvm/llvm/lib/Target/SystemZ/SystemZInstrInfo.cpp' l='1646' c='_ZNK4llvm16SystemZInstrInfo14getLoadAndTestEj'/>
<use f='llvm/llvm/lib/Target/SystemZ/SystemZInstrInfo.cpp' l='1907' c='_ZNK4llvm16SystemZInstrInfo14getLoadAndTrapEj'/>
