<dec f='llvm/llvm/lib/Target/Hexagon/HexagonISelLowering.h' l='53' type='346'/>
<doc f='llvm/llvm/lib/Target/Hexagon/HexagonISelLowering.h' l='53'>// Constant pool.</doc>
<use f='llvm/build/lib/Target/Hexagon/HexagonGenDAGISel.inc' l='61267' u='r' c='_ZN4llvm19HexagonDAGToDAGISel10SelectCodeEPNS_6SDNodeE'/>
<use f='llvm/build/lib/Target/Hexagon/HexagonGenDAGISel.inc' l='61267' u='r' c='_ZN4llvm19HexagonDAGToDAGISel10SelectCodeEPNS_6SDNodeE'/>
<use f='llvm/build/lib/Target/Hexagon/HexagonGenDAGISel.inc' l='66687' u='r' c='_ZN4llvm19HexagonDAGToDAGISel10SelectCodeEPNS_6SDNodeE'/>
<use f='llvm/build/lib/Target/Hexagon/HexagonGenDAGISel.inc' l='66687' u='r' c='_ZN4llvm19HexagonDAGToDAGISel10SelectCodeEPNS_6SDNodeE'/>
<use f='llvm/llvm/lib/Target/Hexagon/HexagonISelDAGToDAG.cpp' l='1363' c='_ZN4llvm19HexagonDAGToDAGISel18SelectAnyImmediateERNS_7SDValueES2_NS_5AlignE'/>
<use f='llvm/llvm/lib/Target/Hexagon/HexagonISelDAGToDAG.cpp' l='1417' c='_ZN4llvm19HexagonDAGToDAGISel19SelectGlobalAddressERNS_7SDValueES2_bNS_5AlignE'/>
<use f='llvm/llvm/lib/Target/Hexagon/HexagonISelLowering.cpp' l='1130' u='r' c='_ZNK4llvm21HexagonTargetLowering17LowerConstantPoolENS_7SDValueERNS_12SelectionDAGE'/>
<use f='llvm/llvm/lib/Target/Hexagon/HexagonISelLowering.cpp' l='1848' c='_ZNK4llvm21HexagonTargetLowering17getTargetNodeNameEj'/>
