<dec f='llvm/llvm/unittests/DebugInfo/DWARF/DwarfGenerator.h' l='251' type='llvm::MCStreamer *'/>
<offset>448</offset>
<doc f='llvm/llvm/unittests/DebugInfo/DWARF/DwarfGenerator.h' l='251'>// Owned by AsmPrinter</doc>
<use f='llvm/llvm/unittests/DebugInfo/DWARF/DwarfGenerator.cpp' l='405' u='w' c='_ZN4llvm8dwarfgen9GeneratorC1Ev'/>
<use f='llvm/llvm/unittests/DebugInfo/DWARF/DwarfGenerator.cpp' l='478' u='w' c='_ZN4llvm8dwarfgen9Generator4initENS_6TripleEt'/>
<use f='llvm/llvm/unittests/DebugInfo/DWARF/DwarfGenerator.cpp' l='483' u='r' c='_ZN4llvm8dwarfgen9Generator4initENS_6TripleEt'/>
<use f='llvm/llvm/unittests/DebugInfo/DWARF/DwarfGenerator.cpp' l='490' u='r' c='_ZN4llvm8dwarfgen9Generator4initENS_6TripleEt'/>
<use f='llvm/llvm/unittests/DebugInfo/DWARF/DwarfGenerator.cpp' l='528' u='r' c='_ZN4llvm8dwarfgen9Generator8generateEv'/>
<use f='llvm/llvm/unittests/DebugInfo/DWARF/DwarfGenerator.cpp' l='547' u='r' c='_ZN4llvm8dwarfgen9Generator8generateEv'/>
<use f='llvm/llvm/unittests/DebugInfo/DWARF/DwarfGenerator.cpp' l='551' u='r' c='_ZN4llvm8dwarfgen9Generator8generateEv'/>
