<dec f='llvm/llvm/include/llvm/CodeGen/StackProtector.h' l='43' type='const llvm::TargetMachine *'/>
<offset>256</offset>
<use f='llvm/llvm/lib/CodeGen/StackProtector.cpp' l='89' u='w' c='_ZN4llvm14StackProtector13runOnFunctionERNS_8FunctionE'/>
<use f='llvm/llvm/lib/CodeGen/StackProtector.cpp' l='90' u='r' c='_ZN4llvm14StackProtector13runOnFunctionERNS_8FunctionE'/>
<use f='llvm/llvm/lib/CodeGen/StackProtector.cpp' l='91' u='r' c='_ZN4llvm14StackProtector13runOnFunctionERNS_8FunctionE'/>
<use f='llvm/llvm/lib/CodeGen/StackProtector.cpp' l='439' u='r' c='_ZN4llvm14StackProtector21InsertStackProtectorsEv'/>
<use f='llvm/llvm/lib/CodeGen/StackProtector.cpp' l='440' u='r' c='_ZN4llvm14StackProtector21InsertStackProtectorsEv'/>
