<dec f='llvm/llvm/include/llvm/DebugInfo/CodeView/CodeView.h' l='145' type='1'/>
<use f='llvm/lldb/source/Plugins/SymbolFile/NativePDB/SymbolFileNativePDB.cpp' l='76' c='_ZL17TranslateLanguageN4llvm8codeview14SourceLanguageE'/>
<use f='llvm/lldb/source/Plugins/SymbolFile/PDB/SymbolFilePDB.cpp' l='66' c='_ZN12_GLOBAL__N_117TranslateLanguageEN4llvm8codeview14SourceLanguageE'/>
<use f='llvm/llvm/lib/CodeGen/AsmPrinter/CodeViewDebug.cpp' l='726' u='r' c='_ZL17MapDWLangToCVLangj'/>
<use f='llvm/llvm/lib/DebugInfo/CodeView/EnumTables.cpp' l='98'/>
<use f='llvm/llvm/lib/DebugInfo/PDB/PDBExtras.cpp' l='216' c='_ZN4llvm3pdblsERNS_11raw_ostreamERKNS_8codeview14SourceLanguageE'/>
<use f='llvm/llvm/lib/DebugInfo/PDB/PDBSymbolCompiland.cpp' l='90' u='r' c='_ZNK4llvm3pdb18PDBSymbolCompiland21getSourceFileFullPathB5cxx11Ev'/>
<use f='llvm/llvm/lib/DebugInfo/PDB/PDBSymbolCompiland.cpp' l='97' u='r' c='_ZNK4llvm3pdb18PDBSymbolCompiland21getSourceFileFullPathB5cxx11Ev'/>
<use f='llvm/llvm/lib/DebugInfo/PDB/PDBSymbolCompiland.cpp' l='98' u='r' c='_ZNK4llvm3pdb18PDBSymbolCompiland21getSourceFileFullPathB5cxx11Ev'/>
<use f='llvm/llvm/lib/DebugInfo/PDB/PDBSymbolCompiland.cpp' l='99' u='r' c='_ZNK4llvm3pdb18PDBSymbolCompiland21getSourceFileFullPathB5cxx11Ev'/>
<use f='llvm/llvm/tools/llvm-pdbutil/MinimalSymbolDumper.cpp' l='192' c='_ZL20formatSourceLanguageB5cxx11N4llvm8codeview14SourceLanguageE'/>
