<use f='llvm/llvm/include/llvm/ExecutionEngine/Orc/ExecutionUtils.h' l='104' u='w' c='_ZN4llvm3orc20StaticInitGVIteratorC1ERNS_6ModuleE'/>
<use f='llvm/llvm/include/llvm/ExecutionEngine/Orc/ExecutionUtils.h' l='106' u='r' c='_ZN4llvm3orc20StaticInitGVIteratorC1ERNS_6ModuleE'/>
<use f='llvm/llvm/include/llvm/ExecutionEngine/Orc/ExecutionUtils.h' l='110' u='w' c='_ZN4llvm3orc20StaticInitGVIteratorC1ERNS_6ModuleE'/>
<use f='llvm/llvm/include/llvm/ExecutionEngine/Orc/ExecutionUtils.h' l='128' u='r' c='_ZN4llvm3orc20StaticInitGVIterator26moveToNextStaticInitGlobalEv'/>
<use f='llvm/llvm/include/llvm/ExecutionEngine/Orc/ExecutionUtils.h' l='130' u='r' c='_ZN4llvm3orc20StaticInitGVIterator26moveToNextStaticInitGlobalEv'/>
<use f='llvm/llvm/include/llvm/ExecutionEngine/Orc/ExecutionUtils.h' l='131' u='w' c='_ZN4llvm3orc20StaticInitGVIterator26moveToNextStaticInitGlobalEv'/>
<dec f='llvm/llvm/include/llvm/ExecutionEngine/Orc/ExecutionUtils.h' l='134' type='Module::global_value_iterator'/>
<offset>512</offset>
