<dec f='llvm/llvm/include/llvm/ExecutionEngine/ExecutionEngine.h' l='114' type='const llvm::DataLayout'/>
<use f='llvm/llvm/include/llvm/ExecutionEngine/ExecutionEngine.h' l='197' u='a' c='_ZNK4llvm15ExecutionEngine13getDataLayoutEv'/>
<use f='llvm/llvm/include/llvm/ExecutionEngine/ExecutionEngine.h' l='505' u='w' c='_ZN4llvm15ExecutionEngineC1ENS_10DataLayoutE'/>
<offset>704</offset>
<doc f='llvm/llvm/include/llvm/ExecutionEngine/ExecutionEngine.h' l='108'>/// The target data for the platform for which execution is being performed.
  ///
  /// Note: the DataLayout is LLVMContext specific because it has an
  /// internal cache based on type pointers. It makes unsafe to reuse the
  /// ExecutionEngine across context, we don&apos;t enforce this rule but undefined
  /// behavior can occurs if the user tries to do it.</doc>
<use f='llvm/llvm/lib/ExecutionEngine/ExecutionEngine.cpp' l='81' u='w' c='_ZN4llvm15ExecutionEngineC1ESt10unique_ptrINS_6ModuleESt14default_deleteIS2_EE'/>
<use f='llvm/llvm/lib/ExecutionEngine/ExecutionEngine.cpp' l='86' u='w' c='_ZN4llvm15ExecutionEngineC1ENS_10DataLayoutESt10unique_ptrINS_6ModuleESt14default_deleteIS3_EE'/>
<use f='llvm/llvm/lib/ExecutionEngine/ExecutionEngine.cpp' l='643' u='m' c='_ZN4llvm15ExecutionEngine16getConstantValueEPKNS_8ConstantE'/>
<use f='llvm/llvm/lib/ExecutionEngine/ExecutionEngine.cpp' l='644' u='r' c='_ZN4llvm15ExecutionEngine16getConstantValueEPKNS_8ConstantE'/>
<use f='llvm/llvm/lib/ExecutionEngine/ExecutionEngine.cpp' l='731' u='m' c='_ZN4llvm15ExecutionEngine16getConstantValueEPKNS_8ConstantE'/>
<use f='llvm/llvm/lib/ExecutionEngine/ExecutionEngine.cpp' l='734' u='m' c='_ZN4llvm15ExecutionEngine16getConstantValueEPKNS_8ConstantE'/>
<use f='llvm/llvm/lib/ExecutionEngine/ExecutionEngine.cpp' l='740' u='m' c='_ZN4llvm15ExecutionEngine16getConstantValueEPKNS_8ConstantE'/>
