<use f='llvm/llvm/include/llvm/ExecutionEngine/Orc/ExecutionUtils.h' l='104' u='w' c='_ZN4llvm3orc20StaticInitGVIteratorC1ERNS_6ModuleE'/>
<use f='llvm/llvm/include/llvm/ExecutionEngine/Orc/ExecutionUtils.h' l='106' u='m' c='_ZN4llvm3orc20StaticInitGVIteratorC1ERNS_6ModuleE'/>
<use f='llvm/llvm/include/llvm/ExecutionEngine/Orc/ExecutionUtils.h' l='107' u='m' c='_ZN4llvm3orc20StaticInitGVIteratorC1ERNS_6ModuleE'/>
<use f='llvm/llvm/include/llvm/ExecutionEngine/Orc/ExecutionUtils.h' l='110' u='w' c='_ZN4llvm3orc20StaticInitGVIteratorC1ERNS_6ModuleE'/>
<use f='llvm/llvm/include/llvm/ExecutionEngine/Orc/ExecutionUtils.h' l='113' u='m' c='_ZNK4llvm3orc20StaticInitGVIteratoreqERKS1_'/>
<use f='llvm/llvm/include/llvm/ExecutionEngine/Orc/ExecutionUtils.h' l='113' u='r' c='_ZNK4llvm3orc20StaticInitGVIteratoreqERKS1_'/>
<use f='llvm/llvm/include/llvm/ExecutionEngine/Orc/ExecutionUtils.h' l='114' u='m' c='_ZNK4llvm3orc20StaticInitGVIteratorneERKS1_'/>
<use f='llvm/llvm/include/llvm/ExecutionEngine/Orc/ExecutionUtils.h' l='114' u='r' c='_ZNK4llvm3orc20StaticInitGVIteratorneERKS1_'/>
<use f='llvm/llvm/include/llvm/ExecutionEngine/Orc/ExecutionUtils.h' l='122' u='m' c='_ZN4llvm3orc20StaticInitGVIteratordeEv'/>
<use f='llvm/llvm/include/llvm/ExecutionEngine/Orc/ExecutionUtils.h' l='127' u='w' c='_ZN4llvm3orc20StaticInitGVIterator26moveToNextStaticInitGlobalEv'/>
<use f='llvm/llvm/include/llvm/ExecutionEngine/Orc/ExecutionUtils.h' l='128' u='m' c='_ZN4llvm3orc20StaticInitGVIterator26moveToNextStaticInitGlobalEv'/>
<use f='llvm/llvm/include/llvm/ExecutionEngine/Orc/ExecutionUtils.h' l='128' u='m' c='_ZN4llvm3orc20StaticInitGVIterator26moveToNextStaticInitGlobalEv'/>
<use f='llvm/llvm/include/llvm/ExecutionEngine/Orc/ExecutionUtils.h' l='129' u='w' c='_ZN4llvm3orc20StaticInitGVIterator26moveToNextStaticInitGlobalEv'/>
<use f='llvm/llvm/include/llvm/ExecutionEngine/Orc/ExecutionUtils.h' l='130' u='m' c='_ZN4llvm3orc20StaticInitGVIterator26moveToNextStaticInitGlobalEv'/>
<use f='llvm/llvm/include/llvm/ExecutionEngine/Orc/ExecutionUtils.h' l='131' u='w' c='_ZN4llvm3orc20StaticInitGVIterator26moveToNextStaticInitGlobalEv'/>
<dec f='llvm/llvm/include/llvm/ExecutionEngine/Orc/ExecutionUtils.h' l='134' type='Module::global_value_iterator'/>
<offset>0</offset>
