<dec f='llvm/llvm/include/llvm/CodeGen/FaultMaps.h' l='156' type='const uint8_t *'/>
<use f='llvm/llvm/include/llvm/CodeGen/FaultMaps.h' l='162' u='w' c='_ZN4llvm14FaultMapParser20FunctionInfoAccessorC1EPKhS3_'/>
<use f='llvm/llvm/include/llvm/CodeGen/FaultMaps.h' l='165' u='r' c='_ZNK4llvm14FaultMapParser20FunctionInfoAccessor15getFunctionAddrEv'/>
<use f='llvm/llvm/include/llvm/CodeGen/FaultMaps.h' l='169' u='r' c='_ZNK4llvm14FaultMapParser20FunctionInfoAccessor17getNumFaultingPCsEv'/>
<use f='llvm/llvm/include/llvm/CodeGen/FaultMaps.h' l='176' u='r' c='_ZNK4llvm14FaultMapParser20FunctionInfoAccessor22getFunctionFaultInfoAtEj'/>
<use f='llvm/llvm/include/llvm/CodeGen/FaultMaps.h' l='185' u='r' c='_ZNK4llvm14FaultMapParser20FunctionInfoAccessor19getNextFunctionInfoEv'/>
<offset>64</offset>
