<dec f='llvm/llvm/lib/Target/RISCV/MCTargetDesc/RISCVTargetStreamer.h' l='41' type='llvm::formatted_raw_ostream &amp;'/>
<offset>128</offset>
<use f='llvm/llvm/lib/Target/RISCV/MCTargetDesc/RISCVTargetStreamer.cpp' l='102' u='w' c='_ZN4llvm22RISCVTargetAsmStreamerC1ERNS_10MCStreamerERNS_21formatted_raw_ostreamE'/>
<use f='llvm/llvm/lib/Target/RISCV/MCTargetDesc/RISCVTargetStreamer.cpp' l='105' u='m' c='_ZN4llvm22RISCVTargetAsmStreamer23emitDirectiveOptionPushEv'/>
<use f='llvm/llvm/lib/Target/RISCV/MCTargetDesc/RISCVTargetStreamer.cpp' l='109' u='m' c='_ZN4llvm22RISCVTargetAsmStreamer22emitDirectiveOptionPopEv'/>
<use f='llvm/llvm/lib/Target/RISCV/MCTargetDesc/RISCVTargetStreamer.cpp' l='113' u='m' c='_ZN4llvm22RISCVTargetAsmStreamer22emitDirectiveOptionPICEv'/>
<use f='llvm/llvm/lib/Target/RISCV/MCTargetDesc/RISCVTargetStreamer.cpp' l='117' u='m' c='_ZN4llvm22RISCVTargetAsmStreamer24emitDirectiveOptionNoPICEv'/>
<use f='llvm/llvm/lib/Target/RISCV/MCTargetDesc/RISCVTargetStreamer.cpp' l='121' u='m' c='_ZN4llvm22RISCVTargetAsmStreamer22emitDirectiveOptionRVCEv'/>
<use f='llvm/llvm/lib/Target/RISCV/MCTargetDesc/RISCVTargetStreamer.cpp' l='125' u='m' c='_ZN4llvm22RISCVTargetAsmStreamer24emitDirectiveOptionNoRVCEv'/>
<use f='llvm/llvm/lib/Target/RISCV/MCTargetDesc/RISCVTargetStreamer.cpp' l='129' u='m' c='_ZN4llvm22RISCVTargetAsmStreamer24emitDirectiveOptionRelaxEv'/>
<use f='llvm/llvm/lib/Target/RISCV/MCTargetDesc/RISCVTargetStreamer.cpp' l='133' u='m' c='_ZN4llvm22RISCVTargetAsmStreamer26emitDirectiveOptionNoRelaxEv'/>
<use f='llvm/llvm/lib/Target/RISCV/MCTargetDesc/RISCVTargetStreamer.cpp' l='137' u='m' c='_ZN4llvm22RISCVTargetAsmStreamer13emitAttributeEjj'/>
<use f='llvm/llvm/lib/Target/RISCV/MCTargetDesc/RISCVTargetStreamer.cpp' l='142' u='m' c='_ZN4llvm22RISCVTargetAsmStreamer17emitTextAttributeEjNS_9StringRefE'/>
