<use f='llvm/llvm/lib/ExecutionEngine/JITLink/EHFrameSupportImpl.h' l='77' u='w' c='_ZN4llvm7jitlink16EHFrameEdgeFixer12ParseContextC1ERNS0_9LinkGraphE'/>
<dec f='llvm/llvm/lib/ExecutionEngine/JITLink/EHFrameSupportImpl.h' l='87' type='llvm::jitlink::LinkGraph &amp;'/>
<use f='llvm/llvm/lib/ExecutionEngine/JITLink/EHFrameSupport.cpp' l='206' u='m' c='_ZN4llvm7jitlink16EHFrameEdgeFixer12processBlockERNS1_12ParseContextERNS0_5BlockE'/>
<use f='llvm/llvm/lib/ExecutionEngine/JITLink/EHFrameSupport.cpp' l='271' u='m' c='_ZN4llvm7jitlink16EHFrameEdgeFixer10processCIEERNS1_12ParseContextERNS0_5BlockEmmm'/>
<use f='llvm/llvm/lib/ExecutionEngine/JITLink/EHFrameSupport.cpp' l='277' u='m' c='_ZN4llvm7jitlink16EHFrameEdgeFixer10processCIEERNS1_12ParseContextERNS0_5BlockEmmm'/>
<use f='llvm/llvm/lib/ExecutionEngine/JITLink/EHFrameSupport.cpp' l='294' u='m' c='_ZN4llvm7jitlink16EHFrameEdgeFixer10processCIEERNS1_12ParseContextERNS0_5BlockEmmm'/>
<use f='llvm/llvm/lib/ExecutionEngine/JITLink/EHFrameSupport.cpp' l='401' u='m' c='_ZN4llvm7jitlink16EHFrameEdgeFixer10processFDEERNS1_12ParseContextERNS0_5BlockEmmmjRNS_8DenseMapIjNS1_10EdgeTargetENS_12DenseMapInfoIjEENS_6detail12DenseMapPairIjS7_EEEE'/>
<use f='llvm/llvm/lib/ExecutionEngine/JITLink/EHFrameSupport.cpp' l='407' u='m' c='_ZN4llvm7jitlink16EHFrameEdgeFixer10processFDEERNS1_12ParseContextERNS0_5BlockEmmmjRNS_8DenseMapIjNS1_10EdgeTargetENS_12DenseMapInfoIjEENS_6detail12DenseMapPairIjS7_EEEE'/>
<use f='llvm/llvm/lib/ExecutionEngine/JITLink/EHFrameSupport.cpp' l='730' u='m' c='_ZN4llvm7jitlink16EHFrameEdgeFixer17getOrCreateSymbolERNS1_12ParseContextEm'/>
<offset>0</offset>
