<dec f='llvm/llvm/include/llvm/Transforms/Scalar/GVN.h' l='231' type='const llvm::BasicBlock *'/>
<use f='llvm/llvm/include/llvm/Transforms/Scalar/GVN.h' l='266' u='w' c='_ZN4llvm3GVN16addToLeaderTableEjPNS_5ValueEPKNS_10BasicBlockE'/>
<use f='llvm/llvm/include/llvm/Transforms/Scalar/GVN.h' l='272' u='w' c='_ZN4llvm3GVN16addToLeaderTableEjPNS_5ValueEPKNS_10BasicBlockE'/>
<use f='llvm/llvm/include/llvm/Transforms/Scalar/GVN.h' l='283' u='r' c='_ZN4llvm3GVN21removeFromLeaderTableEjPNS_11InstructionEPNS_10BasicBlockE'/>
<use f='llvm/llvm/include/llvm/Transforms/Scalar/GVN.h' l='296' u='w' c='_ZN4llvm3GVN21removeFromLeaderTableEjPNS_11InstructionEPNS_10BasicBlockE'/>
<use f='llvm/llvm/include/llvm/Transforms/Scalar/GVN.h' l='300' u='w' c='_ZN4llvm3GVN21removeFromLeaderTableEjPNS_11InstructionEPNS_10BasicBlockE'/>
<use f='llvm/llvm/include/llvm/Transforms/Scalar/GVN.h' l='300' u='r' c='_ZN4llvm3GVN21removeFromLeaderTableEjPNS_11InstructionEPNS_10BasicBlockE'/>
<offset>64</offset>
<use f='llvm/llvm/lib/Transforms/Scalar/GVN.cpp' l='1810' u='r' c='_ZN4llvm3GVN10ValueTable14areAllValsInBBEjPKNS_10BasicBlockERS0_'/>
<use f='llvm/llvm/lib/Transforms/Scalar/GVN.cpp' l='1935' u='r' c='_ZN4llvm3GVN10findLeaderEPKNS_10BasicBlockEj'/>
<use f='llvm/llvm/lib/Transforms/Scalar/GVN.cpp' l='1942' u='r' c='_ZN4llvm3GVN10findLeaderEPKNS_10BasicBlockEj'/>
