<use f='llvm/llvm/include/llvm/PassAnalysisSupport.h' l='160' u='w' c='_ZN4llvm16AnalysisResolverC1ERNS_13PMDataManagerE'/>
<use f='llvm/llvm/include/llvm/PassAnalysisSupport.h' l='162' u='a' c='_ZN4llvm16AnalysisResolver16getPMDataManagerEv'/>
<dec f='llvm/llvm/include/llvm/PassAnalysisSupport.h' l='200' type='llvm::PMDataManager &amp;'/>
<offset>192</offset>
<doc f='llvm/llvm/include/llvm/PassAnalysisSupport.h' l='199'>/// PassManager that is used to resolve analysis info</doc>
<use f='llvm/llvm/lib/IR/LegacyPassManager.cpp' l='1312' u='m' c='_ZNK4llvm16AnalysisResolver22getAnalysisIfAvailableEPKv'/>
<use f='llvm/llvm/lib/IR/LegacyPassManager.cpp' l='1317' u='m' c='_ZN4llvm16AnalysisResolver12findImplPassEPNS_4PassEPKvRNS_8FunctionE'/>
