<dec f='llvm/llvm/lib/CodeGen/SelectionDAG/SelectionDAGBuilder.h' l='382' type='const llvm::TargetMachine &amp;'/>
<use f='llvm/llvm/lib/CodeGen/SelectionDAG/SelectionDAGBuilder.h' l='441' u='w' c='_ZN4llvm19SelectionDAGBuilderC1ERNS_12SelectionDAGERNS_20FunctionLoweringInfoERNS_23SwiftErrorValueTrackingENS_10CodeGenOpt5LevelE'/>
<use f='llvm/llvm/lib/CodeGen/SelectionDAG/SelectionDAGBuilder.cpp' l='1005' u='r' c='_ZN4llvm19SelectionDAGBuilder4initEPNS_14GCFunctionInfoEPNS_9AAResultsEPKNS_17TargetLibraryInfoE'/>
<use f='llvm/llvm/lib/CodeGen/SelectionDAG/SelectionDAGBuilder.cpp' l='1602' u='m' c='_ZN4llvm19SelectionDAGBuilder13visitCatchRetERKNS_15CatchReturnInstE'/>
<use f='llvm/llvm/lib/CodeGen/SelectionDAG/SelectionDAGBuilder.cpp' l='2072' u='m' c='_ZN4llvm19SelectionDAGBuilder28EmitBranchForMergedConditionEPKNS_5ValueEPNS_17MachineBasicBlockES5_S5_S5_NS_17BranchProbabilityES6_b'/>
<use f='llvm/llvm/lib/CodeGen/SelectionDAG/SelectionDAGBuilder.cpp' l='2260' u='m' c='_ZN4llvm19SelectionDAGBuilder7visitBrERKNS_10BranchInstE'/>
<use f='llvm/llvm/lib/CodeGen/SelectionDAG/SelectionDAGBuilder.cpp' l='2641' u='m' c='_ZN4llvm19SelectionDAGBuilder24visitSPDescriptorFailureERNS0_24StackProtectorDescriptorE'/>
<use f='llvm/llvm/lib/CodeGen/SelectionDAG/SelectionDAGBuilder.cpp' l='2646' u='m' c='_ZN4llvm19SelectionDAGBuilder24visitSPDescriptorFailureERNS0_24StackProtectorDescriptorE'/>
<use f='llvm/llvm/lib/CodeGen/SelectionDAG/SelectionDAGBuilder.cpp' l='3129' u='m' c='_ZN4llvm19SelectionDAGBuilder9visitFCmpERKNS_4UserE'/>
<use f='llvm/llvm/lib/CodeGen/SelectionDAG/SelectionDAGBuilder.cpp' l='3420' u='m' c='_ZN4llvm19SelectionDAGBuilder18visitAddrSpaceCastERKNS_4UserE'/>
<use f='llvm/llvm/lib/CodeGen/SelectionDAG/SelectionDAGBuilder.cpp' l='6185' u='m' c='_ZN4llvm19SelectionDAGBuilder18visitIntrinsicCallERKNS_8CallInstEj'/>
<use f='llvm/llvm/lib/CodeGen/SelectionDAG/SelectionDAGBuilder.cpp' l='6636' u='m' c='_ZN4llvm19SelectionDAGBuilder18visitIntrinsicCallERKNS_8CallInstEj'/>
<use f='llvm/llvm/lib/CodeGen/SelectionDAG/SelectionDAGBuilder.cpp' l='7080' u='m' c='_ZN4llvm19SelectionDAGBuilder27visitConstrainedFPIntrinsicERKNS_22ConstrainedFPIntrinsicE'/>
<use f='llvm/llvm/lib/CodeGen/SelectionDAG/SelectionDAGBuilder.cpp' l='7691' u='m' c='_ZN4llvm19SelectionDAGBuilder9visitCallERKNS_8CallInstE'/>
<use f='llvm/llvm/lib/CodeGen/SelectionDAG/SelectionDAGBuilder.cpp' l='10340' u='m' c='_ZN4llvm19SelectionDAGBuilder13lowerWorkItemENS_8SwitchCG18SwitchWorkListItemEPNS_5ValueEPNS_17MachineBasicBlockES6_'/>
<use f='llvm/llvm/lib/CodeGen/SelectionDAG/SelectionDAGBuilder.cpp' l='10678' u='m' c='_ZN4llvm19SelectionDAGBuilder23peelDominantCaseClusterERKNS_10SwitchInstERSt6vectorINS_8SwitchCG11CaseClusterESaIS6_EERNS_17BranchProbabilityE'/>
<use f='llvm/llvm/lib/CodeGen/SelectionDAG/SelectionDAGBuilder.cpp' l='10800' u='m' c='_ZN4llvm19SelectionDAGBuilder11visitSwitchERKNS_10SwitchInstE'/>
<offset>6592</offset>
