<dec f='llvm/llvm/include/llvm/IR/PatternMatch.h' l='177' type='const llvm::APInt *&amp;'/>
<use f='llvm/llvm/include/llvm/IR/PatternMatch.h' l='181' u='w' c='_ZN4llvm12PatternMatch11apint_matchC1ERPKNS_5APIntEb'/>
<use f='llvm/llvm/include/llvm/IR/PatternMatch.h' l='185' u='w' c='_ZN4llvm12PatternMatch11apint_match5matchEPT_'/>
<use f='llvm/llvm/include/llvm/IR/PatternMatch.h' l='192' u='w' c='_ZN4llvm12PatternMatch11apint_match5matchEPT_'/>
<offset>0</offset>
