<dec f='llvm/llvm/include/llvm/Analysis/DependenceAnalysis.h' l='389' type='const llvm::SCEV *'/>
<offset>192</offset>
<use f='llvm/llvm/lib/Analysis/DependenceAnalysis.cpp' l='329' u='r' c='_ZNK4llvm14DependenceInfo10Constraint4getYEv'/>
<use f='llvm/llvm/lib/Analysis/DependenceAnalysis.cpp' l='347' u='r' c='_ZNK4llvm14DependenceInfo10Constraint4getBEv'/>
<use f='llvm/llvm/lib/Analysis/DependenceAnalysis.cpp' l='379' u='w' c='_ZN4llvm14DependenceInfo10Constraint8setPointEPKNS_4SCEVES4_PKNS_4LoopE'/>
<use f='llvm/llvm/lib/Analysis/DependenceAnalysis.cpp' l='387' u='w' c='_ZN4llvm14DependenceInfo10Constraint7setLineEPKNS_4SCEVES4_S4_PKNS_4LoopE'/>
<use f='llvm/llvm/lib/Analysis/DependenceAnalysis.cpp' l='396' u='w' c='_ZN4llvm14DependenceInfo10Constraint11setDistanceEPKNS_4SCEVEPKNS_4LoopE'/>
