<dec f='llvm/llvm/include/llvm/CodeGen/MachineModuleInfo.h' l='82' type='const llvm::LLVMTargetMachine &amp;'/>
<use f='llvm/llvm/include/llvm/CodeGen/MachineModuleInfo.h' l='165' u='a' c='_ZNK4llvm17MachineModuleInfo9getTargetEv'/>
<offset>0</offset>
<use f='llvm/llvm/lib/CodeGen/MachineModuleInfo.cpp' l='180' u='w' c='_ZN4llvm17MachineModuleInfoC1EOS0_'/>
<use f='llvm/llvm/lib/CodeGen/MachineModuleInfo.cpp' l='180' u='r' c='_ZN4llvm17MachineModuleInfoC1EOS0_'/>
<use f='llvm/llvm/lib/CodeGen/MachineModuleInfo.cpp' l='181' u='m' c='_ZN4llvm17MachineModuleInfoC1EOS0_'/>
<use f='llvm/llvm/lib/CodeGen/MachineModuleInfo.cpp' l='181' u='m' c='_ZN4llvm17MachineModuleInfoC1EOS0_'/>
<use f='llvm/llvm/lib/CodeGen/MachineModuleInfo.cpp' l='182' u='m' c='_ZN4llvm17MachineModuleInfoC1EOS0_'/>
<use f='llvm/llvm/lib/CodeGen/MachineModuleInfo.cpp' l='196' u='w' c='_ZN4llvm17MachineModuleInfoC1EPKNS_17LLVMTargetMachineE'/>
<use f='llvm/llvm/lib/CodeGen/MachineModuleInfo.cpp' l='203' u='w' c='_ZN4llvm17MachineModuleInfoC1EPKNS_17LLVMTargetMachineEPNS_9MCContextE'/>
<use f='llvm/llvm/lib/CodeGen/MachineModuleInfo.cpp' l='250' u='m' c='_ZN4llvm17MachineModuleInfo26getOrCreateMachineFunctionERNS_8FunctionE'/>
<use f='llvm/llvm/lib/CodeGen/MachineModuleInfo.cpp' l='251' u='r' c='_ZN4llvm17MachineModuleInfo26getOrCreateMachineFunctionERNS_8FunctionE'/>
