<dec f='llvm/llvm/unittests/DebugInfo/DWARF/DwarfGenerator.h' l='58' type='dwarfgen::CompileUnit *'/>
<use f='llvm/llvm/unittests/DebugInfo/DWARF/DwarfGenerator.h' l='65' u='w' c='_ZN4llvm8dwarfgen3DIEC1EPNS0_11CompileUnitEPNS_3DIEE'/>
<offset>0</offset>
<use f='llvm/llvm/unittests/DebugInfo/DWARF/DwarfGenerator.cpp' l='49' u='r' c='_ZN4llvm8dwarfgen3DIE21computeSizeAndOffsetsEj'/>
<use f='llvm/llvm/unittests/DebugInfo/DWARF/DwarfGenerator.cpp' l='55' u='r' c='_ZN4llvm8dwarfgen3DIE12addAttributeEtNS_5dwarf4FormEm'/>
<use f='llvm/llvm/unittests/DebugInfo/DWARF/DwarfGenerator.cpp' l='61' u='r' c='_ZN4llvm8dwarfgen3DIE12addAttributeEtNS_5dwarf4FormERKNS_6MCExprE'/>
<use f='llvm/llvm/unittests/DebugInfo/DWARF/DwarfGenerator.cpp' l='68' u='r' c='_ZN4llvm8dwarfgen3DIE12addAttributeEtNS_5dwarf4FormENS_9StringRefE'/>
<use f='llvm/llvm/unittests/DebugInfo/DWARF/DwarfGenerator.cpp' l='100' u='r' c='_ZN4llvm8dwarfgen3DIE12addAttributeEtNS_5dwarf4FormERS1_'/>
<use f='llvm/llvm/unittests/DebugInfo/DWARF/DwarfGenerator.cpp' l='107' u='r' c='_ZN4llvm8dwarfgen3DIE12addAttributeEtNS_5dwarf4FormEPKvm'/>
<use f='llvm/llvm/unittests/DebugInfo/DWARF/DwarfGenerator.cpp' l='121' u='r' c='_ZN4llvm8dwarfgen3DIE12addAttributeEtNS_5dwarf4FormE'/>
<use f='llvm/llvm/unittests/DebugInfo/DWARF/DwarfGenerator.cpp' l='128' u='r' c='_ZN4llvm8dwarfgen3DIE26addStrOffsetsBaseAttributeEv'/>
<use f='llvm/llvm/unittests/DebugInfo/DWARF/DwarfGenerator.cpp' l='146' u='r' c='_ZN4llvm8dwarfgen3DIE8addChildENS_5dwarf3TagE'/>
<use f='llvm/llvm/unittests/DebugInfo/DWARF/DwarfGenerator.cpp' l='147' u='r' c='_ZN4llvm8dwarfgen3DIE8addChildENS_5dwarf3TagE'/>
