<def f='llvm/llvm/include/llvm/Support/CommandLine.h' l='471' ll='477'/>
<size>8</size>
<doc f='llvm/llvm/include/llvm/Support/CommandLine.h' l='470'>// sub - Specify the subcommand that this option belongs to.</doc>
<mbr r='llvm::cl::sub::Sub' o='0' t='llvm::cl::SubCommand &amp;'/>
<fun r='_ZN4llvm2cl3subC1ERNS0_10SubCommandE'/>
<fun r='_ZNK4llvm2cl3sub5applyERT_'/>
<use f='llvm/clang/lib/Tooling/CommonOptionsParser.cpp' l='89' c='_ZN5clang7tooling19CommonOptionsParser4initERiPPKcRN4llvm2cl14OptionCategoryENS7_18NumOccurrencesFlagES4_'/>
<use f='llvm/clang/lib/Tooling/CommonOptionsParser.cpp' l='93' c='_ZN5clang7tooling19CommonOptionsParser4initERiPPKcRN4llvm2cl14OptionCategoryENS7_18NumOccurrencesFlagES4_'/>
<use f='llvm/clang/lib/Tooling/CommonOptionsParser.cpp' l='98' c='_ZN5clang7tooling19CommonOptionsParser4initERiPPKcRN4llvm2cl14OptionCategoryENS7_18NumOccurrencesFlagES4_'/>
<use f='llvm/clang/lib/Tooling/CommonOptionsParser.cpp' l='103' c='_ZN5clang7tooling19CommonOptionsParser4initERiPPKcRN4llvm2cl14OptionCategoryENS7_18NumOccurrencesFlagES4_'/>
<size>8</size>
<use f='llvm/clang/tools/clang-refactor/ClangRefactor.cpp' l='42'/>
<use f='llvm/clang/tools/clang-refactor/ClangRefactor.cpp' l='46'/>
<use f='llvm/clang/tools/clang-refactor/ClangRefactor.cpp' l='242' c='_ZN12_GLOBAL__N_135CommandLineRefactoringOptionCreator6createERKN5clang7tooling17RefactoringOptionE'/>
<use f='llvm/clang/tools/clang-refactor/ClangRefactor.cpp' l='269' c='_ZN12_GLOBAL__N_127RefactoringActionSubcommandC1ESt10unique_ptrIN5clang7tooling17RefactoringActionESt14default_deleteIS4_EESt6vectorIS1_INS3_21Refacto13261911'/>
<size>8</size>
<use f='llvm/lldb/tools/lldb-test/lldb-test.cpp' l='62'/>
<use f='llvm/lldb/tools/lldb-test/lldb-test.cpp' l='63'/>
<use f='llvm/lldb/tools/lldb-test/lldb-test.cpp' l='64'/>
<use f='llvm/lldb/tools/lldb-test/lldb-test.cpp' l='65'/>
<use f='llvm/lldb/tools/lldb-test/lldb-test.cpp' l='75'/>
<use f='llvm/lldb/tools/lldb-test/lldb-test.cpp' l='79'/>
<use f='llvm/lldb/tools/lldb-test/lldb-test.cpp' l='83'/>
<use f='llvm/lldb/tools/lldb-test/lldb-test.cpp' l='94'/>
<use f='llvm/lldb/tools/lldb-test/lldb-test.cpp' l='97'/>
<use f='llvm/lldb/tools/lldb-test/lldb-test.cpp' l='100'/>
<use f='llvm/lldb/tools/lldb-test/lldb-test.cpp' l='105'/>
<use f='llvm/lldb/tools/lldb-test/lldb-test.cpp' l='110'/>
<use f='llvm/lldb/tools/lldb-test/lldb-test.cpp' l='129'/>
<use f='llvm/lldb/tools/lldb-test/lldb-test.cpp' l='132'/>
<use f='llvm/lldb/tools/lldb-test/lldb-test.cpp' l='137'/>
<use f='llvm/lldb/tools/lldb-test/lldb-test.cpp' l='141'/>
<use f='llvm/lldb/tools/lldb-test/lldb-test.cpp' l='146'/>
<use f='llvm/lldb/tools/lldb-test/lldb-test.cpp' l='150'/>
<use f='llvm/lldb/tools/lldb-test/lldb-test.cpp' l='161'/>
<use f='llvm/lldb/tools/lldb-test/lldb-test.cpp' l='171'/>
<use f='llvm/lldb/tools/lldb-test/lldb-test.cpp' l='178'/>
<use f='llvm/lldb/tools/lldb-test/lldb-test.cpp' l='181'/>
<use f='llvm/lldb/tools/lldb-test/lldb-test.cpp' l='185'/>
<use f='llvm/lldb/tools/lldb-test/lldb-test.cpp' l='187'/>
<use f='llvm/lldb/tools/lldb-test/lldb-test.cpp' l='208'/>
<use f='llvm/lldb/tools/lldb-test/lldb-test.cpp' l='212'/>
<use f='llvm/lldb/tools/lldb-test/lldb-test.cpp' l='215'/>
<size>8</size>
<use f='llvm/llvm/lib/Support/CommandLine.cpp' l='2391'/>
<use f='llvm/llvm/lib/Support/CommandLine.cpp' l='2397'/>
<use f='llvm/llvm/lib/Support/CommandLine.cpp' l='2405'/>
<use f='llvm/llvm/lib/Support/CommandLine.cpp' l='2413'/>
<use f='llvm/llvm/lib/Support/CommandLine.cpp' l='2419'/>
<use f='llvm/llvm/lib/Support/CommandLine.cpp' l='2424'/>
<size>8</size>
<use f='llvm/llvm/tools/llvm-pdbutil/llvm-pdbutil.cpp' l='159'/>
<use f='llvm/llvm/tools/llvm-pdbutil/llvm-pdbutil.cpp' l='162'/>
<use f='llvm/llvm/tools/llvm-pdbutil/llvm-pdbutil.cpp' l='166'/>
<use f='llvm/llvm/tools/llvm-pdbutil/llvm-pdbutil.cpp' l='170'/>
<use f='llvm/llvm/tools/llvm-pdbutil/llvm-pdbutil.cpp' l='176'/>
<use f='llvm/llvm/tools/llvm-pdbutil/llvm-pdbutil.cpp' l='179'/>
<use f='llvm/llvm/tools/llvm-pdbutil/llvm-pdbutil.cpp' l='181'/>
<use f='llvm/llvm/tools/llvm-pdbutil/llvm-pdbutil.cpp' l='183'/>
<use f='llvm/llvm/tools/llvm-pdbutil/llvm-pdbutil.cpp' l='186'/>
<use f='llvm/llvm/tools/llvm-pdbutil/llvm-pdbutil.cpp' l='189'/>
<use f='llvm/llvm/tools/llvm-pdbutil/llvm-pdbutil.cpp' l='191'/>
<use f='llvm/llvm/tools/llvm-pdbutil/llvm-pdbutil.cpp' l='193'/>
<use f='llvm/llvm/tools/llvm-pdbutil/llvm-pdbutil.cpp' l='195'/>
<use f='llvm/llvm/tools/llvm-pdbutil/llvm-pdbutil.cpp' l='201'/>
<use f='llvm/llvm/tools/llvm-pdbutil/llvm-pdbutil.cpp' l='205'/>
<use f='llvm/llvm/tools/llvm-pdbutil/llvm-pdbutil.cpp' l='209'/>
<use f='llvm/llvm/tools/llvm-pdbutil/llvm-pdbutil.cpp' l='214'/>
<use f='llvm/llvm/tools/llvm-pdbutil/llvm-pdbutil.cpp' l='217'/>
<use f='llvm/llvm/tools/llvm-pdbutil/llvm-pdbutil.cpp' l='220'/>
<use f='llvm/llvm/tools/llvm-pdbutil/llvm-pdbutil.cpp' l='222'/>
<use f='llvm/llvm/tools/llvm-pdbutil/llvm-pdbutil.cpp' l='224'/>
<use f='llvm/llvm/tools/llvm-pdbutil/llvm-pdbutil.cpp' l='227'/>
<use f='llvm/llvm/tools/llvm-pdbutil/llvm-pdbutil.cpp' l='237'/>
<use f='llvm/llvm/tools/llvm-pdbutil/llvm-pdbutil.cpp' l='239'/>
<use f='llvm/llvm/tools/llvm-pdbutil/llvm-pdbutil.cpp' l='241'/>
<use f='llvm/llvm/tools/llvm-pdbutil/llvm-pdbutil.cpp' l='243'/>
<use f='llvm/llvm/tools/llvm-pdbutil/llvm-pdbutil.cpp' l='245'/>
<use f='llvm/llvm/tools/llvm-pdbutil/llvm-pdbutil.cpp' l='247'/>
<use f='llvm/llvm/tools/llvm-pdbutil/llvm-pdbutil.cpp' l='249'/>
<use f='llvm/llvm/tools/llvm-pdbutil/llvm-pdbutil.cpp' l='251'/>
<use f='llvm/llvm/tools/llvm-pdbutil/llvm-pdbutil.cpp' l='261'/>
<use f='llvm/llvm/tools/llvm-pdbutil/llvm-pdbutil.cpp' l='279'/>
<use f='llvm/llvm/tools/llvm-pdbutil/llvm-pdbutil.cpp' l='292'/>
<use f='llvm/llvm/tools/llvm-pdbutil/llvm-pdbutil.cpp' l='295'/>
<use f='llvm/llvm/tools/llvm-pdbutil/llvm-pdbutil.cpp' l='298'/>
<use f='llvm/llvm/tools/llvm-pdbutil/llvm-pdbutil.cpp' l='301'/>
<use f='llvm/llvm/tools/llvm-pdbutil/llvm-pdbutil.cpp' l='306'/>
<use f='llvm/llvm/tools/llvm-pdbutil/llvm-pdbutil.cpp' l='308'/>
<use f='llvm/llvm/tools/llvm-pdbutil/llvm-pdbutil.cpp' l='312'/>
<use f='llvm/llvm/tools/llvm-pdbutil/llvm-pdbutil.cpp' l='315'/>
<use f='llvm/llvm/tools/llvm-pdbutil/llvm-pdbutil.cpp' l='318'/>
<use f='llvm/llvm/tools/llvm-pdbutil/llvm-pdbutil.cpp' l='321'/>
<use f='llvm/llvm/tools/llvm-pdbutil/llvm-pdbutil.cpp' l='326'/>
<use f='llvm/llvm/tools/llvm-pdbutil/llvm-pdbutil.cpp' l='330'/>
<use f='llvm/llvm/tools/llvm-pdbutil/llvm-pdbutil.cpp' l='334'/>
<use f='llvm/llvm/tools/llvm-pdbutil/llvm-pdbutil.cpp' l='338'/>
<use f='llvm/llvm/tools/llvm-pdbutil/llvm-pdbutil.cpp' l='342'/>
<use f='llvm/llvm/tools/llvm-pdbutil/llvm-pdbutil.cpp' l='348'/>
<use f='llvm/llvm/tools/llvm-pdbutil/llvm-pdbutil.cpp' l='353'/>
<use f='llvm/llvm/tools/llvm-pdbutil/llvm-pdbutil.cpp' l='357'/>
<use f='llvm/llvm/tools/llvm-pdbutil/llvm-pdbutil.cpp' l='361'/>
<use f='llvm/llvm/tools/llvm-pdbutil/llvm-pdbutil.cpp' l='379'/>
<use f='llvm/llvm/tools/llvm-pdbutil/llvm-pdbutil.cpp' l='384'/>
<use f='llvm/llvm/tools/llvm-pdbutil/llvm-pdbutil.cpp' l='390'/>
<use f='llvm/llvm/tools/llvm-pdbutil/llvm-pdbutil.cpp' l='393'/>
<use f='llvm/llvm/tools/llvm-pdbutil/llvm-pdbutil.cpp' l='395'/>
<use f='llvm/llvm/tools/llvm-pdbutil/llvm-pdbutil.cpp' l='398'/>
<use f='llvm/llvm/tools/llvm-pdbutil/llvm-pdbutil.cpp' l='400'/>
<use f='llvm/llvm/tools/llvm-pdbutil/llvm-pdbutil.cpp' l='402'/>
<use f='llvm/llvm/tools/llvm-pdbutil/llvm-pdbutil.cpp' l='404'/>
<use f='llvm/llvm/tools/llvm-pdbutil/llvm-pdbutil.cpp' l='406'/>
<use f='llvm/llvm/tools/llvm-pdbutil/llvm-pdbutil.cpp' l='408'/>
<use f='llvm/llvm/tools/llvm-pdbutil/llvm-pdbutil.cpp' l='413'/>
<use f='llvm/llvm/tools/llvm-pdbutil/llvm-pdbutil.cpp' l='417'/>
<use f='llvm/llvm/tools/llvm-pdbutil/llvm-pdbutil.cpp' l='424'/>
<use f='llvm/llvm/tools/llvm-pdbutil/llvm-pdbutil.cpp' l='426'/>
<use f='llvm/llvm/tools/llvm-pdbutil/llvm-pdbutil.cpp' l='429'/>
<use f='llvm/llvm/tools/llvm-pdbutil/llvm-pdbutil.cpp' l='432'/>
<use f='llvm/llvm/tools/llvm-pdbutil/llvm-pdbutil.cpp' l='437'/>
<use f='llvm/llvm/tools/llvm-pdbutil/llvm-pdbutil.cpp' l='440'/>
<use f='llvm/llvm/tools/llvm-pdbutil/llvm-pdbutil.cpp' l='453'/>
<use f='llvm/llvm/tools/llvm-pdbutil/llvm-pdbutil.cpp' l='456'/>
<use f='llvm/llvm/tools/llvm-pdbutil/llvm-pdbutil.cpp' l='460'/>
<use f='llvm/llvm/tools/llvm-pdbutil/llvm-pdbutil.cpp' l='464'/>
<use f='llvm/llvm/tools/llvm-pdbutil/llvm-pdbutil.cpp' l='468'/>
<use f='llvm/llvm/tools/llvm-pdbutil/llvm-pdbutil.cpp' l='472'/>
<use f='llvm/llvm/tools/llvm-pdbutil/llvm-pdbutil.cpp' l='476'/>
<use f='llvm/llvm/tools/llvm-pdbutil/llvm-pdbutil.cpp' l='481'/>
<use f='llvm/llvm/tools/llvm-pdbutil/llvm-pdbutil.cpp' l='485'/>
<use f='llvm/llvm/tools/llvm-pdbutil/llvm-pdbutil.cpp' l='490'/>
<use f='llvm/llvm/tools/llvm-pdbutil/llvm-pdbutil.cpp' l='494'/>
<use f='llvm/llvm/tools/llvm-pdbutil/llvm-pdbutil.cpp' l='500'/>
<use f='llvm/llvm/tools/llvm-pdbutil/llvm-pdbutil.cpp' l='505'/>
<use f='llvm/llvm/tools/llvm-pdbutil/llvm-pdbutil.cpp' l='509'/>
<use f='llvm/llvm/tools/llvm-pdbutil/llvm-pdbutil.cpp' l='513'/>
<use f='llvm/llvm/tools/llvm-pdbutil/llvm-pdbutil.cpp' l='517'/>
<use f='llvm/llvm/tools/llvm-pdbutil/llvm-pdbutil.cpp' l='521'/>
<use f='llvm/llvm/tools/llvm-pdbutil/llvm-pdbutil.cpp' l='528'/>
<use f='llvm/llvm/tools/llvm-pdbutil/llvm-pdbutil.cpp' l='532'/>
<use f='llvm/llvm/tools/llvm-pdbutil/llvm-pdbutil.cpp' l='534'/>
<use f='llvm/llvm/tools/llvm-pdbutil/llvm-pdbutil.cpp' l='539'/>
<use f='llvm/llvm/tools/llvm-pdbutil/llvm-pdbutil.cpp' l='541'/>
<use f='llvm/llvm/tools/llvm-pdbutil/llvm-pdbutil.cpp' l='544'/>
<use f='llvm/llvm/tools/llvm-pdbutil/llvm-pdbutil.cpp' l='548'/>
<use f='llvm/llvm/tools/llvm-pdbutil/llvm-pdbutil.cpp' l='550'/>
<use f='llvm/llvm/tools/llvm-pdbutil/llvm-pdbutil.cpp' l='555'/>
<use f='llvm/llvm/tools/llvm-pdbutil/llvm-pdbutil.cpp' l='558'/>
<use f='llvm/llvm/tools/llvm-pdbutil/llvm-pdbutil.cpp' l='562'/>
<use f='llvm/llvm/tools/llvm-pdbutil/llvm-pdbutil.cpp' l='566'/>
<use f='llvm/llvm/tools/llvm-pdbutil/llvm-pdbutil.cpp' l='570'/>
<use f='llvm/llvm/tools/llvm-pdbutil/llvm-pdbutil.cpp' l='574'/>
<use f='llvm/llvm/tools/llvm-pdbutil/llvm-pdbutil.cpp' l='579'/>
<use f='llvm/llvm/tools/llvm-pdbutil/llvm-pdbutil.cpp' l='584'/>
<use f='llvm/llvm/tools/llvm-pdbutil/llvm-pdbutil.cpp' l='588'/>
<use f='llvm/llvm/tools/llvm-pdbutil/llvm-pdbutil.cpp' l='592'/>
<use f='llvm/llvm/tools/llvm-pdbutil/llvm-pdbutil.cpp' l='597'/>
<use f='llvm/llvm/tools/llvm-pdbutil/llvm-pdbutil.cpp' l='600'/>
<use f='llvm/llvm/tools/llvm-pdbutil/llvm-pdbutil.cpp' l='604'/>
<use f='llvm/llvm/tools/llvm-pdbutil/llvm-pdbutil.cpp' l='609'/>
<use f='llvm/llvm/tools/llvm-pdbutil/llvm-pdbutil.cpp' l='611'/>
<use f='llvm/llvm/tools/llvm-pdbutil/llvm-pdbutil.cpp' l='614'/>
<use f='llvm/llvm/tools/llvm-pdbutil/llvm-pdbutil.cpp' l='617'/>
<use f='llvm/llvm/tools/llvm-pdbutil/llvm-pdbutil.cpp' l='621'/>
<use f='llvm/llvm/tools/llvm-pdbutil/llvm-pdbutil.cpp' l='627'/>
<use f='llvm/llvm/tools/llvm-pdbutil/llvm-pdbutil.cpp' l='631'/>
<use f='llvm/llvm/tools/llvm-pdbutil/llvm-pdbutil.cpp' l='637'/>
<use f='llvm/llvm/tools/llvm-pdbutil/llvm-pdbutil.cpp' l='640'/>
<use f='llvm/llvm/tools/llvm-pdbutil/llvm-pdbutil.cpp' l='643'/>
<use f='llvm/llvm/tools/llvm-pdbutil/llvm-pdbutil.cpp' l='648'/>
<use f='llvm/llvm/tools/llvm-pdbutil/llvm-pdbutil.cpp' l='652'/>
<use f='llvm/llvm/tools/llvm-pdbutil/llvm-pdbutil.cpp' l='655'/>
<use f='llvm/llvm/tools/llvm-pdbutil/llvm-pdbutil.cpp' l='658'/>
<use f='llvm/llvm/tools/llvm-pdbutil/llvm-pdbutil.cpp' l='662'/>
<use f='llvm/llvm/tools/llvm-pdbutil/llvm-pdbutil.cpp' l='666'/>
<use f='llvm/llvm/tools/llvm-pdbutil/llvm-pdbutil.cpp' l='670'/>
<use f='llvm/llvm/tools/llvm-pdbutil/llvm-pdbutil.cpp' l='674'/>
<use f='llvm/llvm/tools/llvm-pdbutil/llvm-pdbutil.cpp' l='678'/>
<use f='llvm/llvm/tools/llvm-pdbutil/llvm-pdbutil.cpp' l='681'/>
<use f='llvm/llvm/tools/llvm-pdbutil/llvm-pdbutil.cpp' l='685'/>
<use f='llvm/llvm/tools/llvm-pdbutil/llvm-pdbutil.cpp' l='688'/>
<use f='llvm/llvm/tools/llvm-pdbutil/llvm-pdbutil.cpp' l='692'/>
<use f='llvm/llvm/tools/llvm-pdbutil/llvm-pdbutil.cpp' l='698'/>
<use f='llvm/llvm/tools/llvm-pdbutil/llvm-pdbutil.cpp' l='701'/>
<use f='llvm/llvm/tools/llvm-pdbutil/llvm-pdbutil.cpp' l='707'/>
<use f='llvm/llvm/tools/llvm-pdbutil/llvm-pdbutil.cpp' l='710'/>
<use f='llvm/llvm/tools/llvm-pdbutil/llvm-pdbutil.cpp' l='714'/>
<use f='llvm/llvm/tools/llvm-pdbutil/llvm-pdbutil.cpp' l='730'/>
<use f='llvm/llvm/tools/llvm-pdbutil/llvm-pdbutil.cpp' l='733'/>
<use f='llvm/llvm/tools/llvm-pdbutil/llvm-pdbutil.cpp' l='737'/>
<use f='llvm/llvm/tools/llvm-pdbutil/llvm-pdbutil.cpp' l='741'/>
<size>8</size>
<use f='llvm/llvm/tools/llvm-xray/xray-account.cpp' l='32'/>
<use f='llvm/llvm/tools/llvm-xray/xray-account.cpp' l='35'/>
<use f='llvm/llvm/tools/llvm-xray/xray-account.cpp' l='40'/>
<use f='llvm/llvm/tools/llvm-xray/xray-account.cpp' l='44'/>
<use f='llvm/llvm/tools/llvm-xray/xray-account.cpp' l='51'/>
<use f='llvm/llvm/tools/llvm-xray/xray-account.cpp' l='61'/>
<use f='llvm/llvm/tools/llvm-xray/xray-account.cpp' l='79'/>
<use f='llvm/llvm/tools/llvm-xray/xray-account.cpp' l='100'/>
<use f='llvm/llvm/tools/llvm-xray/xray-account.cpp' l='105'/>
<use f='llvm/llvm/tools/llvm-xray/xray-account.cpp' l='115'/>
<size>8</size>
<use f='llvm/llvm/tools/llvm-xray/xray-converter.cpp' l='35'/>
<use f='llvm/llvm/tools/llvm-xray/xray-converter.cpp' l='44'/>
<use f='llvm/llvm/tools/llvm-xray/xray-converter.cpp' l='50'/>
<use f='llvm/llvm/tools/llvm-xray/xray-converter.cpp' l='57'/>
<use f='llvm/llvm/tools/llvm-xray/xray-converter.cpp' l='66'/>
<use f='llvm/llvm/tools/llvm-xray/xray-converter.cpp' l='72'/>
<size>8</size>
<use f='llvm/llvm/tools/llvm-xray/xray-extract.cpp' l='35'/>
<use f='llvm/llvm/tools/llvm-xray/xray-extract.cpp' l='39'/>
<use f='llvm/llvm/tools/llvm-xray/xray-extract.cpp' l='45'/>
<use f='llvm/llvm/tools/llvm-xray/xray-extract.cpp' l='52'/>
<size>8</size>
<use f='llvm/llvm/tools/llvm-xray/xray-fdr-dump.cpp' l='31'/>
<use f='llvm/llvm/tools/llvm-xray/xray-fdr-dump.cpp' l='34'/>
<size>8</size>
<use f='llvm/llvm/tools/llvm-xray/xray-graph-diff.cpp' l='34'/>
<use f='llvm/llvm/tools/llvm-xray/xray-graph-diff.cpp' l='37'/>
<use f='llvm/llvm/tools/llvm-xray/xray-graph-diff.cpp' l='42'/>
<use f='llvm/llvm/tools/llvm-xray/xray-graph-diff.cpp' l='48'/>
<use f='llvm/llvm/tools/llvm-xray/xray-graph-diff.cpp' l='54'/>
<use f='llvm/llvm/tools/llvm-xray/xray-graph-diff.cpp' l='63'/>
<use f='llvm/llvm/tools/llvm-xray/xray-graph-diff.cpp' l='71'/>
<use f='llvm/llvm/tools/llvm-xray/xray-graph-diff.cpp' l='79'/>
<use f='llvm/llvm/tools/llvm-xray/xray-graph-diff.cpp' l='86'/>
<use f='llvm/llvm/tools/llvm-xray/xray-graph-diff.cpp' l='93'/>
<use f='llvm/llvm/tools/llvm-xray/xray-graph-diff.cpp' l='100'/>
<use f='llvm/llvm/tools/llvm-xray/xray-graph-diff.cpp' l='107'/>
<use f='llvm/llvm/tools/llvm-xray/xray-graph-diff.cpp' l='130'/>
<use f='llvm/llvm/tools/llvm-xray/xray-graph-diff.cpp' l='154'/>
<use f='llvm/llvm/tools/llvm-xray/xray-graph-diff.cpp' l='178'/>
<use f='llvm/llvm/tools/llvm-xray/xray-graph-diff.cpp' l='201'/>
<use f='llvm/llvm/tools/llvm-xray/xray-graph-diff.cpp' l='209'/>
<size>8</size>
<use f='llvm/llvm/tools/llvm-xray/xray-graph.cpp' l='27'/>
<use f='llvm/llvm/tools/llvm-xray/xray-graph.cpp' l='31'/>
<use f='llvm/llvm/tools/llvm-xray/xray-graph.cpp' l='37'/>
<use f='llvm/llvm/tools/llvm-xray/xray-graph.cpp' l='45'/>
<use f='llvm/llvm/tools/llvm-xray/xray-graph.cpp' l='53'/>
<use f='llvm/llvm/tools/llvm-xray/xray-graph.cpp' l='61'/>
<use f='llvm/llvm/tools/llvm-xray/xray-graph.cpp' l='85'/>
<use f='llvm/llvm/tools/llvm-xray/xray-graph.cpp' l='109'/>
<use f='llvm/llvm/tools/llvm-xray/xray-graph.cpp' l='133'/>
<size>8</size>
<use f='llvm/llvm/tools/llvm-xray/xray-stacks.cpp' l='39'/>
<use f='llvm/llvm/tools/llvm-xray/xray-stacks.cpp' l='43'/>
<use f='llvm/llvm/tools/llvm-xray/xray-stacks.cpp' l='53'/>
<use f='llvm/llvm/tools/llvm-xray/xray-stacks.cpp' l='60'/>
<use f='llvm/llvm/tools/llvm-xray/xray-stacks.cpp' l='65'/>
<use f='llvm/llvm/tools/llvm-xray/xray-stacks.cpp' l='71'/>
<use f='llvm/llvm/tools/llvm-xray/xray-stacks.cpp' l='89'/>
<use f='llvm/llvm/tools/llvm-xray/xray-stacks.cpp' l='108'/>
<size>8</size>
<use f='llvm/llvm/unittests/Support/CommandLineTest.cpp' l='431' c='_ZN12_GLOBAL__N_144CommandLineTest_SetValueInSubcategories_Test8TestBodyEv'/>
<use f='llvm/llvm/unittests/Support/CommandLineTest.cpp' l='432' c='_ZN12_GLOBAL__N_144CommandLineTest_SetValueInSubcategories_Test8TestBodyEv'/>
<use f='llvm/llvm/unittests/Support/CommandLineTest.cpp' l='477' c='_ZN12_GLOBAL__N_149CommandLineTest_LookupFailsInWrongSubCommand_Test8TestBodyEv'/>
<use f='llvm/llvm/unittests/Support/CommandLineTest.cpp' l='478' c='_ZN12_GLOBAL__N_149CommandLineTest_LookupFailsInWrongSubCommand_Test8TestBodyEv'/>
<use f='llvm/llvm/unittests/Support/CommandLineTest.cpp' l='493' c='_ZN12_GLOBAL__N_140CommandLineTest_AddToAllSubCommands_Test8TestBodyEv'/>
<use f='llvm/llvm/unittests/Support/CommandLineTest.cpp' l='530' c='_ZN12_GLOBAL__N_146CommandLineTest_ReparseCommandLineOptions_Test8TestBodyEv'/>
<use f='llvm/llvm/unittests/Support/CommandLineTest.cpp' l='553' c='_ZN12_GLOBAL__N_148CommandLineTest_RemoveFromRegularSubCommand_Test8TestBodyEv'/>
<use f='llvm/llvm/unittests/Support/CommandLineTest.cpp' l='554' c='_ZN12_GLOBAL__N_148CommandLineTest_RemoveFromRegularSubCommand_Test8TestBodyEv'/>
<use f='llvm/llvm/unittests/Support/CommandLineTest.cpp' l='579' c='_ZN12_GLOBAL__N_149CommandLineTest_RemoveFromTopLevelSubCommand_Test8TestBodyEv'/>
<use f='llvm/llvm/unittests/Support/CommandLineTest.cpp' l='581' c='_ZN12_GLOBAL__N_149CommandLineTest_RemoveFromTopLevelSubCommand_Test8TestBodyEv'/>
<use f='llvm/llvm/unittests/Support/CommandLineTest.cpp' l='602' c='_ZN12_GLOBAL__N_145CommandLineTest_RemoveFromAllSubCommands_Test8TestBodyEv'/>
<use f='llvm/llvm/unittests/Support/CommandLineTest.cpp' l='604' c='_ZN12_GLOBAL__N_145CommandLineTest_RemoveFromAllSubCommands_Test8TestBodyEv'/>
<use f='llvm/llvm/unittests/Support/CommandLineTest.cpp' l='651' c='_ZN12_GLOBAL__N_145CommandLineTest_GetRegisteredSubcommands_Test8TestBodyEv'/>
<use f='llvm/llvm/unittests/Support/CommandLineTest.cpp' l='653' c='_ZN12_GLOBAL__N_145CommandLineTest_GetRegisteredSubcommands_Test8TestBodyEv'/>
<use f='llvm/llvm/unittests/Support/CommandLineTest.cpp' l='683' c='_ZN12_GLOBAL__N_135CommandLineTest_DefaultOptions_Test8TestBodyEv'/>
<use f='llvm/llvm/unittests/Support/CommandLineTest.cpp' l='688' c='_ZN12_GLOBAL__N_135CommandLineTest_DefaultOptions_Test8TestBodyEv'/>
<use f='llvm/llvm/unittests/Support/CommandLineTest.cpp' l='695' c='_ZN12_GLOBAL__N_135CommandLineTest_DefaultOptions_Test8TestBodyEv'/>
<use f='llvm/llvm/unittests/Support/CommandLineTest.cpp' l='699' c='_ZN12_GLOBAL__N_135CommandLineTest_DefaultOptions_Test8TestBodyEv'/>
<size>8</size>
