<dec f='llvm/llvm/include/llvm/Analysis/StackLifetime.h' l='188' type='llvm::raw_ostream &amp;'/>
<use f='llvm/llvm/include/llvm/Analysis/StackLifetime.h' l='192' u='w' c='_ZN4llvm24StackLifetimePrinterPassC1ERNS_11raw_ostreamENS_13StackLifetime12LivenessTypeE'/>
<use f='llvm/llvm/lib/Analysis/StackLifetime.cpp' l='400' u='a' c='_ZN4llvm24StackLifetimePrinterPass3runERNS_8FunctionERNS_15AnalysisManagerIS1_JEEE'/>
<offset>64</offset>
