<dec f='llvm/llvm/include/llvm/Support/WithColor.h' l='54' type='llvm::raw_ostream &amp;'/>
<use f='llvm/llvm/include/llvm/Support/WithColor.h' l='75' u='w' c='_ZN4llvm9WithColorC1ERNS_11raw_ostreamENS1_6ColorsEbbNS_9ColorModeE'/>
<use f='llvm/llvm/include/llvm/Support/WithColor.h' l='80' u='a' c='_ZN4llvm9WithColor3getEv'/>
<use f='llvm/llvm/include/llvm/Support/WithColor.h' l='81' u='a' c='_ZN4llvm9WithColorcvRNS_11raw_ostreamEEv'/>
<use f='llvm/llvm/include/llvm/Support/WithColor.h' l='83' c='_ZN4llvm9WithColorlsERT_'/>
<use f='llvm/llvm/include/llvm/Support/WithColor.h' l='87' c='_ZN4llvm9WithColorlsERKT_'/>
<offset>0</offset>
<use f='llvm/llvm/lib/Support/WithColor.cpp' l='22' u='w' c='_ZN4llvm9WithColorC1ERNS_11raw_ostreamENS_14HighlightColorENS_9ColorModeE'/>
<use f='llvm/llvm/lib/Support/WithColor.cpp' l='115' u='m' c='_ZN4llvm9WithColor13colorsEnabledEv'/>
<use f='llvm/llvm/lib/Support/WithColor.cpp' l='124' u='m' c='_ZN4llvm9WithColor11changeColorENS_11raw_ostream6ColorsEbb'/>
<use f='llvm/llvm/lib/Support/WithColor.cpp' l='130' u='m' c='_ZN4llvm9WithColor10resetColorEv'/>
