<dec f='llvm/build/lib/Target/X86/X86GenRegisterInfo.inc' l='32' type='12'/>
<use f='llvm/llvm/lib/Target/X86/MCTargetDesc/X86BaseInfo.h' l='382' c='_ZN4llvm3X8630getSegmentOverridePrefixForRegEj'/>
<use f='llvm/build/lib/Target/X86/X86GenAsmMatcher.inc' l='7425' c='_ZL20validateOperandClassRN4llvm18MCParsedAsmOperandEN12_GLOBAL__N_114MatchClassKindE'/>
<use f='llvm/llvm/lib/Target/X86/Disassembler/X86Disassembler.cpp' l='1773' macro='1' u='r' c='_ZL17translateRegisterRN4llvm6MCInstENS_15X86Disassembler3RegE'/>
<use f='llvm/llvm/lib/Target/X86/Disassembler/X86Disassembler.cpp' l='1822'/>
<use f='llvm/llvm/lib/Target/X86/Disassembler/X86Disassembler.cpp' l='2010' macro='1' u='r' c='_ZL19translateRMRegisterRN4llvm6MCInstERNS_15X86Disassembler19InternalInstructionE'/>
<use f='llvm/llvm/lib/Target/X86/X86MCInstLower.cpp' l='1171' u='r' c='_ZL7emitNopRN4llvm10MCStreamerEjPKNS_12X86SubtargetE'/>
<use f='llvm/llvm/lib/Target/X86/X86RegisterInfo.cpp' l='560' u='r' c='_ZNK4llvm15X86RegisterInfo15getReservedRegsERKNS_15MachineFunctionE'/>
