<dec f='llvm/llvm/include/llvm/Support/ELFAttributeParser.h' l='31' type='llvm::ScopedPrinter *'/>
<use f='llvm/llvm/include/llvm/Support/ELFAttributeParser.h' l='50' u='w' c='_ZN4llvm18ELFAttributeParserC1EPNS_13ScopedPrinterENS_8ArrayRefINS_11TagNameItemEEENS_9StringRefE'/>
<use f='llvm/llvm/include/llvm/Support/ELFAttributeParser.h' l='53' u='w' c='_ZN4llvm18ELFAttributeParserC1ENS_8ArrayRefINS_11TagNameItemEEENS_9StringRefE'/>
<offset>1088</offset>
<use f='llvm/llvm/lib/Support/ARMAttributeParser.cpp' l='72' u='r' c='_ZN4llvm18ARMAttributeParser15stringAttributeENS_13ARMBuildAttrs8AttrTypeE'/>
<use f='llvm/llvm/lib/Support/ARMAttributeParser.cpp' l='73' u='r' c='_ZN4llvm18ARMAttributeParser15stringAttributeENS_13ARMBuildAttrs8AttrTypeE'/>
<use f='llvm/llvm/lib/Support/ARMAttributeParser.cpp' l='74' u='r' c='_ZN4llvm18ARMAttributeParser15stringAttributeENS_13ARMBuildAttrs8AttrTypeE'/>
<use f='llvm/llvm/lib/Support/ARMAttributeParser.cpp' l='76' u='r' c='_ZN4llvm18ARMAttributeParser15stringAttributeENS_13ARMBuildAttrs8AttrTypeE'/>
<use f='llvm/llvm/lib/Support/ARMAttributeParser.cpp' l='77' u='r' c='_ZN4llvm18ARMAttributeParser15stringAttributeENS_13ARMBuildAttrs8AttrTypeE'/>
<use f='llvm/llvm/lib/Support/ARMAttributeParser.cpp' l='287' u='r' c='_ZN4llvm18ARMAttributeParser13compatibilityENS_13ARMBuildAttrs8AttrTypeE'/>
<use f='llvm/llvm/lib/Support/ARMAttributeParser.cpp' l='288' u='r' c='_ZN4llvm18ARMAttributeParser13compatibilityENS_13ARMBuildAttrs8AttrTypeE'/>
<use f='llvm/llvm/lib/Support/ARMAttributeParser.cpp' l='289' u='r' c='_ZN4llvm18ARMAttributeParser13compatibilityENS_13ARMBuildAttrs8AttrTypeE'/>
<use f='llvm/llvm/lib/Support/ARMAttributeParser.cpp' l='290' u='r' c='_ZN4llvm18ARMAttributeParser13compatibilityENS_13ARMBuildAttrs8AttrTypeE'/>
<use f='llvm/llvm/lib/Support/ARMAttributeParser.cpp' l='291' u='r' c='_ZN4llvm18ARMAttributeParser13compatibilityENS_13ARMBuildAttrs8AttrTypeE'/>
<use f='llvm/llvm/lib/Support/ARMAttributeParser.cpp' l='296' u='r' c='_ZN4llvm18ARMAttributeParser13compatibilityENS_13ARMBuildAttrs8AttrTypeE'/>
<use f='llvm/llvm/lib/Support/ARMAttributeParser.cpp' l='299' u='r' c='_ZN4llvm18ARMAttributeParser13compatibilityENS_13ARMBuildAttrs8AttrTypeE'/>
<use f='llvm/llvm/lib/Support/ARMAttributeParser.cpp' l='302' u='r' c='_ZN4llvm18ARMAttributeParser13compatibilityENS_13ARMBuildAttrs8AttrTypeE'/>
<use f='llvm/llvm/lib/Support/ELFAttributeParser.cpp' l='44' u='r' c='_ZN4llvm18ELFAttributeParser16integerAttributeEj'/>
<use f='llvm/llvm/lib/Support/ELFAttributeParser.cpp' l='45' u='r' c='_ZN4llvm18ELFAttributeParser16integerAttributeEj'/>
<use f='llvm/llvm/lib/Support/ELFAttributeParser.cpp' l='46' u='r' c='_ZN4llvm18ELFAttributeParser16integerAttributeEj'/>
<use f='llvm/llvm/lib/Support/ELFAttributeParser.cpp' l='48' u='r' c='_ZN4llvm18ELFAttributeParser16integerAttributeEj'/>
<use f='llvm/llvm/lib/Support/ELFAttributeParser.cpp' l='49' u='r' c='_ZN4llvm18ELFAttributeParser16integerAttributeEj'/>
<use f='llvm/llvm/lib/Support/ELFAttributeParser.cpp' l='60' u='r' c='_ZN4llvm18ELFAttributeParser15stringAttributeEj'/>
<use f='llvm/llvm/lib/Support/ELFAttributeParser.cpp' l='61' u='r' c='_ZN4llvm18ELFAttributeParser15stringAttributeEj'/>
<use f='llvm/llvm/lib/Support/ELFAttributeParser.cpp' l='62' u='r' c='_ZN4llvm18ELFAttributeParser15stringAttributeEj'/>
<use f='llvm/llvm/lib/Support/ELFAttributeParser.cpp' l='64' u='r' c='_ZN4llvm18ELFAttributeParser15stringAttributeEj'/>
<use f='llvm/llvm/lib/Support/ELFAttributeParser.cpp' l='65' u='r' c='_ZN4llvm18ELFAttributeParser15stringAttributeEj'/>
<use f='llvm/llvm/lib/Support/ELFAttributeParser.cpp' l='74' u='r' c='_ZN4llvm18ELFAttributeParser14printAttributeEjjNS_9StringRefE'/>
<use f='llvm/llvm/lib/Support/ELFAttributeParser.cpp' l='77' u='r' c='_ZN4llvm18ELFAttributeParser14printAttributeEjjNS_9StringRefE'/>
<use f='llvm/llvm/lib/Support/ELFAttributeParser.cpp' l='78' u='r' c='_ZN4llvm18ELFAttributeParser14printAttributeEjjNS_9StringRefE'/>
<use f='llvm/llvm/lib/Support/ELFAttributeParser.cpp' l='79' u='r' c='_ZN4llvm18ELFAttributeParser14printAttributeEjjNS_9StringRefE'/>
<use f='llvm/llvm/lib/Support/ELFAttributeParser.cpp' l='81' u='r' c='_ZN4llvm18ELFAttributeParser14printAttributeEjjNS_9StringRefE'/>
<use f='llvm/llvm/lib/Support/ELFAttributeParser.cpp' l='83' u='r' c='_ZN4llvm18ELFAttributeParser14printAttributeEjjNS_9StringRefE'/>
<use f='llvm/llvm/lib/Support/ELFAttributeParser.cpp' l='127' u='r' c='_ZN4llvm18ELFAttributeParser15parseSubsectionEj'/>
<use f='llvm/llvm/lib/Support/ELFAttributeParser.cpp' l='128' u='r' c='_ZN4llvm18ELFAttributeParser15parseSubsectionEj'/>
<use f='llvm/llvm/lib/Support/ELFAttributeParser.cpp' l='129' u='r' c='_ZN4llvm18ELFAttributeParser15parseSubsectionEj'/>
<use f='llvm/llvm/lib/Support/ELFAttributeParser.cpp' l='144' u='r' c='_ZN4llvm18ELFAttributeParser15parseSubsectionEj'/>
<use f='llvm/llvm/lib/Support/ELFAttributeParser.cpp' l='145' u='r' c='_ZN4llvm18ELFAttributeParser15parseSubsectionEj'/>
<use f='llvm/llvm/lib/Support/ELFAttributeParser.cpp' l='146' u='r' c='_ZN4llvm18ELFAttributeParser15parseSubsectionEj'/>
<use f='llvm/llvm/lib/Support/ELFAttributeParser.cpp' l='177' u='r' c='_ZN4llvm18ELFAttributeParser15parseSubsectionEj'/>
<use f='llvm/llvm/lib/Support/ELFAttributeParser.cpp' l='178' u='r' c='_ZN4llvm18ELFAttributeParser15parseSubsectionEj'/>
<use f='llvm/llvm/lib/Support/ELFAttributeParser.cpp' l='180' u='r' c='_ZN4llvm18ELFAttributeParser15parseSubsectionEj'/>
<use f='llvm/llvm/lib/Support/ELFAttributeParser.cpp' l='213' u='r' c='_ZN4llvm18ELFAttributeParser5parseENS_8ArrayRefIhEENS_7support10endiannessE'/>
<use f='llvm/llvm/lib/Support/ELFAttributeParser.cpp' l='214' u='r' c='_ZN4llvm18ELFAttributeParser5parseENS_8ArrayRefIhEENS_7support10endiannessE'/>
<use f='llvm/llvm/lib/Support/ELFAttributeParser.cpp' l='215' u='r' c='_ZN4llvm18ELFAttributeParser5parseENS_8ArrayRefIhEENS_7support10endiannessE'/>
<use f='llvm/llvm/lib/Support/ELFAttributeParser.cpp' l='226' u='r' c='_ZN4llvm18ELFAttributeParser5parseENS_8ArrayRefIhEENS_7support10endiannessE'/>
<use f='llvm/llvm/lib/Support/ELFAttributeParser.cpp' l='227' u='r' c='_ZN4llvm18ELFAttributeParser5parseENS_8ArrayRefIhEENS_7support10endiannessE'/>
<use f='llvm/llvm/lib/Support/ELFAttributeParser.cpp' l='228' u='r' c='_ZN4llvm18ELFAttributeParser5parseENS_8ArrayRefIhEENS_7support10endiannessE'/>
