<use f='llvm/llvm/include/llvm/Analysis/CallGraph.h' l='185' u='w' c='_ZN4llvm13CallGraphNodeC1EPNS_9CallGraphEPNS_8FunctionE'/>
<dec f='llvm/llvm/include/llvm/Analysis/CallGraph.h' l='284' type='llvm::CallGraph *'/>
<offset>0</offset>
<use f='llvm/llvm/lib/Analysis/CallGraph.cpp' l='50' u='w' c='_ZN4llvm9CallGraphC1EOS0_'/>
<use f='llvm/llvm/lib/Analysis/CallGraph.cpp' l='52' u='w' c='_ZN4llvm9CallGraphC1EOS0_'/>
<use f='llvm/llvm/lib/Analysis/CallGraph.cpp' l='222' u='r' c='_ZN4llvm13CallGraphNode17removeCallEdgeForERNS_8CallBaseE'/>
<use f='llvm/llvm/lib/Analysis/CallGraph.cpp' l='275' u='r' c='_ZN4llvm13CallGraphNode15replaceCallEdgeERNS_8CallBaseES2_PS0_'/>
<use f='llvm/llvm/lib/Analysis/CallGraph.cpp' l='278' u='r' c='_ZN4llvm13CallGraphNode15replaceCallEdgeERNS_8CallBaseES2_PS0_'/>
