<dec f='llvm/llvm/include/llvm/Analysis/AliasSetTracker.h' l='465' type='llvm::raw_ostream &amp;'/>
<offset>0</offset>
<use f='llvm/llvm/lib/Analysis/AliasSetTracker.cpp' l='775' u='w' c='_ZN4llvm20AliasSetsPrinterPassC1ERNS_11raw_ostreamE'/>
<use f='llvm/llvm/lib/Analysis/AliasSetTracker.cpp' l='781' u='m' c='_ZN4llvm20AliasSetsPrinterPass3runERNS_8FunctionERNS_15AnalysisManagerIS1_JEEE'/>
<use f='llvm/llvm/lib/Analysis/AliasSetTracker.cpp' l='784' u='a' c='_ZN4llvm20AliasSetsPrinterPass3runERNS_8FunctionERNS_15AnalysisManagerIS1_JEEE'/>
