<use f='llvm/llvm/unittests/ExecutionEngine/Orc/OrcTestCommon.h' l='145' u='m' c='_ZN4llvm16OrcExecutionTestC1Ev'/>
<use f='llvm/llvm/unittests/ExecutionEngine/Orc/OrcTestCommon.h' l='147' u='m' c='_ZN4llvm16OrcExecutionTestC1Ev'/>
<use f='llvm/llvm/unittests/ExecutionEngine/Orc/OrcTestCommon.h' l='149' u='m' c='_ZN4llvm16OrcExecutionTestC1Ev'/>
<use f='llvm/llvm/unittests/ExecutionEngine/Orc/OrcTestCommon.h' l='157' u='m' c='_ZN4llvm16OrcExecutionTestC1Ev'/>
<dec f='llvm/llvm/unittests/ExecutionEngine/Orc/OrcTestCommon.h' l='173' type='std::unique_ptr&lt;TargetMachine&gt;'/>
<offset>2048</offset>
