<dec f='llvm/llvm/include/llvm/CodeGen/GlobalISel/IRTranslator.h' l='609' type='std::unique_ptr&lt;GISelSwitchLowering&gt;'/>
<use f='llvm/llvm/lib/CodeGen/GlobalISel/IRTranslator.cpp' l='392' u='m' c='_ZN4llvm12IRTranslator28emitBranchForMergedConditionEPKNS_5ValueEPNS_17MachineBasicBlockES5_S5_S5_NS_17BranchProbabilityES6_b'/>
<use f='llvm/llvm/lib/CodeGen/GlobalISel/IRTranslator.cpp' l='401' u='m' c='_ZN4llvm12IRTranslator28emitBranchForMergedConditionEPKNS_5ValueEPNS_17MachineBasicBlockES5_S5_S5_NS_17BranchProbabilityES6_b'/>
<use f='llvm/llvm/lib/CodeGen/GlobalISel/IRTranslator.cpp' l='629' u='m' c='_ZN4llvm12IRTranslator11translateBrERKNS_4UserERNS_16MachineIRBuilderE'/>
<use f='llvm/llvm/lib/CodeGen/GlobalISel/IRTranslator.cpp' l='631' u='m' c='_ZN4llvm12IRTranslator11translateBrERKNS_4UserERNS_16MachineIRBuilderE'/>
<use f='llvm/llvm/lib/CodeGen/GlobalISel/IRTranslator.cpp' l='632' u='m' c='_ZN4llvm12IRTranslator11translateBrERKNS_4UserERNS_16MachineIRBuilderE'/>
<use f='llvm/llvm/lib/CodeGen/GlobalISel/IRTranslator.cpp' l='632' u='m' c='_ZN4llvm12IRTranslator11translateBrERKNS_4UserERNS_16MachineIRBuilderE'/>
<use f='llvm/llvm/lib/CodeGen/GlobalISel/IRTranslator.cpp' l='638' u='m' c='_ZN4llvm12IRTranslator11translateBrERKNS_4UserERNS_16MachineIRBuilderE'/>
<use f='llvm/llvm/lib/CodeGen/GlobalISel/IRTranslator.cpp' l='639' u='m' c='_ZN4llvm12IRTranslator11translateBrERKNS_4UserERNS_16MachineIRBuilderE'/>
<use f='llvm/llvm/lib/CodeGen/GlobalISel/IRTranslator.cpp' l='641' u='m' c='_ZN4llvm12IRTranslator11translateBrERKNS_4UserERNS_16MachineIRBuilderE'/>
<use f='llvm/llvm/lib/CodeGen/GlobalISel/IRTranslator.cpp' l='717' u='m' c='_ZN4llvm12IRTranslator15translateSwitchERKNS_4UserERNS_16MachineIRBuilderE'/>
<use f='llvm/llvm/lib/CodeGen/GlobalISel/IRTranslator.cpp' l='718' u='m' c='_ZN4llvm12IRTranslator15translateSwitchERKNS_4UserERNS_16MachineIRBuilderE'/>
<use f='llvm/llvm/lib/CodeGen/GlobalISel/IRTranslator.cpp' l='909' u='m' c='_ZN4llvm12IRTranslator22lowerJumpTableWorkItemENS_8SwitchCG18SwitchWorkListItemEPNS_17MachineBasicBlockES4_S4_RNS_16MachineIRBuilderENS_14ilist_iterat151306'/>
<use f='llvm/llvm/lib/CodeGen/GlobalISel/IRTranslator.cpp' l='910' u='m' c='_ZN4llvm12IRTranslator22lowerJumpTableWorkItemENS_8SwitchCG18SwitchWorkListItemEPNS_17MachineBasicBlockES4_S4_RNS_16MachineIRBuilderENS_14ilist_iterat151306'/>
<use f='llvm/llvm/lib/CodeGen/GlobalISel/IRTranslator.cpp' l='1121' u='m' c='_ZN4llvm12IRTranslator20lowerBitTestWorkItemENS_8SwitchCG18SwitchWorkListItemEPNS_17MachineBasicBlockES4_S4_RNS_16MachineIRBuilderENS_14ilist_iterator16708573'/>
<use f='llvm/llvm/lib/CodeGen/GlobalISel/IRTranslator.cpp' l='2938' u='m' c='_ZN4llvm12IRTranslator18finalizeBasicBlockEv'/>
<use f='llvm/llvm/lib/CodeGen/GlobalISel/IRTranslator.cpp' l='2987' u='m' c='_ZN4llvm12IRTranslator18finalizeBasicBlockEv'/>
<use f='llvm/llvm/lib/CodeGen/GlobalISel/IRTranslator.cpp' l='2989' u='m' c='_ZN4llvm12IRTranslator18finalizeBasicBlockEv'/>
<use f='llvm/llvm/lib/CodeGen/GlobalISel/IRTranslator.cpp' l='2996' u='m' c='_ZN4llvm12IRTranslator18finalizeBasicBlockEv'/>
<use f='llvm/llvm/lib/CodeGen/GlobalISel/IRTranslator.cpp' l='2998' u='m' c='_ZN4llvm12IRTranslator18finalizeBasicBlockEv'/>
<use f='llvm/llvm/lib/CodeGen/GlobalISel/IRTranslator.cpp' l='3000' u='m' c='_ZN4llvm12IRTranslator18finalizeBasicBlockEv'/>
<use f='llvm/llvm/lib/CodeGen/GlobalISel/IRTranslator.cpp' l='3075' u='w' c='_ZN4llvm12IRTranslator20runOnMachineFunctionERNS_15MachineFunctionE'/>
<use f='llvm/llvm/lib/CodeGen/GlobalISel/IRTranslator.cpp' l='3076' u='m' c='_ZN4llvm12IRTranslator20runOnMachineFunctionERNS_15MachineFunctionE'/>
<offset>12608</offset>
