<dec f='llvm/build/lib/Target/MSP430/MSP430GenRegisterInfo.inc' l='25' type='5'/>
<use f='llvm/build/lib/Target/MSP430/MSP430GenAsmMatcher.inc' l='577' c='_ZL20validateOperandClassRN4llvm18MCParsedAsmOperandEN12_GLOBAL__N_114MatchClassKindE'/>
<use f='llvm/llvm/lib/Target/MSP430/AsmParser/MSP430AsmParser.cpp' l='561' c='_ZL16convertGR16ToGR8j'/>
<use f='llvm/llvm/lib/Target/MSP430/Disassembler/MSP430Disassembler.cpp' l='85'/>
<use f='llvm/llvm/lib/Target/MSP430/MSP430FrameLowering.cpp' l='71' u='r' c='_ZNK4llvm19MSP430FrameLowering12emitPrologueERNS_15MachineFunctionERNS_17MachineBasicBlockE'/>
<use f='llvm/llvm/lib/Target/MSP430/MSP430FrameLowering.cpp' l='98' u='r' c='_ZNK4llvm19MSP430FrameLowering12emitPrologueERNS_15MachineFunctionERNS_17MachineBasicBlockE'/>
<use f='llvm/llvm/lib/Target/MSP430/MSP430FrameLowering.cpp' l='99' u='r' c='_ZNK4llvm19MSP430FrameLowering12emitPrologueERNS_15MachineFunctionERNS_17MachineBasicBlockE'/>
<use f='llvm/llvm/lib/Target/MSP430/MSP430FrameLowering.cpp' l='157' u='r' c='_ZNK4llvm19MSP430FrameLowering12emitEpilogueERNS_15MachineFunctionERNS_17MachineBasicBlockE'/>
<use f='llvm/llvm/lib/Target/MSP430/MSP430FrameLowering.cpp' l='161' u='r' c='_ZNK4llvm19MSP430FrameLowering12emitEpilogueERNS_15MachineFunctionERNS_17MachineBasicBlockE'/>
<use f='llvm/llvm/lib/Target/MSP430/MSP430FrameLowering.cpp' l='162' u='r' c='_ZNK4llvm19MSP430FrameLowering12emitEpilogueERNS_15MachineFunctionERNS_17MachineBasicBlockE'/>
<use f='llvm/llvm/lib/Target/MSP430/MSP430FrameLowering.cpp' l='170' u='r' c='_ZNK4llvm19MSP430FrameLowering12emitEpilogueERNS_15MachineFunctionERNS_17MachineBasicBlockE'/>
<use f='llvm/llvm/lib/Target/MSP430/MSP430FrameLowering.cpp' l='171' u='r' c='_ZNK4llvm19MSP430FrameLowering12emitEpilogueERNS_15MachineFunctionERNS_17MachineBasicBlockE'/>
<use f='llvm/llvm/lib/Target/MSP430/MSP430FrameLowering.cpp' l='242' u='r' c='_ZNK4llvm19MSP430FrameLowering29eliminateCallFramePseudoInstrERNS_15MachineFunctionERNS_17MachineBasicBlockENS_26MachineInstrBundleIteratorINS_12MachineInstrELb0EEE'/>
<use f='llvm/llvm/lib/Target/MSP430/MSP430FrameLowering.cpp' l='243' u='r' c='_ZNK4llvm19MSP430FrameLowering29eliminateCallFramePseudoInstrERNS_15MachineFunctionERNS_17MachineBasicBlockENS_26MachineInstrBundleIteratorINS_12MachineInstrELb0EEE'/>
<use f='llvm/llvm/lib/Target/MSP430/MSP430FrameLowering.cpp' l='251' u='r' c='_ZNK4llvm19MSP430FrameLowering29eliminateCallFramePseudoInstrERNS_15MachineFunctionERNS_17MachineBasicBlockENS_26MachineInstrBundleIteratorINS_12MachineInstrELb0EEE'/>
<use f='llvm/llvm/lib/Target/MSP430/MSP430FrameLowering.cpp' l='252' u='r' c='_ZNK4llvm19MSP430FrameLowering29eliminateCallFramePseudoInstrERNS_15MachineFunctionERNS_17MachineBasicBlockENS_26MachineInstrBundleIteratorINS_12MachineInstrELb0EEE'/>
<use f='llvm/llvm/lib/Target/MSP430/MSP430FrameLowering.cpp' l='270' u='r' c='_ZNK4llvm19MSP430FrameLowering29eliminateCallFramePseudoInstrERNS_15MachineFunctionERNS_17MachineBasicBlockENS_26MachineInstrBundleIteratorINS_12MachineInstrELb0EEE'/>
<use f='llvm/llvm/lib/Target/MSP430/MSP430FrameLowering.cpp' l='271' u='r' c='_ZNK4llvm19MSP430FrameLowering29eliminateCallFramePseudoInstrERNS_15MachineFunctionERNS_17MachineBasicBlockENS_26MachineInstrBundleIteratorINS_12MachineInstrELb0EEE'/>
<use f='llvm/llvm/lib/Target/MSP430/MSP430ISelLowering.cpp' l='56' u='r' c='_ZN4llvm20MSP430TargetLoweringC1ERKNS_13TargetMachineERKNS_15MSP430SubtargetE'/>
<use f='llvm/llvm/lib/Target/MSP430/MSP430ISelLowering.cpp' l='854' u='r' c='_ZNK4llvm20MSP430TargetLowering14LowerCCCCallToENS_7SDValueES1_jbbRKNS_15SmallVectorImplINS_3ISD9OutputArgEEERKNS2_IS1_EERKNS2_INS3_8InputArgEEERKNS_59244059'/>
<use f='llvm/llvm/lib/Target/MSP430/MSP430RegisterInfo.cpp' l='83' u='r' c='_ZNK4llvm18MSP430RegisterInfo15getReservedRegsERKNS_15MachineFunctionE'/>
<use f='llvm/llvm/lib/Target/MSP430/MSP430RegisterInfo.cpp' l='115' u='r' c='_ZNK4llvm18MSP430RegisterInfo19eliminateFrameIndexENS_26MachineInstrBundleIteratorINS_12MachineInstrELb0EEEijPNS_12RegScavengerE'/>
<use f='llvm/llvm/lib/Target/MSP430/MSP430RegisterInfo.cpp' l='159' u='r' c='_ZNK4llvm18MSP430RegisterInfo16getFrameRegisterERKNS_15MachineFunctionE'/>
