<dec f='llvm/llvm/include/llvm/Target/TargetOptions.h' l='111' type='3'/>
<doc f='llvm/llvm/include/llvm/Target/TargetOptions.h' l='111'>// Tune debug info for SCE targets (e.g. PS4).</doc>
<use f='llvm/clang/lib/Driver/ToolChains/PS4CPU.h' l='83' u='r' c='_ZNK5clang6driver10toolchains6PS4CPU24getDefaultDebuggerTuningEv'/>
<use f='llvm/clang/lib/Driver/ToolChains/Clang.cpp' l='1022' c='_ZL23RenderDebugEnablingArgsRKN4llvm3opt7ArgListERNS_11SmallVectorIPKcLj16EEEN5clang14codegenoptions13DebugInfoKindEjNS_12DebuggerKindE'/>
<use f='llvm/clang/lib/Driver/ToolChains/Clang.cpp' l='3808' u='r' c='_ZL18renderDebugOptionsRKN5clang6driver9ToolChainERKNS0_6DriverERKN4llvm6TripleERKNS7_3opt7ArgListEbbRNS7_11SmallVectorIPKcLj16EEERNS_14codegenoptions4144156'/>
<use f='llvm/clang/lib/Driver/ToolChains/Clang.cpp' l='3886' u='r' c='_ZL18renderDebugOptionsRKN5clang6driver9ToolChainERKNS0_6DriverERKN4llvm6TripleERKNS7_3opt7ArgListEbbRNS7_11SmallVectorIPKcLj16EEERNS_14codegenoptions4144156'/>
<use f='llvm/clang/lib/Driver/ToolChains/Clang.cpp' l='4000' u='r' c='_ZL18renderDebugOptionsRKN5clang6driver9ToolChainERKNS0_6DriverERKN4llvm6TripleERKNS7_3opt7ArgListEbbRNS7_11SmallVectorIPKcLj16EEERNS_14codegenoptions4144156'/>
<use f='llvm/clang/lib/Driver/ToolChains/Clang.cpp' l='4029' u='r' c='_ZL18renderDebugOptionsRKN5clang6driver9ToolChainERKNS0_6DriverERKN4llvm6TripleERKNS7_3opt7ArgListEbbRNS7_11SmallVectorIPKcLj16EEERNS_14codegenoptions4144156'/>
<use f='llvm/clang/lib/Driver/ToolChains/Clang.cpp' l='4034' u='r' c='_ZL18renderDebugOptionsRKN5clang6driver9ToolChainERKNS0_6DriverERKN4llvm6TripleERKNS7_3opt7ArgListEbbRNS7_11SmallVectorIPKcLj16EEERNS_14codegenoptions4144156'/>
<use f='llvm/llvm/lib/CodeGen/AsmPrinter/DwarfDebug.h' l='822' u='r' c='_ZNK4llvm10DwarfDebug10tuneForSCEEv'/>
<use f='llvm/llvm/lib/CodeGen/AsmPrinter/DwarfDebug.cpp' l='359' u='r' c='_ZN4llvm10DwarfDebugC1EPNS_10AsmPrinterE'/>
<use f='llvm/llvm/lib/CodeGen/CommandFlags.cpp' l='417' u='a' c='_ZN4llvm7codegen20RegisterCodeGenFlagsC1Ev'/>
<use f='llvm/llvm/lib/CodeGen/TargetOptionsImpl.cpp' l='55' u='r' c='_ZNK4llvm13TargetOptions26ShouldEmitDebugEntryValuesEv'/>
