<dec f='llvm/llvm/include/llvm/ExecutionEngine/Orc/LLJIT.h' l='263' type='std::unique_ptr&lt;ExecutionSession&gt;'/>
<offset>0</offset>
<use f='llvm/llvm/lib/ExecutionEngine/Orc/LLJIT.cpp' l='1060' u='m' c='_ZN4llvm3orc5LLJITC1ERNS0_17LLJITBuilderStateERNS_5ErrorE'/>
<use f='llvm/llvm/lib/ExecutionEngine/Orc/LLJIT.cpp' l='1060' u='a' c='_ZN4llvm3orc5LLJITC1ERNS0_17LLJITBuilderStateERNS_5ErrorE'/>
