<dec f='llvm/llvm/include/llvm/CodeGen/ResourcePriorityQueue.h' l='31' type='llvm::ResourcePriorityQueue *'/>
<use f='llvm/llvm/include/llvm/CodeGen/ResourcePriorityQueue.h' l='32' u='w' c='_ZN4llvm13resource_sortC1EPNS_21ResourcePriorityQueueE'/>
<use f='llvm/llvm/lib/CodeGen/SelectionDAG/ResourcePriorityQueue.cpp' l='194' u='r' c='_ZNK4llvm13resource_sortclEPKNS_5SUnitES3_'/>
<use f='llvm/llvm/lib/CodeGen/SelectionDAG/ResourcePriorityQueue.cpp' l='195' u='r' c='_ZNK4llvm13resource_sortclEPKNS_5SUnitES3_'/>
<use f='llvm/llvm/lib/CodeGen/SelectionDAG/ResourcePriorityQueue.cpp' l='201' u='r' c='_ZNK4llvm13resource_sortclEPKNS_5SUnitES3_'/>
<use f='llvm/llvm/lib/CodeGen/SelectionDAG/ResourcePriorityQueue.cpp' l='202' u='r' c='_ZNK4llvm13resource_sortclEPKNS_5SUnitES3_'/>
<offset>0</offset>
