<dec f='llvm/build/lib/Target/Mips/MipsGenInstrInfo.inc' l='1861' type='1846'/>
<use f='llvm/build/lib/Target/Mips/MipsGenAsmMatcher.inc' l='6881'/>
<use f='llvm/build/lib/Target/Mips/MipsGenMCCodeEmitter.inc' l='6682' c='_ZNK4llvm17MipsMCCodeEmitter21getBinaryCodeForInstrERKNS_6MCInstERNS_15SmallVectorImplINS_7MCFixupEEERKNS_15MCSubtargetInfoE'/>
<use f='llvm/llvm/lib/Target/Mips/MCTargetDesc/MipsNaClELFStreamer.cpp' l='227' c='_ZN4llvm28isBasePlusOffsetMemoryAccessEjPjPb'/>
<use f='llvm/llvm/lib/Target/Mips/MipsExpandPseudo.cpp' l='97' u='r' c='_ZN12_GLOBAL__N_116MipsExpandPseudo26expandAtomicCmpSwapSubwordERN4llvm17MachineBasicBlockENS1_26MachineInstrBundleIteratorINS1_12MachineInstrELb0EEERS6_'/>
<use f='llvm/llvm/lib/Target/Mips/MipsExpandPseudo.cpp' l='224' u='r' c='_ZN12_GLOBAL__N_116MipsExpandPseudo19expandAtomicCmpSwapERN4llvm17MachineBasicBlockENS1_26MachineInstrBundleIteratorINS1_12MachineInstrELb0EEERS6_'/>
<use f='llvm/llvm/lib/Target/Mips/MipsExpandPseudo.cpp' l='328' u='r' c='_ZN12_GLOBAL__N_116MipsExpandPseudo24expandAtomicBinOpSubwordERN4llvm17MachineBasicBlockENS1_26MachineInstrBundleIteratorINS1_12MachineInstrELb0EEERS6_'/>
<use f='llvm/llvm/lib/Target/Mips/MipsExpandPseudo.cpp' l='603' u='r' c='_ZN12_GLOBAL__N_116MipsExpandPseudo17expandAtomicBinOpERN4llvm17MachineBasicBlockENS1_26MachineInstrBundleIteratorINS1_12MachineInstrELb0EEERS6_j'/>
<use f='llvm/llvm/lib/Target/Mips/MipsSERegisterInfo.cpp' l='80' c='_ZL28getLoadStoreOffsetSizeInBitsjN4llvm14MachineOperandE'/>
