<dec f='llvm/llvm/include/llvm/Analysis/AssumptionCache.h' l='184' type='llvm::raw_ostream &amp;'/>
<use f='llvm/llvm/include/llvm/Analysis/AssumptionCache.h' l='187' u='w' c='_ZN4llvm21AssumptionPrinterPassC1ERNS_11raw_ostreamE'/>
<offset>0</offset>
<use f='llvm/llvm/lib/Analysis/AssumptionCache.cpp' l='260' u='m' c='_ZN4llvm21AssumptionPrinterPass3runERNS_8FunctionERNS_15AnalysisManagerIS1_JEEE'/>
<use f='llvm/llvm/lib/Analysis/AssumptionCache.cpp' l='263' u='m' c='_ZN4llvm21AssumptionPrinterPass3runERNS_8FunctionERNS_15AnalysisManagerIS1_JEEE'/>
