<dec f='llvm/llvm/include/llvm/CodeGen/DIE.h' l='647' type='llvm::DIEValue'/>
<use f='llvm/llvm/include/llvm/CodeGen/DIE.h' l='649' u='w' c='_ZN4llvm12DIEValueList4NodeC1ENS_8DIEValueE'/>
<use f='llvm/llvm/include/llvm/CodeGen/DIE.h' l='672' u='a' c='_ZNK4llvm12DIEValueList14value_iteratordeEv'/>
<use f='llvm/llvm/include/llvm/CodeGen/DIE.h' l='690' u='a' c='_ZNK4llvm12DIEValueList20const_value_iteratordeEv'/>
<offset>64</offset>
