<def f='llvm/llvm/include/llvm/TableGen/Record.h' l='271' ll='398'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='330' c='_ZN4llvm4InitC1ERKS0_'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='331' c='_ZN4llvm4InitaSERKS0_'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='331' c='_ZN4llvm4InitaSERKS0_'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='358' c='_ZNK4llvm4Init9getCastToEPNS_5RecTyE'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='363' c='_ZNK4llvm4Init20convertInitializerToEPNS_5RecTyE'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='369' c='_ZNK4llvm4Init26convertInitializerBitRangeENS_8ArrayRefIjEE'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='377' c='_ZNK4llvm4Init20convertInitListSliceENS_8ArrayRefIjEE'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='392' c='_ZNK4llvm4Init17resolveReferencesERNS_8ResolverE'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='393' c='_ZNK4llvm4Init17resolveReferencesERNS_8ResolverE'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='397' c='_ZNK4llvm4Init6getBitEj'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='400' c='_ZN4llvmlsERNS_11raw_ostreamERKNS_4InitE'/>
<ovr f='llvm/llvm/include/llvm/TableGen/Record.h' l='406' c='llvm::TypedInit'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='406'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='411' c='_ZN4llvm9TypedInitC1ENS_4Init8InitKindEPNS_5RecTyEh'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='417' c='_ZN4llvm9TypedInit7classofEPKNS_4InitE'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='425' c='_ZNK4llvm9TypedInit9getCastToEPNS_5RecTyE'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='426' c='_ZNK4llvm9TypedInit20convertInitializerToEPNS_5RecTyE'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='428' c='_ZNK4llvm9TypedInit26convertInitializerBitRangeENS_8ArrayRefIjEE'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='429' c='_ZNK4llvm9TypedInit20convertInitListSliceENS_8ArrayRefIjEE'/>
<ovr f='llvm/llvm/include/llvm/TableGen/Record.h' l='438' c='llvm::UnsetInit'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='438'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='439' c='_ZN4llvm9UnsetInitC1Ev'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='445' c='_ZN4llvm9UnsetInit7classofEPKNS_4InitE'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='452' c='_ZNK4llvm9UnsetInit9getCastToEPNS_5RecTyE'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='453' c='_ZNK4llvm9UnsetInit20convertInitializerToEPNS_5RecTyE'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='455' c='_ZNK4llvm9UnsetInit6getBitEj'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='478' c='_ZN4llvm7BitInit7classofEPKNS_4InitE'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='486' c='_ZNK4llvm7BitInit20convertInitializerToEPNS_5RecTyE'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='488' c='_ZNK4llvm7BitInit6getBitEj'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='500'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='513' c='_ZN4llvm8BitsInit7classofEPKNS_4InitE'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='517' c='_ZN4llvm8BitsInit3getENS_8ArrayRefIPNS_4InitEEE'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='523' c='_ZNK4llvm8BitsInit20convertInitializerToEPNS_5RecTyE'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='524' c='_ZNK4llvm8BitsInit26convertInitializerBitRangeENS_8ArrayRefIjEE'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='541' c='_ZNK4llvm8BitsInit17resolveReferencesERNS_8ResolverE'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='543' c='_ZNK4llvm8BitsInit6getBitEj'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='545' c='_ZNK4llvm8BitsInit6getBitEj'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='560' c='_ZN4llvm7IntInit7classofEPKNS_4InitE'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='568' c='_ZNK4llvm7IntInit20convertInitializerToEPNS_5RecTyE'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='569' c='_ZNK4llvm7IntInit26convertInitializerBitRangeENS_8ArrayRefIjEE'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='574' c='_ZNK4llvm7IntInit6getBitEj'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='598' c='_ZN4llvm10StringInit7classofEPKNS_4InitE'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='612' c='_ZNK4llvm10StringInit20convertInitializerToEPNS_5RecTyE'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='627' c='_ZNK4llvm10StringInit6getBitEj'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='635'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='639'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='652' c='_ZN4llvm8ListInit7classofEPKNS_4InitE'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='655' c='_ZN4llvm8ListInit3getENS_8ArrayRefIPNS_4InitEEEPNS_5RecTyE'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='659' c='_ZNK4llvm8ListInit10getElementEj'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='661' c='_ZNK4llvm8ListInit10getElementEj'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='669' c='_ZNK4llvm8ListInit20convertInitListSliceENS_8ArrayRefIjEE'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='671' c='_ZNK4llvm8ListInit20convertInitializerToEPNS_5RecTyE'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='678' c='_ZNK4llvm8ListInit17resolveReferencesERNS_8ResolverE'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='683' c='_ZNK4llvm8ListInit9getValuesEv'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='684' c='_ZNK4llvm8ListInit9getValuesEv'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='687' c='_ZNK4llvm8ListInit5beginEv'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='693' c='_ZNK4llvm8ListInit6getBitEj'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='709' c='_ZN4llvm6OpInit7classofEPKNS_4InitE'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='715' c='_ZNK4llvm6OpInit5cloneENS_8ArrayRefIPNS_4InitEEE'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='718' c='_ZNK4llvm6OpInit10getOperandEj'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='720' c='_ZNK4llvm6OpInit6getBitEj'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='730'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='732' c='_ZN4llvm8UnOpInitC1ENS0_7UnaryOpEPNS_4InitEPNS_5RecTyE'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='739' c='_ZN4llvm8UnOpInit7classofEPKNS_4InitE'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='743' c='_ZN4llvm8UnOpInit3getENS0_7UnaryOpEPNS_4InitEPNS_5RecTyE'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='748' c='_ZNK4llvm8UnOpInit5cloneENS_8ArrayRefIPNS_4InitEEE'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='756' c='_ZNK4llvm8UnOpInit10getOperandEj'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='762' c='_ZNK4llvm8UnOpInit10getOperandEv'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='766' c='_ZNK4llvm8UnOpInit4FoldEPNS_6RecordEb'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='768' c='_ZNK4llvm8UnOpInit17resolveReferencesERNS_8ResolverE'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='781'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='781'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='783' c='_ZN4llvm9BinOpInitC1ENS0_8BinaryOpEPNS_4InitES3_PNS_5RecTyE'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='783' c='_ZN4llvm9BinOpInitC1ENS0_8BinaryOpEPNS_4InitES3_PNS_5RecTyE'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='790' c='_ZN4llvm9BinOpInit7classofEPKNS_4InitE'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='794' c='_ZN4llvm9BinOpInit3getENS0_8BinaryOpEPNS_4InitES3_PNS_5RecTyE'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='794' c='_ZN4llvm9BinOpInit3getENS0_8BinaryOpEPNS_4InitES3_PNS_5RecTyE'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='796' c='_ZN4llvm9BinOpInit12getStrConcatEPNS_4InitES2_'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='796' c='_ZN4llvm9BinOpInit12getStrConcatEPNS_4InitES2_'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='796' c='_ZN4llvm9BinOpInit12getStrConcatEPNS_4InitES2_'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='797' c='_ZN4llvm9BinOpInit13getListConcatEPNS_9TypedInitEPNS_4InitE'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='797' c='_ZN4llvm9BinOpInit13getListConcatEPNS_9TypedInitEPNS_4InitE'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='802' c='_ZNK4llvm9BinOpInit5cloneENS_8ArrayRefIPNS_4InitEEE'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='809' c='_ZNK4llvm9BinOpInit10getOperandEj'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='818' c='_ZNK4llvm9BinOpInit6getLHSEv'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='819' c='_ZNK4llvm9BinOpInit6getRHSEv'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='823' c='_ZNK4llvm9BinOpInit4FoldEPNS_6RecordE'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='825' c='_ZNK4llvm9BinOpInit17resolveReferencesERNS_8ResolverE'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='836'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='836'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='836'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='838' c='_ZN4llvm10TernOpInitC1ENS0_9TernaryOpEPNS_4InitES3_S3_PNS_5RecTyE'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='838' c='_ZN4llvm10TernOpInitC1ENS0_9TernaryOpEPNS_4InitES3_S3_PNS_5RecTyE'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='838' c='_ZN4llvm10TernOpInitC1ENS0_9TernaryOpEPNS_4InitES3_S3_PNS_5RecTyE'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='846' c='_ZN4llvm10TernOpInit7classofEPKNS_4InitE'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='850' c='_ZN4llvm10TernOpInit3getENS0_9TernaryOpEPNS_4InitES3_S3_PNS_5RecTyE'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='851' c='_ZN4llvm10TernOpInit3getENS0_9TernaryOpEPNS_4InitES3_S3_PNS_5RecTyE'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='851' c='_ZN4llvm10TernOpInit3getENS0_9TernaryOpEPNS_4InitES3_S3_PNS_5RecTyE'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='857' c='_ZNK4llvm10TernOpInit5cloneENS_8ArrayRefIPNS_4InitEEE'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='865' c='_ZNK4llvm10TernOpInit10getOperandEj'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='875' c='_ZNK4llvm10TernOpInit6getLHSEv'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='876' c='_ZNK4llvm10TernOpInit6getMHSEv'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='877' c='_ZNK4llvm10TernOpInit6getRHSEv'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='881' c='_ZNK4llvm10TernOpInit4FoldEPNS_6RecordE'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='887' c='_ZNK4llvm10TernOpInit17resolveReferencesERNS_8ResolverE'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='896'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='904' c='_ZNK4llvm10CondOpInit18numTrailingObjectsENS_25trailing_objects_internal19TrailingObjectsBase13OverloadTokenIPNS_4InitEEE'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='912' c='_ZN4llvm10CondOpInit7classofEPKNS_4InitE'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='916' c='_ZN4llvm10CondOpInit3getENS_8ArrayRefIPNS_4InitEEES4_PNS_5RecTyE'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='916' c='_ZN4llvm10CondOpInit3getENS_8ArrayRefIPNS_4InitEEES4_PNS_5RecTyE'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='925' c='_ZNK4llvm10CondOpInit7getCondEj'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='927' c='_ZNK4llvm10CondOpInit7getCondEj'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='930' c='_ZNK4llvm10CondOpInit6getValEj'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='932' c='_ZNK4llvm10CondOpInit6getValEj'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='935' c='_ZNK4llvm10CondOpInit8getCondsEv'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='936' c='_ZNK4llvm10CondOpInit8getCondsEv'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='939' c='_ZNK4llvm10CondOpInit7getValsEv'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='940' c='_ZNK4llvm10CondOpInit7getValsEv'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='943' c='_ZNK4llvm10CondOpInit4FoldEPNS_6RecordE'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='945' c='_ZNK4llvm10CondOpInit17resolveReferencesERNS_8ResolverE'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='966' c='_ZNK4llvm10CondOpInit6getBitEj'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='972'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='973'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='974'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='975'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='976'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='978' c='_ZN4llvm10FoldOpInitC1EPNS_4InitES2_S2_S2_S2_PNS_5RecTyE'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='978' c='_ZN4llvm10FoldOpInitC1EPNS_4InitES2_S2_S2_S2_PNS_5RecTyE'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='978' c='_ZN4llvm10FoldOpInitC1EPNS_4InitES2_S2_S2_S2_PNS_5RecTyE'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='978' c='_ZN4llvm10FoldOpInitC1EPNS_4InitES2_S2_S2_S2_PNS_5RecTyE'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='978' c='_ZN4llvm10FoldOpInitC1EPNS_4InitES2_S2_S2_S2_PNS_5RecTyE'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='986' c='_ZN4llvm10FoldOpInit7classofEPKNS_4InitE'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='988' c='_ZN4llvm10FoldOpInit3getEPNS_4InitES2_S2_S2_S2_PNS_5RecTyE'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='988' c='_ZN4llvm10FoldOpInit3getEPNS_4InitES2_S2_S2_S2_PNS_5RecTyE'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='988' c='_ZN4llvm10FoldOpInit3getEPNS_4InitES2_S2_S2_S2_PNS_5RecTyE'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='988' c='_ZN4llvm10FoldOpInit3getEPNS_4InitES2_S2_S2_S2_PNS_5RecTyE'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='988' c='_ZN4llvm10FoldOpInit3getEPNS_4InitES2_S2_S2_S2_PNS_5RecTyE'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='995' c='_ZNK4llvm10FoldOpInit4FoldEPNS_6RecordE'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='999' c='_ZNK4llvm10FoldOpInit17resolveReferencesERNS_8ResolverE'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='1001' c='_ZNK4llvm10FoldOpInit6getBitEj'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='1010'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='1012' c='_ZN4llvm9IsAOpInitC1EPNS_5RecTyEPNS_4InitE'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='1020' c='_ZN4llvm9IsAOpInit7classofEPKNS_4InitE'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='1022' c='_ZN4llvm9IsAOpInit3getEPNS_5RecTyEPNS_4InitE'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='1028' c='_ZNK4llvm9IsAOpInit4FoldEv'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='1032' c='_ZNK4llvm9IsAOpInit17resolveReferencesERNS_8ResolverE'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='1034' c='_ZNK4llvm9IsAOpInit6getBitEj'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='1041'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='1043' c='_ZN4llvm7VarInitC1EPNS_4InitEPNS_5RecTyE'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='1050' c='_ZN4llvm7VarInit7classofEPKNS_4InitE'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='1055' c='_ZN4llvm7VarInit3getEPNS_4InitEPNS_5RecTyE'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='1058' c='_ZNK4llvm7VarInit11getNameInitEv'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='1069' c='_ZNK4llvm7VarInit17resolveReferencesERNS_8ResolverE'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='1071' c='_ZNK4llvm7VarInit6getBitEj'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='1094' c='_ZN4llvm10VarBitInit7classofEPKNS_4InitE'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='1100' c='_ZNK4llvm10VarBitInit9getBitVarEv'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='1104' c='_ZNK4llvm10VarBitInit17resolveReferencesERNS_8ResolverE'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='1106' c='_ZNK4llvm10VarBitInit6getBitEj'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='1130' c='_ZN4llvm18VarListElementInit7classofEPKNS_4InitE'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='1140' c='_ZNK4llvm18VarListElementInit17resolveReferencesERNS_8ResolverE'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='1142' c='_ZNK4llvm18VarListElementInit6getBitEj'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='1157' c='_ZN4llvm7DefInit7classofEPKNS_4InitE'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='1163' c='_ZNK4llvm7DefInit20convertInitializerToEPNS_5RecTyE'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='1174' c='_ZNK4llvm7DefInit6getBitEj'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='1182'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='1199' c='_ZN4llvm10VarDefInit7classofEPKNS_4InitE'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='1202' c='_ZN4llvm10VarDefInit3getEPNS_6RecordENS_8ArrayRefIPNS_4InitEEE'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='1206' c='_ZNK4llvm10VarDefInit17resolveReferencesERNS_8ResolverE'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='1207' c='_ZNK4llvm10VarDefInit4FoldEv'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='1211' c='_ZNK4llvm10VarDefInit6getArgEj'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='1213' c='_ZNK4llvm10VarDefInit6getArgEj'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='1216'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='1218' c='_ZNK4llvm10VarDefInit10args_beginEv'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='1224' c='_ZNK4llvm10VarDefInit4argsEv'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='1226' c='_ZNK4llvm10VarDefInit6getBitEj'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='1233'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='1236' c='_ZN4llvm9FieldInitC1EPNS_4InitEPNS_10StringInitE'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='1252' c='_ZN4llvm9FieldInit7classofEPKNS_4InitE'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='1256' c='_ZN4llvm9FieldInit3getEPNS_4InitEPNS_10StringInitE'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='1258' c='_ZNK4llvm9FieldInit9getRecordEv'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='1261' c='_ZNK4llvm9FieldInit6getBitEj'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='1263' c='_ZNK4llvm9FieldInit17resolveReferencesERNS_8ResolverE'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='1264' c='_ZNK4llvm9FieldInit4FoldEPNS_6RecordE'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='1276'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='1279'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='1284' c='_ZN4llvm7DagInitC1EPNS_4InitEPNS_10StringInitEjj'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='1288' c='_ZNK4llvm7DagInit18numTrailingObjectsENS_25trailing_objects_internal19TrailingObjectsBase13OverloadTokenIPNS_4InitEEE'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='1294' c='_ZN4llvm7DagInit7classofEPKNS_4InitE'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='1298' c='_ZN4llvm7DagInit3getEPNS_4InitEPNS_10StringInitENS_8ArrayRefIS2_EENS5_IS4_EE'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='1298' c='_ZN4llvm7DagInit3getEPNS_4InitEPNS_10StringInitENS_8ArrayRefIS2_EENS5_IS4_EE'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='1300' c='_ZN4llvm7DagInit3getEPNS_4InitEPNS_10StringInitENS_8ArrayRefISt4pairIS2_S4_EEE'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='1301' c='_ZN4llvm7DagInit3getEPNS_4InitEPNS_10StringInitENS_8ArrayRefISt4pairIS2_S4_EEE'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='1305' c='_ZNK4llvm7DagInit11getOperatorEv'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='1316' c='_ZNK4llvm7DagInit6getArgEj'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='1318' c='_ZNK4llvm7DagInit6getArgEj'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='1331' c='_ZNK4llvm7DagInit7getArgsEv'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='1332' c='_ZNK4llvm7DagInit7getArgsEv'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='1339' c='_ZNK4llvm7DagInit17resolveReferencesERNS_8ResolverE'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='1359' c='_ZNK4llvm7DagInit6getBitEj'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='1381'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='1384'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='1387' c='_ZN4llvm9RecordValC1EPNS_4InitEPNS_5RecTyENS0_9FieldKindE'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='1388' c='_ZN4llvm9RecordValC1EPNS_4InitENS_5SMLocEPNS_5RecTyENS0_9FieldKindE'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='1394' c='_ZNK4llvm9RecordVal11getNameInitEv'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='1421' c='_ZNK4llvm9RecordVal8getValueEv'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='1424' c='_ZN4llvm9RecordVal8setValueEPNS_4InitE'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='1427' c='_ZN4llvm9RecordVal8setValueEPNS_4InitENS_5SMLocE'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='1443'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='1447'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='1450'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='1450'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='1472' c='_ZN4llvm6RecordC1EPNS_4InitENS_8ArrayRefINS_5SMLocEEERNS_12RecordKeeperEbb'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='1498' c='_ZNK4llvm6Record11getNameInitEv'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='1506' c='_ZN4llvm6Record7setNameEPNS_4InitE'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='1519' c='_ZNK4llvm6Record15getTemplateArgsEv'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='1525' c='_ZNK4llvm6Record13getAssertionsEv'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='1525' c='_ZNK4llvm6Record13getAssertionsEv'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='1539' c='_ZNK4llvm6Record13isTemplateArgEPNS_4InitE'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='1540' c='_ZNK4llvm6Record13isTemplateArgEPNS_4InitE'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='1545' c='_ZNK4llvm6Record8getValueEPKNS_4InitE'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='1555' c='_ZN4llvm6Record8getValueEPKNS_4InitE'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='1563' c='_ZN4llvm6Record14addTemplateArgEPNS_4InitE'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='1573' c='_ZN4llvm6Record11removeValueEPNS_4InitE'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='1586' c='_ZN4llvm6Record12addAssertionENS_5SMLocEPNS_4InitES3_'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='1586' c='_ZN4llvm6Record12addAssertionENS_5SMLocEPNS_4InitES3_'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='1649' c='_ZNK4llvm6Record12getValueInitENS_9StringRefE'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='1729'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='1735'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='1771' c='_ZNK4llvm12RecordKeeper9getGlobalENS_9StringRefE'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='1796' c='_ZN4llvm12RecordKeeper14addExtraGlobalENS_9StringRefEPNS_4InitE'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='1803' c='_ZN4llvm12RecordKeeper19getNewAnonymousNameEv'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='1966' c='_ZN4llvm8Resolver7resolveEPNS_4InitE'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='1966' c='_ZN4llvm8Resolver7resolveEPNS_4InitE'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='1984'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='1988' c='_ZN4llvm11MapResolver11MappedValueC1EPNS_4InitEb'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='1991'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='1996' c='_ZN4llvm11MapResolver3setEPNS_4InitES2_'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='1996' c='_ZN4llvm11MapResolver3setEPNS_4InitES2_'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='1998' c='_ZN4llvm11MapResolver7resolveEPNS_4InitE'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='1998' c='_ZN4llvm11MapResolver7resolveEPNS_4InitE'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='2003'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='2003'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='2004'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='2009' c='_ZN4llvm14RecordResolver7resolveEPNS_4InitE'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='2009' c='_ZN4llvm14RecordResolver7resolveEPNS_4InitE'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='2017'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='2025' c='_ZN4llvm14ShadowResolver9addShadowEPNS_4InitE'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='2027' c='_ZN4llvm14ShadowResolver7resolveEPNS_4InitE'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='2027' c='_ZN4llvm14ShadowResolver7resolveEPNS_4InitE'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='2046' c='_ZN4llvm23TrackUnresolvedResolver7resolveEPNS_4InitE'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='2046' c='_ZN4llvm23TrackUnresolvedResolver7resolveEPNS_4InitE'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='2052'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='2056' c='_ZN4llvm20HasReferenceResolverC1EPNS_4InitE'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='2061' c='_ZN4llvm20HasReferenceResolver7resolveEPNS_4InitE'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='2061' c='_ZN4llvm20HasReferenceResolver7resolveEPNS_4InitE'/>
<size>16</size>
<doc f='llvm/llvm/include/llvm/TableGen/Record.h' l='267'>//===----------------------------------------------------------------------===//
//  Initializer Classes
//===----------------------------------------------------------------------===//</doc>
<mbr r='llvm::Init::Kind' o='64' t='const llvm::Init::InitKind'/>
<mbr r='llvm::Init::Opc' o='72' t='uint8_t'/>
<fun r='_ZN4llvm4Init6anchorEv'/>
<fun r='_ZNK4llvm4Init7getKindEv'/>
<fun r='_ZN4llvm4InitC1ENS0_8InitKindEh'/>
<fun r='_ZN4llvm4InitC1ERKS0_'/>
<fun r='_ZN4llvm4InitaSERKS0_'/>
<fun r='_ZN4llvm4InitD1Ev'/>
<fun r='_ZNK4llvm4Init10isCompleteEv'/>
<fun r='_ZNK4llvm4Init10isConcreteEv'/>
<fun r='_ZNK4llvm4Init5printERNS_11raw_ostreamE'/>
<fun r='_ZNK4llvm4Init11getAsStringB5cxx11Ev'/>
<fun r='_ZNK4llvm4Init19getAsUnquotedStringB5cxx11Ev'/>
<fun r='_ZNK4llvm4Init4dumpEv'/>
<fun r='_ZNK4llvm4Init9getCastToEPNS_5RecTyE'/>
<fun r='_ZNK4llvm4Init20convertInitializerToEPNS_5RecTyE'/>
<fun r='_ZNK4llvm4Init26convertInitializerBitRangeENS_8ArrayRefIjEE'/>
<fun r='_ZNK4llvm4Init20convertInitListSliceENS_8ArrayRefIjEE'/>
<fun r='_ZNK4llvm4Init12getFieldTypeEPNS_10StringInitE'/>
<fun r='_ZNK4llvm4Init17resolveReferencesERNS_8ResolverE'/>
<fun r='_ZNK4llvm4Init6getBitEj'/>
<use f='llvm/clang/utils/TableGen/MveEmitter.cpp' l='1034' c='_ZN12_GLOBAL__N_111EmitterBase7getTypeEPN4llvm4InitEPKNS_4TypeE'/>
<use f='llvm/clang/utils/TableGen/MveEmitter.cpp' l='1060' c='_ZN12_GLOBAL__N_111EmitterBase7getTypeEPN4llvm4InitEPKNS_4TypeE'/>
<use f='llvm/clang/utils/TableGen/MveEmitter.cpp' l='1262' c='_ZN12_GLOBAL__N_111EmitterBase16getCodeForDagArgEPN4llvm7DagInitEjRKSt3mapINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESt10shared_ptrINS_6Resu13609687'/>
<use f='llvm/clang/utils/TableGen/MveEmitter.cpp' l='1362' c='_ZN12_GLOBAL__N_113ACLEIntrinsicC1ERNS_11EmitterBaseEPN4llvm6RecordEPKNS_4TypeE'/>
<size>16</size>
<use f='llvm/llvm/include/llvm/TableGen/SetTheory.h' l='127' c='_ZN4llvm9SetTheory8evaluateEPNS_4InitERNS_14SmallSetVectorIPNS_6RecordELj16EEENS_8ArrayRefINS_5SMLocEEE'/>
<use f='llvm/clang/utils/TableGen/NeonEmitter.cpp' l='521' c='_ZN12_GLOBAL__N_19Intrinsic10DagEmitter10emitDagArgEPN4llvm4InitENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE'/>
<use f='llvm/clang/utils/TableGen/NeonEmitter.cpp' l='1781' c='_ZN12_GLOBAL__N_19Intrinsic10DagEmitter10emitDagArgEPN4llvm4InitENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE'/>
<size>16</size>
<use f='llvm/llvm/lib/TableGen/DetailedRecordsBackend.cpp' l='139' c='_ZN12_GLOBAL__N_122DetailedRecordsEmitter17printTemplateArgsEPN4llvm6RecordERNS1_11raw_ostreamE'/>
<use f='llvm/llvm/lib/TableGen/DetailedRecordsBackend.cpp' l='146' c='_ZN12_GLOBAL__N_122DetailedRecordsEmitter17printTemplateArgsEPN4llvm6RecordERNS1_11raw_ostreamE'/>
<size>16</size>
<use f='llvm/llvm/lib/TableGen/JSONBackend.cpp' l='31' c='_ZN12_GLOBAL__N_111JSONEmitter13translateInitERKN4llvm4InitE'/>
<use f='llvm/llvm/lib/TableGen/JSONBackend.cpp' l='43' c='_ZN12_GLOBAL__N_111JSONEmitter13translateInitERKN4llvm4InitE'/>
<size>16</size>
<use f='llvm/llvm/lib/TableGen/TGParser.h' l='32'/>
<use f='llvm/llvm/lib/TableGen/TGParser.h' l='34' c='_ZN4llvm9LetRecordC1EPNS_10StringInitENS_8ArrayRefIjEEPNS_4InitENS_5SMLocE'/>
<use f='llvm/llvm/lib/TableGen/TGParser.h' l='61'/>
<use f='llvm/llvm/lib/TableGen/TGParser.h' l='66' c='_ZN4llvm11ForeachLoopC1ENS_5SMLocEPNS_7VarInitEPNS_4InitE'/>
<use f='llvm/llvm/lib/TableGen/TGParser.h' l='73'/>
<use f='llvm/llvm/lib/TableGen/TGParser.h' l='78'/>
<use f='llvm/llvm/lib/TableGen/TGParser.h' l='92' c='_ZNK4llvm15TGLocalVarScope6getVarENS_9StringRefE'/>
<use f='llvm/llvm/lib/TableGen/TGParser.h' l='109' c='_ZN4llvm15TGLocalVarScope6addVarENS_9StringRefEPNS_4InitE'/>
<use f='llvm/llvm/lib/TableGen/TGParser.h' l='194' c='_ZN4llvm8TGParser8SetValueEPNS_6RecordENS_5SMLocEPNS_4InitENS_8ArrayRefIjEES5_b'/>
<use f='llvm/llvm/lib/TableGen/TGParser.h' l='195' c='_ZN4llvm8TGParser8SetValueEPNS_6RecordENS_5SMLocEPNS_4InitENS_8ArrayRefIjEES5_b'/>
<use f='llvm/llvm/lib/TableGen/TGParser.h' l='202'/>
<use f='llvm/llvm/lib/TableGen/TGParser.h' l='202'/>
<use f='llvm/llvm/lib/TableGen/TGParser.h' l='234' c='_ZN4llvm8TGParser16ParseDeclarationEPNS_6RecordEb'/>
<use f='llvm/llvm/lib/TableGen/TGParser.h' l='235' c='_ZN4llvm8TGParser23ParseForeachDeclarationERPNS_4InitE'/>
<use f='llvm/llvm/lib/TableGen/TGParser.h' l='240' c='_ZN4llvm8TGParser12ParseIDValueEPNS_6RecordEPNS_10StringInitENS_5SMLocENS0_11IDParseModeE'/>
<use f='llvm/llvm/lib/TableGen/TGParser.h' l='242' c='_ZN4llvm8TGParser16ParseSimpleValueEPNS_6RecordEPNS_5RecTyENS0_11IDParseModeE'/>
<use f='llvm/llvm/lib/TableGen/TGParser.h' l='244' c='_ZN4llvm8TGParser10ParseValueEPNS_6RecordEPNS_5RecTyENS0_11IDParseModeE'/>
<use f='llvm/llvm/lib/TableGen/TGParser.h' l='246' c='_ZN4llvm8TGParser14ParseValueListERNS_15SmallVectorImplIPNS_4InitEEEPNS_6RecordES7_PNS_5RecTyE'/>
<use f='llvm/llvm/lib/TableGen/TGParser.h' l='249' c='_ZN4llvm8TGParser15ParseDagArgListERNS_15SmallVectorImplISt4pairIPNS_4InitEPNS_10StringInitEEEEPNS_6RecordE'/>
<use f='llvm/llvm/lib/TableGen/TGParser.h' l='257' c='_ZN4llvm8TGParser14ParseOperationEPNS_6RecordEPNS_5RecTyE'/>
<use f='llvm/llvm/lib/TableGen/TGParser.h' l='258' c='_ZN4llvm8TGParser20ParseOperationSubstrEPNS_6RecordEPNS_5RecTyE'/>
<use f='llvm/llvm/lib/TableGen/TGParser.h' l='259' c='_ZN4llvm8TGParser27ParseOperationForEachFilterEPNS_6RecordEPNS_5RecTyE'/>
<use f='llvm/llvm/lib/TableGen/TGParser.h' l='260' c='_ZN4llvm8TGParser18ParseOperationCondEPNS_6RecordEPNS_5RecTyE'/>
<use f='llvm/llvm/lib/TableGen/TGParser.h' l='262' c='_ZN4llvm8TGParser15ParseObjectNameEPNS_10MultiClassE'/>
<use f='llvm/llvm/lib/TableGen/TGParser.h' l='267' c='_ZN4llvm8TGParser11CheckAssertENS_5SMLocEPNS_4InitES3_'/>
<use f='llvm/llvm/lib/TableGen/TGParser.h' l='267' c='_ZN4llvm8TGParser11CheckAssertENS_5SMLocEPNS_4InitES3_'/>
<size>16</size>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='291' c='_ZNK4llvm9UnsetInit9getCastToEPNS_5RecTyE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='295' c='_ZNK4llvm9UnsetInit20convertInitializerToEPNS_5RecTyE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='306' c='_ZNK4llvm7BitInit20convertInitializerToEPNS_5RecTyE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='323' c='_ZL15ProfileBitsInitRN4llvm16FoldingSetNodeIDENS_8ArrayRefIPNS_4InitEEE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='326' c='_ZL15ProfileBitsInitRN4llvm16FoldingSetNodeIDENS_8ArrayRefIPNS_4InitEEE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='330' c='_ZN4llvm8BitsInit3getENS_8ArrayRefIPNS_4InitEEE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='340' c='_ZN4llvm8BitsInit3getENS_8ArrayRefIPNS_4InitEEE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='344' c='_ZN4llvm8BitsInit3getENS_8ArrayRefIPNS_4InitEEE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='350' c='_ZNK4llvm8BitsInit7ProfileERNS_16FoldingSetNodeIDE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='353' c='_ZNK4llvm8BitsInit20convertInitializerToEPNS_5RecTyE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='379' c='_ZNK4llvm8BitsInit26convertInitializerBitRangeENS_8ArrayRefIjEE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='381' c='_ZNK4llvm8BitsInit26convertInitializerBitRangeENS_8ArrayRefIjEE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='403' c='_ZNK4llvm8BitsInit11getAsStringB5cxx11Ev'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='413' c='_ZNK4llvm8BitsInit17resolveReferencesERNS_8ResolverE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='415' c='_ZNK4llvm8BitsInit17resolveReferencesERNS_8ResolverE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='417' c='_ZNK4llvm8BitsInit17resolveReferencesERNS_8ResolverE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='418' c='_ZNK4llvm8BitsInit17resolveReferencesERNS_8ResolverE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='421' c='_ZNK4llvm8BitsInit17resolveReferencesERNS_8ResolverE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='422' c='_ZNK4llvm8BitsInit17resolveReferencesERNS_8ResolverE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='466' c='_ZNK4llvm7IntInit20convertInitializerToEPNS_5RecTyE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='482' c='_ZNK4llvm7IntInit20convertInitializerToEPNS_5RecTyE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='492' c='_ZNK4llvm7IntInit26convertInitializerBitRangeENS_8ArrayRefIjEE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='494' c='_ZNK4llvm7IntInit26convertInitializerBitRangeENS_8ArrayRefIjEE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='522' c='_ZNK4llvm10StringInit20convertInitializerToEPNS_5RecTyE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='530' c='_ZL15ProfileListInitRN4llvm16FoldingSetNodeIDENS_8ArrayRefIPNS_4InitEEEPNS_5RecTyE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='535' c='_ZL15ProfileListInitRN4llvm16FoldingSetNodeIDENS_8ArrayRefIPNS_4InitEEEPNS_5RecTyE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='539' c='_ZN4llvm8ListInit3getENS_8ArrayRefIPNS_4InitEEEPNS_5RecTyE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='552' c='_ZN4llvm8ListInit3getENS_8ArrayRefIPNS_4InitEEEPNS_5RecTyE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='556' c='_ZN4llvm8ListInit3getENS_8ArrayRefIPNS_4InitEEEPNS_5RecTyE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='567' c='_ZNK4llvm8ListInit20convertInitializerToEPNS_5RecTyE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='572' c='_ZNK4llvm8ListInit20convertInitializerToEPNS_5RecTyE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='579' c='_ZNK4llvm8ListInit20convertInitializerToEPNS_5RecTyE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='580' c='_ZNK4llvm8ListInit20convertInitializerToEPNS_5RecTyE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='595' c='_ZNK4llvm8ListInit20convertInitListSliceENS_8ArrayRefIjEE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='596' c='_ZNK4llvm8ListInit20convertInitListSliceENS_8ArrayRefIjEE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='614' c='_ZNK4llvm8ListInit17resolveReferencesERNS_8ResolverE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='615' c='_ZNK4llvm8ListInit17resolveReferencesERNS_8ResolverE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='619' c='_ZNK4llvm8ListInit17resolveReferencesERNS_8ResolverE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='620' c='_ZNK4llvm8ListInit17resolveReferencesERNS_8ResolverE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='631' c='_ZNK4llvm8ListInit10isConcreteEv'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='641' c='_ZNK4llvm8ListInit11getAsStringB5cxx11Ev'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='649' c='_ZNK4llvm6OpInit6getBitEj'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='656' c='_ZL15ProfileUnOpInitRN4llvm16FoldingSetNodeIDEjPNS_4InitEPNS_5RecTyE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='662' c='_ZN4llvm8UnOpInit3getENS0_7UnaryOpEPNS_4InitEPNS_5RecTyE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='681' c='_ZNK4llvm8UnOpInit4FoldEPNS_6RecordEb'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='731' c='_ZNK4llvm8UnOpInit4FoldEPNS_6RecordEb'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='793' c='_ZNK4llvm8UnOpInit17resolveReferencesERNS_8ResolverE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='794' c='_ZNK4llvm8UnOpInit17resolveReferencesERNS_8ResolverE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='817' c='_ZL16ProfileBinOpInitRN4llvm16FoldingSetNodeIDEjPNS_4InitES3_PNS_5RecTyE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='817' c='_ZL16ProfileBinOpInitRN4llvm16FoldingSetNodeIDEjPNS_4InitES3_PNS_5RecTyE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='825' c='_ZN4llvm9BinOpInit3getENS0_8BinaryOpEPNS_4InitES3_PNS_5RecTyE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='826' c='_ZN4llvm9BinOpInit3getENS0_8BinaryOpEPNS_4InitES3_PNS_5RecTyE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='898' c='_ZN4llvm9BinOpInit12getStrConcatEPNS_4InitES2_'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='898' c='_ZN4llvm9BinOpInit12getStrConcatEPNS_4InitES2_'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='898' c='_ZN4llvm9BinOpInit12getStrConcatEPNS_4InitES2_'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='908' c='_ZL15ConcatListInitsPKN4llvm8ListInitES2_'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='914' c='_ZN4llvm9BinOpInit13getListConcatEPNS_9TypedInitEPNS_4InitE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='914' c='_ZN4llvm9BinOpInit13getListConcatEPNS_9TypedInitEPNS_4InitE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='924' c='_ZNK4llvm9BinOpInit4FoldEPNS_6RecordE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='940' c='_ZNK4llvm9BinOpInit4FoldEPNS_6RecordE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='944' c='_ZNK4llvm9BinOpInit4FoldEPNS_6RecordE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='962' c='_ZNK4llvm9BinOpInit4FoldEPNS_6RecordE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='973' c='_ZNK4llvm9BinOpInit4FoldEPNS_6RecordE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='1058' c='_ZNK4llvm9BinOpInit4FoldEPNS_6RecordE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='1104' c='_ZNK4llvm9BinOpInit17resolveReferencesERNS_8ResolverE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='1105' c='_ZNK4llvm9BinOpInit17resolveReferencesERNS_8ResolverE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='1106' c='_ZNK4llvm9BinOpInit17resolveReferencesERNS_8ResolverE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='1143' c='_ZL17ProfileTernOpInitRN4llvm16FoldingSetNodeIDEjPNS_4InitES3_S3_PNS_5RecTyE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='1143' c='_ZL17ProfileTernOpInitRN4llvm16FoldingSetNodeIDEjPNS_4InitES3_S3_PNS_5RecTyE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='1144' c='_ZL17ProfileTernOpInitRN4llvm16FoldingSetNodeIDEjPNS_4InitES3_S3_PNS_5RecTyE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='1152' c='_ZN4llvm10TernOpInit3getENS0_9TernaryOpEPNS_4InitES3_S3_PNS_5RecTyE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='1152' c='_ZN4llvm10TernOpInit3getENS0_9TernaryOpEPNS_4InitES3_S3_PNS_5RecTyE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='1152' c='_ZN4llvm10TernOpInit3getENS0_9TernaryOpEPNS_4InitES3_S3_PNS_5RecTyE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='1172' c='_ZL9ItemApplyPN4llvm4InitES1_S1_PNS_6RecordE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='1172' c='_ZL9ItemApplyPN4llvm4InitES1_S1_PNS_6RecordE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='1172' c='_ZL9ItemApplyPN4llvm4InitES1_S1_PNS_6RecordE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='1172' c='_ZL9ItemApplyPN4llvm4InitES1_S1_PNS_6RecordE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='1178' c='_ZL15ForeachDagApplyPN4llvm4InitEPNS_7DagInitES1_PNS_6RecordE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='1178' c='_ZL15ForeachDagApplyPN4llvm4InitEPNS_7DagInitES1_PNS_6RecordE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='1178' c='_ZL15ForeachDagApplyPN4llvm4InitEPNS_7DagInitES1_PNS_6RecordE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='1181' c='_ZL15ForeachDagApplyPN4llvm4InitEPNS_7DagInitES1_PNS_6RecordE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='1185' c='_ZL15ForeachDagApplyPN4llvm4InitEPNS_7DagInitES1_PNS_6RecordE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='1187' c='_ZL15ForeachDagApplyPN4llvm4InitEPNS_7DagInitES1_PNS_6RecordE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='1188' c='_ZL15ForeachDagApplyPN4llvm4InitEPNS_7DagInitES1_PNS_6RecordE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='1207' c='_ZL13ForeachHelperPN4llvm4InitES1_S1_PNS_5RecTyEPNS_6RecordE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='1207' c='_ZL13ForeachHelperPN4llvm4InitES1_S1_PNS_5RecTyEPNS_6RecordE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='1207' c='_ZL13ForeachHelperPN4llvm4InitES1_S1_PNS_5RecTyEPNS_6RecordE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='1207' c='_ZL13ForeachHelperPN4llvm4InitES1_S1_PNS_5RecTyEPNS_6RecordE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='1213' c='_ZL13ForeachHelperPN4llvm4InitES1_S1_PNS_5RecTyEPNS_6RecordE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='1215' c='_ZL13ForeachHelperPN4llvm4InitES1_S1_PNS_5RecTyEPNS_6RecordE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='1216' c='_ZL13ForeachHelperPN4llvm4InitES1_S1_PNS_5RecTyEPNS_6RecordE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='1228' c='_ZL12FilterHelperPN4llvm4InitES1_S1_PNS_5RecTyEPNS_6RecordE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='1228' c='_ZL12FilterHelperPN4llvm4InitES1_S1_PNS_5RecTyEPNS_6RecordE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='1228' c='_ZL12FilterHelperPN4llvm4InitES1_S1_PNS_5RecTyEPNS_6RecordE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='1228' c='_ZL12FilterHelperPN4llvm4InitES1_S1_PNS_5RecTyEPNS_6RecordE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='1231' c='_ZL12FilterHelperPN4llvm4InitES1_S1_PNS_5RecTyEPNS_6RecordE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='1233' c='_ZL12FilterHelperPN4llvm4InitES1_S1_PNS_5RecTyEPNS_6RecordE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='1234' c='_ZL12FilterHelperPN4llvm4InitES1_S1_PNS_5RecTyEPNS_6RecordE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='1251' c='_ZNK4llvm10TernOpInit4FoldEPNS_6RecordE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='1298' c='_ZNK4llvm10TernOpInit4FoldEPNS_6RecordE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='1304' c='_ZNK4llvm10TernOpInit4FoldEPNS_6RecordE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='1329' c='_ZNK4llvm10TernOpInit4FoldEPNS_6RecordE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='1332' c='_ZNK4llvm10TernOpInit4FoldEPNS_6RecordE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='1333' c='_ZNK4llvm10TernOpInit4FoldEPNS_6RecordE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='1368' c='_ZNK4llvm10TernOpInit17resolveReferencesERNS_8ResolverE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='1369' c='_ZNK4llvm10TernOpInit17resolveReferencesERNS_8ResolverE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='1381' c='_ZNK4llvm10TernOpInit17resolveReferencesERNS_8ResolverE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='1382' c='_ZNK4llvm10TernOpInit17resolveReferencesERNS_8ResolverE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='1414' c='_ZL17ProfileFoldOpInitRN4llvm16FoldingSetNodeIDEPNS_4InitES3_S3_S3_S3_PNS_5RecTyE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='1414' c='_ZL17ProfileFoldOpInitRN4llvm16FoldingSetNodeIDEPNS_4InitES3_S3_S3_S3_PNS_5RecTyE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='1415' c='_ZL17ProfileFoldOpInitRN4llvm16FoldingSetNodeIDEPNS_4InitES3_S3_S3_S3_PNS_5RecTyE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='1415' c='_ZL17ProfileFoldOpInitRN4llvm16FoldingSetNodeIDEPNS_4InitES3_S3_S3_S3_PNS_5RecTyE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='1415' c='_ZL17ProfileFoldOpInitRN4llvm16FoldingSetNodeIDEPNS_4InitES3_S3_S3_S3_PNS_5RecTyE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='1425' c='_ZN4llvm10FoldOpInit3getEPNS_4InitES2_S2_S2_S2_PNS_5RecTyE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='1425' c='_ZN4llvm10FoldOpInit3getEPNS_4InitES2_S2_S2_S2_PNS_5RecTyE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='1425' c='_ZN4llvm10FoldOpInit3getEPNS_4InitES2_S2_S2_S2_PNS_5RecTyE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='1425' c='_ZN4llvm10FoldOpInit3getEPNS_4InitES2_S2_S2_S2_PNS_5RecTyE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='1426' c='_ZN4llvm10FoldOpInit3getEPNS_4InitES2_S2_S2_S2_PNS_5RecTyE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='1445' c='_ZNK4llvm10FoldOpInit4FoldEPNS_6RecordE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='1447' c='_ZNK4llvm10FoldOpInit4FoldEPNS_6RecordE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='1448' c='_ZNK4llvm10FoldOpInit4FoldEPNS_6RecordE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='1459' c='_ZNK4llvm10FoldOpInit17resolveReferencesERNS_8ResolverE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='1460' c='_ZNK4llvm10FoldOpInit17resolveReferencesERNS_8ResolverE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='1461' c='_ZNK4llvm10FoldOpInit17resolveReferencesERNS_8ResolverE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='1465' c='_ZNK4llvm10FoldOpInit17resolveReferencesERNS_8ResolverE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='1474' c='_ZNK4llvm10FoldOpInit6getBitEj'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='1486' c='_ZL16ProfileIsAOpInitRN4llvm16FoldingSetNodeIDEPNS_5RecTyEPNS_4InitE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='1491' c='_ZN4llvm9IsAOpInit3getEPNS_5RecTyEPNS_4InitE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='1510' c='_ZNK4llvm9IsAOpInit4FoldEv'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='1530' c='_ZNK4llvm9IsAOpInit17resolveReferencesERNS_8ResolverE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='1531' c='_ZNK4llvm9IsAOpInit17resolveReferencesERNS_8ResolverE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='1537' c='_ZNK4llvm9IsAOpInit6getBitEj'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='1557' c='_ZNK4llvm9TypedInit20convertInitializerToEPNS_5RecTyE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='1569' c='_ZNK4llvm9TypedInit26convertInitializerBitRangeENS_8ArrayRefIjEE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='1574' c='_ZNK4llvm9TypedInit26convertInitializerBitRangeENS_8ArrayRefIjEE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='1585' c='_ZNK4llvm9TypedInit9getCastToEPNS_5RecTyE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='1590' c='_ZNK4llvm9TypedInit9getCastToEPNS_5RecTyE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='1603' c='_ZNK4llvm9TypedInit20convertInitListSliceENS_8ArrayRefIjEE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='1610' c='_ZNK4llvm9TypedInit20convertInitListSliceENS_8ArrayRefIjEE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='1620' c='_ZN4llvm7VarInit3getENS_9StringRefEPNS_5RecTyE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='1624' c='_ZN4llvm7VarInit3getEPNS_4InitEPNS_5RecTyE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='1625' c='_ZN4llvm7VarInit3getEPNS_4InitEPNS_5RecTyE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='1641' c='_ZNK4llvm7VarInit6getBitEj'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='1647' c='_ZNK4llvm7VarInit17resolveReferencesERNS_8ResolverE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='1648' c='_ZNK4llvm7VarInit17resolveReferencesERNS_8ResolverE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='1669' c='_ZNK4llvm10VarBitInit17resolveReferencesERNS_8ResolverE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='1670' c='_ZNK4llvm10VarBitInit17resolveReferencesERNS_8ResolverE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='1693' c='_ZNK4llvm18VarListElementInit17resolveReferencesERNS_8ResolverE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='1694' c='_ZNK4llvm18VarListElementInit17resolveReferencesERNS_8ResolverE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='1706' c='_ZNK4llvm18VarListElementInit6getBitEj'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='1719' c='_ZNK4llvm7DefInit20convertInitializerToEPNS_5RecTyE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='1736' c='_ZL17ProfileVarDefInitRN4llvm16FoldingSetNodeIDEPNS_6RecordENS_8ArrayRefIPNS_4InitEEE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='1740' c='_ZL17ProfileVarDefInitRN4llvm16FoldingSetNodeIDEPNS_6RecordENS_8ArrayRefIPNS_4InitEEE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='1744' c='_ZN4llvm10VarDefInit3getEPNS_6RecordENS_8ArrayRefIPNS_4InitEEE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='1754' c='_ZN4llvm10VarDefInit3getEPNS_6RecordENS_8ArrayRefIPNS_4InitEEE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='1758' c='_ZN4llvm10VarDefInit3getEPNS_6RecordENS_8ArrayRefIPNS_4InitEEE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='1780' c='_ZN4llvm10VarDefInit11instantiateEv'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='1813' c='_ZNK4llvm10VarDefInit17resolveReferencesERNS_8ResolverE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='1816' c='_ZNK4llvm10VarDefInit17resolveReferencesERNS_8ResolverE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='1819' c='_ZNK4llvm10VarDefInit17resolveReferencesERNS_8ResolverE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='1820' c='_ZNK4llvm10VarDefInit17resolveReferencesERNS_8ResolverE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='1834' c='_ZNK4llvm10VarDefInit4FoldEv'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='1839' c='_ZNK4llvm10VarDefInit4FoldEv'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='1850' c='_ZNK4llvm10VarDefInit11getAsStringB5cxx11Ev'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='1858' c='_ZN4llvm9FieldInit3getEPNS_4InitEPNS_10StringInitE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='1859' c='_ZN4llvm9FieldInit3getEPNS_4InitEPNS_10StringInitE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='1869' c='_ZNK4llvm9FieldInit6getBitEj'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='1875' c='_ZNK4llvm9FieldInit17resolveReferencesERNS_8ResolverE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='1876' c='_ZNK4llvm9FieldInit17resolveReferencesERNS_8ResolverE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='1882' c='_ZNK4llvm9FieldInit4FoldEPNS_6RecordE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='1890' c='_ZNK4llvm9FieldInit4FoldEPNS_6RecordE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='1899' c='_ZNK4llvm9FieldInit10isConcreteEv'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='1906' c='_ZL17ProfileCondOpInitRN4llvm16FoldingSetNodeIDENS_8ArrayRefIPNS_4InitEEES5_PKNS_5RecTyE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='1907' c='_ZL17ProfileCondOpInitRN4llvm16FoldingSetNodeIDENS_8ArrayRefIPNS_4InitEEES5_PKNS_5RecTyE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='1923' c='_ZNK4llvm10CondOpInit7ProfileERNS_16FoldingSetNodeIDE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='1924' c='_ZNK4llvm10CondOpInit7ProfileERNS_16FoldingSetNodeIDE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='1929' c='_ZN4llvm10CondOpInit3getENS_8ArrayRefIPNS_4InitEEES4_PNS_5RecTyE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='1930' c='_ZN4llvm10CondOpInit3getENS_8ArrayRefIPNS_4InitEEES4_PNS_5RecTyE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='1942' c='_ZN4llvm10CondOpInit3getENS_8ArrayRefIPNS_4InitEEES4_PNS_5RecTyE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='1947' c='_ZN4llvm10CondOpInit3getENS_8ArrayRefIPNS_4InitEEES4_PNS_5RecTyE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='1949' c='_ZN4llvm10CondOpInit3getENS_8ArrayRefIPNS_4InitEEES4_PNS_5RecTyE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='1954' c='_ZNK4llvm10CondOpInit17resolveReferencesERNS_8ResolverE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='1955' c='_ZNK4llvm10CondOpInit17resolveReferencesERNS_8ResolverE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='1957' c='_ZNK4llvm10CondOpInit17resolveReferencesERNS_8ResolverE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='1958' c='_ZNK4llvm10CondOpInit17resolveReferencesERNS_8ResolverE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='1963' c='_ZNK4llvm10CondOpInit17resolveReferencesERNS_8ResolverE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='1964' c='_ZNK4llvm10CondOpInit17resolveReferencesERNS_8ResolverE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='1965' c='_ZNK4llvm10CondOpInit17resolveReferencesERNS_8ResolverE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='1977' c='_ZNK4llvm10CondOpInit4FoldEPNS_6RecordE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='1979' c='_ZNK4llvm10CondOpInit4FoldEPNS_6RecordE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='1980' c='_ZNK4llvm10CondOpInit4FoldEPNS_6RecordE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='1998' c='_ZNK4llvm10CondOpInit10isConcreteEv'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='2002' c='_ZNK4llvm10CondOpInit10isConcreteEv'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='2010' c='_ZNK4llvm10CondOpInit10isCompleteEv'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='2014' c='_ZNK4llvm10CondOpInit10isCompleteEv'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='2032' c='_ZNK4llvm10CondOpInit6getBitEj'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='2036' c='_ZL14ProfileDagInitRN4llvm16FoldingSetNodeIDEPNS_4InitEPNS_10StringInitENS_8ArrayRefIS3_EENS6_IS5_EE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='2037' c='_ZL14ProfileDagInitRN4llvm16FoldingSetNodeIDEPNS_4InitEPNS_10StringInitENS_8ArrayRefIS3_EENS6_IS5_EE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='2053' c='_ZN4llvm7DagInit3getEPNS_4InitEPNS_10StringInitENS_8ArrayRefIS2_EENS5_IS4_EE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='2053' c='_ZN4llvm7DagInit3getEPNS_4InitEPNS_10StringInitENS_8ArrayRefIS2_EENS5_IS4_EE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='2064' c='_ZN4llvm7DagInit3getEPNS_4InitEPNS_10StringInitENS_8ArrayRefIS2_EENS5_IS4_EE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='2067' c='_ZN4llvm7DagInit3getEPNS_4InitEPNS_10StringInitENS_8ArrayRefIS2_EENS5_IS4_EE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='2075' c='_ZN4llvm7DagInit3getEPNS_4InitEPNS_10StringInitENS_8ArrayRefISt4pairIS2_S4_EEE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='2076' c='_ZN4llvm7DagInit3getEPNS_4InitEPNS_10StringInitENS_8ArrayRefISt4pairIS2_S4_EEE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='2077' c='_ZN4llvm7DagInit3getEPNS_4InitEPNS_10StringInitENS_8ArrayRefISt4pairIS2_S4_EEE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='2089' c='_ZNK4llvm7DagInit7ProfileERNS_16FoldingSetNodeIDE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='2099' c='_ZNK4llvm7DagInit17resolveReferencesERNS_8ResolverE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='2100' c='_ZNK4llvm7DagInit17resolveReferencesERNS_8ResolverE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='2103' c='_ZNK4llvm7DagInit17resolveReferencesERNS_8ResolverE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='2104' c='_ZNK4llvm7DagInit17resolveReferencesERNS_8ResolverE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='2109' c='_ZNK4llvm7DagInit17resolveReferencesERNS_8ResolverE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='2119' c='_ZNK4llvm7DagInit10isConcreteEv'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='2145' c='_ZN4llvm9RecordValC1EPNS_4InitEPNS_5RecTyENS0_9FieldKindE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='2153' c='_ZN4llvm9RecordValC1EPNS_4InitENS_5SMLocEPNS_5RecTyENS0_9FieldKindE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='2178' c='_ZN4llvm9RecordVal8setValueEPNS_4InitE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='2186' c='_ZN4llvm9RecordVal8setValueEPNS_4InitE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='2202' c='_ZN4llvm9RecordVal8setValueEPNS_4InitENS_5SMLocE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='2211' c='_ZN4llvm9RecordVal8setValueEPNS_4InitENS_5SMLocE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='2262' c='_ZN4llvm6Record7setNameEPNS_4InitE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='2310' c='_ZN4llvm6Record17resolveReferencesERNS_8ResolverEPKNS_9RecordValE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='2311' c='_ZN4llvm6Record17resolveReferencesERNS_8ResolverEPKNS_9RecordValE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='2327' c='_ZN4llvm6Record17resolveReferencesERNS_8ResolverEPKNS_9RecordValE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='2328' c='_ZN4llvm6Record17resolveReferencesERNS_8ResolverEPKNS_9RecordValE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='2348' c='_ZN4llvmlsERNS_11raw_ostreamERKNS_6RecordE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='2352' c='_ZN4llvmlsERNS_11raw_ostreamERKNS_6RecordE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='2389' c='_ZNK4llvm6Record12getValueInitENS_9StringRefE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='2449' c='_ZNK4llvm6Record20getValueAsListOfDefsENS_9StringRefE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='2477' c='_ZNK4llvm6Record20getValueAsListOfIntsENS_9StringRefE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='2493' c='_ZNK4llvm6Record23getValueAsListOfStringsENS_9StringRefE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='2590' c='_ZN4llvm12RecordKeeper19getNewAnonymousNameEv'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='2670' c='_ZN4llvm11MapResolver7resolveEPNS_4InitE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='2670' c='_ZN4llvm11MapResolver7resolveEPNS_4InitE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='2675' c='_ZN4llvm11MapResolver7resolveEPNS_4InitE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='2688' c='_ZN4llvm14RecordResolver7resolveEPNS_4InitE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='2688' c='_ZN4llvm14RecordResolver7resolveEPNS_4InitE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='2689' c='_ZN4llvm14RecordResolver7resolveEPNS_4InitE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='2693' c='_ZN4llvm14RecordResolver7resolveEPNS_4InitE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='2711' c='_ZN4llvm23TrackUnresolvedResolver7resolveEPNS_4InitE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='2711' c='_ZN4llvm23TrackUnresolvedResolver7resolveEPNS_4InitE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='2712' c='_ZN4llvm23TrackUnresolvedResolver7resolveEPNS_4InitE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='2731' c='_ZN4llvm20HasReferenceResolver7resolveEPNS_4InitE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='2731' c='_ZN4llvm20HasReferenceResolver7resolveEPNS_4InitE'/>
<size>16</size>
<fun r='_ZN4llvm4Init6anchorEv'/>
<use f='llvm/llvm/lib/TableGen/SetTheory.cpp' l='282' c='_ZN4llvm9SetTheory8evaluateEPNS_4InitERNS_14SmallSetVectorIPNS_6RecordELj16EEENS_8ArrayRefINS_5SMLocEEE'/>
<size>16</size>
<use f='llvm/llvm/lib/TableGen/TGParser.cpp' l='41'/>
<use f='llvm/llvm/lib/TableGen/TGParser.cpp' l='51'/>
<use f='llvm/llvm/lib/TableGen/TGParser.cpp' l='76' c='_ZL17checkBitsConcreteRN4llvm6RecordERKNS_9RecordValE'/>
<use f='llvm/llvm/lib/TableGen/TGParser.cpp' l='101' c='_ZL13checkConcreteRN4llvm6RecordE'/>
<use f='llvm/llvm/lib/TableGen/TGParser.cpp' l='116' c='_ZL11QualifyNameRN4llvm6RecordEPNS_10MultiClassEPNS_4InitENS_9StringRefE'/>
<use f='llvm/llvm/lib/TableGen/TGParser.cpp' l='117' c='_ZL11QualifyNameRN4llvm6RecordEPNS_10MultiClassEPNS_4InitENS_9StringRefE'/>
<use f='llvm/llvm/lib/TableGen/TGParser.cpp' l='118' c='_ZL11QualifyNameRN4llvm6RecordEPNS_10MultiClassEPNS_4InitENS_9StringRefE'/>
<use f='llvm/llvm/lib/TableGen/TGParser.cpp' l='122' c='_ZL11QualifyNameRN4llvm6RecordEPNS_10MultiClassEPNS_4InitENS_9StringRefE'/>
<use f='llvm/llvm/lib/TableGen/TGParser.cpp' l='133' c='_ZL27QualifiedNameOfImplicitNameRN4llvm6RecordEPNS_10MultiClassE'/>
<use f='llvm/llvm/lib/TableGen/TGParser.cpp' l='138' c='_ZL27QualifiedNameOfImplicitNamePN4llvm10MultiClassE'/>
<use f='llvm/llvm/lib/TableGen/TGParser.cpp' l='161' c='_ZN4llvm8TGParser8SetValueEPNS_6RecordENS_5SMLocEPNS_4InitENS_8ArrayRefIjEES5_b'/>
<use f='llvm/llvm/lib/TableGen/TGParser.cpp' l='162' c='_ZN4llvm8TGParser8SetValueEPNS_6RecordENS_5SMLocEPNS_4InitENS_8ArrayRefIjEES5_b'/>
<use f='llvm/llvm/lib/TableGen/TGParser.cpp' l='191' c='_ZN4llvm8TGParser8SetValueEPNS_6RecordENS_5SMLocEPNS_4InitENS_8ArrayRefIjEES5_b'/>
<use f='llvm/llvm/lib/TableGen/TGParser.cpp' l='195' c='_ZN4llvm8TGParser8SetValueEPNS_6RecordENS_5SMLocEPNS_4InitENS_8ArrayRefIjEES5_b'/>
<use f='llvm/llvm/lib/TableGen/TGParser.cpp' l='237' c='_ZN4llvm8TGParser11AddSubClassEPNS_6RecordERNS_17SubClassReferenceE'/>
<use f='llvm/llvm/lib/TableGen/TGParser.cpp' l='266' c='_ZN4llvm8TGParser11AddSubClassEPNS_6RecordERNS_17SubClassReferenceE'/>
<use f='llvm/llvm/lib/TableGen/TGParser.cpp' l='312' c='_ZN4llvm8TGParser16AddSubMultiClassEPNS_10MultiClassERNS_22SubMultiClassReferenceE'/>
<use f='llvm/llvm/lib/TableGen/TGParser.cpp' l='324' c='_ZN4llvm8TGParser16AddSubMultiClassEPNS_10MultiClassERNS_22SubMultiClassReferenceE'/>
<use f='llvm/llvm/lib/TableGen/TGParser.cpp' l='379' c='_ZN4llvm8TGParser7resolveERKNS_11ForeachLoopERNS_11SmallVectorISt4pairIPNS_4InitES7_ELj8EEEbPSt6vectorINS_12RecordsEntryESaISC_EEPNS_5SMLocE'/>
<use f='llvm/llvm/lib/TableGen/TGParser.cpp' l='509' c='_ZN4llvm8TGParser15ParseObjectNameEPNS_10MultiClassE'/>
<use f='llvm/llvm/lib/TableGen/TGParser.cpp' l='526' c='_ZN4llvm8TGParser15ParseObjectNameEPNS_10MultiClassE'/>
<use f='llvm/llvm/lib/TableGen/TGParser.cpp' l='531' c='_ZN4llvm8TGParser15ParseObjectNameEPNS_10MultiClassE'/>
<use f='llvm/llvm/lib/TableGen/TGParser.cpp' l='684' c='_ZN4llvm8TGParser15ParseRangePieceERNS_15SmallVectorImplIjEEPNS_9TypedInitE'/>
<use f='llvm/llvm/lib/TableGen/TGParser.cpp' l='707' c='_ZN4llvm8TGParser15ParseRangePieceERNS_15SmallVectorImplIjEEPNS_9TypedInitE'/>
<use f='llvm/llvm/lib/TableGen/TGParser.cpp' l='851' c='_ZN4llvm8TGParser12ParseIDValueEPNS_6RecordEPNS_10StringInitENS_5SMLocENS0_11IDParseModeE'/>
<use f='llvm/llvm/lib/TableGen/TGParser.cpp' l='859' c='_ZN4llvm8TGParser12ParseIDValueEPNS_6RecordEPNS_10StringInitENS_5SMLocENS0_11IDParseModeE'/>
<use f='llvm/llvm/lib/TableGen/TGParser.cpp' l='877' c='_ZN4llvm8TGParser12ParseIDValueEPNS_6RecordEPNS_10StringInitENS_5SMLocENS0_11IDParseModeE'/>
<use f='llvm/llvm/lib/TableGen/TGParser.cpp' l='892' c='_ZN4llvm8TGParser12ParseIDValueEPNS_6RecordEPNS_10StringInitENS_5SMLocENS0_11IDParseModeE'/>
<use f='llvm/llvm/lib/TableGen/TGParser.cpp' l='909' c='_ZN4llvm8TGParser14ParseOperationEPNS_6RecordEPNS_5RecTyE'/>
<use f='llvm/llvm/lib/TableGen/TGParser.cpp' l='989' c='_ZN4llvm8TGParser14ParseOperationEPNS_6RecordEPNS_5RecTyE'/>
<use f='llvm/llvm/lib/TableGen/TGParser.cpp' l='1032' c='_ZN4llvm8TGParser14ParseOperationEPNS_6RecordEPNS_5RecTyE'/>
<use f='llvm/llvm/lib/TableGen/TGParser.cpp' l='1067' c='_ZN4llvm8TGParser14ParseOperationEPNS_6RecordEPNS_5RecTyE'/>
<use f='llvm/llvm/lib/TableGen/TGParser.cpp' l='1189' c='_ZN4llvm8TGParser14ParseOperationEPNS_6RecordEPNS_5RecTyE'/>
<use f='llvm/llvm/lib/TableGen/TGParser.cpp' l='1346' c='_ZN4llvm8TGParser14ParseOperationEPNS_6RecordEPNS_5RecTyE'/>
<use f='llvm/llvm/lib/TableGen/TGParser.cpp' l='1392' c='_ZN4llvm8TGParser14ParseOperationEPNS_6RecordEPNS_5RecTyE'/>
<use f='llvm/llvm/lib/TableGen/TGParser.cpp' l='1401' c='_ZN4llvm8TGParser14ParseOperationEPNS_6RecordEPNS_5RecTyE'/>
<use f='llvm/llvm/lib/TableGen/TGParser.cpp' l='1411' c='_ZN4llvm8TGParser14ParseOperationEPNS_6RecordEPNS_5RecTyE'/>
<use f='llvm/llvm/lib/TableGen/TGParser.cpp' l='1516' c='_ZN4llvm8TGParser14ParseOperationEPNS_6RecordEPNS_5RecTyE'/>
<use f='llvm/llvm/lib/TableGen/TGParser.cpp' l='1532' c='_ZN4llvm8TGParser14ParseOperationEPNS_6RecordEPNS_5RecTyE'/>
<use f='llvm/llvm/lib/TableGen/TGParser.cpp' l='1560' c='_ZN4llvm8TGParser14ParseOperationEPNS_6RecordEPNS_5RecTyE'/>
<use f='llvm/llvm/lib/TableGen/TGParser.cpp' l='1578' c='_ZN4llvm8TGParser14ParseOperationEPNS_6RecordEPNS_5RecTyE'/>
<use f='llvm/llvm/lib/TableGen/TGParser.cpp' l='1604' c='_ZN4llvm8TGParser14ParseOperationEPNS_6RecordEPNS_5RecTyE'/>
<use f='llvm/llvm/lib/TableGen/TGParser.cpp' l='1668' c='_ZN4llvm8TGParser20ParseOperationSubstrEPNS_6RecordEPNS_5RecTyE'/>
<use f='llvm/llvm/lib/TableGen/TGParser.cpp' l='1679' c='_ZN4llvm8TGParser20ParseOperationSubstrEPNS_6RecordEPNS_5RecTyE'/>
<use f='llvm/llvm/lib/TableGen/TGParser.cpp' l='1689' c='_ZN4llvm8TGParser20ParseOperationSubstrEPNS_6RecordEPNS_5RecTyE'/>
<use f='llvm/llvm/lib/TableGen/TGParser.cpp' l='1694' c='_ZN4llvm8TGParser20ParseOperationSubstrEPNS_6RecordEPNS_5RecTyE'/>
<use f='llvm/llvm/lib/TableGen/TGParser.cpp' l='1757' c='_ZN4llvm8TGParser27ParseOperationForEachFilterEPNS_6RecordEPNS_5RecTyE'/>
<use f='llvm/llvm/lib/TableGen/TGParser.cpp' l='1771' c='_ZN4llvm8TGParser27ParseOperationForEachFilterEPNS_6RecordEPNS_5RecTyE'/>
<use f='llvm/llvm/lib/TableGen/TGParser.cpp' l='1786' c='_ZN4llvm8TGParser27ParseOperationForEachFilterEPNS_6RecordEPNS_5RecTyE'/>
<use f='llvm/llvm/lib/TableGen/TGParser.cpp' l='1852' c='_ZN4llvm8TGParser27ParseOperationForEachFilterEPNS_6RecordEPNS_5RecTyE'/>
<use f='llvm/llvm/lib/TableGen/TGParser.cpp' l='1880' c='_ZN4llvm8TGParser18ParseOperationCondEPNS_6RecordEPNS_5RecTyE'/>
<use f='llvm/llvm/lib/TableGen/TGParser.cpp' l='1889' c='_ZN4llvm8TGParser18ParseOperationCondEPNS_6RecordEPNS_5RecTyE'/>
<use f='llvm/llvm/lib/TableGen/TGParser.cpp' l='1890' c='_ZN4llvm8TGParser18ParseOperationCondEPNS_6RecordEPNS_5RecTyE'/>
<use f='llvm/llvm/lib/TableGen/TGParser.cpp' l='1895' c='_ZN4llvm8TGParser18ParseOperationCondEPNS_6RecordEPNS_5RecTyE'/>
<use f='llvm/llvm/lib/TableGen/TGParser.cpp' l='1926' c='_ZN4llvm8TGParser18ParseOperationCondEPNS_6RecordEPNS_5RecTyE'/>
<use f='llvm/llvm/lib/TableGen/TGParser.cpp' l='1980' c='_ZN4llvm8TGParser16ParseSimpleValueEPNS_6RecordEPNS_5RecTyENS0_11IDParseModeE'/>
<use f='llvm/llvm/lib/TableGen/TGParser.cpp' l='1982' c='_ZN4llvm8TGParser16ParseSimpleValueEPNS_6RecordEPNS_5RecTyENS0_11IDParseModeE'/>
<use f='llvm/llvm/lib/TableGen/TGParser.cpp' l='2000' c='_ZN4llvm8TGParser16ParseSimpleValueEPNS_6RecordEPNS_5RecTyENS0_11IDParseModeE'/>
<use f='llvm/llvm/lib/TableGen/TGParser.cpp' l='2049' c='_ZN4llvm8TGParser16ParseSimpleValueEPNS_6RecordEPNS_5RecTyENS0_11IDParseModeE'/>
<use f='llvm/llvm/lib/TableGen/TGParser.cpp' l='2059' c='_ZN4llvm8TGParser16ParseSimpleValueEPNS_6RecordEPNS_5RecTyENS0_11IDParseModeE'/>
<use f='llvm/llvm/lib/TableGen/TGParser.cpp' l='2095' c='_ZN4llvm8TGParser16ParseSimpleValueEPNS_6RecordEPNS_5RecTyENS0_11IDParseModeE'/>
<use f='llvm/llvm/lib/TableGen/TGParser.cpp' l='2106' c='_ZN4llvm8TGParser16ParseSimpleValueEPNS_6RecordEPNS_5RecTyENS0_11IDParseModeE'/>
<use f='llvm/llvm/lib/TableGen/TGParser.cpp' l='2131' c='_ZN4llvm8TGParser16ParseSimpleValueEPNS_6RecordEPNS_5RecTyENS0_11IDParseModeE'/>
<use f='llvm/llvm/lib/TableGen/TGParser.cpp' l='2144' c='_ZN4llvm8TGParser16ParseSimpleValueEPNS_6RecordEPNS_5RecTyENS0_11IDParseModeE'/>
<use f='llvm/llvm/lib/TableGen/TGParser.cpp' l='2186' c='_ZN4llvm8TGParser16ParseSimpleValueEPNS_6RecordEPNS_5RecTyENS0_11IDParseModeE'/>
<use f='llvm/llvm/lib/TableGen/TGParser.cpp' l='2241' c='_ZN4llvm8TGParser16ParseSimpleValueEPNS_6RecordEPNS_5RecTyENS0_11IDParseModeE'/>
<use f='llvm/llvm/lib/TableGen/TGParser.cpp' l='2255' c='_ZN4llvm8TGParser16ParseSimpleValueEPNS_6RecordEPNS_5RecTyENS0_11IDParseModeE'/>
<use f='llvm/llvm/lib/TableGen/TGParser.cpp' l='2320' c='_ZN4llvm8TGParser10ParseValueEPNS_6RecordEPNS_5RecTyENS0_11IDParseModeE'/>
<use f='llvm/llvm/lib/TableGen/TGParser.cpp' l='2321' c='_ZN4llvm8TGParser10ParseValueEPNS_6RecordEPNS_5RecTyENS0_11IDParseModeE'/>
<use f='llvm/llvm/lib/TableGen/TGParser.cpp' l='2411' c='_ZN4llvm8TGParser10ParseValueEPNS_6RecordEPNS_5RecTyENS0_11IDParseModeE'/>
<use f='llvm/llvm/lib/TableGen/TGParser.cpp' l='2450' c='_ZN4llvm8TGParser10ParseValueEPNS_6RecordEPNS_5RecTyENS0_11IDParseModeE'/>
<use f='llvm/llvm/lib/TableGen/TGParser.cpp' l='2487' c='_ZN4llvm8TGParser15ParseDagArgListERNS_15SmallVectorImplISt4pairIPNS_4InitEPNS_10StringInitEEEEPNS_6RecordE'/>
<use f='llvm/llvm/lib/TableGen/TGParser.cpp' l='2499' c='_ZN4llvm8TGParser15ParseDagArgListERNS_15SmallVectorImplISt4pairIPNS_4InitEPNS_10StringInitEEEEPNS_6RecordE'/>
<use f='llvm/llvm/lib/TableGen/TGParser.cpp' l='2530' c='_ZN4llvm8TGParser14ParseValueListERNS_15SmallVectorImplIPNS_4InitEEEPNS_6RecordES7_PNS_5RecTyE'/>
<use f='llvm/llvm/lib/TableGen/TGParser.cpp' l='2535' c='_ZN4llvm8TGParser14ParseValueListERNS_15SmallVectorImplIPNS_4InitEEEPNS_6RecordES7_PNS_5RecTyE'/>
<use f='llvm/llvm/lib/TableGen/TGParser.cpp' l='2562' c='_ZN4llvm8TGParser14ParseValueListERNS_15SmallVectorImplIPNS_4InitEEEPNS_6RecordES7_PNS_5RecTyE'/>
<use f='llvm/llvm/lib/TableGen/TGParser.cpp' l='2591' c='_ZN4llvm8TGParser16ParseDeclarationEPNS_6RecordEb'/>
<use f='llvm/llvm/lib/TableGen/TGParser.cpp' l='2611' c='_ZN4llvm8TGParser16ParseDeclarationEPNS_6RecordEb'/>
<use f='llvm/llvm/lib/TableGen/TGParser.cpp' l='2633' c='_ZN4llvm8TGParser16ParseDeclarationEPNS_6RecordEb'/>
<use f='llvm/llvm/lib/TableGen/TGParser.cpp' l='2653' c='_ZN4llvm8TGParser23ParseForeachDeclarationERPNS_4InitE'/>
<use f='llvm/llvm/lib/TableGen/TGParser.cpp' l='2659' c='_ZN4llvm8TGParser23ParseForeachDeclarationERPNS_4InitE'/>
<use f='llvm/llvm/lib/TableGen/TGParser.cpp' l='2684' c='_ZN4llvm8TGParser23ParseForeachDeclarationERPNS_4InitE'/>
<use f='llvm/llvm/lib/TableGen/TGParser.cpp' l='2717' c='_ZN4llvm8TGParser23ParseForeachDeclarationERPNS_4InitE'/>
<use f='llvm/llvm/lib/TableGen/TGParser.cpp' l='2743' c='_ZN4llvm8TGParser20ParseTemplateArgListEPNS_6RecordE'/>
<use f='llvm/llvm/lib/TableGen/TGParser.cpp' l='2817' c='_ZN4llvm8TGParser13ParseBodyItemEPNS_6RecordE'/>
<use f='llvm/llvm/lib/TableGen/TGParser.cpp' l='2932' c='_ZN4llvm8TGParser8ParseDefEPNS_10MultiClassE'/>
<use f='llvm/llvm/lib/TableGen/TGParser.cpp' l='3017' c='_ZN4llvm8TGParser11ParseDefvarEv'/>
<use f='llvm/llvm/lib/TableGen/TGParser.cpp' l='3045' c='_ZN4llvm8TGParser12ParseForeachEPNS_10MultiClassE'/>
<use f='llvm/llvm/lib/TableGen/TGParser.cpp' l='3099' c='_ZN4llvm8TGParser7ParseIfEPNS_10MultiClassE'/>
<use f='llvm/llvm/lib/TableGen/TGParser.cpp' l='3118' c='_ZN4llvm8TGParser7ParseIfEPNS_10MultiClassE'/>
<use f='llvm/llvm/lib/TableGen/TGParser.cpp' l='3140' c='_ZN4llvm8TGParser7ParseIfEPNS_10MultiClassE'/>
<use f='llvm/llvm/lib/TableGen/TGParser.cpp' l='3199' c='_ZN4llvm8TGParser11ParseAssertEPNS_10MultiClassEPNS_6RecordE'/>
<use f='llvm/llvm/lib/TableGen/TGParser.cpp' l='3208' c='_ZN4llvm8TGParser11ParseAssertEPNS_10MultiClassEPNS_6RecordE'/>
<use f='llvm/llvm/lib/TableGen/TGParser.cpp' l='3295' c='_ZN4llvm8TGParser12ParseLetListERNS_15SmallVectorImplINS_9LetRecordEEE'/>
<use f='llvm/llvm/lib/TableGen/TGParser.cpp' l='3465' c='_ZN4llvm8TGParser9ParseDefmEPNS_10MultiClassE'/>
<use f='llvm/llvm/lib/TableGen/TGParser.cpp' l='3500' c='_ZN4llvm8TGParser9ParseDefmEPNS_10MultiClassE'/>
<use f='llvm/llvm/lib/TableGen/TGParser.cpp' l='3503' c='_ZN4llvm8TGParser9ParseDefmEPNS_10MultiClassE'/>
<use f='llvm/llvm/lib/TableGen/TGParser.cpp' l='3513' c='_ZN4llvm8TGParser9ParseDefmEPNS_10MultiClassE'/>
<use f='llvm/llvm/lib/TableGen/TGParser.cpp' l='3646' c='_ZN4llvm8TGParser11CheckAssertENS_5SMLocEPNS_4InitES3_'/>
<use f='llvm/llvm/lib/TableGen/TGParser.cpp' l='3646' c='_ZN4llvm8TGParser11CheckAssertENS_5SMLocEPNS_4InitES3_'/>
<use f='llvm/llvm/lib/TableGen/TGParser.cpp' l='3669' c='_ZN4llvm8TGParser18CheckRecordAssertsERNS_6RecordE'/>
<use f='llvm/llvm/lib/TableGen/TGParser.cpp' l='3670' c='_ZN4llvm8TGParser18CheckRecordAssertsERNS_6RecordE'/>
<size>16</size>
<use f='llvm/llvm/utils/TableGen/AsmMatcherEmitter.cpp' l='1308' c='_ZN12_GLOBAL__N_114AsmMatcherInfo20buildRegisterClassesERN4llvm15SmallPtrSetImplIPNS1_6RecordEEE'/>
<use f='llvm/llvm/utils/TableGen/AsmMatcherEmitter.cpp' l='1312' c='_ZN12_GLOBAL__N_114AsmMatcherInfo20buildRegisterClassesERN4llvm15SmallPtrSetImplIPNS1_6RecordEEE'/>
<use f='llvm/llvm/utils/TableGen/AsmMatcherEmitter.cpp' l='1359' c='_ZN12_GLOBAL__N_114AsmMatcherInfo19buildOperandClassesEv'/>
<use f='llvm/llvm/utils/TableGen/AsmMatcherEmitter.cpp' l='1377' c='_ZN12_GLOBAL__N_114AsmMatcherInfo19buildOperandClassesEv'/>
<use f='llvm/llvm/utils/TableGen/AsmMatcherEmitter.cpp' l='1386' c='_ZN12_GLOBAL__N_114AsmMatcherInfo19buildOperandClassesEv'/>
<use f='llvm/llvm/utils/TableGen/AsmMatcherEmitter.cpp' l='1395' c='_ZN12_GLOBAL__N_114AsmMatcherInfo19buildOperandClassesEv'/>
<use f='llvm/llvm/utils/TableGen/AsmMatcherEmitter.cpp' l='1400' c='_ZN12_GLOBAL__N_114AsmMatcherInfo19buildOperandClassesEv'/>
<use f='llvm/llvm/utils/TableGen/AsmMatcherEmitter.cpp' l='1403' c='_ZN12_GLOBAL__N_114AsmMatcherInfo19buildOperandClassesEv'/>
<use f='llvm/llvm/utils/TableGen/AsmMatcherEmitter.cpp' l='1411' c='_ZN12_GLOBAL__N_114AsmMatcherInfo19buildOperandClassesEv'/>
<use f='llvm/llvm/utils/TableGen/AsmMatcherEmitter.cpp' l='1416' c='_ZN12_GLOBAL__N_114AsmMatcherInfo19buildOperandClassesEv'/>
<size>16</size>
<use f='llvm/llvm/utils/TableGen/CodeGenDAGPatterns.h' l='644'/>
<use f='llvm/llvm/utils/TableGen/CodeGenDAGPatterns.h' l='671' c='_ZN4llvm15TreePatternNodeC1EPNS_4InitEj'/>
<use f='llvm/llvm/utils/TableGen/CodeGenDAGPatterns.h' l='720' c='_ZNK4llvm15TreePatternNode12getLeafValueEv'/>
<use f='llvm/llvm/utils/TableGen/CodeGenDAGPatterns.h' l='975' c='_ZN4llvm11TreePattern16ParseTreePatternEPNS_4InitENS_9StringRefE'/>
<use f='llvm/llvm/utils/TableGen/CodeGenDAGPatterns.cpp' l='984' c='_ZNK4llvm15TreePredicateFn11getPredCodeB5cxx11Ev'/>
<use f='llvm/llvm/utils/TableGen/CodeGenDAGPatterns.cpp' l='1802' c='_ZL17GetNumNodeResultsPN4llvm6RecordERNS_18CodeGenDAGPatternsE'/>
<use f='llvm/llvm/utils/TableGen/CodeGenDAGPatterns.cpp' l='1962' c='_ZN4llvm15TreePatternNode25SubstituteFormalArgumentsERSt3mapINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESt10shared_ptrIS0_ESt4lessIS7_ESaISt4pairIKS7_S9_EEE'/>
<use f='llvm/llvm/utils/TableGen/CodeGenDAGPatterns.cpp' l='2695' c='_ZN4llvm11TreePatternC1EPNS_6RecordEPNS_8ListInitEbRNS_18CodeGenDAGPatternsE'/>
<use f='llvm/llvm/utils/TableGen/CodeGenDAGPatterns.cpp' l='2734' c='_ZN4llvm11TreePattern16ParseTreePatternEPNS_4InitENS_9StringRefE'/>
<use f='llvm/llvm/utils/TableGen/CodeGenDAGPatterns.cpp' l='2745' c='_ZN4llvm11TreePattern16ParseTreePatternEPNS_4InitENS_9StringRefE'/>
<use f='llvm/llvm/utils/TableGen/CodeGenDAGPatterns.cpp' l='2780' c='_ZN4llvm11TreePattern16ParseTreePatternEPNS_4InitENS_9StringRefE'/>
<use f='llvm/llvm/utils/TableGen/CodeGenDAGPatterns.cpp' l='3239' c='_ZN4llvm18CodeGenDAGPatterns20ParseDefaultOperandsEv'/>
<use f='llvm/llvm/utils/TableGen/CodeGenDAGPatterns.cpp' l='3246' c='_ZN4llvm18CodeGenDAGPatterns20ParseDefaultOperandsEv'/>
<use f='llvm/llvm/utils/TableGen/CodeGenDAGPatterns.cpp' l='3608' c='_ZL20hasNullFragReferencePN4llvm8ListInitE'/>
<use f='llvm/llvm/utils/TableGen/CodeGenDAGPatterns.cpp' l='3909' c='_ZN4llvm18CodeGenDAGPatterns12makePredListEPNS_8ListInitE'/>
<size>16</size>
<use f='llvm/llvm/utils/TableGen/CodeGenInstruction.cpp' l='61' c='_ZN4llvm14CGIOperandListC1EPNS_6RecordE'/>
<use f='llvm/llvm/utils/TableGen/CodeGenInstruction.cpp' l='544' c='_ZN4llvm16CodeGenInstAlias15tryAliasOpMatchEPNS_7DagInitEjPNS_6RecordEbNS_8ArrayRefINS_5SMLocEEERNS_13CodeGenTargetERNS0_13ResultOperandE'/>
<size>16</size>
<use f='llvm/llvm/utils/TableGen/CodeGenMapTable.cpp' l='84'/>
<use f='llvm/llvm/utils/TableGen/CodeGenMapTable.cpp' l='134' c='_ZN12_GLOBAL__N_18InstrMapC1EPN4llvm6RecordE'/>
<use f='llvm/llvm/utils/TableGen/CodeGenMapTable.cpp' l='232' c='_ZN12_GLOBAL__N_115MapTableEmitter16buildRowInstrMapEv'/>
<use f='llvm/llvm/utils/TableGen/CodeGenMapTable.cpp' l='234' c='_ZN12_GLOBAL__N_115MapTableEmitter16buildRowInstrMapEv'/>
<use f='llvm/llvm/utils/TableGen/CodeGenMapTable.cpp' l='240' c='_ZN12_GLOBAL__N_115MapTableEmitter16buildRowInstrMapEv'/>
<use f='llvm/llvm/utils/TableGen/CodeGenMapTable.cpp' l='304' c='_ZN12_GLOBAL__N_115MapTableEmitter17getInstrForColumnEPN4llvm6RecordEPNS1_8ListInitE'/>
<use f='llvm/llvm/utils/TableGen/CodeGenMapTable.cpp' l='307' c='_ZN12_GLOBAL__N_115MapTableEmitter17getInstrForColumnEPN4llvm6RecordEPNS1_8ListInitE'/>
<use f='llvm/llvm/utils/TableGen/CodeGenMapTable.cpp' l='308' c='_ZN12_GLOBAL__N_115MapTableEmitter17getInstrForColumnEPN4llvm6RecordEPNS1_8ListInitE'/>
<use f='llvm/llvm/utils/TableGen/CodeGenMapTable.cpp' l='326' c='_ZN12_GLOBAL__N_115MapTableEmitter17getInstrForColumnEPN4llvm6RecordEPNS1_8ListInitE'/>
<use f='llvm/llvm/utils/TableGen/CodeGenMapTable.cpp' l='327' c='_ZN12_GLOBAL__N_115MapTableEmitter17getInstrForColumnEPN4llvm6RecordEPNS1_8ListInitE'/>
<use f='llvm/llvm/utils/TableGen/CodeGenMapTable.cpp' l='329' c='_ZN12_GLOBAL__N_115MapTableEmitter17getInstrForColumnEPN4llvm6RecordEPNS1_8ListInitE'/>
<use f='llvm/llvm/utils/TableGen/CodeGenMapTable.cpp' l='338' c='_ZN12_GLOBAL__N_115MapTableEmitter17getInstrForColumnEPN4llvm6RecordEPNS1_8ListInitE'/>
<use f='llvm/llvm/utils/TableGen/CodeGenMapTable.cpp' l='481' c='_ZN12_GLOBAL__N_115MapTableEmitter18emitTablesWithFuncERN4llvm11raw_ostreamE'/>
<use f='llvm/llvm/utils/TableGen/CodeGenMapTable.cpp' l='502' c='_ZL9emitEnumsRN4llvm11raw_ostreamERNS_12RecordKeeperE'/>
<use f='llvm/llvm/utils/TableGen/CodeGenMapTable.cpp' l='531' c='_ZL9emitEnumsRN4llvm11raw_ostreamERNS_12RecordKeeperE'/>
<use f='llvm/llvm/utils/TableGen/CodeGenMapTable.cpp' l='535' c='_ZL9emitEnumsRN4llvm11raw_ostreamERNS_12RecordKeeperE'/>
<size>16</size>
<use f='llvm/llvm/utils/TableGen/CodeGenRegisters.cpp' l='648' c='_ZN12_GLOBAL__N_113TupleExpander6expandERN4llvm9SetTheoryEPNS1_6RecordERNS1_14SmallSetVectorIS5_Lj16EEE'/>
<size>16</size>
<use f='llvm/llvm/utils/TableGen/CodeGenSchedule.cpp' l='89' c='_ZN12_GLOBAL__N_111InstRegexOp5applyERN4llvm9SetTheoryEPNS1_7DagInitERNS1_14SmallSetVectorIPNS1_6RecordELj16EEENS1_8ArrayRefINS1_5SMLocEEE'/>
<size>16</size>
<use f='llvm/llvm/utils/TableGen/CodeGenTarget.cpp' l='529' c='_ZN4llvm13CodeGenTarget34reverseBitsForLittleEndianEncodingEv'/>
<use f='llvm/llvm/utils/TableGen/CodeGenTarget.cpp' l='533' c='_ZN4llvm13CodeGenTarget34reverseBitsForLittleEndianEncodingEv'/>
<use f='llvm/llvm/utils/TableGen/CodeGenTarget.cpp' l='534' c='_ZN4llvm13CodeGenTarget34reverseBitsForLittleEndianEncodingEv'/>
<size>16</size>
<use f='llvm/llvm/utils/TableGen/FixedLenDecoderEmitter.cpp' l='1842' c='_ZL19populateInstructionRN4llvm13CodeGenTargetERKNS_6RecordERKNS_18CodeGenInstructionEjRSt3mapIjSt6vectorIN12_GLOBAL__N_111OperandInfoESaISB_EESt4less4267922'/>
<use f='llvm/llvm/utils/TableGen/FixedLenDecoderEmitter.cpp' l='1964' c='_ZL19populateInstructionRN4llvm13CodeGenTargetERKNS_6RecordERKNS_18CodeGenInstructionEjRSt3mapIjSt6vectorIN12_GLOBAL__N_111OperandInfoESaISB_EESt4less4267922'/>
<size>16</size>
<use f='llvm/llvm/utils/TableGen/GICombinerEmitter.cpp' l='183' c='_ZN12_GLOBAL__N_111CombineRule23parseInstructionMatcherERKN4llvm13CodeGenTargetEPNS1_10StringInitERKNS1_4InitERNS1_9StringMapISt6vectorINS0_7VarInfoES6956006'/>
<use f='llvm/llvm/utils/TableGen/GICombinerEmitter.cpp' l='187' c='_ZN12_GLOBAL__N_111CombineRule26parseWipMatchOpcodeMatcherERKN4llvm13CodeGenTargetEPNS1_10StringInitERKNS1_4InitE'/>
<use f='llvm/llvm/utils/TableGen/GICombinerEmitter.cpp' l='283' c='_ZN12_GLOBAL__N_113isSpecificDefERKN4llvm4InitENS0_9StringRefE'/>
<use f='llvm/llvm/utils/TableGen/GICombinerEmitter.cpp' l='294' c='_ZN12_GLOBAL__N_116getDefOfSubClassERKN4llvm4InitENS0_9StringRefE'/>
<use f='llvm/llvm/utils/TableGen/GICombinerEmitter.cpp' l='305' c='_ZN12_GLOBAL__N_126getDagWithSpecificOperatorERKN4llvm4InitENS0_9StringRefE'/>
<use f='llvm/llvm/utils/TableGen/GICombinerEmitter.cpp' l='319' c='_ZN12_GLOBAL__N_128getDagWithOperatorOfSubClassERKN4llvm4InitENS0_9StringRefE'/>
<use f='llvm/llvm/utils/TableGen/GICombinerEmitter.cpp' l='398' c='_ZN12_GLOBAL__N_111CombineRule23parseInstructionMatcherERKN4llvm13CodeGenTargetEPNS1_10StringInitERKNS1_4InitERNS1_9StringMapISt6vectorINS0_7VarInfoES6956006'/>
<use f='llvm/llvm/utils/TableGen/GICombinerEmitter.cpp' l='454' c='_ZN12_GLOBAL__N_111CombineRule26parseWipMatchOpcodeMatcherERKN4llvm13CodeGenTargetEPNS1_10StringInitERKNS1_4InitE'/>
<size>16</size>
<use f='llvm/llvm/utils/TableGen/GlobalISelEmitter.cpp' l='244' c='_ZN12_GLOBAL__N_117explainPredicatesB5cxx11EPKN4llvm15TreePatternNodeE'/>
<use f='llvm/llvm/utils/TableGen/GlobalISelEmitter.cpp' l='378' c='_ZN12_GLOBAL__N_122getInitValueAsRegClassEPN4llvm4InitE'/>
<use f='llvm/llvm/utils/TableGen/GlobalISelEmitter.cpp' l='3746' c='_ZN12_GLOBAL__N_117GlobalISelEmitter20addBuiltinPredicatesEPKN4llvm6RecordERKNS1_15TreePredicateFnERNS_18InstructionMatcherERb'/>
<use f='llvm/llvm/utils/TableGen/GlobalISelEmitter.cpp' l='3891' c='_ZN12_GLOBAL__N_117GlobalISelEmitter28createAndImportSelDAGMatcherERNS_11RuleMatcherERNS_18InstructionMatcherEPKN4llvm15TreePatternNodeERj'/>
<use f='llvm/llvm/utils/TableGen/GlobalISelEmitter.cpp' l='3964' c='_ZN12_GLOBAL__N_117GlobalISelEmitter28createAndImportSelDAGMatcherERNS_11RuleMatcherERNS_18InstructionMatcherEPKN4llvm15TreePatternNodeERj'/>
<size>16</size>
<use f='llvm/llvm/utils/TableGen/InstrInfoEmitter.cpp' l='387' c='_ZN12_GLOBAL__N_116InstrInfoEmitter23emitOperandTypeMappingsERN4llvm11raw_ostreamERKNS1_13CodeGenTargetENS1_8ArrayRefIPKNS1_18CodeGenInstructionEEE'/>
<size>16</size>
<use f='llvm/llvm/utils/TableGen/OptParserEmitter.cpp' l='358' c='_ZN4llvm13EmitOptParserERNS_12RecordKeeperERNS_11raw_ostreamE'/>
<use f='llvm/llvm/utils/TableGen/OptParserEmitter.cpp' l='361' c='_ZN4llvm13EmitOptParserERNS_12RecordKeeperERNS_11raw_ostreamE'/>
<size>16</size>
<use f='llvm/llvm/utils/TableGen/RISCVCompressInstEmitter.cpp' l='287' c='_ZL17validateArgsTypesPN4llvm4InitES1_'/>
<use f='llvm/llvm/utils/TableGen/RISCVCompressInstEmitter.cpp' l='287' c='_ZL17validateArgsTypesPN4llvm4InitES1_'/>
<size>16</size>
<use f='llvm/llvm/utils/TableGen/SearchableTableEmitter.cpp' l='37' c='_ZN12_GLOBAL__N_18getAsIntEPN4llvm4InitE'/>
<use f='llvm/llvm/utils/TableGen/SearchableTableEmitter.cpp' l='94'/>
<use f='llvm/llvm/utils/TableGen/SearchableTableEmitter.cpp' l='105'/>
<use f='llvm/llvm/utils/TableGen/SearchableTableEmitter.cpp' l='114' c='_ZN12_GLOBAL__N_122SearchableTableEmitter21primaryRepresentationB5cxx11EN4llvm5SMLocERKNS_12GenericFieldEPNS1_4InitE'/>
<use f='llvm/llvm/utils/TableGen/SearchableTableEmitter.cpp' l='139' c='_ZN12_GLOBAL__N_122SearchableTableEmitter11isIntrinsicEPN4llvm4InitE'/>
<use f='llvm/llvm/utils/TableGen/SearchableTableEmitter.cpp' l='145' c='_ZN12_GLOBAL__N_122SearchableTableEmitter12getIntrinsicEPN4llvm4InitE'/>
<use f='llvm/llvm/utils/TableGen/SearchableTableEmitter.cpp' l='194' c='_ZN12_GLOBAL__N_122SearchableTableEmitter14parseFieldTypeERNS_12GenericFieldEPN4llvm4InitE'/>
<use f='llvm/llvm/utils/TableGen/SearchableTableEmitter.cpp' l='225' c='_ZN12_GLOBAL__N_122SearchableTableEmitter9compareByEPN4llvm6RecordES3_RKNS_11SearchIndexE'/>
<use f='llvm/llvm/utils/TableGen/SearchableTableEmitter.cpp' l='226' c='_ZN12_GLOBAL__N_122SearchableTableEmitter9compareByEPN4llvm6RecordES3_RKNS_11SearchIndexE'/>
<use f='llvm/llvm/utils/TableGen/SearchableTableEmitter.cpp' l='545' c='_ZN12_GLOBAL__N_122SearchableTableEmitter14parseFieldTypeERNS_12GenericFieldEPN4llvm4InitE'/>
<size>16</size>
