<dec f='llvm/llvm/include/llvm/IR/Instruction.def' l='149' type='15'/>
<use f='llvm/llvm/include/llvm/IR/InstrTypes.h' l='359' u='r' c='_ZN4llvm14BinaryOperator12CreateNSWSubEPNS_5ValueES2_RKNS_5TwineE'/>
<use f='llvm/llvm/include/llvm/IR/InstrTypes.h' l='359' u='r' c='_ZN4llvm14BinaryOperator12CreateNSWSubEPNS_5ValueES2_RKNS_5TwineEPNS_10BasicBlockE'/>
<use f='llvm/llvm/include/llvm/IR/InstrTypes.h' l='359' u='r' c='_ZN4llvm14BinaryOperator12CreateNSWSubEPNS_5ValueES2_RKNS_5TwineEPNS_11InstructionE'/>
<use f='llvm/llvm/include/llvm/IR/InstrTypes.h' l='360' u='r' c='_ZN4llvm14BinaryOperator12CreateNUWSubEPNS_5ValueES2_RKNS_5TwineE'/>
<use f='llvm/llvm/include/llvm/IR/InstrTypes.h' l='360' u='r' c='_ZN4llvm14BinaryOperator12CreateNUWSubEPNS_5ValueES2_RKNS_5TwineEPNS_10BasicBlockE'/>
<use f='llvm/llvm/include/llvm/IR/InstrTypes.h' l='360' u='r' c='_ZN4llvm14BinaryOperator12CreateNUWSubEPNS_5ValueES2_RKNS_5TwineEPNS_11InstructionE'/>
<use f='llvm/llvm/include/llvm/IR/Operator.h' l='102' u='r' c='_ZN4llvm25OverflowingBinaryOperator7classofEPKNS_11InstructionE'/>
<use f='llvm/llvm/include/llvm/IR/Operator.h' l='108' u='r' c='_ZN4llvm25OverflowingBinaryOperator7classofEPKNS_12ConstantExprE'/>
<use f='llvm/llvm/include/llvm/IR/Operator.h' l='430'/>
<use f='llvm/llvm/include/llvm/IR/IRBuilder.h' l='1294' u='r' c='_ZN4llvm13IRBuilderBase9CreateSubEPNS_5ValueES2_RKNS_5TwineEbb'/>
<use f='llvm/clang/lib/CodeGen/CGAtomic.cpp' l='614' u='r' c='_ZL12EmitAtomicOpRN5clang7CodeGen15CodeGenFunctionEPNS_10AtomicExprENS0_7AddressES5_S5_S5_PN4llvm5ValueES8_mNS6_14AtomicOrderingEh'/>
<use f='llvm/clang/lib/CodeGen/CGAtomic.cpp' l='1156' u='r' c='_ZN5clang7CodeGen15CodeGenFunction14EmitAtomicExprEPNS_10AtomicExprE'/>
<use f='llvm/clang/lib/CodeGen/CGBuiltin.cpp' l='3615' u='r' c='_ZN5clang7CodeGen15CodeGenFunction15EmitBuiltinExprENS_10GlobalDeclEjPKNS_8CallExprENS0_15ReturnValueSlotE'/>
<use f='llvm/clang/lib/CodeGen/CGExprScalar.cpp' l='2447' u='r' c='_ZN12_GLOBAL__N_117ScalarExprEmitter23EmitScalarPrePostIncDecEPKN5clang13UnaryOperatorENS1_7CodeGen6LValueEbb'/>
<use f='llvm/clang/lib/CodeGen/CGExprScalar.cpp' l='3000' u='r' c='_ZN12_GLOBAL__N_117ScalarExprEmitter24EmitCompoundAssignLValueEPKN5clang22CompoundAssignOperatorEMS0_FPN4llvm5ValueERKNS_9BinOpInfoEERS7_'/>
<use f='llvm/lldb/source/Expression/IRInterpreter.cpp' l='582' c='_ZN13IRInterpreter12CanInterpretERN4llvm6ModuleERNS0_8FunctionERN12lldb_private6StatusEb'/>
<use f='llvm/lldb/source/Expression/IRInterpreter.cpp' l='693' c='_ZN13IRInterpreter9InterpretERN4llvm6ModuleERNS0_8FunctionENS0_8ArrayRefImEERN12lldb_private15IRExecutionUnitERNS7_6StatusEmmRNS7_16ExecutionContextE'/>
<use f='llvm/lldb/source/Expression/IRInterpreter.cpp' l='748' c='_ZN13IRInterpreter9InterpretERN4llvm6ModuleERNS0_8FunctionENS0_8ArrayRefImEERN12lldb_private15IRExecutionUnitERNS7_6StatusEmmRNS7_16ExecutionContextE'/>
<use f='llvm/llvm/include/llvm/IR/PatternMatch.h' l='967' c='_ZN4llvm12PatternMatch5m_SubERKT_RKT0_'/>
<use f='llvm/llvm/include/llvm/IR/PatternMatch.h' l='969' u='r' c='_ZN4llvm12PatternMatch5m_SubERKT_RKT0_'/>
<use f='llvm/llvm/include/llvm/IR/PatternMatch.h' l='1139' c='_ZN4llvm12PatternMatch8m_NSWSubERKT_RKT0_'/>
<use f='llvm/llvm/include/llvm/IR/PatternMatch.h' l='1142' u='r' c='_ZN4llvm12PatternMatch8m_NSWSubERKT_RKT0_'/>
<use f='llvm/llvm/include/llvm/IR/PatternMatch.h' l='1172' c='_ZN4llvm12PatternMatch8m_NUWSubERKT_RKT0_'/>
<use f='llvm/llvm/include/llvm/IR/PatternMatch.h' l='1175' u='r' c='_ZN4llvm12PatternMatch8m_NUWSubERKT_RKT0_'/>
<use f='llvm/llvm/include/llvm/IR/PatternMatch.h' l='2201' c='_ZN4llvm12PatternMatch5m_NegERKT_'/>
<use f='llvm/llvm/include/llvm/IR/PatternMatch.h' l='2209' c='_ZN4llvm12PatternMatch8m_NSWNegERKT_'/>
<use f='llvm/llvm/lib/Analysis/BasicAliasAnalysis.cpp' l='288' c='_ZN4llvm13BasicAAResult19GetLinearExpressionEPKNS_5ValueERNS_5APIntES5_RjS6_RKNS_10DataLayoutEjPNS_15AssumptionCacheEPNS_13DominatorTreeERbSE_'/>
<use f='llvm/llvm/lib/Analysis/CFLGraph.h' l='563' c='_ZN4llvm5cflaa15CFLGraphBuilder15GetEdgesVisitor17visitConstantExprEPNS_12ConstantExprE'/>
<use f='llvm/llvm/lib/Analysis/ConstantFolding.cpp' l='796' u='r' c='_ZN12_GLOBAL__N_125SymbolicallyEvaluateBinopEjPN4llvm8ConstantES2_RKNS0_10DataLayoutE'/>
<use f='llvm/llvm/lib/Analysis/ConstantFolding.cpp' l='903' u='r' c='_ZN12_GLOBAL__N_123SymbolicallyEvaluateGEPEPKN4llvm11GEPOperatorENS0_8ArrayRefIPNS0_8ConstantEEERKNS0_10DataLayoutEPKNS0_17TargetLibraryInfoE'/>
<use f='llvm/llvm/lib/Analysis/DemandedBits.cpp' l='192' c='_ZN4llvm12DemandedBits24determineLiveOperandBitsEPKNS_11InstructionEPKNS_5ValueEjRKNS_5APIntERS7_RNS_9KnownBitsESC_Rb'/>
<use f='llvm/llvm/lib/Analysis/IVDescriptors.cpp' l='567' c='_ZN4llvm20RecurrenceDescriptor17isRecurrenceInstrEPNS_11InstructionENS_9RecurKindERNS0_8InstDescEb'/>
<use f='llvm/llvm/lib/Analysis/InstructionSimplify.cpp' l='730' u='r' c='_ZL15SimplifySubInstPN4llvm5ValueES1_bbRKNS_13SimplifyQueryEj'/>
<use f='llvm/llvm/lib/Analysis/InstructionSimplify.cpp' l='769' u='r' c='_ZL15SimplifySubInstPN4llvm5ValueES1_bbRKNS_13SimplifyQueryEj'/>
<use f='llvm/llvm/lib/Analysis/InstructionSimplify.cpp' l='777' u='r' c='_ZL15SimplifySubInstPN4llvm5ValueES1_bbRKNS_13SimplifyQueryEj'/>
<use f='llvm/llvm/lib/Analysis/InstructionSimplify.cpp' l='791' u='r' c='_ZL15SimplifySubInstPN4llvm5ValueES1_bbRKNS_13SimplifyQueryEj'/>
<use f='llvm/llvm/lib/Analysis/InstructionSimplify.cpp' l='793' u='r' c='_ZL15SimplifySubInstPN4llvm5ValueES1_bbRKNS_13SimplifyQueryEj'/>
<use f='llvm/llvm/lib/Analysis/InstructionSimplify.cpp' l='799' u='r' c='_ZL15SimplifySubInstPN4llvm5ValueES1_bbRKNS_13SimplifyQueryEj'/>
<use f='llvm/llvm/lib/Analysis/InstructionSimplify.cpp' l='801' u='r' c='_ZL15SimplifySubInstPN4llvm5ValueES1_bbRKNS_13SimplifyQueryEj'/>
<use f='llvm/llvm/lib/Analysis/InstructionSimplify.cpp' l='813' u='r' c='_ZL15SimplifySubInstPN4llvm5ValueES1_bbRKNS_13SimplifyQueryEj'/>
<use f='llvm/llvm/lib/Analysis/InstructionSimplify.cpp' l='826' u='r' c='_ZL15SimplifySubInstPN4llvm5ValueES1_bbRKNS_13SimplifyQueryEj'/>
<use f='llvm/llvm/lib/Analysis/InstructionSimplify.cpp' l='5144' c='_ZL13SimplifyBinOpjPN4llvm5ValueES1_RKNS_13SimplifyQueryEj'/>
<use f='llvm/llvm/lib/Analysis/InstructionSimplify.cpp' l='5281' u='r' c='_ZL20SimplifyRelativeLoadPN4llvm8ConstantES1_RKNS_10DataLayoutE'/>
<use f='llvm/llvm/lib/Analysis/InstructionSimplify.cpp' l='5820' c='_ZN4llvm19SimplifyInstructionEPNS_11InstructionERKNS_13SimplifyQueryEPNS_25OptimizationRemarkEmitterE'/>
<use f='llvm/llvm/lib/Analysis/LoopInfo.cpp' l='358' u='r' c='_ZNK4llvm4Loop28isAuxiliaryInductionVariableERNS_7PHINodeERNS_15ScalarEvolutionE'/>
<use f='llvm/llvm/lib/Analysis/ObjCARCInstKind.cpp' l='253' c='_ZN4llvm7objcarc14GetARCInstKindEPKNS_5ValueE'/>
<use f='llvm/llvm/lib/Analysis/ScalarEvolution.cpp' l='4582' c='_ZL13MatchBinaryOpPN4llvm5ValueERNS_13DominatorTreeE'/>
<use f='llvm/llvm/lib/Analysis/ScalarEvolution.cpp' l='4648' u='r' c='_ZL13MatchBinaryOpPN4llvm5ValueERNS_13DominatorTreeE'/>
<use f='llvm/llvm/lib/Analysis/ScalarEvolution.cpp' l='6395' u='r' c='_ZN4llvm15ScalarEvolution10createSCEVEPNS_5ValueE'/>
<use f='llvm/llvm/lib/Analysis/ScalarEvolution.cpp' l='6403' u='r' c='_ZN4llvm15ScalarEvolution10createSCEVEPNS_5ValueE'/>
<use f='llvm/llvm/lib/Analysis/ScalarEvolution.cpp' l='6410' u='r' c='_ZN4llvm15ScalarEvolution10createSCEVEPNS_5ValueE'/>
<use f='llvm/llvm/lib/Analysis/ScalarEvolution.cpp' l='6452' c='_ZN4llvm15ScalarEvolution10createSCEVEPNS_5ValueE'/>
<use f='llvm/llvm/lib/Analysis/ScalarEvolution.cpp' l='6680' u='r' c='_ZN4llvm15ScalarEvolution10createSCEVEPNS_5ValueE'/>
<use f='llvm/llvm/include/llvm/Analysis/TargetTransformInfoImpl.h' l='933' c='_ZN4llvm31TargetTransformInfoImplCRTPBase11getUserCostEPKNS_4UserENS_8ArrayRefIPKNS_5ValueEEENS_19TargetTransformInfo14TargetCostKindE'/>
<use f='llvm/llvm/lib/Analysis/TargetTransformInfo.cpp' l='1378' c='_ZNK4llvm19TargetTransformInfo24getInstructionThroughputEPKNS_11InstructionE'/>
<use f='llvm/llvm/lib/Analysis/ValueTracking.cpp' l='1250' c='_ZL28computeKnownBitsFromOperatorPKN4llvm8OperatorERKNS_5APIntERNS_9KnownBitsEjRKN12_GLOBAL__N_15QueryE'/>
<use f='llvm/llvm/lib/Analysis/ValueTracking.cpp' l='1380' u='r' c='_ZL28computeKnownBitsFromOperatorPKN4llvm8OperatorERKNS_5APIntERNS_9KnownBitsEjRKN12_GLOBAL__N_15QueryE'/>
<use f='llvm/llvm/lib/Analysis/ValueTracking.cpp' l='1433' u='r' c='_ZL28computeKnownBitsFromOperatorPKN4llvm8OperatorERKNS_5APIntERNS_9KnownBitsEjRKN12_GLOBAL__N_15QueryE'/>
<use f='llvm/llvm/lib/Analysis/ValueTracking.cpp' l='2520' c='_ZL15isKnownNonEqualPKN4llvm5ValueES2_jRKN12_GLOBAL__N_15QueryE'/>
<use f='llvm/llvm/lib/Analysis/ValueTracking.cpp' l='2844' c='_ZL22ComputeNumSignBitsImplPKN4llvm5ValueERKNS_5APIntEjRKN12_GLOBAL__N_15QueryE'/>
<use f='llvm/llvm/lib/AsmParser/LLLexer.cpp' l='861' u='r' c='_ZN4llvm7LLLexer13LexIdentifierEv'/>
<use f='llvm/llvm/lib/AsmParser/LLParser.cpp' l='3674' u='r' c='_ZN4llvm8LLParser10parseValIDERNS_5ValIDEPNS0_16PerFunctionStateE'/>
<use f='llvm/llvm/lib/AsmParser/LLParser.cpp' l='3699' c='_ZN4llvm8LLParser10parseValIDERNS_5ValIDEPNS0_16PerFunctionStateE'/>
<use f='llvm/llvm/lib/Bitcode/Reader/BitcodeReader.cpp' l='1090' u='r' c='_ZL22getDecodedBinaryOpcodejPN4llvm4TypeE'/>
<use f='llvm/llvm/lib/Bitcode/Reader/BitcodeReader.cpp' l='2610' u='r' c='_ZN12_GLOBAL__N_113BitcodeReader14parseConstantsEv'/>
<use f='llvm/llvm/lib/Bitcode/Reader/BitcodeReader.cpp' l='4010' u='r' c='_ZN12_GLOBAL__N_113BitcodeReader17parseFunctionBodyEPN4llvm8FunctionE'/>
<use f='llvm/llvm/lib/Bitcode/Writer/BitcodeWriter.cpp' l='543' c='_ZL22getEncodedBinaryOpcodej'/>
<use f='llvm/llvm/lib/CodeGen/AsmPrinter/AsmPrinter.cpp' l='2475' c='_ZN4llvm10AsmPrinter13lowerConstantEPKNS_8ConstantE'/>
<use f='llvm/llvm/lib/CodeGen/AsmPrinter/AsmPrinter.cpp' l='2523' c='_ZN4llvm10AsmPrinter13lowerConstantEPKNS_8ConstantE'/>
<use f='llvm/llvm/include/llvm/CodeGen/BasicTTIImpl.h' l='1321' c='_ZN4llvm16BasicTTIImplBase21getIntrinsicInstrCostERKNS_23IntrinsicCostAttributesENS_19TargetTransformInfo14TargetCostKindE'/>
<use f='llvm/llvm/include/llvm/CodeGen/BasicTTIImpl.h' l='1602' c='_ZN4llvm16BasicTTIImplBase30getTypeBasedIntrinsicInstrCostERKNS_23IntrinsicCostAttributesENS_19TargetTransformInfo14TargetCostKindE'/>
<use f='llvm/llvm/include/llvm/CodeGen/BasicTTIImpl.h' l='1676' u='r' c='_ZN4llvm16BasicTTIImplBase30getTypeBasedIntrinsicInstrCostERKNS_23IntrinsicCostAttributesENS_19TargetTransformInfo14TargetCostKindE'/>
<use f='llvm/llvm/include/llvm/CodeGen/BasicTTIImpl.h' l='1704' u='r' c='_ZN4llvm16BasicTTIImplBase30getTypeBasedIntrinsicInstrCostERKNS_23IntrinsicCostAttributesENS_19TargetTransformInfo14TargetCostKindE'/>
<use f='llvm/llvm/lib/CodeGen/SelectionDAG/FastISel.cpp' l='1740' c='_ZN4llvm8FastISel14selectOperatorEPKNS_4UserEj'/>
<use f='llvm/llvm/lib/CodeGen/TypePromotion.cpp' l='338' u='r' c='_ZN12_GLOBAL__N_113TypePromotion10isSafeWrapEPN4llvm11InstructionE'/>
<use f='llvm/llvm/lib/CodeGen/TypePromotion.cpp' l='348' u='r' c='_ZN12_GLOBAL__N_113TypePromotion10isSafeWrapEPN4llvm11InstructionE'/>
<use f='llvm/llvm/lib/ExecutionEngine/ExecutionEngine.cpp' l='774' c='_ZN4llvm15ExecutionEngine16getConstantValueEPKNS_8ConstantE'/>
<use f='llvm/llvm/lib/ExecutionEngine/ExecutionEngine.cpp' l='794' c='_ZN4llvm15ExecutionEngine16getConstantValueEPKNS_8ConstantE'/>
<use f='llvm/llvm/lib/ExecutionEngine/Interpreter/Execution.cpp' l='789' c='_ZN4llvm11Interpreter19visitBinaryOperatorERNS_14BinaryOperatorE'/>
<use f='llvm/llvm/lib/ExecutionEngine/Interpreter/Execution.cpp' l='826' c='_ZN4llvm11Interpreter19visitBinaryOperatorERNS_14BinaryOperatorE'/>
<use f='llvm/llvm/lib/ExecutionEngine/Interpreter/Execution.cpp' l='2070' c='_ZN4llvm11Interpreter20getConstantExprValueEPNS_12ConstantExprERNS_16ExecutionContextE'/>
<use f='llvm/llvm/lib/FuzzMutate/IRMutator.cpp' l='211' c='_ZN4llvm26InstModificationIRStrategy6mutateERNS_11InstructionERNS_15RandomIRBuilderE'/>
<use f='llvm/llvm/lib/FuzzMutate/Operations.cpp' l='20' u='r' c='_ZN4llvm20describeFuzzerIntOpsERSt6vectorINS_8fuzzerop12OpDescriptorESaIS2_EE'/>
<use f='llvm/llvm/lib/FuzzMutate/Operations.cpp' l='98' c='_ZN4llvm8fuzzerop15binOpDescriptorEjNS_11Instruction9BinaryOpsE'/>
<use f='llvm/llvm/lib/IR/ConstantFold.cpp' l='1133' c='_ZN4llvm29ConstantFoldBinaryInstructionEjPNS_8ConstantES1_'/>
<use f='llvm/llvm/lib/IR/ConstantFold.cpp' l='1239' c='_ZN4llvm29ConstantFoldBinaryInstructionEjPNS_8ConstantES1_'/>
<use f='llvm/llvm/lib/IR/ConstantFold.cpp' l='1363' c='_ZN4llvm29ConstantFoldBinaryInstructionEjPNS_8ConstantES1_'/>
<use f='llvm/llvm/lib/IR/ConstantFold.cpp' l='1497' c='_ZN4llvm29ConstantFoldBinaryInstructionEjPNS_8ConstantES1_'/>
<use f='llvm/llvm/lib/IR/ConstantRange.cpp' l='256' c='_ZN4llvm13ConstantRange26makeGuaranteedNoWrapRegionENS_11Instruction9BinaryOpsERKS0_j'/>
<use f='llvm/llvm/lib/IR/ConstantRange.cpp' l='799' c='_ZNK4llvm13ConstantRange8binaryOpENS_11Instruction9BinaryOpsERKS0_'/>
<use f='llvm/llvm/lib/IR/ConstantRange.cpp' l='845' c='_ZNK4llvm13ConstantRange19overflowingBinaryOpENS_11Instruction9BinaryOpsERKS0_j'/>
<use f='llvm/llvm/lib/IR/Constants.cpp' l='663' u='r' c='_ZNK4llvm8Constant15needsRelocationEv'/>
<use f='llvm/llvm/lib/IR/Constants.cpp' l='2645' u='r' c='_ZN4llvm12ConstantExpr6getSubEPNS_8ConstantES2_bb'/>
<use f='llvm/llvm/lib/IR/Constants.cpp' l='2782' c='_ZN4llvm12ConstantExpr16getBinOpIdentityEjPNS_4TypeEb'/>
<use f='llvm/llvm/lib/IR/Globals.cpp' l='450' c='_ZL14findBaseObjectPKN4llvm8ConstantERNS_8DenseSetIPKNS_11GlobalAliasENS_12DenseMapInfoIS6_EEEE'/>
<use f='llvm/llvm/lib/IR/Instruction.cpp' l='142' c='_ZN4llvm11Instruction25dropPoisonGeneratingFlagsEv'/>
<use f='llvm/llvm/lib/IR/Instruction.cpp' l='338' c='_ZN4llvm11Instruction13getOpcodeNameEj'/>
<use f='llvm/llvm/lib/IR/Instructions.cpp' l='2538' u='r' c='_ZN4llvm14BinaryOperator9CreateNegEPNS_5ValueERKNS_5TwineEPNS_11InstructionE'/>
<use f='llvm/llvm/lib/IR/Instructions.cpp' l='2546' u='r' c='_ZN4llvm14BinaryOperator9CreateNegEPNS_5ValueERKNS_5TwineEPNS_10BasicBlockE'/>
<use f='llvm/llvm/lib/IR/IntrinsicInst.cpp' l='322' u='r' c='_ZNK4llvm17BinaryOpIntrinsic11getBinaryOpEv'/>
<use f='llvm/llvm/lib/IR/ReplaceConstant.cpp' l='34' c='_ZN4llvm22createReplacementInstrEPNS_12ConstantExprEPNS_11InstructionE'/>
<use f='llvm/llvm/lib/IR/Verifier.cpp' l='3395' c='_ZN12_GLOBAL__N_18Verifier19visitBinaryOperatorERN4llvm14BinaryOperatorE'/>
<use f='llvm/llvm/lib/Target/AArch64/AArch64FastISel.cpp' l='698' c='_ZN12_GLOBAL__N_115AArch64FastISel14computeAddressEPKN4llvm5ValueERNS0_7AddressEPNS1_4TypeE'/>
<use f='llvm/llvm/lib/Target/AArch64/AArch64FastISel.cpp' l='1935' c='_ZN12_GLOBAL__N_115AArch64FastISel12selectAddSubEPKN4llvm11InstructionE'/>
<use f='llvm/llvm/lib/Target/AArch64/AArch64FastISel.cpp' l='5157' c='_ZN12_GLOBAL__N_115AArch64FastISel21fastSelectInstructionEPKN4llvm11InstructionE'/>
<use f='llvm/llvm/lib/Target/AArch64/AArch64ISelLowering.cpp' l='10971' c='_ZNK4llvm21AArch64TargetLowering18shouldSinkOperandsEPNS_11InstructionERNS_15SmallVectorImplIPNS_3UseEEE'/>
<use f='llvm/llvm/lib/Target/AArch64/AArch64TargetTransformInfo.cpp' l='112' c='_ZN4llvm14AArch64TTIImpl17getIntImmCostInstEjjRKNS_5APIntEPNS_4TypeENS_19TargetTransformInfo14TargetCostKindEPNS_11InstructionE'/>
<use f='llvm/llvm/lib/Target/AArch64/AArch64TargetTransformInfo.cpp' l='268' c='_ZN4llvm14AArch64TTIImpl21isWideningInstructionEPNS_4TypeEjNS_8ArrayRefIPKNS_5ValueEEE'/>
<use f='llvm/llvm/lib/Target/AArch64/AArch64TargetTransformInfo.cpp' l='591' u='r' c='_ZN4llvm14AArch64TTIImpl22getArithmeticInstrCostEjPNS_4TypeENS_19TargetTransformInfo14TargetCostKindENS3_16OperandValueKindES5_NS3_22OperandValuePrope869056'/>
<use f='llvm/llvm/lib/Target/AMDGPU/AMDGPUAtomicOptimizer.cpp' l='257' u='r' c='_ZL19buildNonAtomicBinOpRN4llvm9IRBuilderINS_14ConstantFolderENS_24IRBuilderDefaultInserterEEENS_13AtomicRMWInst5BinOpEPNS_5ValueES8_'/>
<use f='llvm/llvm/lib/Target/AMDGPU/AMDGPUCodeGenPrepare.cpp' l='281' c='_ZL15promotedOpIsNSWRKN4llvm11InstructionE'/>
<use f='llvm/llvm/lib/Target/AMDGPU/AMDGPUCodeGenPrepare.cpp' l='297' c='_ZL15promotedOpIsNUWRKN4llvm11InstructionE'/>
<use f='llvm/llvm/include/llvm/Transforms/InstCombine/InstCombiner.h' l='251' u='r' c='_ZN4llvm12InstCombiner14isFreeToInvertEPNS_5ValueEb'/>
<use f='llvm/llvm/include/llvm/Transforms/InstCombine/InstCombiner.h' l='336' c='_ZN4llvm12InstCombiner29getSafeVectorConstantForBinopENS_11Instruction9BinaryOpsEPNS_8ConstantEb'/>
<use f='llvm/llvm/lib/Target/ARM/ARMFastISel.cpp' l='2853' c='_ZN12_GLOBAL__N_111ARMFastISel21fastSelectInstructionEPKN4llvm11InstructionE'/>
<use f='llvm/llvm/lib/Target/ARM/ARMISelLowering.cpp' l='16688' c='_ZNK4llvm17ARMTargetLowering18shouldSinkOperandsEPNS_11InstructionERNS_15SmallVectorImplIPNS_3UseEEE'/>
<use f='llvm/llvm/lib/Target/ARM/ARMISelLowering.cpp' l='16727' c='_ZNK4llvm17ARMTargetLowering18shouldSinkOperandsEPNS_11InstructionERNS_15SmallVectorImplIPNS_3UseEEE'/>
<use f='llvm/llvm/lib/Target/ARM/ARMTargetTransformInfo.cpp' l='1249' c='_ZN4llvm10ARMTTIImpl22getArithmeticInstrCostEjPNS_4TypeENS_19TargetTransformInfo14TargetCostKindENS3_16OperandValueKindES5_NS3_22OperandValuePropertie16237181'/>
<use f='llvm/llvm/lib/Target/ARM/MVEGatherScatterLowering.cpp' l='775' u='r' c='_ZN12_GLOBAL__N_124MVEGatherScatterLowering30tryCreateIncrementingWBGatScatEPN4llvm13IntrinsicInstEPNS1_5ValueES5_jRNS1_9IRBuilderINS1_14ConstantFolde10890651'/>
<use f='llvm/llvm/lib/Target/PowerPC/PPCFastISel.cpp' l='1969' c='_ZN12_GLOBAL__N_111PPCFastISel21fastSelectInstructionEPKN4llvm11InstructionE'/>
<use f='llvm/llvm/lib/Target/PowerPC/PPCTargetTransformInfo.cpp' l='269' c='_ZN4llvm10PPCTTIImpl17getIntImmCostInstEjjRKNS_5APIntEPNS_4TypeENS_19TargetTransformInfo14TargetCostKindEPNS_11InstructionE'/>
<use f='llvm/llvm/lib/Target/RISCV/RISCVTargetTransformInfo.cpp' l='62' c='_ZN4llvm12RISCVTTIImpl17getIntImmCostInstEjjRKNS_5APIntEPNS_4TypeENS_19TargetTransformInfo14TargetCostKindEPNS_11InstructionE'/>
<use f='llvm/llvm/lib/Target/SystemZ/SystemZTargetTransformInfo.cpp' l='112' c='_ZN4llvm14SystemZTTIImpl17getIntImmCostInstEjjRKNS_5APIntEPNS_4TypeENS_19TargetTransformInfo14TargetCostKindEPNS_11InstructionE'/>
<use f='llvm/llvm/lib/Target/SystemZ/SystemZTargetTransformInfo.cpp' l='978' u='r' c='_ZN4llvm14SystemZTTIImpl14isFoldableLoadEPKNS_8LoadInstERPKNS_11InstructionE'/>
<use f='llvm/llvm/lib/Target/SystemZ/SystemZTargetTransformInfo.cpp' l='989' c='_ZN4llvm14SystemZTTIImpl14isFoldableLoadEPKNS_8LoadInstERPKNS_11InstructionE'/>
<use f='llvm/llvm/lib/Target/WebAssembly/WebAssemblyFastISel.cpp' l='357' c='_ZN12_GLOBAL__N_119WebAssemblyFastISel14computeAddressEPKN4llvm5ValueERNS0_7AddressE'/>
<use f='llvm/llvm/lib/Target/X86/X86PartialReduction.cpp' l='192' u='r' c='_ZN12_GLOBAL__N_119X86PartialReduction17trySADReplacementEPN4llvm11InstructionE'/>
<use f='llvm/llvm/lib/Target/X86/X86TargetTransformInfo.cpp' l='282' u='r' c='_ZN4llvm10X86TTIImpl22getArithmeticInstrCostEjPNS_4TypeENS_19TargetTransformInfo14TargetCostKindENS3_16OperandValueKindES5_NS3_22OperandValuePropertie7593393'/>
<use f='llvm/llvm/lib/Target/X86/X86TargetTransformInfo.cpp' l='3974' c='_ZN4llvm10X86TTIImpl17getIntImmCostInstEjjRKNS_5APIntEPNS_4TypeENS_19TargetTransformInfo14TargetCostKindEPNS_11InstructionE'/>
<use f='llvm/llvm/lib/Transforms/AggressiveInstCombine/TruncInstCombine.cpp' l='59' c='_ZL19getRelevantOperandsPN4llvm11InstructionERNS_15SmallVectorImplIPNS_5ValueEEE'/>
<use f='llvm/llvm/lib/Transforms/AggressiveInstCombine/TruncInstCombine.cpp' l='125' c='_ZN4llvm16TruncInstCombine23buildTruncExpressionDagEv'/>
<use f='llvm/llvm/lib/Transforms/AggressiveInstCombine/TruncInstCombine.cpp' l='355' c='_ZN4llvm16TruncInstCombine19ReduceExpressionDagEPNS_4TypeE'/>
<use f='llvm/llvm/lib/Transforms/IPO/AttributorAttributes.cpp' l='7556' c='_ZN12_GLOBAL__N_125AAPotentialValuesFloating23calculateBinaryOperatorEPKN4llvm14BinaryOperatorERKNS1_5APIntES7_RbS8_'/>
<use f='llvm/llvm/lib/Transforms/InstCombine/InstCombineInternal.h' l='311' c='_ZNK4llvm16InstCombinerImpl15willNotOverflowENS_11Instruction9BinaryOpsEPKNS_5ValueES5_RKS1_b'/>
<use f='llvm/llvm/lib/Transforms/InstCombine/InstCombineAddSub.cpp' l='1162' u='r' c='_ZN4llvm16InstCombinerImpl62canonicalizeCondSignextOfHighBitExtractToSignextHighBitExtractERNS_14BinaryOperatorE'/>
<use f='llvm/llvm/lib/Transforms/InstCombine/InstCombineAddSub.cpp' l='1190' u='r' c='_ZN4llvm16InstCombinerImpl62canonicalizeCondSignextOfHighBitExtractToSignextHighBitExtractERNS_14BinaryOperatorE'/>
<use f='llvm/llvm/lib/Transforms/InstCombine/InstCombineAddSub.cpp' l='1229' u='r' c='_ZN4llvm16InstCombinerImpl62canonicalizeCondSignextOfHighBitExtractToSignextHighBitExtractERNS_14BinaryOperatorE'/>
<use f='llvm/llvm/lib/Transforms/InstCombine/InstCombineAndOrXor.cpp' l='1692' u='r' c='_ZN4llvm16InstCombinerImpl17narrowMaskedBinOpERNS_14BinaryOperatorE'/>
<use f='llvm/llvm/lib/Transforms/InstCombine/InstCombineAndOrXor.cpp' l='1833' c='_ZN4llvm16InstCombinerImpl8visitAndERNS_14BinaryOperatorE'/>
<use f='llvm/llvm/lib/Transforms/InstCombine/InstCombineAndOrXor.cpp' l='3265' u='r' c='_ZN4llvm16InstCombinerImpl8visitXorERNS_14BinaryOperatorE'/>
<use f='llvm/llvm/lib/Transforms/InstCombine/InstCombineCasts.cpp' l='194' c='_ZN4llvm16InstCombinerImpl23EvaluateInDifferentTypeEPNS_5ValueEPNS_4TypeEb'/>
<use f='llvm/llvm/lib/Transforms/InstCombine/InstCombineCasts.cpp' l='374' c='_ZL20canEvaluateTruncatedPN4llvm5ValueEPNS_4TypeERNS_16InstCombinerImplEPNS_11InstructionE'/>
<use f='llvm/llvm/lib/Transforms/InstCombine/InstCombineCasts.cpp' l='634' c='_ZN4llvm16InstCombinerImpl11narrowBinOpERNS_9TruncInstE'/>
<use f='llvm/llvm/lib/Transforms/InstCombine/InstCombineCasts.cpp' l='1088' c='_ZL16canEvaluateZExtdPN4llvm5ValueEPNS_4TypeERjRNS_16InstCombinerImplEPNS_11InstructionE'/>
<use f='llvm/llvm/lib/Transforms/InstCombine/InstCombineCasts.cpp' l='1421' c='_ZL16canEvaluateSExtdPN4llvm5ValueEPNS_4TypeE'/>
<use f='llvm/llvm/lib/Transforms/InstCombine/InstCombineCompares.cpp' l='2912' c='_ZN4llvm16InstCombinerImpl24foldICmpInstWithConstantERNS_8ICmpInstE'/>
<use f='llvm/llvm/lib/Transforms/InstCombine/InstCombineCompares.cpp' l='3009' c='_ZN4llvm16InstCombinerImpl33foldICmpBinOpEqualityWithConstantERNS_8ICmpInstEPNS_14BinaryOperatorERKNS_5APIntE'/>
<use f='llvm/llvm/lib/Transforms/InstCombine/InstCombineCompares.cpp' l='3920' u='r' c='_ZN4llvm16InstCombinerImpl13foldICmpBinOpERNS_8ICmpInstERKNS_13SimplifyQueryE'/>
<use f='llvm/llvm/lib/Transforms/InstCombine/InstCombineCompares.cpp' l='3924' u='r' c='_ZN4llvm16InstCombinerImpl13foldICmpBinOpERNS_8ICmpInstERKNS_13SimplifyQueryE'/>
<use f='llvm/llvm/lib/Transforms/InstCombine/InstCombineCompares.cpp' l='4018' c='_ZN4llvm16InstCombinerImpl13foldICmpBinOpERNS_8ICmpInstERKNS_13SimplifyQueryE'/>
<use f='llvm/llvm/lib/Transforms/InstCombine/InstCombineCompares.cpp' l='4517' c='_ZL14isNeutralValueN4llvm11Instruction9BinaryOpsEPNS_5ValueE'/>
<use f='llvm/llvm/lib/Transforms/InstCombine/InstCombineCompares.cpp' l='4536' c='_ZNK4llvm16InstCombinerImpl15computeOverflowENS_11Instruction9BinaryOpsEbPNS_5ValueES4_PS1_'/>
<use f='llvm/llvm/lib/Transforms/InstCombine/InstCombineNegator.cpp' l='222' u='r' c='_ZN4llvm7Negator9visitImplEPNS_5ValueEj'/>
<use f='llvm/llvm/lib/Transforms/InstCombine/InstCombineSelect.cpp' l='257' c='_ZL25getSelectFoldableOperandsPN4llvm14BinaryOperatorE'/>
<use f='llvm/llvm/lib/Transforms/InstCombine/InstCombineSelect.cpp' l='1703' u='r' c='_ZL16foldAddSubSelectRN4llvm10SelectInstERNS_9IRBuilderINS_12TargetFolderENS_25IRBuilderCallbackInserterEEE'/>
<use f='llvm/llvm/lib/Transforms/InstCombine/InstCombineSelect.cpp' l='1709' u='r' c='_ZL16foldAddSubSelectRN4llvm10SelectInstERNS_9IRBuilderINS_12TargetFolderENS_25IRBuilderCallbackInserterEEE'/>
<use f='llvm/llvm/lib/Transforms/InstCombine/InstCombineSelect.cpp' l='2208' u='r' c='_ZN4llvm16InstCombinerImpl15matchSAddSubSatERNS_10SelectInstE'/>
<use f='llvm/llvm/lib/Transforms/InstCombine/InstCombineShifts.cpp' l='768' c='_ZN4llvm16InstCombinerImpl19FoldShiftByConstantEPNS_5ValueEPNS_8ConstantERNS_14BinaryOperatorE'/>
<use f='llvm/llvm/lib/Transforms/InstCombine/InstCombineShifts.cpp' l='822' u='r' c='_ZN4llvm16InstCombinerImpl19FoldShiftByConstantEPNS_5ValueEPNS_8ConstantERNS_14BinaryOperatorE'/>
<use f='llvm/llvm/lib/Transforms/InstCombine/InstCombineSimplifyDemanded.cpp' l='480' c='_ZN4llvm16InstCombinerImpl23SimplifyDemandedUseBitsEPNS_5ValueENS_5APIntERNS_9KnownBitsEjPNS_11InstructionE'/>
<use f='llvm/llvm/lib/Transforms/InstCombine/InstCombineVectorOps.cpp' l='1495' c='_ZL19canEvaluateShuffledPN4llvm5ValueENS_8ArrayRefIiEEj'/>
<use f='llvm/llvm/lib/Transforms/InstCombine/InstCombineVectorOps.cpp' l='1560' c='_ZL8buildNewPN4llvm11InstructionENS_8ArrayRefIPNS_5ValueEEE'/>
<use f='llvm/llvm/lib/Transforms/InstCombine/InstCombineVectorOps.cpp' l='1650' c='_ZL31evaluateInDifferentElementOrderPN4llvm5ValueENS_8ArrayRefIiEE'/>
<use f='llvm/llvm/lib/Transforms/InstCombine/InstructionCombining.cpp' l='265' u='r' c='_ZL20maintainNoSignedWrapRN4llvm14BinaryOperatorEPNS_5ValueES3_'/>
<use f='llvm/llvm/lib/Transforms/InstCombine/InstructionCombining.cpp' l='543' u='r' c='_ZL24leftDistributesOverRightN4llvm11Instruction9BinaryOpsES1_'/>
<use f='llvm/llvm/lib/Transforms/InstCombine/InstructionCombining.cpp' l='583' u='r' c='_ZL25getBinOpsForFactorizationN4llvm11Instruction9BinaryOpsEPNS_14BinaryOperatorERPNS_5ValueES6_'/>
<use f='llvm/llvm/lib/Transforms/InstCombine/InstructionCombining.cpp' l='1769' u='r' c='_ZN4llvm16InstCombinerImpl22narrowMathIfNoOverflowERNS_14BinaryOperatorE'/>
<use f='llvm/llvm/lib/Transforms/InstCombine/InstructionCombining.cpp' l='1796' u='r' c='_ZN4llvm16InstCombinerImpl22narrowMathIfNoOverflowERNS_14BinaryOperatorE'/>
<use f='llvm/llvm/lib/Transforms/Instrumentation/AddressSanitizer.cpp' l='1455' u='r' c='_ZL31isInterestingPointerSubtractionPN4llvm11InstructionE'/>
<use f='llvm/llvm/lib/Transforms/Instrumentation/PoisonChecking.cpp' l='127' c='_ZL30generateCreationChecksForBinOpRN4llvm11InstructionERNS_15SmallVectorImplIPNS_5ValueEEE'/>
<use f='llvm/llvm/lib/Transforms/Scalar/CorrelatedValuePropagation.cpp' l='407' c='_ZL26setDeducedOverflowingFlagsPN4llvm5ValueENS_11Instruction9BinaryOpsEbb'/>
<use f='llvm/llvm/lib/Transforms/Scalar/CorrelatedValuePropagation.cpp' l='978' c='_ZL7runImplRN4llvm8FunctionEPNS_13LazyValueInfoEPNS_13DominatorTreeERKNS_13SimplifyQueryE'/>
<use f='llvm/llvm/lib/Transforms/Scalar/Float2Int.cpp' l='115' u='r' c='_ZL12mapBinOpcodej'/>
<use f='llvm/llvm/lib/Transforms/Scalar/GVN.cpp' l='518' c='_ZN4llvm3GVN10ValueTable11lookupOrAddEPNS_5ValueE'/>
<use f='llvm/llvm/lib/Transforms/Scalar/GVNSink.cpp' l='450' c='_ZN12_GLOBAL__N_110ValueTable11lookupOrAddEPN4llvm5ValueE'/>
<use f='llvm/llvm/lib/Transforms/Scalar/IndVarSimplify.cpp' l='668' c='_ZL20getLoopPhiForCounterPN4llvm5ValueEPNS_4LoopE'/>
<use f='llvm/llvm/lib/Transforms/Scalar/LoopIdiomRecognize.cpp' l='1351' u='r' c='_ZL19detectPopcountIdiomPN4llvm4LoopEPNS_10BasicBlockERPNS_11InstructionERPNS_7PHINodeERPNS_5ValueE'/>
<use f='llvm/llvm/lib/Transforms/Scalar/LoopRerollPass.cpp' l='758' c='_ZL20isSimpleArithmeticOpPN4llvm4UserE'/>
<use f='llvm/llvm/lib/Transforms/Scalar/LoopStrengthReduce.cpp' l='2140' u='r' c='_ZN12_GLOBAL__N_111LSRInstance16OptimizeShadowIVEv'/>
<use f='llvm/llvm/lib/Transforms/Scalar/LowerMatrixIntrinsics.cpp' l='494' c='_ZN12_GLOBAL__N_121LowerMatrixIntrinsics14isUniformShapeEPN4llvm5ValueE'/>
<use f='llvm/llvm/lib/Transforms/Scalar/LowerMatrixIntrinsics.cpp' l='1480' c='_ZN12_GLOBAL__N_121LowerMatrixIntrinsics19VisitBinaryOperatorEPN4llvm14BinaryOperatorE'/>
<use f='llvm/llvm/lib/Transforms/Scalar/NewGVN.cpp' l='1949' c='_ZNK12_GLOBAL__N_16NewGVN25performSymbolicEvaluationEPN4llvm5ValueERNS1_15SmallPtrSetImplIS3_EE'/>
<use f='llvm/llvm/lib/Transforms/Scalar/Reassociate.cpp' l='906' u='r' c='_ZL11NegateValuePN4llvm5ValueEPNS_11InstructionERNS_9SetVectorINS_11AssertingVHIS2_EESt5dequeIS6_SaIS6_EENS_8DenseSetIS6_NS_12DenseMapInfoIS6_EEEEEE'/>
<use f='llvm/llvm/lib/Transforms/Scalar/Reassociate.cpp' l='983' c='_ZL36ShouldConvertOrWithNoCommonBitsToAddPN4llvm11InstructionE'/>
<use f='llvm/llvm/lib/Transforms/Scalar/Reassociate.cpp' l='1031' u='r' c='_ZL21ShouldBreakUpSubtractPN4llvm11InstructionE'/>
<use f='llvm/llvm/lib/Transforms/Scalar/Reassociate.cpp' l='1035' u='r' c='_ZL21ShouldBreakUpSubtractPN4llvm11InstructionE'/>
<use f='llvm/llvm/lib/Transforms/Scalar/Reassociate.cpp' l='1040' u='r' c='_ZL21ShouldBreakUpSubtractPN4llvm11InstructionE'/>
<use f='llvm/llvm/lib/Transforms/Scalar/Reassociate.cpp' l='2227' u='r' c='_ZN4llvm15ReassociatePass12OptimizeInstEPNS_11InstructionE'/>
<use f='llvm/llvm/lib/Transforms/Scalar/Reassociate.cpp' l='2300' u='r' c='_ZN4llvm15ReassociatePass12OptimizeInstEPNS_11InstructionE'/>
<use f='llvm/llvm/lib/Transforms/Scalar/SeparateConstOffsetFromGEP.cpp' l='511' u='r' c='_ZN12_GLOBAL__N_123ConstantOffsetExtractor12CanTraceIntoEbbPN4llvm14BinaryOperatorEb'/>
<use f='llvm/llvm/lib/Transforms/Scalar/SeparateConstOffsetFromGEP.cpp' l='558' u='r' c='_ZN12_GLOBAL__N_123ConstantOffsetExtractor12CanTraceIntoEbbPN4llvm14BinaryOperatorEb'/>
<use f='llvm/llvm/lib/Transforms/Scalar/SeparateConstOffsetFromGEP.cpp' l='593' u='r' c='_ZN12_GLOBAL__N_123ConstantOffsetExtractor19findInEitherOperandEPN4llvm14BinaryOperatorEbb'/>
<use f='llvm/llvm/lib/Transforms/Scalar/SeparateConstOffsetFromGEP.cpp' l='736' u='r' c='_ZN12_GLOBAL__N_123ConstantOffsetExtractor17removeConstOffsetEj'/>
<use f='llvm/llvm/lib/Transforms/Scalar/SeparateConstOffsetFromGEP.cpp' l='1330' u='r' c='_ZN12_GLOBAL__N_126SeparateConstOffsetFromGEP20isLegalToSwapOperandEPN4llvm17GetElementPtrInstES3_PNS1_4LoopE'/>
<use f='llvm/llvm/lib/Transforms/Scalar/SpeculativeExecution.cpp' l='223' c='_ZN4llvmL22ComputeSpeculationCostEPKNS_11InstructionERKNS_19TargetTransformInfoE'/>
<use f='llvm/llvm/lib/Transforms/Utils/CanonicalizeFreezeInLoops.cpp' l='89' u='r' c='_ZN12_GLOBAL__N_129CanonicalizeFreezeInLoopsImpl13canHandleInstEPKN4llvm11InstructionE'/>
<use f='llvm/llvm/lib/Transforms/Utils/Local.cpp' l='1852' c='_ZN4llvm20salvageDebugInfoImplERNS_11InstructionEPNS_12DIExpressionEb'/>
<use f='llvm/llvm/lib/Transforms/Utils/LoopRotationUtils.cpp' l='715' c='_ZL21shouldSpeculateInstrsN4llvm14ilist_iteratorINS_12ilist_detail12node_optionsINS_11InstructionELb0ELb0EvEELb0ELb0EEES5_PNS_4LoopE'/>
<use f='llvm/llvm/lib/Transforms/Utils/ScalarEvolutionExpander.cpp' l='769' u='r' c='_ZN4llvm12SCEVExpander12visitAddExprEPKNS_11SCEVAddExprE'/>
<use f='llvm/llvm/lib/Transforms/Utils/ScalarEvolutionExpander.cpp' l='852' u='r' c='_ZN4llvm12SCEVExpander12visitMulExprEPKNS_11SCEVMulExprE'/>
<use f='llvm/llvm/lib/Transforms/Utils/ScalarEvolutionExpander.cpp' l='972' c='_ZN4llvm12SCEVExpander15getIVIncOperandEPNS_11InstructionES2_b'/>
<use f='llvm/llvm/lib/Transforms/Utils/SimplifyIndVar.cpp' l='417' c='_ZL15willNotOverflowPN4llvm15ScalarEvolutionENS_11Instruction9BinaryOpsEbPKNS_4SCEVES6_'/>
<use f='llvm/llvm/lib/Transforms/Utils/SimplifyIndVar.cpp' l='746' u='r' c='_ZN12_GLOBAL__N_114SimplifyIndvar30strengthenOverflowingOperationEPN4llvm14BinaryOperatorEPNS1_5ValueE'/>
<use f='llvm/llvm/lib/Transforms/Utils/SimplifyIndVar.cpp' l='1192' c='_ZN7WidenIV11cloneIVUserENS_14NarrowIVDefUseEPKN4llvm14SCEVAddRecExprE'/>
<use f='llvm/llvm/lib/Transforms/Utils/SimplifyIndVar.cpp' l='1318' c='_ZNK7WidenIV15getSCEVByOpCodeEPKN4llvm4SCEVES3_j'/>
<use f='llvm/llvm/lib/Transforms/Utils/SimplifyIndVar.cpp' l='1339' u='r' c='_ZN7WidenIV28getExtendedOperandRecurrenceENS_14NarrowIVDefUseE'/>
<use f='llvm/llvm/lib/Transforms/Utils/SimplifyIndVar.cpp' l='1511' u='r' c='_ZN7WidenIV19widenWithVariantUseENS_14NarrowIVDefUseE'/>
<use f='llvm/llvm/lib/Transforms/Vectorize/LoopVectorize.cpp' l='4784' c='_ZN4llvm19InnerLoopVectorizer16widenInstructionERNS_11InstructionEPNS_7VPValueERNS_6VPUserERNS_16VPTransformStateE'/>
<use f='llvm/llvm/lib/Transforms/Vectorize/LoopVectorize.cpp' l='7274' c='_ZN4llvm26LoopVectorizationCostModel18getInstructionCostEPNS_11InstructionENS_12ElementCountERPNS_4TypeE'/>
<use f='llvm/llvm/lib/Transforms/Vectorize/LoopVectorize.cpp' l='8451' c='_ZNK4llvm15VPRecipeBuilder10tryToWidenEPNS_11InstructionERNS_5VPlanE'/>
<use f='llvm/llvm/lib/Transforms/Vectorize/SLPVectorizer.cpp' l='3000' c='_ZN4llvm13slpvectorizer7BoUpSLP13buildTree_recENS_8ArrayRefIPNS_5ValueEEEjRKNS1_8EdgeInfoE'/>
<use f='llvm/llvm/lib/Transforms/Vectorize/SLPVectorizer.cpp' l='3664' c='_ZN4llvm13slpvectorizer7BoUpSLP12getEntryCostEPNS1_9TreeEntryE'/>
<use f='llvm/llvm/lib/Transforms/Vectorize/SLPVectorizer.cpp' l='4545' c='_ZN4llvm13slpvectorizer7BoUpSLP13vectorizeTreeEPNS1_9TreeEntryE'/>
<use f='llvm/llvm/lib/Transforms/Vectorize/SLPVectorizer.cpp' l='5641' c='_ZL21collectValuesToDemotePN4llvm5ValueERNS_15SmallPtrSetImplIS1_EERNS_15SmallVectorImplIS1_EES7_'/>
<use f='llvm/llvm/tools/llvm-stress/llvm-stress.cpp' l='396' u='r' c='_ZN4llvm12_GLOBAL__N_111BinModifier3ActEv'/>
<use f='llvm/llvm/unittests/IR/ConstantRangeTest.cpp' l='1538' u='r' c='_ZN12_GLOBAL__N_145ConstantRange_MakeGuaranteedNoWrapRegion_Test8TestBodyEv'/>
<use f='llvm/llvm/unittests/IR/ConstantRangeTest.cpp' l='1543' u='r' c='_ZN12_GLOBAL__N_145ConstantRange_MakeGuaranteedNoWrapRegion_Test8TestBodyEv'/>
<use f='llvm/llvm/unittests/IR/ConstantRangeTest.cpp' l='1569' u='r' c='_ZN12_GLOBAL__N_145ConstantRange_MakeGuaranteedNoWrapRegion_Test8TestBodyEv'/>
<use f='llvm/llvm/unittests/IR/ConstantRangeTest.cpp' l='1581' u='r' c='_ZN12_GLOBAL__N_145ConstantRange_MakeGuaranteedNoWrapRegion_Test8TestBodyEv'/>
<use f='llvm/llvm/unittests/IR/ConstantRangeTest.cpp' l='1591' u='r' c='_ZN12_GLOBAL__N_145ConstantRange_MakeGuaranteedNoWrapRegion_Test8TestBodyEv'/>
<use f='llvm/llvm/unittests/IR/ConstantRangeTest.cpp' l='1593' u='r' c='_ZN12_GLOBAL__N_145ConstantRange_MakeGuaranteedNoWrapRegion_Test8TestBodyEv'/>
<use f='llvm/llvm/unittests/IR/ConstantRangeTest.cpp' l='1604' u='r' c='_ZN12_GLOBAL__N_145ConstantRange_MakeGuaranteedNoWrapRegion_Test8TestBodyEv'/>
<use f='llvm/llvm/unittests/IR/ConstantRangeTest.cpp' l='1604' u='r' c='_ZN12_GLOBAL__N_145ConstantRange_MakeGuaranteedNoWrapRegion_Test8TestBodyEv'/>
<use f='llvm/llvm/unittests/IR/ConstantRangeTest.cpp' l='1608' u='r' c='_ZN12_GLOBAL__N_145ConstantRange_MakeGuaranteedNoWrapRegion_Test8TestBodyEv'/>
<use f='llvm/llvm/unittests/IR/ConstantRangeTest.cpp' l='1608' u='r' c='_ZN12_GLOBAL__N_145ConstantRange_MakeGuaranteedNoWrapRegion_Test8TestBodyEv'/>
<use f='llvm/llvm/unittests/IR/ConstantRangeTest.cpp' l='1620' u='r' c='_ZN12_GLOBAL__N_145ConstantRange_MakeGuaranteedNoWrapRegion_Test8TestBodyEv'/>
<use f='llvm/llvm/unittests/IR/ConstantRangeTest.cpp' l='1620' u='r' c='_ZN12_GLOBAL__N_145ConstantRange_MakeGuaranteedNoWrapRegion_Test8TestBodyEv'/>
<use f='llvm/llvm/unittests/IR/ConstantRangeTest.cpp' l='1624' u='r' c='_ZN12_GLOBAL__N_145ConstantRange_MakeGuaranteedNoWrapRegion_Test8TestBodyEv'/>
<use f='llvm/llvm/unittests/IR/ConstantRangeTest.cpp' l='1624' u='r' c='_ZN12_GLOBAL__N_145ConstantRange_MakeGuaranteedNoWrapRegion_Test8TestBodyEv'/>
<use f='llvm/llvm/unittests/IR/ConstantRangeTest.cpp' l='1637' u='r' c='_ZN12_GLOBAL__N_145ConstantRange_MakeGuaranteedNoWrapRegion_Test8TestBodyEv'/>
<use f='llvm/llvm/unittests/IR/ConstantRangeTest.cpp' l='1637' u='r' c='_ZN12_GLOBAL__N_145ConstantRange_MakeGuaranteedNoWrapRegion_Test8TestBodyEv'/>
<use f='llvm/llvm/unittests/IR/ConstantRangeTest.cpp' l='1641' u='r' c='_ZN12_GLOBAL__N_145ConstantRange_MakeGuaranteedNoWrapRegion_Test8TestBodyEv'/>
<use f='llvm/llvm/unittests/IR/ConstantRangeTest.cpp' l='1641' u='r' c='_ZN12_GLOBAL__N_145ConstantRange_MakeGuaranteedNoWrapRegion_Test8TestBodyEv'/>
<use f='llvm/llvm/unittests/IR/ConstantRangeTest.cpp' l='1654' u='r' c='_ZN12_GLOBAL__N_145ConstantRange_MakeGuaranteedNoWrapRegion_Test8TestBodyEv'/>
<use f='llvm/llvm/unittests/IR/ConstantRangeTest.cpp' l='1654' u='r' c='_ZN12_GLOBAL__N_145ConstantRange_MakeGuaranteedNoWrapRegion_Test8TestBodyEv'/>
<use f='llvm/llvm/unittests/IR/ConstantRangeTest.cpp' l='1658' u='r' c='_ZN12_GLOBAL__N_145ConstantRange_MakeGuaranteedNoWrapRegion_Test8TestBodyEv'/>
<use f='llvm/llvm/unittests/IR/ConstantRangeTest.cpp' l='1658' u='r' c='_ZN12_GLOBAL__N_145ConstantRange_MakeGuaranteedNoWrapRegion_Test8TestBodyEv'/>
<use f='llvm/llvm/unittests/IR/ConstantRangeTest.cpp' l='1774' u='r' c='_ZN12_GLOBAL__N_141ConstantRange_NoWrapRegionExhaustive_Test8TestBodyEv'/>
<use f='llvm/llvm/unittests/IR/ConstantRangeTest.cpp' l='1781' u='r' c='_ZN12_GLOBAL__N_141ConstantRange_NoWrapRegionExhaustive_Test8TestBodyEv'/>
<use f='llvm/llvm/unittests/Transforms/Utils/CloningTest.cpp' l='72' u='r' c='_ZN12_GLOBAL__N_134CloneInstruction_OverflowBits_Test8TestBodyEv'/>
<use f='llvm/llvm/unittests/Transforms/Utils/IntegerDivisionTest.cpp' l='49' u='r' c='_ZN12_GLOBAL__N_125IntegerDivision_SDiv_Test8TestBodyEv'/>
<use f='llvm/llvm/unittests/Transforms/Utils/IntegerDivisionTest.cpp' l='109' u='r' c='_ZN12_GLOBAL__N_125IntegerDivision_SRem_Test8TestBodyEv'/>
<use f='llvm/llvm/unittests/Transforms/Utils/IntegerDivisionTest.cpp' l='139' u='r' c='_ZN12_GLOBAL__N_125IntegerDivision_URem_Test8TestBodyEv'/>
<use f='llvm/llvm/unittests/Transforms/Utils/IntegerDivisionTest.cpp' l='170' u='r' c='_ZN12_GLOBAL__N_127IntegerDivision_SDiv64_Test8TestBodyEv'/>
<use f='llvm/llvm/unittests/Transforms/Utils/IntegerDivisionTest.cpp' l='230' u='r' c='_ZN12_GLOBAL__N_127IntegerDivision_SRem64_Test8TestBodyEv'/>
<use f='llvm/llvm/unittests/Transforms/Utils/IntegerDivisionTest.cpp' l='260' u='r' c='_ZN12_GLOBAL__N_127IntegerDivision_URem64_Test8TestBodyEv'/>
<use f='llvm/llvm/unittests/Transforms/Vectorize/VPlanTest.cpp' l='329' u='r' c='_ZN4llvm12_GLOBAL__N_127VPBasicBlockTest_print_Test8TestBodyEv'/>
<use f='llvm/polly/lib/CodeGen/IslExprBuilder.cpp' l='106' c='_ZN5polly14IslExprBuilder11createBinOpEN4llvm11Instruction9BinaryOpsEPNS1_5ValueES5_RKNS1_5TwineE'/>
<use f='llvm/polly/lib/CodeGen/IslExprBuilder.cpp' l='122' c='_ZN5polly14IslExprBuilder11createBinOpEN4llvm11Instruction9BinaryOpsEPNS1_5ValueES5_RKNS1_5TwineE'/>
<use f='llvm/polly/lib/CodeGen/IslExprBuilder.cpp' l='157' u='r' c='_ZN5polly14IslExprBuilder9createSubEPN4llvm5ValueES3_RKNS1_5TwineE'/>
