<dec f='llvm/build/lib/Target/Mips/MipsGenInstrInfo.inc' l='840' type='825'/>
<use f='llvm/build/lib/Target/Mips/MipsGenAsmMatcher.inc' l='5631'/>
<use f='llvm/build/lib/Target/Mips/MipsGenMCCodeEmitter.inc' l='4762' c='_ZNK4llvm17MipsMCCodeEmitter21getBinaryCodeForInstrERKNS_6MCInstERNS_15SmallVectorImplINS_7MCFixupEEERKNS_15MCSubtargetInfoE'/>
<use f='llvm/llvm/lib/Target/Mips/MCTargetDesc/MipsNaClELFStreamer.cpp' l='83' c='_ZN12_GLOBAL__N_119MipsNaClELFStreamer6isCallERKN4llvm6MCInstEPb'/>
<use f='llvm/llvm/lib/Target/Mips/MipsInstrInfo.cpp' l='283' c='_ZNK4llvm13MipsInstrInfo21isBranchOffsetInRangeEjl'/>
<use f='llvm/llvm/lib/Target/Mips/MipsInstrInfo.cpp' l='479' c='_ZNK4llvm13MipsInstrInfo24getEquivalentCompactFormENS_26MachineInstrBundleIteratorINS_12MachineInstrELb0EEE'/>
