<dec f='llvm/llvm/include/llvm/Analysis/IRSimilarityIdentifier.h' l='330' type='llvm::IRSimilarity::IRInstructionDataList *'/>
<use f='llvm/llvm/include/llvm/Analysis/IRSimilarityIdentifier.h' l='378' u='w' c='_ZN4llvm12IRSimilarity19IRInstructionMapperC1EPNS_24SpecificBumpPtrAllocatorINS0_17IRInstructionDataEEEPNS2_INS0_21IRInstructionDataListEEE'/>
<use f='llvm/llvm/lib/Analysis/IRSimilarityIdentifier.cpp' l='180' u='r' c='_ZN4llvm12IRSimilarity19IRInstructionMapper20convertToUnsignedVecERNS_10BasicBlockERSt6vectorIPNS0_17IRInstructionDataESaIS6_EERS4_IjSaIjEE'/>
<use f='llvm/llvm/lib/Analysis/IRSimilarityIdentifier.cpp' l='203' u='r' c='_ZN4llvm12IRSimilarity19IRInstructionMapper18mapToLegalUnsignedERNS_14ilist_iteratorINS_12ilist_detail12node_optionsINS_11InstructionELb0ELb0EvEELb0EL14991152'/>
<use f='llvm/llvm/lib/Analysis/IRSimilarityIdentifier.cpp' l='257' u='r' c='_ZN4llvm12IRSimilarity19IRInstructionMapper20mapToIllegalUnsignedERNS_14ilist_iteratorINS_12ilist_detail12node_optionsINS_11InstructionELb0ELb0EvEELb010489967'/>
<offset>448</offset>
