<dec f='llvm/llvm/include/llvm/Remarks/BitstreamRemarkSerializer.h' l='54' type='SmallVector&lt;uint64_t, 64&gt;'/>
<use f='llvm/llvm/lib/Remarks/BitstreamRemarkSerializer.cpp' l='21' u='w' c='_ZN4llvm7remarks31BitstreamRemarkSerializerHelperC1ENS0_28BitstreamRemarkContainerTypeE'/>
<use f='llvm/llvm/lib/Remarks/BitstreamRemarkSerializer.cpp' l='49' u='a' c='_ZN4llvm7remarks31BitstreamRemarkSerializerHelper18setupMetaBlockInfoEv'/>
<use f='llvm/llvm/lib/Remarks/BitstreamRemarkSerializer.cpp' l='52' u='a' c='_ZN4llvm7remarks31BitstreamRemarkSerializerHelper18setupMetaBlockInfoEv'/>
<use f='llvm/llvm/lib/Remarks/BitstreamRemarkSerializer.cpp' l='64' u='a' c='_ZN4llvm7remarks31BitstreamRemarkSerializerHelper22setupMetaRemarkVersionEv'/>
<use f='llvm/llvm/lib/Remarks/BitstreamRemarkSerializer.cpp' l='77' u='m' c='_ZN4llvm7remarks31BitstreamRemarkSerializerHelper21emitMetaRemarkVersionEm'/>
<use f='llvm/llvm/lib/Remarks/BitstreamRemarkSerializer.cpp' l='78' u='m' c='_ZN4llvm7remarks31BitstreamRemarkSerializerHelper21emitMetaRemarkVersionEm'/>
<use f='llvm/llvm/lib/Remarks/BitstreamRemarkSerializer.cpp' l='79' u='m' c='_ZN4llvm7remarks31BitstreamRemarkSerializerHelper21emitMetaRemarkVersionEm'/>
<use f='llvm/llvm/lib/Remarks/BitstreamRemarkSerializer.cpp' l='80' u='r' c='_ZN4llvm7remarks31BitstreamRemarkSerializerHelper21emitMetaRemarkVersionEm'/>
<use f='llvm/llvm/lib/Remarks/BitstreamRemarkSerializer.cpp' l='84' u='a' c='_ZN4llvm7remarks31BitstreamRemarkSerializerHelper15setupMetaStrTabEv'/>
<use f='llvm/llvm/lib/Remarks/BitstreamRemarkSerializer.cpp' l='96' u='m' c='_ZN4llvm7remarks31BitstreamRemarkSerializerHelper14emitMetaStrTabERKNS0_11StringTableE'/>
<use f='llvm/llvm/lib/Remarks/BitstreamRemarkSerializer.cpp' l='97' u='m' c='_ZN4llvm7remarks31BitstreamRemarkSerializerHelper14emitMetaStrTabERKNS0_11StringTableE'/>
<use f='llvm/llvm/lib/Remarks/BitstreamRemarkSerializer.cpp' l='104' u='r' c='_ZN4llvm7remarks31BitstreamRemarkSerializerHelper14emitMetaStrTabERKNS0_11StringTableE'/>
<use f='llvm/llvm/lib/Remarks/BitstreamRemarkSerializer.cpp' l='108' u='a' c='_ZN4llvm7remarks31BitstreamRemarkSerializerHelper21setupMetaExternalFileEv'/>
<use f='llvm/llvm/lib/Remarks/BitstreamRemarkSerializer.cpp' l='119' u='m' c='_ZN4llvm7remarks31BitstreamRemarkSerializerHelper20emitMetaExternalFileENS_9StringRefE'/>
<use f='llvm/llvm/lib/Remarks/BitstreamRemarkSerializer.cpp' l='120' u='m' c='_ZN4llvm7remarks31BitstreamRemarkSerializerHelper20emitMetaExternalFileENS_9StringRefE'/>
<use f='llvm/llvm/lib/Remarks/BitstreamRemarkSerializer.cpp' l='121' u='r' c='_ZN4llvm7remarks31BitstreamRemarkSerializerHelper20emitMetaExternalFileENS_9StringRefE'/>
<use f='llvm/llvm/lib/Remarks/BitstreamRemarkSerializer.cpp' l='126' u='a' c='_ZN4llvm7remarks31BitstreamRemarkSerializerHelper20setupRemarkBlockInfoEv'/>
<use f='llvm/llvm/lib/Remarks/BitstreamRemarkSerializer.cpp' l='130' u='a' c='_ZN4llvm7remarks31BitstreamRemarkSerializerHelper20setupRemarkBlockInfoEv'/>
<use f='llvm/llvm/lib/Remarks/BitstreamRemarkSerializer.cpp' l='144' u='a' c='_ZN4llvm7remarks31BitstreamRemarkSerializerHelper20setupRemarkBlockInfoEv'/>
<use f='llvm/llvm/lib/Remarks/BitstreamRemarkSerializer.cpp' l='157' u='a' c='_ZN4llvm7remarks31BitstreamRemarkSerializerHelper20setupRemarkBlockInfoEv'/>
<use f='llvm/llvm/lib/Remarks/BitstreamRemarkSerializer.cpp' l='168' u='a' c='_ZN4llvm7remarks31BitstreamRemarkSerializerHelper20setupRemarkBlockInfoEv'/>
<use f='llvm/llvm/lib/Remarks/BitstreamRemarkSerializer.cpp' l='184' u='a' c='_ZN4llvm7remarks31BitstreamRemarkSerializerHelper20setupRemarkBlockInfoEv'/>
<use f='llvm/llvm/lib/Remarks/BitstreamRemarkSerializer.cpp' l='240' u='m' c='_ZN4llvm7remarks31BitstreamRemarkSerializerHelper13emitMetaBlockEmNS_8OptionalImEENS2_IPKNS0_11StringTableEEENS2_INS_9StringRefEEE'/>
<use f='llvm/llvm/lib/Remarks/BitstreamRemarkSerializer.cpp' l='241' u='m' c='_ZN4llvm7remarks31BitstreamRemarkSerializerHelper13emitMetaBlockEmNS_8OptionalImEENS2_IPKNS0_11StringTableEEENS2_INS_9StringRefEEE'/>
<use f='llvm/llvm/lib/Remarks/BitstreamRemarkSerializer.cpp' l='242' u='m' c='_ZN4llvm7remarks31BitstreamRemarkSerializerHelper13emitMetaBlockEmNS_8OptionalImEENS2_IPKNS0_11StringTableEEENS2_INS_9StringRefEEE'/>
<use f='llvm/llvm/lib/Remarks/BitstreamRemarkSerializer.cpp' l='243' u='m' c='_ZN4llvm7remarks31BitstreamRemarkSerializerHelper13emitMetaBlockEmNS_8OptionalImEENS2_IPKNS0_11StringTableEEENS2_INS_9StringRefEEE'/>
<use f='llvm/llvm/lib/Remarks/BitstreamRemarkSerializer.cpp' l='244' u='r' c='_ZN4llvm7remarks31BitstreamRemarkSerializerHelper13emitMetaBlockEmNS_8OptionalImEENS2_IPKNS0_11StringTableEEENS2_INS_9StringRefEEE'/>
<use f='llvm/llvm/lib/Remarks/BitstreamRemarkSerializer.cpp' l='272' u='m' c='_ZN4llvm7remarks31BitstreamRemarkSerializerHelper15emitRemarkBlockERKNS0_6RemarkERNS0_11StringTableE'/>
<use f='llvm/llvm/lib/Remarks/BitstreamRemarkSerializer.cpp' l='273' u='m' c='_ZN4llvm7remarks31BitstreamRemarkSerializerHelper15emitRemarkBlockERKNS0_6RemarkERNS0_11StringTableE'/>
<use f='llvm/llvm/lib/Remarks/BitstreamRemarkSerializer.cpp' l='274' u='m' c='_ZN4llvm7remarks31BitstreamRemarkSerializerHelper15emitRemarkBlockERKNS0_6RemarkERNS0_11StringTableE'/>
<use f='llvm/llvm/lib/Remarks/BitstreamRemarkSerializer.cpp' l='275' u='m' c='_ZN4llvm7remarks31BitstreamRemarkSerializerHelper15emitRemarkBlockERKNS0_6RemarkERNS0_11StringTableE'/>
<use f='llvm/llvm/lib/Remarks/BitstreamRemarkSerializer.cpp' l='276' u='m' c='_ZN4llvm7remarks31BitstreamRemarkSerializerHelper15emitRemarkBlockERKNS0_6RemarkERNS0_11StringTableE'/>
<use f='llvm/llvm/lib/Remarks/BitstreamRemarkSerializer.cpp' l='277' u='m' c='_ZN4llvm7remarks31BitstreamRemarkSerializerHelper15emitRemarkBlockERKNS0_6RemarkERNS0_11StringTableE'/>
<use f='llvm/llvm/lib/Remarks/BitstreamRemarkSerializer.cpp' l='278' u='r' c='_ZN4llvm7remarks31BitstreamRemarkSerializerHelper15emitRemarkBlockERKNS0_6RemarkERNS0_11StringTableE'/>
<use f='llvm/llvm/lib/Remarks/BitstreamRemarkSerializer.cpp' l='281' u='m' c='_ZN4llvm7remarks31BitstreamRemarkSerializerHelper15emitRemarkBlockERKNS0_6RemarkERNS0_11StringTableE'/>
<use f='llvm/llvm/lib/Remarks/BitstreamRemarkSerializer.cpp' l='282' u='m' c='_ZN4llvm7remarks31BitstreamRemarkSerializerHelper15emitRemarkBlockERKNS0_6RemarkERNS0_11StringTableE'/>
<use f='llvm/llvm/lib/Remarks/BitstreamRemarkSerializer.cpp' l='283' u='m' c='_ZN4llvm7remarks31BitstreamRemarkSerializerHelper15emitRemarkBlockERKNS0_6RemarkERNS0_11StringTableE'/>
<use f='llvm/llvm/lib/Remarks/BitstreamRemarkSerializer.cpp' l='284' u='m' c='_ZN4llvm7remarks31BitstreamRemarkSerializerHelper15emitRemarkBlockERKNS0_6RemarkERNS0_11StringTableE'/>
<use f='llvm/llvm/lib/Remarks/BitstreamRemarkSerializer.cpp' l='285' u='m' c='_ZN4llvm7remarks31BitstreamRemarkSerializerHelper15emitRemarkBlockERKNS0_6RemarkERNS0_11StringTableE'/>
<use f='llvm/llvm/lib/Remarks/BitstreamRemarkSerializer.cpp' l='286' u='r' c='_ZN4llvm7remarks31BitstreamRemarkSerializerHelper15emitRemarkBlockERKNS0_6RemarkERNS0_11StringTableE'/>
<use f='llvm/llvm/lib/Remarks/BitstreamRemarkSerializer.cpp' l='290' u='m' c='_ZN4llvm7remarks31BitstreamRemarkSerializerHelper15emitRemarkBlockERKNS0_6RemarkERNS0_11StringTableE'/>
<use f='llvm/llvm/lib/Remarks/BitstreamRemarkSerializer.cpp' l='291' u='m' c='_ZN4llvm7remarks31BitstreamRemarkSerializerHelper15emitRemarkBlockERKNS0_6RemarkERNS0_11StringTableE'/>
<use f='llvm/llvm/lib/Remarks/BitstreamRemarkSerializer.cpp' l='292' u='m' c='_ZN4llvm7remarks31BitstreamRemarkSerializerHelper15emitRemarkBlockERKNS0_6RemarkERNS0_11StringTableE'/>
<use f='llvm/llvm/lib/Remarks/BitstreamRemarkSerializer.cpp' l='293' u='r' c='_ZN4llvm7remarks31BitstreamRemarkSerializerHelper15emitRemarkBlockERKNS0_6RemarkERNS0_11StringTableE'/>
<use f='llvm/llvm/lib/Remarks/BitstreamRemarkSerializer.cpp' l='297' u='m' c='_ZN4llvm7remarks31BitstreamRemarkSerializerHelper15emitRemarkBlockERKNS0_6RemarkERNS0_11StringTableE'/>
<use f='llvm/llvm/lib/Remarks/BitstreamRemarkSerializer.cpp' l='301' u='m' c='_ZN4llvm7remarks31BitstreamRemarkSerializerHelper15emitRemarkBlockERKNS0_6RemarkERNS0_11StringTableE'/>
<use f='llvm/llvm/lib/Remarks/BitstreamRemarkSerializer.cpp' l='303' u='m' c='_ZN4llvm7remarks31BitstreamRemarkSerializerHelper15emitRemarkBlockERKNS0_6RemarkERNS0_11StringTableE'/>
<use f='llvm/llvm/lib/Remarks/BitstreamRemarkSerializer.cpp' l='304' u='m' c='_ZN4llvm7remarks31BitstreamRemarkSerializerHelper15emitRemarkBlockERKNS0_6RemarkERNS0_11StringTableE'/>
<use f='llvm/llvm/lib/Remarks/BitstreamRemarkSerializer.cpp' l='306' u='m' c='_ZN4llvm7remarks31BitstreamRemarkSerializerHelper15emitRemarkBlockERKNS0_6RemarkERNS0_11StringTableE'/>
<use f='llvm/llvm/lib/Remarks/BitstreamRemarkSerializer.cpp' l='307' u='m' c='_ZN4llvm7remarks31BitstreamRemarkSerializerHelper15emitRemarkBlockERKNS0_6RemarkERNS0_11StringTableE'/>
<use f='llvm/llvm/lib/Remarks/BitstreamRemarkSerializer.cpp' l='308' u='m' c='_ZN4llvm7remarks31BitstreamRemarkSerializerHelper15emitRemarkBlockERKNS0_6RemarkERNS0_11StringTableE'/>
<use f='llvm/llvm/lib/Remarks/BitstreamRemarkSerializer.cpp' l='313' u='r' c='_ZN4llvm7remarks31BitstreamRemarkSerializerHelper15emitRemarkBlockERKNS0_6RemarkERNS0_11StringTableE'/>
<offset>8384</offset>
<doc f='llvm/llvm/include/llvm/Remarks/BitstreamRemarkSerializer.h' l='53'>/// Buffer used to construct records and pass to the bitstream writer.</doc>
