<use f='llvm/llvm/include/llvm/ExecutionEngine/JITLink/JITLink.h' l='73' u='w' c='_ZN4llvm7jitlink4EdgeC1EhjRNS0_6SymbolEl'/>
<use f='llvm/llvm/include/llvm/ExecutionEngine/JITLink/JITLink.h' l='77' u='r' c='_ZNK4llvm7jitlink4Edge7getKindEv'/>
<use f='llvm/llvm/include/llvm/ExecutionEngine/JITLink/JITLink.h' l='78' u='w' c='_ZN4llvm7jitlink4Edge7setKindEh'/>
<use f='llvm/llvm/include/llvm/ExecutionEngine/JITLink/JITLink.h' l='79' u='r' c='_ZNK4llvm7jitlink4Edge12isRelocationEv'/>
<use f='llvm/llvm/include/llvm/ExecutionEngine/JITLink/JITLink.h' l='82' u='r' c='_ZNK4llvm7jitlink4Edge13getRelocationEv'/>
<use f='llvm/llvm/include/llvm/ExecutionEngine/JITLink/JITLink.h' l='84' u='r' c='_ZNK4llvm7jitlink4Edge11isKeepAliveEv'/>
<dec f='llvm/llvm/include/llvm/ExecutionEngine/JITLink/JITLink.h' l='94' type='llvm::jitlink::Edge::Kind'/>
<offset>192</offset>
