<use f='llvm/llvm/include/llvm/Transforms/Utils/Cloning.h' l='180' u='w' c='_ZN4llvm18InlineFunctionInfoC1EPNS_9CallGraphENS_12function_refIFRNS_15AssumptionCacheERNS_8FunctionEEEEPNS_18ProfileSummaryInfoEPNS_18BlockFrequencyInfoESD_'/>
<dec f='llvm/llvm/include/llvm/Transforms/Utils/Cloning.h' l='185' type='llvm::CallGraph *'/>
<offset>0</offset>
<doc f='llvm/llvm/include/llvm/Transforms/Utils/Cloning.h' l='183'>/// If non-null, InlineFunction will update the callgraph to reflect the
  /// changes it makes.</doc>
<use f='llvm/llvm/lib/Transforms/Utils/InlineFunction.cpp' l='1310' u='r' c='_ZL28UpdateCallGraphAfterInliningRN4llvm8CallBaseENS_14ilist_iteratorINS_12ilist_detail12node_optionsINS_10BasicBlockELb0ELb0EvEELb0ELb0EEERNS_8ValueM12548040'/>
<use f='llvm/llvm/lib/Transforms/Utils/InlineFunction.cpp' l='1918' u='r' c='_ZN4llvm14InlineFunctionERNS_8CallBaseERNS_18InlineFunctionInfoEPNS_9AAResultsEbPNS_8FunctionE'/>
<use f='llvm/llvm/lib/Transforms/Utils/InlineFunction.cpp' l='2333' u='r' c='_ZN4llvm14InlineFunctionERNS_8CallBaseERNS_18InlineFunctionInfoEPNS_9AAResultsEbPNS_8FunctionE'/>
