<dec f='llvm/llvm/include/llvm/Support/VirtualFileSystem.h' l='210' type='llvm::vfs::FileSystem *'/>
<offset>0</offset>
<use f='llvm/llvm/lib/Support/VirtualFileSystem.cpp' l='2264' u='w' c='_ZN4llvm3vfs28recursive_directory_iteratorC1ERNS0_10FileSystemERKNS_5TwineERSt10error_code'/>
<use f='llvm/llvm/lib/Support/VirtualFileSystem.cpp' l='2265' u='r' c='_ZN4llvm3vfs28recursive_directory_iteratorC1ERNS0_10FileSystemERKNS_5TwineERSt10error_code'/>
<use f='llvm/llvm/lib/Support/VirtualFileSystem.cpp' l='2282' u='r' c='_ZN4llvm3vfs28recursive_directory_iterator9incrementERSt10error_code'/>
