<dec f='llvm/llvm/include/llvm/Analysis/CallGraph.h' l='338' type='std::unique_ptr&lt;CallGraph&gt;'/>
<use f='llvm/llvm/include/llvm/Analysis/CallGraph.h' l='348' u='m' c='_ZNK4llvm20CallGraphWrapperPass12getCallGraphEv'/>
<use f='llvm/llvm/include/llvm/Analysis/CallGraph.h' l='349' u='m' c='_ZN4llvm20CallGraphWrapperPass12getCallGraphEv'/>
<use f='llvm/llvm/include/llvm/Analysis/CallGraph.h' l='355' u='m' c='_ZNK4llvm20CallGraphWrapperPass9getModuleEv'/>
<use f='llvm/llvm/include/llvm/Analysis/CallGraph.h' l='357' u='m' c='_ZN4llvm20CallGraphWrapperPass5beginEv'/>
<use f='llvm/llvm/include/llvm/Analysis/CallGraph.h' l='358' u='m' c='_ZN4llvm20CallGraphWrapperPass3endEv'/>
<use f='llvm/llvm/include/llvm/Analysis/CallGraph.h' l='359' u='m' c='_ZNK4llvm20CallGraphWrapperPass5beginEv'/>
<use f='llvm/llvm/include/llvm/Analysis/CallGraph.h' l='360' u='m' c='_ZNK4llvm20CallGraphWrapperPass3endEv'/>
<use f='llvm/llvm/include/llvm/Analysis/CallGraph.h' l='364' u='m' c='_ZNK4llvm20CallGraphWrapperPassixEPKNS_8FunctionE'/>
<use f='llvm/llvm/include/llvm/Analysis/CallGraph.h' l='368' u='m' c='_ZN4llvm20CallGraphWrapperPassixEPKNS_8FunctionE'/>
<use f='llvm/llvm/include/llvm/Analysis/CallGraph.h' l='373' u='m' c='_ZNK4llvm20CallGraphWrapperPass22getExternalCallingNodeEv'/>
<use f='llvm/llvm/include/llvm/Analysis/CallGraph.h' l='377' u='m' c='_ZNK4llvm20CallGraphWrapperPass20getCallsExternalNodeEv'/>
<use f='llvm/llvm/include/llvm/Analysis/CallGraph.h' l='392' u='m' c='_ZN4llvm20CallGraphWrapperPass24removeFunctionFromModuleEPNS_13CallGraphNodeE'/>
<use f='llvm/llvm/include/llvm/Analysis/CallGraph.h' l='398' u='m' c='_ZN4llvm20CallGraphWrapperPass19getOrInsertFunctionEPKNS_8FunctionE'/>
<offset>256</offset>
<use f='llvm/llvm/lib/Analysis/CallGraph.cpp' l='335' u='m' c='_ZN4llvm20CallGraphWrapperPass11runOnModuleERNS_6ModuleE'/>
<use f='llvm/llvm/lib/Analysis/CallGraph.cpp' l='344' u='m' c='_ZN4llvm20CallGraphWrapperPass13releaseMemoryEv'/>
<use f='llvm/llvm/lib/Analysis/CallGraph.cpp' l='347' u='m' c='_ZNK4llvm20CallGraphWrapperPass5printERNS_11raw_ostreamEPKNS_6ModuleE'/>
<use f='llvm/llvm/lib/Analysis/CallGraph.cpp' l='353' u='m' c='_ZNK4llvm20CallGraphWrapperPass5printERNS_11raw_ostreamEPKNS_6ModuleE'/>
