<dec f='llvm/llvm/include/llvm/Analysis/DominanceFrontier.h' l='199' type='llvm::raw_ostream &amp;'/>
<use f='llvm/llvm/lib/Analysis/DominanceFrontier.cpp' l='89' u='w' c='_ZN4llvm28DominanceFrontierPrinterPassC1ERNS_11raw_ostreamE'/>
<use f='llvm/llvm/lib/Analysis/DominanceFrontier.cpp' l='93' u='m' c='_ZN4llvm28DominanceFrontierPrinterPass3runERNS_8FunctionERNS_15AnalysisManagerIS1_JEEE'/>
<use f='llvm/llvm/lib/Analysis/DominanceFrontier.cpp' l='94' u='a' c='_ZN4llvm28DominanceFrontierPrinterPass3runERNS_8FunctionERNS_15AnalysisManagerIS1_JEEE'/>
<offset>0</offset>
