<dec f='llvm/llvm/include/llvm/CodeGen/FastISel.h' l='208' type='const llvm::TargetMachine &amp;'/>
<use f='llvm/llvm/lib/CodeGen/SelectionDAG/FastISel.cpp' l='956' u='m' c='_ZN4llvm8FastISel21selectXRayCustomEventEPKNS_8CallInstE'/>
<use f='llvm/llvm/lib/CodeGen/SelectionDAG/FastISel.cpp' l='975' u='m' c='_ZN4llvm8FastISel20selectXRayTypedEventEPKNS_8CallInstE'/>
<use f='llvm/llvm/lib/CodeGen/SelectionDAG/FastISel.cpp' l='1195' u='r' c='_ZN4llvm8FastISel9lowerCallEPKNS_8CallInstE'/>
<use f='llvm/llvm/lib/CodeGen/SelectionDAG/FastISel.cpp' l='1795' u='m' c='_ZN4llvm8FastISel14selectOperatorEPKNS_4UserEj'/>
<use f='llvm/llvm/lib/CodeGen/SelectionDAG/FastISel.cpp' l='1814' u='m' c='_ZN4llvm8FastISel14selectOperatorEPKNS_4UserEj'/>
<use f='llvm/llvm/lib/CodeGen/SelectionDAG/FastISel.cpp' l='1867' u='w' c='_ZN4llvm8FastISelC1ERNS_20FunctionLoweringInfoEPKNS_17TargetLibraryInfoEb'/>
<offset>640</offset>
<use f='llvm/llvm/lib/Target/AArch64/AArch64FastISel.cpp' l='418' u='m' c='_ZN12_GLOBAL__N_115AArch64FastISel13materializeFPEPKN4llvm10ConstantFPENS1_3MVTE'/>
<use f='llvm/llvm/lib/Target/AArch64/AArch64FastISel.cpp' l='462' u='r' c='_ZN12_GLOBAL__N_115AArch64FastISel13materializeGVEPKN4llvm11GlobalValueE'/>
<use f='llvm/llvm/lib/Target/AArch64/AArch64FastISel.cpp' l='3208' u='m' c='_ZN12_GLOBAL__N_115AArch64FastISel13fastLowerCallERN4llvm8FastISel16CallLoweringInfoE'/>
<use f='llvm/llvm/lib/Target/X86/X86FastISel.cpp' l='143' u='a' c='_ZNK12_GLOBAL__N_111X86FastISel16getTargetMachineEv'/>
<use f='llvm/llvm/lib/Target/X86/X86FastISel.cpp' l='728' u='m' c='_ZN12_GLOBAL__N_111X86FastISel23handleConstantAddressesEPKN4llvm5ValueERNS1_14X86AddressModeE'/>
<use f='llvm/llvm/lib/Target/X86/X86FastISel.cpp' l='1060' u='m' c='_ZN12_GLOBAL__N_111X86FastISel20X86SelectCallAddressEPKN4llvm5ValueERNS1_14X86AddressModeE'/>
<use f='llvm/llvm/lib/Target/X86/X86FastISel.cpp' l='1205' u='m' c='_ZN12_GLOBAL__N_111X86FastISel12X86SelectRetEPKN4llvm11InstructionE'/>
<use f='llvm/llvm/lib/Target/X86/X86FastISel.cpp' l='3257' u='m' c='_ZN12_GLOBAL__N_111X86FastISel13fastLowerCallERN4llvm8FastISel16CallLoweringInfoE'/>
<use f='llvm/llvm/lib/Target/X86/X86FastISel.cpp' l='3563' u='m' c='_ZN12_GLOBAL__N_111X86FastISel13fastLowerCallERN4llvm8FastISel16CallLoweringInfoE'/>
<use f='llvm/llvm/lib/Target/X86/X86FastISel.cpp' l='3770' u='m' c='_ZN12_GLOBAL__N_111X86FastISel16X86MaterializeFPEPKN4llvm10ConstantFPENS1_3MVTE'/>
<use f='llvm/llvm/lib/Target/X86/X86FastISel.cpp' l='3811' u='m' c='_ZN12_GLOBAL__N_111X86FastISel16X86MaterializeFPEPKN4llvm10ConstantFPENS1_3MVTE'/>
<use f='llvm/llvm/lib/Target/X86/X86FastISel.cpp' l='3842' u='m' c='_ZN12_GLOBAL__N_111X86FastISel16X86MaterializeGVEPKN4llvm11GlobalValueENS1_3MVTE'/>
<use f='llvm/llvm/lib/Target/X86/X86FastISel.cpp' l='3855' u='m' c='_ZN12_GLOBAL__N_111X86FastISel16X86MaterializeGVEPKN4llvm11GlobalValueENS1_3MVTE'/>
