<dec f='llvm/llvm/include/llvm/MC/MCTargetOptions.h' l='30' type='1'/>
<doc f='llvm/llvm/include/llvm/MC/MCTargetOptions.h' l='30'>///&lt; zlib-gnu style compression</doc>
<use f='llvm/clang/tools/driver/cc1as_main.cpp' l='229' u='r' c='_ZN12_GLOBAL__N_119AssemblerInvocation14CreateFromArgsERS0_N4llvm8ArrayRefIPKcEERN5clang17DiagnosticsEngineE'/>
<use f='llvm/llvm/tools/llvm-mc/llvm-mc.cpp' l='71' u='a'/>
<use f='llvm/llvm/tools/llvm-objcopy/CopyConfig.cpp' l='580' u='r' c='_ZN4llvm7objcopy19parseObjcopyOptionsENS_8ArrayRefIPKcEENS_12function_refIFNS_5ErrorES6_EEE'/>
<use f='llvm/llvm/tools/llvm-objcopy/ELF/Object.cpp' l='528' u='r' c='_ZN4llvm7objcopy3elf16ELFSectionWriter5visitERKNS1_17CompressedSectionE'/>
<use f='llvm/llvm/tools/llvm-objcopy/ELF/Object.cpp' l='584' u='r' c='_ZN4llvm7objcopy3elf17CompressedSectionC1ERKNS1_11SectionBaseENS_20DebugCompressionTypeERNS_5ErrorE'/>
