<dec f='llvm/llvm/include/llvm/Transforms/Utils/CallGraphUpdater.h' l='51' type='llvm::CGSCCUpdateResult *'/>
<use f='llvm/llvm/include/llvm/Transforms/Utils/CallGraphUpdater.h' l='71' u='w' c='_ZN4llvm16CallGraphUpdater10initializeERNS_13LazyCallGraphERNS1_3SCCERNS_15AnalysisManagerIS3_JS2_EEERNS_17CGSCCUpdateResultE'/>
<offset>3904</offset>
<use f='llvm/llvm/lib/Transforms/Utils/CallGraphUpdater.cpp' l='72' u='r' c='_ZN4llvm16CallGraphUpdater8finalizeEv'/>
<use f='llvm/llvm/lib/Transforms/Utils/CallGraphUpdater.cpp' l='73' u='r' c='_ZN4llvm16CallGraphUpdater8finalizeEv'/>
<use f='llvm/llvm/lib/Transforms/Utils/CallGraphUpdater.cpp' l='95' u='r' c='_ZN4llvm16CallGraphUpdater17reanalyzeFunctionERNS_8FunctionE'/>
