<dec f='llvm/build/lib/Target/AArch64/AArch64GenRegisterInfo.inc' l='247' type='227'/>
<use f='llvm/llvm/lib/Target/AArch64/Utils/AArch64BaseInfo.h' l='41' c='_ZN4llvmL15getWRegFromXRegEj'/>
<use f='llvm/llvm/lib/Target/AArch64/Utils/AArch64BaseInfo.h' l='81' u='r' c='_ZN4llvmL15getXRegFromWRegEj'/>
<use f='llvm/llvm/lib/Target/AArch64/AArch64SLSHardening.cpp' l='159'/>
<use f='llvm/llvm/lib/Target/AArch64/Disassembler/AArch64Disassembler.cpp' l='435'/>
<use f='llvm/llvm/lib/Target/AArch64/MCTargetDesc/AArch64MCTargetDesc.cpp' l='111' u='r' c='_ZN4llvm10AArch64_MC22initLLVMToCVRegMappingEPNS_14MCRegisterInfoE'/>
