<dec f='llvm/build/lib/Target/RISCV/RISCVGenInstrInfo.inc' l='14504' type='14489'/>
<use f='llvm/build/lib/Target/RISCV/RISCVGenCompressInstEmitter.inc' l='660' c='_ZL12compressInstRN4llvm6MCInstERKS0_RKNS_15MCSubtargetInfoERNS_9MCContextE'/>
<use f='llvm/build/lib/Target/RISCV/RISCVGenAsmMatcher.inc' l='3837'/>
<use f='llvm/build/lib/Target/RISCV/RISCVGenAsmMatcher.inc' l='3838'/>
<use f='llvm/llvm/lib/Target/RISCV/AsmParser/RISCVAsmParser.cpp' l='2252' u='r' c='_ZN12_GLOBAL__N_114RISCVAsmParser15emitLoadAddressERN4llvm6MCInstENS1_5SMLocERNS1_10MCStreamerE'/>
<use f='llvm/llvm/lib/Target/RISCV/AsmParser/RISCVAsmParser.cpp' l='2271' u='r' c='_ZN12_GLOBAL__N_114RISCVAsmParser20emitLoadTLSIEAddressERN4llvm6MCInstENS1_5SMLocERNS1_10MCStreamerE'/>
<use f='llvm/llvm/lib/Target/RISCV/AsmParser/RISCVAsmParser.cpp' l='2518' u='r' c='_ZN12_GLOBAL__N_114RISCVAsmParser18processInstructionERN4llvm6MCInstENS1_5SMLocERNS1_15SmallVectorImplISt10unique_ptrINS1_18MCParsedAsmOperandESt14def15576407'/>
<use f='llvm/build/lib/Target/RISCV/RISCVGenMCCodeEmitter.inc' l='15566' c='_ZNK12_GLOBAL__N_118RISCVMCCodeEmitter21getBinaryCodeForInstrERKN4llvm6MCInstERNS1_15SmallVectorImplINS1_7MCFixupEEERKNS1_15MCSubtargetInfoE'/>
<use f='llvm/llvm/lib/Target/RISCV/RISCVExpandPseudoInsts.cpp' l='188' u='r' c='_ZN12_GLOBAL__N_117RISCVExpandPseudo17expandLoadAddressERN4llvm17MachineBasicBlockENS1_26MachineInstrBundleIteratorINS1_12MachineInstrELb0EEERS6_'/>
<use f='llvm/llvm/lib/Target/RISCV/RISCVExpandPseudoInsts.cpp' l='203' u='r' c='_ZN12_GLOBAL__N_117RISCVExpandPseudo22expandLoadTLSIEAddressERN4llvm17MachineBasicBlockENS1_26MachineInstrBundleIteratorINS1_12MachineInstrELb0EEERS6_'/>
<use f='llvm/llvm/lib/Target/RISCV/RISCVFrameLowering.cpp' l='115' u='r' c='_ZL15emitSCSEpilogueRN4llvm15MachineFunctionERNS_17MachineBasicBlockENS_26MachineInstrBundleIteratorINS_12MachineInstrELb0EEERKNS_8DebugLocE'/>
<use f='llvm/build/lib/Target/RISCV/RISCVGenDAGISel.inc' l='13824' u='r' c='_ZN4llvm17RISCVDAGToDAGISel10SelectCodeEPNS_6SDNodeE'/>
<use f='llvm/build/lib/Target/RISCV/RISCVGenDAGISel.inc' l='13824' u='r' c='_ZN4llvm17RISCVDAGToDAGISel10SelectCodeEPNS_6SDNodeE'/>
<use f='llvm/build/lib/Target/RISCV/RISCVGenDAGISel.inc' l='13943' u='r' c='_ZN4llvm17RISCVDAGToDAGISel10SelectCodeEPNS_6SDNodeE'/>
<use f='llvm/build/lib/Target/RISCV/RISCVGenDAGISel.inc' l='13943' u='r' c='_ZN4llvm17RISCVDAGToDAGISel10SelectCodeEPNS_6SDNodeE'/>
<use f='llvm/build/lib/Target/RISCV/RISCVGenDAGISel.inc' l='14076' u='r' c='_ZN4llvm17RISCVDAGToDAGISel10SelectCodeEPNS_6SDNodeE'/>
<use f='llvm/build/lib/Target/RISCV/RISCVGenDAGISel.inc' l='14076' u='r' c='_ZN4llvm17RISCVDAGToDAGISel10SelectCodeEPNS_6SDNodeE'/>
<use f='llvm/build/lib/Target/RISCV/RISCVGenDAGISel.inc' l='14185' u='r' c='_ZN4llvm17RISCVDAGToDAGISel10SelectCodeEPNS_6SDNodeE'/>
<use f='llvm/build/lib/Target/RISCV/RISCVGenDAGISel.inc' l='14185' u='r' c='_ZN4llvm17RISCVDAGToDAGISel10SelectCodeEPNS_6SDNodeE'/>
<use f='llvm/build/lib/Target/RISCV/RISCVGenDAGISel.inc' l='14304' u='r' c='_ZN4llvm17RISCVDAGToDAGISel10SelectCodeEPNS_6SDNodeE'/>
<use f='llvm/build/lib/Target/RISCV/RISCVGenDAGISel.inc' l='14304' u='r' c='_ZN4llvm17RISCVDAGToDAGISel10SelectCodeEPNS_6SDNodeE'/>
<use f='llvm/build/lib/Target/RISCV/RISCVGenDAGISel.inc' l='14407' u='r' c='_ZN4llvm17RISCVDAGToDAGISel10SelectCodeEPNS_6SDNodeE'/>
<use f='llvm/build/lib/Target/RISCV/RISCVGenDAGISel.inc' l='14407' u='r' c='_ZN4llvm17RISCVDAGToDAGISel10SelectCodeEPNS_6SDNodeE'/>
<use f='llvm/build/lib/Target/RISCV/RISCVGenDAGISel.inc' l='14638' u='r' c='_ZN4llvm17RISCVDAGToDAGISel10SelectCodeEPNS_6SDNodeE'/>
<use f='llvm/build/lib/Target/RISCV/RISCVGenDAGISel.inc' l='14638' u='r' c='_ZN4llvm17RISCVDAGToDAGISel10SelectCodeEPNS_6SDNodeE'/>
<use f='llvm/build/lib/Target/RISCV/RISCVGenDAGISel.inc' l='14647' u='r' c='_ZN4llvm17RISCVDAGToDAGISel10SelectCodeEPNS_6SDNodeE'/>
<use f='llvm/build/lib/Target/RISCV/RISCVGenDAGISel.inc' l='14647' u='r' c='_ZN4llvm17RISCVDAGToDAGISel10SelectCodeEPNS_6SDNodeE'/>
<use f='llvm/build/lib/Target/RISCV/RISCVGenDAGISel.inc' l='14760' u='r' c='_ZN4llvm17RISCVDAGToDAGISel10SelectCodeEPNS_6SDNodeE'/>
<use f='llvm/build/lib/Target/RISCV/RISCVGenDAGISel.inc' l='14760' u='r' c='_ZN4llvm17RISCVDAGToDAGISel10SelectCodeEPNS_6SDNodeE'/>
<use f='llvm/build/lib/Target/RISCV/RISCVGenDAGISel.inc' l='14867' u='r' c='_ZN4llvm17RISCVDAGToDAGISel10SelectCodeEPNS_6SDNodeE'/>
<use f='llvm/build/lib/Target/RISCV/RISCVGenDAGISel.inc' l='14867' u='r' c='_ZN4llvm17RISCVDAGToDAGISel10SelectCodeEPNS_6SDNodeE'/>
<use f='llvm/build/lib/Target/RISCV/RISCVGenDAGISel.inc' l='19930' u='r' c='_ZN4llvm17RISCVDAGToDAGISel10SelectCodeEPNS_6SDNodeE'/>
<use f='llvm/build/lib/Target/RISCV/RISCVGenDAGISel.inc' l='19930' u='r' c='_ZN4llvm17RISCVDAGToDAGISel10SelectCodeEPNS_6SDNodeE'/>
<use f='llvm/build/lib/Target/RISCV/RISCVGenDAGISel.inc' l='19974' u='r' c='_ZN4llvm17RISCVDAGToDAGISel10SelectCodeEPNS_6SDNodeE'/>
<use f='llvm/build/lib/Target/RISCV/RISCVGenDAGISel.inc' l='19974' u='r' c='_ZN4llvm17RISCVDAGToDAGISel10SelectCodeEPNS_6SDNodeE'/>
<use f='llvm/build/lib/Target/RISCV/RISCVGenDAGISel.inc' l='20026' u='r' c='_ZN4llvm17RISCVDAGToDAGISel10SelectCodeEPNS_6SDNodeE'/>
<use f='llvm/build/lib/Target/RISCV/RISCVGenDAGISel.inc' l='20026' u='r' c='_ZN4llvm17RISCVDAGToDAGISel10SelectCodeEPNS_6SDNodeE'/>
<use f='llvm/build/lib/Target/RISCV/RISCVGenDAGISel.inc' l='20062' u='r' c='_ZN4llvm17RISCVDAGToDAGISel10SelectCodeEPNS_6SDNodeE'/>
<use f='llvm/build/lib/Target/RISCV/RISCVGenDAGISel.inc' l='20062' u='r' c='_ZN4llvm17RISCVDAGToDAGISel10SelectCodeEPNS_6SDNodeE'/>
<use f='llvm/build/lib/Target/RISCV/RISCVGenDAGISel.inc' l='20106' u='r' c='_ZN4llvm17RISCVDAGToDAGISel10SelectCodeEPNS_6SDNodeE'/>
<use f='llvm/build/lib/Target/RISCV/RISCVGenDAGISel.inc' l='20106' u='r' c='_ZN4llvm17RISCVDAGToDAGISel10SelectCodeEPNS_6SDNodeE'/>
<use f='llvm/build/lib/Target/RISCV/RISCVGenDAGISel.inc' l='20142' u='r' c='_ZN4llvm17RISCVDAGToDAGISel10SelectCodeEPNS_6SDNodeE'/>
<use f='llvm/build/lib/Target/RISCV/RISCVGenDAGISel.inc' l='20142' u='r' c='_ZN4llvm17RISCVDAGToDAGISel10SelectCodeEPNS_6SDNodeE'/>
<use f='llvm/build/lib/Target/RISCV/RISCVGenDAGISel.inc' l='20221' u='r' c='_ZN4llvm17RISCVDAGToDAGISel10SelectCodeEPNS_6SDNodeE'/>
<use f='llvm/build/lib/Target/RISCV/RISCVGenDAGISel.inc' l='20221' u='r' c='_ZN4llvm17RISCVDAGToDAGISel10SelectCodeEPNS_6SDNodeE'/>
<use f='llvm/build/lib/Target/RISCV/RISCVGenDAGISel.inc' l='20230' u='r' c='_ZN4llvm17RISCVDAGToDAGISel10SelectCodeEPNS_6SDNodeE'/>
<use f='llvm/build/lib/Target/RISCV/RISCVGenDAGISel.inc' l='20230' u='r' c='_ZN4llvm17RISCVDAGToDAGISel10SelectCodeEPNS_6SDNodeE'/>
<use f='llvm/build/lib/Target/RISCV/RISCVGenDAGISel.inc' l='20270' u='r' c='_ZN4llvm17RISCVDAGToDAGISel10SelectCodeEPNS_6SDNodeE'/>
<use f='llvm/build/lib/Target/RISCV/RISCVGenDAGISel.inc' l='20270' u='r' c='_ZN4llvm17RISCVDAGToDAGISel10SelectCodeEPNS_6SDNodeE'/>
<use f='llvm/build/lib/Target/RISCV/RISCVGenDAGISel.inc' l='20310' u='r' c='_ZN4llvm17RISCVDAGToDAGISel10SelectCodeEPNS_6SDNodeE'/>
<use f='llvm/build/lib/Target/RISCV/RISCVGenDAGISel.inc' l='20310' u='r' c='_ZN4llvm17RISCVDAGToDAGISel10SelectCodeEPNS_6SDNodeE'/>
<use f='llvm/llvm/lib/Target/RISCV/RISCVISelDAGToDAG.cpp' l='963' c='_ZN4llvm17RISCVDAGToDAGISel23doPeepholeLoadStoreADDIEv'/>
<use f='llvm/llvm/lib/Target/RISCV/RISCVInstrInfo.cpp' l='52' c='_ZNK4llvm14RISCVInstrInfo19isLoadFromStackSlotERKNS_12MachineInstrERi'/>
<use f='llvm/llvm/lib/Target/RISCV/RISCVInstrInfo.cpp' l='187' u='r' c='_ZNK4llvm14RISCVInstrInfo20loadRegFromStackSlotERNS_17MachineBasicBlockENS_26MachineInstrBundleIteratorINS_12MachineInstrELb0EEENS_8RegisterEiPKNS_19T10987319'/>
<use f='llvm/build/lib/Target/RISCV/RISCVGenGlobalISel.inc' l='9533' u='r' c='_ZNK12_GLOBAL__N_124RISCVInstructionSelector13getMatchTableEv'/>
<use f='llvm/build/lib/Target/RISCV/RISCVGenGlobalISel.inc' l='9593' u='r' c='_ZNK12_GLOBAL__N_124RISCVInstructionSelector13getMatchTableEv'/>
<use f='llvm/build/lib/Target/RISCV/RISCVGenGlobalISel.inc' l='9820' u='r' c='_ZNK12_GLOBAL__N_124RISCVInstructionSelector13getMatchTableEv'/>
<use f='llvm/build/lib/Target/RISCV/RISCVGenGlobalISel.inc' l='9858' u='r' c='_ZNK12_GLOBAL__N_124RISCVInstructionSelector13getMatchTableEv'/>
<use f='llvm/build/lib/Target/RISCV/RISCVGenGlobalISel.inc' l='10076' u='r' c='_ZNK12_GLOBAL__N_124RISCVInstructionSelector13getMatchTableEv'/>
<use f='llvm/build/lib/Target/RISCV/RISCVGenGlobalISel.inc' l='10136' u='r' c='_ZNK12_GLOBAL__N_124RISCVInstructionSelector13getMatchTableEv'/>
<use f='llvm/build/lib/Target/RISCV/RISCVGenGlobalISel.inc' l='10363' u='r' c='_ZNK12_GLOBAL__N_124RISCVInstructionSelector13getMatchTableEv'/>
<use f='llvm/build/lib/Target/RISCV/RISCVGenGlobalISel.inc' l='10401' u='r' c='_ZNK12_GLOBAL__N_124RISCVInstructionSelector13getMatchTableEv'/>
<use f='llvm/llvm/lib/Target/RISCV/RISCVMergeBaseOffset.cpp' l='218' c='_ZN12_GLOBAL__N_123RISCVMergeBaseOffsetOpt19detectAndFoldOffsetERN4llvm12MachineInstrES3_'/>
