<dec f='llvm/llvm/include/llvm/ObjectYAML/ELFYAML.h' l='152' type='llvm::ELFYAML::ELF_DYNTAG'/>
<offset>0</offset>
<use f='llvm/llvm/lib/ObjectYAML/ELFEmitter.cpp' l='1614' c='_ZN12_GLOBAL__N_18ELFState19writeSectionContentERNT_4ShdrERKN4llvm7ELFYAML14DynamicSectionERNS_25ContiguousBlobAccumulatorE'/>
<use f='llvm/llvm/lib/ObjectYAML/ELFYAML.cpp' l='1599' u='a' c='_ZN4llvm4yaml13MappingTraitsINS_7ELFYAML12DynamicEntryEE7mappingERNS0_2IOERS3_'/>
