<use f='llvm/llvm/include/llvm/CodeGen/RDFGraph.h' l='741' u='m' c='_ZN4llvm3rdf13DataFlowGraph4packENS0_11RegisterRefE'/>
<use f='llvm/llvm/include/llvm/CodeGen/RDFGraph.h' l='744' u='m' c='_ZNK4llvm3rdf13DataFlowGraph4packENS0_11RegisterRefE'/>
<use f='llvm/llvm/include/llvm/CodeGen/RDFGraph.h' l='747' u='m' c='_ZNK4llvm3rdf13DataFlowGraph6unpackENS0_17PackedRegisterRefE'/>
<dec f='llvm/llvm/include/llvm/CodeGen/RDFGraph.h' l='879' type='llvm::rdf::LaneMaskIndex'/>
<offset>3328</offset>
<doc f='llvm/llvm/include/llvm/CodeGen/RDFGraph.h' l='878'>// Lane mask map.</doc>
