<dec f='llvm/llvm/unittests/CodeGen/TestAsmPrinter.h' l='52' type='std::unique_ptr&lt;TargetMachine&gt;'/>
<offset>128</offset>
<use f='llvm/llvm/unittests/CodeGen/TestAsmPrinter.cpp' l='52' u='m' c='_ZN4llvm14TestAsmPrinter4initEPKNS_6TargetENS_9StringRefEtNS_5dwarf11DwarfFormatE'/>
<use f='llvm/llvm/unittests/CodeGen/TestAsmPrinter.cpp' l='54' u='m' c='_ZN4llvm14TestAsmPrinter4initEPKNS_6TargetENS_9StringRefEtNS_5dwarf11DwarfFormatE'/>
<use f='llvm/llvm/unittests/CodeGen/TestAsmPrinter.cpp' l='58' u='m' c='_ZN4llvm14TestAsmPrinter4initEPKNS_6TargetENS_9StringRefEtNS_5dwarf11DwarfFormatE'/>
<use f='llvm/llvm/unittests/CodeGen/TestAsmPrinter.cpp' l='58' u='m' c='_ZN4llvm14TestAsmPrinter4initEPKNS_6TargetENS_9StringRefEtNS_5dwarf11DwarfFormatE'/>
<use f='llvm/llvm/unittests/CodeGen/TestAsmPrinter.cpp' l='59' u='m' c='_ZN4llvm14TestAsmPrinter4initEPKNS_6TargetENS_9StringRefEtNS_5dwarf11DwarfFormatE'/>
<use f='llvm/llvm/unittests/CodeGen/TestAsmPrinter.cpp' l='60' u='m' c='_ZN4llvm14TestAsmPrinter4initEPKNS_6TargetENS_9StringRefEtNS_5dwarf11DwarfFormatE'/>
<use f='llvm/llvm/unittests/CodeGen/TestAsmPrinter.cpp' l='60' u='m' c='_ZN4llvm14TestAsmPrinter4initEPKNS_6TargetENS_9StringRefEtNS_5dwarf11DwarfFormatE'/>
<use f='llvm/llvm/unittests/CodeGen/TestAsmPrinter.cpp' l='65' u='m' c='_ZN4llvm14TestAsmPrinter4initEPKNS_6TargetENS_9StringRefEtNS_5dwarf11DwarfFormatE'/>
<use f='llvm/llvm/unittests/CodeGen/TestAsmPrinter.cpp' l='86' u='m' c='_ZN4llvm14TestAsmPrinter37setDwarfUsesRelocationsAcrossSectionsEb'/>
