<dec f='llvm/clang/unittests/CodeGen/TestCompiler.h' l='31' type='llvm::Module *'/>
<use f='llvm/clang/unittests/CodeGen/TestCompiler.h' l='83' u='w' c='_ZN4llvm12TestCompiler7compileEv'/>
<use f='llvm/clang/unittests/CodeGen/TestCompiler.h' l='87' u='r' c='_ZN4llvm12TestCompiler7compileEv'/>
<use f='llvm/clang/unittests/CodeGen/TestCompiler.h' l='88' u='r' c='_ZN4llvm12TestCompiler7compileEv'/>
<use f='llvm/clang/unittests/CodeGen/TestCompiler.h' l='94' u='r' c='_ZN4llvm12TestCompiler7compileEv'/>
<offset>2816</offset>
