<dec f='llvm/build/lib/Target/PowerPC/PPCGenRegisterInfo.inc' l='85' type='65'/>
<use f='llvm/llvm/lib/Target/PowerPC/AsmParser/PPCAsmParser.cpp' l='32' macro='1'/>
<use f='llvm/llvm/lib/Target/PowerPC/AsmParser/PPCAsmParser.cpp' l='32' macro='1'/>
<use f='llvm/build/lib/Target/PowerPC/PPCGenAsmMatcher.inc' l='4166' c='_ZL20validateOperandClassRN4llvm18MCParsedAsmOperandEN12_GLOBAL__N_114MatchClassKindE'/>
<use f='llvm/llvm/lib/Target/PowerPC/Disassembler/PPCDisassembler.cpp' l='20' macro='1'/>
<use f='llvm/llvm/lib/Target/PowerPC/Disassembler/PPCDisassembler.cpp' l='20' macro='1'/>
<use f='llvm/llvm/lib/Target/PowerPC/PPCSubtarget.h' l='397' u='r' c='_ZNK4llvm12PPCSubtarget21getTOCPointerRegisterEv'/>
<use f='llvm/llvm/lib/Target/PowerPC/MCTargetDesc/PPCMCCodeEmitter.cpp' l='371' u='r' c='_ZNK4llvm16PPCMCCodeEmitter17getTLSRegEncodingERKNS_6MCInstEjRNS_15SmallVectorImplINS_7MCFixupEEERKNS_15MCSubtargetInfoE'/>
<use f='llvm/llvm/lib/Target/PowerPC/PPCAsmPrinter.cpp' l='1557' u='r' c='_ZN12_GLOBAL__N_118PPCLinuxAsmPrinter21emitFunctionBodyStartEv'/>
<use f='llvm/llvm/lib/Target/PowerPC/PPCFrameLowering.cpp' l='650' u='r' c='_ZNK4llvm16PPCFrameLowering12emitPrologueERNS_15MachineFunctionERNS_17MachineBasicBlockE'/>
<use f='llvm/llvm/lib/Target/PowerPC/PPCFrameLowering.cpp' l='1141' u='r' c='_ZNK4llvm16PPCFrameLowering12emitPrologueERNS_15MachineFunctionERNS_17MachineBasicBlockE'/>
<use f='llvm/llvm/lib/Target/PowerPC/PPCFrameLowering.cpp' l='2316' u='r' c='_ZNK4llvm16PPCFrameLowering25spillCalleeSavedRegistersERNS_17MachineBasicBlockENS_26MachineInstrBundleIteratorINS_12MachineInstrELb0EEENS_8ArrayRefINS10705252'/>
<use f='llvm/llvm/lib/Target/PowerPC/PPCFrameLowering.cpp' l='2460' u='r' c='_ZNK4llvm16PPCFrameLowering27restoreCalleeSavedRegistersERNS_17MachineBasicBlockENS_26MachineInstrBundleIteratorINS_12MachineInstrELb0EEENS_15MutableA12816417'/>
<use f='llvm/llvm/lib/Target/PowerPC/PPCISelLowering.cpp' l='2942' u='r' c='_ZNK4llvm17PPCTargetLowering11getTOCEntryERNS_12SelectionDAGERKNS_5SDLocENS_7SDValueE'/>
<use f='llvm/llvm/lib/Target/PowerPC/PPCISelLowering.cpp' l='3148' u='r' c='_ZNK4llvm17PPCTargetLowering21LowerGlobalTLSAddressENS_7SDValueERNS_12SelectionDAGE'/>
<use f='llvm/llvm/lib/Target/PowerPC/PPCISelLowering.cpp' l='9861' u='r' c='_ZNK4llvm17PPCTargetLowering23LowerINTRINSIC_WO_CHAINENS_7SDValueERNS_12SelectionDAGE'/>
<use f='llvm/llvm/lib/Target/PowerPC/PPCISelLowering.cpp' l='15326' u='r' c='_ZNK4llvm17PPCTargetLowering17getRegisterByNameEPKcNS_3LLTERKNS_15MachineFunctionE'/>
<use f='llvm/llvm/lib/Target/PowerPC/PPCInstrInfo.cpp' l='3003' u='r' c='_ZNK4llvm12PPCInstrInfo18expandPostRAPseudoERNS_12MachineInstrE'/>
<use f='llvm/llvm/lib/Target/PowerPC/PPCRegisterInfo.cpp' l='305' u='r' c='_ZNK4llvm15PPCRegisterInfo15getReservedRegsERKNS_15MachineFunctionE'/>
<use f='llvm/llvm/lib/Target/PowerPC/PPCRegisterInfo.cpp' l='312' u='r' c='_ZNK4llvm15PPCRegisterInfo15getReservedRegsERKNS_15MachineFunctionE'/>
<use f='llvm/llvm/lib/Target/PowerPC/PPCTOCRegDeps.cpp' l='115' u='r' c='_ZN12_GLOBAL__N_113PPCTOCRegDeps12processBlockERN4llvm17MachineBasicBlockE'/>
