<use f='llvm/llvm/include/llvm/ExecutionEngine/Orc/CompileUtils.h' l='71' u='w' c='_ZN4llvm3orc22TMOwningSimpleCompilerC1ESt10unique_ptrINS_13TargetMachineESt14default_deleteIS3_EEPNS_11ObjectCacheE'/>
<dec f='llvm/llvm/include/llvm/ExecutionEngine/Orc/CompileUtils.h' l='76' type='std::shared_ptr&lt;llvm::TargetMachine&gt;'/>
<offset>256</offset>
<doc f='llvm/llvm/include/llvm/ExecutionEngine/Orc/CompileUtils.h' l='74'>// FIXME: shared because std::functions (and consequently
  // IRCompileLayer::CompileFunction) are not moveable.</doc>
