<use f='llvm/llvm/include/llvm/ADT/APInt.h' l='1883' c='_ZNK4llvm5APInt5magicEv'/>
<def f='llvm/llvm/include/llvm/ADT/APInt.h' l='2023' ll='2026'/>
<size>24</size>
<doc f='llvm/llvm/include/llvm/ADT/APInt.h' l='2022'>/// Magic data for optimising signed division by a constant.</doc>
<mbr r='llvm::APInt::ms::m' o='0' t='llvm::APInt'/>
<mbr r='llvm::APInt::ms::s' o='128' t='unsigned int'/>
<use f='llvm/llvm/lib/CodeGen/SelectionDAG/TargetLowering.cpp' l='5104' c='_ZNK4llvm14TargetLowering9BuildSDIVEPNS_6SDNodeERNS_12SelectionDAGEbRNS_15SmallVectorImplIS2_EE'/>
<size>24</size>
<use f='llvm/llvm/lib/Support/APInt.cpp' l='1225' c='_ZNK4llvm5APInt5magicEv'/>
<use f='llvm/llvm/lib/Support/APInt.cpp' l='1230' c='_ZNK4llvm5APInt5magicEv'/>
<size>24</size>
