<dec f='llvm/llvm/include/llvm/DWARFLinker/DWARFStreamer.h' l='184' type='std::unique_ptr&lt;TargetMachine&gt;'/>
<use f='llvm/llvm/lib/DWARFLinker/DWARFStreamer.cpp' l='97' u='m' c='_ZN4llvm13DwarfStreamer4initENS_6TripleE'/>
<use f='llvm/llvm/lib/DWARFLinker/DWARFStreamer.cpp' l='99' u='m' c='_ZN4llvm13DwarfStreamer4initENS_6TripleE'/>
<use f='llvm/llvm/lib/DWARFLinker/DWARFStreamer.cpp' l='102' u='m' c='_ZN4llvm13DwarfStreamer4initENS_6TripleE'/>
<offset>704</offset>
