<use f='llvm/llvm/include/llvm/Transforms/Utils/FunctionComparator.h' l='97' u='w' c='_ZN4llvm18FunctionComparatorC1EPKNS_8FunctionES3_PNS_17GlobalNumberStateE'/>
<dec f='llvm/llvm/include/llvm/Transforms/Utils/FunctionComparator.h' l='328' type='const llvm::Function *'/>
<offset>0</offset>
<use f='llvm/llvm/lib/Transforms/Utils/FunctionComparator.cpp' l='417' u='r' c='_ZNK4llvm18FunctionComparator8cmpTypesEPNS_4TypeES2_'/>
<use f='llvm/llvm/lib/Transforms/Utils/FunctionComparator.cpp' l='702' u='r' c='_ZNK4llvm18FunctionComparator7cmpGEPsEPKNS_11GEPOperatorES3_'/>
<use f='llvm/llvm/lib/Transforms/Utils/FunctionComparator.cpp' l='751' u='r' c='_ZNK4llvm18FunctionComparator9cmpValuesEPKNS_5ValueES3_'/>
<use f='llvm/llvm/lib/Transforms/Utils/FunctionComparator.cpp' l='757' u='r' c='_ZNK4llvm18FunctionComparator9cmpValuesEPKNS_5ValueES3_'/>
<use f='llvm/llvm/lib/Transforms/Utils/FunctionComparator.cpp' l='826' u='r' c='_ZNK4llvm18FunctionComparator16compareSignatureEv'/>
<use f='llvm/llvm/lib/Transforms/Utils/FunctionComparator.cpp' l='829' u='r' c='_ZNK4llvm18FunctionComparator16compareSignatureEv'/>
<use f='llvm/llvm/lib/Transforms/Utils/FunctionComparator.cpp' l='832' u='r' c='_ZNK4llvm18FunctionComparator16compareSignatureEv'/>
<use f='llvm/llvm/lib/Transforms/Utils/FunctionComparator.cpp' l='833' u='r' c='_ZNK4llvm18FunctionComparator16compareSignatureEv'/>
<use f='llvm/llvm/lib/Transforms/Utils/FunctionComparator.cpp' l='837' u='r' c='_ZNK4llvm18FunctionComparator16compareSignatureEv'/>
<use f='llvm/llvm/lib/Transforms/Utils/FunctionComparator.cpp' l='840' u='r' c='_ZNK4llvm18FunctionComparator16compareSignatureEv'/>
<use f='llvm/llvm/lib/Transforms/Utils/FunctionComparator.cpp' l='841' u='r' c='_ZNK4llvm18FunctionComparator16compareSignatureEv'/>
<use f='llvm/llvm/lib/Transforms/Utils/FunctionComparator.cpp' l='845' u='r' c='_ZNK4llvm18FunctionComparator16compareSignatureEv'/>
<use f='llvm/llvm/lib/Transforms/Utils/FunctionComparator.cpp' l='850' u='r' c='_ZNK4llvm18FunctionComparator16compareSignatureEv'/>
<use f='llvm/llvm/lib/Transforms/Utils/FunctionComparator.cpp' l='853' u='r' c='_ZNK4llvm18FunctionComparator16compareSignatureEv'/>
<use f='llvm/llvm/lib/Transforms/Utils/FunctionComparator.cpp' l='861' u='r' c='_ZNK4llvm18FunctionComparator16compareSignatureEv'/>
<use f='llvm/llvm/lib/Transforms/Utils/FunctionComparator.cpp' l='863' u='r' c='_ZNK4llvm18FunctionComparator16compareSignatureEv'/>
<use f='llvm/llvm/lib/Transforms/Utils/FunctionComparator.cpp' l='885' u='r' c='_ZN4llvm18FunctionComparator7compareEv'/>
<use f='llvm/llvm/unittests/Transforms/Utils/FunctionComparatorTest.cpp' l='54' u='r' c='_ZN14TestComparator18testFunctionAccessEPKN4llvm8FunctionES3_'/>
