<use f='llvm/llvm/include/llvm/ExecutionEngine/Orc/CompileUtils.h' l='43' u='w' c='_ZN4llvm3orc14SimpleCompilerC1ERNS_13TargetMachineEPNS_11ObjectCacheE'/>
<dec f='llvm/llvm/include/llvm/ExecutionEngine/Orc/CompileUtils.h' l='59' type='llvm::TargetMachine &amp;'/>
<offset>128</offset>
<use f='llvm/llvm/lib/ExecutionEngine/Orc/CompileUtils.cpp' l='49' u='m' c='_ZN4llvm3orc14SimpleCompilerclERNS_6ModuleE'/>
