<dec f='llvm/llvm/lib/CodeGen/AsmPrinter/DwarfFile.h' l='44' type='const llvm::DwarfCompileUnit *'/>
<offset>64</offset>
<use f='llvm/llvm/lib/CodeGen/AsmPrinter/DwarfDebug.cpp' l='2937' u='r' c='_ZL13emitRangeListRN4llvm10DwarfDebugEPNS_10AsmPrinterERKNS_13RangeSpanListE'/>
<use f='llvm/llvm/lib/CodeGen/AsmPrinter/DwarfDebug.cpp' l='2941' u='r' c='_ZL13emitRangeListRN4llvm10DwarfDebugEPNS_10AsmPrinterERKNS_13RangeSpanListE'/>
