<dec f='llvm/llvm/lib/Transforms/AggressiveInstCombine/AggressiveInstCombineInternal.h' l='53' type='const llvm::DataLayout &amp;'/>
<use f='llvm/llvm/lib/Transforms/AggressiveInstCombine/AggressiveInstCombineInternal.h' l='80' u='w' c='_ZN4llvm16TruncInstCombineC1ERNS_17TargetLibraryInfoERKNS_10DataLayoutERKNS_13DominatorTreeE'/>
<offset>64</offset>
<use f='llvm/llvm/lib/Transforms/AggressiveInstCombine/TruncInstCombine.cpp' l='223' u='m' c='_ZN4llvm16TruncInstCombine14getMinBitWidthEv'/>
<use f='llvm/llvm/lib/Transforms/AggressiveInstCombine/TruncInstCombine.cpp' l='232' u='m' c='_ZN4llvm16TruncInstCombine14getMinBitWidthEv'/>
<use f='llvm/llvm/lib/Transforms/AggressiveInstCombine/TruncInstCombine.cpp' l='233' u='m' c='_ZN4llvm16TruncInstCombine14getMinBitWidthEv'/>
<use f='llvm/llvm/lib/Transforms/AggressiveInstCombine/TruncInstCombine.cpp' l='301' u='r' c='_ZN4llvm16TruncInstCombine17getReducedOperandEPNS_5ValueEPNS_4TypeE'/>
