<dec f='llvm/build/lib/Target/PowerPC/PPCGenInstrInfo.inc' l='1579' type='1564'/>
<use f='llvm/build/lib/Target/PowerPC/PPCGenAsmMatcher.inc' l='6880'/>
<use f='llvm/build/lib/Target/PowerPC/PPCGenMCCodeEmitter.inc' l='2852' c='_ZNK4llvm16PPCMCCodeEmitter21getBinaryCodeForInstrERKNS_6MCInstERNS_15SmallVectorImplINS_7MCFixupEEERKNS_15MCSubtargetInfoE'/>
<use f='llvm/build/lib/Target/PowerPC/PPCGenFastISel.inc' l='3730' u='r' c='_ZN12_GLOBAL__N_111PPCFastISel27fastEmit_ISD_SRL_MVT_i32_rrEN4llvm3MVTEjbjb'/>
<use f='llvm/build/lib/Target/PowerPC/PPCGenFastISel.inc' l='4654' u='r' c='_ZN12_GLOBAL__N_111PPCFastISel30fastEmit_PPCISD_SRL_MVT_i32_rrEN4llvm3MVTEjbjb'/>
<use f='llvm/build/lib/Target/PowerPC/PPCGenDAGISel.inc' l='43722' u='r' c='_ZN12_GLOBAL__N_115PPCDAGToDAGISel10SelectCodeEPN4llvm6SDNodeE'/>
<use f='llvm/build/lib/Target/PowerPC/PPCGenDAGISel.inc' l='43722' u='r' c='_ZN12_GLOBAL__N_115PPCDAGToDAGISel10SelectCodeEPN4llvm6SDNodeE'/>
<use f='llvm/build/lib/Target/PowerPC/PPCGenDAGISel.inc' l='44550' u='r' c='_ZN12_GLOBAL__N_115PPCDAGToDAGISel10SelectCodeEPN4llvm6SDNodeE'/>
<use f='llvm/build/lib/Target/PowerPC/PPCGenDAGISel.inc' l='44550' u='r' c='_ZN12_GLOBAL__N_115PPCDAGToDAGISel10SelectCodeEPN4llvm6SDNodeE'/>
<use f='llvm/llvm/lib/Target/PowerPC/PPCISelDAGToDAG.cpp' l='6393' u='r' c='_ZL23PeepholePPC64ZExtGatherN4llvm7SDValueERNS_15SmallPtrSetImplIPNS_6SDNodeEEE'/>
<use f='llvm/llvm/lib/Target/PowerPC/PPCISelDAGToDAG.cpp' l='6606' c='_ZN12_GLOBAL__N_115PPCDAGToDAGISel17PeepholePPC64ZExtEv'/>
<use f='llvm/llvm/lib/Target/PowerPC/PPCISelLowering.cpp' l='10846' u='r' c='_ZNK4llvm17PPCTargetLowering24EmitPartwordAtomicBinaryERNS_12MachineInstrEPNS_17MachineBasicBlockEbjjj'/>
<use f='llvm/llvm/lib/Target/PowerPC/PPCISelLowering.cpp' l='10881' u='r' c='_ZNK4llvm17PPCTargetLowering24EmitPartwordAtomicBinaryERNS_12MachineInstrEPNS_17MachineBasicBlockEbjjj'/>
<use f='llvm/llvm/lib/Target/PowerPC/PPCISelLowering.cpp' l='11887' u='r' c='_ZNK4llvm17PPCTargetLowering27EmitInstrWithCustomInserterERNS_12MachineInstrEPNS_17MachineBasicBlockE'/>
<use f='llvm/llvm/lib/Target/PowerPC/PPCInstrInfo.cpp' l='3917' c='_ZNK4llvm12PPCInstrInfo15instrHasImmFormEjbRNS_12ImmInstrInfoEb'/>
<use f='llvm/llvm/lib/Target/PowerPC/PPCInstrInfo.cpp' l='3955' c='_ZNK4llvm12PPCInstrInfo15instrHasImmFormEjbRNS_12ImmInstrInfoEb'/>
<use f='llvm/llvm/lib/Target/PowerPC/PPCInstrInfo.cpp' l='4947' u='r' c='_ZNK4llvm12PPCInstrInfo25transformToImmFormFedByLIERNS_12MachineInstrERKNS_12ImmInstrInfoEjS2_'/>
<use f='llvm/llvm/lib/Target/PowerPC/PPCInstrInfo.cpp' l='4954' u='r' c='_ZNK4llvm12PPCInstrInfo25transformToImmFormFedByLIERNS_12MachineInstrERKNS_12ImmInstrInfoEjS2_'/>
<use f='llvm/llvm/lib/Target/PowerPC/PPCInstrInfo.cpp' l='5129' u='r' c='_ZL17isZeroExtendingOpRKN4llvm12MachineInstrE'/>
