<dec f='llvm/llvm/include/llvm/Transforms/Scalar/LoopPassManager.h' l='495' type='llvm::raw_ostream &amp;'/>
<offset>0</offset>
<use f='llvm/llvm/lib/Transforms/Scalar/LoopPassManager.cpp' l='326' u='w' c='_ZN4llvm13PrintLoopPassC1Ev'/>
<use f='llvm/llvm/lib/Transforms/Scalar/LoopPassManager.cpp' l='328' u='w' c='_ZN4llvm13PrintLoopPassC1ERNS_11raw_ostreamERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE'/>
<use f='llvm/llvm/lib/Transforms/Scalar/LoopPassManager.cpp' l='333' u='a' c='_ZN4llvm13PrintLoopPass3runERNS_4LoopERNS_15AnalysisManagerIS1_JRNS_27LoopStandardAnalysisResultsEEEES5_RNS_10LPMUpdaterE'/>
