<dec f='llvm/llvm/lib/Target/AVR/AVRISelLowering.h' l='38' type='338'/>
<doc f='llvm/llvm/lib/Target/AVR/AVRISelLowering.h' l='38'>///&lt; Logical shift left.</doc>
<use f='llvm/build/lib/Target/AVR/AVRGenDAGISel.inc' l='1316' u='r' c='_ZN4llvm15AVRDAGToDAGISel10SelectCodeEPNS_6SDNodeE'/>
<use f='llvm/build/lib/Target/AVR/AVRGenDAGISel.inc' l='1316' u='r' c='_ZN4llvm15AVRDAGToDAGISel10SelectCodeEPNS_6SDNodeE'/>
<use f='llvm/llvm/lib/Target/AVR/AVRISelLowering.cpp' l='246' c='_ZNK4llvm17AVRTargetLowering17getTargetNodeNameEj'/>
<use f='llvm/llvm/lib/Target/AVR/AVRISelLowering.cpp' l='331' u='r' c='_ZNK4llvm17AVRTargetLowering11LowerShiftsENS_7SDValueERNS_12SelectionDAGE'/>
