<dec f='llvm/llvm/include/llvm/IR/PatternMatch.h' l='1201' type='LHS_t'/>
<use f='llvm/llvm/include/llvm/IR/PatternMatch.h' l='1204' u='w' c='_ZN4llvm12PatternMatch15BinOpPred_matchC1ERKT_RKT0_'/>
<use f='llvm/llvm/include/llvm/IR/PatternMatch.h' l='1208' u='c' c='_ZN4llvm12PatternMatch15BinOpPred_match5matchEPTL0__'/>
<use f='llvm/llvm/include/llvm/IR/PatternMatch.h' l='1211' u='c' c='_ZN4llvm12PatternMatch15BinOpPred_match5matchEPTL0__'/>
