<dec f='llvm/llvm/lib/AsmParser/LLParser.h' l='492' type='llvm::Value *'/>
<use f='llvm/llvm/lib/AsmParser/LLParser.h' l='495' u='w' c='_ZN4llvm8LLParser9ParamInfoC1ENS_5SMLocEPNS_5ValueENS_12AttributeSetE'/>
<use f='llvm/llvm/lib/AsmParser/LLParser.cpp' l='6458' u='r' c='_ZN4llvm8LLParser11parseInvokeERPNS_11InstructionERNS0_16PerFunctionStateE'/>
<use f='llvm/llvm/lib/AsmParser/LLParser.cpp' l='6490' u='r' c='_ZN4llvm8LLParser11parseInvokeERPNS_11InstructionERNS0_16PerFunctionStateE'/>
<use f='llvm/llvm/lib/AsmParser/LLParser.cpp' l='6493' u='r' c='_ZN4llvm8LLParser11parseInvokeERPNS_11InstructionERNS0_16PerFunctionStateE'/>
<use f='llvm/llvm/lib/AsmParser/LLParser.cpp' l='6784' u='r' c='_ZN4llvm8LLParser11parseCallBrERPNS_11InstructionERNS0_16PerFunctionStateE'/>
<use f='llvm/llvm/lib/AsmParser/LLParser.cpp' l='6816' u='r' c='_ZN4llvm8LLParser11parseCallBrERPNS_11InstructionERNS0_16PerFunctionStateE'/>
<use f='llvm/llvm/lib/AsmParser/LLParser.cpp' l='6819' u='r' c='_ZN4llvm8LLParser11parseCallBrERPNS_11InstructionERNS0_16PerFunctionStateE'/>
<use f='llvm/llvm/lib/AsmParser/LLParser.cpp' l='7190' u='r' c='_ZN4llvm8LLParser9parseCallERPNS_11InstructionERNS0_16PerFunctionStateENS_8CallInst12TailCallKindE'/>
<use f='llvm/llvm/lib/AsmParser/LLParser.cpp' l='7223' u='r' c='_ZN4llvm8LLParser9parseCallERPNS_11InstructionERNS0_16PerFunctionStateENS_8CallInst12TailCallKindE'/>
<use f='llvm/llvm/lib/AsmParser/LLParser.cpp' l='7226' u='r' c='_ZN4llvm8LLParser9parseCallERPNS_11InstructionERNS0_16PerFunctionStateENS_8CallInst12TailCallKindE'/>
<offset>64</offset>
