<dec f='llvm/build/lib/Target/AVR/AVRGenRegisterInfo.inc' l='28' type='8'/>
<use f='llvm/llvm/lib/Target/AVR/AVRISelLowering.cpp' l='2035' u='r' c='_ZNK4llvm17AVRTargetLowering17getRegisterByNameEPKcNS_3LLTERKNS_15MachineFunctionE'/>
<use f='llvm/build/lib/Target/AVR/AVRGenAsmMatcher.inc' l='1012' c='_ZL20validateOperandClassRN4llvm18MCParsedAsmOperandEN12_GLOBAL__N_114MatchClassKindE'/>
<use f='llvm/llvm/lib/Target/AVR/Disassembler/AVRDisassembler.cpp' l='61'/>
