<dec f='llvm/llvm/include/llvm/IR/Module.h' l='199' type='llvm::DataLayout'/>
<use f='llvm/llvm/include/llvm/IR/Module.h' l='241' u='m' c='_ZNK4llvm6Module16getDataLayoutStrB5cxx11Ev'/>
<offset>2432</offset>
<doc f='llvm/llvm/include/llvm/IR/Module.h' l='199'>///&lt; DataLayout associated with the module</doc>
<use f='llvm/llvm/lib/IR/Module.cpp' l='77' u='w' c='_ZN4llvm6ModuleC1ENS_9StringRefERNS_11LLVMContextE'/>
<use f='llvm/llvm/lib/IR/Module.cpp' l='150' u='m' c='_ZN4llvm6Module19getOrInsertFunctionENS_9StringRefEPNS_12FunctionTypeENS_13AttributeListE'/>
<use f='llvm/llvm/lib/IR/Module.cpp' l='392' u='m' c='_ZN4llvm6Module13setDataLayoutENS_9StringRefE'/>
<use f='llvm/llvm/lib/IR/Module.cpp' l='395' u='w' c='_ZN4llvm6Module13setDataLayoutERKNS_10DataLayoutE'/>
<use f='llvm/llvm/lib/IR/Module.cpp' l='397' u='a' c='_ZNK4llvm6Module13getDataLayoutEv'/>
