<dec f='llvm/build/lib/Target/PowerPC/PPCGenInstrInfo.inc' l='459' type='444'/>
<use f='llvm/build/lib/Target/PowerPC/PPCGenAsmMatcher.inc' l='5024'/>
<use f='llvm/build/lib/Target/PowerPC/PPCGenGlobalISel.inc' l='11702' u='r' c='_ZNK12_GLOBAL__N_122PPCInstructionSelector13getMatchTableEv'/>
<use f='llvm/build/lib/Target/PowerPC/PPCGenMCCodeEmitter.inc' l='4293' c='_ZNK4llvm16PPCMCCodeEmitter21getBinaryCodeForInstrERKNS_6MCInstERNS_15SmallVectorImplINS_7MCFixupEEERKNS_15MCSubtargetInfoE'/>
<use f='llvm/llvm/lib/Target/PowerPC/PPCAsmPrinter.cpp' l='1267' u='r' c='_ZN12_GLOBAL__N_118PPCLinuxAsmPrinter15emitInstructionEPKN4llvm12MachineInstrE'/>
<use f='llvm/llvm/lib/Target/PowerPC/PPCBranchSelector.cpp' l='394' u='r' c='_ZN12_GLOBAL__N_17PPCBSel20runOnMachineFunctionERN4llvm15MachineFunctionE'/>
<use f='llvm/llvm/lib/Target/PowerPC/PPCEarlyReturn.cpp' l='76' u='r' c='_ZN12_GLOBAL__N_114PPCEarlyReturn12processBlockERN4llvm17MachineBasicBlockE'/>
<use f='llvm/llvm/lib/Target/PowerPC/PPCExpandISEL.cpp' l='417' u='r' c='_ZN12_GLOBAL__N_113PPCExpandISEL21reorganizeBlockLayoutERN4llvm11SmallVectorIPNS1_12MachineInstrELj4EEEPNS1_17MachineBasicBlockE'/>
<use f='llvm/build/lib/Target/PowerPC/PPCGenDAGISel.inc' l='44429' u='r' c='_ZN12_GLOBAL__N_115PPCDAGToDAGISel10SelectCodeEPN4llvm6SDNodeE'/>
<use f='llvm/build/lib/Target/PowerPC/PPCGenDAGISel.inc' l='44429' u='r' c='_ZN12_GLOBAL__N_115PPCDAGToDAGISel10SelectCodeEPN4llvm6SDNodeE'/>
<use f='llvm/llvm/lib/Target/PowerPC/PPCISelLowering.cpp' l='10991' u='r' c='_ZNK4llvm17PPCTargetLowering16emitEHSjLjSetJmpERNS_12MachineInstrEPNS_17MachineBasicBlockE'/>
<use f='llvm/llvm/lib/Target/PowerPC/PPCISelLowering.cpp' l='11295' u='r' c='_ZNK4llvm17PPCTargetLowering16emitProbedAllocaERNS_12MachineInstrEPNS_17MachineBasicBlockE'/>
<use f='llvm/llvm/lib/Target/PowerPC/PPCISelLowering.cpp' l='11690' u='r' c='_ZNK4llvm17PPCTargetLowering27EmitInstrWithCustomInserterERNS_12MachineInstrEPNS_17MachineBasicBlockE'/>
<use f='llvm/llvm/lib/Target/PowerPC/PPCISelLowering.cpp' l='11873' u='r' c='_ZNK4llvm17PPCTargetLowering27EmitInstrWithCustomInserterERNS_12MachineInstrEPNS_17MachineBasicBlockE'/>
<use f='llvm/llvm/lib/Target/PowerPC/PPCInstrInfo.cpp' l='1284' u='r' c='_ZNK4llvm12PPCInstrInfo13analyzeBranchERNS_17MachineBasicBlockERPS1_S4_RNS_15SmallVectorImplINS_14MachineOperandEEEb'/>
<use f='llvm/llvm/lib/Target/PowerPC/PPCInstrInfo.cpp' l='1300' u='r' c='_ZNK4llvm12PPCInstrInfo13analyzeBranchERNS_17MachineBasicBlockERPS1_S4_RNS_15SmallVectorImplINS_14MachineOperandEEEb'/>
<use f='llvm/llvm/lib/Target/PowerPC/PPCInstrInfo.cpp' l='1366' u='r' c='_ZNK4llvm12PPCInstrInfo13analyzeBranchERNS_17MachineBasicBlockERPS1_S4_RNS_15SmallVectorImplINS_14MachineOperandEEEb'/>
<use f='llvm/llvm/lib/Target/PowerPC/PPCInstrInfo.cpp' l='1376' u='r' c='_ZNK4llvm12PPCInstrInfo13analyzeBranchERNS_17MachineBasicBlockERPS1_S4_RNS_15SmallVectorImplINS_14MachineOperandEEEb'/>
<use f='llvm/llvm/lib/Target/PowerPC/PPCInstrInfo.cpp' l='1386' u='r' c='_ZNK4llvm12PPCInstrInfo13analyzeBranchERNS_17MachineBasicBlockERPS1_S4_RNS_15SmallVectorImplINS_14MachineOperandEEEb'/>
<use f='llvm/llvm/lib/Target/PowerPC/PPCInstrInfo.cpp' l='1397' u='r' c='_ZNK4llvm12PPCInstrInfo13analyzeBranchERNS_17MachineBasicBlockERPS1_S4_RNS_15SmallVectorImplINS_14MachineOperandEEEb'/>
<use f='llvm/llvm/lib/Target/PowerPC/PPCInstrInfo.cpp' l='1411' u='r' c='_ZNK4llvm12PPCInstrInfo13analyzeBranchERNS_17MachineBasicBlockERPS1_S4_RNS_15SmallVectorImplINS_14MachineOperandEEEb'/>
<use f='llvm/llvm/lib/Target/PowerPC/PPCInstrInfo.cpp' l='1427' u='r' c='_ZNK4llvm12PPCInstrInfo13analyzeBranchERNS_17MachineBasicBlockERPS1_S4_RNS_15SmallVectorImplINS_14MachineOperandEEEb'/>
<use f='llvm/llvm/lib/Target/PowerPC/PPCInstrInfo.cpp' l='1427' u='r' c='_ZNK4llvm12PPCInstrInfo13analyzeBranchERNS_17MachineBasicBlockERPS1_S4_RNS_15SmallVectorImplINS_14MachineOperandEEEb'/>
<use f='llvm/llvm/lib/Target/PowerPC/PPCInstrInfo.cpp' l='1449' u='r' c='_ZNK4llvm12PPCInstrInfo12removeBranchERNS_17MachineBasicBlockEPi'/>
<use f='llvm/llvm/lib/Target/PowerPC/PPCInstrInfo.cpp' l='1490' u='r' c='_ZNK4llvm12PPCInstrInfo12insertBranchERNS_17MachineBasicBlockEPS1_S3_NS_8ArrayRefINS_14MachineOperandEEERKNS_8DebugLocEPi'/>
<use f='llvm/llvm/lib/Target/PowerPC/PPCInstrInfo.cpp' l='1521' u='r' c='_ZNK4llvm12PPCInstrInfo12insertBranchERNS_17MachineBasicBlockEPS1_S3_NS_8ArrayRefINS_14MachineOperandEEERKNS_8DebugLocEPi'/>
<use f='llvm/llvm/lib/Target/PowerPC/PPCInstrInfo.cpp' l='2181' u='r' c='_ZNK4llvm12PPCInstrInfo20PredicateInstructionERNS_12MachineInstrENS_8ArrayRefINS_14MachineOperandEEE'/>
<use f='llvm/llvm/lib/Target/PowerPC/PPCReduceCRLogicals.cpp' l='225' u='r' c='_ZL8splitMBBR14BlockSplitInfo'/>
