<use f='llvm/llvm/include/llvm/Frontend/OpenMP/OMPIRBuilder.h' l='33' u='w' c='_ZN4llvm15OpenMPIRBuilderC1ERNS_6ModuleE'/>
<dec f='llvm/llvm/include/llvm/Frontend/OpenMP/OMPIRBuilder.h' l='460' type='llvm::Module &amp;'/>
<offset>2688</offset>
<doc f='llvm/llvm/include/llvm/Frontend/OpenMP/OMPIRBuilder.h' l='459'>/// The underlying LLVM-IR module</doc>
<use f='llvm/llvm/lib/Frontend/OpenMP/OMPIRBuilder.cpp' l='121' u='a' c='_ZN4llvm15OpenMPIRBuilder29getOrCreateRuntimeFunctionPtrENS_3omp15RuntimeFunctionE'/>
<use f='llvm/llvm/lib/Frontend/OpenMP/OMPIRBuilder.cpp' l='127' u='a' c='_ZN4llvm15OpenMPIRBuilder10initializeEv'/>
<use f='llvm/llvm/lib/Frontend/OpenMP/OMPIRBuilder.cpp' l='164' u='m' c='_ZN4llvm15OpenMPIRBuilder8finalizeEb'/>
<use f='llvm/llvm/lib/Frontend/OpenMP/OMPIRBuilder.cpp' l='224' u='m' c='_ZN4llvm15OpenMPIRBuilder16getOrCreateIdentEPNS_8ConstantENS_3omp9IdentFlagEj'/>
<use f='llvm/llvm/lib/Frontend/OpenMP/OMPIRBuilder.cpp' l='229' u='a' c='_ZN4llvm15OpenMPIRBuilder16getOrCreateIdentEPNS_8ConstantENS_3omp9IdentFlagEj'/>
<use f='llvm/llvm/lib/Frontend/OpenMP/OMPIRBuilder.cpp' l='240' u='m' c='_ZN4llvm15OpenMPIRBuilder15getLanemaskTypeEv'/>
<use f='llvm/llvm/lib/Frontend/OpenMP/OMPIRBuilder.cpp' l='241' u='m' c='_ZN4llvm15OpenMPIRBuilder15getLanemaskTypeEv'/>
<use f='llvm/llvm/lib/Frontend/OpenMP/OMPIRBuilder.cpp' l='251' u='m' c='_ZN4llvm15OpenMPIRBuilder20getOrCreateSrcLocStrENS_9StringRefE'/>
<use f='llvm/llvm/lib/Frontend/OpenMP/OMPIRBuilder.cpp' l='255' u='m' c='_ZN4llvm15OpenMPIRBuilder20getOrCreateSrcLocStrENS_9StringRefE'/>
<use f='llvm/llvm/lib/Frontend/OpenMP/OMPIRBuilder.cpp' l='261' u='a' c='_ZN4llvm15OpenMPIRBuilder20getOrCreateSrcLocStrENS_9StringRefE'/>
<use f='llvm/llvm/lib/Frontend/OpenMP/OMPIRBuilder.cpp' l='293' u='m' c='_ZN4llvm15OpenMPIRBuilder20getOrCreateSrcLocStrERKNS0_19LocationDescriptionE'/>
<use f='llvm/llvm/lib/Frontend/OpenMP/OMPIRBuilder.cpp' l='1093' u='a' c='_ZN4llvm15OpenMPIRBuilder25createStaticWorkshareLoopERKNS0_19LocationDescriptionEPNS_17CanonicalLoopInfoENS_13IRBuilderBase11InsertPointEbPNS_5ValueE'/>
<use f='llvm/llvm/lib/Frontend/OpenMP/OMPIRBuilder.cpp' l='1095' u='a' c='_ZN4llvm15OpenMPIRBuilder25createStaticWorkshareLoopERKNS0_19LocationDescriptionEPNS_17CanonicalLoopInfoENS_13IRBuilderBase11InsertPointEbPNS_5ValueE'/>
<use f='llvm/llvm/lib/Frontend/OpenMP/OMPIRBuilder.cpp' l='1099' u='m' c='_ZN4llvm15OpenMPIRBuilder25createStaticWorkshareLoopERKNS0_19LocationDescriptionEPNS_17CanonicalLoopInfoENS_13IRBuilderBase11InsertPointEbPNS_5ValueE'/>
<use f='llvm/llvm/lib/Frontend/OpenMP/OMPIRBuilder.cpp' l='1580' u='m' c='_ZN4llvm15OpenMPIRBuilder24emitCommonDirectiveEntryENS_3omp9DirectiveEPNS_5ValueEPNS_10BasicBlockEb'/>
<use f='llvm/llvm/lib/Frontend/OpenMP/OMPIRBuilder.cpp' l='1656' u='m' c='_ZN4llvm15OpenMPIRBuilder24createCopyinClauseBlocksENS_13IRBuilderBase11InsertPointEPNS_5ValueES4_PNS_11IntegerTypeEb'/>
<use f='llvm/llvm/lib/Frontend/OpenMP/OMPIRBuilder.cpp' l='1667' u='m' c='_ZN4llvm15OpenMPIRBuilder24createCopyinClauseBlocksENS_13IRBuilderBase11InsertPointEPNS_5ValueES4_PNS_11IntegerTypeEb'/>
<use f='llvm/llvm/lib/Frontend/OpenMP/OMPIRBuilder.cpp' l='1766' u='a' c='_ZN4llvm15OpenMPIRBuilder30getOrCreateOMPInternalVariableEPNS_4TypeERKNS_5TwineEj'/>
