<dec f='llvm/llvm/include/llvm/CodeGen/ModuloSchedule.h' l='170' type='const llvm::TargetSubtargetInfo &amp;'/>
<use f='llvm/llvm/include/llvm/CodeGen/ModuloSchedule.h' l='263' u='w' c='_ZN4llvm22ModuloScheduleExpanderC1ERNS_15MachineFunctionERNS_14ModuloScheduleERNS_13LiveIntervalsENS_8DenseMapIPNS_12MachineInstrESt4pairIjlENS_12Dens8837939'/>
<use f='llvm/llvm/include/llvm/CodeGen/ModuloSchedule.h' l='264' u='m' c='_ZN4llvm22ModuloScheduleExpanderC1ERNS_15MachineFunctionERNS_14ModuloScheduleERNS_13LiveIntervalsENS_8DenseMapIPNS_12MachineInstrESt4pairIjlENS_12Dens8837939'/>
<offset>128</offset>
