<dec f='llvm/llvm/include/llvm/TableGen/Record.h' l='836' type='llvm::Init *'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='840' u='w' c='_ZN4llvm10TernOpInitC1ENS0_9TernaryOpEPNS_4InitES3_S3_PNS_5RecTyE'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='875' u='r' c='_ZNK4llvm10TernOpInit6getLHSEv'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='884' u='r' c='_ZNK4llvm10TernOpInit10isCompleteEv'/>
<offset>256</offset>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='1254' u='r' c='_ZNK4llvm10TernOpInit4FoldEPNS_6RecordE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='1255' u='r' c='_ZNK4llvm10TernOpInit4FoldEPNS_6RecordE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='1256' u='r' c='_ZNK4llvm10TernOpInit4FoldEPNS_6RecordE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='1298' u='r' c='_ZNK4llvm10TernOpInit4FoldEPNS_6RecordE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='1304' u='r' c='_ZNK4llvm10TernOpInit4FoldEPNS_6RecordE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='1311' u='r' c='_ZNK4llvm10TernOpInit4FoldEPNS_6RecordE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='1338' u='r' c='_ZNK4llvm10TernOpInit4FoldEPNS_6RecordE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='1344' u='r' c='_ZNK4llvm10TernOpInit4FoldEPNS_6RecordE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='1369' u='r' c='_ZNK4llvm10TernOpInit17resolveReferencesERNS_8ResolverE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='1371' u='r' c='_ZNK4llvm10TernOpInit17resolveReferencesERNS_8ResolverE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='1392' u='r' c='_ZNK4llvm10TernOpInit17resolveReferencesERNS_8ResolverE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='1410' u='r' c='_ZNK4llvm10TernOpInit11getAsStringB5cxx11Ev'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='1410' u='r' c='_ZNK4llvm10TernOpInit11getAsStringB5cxx11Ev'/>
