<dec f='llvm/llvm/include/llvm/CodeGen/MachineBasicBlock.h' l='1031' type='MachineBasicBlock::iterator'/>
<use f='llvm/llvm/include/llvm/CodeGen/MachineBasicBlock.h' l='1035' u='w' c='_ZN4llvm16MachineInstrSpanC1ENS_26MachineInstrBundleIteratorINS_12MachineInstrELb0EEEPNS_17MachineBasicBlockE'/>
<use f='llvm/llvm/include/llvm/CodeGen/MachineBasicBlock.h' l='1041' u='r' c='_ZN4llvm16MachineInstrSpan5beginEv'/>
<use f='llvm/llvm/include/llvm/CodeGen/MachineBasicBlock.h' l='1041' u='r' c='_ZN4llvm16MachineInstrSpan5beginEv'/>
<offset>128</offset>
