<dec f='llvm/llvm/include/llvm/Analysis/InlineCost.h' l='281' type='llvm::raw_ostream &amp;'/>
<use f='llvm/llvm/include/llvm/Analysis/InlineCost.h' l='284' u='w' c='_ZN4llvm31InlineCostAnnotationPrinterPassC1ERNS_11raw_ostreamE'/>
<offset>0</offset>
<use f='llvm/llvm/lib/Analysis/InlineCost.cpp' l='2788' u='m' c='_ZN4llvm31InlineCostAnnotationPrinterPass3runERNS_8FunctionERNS_15AnalysisManagerIS1_JEEE'/>
