<dec f='llvm/build/lib/Target/Mips/MipsGenInstrInfo.inc' l='611' type='596'/>
<use f='llvm/llvm/lib/Target/Mips/AsmParser/MipsAsmParser.cpp' l='2518' c='_ZN12_GLOBAL__N_113MipsAsmParser20tryExpandInstructionERN4llvm6MCInstENS1_5SMLocERNS1_10MCStreamerEPKNS1_15MCSubtargetInfoE'/>
<use f='llvm/llvm/lib/Target/Mips/AsmParser/MipsAsmParser.cpp' l='4547' c='_ZN12_GLOBAL__N_113MipsAsmParser9expandSgeERN4llvm6MCInstENS1_5SMLocERNS1_10MCStreamerEPKNS1_15MCSubtargetInfoE'/>
<use f='llvm/build/lib/Target/Mips/MipsGenAsmMatcher.inc' l='7611'/>
<use f='llvm/build/lib/Target/Mips/MipsGenAsmMatcher.inc' l='7614'/>
