<dec f='llvm/llvm/lib/Target/ARM/Utils/ARMBaseInfo.h' l='37' type='6'/>
<use f='llvm/llvm/lib/Target/ARM/Utils/ARMBaseInfo.h' l='57' c='_ZN4llvm5ARMCCL20getOppositeConditionENS0_9CondCodesE'/>
<use f='llvm/llvm/lib/Target/ARM/Utils/ARMBaseInfo.h' l='58' u='r' c='_ZN4llvm5ARMCCL20getOppositeConditionENS0_9CondCodesE'/>
<use f='llvm/llvm/lib/Target/ARM/Utils/ARMBaseInfo.h' l='154' c='_ZN4llvmL19ARMCondCodeToStringENS_5ARMCC9CondCodesE'/>
<use f='llvm/llvm/lib/Target/ARM/Utils/ARMBaseInfo.h' l='177' u='r' c='_ZN4llvmL21ARMCondCodeFromStringENS_9StringRefE'/>
<doc f='llvm/llvm/lib/Target/ARM/Utils/ARMBaseInfo.h' l='37'>// Overflow                   Unordered</doc>
<use f='llvm/llvm/lib/Target/ARM/ARMBaseInstrInfo.cpp' l='2832' c='_ZL20getCmpToAddConditionN4llvm5ARMCC9CondCodesE'/>
<use f='llvm/llvm/lib/Target/ARM/ARMBaseInstrInfo.cpp' l='2832' u='r' c='_ZL20getCmpToAddConditionN4llvm5ARMCC9CondCodesE'/>
<use f='llvm/llvm/lib/Target/ARM/ARMBaseInstrInfo.cpp' l='3171' u='r' c='_ZNK4llvm16ARMBaseInstrInfo20optimizeCompareInstrERNS_12MachineInstrENS_8RegisterES3_iiPKNS_19MachineRegisterInfoE'/>
<use f='llvm/llvm/lib/Target/ARM/ARMBaseInstrInfo.cpp' l='3214' c='_ZNK4llvm16ARMBaseInstrInfo20optimizeCompareInstrERNS_12MachineInstrENS_8RegisterES3_iiPKNS_19MachineRegisterInfoE'/>
<use f='llvm/llvm/lib/Target/ARM/ARMFastISel.cpp' l='1207' u='r' c='_ZL14getComparePredN4llvm7CmpInst9PredicateE'/>
<use f='llvm/llvm/lib/Target/ARM/ARMISelLowering.cpp' l='1966' u='r' c='_ZL11FPCCToARMCCN4llvm3ISD8CondCodeERNS_5ARMCC9CondCodesES4_'/>
<use f='llvm/llvm/lib/Target/ARM/ARMISelLowering.cpp' l='1967' u='r' c='_ZL11FPCCToARMCCN4llvm3ISD8CondCodeERNS_5ARMCC9CondCodesES4_'/>
<use f='llvm/llvm/lib/Target/ARM/ARMISelLowering.cpp' l='4964' u='r' c='_ZL20checkVSELConstraintsN4llvm3ISD8CondCodeERNS_5ARMCC9CondCodesERbS5_'/>
<use f='llvm/llvm/lib/Target/ARM/ARMISelLowering.cpp' l='5300' u='r' c='_ZNK4llvm17ARMTargetLowering14LowerSELECT_CCENS_7SDValueERNS_12SelectionDAGE'/>
<use f='llvm/llvm/lib/Target/ARM/ARMInstructionSelector.cpp' l='399' u='a' c='_ZL15getComparePredsN4llvm7CmpInst9PredicateE'/>
<use f='llvm/llvm/lib/Target/ARM/ARMInstructionSelector.cpp' l='428' u='r' c='_ZL15getComparePredsN4llvm7CmpInst9PredicateE'/>
