<dec f='llvm/llvm/include/llvm/Analysis/MemDerefPrinter.h' l='16' type='llvm::raw_ostream &amp;'/>
<use f='llvm/llvm/include/llvm/Analysis/MemDerefPrinter.h' l='19' u='w' c='_ZN4llvm19MemDerefPrinterPassC1ERNS_11raw_ostreamE'/>
<use f='llvm/llvm/lib/Analysis/MemDerefPrinter.cpp' l='84' u='m' c='_ZN4llvm19MemDerefPrinterPass3runERNS_8FunctionERNS_15AnalysisManagerIS1_JEEE'/>
<use f='llvm/llvm/lib/Analysis/MemDerefPrinter.cpp' l='102' u='m' c='_ZN4llvm19MemDerefPrinterPass3runERNS_8FunctionERNS_15AnalysisManagerIS1_JEEE'/>
<use f='llvm/llvm/lib/Analysis/MemDerefPrinter.cpp' l='104' u='a' c='_ZN4llvm19MemDerefPrinterPass3runERNS_8FunctionERNS_15AnalysisManagerIS1_JEEE'/>
<use f='llvm/llvm/lib/Analysis/MemDerefPrinter.cpp' l='106' u='m' c='_ZN4llvm19MemDerefPrinterPass3runERNS_8FunctionERNS_15AnalysisManagerIS1_JEEE'/>
<use f='llvm/llvm/lib/Analysis/MemDerefPrinter.cpp' l='108' u='m' c='_ZN4llvm19MemDerefPrinterPass3runERNS_8FunctionERNS_15AnalysisManagerIS1_JEEE'/>
<use f='llvm/llvm/lib/Analysis/MemDerefPrinter.cpp' l='109' u='m' c='_ZN4llvm19MemDerefPrinterPass3runERNS_8FunctionERNS_15AnalysisManagerIS1_JEEE'/>
<offset>0</offset>
