<dec f='llvm/llvm/include/llvm/CodeGen/GlobalISel/MIPatternMatch.h' l='57' type='int64_t &amp;'/>
<use f='llvm/llvm/include/llvm/CodeGen/GlobalISel/MIPatternMatch.h' l='58' u='w' c='_ZN4llvm14MIPatternMatch13ConstantMatchC1ERl'/>
<use f='llvm/llvm/include/llvm/CodeGen/GlobalISel/MIPatternMatch.h' l='61' u='w' c='_ZN4llvm14MIPatternMatch13ConstantMatch5matchERKNS_19MachineRegisterInfoENS_8RegisterE'/>
<offset>0</offset>
