<use f='llvm/llvm/tools/bugpoint/BugDriver.h' l='56'/>
<def f='llvm/llvm/tools/bugpoint/ToolRunner.h' l='37' ll='75'/>
<use f='llvm/llvm/tools/bugpoint/ToolRunner.h' l='51' c='_ZN4llvm2CC6createEPKcRNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKS8_PKSt6vectorIS8_SaIS8_EE'/>
<use f='llvm/llvm/tools/bugpoint/ToolRunner.h' l='149'/>
<use f='llvm/llvm/tools/bugpoint/ToolRunner.h' l='153' c='_ZN4llvm3LLCC1ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEPNS_2CCEPKSt6vectorIS6_SaIS6_EEb'/>
<size>88</size>
<doc f='llvm/llvm/tools/bugpoint/ToolRunner.h' l='34'>//===---------------------------------------------------------------------===//
// CC abstraction
//</doc>
<mbr r='llvm::CC::CCPath' o='0' t='std::string'/>
<mbr r='llvm::CC::RemoteClientPath' o='256' t='std::string'/>
<mbr r='llvm::CC::ccArgs' o='512' t='std::vector&lt;std::string&gt;'/>
<fun r='_ZN4llvm2CCC1ENS_9StringRefES1_PKSt6vectorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaIS8_EE'/>
<fun r='_ZN4llvm2CC6createEPKcRNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKS8_PKSt6vectorIS8_SaIS8_EE'/>
<fun r='_ZN4llvm2CC14ExecuteProgramERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKSt6vectorIS6_SaIS6_EENS0_8FileTypeES8_S8_SD_jj'/>
<fun r='_ZN4llvm2CC16MakeSharedObjectERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEENS0_8FileTypeERS6_RKSt6vectorIS6_SaIS6_EE'/>
<use f='llvm/llvm/tools/bugpoint/ToolRunner.cpp' l='519' c='_ZN4llvm19AbstractInterpreter9createLLCEPKcRNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKS8_PKSt6vectorIS8_SaIS8_EESG_b'/>
<use f='llvm/llvm/tools/bugpoint/ToolRunner.cpp' l='842' c='_ZN4llvm2CC6createEPKcRNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKS8_PKSt6vectorIS8_SaIS8_EE'/>
<use f='llvm/llvm/tools/bugpoint/ToolRunner.cpp' l='864' c='_ZN4llvm2CC6createEPKcRNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKS8_PKSt6vectorIS8_SaIS8_EE'/>
<size>88</size>
<fun r='_ZN4llvm2CC14ExecuteProgramERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKSt6vectorIS6_SaIS6_EENS0_8FileTypeES8_S8_SD_jj'/>
<fun r='_ZN4llvm2CC16MakeSharedObjectERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEENS0_8FileTypeERS6_RKSt6vectorIS6_SaIS6_EE'/>
<fun r='_ZN4llvm2CC6createEPKcRNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKS8_PKSt6vectorIS8_SaIS8_EE'/>
