<dec f='llvm/llvm/include/llvm/Analysis/BasicAliasAnalysis.h' l='54' type='const llvm::DataLayout &amp;'/>
<use f='llvm/llvm/include/llvm/Analysis/BasicAliasAnalysis.h' l='67' u='w' c='_ZN4llvm13BasicAAResultC1ERKNS_10DataLayoutERKNS_8FunctionERKNS_17TargetLibraryInfoERNS_15AssumptionCacheEPNS_13DominatorTreeEPNS_8LoopInfoEPNS_9PhiValuesE'/>
<use f='llvm/llvm/include/llvm/Analysis/BasicAliasAnalysis.h' l='71' u='w' c='_ZN4llvm13BasicAAResultC1ERKS0_'/>
<use f='llvm/llvm/include/llvm/Analysis/BasicAliasAnalysis.h' l='71' u='r' c='_ZN4llvm13BasicAAResultC1ERKS0_'/>
<use f='llvm/llvm/include/llvm/Analysis/BasicAliasAnalysis.h' l='74' u='w' c='_ZN4llvm13BasicAAResultC1EOS0_'/>
<use f='llvm/llvm/include/llvm/Analysis/BasicAliasAnalysis.h' l='74' u='r' c='_ZN4llvm13BasicAAResultC1EOS0_'/>
<offset>64</offset>
<use f='llvm/llvm/lib/Analysis/BasicAliasAnalysis.cpp' l='1087' u='r' c='_ZN4llvm13BasicAAResult8aliasGEPEPKNS_11GEPOperatorENS_12LocationSizeERKNS_9AAMDNodesEPKNS_5ValueES4_S7_SA_SA_RNS_11AAQueryInfoE'/>
<use f='llvm/llvm/lib/Analysis/BasicAliasAnalysis.cpp' l='1088' u='r' c='_ZN4llvm13BasicAAResult8aliasGEPEPKNS_11GEPOperatorENS_12LocationSizeERKNS_9AAMDNodesEPKNS_5ValueES4_S7_SA_SA_RNS_11AAQueryInfoE'/>
<use f='llvm/llvm/lib/Analysis/BasicAliasAnalysis.cpp' l='1217' u='r' c='_ZN4llvm13BasicAAResult8aliasGEPEPKNS_11GEPOperatorENS_12LocationSizeERKNS_9AAMDNodesEPKNS_5ValueES4_S7_SA_SA_RNS_11AAQueryInfoE'/>
<use f='llvm/llvm/lib/Analysis/BasicAliasAnalysis.cpp' l='1269' u='r' c='_ZN4llvm13BasicAAResult8aliasGEPEPKNS_11GEPOperatorENS_12LocationSizeERKNS_9AAMDNodesEPKNS_5ValueES4_S7_SA_SA_RNS_11AAQueryInfoE'/>
<use f='llvm/llvm/lib/Analysis/BasicAliasAnalysis.cpp' l='1280' u='r' c='_ZN4llvm13BasicAAResult8aliasGEPEPKNS_11GEPOperatorENS_12LocationSizeERKNS_9AAMDNodesEPKNS_5ValueES4_S7_SA_SA_RNS_11AAQueryInfoE'/>
<use f='llvm/llvm/lib/Analysis/BasicAliasAnalysis.cpp' l='1574' u='r' c='_ZN4llvm13BasicAAResult10aliasCheckEPKNS_5ValueENS_12LocationSizeERKNS_9AAMDNodesES3_S4_S7_RNS_11AAQueryInfoE'/>
<use f='llvm/llvm/lib/Analysis/BasicAliasAnalysis.cpp' l='1574' u='r' c='_ZN4llvm13BasicAAResult10aliasCheckEPKNS_5ValueENS_12LocationSizeERKNS_9AAMDNodesES3_S4_S7_RNS_11AAQueryInfoE'/>
<use f='llvm/llvm/lib/Analysis/BasicAliasAnalysis.cpp' l='1577' u='r' c='_ZN4llvm13BasicAAResult10aliasCheckEPKNS_5ValueENS_12LocationSizeERKNS_9AAMDNodesES3_S4_S7_RNS_11AAQueryInfoE'/>
<use f='llvm/llvm/lib/Analysis/BasicAliasAnalysis.cpp' l='1577' u='r' c='_ZN4llvm13BasicAAResult10aliasCheckEPKNS_5ValueENS_12LocationSizeERKNS_9AAMDNodesES3_S4_S7_RNS_11AAQueryInfoE'/>
<use f='llvm/llvm/lib/Analysis/BasicAliasAnalysis.cpp' l='1689' u='r' c='_ZN4llvm13BasicAAResult19aliasCheckRecursiveEPKNS_5ValueENS_12LocationSizeERKNS_9AAMDNodesES3_S4_S7_RNS_11AAQueryInfoES3_S3_'/>
<use f='llvm/llvm/lib/Analysis/BasicAliasAnalysis.cpp' l='1690' u='r' c='_ZN4llvm13BasicAAResult19aliasCheckRecursiveEPKNS_5ValueENS_12LocationSizeERKNS_9AAMDNodesES3_S4_S7_RNS_11AAQueryInfoES3_S3_'/>
<use f='llvm/llvm/lib/Analysis/BasicAliasAnalysis.cpp' l='1797' u='r' c='_ZN4llvm13BasicAAResult23constantOffsetHeuristicERKNS_15SmallVectorImplINS0_16VariableGEPIndexEEENS_12LocationSizeES6_RKNS_5APIntEPNS_15AssumptionCach6670280'/>
<use f='llvm/llvm/lib/Analysis/BasicAliasAnalysis.cpp' l='1801' u='r' c='_ZN4llvm13BasicAAResult23constantOffsetHeuristicERKNS_15SmallVectorImplINS0_16VariableGEPIndexEEENS_12LocationSizeES6_RKNS_5APIntEPNS_15AssumptionCach6670280'/>
