<dec f='llvm/llvm/lib/Target/AArch64/Utils/AArch64BaseInfo.h' l='241' type='5'/>
<use f='llvm/llvm/lib/Target/AArch64/Utils/AArch64BaseInfo.h' l='270' c='_ZN4llvm9AArch64CCL15getCondCodeNameENS0_8CondCodeE'/>
<use f='llvm/llvm/lib/Target/AArch64/Utils/AArch64BaseInfo.h' l='304' c='_ZN4llvm9AArch64CCL24getNZCVToSatisfyCondCodeENS0_8CondCodeE'/>
<doc f='llvm/llvm/lib/Target/AArch64/Utils/AArch64BaseInfo.h' l='241'>// Plus, positive or zero     &gt;, ==, or unordered</doc>
<use f='llvm/llvm/lib/Target/AArch64/AArch64CondBrTuning.cpp' l='130' u='r' c='_ZN12_GLOBAL__N_119AArch64CondBrTuning15convertToCondBrERN4llvm12MachineInstrE'/>
<use f='llvm/llvm/lib/Target/AArch64/AArch64FastISel.cpp' l='2273' u='r' c='_ZL12getCompareCCN4llvm7CmpInst9PredicateE'/>
<use f='llvm/llvm/lib/Target/AArch64/AArch64FastISel.cpp' l='2605' u='r' c='_ZN12_GLOBAL__N_115AArch64FastISel9selectCmpEPKN4llvm11InstructionE'/>
<use f='llvm/llvm/lib/Target/AArch64/AArch64ISelLowering.cpp' l='2171' u='r' c='_ZL21changeFPCCToAArch64CCN4llvm3ISD8CondCodeERNS_9AArch64CC8CondCodeES4_'/>
<use f='llvm/llvm/lib/Target/AArch64/AArch64ISelLowering.cpp' l='2211' u='r' c='_ZL24changeFPCCToANDAArch64CCN4llvm3ISD8CondCodeERNS_9AArch64CC8CondCodeES4_'/>
<use f='llvm/llvm/lib/Target/AArch64/AArch64ISelLowering.cpp' l='4209' u='r' c='_ZNK4llvm21AArch64TargetLowering8LowerABSENS_7SDValueERNS_12SelectionDAGE'/>
<use f='llvm/llvm/lib/Target/AArch64/AArch64ISelLowering.cpp' l='14733' c='_ZL20isEquivalentMasklessjjN4llvm3ISD11LoadExtTypeEii'/>
<use f='llvm/llvm/lib/Target/AArch64/AArch64InstrInfo.cpp' l='1607' c='_ZL11getUsedNZCVN4llvm9AArch64CC8CondCodeE'/>
<use f='llvm/llvm/lib/Target/AArch64/AsmParser/AArch64AsmParser.cpp' l='2760' u='r' c='_ZN12_GLOBAL__N_116AArch64AsmParser19parseCondCodeStringEN4llvm9StringRefE'/>
<use f='llvm/llvm/lib/Target/AArch64/AsmParser/AArch64AsmParser.cpp' l='2781' u='r' c='_ZN12_GLOBAL__N_116AArch64AsmParser19parseCondCodeStringEN4llvm9StringRefE'/>
<use f='llvm/llvm/lib/Target/AArch64/GISel/AArch64InstructionSelector.cpp' l='1251' u='r' c='_ZL25changeFCMPPredToAArch64CCN4llvm7CmpInst9PredicateERNS_9AArch64CC8CondCodeES4_'/>
