<use f='llvm/llvm/include/llvm/Analysis/MemorySSA.h' l='1297' u='w' c='_ZN4llvm18def_chain_iteratorC1Ev'/>
<use f='llvm/llvm/include/llvm/Analysis/MemorySSA.h' l='1298' u='w' c='_ZN4llvm18def_chain_iteratorC1ET_'/>
<use f='llvm/llvm/include/llvm/Analysis/MemorySSA.h' l='1300' u='r' c='_ZNK4llvm18def_chain_iteratordeEv'/>
<use f='llvm/llvm/include/llvm/Analysis/MemorySSA.h' l='1304' c='_ZN4llvm18def_chain_iteratorppEv'/>
<use f='llvm/llvm/include/llvm/Analysis/MemorySSA.h' l='1306' u='w' c='_ZN4llvm18def_chain_iteratorppEv'/>
<use f='llvm/llvm/include/llvm/Analysis/MemorySSA.h' l='1308' u='w' c='_ZN4llvm18def_chain_iteratorppEv'/>
<use f='llvm/llvm/include/llvm/Analysis/MemorySSA.h' l='1310' u='w' c='_ZN4llvm18def_chain_iteratorppEv'/>
<use f='llvm/llvm/include/llvm/Analysis/MemorySSA.h' l='1316' c='_ZNK4llvm18def_chain_iteratoreqERKNS_18def_chain_iteratorIT_XT0_EEE'/>
<dec f='llvm/llvm/include/llvm/Analysis/MemorySSA.h' l='1319' type='T'/>
