<dec f='llvm/llvm/unittests/Transforms/Vectorize/VPlanTestBase.h' l='32' type='std::unique_ptr&lt;Module&gt;'/>
<use f='llvm/llvm/unittests/Transforms/Vectorize/VPlanTestBase.h' l='40' u='w' c='_ZN4llvm13VPlanTestBase11parseModuleEPKc'/>
<use f='llvm/llvm/unittests/Transforms/Vectorize/VPlanTestBase.h' l='41' u='r' c='_ZN4llvm13VPlanTestBase11parseModuleEPKc'/>
<use f='llvm/llvm/unittests/Transforms/Vectorize/VPlanTestBase.h' l='42' u='m' c='_ZN4llvm13VPlanTestBase11parseModuleEPKc'/>
<offset>192</offset>
