<use f='llvm/llvm/include/llvm/ProfileData/SampleProf.h' l='936' u='c' c='_ZN4llvm10sampleprof12SampleSorterC1ERKSt3mapIT_T0_St4lessIS3_ESaISt4pairIKS3_S4_EEE'/>
<use f='llvm/llvm/include/llvm/ProfileData/SampleProf.h' l='937' c='_ZN4llvm10sampleprof12SampleSorterC1ERKSt3mapIT_T0_St4lessIS3_ESaISt4pairIKS3_S4_EEE'/>
<use f='llvm/llvm/include/llvm/ProfileData/SampleProf.h' l='942' u='a' c='_ZNK4llvm10sampleprof12SampleSorter3getEv'/>
<dec f='llvm/llvm/include/llvm/ProfileData/SampleProf.h' l='945' type='llvm::sampleprof::SampleSorter::SamplesWithLocList'/>
