<dec f='llvm/llvm/include/llvm/Analysis/ObjCARCAnalysisUtils.h' l='227' type='llvm::Module *'/>
<use f='llvm/llvm/include/llvm/Analysis/ObjCARCAnalysisUtils.h' l='240' u='w' c='_ZN4llvm7objcarc14ARCMDKindCache4initEPNS_6ModuleE'/>
<use f='llvm/llvm/include/llvm/Analysis/ObjCARCAnalysisUtils.h' l='251' u='r' c='_ZN4llvm7objcarc14ARCMDKindCache3getENS0_11ARCMDKindIDE'/>
<use f='llvm/llvm/include/llvm/Analysis/ObjCARCAnalysisUtils.h' l='256' u='r' c='_ZN4llvm7objcarc14ARCMDKindCache3getENS0_11ARCMDKindIDE'/>
<use f='llvm/llvm/include/llvm/Analysis/ObjCARCAnalysisUtils.h' l='261' u='r' c='_ZN4llvm7objcarc14ARCMDKindCache3getENS0_11ARCMDKindIDE'/>
<offset>0</offset>
