<dec f='llvm/llvm/include/llvm/Demangle/ItaniumDemangle.h' l='1553' type='const llvm::itanium_demangle::Node *'/>
<use f='llvm/llvm/include/llvm/Demangle/ItaniumDemangle.h' l='1559' u='w' c='_ZN4llvm16itanium_demangle10BinaryExprC1EPKNS0_4NodeENS0_10StringViewES4_'/>
<use f='llvm/llvm/include/llvm/Demangle/ItaniumDemangle.h' l='1562' c='_ZNK4llvm16itanium_demangle10BinaryExpr5matchET_'/>
<use f='llvm/llvm/include/llvm/Demangle/ItaniumDemangle.h' l='1571' u='r' c='_ZNK4llvm16itanium_demangle10BinaryExpr9printLeftERNS0_12OutputStreamE'/>
<offset>128</offset>
