<dec f='llvm/llvm/include/llvm/IR/PatternMatch.h' l='979' type='Op_t'/>
<use f='llvm/llvm/include/llvm/IR/PatternMatch.h' l='981' u='w' c='_ZN4llvm12PatternMatch10FNeg_matchC1ERKT_'/>
<use f='llvm/llvm/include/llvm/IR/PatternMatch.h' l='987' u='c' c='_ZN4llvm12PatternMatch10FNeg_match5matchEPTL0__'/>
<use f='llvm/llvm/include/llvm/IR/PatternMatch.h' l='1000' u='c' c='_ZN4llvm12PatternMatch10FNeg_match5matchEPTL0__'/>
