<dec f='llvm/llvm/lib/Transforms/InstCombine/InstCombineInternal.h' l='742' type='const llvm::DataLayout &amp;'/>
<offset>2560</offset>
<use f='llvm/llvm/lib/Transforms/InstCombine/InstCombineNegator.cpp' l='110' u='w' c='_ZN4llvm7NegatorC1ERNS_11LLVMContextERKNS_10DataLayoutERNS_15AssumptionCacheERKNS_13DominatorTreeEb'/>
<use f='llvm/llvm/lib/Transforms/InstCombine/InstCombineNegator.cpp' l='365' u='r' c='_ZN4llvm7Negator9visitImplEPNS_5ValueEj'/>
