<use f='llvm/llvm/include/llvm/CodeGen/RegAllocPBQP.h' l='186' u='w' c='_ZN4llvm4PBQP8RegAlloc12NodeMetadataC1ERKS2_'/>
<use f='llvm/llvm/include/llvm/CodeGen/RegAllocPBQP.h' l='186' u='r' c='_ZN4llvm4PBQP8RegAlloc12NodeMetadataC1ERKS2_'/>
<use f='llvm/llvm/include/llvm/CodeGen/RegAllocPBQP.h' l='215' u='r' c='_ZNK4llvm4PBQP8RegAlloc12NodeMetadata17getReductionStateEv'/>
<use f='llvm/llvm/include/llvm/CodeGen/RegAllocPBQP.h' l='218' u='w' c='_ZN4llvm4PBQP8RegAlloc12NodeMetadata17setReductionStateENS2_14ReductionStateE'/>
<dec f='llvm/llvm/include/llvm/CodeGen/RegAllocPBQP.h' l='257' type='llvm::PBQP::RegAlloc::NodeMetadata::ReductionState'/>
<offset>0</offset>
