<dec f='llvm/llvm/include/llvm/Target/TargetOptions.h' l='87' type='4'/>
<use f='llvm/clang/lib/Basic/Targets/AArch64.cpp' l='107' u='r' c='_ZN5clang7targets17AArch64TargetInfoC1ERKN4llvm6TripleERKNS_13TargetOptionsE'/>
<use f='llvm/clang/lib/Basic/Targets/ARM.cpp' l='335' u='r' c='_ZN5clang7targets13ARMTargetInfoC1ERKN4llvm6TripleERKNS_13TargetOptionsE'/>
<use f='llvm/llvm/lib/CodeGen/CommandFlags.cpp' l='408' u='a' c='_ZN4llvm7codegen20RegisterCodeGenFlagsC1Ev'/>
<use f='llvm/llvm/lib/Target/ARM/ARMTargetMachine.cpp' l='239' u='r' c='_ZN4llvm20ARMBaseTargetMachineC1ERKNS_6TargetERKNS_6TripleENS_9StringRefES7_RKNS_13TargetOptionsENS_8OptionalINS_5Reloc5ModelEEENSB_INS_9CodeModel5Mod16510081'/>
