<dec f='llvm/build/lib/Target/XCore/XCoreGenRegisterInfo.inc' l='28' type='8'/>
<use f='llvm/llvm/lib/Target/XCore/XCoreISelLowering.cpp' l='839' u='r' c='_ZNK4llvm19XCoreTargetLowering14LowerEH_RETURNENS_7SDValueERNS_12SelectionDAGE'/>
<use f='llvm/build/lib/Target/XCore/XCoreGenCallingConv.inc' l='41' u='r' c='_ZL8CC_XCorejN4llvm3MVTES0_NS_11CCValAssign7LocInfoENS_3ISD10ArgFlagsTyERNS_7CCStateE'/>
<use f='llvm/build/lib/Target/XCore/XCoreGenCallingConv.inc' l='65' u='r' c='_ZL11RetCC_XCorejN4llvm3MVTES0_NS_11CCValAssign7LocInfoENS_3ISD10ArgFlagsTyERNS_7CCStateE'/>
<use f='llvm/llvm/lib/Target/XCore/XCoreISelLowering.cpp' l='1346' u='r' c='_ZNK4llvm19XCoreTargetLowering17LowerCCCArgumentsENS_7SDValueEjbRKNS_15SmallVectorImplINS_3ISD8InputArgEEERKNS_5SDLocERNS_12SelectionDAGERNS2_IS1_EE'/>
