<dec f='llvm/llvm/include/llvm/Transforms/Utils/PredicateInfo.h' l='227' type='llvm::raw_ostream &amp;'/>
<use f='llvm/llvm/include/llvm/Transforms/Utils/PredicateInfo.h' l='230' u='w' c='_ZN4llvm24PredicateInfoPrinterPassC1ERNS_11raw_ostreamE'/>
<offset>0</offset>
<use f='llvm/llvm/lib/Transforms/Utils/PredicateInfo.cpp' l='898' u='m' c='_ZN4llvm24PredicateInfoPrinterPass3runERNS_8FunctionERNS_15AnalysisManagerIS1_JEEE'/>
<use f='llvm/llvm/lib/Transforms/Utils/PredicateInfo.cpp' l='900' u='a' c='_ZN4llvm24PredicateInfoPrinterPass3runERNS_8FunctionERNS_15AnalysisManagerIS1_JEEE'/>
