<dec f='llvm/llvm/include/llvm/Analysis/ProfileSummaryInfo.h' l='41' type='const llvm::Module &amp;'/>
<use f='llvm/llvm/include/llvm/Analysis/ProfileSummaryInfo.h' l='61' u='w' c='_ZN4llvm18ProfileSummaryInfoC1ERKNS_6ModuleE'/>
<offset>0</offset>
<use f='llvm/llvm/lib/Analysis/ProfileSummaryInfo.cpp' l='98' u='m' c='_ZN4llvm18ProfileSummaryInfo7refreshEv'/>
<use f='llvm/llvm/lib/Analysis/ProfileSummaryInfo.cpp' l='104' u='m' c='_ZN4llvm18ProfileSummaryInfo7refreshEv'/>
