<dec f='llvm/llvm/lib/Target/AArch64/GISel/AArch64LegalizerInfo.h' l='50' type='const llvm::AArch64Subtarget *'/>
<offset>746112</offset>
<use f='llvm/llvm/lib/Target/AArch64/GISel/AArch64LegalizerInfo.cpp' l='37' u='w' c='_ZN4llvm20AArch64LegalizerInfoC1ERKNS_16AArch64SubtargetE'/>
<use f='llvm/llvm/lib/Target/AArch64/GISel/AArch64LegalizerInfo.cpp' l='783' u='r' c='_ZNK4llvm20AArch64LegalizerInfo26legalizeSmallCMGlobalValueERNS_12MachineInstrERNS_19MachineRegisterInfoERNS_16MachineIRBuilderERNS_19GISelChangeObserverE'/>
<use f='llvm/llvm/lib/Target/AArch64/GISel/AArch64LegalizerInfo.cpp' l='784' u='r' c='_ZNK4llvm20AArch64LegalizerInfo26legalizeSmallCMGlobalValueERNS_12MachineInstrERNS_19MachineRegisterInfoERNS_16MachineIRBuilderERNS_19GISelChangeObserverE'/>
