<dec f='llvm/build/lib/Target/SystemZ/SystemZGenInstrInfo.inc' l='1177' type='1162'/>
<use f='llvm/build/lib/Target/SystemZ/SystemZGenAsmMatcher.inc' l='4044'/>
<use f='llvm/build/lib/Target/SystemZ/SystemZGenMCCodeEmitter.inc' l='3904' c='_ZNK12_GLOBAL__N_120SystemZMCCodeEmitter21getBinaryCodeForInstrERKN4llvm6MCInstERNS1_15SmallVectorImplINS1_7MCFixupEEERKNS1_15MCSubtargetInfoE'/>
<use f='llvm/build/lib/Target/SystemZ/SystemZGenDAGISel.inc' l='20037' u='r' c='_ZN12_GLOBAL__N_119SystemZDAGToDAGISel10SelectCodeEPN4llvm6SDNodeE'/>
<use f='llvm/build/lib/Target/SystemZ/SystemZGenDAGISel.inc' l='20037' u='r' c='_ZN12_GLOBAL__N_119SystemZDAGToDAGISel10SelectCodeEPN4llvm6SDNodeE'/>
<use f='llvm/llvm/lib/Target/SystemZ/SystemZISelLowering.cpp' l='7357' u='r' c='_ZNK4llvm21SystemZTargetLowering20emitAtomicLoadBinaryERNS_12MachineInstrEPNS_17MachineBasicBlockEjjb'/>
<use f='llvm/llvm/lib/Target/SystemZ/SystemZISelLowering.cpp' l='7475' u='r' c='_ZNK4llvm21SystemZTargetLowering20emitAtomicLoadMinMaxERNS_12MachineInstrEPNS_17MachineBasicBlockEjjj'/>
<use f='llvm/llvm/lib/Target/SystemZ/SystemZISelLowering.cpp' l='7588' u='r' c='_ZNK4llvm21SystemZTargetLowering18emitAtomicCmpSwapWERNS_12MachineInstrEPNS_17MachineBasicBlockE'/>
