<dec f='llvm/llvm/include/llvm/Analysis/Delinearization.h' l='29' type='llvm::raw_ostream &amp;'/>
<use f='llvm/llvm/lib/Analysis/Delinearization.cpp' l='140' u='w' c='_ZN4llvm26DelinearizationPrinterPassC1ERNS_11raw_ostreamE'/>
<use f='llvm/llvm/lib/Analysis/Delinearization.cpp' l='143' u='a' c='_ZN4llvm26DelinearizationPrinterPass3runERNS_8FunctionERNS_15AnalysisManagerIS1_JEEE'/>
<offset>0</offset>
