<dec f='llvm/llvm/lib/Target/RISCV/MCTargetDesc/RISCVBaseInfo.h' l='131' type='1'/>
<use f='llvm/llvm/lib/Target/RISCV/AsmParser/RISCVAsmParser.cpp' l='847' u='r' c='_ZNK12_GLOBAL__N_112RISCVOperand19addFenceArgOperandsERN4llvm6MCInstEj'/>
<use f='llvm/llvm/lib/Target/RISCV/MCTargetDesc/RISCVInstPrinter.cpp' l='146' u='r' c='_ZN4llvm16RISCVInstPrinter13printFenceArgEPKNS_6MCInstEjRKNS_15MCSubtargetInfoERNS_11raw_ostreamE'/>
