<dec f='llvm/llvm/lib/Target/X86/X86.h' l='177' type='258'/>
<use f='llvm/llvm/lib/Target/X86/X86ISelDAGToDAG.cpp' l='2501' u='r' c='_ZN12_GLOBAL__N_115X86DAGToDAGISel16selectVectorAddrEPN4llvm9MemSDNodeENS1_7SDValueES4_S4_RS4_S5_S5_S5_S5_'/>
<use f='llvm/llvm/lib/Target/X86/X86ISelDAGToDAG.cpp' l='2543' u='r' c='_ZN12_GLOBAL__N_115X86DAGToDAGISel10selectAddrEPN4llvm6SDNodeENS1_7SDValueERS4_S5_S5_S5_S5_'/>
