<dec f='llvm/llvm/lib/CodeGen/AsmPrinter/DwarfUnit.h' l='337' type='llvm::DwarfCompileUnit &amp;'/>
<use f='llvm/llvm/lib/CodeGen/AsmPrinter/DwarfUnit.h' l='362' u='a' c='_ZN4llvm13DwarfTypeUnit5getCUEv'/>
<offset>2624</offset>
<use f='llvm/llvm/lib/CodeGen/AsmPrinter/DwarfUnit.cpp' l='98' u='w' c='_ZN4llvm13DwarfTypeUnitC1ERNS_16DwarfCompileUnitEPNS_10AsmPrinterEPNS_10DwarfDebugEPNS_9DwarfFileEPNS_19MCDwarfDwoLineTableE'/>
