<use f='llvm/llvm/lib/ExecutionEngine/JITLink/MachOLinkGraphBuilder.h' l='43' u='w' c='_ZN4llvm7jitlink21MachOLinkGraphBuilder16NormalizedSymbolC1ENS_8OptionalINS_9StringRefEEEmhhtNS0_7LinkageENS0_5ScopeE'/>
<dec f='llvm/llvm/lib/ExecutionEngine/JITLink/MachOLinkGraphBuilder.h' l='59' type='llvm::jitlink::Scope'/>
<use f='llvm/llvm/lib/ExecutionEngine/JITLink/MachOLinkGraphBuilder.cpp' l='348' u='r' c='_ZN4llvm7jitlink21MachOLinkGraphBuilder22graphifyRegularSymbolsEv'/>
<use f='llvm/llvm/lib/ExecutionEngine/JITLink/MachOLinkGraphBuilder.cpp' l='452' u='r' c='_ZN4llvm7jitlink21MachOLinkGraphBuilder22graphifyRegularSymbolsEv'/>
<use f='llvm/llvm/lib/ExecutionEngine/JITLink/MachOLinkGraphBuilder.cpp' l='452' u='r' c='_ZN4llvm7jitlink21MachOLinkGraphBuilder22graphifyRegularSymbolsEv'/>
<use f='llvm/llvm/lib/ExecutionEngine/JITLink/MachOLinkGraphBuilder.cpp' l='453' u='r' c='_ZN4llvm7jitlink21MachOLinkGraphBuilder22graphifyRegularSymbolsEv'/>
<use f='llvm/llvm/lib/ExecutionEngine/JITLink/MachOLinkGraphBuilder.cpp' l='453' u='r' c='_ZN4llvm7jitlink21MachOLinkGraphBuilder22graphifyRegularSymbolsEv'/>
<use f='llvm/llvm/lib/ExecutionEngine/JITLink/MachOLinkGraphBuilder.cpp' l='543' u='r' c='_ZN4llvm7jitlink21MachOLinkGraphBuilder22graphifyRegularSymbolsEv'/>
<offset>296</offset>
