<dec f='llvm/llvm/examples/Kaleidoscope/BuildingAJIT/Chapter1/KaleidoscopeJIT.h' l='38' type='llvm::DataLayout'/>
<use f='llvm/llvm/examples/Kaleidoscope/BuildingAJIT/Chapter1/KaleidoscopeJIT.h' l='50' u='w' c='_ZN4llvm3orc15KaleidoscopeJITC1ESt10unique_ptrINS0_20TargetProcessControlESt14default_deleteIS3_EES2_INS0_16ExecutionSessionES4_IS7_EENS0_23JITTargetM9673592'/>
<use f='llvm/llvm/examples/Kaleidoscope/BuildingAJIT/Chapter1/KaleidoscopeJIT.h' l='51' u='r' c='_ZN4llvm3orc15KaleidoscopeJITC1ESt10unique_ptrINS0_20TargetProcessControlESt14default_deleteIS3_EES2_INS0_16ExecutionSessionES4_IS7_EENS0_23JITTargetM9673592'/>
<use f='llvm/llvm/examples/Kaleidoscope/BuildingAJIT/Chapter1/KaleidoscopeJIT.h' l='85' u='a' c='_ZNK4llvm3orc15KaleidoscopeJIT13getDataLayoutEv'/>
<offset>128</offset>
<dec f='llvm/llvm/examples/Kaleidoscope/BuildingAJIT/Chapter2/KaleidoscopeJIT.h' l='43' type='llvm::DataLayout'/>
<use f='llvm/llvm/examples/Kaleidoscope/BuildingAJIT/Chapter2/KaleidoscopeJIT.h' l='56' u='w' c='_ZN4llvm3orc15KaleidoscopeJITC1ESt10unique_ptrINS0_20TargetProcessControlESt14default_deleteIS3_EES2_INS0_16ExecutionSessionES4_IS7_EENS0_23JITTargetM9673592'/>
<use f='llvm/llvm/examples/Kaleidoscope/BuildingAJIT/Chapter2/KaleidoscopeJIT.h' l='57' u='r' c='_ZN4llvm3orc15KaleidoscopeJITC1ESt10unique_ptrINS0_20TargetProcessControlESt14default_deleteIS3_EES2_INS0_16ExecutionSessionES4_IS7_EENS0_23JITTargetM9673592'/>
<use f='llvm/llvm/examples/Kaleidoscope/BuildingAJIT/Chapter2/KaleidoscopeJIT.h' l='92' u='a' c='_ZNK4llvm3orc15KaleidoscopeJIT13getDataLayoutEv'/>
<offset>128</offset>
<dec f='llvm/llvm/examples/Kaleidoscope/BuildingAJIT/Chapter3/KaleidoscopeJIT.h' l='46' type='llvm::DataLayout'/>
<use f='llvm/llvm/examples/Kaleidoscope/BuildingAJIT/Chapter3/KaleidoscopeJIT.h' l='67' u='w' c='_ZN4llvm3orc15KaleidoscopeJITC1ESt10unique_ptrINS0_20TargetProcessControlESt14default_deleteIS3_EES2_INS0_16ExecutionSessionES4_IS7_EES2_INS0_19TPCInd15416843'/>
<use f='llvm/llvm/examples/Kaleidoscope/BuildingAJIT/Chapter3/KaleidoscopeJIT.h' l='67' u='r' c='_ZN4llvm3orc15KaleidoscopeJITC1ESt10unique_ptrINS0_20TargetProcessControlESt14default_deleteIS3_EES2_INS0_16ExecutionSessionES4_IS7_EES2_INS0_19TPCInd15416843'/>
<use f='llvm/llvm/examples/Kaleidoscope/BuildingAJIT/Chapter3/KaleidoscopeJIT.h' l='118' u='a' c='_ZNK4llvm3orc15KaleidoscopeJIT13getDataLayoutEv'/>
<offset>192</offset>
<dec f='llvm/llvm/examples/Kaleidoscope/BuildingAJIT/Chapter4/KaleidoscopeJIT.h' l='133' type='llvm::DataLayout'/>
<use f='llvm/llvm/examples/Kaleidoscope/BuildingAJIT/Chapter4/KaleidoscopeJIT.h' l='154' u='w' c='_ZN4llvm3orc15KaleidoscopeJITC1ESt10unique_ptrINS0_20TargetProcessControlESt14default_deleteIS3_EES2_INS0_16ExecutionSessionES4_IS7_EES2_INS0_19TPCInd15416843'/>
<use f='llvm/llvm/examples/Kaleidoscope/BuildingAJIT/Chapter4/KaleidoscopeJIT.h' l='154' u='r' c='_ZN4llvm3orc15KaleidoscopeJITC1ESt10unique_ptrINS0_20TargetProcessControlESt14default_deleteIS3_EES2_INS0_16ExecutionSessionES4_IS7_EES2_INS0_19TPCInd15416843'/>
<use f='llvm/llvm/examples/Kaleidoscope/BuildingAJIT/Chapter4/KaleidoscopeJIT.h' l='160' u='r' c='_ZN4llvm3orc15KaleidoscopeJITC1ESt10unique_ptrINS0_20TargetProcessControlESt14default_deleteIS3_EES2_INS0_16ExecutionSessionES4_IS7_EES2_INS0_19TPCInd15416843'/>
<use f='llvm/llvm/examples/Kaleidoscope/BuildingAJIT/Chapter4/KaleidoscopeJIT.h' l='203' u='a' c='_ZNK4llvm3orc15KaleidoscopeJIT13getDataLayoutEv'/>
<offset>192</offset>
<dec f='llvm/llvm/examples/Kaleidoscope/include/KaleidoscopeJIT.h' l='38' type='llvm::DataLayout'/>
<use f='llvm/llvm/examples/Kaleidoscope/include/KaleidoscopeJIT.h' l='50' u='w' c='_ZN4llvm3orc15KaleidoscopeJITC1ESt10unique_ptrINS0_20TargetProcessControlESt14default_deleteIS3_EES2_INS0_16ExecutionSessionES4_IS7_EENS0_23JITTargetM9673592'/>
<use f='llvm/llvm/examples/Kaleidoscope/include/KaleidoscopeJIT.h' l='51' u='r' c='_ZN4llvm3orc15KaleidoscopeJITC1ESt10unique_ptrINS0_20TargetProcessControlESt14default_deleteIS3_EES2_INS0_16ExecutionSessionES4_IS7_EENS0_23JITTargetM9673592'/>
<use f='llvm/llvm/examples/Kaleidoscope/include/KaleidoscopeJIT.h' l='85' u='a' c='_ZNK4llvm3orc15KaleidoscopeJIT13getDataLayoutEv'/>
<offset>128</offset>
