<dec f='llvm/llvm/include/llvm/ADT/Triple.h' l='206' type='1'/>
<use f='llvm/llvm/include/llvm/ADT/Triple.h' l='530' u='r' c='_ZNK4llvm6Triple16isGNUEnvironmentEv'/>
<use f='llvm/llvm/include/llvm/ADT/Triple.h' l='573' u='r' c='_ZNK4llvm6Triple23isWindowsGNUEnvironmentEv'/>
<use f='llvm/clang/lib/Basic/Targets.cpp' l='153' c='_ZN5clang7targets14AllocateTargetERKN4llvm6TripleERKNS_13TargetOptionsE'/>
<use f='llvm/clang/lib/Basic/Targets.cpp' l='201' c='_ZN5clang7targets14AllocateTargetERKN4llvm6TripleERKNS_13TargetOptionsE'/>
<use f='llvm/clang/lib/Basic/Targets.cpp' l='512' c='_ZN5clang7targets14AllocateTargetERKN4llvm6TripleERKNS_13TargetOptionsE'/>
<use f='llvm/clang/lib/Basic/Targets.cpp' l='569' c='_ZN5clang7targets14AllocateTargetERKN4llvm6TripleERKNS_13TargetOptionsE'/>
<use f='llvm/clang/lib/Basic/Targets/ARM.cpp' l='302' c='_ZN5clang7targets13ARMTargetInfoC1ERKN4llvm6TripleERKNS_13TargetOptionsE'/>
<use f='llvm/clang/lib/Driver/Driver.cpp' l='519' u='r' c='_ZL19computeTargetTripleRKN5clang6driver6DriverEN4llvm9StringRefERKNS4_3opt7ArgListES5_'/>
<use f='llvm/clang/lib/Driver/Driver.cpp' l='527' u='r' c='_ZL19computeTargetTripleRKN5clang6driver6DriverEN4llvm9StringRefERKNS4_3opt7ArgListES5_'/>
<use f='llvm/clang/lib/Driver/Driver.cpp' l='566' u='r' c='_ZL19computeTargetTripleRKN5clang6driver6DriverEN4llvm9StringRefERKNS4_3opt7ArgListES5_'/>
<use f='llvm/clang/lib/Driver/Driver.cpp' l='569' u='r' c='_ZL19computeTargetTripleRKN5clang6driver6DriverEN4llvm9StringRefERKNS4_3opt7ArgListES5_'/>
<use f='llvm/clang/lib/Driver/Driver.cpp' l='574' u='r' c='_ZL19computeTargetTripleRKN5clang6driver6DriverEN4llvm9StringRefERKNS4_3opt7ArgListES5_'/>
<use f='llvm/clang/lib/Driver/Driver.cpp' l='5151' c='_ZNK5clang6driver6Driver12getToolChainERKN4llvm3opt7ArgListERKNS2_6TripleE'/>
<use f='llvm/clang/lib/Frontend/InitHeaderSearch.cpp' l='327' c='_ZN12_GLOBAL__N_116InitHeaderSearch23AddDefaultCIncludePathsERKN4llvm6TripleERKN5clang19HeaderSearchOptionsE'/>
<use f='llvm/llvm/lib/Support/Triple.cpp' l='237' c='_ZN4llvm6Triple22getEnvironmentTypeNameENS0_15EnvironmentTypeE'/>
<use f='llvm/llvm/lib/Support/Triple.cpp' l='548' u='r' c='_ZL16parseEnvironmentN4llvm9StringRefE'/>
<use f='llvm/llvm/lib/Support/Triple.cpp' l='780' u='r' c='_ZN4llvm6TripleC1ERKNS_5TwineE'/>
<use f='llvm/llvm/lib/Support/Triple.cpp' l='781' u='r' c='_ZN4llvm6TripleC1ERKNS_5TwineE'/>
<use f='llvm/llvm/unittests/ADT/TripleTest.cpp' l='100' c='_ZN12_GLOBAL__N_125TripleTest_ParsedIDs_Test8TestBodyEv'/>
<use f='llvm/llvm/unittests/ADT/TripleTest.cpp' l='100' u='r' c='_ZN12_GLOBAL__N_125TripleTest_ParsedIDs_Test8TestBodyEv'/>
<use f='llvm/llvm/unittests/ADT/TripleTest.cpp' l='106' c='_ZN12_GLOBAL__N_125TripleTest_ParsedIDs_Test8TestBodyEv'/>
<use f='llvm/llvm/unittests/ADT/TripleTest.cpp' l='106' u='r' c='_ZN12_GLOBAL__N_125TripleTest_ParsedIDs_Test8TestBodyEv'/>
<use f='llvm/llvm/unittests/ADT/TripleTest.cpp' l='364' c='_ZN12_GLOBAL__N_125TripleTest_ParsedIDs_Test8TestBodyEv'/>
<use f='llvm/llvm/unittests/ADT/TripleTest.cpp' l='364' u='r' c='_ZN12_GLOBAL__N_125TripleTest_ParsedIDs_Test8TestBodyEv'/>
<use f='llvm/llvm/unittests/ADT/TripleTest.cpp' l='370' c='_ZN12_GLOBAL__N_125TripleTest_ParsedIDs_Test8TestBodyEv'/>
<use f='llvm/llvm/unittests/ADT/TripleTest.cpp' l='370' u='r' c='_ZN12_GLOBAL__N_125TripleTest_ParsedIDs_Test8TestBodyEv'/>
<use f='llvm/llvm/unittests/ADT/TripleTest.cpp' l='376' c='_ZN12_GLOBAL__N_125TripleTest_ParsedIDs_Test8TestBodyEv'/>
<use f='llvm/llvm/unittests/ADT/TripleTest.cpp' l='376' u='r' c='_ZN12_GLOBAL__N_125TripleTest_ParsedIDs_Test8TestBodyEv'/>
<use f='llvm/llvm/unittests/ADT/TripleTest.cpp' l='382' c='_ZN12_GLOBAL__N_125TripleTest_ParsedIDs_Test8TestBodyEv'/>
<use f='llvm/llvm/unittests/ADT/TripleTest.cpp' l='382' u='r' c='_ZN12_GLOBAL__N_125TripleTest_ParsedIDs_Test8TestBodyEv'/>
<use f='llvm/llvm/unittests/ADT/TripleTest.cpp' l='500' c='_ZN12_GLOBAL__N_125TripleTest_ParsedIDs_Test8TestBodyEv'/>
<use f='llvm/llvm/unittests/ADT/TripleTest.cpp' l='500' u='r' c='_ZN12_GLOBAL__N_125TripleTest_ParsedIDs_Test8TestBodyEv'/>
<use f='llvm/llvm/unittests/ADT/TripleTest.cpp' l='505' c='_ZN12_GLOBAL__N_125TripleTest_ParsedIDs_Test8TestBodyEv'/>
<use f='llvm/llvm/unittests/ADT/TripleTest.cpp' l='505' u='r' c='_ZN12_GLOBAL__N_125TripleTest_ParsedIDs_Test8TestBodyEv'/>
<use f='llvm/llvm/unittests/ADT/TripleTest.cpp' l='512' c='_ZN12_GLOBAL__N_125TripleTest_ParsedIDs_Test8TestBodyEv'/>
<use f='llvm/llvm/unittests/ADT/TripleTest.cpp' l='512' u='r' c='_ZN12_GLOBAL__N_125TripleTest_ParsedIDs_Test8TestBodyEv'/>
<use f='llvm/llvm/unittests/ADT/TripleTest.cpp' l='517' c='_ZN12_GLOBAL__N_125TripleTest_ParsedIDs_Test8TestBodyEv'/>
<use f='llvm/llvm/unittests/ADT/TripleTest.cpp' l='517' u='r' c='_ZN12_GLOBAL__N_125TripleTest_ParsedIDs_Test8TestBodyEv'/>
<use f='llvm/llvm/unittests/ADT/TripleTest.cpp' l='524' c='_ZN12_GLOBAL__N_125TripleTest_ParsedIDs_Test8TestBodyEv'/>
<use f='llvm/llvm/unittests/ADT/TripleTest.cpp' l='524' u='r' c='_ZN12_GLOBAL__N_125TripleTest_ParsedIDs_Test8TestBodyEv'/>
<use f='llvm/llvm/unittests/ADT/TripleTest.cpp' l='533' c='_ZN12_GLOBAL__N_125TripleTest_ParsedIDs_Test8TestBodyEv'/>
<use f='llvm/llvm/unittests/ADT/TripleTest.cpp' l='533' u='r' c='_ZN12_GLOBAL__N_125TripleTest_ParsedIDs_Test8TestBodyEv'/>
<use f='llvm/llvm/unittests/ADT/TripleTest.cpp' l='540' c='_ZN12_GLOBAL__N_125TripleTest_ParsedIDs_Test8TestBodyEv'/>
<use f='llvm/llvm/unittests/ADT/TripleTest.cpp' l='540' u='r' c='_ZN12_GLOBAL__N_125TripleTest_ParsedIDs_Test8TestBodyEv'/>
<use f='llvm/llvm/unittests/ADT/TripleTest.cpp' l='545' c='_ZN12_GLOBAL__N_125TripleTest_ParsedIDs_Test8TestBodyEv'/>
<use f='llvm/llvm/unittests/ADT/TripleTest.cpp' l='545' u='r' c='_ZN12_GLOBAL__N_125TripleTest_ParsedIDs_Test8TestBodyEv'/>
<use f='llvm/llvm/unittests/ADT/TripleTest.cpp' l='550' c='_ZN12_GLOBAL__N_125TripleTest_ParsedIDs_Test8TestBodyEv'/>
<use f='llvm/llvm/unittests/ADT/TripleTest.cpp' l='550' u='r' c='_ZN12_GLOBAL__N_125TripleTest_ParsedIDs_Test8TestBodyEv'/>
