<dec f='llvm/llvm/include/llvm/Analysis/GlobalsModRef.h' l='36' type='const llvm::DataLayout &amp;'/>
<offset>64</offset>
<use f='llvm/llvm/lib/Analysis/GlobalsModRef.cpp' l='749' u='m' c='_ZN4llvm15GlobalsAAResult26isNonEscapingGlobalNoAliasEPKNS_11GlobalValueEPKNS_5ValueE'/>
<use f='llvm/llvm/lib/Analysis/GlobalsModRef.cpp' l='750' u='m' c='_ZN4llvm15GlobalsAAResult26isNonEscapingGlobalNoAliasEPKNS_11GlobalValueEPKNS_5ValueE'/>
<use f='llvm/llvm/lib/Analysis/GlobalsModRef.cpp' l='778' u='r' c='_ZN4llvm15GlobalsAAResult26isNonEscapingGlobalNoAliasEPKNS_11GlobalValueEPKNS_5ValueE'/>
<use f='llvm/llvm/lib/Analysis/GlobalsModRef.cpp' l='966' u='w' c='_ZN4llvm15GlobalsAAResultC1ERKNS_10DataLayoutESt8functionIFRKNS_17TargetLibraryInfoERNS_8FunctionEEE'/>
<use f='llvm/llvm/lib/Analysis/GlobalsModRef.cpp' l='969' u='w' c='_ZN4llvm15GlobalsAAResultC1EOS0_'/>
<use f='llvm/llvm/lib/Analysis/GlobalsModRef.cpp' l='969' u='r' c='_ZN4llvm15GlobalsAAResultC1EOS0_'/>
