<use f='llvm/llvm/include/llvm/ExecutionEngine/Orc/Speculation.h' l='182' u='w' c='_ZN4llvm3orc18IRSpeculationLayerC1ERNS0_16ExecutionSessionERNS0_14IRCompileLayerERNS0_10SpeculatorERNS0_17MangleAndInternerESt8functionIFNS_8OptionalI1470630'/>
<dec f='llvm/llvm/include/llvm/ExecutionEngine/Orc/Speculation.h' l='202' type='llvm::orc::Speculator &amp;'/>
<offset>320</offset>
<use f='llvm/llvm/lib/ExecutionEngine/Orc/Speculation.cpp' l='129' u='m' c='_ZN4llvm3orc18IRSpeculationLayer4emitESt10unique_ptrINS0_29MaterializationResponsibilityESt14default_deleteIS3_EENS0_16ThreadSafeModuleE'/>
