<dec f='llvm/llvm/include/llvm/Transforms/Scalar/GVNExpression.h' l='497' type='llvm::BasicBlock *'/>
<use f='llvm/llvm/include/llvm/Transforms/Scalar/GVNExpression.h' l='501' u='w' c='_ZN4llvm13GVNExpression13PHIExpressionC1EjPNS_10BasicBlockE'/>
<use f='llvm/llvm/include/llvm/Transforms/Scalar/GVNExpression.h' l='515' u='r' c='_ZNK4llvm13GVNExpression13PHIExpression6equalsERKNS0_10ExpressionE'/>
<use f='llvm/llvm/include/llvm/Transforms/Scalar/GVNExpression.h' l='515' u='r' c='_ZNK4llvm13GVNExpression13PHIExpression6equalsERKNS0_10ExpressionE'/>
<use f='llvm/llvm/include/llvm/Transforms/Scalar/GVNExpression.h' l='519' u='r' c='_ZNK4llvm13GVNExpression13PHIExpression12getHashValueEv'/>
<use f='llvm/llvm/include/llvm/Transforms/Scalar/GVNExpression.h' l='527' u='r' c='_ZNK4llvm13GVNExpression13PHIExpression13printInternalERNS_11raw_ostreamEb'/>
<offset>384</offset>
