<use f='llvm/llvm/include/llvm/CodeGen/RDFLiveness.h' l='80' u='w' c='_ZN4llvm3rdf8LivenessC1ERNS_19MachineRegisterInfoERKNS0_13DataFlowGraphE'/>
<dec f='llvm/llvm/include/llvm/CodeGen/RDFLiveness.h' l='127' type='const llvm::rdf::PhysicalRegisterInfo &amp;'/>
<use f='llvm/llvm/lib/CodeGen/RDFLiveness.cpp' l='150' u='r' c='_ZN4llvm3rdf8Liveness18getAllReachingDefsENS0_11RegisterRefENS0_8NodeAddrIPNS0_7RefNodeEEEbbRKNS0_12RegisterAggrE'/>
<use f='llvm/llvm/lib/CodeGen/RDFLiveness.cpp' l='181' u='m' c='_ZN4llvm3rdf8Liveness18getAllReachingDefsENS0_11RegisterRefENS0_8NodeAddrIPNS0_7RefNodeEEEbbRKNS0_12RegisterAggrE'/>
<use f='llvm/llvm/lib/CodeGen/RDFLiveness.cpp' l='321' u='r' c='_ZN4llvm3rdf8Liveness25getAllReachingDefsRecImplENS0_11RegisterRefENS0_8NodeAddrIPNS0_7RefNodeEEERSt3setIjSt4lessIjESaIjEERKSB_jj'/>
<use f='llvm/llvm/lib/CodeGen/RDFLiveness.cpp' l='384' u='m' c='_ZN4llvm3rdf8Liveness20getNearestAliasedRefENS0_11RegisterRefENS0_8NodeAddrIPNS0_9InstrNodeEEE'/>
<use f='llvm/llvm/lib/CodeGen/RDFLiveness.cpp' l='436' u='m' c='_ZN4llvm3rdf8Liveness17getAllReachedUsesENS0_11RegisterRefENS0_8NodeAddrIPNS0_7DefNodeEEERKNS0_12RegisterAggrE'/>
<use f='llvm/llvm/lib/CodeGen/RDFLiveness.cpp' l='449' u='m' c='_ZN4llvm3rdf8Liveness17getAllReachedUsesENS0_11RegisterRefENS0_8NodeAddrIPNS0_7DefNodeEEERKNS0_12RegisterAggrE'/>
<use f='llvm/llvm/lib/CodeGen/RDFLiveness.cpp' l='492' u='r' c='_ZN4llvm3rdf8Liveness14computePhiInfoEv'/>
<use f='llvm/llvm/lib/CodeGen/RDFLiveness.cpp' l='564' u='r' c='_ZN4llvm3rdf8Liveness14computePhiInfoEv'/>
<use f='llvm/llvm/lib/CodeGen/RDFLiveness.cpp' l='573' u='m' c='_ZN4llvm3rdf8Liveness14computePhiInfoEv'/>
<use f='llvm/llvm/lib/CodeGen/RDFLiveness.cpp' l='601' u='r' c='_ZN4llvm3rdf8Liveness14computePhiInfoEv'/>
<use f='llvm/llvm/lib/CodeGen/RDFLiveness.cpp' l='704' u='m' c='_ZN4llvm3rdf8Liveness14computePhiInfoEv'/>
<use f='llvm/llvm/lib/CodeGen/RDFLiveness.cpp' l='838' u='r' c='_ZN4llvm3rdf8Liveness14computeLiveInsEv'/>
<use f='llvm/llvm/lib/CodeGen/RDFLiveness.cpp' l='1072' u='r' c='_ZN4llvm3rdf8Liveness8traverseEPNS_17MachineBasicBlockERSt13unordered_mapIjSt13unordered_setISt4pairIjNS_11LaneBitmaskEESt4hashIS8_ESt8equal_toIS8_ESa8234351'/>
<offset>128</offset>
