<dec f='llvm/llvm/tools/llvm-xray/xray-graph-diff.h' l='57' type='llvm::xray::GraphDiffRenderer::GraphT'/>
<use f='llvm/llvm/tools/llvm-xray/xray-graph-diff.h' l='68' u='a' c='_ZN4llvm4xray17GraphDiffRenderer8getGraphEv'/>
<use f='llvm/llvm/tools/llvm-xray/xray-graph-diff.cpp' l='220' u='m' c='_ZN4llvm4xray17GraphDiffRenderer7Factory20getGraphDiffRendererEv'/>
<use f='llvm/llvm/tools/llvm-xray/xray-graph-diff.cpp' l='233' u='m' c='_ZN4llvm4xray17GraphDiffRenderer7Factory20getGraphDiffRendererEv'/>
<use f='llvm/llvm/tools/llvm-xray/xray-graph-diff.cpp' l='369' u='m' c='_ZN4llvm4xray17GraphDiffRenderer16exportGraphAsDOTERNS_11raw_ostreamENS0_13GraphRenderer8StatTypeES5_S5_S5_i'/>
<use f='llvm/llvm/tools/llvm-xray/xray-graph-diff.cpp' l='380' u='m' c='_ZN4llvm4xray17GraphDiffRenderer16exportGraphAsDOTERNS_11raw_ostreamENS0_13GraphRenderer8StatTypeES5_S5_S5_i'/>
<use f='llvm/llvm/tools/llvm-xray/xray-graph-diff.cpp' l='388' u='r' c='_ZN4llvm4xray17GraphDiffRenderer16exportGraphAsDOTERNS_11raw_ostreamENS0_13GraphRenderer8StatTypeES5_S5_S5_i'/>
<use f='llvm/llvm/tools/llvm-xray/xray-graph-diff.cpp' l='392' u='m' c='_ZN4llvm4xray17GraphDiffRenderer16exportGraphAsDOTERNS_11raw_ostreamENS0_13GraphRenderer8StatTypeES5_S5_S5_i'/>
<use f='llvm/llvm/tools/llvm-xray/xray-graph-diff.cpp' l='403' u='r' c='_ZN4llvm4xray17GraphDiffRenderer16exportGraphAsDOTERNS_11raw_ostreamENS0_13GraphRenderer8StatTypeES5_S5_S5_i'/>
<offset>0</offset>
