<dec f='llvm/llvm/lib/Target/AMDGPU/AMDGPUISelLowering.h' l='476' type='422'/>
<use f='llvm/build/lib/Target/AMDGPU/AMDGPUGenDAGISel.inc' l='191946' u='r' c='_ZN12_GLOBAL__N_118AMDGPUDAGToDAGISel10SelectCodeEPN4llvm6SDNodeE'/>
<use f='llvm/build/lib/Target/AMDGPU/AMDGPUGenDAGISel.inc' l='191946' u='r' c='_ZN12_GLOBAL__N_118AMDGPUDAGToDAGISel10SelectCodeEPN4llvm6SDNodeE'/>
<use f='llvm/llvm/lib/Target/AMDGPU/AMDGPUISelLowering.cpp' l='4304' c='_ZNK4llvm20AMDGPUTargetLowering17getTargetNodeNameEj'/>
<use f='llvm/llvm/lib/Target/AMDGPU/AMDGPUISelLowering.cpp' l='4514' c='_ZNK4llvm20AMDGPUTargetLowering29computeKnownBitsForTargetNodeENS_7SDValueERNS_9KnownBitsERKNS_5APIntERKNS_12SelectionDAGEj'/>
<use f='llvm/llvm/lib/Target/AMDGPU/SIISelLowering.cpp' l='5595' u='r' c='_ZNK4llvm16SITargetLowering18LowerGlobalAddressEPNS_21AMDGPUMachineFunctionENS_7SDValueERNS_12SelectionDAGE'/>
