<dec f='llvm/llvm/lib/CodeGen/SelectionDAG/SelectionDAGBuilder.h' l='390' type='const llvm::DataLayout *'/>
<use f='llvm/llvm/lib/CodeGen/SelectionDAG/SelectionDAGBuilder.cpp' l='1002' u='w' c='_ZN4llvm19SelectionDAGBuilder4initEPNS_14GCFunctionInfoEPNS_9AAResultsEPKNS_17TargetLibraryInfoE'/>
<use f='llvm/llvm/lib/CodeGen/SelectionDAG/SelectionDAGBuilder.cpp' l='2552' u='r' c='_ZN4llvm19SelectionDAGBuilder23visitSPDescriptorParentERNS0_24StackProtectorDescriptorEPNS_17MachineBasicBlockE'/>
<use f='llvm/llvm/lib/CodeGen/SelectionDAG/SelectionDAGBuilder.cpp' l='3772' u='r' c='_ZN4llvm19SelectionDAGBuilder18visitGetElementPtrERKNS_4UserE'/>
<use f='llvm/llvm/lib/CodeGen/SelectionDAG/SelectionDAGBuilder.cpp' l='3789' u='r' c='_ZN4llvm19SelectionDAGBuilder18visitGetElementPtrERKNS_4UserE'/>
<use f='llvm/llvm/lib/CodeGen/SelectionDAG/SelectionDAGBuilder.cpp' l='4686' u='r' c='_ZN4llvm19SelectionDAGBuilder20visitTargetIntrinsicERKNS_8CallInstEj'/>
<use f='llvm/llvm/lib/CodeGen/SelectionDAG/SelectionDAGBuilder.cpp' l='6417' u='r' c='_ZN4llvm19SelectionDAGBuilder18visitIntrinsicCallERKNS_8CallInstEj'/>
<use f='llvm/llvm/lib/CodeGen/SelectionDAG/SelectionDAGBuilder.cpp' l='7351' u='r' c='_ZL13getMemCmpLoadPKN4llvm5ValueENS_3MVTERNS_19SelectionDAGBuilderE'/>
<offset>6720</offset>
