<dec f='llvm/build/lib/Target/Mips/MipsGenInstrInfo.inc' l='2465' type='2450'/>
<use f='llvm/build/lib/Target/Mips/MipsGenAsmMatcher.inc' l='7639'/>
<use f='llvm/build/lib/Target/Mips/MipsGenMCCodeEmitter.inc' l='6705' c='_ZNK4llvm17MipsMCCodeEmitter21getBinaryCodeForInstrERKNS_6MCInstERNS_15SmallVectorImplINS_7MCFixupEEERKNS_15MCSubtargetInfoE'/>
<use f='llvm/llvm/lib/Target/Mips/MCTargetDesc/MipsNaClELFStreamer.cpp' l='236' c='_ZN4llvm28isBasePlusOffsetMemoryAccessEjPjPb'/>
<use f='llvm/llvm/lib/Target/Mips/MicroMipsSizeReduction.cpp' l='256' u='r'/>
<use f='llvm/build/lib/Target/Mips/MipsGenDAGISel.inc' l='209' u='r' c='_ZN4llvm16MipsDAGToDAGISel10SelectCodeEPNS_6SDNodeE'/>
<use f='llvm/build/lib/Target/Mips/MipsGenDAGISel.inc' l='209' u='r' c='_ZN4llvm16MipsDAGToDAGISel10SelectCodeEPNS_6SDNodeE'/>
<use f='llvm/build/lib/Target/Mips/MipsGenDAGISel.inc' l='6698' u='r' c='_ZN4llvm16MipsDAGToDAGISel10SelectCodeEPNS_6SDNodeE'/>
<use f='llvm/build/lib/Target/Mips/MipsGenDAGISel.inc' l='6698' u='r' c='_ZN4llvm16MipsDAGToDAGISel10SelectCodeEPNS_6SDNodeE'/>
<use f='llvm/llvm/lib/Target/Mips/MipsFastISel.cpp' l='823' u='r' c='_ZN12_GLOBAL__N_112MipsFastISel9emitStoreEN4llvm3MVTEjRNS0_7AddressEj'/>
<use f='llvm/llvm/lib/Target/Mips/MipsInstructionSelector.cpp' l='201' u='r' c='_ZNK12_GLOBAL__N_123MipsInstructionSelector21selectLoadStoreOpCodeERN4llvm12MachineInstrERNS1_19MachineRegisterInfoE'/>
<use f='llvm/llvm/lib/Target/Mips/MipsSEISelLowering.cpp' l='3538' u='r' c='_ZNK4llvm20MipsSETargetLowering17emitST_F16_PSEUDOERNS_12MachineInstrEPNS_17MachineBasicBlockE'/>
