<dec f='llvm/llvm/include/llvm/CodeGen/MachinePipeliner.h' l='507' type='const llvm::TargetSubtargetInfo &amp;'/>
<use f='llvm/llvm/include/llvm/CodeGen/MachinePipeliner.h' l='516' u='w' c='_ZN4llvm10SMScheduleC1EPNS_15MachineFunctionE'/>
<use f='llvm/llvm/include/llvm/CodeGen/MachinePipeliner.h' l='516' u='a' c='_ZN4llvm10SMScheduleC1EPNS_15MachineFunctionE'/>
<use f='llvm/llvm/lib/CodeGen/MachinePipeliner.cpp' l='2410' u='m' c='_ZN4llvm10SMSchedule6insertEPNS_5SUnitEiii'/>
<use f='llvm/llvm/lib/CodeGen/MachinePipeliner.cpp' l='2417' u='m' c='_ZN4llvm10SMSchedule6insertEPNS_5SUnitEiii'/>
<use f='llvm/llvm/lib/CodeGen/MachinePipeliner.cpp' l='2581' u='m' c='_ZN4llvm10SMSchedule15orderDependenceEPNS_17SwingSchedulerDAGEPNS_5SUnitERSt5dequeIS4_SaIS4_EE'/>
<offset>704</offset>
<doc f='llvm/llvm/include/llvm/CodeGen/MachinePipeliner.h' l='506'>/// Target machine information.</doc>
