<dec f='llvm/llvm/include/llvm/Support/ARMTargetParser.h' l='77' type='const char *'/>
<offset>192</offset>
<use f='llvm/llvm/lib/Support/AArch64TargetParser.cpp' l='168' u='r' c='_ZN4llvm7AArch6417getArchExtFeatureENS_9StringRefE'/>
<use f='llvm/llvm/lib/Support/AArch64TargetParser.cpp' l='169' u='r' c='_ZN4llvm7AArch6417getArchExtFeatureENS_9StringRefE'/>
<use f='llvm/llvm/lib/Support/ARMTargetParser.cpp' l='418' u='r' c='_ZN4llvm3ARM20getExtensionFeaturesEmRSt6vectorINS_9StringRefESaIS2_EE'/>
<use f='llvm/llvm/lib/Support/ARMTargetParser.cpp' l='419' u='r' c='_ZN4llvm3ARM20getExtensionFeaturesEmRSt6vectorINS_9StringRefESaIS2_EE'/>
<use f='llvm/llvm/lib/Support/ARMTargetParser.cpp' l='462' u='r' c='_ZN4llvm3ARM17getArchExtFeatureENS_9StringRefE'/>
<use f='llvm/llvm/lib/Support/ARMTargetParser.cpp' l='463' u='r' c='_ZN4llvm3ARM17getArchExtFeatureENS_9StringRefE'/>
<use f='llvm/llvm/lib/Support/ARMTargetParser.cpp' l='515' u='r' c='_ZN4llvm3ARM21appendArchExtFeaturesENS_9StringRefENS0_8ArchKindES1_RSt6vectorIS1_SaIS1_EERj'/>
<use f='llvm/llvm/lib/Support/ARMTargetParser.cpp' l='516' u='r' c='_ZN4llvm3ARM21appendArchExtFeaturesENS_9StringRefENS0_8ArchKindES1_RSt6vectorIS1_SaIS1_EERj'/>
<use f='llvm/llvm/unittests/Support/TargetParserTest.cpp' l='670' u='r' c='_ZN12_GLOBAL__N_142TargetParserTest_ARMExtensionFeatures_Test8TestBodyEv'/>
<use f='llvm/llvm/unittests/Support/TargetParserTest.cpp' l='671' u='r' c='_ZN12_GLOBAL__N_142TargetParserTest_ARMExtensionFeatures_Test8TestBodyEv'/>
