<dec f='llvm/llvm/unittests/DebugInfo/DWARF/DwarfGenerator.h' l='252' type='std::unique_ptr&lt;TargetMachine&gt;'/>
<offset>512</offset>
<use f='llvm/llvm/unittests/DebugInfo/DWARF/DwarfGenerator.cpp' l='461' u='m' c='_ZN4llvm8dwarfgen9Generator4initENS_6TripleEt'/>
<use f='llvm/llvm/unittests/DebugInfo/DWARF/DwarfGenerator.cpp' l='463' u='m' c='_ZN4llvm8dwarfgen9Generator4initENS_6TripleEt'/>
<use f='llvm/llvm/unittests/DebugInfo/DWARF/DwarfGenerator.cpp' l='467' u='m' c='_ZN4llvm8dwarfgen9Generator4initENS_6TripleEt'/>
<use f='llvm/llvm/unittests/DebugInfo/DWARF/DwarfGenerator.cpp' l='469' u='m' c='_ZN4llvm8dwarfgen9Generator4initENS_6TripleEt'/>
<use f='llvm/llvm/unittests/DebugInfo/DWARF/DwarfGenerator.cpp' l='490' u='m' c='_ZN4llvm8dwarfgen9Generator4initENS_6TripleEt'/>
