<dec f='llvm/llvm/lib/Analysis/StackLifetime.cpp' l='349' type='const llvm::StackLifetime &amp;'/>
<use f='llvm/llvm/lib/Analysis/StackLifetime.cpp' l='353' u='m' c='_ZN4llvm13StackLifetime24LifetimeAnnotationWriter15printInstrAliveEjRNS_21formatted_raw_ostreamE'/>
<use f='llvm/llvm/lib/Analysis/StackLifetime.cpp' l='354' u='m' c='_ZN4llvm13StackLifetime24LifetimeAnnotationWriter15printInstrAliveEjRNS_21formatted_raw_ostreamE'/>
<use f='llvm/llvm/lib/Analysis/StackLifetime.cpp' l='363' u='m' c='_ZN4llvm13StackLifetime24LifetimeAnnotationWriter24emitBasicBlockStartAnnotEPKNS_10BasicBlockERNS_21formatted_raw_ostreamE'/>
<use f='llvm/llvm/lib/Analysis/StackLifetime.cpp' l='364' u='m' c='_ZN4llvm13StackLifetime24LifetimeAnnotationWriter24emitBasicBlockStartAnnotEPKNS_10BasicBlockERNS_21formatted_raw_ostreamE'/>
<use f='llvm/llvm/lib/Analysis/StackLifetime.cpp' l='371' u='m' c='_ZN4llvm13StackLifetime24LifetimeAnnotationWriter16printInfoCommentERKNS_5ValueERNS_21formatted_raw_ostreamE'/>
<use f='llvm/llvm/lib/Analysis/StackLifetime.cpp' l='375' u='m' c='_ZN4llvm13StackLifetime24LifetimeAnnotationWriter16printInfoCommentERKNS_5ValueERNS_21formatted_raw_ostreamE'/>
<use f='llvm/llvm/lib/Analysis/StackLifetime.cpp' l='376' u='m' c='_ZN4llvm13StackLifetime24LifetimeAnnotationWriter16printInfoCommentERKNS_5ValueERNS_21formatted_raw_ostreamE'/>
<use f='llvm/llvm/lib/Analysis/StackLifetime.cpp' l='384' u='w' c='_ZN4llvm13StackLifetime24LifetimeAnnotationWriterC1ERKS0_'/>
<offset>64</offset>
