<use f='llvm/llvm/unittests/ExecutionEngine/Orc/QueueChannel.h' l='52' u='a' c='_ZN4llvm5Queue8getMutexEv'/>
<use f='llvm/llvm/unittests/ExecutionEngine/Orc/QueueChannel.h' l='58' u='a' c='_ZN4llvm5Queue12setReadErrorESt8functionIFNS_5ErrorEvEE'/>
<use f='llvm/llvm/unittests/ExecutionEngine/Orc/QueueChannel.h' l='64' u='a' c='_ZN4llvm5Queue13setWriteErrorESt8functionIFNS_5ErrorEvEE'/>
<dec f='llvm/llvm/unittests/ExecutionEngine/Orc/QueueChannel.h' l='68' type='std::mutex'/>
<offset>640</offset>
