<dec f='llvm/llvm/include/llvm/CodeGen/DIE.h' l='293' type='llvm::StringRef'/>
<use f='llvm/llvm/include/llvm/CodeGen/DIE.h' l='297' u='w' c='_ZN4llvm15DIEInlineStringC1ENS_9StringRefERT_'/>
<use f='llvm/llvm/include/llvm/CodeGen/DIE.h' l='302' u='r' c='_ZNK4llvm15DIEInlineString9getStringEv'/>
<offset>0</offset>
<use f='llvm/llvm/lib/CodeGen/AsmPrinter/DIE.cpp' l='626' u='r' c='_ZNK4llvm15DIEInlineString9emitValueEPKNS_10AsmPrinterENS_5dwarf4FormE'/>
<use f='llvm/llvm/lib/CodeGen/AsmPrinter/DIE.cpp' l='635' u='m' c='_ZNK4llvm15DIEInlineString6SizeOfEPKNS_10AsmPrinterENS_5dwarf4FormE'/>
<use f='llvm/llvm/lib/CodeGen/AsmPrinter/DIE.cpp' l='640' u='r' c='_ZNK4llvm15DIEInlineString5printERNS_11raw_ostreamE'/>
