<dec f='llvm/llvm/include/llvm/Analysis/StackSafetyAnalysis.h' l='95' type='llvm::raw_ostream &amp;'/>
<use f='llvm/llvm/include/llvm/Analysis/StackSafetyAnalysis.h' l='98' u='w' c='_ZN4llvm22StackSafetyPrinterPassC1ERNS_11raw_ostreamE'/>
<offset>0</offset>
<use f='llvm/llvm/lib/Analysis/StackSafetyAnalysis.cpp' l='913' u='m' c='_ZN4llvm22StackSafetyPrinterPass3runERNS_8FunctionERNS_15AnalysisManagerIS1_JEEE'/>
<use f='llvm/llvm/lib/Analysis/StackSafetyAnalysis.cpp' l='914' u='a' c='_ZN4llvm22StackSafetyPrinterPass3runERNS_8FunctionERNS_15AnalysisManagerIS1_JEEE'/>
