<dec f='llvm/llvm/include/llvm/CodeGen/RegisterUsageInfo.h' l='66' type='const llvm::LLVMTargetMachine *'/>
<offset>448</offset>
<use f='llvm/llvm/lib/CodeGen/RegisterUsageInfo.cpp' l='43' u='w' c='_ZN4llvm25PhysicalRegisterUsageInfo16setTargetMachineERKNS_17LLVMTargetMachineE'/>
<use f='llvm/llvm/lib/CodeGen/RegisterUsageInfo.cpp' l='92' u='r' c='_ZNK4llvm25PhysicalRegisterUsageInfo5printERNS_11raw_ostreamEPKNS_6ModuleE'/>
