<dec f='llvm/llvm/tools/llvm-xray/xray-graph.h' l='89' type='llvm::xray::GraphRenderer::GraphT'/>
<use f='llvm/llvm/tools/llvm-xray/xray-graph.h' l='90'/>
<use f='llvm/llvm/tools/llvm-xray/xray-graph.h' l='91'/>
<use f='llvm/llvm/tools/llvm-xray/xray-graph.h' l='129' u='m' c='_ZN4llvm4xray13GraphRendererC1ERKNS0_22FuncIdConversionHelperEb'/>
<use f='llvm/llvm/tools/llvm-xray/xray-graph.h' l='162' u='a' c='_ZN4llvm4xray13GraphRenderer8getGraphEv'/>
<offset>0</offset>
<use f='llvm/llvm/tools/llvm-xray/xray-graph.cpp' l='222' u='m' c='_ZN4llvm4xray13GraphRenderer13accountRecordERKNS0_10XRayRecordE'/>
<use f='llvm/llvm/tools/llvm-xray/xray-graph.cpp' l='223' u='m' c='_ZN4llvm4xray13GraphRenderer13accountRecordERKNS0_10XRayRecordE'/>
<use f='llvm/llvm/tools/llvm-xray/xray-graph.cpp' l='249' u='m' c='_ZN4llvm4xray13GraphRenderer13accountRecordERKNS0_10XRayRecordE'/>
<use f='llvm/llvm/tools/llvm-xray/xray-graph.cpp' l='252' u='m' c='_ZN4llvm4xray13GraphRenderer13accountRecordERKNS0_10XRayRecordE'/>
<use f='llvm/llvm/tools/llvm-xray/xray-graph.cpp' l='259' u='m' c='_ZN4llvm4xray13GraphRenderer13accountRecordERKNS0_10XRayRecordE'/>
<use f='llvm/llvm/tools/llvm-xray/xray-graph.cpp' l='262' u='m' c='_ZN4llvm4xray13GraphRenderer13accountRecordERKNS0_10XRayRecordE'/>
<use f='llvm/llvm/tools/llvm-xray/xray-graph.cpp' l='301' u='m' c='_ZN4llvm4xray13GraphRenderer23calculateEdgeStatisticsEv'/>
<use f='llvm/llvm/tools/llvm-xray/xray-graph.cpp' l='305' u='m' c='_ZN4llvm4xray13GraphRenderer23calculateEdgeStatisticsEv'/>
<use f='llvm/llvm/tools/llvm-xray/xray-graph.cpp' l='311' u='m' c='_ZN4llvm4xray13GraphRenderer25calculateVertexStatisticsEv'/>
<use f='llvm/llvm/tools/llvm-xray/xray-graph.cpp' l='313' u='m' c='_ZN4llvm4xray13GraphRenderer25calculateVertexStatisticsEv'/>
<use f='llvm/llvm/tools/llvm-xray/xray-graph.cpp' l='317' u='m' c='_ZN4llvm4xray13GraphRenderer25calculateVertexStatisticsEv'/>
<use f='llvm/llvm/tools/llvm-xray/xray-graph.cpp' l='318' u='m' c='_ZN4llvm4xray13GraphRenderer25calculateVertexStatisticsEv'/>
<use f='llvm/llvm/tools/llvm-xray/xray-graph.cpp' l='318' u='m' c='_ZN4llvm4xray13GraphRenderer25calculateVertexStatisticsEv'/>
<use f='llvm/llvm/tools/llvm-xray/xray-graph.cpp' l='335' u='m' c='_ZN4llvm4xray13GraphRenderer19normalizeStatisticsEd'/>
<use f='llvm/llvm/tools/llvm-xray/xray-graph.cpp' l='339' u='m' c='_ZN4llvm4xray13GraphRenderer19normalizeStatisticsEd'/>
<use f='llvm/llvm/tools/llvm-xray/xray-graph.cpp' l='344' u='m' c='_ZN4llvm4xray13GraphRenderer19normalizeStatisticsEd'/>
<use f='llvm/llvm/tools/llvm-xray/xray-graph.cpp' l='345' u='m' c='_ZN4llvm4xray13GraphRenderer19normalizeStatisticsEd'/>
<use f='llvm/llvm/tools/llvm-xray/xray-graph.cpp' l='407' u='m' c='_ZN4llvm4xray13GraphRenderer16exportGraphAsDOTERNS_11raw_ostreamENS1_8StatTypeES4_S4_S4_'/>
<use f='llvm/llvm/tools/llvm-xray/xray-graph.cpp' l='414' u='m' c='_ZN4llvm4xray13GraphRenderer16exportGraphAsDOTERNS_11raw_ostreamENS1_8StatTypeES4_S4_S4_'/>
<use f='llvm/llvm/tools/llvm-xray/xray-graph.cpp' l='419' u='m' c='_ZN4llvm4xray13GraphRenderer16exportGraphAsDOTERNS_11raw_ostreamENS1_8StatTypeES4_S4_S4_'/>
<use f='llvm/llvm/tools/llvm-xray/xray-graph.cpp' l='434' u='m' c='_ZN4llvm4xray13GraphRenderer16exportGraphAsDOTERNS_11raw_ostreamENS1_8StatTypeES4_S4_S4_'/>
<use f='llvm/llvm/tools/llvm-xray/xray-graph.cpp' l='486' u='m' c='_ZN4llvm4xray13GraphRenderer7Factory16getGraphRendererEv'/>
<use f='llvm/llvm/tools/llvm-xray/xray-graph.cpp' l='487' u='m' c='_ZN4llvm4xray13GraphRenderer7Factory16getGraphRendererEv'/>
