<dec f='llvm/llvm/lib/Target/ARM/Utils/ARMBaseInfo.h' l='36' type='5'/>
<use f='llvm/llvm/lib/Target/ARM/Utils/ARMBaseInfo.h' l='55' u='r' c='_ZN4llvm5ARMCCL20getOppositeConditionENS0_9CondCodesE'/>
<use f='llvm/llvm/lib/Target/ARM/Utils/ARMBaseInfo.h' l='56' c='_ZN4llvm5ARMCCL20getOppositeConditionENS0_9CondCodesE'/>
<use f='llvm/llvm/lib/Target/ARM/Utils/ARMBaseInfo.h' l='153' c='_ZN4llvmL19ARMCondCodeToStringENS_5ARMCC9CondCodesE'/>
<use f='llvm/llvm/lib/Target/ARM/Utils/ARMBaseInfo.h' l='176' u='r' c='_ZN4llvmL21ARMCondCodeFromStringENS_9StringRefE'/>
<doc f='llvm/llvm/lib/Target/ARM/Utils/ARMBaseInfo.h' l='36'>// Plus, positive or zero     &gt;, ==, or unordered</doc>
<use f='llvm/llvm/lib/Target/ARM/ARMBaseInstrInfo.cpp' l='3208' c='_ZNK4llvm16ARMBaseInstrInfo20optimizeCompareInstrERNS_12MachineInstrENS_8RegisterES3_iiPKNS_19MachineRegisterInfoE'/>
<use f='llvm/llvm/lib/Target/ARM/ARMFastISel.cpp' l='1209' u='r' c='_ZL14getComparePredN4llvm7CmpInst9PredicateE'/>
<use f='llvm/llvm/lib/Target/ARM/ARMISelDAGToDAG.cpp' l='3827' u='r' c='_ZN12_GLOBAL__N_115ARMDAGToDAGISel6SelectEPN4llvm6SDNodeE'/>
<use f='llvm/llvm/lib/Target/ARM/ARMISelDAGToDAG.cpp' l='3904' u='r' c='_ZN12_GLOBAL__N_115ARMDAGToDAGISel6SelectEPN4llvm6SDNodeE'/>
<use f='llvm/llvm/lib/Target/ARM/ARMISelLowering.cpp' l='1969' u='r' c='_ZL11FPCCToARMCCN4llvm3ISD8CondCodeERNS_5ARMCC9CondCodesES4_'/>
<use f='llvm/llvm/lib/Target/ARM/ARMISelLowering.cpp' l='4612' u='r' c='_ZNK4llvm17ARMTargetLowering9getARMCmpENS_7SDValueES1_NS_3ISD8CondCodeERS1_RNS_12SelectionDAGERKNS_5SDLocE'/>
<use f='llvm/llvm/lib/Target/ARM/ARMISelLowering.cpp' l='5278' u='r' c='_ZNK4llvm17ARMTargetLowering14LowerSELECT_CCENS_7SDValueERNS_12SelectionDAGE'/>
<use f='llvm/llvm/lib/Target/ARM/ARMInstructionSelector.cpp' l='431' u='r' c='_ZL15getComparePredsN4llvm7CmpInst9PredicateE'/>
