<dec f='llvm/llvm/include/llvm/ExecutionEngine/Orc/Mangling.h' l='32' type='llvm::orc::ExecutionSession &amp;'/>
<offset>0</offset>
<use f='llvm/llvm/lib/ExecutionEngine/Orc/Mangling.cpp' l='22' u='w' c='_ZN4llvm3orc17MangleAndInternerC1ERNS0_16ExecutionSessionERKNS_10DataLayoutE'/>
<use f='llvm/llvm/lib/ExecutionEngine/Orc/Mangling.cpp' l='30' u='m' c='_ZN4llvm3orc17MangleAndInternerclENS_9StringRefE'/>
