<dec f='llvm/llvm/include/llvm/Support/ARMWinEH.h' l='396' type='const support::ulittle32_t'/>
<use f='llvm/llvm/include/llvm/Support/ARMWinEH.h' l='398' u='w' c='_ZN4llvm3ARM5WinEH13EpilogueScopeC1ENS_7support6detail31packed_endian_specific_integralIjLNS3_10endiannessE1ELm1ELm1EEE'/>
<use f='llvm/llvm/include/llvm/Support/ARMWinEH.h' l='401' u='m' c='_ZNK4llvm3ARM5WinEH13EpilogueScope19EpilogueStartOffsetEv'/>
<use f='llvm/llvm/include/llvm/Support/ARMWinEH.h' l='406' u='m' c='_ZNK4llvm3ARM5WinEH13EpilogueScope6ResARMEv'/>
<use f='llvm/llvm/include/llvm/Support/ARMWinEH.h' l='410' u='m' c='_ZNK4llvm3ARM5WinEH13EpilogueScope10ResAArch64Ev'/>
<use f='llvm/llvm/include/llvm/Support/ARMWinEH.h' l='415' u='m' c='_ZNK4llvm3ARM5WinEH13EpilogueScope9ConditionEv'/>
<use f='llvm/llvm/include/llvm/Support/ARMWinEH.h' l='420' u='m' c='_ZNK4llvm3ARM5WinEH13EpilogueScope21EpilogueStartIndexARMEv'/>
<use f='llvm/llvm/include/llvm/Support/ARMWinEH.h' l='424' u='m' c='_ZNK4llvm3ARM5WinEH13EpilogueScope25EpilogueStartIndexAArch64Ev'/>
<offset>0</offset>
<use f='llvm/llvm/tools/llvm-readobj/ARMWinEHPrinter.cpp' l='925' u='m' c='_ZN4llvm3ARM5WinEH7Decoder15dumpXDataRecordERKNS_6object14COFFObjectFileERKNS3_10SectionRefEmm'/>
<use f='llvm/llvm/tools/llvm-readobj/ARMWinEHPrinter.cpp' l='926' u='m' c='_ZN4llvm3ARM5WinEH7Decoder15dumpXDataRecordERKNS_6object14COFFObjectFileERKNS3_10SectionRefEmm'/>
