<def f='llvm/llvm/unittests/IR/CFGBuilder.h' l='55' ll='63'/>
<use f='llvm/llvm/unittests/IR/CFGBuilder.h' l='59' c='_ZN4llvmltERKNS_10CFGBuilder3ArcES3_'/>
<use f='llvm/llvm/unittests/IR/CFGBuilder.h' l='59' c='_ZN4llvmltERKNS_10CFGBuilder3ArcES3_'/>
<use f='llvm/llvm/unittests/IR/CFGBuilder.h' l='68'/>
<use f='llvm/llvm/unittests/IR/CFGBuilder.h' l='71' c='_ZN4llvm10CFGBuilderC1EPNS_8FunctionERKSt6vectorINS0_3ArcESaIS4_EES3_INS0_6UpdateESaIS9_EE'/>
<use f='llvm/llvm/unittests/IR/CFGBuilder.h' l='80' c='_ZN4llvm10CFGBuilder8buildCFGERKSt6vectorINS0_3ArcESaIS2_EE'/>
<use f='llvm/llvm/unittests/IR/CFGBuilder.h' l='81' c='_ZN4llvm10CFGBuilder7connectERKNS0_3ArcE'/>
<use f='llvm/llvm/unittests/IR/CFGBuilder.h' l='82' c='_ZN4llvm10CFGBuilder10disconnectERKNS0_3ArcE'/>
<use f='llvm/llvm/unittests/IR/CFGBuilder.h' l='87'/>
<use f='llvm/llvm/unittests/IR/CFGBuilder.cpp' l='30' c='_ZN4llvm10CFGBuilderC1EPNS_8FunctionERKSt6vectorINS0_3ArcESaIS4_EES3_INS0_6UpdateESaIS9_EE'/>
<use f='llvm/llvm/unittests/IR/CFGBuilder.cpp' l='97' c='_ZN4llvm10CFGBuilder7connectERKNS0_3ArcE'/>
<use f='llvm/llvm/unittests/IR/CFGBuilder.cpp' l='108' c='_ZN4llvm10CFGBuilder10disconnectERKNS0_3ArcE'/>
<use f='llvm/llvm/unittests/IR/CFGBuilder.cpp' l='121' c='_ZN4llvm10CFGBuilder8buildCFGERKSt6vectorINS0_3ArcESaIS2_EE'/>
<use f='llvm/llvm/unittests/IR/CFGBuilder.cpp' l='167' c='_ZN28CFGBuilder_Construction_Test8TestBodyEv'/>
<use f='llvm/llvm/unittests/IR/CFGBuilder.cpp' l='214' c='_ZN25CFGBuilder_Deletions_Test8TestBodyEv'/>
<use f='llvm/llvm/unittests/IR/CFGBuilder.cpp' l='248' c='_ZN23CFGBuilder_Rebuild_Test8TestBodyEv'/>
<size>32</size>
<mbr r='llvm::CFGBuilder::Arc::From' o='0' t='llvm::StringRef'/>
<mbr r='llvm::CFGBuilder::Arc::To' o='128' t='llvm::StringRef'/>
<use f='llvm/llvm/unittests/IR/DominatorTreeBatchUpdatesTest.cpp' l='195' c='_ZN43DominatorTreeBatchUpdates_InsertDelete_Test8TestBodyEv'/>
<use f='llvm/llvm/unittests/IR/DominatorTreeBatchUpdatesTest.cpp' l='225' c='_ZN53DominatorTreeBatchUpdates_InsertDeleteExhaustive_Test8TestBodyEv'/>
<use f='llvm/llvm/unittests/IR/DominatorTreeBatchUpdatesTest.cpp' l='261' c='_ZN43DominatorTreeBatchUpdates_InfiniteLoop_Test8TestBodyEv'/>
<use f='llvm/llvm/unittests/IR/DominatorTreeBatchUpdatesTest.cpp' l='291' c='_ZN41DominatorTreeBatchUpdates_DeadBlocks_Test8TestBodyEv'/>
<use f='llvm/llvm/unittests/IR/DominatorTreeBatchUpdatesTest.cpp' l='324' c='_ZN44DominatorTreeBatchUpdates_InfiniteLoop2_Test8TestBodyEv'/>
<size>32</size>
<use f='llvm/llvm/unittests/IR/DominatorTreeTest.cpp' l='711' c='_ZN34DominatorTree_InsertReachable_Test8TestBodyEv'/>
<use f='llvm/llvm/unittests/IR/DominatorTreeTest.cpp' l='739' c='_ZN35DominatorTree_InsertReachable2_Test8TestBodyEv'/>
<use f='llvm/llvm/unittests/IR/DominatorTreeTest.cpp' l='765' c='_ZN36DominatorTree_InsertUnreachable_Test8TestBodyEv'/>
<use f='llvm/llvm/unittests/IR/DominatorTreeTest.cpp' l='793' c='_ZN40DominatorTree_InsertFromUnreachable_Test8TestBodyEv'/>
<use f='llvm/llvm/unittests/IR/DominatorTreeTest.cpp' l='816' c='_ZN30DominatorTree_InsertMixed_Test8TestBodyEv'/>
<use f='llvm/llvm/unittests/IR/DominatorTreeTest.cpp' l='843' c='_ZN31DominatorTree_InsertPermut_Test8TestBodyEv'/>
<use f='llvm/llvm/unittests/IR/DominatorTreeTest.cpp' l='875' c='_ZN34DominatorTree_DeleteReachable_Test8TestBodyEv'/>
<use f='llvm/llvm/unittests/IR/DominatorTreeTest.cpp' l='901' c='_ZN36DominatorTree_DeleteUnreachable_Test8TestBodyEv'/>
<use f='llvm/llvm/unittests/IR/DominatorTreeTest.cpp' l='926' c='_ZN31DominatorTree_InsertDelete_Test8TestBodyEv'/>
<use f='llvm/llvm/unittests/IR/DominatorTreeTest.cpp' l='961' c='_ZN41DominatorTree_InsertDeleteExhaustive_Test8TestBodyEv'/>
<use f='llvm/llvm/unittests/IR/DominatorTreeTest.cpp' l='1000' c='_ZN40DominatorTree_InsertIntoIrreducible_Test8TestBodyEv'/>
<size>32</size>
