<def f='llvm/llvm/include/llvm/Object/IRSymtab.h' l='73' ll='78'/>
<use f='llvm/llvm/include/llvm/Object/IRSymtab.h' l='143'/>
<use f='llvm/llvm/include/llvm/Object/IRSymtab.h' l='235'/>
<use f='llvm/llvm/include/llvm/Object/IRSymtab.h' l='354' c='_ZNK4llvm8irsymtab6Reader14module_symbolsEj'/>
<size>12</size>
<doc f='llvm/llvm/include/llvm/Object/IRSymtab.h' l='71'>/// Describes the range of a particular module&apos;s symbols within the symbol
/// table.</doc>
<mbr r='llvm::irsymtab::storage::Module::Begin' o='0' t='llvm::irsymtab::storage::Word'/>
<mbr r='llvm::irsymtab::storage::Module::End' o='32' t='llvm::irsymtab::storage::Word'/>
<mbr r='llvm::irsymtab::storage::Module::UncBegin' o='64' t='llvm::irsymtab::storage::Word'/>
<use f='llvm/llvm/lib/Object/IRSymtab.cpp' l='85'/>
<use f='llvm/llvm/lib/Object/IRSymtab.cpp' l='128' c='_ZN12_GLOBAL__N_17Builder9addModuleEPN4llvm6ModuleE'/>
<size>12</size>
