<dec f='llvm/llvm/include/llvm/CodeGen/TargetPassConfig.h' l='86' type='llvm::legacy::PassManagerBase *'/>
<offset>256</offset>
<use f='llvm/llvm/lib/CodeGen/TargetPassConfig.cpp' l='561' u='w' c='_ZN4llvm16TargetPassConfigC1ERNS_17LLVMTargetMachineERNS_6legacy15PassManagerBaseE'/>
<use f='llvm/llvm/lib/CodeGen/TargetPassConfig.cpp' l='699' u='r' c='_ZN4llvm16TargetPassConfig7addPassEPNS_4PassEb'/>
<use f='llvm/llvm/lib/CodeGen/TargetPassConfig.cpp' l='753' u='r' c='_ZN4llvm16TargetPassConfig12addPrintPassERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE'/>
<use f='llvm/llvm/lib/CodeGen/TargetPassConfig.cpp' l='763' u='r' c='_ZN4llvm16TargetPassConfig13addVerifyPassERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE'/>
<use f='llvm/llvm/lib/CodeGen/TargetPassConfig.cpp' l='767' u='r' c='_ZN4llvm16TargetPassConfig15addDebugifyPassEv'/>
<use f='llvm/llvm/lib/CodeGen/TargetPassConfig.cpp' l='771' u='r' c='_ZN4llvm16TargetPassConfig17addStripDebugPassEv'/>
<use f='llvm/llvm/lib/CodeGen/TargetPassConfig.cpp' l='775' u='r' c='_ZN4llvm16TargetPassConfig17addCheckDebugPassEv'/>
<use f='llvm/llvm/lib/CodeGen/TargetPassConfig.cpp' l='1045' u='r' c='_ZN4llvm16TargetPassConfig13addISelPassesEv'/>
