<dec f='llvm/llvm/unittests/DebugInfo/DWARF/DwarfGenerator.h' l='246' type='std::unique_ptr&lt;MCContext&gt;'/>
<use f='llvm/llvm/unittests/DebugInfo/DWARF/DwarfGenerator.h' l='311' u='m' c='_ZNK4llvm8dwarfgen9Generator12getMCContextEv'/>
<offset>128</offset>
<use f='llvm/llvm/unittests/DebugInfo/DWARF/DwarfGenerator.cpp' l='468' u='m' c='_ZN4llvm8dwarfgen9Generator4initENS_6TripleEt'/>
<use f='llvm/llvm/unittests/DebugInfo/DWARF/DwarfGenerator.cpp' l='469' u='m' c='_ZN4llvm8dwarfgen9Generator4initENS_6TripleEt'/>
<use f='llvm/llvm/unittests/DebugInfo/DWARF/DwarfGenerator.cpp' l='471' u='m' c='_ZN4llvm8dwarfgen9Generator4initENS_6TripleEt'/>
<use f='llvm/llvm/unittests/DebugInfo/DWARF/DwarfGenerator.cpp' l='479' u='m' c='_ZN4llvm8dwarfgen9Generator4initENS_6TripleEt'/>
<use f='llvm/llvm/unittests/DebugInfo/DWARF/DwarfGenerator.cpp' l='496' u='m' c='_ZN4llvm8dwarfgen9Generator4initENS_6TripleEt'/>
<use f='llvm/llvm/unittests/DebugInfo/DWARF/DwarfGenerator.cpp' l='532' u='m' c='_ZN4llvm8dwarfgen9Generator8generateEv'/>
<use f='llvm/llvm/unittests/DebugInfo/DWARF/DwarfGenerator.cpp' l='549' u='m' c='_ZN4llvm8dwarfgen9Generator8generateEv'/>
