<dec f='llvm/llvm/include/llvm/Analysis/LoopNestAnalysis.h' l='164' type='llvm::raw_ostream &amp;'/>
<use f='llvm/llvm/include/llvm/Analysis/LoopNestAnalysis.h' l='167' u='w' c='_ZN4llvm19LoopNestPrinterPassC1ERNS_11raw_ostreamE'/>
<offset>0</offset>
<use f='llvm/llvm/lib/Analysis/LoopNestAnalysis.cpp' l='377' u='a' c='_ZN4llvm19LoopNestPrinterPass3runERNS_4LoopERNS_15AnalysisManagerIS1_JRNS_27LoopStandardAnalysisResultsEEEES5_RNS_10LPMUpdaterE'/>
