<dec f='llvm/llvm/include/llvm/Analysis/PhiValues.h' l='131' type='llvm::raw_ostream &amp;'/>
<use f='llvm/llvm/include/llvm/Analysis/PhiValues.h' l='134' u='w' c='_ZN4llvm20PhiValuesPrinterPassC1ERNS_11raw_ostreamE'/>
<offset>0</offset>
<use f='llvm/llvm/lib/Analysis/PhiValues.cpp' l='197' u='m' c='_ZN4llvm20PhiValuesPrinterPass3runERNS_8FunctionERNS_15AnalysisManagerIS1_JEEE'/>
<use f='llvm/llvm/lib/Analysis/PhiValues.cpp' l='202' u='a' c='_ZN4llvm20PhiValuesPrinterPass3runERNS_8FunctionERNS_15AnalysisManagerIS1_JEEE'/>
