<dec f='llvm/build/lib/Target/X86/X86GenRegisterInfo.inc' l='51' type='31'/>
<use f='llvm/llvm/lib/Target/X86/MCTargetDesc/X86BaseInfo.h' l='386' c='_ZN4llvm3X8630getSegmentOverridePrefixForRegEj'/>
<use f='llvm/llvm/lib/Target/X86/AsmParser/X86Operand.h' l='402' u='r' c='_ZNK4llvm10X86Operand8isDstIdxEv'/>
<use f='llvm/build/lib/Target/X86/X86GenAsmMatcher.inc' l='7428' c='_ZL20validateOperandClassRN4llvm18MCParsedAsmOperandEN12_GLOBAL__N_114MatchClassKindE'/>
<use f='llvm/llvm/lib/Target/X86/Disassembler/X86Disassembler.cpp' l='1773' macro='1' u='r' c='_ZL17translateRegisterRN4llvm6MCInstENS_15X86Disassembler3RegE'/>
<use f='llvm/llvm/lib/Target/X86/Disassembler/X86Disassembler.cpp' l='1825'/>
<use f='llvm/llvm/lib/Target/X86/Disassembler/X86Disassembler.cpp' l='2010' macro='1' u='r' c='_ZL19translateRMRegisterRN4llvm6MCInstERNS_15X86Disassembler19InternalInstructionE'/>
<use f='llvm/llvm/lib/Target/X86/X86RegisterInfo.cpp' l='563' u='r' c='_ZNK4llvm15X86RegisterInfo15getReservedRegsERKNS_15MachineFunctionE'/>
