<dec f='llvm/llvm/tools/llvm-jitlink/llvm-jitlink.h' l='115' type='orc::ExecutionSession'/>
<offset>64</offset>
<use f='llvm/llvm/tools/llvm-jitlink/llvm-jitlink.cpp' l='497' u='a' c='_ZN4llvm29LLVMJITLinkObjectLinkingLayerC1ERNS_7SessionERNS_7jitlink20JITLinkMemoryManagerE'/>
<use f='llvm/llvm/tools/llvm-jitlink/llvm-jitlink.cpp' l='567' u='m' c='_ZN4llvm29LLVMJITLinkObjectLinkingLayer3addENS_18IntrusiveRefCntPtrINS_3orc15ResourceTrackerEEESt10unique_ptrINS_12MemoryBufferESt14default_deleteIS6_EE'/>
<use f='llvm/llvm/tools/llvm-jitlink/llvm-jitlink.cpp' l='780' u='m' c='_ZN4llvm7SessionD1Ev'/>
<use f='llvm/llvm/tools/llvm-jitlink/llvm-jitlink.cpp' l='781' u='m' c='_ZN4llvm7SessionD1Ev'/>
<use f='llvm/llvm/tools/llvm-jitlink/llvm-jitlink.cpp' l='814' u='m' c='_ZN4llvm7SessionC1ESt10unique_ptrINS_3orc20TargetProcessControlESt14default_deleteIS3_EERNS_5ErrorE'/>
<use f='llvm/llvm/tools/llvm-jitlink/llvm-jitlink.cpp' l='823' u='a' c='_ZN4llvm7SessionC1ESt10unique_ptrINS_3orc20TargetProcessControlESt14default_deleteIS3_EERNS_5ErrorE'/>
<use f='llvm/llvm/tools/llvm-jitlink/llvm-jitlink.cpp' l='835' u='a' c='_ZN4llvm7SessionC1ESt10unique_ptrINS_3orc20TargetProcessControlESt14default_deleteIS3_EERNS_5ErrorE'/>
<use f='llvm/llvm/tools/llvm-jitlink/llvm-jitlink.cpp' l='1035' u='m' c='_ZL18loadProcessSymbolsRN4llvm7SessionE'/>
<use f='llvm/llvm/tools/llvm-jitlink/llvm-jitlink.cpp' l='1075' u='m' c='_ZL11loadObjectsRN4llvm7SessionE'/>
<use f='llvm/llvm/tools/llvm-jitlink/llvm-jitlink.cpp' l='1152' u='m' c='_ZL11loadObjectsRN4llvm7SessionE'/>
<use f='llvm/llvm/tools/llvm-jitlink/llvm-jitlink.cpp' l='1261' u='m' c='_ZL17getMainEntryPointRN4llvm7SessionE'/>
<use f='llvm/llvm/tools/llvm-jitlink/llvm-jitlink.cpp' l='1305' u='m' c='main'/>
<use f='llvm/llvm/tools/llvm-jitlink/llvm-jitlink.cpp' l='1329' u='m' c='main'/>
