<dec f='llvm/llvm/include/llvm/ExecutionEngine/Orc/Mangling.h' l='33' type='const llvm::DataLayout &amp;'/>
<offset>64</offset>
<use f='llvm/llvm/lib/ExecutionEngine/Orc/Mangling.cpp' l='22' u='w' c='_ZN4llvm3orc17MangleAndInternerC1ERNS0_16ExecutionSessionERKNS_10DataLayoutE'/>
<use f='llvm/llvm/lib/ExecutionEngine/Orc/Mangling.cpp' l='28' u='r' c='_ZN4llvm3orc17MangleAndInternerclENS_9StringRefE'/>
