<dec f='llvm/build/lib/Target/ARM/ARMGenInstrInfo.inc' l='251' type='236'/>
<use f='llvm/llvm/lib/Target/ARM/ARMBaseInstrInfo.h' l='562' u='r' c='_ZN4llvmL20isUncondBranchOpcodeEi'/>
<use f='llvm/build/lib/Target/ARM/ARMGenMCPseudoLowering.inc' l='14' c='_ZN4llvm13ARMAsmPrinter27emitPseudoExpansionLoweringERNS_10MCStreamerEPKNS_12MachineInstrE'/>
<use f='llvm/llvm/lib/Target/ARM/ARMBaseInstrInfo.cpp' l='487' u='r' c='_ZNK4llvm16ARMBaseInstrInfo12insertBranchERNS_17MachineBasicBlockEPS1_S3_NS_8ArrayRefINS_14MachineOperandEEERKNS_8DebugLocEPi'/>
<use f='llvm/llvm/lib/Target/ARM/ARMBaseInstrInfo.cpp' l='2233' u='r' c='_ZN4llvm27getMatchingCondBranchOpcodeEj'/>
<use f='llvm/llvm/lib/Target/ARM/ARMConstantIslandPass.cpp' l='758' u='r' c='_ZN12_GLOBAL__N_118ARMConstantIslands22initializeFunctionInfoERKSt6vectorIPN4llvm12MachineInstrESaIS4_EE'/>
<use f='llvm/llvm/lib/Target/ARM/ARMConstantIslandPass.cpp' l='760' c='_ZN12_GLOBAL__N_118ARMConstantIslands22initializeFunctionInfoERKSt6vectorIPN4llvm12MachineInstrESaIS4_EE'/>
<use f='llvm/llvm/lib/Target/ARM/ARMConstantIslandPass.cpp' l='951' u='r' c='_ZN12_GLOBAL__N_118ARMConstantIslands21splitBlockBeforeInstrEPN4llvm12MachineInstrE'/>
<use f='llvm/llvm/lib/Target/ARM/ARMConstantIslandPass.cpp' l='1337' u='r' c='_ZN12_GLOBAL__N_118ARMConstantIslands14createNewWaterEjjRPN4llvm17MachineBasicBlockE'/>
<use f='llvm/build/lib/Target/ARM/ARMGenDAGISel.inc' l='59974' u='r' c='_ZN12_GLOBAL__N_115ARMDAGToDAGISel10SelectCodeEPN4llvm6SDNodeE'/>
<use f='llvm/build/lib/Target/ARM/ARMGenDAGISel.inc' l='59974' u='r' c='_ZN12_GLOBAL__N_115ARMDAGToDAGISel10SelectCodeEPN4llvm6SDNodeE'/>
<use f='llvm/llvm/lib/Target/ARM/ARMISelLowering.cpp' l='11168' u='r' c='_ZNK4llvm17ARMTargetLowering27EmitInstrWithCustomInserterERNS_12MachineInstrEPNS_17MachineBasicBlockE'/>
<use f='llvm/build/lib/Target/ARM/ARMGenGlobalISel.inc' l='45620' u='r' c='_ZNK12_GLOBAL__N_122ARMInstructionSelector13getMatchTableEv'/>
