<dec f='llvm/llvm/include/llvm/MCA/Instruction.h' l='338' type='llvm::mca::CycleSegment'/>
<use f='llvm/llvm/include/llvm/MCA/Instruction.h' l='341' u='w' c='_ZN4llvm3mca13ResourceUsageC1ENS0_12CycleSegmentEj'/>
<use f='llvm/llvm/include/llvm/MCA/Instruction.h' l='342' u='m' c='_ZNK4llvm3mca13ResourceUsage4sizeEv'/>
<use f='llvm/llvm/include/llvm/MCA/Instruction.h' l='343' u='m' c='_ZNK4llvm3mca13ResourceUsage10isReservedEv'/>
<use f='llvm/llvm/include/llvm/MCA/Instruction.h' l='344' u='m' c='_ZN4llvm3mca13ResourceUsage11setReservedEv'/>
<offset>0</offset>
<use f='llvm/llvm/lib/MCA/HardwareUnits/ResourceManager.cpp' l='301' u='r' c='_ZN4llvm3mca15ResourceManager16issueInstructionERKNS0_9InstrDescERNS_15SmallVectorImplISt4pairIS6_ImmENS0_14ResourceCyclesEEEE'/>
<use f='llvm/llvm/lib/MCA/InstrBuilder.cpp' l='135' u='m' c='_ZN4llvm3mcaL23initializeUsedResourcesERNS0_9InstrDescERKNS_16MCSchedClassDescERKNS_15MCSubtargetInfoENS_8ArrayRefImEE'/>
