<use f='llvm/llvm/include/llvm/ExecutionEngine/Orc/ThreadSafeModule.h' l='54' u='w' c='_ZN4llvm3orc17ThreadSafeContextC1ESt10unique_ptrINS_11LLVMContextESt14default_deleteIS3_EE'/>
<use f='llvm/llvm/include/llvm/ExecutionEngine/Orc/ThreadSafeModule.h' l='61' u='m' c='_ZN4llvm3orc17ThreadSafeContext10getContextEv'/>
<use f='llvm/llvm/include/llvm/ExecutionEngine/Orc/ThreadSafeModule.h' l='61' u='m' c='_ZN4llvm3orc17ThreadSafeContext10getContextEv'/>
<use f='llvm/llvm/include/llvm/ExecutionEngine/Orc/ThreadSafeModule.h' l='65' u='m' c='_ZNK4llvm3orc17ThreadSafeContext10getContextEv'/>
<use f='llvm/llvm/include/llvm/ExecutionEngine/Orc/ThreadSafeModule.h' l='65' u='m' c='_ZNK4llvm3orc17ThreadSafeContext10getContextEv'/>
<use f='llvm/llvm/include/llvm/ExecutionEngine/Orc/ThreadSafeModule.h' l='69' u='r' c='_ZNK4llvm3orc17ThreadSafeContext7getLockEv'/>
<dec f='llvm/llvm/include/llvm/ExecutionEngine/Orc/ThreadSafeModule.h' l='73' type='std::shared_ptr&lt;State&gt;'/>
<offset>0</offset>
