<dec f='llvm/llvm/lib/Transforms/Vectorize/VPlan.h' l='1067' type='const InterleaveGroup&lt;llvm::Instruction&gt; *'/>
<use f='llvm/llvm/lib/Transforms/Vectorize/VPlan.h' l='1074' u='w' c='_ZN4llvm18VPInterleaveRecipeC1EPKNS_15InterleaveGroupINS_11InstructionEEEPNS_7VPValueENS_8ArrayRefIS7_EES7_'/>
<use f='llvm/llvm/lib/Transforms/Vectorize/VPlan.h' l='1124' u='r' c='_ZN4llvm18VPInterleaveRecipe18getInterleaveGroupEv'/>
<use f='llvm/llvm/lib/Transforms/Vectorize/LoopVectorize.cpp' l='8942' u='r' c='_ZNK4llvm18VPInterleaveRecipe5printERNS_11raw_ostreamERKNS_5TwineERNS_13VPSlotTrackerE'/>
<use f='llvm/llvm/lib/Transforms/Vectorize/LoopVectorize.cpp' l='8943' u='r' c='_ZNK4llvm18VPInterleaveRecipe5printERNS_11raw_ostreamERKNS_5TwineERNS_13VPSlotTrackerE'/>
<use f='llvm/llvm/lib/Transforms/Vectorize/LoopVectorize.cpp' l='8951' u='r' c='_ZNK4llvm18VPInterleaveRecipe5printERNS_11raw_ostreamERKNS_5TwineERNS_13VPSlotTrackerE'/>
<use f='llvm/llvm/lib/Transforms/Vectorize/LoopVectorize.cpp' l='8952' u='r' c='_ZNK4llvm18VPInterleaveRecipe5printERNS_11raw_ostreamERKNS_5TwineERNS_13VPSlotTrackerE'/>
<use f='llvm/llvm/lib/Transforms/Vectorize/LoopVectorize.cpp' l='9029' u='r' c='_ZN4llvm18VPInterleaveRecipe7executeERNS_16VPTransformStateE'/>
<offset>704</offset>
