<dec f='llvm/llvm/lib/IR/Verifier.cpp' l='127' type='const llvm::Module &amp;'/>
<use f='llvm/llvm/lib/IR/Verifier.cpp' l='141' u='w' c='_ZN4llvm15VerifierSupportC1EPNS_11raw_ostreamERKNS_6ModuleE'/>
<use f='llvm/llvm/lib/IR/Verifier.cpp' l='167' u='a' c='_ZN4llvm15VerifierSupport5WriteEPKNS_8MetadataE'/>
<use f='llvm/llvm/lib/IR/Verifier.cpp' l='381' c='_ZN12_GLOBAL__N_18Verifier6verifyEv'/>
<use f='llvm/llvm/lib/IR/Verifier.cpp' l='388' u='m' c='_ZN12_GLOBAL__N_18Verifier6verifyEv'/>
<use f='llvm/llvm/lib/IR/Verifier.cpp' l='391' u='m' c='_ZN12_GLOBAL__N_18Verifier6verifyEv'/>
<use f='llvm/llvm/lib/IR/Verifier.cpp' l='394' u='m' c='_ZN12_GLOBAL__N_18Verifier6verifyEv'/>
<use f='llvm/llvm/lib/IR/Verifier.cpp' l='397' u='m' c='_ZN12_GLOBAL__N_18Verifier6verifyEv'/>
<use f='llvm/llvm/lib/IR/Verifier.cpp' l='400' u='r' c='_ZN12_GLOBAL__N_18Verifier6verifyEv'/>
<use f='llvm/llvm/lib/IR/Verifier.cpp' l='401' u='r' c='_ZN12_GLOBAL__N_18Verifier6verifyEv'/>
<use f='llvm/llvm/lib/IR/Verifier.cpp' l='402' u='r' c='_ZN12_GLOBAL__N_18Verifier6verifyEv'/>
<use f='llvm/llvm/lib/IR/Verifier.cpp' l='621' u='a' c='_ZN12_GLOBAL__N_18Verifier16visitGlobalValueERKN4llvm11GlobalValueE'/>
<use f='llvm/llvm/lib/IR/Verifier.cpp' l='623' u='a' c='_ZN12_GLOBAL__N_18Verifier16visitGlobalValueERKN4llvm11GlobalValueE'/>
<use f='llvm/llvm/lib/IR/Verifier.cpp' l='624' u='a' c='_ZN12_GLOBAL__N_18Verifier16visitGlobalValueERKN4llvm11GlobalValueE'/>
<use f='llvm/llvm/lib/IR/Verifier.cpp' l='629' u='a' c='_ZN12_GLOBAL__N_18Verifier16visitGlobalValueERKN4llvm11GlobalValueE'/>
<use f='llvm/llvm/lib/IR/Verifier.cpp' l='630' u='a' c='_ZN12_GLOBAL__N_18Verifier16visitGlobalValueERKN4llvm11GlobalValueE'/>
<use f='llvm/llvm/lib/IR/Verifier.cpp' l='1413' u='m' c='_ZN12_GLOBAL__N_18Verifier11visitComdatERKN4llvm6ComdatE'/>
<use f='llvm/llvm/lib/IR/Verifier.cpp' l='1567' u='m' c='_ZN12_GLOBAL__N_18Verifier15visitModuleFlagEPKN4llvm6MDNodeERNS1_8DenseMapIPKNS1_8MDStringES4_NS1_12DenseMapInfoIS8_EENS1_6detail12DenseMapPairIS8_S4_1914227'/>
<use f='llvm/llvm/lib/IR/Verifier.cpp' l='2059' u='a' c='_ZN12_GLOBAL__N_18Verifier29visitConstantExprsRecursivelyEPKN4llvm8ConstantE'/>
<use f='llvm/llvm/lib/IR/Verifier.cpp' l='2060' u='a' c='_ZN12_GLOBAL__N_18Verifier29visitConstantExprsRecursivelyEPKN4llvm8ConstantE'/>
<use f='llvm/llvm/lib/IR/Verifier.cpp' l='4375' u='a' c='_ZN12_GLOBAL__N_18Verifier16visitInstructionERN4llvm11InstructionE'/>
<use f='llvm/llvm/lib/IR/Verifier.cpp' l='4376' u='a' c='_ZN12_GLOBAL__N_18Verifier16visitInstructionERN4llvm11InstructionE'/>
<use f='llvm/llvm/lib/IR/Verifier.cpp' l='4384' u='a' c='_ZN12_GLOBAL__N_18Verifier16visitInstructionERN4llvm11InstructionE'/>
<use f='llvm/llvm/lib/IR/Verifier.cpp' l='4385' u='a' c='_ZN12_GLOBAL__N_18Verifier16visitInstructionERN4llvm11InstructionE'/>
<use f='llvm/llvm/lib/IR/Verifier.cpp' l='5499' u='m' c='_ZN12_GLOBAL__N_18Verifier18verifyCompileUnitsEv'/>
<use f='llvm/llvm/lib/IR/Verifier.cpp' l='5501' u='m' c='_ZN12_GLOBAL__N_18Verifier18verifyCompileUnitsEv'/>
<offset>64</offset>
