<dec f='llvm/llvm/lib/Transforms/Instrumentation/ValueProfileCollector.h' l='60' type='llvm::Value *'/>
<use f='llvm/llvm/lib/Transforms/Instrumentation/PGOInstrumentation.cpp' l='955' u='r' c='_ZL17instrumentOneFuncRN4llvm8FunctionEPNS_6ModuleERNS_17TargetLibraryInfoEPNS_21BranchProbabilityInfoEPNS_18BlockFrequencyInfoERSt18unordered_multima3315825'/>
<use f='llvm/llvm/lib/Transforms/Instrumentation/PGOInstrumentation.cpp' l='956' u='r' c='_ZL17instrumentOneFuncRN4llvm8FunctionEPNS_6ModuleERNS_17TargetLibraryInfoEPNS_21BranchProbabilityInfoEPNS_18BlockFrequencyInfoERSt18unordered_multima3315825'/>
<use f='llvm/llvm/lib/Transforms/Instrumentation/PGOInstrumentation.cpp' l='957' u='r' c='_ZL17instrumentOneFuncRN4llvm8FunctionEPNS_6ModuleERNS_17TargetLibraryInfoEPNS_21BranchProbabilityInfoEPNS_18BlockFrequencyInfoERSt18unordered_multima3315825'/>
<use f='llvm/llvm/lib/Transforms/Instrumentation/PGOInstrumentation.cpp' l='958' u='r' c='_ZL17instrumentOneFuncRN4llvm8FunctionEPNS_6ModuleERNS_17TargetLibraryInfoEPNS_21BranchProbabilityInfoEPNS_18BlockFrequencyInfoERSt18unordered_multima3315825'/>
<offset>0</offset>
<doc f='llvm/llvm/lib/Transforms/Instrumentation/ValueProfileCollector.h' l='60'>// The value to profile.</doc>
