<dec f='llvm/llvm/include/llvm/Support/raw_ostream.h' l='96' type='1'/>
<use f='llvm/llvm/include/llvm/Support/raw_ostream.h' l='108'/>
<use f='llvm/clang/tools/diagtool/TreeView.cpp' l='68' u='r' c='_ZN11TreePrinter10printGroupERKN8diagtool11GroupRecordEj'/>
<use f='llvm/clang/tools/diagtool/TreeView.cpp' l='134' u='r' c='_ZN11TreePrinter7showKeyEv'/>
<use f='llvm/lld/Common/ErrorHandler.cpp' l='220' u='r' c='_ZN3lld12ErrorHandler5errorERKN4llvm5TwineE'/>
<use f='llvm/lld/Common/ErrorHandler.cpp' l='223' u='r' c='_ZN3lld12ErrorHandler5errorERKN4llvm5TwineE'/>
