<dec f='llvm/llvm/include/llvm/Analysis/VectorUtils.h' l='217' type='const llvm::Module *'/>
<use f='llvm/llvm/include/llvm/Analysis/VectorUtils.h' l='269' u='w' c='_ZN4llvm10VFDatabaseC1ERNS_8CallInstE'/>
<use f='llvm/llvm/include/llvm/Analysis/VectorUtils.h' l='281' u='r' c='_ZNK4llvm10VFDatabase21getVectorizedFunctionERKNS_7VFShapeE'/>
<offset>0</offset>
<doc f='llvm/llvm/include/llvm/Analysis/VectorUtils.h' l='216'>/// The Module of the CallInst CI.</doc>
