<dec f='llvm/llvm/include/llvm/ExecutionEngine/Orc/ObjectLinkingLayer.h' l='203' type='llvm::orc::ExecutionSession &amp;'/>
<offset>384</offset>
<use f='llvm/llvm/lib/ExecutionEngine/Orc/ObjectLinkingLayer.cpp' l='567' u='w' c='_ZN4llvm3orc25EHFrameRegistrationPluginC1ERNS0_16ExecutionSessionESt10unique_ptrINS_7jitlink16EHFrameRegistrarESt14default_deleteIS6_EE'/>
<use f='llvm/llvm/lib/ExecutionEngine/Orc/ObjectLinkingLayer.cpp' l='617' u='m' c='_ZN4llvm3orc25EHFrameRegistrationPlugin23notifyRemovingResourcesEm'/>
