<dec f='llvm/llvm/include/llvm/CodeGen/GlobalISel/GISelKnownBits.h' l='31' type='const llvm::TargetLowering &amp;'/>
<offset>704</offset>
<use f='llvm/llvm/lib/CodeGen/GlobalISel/GISelKnownBits.cpp' l='31' u='w' c='_ZN4llvm14GISelKnownBitsC1ERNS_15MachineFunctionEj'/>
<use f='llvm/llvm/lib/CodeGen/GlobalISel/GISelKnownBits.cpp' l='46' u='m' c='_ZN4llvm14GISelKnownBits21computeKnownAlignmentENS_8RegisterEj'/>
<use f='llvm/llvm/lib/CodeGen/GlobalISel/GISelKnownBits.cpp' l='164' u='m' c='_ZN4llvm14GISelKnownBits20computeKnownBitsImplENS_8RegisterERNS_9KnownBitsERKNS_5APIntEj'/>
<use f='llvm/llvm/lib/CodeGen/GlobalISel/GISelKnownBits.cpp' l='225' u='m' c='_ZN4llvm14GISelKnownBits20computeKnownBitsImplENS_8RegisterERNS_9KnownBitsERKNS_5APIntEj'/>
<use f='llvm/llvm/lib/CodeGen/GlobalISel/GISelKnownBits.cpp' l='335' u='m' c='_ZN4llvm14GISelKnownBits20computeKnownBitsImplENS_8RegisterERNS_9KnownBitsERKNS_5APIntEj'/>
<use f='llvm/llvm/lib/CodeGen/GlobalISel/GISelKnownBits.cpp' l='572' u='m' c='_ZN4llvm14GISelKnownBits18computeNumSignBitsENS_8RegisterERKNS_5APIntEj'/>
