<use f='llvm/llvm/include/llvm/ExecutionEngine/Orc/LLJIT.h' l='68' u='a' c='_ZNK4llvm3orc5LLJIT13getDataLayoutEv'/>
<dec f='llvm/llvm/include/llvm/ExecutionEngine/Orc/LLJIT.h' l='207' type='llvm::DataLayout'/>
<offset>192</offset>
<use f='llvm/llvm/lib/ExecutionEngine/Orc/LLJIT.cpp' l='1061' u='w' c='_ZN4llvm3orc5LLJITC1ERNS0_17LLJITBuilderStateERNS_5ErrorE'/>
<use f='llvm/llvm/lib/ExecutionEngine/Orc/LLJIT.cpp' l='1073' u='w' c='_ZN4llvm3orc5LLJITC1ERNS0_17LLJITBuilderStateERNS_5ErrorE'/>
<use f='llvm/llvm/lib/ExecutionEngine/Orc/LLJIT.cpp' l='1075' u='w' c='_ZN4llvm3orc5LLJITC1ERNS0_17LLJITBuilderStateERNS_5ErrorE'/>
<use f='llvm/llvm/lib/ExecutionEngine/Orc/LLJIT.cpp' l='1133' u='r' c='_ZNK4llvm3orc5LLJIT6mangleB5cxx11ENS_9StringRefE'/>
<use f='llvm/llvm/lib/ExecutionEngine/Orc/LLJIT.cpp' l='1140' u='r' c='_ZN4llvm3orc5LLJIT15applyDataLayoutERNS_6ModuleE'/>
<use f='llvm/llvm/lib/ExecutionEngine/Orc/LLJIT.cpp' l='1142' u='r' c='_ZN4llvm3orc5LLJIT15applyDataLayoutERNS_6ModuleE'/>
<use f='llvm/llvm/lib/ExecutionEngine/Orc/LLJIT.cpp' l='1146' u='m' c='_ZN4llvm3orc5LLJIT15applyDataLayoutERNS_6ModuleE'/>
