<dec f='llvm/llvm/lib/Transforms/Vectorize/VPRecipeBuilder.h' l='39' type='llvm::VPBuilder &amp;'/>
<use f='llvm/llvm/lib/Transforms/Vectorize/VPRecipeBuilder.h' l='100' u='w' c='_ZN4llvm15VPRecipeBuilderC1EPNS_4LoopEPKNS_17TargetLibraryInfoEPNS_25LoopVectorizationLegalityERNS_26LoopVectorizationCostModelERNS_25PredicatedScalar11179411'/>
<use f='llvm/llvm/lib/Transforms/Vectorize/LoopVectorize.cpp' l='8188' u='m' c='_ZN4llvm15VPRecipeBuilder14createEdgeMaskEPNS_10BasicBlockES2_RSt10unique_ptrINS_5VPlanESt14default_deleteIS4_EE'/>
<use f='llvm/llvm/lib/Transforms/Vectorize/LoopVectorize.cpp' l='8197' u='m' c='_ZN4llvm15VPRecipeBuilder14createEdgeMaskEPNS_10BasicBlockES2_RSt10unique_ptrINS_5VPlanESt14default_deleteIS4_EE'/>
<use f='llvm/llvm/lib/Transforms/Vectorize/LoopVectorize.cpp' l='8220' u='a' c='_ZN4llvm15VPRecipeBuilder17createBlockInMaskEPNS_10BasicBlockERSt10unique_ptrINS_5VPlanESt14default_deleteIS4_EE'/>
<use f='llvm/llvm/lib/Transforms/Vectorize/LoopVectorize.cpp' l='8221' u='m' c='_ZN4llvm15VPRecipeBuilder17createBlockInMaskEPNS_10BasicBlockERSt10unique_ptrINS_5VPlanESt14default_deleteIS4_EE'/>
<use f='llvm/llvm/lib/Transforms/Vectorize/LoopVectorize.cpp' l='8222' u='m' c='_ZN4llvm15VPRecipeBuilder17createBlockInMaskEPNS_10BasicBlockERSt10unique_ptrINS_5VPlanESt14default_deleteIS4_EE'/>
<use f='llvm/llvm/lib/Transforms/Vectorize/LoopVectorize.cpp' l='8222' u='m' c='_ZN4llvm15VPRecipeBuilder17createBlockInMaskEPNS_10BasicBlockERSt10unique_ptrINS_5VPlanESt14default_deleteIS4_EE'/>
<use f='llvm/llvm/lib/Transforms/Vectorize/LoopVectorize.cpp' l='8232' u='m' c='_ZN4llvm15VPRecipeBuilder17createBlockInMaskEPNS_10BasicBlockERSt10unique_ptrINS_5VPlanESt14default_deleteIS4_EE'/>
<use f='llvm/llvm/lib/Transforms/Vectorize/LoopVectorize.cpp' l='8243' u='m' c='_ZN4llvm15VPRecipeBuilder17createBlockInMaskEPNS_10BasicBlockERSt10unique_ptrINS_5VPlanESt14default_deleteIS4_EE'/>
<use f='llvm/llvm/lib/Transforms/Vectorize/LoopVectorize.cpp' l='8245' u='m' c='_ZN4llvm15VPRecipeBuilder17createBlockInMaskEPNS_10BasicBlockERSt10unique_ptrINS_5VPlanESt14default_deleteIS4_EE'/>
<use f='llvm/llvm/lib/Transforms/Vectorize/LoopVectorize.cpp' l='8261' u='m' c='_ZN4llvm15VPRecipeBuilder17createBlockInMaskEPNS_10BasicBlockERSt10unique_ptrINS_5VPlanESt14default_deleteIS4_EE'/>
<offset>320</offset>
