<dec f='llvm/llvm/include/llvm/IR/IRBuilder.h' l='390' type='llvm::IRBuilderBase &amp;'/>
<use f='llvm/llvm/include/llvm/IR/IRBuilder.h' l='399' u='w' c='_ZN4llvm13IRBuilderBase17FastMathFlagGuardC1ERS0_'/>
<use f='llvm/llvm/include/llvm/IR/IRBuilder.h' l='408' u='m' c='_ZN4llvm13IRBuilderBase17FastMathFlagGuardD1Ev'/>
<use f='llvm/llvm/include/llvm/IR/IRBuilder.h' l='409' u='m' c='_ZN4llvm13IRBuilderBase17FastMathFlagGuardD1Ev'/>
<use f='llvm/llvm/include/llvm/IR/IRBuilder.h' l='410' u='m' c='_ZN4llvm13IRBuilderBase17FastMathFlagGuardD1Ev'/>
<use f='llvm/llvm/include/llvm/IR/IRBuilder.h' l='411' u='m' c='_ZN4llvm13IRBuilderBase17FastMathFlagGuardD1Ev'/>
<use f='llvm/llvm/include/llvm/IR/IRBuilder.h' l='412' u='m' c='_ZN4llvm13IRBuilderBase17FastMathFlagGuardD1Ev'/>
<offset>0</offset>
