<dec f='llvm/llvm/include/llvm/Object/SymbolicFile.h' l='39' type='uintptr_t'/>
<use f='llvm/llvm/include/llvm/Object/SymbolicFile.h' l='46' u='r' c='_ZN4llvm6objectlsERT_RKNS0_11DataRefImplE'/>
<use f='llvm/llvm/include/llvm/Object/ObjectFile.h' l='581' u='w' c='_ZN4llvm12DenseMapInfoINS_6object10SectionRefEE15getTombstoneKeyEv'/>
<use f='llvm/llvm/include/llvm/Object/ObjectFile.h' l='586' u='r' c='_ZN4llvm12DenseMapInfoINS_6object10SectionRefEE12getHashValueERKS2_'/>
<offset>0</offset>
<use f='llvm/llvm/include/llvm/Object/ELFObjectFile.h' l='337' u='r' c='_ZNK4llvm6object13ELFObjectFile13toELFShdrIterENS0_11DataRefImplE'/>
<use f='llvm/llvm/include/llvm/Object/ELFObjectFile.h' l='342' u='w' c='_ZNK4llvm6object13ELFObjectFile5toDRIEPKNT_4ShdrE'/>
<use f='llvm/llvm/include/llvm/Object/ELFObjectFile.h' l='348' u='w' c='_ZNK4llvm6object13ELFObjectFile5toDRIEPKNT_3DynE'/>
<use f='llvm/llvm/include/llvm/Object/ELFObjectFile.h' l='415' u='r' c='_ZNK4llvm6object13ELFObjectFile10getSectionENS0_11DataRefImplE'/>
<use f='llvm/llvm/include/llvm/Object/ELFObjectFile.h' l='771' u='w' c='_ZNK4llvm6object13ELFObjectFile16getSymbolSectionEPKNT_3SymEPKNS2_4ShdrE'/>
<use f='llvm/llvm/include/llvm/Object/ELFObjectFile.h' l='926' u='r' c='_ZNK4llvm6object13ELFObjectFile17section_rel_beginENS0_11DataRefImplE'/>
<use f='llvm/llvm/include/llvm/Object/ELFObjectFile.h' l='934' u='r' c='_ZNK4llvm6object13ELFObjectFile15section_rel_endENS0_11DataRefImplE'/>
<use f='llvm/llvm/include/llvm/Object/MachO.h' l='696' u='r' c='_ZN4llvm6object7DiceRef8moveNextEv'/>
<use f='llvm/llvm/include/llvm/Object/MachO.h' l='697' u='w' c='_ZN4llvm6object7DiceRef8moveNextEv'/>
<use f='llvm/lld/COFF/Chunks.cpp' l='678' u='w' c='_ZNK3lld4coff12SectionChunk16getSectionNumberEv'/>
<use f='llvm/llvm/include/llvm/Object/COFFImportFile.h' l='37' u='w' c='_ZNK4llvm6object14COFFImportFile14moveSymbolNextERNS0_11DataRefImplE'/>
<use f='llvm/llvm/include/llvm/Object/COFFImportFile.h' l='40' u='r' c='_ZNK4llvm6object14COFFImportFile15printSymbolNameERNS_11raw_ostreamENS0_11DataRefImplE'/>
<use f='llvm/llvm/include/llvm/Object/COFFImportFile.h' l='56' u='w' c='_ZNK4llvm6object14COFFImportFile10symbol_endEv'/>
<use f='llvm/lld/ELF/DWARF.cpp' l='130' u='w' c='_ZNK3lld3elf11LLDDwarfObj7findAuxERKNS0_16InputSectionBaseEmN4llvm8ArrayRefITL0__EE'/>
<use f='llvm/llvm/lib/ExecutionEngine/RuntimeDyld/RuntimeDyldELF.cpp' l='109' u='r' c='_ZN12_GLOBAL__N_113DyldELFObject20updateSectionAddressERKN4llvm6object10SectionRefEm'/>
<use f='llvm/llvm/lib/ExecutionEngine/RuntimeDyld/RuntimeDyldELF.cpp' l='165' u='r' c='_ZN12_GLOBAL__N_121createRTDyldELFObjectEN4llvm15MemoryBufferRefERKNS0_6object10ObjectFileERKNS_19LoadedELFObjectInfoE'/>
<use f='llvm/llvm/lib/Object/COFFObjectFile.cpp' l='104' u='r' c='_ZNK4llvm6object14COFFObjectFile6toSymbENS0_11DataRefImplE'/>
<use f='llvm/llvm/lib/Object/COFFObjectFile.cpp' l='120' u='r' c='_ZNK4llvm6object14COFFObjectFile5toSecENS0_11DataRefImplE'/>
<use f='llvm/llvm/lib/Object/COFFObjectFile.cpp' l='141' u='w' c='_ZNK4llvm6object14COFFObjectFile14moveSymbolNextERNS0_11DataRefImplE'/>
<use f='llvm/llvm/lib/Object/COFFObjectFile.cpp' l='145' u='w' c='_ZNK4llvm6object14COFFObjectFile14moveSymbolNextERNS0_11DataRefImplE'/>
<use f='llvm/llvm/lib/Object/COFFObjectFile.cpp' l='255' u='w' c='_ZNK4llvm6object14COFFObjectFile16getSymbolSectionENS0_11DataRefImplE'/>
<use f='llvm/llvm/lib/Object/COFFObjectFile.cpp' l='267' u='w' c='_ZNK4llvm6object14COFFObjectFile15moveSectionNextERNS0_11DataRefImplE'/>
<use f='llvm/llvm/lib/Object/COFFObjectFile.cpp' l='337' u='r' c='_ZNK4llvm6object14COFFObjectFile12getSectionIDENS0_10SectionRefE'/>
<use f='llvm/llvm/lib/Object/COFFObjectFile.cpp' l='395' u='w' c='_ZNK4llvm6object14COFFObjectFile17section_rel_beginENS0_11DataRefImplE'/>
<use f='llvm/llvm/lib/Object/COFFObjectFile.cpp' l='405' u='w' c='_ZNK4llvm6object14COFFObjectFile15section_rel_endENS0_11DataRefImplE'/>
<use f='llvm/llvm/lib/Object/COFFObjectFile.cpp' l='864' u='w' c='_ZNK4llvm6object14COFFObjectFile12symbol_beginEv'/>
<use f='llvm/llvm/lib/Object/COFFObjectFile.cpp' l='871' u='w' c='_ZNK4llvm6object14COFFObjectFile10symbol_endEv'/>
<use f='llvm/llvm/lib/Object/COFFObjectFile.cpp' l='917' u='w' c='_ZNK4llvm6object14COFFObjectFile13section_beginEv'/>
<use f='llvm/llvm/lib/Object/COFFObjectFile.cpp' l='925' u='w' c='_ZNK4llvm6object14COFFObjectFile11section_endEv'/>
<use f='llvm/llvm/lib/Object/COFFObjectFile.cpp' l='1143' u='r' c='_ZNK4llvm6object14COFFObjectFile5toRelENS0_11DataRefImplE'/>
<use f='llvm/llvm/lib/Object/COFFObjectFile.cpp' l='1147' u='w' c='_ZNK4llvm6object14COFFObjectFile18moveRelocationNextERNS0_11DataRefImplE'/>
<use f='llvm/llvm/lib/Object/COFFObjectFile.cpp' l='1148' u='r' c='_ZNK4llvm6object14COFFObjectFile18moveRelocationNextERNS0_11DataRefImplE'/>
<use f='llvm/llvm/lib/Object/COFFObjectFile.cpp' l='1162' u='w' c='_ZNK4llvm6object14COFFObjectFile19getRelocationSymbolENS0_11DataRefImplE'/>
<use f='llvm/llvm/lib/Object/COFFObjectFile.cpp' l='1164' u='w' c='_ZNK4llvm6object14COFFObjectFile19getRelocationSymbolENS0_11DataRefImplE'/>
<use f='llvm/llvm/lib/Object/IRObjectFile.cpp' l='38' u='r' c='_ZL6getSymB5cxx11RN4llvm6object11DataRefImplE'/>
<use f='llvm/llvm/lib/Object/IRObjectFile.cpp' l='42' u='w' c='_ZNK4llvm6object12IRObjectFile14moveSymbolNextERNS0_11DataRefImplE'/>
<use f='llvm/llvm/lib/Object/IRObjectFile.cpp' l='56' u='w' c='_ZNK4llvm6object12IRObjectFile12symbol_beginEv'/>
<use f='llvm/llvm/lib/Object/IRObjectFile.cpp' l='62' u='w' c='_ZNK4llvm6object12IRObjectFile10symbol_endEv'/>
<use f='llvm/llvm/lib/Object/MachOObjectFile.cpp' l='115' u='r' c='_ZL23getSymbolTableEntryBaseRKN4llvm6object15MachOObjectFileENS0_11DataRefImplE'/>
<use f='llvm/llvm/lib/Object/MachOObjectFile.cpp' l='1752' u='w' c='_ZNK4llvm6object15MachOObjectFile14moveSymbolNextERNS0_11DataRefImplE'/>
<use f='llvm/llvm/lib/Object/MachOObjectFile.cpp' l='2154' u='w' c='_ZNK4llvm6object15MachOObjectFile19getRelocationSymbolENS0_11DataRefImplE'/>
<use f='llvm/llvm/lib/Object/MachOObjectFile.cpp' l='2510' u='w' c='_ZNK4llvm6object15MachOObjectFile10symbol_endEv'/>
<use f='llvm/llvm/lib/Object/MachOObjectFile.cpp' l='2521' u='w' c='_ZNK4llvm6object15MachOObjectFile16getSymbolByIndexEj'/>
<use f='llvm/llvm/lib/Object/MachOObjectFile.cpp' l='2522' u='w' c='_ZNK4llvm6object15MachOObjectFile16getSymbolByIndexEj'/>
<use f='llvm/llvm/lib/Object/MachOObjectFile.cpp' l='2533' u='w' c='_ZNK4llvm6object15MachOObjectFile14getSymbolIndexENS0_11DataRefImplE'/>
<use f='llvm/llvm/lib/Object/MachOObjectFile.cpp' l='2534' u='r' c='_ZNK4llvm6object15MachOObjectFile14getSymbolIndexENS0_11DataRefImplE'/>
<use f='llvm/llvm/lib/Object/MachOObjectFile.cpp' l='2534' u='r' c='_ZNK4llvm6object15MachOObjectFile14getSymbolIndexENS0_11DataRefImplE'/>
<use f='llvm/llvm/lib/Object/MachOObjectFile.cpp' l='2800' u='w' c='_ZNK4llvm6object15MachOObjectFile11begin_dicesEv'/>
<use f='llvm/llvm/lib/Object/MachOObjectFile.cpp' l='2811' u='w' c='_ZNK4llvm6object15MachOObjectFile9end_dicesEv'/>
<use f='llvm/llvm/lib/Object/MachOObjectFile.cpp' l='4285' u='r' c='_ZNK4llvm6object15MachOObjectFile19getSymbolTableEntryENS0_11DataRefImplE'/>
<use f='llvm/llvm/lib/Object/MachOObjectFile.cpp' l='4291' u='r' c='_ZNK4llvm6object15MachOObjectFile21getSymbol64TableEntryENS0_11DataRefImplE'/>
<use f='llvm/llvm/lib/Object/MachOObjectFile.cpp' l='4444' u='r' c='_ZNK4llvm6object15MachOObjectFile7getDiceENS0_11DataRefImplE'/>
<use f='llvm/llvm/lib/Object/RelocationResolver.cpp' l='759' u='r' c='_ZN4llvm6object17resolveRelocationEPFmmmmmlERKNS0_13RelocationRefEmm'/>
<use f='llvm/llvm/lib/Object/XCOFFObjectFile.cpp' l='105' u='r' c='_ZNK4llvm6object15XCOFFObjectFile11toSection32ENS0_11DataRefImplE'/>
<use f='llvm/llvm/lib/Object/XCOFFObjectFile.cpp' l='114' u='r' c='_ZNK4llvm6object15XCOFFObjectFile11toSection64ENS0_11DataRefImplE'/>
<use f='llvm/llvm/lib/Object/XCOFFObjectFile.cpp' l='123' u='r' c='_ZNK4llvm6object15XCOFFObjectFile13toSymbolEntryENS0_11DataRefImplE'/>
<use f='llvm/llvm/lib/Object/XCOFFObjectFile.cpp' l='158' u='w' c='_ZNK4llvm6object15XCOFFObjectFile14moveSymbolNextERNS0_11DataRefImplE'/>
<use f='llvm/llvm/lib/Object/XCOFFObjectFile.cpp' l='238' u='r' c='_ZNK4llvm6object15XCOFFObjectFile15moveSectionNextERNS0_11DataRefImplE'/>
<use f='llvm/llvm/lib/Object/XCOFFObjectFile.cpp' l='239' u='w' c='_ZNK4llvm6object15XCOFFObjectFile15moveSectionNextERNS0_11DataRefImplE'/>
<use f='llvm/llvm/lib/Object/XCOFFObjectFile.cpp' l='331' u='w' c='_ZNK4llvm6object15XCOFFObjectFile17section_rel_beginENS0_11DataRefImplE'/>
<use f='llvm/llvm/lib/Object/XCOFFObjectFile.cpp' l='343' u='w' c='_ZNK4llvm6object15XCOFFObjectFile15section_rel_endENS0_11DataRefImplE'/>
<use f='llvm/llvm/lib/Object/XCOFFObjectFile.cpp' l='348' u='w' c='_ZNK4llvm6object15XCOFFObjectFile18moveRelocationNextERNS0_11DataRefImplE'/>
<use f='llvm/llvm/lib/Object/XCOFFObjectFile.cpp' l='348' u='r' c='_ZNK4llvm6object15XCOFFObjectFile18moveRelocationNextERNS0_11DataRefImplE'/>
<use f='llvm/llvm/lib/Object/XCOFFObjectFile.cpp' l='354' u='r' c='_ZNK4llvm6object15XCOFFObjectFile19getRelocationOffsetENS0_11DataRefImplE'/>
<use f='llvm/llvm/lib/Object/XCOFFObjectFile.cpp' l='373' u='r' c='_ZNK4llvm6object15XCOFFObjectFile19getRelocationSymbolENS0_11DataRefImplE'/>
<use f='llvm/llvm/lib/Object/XCOFFObjectFile.cpp' l='380' u='w' c='_ZNK4llvm6object15XCOFFObjectFile19getRelocationSymbolENS0_11DataRefImplE'/>
<use f='llvm/llvm/lib/Object/XCOFFObjectFile.cpp' l='387' u='r' c='_ZNK4llvm6object15XCOFFObjectFile17getRelocationTypeENS0_11DataRefImplE'/>
<use f='llvm/llvm/lib/Object/XCOFFObjectFile.cpp' l='394' u='r' c='_ZNK4llvm6object15XCOFFObjectFile21getRelocationTypeNameENS0_11DataRefImplERNS_15SmallVectorImplIcEE'/>
<use f='llvm/llvm/lib/Object/XCOFFObjectFile.cpp' l='409' u='w' c='_ZNK4llvm6object15XCOFFObjectFile12symbol_beginEv'/>
<use f='llvm/llvm/lib/Object/XCOFFObjectFile.cpp' l='417' u='w' c='_ZNK4llvm6object15XCOFFObjectFile10symbol_endEv'/>
<use f='llvm/llvm/lib/Object/XCOFFObjectFile.cpp' l='424' u='w' c='_ZNK4llvm6object15XCOFFObjectFile13section_beginEv'/>
<use f='llvm/llvm/lib/Object/XCOFFObjectFile.cpp' l='430' u='w' c='_ZNK4llvm6object15XCOFFObjectFile11section_endEv'/>
<use f='llvm/llvm/lib/Object/XCOFFObjectFile.cpp' l='483' u='w' c='_ZNK4llvm6object15XCOFFObjectFile15getSectionByNumEs'/>
<use f='llvm/llvm/lib/Object/XCOFFObjectFile.cpp' l='590' u='w' c='_ZNK4llvm6object15XCOFFObjectFile20getSymbolNameByIndexEj'/>
<use f='llvm/llvm/lib/Object/XCOFFObjectFile.cpp' l='786' u='r' c='_ZNK4llvm6object14XCOFFSymbolRef21getXCOFFCsectAuxEnt32Ev'/>
<use f='llvm/llvm/tools/llvm-nm/llvm-nm.cpp' l='319' u='r' c='_ZL20compareSymbolAddressRKN12_GLOBAL__N_18NMSymbolES2_'/>
<use f='llvm/llvm/tools/llvm-nm/llvm-nm.cpp' l='327' u='r' c='_ZL20compareSymbolAddressRKN12_GLOBAL__N_18NMSymbolES2_'/>
<use f='llvm/llvm/tools/llvm-nm/llvm-nm.cpp' l='413' u='r' c='_ZL17darwinPrintSymbolRN4llvm6object12SymbolicFileERKN12_GLOBAL__N_18NMSymbolEPcPKcS9_S9_'/>
<use f='llvm/llvm/tools/llvm-nm/llvm-nm.cpp' l='431' u='r' c='_ZL17darwinPrintSymbolRN4llvm6object12SymbolicFileERKN12_GLOBAL__N_18NMSymbolEPcPKcS9_S9_'/>
<use f='llvm/llvm/tools/llvm-nm/llvm-nm.cpp' l='457' u='r' c='_ZL17darwinPrintSymbolRN4llvm6object12SymbolicFileERKN12_GLOBAL__N_18NMSymbolEPcPKcS9_S9_'/>
<use f='llvm/llvm/tools/llvm-nm/llvm-nm.cpp' l='522' u='r' c='_ZL17darwinPrintSymbolRN4llvm6object12SymbolicFileERKN12_GLOBAL__N_18NMSymbolEPcPKcS9_S9_'/>
<use f='llvm/llvm/tools/llvm-nm/llvm-nm.cpp' l='596' u='r' c='_ZL17darwinPrintSymbolRN4llvm6object12SymbolicFileERKN12_GLOBAL__N_18NMSymbolEPcPKcS9_S9_'/>
<use f='llvm/llvm/tools/llvm-nm/llvm-nm.cpp' l='824' u='r' c='_ZL22sortAndPrintSymbolListRN4llvm6object12SymbolicFileEbNS_9StringRefES3_'/>
<use f='llvm/llvm/tools/llvm-nm/llvm-nm.cpp' l='899' u='r' c='_ZL22sortAndPrintSymbolListRN4llvm6object12SymbolicFileEbNS_9StringRefES3_'/>
<use f='llvm/llvm/tools/llvm-objdump/llvm-objdump.cpp' l='1582' u='r' c='_ZN4llvm7objdump16createSymbolInfoEPKNS_6object10ObjectFileERKNS1_9SymbolRefE'/>
<use f='llvm/llvm/unittests/Object/SymbolicFileTest.cpp' l='22' u='r' c='_ZN30Object_DataRefImplOstream_Test8TestBodyEv'/>
<use f='llvm/llvm/unittests/Object/SymbolicFileTest.cpp' l='23' u='r' c='_ZN30Object_DataRefImplOstream_Test8TestBodyEv'/>
<use f='llvm/llvm/unittests/Object/SymbolicFileTest.cpp' l='28' u='r' c='_ZN30Object_DataRefImplOstream_Test8TestBodyEv'/>
