<dec f='llvm/llvm/lib/Target/NVPTX/NVPTXISelDAGToDAG.h' l='28' type='const llvm::NVPTXTargetMachine &amp;'/>
<use f='llvm/llvm/lib/Target/NVPTX/NVPTXISelDAGToDAG.cpp' l='40' u='w' c='_ZN4llvm17NVPTXDAGToDAGISelC1ERNS_18NVPTXTargetMachineENS_10CodeGenOpt5LevelE'/>
<use f='llvm/llvm/lib/Target/NVPTX/NVPTXISelDAGToDAG.cpp' l='72' u='m' c='_ZNK4llvm17NVPTXDAGToDAGISel16useShortPointersEv'/>
<use f='llvm/llvm/lib/Target/NVPTX/NVPTXISelDAGToDAG.cpp' l='751' u='m' c='_ZN4llvm17NVPTXDAGToDAGISel19SelectAddrSpaceCastEPNS_6SDNodeE'/>
<use f='llvm/llvm/lib/Target/NVPTX/NVPTXISelDAGToDAG.cpp' l='754' u='m' c='_ZN4llvm17NVPTXDAGToDAGISel19SelectAddrSpaceCastEPNS_6SDNodeE'/>
<use f='llvm/llvm/lib/Target/NVPTX/NVPTXISelDAGToDAG.cpp' l='759' u='m' c='_ZN4llvm17NVPTXDAGToDAGISel19SelectAddrSpaceCastEPNS_6SDNodeE'/>
<use f='llvm/llvm/lib/Target/NVPTX/NVPTXISelDAGToDAG.cpp' l='764' u='m' c='_ZN4llvm17NVPTXDAGToDAGISel19SelectAddrSpaceCastEPNS_6SDNodeE'/>
<use f='llvm/llvm/lib/Target/NVPTX/NVPTXISelDAGToDAG.cpp' l='780' u='m' c='_ZN4llvm17NVPTXDAGToDAGISel19SelectAddrSpaceCastEPNS_6SDNodeE'/>
<use f='llvm/llvm/lib/Target/NVPTX/NVPTXISelDAGToDAG.cpp' l='784' u='m' c='_ZN4llvm17NVPTXDAGToDAGISel19SelectAddrSpaceCastEPNS_6SDNodeE'/>
<use f='llvm/llvm/lib/Target/NVPTX/NVPTXISelDAGToDAG.cpp' l='789' u='m' c='_ZN4llvm17NVPTXDAGToDAGISel19SelectAddrSpaceCastEPNS_6SDNodeE'/>
<use f='llvm/llvm/lib/Target/NVPTX/NVPTXISelDAGToDAG.cpp' l='794' u='m' c='_ZN4llvm17NVPTXDAGToDAGISel19SelectAddrSpaceCastEPNS_6SDNodeE'/>
<use f='llvm/llvm/lib/Target/NVPTX/NVPTXISelDAGToDAG.cpp' l='799' u='m' c='_ZN4llvm17NVPTXDAGToDAGISel19SelectAddrSpaceCastEPNS_6SDNodeE'/>
<use f='llvm/llvm/lib/Target/NVPTX/NVPTXISelDAGToDAG.cpp' l='1365' u='m' c='_ZN4llvm17NVPTXDAGToDAGISel9tryLDGLDUEPNS_6SDNodeE'/>
<use f='llvm/llvm/lib/Target/NVPTX/NVPTXISelDAGToDAG.cpp' l='1367' u='m' c='_ZN4llvm17NVPTXDAGToDAGISel9tryLDGLDUEPNS_6SDNodeE'/>
<use f='llvm/llvm/lib/Target/NVPTX/NVPTXISelDAGToDAG.cpp' l='1513' u='m' c='_ZN4llvm17NVPTXDAGToDAGISel9tryLDGLDUEPNS_6SDNodeE'/>
<offset>2560</offset>
