<dec f='llvm/build/lib/Target/Sparc/SparcGenRegisterInfo.inc' l='44' type='24'/>
<use f='llvm/llvm/lib/Target/Sparc/AsmParser/SparcAsmParser.cpp' l='172'/>
<use f='llvm/llvm/lib/Target/Sparc/AsmParser/SparcAsmParser.cpp' l='1129' u='r' c='_ZN12_GLOBAL__N_114SparcAsmParser17matchRegisterNameERKN4llvm8AsmTokenERjS5_'/>
<use f='llvm/build/lib/Target/Sparc/SparcGenAsmMatcher.inc' l='2090' c='_ZL20validateOperandClassRN4llvm18MCParsedAsmOperandEN12_GLOBAL__N_114MatchClassKindE'/>
<use f='llvm/llvm/lib/Target/Sparc/Disassembler/SparcDisassembler.cpp' l='104'/>
<use f='llvm/llvm/lib/Target/Sparc/SparcISelDAGToDAG.cpp' l='359' u='r' c='_ZN12_GLOBAL__N_117SparcDAGToDAGISel6SelectEPN4llvm6SDNodeE'/>
