<use f='llvm/llvm/include/llvm/ExecutionEngine/Orc/IRCompileLayer.h' l='34' u='w' c='_ZN4llvm3orc14IRCompileLayer10IRCompilerC1ENS0_14IRSymbolMapper15ManglingOptionsE'/>
<use f='llvm/llvm/include/llvm/ExecutionEngine/Orc/IRCompileLayer.h' l='37' u='a' c='_ZNK4llvm3orc14IRCompileLayer10IRCompiler18getManglingOptionsEv'/>
<use f='llvm/llvm/include/llvm/ExecutionEngine/Orc/IRCompileLayer.h' l='42' u='a' c='_ZN4llvm3orc14IRCompileLayer10IRCompiler15manglingOptionsEv'/>
<dec f='llvm/llvm/include/llvm/ExecutionEngine/Orc/IRCompileLayer.h' l='45' type='IRSymbolMapper::ManglingOptions'/>
<offset>64</offset>
