<dec f='llvm/build/lib/Target/ARM/ARMGenRegisterInfo.inc' l='94' type='74'/>
<use f='llvm/llvm/lib/Target/ARM/MCTargetDesc/ARMBaseInfo.h' l='163' c='_ZN4llvmL16isARMLowRegisterEj'/>
<use f='llvm/llvm/lib/Target/ARM/ARMBaseRegisterInfo.h' l='50' c='_ZN4llvmL18isARMArea1RegisterEjb'/>
<use f='llvm/llvm/lib/Target/ARM/ARMCallingConv.cpp' l='24' u='r' c='_ZL13f64AssignAPCSjN4llvm3MVTES0_NS_11CCValAssign7LocInfoERNS_7CCStateEb'/>
<use f='llvm/llvm/lib/Target/ARM/ARMCallingConv.cpp' l='65' u='r' c='_ZL14f64AssignAAPCSjN4llvm3MVTES0_NS_11CCValAssign7LocInfoERNS_7CCStateEb'/>
<use f='llvm/llvm/lib/Target/ARM/ARMCallingConv.cpp' l='68' u='r' c='_ZL14f64AssignAAPCSjN4llvm3MVTES0_NS_11CCValAssign7LocInfoERNS_7CCStateEb'/>
<use f='llvm/llvm/lib/Target/ARM/ARMCallingConv.cpp' l='116' u='r' c='_ZL12f64RetAssignjN4llvm3MVTES0_NS_11CCValAssign7LocInfoERNS_7CCStateE'/>
<use f='llvm/llvm/lib/Target/ARM/ARMCallingConv.cpp' l='153'/>
<use f='llvm/build/lib/Target/ARM/ARMGenCallingConv.inc' l='146' u='r' c='_ZL19CC_ARM_AAPCS_CommonjN4llvm3MVTES0_NS_11CCValAssign7LocInfoENS_3ISD10ArgFlagsTyERNS_7CCStateE'/>
<use f='llvm/build/lib/Target/ARM/ARMGenCallingConv.inc' l='161' u='r' c='_ZL19CC_ARM_AAPCS_CommonjN4llvm3MVTES0_NS_11CCValAssign7LocInfoENS_3ISD10ArgFlagsTyERNS_7CCStateE'/>
<use f='llvm/build/lib/Target/ARM/ARMGenCallingConv.inc' l='173' u='r' c='_ZL19CC_ARM_AAPCS_CommonjN4llvm3MVTES0_NS_11CCValAssign7LocInfoENS_3ISD10ArgFlagsTyERNS_7CCStateE'/>
<use f='llvm/build/lib/Target/ARM/ARMGenCallingConv.inc' l='183' u='r' c='_ZL19CC_ARM_AAPCS_CommonjN4llvm3MVTES0_NS_11CCValAssign7LocInfoENS_3ISD10ArgFlagsTyERNS_7CCStateE'/>
<use f='llvm/build/lib/Target/ARM/ARMGenCallingConv.inc' l='405' u='r' c='_ZN4llvm11CC_ARM_APCSEjNS_3MVTES0_NS_11CCValAssign7LocInfoENS_3ISD10ArgFlagsTyERNS_7CCStateE'/>
<use f='llvm/build/lib/Target/ARM/ARMGenCallingConv.inc' l='707' u='r' c='_ZL22RetCC_ARM_AAPCS_CommonjN4llvm3MVTES0_NS_11CCValAssign7LocInfoENS_3ISD10ArgFlagsTyERNS_7CCStateE'/>
<use f='llvm/build/lib/Target/ARM/ARMGenCallingConv.inc' l='717' u='r' c='_ZL22RetCC_ARM_AAPCS_CommonjN4llvm3MVTES0_NS_11CCValAssign7LocInfoENS_3ISD10ArgFlagsTyERNS_7CCStateE'/>
<use f='llvm/build/lib/Target/ARM/ARMGenCallingConv.inc' l='888' u='r' c='_ZN4llvm14RetCC_ARM_APCSEjNS_3MVTES0_NS_11CCValAssign7LocInfoENS_3ISD10ArgFlagsTyERNS_7CCStateE'/>
<use f='llvm/build/lib/Target/ARM/ARMGenCallingConv.inc' l='898' u='r' c='_ZN4llvm14RetCC_ARM_APCSEjNS_3MVTES0_NS_11CCValAssign7LocInfoENS_3ISD10ArgFlagsTyERNS_7CCStateE'/>
<use f='llvm/llvm/lib/Target/ARM/ARMExpandPseudoInsts.cpp' l='2007' u='r' c='_ZN12_GLOBAL__N_115ARMExpandPseudo8ExpandMIERN4llvm17MachineBasicBlockENS1_26MachineInstrBundleIteratorINS1_12MachineInstrELb0EEERS6_'/>
<use f='llvm/llvm/lib/Target/ARM/ARMExpandPseudoInsts.cpp' l='2040' u='r' c='_ZN12_GLOBAL__N_115ARMExpandPseudo8ExpandMIERN4llvm17MachineBasicBlockENS1_26MachineInstrBundleIteratorINS1_12MachineInstrELb0EEERS6_'/>
<use f='llvm/llvm/lib/Target/ARM/ARMFastISel.cpp' l='3056' u='r' c='_ZN12_GLOBAL__N_111ARMFastISel18fastLowerArgumentsEv'/>
<use f='llvm/llvm/lib/Target/ARM/ARMFrameLowering.cpp' l='412' c='_ZNK4llvm16ARMFrameLowering12emitPrologueERNS_15MachineFunctionERNS_17MachineBasicBlockE'/>
<use f='llvm/llvm/lib/Target/ARM/ARMFrameLowering.cpp' l='632' c='_ZNK4llvm16ARMFrameLowering12emitPrologueERNS_15MachineFunctionERNS_17MachineBasicBlockE'/>
<use f='llvm/llvm/lib/Target/ARM/ARMFrameLowering.cpp' l='1770' c='_ZNK4llvm16ARMFrameLowering20determineCalleeSavesERNS_15MachineFunctionERNS_9BitVectorEPNS_12RegScavengerE'/>
<use f='llvm/llvm/lib/Target/ARM/ARMFrameLowering.cpp' l='1786' c='_ZNK4llvm16ARMFrameLowering20determineCalleeSavesERNS_15MachineFunctionERNS_9BitVectorEPNS_12RegScavengerE'/>
<use f='llvm/llvm/lib/Target/ARM/ARMFrameLowering.cpp' l='1952' c='_ZNK4llvm16ARMFrameLowering20determineCalleeSavesERNS_15MachineFunctionERNS_9BitVectorEPNS_12RegScavengerE'/>
<use f='llvm/llvm/lib/Target/ARM/ARMISelLowering.cpp' l='153'/>
<use f='llvm/llvm/lib/Target/ARM/ARMSLSHardening.cpp' l='136'/>
<use f='llvm/llvm/lib/Target/ARM/ARMSLSHardening.cpp' l='150'/>
<use f='llvm/llvm/lib/Target/ARM/AsmParser/ARMAsmParser.cpp' l='3979' u='r' c='_ZN12_GLOBAL__N_112ARMAsmParser16tryParseRegisterEv'/>
<use f='llvm/llvm/lib/Target/ARM/AsmParser/ARMAsmParser.cpp' l='4323' u='r' c='_ZL15getNextRegisterj'/>
<use f='llvm/llvm/lib/Target/ARM/AsmParser/ARMAsmParser.cpp' l='4324' c='_ZL15getNextRegisterj'/>
<use f='llvm/llvm/lib/Target/ARM/AsmParser/ARMAsmParser.cpp' l='6897' c='_ZN12_GLOBAL__N_112ARMAsmParser24CDEConvertDualRegOperandEN4llvm9StringRefERNS1_15SmallVectorImplISt10unique_ptrINS1_18MCParsedAsmOperandESt14default_deleteIS5_EEEE'/>
<use f='llvm/build/lib/Target/ARM/ARMGenAsmMatcher.inc' l='9380' c='_ZL20validateOperandClassRN4llvm18MCParsedAsmOperandEN12_GLOBAL__N_114MatchClassKindE'/>
<use f='llvm/llvm/lib/Target/ARM/Disassembler/ARMDisassembler.cpp' l='1120'/>
<use f='llvm/llvm/lib/Target/ARM/Disassembler/ARMDisassembler.cpp' l='1127'/>
<use f='llvm/llvm/lib/Target/ARM/Disassembler/ARMDisassembler.cpp' l='1277' u='r' c='_ZL24DecodetcGPRRegisterClassRN4llvm6MCInstEjmPKv'/>
<use f='llvm/llvm/lib/Target/ARM/MCTargetDesc/ARMMCTargetDesc.cpp' l='229' u='r' c='_ZN4llvm6ARM_MC22initLLVMToCVRegMappingEPNS_14MCRegisterInfoE'/>
<use f='llvm/llvm/lib/Target/ARM/Thumb1FrameLowering.cpp' l='284' c='_ZNK4llvm19Thumb1FrameLowering12emitPrologueERNS_15MachineFunctionERNS_17MachineBasicBlockE'/>
<use f='llvm/llvm/lib/Target/ARM/Thumb1FrameLowering.cpp' l='844' c='_ZNK4llvm19Thumb1FrameLowering25spillCalleeSavedRegistersERNS_17MachineBasicBlockENS_26MachineInstrBundleIteratorINS_12MachineInstrELb0EEENS_8ArrayRef10067070'/>
<use f='llvm/llvm/lib/Target/ARM/Thumb1FrameLowering.cpp' l='876' u='r' c='_ZNK4llvm19Thumb1FrameLowering25spillCalleeSavedRegistersERNS_17MachineBasicBlockENS_26MachineInstrBundleIteratorINS_12MachineInstrELb0EEENS_8ArrayRef10067070'/>
<use f='llvm/llvm/lib/Target/ARM/Thumb1FrameLowering.cpp' l='974' u='r' c='_ZNK4llvm19Thumb1FrameLowering27restoreCalleeSavedRegistersERNS_17MachineBasicBlockENS_26MachineInstrBundleIteratorINS_12MachineInstrELb0EEENS_15Mutab11398323'/>
<use f='llvm/llvm/lib/Target/ARM/Thumb1FrameLowering.cpp' l='982' u='r' c='_ZNK4llvm19Thumb1FrameLowering27restoreCalleeSavedRegistersERNS_17MachineBasicBlockENS_26MachineInstrBundleIteratorINS_12MachineInstrELb0EEENS_15Mutab11398323'/>
