<dec f='llvm/llvm/lib/Target/AArch64/AArch64TargetTransformInfo.h' l='47' type='const llvm::AArch64Subtarget *'/>
<use f='llvm/llvm/lib/Target/AArch64/AArch64TargetTransformInfo.h' l='50' u='r' c='_ZNK4llvm14AArch64TTIImpl5getSTEv'/>
<use f='llvm/llvm/lib/Target/AArch64/AArch64TargetTransformInfo.h' l='64' u='w' c='_ZN4llvm14AArch64TTIImplC1EPKNS_20AArch64TargetMachineERKNS_8FunctionE'/>
<use f='llvm/llvm/lib/Target/AArch64/AArch64TargetTransformInfo.h' l='65' u='r' c='_ZN4llvm14AArch64TTIImplC1EPKNS_20AArch64TargetMachineERKNS_8FunctionE'/>
<use f='llvm/llvm/lib/Target/AArch64/AArch64TargetTransformInfo.h' l='93' u='r' c='_ZNK4llvm14AArch64TTIImpl20getNumberOfRegistersEj'/>
<use f='llvm/llvm/lib/Target/AArch64/AArch64TargetTransformInfo.h' l='105' u='r' c='_ZNK4llvm14AArch64TTIImpl19getRegisterBitWidthEb'/>
<use f='llvm/llvm/lib/Target/AArch64/AArch64TargetTransformInfo.h' l='106' u='r' c='_ZNK4llvm14AArch64TTIImpl19getRegisterBitWidthEb'/>
<use f='llvm/llvm/lib/Target/AArch64/AArch64TargetTransformInfo.h' l='107' u='r' c='_ZNK4llvm14AArch64TTIImpl19getRegisterBitWidthEb'/>
<use f='llvm/llvm/lib/Target/AArch64/AArch64TargetTransformInfo.h' l='115' u='r' c='_ZN4llvm14AArch64TTIImpl28getMinVectorRegisterBitWidthEv'/>
<use f='llvm/llvm/lib/Target/AArch64/AArch64TargetTransformInfo.h' l='119' u='r' c='_ZNK4llvm14AArch64TTIImpl12getMaxVScaleEv'/>
<use f='llvm/llvm/lib/Target/AArch64/AArch64TargetTransformInfo.h' l='190' u='r' c='_ZN4llvm14AArch64TTIImpl22isLegalMaskedLoadStoreEPNS_4TypeENS_5AlignE'/>
<use f='llvm/llvm/lib/Target/AArch64/AArch64TargetTransformInfo.h' l='250' u='r' c='_ZNK4llvm14AArch64TTIImpl23supportsScalableVectorsEv'/>
<offset>128</offset>
<use f='llvm/llvm/lib/Target/AArch64/AArch64TargetTransformInfo.cpp' l='545' u='r' c='_ZN4llvm14AArch64TTIImpl18getVectorInstrCostEjPNS_4TypeEj'/>
<use f='llvm/llvm/lib/Target/AArch64/AArch64TargetTransformInfo.cpp' l='571' u='r' c='_ZN4llvm14AArch64TTIImpl22getArithmeticInstrCostEjPNS_4TypeENS_19TargetTransformInfo14TargetCostKindENS3_16OperandValueKindES5_NS3_22OperandValuePrope869056'/>
<use f='llvm/llvm/lib/Target/AArch64/AArch64TargetTransformInfo.cpp' l='760' u='r' c='_ZNK4llvm14AArch64TTIImpl21enableMemCmpExpansionEbb'/>
<use f='llvm/llvm/lib/Target/AArch64/AArch64TargetTransformInfo.cpp' l='796' u='r' c='_ZNK4llvm14AArch64TTIImpl13useNeonVectorEPKNS_4TypeE'/>
<use f='llvm/llvm/lib/Target/AArch64/AArch64TargetTransformInfo.cpp' l='814' u='r' c='_ZN4llvm14AArch64TTIImpl15getMemoryOpCostEjPNS_4TypeENS_10MaybeAlignEjNS_19TargetTransformInfo14TargetCostKindEPKNS_11InstructionE'/>
<use f='llvm/llvm/lib/Target/AArch64/AArch64TargetTransformInfo.cpp' l='889' u='r' c='_ZN4llvm14AArch64TTIImpl22getMaxInterleaveFactorEj'/>
<use f='llvm/llvm/lib/Target/AArch64/AArch64TargetTransformInfo.cpp' l='958' u='r' c='_ZN4llvm14AArch64TTIImpl23getUnrollingPreferencesEPNS_4LoopERNS_15ScalarEvolutionERNS_19TargetTransformInfo20UnrollingPreferencesE'/>
