<dec f='llvm/llvm/lib/Target/Mips/MipsSubtarget.h' l='214' type='const llvm::MipsTargetMachine &amp;'/>
<offset>3328</offset>
<use f='llvm/llvm/lib/Target/Mips/MipsSubtarget.cpp' l='85' u='w' c='_ZN4llvm13MipsSubtargetC1ERKNS_6TripleENS_9StringRefES4_bRKNS_17MipsTargetMachineENS_10MaybeAlignE'/>
<use f='llvm/llvm/lib/Target/Mips/MipsSubtarget.cpp' l='221' u='m' c='_ZNK4llvm13MipsSubtarget21isPositionIndependentEv'/>
<use f='llvm/llvm/lib/Target/Mips/MipsSubtarget.cpp' l='273' u='m' c='_ZNK4llvm13MipsSubtarget18getRelocationModelEv'/>
<use f='llvm/llvm/lib/Target/Mips/MipsSubtarget.cpp' l='279' u='m' c='_ZNK4llvm13MipsSubtarget6getABIEv'/>
