<dec f='llvm/llvm/lib/TableGen/TGParser.cpp' l='50' type='llvm::MultiClass *'/>
<use f='llvm/llvm/lib/TableGen/TGParser.cpp' l='53' u='w' c='_ZN4llvm22SubMultiClassReferenceC1Ev'/>
<use f='llvm/llvm/lib/TableGen/TGParser.cpp' l='55' u='r' c='_ZNK4llvm22SubMultiClassReference9isInvalidEv'/>
<use f='llvm/llvm/lib/TableGen/TGParser.cpp' l='310' u='r' c='_ZN4llvm8TGParser16AddSubMultiClassEPNS_10MultiClassERNS_22SubMultiClassReferenceE'/>
<use f='llvm/llvm/lib/TableGen/TGParser.cpp' l='645' u='w' c='_ZN4llvm8TGParser27ParseSubMultiClassReferenceEPNS_10MultiClassE'/>
<use f='llvm/llvm/lib/TableGen/TGParser.cpp' l='646' u='r' c='_ZN4llvm8TGParser27ParseSubMultiClassReferenceEPNS_10MultiClassE'/>
<use f='llvm/llvm/lib/TableGen/TGParser.cpp' l='656' u='w' c='_ZN4llvm8TGParser27ParseSubMultiClassReferenceEPNS_10MultiClassE'/>
<use f='llvm/llvm/lib/TableGen/TGParser.cpp' l='660' u='r' c='_ZN4llvm8TGParser27ParseSubMultiClassReferenceEPNS_10MultiClassE'/>
<use f='llvm/llvm/lib/TableGen/TGParser.cpp' l='662' u='w' c='_ZN4llvm8TGParser27ParseSubMultiClassReferenceEPNS_10MultiClassE'/>
<use f='llvm/llvm/lib/TableGen/TGParser.cpp' l='668' u='w' c='_ZN4llvm8TGParser27ParseSubMultiClassReferenceEPNS_10MultiClassE'/>
<use f='llvm/llvm/lib/TableGen/TGParser.cpp' l='3398' u='r' c='_ZN4llvm8TGParser15ParseMultiClassEv'/>
<offset>128</offset>
