<dec f='llvm/llvm/include/llvm/Target/TargetMachine.h' l='92' type='const llvm::DataLayout'/>
<use f='llvm/llvm/include/llvm/Target/TargetMachine.h' l='166' u='r' c='_ZNK4llvm13TargetMachine16createDataLayoutEv'/>
<use f='llvm/llvm/include/llvm/Target/TargetMachine.h' l='174' u='m' c='_ZNK4llvm13TargetMachine22isCompatibleDataLayoutERKNS_10DataLayoutE'/>
<use f='llvm/llvm/include/llvm/Target/TargetMachine.h' l='181' u='m' c='_ZNK4llvm13TargetMachine14getPointerSizeEj'/>
<use f='llvm/llvm/include/llvm/Target/TargetMachine.h' l='185' u='m' c='_ZNK4llvm13TargetMachine20getPointerSizeInBitsEj'/>
<use f='llvm/llvm/include/llvm/Target/TargetMachine.h' l='189' u='m' c='_ZNK4llvm13TargetMachine21getProgramPointerSizeEv'/>
<use f='llvm/llvm/include/llvm/Target/TargetMachine.h' l='189' u='m' c='_ZNK4llvm13TargetMachine21getProgramPointerSizeEv'/>
<use f='llvm/llvm/include/llvm/Target/TargetMachine.h' l='193' u='m' c='_ZNK4llvm13TargetMachine20getAllocaPointerSizeEv'/>
<use f='llvm/llvm/include/llvm/Target/TargetMachine.h' l='193' u='m' c='_ZNK4llvm13TargetMachine20getAllocaPointerSizeEv'/>
<offset>128</offset>
<doc f='llvm/llvm/include/llvm/Target/TargetMachine.h' l='86'>/// DataLayout for the target: keep ABI type size and alignment.
  ///
  /// The DataLayout is created based on the string representation provided
  /// during construction. It is kept here only to avoid reparsing the string
  /// but should not really be used during compilation, because it has an
  /// internal cache that is context specific.</doc>
<use f='llvm/llvm/lib/Target/TargetMachine.cpp' l='37' u='w' c='_ZN4llvm13TargetMachineC1ERKNS_6TargetENS_9StringRefERKNS_6TripleES4_S4_RKNS_13TargetOptionsE'/>
