<dec f='llvm/build/lib/Target/Mips/MipsGenInstrInfo.inc' l='1764' type='1749'/>
<use f='llvm/llvm/lib/Target/Mips/AsmParser/MipsAsmParser.cpp' l='2098' u='r' c='_ZN12_GLOBAL__N_113MipsAsmParser18processInstructionERN4llvm6MCInstENS1_5SMLocERNS1_10MCStreamerEPKNS1_15MCSubtargetInfoE'/>
<use f='llvm/build/lib/Target/Mips/MipsGenAsmMatcher.inc' l='6761'/>
<use f='llvm/build/lib/Target/Mips/MipsGenMCCodeEmitter.inc' l='8330' c='_ZNK4llvm17MipsMCCodeEmitter21getBinaryCodeForInstrERKNS_6MCInstERNS_15SmallVectorImplINS_7MCFixupEEERKNS_15MCSubtargetInfoE'/>
<use f='llvm/build/lib/Target/Mips/MipsGenDAGISel.inc' l='24411' u='r' c='_ZN4llvm16MipsDAGToDAGISel10SelectCodeEPNS_6SDNodeE'/>
<use f='llvm/build/lib/Target/Mips/MipsGenDAGISel.inc' l='24411' u='r' c='_ZN4llvm16MipsDAGToDAGISel10SelectCodeEPNS_6SDNodeE'/>
<use f='llvm/build/lib/Target/Mips/MipsGenMCPseudoLowering.inc' l='872' u='r' c='_ZN4llvm14MipsAsmPrinter27emitPseudoExpansionLoweringERNS_10MCStreamerEPKNS_12MachineInstrE'/>
<use f='llvm/llvm/lib/Target/Mips/MipsBranchExpansion.cpp' l='676' u='r' c='_ZN12_GLOBAL__N_119MipsBranchExpansion18expandToLongBranchERNS_7MBBInfoE'/>
<use f='llvm/build/lib/Target/Mips/MipsGenGlobalISel.inc' l='23801' u='r' c='_ZNK12_GLOBAL__N_123MipsInstructionSelector13getMatchTableEv'/>
<use f='llvm/llvm/lib/Target/Mips/MipsSEInstrInfo.cpp' l='30' u='r' c='_ZL22getUnconditionalBranchRKN4llvm13MipsSubtargetE'/>
<use f='llvm/llvm/lib/Target/Mips/MipsSEInstrInfo.cpp' l='665' u='r' c='_ZNK4llvm15MipsSEInstrInfo18getAnalyzableBrOpcEj'/>
