<dec f='llvm/llvm/lib/Target/AArch64/Utils/AArch64BaseInfo.h' l='242' type='6'/>
<use f='llvm/llvm/lib/Target/AArch64/Utils/AArch64BaseInfo.h' l='271' c='_ZN4llvm9AArch64CCL15getCondCodeNameENS0_8CondCodeE'/>
<use f='llvm/llvm/lib/Target/AArch64/Utils/AArch64BaseInfo.h' l='305' c='_ZN4llvm9AArch64CCL24getNZCVToSatisfyCondCodeENS0_8CondCodeE'/>
<doc f='llvm/llvm/lib/Target/AArch64/Utils/AArch64BaseInfo.h' l='242'>// Overflow                   Unordered</doc>
<use f='llvm/llvm/lib/Target/AArch64/AArch64FastISel.cpp' l='2271' u='r' c='_ZL12getCompareCCN4llvm7CmpInst9PredicateE'/>
<use f='llvm/llvm/lib/Target/AArch64/AArch64FastISel.cpp' l='2467' u='r' c='_ZN12_GLOBAL__N_115AArch64FastISel12selectBranchEPKN4llvm11InstructionE'/>
<use f='llvm/llvm/lib/Target/AArch64/AArch64FastISel.cpp' l='2793' u='r' c='_ZN12_GLOBAL__N_115AArch64FastISel12selectSelectEPKN4llvm11InstructionE'/>
<use f='llvm/llvm/lib/Target/AArch64/AArch64FastISel.cpp' l='3438' u='r' c='_ZN12_GLOBAL__N_115AArch64FastISel17foldXALUIntrinsicERN4llvm9AArch64CC8CondCodeEPKNS1_11InstructionEPKNS1_5ValueE'/>
<use f='llvm/llvm/lib/Target/AArch64/AArch64FastISel.cpp' l='3729' u='r' c='_ZN12_GLOBAL__N_115AArch64FastISel22fastLowerIntrinsicCallEPKN4llvm13IntrinsicInstE'/>
<use f='llvm/llvm/lib/Target/AArch64/AArch64FastISel.cpp' l='3737' u='r' c='_ZN12_GLOBAL__N_115AArch64FastISel22fastLowerIntrinsicCallEPKN4llvm13IntrinsicInstE'/>
<use f='llvm/llvm/lib/Target/AArch64/AArch64ISelLowering.cpp' l='2161' u='r' c='_ZL21changeFPCCToAArch64CCN4llvm3ISD8CondCodeERNS_9AArch64CC8CondCodeES4_'/>
<use f='llvm/llvm/lib/Target/AArch64/AArch64ISelLowering.cpp' l='2165' u='r' c='_ZL21changeFPCCToAArch64CCN4llvm3ISD8CondCodeERNS_9AArch64CC8CondCodeES4_'/>
<use f='llvm/llvm/lib/Target/AArch64/AArch64ISelLowering.cpp' l='2807' u='r' c='_ZL17getAArch64XALUOOpRN4llvm9AArch64CC8CondCodeENS_7SDValueERNS_12SelectionDAGE'/>
<use f='llvm/llvm/lib/Target/AArch64/AArch64ISelLowering.cpp' l='2815' u='r' c='_ZL17getAArch64XALUOOpRN4llvm9AArch64CC8CondCodeENS_7SDValueERNS_12SelectionDAGE'/>
<use f='llvm/llvm/lib/Target/AArch64/AArch64ISelLowering.cpp' l='14757' c='_ZL20isEquivalentMasklessjjN4llvm3ISD11LoadExtTypeEii'/>
<use f='llvm/llvm/lib/Target/AArch64/AArch64InstrInfo.cpp' l='1611' c='_ZL11getUsedNZCVN4llvm9AArch64CC8CondCodeE'/>
<use f='llvm/llvm/lib/Target/AArch64/AsmParser/AArch64AsmParser.cpp' l='2761' u='r' c='_ZN12_GLOBAL__N_116AArch64AsmParser19parseCondCodeStringEN4llvm9StringRefE'/>
<use f='llvm/llvm/lib/Target/AArch64/GISel/AArch64InstructionSelector.cpp' l='1241' u='r' c='_ZL25changeFCMPPredToAArch64CCN4llvm7CmpInst9PredicateERNS_9AArch64CC8CondCodeES4_'/>
<use f='llvm/llvm/lib/Target/AArch64/GISel/AArch64InstructionSelector.cpp' l='1245' u='r' c='_ZL25changeFCMPPredToAArch64CCN4llvm7CmpInst9PredicateERNS_9AArch64CC8CondCodeES4_'/>
<use f='llvm/llvm/lib/Target/AArch64/GISel/AArch64InstructionSelector.cpp' l='4375' u='a' c='_ZNK12_GLOBAL__N_126AArch64InstructionSelector14emitOverflowOpEjN4llvm8RegisterERNS1_14MachineOperandES4_RNS1_16MachineIRBuilderE'/>
<use f='llvm/llvm/lib/Target/AArch64/GISel/AArch64InstructionSelector.cpp' l='4379' u='a' c='_ZNK12_GLOBAL__N_126AArch64InstructionSelector14emitOverflowOpEjN4llvm8RegisterERNS1_14MachineOperandES4_RNS1_16MachineIRBuilderE'/>
