<dec f='llvm/llvm/lib/FileCheck/FileCheckImpl.h' l='817' type='llvm::Pattern'/>
<use f='llvm/llvm/lib/FileCheck/FileCheckImpl.h' l='830' u='w' c='_ZN4llvm15FileCheckStringC1ERKNS_7PatternENS_9StringRefENS_5SMLocE'/>
<use f='llvm/llvm/lib/FileCheck/FileCheck.cpp' l='2059' u='r' c='_ZL10PrintMatchbRKN4llvm9SourceMgrERKNS_15FileCheckStringEiNS_9StringRefEmmRNS_16FileCheckRequestEPSt6vectorINS_13FileCheckDiagESaISA_EE'/>
<use f='llvm/llvm/lib/FileCheck/FileCheck.cpp' l='2128' u='r' c='_ZL12PrintNoMatchbRKN4llvm9SourceMgrERKNS_15FileCheckStringEiNS_9StringRefEbPSt6vectorINS_13FileCheckDiagESaIS8_EENS_5ErrorE'/>
<use f='llvm/llvm/lib/FileCheck/FileCheck.cpp' l='2180' u='m' c='_ZNK4llvm15FileCheckString5CheckERKNS_9SourceMgrENS_9StringRefEbRmRNS_16FileCheckRequestEPSt6vectorINS_13FileCheckDiagESaIS9_EE'/>
<use f='llvm/llvm/lib/FileCheck/FileCheck.cpp' l='2184' u='m' c='_ZNK4llvm15FileCheckString5CheckERKNS_9SourceMgrENS_9StringRefEbRmRNS_16FileCheckRequestEPSt6vectorINS_13FileCheckDiagESaIS9_EE'/>
<use f='llvm/llvm/lib/FileCheck/FileCheck.cpp' l='2215' u='m' c='_ZNK4llvm15FileCheckString5CheckERKNS_9SourceMgrENS_9StringRefEbRmRNS_16FileCheckRequestEPSt6vectorINS_13FileCheckDiagESaIS9_EE'/>
<use f='llvm/llvm/lib/FileCheck/FileCheck.cpp' l='2224' u='m' c='_ZNK4llvm15FileCheckString5CheckERKNS_9SourceMgrENS_9StringRefEbRmRNS_16FileCheckRequestEPSt6vectorINS_13FileCheckDiagESaIS9_EE'/>
<use f='llvm/llvm/lib/FileCheck/FileCheck.cpp' l='2239' u='m' c='_ZNK4llvm15FileCheckString9CheckNextERKNS_9SourceMgrENS_9StringRefE'/>
<use f='llvm/llvm/lib/FileCheck/FileCheck.cpp' l='2240' u='m' c='_ZNK4llvm15FileCheckString9CheckNextERKNS_9SourceMgrENS_9StringRefE'/>
<use f='llvm/llvm/lib/FileCheck/FileCheck.cpp' l='2245' u='m' c='_ZNK4llvm15FileCheckString9CheckNextERKNS_9SourceMgrENS_9StringRefE'/>
<use f='llvm/llvm/lib/FileCheck/FileCheck.cpp' l='2278' u='m' c='_ZNK4llvm15FileCheckString9CheckSameERKNS_9SourceMgrENS_9StringRefE'/>
<use f='llvm/llvm/lib/FileCheck/FileCheck.cpp' l='2706' u='m' c='_ZN4llvm9FileCheck10checkInputERNS_9SourceMgrENS_9StringRefEPSt6vectorINS_13FileCheckDiagESaIS5_EE'/>
<offset>0</offset>
<doc f='llvm/llvm/lib/FileCheck/FileCheckImpl.h' l='816'>/// The pattern to match.</doc>
