<dec f='llvm/llvm/include/llvm/Support/GraphWriter.h' l='68' type='const GraphType &amp;'/>
<use f='llvm/llvm/include/llvm/Support/GraphWriter.h' l='110' u='w' c='_ZN4llvm11GraphWriterC1ERNS_11raw_ostreamERKT_b'/>
<use f='llvm/llvm/include/llvm/Support/GraphWriter.h' l='122' c='_ZN4llvm11GraphWriter10writeGraphERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE'/>
<use f='llvm/llvm/include/llvm/Support/GraphWriter.h' l='129' c='_ZN4llvm11GraphWriter11writeHeaderERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE'/>
<use f='llvm/llvm/include/llvm/Support/GraphWriter.h' l='145' c='_ZN4llvm11GraphWriter11writeHeaderERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE'/>
<use f='llvm/llvm/include/llvm/Support/GraphWriter.h' l='156' c='_ZN4llvm11GraphWriter10writeNodesEv'/>
<use f='llvm/llvm/include/llvm/Support/GraphWriter.h' l='161' c='_ZN4llvm11GraphWriter12isNodeHiddenENS_11GraphTraitsIT_E7NodeRefE'/>
<use f='llvm/llvm/include/llvm/Support/GraphWriter.h' l='164' c='_ZN4llvm11GraphWriter9writeNodeENS_11GraphTraitsIT_E7NodeRefE'/>
<use f='llvm/llvm/include/llvm/Support/GraphWriter.h' l='171' c='_ZN4llvm11GraphWriter9writeNodeENS_11GraphTraitsIT_E7NodeRefE'/>
<use f='llvm/llvm/include/llvm/Support/GraphWriter.h' l='174' c='_ZN4llvm11GraphWriter9writeNodeENS_11GraphTraitsIT_E7NodeRefE'/>
<use f='llvm/llvm/include/llvm/Support/GraphWriter.h' l='178' c='_ZN4llvm11GraphWriter9writeNodeENS_11GraphTraitsIT_E7NodeRefE'/>
<use f='llvm/llvm/include/llvm/Support/GraphWriter.h' l='196' c='_ZN4llvm11GraphWriter9writeNodeENS_11GraphTraitsIT_E7NodeRefE'/>
<use f='llvm/llvm/include/llvm/Support/GraphWriter.h' l='199' c='_ZN4llvm11GraphWriter9writeNodeENS_11GraphTraitsIT_E7NodeRefE'/>
<use f='llvm/llvm/include/llvm/Support/GraphWriter.h' l='203' c='_ZN4llvm11GraphWriter9writeNodeENS_11GraphTraitsIT_E7NodeRefE'/>
<use f='llvm/llvm/include/llvm/Support/GraphWriter.h' l='229' c='_ZN4llvm11GraphWriter9writeNodeENS_11GraphTraitsIT_E7NodeRefE'/>
<use f='llvm/llvm/include/llvm/Support/GraphWriter.h' l='232' c='_ZN4llvm11GraphWriter9writeNodeENS_11GraphTraitsIT_E7NodeRefE'/>
<use f='llvm/llvm/include/llvm/Support/GraphWriter.h' l='253' c='_ZN4llvm11GraphWriter9writeEdgeENS_11GraphTraitsIT_E7NodeRefEjNS3_17ChildIteratorTypeE'/>
