<dec f='llvm/llvm/include/llvm/Support/ToolOutputFile.h' l='48' type='llvm::raw_fd_ostream *'/>
<use f='llvm/llvm/include/llvm/Support/ToolOutputFile.h' l='59' u='r' c='_ZN4llvm14ToolOutputFile2osEv'/>
<offset>1152</offset>
<doc f='llvm/llvm/include/llvm/Support/ToolOutputFile.h' l='47'>/// The actual stream to use.</doc>
<use f='llvm/llvm/lib/Support/ToolOutputFile.cpp' l='44' u='w' c='_ZN4llvm14ToolOutputFileC1ENS_9StringRefERSt10error_codeNS_3sys2fs9OpenFlagsE'/>
<use f='llvm/llvm/lib/Support/ToolOutputFile.cpp' l='49' u='w' c='_ZN4llvm14ToolOutputFileC1ENS_9StringRefERSt10error_codeNS_3sys2fs9OpenFlagsE'/>
<use f='llvm/llvm/lib/Support/ToolOutputFile.cpp' l='58' u='w' c='_ZN4llvm14ToolOutputFileC1ENS_9StringRefEi'/>
