<dec f='llvm/llvm/include/llvm/Transforms/Utils/FunctionImportUtils.h' l='27' type='llvm::Module &amp;'/>
<use f='llvm/llvm/include/llvm/Transforms/Utils/FunctionImportUtils.h' l='104' u='w' c='_ZN4llvm30FunctionImportGlobalProcessingC1ERNS_6ModuleERKNS_18ModuleSummaryIndexEPNS_9SetVectorIPNS_11GlobalValueESt6vectorIS8_SaIS8_EENS_8DenseSetIS814283526'/>
<offset>0</offset>
<doc f='llvm/llvm/include/llvm/Transforms/Utils/FunctionImportUtils.h' l='26'>/// The Module which we are exporting or importing functions from.</doc>
<use f='llvm/llvm/lib/Transforms/Utils/FunctionImportUtils.cpp' l='206' u='m' c='_ZN4llvm30FunctionImportGlobalProcessing23processGlobalForThinLTOERNS_11GlobalValueE'/>
<use f='llvm/llvm/lib/Transforms/Utils/FunctionImportUtils.cpp' l='243' u='m' c='_ZN4llvm30FunctionImportGlobalProcessing23processGlobalForThinLTOERNS_11GlobalValueE'/>
<use f='llvm/llvm/lib/Transforms/Utils/FunctionImportUtils.cpp' l='272' u='m' c='_ZN4llvm30FunctionImportGlobalProcessing23processGlobalForThinLTOERNS_11GlobalValueE'/>
<use f='llvm/llvm/lib/Transforms/Utils/FunctionImportUtils.cpp' l='305' u='m' c='_ZN4llvm30FunctionImportGlobalProcessing24processGlobalsForThinLTOEv'/>
<use f='llvm/llvm/lib/Transforms/Utils/FunctionImportUtils.cpp' l='307' c='_ZN4llvm30FunctionImportGlobalProcessing24processGlobalsForThinLTOEv'/>
<use f='llvm/llvm/lib/Transforms/Utils/FunctionImportUtils.cpp' l='309' u='m' c='_ZN4llvm30FunctionImportGlobalProcessing24processGlobalsForThinLTOEv'/>
<use f='llvm/llvm/lib/Transforms/Utils/FunctionImportUtils.cpp' l='315' u='m' c='_ZN4llvm30FunctionImportGlobalProcessing24processGlobalsForThinLTOEv'/>
