<use f='llvm/llvm/include/llvm/Support/VirtualFileSystem.h' l='373' u='w' c='_ZN4llvm3vfs15ProxyFileSystemC1ENS_18IntrusiveRefCntPtrINS0_10FileSystemEEE'/>
<use f='llvm/llvm/include/llvm/Support/VirtualFileSystem.h' l='376' u='m' c='_ZN4llvm3vfs15ProxyFileSystem6statusERKNS_5TwineE'/>
<use f='llvm/llvm/include/llvm/Support/VirtualFileSystem.h' l='380' u='m' c='_ZN4llvm3vfs15ProxyFileSystem15openFileForReadERKNS_5TwineE'/>
<use f='llvm/llvm/include/llvm/Support/VirtualFileSystem.h' l='383' u='m' c='_ZN4llvm3vfs15ProxyFileSystem9dir_beginERKNS_5TwineERSt10error_code'/>
<use f='llvm/llvm/include/llvm/Support/VirtualFileSystem.h' l='386' u='m' c='_ZNK4llvm3vfs15ProxyFileSystem26getCurrentWorkingDirectoryB5cxx11Ev'/>
<use f='llvm/llvm/include/llvm/Support/VirtualFileSystem.h' l='389' u='m' c='_ZN4llvm3vfs15ProxyFileSystem26setCurrentWorkingDirectoryERKNS_5TwineE'/>
<use f='llvm/llvm/include/llvm/Support/VirtualFileSystem.h' l='393' u='m' c='_ZNK4llvm3vfs15ProxyFileSystem11getRealPathERKNS_5TwineERNS_15SmallVectorImplIcEE'/>
<use f='llvm/llvm/include/llvm/Support/VirtualFileSystem.h' l='396' u='m' c='_ZN4llvm3vfs15ProxyFileSystem7isLocalERKNS_5TwineERb'/>
<use f='llvm/llvm/include/llvm/Support/VirtualFileSystem.h' l='400' u='m' c='_ZN4llvm3vfs15ProxyFileSystem15getUnderlyingFSEv'/>
<dec f='llvm/llvm/include/llvm/Support/VirtualFileSystem.h' l='403' type='IntrusiveRefCntPtr&lt;llvm::vfs::FileSystem&gt;'/>
<offset>128</offset>
