<dec f='llvm/llvm/include/llvm/ExecutionEngine/Orc/Layer.h' l='175' type='llvm::orc::ObjectLayer &amp;'/>
<offset>320</offset>
<use f='llvm/llvm/lib/ExecutionEngine/Orc/Layer.cpp' l='191' u='w' c='_ZN4llvm3orc35BasicObjectLayerMaterializationUnitC1ERNS0_11ObjectLayerESt10unique_ptrINS_12MemoryBufferESt14default_deleteIS5_EENS_8DenseMapINS0_15Sym246112'/>
<use f='llvm/llvm/lib/ExecutionEngine/Orc/Layer.cpp' l='202' u='m' c='_ZN4llvm3orc35BasicObjectLayerMaterializationUnit11materializeESt10unique_ptrINS0_29MaterializationResponsibilityESt14default_deleteIS3_EE'/>
