<use f='llvm/llvm/tools/llvm-readobj/WindowsResourceDumper.h' l='21' u='w' c='_ZN4llvm6object10WindowsRes6DumperC1EPNS0_15WindowsResourceERNS_13ScopedPrinterE'/>
<dec f='llvm/llvm/tools/llvm-readobj/WindowsResourceDumper.h' l='26' type='llvm::ScopedPrinter &amp;'/>
<use f='llvm/llvm/tools/llvm-readobj/WindowsResourceDumper.cpp' l='57' u='m' c='_ZN4llvm6object10WindowsRes6Dumper10printEntryERKNS0_16ResourceEntryRefE'/>
<use f='llvm/llvm/tools/llvm-readobj/WindowsResourceDumper.cpp' l='62' u='m' c='_ZN4llvm6object10WindowsRes6Dumper10printEntryERKNS0_16ResourceEntryRefE'/>
<use f='llvm/llvm/tools/llvm-readobj/WindowsResourceDumper.cpp' l='67' u='m' c='_ZN4llvm6object10WindowsRes6Dumper10printEntryERKNS0_16ResourceEntryRefE'/>
<use f='llvm/llvm/tools/llvm-readobj/WindowsResourceDumper.cpp' l='69' u='m' c='_ZN4llvm6object10WindowsRes6Dumper10printEntryERKNS0_16ResourceEntryRefE'/>
<use f='llvm/llvm/tools/llvm-readobj/WindowsResourceDumper.cpp' l='71' u='m' c='_ZN4llvm6object10WindowsRes6Dumper10printEntryERKNS0_16ResourceEntryRefE'/>
<use f='llvm/llvm/tools/llvm-readobj/WindowsResourceDumper.cpp' l='72' u='m' c='_ZN4llvm6object10WindowsRes6Dumper10printEntryERKNS0_16ResourceEntryRefE'/>
<use f='llvm/llvm/tools/llvm-readobj/WindowsResourceDumper.cpp' l='73' u='m' c='_ZN4llvm6object10WindowsRes6Dumper10printEntryERKNS0_16ResourceEntryRefE'/>
<use f='llvm/llvm/tools/llvm-readobj/WindowsResourceDumper.cpp' l='74' u='m' c='_ZN4llvm6object10WindowsRes6Dumper10printEntryERKNS0_16ResourceEntryRefE'/>
<use f='llvm/llvm/tools/llvm-readobj/WindowsResourceDumper.cpp' l='75' u='m' c='_ZN4llvm6object10WindowsRes6Dumper10printEntryERKNS0_16ResourceEntryRefE'/>
<use f='llvm/llvm/tools/llvm-readobj/WindowsResourceDumper.cpp' l='76' u='m' c='_ZN4llvm6object10WindowsRes6Dumper10printEntryERKNS0_16ResourceEntryRefE'/>
<use f='llvm/llvm/tools/llvm-readobj/WindowsResourceDumper.cpp' l='77' u='m' c='_ZN4llvm6object10WindowsRes6Dumper10printEntryERKNS0_16ResourceEntryRefE'/>
<use f='llvm/llvm/tools/llvm-readobj/WindowsResourceDumper.cpp' l='78' u='m' c='_ZN4llvm6object10WindowsRes6Dumper10printEntryERKNS0_16ResourceEntryRefE'/>
<use f='llvm/llvm/tools/llvm-readobj/WindowsResourceDumper.cpp' l='79' u='m' c='_ZN4llvm6object10WindowsRes6Dumper10printEntryERKNS0_16ResourceEntryRefE'/>
<offset>0</offset>
