<use f='llvm/llvm/include/llvm/Transforms/IPO/Attributor.h' l='751' u='w' c='_ZN4llvm16InformationCacheC1ERKNS_6ModuleERNS_14AnalysisGetterERNS_20BumpPtrAllocatorImplINS_15MallocAllocatorELm4096ELm4096ELm128EEEPNS_9SetVectorIPN13877892'/>
<use f='llvm/llvm/include/llvm/Transforms/IPO/Attributor.h' l='890' u='a' c='_ZN4llvm16InformationCache5getDLEv'/>
<dec f='llvm/llvm/include/llvm/Transforms/IPO/Attributor.h' l='954' type='const llvm::DataLayout &amp;'/>
<use f='llvm/llvm/include/llvm/Transforms/IPO/Attributor.h' l='1554' u='a' c='_ZNK4llvm10Attributor13getDataLayoutEv'/>
<offset>960</offset>
<doc f='llvm/llvm/include/llvm/Transforms/IPO/Attributor.h' l='953'>/// The datalayout used in the module.</doc>
