<dec f='llvm/llvm/lib/Target/Hexagon/HexagonVLIWPacketizer.h' l='70' type='const llvm::MachineLoopInfo *'/>
<use f='llvm/llvm/lib/Target/Hexagon/HexagonVLIWPacketizer.cpp' l='136' u='w' c='_ZN4llvm21HexagonPacketizerListC1ERNS_15MachineFunctionERNS_15MachineLoopInfoEPNS_9AAResultsEPKNS_28MachineBranchProbabilityInfoEb'/>
<use f='llvm/llvm/lib/Target/Hexagon/HexagonVLIWPacketizer.cpp' l='1898' u='r' c='_ZN4llvm21HexagonPacketizerList13producesStallERKNS_12MachineInstrE'/>
<use f='llvm/llvm/lib/Target/Hexagon/HexagonVLIWPacketizer.cpp' l='1898' u='r' c='_ZN4llvm21HexagonPacketizerList13producesStallERKNS_12MachineInstrE'/>
<offset>1664</offset>
