<dec f='llvm/build/lib/Target/X86/X86GenRegisterInfo.inc' l='71' type='51'/>
<use f='llvm/build/lib/Target/X86/X86GenAsmMatcher.inc' l='7271' c='_ZL20validateOperandClassRN4llvm18MCParsedAsmOperandEN12_GLOBAL__N_114MatchClassKindE'/>
<use f='llvm/llvm/lib/Target/X86/Disassembler/X86Disassembler.cpp' l='1773' macro='1' u='r' c='_ZL17translateRegisterRN4llvm6MCInstENS_15X86Disassembler3RegE'/>
<use f='llvm/llvm/lib/Target/X86/Disassembler/X86Disassembler.cpp' l='2010' macro='1' u='r' c='_ZL19translateRMRegisterRN4llvm6MCInstERNS_15X86Disassembler19InternalInstructionE'/>
<use f='llvm/llvm/lib/Target/X86/Disassembler/X86Disassembler.cpp' l='2057' macro='1' u='r' c='_ZL17translateRMMemoryRN4llvm6MCInstERNS_15X86Disassembler19InternalInstructionEPKNS_14MCDisassemblerEb'/>
<use f='llvm/llvm/lib/Target/X86/Disassembler/X86Disassembler.cpp' l='2073' macro='1' u='r' c='_ZL17translateRMMemoryRN4llvm6MCInstERNS_15X86Disassembler19InternalInstructionEPKNS_14MCDisassemblerEb'/>
<use f='llvm/llvm/lib/Target/X86/Disassembler/X86Disassembler.cpp' l='2151' macro='1' u='r' c='_ZL17translateRMMemoryRN4llvm6MCInstERNS_15X86Disassembler19InternalInstructionEPKNS_14MCDisassemblerEb'/>
<use f='llvm/llvm/lib/Target/X86/MCTargetDesc/X86AsmBackend.cpp' l='1269' c='_ZNK12_GLOBAL__N_119DarwinX86AsmBackend13PushInstrSizeEj'/>
<use f='llvm/llvm/lib/Target/X86/MCTargetDesc/X86AsmBackend.cpp' l='1289' u='r' c='_ZNK12_GLOBAL__N_119DarwinX86AsmBackend22getCompactUnwindRegNumEj'/>
<use f='llvm/llvm/lib/Target/X86/MCTargetDesc/X86MCTargetDesc.cpp' l='155' u='r' c='_ZN4llvm6X86_MC28initLLVMToSEHAndCVRegMappingEPNS_14MCRegisterInfoE'/>
<use f='llvm/llvm/lib/Target/X86/MCTargetDesc/X86MCTargetDesc.cpp' l='633' c='_ZN4llvm28getX86SubSuperRegisterOrZeroENS_10MCRegisterEjb'/>
<use f='llvm/llvm/lib/Target/X86/MCTargetDesc/X86MCTargetDesc.cpp' l='645' c='_ZN4llvm28getX86SubSuperRegisterOrZeroENS_10MCRegisterEjb'/>
<use f='llvm/llvm/lib/Target/X86/MCTargetDesc/X86MCTargetDesc.cpp' l='682' c='_ZN4llvm28getX86SubSuperRegisterOrZeroENS_10MCRegisterEjb'/>
<use f='llvm/llvm/lib/Target/X86/MCTargetDesc/X86MCTargetDesc.cpp' l='718' c='_ZN4llvm28getX86SubSuperRegisterOrZeroENS_10MCRegisterEjb'/>
<use f='llvm/llvm/lib/Target/X86/MCTargetDesc/X86MCTargetDesc.cpp' l='754' c='_ZN4llvm28getX86SubSuperRegisterOrZeroENS_10MCRegisterEjb'/>
<use f='llvm/llvm/lib/Target/X86/MCTargetDesc/X86MCTargetDesc.cpp' l='755' u='r' c='_ZN4llvm28getX86SubSuperRegisterOrZeroENS_10MCRegisterEjb'/>
<use f='llvm/build/lib/Target/X86/X86GenCallingConv.inc' l='1680' u='r' c='_ZL13CC_X86_64_GHCjN4llvm3MVTES0_NS_11CCValAssign7LocInfoENS_3ISD10ArgFlagsTyERNS_7CCStateE'/>
<use f='llvm/build/lib/Target/X86/X86GenCallingConv.inc' l='1751' u='r' c='_ZL14CC_X86_64_HHVMjN4llvm3MVTES0_NS_11CCValAssign7LocInfoENS_3ISD10ArgFlagsTyERNS_7CCStateE'/>
<use f='llvm/build/lib/Target/X86/X86GenCallingConv.inc' l='3394' u='r' c='_ZL17RetCC_X86_64_HHVMjN4llvm3MVTES0_NS_11CCValAssign7LocInfoENS_3ISD10ArgFlagsTyERNS_7CCStateE'/>
<use f='llvm/llvm/lib/Target/X86/X86ExpandPseudo.cpp' l='351' u='r' c='_ZN12_GLOBAL__N_115X86ExpandPseudo8ExpandMIERN4llvm17MachineBasicBlockENS1_26MachineInstrBundleIteratorINS1_12MachineInstrELb0EEE'/>
<use f='llvm/llvm/lib/Target/X86/X86ExpandPseudo.cpp' l='358' u='r' c='_ZN12_GLOBAL__N_115X86ExpandPseudo8ExpandMIERN4llvm17MachineBasicBlockENS1_26MachineInstrBundleIteratorINS1_12MachineInstrELb0EEE'/>
<use f='llvm/llvm/lib/Target/X86/X86ExpandPseudo.cpp' l='456' u='r' c='_ZN12_GLOBAL__N_115X86ExpandPseudo8ExpandMIERN4llvm17MachineBasicBlockENS1_26MachineInstrBundleIteratorINS1_12MachineInstrELb0EEE'/>
<use f='llvm/llvm/lib/Target/X86/X86ISelLowering.cpp' l='34039' u='r' c='_ZNK4llvm17X86TargetLowering27EmitInstrWithCustomInserterERNS_12MachineInstrEPNS_17MachineBasicBlockE'/>
<use f='llvm/llvm/lib/Target/X86/X86ISelLowering.cpp' l='34046' u='r' c='_ZNK4llvm17X86TargetLowering27EmitInstrWithCustomInserterERNS_12MachineInstrEPNS_17MachineBasicBlockE'/>
<use f='llvm/llvm/lib/Target/X86/X86ISelLowering.cpp' l='34056' u='r' c='_ZNK4llvm17X86TargetLowering27EmitInstrWithCustomInserterERNS_12MachineInstrEPNS_17MachineBasicBlockE'/>
<use f='llvm/llvm/lib/Target/X86/X86ISelLowering.cpp' l='34069' u='r' c='_ZNK4llvm17X86TargetLowering27EmitInstrWithCustomInserterERNS_12MachineInstrEPNS_17MachineBasicBlockE'/>
<use f='llvm/llvm/lib/Target/X86/X86ISelLowering.cpp' l='34095' u='r' c='_ZNK4llvm17X86TargetLowering27EmitInstrWithCustomInserterERNS_12MachineInstrEPNS_17MachineBasicBlockE'/>
<use f='llvm/llvm/lib/Target/X86/X86ISelLowering.cpp' l='51507' c='_ZNK4llvm17X86TargetLowering28getRegForInlineAsmConstraintEPKNS_18TargetRegisterInfoENS_9StringRefENS_3MVTE'/>
<use f='llvm/llvm/lib/Target/X86/X86RegisterInfo.cpp' l='68' u='r' c='_ZN4llvm15X86RegisterInfoC1ERKNS_6TripleE'/>
<use f='llvm/llvm/unittests/tools/llvm-exegesis/X86/SnippetGeneratorTest.cpp' l='456' u='r' c='_ZN4llvm8exegesis12_GLOBAL__N_165FakeSnippetGeneratorTest_ComputeRegisterInitialValuesAdd64rr_Test8TestBodyEv'/>
<use f='llvm/llvm/unittests/tools/llvm-exegesis/X86/SnippetGeneratorTest.cpp' l='461' u='r' c='_ZN4llvm8exegesis12_GLOBAL__N_165FakeSnippetGeneratorTest_ComputeRegisterInitialValuesAdd64rr_Test8TestBodyEv'/>
