<dec f='llvm/llvm/include/llvm/Analysis/MemoryBuiltins.h' l='297' type='const llvm::DataLayout &amp;'/>
<offset>0</offset>
<use f='llvm/llvm/lib/Analysis/MemoryBuiltins.cpp' l='862' u='w' c='_ZN4llvm25ObjectSizeOffsetEvaluatorC1ERKNS_10DataLayoutEPKNS_17TargetLibraryInfoERNS_11LLVMContextENS_14ObjectSizeOptsE'/>
<use f='llvm/llvm/lib/Analysis/MemoryBuiltins.cpp' l='873' u='m' c='_ZN4llvm25ObjectSizeOffsetEvaluator7computeEPNS_5ValueE'/>
<use f='llvm/llvm/lib/Analysis/MemoryBuiltins.cpp' l='902' u='r' c='_ZN4llvm25ObjectSizeOffsetEvaluator8compute_EPNS_5ValueE'/>
<use f='llvm/llvm/lib/Analysis/MemoryBuiltins.cpp' l='960' u='m' c='_ZN4llvm25ObjectSizeOffsetEvaluator15visitAllocaInstERNS_10AllocaInstE'/>
<use f='llvm/llvm/lib/Analysis/MemoryBuiltins.cpp' l='1011' u='r' c='_ZN4llvm25ObjectSizeOffsetEvaluator16visitGEPOperatorERNS_11GEPOperatorE'/>
