<dec f='llvm/llvm/unittests/Transforms/IPO/AttributorTestBase.h' l='34' type='std::unique_ptr&lt;Module&gt;'/>
<use f='llvm/llvm/unittests/Transforms/IPO/AttributorTestBase.h' l='40' u='w' c='_ZN4llvm18AttributorTestBase11parseModuleEPKc'/>
<use f='llvm/llvm/unittests/Transforms/IPO/AttributorTestBase.h' l='41' u='r' c='_ZN4llvm18AttributorTestBase11parseModuleEPKc'/>
<use f='llvm/llvm/unittests/Transforms/IPO/AttributorTestBase.h' l='42' u='m' c='_ZN4llvm18AttributorTestBase11parseModuleEPKc'/>
<offset>192</offset>
