<use f='llvm/llvm/include/llvm/IR/DebugInfo.h' l='114' u='m' c='_ZNK4llvm15DebugInfoFinder11subprogramsEv'/>
<use f='llvm/llvm/include/llvm/IR/DebugInfo.h' l='114' u='m' c='_ZNK4llvm15DebugInfoFinder11subprogramsEv'/>
<use f='llvm/llvm/include/llvm/IR/DebugInfo.h' l='131' u='m' c='_ZNK4llvm15DebugInfoFinder16subprogram_countEv'/>
<dec f='llvm/llvm/include/llvm/IR/DebugInfo.h' l='137' type='SmallVector&lt;llvm::DISubprogram *, 8&gt;'/>
<offset>640</offset>
<use f='llvm/llvm/lib/IR/DebugInfo.cpp' l='55' u='m' c='_ZN4llvm15DebugInfoFinder5resetEv'/>
<use f='llvm/llvm/lib/IR/DebugInfo.cpp' l='247' u='m' c='_ZN4llvm15DebugInfoFinder13addSubprogramEPNS_12DISubprogramE'/>
