<use f='llvm/llvm/lib/Support/YAMLParser.cpp' l='272' u='r' c='_ZN4llvm4yaml7Scanner8setErrorERKNS_5TwineEPKc'/>
<use f='llvm/llvm/lib/Support/YAMLParser.cpp' l='273' u='r' c='_ZN4llvm4yaml7Scanner8setErrorERKNS_5TwineEPKc'/>
<dec f='llvm/llvm/lib/Support/YAMLParser.cpp' l='551' type='std::error_code *'/>
<use f='llvm/llvm/lib/Support/YAMLParser.cpp' l='837' u='w' c='_ZN4llvm4yaml7ScannerC1ENS_9StringRefERNS_9SourceMgrEbPSt10error_code'/>
<use f='llvm/llvm/lib/Support/YAMLParser.cpp' l='843' u='w' c='_ZN4llvm4yaml7ScannerC1ENS_15MemoryBufferRefERNS_9SourceMgrEbPSt10error_code'/>
<offset>2688</offset>
