<dec f='llvm/build/lib/Target/Hexagon/HexagonGenRegisterInfo.inc' l='26' type='6'/>
<use f='llvm/build/lib/Target/Hexagon/HexagonGenAsmMatcher.inc' l='7060' c='_ZL20validateOperandClassRN4llvm18MCParsedAsmOperandEN12_GLOBAL__N_114MatchClassKindE'/>
<use f='llvm/llvm/lib/Target/Hexagon/Disassembler/HexagonDisassembler.cpp' l='663' u='r' c='_ZL26DecodeCtrRegsRegisterClassRN4llvm6MCInstEjmPKv'/>
<use f='llvm/llvm/lib/Target/Hexagon/HexagonRegisterInfo.cpp' l='158' u='r' c='_ZNK4llvm19HexagonRegisterInfo15getReservedRegsERKNS_15MachineFunctionE'/>
<use f='llvm/llvm/lib/Target/Hexagon/MCTargetDesc/HexagonMCCodeEmitter.cpp' l='650' u='r' c='_ZNK4llvm20HexagonMCCodeEmitter14getExprOpValueERKNS_6MCInstERKNS_9MCOperandEPKNS_6MCExprERNS_15SmallVectorImplINS_7MCFixupEEERKNS_15MCSubtargetInfoE'/>
