<use f='llvm/llvm/include/llvm/Analysis/DDG.h' l='438' u='w' c='_ZN4llvm22DDGAnalysisPrinterPassC1ERNS_11raw_ostreamE'/>
<dec f='llvm/llvm/include/llvm/Analysis/DDG.h' l='443' type='llvm::raw_ostream &amp;'/>
<use f='llvm/llvm/lib/Analysis/DDG.cpp' l='320' u='m' c='_ZN4llvm22DDGAnalysisPrinterPass3runERNS_4LoopERNS_15AnalysisManagerIS1_JRNS_27LoopStandardAnalysisResultsEEEES5_RNS_10LPMUpdaterE'/>
<use f='llvm/llvm/lib/Analysis/DDG.cpp' l='321' u='a' c='_ZN4llvm22DDGAnalysisPrinterPass3runERNS_4LoopERNS_15AnalysisManagerIS1_JRNS_27LoopStandardAnalysisResultsEEEES5_RNS_10LPMUpdaterE'/>
<offset>0</offset>
