<dec f='llvm/llvm/lib/Target/AArch64/Utils/AArch64BaseInfo.h' l='237' type='1'/>
<use f='llvm/llvm/lib/Target/AArch64/Utils/AArch64BaseInfo.h' l='256'/>
<use f='llvm/llvm/lib/Target/AArch64/Utils/AArch64BaseInfo.h' l='266' c='_ZN4llvm9AArch64CCL15getCondCodeNameENS0_8CondCodeE'/>
<use f='llvm/llvm/lib/Target/AArch64/Utils/AArch64BaseInfo.h' l='300' c='_ZN4llvm9AArch64CCL24getNZCVToSatisfyCondCodeENS0_8CondCodeE'/>
<doc f='llvm/llvm/lib/Target/AArch64/Utils/AArch64BaseInfo.h' l='237'>// Not equal                  Not equal, or unordered</doc>
<use f='llvm/llvm/lib/Target/AArch64/AArch64AsmPrinter.cpp' l='386' u='r' c='_ZN12_GLOBAL__N_117AArch64AsmPrinter26EmitHwasanMemaccessSymbolsERN4llvm6ModuleE'/>
<use f='llvm/llvm/lib/Target/AArch64/AArch64CondBrTuning.cpp' l='126' u='r' c='_ZN12_GLOBAL__N_119AArch64CondBrTuning15convertToCondBrERN4llvm12MachineInstrE'/>
<use f='llvm/llvm/lib/Target/AArch64/AArch64ConditionalCompares.cpp' l='294' u='r' c='_ZL9parseCondN4llvm8ArrayRefINS_14MachineOperandEEERNS_9AArch64CC8CondCodeE'/>
<use f='llvm/llvm/lib/Target/AArch64/AArch64ConditionalCompares.cpp' l='709' u='r' c='_ZN12_GLOBAL__N_111SSACCmpConv7convertERN4llvm15SmallVectorImplIPNS1_17MachineBasicBlockEEE'/>
<use f='llvm/llvm/lib/Target/AArch64/AArch64ExpandPseudoInsts.cpp' l='221' u='r' c='_ZN12_GLOBAL__N_119AArch64ExpandPseudo14expandCMP_SWAPERN4llvm17MachineBasicBlockENS1_26MachineInstrBundleIteratorINS1_12MachineInstrELb0EEEjjjjjRS6_'/>
<use f='llvm/llvm/lib/Target/AArch64/AArch64FastISel.cpp' l='2282' u='r' c='_ZL12getCompareCCN4llvm7CmpInst9PredicateE'/>
<use f='llvm/llvm/lib/Target/AArch64/AArch64FastISel.cpp' l='2506' u='r' c='_ZN12_GLOBAL__N_115AArch64FastISel12selectBranchEPKN4llvm11InstructionE'/>
<use f='llvm/llvm/lib/Target/AArch64/AArch64FastISel.cpp' l='2604' u='r' c='_ZN12_GLOBAL__N_115AArch64FastISel9selectCmpEPKN4llvm11InstructionE'/>
<use f='llvm/llvm/lib/Target/AArch64/AArch64FastISel.cpp' l='2741' u='r' c='_ZN12_GLOBAL__N_115AArch64FastISel12selectSelectEPKN4llvm11InstructionE'/>
<use f='llvm/llvm/lib/Target/AArch64/AArch64FastISel.cpp' l='3448' u='r' c='_ZN12_GLOBAL__N_115AArch64FastISel17foldXALUIntrinsicERN4llvm9AArch64CC8CondCodeEPKNS1_11InstructionEPKNS1_5ValueE'/>
<use f='llvm/llvm/lib/Target/AArch64/AArch64FastISel.cpp' l='3744' u='r' c='_ZN12_GLOBAL__N_115AArch64FastISel22fastLowerIntrinsicCallEPKN4llvm13IntrinsicInstE'/>
<use f='llvm/llvm/lib/Target/AArch64/AArch64FastISel.cpp' l='3779' u='r' c='_ZN12_GLOBAL__N_115AArch64FastISel22fastLowerIntrinsicCallEPKN4llvm13IntrinsicInstE'/>
<use f='llvm/llvm/lib/Target/AArch64/AArch64FastISel.cpp' l='5145' u='r' c='_ZN12_GLOBAL__N_115AArch64FastISel19selectAtomicCmpXchgEPKN4llvm17AtomicCmpXchgInstE'/>
<use f='llvm/llvm/lib/Target/AArch64/AArch64ISelLowering.cpp' l='2105' u='r' c='_ZL22changeIntCCToAArch64CCN4llvm3ISD8CondCodeE'/>
<use f='llvm/llvm/lib/Target/AArch64/AArch64ISelLowering.cpp' l='2183' u='r' c='_ZL21changeFPCCToAArch64CCN4llvm3ISD8CondCodeERNS_9AArch64CC8CondCodeES4_'/>
<use f='llvm/llvm/lib/Target/AArch64/AArch64ISelLowering.cpp' l='2205' u='r' c='_ZL24changeFPCCToANDAArch64CCN4llvm3ISD8CondCodeERNS_9AArch64CC8CondCodeES4_'/>
<use f='llvm/llvm/lib/Target/AArch64/AArch64ISelLowering.cpp' l='2824' u='r' c='_ZL17getAArch64XALUOOpRN4llvm9AArch64CC8CondCodeENS_7SDValueERNS_12SelectionDAGE'/>
<use f='llvm/llvm/lib/Target/AArch64/AArch64ISelLowering.cpp' l='6800' u='r' c='_ZNK4llvm21AArch64TargetLowering14LowerSELECT_CCENS_3ISD8CondCodeENS_7SDValueES3_S3_S3_RKNS_5SDLocERNS_12SelectionDAGE'/>
<use f='llvm/llvm/lib/Target/AArch64/AArch64ISelLowering.cpp' l='10191' c='_ZL20EmitVectorComparisonN4llvm7SDValueES0_NS_9AArch64CC8CondCodeEbNS_3EVTERKNS_5SDLocERNS_12SelectionDAGE'/>
<use f='llvm/llvm/lib/Target/AArch64/AArch64ISelLowering.cpp' l='10230' c='_ZL20EmitVectorComparisonN4llvm7SDValueES0_NS_9AArch64CC8CondCodeEbNS_3EVTERKNS_5SDLocERNS_12SelectionDAGE'/>
<use f='llvm/llvm/lib/Target/AArch64/AArch64ISelLowering.cpp' l='14748' c='_ZL20isEquivalentMasklessjjN4llvm3ISD11LoadExtTypeEii'/>
<use f='llvm/llvm/lib/Target/AArch64/AArch64ISelLowering.cpp' l='14863' u='r' c='_ZL20performBRCONDCombinePN4llvm6SDNodeERNS_14TargetLowering15DAGCombinerInfoERNS_12SelectionDAGE'/>
<use f='llvm/llvm/lib/Target/AArch64/AArch64InstrInfo.cpp' l='687' u='r' c='_ZNK4llvm16AArch64InstrInfo12insertSelectERNS_17MachineBasicBlockENS_26MachineInstrBundleIteratorINS_12MachineInstrELb0EEERKNS_8DebugLocENS_8RegisterE7312218'/>
<use f='llvm/llvm/lib/Target/AArch64/AArch64InstrInfo.cpp' l='691' u='r' c='_ZNK4llvm16AArch64InstrInfo12insertSelectERNS_17MachineBasicBlockENS_26MachineInstrBundleIteratorINS_12MachineInstrELb0EEERKNS_8DebugLocENS_8RegisterE7312218'/>
<use f='llvm/llvm/lib/Target/AArch64/AArch64InstrInfo.cpp' l='722' u='r' c='_ZNK4llvm16AArch64InstrInfo12insertSelectERNS_17MachineBasicBlockENS_26MachineInstrBundleIteratorINS_12MachineInstrELb0EEERKNS_8DebugLocENS_8RegisterE7312218'/>
<use f='llvm/llvm/lib/Target/AArch64/AArch64InstrInfo.cpp' l='1593' c='_ZL11getUsedNZCVN4llvm9AArch64CC8CondCodeE'/>
<use f='llvm/llvm/lib/Target/AArch64/AArch64RedundantCopyElimination.cpp' l='146' u='r' c='_ZN12_GLOBAL__N_131AArch64RedundantCopyElimination18knownRegValInBlockERN4llvm12MachineInstrEPNS1_17MachineBasicBlockERNS1_15SmallVectorImplINS0_6RegI8280297'/>
<use f='llvm/llvm/lib/Target/AArch64/AArch64RedundantCopyElimination.cpp' l='151' u='r' c='_ZN12_GLOBAL__N_131AArch64RedundantCopyElimination18knownRegValInBlockERN4llvm12MachineInstrEPNS1_17MachineBasicBlockERNS1_15SmallVectorImplINS0_6RegI8280297'/>
<use f='llvm/llvm/lib/Target/AArch64/AsmParser/AArch64AsmParser.cpp' l='2754' u='r' c='_ZN12_GLOBAL__N_116AArch64AsmParser19parseCondCodeStringEN4llvm9StringRefE'/>
<use f='llvm/llvm/lib/Target/AArch64/AsmParser/AArch64AsmParser.cpp' l='2777' u='r' c='_ZN12_GLOBAL__N_116AArch64AsmParser19parseCondCodeStringEN4llvm9StringRefE'/>
<use f='llvm/llvm/lib/Target/AArch64/GISel/AArch64InstructionSelector.cpp' l='1189' u='r' c='_ZL25changeICMPPredToAArch64CCN4llvm7CmpInst9PredicateE'/>
<use f='llvm/llvm/lib/Target/AArch64/GISel/AArch64InstructionSelector.cpp' l='1260' u='r' c='_ZL25changeFCMPPredToAArch64CCN4llvm7CmpInst9PredicateERNS_9AArch64CC8CondCodeES4_'/>
<use f='llvm/llvm/lib/Target/AArch64/GISel/AArch64InstructionSelector.cpp' l='3069' u='r' c='_ZN12_GLOBAL__N_126AArch64InstructionSelector6selectERN4llvm12MachineInstrE'/>
<use f='llvm/llvm/lib/Target/AArch64/GISel/AArch64InstructionSelector.cpp' l='4499' u='r' c='_ZNK12_GLOBAL__N_126AArch64InstructionSelector21tryFoldIntegerCompareERN4llvm14MachineOperandES3_S3_RNS1_16MachineIRBuilderE'/>
