<dec f='llvm/llvm/include/llvm/MC/StringTableBuilder.h' l='40' type='llvm::StringTableBuilder::Kind'/>
<offset>256</offset>
<use f='llvm/llvm/lib/MC/StringTableBuilder.cpp' l='31' u='r' c='_ZN4llvm18StringTableBuilder8initSizeEv'/>
<use f='llvm/llvm/lib/MC/StringTableBuilder.cpp' l='55' u='w' c='_ZN4llvm18StringTableBuilderC1ENS0_4KindEj'/>
<use f='llvm/llvm/lib/MC/StringTableBuilder.cpp' l='78' u='r' c='_ZNK4llvm18StringTableBuilder5writeEPh'/>
<use f='llvm/llvm/lib/MC/StringTableBuilder.cpp' l='80' u='r' c='_ZNK4llvm18StringTableBuilder5writeEPh'/>
<use f='llvm/llvm/lib/MC/StringTableBuilder.cpp' l='152' u='r' c='_ZN4llvm18StringTableBuilder19finalizeStringTableEb'/>
<use f='llvm/llvm/lib/MC/StringTableBuilder.cpp' l='163' u='r' c='_ZN4llvm18StringTableBuilder19finalizeStringTableEb'/>
<use f='llvm/llvm/lib/MC/StringTableBuilder.cpp' l='169' u='r' c='_ZN4llvm18StringTableBuilder19finalizeStringTableEb'/>
<use f='llvm/llvm/lib/MC/StringTableBuilder.cpp' l='169' u='r' c='_ZN4llvm18StringTableBuilder19finalizeStringTableEb'/>
<use f='llvm/llvm/lib/MC/StringTableBuilder.cpp' l='171' u='r' c='_ZN4llvm18StringTableBuilder19finalizeStringTableEb'/>
<use f='llvm/llvm/lib/MC/StringTableBuilder.cpp' l='171' u='r' c='_ZN4llvm18StringTableBuilder19finalizeStringTableEb'/>
<use f='llvm/llvm/lib/MC/StringTableBuilder.cpp' l='177' u='r' c='_ZN4llvm18StringTableBuilder19finalizeStringTableEb'/>
<use f='llvm/llvm/lib/MC/StringTableBuilder.cpp' l='177' u='r' c='_ZN4llvm18StringTableBuilder19finalizeStringTableEb'/>
<use f='llvm/llvm/lib/MC/StringTableBuilder.cpp' l='184' u='r' c='_ZN4llvm18StringTableBuilder19finalizeStringTableEb'/>
<use f='llvm/llvm/lib/MC/StringTableBuilder.cpp' l='201' u='r' c='_ZN4llvm18StringTableBuilder3addENS_19CachedHashStringRefE'/>
<use f='llvm/llvm/lib/MC/StringTableBuilder.cpp' l='209' u='r' c='_ZN4llvm18StringTableBuilder3addENS_19CachedHashStringRefE'/>
