<dec f='llvm/llvm/include/llvm/Object/SymbolSize.h' l='19' type='llvm::object::symbol_iterator'/>
<offset>0</offset>
<use f='llvm/llvm/lib/Object/SymbolSize.cpp' l='86' u='m' c='_ZN4llvm6object18computeSymbolSizesERKNS0_10ObjectFileE'/>
<use f='llvm/llvm/lib/Object/SymbolSize.cpp' l='101' u='m' c='_ZN4llvm6object18computeSymbolSizesERKNS0_10ObjectFileE'/>
<use f='llvm/llvm/lib/Object/SymbolSize.cpp' l='103' u='m' c='_ZN4llvm6object18computeSymbolSizesERKNS0_10ObjectFileE'/>
