<dec f='llvm/llvm/include/llvm/ProfileData/Coverage/CoverageMapping.h' l='152' type='llvm::coverage::Counter'/>
<use f='llvm/llvm/include/llvm/ProfileData/Coverage/CoverageMapping.h' l='155' u='w' c='_ZN4llvm8coverage17CounterExpressionC1ENS1_8ExprKindENS0_7CounterES3_'/>
<use f='llvm/llvm/include/llvm/ProfileData/Coverage/CoverageMapping.h' l='1045' u='m' c='_ZN4llvm12DenseMapInfoINS_8coverage17CounterExpressionEE12getHashValueERKS2_'/>
<use f='llvm/llvm/include/llvm/ProfileData/Coverage/CoverageMapping.h' l='1045' u='m' c='_ZN4llvm12DenseMapInfoINS_8coverage17CounterExpressionEE12getHashValueERKS2_'/>
<use f='llvm/llvm/include/llvm/ProfileData/Coverage/CoverageMapping.h' l='1051' u='r' c='_ZN4llvm12DenseMapInfoINS_8coverage17CounterExpressionEE7isEqualERKS2_S5_'/>
<use f='llvm/llvm/include/llvm/ProfileData/Coverage/CoverageMapping.h' l='1051' u='r' c='_ZN4llvm12DenseMapInfoINS_8coverage17CounterExpressionEE7isEqualERKS2_S5_'/>
<offset>32</offset>
<use f='llvm/llvm/lib/ProfileData/Coverage/CoverageMapping.cpp' l='67' u='r' c='_ZN4llvm8coverage24CounterExpressionBuilder12extractTermsENS0_7CounterEiRNS_15SmallVectorImplINS1_4TermEEE'/>
<use f='llvm/llvm/lib/ProfileData/Coverage/CoverageMapping.cpp' l='148' u='r' c='_ZNK4llvm8coverage21CounterMappingContext4dumpERKNS0_7CounterERNS_11raw_ostreamE'/>
<use f='llvm/llvm/lib/ProfileData/Coverage/CoverageMapping.cpp' l='177' u='r' c='_ZNK4llvm8coverage21CounterMappingContext8evaluateERKNS0_7CounterE'/>
<use f='llvm/llvm/lib/ProfileData/Coverage/CoverageMappingReader.cpp' l='356' u='a' c='_ZN4llvm8coverage24RawCoverageMappingReader4readEv'/>
<use f='llvm/llvm/lib/ProfileData/Coverage/CoverageMappingWriter.cpp' l='98' u='r' c='_ZN12_GLOBAL__N_127CounterExpressionsMinimizer4markEN4llvm8coverage7CounterE'/>
<use f='llvm/llvm/lib/ProfileData/Coverage/CoverageMappingWriter.cpp' l='108' u='r' c='_ZN12_GLOBAL__N_127CounterExpressionsMinimizer10gatherUsedEN4llvm8coverage7CounterE'/>
<use f='llvm/llvm/lib/ProfileData/Coverage/CoverageMappingWriter.cpp' l='184' u='r' c='_ZN4llvm8coverage21CoverageMappingWriter5writeERNS_11raw_ostreamE'/>
