<dec f='llvm/llvm/include/llvm/IR/LLVMRemarkStreamer.h' l='28' type='remarks::RemarkStreamer &amp;'/>
<use f='llvm/llvm/include/llvm/IR/LLVMRemarkStreamer.h' l='35' u='w' c='_ZN4llvm18LLVMRemarkStreamerC1ERNS_7remarks14RemarkStreamerE'/>
<offset>0</offset>
<use f='llvm/llvm/lib/IR/LLVMRemarkStreamer.cpp' l='79' u='m' c='_ZN4llvm18LLVMRemarkStreamer4emitERKNS_30DiagnosticInfoOptimizationBaseE'/>
<use f='llvm/llvm/lib/IR/LLVMRemarkStreamer.cpp' l='85' u='m' c='_ZN4llvm18LLVMRemarkStreamer4emitERKNS_30DiagnosticInfoOptimizationBaseE'/>
