<dec f='llvm/llvm/include/llvm/IR/PatternMatch.h' l='355' type='const llvm::APFloat *&amp;'/>
<use f='llvm/llvm/include/llvm/IR/PatternMatch.h' l='357' u='w' c='_ZN4llvm12PatternMatch11apf_pred_tyC1ERPKNS_7APFloatE'/>
<use f='llvm/llvm/include/llvm/IR/PatternMatch.h' l='362' u='w' c='_ZN4llvm12PatternMatch11apf_pred_ty5matchEPTL0__'/>
<use f='llvm/llvm/include/llvm/IR/PatternMatch.h' l='370' u='w' c='_ZN4llvm12PatternMatch11apf_pred_ty5matchEPTL0__'/>
