<dec f='llvm/llvm/lib/IR/LLVMContextImpl.h' l='632' type='uint8_t'/>
<use f='llvm/llvm/lib/IR/LLVMContextImpl.h' l='636' u='w' c='_ZN4llvm13MDNodeKeyImplINS_16DISubroutineTypeEEC1EjhPNS_8MetadataE'/>
<use f='llvm/llvm/lib/IR/LLVMContextImpl.h' l='638' u='w' c='_ZN4llvm13MDNodeKeyImplINS_16DISubroutineTypeEEC1EPKS1_'/>
<use f='llvm/llvm/lib/IR/LLVMContextImpl.h' l='641' u='r' c='_ZNK4llvm13MDNodeKeyImplINS_16DISubroutineTypeEE7isKeyOfEPKS1_'/>
<use f='llvm/llvm/lib/IR/LLVMContextImpl.h' l='645' u='r' c='_ZNK4llvm13MDNodeKeyImplINS_16DISubroutineTypeEE12getHashValueEv'/>
<offset>32</offset>
