<dec f='llvm/llvm/include/llvm/Analysis/LoopCacheAnalysis.h' l='271' type='llvm::raw_ostream &amp;'/>
<use f='llvm/llvm/include/llvm/Analysis/LoopCacheAnalysis.h' l='274' u='w' c='_ZN4llvm20LoopCachePrinterPassC1ERNS_11raw_ostreamE'/>
<use f='llvm/llvm/lib/Analysis/LoopCacheAnalysis.cpp' l='663' u='a' c='_ZN4llvm20LoopCachePrinterPass3runERNS_4LoopERNS_15AnalysisManagerIS1_JRNS_27LoopStandardAnalysisResultsEEEES5_RNS_10LPMUpdaterE'/>
<offset>0</offset>
