<dec f='llvm/llvm/include/llvm/IR/InstrTypes.h' l='1118' type='std::string'/>
<use f='llvm/llvm/include/llvm/IR/InstrTypes.h' l='1123' u='w' c='_ZN4llvm17OperandBundleDefTC1ENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESt6vectorIT_SaIS8_EE'/>
<use f='llvm/llvm/include/llvm/IR/InstrTypes.h' l='1125' u='w' c='_ZN4llvm17OperandBundleDefTC1ENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEENS_8ArrayRefIT_EE'/>
<use f='llvm/llvm/include/llvm/IR/InstrTypes.h' l='1128' u='w' c='_ZN4llvm17OperandBundleDefTC1ERKNS_16OperandBundleUseE'/>
<use f='llvm/llvm/include/llvm/IR/InstrTypes.h' l='1140' u='r' c='_ZNK4llvm17OperandBundleDefT6getTagEv'/>
