<use f='llvm/llvm/include/llvm/IR/LegacyPassManagers.h' l='140' u='m' c='_ZNK4llvm7PMStack5beginEv'/>
<use f='llvm/llvm/include/llvm/IR/LegacyPassManagers.h' l='141' u='m' c='_ZNK4llvm7PMStack3endEv'/>
<use f='llvm/llvm/include/llvm/IR/LegacyPassManagers.h' l='144' u='m' c='_ZNK4llvm7PMStack3topEv'/>
<use f='llvm/llvm/include/llvm/IR/LegacyPassManagers.h' l='146' u='m' c='_ZNK4llvm7PMStack5emptyEv'/>
<dec f='llvm/llvm/include/llvm/IR/LegacyPassManagers.h' l='151' type='std::vector&lt;PMDataManager *&gt;'/>
<offset>0</offset>
<use f='llvm/llvm/lib/IR/LegacyPassManager.cpp' l='1692' u='m' c='_ZN4llvm7PMStack3popEv'/>
<use f='llvm/llvm/lib/IR/LegacyPassManager.cpp' l='1716' u='m' c='_ZN4llvm7PMStack4pushEPNS_13PMDataManagerE'/>
<use f='llvm/llvm/lib/IR/LegacyPassManager.cpp' l='1721' c='_ZNK4llvm7PMStack4dumpEv'/>
<use f='llvm/llvm/lib/IR/LegacyPassManager.cpp' l='1724' u='m' c='_ZNK4llvm7PMStack4dumpEv'/>
