<dec f='llvm/build/lib/Target/Mips/MipsGenInstrInfo.inc' l='1821' type='1806'/>
<use f='llvm/llvm/lib/Target/Mips/AsmParser/MipsAsmParser.cpp' l='2952' u='r' c='_ZN12_GLOBAL__N_113MipsAsmParser23loadAndAddSymbolAddressEPKN4llvm6MCExprEjjbNS1_5SMLocERNS1_10MCStreamerEPKNS1_15MCSubtargetInfoE'/>
<use f='llvm/llvm/lib/Target/Mips/AsmParser/MipsAsmParser.cpp' l='2957' u='r' c='_ZN12_GLOBAL__N_113MipsAsmParser23loadAndAddSymbolAddressEPKN4llvm6MCExprEjjbNS1_5SMLocERNS1_10MCStreamerEPKNS1_15MCSubtargetInfoE'/>
<use f='llvm/llvm/lib/Target/Mips/AsmParser/MipsAsmParser.cpp' l='2997' u='r' c='_ZN12_GLOBAL__N_113MipsAsmParser23loadAndAddSymbolAddressEPKN4llvm6MCExprEjjbNS1_5SMLocERNS1_10MCStreamerEPKNS1_15MCSubtargetInfoE'/>
<use f='llvm/llvm/lib/Target/Mips/AsmParser/MipsAsmParser.cpp' l='3064' u='r' c='_ZN12_GLOBAL__N_113MipsAsmParser23loadAndAddSymbolAddressEPKN4llvm6MCExprEjjbNS1_5SMLocERNS1_10MCStreamerEPKNS1_15MCSubtargetInfoE'/>
<use f='llvm/llvm/lib/Target/Mips/AsmParser/MipsAsmParser.cpp' l='3300' u='r' c='_ZN12_GLOBAL__N_113MipsAsmParser18emitPartialAddressERN4llvm18MipsTargetStreamerENS1_5SMLocEPNS1_8MCSymbolE'/>
<use f='llvm/llvm/lib/Target/Mips/AsmParser/MipsAsmParser.cpp' l='3485' u='r' c='_ZN12_GLOBAL__N_113MipsAsmParser24expandLoadDoubleImmToGPRERN4llvm6MCInstENS1_5SMLocERNS1_10MCStreamerEPKNS1_15MCSubtargetInfoE'/>
<use f='llvm/build/lib/Target/Mips/MipsGenAsmMatcher.inc' l='6835'/>
<use f='llvm/build/lib/Target/Mips/MipsGenMCCodeEmitter.inc' l='6669' c='_ZNK4llvm17MipsMCCodeEmitter21getBinaryCodeForInstrERKNS_6MCInstERNS_15SmallVectorImplINS_7MCFixupEEERKNS_15MCSubtargetInfoE'/>
<use f='llvm/llvm/lib/Target/Mips/MCTargetDesc/MipsTargetStreamer.cpp' l='1297' u='r' c='_ZN4llvm21MipsTargetELFStreamer21emitDirectiveCpreturnEjb'/>
<use f='llvm/build/lib/Target/Mips/MipsGenDAGISel.inc' l='885' u='r' c='_ZN4llvm16MipsDAGToDAGISel10SelectCodeEPNS_6SDNodeE'/>
<use f='llvm/build/lib/Target/Mips/MipsGenDAGISel.inc' l='885' u='r' c='_ZN4llvm16MipsDAGToDAGISel10SelectCodeEPNS_6SDNodeE'/>
<use f='llvm/build/lib/Target/Mips/MipsGenDAGISel.inc' l='6671' u='r' c='_ZN4llvm16MipsDAGToDAGISel10SelectCodeEPNS_6SDNodeE'/>
<use f='llvm/build/lib/Target/Mips/MipsGenDAGISel.inc' l='6671' u='r' c='_ZN4llvm16MipsDAGToDAGISel10SelectCodeEPNS_6SDNodeE'/>
<use f='llvm/llvm/lib/Target/Mips/MipsBranchExpansion.cpp' l='625' u='r' c='_ZN12_GLOBAL__N_119MipsBranchExpansion18expandToLongBranchERNS_7MBBInfoE'/>
<use f='llvm/llvm/lib/Target/Mips/MipsISelLowering.cpp' l='4799' u='r' c='_ZNK4llvm18MipsTargetLowering9emitLDR_DERNS_12MachineInstrEPNS_17MachineBasicBlockE'/>
<use f='llvm/llvm/lib/Target/Mips/MipsSEInstrInfo.cpp' l='49' u='r' c='_ZNK4llvm15MipsSEInstrInfo19isLoadFromStackSlotERKNS_12MachineInstrERi'/>
<use f='llvm/llvm/lib/Target/Mips/MipsSEInstrInfo.cpp' l='335' u='r' c='_ZNK4llvm15MipsSEInstrInfo16loadRegFromStackERNS_17MachineBasicBlockENS_26MachineInstrBundleIteratorINS_12MachineInstrELb0EEENS_8RegisterEiPKNS_19Targ15511294'/>
<use f='llvm/llvm/lib/Target/Mips/MipsSEInstrInfo.cpp' l='364' u='r' c='_ZNK4llvm15MipsSEInstrInfo16loadRegFromStackERNS_17MachineBasicBlockENS_26MachineInstrBundleIteratorINS_12MachineInstrELb0EEENS_8RegisterEiPKNS_19Targ15511294'/>
<use f='llvm/llvm/lib/Target/Mips/MipsSEInstrInfo.cpp' l='368' u='r' c='_ZNK4llvm15MipsSEInstrInfo16loadRegFromStackERNS_17MachineBasicBlockENS_26MachineInstrBundleIteratorINS_12MachineInstrELb0EEENS_8RegisterEiPKNS_19Targ15511294'/>
