<use f='llvm/llvm/include/llvm/CodeGen/CodeGenPassBuilder.h' l='205' u='w' c='_ZN4llvm18CodeGenPassBuilder14AddMachinePassC1ERNS_26MachineFunctionPassManagerE'/>
<use f='llvm/llvm/include/llvm/CodeGen/CodeGenPassBuilder.h' l='214' u='c' c='_ZN4llvm18CodeGenPassBuilder14AddMachinePassclEOTL0__'/>
<use f='llvm/llvm/include/llvm/CodeGen/CodeGenPassBuilder.h' l='232' u='a' c='_ZN4llvm18CodeGenPassBuilder14AddMachinePass9releasePMEv'/>
<dec f='llvm/llvm/include/llvm/CodeGen/CodeGenPassBuilder.h' l='235' type='llvm::MachineFunctionPassManager &amp;'/>
