<dec f='llvm/build/lib/Target/Mips/MipsGenRegisterInfo.inc' l='28' type='8'/>
<use f='llvm/llvm/lib/Target/Mips/AsmParser/MipsAsmParser.cpp' l='3256' u='r' c='_ZL7nextRegj'/>
<use f='llvm/llvm/lib/Target/Mips/AsmParser/MipsAsmParser.cpp' l='3257' c='_ZL7nextRegj'/>
<use f='llvm/llvm/lib/Target/Mips/AsmParser/MipsAsmParser.cpp' l='5609' u='r' c='_ZL20getRegisterForMxtrFPRN4llvm6MCInstEb'/>
<use f='llvm/llvm/lib/Target/Mips/AsmParser/MipsAsmParser.cpp' l='5648' u='r' c='_ZL20getRegisterForMxtrC0RN4llvm6MCInstEb'/>
<use f='llvm/llvm/lib/Target/Mips/AsmParser/MipsAsmParser.cpp' l='6833' u='r' c='_ZN12_GLOBAL__N_113MipsAsmParser17parseRegisterListERN4llvm15SmallVectorImplISt10unique_ptrINS1_18MCParsedAsmOperandESt14default_deleteIS4_EEEE'/>
<use f='llvm/llvm/lib/Target/Mips/AsmParser/MipsAsmParser.cpp' l='6842' u='r' c='_ZN12_GLOBAL__N_113MipsAsmParser17parseRegisterListERN4llvm15SmallVectorImplISt10unique_ptrINS1_18MCParsedAsmOperandESt14default_deleteIS4_EEEE'/>
<use f='llvm/build/lib/Target/Mips/MipsGenAsmMatcher.inc' l='4231' c='_ZL20validateOperandClassRN4llvm18MCParsedAsmOperandEN12_GLOBAL__N_114MatchClassKindE'/>
<use f='llvm/llvm/lib/Target/Mips/Disassembler/MipsDisassembler.cpp' l='2427' u='r' c='_ZL20DecodeRegListOperandRN4llvm6MCInstEjmPKv'/>
<use f='llvm/llvm/lib/Target/Mips/MCTargetDesc/MipsABIInfo.cpp' l='78' u='r' c='_ZNK4llvm11MipsABIInfo11GetFramePtrEv'/>
<use f='llvm/llvm/lib/Target/Mips/MicroMipsSizeReduction.cpp' l='384' u='r' c='_ZL20ConsecutiveRegistersjj'/>
<use f='llvm/llvm/lib/Target/Mips/MipsISelLowering.cpp' l='2502' u='r' c='_ZNK4llvm18MipsTargetLowering14lowerFRAMEADDRENS_7SDValueERNS_12SelectionDAGE'/>
<use f='llvm/llvm/lib/Target/Mips/MipsRegisterInfo.cpp' l='195' u='r' c='_ZNK4llvm16MipsRegisterInfo15getReservedRegsERKNS_15MachineFunctionE'/>
<use f='llvm/llvm/lib/Target/Mips/MipsRegisterInfo.cpp' l='285' u='r' c='_ZNK4llvm16MipsRegisterInfo16getFrameRegisterERKNS_15MachineFunctionE'/>
<use f='llvm/llvm/lib/Target/Mips/MipsRegisterInfo.cpp' l='301' u='r' c='_ZNK4llvm16MipsRegisterInfo15canRealignStackERKNS_15MachineFunctionE'/>
