<dec f='llvm/llvm/include/llvm/TableGen/Record.h' l='777' type='14'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='999' c='_ZNK4llvm9BinOpInit4FoldEPNS_6RecordE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='1014' c='_ZNK4llvm9BinOpInit4FoldEPNS_6RecordE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='1032' c='_ZNK4llvm9BinOpInit4FoldEPNS_6RecordE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='1044' u='r' c='_ZNK4llvm9BinOpInit4FoldEPNS_6RecordE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='1048' u='r' c='_ZNK4llvm9BinOpInit4FoldEPNS_6RecordE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='1127' c='_ZNK4llvm9BinOpInit11getAsStringB5cxx11Ev'/>
<use f='llvm/llvm/lib/TableGen/TGParser.cpp' l='1117' u='r' c='_ZN4llvm8TGParser14ParseOperationEPNS_6RecordEPNS_5RecTyE'/>
<use f='llvm/llvm/lib/TableGen/TGParser.cpp' l='1245' c='_ZN4llvm8TGParser14ParseOperationEPNS_6RecordEPNS_5RecTyE'/>
