<dec f='llvm/llvm/lib/Target/ARM/Utils/ARMBaseInfo.h' l='32' type='1'/>
<use f='llvm/llvm/lib/Target/ARM/Utils/ARMBaseInfo.h' l='51' u='r' c='_ZN4llvm5ARMCCL20getOppositeConditionENS0_9CondCodesE'/>
<use f='llvm/llvm/lib/Target/ARM/Utils/ARMBaseInfo.h' l='52' c='_ZN4llvm5ARMCCL20getOppositeConditionENS0_9CondCodesE'/>
<use f='llvm/llvm/lib/Target/ARM/Utils/ARMBaseInfo.h' l='75' c='_ZN4llvm5ARMCCL19getSwappedConditionENS0_9CondCodesE'/>
<use f='llvm/llvm/lib/Target/ARM/Utils/ARMBaseInfo.h' l='75' u='r' c='_ZN4llvm5ARMCCL19getSwappedConditionENS0_9CondCodesE'/>
<use f='llvm/llvm/lib/Target/ARM/Utils/ARMBaseInfo.h' l='149' c='_ZN4llvmL19ARMCondCodeToStringENS_5ARMCC9CondCodesE'/>
<use f='llvm/llvm/lib/Target/ARM/Utils/ARMBaseInfo.h' l='170' u='r' c='_ZN4llvmL21ARMCondCodeFromStringENS_9StringRefE'/>
<doc f='llvm/llvm/lib/Target/ARM/Utils/ARMBaseInfo.h' l='32'>// Not equal                  Not equal, or unordered</doc>
<use f='llvm/llvm/lib/Target/ARM/MVETailPredUtils.h' l='150' u='r' c='_ZN4llvm13RevertLoopEndEPNS_12MachineInstrEPKNS_15TargetInstrInfoEjb'/>
<use f='llvm/llvm/lib/Target/ARM/ARMBaseInstrInfo.cpp' l='3206' c='_ZNK4llvm16ARMBaseInstrInfo20optimizeCompareInstrERNS_12MachineInstrENS_8RegisterES3_iiPKNS_19MachineRegisterInfoE'/>
<use f='llvm/llvm/lib/Target/ARM/ARMConstantIslandPass.cpp' l='1889' u='r' c='_ZN12_GLOBAL__N_118ARMConstantIslands22optimizeThumb2BranchesEv'/>
<use f='llvm/llvm/lib/Target/ARM/ARMExpandPseudoInsts.cpp' l='1607' u='r' c='_ZN12_GLOBAL__N_115ARMExpandPseudo14ExpandCMP_SWAPERN4llvm17MachineBasicBlockENS1_26MachineInstrBundleIteratorINS1_12MachineInstrELb0EEEjjjRS6_'/>
<use f='llvm/llvm/lib/Target/ARM/ARMExpandPseudoInsts.cpp' l='1630' u='r' c='_ZN12_GLOBAL__N_115ARMExpandPseudo14ExpandCMP_SWAPERN4llvm17MachineBasicBlockENS1_26MachineInstrBundleIteratorINS1_12MachineInstrELb0EEEjjjRS6_'/>
<use f='llvm/llvm/lib/Target/ARM/ARMExpandPseudoInsts.cpp' l='1728' u='r' c='_ZN12_GLOBAL__N_115ARMExpandPseudo17ExpandCMP_SWAP_64ERN4llvm17MachineBasicBlockENS1_26MachineInstrBundleIteratorINS1_12MachineInstrELb0EEERS6_'/>
<use f='llvm/llvm/lib/Target/ARM/ARMExpandPseudoInsts.cpp' l='1750' u='r' c='_ZN12_GLOBAL__N_115ARMExpandPseudo17ExpandCMP_SWAP_64ERN4llvm17MachineBasicBlockENS1_26MachineInstrBundleIteratorINS1_12MachineInstrELb0EEERS6_'/>
<use f='llvm/llvm/lib/Target/ARM/ARMFastISel.cpp' l='1218' u='r' c='_ZL14getComparePredN4llvm7CmpInst9PredicateE'/>
<use f='llvm/llvm/lib/Target/ARM/ARMFastISel.cpp' l='1271' u='r' c='_ZN12_GLOBAL__N_111ARMFastISel12SelectBranchEPKN4llvm11InstructionE'/>
<use f='llvm/llvm/lib/Target/ARM/ARMFastISel.cpp' l='1309' u='r' c='_ZN12_GLOBAL__N_111ARMFastISel12SelectBranchEPKN4llvm11InstructionE'/>
<use f='llvm/llvm/lib/Target/ARM/ARMFastISel.cpp' l='1665' u='r' c='_ZN12_GLOBAL__N_111ARMFastISel12SelectSelectEPKN4llvm11InstructionE'/>
<use f='llvm/llvm/lib/Target/ARM/ARMISelDAGToDAG.cpp' l='3823' c='_ZN12_GLOBAL__N_115ARMDAGToDAGISel6SelectEPN4llvm6SDNodeE'/>
<use f='llvm/llvm/lib/Target/ARM/ARMISelDAGToDAG.cpp' l='3900' c='_ZN12_GLOBAL__N_115ARMDAGToDAGISel6SelectEPN4llvm6SDNodeE'/>
<use f='llvm/llvm/lib/Target/ARM/ARMISelLowering.cpp' l='1937' u='r' c='_ZL12IntCCToARMCCN4llvm3ISD8CondCodeE'/>
<use f='llvm/llvm/lib/Target/ARM/ARMISelLowering.cpp' l='1975' u='r' c='_ZL11FPCCToARMCCN4llvm3ISD8CondCodeERNS_5ARMCC9CondCodesES4_'/>
<use f='llvm/llvm/lib/Target/ARM/ARMISelLowering.cpp' l='4626' c='_ZNK4llvm17ARMTargetLowering9getARMCmpENS_7SDValueES1_NS_3ISD8CondCodeERS1_RNS_12SelectionDAGERKNS_5SDLocE'/>
<use f='llvm/llvm/lib/Target/ARM/ARMISelLowering.cpp' l='5268' u='r' c='_ZNK4llvm17ARMTargetLowering14LowerSELECT_CCENS_7SDValueERNS_12SelectionDAGE'/>
<use f='llvm/llvm/lib/Target/ARM/ARMISelLowering.cpp' l='6447' u='r' c='_ZL11LowerVSETCCN4llvm7SDValueERNS_12SelectionDAGEPKNS_12ARMSubtargetE'/>
<use f='llvm/llvm/lib/Target/ARM/ARMISelLowering.cpp' l='6496' u='r' c='_ZL11LowerVSETCCN4llvm7SDValueERNS_12SelectionDAGEPKNS_12ARMSubtargetE'/>
<use f='llvm/llvm/lib/Target/ARM/ARMISelLowering.cpp' l='8139' u='r' c='_ZL22LowerVECTOR_SHUFFLE_i1N4llvm7SDValueERNS_12SelectionDAGEPKNS_12ARMSubtargetE'/>
<use f='llvm/llvm/lib/Target/ARM/ARMISelLowering.cpp' l='8580' u='r' c='_ZL22LowerCONCAT_VECTORS_i1N4llvm7SDValueERNS_12SelectionDAGEPKNS_12ARMSubtargetE'/>
<use f='llvm/llvm/lib/Target/ARM/ARMISelLowering.cpp' l='8642' u='r' c='_ZL22LowerEXTRACT_SUBVECTORN4llvm7SDValueERNS_12SelectionDAGEPKNS_12ARMSubtargetE'/>
<use f='llvm/llvm/lib/Target/ARM/ARMISelLowering.cpp' l='10809' u='r' c='_ZNK4llvm17ARMTargetLowering15EmitStructByvalERNS_12MachineInstrEPNS_17MachineBasicBlockE'/>
<use f='llvm/llvm/lib/Target/ARM/ARMISelLowering.cpp' l='11158' u='r' c='_ZNK4llvm17ARMTargetLowering27EmitInstrWithCustomInserterERNS_12MachineInstrEPNS_17MachineBasicBlockE'/>
<use f='llvm/llvm/lib/Target/ARM/ARMISelLowering.cpp' l='13229' c='_ZL14isValidMVECondjb'/>
<use f='llvm/llvm/lib/Target/ARM/ARMISelLowering.cpp' l='16088' u='r' c='_ZNK4llvm17ARMTargetLowering20PerformBRCONDCombineEPNS_6SDNodeERNS_12SelectionDAGE'/>
<use f='llvm/llvm/lib/Target/ARM/ARMISelLowering.cpp' l='16151' u='r' c='_ZNK4llvm17ARMTargetLowering18PerformCMOVCombineEPNS_6SDNodeERNS_12SelectionDAGE'/>
<use f='llvm/llvm/lib/Target/ARM/ARMISelLowering.cpp' l='16163' u='r' c='_ZNK4llvm17ARMTargetLowering18PerformCMOVCombineEPNS_6SDNodeERNS_12SelectionDAGE'/>
<use f='llvm/llvm/lib/Target/ARM/ARMISelLowering.cpp' l='16209' u='r' c='_ZNK4llvm17ARMTargetLowering18PerformCMOVCombineEPNS_6SDNodeERNS_12SelectionDAGE'/>
<use f='llvm/llvm/lib/Target/ARM/ARMISelLowering.cpp' l='16232' u='r' c='_ZNK4llvm17ARMTargetLowering18PerformCMOVCombineEPNS_6SDNodeERNS_12SelectionDAGE'/>
<use f='llvm/llvm/lib/Target/ARM/ARMISelLowering.cpp' l='16252' u='r' c='_ZNK4llvm17ARMTargetLowering18PerformCMOVCombineEPNS_6SDNodeERNS_12SelectionDAGE'/>
<use f='llvm/llvm/lib/Target/ARM/ARMInstructionSelector.cpp' l='443' u='r' c='_ZL15getComparePredsN4llvm7CmpInst9PredicateE'/>
<use f='llvm/llvm/lib/Target/ARM/ARMInstructionSelector.cpp' l='1154' u='r' c='_ZN12_GLOBAL__N_122ARMInstructionSelector6selectERN4llvm12MachineInstrE'/>
<use f='llvm/llvm/lib/Target/ARM/ARMLowOverheadLoops.cpp' l='1393' u='r' c='_ZNK12_GLOBAL__N_119ARMLowOverheadLoops16RevertLoopEndDecEPN4llvm12MachineInstrE'/>
<use f='llvm/llvm/lib/Target/ARM/AsmParser/ARMAsmParser.cpp' l='2362' u='r' c='_ZNK12_GLOBAL__N_110ARMOperand23isITCondCodeRestrictedIEv'/>
<use f='llvm/llvm/lib/Target/ARM/AsmParser/ARMAsmParser.cpp' l='2384' u='r' c='_ZNK12_GLOBAL__N_110ARMOperand24isITCondCodeRestrictedFPEv'/>
<use f='llvm/llvm/lib/Target/ARM/AsmParser/ARMAsmParser.cpp' l='7179' u='r' c='_ZN12_GLOBAL__N_112ARMAsmParser16ParseInstructionERN4llvm20ParseInstructionInfoENS1_9StringRefENS1_5SMLocERNS1_15SmallVectorImplISt10unique_ptrINS1_1892611'/>
<use f='llvm/llvm/lib/Target/ARM/Disassembler/ARMDisassembler.cpp' l='6227' u='r' c='_ZL33DecodeRestrictedIPredicateOperandRN4llvm6MCInstEjmPKv'/>
<use f='llvm/llvm/lib/Target/ARM/Disassembler/ARMDisassembler.cpp' l='6273' u='r' c='_ZL34DecodeRestrictedFPPredicateOperandRN4llvm6MCInstEjmPKv'/>
<use f='llvm/llvm/lib/Target/ARM/MCTargetDesc/ARMMCCodeEmitter.cpp' l='1965' c='_ZNK12_GLOBAL__N_116ARMMCCodeEmitter28getRestrictedCondCodeOpValueERKN4llvm6MCInstEjRNS1_15SmallVectorImplINS1_7MCFixupEEERKNS1_15MCSubtargetInfoE'/>
