<dec f='llvm/llvm/tools/llvm-objcopy/CopyConfig.h' l='104' type='std::shared_ptr&lt;GlobPattern&gt;'/>
<use f='llvm/llvm/tools/llvm-objcopy/CopyConfig.h' l='110' u='w' c='_ZN4llvm7objcopy13NameOrPatternC1ESt10shared_ptrINS_11GlobPatternEEb'/>
<use f='llvm/llvm/tools/llvm-objcopy/CopyConfig.h' l='121' u='m' c='_ZNK4llvm7objcopy13NameOrPatterneqENS_9StringRefE'/>
<use f='llvm/llvm/tools/llvm-objcopy/CopyConfig.h' l='121' u='m' c='_ZNK4llvm7objcopy13NameOrPatterneqENS_9StringRefE'/>
<offset>256</offset>
