<dec f='llvm/llvm/include/llvm/TableGen/Record.h' l='781' type='llvm::Init *'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='784' u='w' c='_ZN4llvm9BinOpInitC1ENS0_8BinaryOpEPNS_4InitES3_PNS_5RecTyE'/>
<use f='llvm/llvm/include/llvm/TableGen/Record.h' l='818' u='r' c='_ZNK4llvm9BinOpInit6getLHSEv'/>
<offset>256</offset>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='927' u='r' c='_ZNK4llvm9BinOpInit4FoldEPNS_6RecordE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='959' u='r' c='_ZNK4llvm9BinOpInit4FoldEPNS_6RecordE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='970' u='r' c='_ZNK4llvm9BinOpInit4FoldEPNS_6RecordE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='979' u='r' c='_ZNK4llvm9BinOpInit4FoldEPNS_6RecordE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='986' u='r' c='_ZNK4llvm9BinOpInit4FoldEPNS_6RecordE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='1007' u='r' c='_ZNK4llvm9BinOpInit4FoldEPNS_6RecordE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='1026' u='r' c='_ZNK4llvm9BinOpInit4FoldEPNS_6RecordE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='1045' u='r' c='_ZNK4llvm9BinOpInit4FoldEPNS_6RecordE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='1055' u='r' c='_ZNK4llvm9BinOpInit4FoldEPNS_6RecordE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='1078' u='r' c='_ZNK4llvm9BinOpInit4FoldEPNS_6RecordE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='1105' u='r' c='_ZNK4llvm9BinOpInit17resolveReferencesERNS_8ResolverE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='1108' u='r' c='_ZNK4llvm9BinOpInit17resolveReferencesERNS_8ResolverE'/>
<use f='llvm/llvm/lib/TableGen/Record.cpp' l='1139' u='r' c='_ZNK4llvm9BinOpInit11getAsStringB5cxx11Ev'/>
