<dec f='llvm/build/lib/Target/Mips/MipsGenInstrInfo.inc' l='2683' type='2668'/>
<use f='llvm/llvm/lib/Target/Mips/AsmParser/MipsAsmParser.cpp' l='5283' u='r' c='_ZN12_GLOBAL__N_113MipsAsmParser21expandLoadStoreDMacroERN4llvm6MCInstENS1_5SMLocERNS1_10MCStreamerEPKNS1_15MCSubtargetInfoEb'/>
<use f='llvm/build/lib/Target/Mips/MipsGenAsmMatcher.inc' l='7944'/>
<use f='llvm/build/lib/Target/Mips/MipsGenMCCodeEmitter.inc' l='6707' c='_ZNK4llvm17MipsMCCodeEmitter21getBinaryCodeForInstrERKNS_6MCInstERNS_15SmallVectorImplINS_7MCFixupEEERKNS_15MCSubtargetInfoE'/>
<use f='llvm/llvm/lib/Target/Mips/MCTargetDesc/MipsNaClELFStreamer.cpp' l='237' c='_ZN4llvm28isBasePlusOffsetMemoryAccessEjPjPb'/>
<use f='llvm/llvm/lib/Target/Mips/MCTargetDesc/MipsTargetStreamer.cpp' l='1219' u='r' c='_ZN4llvm21MipsTargetELFStreamer22emitDirectiveCpRestoreEiNS_12function_refIFjvEEENS_5SMLocEPKNS_15MCSubtargetInfoE'/>
<use f='llvm/llvm/lib/Target/Mips/MicroMipsSizeReduction.cpp' l='266' u='r'/>
<use f='llvm/llvm/lib/Target/Mips/MicroMipsSizeReduction.cpp' l='268' u='r'/>
<use f='llvm/llvm/lib/Target/Mips/MicroMipsSizeReduction.cpp' l='360' u='r' c='_ZL13CheckXWPInstrPN4llvm12MachineInstrEbRKN12_GLOBAL__N_111ReduceEntryE'/>
<use f='llvm/build/lib/Target/Mips/MipsGenDAGISel.inc' l='183' u='r' c='_ZN4llvm16MipsDAGToDAGISel10SelectCodeEPNS_6SDNodeE'/>
<use f='llvm/build/lib/Target/Mips/MipsGenDAGISel.inc' l='183' u='r' c='_ZN4llvm16MipsDAGToDAGISel10SelectCodeEPNS_6SDNodeE'/>
<use f='llvm/build/lib/Target/Mips/MipsGenDAGISel.inc' l='220' u='r' c='_ZN4llvm16MipsDAGToDAGISel10SelectCodeEPNS_6SDNodeE'/>
<use f='llvm/build/lib/Target/Mips/MipsGenDAGISel.inc' l='220' u='r' c='_ZN4llvm16MipsDAGToDAGISel10SelectCodeEPNS_6SDNodeE'/>
<use f='llvm/build/lib/Target/Mips/MipsGenDAGISel.inc' l='552' u='r' c='_ZN4llvm16MipsDAGToDAGISel10SelectCodeEPNS_6SDNodeE'/>
<use f='llvm/build/lib/Target/Mips/MipsGenDAGISel.inc' l='552' u='r' c='_ZN4llvm16MipsDAGToDAGISel10SelectCodeEPNS_6SDNodeE'/>
<use f='llvm/build/lib/Target/Mips/MipsGenDAGISel.inc' l='567' u='r' c='_ZN4llvm16MipsDAGToDAGISel10SelectCodeEPNS_6SDNodeE'/>
<use f='llvm/build/lib/Target/Mips/MipsGenDAGISel.inc' l='567' u='r' c='_ZN4llvm16MipsDAGToDAGISel10SelectCodeEPNS_6SDNodeE'/>
<use f='llvm/build/lib/Target/Mips/MipsGenDAGISel.inc' l='6707' u='r' c='_ZN4llvm16MipsDAGToDAGISel10SelectCodeEPNS_6SDNodeE'/>
<use f='llvm/build/lib/Target/Mips/MipsGenDAGISel.inc' l='6707' u='r' c='_ZN4llvm16MipsDAGToDAGISel10SelectCodeEPNS_6SDNodeE'/>
<use f='llvm/llvm/lib/Target/Mips/MipsBranchExpansion.cpp' l='468' u='r' c='_ZN12_GLOBAL__N_119MipsBranchExpansion18expandToLongBranchERNS_7MBBInfoE'/>
<use f='llvm/llvm/lib/Target/Mips/MipsFastISel.cpp' l='826' u='r' c='_ZN12_GLOBAL__N_112MipsFastISel9emitStoreEN4llvm3MVTEjRNS0_7AddressEj'/>
<use f='llvm/llvm/lib/Target/Mips/MipsISelLowering.cpp' l='4888' u='r' c='_ZNK4llvm18MipsTargetLowering9emitSTR_WERNS_12MachineInstrEPNS_17MachineBasicBlockE'/>
<use f='llvm/llvm/lib/Target/Mips/MipsISelLowering.cpp' l='4960' u='r' c='_ZNK4llvm18MipsTargetLowering9emitSTR_DERNS_12MachineInstrEPNS_17MachineBasicBlockE'/>
<use f='llvm/llvm/lib/Target/Mips/MipsISelLowering.cpp' l='4964' u='r' c='_ZNK4llvm18MipsTargetLowering9emitSTR_DERNS_12MachineInstrEPNS_17MachineBasicBlockE'/>
<use f='llvm/llvm/lib/Target/Mips/MipsInstructionSelector.cpp' l='199' u='r' c='_ZNK12_GLOBAL__N_123MipsInstructionSelector21selectLoadStoreOpCodeERN4llvm12MachineInstrERNS1_19MachineRegisterInfoE'/>
<use f='llvm/llvm/lib/Target/Mips/MipsInstructionSelector.cpp' l='916' u='r' c='_ZN12_GLOBAL__N_123MipsInstructionSelector6selectERN4llvm12MachineInstrE'/>
<use f='llvm/llvm/lib/Target/Mips/MipsSEInstrInfo.cpp' l='71' u='r' c='_ZNK4llvm15MipsSEInstrInfo18isStoreToStackSlotERKNS_12MachineInstrERi'/>
<use f='llvm/llvm/lib/Target/Mips/MipsSEInstrInfo.cpp' l='255' u='r' c='_ZNK4llvm15MipsSEInstrInfo15storeRegToStackERNS_17MachineBasicBlockENS_26MachineInstrBundleIteratorINS_12MachineInstrELb0EEENS_8RegisterEbiPKNS_19Targ4808487'/>
<use f='llvm/llvm/lib/Target/Mips/MipsSEInstrInfo.cpp' l='284' u='r' c='_ZNK4llvm15MipsSEInstrInfo15storeRegToStackERNS_17MachineBasicBlockENS_26MachineInstrBundleIteratorINS_12MachineInstrELb0EEENS_8RegisterEbiPKNS_19Targ4808487'/>
<use f='llvm/llvm/lib/Target/Mips/MipsSEInstrInfo.cpp' l='288' u='r' c='_ZNK4llvm15MipsSEInstrInfo15storeRegToStackERNS_17MachineBasicBlockENS_26MachineInstrBundleIteratorINS_12MachineInstrELb0EEENS_8RegisterEbiPKNS_19Targ4808487'/>
