<use f='llvm/llvm/include/llvm/IR/InstrTypes.h' l='1998' u='r' c='_ZNK4llvm8CallBase27hasClobberingOperandBundlesEv'/>
<use f='llvm/llvm/include/llvm/IR/InstrTypes.h' l='1999' u='r' c='_ZNK4llvm8CallBase27hasClobberingOperandBundlesEv'/>
<dec f='llvm/llvm/include/llvm/IR/InstrTypes.h' l='2079' type='StringMapEntry&lt;uint32_t&gt; *'/>
<use f='llvm/llvm/include/llvm/IR/InstrTypes.h' l='2090' u='r' c='_ZNK4llvm8CallBase12BundleOpInfoeqERKS1_'/>
<use f='llvm/llvm/include/llvm/IR/InstrTypes.h' l='2090' u='r' c='_ZNK4llvm8CallBase12BundleOpInfoeqERKS1_'/>
<use f='llvm/llvm/include/llvm/IR/InstrTypes.h' l='2100' u='r' c='_ZNK4llvm8CallBase29operandBundleFromBundleOpInfoERKNS0_12BundleOpInfoE'/>
<offset>0</offset>
<doc f='llvm/llvm/include/llvm/IR/InstrTypes.h' l='2077'>/// The operand bundle tag, interned by
    /// LLVMContextImpl::getOrInsertBundleTag.</doc>
<use f='llvm/llvm/lib/Analysis/AssumeBundleQueries.cpp' l='59' u='r' c='_ZN4llvm20hasAttributeInAssumeERNS_8CallInstEPNS_5ValueENS_9StringRefEPm'/>
<use f='llvm/llvm/lib/Analysis/AssumeBundleQueries.cpp' l='81' u='r' c='_ZN4llvm17fillMapFromAssumeERNS_8CallInstERNS_8DenseMapISt4pairIPNS_5ValueENS_9Attribute8AttrKindEENS2_IPNS_13IntrinsicInstENS_6MinMaxENS_12DenseMapIn7147981'/>
<use f='llvm/llvm/lib/Analysis/AssumeBundleQueries.cpp' l='108' u='r' c='_ZN4llvm22getKnowledgeFromBundleERNS_8CallInstERKNS_8CallBase12BundleOpInfoE'/>
<use f='llvm/llvm/lib/Analysis/AssumeBundleQueries.cpp' l='140' u='r' c='_ZN4llvm23isAssumeWithEmptyBundleERNS_8CallInstE'/>
<use f='llvm/llvm/lib/IR/Instructions.cpp' l='368' u='w' c='_ZN4llvm8CallBase26populateBundleOperandInfosENS_8ArrayRefINS_17OperandBundleDefTIPNS_5ValueEEEEEj'/>
<use f='llvm/llvm/lib/IR/Value.cpp' l='212' u='w' c='_ZN4llvm5Value16dropDroppableUseERNS_3UseE'/>
<use f='llvm/llvm/lib/IR/Verifier.cpp' l='4546' u='r' c='_ZN12_GLOBAL__N_18Verifier18visitIntrinsicCallEjRN4llvm8CallBaseE'/>
<use f='llvm/llvm/lib/IR/Verifier.cpp' l='4547' u='r' c='_ZN12_GLOBAL__N_18Verifier18visitIntrinsicCallEjRN4llvm8CallBaseE'/>
<use f='llvm/llvm/lib/IR/Verifier.cpp' l='4550' u='r' c='_ZN12_GLOBAL__N_18Verifier18visitIntrinsicCallEjRN4llvm8CallBaseE'/>
<use f='llvm/llvm/lib/Transforms/Utils/AssumeBundleBuilder.cpp' l='384' u='w' c='_ZN12_GLOBAL__N_114AssumeSimplify22dropRedundantKnowledgeEv'/>
<use f='llvm/llvm/lib/Transforms/Utils/AssumeBundleBuilder.cpp' l='386' u='r' c='_ZN12_GLOBAL__N_114AssumeSimplify22dropRedundantKnowledgeEv'/>
