<dec f='llvm/build/lib/Target/X86/X86GenRegisterInfo.inc' l='57' type='37'/>
<use f='llvm/llvm/lib/Target/X86/MCTargetDesc/X86BaseInfo.h' l='390' c='_ZN4llvm3X8630getSegmentOverridePrefixForRegEj'/>
<use f='llvm/build/lib/Target/X86/X86GenAsmMatcher.inc' l='7430' c='_ZL20validateOperandClassRN4llvm18MCParsedAsmOperandEN12_GLOBAL__N_114MatchClassKindE'/>
<use f='llvm/llvm/lib/Target/X86/Disassembler/X86Disassembler.cpp' l='1773' macro='1' u='r' c='_ZL17translateRegisterRN4llvm6MCInstENS_15X86Disassembler3RegE'/>
<use f='llvm/llvm/lib/Target/X86/Disassembler/X86Disassembler.cpp' l='1827'/>
<use f='llvm/llvm/lib/Target/X86/Disassembler/X86Disassembler.cpp' l='2010' macro='1' u='r' c='_ZL19translateRMRegisterRN4llvm6MCInstERNS_15X86Disassembler19InternalInstructionE'/>
<use f='llvm/llvm/lib/Target/X86/X86FrameLowering.cpp' l='865' u='r' c='_ZNK4llvm16X86FrameLowering36emitStackProbeInlineWindowsCoreCLR64ERNS_15MachineFunctionERNS_17MachineBasicBlockENS_26MachineInstrBundleIteratorINS_12M2458809'/>
<use f='llvm/llvm/lib/Target/X86/X86FrameLowering.cpp' l='2703' u='r' c='_ZNK4llvm16X86FrameLowering24adjustForSegmentedStacksERNS_15MachineFunctionERNS_17MachineBasicBlockE'/>
<use f='llvm/llvm/lib/Target/X86/X86FrameLowering.cpp' l='2706' u='r' c='_ZNK4llvm16X86FrameLowering24adjustForSegmentedStacksERNS_15MachineFunctionERNS_17MachineBasicBlockE'/>
<use f='llvm/llvm/lib/Target/X86/X86FrameLowering.cpp' l='2728' u='r' c='_ZNK4llvm16X86FrameLowering24adjustForSegmentedStacksERNS_15MachineFunctionERNS_17MachineBasicBlockE'/>
<use f='llvm/llvm/lib/Target/X86/X86FrameLowering.cpp' l='2731' u='r' c='_ZNK4llvm16X86FrameLowering24adjustForSegmentedStacksERNS_15MachineFunctionERNS_17MachineBasicBlockE'/>
<use f='llvm/llvm/lib/Target/X86/X86ISelDAGToDAG.cpp' l='1639' u='r' c='_ZN12_GLOBAL__N_115X86DAGToDAGISel18matchLoadInAddressEPN4llvm10LoadSDNodeERNS_18X86ISelAddressModeEb'/>
<use f='llvm/llvm/lib/Target/X86/X86ISelDAGToDAG.cpp' l='2498' u='r' c='_ZN12_GLOBAL__N_115X86DAGToDAGISel16selectVectorAddrEPN4llvm9MemSDNodeENS1_7SDValueES4_S4_RS4_S5_S5_S5_S5_'/>
<use f='llvm/llvm/lib/Target/X86/X86ISelDAGToDAG.cpp' l='2540' u='r' c='_ZN12_GLOBAL__N_115X86DAGToDAGISel10selectAddrEPN4llvm6SDNodeENS1_7SDValueERS4_S5_S5_S5_S5_'/>
<use f='llvm/llvm/lib/Target/X86/X86ISelLowering.cpp' l='32644' u='r' c='_ZNK4llvm17X86TargetLowering20EmitLoweredSegAllocaERNS_12MachineInstrEPNS_17MachineBasicBlockE'/>
<use f='llvm/llvm/lib/Target/X86/X86RegisterInfo.cpp' l='565' u='r' c='_ZNK4llvm15X86RegisterInfo15getReservedRegsERKNS_15MachineFunctionE'/>
