<def f='llvm/llvm/include/llvm/Transforms/Scalar/Reassociate.h' l='59' ll='64'/>
<use f='llvm/llvm/include/llvm/Transforms/Scalar/Reassociate.h' l='118' c='_ZN4llvm15ReassociatePass23buildMinimalMultiplyDAGERNS_13IRBuilderBaseERNS_15SmallVectorImplINS_11reassociate6FactorEEE'/>
<size>16</size>
<doc f='llvm/llvm/include/llvm/Transforms/Scalar/Reassociate.h' l='57'>/// Utility class representing a base and exponent pair which form one
/// factor of some product.</doc>
<mbr r='llvm::reassociate::Factor::Base' o='0' t='llvm::Value *'/>
<mbr r='llvm::reassociate::Factor::Power' o='64' t='unsigned int'/>
<fun r='_ZN4llvm11reassociate6FactorC1EPNS_5ValueEj'/>
<use f='llvm/llvm/lib/Transforms/Scalar/Reassociate.cpp' l='1768' c='_ZL22collectMultiplyFactorsRN4llvm15SmallVectorImplINS_11reassociate10ValueEntryEEERNS0_INS1_6FactorEEE'/>
<use f='llvm/llvm/lib/Transforms/Scalar/Reassociate.cpp' l='1806' c='_ZL22collectMultiplyFactorsRN4llvm15SmallVectorImplINS_11reassociate10ValueEntryEEERNS0_INS1_6FactorEEE'/>
<use f='llvm/llvm/lib/Transforms/Scalar/Reassociate.cpp' l='1814' c='_ZL22collectMultiplyFactorsRN4llvm15SmallVectorImplINS_11reassociate10ValueEntryEEERNS0_INS1_6FactorEEE'/>
<use f='llvm/llvm/lib/Transforms/Scalar/Reassociate.cpp' l='1814' c='_ZL22collectMultiplyFactorsRN4llvm15SmallVectorImplINS_11reassociate10ValueEntryEEERNS0_INS1_6FactorEEE'/>
<use f='llvm/llvm/lib/Transforms/Scalar/Reassociate.cpp' l='1845' c='_ZN4llvm15ReassociatePass23buildMinimalMultiplyDAGERNS_13IRBuilderBaseERNS_15SmallVectorImplINS_11reassociate6FactorEEE'/>
<use f='llvm/llvm/lib/Transforms/Scalar/Reassociate.cpp' l='1876' c='_ZN4llvm15ReassociatePass23buildMinimalMultiplyDAGERNS_13IRBuilderBaseERNS_15SmallVectorImplINS_11reassociate6FactorEEE'/>
<use f='llvm/llvm/lib/Transforms/Scalar/Reassociate.cpp' l='1876' c='_ZN4llvm15ReassociatePass23buildMinimalMultiplyDAGERNS_13IRBuilderBaseERNS_15SmallVectorImplINS_11reassociate6FactorEEE'/>
<use f='llvm/llvm/lib/Transforms/Scalar/Reassociate.cpp' l='1911' c='_ZN4llvm15ReassociatePass11OptimizeMulEPNS_14BinaryOperatorERNS_15SmallVectorImplINS_11reassociate10ValueEntryEEE'/>
<size>16</size>
