<dec f='llvm/llvm/lib/Target/AMDGPU/GCNSchedStrategy.h' l='75' type='const llvm::GCNSubtarget &amp;'/>
<offset>40832</offset>
<use f='llvm/llvm/lib/Target/AMDGPU/GCNSchedStrategy.cpp' l='290' u='w' c='_ZN4llvm20GCNScheduleDAGMILiveC1EPNS_19MachineSchedContextESt10unique_ptrINS_20MachineSchedStrategyESt14default_deleteIS4_EE'/>
<use f='llvm/llvm/lib/Target/AMDGPU/GCNSchedStrategy.cpp' l='344' u='r' c='_ZN4llvm20GCNScheduleDAGMILive8scheduleEv'/>
<use f='llvm/llvm/lib/Target/AMDGPU/GCNSchedStrategy.cpp' l='345' u='r' c='_ZN4llvm20GCNScheduleDAGMILive8scheduleEv'/>
<use f='llvm/llvm/lib/Target/AMDGPU/GCNSchedStrategy.cpp' l='367' u='m' c='_ZN4llvm20GCNScheduleDAGMILive8scheduleEv'/>
<use f='llvm/llvm/lib/Target/AMDGPU/GCNSchedStrategy.cpp' l='368' u='m' c='_ZN4llvm20GCNScheduleDAGMILive8scheduleEv'/>
<use f='llvm/llvm/lib/Target/AMDGPU/GCNSchedStrategy.cpp' l='375' u='r' c='_ZN4llvm20GCNScheduleDAGMILive8scheduleEv'/>
<use f='llvm/llvm/lib/Target/AMDGPU/GCNSchedStrategy.cpp' l='378' u='r' c='_ZN4llvm20GCNScheduleDAGMILive8scheduleEv'/>
