<dec f='llvm/llvm/include/llvm/ExecutionEngine/Orc/LazyReexports.h' l='79' type='llvm::orc::ExecutionSession &amp;'/>
<offset>384</offset>
<use f='llvm/llvm/lib/ExecutionEngine/Orc/LazyReexports.cpp' l='21' u='w' c='_ZN4llvm3orc22LazyCallThroughManagerC1ERNS0_16ExecutionSessionEmPNS0_14TrampolinePoolE'/>
<use f='llvm/llvm/lib/ExecutionEngine/Orc/LazyReexports.cpp' l='40' u='m' c='_ZN4llvm3orc22LazyCallThroughManager22reportCallThroughErrorENS_5ErrorE'/>
<use f='llvm/llvm/lib/ExecutionEngine/Orc/LazyReexports.cpp' l='98' u='m' c='_ZN4llvm3orc22LazyCallThroughManager31resolveTrampolineLandingAddressEmNS_15unique_functionIKFvmEEE'/>
