<dec f='llvm/llvm/include/llvm/CodeGen/GlobalISel/LegalizerInfo.h' l='152' type='llvm::LegalizeActions::LegalizeAction'/>
<use f='llvm/llvm/include/llvm/CodeGen/GlobalISel/LegalizerInfo.h' l='160' u='w' c='_ZN4llvm18LegalizeActionStepC1ENS_15LegalizeActions14LegalizeActionEjNS_3LLTE'/>
<use f='llvm/llvm/include/llvm/CodeGen/GlobalISel/LegalizerInfo.h' l='163' u='r' c='_ZNK4llvm18LegalizeActionStepeqERKS0_'/>
<use f='llvm/llvm/include/llvm/CodeGen/GlobalISel/LegalizerInfo.h' l='164' u='r' c='_ZNK4llvm18LegalizeActionStepeqERKS0_'/>
<use f='llvm/llvm/include/llvm/CodeGen/GlobalISel/LegalizerInfo.h' l='1258' u='r' c='_ZNK4llvm13LegalizerInfo7isLegalERKNS_13LegalityQueryE'/>
<use f='llvm/llvm/include/llvm/CodeGen/GlobalISel/LegalizerInfo.h' l='1262' u='r' c='_ZNK4llvm13LegalizerInfo15isLegalOrCustomERKNS_13LegalityQueryE'/>
<use f='llvm/llvm/lib/CodeGen/GlobalISel/CombinerHelper.cpp' l='113' u='r' c='_ZNK4llvm14CombinerHelper24isLegalOrBeforeLegalizerERKNS_13LegalityQueryE'/>
<use f='llvm/llvm/lib/CodeGen/GlobalISel/CombinerHelper.cpp' l='489' u='r' c='_ZN4llvm14CombinerHelper26matchCombineExtendingLoadsERNS_12MachineInstrERNS_14PreferredTupleE'/>
<offset>0</offset>
<doc f='llvm/llvm/include/llvm/CodeGen/GlobalISel/LegalizerInfo.h' l='151'>/// The action to take or the final answer.</doc>
<use f='llvm/llvm/include/llvm/CodeGen/GlobalISel/LegalizationArtifactCombiner.h' l='551' u='r' c='_ZN4llvm28LegalizationArtifactCombiner23tryCombineUnmergeValuesERNS_12MachineInstrERNS_15SmallVectorImplIPS1_EERNS3_INS_8RegisterEEERNS_19GISelChangeObserverE'/>
<use f='llvm/llvm/include/llvm/CodeGen/GlobalISel/LegalizationArtifactCombiner.h' l='981' u='r' c='_ZNK4llvm28LegalizationArtifactCombiner17isInstUnsupportedERKNS_13LegalityQueryE'/>
<use f='llvm/llvm/include/llvm/CodeGen/GlobalISel/LegalizationArtifactCombiner.h' l='981' u='r' c='_ZNK4llvm28LegalizationArtifactCombiner17isInstUnsupportedERKNS_13LegalityQueryE'/>
<use f='llvm/llvm/include/llvm/CodeGen/GlobalISel/LegalizationArtifactCombiner.h' l='985' u='r' c='_ZNK4llvm28LegalizationArtifactCombiner11isInstLegalERKNS_13LegalityQueryE'/>
<use f='llvm/llvm/lib/CodeGen/GlobalISel/LegalizerHelper.cpp' l='112' u='r' c='_ZN4llvm15LegalizerHelper17legalizeInstrStepERNS_12MachineInstrE'/>
<use f='llvm/llvm/lib/CodeGen/GlobalISel/LegalizerHelper.cpp' l='2951' u='r' c='_ZN4llvm15LegalizerHelper5lowerERNS_12MachineInstrEjNS_3LLTE'/>
<use f='llvm/llvm/lib/CodeGen/GlobalISel/LegalizerHelper.cpp' l='4852' u='r' c='_ZN4llvm15LegalizerHelper13lowerBitCountERNS_12MachineInstrE'/>
<use f='llvm/llvm/lib/CodeGen/GlobalISel/LegalizerInfo.cpp' l='468' u='r' c='_ZNK4llvm13LegalizerInfo9getActionERKNS_13LegalityQueryE'/>
<use f='llvm/llvm/lib/CodeGen/GlobalISel/LegalizerInfo.cpp' l='518' u='r' c='_ZNK4llvm13LegalizerInfo7isLegalERKNS_12MachineInstrERKNS_19MachineRegisterInfoE'/>
<use f='llvm/llvm/lib/CodeGen/GlobalISel/LegalizerInfo.cpp' l='523' u='r' c='_ZNK4llvm13LegalizerInfo15isLegalOrCustomERKNS_12MachineInstrERKNS_19MachineRegisterInfoE'/>
<use f='llvm/llvm/unittests/CodeGen/GlobalISel/LegalizerInfoTest.cpp' l='39' u='r' c='_ZN4llvmlsERSoNS_18LegalizeActionStepE'/>
