<dec f='llvm/llvm/include/llvm/Analysis/PostDominators.h' l='65' type='llvm::raw_ostream &amp;'/>
<offset>0</offset>
<use f='llvm/llvm/lib/Analysis/PostDominators.cpp' l='105' u='w' c='_ZN4llvm28PostDominatorTreePrinterPassC1ERNS_11raw_ostreamE'/>
<use f='llvm/llvm/lib/Analysis/PostDominators.cpp' l='109' u='m' c='_ZN4llvm28PostDominatorTreePrinterPass3runERNS_8FunctionERNS_15AnalysisManagerIS1_JEEE'/>
<use f='llvm/llvm/lib/Analysis/PostDominators.cpp' l='110' u='a' c='_ZN4llvm28PostDominatorTreePrinterPass3runERNS_8FunctionERNS_15AnalysisManagerIS1_JEEE'/>
