<dec f='llvm/llvm/lib/Target/AMDGPU/AMDGPUTargetTransformInfo.h' l='45' type='const llvm::TargetSubtargetInfo *'/>
<use f='llvm/llvm/lib/Target/AMDGPU/AMDGPUTargetTransformInfo.h' l='48' u='r' c='_ZNK4llvm13AMDGPUTTIImpl5getSTEv'/>
<offset>576</offset>
<use f='llvm/llvm/lib/Target/AMDGPU/AMDGPUTargetTransformInfo.cpp' l='99' u='w' c='_ZN4llvm13AMDGPUTTIImplC1EPKNS_19AMDGPUTargetMachineERKNS_8FunctionE'/>
<use f='llvm/llvm/lib/Target/AMDGPU/AMDGPUTargetTransformInfo.cpp' l='100' u='r' c='_ZN4llvm13AMDGPUTTIImplC1EPKNS_19AMDGPUTargetMachineERKNS_8FunctionE'/>
