<dec f='llvm/llvm/include/llvm/CodeGen/EdgeBundles.h' l='30' type='llvm::IntEqClasses'/>
<use f='llvm/llvm/include/llvm/CodeGen/EdgeBundles.h' l='41' u='m' c='_ZNK4llvm11EdgeBundles9getBundleEjb'/>
<use f='llvm/llvm/include/llvm/CodeGen/EdgeBundles.h' l='44' u='m' c='_ZNK4llvm11EdgeBundles13getNumBundlesEv'/>
<use f='llvm/llvm/lib/CodeGen/EdgeBundles.cpp' l='43' u='m' c='_ZN4llvm11EdgeBundles20runOnMachineFunctionERNS_15MachineFunctionE'/>
<use f='llvm/llvm/lib/CodeGen/EdgeBundles.cpp' l='44' u='m' c='_ZN4llvm11EdgeBundles20runOnMachineFunctionERNS_15MachineFunctionE'/>
<use f='llvm/llvm/lib/CodeGen/EdgeBundles.cpp' l='51' u='m' c='_ZN4llvm11EdgeBundles20runOnMachineFunctionERNS_15MachineFunctionE'/>
<use f='llvm/llvm/lib/CodeGen/EdgeBundles.cpp' l='53' u='m' c='_ZN4llvm11EdgeBundles20runOnMachineFunctionERNS_15MachineFunctionE'/>
<offset>896</offset>
<doc f='llvm/llvm/include/llvm/CodeGen/EdgeBundles.h' l='27'>/// EC - Each edge bundle is an equivalence class. The keys are:
  ///   2*BB-&gt;getNumber()   -&gt; Ingoing bundle.
  ///   2*BB-&gt;getNumber()+1 -&gt; Outgoing bundle.</doc>
