<use f='llvm/llvm/tools/llvm-rc/ResourceFileWriter.h' l='47' u='w' c='_ZN4llvm2rc18ResourceFileWriterC1ERKNS0_12WriterParamsESt10unique_ptrINS_14raw_fd_ostreamESt14default_deleteIS6_EE'/>
<dec f='llvm/llvm/tools/llvm-rc/ResourceFileWriter.h' l='174' type='std::unique_ptr&lt;raw_fd_ostream&gt;'/>
<use f='llvm/llvm/tools/llvm-rc/ResourceFileWriter.h' l='176' u='m' c='_ZNK4llvm2rc18ResourceFileWriter4tellEv'/>
<use f='llvm/llvm/tools/llvm-rc/ResourceFileWriter.h' l='193' u='m' c='_ZN4llvm2rc18ResourceFileWriter13writeObjectAtERKT_m'/>
<use f='llvm/llvm/tools/llvm-rc/ResourceFileWriter.cpp' l='365' u='m' c='_ZN4llvm2rc18ResourceFileWriter11writeObjectENS_8ArrayRefIhEE'/>
<use f='llvm/llvm/tools/llvm-rc/ResourceFileWriter.cpp' l='410' u='m' c='_ZN4llvm2rc18ResourceFileWriter10appendFileENS_9StringRefE'/>
<use f='llvm/llvm/tools/llvm-rc/ResourceFileWriter.cpp' l='720' u='m' c='_ZN4llvm2rc18ResourceFileWriter15writeBitmapBodyEPKNS0_10RCResourceE'/>
<offset>1728</offset>
<doc f='llvm/llvm/tools/llvm-rc/ResourceFileWriter.h' l='173'>// Output stream handling.</doc>
