<dec f='llvm/llvm/lib/Target/X86/MCTargetDesc/X86BaseInfo.h' l='128' type='0'/>
<use f='llvm/llvm/lib/Target/X86/MCTargetDesc/X86BaseInfo.h' l='315' u='r' c='_ZN4llvm3X8635classifySecondCondCodeInMacroFusionENS0_8CondCodeE'/>
<use f='llvm/llvm/lib/Target/X86/MCTargetDesc/X86BaseInfo.h' l='344' u='r' c='_ZN4llvm3X8612isMacroFusedENS0_24FirstMacroFusionInstKindENS0_25SecondMacroFusionInstKindE'/>
<doc f='llvm/llvm/lib/Target/X86/MCTargetDesc/X86BaseInfo.h' l='127'>// JA, JB and variants.</doc>
