<dec f='llvm/llvm/lib/Target/AMDGPU/AMDGPUAliasAnalysis.h' l='28' type='const llvm::DataLayout &amp;'/>
<use f='llvm/llvm/lib/Target/AMDGPU/AMDGPUAliasAnalysis.h' l='31' u='w' c='_ZN4llvm14AMDGPUAAResultC1ERKNS_10DataLayoutE'/>
<use f='llvm/llvm/lib/Target/AMDGPU/AMDGPUAliasAnalysis.h' l='33' u='w' c='_ZN4llvm14AMDGPUAAResultC1EOS0_'/>
<use f='llvm/llvm/lib/Target/AMDGPU/AMDGPUAliasAnalysis.h' l='33' u='r' c='_ZN4llvm14AMDGPUAAResultC1EOS0_'/>
<offset>64</offset>
