<use f='llvm/llvm/include/llvm/Passes/PassBuilder.h' l='43' u='w' c='_ZN4llvm10PGOOptionsC1ENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES6_S6_NS0_9PGOActionENS0_11CSPGOActionEbb'/>
<dec f='llvm/llvm/include/llvm/Passes/PassBuilder.h' l='78' type='llvm::PGOOptions::PGOAction'/>
<offset>768</offset>
<use f='llvm/llvm/lib/Passes/PassBuilder.cpp' l='579' u='r' c='_ZN4llvm11PassBuilder37buildO1FunctionSimplificationPipelineENS0_17OptimizationLevelENS_18ThinOrFullLTOPhaseE'/>
<use f='llvm/llvm/lib/Passes/PassBuilder.cpp' l='695' u='r' c='_ZN4llvm11PassBuilder35buildFunctionSimplificationPipelineENS0_17OptimizationLevelENS_18ThinOrFullLTOPhaseE'/>
<use f='llvm/llvm/lib/Passes/PassBuilder.cpp' l='743' u='r' c='_ZN4llvm11PassBuilder35buildFunctionSimplificationPipelineENS0_17OptimizationLevelENS_18ThinOrFullLTOPhaseE'/>
<use f='llvm/llvm/lib/Passes/PassBuilder.cpp' l='823' u='r' c='_ZN4llvm11PassBuilder35buildFunctionSimplificationPipelineENS0_17OptimizationLevelENS_18ThinOrFullLTOPhaseE'/>
<use f='llvm/llvm/lib/Passes/PassBuilder.cpp' l='824' u='r' c='_ZN4llvm11PassBuilder35buildFunctionSimplificationPipelineENS0_17OptimizationLevelENS_18ThinOrFullLTOPhaseE'/>
<use f='llvm/llvm/lib/Passes/PassBuilder.cpp' l='935' u='r' c='_ZN4llvm11PassBuilder20buildInlinerPipelineENS0_17OptimizationLevelENS_18ThinOrFullLTOPhaseE'/>
<use f='llvm/llvm/lib/Passes/PassBuilder.cpp' l='1010' u='r' c='_ZN4llvm11PassBuilder33buildModuleSimplificationPipelineENS0_17OptimizationLevelENS_18ThinOrFullLTOPhaseE'/>
<use f='llvm/llvm/lib/Passes/PassBuilder.cpp' l='1128' u='r' c='_ZN4llvm11PassBuilder33buildModuleSimplificationPipelineENS0_17OptimizationLevelENS_18ThinOrFullLTOPhaseE'/>
<use f='llvm/llvm/lib/Passes/PassBuilder.cpp' l='1129' u='r' c='_ZN4llvm11PassBuilder33buildModuleSimplificationPipelineENS0_17OptimizationLevelENS_18ThinOrFullLTOPhaseE'/>
<use f='llvm/llvm/lib/Passes/PassBuilder.cpp' l='1131' u='r' c='_ZN4llvm11PassBuilder33buildModuleSimplificationPipelineENS0_17OptimizationLevelENS_18ThinOrFullLTOPhaseE'/>
<use f='llvm/llvm/lib/Passes/PassBuilder.cpp' l='1572' u='r' c='_ZN4llvm11PassBuilder23buildLTODefaultPipelineENS0_17OptimizationLevelEPNS_18ModuleSummaryIndexE'/>
<use f='llvm/llvm/lib/Passes/PassBuilder.cpp' l='1603' u='r' c='_ZN4llvm11PassBuilder23buildLTODefaultPipelineENS0_17OptimizationLevelEPNS_18ModuleSummaryIndexE'/>
<use f='llvm/llvm/lib/Passes/PassBuilder.cpp' l='1811' u='r' c='_ZN4llvm11PassBuilder22buildO0DefaultPipelineENS0_17OptimizationLevelEb'/>
<use f='llvm/llvm/lib/Passes/PassBuilder.cpp' l='1812' u='r' c='_ZN4llvm11PassBuilder22buildO0DefaultPipelineENS0_17OptimizationLevelEb'/>
<use f='llvm/llvm/lib/Passes/PassBuilder.cpp' l='1815' u='r' c='_ZN4llvm11PassBuilder22buildO0DefaultPipelineENS0_17OptimizationLevelEb'/>
<use f='llvm/llvm/tools/opt/NewPMDriver.cpp' l='264' u='r' c='_ZN4llvm15runPassPipelineENS_9StringRefERNS_6ModuleEPNS_13TargetMachineEPNS_21TargetLibraryInfoImplEPNS_14ToolOutputFileES8_S8_S0_NS_8ArrayRefIS0_EENS12269778'/>
<use f='llvm/llvm/tools/opt/NewPMDriver.cpp' l='265' u='r' c='_ZN4llvm15runPassPipelineENS_9StringRefERNS_6ModuleEPNS_13TargetMachineEPNS_21TargetLibraryInfoImplEPNS_14ToolOutputFileES8_S8_S0_NS_8ArrayRefIS0_EENS12269778'/>
