<dec f='llvm/llvm/include/llvm/IR/IRPrintingPasses.h' l='53' type='llvm::raw_ostream &amp;'/>
<offset>0</offset>
<use f='llvm/llvm/lib/IR/IRPrintingPasses.cpp' l='25' u='w' c='_ZN4llvm15PrintModulePassC1Ev'/>
<use f='llvm/llvm/lib/IR/IRPrintingPasses.cpp' l='28' u='w' c='_ZN4llvm15PrintModulePassC1ERNS_11raw_ostreamERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEb'/>
<use f='llvm/llvm/lib/IR/IRPrintingPasses.cpp' l='34' u='m' c='_ZN4llvm15PrintModulePass3runERNS_6ModuleERNS_15AnalysisManagerIS1_JEEE'/>
<use f='llvm/llvm/lib/IR/IRPrintingPasses.cpp' l='35' u='a' c='_ZN4llvm15PrintModulePass3runERNS_6ModuleERNS_15AnalysisManagerIS1_JEEE'/>
<use f='llvm/llvm/lib/IR/IRPrintingPasses.cpp' l='42' u='m' c='_ZN4llvm15PrintModulePass3runERNS_6ModuleERNS_15AnalysisManagerIS1_JEEE'/>
<use f='llvm/llvm/lib/IR/IRPrintingPasses.cpp' l='45' u='a' c='_ZN4llvm15PrintModulePass3runERNS_6ModuleERNS_15AnalysisManagerIS1_JEEE'/>
