<dec f='llvm/llvm/lib/CodeGen/BranchFolding.h' l='126' type='llvm::MachineLoopInfo *'/>
<use f='llvm/llvm/lib/CodeGen/BranchFolding.cpp' l='174' u='r' c='_ZN4llvm12BranchFolder15RemoveDeadBlockEPNS_17MachineBasicBlockE'/>
<use f='llvm/llvm/lib/CodeGen/BranchFolding.cpp' l='175' u='r' c='_ZN4llvm12BranchFolder15RemoveDeadBlockEPNS_17MachineBasicBlockE'/>
<use f='llvm/llvm/lib/CodeGen/BranchFolding.cpp' l='190' u='w' c='_ZN4llvm12BranchFolder16OptimizeFunctionERNS_15MachineFunctionEPKNS_15TargetInstrInfoEPKNS_18TargetRegisterInfoEPNS_15MachineLoopInfoEb'/>
<use f='llvm/llvm/lib/CodeGen/BranchFolding.cpp' l='411' u='r' c='_ZN4llvm12BranchFolder10SplitMBBAtERNS_17MachineBasicBlockENS_26MachineInstrBundleIteratorINS_12MachineInstrELb0EEEPKNS_10BasicBlockE'/>
<use f='llvm/llvm/lib/CodeGen/BranchFolding.cpp' l='412' u='r' c='_ZN4llvm12BranchFolder10SplitMBBAtERNS_17MachineBasicBlockENS_26MachineInstrBundleIteratorINS_12MachineInstrELb0EEEPKNS_10BasicBlockE'/>
<use f='llvm/llvm/lib/CodeGen/BranchFolding.cpp' l='413' u='r' c='_ZN4llvm12BranchFolder10SplitMBBAtERNS_17MachineBasicBlockENS_26MachineInstrBundleIteratorINS_12MachineInstrELb0EEEPKNS_10BasicBlockE'/>
<use f='llvm/llvm/lib/CodeGen/BranchFolding.cpp' l='1061' u='r' c='_ZN4llvm12BranchFolder15TailMergeBlocksERNS_15MachineFunctionE'/>
<use f='llvm/llvm/lib/CodeGen/BranchFolding.cpp' l='1062' u='r' c='_ZN4llvm12BranchFolder15TailMergeBlocksERNS_15MachineFunctionE'/>
<use f='llvm/llvm/lib/CodeGen/BranchFolding.cpp' l='1090' u='r' c='_ZN4llvm12BranchFolder15TailMergeBlocksERNS_15MachineFunctionE'/>
<use f='llvm/llvm/lib/CodeGen/BranchFolding.cpp' l='1091' u='r' c='_ZN4llvm12BranchFolder15TailMergeBlocksERNS_15MachineFunctionE'/>
<offset>1216</offset>
