<dec f='llvm/build/lib/Target/Mips/MipsGenInstrInfo.inc' l='2622' type='2607'/>
<use f='llvm/llvm/lib/Target/Mips/AsmParser/MipsAsmParser.cpp' l='4199' u='r' c='_ZN12_GLOBAL__N_113MipsAsmParser12expandDivRemERN4llvm6MCInstENS1_5SMLocERNS1_10MCStreamerEPKNS1_15MCSubtargetInfoEbb'/>
<use f='llvm/llvm/lib/Target/Mips/AsmParser/MipsAsmParser.cpp' l='5149' u='r' c='_ZN12_GLOBAL__N_113MipsAsmParser9expandAbsERN4llvm6MCInstENS1_5SMLocERNS1_10MCStreamerEPKNS1_15MCSubtargetInfoE'/>
<use f='llvm/build/lib/Target/Mips/MipsGenAsmMatcher.inc' l='7291'/>
<use f='llvm/build/lib/Target/Mips/MipsGenAsmMatcher.inc' l='7295'/>
<use f='llvm/build/lib/Target/Mips/MipsGenAsmMatcher.inc' l='7862'/>
<use f='llvm/build/lib/Target/Mips/MipsGenAsmMatcher.inc' l='7866'/>
<use f='llvm/build/lib/Target/Mips/MipsGenAsmWriter.inc' l='7928' u='r' c='_ZN4llvm15MipsInstPrinter15printAliasInstrEPKNS_6MCInstEmRNS_11raw_ostreamE'/>
<use f='llvm/build/lib/Target/Mips/MipsGenMCCodeEmitter.inc' l='5149' c='_ZNK4llvm17MipsMCCodeEmitter21getBinaryCodeForInstrERKNS_6MCInstERNS_15SmallVectorImplINS_7MCFixupEEERKNS_15MCSubtargetInfoE'/>
<use f='llvm/llvm/lib/Target/Mips/MipsSEISelLowering.cpp' l='3419' u='r' c='_ZNK4llvm20MipsSETargetLowering18emitINSERT_DF_VIDXERNS_12MachineInstrEPNS_17MachineBasicBlockEjb'/>
