<dec f='llvm/llvm/include/llvm/Analysis/IRSimilarityIdentifier.h' l='198' type='llvm::IRSimilarity::IRInstructionDataList *'/>
<use f='llvm/llvm/lib/Analysis/IRSimilarityIdentifier.cpp' l='28' u='w' c='_ZN4llvm12IRSimilarity17IRInstructionDataC1ERNS_11InstructionEbRNS0_21IRInstructionDataListE'/>
<offset>704</offset>
<use f='llvm/llvm/lib/Transforms/IPO/IROutliner.cpp' l='1500' u='r' c='_ZN4llvm10IROutliner14extractSectionERNS_16OutlinableRegionE'/>
