<dec f='llvm/llvm/tools/llvm-pdbutil/InputFile.h' l='124' type='codeview::StringsAndChecksumsRef'/>
<offset>704</offset>
<use f='llvm/llvm/tools/llvm-pdbutil/InputFile.cpp' l='144' u='m' c='_ZN4llvm3pdb11SymbolGroupC1EPNS0_9InputFileEj'/>
<use f='llvm/llvm/tools/llvm-pdbutil/InputFile.cpp' l='144' u='m' c='_ZN4llvm3pdb11SymbolGroupC1EPNS0_9InputFileEj'/>
<use f='llvm/llvm/tools/llvm-pdbutil/InputFile.cpp' l='145' u='m' c='_ZN4llvm3pdb11SymbolGroupC1EPNS0_9InputFileEj'/>
<use f='llvm/llvm/tools/llvm-pdbutil/InputFile.cpp' l='150' u='m' c='_ZN4llvm3pdb11SymbolGroupC1EPNS0_9InputFileEj'/>
<use f='llvm/llvm/tools/llvm-pdbutil/InputFile.cpp' l='150' u='m' c='_ZN4llvm3pdb11SymbolGroupC1EPNS0_9InputFileEj'/>
<use f='llvm/llvm/tools/llvm-pdbutil/InputFile.cpp' l='170' u='m' c='_ZN4llvm3pdb11SymbolGroup16initializeForPdbEj'/>
<use f='llvm/llvm/tools/llvm-pdbutil/InputFile.cpp' l='173' u='m' c='_ZN4llvm3pdb11SymbolGroup16initializeForPdbEj'/>
<use f='llvm/llvm/tools/llvm-pdbutil/InputFile.cpp' l='178' u='m' c='_ZN4llvm3pdb11SymbolGroup16initializeForPdbEj'/>
<use f='llvm/llvm/tools/llvm-pdbutil/InputFile.cpp' l='187' u='m' c='_ZN4llvm3pdb11SymbolGroup16initializeForPdbEj'/>
<use f='llvm/llvm/tools/llvm-pdbutil/InputFile.cpp' l='192' u='m' c='_ZN4llvm3pdb11SymbolGroup18rebuildChecksumMapEv'/>
<use f='llvm/llvm/tools/llvm-pdbutil/InputFile.cpp' l='195' u='m' c='_ZN4llvm3pdb11SymbolGroup18rebuildChecksumMapEv'/>
<use f='llvm/llvm/tools/llvm-pdbutil/InputFile.cpp' l='196' u='m' c='_ZN4llvm3pdb11SymbolGroup18rebuildChecksumMapEv'/>
<use f='llvm/llvm/tools/llvm-pdbutil/InputFile.cpp' l='209' u='m' c='_ZNK4llvm3pdb11SymbolGroup22getNameFromStringTableEj'/>
<use f='llvm/llvm/tools/llvm-pdbutil/InputFile.cpp' l='228' u='m' c='_ZNK4llvm3pdb11SymbolGroup25formatFromChecksumsOffsetERNS0_11LinePrinterEjb'/>
<use f='llvm/llvm/tools/llvm-pdbutil/InputFile.cpp' l='233' u='m' c='_ZNK4llvm3pdb11SymbolGroup25formatFromChecksumsOffsetERNS0_11LinePrinterEjb'/>
<use f='llvm/llvm/tools/llvm-pdbutil/InputFile.cpp' l='234' u='m' c='_ZNK4llvm3pdb11SymbolGroup25formatFromChecksumsOffsetERNS0_11LinePrinterEjb'/>
