<dec f='llvm/llvm/include/llvm/Support/Automaton.h' l='171' type='std::shared_ptr&lt;MapTy&gt;'/>
<use f='llvm/llvm/include/llvm/Support/Automaton.h' l='199' u='w' c='_ZN4llvm9AutomatonC1ENS_8ArrayRefITL0__EENS1_INS_12NfaStatePairEEE'/>
<use f='llvm/llvm/include/llvm/Support/Automaton.h' l='202' u='c' c='_ZN4llvm9AutomatonC1ENS_8ArrayRefITL0__EENS1_INS_12NfaStatePairEEE'/>
<use f='llvm/llvm/include/llvm/Support/Automaton.h' l='206' u='w' c='_ZN4llvm9AutomatonC1ERKNS_9AutomatonIT_EE'/>
<use f='llvm/llvm/include/llvm/Support/Automaton.h' l='236' u='c' c='_ZN4llvm9Automaton3addERKT_'/>
<use f='llvm/llvm/include/llvm/Support/Automaton.h' l='237' u='c' c='_ZN4llvm9Automaton3addERKT_'/>
<use f='llvm/llvm/include/llvm/Support/Automaton.h' l='247' u='c' c='_ZN4llvm9Automaton6canAddERKT_'/>
<use f='llvm/llvm/include/llvm/Support/Automaton.h' l='248' u='c' c='_ZN4llvm9Automaton6canAddERKT_'/>
