<dec f='llvm/llvm/lib/Target/AMDGPU/MCTargetDesc/AMDGPUTargetStreamer.h' l='142' type='Triple::OSType'/>
<offset>3072</offset>
<use f='llvm/llvm/lib/Target/AMDGPU/MCTargetDesc/AMDGPUTargetStreamer.cpp' l='408' u='w' c='_ZN4llvm23AMDGPUTargetELFStreamerC1ERNS_10MCStreamerERKNS_15MCSubtargetInfoE'/>
<use f='llvm/llvm/lib/Target/AMDGPU/MCTargetDesc/AMDGPUTargetStreamer.cpp' l='459' u='r' c='_ZN4llvm23AMDGPUTargetELFStreamer8EmitNoteENS_9StringRefEPKNS_6MCExprEjNS_12function_refIFvRNS_13MCELFStreamerEEEE'/>
