<dec f='llvm/llvm/lib/Transforms/Vectorize/LoopVectorizationPlanner.h' l='41' type='llvm::VPBasicBlock *'/>
<use f='llvm/llvm/lib/Transforms/Vectorize/LoopVectorizationPlanner.h' l='47' u='r' c='_ZN4llvm9VPBuilder17createInstructionEjNS_8ArrayRefIPNS_7VPValueEEE'/>
<use f='llvm/llvm/lib/Transforms/Vectorize/LoopVectorizationPlanner.h' l='48' u='r' c='_ZN4llvm9VPBuilder17createInstructionEjNS_8ArrayRefIPNS_7VPValueEEE'/>
<use f='llvm/llvm/lib/Transforms/Vectorize/LoopVectorizationPlanner.h' l='63' u='w' c='_ZN4llvm9VPBuilder19clearInsertionPointEv'/>
<use f='llvm/llvm/lib/Transforms/Vectorize/LoopVectorizationPlanner.h' l='67' u='r' c='_ZNK4llvm9VPBuilder14getInsertBlockEv'/>
<use f='llvm/llvm/lib/Transforms/Vectorize/LoopVectorizationPlanner.h' l='102' u='w' c='_ZN4llvm9VPBuilder14setInsertPointEPNS_12VPBasicBlockE'/>
<use f='llvm/llvm/lib/Transforms/Vectorize/LoopVectorizationPlanner.h' l='103' u='r' c='_ZN4llvm9VPBuilder14setInsertPointEPNS_12VPBasicBlockE'/>
<use f='llvm/llvm/lib/Transforms/Vectorize/LoopVectorizationPlanner.h' l='109' u='w' c='_ZN4llvm9VPBuilder14setInsertPointEPNS_12VPBasicBlockENS_14ilist_iteratorINS_12ilist_detail12node_optionsINS_12VPRecipeBaseELb0ELb0EvEELb0ELb0EEE'/>
<use f='llvm/llvm/lib/Transforms/Vectorize/LoopVectorizationPlanner.h' l='115' u='r' c='_ZNK4llvm9VPBuilder6insertEPNS_13VPInstructionE'/>
<offset>0</offset>
