<dec f='llvm/polly/include/polly/ScheduleOptimizer.h' l='36' type='int'/>
<use f='llvm/polly/lib/Transform/ScheduleOptimizer.cpp' l='837' u='r' c='_ZN21ScheduleTreeOptimizer17createMacroKernelEN3isl12noexceptions13schedule_nodeE19MacroKernelParamsTy'/>
<use f='llvm/polly/lib/Transform/ScheduleOptimizer.cpp' l='842' u='r' c='_ZN21ScheduleTreeOptimizer17createMacroKernelEN3isl12noexceptions13schedule_nodeE19MacroKernelParamsTy'/>
<use f='llvm/polly/lib/Transform/ScheduleOptimizer.cpp' l='1135' u='r' c='_ZL32optimizeDataLayoutMatrMulPatternN3isl12noexceptions13schedule_nodeENS0_3mapE19MicroKernelParamsTy19MacroKernelParamsTyRN5polly12MatMulInfoTyE'/>
<use f='llvm/polly/lib/Transform/ScheduleOptimizer.cpp' l='1297' u='r' c='_ZN21ScheduleTreeOptimizer21optimizeMatMulPatternEN3isl12noexceptions13schedule_nodeEPKN4llvm19TargetTransformInfoERN5polly12MatMulInfoTyE'/>
<offset>0</offset>
