<dec f='llvm/compiler-rt/lib/msan/msan.h' l='36' type='1'/>
<use f='llvm/compiler-rt/lib/msan/msan.h' l='240'/>
<use f='llvm/compiler-rt/lib/msan/msan.h' l='248'/>
<use f='llvm/compiler-rt/lib/msan/msan.h' l='251'/>
<use f='llvm/compiler-rt/lib/msan/msan.cpp' l='505' macro='1' u='r' c='__msan_print_shadow'/>
<use f='llvm/compiler-rt/lib/msan/msan.cpp' l='514' macro='1' u='r' c='__msan_dump_shadow'/>
<use f='llvm/compiler-rt/lib/msan/msan.cpp' l='526' macro='1' u='r' c='__msan_test_shadow'/>
<use f='llvm/compiler-rt/lib/msan/msan_interceptors.cpp' l='577' macro='1' u='r' c='__interceptor_wmemset'/>
<use f='llvm/compiler-rt/lib/msan/msan_interceptors.cpp' l='934' macro='1' u='r' c='_ZL16mmap_interceptorT_Pvmiiiy'/>
<use f='llvm/compiler-rt/lib/msan/msan_interceptors.cpp' l='934' macro='1' u='r' c='_ZL16mmap_interceptorT_Pvmiiiy'/>
<use f='llvm/compiler-rt/lib/msan/msan_interceptors.cpp' l='945' macro='1' u='r' c='_ZL16mmap_interceptorT_Pvmiiiy'/>
<use f='llvm/compiler-rt/lib/msan/msan_interceptors.cpp' l='945' macro='1' u='r' c='_ZL16mmap_interceptorT_Pvmiiiy'/>
<use f='llvm/compiler-rt/lib/msan/msan_interceptors.cpp' l='1532' macro='1' u='r' c='__msan_unpoison'/>
<use f='llvm/compiler-rt/lib/msan/msan_interceptors.cpp' l='1537' macro='1' u='r' c='__msan_poison'/>
<use f='llvm/compiler-rt/lib/msan/msan_interceptors.cpp' l='1542' macro='1' u='r' c='__msan_poison_stack'/>
<use f='llvm/compiler-rt/lib/msan/msan_interceptors.cpp' l='1584' macro='1' u='r' c='__msan_unpoison_string'/>
<use f='llvm/compiler-rt/lib/msan/msan_linux.cpp' l='87' u='r' c='__msan::CheckMemoryLayoutSanity'/>
<use f='llvm/compiler-rt/lib/msan/msan_linux.cpp' l='116' macro='1' u='r' c='__msan::InitShadow'/>
<use f='llvm/compiler-rt/lib/msan/msan_linux.cpp' l='140' u='r' c='__msan::InitShadow'/>
<use f='llvm/compiler-rt/lib/msan/msan_poisoning.cpp' l='44' macro='1' u='r' c='__msan::CopyOrigin'/>
<use f='llvm/compiler-rt/lib/msan/msan_poisoning.cpp' l='44' macro='1' u='r' c='__msan::CopyOrigin'/>
<use f='llvm/compiler-rt/lib/msan/msan_poisoning.cpp' l='99' macro='1' u='r' c='__msan::ReverseCopyOrigin'/>
<use f='llvm/compiler-rt/lib/msan/msan_poisoning.cpp' l='99' macro='1' u='r' c='__msan::ReverseCopyOrigin'/>
<use f='llvm/compiler-rt/lib/msan/msan_poisoning.cpp' l='168' macro='1' u='r' c='__msan::MoveShadowAndOrigin'/>
<use f='llvm/compiler-rt/lib/msan/msan_poisoning.cpp' l='169' macro='1' u='r' c='__msan::MoveShadowAndOrigin'/>
<use f='llvm/compiler-rt/lib/msan/msan_poisoning.cpp' l='181' macro='1' u='r' c='__msan::CopyShadowAndOrigin'/>
<use f='llvm/compiler-rt/lib/msan/msan_poisoning.cpp' l='182' macro='1' u='r' c='__msan::CopyShadowAndOrigin'/>
<use f='llvm/compiler-rt/lib/msan/msan_thread.cpp' l='47' macro='1' u='r' c='__msan::MsanThread::Init'/>
<use f='llvm/compiler-rt/lib/msan/msan_thread.cpp' l='48' macro='1' u='r' c='__msan::MsanThread::Init'/>
