<dec f='llvm/polly/include/polly/ScheduleOptimizer.h' l='28' type='int'/>
<use f='llvm/polly/lib/Transform/ScheduleOptimizer.cpp' l='828' u='r' c='_ZN21ScheduleTreeOptimizer17createMicroKernelEN3isl12noexceptions13schedule_nodeE19MicroKernelParamsTy'/>
<use f='llvm/polly/lib/Transform/ScheduleOptimizer.cpp' l='984' u='r' c='_ZL20getMacroKernelParamsPKN4llvm19TargetTransformInfoERK19MicroKernelParamsTyN5polly12MatMulInfoTyE'/>
<use f='llvm/polly/lib/Transform/ScheduleOptimizer.cpp' l='993' u='r' c='_ZL20getMacroKernelParamsPKN4llvm19TargetTransformInfoERK19MicroKernelParamsTyN5polly12MatMulInfoTyE'/>
<use f='llvm/polly/lib/Transform/ScheduleOptimizer.cpp' l='1011' u='r' c='_ZL20getMacroKernelParamsPKN4llvm19TargetTransformInfoERK19MicroKernelParamsTyN5polly12MatMulInfoTyE'/>
<use f='llvm/polly/lib/Transform/ScheduleOptimizer.cpp' l='1106' u='r' c='_ZL32optimizeDataLayoutMatrMulPatternN3isl12noexceptions13schedule_nodeENS0_3mapE19MicroKernelParamsTy19MacroKernelParamsTyRN5polly12MatMulInfoTyE'/>
<use f='llvm/polly/lib/Transform/ScheduleOptimizer.cpp' l='1108' u='r' c='_ZL32optimizeDataLayoutMatrMulPatternN3isl12noexceptions13schedule_nodeENS0_3mapE19MicroKernelParamsTy19MacroKernelParamsTyRN5polly12MatMulInfoTyE'/>
<use f='llvm/polly/lib/Transform/ScheduleOptimizer.cpp' l='1206' u='r' c='_ZL32isolateAndUnrollMatMulInnerLoopsN3isl12noexceptions13schedule_nodeE19MicroKernelParamsTy'/>
<offset>32</offset>
