<dec f='llvm/build/tools/clang/lib/Sema/OpenCLBuiltins.inc' l='125' type='const clang::LangAS'/>
<use f='llvm/build/tools/clang/lib/Sema/OpenCLBuiltins.inc' l='12012' u='r' c='_ZL8OCL2QualRN5clang10ASTContextERK16OpenCLTypeStructRN4llvm15SmallVectorImplINS_8QualTypeEEE'/>
<offset>96</offset>
<doc f='llvm/build/tools/clang/lib/Sema/OpenCLBuiltins.inc' l='124'>// Address space of the pointer (if applicable).</doc>
