<dec f='llvm/llvm/tools/llvm-readobj/llvm-readobj.h' l='42' type='1'/>
<use f='llvm/llvm/tools/llvm-readobj/ELFDumper.cpp' l='697' u='r' c='_ZN4llvmL15createELFDumperERKNS_6object13ELFObjectFileIT_EERNS_13ScopedPrinterE'/>
<use f='llvm/llvm/tools/llvm-readobj/ELFDumper.cpp' l='2059' u='r' c='_ZNK12_GLOBAL__N_19ELFDumper15getDynamicEntryB5cxx11Emm'/>
<use f='llvm/llvm/tools/llvm-readobj/llvm-readobj.cpp' l='378' u='a'/>
<use f='llvm/llvm/tools/llvm-readobj/llvm-readobj.cpp' l='500' u='r' c='_ZL10dumpObjectRN4llvm6object10ObjectFileERNS_13ScopedPrinterEPKNS0_7ArchiveE'/>
<use f='llvm/llvm/tools/llvm-readobj/llvm-readobj.cpp' l='729' u='r' c='main'/>
