<dec f='llvm/polly/include/polly/ScopDetectionDiagnostic.h' l='787' type='llvm::BasicBlock *'/>
<offset>128</offset>
<use f='llvm/polly/lib/Analysis/ScopDetectionDiagnostic.cpp' l='750' u='w' c='_ZN5polly11ReportEntryC1EPN4llvm10BasicBlockE'/>
<use f='llvm/polly/lib/Analysis/ScopDetectionDiagnostic.cpp' l='754' u='r' c='_ZNK5polly11ReportEntry11getRemarkBBEv'/>
<use f='llvm/polly/lib/Analysis/ScopDetectionDiagnostic.cpp' l='765' u='r' c='_ZNK5polly11ReportEntry11getDebugLocEv'/>
