<dec f='llvm/polly/include/polly/ScopDetectionDiagnostic.h' l='323' type='llvm::BasicBlock *'/>
<use f='llvm/polly/include/polly/ScopDetectionDiagnostic.h' l='327' u='w' c='_ZN5polly17ReportInvalidCondC1EPKN4llvm11InstructionEPNS1_10BasicBlockE'/>
<offset>192</offset>
<doc f='llvm/polly/include/polly/ScopDetectionDiagnostic.h' l='322'>// The BasicBlock we found the broken condition in.</doc>
<use f='llvm/polly/lib/Analysis/ScopDetectionDiagnostic.cpp' l='298' u='r' c='_ZNK5polly17ReportInvalidCond11getRemarkBBEv'/>
<use f='llvm/polly/lib/Analysis/ScopDetectionDiagnostic.cpp' l='301' u='r' c='_ZNK5polly17ReportInvalidCond10getMessageB5cxx11Ev'/>
