<use f='llvm/polly/include/polly/ScopDetection.h' l='621' u='w' c='_ZN5polly23ScopAnalysisPrinterPassC1ERN4llvm11raw_ostreamE'/>
<dec f='llvm/polly/include/polly/ScopDetection.h' l='625' type='llvm::raw_ostream &amp;'/>
<offset>0</offset>
<use f='llvm/polly/lib/Analysis/ScopDetection.cpp' l='1916' u='m' c='_ZN5polly23ScopAnalysisPrinterPass3runERN4llvm8FunctionERNS1_15AnalysisManagerIS2_JEEE'/>
<use f='llvm/polly/lib/Analysis/ScopDetection.cpp' l='1919' u='m' c='_ZN5polly23ScopAnalysisPrinterPass3runERN4llvm8FunctionERNS1_15AnalysisManagerIS2_JEEE'/>
<use f='llvm/polly/lib/Analysis/ScopDetection.cpp' l='1921' u='m' c='_ZN5polly23ScopAnalysisPrinterPass3runERN4llvm8FunctionERNS1_15AnalysisManagerIS2_JEEE'/>
