<dec f='llvm/polly/include/polly/Support/SCEVAffinator.h' l='63' type='polly::Scop *'/>
<offset>192</offset>
<use f='llvm/polly/lib/Support/SCEVAffinator.cpp' l='84' u='w' c='_ZN5polly13SCEVAffinatorC1EPNS_4ScopERN4llvm8LoopInfoE'/>
<use f='llvm/polly/lib/Support/SCEVAffinator.cpp' l='122' u='r' c='_ZN5polly13SCEVAffinator8getPwAffEPKN4llvm4SCEVEPNS1_10BasicBlockEPNS1_11SmallVectorINS_10AssumptionELj8EEE'/>
<use f='llvm/polly/lib/Support/SCEVAffinator.cpp' l='208' u='r' c='_ZN5polly13SCEVAffinator5visitEPKN4llvm4SCEVE'/>
<use f='llvm/polly/lib/Support/SCEVAffinator.cpp' l='208' u='r' c='_ZN5polly13SCEVAffinator5visitEPKN4llvm4SCEVE'/>
<use f='llvm/polly/lib/Support/SCEVAffinator.cpp' l='214' u='r' c='_ZN5polly13SCEVAffinator5visitEPKN4llvm4SCEVE'/>
<use f='llvm/polly/lib/Support/SCEVAffinator.cpp' l='411' u='r' c='_ZN5polly13SCEVAffinator15visitAddRecExprEPKN4llvm14SCEVAddRecExprE'/>
<use f='llvm/polly/lib/Support/SCEVAffinator.cpp' l='562' u='r' c='_ZN5polly13SCEVAffinator17complexityBailoutEv'/>
<use f='llvm/polly/lib/Support/SCEVAffinator.cpp' l='563' u='r' c='_ZN5polly13SCEVAffinator17complexityBailoutEv'/>
