<dec f='llvm/polly/include/polly/CodeGen/IslAst.h' l='63' type='polly::Scop &amp;'/>
<offset>0</offset>
<use f='llvm/polly/lib/CodeGen/IslAst.cpp' l='508' u='w' c='_ZN5polly6IslAstC1ERNS_4ScopE'/>
<use f='llvm/polly/lib/CodeGen/IslAst.cpp' l='511' u='w' c='_ZN5polly6IslAstC1EOS0_'/>
<use f='llvm/polly/lib/CodeGen/IslAst.cpp' l='511' u='r' c='_ZN5polly6IslAstC1EOS0_'/>
<use f='llvm/polly/lib/CodeGen/IslAst.cpp' l='524' u='m' c='_ZN5polly6IslAst4initERKNS_11DependencesE'/>
<use f='llvm/polly/lib/CodeGen/IslAst.cpp' l='527' u='a' c='_ZN5polly6IslAst4initERKNS_11DependencesE'/>
<use f='llvm/polly/lib/CodeGen/IslAst.cpp' l='530' u='m' c='_ZN5polly6IslAst4initERKNS_11DependencesE'/>
<use f='llvm/polly/lib/CodeGen/IslAst.cpp' l='535' u='m' c='_ZN5polly6IslAst4initERKNS_11DependencesE'/>
<use f='llvm/polly/lib/CodeGen/IslAst.cpp' l='542' u='m' c='_ZN5polly6IslAst4initERKNS_11DependencesE'/>
<use f='llvm/polly/lib/CodeGen/IslAst.cpp' l='545' u='m' c='_ZN5polly6IslAst4initERKNS_11DependencesE'/>
<use f='llvm/polly/lib/CodeGen/IslAst.cpp' l='566' u='a' c='_ZN5polly6IslAst4initERKNS_11DependencesE'/>
<use f='llvm/polly/lib/CodeGen/IslAst.cpp' l='568' u='m' c='_ZN5polly6IslAst4initERKNS_11DependencesE'/>
