<use f='llvm/polly/include/polly/CodeGen/IslAst.h' l='208' u='w' c='_ZN5polly17IslAstPrinterPassC1ERN4llvm11raw_ostreamE'/>
<dec f='llvm/polly/include/polly/CodeGen/IslAst.h' l='213' type='llvm::raw_ostream &amp;'/>
<offset>0</offset>
<use f='llvm/polly/lib/CodeGen/IslAst.cpp' l='781' u='a' c='_ZN5polly17IslAstPrinterPass3runERNS_4ScopERN4llvm15AnalysisManagerIS1_JRNS_27ScopStandardAnalysisResultsEEEES6_RNS_10SPMUpdaterE'/>
