<dec f='llvm/polly/include/polly/ScheduleOptimizer.h' l='67' type='int'/>
<use f='llvm/polly/lib/Transform/ScheduleOptimizer.cpp' l='660' u='a' c='_ZL27isMatMulNonScalarReadAccessPN5polly12MemoryAccessERNS_12MatMulInfoTyE'/>
<use f='llvm/polly/lib/Transform/ScheduleOptimizer.cpp' l='664' u='a' c='_ZL27isMatMulNonScalarReadAccessPN5polly12MemoryAccessERNS_12MatMulInfoTyE'/>
<use f='llvm/polly/lib/Transform/ScheduleOptimizer.cpp' l='697' u='r' c='_ZL23containsOnlyMatrMultAccN3isl12noexceptions3mapERN5polly12MatMulInfoTyE'/>
<use f='llvm/polly/lib/Transform/ScheduleOptimizer.cpp' l='790' u='a' c='_ZL16containsMatrMultN3isl12noexceptions3mapEPKN5polly11DependencesERNS2_12MatMulInfoTyE'/>
<use f='llvm/polly/lib/Transform/ScheduleOptimizer.cpp' l='1289' u='r' c='_ZN21ScheduleTreeOptimizer21optimizeMatMulPatternEN3isl12noexceptions13schedule_nodeEPKN4llvm19TargetTransformInfoERN5polly12MatMulInfoTyE'/>
<use f='llvm/polly/lib/Transform/ScheduleOptimizer.cpp' l='1289' u='r' c='_ZN21ScheduleTreeOptimizer21optimizeMatMulPatternEN3isl12noexceptions13schedule_nodeEPKN4llvm19TargetTransformInfoERN5polly12MatMulInfoTyE'/>
<offset>320</offset>
