<dec f='llvm/polly/include/polly/ScopDetectionDiagnostic.h' l='584' type='llvm::Loop *'/>
<use f='llvm/polly/include/polly/ScopDetectionDiagnostic.h' l='590' u='w' c='_ZN5polly26ReportLoopHasMultipleExitsC1EPN4llvm4LoopE'/>
<offset>128</offset>
<doc f='llvm/polly/include/polly/ScopDetectionDiagnostic.h' l='583'>/// The loop that has multiple exits.</doc>
<use f='llvm/polly/lib/Analysis/ScopDetectionDiagnostic.cpp' l='502' u='r' c='_ZNK5polly26ReportLoopHasMultipleExits11getRemarkBBEv'/>
<use f='llvm/polly/lib/Analysis/ScopDetectionDiagnostic.cpp' l='506' u='r' c='_ZNK5polly26ReportLoopHasMultipleExits10getMessageB5cxx11Ev'/>
