<dec f='llvm/polly/include/polly/ScopDetectionDiagnostic.h' l='199' type='llvm::BasicBlock *'/>
<use f='llvm/polly/include/polly/ScopDetectionDiagnostic.h' l='203' u='w' c='_ZN5polly23ReportInvalidTerminatorC1EPN4llvm10BasicBlockE'/>
<offset>128</offset>
<use f='llvm/polly/lib/Analysis/ScopDetectionDiagnostic.cpp' l='204' u='r' c='_ZNK5polly23ReportInvalidTerminator11getRemarkBBEv'/>
<use f='llvm/polly/lib/Analysis/ScopDetectionDiagnostic.cpp' l='207' u='r' c='_ZNK5polly23ReportInvalidTerminator10getMessageB5cxx11Ev'/>
<use f='llvm/polly/lib/Analysis/ScopDetectionDiagnostic.cpp' l='211' u='r' c='_ZNK5polly23ReportInvalidTerminator11getDebugLocEv'/>
