<dec f='llvm/polly/include/polly/ScopDetectionDiagnostic.h' l='373' type='const llvm::SCEV *'/>
<use f='llvm/polly/include/polly/ScopDetectionDiagnostic.h' l='380' u='w' c='_ZN5polly18ReportNonAffBranchC1EPN4llvm10BasicBlockEPKNS1_4SCEVES6_PKNS1_11InstructionE'/>
<use f='llvm/polly/include/polly/ScopDetectionDiagnostic.h' l='383' u='r' c='_ZN5polly18ReportNonAffBranch3lhsEv'/>
<offset>256</offset>
<doc f='llvm/polly/include/polly/ScopDetectionDiagnostic.h' l='371'>/// LHS &amp; RHS of the failed condition.
  //@{</doc>
<use f='llvm/polly/lib/Analysis/ScopDetectionDiagnostic.cpp' l='333' u='r' c='_ZNK5polly18ReportNonAffBranch10getMessageB5cxx11Ev'/>
