<dec f='llvm/polly/include/polly/ScheduleOptimizer.h' l='62' type='polly::MemoryAccess *'/>
<use f='llvm/polly/lib/Transform/ScheduleOptimizer.cpp' l='664' u='r' c='_ZL27isMatMulNonScalarReadAccessPN5polly12MemoryAccessERNS_12MatMulInfoTyE'/>
<use f='llvm/polly/lib/Transform/ScheduleOptimizer.cpp' l='665' u='w' c='_ZL27isMatMulNonScalarReadAccessPN5polly12MemoryAccessERNS_12MatMulInfoTyE'/>
<use f='llvm/polly/lib/Transform/ScheduleOptimizer.cpp' l='796' u='r' c='_ZL16containsMatrMultN3isl12noexceptions3mapEPKN5polly11DependencesERNS2_12MatMulInfoTyE'/>
<use f='llvm/polly/lib/Transform/ScheduleOptimizer.cpp' l='866' u='r' c='_ZL22getMatMulAlignTypeSizeN5polly12MatMulInfoTyE'/>
<use f='llvm/polly/lib/Transform/ScheduleOptimizer.cpp' l='881' u='r' c='_ZL17getMatMulTypeSizeN5polly12MatMulInfoTyE'/>
<use f='llvm/polly/lib/Transform/ScheduleOptimizer.cpp' l='1110' u='r' c='_ZL32optimizeDataLayoutMatrMulPatternN3isl12noexceptions13schedule_nodeENS0_3mapE19MicroKernelParamsTy19MacroKernelParamsTyRN5polly12MatMulInfoTyE'/>
<use f='llvm/polly/lib/Transform/ScheduleOptimizer.cpp' l='1113' u='r' c='_ZL32optimizeDataLayoutMatrMulPatternN3isl12noexceptions13schedule_nodeENS0_3mapE19MicroKernelParamsTy19MacroKernelParamsTyRN5polly12MatMulInfoTyE'/>
<use f='llvm/polly/lib/Transform/ScheduleOptimizer.cpp' l='1114' u='r' c='_ZL32optimizeDataLayoutMatrMulPatternN3isl12noexceptions13schedule_nodeENS0_3mapE19MicroKernelParamsTy19MacroKernelParamsTyRN5polly12MatMulInfoTyE'/>
<use f='llvm/polly/lib/Transform/ScheduleOptimizer.cpp' l='1125' u='r' c='_ZL32optimizeDataLayoutMatrMulPatternN3isl12noexceptions13schedule_nodeENS0_3mapE19MicroKernelParamsTy19MacroKernelParamsTyRN5polly12MatMulInfoTyE'/>
<offset>64</offset>
