<dec f='llvm/polly/include/polly/DependenceInfo.h' l='257' type='polly::Scop *'/>
<use f='llvm/polly/lib/Analysis/DependenceInfo.cpp' l='869' u='r' c='_ZN5polly14DependenceInfo20recomputeDependencesENS_11Dependences13AnalysisLevelE'/>
<use f='llvm/polly/lib/Analysis/DependenceInfo.cpp' l='870' u='r' c='_ZN5polly14DependenceInfo20recomputeDependencesENS_11Dependences13AnalysisLevelE'/>
<use f='llvm/polly/lib/Analysis/DependenceInfo.cpp' l='875' u='w' c='_ZN5polly14DependenceInfo9runOnScopERNS_4ScopE'/>
<offset>320</offset>
