<dec f='llvm/polly/include/polly/CodeGen/IslExprBuilder.h' l='204' type='const llvm::DataLayout &amp;'/>
<offset>384</offset>
<use f='llvm/polly/lib/CodeGen/IslExprBuilder.cpp' l='45' u='w' c='_ZN5polly14IslExprBuilderC1ERNS_4ScopERN4llvm9IRBuilderINS3_14ConstantFolderENS_10IRInserterEEERNS3_9MapVectorIP6isl_idNS3_11AssertingVHINS3_5ValueEEE5325692'/>
<use f='llvm/polly/lib/CodeGen/IslExprBuilder.cpp' l='321' u='r' c='_ZN5polly14IslExprBuilder19createAccessAddressEP12isl_ast_expr'/>
<use f='llvm/polly/lib/CodeGen/IslExprBuilder.cpp' l='506' u='m' c='_ZN5polly14IslExprBuilder12createOpICmpEP12isl_ast_expr'/>
<use f='llvm/polly/lib/CodeGen/IslExprBuilder.cpp' l='730' u='m' c='_ZN5polly14IslExprBuilder8createIdEP12isl_ast_expr'/>
