<dec f='llvm/polly/include/polly/Support/SCEVAffinator.h' l='68' type='llvm::BasicBlock *'/>
<offset>512</offset>
<use f='llvm/polly/lib/Support/SCEVAffinator.cpp' l='87' u='r' c='_ZN5polly13SCEVAffinator8getScopeEv'/>
<use f='llvm/polly/lib/Support/SCEVAffinator.cpp' l='87' u='r' c='_ZN5polly13SCEVAffinator8getScopeEv'/>
<use f='llvm/polly/lib/Support/SCEVAffinator.cpp' l='106' u='r' c='_ZN5polly13SCEVAffinator25takeNonNegativeAssumptionERSt4pairIN3isl12noexceptions6pw_affENS3_3setEEPN4llvm11SmallVectorINS_10AssumptionELj8EEE'/>
<use f='llvm/polly/lib/Support/SCEVAffinator.cpp' l='107' u='r' c='_ZN5polly13SCEVAffinator25takeNonNegativeAssumptionERSt4pairIN3isl12noexceptions6pw_affENS3_3setEEPN4llvm11SmallVectorINS_10AssumptionELj8EEE'/>
<use f='llvm/polly/lib/Support/SCEVAffinator.cpp' l='107' u='r' c='_ZN5polly13SCEVAffinator25takeNonNegativeAssumptionERSt4pairIN3isl12noexceptions6pw_affENS3_3setEEPN4llvm11SmallVectorINS_10AssumptionELj8EEE'/>
<use f='llvm/polly/lib/Support/SCEVAffinator.cpp' l='109' u='r' c='_ZN5polly13SCEVAffinator25takeNonNegativeAssumptionERSt4pairIN3isl12noexceptions6pw_affENS3_3setEEPN4llvm11SmallVectorINS_10AssumptionELj8EEE'/>
<use f='llvm/polly/lib/Support/SCEVAffinator.cpp' l='118' u='w' c='_ZN5polly13SCEVAffinator8getPwAffEPKN4llvm4SCEVEPNS1_10BasicBlockEPNS1_11SmallVectorINS_10AssumptionELj8EEE'/>
<use f='llvm/polly/lib/Support/SCEVAffinator.cpp' l='147' u='r' c='_ZNK5polly13SCEVAffinator16checkForWrappingEPKN4llvm4SCEVESt4pairIN3isl12noexceptions6pw_affENS7_3setEE'/>
<use f='llvm/polly/lib/Support/SCEVAffinator.cpp' l='147' u='r' c='_ZNK5polly13SCEVAffinator16checkForWrappingEPKN4llvm4SCEVESt4pairIN3isl12noexceptions6pw_affENS7_3setEE'/>
<use f='llvm/polly/lib/Support/SCEVAffinator.cpp' l='148' u='r' c='_ZNK5polly13SCEVAffinator16checkForWrappingEPKN4llvm4SCEVESt4pairIN3isl12noexceptions6pw_affENS7_3setEE'/>
<use f='llvm/polly/lib/Support/SCEVAffinator.cpp' l='154' u='r' c='_ZNK5polly13SCEVAffinator16checkForWrappingEPKN4llvm4SCEVESt4pairIN3isl12noexceptions6pw_affENS7_3setEE'/>
<use f='llvm/polly/lib/Support/SCEVAffinator.cpp' l='198' u='a' c='_ZN5polly13SCEVAffinator5visitEPKN4llvm4SCEVE'/>
<use f='llvm/polly/lib/Support/SCEVAffinator.cpp' l='296' u='r' c='_ZN5polly13SCEVAffinator17visitTruncateExprEPKN4llvm16SCEVTruncateExprE'/>
<use f='llvm/polly/lib/Support/SCEVAffinator.cpp' l='303' u='r' c='_ZN5polly13SCEVAffinator17visitTruncateExprEPKN4llvm16SCEVTruncateExprE'/>
<use f='llvm/polly/lib/Support/SCEVAffinator.cpp' l='561' u='r' c='_ZN5polly13SCEVAffinator17complexityBailoutEv'/>
<use f='llvm/polly/lib/Support/SCEVAffinator.cpp' l='561' u='r' c='_ZN5polly13SCEVAffinator17complexityBailoutEv'/>
