<dec f='llvm/polly/include/polly/ScopDetectionDiagnostic.h' l='247' type='llvm::BasicBlock *'/>
<use f='llvm/polly/include/polly/ScopDetectionDiagnostic.h' l='252' u='w' c='_ZN5polly23ReportUnreachableInExitC1EPN4llvm10BasicBlockENS1_8DebugLocE'/>
<offset>128</offset>
<use f='llvm/polly/lib/Analysis/ScopDetectionDiagnostic.cpp' l='225' u='r' c='_ZNK5polly23ReportUnreachableInExit11getRemarkBBEv'/>
<use f='llvm/polly/lib/Analysis/ScopDetectionDiagnostic.cpp' l='228' u='r' c='_ZNK5polly23ReportUnreachableInExit10getMessageB5cxx11Ev'/>
