<use f='llvm/polly/include/polly/DependenceInfo.h' l='249' c='_ZN5polly14DependenceInfo13releaseMemoryEv'/>
<dec f='llvm/polly/include/polly/DependenceInfo.h' l='260' type='std::unique_ptr&lt;Dependences&gt; [3]'/>
<use f='llvm/polly/lib/Analysis/DependenceInfo.cpp' l='861' u='m' c='_ZN5polly14DependenceInfo14getDependencesENS_11Dependences13AnalysisLevelE'/>
<use f='llvm/polly/lib/Analysis/DependenceInfo.cpp' l='869' u='m' c='_ZN5polly14DependenceInfo20recomputeDependencesENS_11Dependences13AnalysisLevelE'/>
<use f='llvm/polly/lib/Analysis/DependenceInfo.cpp' l='870' u='m' c='_ZN5polly14DependenceInfo20recomputeDependencesENS_11Dependences13AnalysisLevelE'/>
<use f='llvm/polly/lib/Analysis/DependenceInfo.cpp' l='871' u='m' c='_ZN5polly14DependenceInfo20recomputeDependencesENS_11Dependences13AnalysisLevelE'/>
<use f='llvm/polly/lib/Analysis/DependenceInfo.cpp' l='882' u='m' c='_ZNK5polly14DependenceInfo9printScopERN4llvm11raw_ostreamERNS_4ScopE'/>
<offset>384</offset>
<doc f='llvm/polly/include/polly/DependenceInfo.h' l='259'>/// Dependences struct for the current SCoP.</doc>
