<use f='llvm/polly/include/polly/Simplify.h' l='160' u='w' c='_ZN5polly19SimplifyPrinterPassC1ERN4llvm11raw_ostreamEi'/>
<dec f='llvm/polly/include/polly/Simplify.h' l='165' type='llvm::raw_ostream &amp;'/>
<offset>0</offset>
<use f='llvm/polly/lib/Transform/Simplify.cpp' l='724' u='a' c='_ZN5polly19SimplifyPrinterPass3runERNS_4ScopERN4llvm15AnalysisManagerIS1_JRNS_27ScopStandardAnalysisResultsEEEES6_RNS_10SPMUpdaterE'/>
