<dec f='llvm/polly/include/polly/ScopDetectionDiagnostic.h' l='524' type='llvm::Loop *'/>
<offset>128</offset>
<doc f='llvm/polly/include/polly/ScopDetectionDiagnostic.h' l='523'>// The offending loop.</doc>
<use f='llvm/polly/lib/Analysis/ScopDetectionDiagnostic.cpp' l='449' u='w' c='_ZN5polly15ReportLoopBoundC1EPN4llvm4LoopEPKNS1_4SCEVE'/>
<use f='llvm/polly/lib/Analysis/ScopDetectionDiagnostic.cpp' l='454' u='r' c='_ZNK5polly15ReportLoopBound11getRemarkBBEv'/>
<use f='llvm/polly/lib/Analysis/ScopDetectionDiagnostic.cpp' l='458' u='r' c='_ZNK5polly15ReportLoopBound10getMessageB5cxx11Ev'/>
