<dec f='llvm/polly/include/polly/ScopInfo.h' l='1100' type='polly::MemoryAccess *'/>
<offset>0</offset>
<doc f='llvm/polly/include/polly/ScopInfo.h' l='1099'>/// The memory access that is (partially) invariant.</doc>
<use f='llvm/polly/lib/Analysis/ScopBuilder.cpp' l='2786' u='r' c='_ZN5polly11ScopBuilder19hoistInvariantLoadsEv'/>
<use f='llvm/polly/lib/Analysis/ScopBuilder.cpp' l='2997' u='r' c='_ZN5polly11ScopBuilder17addInvariantLoadsERNS_8ScopStmtERN4llvm11SmallVectorINS_15InvariantAccessELj8EEE'/>
<use f='llvm/polly/lib/Analysis/ScopBuilder.cpp' l='3008' u='r' c='_ZN5polly11ScopBuilder17addInvariantLoadsERNS_8ScopStmtERN4llvm11SmallVectorINS_15InvariantAccessELj8EEE'/>
<use f='llvm/polly/lib/Analysis/ScopBuilder.cpp' l='3028' u='r' c='_ZN5polly11ScopBuilder17addInvariantLoadsERNS_8ScopStmtERN4llvm11SmallVectorINS_15InvariantAccessELj8EEE'/>
