<dec f='llvm/polly/include/polly/ScopInfo.h' l='2728' type='std::unique_ptr&lt;Scop&gt;'/>
<use f='llvm/polly/include/polly/ScopInfo.h' l='2742' u='m' c='_ZN5polly18ScopInfoRegionPass7getScopEv'/>
<use f='llvm/polly/include/polly/ScopInfo.h' l='2743' u='m' c='_ZNK5polly18ScopInfoRegionPass7getScopEv'/>
<use f='llvm/polly/include/polly/ScopInfo.h' l='2748' u='m' c='_ZN5polly18ScopInfoRegionPass13releaseMemoryEv'/>
<offset>256</offset>
<doc f='llvm/polly/include/polly/ScopInfo.h' l='2727'>/// The Scop pointer which is used to construct a Scop.</doc>
<use f='llvm/polly/lib/Analysis/ScopInfo.cpp' l='2719' u='w' c='_ZN5polly18ScopInfoRegionPass11runOnRegionEPN4llvm6RegionERNS1_13RGPassManagerE'/>
<use f='llvm/polly/lib/Analysis/ScopInfo.cpp' l='2722' u='m' c='_ZN5polly18ScopInfoRegionPass11runOnRegionEPN4llvm6RegionERNS1_13RGPassManagerE'/>
<use f='llvm/polly/lib/Analysis/ScopInfo.cpp' l='2724' u='m' c='_ZN5polly18ScopInfoRegionPass11runOnRegionEPN4llvm6RegionERNS1_13RGPassManagerE'/>
<use f='llvm/polly/lib/Analysis/ScopInfo.cpp' l='2725' u='m' c='_ZN5polly18ScopInfoRegionPass11runOnRegionEPN4llvm6RegionERNS1_13RGPassManagerE'/>
<use f='llvm/polly/lib/Analysis/ScopInfo.cpp' l='2733' u='m' c='_ZNK5polly18ScopInfoRegionPass5printERN4llvm11raw_ostreamEPKNS1_6ModuleE'/>
<use f='llvm/polly/lib/Analysis/ScopInfo.cpp' l='2734' u='m' c='_ZNK5polly18ScopInfoRegionPass5printERN4llvm11raw_ostreamEPKNS1_6ModuleE'/>
