<dec f='llvm/polly/include/polly/ScopDetectionDiagnostic.h' l='556' type='llvm::Loop *'/>
<use f='llvm/polly/include/polly/ScopDetectionDiagnostic.h' l='562' u='w' c='_ZN5polly19ReportLoopHasNoExitC1EPN4llvm4LoopE'/>
<offset>128</offset>
<doc f='llvm/polly/include/polly/ScopDetectionDiagnostic.h' l='555'>/// The loop that has no exit.</doc>
<use f='llvm/polly/lib/Analysis/ScopDetectionDiagnostic.cpp' l='478' u='r' c='_ZNK5polly19ReportLoopHasNoExit11getRemarkBBEv'/>
<use f='llvm/polly/lib/Analysis/ScopDetectionDiagnostic.cpp' l='481' u='r' c='_ZNK5polly19ReportLoopHasNoExit10getMessageB5cxx11Ev'/>
