<dec f='llvm/polly/include/polly/ScopBuilder.h' l='776' type='llvm::Loop *'/>
<use f='llvm/polly/include/polly/ScopBuilder.h' l='786' u='w' c='_ZN5polly11ScopBuilder16LoopStackElementC1EPN4llvm4LoopEN3isl12noexceptions8scheduleEj'/>
<use f='llvm/polly/lib/Analysis/ScopBuilder.cpp' l='1238' u='r' c='_ZN5polly11ScopBuilder13buildScheduleEPN4llvm6RegionERNS1_11SmallVectorINS0_16LoopStackElementELj4EEE'/>
<use f='llvm/polly/lib/Analysis/ScopBuilder.cpp' l='1280' u='r' c='_ZN5polly11ScopBuilder13buildScheduleEPN4llvm10RegionNodeERNS1_11SmallVectorINS0_16LoopStackElementELj4EEE'/>
<use f='llvm/polly/lib/Analysis/ScopBuilder.cpp' l='1281' u='r' c='_ZN5polly11ScopBuilder13buildScheduleEPN4llvm10RegionNodeERNS1_11SmallVectorINS0_16LoopStackElementELj4EEE'/>
<offset>0</offset>
<doc f='llvm/polly/include/polly/ScopBuilder.h' l='775'>// The loop for which we keep information.</doc>
