<dec f='llvm/polly/include/polly/ScopInfo.h' l='414' type='polly::Scop &amp;'/>
<offset>1664</offset>
<doc f='llvm/polly/include/polly/ScopInfo.h' l='413'>/// The scop this SAI object belongs to.</doc>
<use f='llvm/polly/lib/Analysis/ScopInfo.cpp' l='232' u='w' c='_ZN5polly13ScopArrayInfoC1EPN4llvm5ValueEPNS1_4TypeEN3isl12noexceptions3ctxENS1_8ArrayRefIPKNS1_4SCEVEEENS_10MemoryKindERKNS1_10DataLayoutEPNS_4ScopEPKc'/>
<use f='llvm/polly/lib/Analysis/ScopInfo.cpp' l='261' u='m' c='_ZN5polly13ScopArrayInfo10isReadOnlyEv'/>
<use f='llvm/polly/lib/Analysis/ScopInfo.cpp' l='313' u='m' c='_ZN5polly13ScopArrayInfo14applyAndSetFADEPN4llvm5ValueE'/>
<use f='llvm/polly/lib/Analysis/ScopInfo.cpp' l='317' u='m' c='_ZN5polly13ScopArrayInfo14applyAndSetFADEPN4llvm5ValueE'/>
<use f='llvm/polly/lib/Analysis/ScopInfo.cpp' l='353' u='m' c='_ZN5polly13ScopArrayInfo11updateSizesEN4llvm8ArrayRefIPKNS1_4SCEVEEEb'/>
