<dec f='llvm/polly/include/polly/ScopDetectionDiagnostic.h' l='612' type='llvm::Loop *'/>
<use f='llvm/polly/include/polly/ScopDetectionDiagnostic.h' l='618' u='w' c='_ZN5polly25ReportLoopOnlySomeLatchesC1EPN4llvm4LoopE'/>
<offset>128</offset>
<doc f='llvm/polly/include/polly/ScopDetectionDiagnostic.h' l='611'>/// The loop for which not all loop latches are part of the scop.</doc>
<use f='llvm/polly/lib/Analysis/ScopDetectionDiagnostic.cpp' l='527' u='r' c='_ZNK5polly25ReportLoopOnlySomeLatches11getRemarkBBEv'/>
<use f='llvm/polly/lib/Analysis/ScopDetectionDiagnostic.cpp' l='531' u='r' c='_ZNK5polly25ReportLoopOnlySomeLatches10getMessageB5cxx11Ev'/>
