<dec f='llvm/polly/include/polly/CodeGen/IslAst.h' l='112' type='polly::Scop &amp;'/>
<use f='llvm/polly/include/polly/CodeGen/IslAst.h' l='116' u='w' c='_ZN5polly10IslAstInfoC1ERNS_4ScopERKNS_11DependencesE'/>
<offset>0</offset>
<use f='llvm/polly/lib/CodeGen/IslAst.cpp' l='723' u='m' c='_ZN5polly10IslAstInfo5printERN4llvm11raw_ostreamE'/>
<use f='llvm/polly/lib/CodeGen/IslAst.cpp' l='725' u='m' c='_ZN5polly10IslAstInfo5printERN4llvm11raw_ostreamE'/>
<use f='llvm/polly/lib/CodeGen/IslAst.cpp' l='740' u='m' c='_ZN5polly10IslAstInfo5printERN4llvm11raw_ostreamE'/>
<use f='llvm/polly/lib/CodeGen/IslAst.cpp' l='747' u='m' c='_ZN5polly10IslAstInfo5printERN4llvm11raw_ostreamE'/>
<use f='llvm/polly/lib/CodeGen/IslAst.cpp' l='756' u='m' c='_ZN5polly10IslAstInfo5printERN4llvm11raw_ostreamE'/>
