<dec f='llvm/polly/include/polly/ScopDetectionDiagnostic.h' l='369' type='llvm::BasicBlock *'/>
<use f='llvm/polly/include/polly/ScopDetectionDiagnostic.h' l='380' u='w' c='_ZN5polly18ReportNonAffBranchC1EPN4llvm10BasicBlockEPKNS1_4SCEVES6_PKNS1_11InstructionE'/>
<offset>192</offset>
<doc f='llvm/polly/include/polly/ScopDetectionDiagnostic.h' l='368'>// The BasicBlock we found the non-affine branch in.</doc>
<use f='llvm/polly/lib/Analysis/ScopDetectionDiagnostic.cpp' l='329' u='r' c='_ZNK5polly18ReportNonAffBranch11getRemarkBBEv'/>
<use f='llvm/polly/lib/Analysis/ScopDetectionDiagnostic.cpp' l='332' u='r' c='_ZNK5polly18ReportNonAffBranch10getMessageB5cxx11Ev'/>
