<dec f='llvm/polly/include/polly/Support/ScopHelper.h' l='70' type='llvm::BasicBlock *'/>
<offset>192</offset>
<doc f='llvm/polly/include/polly/Support/ScopHelper.h' l='69'>/// An optional block whose domain can simplify the assumption.</doc>
<use f='llvm/polly/lib/Analysis/ScopBuilder.cpp' l='1496' u='r' c='_ZN5polly11ScopBuilder22addRecordedAssumptionsEv'/>
<use f='llvm/polly/lib/Analysis/ScopBuilder.cpp' l='1503' u='r' c='_ZN5polly11ScopBuilder22addRecordedAssumptionsEv'/>
<use f='llvm/polly/lib/Analysis/ScopBuilder.cpp' l='1522' u='r' c='_ZN5polly11ScopBuilder22addRecordedAssumptionsEv'/>
