<dec f='llvm/polly/include/polly/ScopInfo.h' l='411' type='const llvm::DataLayout &amp;'/>
<offset>1600</offset>
<doc f='llvm/polly/include/polly/ScopInfo.h' l='410'>/// The data layout of the module.</doc>
<use f='llvm/polly/lib/Analysis/ScopInfo.cpp' l='232' u='w' c='_ZN5polly13ScopArrayInfoC1EPN4llvm5ValueEPNS1_4TypeEN3isl12noexceptions3ctxENS1_8ArrayRefIPKNS1_4SCEVEEENS_10MemoryKindERKNS1_10DataLayoutEPNS_4ScopEPKc'/>
<use f='llvm/polly/lib/Analysis/ScopInfo.cpp' l='286' u='m' c='_ZN5polly13ScopArrayInfo17updateElementTypeEPN4llvm4TypeE'/>
<use f='llvm/polly/lib/Analysis/ScopInfo.cpp' l='287' u='m' c='_ZN5polly13ScopArrayInfo17updateElementTypeEPN4llvm4TypeE'/>
<use f='llvm/polly/lib/Analysis/ScopInfo.cpp' l='362' u='m' c='_ZNK5polly13ScopArrayInfo18getElemSizeInBytesEv'/>
