<dec f='llvm/polly/include/polly/ScopBuilder.h' l='38' type='const llvm::DataLayout &amp;'/>
<use f='llvm/polly/lib/Analysis/ScopBuilder.cpp' l='1624' u='m' c='_ZN5polly11ScopBuilder24buildAccessMultiDimFixedENS_10MemAccInstEPNS_8ScopStmtE'/>
<use f='llvm/polly/lib/Analysis/ScopBuilder.cpp' l='1625' u='m' c='_ZN5polly11ScopBuilder24buildAccessMultiDimFixedENS_10MemAccInstEPNS_8ScopStmtE'/>
<use f='llvm/polly/lib/Analysis/ScopBuilder.cpp' l='1683' u='m' c='_ZN5polly11ScopBuilder24buildAccessMultiDimParamENS_10MemAccInstEPNS_8ScopStmtE'/>
<use f='llvm/polly/lib/Analysis/ScopBuilder.cpp' l='3789' u='w' c='_ZN5polly11ScopBuilderC1EPN4llvm6RegionERNS1_15AssumptionCacheERNS1_9AAResultsERKNS1_10DataLayoutERNS1_13DominatorTreeERNS1_8LoopInfoERNS_13ScopDetect5687132'/>
<offset>64</offset>
<doc f='llvm/polly/include/polly/ScopBuilder.h' l='37'>/// Target data for element size computing.</doc>
