<dec f='llvm/polly/include/polly/CodeGen/PerfMonitor.h' l='46' type='const polly::Scop &amp;'/>
<offset>1216</offset>
<doc f='llvm/polly/include/polly/CodeGen/PerfMonitor.h' l='45'>// The scop to profile against.</doc>
<use f='llvm/polly/lib/CodeGen/PerfMonitor.cpp' l='65' u='w' c='_ZN5polly11PerfMonitorC1ERKNS_4ScopEPN4llvm6ModuleE'/>
<use f='llvm/polly/lib/CodeGen/PerfMonitor.cpp' l='94' u='r' c='_ZN5polly11PerfMonitor14addScopCounterEv'/>
<use f='llvm/polly/lib/CodeGen/PerfMonitor.cpp' l='185' u='m' c='_ZN5polly11PerfMonitor19AppendScopReportingEv'/>
<use f='llvm/polly/lib/CodeGen/PerfMonitor.cpp' l='189' u='m' c='_ZN5polly11PerfMonitor19AppendScopReportingEv'/>
