<dec f='llvm/polly/include/polly/ScopPass.h' l='150' type='polly::Scop *'/>
<use f='llvm/polly/include/polly/ScopPass.h' l='153' u='w' c='_ZN5polly8ScopPassC1ERc'/>
<offset>256</offset>
<use f='llvm/polly/lib/Analysis/ScopPass.cpp' l='25' u='w' c='_ZN5polly8ScopPass11runOnRegionEPN4llvm6RegionERNS1_13RGPassManagerE'/>
<use f='llvm/polly/lib/Analysis/ScopPass.cpp' l='30' u='w' c='_ZN5polly8ScopPass11runOnRegionEPN4llvm6RegionERNS1_13RGPassManagerE'/>
<use f='llvm/polly/lib/Analysis/ScopPass.cpp' l='31' u='r' c='_ZN5polly8ScopPass11runOnRegionEPN4llvm6RegionERNS1_13RGPassManagerE'/>
<use f='llvm/polly/lib/Analysis/ScopPass.cpp' l='37' u='r' c='_ZNK5polly8ScopPass5printERN4llvm11raw_ostreamEPKNS1_6ModuleE'/>
<use f='llvm/polly/lib/Analysis/ScopPass.cpp' l='38' u='r' c='_ZNK5polly8ScopPass5printERN4llvm11raw_ostreamEPKNS1_6ModuleE'/>
