<use f='llvm/polly/include/polly/DependenceInfo.h' l='215' u='w' c='_ZN5polly25DependenceInfoPrinterPassC1ERN4llvm11raw_ostreamE'/>
<dec f='llvm/polly/include/polly/DependenceInfo.h' l='220' type='llvm::raw_ostream &amp;'/>
<use f='llvm/polly/lib/Analysis/DependenceInfo.cpp' l='847' u='a' c='_ZN5polly25DependenceInfoPrinterPass3runERNS_4ScopERN4llvm15AnalysisManagerIS1_JRNS_27ScopStandardAnalysisResultsEEEES6_RNS_10SPMUpdaterE'/>
<use f='llvm/polly/lib/Analysis/DependenceInfo.cpp' l='854' u='a' c='_ZN5polly25DependenceInfoPrinterPass3runERNS_4ScopERN4llvm15AnalysisManagerIS1_JRNS_27ScopStandardAnalysisResultsEEEES6_RNS_10SPMUpdaterE'/>
<offset>0</offset>
