<dec f='llvm/polly/include/polly/ScopDetectionDiagnostic.h' l='298' type='llvm::BasicBlock *'/>
<use f='llvm/polly/include/polly/ScopDetectionDiagnostic.h' l='302' u='w' c='_ZN5polly15ReportUndefCondC1EPKN4llvm11InstructionEPNS1_10BasicBlockE'/>
<offset>192</offset>
<doc f='llvm/polly/include/polly/ScopDetectionDiagnostic.h' l='297'>// The BasicBlock we found the broken condition in.</doc>
<use f='llvm/polly/lib/Analysis/ScopDetectionDiagnostic.cpp' l='283' u='r' c='_ZNK5polly15ReportUndefCond11getRemarkBBEv'/>
<use f='llvm/polly/lib/Analysis/ScopDetectionDiagnostic.cpp' l='286' u='r' c='_ZNK5polly15ReportUndefCond10getMessageB5cxx11Ev'/>
