<dec f='llvm/polly/include/polly/ScopDetectionDiagnostic.h' l='346' type='llvm::BasicBlock *'/>
<use f='llvm/polly/include/polly/ScopDetectionDiagnostic.h' l='350' u='w' c='_ZN5polly18ReportUndefOperandC1EPN4llvm10BasicBlockEPKNS1_11InstructionE'/>
<offset>192</offset>
<doc f='llvm/polly/include/polly/ScopDetectionDiagnostic.h' l='345'>// The BasicBlock we found the undefined operand in.</doc>
<use f='llvm/polly/lib/Analysis/ScopDetectionDiagnostic.cpp' l='314' u='r' c='_ZNK5polly18ReportUndefOperand11getRemarkBBEv'/>
<use f='llvm/polly/lib/Analysis/ScopDetectionDiagnostic.cpp' l='317' u='r' c='_ZNK5polly18ReportUndefOperand10getMessageB5cxx11Ev'/>
