<dec f='llvm/polly/include/polly/CodeGen/IslExprBuilder.h' l='185' type='polly::Scop &amp;'/>
<offset>64</offset>
<use f='llvm/polly/lib/CodeGen/IslExprBuilder.cpp' l='44' u='w' c='_ZN5polly14IslExprBuilderC1ERNS_4ScopERN4llvm9IRBuilderINS3_14ConstantFolderENS_10IRInserterEEERNS3_9MapVectorIP6isl_idNS3_11AssertingVHINS3_5ValueEEE5325692'/>
<use f='llvm/polly/lib/CodeGen/IslExprBuilder.cpp' l='321' u='a' c='_ZN5polly14IslExprBuilder19createAccessAddressEP12isl_ast_expr'/>
