<dec f='llvm/polly/include/polly/Support/SCEVAffinator.h' l='72' type='const llvm::DataLayout &amp;'/>
<offset>640</offset>
<doc f='llvm/polly/include/polly/Support/SCEVAffinator.h' l='71'>/// Target data for element size computing.</doc>
<use f='llvm/polly/lib/Support/SCEVAffinator.cpp' l='85' u='w' c='_ZN5polly13SCEVAffinatorC1EPNS_4ScopERN4llvm8LoopInfoE'/>
<use f='llvm/polly/lib/Support/SCEVAffinator.cpp' l='161' u='m' c='_ZNK5polly13SCEVAffinator17addModuloSemanticEN3isl12noexceptions6pw_affEPN4llvm4TypeE'/>
<use f='llvm/polly/lib/Support/SCEVAffinator.cpp' l='188' u='m' c='_ZN5polly13SCEVAffinator20computeModuloForExprEPKN4llvm4SCEVE'/>
<use f='llvm/polly/lib/Support/SCEVAffinator.cpp' l='282' u='m' c='_ZN5polly13SCEVAffinator17visitTruncateExprEPKN4llvm16SCEVTruncateExprE'/>
<use f='llvm/polly/lib/Support/SCEVAffinator.cpp' l='363' u='m' c='_ZN5polly13SCEVAffinator19visitZeroExtendExprEPKN4llvm18SCEVZeroExtendExprE'/>
<use f='llvm/polly/lib/Support/SCEVAffinator.cpp' l='488' u='m' c='_ZN5polly13SCEVAffinator13visitUDivExprEPKN4llvm12SCEVUDivExprE'/>
