<dec f='llvm/lld/ELF/Arch/PPC64.cpp' l='75' type='3892314112'/>
<use f='llvm/lld/ELF/Arch/PPCInsns.def' l='10' u='r' c='_ZL18checkPPCLegacyInsnj'/>
<use f='llvm/lld/ELF/Arch/PPC64.cpp' l='440' c='_ZL19isDSFormInstruction13PPCLegacyInsn'/>
<use f='llvm/lld/ELF/Arch/PPCInsns.def' l='10' c='_ZL17getPCRelativeForm13PPCLegacyInsn'/>
<use f='llvm/lld/ELF/Arch/PPCInsns.def' l='10' c='_ZL11getInsnMask13PPCLegacyInsn'/>
