<dec f='llvm/compiler-rt/lib/scudo/standalone/size_class_map.h' l='108' type='const scudo::u8'/>
<use f='llvm/compiler-rt/lib/scudo/standalone/size_class_map.h' l='109' u='r'/>
<use f='llvm/compiler-rt/lib/scudo/standalone/size_class_map.h' l='116' u='r' c='_ZN5scudo17TableSizeClassMap9SizeTableC1Ev'/>
<use f='llvm/compiler-rt/lib/scudo/standalone/size_class_map.h' l='134' u='r' c='_ZN5scudo17TableSizeClassMap9SizeTable12getTableSizeEv'/>
<use f='llvm/compiler-rt/lib/scudo/standalone/size_class_map.h' l='162' c='_ZN5scudo17TableSizeClassMap16getClassIdBySizeEm'/>
