<dec f='llvm/compiler-rt/lib/scudo/standalone/stack_depot.h' l='82' type='scudo::atomic_u64 [524288]'/>
<use f='llvm/compiler-rt/lib/scudo/standalone/stack_depot.h' l='95' u='a' c='_ZN5scudo10StackDepot6insertEPmS1_'/>
<use f='llvm/compiler-rt/lib/scudo/standalone/stack_depot.h' l='103' u='a' c='_ZN5scudo10StackDepot6insertEPmS1_'/>
<use f='llvm/compiler-rt/lib/scudo/standalone/stack_depot.h' l='106' u='a' c='_ZN5scudo10StackDepot6insertEPmS1_'/>
<use f='llvm/compiler-rt/lib/scudo/standalone/stack_depot.h' l='120' u='a' c='_ZNK5scudo10StackDepot4findEjPmS1_'/>
<use f='llvm/compiler-rt/lib/scudo/standalone/stack_depot.h' l='132' u='a' c='_ZNK5scudo10StackDepot4findEjPmS1_'/>
<use f='llvm/compiler-rt/lib/scudo/standalone/stack_depot.h' l='138' u='a' c='_ZNK5scudo10StackDepotixEm'/>
<offset>2097216</offset>
