<dec f='llvm/compiler-rt/lib/scudo/standalone/stack_depot.h' l='18' type='const scudo::u32'/>
<use f='llvm/compiler-rt/lib/scudo/standalone/stack_depot.h' l='26' u='r' c='_ZN5scudo18MurMur2HashBuilder3addEj'/>
<use f='llvm/compiler-rt/lib/scudo/standalone/stack_depot.h' l='28' u='r' c='_ZN5scudo18MurMur2HashBuilder3addEj'/>
<use f='llvm/compiler-rt/lib/scudo/standalone/stack_depot.h' l='29' u='r' c='_ZN5scudo18MurMur2HashBuilder3addEj'/>
<use f='llvm/compiler-rt/lib/scudo/standalone/stack_depot.h' l='35' u='r' c='_ZN5scudo18MurMur2HashBuilder3getEv'/>
