<use f='llvm/compiler-rt/lib/scudo/standalone/mutex.h' l='25' u='w' c='_ZN5scudo11HybridMutex4initEv'/>
<dec f='llvm/compiler-rt/lib/scudo/standalone/mutex.h' l='51' type='scudo::atomic_u32'/>
<offset>0</offset>
<use f='llvm/compiler-rt/lib/scudo/standalone/linux.cpp' l='100' u='a' c='_ZN5scudo11HybridMutex7tryLockEv'/>
<use f='llvm/compiler-rt/lib/scudo/standalone/linux.cpp' l='105' u='a' c='_ZN5scudo11HybridMutex8lockSlowEv'/>
<use f='llvm/compiler-rt/lib/scudo/standalone/linux.cpp' l='109' u='a' c='_ZN5scudo11HybridMutex8lockSlowEv'/>
<use f='llvm/compiler-rt/lib/scudo/standalone/linux.cpp' l='111' u='a' c='_ZN5scudo11HybridMutex8lockSlowEv'/>
<use f='llvm/compiler-rt/lib/scudo/standalone/linux.cpp' l='113' u='a' c='_ZN5scudo11HybridMutex8lockSlowEv'/>
<use f='llvm/compiler-rt/lib/scudo/standalone/linux.cpp' l='118' u='a' c='_ZN5scudo11HybridMutex6unlockEv'/>
<use f='llvm/compiler-rt/lib/scudo/standalone/linux.cpp' l='119' u='a' c='_ZN5scudo11HybridMutex6unlockEv'/>
<use f='llvm/compiler-rt/lib/scudo/standalone/linux.cpp' l='120' u='a' c='_ZN5scudo11HybridMutex6unlockEv'/>
