<dec f='llvm/compiler-rt/lib/scudo/standalone/stack_depot.h' l='21' type='scudo::u32'/>
<use f='llvm/compiler-rt/lib/scudo/standalone/stack_depot.h' l='24' u='w' c='_ZN5scudo18MurMur2HashBuilderC1Ej'/>
<use f='llvm/compiler-rt/lib/scudo/standalone/stack_depot.h' l='29' u='w' c='_ZN5scudo18MurMur2HashBuilder3addEj'/>
<use f='llvm/compiler-rt/lib/scudo/standalone/stack_depot.h' l='30' u='w' c='_ZN5scudo18MurMur2HashBuilder3addEj'/>
<use f='llvm/compiler-rt/lib/scudo/standalone/stack_depot.h' l='33' u='r' c='_ZN5scudo18MurMur2HashBuilder3getEv'/>
<offset>0</offset>
