<dec f='llvm/compiler-rt/lib/scudo/standalone/size_class_map.h' l='64' type='const scudo::u8'/>
<use f='llvm/compiler-rt/lib/scudo/standalone/size_class_map.h' l='65' u='r'/>
<use f='llvm/compiler-rt/lib/scudo/standalone/size_class_map.h' l='74' u='r'/>
<use f='llvm/compiler-rt/lib/scudo/standalone/size_class_map.h' l='84' u='r' c='_ZN5scudo17FixedSizeClassMap16getSizeByClassIdEm'/>
<use f='llvm/compiler-rt/lib/scudo/standalone/size_class_map.h' l='85' u='r' c='_ZN5scudo17FixedSizeClassMap16getSizeByClassIdEm'/>
<use f='llvm/compiler-rt/lib/scudo/standalone/size_class_map.h' l='95' c='_ZN5scudo17FixedSizeClassMap16getClassIdBySizeEm'/>
