<def f='llvm/llvm/utils/unittest/googletest/include/gtest/internal/gtest-port.h' l='1165' ll='1235'/>
<use f='llvm/llvm/utils/unittest/googletest/include/gtest/internal/gtest-port.h' l='1169' c='_ZN7testing8internal2REC1ERKS1_'/>
<use f='llvm/llvm/utils/unittest/googletest/include/gtest/internal/gtest-port.h' l='1193' c='_ZN7testing8internal2RE9FullMatchERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKS1_'/>
<use f='llvm/llvm/utils/unittest/googletest/include/gtest/internal/gtest-port.h' l='1196' c='_ZN7testing8internal2RE12PartialMatchERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKS1_'/>
<use f='llvm/llvm/utils/unittest/googletest/include/gtest/internal/gtest-port.h' l='1211' c='_ZN7testing8internal2RE9FullMatchEPKcRKS1_'/>
<use f='llvm/llvm/utils/unittest/googletest/include/gtest/internal/gtest-port.h' l='1212' c='_ZN7testing8internal2RE12PartialMatchEPKcRKS1_'/>
<use f='llvm/llvm/utils/unittest/googletest/include/gtest/internal/gtest-port.h' l='1234' c='_ZN7testing8internal2REaSERKS1_'/>
<use f='llvm/llvm/utils/unittest/googletest/include/gtest/internal/gtest-death-test-internal.h' l='79' c='_ZN7testing8internal9DeathTest6CreateEPKcPKNS0_2REES3_iPPS1_'/>
<use f='llvm/llvm/utils/unittest/googletest/include/gtest/internal/gtest-death-test-internal.h' l='143' c='_ZN7testing8internal16DeathTestFactory6CreateEPKcPKNS0_2REES3_iPPNS0_9DeathTestE'/>
<use f='llvm/llvm/utils/unittest/googletest/include/gtest/internal/gtest-death-test-internal.h' l='150' c='_ZN7testing8internal23DefaultDeathTestFactory6CreateEPKcPKNS0_2REES3_iPPNS0_9DeathTestE'/>
<use f='llvm/llvm/utils/unittest/googlemock/include/gmock/gmock-matchers.h' l='1330' c='_ZN7testing8internal19MatchesRegexMatcherC1EPKNS0_2REEb'/>
<use f='llvm/llvm/utils/unittest/googlemock/include/gmock/gmock-matchers.h' l='1368'/>
<use f='llvm/llvm/utils/unittest/googlemock/include/gmock/gmock-matchers.h' l='4030' c='_ZN7testing12MatchesRegexEPKNS_8internal2REE'/>
<use f='llvm/llvm/utils/unittest/googlemock/include/gmock/gmock-matchers.h' l='4035' c='_ZN7testing12MatchesRegexERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE'/>
<use f='llvm/llvm/utils/unittest/googlemock/include/gmock/gmock-matchers.h' l='4041' c='_ZN7testing13ContainsRegexEPKNS_8internal2REE'/>
<use f='llvm/llvm/utils/unittest/googlemock/include/gmock/gmock-matchers.h' l='4046' c='_ZN7testing13ContainsRegexERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE'/>
<size>144</size>
<doc f='llvm/llvm/utils/unittest/googletest/include/gtest/internal/gtest-port.h' l='1161'>// Defines RE.

// A simple C++ wrapper for &lt;regex.h&gt;.  It uses the POSIX Extended
// Regular Expression syntax.</doc>
<fun r='_ZN7testing8internal2REC1ERKS1_'/>
<fun r='_ZN7testing8internal2REC1ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE'/>
<fun r='_ZN7testing8internal2REC1EPKc'/>
<fun r='_ZN7testing8internal2RED1Ev'/>
<fun r='_ZNK7testing8internal2RE7patternEv'/>
<fun r='_ZN7testing8internal2RE9FullMatchERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKS1_'/>
<fun r='_ZN7testing8internal2RE12PartialMatchERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKS1_'/>
<fun r='_ZN7testing8internal2RE9FullMatchEPKcRKS1_'/>
<fun r='_ZN7testing8internal2RE12PartialMatchEPKcRKS1_'/>
<fun r='_ZN7testing8internal2RE4InitEPKc'/>
<mbr r='testing::internal::RE::pattern_' o='0' t='const char *'/>
<mbr r='testing::internal::RE::is_valid_' o='64' t='bool'/>
<mbr r='testing::internal::RE::full_regex_' o='128' t='regex_t'/>
<mbr r='testing::internal::RE::partial_regex_' o='640' t='regex_t'/>
<use f='llvm/clang/unittests/libclang/CrashTests/LibclangCrashTest.cpp' l='21' macro='1' c='_ZN59LibclangParseTest_InstallAbortingLLVMFatalErrorHandler_Test8TestBodyEv'/>
<use f='llvm/clang/unittests/libclang/CrashTests/LibclangCrashTest.cpp' l='34' macro='1' c='_ZN61LibclangParseTest_UninstallAbortingLLVMFatalErrorHandler_Test8TestBodyEv'/>
<size>144</size>
<use f='llvm/lldb/unittests/Utility/ReproducerInstrumentationTest.cpp' l='907' macro='1' c='_ZN45PassiveReplayTest_InstrumentedFooInvalid_Test8TestBodyEv'/>
<use f='llvm/lldb/unittests/Utility/ReproducerInstrumentationTest.cpp' l='1166' macro='1' c='_ZN37RecordReplayTest_InvalidSequence_Test8TestBodyEv'/>
<size>144</size>
<use f='llvm/llvm/unittests/CodeGen/AArch64SelectionDAGTest.cpp' l='648' macro='1' c='_ZN4llvm70AArch64SelectionDAGTest_getTypeConversion_NoScalarizeEVT_nxv1f128_Test8TestBodyEv'/>
<size>144</size>
<use f='llvm/llvm/unittests/Support/ErrorTest.cpp' l='491' macro='1' c='_ZN12_GLOBAL__N_122Error_ExitOnError_Test8TestBodyEv'/>
<use f='llvm/llvm/unittests/Support/ErrorTest.cpp' l='495' macro='1' c='_ZN12_GLOBAL__N_122Error_ExitOnError_Test8TestBodyEv'/>
<size>144</size>
<use f='llvm/llvm/unittests/Transforms/Vectorize/VPlanTest.cpp' l='611' macro='1' c='_ZN4llvm12_GLOBAL__N_122VPRecipeTest_dump_Test8TestBodyEv'/>
<use f='llvm/llvm/unittests/Transforms/Vectorize/VPlanTest.cpp' l='620' macro='1' c='_ZN4llvm12_GLOBAL__N_122VPRecipeTest_dump_Test8TestBodyEv'/>
<use f='llvm/llvm/unittests/Transforms/Vectorize/VPlanTest.cpp' l='629' macro='1' c='_ZN4llvm12_GLOBAL__N_122VPRecipeTest_dump_Test8TestBodyEv'/>
<size>144</size>
<use f='llvm/llvm/utils/unittest/googletest/src/gtest-death-test.cc' l='356' c='_ZN7testing8internal9DeathTest6CreateEPKcPKNS0_2REES3_iPPS1_'/>
<use f='llvm/llvm/utils/unittest/googletest/src/gtest-death-test.cc' l='375' c='_ZN7testing8internal13DeathTestImplC1EPKcPKNS0_2REE'/>
<use f='llvm/llvm/utils/unittest/googletest/src/gtest-death-test.cc' l='391' c='_ZNK7testing8internal13DeathTestImpl5regexEv'/>
<use f='llvm/llvm/utils/unittest/googletest/src/gtest-death-test.cc' l='415'/>
<use f='llvm/llvm/utils/unittest/googletest/src/gtest-death-test.cc' l='789' c='_ZN7testing8internal16ForkingDeathTestC1EPKcPKNS0_2REE'/>
<use f='llvm/llvm/utils/unittest/googletest/src/gtest-death-test.cc' l='803' c='_ZN7testing8internal16ForkingDeathTestC1EPKcPKNS0_2REE'/>
<use f='llvm/llvm/utils/unittest/googletest/src/gtest-death-test.cc' l='826' c='_ZN7testing8internal15NoExecDeathTestC1EPKcPKNS0_2REE'/>
<use f='llvm/llvm/utils/unittest/googletest/src/gtest-death-test.cc' l='881' c='_ZN7testing8internal13ExecDeathTestC1EPKcPKNS0_2REES3_i'/>
<use f='llvm/llvm/utils/unittest/googletest/src/gtest-death-test.cc' l='1171' c='_ZN7testing8internal23DefaultDeathTestFactory6CreateEPKcPKNS0_2REES3_iPPNS0_9DeathTestE'/>
<use f='llvm/llvm/utils/unittest/googletest/src/gtest-port.cc' l='577' c='_ZN7testing8internal2RE9FullMatchEPKcRKS1_'/>
<use f='llvm/llvm/utils/unittest/googletest/src/gtest-port.cc' l='586' c='_ZN7testing8internal2RE12PartialMatchEPKcRKS1_'/>
<size>144</size>
<fun r='_ZN7testing8internal2RED1Ev'/>
<fun r='_ZN7testing8internal2RE9FullMatchEPKcRKS1_'/>
<fun r='_ZN7testing8internal2RE12PartialMatchEPKcRKS1_'/>
<fun r='_ZN7testing8internal2RE4InitEPKc'/>
