<def f='llvm/llvm/utils/unittest/googlemock/include/gmock/gmock-actions.h' l='357' ll='406'/>
<use f='llvm/llvm/utils/unittest/googlemock/include/gmock/gmock-actions.h' l='379' c='_ZN7testing6ActionC1ERKNS_6ActionITL0__EE'/>
<use f='llvm/llvm/utils/unittest/googlemock/include/gmock/gmock-actions.h' l='435' c='_ZNK7testing17PolymorphicActioncvNS_6ActionITL0__EEEv'/>
<use f='llvm/llvm/utils/unittest/googlemock/include/gmock/gmock-actions.h' l='436' c='_ZNK7testing17PolymorphicActioncvNS_6ActionITL0__EEEv'/>
<use f='llvm/llvm/utils/unittest/googlemock/include/gmock/gmock-actions.h' l='466' c='_ZN7testing10MakeActionEPNS_15ActionInterfaceIT_EE'/>
<use f='llvm/llvm/utils/unittest/googlemock/include/gmock/gmock-actions.h' l='467' c='_ZN7testing10MakeActionEPNS_15ActionInterfaceIT_EE'/>
<use f='llvm/llvm/utils/unittest/googlemock/include/gmock/gmock-actions.h' l='492' c='_ZN7testing8internal13ActionAdaptorC1ERKNS_6ActionIT0_EE'/>
<use f='llvm/llvm/utils/unittest/googlemock/include/gmock/gmock-actions.h' l='547' c='_ZNK7testing8internal12ReturnActioncvNS_6ActionITL0__EEEv'/>
<use f='llvm/llvm/utils/unittest/googlemock/include/gmock/gmock-actions.h' l='560' c='_ZNK7testing8internal12ReturnActioncvNS_6ActionITL0__EEEv'/>
<use f='llvm/llvm/utils/unittest/googlemock/include/gmock/gmock-actions.h' l='665' c='_ZNK7testing8internal15ReturnRefActioncvNS_6ActionITL0__EEEv'/>
<use f='llvm/llvm/utils/unittest/googlemock/include/gmock/gmock-actions.h' l='672' c='_ZNK7testing8internal15ReturnRefActioncvNS_6ActionITL0__EEEv'/>
<use f='llvm/llvm/utils/unittest/googlemock/include/gmock/gmock-actions.h' l='713' c='_ZNK7testing8internal21ReturnRefOfCopyActioncvNS_6ActionITL0__EEEv'/>
<use f='llvm/llvm/utils/unittest/googlemock/include/gmock/gmock-actions.h' l='721' c='_ZNK7testing8internal21ReturnRefOfCopyActioncvNS_6ActionITL0__EEEv'/>
<use f='llvm/llvm/utils/unittest/googlemock/include/gmock/gmock-actions.h' l='755' c='_ZNK7testing8internal15DoDefaultActioncvNS_6ActionIT_EEEv'/>
<use f='llvm/llvm/utils/unittest/googlemock/include/gmock/gmock-actions.h' l='755' c='_ZNK7testing8internal15DoDefaultActioncvNS_6ActionIT_EEEv'/>
<use f='llvm/llvm/utils/unittest/googlemock/include/gmock/gmock-actions.h' l='898' c='_ZNK7testing8internal18IgnoreResultActioncvNS_6ActionITL0__EEEv'/>
<use f='llvm/llvm/utils/unittest/googlemock/include/gmock/gmock-actions.h' l='912' c='_ZNK7testing8internal18IgnoreResultActioncvNS_6ActionITL0__EEEv'/>
<use f='llvm/llvm/utils/unittest/googlemock/include/gmock/gmock-actions.h' l='935'/>
<use f='llvm/llvm/utils/unittest/googlemock/include/gmock/gmock-actions.h' l='983' c='_ZNK7testing8internal12DoBothActioncvNS_6ActionITL0__EEEv'/>
<use f='llvm/llvm/utils/unittest/googlemock/include/gmock/gmock-actions.h' l='984' c='_ZNK7testing8internal12DoBothActioncvNS_6ActionITL0__EEEv'/>
<use f='llvm/llvm/utils/unittest/googlemock/include/gmock/gmock-actions.h' l='996' c='_ZN7testing8internal12DoBothAction4ImplC1ERKNS_6ActionINS0_8FunctionITL0__E14MakeResultVoidEEERKNS3_IS5_EE'/>
<use f='llvm/llvm/utils/unittest/googlemock/include/gmock/gmock-actions.h' l='996' c='_ZN7testing8internal12DoBothAction4ImplC1ERKNS_6ActionINS0_8FunctionITL0__E14MakeResultVoidEEERKNS3_IS5_EE'/>
<use f='llvm/llvm/utils/unittest/googlemock/include/gmock/gmock-actions.h' l='1005'/>
<use f='llvm/llvm/utils/unittest/googlemock/include/gmock/gmock-actions.h' l='1006'/>
<use f='llvm/llvm/utils/unittest/googlemock/include/gmock/gmock-actions.h' l='1057' c='_ZN7testing6ActionC1ERKNS_6ActionITL0__EE'/>
<use f='llvm/llvm/utils/unittest/googlemock/include/gmock/gmock-actions.h' l='1057' c='_ZN7testing6ActionC1ERKNS_6ActionITL0__EE'/>
<use f='llvm/llvm/utils/unittest/googlemock/include/gmock/gmock-generated-actions.h' l='468' c='_ZNK7testing8internal14WithArgsActioncvNS_6ActionITL0__EEEv'/>
<use f='llvm/llvm/utils/unittest/googlemock/include/gmock/gmock-generated-actions.h' l='488'/>
<use f='llvm/llvm/utils/unittest/googlemock/include/gmock/gmock-generated-actions.h' l='1277' c='_ZNK7testing20InvokeArgumentActioncvNS_6ActionITL0__EEEv'/>
<use f='llvm/llvm/utils/unittest/googlemock/include/gmock/gmock-generated-actions.h' l='1278' c='_ZNK7testing20InvokeArgumentActioncvNS_6ActionITL0__EEEv'/>
<use f='llvm/llvm/utils/unittest/googlemock/include/gmock/gmock-generated-actions.h' l='1277' c='_ZNK7testing21InvokeArgumentActionPcvNS_6ActionITL0__EEEv'/>
<use f='llvm/llvm/utils/unittest/googlemock/include/gmock/gmock-generated-actions.h' l='1278' c='_ZNK7testing21InvokeArgumentActionPcvNS_6ActionITL0__EEEv'/>
<use f='llvm/llvm/utils/unittest/googlemock/include/gmock/gmock-generated-actions.h' l='1277' c='_ZNK7testing22InvokeArgumentActionP2cvNS_6ActionITL0__EEEv'/>
<use f='llvm/llvm/utils/unittest/googlemock/include/gmock/gmock-generated-actions.h' l='1278' c='_ZNK7testing22InvokeArgumentActionP2cvNS_6ActionITL0__EEEv'/>
<use f='llvm/llvm/utils/unittest/googlemock/include/gmock/gmock-generated-actions.h' l='1277' c='_ZNK7testing22InvokeArgumentActionP3cvNS_6ActionITL0__EEEv'/>
<use f='llvm/llvm/utils/unittest/googlemock/include/gmock/gmock-generated-actions.h' l='1278' c='_ZNK7testing22InvokeArgumentActionP3cvNS_6ActionITL0__EEEv'/>
<use f='llvm/llvm/utils/unittest/googlemock/include/gmock/gmock-generated-actions.h' l='1277' c='_ZNK7testing22InvokeArgumentActionP4cvNS_6ActionITL0__EEEv'/>
<use f='llvm/llvm/utils/unittest/googlemock/include/gmock/gmock-generated-actions.h' l='1278' c='_ZNK7testing22InvokeArgumentActionP4cvNS_6ActionITL0__EEEv'/>
<use f='llvm/llvm/utils/unittest/googlemock/include/gmock/gmock-generated-actions.h' l='1277' c='_ZNK7testing22InvokeArgumentActionP5cvNS_6ActionITL0__EEEv'/>
<use f='llvm/llvm/utils/unittest/googlemock/include/gmock/gmock-generated-actions.h' l='1278' c='_ZNK7testing22InvokeArgumentActionP5cvNS_6ActionITL0__EEEv'/>
<use f='llvm/llvm/utils/unittest/googlemock/include/gmock/gmock-generated-actions.h' l='1277' c='_ZNK7testing22InvokeArgumentActionP6cvNS_6ActionITL0__EEEv'/>
<use f='llvm/llvm/utils/unittest/googlemock/include/gmock/gmock-generated-actions.h' l='1278' c='_ZNK7testing22InvokeArgumentActionP6cvNS_6ActionITL0__EEEv'/>
<use f='llvm/llvm/utils/unittest/googlemock/include/gmock/gmock-generated-actions.h' l='1277' c='_ZNK7testing22InvokeArgumentActionP7cvNS_6ActionITL0__EEEv'/>
<use f='llvm/llvm/utils/unittest/googlemock/include/gmock/gmock-generated-actions.h' l='1278' c='_ZNK7testing22InvokeArgumentActionP7cvNS_6ActionITL0__EEEv'/>
<use f='llvm/llvm/utils/unittest/googlemock/include/gmock/gmock-generated-actions.h' l='1277' c='_ZNK7testing22InvokeArgumentActionP8cvNS_6ActionITL0__EEEv'/>
<use f='llvm/llvm/utils/unittest/googlemock/include/gmock/gmock-generated-actions.h' l='1278' c='_ZNK7testing22InvokeArgumentActionP8cvNS_6ActionITL0__EEEv'/>
<use f='llvm/llvm/utils/unittest/googlemock/include/gmock/gmock-generated-actions.h' l='1277' c='_ZNK7testing22InvokeArgumentActionP9cvNS_6ActionITL0__EEEv'/>
<use f='llvm/llvm/utils/unittest/googlemock/include/gmock/gmock-generated-actions.h' l='1278' c='_ZNK7testing22InvokeArgumentActionP9cvNS_6ActionITL0__EEEv'/>
<use f='llvm/llvm/utils/unittest/googlemock/include/gmock/gmock-generated-actions.h' l='1277' c='_ZNK7testing23InvokeArgumentActionP10cvNS_6ActionITL0__EEEv'/>
<use f='llvm/llvm/utils/unittest/googlemock/include/gmock/gmock-generated-actions.h' l='1278' c='_ZNK7testing23InvokeArgumentActionP10cvNS_6ActionITL0__EEEv'/>
<use f='llvm/llvm/utils/unittest/googlemock/include/gmock/gmock-generated-actions.h' l='1277' c='_ZNK7testing15ReturnNewActioncvNS_6ActionITL0__EEEv'/>
<use f='llvm/llvm/utils/unittest/googlemock/include/gmock/gmock-generated-actions.h' l='1278' c='_ZNK7testing15ReturnNewActioncvNS_6ActionITL0__EEEv'/>
<use f='llvm/llvm/utils/unittest/googlemock/include/gmock/gmock-generated-actions.h' l='1277' c='_ZNK7testing16ReturnNewActionPcvNS_6ActionITL0__EEEv'/>
<use f='llvm/llvm/utils/unittest/googlemock/include/gmock/gmock-generated-actions.h' l='1278' c='_ZNK7testing16ReturnNewActionPcvNS_6ActionITL0__EEEv'/>
<use f='llvm/llvm/utils/unittest/googlemock/include/gmock/gmock-generated-actions.h' l='1277' c='_ZNK7testing17ReturnNewActionP2cvNS_6ActionITL0__EEEv'/>
<use f='llvm/llvm/utils/unittest/googlemock/include/gmock/gmock-generated-actions.h' l='1278' c='_ZNK7testing17ReturnNewActionP2cvNS_6ActionITL0__EEEv'/>
<use f='llvm/llvm/utils/unittest/googlemock/include/gmock/gmock-generated-actions.h' l='1277' c='_ZNK7testing17ReturnNewActionP3cvNS_6ActionITL0__EEEv'/>
<use f='llvm/llvm/utils/unittest/googlemock/include/gmock/gmock-generated-actions.h' l='1278' c='_ZNK7testing17ReturnNewActionP3cvNS_6ActionITL0__EEEv'/>
<use f='llvm/llvm/utils/unittest/googlemock/include/gmock/gmock-generated-actions.h' l='1277' c='_ZNK7testing17ReturnNewActionP4cvNS_6ActionITL0__EEEv'/>
<use f='llvm/llvm/utils/unittest/googlemock/include/gmock/gmock-generated-actions.h' l='1278' c='_ZNK7testing17ReturnNewActionP4cvNS_6ActionITL0__EEEv'/>
<use f='llvm/llvm/utils/unittest/googlemock/include/gmock/gmock-generated-actions.h' l='1277' c='_ZNK7testing17ReturnNewActionP5cvNS_6ActionITL0__EEEv'/>
<use f='llvm/llvm/utils/unittest/googlemock/include/gmock/gmock-generated-actions.h' l='1278' c='_ZNK7testing17ReturnNewActionP5cvNS_6ActionITL0__EEEv'/>
<use f='llvm/llvm/utils/unittest/googlemock/include/gmock/gmock-generated-actions.h' l='1277' c='_ZNK7testing17ReturnNewActionP6cvNS_6ActionITL0__EEEv'/>
<use f='llvm/llvm/utils/unittest/googlemock/include/gmock/gmock-generated-actions.h' l='1278' c='_ZNK7testing17ReturnNewActionP6cvNS_6ActionITL0__EEEv'/>
<use f='llvm/llvm/utils/unittest/googlemock/include/gmock/gmock-generated-actions.h' l='1277' c='_ZNK7testing17ReturnNewActionP7cvNS_6ActionITL0__EEEv'/>
<use f='llvm/llvm/utils/unittest/googlemock/include/gmock/gmock-generated-actions.h' l='1278' c='_ZNK7testing17ReturnNewActionP7cvNS_6ActionITL0__EEEv'/>
<use f='llvm/llvm/utils/unittest/googlemock/include/gmock/gmock-generated-actions.h' l='1277' c='_ZNK7testing17ReturnNewActionP8cvNS_6ActionITL0__EEEv'/>
<use f='llvm/llvm/utils/unittest/googlemock/include/gmock/gmock-generated-actions.h' l='1278' c='_ZNK7testing17ReturnNewActionP8cvNS_6ActionITL0__EEEv'/>
<use f='llvm/llvm/utils/unittest/googlemock/include/gmock/gmock-generated-actions.h' l='1277' c='_ZNK7testing17ReturnNewActionP9cvNS_6ActionITL0__EEEv'/>
<use f='llvm/llvm/utils/unittest/googlemock/include/gmock/gmock-generated-actions.h' l='1278' c='_ZNK7testing17ReturnNewActionP9cvNS_6ActionITL0__EEEv'/>
<use f='llvm/llvm/utils/unittest/googlemock/include/gmock/gmock-generated-actions.h' l='1277' c='_ZNK7testing18ReturnNewActionP10cvNS_6ActionITL0__EEEv'/>
<use f='llvm/llvm/utils/unittest/googlemock/include/gmock/gmock-generated-actions.h' l='1278' c='_ZNK7testing18ReturnNewActionP10cvNS_6ActionITL0__EEEv'/>
<use f='llvm/llvm/utils/unittest/googlemock/include/gmock/gmock-spec-builders.h' l='318' c='_ZN7testing8internal10OnCallSpec13WillByDefaultERKNS_6ActionIT_EE'/>
<use f='llvm/llvm/utils/unittest/googlemock/include/gmock/gmock-spec-builders.h' l='336' c='_ZNK7testing8internal10OnCallSpec9GetActionEv'/>
<use f='llvm/llvm/utils/unittest/googlemock/include/gmock/gmock-spec-builders.h' l='359'/>
<use f='llvm/llvm/utils/unittest/googlemock/include/gmock/gmock-spec-builders.h' l='904' c='_ZN7testing8internal16TypedExpectationD1Ev'/>
<use f='llvm/llvm/utils/unittest/googlemock/include/gmock/gmock-spec-builders.h' l='996' c='_ZN7testing8internal16TypedExpectation8WillOnceERKNS_6ActionIT_EE'/>
<use f='llvm/llvm/utils/unittest/googlemock/include/gmock/gmock-spec-builders.h' l='1002' c='_ZN7testing8internal16TypedExpectation8WillOnceERKNS_6ActionIT_EE'/>
<use f='llvm/llvm/utils/unittest/googlemock/include/gmock/gmock-spec-builders.h' l='1010' c='_ZN7testing8internal16TypedExpectation14WillRepeatedlyERKNS_6ActionIT_EE'/>
<use f='llvm/llvm/utils/unittest/googlemock/include/gmock/gmock-spec-builders.h' l='1060' c='_ZNK7testing8internal16TypedExpectation15repeated_actionEv'/>
<use f='llvm/llvm/utils/unittest/googlemock/include/gmock/gmock-spec-builders.h' l='1153' c='_ZNK7testing8internal16TypedExpectation16GetCurrentActionEPKNS0_18FunctionMockerBaseIT_EERKNS0_8FunctionIS3_E13ArgumentTupleE'/>
<use f='llvm/llvm/utils/unittest/googlemock/include/gmock/gmock-spec-builders.h' l='1179' c='_ZNK7testing8internal16TypedExpectation16GetCurrentActionEPKNS0_18FunctionMockerBaseIT_EERKNS0_8FunctionIS3_E13ArgumentTupleE'/>
<use f='llvm/llvm/utils/unittest/googlemock/include/gmock/gmock-spec-builders.h' l='1190' c='_ZN7testing8internal16TypedExpectation21GetActionForArgumentsEPKNS0_18FunctionMockerBaseIT_EERKNS0_8FunctionIS3_E13ArgumentTupleEPSoSC_'/>
<use f='llvm/llvm/utils/unittest/googlemock/include/gmock/gmock-spec-builders.h' l='1227'/>
<use f='llvm/llvm/utils/unittest/googlemock/include/gmock/gmock-spec-builders.h' l='1403' c='_ZN7testing8internal18ActionResultHolder13PerformActionERKNS_6ActionITL0__EERKNS0_8FunctionIS3_E13ArgumentTupleE'/>
<use f='llvm/llvm/utils/unittest/googlemock/include/gmock/gmock-spec-builders.h' l='1443' c='_ZN7testing8internal18ActionResultHolderIvE13PerformActionERKNS_6ActionIT_EERKNS0_8FunctionIS4_E13ArgumentTupleE'/>
<use f='llvm/llvm/utils/unittest/googlemock/include/gmock/gmock-spec-builders.h' l='1541' c='_ZNK7testing8internal18FunctionMockerBase20UntypedPerformActionEPKvS3_'/>
<use f='llvm/llvm/utils/unittest/googlemock/include/gmock/gmock-spec-builders.h' l='1541' c='_ZNK7testing8internal18FunctionMockerBase20UntypedPerformActionEPKvS3_'/>
<use f='llvm/llvm/utils/unittest/googlemock/include/gmock/gmock-spec-builders.h' l='1699' c='_ZN7testing8internal18FunctionMockerBase30UntypedFindMatchingExpectationEPKvPS3_PbPSoS6_'/>
<use f='llvm/llvm/utils/unittest/googlemock/include/gmock/gmock-more-actions.h' l='163' macro='1' c='_ZNK7testing15ReturnArgActioncvNS_6ActionITL0__EEEv'/>
<use f='llvm/llvm/utils/unittest/googlemock/include/gmock/gmock-more-actions.h' l='163' macro='1' c='_ZNK7testing15ReturnArgActioncvNS_6ActionITL0__EEEv'/>
<use f='llvm/llvm/utils/unittest/googlemock/include/gmock/gmock-more-actions.h' l='171' macro='1' c='_ZNK7testing14SaveArgActionPcvNS_6ActionITL0__EEEv'/>
<use f='llvm/llvm/utils/unittest/googlemock/include/gmock/gmock-more-actions.h' l='171' macro='1' c='_ZNK7testing14SaveArgActionPcvNS_6ActionITL0__EEEv'/>
<use f='llvm/llvm/utils/unittest/googlemock/include/gmock/gmock-more-actions.h' l='179' macro='1' c='_ZNK7testing21SaveArgPointeeActionPcvNS_6ActionITL0__EEEv'/>
<use f='llvm/llvm/utils/unittest/googlemock/include/gmock/gmock-more-actions.h' l='179' macro='1' c='_ZNK7testing21SaveArgPointeeActionPcvNS_6ActionITL0__EEEv'/>
<use f='llvm/llvm/utils/unittest/googlemock/include/gmock/gmock-more-actions.h' l='187' macro='1' c='_ZNK7testing20SetArgRefereeActionPcvNS_6ActionITL0__EEEv'/>
<use f='llvm/llvm/utils/unittest/googlemock/include/gmock/gmock-more-actions.h' l='187' macro='1' c='_ZNK7testing20SetArgRefereeActionPcvNS_6ActionITL0__EEEv'/>
<use f='llvm/llvm/utils/unittest/googlemock/include/gmock/gmock-more-actions.h' l='204' macro='1' c='_ZNK7testing24SetArrayArgumentActionP2cvNS_6ActionITL0__EEEv'/>
<use f='llvm/llvm/utils/unittest/googlemock/include/gmock/gmock-more-actions.h' l='204' macro='1' c='_ZNK7testing24SetArrayArgumentActionP2cvNS_6ActionITL0__EEEv'/>
<use f='llvm/llvm/utils/unittest/googlemock/include/gmock/gmock-more-actions.h' l='217' macro='1' c='_ZNK7testing15DeleteArgActioncvNS_6ActionITL0__EEEv'/>
<use f='llvm/llvm/utils/unittest/googlemock/include/gmock/gmock-more-actions.h' l='217' macro='1' c='_ZNK7testing15DeleteArgActioncvNS_6ActionITL0__EEEv'/>
<use f='llvm/llvm/utils/unittest/googlemock/include/gmock/gmock-more-actions.h' l='224' macro='1' c='_ZNK7testing20ReturnPointeeActionPcvNS_6ActionITL0__EEEv'/>
<use f='llvm/llvm/utils/unittest/googlemock/include/gmock/gmock-more-actions.h' l='224' macro='1' c='_ZNK7testing20ReturnPointeeActionPcvNS_6ActionITL0__EEEv'/>
<fun r='_ZN7testing6ActionC1Ev'/>
<fun r='_ZN7testing6ActionC1EPNS_15ActionInterfaceIT_EE'/>
<fun r='_ZN7testing6ActionC1ERKNS_6ActionIT_EE'/>
<fun r='_ZN7testing6ActionaSERKNS_6ActionIT_EE'/>
<fun r='_ZN7testing6ActionC1ERKNS_6ActionITL0__EE'/>
<fun r='_ZNK7testing6Action11IsDoDefaultEv'/>
<fun r='_ZNK7testing6Action7PerformERKNS_8internal8FunctionIT_E13ArgumentTupleE'/>
<mbr r='testing::Action::impl_' t='internal::linked_ptr&lt;ActionInterface&lt;F&gt; &gt;'/>
<fun r='_ZN7testing6ActionC1ERKNS_6ActionITL0__EE'/>
