<def f='x265/source/common/primitives.h' l='273' ll='313'/>
<use f='x265/source/common/primitives.h' l='273'/>
<size>584</size>
<mbr r='x265::EncoderPrimitives::CU::dct' o='0' t='x265::dct_t'/>
<mbr r='x265::EncoderPrimitives::CU::idct' o='64' t='x265::idct_t'/>
<mbr r='x265::EncoderPrimitives::CU::standard_dct' o='128' t='x265::dct_t'/>
<mbr r='x265::EncoderPrimitives::CU::lowpass_dct' o='192' t='x265::dct_t'/>
<mbr r='x265::EncoderPrimitives::CU::calcresidual' o='256' t='x265::calcresidual_t [2]'/>
<mbr r='x265::EncoderPrimitives::CU::sub_ps' o='384' t='x265::pixel_sub_ps_t'/>
<mbr r='x265::EncoderPrimitives::CU::add_ps' o='448' t='x265::pixel_add_ps_t [2]'/>
<mbr r='x265::EncoderPrimitives::CU::blockfill_s' o='576' t='x265::blockfill_s_t [2]'/>
<mbr r='x265::EncoderPrimitives::CU::copy_cnt' o='704' t='x265::copy_cnt_t'/>
<mbr r='x265::EncoderPrimitives::CU::count_nonzero' o='768' t='x265::count_nonzero_t'/>
<mbr r='x265::EncoderPrimitives::CU::cpy2Dto1D_shl' o='832' t='x265::cpy2Dto1D_shl_t'/>
<mbr r='x265::EncoderPrimitives::CU::cpy2Dto1D_shr' o='896' t='x265::cpy2Dto1D_shr_t'/>
<mbr r='x265::EncoderPrimitives::CU::cpy1Dto2D_shl' o='960' t='x265::cpy1Dto2D_shl_t [2]'/>
<mbr r='x265::EncoderPrimitives::CU::cpy1Dto2D_shr' o='1088' t='x265::cpy1Dto2D_shr_t'/>
<mbr r='x265::EncoderPrimitives::CU::copy_sp' o='1152' t='x265::copy_sp_t'/>
<mbr r='x265::EncoderPrimitives::CU::copy_ps' o='1216' t='x265::copy_ps_t'/>
<mbr r='x265::EncoderPrimitives::CU::copy_ss' o='1280' t='x265::copy_ss_t'/>
<mbr r='x265::EncoderPrimitives::CU::copy_pp' o='1344' t='x265::copy_pp_t'/>
<mbr r='x265::EncoderPrimitives::CU::var' o='1408' t='x265::var_t'/>
<mbr r='x265::EncoderPrimitives::CU::sse_pp' o='1472' t='x265::pixel_sse_t'/>
<mbr r='x265::EncoderPrimitives::CU::sse_ss' o='1536' t='x265::pixel_sse_ss_t'/>
<mbr r='x265::EncoderPrimitives::CU::psy_cost_pp' o='1600' t='x265::pixelcmp_t'/>
<mbr r='x265::EncoderPrimitives::CU::ssd_s' o='1664' t='x265::pixel_ssd_s_t [2]'/>
<mbr r='x265::EncoderPrimitives::CU::sa8d' o='1792' t='x265::pixelcmp_t'/>
<mbr r='x265::EncoderPrimitives::CU::transpose' o='1856' t='x265::transpose_t'/>
<mbr r='x265::EncoderPrimitives::CU::intra_pred_allangs' o='1920' t='x265::intra_allangs_t'/>
<mbr r='x265::EncoderPrimitives::CU::intra_filter' o='1984' t='x265::intra_filter_t'/>
<mbr r='x265::EncoderPrimitives::CU::intra_pred' o='2048' t='x265::intra_pred_t [35]'/>
<mbr r='x265::EncoderPrimitives::CU::nonPsyRdoQuant' o='4288' t='x265::nonPsyRdoQuant_t'/>
<mbr r='x265::EncoderPrimitives::CU::psyRdoQuant' o='4352' t='x265::psyRdoQuant_t'/>
<mbr r='x265::EncoderPrimitives::CU::psyRdoQuant_1p' o='4416' t='x265::psyRdoQuant_t1'/>
<mbr r='x265::EncoderPrimitives::CU::psyRdoQuant_2p' o='4480' t='x265::psyRdoQuant_t2'/>
<mbr r='x265::EncoderPrimitives::CU::ssimDist' o='4544' t='x265::ssimDistortion_t'/>
<mbr r='x265::EncoderPrimitives::CU::normFact' o='4608' t='x265::normFactor_t'/>
