<dec f='ffmpeg/libavcodec/aacenc.h' l='381' type='PutBitContext'/>
<use f='ffmpeg/libavcodec/aaccoder_trellis.h' l='175' u='a' c='codebook_trellis_rate'/>
<use f='ffmpeg/libavcodec/aaccoder_trellis.h' l='184' u='a' c='codebook_trellis_rate'/>
<use f='ffmpeg/libavcodec/aaccoder_trellis.h' l='187' u='a' c='codebook_trellis_rate'/>
<use f='ffmpeg/libavcodec/aaccoder.c' l='171' u='a' c='encode_window_bands_info'/>
<use f='ffmpeg/libavcodec/aaccoder.c' l='180' u='a' c='encode_window_bands_info'/>
<use f='ffmpeg/libavcodec/aaccoder.c' l='183' u='a' c='encode_window_bands_info'/>
<offset>320</offset>
<use f='ffmpeg/libavcodec/aacenc.c' l='222' u='a' c='put_ics_info'/>
<use f='ffmpeg/libavcodec/aacenc.c' l='223' u='a' c='put_ics_info'/>
<use f='ffmpeg/libavcodec/aacenc.c' l='224' u='a' c='put_ics_info'/>
<use f='ffmpeg/libavcodec/aacenc.c' l='226' u='a' c='put_ics_info'/>
<use f='ffmpeg/libavcodec/aacenc.c' l='227' u='a' c='put_ics_info'/>
<use f='ffmpeg/libavcodec/aacenc.c' l='229' u='a' c='put_ics_info'/>
<use f='ffmpeg/libavcodec/aacenc.c' l='231' u='a' c='put_ics_info'/>
<use f='ffmpeg/libavcodec/aacenc.c' l='395' u='a' c='encode_scale_factors'/>
<use f='ffmpeg/libavcodec/aacenc.c' l='408' u='a' c='encode_scale_factors'/>
<use f='ffmpeg/libavcodec/aacenc.c' l='421' u='a' c='encode_pulses'/>
<use f='ffmpeg/libavcodec/aacenc.c' l='425' u='a' c='encode_pulses'/>
<use f='ffmpeg/libavcodec/aacenc.c' l='426' u='a' c='encode_pulses'/>
<use f='ffmpeg/libavcodec/aacenc.c' l='428' u='a' c='encode_pulses'/>
<use f='ffmpeg/libavcodec/aacenc.c' l='429' u='a' c='encode_pulses'/>
<use f='ffmpeg/libavcodec/aacenc.c' l='448' u='a' c='encode_spectral_coeffs'/>
<use f='ffmpeg/libavcodec/aacenc.c' l='488' u='a' c='encode_individual_channel'/>
<use f='ffmpeg/libavcodec/aacenc.c' l='499' u='a' c='encode_individual_channel'/>
<use f='ffmpeg/libavcodec/aacenc.c' l='502' u='a' c='encode_individual_channel'/>
<use f='ffmpeg/libavcodec/aacenc.c' l='515' u='a' c='put_bitstream_info'/>
<use f='ffmpeg/libavcodec/aacenc.c' l='516' u='a' c='put_bitstream_info'/>
<use f='ffmpeg/libavcodec/aacenc.c' l='518' u='a' c='put_bitstream_info'/>
<use f='ffmpeg/libavcodec/aacenc.c' l='519' u='a' c='put_bitstream_info'/>
<use f='ffmpeg/libavcodec/aacenc.c' l='520' u='a' c='put_bitstream_info'/>
<use f='ffmpeg/libavcodec/aacenc.c' l='521' u='a' c='put_bitstream_info'/>
<use f='ffmpeg/libavcodec/aacenc.c' l='523' u='a' c='put_bitstream_info'/>
<use f='ffmpeg/libavcodec/aacenc.c' l='524' u='a' c='put_bitstream_info'/>
<use f='ffmpeg/libavcodec/aacenc.c' l='682' u='a' c='aac_encode_frame'/>
<use f='ffmpeg/libavcodec/aacenc.c' l='698' u='a' c='aac_encode_frame'/>
<use f='ffmpeg/libavcodec/aacenc.c' l='699' u='a' c='aac_encode_frame'/>
<use f='ffmpeg/libavcodec/aacenc.c' l='798' u='a' c='aac_encode_frame'/>
<use f='ffmpeg/libavcodec/aacenc.c' l='805' u='a' c='aac_encode_frame'/>
<use f='ffmpeg/libavcodec/aacenc.c' l='825' u='a' c='aac_encode_frame'/>
<use f='ffmpeg/libavcodec/aacenc.c' l='880' u='a' c='aac_encode_frame'/>
<use f='ffmpeg/libavcodec/aacenc.c' l='881' u='a' c='aac_encode_frame'/>
<use f='ffmpeg/libavcodec/aacenc.c' l='883' u='a' c='aac_encode_frame'/>
<use f='ffmpeg/libavcodec/aacenc.c' l='891' u='a' c='aac_encode_frame'/>
<use f='ffmpeg/libavcodec/aacenc_ltp.c' l='43' u='a' c='ff_aac_encode_ltp_info'/>
<use f='ffmpeg/libavcodec/aacenc_ltp.c' l='44' u='a' c='ff_aac_encode_ltp_info'/>
<use f='ffmpeg/libavcodec/aacenc_ltp.c' l='47' u='a' c='ff_aac_encode_ltp_info'/>
<use f='ffmpeg/libavcodec/aacenc_ltp.c' l='48' u='a' c='ff_aac_encode_ltp_info'/>
<use f='ffmpeg/libavcodec/aacenc_ltp.c' l='50' u='a' c='ff_aac_encode_ltp_info'/>
<use f='ffmpeg/libavcodec/aacenc_pred.c' l='342' u='a' c='ff_aac_encode_main_pred'/>
<use f='ffmpeg/libavcodec/aacenc_pred.c' l='344' u='a' c='ff_aac_encode_main_pred'/>
<use f='ffmpeg/libavcodec/aacenc_pred.c' l='346' u='a' c='ff_aac_encode_main_pred'/>
<use f='ffmpeg/libavcodec/aacenc_tns.c' l='81' u='a' c='ff_aac_encode_tns_info'/>
<use f='ffmpeg/libavcodec/aacenc_tns.c' l='84' u='a' c='ff_aac_encode_tns_info'/>
<use f='ffmpeg/libavcodec/aacenc_tns.c' l='86' u='a' c='ff_aac_encode_tns_info'/>
<use f='ffmpeg/libavcodec/aacenc_tns.c' l='87' u='a' c='ff_aac_encode_tns_info'/>
<use f='ffmpeg/libavcodec/aacenc_tns.c' l='90' u='a' c='ff_aac_encode_tns_info'/>
<use f='ffmpeg/libavcodec/aacenc_tns.c' l='93' u='a' c='ff_aac_encode_tns_info'/>
<use f='ffmpeg/libavcodec/aacenc_tns.c' l='96' u='a' c='ff_aac_encode_tns_info'/>
