<dec f='ffmpeg/libavcodec/ac3enc.h' l='158' type='PutBitContext'/>
<use f='ffmpeg/libavcodec/ac3enc.c' l='1400' u='a' c='ac3_output_frame_header'/>
<use f='ffmpeg/libavcodec/ac3enc.c' l='1401' u='a' c='ac3_output_frame_header'/>
<use f='ffmpeg/libavcodec/ac3enc.c' l='1402' u='a' c='ac3_output_frame_header'/>
<use f='ffmpeg/libavcodec/ac3enc.c' l='1403' u='a' c='ac3_output_frame_header'/>
<use f='ffmpeg/libavcodec/ac3enc.c' l='1404' u='a' c='ac3_output_frame_header'/>
<use f='ffmpeg/libavcodec/ac3enc.c' l='1405' u='a' c='ac3_output_frame_header'/>
<use f='ffmpeg/libavcodec/ac3enc.c' l='1406' u='a' c='ac3_output_frame_header'/>
<use f='ffmpeg/libavcodec/ac3enc.c' l='1408' u='a' c='ac3_output_frame_header'/>
<use f='ffmpeg/libavcodec/ac3enc.c' l='1410' u='a' c='ac3_output_frame_header'/>
<use f='ffmpeg/libavcodec/ac3enc.c' l='1412' u='a' c='ac3_output_frame_header'/>
<use f='ffmpeg/libavcodec/ac3enc.c' l='1413' u='a' c='ac3_output_frame_header'/>
<use f='ffmpeg/libavcodec/ac3enc.c' l='1414' u='a' c='ac3_output_frame_header'/>
<use f='ffmpeg/libavcodec/ac3enc.c' l='1415' u='a' c='ac3_output_frame_header'/>
<use f='ffmpeg/libavcodec/ac3enc.c' l='1416' u='a' c='ac3_output_frame_header'/>
<use f='ffmpeg/libavcodec/ac3enc.c' l='1417' u='a' c='ac3_output_frame_header'/>
<use f='ffmpeg/libavcodec/ac3enc.c' l='1419' u='a' c='ac3_output_frame_header'/>
<use f='ffmpeg/libavcodec/ac3enc.c' l='1420' u='a' c='ac3_output_frame_header'/>
<use f='ffmpeg/libavcodec/ac3enc.c' l='1422' u='a' c='ac3_output_frame_header'/>
<use f='ffmpeg/libavcodec/ac3enc.c' l='1423' u='a' c='ac3_output_frame_header'/>
<use f='ffmpeg/libavcodec/ac3enc.c' l='1426' u='a' c='ac3_output_frame_header'/>
<use f='ffmpeg/libavcodec/ac3enc.c' l='1428' u='a' c='ac3_output_frame_header'/>
<use f='ffmpeg/libavcodec/ac3enc.c' l='1429' u='a' c='ac3_output_frame_header'/>
<use f='ffmpeg/libavcodec/ac3enc.c' l='1430' u='a' c='ac3_output_frame_header'/>
<use f='ffmpeg/libavcodec/ac3enc.c' l='1431' u='a' c='ac3_output_frame_header'/>
<use f='ffmpeg/libavcodec/ac3enc.c' l='1432' u='a' c='ac3_output_frame_header'/>
<use f='ffmpeg/libavcodec/ac3enc.c' l='1434' u='a' c='ac3_output_frame_header'/>
<use f='ffmpeg/libavcodec/ac3enc.c' l='1436' u='a' c='ac3_output_frame_header'/>
<use f='ffmpeg/libavcodec/ac3enc.c' l='1437' u='a' c='ac3_output_frame_header'/>
<use f='ffmpeg/libavcodec/ac3enc.c' l='1438' u='a' c='ac3_output_frame_header'/>
<use f='ffmpeg/libavcodec/ac3enc.c' l='1439' u='a' c='ac3_output_frame_header'/>
<use f='ffmpeg/libavcodec/ac3enc.c' l='1442' u='a' c='ac3_output_frame_header'/>
<use f='ffmpeg/libavcodec/ac3enc.c' l='1443' u='a' c='ac3_output_frame_header'/>
<use f='ffmpeg/libavcodec/ac3enc.c' l='1445' u='a' c='ac3_output_frame_header'/>
<use f='ffmpeg/libavcodec/ac3enc.c' l='1460' u='a' c='output_audio_block'/>
<use f='ffmpeg/libavcodec/ac3enc.c' l='1466' u='a' c='output_audio_block'/>
<use f='ffmpeg/libavcodec/ac3enc.c' l='1470' u='a' c='output_audio_block'/>
<use f='ffmpeg/libavcodec/ac3enc.c' l='1474' u='a' c='output_audio_block'/>
<use f='ffmpeg/libavcodec/ac3enc.c' l='1478' u='a' c='output_audio_block'/>
<use f='ffmpeg/libavcodec/ac3enc.c' l='1481' u='a' c='output_audio_block'/>
<use f='ffmpeg/libavcodec/ac3enc.c' l='1485' u='a' c='output_audio_block'/>
<use f='ffmpeg/libavcodec/ac3enc.c' l='1488' u='a' c='output_audio_block'/>
<use f='ffmpeg/libavcodec/ac3enc.c' l='1491' u='a' c='output_audio_block'/>
<use f='ffmpeg/libavcodec/ac3enc.c' l='1494' u='a' c='output_audio_block'/>
<use f='ffmpeg/libavcodec/ac3enc.c' l='1495' u='a' c='output_audio_block'/>
<use f='ffmpeg/libavcodec/ac3enc.c' l='1498' u='a' c='output_audio_block'/>
<use f='ffmpeg/libavcodec/ac3enc.c' l='1501' u='a' c='output_audio_block'/>
<use f='ffmpeg/libavcodec/ac3enc.c' l='1511' u='a' c='output_audio_block'/>
<use f='ffmpeg/libavcodec/ac3enc.c' l='1513' u='a' c='output_audio_block'/>
<use f='ffmpeg/libavcodec/ac3enc.c' l='1515' u='a' c='output_audio_block'/>
<use f='ffmpeg/libavcodec/ac3enc.c' l='1516' u='a' c='output_audio_block'/>
<use f='ffmpeg/libavcodec/ac3enc.c' l='1526' u='a' c='output_audio_block'/>
<use f='ffmpeg/libavcodec/ac3enc.c' l='1530' u='a' c='output_audio_block'/>
<use f='ffmpeg/libavcodec/ac3enc.c' l='1537' u='a' c='output_audio_block'/>
<use f='ffmpeg/libavcodec/ac3enc.c' l='1539' u='a' c='output_audio_block'/>
<use f='ffmpeg/libavcodec/ac3enc.c' l='1545' u='a' c='output_audio_block'/>
<use f='ffmpeg/libavcodec/ac3enc.c' l='1557' u='a' c='output_audio_block'/>
<use f='ffmpeg/libavcodec/ac3enc.c' l='1562' u='a' c='output_audio_block'/>
<use f='ffmpeg/libavcodec/ac3enc.c' l='1566' u='a' c='output_audio_block'/>
<use f='ffmpeg/libavcodec/ac3enc.c' l='1572' u='a' c='output_audio_block'/>
<use f='ffmpeg/libavcodec/ac3enc.c' l='1574' u='a' c='output_audio_block'/>
<use f='ffmpeg/libavcodec/ac3enc.c' l='1575' u='a' c='output_audio_block'/>
<use f='ffmpeg/libavcodec/ac3enc.c' l='1576' u='a' c='output_audio_block'/>
<use f='ffmpeg/libavcodec/ac3enc.c' l='1577' u='a' c='output_audio_block'/>
<use f='ffmpeg/libavcodec/ac3enc.c' l='1578' u='a' c='output_audio_block'/>
<use f='ffmpeg/libavcodec/ac3enc.c' l='1584' u='a' c='output_audio_block'/>
<use f='ffmpeg/libavcodec/ac3enc.c' l='1586' u='a' c='output_audio_block'/>
<use f='ffmpeg/libavcodec/ac3enc.c' l='1588' u='a' c='output_audio_block'/>
<use f='ffmpeg/libavcodec/ac3enc.c' l='1589' u='a' c='output_audio_block'/>
<use f='ffmpeg/libavcodec/ac3enc.c' l='1593' u='a' c='output_audio_block'/>
<use f='ffmpeg/libavcodec/ac3enc.c' l='1599' u='a' c='output_audio_block'/>
<use f='ffmpeg/libavcodec/ac3enc.c' l='1601' u='a' c='output_audio_block'/>
<use f='ffmpeg/libavcodec/ac3enc.c' l='1602' u='a' c='output_audio_block'/>
<use f='ffmpeg/libavcodec/ac3enc.c' l='1607' u='a' c='output_audio_block'/>
<use f='ffmpeg/libavcodec/ac3enc.c' l='1608' u='a' c='output_audio_block'/>
<use f='ffmpeg/libavcodec/ac3enc.c' l='1626' u='a' c='output_audio_block'/>
<use f='ffmpeg/libavcodec/ac3enc.c' l='1627' u='a' c='output_audio_block'/>
<use f='ffmpeg/libavcodec/ac3enc.c' l='1628' u='a' c='output_audio_block'/>
<use f='ffmpeg/libavcodec/ac3enc.c' l='1629' u='a' c='output_audio_block'/>
<use f='ffmpeg/libavcodec/ac3enc.c' l='1630' u='a' c='output_audio_block'/>
<use f='ffmpeg/libavcodec/ac3enc.c' l='1631' u='a' c='output_audio_block'/>
<use f='ffmpeg/libavcodec/ac3enc.c' l='1632' u='a' c='output_audio_block'/>
<use f='ffmpeg/libavcodec/ac3enc.c' l='1689' u='a' c='output_frame_end'/>
<use f='ffmpeg/libavcodec/ac3enc.c' l='1690' u='m' c='output_frame_end'/>
<use f='ffmpeg/libavcodec/ac3enc.c' l='1691' u='a' c='output_frame_end'/>
<use f='ffmpeg/libavcodec/ac3enc.c' l='1694' u='a' c='output_frame_end'/>
<use f='ffmpeg/libavcodec/ac3enc.c' l='1732' u='a' c='ac3_output_frame'/>
<offset>960</offset>
<doc f='ffmpeg/libavcodec/ac3enc.h' l='158'>///&lt; bitstream writer context</doc>
<use f='ffmpeg/libavcodec/eac3enc.c' l='130' u='a' c='ff_eac3_output_frame_header'/>
<use f='ffmpeg/libavcodec/eac3enc.c' l='133' u='a' c='ff_eac3_output_frame_header'/>
<use f='ffmpeg/libavcodec/eac3enc.c' l='134' u='a' c='ff_eac3_output_frame_header'/>
<use f='ffmpeg/libavcodec/eac3enc.c' l='135' u='a' c='ff_eac3_output_frame_header'/>
<use f='ffmpeg/libavcodec/eac3enc.c' l='137' u='a' c='ff_eac3_output_frame_header'/>
<use f='ffmpeg/libavcodec/eac3enc.c' l='138' u='a' c='ff_eac3_output_frame_header'/>
<use f='ffmpeg/libavcodec/eac3enc.c' l='140' u='a' c='ff_eac3_output_frame_header'/>
<use f='ffmpeg/libavcodec/eac3enc.c' l='141' u='a' c='ff_eac3_output_frame_header'/>
<use f='ffmpeg/libavcodec/eac3enc.c' l='143' u='a' c='ff_eac3_output_frame_header'/>
<use f='ffmpeg/libavcodec/eac3enc.c' l='144' u='a' c='ff_eac3_output_frame_header'/>
<use f='ffmpeg/libavcodec/eac3enc.c' l='145' u='a' c='ff_eac3_output_frame_header'/>
<use f='ffmpeg/libavcodec/eac3enc.c' l='146' u='a' c='ff_eac3_output_frame_header'/>
<use f='ffmpeg/libavcodec/eac3enc.c' l='147' u='a' c='ff_eac3_output_frame_header'/>
<use f='ffmpeg/libavcodec/eac3enc.c' l='149' u='a' c='ff_eac3_output_frame_header'/>
<use f='ffmpeg/libavcodec/eac3enc.c' l='152' u='a' c='ff_eac3_output_frame_header'/>
<use f='ffmpeg/libavcodec/eac3enc.c' l='154' u='a' c='ff_eac3_output_frame_header'/>
<use f='ffmpeg/libavcodec/eac3enc.c' l='155' u='a' c='ff_eac3_output_frame_header'/>
<use f='ffmpeg/libavcodec/eac3enc.c' l='158' u='a' c='ff_eac3_output_frame_header'/>
<use f='ffmpeg/libavcodec/eac3enc.c' l='159' u='a' c='ff_eac3_output_frame_header'/>
<use f='ffmpeg/libavcodec/eac3enc.c' l='162' u='a' c='ff_eac3_output_frame_header'/>
<use f='ffmpeg/libavcodec/eac3enc.c' l='163' u='a' c='ff_eac3_output_frame_header'/>
<use f='ffmpeg/libavcodec/eac3enc.c' l='164' u='a' c='ff_eac3_output_frame_header'/>
<use f='ffmpeg/libavcodec/eac3enc.c' l='165' u='a' c='ff_eac3_output_frame_header'/>
<use f='ffmpeg/libavcodec/eac3enc.c' l='167' u='a' c='ff_eac3_output_frame_header'/>
<use f='ffmpeg/libavcodec/eac3enc.c' l='168' u='a' c='ff_eac3_output_frame_header'/>
<use f='ffmpeg/libavcodec/eac3enc.c' l='171' u='a' c='ff_eac3_output_frame_header'/>
<use f='ffmpeg/libavcodec/eac3enc.c' l='173' u='a' c='ff_eac3_output_frame_header'/>
<use f='ffmpeg/libavcodec/eac3enc.c' l='174' u='a' c='ff_eac3_output_frame_header'/>
<use f='ffmpeg/libavcodec/eac3enc.c' l='175' u='a' c='ff_eac3_output_frame_header'/>
<use f='ffmpeg/libavcodec/eac3enc.c' l='177' u='a' c='ff_eac3_output_frame_header'/>
<use f='ffmpeg/libavcodec/eac3enc.c' l='178' u='a' c='ff_eac3_output_frame_header'/>
<use f='ffmpeg/libavcodec/eac3enc.c' l='181' u='a' c='ff_eac3_output_frame_header'/>
<use f='ffmpeg/libavcodec/eac3enc.c' l='182' u='a' c='ff_eac3_output_frame_header'/>
<use f='ffmpeg/libavcodec/eac3enc.c' l='184' u='a' c='ff_eac3_output_frame_header'/>
<use f='ffmpeg/libavcodec/eac3enc.c' l='185' u='a' c='ff_eac3_output_frame_header'/>
<use f='ffmpeg/libavcodec/eac3enc.c' l='186' u='a' c='ff_eac3_output_frame_header'/>
<use f='ffmpeg/libavcodec/eac3enc.c' l='188' u='a' c='ff_eac3_output_frame_header'/>
<use f='ffmpeg/libavcodec/eac3enc.c' l='191' u='a' c='ff_eac3_output_frame_header'/>
<use f='ffmpeg/libavcodec/eac3enc.c' l='192' u='a' c='ff_eac3_output_frame_header'/>
<use f='ffmpeg/libavcodec/eac3enc.c' l='196' u='a' c='ff_eac3_output_frame_header'/>
<use f='ffmpeg/libavcodec/eac3enc.c' l='197' u='a' c='ff_eac3_output_frame_header'/>
<use f='ffmpeg/libavcodec/eac3enc.c' l='199' u='a' c='ff_eac3_output_frame_header'/>
<use f='ffmpeg/libavcodec/eac3enc.c' l='200' u='a' c='ff_eac3_output_frame_header'/>
<use f='ffmpeg/libavcodec/eac3enc.c' l='201' u='a' c='ff_eac3_output_frame_header'/>
<use f='ffmpeg/libavcodec/eac3enc.c' l='202' u='a' c='ff_eac3_output_frame_header'/>
<use f='ffmpeg/libavcodec/eac3enc.c' l='203' u='a' c='ff_eac3_output_frame_header'/>
<use f='ffmpeg/libavcodec/eac3enc.c' l='204' u='a' c='ff_eac3_output_frame_header'/>
<use f='ffmpeg/libavcodec/eac3enc.c' l='205' u='a' c='ff_eac3_output_frame_header'/>
<use f='ffmpeg/libavcodec/eac3enc.c' l='206' u='a' c='ff_eac3_output_frame_header'/>
<use f='ffmpeg/libavcodec/eac3enc.c' l='207' u='a' c='ff_eac3_output_frame_header'/>
<use f='ffmpeg/libavcodec/eac3enc.c' l='210' u='a' c='ff_eac3_output_frame_header'/>
<use f='ffmpeg/libavcodec/eac3enc.c' l='213' u='a' c='ff_eac3_output_frame_header'/>
<use f='ffmpeg/libavcodec/eac3enc.c' l='215' u='a' c='ff_eac3_output_frame_header'/>
<use f='ffmpeg/libavcodec/eac3enc.c' l='221' u='a' c='ff_eac3_output_frame_header'/>
<use f='ffmpeg/libavcodec/eac3enc.c' l='225' u='a' c='ff_eac3_output_frame_header'/>
<use f='ffmpeg/libavcodec/eac3enc.c' l='229' u='a' c='ff_eac3_output_frame_header'/>
<use f='ffmpeg/libavcodec/eac3enc.c' l='233' u='a' c='ff_eac3_output_frame_header'/>
<use f='ffmpeg/libavcodec/eac3enc.c' l='237' u='a' c='ff_eac3_output_frame_header'/>
<use f='ffmpeg/libavcodec/eac3enc.c' l='239' u='a' c='ff_eac3_output_frame_header'/>
<use f='ffmpeg/libavcodec/eac3enc.c' l='243' u='a' c='ff_eac3_output_frame_header'/>
<use f='ffmpeg/libavcodec/eac3enc.c' l='244' u='a' c='ff_eac3_output_frame_header'/>
<use f='ffmpeg/libavcodec/eac3enc.c' l='247' u='a' c='ff_eac3_output_frame_header'/>
