<dec f='ffmpeg/libavcodec/bsf.h' l='128' type='int (*)(AVBSFContext *)'/>
<offset>256</offset>
<use f='ffmpeg/libavcodec/aac_adtstoasc_bsf.c' l='155' u='w'/>
<use f='ffmpeg/libavcodec/av1_frame_merge_bsf.c' l='157' u='w'/>
<use f='ffmpeg/libavcodec/av1_frame_split_bsf.c' l='256' u='w'/>
<use f='ffmpeg/libavcodec/av1_metadata_bsf.c' l='224' u='w'/>
<use f='ffmpeg/libavcodec/bsf.c' l='180' u='r' c='av_bsf_init'/>
<use f='ffmpeg/libavcodec/bsf.c' l='181' u='r' c='av_bsf_init'/>
<use f='ffmpeg/libavcodec/bsf.c' l='406' u='w'/>
<use f='ffmpeg/libavcodec/extract_extradata_bsf.c' l='429' u='w'/>
<use f='ffmpeg/libavcodec/filter_units_bsf.c' l='242' u='w'/>
<use f='ffmpeg/libavcodec/h264_metadata_bsf.c' l='706' u='w'/>
<use f='ffmpeg/libavcodec/h264_mp4toannexb_bsf.c' l='318' u='w'/>
<use f='ffmpeg/libavcodec/h264_redundant_pps_bsf.c' l='144' u='w'/>
<use f='ffmpeg/libavcodec/h265_metadata_bsf.c' l='505' u='w'/>
<use f='ffmpeg/libavcodec/hevc_mp4toannexb_bsf.c' l='201' u='w'/>
<use f='ffmpeg/libavcodec/mpeg2_metadata_bsf.c' l='239' u='w'/>
<use f='ffmpeg/libavcodec/mpeg4_unpack_bframes_bsf.c' l='161' u='w'/>
<use f='ffmpeg/libavcodec/opus_metadata_bsf.c' l='64' u='w'/>
<use f='ffmpeg/libavcodec/pcm_rechunk_bsf.c' l='216' u='w'/>
<use f='ffmpeg/libavcodec/prores_metadata_bsf.c' l='171' u='w'/>
<use f='ffmpeg/libavcodec/remove_extradata_bsf.c' l='115' u='w'/>
<use f='ffmpeg/libavcodec/setts_bsf.c' l='218' u='w'/>
<use f='ffmpeg/libavcodec/trace_headers_bsf.c' l='110' u='w'/>
<use f='ffmpeg/libavcodec/vp9_metadata_bsf.c' l='142' u='w'/>
<use f='ffmpeg/libavcodec/vp9_superframe_bsf.c' l='218' u='w'/>
<use f='ffmpeg/libavcodec/vp9_superframe_split_bsf.c' l='161' u='w'/>
