<dec f='ffmpeg/libavcodec/cavs.h' l='161' type='AVFrame *'/>
<use f='ffmpeg/libavcodec/cavs.c' l='479' u='r' c='mc_part_std'/>
<use f='ffmpeg/libavcodec/cavs.c' l='489' u='r' c='mc_part_std'/>
<use f='ffmpeg/libavcodec/cavs.c' l='709' u='r' c='ff_cavs_next_mb'/>
<use f='ffmpeg/libavcodec/cavs.c' l='710' u='r' c='ff_cavs_next_mb'/>
<use f='ffmpeg/libavcodec/cavs.c' l='711' u='r' c='ff_cavs_next_mb'/>
<use f='ffmpeg/libavcodec/cavs.c' l='737' u='r' c='ff_cavs_init_pic'/>
<use f='ffmpeg/libavcodec/cavs.c' l='738' u='r' c='ff_cavs_init_pic'/>
<use f='ffmpeg/libavcodec/cavs.c' l='739' u='r' c='ff_cavs_init_pic'/>
<use f='ffmpeg/libavcodec/cavs.c' l='740' u='r' c='ff_cavs_init_pic'/>
<use f='ffmpeg/libavcodec/cavs.c' l='741' u='r' c='ff_cavs_init_pic'/>
<use f='ffmpeg/libavcodec/cavs.c' l='812' u='w' c='ff_cavs_init'/>
<use f='ffmpeg/libavcodec/cavs.c' l='813' u='w' c='ff_cavs_init'/>
<use f='ffmpeg/libavcodec/cavs.c' l='814' u='w' c='ff_cavs_init'/>
<use f='ffmpeg/libavcodec/cavs.c' l='815' u='r' c='ff_cavs_init'/>
<use f='ffmpeg/libavcodec/cavs.c' l='815' u='r' c='ff_cavs_init'/>
<use f='ffmpeg/libavcodec/cavs.c' l='815' u='r' c='ff_cavs_init'/>
<use f='ffmpeg/libavcodec/cavs.c' l='846' u='a' c='ff_cavs_end'/>
<use f='ffmpeg/libavcodec/cavs.c' l='847' u='a' c='ff_cavs_end'/>
<use f='ffmpeg/libavcodec/cavs.c' l='848' u='a' c='ff_cavs_end'/>
<offset>0</offset>
<use f='ffmpeg/libavcodec/cavsdec.c' l='647' u='r' c='set_mv_intra'/>
<use f='ffmpeg/libavcodec/cavsdec.c' l='687' u='r' c='decode_mb_i'/>
<use f='ffmpeg/libavcodec/cavsdec.c' l='944' u='r' c='decode_slice_header'/>
<use f='ffmpeg/libavcodec/cavsdec.c' l='992' u='r' c='decode_pic'/>
<use f='ffmpeg/libavcodec/cavsdec.c' l='996' u='r' c='decode_pic'/>
<use f='ffmpeg/libavcodec/cavsdec.c' l='997' u='r' c='decode_pic'/>
<use f='ffmpeg/libavcodec/cavsdec.c' l='1002' u='r' c='decode_pic'/>
<use f='ffmpeg/libavcodec/cavsdec.c' l='1003' u='r' c='decode_pic'/>
<use f='ffmpeg/libavcodec/cavsdec.c' l='1003' u='r' c='decode_pic'/>
<use f='ffmpeg/libavcodec/cavsdec.c' l='1006' u='r' c='decode_pic'/>
<use f='ffmpeg/libavcodec/cavsdec.c' l='1020' u='r' c='decode_pic'/>
<use f='ffmpeg/libavcodec/cavsdec.c' l='1020' u='r' c='decode_pic'/>
<use f='ffmpeg/libavcodec/cavsdec.c' l='1026' u='r' c='decode_pic'/>
<use f='ffmpeg/libavcodec/cavsdec.c' l='1026' u='r' c='decode_pic'/>
<use f='ffmpeg/libavcodec/cavsdec.c' l='1026' u='r' c='decode_pic'/>
<use f='ffmpeg/libavcodec/cavsdec.c' l='1037' u='r' c='decode_pic'/>
<use f='ffmpeg/libavcodec/cavsdec.c' l='1045' u='r' c='decode_pic'/>
<use f='ffmpeg/libavcodec/cavsdec.c' l='1069' u='r' c='decode_pic'/>
<use f='ffmpeg/libavcodec/cavsdec.c' l='1074' u='r' c='decode_pic'/>
<use f='ffmpeg/libavcodec/cavsdec.c' l='1093' u='r' c='decode_pic'/>
<use f='ffmpeg/libavcodec/cavsdec.c' l='1100' u='r' c='decode_pic'/>
<use f='ffmpeg/libavcodec/cavsdec.c' l='1156' u='r' c='decode_pic'/>
<use f='ffmpeg/libavcodec/cavsdec.c' l='1157' u='r' c='decode_pic'/>
<use f='ffmpeg/libavcodec/cavsdec.c' l='1239' u='r' c='cavs_decode_frame'/>
<use f='ffmpeg/libavcodec/cavsdec.c' l='1241' u='r' c='cavs_decode_frame'/>
<use f='ffmpeg/libavcodec/cavsdec.c' l='1265' u='r' c='cavs_decode_frame'/>
<use f='ffmpeg/libavcodec/cavsdec.c' l='1266' u='r' c='cavs_decode_frame'/>
<use f='ffmpeg/libavcodec/cavsdec.c' l='1283' u='r' c='cavs_decode_frame'/>
<use f='ffmpeg/libavcodec/cavsdec.c' l='1284' u='r' c='cavs_decode_frame'/>
<use f='ffmpeg/libavcodec/cavsdec.c' l='1285' u='r' c='cavs_decode_frame'/>
<use f='ffmpeg/libavcodec/cavsdec.c' l='1291' u='r' c='cavs_decode_frame'/>
