<dec f='ffmpeg/libavcodec/avcodec.h' l='2698' type='int'/>
<offset>96</offset>
<doc f='ffmpeg/libavcodec/avcodec.h' l='2698'>///&lt; height           of pict, undefined when pict is not set</doc>
<use f='ffmpeg/fftools/ffmpeg.c' l='203' u='r' c='sub2video_copy_rect'/>
<use f='ffmpeg/fftools/ffmpeg.c' l='205' u='r' c='sub2video_copy_rect'/>
<use f='ffmpeg/fftools/ffmpeg.c' l='213' u='r' c='sub2video_copy_rect'/>
<use f='ffmpeg/libavcodec/dvbsubdec.c' l='788' u='w' c='save_subtitle_set'/>
<use f='ffmpeg/libavcodec/dvbsubdec.c' l='828' u='r' c='save_subtitle_set'/>
<use f='ffmpeg/libavcodec/dvbsubenc.c' l='405' u='r' c='dvbsub_encode'/>
<use f='ffmpeg/libavcodec/dvbsubenc.c' l='469' u='r' c='dvbsub_encode'/>
<use f='ffmpeg/libavcodec/dvbsubenc.c' l='478' u='r' c='dvbsub_encode'/>
<use f='ffmpeg/libavcodec/dvdsubdec.c' l='408' u='w' c='decode_dvd_subtitles'/>
<use f='ffmpeg/libavcodec/dvdsubdec.c' l='458' u='r' c='find_smallest_bounding_rectangle'/>
<use f='ffmpeg/libavcodec/dvdsubdec.c' l='470' u='r' c='find_smallest_bounding_rectangle'/>
<use f='ffmpeg/libavcodec/dvdsubdec.c' l='473' u='r' c='find_smallest_bounding_rectangle'/>
<use f='ffmpeg/libavcodec/dvdsubdec.c' l='475' u='w' c='find_smallest_bounding_rectangle'/>
<use f='ffmpeg/libavcodec/dvdsubdec.c' l='479' u='r' c='find_smallest_bounding_rectangle'/>
<use f='ffmpeg/libavcodec/dvdsubdec.c' l='485' u='r' c='find_smallest_bounding_rectangle'/>
<use f='ffmpeg/libavcodec/dvdsubdec.c' l='488' u='r' c='find_smallest_bounding_rectangle'/>
<use f='ffmpeg/libavcodec/dvdsubdec.c' l='503' u='w' c='find_smallest_bounding_rectangle'/>
<use f='ffmpeg/libavcodec/dvdsubenc.c' l='127' u='r' c='count_colors'/>
<use f='ffmpeg/libavcodec/dvdsubenc.c' l='243' u='r' c='copy_rectangle'/>
<use f='ffmpeg/libavcodec/dvdsubenc.c' l='304' u='r' c='encode_dvd_subtitles'/>
<use f='ffmpeg/libavcodec/dvdsubenc.c' l='309' u='r' c='encode_dvd_subtitles'/>
<use f='ffmpeg/libavcodec/dvdsubenc.c' l='309' u='r' c='encode_dvd_subtitles'/>
<use f='ffmpeg/libavcodec/dvdsubenc.c' l='314' u='w' c='encode_dvd_subtitles'/>
<use f='ffmpeg/libavcodec/dvdsubenc.c' l='315' u='r' c='encode_dvd_subtitles'/>
<use f='ffmpeg/libavcodec/dvdsubenc.c' l='319' u='r' c='encode_dvd_subtitles'/>
<use f='ffmpeg/libavcodec/dvdsubenc.c' l='321' u='r' c='encode_dvd_subtitles'/>
<use f='ffmpeg/libavcodec/dvdsubenc.c' l='329' u='r' c='encode_dvd_subtitles'/>
<use f='ffmpeg/libavcodec/dvdsubenc.c' l='356' u='r' c='encode_dvd_subtitles'/>
<use f='ffmpeg/libavcodec/dvdsubenc.c' l='362' u='r' c='encode_dvd_subtitles'/>
<use f='ffmpeg/libavcodec/dvdsubenc.c' l='365' u='r' c='encode_dvd_subtitles'/>
<use f='ffmpeg/libavcodec/dvdsubenc.c' l='367' u='r' c='encode_dvd_subtitles'/>
<use f='ffmpeg/libavcodec/dvdsubenc.c' l='369' u='w' c='encode_dvd_subtitles'/>
<use f='ffmpeg/libavcodec/dvdsubenc.c' l='390' u='r' c='encode_dvd_subtitles'/>
<use f='ffmpeg/libavcodec/pgssubdec.c' l='169' u='r' c='decode_rle'/>
<use f='ffmpeg/libavcodec/pgssubdec.c' l='177' u='r' c='decode_rle'/>
<use f='ffmpeg/libavcodec/pgssubdec.c' l='192' u='r' c='decode_rle'/>
<use f='ffmpeg/libavcodec/pgssubdec.c' l='211' u='r' c='decode_rle'/>
<use f='ffmpeg/libavcodec/pgssubdec.c' l='216' u='r' c='decode_rle'/>
<use f='ffmpeg/libavcodec/pgssubdec.c' l='565' u='w' c='display_end_segment'/>
<use f='ffmpeg/libavcodec/pgssubdec.c' l='585' u='w' c='display_end_segment'/>
<use f='ffmpeg/libavcodec/xsubdec.c' l='109' u='w' c='decode_frame'/>
<use f='ffmpeg/libavcodec/xsubenc.c' l='177' u='r' c='xsub_encode'/>
<use f='ffmpeg/libavcodec/xsubenc.c' l='198' u='r' c='xsub_encode'/>
<use f='ffmpeg/libavcodec/xsubenc.c' l='204' u='r' c='xsub_encode'/>
<use f='ffmpeg/libavcodec/xsubenc.c' l='208' u='r' c='xsub_encode'/>
