<dec f='ffmpeg/libavcodec/mpc.h' l='47' type='int [2]'/>
<use f='ffmpeg/libavcodec/mpc.c' l='69' u='r' c='ff_mpc_dequantize_and_synth'/>
<use f='ffmpeg/libavcodec/mpc.c' l='71' u='r' c='ff_mpc_dequantize_and_synth'/>
<use f='ffmpeg/libavcodec/mpc.c' l='74' u='r' c='ff_mpc_dequantize_and_synth'/>
<use f='ffmpeg/libavcodec/mpc.c' l='77' u='r' c='ff_mpc_dequantize_and_synth'/>
<offset>32</offset>
<use f='ffmpeg/libavcodec/mpc7.c' l='223' u='w' c='mpc7_decode_frame'/>
<use f='ffmpeg/libavcodec/mpc7.c' l='224' u='w' c='mpc7_decode_frame'/>
<use f='ffmpeg/libavcodec/mpc7.c' l='224' u='r' c='mpc7_decode_frame'/>
<use f='ffmpeg/libavcodec/mpc7.c' l='225' u='r' c='mpc7_decode_frame'/>
<use f='ffmpeg/libavcodec/mpc7.c' l='225' u='r' c='mpc7_decode_frame'/>
<use f='ffmpeg/libavcodec/mpc7.c' l='231' u='r' c='mpc7_decode_frame'/>
<use f='ffmpeg/libavcodec/mpc7.c' l='231' u='r' c='mpc7_decode_frame'/>
<use f='ffmpeg/libavcodec/mpc7.c' l='239' u='r' c='mpc7_decode_frame'/>
<use f='ffmpeg/libavcodec/mpc7.c' l='243' u='r' c='mpc7_decode_frame'/>
<use f='ffmpeg/libavcodec/mpc7.c' l='272' u='r' c='mpc7_decode_frame'/>
<use f='ffmpeg/libavcodec/mpc8.c' l='230' u='w' c='mpc8_decode_frame'/>
<use f='ffmpeg/libavcodec/mpc8.c' l='238' u='r' c='mpc8_decode_frame'/>
<use f='ffmpeg/libavcodec/mpc8.c' l='238' u='r' c='mpc8_decode_frame'/>
<use f='ffmpeg/libavcodec/mpc8.c' l='243' u='r' c='mpc8_decode_frame'/>
<use f='ffmpeg/libavcodec/mpc8.c' l='243' u='r' c='mpc8_decode_frame'/>
<use f='ffmpeg/libavcodec/mpc8.c' l='250' u='w' c='mpc8_decode_frame'/>
<use f='ffmpeg/libavcodec/mpc8.c' l='250' u='w' c='mpc8_decode_frame'/>
<use f='ffmpeg/libavcodec/mpc8.c' l='258' u='r' c='mpc8_decode_frame'/>
<use f='ffmpeg/libavcodec/mpc8.c' l='258' u='r' c='mpc8_decode_frame'/>
<use f='ffmpeg/libavcodec/mpc8.c' l='259' u='r' c='mpc8_decode_frame'/>
<use f='ffmpeg/libavcodec/mpc8.c' l='259' u='r' c='mpc8_decode_frame'/>
<use f='ffmpeg/libavcodec/mpc8.c' l='262' u='r' c='mpc8_decode_frame'/>
<use f='ffmpeg/libavcodec/mpc8.c' l='263' u='r' c='mpc8_decode_frame'/>
<use f='ffmpeg/libavcodec/mpc8.c' l='270' u='r' c='mpc8_decode_frame'/>
<use f='ffmpeg/libavcodec/mpc8.c' l='296' u='r' c='mpc8_decode_frame'/>
