<dec f='ffmpeg/libavcodec/aac.h' l='285' type='SingleChannelElement [2]'/>
<use f='ffmpeg/libavcodec/aaccoder.c' l='765' u='a' c='search_for_ms'/>
<use f='ffmpeg/libavcodec/aaccoder.c' l='766' u='a' c='search_for_ms'/>
<offset>2304</offset>
<doc f='ffmpeg/libavcodec/aac.h' l='284'>// shared</doc>
<use f='ffmpeg/libavcodec/aacdec.c' l='219' u='m' c='apply_dependent_coupling'/>
<use f='ffmpeg/libavcodec/aacdec.c' l='222' u='m' c='apply_dependent_coupling'/>
<use f='ffmpeg/libavcodec/aacdec.c' l='231' u='m' c='apply_dependent_coupling'/>
<use f='ffmpeg/libavcodec/aacdec.c' l='256' u='m' c='apply_independent_coupling'/>
<use f='ffmpeg/libavcodec/aacdec_template.c' l='144' u='a' c='che_configure'/>
<use f='ffmpeg/libavcodec/aacdec_template.c' l='147' u='a' c='che_configure'/>
<use f='ffmpeg/libavcodec/aacdec_template.c' l='168' u='m' c='frame_configure_elements'/>
<use f='ffmpeg/libavcodec/aacdec_template.c' l='168' u='m' c='frame_configure_elements'/>
<use f='ffmpeg/libavcodec/aacdec_template.c' l='169' u='m' c='frame_configure_elements'/>
<use f='ffmpeg/libavcodec/aacdec_template.c' l='169' u='m' c='frame_configure_elements'/>
<use f='ffmpeg/libavcodec/aacdec_template.c' l='602' u='m' c='flush'/>
<use f='ffmpeg/libavcodec/aacdec_template.c' l='602' u='m' c='flush'/>
<use f='ffmpeg/libavcodec/aacdec_template.c' l='1727' u='m' c='decode_mid_side_stereo'/>
<use f='ffmpeg/libavcodec/aacdec_template.c' l='1727' u='m' c='decode_mid_side_stereo'/>
<use f='ffmpeg/libavcodec/aacdec_template.c' l='2199' u='m' c='apply_mid_side_stereo'/>
<use f='ffmpeg/libavcodec/aacdec_template.c' l='2200' u='m' c='apply_mid_side_stereo'/>
<use f='ffmpeg/libavcodec/aacdec_template.c' l='2201' u='m' c='apply_mid_side_stereo'/>
<use f='ffmpeg/libavcodec/aacdec_template.c' l='2207' u='m' c='apply_mid_side_stereo'/>
<use f='ffmpeg/libavcodec/aacdec_template.c' l='2208' u='m' c='apply_mid_side_stereo'/>
<use f='ffmpeg/libavcodec/aacdec_template.c' l='2238' u='m' c='apply_intensity_stereo'/>
<use f='ffmpeg/libavcodec/aacdec_template.c' l='2239' u='a' c='apply_intensity_stereo'/>
<use f='ffmpeg/libavcodec/aacdec_template.c' l='2240' u='m' c='apply_intensity_stereo'/>
<use f='ffmpeg/libavcodec/aacdec_template.c' l='2240' u='m' c='apply_intensity_stereo'/>
<use f='ffmpeg/libavcodec/aacdec_template.c' l='2292' u='m' c='decode_cpe'/>
<use f='ffmpeg/libavcodec/aacdec_template.c' l='2294' u='m' c='decode_cpe'/>
<use f='ffmpeg/libavcodec/aacdec_template.c' l='2295' u='m' c='decode_cpe'/>
<use f='ffmpeg/libavcodec/aacdec_template.c' l='2295' u='m' c='decode_cpe'/>
<use f='ffmpeg/libavcodec/aacdec_template.c' l='2296' u='m' c='decode_cpe'/>
<use f='ffmpeg/libavcodec/aacdec_template.c' l='2297' u='m' c='decode_cpe'/>
<use f='ffmpeg/libavcodec/aacdec_template.c' l='2299' u='m' c='decode_cpe'/>
<use f='ffmpeg/libavcodec/aacdec_template.c' l='2300' u='m' c='decode_cpe'/>
<use f='ffmpeg/libavcodec/aacdec_template.c' l='2300' u='m' c='decode_cpe'/>
<use f='ffmpeg/libavcodec/aacdec_template.c' l='2308' u='a' c='decode_cpe'/>
<use f='ffmpeg/libavcodec/aacdec_template.c' l='2310' u='a' c='decode_cpe'/>
<use f='ffmpeg/libavcodec/aacdec_template.c' l='2317' u='a' c='decode_cpe'/>
<use f='ffmpeg/libavcodec/aacdec_template.c' l='2318' u='a' c='decode_cpe'/>
<use f='ffmpeg/libavcodec/aacdec_template.c' l='2344' u='a' c='decode_cce'/>
<use f='ffmpeg/libavcodec/aacdec_template.c' l='2996' u='a' c='apply_channel_coupling'/>
<use f='ffmpeg/libavcodec/aacdec_template.c' l='3001' u='a' c='apply_channel_coupling'/>
<use f='ffmpeg/libavcodec/aacdec_template.c' l='3036' u='m' c='spectral_to_sample'/>
<use f='ffmpeg/libavcodec/aacdec_template.c' l='3037' u='m' c='spectral_to_sample'/>
<use f='ffmpeg/libavcodec/aacdec_template.c' l='3038' u='a' c='spectral_to_sample'/>
<use f='ffmpeg/libavcodec/aacdec_template.c' l='3039' u='m' c='spectral_to_sample'/>
<use f='ffmpeg/libavcodec/aacdec_template.c' l='3040' u='a' c='spectral_to_sample'/>
<use f='ffmpeg/libavcodec/aacdec_template.c' l='3043' u='m' c='spectral_to_sample'/>
<use f='ffmpeg/libavcodec/aacdec_template.c' l='3044' u='m' c='spectral_to_sample'/>
<use f='ffmpeg/libavcodec/aacdec_template.c' l='3044' u='m' c='spectral_to_sample'/>
<use f='ffmpeg/libavcodec/aacdec_template.c' l='3044' u='m' c='spectral_to_sample'/>
<use f='ffmpeg/libavcodec/aacdec_template.c' l='3045' u='m' c='spectral_to_sample'/>
<use f='ffmpeg/libavcodec/aacdec_template.c' l='3046' u='m' c='spectral_to_sample'/>
<use f='ffmpeg/libavcodec/aacdec_template.c' l='3046' u='m' c='spectral_to_sample'/>
<use f='ffmpeg/libavcodec/aacdec_template.c' l='3046' u='m' c='spectral_to_sample'/>
<use f='ffmpeg/libavcodec/aacdec_template.c' l='3050' u='a' c='spectral_to_sample'/>
<use f='ffmpeg/libavcodec/aacdec_template.c' l='3052' u='a' c='spectral_to_sample'/>
<use f='ffmpeg/libavcodec/aacdec_template.c' l='3054' u='a' c='spectral_to_sample'/>
<use f='ffmpeg/libavcodec/aacdec_template.c' l='3056' u='a' c='spectral_to_sample'/>
<use f='ffmpeg/libavcodec/aacdec_template.c' l='3059' u='m' c='spectral_to_sample'/>
<use f='ffmpeg/libavcodec/aacdec_template.c' l='3059' u='m' c='spectral_to_sample'/>
<use f='ffmpeg/libavcodec/aacdec_template.c' l='3190' u='a' c='aac_decode_er_frame'/>
<use f='ffmpeg/libavcodec/aacdec_template.c' l='3196' u='a' c='aac_decode_er_frame'/>
<use f='ffmpeg/libavcodec/aacdec_template.c' l='3291' u='a' c='aac_decode_frame_int'/>
<use f='ffmpeg/libavcodec/aacdec_template.c' l='3306' u='a' c='aac_decode_frame_int'/>
<use f='ffmpeg/libavcodec/aacdec_fixed.c' l='361' u='m' c='apply_dependent_coupling_fixed'/>
<use f='ffmpeg/libavcodec/aacdec_fixed.c' l='364' u='m' c='apply_dependent_coupling_fixed'/>
<use f='ffmpeg/libavcodec/aacdec_fixed.c' l='373' u='m' c='apply_dependent_coupling_fixed'/>
<use f='ffmpeg/libavcodec/aacdec_fixed.c' l='427' u='m' c='apply_independent_coupling_fixed'/>
<use f='ffmpeg/libavcodec/aacenc.c' l='245' u='m' c='encode_ms_info'/>
<use f='ffmpeg/libavcodec/aacenc.c' l='245' u='m' c='encode_ms_info'/>
<use f='ffmpeg/libavcodec/aacenc.c' l='246' u='m' c='encode_ms_info'/>
<use f='ffmpeg/libavcodec/aacenc.c' l='259' u='m' c='adjust_frame_information'/>
<use f='ffmpeg/libavcodec/aacenc.c' l='261' u='m' c='adjust_frame_information'/>
<use f='ffmpeg/libavcodec/aacenc.c' l='264' u='m' c='adjust_frame_information'/>
<use f='ffmpeg/libavcodec/aacenc.c' l='276' u='m' c='adjust_frame_information'/>
<use f='ffmpeg/libavcodec/aacenc.c' l='281' u='m' c='adjust_frame_information'/>
<use f='ffmpeg/libavcodec/aacenc.c' l='287' u='m' c='adjust_frame_information'/>
<use f='ffmpeg/libavcodec/aacenc.c' l='288' u='m' c='adjust_frame_information'/>
<use f='ffmpeg/libavcodec/aacenc.c' l='306' u='m' c='apply_intensity_stereo'/>
<use f='ffmpeg/libavcodec/aacenc.c' l='313' u='m' c='apply_intensity_stereo'/>
<use f='ffmpeg/libavcodec/aacenc.c' l='314' u='m' c='apply_intensity_stereo'/>
<use f='ffmpeg/libavcodec/aacenc.c' l='322' u='m' c='apply_intensity_stereo'/>
<use f='ffmpeg/libavcodec/aacenc.c' l='322' u='m' c='apply_intensity_stereo'/>
<use f='ffmpeg/libavcodec/aacenc.c' l='323' u='m' c='apply_intensity_stereo'/>
<use f='ffmpeg/libavcodec/aacenc.c' l='324' u='m' c='apply_intensity_stereo'/>
<use f='ffmpeg/libavcodec/aacenc.c' l='335' u='m' c='apply_mid_side_stereo'/>
<use f='ffmpeg/libavcodec/aacenc.c' l='347' u='m' c='apply_mid_side_stereo'/>
<use f='ffmpeg/libavcodec/aacenc.c' l='348' u='m' c='apply_mid_side_stereo'/>
<use f='ffmpeg/libavcodec/aacenc.c' l='353' u='m' c='apply_mid_side_stereo'/>
<use f='ffmpeg/libavcodec/aacenc.c' l='353' u='m' c='apply_mid_side_stereo'/>
<use f='ffmpeg/libavcodec/aacenc.c' l='354' u='m' c='apply_mid_side_stereo'/>
<use f='ffmpeg/libavcodec/aacenc.c' l='355' u='m' c='apply_mid_side_stereo'/>
<use f='ffmpeg/libavcodec/aacenc.c' l='356' u='m' c='apply_mid_side_stereo'/>
<use f='ffmpeg/libavcodec/aacenc.c' l='592' u='a' c='aac_encode_frame'/>
<use f='ffmpeg/libavcodec/aacenc.c' l='669' u='m' c='aac_encode_frame'/>
<use f='ffmpeg/libavcodec/aacenc.c' l='701' u='a' c='aac_encode_frame'/>
<use f='ffmpeg/libavcodec/aacenc.c' l='725' u='a' c='aac_encode_frame'/>
<use f='ffmpeg/libavcodec/aacenc.c' l='726' u='a' c='aac_encode_frame'/>
<use f='ffmpeg/libavcodec/aacenc.c' l='741' u='a' c='aac_encode_frame'/>
<use f='ffmpeg/libavcodec/aacenc.c' l='761' u='a' c='aac_encode_frame'/>
<use f='ffmpeg/libavcodec/aacenc.c' l='765' u='m' c='aac_encode_frame'/>
<use f='ffmpeg/libavcodec/aacenc.c' l='770' u='a' c='aac_encode_frame'/>
<use f='ffmpeg/libavcodec/aacenc.c' l='787' u='a' c='aac_encode_frame'/>
<use f='ffmpeg/libavcodec/aacenc.c' l='800' u='m' c='aac_encode_frame'/>
<use f='ffmpeg/libavcodec/aacenc.c' l='802' u='a' c='aac_encode_frame'/>
<use f='ffmpeg/libavcodec/aacenc.c' l='804' u='a' c='aac_encode_frame'/>
<use f='ffmpeg/libavcodec/aacenc.c' l='811' u='a' c='aac_encode_frame'/>
<use f='ffmpeg/libavcodec/aacenc.c' l='867' u='m' c='aac_encode_frame'/>
<use f='ffmpeg/libavcodec/aacenc.c' l='867' u='m' c='aac_encode_frame'/>
<use f='ffmpeg/libavcodec/aacenc.c' l='867' u='m' c='aac_encode_frame'/>
<use f='ffmpeg/libavcodec/aacenc_is.c' l='39' u='a' c='ff_aac_is_encoding_err'/>
<use f='ffmpeg/libavcodec/aacenc_is.c' l='40' u='a' c='ff_aac_is_encoding_err'/>
<use f='ffmpeg/libavcodec/aacenc_is.c' l='100' u='a' c='ff_aac_search_for_is'/>
<use f='ffmpeg/libavcodec/aacenc_is.c' l='101' u='a' c='ff_aac_search_for_is'/>
<use f='ffmpeg/libavcodec/aacenc_is.c' l='116' u='m' c='ff_aac_search_for_is'/>
<use f='ffmpeg/libavcodec/aacenc_is.c' l='116' u='m' c='ff_aac_search_for_is'/>
<use f='ffmpeg/libavcodec/aacenc_is.c' l='117' u='m' c='ff_aac_search_for_is'/>
<use f='ffmpeg/libavcodec/aacenc_is.c' l='117' u='m' c='ff_aac_search_for_is'/>
<use f='ffmpeg/libavcodec/aacenc_is.c' l='139' u='m' c='ff_aac_search_for_is'/>
<use f='ffmpeg/libavcodec/aacenc_is.c' l='140' u='m' c='ff_aac_search_for_is'/>
<use f='ffmpeg/libavcodec/aacenc_is.c' l='141' u='m' c='ff_aac_search_for_is'/>
<use f='ffmpeg/libavcodec/aacenc_is.c' l='142' u='m' c='ff_aac_search_for_is'/>
<use f='ffmpeg/libavcodec/aacenc_is.c' l='145' u='m' c='ff_aac_search_for_is'/>
<use f='ffmpeg/libavcodec/aacenc_is.c' l='147' u='m' c='ff_aac_search_for_is'/>
<use f='ffmpeg/libavcodec/aacenc_ltp.c' l='63' u='a' c='ff_aac_ltp_insert_new_frame'/>
<use f='ffmpeg/libavcodec/aacenc_ltp.c' l='133' u='a' c='ff_aac_adjust_common_ltp'/>
<use f='ffmpeg/libavcodec/aacenc_ltp.c' l='134' u='a' c='ff_aac_adjust_common_ltp'/>
<use f='ffmpeg/libavcodec/aacenc_pred.c' l='154' u='a' c='ff_aac_adjust_common_pred'/>
<use f='ffmpeg/libavcodec/aacenc_pred.c' l='155' u='a' c='ff_aac_adjust_common_pred'/>
