<dec f='ffmpeg/libavcodec/dnxhdenc.h' l='49' type='MpegEncContext'/>
<use f='ffmpeg/libavcodec/dnxhdenc.c' l='269' u='m' c='dnxhd_init_qmat'/>
<use f='ffmpeg/libavcodec/dnxhdenc.c' l='270' u='m' c='dnxhd_init_qmat'/>
<use f='ffmpeg/libavcodec/dnxhdenc.c' l='271' u='m' c='dnxhd_init_qmat'/>
<use f='ffmpeg/libavcodec/dnxhdenc.c' l='272' u='m' c='dnxhd_init_qmat'/>
<use f='ffmpeg/libavcodec/dnxhdenc.c' l='277' u='m' c='dnxhd_init_qmat'/>
<use f='ffmpeg/libavcodec/dnxhdenc.c' l='280' u='a' c='dnxhd_init_qmat'/>
<use f='ffmpeg/libavcodec/dnxhdenc.c' l='282' u='m' c='dnxhd_init_qmat'/>
<use f='ffmpeg/libavcodec/dnxhdenc.c' l='284' u='m' c='dnxhd_init_qmat'/>
<use f='ffmpeg/libavcodec/dnxhdenc.c' l='287' u='a' c='dnxhd_init_qmat'/>
<use f='ffmpeg/libavcodec/dnxhdenc.c' l='289' u='m' c='dnxhd_init_qmat'/>
<use f='ffmpeg/libavcodec/dnxhdenc.c' l='291' u='m' c='dnxhd_init_qmat'/>
<use f='ffmpeg/libavcodec/dnxhdenc.c' l='303' u='m' c='dnxhd_init_qmat'/>
<use f='ffmpeg/libavcodec/dnxhdenc.c' l='326' u='m' c='dnxhd_init_qmat'/>
<use f='ffmpeg/libavcodec/dnxhdenc.c' l='327' u='m' c='dnxhd_init_qmat'/>
<use f='ffmpeg/libavcodec/dnxhdenc.c' l='328' u='m' c='dnxhd_init_qmat'/>
<use f='ffmpeg/libavcodec/dnxhdenc.c' l='329' u='m' c='dnxhd_init_qmat'/>
<use f='ffmpeg/libavcodec/dnxhdenc.c' l='336' u='m' c='dnxhd_init_rc'/>
<use f='ffmpeg/libavcodec/dnxhdenc.c' l='336' u='m' c='dnxhd_init_rc'/>
<use f='ffmpeg/libavcodec/dnxhdenc.c' l='339' u='m' c='dnxhd_init_rc'/>
<use f='ffmpeg/libavcodec/dnxhdenc.c' l='340' u='m' c='dnxhd_init_rc'/>
<use f='ffmpeg/libavcodec/dnxhdenc.c' l='341' u='m' c='dnxhd_init_rc'/>
<use f='ffmpeg/libavcodec/dnxhdenc.c' l='417' u='m' c='dnxhd_encode_init'/>
<use f='ffmpeg/libavcodec/dnxhdenc.c' l='418' u='m' c='dnxhd_encode_init'/>
<use f='ffmpeg/libavcodec/dnxhdenc.c' l='419' u='m' c='dnxhd_encode_init'/>
<use f='ffmpeg/libavcodec/dnxhdenc.c' l='424' u='m' c='dnxhd_encode_init'/>
<use f='ffmpeg/libavcodec/dnxhdenc.c' l='425' u='a' c='dnxhd_encode_init'/>
<use f='ffmpeg/libavcodec/dnxhdenc.c' l='426' u='m' c='dnxhd_encode_init'/>
<use f='ffmpeg/libavcodec/dnxhdenc.c' l='427' u='m' c='dnxhd_encode_init'/>
<use f='ffmpeg/libavcodec/dnxhdenc.c' l='428' u='a' c='dnxhd_encode_init'/>
<use f='ffmpeg/libavcodec/dnxhdenc.c' l='431' u='m' c='dnxhd_encode_init'/>
<use f='ffmpeg/libavcodec/dnxhdenc.c' l='433' u='m' c='dnxhd_encode_init'/>
<use f='ffmpeg/libavcodec/dnxhdenc.c' l='434' u='m' c='dnxhd_encode_init'/>
<use f='ffmpeg/libavcodec/dnxhdenc.c' l='437' u='m' c='dnxhd_encode_init'/>
<use f='ffmpeg/libavcodec/dnxhdenc.c' l='441' u='m' c='dnxhd_encode_init'/>
<use f='ffmpeg/libavcodec/dnxhdenc.c' l='452' u='m' c='dnxhd_encode_init'/>
<use f='ffmpeg/libavcodec/dnxhdenc.c' l='453' u='m' c='dnxhd_encode_init'/>
<use f='ffmpeg/libavcodec/dnxhdenc.c' l='457' u='m' c='dnxhd_encode_init'/>
<use f='ffmpeg/libavcodec/dnxhdenc.c' l='466' u='m' c='dnxhd_encode_init'/>
<use f='ffmpeg/libavcodec/dnxhdenc.c' l='466' u='m' c='dnxhd_encode_init'/>
<use f='ffmpeg/libavcodec/dnxhdenc.c' l='466' u='m' c='dnxhd_encode_init'/>
<use f='ffmpeg/libavcodec/dnxhdenc.c' l='478' u='m' c='dnxhd_encode_init'/>
<use f='ffmpeg/libavcodec/dnxhdenc.c' l='479' u='m' c='dnxhd_encode_init'/>
<use f='ffmpeg/libavcodec/dnxhdenc.c' l='497' u='m' c='dnxhd_encode_init'/>
<use f='ffmpeg/libavcodec/dnxhdenc.c' l='498' u='m' c='dnxhd_encode_init'/>
<use f='ffmpeg/libavcodec/dnxhdenc.c' l='499' u='m' c='dnxhd_encode_init'/>
<use f='ffmpeg/libavcodec/dnxhdenc.c' l='500' u='m' c='dnxhd_encode_init'/>
<use f='ffmpeg/libavcodec/dnxhdenc.c' l='562' u='m' c='dnxhd_write_header'/>
<use f='ffmpeg/libavcodec/dnxhdenc.c' l='563' u='m' c='dnxhd_write_header'/>
<use f='ffmpeg/libavcodec/dnxhdenc.c' l='579' u='m' c='dnxhd_encode_dc'/>
<use f='ffmpeg/libavcodec/dnxhdenc.c' l='591' u='m' c='dnxhd_encode_block'/>
<use f='ffmpeg/libavcodec/dnxhdenc.c' l='592' u='m' c='dnxhd_encode_block'/>
<use f='ffmpeg/libavcodec/dnxhdenc.c' l='595' u='m' c='dnxhd_encode_block'/>
<use f='ffmpeg/libavcodec/dnxhdenc.c' l='600' u='m' c='dnxhd_encode_block'/>
<use f='ffmpeg/libavcodec/dnxhdenc.c' l='602' u='m' c='dnxhd_encode_block'/>
<use f='ffmpeg/libavcodec/dnxhdenc.c' l='607' u='m' c='dnxhd_encode_block'/>
<use f='ffmpeg/libavcodec/dnxhdenc.c' l='627' u='m' c='dnxhd_unquantize_c'/>
<use f='ffmpeg/libavcodec/dnxhdenc.c' l='675' u='m' c='dnxhd_calc_ac_bits'/>
<use f='ffmpeg/libavcodec/dnxhdenc.c' l='694' u='m' c='dnxhd_get_blocks'/>
<use f='ffmpeg/libavcodec/dnxhdenc.c' l='695' u='m' c='dnxhd_get_blocks'/>
<use f='ffmpeg/libavcodec/dnxhdenc.c' l='697' u='m' c='dnxhd_get_blocks'/>
<use f='ffmpeg/libavcodec/dnxhdenc.c' l='699' u='m' c='dnxhd_get_blocks'/>
<use f='ffmpeg/libavcodec/dnxhdenc.c' l='701' u='m' c='dnxhd_get_blocks'/>
<use f='ffmpeg/libavcodec/dnxhdenc.c' l='702' u='m' c='dnxhd_get_blocks'/>
<use f='ffmpeg/libavcodec/dnxhdenc.c' l='703' u='m' c='dnxhd_get_blocks'/>
<use f='ffmpeg/libavcodec/dnxhdenc.c' l='705' u='m' c='dnxhd_get_blocks'/>
<use f='ffmpeg/libavcodec/dnxhdenc.c' l='706' u='m' c='dnxhd_get_blocks'/>
<use f='ffmpeg/libavcodec/dnxhdenc.c' l='707' u='m' c='dnxhd_get_blocks'/>
<use f='ffmpeg/libavcodec/dnxhdenc.c' l='708' u='m' c='dnxhd_get_blocks'/>
<use f='ffmpeg/libavcodec/dnxhdenc.c' l='715' u='m' c='dnxhd_get_blocks'/>
<use f='ffmpeg/libavcodec/dnxhdenc.c' l='719' u='m' c='dnxhd_get_blocks'/>
<use f='ffmpeg/libavcodec/dnxhdenc.c' l='723' u='m' c='dnxhd_get_blocks'/>
<use f='ffmpeg/libavcodec/dnxhdenc.c' l='732' u='m' c='dnxhd_get_blocks'/>
<use f='ffmpeg/libavcodec/dnxhdenc.c' l='733' u='m' c='dnxhd_get_blocks'/>
<use f='ffmpeg/libavcodec/dnxhdenc.c' l='734' u='m' c='dnxhd_get_blocks'/>
<use f='ffmpeg/libavcodec/dnxhdenc.c' l='735' u='m' c='dnxhd_get_blocks'/>
<use f='ffmpeg/libavcodec/dnxhdenc.c' l='742' u='m' c='dnxhd_get_blocks'/>
<use f='ffmpeg/libavcodec/dnxhdenc.c' l='746' u='m' c='dnxhd_get_blocks'/>
<use f='ffmpeg/libavcodec/dnxhdenc.c' l='750' u='m' c='dnxhd_get_blocks'/>
<use f='ffmpeg/libavcodec/dnxhdenc.c' l='767' u='m' c='dnxhd_get_blocks'/>
<use f='ffmpeg/libavcodec/dnxhdenc.c' l='767' u='m' c='dnxhd_get_blocks'/>
<use f='ffmpeg/libavcodec/dnxhdenc.c' l='838' u='m' c='dnxhd_calc_bits_thread'/>
<use f='ffmpeg/libavcodec/dnxhdenc.c' l='839' u='m' c='dnxhd_calc_bits_thread'/>
<use f='ffmpeg/libavcodec/dnxhdenc.c' l='840' u='m' c='dnxhd_calc_bits_thread'/>
<use f='ffmpeg/libavcodec/dnxhdenc.c' l='842' u='m' c='dnxhd_calc_bits_thread'/>
<use f='ffmpeg/libavcodec/dnxhdenc.c' l='843' u='m' c='dnxhd_calc_bits_thread'/>
<use f='ffmpeg/libavcodec/dnxhdenc.c' l='857' u='m' c='dnxhd_calc_bits_thread'/>
<use f='ffmpeg/libavcodec/dnxhdenc.c' l='857' u='a' c='dnxhd_calc_bits_thread'/>
<use f='ffmpeg/libavcodec/dnxhdenc.c' l='862' u='m' c='dnxhd_calc_bits_thread'/>
<use f='ffmpeg/libavcodec/dnxhdenc.c' l='871' u='m' c='dnxhd_calc_bits_thread'/>
<use f='ffmpeg/libavcodec/dnxhdenc.c' l='875' u='m' c='dnxhd_calc_bits_thread'/>
<use f='ffmpeg/libavcodec/dnxhdenc.c' l='879' u='m' c='dnxhd_calc_bits_thread'/>
<use f='ffmpeg/libavcodec/dnxhdenc.c' l='880' u='m' c='dnxhd_calc_bits_thread'/>
<use f='ffmpeg/libavcodec/dnxhdenc.c' l='892' u='m' c='dnxhd_encode_thread'/>
<use f='ffmpeg/libavcodec/dnxhdenc.c' l='895' u='m' c='dnxhd_encode_thread'/>
<use f='ffmpeg/libavcodec/dnxhdenc.c' l='896' u='m' c='dnxhd_encode_thread'/>
<use f='ffmpeg/libavcodec/dnxhdenc.c' l='897' u='m' c='dnxhd_encode_thread'/>
<use f='ffmpeg/libavcodec/dnxhdenc.c' l='898' u='m' c='dnxhd_encode_thread'/>
<use f='ffmpeg/libavcodec/dnxhdenc.c' l='899' u='m' c='dnxhd_encode_thread'/>
<use f='ffmpeg/libavcodec/dnxhdenc.c' l='903' u='m' c='dnxhd_encode_thread'/>
<use f='ffmpeg/libavcodec/dnxhdenc.c' l='904' u='m' c='dnxhd_encode_thread'/>
<use f='ffmpeg/libavcodec/dnxhdenc.c' l='911' u='m' c='dnxhd_encode_thread'/>
<use f='ffmpeg/libavcodec/dnxhdenc.c' l='911' u='a' c='dnxhd_encode_thread'/>
<use f='ffmpeg/libavcodec/dnxhdenc.c' l='918' u='m' c='dnxhd_encode_thread'/>
<use f='ffmpeg/libavcodec/dnxhdenc.c' l='919' u='m' c='dnxhd_encode_thread'/>
<use f='ffmpeg/libavcodec/dnxhdenc.c' l='919' u='m' c='dnxhd_encode_thread'/>
<use f='ffmpeg/libavcodec/dnxhdenc.c' l='920' u='m' c='dnxhd_encode_thread'/>
<use f='ffmpeg/libavcodec/dnxhdenc.c' l='928' u='m' c='dnxhd_setup_threads_slices'/>
<use f='ffmpeg/libavcodec/dnxhdenc.c' l='932' u='m' c='dnxhd_setup_threads_slices'/>
<use f='ffmpeg/libavcodec/dnxhdenc.c' l='933' u='m' c='dnxhd_setup_threads_slices'/>
<use f='ffmpeg/libavcodec/dnxhdenc.c' l='948' u='m' c='dnxhd_mb_var_thread'/>
<use f='ffmpeg/libavcodec/dnxhdenc.c' l='953' u='m' c='dnxhd_mb_var_thread'/>
<use f='ffmpeg/libavcodec/dnxhdenc.c' l='954' u='m' c='dnxhd_mb_var_thread'/>
<use f='ffmpeg/libavcodec/dnxhdenc.c' l='955' u='m' c='dnxhd_mb_var_thread'/>
<use f='ffmpeg/libavcodec/dnxhdenc.c' l='960' u='m' c='dnxhd_mb_var_thread'/>
<use f='ffmpeg/libavcodec/dnxhdenc.c' l='960' u='m' c='dnxhd_mb_var_thread'/>
<use f='ffmpeg/libavcodec/dnxhdenc.c' l='961' u='m' c='dnxhd_mb_var_thread'/>
<use f='ffmpeg/libavcodec/dnxhdenc.c' l='961' u='m' c='dnxhd_mb_var_thread'/>
<use f='ffmpeg/libavcodec/dnxhdenc.c' l='968' u='m' c='dnxhd_mb_var_thread'/>
<use f='ffmpeg/libavcodec/dnxhdenc.c' l='980' u='m' c='dnxhd_mb_var_thread'/>
<use f='ffmpeg/libavcodec/dnxhdenc.c' l='981' u='m' c='dnxhd_mb_var_thread'/>
<use f='ffmpeg/libavcodec/dnxhdenc.c' l='984' u='m' c='dnxhd_mb_var_thread'/>
<use f='ffmpeg/libavcodec/dnxhdenc.c' l='1020' u='m' c='dnxhd_encode_rdo'/>
<use f='ffmpeg/libavcodec/dnxhdenc.c' l='1032' u='m' c='dnxhd_encode_rdo'/>
<use f='ffmpeg/libavcodec/dnxhdenc.c' l='1033' u='m' c='dnxhd_encode_rdo'/>
<use f='ffmpeg/libavcodec/dnxhdenc.c' l='1036' u='m' c='dnxhd_encode_rdo'/>
<use f='ffmpeg/libavcodec/dnxhdenc.c' l='1039' u='m' c='dnxhd_encode_rdo'/>
<use f='ffmpeg/libavcodec/dnxhdenc.c' l='1103' u='m' c='dnxhd_find_qscale'/>
<use f='ffmpeg/libavcodec/dnxhdenc.c' l='1103' u='m' c='dnxhd_find_qscale'/>
<use f='ffmpeg/libavcodec/dnxhdenc.c' l='1104' u='m' c='dnxhd_find_qscale'/>
<use f='ffmpeg/libavcodec/dnxhdenc.c' l='1105' u='m' c='dnxhd_find_qscale'/>
<use f='ffmpeg/libavcodec/dnxhdenc.c' l='1106' u='m' c='dnxhd_find_qscale'/>
<use f='ffmpeg/libavcodec/dnxhdenc.c' l='1107' u='m' c='dnxhd_find_qscale'/>
<use f='ffmpeg/libavcodec/dnxhdenc.c' l='1107' u='m' c='dnxhd_find_qscale'/>
<use f='ffmpeg/libavcodec/dnxhdenc.c' l='1136' u='m' c='dnxhd_find_qscale'/>
<use f='ffmpeg/libavcodec/dnxhdenc.c' l='1206' u='m' c='dnxhd_encode_fast'/>
<use f='ffmpeg/libavcodec/dnxhdenc.c' l='1207' u='m' c='dnxhd_encode_fast'/>
<use f='ffmpeg/libavcodec/dnxhdenc.c' l='1208' u='m' c='dnxhd_encode_fast'/>
<use f='ffmpeg/libavcodec/dnxhdenc.c' l='1209' u='m' c='dnxhd_encode_fast'/>
<use f='ffmpeg/libavcodec/dnxhdenc.c' l='1216' u='m' c='dnxhd_encode_fast'/>
<use f='ffmpeg/libavcodec/dnxhdenc.c' l='1220' u='m' c='dnxhd_encode_fast'/>
<use f='ffmpeg/libavcodec/dnxhdenc.c' l='1230' u='m' c='dnxhd_encode_fast'/>
<use f='ffmpeg/libavcodec/dnxhdenc.c' l='1231' u='m' c='dnxhd_encode_fast'/>
<use f='ffmpeg/libavcodec/dnxhdenc.c' l='1232' u='m' c='dnxhd_encode_fast'/>
<use f='ffmpeg/libavcodec/dnxhdenc.c' l='1234' u='m' c='dnxhd_encode_fast'/>
<use f='ffmpeg/libavcodec/dnxhdenc.c' l='1236' u='m' c='dnxhd_encode_fast'/>
<use f='ffmpeg/libavcodec/dnxhdenc.c' l='1238' u='m' c='dnxhd_encode_fast'/>
<use f='ffmpeg/libavcodec/dnxhdenc.c' l='1248' u='m' c='dnxhd_load_picture'/>
<use f='ffmpeg/libavcodec/dnxhdenc.c' l='1249' u='m' c='dnxhd_load_picture'/>
<use f='ffmpeg/libavcodec/dnxhdenc.c' l='1250' u='m' c='dnxhd_load_picture'/>
<use f='ffmpeg/libavcodec/dnxhdenc.c' l='1251' u='m' c='dnxhd_load_picture'/>
<use f='ffmpeg/libavcodec/dnxhdenc.c' l='1252' u='m' c='dnxhd_load_picture'/>
<use f='ffmpeg/libavcodec/dnxhdenc.c' l='1257' u='m' c='dnxhd_load_picture'/>
<use f='ffmpeg/libavcodec/dnxhdenc.c' l='1299' u='m' c='dnxhd_encode_picture'/>
<use f='ffmpeg/libavcodec/dnxhdenc.c' l='1305' u='m' c='dnxhd_encode_picture'/>
<offset>320</offset>
<doc f='ffmpeg/libavcodec/dnxhdenc.h' l='49'>///&lt; Used for quantization dsp functions</doc>
