<dec f='ffmpeg/libavcodec/error_resilience.h' l='42' type='AVFrame *'/>
<offset>0</offset>
<use f='ffmpeg/libavcodec/error_resilience.c' l='62' u='r' c='put_dc'/>
<use f='ffmpeg/libavcodec/error_resilience.c' l='402' u='r' c='guess_mv'/>
<use f='ffmpeg/libavcodec/error_resilience.c' l='402' u='r' c='guess_mv'/>
<use f='ffmpeg/libavcodec/error_resilience.c' l='403' u='r' c='guess_mv'/>
<use f='ffmpeg/libavcodec/error_resilience.c' l='403' u='r' c='guess_mv'/>
<use f='ffmpeg/libavcodec/error_resilience.c' l='404' u='r' c='guess_mv'/>
<use f='ffmpeg/libavcodec/error_resilience.c' l='404' u='r' c='guess_mv'/>
<use f='ffmpeg/libavcodec/error_resilience.c' l='405' u='r' c='guess_mv'/>
<use f='ffmpeg/libavcodec/error_resilience.c' l='405' u='r' c='guess_mv'/>
<use f='ffmpeg/libavcodec/error_resilience.c' l='429' u='r' c='guess_mv'/>
<use f='ffmpeg/libavcodec/error_resilience.c' l='444' u='r' c='guess_mv'/>
<use f='ffmpeg/libavcodec/error_resilience.c' l='444' u='r' c='guess_mv'/>
<use f='ffmpeg/libavcodec/error_resilience.c' l='626' u='r' c='guess_mv'/>
<use f='ffmpeg/libavcodec/error_resilience.c' l='628' u='r' c='guess_mv'/>
<use f='ffmpeg/libavcodec/error_resilience.c' l='726' u='r' c='is_intra_more_likely'/>
<use f='ffmpeg/libavcodec/error_resilience.c' l='726' u='r' c='is_intra_more_likely'/>
<use f='ffmpeg/libavcodec/error_resilience.c' l='746' u='r' c='is_intra_more_likely'/>
<use f='ffmpeg/libavcodec/error_resilience.c' l='767' u='r' c='is_intra_more_likely'/>
<use f='ffmpeg/libavcodec/error_resilience.c' l='768' u='r' c='is_intra_more_likely'/>
<use f='ffmpeg/libavcodec/error_resilience.c' l='769' u='r' c='is_intra_more_likely'/>
<use f='ffmpeg/libavcodec/error_resilience.c' l='771' u='r' c='is_intra_more_likely'/>
<use f='ffmpeg/libavcodec/error_resilience.c' l='816' u='r' c='er_supported'/>
<use f='ffmpeg/libavcodec/error_resilience.c' l='919' u='r' c='ff_er_frame_end'/>
<use f='ffmpeg/libavcodec/error_resilience.c' l='935' u='r' c='ff_er_frame_end'/>
<use f='ffmpeg/libavcodec/error_resilience.c' l='936' u='r' c='ff_er_frame_end'/>
<use f='ffmpeg/libavcodec/error_resilience.c' l='936' u='r' c='ff_er_frame_end'/>
<use f='ffmpeg/libavcodec/error_resilience.c' l='937' u='r' c='ff_er_frame_end'/>
<use f='ffmpeg/libavcodec/error_resilience.c' l='937' u='r' c='ff_er_frame_end'/>
<use f='ffmpeg/libavcodec/error_resilience.c' l='938' u='r' c='ff_er_frame_end'/>
<use f='ffmpeg/libavcodec/error_resilience.c' l='938' u='r' c='ff_er_frame_end'/>
<use f='ffmpeg/libavcodec/error_resilience.c' l='943' u='r' c='ff_er_frame_end'/>
<use f='ffmpeg/libavcodec/error_resilience.c' l='944' u='r' c='ff_er_frame_end'/>
<use f='ffmpeg/libavcodec/error_resilience.c' l='944' u='r' c='ff_er_frame_end'/>
<use f='ffmpeg/libavcodec/error_resilience.c' l='945' u='r' c='ff_er_frame_end'/>
<use f='ffmpeg/libavcodec/error_resilience.c' l='945' u='r' c='ff_er_frame_end'/>
<use f='ffmpeg/libavcodec/error_resilience.c' l='946' u='r' c='ff_er_frame_end'/>
<use f='ffmpeg/libavcodec/error_resilience.c' l='946' u='r' c='ff_er_frame_end'/>
<use f='ffmpeg/libavcodec/error_resilience.c' l='1122' u='r' c='ff_er_frame_end'/>
<use f='ffmpeg/libavcodec/error_resilience.c' l='1124' u='r' c='ff_er_frame_end'/>
<use f='ffmpeg/libavcodec/error_resilience.c' l='1142' u='r' c='ff_er_frame_end'/>
<use f='ffmpeg/libavcodec/error_resilience.c' l='1142' u='r' c='ff_er_frame_end'/>
<use f='ffmpeg/libavcodec/error_resilience.c' l='1143' u='r' c='ff_er_frame_end'/>
<use f='ffmpeg/libavcodec/error_resilience.c' l='1143' u='r' c='ff_er_frame_end'/>
<use f='ffmpeg/libavcodec/error_resilience.c' l='1155' u='r' c='ff_er_frame_end'/>
<use f='ffmpeg/libavcodec/error_resilience.c' l='1155' u='r' c='ff_er_frame_end'/>
<use f='ffmpeg/libavcodec/error_resilience.c' l='1188' u='r' c='ff_er_frame_end'/>
<use f='ffmpeg/libavcodec/error_resilience.c' l='1205' u='r' c='ff_er_frame_end'/>
<use f='ffmpeg/libavcodec/error_resilience.c' l='1205' u='r' c='ff_er_frame_end'/>
<use f='ffmpeg/libavcodec/error_resilience.c' l='1207' u='r' c='ff_er_frame_end'/>
<use f='ffmpeg/libavcodec/error_resilience.c' l='1207' u='r' c='ff_er_frame_end'/>
<use f='ffmpeg/libavcodec/error_resilience.c' l='1254' u='r' c='ff_er_frame_end'/>
<use f='ffmpeg/libavcodec/error_resilience.c' l='1255' u='r' c='ff_er_frame_end'/>
<use f='ffmpeg/libavcodec/error_resilience.c' l='1256' u='r' c='ff_er_frame_end'/>
<use f='ffmpeg/libavcodec/error_resilience.c' l='1270' u='r' c='ff_er_frame_end'/>
<use f='ffmpeg/libavcodec/error_resilience.c' l='1310' u='r' c='ff_er_frame_end'/>
<use f='ffmpeg/libavcodec/error_resilience.c' l='1311' u='r' c='ff_er_frame_end'/>
<use f='ffmpeg/libavcodec/error_resilience.c' l='1312' u='r' c='ff_er_frame_end'/>
<use f='ffmpeg/libavcodec/error_resilience.c' l='1313' u='r' c='ff_er_frame_end'/>
<use f='ffmpeg/libavcodec/error_resilience.c' l='1323' u='r' c='ff_er_frame_end'/>
<use f='ffmpeg/libavcodec/error_resilience.c' l='1327' u='r' c='ff_er_frame_end'/>
<use f='ffmpeg/libavcodec/error_resilience.c' l='1330' u='r' c='ff_er_frame_end'/>
<use f='ffmpeg/libavcodec/error_resilience.c' l='1331' u='r' c='ff_er_frame_end'/>
<use f='ffmpeg/libavcodec/error_resilience.c' l='1333' u='r' c='ff_er_frame_end'/>
<use f='ffmpeg/libavcodec/error_resilience.c' l='1335' u='r' c='ff_er_frame_end'/>
<use f='ffmpeg/libavcodec/error_resilience.c' l='1337' u='r' c='ff_er_frame_end'/>
<use f='ffmpeg/libavcodec/error_resilience.c' l='1348' u='r' c='ff_er_frame_end'/>
<use f='ffmpeg/libavcodec/h264_picture.c' l='146' u='w' c='ff_h264_set_erpic'/>
<use f='ffmpeg/libavcodec/mpeg_er.c' l='29' u='w' c='set_erpic'/>
<use f='ffmpeg/libavcodec/mpeg_er.c' l='34' u='w' c='set_erpic'/>
