<dec f='ffmpeg/libavcodec/ffv1.h' l='81' type='RangeCoder'/>
<use f='ffmpeg/libavcodec/ffv1.c' l='97' u='m' c='ff_ffv1_init_slice_state'/>
<use f='ffmpeg/libavcodec/ffv1.c' l='98' u='m' c='ff_ffv1_init_slice_state'/>
<use f='ffmpeg/libavcodec/ffv1.c' l='98' u='m' c='ff_ffv1_init_slice_state'/>
<offset>128</offset>
<use f='ffmpeg/libavcodec/ffv1dec.c' l='98' u='a' c='is_input_end'/>
<use f='ffmpeg/libavcodec/ffv1dec_template.c' l='28' u='a' c='decode_line'/>
<use f='ffmpeg/libavcodec/ffv1dec_template.c' l='28' u='a' c='decode_line32'/>
<use f='ffmpeg/libavcodec/ffv1dec.c' l='166' u='a' c='decode_slice_header'/>
<use f='ffmpeg/libavcodec/ffv1dec.c' l='311' u='a' c='decode_slice'/>
<use f='ffmpeg/libavcodec/ffv1dec.c' l='312' u='m' c='decode_slice'/>
<use f='ffmpeg/libavcodec/ffv1dec.c' l='312' u='m' c='decode_slice'/>
<use f='ffmpeg/libavcodec/ffv1dec.c' l='314' u='m' c='decode_slice'/>
<use f='ffmpeg/libavcodec/ffv1dec.c' l='315' u='m' c='decode_slice'/>
<use f='ffmpeg/libavcodec/ffv1dec.c' l='315' u='m' c='decode_slice'/>
<use f='ffmpeg/libavcodec/ffv1dec.c' l='350' u='a' c='decode_slice'/>
<use f='ffmpeg/libavcodec/ffv1dec.c' l='351' u='m' c='decode_slice'/>
<use f='ffmpeg/libavcodec/ffv1dec.c' l='351' u='m' c='decode_slice'/>
<use f='ffmpeg/libavcodec/ffv1dec.c' l='412' u='a' c='read_extra_header'/>
<use f='ffmpeg/libavcodec/ffv1dec.c' l='531' u='a' c='read_header'/>
<use f='ffmpeg/libavcodec/ffv1dec.c' l='837' u='a' c='decode_frame'/>
<use f='ffmpeg/libavcodec/ffv1dec.c' l='922' u='a' c='decode_frame'/>
<use f='ffmpeg/libavcodec/ffv1dec.c' l='924' u='m' c='decode_frame'/>
<use f='ffmpeg/libavcodec/ffv1enc_template.c' l='28' u='a' c='encode_line'/>
<use f='ffmpeg/libavcodec/ffv1enc_template.c' l='28' u='a' c='encode_line32'/>
<use f='ffmpeg/libavcodec/ffv1enc.c' l='350' u='a' c='write_header'/>
<use f='ffmpeg/libavcodec/ffv1enc.c' l='395' u='a' c='write_extradata'/>
<use f='ffmpeg/libavcodec/ffv1enc.c' l='929' u='a' c='encode_slice_header'/>
<use f='ffmpeg/libavcodec/ffv1enc.c' l='1053' u='r' c='encode_slice'/>
<use f='ffmpeg/libavcodec/ffv1enc.c' l='1074' u='a' c='encode_slice'/>
<use f='ffmpeg/libavcodec/ffv1enc.c' l='1076' u='m' c='encode_slice'/>
<use f='ffmpeg/libavcodec/ffv1enc.c' l='1077' u='m' c='encode_slice'/>
<use f='ffmpeg/libavcodec/ffv1enc.c' l='1077' u='m' c='encode_slice'/>
<use f='ffmpeg/libavcodec/ffv1enc.c' l='1112' u='w' c='encode_slice'/>
<use f='ffmpeg/libavcodec/ffv1enc.c' l='1123' u='a' c='encode_frame'/>
<use f='ffmpeg/libavcodec/ffv1enc.c' l='1223' u='a' c='encode_frame'/>
<use f='ffmpeg/libavcodec/ffv1enc.c' l='1225' u='m' c='encode_frame'/>
<use f='ffmpeg/libavcodec/ffv1enc.c' l='1225' u='m' c='encode_frame'/>
<use f='ffmpeg/libavcodec/ffv1enc.c' l='1226' u='m' c='encode_frame'/>
<use f='ffmpeg/libavcodec/ffv1enc.c' l='1226' u='m' c='encode_frame'/>
<use f='ffmpeg/libavcodec/ffv1enc.c' l='1227' u='m' c='encode_frame'/>
<use f='ffmpeg/libavcodec/ffv1enc.c' l='1227' u='m' c='encode_frame'/>
<use f='ffmpeg/libavcodec/ffv1enc.c' l='1239' u='a' c='encode_frame'/>
<use f='ffmpeg/libavcodec/ffv1enc.c' l='1246' u='m' c='encode_frame'/>
