<dec f='ffmpeg/libavcodec/hevcdec.h' l='456' type='PredictionUnit'/>
<use f='ffmpeg/libavcodec/hevc_cabac.c' l='1553' u='m' c='ff_hevc_hls_mvd_coding'/>
<use f='ffmpeg/libavcodec/hevc_cabac.c' l='1554' u='m' c='ff_hevc_hls_mvd_coding'/>
<use f='ffmpeg/libavcodec/hevc_cabac.c' l='1555' u='m' c='ff_hevc_hls_mvd_coding'/>
<use f='ffmpeg/libavcodec/hevc_cabac.c' l='1559' u='m' c='ff_hevc_hls_mvd_coding'/>
<use f='ffmpeg/libavcodec/hevc_cabac.c' l='1560' u='m' c='ff_hevc_hls_mvd_coding'/>
<use f='ffmpeg/libavcodec/hevc_cabac.c' l='1561' u='m' c='ff_hevc_hls_mvd_coding'/>
<offset>250048</offset>
<use f='ffmpeg/libavcodec/hevcdec.c' l='1319' u='m' c='hls_transform_tree'/>
<use f='ffmpeg/libavcodec/hevcdec.c' l='1321' u='m' c='hls_transform_tree'/>
<use f='ffmpeg/libavcodec/hevcdec.c' l='1322' u='m' c='hls_transform_tree'/>
<use f='ffmpeg/libavcodec/hevcdec.c' l='1324' u='m' c='hls_transform_tree'/>
<use f='ffmpeg/libavcodec/hevcdec.c' l='1325' u='m' c='hls_transform_tree'/>
<use f='ffmpeg/libavcodec/hevcdec.c' l='1329' u='m' c='hls_transform_tree'/>
<use f='ffmpeg/libavcodec/hevcdec.c' l='1330' u='m' c='hls_transform_tree'/>
<use f='ffmpeg/libavcodec/hevcdec.c' l='1331' u='m' c='hls_transform_tree'/>
<use f='ffmpeg/libavcodec/hevcdec.c' l='1819' u='m' c='hevc_luma_mv_mvp_mode'/>
<use f='ffmpeg/libavcodec/hevcdec.c' l='1820' u='m' c='hevc_luma_mv_mvp_mode'/>
<use f='ffmpeg/libavcodec/hevcdec.c' l='1828' u='m' c='hevc_luma_mv_mvp_mode'/>
<use f='ffmpeg/libavcodec/hevcdec.c' l='1837' u='m' c='hevc_luma_mv_mvp_mode'/>
<use f='ffmpeg/libavcodec/hevcdec.c' l='1838' u='m' c='hevc_luma_mv_mvp_mode'/>
<use f='ffmpeg/libavcodec/hevcdec.c' l='1871' u='m' c='hls_prediction_unit'/>
<use f='ffmpeg/libavcodec/hevcdec.c' l='1873' u='m' c='hls_prediction_unit'/>
<use f='ffmpeg/libavcodec/hevcdec.c' l='2018' u='m' c='luma_intra_pred_mode'/>
<use f='ffmpeg/libavcodec/hevcdec.c' l='2027' u='m' c='luma_intra_pred_mode'/>
<use f='ffmpeg/libavcodec/hevcdec.c' l='2084' u='m' c='intra_prediction_unit'/>
<use f='ffmpeg/libavcodec/hevcdec.c' l='2086' u='m' c='intra_prediction_unit'/>
<use f='ffmpeg/libavcodec/hevcdec.c' l='2088' u='m' c='intra_prediction_unit'/>
<use f='ffmpeg/libavcodec/hevcdec.c' l='2097' u='m' c='intra_prediction_unit'/>
<use f='ffmpeg/libavcodec/hevcdec.c' l='2099' u='m' c='intra_prediction_unit'/>
<use f='ffmpeg/libavcodec/hevcdec.c' l='2100' u='m' c='intra_prediction_unit'/>
<use f='ffmpeg/libavcodec/hevcdec.c' l='2102' u='m' c='intra_prediction_unit'/>
<use f='ffmpeg/libavcodec/hevcdec.c' l='2104' u='m' c='intra_prediction_unit'/>
<use f='ffmpeg/libavcodec/hevcdec.c' l='2104' u='m' c='intra_prediction_unit'/>
<use f='ffmpeg/libavcodec/hevcdec.c' l='2110' u='m' c='intra_prediction_unit'/>
<use f='ffmpeg/libavcodec/hevcdec.c' l='2112' u='m' c='intra_prediction_unit'/>
<use f='ffmpeg/libavcodec/hevcdec.c' l='2117' u='m' c='intra_prediction_unit'/>
<use f='ffmpeg/libavcodec/hevcdec.c' l='2119' u='m' c='intra_prediction_unit'/>
<use f='ffmpeg/libavcodec/hevcdec.c' l='2123' u='m' c='intra_prediction_unit'/>
<use f='ffmpeg/libavcodec/hevcdec.c' l='2124' u='m' c='intra_prediction_unit'/>
<use f='ffmpeg/libavcodec/hevcdec.c' l='2126' u='m' c='intra_prediction_unit'/>
<use f='ffmpeg/libavcodec/hevcdec.c' l='2128' u='m' c='intra_prediction_unit'/>
<use f='ffmpeg/libavcodec/hevcdec.c' l='2128' u='m' c='intra_prediction_unit'/>
<use f='ffmpeg/libavcodec/hevcdec.c' l='2177' u='m' c='hls_coding_unit'/>
<use f='ffmpeg/libavcodec/hevcdec.c' l='2280' u='m' c='hls_coding_unit'/>
