<dec f='ffmpeg/libavcodec/hevcdec.h' l='433' type='CABACContext'/>
<use f='ffmpeg/libavcodec/hevc_cabac.c' l='474' u='a' c='cabac_reinit'/>
<use f='ffmpeg/libavcodec/hevc_cabac.c' l='482' u='a' c='cabac_init_decoder'/>
<use f='ffmpeg/libavcodec/hevc_cabac.c' l='547' u='a' c='ff_hevc_cabac_init'/>
<use f='ffmpeg/libavcodec/hevc_cabac.c' l='566' u='a' c='ff_hevc_sao_merge_flag_decode'/>
<use f='ffmpeg/libavcodec/hevc_cabac.c' l='566' u='a' c='ff_hevc_sao_type_idx_decode'/>
<use f='ffmpeg/libavcodec/hevc_cabac.c' l='578' u='a' c='ff_hevc_sao_type_idx_decode'/>
<use f='ffmpeg/libavcodec/hevc_cabac.c' l='586' u='a' c='ff_hevc_sao_band_position_decode'/>
<use f='ffmpeg/libavcodec/hevc_cabac.c' l='589' u='a' c='ff_hevc_sao_band_position_decode'/>
<use f='ffmpeg/libavcodec/hevc_cabac.c' l='598' u='a' c='ff_hevc_sao_offset_abs_decode'/>
<use f='ffmpeg/libavcodec/hevc_cabac.c' l='605' u='a' c='ff_hevc_sao_offset_sign_decode'/>
<use f='ffmpeg/libavcodec/hevc_cabac.c' l='610' u='a' c='ff_hevc_sao_eo_class_decode'/>
<use f='ffmpeg/libavcodec/hevc_cabac.c' l='611' u='a' c='ff_hevc_sao_eo_class_decode'/>
<use f='ffmpeg/libavcodec/hevc_cabac.c' l='617' u='a' c='ff_hevc_end_of_slice_flag_decode'/>
<use f='ffmpeg/libavcodec/hevc_cabac.c' l='566' u='a' c='ff_hevc_cu_transquant_bypass_flag_decode'/>
<use f='ffmpeg/libavcodec/hevc_cabac.c' l='566' u='a' c='ff_hevc_skip_flag_decode'/>
<use f='ffmpeg/libavcodec/hevc_cabac.c' l='566' u='a' c='ff_hevc_cu_qp_delta_abs'/>
<use f='ffmpeg/libavcodec/hevc_cabac.c' l='652' u='a' c='ff_hevc_cu_qp_delta_abs'/>
<use f='ffmpeg/libavcodec/hevc_cabac.c' l='662' u='a' c='ff_hevc_cu_qp_delta_abs'/>
<use f='ffmpeg/libavcodec/hevc_cabac.c' l='669' u='a' c='ff_hevc_cu_qp_delta_sign_flag'/>
<use f='ffmpeg/libavcodec/hevc_cabac.c' l='566' u='a' c='ff_hevc_cu_chroma_qp_offset_flag'/>
<use f='ffmpeg/libavcodec/hevc_cabac.c' l='566' u='a' c='ff_hevc_cu_chroma_qp_offset_idx'/>
<use f='ffmpeg/libavcodec/hevc_cabac.c' l='566' u='a' c='ff_hevc_pred_mode_decode'/>
<use f='ffmpeg/libavcodec/hevc_cabac.c' l='566' u='a' c='ff_hevc_split_coding_unit_flag_decode'/>
<use f='ffmpeg/libavcodec/hevc_cabac.c' l='566' u='a' c='ff_hevc_part_mode_decode'/>
<use f='ffmpeg/libavcodec/hevc_cabac.c' l='566' u='a' c='ff_hevc_part_mode_decode'/>
<use f='ffmpeg/libavcodec/hevc_cabac.c' l='566' u='a' c='ff_hevc_part_mode_decode'/>
<use f='ffmpeg/libavcodec/hevc_cabac.c' l='566' u='a' c='ff_hevc_part_mode_decode'/>
<use f='ffmpeg/libavcodec/hevc_cabac.c' l='566' u='a' c='ff_hevc_part_mode_decode'/>
<use f='ffmpeg/libavcodec/hevc_cabac.c' l='566' u='a' c='ff_hevc_part_mode_decode'/>
<use f='ffmpeg/libavcodec/hevc_cabac.c' l='737' u='a' c='ff_hevc_part_mode_decode'/>
<use f='ffmpeg/libavcodec/hevc_cabac.c' l='566' u='a' c='ff_hevc_part_mode_decode'/>
<use f='ffmpeg/libavcodec/hevc_cabac.c' l='744' u='a' c='ff_hevc_part_mode_decode'/>
<use f='ffmpeg/libavcodec/hevc_cabac.c' l='751' u='a' c='ff_hevc_pcm_flag_decode'/>
<use f='ffmpeg/libavcodec/hevc_cabac.c' l='566' u='a' c='ff_hevc_prev_intra_luma_pred_flag_decode'/>
<use f='ffmpeg/libavcodec/hevc_cabac.c' l='762' u='a' c='ff_hevc_mpm_idx_decode'/>
<use f='ffmpeg/libavcodec/hevc_cabac.c' l='770' u='a' c='ff_hevc_rem_intra_luma_pred_mode_decode'/>
<use f='ffmpeg/libavcodec/hevc_cabac.c' l='773' u='a' c='ff_hevc_rem_intra_luma_pred_mode_decode'/>
<use f='ffmpeg/libavcodec/hevc_cabac.c' l='566' u='a' c='ff_hevc_intra_chroma_pred_mode_decode'/>
<use f='ffmpeg/libavcodec/hevc_cabac.c' l='783' u='a' c='ff_hevc_intra_chroma_pred_mode_decode'/>
<use f='ffmpeg/libavcodec/hevc_cabac.c' l='784' u='a' c='ff_hevc_intra_chroma_pred_mode_decode'/>
<use f='ffmpeg/libavcodec/hevc_cabac.c' l='566' u='a' c='ff_hevc_merge_idx_decode'/>
<use f='ffmpeg/libavcodec/hevc_cabac.c' l='793' u='a' c='ff_hevc_merge_idx_decode'/>
<use f='ffmpeg/libavcodec/hevc_cabac.c' l='566' u='a' c='ff_hevc_merge_flag_decode'/>
<use f='ffmpeg/libavcodec/hevc_cabac.c' l='566' u='a' c='ff_hevc_inter_pred_idc_decode'/>
<use f='ffmpeg/libavcodec/hevc_cabac.c' l='566' u='a' c='ff_hevc_inter_pred_idc_decode'/>
<use f='ffmpeg/libavcodec/hevc_cabac.c' l='566' u='a' c='ff_hevc_inter_pred_idc_decode'/>
<use f='ffmpeg/libavcodec/hevc_cabac.c' l='566' u='a' c='ff_hevc_ref_idx_lx_decode'/>
<use f='ffmpeg/libavcodec/hevc_cabac.c' l='823' u='a' c='ff_hevc_ref_idx_lx_decode'/>
<use f='ffmpeg/libavcodec/hevc_cabac.c' l='566' u='a' c='ff_hevc_mvp_lx_flag_decode'/>
<use f='ffmpeg/libavcodec/hevc_cabac.c' l='566' u='a' c='ff_hevc_no_residual_syntax_flag_decode'/>
<use f='ffmpeg/libavcodec/hevc_cabac.c' l='566' u='a' c='abs_mvd_greater0_flag_decode'/>
<use f='ffmpeg/libavcodec/hevc_cabac.c' l='566' u='a' c='abs_mvd_greater1_flag_decode'/>
<use f='ffmpeg/libavcodec/hevc_cabac.c' l='855' u='a' c='mvd_decode'/>
<use f='ffmpeg/libavcodec/hevc_cabac.c' l='864' u='a' c='mvd_decode'/>
<use f='ffmpeg/libavcodec/hevc_cabac.c' l='865' u='a' c='mvd_decode'/>
<use f='ffmpeg/libavcodec/hevc_cabac.c' l='870' u='a' c='mvd_sign_flag_decode'/>
<use f='ffmpeg/libavcodec/hevc_cabac.c' l='566' u='a' c='ff_hevc_split_transform_flag_decode'/>
<use f='ffmpeg/libavcodec/hevc_cabac.c' l='566' u='a' c='ff_hevc_cbf_cb_cr_decode'/>
<use f='ffmpeg/libavcodec/hevc_cabac.c' l='566' u='a' c='ff_hevc_cbf_luma_decode'/>
<use f='ffmpeg/libavcodec/hevc_cabac.c' l='566' u='a' c='hevc_transform_skip_flag_decode'/>
<use f='ffmpeg/libavcodec/hevc_cabac.c' l='566' u='a' c='explicit_rdpcm_flag_decode'/>
<use f='ffmpeg/libavcodec/hevc_cabac.c' l='566' u='a' c='explicit_rdpcm_dir_flag_decode'/>
<use f='ffmpeg/libavcodec/hevc_cabac.c' l='566' u='a' c='ff_hevc_log2_res_scale_abs'/>
<use f='ffmpeg/libavcodec/hevc_cabac.c' l='566' u='a' c='ff_hevc_res_scale_sign_flag'/>
<use f='ffmpeg/libavcodec/hevc_cabac.c' l='566' u='a' c='last_significant_coeff_xy_prefix_decode'/>
<use f='ffmpeg/libavcodec/hevc_cabac.c' l='566' u='a' c='last_significant_coeff_xy_prefix_decode'/>
<use f='ffmpeg/libavcodec/hevc_cabac.c' l='947' u='a' c='last_significant_coeff_suffix_decode'/>
<use f='ffmpeg/libavcodec/hevc_cabac.c' l='950' u='a' c='last_significant_coeff_suffix_decode'/>
<use f='ffmpeg/libavcodec/hevc_cabac.c' l='566' u='a' c='significant_coeff_group_flag_decode'/>
<use f='ffmpeg/libavcodec/hevc_cabac.c' l='566' u='a' c='significant_coeff_flag_decode'/>
<use f='ffmpeg/libavcodec/hevc_cabac.c' l='566' u='a' c='significant_coeff_flag_decode_0'/>
<use f='ffmpeg/libavcodec/hevc_cabac.c' l='566' u='a' c='coeff_abs_level_greater1_flag_decode'/>
<use f='ffmpeg/libavcodec/hevc_cabac.c' l='566' u='a' c='coeff_abs_level_greater2_flag_decode'/>
<use f='ffmpeg/libavcodec/hevc_cabac.c' l='998' u='a' c='coeff_abs_level_remaining_decode'/>
<use f='ffmpeg/libavcodec/hevc_cabac.c' l='1003' u='a' c='coeff_abs_level_remaining_decode'/>
<use f='ffmpeg/libavcodec/hevc_cabac.c' l='1014' u='a' c='coeff_abs_level_remaining_decode'/>
<use f='ffmpeg/libavcodec/hevc_cabac.c' l='1027' u='a' c='coeff_sign_flag_decode'/>
<offset>1920</offset>
<use f='ffmpeg/libavcodec/hevcdec.c' l='1439' u='a' c='hls_pcm_sample'/>
<use f='ffmpeg/libavcodec/hevcdec.c' l='2545' u='a' c='hls_decode_entry_wpp'/>
