<dec f='ffmpeg/libavcodec/hevcdec.h' l='455' type='CodingUnit'/>
<use f='ffmpeg/libavcodec/hevc_cabac.c' l='717' u='m' c='ff_hevc_part_mode_decode'/>
<use f='ffmpeg/libavcodec/hevc_cabac.c' l='1076' u='m' c='ff_hevc_hls_residual_coding'/>
<use f='ffmpeg/libavcodec/hevc_cabac.c' l='1137' u='m' c='ff_hevc_hls_residual_coding'/>
<use f='ffmpeg/libavcodec/hevc_cabac.c' l='1152' u='m' c='ff_hevc_hls_residual_coding'/>
<use f='ffmpeg/libavcodec/hevc_cabac.c' l='1153' u='m' c='ff_hevc_hls_residual_coding'/>
<use f='ffmpeg/libavcodec/hevc_cabac.c' l='1284' u='m' c='ff_hevc_hls_residual_coding'/>
<use f='ffmpeg/libavcodec/hevc_cabac.c' l='1325' u='m' c='ff_hevc_hls_residual_coding'/>
<use f='ffmpeg/libavcodec/hevc_cabac.c' l='1370' u='m' c='ff_hevc_hls_residual_coding'/>
<use f='ffmpeg/libavcodec/hevc_cabac.c' l='1396' u='m' c='ff_hevc_hls_residual_coding'/>
<use f='ffmpeg/libavcodec/hevc_cabac.c' l='1397' u='m' c='ff_hevc_hls_residual_coding'/>
<use f='ffmpeg/libavcodec/hevc_cabac.c' l='1459' u='m' c='ff_hevc_hls_residual_coding'/>
<use f='ffmpeg/libavcodec/hevc_cabac.c' l='1487' u='m' c='ff_hevc_hls_residual_coding'/>
<use f='ffmpeg/libavcodec/hevc_cabac.c' l='1498' u='m' c='ff_hevc_hls_residual_coding'/>
<use f='ffmpeg/libavcodec/hevc_cabac.c' l='1507' u='m' c='ff_hevc_hls_residual_coding'/>
<use f='ffmpeg/libavcodec/hevc_cabac.c' l='1513' u='m' c='ff_hevc_hls_residual_coding'/>
<offset>249888</offset>
<use f='ffmpeg/libavcodec/hevc_mvs.c' l='335' u='m' c='derive_spatial_merge_candidates'/>
<use f='ffmpeg/libavcodec/hevc_mvs.c' l='336' u='m' c='derive_spatial_merge_candidates'/>
<use f='ffmpeg/libavcodec/hevc_mvs.c' l='337' u='m' c='derive_spatial_merge_candidates'/>
<use f='ffmpeg/libavcodec/hevc_mvs.c' l='351' u='m' c='derive_spatial_merge_candidates'/>
<use f='ffmpeg/libavcodec/hevc_mvs.c' l='352' u='m' c='derive_spatial_merge_candidates'/>
<use f='ffmpeg/libavcodec/hevc_mvs.c' l='353' u='m' c='derive_spatial_merge_candidates'/>
<use f='ffmpeg/libavcodec/hevc_mvs.c' l='492' u='m' c='ff_hevc_luma_mv_merge_mode'/>
<use f='ffmpeg/libavcodec/hevc_mvs.c' l='493' u='m' c='ff_hevc_luma_mv_merge_mode'/>
<use f='ffmpeg/libavcodec/hevcdec.c' l='1088' u='m' c='hls_transform_unit'/>
<use f='ffmpeg/libavcodec/hevcdec.c' l='1125' u='m' c='hls_transform_unit'/>
<use f='ffmpeg/libavcodec/hevcdec.c' l='1143' u='m' c='hls_transform_unit'/>
<use f='ffmpeg/libavcodec/hevcdec.c' l='1169' u='m' c='hls_transform_unit'/>
<use f='ffmpeg/libavcodec/hevcdec.c' l='1176' u='m' c='hls_transform_unit'/>
<use f='ffmpeg/libavcodec/hevcdec.c' l='1205' u='m' c='hls_transform_unit'/>
<use f='ffmpeg/libavcodec/hevcdec.c' l='1233' u='m' c='hls_transform_unit'/>
<use f='ffmpeg/libavcodec/hevcdec.c' l='1243' u='m' c='hls_transform_unit'/>
<use f='ffmpeg/libavcodec/hevcdec.c' l='1253' u='m' c='hls_transform_unit'/>
<use f='ffmpeg/libavcodec/hevcdec.c' l='1317' u='m' c='hls_transform_tree'/>
<use f='ffmpeg/libavcodec/hevcdec.c' l='1336' u='m' c='hls_transform_tree'/>
<use f='ffmpeg/libavcodec/hevcdec.c' l='1337' u='m' c='hls_transform_tree'/>
<use f='ffmpeg/libavcodec/hevcdec.c' l='1341' u='m' c='hls_transform_tree'/>
<use f='ffmpeg/libavcodec/hevcdec.c' l='1342' u='m' c='hls_transform_tree'/>
<use f='ffmpeg/libavcodec/hevcdec.c' l='1346' u='m' c='hls_transform_tree'/>
<use f='ffmpeg/libavcodec/hevcdec.c' l='1392' u='m' c='hls_transform_tree'/>
<use f='ffmpeg/libavcodec/hevcdec.c' l='1416' u='m' c='hls_transform_tree'/>
<use f='ffmpeg/libavcodec/hevcdec.c' l='2071' u='m' c='intra_prediction_unit'/>
<use f='ffmpeg/libavcodec/hevcdec.c' l='2150' u='m' c='intra_prediction_unit_default_value'/>
<use f='ffmpeg/libavcodec/hevcdec.c' l='2169' u='m' c='hls_coding_unit'/>
<use f='ffmpeg/libavcodec/hevcdec.c' l='2170' u='m' c='hls_coding_unit'/>
<use f='ffmpeg/libavcodec/hevcdec.c' l='2171' u='m' c='hls_coding_unit'/>
<use f='ffmpeg/libavcodec/hevcdec.c' l='2172' u='m' c='hls_coding_unit'/>
<use f='ffmpeg/libavcodec/hevcdec.c' l='2173' u='m' c='hls_coding_unit'/>
<use f='ffmpeg/libavcodec/hevcdec.c' l='2179' u='m' c='hls_coding_unit'/>
<use f='ffmpeg/libavcodec/hevcdec.c' l='2180' u='m' c='hls_coding_unit'/>
<use f='ffmpeg/libavcodec/hevcdec.c' l='2183' u='m' c='hls_coding_unit'/>
<use f='ffmpeg/libavcodec/hevcdec.c' l='2193' u='m' c='hls_coding_unit'/>
<use f='ffmpeg/libavcodec/hevcdec.c' l='2212' u='m' c='hls_coding_unit'/>
<use f='ffmpeg/libavcodec/hevcdec.c' l='2213' u='m' c='hls_coding_unit'/>
<use f='ffmpeg/libavcodec/hevcdec.c' l='2215' u='m' c='hls_coding_unit'/>
<use f='ffmpeg/libavcodec/hevcdec.c' l='2216' u='m' c='hls_coding_unit'/>
<use f='ffmpeg/libavcodec/hevcdec.c' l='2216' u='m' c='hls_coding_unit'/>
<use f='ffmpeg/libavcodec/hevcdec.c' l='2217' u='m' c='hls_coding_unit'/>
<use f='ffmpeg/libavcodec/hevcdec.c' l='2220' u='m' c='hls_coding_unit'/>
<use f='ffmpeg/libavcodec/hevcdec.c' l='2221' u='m' c='hls_coding_unit'/>
<use f='ffmpeg/libavcodec/hevcdec.c' l='2239' u='m' c='hls_coding_unit'/>
<use f='ffmpeg/libavcodec/hevcdec.c' l='2279' u='m' c='hls_coding_unit'/>
<use f='ffmpeg/libavcodec/hevcdec.c' l='2280' u='m' c='hls_coding_unit'/>
<use f='ffmpeg/libavcodec/hevcdec.c' l='2285' u='m' c='hls_coding_unit'/>
<use f='ffmpeg/libavcodec/hevcdec.c' l='2285' u='m' c='hls_coding_unit'/>
<use f='ffmpeg/libavcodec/hevcdec.c' l='2286' u='m' c='hls_coding_unit'/>
