<dec f='ffmpeg/libavcodec/hevcdec.h' l='504' type='SliceHeader'/>
<use f='ffmpeg/libavcodec/hevc_cabac.c' l='489' u='m' c='cabac_init_state'/>
<use f='ffmpeg/libavcodec/hevc_cabac.c' l='492' u='m' c='cabac_init_state'/>
<use f='ffmpeg/libavcodec/hevc_cabac.c' l='492' u='m' c='cabac_init_state'/>
<use f='ffmpeg/libavcodec/hevc_cabac.c' l='499' u='m' c='cabac_init_state'/>
<use f='ffmpeg/libavcodec/hevc_cabac.c' l='513' u='m' c='ff_hevc_cabac_init'/>
<use f='ffmpeg/libavcodec/hevc_cabac.c' l='517' u='m' c='ff_hevc_cabac_init'/>
<use f='ffmpeg/libavcodec/hevc_cabac.c' l='522' u='m' c='ff_hevc_cabac_init'/>
<use f='ffmpeg/libavcodec/hevc_cabac.c' l='527' u='m' c='ff_hevc_cabac_init'/>
<use f='ffmpeg/libavcodec/hevc_cabac.c' l='793' u='m' c='ff_hevc_merge_idx_decode'/>
<use f='ffmpeg/libavcodec/hevc_cabac.c' l='1104' u='m' c='ff_hevc_hls_residual_coding'/>
<use f='ffmpeg/libavcodec/hevc_cabac.c' l='1107' u='m' c='ff_hevc_hls_residual_coding'/>
<offset>20160</offset>
<use f='ffmpeg/libavcodec/hevc_filter.c' l='98' u='m' c='get_qPy_pred'/>
<use f='ffmpeg/libavcodec/hevc_filter.c' l='730' u='m' c='ff_hevc_deblocking_boundary_strengths'/>
<use f='ffmpeg/libavcodec/hevc_filter.c' l='768' u='m' c='ff_hevc_deblocking_boundary_strengths'/>
<use f='ffmpeg/libavcodec/hevc_filter.c' l='849' u='m' c='ff_hevc_hls_filter'/>
<use f='ffmpeg/libavcodec/hevc_filter.c' l='851' u='m' c='ff_hevc_hls_filter'/>
<use f='ffmpeg/libavcodec/hevc_mvs.c' l='193' u='m' c='derive_temporal_colocated_mvs'/>
<use f='ffmpeg/libavcodec/hevc_mvs.c' l='319' u='m' c='derive_spatial_merge_candidates'/>
<use f='ffmpeg/libavcodec/hevc_mvs.c' l='320' u='m' c='derive_spatial_merge_candidates'/>
<use f='ffmpeg/libavcodec/hevc_mvs.c' l='320' u='m' c='derive_spatial_merge_candidates'/>
<use f='ffmpeg/libavcodec/hevc_mvs.c' l='320' u='m' c='derive_spatial_merge_candidates'/>
<use f='ffmpeg/libavcodec/hevc_mvs.c' l='320' u='m' c='derive_spatial_merge_candidates'/>
<use f='ffmpeg/libavcodec/hevc_mvs.c' l='320' u='m' c='derive_spatial_merge_candidates'/>
<use f='ffmpeg/libavcodec/hevc_mvs.c' l='410' u='m' c='derive_spatial_merge_candidates'/>
<use f='ffmpeg/libavcodec/hevc_mvs.c' l='411' u='m' c='derive_spatial_merge_candidates'/>
<use f='ffmpeg/libavcodec/hevc_mvs.c' l='415' u='m' c='derive_spatial_merge_candidates'/>
<use f='ffmpeg/libavcodec/hevc_mvs.c' l='434' u='m' c='derive_spatial_merge_candidates'/>
<use f='ffmpeg/libavcodec/hevc_mvs.c' l='435' u='m' c='derive_spatial_merge_candidates'/>
<use f='ffmpeg/libavcodec/hevc_mvs.c' l='438' u='m' c='derive_spatial_merge_candidates'/>
<use f='ffmpeg/libavcodec/hevc_mvs.c' l='462' u='m' c='derive_spatial_merge_candidates'/>
<use f='ffmpeg/libavcodec/hevc_mvs.c' l='463' u='m' c='derive_spatial_merge_candidates'/>
<use f='ffmpeg/libavcodec/hevc_mvs.c' l='763' u='m' c='ff_hevc_luma_mv_mvp_mode'/>
<use f='ffmpeg/libavcodec/hevc_refs.c' l='159' u='m' c='ff_hevc_set_new_ref'/>
<use f='ffmpeg/libavcodec/hevc_refs.c' l='181' u='m' c='ff_hevc_output_frame'/>
<use f='ffmpeg/libavcodec/hevc_refs.c' l='277' u='m' c='init_slice_rpl'/>
<use f='ffmpeg/libavcodec/hevc_refs.c' l='293' u='a' c='ff_hevc_slice_rpl'/>
<use f='ffmpeg/libavcodec/hevc_refs.c' l='445' u='m' c='ff_hevc_frame_rps'/>
<use f='ffmpeg/libavcodec/hevc_refs.c' l='446' u='m' c='ff_hevc_frame_rps'/>
<use f='ffmpeg/libavcodec/hevc_refs.c' l='507' u='m' c='ff_hevc_frame_nb_refs'/>
<use f='ffmpeg/libavcodec/hevc_refs.c' l='508' u='m' c='ff_hevc_frame_nb_refs'/>
<use f='ffmpeg/libavcodec/hevcdec.c' l='79' u='m' c='pic_arrays_free'/>
<use f='ffmpeg/libavcodec/hevcdec.c' l='80' u='m' c='pic_arrays_free'/>
<use f='ffmpeg/libavcodec/hevcdec.c' l='81' u='m' c='pic_arrays_free'/>
<use f='ffmpeg/libavcodec/hevcdec.c' l='159' u='m' c='pred_weight_table'/>
<use f='ffmpeg/libavcodec/hevcdec.c' l='166' u='m' c='pred_weight_table'/>
<use f='ffmpeg/libavcodec/hevcdec.c' l='169' u='m' c='pred_weight_table'/>
<use f='ffmpeg/libavcodec/hevcdec.c' l='172' u='m' c='pred_weight_table'/>
<use f='ffmpeg/libavcodec/hevcdec.c' l='172' u='m' c='pred_weight_table'/>
<use f='ffmpeg/libavcodec/hevcdec.c' l='173' u='m' c='pred_weight_table'/>
<use f='ffmpeg/libavcodec/hevcdec.c' l='177' u='m' c='pred_weight_table'/>
<use f='ffmpeg/libavcodec/hevcdec.c' l='180' u='m' c='pred_weight_table'/>
<use f='ffmpeg/libavcodec/hevcdec.c' l='183' u='m' c='pred_weight_table'/>
<use f='ffmpeg/libavcodec/hevcdec.c' l='188' u='m' c='pred_weight_table'/>
<use f='ffmpeg/libavcodec/hevcdec.c' l='188' u='m' c='pred_weight_table'/>
<use f='ffmpeg/libavcodec/hevcdec.c' l='189' u='m' c='pred_weight_table'/>
<use f='ffmpeg/libavcodec/hevcdec.c' l='201' u='m' c='pred_weight_table'/>
<use f='ffmpeg/libavcodec/hevcdec.c' l='201' u='m' c='pred_weight_table'/>
<use f='ffmpeg/libavcodec/hevcdec.c' l='202' u='m' c='pred_weight_table'/>
<use f='ffmpeg/libavcodec/hevcdec.c' l='202' u='m' c='pred_weight_table'/>
<use f='ffmpeg/libavcodec/hevcdec.c' l='203' u='m' c='pred_weight_table'/>
<use f='ffmpeg/libavcodec/hevcdec.c' l='206' u='m' c='pred_weight_table'/>
<use f='ffmpeg/libavcodec/hevcdec.c' l='206' u='m' c='pred_weight_table'/>
<use f='ffmpeg/libavcodec/hevcdec.c' l='207' u='m' c='pred_weight_table'/>
<use f='ffmpeg/libavcodec/hevcdec.c' l='208' u='m' c='pred_weight_table'/>
<use f='ffmpeg/libavcodec/hevcdec.c' l='208' u='m' c='pred_weight_table'/>
<use f='ffmpeg/libavcodec/hevcdec.c' l='209' u='m' c='pred_weight_table'/>
<use f='ffmpeg/libavcodec/hevcdec.c' l='212' u='m' c='pred_weight_table'/>
<use f='ffmpeg/libavcodec/hevcdec.c' l='213' u='m' c='pred_weight_table'/>
<use f='ffmpeg/libavcodec/hevcdec.c' l='216' u='m' c='pred_weight_table'/>
<use f='ffmpeg/libavcodec/hevcdec.c' l='216' u='m' c='pred_weight_table'/>
<use f='ffmpeg/libavcodec/hevcdec.c' l='217' u='m' c='pred_weight_table'/>
<use f='ffmpeg/libavcodec/hevcdec.c' l='221' u='m' c='pred_weight_table'/>
<use f='ffmpeg/libavcodec/hevcdec.c' l='224' u='m' c='pred_weight_table'/>
<use f='ffmpeg/libavcodec/hevcdec.c' l='227' u='m' c='pred_weight_table'/>
<use f='ffmpeg/libavcodec/hevcdec.c' l='232' u='m' c='pred_weight_table'/>
<use f='ffmpeg/libavcodec/hevcdec.c' l='232' u='m' c='pred_weight_table'/>
<use f='ffmpeg/libavcodec/hevcdec.c' l='233' u='m' c='pred_weight_table'/>
<use f='ffmpeg/libavcodec/hevcdec.c' l='245' u='m' c='pred_weight_table'/>
<use f='ffmpeg/libavcodec/hevcdec.c' l='245' u='m' c='pred_weight_table'/>
<use f='ffmpeg/libavcodec/hevcdec.c' l='246' u='m' c='pred_weight_table'/>
<use f='ffmpeg/libavcodec/hevcdec.c' l='246' u='m' c='pred_weight_table'/>
<use f='ffmpeg/libavcodec/hevcdec.c' l='247' u='m' c='pred_weight_table'/>
<use f='ffmpeg/libavcodec/hevcdec.c' l='250' u='m' c='pred_weight_table'/>
<use f='ffmpeg/libavcodec/hevcdec.c' l='250' u='m' c='pred_weight_table'/>
<use f='ffmpeg/libavcodec/hevcdec.c' l='251' u='m' c='pred_weight_table'/>
<use f='ffmpeg/libavcodec/hevcdec.c' l='252' u='m' c='pred_weight_table'/>
<use f='ffmpeg/libavcodec/hevcdec.c' l='252' u='m' c='pred_weight_table'/>
<use f='ffmpeg/libavcodec/hevcdec.c' l='253' u='m' c='pred_weight_table'/>
<use f='ffmpeg/libavcodec/hevcdec.c' l='306' u='m' c='decode_lt_rps'/>
<use f='ffmpeg/libavcodec/hevcdec.c' l='542' u='a' c='hls_slice_header'/>
<use f='ffmpeg/libavcodec/hevcdec.c' l='710' u='m' c='hls_slice_header'/>
<use f='ffmpeg/libavcodec/hevcdec.c' l='952' u='m' c='hls_slice_header'/>
<use f='ffmpeg/libavcodec/hevcdec.c' l='952' u='m' c='hls_slice_header'/>
<use f='ffmpeg/libavcodec/hevcdec.c' l='963' u='m' c='hls_slice_header'/>
<use f='ffmpeg/libavcodec/hevcdec.c' l='966' u='m' c='hls_slice_header'/>
<use f='ffmpeg/libavcodec/hevcdec.c' l='997' u='m' c='hls_sao_param'/>
<use f='ffmpeg/libavcodec/hevcdec.c' l='998' u='m' c='hls_sao_param'/>
<use f='ffmpeg/libavcodec/hevcdec.c' l='1013' u='m' c='hls_sao_param'/>
<use f='ffmpeg/libavcodec/hevcdec.c' l='1124' u='m' c='hls_transform_unit'/>
<use f='ffmpeg/libavcodec/hevcdec.c' l='1413' u='m' c='hls_transform_tree'/>
<use f='ffmpeg/libavcodec/hevcdec.c' l='1442' u='m' c='hls_pcm_sample'/>
<use f='ffmpeg/libavcodec/hevcdec.c' l='1491' u='m' c='luma_mc_uni'/>
<use f='ffmpeg/libavcodec/hevcdec.c' l='1492' u='m' c='luma_mc_uni'/>
<use f='ffmpeg/libavcodec/hevcdec.c' l='1521' u='m' c='luma_mc_uni'/>
<use f='ffmpeg/libavcodec/hevcdec.c' l='1554' u='m' c='luma_mc_bi'/>
<use f='ffmpeg/libavcodec/hevcdec.c' l='1555' u='m' c='luma_mc_bi'/>
<use f='ffmpeg/libavcodec/hevcdec.c' l='1606' u='m' c='luma_mc_bi'/>
<use f='ffmpeg/libavcodec/hevcdec.c' l='1607' u='m' c='luma_mc_bi'/>
<use f='ffmpeg/libavcodec/hevcdec.c' l='1608' u='m' c='luma_mc_bi'/>
<use f='ffmpeg/libavcodec/hevcdec.c' l='1609' u='m' c='luma_mc_bi'/>
<use f='ffmpeg/libavcodec/hevcdec.c' l='1610' u='m' c='luma_mc_bi'/>
<use f='ffmpeg/libavcodec/hevcdec.c' l='1640' u='m' c='chroma_mc_uni'/>
<use f='ffmpeg/libavcodec/hevcdec.c' l='1641' u='m' c='chroma_mc_uni'/>
<use f='ffmpeg/libavcodec/hevcdec.c' l='1676' u='m' c='chroma_mc_uni'/>
<use f='ffmpeg/libavcodec/hevcdec.c' l='1705' u='m' c='chroma_mc_bi'/>
<use f='ffmpeg/libavcodec/hevcdec.c' l='1706' u='m' c='chroma_mc_bi'/>
<use f='ffmpeg/libavcodec/hevcdec.c' l='1779' u='m' c='chroma_mc_bi'/>
<use f='ffmpeg/libavcodec/hevcdec.c' l='1780' u='m' c='chroma_mc_bi'/>
<use f='ffmpeg/libavcodec/hevcdec.c' l='1781' u='m' c='chroma_mc_bi'/>
<use f='ffmpeg/libavcodec/hevcdec.c' l='1782' u='m' c='chroma_mc_bi'/>
<use f='ffmpeg/libavcodec/hevcdec.c' l='1783' u='m' c='chroma_mc_bi'/>
<use f='ffmpeg/libavcodec/hevcdec.c' l='1807' u='m' c='hevc_luma_mv_mvp_mode'/>
<use f='ffmpeg/libavcodec/hevcdec.c' l='1811' u='m' c='hevc_luma_mv_mvp_mode'/>
<use f='ffmpeg/libavcodec/hevcdec.c' l='1812' u='m' c='hevc_luma_mv_mvp_mode'/>
<use f='ffmpeg/libavcodec/hevcdec.c' l='1824' u='m' c='hevc_luma_mv_mvp_mode'/>
<use f='ffmpeg/libavcodec/hevcdec.c' l='1825' u='m' c='hevc_luma_mv_mvp_mode'/>
<use f='ffmpeg/libavcodec/hevcdec.c' l='1827' u='m' c='hevc_luma_mv_mvp_mode'/>
<use f='ffmpeg/libavcodec/hevcdec.c' l='1874' u='m' c='hls_prediction_unit'/>
<use f='ffmpeg/libavcodec/hevcdec.c' l='1914' u='m' c='hls_prediction_unit'/>
<use f='ffmpeg/libavcodec/hevcdec.c' l='1915' u='m' c='hls_prediction_unit'/>
<use f='ffmpeg/libavcodec/hevcdec.c' l='1920' u='m' c='hls_prediction_unit'/>
<use f='ffmpeg/libavcodec/hevcdec.c' l='1920' u='m' c='hls_prediction_unit'/>
<use f='ffmpeg/libavcodec/hevcdec.c' l='1923' u='m' c='hls_prediction_unit'/>
<use f='ffmpeg/libavcodec/hevcdec.c' l='1923' u='m' c='hls_prediction_unit'/>
<use f='ffmpeg/libavcodec/hevcdec.c' l='1933' u='m' c='hls_prediction_unit'/>
<use f='ffmpeg/libavcodec/hevcdec.c' l='1934' u='m' c='hls_prediction_unit'/>
<use f='ffmpeg/libavcodec/hevcdec.c' l='1939' u='m' c='hls_prediction_unit'/>
<use f='ffmpeg/libavcodec/hevcdec.c' l='1939' u='m' c='hls_prediction_unit'/>
<use f='ffmpeg/libavcodec/hevcdec.c' l='1943' u='m' c='hls_prediction_unit'/>
<use f='ffmpeg/libavcodec/hevcdec.c' l='1943' u='m' c='hls_prediction_unit'/>
<use f='ffmpeg/libavcodec/hevcdec.c' l='2185' u='m' c='hls_coding_unit'/>
<use f='ffmpeg/libavcodec/hevcdec.c' l='2206' u='m' c='hls_coding_unit'/>
<use f='ffmpeg/libavcodec/hevcdec.c' l='2211' u='m' c='hls_coding_unit'/>
<use f='ffmpeg/libavcodec/hevcdec.c' l='2294' u='m' c='hls_coding_unit'/>
<use f='ffmpeg/libavcodec/hevcdec.c' l='2341' u='m' c='hls_coding_quadtree'/>
<use f='ffmpeg/libavcodec/hevcdec.c' l='2410' u='m' c='hls_decode_neighbour'/>
<use f='ffmpeg/libavcodec/hevcdec.c' l='2412' u='m' c='hls_decode_neighbour'/>
<use f='ffmpeg/libavcodec/hevcdec.c' l='2460' u='m' c='hls_decode_entry'/>
<use f='ffmpeg/libavcodec/hevcdec.c' l='2463' u='m' c='hls_decode_entry'/>
<use f='ffmpeg/libavcodec/hevcdec.c' l='2468' u='m' c='hls_decode_entry'/>
<use f='ffmpeg/libavcodec/hevcdec.c' l='2470' u='m' c='hls_decode_entry'/>
<use f='ffmpeg/libavcodec/hevcdec.c' l='2491' u='m' c='hls_decode_entry'/>
<use f='ffmpeg/libavcodec/hevcdec.c' l='2492' u='m' c='hls_decode_entry'/>
<use f='ffmpeg/libavcodec/hevcdec.c' l='2493' u='m' c='hls_decode_entry'/>
<use f='ffmpeg/libavcodec/hevcdec.c' l='2533' u='m' c='hls_decode_entry_wpp'/>
<use f='ffmpeg/libavcodec/hevcdec.c' l='2542' u='m' c='hls_decode_entry_wpp'/>
<use f='ffmpeg/libavcodec/hevcdec.c' l='2542' u='m' c='hls_decode_entry_wpp'/>
<use f='ffmpeg/libavcodec/hevcdec.c' l='2545' u='m' c='hls_decode_entry_wpp'/>
<use f='ffmpeg/libavcodec/hevcdec.c' l='2545' u='m' c='hls_decode_entry_wpp'/>
<use f='ffmpeg/libavcodec/hevcdec.c' l='2578' u='m' c='hls_decode_entry_wpp'/>
<use f='ffmpeg/libavcodec/hevcdec.c' l='2611' u='m' c='hls_slice_data_wpp'/>
<use f='ffmpeg/libavcodec/hevcdec.c' l='2612' u='m' c='hls_slice_data_wpp'/>
<use f='ffmpeg/libavcodec/hevcdec.c' l='2623' u='m' c='hls_slice_data_wpp'/>
<use f='ffmpeg/libavcodec/hevcdec.c' l='2623' u='m' c='hls_slice_data_wpp'/>
<use f='ffmpeg/libavcodec/hevcdec.c' l='2625' u='m' c='hls_slice_data_wpp'/>
<use f='ffmpeg/libavcodec/hevcdec.c' l='2625' u='m' c='hls_slice_data_wpp'/>
<use f='ffmpeg/libavcodec/hevcdec.c' l='2632' u='m' c='hls_slice_data_wpp'/>
<use f='ffmpeg/libavcodec/hevcdec.c' l='2651' u='m' c='hls_slice_data_wpp'/>
<use f='ffmpeg/libavcodec/hevcdec.c' l='2658' u='m' c='hls_slice_data_wpp'/>
<use f='ffmpeg/libavcodec/hevcdec.c' l='2659' u='m' c='hls_slice_data_wpp'/>
<use f='ffmpeg/libavcodec/hevcdec.c' l='2661' u='m' c='hls_slice_data_wpp'/>
<use f='ffmpeg/libavcodec/hevcdec.c' l='2667' u='m' c='hls_slice_data_wpp'/>
<use f='ffmpeg/libavcodec/hevcdec.c' l='2667' u='m' c='hls_slice_data_wpp'/>
<use f='ffmpeg/libavcodec/hevcdec.c' l='2668' u='m' c='hls_slice_data_wpp'/>
<use f='ffmpeg/libavcodec/hevcdec.c' l='2671' u='m' c='hls_slice_data_wpp'/>
<use f='ffmpeg/libavcodec/hevcdec.c' l='2672' u='m' c='hls_slice_data_wpp'/>
<use f='ffmpeg/libavcodec/hevcdec.c' l='2672' u='m' c='hls_slice_data_wpp'/>
<use f='ffmpeg/libavcodec/hevcdec.c' l='2678' u='m' c='hls_slice_data_wpp'/>
<use f='ffmpeg/libavcodec/hevcdec.c' l='2678' u='m' c='hls_slice_data_wpp'/>
<use f='ffmpeg/libavcodec/hevcdec.c' l='2679' u='m' c='hls_slice_data_wpp'/>
<use f='ffmpeg/libavcodec/hevcdec.c' l='2679' u='m' c='hls_slice_data_wpp'/>
<use f='ffmpeg/libavcodec/hevcdec.c' l='2694' u='m' c='hls_slice_data_wpp'/>
<use f='ffmpeg/libavcodec/hevcdec.c' l='2700' u='m' c='hls_slice_data_wpp'/>
<use f='ffmpeg/libavcodec/hevcdec.c' l='2702' u='m' c='hls_slice_data_wpp'/>
<use f='ffmpeg/libavcodec/hevcdec.c' l='2934' u='m' c='hevc_frame_start'/>
<use f='ffmpeg/libavcodec/hevcdec.c' l='3047' u='m' c='decode_nal_unit'/>
<use f='ffmpeg/libavcodec/hevcdec.c' l='3048' u='m' c='decode_nal_unit'/>
<use f='ffmpeg/libavcodec/hevcdec.c' l='3053' u='m' c='decode_nal_unit'/>
<use f='ffmpeg/libavcodec/hevcdec.c' l='3088' u='m' c='decode_nal_unit'/>
<use f='ffmpeg/libavcodec/hevcdec.c' l='3089' u='m' c='decode_nal_unit'/>
<use f='ffmpeg/libavcodec/hevcdec.c' l='3098' u='m' c='decode_nal_unit'/>
<use f='ffmpeg/libavcodec/hevcdec.c' l='3109' u='m' c='decode_nal_unit'/>
<use f='ffmpeg/libavcodec/hevcdec.c' l='3429' u='m' c='hevc_decode_free'/>
<use f='ffmpeg/libavcodec/hevcdec.c' l='3430' u='m' c='hevc_decode_free'/>
<use f='ffmpeg/libavcodec/hevcdec.c' l='3431' u='m' c='hevc_decode_free'/>
