<dec f='ffmpeg/libavcodec/huffyuv.h' l='60' type='PutBitContext'/>
<offset>448</offset>
<use f='ffmpeg/libavcodec/huffyuvenc.c' l='446' u='m' c='encode_422_bitstream'/>
<use f='ffmpeg/libavcodec/huffyuvenc.c' l='446' u='m' c='encode_422_bitstream'/>
<use f='ffmpeg/libavcodec/huffyuvenc.c' l='446' u='a' c='encode_422_bitstream'/>
<use f='ffmpeg/libavcodec/huffyuvenc.c' l='474' u='a' c='encode_422_bitstream'/>
<use f='ffmpeg/libavcodec/huffyuvenc.c' l='476' u='a' c='encode_422_bitstream'/>
<use f='ffmpeg/libavcodec/huffyuvenc.c' l='478' u='a' c='encode_422_bitstream'/>
<use f='ffmpeg/libavcodec/huffyuvenc.c' l='480' u='a' c='encode_422_bitstream'/>
<use f='ffmpeg/libavcodec/huffyuvenc.c' l='485' u='a' c='encode_422_bitstream'/>
<use f='ffmpeg/libavcodec/huffyuvenc.c' l='486' u='a' c='encode_422_bitstream'/>
<use f='ffmpeg/libavcodec/huffyuvenc.c' l='487' u='a' c='encode_422_bitstream'/>
<use f='ffmpeg/libavcodec/huffyuvenc.c' l='488' u='a' c='encode_422_bitstream'/>
<use f='ffmpeg/libavcodec/huffyuvenc.c' l='498' u='m' c='encode_plane_bitstream'/>
<use f='ffmpeg/libavcodec/huffyuvenc.c' l='498' u='m' c='encode_plane_bitstream'/>
<use f='ffmpeg/libavcodec/huffyuvenc.c' l='498' u='a' c='encode_plane_bitstream'/>
<use f='ffmpeg/libavcodec/huffyuvenc.c' l='535' u='a' c='encode_plane_bitstream'/>
<use f='ffmpeg/libavcodec/huffyuvenc.c' l='536' u='a' c='encode_plane_bitstream'/>
<use f='ffmpeg/libavcodec/huffyuvenc.c' l='514' u='a' c='encode_plane_bitstream'/>
<use f='ffmpeg/libavcodec/huffyuvenc.c' l='535' u='a' c='encode_plane_bitstream'/>
<use f='ffmpeg/libavcodec/huffyuvenc.c' l='536' u='a' c='encode_plane_bitstream'/>
<use f='ffmpeg/libavcodec/huffyuvenc.c' l='514' u='a' c='encode_plane_bitstream'/>
<use f='ffmpeg/libavcodec/huffyuvenc.c' l='535' u='a' c='encode_plane_bitstream'/>
<use f='ffmpeg/libavcodec/huffyuvenc.c' l='536' u='a' c='encode_plane_bitstream'/>
<use f='ffmpeg/libavcodec/huffyuvenc.c' l='514' u='a' c='encode_plane_bitstream'/>
<use f='ffmpeg/libavcodec/huffyuvenc.c' l='535' u='a' c='encode_plane_bitstream'/>
<use f='ffmpeg/libavcodec/huffyuvenc.c' l='536' u='a' c='encode_plane_bitstream'/>
<use f='ffmpeg/libavcodec/huffyuvenc.c' l='514' u='a' c='encode_plane_bitstream'/>
<use f='ffmpeg/libavcodec/huffyuvenc.c' l='538' u='a' c='encode_plane_bitstream'/>
<use f='ffmpeg/libavcodec/huffyuvenc.c' l='539' u='a' c='encode_plane_bitstream'/>
<use f='ffmpeg/libavcodec/huffyuvenc.c' l='540' u='a' c='encode_plane_bitstream'/>
<use f='ffmpeg/libavcodec/huffyuvenc.c' l='541' u='a' c='encode_plane_bitstream'/>
<use f='ffmpeg/libavcodec/huffyuvenc.c' l='516' u='a' c='encode_plane_bitstream'/>
<use f='ffmpeg/libavcodec/huffyuvenc.c' l='517' u='a' c='encode_plane_bitstream'/>
<use f='ffmpeg/libavcodec/huffyuvenc.c' l='538' u='a' c='encode_plane_bitstream'/>
<use f='ffmpeg/libavcodec/huffyuvenc.c' l='539' u='a' c='encode_plane_bitstream'/>
<use f='ffmpeg/libavcodec/huffyuvenc.c' l='540' u='a' c='encode_plane_bitstream'/>
<use f='ffmpeg/libavcodec/huffyuvenc.c' l='541' u='a' c='encode_plane_bitstream'/>
<use f='ffmpeg/libavcodec/huffyuvenc.c' l='516' u='a' c='encode_plane_bitstream'/>
<use f='ffmpeg/libavcodec/huffyuvenc.c' l='517' u='a' c='encode_plane_bitstream'/>
<use f='ffmpeg/libavcodec/huffyuvenc.c' l='660' u='m' c='encode_gray_bitstream'/>
<use f='ffmpeg/libavcodec/huffyuvenc.c' l='660' u='m' c='encode_gray_bitstream'/>
<use f='ffmpeg/libavcodec/huffyuvenc.c' l='660' u='a' c='encode_gray_bitstream'/>
<use f='ffmpeg/libavcodec/huffyuvenc.c' l='672' u='a' c='encode_gray_bitstream'/>
<use f='ffmpeg/libavcodec/huffyuvenc.c' l='673' u='a' c='encode_gray_bitstream'/>
<use f='ffmpeg/libavcodec/huffyuvenc.c' l='672' u='a' c='encode_gray_bitstream'/>
<use f='ffmpeg/libavcodec/huffyuvenc.c' l='673' u='a' c='encode_gray_bitstream'/>
<use f='ffmpeg/libavcodec/huffyuvenc.c' l='705' u='m' c='encode_bgra_bitstream'/>
<use f='ffmpeg/libavcodec/huffyuvenc.c' l='705' u='m' c='encode_bgra_bitstream'/>
<use f='ffmpeg/libavcodec/huffyuvenc.c' l='705' u='a' c='encode_bgra_bitstream'/>
<use f='ffmpeg/libavcodec/huffyuvenc.c' l='725' u='a' c='encode_bgra_bitstream'/>
<use f='ffmpeg/libavcodec/huffyuvenc.c' l='726' u='a' c='encode_bgra_bitstream'/>
<use f='ffmpeg/libavcodec/huffyuvenc.c' l='727' u='a' c='encode_bgra_bitstream'/>
<use f='ffmpeg/libavcodec/huffyuvenc.c' l='729' u='a' c='encode_bgra_bitstream'/>
<use f='ffmpeg/libavcodec/huffyuvenc.c' l='725' u='a' c='encode_bgra_bitstream'/>
<use f='ffmpeg/libavcodec/huffyuvenc.c' l='726' u='a' c='encode_bgra_bitstream'/>
<use f='ffmpeg/libavcodec/huffyuvenc.c' l='727' u='a' c='encode_bgra_bitstream'/>
<use f='ffmpeg/libavcodec/huffyuvenc.c' l='729' u='a' c='encode_bgra_bitstream'/>
<use f='ffmpeg/libavcodec/huffyuvenc.c' l='778' u='a' c='encode_frame'/>
<use f='ffmpeg/libavcodec/huffyuvenc.c' l='784' u='a' c='encode_frame'/>
<use f='ffmpeg/libavcodec/huffyuvenc.c' l='785' u='a' c='encode_frame'/>
<use f='ffmpeg/libavcodec/huffyuvenc.c' l='786' u='a' c='encode_frame'/>
<use f='ffmpeg/libavcodec/huffyuvenc.c' l='787' u='a' c='encode_frame'/>
<use f='ffmpeg/libavcodec/huffyuvenc.c' l='892' u='a' c='encode_frame'/>
<use f='ffmpeg/libavcodec/huffyuvenc.c' l='893' u='a' c='encode_frame'/>
<use f='ffmpeg/libavcodec/huffyuvenc.c' l='894' u='a' c='encode_frame'/>
<use f='ffmpeg/libavcodec/huffyuvenc.c' l='895' u='a' c='encode_frame'/>
<use f='ffmpeg/libavcodec/huffyuvenc.c' l='920' u='a' c='encode_frame'/>
<use f='ffmpeg/libavcodec/huffyuvenc.c' l='921' u='a' c='encode_frame'/>
<use f='ffmpeg/libavcodec/huffyuvenc.c' l='922' u='a' c='encode_frame'/>
<use f='ffmpeg/libavcodec/huffyuvenc.c' l='923' u='a' c='encode_frame'/>
<use f='ffmpeg/libavcodec/huffyuvenc.c' l='1000' u='a' c='encode_frame'/>
<use f='ffmpeg/libavcodec/huffyuvenc.c' l='1001' u='a' c='encode_frame'/>
<use f='ffmpeg/libavcodec/huffyuvenc.c' l='1002' u='a' c='encode_frame'/>
<use f='ffmpeg/libavcodec/huffyuvenc.c' l='1023' u='a' c='encode_frame'/>
