<dec f='ffmpeg/libavfilter/colorspace.h' l='29' type='double'/>
<use f='ffmpeg/libavfilter/colorspace.c' l='147' u='r' c='ff_fill_rgb2yuv_table'/>
<use f='ffmpeg/libavfilter/colorspace.c' l='150' u='r' c='ff_fill_rgb2yuv_table'/>
<use f='ffmpeg/libavfilter/colorspace.c' l='156' u='r' c='ff_fill_rgb2yuv_table'/>
<use f='ffmpeg/libavfilter/colorspace.c' l='161' u='r' c='ff_fill_rgb2yuv_table'/>
<use f='ffmpeg/libavfilter/colorspace.c' l='164' u='r' c='ff_fill_rgb2yuv_table'/>
<offset>64</offset>
<use f='ffmpeg/libavfilter/vf_tonemap.c' l='148' u='r' c='tonemap'/>
