<dec f='ffmpeg/libavformat/isom.h' l='159' type='AVIOContext *'/>
<offset>0</offset>
<use f='ffmpeg/libavformat/mov.c' l='4287' u='a' c='mov_read_trak'/>
<use f='ffmpeg/libavformat/mov.c' l='4303' u='w' c='mov_read_trak'/>
<use f='ffmpeg/libavformat/mov.c' l='7226' u='r' c='mov_read_chapters'/>
<use f='ffmpeg/libavformat/mov.c' l='7233' u='r' c='mov_read_chapters'/>
<use f='ffmpeg/libavformat/mov.c' l='7238' u='r' c='mov_read_chapters'/>
<use f='ffmpeg/libavformat/mov.c' l='7260' u='r' c='mov_read_chapters'/>
<use f='ffmpeg/libavformat/mov.c' l='7266' u='r' c='mov_read_chapters'/>
<use f='ffmpeg/libavformat/mov.c' l='7279' u='r' c='mov_read_chapters'/>
<use f='ffmpeg/libavformat/mov.c' l='7281' u='r' c='mov_read_chapters'/>
<use f='ffmpeg/libavformat/mov.c' l='7283' u='r' c='mov_read_chapters'/>
<use f='ffmpeg/libavformat/mov.c' l='7289' u='r' c='mov_read_chapters'/>
<use f='ffmpeg/libavformat/mov.c' l='7298' u='r' c='mov_read_chapters'/>
<use f='ffmpeg/libavformat/mov.c' l='7320' u='r' c='mov_read_rtmd_track'/>
<use f='ffmpeg/libavformat/mov.c' l='7326' u='r' c='mov_read_rtmd_track'/>
<use f='ffmpeg/libavformat/mov.c' l='7337' u='r' c='mov_read_rtmd_track'/>
<use f='ffmpeg/libavformat/mov.c' l='7345' u='r' c='mov_read_timecode_track'/>
<use f='ffmpeg/libavformat/mov.c' l='7351' u='r' c='mov_read_timecode_track'/>
<use f='ffmpeg/libavformat/mov.c' l='7365' u='r' c='mov_read_timecode_track'/>
<use f='ffmpeg/libavformat/mov.c' l='7403' u='a' c='mov_read_close'/>
<use f='ffmpeg/libavformat/mov.c' l='7405' u='w' c='mov_read_close'/>
<use f='ffmpeg/libavformat/mov.c' l='7816' u='r' c='mov_find_next_sample'/>
<use f='ffmpeg/libavformat/mov.c' l='7822' u='r' c='mov_find_next_sample'/>
<use f='ffmpeg/libavformat/mov.c' l='7822' u='r' c='mov_find_next_sample'/>
<use f='ffmpeg/libavformat/mov.c' l='7950' u='r' c='mov_read_packet'/>
<use f='ffmpeg/libavformat/mov.c' l='7954' u='r' c='mov_read_packet'/>
<use f='ffmpeg/libavformat/mov.c' l='7966' u='r' c='mov_read_packet'/>
<use f='ffmpeg/libavformat/mov.c' l='7968' u='r' c='mov_read_packet'/>
<use f='ffmpeg/libavformat/mov.c' l='7970' u='r' c='mov_read_packet'/>
