<dec f='ffmpeg/libavcodec/mpegaudiodec_template.c' l='75' macro='1' type='int'/>
<use f='ffmpeg/libavcodec/mpegaudiodec_template.c' l='473' u='r' c='mp_decode_layer2'/>
<use f='ffmpeg/libavcodec/mpegaudiodec_template.c' l='946' u='r' c='compute_stereo'/>
<use f='ffmpeg/libavcodec/mpegaudiodec_template.c' l='1213' u='r' c='mp_decode_layer3'/>
<use f='ffmpeg/libavcodec/mpegaudiodec_template.c' l='1251' u='r' c='mp_decode_layer3'/>
<use f='ffmpeg/libavcodec/mpegaudiodec_template.c' l='1285' u='r' c='mp_decode_layer3'/>
<use f='ffmpeg/libavcodec/mpegaudiodec_template.c' l='1335' u='r' c='mp_decode_layer3'/>
<use f='ffmpeg/libavcodec/mpegaudiodec_template.c' l='1483' u='r' c='mp_decode_frame'/>
<offset>288</offset>
