<dec f='ffmpeg/libavcodec/mpc.h' l='56' type='int'/>
<offset>544</offset>
<use f='ffmpeg/libavcodec/mpc7.c' l='99' u='w' c='mpc7_decode_init'/>
<use f='ffmpeg/libavcodec/mpc7.c' l='109' u='r' c='mpc7_decode_init'/>
<use f='ffmpeg/libavcodec/mpc7.c' l='233' u='r' c='mpc7_decode_frame'/>
<use f='ffmpeg/libavcodec/mpc8.c' l='168' u='w' c='mpc8_decode_init'/>
<use f='ffmpeg/libavcodec/mpc8.c' l='233' u='r' c='mpc8_decode_frame'/>
