<dec f='ffmpeg/libavcodec/mpegvideo.h' l='151' type='PutBitContext'/>
<use f='ffmpeg/libavcodec/mpegvideo.h' l='766' u='a' c='get_bits_diff'/>
<offset>6528</offset>
<doc f='ffmpeg/libavcodec/mpegvideo.h' l='150'>/** bit output */</doc>
<use f='ffmpeg/libavcodec/dnxhdenc.c' l='579' u='a' c='dnxhd_encode_dc'/>
<use f='ffmpeg/libavcodec/dnxhdenc.c' l='600' u='a' c='dnxhd_encode_block'/>
<use f='ffmpeg/libavcodec/dnxhdenc.c' l='602' u='a' c='dnxhd_encode_block'/>
<use f='ffmpeg/libavcodec/dnxhdenc.c' l='607' u='a' c='dnxhd_encode_block'/>
<use f='ffmpeg/libavcodec/dnxhdenc.c' l='892' u='a' c='dnxhd_encode_thread'/>
<use f='ffmpeg/libavcodec/dnxhdenc.c' l='903' u='a' c='dnxhd_encode_thread'/>
<use f='ffmpeg/libavcodec/dnxhdenc.c' l='904' u='a' c='dnxhd_encode_thread'/>
<use f='ffmpeg/libavcodec/dnxhdenc.c' l='918' u='a' c='dnxhd_encode_thread'/>
<use f='ffmpeg/libavcodec/dnxhdenc.c' l='919' u='a' c='dnxhd_encode_thread'/>
<use f='ffmpeg/libavcodec/dnxhdenc.c' l='919' u='a' c='dnxhd_encode_thread'/>
<use f='ffmpeg/libavcodec/dnxhdenc.c' l='920' u='a' c='dnxhd_encode_thread'/>
<use f='ffmpeg/libavcodec/h263.h' l='120' u='a' c='ff_h263_encode_motion_vector'/>
<use f='ffmpeg/libavcodec/h263.h' l='124' u='a' c='ff_h263_encode_motion_vector'/>
<use f='ffmpeg/libavcodec/h263.h' l='125' u='a' c='ff_h263_encode_motion_vector'/>
<use f='ffmpeg/libavcodec/flvenc.c' l='31' u='a' c='ff_flv_encode_picture_header'/>
<use f='ffmpeg/libavcodec/flvenc.c' l='33' u='a' c='ff_flv_encode_picture_header'/>
<use f='ffmpeg/libavcodec/flvenc.c' l='35' u='a' c='ff_flv_encode_picture_header'/>
<use f='ffmpeg/libavcodec/flvenc.c' l='36' u='a' c='ff_flv_encode_picture_header'/>
<use f='ffmpeg/libavcodec/flvenc.c' l='53' u='a' c='ff_flv_encode_picture_header'/>
<use f='ffmpeg/libavcodec/flvenc.c' l='55' u='a' c='ff_flv_encode_picture_header'/>
<use f='ffmpeg/libavcodec/flvenc.c' l='56' u='a' c='ff_flv_encode_picture_header'/>
<use f='ffmpeg/libavcodec/flvenc.c' l='58' u='a' c='ff_flv_encode_picture_header'/>
<use f='ffmpeg/libavcodec/flvenc.c' l='59' u='a' c='ff_flv_encode_picture_header'/>
<use f='ffmpeg/libavcodec/flvenc.c' l='61' u='a' c='ff_flv_encode_picture_header'/>
<use f='ffmpeg/libavcodec/flvenc.c' l='62' u='a' c='ff_flv_encode_picture_header'/>
<use f='ffmpeg/libavcodec/flvenc.c' l='63' u='a' c='ff_flv_encode_picture_header'/>
<use f='ffmpeg/libavcodec/flvenc.c' l='64' u='a' c='ff_flv_encode_picture_header'/>
<use f='ffmpeg/libavcodec/h261enc.c' l='59' u='a' c='ff_h261_encode_picture_header'/>
<use f='ffmpeg/libavcodec/h261enc.c' l='62' u='a' c='ff_h261_encode_picture_header'/>
<use f='ffmpeg/libavcodec/h261enc.c' l='64' u='a' c='ff_h261_encode_picture_header'/>
<use f='ffmpeg/libavcodec/h261enc.c' l='68' u='a' c='ff_h261_encode_picture_header'/>
<use f='ffmpeg/libavcodec/h261enc.c' l='70' u='a' c='ff_h261_encode_picture_header'/>
<use f='ffmpeg/libavcodec/h261enc.c' l='71' u='a' c='ff_h261_encode_picture_header'/>
<use f='ffmpeg/libavcodec/h261enc.c' l='72' u='a' c='ff_h261_encode_picture_header'/>
<use f='ffmpeg/libavcodec/h261enc.c' l='76' u='a' c='ff_h261_encode_picture_header'/>
<use f='ffmpeg/libavcodec/h261enc.c' l='78' u='a' c='ff_h261_encode_picture_header'/>
<use f='ffmpeg/libavcodec/h261enc.c' l='79' u='a' c='ff_h261_encode_picture_header'/>
<use f='ffmpeg/libavcodec/h261enc.c' l='81' u='a' c='ff_h261_encode_picture_header'/>
<use f='ffmpeg/libavcodec/h261enc.c' l='100' u='a' c='h261_encode_gob_header'/>
<use f='ffmpeg/libavcodec/h261enc.c' l='101' u='a' c='h261_encode_gob_header'/>
<use f='ffmpeg/libavcodec/h261enc.c' l='102' u='a' c='h261_encode_gob_header'/>
<use f='ffmpeg/libavcodec/h261enc.c' l='103' u='a' c='h261_encode_gob_header'/>
<use f='ffmpeg/libavcodec/h261enc.c' l='142' u='a' c='h261_encode_motion'/>
<use f='ffmpeg/libavcodec/h261enc.c' l='150' u='a' c='h261_encode_motion'/>
<use f='ffmpeg/libavcodec/h261enc.c' l='151' u='a' c='h261_encode_motion'/>
<use f='ffmpeg/libavcodec/h261enc.c' l='191' u='a' c='h261_encode_block'/>
<use f='ffmpeg/libavcodec/h261enc.c' l='193' u='a' c='h261_encode_block'/>
<use f='ffmpeg/libavcodec/h261enc.c' l='198' u='a' c='h261_encode_block'/>
<use f='ffmpeg/libavcodec/h261enc.c' l='222' u='a' c='h261_encode_block'/>
<use f='ffmpeg/libavcodec/h261enc.c' l='224' u='a' c='h261_encode_block'/>
<use f='ffmpeg/libavcodec/h261enc.c' l='227' u='a' c='h261_encode_block'/>
<use f='ffmpeg/libavcodec/h261enc.c' l='229' u='a' c='h261_encode_block'/>
<use f='ffmpeg/libavcodec/h261enc.c' l='235' u='a' c='h261_encode_block'/>
<use f='ffmpeg/libavcodec/h261enc.c' l='267' u='a' c='ff_h261_encode_mb'/>
<use f='ffmpeg/libavcodec/h261enc.c' l='290' u='a' c='ff_h261_encode_mb'/>
<use f='ffmpeg/libavcodec/h261enc.c' l='298' u='a' c='ff_h261_encode_mb'/>
<use f='ffmpeg/libavcodec/h261enc.c' l='312' u='a' c='ff_h261_encode_mb'/>
<use f='ffmpeg/libavcodec/ituh263enc.c' l='127' u='a' c='ff_h263_encode_picture_header'/>
<use f='ffmpeg/libavcodec/ituh263enc.c' l='130' u='a' c='ff_h263_encode_picture_header'/>
<use f='ffmpeg/libavcodec/ituh263enc.c' l='131' u='a' c='ff_h263_encode_picture_header'/>
<use f='ffmpeg/libavcodec/ituh263enc.c' l='134' u='a' c='ff_h263_encode_picture_header'/>
<use f='ffmpeg/libavcodec/ituh263enc.c' l='136' u='a' c='ff_h263_encode_picture_header'/>
<use f='ffmpeg/libavcodec/ituh263enc.c' l='137' u='a' c='ff_h263_encode_picture_header'/>
<use f='ffmpeg/libavcodec/ituh263enc.c' l='138' u='a' c='ff_h263_encode_picture_header'/>
<use f='ffmpeg/libavcodec/ituh263enc.c' l='139' u='a' c='ff_h263_encode_picture_header'/>
<use f='ffmpeg/libavcodec/ituh263enc.c' l='140' u='a' c='ff_h263_encode_picture_header'/>
<use f='ffmpeg/libavcodec/ituh263enc.c' l='145' u='a' c='ff_h263_encode_picture_header'/>
<use f='ffmpeg/libavcodec/ituh263enc.c' l='146' u='a' c='ff_h263_encode_picture_header'/>
<use f='ffmpeg/libavcodec/ituh263enc.c' l='150' u='a' c='ff_h263_encode_picture_header'/>
<use f='ffmpeg/libavcodec/ituh263enc.c' l='151' u='a' c='ff_h263_encode_picture_header'/>
<use f='ffmpeg/libavcodec/ituh263enc.c' l='152' u='a' c='ff_h263_encode_picture_header'/>
<use f='ffmpeg/libavcodec/ituh263enc.c' l='153' u='a' c='ff_h263_encode_picture_header'/>
<use f='ffmpeg/libavcodec/ituh263enc.c' l='154' u='a' c='ff_h263_encode_picture_header'/>
<use f='ffmpeg/libavcodec/ituh263enc.c' l='155' u='a' c='ff_h263_encode_picture_header'/>
<use f='ffmpeg/libavcodec/ituh263enc.c' l='161' u='a' c='ff_h263_encode_picture_header'/>
<use f='ffmpeg/libavcodec/ituh263enc.c' l='162' u='a' c='ff_h263_encode_picture_header'/>
<use f='ffmpeg/libavcodec/ituh263enc.c' l='164' u='a' c='ff_h263_encode_picture_header'/>
<use f='ffmpeg/libavcodec/ituh263enc.c' l='166' u='a' c='ff_h263_encode_picture_header'/>
<use f='ffmpeg/libavcodec/ituh263enc.c' l='168' u='a' c='ff_h263_encode_picture_header'/>
<use f='ffmpeg/libavcodec/ituh263enc.c' l='169' u='a' c='ff_h263_encode_picture_header'/>
<use f='ffmpeg/libavcodec/ituh263enc.c' l='170' u='a' c='ff_h263_encode_picture_header'/>
<use f='ffmpeg/libavcodec/ituh263enc.c' l='171' u='a' c='ff_h263_encode_picture_header'/>
<use f='ffmpeg/libavcodec/ituh263enc.c' l='172' u='a' c='ff_h263_encode_picture_header'/>
<use f='ffmpeg/libavcodec/ituh263enc.c' l='173' u='a' c='ff_h263_encode_picture_header'/>
<use f='ffmpeg/libavcodec/ituh263enc.c' l='174' u='a' c='ff_h263_encode_picture_header'/>
<use f='ffmpeg/libavcodec/ituh263enc.c' l='175' u='a' c='ff_h263_encode_picture_header'/>
<use f='ffmpeg/libavcodec/ituh263enc.c' l='176' u='a' c='ff_h263_encode_picture_header'/>
<use f='ffmpeg/libavcodec/ituh263enc.c' l='177' u='a' c='ff_h263_encode_picture_header'/>
<use f='ffmpeg/libavcodec/ituh263enc.c' l='178' u='a' c='ff_h263_encode_picture_header'/>
<use f='ffmpeg/libavcodec/ituh263enc.c' l='179' u='a' c='ff_h263_encode_picture_header'/>
<use f='ffmpeg/libavcodec/ituh263enc.c' l='180' u='a' c='ff_h263_encode_picture_header'/>
<use f='ffmpeg/libavcodec/ituh263enc.c' l='182' u='a' c='ff_h263_encode_picture_header'/>
<use f='ffmpeg/libavcodec/ituh263enc.c' l='184' u='a' c='ff_h263_encode_picture_header'/>
<use f='ffmpeg/libavcodec/ituh263enc.c' l='185' u='a' c='ff_h263_encode_picture_header'/>
<use f='ffmpeg/libavcodec/ituh263enc.c' l='186' u='a' c='ff_h263_encode_picture_header'/>
<use f='ffmpeg/libavcodec/ituh263enc.c' l='187' u='a' c='ff_h263_encode_picture_header'/>
<use f='ffmpeg/libavcodec/ituh263enc.c' l='188' u='a' c='ff_h263_encode_picture_header'/>
<use f='ffmpeg/libavcodec/ituh263enc.c' l='191' u='a' c='ff_h263_encode_picture_header'/>
<use f='ffmpeg/libavcodec/ituh263enc.c' l='197' u='a' c='ff_h263_encode_picture_header'/>
<use f='ffmpeg/libavcodec/ituh263enc.c' l='198' u='a' c='ff_h263_encode_picture_header'/>
<use f='ffmpeg/libavcodec/ituh263enc.c' l='199' u='a' c='ff_h263_encode_picture_header'/>
<use f='ffmpeg/libavcodec/ituh263enc.c' l='200' u='a' c='ff_h263_encode_picture_header'/>
<use f='ffmpeg/libavcodec/ituh263enc.c' l='202' u='a' c='ff_h263_encode_picture_header'/>
<use f='ffmpeg/libavcodec/ituh263enc.c' l='203' u='a' c='ff_h263_encode_picture_header'/>
<use f='ffmpeg/libavcodec/ituh263enc.c' l='208' u='a' c='ff_h263_encode_picture_header'/>
<use f='ffmpeg/libavcodec/ituh263enc.c' l='209' u='a' c='ff_h263_encode_picture_header'/>
<use f='ffmpeg/libavcodec/ituh263enc.c' l='211' u='a' c='ff_h263_encode_picture_header'/>
<use f='ffmpeg/libavcodec/ituh263enc.c' l='218' u='a' c='ff_h263_encode_picture_header'/>
<use f='ffmpeg/libavcodec/ituh263enc.c' l='220' u='a' c='ff_h263_encode_picture_header'/>
<use f='ffmpeg/libavcodec/ituh263enc.c' l='222' u='a' c='ff_h263_encode_picture_header'/>
<use f='ffmpeg/libavcodec/ituh263enc.c' l='225' u='a' c='ff_h263_encode_picture_header'/>
<use f='ffmpeg/libavcodec/ituh263enc.c' l='228' u='a' c='ff_h263_encode_picture_header'/>
<use f='ffmpeg/libavcodec/ituh263enc.c' l='233' u='a' c='ff_h263_encode_picture_header'/>
<use f='ffmpeg/libavcodec/ituh263enc.c' l='242' u='a' c='ff_h263_encode_gob_header'/>
<use f='ffmpeg/libavcodec/ituh263enc.c' l='245' u='a' c='ff_h263_encode_gob_header'/>
<use f='ffmpeg/libavcodec/ituh263enc.c' l='250' u='a' c='ff_h263_encode_gob_header'/>
<use f='ffmpeg/libavcodec/ituh263enc.c' l='251' u='a' c='ff_h263_encode_gob_header'/>
<use f='ffmpeg/libavcodec/ituh263enc.c' l='252' u='a' c='ff_h263_encode_gob_header'/>
<use f='ffmpeg/libavcodec/ituh263enc.c' l='253' u='a' c='ff_h263_encode_gob_header'/>
<use f='ffmpeg/libavcodec/ituh263enc.c' l='257' u='a' c='ff_h263_encode_gob_header'/>
<use f='ffmpeg/libavcodec/ituh263enc.c' l='258' u='a' c='ff_h263_encode_gob_header'/>
<use f='ffmpeg/libavcodec/ituh263enc.c' l='259' u='a' c='ff_h263_encode_gob_header'/>
<use f='ffmpeg/libavcodec/ituh263enc.c' l='319' u='a' c='h263_encode_block'/>
<use f='ffmpeg/libavcodec/ituh263enc.c' l='321' u='a' c='h263_encode_block'/>
<use f='ffmpeg/libavcodec/ituh263enc.c' l='383' u='a' c='h263_encode_block'/>
<use f='ffmpeg/libavcodec/ituh263enc.c' l='386' u='a' c='h263_encode_block'/>
<use f='ffmpeg/libavcodec/ituh263enc.c' l='387' u='a' c='h263_encode_block'/>
<use f='ffmpeg/libavcodec/ituh263enc.c' l='392' u='a' c='h263_encode_block'/>
<use f='ffmpeg/libavcodec/ituh263enc.c' l='394' u='a' c='h263_encode_block'/>
<use f='ffmpeg/libavcodec/ituh263enc.c' l='395' u='a' c='h263_encode_block'/>
<use f='ffmpeg/libavcodec/ituh263enc.c' l='396' u='a' c='h263_encode_block'/>
<use f='ffmpeg/libavcodec/ituh263enc.c' l='399' u='a' c='h263_encode_block'/>
<use f='ffmpeg/libavcodec/ituh263enc.c' l='402' u='a' c='h263_encode_block'/>
<use f='ffmpeg/libavcodec/ituh263enc.c' l='463' u='a' c='ff_h263_encode_mb'/>
<use f='ffmpeg/libavcodec/ituh263enc.c' l='472' u='a' c='ff_h263_encode_mb'/>
<use f='ffmpeg/libavcodec/ituh263enc.c' l='480' u='a' c='ff_h263_encode_mb'/>
<use f='ffmpeg/libavcodec/ituh263enc.c' l='484' u='a' c='ff_h263_encode_mb'/>
<use f='ffmpeg/libavcodec/ituh263enc.c' l='486' u='a' c='ff_h263_encode_mb'/>
<use f='ffmpeg/libavcodec/ituh263enc.c' l='500' u='a' c='ff_h263_encode_mb'/>
<use f='ffmpeg/libavcodec/ituh263enc.c' l='501' u='a' c='ff_h263_encode_mb'/>
<use f='ffmpeg/libavcodec/ituh263enc.c' l='504' u='a' c='ff_h263_encode_mb'/>
<use f='ffmpeg/libavcodec/ituh263enc.c' l='507' u='a' c='ff_h263_encode_mb'/>
<use f='ffmpeg/libavcodec/ituh263enc.c' l='510' u='a' c='ff_h263_encode_mb'/>
<use f='ffmpeg/libavcodec/ituh263enc.c' l='512' u='a' c='ff_h263_encode_mb'/>
<use f='ffmpeg/libavcodec/ituh263enc.c' l='529' u='a' c='ff_h263_encode_mb'/>
<use f='ffmpeg/libavcodec/ituh263enc.c' l='530' u='a' c='ff_h263_encode_mb'/>
<use f='ffmpeg/libavcodec/ituh263enc.c' l='533' u='a' c='ff_h263_encode_mb'/>
<use f='ffmpeg/libavcodec/ituh263enc.c' l='600' u='a' c='ff_h263_encode_mb'/>
<use f='ffmpeg/libavcodec/ituh263enc.c' l='605' u='a' c='ff_h263_encode_mb'/>
<use f='ffmpeg/libavcodec/ituh263enc.c' l='606' u='a' c='ff_h263_encode_mb'/>
<use f='ffmpeg/libavcodec/ituh263enc.c' l='612' u='a' c='ff_h263_encode_mb'/>
<use f='ffmpeg/libavcodec/ituh263enc.c' l='615' u='a' c='ff_h263_encode_mb'/>
<use f='ffmpeg/libavcodec/ituh263enc.c' l='617' u='a' c='ff_h263_encode_mb'/>
<use f='ffmpeg/libavcodec/ituh263enc.c' l='830' u='a' c='ff_h263_encode_mba'/>
<use f='ffmpeg/libavcodec/mjpegenc.c' l='106' u='a' c='mjpeg_encode_picture_frame'/>
<use f='ffmpeg/libavcodec/mjpegenc.c' l='108' u='a' c='mjpeg_encode_picture_frame'/>
<use f='ffmpeg/libavcodec/mjpegenc.c' l='186' u='a' c='ff_mjpeg_encode_stuffing'/>
<use f='ffmpeg/libavcodec/mjpegenc.c' l='205' u='a' c='ff_mjpeg_encode_stuffing'/>
<use f='ffmpeg/libavcodec/mjpegenc.c' l='210' u='a' c='ff_mjpeg_encode_stuffing'/>
<use f='ffmpeg/libavcodec/mjpegenc.c' l='211' u='a' c='ff_mjpeg_encode_stuffing'/>
<use f='ffmpeg/libavcodec/mjpegenc.c' l='427' u='a' c='encode_block'/>
<use f='ffmpeg/libavcodec/mjpegenc.c' l='431' u='a' c='encode_block'/>
<use f='ffmpeg/libavcodec/mjpegenc.c' l='448' u='a' c='encode_block'/>
<use f='ffmpeg/libavcodec/mjpegenc.c' l='460' u='a' c='encode_block'/>
<use f='ffmpeg/libavcodec/mjpegenc.c' l='462' u='a' c='encode_block'/>
<use f='ffmpeg/libavcodec/mjpegenc.c' l='469' u='a' c='encode_block'/>
<use f='ffmpeg/libavcodec/mpeg12enc.c' l='238' u='a' c='put_header'/>
<use f='ffmpeg/libavcodec/mpeg12enc.c' l='239' u='a' c='put_header'/>
<use f='ffmpeg/libavcodec/mpeg12enc.c' l='240' u='a' c='put_header'/>
<use f='ffmpeg/libavcodec/mpeg12enc.c' l='261' u='a' c='mpeg1_encode_sequence_header'/>
<use f='ffmpeg/libavcodec/mpeg12enc.c' l='262' u='a' c='mpeg1_encode_sequence_header'/>
<use f='ffmpeg/libavcodec/mpeg12enc.c' l='279' u='a' c='mpeg1_encode_sequence_header'/>
<use f='ffmpeg/libavcodec/mpeg12enc.c' l='280' u='a' c='mpeg1_encode_sequence_header'/>
<use f='ffmpeg/libavcodec/mpeg12enc.c' l='298' u='a' c='mpeg1_encode_sequence_header'/>
<use f='ffmpeg/libavcodec/mpeg12enc.c' l='299' u='a' c='mpeg1_encode_sequence_header'/>
<use f='ffmpeg/libavcodec/mpeg12enc.c' l='300' u='a' c='mpeg1_encode_sequence_header'/>
<use f='ffmpeg/libavcodec/mpeg12enc.c' l='314' u='a' c='mpeg1_encode_sequence_header'/>
<use f='ffmpeg/libavcodec/mpeg12enc.c' l='316' u='a' c='mpeg1_encode_sequence_header'/>
<use f='ffmpeg/libavcodec/mpeg12enc.c' l='317' u='a' c='mpeg1_encode_sequence_header'/>
<use f='ffmpeg/libavcodec/mpeg12enc.c' l='326' u='a' c='mpeg1_encode_sequence_header'/>
<use f='ffmpeg/libavcodec/mpeg12enc.c' l='328' u='a' c='mpeg1_encode_sequence_header'/>
<use f='ffmpeg/libavcodec/mpeg12enc.c' l='330' u='a' c='mpeg1_encode_sequence_header'/>
<use f='ffmpeg/libavcodec/mpeg12enc.c' l='331' u='a' c='mpeg1_encode_sequence_header'/>
<use f='ffmpeg/libavcodec/mpeg12enc.c' l='333' u='a' c='mpeg1_encode_sequence_header'/>
<use f='ffmpeg/libavcodec/mpeg12enc.c' l='334' u='a' c='mpeg1_encode_sequence_header'/>
<use f='ffmpeg/libavcodec/mpeg12enc.c' l='335' u='a' c='mpeg1_encode_sequence_header'/>
<use f='ffmpeg/libavcodec/mpeg12enc.c' l='336' u='a' c='mpeg1_encode_sequence_header'/>
<use f='ffmpeg/libavcodec/mpeg12enc.c' l='337' u='a' c='mpeg1_encode_sequence_header'/>
<use f='ffmpeg/libavcodec/mpeg12enc.c' l='338' u='a' c='mpeg1_encode_sequence_header'/>
<use f='ffmpeg/libavcodec/mpeg12enc.c' l='339' u='a' c='mpeg1_encode_sequence_header'/>
<use f='ffmpeg/libavcodec/mpeg12enc.c' l='340' u='a' c='mpeg1_encode_sequence_header'/>
<use f='ffmpeg/libavcodec/mpeg12enc.c' l='341' u='a' c='mpeg1_encode_sequence_header'/>
<use f='ffmpeg/libavcodec/mpeg12enc.c' l='342' u='a' c='mpeg1_encode_sequence_header'/>
<use f='ffmpeg/libavcodec/mpeg12enc.c' l='362' u='a' c='mpeg1_encode_sequence_header'/>
<use f='ffmpeg/libavcodec/mpeg12enc.c' l='363' u='a' c='mpeg1_encode_sequence_header'/>
<use f='ffmpeg/libavcodec/mpeg12enc.c' l='364' u='a' c='mpeg1_encode_sequence_header'/>
<use f='ffmpeg/libavcodec/mpeg12enc.c' l='365' u='a' c='mpeg1_encode_sequence_header'/>
<use f='ffmpeg/libavcodec/mpeg12enc.c' l='366' u='a' c='mpeg1_encode_sequence_header'/>
<use f='ffmpeg/libavcodec/mpeg12enc.c' l='367' u='a' c='mpeg1_encode_sequence_header'/>
<use f='ffmpeg/libavcodec/mpeg12enc.c' l='368' u='a' c='mpeg1_encode_sequence_header'/>
<use f='ffmpeg/libavcodec/mpeg12enc.c' l='369' u='a' c='mpeg1_encode_sequence_header'/>
<use f='ffmpeg/libavcodec/mpeg12enc.c' l='370' u='a' c='mpeg1_encode_sequence_header'/>
<use f='ffmpeg/libavcodec/mpeg12enc.c' l='371' u='a' c='mpeg1_encode_sequence_header'/>
<use f='ffmpeg/libavcodec/mpeg12enc.c' l='376' u='a' c='mpeg1_encode_sequence_header'/>
<use f='ffmpeg/libavcodec/mpeg12enc.c' l='389' u='a' c='mpeg1_encode_sequence_header'/>
<use f='ffmpeg/libavcodec/mpeg12enc.c' l='390' u='a' c='mpeg1_encode_sequence_header'/>
<use f='ffmpeg/libavcodec/mpeg12enc.c' l='391' u='a' c='mpeg1_encode_sequence_header'/>
<use f='ffmpeg/libavcodec/mpeg12enc.c' l='392' u='a' c='mpeg1_encode_sequence_header'/>
<use f='ffmpeg/libavcodec/mpeg12enc.c' l='393' u='a' c='mpeg1_encode_sequence_header'/>
<use f='ffmpeg/libavcodec/mpeg12enc.c' l='394' u='a' c='mpeg1_encode_sequence_header'/>
<use f='ffmpeg/libavcodec/mpeg12enc.c' l='395' u='a' c='mpeg1_encode_sequence_header'/>
<use f='ffmpeg/libavcodec/mpeg12enc.c' l='402' u='a' c='encode_mb_skip_run'/>
<use f='ffmpeg/libavcodec/mpeg12enc.c' l='405' u='a' c='encode_mb_skip_run'/>
<use f='ffmpeg/libavcodec/mpeg12enc.c' l='411' u='a' c='put_qscale'/>
<use f='ffmpeg/libavcodec/mpeg12enc.c' l='419' u='a' c='ff_mpeg1_encode_slice_header'/>
<use f='ffmpeg/libavcodec/mpeg12enc.c' l='425' u='a' c='ff_mpeg1_encode_slice_header'/>
<use f='ffmpeg/libavcodec/mpeg12enc.c' l='438' u='a' c='ff_mpeg1_encode_picture_header'/>
<use f='ffmpeg/libavcodec/mpeg12enc.c' l='440' u='a' c='ff_mpeg1_encode_picture_header'/>
<use f='ffmpeg/libavcodec/mpeg12enc.c' l='442' u='m' c='ff_mpeg1_encode_picture_header'/>
<use f='ffmpeg/libavcodec/mpeg12enc.c' l='442' u='a' c='ff_mpeg1_encode_picture_header'/>
<use f='ffmpeg/libavcodec/mpeg12enc.c' l='443' u='a' c='ff_mpeg1_encode_picture_header'/>
<use f='ffmpeg/libavcodec/mpeg12enc.c' l='448' u='a' c='ff_mpeg1_encode_picture_header'/>
<use f='ffmpeg/libavcodec/mpeg12enc.c' l='450' u='a' c='ff_mpeg1_encode_picture_header'/>
<use f='ffmpeg/libavcodec/mpeg12enc.c' l='452' u='a' c='ff_mpeg1_encode_picture_header'/>
<use f='ffmpeg/libavcodec/mpeg12enc.c' l='457' u='a' c='ff_mpeg1_encode_picture_header'/>
<use f='ffmpeg/libavcodec/mpeg12enc.c' l='459' u='a' c='ff_mpeg1_encode_picture_header'/>
<use f='ffmpeg/libavcodec/mpeg12enc.c' l='461' u='a' c='ff_mpeg1_encode_picture_header'/>
<use f='ffmpeg/libavcodec/mpeg12enc.c' l='464' u='a' c='ff_mpeg1_encode_picture_header'/>
<use f='ffmpeg/libavcodec/mpeg12enc.c' l='469' u='a' c='ff_mpeg1_encode_picture_header'/>
<use f='ffmpeg/libavcodec/mpeg12enc.c' l='472' u='a' c='ff_mpeg1_encode_picture_header'/>
<use f='ffmpeg/libavcodec/mpeg12enc.c' l='473' u='a' c='ff_mpeg1_encode_picture_header'/>
<use f='ffmpeg/libavcodec/mpeg12enc.c' l='475' u='a' c='ff_mpeg1_encode_picture_header'/>
<use f='ffmpeg/libavcodec/mpeg12enc.c' l='478' u='a' c='ff_mpeg1_encode_picture_header'/>
<use f='ffmpeg/libavcodec/mpeg12enc.c' l='479' u='a' c='ff_mpeg1_encode_picture_header'/>
<use f='ffmpeg/libavcodec/mpeg12enc.c' l='481' u='a' c='ff_mpeg1_encode_picture_header'/>
<use f='ffmpeg/libavcodec/mpeg12enc.c' l='483' u='a' c='ff_mpeg1_encode_picture_header'/>
<use f='ffmpeg/libavcodec/mpeg12enc.c' l='486' u='a' c='ff_mpeg1_encode_picture_header'/>
<use f='ffmpeg/libavcodec/mpeg12enc.c' l='488' u='a' c='ff_mpeg1_encode_picture_header'/>
<use f='ffmpeg/libavcodec/mpeg12enc.c' l='490' u='a' c='ff_mpeg1_encode_picture_header'/>
<use f='ffmpeg/libavcodec/mpeg12enc.c' l='494' u='a' c='ff_mpeg1_encode_picture_header'/>
<use f='ffmpeg/libavcodec/mpeg12enc.c' l='495' u='a' c='ff_mpeg1_encode_picture_header'/>
<use f='ffmpeg/libavcodec/mpeg12enc.c' l='496' u='a' c='ff_mpeg1_encode_picture_header'/>
<use f='ffmpeg/libavcodec/mpeg12enc.c' l='497' u='a' c='ff_mpeg1_encode_picture_header'/>
<use f='ffmpeg/libavcodec/mpeg12enc.c' l='498' u='a' c='ff_mpeg1_encode_picture_header'/>
<use f='ffmpeg/libavcodec/mpeg12enc.c' l='499' u='a' c='ff_mpeg1_encode_picture_header'/>
<use f='ffmpeg/libavcodec/mpeg12enc.c' l='502' u='a' c='ff_mpeg1_encode_picture_header'/>
<use f='ffmpeg/libavcodec/mpeg12enc.c' l='504' u='a' c='ff_mpeg1_encode_picture_header'/>
<use f='ffmpeg/libavcodec/mpeg12enc.c' l='505' u='a' c='ff_mpeg1_encode_picture_header'/>
<use f='ffmpeg/libavcodec/mpeg12enc.c' l='512' u='a' c='ff_mpeg1_encode_picture_header'/>
<use f='ffmpeg/libavcodec/mpeg12enc.c' l='540' u='a' c='ff_mpeg1_encode_picture_header'/>
<use f='ffmpeg/libavcodec/mpeg12enc.c' l='541' u='a' c='ff_mpeg1_encode_picture_header'/>
<use f='ffmpeg/libavcodec/mpeg12enc.c' l='542' u='a' c='ff_mpeg1_encode_picture_header'/>
<use f='ffmpeg/libavcodec/mpeg12enc.c' l='543' u='a' c='ff_mpeg1_encode_picture_header'/>
<use f='ffmpeg/libavcodec/mpeg12enc.c' l='544' u='a' c='ff_mpeg1_encode_picture_header'/>
<use f='ffmpeg/libavcodec/mpeg12enc.c' l='546' u='a' c='ff_mpeg1_encode_picture_header'/>
<use f='ffmpeg/libavcodec/mpeg12enc.c' l='547' u='a' c='ff_mpeg1_encode_picture_header'/>
<use f='ffmpeg/libavcodec/mpeg12enc.c' l='548' u='a' c='ff_mpeg1_encode_picture_header'/>
<use f='ffmpeg/libavcodec/mpeg12enc.c' l='549' u='a' c='ff_mpeg1_encode_picture_header'/>
<use f='ffmpeg/libavcodec/mpeg12enc.c' l='562' u='a' c='ff_mpeg1_encode_picture_header'/>
<use f='ffmpeg/libavcodec/mpeg12enc.c' l='563' u='a' c='ff_mpeg1_encode_picture_header'/>
<use f='ffmpeg/libavcodec/mpeg12enc.c' l='564' u='a' c='ff_mpeg1_encode_picture_header'/>
<use f='ffmpeg/libavcodec/mpeg12enc.c' l='565' u='a' c='ff_mpeg1_encode_picture_header'/>
<use f='ffmpeg/libavcodec/mpeg12enc.c' l='566' u='a' c='ff_mpeg1_encode_picture_header'/>
<use f='ffmpeg/libavcodec/mpeg12enc.c' l='567' u='a' c='ff_mpeg1_encode_picture_header'/>
<use f='ffmpeg/libavcodec/mpeg12enc.c' l='569' u='a' c='ff_mpeg1_encode_picture_header'/>
<use f='ffmpeg/libavcodec/mpeg12enc.c' l='572' u='a' c='ff_mpeg1_encode_picture_header'/>
<use f='ffmpeg/libavcodec/mpeg12enc.c' l='574' u='a' c='ff_mpeg1_encode_picture_header'/>
<use f='ffmpeg/libavcodec/mpeg12enc.c' l='590' u='a' c='put_mb_modes'/>
<use f='ffmpeg/libavcodec/mpeg12enc.c' l='594' u='a' c='put_mb_modes'/>
<use f='ffmpeg/libavcodec/mpeg12enc.c' l='595' u='a' c='put_mb_modes'/>
<use f='ffmpeg/libavcodec/mpeg12enc.c' l='604' u='a' c='mpeg1_encode_motion'/>
<use f='ffmpeg/libavcodec/mpeg12enc.c' l='629' u='a' c='mpeg1_encode_motion'/>
<use f='ffmpeg/libavcodec/mpeg12enc.c' l='633' u='a' c='mpeg1_encode_motion'/>
<use f='ffmpeg/libavcodec/mpeg12enc.c' l='635' u='a' c='mpeg1_encode_motion'/>
<use f='ffmpeg/libavcodec/mpeg12enc.c' l='652' u='a' c='encode_dc'/>
<use f='ffmpeg/libavcodec/mpeg12enc.c' l='657' u='a' c='encode_dc'/>
<use f='ffmpeg/libavcodec/mpeg12enc.c' l='663' u='a' c='encode_dc'/>
<use f='ffmpeg/libavcodec/mpeg12enc.c' l='667' u='a' c='encode_dc'/>
<use f='ffmpeg/libavcodec/mpeg12enc.c' l='697' u='a' c='mpeg1_encode_block'/>
<use f='ffmpeg/libavcodec/mpeg12enc.c' l='725' u='a' c='mpeg1_encode_block'/>
<use f='ffmpeg/libavcodec/mpeg12enc.c' l='729' u='a' c='mpeg1_encode_block'/>
<use f='ffmpeg/libavcodec/mpeg12enc.c' l='731' u='a' c='mpeg1_encode_block'/>
<use f='ffmpeg/libavcodec/mpeg12enc.c' l='734' u='a' c='mpeg1_encode_block'/>
<use f='ffmpeg/libavcodec/mpeg12enc.c' l='737' u='a' c='mpeg1_encode_block'/>
<use f='ffmpeg/libavcodec/mpeg12enc.c' l='739' u='a' c='mpeg1_encode_block'/>
<use f='ffmpeg/libavcodec/mpeg12enc.c' l='742' u='a' c='mpeg1_encode_block'/>
<use f='ffmpeg/libavcodec/mpeg12enc.c' l='749' u='a' c='mpeg1_encode_block'/>
<use f='ffmpeg/libavcodec/mpeg12enc.c' l='853' u='a' c='mpeg1_encode_mb_internal'/>
<use f='ffmpeg/libavcodec/mpeg12enc.c' l='855' u='a' c='mpeg1_encode_mb_internal'/>
<use f='ffmpeg/libavcodec/mpeg12enc.c' l='881' u='a' c='mpeg1_encode_mb_internal'/>
<use f='ffmpeg/libavcodec/mpeg12enc.c' l='882' u='a' c='mpeg1_encode_mb_internal'/>
<use f='ffmpeg/libavcodec/mpeg12enc.c' l='887' u='a' c='mpeg1_encode_mb_internal'/>
<use f='ffmpeg/libavcodec/mpeg12enc.c' l='901' u='a' c='mpeg1_encode_mb_internal'/>
<use f='ffmpeg/libavcodec/mpeg12enc.c' l='905' u='a' c='mpeg1_encode_mb_internal'/>
<use f='ffmpeg/libavcodec/mpeg12enc.c' l='908' u='a' c='mpeg1_encode_mb_internal'/>
<use f='ffmpeg/libavcodec/mpeg12enc.c' l='925' u='a' c='mpeg1_encode_mb_internal'/>
<use f='ffmpeg/libavcodec/mpeg12enc.c' l='927' u='a' c='mpeg1_encode_mb_internal'/>
<use f='ffmpeg/libavcodec/mpeg12enc.c' l='971' u='a' c='mpeg1_encode_mb_internal'/>
<use f='ffmpeg/libavcodec/mpeg12enc.c' l='972' u='a' c='mpeg1_encode_mb_internal'/>
<use f='ffmpeg/libavcodec/mpeg12enc.c' l='978' u='a' c='mpeg1_encode_mb_internal'/>
<use f='ffmpeg/libavcodec/mpeg12enc.c' l='992' u='a' c='mpeg1_encode_mb_internal'/>
<use f='ffmpeg/libavcodec/mpeg12enc.c' l='1008' u='a' c='mpeg1_encode_mb_internal'/>
<use f='ffmpeg/libavcodec/mpeg12enc.c' l='1012' u='a' c='mpeg1_encode_mb_internal'/>
<use f='ffmpeg/libavcodec/mpeg12enc.c' l='1015' u='a' c='mpeg1_encode_mb_internal'/>
<use f='ffmpeg/libavcodec/mpeg4videoenc.c' l='408' u='a' c='mpeg4_encode_blocks'/>
<use f='ffmpeg/libavcodec/mpeg4videoenc.c' l='420' u='a' c='mpeg4_encode_blocks'/>
<use f='ffmpeg/libavcodec/mpeg4videoenc.c' l='480' u='a' c='ff_mpeg4_encode_mb'/>
<use f='ffmpeg/libavcodec/mpeg4videoenc.c' l='481' u='a' c='ff_mpeg4_encode_mb'/>
<use f='ffmpeg/libavcodec/mpeg4videoenc.c' l='482' u='a' c='ff_mpeg4_encode_mb'/>
<use f='ffmpeg/libavcodec/mpeg4videoenc.c' l='525' u='a' c='ff_mpeg4_encode_mb'/>
<use f='ffmpeg/libavcodec/mpeg4videoenc.c' l='535' u='a' c='ff_mpeg4_encode_mb'/>
<use f='ffmpeg/libavcodec/mpeg4videoenc.c' l='536' u='a' c='ff_mpeg4_encode_mb'/>
<use f='ffmpeg/libavcodec/mpeg4videoenc.c' l='537' u='a' c='ff_mpeg4_encode_mb'/>
<use f='ffmpeg/libavcodec/mpeg4videoenc.c' l='539' u='a' c='ff_mpeg4_encode_mb'/>
<use f='ffmpeg/libavcodec/mpeg4videoenc.c' l='543' u='a' c='ff_mpeg4_encode_mb'/>
<use f='ffmpeg/libavcodec/mpeg4videoenc.c' l='545' u='a' c='ff_mpeg4_encode_mb'/>
<use f='ffmpeg/libavcodec/mpeg4videoenc.c' l='551' u='a' c='ff_mpeg4_encode_mb'/>
<use f='ffmpeg/libavcodec/mpeg4videoenc.c' l='553' u='a' c='ff_mpeg4_encode_mb'/>
<use f='ffmpeg/libavcodec/mpeg4videoenc.c' l='591' u='a' c='ff_mpeg4_encode_mb'/>
<use f='ffmpeg/libavcodec/mpeg4videoenc.c' l='592' u='a' c='ff_mpeg4_encode_mb'/>
<use f='ffmpeg/libavcodec/mpeg4videoenc.c' l='595' u='a' c='ff_mpeg4_encode_mb'/>
<use f='ffmpeg/libavcodec/mpeg4videoenc.c' l='596' u='a' c='ff_mpeg4_encode_mb'/>
<use f='ffmpeg/libavcodec/mpeg4videoenc.c' l='626' u='a' c='ff_mpeg4_encode_mb'/>
<use f='ffmpeg/libavcodec/mpeg4videoenc.c' l='686' u='a' c='ff_mpeg4_encode_mb'/>
<use f='ffmpeg/libavcodec/mpeg4videoenc.c' l='698' u='a' c='ff_mpeg4_encode_mb'/>
<use f='ffmpeg/libavcodec/mpeg4videoenc.c' l='705' u='a' c='ff_mpeg4_encode_mb'/>
<use f='ffmpeg/libavcodec/mpeg4videoenc.c' l='732' u='a' c='ff_mpeg4_encode_mb'/>
<use f='ffmpeg/libavcodec/mpeg4videoenc.c' l='752' u='a' c='ff_mpeg4_encode_mb'/>
<use f='ffmpeg/libavcodec/mpeg4videoenc.c' l='753' u='a' c='ff_mpeg4_encode_mb'/>
<use f='ffmpeg/libavcodec/mpeg4videoenc.c' l='765' u='a' c='ff_mpeg4_encode_mb'/>
<use f='ffmpeg/libavcodec/mpeg4videoenc.c' l='825' u='a' c='ff_mpeg4_encode_mb'/>
<use f='ffmpeg/libavcodec/mpeg4videoenc.c' l='831' u='a' c='ff_mpeg4_encode_mb'/>
<use f='ffmpeg/libavcodec/mpeg4videoenc.c' l='832' u='a' c='ff_mpeg4_encode_mb'/>
<use f='ffmpeg/libavcodec/mpeg4videoenc.c' l='889' u='a' c='mpeg4_encode_gop_header'/>
<use f='ffmpeg/libavcodec/mpeg4videoenc.c' l='890' u='a' c='mpeg4_encode_gop_header'/>
<use f='ffmpeg/libavcodec/mpeg4videoenc.c' l='903' u='a' c='mpeg4_encode_gop_header'/>
<use f='ffmpeg/libavcodec/mpeg4videoenc.c' l='904' u='a' c='mpeg4_encode_gop_header'/>
<use f='ffmpeg/libavcodec/mpeg4videoenc.c' l='905' u='a' c='mpeg4_encode_gop_header'/>
<use f='ffmpeg/libavcodec/mpeg4videoenc.c' l='906' u='a' c='mpeg4_encode_gop_header'/>
<use f='ffmpeg/libavcodec/mpeg4videoenc.c' l='908' u='a' c='mpeg4_encode_gop_header'/>
<use f='ffmpeg/libavcodec/mpeg4videoenc.c' l='909' u='a' c='mpeg4_encode_gop_header'/>
<use f='ffmpeg/libavcodec/mpeg4videoenc.c' l='911' u='a' c='mpeg4_encode_gop_header'/>
<use f='ffmpeg/libavcodec/mpeg4videoenc.c' l='939' u='a' c='mpeg4_encode_visual_object_header'/>
<use f='ffmpeg/libavcodec/mpeg4videoenc.c' l='940' u='a' c='mpeg4_encode_visual_object_header'/>
<use f='ffmpeg/libavcodec/mpeg4videoenc.c' l='942' u='a' c='mpeg4_encode_visual_object_header'/>
<use f='ffmpeg/libavcodec/mpeg4videoenc.c' l='944' u='a' c='mpeg4_encode_visual_object_header'/>
<use f='ffmpeg/libavcodec/mpeg4videoenc.c' l='945' u='a' c='mpeg4_encode_visual_object_header'/>
<use f='ffmpeg/libavcodec/mpeg4videoenc.c' l='947' u='a' c='mpeg4_encode_visual_object_header'/>
<use f='ffmpeg/libavcodec/mpeg4videoenc.c' l='948' u='a' c='mpeg4_encode_visual_object_header'/>
<use f='ffmpeg/libavcodec/mpeg4videoenc.c' l='949' u='a' c='mpeg4_encode_visual_object_header'/>
<use f='ffmpeg/libavcodec/mpeg4videoenc.c' l='951' u='a' c='mpeg4_encode_visual_object_header'/>
<use f='ffmpeg/libavcodec/mpeg4videoenc.c' l='953' u='a' c='mpeg4_encode_visual_object_header'/>
<use f='ffmpeg/libavcodec/mpeg4videoenc.c' l='955' u='a' c='mpeg4_encode_visual_object_header'/>
<use f='ffmpeg/libavcodec/mpeg4videoenc.c' l='972' u='a' c='mpeg4_encode_vol_header'/>
<use f='ffmpeg/libavcodec/mpeg4videoenc.c' l='973' u='a' c='mpeg4_encode_vol_header'/>
<use f='ffmpeg/libavcodec/mpeg4videoenc.c' l='974' u='a' c='mpeg4_encode_vol_header'/>
<use f='ffmpeg/libavcodec/mpeg4videoenc.c' l='975' u='a' c='mpeg4_encode_vol_header'/>
<use f='ffmpeg/libavcodec/mpeg4videoenc.c' l='977' u='a' c='mpeg4_encode_vol_header'/>
<use f='ffmpeg/libavcodec/mpeg4videoenc.c' l='978' u='a' c='mpeg4_encode_vol_header'/>
<use f='ffmpeg/libavcodec/mpeg4videoenc.c' l='980' u='a' c='mpeg4_encode_vol_header'/>
<use f='ffmpeg/libavcodec/mpeg4videoenc.c' l='982' u='a' c='mpeg4_encode_vol_header'/>
<use f='ffmpeg/libavcodec/mpeg4videoenc.c' l='983' u='a' c='mpeg4_encode_vol_header'/>
<use f='ffmpeg/libavcodec/mpeg4videoenc.c' l='984' u='a' c='mpeg4_encode_vol_header'/>
<use f='ffmpeg/libavcodec/mpeg4videoenc.c' l='989' u='a' c='mpeg4_encode_vol_header'/>
<use f='ffmpeg/libavcodec/mpeg4videoenc.c' l='993' u='a' c='mpeg4_encode_vol_header'/>
<use f='ffmpeg/libavcodec/mpeg4videoenc.c' l='994' u='a' c='mpeg4_encode_vol_header'/>
<use f='ffmpeg/libavcodec/mpeg4videoenc.c' l='998' u='a' c='mpeg4_encode_vol_header'/>
<use f='ffmpeg/libavcodec/mpeg4videoenc.c' l='1000' u='a' c='mpeg4_encode_vol_header'/>
<use f='ffmpeg/libavcodec/mpeg4videoenc.c' l='1001' u='a' c='mpeg4_encode_vol_header'/>
<use f='ffmpeg/libavcodec/mpeg4videoenc.c' l='1002' u='a' c='mpeg4_encode_vol_header'/>
<use f='ffmpeg/libavcodec/mpeg4videoenc.c' l='1003' u='a' c='mpeg4_encode_vol_header'/>
<use f='ffmpeg/libavcodec/mpeg4videoenc.c' l='1006' u='a' c='mpeg4_encode_vol_header'/>
<use f='ffmpeg/libavcodec/mpeg4videoenc.c' l='1007' u='a' c='mpeg4_encode_vol_header'/>
<use f='ffmpeg/libavcodec/mpeg4videoenc.c' l='1009' u='a' c='mpeg4_encode_vol_header'/>
<use f='ffmpeg/libavcodec/mpeg4videoenc.c' l='1012' u='a' c='mpeg4_encode_vol_header'/>
<use f='ffmpeg/libavcodec/mpeg4videoenc.c' l='1013' u='a' c='mpeg4_encode_vol_header'/>
<use f='ffmpeg/libavcodec/mpeg4videoenc.c' l='1014' u='a' c='mpeg4_encode_vol_header'/>
<use f='ffmpeg/libavcodec/mpeg4videoenc.c' l='1015' u='a' c='mpeg4_encode_vol_header'/>
<use f='ffmpeg/libavcodec/mpeg4videoenc.c' l='1016' u='a' c='mpeg4_encode_vol_header'/>
<use f='ffmpeg/libavcodec/mpeg4videoenc.c' l='1017' u='a' c='mpeg4_encode_vol_header'/>
<use f='ffmpeg/libavcodec/mpeg4videoenc.c' l='1018' u='a' c='mpeg4_encode_vol_header'/>
<use f='ffmpeg/libavcodec/mpeg4videoenc.c' l='1019' u='a' c='mpeg4_encode_vol_header'/>
<use f='ffmpeg/libavcodec/mpeg4videoenc.c' l='1020' u='a' c='mpeg4_encode_vol_header'/>
<use f='ffmpeg/libavcodec/mpeg4videoenc.c' l='1022' u='a' c='mpeg4_encode_vol_header'/>
<use f='ffmpeg/libavcodec/mpeg4videoenc.c' l='1024' u='a' c='mpeg4_encode_vol_header'/>
<use f='ffmpeg/libavcodec/mpeg4videoenc.c' l='1026' u='a' c='mpeg4_encode_vol_header'/>
<use f='ffmpeg/libavcodec/mpeg4videoenc.c' l='1027' u='a' c='mpeg4_encode_vol_header'/>
<use f='ffmpeg/libavcodec/mpeg4videoenc.c' l='1030' u='a' c='mpeg4_encode_vol_header'/>
<use f='ffmpeg/libavcodec/mpeg4videoenc.c' l='1031' u='a' c='mpeg4_encode_vol_header'/>
<use f='ffmpeg/libavcodec/mpeg4videoenc.c' l='1035' u='a' c='mpeg4_encode_vol_header'/>
<use f='ffmpeg/libavcodec/mpeg4videoenc.c' l='1036' u='a' c='mpeg4_encode_vol_header'/>
<use f='ffmpeg/libavcodec/mpeg4videoenc.c' l='1037' u='a' c='mpeg4_encode_vol_header'/>
<use f='ffmpeg/libavcodec/mpeg4videoenc.c' l='1038' u='a' c='mpeg4_encode_vol_header'/>
<use f='ffmpeg/libavcodec/mpeg4videoenc.c' l='1040' u='a' c='mpeg4_encode_vol_header'/>
<use f='ffmpeg/libavcodec/mpeg4videoenc.c' l='1043' u='a' c='mpeg4_encode_vol_header'/>
<use f='ffmpeg/libavcodec/mpeg4videoenc.c' l='1044' u='a' c='mpeg4_encode_vol_header'/>
<use f='ffmpeg/libavcodec/mpeg4videoenc.c' l='1046' u='a' c='mpeg4_encode_vol_header'/>
<use f='ffmpeg/libavcodec/mpeg4videoenc.c' l='1048' u='a' c='mpeg4_encode_vol_header'/>
<use f='ffmpeg/libavcodec/mpeg4videoenc.c' l='1052' u='a' c='mpeg4_encode_vol_header'/>
<use f='ffmpeg/libavcodec/mpeg4videoenc.c' l='1053' u='a' c='mpeg4_encode_vol_header'/>
<use f='ffmpeg/libavcodec/mpeg4videoenc.c' l='1054' u='a' c='mpeg4_encode_vol_header'/>
<use f='ffmpeg/libavcodec/mpeg4videoenc.c' l='1077' u='a' c='ff_mpeg4_encode_picture_header'/>
<use f='ffmpeg/libavcodec/mpeg4videoenc.c' l='1078' u='a' c='ff_mpeg4_encode_picture_header'/>
<use f='ffmpeg/libavcodec/mpeg4videoenc.c' l='1079' u='a' c='ff_mpeg4_encode_picture_header'/>
<use f='ffmpeg/libavcodec/mpeg4videoenc.c' l='1091' u='a' c='ff_mpeg4_encode_picture_header'/>
<use f='ffmpeg/libavcodec/mpeg4videoenc.c' l='1093' u='a' c='ff_mpeg4_encode_picture_header'/>
<use f='ffmpeg/libavcodec/mpeg4videoenc.c' l='1095' u='a' c='ff_mpeg4_encode_picture_header'/>
<use f='ffmpeg/libavcodec/mpeg4videoenc.c' l='1096' u='a' c='ff_mpeg4_encode_picture_header'/>
<use f='ffmpeg/libavcodec/mpeg4videoenc.c' l='1097' u='a' c='ff_mpeg4_encode_picture_header'/>
<use f='ffmpeg/libavcodec/mpeg4videoenc.c' l='1098' u='a' c='ff_mpeg4_encode_picture_header'/>
<use f='ffmpeg/libavcodec/mpeg4videoenc.c' l='1100' u='a' c='ff_mpeg4_encode_picture_header'/>
<use f='ffmpeg/libavcodec/mpeg4videoenc.c' l='1102' u='a' c='ff_mpeg4_encode_picture_header'/>
<use f='ffmpeg/libavcodec/mpeg4videoenc.c' l='1104' u='a' c='ff_mpeg4_encode_picture_header'/>
<use f='ffmpeg/libavcodec/mpeg4videoenc.c' l='1105' u='a' c='ff_mpeg4_encode_picture_header'/>
<use f='ffmpeg/libavcodec/mpeg4videoenc.c' l='1109' u='a' c='ff_mpeg4_encode_picture_header'/>
<use f='ffmpeg/libavcodec/mpeg4videoenc.c' l='1112' u='a' c='ff_mpeg4_encode_picture_header'/>
<use f='ffmpeg/libavcodec/mpeg4videoenc.c' l='1114' u='a' c='ff_mpeg4_encode_picture_header'/>
<use f='ffmpeg/libavcodec/mpeg4videoenc.c' l='1309' u='a' c='encode_init'/>
<use f='ffmpeg/libavcodec/mpeg4videoenc.c' l='1316' u='a' c='encode_init'/>
<use f='ffmpeg/libavcodec/mpeg4videoenc.c' l='1317' u='a' c='encode_init'/>
<use f='ffmpeg/libavcodec/mpeg4videoenc.c' l='1324' u='a' c='ff_mpeg4_init_partitions'/>
<use f='ffmpeg/libavcodec/mpeg4videoenc.c' l='1325' u='m' c='ff_mpeg4_init_partitions'/>
<use f='ffmpeg/libavcodec/mpeg4videoenc.c' l='1330' u='a' c='ff_mpeg4_init_partitions'/>
<use f='ffmpeg/libavcodec/mpeg4videoenc.c' l='1339' u='a' c='ff_mpeg4_merge_partitions'/>
<use f='ffmpeg/libavcodec/mpeg4videoenc.c' l='1342' u='a' c='ff_mpeg4_merge_partitions'/>
<use f='ffmpeg/libavcodec/mpeg4videoenc.c' l='1346' u='a' c='ff_mpeg4_merge_partitions'/>
<use f='ffmpeg/libavcodec/mpeg4videoenc.c' l='1355' u='a' c='ff_mpeg4_merge_partitions'/>
<use f='ffmpeg/libavcodec/mpeg4videoenc.c' l='1355' u='m' c='ff_mpeg4_merge_partitions'/>
<use f='ffmpeg/libavcodec/mpeg4videoenc.c' l='1356' u='a' c='ff_mpeg4_merge_partitions'/>
<use f='ffmpeg/libavcodec/mpeg4videoenc.c' l='1357' u='a' c='ff_mpeg4_merge_partitions'/>
<use f='ffmpeg/libavcodec/mpeg4videoenc.c' l='1358' u='a' c='ff_mpeg4_merge_partitions'/>
<use f='ffmpeg/libavcodec/mpeg4videoenc.c' l='1365' u='a' c='ff_mpeg4_encode_video_packet_header'/>
<use f='ffmpeg/libavcodec/mpeg4videoenc.c' l='1366' u='a' c='ff_mpeg4_encode_video_packet_header'/>
<use f='ffmpeg/libavcodec/mpeg4videoenc.c' l='1368' u='a' c='ff_mpeg4_encode_video_packet_header'/>
<use f='ffmpeg/libavcodec/mpeg4videoenc.c' l='1369' u='a' c='ff_mpeg4_encode_video_packet_header'/>
<use f='ffmpeg/libavcodec/mpeg4videoenc.c' l='1370' u='a' c='ff_mpeg4_encode_video_packet_header'/>
<use f='ffmpeg/libavcodec/mpegvideo.c' l='488' u='w' c='backup_duplicate_context'/>
<use f='ffmpeg/libavcodec/mpegvideo.c' l='488' u='r' c='backup_duplicate_context'/>
<use f='ffmpeg/libavcodec/mpegvideo_enc.c' l='1895' u='a' c='ff_mpv_encode_picture'/>
<use f='ffmpeg/libavcodec/mpegvideo_enc.c' l='1906' u='m' c='ff_mpv_encode_picture'/>
<use f='ffmpeg/libavcodec/mpegvideo_enc.c' l='1907' u='m' c='ff_mpv_encode_picture'/>
<use f='ffmpeg/libavcodec/mpegvideo_enc.c' l='1930' u='a' c='ff_mpv_encode_picture'/>
<use f='ffmpeg/libavcodec/mpegvideo_enc.c' l='1938' u='a' c='ff_mpv_encode_picture'/>
<use f='ffmpeg/libavcodec/mpegvideo_enc.c' l='1963' u='a' c='ff_mpv_encode_picture'/>
<use f='ffmpeg/libavcodec/mpegvideo_enc.c' l='1990' u='a' c='ff_mpv_encode_picture'/>
<use f='ffmpeg/libavcodec/mpegvideo_enc.c' l='1991' u='a' c='ff_mpv_encode_picture'/>
<use f='ffmpeg/libavcodec/mpegvideo_enc.c' l='1996' u='m' c='ff_mpv_encode_picture'/>
<use f='ffmpeg/libavcodec/mpegvideo_enc.c' l='1996' u='m' c='ff_mpv_encode_picture'/>
<use f='ffmpeg/libavcodec/mpegvideo_enc.c' l='1996' u='a' c='ff_mpv_encode_picture'/>
<use f='ffmpeg/libavcodec/mpegvideo_enc.c' l='2006' u='a' c='ff_mpv_encode_picture'/>
<use f='ffmpeg/libavcodec/mpegvideo_enc.c' l='2010' u='a' c='ff_mpv_encode_picture'/>
<use f='ffmpeg/libavcodec/mpegvideo_enc.c' l='2011' u='a' c='ff_mpv_encode_picture'/>
<use f='ffmpeg/libavcodec/mpegvideo_enc.c' l='2014' u='a' c='ff_mpv_encode_picture'/>
<use f='ffmpeg/libavcodec/mpegvideo_enc.c' l='2020' u='a' c='ff_mpv_encode_picture'/>
<use f='ffmpeg/libavcodec/mpegvideo_enc.c' l='2021' u='a' c='ff_mpv_encode_picture'/>
<use f='ffmpeg/libavcodec/mpegvideo_enc.c' l='2037' u='m' c='ff_mpv_encode_picture'/>
<use f='ffmpeg/libavcodec/mpegvideo_enc.c' l='2674' u='w' c='copy_context_after_encode'/>
<use f='ffmpeg/libavcodec/mpegvideo_enc.c' l='2674' u='r' c='copy_context_after_encode'/>
<use f='ffmpeg/libavcodec/mpegvideo_enc.c' l='2698' u='w' c='encode_mb_hq'/>
<use f='ffmpeg/libavcodec/mpegvideo_enc.c' l='2714' u='a' c='encode_mb_hq'/>
<use f='ffmpeg/libavcodec/mpegvideo_enc.c' l='2856' u='a' c='write_slice_end'/>
<use f='ffmpeg/libavcodec/mpegvideo_enc.c' l='2863' u='a' c='write_slice_end'/>
<use f='ffmpeg/libavcodec/mpegvideo_enc.c' l='2872' u='a' c='write_mb_info'/>
<use f='ffmpeg/libavcodec/mpegvideo_enc.c' l='2893' u='a' c='update_mb_info'/>
<use f='ffmpeg/libavcodec/mpegvideo_enc.c' l='2898' u='a' c='update_mb_info'/>
<use f='ffmpeg/libavcodec/mpegvideo_enc.c' l='2906' u='a' c='update_mb_info'/>
<use f='ffmpeg/libavcodec/mpegvideo_enc.c' l='2914' u='m' c='ff_mpv_reallocate_putbitbuffer'/>
<use f='ffmpeg/libavcodec/mpegvideo_enc.c' l='2914' u='m' c='ff_mpv_reallocate_putbitbuffer'/>
<use f='ffmpeg/libavcodec/mpegvideo_enc.c' l='2914' u='a' c='ff_mpv_reallocate_putbitbuffer'/>
<use f='ffmpeg/libavcodec/mpegvideo_enc.c' l='2916' u='m' c='ff_mpv_reallocate_putbitbuffer'/>
<use f='ffmpeg/libavcodec/mpegvideo_enc.c' l='2917' u='m' c='ff_mpv_reallocate_putbitbuffer'/>
<use f='ffmpeg/libavcodec/mpegvideo_enc.c' l='2918' u='m' c='ff_mpv_reallocate_putbitbuffer'/>
<use f='ffmpeg/libavcodec/mpegvideo_enc.c' l='2939' u='a' c='ff_mpv_reallocate_putbitbuffer'/>
<use f='ffmpeg/libavcodec/mpegvideo_enc.c' l='2940' u='m' c='ff_mpv_reallocate_putbitbuffer'/>
<use f='ffmpeg/libavcodec/mpegvideo_enc.c' l='2941' u='m' c='ff_mpv_reallocate_putbitbuffer'/>
<use f='ffmpeg/libavcodec/mpegvideo_enc.c' l='2943' u='m' c='ff_mpv_reallocate_putbitbuffer'/>
<use f='ffmpeg/libavcodec/mpegvideo_enc.c' l='2943' u='m' c='ff_mpv_reallocate_putbitbuffer'/>
<use f='ffmpeg/libavcodec/mpegvideo_enc.c' l='2943' u='a' c='ff_mpv_reallocate_putbitbuffer'/>
<use f='ffmpeg/libavcodec/mpegvideo_enc.c' l='2965' u='a' c='encode_thread'/>
<use f='ffmpeg/libavcodec/mpegvideo_enc.c' l='3008' u='m' c='encode_thread'/>
<use f='ffmpeg/libavcodec/mpegvideo_enc.c' l='3035' u='m' c='encode_thread'/>
<use f='ffmpeg/libavcodec/mpegvideo_enc.c' l='3035' u='m' c='encode_thread'/>
<use f='ffmpeg/libavcodec/mpegvideo_enc.c' l='3035' u='a' c='encode_thread'/>
<use f='ffmpeg/libavcodec/mpegvideo_enc.c' l='3061' u='a' c='encode_thread'/>
<use f='ffmpeg/libavcodec/mpegvideo_enc.c' l='3061' u='m' c='encode_thread'/>
<use f='ffmpeg/libavcodec/mpegvideo_enc.c' l='3095' u='a' c='encode_thread'/>
<use f='ffmpeg/libavcodec/mpegvideo_enc.c' l='3098' u='a' c='encode_thread'/>
<use f='ffmpeg/libavcodec/mpegvideo_enc.c' l='3102' u='m' c='encode_thread'/>
<use f='ffmpeg/libavcodec/mpegvideo_enc.c' l='3139' u='a' c='encode_thread'/>
<use f='ffmpeg/libavcodec/mpegvideo_enc.c' l='3166' u='w' c='encode_thread'/>
<use f='ffmpeg/libavcodec/mpegvideo_enc.c' l='3166' u='r' c='encode_thread'/>
<use f='ffmpeg/libavcodec/mpegvideo_enc.c' l='3401' u='a' c='encode_thread'/>
<use f='ffmpeg/libavcodec/mpegvideo_enc.c' l='3402' u='a' c='encode_thread'/>
<use f='ffmpeg/libavcodec/mpegvideo_enc.c' l='3403' u='a' c='encode_thread'/>
<use f='ffmpeg/libavcodec/mpegvideo_enc.c' l='3404' u='w' c='encode_thread'/>
<use f='ffmpeg/libavcodec/mpegvideo_enc.c' l='3404' u='r' c='encode_thread'/>
<use f='ffmpeg/libavcodec/mpegvideo_enc.c' l='3417' u='a' c='encode_thread'/>
<use f='ffmpeg/libavcodec/mpegvideo_enc.c' l='3580' u='a' c='encode_thread'/>
<use f='ffmpeg/libavcodec/mpegvideo_enc.c' l='3595' u='a' c='encode_thread'/>
<use f='ffmpeg/libavcodec/mpegvideo_enc.c' l='3641' u='a' c='merge_context_after_encode'/>
<use f='ffmpeg/libavcodec/mpegvideo_enc.c' l='3641' u='m' c='merge_context_after_encode'/>
<use f='ffmpeg/libavcodec/mpegvideo_enc.c' l='3641' u='a' c='merge_context_after_encode'/>
<use f='ffmpeg/libavcodec/mpegvideo_enc.c' l='3642' u='a' c='merge_context_after_encode'/>
<use f='ffmpeg/libavcodec/mpegvideo_enc.c' l='3922' u='a' c='encode_picture'/>
<use f='ffmpeg/libavcodec/mpegvideo_enc.c' l='3926' u='a' c='encode_picture'/>
<use f='ffmpeg/libavcodec/mpegvideo_enc.c' l='3965' u='a' c='encode_picture'/>
<use f='ffmpeg/libavcodec/mpegvideo_enc.c' l='3973' u='m' c='encode_picture'/>
<use f='ffmpeg/libavcodec/mpegvideo_enc.c' l='3973' u='m' c='encode_picture'/>
<use f='ffmpeg/libavcodec/mpegvideo_enc.c' l='3974' u='a' c='encode_picture'/>
<use f='ffmpeg/libavcodec/mpegvideo_enc.c' l='3974' u='m' c='encode_picture'/>
<use f='ffmpeg/libavcodec/mpegvideo_enc.c' l='3974' u='m' c='encode_picture'/>
<use f='ffmpeg/libavcodec/mpegvideo_enc.c' l='3974' u='m' c='encode_picture'/>
<use f='ffmpeg/libavcodec/mpegvideo_enc.c' l='3974' u='m' c='encode_picture'/>
<use f='ffmpeg/libavcodec/msmpeg4enc.c' l='221' u='a' c='ff_msmpeg4_encode_picture_header'/>
<use f='ffmpeg/libavcodec/msmpeg4enc.c' l='222' u='a' c='ff_msmpeg4_encode_picture_header'/>
<use f='ffmpeg/libavcodec/msmpeg4enc.c' l='224' u='a' c='ff_msmpeg4_encode_picture_header'/>
<use f='ffmpeg/libavcodec/msmpeg4enc.c' l='241' u='a' c='ff_msmpeg4_encode_picture_header'/>
<use f='ffmpeg/libavcodec/msmpeg4enc.c' l='246' u='a' c='ff_msmpeg4_encode_picture_header'/>
<use f='ffmpeg/libavcodec/msmpeg4enc.c' l='251' u='a' c='ff_msmpeg4_encode_picture_header'/>
<use f='ffmpeg/libavcodec/msmpeg4enc.c' l='252' u='a' c='ff_msmpeg4_encode_picture_header'/>
<use f='ffmpeg/libavcodec/msmpeg4enc.c' l='255' u='a' c='ff_msmpeg4_encode_picture_header'/>
<use f='ffmpeg/libavcodec/msmpeg4enc.c' l='258' u='a' c='ff_msmpeg4_encode_picture_header'/>
<use f='ffmpeg/libavcodec/msmpeg4enc.c' l='261' u='a' c='ff_msmpeg4_encode_picture_header'/>
<use f='ffmpeg/libavcodec/msmpeg4enc.c' l='265' u='a' c='ff_msmpeg4_encode_picture_header'/>
<use f='ffmpeg/libavcodec/msmpeg4enc.c' l='267' u='a' c='ff_msmpeg4_encode_picture_header'/>
<use f='ffmpeg/libavcodec/msmpeg4enc.c' l='269' u='a' c='ff_msmpeg4_encode_picture_header'/>
<use f='ffmpeg/libavcodec/msmpeg4enc.c' l='280' u='a' c='ff_msmpeg4_encode_ext_header'/>
<use f='ffmpeg/libavcodec/msmpeg4enc.c' l='282' u='a' c='ff_msmpeg4_encode_ext_header'/>
<use f='ffmpeg/libavcodec/msmpeg4enc.c' l='285' u='a' c='ff_msmpeg4_encode_ext_header'/>
<use f='ffmpeg/libavcodec/msmpeg4enc.c' l='313' u='a' c='ff_msmpeg4_encode_motion'/>
<use f='ffmpeg/libavcodec/msmpeg4enc.c' l='318' u='a' c='ff_msmpeg4_encode_motion'/>
<use f='ffmpeg/libavcodec/msmpeg4enc.c' l='319' u='a' c='ff_msmpeg4_encode_motion'/>
<use f='ffmpeg/libavcodec/msmpeg4enc.c' l='343' u='a' c='msmpeg4v2_encode_motion'/>
<use f='ffmpeg/libavcodec/msmpeg4enc.c' l='362' u='a' c='msmpeg4v2_encode_motion'/>
<use f='ffmpeg/libavcodec/msmpeg4enc.c' l='364' u='a' c='msmpeg4v2_encode_motion'/>
<use f='ffmpeg/libavcodec/msmpeg4enc.c' l='388' u='a' c='ff_msmpeg4_encode_mb'/>
<use f='ffmpeg/libavcodec/msmpeg4enc.c' l='396' u='a' c='ff_msmpeg4_encode_mb'/>
<use f='ffmpeg/libavcodec/msmpeg4enc.c' l='399' u='a' c='ff_msmpeg4_encode_mb'/>
<use f='ffmpeg/libavcodec/msmpeg4enc.c' l='405' u='a' c='ff_msmpeg4_encode_mb'/>
<use f='ffmpeg/libavcodec/msmpeg4enc.c' l='415' u='a' c='ff_msmpeg4_encode_mb'/>
<use f='ffmpeg/libavcodec/msmpeg4enc.c' l='452' u='a' c='ff_msmpeg4_encode_mb'/>
<use f='ffmpeg/libavcodec/msmpeg4enc.c' l='456' u='a' c='ff_msmpeg4_encode_mb'/>
<use f='ffmpeg/libavcodec/msmpeg4enc.c' l='457' u='a' c='ff_msmpeg4_encode_mb'/>
<use f='ffmpeg/libavcodec/msmpeg4enc.c' l='461' u='a' c='ff_msmpeg4_encode_mb'/>
<use f='ffmpeg/libavcodec/msmpeg4enc.c' l='462' u='a' c='ff_msmpeg4_encode_mb'/>
<use f='ffmpeg/libavcodec/msmpeg4enc.c' l='467' u='a' c='ff_msmpeg4_encode_mb'/>
<use f='ffmpeg/libavcodec/msmpeg4enc.c' l='471' u='a' c='ff_msmpeg4_encode_mb'/>
<use f='ffmpeg/libavcodec/msmpeg4enc.c' l='472' u='a' c='ff_msmpeg4_encode_mb'/>
<use f='ffmpeg/libavcodec/msmpeg4enc.c' l='476' u='a' c='ff_msmpeg4_encode_mb'/>
<use f='ffmpeg/libavcodec/msmpeg4enc.c' l='479' u='a' c='ff_msmpeg4_encode_mb'/>
<use f='ffmpeg/libavcodec/msmpeg4enc.c' l='513' u='a' c='msmpeg4_encode_dc'/>
<use f='ffmpeg/libavcodec/msmpeg4enc.c' l='517' u='a' c='msmpeg4_encode_dc'/>
<use f='ffmpeg/libavcodec/msmpeg4enc.c' l='542' u='a' c='msmpeg4_encode_dc'/>
<use f='ffmpeg/libavcodec/msmpeg4enc.c' l='544' u='a' c='msmpeg4_encode_dc'/>
<use f='ffmpeg/libavcodec/msmpeg4enc.c' l='548' u='a' c='msmpeg4_encode_dc'/>
<use f='ffmpeg/libavcodec/msmpeg4enc.c' l='550' u='a' c='msmpeg4_encode_dc'/>
<use f='ffmpeg/libavcodec/msmpeg4enc.c' l='558' u='a' c='msmpeg4_encode_dc'/>
<use f='ffmpeg/libavcodec/msmpeg4enc.c' l='560' u='a' c='msmpeg4_encode_dc'/>
<use f='ffmpeg/libavcodec/msmpeg4enc.c' l='563' u='a' c='msmpeg4_encode_dc'/>
<use f='ffmpeg/libavcodec/msmpeg4enc.c' l='628' u='a' c='ff_msmpeg4_encode_block'/>
<use f='ffmpeg/libavcodec/msmpeg4enc.c' l='638' u='a' c='ff_msmpeg4_encode_block'/>
<use f='ffmpeg/libavcodec/msmpeg4enc.c' l='651' u='a' c='ff_msmpeg4_encode_block'/>
<use f='ffmpeg/libavcodec/msmpeg4enc.c' l='652' u='a' c='ff_msmpeg4_encode_block'/>
<use f='ffmpeg/libavcodec/msmpeg4enc.c' l='659' u='a' c='ff_msmpeg4_encode_block'/>
<use f='ffmpeg/libavcodec/msmpeg4enc.c' l='661' u='a' c='ff_msmpeg4_encode_block'/>
<use f='ffmpeg/libavcodec/msmpeg4enc.c' l='663' u='a' c='ff_msmpeg4_encode_block'/>
<use f='ffmpeg/libavcodec/msmpeg4enc.c' l='664' u='a' c='ff_msmpeg4_encode_block'/>
<use f='ffmpeg/libavcodec/msmpeg4enc.c' l='665' u='a' c='ff_msmpeg4_encode_block'/>
<use f='ffmpeg/libavcodec/msmpeg4enc.c' l='667' u='a' c='ff_msmpeg4_encode_block'/>
<use f='ffmpeg/libavcodec/msmpeg4enc.c' l='668' u='a' c='ff_msmpeg4_encode_block'/>
<use f='ffmpeg/libavcodec/msmpeg4enc.c' l='672' u='a' c='ff_msmpeg4_encode_block'/>
<use f='ffmpeg/libavcodec/msmpeg4enc.c' l='673' u='a' c='ff_msmpeg4_encode_block'/>
<use f='ffmpeg/libavcodec/msmpeg4enc.c' l='674' u='a' c='ff_msmpeg4_encode_block'/>
<use f='ffmpeg/libavcodec/msmpeg4enc.c' l='678' u='a' c='ff_msmpeg4_encode_block'/>
<use f='ffmpeg/libavcodec/msmpeg4enc.c' l='679' u='a' c='ff_msmpeg4_encode_block'/>
<use f='ffmpeg/libavcodec/msmpeg4enc.c' l='680' u='a' c='ff_msmpeg4_encode_block'/>
<use f='ffmpeg/libavcodec/msmpeg4enc.c' l='683' u='a' c='ff_msmpeg4_encode_block'/>
<use f='ffmpeg/libavcodec/rv10enc.c' l='36' u='a' c='ff_rv10_encode_picture_header'/>
<use f='ffmpeg/libavcodec/rv10enc.c' l='38' u='a' c='ff_rv10_encode_picture_header'/>
<use f='ffmpeg/libavcodec/rv10enc.c' l='40' u='a' c='ff_rv10_encode_picture_header'/>
<use f='ffmpeg/libavcodec/rv10enc.c' l='42' u='a' c='ff_rv10_encode_picture_header'/>
<use f='ffmpeg/libavcodec/rv10enc.c' l='44' u='a' c='ff_rv10_encode_picture_header'/>
<use f='ffmpeg/libavcodec/rv10enc.c' l='57' u='a' c='ff_rv10_encode_picture_header'/>
<use f='ffmpeg/libavcodec/rv10enc.c' l='58' u='a' c='ff_rv10_encode_picture_header'/>
<use f='ffmpeg/libavcodec/rv10enc.c' l='59' u='a' c='ff_rv10_encode_picture_header'/>
<use f='ffmpeg/libavcodec/rv10enc.c' l='62' u='a' c='ff_rv10_encode_picture_header'/>
<use f='ffmpeg/libavcodec/rv20enc.c' l='36' u='a' c='ff_rv20_encode_picture_header'/>
<use f='ffmpeg/libavcodec/rv20enc.c' l='37' u='a' c='ff_rv20_encode_picture_header'/>
<use f='ffmpeg/libavcodec/rv20enc.c' l='38' u='a' c='ff_rv20_encode_picture_header'/>
<use f='ffmpeg/libavcodec/rv20enc.c' l='40' u='a' c='ff_rv20_encode_picture_header'/>
<use f='ffmpeg/libavcodec/rv20enc.c' l='44' u='a' c='ff_rv20_encode_picture_header'/>
<use f='ffmpeg/libavcodec/speedhqenc.c' l='142' u='a' c='ff_speedhq_encode_picture_header'/>
<use f='ffmpeg/libavcodec/speedhqenc.c' l='143' u='a' c='ff_speedhq_encode_picture_header'/>
<use f='ffmpeg/libavcodec/speedhqenc.c' l='147' u='a' c='ff_speedhq_encode_picture_header'/>
<use f='ffmpeg/libavcodec/speedhqenc.c' l='154' u='a' c='ff_speedhq_end_slice'/>
<use f='ffmpeg/libavcodec/speedhqenc.c' l='155' u='m' c='ff_speedhq_end_slice'/>
<use f='ffmpeg/libavcodec/speedhqenc.c' l='155' u='m' c='ff_speedhq_end_slice'/>
<use f='ffmpeg/libavcodec/speedhqenc.c' l='156' u='m' c='ff_speedhq_end_slice'/>
<use f='ffmpeg/libavcodec/speedhqenc.c' l='156' u='m' c='ff_speedhq_end_slice'/>
<use f='ffmpeg/libavcodec/speedhqenc.c' l='156' u='m' c='ff_speedhq_end_slice'/>
<use f='ffmpeg/libavcodec/speedhqenc.c' l='159' u='m' c='ff_speedhq_end_slice'/>
<use f='ffmpeg/libavcodec/speedhqenc.c' l='159' u='m' c='ff_speedhq_end_slice'/>
<use f='ffmpeg/libavcodec/speedhqenc.c' l='160' u='a' c='ff_speedhq_end_slice'/>
<use f='ffmpeg/libavcodec/speedhqenc.c' l='207' u='a' c='encode_block'/>
<use f='ffmpeg/libavcodec/speedhqenc.c' l='229' u='a' c='encode_block'/>
<use f='ffmpeg/libavcodec/speedhqenc.c' l='233' u='a' c='encode_block'/>
<use f='ffmpeg/libavcodec/speedhqenc.c' l='235' u='a' c='encode_block'/>
<use f='ffmpeg/libavcodec/speedhqenc.c' l='236' u='a' c='encode_block'/>
<use f='ffmpeg/libavcodec/speedhqenc.c' l='242' u='a' c='encode_block'/>
<use f='ffmpeg/libavcodec/svq1enc.c' l='420' u='w' c='svq1_encode_plane'/>
<use f='ffmpeg/libavcodec/svq1enc.c' l='427' u='a' c='svq1_encode_plane'/>
<use f='ffmpeg/libavcodec/svq1enc.c' l='428' u='a' c='svq1_encode_plane'/>
<use f='ffmpeg/libavcodec/svq1enc.c' l='429' u='r' c='svq1_encode_plane'/>
<use f='ffmpeg/libavcodec/wmv2enc.c' l='78' u='a' c='ff_wmv2_encode_picture_header'/>
<use f='ffmpeg/libavcodec/wmv2enc.c' l='80' u='a' c='ff_wmv2_encode_picture_header'/>
<use f='ffmpeg/libavcodec/wmv2enc.c' l='81' u='a' c='ff_wmv2_encode_picture_header'/>
<use f='ffmpeg/libavcodec/wmv2enc.c' l='96' u='a' c='ff_wmv2_encode_picture_header'/>
<use f='ffmpeg/libavcodec/wmv2enc.c' l='99' u='a' c='ff_wmv2_encode_picture_header'/>
<use f='ffmpeg/libavcodec/wmv2enc.c' l='102' u='a' c='ff_wmv2_encode_picture_header'/>
<use f='ffmpeg/libavcodec/wmv2enc.c' l='103' u='a' c='ff_wmv2_encode_picture_header'/>
<use f='ffmpeg/libavcodec/wmv2enc.c' l='106' u='a' c='ff_wmv2_encode_picture_header'/>
<use f='ffmpeg/libavcodec/wmv2enc.c' l='112' u='a' c='ff_wmv2_encode_picture_header'/>
<use f='ffmpeg/libavcodec/wmv2enc.c' l='114' u='a' c='ff_wmv2_encode_picture_header'/>
<use f='ffmpeg/libavcodec/wmv2enc.c' l='118' u='a' c='ff_wmv2_encode_picture_header'/>
<use f='ffmpeg/libavcodec/wmv2enc.c' l='121' u='a' c='ff_wmv2_encode_picture_header'/>
<use f='ffmpeg/libavcodec/wmv2enc.c' l='123' u='a' c='ff_wmv2_encode_picture_header'/>
<use f='ffmpeg/libavcodec/wmv2enc.c' l='127' u='a' c='ff_wmv2_encode_picture_header'/>
<use f='ffmpeg/libavcodec/wmv2enc.c' l='130' u='a' c='ff_wmv2_encode_picture_header'/>
<use f='ffmpeg/libavcodec/wmv2enc.c' l='133' u='a' c='ff_wmv2_encode_picture_header'/>
<use f='ffmpeg/libavcodec/wmv2enc.c' l='134' u='a' c='ff_wmv2_encode_picture_header'/>
<use f='ffmpeg/libavcodec/wmv2enc.c' l='164' u='a' c='ff_wmv2_encode_mb'/>
<use f='ffmpeg/libavcodec/wmv2enc.c' l='192' u='a' c='ff_wmv2_encode_mb'/>
<use f='ffmpeg/libavcodec/wmv2enc.c' l='196' u='a' c='ff_wmv2_encode_mb'/>
<use f='ffmpeg/libavcodec/wmv2enc.c' l='199' u='a' c='ff_wmv2_encode_mb'/>
<use f='ffmpeg/libavcodec/wmv2enc.c' l='202' u='a' c='ff_wmv2_encode_mb'/>
