<dec f='ffmpeg/libavcodec/opus_rc.h' l='42' type='RawBitsContext'/>
<offset>256</offset>
<use f='ffmpeg/libavcodec/opus_celt.c' l='346' u='m' c='ff_celt_decode_frame'/>
<use f='ffmpeg/libavcodec/opus_rc.c' l='43' u='m' c='opus_rc_enc_carryout'/>
<use f='ffmpeg/libavcodec/opus_rc.c' l='144' u='m' c='ff_opus_rc_get_raw'/>
<use f='ffmpeg/libavcodec/opus_rc.c' l='144' u='m' c='ff_opus_rc_get_raw'/>
<use f='ffmpeg/libavcodec/opus_rc.c' l='145' u='m' c='ff_opus_rc_get_raw'/>
<use f='ffmpeg/libavcodec/opus_rc.c' l='145' u='m' c='ff_opus_rc_get_raw'/>
<use f='ffmpeg/libavcodec/opus_rc.c' l='145' u='m' c='ff_opus_rc_get_raw'/>
<use f='ffmpeg/libavcodec/opus_rc.c' l='146' u='m' c='ff_opus_rc_get_raw'/>
<use f='ffmpeg/libavcodec/opus_rc.c' l='147' u='m' c='ff_opus_rc_get_raw'/>
<use f='ffmpeg/libavcodec/opus_rc.c' l='150' u='m' c='ff_opus_rc_get_raw'/>
<use f='ffmpeg/libavcodec/opus_rc.c' l='151' u='m' c='ff_opus_rc_get_raw'/>
<use f='ffmpeg/libavcodec/opus_rc.c' l='152' u='m' c='ff_opus_rc_get_raw'/>
<use f='ffmpeg/libavcodec/opus_rc.c' l='163' u='m' c='ff_opus_rc_put_raw'/>
<use f='ffmpeg/libavcodec/opus_rc.c' l='163' u='m' c='ff_opus_rc_put_raw'/>
<use f='ffmpeg/libavcodec/opus_rc.c' l='166' u='m' c='ff_opus_rc_put_raw'/>
<use f='ffmpeg/libavcodec/opus_rc.c' l='166' u='m' c='ff_opus_rc_put_raw'/>
<use f='ffmpeg/libavcodec/opus_rc.c' l='167' u='m' c='ff_opus_rc_put_raw'/>
<use f='ffmpeg/libavcodec/opus_rc.c' l='167' u='m' c='ff_opus_rc_put_raw'/>
<use f='ffmpeg/libavcodec/opus_rc.c' l='169' u='m' c='ff_opus_rc_put_raw'/>
<use f='ffmpeg/libavcodec/opus_rc.c' l='170' u='m' c='ff_opus_rc_put_raw'/>
<use f='ffmpeg/libavcodec/opus_rc.c' l='170' u='m' c='ff_opus_rc_put_raw'/>
<use f='ffmpeg/libavcodec/opus_rc.c' l='171' u='m' c='ff_opus_rc_put_raw'/>
<use f='ffmpeg/libavcodec/opus_rc.c' l='172' u='m' c='ff_opus_rc_put_raw'/>
<use f='ffmpeg/libavcodec/opus_rc.c' l='173' u='m' c='ff_opus_rc_put_raw'/>
<use f='ffmpeg/libavcodec/opus_rc.c' l='174' u='m' c='ff_opus_rc_put_raw'/>
<use f='ffmpeg/libavcodec/opus_rc.c' l='174' u='m' c='ff_opus_rc_put_raw'/>
<use f='ffmpeg/libavcodec/opus_rc.c' l='175' u='m' c='ff_opus_rc_put_raw'/>
<use f='ffmpeg/libavcodec/opus_rc.c' l='354' u='m' c='ff_opus_rc_dec_raw_init'/>
<use f='ffmpeg/libavcodec/opus_rc.c' l='355' u='m' c='ff_opus_rc_dec_raw_init'/>
<use f='ffmpeg/libavcodec/opus_rc.c' l='356' u='m' c='ff_opus_rc_dec_raw_init'/>
<use f='ffmpeg/libavcodec/opus_rc.c' l='357' u='m' c='ff_opus_rc_dec_raw_init'/>
<use f='ffmpeg/libavcodec/opus_rc.c' l='386' u='m' c='ff_opus_rc_enc_end'/>
<use f='ffmpeg/libavcodec/opus_rc.c' l='386' u='m' c='ff_opus_rc_enc_end'/>
<use f='ffmpeg/libavcodec/opus_rc.c' l='389' u='m' c='ff_opus_rc_enc_end'/>
<use f='ffmpeg/libavcodec/opus_rc.c' l='389' u='m' c='ff_opus_rc_enc_end'/>
<use f='ffmpeg/libavcodec/opus_rc.c' l='392' u='m' c='ff_opus_rc_enc_end'/>
<use f='ffmpeg/libavcodec/opus_rc.c' l='393' u='m' c='ff_opus_rc_enc_end'/>
<use f='ffmpeg/libavcodec/opus_rc.c' l='394' u='m' c='ff_opus_rc_enc_end'/>
<use f='ffmpeg/libavcodec/opus_rc.c' l='394' u='m' c='ff_opus_rc_enc_end'/>
<use f='ffmpeg/libavcodec/opus_rc.c' l='398' u='m' c='ff_opus_rc_enc_end'/>
<use f='ffmpeg/libavcodec/opus_rc.c' l='398' u='m' c='ff_opus_rc_enc_end'/>
