<dec f='ffmpeg/libavcodec/mpegpicture.h' l='46' type='struct AVFrame *'/>
<offset>0</offset>
<use f='ffmpeg/libavcodec/h261dec.c' l='626' u='r' c='h261_decode_frame'/>
<use f='ffmpeg/libavcodec/h261dec.c' l='627' u='r' c='h261_decode_frame'/>
<use f='ffmpeg/libavcodec/h261dec.c' l='650' u='r' c='h261_decode_frame'/>
<use f='ffmpeg/libavcodec/h261dec.c' l='650' u='r' c='h261_decode_frame'/>
<use f='ffmpeg/libavcodec/h261dec.c' l='651' u='r' c='h261_decode_frame'/>
<use f='ffmpeg/libavcodec/h261dec.c' l='653' u='r' c='h261_decode_frame'/>
<use f='ffmpeg/libavcodec/h263dec.c' l='436' u='r' c='ff_h263_decode_frame'/>
<use f='ffmpeg/libavcodec/h263dec.c' l='538' u='r' c='ff_h263_decode_frame'/>
<use f='ffmpeg/libavcodec/h263dec.c' l='586' u='r' c='ff_h263_decode_frame'/>
<use f='ffmpeg/libavcodec/h263dec.c' l='587' u='r' c='ff_h263_decode_frame'/>
<use f='ffmpeg/libavcodec/h263dec.c' l='694' u='r' c='ff_h263_decode_frame'/>
<use f='ffmpeg/libavcodec/h263dec.c' l='699' u='r' c='ff_h263_decode_frame'/>
<use f='ffmpeg/libavcodec/intrax8.c' l='750' u='r' c='ff_intrax8_decode_picture'/>
<use f='ffmpeg/libavcodec/ituh263dec.c' l='666' u='r' c='set_direct_mv'/>
<use f='ffmpeg/libavcodec/motion_est.c' l='684' u='r' c='h263_mv4_search'/>
<use f='ffmpeg/libavcodec/motion_est.c' l='701' u='r' c='h263_mv4_search'/>
<use f='ffmpeg/libavcodec/motion_est.c' l='702' u='r' c='h263_mv4_search'/>
<use f='ffmpeg/libavcodec/motion_est.c' l='704' u='r' c='h263_mv4_search'/>
<use f='ffmpeg/libavcodec/motion_est.c' l='705' u='r' c='h263_mv4_search'/>
<use f='ffmpeg/libavcodec/motion_est.c' l='708' u='r' c='h263_mv4_search'/>
<use f='ffmpeg/libavcodec/motion_est.c' l='709' u='r' c='h263_mv4_search'/>
<use f='ffmpeg/libavcodec/motion_est.c' l='898' u='r' c='ff_estimate_p_frame_motion'/>
<use f='ffmpeg/libavcodec/motion_est.c' l='898' u='r' c='ff_estimate_p_frame_motion'/>
<use f='ffmpeg/libavcodec/motion_est.c' l='1069' u='r' c='ff_pre_estimate_p_frame_motion'/>
<use f='ffmpeg/libavcodec/motion_est.c' l='1069' u='r' c='ff_pre_estimate_p_frame_motion'/>
<use f='ffmpeg/libavcodec/motion_est.c' l='1498' u='r' c='ff_estimate_b_frame_motion'/>
<use f='ffmpeg/libavcodec/motion_est.c' l='1498' u='r' c='ff_estimate_b_frame_motion'/>
<use f='ffmpeg/libavcodec/motion_est.c' l='1499' u='r' c='ff_estimate_b_frame_motion'/>
<use f='ffmpeg/libavcodec/mpeg12dec.c' l='1375' u='r' c='mpeg1_decode_picture'/>
<use f='ffmpeg/libavcodec/mpeg12dec.c' l='1376' u='r' c='mpeg1_decode_picture'/>
<use f='ffmpeg/libavcodec/mpeg12dec.c' l='1551' u='r' c='mpeg_decode_picture_coding_extension'/>
<use f='ffmpeg/libavcodec/mpeg12dec.c' l='1552' u='r' c='mpeg_decode_picture_coding_extension'/>
<use f='ffmpeg/libavcodec/mpeg12dec.c' l='1612' u='r' c='mpeg_field_start'/>
<use f='ffmpeg/libavcodec/mpeg12dec.c' l='1616' u='r' c='mpeg_field_start'/>
<use f='ffmpeg/libavcodec/mpeg12dec.c' l='1618' u='r' c='mpeg_field_start'/>
<use f='ffmpeg/libavcodec/mpeg12dec.c' l='1620' u='r' c='mpeg_field_start'/>
<use f='ffmpeg/libavcodec/mpeg12dec.c' l='1624' u='r' c='mpeg_field_start'/>
<use f='ffmpeg/libavcodec/mpeg12dec.c' l='1633' u='r' c='mpeg_field_start'/>
<use f='ffmpeg/libavcodec/mpeg12dec.c' l='1641' u='r' c='mpeg_field_start'/>
<use f='ffmpeg/libavcodec/mpeg12dec.c' l='1651' u='r' c='mpeg_field_start'/>
<use f='ffmpeg/libavcodec/mpeg12dec.c' l='1679' u='r' c='mpeg_field_start'/>
<use f='ffmpeg/libavcodec/mpeg12dec.c' l='1679' u='r' c='mpeg_field_start'/>
<use f='ffmpeg/libavcodec/mpeg12dec.c' l='1681' u='r' c='mpeg_field_start'/>
<use f='ffmpeg/libavcodec/mpeg12dec.c' l='1682' u='r' c='mpeg_field_start'/>
<use f='ffmpeg/libavcodec/mpeg12dec.c' l='2059' u='r' c='slice_end'/>
<use f='ffmpeg/libavcodec/mpeg12dec.c' l='2070' u='r' c='slice_end'/>
<use f='ffmpeg/libavcodec/mpeg12dec.c' l='2804' u='r' c='mpeg_decode_frame'/>
<use f='ffmpeg/libavcodec/mpeg12enc.c' l='255' u='r' c='mpeg1_encode_sequence_header'/>
<use f='ffmpeg/libavcodec/mpeg12enc.c' l='344' u='r' c='mpeg1_encode_sequence_header'/>
<use f='ffmpeg/libavcodec/mpeg12enc.c' l='380' u='r' c='mpeg1_encode_sequence_header'/>
<use f='ffmpeg/libavcodec/mpeg12enc.c' l='383' u='r' c='mpeg1_encode_sequence_header'/>
<use f='ffmpeg/libavcodec/mpeg12enc.c' l='490' u='r' c='ff_mpeg1_encode_picture_header'/>
<use f='ffmpeg/libavcodec/mpeg12enc.c' l='514' u='r' c='ff_mpeg1_encode_picture_header'/>
<use f='ffmpeg/libavcodec/mpeg12enc.c' l='554' u='r' c='ff_mpeg1_encode_picture_header'/>
<use f='ffmpeg/libavcodec/mpeg4videoenc.c' l='647' u='r' c='ff_mpeg4_encode_mb'/>
<use f='ffmpeg/libavcodec/mpeg4videoenc.c' l='655' u='r' c='ff_mpeg4_encode_mb'/>
<use f='ffmpeg/libavcodec/mpeg4videoenc.c' l='658' u='r' c='ff_mpeg4_encode_mb'/>
<use f='ffmpeg/libavcodec/mpeg4videoenc.c' l='892' u='r' c='mpeg4_encode_gop_header'/>
<use f='ffmpeg/libavcodec/mpeg4videoenc.c' l='894' u='r' c='mpeg4_encode_gop_header'/>
<use f='ffmpeg/libavcodec/mpeg4videoenc.c' l='894' u='r' c='mpeg4_encode_gop_header'/>
<use f='ffmpeg/libavcodec/mpeg4videoenc.c' l='1104' u='r' c='ff_mpeg4_encode_picture_header'/>
<use f='ffmpeg/libavcodec/mpeg_er.c' l='34' u='r' c='set_erpic'/>
<use f='ffmpeg/libavcodec/mpeg_er.c' l='84' u='r' c='mpeg_er_decode_mb'/>
<use f='ffmpeg/libavcodec/mpeg_er.c' l='87' u='r' c='mpeg_er_decode_mb'/>
<use f='ffmpeg/libavcodec/mpeg_er.c' l='90' u='r' c='mpeg_er_decode_mb'/>
<use f='ffmpeg/libavcodec/mpegpicture.c' l='106' u='r' c='alloc_frame_buffer'/>
<use f='ffmpeg/libavcodec/mpegpicture.c' l='111' u='r' c='alloc_frame_buffer'/>
<use f='ffmpeg/libavcodec/mpegpicture.c' l='112' u='r' c='alloc_frame_buffer'/>
<use f='ffmpeg/libavcodec/mpegpicture.c' l='118' u='r' c='alloc_frame_buffer'/>
<use f='ffmpeg/libavcodec/mpegpicture.c' l='119' u='r' c='alloc_frame_buffer'/>
<use f='ffmpeg/libavcodec/mpegpicture.c' l='120' u='r' c='alloc_frame_buffer'/>
<use f='ffmpeg/libavcodec/mpegpicture.c' l='121' u='r' c='alloc_frame_buffer'/>
<use f='ffmpeg/libavcodec/mpegpicture.c' l='124' u='r' c='alloc_frame_buffer'/>
<use f='ffmpeg/libavcodec/mpegpicture.c' l='126' u='r' c='alloc_frame_buffer'/>
<use f='ffmpeg/libavcodec/mpegpicture.c' l='132' u='r' c='alloc_frame_buffer'/>
<use f='ffmpeg/libavcodec/mpegpicture.c' l='134' u='r' c='alloc_frame_buffer'/>
<use f='ffmpeg/libavcodec/mpegpicture.c' l='136' u='r' c='alloc_frame_buffer'/>
<use f='ffmpeg/libavcodec/mpegpicture.c' l='138' u='r' c='alloc_frame_buffer'/>
<use f='ffmpeg/libavcodec/mpegpicture.c' l='139' u='r' c='alloc_frame_buffer'/>
<use f='ffmpeg/libavcodec/mpegpicture.c' l='154' u='r' c='alloc_frame_buffer'/>
<use f='ffmpeg/libavcodec/mpegpicture.c' l='155' u='r' c='alloc_frame_buffer'/>
<use f='ffmpeg/libavcodec/mpegpicture.c' l='158' u='r' c='alloc_frame_buffer'/>
<use f='ffmpeg/libavcodec/mpegpicture.c' l='159' u='r' c='alloc_frame_buffer'/>
<use f='ffmpeg/libavcodec/mpegpicture.c' l='164' u='r' c='alloc_frame_buffer'/>
<use f='ffmpeg/libavcodec/mpegpicture.c' l='165' u='r' c='alloc_frame_buffer'/>
<use f='ffmpeg/libavcodec/mpegpicture.c' l='165' u='r' c='alloc_frame_buffer'/>
<use f='ffmpeg/libavcodec/mpegpicture.c' l='174' u='r' c='alloc_frame_buffer'/>
<use f='ffmpeg/libavcodec/mpegpicture.c' l='246' u='r' c='ff_alloc_picture'/>
<use f='ffmpeg/libavcodec/mpegpicture.c' l='249' u='r' c='ff_alloc_picture'/>
<use f='ffmpeg/libavcodec/mpegpicture.c' l='255' u='r' c='ff_alloc_picture'/>
<use f='ffmpeg/libavcodec/mpegpicture.c' l='256' u='r' c='ff_alloc_picture'/>
<use f='ffmpeg/libavcodec/mpegpicture.c' l='299' u='r' c='ff_mpeg_unref_picture'/>
<use f='ffmpeg/libavcodec/mpegpicture.c' l='306' u='r' c='ff_mpeg_unref_picture'/>
<use f='ffmpeg/libavcodec/mpegpicture.c' l='307' u='r' c='ff_mpeg_unref_picture'/>
<use f='ffmpeg/libavcodec/mpegpicture.c' l='359' u='r' c='ff_mpeg_ref_picture'/>
<use f='ffmpeg/libavcodec/mpegpicture.c' l='360' u='r' c='ff_mpeg_ref_picture'/>
<use f='ffmpeg/libavcodec/mpegpicture.c' l='362' u='r' c='ff_mpeg_ref_picture'/>
<use f='ffmpeg/libavcodec/mpegpicture.c' l='363' u='r' c='ff_mpeg_ref_picture'/>
<use f='ffmpeg/libavcodec/mpegpicture.c' l='400' u='r' c='pic_is_unused'/>
<use f='ffmpeg/libavcodec/mpegpicture.c' l='413' u='r' c='find_unused_picture'/>
<use f='ffmpeg/libavcodec/mpegvideo.c' l='578' u='r' c='ff_mpeg_update_thread_context'/>
<use f='ffmpeg/libavcodec/mpegvideo.c' l='586' u='r' c='ff_mpeg_update_thread_context'/>
<use f='ffmpeg/libavcodec/mpegvideo.c' l='586' u='r' c='ff_mpeg_update_thread_context'/>
<use f='ffmpeg/libavcodec/mpegvideo.c' l='586' u='r' c='ff_mpeg_update_thread_context'/>
<use f='ffmpeg/libavcodec/mpegvideo.c' l='586' u='r' c='ff_mpeg_update_thread_context'/>
<use f='ffmpeg/libavcodec/mpegvideo.c' l='586' u='r' c='ff_mpeg_update_thread_context'/>
<use f='ffmpeg/libavcodec/mpegvideo.c' l='586' u='r' c='ff_mpeg_update_thread_context'/>
<use f='ffmpeg/libavcodec/mpegvideo.c' l='664' u='r' c='ff_mpeg_update_thread_context'/>
<use f='ffmpeg/libavcodec/mpegvideo.c' l='963' u='w' c='ff_mpv_common_init'/>
<use f='ffmpeg/libavcodec/mpegvideo.c' l='964' u='r' c='ff_mpv_common_init'/>
<use f='ffmpeg/libavcodec/mpegvideo.c' l='968' u='w' c='ff_mpv_common_init'/>
<use f='ffmpeg/libavcodec/mpegvideo.c' l='969' u='w' c='ff_mpv_common_init'/>
<use f='ffmpeg/libavcodec/mpegvideo.c' l='970' u='w' c='ff_mpv_common_init'/>
<use f='ffmpeg/libavcodec/mpegvideo.c' l='971' u='w' c='ff_mpv_common_init'/>
<use f='ffmpeg/libavcodec/mpegvideo.c' l='1135' u='a' c='ff_mpv_common_end'/>
<use f='ffmpeg/libavcodec/mpegvideo.c' l='1141' u='a' c='ff_mpv_common_end'/>
<use f='ffmpeg/libavcodec/mpegvideo.c' l='1144' u='a' c='ff_mpv_common_end'/>
<use f='ffmpeg/libavcodec/mpegvideo.c' l='1147' u='a' c='ff_mpv_common_end'/>
<use f='ffmpeg/libavcodec/mpegvideo.c' l='1150' u='a' c='ff_mpv_common_end'/>
<use f='ffmpeg/libavcodec/mpegvideo.c' l='1195' u='r' c='ff_mpv_frame_start'/>
<use f='ffmpeg/libavcodec/mpegvideo.c' l='1219' u='r' c='ff_mpv_frame_start'/>
<use f='ffmpeg/libavcodec/mpegvideo.c' l='1238' u='r' c='ff_mpv_frame_start'/>
<use f='ffmpeg/libavcodec/mpegvideo.c' l='1245' u='r' c='ff_mpv_frame_start'/>
<use f='ffmpeg/libavcodec/mpegvideo.c' l='1249' u='r' c='ff_mpv_frame_start'/>
<use f='ffmpeg/libavcodec/mpegvideo.c' l='1252' u='r' c='ff_mpv_frame_start'/>
<use f='ffmpeg/libavcodec/mpegvideo.c' l='1256' u='r' c='ff_mpv_frame_start'/>
<use f='ffmpeg/libavcodec/mpegvideo.c' l='1259' u='r' c='ff_mpv_frame_start'/>
<use f='ffmpeg/libavcodec/mpegvideo.c' l='1272' u='r' c='ff_mpv_frame_start'/>
<use f='ffmpeg/libavcodec/mpegvideo.c' l='1273' u='r' c='ff_mpv_frame_start'/>
<use f='ffmpeg/libavcodec/mpegvideo.c' l='1274' u='r' c='ff_mpv_frame_start'/>
<use f='ffmpeg/libavcodec/mpegvideo.c' l='1277' u='r' c='ff_mpv_frame_start'/>
<use f='ffmpeg/libavcodec/mpegvideo.c' l='1282' u='r' c='ff_mpv_frame_start'/>
<use f='ffmpeg/libavcodec/mpegvideo.c' l='1298' u='r' c='ff_mpv_frame_start'/>
<use f='ffmpeg/libavcodec/mpegvideo.c' l='1299' u='r' c='ff_mpv_frame_start'/>
<use f='ffmpeg/libavcodec/mpegvideo.c' l='1308' u='r' c='ff_mpv_frame_start'/>
<use f='ffmpeg/libavcodec/mpegvideo.c' l='1308' u='r' c='ff_mpv_frame_start'/>
<use f='ffmpeg/libavcodec/mpegvideo.c' l='1310' u='r' c='ff_mpv_frame_start'/>
<use f='ffmpeg/libavcodec/mpegvideo.c' l='1312' u='r' c='ff_mpv_frame_start'/>
<use f='ffmpeg/libavcodec/mpegvideo.c' l='1312' u='r' c='ff_mpv_frame_start'/>
<use f='ffmpeg/libavcodec/mpegvideo.c' l='1314' u='r' c='ff_mpv_frame_start'/>
<use f='ffmpeg/libavcodec/mpegvideo.c' l='1314' u='r' c='ff_mpv_frame_start'/>
<use f='ffmpeg/libavcodec/mpegvideo.c' l='1321' u='r' c='ff_mpv_frame_start'/>
<use f='ffmpeg/libavcodec/mpegvideo.c' l='1321' u='r' c='ff_mpv_frame_start'/>
<use f='ffmpeg/libavcodec/mpegvideo.c' l='1328' u='r' c='ff_mpv_frame_start'/>
<use f='ffmpeg/libavcodec/mpegvideo.c' l='1339' u='r' c='ff_mpv_frame_start'/>
<use f='ffmpeg/libavcodec/mpegvideo.c' l='1340' u='r' c='ff_mpv_frame_start'/>
<use f='ffmpeg/libavcodec/mpegvideo.c' l='1355' u='r' c='ff_mpv_frame_start'/>
<use f='ffmpeg/libavcodec/mpegvideo.c' l='1361' u='r' c='ff_mpv_frame_start'/>
<use f='ffmpeg/libavcodec/mpegvideo.c' l='1368' u='r' c='ff_mpv_frame_start'/>
<use f='ffmpeg/libavcodec/mpegvideo.c' l='1374' u='r' c='ff_mpv_frame_start'/>
<use f='ffmpeg/libavcodec/mpegvideo.c' l='1375' u='r' c='ff_mpv_frame_start'/>
<use f='ffmpeg/libavcodec/mpegvideo.c' l='1377' u='r' c='ff_mpv_frame_start'/>
<use f='ffmpeg/libavcodec/mpegvideo.c' l='1378' u='r' c='ff_mpv_frame_start'/>
<use f='ffmpeg/libavcodec/mpegvideo.c' l='1379' u='r' c='ff_mpv_frame_start'/>
<use f='ffmpeg/libavcodec/mpegvideo.c' l='1398' u='r' c='ff_mpv_frame_start'/>
<use f='ffmpeg/libavcodec/mpegvideo.c' l='1519' u='r' c='mpeg_motion_lowres'/>
<use f='ffmpeg/libavcodec/mpegvideo.c' l='1520' u='r' c='mpeg_motion_lowres'/>
<use f='ffmpeg/libavcodec/mpegvideo.c' l='1766' u='r' c='MPV_motion_lowres'/>
<use f='ffmpeg/libavcodec/mpegvideo.c' l='1784' u='r' c='MPV_motion_lowres'/>
<use f='ffmpeg/libavcodec/mpegvideo.c' l='1826' u='r' c='MPV_motion_lowres'/>
<use f='ffmpeg/libavcodec/mpegvideo.c' l='1992' u='r' c='mpv_reconstruct_mb_internal'/>
<use f='ffmpeg/libavcodec/mpegvideo.c' l='1993' u='r' c='mpv_reconstruct_mb_internal'/>
<use f='ffmpeg/libavcodec/mpegvideo.c' l='2048' u='r' c='mpv_reconstruct_mb_internal'/>
<use f='ffmpeg/libavcodec/mpegvideo.c' l='2052' u='r' c='mpv_reconstruct_mb_internal'/>
<use f='ffmpeg/libavcodec/mpegvideo.c' l='2062' u='r' c='mpv_reconstruct_mb_internal'/>
<use f='ffmpeg/libavcodec/mpegvideo.c' l='2067' u='r' c='mpv_reconstruct_mb_internal'/>
<use f='ffmpeg/libavcodec/mpegvideo.c' l='2262' u='r' c='ff_mpeg_draw_horiz_band'/>
<use f='ffmpeg/libavcodec/mpegvideo.c' l='2263' u='r' c='ff_mpeg_draw_horiz_band'/>
<use f='ffmpeg/libavcodec/mpegvideo.c' l='2268' u='r' c='ff_init_block_index'/>
<use f='ffmpeg/libavcodec/mpegvideo.c' l='2269' u='r' c='ff_init_block_index'/>
<use f='ffmpeg/libavcodec/mpegvideo.c' l='2281' u='r' c='ff_init_block_index'/>
<use f='ffmpeg/libavcodec/mpegvideo.c' l='2282' u='r' c='ff_init_block_index'/>
<use f='ffmpeg/libavcodec/mpegvideo.c' l='2283' u='r' c='ff_init_block_index'/>
<use f='ffmpeg/libavcodec/mpegvideo_enc.c' l='1239' u='r' c='load_input_picture'/>
<use f='ffmpeg/libavcodec/mpegvideo_enc.c' l='1247' u='r' c='load_input_picture'/>
<use f='ffmpeg/libavcodec/mpegvideo_enc.c' l='1248' u='r' c='load_input_picture'/>
<use f='ffmpeg/libavcodec/mpegvideo_enc.c' l='1249' u='r' c='load_input_picture'/>
<use f='ffmpeg/libavcodec/mpegvideo_enc.c' l='1265' u='r' c='load_input_picture'/>
<use f='ffmpeg/libavcodec/mpegvideo_enc.c' l='1298' u='r' c='load_input_picture'/>
<use f='ffmpeg/libavcodec/mpegvideo_enc.c' l='1302' u='r' c='load_input_picture'/>
<use f='ffmpeg/libavcodec/mpegvideo_enc.c' l='1303' u='r' c='load_input_picture'/>
<use f='ffmpeg/libavcodec/mpegvideo_enc.c' l='1333' u='r' c='skip_check'/>
<use f='ffmpeg/libavcodec/mpegvideo_enc.c' l='1338' u='r' c='skip_check'/>
<use f='ffmpeg/libavcodec/mpegvideo_enc.c' l='1339' u='r' c='skip_check'/>
<use f='ffmpeg/libavcodec/mpegvideo_enc.c' l='1423' u='r' c='estimate_best_b_count'/>
<use f='ffmpeg/libavcodec/mpegvideo_enc.c' l='1434' u='r' c='estimate_best_b_count'/>
<use f='ffmpeg/libavcodec/mpegvideo_enc.c' l='1439' u='r' c='estimate_best_b_count'/>
<use f='ffmpeg/libavcodec/mpegvideo_enc.c' l='1444' u='r' c='estimate_best_b_count'/>
<use f='ffmpeg/libavcodec/mpegvideo_enc.c' l='1550' u='r' c='select_input_picture'/>
<use f='ffmpeg/libavcodec/mpegvideo_enc.c' l='1561' u='r' c='select_input_picture'/>
<use f='ffmpeg/libavcodec/mpegvideo_enc.c' l='1562' u='r' c='select_input_picture'/>
<use f='ffmpeg/libavcodec/mpegvideo_enc.c' l='1569' u='r' c='select_input_picture'/>
<use f='ffmpeg/libavcodec/mpegvideo_enc.c' l='1578' u='r' c='select_input_picture'/>
<use f='ffmpeg/libavcodec/mpegvideo_enc.c' l='1593' u='r' c='select_input_picture'/>
<use f='ffmpeg/libavcodec/mpegvideo_enc.c' l='1594' u='r' c='select_input_picture'/>
<use f='ffmpeg/libavcodec/mpegvideo_enc.c' l='1620' u='r' c='select_input_picture'/>
<use f='ffmpeg/libavcodec/mpegvideo_enc.c' l='1624' u='r' c='select_input_picture'/>
<use f='ffmpeg/libavcodec/mpegvideo_enc.c' l='1637' u='r' c='select_input_picture'/>
<use f='ffmpeg/libavcodec/mpegvideo_enc.c' l='1642' u='r' c='select_input_picture'/>
<use f='ffmpeg/libavcodec/mpegvideo_enc.c' l='1646' u='r' c='select_input_picture'/>
<use f='ffmpeg/libavcodec/mpegvideo_enc.c' l='1647' u='r' c='select_input_picture'/>
<use f='ffmpeg/libavcodec/mpegvideo_enc.c' l='1648' u='r' c='select_input_picture'/>
<use f='ffmpeg/libavcodec/mpegvideo_enc.c' l='1652' u='r' c='select_input_picture'/>
<use f='ffmpeg/libavcodec/mpegvideo_enc.c' l='1654' u='r' c='select_input_picture'/>
<use f='ffmpeg/libavcodec/mpegvideo_enc.c' l='1664' u='r' c='select_input_picture'/>
<use f='ffmpeg/libavcodec/mpegvideo_enc.c' l='1685' u='r' c='select_input_picture'/>
<use f='ffmpeg/libavcodec/mpegvideo_enc.c' l='1685' u='r' c='select_input_picture'/>
<use f='ffmpeg/libavcodec/mpegvideo_enc.c' l='1690' u='r' c='select_input_picture'/>
<use f='ffmpeg/libavcodec/mpegvideo_enc.c' l='1698' u='r' c='select_input_picture'/>
<use f='ffmpeg/libavcodec/mpegvideo_enc.c' l='1699' u='r' c='select_input_picture'/>
<use f='ffmpeg/libavcodec/mpegvideo_enc.c' l='1707' u='r' c='select_input_picture'/>
<use f='ffmpeg/libavcodec/mpegvideo_enc.c' l='1720' u='r' c='frame_end'/>
<use f='ffmpeg/libavcodec/mpegvideo_enc.c' l='1721' u='r' c='frame_end'/>
<use f='ffmpeg/libavcodec/mpegvideo_enc.c' l='1725' u='r' c='frame_end'/>
<use f='ffmpeg/libavcodec/mpegvideo_enc.c' l='1726' u='r' c='frame_end'/>
<use f='ffmpeg/libavcodec/mpegvideo_enc.c' l='1732' u='r' c='frame_end'/>
<use f='ffmpeg/libavcodec/mpegvideo_enc.c' l='1733' u='r' c='frame_end'/>
<use f='ffmpeg/libavcodec/mpegvideo_enc.c' l='1744' u='r' c='frame_end'/>
<use f='ffmpeg/libavcodec/mpegvideo_enc.c' l='1751' u='r' c='frame_end'/>
<use f='ffmpeg/libavcodec/mpegvideo_enc.c' l='1756' u='r' c='frame_end'/>
<use f='ffmpeg/libavcodec/mpegvideo_enc.c' l='1790' u='r' c='frame_start'/>
<use f='ffmpeg/libavcodec/mpegvideo_enc.c' l='1794' u='r' c='frame_start'/>
<use f='ffmpeg/libavcodec/mpegvideo_enc.c' l='1795' u='r' c='frame_start'/>
<use f='ffmpeg/libavcodec/mpegvideo_enc.c' l='1810' u='r' c='frame_start'/>
<use f='ffmpeg/libavcodec/mpegvideo_enc.c' l='1817' u='r' c='frame_start'/>
<use f='ffmpeg/libavcodec/mpegvideo_enc.c' l='1827' u='r' c='frame_start'/>
<use f='ffmpeg/libavcodec/mpegvideo_enc.c' l='1828' u='r' c='frame_start'/>
<use f='ffmpeg/libavcodec/mpegvideo_enc.c' l='1830' u='r' c='frame_start'/>
<use f='ffmpeg/libavcodec/mpegvideo_enc.c' l='1831' u='r' c='frame_start'/>
<use f='ffmpeg/libavcodec/mpegvideo_enc.c' l='1832' u='r' c='frame_start'/>
<use f='ffmpeg/libavcodec/mpegvideo_enc.c' l='1874' u='r' c='ff_mpv_encode_picture'/>
<use f='ffmpeg/libavcodec/mpegvideo_enc.c' l='1898' u='r' c='ff_mpv_encode_picture'/>
<use f='ffmpeg/libavcodec/mpegvideo_enc.c' l='1981' u='r' c='ff_mpv_encode_picture'/>
<use f='ffmpeg/libavcodec/mpegvideo_enc.c' l='2086' u='r' c='ff_mpv_encode_picture'/>
<use f='ffmpeg/libavcodec/mpegvideo_enc.c' l='2088' u='r' c='ff_mpv_encode_picture'/>
<use f='ffmpeg/libavcodec/mpegvideo_enc.c' l='2095' u='r' c='ff_mpv_encode_picture'/>
<use f='ffmpeg/libavcodec/mpegvideo_enc.c' l='2282' u='r' c='encode_mb_internal'/>
<use f='ffmpeg/libavcodec/mpegvideo_enc.c' l='2284' u='r' c='encode_mb_internal'/>
<use f='ffmpeg/libavcodec/mpegvideo_enc.c' l='2286' u='r' c='encode_mb_internal'/>
<use f='ffmpeg/libavcodec/mpegvideo_enc.c' l='2381' u='r' c='encode_mb_internal'/>
<use f='ffmpeg/libavcodec/mpegvideo_enc.c' l='2388' u='r' c='encode_mb_internal'/>
<use f='ffmpeg/libavcodec/mpegvideo_enc.c' l='2769' u='r' c='sse_mb'/>
<use f='ffmpeg/libavcodec/mpegvideo_enc.c' l='2770' u='r' c='sse_mb'/>
<use f='ffmpeg/libavcodec/mpegvideo_enc.c' l='2771' u='r' c='sse_mb'/>
<use f='ffmpeg/libavcodec/mpegvideo_enc.c' l='2773' u='r' c='sse_mb'/>
<use f='ffmpeg/libavcodec/mpegvideo_enc.c' l='2774' u='r' c='sse_mb'/>
<use f='ffmpeg/libavcodec/mpegvideo_enc.c' l='2775' u='r' c='sse_mb'/>
<use f='ffmpeg/libavcodec/mpegvideo_enc.c' l='2778' u='r' c='sse_mb'/>
<use f='ffmpeg/libavcodec/mpegvideo_enc.c' l='2779' u='r' c='sse_mb'/>
<use f='ffmpeg/libavcodec/mpegvideo_enc.c' l='2780' u='r' c='sse_mb'/>
<use f='ffmpeg/libavcodec/mpegvideo_enc.c' l='2835' u='r' c='mb_var_thread'/>
<use f='ffmpeg/libavcodec/mpegvideo_enc.c' l='3566' u='r' c='encode_thread'/>
<use f='ffmpeg/libavcodec/mpegvideo_enc.c' l='3569' u='r' c='encode_thread'/>
<use f='ffmpeg/libavcodec/mpegvideo_enc.c' l='3572' u='r' c='encode_thread'/>
<use f='ffmpeg/libavcodec/mpegvideo_enc.c' l='3647' u='r' c='estimate_qp'/>
<use f='ffmpeg/libavcodec/mpegvideo_enc.c' l='3648' u='r' c='estimate_qp'/>
<use f='ffmpeg/libavcodec/mpegvideo_enc.c' l='3652' u='r' c='estimate_qp'/>
<use f='ffmpeg/libavcodec/mpegvideo_enc.c' l='3653' u='r' c='estimate_qp'/>
<use f='ffmpeg/libavcodec/mpegvideo_enc.c' l='3654' u='r' c='estimate_qp'/>
<use f='ffmpeg/libavcodec/mpegvideo_enc.c' l='3677' u='r' c='estimate_qp'/>
<use f='ffmpeg/libavcodec/mpegvideo_enc.c' l='3685' u='r' c='set_frame_distances'/>
<use f='ffmpeg/libavcodec/mpegvideo_enc.c' l='3913' u='r' c='encode_picture'/>
<use f='ffmpeg/libavcodec/mpegvideo_enc.c' l='3914' u='r' c='encode_picture'/>
<use f='ffmpeg/libavcodec/mpegvideo_enc.c' l='3915' u='r' c='encode_picture'/>
<use f='ffmpeg/libavcodec/mpegvideo_enc.c' l='3916' u='r' c='encode_picture'/>
<use f='ffmpeg/libavcodec/mpegvideo_enc.c' l='3918' u='r' c='encode_picture'/>
<use f='ffmpeg/libavcodec/mpegvideo_motion.c' l='248' u='r' c='mpeg_motion_internal'/>
<use f='ffmpeg/libavcodec/mpegvideo_motion.c' l='249' u='r' c='mpeg_motion_internal'/>
<use f='ffmpeg/libavcodec/mpegvideo_motion.c' l='903' u='r' c='mpv_motion_internal'/>
<use f='ffmpeg/libavcodec/mpegvideo_motion.c' l='922' u='r' c='mpv_motion_internal'/>
<use f='ffmpeg/libavcodec/mpegvideo_motion.c' l='950' u='r' c='mpv_motion_internal'/>
<use f='ffmpeg/libavcodec/mpegvideo_motion.c' l='965' u='r' c='mpv_motion_internal'/>
<use f='ffmpeg/libavcodec/msmpeg4.c' l='280' u='r' c='ff_msmpeg4_pred_dc'/>
<use f='ffmpeg/libavcodec/msmpeg4.c' l='283' u='r' c='ff_msmpeg4_pred_dc'/>
<use f='ffmpeg/libavcodec/mss2.c' l='434' u='r' c='decode_wmv9'/>
<use f='ffmpeg/libavcodec/ratecontrol.c' l='43' u='r' c='ff_write_pass1_stats'/>
<use f='ffmpeg/libavcodec/ratecontrol.c' l='44' u='r' c='ff_write_pass1_stats'/>
<use f='ffmpeg/libavcodec/ratecontrol.c' l='46' u='r' c='ff_write_pass1_stats'/>
<use f='ffmpeg/libavcodec/ratecontrol.c' l='923' u='r' c='ff_rate_estimate_qscale'/>
<use f='ffmpeg/libavcodec/ratecontrol.c' l='926' u='r' c='ff_rate_estimate_qscale'/>
<use f='ffmpeg/libavcodec/rv10.c' l='483' u='r' c='rv10_decode_packet'/>
<use f='ffmpeg/libavcodec/rv10.c' l='658' u='r' c='rv10_decode_frame'/>
<use f='ffmpeg/libavcodec/rv10.c' l='663' u='r' c='rv10_decode_frame'/>
<use f='ffmpeg/libavcodec/rv30.c' l='177' u='r' c='rv30_loop_filter'/>
<use f='ffmpeg/libavcodec/rv30.c' l='197' u='r' c='rv30_loop_filter'/>
<use f='ffmpeg/libavcodec/rv30.c' l='219' u='r' c='rv30_loop_filter'/>
<use f='ffmpeg/libavcodec/rv30.c' l='239' u='r' c='rv30_loop_filter'/>
<use f='ffmpeg/libavcodec/rv34.c' l='709' u='r' c='rv34_mc'/>
<use f='ffmpeg/libavcodec/rv34.c' l='709' u='r' c='rv34_mc'/>
<use f='ffmpeg/libavcodec/rv34.c' l='710' u='r' c='rv34_mc'/>
<use f='ffmpeg/libavcodec/rv34.c' l='710' u='r' c='rv34_mc'/>
<use f='ffmpeg/libavcodec/rv34.c' l='711' u='r' c='rv34_mc'/>
<use f='ffmpeg/libavcodec/rv34.c' l='711' u='r' c='rv34_mc'/>
<use f='ffmpeg/libavcodec/rv34.c' l='1580' u='r' c='finish_frame'/>
<use f='ffmpeg/libavcodec/rv34.c' l='1586' u='r' c='finish_frame'/>
<use f='ffmpeg/libavcodec/rv34.c' l='1627' u='r' c='ff_rv34_decode_frame'/>
<use f='ffmpeg/libavcodec/rv34.c' l='1655' u='r' c='ff_rv34_decode_frame'/>
<use f='ffmpeg/libavcodec/rv40.c' l='465' u='r' c='rv40_loop_filter'/>
<use f='ffmpeg/libavcodec/rv40.c' l='510' u='r' c='rv40_loop_filter'/>
<use f='ffmpeg/libavcodec/snowenc.c' l='1668' u='w' c='encode_frame'/>
<use f='ffmpeg/libavcodec/snowenc.c' l='1669' u='r' c='encode_frame'/>
<use f='ffmpeg/libavcodec/snowenc.c' l='1679' u='w' c='encode_frame'/>
<use f='ffmpeg/libavcodec/snowenc.c' l='1680' u='w' c='encode_frame'/>
<use f='ffmpeg/libavcodec/snowenc.c' l='1883' u='r' c='encode_frame'/>
<use f='ffmpeg/libavcodec/snowenc.c' l='1884' u='r' c='encode_frame'/>
<use f='ffmpeg/libavcodec/snowenc.c' l='1885' u='r' c='encode_frame'/>
<use f='ffmpeg/libavcodec/svq1enc.c' l='274' u='r' c='svq1_encode_plane'/>
<use f='ffmpeg/libavcodec/svq1enc.c' l='276' u='r' c='svq1_encode_plane'/>
<use f='ffmpeg/libavcodec/svq1enc.c' l='277' u='r' c='svq1_encode_plane'/>
<use f='ffmpeg/libavcodec/svq1enc.c' l='278' u='r' c='svq1_encode_plane'/>
<use f='ffmpeg/libavcodec/svq1enc.c' l='327' u='r' c='svq1_encode_plane'/>
<use f='ffmpeg/libavcodec/vc1.c' l='861' u='r' c='ff_vc1_parse_frame_header_adv'/>
<use f='ffmpeg/libavcodec/vc1_block.c' l='64' u='r' c='init_block_index'/>
<use f='ffmpeg/libavcodec/vc1_block.c' l='65' u='r' c='init_block_index'/>
<use f='ffmpeg/libavcodec/vc1_block.c' l='66' u='r' c='init_block_index'/>
<use f='ffmpeg/libavcodec/vc1_block.c' l='2975' u='r' c='vc1_decode_skip_blocks'/>
<use f='ffmpeg/libavcodec/vc1_block.c' l='2984' u='r' c='vc1_decode_skip_blocks'/>
<use f='ffmpeg/libavcodec/vc1_block.c' l='2985' u='r' c='vc1_decode_skip_blocks'/>
<use f='ffmpeg/libavcodec/vc1_block.c' l='2986' u='r' c='vc1_decode_skip_blocks'/>
<use f='ffmpeg/libavcodec/vc1_mc.c' l='187' u='r' c='ff_vc1_mc_1mv'/>
<use f='ffmpeg/libavcodec/vc1_mc.c' l='190' u='r' c='ff_vc1_mc_1mv'/>
<use f='ffmpeg/libavcodec/vc1_mc.c' l='191' u='r' c='ff_vc1_mc_1mv'/>
<use f='ffmpeg/libavcodec/vc1_mc.c' l='222' u='r' c='ff_vc1_mc_1mv'/>
<use f='ffmpeg/libavcodec/vc1_mc.c' l='223' u='r' c='ff_vc1_mc_1mv'/>
<use f='ffmpeg/libavcodec/vc1_mc.c' l='224' u='r' c='ff_vc1_mc_1mv'/>
<use f='ffmpeg/libavcodec/vc1_mc.c' l='230' u='r' c='ff_vc1_mc_1mv'/>
<use f='ffmpeg/libavcodec/vc1_mc.c' l='231' u='r' c='ff_vc1_mc_1mv'/>
<use f='ffmpeg/libavcodec/vc1_mc.c' l='232' u='r' c='ff_vc1_mc_1mv'/>
<use f='ffmpeg/libavcodec/vc1_mc.c' l='236' u='r' c='ff_vc1_mc_1mv'/>
<use f='ffmpeg/libavcodec/vc1_mc.c' l='239' u='r' c='ff_vc1_mc_1mv'/>
<use f='ffmpeg/libavcodec/vc1_mc.c' l='240' u='r' c='ff_vc1_mc_1mv'/>
<use f='ffmpeg/libavcodec/vc1_mc.c' l='241' u='r' c='ff_vc1_mc_1mv'/>
<use f='ffmpeg/libavcodec/vc1_mc.c' l='245' u='r' c='ff_vc1_mc_1mv'/>
<use f='ffmpeg/libavcodec/vc1_mc.c' l='467' u='r' c='ff_vc1_mc_4mv_luma'/>
<use f='ffmpeg/libavcodec/vc1_mc.c' l='470' u='r' c='ff_vc1_mc_4mv_luma'/>
<use f='ffmpeg/libavcodec/vc1_mc.c' l='477' u='r' c='ff_vc1_mc_4mv_luma'/>
<use f='ffmpeg/libavcodec/vc1_mc.c' l='482' u='r' c='ff_vc1_mc_4mv_luma'/>
<use f='ffmpeg/libavcodec/vc1_mc.c' l='485' u='r' c='ff_vc1_mc_4mv_luma'/>
<use f='ffmpeg/libavcodec/vc1_mc.c' l='488' u='r' c='ff_vc1_mc_4mv_luma'/>
<use f='ffmpeg/libavcodec/vc1_mc.c' l='491' u='r' c='ff_vc1_mc_4mv_luma'/>
<use f='ffmpeg/libavcodec/vc1_mc.c' l='648' u='r' c='ff_vc1_mc_4mv_chroma'/>
<use f='ffmpeg/libavcodec/vc1_mc.c' l='667' u='r' c='ff_vc1_mc_4mv_chroma'/>
<use f='ffmpeg/libavcodec/vc1_mc.c' l='672' u='r' c='ff_vc1_mc_4mv_chroma'/>
<use f='ffmpeg/libavcodec/vc1_mc.c' l='701' u='r' c='ff_vc1_mc_4mv_chroma'/>
<use f='ffmpeg/libavcodec/vc1_mc.c' l='702' u='r' c='ff_vc1_mc_4mv_chroma'/>
<use f='ffmpeg/libavcodec/vc1_mc.c' l='707' u='r' c='ff_vc1_mc_4mv_chroma'/>
<use f='ffmpeg/libavcodec/vc1_mc.c' l='708' u='r' c='ff_vc1_mc_4mv_chroma'/>
<use f='ffmpeg/libavcodec/vc1_mc.c' l='711' u='r' c='ff_vc1_mc_4mv_chroma'/>
<use f='ffmpeg/libavcodec/vc1_mc.c' l='714' u='r' c='ff_vc1_mc_4mv_chroma'/>
<use f='ffmpeg/libavcodec/vc1_mc.c' l='715' u='r' c='ff_vc1_mc_4mv_chroma'/>
<use f='ffmpeg/libavcodec/vc1_mc.c' l='718' u='r' c='ff_vc1_mc_4mv_chroma'/>
<use f='ffmpeg/libavcodec/vc1_mc.c' l='859' u='r' c='ff_vc1_mc_4mv_chroma4'/>
<use f='ffmpeg/libavcodec/vc1_mc.c' l='883' u='r' c='ff_vc1_mc_4mv_chroma4'/>
<use f='ffmpeg/libavcodec/vc1_mc.c' l='884' u='r' c='ff_vc1_mc_4mv_chroma4'/>
<use f='ffmpeg/libavcodec/vc1_mc.c' l='887' u='r' c='ff_vc1_mc_4mv_chroma4'/>
<use f='ffmpeg/libavcodec/vc1_mc.c' l='889' u='r' c='ff_vc1_mc_4mv_chroma4'/>
<use f='ffmpeg/libavcodec/vc1_mc.c' l='890' u='r' c='ff_vc1_mc_4mv_chroma4'/>
<use f='ffmpeg/libavcodec/vc1_mc.c' l='893' u='r' c='ff_vc1_mc_4mv_chroma4'/>
<use f='ffmpeg/libavcodec/vc1_mc.c' l='1015' u='r' c='ff_vc1_interp_mc'/>
<use f='ffmpeg/libavcodec/vc1_mc.c' l='1018' u='r' c='ff_vc1_interp_mc'/>
<use f='ffmpeg/libavcodec/vc1_mc.c' l='1019' u='r' c='ff_vc1_interp_mc'/>
<use f='ffmpeg/libavcodec/vc1_mc.c' l='1033' u='r' c='ff_vc1_interp_mc'/>
<use f='ffmpeg/libavcodec/vc1_mc.c' l='1034' u='r' c='ff_vc1_interp_mc'/>
<use f='ffmpeg/libavcodec/vc1_mc.c' l='1035' u='r' c='ff_vc1_interp_mc'/>
<use f='ffmpeg/libavcodec/vc1_mc.c' l='1037' u='r' c='ff_vc1_interp_mc'/>
<use f='ffmpeg/libavcodec/vc1dec.c' l='203' u='r' c='vc1_draw_sprites'/>
<use f='ffmpeg/libavcodec/vc1dec.c' l='204' u='r' c='vc1_draw_sprites'/>
<use f='ffmpeg/libavcodec/vc1dec.c' l='210' u='r' c='vc1_draw_sprites'/>
<use f='ffmpeg/libavcodec/vc1dec.c' l='211' u='r' c='vc1_draw_sprites'/>
<use f='ffmpeg/libavcodec/vc1dec.c' l='285' u='r' c='vc1_decode_sprites'/>
<use f='ffmpeg/libavcodec/vc1dec.c' l='285' u='r' c='vc1_decode_sprites'/>
<use f='ffmpeg/libavcodec/vc1dec.c' l='290' u='r' c='vc1_decode_sprites'/>
<use f='ffmpeg/libavcodec/vc1dec.c' l='308' u='r' c='vc1_sprite_flush'/>
<use f='ffmpeg/libavcodec/vc1dec.c' l='651' u='r' c='vc1_decode_frame'/>
<use f='ffmpeg/libavcodec/vc1dec.c' l='859' u='r' c='vc1_decode_frame'/>
<use f='ffmpeg/libavcodec/vc1dec.c' l='860' u='r' c='vc1_decode_frame'/>
<use f='ffmpeg/libavcodec/vc1dec.c' l='885' u='r' c='vc1_decode_frame'/>
<use f='ffmpeg/libavcodec/vc1dec.c' l='886' u='r' c='vc1_decode_frame'/>
<use f='ffmpeg/libavcodec/vc1dec.c' l='889' u='r' c='vc1_decode_frame'/>
<use f='ffmpeg/libavcodec/vc1dec.c' l='894' u='r' c='vc1_decode_frame'/>
<use f='ffmpeg/libavcodec/vc1dec.c' l='897' u='r' c='vc1_decode_frame'/>
<use f='ffmpeg/libavcodec/vc1dec.c' l='953' u='r' c='vc1_decode_frame'/>
<use f='ffmpeg/libavcodec/vc1dec.c' l='1032' u='r' c='vc1_decode_frame'/>
<use f='ffmpeg/libavcodec/vc1dec.c' l='1033' u='r' c='vc1_decode_frame'/>
<use f='ffmpeg/libavcodec/vc1dec.c' l='1034' u='r' c='vc1_decode_frame'/>
<use f='ffmpeg/libavcodec/vc1dec.c' l='1109' u='r' c='vc1_decode_frame'/>
<use f='ffmpeg/libavcodec/vc1dec.c' l='1110' u='r' c='vc1_decode_frame'/>
<use f='ffmpeg/libavcodec/vc1dec.c' l='1111' u='r' c='vc1_decode_frame'/>
<use f='ffmpeg/libavcodec/vc1dec.c' l='1153' u='r' c='vc1_decode_frame'/>
<use f='ffmpeg/libavcodec/vc1dec.c' l='1158' u='r' c='vc1_decode_frame'/>
