<dec f='ffmpeg/libavformat/rtpdec.h' l='149' type='AVStream *'/>
<offset>64</offset>
<use f='ffmpeg/libavformat/rtpdec.c' l='577' u='w' c='ff_rtp_parse_open'/>
<use f='ffmpeg/libavformat/rtpdec.c' l='644' u='r' c='finalize_packet'/>
<use f='ffmpeg/libavformat/rtpdec.c' l='645' u='r' c='finalize_packet'/>
<use f='ffmpeg/libavformat/rtpdec.c' l='689' u='r' c='rtp_parse_packet_internal'/>
<use f='ffmpeg/libavformat/rtpdec.c' l='730' u='r' c='rtp_parse_packet_internal'/>
<use f='ffmpeg/libavformat/rtpdec.c' l='839' u='r' c='rtp_parse_one_packet'/>
<use f='ffmpeg/libavformat/rtpdec.c' l='855' u='r' c='rtp_parse_one_packet'/>
<use f='ffmpeg/libavformat/rtpdec.c' l='858' u='r' c='rtp_parse_one_packet'/>
<use f='ffmpeg/libavformat/rtsp.c' l='2303' u='r' c='ff_rtsp_fetch_packet'/>
<use f='ffmpeg/libavformat/rtsp.c' l='2305' u='r' c='ff_rtsp_fetch_packet'/>
