<dec f='ffmpeg/libavcodec/sbcdsp.h' l='49' type='int16_t [2][328]'/>
<offset>128</offset>
<use f='ffmpeg/libavcodec/sbcenc.c' l='57' u='a' c='sbc_analyze_audio'/>
<use f='ffmpeg/libavcodec/sbcenc.c' l='73' u='a' c='sbc_analyze_audio'/>
<use f='ffmpeg/libavcodec/sbcenc.c' l='268' u='a' c='sbc_encode_init'/>
<use f='ffmpeg/libavcodec/sbcenc.c' l='268' u='r' c='sbc_encode_init'/>
<use f='ffmpeg/libavcodec/sbcenc.c' l='299' c='sbc_encode_frame'/>
<use f='ffmpeg/libavcodec/sbcenc.c' l='303' c='sbc_encode_frame'/>
