<dec f='ffmpeg/libavcodec/snow.h' l='117' type='RangeCoder'/>
<use f='ffmpeg/libavcodec/snow.h' l='615' u='a' c='unpack_coeffs'/>
<use f='ffmpeg/libavcodec/snow.h' l='616' u='a' c='unpack_coeffs'/>
<use f='ffmpeg/libavcodec/snow.h' l='651' u='a' c='unpack_coeffs'/>
<use f='ffmpeg/libavcodec/snow.h' l='653' u='a' c='unpack_coeffs'/>
<use f='ffmpeg/libavcodec/snow.h' l='654' u='a' c='unpack_coeffs'/>
<use f='ffmpeg/libavcodec/snow.h' l='664' u='a' c='unpack_coeffs'/>
<use f='ffmpeg/libavcodec/snow.h' l='666' u='a' c='unpack_coeffs'/>
<use f='ffmpeg/libavcodec/snow.h' l='667' u='a' c='unpack_coeffs'/>
<offset>128</offset>
<use f='ffmpeg/libavcodec/snowdec.c' l='175' u='a' c='decode_q_branch'/>
<use f='ffmpeg/libavcodec/snowdec.c' l='185' u='a' c='decode_q_branch'/>
<use f='ffmpeg/libavcodec/snowdec.c' l='189' u='a' c='decode_q_branch'/>
<use f='ffmpeg/libavcodec/snowdec.c' l='195' u='a' c='decode_q_branch'/>
<use f='ffmpeg/libavcodec/snowdec.c' l='196' u='a' c='decode_q_branch'/>
<use f='ffmpeg/libavcodec/snowdec.c' l='205' u='a' c='decode_q_branch'/>
<use f='ffmpeg/libavcodec/snowdec.c' l='211' u='a' c='decode_q_branch'/>
<use f='ffmpeg/libavcodec/snowdec.c' l='212' u='a' c='decode_q_branch'/>
<use f='ffmpeg/libavcodec/snowdec.c' l='287' u='a' c='decode_qlogs'/>
<use f='ffmpeg/libavcodec/snowdec.c' l='308' u='a' c='decode_header'/>
<use f='ffmpeg/libavcodec/snowdec.c' l='295' u='a' c='decode_header'/>
<use f='ffmpeg/libavcodec/snowdec.c' l='319' u='a' c='decode_header'/>
<use f='ffmpeg/libavcodec/snowdec.c' l='320' u='a' c='decode_header'/>
<use f='ffmpeg/libavcodec/snowdec.c' l='321' u='a' c='decode_header'/>
<use f='ffmpeg/libavcodec/snowdec.c' l='295' u='a' c='decode_header'/>
<use f='ffmpeg/libavcodec/snowdec.c' l='323' u='a' c='decode_header'/>
<use f='ffmpeg/libavcodec/snowdec.c' l='328' u='a' c='decode_header'/>
<use f='ffmpeg/libavcodec/snowdec.c' l='329' u='a' c='decode_header'/>
<use f='ffmpeg/libavcodec/snowdec.c' l='352' u='a' c='decode_header'/>
<use f='ffmpeg/libavcodec/snowdec.c' l='295' u='a' c='decode_header'/>
<use f='ffmpeg/libavcodec/snowdec.c' l='361' u='a' c='decode_header'/>
<use f='ffmpeg/libavcodec/snowdec.c' l='365' u='a' c='decode_header'/>
<use f='ffmpeg/libavcodec/snowdec.c' l='366' u='a' c='decode_header'/>
<use f='ffmpeg/libavcodec/snowdec.c' l='372' u='a' c='decode_header'/>
<use f='ffmpeg/libavcodec/snowdec.c' l='384' u='a' c='decode_header'/>
<use f='ffmpeg/libavcodec/snowdec.c' l='295' u='a' c='decode_header'/>
<use f='ffmpeg/libavcodec/snowdec.c' l='390' u='a' c='decode_header'/>
<use f='ffmpeg/libavcodec/snowdec.c' l='406' u='a' c='decode_header'/>
<use f='ffmpeg/libavcodec/snowdec.c' l='407' u='a' c='decode_header'/>
<use f='ffmpeg/libavcodec/snowdec.c' l='408' u='a' c='decode_header'/>
<use f='ffmpeg/libavcodec/snowdec.c' l='409' u='a' c='decode_header'/>
<use f='ffmpeg/libavcodec/snowdec.c' l='433' u='m' c='decode_blocks'/>
<use f='ffmpeg/libavcodec/snowdec.c' l='433' u='m' c='decode_blocks'/>
<use f='ffmpeg/libavcodec/snowdec.c' l='448' u='a' c='decode_frame'/>
<use f='ffmpeg/libavcodec/snowenc.c' l='235' u='m' c='encode_q_branch'/>
<use f='ffmpeg/libavcodec/snowenc.c' l='236' u='m' c='encode_q_branch'/>
<use f='ffmpeg/libavcodec/snowenc.c' l='363' u='a' c='encode_q_branch'/>
<use f='ffmpeg/libavcodec/snowenc.c' l='363' u='m' c='encode_q_branch'/>
<use f='ffmpeg/libavcodec/snowenc.c' l='363' u='m' c='encode_q_branch'/>
<use f='ffmpeg/libavcodec/snowenc.c' l='364' u='r' c='encode_q_branch'/>
<use f='ffmpeg/libavcodec/snowenc.c' l='396' u='r' c='encode_q_branch'/>
<use f='ffmpeg/libavcodec/snowenc.c' l='426' u='a' c='encode_q_branch'/>
<use f='ffmpeg/libavcodec/snowenc.c' l='440' u='w' c='encode_q_branch'/>
<use f='ffmpeg/libavcodec/snowenc.c' l='441' u='m' c='encode_q_branch'/>
<use f='ffmpeg/libavcodec/snowenc.c' l='442' u='m' c='encode_q_branch'/>
<use f='ffmpeg/libavcodec/snowenc.c' l='448' u='w' c='encode_q_branch'/>
<use f='ffmpeg/libavcodec/snowenc.c' l='449' u='m' c='encode_q_branch'/>
<use f='ffmpeg/libavcodec/snowenc.c' l='450' u='m' c='encode_q_branch'/>
<use f='ffmpeg/libavcodec/snowenc.c' l='483' u='a' c='encode_q_branch2'/>
<use f='ffmpeg/libavcodec/snowenc.c' l='485' u='a' c='encode_q_branch2'/>
<use f='ffmpeg/libavcodec/snowenc.c' l='495' u='a' c='encode_q_branch2'/>
<use f='ffmpeg/libavcodec/snowenc.c' l='496' u='a' c='encode_q_branch2'/>
<use f='ffmpeg/libavcodec/snowenc.c' l='498' u='a' c='encode_q_branch2'/>
<use f='ffmpeg/libavcodec/snowenc.c' l='499' u='a' c='encode_q_branch2'/>
<use f='ffmpeg/libavcodec/snowenc.c' l='504' u='a' c='encode_q_branch2'/>
<use f='ffmpeg/libavcodec/snowenc.c' l='506' u='a' c='encode_q_branch2'/>
<use f='ffmpeg/libavcodec/snowenc.c' l='507' u='a' c='encode_q_branch2'/>
<use f='ffmpeg/libavcodec/snowenc.c' l='508' u='a' c='encode_q_branch2'/>
<use f='ffmpeg/libavcodec/snowenc.c' l='833' u='a' c='encode_subband_c0run'/>
<use f='ffmpeg/libavcodec/snowenc.c' l='835' u='a' c='encode_subband_c0run'/>
<use f='ffmpeg/libavcodec/snowenc.c' l='838' u='m' c='encode_subband_c0run'/>
<use f='ffmpeg/libavcodec/snowenc.c' l='838' u='m' c='encode_subband_c0run'/>
<use f='ffmpeg/libavcodec/snowenc.c' l='872' u='a' c='encode_subband_c0run'/>
<use f='ffmpeg/libavcodec/snowenc.c' l='878' u='a' c='encode_subband_c0run'/>
<use f='ffmpeg/libavcodec/snowenc.c' l='890' u='a' c='encode_subband_c0run'/>
<use f='ffmpeg/libavcodec/snowenc.c' l='891' u='a' c='encode_subband_c0run'/>
<use f='ffmpeg/libavcodec/snowenc.c' l='1006' u='r' c='iterative_me'/>
<use f='ffmpeg/libavcodec/snowenc.c' l='1012' u='w' c='iterative_me'/>
<use f='ffmpeg/libavcodec/snowenc.c' l='1234' u='m' c='encode_blocks'/>
<use f='ffmpeg/libavcodec/snowenc.c' l='1234' u='m' c='encode_blocks'/>
<use f='ffmpeg/libavcodec/snowenc.c' l='1385' u='a' c='encode_qlogs'/>
<use f='ffmpeg/libavcodec/snowenc.c' l='1397' u='a' c='encode_header'/>
<use f='ffmpeg/libavcodec/snowenc.c' l='1413' u='a' c='encode_header'/>
<use f='ffmpeg/libavcodec/snowenc.c' l='1414' u='a' c='encode_header'/>
<use f='ffmpeg/libavcodec/snowenc.c' l='1415' u='a' c='encode_header'/>
<use f='ffmpeg/libavcodec/snowenc.c' l='1416' u='a' c='encode_header'/>
<use f='ffmpeg/libavcodec/snowenc.c' l='1417' u='a' c='encode_header'/>
<use f='ffmpeg/libavcodec/snowenc.c' l='1418' u='a' c='encode_header'/>
<use f='ffmpeg/libavcodec/snowenc.c' l='1420' u='a' c='encode_header'/>
<use f='ffmpeg/libavcodec/snowenc.c' l='1421' u='a' c='encode_header'/>
<use f='ffmpeg/libavcodec/snowenc.c' l='1423' u='a' c='encode_header'/>
<use f='ffmpeg/libavcodec/snowenc.c' l='1425' u='a' c='encode_header'/>
<use f='ffmpeg/libavcodec/snowenc.c' l='1438' u='a' c='encode_header'/>
<use f='ffmpeg/libavcodec/snowenc.c' l='1442' u='a' c='encode_header'/>
<use f='ffmpeg/libavcodec/snowenc.c' l='1443' u='a' c='encode_header'/>
<use f='ffmpeg/libavcodec/snowenc.c' l='1445' u='a' c='encode_header'/>
<use f='ffmpeg/libavcodec/snowenc.c' l='1449' u='a' c='encode_header'/>
<use f='ffmpeg/libavcodec/snowenc.c' l='1450' u='a' c='encode_header'/>
<use f='ffmpeg/libavcodec/snowenc.c' l='1453' u='a' c='encode_header'/>
<use f='ffmpeg/libavcodec/snowenc.c' l='1456' u='a' c='encode_header'/>
<use f='ffmpeg/libavcodec/snowenc.c' l='1457' u='a' c='encode_header'/>
<use f='ffmpeg/libavcodec/snowenc.c' l='1458' u='a' c='encode_header'/>
<use f='ffmpeg/libavcodec/snowenc.c' l='1459' u='a' c='encode_header'/>
<use f='ffmpeg/libavcodec/snowenc.c' l='1460' u='a' c='encode_header'/>
<use f='ffmpeg/libavcodec/snowenc.c' l='1571' u='a' c='encode_frame'/>
<use f='ffmpeg/libavcodec/snowenc.c' l='1741' u='m' c='encode_frame'/>
<use f='ffmpeg/libavcodec/snowenc.c' l='1741' u='m' c='encode_frame'/>
<use f='ffmpeg/libavcodec/snowenc.c' l='1743' u='m' c='encode_frame'/>
<use f='ffmpeg/libavcodec/snowenc.c' l='1743' u='m' c='encode_frame'/>
<use f='ffmpeg/libavcodec/snowenc.c' l='1881' u='m' c='encode_frame'/>
<use f='ffmpeg/libavcodec/snowenc.c' l='1881' u='m' c='encode_frame'/>
<use f='ffmpeg/libavcodec/snowenc.c' l='1886' u='m' c='encode_frame'/>
<use f='ffmpeg/libavcodec/snowenc.c' l='1886' u='m' c='encode_frame'/>
