<dec f='ffmpeg/libavcodec/snow.h' l='183' type='MpegEncContext'/>
<use f='ffmpeg/libavcodec/snow.c' l='709' u='m' c='ff_snow_common_end'/>
<use f='ffmpeg/libavcodec/snow.c' l='710' u='m' c='ff_snow_common_end'/>
<use f='ffmpeg/libavcodec/snow.c' l='711' u='m' c='ff_snow_common_end'/>
<use f='ffmpeg/libavcodec/snow.c' l='712' u='m' c='ff_snow_common_end'/>
<use f='ffmpeg/libavcodec/snow.c' l='713' u='m' c='ff_snow_common_end'/>
<offset>17192064</offset>
<doc f='ffmpeg/libavcodec/snow.h' l='183'>// needed for motion estimation, should not be used for anything else, the idea is to eventually make the motion estimation independent of MpegEncContext, so this will be removed then (FIXME/XXX)</doc>
<use f='ffmpeg/libavcodec/snowenc.c' l='81' u='m' c='encode_init'/>
<use f='ffmpeg/libavcodec/snowenc.c' l='82' u='m' c='encode_init'/>
<use f='ffmpeg/libavcodec/snowenc.c' l='83' u='m' c='encode_init'/>
<use f='ffmpeg/libavcodec/snowenc.c' l='84' u='m' c='encode_init'/>
<use f='ffmpeg/libavcodec/snowenc.c' l='85' u='m' c='encode_init'/>
<use f='ffmpeg/libavcodec/snowenc.c' l='87' u='m' c='encode_init'/>
<use f='ffmpeg/libavcodec/snowenc.c' l='88' u='m' c='encode_init'/>
<use f='ffmpeg/libavcodec/snowenc.c' l='89' u='m' c='encode_init'/>
<use f='ffmpeg/libavcodec/snowenc.c' l='90' u='m' c='encode_init'/>
<use f='ffmpeg/libavcodec/snowenc.c' l='91' u='m' c='encode_init'/>
<use f='ffmpeg/libavcodec/snowenc.c' l='92' u='m' c='encode_init'/>
<use f='ffmpeg/libavcodec/snowenc.c' l='92' u='m' c='encode_init'/>
<use f='ffmpeg/libavcodec/snowenc.c' l='92' u='m' c='encode_init'/>
<use f='ffmpeg/libavcodec/snowenc.c' l='92' u='m' c='encode_init'/>
<use f='ffmpeg/libavcodec/snowenc.c' l='95' u='a' c='encode_init'/>
<use f='ffmpeg/libavcodec/snowenc.c' l='107' u='a' c='encode_init'/>
<use f='ffmpeg/libavcodec/snowenc.c' l='266' u='m' c='encode_q_branch'/>
<use f='ffmpeg/libavcodec/snowenc.c' l='295' u='m' c='encode_q_branch'/>
<use f='ffmpeg/libavcodec/snowenc.c' l='296' u='m' c='encode_q_branch'/>
<use f='ffmpeg/libavcodec/snowenc.c' l='297' u='m' c='encode_q_branch'/>
<use f='ffmpeg/libavcodec/snowenc.c' l='306' u='m' c='encode_q_branch'/>
<use f='ffmpeg/libavcodec/snowenc.c' l='337' u='a' c='encode_q_branch'/>
<use f='ffmpeg/libavcodec/snowenc.c' l='345' u='a' c='encode_q_branch'/>
<use f='ffmpeg/libavcodec/snowenc.c' l='346' u='a' c='encode_q_branch'/>
<use f='ffmpeg/libavcodec/snowenc.c' l='422' u='m' c='encode_q_branch'/>
<use f='ffmpeg/libavcodec/snowenc.c' l='523' u='m' c='get_dc'/>
<use f='ffmpeg/libavcodec/snowenc.c' l='618' u='m' c='get_block_rd'/>
<use f='ffmpeg/libavcodec/snowenc.c' l='681' u='a' c='get_block_rd'/>
<use f='ffmpeg/libavcodec/snowenc.c' l='683' u='a' c='get_block_rd'/>
<use f='ffmpeg/libavcodec/snowenc.c' l='688' u='a' c='get_block_rd'/>
<use f='ffmpeg/libavcodec/snowenc.c' l='693' u='a' c='get_block_rd'/>
<use f='ffmpeg/libavcodec/snowenc.c' l='757' u='a' c='get_4block_rd'/>
<use f='ffmpeg/libavcodec/snowenc.c' l='1525' u='m' c='ratecontrol_1pass'/>
<use f='ffmpeg/libavcodec/snowenc.c' l='1526' u='m' c='ratecontrol_1pass'/>
<use f='ffmpeg/libavcodec/snowenc.c' l='1528' u='m' c='ratecontrol_1pass'/>
<use f='ffmpeg/libavcodec/snowenc.c' l='1529' u='m' c='ratecontrol_1pass'/>
<use f='ffmpeg/libavcodec/snowenc.c' l='1532' u='a' c='ratecontrol_1pass'/>
<use f='ffmpeg/libavcodec/snowenc.c' l='1603' u='m' c='encode_frame'/>
<use f='ffmpeg/libavcodec/snowenc.c' l='1605' u='m' c='encode_frame'/>
<use f='ffmpeg/libavcodec/snowenc.c' l='1605' u='m' c='encode_frame'/>
<use f='ffmpeg/libavcodec/snowenc.c' l='1608' u='a' c='encode_frame'/>
<use f='ffmpeg/libavcodec/snowenc.c' l='1614' u='m' c='encode_frame'/>
<use f='ffmpeg/libavcodec/snowenc.c' l='1667' u='m' c='encode_frame'/>
<use f='ffmpeg/libavcodec/snowenc.c' l='1667' u='m' c='encode_frame'/>
<use f='ffmpeg/libavcodec/snowenc.c' l='1668' u='m' c='encode_frame'/>
<use f='ffmpeg/libavcodec/snowenc.c' l='1669' u='m' c='encode_frame'/>
<use f='ffmpeg/libavcodec/snowenc.c' l='1678' u='m' c='encode_frame'/>
<use f='ffmpeg/libavcodec/snowenc.c' l='1679' u='m' c='encode_frame'/>
<use f='ffmpeg/libavcodec/snowenc.c' l='1680' u='m' c='encode_frame'/>
<use f='ffmpeg/libavcodec/snowenc.c' l='1681' u='m' c='encode_frame'/>
<use f='ffmpeg/libavcodec/snowenc.c' l='1681' u='m' c='encode_frame'/>
<use f='ffmpeg/libavcodec/snowenc.c' l='1682' u='m' c='encode_frame'/>
<use f='ffmpeg/libavcodec/snowenc.c' l='1683' u='m' c='encode_frame'/>
<use f='ffmpeg/libavcodec/snowenc.c' l='1684' u='m' c='encode_frame'/>
<use f='ffmpeg/libavcodec/snowenc.c' l='1685' u='m' c='encode_frame'/>
<use f='ffmpeg/libavcodec/snowenc.c' l='1686' u='m' c='encode_frame'/>
<use f='ffmpeg/libavcodec/snowenc.c' l='1687' u='m' c='encode_frame'/>
<use f='ffmpeg/libavcodec/snowenc.c' l='1688' u='m' c='encode_frame'/>
<use f='ffmpeg/libavcodec/snowenc.c' l='1688' u='m' c='encode_frame'/>
<use f='ffmpeg/libavcodec/snowenc.c' l='1689' u='m' c='encode_frame'/>
<use f='ffmpeg/libavcodec/snowenc.c' l='1689' u='m' c='encode_frame'/>
<use f='ffmpeg/libavcodec/snowenc.c' l='1690' u='m' c='encode_frame'/>
<use f='ffmpeg/libavcodec/snowenc.c' l='1691' u='m' c='encode_frame'/>
<use f='ffmpeg/libavcodec/snowenc.c' l='1692' u='m' c='encode_frame'/>
<use f='ffmpeg/libavcodec/snowenc.c' l='1693' u='m' c='encode_frame'/>
<use f='ffmpeg/libavcodec/snowenc.c' l='1694' u='m' c='encode_frame'/>
<use f='ffmpeg/libavcodec/snowenc.c' l='1695' u='m' c='encode_frame'/>
<use f='ffmpeg/libavcodec/snowenc.c' l='1696' u='m' c='encode_frame'/>
<use f='ffmpeg/libavcodec/snowenc.c' l='1697' u='m' c='encode_frame'/>
<use f='ffmpeg/libavcodec/snowenc.c' l='1699' u='m' c='encode_frame'/>
<use f='ffmpeg/libavcodec/snowenc.c' l='1700' u='m' c='encode_frame'/>
<use f='ffmpeg/libavcodec/snowenc.c' l='1700' u='m' c='encode_frame'/>
<use f='ffmpeg/libavcodec/snowenc.c' l='1701' u='m' c='encode_frame'/>
<use f='ffmpeg/libavcodec/snowenc.c' l='1701' u='m' c='encode_frame'/>
<use f='ffmpeg/libavcodec/snowenc.c' l='1701' u='m' c='encode_frame'/>
<use f='ffmpeg/libavcodec/snowenc.c' l='1703' u='m' c='encode_frame'/>
<use f='ffmpeg/libavcodec/snowenc.c' l='1704' u='m' c='encode_frame'/>
<use f='ffmpeg/libavcodec/snowenc.c' l='1705' u='m' c='encode_frame'/>
<use f='ffmpeg/libavcodec/snowenc.c' l='1706' u='a' c='encode_frame'/>
<use f='ffmpeg/libavcodec/snowenc.c' l='1707' u='m' c='encode_frame'/>
<use f='ffmpeg/libavcodec/snowenc.c' l='1708' u='m' c='encode_frame'/>
<use f='ffmpeg/libavcodec/snowenc.c' l='1729' u='m' c='encode_frame'/>
<use f='ffmpeg/libavcodec/snowenc.c' l='1741' u='m' c='encode_frame'/>
<use f='ffmpeg/libavcodec/snowenc.c' l='1743' u='m' c='encode_frame'/>
<use f='ffmpeg/libavcodec/snowenc.c' l='1743' u='m' c='encode_frame'/>
<use f='ffmpeg/libavcodec/snowenc.c' l='1772' u='m' c='encode_frame'/>
<use f='ffmpeg/libavcodec/snowenc.c' l='1881' u='m' c='encode_frame'/>
<use f='ffmpeg/libavcodec/snowenc.c' l='1882' u='m' c='encode_frame'/>
<use f='ffmpeg/libavcodec/snowenc.c' l='1882' u='m' c='encode_frame'/>
<use f='ffmpeg/libavcodec/snowenc.c' l='1882' u='m' c='encode_frame'/>
<use f='ffmpeg/libavcodec/snowenc.c' l='1882' u='m' c='encode_frame'/>
<use f='ffmpeg/libavcodec/snowenc.c' l='1883' u='m' c='encode_frame'/>
<use f='ffmpeg/libavcodec/snowenc.c' l='1884' u='m' c='encode_frame'/>
<use f='ffmpeg/libavcodec/snowenc.c' l='1885' u='m' c='encode_frame'/>
<use f='ffmpeg/libavcodec/snowenc.c' l='1886' u='m' c='encode_frame'/>
<use f='ffmpeg/libavcodec/snowenc.c' l='1888' u='a' c='encode_frame'/>
<use f='ffmpeg/libavcodec/snowenc.c' l='1891' u='a' c='encode_frame'/>
<use f='ffmpeg/libavcodec/snowenc.c' l='1892' u='m' c='encode_frame'/>
<use f='ffmpeg/libavcodec/snowenc.c' l='1892' u='m' c='encode_frame'/>
<use f='ffmpeg/libavcodec/snowenc.c' l='1895' u='m' c='encode_frame'/>
<use f='ffmpeg/libavcodec/snowenc.c' l='1896' u='m' c='encode_frame'/>
<use f='ffmpeg/libavcodec/snowenc.c' l='1897' u='m' c='encode_frame'/>
<use f='ffmpeg/libavcodec/snowenc.c' l='1898' u='m' c='encode_frame'/>
<use f='ffmpeg/libavcodec/snowenc.c' l='1928' u='a' c='encode_end'/>
