<dec f='ffmpeg/libavcodec/sbr.h' l='195' type='INTFLOAT [2][2][38][64]'/>
<offset>2729728</offset>
<doc f='ffmpeg/libavcodec/sbr.h' l='194'>///QMF values of the reconstructed signal</doc>
<use f='ffmpeg/libavcodec/aacsbr_template.c' l='1540' c='ff_sbr_apply'/>
<use f='ffmpeg/libavcodec/aacsbr_template.c' l='1548' u='r' c='ff_sbr_apply'/>
<use f='ffmpeg/libavcodec/aacsbr_template.c' l='1548' u='r' c='ff_sbr_apply'/>
<use f='ffmpeg/libavcodec/aacsbr_template.c' l='1550' u='r' c='ff_sbr_apply'/>
<use f='ffmpeg/libavcodec/aacsbr_template.c' l='1550' u='r' c='ff_sbr_apply'/>
<use f='ffmpeg/libavcodec/aacsbr_template.c' l='1550' u='r' c='ff_sbr_apply'/>
<use f='ffmpeg/libavcodec/aacsbr_template.c' l='1556' u='r' c='ff_sbr_apply'/>
<use f='ffmpeg/libavcodec/aacsbr_template.c' l='1562' u='r' c='ff_sbr_apply'/>
