<dec f='ffmpeg/libavcodec/svq1enc.h' l='39' type='MpegEncContext'/>
<use f='ffmpeg/libavcodec/svq1enc.c' l='271' u='m' c='svq1_encode_plane'/>
<use f='ffmpeg/libavcodec/svq1enc.c' l='272' u='m' c='svq1_encode_plane'/>
<use f='ffmpeg/libavcodec/svq1enc.c' l='272' u='m' c='svq1_encode_plane'/>
<use f='ffmpeg/libavcodec/svq1enc.c' l='273' u='m' c='svq1_encode_plane'/>
<use f='ffmpeg/libavcodec/svq1enc.c' l='273' u='m' c='svq1_encode_plane'/>
<use f='ffmpeg/libavcodec/svq1enc.c' l='274' u='m' c='svq1_encode_plane'/>
<use f='ffmpeg/libavcodec/svq1enc.c' l='275' u='m' c='svq1_encode_plane'/>
<use f='ffmpeg/libavcodec/svq1enc.c' l='276' u='m' c='svq1_encode_plane'/>
<use f='ffmpeg/libavcodec/svq1enc.c' l='277' u='m' c='svq1_encode_plane'/>
<use f='ffmpeg/libavcodec/svq1enc.c' l='278' u='m' c='svq1_encode_plane'/>
<use f='ffmpeg/libavcodec/svq1enc.c' l='279' u='m' c='svq1_encode_plane'/>
<use f='ffmpeg/libavcodec/svq1enc.c' l='280' u='m' c='svq1_encode_plane'/>
<use f='ffmpeg/libavcodec/svq1enc.c' l='281' u='m' c='svq1_encode_plane'/>
<use f='ffmpeg/libavcodec/svq1enc.c' l='282' u='m' c='svq1_encode_plane'/>
<use f='ffmpeg/libavcodec/svq1enc.c' l='283' u='m' c='svq1_encode_plane'/>
<use f='ffmpeg/libavcodec/svq1enc.c' l='283' u='m' c='svq1_encode_plane'/>
<use f='ffmpeg/libavcodec/svq1enc.c' l='284' u='m' c='svq1_encode_plane'/>
<use f='ffmpeg/libavcodec/svq1enc.c' l='284' u='m' c='svq1_encode_plane'/>
<use f='ffmpeg/libavcodec/svq1enc.c' l='285' u='m' c='svq1_encode_plane'/>
<use f='ffmpeg/libavcodec/svq1enc.c' l='286' u='m' c='svq1_encode_plane'/>
<use f='ffmpeg/libavcodec/svq1enc.c' l='287' u='m' c='svq1_encode_plane'/>
<use f='ffmpeg/libavcodec/svq1enc.c' l='288' u='m' c='svq1_encode_plane'/>
<use f='ffmpeg/libavcodec/svq1enc.c' l='291' u='m' c='svq1_encode_plane'/>
<use f='ffmpeg/libavcodec/svq1enc.c' l='292' u='m' c='svq1_encode_plane'/>
<use f='ffmpeg/libavcodec/svq1enc.c' l='292' u='m' c='svq1_encode_plane'/>
<use f='ffmpeg/libavcodec/svq1enc.c' l='295' u='m' c='svq1_encode_plane'/>
<use f='ffmpeg/libavcodec/svq1enc.c' l='295' u='m' c='svq1_encode_plane'/>
<use f='ffmpeg/libavcodec/svq1enc.c' l='295' u='m' c='svq1_encode_plane'/>
<use f='ffmpeg/libavcodec/svq1enc.c' l='300' u='m' c='svq1_encode_plane'/>
<use f='ffmpeg/libavcodec/svq1enc.c' l='303' u='m' c='svq1_encode_plane'/>
<use f='ffmpeg/libavcodec/svq1enc.c' l='310' u='m' c='svq1_encode_plane'/>
<use f='ffmpeg/libavcodec/svq1enc.c' l='313' u='m' c='svq1_encode_plane'/>
<use f='ffmpeg/libavcodec/svq1enc.c' l='314' u='m' c='svq1_encode_plane'/>
<use f='ffmpeg/libavcodec/svq1enc.c' l='315' u='m' c='svq1_encode_plane'/>
<use f='ffmpeg/libavcodec/svq1enc.c' l='316' u='m' c='svq1_encode_plane'/>
<use f='ffmpeg/libavcodec/svq1enc.c' l='318' u='m' c='svq1_encode_plane'/>
<use f='ffmpeg/libavcodec/svq1enc.c' l='319' u='m' c='svq1_encode_plane'/>
<use f='ffmpeg/libavcodec/svq1enc.c' l='320' u='m' c='svq1_encode_plane'/>
<use f='ffmpeg/libavcodec/svq1enc.c' l='321' u='m' c='svq1_encode_plane'/>
<use f='ffmpeg/libavcodec/svq1enc.c' l='322' u='a' c='svq1_encode_plane'/>
<use f='ffmpeg/libavcodec/svq1enc.c' l='324' u='m' c='svq1_encode_plane'/>
<use f='ffmpeg/libavcodec/svq1enc.c' l='325' u='m' c='svq1_encode_plane'/>
<use f='ffmpeg/libavcodec/svq1enc.c' l='327' u='m' c='svq1_encode_plane'/>
<use f='ffmpeg/libavcodec/svq1enc.c' l='328' u='m' c='svq1_encode_plane'/>
<use f='ffmpeg/libavcodec/svq1enc.c' l='341' u='m' c='svq1_encode_plane'/>
<use f='ffmpeg/libavcodec/svq1enc.c' l='342' u='a' c='svq1_encode_plane'/>
<use f='ffmpeg/libavcodec/svq1enc.c' l='344' u='a' c='svq1_encode_plane'/>
<use f='ffmpeg/libavcodec/svq1enc.c' l='346' u='m' c='svq1_encode_plane'/>
<use f='ffmpeg/libavcodec/svq1enc.c' l='349' u='a' c='svq1_encode_plane'/>
<use f='ffmpeg/libavcodec/svq1enc.c' l='350' u='a' c='svq1_encode_plane'/>
<use f='ffmpeg/libavcodec/svq1enc.c' l='350' u='m' c='svq1_encode_plane'/>
<use f='ffmpeg/libavcodec/svq1enc.c' l='350' u='m' c='svq1_encode_plane'/>
<use f='ffmpeg/libavcodec/svq1enc.c' l='354' u='m' c='svq1_encode_plane'/>
<use f='ffmpeg/libavcodec/svq1enc.c' l='365' u='m' c='svq1_encode_plane'/>
<use f='ffmpeg/libavcodec/svq1enc.c' l='381' u='m' c='svq1_encode_plane'/>
<use f='ffmpeg/libavcodec/svq1enc.c' l='382' u='a' c='svq1_encode_plane'/>
<use f='ffmpeg/libavcodec/svq1enc.c' l='385' u='m' c='svq1_encode_plane'/>
<use f='ffmpeg/libavcodec/svq1enc.c' l='385' u='m' c='svq1_encode_plane'/>
<use f='ffmpeg/libavcodec/svq1enc.c' l='411' u='a' c='svq1_encode_plane'/>
<use f='ffmpeg/libavcodec/svq1enc.c' l='412' u='m' c='svq1_encode_plane'/>
<use f='ffmpeg/libavcodec/svq1enc.c' l='412' u='m' c='svq1_encode_plane'/>
<use f='ffmpeg/libavcodec/svq1enc.c' l='420' u='m' c='svq1_encode_plane'/>
<use f='ffmpeg/libavcodec/svq1enc.c' l='427' u='m' c='svq1_encode_plane'/>
<use f='ffmpeg/libavcodec/svq1enc.c' l='428' u='m' c='svq1_encode_plane'/>
<use f='ffmpeg/libavcodec/svq1enc.c' l='429' u='m' c='svq1_encode_plane'/>
<use f='ffmpeg/libavcodec/svq1enc.c' l='464' u='m' c='svq1_encode_plane'/>
<use f='ffmpeg/libavcodec/svq1enc.c' l='465' u='m' c='svq1_encode_plane'/>
<use f='ffmpeg/libavcodec/svq1enc.c' l='466' u='m' c='svq1_encode_plane'/>
<use f='ffmpeg/libavcodec/svq1enc.c' l='467' u='m' c='svq1_encode_plane'/>
<use f='ffmpeg/libavcodec/svq1enc.c' l='480' u='m' c='svq1_encode_plane'/>
<use f='ffmpeg/libavcodec/svq1enc.c' l='494' u='m' c='svq1_encode_end'/>
<use f='ffmpeg/libavcodec/svq1enc.c' l='495' u='a' c='svq1_encode_end'/>
<use f='ffmpeg/libavcodec/svq1enc.c' l='497' u='m' c='svq1_encode_end'/>
<use f='ffmpeg/libavcodec/svq1enc.c' l='498' u='m' c='svq1_encode_end'/>
<use f='ffmpeg/libavcodec/svq1enc.c' l='499' u='m' c='svq1_encode_end'/>
<use f='ffmpeg/libavcodec/svq1enc.c' l='527' u='m' c='svq1_encode_init'/>
<use f='ffmpeg/libavcodec/svq1enc.c' l='545' u='m' c='svq1_encode_init'/>
<use f='ffmpeg/libavcodec/svq1enc.c' l='547' u='a' c='svq1_encode_init'/>
<use f='ffmpeg/libavcodec/svq1enc.c' l='551' u='m' c='svq1_encode_init'/>
<use f='ffmpeg/libavcodec/svq1enc.c' l='552' u='m' c='svq1_encode_init'/>
<use f='ffmpeg/libavcodec/svq1enc.c' l='553' u='m' c='svq1_encode_init'/>
<use f='ffmpeg/libavcodec/svq1enc.c' l='555' u='m' c='svq1_encode_init'/>
<use f='ffmpeg/libavcodec/svq1enc.c' l='556' u='m' c='svq1_encode_init'/>
<use f='ffmpeg/libavcodec/svq1enc.c' l='563' u='m' c='svq1_encode_init'/>
<use f='ffmpeg/libavcodec/svq1enc.c' l='563' u='m' c='svq1_encode_init'/>
<use f='ffmpeg/libavcodec/svq1enc.c' l='563' u='m' c='svq1_encode_init'/>
<use f='ffmpeg/libavcodec/svq1enc.c' l='564' u='m' c='svq1_encode_init'/>
<use f='ffmpeg/libavcodec/svq1enc.c' l='573' u='a' c='svq1_encode_init'/>
<offset>0</offset>
<doc f='ffmpeg/libavcodec/svq1enc.h' l='36'>/* FIXME: Needed for motion estimation, should not be used for anything
     * else, the idea is to make the motion estimation eventually independent
     * of MpegEncContext, so this will be removed then. */</doc>
