<dec f='ffmpeg/libavcodec/thread.h' l='35' type='AVFrame *'/>
<use f='ffmpeg/libavcodec/aic.c' l='394' u='w' c='aic_decode_frame'/>
<offset>0</offset>
<use f='ffmpeg/libavcodec/alac.c' l='273' u='w' c='decode_element'/>
<use f='ffmpeg/libavcodec/av1dec.c' l='539' u='a' c='av1_decode_free'/>
<use f='ffmpeg/libavcodec/av1dec.c' l='542' u='a' c='av1_decode_free'/>
<use f='ffmpeg/libavcodec/av1dec.c' l='638' u='w' c='av1_decode_init'/>
<use f='ffmpeg/libavcodec/av1dec.c' l='639' u='r' c='av1_decode_init'/>
<use f='ffmpeg/libavcodec/av1dec.c' l='646' u='w' c='av1_decode_init'/>
<use f='ffmpeg/libavcodec/av1dec.c' l='647' u='r' c='av1_decode_init'/>
<use f='ffmpeg/libavcodec/av1dec.c' l='709' u='r' c='av1_frame_alloc'/>
<use f='ffmpeg/libavcodec/av1dec.c' l='808' u='r' c='set_output_frame'/>
<use f='ffmpeg/libavcodec/av1dec.c' l='845' u='r' c='update_reference_list'/>
<use f='ffmpeg/libavcodec/av1dec.c' l='862' u='r' c='get_current_frame'/>
<use f='ffmpeg/libavcodec/av1dec.c' l='977' u='r' c='av1_decode_frame'/>
<use f='ffmpeg/libavcodec/cfhd.c' l='381' u='w' c='cfhd_decode'/>
<use f='ffmpeg/libavcodec/cfhd.c' l='684' u='r' c='cfhd_decode'/>
<use f='ffmpeg/libavcodec/cfhd.c' l='685' u='r' c='cfhd_decode'/>
<use f='ffmpeg/libavcodec/cfhd.c' l='695' u='r' c='cfhd_decode'/>
<use f='ffmpeg/libavcodec/cfhd.c' l='696' u='r' c='cfhd_decode'/>
<use f='ffmpeg/libavcodec/cllc.c' l='363' u='w' c='cllc_decode_frame'/>
<use f='ffmpeg/libavcodec/cri.c' l='177' u='w' c='cri_decode_frame'/>
<use f='ffmpeg/libavcodec/dnxhddec.c' l='613' u='w' c='dnxhd_decode_frame'/>
<use f='ffmpeg/libavcodec/dvdec.c' l='553' u='w' c='dvvideo_decode_frame'/>
<use f='ffmpeg/libavcodec/dvdec.c' l='574' u='r' c='dvvideo_decode_frame'/>
<use f='ffmpeg/libavcodec/dvdec.c' l='575' u='r' c='dvvideo_decode_frame'/>
<use f='ffmpeg/libavcodec/dvdec.c' l='576' u='r' c='dvvideo_decode_frame'/>
<use f='ffmpeg/libavcodec/dvdec.c' l='599' u='r' c='dvvideo_decode_frame'/>
<use f='ffmpeg/libavcodec/dvdec.c' l='600' u='r' c='dvvideo_decode_frame'/>
<use f='ffmpeg/libavcodec/dvdec.c' l='602' u='r' c='dvvideo_decode_frame'/>
<use f='ffmpeg/libavcodec/dvdec.c' l='603' u='r' c='dvvideo_decode_frame'/>
<use f='ffmpeg/libavcodec/dvdec.c' l='605' u='r' c='dvvideo_decode_frame'/>
<use f='ffmpeg/libavcodec/dvdec.c' l='606' u='r' c='dvvideo_decode_frame'/>
<use f='ffmpeg/libavcodec/dxtory.c' l='96' u='w' c='dxtory_decode_v1_rgb'/>
<use f='ffmpeg/libavcodec/dxtory.c' l='128' u='w' c='dxtory_decode_v1_410'/>
<use f='ffmpeg/libavcodec/dxtory.c' l='224' u='w' c='dxtory_decode_v1_420'/>
<use f='ffmpeg/libavcodec/dxtory.c' l='297' u='w' c='dxtory_decode_v1_444'/>
<use f='ffmpeg/libavcodec/dxtory.c' l='433' u='w' c='dxtory_decode_v2'/>
<use f='ffmpeg/libavcodec/dxv.c' l='1214' u='w' c='dxv_decode'/>
<use f='ffmpeg/libavcodec/dxv.c' l='1221' u='r' c='dxv_decode'/>
<use f='ffmpeg/libavcodec/dxv.c' l='1224' u='r' c='dxv_decode'/>
<use f='ffmpeg/libavcodec/dxv.c' l='1225' u='r' c='dxv_decode'/>
<use f='ffmpeg/libavcodec/exr.c' l='2020' u='w' c='decode_frame'/>
<use f='ffmpeg/libavcodec/ffv1.c' l='51' u='w' c='ff_ffv1_common_init'/>
<use f='ffmpeg/libavcodec/ffv1.c' l='52' u='w' c='ff_ffv1_common_init'/>
<use f='ffmpeg/libavcodec/ffv1.c' l='53' u='r' c='ff_ffv1_common_init'/>
<use f='ffmpeg/libavcodec/ffv1.c' l='53' u='r' c='ff_ffv1_common_init'/>
<use f='ffmpeg/libavcodec/ffv1.c' l='206' u='r' c='ff_ffv1_close'/>
<use f='ffmpeg/libavcodec/ffv1.c' l='208' u='a' c='ff_ffv1_close'/>
<use f='ffmpeg/libavcodec/ffv1.c' l='210' u='r' c='ff_ffv1_close'/>
<use f='ffmpeg/libavcodec/ffv1.c' l='212' u='a' c='ff_ffv1_close'/>
<use f='ffmpeg/libavcodec/ffv1dec.c' l='843' u='r' c='decode_frame'/>
<use f='ffmpeg/libavcodec/ffv1dec.c' l='847' u='r' c='decode_frame'/>
<use f='ffmpeg/libavcodec/ffv1dec.c' l='940' u='r' c='decode_frame'/>
<use f='ffmpeg/libavcodec/ffv1dec.c' l='951' u='r' c='decode_frame'/>
<use f='ffmpeg/libavcodec/ffv1dec.c' l='951' u='r' c='decode_frame'/>
<use f='ffmpeg/libavcodec/ffv1dec.c' l='958' u='r' c='decode_frame'/>
<use f='ffmpeg/libavcodec/ffv1dec.c' l='961' u='r' c='decode_frame'/>
<use f='ffmpeg/libavcodec/ffv1dec.c' l='971' u='r' c='decode_frame'/>
<use f='ffmpeg/libavcodec/ffv1dec.c' l='974' u='r' c='decode_frame'/>
<use f='ffmpeg/libavcodec/ffv1dec.c' l='1045' u='r' c='update_thread_context'/>
<use f='ffmpeg/libavcodec/ffv1enc.c' l='942' u='r' c='encode_slice_header'/>
<use f='ffmpeg/libavcodec/ffv1enc.c' l='945' u='r' c='encode_slice_header'/>
<use f='ffmpeg/libavcodec/ffv1enc.c' l='946' u='r' c='encode_slice_header'/>
<use f='ffmpeg/libavcodec/ffv1enc.c' l='947' u='r' c='encode_slice_header'/>
<use f='ffmpeg/libavcodec/ffv1enc.c' l='1050' u='r' c='encode_slice'/>
<use f='ffmpeg/libavcodec/ffv1enc.c' l='1124' u='r' c='encode_frame'/>
<use f='ffmpeg/libavcodec/flacdec.c' l='562' u='w' c='flac_decode_frame'/>
<use f='ffmpeg/libavcodec/fraps.c' l='143' u='w' c='decode_frame'/>
<use f='ffmpeg/libavcodec/h264_picture.c' l='72' u='r' c='ff_h264_ref_picture'/>
<use f='ffmpeg/libavcodec/h264_picture.c' l='74' u='w' c='ff_h264_ref_picture'/>
<use f='ffmpeg/libavcodec/h264_slice.c' l='193' u='w' c='alloc_picture'/>
<use f='ffmpeg/libavcodec/h264_slice.c' l='1607' u='w' c='h264_field_start'/>
<use f='ffmpeg/libavcodec/hapdec.c' l='333' u='w' c='hap_decode'/>
<use f='ffmpeg/libavcodec/hapdec.c' l='389' u='r' c='hap_decode'/>
<use f='ffmpeg/libavcodec/hapdec.c' l='391' u='w' c='hap_decode'/>
<use f='ffmpeg/libavcodec/hapdec.c' l='392' u='r' c='hap_decode'/>
<use f='ffmpeg/libavcodec/hapdec.c' l='397' u='r' c='hap_decode'/>
<use f='ffmpeg/libavcodec/hapdec.c' l='398' u='r' c='hap_decode'/>
<use f='ffmpeg/libavcodec/hevcdec.c' l='3477' u='w' c='hevc_init_context'/>
<use f='ffmpeg/libavcodec/hqx.c' l='407' u='w' c='hqx_decode_frame'/>
<use f='ffmpeg/libavcodec/huffyuvdec.c' l='1196' u='w' c='decode_frame'/>
<use f='ffmpeg/libavcodec/jpeg2000dec.c' l='2497' u='w' c='jpeg2000_decode_frame'/>
<use f='ffmpeg/libavcodec/lagarith.c' l='542' u='w' c='lag_decode_frame'/>
<use f='ffmpeg/libavcodec/lcldec.c' l='161' u='w' c='decode_frame'/>
<use f='ffmpeg/libavcodec/magicyuv.c' l='434' u='w' c='magy_decode_frame'/>
<use f='ffmpeg/libavcodec/mdec.c' l='176' u='w' c='decode_frame'/>
<use f='ffmpeg/libavcodec/mdec.c' l='181' u='r' c='decode_frame'/>
<use f='ffmpeg/libavcodec/mdec.c' l='182' u='r' c='decode_frame'/>
<use f='ffmpeg/libavcodec/mdec.c' l='204' u='r' c='decode_frame'/>
<use f='ffmpeg/libavcodec/mimic.c' l='113' u='r' c='mimic_decode_end'/>
<use f='ffmpeg/libavcodec/mimic.c' l='115' u='a' c='mimic_decode_end'/>
<use f='ffmpeg/libavcodec/mimic.c' l='143' u='w' c='mimic_decode_init'/>
<use f='ffmpeg/libavcodec/mimic.c' l='144' u='r' c='mimic_decode_init'/>
<use f='ffmpeg/libavcodec/mimic.c' l='167' u='r' c='mimic_decode_update_thread_context'/>
<use f='ffmpeg/libavcodec/mimic.c' l='268' u='r' c='decode'/>
<use f='ffmpeg/libavcodec/mimic.c' l='269' u='r' c='decode'/>
<use f='ffmpeg/libavcodec/mimic.c' l='270' u='r' c='decode'/>
<use f='ffmpeg/libavcodec/mimic.c' l='293' u='r' c='decode'/>
<use f='ffmpeg/libavcodec/mimic.c' l='299' u='r' c='decode'/>
<use f='ffmpeg/libavcodec/mimic.c' l='392' u='r' c='mimic_decode_frame'/>
<use f='ffmpeg/libavcodec/mimic.c' l='398' u='r' c='mimic_decode_frame'/>
<use f='ffmpeg/libavcodec/mimic.c' l='426' u='r' c='mimic_decode_frame'/>
<use f='ffmpeg/libavcodec/mpegpicture.c' l='106' u='w' c='alloc_frame_buffer'/>
<use f='ffmpeg/libavcodec/mpegpicture.c' l='299' u='w' c='ff_mpeg_unref_picture'/>
<use f='ffmpeg/libavcodec/mpegpicture.c' l='362' u='w' c='ff_mpeg_ref_picture'/>
<use f='ffmpeg/libavcodec/mpegpicture.c' l='363' u='w' c='ff_mpeg_ref_picture'/>
<use f='ffmpeg/libavcodec/notchlc.c' l='467' u='w' c='decode_frame'/>
<use f='ffmpeg/libavcodec/photocd.c' l='297' u='w' c='photocd_decode_frame'/>
<use f='ffmpeg/libavcodec/pixlet.c' l='609' u='w' c='pixlet_decode_frame'/>
<use f='ffmpeg/libavcodec/pixlet.c' l='681' u='r' c='pixlet_decode_frame'/>
<use f='ffmpeg/libavcodec/pixlet.c' l='688' u='r' c='pixlet_decode_frame'/>
<use f='ffmpeg/libavcodec/pixlet.c' l='689' u='r' c='pixlet_decode_frame'/>
<use f='ffmpeg/libavcodec/pngdec.c' l='1025' u='r' c='decode_fctl_chunk'/>
<use f='ffmpeg/libavcodec/pngdec.c' l='1058' u='r' c='handle_p_frame_png'/>
<use f='ffmpeg/libavcodec/pngdec.c' l='1066' u='r' c='handle_p_frame_png'/>
<use f='ffmpeg/libavcodec/pngdec.c' l='1079' u='r' c='handle_p_frame_apng'/>
<use f='ffmpeg/libavcodec/pngdec.c' l='1080' u='r' c='handle_p_frame_apng'/>
<use f='ffmpeg/libavcodec/pngdec.c' l='1435' u='r' c='decode_frame_common'/>
<use f='ffmpeg/libavcodec/pngdec.c' l='1437' u='r' c='decode_frame_common'/>
<use f='ffmpeg/libavcodec/pngdec.c' l='1438' u='r' c='decode_frame_common'/>
<use f='ffmpeg/libavcodec/pngdec.c' l='1439' u='r' c='decode_frame_common'/>
<use f='ffmpeg/libavcodec/pngdec.c' l='1538' u='r' c='decode_frame_png'/>
<use f='ffmpeg/libavcodec/pngdec.c' l='1577' u='r' c='decode_frame_png'/>
<use f='ffmpeg/libavcodec/pngdec.c' l='1604' u='r' c='decode_frame_apng'/>
<use f='ffmpeg/libavcodec/pngdec.c' l='1640' u='r' c='decode_frame_apng'/>
<use f='ffmpeg/libavcodec/pngdec.c' l='1700' u='r' c='update_thread_context'/>
<use f='ffmpeg/libavcodec/pngdec.c' l='1717' u='w' c='png_dec_init'/>
<use f='ffmpeg/libavcodec/pngdec.c' l='1718' u='w' c='png_dec_init'/>
<use f='ffmpeg/libavcodec/pngdec.c' l='1719' u='r' c='png_dec_init'/>
<use f='ffmpeg/libavcodec/pngdec.c' l='1719' u='r' c='png_dec_init'/>
<use f='ffmpeg/libavcodec/pngdec.c' l='1720' u='a' c='png_dec_init'/>
<use f='ffmpeg/libavcodec/pngdec.c' l='1721' u='a' c='png_dec_init'/>
<use f='ffmpeg/libavcodec/pngdec.c' l='1735' u='a' c='png_dec_end'/>
<use f='ffmpeg/libavcodec/pngdec.c' l='1737' u='a' c='png_dec_end'/>
<use f='ffmpeg/libavcodec/proresdec2.c' l='759' u='w' c='decode_frame'/>
<use f='ffmpeg/libavcodec/pthread_frame.c' l='1006' u='r' c='thread_get_buffer_internal'/>
<use f='ffmpeg/libavcodec/pthread_frame.c' l='1038' u='r' c='thread_get_buffer_internal'/>
<use f='ffmpeg/libavcodec/pthread_frame.c' l='1041' u='r' c='thread_get_buffer_internal'/>
<use f='ffmpeg/libavcodec/pthread_frame.c' l='1117' u='r' c='ff_thread_release_buffer'/>
<use f='ffmpeg/libavcodec/pthread_frame.c' l='1130' u='r' c='ff_thread_release_buffer'/>
<use f='ffmpeg/libavcodec/pthread_frame.c' l='1131' u='r' c='ff_thread_release_buffer'/>
<use f='ffmpeg/libavcodec/pthread_frame.c' l='1154' u='r' c='ff_thread_release_buffer'/>
<use f='ffmpeg/libavcodec/pthread_frame.c' l='1165' u='r' c='ff_thread_release_buffer'/>
<use f='ffmpeg/libavcodec/pthread_frame.c' l='1165' u='r' c='ff_thread_release_buffer'/>
<use f='ffmpeg/libavcodec/pthread_frame.c' l='1166' u='r' c='ff_thread_release_buffer'/>
<use f='ffmpeg/libavcodec/pthread_frame.c' l='1167' u='r' c='ff_thread_release_buffer'/>
<use f='ffmpeg/libavcodec/pthread_frame.c' l='1167' u='r' c='ff_thread_release_buffer'/>
<use f='ffmpeg/libavcodec/pthread_frame.c' l='1167' u='r' c='ff_thread_release_buffer'/>
<use f='ffmpeg/libavcodec/pthread_frame.c' l='1168' u='r' c='ff_thread_release_buffer'/>
<use f='ffmpeg/libavcodec/sheervideo.c' l='1813' u='w' c='decode_frame'/>
<use f='ffmpeg/libavcodec/takdec.c' l='682' u='w' c='tak_decode_frame'/>
<use f='ffmpeg/libavcodec/tiff.c' l='1213' u='r' c='init_image'/>
<use f='ffmpeg/libavcodec/tiff.c' l='1217' u='r' c='init_image'/>
<use f='ffmpeg/libavcodec/tiff.c' l='1779' u='w' c='decode_frame'/>
<use f='ffmpeg/libavcodec/tta.c' l='223' u='w' c='tta_decode_frame'/>
<use f='ffmpeg/libavcodec/utils.c' l='910' u='r' c='ff_thread_ref_frame'/>
<use f='ffmpeg/libavcodec/utils.c' l='910' u='r' c='ff_thread_ref_frame'/>
<use f='ffmpeg/libavcodec/utvideodec.c' l='571' u='w' c='decode_frame'/>
<use f='ffmpeg/libavcodec/utvideodec.c' l='712' u='r' c='decode_frame'/>
<use f='ffmpeg/libavcodec/utvideodec.c' l='713' u='r' c='decode_frame'/>
<use f='ffmpeg/libavcodec/utvideodec.c' l='720' u='r' c='decode_frame'/>
<use f='ffmpeg/libavcodec/utvideodec.c' l='721' u='r' c='decode_frame'/>
<use f='ffmpeg/libavcodec/utvideodec.c' l='724' u='r' c='decode_frame'/>
<use f='ffmpeg/libavcodec/utvideodec.c' l='725' u='r' c='decode_frame'/>
<use f='ffmpeg/libavcodec/utvideodec.c' l='731' u='r' c='decode_frame'/>
<use f='ffmpeg/libavcodec/utvideodec.c' l='732' u='r' c='decode_frame'/>
<use f='ffmpeg/libavcodec/utvideodec.c' l='735' u='r' c='decode_frame'/>
<use f='ffmpeg/libavcodec/utvideodec.c' l='736' u='r' c='decode_frame'/>
<use f='ffmpeg/libavcodec/utvideodec.c' l='742' u='r' c='decode_frame'/>
<use f='ffmpeg/libavcodec/utvideodec.c' l='742' u='r' c='decode_frame'/>
<use f='ffmpeg/libavcodec/utvideodec.c' l='742' u='r' c='decode_frame'/>
<use f='ffmpeg/libavcodec/utvideodec.c' l='743' u='r' c='decode_frame'/>
<use f='ffmpeg/libavcodec/utvideodec.c' l='743' u='r' c='decode_frame'/>
<use f='ffmpeg/libavcodec/utvideodec.c' l='743' u='r' c='decode_frame'/>
<use f='ffmpeg/libavcodec/utvideodec.c' l='749' u='r' c='decode_frame'/>
<use f='ffmpeg/libavcodec/utvideodec.c' l='750' u='r' c='decode_frame'/>
<use f='ffmpeg/libavcodec/utvideodec.c' l='757' u='r' c='decode_frame'/>
<use f='ffmpeg/libavcodec/utvideodec.c' l='757' u='r' c='decode_frame'/>
<use f='ffmpeg/libavcodec/utvideodec.c' l='757' u='r' c='decode_frame'/>
<use f='ffmpeg/libavcodec/utvideodec.c' l='758' u='r' c='decode_frame'/>
<use f='ffmpeg/libavcodec/utvideodec.c' l='758' u='r' c='decode_frame'/>
<use f='ffmpeg/libavcodec/utvideodec.c' l='758' u='r' c='decode_frame'/>
<use f='ffmpeg/libavcodec/utvideodec.c' l='763' u='r' c='decode_frame'/>
<use f='ffmpeg/libavcodec/utvideodec.c' l='763' u='r' c='decode_frame'/>
<use f='ffmpeg/libavcodec/utvideodec.c' l='770' u='r' c='decode_frame'/>
<use f='ffmpeg/libavcodec/utvideodec.c' l='770' u='r' c='decode_frame'/>
<use f='ffmpeg/libavcodec/utvideodec.c' l='774' u='r' c='decode_frame'/>
<use f='ffmpeg/libavcodec/utvideodec.c' l='774' u='r' c='decode_frame'/>
<use f='ffmpeg/libavcodec/utvideodec.c' l='781' u='r' c='decode_frame'/>
<use f='ffmpeg/libavcodec/utvideodec.c' l='781' u='r' c='decode_frame'/>
<use f='ffmpeg/libavcodec/utvideodec.c' l='785' u='r' c='decode_frame'/>
<use f='ffmpeg/libavcodec/utvideodec.c' l='785' u='r' c='decode_frame'/>
<use f='ffmpeg/libavcodec/utvideodec.c' l='795' u='r' c='decode_frame'/>
<use f='ffmpeg/libavcodec/utvideodec.c' l='795' u='r' c='decode_frame'/>
<use f='ffmpeg/libavcodec/utvideodec.c' l='802' u='r' c='decode_frame'/>
<use f='ffmpeg/libavcodec/utvideodec.c' l='802' u='r' c='decode_frame'/>
<use f='ffmpeg/libavcodec/utvideodec.c' l='806' u='r' c='decode_frame'/>
<use f='ffmpeg/libavcodec/utvideodec.c' l='806' u='r' c='decode_frame'/>
<use f='ffmpeg/libavcodec/utvideodec.c' l='812' u='r' c='decode_frame'/>
<use f='ffmpeg/libavcodec/utvideodec.c' l='812' u='r' c='decode_frame'/>
<use f='ffmpeg/libavcodec/utvideodec.c' l='816' u='r' c='decode_frame'/>
<use f='ffmpeg/libavcodec/utvideodec.c' l='816' u='r' c='decode_frame'/>
<use f='ffmpeg/libavcodec/utvideodec.c' l='825' u='r' c='decode_frame'/>
<use f='ffmpeg/libavcodec/utvideodec.c' l='825' u='r' c='decode_frame'/>
<use f='ffmpeg/libavcodec/utvideodec.c' l='832' u='r' c='decode_frame'/>
<use f='ffmpeg/libavcodec/utvideodec.c' l='832' u='r' c='decode_frame'/>
<use f='ffmpeg/libavcodec/utvideodec.c' l='836' u='r' c='decode_frame'/>
<use f='ffmpeg/libavcodec/utvideodec.c' l='836' u='r' c='decode_frame'/>
<use f='ffmpeg/libavcodec/utvideodec.c' l='842' u='r' c='decode_frame'/>
<use f='ffmpeg/libavcodec/utvideodec.c' l='842' u='r' c='decode_frame'/>
<use f='ffmpeg/libavcodec/utvideodec.c' l='846' u='r' c='decode_frame'/>
<use f='ffmpeg/libavcodec/utvideodec.c' l='846' u='r' c='decode_frame'/>
<use f='ffmpeg/libavcodec/utvideodec.c' l='855' u='r' c='decode_frame'/>
<use f='ffmpeg/libavcodec/utvideodec.c' l='855' u='r' c='decode_frame'/>
<use f='ffmpeg/libavcodec/utvideodec.c' l='864' u='r' c='decode_frame'/>
<use f='ffmpeg/libavcodec/utvideodec.c' l='864' u='r' c='decode_frame'/>
<use f='ffmpeg/libavcodec/utvideodec.c' l='873' u='r' c='decode_frame'/>
<use f='ffmpeg/libavcodec/utvideodec.c' l='874' u='r' c='decode_frame'/>
<use f='ffmpeg/libavcodec/utvideodec.c' l='875' u='r' c='decode_frame'/>
<use f='ffmpeg/libavcodec/v210dec.c' l='146' u='w' c='decode_frame'/>
<use f='ffmpeg/libavcodec/v410dec.c' l='92' u='w' c='v410_decode_frame'/>
<use f='ffmpeg/libavcodec/vble.c' l='128' u='w' c='vble_decode_frame'/>
<use f='ffmpeg/libavcodec/vp3.c' l='334' u='r' c='vp3_decode_flush'/>
<use f='ffmpeg/libavcodec/vp3.c' l='336' u='r' c='vp3_decode_flush'/>
<use f='ffmpeg/libavcodec/vp3.c' l='338' u='r' c='vp3_decode_flush'/>
<use f='ffmpeg/libavcodec/vp3.c' l='354' u='a' c='vp3_decode_end'/>
<use f='ffmpeg/libavcodec/vp3.c' l='355' u='a' c='vp3_decode_end'/>
<use f='ffmpeg/libavcodec/vp3.c' l='356' u='a' c='vp3_decode_end'/>
<use f='ffmpeg/libavcodec/vp3.c' l='1801' u='r' c='apply_loop_filter'/>
<use f='ffmpeg/libavcodec/vp3.c' l='1802' u='r' c='apply_loop_filter'/>
<use f='ffmpeg/libavcodec/vp3.c' l='1932' u='r' c='vp3_draw_horiz_band'/>
<use f='ffmpeg/libavcodec/vp3.c' l='1933' u='r' c='vp3_draw_horiz_band'/>
<use f='ffmpeg/libavcodec/vp3.c' l='1934' u='r' c='vp3_draw_horiz_band'/>
<use f='ffmpeg/libavcodec/vp3.c' l='1939' u='r' c='vp3_draw_horiz_band'/>
<use f='ffmpeg/libavcodec/vp3.c' l='2081' u='r' c='render_slice'/>
<use f='ffmpeg/libavcodec/vp3.c' l='2083' u='r' c='render_slice'/>
<use f='ffmpeg/libavcodec/vp3.c' l='2085' u='r' c='render_slice'/>
<use f='ffmpeg/libavcodec/vp3.c' l='2087' u='r' c='render_slice'/>
<use f='ffmpeg/libavcodec/vp3.c' l='2313' u='w' c='init_frames'/>
<use f='ffmpeg/libavcodec/vp3.c' l='2314' u='w' c='init_frames'/>
<use f='ffmpeg/libavcodec/vp3.c' l='2315' u='w' c='init_frames'/>
<use f='ffmpeg/libavcodec/vp3.c' l='2317' u='r' c='init_frames'/>
<use f='ffmpeg/libavcodec/vp3.c' l='2317' u='r' c='init_frames'/>
<use f='ffmpeg/libavcodec/vp3.c' l='2317' u='r' c='init_frames'/>
<use f='ffmpeg/libavcodec/vp3.c' l='2534' u='r' c='ref_frame'/>
<use f='ffmpeg/libavcodec/vp3.c' l='2554' u='r' c='vp3_update_thread_context'/>
<use f='ffmpeg/libavcodec/vp3.c' l='2680' u='r' c='vp3_decode_frame'/>
<use f='ffmpeg/libavcodec/vp3.c' l='2682' u='r' c='vp3_decode_frame'/>
<use f='ffmpeg/libavcodec/vp3.c' l='2687' u='r' c='vp3_decode_frame'/>
<use f='ffmpeg/libavcodec/vp3.c' l='2687' u='r' c='vp3_decode_frame'/>
<use f='ffmpeg/libavcodec/vp3.c' l='2687' u='r' c='vp3_decode_frame'/>
<use f='ffmpeg/libavcodec/vp3.c' l='2730' u='r' c='vp3_decode_frame'/>
<use f='ffmpeg/libavcodec/vp3.c' l='2734' u='r' c='vp3_decode_frame'/>
<use f='ffmpeg/libavcodec/vp3.c' l='2794' u='r' c='vp3_decode_frame'/>
<use f='ffmpeg/libavcodec/vp3.c' l='2810' u='r' c='vp3_decode_frame'/>
<use f='ffmpeg/libavcodec/vp3.c' l='2832' u='r' c='vp3_decode_frame'/>
<use f='ffmpeg/libavcodec/vp8.c' l='165' u='r' c='vp8_find_free_buffer'/>
<use f='ffmpeg/libavcodec/vp8.c' l='524' u='r' c='vp7_fade_frame'/>
<use f='ffmpeg/libavcodec/vp8.c' l='532' u='r' c='vp7_fade_frame'/>
<use f='ffmpeg/libavcodec/vp8.c' l='1815' u='r' c='vp8_mc_luma'/>
<use f='ffmpeg/libavcodec/vp8.c' l='1873' u='r' c='vp8_mc_chroma'/>
<use f='ffmpeg/libavcodec/vp8.c' l='1873' u='r' c='vp8_mc_chroma'/>
<use f='ffmpeg/libavcodec/vp8.c' l='1963' u='r' c='prefetch_motion'/>
<use f='ffmpeg/libavcodec/vp8.c' l='2377' u='r' c='decode_mb_row_no_filter'/>
<use f='ffmpeg/libavcodec/vp8.c' l='2378' u='r' c='decode_mb_row_no_filter'/>
<use f='ffmpeg/libavcodec/vp8.c' l='2379' u='r' c='decode_mb_row_no_filter'/>
<use f='ffmpeg/libavcodec/vp8.c' l='2377' u='r' c='decode_mb_row_no_filter'/>
<use f='ffmpeg/libavcodec/vp8.c' l='2378' u='r' c='decode_mb_row_no_filter'/>
<use f='ffmpeg/libavcodec/vp8.c' l='2379' u='r' c='decode_mb_row_no_filter'/>
<use f='ffmpeg/libavcodec/vp8.c' l='2511' u='r' c='filter_mb_row'/>
<use f='ffmpeg/libavcodec/vp8.c' l='2669' u='r' c='vp78_decode_frame'/>
<use f='ffmpeg/libavcodec/vp8.c' l='2698' u='r' c='vp78_decode_frame'/>
<use f='ffmpeg/libavcodec/vp8.c' l='2699' u='r' c='vp78_decode_frame'/>
<use f='ffmpeg/libavcodec/vp8.c' l='2739' u='r' c='vp78_decode_frame'/>
<use f='ffmpeg/libavcodec/vp8.c' l='2740' u='r' c='vp78_decode_frame'/>
<use f='ffmpeg/libavcodec/vp8.c' l='2799' u='r' c='vp78_decode_frame'/>
<use f='ffmpeg/libavcodec/vp8.c' l='2834' u='a' c='ff_vp8_decode_free'/>
<use f='ffmpeg/libavcodec/vp8.c' l='2843' u='w' c='vp8_init_frames'/>
<use f='ffmpeg/libavcodec/vp8.c' l='2844' u='r' c='vp8_init_frames'/>
<use f='ffmpeg/libavcodec/vp8.c' l='2923' u='r' c='vp8_decode_update_thread_context'/>
<use f='ffmpeg/libavcodec/vp9.c' l='589' u='r' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='590' u='r' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='591' u='r' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='596' u='r' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='597' u='r' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='599' u='r' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='600' u='r' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='602' u='r' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='603' u='r' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='611' u='r' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='612' u='r' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='824' u='r' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='1101' u='r' c='decode_sb'/>
<use f='ffmpeg/libavcodec/vp9.c' l='1176' u='r' c='decode_sb_mem'/>
<use f='ffmpeg/libavcodec/vp9.c' l='1243' u='a' c='vp9_decode_free'/>
<use f='ffmpeg/libavcodec/vp9.c' l='1248' u='a' c='vp9_decode_free'/>
<use f='ffmpeg/libavcodec/vp9.c' l='1250' u='a' c='vp9_decode_free'/>
<use f='ffmpeg/libavcodec/vp9.c' l='1270' u='r' c='decode_tiles'/>
<use f='ffmpeg/libavcodec/vp9.c' l='1406' u='r' c='decode_tiles_mt'/>
<use f='ffmpeg/libavcodec/vp9.c' l='1479' u='r' c='loopfilter_proc'/>
<use f='ffmpeg/libavcodec/vp9.c' l='1512' u='r' c='vp9_export_enc_params'/>
<use f='ffmpeg/libavcodec/vp9.c' l='1568' u='r' c='vp9_decode_frame'/>
<use f='ffmpeg/libavcodec/vp9.c' l='1572' u='r' c='vp9_decode_frame'/>
<use f='ffmpeg/libavcodec/vp9.c' l='1582' u='r' c='vp9_decode_frame'/>
<use f='ffmpeg/libavcodec/vp9.c' l='1584' u='r' c='vp9_decode_frame'/>
<use f='ffmpeg/libavcodec/vp9.c' l='1595' u='r' c='vp9_decode_frame'/>
<use f='ffmpeg/libavcodec/vp9.c' l='1597' u='r' c='vp9_decode_frame'/>
<use f='ffmpeg/libavcodec/vp9.c' l='1601' u='r' c='vp9_decode_frame'/>
<use f='ffmpeg/libavcodec/vp9.c' l='1603' u='r' c='vp9_decode_frame'/>
<use f='ffmpeg/libavcodec/vp9.c' l='1606' u='r' c='vp9_decode_frame'/>
<use f='ffmpeg/libavcodec/vp9.c' l='1610' u='r' c='vp9_decode_frame'/>
<use f='ffmpeg/libavcodec/vp9.c' l='1614' u='r' c='vp9_decode_frame'/>
<use f='ffmpeg/libavcodec/vp9.c' l='1615' u='r' c='vp9_decode_frame'/>
<use f='ffmpeg/libavcodec/vp9.c' l='1615' u='r' c='vp9_decode_frame'/>
<use f='ffmpeg/libavcodec/vp9.c' l='1616' u='r' c='vp9_decode_frame'/>
<use f='ffmpeg/libavcodec/vp9.c' l='1616' u='r' c='vp9_decode_frame'/>
<use f='ffmpeg/libavcodec/vp9.c' l='1622' u='r' c='vp9_decode_frame'/>
<use f='ffmpeg/libavcodec/vp9.c' l='1626' u='r' c='vp9_decode_frame'/>
<use f='ffmpeg/libavcodec/vp9.c' l='1771' u='r' c='vp9_decode_frame'/>
<use f='ffmpeg/libavcodec/vp9.c' l='1773' u='r' c='vp9_decode_frame'/>
<use f='ffmpeg/libavcodec/vp9.c' l='1779' u='r' c='vp9_decode_frame'/>
<use f='ffmpeg/libavcodec/vp9.c' l='1804' u='w' c='init_frames'/>
<use f='ffmpeg/libavcodec/vp9.c' l='1805' u='r' c='init_frames'/>
<use f='ffmpeg/libavcodec/vp9.c' l='1812' u='w' c='init_frames'/>
<use f='ffmpeg/libavcodec/vp9.c' l='1813' u='w' c='init_frames'/>
<use f='ffmpeg/libavcodec/vp9.c' l='1814' u='r' c='init_frames'/>
<use f='ffmpeg/libavcodec/vp9.c' l='1814' u='r' c='init_frames'/>
<use f='ffmpeg/libavcodec/vp9.c' l='1841' u='r' c='vp9_decode_update_thread_context'/>
<use f='ffmpeg/libavcodec/vp9.c' l='1843' u='r' c='vp9_decode_update_thread_context'/>
<use f='ffmpeg/libavcodec/vp9.c' l='1849' u='r' c='vp9_decode_update_thread_context'/>
<use f='ffmpeg/libavcodec/vp9.c' l='1851' u='r' c='vp9_decode_update_thread_context'/>
<use f='ffmpeg/libavcodec/vp9block.c' l='1273' u='r' c='ff_vp9_decode_block'/>
<use f='ffmpeg/libavcodec/vp9lpf.c' l='182' u='r' c='ff_vp9_loopfilter_sb'/>
<use f='ffmpeg/libavcodec/vp9recon.c' l='231' u='r' c='intra_recon'/>
<use f='ffmpeg/libavcodec/vp9recon.c' l='246' u='r' c='intra_recon'/>
<use f='ffmpeg/libavcodec/vp9recon.c' l='254' u='r' c='intra_recon'/>
<use f='ffmpeg/libavcodec/vp9recon.c' l='265' u='r' c='intra_recon'/>
<use f='ffmpeg/libavcodec/vp9recon.c' l='275' u='r' c='intra_recon'/>
<use f='ffmpeg/libavcodec/vp9recon.c' l='283' u='r' c='intra_recon'/>
<use f='ffmpeg/libavcodec/vp9_mc_template.c' l='40' u='r' c='inter_pred_8bpp'/>
<use f='ffmpeg/libavcodec/vp9_mc_template.c' l='47' u='r' c='inter_pred_8bpp'/>
<use f='ffmpeg/libavcodec/vp9_mc_template.c' l='40' u='r' c='inter_pred_16bpp'/>
<use f='ffmpeg/libavcodec/vp9_mc_template.c' l='47' u='r' c='inter_pred_16bpp'/>
<use f='ffmpeg/libavcodec/vp9recon.c' l='418' u='r' c='mc_luma_scaled'/>
<use f='ffmpeg/libavcodec/vp9recon.c' l='418' u='r' c='mc_luma_scaled'/>
<use f='ffmpeg/libavcodec/vp9recon.c' l='419' u='r' c='mc_luma_scaled'/>
<use f='ffmpeg/libavcodec/vp9recon.c' l='419' u='r' c='mc_luma_scaled'/>
<use f='ffmpeg/libavcodec/vp9recon.c' l='478' u='r' c='mc_chroma_scaled'/>
<use f='ffmpeg/libavcodec/vp9recon.c' l='478' u='r' c='mc_chroma_scaled'/>
<use f='ffmpeg/libavcodec/vp9recon.c' l='479' u='r' c='mc_chroma_scaled'/>
<use f='ffmpeg/libavcodec/vp9recon.c' l='479' u='r' c='mc_chroma_scaled'/>
<use f='ffmpeg/libavcodec/vp9_mc_template.c' l='40' u='r' c='inter_pred_scaled_8bpp'/>
<use f='ffmpeg/libavcodec/vp9_mc_template.c' l='47' u='r' c='inter_pred_scaled_8bpp'/>
<use f='ffmpeg/libavcodec/vp9_mc_template.c' l='40' u='r' c='inter_pred_scaled_16bpp'/>
<use f='ffmpeg/libavcodec/vp9_mc_template.c' l='47' u='r' c='inter_pred_scaled_16bpp'/>
<use f='ffmpeg/libavcodec/wavpack.c' l='1022' u='r' c='update_thread_context'/>
<use f='ffmpeg/libavcodec/wavpack.c' l='1049' u='w' c='wavpack_decode_init'/>
<use f='ffmpeg/libavcodec/wavpack.c' l='1050' u='w' c='wavpack_decode_init'/>
<use f='ffmpeg/libavcodec/wavpack.c' l='1052' u='r' c='wavpack_decode_init'/>
<use f='ffmpeg/libavcodec/wavpack.c' l='1052' u='r' c='wavpack_decode_init'/>
<use f='ffmpeg/libavcodec/wavpack.c' l='1069' u='a' c='wavpack_decode_end'/>
<use f='ffmpeg/libavcodec/wavpack.c' l='1072' u='a' c='wavpack_decode_end'/>
<use f='ffmpeg/libavcodec/wavpack.c' l='1553' u='r' c='wavpack_decode_block'/>
<use f='ffmpeg/libavcodec/wavpack.c' l='1557' u='r' c='wavpack_decode_block'/>
<use f='ffmpeg/libavcodec/webp.c' l='570' u='w' c='decode_entropy_coded_image'/>
<use f='ffmpeg/libavcodec/ylc.c' l='288' u='w' c='decode_frame'/>
