<dec f='ffmpeg/libavfilter/avf_avectorscope.c' l='40' type='2'/>
<use f='ffmpeg/libavfilter/avf_avectorscope.c' l='84' u='r'/>
<use f='ffmpeg/libavfilter/avf_avectorscope.c' l='84' u='r'/>
<use f='ffmpeg/libavfilter/avf_avectorscope.c' l='84' u='r'/>
<use f='ffmpeg/libavfilter/avf_avectorscope.c' l='84' u='r'/>
<use f='ffmpeg/libavfilter/avf_avectorscope.c' l='84' u='r'/>
<use f='ffmpeg/libavfilter/avf_avectorscope.c' l='84' u='r'/>
<use f='ffmpeg/libavfilter/avf_avectorscope.c' l='84' u='r'/>
<use f='ffmpeg/libavfilter/avf_avectorscope.c' l='84' u='r'/>
<use f='ffmpeg/libavfilter/avf_avectorscope.c' l='229' u='r' c='config_output'/>
