<dec f='ffmpeg/libavcodec/vp9dec.h' l='127' type='ProbContext'/>
<dec f='ffmpeg/libavcodec/vp9dec.h' l='131' type='ProbContext'/>
<use f='ffmpeg/libavcodec/vp9.c' l='859' u='w' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='859' u='w' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='859' u='w' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='860' u='w' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='870' u='w' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='906' u='w' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='906' u='r' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='919' u='m' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='919' u='m' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='923' u='m' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='924' u='m' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='928' u='m' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='929' u='m' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='973' u='m' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='973' u='m' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='978' u='m' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='979' u='m' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='985' u='m' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='986' u='m' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='990' u='m' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='990' u='m' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='999' u='m' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='1000' u='m' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='1008' u='m' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='1009' u='m' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='1011' u='m' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='1012' u='m' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='1019' u='m' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='1020' u='m' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='1026' u='m' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='1027' u='m' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='1033' u='m' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='1035' u='m' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='1040' u='m' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='1044' u='m' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='1049' u='m' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='1053' u='m' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='1058' u='m' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='1066' u='m' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='1071' u='m' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='1078' u='m' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='1082' u='m' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='1098' u='m' c='decode_sb'/>
<use f='ffmpeg/libavcodec/vp9.c' l='1678' u='w' c='vp9_decode_frame'/>
<use f='ffmpeg/libavcodec/vp9.c' l='1678' u='r' c='vp9_decode_frame'/>
<offset>0</offset>
<use f='ffmpeg/libavcodec/vp9block.c' l='147' u='m' c='decode_mode'/>
<use f='ffmpeg/libavcodec/vp9block.c' l='165' u='m' c='decode_mode'/>
<use f='ffmpeg/libavcodec/vp9block.c' l='190' u='m' c='decode_mode'/>
<use f='ffmpeg/libavcodec/vp9block.c' l='192' u='m' c='decode_mode'/>
<use f='ffmpeg/libavcodec/vp9block.c' l='194' u='m' c='decode_mode'/>
<use f='ffmpeg/libavcodec/vp9block.c' l='199' u='m' c='decode_mode'/>
<use f='ffmpeg/libavcodec/vp9block.c' l='201' u='m' c='decode_mode'/>
<use f='ffmpeg/libavcodec/vp9block.c' l='205' u='m' c='decode_mode'/>
<use f='ffmpeg/libavcodec/vp9block.c' l='274' u='m' c='decode_mode'/>
<use f='ffmpeg/libavcodec/vp9block.c' l='278' u='m' c='decode_mode'/>
<use f='ffmpeg/libavcodec/vp9block.c' l='285' u='m' c='decode_mode'/>
<use f='ffmpeg/libavcodec/vp9block.c' l='289' u='m' c='decode_mode'/>
<use f='ffmpeg/libavcodec/vp9block.c' l='305' u='m' c='decode_mode'/>
<use f='ffmpeg/libavcodec/vp9block.c' l='312' u='m' c='decode_mode'/>
<use f='ffmpeg/libavcodec/vp9block.c' l='370' u='m' c='decode_mode'/>
<use f='ffmpeg/libavcodec/vp9block.c' l='442' u='m' c='decode_mode'/>
<use f='ffmpeg/libavcodec/vp9block.c' l='482' u='m' c='decode_mode'/>
<use f='ffmpeg/libavcodec/vp9block.c' l='569' u='m' c='decode_mode'/>
<use f='ffmpeg/libavcodec/vp9block.c' l='593' u='m' c='decode_mode'/>
<use f='ffmpeg/libavcodec/vp9block.c' l='618' u='m' c='decode_mode'/>
<use f='ffmpeg/libavcodec/vp9block.c' l='629' u='m' c='decode_mode'/>
<use f='ffmpeg/libavcodec/vp9block.c' l='635' u='m' c='decode_mode'/>
<use f='ffmpeg/libavcodec/vp9block.c' l='646' u='m' c='decode_mode'/>
<use f='ffmpeg/libavcodec/vp9block.c' l='652' u='m' c='decode_mode'/>
<use f='ffmpeg/libavcodec/vp9mvs.c' l='239' u='m' c='read_mv_component'/>
<use f='ffmpeg/libavcodec/vp9mvs.c' l='241' u='m' c='read_mv_component'/>
<use f='ffmpeg/libavcodec/vp9mvs.c' l='249' u='m' c='read_mv_component'/>
<use f='ffmpeg/libavcodec/vp9mvs.c' l='255' u='m' c='read_mv_component'/>
<use f='ffmpeg/libavcodec/vp9mvs.c' l='259' u='m' c='read_mv_component'/>
<use f='ffmpeg/libavcodec/vp9mvs.c' l='270' u='m' c='read_mv_component'/>
<use f='ffmpeg/libavcodec/vp9mvs.c' l='273' u='m' c='read_mv_component'/>
<use f='ffmpeg/libavcodec/vp9mvs.c' l='277' u='m' c='read_mv_component'/>
<use f='ffmpeg/libavcodec/vp9mvs.c' l='323' u='m' c='ff_vp9_fill_mv'/>
<use f='ffmpeg/libavcodec/vp9mvs.c' l='354' u='m' c='ff_vp9_fill_mv'/>
<use f='ffmpeg/libavcodec/vp9prob.c' l='49' u='a' c='ff_vp9_adapt_probs'/>
<use f='ffmpeg/libavcodec/vp9prob.c' l='71' u='m' c='ff_vp9_adapt_probs'/>
<use f='ffmpeg/libavcodec/vp9prob.c' l='72' u='m' c='ff_vp9_adapt_probs'/>
<use f='ffmpeg/libavcodec/vp9prob.c' l='73' u='m' c='ff_vp9_adapt_probs'/>
<use f='ffmpeg/libavcodec/vp9prob.c' l='74' u='m' c='ff_vp9_adapt_probs'/>
