<dec f='ffmpeg/libavcodec/vp9dec.h' l='101' type='VP56RangeCoder'/>
<use f='ffmpeg/libavcodec/vp9.c' l='884' u='a' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='888' u='a' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='912' u='a' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='914' u='a' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='918' u='a' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='919' u='a' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='922' u='a' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='924' u='a' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='927' u='a' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='929' u='a' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='936' u='a' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='946' u='a' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='947' u='a' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='972' u='a' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='973' u='a' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='977' u='a' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='979' u='a' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='984' u='a' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='986' u='a' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='989' u='a' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='990' u='a' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='993' u='a' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='995' u='a' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='998' u='a' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='1000' u='a' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='1007' u='a' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='1009' u='a' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='1010' u='a' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='1012' u='a' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='1018' u='a' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='1020' u='a' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='1025' u='a' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='1027' u='a' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='1032' u='a' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='1034' u='a' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='1039' u='a' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='1040' u='a' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='1043' u='a' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='1045' u='a' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='1048' u='a' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='1050' u='a' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='1052' u='a' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='1054' u='a' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='1057' u='a' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='1059' u='a' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='1065' u='a' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='1067' u='a' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='1070' u='a' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='1072' u='a' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='1077' u='a' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='1079' u='a' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='1081' u='a' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='1083' u='a' c='decode_frame_header'/>
<offset>25792</offset>
