<dec f='ffmpeg/libavcodec/vp9dsp.h' l='114' type='vp9_mc_func [5][4][2][2][2]'/>
<offset>6144</offset>
<doc f='ffmpeg/libavcodec/vp9dsp.h' l='105'>/*
     * dimension 1: hsize (0: 64, 1: 32, 2: 16, 3: 8, 4: 4)
     * dimension 2: filter type (0: smooth, 1: regular, 2: sharp, 3: bilin)
     * dimension 3: averaging type (0: put, 1: avg)
     * dimension 4: x subpel interpolation (0: none, 1: 8tap/bilin)
     * dimension 5: y subpel interpolation (0: none, 1: 8tap/bilin)
     *
     * dst/stride are aligned by hsize
     */</doc>
<use f='ffmpeg/libavcodec/vp9block.c' l='1408' u='r' c='ff_vp9_decode_block'/>
<use f='ffmpeg/libavcodec/vp9block.c' l='1423' u='r' c='ff_vp9_decode_block'/>
<use f='ffmpeg/libavcodec/vp9block.c' l='1425' u='r' c='ff_vp9_decode_block'/>
<use f='ffmpeg/libavcodec/vp9dsp_template.c' l='2277' u='w' c='ff_vp9dsp_mc_init_10'/>
<use f='ffmpeg/libavcodec/vp9dsp_template.c' l='2278' u='w' c='ff_vp9dsp_mc_init_10'/>
<use f='ffmpeg/libavcodec/vp9dsp_template.c' l='2279' u='w' c='ff_vp9dsp_mc_init_10'/>
<use f='ffmpeg/libavcodec/vp9dsp_template.c' l='2280' u='w' c='ff_vp9dsp_mc_init_10'/>
<use f='ffmpeg/libavcodec/vp9dsp_template.c' l='2277' u='w' c='ff_vp9dsp_mc_init_10'/>
<use f='ffmpeg/libavcodec/vp9dsp_template.c' l='2278' u='w' c='ff_vp9dsp_mc_init_10'/>
<use f='ffmpeg/libavcodec/vp9dsp_template.c' l='2279' u='w' c='ff_vp9dsp_mc_init_10'/>
<use f='ffmpeg/libavcodec/vp9dsp_template.c' l='2280' u='w' c='ff_vp9dsp_mc_init_10'/>
<use f='ffmpeg/libavcodec/vp9dsp_template.c' l='2277' u='w' c='ff_vp9dsp_mc_init_10'/>
<use f='ffmpeg/libavcodec/vp9dsp_template.c' l='2278' u='w' c='ff_vp9dsp_mc_init_10'/>
<use f='ffmpeg/libavcodec/vp9dsp_template.c' l='2279' u='w' c='ff_vp9dsp_mc_init_10'/>
<use f='ffmpeg/libavcodec/vp9dsp_template.c' l='2280' u='w' c='ff_vp9dsp_mc_init_10'/>
<use f='ffmpeg/libavcodec/vp9dsp_template.c' l='2277' u='w' c='ff_vp9dsp_mc_init_10'/>
<use f='ffmpeg/libavcodec/vp9dsp_template.c' l='2278' u='w' c='ff_vp9dsp_mc_init_10'/>
<use f='ffmpeg/libavcodec/vp9dsp_template.c' l='2279' u='w' c='ff_vp9dsp_mc_init_10'/>
<use f='ffmpeg/libavcodec/vp9dsp_template.c' l='2280' u='w' c='ff_vp9dsp_mc_init_10'/>
<use f='ffmpeg/libavcodec/vp9dsp_template.c' l='2277' u='w' c='ff_vp9dsp_mc_init_10'/>
<use f='ffmpeg/libavcodec/vp9dsp_template.c' l='2278' u='w' c='ff_vp9dsp_mc_init_10'/>
<use f='ffmpeg/libavcodec/vp9dsp_template.c' l='2279' u='w' c='ff_vp9dsp_mc_init_10'/>
<use f='ffmpeg/libavcodec/vp9dsp_template.c' l='2280' u='w' c='ff_vp9dsp_mc_init_10'/>
<use f='ffmpeg/libavcodec/vp9dsp_template.c' l='2277' u='w' c='ff_vp9dsp_mc_init_10'/>
<use f='ffmpeg/libavcodec/vp9dsp_template.c' l='2278' u='w' c='ff_vp9dsp_mc_init_10'/>
<use f='ffmpeg/libavcodec/vp9dsp_template.c' l='2279' u='w' c='ff_vp9dsp_mc_init_10'/>
<use f='ffmpeg/libavcodec/vp9dsp_template.c' l='2280' u='w' c='ff_vp9dsp_mc_init_10'/>
<use f='ffmpeg/libavcodec/vp9dsp_template.c' l='2277' u='w' c='ff_vp9dsp_mc_init_10'/>
<use f='ffmpeg/libavcodec/vp9dsp_template.c' l='2278' u='w' c='ff_vp9dsp_mc_init_10'/>
<use f='ffmpeg/libavcodec/vp9dsp_template.c' l='2279' u='w' c='ff_vp9dsp_mc_init_10'/>
<use f='ffmpeg/libavcodec/vp9dsp_template.c' l='2280' u='w' c='ff_vp9dsp_mc_init_10'/>
<use f='ffmpeg/libavcodec/vp9dsp_template.c' l='2277' u='w' c='ff_vp9dsp_mc_init_10'/>
<use f='ffmpeg/libavcodec/vp9dsp_template.c' l='2278' u='w' c='ff_vp9dsp_mc_init_10'/>
<use f='ffmpeg/libavcodec/vp9dsp_template.c' l='2279' u='w' c='ff_vp9dsp_mc_init_10'/>
<use f='ffmpeg/libavcodec/vp9dsp_template.c' l='2280' u='w' c='ff_vp9dsp_mc_init_10'/>
<use f='ffmpeg/libavcodec/vp9dsp_template.c' l='2277' u='w' c='ff_vp9dsp_mc_init_10'/>
<use f='ffmpeg/libavcodec/vp9dsp_template.c' l='2278' u='w' c='ff_vp9dsp_mc_init_10'/>
<use f='ffmpeg/libavcodec/vp9dsp_template.c' l='2279' u='w' c='ff_vp9dsp_mc_init_10'/>
<use f='ffmpeg/libavcodec/vp9dsp_template.c' l='2280' u='w' c='ff_vp9dsp_mc_init_10'/>
<use f='ffmpeg/libavcodec/vp9dsp_template.c' l='2277' u='w' c='ff_vp9dsp_mc_init_10'/>
<use f='ffmpeg/libavcodec/vp9dsp_template.c' l='2278' u='w' c='ff_vp9dsp_mc_init_10'/>
<use f='ffmpeg/libavcodec/vp9dsp_template.c' l='2279' u='w' c='ff_vp9dsp_mc_init_10'/>
<use f='ffmpeg/libavcodec/vp9dsp_template.c' l='2280' u='w' c='ff_vp9dsp_mc_init_10'/>
<use f='ffmpeg/libavcodec/vp9dsp_template.c' l='2298' u='w' c='ff_vp9dsp_mc_init_10'/>
<use f='ffmpeg/libavcodec/vp9dsp_template.c' l='2299' u='w' c='ff_vp9dsp_mc_init_10'/>
<use f='ffmpeg/libavcodec/vp9dsp_template.c' l='2300' u='w' c='ff_vp9dsp_mc_init_10'/>
<use f='ffmpeg/libavcodec/vp9dsp_template.c' l='2307' u='w' c='ff_vp9dsp_mc_init_10'/>
<use f='ffmpeg/libavcodec/vp9dsp_template.c' l='2298' u='w' c='ff_vp9dsp_mc_init_10'/>
<use f='ffmpeg/libavcodec/vp9dsp_template.c' l='2299' u='w' c='ff_vp9dsp_mc_init_10'/>
<use f='ffmpeg/libavcodec/vp9dsp_template.c' l='2300' u='w' c='ff_vp9dsp_mc_init_10'/>
<use f='ffmpeg/libavcodec/vp9dsp_template.c' l='2307' u='w' c='ff_vp9dsp_mc_init_10'/>
<use f='ffmpeg/libavcodec/vp9dsp_template.c' l='2298' u='w' c='ff_vp9dsp_mc_init_10'/>
<use f='ffmpeg/libavcodec/vp9dsp_template.c' l='2299' u='w' c='ff_vp9dsp_mc_init_10'/>
<use f='ffmpeg/libavcodec/vp9dsp_template.c' l='2300' u='w' c='ff_vp9dsp_mc_init_10'/>
<use f='ffmpeg/libavcodec/vp9dsp_template.c' l='2307' u='w' c='ff_vp9dsp_mc_init_10'/>
<use f='ffmpeg/libavcodec/vp9dsp_template.c' l='2298' u='w' c='ff_vp9dsp_mc_init_10'/>
<use f='ffmpeg/libavcodec/vp9dsp_template.c' l='2299' u='w' c='ff_vp9dsp_mc_init_10'/>
<use f='ffmpeg/libavcodec/vp9dsp_template.c' l='2300' u='w' c='ff_vp9dsp_mc_init_10'/>
<use f='ffmpeg/libavcodec/vp9dsp_template.c' l='2307' u='w' c='ff_vp9dsp_mc_init_10'/>
<use f='ffmpeg/libavcodec/vp9dsp_template.c' l='2298' u='w' c='ff_vp9dsp_mc_init_10'/>
<use f='ffmpeg/libavcodec/vp9dsp_template.c' l='2299' u='w' c='ff_vp9dsp_mc_init_10'/>
<use f='ffmpeg/libavcodec/vp9dsp_template.c' l='2300' u='w' c='ff_vp9dsp_mc_init_10'/>
<use f='ffmpeg/libavcodec/vp9dsp_template.c' l='2307' u='w' c='ff_vp9dsp_mc_init_10'/>
<use f='ffmpeg/libavcodec/vp9dsp_template.c' l='2298' u='w' c='ff_vp9dsp_mc_init_10'/>
<use f='ffmpeg/libavcodec/vp9dsp_template.c' l='2299' u='w' c='ff_vp9dsp_mc_init_10'/>
<use f='ffmpeg/libavcodec/vp9dsp_template.c' l='2300' u='w' c='ff_vp9dsp_mc_init_10'/>
<use f='ffmpeg/libavcodec/vp9dsp_template.c' l='2307' u='w' c='ff_vp9dsp_mc_init_10'/>
<use f='ffmpeg/libavcodec/vp9dsp_template.c' l='2298' u='w' c='ff_vp9dsp_mc_init_10'/>
<use f='ffmpeg/libavcodec/vp9dsp_template.c' l='2299' u='w' c='ff_vp9dsp_mc_init_10'/>
<use f='ffmpeg/libavcodec/vp9dsp_template.c' l='2300' u='w' c='ff_vp9dsp_mc_init_10'/>
<use f='ffmpeg/libavcodec/vp9dsp_template.c' l='2307' u='w' c='ff_vp9dsp_mc_init_10'/>
<use f='ffmpeg/libavcodec/vp9dsp_template.c' l='2298' u='w' c='ff_vp9dsp_mc_init_10'/>
<use f='ffmpeg/libavcodec/vp9dsp_template.c' l='2299' u='w' c='ff_vp9dsp_mc_init_10'/>
<use f='ffmpeg/libavcodec/vp9dsp_template.c' l='2300' u='w' c='ff_vp9dsp_mc_init_10'/>
<use f='ffmpeg/libavcodec/vp9dsp_template.c' l='2307' u='w' c='ff_vp9dsp_mc_init_10'/>
<use f='ffmpeg/libavcodec/vp9dsp_template.c' l='2298' u='w' c='ff_vp9dsp_mc_init_10'/>
<use f='ffmpeg/libavcodec/vp9dsp_template.c' l='2299' u='w' c='ff_vp9dsp_mc_init_10'/>
<use f='ffmpeg/libavcodec/vp9dsp_template.c' l='2300' u='w' c='ff_vp9dsp_mc_init_10'/>
<use f='ffmpeg/libavcodec/vp9dsp_template.c' l='2307' u='w' c='ff_vp9dsp_mc_init_10'/>
<use f='ffmpeg/libavcodec/vp9dsp_template.c' l='2298' u='w' c='ff_vp9dsp_mc_init_10'/>
<use f='ffmpeg/libavcodec/vp9dsp_template.c' l='2299' u='w' c='ff_vp9dsp_mc_init_10'/>
<use f='ffmpeg/libavcodec/vp9dsp_template.c' l='2300' u='w' c='ff_vp9dsp_mc_init_10'/>
<use f='ffmpeg/libavcodec/vp9dsp_template.c' l='2307' u='w' c='ff_vp9dsp_mc_init_10'/>
<use f='ffmpeg/libavcodec/vp9dsp_template.c' l='2298' u='w' c='ff_vp9dsp_mc_init_10'/>
<use f='ffmpeg/libavcodec/vp9dsp_template.c' l='2299' u='w' c='ff_vp9dsp_mc_init_10'/>
<use f='ffmpeg/libavcodec/vp9dsp_template.c' l='2300' u='w' c='ff_vp9dsp_mc_init_10'/>
<use f='ffmpeg/libavcodec/vp9dsp_template.c' l='2307' u='w' c='ff_vp9dsp_mc_init_10'/>
<use f='ffmpeg/libavcodec/vp9dsp_template.c' l='2298' u='w' c='ff_vp9dsp_mc_init_10'/>
<use f='ffmpeg/libavcodec/vp9dsp_template.c' l='2299' u='w' c='ff_vp9dsp_mc_init_10'/>
<use f='ffmpeg/libavcodec/vp9dsp_template.c' l='2300' u='w' c='ff_vp9dsp_mc_init_10'/>
<use f='ffmpeg/libavcodec/vp9dsp_template.c' l='2307' u='w' c='ff_vp9dsp_mc_init_10'/>
<use f='ffmpeg/libavcodec/vp9dsp_template.c' l='2298' u='w' c='ff_vp9dsp_mc_init_10'/>
<use f='ffmpeg/libavcodec/vp9dsp_template.c' l='2299' u='w' c='ff_vp9dsp_mc_init_10'/>
<use f='ffmpeg/libavcodec/vp9dsp_template.c' l='2300' u='w' c='ff_vp9dsp_mc_init_10'/>
<use f='ffmpeg/libavcodec/vp9dsp_template.c' l='2307' u='w' c='ff_vp9dsp_mc_init_10'/>
<use f='ffmpeg/libavcodec/vp9dsp_template.c' l='2298' u='w' c='ff_vp9dsp_mc_init_10'/>
<use f='ffmpeg/libavcodec/vp9dsp_template.c' l='2299' u='w' c='ff_vp9dsp_mc_init_10'/>
<use f='ffmpeg/libavcodec/vp9dsp_template.c' l='2300' u='w' c='ff_vp9dsp_mc_init_10'/>
<use f='ffmpeg/libavcodec/vp9dsp_template.c' l='2307' u='w' c='ff_vp9dsp_mc_init_10'/>
<use f='ffmpeg/libavcodec/vp9dsp_template.c' l='2298' u='w' c='ff_vp9dsp_mc_init_10'/>
<use f='ffmpeg/libavcodec/vp9dsp_template.c' l='2299' u='w' c='ff_vp9dsp_mc_init_10'/>
<use f='ffmpeg/libavcodec/vp9dsp_template.c' l='2300' u='w' c='ff_vp9dsp_mc_init_10'/>
<use f='ffmpeg/libavcodec/vp9dsp_template.c' l='2307' u='w' c='ff_vp9dsp_mc_init_10'/>
<use f='ffmpeg/libavcodec/vp9dsp_template.c' l='2298' u='w' c='ff_vp9dsp_mc_init_10'/>
<use f='ffmpeg/libavcodec/vp9dsp_template.c' l='2299' u='w' c='ff_vp9dsp_mc_init_10'/>
<use f='ffmpeg/libavcodec/vp9dsp_template.c' l='2300' u='w' c='ff_vp9dsp_mc_init_10'/>
<use f='ffmpeg/libavcodec/vp9dsp_template.c' l='2307' u='w' c='ff_vp9dsp_mc_init_10'/>
<use f='ffmpeg/libavcodec/vp9dsp_template.c' l='2298' u='w' c='ff_vp9dsp_mc_init_10'/>
<use f='ffmpeg/libavcodec/vp9dsp_template.c' l='2299' u='w' c='ff_vp9dsp_mc_init_10'/>
<use f='ffmpeg/libavcodec/vp9dsp_template.c' l='2300' u='w' c='ff_vp9dsp_mc_init_10'/>
<use f='ffmpeg/libavcodec/vp9dsp_template.c' l='2307' u='w' c='ff_vp9dsp_mc_init_10'/>
<use f='ffmpeg/libavcodec/vp9dsp_template.c' l='2298' u='w' c='ff_vp9dsp_mc_init_10'/>
<use f='ffmpeg/libavcodec/vp9dsp_template.c' l='2299' u='w' c='ff_vp9dsp_mc_init_10'/>
<use f='ffmpeg/libavcodec/vp9dsp_template.c' l='2300' u='w' c='ff_vp9dsp_mc_init_10'/>
<use f='ffmpeg/libavcodec/vp9dsp_template.c' l='2307' u='w' c='ff_vp9dsp_mc_init_10'/>
<use f='ffmpeg/libavcodec/vp9dsp_template.c' l='2298' u='w' c='ff_vp9dsp_mc_init_10'/>
<use f='ffmpeg/libavcodec/vp9dsp_template.c' l='2299' u='w' c='ff_vp9dsp_mc_init_10'/>
<use f='ffmpeg/libavcodec/vp9dsp_template.c' l='2300' u='w' c='ff_vp9dsp_mc_init_10'/>
<use f='ffmpeg/libavcodec/vp9dsp_template.c' l='2307' u='w' c='ff_vp9dsp_mc_init_10'/>
<use f='ffmpeg/libavcodec/vp9dsp_template.c' l='2298' u='w' c='ff_vp9dsp_mc_init_10'/>
<use f='ffmpeg/libavcodec/vp9dsp_template.c' l='2299' u='w' c='ff_vp9dsp_mc_init_10'/>
<use f='ffmpeg/libavcodec/vp9dsp_template.c' l='2300' u='w' c='ff_vp9dsp_mc_init_10'/>
<use f='ffmpeg/libavcodec/vp9dsp_template.c' l='2307' u='w' c='ff_vp9dsp_mc_init_10'/>
<use f='ffmpeg/libavcodec/vp9dsp_template.c' l='2298' u='w' c='ff_vp9dsp_mc_init_10'/>
<use f='ffmpeg/libavcodec/vp9dsp_template.c' l='2299' u='w' c='ff_vp9dsp_mc_init_10'/>
<use f='ffmpeg/libavcodec/vp9dsp_template.c' l='2300' u='w' c='ff_vp9dsp_mc_init_10'/>
<use f='ffmpeg/libavcodec/vp9dsp_template.c' l='2307' u='w' c='ff_vp9dsp_mc_init_10'/>
<use f='ffmpeg/libavcodec/vp9dsp_template.c' l='2298' u='w' c='ff_vp9dsp_mc_init_10'/>
<use f='ffmpeg/libavcodec/vp9dsp_template.c' l='2299' u='w' c='ff_vp9dsp_mc_init_10'/>
<use f='ffmpeg/libavcodec/vp9dsp_template.c' l='2300' u='w' c='ff_vp9dsp_mc_init_10'/>
<use f='ffmpeg/libavcodec/vp9dsp_template.c' l='2307' u='w' c='ff_vp9dsp_mc_init_10'/>
<use f='ffmpeg/libavcodec/vp9dsp_template.c' l='2298' u='w' c='ff_vp9dsp_mc_init_10'/>
<use f='ffmpeg/libavcodec/vp9dsp_template.c' l='2299' u='w' c='ff_vp9dsp_mc_init_10'/>
<use f='ffmpeg/libavcodec/vp9dsp_template.c' l='2300' u='w' c='ff_vp9dsp_mc_init_10'/>
<use f='ffmpeg/libavcodec/vp9dsp_template.c' l='2307' u='w' c='ff_vp9dsp_mc_init_10'/>
<use f='ffmpeg/libavcodec/vp9dsp_template.c' l='2298' u='w' c='ff_vp9dsp_mc_init_10'/>
<use f='ffmpeg/libavcodec/vp9dsp_template.c' l='2299' u='w' c='ff_vp9dsp_mc_init_10'/>
<use f='ffmpeg/libavcodec/vp9dsp_template.c' l='2300' u='w' c='ff_vp9dsp_mc_init_10'/>
<use f='ffmpeg/libavcodec/vp9dsp_template.c' l='2307' u='w' c='ff_vp9dsp_mc_init_10'/>
<use f='ffmpeg/libavcodec/vp9dsp_template.c' l='2298' u='w' c='ff_vp9dsp_mc_init_10'/>
<use f='ffmpeg/libavcodec/vp9dsp_template.c' l='2299' u='w' c='ff_vp9dsp_mc_init_10'/>
<use f='ffmpeg/libavcodec/vp9dsp_template.c' l='2300' u='w' c='ff_vp9dsp_mc_init_10'/>
<use f='ffmpeg/libavcodec/vp9dsp_template.c' l='2307' u='w' c='ff_vp9dsp_mc_init_10'/>
<use f='ffmpeg/libavcodec/vp9dsp_template.c' l='2298' u='w' c='ff_vp9dsp_mc_init_10'/>
<use f='ffmpeg/libavcodec/vp9dsp_template.c' l='2299' u='w' c='ff_vp9dsp_mc_init_10'/>
<use f='ffmpeg/libavcodec/vp9dsp_template.c' l='2300' u='w' c='ff_vp9dsp_mc_init_10'/>
<use f='ffmpeg/libavcodec/vp9dsp_template.c' l='2307' u='w' c='ff_vp9dsp_mc_init_10'/>
<use f='ffmpeg/libavcodec/vp9dsp_template.c' l='2298' u='w' c='ff_vp9dsp_mc_init_10'/>
<use f='ffmpeg/libavcodec/vp9dsp_template.c' l='2299' u='w' c='ff_vp9dsp_mc_init_10'/>
<use f='ffmpeg/libavcodec/vp9dsp_template.c' l='2300' u='w' c='ff_vp9dsp_mc_init_10'/>
<use f='ffmpeg/libavcodec/vp9dsp_template.c' l='2307' u='w' c='ff_vp9dsp_mc_init_10'/>
<use f='ffmpeg/libavcodec/vp9dsp_template.c' l='2298' u='w' c='ff_vp9dsp_mc_init_10'/>
<use f='ffmpeg/libavcodec/vp9dsp_template.c' l='2299' u='w' c='ff_vp9dsp_mc_init_10'/>
<use f='ffmpeg/libavcodec/vp9dsp_template.c' l='2300' u='w' c='ff_vp9dsp_mc_init_10'/>
<use f='ffmpeg/libavcodec/vp9dsp_template.c' l='2307' u='w' c='ff_vp9dsp_mc_init_10'/>
<use f='ffmpeg/libavcodec/vp9dsp_template.c' l='2298' u='w' c='ff_vp9dsp_mc_init_10'/>
<use f='ffmpeg/libavcodec/vp9dsp_template.c' l='2299' u='w' c='ff_vp9dsp_mc_init_10'/>
<use f='ffmpeg/libavcodec/vp9dsp_template.c' l='2300' u='w' c='ff_vp9dsp_mc_init_10'/>
<use f='ffmpeg/libavcodec/vp9dsp_template.c' l='2307' u='w' c='ff_vp9dsp_mc_init_10'/>
<use f='ffmpeg/libavcodec/vp9dsp_template.c' l='2298' u='w' c='ff_vp9dsp_mc_init_10'/>
<use f='ffmpeg/libavcodec/vp9dsp_template.c' l='2299' u='w' c='ff_vp9dsp_mc_init_10'/>
<use f='ffmpeg/libavcodec/vp9dsp_template.c' l='2300' u='w' c='ff_vp9dsp_mc_init_10'/>
<use f='ffmpeg/libavcodec/vp9dsp_template.c' l='2307' u='w' c='ff_vp9dsp_mc_init_10'/>
<use f='ffmpeg/libavcodec/vp9_mc_template.c' l='58' u='r' c='inter_pred_8bpp'/>
<use f='ffmpeg/libavcodec/vp9_mc_template.c' l='61' u='r' c='inter_pred_8bpp'/>
<use f='ffmpeg/libavcodec/vp9_mc_template.c' l='69' u='r' c='inter_pred_8bpp'/>
<use f='ffmpeg/libavcodec/vp9_mc_template.c' l='76' u='r' c='inter_pred_8bpp'/>
<use f='ffmpeg/libavcodec/vp9_mc_template.c' l='90' u='r' c='inter_pred_8bpp'/>
<use f='ffmpeg/libavcodec/vp9_mc_template.c' l='99' u='r' c='inter_pred_8bpp'/>
<use f='ffmpeg/libavcodec/vp9_mc_template.c' l='102' u='r' c='inter_pred_8bpp'/>
<use f='ffmpeg/libavcodec/vp9_mc_template.c' l='110' u='r' c='inter_pred_8bpp'/>
<use f='ffmpeg/libavcodec/vp9_mc_template.c' l='117' u='r' c='inter_pred_8bpp'/>
<use f='ffmpeg/libavcodec/vp9_mc_template.c' l='131' u='r' c='inter_pred_8bpp'/>
<use f='ffmpeg/libavcodec/vp9_mc_template.c' l='140' u='r' c='inter_pred_8bpp'/>
<use f='ffmpeg/libavcodec/vp9_mc_template.c' l='143' u='r' c='inter_pred_8bpp'/>
<use f='ffmpeg/libavcodec/vp9_mc_template.c' l='150' u='r' c='inter_pred_8bpp'/>
<use f='ffmpeg/libavcodec/vp9_mc_template.c' l='157' u='r' c='inter_pred_8bpp'/>
<use f='ffmpeg/libavcodec/vp9_mc_template.c' l='163' u='r' c='inter_pred_8bpp'/>
<use f='ffmpeg/libavcodec/vp9_mc_template.c' l='173' u='r' c='inter_pred_8bpp'/>
<use f='ffmpeg/libavcodec/vp9_mc_template.c' l='176' u='r' c='inter_pred_8bpp'/>
<use f='ffmpeg/libavcodec/vp9_mc_template.c' l='183' u='r' c='inter_pred_8bpp'/>
<use f='ffmpeg/libavcodec/vp9_mc_template.c' l='190' u='r' c='inter_pred_8bpp'/>
<use f='ffmpeg/libavcodec/vp9_mc_template.c' l='196' u='r' c='inter_pred_8bpp'/>
<use f='ffmpeg/libavcodec/vp9_mc_template.c' l='214' u='r' c='inter_pred_8bpp'/>
<use f='ffmpeg/libavcodec/vp9_mc_template.c' l='218' u='r' c='inter_pred_8bpp'/>
<use f='ffmpeg/libavcodec/vp9_mc_template.c' l='222' u='r' c='inter_pred_8bpp'/>
<use f='ffmpeg/libavcodec/vp9_mc_template.c' l='227' u='r' c='inter_pred_8bpp'/>
<use f='ffmpeg/libavcodec/vp9_mc_template.c' l='238' u='r' c='inter_pred_8bpp'/>
<use f='ffmpeg/libavcodec/vp9_mc_template.c' l='246' u='r' c='inter_pred_8bpp'/>
<use f='ffmpeg/libavcodec/vp9_mc_template.c' l='253' u='r' c='inter_pred_8bpp'/>
<use f='ffmpeg/libavcodec/vp9_mc_template.c' l='265' u='r' c='inter_pred_8bpp'/>
<use f='ffmpeg/libavcodec/vp9_mc_template.c' l='275' u='r' c='inter_pred_8bpp'/>
<use f='ffmpeg/libavcodec/vp9_mc_template.c' l='282' u='r' c='inter_pred_8bpp'/>
<use f='ffmpeg/libavcodec/vp9_mc_template.c' l='288' u='r' c='inter_pred_8bpp'/>
<use f='ffmpeg/libavcodec/vp9_mc_template.c' l='295' u='r' c='inter_pred_8bpp'/>
<use f='ffmpeg/libavcodec/vp9_mc_template.c' l='301' u='r' c='inter_pred_8bpp'/>
<use f='ffmpeg/libavcodec/vp9_mc_template.c' l='312' u='r' c='inter_pred_8bpp'/>
<use f='ffmpeg/libavcodec/vp9_mc_template.c' l='315' u='r' c='inter_pred_8bpp'/>
<use f='ffmpeg/libavcodec/vp9_mc_template.c' l='318' u='r' c='inter_pred_8bpp'/>
<use f='ffmpeg/libavcodec/vp9_mc_template.c' l='322' u='r' c='inter_pred_8bpp'/>
<use f='ffmpeg/libavcodec/vp9_mc_template.c' l='332' u='r' c='inter_pred_8bpp'/>
<use f='ffmpeg/libavcodec/vp9_mc_template.c' l='340' u='r' c='inter_pred_8bpp'/>
<use f='ffmpeg/libavcodec/vp9_mc_template.c' l='347' u='r' c='inter_pred_8bpp'/>
<use f='ffmpeg/libavcodec/vp9_mc_template.c' l='359' u='r' c='inter_pred_8bpp'/>
<use f='ffmpeg/libavcodec/vp9_mc_template.c' l='369' u='r' c='inter_pred_8bpp'/>
<use f='ffmpeg/libavcodec/vp9_mc_template.c' l='376' u='r' c='inter_pred_8bpp'/>
<use f='ffmpeg/libavcodec/vp9_mc_template.c' l='382' u='r' c='inter_pred_8bpp'/>
<use f='ffmpeg/libavcodec/vp9_mc_template.c' l='389' u='r' c='inter_pred_8bpp'/>
<use f='ffmpeg/libavcodec/vp9_mc_template.c' l='395' u='r' c='inter_pred_8bpp'/>
<use f='ffmpeg/libavcodec/vp9_mc_template.c' l='413' u='r' c='inter_pred_8bpp'/>
<use f='ffmpeg/libavcodec/vp9_mc_template.c' l='418' u='r' c='inter_pred_8bpp'/>
<use f='ffmpeg/libavcodec/vp9_mc_template.c' l='426' u='r' c='inter_pred_8bpp'/>
<use f='ffmpeg/libavcodec/vp9_mc_template.c' l='431' u='r' c='inter_pred_8bpp'/>
<use f='ffmpeg/libavcodec/vp9_mc_template.c' l='58' u='r' c='inter_pred_16bpp'/>
<use f='ffmpeg/libavcodec/vp9_mc_template.c' l='61' u='r' c='inter_pred_16bpp'/>
<use f='ffmpeg/libavcodec/vp9_mc_template.c' l='69' u='r' c='inter_pred_16bpp'/>
<use f='ffmpeg/libavcodec/vp9_mc_template.c' l='76' u='r' c='inter_pred_16bpp'/>
<use f='ffmpeg/libavcodec/vp9_mc_template.c' l='90' u='r' c='inter_pred_16bpp'/>
<use f='ffmpeg/libavcodec/vp9_mc_template.c' l='99' u='r' c='inter_pred_16bpp'/>
<use f='ffmpeg/libavcodec/vp9_mc_template.c' l='102' u='r' c='inter_pred_16bpp'/>
<use f='ffmpeg/libavcodec/vp9_mc_template.c' l='110' u='r' c='inter_pred_16bpp'/>
<use f='ffmpeg/libavcodec/vp9_mc_template.c' l='117' u='r' c='inter_pred_16bpp'/>
<use f='ffmpeg/libavcodec/vp9_mc_template.c' l='131' u='r' c='inter_pred_16bpp'/>
<use f='ffmpeg/libavcodec/vp9_mc_template.c' l='140' u='r' c='inter_pred_16bpp'/>
<use f='ffmpeg/libavcodec/vp9_mc_template.c' l='143' u='r' c='inter_pred_16bpp'/>
<use f='ffmpeg/libavcodec/vp9_mc_template.c' l='150' u='r' c='inter_pred_16bpp'/>
<use f='ffmpeg/libavcodec/vp9_mc_template.c' l='157' u='r' c='inter_pred_16bpp'/>
<use f='ffmpeg/libavcodec/vp9_mc_template.c' l='163' u='r' c='inter_pred_16bpp'/>
<use f='ffmpeg/libavcodec/vp9_mc_template.c' l='173' u='r' c='inter_pred_16bpp'/>
<use f='ffmpeg/libavcodec/vp9_mc_template.c' l='176' u='r' c='inter_pred_16bpp'/>
<use f='ffmpeg/libavcodec/vp9_mc_template.c' l='183' u='r' c='inter_pred_16bpp'/>
<use f='ffmpeg/libavcodec/vp9_mc_template.c' l='190' u='r' c='inter_pred_16bpp'/>
<use f='ffmpeg/libavcodec/vp9_mc_template.c' l='196' u='r' c='inter_pred_16bpp'/>
<use f='ffmpeg/libavcodec/vp9_mc_template.c' l='214' u='r' c='inter_pred_16bpp'/>
<use f='ffmpeg/libavcodec/vp9_mc_template.c' l='218' u='r' c='inter_pred_16bpp'/>
<use f='ffmpeg/libavcodec/vp9_mc_template.c' l='222' u='r' c='inter_pred_16bpp'/>
<use f='ffmpeg/libavcodec/vp9_mc_template.c' l='227' u='r' c='inter_pred_16bpp'/>
<use f='ffmpeg/libavcodec/vp9_mc_template.c' l='238' u='r' c='inter_pred_16bpp'/>
<use f='ffmpeg/libavcodec/vp9_mc_template.c' l='246' u='r' c='inter_pred_16bpp'/>
<use f='ffmpeg/libavcodec/vp9_mc_template.c' l='253' u='r' c='inter_pred_16bpp'/>
<use f='ffmpeg/libavcodec/vp9_mc_template.c' l='265' u='r' c='inter_pred_16bpp'/>
<use f='ffmpeg/libavcodec/vp9_mc_template.c' l='275' u='r' c='inter_pred_16bpp'/>
<use f='ffmpeg/libavcodec/vp9_mc_template.c' l='282' u='r' c='inter_pred_16bpp'/>
<use f='ffmpeg/libavcodec/vp9_mc_template.c' l='288' u='r' c='inter_pred_16bpp'/>
<use f='ffmpeg/libavcodec/vp9_mc_template.c' l='295' u='r' c='inter_pred_16bpp'/>
<use f='ffmpeg/libavcodec/vp9_mc_template.c' l='301' u='r' c='inter_pred_16bpp'/>
<use f='ffmpeg/libavcodec/vp9_mc_template.c' l='312' u='r' c='inter_pred_16bpp'/>
<use f='ffmpeg/libavcodec/vp9_mc_template.c' l='315' u='r' c='inter_pred_16bpp'/>
<use f='ffmpeg/libavcodec/vp9_mc_template.c' l='318' u='r' c='inter_pred_16bpp'/>
<use f='ffmpeg/libavcodec/vp9_mc_template.c' l='322' u='r' c='inter_pred_16bpp'/>
<use f='ffmpeg/libavcodec/vp9_mc_template.c' l='332' u='r' c='inter_pred_16bpp'/>
<use f='ffmpeg/libavcodec/vp9_mc_template.c' l='340' u='r' c='inter_pred_16bpp'/>
<use f='ffmpeg/libavcodec/vp9_mc_template.c' l='347' u='r' c='inter_pred_16bpp'/>
<use f='ffmpeg/libavcodec/vp9_mc_template.c' l='359' u='r' c='inter_pred_16bpp'/>
<use f='ffmpeg/libavcodec/vp9_mc_template.c' l='369' u='r' c='inter_pred_16bpp'/>
<use f='ffmpeg/libavcodec/vp9_mc_template.c' l='376' u='r' c='inter_pred_16bpp'/>
<use f='ffmpeg/libavcodec/vp9_mc_template.c' l='382' u='r' c='inter_pred_16bpp'/>
<use f='ffmpeg/libavcodec/vp9_mc_template.c' l='389' u='r' c='inter_pred_16bpp'/>
<use f='ffmpeg/libavcodec/vp9_mc_template.c' l='395' u='r' c='inter_pred_16bpp'/>
<use f='ffmpeg/libavcodec/vp9_mc_template.c' l='413' u='r' c='inter_pred_16bpp'/>
<use f='ffmpeg/libavcodec/vp9_mc_template.c' l='418' u='r' c='inter_pred_16bpp'/>
<use f='ffmpeg/libavcodec/vp9_mc_template.c' l='426' u='r' c='inter_pred_16bpp'/>
<use f='ffmpeg/libavcodec/vp9_mc_template.c' l='431' u='r' c='inter_pred_16bpp'/>
<use f='ffmpeg/libavcodec/vp9_mc_template.c' l='214' u='r' c='inter_pred_scaled_8bpp'/>
<use f='ffmpeg/libavcodec/vp9_mc_template.c' l='218' u='r' c='inter_pred_scaled_8bpp'/>
<use f='ffmpeg/libavcodec/vp9_mc_template.c' l='222' u='r' c='inter_pred_scaled_8bpp'/>
<use f='ffmpeg/libavcodec/vp9_mc_template.c' l='227' u='r' c='inter_pred_scaled_8bpp'/>
<use f='ffmpeg/libavcodec/vp9_mc_template.c' l='238' u='r' c='inter_pred_scaled_8bpp'/>
<use f='ffmpeg/libavcodec/vp9_mc_template.c' l='246' u='r' c='inter_pred_scaled_8bpp'/>
<use f='ffmpeg/libavcodec/vp9_mc_template.c' l='253' u='r' c='inter_pred_scaled_8bpp'/>
<use f='ffmpeg/libavcodec/vp9_mc_template.c' l='265' u='r' c='inter_pred_scaled_8bpp'/>
<use f='ffmpeg/libavcodec/vp9_mc_template.c' l='275' u='r' c='inter_pred_scaled_8bpp'/>
<use f='ffmpeg/libavcodec/vp9_mc_template.c' l='282' u='r' c='inter_pred_scaled_8bpp'/>
<use f='ffmpeg/libavcodec/vp9_mc_template.c' l='288' u='r' c='inter_pred_scaled_8bpp'/>
<use f='ffmpeg/libavcodec/vp9_mc_template.c' l='295' u='r' c='inter_pred_scaled_8bpp'/>
<use f='ffmpeg/libavcodec/vp9_mc_template.c' l='301' u='r' c='inter_pred_scaled_8bpp'/>
<use f='ffmpeg/libavcodec/vp9_mc_template.c' l='312' u='r' c='inter_pred_scaled_8bpp'/>
<use f='ffmpeg/libavcodec/vp9_mc_template.c' l='315' u='r' c='inter_pred_scaled_8bpp'/>
<use f='ffmpeg/libavcodec/vp9_mc_template.c' l='318' u='r' c='inter_pred_scaled_8bpp'/>
<use f='ffmpeg/libavcodec/vp9_mc_template.c' l='322' u='r' c='inter_pred_scaled_8bpp'/>
<use f='ffmpeg/libavcodec/vp9_mc_template.c' l='332' u='r' c='inter_pred_scaled_8bpp'/>
<use f='ffmpeg/libavcodec/vp9_mc_template.c' l='340' u='r' c='inter_pred_scaled_8bpp'/>
<use f='ffmpeg/libavcodec/vp9_mc_template.c' l='347' u='r' c='inter_pred_scaled_8bpp'/>
<use f='ffmpeg/libavcodec/vp9_mc_template.c' l='359' u='r' c='inter_pred_scaled_8bpp'/>
<use f='ffmpeg/libavcodec/vp9_mc_template.c' l='369' u='r' c='inter_pred_scaled_8bpp'/>
<use f='ffmpeg/libavcodec/vp9_mc_template.c' l='376' u='r' c='inter_pred_scaled_8bpp'/>
<use f='ffmpeg/libavcodec/vp9_mc_template.c' l='382' u='r' c='inter_pred_scaled_8bpp'/>
<use f='ffmpeg/libavcodec/vp9_mc_template.c' l='389' u='r' c='inter_pred_scaled_8bpp'/>
<use f='ffmpeg/libavcodec/vp9_mc_template.c' l='395' u='r' c='inter_pred_scaled_8bpp'/>
<use f='ffmpeg/libavcodec/vp9_mc_template.c' l='413' u='r' c='inter_pred_scaled_8bpp'/>
<use f='ffmpeg/libavcodec/vp9_mc_template.c' l='418' u='r' c='inter_pred_scaled_8bpp'/>
<use f='ffmpeg/libavcodec/vp9_mc_template.c' l='426' u='r' c='inter_pred_scaled_8bpp'/>
<use f='ffmpeg/libavcodec/vp9_mc_template.c' l='431' u='r' c='inter_pred_scaled_8bpp'/>
<use f='ffmpeg/libavcodec/vp9_mc_template.c' l='214' u='r' c='inter_pred_scaled_16bpp'/>
<use f='ffmpeg/libavcodec/vp9_mc_template.c' l='218' u='r' c='inter_pred_scaled_16bpp'/>
<use f='ffmpeg/libavcodec/vp9_mc_template.c' l='222' u='r' c='inter_pred_scaled_16bpp'/>
<use f='ffmpeg/libavcodec/vp9_mc_template.c' l='227' u='r' c='inter_pred_scaled_16bpp'/>
<use f='ffmpeg/libavcodec/vp9_mc_template.c' l='238' u='r' c='inter_pred_scaled_16bpp'/>
<use f='ffmpeg/libavcodec/vp9_mc_template.c' l='246' u='r' c='inter_pred_scaled_16bpp'/>
<use f='ffmpeg/libavcodec/vp9_mc_template.c' l='253' u='r' c='inter_pred_scaled_16bpp'/>
<use f='ffmpeg/libavcodec/vp9_mc_template.c' l='265' u='r' c='inter_pred_scaled_16bpp'/>
<use f='ffmpeg/libavcodec/vp9_mc_template.c' l='275' u='r' c='inter_pred_scaled_16bpp'/>
<use f='ffmpeg/libavcodec/vp9_mc_template.c' l='282' u='r' c='inter_pred_scaled_16bpp'/>
<use f='ffmpeg/libavcodec/vp9_mc_template.c' l='288' u='r' c='inter_pred_scaled_16bpp'/>
<use f='ffmpeg/libavcodec/vp9_mc_template.c' l='295' u='r' c='inter_pred_scaled_16bpp'/>
<use f='ffmpeg/libavcodec/vp9_mc_template.c' l='301' u='r' c='inter_pred_scaled_16bpp'/>
<use f='ffmpeg/libavcodec/vp9_mc_template.c' l='312' u='r' c='inter_pred_scaled_16bpp'/>
<use f='ffmpeg/libavcodec/vp9_mc_template.c' l='315' u='r' c='inter_pred_scaled_16bpp'/>
<use f='ffmpeg/libavcodec/vp9_mc_template.c' l='318' u='r' c='inter_pred_scaled_16bpp'/>
<use f='ffmpeg/libavcodec/vp9_mc_template.c' l='322' u='r' c='inter_pred_scaled_16bpp'/>
<use f='ffmpeg/libavcodec/vp9_mc_template.c' l='332' u='r' c='inter_pred_scaled_16bpp'/>
<use f='ffmpeg/libavcodec/vp9_mc_template.c' l='340' u='r' c='inter_pred_scaled_16bpp'/>
<use f='ffmpeg/libavcodec/vp9_mc_template.c' l='347' u='r' c='inter_pred_scaled_16bpp'/>
<use f='ffmpeg/libavcodec/vp9_mc_template.c' l='359' u='r' c='inter_pred_scaled_16bpp'/>
<use f='ffmpeg/libavcodec/vp9_mc_template.c' l='369' u='r' c='inter_pred_scaled_16bpp'/>
<use f='ffmpeg/libavcodec/vp9_mc_template.c' l='376' u='r' c='inter_pred_scaled_16bpp'/>
<use f='ffmpeg/libavcodec/vp9_mc_template.c' l='382' u='r' c='inter_pred_scaled_16bpp'/>
<use f='ffmpeg/libavcodec/vp9_mc_template.c' l='389' u='r' c='inter_pred_scaled_16bpp'/>
<use f='ffmpeg/libavcodec/vp9_mc_template.c' l='395' u='r' c='inter_pred_scaled_16bpp'/>
<use f='ffmpeg/libavcodec/vp9_mc_template.c' l='413' u='r' c='inter_pred_scaled_16bpp'/>
<use f='ffmpeg/libavcodec/vp9_mc_template.c' l='418' u='r' c='inter_pred_scaled_16bpp'/>
<use f='ffmpeg/libavcodec/vp9_mc_template.c' l='426' u='r' c='inter_pred_scaled_16bpp'/>
<use f='ffmpeg/libavcodec/vp9_mc_template.c' l='431' u='r' c='inter_pred_scaled_16bpp'/>
