<dec f='ffmpeg/libavcodec/vp9shared.h' l='60' type='ThreadFrame'/>
<use f='ffmpeg/libavcodec/vp9.c' l='106' u='a' c='vp9_frame_unref'/>
<use f='ffmpeg/libavcodec/vp9.c' l='118' u='a' c='vp9_frame_alloc'/>
<use f='ffmpeg/libavcodec/vp9.c' l='163' u='a' c='vp9_frame_ref'/>
<use f='ffmpeg/libavcodec/vp9.c' l='163' u='a' c='vp9_frame_ref'/>
<use f='ffmpeg/libavcodec/vp9.c' l='611' u='m' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='612' u='m' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='1101' u='m' c='decode_sb'/>
<use f='ffmpeg/libavcodec/vp9.c' l='1176' u='m' c='decode_sb_mem'/>
<use f='ffmpeg/libavcodec/vp9.c' l='1243' u='m' c='vp9_decode_free'/>
<use f='ffmpeg/libavcodec/vp9.c' l='1270' u='m' c='decode_tiles'/>
<use f='ffmpeg/libavcodec/vp9.c' l='1292' u='a' c='decode_tiles'/>
<use f='ffmpeg/libavcodec/vp9.c' l='1299' u='a' c='decode_tiles'/>
<use f='ffmpeg/libavcodec/vp9.c' l='1386' u='a' c='decode_tiles'/>
<use f='ffmpeg/libavcodec/vp9.c' l='1406' u='m' c='decode_tiles_mt'/>
<use f='ffmpeg/libavcodec/vp9.c' l='1479' u='m' c='loopfilter_proc'/>
<use f='ffmpeg/libavcodec/vp9.c' l='1512' u='m' c='vp9_export_enc_params'/>
<use f='ffmpeg/libavcodec/vp9.c' l='1595' u='m' c='vp9_decode_frame'/>
<use f='ffmpeg/libavcodec/vp9.c' l='1597' u='m' c='vp9_decode_frame'/>
<use f='ffmpeg/libavcodec/vp9.c' l='1601' u='m' c='vp9_decode_frame'/>
<use f='ffmpeg/libavcodec/vp9.c' l='1603' u='m' c='vp9_decode_frame'/>
<use f='ffmpeg/libavcodec/vp9.c' l='1606' u='m' c='vp9_decode_frame'/>
<use f='ffmpeg/libavcodec/vp9.c' l='1610' u='m' c='vp9_decode_frame'/>
<use f='ffmpeg/libavcodec/vp9.c' l='1614' u='m' c='vp9_decode_frame'/>
<use f='ffmpeg/libavcodec/vp9.c' l='1615' u='m' c='vp9_decode_frame'/>
<use f='ffmpeg/libavcodec/vp9.c' l='1615' u='m' c='vp9_decode_frame'/>
<use f='ffmpeg/libavcodec/vp9.c' l='1616' u='m' c='vp9_decode_frame'/>
<use f='ffmpeg/libavcodec/vp9.c' l='1616' u='m' c='vp9_decode_frame'/>
<use f='ffmpeg/libavcodec/vp9.c' l='1625' u='a' c='vp9_decode_frame'/>
<use f='ffmpeg/libavcodec/vp9.c' l='1739' u='a' c='vp9_decode_frame'/>
<use f='ffmpeg/libavcodec/vp9.c' l='1755' u='a' c='vp9_decode_frame'/>
<use f='ffmpeg/libavcodec/vp9.c' l='1779' u='m' c='vp9_decode_frame'/>
<use f='ffmpeg/libavcodec/vp9.c' l='1804' u='m' c='init_frames'/>
<use f='ffmpeg/libavcodec/vp9.c' l='1805' u='m' c='init_frames'/>
<use f='ffmpeg/libavcodec/vp9.c' l='1841' u='m' c='vp9_decode_update_thread_context'/>
<use f='ffmpeg/libavcodec/vp9.c' l='1843' u='m' c='vp9_decode_update_thread_context'/>
<offset>0</offset>
<use f='ffmpeg/libavcodec/vp9block.c' l='116' u='a' c='decode_mode'/>
<use f='ffmpeg/libavcodec/vp9block.c' l='1273' u='m' c='ff_vp9_decode_block'/>
<use f='ffmpeg/libavcodec/vp9lpf.c' l='182' u='m' c='ff_vp9_loopfilter_sb'/>
<use f='ffmpeg/libavcodec/vp9mvs.c' l='178' u='a' c='find_ref_mvs'/>
<use f='ffmpeg/libavcodec/vp9recon.c' l='231' u='m' c='intra_recon'/>
<use f='ffmpeg/libavcodec/vp9recon.c' l='246' u='m' c='intra_recon'/>
<use f='ffmpeg/libavcodec/vp9recon.c' l='254' u='m' c='intra_recon'/>
<use f='ffmpeg/libavcodec/vp9recon.c' l='265' u='m' c='intra_recon'/>
<use f='ffmpeg/libavcodec/vp9recon.c' l='275' u='m' c='intra_recon'/>
<use f='ffmpeg/libavcodec/vp9recon.c' l='283' u='m' c='intra_recon'/>
<use f='ffmpeg/libavcodec/vp9recon.c' l='418' u='m' c='mc_luma_scaled'/>
<use f='ffmpeg/libavcodec/vp9recon.c' l='419' u='m' c='mc_luma_scaled'/>
<use f='ffmpeg/libavcodec/vp9recon.c' l='478' u='m' c='mc_chroma_scaled'/>
<use f='ffmpeg/libavcodec/vp9recon.c' l='479' u='m' c='mc_chroma_scaled'/>
