<dec f='ffmpeg/libavcodec/vp9shared.h' l='160' type='VP9BitstreamHeader'/>
<use f='ffmpeg/libavcodec/vp9.c' l='299' u='m' c='update_size'/>
<use f='ffmpeg/libavcodec/vp9.c' l='300' u='m' c='update_size'/>
<use f='ffmpeg/libavcodec/vp9.c' l='301' u='m' c='update_size'/>
<use f='ffmpeg/libavcodec/vp9.c' l='302' u='m' c='update_size'/>
<use f='ffmpeg/libavcodec/vp9.c' l='453' u='m' c='read_colorspace_details'/>
<use f='ffmpeg/libavcodec/vp9.c' l='454' u='m' c='read_colorspace_details'/>
<use f='ffmpeg/libavcodec/vp9.c' l='529' u='m' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='535' u='m' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='536' u='m' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='538' u='m' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='539' u='m' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='540' u='m' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='541' u='m' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='541' u='m' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='543' u='m' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='551' u='m' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='557' u='m' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='557' u='m' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='558' u='m' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='558' u='m' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='559' u='m' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='569' u='m' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='576' u='m' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='582' u='m' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='583' u='m' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='584' u='m' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='584' u='m' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='585' u='m' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='586' u='m' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='586' u='m' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='587' u='m' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='588' u='m' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='588' u='m' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='589' u='m' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='590' u='m' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='591' u='m' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='596' u='m' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='597' u='m' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='599' u='m' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='600' u='m' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='602' u='m' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='603' u='m' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='611' u='m' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='615' u='m' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='616' u='m' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='618' u='m' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='618' u='m' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='618' u='m' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='619' u='m' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='619' u='m' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='620' u='m' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='621' u='m' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='621' u='m' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='622' u='m' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='623' u='m' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='624' u='m' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='625' u='m' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='625' u='m' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='626' u='m' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='627' u='m' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='628' u='m' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='630' u='m' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='631' u='m' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='632' u='m' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='637' u='m' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='637' u='m' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='638' u='m' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='638' u='m' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='639' u='m' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='640' u='m' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='640' u='m' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='641' u='m' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='644' u='m' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='644' u='m' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='644' u='m' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='646' u='m' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='647' u='m' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='648' u='m' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='649' u='m' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='650' u='m' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='651' u='m' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='652' u='m' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='652' u='m' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='654' u='m' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='658' u='m' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='672' u='m' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='673' u='m' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='674' u='m' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='677' u='m' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='680' u='m' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='685' u='m' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='686' u='m' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='687' u='m' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='688' u='m' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='689' u='m' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='689' u='m' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='689' u='m' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='690' u='m' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='690' u='m' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='691' u='m' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='695' u='m' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='696' u='m' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='698' u='m' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='700' u='m' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='702' u='m' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='707' u='m' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='709' u='m' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='710' u='m' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='711' u='m' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='712' u='m' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='713' u='m' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='714' u='m' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='715' u='m' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='721' u='m' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='724' u='m' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='724' u='m' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='725' u='m' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='726' u='m' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='728' u='m' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='728' u='m' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='730' u='m' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='732' u='m' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='733' u='m' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='734' u='m' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='737' u='m' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='738' u='m' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='739' u='m' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='740' u='m' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='742' u='m' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='743' u='m' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='743' u='m' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='744' u='m' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='745' u='m' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='747' u='m' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='747' u='m' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='749' u='m' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='751' u='m' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='752' u='m' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='753' u='m' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='754' u='m' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='756' u='m' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='757' u='m' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='758' u='m' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='759' u='m' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='760' u='m' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='761' u='m' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='764' u='m' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='765' u='m' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='775' u='m' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='776' u='m' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='777' u='m' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='780' u='m' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='782' u='m' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='786' u='m' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='787' u='m' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='787' u='m' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='788' u='m' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='788' u='m' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='798' u='m' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='798' u='m' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='801' u='m' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='806' u='m' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='821' u='m' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='821' u='m' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='824' u='m' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='858' u='m' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='858' u='m' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='858' u='m' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='858' u='m' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='869' u='m' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='869' u='m' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='876' u='m' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='877' u='m' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='894' u='m' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='894' u='m' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='909' u='m' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='910' u='m' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='912' u='m' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='913' u='m' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='914' u='m' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='916' u='m' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='966' u='m' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='974' u='m' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='974' u='m' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='981' u='m' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='992' u='m' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='993' u='m' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='994' u='m' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='995' u='m' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='996' u='m' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='1002' u='m' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='1005' u='m' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='1016' u='m' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='1075' u='m' c='decode_frame_header'/>
<use f='ffmpeg/libavcodec/vp9.c' l='1097' u='m' c='decode_sb'/>
<use f='ffmpeg/libavcodec/vp9.c' l='1097' u='m' c='decode_sb'/>
<use f='ffmpeg/libavcodec/vp9.c' l='1276' u='m' c='decode_tiles'/>
<use f='ffmpeg/libavcodec/vp9.c' l='1278' u='m' c='decode_tiles'/>
<use f='ffmpeg/libavcodec/vp9.c' l='1280' u='m' c='decode_tiles'/>
<use f='ffmpeg/libavcodec/vp9.c' l='1283' u='m' c='decode_tiles'/>
<use f='ffmpeg/libavcodec/vp9.c' l='1284' u='m' c='decode_tiles'/>
<use f='ffmpeg/libavcodec/vp9.c' l='1311' u='m' c='decode_tiles'/>
<use f='ffmpeg/libavcodec/vp9.c' l='1313' u='m' c='decode_tiles'/>
<use f='ffmpeg/libavcodec/vp9.c' l='1318' u='m' c='decode_tiles'/>
<use f='ffmpeg/libavcodec/vp9.c' l='1318' u='m' c='decode_tiles'/>
<use f='ffmpeg/libavcodec/vp9.c' l='1371' u='m' c='decode_tiles'/>
<use f='ffmpeg/libavcodec/vp9.c' l='1411' u='m' c='decode_tiles_mt'/>
<use f='ffmpeg/libavcodec/vp9.c' l='1417' u='m' c='decode_tiles_mt'/>
<use f='ffmpeg/libavcodec/vp9.c' l='1419' u='m' c='decode_tiles_mt'/>
<use f='ffmpeg/libavcodec/vp9.c' l='1429' u='m' c='decode_tiles_mt'/>
<use f='ffmpeg/libavcodec/vp9.c' l='1429' u='m' c='decode_tiles_mt'/>
<use f='ffmpeg/libavcodec/vp9.c' l='1484' u='m' c='loopfilter_proc'/>
<use f='ffmpeg/libavcodec/vp9.c' l='1486' u='m' c='loopfilter_proc'/>
<use f='ffmpeg/libavcodec/vp9.c' l='1507' u='m' c='vp9_export_enc_params'/>
<use f='ffmpeg/libavcodec/vp9.c' l='1517' u='m' c='vp9_export_enc_params'/>
<use f='ffmpeg/libavcodec/vp9.c' l='1518' u='m' c='vp9_export_enc_params'/>
<use f='ffmpeg/libavcodec/vp9.c' l='1519' u='m' c='vp9_export_enc_params'/>
<use f='ffmpeg/libavcodec/vp9.c' l='1520' u='m' c='vp9_export_enc_params'/>
<use f='ffmpeg/libavcodec/vp9.c' l='1521' u='m' c='vp9_export_enc_params'/>
<use f='ffmpeg/libavcodec/vp9.c' l='1522' u='m' c='vp9_export_enc_params'/>
<use f='ffmpeg/libavcodec/vp9.c' l='1542' u='m' c='vp9_export_enc_params'/>
<use f='ffmpeg/libavcodec/vp9.c' l='1543' u='m' c='vp9_export_enc_params'/>
<use f='ffmpeg/libavcodec/vp9.c' l='1544' u='m' c='vp9_export_enc_params'/>
<use f='ffmpeg/libavcodec/vp9.c' l='1562' u='m' c='vp9_decode_frame'/>
<use f='ffmpeg/libavcodec/vp9.c' l='1562' u='m' c='vp9_decode_frame'/>
<use f='ffmpeg/libavcodec/vp9.c' l='1594' u='m' c='vp9_decode_frame'/>
<use f='ffmpeg/libavcodec/vp9.c' l='1594' u='m' c='vp9_decode_frame'/>
<use f='ffmpeg/libavcodec/vp9.c' l='1597' u='m' c='vp9_decode_frame'/>
<use f='ffmpeg/libavcodec/vp9.c' l='1597' u='m' c='vp9_decode_frame'/>
<use f='ffmpeg/libavcodec/vp9.c' l='1597' u='m' c='vp9_decode_frame'/>
<use f='ffmpeg/libavcodec/vp9.c' l='1603' u='m' c='vp9_decode_frame'/>
<use f='ffmpeg/libavcodec/vp9.c' l='1603' u='m' c='vp9_decode_frame'/>
<use f='ffmpeg/libavcodec/vp9.c' l='1603' u='m' c='vp9_decode_frame'/>
<use f='ffmpeg/libavcodec/vp9.c' l='1611' u='m' c='vp9_decode_frame'/>
<use f='ffmpeg/libavcodec/vp9.c' l='1612' u='m' c='vp9_decode_frame'/>
<use f='ffmpeg/libavcodec/vp9.c' l='1612' u='m' c='vp9_decode_frame'/>
<use f='ffmpeg/libavcodec/vp9.c' l='1624' u='m' c='vp9_decode_frame'/>
<use f='ffmpeg/libavcodec/vp9.c' l='1649' u='m' c='vp9_decode_frame'/>
<use f='ffmpeg/libavcodec/vp9.c' l='1649' u='m' c='vp9_decode_frame'/>
<use f='ffmpeg/libavcodec/vp9.c' l='1659' u='m' c='vp9_decode_frame'/>
<use f='ffmpeg/libavcodec/vp9.c' l='1659' u='m' c='vp9_decode_frame'/>
<use f='ffmpeg/libavcodec/vp9.c' l='1665' u='m' c='vp9_decode_frame'/>
<use f='ffmpeg/libavcodec/vp9.c' l='1665' u='m' c='vp9_decode_frame'/>
<use f='ffmpeg/libavcodec/vp9.c' l='1673' u='m' c='vp9_decode_frame'/>
<use f='ffmpeg/libavcodec/vp9.c' l='1675' u='m' c='vp9_decode_frame'/>
<use f='ffmpeg/libavcodec/vp9.c' l='1678' u='m' c='vp9_decode_frame'/>
<use f='ffmpeg/libavcodec/vp9.c' l='1680' u='m' c='vp9_decode_frame'/>
<use f='ffmpeg/libavcodec/vp9.c' l='1709' u='m' c='vp9_decode_frame'/>
<use f='ffmpeg/libavcodec/vp9.c' l='1710' u='m' c='vp9_decode_frame'/>
<use f='ffmpeg/libavcodec/vp9.c' l='1713' u='m' c='vp9_decode_frame'/>
<use f='ffmpeg/libavcodec/vp9.c' l='1714' u='m' c='vp9_decode_frame'/>
<use f='ffmpeg/libavcodec/vp9.c' l='1733' u='m' c='vp9_decode_frame'/>
<use f='ffmpeg/libavcodec/vp9.c' l='1746' u='m' c='vp9_decode_frame'/>
<use f='ffmpeg/libavcodec/vp9.c' l='1750' u='m' c='vp9_decode_frame'/>
<use f='ffmpeg/libavcodec/vp9.c' l='1750' u='m' c='vp9_decode_frame'/>
<use f='ffmpeg/libavcodec/vp9.c' l='1778' u='m' c='vp9_decode_frame'/>
<use f='ffmpeg/libavcodec/vp9.c' l='1829' u='m' c='vp9_decode_init'/>
<use f='ffmpeg/libavcodec/vp9.c' l='1857' u='m' c='vp9_decode_update_thread_context'/>
<use f='ffmpeg/libavcodec/vp9.c' l='1857' u='m' c='vp9_decode_update_thread_context'/>
<use f='ffmpeg/libavcodec/vp9.c' l='1858' u='m' c='vp9_decode_update_thread_context'/>
<use f='ffmpeg/libavcodec/vp9.c' l='1858' u='m' c='vp9_decode_update_thread_context'/>
<use f='ffmpeg/libavcodec/vp9.c' l='1859' u='m' c='vp9_decode_update_thread_context'/>
<use f='ffmpeg/libavcodec/vp9.c' l='1859' u='m' c='vp9_decode_update_thread_context'/>
<use f='ffmpeg/libavcodec/vp9.c' l='1862' u='m' c='vp9_decode_update_thread_context'/>
<use f='ffmpeg/libavcodec/vp9.c' l='1862' u='m' c='vp9_decode_update_thread_context'/>
<use f='ffmpeg/libavcodec/vp9.c' l='1863' u='m' c='vp9_decode_update_thread_context'/>
<use f='ffmpeg/libavcodec/vp9.c' l='1863' u='m' c='vp9_decode_update_thread_context'/>
<use f='ffmpeg/libavcodec/vp9.c' l='1864' u='m' c='vp9_decode_update_thread_context'/>
<use f='ffmpeg/libavcodec/vp9.c' l='1864' u='m' c='vp9_decode_update_thread_context'/>
<use f='ffmpeg/libavcodec/vp9.c' l='1869' u='m' c='vp9_decode_update_thread_context'/>
<use f='ffmpeg/libavcodec/vp9.c' l='1869' u='m' c='vp9_decode_update_thread_context'/>
<use f='ffmpeg/libavcodec/vp9.c' l='1873' u='m' c='vp9_decode_update_thread_context'/>
<use f='ffmpeg/libavcodec/vp9.c' l='1873' u='m' c='vp9_decode_update_thread_context'/>
<use f='ffmpeg/libavcodec/vp9.c' l='1873' u='m' c='vp9_decode_update_thread_context'/>
<use f='ffmpeg/libavcodec/vp9.c' l='1874' u='m' c='vp9_decode_update_thread_context'/>
<use f='ffmpeg/libavcodec/vp9.c' l='1874' u='m' c='vp9_decode_update_thread_context'/>
<use f='ffmpeg/libavcodec/vp9.c' l='1875' u='m' c='vp9_decode_update_thread_context'/>
<offset>0</offset>
<use f='ffmpeg/libavcodec/vp9block.c' l='101' u='m' c='decode_mode'/>
<use f='ffmpeg/libavcodec/vp9block.c' l='103' u='m' c='decode_mode'/>
<use f='ffmpeg/libavcodec/vp9block.c' l='103' u='m' c='decode_mode'/>
<use f='ffmpeg/libavcodec/vp9block.c' l='104' u='m' c='decode_mode'/>
<use f='ffmpeg/libavcodec/vp9block.c' l='105' u='m' c='decode_mode'/>
<use f='ffmpeg/libavcodec/vp9block.c' l='106' u='m' c='decode_mode'/>
<use f='ffmpeg/libavcodec/vp9block.c' l='107' u='m' c='decode_mode'/>
<use f='ffmpeg/libavcodec/vp9block.c' l='109' u='m' c='decode_mode'/>
<use f='ffmpeg/libavcodec/vp9block.c' l='111' u='m' c='decode_mode'/>
<use f='ffmpeg/libavcodec/vp9block.c' l='132' u='m' c='decode_mode'/>
<use f='ffmpeg/libavcodec/vp9block.c' l='137' u='m' c='decode_mode'/>
<use f='ffmpeg/libavcodec/vp9block.c' l='138' u='m' c='decode_mode'/>
<use f='ffmpeg/libavcodec/vp9block.c' l='138' u='m' c='decode_mode'/>
<use f='ffmpeg/libavcodec/vp9block.c' l='138' u='m' c='decode_mode'/>
<use f='ffmpeg/libavcodec/vp9block.c' l='143' u='m' c='decode_mode'/>
<use f='ffmpeg/libavcodec/vp9block.c' l='144' u='m' c='decode_mode'/>
<use f='ffmpeg/libavcodec/vp9block.c' l='151' u='m' c='decode_mode'/>
<use f='ffmpeg/libavcodec/vp9block.c' l='151' u='m' c='decode_mode'/>
<use f='ffmpeg/libavcodec/vp9block.c' l='153' u='m' c='decode_mode'/>
<use f='ffmpeg/libavcodec/vp9block.c' l='153' u='m' c='decode_mode'/>
<use f='ffmpeg/libavcodec/vp9block.c' l='154' u='m' c='decode_mode'/>
<use f='ffmpeg/libavcodec/vp9block.c' l='170' u='m' c='decode_mode'/>
<use f='ffmpeg/libavcodec/vp9block.c' l='213' u='m' c='decode_mode'/>
<use f='ffmpeg/libavcodec/vp9block.c' l='213' u='m' c='decode_mode'/>
<use f='ffmpeg/libavcodec/vp9block.c' l='216' u='m' c='decode_mode'/>
<use f='ffmpeg/libavcodec/vp9block.c' l='216' u='m' c='decode_mode'/>
<use f='ffmpeg/libavcodec/vp9block.c' l='332' u='m' c='decode_mode'/>
<use f='ffmpeg/libavcodec/vp9block.c' l='332' u='m' c='decode_mode'/>
<use f='ffmpeg/libavcodec/vp9block.c' l='335' u='m' c='decode_mode'/>
<use f='ffmpeg/libavcodec/vp9block.c' l='338' u='m' c='decode_mode'/>
<use f='ffmpeg/libavcodec/vp9block.c' l='339' u='m' c='decode_mode'/>
<use f='ffmpeg/libavcodec/vp9block.c' l='350' u='m' c='decode_mode'/>
<use f='ffmpeg/libavcodec/vp9block.c' l='353' u='m' c='decode_mode'/>
<use f='ffmpeg/libavcodec/vp9block.c' l='356' u='m' c='decode_mode'/>
<use f='ffmpeg/libavcodec/vp9block.c' l='358' u='m' c='decode_mode'/>
<use f='ffmpeg/libavcodec/vp9block.c' l='362' u='m' c='decode_mode'/>
<use f='ffmpeg/libavcodec/vp9block.c' l='366' u='m' c='decode_mode'/>
<use f='ffmpeg/libavcodec/vp9block.c' l='378' u='m' c='decode_mode'/>
<use f='ffmpeg/libavcodec/vp9block.c' l='378' u='m' c='decode_mode'/>
<use f='ffmpeg/libavcodec/vp9block.c' l='380' u='m' c='decode_mode'/>
<use f='ffmpeg/libavcodec/vp9block.c' l='388' u='m' c='decode_mode'/>
<use f='ffmpeg/libavcodec/vp9block.c' l='391' u='m' c='decode_mode'/>
<use f='ffmpeg/libavcodec/vp9block.c' l='395' u='m' c='decode_mode'/>
<use f='ffmpeg/libavcodec/vp9block.c' l='398' u='m' c='decode_mode'/>
<use f='ffmpeg/libavcodec/vp9block.c' l='398' u='m' c='decode_mode'/>
<use f='ffmpeg/libavcodec/vp9block.c' l='399' u='m' c='decode_mode'/>
<use f='ffmpeg/libavcodec/vp9block.c' l='399' u='m' c='decode_mode'/>
<use f='ffmpeg/libavcodec/vp9block.c' l='405' u='m' c='decode_mode'/>
<use f='ffmpeg/libavcodec/vp9block.c' l='405' u='m' c='decode_mode'/>
<use f='ffmpeg/libavcodec/vp9block.c' l='408' u='m' c='decode_mode'/>
<use f='ffmpeg/libavcodec/vp9block.c' l='409' u='m' c='decode_mode'/>
<use f='ffmpeg/libavcodec/vp9block.c' l='412' u='m' c='decode_mode'/>
<use f='ffmpeg/libavcodec/vp9block.c' l='412' u='m' c='decode_mode'/>
<use f='ffmpeg/libavcodec/vp9block.c' l='415' u='m' c='decode_mode'/>
<use f='ffmpeg/libavcodec/vp9block.c' l='416' u='m' c='decode_mode'/>
<use f='ffmpeg/libavcodec/vp9block.c' l='426' u='m' c='decode_mode'/>
<use f='ffmpeg/libavcodec/vp9block.c' l='428' u='m' c='decode_mode'/>
<use f='ffmpeg/libavcodec/vp9block.c' l='435' u='m' c='decode_mode'/>
<use f='ffmpeg/libavcodec/vp9block.c' l='437' u='m' c='decode_mode'/>
<use f='ffmpeg/libavcodec/vp9block.c' l='443' u='m' c='decode_mode'/>
<use f='ffmpeg/libavcodec/vp9block.c' l='452' u='m' c='decode_mode'/>
<use f='ffmpeg/libavcodec/vp9block.c' l='456' u='m' c='decode_mode'/>
<use f='ffmpeg/libavcodec/vp9block.c' l='460' u='m' c='decode_mode'/>
<use f='ffmpeg/libavcodec/vp9block.c' l='467' u='m' c='decode_mode'/>
<use f='ffmpeg/libavcodec/vp9block.c' l='475' u='m' c='decode_mode'/>
<use f='ffmpeg/libavcodec/vp9block.c' l='494' u='m' c='decode_mode'/>
<use f='ffmpeg/libavcodec/vp9block.c' l='505' u='m' c='decode_mode'/>
<use f='ffmpeg/libavcodec/vp9block.c' l='515' u='m' c='decode_mode'/>
<use f='ffmpeg/libavcodec/vp9block.c' l='521' u='m' c='decode_mode'/>
<use f='ffmpeg/libavcodec/vp9block.c' l='525' u='m' c='decode_mode'/>
<use f='ffmpeg/libavcodec/vp9block.c' l='529' u='m' c='decode_mode'/>
<use f='ffmpeg/libavcodec/vp9block.c' l='533' u='m' c='decode_mode'/>
<use f='ffmpeg/libavcodec/vp9block.c' l='552' u='m' c='decode_mode'/>
<use f='ffmpeg/libavcodec/vp9block.c' l='562' u='m' c='decode_mode'/>
<use f='ffmpeg/libavcodec/vp9block.c' l='577' u='m' c='decode_mode'/>
<use f='ffmpeg/libavcodec/vp9block.c' l='577' u='m' c='decode_mode'/>
<use f='ffmpeg/libavcodec/vp9block.c' l='601' u='m' c='decode_mode'/>
<use f='ffmpeg/libavcodec/vp9block.c' l='622' u='m' c='decode_mode'/>
<use f='ffmpeg/libavcodec/vp9block.c' l='678' u='m' c='decode_mode'/>
<use f='ffmpeg/libavcodec/vp9block.c' l='678' u='m' c='decode_mode'/>
<use f='ffmpeg/libavcodec/vp9block.c' l='724' u='m' c='decode_mode'/>
<use f='ffmpeg/libavcodec/vp9block.c' l='724' u='m' c='decode_mode'/>
<use f='ffmpeg/libavcodec/vp9block.c' l='730' u='m' c='decode_mode'/>
<use f='ffmpeg/libavcodec/vp9block.c' l='724' u='m' c='decode_mode'/>
<use f='ffmpeg/libavcodec/vp9block.c' l='724' u='m' c='decode_mode'/>
<use f='ffmpeg/libavcodec/vp9block.c' l='730' u='m' c='decode_mode'/>
<use f='ffmpeg/libavcodec/vp9block.c' l='724' u='m' c='decode_mode'/>
<use f='ffmpeg/libavcodec/vp9block.c' l='724' u='m' c='decode_mode'/>
<use f='ffmpeg/libavcodec/vp9block.c' l='730' u='m' c='decode_mode'/>
<use f='ffmpeg/libavcodec/vp9block.c' l='724' u='m' c='decode_mode'/>
<use f='ffmpeg/libavcodec/vp9block.c' l='724' u='m' c='decode_mode'/>
<use f='ffmpeg/libavcodec/vp9block.c' l='730' u='m' c='decode_mode'/>
<use f='ffmpeg/libavcodec/vp9block.c' l='724' u='m' c='decode_mode'/>
<use f='ffmpeg/libavcodec/vp9block.c' l='724' u='m' c='decode_mode'/>
<use f='ffmpeg/libavcodec/vp9block.c' l='730' u='m' c='decode_mode'/>
<use f='ffmpeg/libavcodec/vp9block.c' l='724' u='m' c='decode_mode'/>
<use f='ffmpeg/libavcodec/vp9block.c' l='724' u='m' c='decode_mode'/>
<use f='ffmpeg/libavcodec/vp9block.c' l='730' u='m' c='decode_mode'/>
<use f='ffmpeg/libavcodec/vp9block.c' l='724' u='m' c='decode_mode'/>
<use f='ffmpeg/libavcodec/vp9block.c' l='724' u='m' c='decode_mode'/>
<use f='ffmpeg/libavcodec/vp9block.c' l='730' u='m' c='decode_mode'/>
<use f='ffmpeg/libavcodec/vp9block.c' l='724' u='m' c='decode_mode'/>
<use f='ffmpeg/libavcodec/vp9block.c' l='724' u='m' c='decode_mode'/>
<use f='ffmpeg/libavcodec/vp9block.c' l='730' u='m' c='decode_mode'/>
<use f='ffmpeg/libavcodec/vp9block.c' l='750' u='m' c='decode_mode'/>
<use f='ffmpeg/libavcodec/vp9block.c' l='750' u='m' c='decode_mode'/>
<use f='ffmpeg/libavcodec/vp9block.c' l='950' u='m' c='decode_coeffs_b_16bpp'/>
<use f='ffmpeg/libavcodec/vp9block.c' l='960' u='m' c='decode_coeffs_b32_16bpp'/>
<use f='ffmpeg/libavcodec/vp9block.c' l='976' u='m' c='decode_coeffs'/>
<use f='ffmpeg/libavcodec/vp9block.c' l='977' u='m' c='decode_coeffs'/>
<use f='ffmpeg/libavcodec/vp9block.c' l='1388' u='m' c='ff_vp9_decode_block'/>
<use f='ffmpeg/libavcodec/vp9block.c' l='1394' u='m' c='ff_vp9_decode_block'/>
<use f='ffmpeg/libavcodec/vp9block.c' l='1433' u='m' c='ff_vp9_decode_block'/>
<use f='ffmpeg/libavcodec/vp9block.c' l='1434' u='m' c='ff_vp9_decode_block'/>
<use f='ffmpeg/libavcodec/vp9mvs.c' l='174' u='m' c='find_ref_mvs'/>
<use f='ffmpeg/libavcodec/vp9mvs.c' l='204' u='m' c='find_ref_mvs'/>
<use f='ffmpeg/libavcodec/vp9mvs.c' l='204' u='m' c='find_ref_mvs'/>
<use f='ffmpeg/libavcodec/vp9mvs.c' l='209' u='m' c='find_ref_mvs'/>
<use f='ffmpeg/libavcodec/vp9mvs.c' l='209' u='m' c='find_ref_mvs'/>
<use f='ffmpeg/libavcodec/vp9mvs.c' l='215' u='m' c='find_ref_mvs'/>
<use f='ffmpeg/libavcodec/vp9mvs.c' l='220' u='m' c='find_ref_mvs'/>
<use f='ffmpeg/libavcodec/vp9mvs.c' l='220' u='m' c='find_ref_mvs'/>
<use f='ffmpeg/libavcodec/vp9mvs.c' l='225' u='m' c='find_ref_mvs'/>
<use f='ffmpeg/libavcodec/vp9mvs.c' l='225' u='m' c='find_ref_mvs'/>
<use f='ffmpeg/libavcodec/vp9mvs.c' l='306' u='m' c='ff_vp9_fill_mv'/>
<use f='ffmpeg/libavcodec/vp9mvs.c' l='337' u='m' c='ff_vp9_fill_mv'/>
<use f='ffmpeg/libavcodec/vp9prob.c' l='49' u='m' c='ff_vp9_adapt_probs'/>
<use f='ffmpeg/libavcodec/vp9prob.c' l='50' u='m' c='ff_vp9_adapt_probs'/>
<use f='ffmpeg/libavcodec/vp9prob.c' l='50' u='m' c='ff_vp9_adapt_probs'/>
<use f='ffmpeg/libavcodec/vp9prob.c' l='58' u='m' c='ff_vp9_adapt_probs'/>
<use f='ffmpeg/libavcodec/vp9prob.c' l='70' u='m' c='ff_vp9_adapt_probs'/>
<use f='ffmpeg/libavcodec/vp9prob.c' l='70' u='m' c='ff_vp9_adapt_probs'/>
<use f='ffmpeg/libavcodec/vp9prob.c' l='89' u='m' c='ff_vp9_adapt_probs'/>
<use f='ffmpeg/libavcodec/vp9prob.c' l='96' u='m' c='ff_vp9_adapt_probs'/>
<use f='ffmpeg/libavcodec/vp9prob.c' l='102' u='m' c='ff_vp9_adapt_probs'/>
<use f='ffmpeg/libavcodec/vp9prob.c' l='124' u='m' c='ff_vp9_adapt_probs'/>
<use f='ffmpeg/libavcodec/vp9prob.c' l='139' u='m' c='ff_vp9_adapt_probs'/>
<use f='ffmpeg/libavcodec/vp9prob.c' l='216' u='m' c='ff_vp9_adapt_probs'/>
<use f='ffmpeg/libavcodec/vp9recon.c' l='44' u='m' c='check_intra_mode'/>
<use f='ffmpeg/libavcodec/vp9recon.c' l='229' u='m' c='intra_recon'/>
<use f='ffmpeg/libavcodec/vp9recon.c' l='229' u='m' c='intra_recon'/>
<use f='ffmpeg/libavcodec/vp9_mc_template.c' l='39' u='m' c='inter_pred_8bpp'/>
<use f='ffmpeg/libavcodec/vp9_mc_template.c' l='46' u='m' c='inter_pred_8bpp'/>
<use f='ffmpeg/libavcodec/vp9_mc_template.c' l='39' u='m' c='inter_pred_16bpp'/>
<use f='ffmpeg/libavcodec/vp9_mc_template.c' l='46' u='m' c='inter_pred_16bpp'/>
<use f='ffmpeg/libavcodec/vp9_mc_template.c' l='39' u='m' c='inter_pred_scaled_8bpp'/>
<use f='ffmpeg/libavcodec/vp9_mc_template.c' l='46' u='m' c='inter_pred_scaled_8bpp'/>
<use f='ffmpeg/libavcodec/vp9_mc_template.c' l='39' u='m' c='inter_pred_scaled_16bpp'/>
<use f='ffmpeg/libavcodec/vp9_mc_template.c' l='46' u='m' c='inter_pred_scaled_16bpp'/>
<use f='ffmpeg/libavcodec/vp9recon.c' l='607' u='m' c='inter_recon'/>
<use f='ffmpeg/libavcodec/vp9recon.c' l='607' u='m' c='inter_recon'/>
