<dec f='ffmpeg/libavcodec/vp9dec.h' l='169' type='VP56RangeCoder *'/>
<use f='ffmpeg/libavcodec/vp9.c' l='1106' u='r' c='decode_sb'/>
<use f='ffmpeg/libavcodec/vp9.c' l='1110' u='r' c='decode_sb'/>
<use f='ffmpeg/libavcodec/vp9.c' l='1142' u='r' c='decode_sb'/>
<use f='ffmpeg/libavcodec/vp9.c' l='1153' u='r' c='decode_sb'/>
<use f='ffmpeg/libavcodec/vp9.c' l='1327' u='w' c='decode_tiles'/>
<use f='ffmpeg/libavcodec/vp9.c' l='1344' u='r' c='decode_tiles'/>
<use f='ffmpeg/libavcodec/vp9.c' l='1421' u='w' c='decode_tiles_mt'/>
<offset>128</offset>
<use f='ffmpeg/libavcodec/vp9block.c' l='105' u='r' c='decode_mode'/>
<use f='ffmpeg/libavcodec/vp9block.c' l='108' u='r' c='decode_mode'/>
<use f='ffmpeg/libavcodec/vp9block.c' l='131' u='r' c='decode_mode'/>
<use f='ffmpeg/libavcodec/vp9block.c' l='147' u='r' c='decode_mode'/>
<use f='ffmpeg/libavcodec/vp9block.c' l='165' u='r' c='decode_mode'/>
<use f='ffmpeg/libavcodec/vp9block.c' l='190' u='r' c='decode_mode'/>
<use f='ffmpeg/libavcodec/vp9block.c' l='192' u='r' c='decode_mode'/>
<use f='ffmpeg/libavcodec/vp9block.c' l='194' u='r' c='decode_mode'/>
<use f='ffmpeg/libavcodec/vp9block.c' l='199' u='r' c='decode_mode'/>
<use f='ffmpeg/libavcodec/vp9block.c' l='201' u='r' c='decode_mode'/>
<use f='ffmpeg/libavcodec/vp9block.c' l='205' u='r' c='decode_mode'/>
<use f='ffmpeg/libavcodec/vp9block.c' l='226' u='r' c='decode_mode'/>
<use f='ffmpeg/libavcodec/vp9block.c' l='229' u='r' c='decode_mode'/>
<use f='ffmpeg/libavcodec/vp9block.c' l='240' u='r' c='decode_mode'/>
<use f='ffmpeg/libavcodec/vp9block.c' l='243' u='r' c='decode_mode'/>
<use f='ffmpeg/libavcodec/vp9block.c' l='259' u='r' c='decode_mode'/>
<use f='ffmpeg/libavcodec/vp9block.c' l='268' u='r' c='decode_mode'/>
<use f='ffmpeg/libavcodec/vp9block.c' l='273' u='r' c='decode_mode'/>
<use f='ffmpeg/libavcodec/vp9block.c' l='277' u='r' c='decode_mode'/>
<use f='ffmpeg/libavcodec/vp9block.c' l='284' u='r' c='decode_mode'/>
<use f='ffmpeg/libavcodec/vp9block.c' l='288' u='r' c='decode_mode'/>
<use f='ffmpeg/libavcodec/vp9block.c' l='304' u='r' c='decode_mode'/>
<use f='ffmpeg/libavcodec/vp9block.c' l='311' u='r' c='decode_mode'/>
<use f='ffmpeg/libavcodec/vp9block.c' l='370' u='r' c='decode_mode'/>
<use f='ffmpeg/libavcodec/vp9block.c' l='442' u='r' c='decode_mode'/>
<use f='ffmpeg/libavcodec/vp9block.c' l='482' u='r' c='decode_mode'/>
<use f='ffmpeg/libavcodec/vp9block.c' l='569' u='r' c='decode_mode'/>
<use f='ffmpeg/libavcodec/vp9block.c' l='592' u='r' c='decode_mode'/>
<use f='ffmpeg/libavcodec/vp9block.c' l='617' u='r' c='decode_mode'/>
<use f='ffmpeg/libavcodec/vp9block.c' l='628' u='r' c='decode_mode'/>
<use f='ffmpeg/libavcodec/vp9block.c' l='634' u='r' c='decode_mode'/>
<use f='ffmpeg/libavcodec/vp9block.c' l='645' u='r' c='decode_mode'/>
<use f='ffmpeg/libavcodec/vp9block.c' l='651' u='r' c='decode_mode'/>
<use f='ffmpeg/libavcodec/vp9block.c' l='930' u='r' c='decode_coeffs_b_8bpp'/>
<use f='ffmpeg/libavcodec/vp9block.c' l='940' u='r' c='decode_coeffs_b32_8bpp'/>
<use f='ffmpeg/libavcodec/vp9block.c' l='950' u='r' c='decode_coeffs_b_16bpp'/>
<use f='ffmpeg/libavcodec/vp9block.c' l='960' u='r' c='decode_coeffs_b32_16bpp'/>
<use f='ffmpeg/libavcodec/vp9mvs.c' l='239' u='r' c='read_mv_component'/>
<use f='ffmpeg/libavcodec/vp9mvs.c' l='240' u='r' c='read_mv_component'/>
<use f='ffmpeg/libavcodec/vp9mvs.c' l='249' u='r' c='read_mv_component'/>
<use f='ffmpeg/libavcodec/vp9mvs.c' l='254' u='r' c='read_mv_component'/>
<use f='ffmpeg/libavcodec/vp9mvs.c' l='259' u='r' c='read_mv_component'/>
<use f='ffmpeg/libavcodec/vp9mvs.c' l='270' u='r' c='read_mv_component'/>
<use f='ffmpeg/libavcodec/vp9mvs.c' l='272' u='r' c='read_mv_component'/>
<use f='ffmpeg/libavcodec/vp9mvs.c' l='277' u='r' c='read_mv_component'/>
<use f='ffmpeg/libavcodec/vp9mvs.c' l='322' u='r' c='ff_vp9_fill_mv'/>
<use f='ffmpeg/libavcodec/vp9mvs.c' l='353' u='r' c='ff_vp9_fill_mv'/>
