<def f='halide/build-apps/flatbuffers/include/flatbuffers/flexbuffers.h' l='897' ll='1609'/>
<use f='halide/build-apps/flatbuffers/include/flatbuffers/flexbuffers.h' l='1566' c='_ZN11flexbuffers7BuilderC1ERKS0_'/>
<use f='halide/build-apps/flatbuffers/include/flatbuffers/flexbuffers.h' l='1567' c='_ZN11flexbuffers7BuilderaSERKS0_'/>
<use f='halide/build-apps/flatbuffers/include/flatbuffers/flexbuffers.h' l='1567' c='_ZN11flexbuffers7BuilderaSERKS0_'/>
<size>160</size>
<fun r='_ZN11flexbuffers7BuilderC1EmNS_11BuilderFlagE'/>
<fun r='_ZNK11flexbuffers7Builder9GetBufferEv'/>
<fun r='_ZNK11flexbuffers7Builder7GetSizeEv'/>
<fun r='_ZN11flexbuffers7Builder5ClearEv'/>
<fun r='_ZN11flexbuffers7Builder4NullEv'/>
<fun r='_ZN11flexbuffers7Builder4NullEPKc'/>
<fun r='_ZN11flexbuffers7Builder3IntEl'/>
<fun r='_ZN11flexbuffers7Builder3IntEPKcl'/>
<fun r='_ZN11flexbuffers7Builder4UIntEm'/>
<fun r='_ZN11flexbuffers7Builder4UIntEPKcm'/>
<fun r='_ZN11flexbuffers7Builder5FloatEf'/>
<fun r='_ZN11flexbuffers7Builder5FloatEPKcf'/>
<fun r='_ZN11flexbuffers7Builder6DoubleEd'/>
<fun r='_ZN11flexbuffers7Builder6DoubleEPKcd'/>
<fun r='_ZN11flexbuffers7Builder4BoolEb'/>
<fun r='_ZN11flexbuffers7Builder4BoolEPKcb'/>
<fun r='_ZN11flexbuffers7Builder11IndirectIntEl'/>
<fun r='_ZN11flexbuffers7Builder11IndirectIntEPKcl'/>
<fun r='_ZN11flexbuffers7Builder12IndirectUIntEm'/>
<fun r='_ZN11flexbuffers7Builder12IndirectUIntEPKcm'/>
<fun r='_ZN11flexbuffers7Builder13IndirectFloatEf'/>
<fun r='_ZN11flexbuffers7Builder13IndirectFloatEPKcf'/>
<fun r='_ZN11flexbuffers7Builder14IndirectDoubleEd'/>
<fun r='_ZN11flexbuffers7Builder14IndirectDoubleEPKcd'/>
<fun r='_ZN11flexbuffers7Builder3KeyEPKcm'/>
<fun r='_ZN11flexbuffers7Builder3KeyEPKc'/>
<fun r='_ZN11flexbuffers7Builder3KeyERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE'/>
<fun r='_ZN11flexbuffers7Builder6StringEPKcm'/>
<fun r='_ZN11flexbuffers7Builder6StringEPKc'/>
<fun r='_ZN11flexbuffers7Builder6StringERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE'/>
<fun r='_ZN11flexbuffers7Builder6StringERKNS_6StringE'/>
<fun r='_ZN11flexbuffers7Builder6StringEPKcS2_'/>
<fun r='_ZN11flexbuffers7Builder6StringEPKcRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE'/>
<fun r='_ZN11flexbuffers7Builder6StringEPKcRKNS_6StringE'/>
<fun r='_ZN11flexbuffers7Builder4BlobEPKvm'/>
<fun r='_ZN11flexbuffers7Builder4BlobERKSt6vectorIhSaIhEE'/>
<fun r='_ZN11flexbuffers7Builder11StartVectorEv'/>
<fun r='_ZN11flexbuffers7Builder11StartVectorEPKc'/>
<fun r='_ZN11flexbuffers7Builder8StartMapEv'/>
<fun r='_ZN11flexbuffers7Builder8StartMapEPKc'/>
<fun r='_ZN11flexbuffers7Builder9EndVectorEmbb'/>
<fun r='_ZN11flexbuffers7Builder6EndMapEm'/>
<fun r='_ZN11flexbuffers7Builder6VectorET_'/>
<fun r='_ZN11flexbuffers7Builder6VectorET_RT0_'/>
<fun r='_ZN11flexbuffers7Builder6VectorEPKcT_'/>
<fun r='_ZN11flexbuffers7Builder6VectorEPKcT_RT0_'/>
<fun r='_ZN11flexbuffers7Builder6VectorEPKT_m'/>
<fun r='_ZN11flexbuffers7Builder6VectorEPKcPKT_m'/>
<fun r='_ZN11flexbuffers7Builder6VectorERKSt6vectorIT_SaIS2_EE'/>
<fun r='_ZN11flexbuffers7Builder11TypedVectorET_'/>
<fun r='_ZN11flexbuffers7Builder11TypedVectorET_RT0_'/>
<fun r='_ZN11flexbuffers7Builder11TypedVectorEPKcT_'/>
<fun r='_ZN11flexbuffers7Builder11TypedVectorEPKcT_RT0_'/>
<fun r='_ZN11flexbuffers7Builder16FixedTypedVectorEPKT_m'/>
<fun r='_ZN11flexbuffers7Builder16FixedTypedVectorEPKcPKT_m'/>
<fun r='_ZN11flexbuffers7Builder3MapET_'/>
<fun r='_ZN11flexbuffers7Builder3MapET_RT0_'/>
<fun r='_ZN11flexbuffers7Builder3MapEPKcT_'/>
<fun r='_ZN11flexbuffers7Builder3MapEPKcT_RT0_'/>
<fun r='_ZN11flexbuffers7Builder3MapERKSt3mapINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEET_St4lessIS7_ESaISt4pairIKS7_S8_EEE'/>
<fun r='_ZN11flexbuffers7Builder9LastValueEv'/>
<fun r='_ZN11flexbuffers7Builder10ReuseValueENS0_5ValueE'/>
<fun r='_ZN11flexbuffers7Builder10ReuseValueEPKcNS0_5ValueE'/>
<fun r='_ZN11flexbuffers7Builder3AddEa'/>
<fun r='_ZN11flexbuffers7Builder3AddEs'/>
<fun r='_ZN11flexbuffers7Builder3AddEi'/>
<fun r='_ZN11flexbuffers7Builder3AddEl'/>
<fun r='_ZN11flexbuffers7Builder3AddEh'/>
<fun r='_ZN11flexbuffers7Builder3AddEt'/>
<fun r='_ZN11flexbuffers7Builder3AddEj'/>
<fun r='_ZN11flexbuffers7Builder3AddEm'/>
<fun r='_ZN11flexbuffers7Builder3AddEf'/>
<fun r='_ZN11flexbuffers7Builder3AddEd'/>
<fun r='_ZN11flexbuffers7Builder3AddEb'/>
<fun r='_ZN11flexbuffers7Builder3AddEPKc'/>
<fun r='_ZN11flexbuffers7Builder3AddERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE'/>
<fun r='_ZN11flexbuffers7Builder3AddERKNS_6StringE'/>
<fun r='_ZN11flexbuffers7Builder3AddERKSt6vectorIT_SaIS2_EE'/>
<fun r='_ZN11flexbuffers7Builder3AddEPKcRKT_'/>
<fun r='_ZN11flexbuffers7Builder3AddERKSt3mapINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEET_St4lessIS7_ESaISt4pairIKS7_S8_EEE'/>
<fun r='_ZN11flexbuffers7BuilderpLERKT_'/>
<fun r='_ZN11flexbuffers7Builder20ForceMinimumBitWidthENS_8BitWidthE'/>
<fun r='_ZN11flexbuffers7Builder6FinishEv'/>
<fun r='_ZNK11flexbuffers7Builder8FinishedEv'/>
<fun r='_ZN11flexbuffers7Builder5AlignENS_8BitWidthE'/>
<fun r='_ZN11flexbuffers7Builder10WriteBytesEPKvm'/>
<fun r='_ZN11flexbuffers7Builder5WriteET_m'/>
<fun r='_ZN11flexbuffers7Builder11WriteDoubleEdh'/>
<fun r='_ZN11flexbuffers7Builder11WriteOffsetEmh'/>
<fun r='_ZN11flexbuffers7Builder12PushIndirectET_NS_4TypeENS_8BitWidthE'/>
<fun r='_ZN11flexbuffers7Builder6WidthBEm'/>
<fun r='_ZN11flexbuffers7Builder13GetScalarTypeEv'/>
<fun r='_ZN11flexbuffers7Builder8WriteAnyERKNS0_5ValueEh'/>
<fun r='_ZN11flexbuffers7Builder10CreateBlobEPKvmmNS_4TypeE'/>
<fun r='_ZN11flexbuffers7Builder12ScalarVectorEPKT_mb'/>
<fun r='_ZN11flexbuffers7Builder12CreateVectorEmmmbbPKNS0_5ValueE'/>
<fun r='_ZN11flexbuffers7BuilderC1ERKS0_'/>
<fun r='_ZN11flexbuffers7BuilderaSERKS0_'/>
<mbr r='flexbuffers::Builder::buf_' o='0' t='std::vector&lt;uint8_t&gt;'/>
<mbr r='flexbuffers::Builder::stack_' o='192' t='std::vector&lt;Value&gt;'/>
<mbr r='flexbuffers::Builder::finished_' o='384' t='bool'/>
<mbr r='flexbuffers::Builder::flags_' o='416' t='flexbuffers::BuilderFlag'/>
<mbr r='flexbuffers::Builder::force_min_bit_width_' o='448' t='flexbuffers::BitWidth'/>
<mbr r='flexbuffers::Builder::key_pool' o='512' t='flexbuffers::Builder::KeyOffsetMap'/>
<mbr r='flexbuffers::Builder::string_pool' o='896' t='flexbuffers::Builder::StringOffsetMap'/>
<use f='halide/build-apps/flatbuffers/include/flatbuffers/idl.h' l='835' c='_ZN11flatbuffers6Parser15ParseFlexBufferEPKcS2_PN11flexbuffers7BuilderE'/>
<use f='halide/build-apps/flatbuffers/include/flatbuffers/idl.h' l='915' c='_ZN11flatbuffers6Parser20ParseFlexBufferValueEPN11flexbuffers7BuilderE'/>
<use f='halide/build-apps/flatbuffers/include/flatbuffers/idl.h' l='947'/>
<size>160</size>
<use f='halide/build-apps/flatbuffers/src/idl_parser.cpp' l='1097' c='_ZN11flatbuffers6Parser10ParseTableERKNS_9StructDefEPNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEPj'/>
<use f='halide/build-apps/flatbuffers/src/idl_parser.cpp' l='2740' c='_ZN11flatbuffers6Parser20ParseFlexBufferValueEPN11flexbuffers7BuilderE'/>
<use f='halide/build-apps/flatbuffers/src/idl_parser.cpp' l='2799' c='_ZN11flatbuffers6Parser15ParseFlexBufferEPKcS2_PN11flexbuffers7BuilderE'/>
<size>160</size>
