<dec f='halide/build-apps/gemmlowp/internal/block_params.h' l='162' type='0'/>
<use f='halide/build-apps/gemmlowp/internal/block_params.h' l='167' u='r' c='_ZN8gemmlowp18GetSideBlockParamsENS_4SideEPNS_15SideBlockParamsERKNS_11BlockParamsE'/>
<use f='halide/build-apps/gemmlowp/internal/block_params.h' l='169' u='r' c='_ZN8gemmlowp18GetSideBlockParamsENS_4SideEPNS_15SideBlockParamsERKNS_11BlockParamsE'/>
<use f='halide/build-apps/gemmlowp/internal/single_thread_gemm.h' l='115' u='r' c='_ZN8gemmlowp16SingleThreadGemmEPNS_23SingleThreadGemmContextERKNS_10KernelBaseERKNS_9MatrixMapIKT0_XT3_EEERKNS5_IS7_XT4_EEEPNS5_IT1_XT5_EEERKT6_RKT7_RKT8_'/>
<use f='halide/build-apps/gemmlowp/internal/multi_thread_gemm.h' l='496' u='r' c='_ZN8gemmlowp21GemmWithPackedRhsTask3RunEv'/>
