<dec f='halide/src/autoschedulers/adams2019/LoopNest.h' l='103' type='const Halide::Internal::Autoscheduler::LoopNest *'/>
<offset>0</offset>
<doc f='halide/src/autoschedulers/adams2019/LoopNest.h' l='103'>// Its containing compute_at site</doc>
<use f='halide/src/autoschedulers/adams2019/LoopNest.cpp' l='208' u='w' c='_ZNK6Halide8Internal13Autoscheduler8LoopNest9get_sitesER14PerfectHashMapINS1_11FunctionDAG4Node5StageENS2_5SitesELi4E22PerfectHashMapAsserterEPKS2_SC_'/>
<use f='halide/src/autoschedulers/adams2019/LoopNest.cpp' l='220' u='w' c='_ZNK6Halide8Internal13Autoscheduler8LoopNest9get_sitesER14PerfectHashMapINS1_11FunctionDAG4Node5StageENS2_5SitesELi4E22PerfectHashMapAsserterEPKS2_SC_'/>
<use f='halide/src/autoschedulers/adams2019/LoopNest.cpp' l='715' u='r' c='_ZNK6Halide8Internal13Autoscheduler8LoopNest16compute_featuresERKNS1_11FunctionDAGERKNS_13MachineParamsERK14PerfectHashMapINS3_4Node5StageENS2_5SitesE1864315'/>
<use f='halide/src/autoschedulers/adams2019/State.cpp' l='32' u='r' c='_ZN6Halide8Internal13Autoscheduler5State21compute_featurizationERKNS1_11FunctionDAGERKNS_13MachineParamsEP14PerfectHashMapINS3_4Node5StageENS0_16Sched11298370'/>
<use f='halide/src/autoschedulers/adams2019/State.cpp' l='33' u='w' c='_ZN6Halide8Internal13Autoscheduler5State21compute_featurizationERKNS1_11FunctionDAGERKNS_13MachineParamsEP14PerfectHashMapINS3_4Node5StageENS0_16Sched11298370'/>
<use f='halide/src/autoschedulers/adams2019/State.cpp' l='54' u='r' c='_ZN6Halide8Internal13Autoscheduler5State21compute_featurizationERKNS1_11FunctionDAGERKNS_13MachineParamsEP14PerfectHashMapINS3_4Node5StageENS0_16Sched11298370'/>
<use f='halide/src/autoschedulers/adams2019/State.cpp' l='73' u='w' c='_ZN6Halide8Internal13Autoscheduler5State21compute_featurizationERKNS1_11FunctionDAGERKNS_13MachineParamsEP14PerfectHashMapINS3_4Node5StageENS0_16Sched11298370'/>
