<dec f='halide/halide-install/include/Halide.h' l='3792' type='15'/>
<use f='halide/halide-install/include/Halide.h' l='12009'/>
<use f='halide/halide-install/include/Halide.h' l='12977' c='_ZN6Halide8Internal15VariadicVisitor13dispatch_exprEPKNS0_12BaseExprNodeEDpOTL0__'/>
<use f='halide/halide-install/include/Halide.h' l='13052' c='_ZN6Halide8Internal15VariadicVisitor13dispatch_stmtEPKNS0_12BaseStmtNodeEDpOTL0__'/>
<use f='halide/halide-install/include/Halide.h' l='27772' u='r' c='_ZN6Halide8Internal9IRMatcher11commutativeENS0_10IRNodeTypeE'/>
<dec f='halide/build/include/Halide.h' l='3792' type='15'/>
<use f='halide/build/include/Halide.h' l='12009'/>
<use f='halide/build/include/Halide.h' l='12977' c='_ZN6Halide8Internal15VariadicVisitor13dispatch_exprEPKNS0_12BaseExprNodeEDpOTL0__'/>
<use f='halide/build/include/Halide.h' l='13052' c='_ZN6Halide8Internal15VariadicVisitor13dispatch_stmtEPKNS0_12BaseStmtNodeEDpOTL0__'/>
<use f='halide/build/include/Halide.h' l='27772' u='r' c='_ZN6Halide8Internal9IRMatcher11commutativeENS0_10IRNodeTypeE'/>
<dec f='halide/src/Expr.h' l='45' type='15'/>
<use f='halide/src/IR.h' l='117'/>
<use f='halide/src/IRVisitor.h' l='195' c='_ZN6Halide8Internal15VariadicVisitor13dispatch_exprEPKNS0_12BaseExprNodeEDpOTL0__'/>
<use f='halide/src/IRVisitor.h' l='270' c='_ZN6Halide8Internal15VariadicVisitor13dispatch_stmtEPKNS0_12BaseStmtNodeEDpOTL0__'/>
<use f='halide/src/IRMatch.h' l='658' u='r' c='_ZN6Halide8Internal9IRMatcher11commutativeENS0_10IRNodeTypeE'/>
<use f='halide/src/IRMatch.cpp' l='453' c='_ZN6Halide8Internal9IRMatcher12equal_helperERKNS0_12BaseExprNodeES4_'/>
