<dec f='halide/src/autoschedulers/adams2019/Timer.h' l='19' type='std::string'/>
<use f='halide/src/autoschedulers/adams2019/Timer.h' l='22' u='w' c='_ZN6Halide8Internal13Autoscheduler11ScopedTimerC1ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE'/>
<use f='halide/src/autoschedulers/adams2019/Timer.h' l='29' u='a' c='_ZN6Halide8Internal13Autoscheduler11ScopedTimerD1Ev'/>
<offset>64</offset>
