<def f='halide/halide-install/include/Halide.h' l='5051' ll='5127'/>
<use f='halide/halide-install/include/Halide.h' l='5129' c='_ZN6Halide6TargetC1ENS0_2OSENS0_4ArchEiRKSt6vectorINS0_7FeatureESaIS4_EE'/>
<use f='halide/halide-install/include/Halide.h' l='5129' c='_ZN6Halide6TargetC1ENS0_2OSENS0_4ArchEiRKSt6vectorINS0_7FeatureESaIS4_EE'/>
<use f='halide/halide-install/include/Halide.h' l='5158' c='_ZN6Halide6Target11set_featureENS0_7FeatureEb'/>
<use f='halide/halide-install/include/Halide.h' l='5160' c='_ZN6Halide6Target12set_featuresERKSt6vectorINS0_7FeatureESaIS2_EEb'/>
<use f='halide/halide-install/include/Halide.h' l='5162' c='_ZNK6Halide6Target11has_featureENS0_7FeatureE'/>
<use f='halide/halide-install/include/Halide.h' l='5165' c='_ZNK6Halide6Target11has_featureE23halide_target_feature_t'/>
<use f='halide/halide-install/include/Halide.h' l='5168' c='_ZNK6Halide6Target15features_any_ofERKSt6vectorINS0_7FeatureESaIS2_EE'/>
<use f='halide/halide-install/include/Halide.h' l='5170' c='_ZNK6Halide6Target15features_all_ofERKSt6vectorINS0_7FeatureESaIS2_EE'/>
<use f='halide/halide-install/include/Halide.h' l='5176' c='_ZNK6Halide6Target12with_featureENS0_7FeatureE'/>
<use f='halide/halide-install/include/Halide.h' l='5182' c='_ZNK6Halide6Target15without_featureENS0_7FeatureE'/>
<use f='halide/halide-install/include/Halide.h' l='5294' c='_ZN6Halide6Target15feature_to_nameB5cxx11ENS0_7FeatureE'/>
<use f='halide/halide-install/include/Halide.h' l='5299' c='_ZN6Halide6Target17feature_from_nameERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE'/>
<use f='halide/halide-install/include/Halide.h' l='5323' c='_ZN6Halide29target_feature_for_device_apiENS_9DeviceAPIE'/>
<doc f='halide/halide-install/include/Halide.h' l='5047'>/** Optional features a target can have.
     * Corresponds to feature_name_map in Target.cpp.
     * See definitions in HalideRuntime.h for full information.
     */</doc>
<def f='halide/build/include/Halide.h' l='5051' ll='5127'/>
<use f='halide/build/include/Halide.h' l='5129' c='_ZN6Halide6TargetC1ENS0_2OSENS0_4ArchEiRKSt6vectorINS0_7FeatureESaIS4_EE'/>
<use f='halide/build/include/Halide.h' l='5129' c='_ZN6Halide6TargetC1ENS0_2OSENS0_4ArchEiRKSt6vectorINS0_7FeatureESaIS4_EE'/>
<use f='halide/build/include/Halide.h' l='5158' c='_ZN6Halide6Target11set_featureENS0_7FeatureEb'/>
<use f='halide/build/include/Halide.h' l='5160' c='_ZN6Halide6Target12set_featuresERKSt6vectorINS0_7FeatureESaIS2_EEb'/>
<use f='halide/build/include/Halide.h' l='5162' c='_ZNK6Halide6Target11has_featureENS0_7FeatureE'/>
<use f='halide/build/include/Halide.h' l='5165' c='_ZNK6Halide6Target11has_featureE23halide_target_feature_t'/>
<use f='halide/build/include/Halide.h' l='5168' c='_ZNK6Halide6Target15features_any_ofERKSt6vectorINS0_7FeatureESaIS2_EE'/>
<use f='halide/build/include/Halide.h' l='5170' c='_ZNK6Halide6Target15features_all_ofERKSt6vectorINS0_7FeatureESaIS2_EE'/>
<use f='halide/build/include/Halide.h' l='5176' c='_ZNK6Halide6Target12with_featureENS0_7FeatureE'/>
<use f='halide/build/include/Halide.h' l='5182' c='_ZNK6Halide6Target15without_featureENS0_7FeatureE'/>
<use f='halide/build/include/Halide.h' l='5294' c='_ZN6Halide6Target15feature_to_nameB5cxx11ENS0_7FeatureE'/>
<use f='halide/build/include/Halide.h' l='5299' c='_ZN6Halide6Target17feature_from_nameERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE'/>
<use f='halide/build/include/Halide.h' l='5323' c='_ZN6Halide29target_feature_for_device_apiENS_9DeviceAPIE'/>
<doc f='halide/build/include/Halide.h' l='5047'>/** Optional features a target can have.
     * Corresponds to feature_name_map in Target.cpp.
     * See definitions in HalideRuntime.h for full information.
     */</doc>
<use f='halide/python_bindings/src/PyEnums.cpp' l='84' c='_ZN6Halide14PythonBindings12define_enumsERN8pybind117module_E'/>
<use f='halide/python_bindings/src/PyTarget.cpp' l='27' c='_ZN6Halide14PythonBindings13define_targetERN8pybind117module_E'/>
<use f='halide/python_bindings/src/PyTarget.cpp' l='40' c='_ZN6Halide14PythonBindings13define_targetERN8pybind117module_E'/>
<def f='halide/src/Target.h' l='57' ll='133'/>
<use f='halide/src/Target.h' l='135' c='_ZN6Halide6TargetC1ENS0_2OSENS0_4ArchEiRKSt6vectorINS0_7FeatureESaIS4_EE'/>
<use f='halide/src/Target.h' l='135' c='_ZN6Halide6TargetC1ENS0_2OSENS0_4ArchEiRKSt6vectorINS0_7FeatureESaIS4_EE'/>
<use f='halide/src/Target.h' l='164' c='_ZN6Halide6Target11set_featureENS0_7FeatureEb'/>
<use f='halide/src/Target.h' l='166' c='_ZN6Halide6Target12set_featuresERKSt6vectorINS0_7FeatureESaIS2_EEb'/>
<use f='halide/src/Target.h' l='168' c='_ZNK6Halide6Target11has_featureENS0_7FeatureE'/>
<use f='halide/src/Target.h' l='171' c='_ZNK6Halide6Target11has_featureE23halide_target_feature_t'/>
<use f='halide/src/Target.h' l='174' c='_ZNK6Halide6Target15features_any_ofERKSt6vectorINS0_7FeatureESaIS2_EE'/>
<use f='halide/src/Target.h' l='176' c='_ZNK6Halide6Target15features_all_ofERKSt6vectorINS0_7FeatureESaIS2_EE'/>
<use f='halide/src/Target.h' l='182' c='_ZNK6Halide6Target12with_featureENS0_7FeatureE'/>
<use f='halide/src/Target.h' l='188' c='_ZNK6Halide6Target15without_featureENS0_7FeatureE'/>
<use f='halide/src/Target.h' l='300' c='_ZN6Halide6Target15feature_to_nameB5cxx11ENS0_7FeatureE'/>
<use f='halide/src/Target.h' l='305' c='_ZN6Halide6Target17feature_from_nameERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE'/>
<use f='halide/src/Target.h' l='329' c='_ZN6Halide29target_feature_for_device_apiENS_9DeviceAPIE'/>
<doc f='halide/src/Target.h' l='53'>/** Optional features a target can have.
     * Corresponds to feature_name_map in Target.cpp.
     * See definitions in HalideRuntime.h for full information.
     */</doc>
<use f='halide/src/CodeGen_ARM.cpp' l='1145' c='_ZN6Halide8Internal12_GLOBAL__N_111CodeGen_ARM21codegen_vector_reduceEPKNS0_12VectorReduceERKNS_4ExprE'/>
<use f='halide/src/CodeGen_PowerPC.cpp' l='50'/>
<use f='halide/src/CodeGen_WebAssembly.cpp' l='53'/>
<use f='halide/src/CodeGen_X86.cpp' l='97'/>
<use f='halide/src/HexagonOffload.cpp' l='973' c='_ZN6Halide8Internal18inject_hexagon_rpcENS0_4StmtERKNS_6TargetERNS_6ModuleE'/>
<use f='halide/src/HexagonOffload.cpp' l='982' c='_ZN6Halide8Internal18inject_hexagon_rpcENS0_4StmtERKNS_6TargetERNS_6ModuleE'/>
<use f='halide/src/Module.cpp' l='287' c='_ZN6Halide8Internal12_GLOBAL__N_118emit_schedule_fileERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKSt6vectorINS_6TargetESaISB_EES9_S9_S9_RSo'/>
<use f='halide/src/Module.cpp' l='842' c='_ZN6Halide19compile_multitargetERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKSt3mapINS_6OutputES5_St4lessIS9_ESaISt4pairIKS9_S5_EEERKSt6vec11731248'/>
<use f='halide/src/Module.cpp' l='897' c='_ZN6Halide19compile_multitargetERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKSt3mapINS_6OutputES5_St4lessIS9_ESaISt4pairIKS9_S5_EEERKSt6vec11731248'/>
<use f='halide/src/Module.cpp' l='936' c='_ZN6Halide19compile_multitargetERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKSt3mapINS_6OutputES5_St4lessIS9_ESaISt4pairIKS9_S5_EEERKSt6vec11731248'/>
<use f='halide/src/Module.cpp' l='1042' c='_ZN6Halide19compile_multitargetERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKSt3mapINS_6OutputES5_St4lessIS9_ESaISt4pairIKS9_S5_EEERKSt6vec11731248'/>
<use f='halide/src/Target.cpp' l='79' c='_ZN6Halide12_GLOBAL__N_121calculate_host_targetEv'/>
<use f='halide/src/Target.cpp' l='237' c='_ZN6Halide12_GLOBAL__N_130calculate_host_cuda_capabilityENS_6TargetE'/>
<use f='halide/src/Target.cpp' l='265' c='_ZN6Halide12_GLOBAL__N_124get_host_cuda_capabilityENS_6TargetE'/>
<use f='halide/src/Target.cpp' l='266' c='_ZN6Halide12_GLOBAL__N_124get_host_cuda_capabilityENS_6TargetE'/>
<use f='halide/src/Target.cpp' l='311'/>
<use f='halide/src/Target.cpp' l='389' c='_ZN6Halide12_GLOBAL__N_114lookup_featureERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERNS_6Target7FeatureE'/>
<use f='halide/src/Target.cpp' l='454' c='_ZN6Halide12_GLOBAL__N_112merge_stringERNS_6TargetERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE'/>
<use f='halide/src/Target.cpp' l='589' c='_ZN6Halide6Target15feature_to_nameB5cxx11ENS0_7FeatureE'/>
<use f='halide/src/Target.cpp' l='599' c='_ZN6Halide6Target17feature_from_nameERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE'/>
<use f='halide/src/Target.cpp' l='600' c='_ZN6Halide6Target17feature_from_nameERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE'/>
<use f='halide/src/Target.cpp' l='684' c='_ZN6Halide6Target11set_featureENS0_7FeatureEb'/>
<use f='halide/src/Target.cpp' l='692' c='_ZN6Halide6Target12set_featuresERKSt6vectorINS0_7FeatureESaIS2_EEb'/>
<use f='halide/src/Target.cpp' l='693' c='_ZN6Halide6Target12set_featuresERKSt6vectorINS0_7FeatureESaIS2_EEb'/>
<use f='halide/src/Target.cpp' l='698' c='_ZNK6Halide6Target11has_featureENS0_7FeatureE'/>
<use f='halide/src/Target.cpp' l='706' c='_ZNK6Halide6Target15features_any_ofERKSt6vectorINS0_7FeatureESaIS2_EE'/>
<use f='halide/src/Target.cpp' l='707' c='_ZNK6Halide6Target15features_any_ofERKSt6vectorINS0_7FeatureESaIS2_EE'/>
<use f='halide/src/Target.cpp' l='715' c='_ZNK6Halide6Target15features_all_ofERKSt6vectorINS0_7FeatureESaIS2_EE'/>
<use f='halide/src/Target.cpp' l='716' c='_ZNK6Halide6Target15features_all_ofERKSt6vectorINS0_7FeatureESaIS2_EE'/>
<use f='halide/src/Target.cpp' l='724' c='_ZNK6Halide6Target12with_featureENS0_7FeatureE'/>
<use f='halide/src/Target.cpp' l='730' c='_ZNK6Halide6Target15without_featureENS0_7FeatureE'/>
<use f='halide/src/Target.cpp' l='863' c='_ZN6Halide29target_feature_for_device_apiENS_9DeviceAPIE'/>
<use f='halide/src/Target.cpp' l='944' c='_ZN6Halide6Target29get_runtime_compatible_targetERKS0_RS0_'/>
<use f='halide/src/Target.cpp' l='970' c='_ZN6Halide6Target29get_runtime_compatible_targetERKS0_RS0_'/>
<use f='halide/src/Target.cpp' l='989' c='_ZN6Halide6Target29get_runtime_compatible_targetERKS0_RS0_'/>
<use f='halide/src/Target.cpp' l='1105' c='_ZN6Halide8Internal11target_testEv'/>
<use f='halide/tutorial/lesson_11_cross_compilation.cpp' l='59' c='main'/>
<use f='halide/tutorial/lesson_11_cross_compilation.cpp' l='68' c='main'/>
<use f='halide/tutorial/lesson_11_cross_compilation.cpp' l='83' c='main'/>
<use f='halide/tutorial/lesson_12_using_the_gpu.cpp' l='290' c='_Z15find_gpu_targetv'/>
<use f='halide/tutorial/lesson_12_using_the_gpu.cpp' l='308' c='_Z15find_gpu_targetv'/>
