<dec f='halide/halide-install/include/Halide.h' l='15675' type='Halide::RVar'/>
<use f='halide/apps/bgu/bgu_generator.cpp' l='305' u='m' c='_ZN12_GLOBAL__N_13BGU8generateEv'/>
<use f='halide/apps/bgu/bgu_generator.cpp' l='539' u='r' c='_ZN12_GLOBAL__N_13BGU8generateEv'/>
<use f='halide/apps/bgu/bgu_generator.cpp' l='618' u='r' c='_ZN12_GLOBAL__N_13BGU8generateEv'/>
<use f='halide/apps/bgu/bgu_generator.cpp' l='626' u='r' c='_ZN12_GLOBAL__N_13BGU8generateEv'/>
<use f='halide/apps/bgu/bgu_generator.cpp' l='633' u='r' c='_ZN12_GLOBAL__N_13BGU8generateEv'/>
<use f='halide/apps/bgu/bgu_generator.cpp' l='636' u='r' c='_ZN12_GLOBAL__N_13BGU8generateEv'/>
<use f='halide/apps/bgu/bgu_generator.cpp' l='639' u='r' c='_ZN12_GLOBAL__N_13BGU8generateEv'/>
<offset>64</offset>
<use f='halide/apps/bilateral_grid/bilateral_grid_generator.cpp' l='23' u='m' c='_ZN12_GLOBAL__N_113BilateralGrid8generateEv'/>
<use f='halide/apps/bilateral_grid/bilateral_grid_generator.cpp' l='103' u='r' c='_ZN12_GLOBAL__N_113BilateralGrid8generateEv'/>
<use f='halide/apps/bilateral_grid/bilateral_grid_generator.cpp' l='139' u='r' c='_ZN12_GLOBAL__N_113BilateralGrid8generateEv'/>
<use f='halide/apps/conv_layer/conv_layer_generator.cpp' l='26' u='a' c='_ZN12_GLOBAL__N_116ConvolutionLayer8generateEv'/>
<use f='halide/apps/conv_layer/conv_layer_generator.cpp' l='26' u='a' c='_ZN12_GLOBAL__N_116ConvolutionLayer8generateEv'/>
<use f='halide/apps/conv_layer/conv_layer_generator.cpp' l='103' u='r' c='_ZN12_GLOBAL__N_116ConvolutionLayer8generateEv'/>
<use f='halide/apps/conv_layer/conv_layer_generator.cpp' l='188' u='a' c='_ZN12_GLOBAL__N_116ConvolutionLayer8generateEv'/>
<use f='halide/apps/conv_layer/conv_layer_generator.cpp' l='193' u='r' c='_ZN12_GLOBAL__N_116ConvolutionLayer8generateEv'/>
<use f='halide/apps/conv_layer/conv_layer_generator.cpp' l='195' u='r' c='_ZN12_GLOBAL__N_116ConvolutionLayer8generateEv'/>
<use f='halide/apps/fft/fft.cpp' l='361' u='r' c='_ZN12_GLOBAL__N_18fft_dim1E5FuncTI11ComplexExprERKSt6vectorIiSaIiEEiiN6Halide4ExprEbRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKNS8_6Targe14237183'/>
<use f='halide/apps/hannk/halide/conv_generator.cpp' l='105' u='a' c='_ZN5hannk4Conv8generateEv'/>
<use f='halide/apps/hannk/halide/conv_generator.cpp' l='107' u='m' c='_ZN5hannk4Conv8generateEv'/>
<use f='halide/apps/hannk/halide/conv_generator.cpp' l='239' u='a' c='_ZN5hannk4Conv8generateEv'/>
<use f='halide/apps/hannk/halide/conv_generator.cpp' l='286' u='a' c='_ZN5hannk4Conv8generateEv'/>
<use f='halide/apps/hannk/halide/conv_generator.cpp' l='299' u='a' c='_ZN5hannk4Conv8generateEv'/>
<use f='halide/apps/hannk/halide/depthwise_conv_generator.cpp' l='67' u='a' c='_ZN5hannk13DepthwiseConv8generateEv'/>
<use f='halide/apps/hannk/halide/depthwise_conv_generator.cpp' l='91' u='m' c='_ZN5hannk13DepthwiseConv8generateEv'/>
<use f='halide/apps/hannk/halide/depthwise_conv_generator.cpp' l='180' u='a' c='_ZN5hannk13DepthwiseConv8generateEv'/>
<use f='halide/apps/hannk/halide/depthwise_conv_generator.cpp' l='186' u='r' c='_ZN5hannk13DepthwiseConv8generateEv'/>
<use f='halide/apps/hannk/halide/elementwise_generator.cpp' l='161' u='m' c='_ZN5hannk11Elementwise5buildEv'/>
<use f='halide/apps/hannk/halide/elementwise_generator.cpp' l='162' u='m' c='_ZN5hannk11Elementwise5buildEv'/>
<use f='halide/apps/hannk/halide/elementwise_generator.cpp' l='207' u='r' c='_ZN5hannk11Elementwise5buildEv'/>
<use f='halide/apps/hannk/halide/pool_generator.cpp' l='46' u='m' c='_ZN5hannk11AveragePool8generateEv'/>
<use f='halide/apps/hannk/halide/pool_generator.cpp' l='129' u='m' c='_ZN5hannk7MaxPool8generateEv'/>
<use f='halide/apps/hannk/halide/reductions_generator.cpp' l='34' u='m' c='_ZN5hannk4Mean8generateEv'/>
<use f='halide/apps/hannk/halide/reductions_generator.cpp' l='47' u='a' c='_ZN5hannk4Mean8generateEv'/>
<use f='halide/apps/hist/hist_generator.cpp' l='43' u='m' c='_ZN12_GLOBAL__N_14Hist8generateEv'/>
<use f='halide/apps/hist/hist_generator.cpp' l='43' u='m' c='_ZN12_GLOBAL__N_14Hist8generateEv'/>
<use f='halide/apps/hist/hist_generator.cpp' l='43' u='m' c='_ZN12_GLOBAL__N_14Hist8generateEv'/>
<use f='halide/apps/max_filter/max_filter_generator.cpp' l='30' u='a' c='_ZN12_GLOBAL__N_13Max8generateEv'/>
<use f='halide/apps/max_filter/max_filter_generator.cpp' l='30' u='a' c='_ZN12_GLOBAL__N_13Max8generateEv'/>
<use f='halide/apps/max_filter/max_filter_generator.cpp' l='31' u='m' c='_ZN12_GLOBAL__N_13Max8generateEv'/>
<use f='halide/apps/max_filter/max_filter_generator.cpp' l='85' u='r' c='_ZN12_GLOBAL__N_13Max8generateEv'/>
<use f='halide/apps/max_filter/max_filter_generator.cpp' l='110' u='r' c='_ZN12_GLOBAL__N_13Max8generateEv'/>
<use f='halide/apps/nl_means/nl_means_generator.cpp' l='60' u='a' c='_ZN12_GLOBAL__N_113NonLocalMeans8generateEv'/>
<use f='halide/apps/nl_means/nl_means_generator.cpp' l='60' u='m' c='_ZN12_GLOBAL__N_113NonLocalMeans8generateEv'/>
<use f='halide/apps/nl_means/nl_means_generator.cpp' l='104' u='r' c='_ZN12_GLOBAL__N_113NonLocalMeans8generateEv'/>
<use f='halide/apps/nl_means/nl_means_generator.cpp' l='149' u='a' c='_ZN12_GLOBAL__N_113NonLocalMeans8generateEv'/>
<dec f='halide/build/include/Halide.h' l='15675' type='Halide::RVar'/>
<offset>64</offset>
<use f='halide/python_bindings/src/PyRDom.cpp' l='49' u='a' c='_ZN6Halide14PythonBindings11define_rdomERN8pybind117module_E'/>
<dec f='halide/src/RDom.h' l='337' type='Halide::RVar'/>
<offset>64</offset>
<use f='halide/src/Bounds.cpp' l='3062' u='m' c='_ZN6Halide8Internal12_GLOBAL__N_119constant_bound_testEv'/>
<use f='halide/src/Bounds.cpp' l='3066' u='m' c='_ZN6Halide8Internal12_GLOBAL__N_119constant_bound_testEv'/>
<use f='halide/src/DerivativeUtils.cpp' l='392' u='m' c='_ZN6Halide8Internal13solve_inverseENS_4ExprERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES9_'/>
<use f='halide/src/DerivativeUtils.cpp' l='395' u='m' c='_ZN6Halide8Internal13solve_inverseENS_4ExprERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES9_'/>
<use f='halide/src/Generator.cpp' l='2324' u='m' c='_ZN6Halide8Internal14generator_testEv'/>
<use f='halide/src/Generator.cpp' l='2324' u='m' c='_ZN6Halide8Internal14generator_testEv'/>
<use f='halide/src/Generator.cpp' l='2325' u='r' c='_ZN6Halide8Internal14generator_testEv'/>
<use f='halide/src/InlineReductions.cpp' l='83' u='m' c='_ZN6Halide8Internal12_GLOBAL__N_112FindFreeVars5visitEPKNS0_8VariableE'/>
<use f='halide/src/RDom.cpp' l='79' u='a' c='_ZN6Halide4RDom9init_varsERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE'/>
<use f='halide/src/RDom.cpp' l='203' u='r' c='_ZNK6Halide4RDomixEi'/>
<use f='halide/src/RDom.cpp' l='215' u='r' c='_ZNK6Halide4RDomixEi'/>
<use f='halide/src/RDom.cpp' l='226' u='m' c='_ZNK6Halide4RDomcvNS_4ExprEEv'/>
<use f='halide/src/RDom.cpp' l='235' u='r' c='_ZNK6Halide4RDomcvNS_4RVarEEv'/>
<use f='halide/src/autoschedulers/adams2019/cost_model_generator.cpp' l='210' u='a' c='_ZN9CostModel8generateEv'/>
<use f='halide/src/autoschedulers/adams2019/cost_model_generator.cpp' l='211' u='a' c='_ZN9CostModel8generateEv'/>
<use f='halide/src/autoschedulers/adams2019/cost_model_generator.cpp' l='229' c='_ZN9CostModel8generateEv'/>
<use f='halide/src/autoschedulers/adams2019/cost_model_generator.cpp' l='229' u='m' c='_ZN9CostModel8generateEv'/>
<use f='halide/src/autoschedulers/adams2019/cost_model_generator.cpp' l='235' c='_ZN9CostModel8generateEv'/>
<use f='halide/src/autoschedulers/adams2019/cost_model_generator.cpp' l='235' u='m' c='_ZN9CostModel8generateEv'/>
<use f='halide/src/autoschedulers/adams2019/cost_model_generator.cpp' l='424' u='m' c='_ZN9CostModel8generateEv'/>
<use f='halide/src/autoschedulers/adams2019/cost_model_generator.cpp' l='553' c='_ZN9CostModel8generateEv'/>
<use f='halide/src/autoschedulers/adams2019/cost_model_generator.cpp' l='554' c='_ZN9CostModel8generateEv'/>
<use f='halide/src/autoschedulers/adams2019/demo_generator.cpp' l='22' u='a' c='_ZN12_GLOBAL__N_18ConvRelu8generateEv'/>
<use f='halide/src/autoschedulers/adams2019/demo_generator.cpp' l='22' u='a' c='_ZN12_GLOBAL__N_18ConvRelu8generateEv'/>
<use f='halide/src/autoschedulers/adams2019/included_schedule_file_generator.cpp' l='30' u='a' c='_ZN12_GLOBAL__N_120IncludedScheduleFile8generateEv'/>
<use f='halide/src/autoschedulers/adams2019/included_schedule_file_generator.cpp' l='30' u='a' c='_ZN12_GLOBAL__N_120IncludedScheduleFile8generateEv'/>
<use f='halide/src/autoschedulers/adams2019/test.cpp' l='519' u='m' c='main'/>
<use f='halide/src/autoschedulers/adams2019/test.cpp' l='550' u='m' c='main'/>
<use f='halide/src/autoschedulers/adams2019/test.cpp' l='551' u='m' c='main'/>
<use f='halide/src/autoschedulers/adams2019/test.cpp' l='864' u='m' c='main'/>
<use f='halide/src/autoschedulers/li2018/demo_generator.cpp' l='22' u='a' c='_ZN12_GLOBAL__N_18ConvRelu8generateEv'/>
<use f='halide/src/autoschedulers/li2018/demo_generator.cpp' l='22' u='a' c='_ZN12_GLOBAL__N_18ConvRelu8generateEv'/>
<use f='halide/src/autoschedulers/li2018/test.cpp' l='75' u='m' c='main'/>
<use f='halide/src/autoschedulers/li2018/test.cpp' l='108' u='m' c='main'/>
<use f='halide/src/autoschedulers/li2018/test.cpp' l='124' u='m' c='main'/>
<use f='halide/test/generator/rdom_input_generator.cpp' l='19' u='a' c='_ZN12_GLOBAL__N_19RDomInput8generateEv'/>
<use f='halide/test/generator/rdom_input_generator.cpp' l='19' u='a' c='_ZN12_GLOBAL__N_19RDomInput8generateEv'/>
<use f='halide/tutorial/lesson_09_update_definitions.cpp' l='206' u='m' c='main'/>
<use f='halide/tutorial/lesson_09_update_definitions.cpp' l='655' u='m' c='main'/>
<use f='halide/tutorial/lesson_09_update_definitions.cpp' l='769' u='m' c='main'/>
<use f='halide/tutorial/lesson_09_update_definitions.cpp' l='770' u='m' c='main'/>
<use f='halide/tutorial/lesson_17_predicated_rdom.cpp' l='58' u='m' c='main'/>
<use f='halide/tutorial/lesson_17_predicated_rdom.cpp' l='58' u='m' c='main'/>
<use f='halide/tutorial/lesson_17_predicated_rdom.cpp' l='61' u='m' c='main'/>
<use f='halide/tutorial/lesson_17_predicated_rdom.cpp' l='109' u='m' c='main'/>
<use f='halide/tutorial/lesson_17_predicated_rdom.cpp' l='110' u='m' c='main'/>
<use f='halide/tutorial/lesson_17_predicated_rdom.cpp' l='111' u='m' c='main'/>
<use f='halide/tutorial/lesson_17_predicated_rdom.cpp' l='117' u='m' c='main'/>
<use f='halide/tutorial/lesson_17_predicated_rdom.cpp' l='164' u='m' c='main'/>
<use f='halide/tutorial/lesson_17_predicated_rdom.cpp' l='165' u='m' c='main'/>
<use f='halide/tutorial/lesson_17_predicated_rdom.cpp' l='166' u='m' c='main'/>
<use f='halide/tutorial/lesson_17_predicated_rdom.cpp' l='172' u='m' c='main'/>
<use f='halide/tutorial/lesson_17_predicated_rdom.cpp' l='173' u='m' c='main'/>
<use f='halide/tutorial/lesson_18_parallel_associative_reductions.cpp' l='46' u='m' c='main'/>
<use f='halide/tutorial/lesson_18_parallel_associative_reductions.cpp' l='120' u='m' c='main'/>
<use f='halide/tutorial/lesson_18_parallel_associative_reductions.cpp' l='205' u='m' c='main'/>
<use f='halide/tutorial/lesson_18_parallel_associative_reductions.cpp' l='209' u='r' c='main'/>
<use f='halide/tutorial/lesson_18_parallel_associative_reductions.cpp' l='273' u='m' c='main'/>
<use f='halide/tutorial/lesson_18_parallel_associative_reductions.cpp' l='279' u='r' c='main'/>
