<dec f='halide/llvm-install/include/llvm/Analysis/AliasAnalysis.h' l='123' type='6'/>
<use f='halide/llvm-install/include/llvm/Analysis/AliasAnalysis.h' l='125' u='r'/>
<use f='halide/llvm-install/include/llvm/Analysis/AliasAnalysis.h' l='183' u='r' c='_ZN4llvm8clearRefENS_10ModRefInfoE'/>
<use f='halide/llvm-install/include/llvm/Analysis/AliasAnalysis.h' l='244' u='r'/>
<use f='halide/llvm-install/include/llvm/Analysis/AliasAnalysis.h' l='266' u='r'/>
<use f='halide/llvm-install/include/llvm/Analysis/AliasAnalysis.h' l='295' u='r'/>
<use f='halide/llvm-install/include/llvm/Analysis/AliasAnalysis.h' l='321' u='r'/>
<doc f='halide/llvm-install/include/llvm/Analysis/AliasAnalysis.h' l='122'>/// The access may modify the value stored in memory.</doc>
