<use f='halide/halide-install/include/Halide.h' l='13389' c='_ZN6Halide8Internal9JITModule14compile_moduleESt10unique_ptrIN4llvm6ModuleESt14default_deleteIS4_EERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIc1691512'/>
<use f='halide/halide-install/include/Halide.h' l='13430' c='_ZN6Halide8Internal16JITSharedRuntime3getEPN4llvm6ModuleERKNS_6TargetEb'/>
<use f='halide/halide-install/include/Halide.h' l='19723' c='_ZN6Halide8Internal18get_target_optionsERKN4llvm6ModuleERNS1_13TargetOptionsERNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESD_'/>
<use f='halide/halide-install/include/Halide.h' l='19726' c='_ZN6Halide8Internal20clone_target_optionsERKN4llvm6ModuleERS2_'/>
<use f='halide/halide-install/include/Halide.h' l='19726' c='_ZN6Halide8Internal20clone_target_optionsERKN4llvm6ModuleERS2_'/>
<use f='halide/halide-install/include/Halide.h' l='19729' c='_ZN6Halide8Internal19make_target_machineERKN4llvm6ModuleE'/>
<use f='halide/halide-install/include/Halide.h' l='19738' c='_ZN6Halide8Internal13embed_bitcodeEPN4llvm6ModuleERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE'/>
<use f='halide/halide-install/include/Halide.h' l='19804' c='_ZN6Halide8Internal12CodeGen_LLVM7compileERKNS_6ModuleE'/>
<use f='halide/halide-install/include/Halide.h' l='19817' c='_ZN6Halide8Internal12CodeGen_LLVM19compile_trampolinesERKNS_6TargetERN4llvm11LLVMContextERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKSt6ve2948072'/>
<use f='halide/halide-install/include/Halide.h' l='19880'/>
<use f='halide/halide-install/include/Halide.h' l='20305' c='_ZN6Halide8Internal12CodeGen_LLVM14finish_codegenEv'/>
<use f='halide/halide-install/include/Halide.h' l='20315' c='_ZN6Halide12codegen_llvmERKNS_6ModuleERN4llvm11LLVMContextE'/>
<use f='halide/halide-install/include/Halide.h' l='30180' c='_ZN6Halide29compile_module_to_llvm_moduleERKNS_6ModuleERN4llvm11LLVMContextE'/>
<use f='halide/halide-install/include/Halide.h' l='30187' c='_ZN6Halide29compile_llvm_module_to_objectERN4llvm6ModuleERNS0_17raw_pwrite_streamE'/>
<use f='halide/halide-install/include/Halide.h' l='30188' c='_ZN6Halide31compile_llvm_module_to_assemblyERN4llvm6ModuleERNS0_17raw_pwrite_streamE'/>
<use f='halide/halide-install/include/Halide.h' l='30193' c='_ZN6Halide35compile_llvm_module_to_llvm_bitcodeERN4llvm6ModuleERNS0_17raw_pwrite_streamE'/>
<use f='halide/halide-install/include/Halide.h' l='30194' c='_ZN6Halide36compile_llvm_module_to_llvm_assemblyERN4llvm6ModuleERNS0_17raw_pwrite_streamE'/>
<use f='halide/halide-install/include/Halide.h' l='30236' c='_ZN6Halide8Internal29get_initial_module_for_targetENS_6TargetEPN4llvm11LLVMContextEbb'/>
<use f='halide/halide-install/include/Halide.h' l='30239' c='_ZN6Halide8Internal33get_initial_module_for_ptx_deviceENS_6TargetEPN4llvm11LLVMContextE'/>
<use f='halide/halide-install/include/Halide.h' l='30242' c='_ZN6Halide8Internal21add_bitcode_to_moduleEPN4llvm11LLVMContextERNS1_6ModuleERKSt6vectorIhSaIhEERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE'/>
<use f='halide/halide-install/include/Halide.h' l='30247' c='_ZN6Halide8Internal26link_with_wasm_jit_runtimeEPN4llvm11LLVMContextERKNS_6TargetESt10unique_ptrINS1_6ModuleESt14default_deleteIS8_EE'/>
<use f='halide/halide-install/include/Halide.h' l='30248' c='_ZN6Halide8Internal26link_with_wasm_jit_runtimeEPN4llvm11LLVMContextERKNS_6TargetESt10unique_ptrINS1_6ModuleESt14default_deleteIS8_EE'/>
<use f='halide/halide-install/include/Halide.h' l='30441' c='_ZN6Halide8Internal21define_matlab_wrapperEPN4llvm6ModuleEPNS1_8FunctionES5_'/>
<use f='halide/build/include/Halide.h' l='13389' c='_ZN6Halide8Internal9JITModule14compile_moduleESt10unique_ptrIN4llvm6ModuleESt14default_deleteIS4_EERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIc1691512'/>
<use f='halide/build/include/Halide.h' l='13430' c='_ZN6Halide8Internal16JITSharedRuntime3getEPN4llvm6ModuleERKNS_6TargetEb'/>
<use f='halide/build/include/Halide.h' l='19723' c='_ZN6Halide8Internal18get_target_optionsERKN4llvm6ModuleERNS1_13TargetOptionsERNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESD_'/>
<use f='halide/build/include/Halide.h' l='19726' c='_ZN6Halide8Internal20clone_target_optionsERKN4llvm6ModuleERS2_'/>
<use f='halide/build/include/Halide.h' l='19726' c='_ZN6Halide8Internal20clone_target_optionsERKN4llvm6ModuleERS2_'/>
<use f='halide/build/include/Halide.h' l='19729' c='_ZN6Halide8Internal19make_target_machineERKN4llvm6ModuleE'/>
<use f='halide/build/include/Halide.h' l='19738' c='_ZN6Halide8Internal13embed_bitcodeEPN4llvm6ModuleERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE'/>
<use f='halide/build/include/Halide.h' l='19804' c='_ZN6Halide8Internal12CodeGen_LLVM7compileERKNS_6ModuleE'/>
<use f='halide/build/include/Halide.h' l='19817' c='_ZN6Halide8Internal12CodeGen_LLVM19compile_trampolinesERKNS_6TargetERN4llvm11LLVMContextERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKSt6ve2948072'/>
<use f='halide/build/include/Halide.h' l='19880'/>
<use f='halide/build/include/Halide.h' l='20305' c='_ZN6Halide8Internal12CodeGen_LLVM14finish_codegenEv'/>
<use f='halide/build/include/Halide.h' l='20315' c='_ZN6Halide12codegen_llvmERKNS_6ModuleERN4llvm11LLVMContextE'/>
<use f='halide/build/include/Halide.h' l='30180' c='_ZN6Halide29compile_module_to_llvm_moduleERKNS_6ModuleERN4llvm11LLVMContextE'/>
<use f='halide/build/include/Halide.h' l='30187' c='_ZN6Halide29compile_llvm_module_to_objectERN4llvm6ModuleERNS0_17raw_pwrite_streamE'/>
<use f='halide/build/include/Halide.h' l='30188' c='_ZN6Halide31compile_llvm_module_to_assemblyERN4llvm6ModuleERNS0_17raw_pwrite_streamE'/>
<use f='halide/build/include/Halide.h' l='30193' c='_ZN6Halide35compile_llvm_module_to_llvm_bitcodeERN4llvm6ModuleERNS0_17raw_pwrite_streamE'/>
<use f='halide/build/include/Halide.h' l='30194' c='_ZN6Halide36compile_llvm_module_to_llvm_assemblyERN4llvm6ModuleERNS0_17raw_pwrite_streamE'/>
<use f='halide/build/include/Halide.h' l='30236' c='_ZN6Halide8Internal29get_initial_module_for_targetENS_6TargetEPN4llvm11LLVMContextEbb'/>
<use f='halide/build/include/Halide.h' l='30239' c='_ZN6Halide8Internal33get_initial_module_for_ptx_deviceENS_6TargetEPN4llvm11LLVMContextE'/>
<use f='halide/build/include/Halide.h' l='30242' c='_ZN6Halide8Internal21add_bitcode_to_moduleEPN4llvm11LLVMContextERNS1_6ModuleERKSt6vectorIhSaIhEERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE'/>
<use f='halide/build/include/Halide.h' l='30247' c='_ZN6Halide8Internal26link_with_wasm_jit_runtimeEPN4llvm11LLVMContextERKNS_6TargetESt10unique_ptrINS1_6ModuleESt14default_deleteIS8_EE'/>
<use f='halide/build/include/Halide.h' l='30248' c='_ZN6Halide8Internal26link_with_wasm_jit_runtimeEPN4llvm11LLVMContextERKNS_6TargetESt10unique_ptrINS1_6ModuleESt14default_deleteIS8_EE'/>
<use f='halide/build/include/Halide.h' l='30441' c='_ZN6Halide8Internal21define_matlab_wrapperEPN4llvm6ModuleEPNS1_8FunctionES5_'/>
<use f='halide/src/JITModule.h' l='122' c='_ZN6Halide8Internal9JITModule14compile_moduleESt10unique_ptrIN4llvm6ModuleESt14default_deleteIS4_EERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIc1691512'/>
<use f='halide/src/JITModule.h' l='163' c='_ZN6Halide8Internal16JITSharedRuntime3getEPN4llvm6ModuleERKNS_6TargetEb'/>
<use f='halide/src/CodeGen_Internal.h' l='120' c='_ZN6Halide8Internal18get_target_optionsERKN4llvm6ModuleERNS1_13TargetOptionsERNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESD_'/>
<use f='halide/src/CodeGen_Internal.h' l='123' c='_ZN6Halide8Internal20clone_target_optionsERKN4llvm6ModuleERS2_'/>
<use f='halide/src/CodeGen_Internal.h' l='123' c='_ZN6Halide8Internal20clone_target_optionsERKN4llvm6ModuleERS2_'/>
<use f='halide/src/CodeGen_Internal.h' l='126' c='_ZN6Halide8Internal19make_target_machineERKN4llvm6ModuleE'/>
<use f='halide/src/CodeGen_Internal.h' l='135' c='_ZN6Halide8Internal13embed_bitcodeEPN4llvm6ModuleERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE'/>
<use f='halide/src/CodeGen_LLVM.h' l='65' c='_ZN6Halide8Internal12CodeGen_LLVM7compileERKNS_6ModuleE'/>
<use f='halide/src/CodeGen_LLVM.h' l='78' c='_ZN6Halide8Internal12CodeGen_LLVM19compile_trampolinesERKNS_6TargetERN4llvm11LLVMContextERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKSt6ve2948072'/>
<use f='halide/src/CodeGen_LLVM.h' l='141'/>
<use f='halide/src/CodeGen_LLVM.h' l='566' c='_ZN6Halide8Internal12CodeGen_LLVM14finish_codegenEv'/>
<use f='halide/src/CodeGen_LLVM.h' l='576' c='_ZN6Halide12codegen_llvmERKNS_6ModuleERN4llvm11LLVMContextE'/>
<use f='halide/llvm-install/include/llvm/IR/Value.h' l='240' c='_ZNK4llvm5Value14printAsOperandERNS_11raw_ostreamEbPKNS_6ModuleE'/>
<use f='halide/llvm-install/include/llvm/IR/LLVMContext.h' l='329'/>
<use f='halide/llvm-install/include/llvm/IR/LLVMContext.h' l='333' c='_ZN4llvm11LLVMContext9addModuleEPNS_6ModuleE'/>
<use f='halide/llvm-install/include/llvm/IR/LLVMContext.h' l='336' c='_ZN4llvm11LLVMContext12removeModuleEPNS_6ModuleE'/>
<use f='halide/llvm-install/include/llvm/IR/Metadata.h' l='112' c='_ZNK4llvm8Metadata4dumpEPKNS_6ModuleE'/>
<use f='halide/llvm-install/include/llvm/IR/Metadata.h' l='122' c='_ZNK4llvm8Metadata5printERNS_11raw_ostreamEPKNS_6ModuleEb'/>
<use f='halide/llvm-install/include/llvm/IR/Metadata.h' l='124' c='_ZNK4llvm8Metadata5printERNS_11raw_ostreamERNS_17ModuleSlotTrackerEPKNS_6ModuleEb'/>
<use f='halide/llvm-install/include/llvm/IR/Metadata.h' l='135' c='_ZNK4llvm8Metadata14printAsOperandERNS_11raw_ostreamEPKNS_6ModuleE'/>
<use f='halide/llvm-install/include/llvm/IR/Metadata.h' l='137' c='_ZNK4llvm8Metadata14printAsOperandERNS_11raw_ostreamERNS_17ModuleSlotTrackerEPKNS_6ModuleE'/>
<use f='halide/llvm-install/include/llvm/IR/Metadata.h' l='1376'/>
<use f='halide/llvm-install/include/llvm/IR/Metadata.h' l='1379'/>
<use f='halide/llvm-install/include/llvm/IR/Metadata.h' l='1382' c='_ZN4llvm11NamedMDNode9setParentEPNS_6ModuleE'/>
<use f='halide/llvm-install/include/llvm/IR/Metadata.h' l='1440' c='_ZN4llvm11NamedMDNode9getParentEv'/>
<use f='halide/llvm-install/include/llvm/IR/Metadata.h' l='1441' c='_ZNK4llvm11NamedMDNode9getParentEv'/>
<use f='halide/llvm-install/include/llvm/IR/DataLayout.h' l='203' c='_ZN4llvm10DataLayoutC1EPKNS_6ModuleE'/>
<use f='halide/llvm-install/include/llvm/IR/DataLayout.h' l='230' c='_ZN4llvm10DataLayout4initEPKNS_6ModuleE'/>
<use f='halide/llvm-install/include/llvm/IR/Comdat.h' l='51'/>
<use f='halide/llvm-install/include/llvm/IR/SymbolTableListTraits.h' l='54'/>
<use f='halide/llvm-install/include/llvm/IR/SymbolTableListTraits.h' l='55'/>
<use f='halide/llvm-install/include/llvm/IR/SymbolTableListTraits.h' l='56'/>
<use f='halide/llvm-install/include/llvm/IR/SymbolTableListTraits.h' l='57'/>
<use f='halide/llvm-install/include/llvm/IR/Instruction.h' l='102' c='_ZNK4llvm11Instruction9getModuleEv'/>
<use f='halide/llvm-install/include/llvm/IR/Instruction.h' l='103' c='_ZN4llvm11Instruction9getModuleEv'/>
<use f='halide/llvm-install/include/llvm/IR/Instruction.h' l='104' c='_ZN4llvm11Instruction9getModuleEv'/>
<use f='halide/llvm-install/include/llvm/IR/BasicBlock.h' l='114' c='_ZNK4llvm10BasicBlock9getModuleEv'/>
<use f='halide/llvm-install/include/llvm/IR/BasicBlock.h' l='115' c='_ZN4llvm10BasicBlock9getModuleEv'/>
<use f='halide/llvm-install/include/llvm/IR/BasicBlock.h' l='116' c='_ZN4llvm10BasicBlock9getModuleEv'/>
<use f='halide/llvm-install/include/llvm/IR/GlobalValue.h' l='166'/>
<use f='halide/llvm-install/include/llvm/IR/GlobalValue.h' l='169' c='_ZN4llvm11GlobalValue9setParentEPNS_6ModuleE'/>
<use f='halide/llvm-install/include/llvm/IR/GlobalValue.h' l='572' c='_ZN4llvm11GlobalValue9getParentEv'/>
<use f='halide/llvm-install/include/llvm/IR/GlobalValue.h' l='573' c='_ZNK4llvm11GlobalValue9getParentEv'/>
<use f='halide/llvm-install/include/llvm/IR/Function.h' l='125' c='_ZN4llvm8FunctionC1EPNS_12FunctionTypeENS_11GlobalValue12LinkageTypesEjRKNS_5TwineEPNS_6ModuleE'/>
<use f='halide/llvm-install/include/llvm/IR/Function.h' l='139' c='_ZN4llvm8Function6CreateEPNS_12FunctionTypeENS_11GlobalValue12LinkageTypesEjRKNS_5TwineEPNS_6ModuleE'/>
<use f='halide/llvm-install/include/llvm/IR/Function.h' l='145' c='_ZN4llvm8Function6CreateEPNS_12FunctionTypeENS_11GlobalValue12LinkageTypesERKNS_5TwineEPNS_6ModuleE'/>
<use f='halide/llvm-install/include/llvm/IR/Function.h' l='154' c='_ZN4llvm8Function6CreateEPNS_12FunctionTypeENS_11GlobalValue12LinkageTypesERKNS_5TwineERNS_6ModuleE'/>
<use f='halide/llvm-install/include/llvm/IR/GlobalAlias.h' l='32' c='_ZN4llvm11GlobalAliasC1EPNS_4TypeEjNS_11GlobalValue12LinkageTypesERKNS_5TwineEPNS_8ConstantEPNS_6ModuleE'/>
<use f='halide/llvm-install/include/llvm/IR/GlobalAlias.h' l='42' c='_ZN4llvm11GlobalAlias6createEPNS_4TypeEjNS_11GlobalValue12LinkageTypesERKNS_5TwineEPNS_8ConstantEPNS_6ModuleE'/>
<use f='halide/llvm-install/include/llvm/IR/GlobalAlias.h' l='47' c='_ZN4llvm11GlobalAlias6createEPNS_4TypeEjNS_11GlobalValue12LinkageTypesERKNS_5TwineEPNS_6ModuleE'/>
<use f='halide/llvm-install/include/llvm/IR/GlobalIFunc.h' l='37' c='_ZN4llvm11GlobalIFuncC1EPNS_4TypeEjNS_11GlobalValue12LinkageTypesERKNS_5TwineEPNS_8ConstantEPNS_6ModuleE'/>
<use f='halide/llvm-install/include/llvm/IR/GlobalIFunc.h' l='47' c='_ZN4llvm11GlobalIFunc6createEPNS_4TypeEjNS_11GlobalValue12LinkageTypesERKNS_5TwineEPNS_8ConstantEPNS_6ModuleE'/>
<use f='halide/llvm-install/include/llvm/IR/GlobalVariable.h' l='59' c='_ZN4llvm14GlobalVariableC1ERNS_6ModuleEPNS_4TypeEbNS_11GlobalValue12LinkageTypesEPNS_8ConstantERKNS_5TwineEPS0_NS5_15ThreadLocalModeENS_8OptionalIjEEb'/>
<def f='halide/llvm-install/include/llvm/IR/Module.h' l='67' ll='886'/>
<use f='halide/llvm-install/include/llvm/IR/Module.h' l='403' c='_ZN4llvm6Module17getGlobalVariableENS_9StringRefEb'/>
<use f='halide/llvm-install/include/llvm/IR/Module.h' l='415' c='_ZN4llvm6Module14getNamedGlobalENS_9StringRefE'/>
<use f='halide/llvm-install/include/llvm/IR/Module.h' l='535' c='_ZN4llvm6Module16getSublistAccessEPNS_14GlobalVariableE'/>
<use f='halide/llvm-install/include/llvm/IR/Module.h' l='543' c='_ZN4llvm6Module16getSublistAccessEPNS_8FunctionE'/>
<use f='halide/llvm-install/include/llvm/IR/Module.h' l='552' c='_ZN4llvm6Module16getSublistAccessEPNS_11GlobalAliasE'/>
<use f='halide/llvm-install/include/llvm/IR/Module.h' l='561' c='_ZN4llvm6Module16getSublistAccessEPNS_11GlobalIFuncE'/>
<use f='halide/llvm-install/include/llvm/IR/Module.h' l='570' c='_ZN4llvm6Module16getSublistAccessEPNS_11NamedMDNodeE'/>
<use f='halide/llvm-install/include/llvm/IR/Module.h' l='890' c='_ZN4llvm26collectUsedGlobalVariablesERKNS_6ModuleERNS_15SmallPtrSetImplIPNS_11GlobalValueEEEb'/>
<use f='halide/llvm-install/include/llvm/IR/Module.h' l='895' c='_ZN4llvmlsERNS_11raw_ostreamERKNS_6ModuleE'/>
<use f='halide/llvm-install/include/llvm/IR/Module.h' l='901' c='_ZN4llvm6unwrapEP16LLVMOpaqueModule'/>
<use f='halide/llvm-install/include/llvm/IR/Module.h' l='901' c='_ZN4llvm6unwrapEP16LLVMOpaqueModule'/>
<use f='halide/llvm-install/include/llvm/IR/Module.h' l='901' c='_ZN4llvm4wrapEPKNS_6ModuleE'/>
<use f='halide/llvm-install/include/llvm/IR/Module.h' l='901' c='_ZN4llvm4wrapEPKNS_6ModuleE'/>
<use f='halide/llvm-install/include/llvm/IR/Module.h' l='906' c='_ZN4llvm6unwrapEP24LLVMOpaqueModuleProvider'/>
<use f='halide/llvm-install/include/llvm/IR/Module.h' l='907' c='_ZN4llvm6unwrapEP24LLVMOpaqueModuleProvider'/>
<use f='halide/llvm-install/include/llvm/Pass.h' l='116' c='_ZN4llvm4Pass16doInitializationERNS_6ModuleE'/>
<use f='halide/llvm-install/include/llvm/Pass.h' l='120' c='_ZN4llvm4Pass14doFinalizationERNS_6ModuleE'/>
<use f='halide/llvm-install/include/llvm/Pass.h' l='128' c='_ZNK4llvm4Pass5printERNS_11raw_ostreamEPKNS_6ModuleE'/>
<use f='halide/llvm-install/include/llvm/Pass.h' l='251' c='_ZN4llvm10ModulePass11runOnModuleERNS_6ModuleE'/>
<use f='halide/llvm-install/include/llvm/Pass.h' l='261' c='_ZNK4llvm10ModulePass10skipModuleERNS_6ModuleE'/>
<use f='halide/llvm-install/include/llvm/Pass.h' l='286' c='_ZN4llvm13ImmutablePass11runOnModuleERNS_6ModuleE'/>
<use f='halide/llvm-install/include/llvm/IR/PassManager.h' l='103'/>
<use f='halide/llvm-install/include/llvm/IR/PassManager.h' l='588'/>
<use f='halide/llvm-install/include/llvm/IR/PassManager.h' l='591'/>
<use f='halide/llvm-install/include/llvm/IR/PassManager.h' l='942'/>
<use f='halide/llvm-install/include/llvm/IR/PassManager.h' l='945'/>
<use f='halide/llvm-install/include/llvm/IR/PassManager.h' l='1052'/>
<use f='halide/llvm-install/include/llvm/IR/PassManager.h' l='1058' c='_ZN4llvm25InnerAnalysisManagerProxy6Result10invalidateERT0_RKNS_17PreservedAnalysesERNS_15AnalysisManagerIS2_JDpT1_EE11InvalidatorE'/>
<use f='halide/llvm-install/include/llvm/IR/PassManager.h' l='1064'/>
<use f='halide/llvm-install/include/llvm/IR/PassManager.h' l='1240' c='_ZN4llvm27ModuleToFunctionPassAdaptor3runERNS_6ModuleERNS_15AnalysisManagerIS1_JEEE'/>
<use f='halide/llvm-install/include/llvm/Target/TargetMachine.h' l='32'/>
<use f='halide/llvm-install/include/llvm/Target/TargetMachine.h' l='226' c='_ZNK4llvm13TargetMachine20shouldAssumeDSOLocalERKNS_6ModuleEPKNS_11GlobalValueE'/>
<use f='halide/llvm-install/include/llvm/ExecutionEngine/ExecutionEngine.h' l='134'/>
<use f='halide/llvm-install/include/llvm/ExecutionEngine/ExecutionEngine.h' l='140'/>
<use f='halide/llvm-install/include/llvm/ExecutionEngine/ExecutionEngine.h' l='145'/>
<use f='halide/llvm-install/include/llvm/ExecutionEngine/ExecutionEngine.h' l='170' c='_ZN4llvm15ExecutionEngine9addModuleESt10unique_ptrINS_6ModuleESt14default_deleteIS2_EE'/>
<use f='halide/llvm-install/include/llvm/ExecutionEngine/ExecutionEngine.h' l='205' c='_ZN4llvm15ExecutionEngine12removeModuleEPNS_6ModuleE'/>
<use f='halide/llvm-install/include/llvm/ExecutionEngine/ExecutionEngine.h' l='266' c='_ZN4llvm15ExecutionEngine21generateCodeForModuleEPNS_6ModuleE'/>
<use f='halide/llvm-install/include/llvm/ExecutionEngine/ExecutionEngine.h' l='299' c='_ZN4llvm15ExecutionEngine32runStaticConstructorsDestructorsERNS_6ModuleEb'/>
<use f='halide/llvm-install/include/llvm/ExecutionEngine/ExecutionEngine.h' l='325' c='_ZN4llvm15ExecutionEngine29clearGlobalMappingsFromModuleEPNS_6ModuleE'/>
<use f='halide/llvm-install/include/llvm/ExecutionEngine/ExecutionEngine.h' l='506' c='_ZN4llvm15ExecutionEngineC1ENS_10DataLayoutESt10unique_ptrINS_6ModuleESt14default_deleteIS3_EE'/>
<use f='halide/llvm-install/include/llvm/ExecutionEngine/ExecutionEngine.h' l='507' c='_ZN4llvm15ExecutionEngineC1ESt10unique_ptrINS_6ModuleESt14default_deleteIS2_EE'/>
<use f='halide/llvm-install/include/llvm/ExecutionEngine/ExecutionEngine.h' l='518' c='_ZN4llvm15ExecutionEngine4InitESt10unique_ptrINS_6ModuleESt14default_deleteIS2_EE'/>
<use f='halide/llvm-install/include/llvm/ExecutionEngine/ExecutionEngine.h' l='537'/>
<use f='halide/llvm-install/include/llvm/ExecutionEngine/ExecutionEngine.h' l='557' c='_ZN4llvm13EngineBuilderC1ESt10unique_ptrINS_6ModuleESt14default_deleteIS2_EE'/>
<use f='halide/llvm-install/include/llvm/Analysis/TargetLibraryInfo.h' l='201' c='_ZNK4llvm21TargetLibraryInfoImpl12getWCharSizeERKNS_6ModuleE'/>
<use f='halide/llvm-install/include/llvm/Analysis/TargetLibraryInfo.h' l='394' c='_ZNK4llvm17TargetLibraryInfo12getWCharSizeERKNS_6ModuleE'/>
<use f='halide/llvm-install/include/llvm/Analysis/TargetLibraryInfo.h' l='402' c='_ZN4llvm17TargetLibraryInfo10invalidateERNS_6ModuleERKNS_17PreservedAnalysesERNS_15AnalysisManagerIS1_JEE11InvalidatorE'/>
<use f='halide/llvm-install/include/llvm/IR/ModuleSummaryIndex.h' l='1409' c='_ZNK4llvm18ModuleSummaryIndex20hasExportedFunctionsERKNS_6ModuleE'/>
<use f='halide/llvm-install/include/llvm/Bitcode/BitcodeReader.h' l='83' c='_ZN4llvm13BitcodeModule13getModuleImplERNS_11LLVMContextEbbbNS_12function_refIFNS_8OptionalINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEENS_9StringRefEEEE'/>
<use f='halide/llvm-install/include/llvm/Bitcode/BitcodeReader.h' l='101' c='_ZN4llvm13BitcodeModule13getLazyModuleERNS_11LLVMContextEbb'/>
<use f='halide/llvm-install/include/llvm/Bitcode/BitcodeReader.h' l='106' c='_ZN4llvm13BitcodeModule11parseModuleERNS_11LLVMContextENS_12function_refIFNS_8OptionalINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEENS_9StringRefEEEE'/>
<use f='halide/llvm-install/include/llvm/Bitcode/BitcodeReader.h' l='143' c='_ZN4llvm20getLazyBitcodeModuleENS_15MemoryBufferRefERNS_11LLVMContextEbb'/>
<use f='halide/llvm-install/include/llvm/Bitcode/BitcodeReader.h' l='152' c='_ZN4llvm26getOwningLazyBitcodeModuleEOSt10unique_ptrINS_12MemoryBufferESt14default_deleteIS1_EERNS_11LLVMContextEbb'/>
<use f='halide/llvm-install/include/llvm/Bitcode/BitcodeReader.h' l='171' c='_ZN4llvm16parseBitcodeFileENS_15MemoryBufferRefERNS_11LLVMContextENS_12function_refIFNS_8OptionalINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEENS_9StringRefEEEE'/>
<use f='halide/llvm-install/include/llvm/Bitcode/BitcodeWriter.h' l='46'/>
<use f='halide/llvm-install/include/llvm/Bitcode/BitcodeWriter.h' l='89' c='_ZN4llvm13BitcodeWriter11writeModuleERKNS_6ModuleEbPKNS_18ModuleSummaryIndexEbPSt5arrayIjLm5EE'/>
<use f='halide/llvm-install/include/llvm/Bitcode/BitcodeWriter.h' l='100' c='_ZN4llvm13BitcodeWriter20writeThinLinkBitcodeERKNS_6ModuleERKNS_18ModuleSummaryIndexERKSt5arrayIjLm5EE'/>
<use f='halide/llvm-install/include/llvm/Bitcode/BitcodeWriter.h' l='129' c='_ZN4llvm18WriteBitcodeToFileERKNS_6ModuleERNS_11raw_ostreamEbPKNS_18ModuleSummaryIndexEbPSt5arrayIjLm5EE'/>
<use f='halide/llvm-install/include/llvm/Bitcode/BitcodeWriter.h' l='142' c='_ZN4llvm26WriteThinLinkBitcodeToFileERKNS_6ModuleERNS_11raw_ostreamERKNS_18ModuleSummaryIndexERKSt5arrayIjLm5EE'/>
<use f='halide/llvm-install/include/llvm/Bitcode/BitcodeWriter.h' l='164' c='_ZN4llvm20EmbedBitcodeInModuleERNS_6ModuleENS_15MemoryBufferRefEbbRKSt6vectorIhSaIhEE'/>
<use f='halide/llvm-install/include/llvm/IR/LegacyPassManager.h' l='58' c='_ZN4llvm6legacy11PassManager3runERNS_6ModuleE'/>
<use f='halide/llvm-install/include/llvm/IR/LegacyPassManager.h' l='71' c='_ZN4llvm6legacy19FunctionPassManagerC1EPNS_6ModuleE'/>
<use f='halide/llvm-install/include/llvm/IR/LegacyPassManager.h' l='92'/>
<use f='halide/llvm-install/include/llvm/IR/Verifier.h' l='100' c='_ZN4llvm12verifyModuleERKNS_6ModuleEPNS_11raw_ostreamEPb'/>
<use f='halide/llvm-install/include/llvm/IR/Verifier.h' l='117' c='_ZN4llvm16VerifierAnalysis3runERNS_6ModuleERNS_15AnalysisManagerIS1_JEEE'/>
<use f='halide/llvm-install/include/llvm/IR/Verifier.h' l='125' c='_ZN4llvm12verifyModuleERbRKNS_6ModuleEPNS_11raw_ostreamE'/>
<use f='halide/llvm-install/include/llvm/IR/Verifier.h' l='143' c='_ZN4llvm12VerifierPass3runERNS_6ModuleERNS_15AnalysisManagerIS1_JEEE'/>
<use f='halide/llvm-install/include/llvm/Linker/IRMover.h' l='62' c='_ZN4llvm7IRMoverC1ERNS_6ModuleE'/>
<use f='halide/llvm-install/include/llvm/Linker/IRMover.h' l='75' c='_ZN4llvm7IRMover4moveESt10unique_ptrINS_6ModuleESt14default_deleteIS2_EENS_8ArrayRefIPNS_11GlobalValueEEESt8functionIFvRS7_SA_IFvSB_EEEEb'/>
<use f='halide/llvm-install/include/llvm/Linker/IRMover.h' l='78' c='_ZN4llvm7IRMover9getModuleEv'/>
<use f='halide/llvm-install/include/llvm/Linker/IRMover.h' l='81'/>
<use f='halide/llvm-install/include/llvm/Linker/Linker.h' l='34' c='_ZN4llvm6LinkerC1ERNS_6ModuleE'/>
<use f='halide/llvm-install/include/llvm/Linker/Linker.h' l='46' c='_ZN4llvm6Linker12linkInModuleESt10unique_ptrINS_6ModuleESt14default_deleteIS2_EEjSt8functionIFvRS2_RKNS_9StringSetINS_15MallocAllocatorEEEEE'/>
<use f='halide/llvm-install/include/llvm/Linker/Linker.h' l='47' c='_ZN4llvm6Linker12linkInModuleESt10unique_ptrINS_6ModuleESt14default_deleteIS2_EEjSt8functionIFvRS2_RKNS_9StringSetINS_15MallocAllocatorEEEEE'/>
<use f='halide/llvm-install/include/llvm/Linker/Linker.h' l='50' c='_ZN4llvm6Linker11linkModulesERNS_6ModuleESt10unique_ptrIS1_St14default_deleteIS1_EEjSt8functionIFvS2_RKNS_9StringSetINS_15MallocAllocatorEEEEE'/>
<use f='halide/llvm-install/include/llvm/Linker/Linker.h' l='50' c='_ZN4llvm6Linker11linkModulesERNS_6ModuleESt10unique_ptrIS1_St14default_deleteIS1_EEjSt8functionIFvS2_RKNS_9StringSetINS_15MallocAllocatorEEEEE'/>
<use f='halide/llvm-install/include/llvm/Linker/Linker.h' l='52' c='_ZN4llvm6Linker11linkModulesERNS_6ModuleESt10unique_ptrIS1_St14default_deleteIS1_EEjSt8functionIFvS2_RKNS_9StringSetINS_15MallocAllocatorEEEEE'/>
<use f='halide/llvm-install/include/llvm/Analysis/LazyCallGraph.h' l='922' c='_ZN4llvm13LazyCallGraphC1ERNS_6ModuleENS_12function_refIFRNS_17TargetLibraryInfoERNS_8FunctionEEEE'/>
<use f='halide/llvm-install/include/llvm/Analysis/LazyCallGraph.h' l='928' c='_ZN4llvm13LazyCallGraph10invalidateERNS_6ModuleERKNS_17PreservedAnalysesERNS_15AnalysisManagerIS1_JEE11InvalidatorE'/>
<use f='halide/llvm-install/include/llvm/Analysis/LazyCallGraph.h' l='1290' c='_ZN4llvm21LazyCallGraphAnalysis3runERNS_6ModuleERNS_15AnalysisManagerIS1_JEEE'/>
<use f='halide/llvm-install/include/llvm/Analysis/LazyCallGraph.h' l='1310' c='_ZN4llvm24LazyCallGraphPrinterPass3runERNS_6ModuleERNS_15AnalysisManagerIS1_JEEE'/>
<use f='halide/llvm-install/include/llvm/Analysis/LazyCallGraph.h' l='1323' c='_ZN4llvm27LazyCallGraphDOTPrinterPass3runERNS_6ModuleERNS_15AnalysisManagerIS1_JEEE'/>
<use f='halide/llvm-install/include/llvm/Analysis/CGSCCPassManager.h' l='168'/>
<use f='halide/llvm-install/include/llvm/Analysis/CGSCCPassManager.h' l='191' c='_ZN4llvm25InnerAnalysisManagerProxyINS_15AnalysisManagerINS_13LazyCallGraph3SCCEJRS2_EEENS_6ModuleEJEE6Result10invalidateERS6_RKNS_17PreservedAnalyses7690279'/>
<use f='halide/llvm-install/include/llvm/Analysis/CGSCCPassManager.h' l='203' c='_ZN4llvm25InnerAnalysisManagerProxy3runERT0_RNS_15AnalysisManagerIS1_JDpT1_EEES5_'/>
<use f='halide/llvm-install/include/llvm/Analysis/CGSCCPassManager.h' l='207'/>
<use f='halide/llvm-install/include/llvm/Analysis/CGSCCPassManager.h' l='364' c='_ZN4llvm33ModuleToPostOrderCGSCCPassAdaptor3runERNS_6ModuleERNS_15AnalysisManagerIS1_JEEE'/>
<use f='halide/llvm-install/include/llvm/Analysis/AssumptionCache.h' l='244' c='_ZN4llvm22AssumptionCacheTracker14doFinalizationERNS_6ModuleE'/>
<use f='halide/llvm-install/include/llvm/Analysis/BlockFrequencyInfo.h' l='154' c='_ZNK4llvm29BlockFrequencyInfoWrapperPass5printERNS_11raw_ostreamEPKNS_6ModuleE'/>
<use f='halide/llvm-install/include/llvm/IR/DiagnosticInfo.h' l='238'/>
<use f='halide/llvm-install/include/llvm/IR/DiagnosticInfo.h' l='245' c='_ZN4llvm34DiagnosticInfoDebugMetadataVersionC1ERKNS_6ModuleEjNS_18DiagnosticSeverityE'/>
<use f='halide/llvm-install/include/llvm/IR/DiagnosticInfo.h' l='250' c='_ZNK4llvm34DiagnosticInfoDebugMetadataVersion9getModuleEv'/>
<use f='halide/llvm-install/include/llvm/IR/DiagnosticInfo.h' l='265'/>
<use f='halide/llvm-install/include/llvm/IR/DiagnosticInfo.h' l='270' c='_ZN4llvm42DiagnosticInfoIgnoringInvalidDebugMetadataC1ERKNS_6ModuleENS_18DiagnosticSeverityE'/>
<use f='halide/llvm-install/include/llvm/IR/DiagnosticInfo.h' l='273' c='_ZNK4llvm42DiagnosticInfoIgnoringInvalidDebugMetadata9getModuleEv'/>
<use f='halide/llvm-install/include/llvm/Analysis/Utils/ImportedFunctionsInliningStatistics.h' l='69' c='_ZN4llvm35ImportedFunctionsInliningStatistics13setModuleInfoERKNS_6ModuleE'/>
<use f='halide/llvm-install/include/llvm/Analysis/InlineAdvisor.h' l='165' c='_ZN4llvm13InlineAdvisorC1ERNS_6ModuleERNS_15AnalysisManagerINS_8FunctionEJEEE'/>
<use f='halide/llvm-install/include/llvm/Analysis/InlineAdvisor.h' l='170'/>
<use f='halide/llvm-install/include/llvm/Analysis/InlineAdvisor.h' l='206' c='_ZN4llvm20DefaultInlineAdvisorC1ERNS_6ModuleERNS_15AnalysisManagerINS_8FunctionEJEEENS_12InlineParamsE'/>
<use f='halide/llvm-install/include/llvm/Analysis/InlineAdvisor.h' l='225' c='_ZN4llvm21InlineAdvisorAnalysis6ResultC1ERNS_6ModuleERNS_15AnalysisManagerIS2_JEEE'/>
<use f='halide/llvm-install/include/llvm/Analysis/InlineAdvisor.h' l='226' c='_ZN4llvm21InlineAdvisorAnalysis6Result10invalidateERNS_6ModuleERKNS_17PreservedAnalysesERNS_15AnalysisManagerIS2_JEE11InvalidatorE'/>
<use f='halide/llvm-install/include/llvm/Analysis/InlineAdvisor.h' l='237'/>
<use f='halide/llvm-install/include/llvm/Analysis/InlineAdvisor.h' l='242' c='_ZN4llvm21InlineAdvisorAnalysis3runERNS_6ModuleERNS_15AnalysisManagerIS1_JEEE'/>
<use f='halide/llvm-install/include/llvm/Analysis/ReplayInlineAdvisor.h' l='27' c='_ZN4llvm19ReplayInlineAdvisorC1ERNS_6ModuleERNS_15AnalysisManagerINS_8FunctionEJEEERNS_11LLVMContextESt10unique_ptrINS_13InlineAdvisorESt14default_del7365519'/>
<use f='halide/llvm-install/include/llvm/Transforms/IPO/Inliner.h' l='108' c='_ZN4llvm11InlinerPass10getAdvisorERKNS_25OuterAnalysisManagerProxyINS_15AnalysisManagerINS_6ModuleEJEEENS_13LazyCallGraph3SCCEJRS5_EE6ResultERNS2_INS_8FunctionEJEEERS3_'/>
<use f='halide/llvm-install/include/llvm/Transforms/IPO/Inliner.h' l='128' c='_ZN4llvm24ModuleInlinerWrapperPass3runERNS_6ModuleERNS_15AnalysisManagerIS1_JEEE'/>
<use f='halide/llvm-install/include/llvm/Transforms/IPO/Inliner.h' l='136' c='_ZN4llvm24ModuleInlinerWrapperPass25addRequiredModuleAnalysisEv'/>
<use f='halide/llvm-install/include/llvm/Transforms/Instrumentation.h' l='42' c='_ZN4llvm28createPrivateGlobalForStringERNS_6ModuleENS_9StringRefEbPKc'/>
<use f='halide/llvm-install/include/llvm/Analysis/LoopInfo.h' l='1267' c='_ZNK4llvm19LoopInfoWrapperPass5printERNS_11raw_ostreamEPKNS_6ModuleE'/>
<use f='halide/llvm-install/include/llvm/IR/Dominators.h' l='299' c='_ZNK4llvm24DominatorTreeWrapperPass5printERNS_11raw_ostreamEPKNS_6ModuleE'/>
<use f='halide/llvm-install/include/llvm/Transforms/Instrumentation/AddressSanitizer.h' l='51' c='_ZN4llvm15GlobalsMetadataC1ERNS_6ModuleE'/>
<use f='halide/llvm-install/include/llvm/Transforms/Instrumentation/AddressSanitizer.h' l='61' c='_ZN4llvm15GlobalsMetadata10invalidateERNS_6ModuleERKNS_17PreservedAnalysesERNS_15AnalysisManagerIS1_JEE11InvalidatorE'/>
<use f='halide/llvm-install/include/llvm/Transforms/Instrumentation/AddressSanitizer.h' l='85' c='_ZN4llvm27ASanGlobalsMetadataAnalysis3runERNS_6ModuleERNS_15AnalysisManagerIS1_JEEE'/>
<use f='halide/llvm-install/include/llvm/Transforms/Instrumentation/AddressSanitizer.h' l='125' c='_ZN4llvm26ModuleAddressSanitizerPass3runERNS_6ModuleERNS_15AnalysisManagerIS1_JEEE'/>
<use f='halide/llvm-install/include/llvm/Transforms/Instrumentation/ThreadSanitizer.h' l='30' c='_ZN4llvm19ThreadSanitizerPass3runERNS_6ModuleERNS_15AnalysisManagerIS1_JEEE'/>
<use f='halide/llvm-install/include/llvm/Transforms/Utils/ModuleUtils.h' l='35' c='_ZN4llvm19appendToGlobalCtorsERNS_6ModuleEPNS_8FunctionEiPNS_8ConstantE'/>
<use f='halide/llvm-install/include/llvm/Transforms/Utils/ModuleUtils.h' l='39' c='_ZN4llvm19appendToGlobalDtorsERNS_6ModuleEPNS_8FunctionEiPNS_8ConstantE'/>
<use f='halide/llvm-install/include/llvm/Transforms/Utils/ModuleUtils.h' l='42' c='_ZN4llvm28declareSanitizerInitFunctionERNS_6ModuleENS_9StringRefENS_8ArrayRefIPNS_4TypeEEE'/>
<use f='halide/llvm-install/include/llvm/Transforms/Utils/ModuleUtils.h' l='47' c='_ZN4llvm19createSanitizerCtorERNS_6ModuleENS_9StringRefE'/>
<use f='halide/llvm-install/include/llvm/Transforms/Utils/ModuleUtils.h' l='54' c='_ZN4llvm35createSanitizerCtorAndInitFunctionsERNS_6ModuleENS_9StringRefES2_NS_8ArrayRefIPNS_4TypeEEENS3_IPNS_5ValueEEES2_'/>
<use f='halide/llvm-install/include/llvm/Transforms/Utils/ModuleUtils.h' l='66' c='_ZN4llvm40getOrCreateSanitizerCtorAndInitFunctionsERNS_6ModuleENS_9StringRefES2_NS_8ArrayRefIPNS_4TypeEEENS3_IPNS_5ValueEEENS_12function_refIFvPNS_8Fu13969480'/>
<use f='halide/llvm-install/include/llvm/Transforms/Utils/ModuleUtils.h' l='74' c='_ZN4llvm23getOrCreateInitFunctionERNS_6ModuleENS_9StringRefE'/>
<use f='halide/llvm-install/include/llvm/Transforms/Utils/ModuleUtils.h' l='78' c='_ZN4llvm17nameUnamedGlobalsERNS_6ModuleE'/>
<use f='halide/llvm-install/include/llvm/Transforms/Utils/ModuleUtils.h' l='81' c='_ZN4llvm12appendToUsedERNS_6ModuleENS_8ArrayRefIPNS_11GlobalValueEEE'/>
<use f='halide/llvm-install/include/llvm/Transforms/Utils/ModuleUtils.h' l='84' c='_ZN4llvm20appendToCompilerUsedERNS_6ModuleENS_8ArrayRefIPNS_11GlobalValueEEE'/>
<use f='halide/llvm-install/include/llvm/Transforms/Utils/ModuleUtils.h' l='100' c='_ZN4llvm25filterDeadComdatFunctionsERNS_6ModuleERNS_15SmallVectorImplIPNS_8FunctionEEE'/>
<use f='halide/llvm-install/include/llvm/Transforms/Utils/ModuleUtils.h' l='112' c='_ZN4llvm17getUniqueModuleIdB5cxx11EPNS_6ModuleE'/>
<use f='halide/llvm-install/include/llvm/Transforms/Utils/SymbolRewriter.h' l='83' c='_ZN4llvm14SymbolRewriter17RewriteDescriptor15performOnModuleERNS_6ModuleE'/>
<use f='halide/llvm-install/include/llvm/Transforms/Utils/SymbolRewriter.h' l='128' c='_ZN4llvm17RewriteSymbolPass3runERNS_6ModuleERNS_15AnalysisManagerIS1_JEEE'/>
<use f='halide/llvm-install/include/llvm/Transforms/Utils/SymbolRewriter.h' l='131' c='_ZN4llvm17RewriteSymbolPass7runImplERNS_6ModuleE'/>
<use f='halide/llvm-install/include/llvm/Transforms/IPO/AlwaysInliner.h' l='36' c='_ZN4llvm17AlwaysInlinerPass3runERNS_6ModuleERNS_15AnalysisManagerIS1_JEEE'/>
<use f='halide/llvm-install/include/llvm/IR/Intrinsics.h' l='87' c='_ZN4llvm9Intrinsic14getDeclarationEPNS_6ModuleEjNS_8ArrayRefIPNS_4TypeEEE'/>
<use f='halide/llvm-install/include/llvm/IR/IRBuilder.h' l='450' c='_ZN4llvm13IRBuilderBase18CreateGlobalStringENS_9StringRefERKNS_5TwineEjPNS_6ModuleE'/>
<use f='halide/llvm-install/include/llvm/IR/IRBuilder.h' l='2048' c='_ZN4llvm13IRBuilderBase21CreateGlobalStringPtrENS_9StringRefERKNS_5TwineEjPNS_6ModuleE'/>
<use f='halide/src/LLVM_Headers.h' l='117' c='_ZN6Halide8Internal28get_llvm_struct_type_by_nameEPN4llvm6ModuleEPKc'/>
<size>744</size>
<doc f='halide/llvm-install/include/llvm/IR/Module.h' l='56'>/// A Module instance is used to store all the information related to an
/// LLVM module. Modules are the top level container of all other LLVM
/// Intermediate Representation (IR) objects. Each module directly contains a
/// list of globals variables, a list of functions, a list of libraries (or
/// other modules) this module depends on, a symbol table, and various data
/// about the target&apos;s characteristics.
///
/// A module maintains a GlobalValRefMap object that is used to hold all
/// constant references to global variables in the module.  When a global
/// variable is destroyed, it should have no entries in the GlobalValueRefMap.
/// The main container class for the LLVM Intermediate Representation.</doc>
<fun r='_ZN4llvm6Module22isValidModFlagBehaviorEPNS_8MetadataERNS0_15ModFlagBehaviorE'/>
<fun r='_ZN4llvm6Module17isValidModuleFlagERKNS_6MDNodeERNS0_15ModFlagBehaviorERPNS_8MDStringERPNS_8MetadataE'/>
<mbr r='llvm::Module::Context' o='0' t='llvm::LLVMContext &amp;'/>
<mbr r='llvm::Module::GlobalList' o='64' t='llvm::Module::GlobalListType'/>
<mbr r='llvm::Module::FunctionList' o='192' t='llvm::Module::FunctionListType'/>
<mbr r='llvm::Module::AliasList' o='320' t='llvm::Module::AliasListType'/>
<mbr r='llvm::Module::IFuncList' o='448' t='llvm::Module::IFuncListType'/>
<mbr r='llvm::Module::NamedMDList' o='576' t='llvm::Module::NamedMDListType'/>
<mbr r='llvm::Module::GlobalScopeAsm' o='704' t='std::string'/>
<mbr r='llvm::Module::ValSymTab' o='960' t='std::unique_ptr&lt;ValueSymbolTable&gt;'/>
<mbr r='llvm::Module::ComdatSymTab' o='1024' t='llvm::Module::ComdatSymTabType'/>
<mbr r='llvm::Module::OwnedMemoryBuffer' o='1280' t='std::unique_ptr&lt;MemoryBuffer&gt;'/>
<mbr r='llvm::Module::Materializer' o='1344' t='std::unique_ptr&lt;GVMaterializer&gt;'/>
<mbr r='llvm::Module::ModuleID' o='1408' t='std::string'/>
<mbr r='llvm::Module::SourceFileName' o='1664' t='std::string'/>
<mbr r='llvm::Module::TargetTriple' o='1920' t='std::string'/>
<mbr r='llvm::Module::NamedMDSymTab' o='2176' t='llvm::Module::NamedMDSymTabType'/>
<mbr r='llvm::Module::DL' o='2432' t='llvm::DataLayout'/>
<fun r='_ZN4llvm6ModuleC1ENS_9StringRefERNS_11LLVMContextE'/>
<fun r='_ZN4llvm6ModuleD1Ev'/>
<fun r='_ZNK4llvm6Module19getModuleIdentifierB5cxx11Ev'/>
<fun r='_ZN4llvm6Module19getInstructionCountEv'/>
<fun r='_ZNK4llvm6Module17getSourceFileNameB5cxx11Ev'/>
<fun r='_ZNK4llvm6Module7getNameEv'/>
<fun r='_ZNK4llvm6Module16getDataLayoutStrB5cxx11Ev'/>
<fun r='_ZNK4llvm6Module13getDataLayoutEv'/>
<fun r='_ZNK4llvm6Module15getTargetTripleB5cxx11Ev'/>
<fun r='_ZNK4llvm6Module10getContextEv'/>
<fun r='_ZNK4llvm6Module18getModuleInlineAsmB5cxx11Ev'/>
<fun r='_ZNK4llvm6Module9createRNGENS_9StringRefE'/>
<fun r='_ZN4llvm6Module33shouldEmitInstrCountChangedRemarkEv'/>
<fun r='_ZN4llvm6Module19setModuleIdentifierENS_9StringRefE'/>
<fun r='_ZN4llvm6Module17setSourceFileNameENS_9StringRefE'/>
<fun r='_ZN4llvm6Module13setDataLayoutENS_9StringRefE'/>
<fun r='_ZN4llvm6Module13setDataLayoutERKNS_10DataLayoutE'/>
<fun r='_ZN4llvm6Module15setTargetTripleENS_9StringRefE'/>
<fun r='_ZN4llvm6Module18setModuleInlineAsmENS_9StringRefE'/>
<fun r='_ZN4llvm6Module21appendModuleInlineAsmENS_9StringRefE'/>
<fun r='_ZNK4llvm6Module13getNamedValueENS_9StringRefE'/>
<fun r='_ZNK4llvm6Module11getMDKindIDENS_9StringRefE'/>
<fun r='_ZNK4llvm6Module14getMDKindNamesERNS_15SmallVectorImplINS_9StringRefEEE'/>
<fun r='_ZNK4llvm6Module20getOperandBundleTagsERNS_15SmallVectorImplINS_9StringRefEEE'/>
<fun r='_ZNK4llvm6Module24getIdentifiedStructTypesEv'/>
<fun r='_ZN4llvm6Module19getOrInsertFunctionENS_9StringRefEPNS_12FunctionTypeENS_13AttributeListE'/>
<fun r='_ZN4llvm6Module19getOrInsertFunctionENS_9StringRefEPNS_12FunctionTypeE'/>
<fun r='_ZN4llvm6Module19getOrInsertFunctionENS_9StringRefENS_13AttributeListEPNS_4TypeEDpT_'/>
<fun r='_ZN4llvm6Module19getOrInsertFunctionENS_9StringRefEPNS_4TypeEDpT_'/>
<fun r='_ZN4llvm6Module19getOrInsertFunctionENS_9StringRefENS_13AttributeListEPNS_12FunctionTypeEDpT_'/>
<fun r='_ZNK4llvm6Module11getFunctionENS_9StringRefE'/>
<fun r='_ZNK4llvm6Module17getGlobalVariableENS_9StringRefE'/>
<fun r='_ZNK4llvm6Module17getGlobalVariableENS_9StringRefEb'/>
<fun r='_ZN4llvm6Module17getGlobalVariableENS_9StringRefEb'/>
<fun r='_ZNK4llvm6Module14getNamedGlobalENS_9StringRefE'/>
<fun r='_ZN4llvm6Module14getNamedGlobalENS_9StringRefE'/>
<fun r='_ZN4llvm6Module17getOrInsertGlobalENS_9StringRefEPNS_4TypeENS_12function_refIFPNS_14GlobalVariableEvEEE'/>
<fun r='_ZN4llvm6Module17getOrInsertGlobalENS_9StringRefEPNS_4TypeE'/>
<fun r='_ZNK4llvm6Module13getNamedAliasENS_9StringRefE'/>
<fun r='_ZNK4llvm6Module13getNamedIFuncENS_9StringRefE'/>
<fun r='_ZNK4llvm6Module16getNamedMetadataERKNS_5TwineE'/>
<fun r='_ZN4llvm6Module24getOrInsertNamedMetadataENS_9StringRefE'/>
<fun r='_ZN4llvm6Module18eraseNamedMetadataEPNS_11NamedMDNodeE'/>
<fun r='_ZN4llvm6Module17getOrInsertComdatENS_9StringRefE'/>
<fun r='_ZNK4llvm6Module22getModuleFlagsMetadataERNS_15SmallVectorImplINS0_15ModuleFlagEntryEEE'/>
<fun r='_ZNK4llvm6Module13getModuleFlagENS_9StringRefE'/>
<fun r='_ZNK4llvm6Module22getModuleFlagsMetadataEv'/>
<fun r='_ZN4llvm6Module30getOrInsertModuleFlagsMetadataEv'/>
<fun r='_ZN4llvm6Module13addModuleFlagENS0_15ModFlagBehaviorENS_9StringRefEPNS_8MetadataE'/>
<fun r='_ZN4llvm6Module13addModuleFlagENS0_15ModFlagBehaviorENS_9StringRefEPNS_8ConstantE'/>
<fun r='_ZN4llvm6Module13addModuleFlagENS0_15ModFlagBehaviorENS_9StringRefEj'/>
<fun r='_ZN4llvm6Module13addModuleFlagEPNS_6MDNodeE'/>
<fun r='_ZN4llvm6Module13setModuleFlagENS0_15ModFlagBehaviorENS_9StringRefEPNS_8MetadataE'/>
<fun r='_ZN4llvm6Module15setMaterializerEPNS_14GVMaterializerE'/>
<fun r='_ZNK4llvm6Module15getMaterializerEv'/>
<fun r='_ZNK4llvm6Module14isMaterializedEv'/>
<fun r='_ZN4llvm6Module11materializeEPNS_11GlobalValueE'/>
<fun r='_ZN4llvm6Module14materializeAllEv'/>
<fun r='_ZN4llvm6Module19materializeMetadataEv'/>
<fun r='_ZNK4llvm6Module13getGlobalListEv'/>
<fun r='_ZN4llvm6Module13getGlobalListEv'/>
<fun r='_ZN4llvm6Module16getSublistAccessEPNS_14GlobalVariableE'/>
<fun r='_ZNK4llvm6Module15getFunctionListEv'/>
<fun r='_ZN4llvm6Module15getFunctionListEv'/>
<fun r='_ZN4llvm6Module16getSublistAccessEPNS_8FunctionE'/>
<fun r='_ZNK4llvm6Module12getAliasListEv'/>
<fun r='_ZN4llvm6Module12getAliasListEv'/>
<fun r='_ZN4llvm6Module16getSublistAccessEPNS_11GlobalAliasE'/>
<fun r='_ZNK4llvm6Module12getIFuncListEv'/>
<fun r='_ZN4llvm6Module12getIFuncListEv'/>
<fun r='_ZN4llvm6Module16getSublistAccessEPNS_11GlobalIFuncE'/>
<fun r='_ZNK4llvm6Module14getNamedMDListEv'/>
<fun r='_ZN4llvm6Module14getNamedMDListEv'/>
<fun r='_ZN4llvm6Module16getSublistAccessEPNS_11NamedMDNodeE'/>
<fun r='_ZNK4llvm6Module19getValueSymbolTableEv'/>
<fun r='_ZN4llvm6Module19getValueSymbolTableEv'/>
<fun r='_ZNK4llvm6Module20getComdatSymbolTableEv'/>
<fun r='_ZN4llvm6Module20getComdatSymbolTableEv'/>
<fun r='_ZN4llvm6Module12global_beginEv'/>
<fun r='_ZNK4llvm6Module12global_beginEv'/>
<fun r='_ZN4llvm6Module10global_endEv'/>
<fun r='_ZNK4llvm6Module10global_endEv'/>
<fun r='_ZNK4llvm6Module11global_sizeEv'/>
<fun r='_ZNK4llvm6Module12global_emptyEv'/>
<fun r='_ZN4llvm6Module7globalsEv'/>
<fun r='_ZNK4llvm6Module7globalsEv'/>
<fun r='_ZN4llvm6Module5beginEv'/>
<fun r='_ZNK4llvm6Module5beginEv'/>
<fun r='_ZN4llvm6Module3endEv'/>
<fun r='_ZNK4llvm6Module3endEv'/>
<fun r='_ZN4llvm6Module6rbeginEv'/>
<fun r='_ZNK4llvm6Module6rbeginEv'/>
<fun r='_ZN4llvm6Module4rendEv'/>
<fun r='_ZNK4llvm6Module4rendEv'/>
<fun r='_ZNK4llvm6Module4sizeEv'/>
<fun r='_ZNK4llvm6Module5emptyEv'/>
<fun r='_ZN4llvm6Module9functionsEv'/>
<fun r='_ZNK4llvm6Module9functionsEv'/>
<fun r='_ZN4llvm6Module11alias_beginEv'/>
<fun r='_ZNK4llvm6Module11alias_beginEv'/>
<fun r='_ZN4llvm6Module9alias_endEv'/>
<fun r='_ZNK4llvm6Module9alias_endEv'/>
<fun r='_ZNK4llvm6Module10alias_sizeEv'/>
<fun r='_ZNK4llvm6Module11alias_emptyEv'/>
<fun r='_ZN4llvm6Module7aliasesEv'/>
<fun r='_ZNK4llvm6Module7aliasesEv'/>
<fun r='_ZN4llvm6Module11ifunc_beginEv'/>
<fun r='_ZNK4llvm6Module11ifunc_beginEv'/>
<fun r='_ZN4llvm6Module9ifunc_endEv'/>
<fun r='_ZNK4llvm6Module9ifunc_endEv'/>
<fun r='_ZNK4llvm6Module10ifunc_sizeEv'/>
<fun r='_ZNK4llvm6Module11ifunc_emptyEv'/>
<fun r='_ZN4llvm6Module6ifuncsEv'/>
<fun r='_ZNK4llvm6Module6ifuncsEv'/>
<fun r='_ZN4llvm6Module14global_objectsEv'/>
<fun r='_ZNK4llvm6Module14global_objectsEv'/>
<fun r='_ZN4llvm6Module13global_valuesEv'/>
<fun r='_ZNK4llvm6Module13global_valuesEv'/>
<fun r='_ZN4llvm6Module20named_metadata_beginEv'/>
<fun r='_ZNK4llvm6Module20named_metadata_beginEv'/>
<fun r='_ZN4llvm6Module18named_metadata_endEv'/>
<fun r='_ZNK4llvm6Module18named_metadata_endEv'/>
<fun r='_ZNK4llvm6Module19named_metadata_sizeEv'/>
<fun r='_ZNK4llvm6Module20named_metadata_emptyEv'/>
<fun r='_ZN4llvm6Module14named_metadataEv'/>
<fun r='_ZNK4llvm6Module14named_metadataEv'/>
<fun r='_ZNK4llvm6Module25debug_compile_units_beginEv'/>
<fun r='_ZNK4llvm6Module23debug_compile_units_endEv'/>
<fun r='_ZNK4llvm6Module19debug_compile_unitsEv'/>
<fun r='_ZN4llvm6Module31dropTriviallyDeadConstantArraysEv'/>
<fun r='_ZNK4llvm6Module5printERNS_11raw_ostreamEPNS_24AssemblyAnnotationWriterEbb'/>
<fun r='_ZNK4llvm6Module4dumpEv'/>
<fun r='_ZN4llvm6Module17dropAllReferencesEv'/>
<fun r='_ZNK4llvm6Module27getNumberRegisterParametersEv'/>
<fun r='_ZNK4llvm6Module15getDwarfVersionEv'/>
<fun r='_ZNK4llvm6Module15getCodeViewFlagEv'/>
<fun r='_ZNK4llvm6Module11getPICLevelEv'/>
<fun r='_ZN4llvm6Module11setPICLevelENS_8PICLevel5LevelE'/>
<fun r='_ZNK4llvm6Module11getPIELevelEv'/>
<fun r='_ZN4llvm6Module11setPIELevelENS_8PIELevel5LevelE'/>
<fun r='_ZNK4llvm6Module12getCodeModelEv'/>
<fun r='_ZN4llvm6Module12setCodeModelENS_9CodeModel5ModelE'/>
<fun r='_ZN4llvm6Module17setProfileSummaryEPNS_8MetadataENS_14ProfileSummary4KindE'/>
<fun r='_ZNK4llvm6Module17getProfileSummaryEb'/>
<fun r='_ZNK4llvm6Module24getSemanticInterpositionEv'/>
<fun r='_ZN4llvm6Module24setSemanticInterpositionEb'/>
<fun r='_ZNK4llvm6Module14getRtLibUseGOTEv'/>
<fun r='_ZN4llvm6Module14setRtLibUseGOTEv'/>
<fun r='_ZN4llvm6Module13setSDKVersionERKNS_12VersionTupleE'/>
<fun r='_ZNK4llvm6Module13getSDKVersionEv'/>
<fun r='_ZN4llvm6Module20setOwnedMemoryBufferESt10unique_ptrINS_12MemoryBufferESt14default_deleteIS2_EE'/>
<fun r='_ZN4llvm6Module28setPartialSampleProfileRatioERKNS_18ModuleSummaryIndexE'/>
<use f='halide/src/CodeGen_Internal.cpp' l='658' c='_ZN6Halide8Internal18get_target_optionsERKN4llvm6ModuleERNS1_13TargetOptionsERNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESD_'/>
<use f='halide/src/CodeGen_Internal.cpp' l='688' c='_ZN6Halide8Internal20clone_target_optionsERKN4llvm6ModuleERS2_'/>
<use f='halide/src/CodeGen_Internal.cpp' l='688' c='_ZN6Halide8Internal20clone_target_optionsERKN4llvm6ModuleERS2_'/>
<use f='halide/src/CodeGen_Internal.cpp' l='714' c='_ZN6Halide8Internal19make_target_machineERKN4llvm6ModuleE'/>
<use f='halide/src/CodeGen_Internal.cpp' l='751' c='_ZN6Halide8Internal13embed_bitcodeEPN4llvm6ModuleERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE'/>
<size>744</size>
<use f='halide/src/LLVM_Runtime_Linker.h' l='29' c='_ZN6Halide8Internal29get_initial_module_for_targetENS_6TargetEPN4llvm11LLVMContextEbb'/>
<use f='halide/src/LLVM_Runtime_Linker.h' l='32' c='_ZN6Halide8Internal33get_initial_module_for_ptx_deviceENS_6TargetEPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.h' l='35' c='_ZN6Halide8Internal21add_bitcode_to_moduleEPN4llvm11LLVMContextERNS1_6ModuleERKSt6vectorIhSaIhEERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE'/>
<use f='halide/src/LLVM_Runtime_Linker.h' l='40' c='_ZN6Halide8Internal26link_with_wasm_jit_runtimeEPN4llvm11LLVMContextERKNS_6TargetESt10unique_ptrINS1_6ModuleESt14default_deleteIS8_EE'/>
<use f='halide/src/LLVM_Runtime_Linker.h' l='41' c='_ZN6Halide8Internal26link_with_wasm_jit_runtimeEPN4llvm11LLVMContextERKNS_6TargetESt10unique_ptrINS1_6ModuleESt14default_deleteIS8_EE'/>
<use f='halide/src/MatlabWrapper.h' l='21' c='_ZN6Halide8Internal21define_matlab_wrapperEPN4llvm6ModuleEPNS1_8FunctionES5_'/>
<use f='halide/src/CodeGen_LLVM.cpp' l='40' c='_ZN6Halide12codegen_llvmERKNS_6ModuleERN4llvm11LLVMContextE'/>
<use f='halide/src/CodeGen_LLVM.cpp' l='403' c='_ZN6Halide8Internal12CodeGen_LLVM19compile_trampolinesERKNS_6TargetERN4llvm11LLVMContextERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKSt6ve2948072'/>
<use f='halide/src/CodeGen_LLVM.cpp' l='477' c='_ZN6Halide8Internal12CodeGen_LLVM7compileERKNS_6ModuleE'/>
<use f='halide/src/CodeGen_LLVM.cpp' l='515' c='_ZN6Halide8Internal12CodeGen_LLVM14finish_codegenEv'/>
<use f='halide/src/CodeGen_LLVM.cpp' l='1134' c='_ZN6Halide8Internal12CodeGen_LLVM15optimize_moduleEv'/>
<size>744</size>
<use f='halide/src/LLVM_Output.h' l='31' c='_ZN6Halide29compile_module_to_llvm_moduleERKNS_6ModuleERN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Output.h' l='38' c='_ZN6Halide29compile_llvm_module_to_objectERN4llvm6ModuleERNS0_17raw_pwrite_streamE'/>
<use f='halide/src/LLVM_Output.h' l='39' c='_ZN6Halide31compile_llvm_module_to_assemblyERN4llvm6ModuleERNS0_17raw_pwrite_streamE'/>
<use f='halide/src/LLVM_Output.h' l='44' c='_ZN6Halide35compile_llvm_module_to_llvm_bitcodeERN4llvm6ModuleERNS0_17raw_pwrite_streamE'/>
<use f='halide/src/LLVM_Output.h' l='45' c='_ZN6Halide36compile_llvm_module_to_llvm_assemblyERN4llvm6ModuleERNS0_17raw_pwrite_streamE'/>
<use f='halide/src/HexagonOffload.cpp' l='1003' c='_ZN6Halide8Internal39compile_module_to_hexagon_shared_objectERKNS_6ModuleE'/>
<size>744</size>
<use f='halide/src/JITModule.cpp' l='236' c='_ZN6Halide8Internal9JITModuleC1ERKNS_6ModuleERKNS0_11LoweredFuncERKSt6vectorIS1_SaIS1_EE'/>
<use f='halide/src/JITModule.cpp' l='245' c='_ZN6Halide8Internal9JITModule14compile_moduleESt10unique_ptrIN4llvm6ModuleESt14default_deleteIS4_EERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIc1691512'/>
<use f='halide/src/JITModule.cpp' l='369' c='_ZN6Halide8Internal9JITModule23make_trampolines_moduleERKNS_6TargetERKSt3mapINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEENS_9JITExternESt4less15121187'/>
<use f='halide/src/JITModule.cpp' l='651' c='_ZN6Halide8Internal12_GLOBAL__N_111make_moduleEPN4llvm6ModuleENS_6TargetENS1_11RuntimeKindERKSt6vectorINS0_9JITModuleESaIS8_EEb'/>
<use f='halide/src/JITModule.cpp' l='830' c='_ZN6Halide8Internal16JITSharedRuntime3getEPN4llvm6ModuleERKNS_6TargetEb'/>
<size>744</size>
<use f='halide/src/LLVM_Output.cpp' l='323' c='_ZN6Halide12_GLOBAL__N_112clone_moduleERKN4llvm6ModuleE'/>
<use f='halide/src/LLVM_Output.cpp' l='323' c='_ZN6Halide12_GLOBAL__N_112clone_moduleERKN4llvm6ModuleE'/>
<use f='halide/src/LLVM_Output.cpp' l='341' c='_ZN6Halide9emit_fileERKN4llvm6ModuleERNS0_17raw_pwrite_streamENS0_15CodeGenFileTypeE'/>
<use f='halide/src/LLVM_Output.cpp' l='349' c='_ZN6Halide9emit_fileERKN4llvm6ModuleERNS0_17raw_pwrite_streamENS0_15CodeGenFileTypeE'/>
<use f='halide/src/LLVM_Output.cpp' l='398' c='_ZN6Halide29compile_module_to_llvm_moduleERKNS_6ModuleERN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Output.cpp' l='402' c='_ZN6Halide29compile_llvm_module_to_objectERN4llvm6ModuleERNS0_17raw_pwrite_streamE'/>
<use f='halide/src/LLVM_Output.cpp' l='406' c='_ZN6Halide31compile_llvm_module_to_assemblyERN4llvm6ModuleERNS0_17raw_pwrite_streamE'/>
<use f='halide/src/LLVM_Output.cpp' l='410' c='_ZN6Halide35compile_llvm_module_to_llvm_bitcodeERN4llvm6ModuleERNS0_17raw_pwrite_streamE'/>
<use f='halide/src/LLVM_Output.cpp' l='414' c='_ZN6Halide36compile_llvm_module_to_llvm_assemblyERN4llvm6ModuleERNS0_17raw_pwrite_streamE'/>
<size>744</size>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='13' c='_ZN6Halide12_GLOBAL__N_118parse_bitcode_fileEN4llvm9StringRefEPNS1_11LLVMContextEPKc'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='24' c='_ZN6Halide12_GLOBAL__N_118parse_bitcode_fileEN4llvm9StringRefEPNS1_11LLVMContextEPKc'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_134get_initmod_alignment_128_32_debugEPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_134get_initmod_alignment_128_64_debugEPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_128get_initmod_alignment_128_32EPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_128get_initmod_alignment_128_64EPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='50' c='_ZN6Halide12_GLOBAL__N_125get_initmod_alignment_128EPN4llvm11LLVMContextEbb'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_133get_initmod_alignment_32_32_debugEPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_133get_initmod_alignment_32_64_debugEPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_127get_initmod_alignment_32_32EPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_127get_initmod_alignment_32_64EPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='50' c='_ZN6Halide12_GLOBAL__N_124get_initmod_alignment_32EPN4llvm11LLVMContextEbb'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_137get_initmod_allocation_cache_32_debugEPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_137get_initmod_allocation_cache_64_debugEPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_131get_initmod_allocation_cache_32EPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_131get_initmod_allocation_cache_64EPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='50' c='_ZN6Halide12_GLOBAL__N_128get_initmod_allocation_cacheEPN4llvm11LLVMContextEbb'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_133get_initmod_alignment_64_32_debugEPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_133get_initmod_alignment_64_64_debugEPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_127get_initmod_alignment_64_32EPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_127get_initmod_alignment_64_64EPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='50' c='_ZN6Halide12_GLOBAL__N_124get_initmod_alignment_64EPN4llvm11LLVMContextEbb'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_134get_initmod_android_clock_32_debugEPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_134get_initmod_android_clock_64_debugEPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_128get_initmod_android_clock_32EPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_128get_initmod_android_clock_64EPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='50' c='_ZN6Halide12_GLOBAL__N_125get_initmod_android_clockEPN4llvm11LLVMContextEbb'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_143get_initmod_android_host_cpu_count_32_debugEPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_143get_initmod_android_host_cpu_count_64_debugEPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_137get_initmod_android_host_cpu_count_32EPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_137get_initmod_android_host_cpu_count_64EPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='50' c='_ZN6Halide12_GLOBAL__N_134get_initmod_android_host_cpu_countEPN4llvm11LLVMContextEbb'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_131get_initmod_android_io_32_debugEPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_131get_initmod_android_io_64_debugEPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_125get_initmod_android_io_32EPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_125get_initmod_android_io_64EPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='50' c='_ZN6Halide12_GLOBAL__N_122get_initmod_android_ioEPN4llvm11LLVMContextEbb'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_136get_initmod_halide_buffer_t_32_debugEPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_136get_initmod_halide_buffer_t_64_debugEPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_130get_initmod_halide_buffer_t_32EPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_130get_initmod_halide_buffer_t_64EPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='50' c='_ZN6Halide12_GLOBAL__N_127get_initmod_halide_buffer_tEPN4llvm11LLVMContextEbb'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_126get_initmod_cache_32_debugEPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_126get_initmod_cache_64_debugEPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_120get_initmod_cache_32EPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_120get_initmod_cache_64EPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='50' c='_ZN6Halide12_GLOBAL__N_117get_initmod_cacheEPN4llvm11LLVMContextEbb'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_135get_initmod_can_use_target_32_debugEPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_135get_initmod_can_use_target_64_debugEPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_129get_initmod_can_use_target_32EPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_129get_initmod_can_use_target_64EPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='50' c='_ZN6Halide12_GLOBAL__N_126get_initmod_can_use_targetEPN4llvm11LLVMContextEbb'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_125get_initmod_cuda_32_debugEPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_125get_initmod_cuda_64_debugEPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_119get_initmod_cuda_32EPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_119get_initmod_cuda_64EPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='50' c='_ZN6Halide12_GLOBAL__N_116get_initmod_cudaEPN4llvm11LLVMContextEbb'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_132get_initmod_destructors_32_debugEPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_132get_initmod_destructors_64_debugEPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_126get_initmod_destructors_32EPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_126get_initmod_destructors_64EPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='50' c='_ZN6Halide12_GLOBAL__N_123get_initmod_destructorsEPN4llvm11LLVMContextEbb'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_137get_initmod_device_interface_32_debugEPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_137get_initmod_device_interface_64_debugEPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_131get_initmod_device_interface_32EPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_131get_initmod_device_interface_64EPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='50' c='_ZN6Halide12_GLOBAL__N_128get_initmod_device_interfaceEPN4llvm11LLVMContextEbb'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_127get_initmod_errors_32_debugEPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_127get_initmod_errors_64_debugEPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_121get_initmod_errors_32EPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_121get_initmod_errors_64EPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='50' c='_ZN6Halide12_GLOBAL__N_118get_initmod_errorsEPN4llvm11LLVMContextEbb'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_136get_initmod_fake_get_symbol_32_debugEPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_136get_initmod_fake_get_symbol_64_debugEPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_130get_initmod_fake_get_symbol_32EPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_130get_initmod_fake_get_symbol_64EPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='50' c='_ZN6Halide12_GLOBAL__N_127get_initmod_fake_get_symbolEPN4llvm11LLVMContextEbb'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_137get_initmod_fake_thread_pool_32_debugEPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_137get_initmod_fake_thread_pool_64_debugEPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_131get_initmod_fake_thread_pool_32EPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_131get_initmod_fake_thread_pool_64EPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='50' c='_ZN6Halide12_GLOBAL__N_128get_initmod_fake_thread_poolEPN4llvm11LLVMContextEbb'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_130get_initmod_float16_t_32_debugEPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_130get_initmod_float16_t_64_debugEPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_124get_initmod_float16_t_32EPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_124get_initmod_float16_t_64EPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='50' c='_ZN6Halide12_GLOBAL__N_121get_initmod_float16_tEPN4llvm11LLVMContextEbb'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_134get_initmod_fuchsia_clock_32_debugEPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_134get_initmod_fuchsia_clock_64_debugEPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_128get_initmod_fuchsia_clock_32EPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_128get_initmod_fuchsia_clock_64EPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='50' c='_ZN6Halide12_GLOBAL__N_125get_initmod_fuchsia_clockEPN4llvm11LLVMContextEbb'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_143get_initmod_fuchsia_host_cpu_count_32_debugEPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_143get_initmod_fuchsia_host_cpu_count_64_debugEPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_137get_initmod_fuchsia_host_cpu_count_32EPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_137get_initmod_fuchsia_host_cpu_count_64EPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='50' c='_ZN6Halide12_GLOBAL__N_134get_initmod_fuchsia_host_cpu_countEPN4llvm11LLVMContextEbb'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_134get_initmod_fuchsia_yield_32_debugEPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_134get_initmod_fuchsia_yield_64_debugEPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_128get_initmod_fuchsia_yield_32EPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_128get_initmod_fuchsia_yield_64EPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='50' c='_ZN6Halide12_GLOBAL__N_125get_initmod_fuchsia_yieldEPN4llvm11LLVMContextEbb'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_141get_initmod_gpu_device_selection_32_debugEPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_141get_initmod_gpu_device_selection_64_debugEPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_135get_initmod_gpu_device_selection_32EPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_135get_initmod_gpu_device_selection_64EPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='50' c='_ZN6Halide12_GLOBAL__N_132get_initmod_gpu_device_selectionEPN4llvm11LLVMContextEbb'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_132get_initmod_hexagon_dma_32_debugEPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_132get_initmod_hexagon_dma_64_debugEPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_126get_initmod_hexagon_dma_32EPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_126get_initmod_hexagon_dma_64EPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='50' c='_ZN6Halide12_GLOBAL__N_123get_initmod_hexagon_dmaEPN4llvm11LLVMContextEbb'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_133get_initmod_hexagon_host_32_debugEPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_133get_initmod_hexagon_host_64_debugEPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_127get_initmod_hexagon_host_32EPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_127get_initmod_hexagon_host_64EPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='50' c='_ZN6Halide12_GLOBAL__N_124get_initmod_hexagon_hostEPN4llvm11LLVMContextEbb'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_127get_initmod_ios_io_32_debugEPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_127get_initmod_ios_io_64_debugEPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_121get_initmod_ios_io_32EPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_121get_initmod_ios_io_64EPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='50' c='_ZN6Halide12_GLOBAL__N_118get_initmod_ios_ioEPN4llvm11LLVMContextEbb'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_132get_initmod_linux_clock_32_debugEPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_132get_initmod_linux_clock_64_debugEPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_126get_initmod_linux_clock_32EPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_126get_initmod_linux_clock_64EPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='50' c='_ZN6Halide12_GLOBAL__N_123get_initmod_linux_clockEPN4llvm11LLVMContextEbb'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_141get_initmod_linux_host_cpu_count_32_debugEPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_141get_initmod_linux_host_cpu_count_64_debugEPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_135get_initmod_linux_host_cpu_count_32EPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_135get_initmod_linux_host_cpu_count_64EPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='50' c='_ZN6Halide12_GLOBAL__N_132get_initmod_linux_host_cpu_countEPN4llvm11LLVMContextEbb'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_132get_initmod_linux_yield_32_debugEPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_132get_initmod_linux_yield_64_debugEPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_126get_initmod_linux_yield_32EPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_126get_initmod_linux_yield_64EPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='50' c='_ZN6Halide12_GLOBAL__N_123get_initmod_linux_yieldEPN4llvm11LLVMContextEbb'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_127get_initmod_matlab_32_debugEPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_127get_initmod_matlab_64_debugEPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_121get_initmod_matlab_32EPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_121get_initmod_matlab_64EPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='50' c='_ZN6Halide12_GLOBAL__N_118get_initmod_matlabEPN4llvm11LLVMContextEbb'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_129get_initmod_metadata_32_debugEPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_129get_initmod_metadata_64_debugEPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_123get_initmod_metadata_32EPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_123get_initmod_metadata_64EPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='50' c='_ZN6Halide12_GLOBAL__N_120get_initmod_metadataEPN4llvm11LLVMContextEbb'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_141get_initmod_module_aot_ref_count_32_debugEPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_141get_initmod_module_aot_ref_count_64_debugEPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_135get_initmod_module_aot_ref_count_32EPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_135get_initmod_module_aot_ref_count_64EPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='50' c='_ZN6Halide12_GLOBAL__N_132get_initmod_module_aot_ref_countEPN4llvm11LLVMContextEbb'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_141get_initmod_module_jit_ref_count_32_debugEPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_141get_initmod_module_jit_ref_count_64_debugEPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_135get_initmod_module_jit_ref_count_32EPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_135get_initmod_module_jit_ref_count_64EPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='50' c='_ZN6Halide12_GLOBAL__N_132get_initmod_module_jit_ref_countEPN4llvm11LLVMContextEbb'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_125get_initmod_msan_32_debugEPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_125get_initmod_msan_64_debugEPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_119get_initmod_msan_32EPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_119get_initmod_msan_64EPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='50' c='_ZN6Halide12_GLOBAL__N_116get_initmod_msanEPN4llvm11LLVMContextEbb'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_131get_initmod_msan_stubs_32_debugEPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_131get_initmod_msan_stubs_64_debugEPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_125get_initmod_msan_stubs_32EPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_125get_initmod_msan_stubs_64EPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='50' c='_ZN6Halide12_GLOBAL__N_122get_initmod_msan_stubsEPN4llvm11LLVMContextEbb'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_127get_initmod_opencl_32_debugEPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_127get_initmod_opencl_64_debugEPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_121get_initmod_opencl_32EPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_121get_initmod_opencl_64EPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='50' c='_ZN6Halide12_GLOBAL__N_118get_initmod_openclEPN4llvm11LLVMContextEbb'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_134get_initmod_openglcompute_32_debugEPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_134get_initmod_openglcompute_64_debugEPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_128get_initmod_openglcompute_32EPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_128get_initmod_openglcompute_64EPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='50' c='_ZN6Halide12_GLOBAL__N_125get_initmod_openglcomputeEPN4llvm11LLVMContextEbb'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_139get_initmod_opengl_egl_context_32_debugEPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_139get_initmod_opengl_egl_context_64_debugEPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_133get_initmod_opengl_egl_context_32EPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_133get_initmod_opengl_egl_context_64EPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='50' c='_ZN6Halide12_GLOBAL__N_130get_initmod_opengl_egl_contextEPN4llvm11LLVMContextEbb'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_139get_initmod_opengl_glx_context_32_debugEPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_139get_initmod_opengl_glx_context_64_debugEPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_133get_initmod_opengl_glx_context_32EPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_133get_initmod_opengl_glx_context_64EPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='50' c='_ZN6Halide12_GLOBAL__N_130get_initmod_opengl_glx_contextEPN4llvm11LLVMContextEbb'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_130get_initmod_osx_clock_32_debugEPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_130get_initmod_osx_clock_64_debugEPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_124get_initmod_osx_clock_32EPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_124get_initmod_osx_clock_64EPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='50' c='_ZN6Halide12_GLOBAL__N_121get_initmod_osx_clockEPN4llvm11LLVMContextEbb'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_135get_initmod_osx_get_symbol_32_debugEPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_135get_initmod_osx_get_symbol_64_debugEPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_129get_initmod_osx_get_symbol_32EPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_129get_initmod_osx_get_symbol_64EPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='50' c='_ZN6Halide12_GLOBAL__N_126get_initmod_osx_get_symbolEPN4llvm11LLVMContextEbb'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_139get_initmod_osx_host_cpu_count_32_debugEPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_139get_initmod_osx_host_cpu_count_64_debugEPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_133get_initmod_osx_host_cpu_count_32EPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_133get_initmod_osx_host_cpu_count_64EPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='50' c='_ZN6Halide12_GLOBAL__N_130get_initmod_osx_host_cpu_countEPN4llvm11LLVMContextEbb'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_139get_initmod_osx_opengl_context_32_debugEPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_139get_initmod_osx_opengl_context_64_debugEPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_133get_initmod_osx_opengl_context_32EPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_133get_initmod_osx_opengl_context_64EPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='50' c='_ZN6Halide12_GLOBAL__N_130get_initmod_osx_opengl_contextEPN4llvm11LLVMContextEbb'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_130get_initmod_osx_yield_32_debugEPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_130get_initmod_osx_yield_64_debugEPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_124get_initmod_osx_yield_32EPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_124get_initmod_osx_yield_64EPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='50' c='_ZN6Halide12_GLOBAL__N_121get_initmod_osx_yieldEPN4llvm11LLVMContextEbb'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_136get_initmod_posix_allocator_32_debugEPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_136get_initmod_posix_allocator_64_debugEPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_130get_initmod_posix_allocator_32EPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_130get_initmod_posix_allocator_64EPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='50' c='_ZN6Halide12_GLOBAL__N_127get_initmod_posix_allocatorEPN4llvm11LLVMContextEbb'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_132get_initmod_posix_clock_32_debugEPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_132get_initmod_posix_clock_64_debugEPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_126get_initmod_posix_clock_32EPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_126get_initmod_posix_clock_64EPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='50' c='_ZN6Halide12_GLOBAL__N_123get_initmod_posix_clockEPN4llvm11LLVMContextEbb'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_140get_initmod_posix_error_handler_32_debugEPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_140get_initmod_posix_error_handler_64_debugEPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_134get_initmod_posix_error_handler_32EPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_134get_initmod_posix_error_handler_64EPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='50' c='_ZN6Halide12_GLOBAL__N_131get_initmod_posix_error_handlerEPN4llvm11LLVMContextEbb'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_137get_initmod_posix_get_symbol_32_debugEPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_137get_initmod_posix_get_symbol_64_debugEPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_131get_initmod_posix_get_symbol_32EPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_131get_initmod_posix_get_symbol_64EPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='50' c='_ZN6Halide12_GLOBAL__N_128get_initmod_posix_get_symbolEPN4llvm11LLVMContextEbb'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_129get_initmod_posix_io_32_debugEPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_129get_initmod_posix_io_64_debugEPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_123get_initmod_posix_io_32EPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_123get_initmod_posix_io_64EPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='50' c='_ZN6Halide12_GLOBAL__N_120get_initmod_posix_ioEPN4llvm11LLVMContextEbb'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_132get_initmod_posix_print_32_debugEPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_132get_initmod_posix_print_64_debugEPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_126get_initmod_posix_print_32EPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_126get_initmod_posix_print_64EPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='50' c='_ZN6Halide12_GLOBAL__N_123get_initmod_posix_printEPN4llvm11LLVMContextEbb'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_134get_initmod_posix_threads_32_debugEPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_134get_initmod_posix_threads_64_debugEPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_128get_initmod_posix_threads_32EPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_128get_initmod_posix_threads_64EPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='50' c='_ZN6Halide12_GLOBAL__N_125get_initmod_posix_threadsEPN4llvm11LLVMContextEbb'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_139get_initmod_posix_threads_tsan_32_debugEPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_139get_initmod_posix_threads_tsan_64_debugEPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_133get_initmod_posix_threads_tsan_32EPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_133get_initmod_posix_threads_tsan_64EPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='50' c='_ZN6Halide12_GLOBAL__N_130get_initmod_posix_threads_tsanEPN4llvm11LLVMContextEbb'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_129get_initmod_prefetch_32_debugEPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_129get_initmod_prefetch_64_debugEPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_123get_initmod_prefetch_32EPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_123get_initmod_prefetch_64EPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='50' c='_ZN6Halide12_GLOBAL__N_120get_initmod_prefetchEPN4llvm11LLVMContextEbb'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_129get_initmod_profiler_32_debugEPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_129get_initmod_profiler_64_debugEPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_123get_initmod_profiler_32EPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_123get_initmod_profiler_64EPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='50' c='_ZN6Halide12_GLOBAL__N_120get_initmod_profilerEPN4llvm11LLVMContextEbb'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_137get_initmod_profiler_inlined_32_debugEPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_137get_initmod_profiler_inlined_64_debugEPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_131get_initmod_profiler_inlined_32EPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_131get_initmod_profiler_inlined_64EPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='50' c='_ZN6Halide12_GLOBAL__N_128get_initmod_profiler_inlinedEPN4llvm11LLVMContextEbb'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_132get_initmod_pseudostack_32_debugEPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_132get_initmod_pseudostack_64_debugEPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_126get_initmod_pseudostack_32EPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_126get_initmod_pseudostack_64EPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='50' c='_ZN6Halide12_GLOBAL__N_123get_initmod_pseudostackEPN4llvm11LLVMContextEbb'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_135get_initmod_qurt_allocator_32_debugEPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_135get_initmod_qurt_allocator_64_debugEPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_129get_initmod_qurt_allocator_32EPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_129get_initmod_qurt_allocator_64EPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='50' c='_ZN6Halide12_GLOBAL__N_126get_initmod_qurt_allocatorEPN4llvm11LLVMContextEbb'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_144get_initmod_hexagon_cache_allocator_32_debugEPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_144get_initmod_hexagon_cache_allocator_64_debugEPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_138get_initmod_hexagon_cache_allocator_32EPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_138get_initmod_hexagon_cache_allocator_64EPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='50' c='_ZN6Halide12_GLOBAL__N_135get_initmod_hexagon_cache_allocatorEPN4llvm11LLVMContextEbb'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_137get_initmod_hexagon_dma_pool_32_debugEPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_137get_initmod_hexagon_dma_pool_64_debugEPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_131get_initmod_hexagon_dma_pool_32EPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_131get_initmod_hexagon_dma_pool_64EPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='50' c='_ZN6Halide12_GLOBAL__N_128get_initmod_hexagon_dma_poolEPN4llvm11LLVMContextEbb'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_129get_initmod_qurt_hvx_32_debugEPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_129get_initmod_qurt_hvx_64_debugEPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_123get_initmod_qurt_hvx_32EPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_123get_initmod_qurt_hvx_64EPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='50' c='_ZN6Halide12_GLOBAL__N_120get_initmod_qurt_hvxEPN4llvm11LLVMContextEbb'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_134get_initmod_qurt_hvx_vtcm_32_debugEPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_134get_initmod_qurt_hvx_vtcm_64_debugEPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_128get_initmod_qurt_hvx_vtcm_32EPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_128get_initmod_qurt_hvx_vtcm_64EPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='50' c='_ZN6Halide12_GLOBAL__N_125get_initmod_qurt_hvx_vtcmEPN4llvm11LLVMContextEbb'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_135get_initmod_qurt_init_fini_32_debugEPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_135get_initmod_qurt_init_fini_64_debugEPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_129get_initmod_qurt_init_fini_32EPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_129get_initmod_qurt_init_fini_64EPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='50' c='_ZN6Halide12_GLOBAL__N_126get_initmod_qurt_init_finiEPN4llvm11LLVMContextEbb'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_133get_initmod_qurt_threads_32_debugEPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_133get_initmod_qurt_threads_64_debugEPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_127get_initmod_qurt_threads_32EPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_127get_initmod_qurt_threads_64EPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='50' c='_ZN6Halide12_GLOBAL__N_124get_initmod_qurt_threadsEPN4llvm11LLVMContextEbb'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_138get_initmod_qurt_threads_tsan_32_debugEPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_138get_initmod_qurt_threads_tsan_64_debugEPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_132get_initmod_qurt_threads_tsan_32EPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_132get_initmod_qurt_threads_tsan_64EPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='50' c='_ZN6Halide12_GLOBAL__N_129get_initmod_qurt_threads_tsanEPN4llvm11LLVMContextEbb'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_131get_initmod_qurt_yield_32_debugEPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_131get_initmod_qurt_yield_64_debugEPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_125get_initmod_qurt_yield_32EPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_125get_initmod_qurt_yield_64EPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='50' c='_ZN6Halide12_GLOBAL__N_122get_initmod_qurt_yieldEPN4llvm11LLVMContextEbb'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_132get_initmod_runtime_api_32_debugEPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_132get_initmod_runtime_api_64_debugEPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_126get_initmod_runtime_api_32EPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_126get_initmod_runtime_api_64EPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='50' c='_ZN6Halide12_GLOBAL__N_123get_initmod_runtime_apiEPN4llvm11LLVMContextEbb'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_124get_initmod_ssp_32_debugEPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_124get_initmod_ssp_64_debugEPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_118get_initmod_ssp_32EPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_118get_initmod_ssp_64EPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='50' c='_ZN6Halide12_GLOBAL__N_115get_initmod_sspEPN4llvm11LLVMContextEbb'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_130get_initmod_to_string_32_debugEPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_130get_initmod_to_string_64_debugEPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_124get_initmod_to_string_32EPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_124get_initmod_to_string_64EPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='50' c='_ZN6Halide12_GLOBAL__N_121get_initmod_to_stringEPN4llvm11LLVMContextEbb'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_133get_initmod_trace_helper_32_debugEPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_133get_initmod_trace_helper_64_debugEPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_127get_initmod_trace_helper_32EPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_127get_initmod_trace_helper_64EPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='50' c='_ZN6Halide12_GLOBAL__N_124get_initmod_trace_helperEPN4llvm11LLVMContextEbb'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_128get_initmod_tracing_32_debugEPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_128get_initmod_tracing_64_debugEPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_122get_initmod_tracing_32EPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_122get_initmod_tracing_64EPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='50' c='_ZN6Halide12_GLOBAL__N_119get_initmod_tracingEPN4llvm11LLVMContextEbb'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_134get_initmod_windows_clock_32_debugEPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_134get_initmod_windows_clock_64_debugEPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_128get_initmod_windows_clock_32EPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_128get_initmod_windows_clock_64EPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='50' c='_ZN6Halide12_GLOBAL__N_125get_initmod_windows_clockEPN4llvm11LLVMContextEbb'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_133get_initmod_windows_cuda_32_debugEPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_133get_initmod_windows_cuda_64_debugEPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_127get_initmod_windows_cuda_32EPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_127get_initmod_windows_cuda_64EPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='50' c='_ZN6Halide12_GLOBAL__N_124get_initmod_windows_cudaEPN4llvm11LLVMContextEbb'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_139get_initmod_windows_get_symbol_32_debugEPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_139get_initmod_windows_get_symbol_64_debugEPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_133get_initmod_windows_get_symbol_32EPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_133get_initmod_windows_get_symbol_64EPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='50' c='_ZN6Halide12_GLOBAL__N_130get_initmod_windows_get_symbolEPN4llvm11LLVMContextEbb'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_131get_initmod_windows_io_32_debugEPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_131get_initmod_windows_io_64_debugEPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_125get_initmod_windows_io_32EPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_125get_initmod_windows_io_64EPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='50' c='_ZN6Halide12_GLOBAL__N_122get_initmod_windows_ioEPN4llvm11LLVMContextEbb'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_135get_initmod_windows_opencl_32_debugEPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_135get_initmod_windows_opencl_64_debugEPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_129get_initmod_windows_opencl_32EPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_129get_initmod_windows_opencl_64EPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='50' c='_ZN6Halide12_GLOBAL__N_126get_initmod_windows_openclEPN4llvm11LLVMContextEbb'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_137get_initmod_windows_profiler_32_debugEPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_137get_initmod_windows_profiler_64_debugEPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_131get_initmod_windows_profiler_32EPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_131get_initmod_windows_profiler_64EPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='50' c='_ZN6Halide12_GLOBAL__N_128get_initmod_windows_profilerEPN4llvm11LLVMContextEbb'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_136get_initmod_windows_threads_32_debugEPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_136get_initmod_windows_threads_64_debugEPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_130get_initmod_windows_threads_32EPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_130get_initmod_windows_threads_64EPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='50' c='_ZN6Halide12_GLOBAL__N_127get_initmod_windows_threadsEPN4llvm11LLVMContextEbb'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_141get_initmod_windows_threads_tsan_32_debugEPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_141get_initmod_windows_threads_tsan_64_debugEPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_135get_initmod_windows_threads_tsan_32EPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_135get_initmod_windows_threads_tsan_64EPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='50' c='_ZN6Halide12_GLOBAL__N_132get_initmod_windows_threads_tsanEPN4llvm11LLVMContextEbb'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_134get_initmod_windows_yield_32_debugEPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_134get_initmod_windows_yield_64_debugEPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_128get_initmod_windows_yield_32EPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_128get_initmod_windows_yield_64EPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='50' c='_ZN6Halide12_GLOBAL__N_125get_initmod_windows_yieldEPN4llvm11LLVMContextEbb'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_138get_initmod_write_debug_image_32_debugEPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_138get_initmod_write_debug_image_64_debugEPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_132get_initmod_write_debug_image_32EPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_132get_initmod_write_debug_image_64EPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='50' c='_ZN6Halide12_GLOBAL__N_129get_initmod_write_debug_imageEPN4llvm11LLVMContextEbb'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_125get_initmod_posix_math_llEPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_125get_initmod_win32_math_llEPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_122get_initmod_ptx_dev_llEPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_126get_initmod_metal_32_debugEPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_126get_initmod_metal_64_debugEPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_120get_initmod_metal_32EPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_120get_initmod_metal_64EPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='50' c='_ZN6Halide12_GLOBAL__N_117get_initmod_metalEPN4llvm11LLVMContextEbb'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_135get_initmod_metal_objc_arm_32_debugEPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_135get_initmod_metal_objc_arm_64_debugEPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_129get_initmod_metal_objc_arm_32EPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_129get_initmod_metal_objc_arm_64EPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='50' c='_ZN6Halide12_GLOBAL__N_126get_initmod_metal_objc_armEPN4llvm11LLVMContextEbb'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_135get_initmod_metal_objc_x86_32_debugEPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_135get_initmod_metal_objc_x86_64_debugEPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_129get_initmod_metal_objc_x86_32EPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_129get_initmod_metal_objc_x86_64EPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='50' c='_ZN6Halide12_GLOBAL__N_126get_initmod_metal_objc_x86EPN4llvm11LLVMContextEbb'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_118get_initmod_arm_llEPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_126get_initmod_arm_no_neon_llEPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_137get_initmod_arm_cpu_features_32_debugEPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_137get_initmod_arm_cpu_features_64_debugEPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_131get_initmod_arm_cpu_features_32EPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_131get_initmod_arm_cpu_features_64EPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='50' c='_ZN6Halide12_GLOBAL__N_128get_initmod_arm_cpu_featuresEPN4llvm11LLVMContextEbb'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_122get_initmod_aarch64_llEPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_141get_initmod_aarch64_cpu_features_32_debugEPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_141get_initmod_aarch64_cpu_features_64_debugEPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_135get_initmod_aarch64_cpu_features_32EPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_135get_initmod_aarch64_cpu_features_64EPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='50' c='_ZN6Halide12_GLOBAL__N_132get_initmod_aarch64_cpu_featuresEPN4llvm11LLVMContextEbb'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_129get_initmod_ptx_compute_20_llEPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_129get_initmod_ptx_compute_30_llEPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_129get_initmod_ptx_compute_35_llEPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_145get_initmod_windows_d3d12compute_x86_32_debugEPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_145get_initmod_windows_d3d12compute_x86_64_debugEPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_139get_initmod_windows_d3d12compute_x86_32EPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_139get_initmod_windows_d3d12compute_x86_64EPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='50' c='_ZN6Halide12_GLOBAL__N_136get_initmod_windows_d3d12compute_x86EPN4llvm11LLVMContextEbb'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_139get_initmod_windows_d3d12compute_arm_32EPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_145get_initmod_windows_d3d12compute_arm_32_debugEPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_139get_initmod_windows_d3d12compute_arm_64EPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_145get_initmod_windows_d3d12compute_arm_64_debugEPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='50' c='_ZN6Halide12_GLOBAL__N_136get_initmod_windows_d3d12compute_armEPN4llvm11LLVMContextEbb'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_125get_initmod_x86_avx512_llEPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_123get_initmod_x86_avx2_llEPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_122get_initmod_x86_avx_llEPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_118get_initmod_x86_llEPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_124get_initmod_x86_sse41_llEPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_137get_initmod_x86_cpu_features_32_debugEPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_137get_initmod_x86_cpu_features_64_debugEPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_131get_initmod_x86_cpu_features_32EPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_131get_initmod_x86_cpu_features_64EPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='50' c='_ZN6Halide12_GLOBAL__N_128get_initmod_x86_cpu_featuresEPN4llvm11LLVMContextEbb'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_119get_initmod_mips_llEPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_138get_initmod_mips_cpu_features_32_debugEPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_138get_initmod_mips_cpu_features_64_debugEPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_132get_initmod_mips_cpu_features_32EPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_132get_initmod_mips_cpu_features_64EPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='50' c='_ZN6Halide12_GLOBAL__N_129get_initmod_mips_cpu_featuresEPN4llvm11LLVMContextEbb'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_122get_initmod_powerpc_llEPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_141get_initmod_powerpc_cpu_features_32_debugEPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_141get_initmod_powerpc_cpu_features_64_debugEPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_135get_initmod_powerpc_cpu_features_32EPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_135get_initmod_powerpc_cpu_features_64EPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='50' c='_ZN6Halide12_GLOBAL__N_132get_initmod_powerpc_cpu_featuresEPN4llvm11LLVMContextEbb'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_122get_initmod_hvx_128_llEPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_141get_initmod_hexagon_cpu_features_32_debugEPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_141get_initmod_hexagon_cpu_features_64_debugEPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_135get_initmod_hexagon_cpu_features_32EPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_135get_initmod_hexagon_cpu_features_64EPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='50' c='_ZN6Halide12_GLOBAL__N_132get_initmod_hexagon_cpu_featuresEPN4llvm11LLVMContextEbb'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_138get_initmod_wasm_cpu_features_32_debugEPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_138get_initmod_wasm_cpu_features_64_debugEPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_132get_initmod_wasm_cpu_features_32EPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_132get_initmod_wasm_cpu_features_64EPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='50' c='_ZN6Halide12_GLOBAL__N_129get_initmod_wasm_cpu_featuresEPN4llvm11LLVMContextEbb'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_124get_initmod_wasm_math_llEPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_139get_initmod_riscv_cpu_features_32_debugEPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_139get_initmod_riscv_cpu_features_64_debugEPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_133get_initmod_riscv_cpu_features_32EPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='33' c='_ZN6Halide12_GLOBAL__N_133get_initmod_riscv_cpu_features_64EPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='50' c='_ZN6Halide12_GLOBAL__N_130get_initmod_riscv_cpu_featuresEPN4llvm11LLVMContextEbb'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='541' c='_ZN6Halide12_GLOBAL__N_112link_modulesERSt6vectorISt10unique_ptrIN4llvm6ModuleESt14default_deleteIS4_EESaIS7_EENS_6TargetEb'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='671' c='_ZN6Halide8Internal24undo_win32_name_manglingEPN4llvm6ModuleE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='712' c='_ZN6Halide8Internal28add_underscore_to_posix_callEPN4llvm8CallInstEPNS1_8FunctionEPNS1_6ModuleE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='728' c='_ZN6Halide8Internal41add_underscores_to_posix_calls_on_windowsEPN4llvm6ModuleE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='749' c='_ZN6Halide8Internal26link_with_wasm_jit_runtimeEPN4llvm11LLVMContextERKNS_6TargetESt10unique_ptrINS1_6ModuleESt14default_deleteIS8_EE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='750' c='_ZN6Halide8Internal26link_with_wasm_jit_runtimeEPN4llvm11LLVMContextERKNS_6TargetESt10unique_ptrINS1_6ModuleESt14default_deleteIS8_EE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='756' c='_ZN6Halide8Internal26link_with_wasm_jit_runtimeEPN4llvm11LLVMContextERKNS_6TargetESt10unique_ptrINS1_6ModuleESt14default_deleteIS8_EE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='784' c='_ZN6Halide8Internal29get_initial_module_for_targetENS_6TargetEPN4llvm11LLVMContextEbb'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='815' c='_ZN6Halide8Internal29get_initial_module_for_targetENS_6TargetEPN4llvm11LLVMContextEbb'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='1203' c='_ZN6Halide8Internal33get_initial_module_for_ptx_deviceENS_6TargetEPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='1204' c='_ZN6Halide8Internal33get_initial_module_for_ptx_deviceENS_6TargetEPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='1207' c='_ZN6Halide8Internal33get_initial_module_for_ptx_deviceENS_6TargetEPN4llvm11LLVMContextE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='1257' c='_ZN6Halide8Internal21add_bitcode_to_moduleEPN4llvm11LLVMContextERNS1_6ModuleERKSt6vectorIhSaIhEERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE'/>
<use f='halide/src/LLVM_Runtime_Linker.cpp' l='1260' c='_ZN6Halide8Internal21add_bitcode_to_moduleEPN4llvm11LLVMContextERNS1_6ModuleERKSt6vectorIhSaIhEERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE'/>
<size>744</size>
<use f='halide/src/MatlabWrapper.cpp' l='10' c='_ZN6Halide8Internal21define_matlab_wrapperEPN4llvm6ModuleEPNS1_8FunctionES5_'/>
<size>744</size>
<use f='halide/src/Module.cpp' l='483' c='_ZNK6Halide6Module17compile_to_bufferEv'/>
<use f='halide/src/Module.cpp' l='589' c='_ZNK6Halide6Module7compileERKSt3mapINS_6OutputENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESt4lessIS2_ESaISt4pairIKS2_S8_EEE'/>
<size>744</size>
