<dec f='halide/llvm-install/include/llvm/IR/DebugInfoMetadata.h' l='1261' type='uint8_t'/>
<use f='halide/llvm-install/include/llvm/IR/DebugInfoMetadata.h' l='1267' u='w' c='_ZN4llvm16DISubroutineTypeC1ERNS_11LLVMContextENS_8Metadata11StorageTypeENS_6DINode7DIFlagsEhNS_8ArrayRefIPS3_EE'/>
<use f='halide/llvm-install/include/llvm/IR/DebugInfoMetadata.h' l='1295' u='r' c='_ZNK4llvm16DISubroutineType5getCCEv'/>
<offset>416</offset>
<doc f='halide/llvm-install/include/llvm/IR/DebugInfoMetadata.h' l='1259'>/// The calling convention used with DW_AT_calling_convention. Actually of
  /// type dwarf::CallingConvention.</doc>
