<dec f='halide/llvm-install/include/llvm/ADT/iterator.h' l='213' type='WrappedIteratorT'/>
<use f='halide/llvm-install/include/llvm/ADT/iterator.h' l='217' u='w' c='_ZN4llvm21iterator_adaptor_baseC1ET0_'/>
<use f='halide/llvm-install/include/llvm/ADT/iterator.h' l='222' u='a' c='_ZNK4llvm21iterator_adaptor_base7wrappedEv'/>
<use f='halide/llvm-install/include/llvm/ADT/iterator.h' l='231' u='w' c='_ZN4llvm21iterator_adaptor_basepLET3_'/>
<use f='halide/llvm-install/include/llvm/ADT/iterator.h' l='238' u='w' c='_ZN4llvm21iterator_adaptor_basemIET3_'/>
<use f='halide/llvm-install/include/llvm/ADT/iterator.h' l='246' c='_ZNK4llvm21iterator_adaptor_basemiERKT_'/>
<use f='halide/llvm-install/include/llvm/ADT/iterator.h' l='253' u='w' c='_ZN4llvm21iterator_adaptor_baseppEv'/>
<use f='halide/llvm-install/include/llvm/ADT/iterator.h' l='261' u='w' c='_ZN4llvm21iterator_adaptor_basemmEv'/>
<use f='halide/llvm-install/include/llvm/ADT/iterator.h' l='277' c='_ZNK4llvm21iterator_adaptor_basedeEv'/>
<use f='halide/llvm-install/include/llvm/IR/User.h' l='256' u='r' c='_ZNK4llvm4User17value_op_iteratordeEv'/>
<use f='halide/llvm-install/include/llvm/IR/User.h' l='277' u='r' c='_ZNK4llvm4User23const_value_op_iteratordeEv'/>
<use f='halide/llvm-install/include/llvm/Analysis/LazyCallGraph.h' l='207' u='r' c='_ZN4llvm13LazyCallGraph12EdgeSequence8iteratorC1EPNS0_4EdgeES4_'/>
<use f='halide/llvm-install/include/llvm/Analysis/LazyCallGraph.h' l='207' u='r' c='_ZN4llvm13LazyCallGraph12EdgeSequence8iteratorC1EPNS0_4EdgeES4_'/>
<use f='halide/llvm-install/include/llvm/Analysis/LazyCallGraph.h' l='208' u='w' c='_ZN4llvm13LazyCallGraph12EdgeSequence8iteratorC1EPNS0_4EdgeES4_'/>
<use f='halide/llvm-install/include/llvm/Analysis/LazyCallGraph.h' l='217' u='w' c='_ZN4llvm13LazyCallGraph12EdgeSequence8iteratorppEv'/>
<use f='halide/llvm-install/include/llvm/Analysis/LazyCallGraph.h' l='218' u='r' c='_ZN4llvm13LazyCallGraph12EdgeSequence8iteratorppEv'/>
<use f='halide/llvm-install/include/llvm/Analysis/LazyCallGraph.h' l='218' u='r' c='_ZN4llvm13LazyCallGraph12EdgeSequence8iteratorppEv'/>
<use f='halide/llvm-install/include/llvm/Analysis/LazyCallGraph.h' l='237' u='r' c='_ZN4llvm13LazyCallGraph12EdgeSequence13call_iterator17advanceToNextEdgeEv'/>
<use f='halide/llvm-install/include/llvm/Analysis/LazyCallGraph.h' l='237' u='r' c='_ZN4llvm13LazyCallGraph12EdgeSequence13call_iterator17advanceToNextEdgeEv'/>
<use f='halide/llvm-install/include/llvm/Analysis/LazyCallGraph.h' l='237' u='r' c='_ZN4llvm13LazyCallGraph12EdgeSequence13call_iterator17advanceToNextEdgeEv'/>
<use f='halide/llvm-install/include/llvm/Analysis/LazyCallGraph.h' l='238' u='w' c='_ZN4llvm13LazyCallGraph12EdgeSequence13call_iterator17advanceToNextEdgeEv'/>
<use f='halide/llvm-install/include/llvm/Analysis/LazyCallGraph.h' l='252' u='w' c='_ZN4llvm13LazyCallGraph12EdgeSequence13call_iteratorppEv'/>
<use f='halide/llvm-install/include/llvm/IR/Instructions.h' l='3054' u='m' c='_ZNK4llvm10BranchInst16succ_op_iteratordeEv'/>
<use f='halide/llvm-install/include/llvm/IR/Instructions.h' l='3067' u='m' c='_ZNK4llvm10BranchInst22const_succ_op_iteratordeEv'/>
<use f='halide/llvm-install/include/llvm/IR/Instructions.h' l='3605' u='m' c='_ZNK4llvm14IndirectBrInst16succ_op_iteratordeEv'/>
<use f='halide/llvm-install/include/llvm/IR/Instructions.h' l='3618' u='m' c='_ZNK4llvm14IndirectBrInst22const_succ_op_iteratordeEv'/>
