<dec f='halide/llvm-install/include/llvm/IR/Instruction.def' l='149' type='15'/>
<use f='halide/llvm-install/include/llvm/IR/Instruction.def' l='149' u='r' c='_ZN4llvm14BinaryOperator9CreateSubEPNS_5ValueES2_RKNS_5TwineE'/>
<use f='halide/llvm-install/include/llvm/IR/Instruction.def' l='149' u='r' c='_ZN4llvm14BinaryOperator9CreateSubEPNS_5ValueES2_RKNS_5TwineEPNS_10BasicBlockE'/>
<use f='halide/llvm-install/include/llvm/IR/Instruction.def' l='149' u='r' c='_ZN4llvm14BinaryOperator9CreateSubEPNS_5ValueES2_RKNS_5TwineEPNS_11InstructionE'/>
<use f='halide/llvm-install/include/llvm/IR/InstrTypes.h' l='359' u='r' c='_ZN4llvm14BinaryOperator12CreateNSWSubEPNS_5ValueES2_RKNS_5TwineE'/>
<use f='halide/llvm-install/include/llvm/IR/InstrTypes.h' l='359' u='r' c='_ZN4llvm14BinaryOperator12CreateNSWSubEPNS_5ValueES2_RKNS_5TwineEPNS_10BasicBlockE'/>
<use f='halide/llvm-install/include/llvm/IR/InstrTypes.h' l='359' u='r' c='_ZN4llvm14BinaryOperator12CreateNSWSubEPNS_5ValueES2_RKNS_5TwineEPNS_11InstructionE'/>
<use f='halide/llvm-install/include/llvm/IR/InstrTypes.h' l='360' u='r' c='_ZN4llvm14BinaryOperator12CreateNUWSubEPNS_5ValueES2_RKNS_5TwineE'/>
<use f='halide/llvm-install/include/llvm/IR/InstrTypes.h' l='360' u='r' c='_ZN4llvm14BinaryOperator12CreateNUWSubEPNS_5ValueES2_RKNS_5TwineEPNS_10BasicBlockE'/>
<use f='halide/llvm-install/include/llvm/IR/InstrTypes.h' l='360' u='r' c='_ZN4llvm14BinaryOperator12CreateNUWSubEPNS_5ValueES2_RKNS_5TwineEPNS_11InstructionE'/>
<use f='halide/llvm-install/include/llvm/IR/Operator.h' l='102' u='r' c='_ZN4llvm25OverflowingBinaryOperator7classofEPKNS_11InstructionE'/>
<use f='halide/llvm-install/include/llvm/IR/Operator.h' l='108' u='r' c='_ZN4llvm25OverflowingBinaryOperator7classofEPKNS_12ConstantExprE'/>
<use f='halide/llvm-install/include/llvm/IR/Operator.h' l='430'/>
<use f='halide/llvm-install/include/llvm/IR/IRBuilder.h' l='1294' u='r' c='_ZN4llvm13IRBuilderBase9CreateSubEPNS_5ValueES2_RKNS_5TwineEbb'/>
