<dec f='halide/llvm-install/include/llvm/Analysis/LazyCallGraph.h' l='233' type='VectorImplT::iterator'/>
<use f='halide/llvm-install/include/llvm/Analysis/LazyCallGraph.h' l='237' u='r' c='_ZN4llvm13LazyCallGraph12EdgeSequence13call_iterator17advanceToNextEdgeEv'/>
<use f='halide/llvm-install/include/llvm/Analysis/LazyCallGraph.h' l='243' u='w' c='_ZN4llvm13LazyCallGraph12EdgeSequence13call_iteratorC1EPNS0_4EdgeES4_'/>
<offset>64</offset>
