<dec f='halide/llvm-install/include/llvm/Support/raw_ostream.h' l='691' type='std::unique_ptr&lt;raw_ostream&gt;'/>
<use f='halide/llvm-install/include/llvm/Support/raw_ostream.h' l='698' u='w' c='_ZN4llvm21buffer_unique_ostreamC1ESt10unique_ptrINS_11raw_ostreamESt14default_deleteIS2_EE'/>
<use f='halide/llvm-install/include/llvm/Support/raw_ostream.h' l='699' u='m' c='_ZN4llvm21buffer_unique_ostreamD1Ev'/>
<offset>576</offset>
