<use f='halide/llvm-install/include/llvm/Analysis/LazyCallGraph.h' l='324' u='r' c='_ZNK4llvm13LazyCallGraph4Node8getGraphEv'/>
<use f='halide/llvm-install/include/llvm/Analysis/LazyCallGraph.h' l='345' u='r' c='_ZNK4llvm13LazyCallGraph4Node6isDeadEv'/>
<dec f='halide/llvm-install/include/llvm/Analysis/LazyCallGraph.h' l='376' type='llvm::LazyCallGraph *'/>
<use f='halide/llvm-install/include/llvm/Analysis/LazyCallGraph.h' l='389' u='w' c='_ZN4llvm13LazyCallGraph4NodeC1ERS0_RNS_8FunctionE'/>
<offset>0</offset>
