<dec f='halide/llvm-install/include/llvm/IR/Metadata.h' l='343' type='llvm::Value *'/>
<use f='halide/llvm-install/include/llvm/IR/Metadata.h' l='352' u='w' c='_ZN4llvm15ValueAsMetadataC1EjPNS_5ValueE'/>
<use f='halide/llvm-install/include/llvm/IR/Metadata.h' l='379' u='r' c='_ZNK4llvm15ValueAsMetadata8getValueEv'/>
<use f='halide/llvm-install/include/llvm/IR/Metadata.h' l='380' u='r' c='_ZNK4llvm15ValueAsMetadata7getTypeEv'/>
<use f='halide/llvm-install/include/llvm/IR/Metadata.h' l='381' u='r' c='_ZNK4llvm15ValueAsMetadata10getContextEv'/>
<offset>1024</offset>
