<dec f='halide/llvm-install/include/llvm/Analysis/CallGraphSCCPass.h' l='88' type='const llvm::CallGraph &amp;'/>
<use f='halide/llvm-install/include/llvm/Analysis/CallGraphSCCPass.h' l='93' u='w' c='_ZN4llvm12CallGraphSCCC1ERNS_9CallGraphEPv'/>
<use f='halide/llvm-install/include/llvm/Analysis/CallGraphSCCPass.h' l='115' u='a' c='_ZN4llvm12CallGraphSCC12getCallGraphEv'/>
<offset>0</offset>
<doc f='halide/llvm-install/include/llvm/Analysis/CallGraphSCCPass.h' l='88'>// The call graph for this SCC.</doc>
