<use f='halide/llvm-install/include/llvm/IR/DiagnosticInfo.h' l='290' u='w' c='_ZN4llvm27DiagnosticInfoSampleProfileC1ENS_9StringRefEjRKNS_5TwineENS_18DiagnosticSeverityE'/>
<use f='halide/llvm-install/include/llvm/IR/DiagnosticInfo.h' l='294' u='w' c='_ZN4llvm27DiagnosticInfoSampleProfileC1ENS_9StringRefERKNS_5TwineENS_18DiagnosticSeverityE'/>
<use f='halide/llvm-install/include/llvm/IR/DiagnosticInfo.h' l='297' u='w' c='_ZN4llvm27DiagnosticInfoSampleProfileC1ERKNS_5TwineENS_18DiagnosticSeverityE'/>
<use f='halide/llvm-install/include/llvm/IR/DiagnosticInfo.h' l='308' u='a' c='_ZNK4llvm27DiagnosticInfoSampleProfile6getMsgEv'/>
<dec f='halide/llvm-install/include/llvm/IR/DiagnosticInfo.h' l='319' type='const llvm::Twine &amp;'/>
<offset>320</offset>
<doc f='halide/llvm-install/include/llvm/IR/DiagnosticInfo.h' l='318'>/// Message to report.</doc>
