<dec f='halide/llvm-install/include/llvm/IR/DiagnosticInfo.h' l='993' type='llvm::Twine'/>
<use f='halide/llvm-install/include/llvm/IR/DiagnosticInfo.h' l='1007' u='w' c='_ZN4llvm25DiagnosticInfoUnsupportedC1ERKNS_8FunctionERKNS_5TwineERKNS_18DiagnosticLocationENS_18DiagnosticSeverityE'/>
<use f='halide/llvm-install/include/llvm/IR/DiagnosticInfo.h' l='1013' u='a' c='_ZNK4llvm25DiagnosticInfoUnsupported10getMessageEv'/>
<offset>320</offset>
