<dec f='halide/llvm-install/include/llvm/Support/raw_ostream.h' l='608' type='std::string &amp;'/>
<use f='halide/llvm-install/include/llvm/Support/raw_ostream.h' l='615' u='m' c='_ZNK4llvm18raw_string_ostream11current_posEv'/>
<use f='halide/llvm-install/include/llvm/Support/raw_ostream.h' l='618' u='w' c='_ZN4llvm18raw_string_ostreamC1ERNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE'/>
<use f='halide/llvm-install/include/llvm/Support/raw_ostream.h' l='627' u='a' c='_ZN4llvm18raw_string_ostream3strB5cxx11Ev'/>
<offset>512</offset>
