<use f='halide/llvm-install/include/llvm/Support/YAMLTraits.h' l='315'/>
<use f='halide/llvm-install/include/llvm/Support/YAMLTraits.h' l='331'/>
<use f='halide/llvm-install/include/llvm/Support/YAMLTraits.h' l='400'/>
<use f='halide/llvm-install/include/llvm/Support/YAMLTraits.h' l='414'/>
<use f='halide/llvm-install/include/llvm/Support/YAMLTraits.h' l='426'/>
<use f='halide/llvm-install/include/llvm/Support/YAMLTraits.h' l='440'/>
<use f='halide/llvm-install/include/llvm/Support/YAMLTraits.h' l='454'/>
<use f='halide/llvm-install/include/llvm/Support/YAMLTraits.h' l='469'/>
<use f='halide/llvm-install/include/llvm/Support/YAMLTraits.h' l='518'/>
<def f='halide/llvm-install/include/llvm/Support/YAMLTraits.h' l='751' ll='940'/>
<use f='halide/llvm-install/include/llvm/Support/YAMLTraits.h' l='945' c='_ZN4llvm4yaml6detail9doMappingERNS0_2IOERT_RT0_'/>
<use f='halide/llvm-install/include/llvm/Support/YAMLTraits.h' l='949' c='_ZN4llvm4yaml6detail9doMappingERNS0_2IOERT_RNS0_12EmptyContextE'/>
<use f='halide/llvm-install/include/llvm/Support/YAMLTraits.h' l='957' c='_ZN4llvm4yaml7yamlizeERNS0_2IOERT_bRNS0_12EmptyContextE'/>
<use f='halide/llvm-install/include/llvm/Support/YAMLTraits.h' l='965' c='_ZN4llvm4yaml7yamlizeERNS0_2IOERT_bRNS0_12EmptyContextE'/>
<use f='halide/llvm-install/include/llvm/Support/YAMLTraits.h' l='976' c='_ZN4llvm4yaml7yamlizeERNS0_2IOERT_bRNS0_12EmptyContextE'/>
<use f='halide/llvm-install/include/llvm/Support/YAMLTraits.h' l='997' c='_ZN4llvm4yaml7yamlizeERNS0_2IOERT_bRNS0_12EmptyContextE'/>
<use f='halide/llvm-install/include/llvm/Support/YAMLTraits.h' l='1016' c='_ZN4llvm4yaml7yamlizeERNS0_2IOERT_bRNS0_12EmptyContextE'/>
<use f='halide/llvm-install/include/llvm/Support/YAMLTraits.h' l='1041' c='_ZN4llvm4yaml7yamlizeERNS0_2IOERT_bRT0_'/>
<use f='halide/llvm-install/include/llvm/Support/YAMLTraits.h' l='1067' c='_ZN4llvm4yaml7yamlizeERNS0_2IOERT_bRT0_'/>
<use f='halide/llvm-install/include/llvm/Support/YAMLTraits.h' l='1081' c='_ZN4llvm4yaml7yamlizeERNS0_2IOERT_bRNS0_12EmptyContextE'/>
<use f='halide/llvm-install/include/llvm/Support/YAMLTraits.h' l='1096' c='_ZN4llvm4yaml7yamlizeERNS0_2IOERT_bRNS0_12EmptyContextE'/>
<use f='halide/llvm-install/include/llvm/Support/YAMLTraits.h' l='1110' c='_ZN4llvm4yaml7yamlizeERNS0_2IOERT_bRNS0_12EmptyContextE'/>
<use f='halide/llvm-install/include/llvm/Support/YAMLTraits.h' l='1116' c='_ZN4llvm4yaml7yamlizeERNS0_2IOERT_bRT0_'/>
<use f='halide/llvm-install/include/llvm/Support/YAMLTraits.h' l='1270' c='_ZN4llvm4yaml23ScalarEnumerationTraitsINS_7support6detail31packed_endian_specific_integralIT_XT0_EXT1_EXsr13PickAlignmentIS5_XT1_EEE5valueEEENSt9enabl4134484'/>
<use f='halide/llvm-install/include/llvm/Support/YAMLTraits.h' l='1285' c='_ZN4llvm4yaml18ScalarBitSetTraitsINS_7support6detail31packed_endian_specific_integralIT_XT0_EXT1_EXsr13PickAlignmentIS5_XT1_EEE5valueEEENSt9enable_ifI9848273'/>
<use f='halide/llvm-install/include/llvm/Support/YAMLTraits.h' l='1296' c='_ZN4llvm4yaml20MappingNormalizationC1ERNS0_2IOERT0_'/>
<use f='halide/llvm-install/include/llvm/Support/YAMLTraits.h' l='1319'/>
<use f='halide/llvm-install/include/llvm/Support/YAMLTraits.h' l='1328' c='_ZN4llvm4yaml24MappingNormalizationHeapC1ERNS0_2IOERT0_PNS_20BumpPtrAllocatorImplINS_15MallocAllocatorELm4096ELm4096ELm128EEE'/>
<use f='halide/llvm-install/include/llvm/Support/YAMLTraits.h' l='1356'/>
<ovr f='halide/llvm-install/include/llvm/Support/YAMLTraits.h' l='1373' c='llvm::yaml::Input'/>
<use f='halide/llvm-install/include/llvm/Support/YAMLTraits.h' l='1373'/>
<ovr f='halide/llvm-install/include/llvm/Support/YAMLTraits.h' l='1536' c='llvm::yaml::Output'/>
<use f='halide/llvm-install/include/llvm/Support/YAMLTraits.h' l='1536'/>
<use f='halide/llvm-install/include/llvm/Support/YAMLTraits.h' l='1910' c='_ZN4llvm4yaml18SequenceTraitsImpl4sizeERNS0_2IOERT_'/>
<use f='halide/llvm-install/include/llvm/Support/YAMLTraits.h' l='1912' c='_ZN4llvm4yaml18SequenceTraitsImpl7elementERNS0_2IOERT_m'/>
<use f='halide/llvm-install/include/llvm/Support/YAMLTraits.h' l='1963' c='_ZN4llvm4yaml35StdMapStringCustomMappingTraitsImpl8inputOneERNS0_2IOENS_9StringRefERSt3mapINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEET_St4le13306843'/>
<use f='halide/llvm-install/include/llvm/Support/YAMLTraits.h' l='1967' c='_ZN4llvm4yaml35StdMapStringCustomMappingTraitsImpl6outputERNS0_2IOERSt3mapINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEET_St4lessISA_ESaISt4pairIKSA_SB_EEE'/>
<size>16</size>
<doc f='halide/llvm-install/include/llvm/Support/YAMLTraits.h' l='750'>// Base class for Input and Output.</doc>
<fun r='_ZN4llvm4yaml2IOC1EPv'/>
<fun r='_ZN4llvm4yaml2IOD1Ev'/>
<fun r='_ZNK4llvm4yaml2IO10outputtingEv'/>
<fun r='_ZN4llvm4yaml2IO13beginSequenceEv'/>
<fun r='_ZN4llvm4yaml2IO16preflightElementEjRPv'/>
<fun r='_ZN4llvm4yaml2IO17postflightElementEPv'/>
<fun r='_ZN4llvm4yaml2IO11endSequenceEv'/>
<fun r='_ZN4llvm4yaml2IO21canElideEmptySequenceEv'/>
<fun r='_ZN4llvm4yaml2IO17beginFlowSequenceEv'/>
<fun r='_ZN4llvm4yaml2IO20preflightFlowElementEjRPv'/>
<fun r='_ZN4llvm4yaml2IO21postflightFlowElementEPv'/>
<fun r='_ZN4llvm4yaml2IO15endFlowSequenceEv'/>
<fun r='_ZN4llvm4yaml2IO6mapTagENS_9StringRefEb'/>
<fun r='_ZN4llvm4yaml2IO12beginMappingEv'/>
<fun r='_ZN4llvm4yaml2IO10endMappingEv'/>
<fun r='_ZN4llvm4yaml2IO12preflightKeyEPKcbbRbRPv'/>
<fun r='_ZN4llvm4yaml2IO13postflightKeyEPv'/>
<fun r='_ZN4llvm4yaml2IO4keysEv'/>
<fun r='_ZN4llvm4yaml2IO16beginFlowMappingEv'/>
<fun r='_ZN4llvm4yaml2IO14endFlowMappingEv'/>
<fun r='_ZN4llvm4yaml2IO15beginEnumScalarEv'/>
<fun r='_ZN4llvm4yaml2IO15matchEnumScalarEPKcb'/>
<fun r='_ZN4llvm4yaml2IO17matchEnumFallbackEv'/>
<fun r='_ZN4llvm4yaml2IO13endEnumScalarEv'/>
<fun r='_ZN4llvm4yaml2IO17beginBitSetScalarERb'/>
<fun r='_ZN4llvm4yaml2IO11bitSetMatchEPKcb'/>
<fun r='_ZN4llvm4yaml2IO15endBitSetScalarEv'/>
<fun r='_ZN4llvm4yaml2IO12scalarStringERNS_9StringRefENS0_11QuotingTypeE'/>
<fun r='_ZN4llvm4yaml2IO17blockScalarStringERNS_9StringRefE'/>
<fun r='_ZN4llvm4yaml2IO9scalarTagERNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE'/>
<fun r='_ZN4llvm4yaml2IO11getNodeKindEv'/>
<fun r='_ZN4llvm4yaml2IO8setErrorERKNS_5TwineE'/>
<fun r='_ZN4llvm4yaml2IO19setAllowUnknownKeysEb'/>
<fun r='_ZN4llvm4yaml2IO8enumCaseERT_PKcS2_'/>
<fun r='_ZN4llvm4yaml2IO8enumCaseERT_PKcj'/>
<fun r='_ZN4llvm4yaml2IO12enumFallbackERT0_'/>
<fun r='_ZN4llvm4yaml2IO10bitSetCaseERT_PKcS2_'/>
<fun r='_ZN4llvm4yaml2IO10bitSetCaseERT_PKcj'/>
<fun r='_ZN4llvm4yaml2IO16maskedBitSetCaseERT_PKcS2_S2_'/>
<fun r='_ZN4llvm4yaml2IO16maskedBitSetCaseERT_PKcjj'/>
<fun r='_ZNK4llvm4yaml2IO10getContextEv'/>
<fun r='_ZN4llvm4yaml2IO10setContextEPv'/>
<fun r='_ZN4llvm4yaml2IO11mapRequiredEPKcRT_'/>
<fun r='_ZN4llvm4yaml2IO11mapRequiredEPKcRT_RT0_'/>
<fun r='_ZN4llvm4yaml2IO11mapOptionalEPKcRT_'/>
<fun r='_ZN4llvm4yaml2IO11mapOptionalEPKcRT_RKT0_'/>
<fun r='_ZN4llvm4yaml2IO22mapOptionalWithContextEPKcRT_RT0_'/>
<fun r='_ZN4llvm4yaml2IO22mapOptionalWithContextEPKcRNS_8OptionalIT_EERT0_'/>
<fun r='_ZN4llvm4yaml2IO22mapOptionalWithContextEPKcRT_RT0_'/>
<fun r='_ZN4llvm4yaml2IO22mapOptionalWithContextEPKcRT_RKT1_RT0_'/>
<fun r='_ZN4llvm4yaml2IO21processKeyWithDefaultEPKcRNS_8OptionalIT_EERKS6_bRT0_'/>
<fun r='_ZN4llvm4yaml2IO21processKeyWithDefaultEPKcRT_RKS4_bRT0_'/>
<fun r='_ZN4llvm4yaml2IO10processKeyEPKcRT_bRT0_'/>
<mbr r='llvm::yaml::IO::Ctxt' o='64' t='void *'/>
<fun r='_ZN4llvm4yaml2IO21processKeyWithDefaultEPKcRNS_8OptionalIT_EERKS6_bRT0_'/>
