<use f='halide/src/autoschedulers/adams2019/AutoSchedule.cpp' l='453' u='m' c='_ZN6Halide8Internal13Autoscheduler21optimal_schedule_passERNS1_11FunctionDAGERKSt6vectorINS0_8FunctionESaIS5_EERKNS_13MachineParamsEPNS_9CostModelERSt14755906'/>
<use f='halide/src/autoschedulers/adams2019/retrain_cost_model.cpp' l='172' u='m' c='_ZN12_GLOBAL__N_112load_samplesERKNS_5FlagsE'/>
<use f='halide/src/autoschedulers/adams2019/retrain_cost_model.cpp' l='174' u='a' c='_ZN12_GLOBAL__N_112load_samplesERKNS_5FlagsE'/>
